### ISSUE TITLE
Modifications for Ubuntu 17.10 support..

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#1]
Hi,
nice project..
just testing and it fails on Ubuntu 17.10..
some notes:

1. have to change build-win64.txt file to using gcc and g++ posix variants:
c = '/usr/bin/x86_64-w64-mingw32-gcc-posix'
cpp = '/usr/bin/x86_64-w64-mingw32-g++-posix'
if not have issues with std::mutex not defined etc.. seems related to thread support varying between posix and win32 modes..

2. Ubuntu 17.10 seems it includes mingw g++ version 6.2 so optional header isn't avaiable have to change to:
#include <experimental/optional>
also std::experimental::optional..

3. you should point to use Wine staging for Vulkan support..

**Comment by doitsujin** [comment]
1. Does adding ```-pthread``` as a compiler option work as well? The mingw packages I'm using on my Arch Linux don't have the ```-posix``` binaries. It does ship with mingw-gcc version 7.2 though.

2. Since this is only used in very few places I might just rewrite the code without using optional.

3. You're right, added that to the README.

**Comment by oscarbg** [comment]
will try if -pthread fixes it..

**Comment by oscarbg** [comment]
doesn't help..
tested with "-pthread','-lpthread','-lssl','-lcrypto" everywhere..

[properties]
c_args = ['-Og', '-ggdb','-pthread','-lpthread','-lssl','-lcrypto']
c_link_args = ['-static', '-static-libgcc','-pthread','-lpthread','-lssl','-lcrypto']

cpp_args = ['-std=c++17', '-Og', '-gstabs','-pthread','-lpthread','-lssl','-lcrypto']
cpp_link_args = ['-static', '-static-libgcc', '-static-libstdc++','-pthread','-lpthread','-lssl','-lcrypto']

and still get 
"error: ‘mutex’ in namespace ‘std’ does not name a type"

**Comment by bog-dan-ro** [comment]
Check https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=757259 to see how to switch to pthread

**Comment by oscarbg** [comment]
thanks @bog-dan-ro ..
I now switched to Ubuntu 18.04dev with mingw gcc 7.2 by default and with 
update-alternatives --config x86_64-w64-mingw32-gcc
update-alternatives --config x86_64-w64-mingw32-g++
to posix variants it works with no code changes!
so closing it..

**Comment by rzyghul** [comment]
Just a note - On Kali additionally to oscarbg change required on ubuntu with x86_64-w64-mingw32-gcc/g++ you also need switching wingw to posix for environment targeting Win32:
update-alternatives --config i686-w64-mingw32-gcc
update-alternatives --config i686-w64-mingw32-g++
