### ISSUE TITLE
Issue 1000

### ISSUE THREAD

**Issue by rphsoftware** [doitsujin/dxvk#1000]
:frog: :tada: :ok_hand: :rocket:

**Comment by Leopard1907** [comment]
🐸

**Comment by doitsujin** [comment]
![a143064-0](https://user-images.githubusercontent.com/25567304/55651052-ae02ed00-57e7-11e9-9d70-35b3153a7fa4.png)
for opening the **most valuable bug report** on this tracker.

I'm genuinely impressed what people come up with these days.
