### ISSUE TITLE
High values of mouse polling rate cause severe stuttering when moving the camera

### ISSUE THREAD

**Issue by Zeioth** [doitsujin/dxvk#1001]
When the mouse works with a polling rate of more than 125hz, games show severe stuttering and high frametimes, ONLY when the player move the camera. Everything else seem to run smooth.

### Affect the next games

* **Sekiro**: Polling rate 1000, or 500 cause frametimes spikes and stuttering when the player move the camera. Polling rate 125 fixes the issue.
* **Quake Champions**:  Polling rate 1000 cause frametimes spikes and stuttering when the camera move quickly. Polling rate 125 fixes the issue.
* **The witcher 3**: Polling rate 1000 cause frametimes spikes when the camera move too fast, but it doesn't produce stuttering. Polling rate 125 fixes the issue.
* **Doom 2016**: Polling rate 1000 cause frametimes spikes and stuttering when the camera move too fast. Polling rate 125 or 500 fixes the issue.

### It doesn't affect the next games
* **Bioshock: Infinite**: Linux native OpenGL game. Runs perfect with any polling rate.
* **Portal 1**: Linux native OpenGL game. Runs perfect with any polling rate.
* **Nier: Automata**: Runs perfect with any polling rate. Maybe because the camera move extremely slow.

### Other people reporting this bug:
[Ultimate Doom FPS drops with higher mouse polling rate.](https://github.com/ValveSoftware/Proton/issues/1534)
[High polling mouse causes stutter in editor.](https://forum.unity.com/threads/high-polling-mouse-causes-stutter-in-editor-solved.632338/)

### How to reproduce
In the game 'Sekiro', press the physical DPI button of your mouse, and move the camera.

### System information
- Distro: Arch antergos XFCE
- Kernel: Linux 5.0.5.arch1-1
- GPU: Ryzen 1700
- Driver: 418.49.4
- Wine version: 4.5-tkg
- DXVK version: Tested with master and 1.0.2, but probably affects all the other versions.
- Mouse: BenQ Zowie EC2-A

**Comment by libcg** [comment]
This is not necessarily a DXVK issue. Did you try on Windows?

**Comment by Joshua-Ashton** [comment]
I have a kernel issue, please fix it in your graphics library!

**Comment by Zeioth** [comment]
Not necessarily, but I want to hear doitsujin opinion about the issue. Worst case scenario, we'll find out the right place to report it.

**Comment by Zeioth** [comment]
Relevant for testers:
![relevant](https://user-images.githubusercontent.com/3357792/55662143-55484a00-5811-11e9-9ca5-3102db0e9d72.png)

**Comment by Zeioth** [comment]
I've been able to reproduce it in Doom 2016, which doesn't use DXVK. So most likely is a Wine issue. Any recommendation to make this reach the right eyes?

**Comment by Joshua-Ashton** [comment]
> So most likely is a Wine issue.

Testing a few (true) native games would be a good idea here.

**Comment by doitsujin** [comment]
I don't really see the point in reporting this here at all, especially if Doom is affected. It's not like there's `if (mousePollingRate > 125) makeEverythingSlow` in my code.

Please report this on the proton bug tracker.

**Comment by Zeioth** [comment]
Issue moved to Proton:
https://github.com/ValveSoftware/Proton/issues/2455

And Wine:
https://forum.winehq.org/viewtopic.php?f=8&t=32235
