### ISSUE TITLE
DXVK 1.1 breaks gamma

### ISSUE THREAD

**Issue by grigi** [doitsujin/dxvk#1003]
Gamma adjustment is broken again with DXVK 1.1
Works in 1.0.1 and 1.0.2 (and 0.96 and older)

Issue is the same as https://github.com/doitsujin/dxvk/issues/937#issuecomment-471330437

### Software information
Witcher 3 — Proton 4.2 — DXVK 1.1

### System information
- GPU: Intel UHD620
- Driver: AMV from mesa git
- Wine version: Wine 4.2 bundles with Proton 4.2-2
- DXVK version: DXVK 1.1
- OS: Gentoo Linux, 5.0.5, KDE5 desktop with compositing disabled.

**Comment by doitsujin** [comment]
You're right, and I **did** test this a million times and it was working just fine.
