### ISSUE TITLE
Game lock up!  VK_ERROR_DEVICE_LOST

### ISSUE THREAD

**Issue by Lee02** [doitsujin/dxvk#1006]
### System information
- GPU:GTX970
- Windows Driver:419.17
- Linux Driver:Linux 418.49.04
- Wine version: 4.0
- DXVK version: 1.0-lastversion

ubuntu and windows all have this Question!so Apitrace in windows.
ubuntu and windows all have this Question!so Apitrace in windows.
ubuntu and windows all have this Question!so Apitrace in windows.

sorry! my english bad!

thx!

Question:game lock up! 

err:   DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
err:   DxvkDevice: Command buffer submission failed: VK_ERROR_DEVICE_LOST
err:   DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
err:   DxvkDevice: Command buffer submission failed: VK_ERROR_DEVICE_LOST
err:   DxvkDevice: Command buffer submission failed: VK_ERROR_DEVICE_LOST

### Apitrace file(s)
RenderDoc log!

https://raw.githubusercontent.com/Lee02/dxvk/master/RenderDoc_2019.04.08_20.59.48.log

dxvk log:
https://github.com/Lee02/dxvk/blob/master/GujianOL_d3d11.log
https://github.com/Lee02/dxvk/blob/master/GujianOL_dxgi.log

**Comment by Joshua-Ashton** [comment]
What game?

**Comment by doitsujin** [comment]
can't really do much without even knowing what game you mean.

**Comment by yagomont** [comment]
After seeing some of your submitted issues here:
I very much suggest improving your English skills.

Otherwise, it gets hard to know what is the issue.
You are right on trying to help, keep up the work.
