### ISSUE TITLE
DXVK 1.1 removed?

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#1008]

**Comment by Bfgeshka** [comment]
I believe it had serious bug and there was a warning about it in the header of release notes for 1.1.

**Comment by doitsujin** [comment]
Yes, there were serious issues with people getting GPU hangs and crashes. Still haven't figured out why, or how to reproduce it, but to avoid shipping this to a wider audience (esp. Lutris, which pulls releases directly from github) it was removed.
