### ISSUE TITLE
X-Men origins: Wolverine

### ISSUE THREAD

**Issue by legluondunet** [doitsujin/dxvk#1011]
### Software information
X-Men origins: Wolverine

### System information
- GPU: NVIDIA GeForce GTX 770
- Driver: Nvidia drivers 418.56
- Wine version: 4.5-staging
- DXVK version: 1.0.2

### Apitrace file(s)
No crash

### Log files
[Wolverine_dxgi.log](https://github.com/doitsujin/dxvk/files/3074634/Wolverine_dxgi.log)
[Wolverine_d3d11.log](https://github.com/doitsujin/dxvk/files/3074635/Wolverine_d3d11.log)
The file Wolverine_d3d10.log is empty

Hello,
you can launch this game in DirectX10 mode if you change in WEngine.ini file this line:
AllowD3D10=False
to true

Issues:
- Very long time to load the first time I launched game
- invisible main menu
- Wolverine and others characters have no skin (cf picture)

**Comment by legluondunet** [comment]
DirectX9:
![Capture d’écran de 2019-04-12 20-15-47](https://user-images.githubusercontent.com/325405/56057718-d34fa800-5d5f-11e9-9778-b1dbf7cf8266.png)
DirectX10 DXVK:
![Capture d’écran de 2019-04-12 20-04-46](https://user-images.githubusercontent.com/325405/56057735-e4001e00-5d5f-11e9-99fb-0324663a2c87.png)
Characters have no skin:
![Capture d’écran de 2019-04-12 19-56-32](https://user-images.githubusercontent.com/325405/56057779-fb3f0b80-5d5f-11e9-93d7-a7290091b975.png)

**Comment by doitsujin** [comment]
I cannot provide support for unofficial render paths that some games may have. This is almost certainly a bug with the D3D10 renderer, not DXVK, there's a reason why the game uses D3D9 by default.

Also, no apitrace -> can't debug.
