### ISSUE TITLE
Battle.net App VK_ERROR_MEMORY_MAP_FAILED

### ISSUE THREAD

**Issue by waaagh313ph4n7** [doitsujin/dxvk#1013]
The Battle.net app fills up all available memory (of 16gb total) seconds after launching, causing numerous VK_ERROR_MEMORY_MAP_FAILED errors and system freeze. This happens both with latest git versions of mesa/llvm/dxvk as well as older combinations that used to work, so I'm assuming something changed in the latest Battle.net updated to cause it.

### Software information
Battle.net 1.13.2.11060

### System information
- GPU: AMD Radeon R7 370 
- Driver: mesa-git  109802.6279074de18
- Wine version: wine-staging  4.5
- DXVK version: dxvk-git  1.0.1.r99.g522fa8d7

### Log files
- d3d11.log: [Battle.net_d3d11.log](https://github.com/doitsujin/dxvk/files/3077314/Battle.net_d3d11.log)
- dxgi.log: [Battle.net_dxgi.log](https://github.com/doitsujin/dxvk/files/3077315/Battle.net_dxgi.log)

**Comment by arzardk** [comment]
I'm just wondering, but If you think this is the problem with Battle.net, why are you creating issue here and not in the Battle.net github?

**Comment by doitsujin** [comment]
Can't reproduce, works fine for me using Mesa 19.0, RX 480, Kernel 5.0.

**Comment by waaagh313ph4n7** [comment]
Thanks, I tried that but for some reason could not get the games working while Battle.net itself was running without DXVK. Anyway I did a clean install of my system and all is working fine again. Must have been something else that was broken, but I only noticed it in that instance. Very strange.
