### ISSUE TITLE
Divinity: Original Sin 2 - Definitive Edition  (Steam AppID 435150)

### ISSUE THREAD

**Issue by Bamsey** [doitsujin/dxvk#1014]
Dramatically drop FPS (7-11fps) after QuickSaveGame or SaveGame. After that only game restart helps (Alt+Tab sometimes)

### Software information
Divinity: Original Sin 2 - Definitive Edition  (Steam AppID 435150)

### System information
- GPU:GTX950M or INTEL HD530
- Driver:nvidia 418. 56 / Mesa 19.0.1
- Wine version: 4.6 Stagging
- DXVK version: 1.0.2

### Apitrace file(s)

[SupportTool.trace.zip](https://github.com/doitsujin/dxvk/files/3077578/SupportTool.trace.zip)

### Log files
- d3d11.log:
[SupportTool_d3d11.log](https://github.com/doitsujin/dxvk/files/3077571/SupportTool_d3d11.log)

- dxgi.log: [SupportTool_dxgi.log](https://github.com/doitsujin/dxvk/files/3077572/SupportTool_dxgi.log)

[steam-435150.log](https://github.com/doitsujin/dxvk/files/3077573/steam-435150.log)

**Comment by doitsujin** [comment]
Does this problem also occur with wined3d?

Also, your apitrace is basically empty. What's `SupportTool.exe` anyway? Doesn't sound like a game executable.

**Comment by Bamsey** [comment]
No. Only DXVK. 
With parameters PROTON_USE_WINED3D=1 works fine, but performance is poor.

**Comment by Bamsey** [comment]
About Your question:

mv bin bin.bak
ln -s DefEd\bin bin
cd bin
mv SupportTool.exe SupportTool.bak
ln -s EoCApp.exe SupportTool.exe

without this manipulation, the game does not start

**Comment by doitsujin** [comment]
Looking at [ProtonDB](https://www.protondb.com/app/435150) entries for this game, it seems that this issue is specific to your setup. Not really sure what to m

Anyway, can't debug that right now until I get my hands on that game, but chances are **very** high that I won't be able to reproduce this at all.

**Comment by Bamsey** [comment]
I'm not the only one with a problem: 
https://www.reddit.com/r/SteamPlay/comments/a1ytqd/divinity_original_sin_2_audio_issues_fps_drops/

I prepared the dxvk.conf file and put it in the folder with the game file. I set suggested parameters. Problem still occure.

Thx.

**Comment by doitsujin** [comment]
The person on Reddit wasn't using DXVK, which indicates that this isn't really my bug. No idea **what** is causing it though.

**Comment by Bamsey** [comment]
I see. 
Anyway, thank you for trying to help.

**Comment by Bamsey** [comment]
From my observation that the problem may have something to do with rendering shadows. As suggested by one of the players, lowering the quality of shadows reduces the number of fps drops

**Comment by doitsujin** [comment]
That a) doesn't really help since I don't know how the game renders shadows, and b) doesn't really explain why it only happens after a save.

What does `DXVK_HUD=memory` show? There's a chance you're running out of VRAM.

**Comment by Bamsey** [comment]
FYI

![after_save](https://user-images.githubusercontent.com/49482051/56117587-afab7e00-5f68-11e9-82bb-7f70c23c9e88.png)
![before_save](https://user-images.githubusercontent.com/49482051/56117588-afab7e00-5f68-11e9-80f7-bf592faa1a00.png)

**Comment by K0bin** [comment]
How much VRAM does your 950m have?

**Comment by doitsujin** [comment]
According to the DXGI log it's 2GB, which.... is a bit questionable, since neither DXVK nor the Nvidia driver have great memory management and background apps (browser, compositor etc.) eat some of that as well. I wonder if lowering texture and shadow quality fixes things for you.

**Comment by Bamsey** [comment]
Yes, I have 2048/5Ghz,  and yes, lowering the texture quality helps for a while.

**Comment by Bamsey** [comment]
Thanks guys. Conclusion - replacement of equipment, or playing on low settings.
