### ISSUE TITLE
Ignore missing .dlls in setup_dxvk.sh

### ISSUE THREAD

**Issue by moll** [doitsujin/dxvk#1015]
Hey,

I was upgrading the DXVK DLLs in some old wineprefixes of mine and noticed it constantly failed because the original d3d10.dll et alii were missing — either because the previous installer scripts didn't back them up OR because Lutris, a game manager for Linux, impolitely forced its own DXVK versions and didn't back the originals up. That wouldn't be a problem if `setup_dxvk.sh` didn't insist on them having to exist before symlinking/installing the DXVK variants: https://github.com/doitsujin/dxvk/blob/044e3967e7a74c8843d4142a64b5194f9320a4ea/setup_dxvk.sh#L109

I propose their prior existence be made optional. 

Cheers

**Comment by SveSop** [comment]
The `setup_dxvk.sh` changed a little while back, and if you have a wineprefix with a previous dxvk install your best bet is to manually uninstall stuff/remove dll redirects, and reinstall using the current script. 

I do not think it warrants a script change for it, but i guess if its a simple change that does not crud the function im sure someone will listen :)

PS. I did try to ask something similar when the script changed, but ended up giving up the argument and learned to live with "the new way"...

**Comment by moll** [comment]
Well, I think it's also buggy given that my prefixes had that file as symlinks, yet the symlinks referred to nonexistent files. That's because `-f` follows symlinks. I'd claim that the existence check has no practical use. ;)

**Comment by Sebastiangperez** [comment]
Im still using the verb setup file for winetricks from early versions

**Comment by doitsujin** [comment]
Sorry for not responding earlier - this should be fixed these days since we run `wineboot -u` on the prefix during the setup to restore the old DLLs.
