### ISSUE TITLE
DXVK with Wine on macOS?

### ISSUE THREAD

**Issue by The-SamminAter** [doitsujin/dxvk#1017]
Since Wine for macOS supports Vulkan via MoltenVK, could DXVK somehow be used with Wine to run DX10/11 Windows games on macOS?

**Comment by K0bin** [comment]
There's an issue on the MoltenVK bug tracker about this: https://github.com/KhronosGroup/MoltenVK/issues/203

tl;dr: Metal doesn't support all Vulkan features that DXVK relies on.

**Comment by cdavis5e** [comment]
Also, at least one upcoming port of ours (CodeWeavers') will use DXVK to support D3D11 graphics on Mac.

**Comment by The-SamminAter** [comment]
In the future would is it likely to be able to play DX10/11 games on macOS with MoltenVK and DXVK with Wine?

**Comment by The-SamminAter** [comment]
In the future is it likely that Wine will be able to play DX10/11 games on macOS (with MoltenVK and DXVK)?

**Comment by K0bin** [comment]
There might be some games that work but a lot of them probably rely on features that MoltenVK cant implement.

**Comment by UInt2048** [comment]
@doitsujin According to the aforementioned KhronosGroup/MoltenVK#203, CodeWeavers has made some customisation to DXVK or something to allow DirectX11 to work in CrossOver 20. Do you think there is any possibility for macOS now?

**Comment by K0bin** [comment]
> Do you think there is any possibility for macOS now?

I think all CW did was disable a few hard requirements of DXVK.
FWIW there are still a lot of issues with it like the lack of geometry shaders.

Aside from that, I don't think anyone is willing to maintain Mac OS support in DXVK considering you'd have to buy Apple hardware first.

**Comment by Joshua-Ashton** [comment]
I am never touching that shitty platform again.

If someone wants to maintain support for that they are welcome to pull request genuine fixes. I'd rather not us have hacks that will only work in games specifically designed for it though.

**Comment by doitsujin** [comment]
CW have their own fork of DXVK that works around MVK's lack of features. There won't be official support for it in upstream DXVK since none of us here use, or care about, Mac OS X. It's nice that it works, though.

**Comment by mozo78** [comment]
I don't want to offend anyone but I think macOS don't deserve DXVK support. Don't use Apple's shitty hardware and software - problem solved.

**Comment by SteveGremory** [comment]
well this has certainly changed, the M1 Max macs that released yesterday promise good performance and it'd be a huge waste to let it rot just like that, no?
