### ISSUE TITLE
Subnautica: Crash during level loading

### ISSUE THREAD

**Issue by hlarsen** [doitsujin/dxvk#102]
### Software information
Subnautica

using -force-d3d11 and dxvk  crashes when loading a game (new or existing), however the main menu that includes water effects loads and runs...

wined3d loads but has problems with (at least) some missing textures (unplayable)
opengl loads but has issues with flickering textures, but is playable

### System information
- GPU: GTX 960
- Driver: 384.11
- Wine version: 2.21-staging
- DXVK version: ced02ba

### Apitrace file(s)
- working on it, will update the issue if i can get it working

### Log files
- d3d11.log: [Subnautica_d3d11.log](https://github.com/doitsujin/dxvk/files/1756929/Subnautica_d3d11.log)

- dxgi.log: [Subnautica_dxgi.log](https://github.com/doitsujin/dxvk/files/1756932/Subnautica_dxgi.log)

**Comment by volca02** [comment]
this is probably related to #93 

```
err:   D3D11Device: CheckFeatureSupport: Unknown feature: 10
err:   D3D11Device::CreateBuffer: D3D11_BIND_STREAM_OUTPUT not supported
err:   DxbcCompiler: Invalid sampled type: DxbcResourceReturnType::Mixed
err:   D3D11Device::CreateGeometryShaderWithStreamOutput: Not implemented
err:   D3D11DeviceContext::SOSetTargets: Not implemented
```

There are also reports of unsupported formats: DXGI_FORMAT_B4G4R4A4_UNORM (115) and DXGI_FORMAT_FORCE_UINT (4294967295)

**Comment by Thaodan** [comment]
>`DXGI_FORMAT_B4G4R4A4_UNORM` should be supported since today, and  
`DXGI_FORMAT_FORCE_UINT` is not even a valid format.

Its kinda one see here:

https://msdn.microsoft.com/en-us/library/windows/desktop/bb173059(v=vs.
85).aspx

**Comment by hlarsen** [comment]
confirming i'm no longer seeing

> err:   DxgiAdapter: No format mapping for DXGI_FORMAT_B4G4R4A4_UNORM

or

> err:   D3D11: Unsupported format: 115

in the logs using 43b7e84.

**Comment by volca02** [comment]
@Thaodan it's in the enum just to force correct enum size (in bits), I think.

**Comment by doitsujin** [comment]
@Thaodan quoting from that exact page:

> DXGI_FORMAT_FORCE_UINT
Forces this enumeration to compile to 32 bits in size. Without this value, some compilers would allow this enumeration to compile to a size other than 32 bits. This value is not used.

So if a game actually tries to use it for anything (maybe other than format support queries), that's an engine bug.

**Comment by volca02** [comment]
And it still does, even after DXGI_FORMAT_B4G4R4A4_UNORM was fixed.

```
err:   D3D11: Unsupported format: 4294967295
```

There are couple 'Unknown interface query' errors before this, though, so we don't know if this not just a side effect of those.

**Comment by doitsujin** [comment]
> `err:   D3D11Device: CheckFeatureSupport: Unknown feature: 10`

That's not really an issue, and the remaining messages are related to stream output (#135), so I'll close this for now.
