### ISSUE TITLE
Provide dxvk.conf as part of the repository

### ISSUE THREAD

**Issue by loathingKernel** [doitsujin/dxvk#1020]
Would it be possible to provide the dxvk.conf sample file as part of the repository and the release tarball? This would help packagers to provide a system-wide sample file in their respective packages for users to diff on version updates or copy it from a default location in their system.

**Comment by npour** [comment]
The configuration file is normally loaded from the working directory. I don't there there is a point to there being a sample file provided since the configuration file typically only contains a few game specific settings.

**Comment by Kreyren** [comment]
if it helps someone with contrib to project and using dxvk why not? Note that sample is present on https://github.com/doitsujin/dxvk/wiki/Configuration

**Comment by loathingKernel** [comment]
My use-case with this is that I use custom scripts to launch wine games which set up the environment. As such I point the env variables to locations and the dxvk.conf outside the wine prefix or the game dir depending of the script used. So, I would like to have a skeleton file there in case I would like to edit it and I need to copy it from somewhere. It also helps to have the file as it is somewhere, to be able to diff and update it on version updates if it required. Right now, for the d9vk packages I maintain, I have to clone the dxvk.wiki and do some ugly sed-fu to strip the file from the unneeded stuff in Configuration.md.

**Comment by doitsujin** [comment]
Not the worst idea in the world, I guess this is also less annoying to maintain than the wiki page as an example config file.
