### ISSUE TITLE
Metro: Exodus does not start if wineprefix was created with wine 4.x

### ISSUE THREAD

**Issue by mittorn** [doitsujin/dxvk#1024]
When using wineprefix created in wine-3.13, game starts in all used wine versions (3.13, 4.0, 4.4, 4.6), No sound in 4.4, it seems to be wine bug
On clean wineprefix with dxvk installed (i tried with and without dxgi), it hangs before tries create context, so no log created
Game starts successfully without dxvk installed (using wined3d implementation) on clean wineprefix

https://pastebin.com/jC1gFFVf

### Software information
Metro: Exodus

### System information
- GPU: Ryzen 5 2400G (AMD RAVEN, Vega 11)
- Driver: amdvlk from amdgpu-pro
- Wine version: 3.13, 4.0, 4.4, 4.6
- DXVK version: 1.0.3

### Apitrace file(s)
No d3d11 calls was made

### Log files
Not created

**Comment by doitsujin** [comment]
If no log is created, DXVK doesn't even get loaded. This must be an issue somewhere in your setup.

**Comment by acedogblast** [comment]
Metro: Exodus works for me using Lutris with tkg-4.5 and DXVK 1.0.3.

**Comment by mittorn** [comment]
But just installing dxvk on 4.x breaks it. Without dxvk installed it runs normally (except graphics issues). It seems to be a wine issue, but it only happens when installing dxvk, so i reported here

**Comment by mittorn** [comment]
@ acedogblast 
> Metro: Exodus works for me using Lutris with tkg-4.5 and DXVK 1.0.3.
Does text in main menu, tablet and on-hand display draw correctly?

**Comment by eugenydn** [comment]
> But just installing dxvk on 4.x breaks it. Without dxvk installed it runs normally (except graphics issues). It seems to be a wine issue, but it only happens when installing dxvk, so i reported here

Same for me.

**Comment by acedogblast** [comment]
@mittorn have you used DXVK before in other games? Can you also post the console output of wine?

**Comment by mittorn** [comment]
I tried to launch risk of rain 2 in wine 3.x, but it does not draw player with dxvk (and does not draw almost everything with wined3d)
Now i removed all modern games except metro because lack of free disk space

**Comment by doitsujin** [comment]
> but it does not draw player with dxvk

Your driver probably doesn't support Transform Feedback.

**Comment by mittorn** [comment]
ok, i'll try it again with updated driver, i used old amdvlk from amdgpu-pro before

**Comment by eugenydn** [comment]
With dxvk-win32/64 version it works good. Previously i used winelib version.

**Comment by K0bin** [comment]
That's not related to a 2 year old issue with Metro Exodus. Please open a new issue.
