### ISSUE TITLE
[QUESTION] Will be async patches in future version of DXVK

### ISSUE THREAD

**Issue by t14462** [doitsujin/dxvk#1026]
Some guy made async shader compile patches for DXVK, but it little buggy

So, maybe if Wine Esync merged to staging - DXVK async will be?

**Comment by doitsujin** [comment]
Short version: No.

Long version: It alters rendering without the game being aware of it, which is unacceptable especially in the context of multi-player games. I know it helps some games tremendously, but use it at your own risk.

**Comment by Kerrung** [comment]
@doitsujin But can it be at least possible to add this as a disabled option by default in the configuration file?

> Short version: No.
> 
> Long version: It alters rendering without the game being aware of it, which is unacceptable especially in the context of multi-player games. I know it helps some games tremendously, but use it at your own risk.

**Comment by doitsujin** [comment]
No.
