### ISSUE TITLE
Winelib DXVK crashing configators of bethesda games

### ISSUE THREAD

**Issue by t14462** [doitsujin/dxvk#1029]
Winelib DXVK crashing configators of bethesda games: Fallout 4, Skyrim SE (and probably D9VK oblivion, I'll test it now)

With Fallout New Vegas and F3 - everything OK.

STEPS TO REPRODUCE:

1.Have Mesa AMD RADV driver
2.Build wine with DXVK winelib
3.Start game launcher
4.Press SETTINGS
5.See: wine: Unhandled page fault on read access to 0x00000000 at address 0x14000c5c1 (thread 0035), starting debugger...
Problem on memory acces when app wants to get video capabilities from driver.

It's weird, because games itself works perfect.

On standalone DXVK this bug not appear.

Is it possible to fix it somehow or figure out with workarounds?

**Comment by doitsujin** [comment]
Probably some DLL load order issue. This is also why winelib builds aren't really supported, symlinking them to the DLL names is a dirty hack that doesn't always produce the desired results.

Please use the mingw builds instead.

**Comment by t14462** [comment]
Im using ASYNC flag in Tk-Glitch

So for that I need setup full mingw kitchen and build all components manually.

Force-disabled ASYNC flag does not hurt anybody, and everyone can turn it on in offline games on official builds.

I just cant understand, it's difficult to support that feature or what?..

**Comment by doitsujin** [comment]
> I just cant understand, it's difficult to support that feature or what?..

I explained why this feature is not and will not be supported in DXVK in #1026. If you want to use it, fine, but don't expect me to provide any support for it.

wrt winelib not working, you could try setting `d3d11.dll` and `dxgi.dll` to **builtin** instead of native, since wine tends to treat the winelib .dll.so files as builtin. No gurantee that this will work though.
