### ISSUE TITLE
Star Citizen hangs with WINEESYNC=1

### ISSUE THREAD

**Issue by rawfoxDE** [doitsujin/dxvk#1030]
Star Citizen hangs when esync is enabled.
The game is working, when esync is switched off (default).

In wine-4.6 (staging) esync has been working with StarCitizen.

This patch broke the use of esync:
https://github.com/wine-staging/wine-staging/commit/d8568c947aa346256ec3c94938b50e5e1880208a#comments

### System information
- GPU: 1060/6
- Driver: 418.52.05
- Wine version: 4.7 (staging)
- DXVK version: 1.0.3

### Log files
no logs created due to the game not starting

The game run smoother with esync enabled, even on low fps the performance was noticeable better, so no need to say we would love to have esybc working with StarCitizen :)

**Comment by doitsujin** [comment]
Maybe report the bug to the correct project?

**Comment by rawfoxDE** [comment]
Aww im so sorry to make you busy with this, that was complete wrong here.
My fault, i owe you a beer ^^
