### ISSUE TITLE
Spellforce 3 crashes at startup

### ISSUE THREAD

**Issue by mozo78** [doitsujin/dxvk#1031]
The game crashes at start with DXVK. I tried nviapi hack, older DXVK versions, installing vcredist2013, etc. to no avail. With Wine the game starts just fine and it does work but the ground is black. The apitrace crashes in the main menu but this is far beyond the point DXVK crashes, so I hope it will be of any help. With DXVK the game crashes immediately at start.

### Software information
Spellforce 3 GOG latest version 1.40.

### System information
- GPU: NVIDIA GTX 1080Ti
- Driver: 418.56
- Wine version: 4.7
- DXVK version: 1.0.3

### Apitrace file(s)
https://my.pcloud.com/publink/show?code=XZbLKO7Z0QtKtXnb4tJhtLwnrxNypB1BJaLX

### Log files
- d3d11.log:
https://pastebin.com/NJJVWrKv
- dxgi.log: 
https://pastebin.com/yTafVrzJ
- Wine.log:
https://pastebin.com/i9gUmQzG

**Comment by doitsujin** [comment]
Looks like this game requires `IDXGISurface`, I'll look into it.

**Comment by mozo78** [comment]
Thank you very much :)

**Comment by mozo78** [comment]
Can you give me a compiled build to test it? Thank you :)

**Comment by mozo78** [comment]
I downloadded it from the latest link. Thank you once again, great job, the game runs now!

**Comment by doitsujin** [comment]
Sure: [dxvk-master.tar.gz](https://github.com/doitsujin/dxvk/files/3123936/dxvk-master.tar.gz)

Your apitrace replays correctly on my end with that patch and shows the menu.

**Comment by mozo78** [comment]
Thank you !

**Comment by mozo78** [comment]
Hello doitsujun,
I'm sorry to write here but I don't know how shall I go about it.

In this Steam thread a user claims that 60% of the effects are missing an there is no water:
https://steamcommunity.com/app/311290/discussions/0/133258092254081438/?ctp=3#c1647665620925442473
Since I don't played the game on Windows I don't know how it's supposed to look like. Can we do something about that missing stuff?

**Comment by doitsujin** [comment]
I also don't know how this is supposed to look on Windows. If there are bugs, I'm going to need more info ( and an apitrace that actually reproduces them).

UI fonts are indeed wrong, but that really doesn't look like a DXVK bug.

**Comment by mozo78** [comment]
Yes the fonts bug isn't DXVK related and this bug isn't that important. I already filed a bug a few days ago:
https://bugs.winehq.org/show_bug.cgi?id=47085
From this video I can see the water:
https://youtu.be/wWmVKXJa2u8?t=118
This is the video I recorded with DXVK and the water indeed is missing:
https://youtu.be/XPpGcDGCJLE?t=117

**Comment by mozo78** [comment]
Unfortunately the apitrace crashes the game at Main menu. I tried several times to no avail. I use the apitrace method with putting bin and lib folders to the .exe directory and run:
`bin/apitrace.exe trace -a dxgi SF3ClientFinal.exe`
When I try the recommendet way [here](https://github.com/doitsujin/dxvk/wiki/Common-issues#apitrace) I get this error:
`apitrace: loaded into C:\game\SF3ClientFinal.exe
apitrace: tracing to C:\game\SF3ClientFinal.1.trace
error: unavailable function CreateDXGIFactory`

**Comment by doitsujin** [comment]
I have access to the game now. I wonder how you got it to run at all because it requires Direct2D, and it requires D3D10 state blocks which DXVK doesn't implement (I have an implementation locally though).

Also, how did you manage to get fonts to show up? The main menu renders fine on my end, but no fonts *at all*.

**Comment by mozo78** [comment]
The game runs out-of-the-box for me. No dll overrides or something else, just DXVK. You have to use Wine 4.7 and a high resolution like FullHD in order to have readable fonts. It runs with Wine without DXVK also but is slower and the ground is black.

**Comment by doitsujin** [comment]
Ah, I suppose you were using Wine's D3D10 implementation rather than mine then, it does actually work with that. Anyway, I'll look into the issue(s).

**Comment by mozo78** [comment]
Thank you very much :)
