### ISSUE TITLE
Watch Dogs crash after showing the save's systems

### ISSUE THREAD

**Issue by RavengamerSpace** [doitsujin/dxvk#1032]
When I launch Watch Dogs (Uplay version), the game launch himself but crash after showing the message of how save works.

### Software information
Watch Dogs (Uplay version)

### System information
- GPU: AMD Radeon RX 460 (POLARIS11, DRM 3.27.0, 5.0.7-1-MANJARO, LLVM 8.0.0)
- Driver: Mesa 19.0.2
- Wine version: 4.5-staging
- DXVK version: 1.0.3

### Log files
- d3d11.log: [Watch_Dogs_d3d11.log](https://github.com/doitsujin/dxvk/files/3124147/Watch_Dogs_d3d11.log)
- dxgi.log: [Watch_Dogs_dxgi.log](https://github.com/doitsujin/dxvk/files/3124148/Watch_Dogs_dxgi.log)
- lutris.log: [watch_dogs_crash.log](https://github.com/doitsujin/dxvk/files/3124140/watch_dogs_crash.log)

**Comment by doitsujin** [comment]
Watch Dogs 1 generally works fine with DXVK, make sure you have the Uplay overlay disabled and your wine prefix [configured properly](https://www.protondb.com/app/243470) (i.e. set it to Windows XP).

**Comment by kassindornelles** [comment]
@RavengamerSpace  don't forget to launch the game with the Uplay overlay disabled, it can cause some... trouble.

**Comment by RavengamerSpace** [comment]
Yeah, it's works now.
Thanks
