### ISSUE TITLE
[Tk-Glitch] Can PE libs support in 4.7 fix hackery problems with builtin DXVK winelib?

### ISSUE THREAD

**Issue by t14462** [doitsujin/dxvk#1034]
If DXVK winelib builds is dirty hackery with problems, and its not officially supported...

... Maybe building D9VK/DXVK as PE libs can fix many problems?

Is it possible to make builtin DXVK as PE lib?

**Comment by Joshua-Ashton** [comment]
This is *exactly* what a non-winelib build is.

**Comment by Glog78** [comment]
feel free to adapt this https://github.com/Tk-Glitch/PKGBUILDS/tree/master/wine-tkg-git 
This basically tells you all known to work ways of building dxvk (including builtin libraries). 

An alternative is you might want to checkout this side with different build descriptions for arch packages -> https://aur.archlinux.org/packages/?O=0&SeB=nd&K=dxvk&outdated=&SB=n&SO=a&PP=50&do_Search=Go

**Comment by Joshua-Ashton** [comment]
You should also move your issue here:
https://github.com/Tk-Glitch/PKGBUILDS

This is not the issue tracker for TKG's pkgbuilds.

**Comment by t14462** [comment]
I asked already. I heard news about support for builtin PE libs in Wine 4.7

I was so worried about this idea... and nobody to ask at night, when everyone sleeping. So I asked everyone xD

**Comment by Glog78** [comment]
Check this side -> https://github.com/doitsujin/dxvk

There is an area "manually compiling" and inside of the project there are the following 2 files:
build-wine32.txt and build-wine64.txt. These uses winegcc and create files which you can use instead of the wine default builtins.

**Comment by t14462** [comment]
I building now Tk-Glitch versions of MinGw D9VK + DXVK with patchset

I need patchset. It was only reason why I asking about "Builtin PEs"
