### ISSUE TITLE
Final Fantasy XIII texture issues.

### ISSUE THREAD

**Issue by torbol** [doitsujin/dxvk#1044]
Hair texture problem: 
![Captura de pantalla de 2019-05-06 23-57-41](https://user-images.githubusercontent.com/45130968/57257876-06cddb80-705b-11e9-9bfa-ed7a123f6257.png)
![Captura de pantalla de 2019-05-06 23-58-03](https://user-images.githubusercontent.com/45130968/57257892-0fbead00-705b-11e9-86b2-1fdf8119ad47.png)

Im using Steam native client with:

Proton:4.2-3
Distro:Ubuntu 18.04.2 LTS
Kernel:5.1.0-050100-generic
RAM:16 GB
GPU Driver:4.5 Mesa 19.0.1 - padoka PPA
GPU:Radeon RX 590
CPU:AMD Ryzen 5 2600X Six-Core

**Comment by doitsujin** [comment]
Final Fantasy XIII is a D3D9 game.

**Comment by iWeaker4you** [comment]
D9VK will work..
