### ISSUE TITLE
Dying Light performance regression since DXVK 1.0

### ISSUE THREAD

**Issue by sianhulo** [doitsujin/dxvk#1047]
### Software information
Dying Light (gog version) with the lowest video settings.

### System information
- GPU: AMD HD 7770
- Driver: Mesa 19.0.3
- Wine version:  4.6
- DXVK version: 1.0, 1.0.1, 1.0.2, 1.0.3 (1.1.1 not tested as I don't have mesa 19.1 yet)

What happens in each version is a little different, but the basic is that after going ingame, and after a handful of seconds, the performance sharply declines.

My gpu is underpowered for this game, so there might be no "bug" to fix, but just in case I decided to provide as much informaiton as possible, as the game is perfectly playable on DXVK 0.96.

I want to note that the main menu of this game shows a 3d renderization of our character and some buildings in the distance, but the problem never seems to manifest in this point (left it running several minutes just to make sure) nor in the loading screen for our save. The game starts playable but with lower framerate than normal (45 vs 30 fps) and the performance fast degrades further, in a handful of seconds it goes down to ~18 FPS (the game stops running full speed and there's input lag added) and then keeps going down until it settles at arround 4 FPS, this appears to be a gpu bottleneck as my cpu utilization goes down compared to what I'd have under 0.96. After the problem manifests it persists, so if I go to the main menu the problem is still there and the framerate becomes ~7FPS (compared to what's normally ~90 FPS).

### Log files
- d3d11.log: 
[DyingLightGame_d3d11.log](https://github.com/doitsujin/dxvk/files/3154881/DyingLightGame_d3d11.log)

- dxgi.log:  
[DyingLightGame_dxgi.log](https://github.com/doitsujin/dxvk/files/3154883/DyingLightGame_dxgi.log)

**Comment by doitsujin** [comment]
The problem is most likely that your GPU only has 1GB of VRAM, which isn't enough for DXVK. Bear in mind thst DXVK's memory management isn't as good as that of Windows, so it basically needs more VRAM.

**Comment by sianhulo** [comment]
I understand that, and it might have been missed in all that text, but it was running find up until 0.96. Though, I understand if changes that are needed for the correct behavior of games is what introduced this and as such is not "fixable".

I'll try to run a bisect when I have more time to try and find what commit caused the regression just for the sake of having more information available.

**Comment by sianhulo** [comment]
did the bisect, the commit that caused the problem for me was dfa8524e7352228d3176340112ebc0165967f991

**Comment by doitsujin** [comment]
That was actually supposed to *improve* the situation in low-vram scenarios.... guess that didn't work out in your case.

Anyway, there's nothing wrong with that commit per se, and improving memory-bound performance would be *extremely* hard since it would still require moving Vulkan resources around manually and rebuilding all sorts of stuff on the fly; I'd like to avoid that.

**Comment by sianhulo** [comment]
I guess there's nothing to be done about it, I'll just have to stick with v0.96.

**Comment by sianhulo** [comment]
I guess there's nothing to be done about it, I'll just have to stick with v0.96.
