### ISSUE TITLE
Different rendering results due to different, but valid driver behavior - solvable by DXVK?

### ISSUE THREAD

**Issue by aufkrawall** [doitsujin/dxvk#1050]
Samuel Pitoiset explained to me that at least in this particular shadow map example, differences between drivers are to be expected due to the Vulkan spec:
https://bugs.freedesktop.org/show_bug.cgi?id=109599

Is there the possibility for DXVK to unify the result among drivers in such cases?

**Comment by hakzsam** [comment]
Apps have no way to know the implementation-dependent depth bias values unfortunately.

**Comment by doitsujin** [comment]
@aufkrawall just so happens that I discussed that with Samuel already as well. Right now there's no way at all to address this problem, other than by adding driver hacks which I'm not keen on doing.

It appears that D3D11 wants the scaling factor to be 1 though (i.e. no scaling).

**Comment by hakzsam** [comment]
Maybe we could force the factor to be 1 for DXVK only?
I'm really not a fan of app-specific hacks though...

**Comment by Oschowa** [comment]
Maybe a new vulkan extension, which lets the app specify the depth bias value it wants, would help?

**Comment by aufkrawall** [comment]
Seems this has stalled?

**Comment by doitsujin** [comment]
There's nothing we can do without some sort of Vulkan support.

**Comment by aufkrawall** [comment]
Not intending to nag anyone, but situation seems unchanged with recent mesa git-master (small shadows "missing" vs. native/amdvlk). :(

**Comment by K0bin** [comment]
There's still no way to fix this properly.

**Comment by aufkrawall** [comment]
Ok.

@hakzsam Since the efforts to get it into a clean extension aren't exactly rushing ahead, would it be possible to implement an env variable in RADV to make it calculate depth bias like it does with your patch on the freedesktop tracker? Then at least one wouldn't have to patch Mesa to get correct shadow rendering in DXVK. :)

**Comment by aufkrawall** [comment]
There was https://cgit.freedesktop.org/mesa/mesa/commit/?id=8a47422d9778056b2263d5f253fab49dfed91486

Seems to look ~identical now vs. amdvlk (at least in Hitman 2) :)
![Screenshot_20210226_195442](https://user-images.githubusercontent.com/13510490/109343214-476c9980-786d-11eb-9f32-631c7c12dc6e.png)
![Screenshot_20210226_195226](https://user-images.githubusercontent.com/13510490/109343222-49cef380-786d-11eb-93d6-b98da4fd6617.png)


This probably can be closed now?
