### ISSUE TITLE
Batman: Arkham City GOTY requires CSGetUnorderedAccessViews

### ISSUE THREAD

**Issue by roothorick** [doitsujin/dxvk#106]
### Software information
Game crashes at the tail end of the Nvidia logo, presenting an error dialog with a stacktrace. Trace is also output to console: https://pastebin.com/juWJdNtt

Shortly before the crash, `err:   D3D11DeviceContext::CSGetUnorderedAccessViews: Not implemented` appears in d3d11.log. It appears that the game assumes that method will succeed, which causes it to dereference a bad pointer.

### System information
- GPU: Radeon RX 480
- Driver: Mesa 17.3.2
- Wine version: 2.21-staging
- DXVK version: git bdfbd3e

### Log files
- d3d11.log: https://pastebin.com/uMsnRkRZ
- dxgi.log: https://pastebin.com/Gb3QQFUC

**Comment by oscarbg** [comment]
the report also shows the same for 
D3D11DeviceContext::GetPredication
D3D11DeviceContext::SetPredication
functions could be also reason of crash..

**Comment by doitsujin** [comment]
`CSGetUnorderedAccessViews` is implemented as of d74db72adde16990020965642fcd5abb7f05f97a. Predication is a bit more involved since it's one of those features that are not natively supported by Vulkan.

**Comment by roothorick** [comment]
As of 3dea58d it gets just a hair further; advances past the NV logo to a black screen, then produces an error dialog with a different trace. Clearly a different issue. I'll start a separate issue -- it's unclear whether it's predication related or not, based on the stacktrace now recorded by the game.
