### ISSUE TITLE
Shadow Warrior 2 video palyback problem

### ISSUE THREAD

**Issue by VortexAcherontic** [doitsujin/dxvk#1061]
While I made a showcase report on Shadow Warrior 2 I noticed that in the 2nd Level where you first enter the ZILLA Enterprise Laboratory there is a TV where a video should have ben played but it just shows a purple texture

![SW2_Showcase-f082845](https://user-images.githubusercontent.com/11244092/57809353-9105f600-7765-11e9-81dd-e233f1497a0a.png)

### Software information
Shadow Warrior 2, Maximum Graphics

### System information
- GPU: NVidia GeForce GTX 1080
- Driver: 418.56
- Wine version: 4.0
- DXVK version: 1.2

### Apitrace file(s)
Unfortunately I can not provide an aptitrace log because right after the loading screen the game crashes.

Because I use Lutris to play the game I tried the following:

Disabled DXVK via Lutris and launched the game to make sure it runs with out DXVK.
OpenGL rendering was working and I was able to walk around. (No DXVK_HUD which was still enabled in the envs to make sure DXVK is off)

export WINEPREFIX="<Path-to-Lutris-Wine-Prefix>"
`/home/<user>/.local/share/lutris/runners/wine/tkg-4.0-x86_64/bin/wine /home/<user>/Downloads/Software/apitrace-msvc/x64/bin/apitrace.exe trace -a dxgi <Path-to-SW2-installation>/ShadowWarrior2.exe`

### Log files
- d3d11.log: [GoogleDrive](https://drive.google.com/open?id=1cg2B-9M-zjRPeoI4kJrMKm8dTGDNTHLq)
- dxgi.log: [GoogleDrive](https://drive.google.com/open?id=1zKeHChfPXgFdWc9cxyDYv9AbkXzxMx74)

**Comment by doitsujin** [comment]
You probably need mfplat or something for the video to be played back. This isn't a "texture" issue but a video playback issue.

**Comment by VortexAcherontic** [comment]
So I fetched the Wine debug output and tried to run the game wit Wine 4.5 but same issue.
In the Log I get a lot of these
```
0038:fixme:rawinput:GetRegisteredRawInputDevices devices (nil), device_count 0x1daf170, size 16 stub!
0038:fixme:rawinput:GetRegisteredRawInputDevices devices 0x4d19f0, device_count 0x1daf170, size 16 stub!
0037:fixme:rawinput:GetRegisteredRawInputDevices devices (nil), device_count 0x1c8f170, size 16 stub!
0037:fixme:rawinput:GetRegisteredRawInputDevices devices 0x4d19f0, device_count 0x1c8f170, size 16 stub!
0039:fixme:rawinput:GetRegisteredRawInputDevices devices (nil), device_count 0x1ecf170, size 16 stub!
0039:fixme:rawinput:GetRegisteredRawInputDevices devices 0x4d19f0, device_count 0x1ecf170, size 16 stub!
0035:fixme:rawinput:GetRegisteredRawInputDevices devices (nil), device_count 0x1a4f170, size 16 stub!
0035:fixme:rawinput:GetRegisteredRawInputDevices devices 0x4d19f0, device_count 0x1a4f170, size 16 stub!
003b:fixme:rawinput:GetRegisteredRawInputDevices devices (nil), device_count 0x210f170, size 16 stub!
003b:fixme:rawinput:GetRegisteredRawInputDevices devices 0x4d19f0, device_count 0x210f170, size 16 stub!
003c:fixme:rawinput:GetRegisteredRawInputDevices devices (nil), device_count 0x222f170, size 16 stub!
003c:fixme:rawinput:GetRegisteredRawInputDevices devices 0x4d19f0, device_count 0x222f170, size 16 stub!
003e:fixme:rawinput:GetRegisteredRawInputDevices devices (nil), device_count 0x246f170, size 16 stub!
003e:fixme:rawinput:GetRegisteredRawInputDevices devices 0x4d19f0, device_count 0x246f170, size 16 stub!
003c:fixme:rawinput:GetRegisteredRawInputDevices devices (nil), device_count 0x222f170, size 16 stub!
003c:fixme:rawinput:GetRegisteredRawInputDevices devices 0x4d19f0, device_count 0x222f170, size 16 stub!
003f:fixme:rawinput:GetRegisteredRawInputDevices devices (nil), device_count 0x258f170, size 16 stub!
003f:fixme:rawinput:GetRegisteredRawInputDevices devices 0x4d19f0, device_count 0x258f170, size 16 stub!
```

But I can not find anything special.
How ever here is the full log: [Wine Log](https://drive.google.com/open?id=1XHpf5OkQc_XuFh6ELzw3VGaLdf2h8r04)

**Comment by doitsujin** [comment]
Can you post a savegame? I'm still fairly certain that this isn't my issue, but it can't hurt to take a quick look at what exactly the game is doing there.

**Comment by Jrugia** [comment]
If a savegame is provided I'd be happy to help test this as I've got the game installed.

**Comment by shmerl** [comment]
I finished the game, but have never encountered such bug. Can you post a savegame please?

**Comment by VortexAcherontic** [comment]
If I did not forgot something this should be the save game. I zipped the folder named "2" cuz it's the 2nd save I did. Hope this helps.

And @shmerl this is also the GOG Version I'm playing should be version 1.1.14.0

[2.zip](https://github.com/doitsujin/dxvk/files/3194006/2.zip)

**Comment by VortexAcherontic** [comment]
Okay now it's sure that it is not a DXVK issue.
Ran the game with the wine OpenGL renderer and the TV keeps purple.

Further on 4.6-protonified also did not solved the issue.
So it's something else I need to figure out :D

I should have checked this earlier before opening a ticket :confounded:

**Comment by shmerl** [comment]
Hm, I guess I either missed it last time, or something is different now - I do get this purple screen in the cutscene, but after the cutscene the screen looks OK.

**Comment by VortexAcherontic** [comment]
Yes, while the cut scene (checked it on youtube in an Let's play done on Windows) there is a movie played on it. Some guy. After the cut scene the screen is just blank eg. just a texture is on it. 
That's probably why @doitsujin may though it's a codec problem.

**Comment by shmerl** [comment]
> it's a codec problem and it's probably is

The game has some videos in Wangopedia, but they never worked for me in Wine. So I assume it's a related issue.

**Comment by VortexAcherontic** [comment]
I can confirm that also in the Extras Menu no Movie is working for me as well.
It looks more and more like an Wine/Codec issue x.x

So, since it is no a DXVK issue we could close this here right? :smile:
