### ISSUE TITLE
spoof Nvidia GPU to fix Mirror's Edge Catalyst crash on radv

### ISSUE THREAD

**Issue by aufkrawall** [doitsujin/dxvk#1062]
Would it be possible to apply `dxgi.customVendorId = 10de` for `MirrorsEdgeCatalyst.exe` and `MirrorsEdgeCatalystTrial.exe` by default? Without, the game won't start on radv.

**Comment by doitsujin** [comment]
Can you elaborate on what "won't start" means? Any hints on what might be going wrong?

**Comment by aufkrawall** [comment]
The game starts windowed in 720p (like most  Frostbite engine games), but before it would switch into fullscreen, it just crashes.

[MirrorsEdgeCatalyst_d3d11.log](https://github.com/doitsujin/dxvk/files/3188995/MirrorsEdgeCatalyst_d3d11.log)
[MirrorsEdgeCatalyst_dxgi.log](https://github.com/doitsujin/dxvk/files/3188996/MirrorsEdgeCatalyst_dxgi.log)
[backtrace.txt](https://github.com/doitsujin/dxvk/files/3188997/backtrace.txt)

**Comment by doitsujin** [comment]
Can you post the full wine log? I wonder if it's trying to load a DLL and fails.

**Comment by aufkrawall** [comment]
Ah, dang. I forgot I turned Wine verbosity down. Sorry for not providing more information in the first place, I was under the false impression that there would be nothing more to it.
Going to post an update tomorrow.

**Comment by aufkrawall** [comment]
Sorry, lots of clutter due to Origin.

Maybe this is interesting?

> 0022:fixme:nvapi:unimplemented_stub function 0xd44d3c4e is unimplemented!

[wine.log](https://github.com/doitsujin/dxvk/files/3190554/wine.log)

**Comment by doitsujin** [comment]
Can you try setting the DLL overrides for nvapi,nvapi64 to **disabled**?

**Comment by aufkrawall** [comment]
That makes the warning go away, but unfortunately not the crash.
[wine.log](https://github.com/doitsujin/dxvk/files/3190851/wine.log)
(I btw. had to downgrade to Mesa 19 in the meantime due to big, general radeonsi regresssion, in case you wonder.)

**Comment by doitsujin** [comment]
Well, guess i'll add a config override then. I really dislike doing that and would rather figure out what's actually going on and fix that, but this doesn't seem to be directly dxvk-related and there's absolutely no useful clue in the logs whatsoever.
