### ISSUE TITLE
Flower broken graphics

### ISSUE THREAD

**Issue by mozo78** [doitsujin/dxvk#1066]
The game starts but the graphics are broken. The developer's logos at the start are displayed correctly. I can't get apitrace for the game starts only with DXVK. The trails on the screenshot are from the moving mouse cursor. There arent any other images. I saw the main menu on YouTube and there are window and a flower in a flowerpot.
![1](https://user-images.githubusercontent.com/38666396/57968557-d0eef800-7974-11e9-920f-c1f6d2591cec.png)

### Software information
Flower.exe

### System information
- GPU: GTX 1080Ti
- Driver: 430.14
- Wine version: 4.8
- DXVK version: master

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
https://pastebin.com/0JZju2sk
- dxgi.log: 
https://pastebin.com/MWvMhKwB
- Wine.log
[wine.log.zip](https://github.com/doitsujin/dxvk/files/3193974/wine.log.zip)

**Comment by doitsujin** [comment]
Can't debug without an apitrace.

**Comment by mozo78** [comment]
Yes I know but I can't get it :(

**Comment by mozo78** [comment]
Here you are:
https://my.pcloud.com/publink/show?code=XZg62I7ZiqDsF1ubNLJ6qDgTuKLIH7dHbqmy

**Comment by doitsujin** [comment]
Thanks; unfortunately that trace isn't very useful since it shows garbled graphics on Windows as well. :(

**Comment by mozo78** [comment]
I hope someone get an apitrace on Windows :)

**Comment by doitsujin** [comment]
Can you try `winetricks d3dcompiler_47` and `winetricks d3dcompiler_43` and see if that fixes anything?

**Comment by mozo78** [comment]
Unfortunately it doesn't change anything...

**Comment by K0bin** [comment]
Can you post the logs and Wine output of the game with Microsofts d3dcompiler?

**Comment by mozo78** [comment]
Sure:
- dxgi.log
[Flower_dxgi.log](https://github.com/doitsujin/dxvk/files/3194146/Flower_dxgi.log)
- d3d11.log
[Flower_d3d11.log](https://github.com/doitsujin/dxvk/files/3194147/Flower_d3d11.log)
- Wine.log
[wine.log.zip](https://github.com/doitsujin/dxvk/files/3194148/wine.log.zip)
[wine.zip](https://github.com/doitsujin/dxvk/files/3194149/wine.zip)

**Comment by mozo78** [comment]
Here is a Windows trace:
https://my.pcloud.com/publink/show?code=XZg62I7ZiqDsF1ubNLJ6qDgTuKLIH7dHbqmy

**Comment by mozo78** [comment]
@doitsujin 
Does the Windows apitrace help?

**Comment by doitsujin** [comment]
Do you really expect me to start working on this immediately on a Sunday morning at 6am?

Haven't looked yet, will do that tomorrow.

**Comment by K0bin** [comment]
Just for the record (already discussed this on Discord):
the issue is that the game uploads its textures by mapping all subresources at once.
This fails because DXVK currently only supports 1 mapped subresource at a time.

**Comment by mozo78** [comment]
> Do you really expect me to start working on this immediately on a Sunday morning at 6am?
> 
> Haven't looked yet, will do that tomorrow.

Of course not, just asking. Excuse me but we are obviously in different time zones and I didn't knew that :)



> Just for the record (already discussed this on Discord):
> the issue is that the game uploads its textures by mapping all subresources at once.
> This fails because DXVK currently only supports 1 mapped subresource at a time.

Is this a big problem or can be fixed?

**Comment by doitsujin** [comment]
> Is this a big problem or can be fixed?

Can be fixed, although it's going to be quite a bit of work that might take a few days to fully stabilize. Thanks for posting the trace though, it is indeed helpful.

**Comment by mozo78** [comment]
Thank you :)

**Comment by doitsujin** [comment]
Can you test if this build fixes it:
[dxvk-map-image-buffer-fix.tar.gz](https://github.com/doitsujin/dxvk/files/3198328/dxvk-map-image-buffer-fix.tar.gz)

Built from [this](https://github.com/doitsujin/dxvk/tree/d3d11-map-image-buffer-fix) branch.

**Comment by mozo78** [comment]
You are simply the best!!!
With vsync the game stutters on every second but when I turn it off the game runs very smooth with ~150 FPS. Thank you!!!

**Comment by doitsujin** [comment]
Thanks for the quick feedback, I'll do some more testing and then merge the branch.

**Comment by mozo78** [comment]
I was at work otherwise my feedback It would have been much faster :)

**Comment by mozo78** [comment]
@doitsujin 
Almost forgot. Here is your splendid work!
https://www.youtube.com/watch?v=VzvcLBj4NxM
