### ISSUE TITLE
Quake Champions and Battlefield 5 crash on opening

### ISSUE THREAD

**Issue by vtx2s** [doitsujin/dxvk#1068]
Hi, I'm running Windows 10 64bit edition and running a gtx 1050ti. I've downloaded dxvk-1.2.tar.gz and copied the files on x64 folder to the game directory of each game.

Both games crash on launch, here's the log from Quake Champions crash:

info:  Game: QuakeChampions.exe
info:  DXVK: v1.2
warn:  OpenVR: Failed to locate module
info:  Game: QuakeChampions.exe
info:  DXVK: v1.2
warn:  OpenVR: Failed to locate module
info:  Game: QuakeChampions.exe
info:  DXVK: v1.2
warn:  OpenVR: Failed to locate module
info:  Game: QuakeChampions.exe
info:  DXVK: v1.2
warn:  OpenVR: Failed to locate module
info:  Game: QuakeChampions.exe
info:  DXVK: v1.2
warn:  OpenVR: Failed to locate module
info:  Game: QuakeChampions.exe
info:  DXVK: v1.2
warn:  OpenVR: Failed to locate module
info:  Game: QuakeChampions.exe
info:  DXVK: v1.2
warn:  OpenVR: Failed to locate module
info:  Game: QuakeChampions.exe
info:  DXVK: v1.2
warn:  OpenVR: Failed to locate module
info:  Game: QuakeChampions.exe
info:  DXVK: v1.2
warn:  OpenVR: Failed to locate module

I have the VulkanSDK installed, am I doing something wrong or is it not working? Do I need to copy any more files to some system32 or syswow64 folder?

**Comment by doitsujin** [comment]
> Do I need to copy any more files to some system32 or syswow64 folder?

Dear god, no. You're just going to break your Windows install with that.

Do older versions work? Note that I do not and cannot support Windows, but if this is actually a DXVK regression, I'll have to find a way to reproduce this. Quake Champions works fine on my system both on Windows and on Linux.

Also, please post the **full** log files.

**Comment by vtx2s** [comment]
I've tried now with version 1.0 and 0.7 and reproduced the same result, crash on launch. Log files attached.
[QuakeChampions_dxgi.log](https://github.com/doitsujin/dxvk/files/3194394/QuakeChampions_dxgi.log)

Maybe something to do with my system having nvidia optimus?
[QuakeChampions_dxgi.log](https://github.com/doitsujin/dxvk/files/3194395/QuakeChampions_dxgi.log)

**Comment by doitsujin** [comment]
Yes, that's very likely. The Intel driver on Windows does not work with DXVK since it uses DXGI internally; unfortunately that it just happens to be DXVK's DXGI implementation which in turn uses Vulkan, so it creates an infinite recursion issue.

**Comment by vtx2s** [comment]
So one more reason for me to give up on nvidia optimus laptops lol, it even messes up with external monitors with higher refresh rates since all display goes through the intel dGPU... so no chance of having g-sync working too. Better start building my own desktop.
