### ISSUE TITLE
DXVK_HUD=0 enables the HUD

### ISSUE THREAD

**Issue by ssorgatem** [doitsujin/dxvk#107]
Launching an app with DXVK_HUD=0 enables the HUD. 
I don't if it's intended or not, but it's at the very least counter-intuitive.

I guess the code is simply checking whether DXVK_HUD is defined or not and doesn't actually check its value... so either it should check for the value of DXVK_HUD and not enable it if it's 0 (or "false" maybe too), or the documentation should be made more clear.

This may affect the other environment variables too (haven't checked; it's not that easy to tell...)

**Comment by doitsujin** [comment]
Looking at the code, it was originally intended to make the HUD somewhat customizable, and I will probably return to that at some point. Setting the environment variable to an empty string disables the HUD.

I'll leave this open for now since there is also a related pull request, I'm still undecided which way to go.

**Comment by SveSop** [comment]
Would be nice to have eg:
=0 - would mean disabled
=1 - would mean as it is now
=2 - gpu/cpu/memory load/utilization

Struggling a bit with the "props.driverVersion" not really outputting the correct minor version? Does that work for AMD, and not for nVidia? (That too.....)
Shows: 390.100.0 for me for the 390.25 driver.

**Comment by doitsujin** [comment]
I was thinking of something like `DXVK_HUD=gpuinfo,fps,...`. Kind of like how `GALLIUM_HUD` works, just not as complicated.

> Struggling a bit with the "props.driverVersion" not really outputting the correct minor version?

Nvidia use their own weird undocumented format instead of the standard Vulkan version format. It works for both Mesa and AMD's official drivers, so yes, that's normal.

**Comment by SveSop** [comment]
> Nvidia use their own weird undocumented format instead of the standard Vulkan version format. It works for both Mesa and AMD's official drivers, so yes, that's normal.

Yeah, that makes sense. Back when i was using a R9 270x  and tried wine stuff, i was just told "nah, AMD is bugged to pieces.. even with Mesa". Same when trying to run steam games without binary blob... and even with the blob, that did not really work that well.
So i bought a nVidia card cos of the superior binary drivers for Linux.. Everyone tells you : Gaming under Linux? Go with nVidia........ xept here ofc. Here nVidia is just shit and does not follow ANY standards, and if you are lucky you get some garbled graphics :)

No, i know its not that bad.. but i get this weird feeling that "MY shit is the only thing working" whenever you talk to someone coding. Yeah yeah yeah.. i know "god" himself aka. Linus T has been vokal about nVidia and their closed source shit.. but nevertheless :) I guess one should have both cards just to be able to run stuff.. Especially when opensource stuff breaks for hardware. And yes, it HAS been crap for AMD, but might now be the only thing in the world working :)

**Comment by Yardanico** [comment]
@SveSop well, at least intel/amd graphic drivers are open-source and implement same standards while nvidia always does everything it likes (For example - EGL vs GBM - every other graphic driver implements GBM while nvidia created their own EGL)

**Comment by doitsujin** [comment]
FWIW, Nvidia driver versions should be reported correctly as of 49d2cee930379adba943bae048249a1c4bc6ddfa.

**Comment by SveSop** [comment]
@doitsujin Sweet thanks! :) 
PS. Minor typo: [https://github.com/doitsujin/dxvk/commit/49d2cee930379adba943bae048249a1c4bc6ddfa#commitcomment-27888666](https://github.com/doitsujin/dxvk/commit/49d2cee930379adba943bae048249a1c4bc6ddfa#commitcomment-27888666)
