### ISSUE TITLE
Dawn of Discovery

### ISSUE THREAD

**Issue by tsalwierz** [doitsujin/dxvk#1070]
This game is getting closer to working on DXVK! Before it just crashed instantly to desktop, now with the latest master it's opening to a black screen with a cursor and music in the background.

Dunno if an apitrace would be helpful here. If you want some logs just let me know which.

**Comment by doitsujin** [comment]
> Dunno if an apitrace would be helpful here

Yes, that's why the issue template is asking for it. Preferably recorded on an environment where the game actually works (i.e. Windows). Also, please post the dxvk logs and the full wine console output.

I'm rather baffled that there are still games which don't get past the black screen stage at all; I thought we got past that like a year ago.

**Comment by tsalwierz** [comment]
It's not just a DXVK issue. It also happens on D9VK when DX9 is enabled through the Engine.ini.

Here's the output of the wine console output with debug enabled: https://gist.github.com/tsalwierz/dc623898b82005ab2817809b94fc017a

How would I go about getting DXVK logs - and if I use the apitrace on Windows does it need to be using DXVK or just native stuff?

Specifically asking because I set the dxvk log path and log level and never saw any data.

**Comment by mozo78** [comment]
The game starts and doesn't crash but when in DX10 mode there is only black screen with cursor and sounds. Here are the logs:
- d3d10.log
[Anno4_d3d10.log](https://github.com/doitsujin/dxvk/files/3197057/Anno4_d3d10.log)
- d3d11.log
[Anno4_d3d11.log](https://github.com/doitsujin/dxvk/files/3197058/Anno4_d3d11.log)
- dxgi.log
[Anno4_dxgi.log](https://github.com/doitsujin/dxvk/files/3197060/Anno4_dxgi.log)
I can get an apitrace but I have go to work. Just say and when I get to home I'll try to provide it.

**Comment by doitsujin** [comment]
> `warn:  D3D10CreateEffectFromMemory: Not implemented`

Well, I guess that tells us all we need to know. This game requires the D3D10 effects framework, which is a pain in the arse.

It might be possible to implement this using the `d3dx10` libraries, but that means that you're going to have to use a native d3dx10 implementation for now. I'll give it a shot anyway.

**Comment by mozo78** [comment]
d3dx10 implementation doesn't work too - again black screen with sounds in the background :)

**Comment by doitsujin** [comment]
Maybe give me time to implement it first?

**Comment by mozo78** [comment]
Of course I thought you talk for Wine's d3d10 implementation and as I said it's broken too with this game :) I'm not in a hurry and I don't play this game at all. I just helping tsalwierz. I'm sorry for the misunderstanding.

**Comment by tsalwierz** [comment]
Would a DX10 or DX11 trace help with this @doitsujin ? If so I can get it to you tomorrow.

**Comment by doitsujin** [comment]
A D3D10 trace might be useful, although I'm not sure how it captures the D3D10 effect stuff.

**Comment by doitsujin** [comment]
So I tried the `d3dx10` thing, and it turns out that Microsoft's own implementation recursively calls back into `d3d10.dll`. Unfortunately this makes it completely impossible to support D3D10 effects in DXVK.
