### ISSUE TITLE
Ancestors Legacy Saladins Conquest rendering problems

### ISSUE THREAD

**Issue by mozo78** [doitsujin/dxvk#1073]
The game runs but have rendering problems - some menus are white ant some popup windows too:
![1](https://user-images.githubusercontent.com/38666396/58196014-00359a00-7cd2-11e9-8989-0c4f9a0b6f49.png)
![2](https://user-images.githubusercontent.com/38666396/58196025-0592e480-7cd2-11e9-9f23-0a8422c58f73.png)
![3](https://user-images.githubusercontent.com/38666396/58196041-09bf0200-7cd2-11e9-84c1-7b65a332245f.png)

### Software information
Ancestors Legacy Saladins Conquest

### System information
- GPU: GTX 1080Ti
- Driver: 430.39
- Wine version: 3.16
- DXVK version:  1.2.1

### Apitrace file(s)
https://my.pcloud.com/publink/show?code=XZtHOI7ZDQArqQKMVt74nBFDrmRJvLq3l3Sk

### Log files
- d3d11.log:
[Anc-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/3208628/Anc-Win64-Shipping_d3d11.log)
- dxgi.log: 
[Anc-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/3208629/Anc-Win64-Shipping_dxgi.log)

**Comment by K0bin** [comment]
![grafik](https://user-images.githubusercontent.com/1131720/58200570-5a832a80-7cd3-11e9-8e29-2968c8608758.png)

The trace replays fine for me with 1.2.1.

**Comment by mozo78** [comment]
But the game doesn't...

**Comment by doitsujin** [comment]
Can you post the full wine log? If the apitrace replays correctly, and it does, it's usually an indication that something's wrong elsewhere (especially so if the game works correctly on Windows with DXVK).

**Comment by Jrugia** [comment]
Noticed the OP is using Wine 3.16, maybe updating to a newer version would help?

**Comment by mozo78** [comment]
Yes I know and I succeeded running tens of UE4 games. The game doesn't start with newer Wine versions but with Wine 3.16. With newest it actually starts but there is just black screen without background sounds.
 
- wine 3.16.log:
[wine 3.16.log](https://github.com/doitsujin/dxvk/files/3209586/wine.3.16.log)
- wine 4.8.log:
[wine 4.8.log](https://github.com/doitsujin/dxvk/files/3209587/wine.4.8.log)

**Comment by doitsujin** [comment]
```
0027:fixme:mfplat:MFCreateMediaSession session configuration ignored
00bb:fixme:mfplat:mfsource_CreatePresentationDescriptor (0xfdce9f0)->(0x2e05fc58): stub
```
Well there you go. You're probably going to have to set up native mfplat to get the game to work.

**Comment by mozo78** [comment]
Yes I saw that before I write this issue. I prepared mfplat prefix to no avail - black screen with newer Wine versions and white screens with older ones.

**Comment by mozo78** [comment]
Previously I tried Shadows: Awakening mfplat way:
https://github.com/ValveSoftware/Proton/issues/1102#issuecomment-419678627
Now I tried RE7's way and the game already starts with newer Wine versions and no more black screen! Unfortunately "the white problem" is still here.

**Comment by doitsujin** [comment]
So, does this work on wined3d?

**Comment by mozo78** [comment]
Yes without DXVK the game starts but with pretty the same rendering problems. I tried d3dcompiler_47/43 and DirectX9 to no avail.

**Comment by Pierdek** [comment]
You can try to remove *.mp4 files, this should eliminate white rects, the game should work fine without them.

**Comment by mozo78** [comment]
If you talk about .mp4 files in /Anc/Content/Movies/, I removed them but this doesn't help :)

**Comment by tonix64** [comment]
This game needs an mfplat fix with msmpeg2vdec.dll / msmpeg2adec.dll codecs. (So the python-installcab fix for mfplat + wmv is not going to work for this game)

Afaik no ms redistributable is known that includes those .dll files, so you need to get the right dlls from a windows install as well as set some registry variables related to the mpeg decoder.

It's the same fix some people is using for other games like "Monster Hunter World", "Gris" or "Breathedge" so you may be able to find a better howto or quicker fix but it's documented here: https://askubuntu.com/questions/651099/how-to-install-windows-media-feature-pack-required-by-a-game.

**Comment by mozo78** [comment]
I tried it with a prefix in which Gris is working perfectly fine to no avail. The main menu is white and there is white square instead of movies.

**Comment by tonix64** [comment]
Strange because I've tried it, maybe it requires some other dlls besides those, I applied the z0z0z fix and it worked fine.

**Comment by mozo78** [comment]
I give up long ago. Thank you any way :)

Who is z0z0z? And where is his fix?

**Comment by mozo78** [comment]
@tonix64
Thank you. I tried it again and it works fine with z0z0z's fix :)

**Comment by tonix64** [comment]
Great :)
