### ISSUE TITLE
Uninstall wine

### ISSUE THREAD

**Issue by bailehang** [doitsujin/dxvk#1075]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Name of the game, settings used etc.

### System information
- GPU:
- Driver:
- Wine version: 
- DXVK version: 

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log:

**Comment by bailehang** [comment]
Hand error, sorry.
I am searching how to completely uninstall wine.

**Comment by Kreyren** [comment]
@bailehang Need help? 

### Ubuntu/Debian
`sudo apt remove package_name` or using `synaptic` (https://wiki.debian.org/Synaptic).

### OpenSuse
Either using YaST or `sudo zypper remove package_name`

### Fedora
`dnf -e package_name`

### Gentoo
`emerge -Ca package_name`
- -a = --ask 
- -C = --unmerge (will remove system packages!)

### Exherbo
`cave uninstall package_name` or `cave resolve '-package_name`

### TempleOS
You pray to god for the task needed

---

I also recommend you to check IRC of your distro on https://webchat.freenode.net/ 
Channels:
- #ubuntu 
- #debian
- #fedora 
- #suse 
- #gentoo 
- #exherbo

**Comment by rphsoftware** [comment]
🐸🐸🐸🐸

**Comment by bailehang** [comment]
> 🐸🐸🐸🐸

![image](https://user-images.githubusercontent.com/7373218/58525652-1fb35200-81ff-11e9-8421-b50507450a72.png)
