### ISSUE TITLE
Spellforce 3 severe framerate drop

### ISSUE THREAD

**Issue by mozo78** [doitsujin/dxvk#1078]
The game works very well but on some cases and always when the player has a base, the FPS drops drastically after a certain amount of time. Closing and starting the game solves the problem temporarily but after ~10 minutes the game starts to lag and after ~15 minutes it gets nearly unplayable. Lowering the video settings to their minimum doesn't help. I tried with 
"dxgi.customVendorId = 1c06
dxgi.customDeviceId = 10de"
in the dxvk.conf to no avail.
In such moments GPU utilization is around 5-7% and the CPU around 10%. When there isn't frame drop and the game is working normaly, the utilization is ~30-35%.

![1](https://user-images.githubusercontent.com/38666396/58435094-9816f780-80c7-11e9-9bc3-e907bf7843ef.png)

I can't get an apitrace because the frame drop is after 10 minutes and the file will be enormous. @doitsujin since you mentioned previously you have access to the game, I can give you a savegame.

### Software information
Name of the game, settings used etc.

### System information
- GPU: NVIDIA GTX 1080 Ti
- Driver: 430.14.0
- Wine version: 4.8
- DXVK version: 1.2.1

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
[SF3ClientFinal_d3d11.log](https://github.com/doitsujin/dxvk/files/3224754/SF3ClientFinal_d3d11.log)

- dxgi.log: 
[SF3ClientFinal_dxgi.log](https://github.com/doitsujin/dxvk/files/3224755/SF3ClientFinal_dxgi.log)

**Comment by doitsujin** [comment]
What about memory utilization? Does this happen on Windows?

**Comment by Leopard1907** [comment]
"severe framedrop" isn't something he can debug just by looking at log files

**Comment by mozo78** [comment]
As is seen at the screenshot the memory is just around 2GB. My video card is with 11GB.
Here you are the save:
https://my.pcloud.com/publink/show?code=XZIKHA7Zxte4Yi7l98FBC2T5LW7Mnk1Nd9Lk

I don't have Windows but I searched on the Web and I can't find similar problem on Windows. Now I'll try with WineD3D and will report ASAP.

**Comment by doitsujin** [comment]
I meant RAM, not VRAM. Anyway, thanks for the save, will look probably tomorrow.

Anything special I need to do to reproduce the problem?

**Comment by mozo78** [comment]
Nope, just wait ~10 minutes :)
Unfortunately I tried with WineD3D and the problem is here again.
My RAM is 32GB and when the problem occurs the amount of RAM taken is no more than 5GB for the whole system.

**Comment by doitsujin** [comment]
okay, so I had this running for ~20 minutes now and performance has always been between 30 and 50 FPS, using highest settings. Can't reproduce the problem. The game also doesn't spend much time on rendering at all.

If this happens for you with wined3d as well, the issue is most likely elsewhere. Note that I used Proton 4.2-5 for testing, not standalone wine.

**Comment by mozo78** [comment]
Hm, very strange. For WineD3D I tested the game with clean prefix with vanilla Wine and the problem was there. May be I must try with Proton. It'll be interesting. Thank you :)

**Comment by mozo78** [comment]
Confirming - with Proton there isn't such problem. Obviously Valve was implemented something but I don't know what :)
