### ISSUE TITLE
Some of My ideas about DXVK

### ISSUE THREAD

**Issue by bailehang** [doitsujin/dxvk#1079]
Recently I used DXVK on Ubuntu run a big game, although it can run smoothly, it has two disadvantages:
1. The average frame rate is half that on Windows with the same computer hardware configuration. 
2. Some special renderings don't work.
I suspect it's all about NVIDIA driving obsolescence, it doesn't fit as well as it does on Windows.

There has been a lot of news about cloud games recently. I don't know how they can render games on high performance servers.

Thanks, everyone who reads.

**Comment by doitsujin** [comment]
So what exactly is your point? Which game were you trying to run? Having rendering issues and half of native Windows performace isn't expected, it should be fixed, but to do that I need some info.

**Comment by kassindornelles** [comment]
@bailehang what do you mean with "special renderings" ?
are you sure that you are using the latest drivers on linux?

**Comment by bailehang** [comment]
Thanks,
@kassindornelles @doitsujin 
My point is that running games on Linux is not as efficient as running games on Windows.
I updated to the latest drive, the game will run suddenly stuck, (The latest driver is NVIDIA 430)
So I lowered my driver version for smooth running. (NVIDIA 390)

Since you recommend the latest drivers, I'll try again.

**Comment by doitsujin** [comment]
> My point is that running games on Linux is not as efficient as running games on Windows.

Yes, but not by 50%. Even on Nvidia hardware you shouldn't see more than a 20% performance drop in most games, on AMD hardware even less. So I'll ask again, **which game** are you talking about?

**Comment by Roesjka** [comment]
> Thanks,
> @kassindornelles @doitsujin
> My point is that running games on Linux is not as efficient as running games on Windows.
> I updated to the latest drive, the game will run suddenly stuck, (The latest driver is NVIDIA 430)
> So I lowered my driver version for smooth running. (NVIDIA 390)
> 
> Since you recommend the latest drivers, I'll try again.

Would also be nice to mention the distro.
I play WoW default settings FG 100fps BG 30fps. Same defaults as on Windows.
EVE Online over 100 fps. That's lower than on Windows but anything higher than 100fps is for a lot of games unnecessary whatever others may say.

**Comment by oscarbg** [comment]
well at least I can say running Heavy Rain demo on Windows with latest DXVK 1.2.1 and latest DXVK master having some Heavy Rain patch and latest NV 430.64 or AMD 19.5.2 I’m getting half perf. at 4K I get 60fps on Vega and Titan V on DX11 but around 30 fps using DXVK..

**Comment by doitsujin** [comment]
Heavy Rain is indeed bad, that's because it changes render targets after almost every single draw call. I don't consider that fixable, and it's really not something that any game should ever do.

**Comment by Pangaea666** [comment]
I don't see any "ideas" here?

If you have specific issues with a game, then I'd recommend to describe what happens, with as much detail as you remember, and mention which game it is and what hardware and distro etc you have. Then it is easier to try to figure out what might be wrong.

**Comment by bailehang** [comment]
The game is our own research and development, like WoW.
I retried the following configuration and the game crashed. Please help me check the problem.
[Game_d3d11.log](https://github.com/doitsujin/dxvk/files/3230459/Game_d3d11.log)
[Game_dxgi.log](https://github.com/doitsujin/dxvk/files/3230460/Game_dxgi.log)
- SYSTEM:  18.04.1-Ubuntu （I‘ve tried 19.04，and they all crash)
- GPU：GeForce GTX 1060 6G
- Driver: 430，418，410 all crash，390 is ok
- Wine version: 4.9 winehq-devel
- DXVK version:  the latest from git

Thanks!

**Comment by doitsujin** [comment]
> err:   DxvkSubmissionQueue: Command submission failed with VK_ERROR_DEVICE_LOST

Yeah, something crashes your driver.

Anyway, can't provide support for games that aren't publicly available, reasons should hopefully be obvious.

**Comment by bailehang** [comment]
https://github.com/doitsujin/dxvk/issues/469
Have other similar situations been resolved？

**Comment by doitsujin** [comment]
Again, it means that *something* in your game crashes your graphics driver, there are many reasons why this could happen. But I **cannot debug your game**, so there's not much I can do here.

**Comment by bailehang** [comment]
Thanks，
our game has been released, but I'm experimenting with a Linux version, and if you can keep it a secret, I'll give you the download link in private.
Note:  that it's a Chinese game.

**Comment by mozo78** [comment]
It's better releasing native version ;)

**Comment by Joshua-Ashton** [comment]
> Thanks，
our game has been released, but I'm experimenting with a Linux version, and if you can keep it a secret, I'll give you the download link in private.

Hate to break it to you, but it's not much of a secret due to the fact you announced it on a public issue tracker!

:frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog: :frog:

**Comment by bailehang** [comment]
> > Thanks，
> > our game has been released, but I'm experimenting with a Linux version, and if you can keep it a secret, I'll give you the download link in private.
> 
> Hate to break it to you, but it's not much of a secret due to the fact you announced it on a public issue tracker!
> 
> 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸 🐸

I am not an FBI, I don't need such strict confidentiality, just don't preach it.
![image](https://user-images.githubusercontent.com/7373218/58602095-1b9a3980-82be-11e9-956d-aa4ca623a07e.png)

**Comment by bailehang** [comment]
If you are willing to help, please contact me(bailehang@sina.com), I can show you Chinese style games!

**Comment by Joshua-Ashton** [comment]
Good website. :frog:

![image](https://user-images.githubusercontent.com/21316711/58650346-57f18800-8306-11e9-9880-d6ba353a9f71.png)

**Comment by bailehang** [comment]
> Good website. 🐸
> 
> ![image](https://user-images.githubusercontent.com/21316711/58650346-57f18800-8306-11e9-9880-d6ba353a9f71.png)

![image](https://user-images.githubusercontent.com/7373218/58676734-e9570d80-838b-11e9-96bc-2e7128155492.png)
This line of Chinese meaning is: Go straight to the Sina North American edition.
You don't have to wonder that Chinese websites are not very friendly to foreign countries. We can use facebook or other software to communicate.

**Comment by bailehang** [comment]
I have located that the graphics card was lost due to an error in the geometry shader.
I will keep watching and trying to fix the shader.
