### ISSUE TITLE
Batman Arkham City GOTY: Crash in vkCreateImage()

### ISSUE THREAD

**Issue by roothorick** [doitsujin/dxvk#108]
### Software information
Game goes to a black screen after Nvidia logo, split second after gives a sizable crash dialog with vkCreateImage() being the topmost frame that's not unresolved or in standard library space. d3d11.log has a pile of messages related to unimplemented predication support, but it's not clear if the two are connected. Stacktrace: https://pastebin.com/zp1U5Jmc

### System information
- GPU: Radeon RX 480
- Driver: Mesa 17.3.2
- Wine version: 2.21-staging
- DXVK version: git 3dea58d

### Apitrace file(s)
 - Under wined3d, crashes a few frames into the main menu, but that's past where dxvk gets tripped up. https://roothorick.mooo.com/BatmanAC.trace

### Log files
- d3d11.log: https://pastebin.com/b8RSAgMN
- dxgi.log: https://pastebin.com/Zm6wfw7y

**Comment by exolyte** [comment]
Tested this game on latest master (24f0528) and it crashes on a black screen after the nvidia logo as well, but with an error message about CreateShaderResourceView() and a texture creation error in the logs.

[BatmanAC_d3d11.log](https://github.com/doitsujin/dxvk/files/1912758/BatmanAC_d3d11.log)
[BatmanAC_dxgi.log](https://github.com/doitsujin/dxvk/files/1912759/BatmanAC_dxgi.log)
Driver is mesa 18.0.0 (I have no idea why it says 0.0.0).

I'm guessing this is related to #219

**Comment by AccountOneOff** [comment]
Just tested this game and it crashes at the same point after the Nvidia splash screen except I get this error message instead:

![screenshot](https://user-images.githubusercontent.com/15083452/39172986-42d8a128-4758-11e8-94b3-b064acc66370.png)

## System information

-    GPU: GTX 960
-    Driver: 396.18.0
-    Wine version: Staging 3.5
-    DXVK version: 5eaacf7

[BatmanAC_d3d11.log](https://github.com/doitsujin/dxvk/files/1941413/BatmanAC_d3d11.log)
[BatmanAC_dxgi.log](https://github.com/doitsujin/dxvk/files/1941414/BatmanAC_dxgi.log)

**Comment by doitsujin** [comment]
@AccountOneOff It should work for you with the latest commits. I'll keep this open to track the RADV state of affairs, which *as of now* doesn't support the RGB formats for images at all.

**Comment by doitsujin** [comment]
Should be fixed by this radv patch:
https://lists.freedesktop.org/archives/mesa-dev/2018-May/193606.html
