### ISSUE TITLE
Stalker clear sky maxed out black or distorted screen

### ISSUE THREAD

**Issue by XakepSDK** [doitsujin/dxvk#1080]
### Software information
STALKER: Clear Sky (20510)
Black screen or distorted screen.
Everything maxed out, game restarted, then maxed out again, first max out opens more settings after restart.
Here's game settings, should be in `$GAME_DIR/_appdata_/`, name: `user.ltx`
[user.tar.gz](https://github.com/doitsujin/dxvk/files/3229626/user.tar.gz)

After i alt+tab some times, graphics start to draw, but distorted.
![20190529024135_1](https://user-images.githubusercontent.com/4938483/58511252-f0aec900-8189-11e9-876d-0c8df87d6dda.jpg)

### System information
- GPU: RTX 2080 Ti
- Driver: 430.14
- Wine version: Proton 4.2-5
- DXVK version: 1.2.1

### Apitrace file(s)
[STALKER Clear Sky_apitrace.tar.gz](https://github.com/doitsujin/dxvk/files/3229627/STALKER.Clear.Sky_apitrace.tar.gz)
I just dropped 3 dlls from https://github.com/doitsujin/dxvk/wiki/Common-issues
without disabling dxvk because it won't generate these files.
I'm not sure if this is correct, because this https://github.com/doitsujin/dxvk/blob/master/issue_template.md page says, that i should disable it.

### Log files
[STALKER Clear Sky_1_log_broken.tar.gz](https://github.com/doitsujin/dxvk/files/3229628/STALKER.Clear.Sky_1_log_broken.tar.gz)

**Comment by doitsujin** [comment]
The apitrace is empty. Rule of thumb: if it's much smaller than 100 MB, it's probably not very useful.

Anyway, tons of d3dcompiler messages in the log, so trying a native d3dcompiler_43 might help.

**Comment by XakepSDK** [comment]
Game doesn't start with `PROTON_USE_WINED3D=1`
I did this: `WINEPREFIX=/media/data/SteamLibrary/steamapps/compatdata/20510/pfx/ winetricks d3dcompiler_43`
`winecfg` shows this:
![d5cc0baf87](https://user-images.githubusercontent.com/4938483/58512815-88fa7d00-818d-11e9-8863-b9cc3437d5b1.png)

Wine version used for winetricks
`wine --version`: `wine-4.9 (Staging)`

Same distorted screen issue.

**Comment by XakepSDK** [comment]
Should game start with apitrace libs? Because when i tried to start game with them, game engine bug trap catched something and game didn't started.
Also with wined3d and proton log enabled i got 700+MiB log.
Full of this:
Index just increasing.
```
40691.820:0027:0028:fixme:d3d10:d3d10_shader_reflection_GetConstantBufferByIndex iface 0x1004508, index 25668 stub!
40691.820:0027:0028:fixme:d3d10:d3d10_shader_reflection_GetConstantBufferByIndex iface 0x1004508, index 25669 stub!
40691.820:0027:0028:fixme:d3d10:d3d10_shader_reflection_GetConstantBufferByIndex iface 0x1004508, index 25670 stub!
40691.820:0027:0028:fixme:d3d10:d3d10_shader_reflection_GetConstantBufferByIndex iface 0x1004508, index 25671 stub!
```

**Comment by XakepSDK** [comment]
I think i found core of issue: anti-aliasing.
If i enable it, image is distorted.
I talked with some stalker fans, they said, that on their systems(windows) image is little bit distorted, not like mine.
Also i found source code of engine.
Source code: 
[patch 1.5.06.tar.gz](https://github.com/doitsujin/dxvk/files/3229864/patch.1.5.06.tar.gz)

Some info about dir. structure if you are interested:
Engine source code: http://files.xray-engine.org/xray_engine/src/soc_cs/
Password in: stk-src-tags.txt
You need `tags/clear sky/patch 1.5.06/` rendering code in `Layers` directory

**Comment by XakepSDK** [comment]
This happens with latest DXVK:
https://github.com/doitsujin/dxvk/commit/1e0fe36cae8128820f8a2314060e139f5ec6de93
![20190529050624_1](https://user-images.githubusercontent.com/4938483/58518086-4d67af00-819d-11e9-8d2e-d4fb2cb97370.jpg)

proton log:
https://gist.github.com/XakepSDK/47defbf4fa13277fdef99a18ccb645e1

**Comment by XakepSDK** [comment]
My friend made apitrace on windows:
https://drive.google.com/open?id=1b1pZzUyzws7G0Pm9Zc-syplulhKL6nm8

**Comment by XakepSDK** [comment]
Is apitrace useful? I can make another one if you want

**Comment by doitsujin** [comment]
Haven't looked at it yet.

**Comment by doitsujin** [comment]
Does this work if you disable MSAA? It looks like the game tries to sample an MSAA texture like a non-MSAA texture, which is not supported in Vulkan and cannot be emulated in a performant way.

**Comment by XakepSDK** [comment]
Looks like it's working if i completely disable AA.
If it's not hard, could you make workaround so i can test it?

**Comment by doitsujin** [comment]
Unfortunately no, as mentioned there is no way to implement this behaviour properly.

**Comment by XakepSDK** [comment]
Guys from community said, that this stretching issue happens only in main menu.
Does this mean, that i will have 1fps only in main menu?

**Comment by doitsujin** [comment]
I'm not going to implement a workaround because it's too much work for little to no practical return.

**Comment by XakepSDK** [comment]
Thanks for debugging things. Close if you wish.

**Comment by XakepSDK** [comment]
Game starts flickering after some time playing. Hard to make screenshot.
![20190613182611_1](https://user-images.githubusercontent.com/4938483/59432419-c76f7900-8dd6-11e9-870c-5ee36e4a7e3f.jpg)

**Comment by doitsujin** [comment]
Does the game support D3D9 or work properly on wined3d? I cannot fix that broken engine.

**Comment by XakepSDK** [comment]
Yes, but most features are on DX10 renderer. Previous screenshot was made without AA.

**Comment by SurDno** [comment]
Flickering during rain is vanilla issue that happens on all of the default DirectX renderers and has nothing to do with DXVK.

**Comment by XakepSDK** [comment]
Game does not have any issues for me with proton 5
Everything works as excepted, except anti-aliasing in stalker soc and clear sky, but this is game bug
