### ISSUE TITLE
v1.2.1 setup_dxvk.sh reverses x32/x64 dlls.so and starts steam.exe

### ISSUE THREAD

**Issue by Techwolf** [doitsujin/dxvk#1084]
### System information
- GPU: Nvidia
- Driver: 430.14
- Wine version:  4.9
- DXVK version:  1.2.1

Lastest release, 1.2.1, setup_dxvk.sh will install the 32 bit dlls in wowsys64 and the 64bit dlls into system32. Pops up a small window of configering wine and then an error pops up on top of that window. After closing them out, steam.exe is started.

I uninstalled 1.2.1 and use 1.2 install and it works without issue.

**Comment by Joshua-Ashton** [comment]
nonononononono

In a 64 bit prefix: SysWOW64 houses 32 bit dlls, and System32 houses 64 bit dlls.
In a 32 bit prefix: SysWOW64 is non existant and System32 houses 32 bit dlls.

setup_dxvk.sh also has nothing todo with starting Steam. I have no idea how that's happening.

Regarding the error popup... There is very little anyone can do to help that if you don't actually say what the error is.

**Comment by Techwolf** [comment]
Thank you for the info. I will close this bug while I figure out what is causing the steam.exe issue.

Love the reverse logic there, system32 for 64 bit and wow64 is 32 bit.

**Comment by doitsujin** [comment]
Well, "an error" is not very specific. My script also doesn't start steam.exe directly, **however** it does invoke wine, so any autostart app inside your wine prefix **will** be started. You'll probably want to check your configuration.

As Joshua mentioned, the 32-bit and 64-bit locations are correct.

**Comment by Thaodan** [comment]
>Love the reverse logic there, system32 for 64 bit and wow64 is 32 bit. 
Because its Windows-On-Windows 64-bit and there is Windows-On-Windows 32 bit.
System32 comes from Win32, there was also system for Win16.
