### ISSUE TITLE
World of Warcraft: Flickering textures

### ISSUE THREAD

**Issue by kleest** [doitsujin/dxvk#1086]
Starting with commit f501ebce973d26d1d4e86911526ec73690f6208e (bisected), some textures begin to flicker. I did not manage to produce an apitrace, and the validation layers log does not contain any useful difference between a good and bad commit. If it helps, I can record a video.

### Software information
* World of Warcraft 8.1.5 (29981)
* DirectX 11 API
* CMAA

### System information
- GPU: AMD Radeon R9 390
- Driver: Mesa 19.0.5 (RADV)
- Wine version: wine-staging 4.8
- DXVK version: 3de87b41

### Apitrace file(s)
--

### Log files
- d3d11.log:
[Wow_d3d11.log](https://github.com/doitsujin/dxvk/files/3259438/Wow_d3d11.log)

- dxgi.log: 
[Wow_dxgi.log](https://github.com/doitsujin/dxvk/files/3259439/Wow_dxgi.log)

### Screenshots
Look at fence (bottom-left) and the lamps.
![WoWScrnShot_060619_005246](https://user-images.githubusercontent.com/6516878/58997840-a8814d80-87fe-11e9-83ea-d501172b990c.jpg)
![WoWScrnShot_060619_005247](https://user-images.githubusercontent.com/6516878/58997843-aa4b1100-87fe-11e9-94cf-4e653391acfb.jpg)

**Comment by doitsujin** [comment]
Thanks for bisecting this, unfortunately I don't quite understand why this particular commit breaks this and therefore I also don't know how to fix this without reverting the performance optimization.

**Comment by doitsujin** [comment]
Can you test whether this patch fixes the problem? It effectively reverts the problematic commit.
[wow.patch.txt](https://github.com/doitsujin/dxvk/files/3261561/wow.patch.txt)

**Comment by kleest** [comment]
Yes, the patch fixes the problem.

**Comment by kleest** [comment]
I managed to capture an API trace on Windows. However, I am unable to replay the trace when using Wine regardless of dxvk. It crashes with the following log:
```
8 @0 IDXGIAdapter3::QueryInterface(this = 0x2b10c7ba140, riid = IID_IDXGIAdapterInternal2, ppvObj = &0x2b10c7ba1c8) = S_OK
8: warning: unknown object 0x2b10c7ba1c8
8: warning: failed with 0x80004002 (E_NOINTERFACE): 
002c:fixme:dxgi:DXGID3D10CreateDevice Ignoring flags 0x100.
20 @0 IDXGIAdapter3::EnumOutputs(this = 0x2b10c7ba140, Output = 1, ppOutput = &0x2b17e2c9e90) = S_OK
20: warning: failed with 0x887a0002 (DXGI_ERROR_NOT_FOUND): The item requested was not found. For GetPrivateData calls, this means that the specified GUID had not been previously associated with the object.
22: debug: apitrace: warning: caught exception 0xc0000005
apitrace: warning: caught exception 0xc0000005
22: error: caught an unhandled exception
```
Another trace out of this bugtracker (Stalker Clear Sky) is working fine.  

I can upload the apitrace for you. However, because I am not able to replay the trace I cannot guarantee that the trace contains the flickering issue.

**Comment by kleest** [comment]
There you go:
https://drive.google.com/file/d/14WeFelqOxxmFfO89WwM0FXfj_ODXoaha/view?usp=drivesdk

**Comment by doitsujin** [comment]
Thanks, that should be at least somewhat useful.

**Comment by doitsujin** [comment]
@kleest can you test if [this](https://github.com/doitsujin/dxvk/tree/dxvk-constant-buffer-binding-opt) branch works correctly with World of Warcraft? It's basically a reimplementation of the optimization that was causing this issue, but with a fix applied.

**Comment by kleest** [comment]
That branch works correctly. Note: As I don't have an active subscription, I tested it in an area accessible through starter edition, where f501ebce973d26d1d4e86911526ec73690f6208e caused the issues as well.
  
Thank you for your work!
