### ISSUE TITLE
Some Unity applications: Hangs/crashes before creating window, validation errors

### ISSUE THREAD

**Issue by roothorick** [doitsujin/dxvk#109]
### Software information
Hangs or crashes before creating its window. No error dialogs that I can see. Console output shows validation errors.

Apps known to be affected:
* Black The Fall
* Gone Home
* Mass Exodus
* Metrico+

Logs and output are from Black The fall.

Console output: https://pastebin.com/bQjhw8s5

### System information
- GPU: Radeon RX 480
- Driver: Mesa 17.3.2
- Wine version: 2.21-staging
- DXVK version: git 3dea58d

### Apitrace file(s)
apitrace won't record a useful trace for this game, for some reason...

### Log files
- d3d11.log: https://pastebin.com/xZJWqpXh
- dxgi.log: https://pastebin.com/PLffxKQM

**Comment by roothorick** [comment]
Gone Home crashes instead of hangs, but produces nearly identical validation errors. Assuming to be the same issue for the time being.

**Comment by roothorick** [comment]
Identified a third title with a crash and nearly identical validation errors: Mass Exodus.

I'm going to start a list up top.

**Comment by doitsujin** [comment]
Can you re-test this with a recent build? The issue that caused the validation errors has been fixed.

**Comment by exolyte** [comment]
I was able to get in game in Black The Fall with latest master ( 8cd97959f2b97c17d25ce2b8b1956a6a08ebe893 ), it did have some graphical issues which are most likely related to missing stream output ( https://github.com/doitsujin/dxvk/issues/135 )

**Comment by doitsujin** [comment]
Closing due to lack of feedback. Unity Engine games almost universally require Stream Output though, so there will likely be rendering issues.
