### ISSUE TITLE
Planet Coaster (493340) crashes with black screen at launch

### ISSUE THREAD

**Issue by alasky17** [doitsujin/dxvk#1091]
### Software information
Planet Coaster (493340) will crash with a black screen and a crash dialogue on launch, and the window generally must be killed forcefully. 
![planet-coaster-crash](https://user-images.githubusercontent.com/40211296/59376922-bb23e700-8d16-11e9-93db-480962408f44.png)

This happens with plain Proton 4.2-7, but with the addition of the commits listed below, the crash changes and points more directly to dxvk.  One of the commits is already upstreamed and the other two are in the queue and will be upstreamed soon.

No special settings, etc. 

### System information
- GPU:AMD Radeon RX 470
- Driver:amdgpu
- Wine version: Proton 4.2-7 with 3 extra patches to fix a different crash (third one has already been accepted upstream)
[https://source.winehq.org/patches/data/166403](url)
[https://source.winehq.org/patches/data/166404](url)
wine commit 9445bed2981c5a68a57c749b9354649980a31c39 =  [https://source.winehq.org/patches/data/166310](url)
- DXVK version:  8ba89c94cd3fbc9788e4345aea7d4d69f632cc59 dxvk (essentially 1.2.1 for Proton)

### Apitrace file(s)
- Put a link here
[PlanetCoaster.trace.gz](https://github.com/doitsujin/dxvk/files/3282684/PlanetCoaster.trace.gz)

### Log files
- d3d11.log:
[PlanetCoaster_d3d11.log](https://github.com/doitsujin/dxvk/files/3282668/PlanetCoaster_d3d11.log)

- dxgi.log: 
[PlanetCoaster_dxgi.log](https://github.com/doitsujin/dxvk/files/3282669/PlanetCoaster_dxgi.log)

**Comment by alasky17** [comment]
One other note about this crash - the crash log also looked different when there was a controller plugged in.  The logs I provided did not have a controller plugged in.  I think that the controller issue is on the wine side, not dxvk.

**Comment by doitsujin** [comment]
Does this work with wined3d?

I do have access to the game but given that it never worked with wine at all, I'd like to see some solid indications that this is indeed a DXVK bug and not just something else in wine. The apitrace unfortunately isn't particularly helpful.

**Comment by alasky17** [comment]
Yes, the game works with wined3d (with some glitches like a few textures rendered black) with the three commits I mentioned.  The commits fix some crashes in wine and allow the game to get past the title screen with wined3d, at which point it runs alright and definitely renders.  I could upload my custom proton build somewhere if that would be useful to you.

I can also upload a log of the game running with wined3d if that would be useful?  Is there anything else I can do that would be helpful?

**Comment by doitsujin** [comment]
This should be fixed as of 5a66da8ef813944e4d7fc5dab056b36bb03c8c2c. I tested the game on Windows however, not on wine, so if it still crashes on wine it's most likely an unrelated issue.

Do note that while the menu runs fine, the game will run at ~1 FPS at most for some reason.

**Comment by mozo78** [comment]
@alasky17 
Can you give me the patched Proton to test it or it's better to post working links to patches in order to compile it myself. 
Thank you :)

**Comment by alasky17** [comment]
@mozo78 Here are the three patches: 

[0001-zeb-166310.txt](https://github.com/doitsujin/dxvk/files/3286777/0001-zeb-166310.txt)

[0002-kernel32-Set-up-a-guard-page-at-the-bottom-of-the-fi.txt](https://github.com/doitsujin/dxvk/files/3286782/0002-kernel32-Set-up-a-guard-page-at-the-bottom-of-the-fi.txt)
[0001-kernel32-Allocate-at-least-1MB-of-stack-space-in-Cre.txt](https://github.com/doitsujin/dxvk/files/3286783/0001-kernel32-Allocate-at-least-1MB-of-stack-space-in-Cre.txt)

I believe that only the first one (0001-zeb....) is not upstreamed in plain wine yet.  I have only run this with Proton, not plain wine, so I'm not sure how the behavior will differ if you compile wine with the patches.  

You can also compile proton quite easily (instructions at the bottom of this page -- I would highly recommend the vagrant path: https://github.com/ValveSoftware/Proton) and if you do that path, then you have to delete the second half of the 0001-zeb... patch regarding /dlls/ucrtbase/tests/scanf.c before applying the patch since that file does not exist in Proton's wine yet.

**Comment by mozo78** [comment]
Thank you very much :)

**Comment by mozo78** [comment]
Yes, the game doesn't run with Wine nor with Wine-Staging. Can you, please, give me your patched Proton?

**Comment by doitsujin** [comment]
I was able to get this run with wine-staging 4.10 with the two patches mentioned in the original post.
![Bildschirmfoto-791](https://user-images.githubusercontent.com/25567304/59499979-d4ed3780-8e98-11e9-8e81-6120e4d9adec.png)

Note that on the AMD side it doesn't work with AMDVLK or the proprietary driver, only RADV can run it right now.

**Comment by mozo78** [comment]
Hmm, I applied the patches and it crashes at start. Can you give me your patched Wine please?
Thank you :)

**Comment by doitsujin** [comment]
Are you running latest dxvk as well? 1.2.1 **will** crash.

**Comment by mozo78** [comment]
I download the latest master from here:
https://haagch.frickel.club/files/dxvk/latest/64/bin/
Is that right?

**Comment by doitsujin** [comment]
Try this; maybe the build was too old.
[dxvk-master.tar.gz](https://github.com/doitsujin/dxvk/files/3291296/dxvk-master.tar.gz)

**Comment by mozo78** [comment]
Unforunately it crasjes again with this build. Is there something special about Wine components I must install? Or maybe I didn't compile Wine properly. I know how to apply patches and compile Wine and did it for many games but... I tried to compile it again with the pretty same result.

Can you give me your patched Wine?

**Comment by alasky17** [comment]
@mozo78 I uploaded my custom proton build to google drive: [link to drive folder](https://drive.google.com/drive/folders/12NNNflk6qFUbDgKyFVTi1YmVcxlXkV52?usp=sharing)

You will have to drop the newer dxvk into the build.  After you run a game with the proton build, it will automatically create a dist folder, and the dxvk 32 and 64 bit versions can go in dist/lib/wine/dxvk and dist/lib64/wine/dxvk respectively.

Hopefully one of the options will help :)

**Comment by mozo78** [comment]
Thank you very much :)

**Comment by rinaldus** [comment]
> @mozo78 I uploaded my custom proton build to google drive: [link to drive folder](https://drive.google.com/drive/folders/12NNNflk6qFUbDgKyFVTi1YmVcxlXkV52?usp=sharing)
> 
> You will have to drop the newer dxvk into the build. After you run a game with the proton build, it will automatically create a dist folder, and the dxvk 32 and 64 bit versions can go in dist/lib/wine/dxvk and dist/lib64/wine/dxvk respectively.
> 
> Hopefully one of the options will help :)

I unpacked the archive to ~/.steam/compatibilitytools.d, but Steam doesn't see new Proton build.

**Comment by alasky17** [comment]
@rinaldus I believe that you need some config file for the archive to work in compatibilitytools.d.  You can replace the contents of one of your proton versions from steamapps/common/ with the custom proton build instead (keep the folder name, eg steamapps/common/Proton\ 3.7).  

To get the original proton release version back later, you can verify the integrity of the Proton files (under the Library Tools tab) and if that doesn't delete the custom build automatically it will trigger it to re-download after you delete the proton folder you chose completely.  Hope this helps!

**Comment by Ashe** [comment]
Does anyone have an updated guide for this? Is it still working? I downloaded that google drive folder but I believe the technicalities are getting in the way.

Firstly, you have a `proton_dist.tar.-gz` in there. I extracted that first, then tried to place my `dxvk` folders over the top. However, I'm not sure which Proton version to get them from. I tried `Proton4.2` from `steamapps/common`.

Secondly, the `compatibilitytool.vdf` file. Here's the one I tried, and I created a name:

```
"compatibilitytools"
{
  "compat_tools"
  {
    "Proton-4.2-PLANETCOASTER-1" // Internal name of this tool
    {
      // Can register this tool with Steam in two ways:
      //
      // - The tool can be placed as a subdirectory in compatibilitytools.d, in which case this
      //   should be '.'
      //
      // - This manifest can be placed directly in compatibilitytools.d, in which case this should
      //   be the relative or absolute path to the tool's dist directory.
      "install_path" "."

      // For this template, we're going to substitute the display_name key in here, e.g.:
      "display_name" "Proton-4.2-PLANETCOASTER-1"

      "from_oslist"  "windows"
      "to_oslist"    "linux"
    }
  }
}
```
I have no idea if this is right or not.

Finally, every time I mess around with these files the game gets uninstalled. I made a backup, but I've installed the game 3 times now. ***To anyone reading this, backup your game first just in case it happens to you too.***

Any help would be appreciated as I got this for my birthday (today) :)

**Comment by Ashe** [comment]
Edit: Sorry for this being straight after my comment BUT:

It appears to work out of the box for me with `Proton.11-5` specifically.
