### ISSUE TITLE
WRC5:intel:err:   D3D11CreateDevice: Failed to create a DXGI factory

### ISSUE THREAD

**Issue by DenKos363** [doitsujin/dxvk#1095]
Hi. Could you please help with running the game using dxvk? According to regular launch, game has DirectX11 and DirectX9 support.
When I am running the game with DX11 - looks like it doesn't launch via dxvk (I am trying to get renderdoc for it, and I think, can't - because of the dxvk initialization error).

### Game launch command:
VK_ICD_FILENAMES=/home/ubutu/mesa_versions/mesa-git-14.06-iris/share/vulkan/icd.d/intel_icd.x86_64.json DXVK_HUD=fps,devinfo PROTON_LOG=1 %command% &> ~/game_log.txt

### Software information
Steam version of WNC 5

### System information
- GPU: HD Graphics 5500 (Broadwell GT2)
- Driver: Mesa 18.2.8 and Mesa 19.1.0-devel (git-cf652205cf) and Mesa 19.2.0-devel (git-8ead5bebdb)
- using Proton 4.2-7 (DXVK and Wine related to it)
upd - proton lower version doesn't launch the game at all (issues with searching game libs...)

### Log files
proton log with error https://gist.github.com/DenKos363/a75d5373000bb2f953401249b2ff266b

### Short logs:
`
info:  Game: WRC5.exe
info:  DXVK: v1.2-30-g8ba89c94
183022.603:0027:0028:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\openvr_api_dxvk.dll" at 0x2200000: native
183022.604:0027:0028:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\api-ms-win-core-synch-l1-2-0.dll" at 0xf2400000: builtin
183022.605:0027:0028:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\api-ms-win-core-fibers-l1-1-1.dll" at 0xf23e0000: builtin
183022.605:0027:0028:trace:loaddll:load_builtin_dll Loaded L"C:\\windows\\system32\\api-ms-win-core-localization-l1-2-1.dll" at 0xf23d0000: builtin
warn:  OpenVR: Failed to initialize OpenVR
info:  Required Vulkan extension VK_KHR_get_physical_device_properties2 not supported
info:  Required Vulkan extension VK_KHR_surface not supported
info:  Required Vulkan extension VK_KHR_win32_surface not supported
err:   DxvkInstance: Failed to create instance
err:   D3D11CreateDevice: Failed to create a DXGI factory
183022.622:0027:0028:warn:debugstr:OutputDebugStringA "  info : Creating video device\n"
`

upd - looks like question is general for my GPU model (as I understand, it should be supported by dxvk). I checked another game, also used dx11, and got the same output in logs.

Help please to sort out - where to find the root of this problem.

**Comment by Oschowa** [comment]
The root of your problem is that your vulkan setup is broken, have you verified that it works at all with `vulkaninfo` or `vkcube`? Also, vulkan support for your GPU is incomplete, so you'll likely face rendering issues or other borkeness, even if you get games to launch.

**Comment by DenKos363** [comment]
@Oschowa I checked vulkaninfo and vulkan-smoketest. Both work fine. And I am not sure what could be broken in vulkan setup, because I tested "system" one, and 2 compiled manually.
>Also, vulkan support for your GPU is incomplete
Is there any chance to check whether games should be launched successfully on this gpu? I tried to re-check issues related to this game with older dxvk, and was a bit confused when found out that game ran without dxvk, so my checks are not relevant now.

**Comment by Oschowa** [comment]
Generally, if dxvk fails to create an Instance, like it does it your case, it means your vulkan driver doesn't work or is non-existing. You could try to run the game with wined3d so it runs over OpenGL (`PROTON_USE_WINED3D=1`) and see if that works when forcing dx11. You could also try other games, if a game defaults to dx9, there is probably a reason for that.

**Comment by doitsujin** [comment]
Something definitely **is** broken on your setup. Are you sure that the game is a 64-bit game?

**Comment by DenKos363** [comment]
hm, now I even don't know. Game is launching using wine and opengl instead of dx11, but my goal is to run exactly using dx11.
About x32 x64 - I didn't check for sure, but when I used to apply mesa drivers (i965) exactly x64 - game launched normally. Usually in case if wrong driver was selected - game won't start (with error about EFL flags etc).
I will re-check drivers version and maybe reinstall the hole system, because I have no ideas, what could be set up in a wrong way.
Thank you for suggestions

**Comment by FurretUber** [comment]
It seems there are multiple problems on your current setup:

1) There is no 32-bit build. Looks like this game is 64-bit so it shouldn't be the problem, but this is still bad;
2) You set the new Vulkan json file but you did not set the new driver directory (`LIBGL_DRIVERS_PATH`);

When I have to specify a Mesa version, I set both `LIBGL_DRIVERS_PATH` and `VK_ICD_FILENAMES`. You are trying to set a supposedly newer Vulkan version but the drivers are still the old ones, 18.2.8, and 18.2.8 is still a bad version for Intel ANV. With 18.3 it started to get better and with 19.0 you should be comfortable for most games (still no Elite Dangerous: Horizons, however :frowning_face: ).

Whenever possible, match the version from the `LIBGL_DRIVERS_PATH` and `VK_ICD_FILENAMES`. Otherwise, unexpected problems can arise, as GPU hangs (Important: on Ubuntu 18.04 with 4.18 kernel, Intel ANV GPU hangs caused by **DXVK will hard crash the system**).

As a reference, here is my custom command line to run Elite Dangerous. It requires both 32 and 64-bit build because the game has a launcher. 

```
PROTON_NO_ESYNC=1 DXVK_CONFIG_FILE=/home/usuario/Documentos/dxvk.conf VK_ICD_FILENAMES=/usr/local/mesa64-19.0.2/share/vulkan/icd.d/intel_icd.x86_64.json:/usr/local/mesa32-19.0.2/share/vulkan/icd.d/intel_icd.i686.json LIBGL_DRIVERS_PATH=/usr/local/mesa64-19.0.2/lib/dri:/usr/local/mesa32-19.0.2/lib/dri %command%
```

**Comment by DenKos363** [comment]
thank you guys! I sorted out this issue simply in another system (manjaro). Game works using dxvk now (according to the information in logs)
