### ISSUE TITLE
err:module:import dll Loading library d3d11.dll

### ISSUE THREAD

**Issue by bailehang** [doitsujin/dxvk#1098]
Hi, 
I recently installed wine and dxvk on another operating system
```
$uname -a 
Linux localhost.localdomain 4.19.5-300.fc29.x86_64 #1 SMP Tue Nov 27 19:29:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
The difference with ubuntu is that apt is not installed...There is also a lack of official installation guidance.

So I tried to compile the wine 4.10 and dxvk from git by myself.
tip:I just compiled wine64，no wine, so I modified `setup_dxvk.sh` script，and just compiled dxvk x64

I use `setup_dxvk.sh` add x64 dll.so to wine
I can see the installed d3d10, d3d10_1, d3d11, dxgi in `winecfg`

When I finally run the game, the following error pops up:

```
0009:err:module:import_dll Loading library d3d11.dll (which is needed by L"Z:\\home\\white\xxxxxxxxxx.exe") failed (error c000012f).
0009:err:module:import_dll Loading library dxgi.dll (which is needed by L"Z:\\home\\white\xxxxxxxxxx.exe") failed (error c000012f).
```

How can I set up the d3d*.DLL correctly?
Thanks.

**Comment by doitsujin** [comment]
Try setting the DLL overrides to `native,builtin` instead.

Also, note that 32-bit games with your setup aren't going to work **at all** and that winelib builds are known to cause some issues.

**Comment by bailehang** [comment]
@doitsujin It still doesn't work

**Comment by doitsujin** [comment]
I mean you messed around with the setup script, that's entirely your issue and not mine.

**Comment by bailehang** [comment]
Because I didn't generate wine, I just generated wine64.
So `setup_dxvk.sh` in line 56 has err
```
winever=`$wine --version | grep wine`
```
There's no $wine

**Comment by doitsujin** [comment]
*sigh*

Copy the files manually to `windows/system32` and change the extension from `.dll.so` to just `.dll`, then **remove** the D3D11 and DXGI DLL overrides **entirely** since wine considers winelib builds to be `builtin`. Or use mingw for building.

DXVK currently does not support pure 64-bit prefixes because they are extremely uncommon and pretty much useless. I am aware that this is going to have to change with Ubuntu dropping all 32-bit support for good, but right now you have to figure things out on your own.

**Comment by bailehang** [comment]
Thanks for your explanation. Thanks for your patience. 
Should I use a WINE version less than 4.10 for 32-bit compilation?

**Comment by bailehang** [comment]
I downloaded the compiled wine dxvk and vulkansdk, the game worked perfectly.
Summary: compilation dependencies are hard to find in different operating systems.
