### ISSUE TITLE
Chivalry Medieval Warfare: validation error spam at main menu

### ISSUE THREAD

**Issue by roothorick** [doitsujin/dxvk#110]
### Software information
Game falls back to dx9 mode by default, but can be forced by specifying `-d3d11` on the command line. Don't know if this is a bug in dxvk, an issue elsewhere in Wine, or simply default behavior on Windows 7.

While at the main menu, the console floods with:
```
DS(ERROR): object: 0x0 type: 0 location: 7402 msgCode: 155191012: vkCreateFramebuffer(): VkFramebufferCreateInfo attachment #1 mip level 0 has dimensions smaller than the corresponding framebuffer dimensions. Here are the respective dimensions for attachment #1, framebuffer:
width: 1285, 1288
height: 723, 728
layerCount: 1, 1
The spec valid usage text states 'Each element of pAttachments must have dimensions at least as large as the corresponding framebuffer dimension' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkFramebufferCreateInfo-pAttachments-00882)
```

This flood continues into gameplay. Performance is extremely poor (6-12fps), likely as a result. Graphics look correct from a passing glance.

### System information
- GPU: Radeon RX 480
- Driver: Mesa 17.3.2
- Wine version: 2.21-staging
- DXVK version: git 3dea58d

### Apitrace file(s)
Under wined3d, loading to menu and immediately exiting.
https://roothorick.mooo.com/CMW.trace

### Log files
[CMW_d3d11.log](https://github.com/doitsujin/dxvk/files/1772819/CMW_d3d11.log)
[CMW_dxgi.log](https://github.com/doitsujin/dxvk/files/1772820/CMW_dxgi.log)

**Comment by doitsujin** [comment]
Should be fixed as of Version 0.50.
