### ISSUE TITLE
The Witcher 3 Texture Flickering and Weird Colors

### ISSUE THREAD

**Issue by index-0** [doitsujin/dxvk#1102]
I've been trying to play this game since December, and I've try changing every in-game setting and with different drivers and wine versions, but always gives me the same issue, the texture flickers almost everywhere, and the textures gets white and the horse blue in most areas and sometimes everything looks bright, and those colors changes in textures that I mentioned are just a tiny bit of all the things that can get weird colors, but there are some areas where everything looks fine. 

Here's a video I recorded about the issue:
https://drive.google.com/file/d/1_X9AWal7toq67aueOHo5MKY18I5CGz_z/view?usp=sharing

and here's a picture:
![2019-06-19-09:05:27-screenshot](https://user-images.githubusercontent.com/22756958/59773224-e22c6c80-9272-11e9-8ac4-3ccc0d45eef5.png)

### Software information
The Witcher 3 - latest version
I've try in low setting with everything disabled and in ultra with everything enabled and I've try with different resolutions

### System information
- GPU: Radeon RX 580
- Driver: Mesa 19.1.0 (DRM 3.30.0, 5.1.7-gentoo, LLVM 8.0.0)
- Wine version: wine 4.9 (staging) and proton 4.2-7
- DXVK version: 1.2-30-g8ba89c94

### Apitrace file(s)
I tried to get the apitrace file, but I get like 1 frame per minute in the lowest settings and doesn't output a trace file, I don't know if this is normal, but I'm trying again rn.

### Log files
- d3d11.log: [witcher3_d3d11.log](https://github.com/doitsujin/dxvk/files/3306479/witcher3_d3d11.log)
- dxgi.log: [witcher3_dxgi.log](https://github.com/doitsujin/dxvk/files/3306482/witcher3_dxgi.log)

**Comment by doitsujin** [comment]
This game is known to work fine with DXVK on your hardware and driver, something must be horrendously wrong on your end.

**Comment by doitsujin** [comment]
Looks like your DXVK build is the one from Proton, which should be fine.

No issues on my end with an RX 480, Mesa 19.0.6, LLVM 8.0.0 and the exact same DXVK build. I'm on Arch, btw.
![Bildschirmfoto-797](https://user-images.githubusercontent.com/25567304/59800715-9ec01580-92e7-11e9-8ceb-7667dfc97332.png)

**Comment by index-0** [comment]
I was able to reproduce the same bug on windows 10
![Captura de pantalla (1)](https://user-images.githubusercontent.com/22756958/59930208-11c0ad80-9408-11e9-8bdc-17c15d90f0b1.png)

and I found something similar on cdprojektred forum from 2015:
[https://forums.cdprojektred.com/index.php?threads/graphics-colours-seem-to-be-inverted-everywhere-in-gameplay.47878/](url)

So is not dxvk related, sorry for the inconvenience.
