### ISSUE TITLE
AC: Syndicate with Mesa 19.1.1

### ISSUE THREAD

**Issue by SR-dude** [doitsujin/dxvk#1106]
There was a problem with the latest mesa point release.  Mesa 19.1.1  gave me a white screen
when playing Assassin's Creed Syndicate. It painted the HUD, though . 

 I decided to downgrade back to  19.1.0. 

from inxi:
`Graphics:  Display: server: X.Org 1.20.5 driver: amdgpu unloaded: fbdev,modesetting resolution: 1600x900~60Hz 
           OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.30.0 5.1.14 LLVM 8.0.0) v: 4.5 Mesa 19.1.0 (git-1517811f4f) 
...
Kernel: 5.1.14 x86_64 bits: 64 Desktop: LXDE 0.10.0
`

**Comment by K0bin** [comment]
If you it works on Mesa 19.1.0 and doesn't work on 19.1.1, wouldn't the Mesa bugtracker be a better place to report this?

**Comment by SR-dude** [comment]
Yes, you're are right of course. It is more likely that my llvm 8.0 is old and mesa developers are using
svn.

**Comment by SR-dude** [comment]
If I'm off tomorrow I'll do a git bisect on mesa.

**Comment by SR-dude** [comment]
Recompiling 19.1.1 didn't give me a white screen. So,  there is nothing to bisect. I did upgrade dxvk. Maybe that fixed it?
