### ISSUE TITLE
dxvk 1.2.3 fails to CreateSwapChain()

### ISSUE THREAD

**Issue by niko1point0** [doitsujin/dxvk#1109]
I am using Windows 10, Intel i7-7700hq, 8gb DDR4 RAM, GTX 1050.

I tried to use DXVK 1.2.3 d3d11.dll with Unigine Heaven Benchmark 4.0 (which is free for anyone to download), and I get the error message:

Direct3D11 error: 0x80004002
CreateSwapChain() failed

**Comment by K0bin** [comment]
When stuff fails there, it's usually caused by a setup issue. Keep in mind that Windows is unsupported and may not work in some cases.

Can you post the DXVK logs that the issue template explicit asks for?

**Comment by Joshua-Ashton** [comment]
Your issue is you are not using **both** the **d3d11.dll** and **dxgi.dll**s together. This is necessary to make it work -- else it fails on the swapchain creation as that calls through to the real Windows' DXGI which doesn't interface nicely with DXVK's.

**Comment by doitsujin** [comment]
What Josh said, and if that still doesn't work - well, it **does** work fine on Linux and that's really all I care about. Not all games or applications that work with DXVK on Linux also work on Windows, mostly due to DLL loading mechanisms.

**Comment by niko1point0** [comment]
Copying DXGI.dll did not fix the bug. I tested Crash Bandicoot N Sane Trilogy without DXGI.dll and that worked fine

**Comment by K0bin** [comment]
> I tested Crash Bandicoot N Sane Trilogy without DXGI.dll and that worked fine

Probably because it didn't even pick up DXVK and just used Windows D3D11.

**Comment by niko1point0** [comment]
It definitely picked up DXVK, in Crash Bandicoot. I saw DXVK's UI which shows the Vulkan version, and the frame rate

**Comment by doitsujin** [comment]
It is impossible for DXVK to work on top of Windows' DXGI implementation.

**Comment by niko1point0** [comment]
Weird, maybe I did copy DXGI.dll for Crash bandicoot, even though I don't remember doing so. 

Regardless, DXVK doesn't work for Unigine Heaven Benchmark, even with DXGI.dll, it fails to create swapchain

**Comment by doitsujin** [comment]
Heaven fails to create a swap chain because it loads `dxgi.dll` from your Windows install, but `d3d11.dll` from DXVK. This can happen **even if** you copied the file to the right location due to DLL load order shenanigans.

Nonsense like this is exactly why I don't support Windows, it's not uncommon at all to run into issues like this and trying to figure out what exactly is going on is just a massive waste of time.

**Comment by Joshua-Ashton** [comment]
You did put it in the same folder you placed the d3d11.dll, right?

**Comment by niko1point0** [comment]
Yes
