### ISSUE TITLE
dgVoodoo crash

### ISSUE THREAD

**Issue by xDShot** [doitsujin/dxvk#1111]
### Software information
dgVoodoo crashes (both dgVoodooCpl.exe configurator and targeting games)

### System information
- GPU: Intel HD4600 and AMD Radeon 8750M
- Driver: mesa 19.1.1
- Wine version: wine-staging 4.11
- DXVK version: 1.2.3

### Apitrace file(s)
[dgVoodooCpl.zip](https://github.com/doitsujin/dxvk/files/3345507/dgVoodooCpl.zip)

### Log files
- d3d11.log: empty
- dxgi.log: [dgVoodooCpl_dxgi.log](https://github.com/doitsujin/dxvk/files/3345513/dgVoodooCpl_dxgi.log)

**Comment by xDShot** [comment]
### Software information
[Sacred Gold](https://www.gog.com/game/sacred_gold)

### System information
Same

### Apitrace file(s)
https://transfer.sh/133gfm/Sacred.7z

### Log files
- d3d11.log: empty
- dxgi.log: [Sacred_dxgi.log](https://github.com/doitsujin/dxvk/files/3345551/Sacred_dxgi.log)

**Comment by mozo78** [comment]
It depends on dgVoodoo, not on DXVK. If it crash with DXVK, it probably will not run on Windows either. I recorded some games with dgVoodoo and DXVK, just to name a few:
https://www.youtube.com/watch?v=gbgyFX6iOpA&t=41s
https://www.youtube.com/watch?v=Iu9sHgq1dTc
https://www.youtube.com/watch?v=mLivDIgsymI
https://www.youtube.com/watch?v=-sL216uXVUQ

**Comment by Joshua-Ashton** [comment]
The trace of the dgVoodoo cpl doesn't actually work on Windows here 🐸 

I'll see if there's anything I can see on the real dgVoodoo.

**Comment by Joshua-Ashton** [comment]
Yep, no issues with dgVoodooCpl.exe + DXVK (d3d11 + dxgi) for me. It works fine.

Obviously a Wine bug or an issue in the DgVoodoo version you are using. 😄

**Comment by xDShot** [comment]
Yeah, didn't notice I was using old version. With latest (v2.55.4.1) the configurator launches, but the game still crashes, although it was confirmed to be working on windows.

**Comment by xDShot** [comment]
new trace https://transfer.sh/14IInz/Sacred_dgv2.55.4.1.7z

**Comment by doitsujin** [comment]
Your trace does not reproduce the crash. Please **don't** record traces with dxvk to debug crashes because the resulting trace files **will end before the crash happens**.

**Comment by doitsujin** [comment]
dgvoodoo is also using your Haswell GPU, which is not supported on DXVK.

**Comment by xDShot** [comment]
>Please don't record traces with dxvk

It wasn't

**Comment by doitsujin** [comment]
In that case, all I can say is "works for me" :man_shrugging:

**Comment by xDShot** [comment]
>export DXVK_FILTER_DEVICE_NAME=AMD

Woah this magic var did actually help thanks!
