### ISSUE TITLE
Black Screen with The Sinking City

### ISSUE THREAD

**Issue by SR-dude** [doitsujin/dxvk#1113]
### Software information
Epic's exclusive title: The Sinking City

### System information
From inxi:
System:    Host: ANTHONYJ Kernel: 5.1.15 x86_64 bits: 64 Desktop: LXDE 0.10.0 
           Distro: Linux From Scratch SVN-20190519 20190519-systemd/multilib 
Graphics:  Display: server: X.Org 1.20.5 driver: amdgpu unloaded: fbdev,modesetting resolution: 1600x900~60Hz 
           OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.30.0 5.1.15 LLVM 8.0.0) v: 4.5 Mesa 19.1.1 (git-22eddd8b9d)
- Wine version:  Tested both 4.11(Staging) and ge-protonified-4.10-x86_64(from Lutris)
- DXVK version:  1.2.3

### Log files
- d3d11.log:
[TSCGame-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/3359131/TSCGame-Win64-Shipping_d3d11.log)

- dxgi.log: 
[TSCGame-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/3359132/TSCGame-Win64-Shipping_dxgi.log)

- wine ouput: [TSCconsole.log](https://github.com/doitsujin/dxvk/files/3359130/TSCconsole.log)

### Problem Summary
Epic's exclusive title: The Sinking City
Playing the game via Lutris  gave me a back screen with a message at the bottom stating that it was compiling shaders, then the screen went totally black.  The lines in the wine log involving: "Unhandled modifier 0x800000c2, 0x00155543 and 0x80000042" are spammed continuously. I excised those  from the posted log above.

**Comment by doitsujin** [comment]
Your console log indicates that you're using wined3d and not DXVK. Also, this game uses mfplat, which is probably why you're getting a black screen in the first place since that's not implemented properly in wine yet.

The game [does work](https://www.youtube.com/watch?v=aUjUDkygKpA) with DXVK, but may require some manual setup.

**Comment by SR-dude** [comment]
I got it working. Thanks!

Do you mean DXVK doesn't output any lines at the wine terminal and if I see lines like those then the wined3d backend is live?

**Comment by doitsujin** [comment]
> 01ae:fixme:d3d11:d3d_blend_state_create Per-rendertarget blend not implemented.
> 01ae:fixme:d3d_shader:shader_sm4_read_instruction_modifier Unhandled modifier 0x80000042.

This kind of stuff most definitely **is** wined3d-related. DXVK prints the same stuff that it writes to the log files into the console, but some games may "eat" that output so you may see nothing.

**Comment by SR-dude** [comment]
OK, I forgot to reinstall dxvk when switching wine versions.
