### ISSUE TITLE
 did i install dxvk correctly ? because nothing works 

### ISSUE THREAD

**Issue by iqrulltion** [doitsujin/dxvk#1118]
i am using wine staging 4.11 , beside winetricks last version. i installed dxvk /vulkan for ubuntu (plus runtime sdk from winetricks )/meson/MinGw64  etc 

but with starting games notice i said " games " there is a same result  almost " missing directx 11 please update it or install it etc as i remember  ) but this message disappeared when i made "dxgi" built-in not native  ...  

but the logs from "dxvk " are still the same almost if not "all"  so it does not matter the name of "target" ..
in simple nothing works with "dxvk" for me ..

the logs .. ( i might provide more info if I have to )

[LOGS.tar.gz](https://github.com/doitsujin/dxvk/files/3370525/LOGS.tar.gz)

thanks.

**Comment by Joshua-Ashton** [comment]
For d3d11 games you need to have **both** d3d11.dll **and** dxgi.dll for it to work.

**Comment by iqrulltion** [comment]
> For d3d11 games you need to have **both** d3d11.dll **and** dxgi.dll for it to work.

i changed "dxgi" from " native" to "built-in" for solving the missing directx11 error. maybe I read it here or there when i was searching about the error. but anyway i made it as default "native"  again .. when that did not solve the main problem ..

**Comment by doitsujin** [comment]
Looking at the logs, you don't seem to have any Vulkan driver or the loader libraries installed. Make sure to also install the corresponding 32-bit libraries for your distro.

**Comment by iqrulltion** [comment]
I thought i installed vulkan i can see "libvulkan-dev/libvulkan1/libvulkan1:i386/mesa-vulkan-divers/mesa-vulkan-drivers:i386/vulkan-utils  packages are installed , beside the sdk and the runtime. 

1-  i just saw "wiki" and found 2 names AMDVLK and AMDRADV . i searched that and reached 
the AMDVLK page on github  is that what i should install ?

2- https://github.com/KhronosGroup/Vulkan-Loader ? same question ?
 
**3-  very important:** can you explain more about this part " **corresponding 32-bit libraries** " ? 

it would be better if you confirmed what above  so i do not mess with the graphics driver or install something not necessary ..

**Comment by doitsujin** [comment]
> 3- important: can you explain more about this part " corresponding 32-bit libraries " ?

I don't know which part of that you don't understand, but you need both the 32-bit and 64-bit packages of your Vulkan driver and loader, i.e. the :i386 variants. Apparently you already did that.

Anyway, no idea what's wrong, but the DXVK log shows that Vulkan just isn't working on your system.

**Comment by iqrulltion** [comment]
> Apparently you already did that, so no reason to worry.
> Anyway, no idea what's wrong, but the DXVK log shows that Vulkan just isn't working on your system.

so i am on my own to find out that and fix that , but any way i just want  to make this point clear and then i might not comment a new comment until i find something new or fix it .

1-so theoretically and practically all i need to make " dxvk" works fine for normal cases is
" dxvk for wine+ Vulkan driver + Meson +MinGW64 "  ?

**Comment by Oschowa** [comment]
You don't need meson or mingw if you only want to use dxvk. Just make sure your vulkan driver works for 64 and 32 bit applications (how you do this will depend on your distro), and install dxvk as described here https://github.com/doitsujin/dxvk#how-to-use

**Comment by iqrulltion** [comment]
> Just make sure your vulkan driver works for 64 and 32 bit applications (how you do this will depend on your distro), and install dxvk as described here https://github.com/doitsujin/dxvk#how-to-use

The packages for ubuntu i named above are installed , i might reinstall them or search more about that but i am confused.  but as start this is where as i remember installed vulkan from https://linuxconfig.org/install-and-test-vulkan-on-linux
 
1- i just want to know what " the update " i added means ?
