### ISSUE TITLE
Feature Request: DXVK_HUD display for x seconds and then turn it off

### ISSUE THREAD

**Issue by 7oxicshadow** [doitsujin/dxvk#1119]
Would it be difficult to add a DXVK_HUD parameter to only show the HUD for say 30 seconds and then turn it off (or fade out)?

This might seem like an odd request but I have a number of different wine prefixes and I don't always know what version of DXVK they are running. Having the HUD on-screen for x seconds on startup would be a good way of keeping track of things without the distraction during gameplay.

**Comment by doitsujin** [comment]
The DXVK version will also be written to the log files, you could check that. I'm not really keen in implementing anything that makes the HUD more complicated than necessary.

**Comment by shmerl** [comment]
Is there a way to toggle HUD based on some keyboard key? That could be really useful and will cover the above use case as well.

**Comment by doitsujin** [comment]
> Is there a way to toggle HUD based on some keyboard key combination?

Just **NO**.

DXVK is a D3D11 translation layer and **not something that should mess with the user's keyboard input**. Hooking keyboard events is guaranteed to break *something* and create confusion, then the next thing people would ask for is being able to rebind the key to something else, and we end up with a bloated, broken solution that is a pain in the ass to maintain and has **nothing** to do with translating D3D11 to Vulkan in the first place.

This is a **really** terrible idea.
