### ISSUE TITLE
Fallout 4 (regression)

### ISSUE THREAD

**Issue by t14462** [doitsujin/dxvk#1122]
### Software information
Fallout 4

### System information
- GPU: RX560
- Driver: RADV
- Wine version: wine-4.12.1.r3.g5ed9211e ( TkG Staging Esync )
- DXVK version: 1.2.3

### Log files
[Fallout4_dxgi.log](https://github.com/doitsujin/dxvk/files/3383656/Fallout4_dxgi.log)
[Fallout4_d3d11.log](https://github.com/doitsujin/dxvk/files/3383657/Fallout4_d3d11.log)

On launching game shows black screen with blink of loading indicator, and just goes to background

**Comment by Joshua-Ashton** [comment]
Can you give some information about your Mesa version?

**Comment by doitsujin** [comment]
Works fine for me on Proton. Please make sure that this isn't just an issue with your wine build, and give more info about the settings used, etc.
![Bildschirmfoto-847](https://user-images.githubusercontent.com/25567304/61091329-0f1f0a00-a442-11e9-93e7-115dae459380.png)

**Comment by t14462** [comment]
Mesa 19.1.1, LLVM 8

Maybe it's fine on ACO, so i just wait for 19.2 release with ACO

**Comment by t14462** [comment]
Yeah, this was wine bug. Staging from repo running game normally
