### ISSUE TITLE
my list of games that don't work with dxvk DONT DELETE PLEASE

### ISSUE THREAD

**Issue by RedFred98** [doitsujin/dxvk#1126]
just cause 2
euro truck simulator 2
fallout
fallout tactics
gumboy: crazy adventures
huniepop
team fortress 2
bioshock infinite

all of them either don't use dxvk which they should cause i added it or crash? I add the d3d11.dll to the folder and it either crash to desktop or something about swapchain

i am using vega 56 on windows 8.1 professional with latest updates and latest driver i downloaded yesterday

PLEASE DO NOT DELETE THE ISSUE UNTIL ALL THE PROBLEM IS SOLVED

**Comment by RedFred98** [comment]
by the way i use the new 1.3

**Comment by hch12907** [comment]
No logs, no renderdocs, using Windows which is not officially supported...

Honestly, this issue is useless.

**Comment by varris1** [comment]
> Honestly, this issue is useless.
especially when most of those games run on d3d9

**Comment by doitsujin** [comment]
Of course none of the games work when **most of them aren't even D3D11 games**. Windows 8.1 hasn't had active AMD driver support for ages either. Bioshock Inifinite works fine with DXVK on Linux.

Please do some basic research before filing bug reports that just waste people's time.

**Comment by RedFred98** [comment]
i installed the windows 7 driver on it, and it works fine for other things and thats what is reccomended

**Comment by RedFred98** [comment]
i fixed it!

**Comment by RedFred98** [comment]
i added dxgi.dll and now it works 😸

**Comment by RedFred98** [comment]
btw some other games still dont use it? I check using bandicam to see what rendering it is using any ideas guys?

**Comment by K0bin** [comment]
- Windows is unsupported
- AMDs Vulkan driver for Windows isn't particularly great
- DXVK **can't** work without it's dxgi.dll on Windows
- some games don't work with DXVK on Windows and there's nothing we can do there
