### ISSUE TITLE
Fallout 76 Slowdowns

### ISSUE THREAD

**Issue by ZachBacon** [doitsujin/dxvk#1128]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Name of the game, settings used etc.
Fallout 76 set on ultra for settings

### System information
- GPU: NVidia GTX 1660
- Driver: 431.36
- Wine version: None - Windows 10 Pro
- DXVK version: 1.3

### Apitrace file(s)
- Put a link here: https://www.dropbox.com/s/pj3lxw97supv3b0/Fallout76.tar.xz?dl=0

### Log files
- d3d11.log: [Fallout76_d3d11.log](https://github.com/doitsujin/dxvk/files/3389412/Fallout76_d3d11.log)
- dxgi.log: [Fallout76_dxgi.log](https://github.com/doitsujin/dxvk/files/3389413/Fallout76_dxgi.log)

**Comment by doitsujin** [comment]
What do you mean by "slowdowns"? Isn't it kind of normal for this game to be poorly optimized?

**Comment by ZachBacon** [comment]
Not so much stutter, as it slows to a crawl with dxvk, with native d3d11, the building I'm entering in the apitrace, doesn't happen. Just happens with dxvk. Which makes me wonder if there's a call being made that isn't being handled properly that the game is making.

**Comment by doitsujin** [comment]
Some more info would be useful (GPU bound or CPU? Any suspiciously high numbers in the HUD when using `DXVK_HUD=full`)?
