### ISSUE TITLE
Scrap Mechanic: "Unable to find suitable graphics adapter." on AMD/Intel Mesa

### ISSUE THREAD

**Issue by Friz64** [doitsujin/dxvk#1129]
Scrap Mechanic refuses to launch with AMD/Intel Mesa. The game crashes with this error:
![image](https://user-images.githubusercontent.com/20155479/61183528-bc607080-a642-11e9-9432-635872d8267d.png)
This has been confirmed by a few AMD/Intel Mesa users on [protondb](https://www.protondb.com/app/387990).

### System information
- GPU: AMD RX 580 (AMD RADV POLARIS10 (LLVM 7.0.1))
- Proton version: Proton 4.2-9

### Log files
```13:34:12 (1) [Default] Initializing Logger
13:34:12 (1) [System] Operating system: Win 7 Service pack 1
13:34:12 (1) [System] Permissions for C:/users/steamuser/Application Data - Others write | Others read | Group write | Group read | Owner write | Owner read
13:34:12 (1) [System] Permissions for C:/users/steamuser/Local Settings/Application Data - Others write | Others read | Group write | Group read | Owner write | Owner read
13:34:12 (1) [System] Permissions for .. - Others write | Others read | Group write | Group read | Owner write | Owner read
13:34:12 (1) [Default] Initializing ResourceManager
13:34:12 (1) ERROR: d:\jenkinsworkspace\scrapmechanic\contraptioncommon\resources\resourcemanager.cpp:89 $GAME_DATA/Objects/Mesh/fittings/obj_fittings_fusebox.mesh is marked for upgrade, but the file exists. Ignoring upgrade pair
13:34:12 (1) ERROR: d:\jenkinsworkspace\scrapmechanic\contraptioncommon\renderer\dx11\d3d11_device.cpp:127 DirectX Error "CreateDXGIFactory" failed. Error code: 0x80004005

13:34:12 (1) [Render] ERROR: d:\jenkinsworkspace\scrapmechanic\contraptioncommon\renderer\dx11\d3d11_renderer.cpp:59 Adapter search failed
Shutting down...
```

The game [works fine on DXVK](https://github.com/doitsujin/dxvk/issues/1116#issuecomment-509120723) using the proprietary NVIDIA driver since [this patch](https://github.com/doitsujin/dxvk/pull/1117) was introduced, but this is unrelated to this issue since the game still crashes with same error on DXVK master.

**Comment by K0bin** [comment]
Please also post the DXVK log files and an apitrace.

**Comment by doitsujin** [comment]
Can you **please** not straight-up ignore the issue template and post the DXVK logs? There's a reason why I'm asking for those in the issue template, it's getting really annoying to have to ask twice for them on every single bug report.

**Comment by Friz64** [comment]
Sorry for not providing the log files directly. I was able to create a API Trace: [ScrapMechanic.trace.tar.gz](https://github.com/doitsujin/dxvk/files/3389879/ScrapMechanic.trace.tar.gz)

Here's a dump i did:
```
$ wine apitrace.exe dump ScrapMechanic.trace 
// process.name = "Z:\\media\\hdd1\\SteamLibrary\\steamapps\\common\\Scrap Mechanic\\Release\\ScrapMechanic.exe"
0 CreateDXGIFactory(riid = IID_IDXGIFactory, ppFactory = ?) = E_FAIL
0009:fixme:kernelbase:AppPolicyGetProcessTerminationMethod 0xfffffffa, 0x33fe44
```

It seems like there was no DXVK log generated in the game directory though.

**Comment by doitsujin** [comment]
Proton disables those by default, you need to set the Steam launch options for this game to `PROTON_LOG=1 %command%` in order to enable it.

**Comment by Friz64** [comment]
[ScrapMechanic_dxgi.log](https://github.com/doitsujin/dxvk/files/3389887/ScrapMechanic_dxgi.log)

**Comment by varris1** [comment]
Error on your end. Do you have the vulkan drivers for 64 **and** 32 bit installed?

**Comment by doitsujin** [comment]
That's definitely a setup issue on your end then. Make sure you have the 32-bit Vulkan driver and libraries installed.

**Comment by Friz64** [comment]
That was indeed the problem! After installing the 32-bit Vulkan Drivers (which many people don't have apparently), applying the `RSGetViewports` fix and removing the apitrace DirectX libraries, it starts up perfectly. Now i have 60 FPS with max settings and no graphical glitches. Thank you so much for your help.
