### ISSUE TITLE
Hitman (2016): Gameplay doesn't render, spams validation errors

### ISSUE THREAD

**Issue by roothorick** [doitsujin/dxvk#113]
### Software information
Hitman (2016) menus look perfect, gameplay has tutorial overlays but otherwise everything is black. During gameplay, console is flooded with validation errors.

### System information
- GPU: Radeon RX 480
- Driver: Mesa 17.3.2
- Wine version: 2.21-staging
- DXVK version: git 3dea58d

### Apitrace file(s)
Not possible due to DRM

### Log files
Console log includes output from Steam due to DRM
[HITMAN_console.log](https://github.com/doitsujin/dxvk/files/1773221/HITMAN_console.log)
[HITMAN_d3d11.log](https://github.com/doitsujin/dxvk/files/1773222/HITMAN_d3d11.log)
[HITMAN_dxgi.log](https://github.com/doitsujin/dxvk/files/1773223/HITMAN_dxgi.log)

**Comment by doitsujin** [comment]
581e505f54bcb7d852183665a1b54af7e305a406 fixes remaining rendering issues.
![bildschirmfoto-670](https://user-images.githubusercontent.com/25567304/39951013-339ab994-5586-11e8-9d60-a392c5baed34.png)
