### ISSUE TITLE
Heroes of The Storm: graphics freeze on intel nuc NUC8i7BEH

### ISSUE THREAD

**Issue by samzilverberg** [doitsujin/dxvk#1130]
### Software information

Heroes of the Storm
Low settings

### System information

- Intel NUC8i7BEH
- OS: Manjaro with kernel 4.19.56-1-MANJARO
- GPU:  Intel Iris Plus Graphics 655 GPU
- Driver: mesa 19.1.99 (installed from aur https://aur.archlinux.org/packages/mesa-git/)
- Wine version: ge-protonified-4.10-x86_64
- DXVK version: 1.3

### Log files

[HeroesOfTheStorm_x64_d3d11.log](https://github.com/doitsujin/dxvk/files/3390532/HeroesOfTheStorm_x64_d3d11.log)
[HeroesOfTheStorm_x64_dxgi.log](https://github.com/doitsujin/dxvk/files/3390533/HeroesOfTheStorm_x64_dxgi.log)

### Apitrace file(s)

I wasn't able to get this working before opening the issue.
I will do some more googling tomorrow to understand how to do this.

### description of problem

This NUC, according to some reviews/blogs, is able to run HOTS on medium settings on Windows. so I figured it might work as well on linux on low settings.

I'm able to run the game without dxvk with semi-playable results.

when using dxvk, the game can start, but will freeze after starting some "heavier" graphics process such as switching to the "play" screen from the default "home" screen, or even just by opening/closing the chat a couple of times.
I put some effort and read other issues that i thought are related, I've enabled the vulkan validation layers, tried a couple of dxvk versions, some older wine versions (via lutris) and more.

the wine logs are not very helpful (i ran with WINDEBUG=-all), the interesting line is:
```
INTEL-MESA: error: ../mesa/src/intel/vulkan/anv_device.c:2646: GPU hung on one of our command buffers (VK_ERROR_DEVICE_LOST)
```
from reading other issues on this repo I gather the error might be somewhere else entirely (mesa?). 

could you give me some pointers (links?) on how/what to debug next?
is running games using DXVK on an intel nuc a lost cause? or is there hope? :)

**Comment by doitsujin** [comment]
You should probably report this to Mesa as it seems to be a driver issue.

**Comment by werman** [comment]
Tested on HD 630 and it is the same issue as in "Monopoly Plus" and "Alien: Isolation" (https://bugs.freedesktop.org/show_bug.cgi?id=109203).

The simplest workaround will be adding `INTEL_DEBUG=nohiz` environment variable, however you will suffer some performance penalty.

**Comment by samzilverberg** [comment]
adding `INTEL_DEBUG=nohiz` to env vars does indeed prevent game from hanging :)
the game is now just a little more playable :laughing: , at least its a step in the right direction.

what a magical debug flag!  its not even documented in [the mesa docs](https://mesa-docs.readthedocs.io/en/latest/envvars.html?highlight=intel_debug).
i was able to find some hint of what it is on the mesa repo but the graphical terms are way beyond my knowledge.

werman already added a comment on an existing bug at mesa, which is probably where the bug is at, so i'll close the issue.

**Comment by werman** [comment]
Finally, the underlying cause was found by Jason and there is already a merge request to fix the hang which probably would be merged soon https://gitlab.freedesktop.org/mesa/mesa/merge_requests/1347.

**Comment by samzilverberg** [comment]
i tried it out, it works 🎉 
performance is a little better than with the `nohiz` flag.
game did get the whole OS stuck after around an hour, with no way out other than hard reboot (also tried with alt+ctrl+f1-12... ).
but thats a different problem to try and debug sometime later 👍

**Comment by DenKos363** [comment]
hey
> game did get the whole OS stuck after around an hour, with no way out other than hard reboot (also tried with alt+ctrl+f1-12... ).
I left the game (on tutorial) for a hole night. Also I played yesterday and today (finished the tutorial actually) - and didn't get any hangs. I used the same HW as and in previous issue (KBL, HD 630 gpu).
So possibly your case now related exactly to your gpu model. But still - would be great to get logs or reproduce steps for this hang :)

**Comment by samzilverberg** [comment]
@DenKos363 sorry for the late reply.
i've been playing without experiencing any "OS Hangs" problems anymore.
whatever I experienced back then in July must have been caused by something else, and anyway isn't reproducible in any simple way.
