### ISSUE TITLE
EVE Online: Performance regression in 1.2.0 and higher

### ISSUE THREAD

**Issue by AaronOpfer** [doitsujin/dxvk#1131]
When using DXVK 1.2.0 and greater, EVE Online suffers significant performance degradation. Version 1.1.1 is the last version where performance is excellent where viewing the outside of a citadel gave me 110FPS. 1.2.0 shows 75FPS for the same scenario. In addition, visual glitches began to occur in some scenarios (ambient gas clouds in deadspace pockets, for example).

I have an API trace of undocking from a busy station in hopes that it allows you to see the FPS degradation. I might file a separate issue for the visual artifacts since I did not capture them in this API trace.

### Software information
EVE Online, high graphics settings

### System information
- GPU: NVIDIA GTX 1060 6GB
- Driver: 4.6.0 NVIDIA 418.74
- Wine version: tkg-4.6
- DXVK version: 1.2.0

### Apitrace file(s)
[removed]

### Log files
For some reason I was unable to locate any DXVK logfiles. I think lutris might be fighting me for these.

**Comment by doitsujin** [comment]
Apitraces aren't really useful to debug performance regressions. Can you bisect this to the exact commit which introduced the regression? Same thing would be appreciated for the rendering issue, although an apitrace will be needed to debug that.

**Comment by AaronOpfer** [comment]
Bisect says the first bad commit is 45be1dfb53ff56d637c1c6e0ea6f9ab2b5f11a05

**Comment by Joshua-Ashton** [comment]
Curious, can you try my branch and see if it helps the issue at all?

https://github.com/Joshua-Ashton/dxvk/tree/d3d11-query-flush

**Comment by AaronOpfer** [comment]
@Joshua-Ashton your branch appears to fix the issue.

**Comment by doitsujin** [comment]
That's annoying, but unfortunately, Joshua's branch will break Fallout 4 and potentially other games that don't behave correctly, so applying it isn't really an option.

**Comment by doitsujin** [comment]
Actually, can you test if https://github.com/doitsujin/dxvk/tree/dxvk-donotflush fixes the performance issues as well?

**Comment by AaronOpfer** [comment]
@doitsujin that branch also seems to have full performance.

**Comment by doitsujin** [comment]
Alright, I'll merge it then. Thanks
