### ISSUE TITLE
winetricks stopped pulling dxvk

### ISSUE THREAD

**Issue by WiseFerret** [doitsujin/dxvk#1132]
As of version 1.3, the command "winetricks --force dxvk" stopped working. Is this the correct place to report it?
This is what I get:

yotam@ape:~$ winetricks --force dxvk
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20181203 - sha256sum: b4b29a961905bfed1db98f10e2f09a356b719861fc8602ffbf813a22579b2848 with wine-4.12.1 (Staging) and WINEARCH=win64
Executing w_do_call dxvk
Executing load_dxvk 
Executing cd /tmp/winetricks.v0iPh71Z
Downloading https://raw.githubusercontent.com/doitsujin/dxvk/master/RELEASE to /tmp/winetricks.v0iPh71Z
--2019-07-15 21:34:58--  https://raw.githubusercontent.com/doitsujin/dxvk/master/RELEASE
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.12.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.12.133|:443... connected.
...הבושת תלבקל ןיתממ ,החלשנ HTTP תיינפ 200 OK
Length: 6 [text/plain]
Saving to: ‘RELEASE’

RELEASE             100%[===================>]       6  --.-KB/s    in 0s      

2019-07-15 21:34:59 (439 KB/s) - ‘RELEASE’ saved [6/6]

Executing cd /home/yotam
Executing cd /home/yotam/.cache/winetricks/dxvk
Downloading https://github.com/doitsujin/dxvk/releases/download/v1.3.0/dxvk-1.3.0.tar.gz to /home/yotam/.cache/winetricks/dxvk
--2019-07-15 21:34:59--  https://github.com/doitsujin/dxvk/releases/download/v1.3.0/dxvk-1.3.0.tar.gz
Resolving github.com (github.com)... 140.82.118.3
Connecting to github.com (github.com)|140.82.118.3|:443... connected.
...הבושת תלבקל ןיתממ ,החלשנ HTTP תיינפ 404 Not Found
2019-07-15 21:35:00 ERROR 404: Not Found.

Executing cd /home/yotam/.cache/winetricks/dxvk
Downloading https://web.archive.org/web/2000/https://github.com/doitsujin/dxvk/releases/download/v1.3.0/dxvk-1.3.0.tar.gz to /home/yotam/.cache/winetricks/dxvk
--2019-07-15 21:35:01--  https://web.archive.org/web/2000/https://github.com/doitsujin/dxvk/releases/download/v1.3.0/dxvk-1.3.0.tar.gz
Resolving web.archive.org (web.archive.org)... 207.241.233.214
Connecting to web.archive.org (web.archive.org)|207.241.233.214|:443... connected.
...הבושת תלבקל ןיתממ ,החלשנ HTTP תיינפ 404 NOT FOUND
2019-07-15 21:35:06 ERROR 404: NOT FOUND.

------------------------------------------------------
Downloading https://web.archive.org/web/2000/https://github.com/doitsujin/dxvk/releases/download/v1.3.0/dxvk-1.3.0.tar.gz failed
------------------------------------------------------

**Comment by doitsujin** [comment]
Thanks for the heads-up, should be fixed by 1a9c1b4401e44ea2e92f54233356a0c752fc01b3.

But, next time, please fix the formatting of your post, or just attach terminal output as a text file if you don't know how to use Markdown, this was rather unreadable.

**Comment by bobwya** [comment]
@doitsujin I've a pull request against winetricks to use the Github API to pull the current **DXVK** release version. The updated **winetricks** **dxvk** verb handles your **1.3** release correctly. So going forward (when we go forward!) **winetricks** probably won't need the **RELEASE** file to be updated any more...
