### ISSUE TITLE
Question: Support VK_EXT_texel_buffer_alignment ..

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#1134]
Hi,
just asking as I vaguely remember a VK_EXT_shader_demote_to_helper_invocation branch having this support too.. now that branch seems was been merged (and removed) for 1.3 but the VK_EXT_texel_buffer_alignment patch is missing..

thanks..

**Comment by doitsujin** [comment]
I'd appreciate if you didn't ask for supporting every single Vulkan extension.

The old branch only enabled a device feature without actually querying the device limits, which made the implementation somewhat useless.

**Comment by oscarbg** [comment]
Ok, sorry..
