### ISSUE TITLE
Modded Final Fantasy XIV corrupted rendering with DXVK 1.3.1

### ISSUE THREAD

**Issue by fosspill** [doitsujin/dxvk#1138]
After switching from DXVK 1.3 to 1.3.1 FFXIV has started crashing when mods are installed.

Note: Unmodded still works fine.

I have been unable so far to track down specific types of mods that cause issues. Everything I've tried seems to be working as excepted with 1.3.1 as long as you have just a few mods installed.

I've also been unable to create an apitrace. Likely due to the launcher being 32bit and the game itself being 64 bit. I'll keep trying when I have time.

A picture of the "crash" / "corruption": https://i.imgur.com/nZniTwj.png - The DXVK HUD is still updating, but nothing functions.
### Workaround
Switch back to DXVK 1.3

### Software information
Final Fantasy XIV, default settings, modded.

### System information
- GPU: Vega 56
- Driver: Mesa-Aco 19.2.0 and Mesa (normal) 19.1.2
- Wine version: Wine-staging 4.12.1 and Wine-staging 4.10
- DXVK version: **1.3.1**

### Apitrace file(s)
- Unsure about how to go about this as the game crashes instantly upon starting with apitrace.

### Log files
- d3d11.log: https://gist.github.com/shinnova/dc573350adc8d181907eb0cb22db650f/raw/81801b3dc6b07974d88135ff4df346930bf8c6c4/ffxiv_dx11_d3d11.log
- dxgi.log: https://gist.github.com/shinnova/dc573350adc8d181907eb0cb22db650f/raw/81801b3dc6b07974d88135ff4df346930bf8c6c4/ffxiv_dx11_dxgi.log
- wine console output: https://gist.githubusercontent.com/shinnova/dc573350adc8d181907eb0cb22db650f/raw/86af91df05de15e36ed3dbcc7f7a7844fe89f59c/wine%2520console%2520log

**Comment by doitsujin** [comment]
Game works fine on my RX 480, but I'm also not using any mods. Also, please test **without** ACO, since older ACO builds are known to break the game (it has been fixed upstream, but I have no idea where you're getting your build from).

Does this build work? It disables the optimization you mentioned, but I don't see why it would cause the game to crash.
[dxvk-ffxiv-test.tar.gz](https://github.com/doitsujin/dxvk/files/3414780/dxvk-ffxiv-test.tar.gz)

**Comment by fosspill** [comment]
To clarify. The game works fine without mods on both 1.3 and 1.3.1. But with mods 1.3.1 crashes. 

And to clarify about aco, I've tested both mesa-aco and stable normal Mesa. Same issue.

Will test your build soon.

**Comment by doitsujin** [comment]
Then please test the build I gave you. If that doesn't work, you're going to have to either figure out how to get an apitrace of the game or bisect the issue yourself (or just play without mods). I cannot support modded setups.

**Comment by varris1** [comment]
@fosspill What kind of mods did you use? Without more details it will be difficult to fix.

**Comment by fosspill** [comment]
So, quick update while I keep testing.

The dxvk-ffxiv-test build doesn't make a difference, as far as I can tell.

@varris1 Currently testing various mods. Kind of tedious to test, but I haven't been able to find a specific type of mod that causes crashing. It might be as simple as the amount of mods causing issues with 1.3.1 and not 1.3.

**Comment by doitsujin** [comment]
Can you please [bisect](https://git-scm.com/docs/git-bisect) the problem then?

I'll be blunt, I don't care about your use case since it probably violates the game's ToS, but I **do** care about DXVK regressions since they might affect pretty much any game out there.

**Comment by fosspill** [comment]
I understand that you don't care about this specific use case directly, that's fine :) 

I'll try bisecting the problem when I have time.

Regarding the wine log, somehow it seems like the rendering itself crashes, but the game itself keeps running in a corrupted state. Maybe crashing was the wrong word to use?

**Comment by shinnova** [comment]
While @fosspill is bisecting the issue, I've been testing different types of mods and found at least one type of mod that causes this issue reliably. Furniture model mods, for instance this "[toilet mod](https://cdn.discordapp.com/attachments/431289537067614208/549504113251975168/Riviera_toilet.ttmp2)".

I also want to say thank you for giving this potentially silly yet surprisingly popular use case some attention.

**Comment by fosspill** [comment]
Wow, bisecting is actually kind of fun and therapeutic in a strange way.

Here is the output after bisecting @doitsujin 

```
acf6c27e76d07bd9f8ec2b1beb7117015ef129d8 is the first bad commit
commit acf6c27e76d07bd9f8ec2b1beb7117015ef129d8
Author: Philip Rebohle <philip.rebohle@tu-dortmund.de>
Date:   Mon Jul 15 04:14:23 2019 +0200

    [dxvk] Limit maximum size of multi-slice buffers
    
    Reduces memory fragmentation caused by frequently renamed buffers.

 src/dxvk/dxvk_buffer.cpp | 7 +++++++
 src/dxvk/dxvk_buffer.h   | 9 +++++----
 2 files changed, 12 insertions(+), 4 deletions(-)

```

**Comment by Joshua-Ashton** [comment]
I noticed that in d9vk, when making a zero-sized DxvkBuffer it crashes due to a divide by zero exception here.

Could be the same thing perhaps?

**Comment by Joshua-Ashton** [comment]
@fosspill Are you able to test whether that fixes the issue? Cheers.

**Comment by fosspill** [comment]
@Joshua-Ashton, I built DXVK from your "dxvk-buffer-div-zero" branch and it works perfectly to what I can see so far.

**Comment by doitsujin** [comment]
00cf2a20a3a3e2ea2a3db0dbddf619152159d8f0 should hopefully fix the problem properly.

**Comment by fosspill** [comment]
@doitsujin Indeed, that seems to have done it :)

**Comment by doitsujin** [comment]
Alright, thanks for confirming.

**Comment by Miotos** [comment]
@doitsujin Thanks for fixing this! I had this similar crash with DXVK 1.3.1 playing 3DXChat (NSFW game) :blush:  I just build DXVK from source and got it running again no problem :+1:
