### ISSUE TITLE
A10-7300 iGPU won't let me DXVK

### ISSUE THREAD

**Issue by ThePacificGamer** [doitsujin/dxvk#1142]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Overwatch, Default Lutris Settings

### System information
- GPU: AMD Kaveri
- Driver: Latest Mesa Radeon Driver
- Wine version: Latest Wine-Staging
- DXVK version: 1.3.1

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log: 

When loading Overwatch from lutris it says This system doesn't have Vulkan installed or the System is unsupported, I looked up online and it says the iGPU is supported by Vulkan. I installed Vulkan correctly for my distro, please help!

**Comment by doitsujin** [comment]
> I installed Vulkan correctly for my distro, please help!

Well, apparently you didn't. I can't help you since you gave no useful information about your system except the hardware, posted no DXVK logs, and gave no details on what exactly you did to "install Vulkan".
