### ISSUE TITLE
Stalker: Call of Prypiat with OpenXray Engine cant start

### ISSUE THREAD

**Issue by dzatenatskiy** [doitsujin/dxvk#1143]
After starting the game, I see the message Try to lower settings. On any settings.
The game starts with wine3d
I attached a screenshot and log file.
If you need more information, I will gladly provide it.

https://www.dropbox.com/s/dg8a2de7mdh4czw/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20%D0%BE%D1%82%202019-07-23%2014-03-32.png?dl=0

### Software information
Ubuntu 18.04
Stalker: Call of Prypiat with OpenXray Engine
https://github.com/OpenXRay/xray-16/releases

### System information
- GPU: Intel Iris Plus 655
- Driver: Mesa 19.1.2
- Wine version: ge-protonified 4.10 x86-64
- DXVK version: 1.3.1

### Log files
[stalker.log](https://github.com/doitsujin/dxvk/files/3421663/stalker.log)
[xrEngine_dxgi.log](https://github.com/doitsujin/dxvk/files/3421665/xrEngine_dxgi.log)
[xrEngine_d3d11.log](https://github.com/doitsujin/dxvk/files/3421666/xrEngine_d3d11.log)

**Comment by doitsujin** [comment]
Almost certainly not a DXVK bug, you will however need to install some native d3dcompiler using winetricks (probably `d3dcompiler_43` or `d3dcompiler_47`, not sure which). Please also post the wine console output.

https://github.com/OpenXRay/xray-16/blob/2aad79ae658503f7e08ba84ba82448bf99cc03c9/doc/design/task_list.txt#L59-L60

**Comment by dzatenatskiy** [comment]
> Everything seems to be fine on the DXVK side of things, you will however need to install some native d3dcompiler using winetricks (probably `d3dcompiler_43` or `d3dcompiler_47`, not sure which), see:
> 

Can I install one or both?

> https://github.com/OpenXRay/xray-16/blob/2aad79ae658503f7e08ba84ba82448bf99cc03c9/doc/design/task_list.txt#L59-L60
> 
> Please also post the wine console output.
> 
wine console output is in stalker.log. I attached it to the first post.

> Note that this engine **will** have rendering and stability issues with DXVK and I don't plan to fix those.

**Comment by doitsujin** [comment]
But stalker.log doesn't contain any wine messages at all. I would at least expect a bunch of `fixme`'s.

> Can I install one or both?

Both. `_46` is also a thing but used rarely.

**Comment by dzatenatskiy** [comment]
> But stalker.log doesn't contain any wine messages at all, instead you were using some Vulkan layer. I would at least expect a bunch of `fixme`'s in a wine log.
> 
> You weren't using `WINEDEBUG=-all`, right?
> 
> > Can I install one or both?
> 
> Both. `_46` is also a thing but used rarely.

I installed d3dcompiller_43 and 47. Now everything works. I tried to start the game for a long time, tried different libraries. The solution was so simple. Many thanks.
