### ISSUE TITLE
Vulkan Extensions missing for supported Graphics Card

### ISSUE THREAD

**Issue by phaitonican** [doitsujin/dxvk#1144]
```
info:  Required Vulkan extension VK_KHR_get_physical_device_properties2 not supported
info:  Required Vulkan extension VK_KHR_surface not supported
info:  Required Vulkan extension VK_KHR_win32_surface not supported
```

Seems maybe it is not always this case for other DXVK apps. Some other people seem to have this too for example: https://forums.lutris.net/t/eso-poe-dxvk-missing-vulkan-extensions-which-are-actually-supported/4437 or #774 

I was not sure if this is a Vulkan bug or a DXVK bug or neither, so I posted it for both. Also I installed everything listed here: https://github.com/lutris/lutris/wiki/Installing-drivers#installing-vulkan
etc.

Also set radeon.si_support=0 amdgpu.si_support=1 from https://wiki.archlinux.org/index.php/AMDGPU#Enable_Southern_Islands_(SI)_and_Sea_Islands_(CIK)_support
for my Southern Islands graphics card.

### Software information
League of Legends D9VK AppImage (Lutris)

### System information
- GPU: AMD RX 570
- Driver: Mesa and vulkan-radeon 19.1.3-1
- Wine version: wine-staging 4.12.1-1
- DXVK version: from D9VK 0.12

**Comment by doitsujin** [comment]
You're missing some packages (most likely the 32-bit vulkan loader or driver).

**Comment by phaitonican** [comment]
`sudo pacman -S vulkan-radeon lib32-vulkan-radeon vulkan-icd-loader lib32-vulkan-icd-loader`

installed every package from https://github.com/lutris/lutris/wiki/How-to:-DXVK needed for my AMDGPU

**Comment by doitsujin** [comment]
This isn't a bug, this is a setup issue on your end. Maybe Lutris screws with your environment variables or something; I can't really help you with that since it's not my issue.

**Comment by phaitonican** [comment]
Can you help me figure out if this is rather a Vulkan bug or Mesa bug?
Because I am sure this can't be a setup issue on my end. For example this guy has the same issue:
https://bugs.launchpad.net/ubuntu/+source/dxvk/+bug/1835980

**Comment by K0bin** [comment]
The bug report you linked says `The hardware this is running on is a Mac Pro 1,1, graphics card Nvidia 7300 GT.`. That GPU doesn't even support Vulkan.

**Comment by phaitonican** [comment]
true but RX 570 does so what can be the error? Pls help

**Comment by K0bin** [comment]
Try setting up the game manually inside Wine without Lutris.

**Comment by phaitonican** [comment]
yes tried that already (this guy tried help me: https://github.com/mmtrt/Wine-AppImage/issues/6#issuecomment-515263908).
But I am gonna try again. Thanks.
Maybe my card really doesn't support those three extensions or something.

**Comment by K0bin** [comment]
Try without the AppImage then.

**Comment by phaitonican** [comment]
Oh, without AppImage it works. Ok seems to not be my error then, thank you very much I thought since about 40 hours I do something wrong...
Thank you very much :)

**Comment by ansidev** [comment]
@phaitonican Can you share more about your solution?

**Comment by K0bin** [comment]
The solution is to set up Wine and DXVK like you normally would. Install normal Wine, make sure you have Vulkan drivers and loaders (dont forget 32bit) and then use the install script that comes with dxvk releases.

**Comment by yjacks** [comment]
I meet this problem too,the log is same as you.
My GPU is AMD HD4350

**Comment by phaitonican** [comment]
> I meet this problem too,the log is same as you. My GPU is AMD HD4350

yjacks this is not a dxvk issue. I was wrong. This was because I installed a AppImage which has missing DXVK drivers for my graphics card. If you don't use a AppImage and install ALL requirements it should work.
