### ISSUE TITLE
Question: dxvk prepackaged in /lib/wine/ does not seem to work

### ISSUE THREAD

**Issue by frantisekz** [doitsujin/dxvk#1146]
Hi,

I am experimenting a little with DXVK packaging. My theory is that if you place compiled dxvk .dll files (replacing original wine3d dll files) into /lib/wine and /lib64/wine, wine should pick them up while generating new / updating old prefix.

However, it doesn't seem like it does create/copy any of dxvk files from /lib(64)/wine to /dosdevices/c\:/windows/system32/ or syswow64. It does work for original .dll files from wine3d however.

Wine has been replacing .so files with .dll files located in /lib/wine in recent versions, so it seemed this should just work. (the only remaining file is dxgi, which is still in .so format, but d3d11, d3d10 and others are just plain DLL files in wine-4.12.1).

Was my assumption wrong, or am I doing something wrong? 

Thanks a lot !

EDIT: I've compiled dxvk with mingw, in order to get dll files which wine seems to be using recently and not .so files.

**Comment by doitsujin** [comment]
This doesn't really sound like something I can / want to support, especially since I'm not really familiar with the way wine sets up new prefixes. Replacing the .so files used to work with winelib builds, but that's also more of a hack than anything else.

Replacing wine files is a bad idea since they would get replaced by the next wine update anyway (also there are still legitimate reasons to keep using wined3d).

**Comment by frantisekz** [comment]
This was planned to be supported/worked on with distribution packaging (I am talking about Fedora, forgot to mention that). 

Basically, the plan was to split out d3d files from the main wine package into subpackages and have dxvk packaged providing these files too, so users would be able to choose which d3d implementation they want and keep that choice throughout wine updates too.

I'll try to look at the wine code, why is it copying original dll files from /lib into prefixes but not dxvk ones, was asking just if somebody had a clue why is it not working out of the box.

**Comment by frantisekz** [comment]
Hmm, okay, having d3dxx .so files in /lib/wine works just fine too (even when latest wine release use .dll files and not .so files for d3d ), so I am probably not going to dig too much why dxvk .dll files don't work while the wine ones do.

Anyway, thanks!
