### ISSUE TITLE
Anno 1800 graphical problems

### ISSUE THREAD

**Issue by mozo78** [doitsujin/dxvk#1151]
The game runs fine, with good performance but there is a blue cover over the mountains:
![Anno 1800](https://user-images.githubusercontent.com/38666396/62421002-ecc88700-b6a3-11e9-9f8f-ab14cf9796aa.png)

### Software information
Anno 1800.

### System information
- GPU: GTX NVIDIA 1080 Ti
- Driver: 430.40
- Wine version: 4.13
- DXVK version: 1.3.1/ latest master

### Apitrace file(s)
https://my.pcloud.com/publink/show?code=XZgAHi7ZJlB4aeDGknJUlBRh5DizdbyzrDgV

### Log files
- d3d11.log:
[Anno1800_d3d11.log](https://github.com/doitsujin/dxvk/files/3464651/Anno1800_d3d11.log)

- dxgi.log:
[Anno1800_dxgi.log](https://github.com/doitsujin/dxvk/files/3464652/Anno1800_dxgi.log)

**Comment by doitsujin** [comment]
Can you test an older DXVK version? I know for a fact that the game was running fine when it came out.

**Comment by mozo78** [comment]
According to this post it is a problem since the last update:
https://github.com/ValveSoftware/Proton/issues/2544#issuecomment-517936560

I'll test it with an older version and will write you back.

**Comment by tannisroot** [comment]
Did you record an apitrace with native D3D11 on Windows, WineD3D or DXVK?
If you are able to replay it, can you check whether you can observe the issue in that trace?

**Comment by mozo78** [comment]
Unfortunately I couldn't get the apitrace on Linux and I installed the microsoft's crap temporarily. I don't know how to replay the trace.

**Comment by doitsujin** [comment]
The trace renders fine on my end, so it's likely some sort of feedback issue.

Can you bisect the problem? Someone else mentioned that the game works fine with 1.2.3 and broke with 1.3.

**Comment by mozo78** [comment]
I tried it with 6b2f4f9 but the blue problem is there. Then I tried it with 1.0.3 and it runs fine. I can't test many versions for I bought a shared account and it is very difficult to get in game :)

**Comment by doitsujin** [comment]
Well, someone else reported that it works fine on latest master but not on 1.3.1.

Can you test this build:
[dxvk.tar.gz](https://github.com/doitsujin/dxvk/files/3464829/dxvk.tar.gz)

I can't test the game right now, so I won't be able to fix this today.

**Comment by mozo78** [comment]
Yes, with this build everything is perfect. Thank you!
![Screenshot_20190804_140611](https://user-images.githubusercontent.com/38666396/62422820-21970700-b6c1-11e9-968a-81525b14ee80.png)

**Comment by doitsujin** [comment]
That build is literally latest master though.

Are you **absolutely certain** that you built everything correctly when testing it?

**Comment by mozo78** [comment]
I don't know, I just download the latest dlls fron here:
https://haagch.frickel.club/files/dxvk/latest/64/bin/

**Comment by Joshua-Ashton** [comment]
Those builds are always 5 days or so behind... Those builds are from 1st August.

**Comment by mozo78** [comment]
I see. Where I can downloaded the latest from?

**Comment by doitsujin** [comment]
Looks like the "latest" build is several days old. I'll close this then since the *actually* latest build is working fine.
