### ISSUE TITLE
Strange colors of mud covered walls in Shadow of the Tomb Raider

### ISSUE THREAD

**Issue by AlexeyProkhin** [doitsujin/dxvk#1152]
This happens only for a brief moment when the survival instincts are about to run out. The bug reproducible for me on any graphic settings.
![20190804195837_1](https://user-images.githubusercontent.com/615489/62427452-c6363a80-b6fb-11e9-8716-d640ca38676b.jpg)

### System information
- GPU: GeForce GTX 1070
- Driver: 430.40
- Wine version: Proton 4.11-1
- DXVK version: 1.3 and 6b2f4f93cc51c7c75dbf4cc067c0b924052d6d35

### Apitrace file(s)
- https://drive.google.com/file/d/1OCUdFI3KhpJXjeq4jnLHr6RD0NUixf4j/view?usp=sharing

### Log files
- d3d11.log: [SOTTR_d3d11.log](https://github.com/doitsujin/dxvk/files/3465159/SOTTR_d3d11.log)
- dxgi.log: [SOTTR_dxgi.log](https://github.com/doitsujin/dxvk/files/3465160/SOTTR_dxgi.log)

**Comment by AlexeyProkhin** [comment]
Unfortunately, the trace does not show the issue, at least for me. I have recorded it in win10. Should I rerecord it with dxvk?
Also, in case you have the game, here is my save file: 
[save4.dat.zip](https://github.com/doitsujin/dxvk/files/3465174/save4.dat.zip)

**Comment by doitsujin** [comment]
I'm aware of this problem but don't know how to debug it.

**Comment by AlexeyProkhin** [comment]
Well, it occurs in any region with the mud covered walls, nowhere else. And, for what it is worth, disabling nviapi hack seems to make the bug less annoying, the walls stop blinking.

**Comment by doitsujin** [comment]
Small update:
- Your apitrace renders fine, which is... annoying
- I can definitely reproduce the bug with your savegame (haven't really seen the issue in later parts of the game so I had hoped it would have been resolved)
- Neither your trace nor the game work with RenderDoc on Windows, so I cannot really check what native D3D11 is doing.

In short, I have absolutely no clue how to debug this besides guessing and trying a few things.

**Comment by kakra** [comment]
I've lately found that the behavior of some rendering bugs in SOTTR changes depending on the rendering resolution, i.e. I switched to QHD resolution and now I got the black pixel bleeding bug back. Switching back to a lower resolution and it's gone.

Regarding your pink mud walls: I'm seeing this, too. But not in every region. This shows only up when the survival instinct runs out, then there's this pink flickering while the white overlay effect fades out.

**Comment by doitsujin** [comment]
Small update: This bug occurs with
- vkd3d on Linux
- DXVK on Linux
- wined3d on Linux (apparently)

but **not** with DXVK on Windows.

I'm really not sure what's going on at this point, we might be looking at a weird wine bug. I'll look into this a bit more.

**Comment by kakra** [comment]
Maybe it's one of those strange bugs where the game accesses freed memory or uses some uninitialized values, and that just happens to be pink in Wine, and white in Windows...
