### ISSUE TITLE
Superposition: Crash when loading

### ISSUE THREAD

**Issue by d4rkf4b** [doitsujin/dxvk#1153]
Hello,
To begin, thank you for all the work you do on dxvk.
I'm french, sorry if my english is not perfect.
I suppose I found a problem between two commits. I am having this on a computer equipped with GeForce GTX 680 running Unigine Superposition benchmark on Ubuntu 19.04.
You can found logs between these commits with this issue.
Since commit 6936da1, I can't run Unigine Superposition without issue. Application crashes when loading. Superposition benchmark run fine with commit 18aada2.
Testing on the same computer with a GeForce GTX 970, commit 6936da1 and commit 18aada2. Running fine.
Testing on other computer with GTX 680. Commit 6936da1, application crashes when loading. Commit 18aada2, running fine.
This problem is still present in master branch. 
Hope that help you.

### System information
- GPU: GeForce GTX 680 and GeForce GTX 970
- Driver: 418.52.18
- Wine version:  >= 4.12.1 
- DXVK version: 1.3 Commit 6936da1

### Log files
- [Commit_]d3d11.log and [Commit_]dxgi.log::
[18aada2_launcher_d3d11.log](https://github.com/doitsujin/dxvk/files/3469356/18aada2_launcher_d3d11.log)
[18aada2_launcher_dxgi.log](https://github.com/doitsujin/dxvk/files/3469357/18aada2_launcher_dxgi.log)
[6936da1_launcher_d3d11.log](https://github.com/doitsujin/dxvk/files/3469358/6936da1_launcher_d3d11.log)
[6936da1_launcher_dxgi.log](https://github.com/doitsujin/dxvk/files/3469359/6936da1_launcher_dxgi.log)

**Comment by doitsujin** [comment]
I'm aware that Superposition doesn't work properly on some low-VRAM Nvidia GPUs, but I also don't plan to invest any significant amount of time into trying to debug this. It's likely related to #1100, which is a known problem.

**Comment by d4rkf4b** [comment]
No problem. Create this issue only if that can help you.
Thanks for your answer.
