### ISSUE TITLE
World of Warcraft breaks when unfocused

### ISSUE THREAD

**Issue by krathalan** [doitsujin/dxvk#1154]
### Issue description
With the latest 1.3.2 DXVK, World of Warcraft runs at least as good as (probably better than) before, but if I switch to a different workspace in i3 for more than a few seconds (thus unfocusing the World of Warcraft window), then try to switch *back* to the World of Warcraft window, the game doesn't display anything (I can see my background wallpaper) and my system becomes laggy. 

Switching back to 1.3.1 completely resolves this issue.

### Software information
Game: World of Warcraft

World of Warcraft settings: [Config.wtf](https://gist.github.com/krathalan/5de5cfab87e5d933d11beee9ef909ab2#file-wow_config-wtf)

### System information
- GPU: NVIDIA 980 Ti
- Driver: nvidia 430.40-1
- Wine version: lutris-4.12
- DXVK version: 1.3.2

### Apitrace file(s)
I would be happy to provide an Apitrace file but I'm having some trouble generating one. I tried downloading the Linux binaries through my package manager but your instructions say to run it through Wine, so I downloaded the Apitrace Windows binaries and put them in the World of Warcraft folder, in their own folder (so apitrace.exe is in apitrace/apitrace.exe).

Running `wine apitrace/apitrace.exe trace -a dxgi Wow.exe` starts to work, but then I get the error "error: failed to find dxgitrace.dll wrapper", even though `dxgitrace.dll` is in the `apitrace/` folder.. I'm not sure what to troubleshoot from here. 

### Log files
- d3d11.log: [Wow_d3d11.log](https://gist.github.com/krathalan/5de5cfab87e5d933d11beee9ef909ab2#file-wow_d3d11-log)
- dxgi.log: [Wow_dxgi.log](https://gist.github.com/krathalan/5de5cfab87e5d933d11beee9ef909ab2#file-wow_dxgi-log)

**Comment by doitsujin** [comment]
Can't reproduce.

Can you test if setting `dxvk.asyncPresent = True` in dxvk.conf fixes this?

**Comment by doitsujin** [comment]
Might also be worth testing bd40b057202a9e42196c4c1209920c228161d793. Here's a build:
[dxvk-master.tar.gz](https://github.com/doitsujin/dxvk/files/3470807/dxvk-master.tar.gz)

Apparently this commit fixes a somewhat similar issue on Overwatch for some people.

**Comment by dylanparry** [comment]
I was having the same issue with World of Warcraft, and the above build does appear to fix this for me at least.

**Comment by Sorikoff** [comment]
Same for me.

**Comment by krathalan** [comment]
I selected "Manual" in the Lutris WoW settings and installed the posted bd40b05 build with the instructions in the readme (https://github.com/doitsujin/dxvk#how-to-use). This seems to fix the issue for me. Is there a way for me to verify that I'm using the bd40b05 version of DXVK?

**Comment by krathalan** [comment]
Also, @doitsujin disabling "Allowing flipping" does not fix the issue with the release 1.3.2.

**Comment by krathalan** [comment]
Not sure what update fixed this for me, but as of 1.4.2 I no longer have this issue.
