### ISSUE TITLE
Far Cry Primal Red Issue

### ISSUE THREAD

**Issue by youandmy** [doitsujin/dxvk#1155]
Hello DXVK dev. I'll just write this as 1.3.2 introduced red shaders and flickering for the benchmark (not sure about gameplay) of far cry primal. This was not an issue in 1.3.1 with the same specs I am using. I will just post for now and take a little time to see if I can bisect the issue and come up with an apitrace. brb

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Far Cry Primal, Preset High for settings

### System information
- GPU: RX 480
- Driver: Mesa 19.2.0-devel (git-70bb3c0bec) (mesa-aco)
- Wine version: 4.13
- DXVK version: 1.3.2

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
[FCPrimal_d3d11.log](https://github.com/doitsujin/dxvk/files/3469736/FCPrimal_d3d11.log)

- dxgi.log:
[FCPrimal_dxgi.log](https://github.com/doitsujin/dxvk/files/3469737/FCPrimal_dxgi.log)

**Comment by Joshua-Ashton** [comment]
Apitrace + a picture of what you mean might be useful

**Comment by youandmy** [comment]
![2019-08-06-004637_1920x1080_scrot](https://user-images.githubusercontent.com/45441077/62514231-26081080-b7e4-11e9-8853-2b2b87573e52.png)
![2019-08-06-004911_1920x1080_scrot](https://user-images.githubusercontent.com/45441077/62514235-2b655b00-b7e4-11e9-9ff1-ac00fc1647f7.png)
the red one is on 1.3.2 .... I actually got impatient as apitrace takes a million to get going in this game not like others. I bisected the issue to this release if it I did it right and even helps 65c1e58bd9abcf808d018ef366c901f9fee9203f big release so not sure...

**Comment by doitsujin** [comment]
This is a known game bug. I'm not sure what magic is required to make it work again.

**Comment by youandmy** [comment]
ok, then as dxvk is working as it should be fine to close this and just revert to 1.3.1 whenever I play this game I guess.

**Comment by doitsujin** [comment]
I'm not opposed to keeping this open, but here's the thing, I don't have the slightest idea how to convince the game to render properly again.

**Comment by K0bin** [comment]
https://i.imgur.com/m9tfwNJ.jpg

This appears to be a compiler bug. If I compile DXVK 1.3.2 with MSVC it looks correct. (left pic is D3D11 for reference)

**Comment by Joshua-Ashton** [comment]
Here are some respective builds

[ooheeooaaattingtangwallawalla-clang-bang.zip](https://github.com/doitsujin/dxvk/files/3474451/ooheeooaaattingtangwallawalla-clang-bang.zip)
[boat-on-the-msvc.zip](https://github.com/doitsujin/dxvk/files/3474452/boat-on-the-msvc.zip)

**Comment by youandmy** [comment]
works as expected now with that update, thank you all for the work.
![2019-08-07-011747_1920x1080_scrot](https://user-images.githubusercontent.com/45441077/62599217-44880d80-b8b1-11e9-95bb-28a0ec15f11c.png)
