### ISSUE TITLE
Shimmering clothes in Hellblade: Senua's Sacrifice

### ISSUE THREAD

**Issue by 88i** [doitsujin/dxvk#1157]
Issue description:

Please watch the fur on Senua's shoulders in this video: https://www.youtube.com/watch?v=V4a-E1oGbaU&t=41s

But when DXVK is used, this fur vibrates in a strange way: https://www.youtube.com/watch?v=Os2mbNsfjJo&t=105s

### Software information
Hellblade: Senua's Sacrifice 
Settings: any

### System information
- GPU: GTX 1050 2GB
- Driver: latest nvidia drivers
- Wine version: 4.12
- DXVK version: 1.3

### Apitrace file(s)
Inapplicable

### Log files
Inapplicable

**Comment by doitsujin** [comment]
Works fine for me.

Have you even tested the game yourself or are you filing this bug report based on a **one year old video**? Why are log files "inapplicable" and what are "latest" nvidia drivers?

Sorry, I cannot provide any help if you don't provide any details.
