### ISSUE TITLE
Misrendering in SteamVR Performance Test

### ISSUE THREAD

**Issue by ryao** [doitsujin/dxvk#1160]
## Software information
SteamVR Performance Test
Picked the do not report to valve launch option through the right click context menu under the Tools section of my Steam library.

### System information
- GPU: GeForce GTX 1070
- Driver: 430.34
- Wine version: Proton 4.11-2
- DXVK version: Proton 4.11-2 bundled version

### Apitrace file(s)
- I cannot generate an API Trace. It crashes when trying to use WineD3D and I do not have Windows.

### Log files
- d3d11.log: Not generated by proton
- dxgi.log: Not generated by proton

**Comment by ryao** [comment]
Some of the misrendering issues go away with `d3d11.dcSingleUseMode = False`. I found the d3d11.log and dxgi.log files. Their names were not what I expected:

[vr_d3d11.log](https://github.com/doitsujin/dxvk/files/3488592/vr_d3d11.log)
[vr_dxgi.log](https://github.com/doitsujin/dxvk/files/3488594/vr_dxgi.log)

**Comment by kwahoo2** [comment]
After updating Proton to 4.11-3, the app is able to start and display something. But there are rendering artifacts (see screenshot)

### System information

* GPU: Radeon RX 580
* Driver: 430.34 Mesa 19.3.0-devel (LLVM 8.0.0) + Valve ACO (tested with and w/o)
 * Wine version: Proton 4.11-3
* DXVK version: Proton 4.11-3 bundled version

![SteamVR Performance Test](https://i.imgur.com/HphQvqW.png)

[vr_d3d11.log](https://raw.githubusercontent.com/kwahoo2/steamreports/master/steamvrperftest/vr_d3d11.log)

[vr_dxgi.log](https://raw.githubusercontent.com/kwahoo2/steamreports/master/steamvrperftest/vr_dxgi.log)

**Comment by Joshua-Ashton** [comment]
Read above.

**Comment by kwahoo2** [comment]
> Read above.

This is with Proton 4.11-3, where dcSingleUseMode should be disabled, but according logs it isn't:

warn:  D3D11: Command list submitted multiple times,
warn:         but d3d11.dcSingleUseMode is enabled

**Comment by Joshua-Ashton** [comment]
Why would it? There's no release of DXVK with this fix that's in Proton afaik.

**Comment by kwahoo2** [comment]
Ok, @ryao comment from https://github.com/ValveSoftware/SteamVR-for-Linux/issues/218 mislead me a bit. 

Is there a way to disable d3d11.dcSingleUseMode without recompiling DXVK?

**Comment by Joshua-Ashton** [comment]
dxvk.conf

**Comment by doitsujin** [comment]
There has been no DXVK update since 4.11-2, so yes, it is expected to be broken. Changing the option won't fix all of it since there were actually two different issues with it.

**Comment by kwahoo2** [comment]
> Changing the option won't fix all of it since there were actually two different issues with it.

Yes, I've just tried it, the difference is very minor https://i.imgur.com/VVipivV.png

**Comment by kwahoo2** [comment]
DXVK 1.3.3 fixed incorrect rendering for me. Performance looks ok too: 6.4 score, 0 frames below 60fps, 0 frames CPU-bound.
