### ISSUE TITLE
Frequent frame time spikes in Assetto Corsa Competizione

### ISSUE THREAD

**Issue by jp7677** [doitsujin/dxvk#1161]
Assetto Corsa Competizione suffers from regular frame times spikes. Sometimes they happen with a regular frequency of 1 or 2 seconds for several seconds long. Sometime the spikes happen close together. The game itself indicate then that CPU usage is above 100%. The game "recovers" from the spikes, but these spikes may start again later during game play.
See this screenshot for an example of the frame time graph when this behavior occurs.
![Screenshot from 2019-08-07 21-28-51](https://user-images.githubusercontent.com/17219293/62830713-741d7980-bc13-11e9-8774-aa71b4096a45.png)
Note that the logging in screenshot stalls during a spike too.

I don't think this behavior is caused by shader compilation or at least not solemnly, it still occurs after lots of "rounds on a track" i.c.w. with a warm state cache. The game runs graphics wise with the exception of the frame time spikes astonishingly well.

### Software information
Assetto Corsa Competizione 1.0.7, my settings vary between mid and epic, though I haven't found _the_ setting that seemed to cause this. My impression is that having v-sync enabled seems to make it less worse or "postpone" the spikes, but I'm not that sure. These spikes started with version 1.0 of the game (it was available as Early Access), so a game change introduced these. This behavior is confirmed by at least one other user (https://github.com/ValveSoftware/Proton/issues/1420#issuecomment-497238834). Currently the games uses Unreal Engine 4.22 (that's what a folder name in application data indicates).

Considering this behavior was introduced with a game update this might not be related to DXVK at all.

### System information
- GPU: NVIDIA GTX 1080
- Driver: 430.40
- Wine version: Proton 4.11 (esync enabled)
- DXVK version: v1.3.2-4-g0b21ef18 (from Proton 4.11), same results with master

### Apitrace file(s)
- https://www.dropbox.com/s/40ii3832uxl03ma/AC2-Win64-Shipping.tar.xz?dl=0
This trace was taken with DXVK since a Wine3D would not replay. This trace has just something like 10 seconds of actual gameplay in it. I don't know if the trace covers a spike due to the penalty of having apitrace attached. Let me know if it would be useful to take a longer trace.  

### Log files
- dxgi.log: [AC2-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/3489566/AC2-Win64-Shipping_dxgi.log)
- d3d11.log: [AC2-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/3489565/AC2-Win64-Shipping_d3d11.log)
- d3d11.log with extra GetData logging from DXVK build provided from a Discord user: https://www.dropbox.com/s/1qrlttg326pk5c4/AC2-Win64-Shipping_d3d11-GetData.zip?dl=0

Please let me know if I can assist any further. Last but not least, D(X|9)VK are magic projects, thanks a lot for all the hard work!

**Comment by jp7677** [comment]
It doesn't seem that DXVK does anything wrong here. The game is just very CPU intensive, bringing one core during game play to 100% like all the time even with lowest graphics settings.

**Comment by doitsujin** [comment]
Well, this still shouldn't really happen, but the apitrace just doesn't show any suspicious behaviour. It's very possible that running the game through apitrace just hides the cause of these spikes.

Which makes this even more annoying to debug.

**Comment by jp7677** [comment]
Actually the in-game replay shot in my mind today. When replaying driving on the track in the game itself, the CPU usage of the busiest core seems around 50%. Spikes that I encountered during actual play, when one core had been constantly at 100% usage, didn't occur during in-game replay. I see a spike or two, but overall the frame times are much much smoother in the in-game replay. I guess that sorts out that DXVK causes the high CPU usage in this game.
I can't judge if high CPU pressure could cause DXVK to act differently, but I guess the game itself is thus causing the frequent spikes like in the screenshots.
Would be interesting to know how CPU usage is on Windows... Anyway, the game still gets a lot of updates, hopefully a game update solves this at some point.

Thanks a lot for your time for looking into the trace!

**Comment by leillo1975** [comment]
I'm have the same problem like you. I copy/paste the [message I left on Proton Issues](https://github.com/ValveSoftware/Proton/issues/1420#issuecomment-583780851):

I found that this game has a lot of stuttering, especially in multiplayer games, or when you ride against many cars. In certain moments the games shows a message on the top-left (CPU use > 99%), and the frametimes graph of the DXVK_HUD shows a lot of stutter. I recorded a video to show you this problem:
https://youtu.be/cEoahOxIWqc

As you can see in the "htop" window, the the CPU are not at 99% (perhaps 60%). There are a lot of CPU performance lost, and is probably that if the game use the entire CPU, this stutter would be much less. I think that this is not normal.

I made a Blender Benchmark and all the cores were set at 100% in "htop" without problems.

I played 2 multiplayer races on Windows in the same PC without any issues and CPU overload messages. I think that Proton can't use all the CPU in this game. The problem is the same with versions 5.0, 4.11 and 4.2

My CPU is a Intel i7-3770. You can see a GIST of my system here:
https://gist.github.com/leillo1975/db654fd0c71ce0baf57c1cca5bef3525

**Comment by jp7677** [comment]
Well, as stated in the Proton issue list, I do still see the occasional frame time spike on my machine. but overall it got much better with recent game updates.

**Comment by leillo1975** [comment]
As I stated on proton Issue, the strange thing is that the game reports a CPU usage > 99% and the OS only reports less than 60%. It's like if Proton doesn't use the full power of the CPU

**Comment by jp7677** [comment]
This mystery has finally been solved. See https://github.com/ValveSoftware/Proton/issues/1420#issuecomment-639084670
