### ISSUE TITLE
Assassin's Creed III Remastered: no rendering

### ISSUE THREAD

**Issue by d4rkf4b** [doitsujin/dxvk#1162]
Hello,
When I launch this game, I only have a black screen. Game seems working since I can hear sounds. If I launch it from Win 10, running fine.
I made apitrace files from Win10 and Wine (without dxvk)
Thanks for your work.

### Software information
Assassin's Creed III Remastered

### System information
- GPU: GeForce GTX 970
- Driver: 430.40.0
- Wine version: 4.13
- DXVK version: 1.3.2-5-g1999ca9d

### Apitrace files

[apitrace.zip](http://dl.free.fr/v3SHeR9gX)

### Log files
- d3d11.log:
[ACIII_d3d11.log](https://github.com/doitsujin/dxvk/files/3490525/ACIII_d3d11.log)

- dxgi.log:
[ACIII_dxgi.log](https://github.com/doitsujin/dxvk/files/3490526/ACIII_dxgi.log)

**Comment by K0bin** [comment]
I did test this game at some point with DXVK and it was working fine.
Can you please test DXVK 1.2.3 (and maybe 1.1.1) to find out if this is a regression?

**Comment by doitsujin** [comment]
The Windows 10 apitrace replays fine, the trace recorded on Wine just doesn't actually draw *anything*. This isn't a DXVK bug, you probably just need some extra libraries (d3dcompiler?).

Please post the full wine log.

**Comment by d4rkf4b** [comment]
@K0bin 
since 4 months of testing, I always had a black screen with wine and dxvk. Are You sure you talk about remastered version?
@doitsujin 
What log do you want? 
Perhaps my Wine apitrace are bad. On Win10, game is very slow when launching with apitrace. With wine and black screen, I perhaps stopped the game too early.

**Comment by K0bin** [comment]
Still works perfectly fine for me. Yes, that is the remaster.
![grafik](https://user-images.githubusercontent.com/1131720/62861765-c8eced00-bd04-11e9-9372-cfa7c6eedb8d.png)

> Perhaps my Wine apitrace are bad. On Win10, game is very slow when launching with apitrace. With wine and black screen, I perhaps stopped the game too early.

No, you did that correctly.

> I have a file ACIII.dxvk-cache in directory.

That doesn't matter.

>  What log do you want?

The Wine terminal output from running the game. Ideally with WINEDEUBG=+loaddll or more logging. It should show whether the game needs D3DCompiler (and which version) which is likely the issue here.

**Comment by d4rkf4b** [comment]
@doitsujin 
I made another apitrace with wine, more longer:
[ACIII_d3d11.log](https://github.com/doitsujin/dxvk/files/3492008/ACIII_d3d11.log)
[ACIII_dxgi.log](https://github.com/doitsujin/dxvk/files/3492009/ACIII_dxgi.log)
[ACIII.cache.zip](http://dl.free.fr/bfa7Fsn0O)
[Wine_ACIII.log](https://github.com/doitsujin/dxvk/files/3492187/Wine_ACIII.log)


@K0bin 
You run it from Windows 10 (driver 431.60). Works fine for me too on it. That confirm this is wine related.

**Comment by K0bin** [comment]
> You run it from Windows 10 (driver 431.60). Works fine for me too on it. That confirm this is wine related.

That proves DXVK works perfectly fine with the game and the bug is caused by Wine.

Wine logs are full of d3dcompiler messages. Installing Microsofts d3dcompiler (don't know if 43 or 47, just try both) should fix the issue for you.

**Comment by doitsujin** [comment]
> 002f:err:d3dcompiler:compile_shader HLSL shader parsing failed.

This confirms that this is a d3dcompiler issue. Running `winetricks d3dcompiler_43` and `winetricks d3dcompiler_47` on your prefix should fix the issue.

**Comment by d4rkf4b** [comment]
Works fine now, Thanks
