### ISSUE TITLE
The Evil Within crashes with DXVK

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [doitsujin/dxvk#1164]
The Evil Within 1 crashes after pressing continue in the main menu, or before reaching the main menu. I can run it with wined3d, but it runs in slow motion.
I tried different Wine versions, different DXVK versions, and different drivers, but no difference.

### System information
- GPU: AMD HD 8750M
- Driver: Mesa 19.1.99
- Wine version: 4.13-staging
- DXVK version: 1.3.2

### Log files
- d3d11.log: [EvilWithin_d3d11.log](https://github.com/doitsujin/dxvk/files/3494206/EvilWithin_d3d11.log)
- dxgi.log: [EvilWithin_dxgi.log](https://github.com/doitsujin/dxvk/files/3494207/EvilWithin_dxgi.log)

**Comment by doitsujin** [comment]
At least the demo works fine on my end (I don't have the full game):
![Bildschirmfoto-910](https://user-images.githubusercontent.com/25567304/62900581-d03ee580-bd5a-11e9-9d81-e8fcd05d6c30.png)

Can you please try this with Proton rather than wine-staging, and also post the full wine log?

**Comment by ahmed-elsayed2017** [comment]
I can't find any proton log for this game. I don't know why. Normal Wine log will be any useful for you if you are interested? If you are, what do you want me to debug exactly? or do I use:
`WINEDEBUG=+timestamp,+pid,+tid,+seh,+debugstr,+module`
to give me the same log as Proton?

**Comment by ahmed-elsayed2017** [comment]
I can't find any proton log for this game. I don't know why. Here is wine-staging log that has the same information as Proton log if you are interested
[EvilWithin.tar.gz](https://github.com/doitsujin/dxvk/files/3497586/EvilWithin.tar.gz)

I made it using the debug command:
`WINEDEBUG=+timestamp,+pid,+tid,+seh,+debugstr,+module`

**Comment by ahmed-elsayed2017** [comment]
I tried to record an apitrace, but it crashed after a few seconds. I don't know if it is any useful

[EvilWithin.zip](https://github.com/doitsujin/dxvk/files/3502762/EvilWithin.zip)

**Comment by ahmed-elsayed2017** [comment]
Full wine log:
[EvilWithin.log](https://github.com/doitsujin/dxvk/files/3502786/EvilWithin.log)

The game crashes after pressing Continue.

**Comment by doitsujin** [comment]
Are you sure your Mesa build isn't borked? For some reason it crashes inside the driver, in a function that **really** shouldn't crash:
```
  5 0x00007f6264f952d6 vk_icdGetPhysicalDeviceProcAddr+0xffffffffffffffff() in libvulkan_radeon.so (0x0000000000000001)
```

**Comment by ahmed-elsayed2017** [comment]
Other games were running fine. Anyway, I used Obiaf PPA instead of Padoka PPA Unstable, and the game runs fine with it. Thanks, and sorry for wasting your time.

**Comment by ahmed-elsayed2017** [comment]
Since you have the demo of the game, do you notice any difference between SMAA, or FXAA, being turned on, and being turned off?

**Comment by doitsujin** [comment]
They work fine.

**Comment by HolimaX** [comment]
Similar crash is seen on Doom 2016 @ Fedora 33 , wine-staging 6.6 and DXVK 1.8.1

**Comment by Joshua-Ashton** [comment]
Doom is a native Vulkan game.

**Comment by HolimaX** [comment]
> Doom is a native Vulkan game.

So? Game is executed from Wine environment - It works in OpenGL; fails on Vulkan render. Are you saying that this project only tracks and supports bugs to apps that is not "native" Vulkan apps?

**Comment by ZachBacon** [comment]
> > Doom is a native Vulkan game.
> 
> So? Game is executed from Wine environment - It works in OpenGL; fails on Vulkan render. Are you saying that this project only tracks and supports bugs to apps that is not "native" Vulkan apps?

So? Dxvk translates d3d calls from 9,10 and 11 to Vulkan, not Vulkan to Vulkan.

**Comment by Ahmed-E-86** [comment]
> > Doom is a native Vulkan game.
> 
> So? Game is executed from Wine environment - It works in OpenGL; fails on Vulkan render. Are you saying that this project only tracks and supports bugs to apps that is not "native" Vulkan apps?

They only track issues related to their project --> DXVK. Also, my issue was not even related to DXVK. It was a driver issue.

If you want to report an issue related to Vulkan, report it there --> https://gitlab.freedesktop.org/mesa/mesa
