### ISSUE TITLE
UAV loads of non R32_* format without StorageImageReadWithoutFormat support

### ISSUE THREAD

**Issue by werman** [doitsujin/dxvk#1165]
After my investigation I found that it was mentioned in https://github.com/doitsujin/dxvk/issues/150 so I guess I've stumbled upon the real world example.

Shadow of the Tomb Raider is rendered incorrectly on ANV because its compute shader that applies lut uses R11G11B10_FLOAT uav:
![image](https://user-images.githubusercontent.com/3993671/63023969-e3fb6080-beae-11e9-828e-ca26902e15cf.png)

![image](https://user-images.githubusercontent.com/3993671/63024170-59673100-beaf-11e9-934f-c5df1e86f90f.png)

Also I didn't try the game itself but used a trace from the investigations of the neighbor SOTTR bug so I don't know which settings are used.

**Comment by doitsujin** [comment]
Does the compute shader **read** the UAV? If not, then that isn't the issue.

If it does, it's the game's fault. Unless explicitly reported by the driver as supported, reading from non-`R32_*` UAVs is illegal.

**Comment by werman** [comment]
> Does the compute shader read the UAV? If not, then that isn't the issue.

Yes, modifies value and writes back.

> If not, it's the game's fault. Unless explicitly reported by the driver as supported, reading from non-R32_* UAVs is illegal, and DXVK doesn't report that as supported.

Ah, I see, so I need to launch the game itself and see what it does with DXVK instead of trace. Sorry for troubling you then. Thanks!
