### ISSUE TITLE
Shadow Warrior 2013 no DirectX 10 device found

### ISSUE THREAD

**Issue by rstevenson1976** [doitsujin/dxvk#1167]
when launching Shadow Warrior 2013 in DXVK it simply says no directx 10 device found and doesn't launch

Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Name of the game, settings used etc.

### System information
- GPU:AMD RX570
- Driver:latest mesa from ppa
- Wine version: Wine-Staging 4.13
- DXVK version: 1.3.2

### Apitrace file(s)
https://drive.google.com/file/d/1YQNzcXTNeu--hlyYk4FNJYGdCwLe9pMY/view?usp=sharing
### Log files
- d3d11.log:
- dxgi.log:

[sw.x64_d3d11.log](https://github.com/doitsujin/dxvk/files/3511211/sw.x64_d3d11.log)
[sw.x64_dxgi.log](https://github.com/doitsujin/dxvk/files/3511213/sw.x64_dxgi.log)

**Comment by doitsujin** [comment]
This is not a DXVK bug but some setup issue. Hard Reset Redux has the exact same problem; there is a way to fix it but I forgot how to do that.

**Comment by rstevenson1976** [comment]
but, it works without dxvk

**Comment by doitsujin** [comment]
The game works fine with DXVK as well if you get around that error message.

IIRC on AMD GPUs, you have to use wine's DXGI so that D3D11 and some other API return the same adapter names. Set the environment variable `WINEDLLOVERRIDES=dxgi=b` in order to so that.
