### ISSUE TITLE
Is there any plan to support DX12 in DXVK?

### ISSUE THREAD

**Issue by laichiaheng** [doitsujin/dxvk#1168]
There is D9VK for DX9, here is DXVK for DX10 and DX11, is there any plan to support DX12 in DXVK soon?

**Comment by K0bin** [comment]
https://source.winehq.org/git/vkd3d.git/

**Comment by laichiaheng** [comment]
Isn't it conflict with DXVK?

**Comment by K0bin** [comment]
https://github.com/doitsujin/dxvk/wiki/DXGI
