### ISSUE TITLE
World of Warcraft Stuttering 

### ISSUE THREAD

**Issue by mknepper** [doitsujin/dxvk#1170]
So basically I'm getting these random freezes/stutters. Here's a video of the footage (recorded with OBS):

[https://www.bitchute.com/video/0bCZy4R0AVyb/](https://www.bitchute.com/video/0bCZy4R0AVyb/)

Phenomena occurs at 36 seconds, 1:03, 1:59, and 2:59.

**Notes:** The issue seems to occur when models are loaded onto the screen mostly, though environments seem to do the same thing as well. Renicing the application from the standard of 0 to a new niceness of -14 seems to reduce the random stutter/freezing, but it does not remove it. Turning Xfce 4.12's Vsync and/or compositor doesn't seem to make a difference. The problem persists in fullscreen mode as well. Reducing visual settings also helps mitigate *some* of the issue, but not all. Running on lowest settings, the issue still persists. Disabling esync in the Lutris options doesn't seem to do anything.

### Software information
World of Warcraft
Preset Quality of 7
MSAA disabled
Triple Buffering disabled
Lutris (from PPA) (http://ppa.launchpad.net/lutris-team/lutris/ubuntu)
MESA (from PPA) (http://ppa.launchpad.net/paulo-miguel-dias/pkppa/ubuntu)
Wine (from PPA) (https://dl.winehq.org/wine-builds/ubuntu/)

### System information
- GPU: AMD Radeon RX 580 8GB 
- Driver: mesa-va-drivers/bionic,now 19.1.2-0~b~padoka0 amd64 
- CPU: Ryzen 2700x
- RAM: 3200Mhz Samsung B-Die CL 14 16GB
- Wine version: 4.14 Staging, ge-protonified-nofshack-4.9-x86_64
- DXVK version:  1.32, 0.96, 1.31
- Xubuntu 18.04.3 LTS (kernel: Linux debian 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)

### Log from Lutris:
[https://pastebin.com/fxFUWsMK](https://pastebin.com/fxFUWsMK)

**Having issues with Apitrace. Can't seem to locate the dx11 logs. If there are any other logs that can assist in tracking down the source, let me know and I'll go looking for them. Thank you for your awesome work and contributions to gaming on Linux!**

**Edit: The log contains several runs, but the last session is the one from the video.**

**Comment by doitsujin** [comment]
This is normal and caused by shader compilation. Cannot be fixed.

**Comment by mknepper** [comment]
Alright, cool, thank you! How would I use ACO in Lutris?

**Comment by gcarq** [comment]
@mknepper Here are the official testing instructions: https://steamcommunity.com/app/221410/discussions/0/1640915206474070669/. It's a replacement for mesa, not related to lutris

**Comment by mknepper** [comment]
Ah, I see. Thank you so much. I'm going to give it a shot. I don't know how useful it will be, but I'll post results here.

**Comment by mknepper** [comment]
Update: After installing the ACO Mesa drivers, there is a significant reduction in stuttering to the point where I struggle to notice is. During WoW gameplay, where it used to stutter, I instead see a message that says "compiling shaders". There is next to no stutter now or hang-ups. I'm going to mark this as closed since ACO seems to solve 95% of the problem. Thank you!
