### ISSUE TITLE
Add logging of performance data

### ISSUE THREAD

**Issue by berniyh** [doitsujin/dxvk#1172]
Hi,

I'm aware from various other feature request that you're not too keen on extending the HUD and its functionality.
However one thing that I would find very helpful is actual logging of the shown data.
This would make it easier to track and compare the performance, e.g. to track down performance issues, regressions etc.
And it also would allow for external analysis of the performance if one wishes to do so (e.g. generating histograms).

The respective change is also very simple:
https://github.com/flightlessmango/dxvk/commit/c35fcb5aa9deb783ffd34e1d211e084333c6c8e2

Would need slight modification to remove the cpu utilization that is not present on your branch, but apart from that it should be very close.

**Comment by K0bin** [comment]
I don't think writing to a file on the cs thread (which is what that change does) is a particularly good idea.

**Comment by Joshua-Ashton** [comment]
The flightlessmango hud is a *complete shitshow* in terms of performance.

I also think it's a bit feature creepy and out of scope. Maybe make a VK layer for this?

**Comment by berniyh** [comment]
> I don't think writing to a file on the cs thread (which is what that change does) is a particularly good idea.

I don't know anything about that code. I was just having a look if I can log the data that the HUD is giving me and did a bit of research which brought me to that patch.
If it's not a good idea to do it that way then don't take that patch.

> The flightlessmango hud is a _complete shitshow_ in terms of performance.
> 
> I also think it's a bit feature creepy and out of scope. Maybe make a VK layer for this?

I'm not suggesting to implement everything that branch does. Actually don't want to add anything to the HUD with this.
Just thought it might be a good idea to log the data it already acquires.

**Comment by doitsujin** [comment]
I don't really see why this has to be part of DXVK. I think the Mesa Vulkan layer (`VK_LAYER_MESA_overlay`, also works on Nvidia) already provides this functionality.

**Comment by berniyh** [comment]
Thanks, I didn't know about that one. Yeah, that'll do, so you can close this one.
