### ISSUE TITLE
VRChat freezes when loading some worlds

### ISSUE THREAD

**Issue by AuroransSolis** [doitsujin/dxvk#1176]
Right, so the issue that I've encountered is that certain worlds will just freeze the game on a black screen with the "Hold V" overlay. It's not frequent, but definitely a bit irritating when it happens since I have to `pkill` the game and start it up again. I've confirmed that the same worlds cause the game to crash when running with or without wined3d, with and without eSync. The two worlds that I remember causing this off the top of my head are "The Great Pug" and "Sign Language" (created by _MINT_ in case you find multiple by the same name).

### Software information
VRChat 2019.3.1, launch settings: `PROTON_LOG=1 %command%`, launching through Steam Play

### System information
- GPU: Radeon RX480
- Driver: `media-libs/mesa-19.2.0_rc1` with:
    USE: `X classic dri3 egl gallium gbm gles2 llvm vaapi vulkan`
    VIDEO_CARDS: `intel nouveau radeon radeonsi`
    ABI_x86: 32, 64
- Wine version: Proton 4.11-3
- DXVK version: `app-emulation/dxvk-1.3.2-r1`

### Apitrace file(s)
Not sure I got the output correctly (just right clicked, "Select all", then pasted into Pastebin and _ugh_ manually formatted it), but here we go: https://pastebin.com/3VFhBcNR

### Log files
- d3d11.log: https://pastebin.com/6JgG94jX
- dxgi.log: https://pastebin.com/7xB44mtg

**Comment by doitsujin** [comment]
Does this work on wined3d?

fwiw the "apitrace" you posted isn't an apitrace but just some console output. I'm more interested in the .trace file, ideally recorded on Windows - though I'm not sure how useful that would be in this case.

**Comment by AuroransSolis** [comment]
If you're referring to running this with the `PROTON_USE_WINED3D=1` option, then no, it doesn't work on wined3d (and in fact has quite a few graphical glitches that for some reason don't show up when I use `apitrace`). Here's a link to an Imgur gallery containing a few examples of such graphical issues: https://imgur.com/a/X3rg2Qx.

Apologies about grabbing the wrong `.trace` file. Here's the right one: (good for 1 download and for 7 days): https://send.firefox.com/download/0f82e022e97d95f3/#h1aMuCkftA_awlpnnnf1WA
Or at least I hope it is. Uploading that took literally hours :x

**Comment by leucome** [comment]
VRChat usually freezes  when a world use  youtube-dl.exe.  You can remove/rename this file from VRChat to disable the feature.  It usually resolve the freezing issue.  

It's far from a perfect solution but it make the game playable.

**Comment by Blisto91** [comment]
Was this issue solved?

I have not been able to reproduce it myself when playing some none VR rooms including the great pug and some others.
As said above it seems people had trouble in worlds with youtube-dl in the past? But seems like a proton issue maybe and isn't a problem anymore?

**Comment by Blisto91** [comment]
@AuroransSolis @leucome Friendly ping.
