### ISSUE TITLE
WRC 8 slow performance, fullscreen issue

### ISSUE THREAD

**Issue by mozo78** [doitsujin/dxvk#1186]
The game runs slow with 17-19 FPS no matter the settings (also tried AMD spoof disabled). When I try to set it to fullscreen, the video signal to the display is stopped and I have to restart to get a picture again. The game is not freezing, the sound continue to work but the monitor lose signal and after some time goes to sleep mode. I haven't seen such problem till now.

### Software information
WRC 8 FIA World Rally Championship

### System information
- GPU: GTX 1080 Ti
- Driver: 435.21
- Wine version: 4.14 Staging
- DXVK version: 1.3.3

### Apitrace file(s)
https://my.pcloud.com/publink/show?code=XZGgE5kZJXCn3jsOVom1mQIg47uhKLOx2vfV

### Log files
- d3d11.log:
[WRC8_d3d11.log](https://github.com/doitsujin/dxvk/files/3586550/WRC8_d3d11.log)

- dxgi.log:
[WRC8_dxgi.log](https://github.com/doitsujin/dxvk/files/3586552/WRC8_dxgi.log)

**Comment by doitsujin** [comment]
I need more details.
- Are you CPU bound or GPU bound?
- Can you please post the full wine output?
- Does fullscreen work with wine's dxgi?

**Comment by mozo78** [comment]
Yes, my display complain that there's no signal :) With Wine's dxgi fullscreen mode is working without problems.
With Wine I get 172-200 FPS at the splash screen which is impossible with DXVK. DXVK gives 17 at the splash screen. In game Wine gives 17-30 FPS.
I don't know if I'm CPU or GPU bound, here you are the needed data:
![Screenshot_20190907_170830](https://user-images.githubusercontent.com/38666396/64476070-60721e00-d193-11e9-91a5-8abdff4f93c1.png)
Here you are the Wine log:

[WRC8 wine.zip](https://github.com/doitsujin/dxvk/files/3586667/WRC8.wine.zip)

**Comment by mozo78** [comment]
Yes I also use only KDE and it's my favorite DE and this is the very first game with such problem. Of course I tried to stop effects and the compositor, changing resolution, using d3d11.allowMapFlagNoWait, etc. to no avail.

**Comment by xpander69** [comment]
hey @mozo78 
did the issue happen like this on fullscreen: https://drive.google.com/file/d/1Axu70FvH92ZmSxQOLLJON8A3RcY3QNDs/view

Im having maybe similar problem with WRC 9. works fine in wine virtual window, but without it it performs like 15 FPS on borderless mode and fullscreen then it flickers like that.... im on MATE desktop though, no plasma

**Comment by czarekkwasny** [comment]
I've got exactly the same issue... like in the video attached... Curiously it worked just fine in all modes before i upgraded the nvidia drivers (to 470) but even downgrading them back to 465 didn't resolve the issue. I wonder if there's any solution

**Comment by czarekkwasny** [comment]
Ok, so I managed to workaround the issue... The game seems to work very well with latest Proton-GE-6.16GE and NVIDIA Driver 470.63.01. The two required tweaks are Protontricks (protontricks 1004750 win7) and setting the Steam command line: PROTON_NO_D3D12=1 %command%

**Comment by Blisto91** [comment]
@mozo78 if you are still around can i get you to retest this issue? 🙂

**Comment by xpander69** [comment]
WRC9 and 10 seem to work fine without any issues, but WRC8, for whatever reason opens up fine but the window will get minimized and when trying to bring it up it instantly minimizes again. game is running fine on the background, but cant bring the window up.
This probably is some window manager shenanigan? though i havent seen any other game do that.
how it looks: https://drive.google.com/file/d/1jeXS_neg0wGxM0Xw55WWvVaGMKV0sjSa/view?usp=sharing

**Comment by Blisto91** [comment]
I see the window issue on my system. When i launch it will keep blinking white and can be a bit uncomfortable to look at. Not good for people with epilepsy. This does not happen when i set dxgi to builtin override.
According to the logs it keeps setting the display mode over and over again.

[WRC8_d3d11.log](https://github.com/doitsujin/dxvk/files/9174119/WRC8_d3d11.log)
[WRC8_dxgi.log](https://github.com/doitsujin/dxvk/files/9174120/WRC8_dxgi.log)

Also made a trace with dxvk. Dunno if it's useful
https://mega.nz/file/Z8JhSZ4I#_EyCA2m53LziSXQGIUmvnpidKEERmCYh37TtKdMNNEg

**Comment by Blisto91** [comment]
@xpander69 Could i get you to check your issue again? Latest dxvk and or proton experimental and all that jazz. 🙂

**Comment by xpander69** [comment]
The Constant minimize bug seems to be related to my WM (Marco). Most likely same thing happens on Gnome WM? cause marco is a fork of it. Switching to xfwm4 fixed the issue. The original slow performance issue is also fixed long time ago it seems so this can be closed.
