### ISSUE TITLE
GTAV low fps

### ISSUE THREAD

**Issue by mrdev023** [doitsujin/dxvk#1187]
I'm turn around 20-30fps with any settings (low, high).

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
GTAV (Low or High settings)

### System information
- GPU: RTX 2080ti
- Driver: NVIDIA 430.40
- Wine version: lutris-4.13-x86_64
- DXVK version: 1.3.3

### Apitrace file(s)
- https://mega.nz/#!q1Y31YKJ!9PIRRjbm3tGjtsykGTjtx1q9QmcL-0CftVnawSRzbF4

### Log files
- d3d11.log:
[GTA5_d3d11.log](https://github.com/doitsujin/dxvk/files/3586689/GTA5_d3d11.log)

- dxgi.log:
[GTA5_dxgi.log](https://github.com/doitsujin/dxvk/files/3586688/GTA5_dxgi.log)

**Comment by kassindornelles** [comment]
What DE are you using?
CPU model?
Are you using borderless window or full screen?

**Comment by doitsujin** [comment]
Please try with Proton instead of your Lutris setup. While this game isn't known to run particularly well on DXVK, if you get 20 FPS it's probably an issue on your end (or just an underpowered CPU).

**Comment by mrdev023** [comment]
I have a AMD THREADTRIPPER 2990WX CPU
KDE Plasma
Manjaro
Yes i use ESYNC
With PROTON i have same problem

**Comment by mrdev023** [comment]
I have this only with GTAV on any other Game i have a very good performance

**Comment by doitsujin** [comment]
That sounds like a case of having too many cores then. It's a known issue that (especially the 32-core) Threadripper CPUs don't work well in some games. Please try disabling all but eight cores before running the game.

**Comment by mrdev023** [comment]
How ?

**Comment by doitsujin** [comment]
You'll probably want to disable 16-63, not 9-63, but yes, that's how it works (as root).

Note that some people seem to have issues doing this on some kernels.

**Comment by mrdev023** [comment]
It resolve my issue but why it doesn't work with a lot of CPU because on windows it work perfectly

**Comment by doitsujin** [comment]
Don't know, but that's either a wine issue or a kernel issue, not something I can fix inside DXVK.
