### ISSUE TITLE
RFC: Build system improvements (again)

### ISSUE THREAD

**Issue by pchome** [doitsujin/dxvk#1189]
### Description
People want more compiler/options variants, which are hard to support and which became insane in the `meson.build` file. Let's isolate this variations in the separate directory structures, so if one want support new "compiler-name" compilation, it will be easy to do so, by copy/patch files somewhere else, not touching main `meson.build`.

### Idea
1. Create e.g. `compiler/` directory w/ the following structure:
    ```
    compiler/clang/
    compiler/gcc/
    compiler/mingw-clang/
    compiler/mingw-gcc/
    compiler/msvc/
    compiler/wine-clang/
    compiler/wine-gcc/
    ```

2. Each can contain whatever they need to compile DXVK (additional includes/files/etc.), cross-files and `meson.build`.

3. The `meson.build` file should contain what currently under corresponding condition in the main `meson.build` file.
e.g. for winelib: https://github.com/doitsujin/dxvk/blob/master/meson.build#L28-L49

4. All conditions then could be replaced by the following code
    ```meson
    # compiler_specific_files='compiler/wine-gcc', defined in compiler/wine-gcc/buld-wine64.txt
    # 'compiler/mingw-gcc' - default fallback
    dxvk_compiler_dir = meson.get_cross_property('compiler_specific_files', 'compiler/mingw-gcc')
    subdir(dxvk_compiler_dir)
    ```
    or
    ```meson
    if dxvk_winelib
      subdir('compiler/wine-gcc')
    else
    ```
### Clarification 
Based on how Meson `subdir()` [command work](https://mesonbuild.com/Reference-manual.html#subdir)
> Enters the specified subdirectory and executes the meson.build file in it. Once that is done, it returns and execution continues on the line following this subdir() command. Variables defined in that meson.build file are then available for use in later parts of the current build file and in all subsequent build files executed with subdir().

If "mingw-gcc" is default and only supported compiler, then not necessary to create `compiler/mingw-gcc/` directory for it. You can keep it's parts as-is, just drop everything else and add the ability to redefine variables.

Well, then just forget about those files, no need to support them. Anyone, who use them, will be able to create PR to improve/fix corresponding compilation.

### Mics
Also, later, it may be worth to define more generic names for some lower-level variables, to be redefined. E.g. `d3d11_shared_objects=` (`d3d11_shared_(defs|overrides|...)=`, found in `src/d3d11/meson.build`).

More of possible change candidates: `d3d10_deps=` and other places/variables with conditions, shared library names, etc.

### Conclusion
Just a basic idea. I could create this in practice and PR, if it worth so.

_Theoretically should help "clang"/"dxvk-native"/"macOS"/... users. Also "winelib", to not being completely dropped ;)_

**Comment by doitsujin** [comment]
Isn't the current build system already complicated enough? Why do we need to support **even more** setups in **even worse** ways?

**Comment by pchome** [comment]
The idea is to simplify it for you, in the first place. AFAIK, you don't want to support other compilers than mingw. In the second place -- the ability to just copy custom files into `compilers/compiler-name/` w/o additional changes to all `meson.build` files.

So the `meson.build` file will look like it written for mingw, with only one condition to include third-party directory, which will be supported by the others, or left as-is, not your problem. But yes, the final solution can be worse. That's why asking. 

In particular, I remembered about "dxvk-native", and finally tried to build it. I don't know what the status of this patch, but it trying to mess with the build system even more. Maybe such changes should help to simplifiy the patch, idk. @Guy1524 ?

**Comment by Guy1524** [comment]
@pchome I'll have to look back at my patch to see if this is desirable, but I think the bigger issue was that my patch involved a lot of compiler directives scattered around.

**Comment by pchome** [comment]
I should stop doing dirty hacks (lazybones).

I remembered, I already tried to do something like this [a while ago](https://github.com/pchome/dxvk-experiments/tree/winebuild/linux), and that was rather bad idea.
