### ISSUE TITLE
World of Warcraft 32-bit client reverts back to wine D3D9

### ISSUE THREAD

**Issue by ChazyTheBest** [doitsujin/dxvk#1192]
When I run a 64-bit WoW client (like 5.4.8), the game runs just fine with D3D11 support, I can see the DXVK HUD and everything is working as expected.

![Screenshot_20190915_225135](https://user-images.githubusercontent.com/654229/64927522-25639080-d80c-11e9-82c9-4080d989302a.png)

With a 32-bit client, however, there's no HUD so DXVK is failing to create the instance and reverts back to D3D9 (what the logs say).

Older WoW versions (< 4.0.1) don't have a 64-bit client, so I can only run the only executable which is 32-bit. I think only version 3.3.5a has D3D11 support, but I'm not 100% sure.

I'm on Arch Linux (everything should be up to date), and I just got the latest DXVK release, the AUR bin package is out of date by quite a bit.

Steps I followed:

```bash
$ git clone https://github.com/doitsujin/dxvk/
$ cd dxvk
$ ./package-release.sh master /home/GAMES/ --no-package
$ sudo -u wineuser /home/GAMES/dxvk-master/setup_dxvk.sh install
```

Nothing special, really.

### System information
- GPU: AMD Radeon RX 480 8GB
- Driver: AMDGPU
- Wine version: wine-staging-4.15-1
- DXVK version: 1.3.4-2-gc852b6de

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
    - 5.4.8 64-bit client:
https://gist.github.com/ChazyTheBest/6fc5801e3abec694eb5b0f8ff692e0f5
    - 5.4.8 32-bit client: empty
    - 3.3.5a client: empty
- dxgi.log:
    - 5.4.8 64-bit client:
https://gist.github.com/ChazyTheBest/83d94c2badeaac8589ff99e27524c4f7
    - 5.4.8 32-bit client:
https://gist.github.com/ChazyTheBest/e0babb79819cc511af9558261f9e4bd0
    - 3.3.5a client: empty

3.3.5a console log: https://gist.github.com/ChazyTheBest/9dbf21d3679cfc72eb780575fcdec956

**Comment by K0bin** [comment]
You don't have a 32bit Vulkan driver installed.

**Comment by Thaodan** [comment]
Wow pre 4.x has D3D11 mode see:
https://wow.gamepedia.com/CVar_gxApi[1] 

--------
[1] https://wow.gamepedia.com/CVar_gxApi

**Comment by doitsujin** [comment]
Like @K0bin mentioned, you're missing some 32-bit packages. Make sure you have [lib32-vulkan-icd-loader](https://www.archlinux.org/packages/?q=lib32-vulkan-icd-loader) and [lib32-vulkan-radeon](https://www.archlinux.org/packages/multilib/x86_64/lib32-vulkan-radeon/) installed.

**Comment by ChazyTheBest** [comment]
My bad, I was missing `lib32-vulkan-radeon` package.

I still can't make Wow 3.3.5a work in D3D11 mode...

@Thaodan Looks like it doesn't, if you take a better look, D3D11 is under 4.0.1:

> Cataclysm Patch 4.0.1 (2010-10-12):
>     DirectX11 compatibility mode added - "d3d11"

**Comment by Thaodan** [comment]
I said pre 4.x had NO D3D11 
mode.

**Comment by ChazyTheBest** [comment]
> I said pre 4.x had NO D3D11 mode.

I don't see a "no" in your first comment.

> Wow pre 4.x has D3D11 mode see: [https://wow.gamepedia.com/CVar_gxApi[1]](https://wow.gamepedia.com/CVar_gxApi%5B1%5D)
> […](#)
> -------- [1] https://wow.gamepedia.com/CVar_gxApi
