### ISSUE TITLE
Remark about Neverwinter Online (and possibly others) with low memory GPUs

### ISSUE THREAD

**Issue by QuImUfu** [doitsujin/dxvk#1195]
I made some observations playing Neverwinter Online on a RX 460 2GB card with DXVK 1.3.4:
When playing Neverwinter Online memory usage increases till the game thinks it hit the cards memory limit. With DXVK at that point it already uses ~500MB=~25% more memory than the card has available and the performance tanks.  
If i set dxgi.maxDeviceMemory and dxgi.maxSharedMemory to half of the cards actual memory (1024) the game runs without any issues, with only a very minor performance hit and starts cleaning up as soon as dxvks hud reports it is hitting ~1500 MB (the game probably thinks it hit 1000 MB at that point).  
I do not know whether this is of interst, but maybe DXVK could purposely report less memory (e.g. 50% of actual available memory) for this game (and possibly others) without the user having to create/edit a config.

**Comment by doitsujin** [comment]
> but maybe DXVK could purposely report less memory (e.g. 50% of actual available memory)

No, the config options exist for this exact purpose.

In this case it just seems that the game grossly underestimates the amount of VRAM that other resources need (esp. render targets and such), but on 4GB cards this is probably less of an issue, and for other games that aren't being stupid it's just straight-up *wrong* to report 50% less.

**Comment by QuImUfu** [comment]
yes, that is clear, but as i understood dxvk ships with default configs for different games. Why should the "Neverwinter Online" default config not contain this workaround?

**Comment by doitsujin** [comment]
Because a) it is not clear on which setups it is needed and b) reporting "50% less" just isn't supported, just fixed numbers, and I don't plan to change that.
