### ISSUE TITLE
Latest Rockstar Games Launcher (needed for GTAV) unable to launch with dxvk

### ISSUE THREAD

**Issue by fls2018** [doitsujin/dxvk#1196]
The latest launcher update spits out an "Unable to launch game, please verify game data" error when attempting to launch with dxvk, it works fine with wined3d.

Using a custom winecfg for GTA5.exe and manual/symlink dxvk means you can get into game but it's not very practical for proton.

I've included a wine log output running wined3d below.

### Software information
[Rockstar Games Launcher](https://www.rockstargames.com/newswire/article/61123/Download-The-Rockstar-Games-Launcher)

Due to other install bugs the .exe needs to be manually unpacked as described here:

https://github.com/ValveSoftware/Proton/issues/37#issuecomment-532857480

It also requires vc runtime 2019 (and corefonts if running in wine).

### System information
- GPU: GTX 1070
- Driver: 435.21
- Wine version: Proton/Lutris 4.15
- DXVK version: 1.3.4

### Log files
wined3d output - [output.txt](https://github.com/doitsujin/dxvk/files/3630956/output.txt)

**Comment by doitsujin** [comment]
This is a bug in Wine's Direct2D implementation. I do not plan to work around this in DXVK.

**Comment by fls2018** [comment]
I tried that commit and it made no difference, unfortunately an update today has broke the launcher even more & now the game doesn't launch with the wined3d workaround in the first post.

**Comment by CodingKoopa** [comment]
[This](https://github.com/ValveSoftware/Proton/issues/37#issuecomment-533347654) comment may be relevant for testing today's launcher update.

**Comment by fls2018** [comment]
> [This](https://github.com/ValveSoftware/Proton/issues/37#issuecomment-533347654) comment may be relevant for testing today's launcher update.

I've just done those patches and combined with latest dxvk master the launcher now works graphically at least, however today's update has caused some other issues,

I'm confident that the issue with dxvk not working with the launcher now has a potential fix so I can probably close this, just the administrator issue for now to resolve.

Thanks again @doitsujin for the dxvk related fixes.
