### ISSUE TITLE
Install script resets winecfg Desktop Integration / My Documents mapping

### ISSUE THREAD

**Issue by foresto** [doitsujin/dxvk#1199]
Whenever I use setup_dxvk.sh to install a new version, it resets the Wine prefix's My Documents folder mapping back to its default value, which is my home directory. This leads to missing game saves and clutter in my home directory, until I notice and fix it.

### System information
- Wine version: 4.16 staging
- DXVK version: 1.4

**Comment by Joshua-Ashton** [comment]
Could be ``$wineboot -u`` causing it. Will test this tomorrow.

**Comment by doitsujin** [comment]
Does this also happen after a wine version update? If so then it's *definitely* `wineboot -u`.

I suppose I could add a flag to skip that step, but it might not be desireable.

**Comment by jp7677** [comment]
yes, this is definitely `wineboot`. I'm also also loosing the folder mappings with each wine update. I would love to now how to prevent this when wine updates/setup a prefix. Or alternatively, how to set the mapping from cmd.

**Comment by rodrigo21** [comment]
Try chmod -w 'your user' on the prefix/users folder.

Works for me.

**Comment by foresto** [comment]
> Does this also happen after a wine version update?

It happens whenever I run setup_dxvk.sh install, regardless of whether wine has been updated, and regardless of whether the dxvk install files have been updated.

**Comment by doitsujin** [comment]
That's not what I was asking. I was asking whether you also lose your folder mappings **after a wine update**, regardless of whether you ran the script or not. But @jp7677 basically answered that already.

The script itself **does not** mess with your folder overrides, it's one specific wine command that it runs. Honestly this really isn't a bug, let alone my bug, it's just what running wineboot does, the best thing I can do is provide a workaround which may break uninstalling dxvk.

**Comment by foresto** [comment]
I see. I wasn't trying to blame anyone; just pointing out that running the script causes minor breakage (even if it's a side effect), and thought you'd like to know about it.

> the best thing I can do is provide a workaround which may break uninstalling dxvk.

If the only solution would be to break dxvk's uninstall, then I wouldn't worry about it. The folder mapping breakage is annoying, but easy enough to fix manually. Maybe a wine bug report is in order here.

**Comment by pchome** [comment]
`$ find pfx/drive_c/users/*/ -type l -exec ls -l {} +`
Your custom mappings usually just a symbolic links.

**Comment by jp7677** [comment]
> `$ find pfx/drive_c/users/*/ -type l -exec ls -l {} +`
> Your custom mappings usually just a symbolic links.

My guess would be registry settings, but haven't actually looked into it.

**Comment by pchome** [comment]
> My guess would be registry settings, but haven't actually looked into it.

`$wine regedit /?` or `$wine reg /?`

**Comment by SveSop** [comment]
@foresto 
Does this happen for default vanilla wine (from WineHQ) in a NEW wineprefix you have not installed anything into?

I bet it do not...
There is some registry tweakage to the default wine behavior of this.. Maybe you one time (or something else) made something like this: [https://www.reddit.com/r/wine_gaming/comments/8vwi0n/how_to_prevent_wine_from_making_folder_shortcuts/](https://www.reddit.com/r/wine_gaming/comments/8vwi0n/how_to_prevent_wine_from_making_folder_shortcuts/)

eg. `winetricks sandbox` I have not tried that one, but `wineboot -u` does not do what you describe unless you are using a modified wineprefix OR a modified wine version :)

**Comment by foresto** [comment]
> Maybe you one time (or something else) made something like this:

No, I never ran *winetricks sandbox* or any other hackery on the user directories. I simply used *winecfg* to point My Documents at a directory other than the default $HOME. The prefix is very recent.

I'm using official wine-staging from winehq's repository. Is there some reason to believe that staging behaves differently from non-staging in this area?

**Comment by SveSop** [comment]
> I'm using official wine-staging from winehq's repository. Is there some reason to believe that staging behaves differently from non-staging in this area?
Nope.

Sadly this is the default wine behavior. Maybe post on the winehq forum or something to get a tips if it is possible to make this permanent after a `wineboot -u` operation. And as others have pointed out, the SAME problem will also happen whenever you get a new wine version (and thats appx every fortnight when it comes to wine).

**Comment by bobwya** [comment]
@foresto 

I added the winetricks verb:

    winetricks isolate_home

because of this very issue. This change is more permanent, and will persist through:

    wineboot -u

operations. This will leave the **Z:** **/** (root) mapping in place.

I did post some patches to the **wine-devel** ML (last summer) to start resolving this issue. But after be assigned to a reviewer I heard nothing further...

**Comment by Fincer** [comment]
[Wine bugzilla issue #22974 ("Shell folders" settings are reset after each wine update)](https://bugs.winehq.org/show_bug.cgi?id=22974) may be related, you might want to check it out.

**Comment by foresto** [comment]
Wow, more response here than I expected. Nice to see people so interested in making things work better.

@bobwya, I don't see isolate_home in [winetricks master](https://github.com/Winetricks/winetricks/blob/master/src/winetricks). Is your new verb implementation someplace where I can see it?

@Fincer, thanks for the winehq link. The latest patch set is encouraging.

**Comment by pchome** [comment]
@foresto 
https://github.com/Winetricks/winetricks/search?q=isolate_home&type=Commits

**Comment by ionenwks** [comment]
> [Wine bugzilla issue #22974 ("Shell folders" settings are reset after each wine update)](https://bugs.winehq.org/show_bug.cgi?id=22974) may be related, you might want to check it out.

I'm amazed to see this is still around. I build my own wine and had the patch from there a for a long time now so I tend to forget it's a thing.

**Comment by bobwya** [comment]
> 
> @bobwya, I don't see isolate_home in [winetricks master](https://github.com/Winetricks/winetricks/blob/master/src/winetricks). Is your new verb implementation someplace where I can see it?

The verb has been committed, in winetricks, since June 2018... :-)

**Comment by ionenwks** [comment]
Seems wine finally pushed a fix for this 10 years old bug in wine-5.3, I tried and updating doesn't cause folders to reset anymore. This wasn't dxvk's bug in the first place either way so I feel this should probably be closed.
