### ISSUE TITLE
Ni No Kuni Remastered - Rendering Issue

### ISSUE THREAD

**Issue by alligatorshoes** [doitsujin/dxvk#1200]
Ni No Kuni remastered has some odd issues when rendering plants and trees. Apologies for the poor explanation, but here's a picture I took:

![20190922_171522_resized](https://user-images.githubusercontent.com/44007961/65391267-1d04db80-dd5f-11e9-9d97-b180ad3cee49.jpg)

With debug logging enabled, a huge amount of fixme's are being thrown out, such as:

`002a:fixme:d3dcompiler:skip_dword_unknown Skipping 4 unknown DWORDs:
002a:fixme:d3dcompiler:skip_dword_unknown 	0x7b891201
002a:fixme:d3dcompiler:skip_dword_unknown 	0x0c5eee17
002a:fixme:d3dcompiler:skip_dword_unknown 	0xfff94af7
002a:fixme:d3dcompiler:skip_dword_unknown 	0x267d6b3e
002a:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000001
002a:fixme:d3dcompiler:skip_dword_unknown Skipping 8 unknown DWORDs:
002a:fixme:d3dcompiler:skip_dword_unknown 	0x31314452
002a:fixme:d3dcompiler:skip_dword_unknown 	0x0000003c
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000018
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000020
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000028
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000024
002a:fixme:d3dcompiler:skip_dword_unknown 	0x0000000c
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
002a:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000008
002a:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000008
002a:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
002a:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
002a:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
002a:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
002a:fixme:d3dcompiler:skip_dword_unknown Skipping 2 unknown DWORDs:
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
002a:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
002a:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
002a:fixme:d3dcompiler:skip_dword_unknown Skipping 3 unknown DWORDs:
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
002a:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
002a:fixme:d3dcompiler:d3dcompiler_shader_reflection_GetDesc iface 0x3f92b690, desc 0x24eba0 partial stub!`

### Software information
Ni No Kuni Remastered

### System information
- GPU: GTX 1070
- Driver: 435.21.0
- Wine version: Proton 4.11-5
- DXVK version: 1.4

### Apitrace file(s)
https://www.dropbox.com/s/oiv70tvbsqbcowe/NinoKuni_WotWW_Remastered.trace.tar.gz?dl=0

### Log files
[logs.tar.gz](https://github.com/doitsujin/dxvk/files/3639964/logs.tar.gz)

**Comment by doitsujin** [comment]
Try `winetricks d3dcompiler_43` and `winetricks d3dcompiler_47`.

If that doesn't fix your issue, but the FIXMEs disappear, then I'm going to need an apitrace to look into this.

**Comment by alligatorshoes** [comment]
Thanks for your response. So in terms of apitrace, do I just place the d3d11.dll, dxgi.dll and dxgitrace.dll files in the same file as the game .exe and then run the title? Do I need DXVK enabled or disabled for the run?

Amusingly the game doesn't work *without* DXVK enabled, and with DXVK enabled it's like a slide-show, running perhaps 1 frame every few seconds or so.

> An apitrace would really be helful though since the shaders seem to contain instructions that I've never seen in any other game before and aren't supported by DXVK right now; having a test case for those would be nice.

I think you're right. It won't even run without DXVK, generating a bunch of d3d11 not supported errors.

**Comment by doitsujin** [comment]
> do I just place the d3d11.dll, dxgi.dll and dxgitrace.dll files in the same file as the game .exe and then run the title?

Yes, that should work.

> Do I need DXVK enabled or disabled for the run?

Enabled in this case.

> and with DXVK enabled it's like a slide-show, running perhaps 1 frame every few seconds or so (with apitrace files installed).

I'm afraid that's normal. What's important is that you capture a few frames where the rendering issues are visible so that I can try to reproduce the problem on my end.

**Comment by alligatorshoes** [comment]
Thanks for the information, as a relative newbie to this, it is most appreciated.

I've added the API trace to my original post now. Please let me know if I can provide any more diagnostic or debug information.

**Comment by kiberx** [comment]
Hello,
Same issue, attached apitrace with DXVK.
Game: NinoKuni_WotWW_Remastered.exe
DXVK: v1.4
GPU: GeForce GTX 970
Driver: 435.21.0
https://drive.google.com/file/d/1rZIi7ymJaZ-qSiSTthGr4oEk7qUOKdmG/view?usp=sharing

**Comment by kiberx** [comment]
![nino](https://user-images.githubusercontent.com/34471603/65393684-923ad580-dd8c-11e9-93f3-b0397b8cecd1.png)
Screenshot with render issue.

**Comment by doitsujin** [comment]
Thanks for providing the trace, this should be fixed. Here's a build:
[dxvk-nino.tar.gz](https://github.com/doitsujin/dxvk/files/3640142/dxvk-nino.tar.gz)

**Comment by alligatorshoes** [comment]
Holy crap that was fast! Thanks so much for taking the time to look into this and provide a fix so quickly! I can confirm that this is fixed in your linked build.

Thank you!

**Comment by Pik-a-boo** [comment]
I still got some lighting/artifacts problem with the game.
![Screenshot_20190930_174755](https://user-images.githubusercontent.com/48792756/65889896-ae50ff00-e3aa-11e9-86f8-dbbc421335b0.png)
GPU: Radeon 530
Driver : Mesa 19.2 with and without ACO.

**Comment by doitsujin** [comment]
Can you try amdvlk? Could be a GCN 1-specific driver bug.

**Comment by alligatorshoes** [comment]
Just wanted to provide my own feedback here... I can't see anything obviously wrong in the screenshot above. What is the exact problem with it? The game has a somewhat comic-book art style so it looks how I'd expect. It also doesn't help you're in a dark spot in the game where there are many shadows, etc.

**Comment by Pik-a-boo** [comment]
![Screenshot_20191001_113500](https://user-images.githubusercontent.com/48792756/65946842-b5761c80-e43f-11e9-902a-f32d95a9b7cf.png)
This is how it should look, it looks that way on my Intel GPU (but it way slower for playing the game).
I wish i could use AMDVLK but thats what i get when i use it lol 
![תמונה](https://user-images.githubusercontent.com/48792756/65947176-64b2f380-e440-11e9-8680-af830fe6c6af.png)
I will upload a apitrace if i figure how and if its still needed.
