### ISSUE TITLE
Chain swap failure - Heroes of the Storm

### ISSUE THREAD

**Issue by mcrowson** [doitsujin/dxvk#1204]
The game Heroes of the Storm made an update and now the game crashes. I suspect there is some needed dxvk config needed after reading [this](https://github.com/doitsujin/dxvk/wiki/Common-issues#errors-about-missing-d3d11-support) and seeing that [input issues](https://github.com/doitsujin/dxvk/wiki/Common-issues#input-issues) seem to be a common thing. Just not sure how to configure it.

The game works if I turn off DXVK and set PBA_ENABLE=1 as an environment variable.

### Software information
Heroes of the Storm

### System information
- GPU: nVidia GeForce GTX 950
- Driver:430.50.0
- Wine version: 4.16
- DXVK version: 1.4

### Apitrace file(s)
I genuinely tried to install this and get it going, but am not familiar enough with wine etc. Sorry :( I can spend more time figuring this out if requested.

### Log files
- d3d11.log:[HeroesOfTheStorm_x64_d3d11.log](https://github.com/doitsujin/dxvk/files/3654999/HeroesOfTheStorm_x64_d3d11.log)

- dxgi.log: [HeroesOfTheStorm_x64_dxgi.log](https://github.com/doitsujin/dxvk/files/3655000/HeroesOfTheStorm_x64_dxgi.log)

**Comment by doitsujin** [comment]
Please post the full wine output. All the DXVK logs are going to tell us is that we cannot create a Vulkan swap chain for the window for whatever reason - note that this is **not** a bug and cannot be fixed inside DXVK, but getting some info on what the issue is would be a start.

**Comment by mcrowson** [comment]
I figured this was a configuration issue and not a bug, but was not sure where else to get help. Thanks for taking a look at least. Here are the wine logs. I haven't seen anything obvious, but maybe your eyes can find what I'm missing.
[wine_hots_out.log](https://github.com/doitsujin/dxvk/files/3655334/wine_hots_out.log)

**Comment by doitsujin** [comment]
That's a log from battle.net, it does not include any messages from the actual game.

**Comment by SveSop** [comment]
@mcrowson 
The env variable `PBA_ENABLE=1` does nothing for wine-4.16 as it is not compatible with wine-4.x (It does not hurt, but does nothing)

**Comment by mcrowson** [comment]
I realize we're well into the depths of my ignorance here and not into a dxvk bug, but I'm not above asking for help. 

The game has to be launched through the Battle.net launcher, and so it is a child process. The log settings for Lutris (how I'm running it) are just for the parent process of the Battle.net launcher. So my question is, how can I get logs from the child processes as well from wine? I'm assuming I'll do it via command line, but I haven't found any obvious flags for doing this.

**Comment by mcrowson** [comment]
Additionally, this appears to just be an issue with NVIDIA cards, players with AMD seem to have no issue.

**Comment by xunto** [comment]
I can confirm that crash happens after this update. Games crashes only if dxvk is installed. I wasn't able to find any meaningful error message though.

**Comment by mcrowson** [comment]
Crash no longer happens with 1.4.2
