### ISSUE TITLE
DX11 feature level 10.0 required to run the engine 

### ISSUE THREAD

**Issue by iqrulltion** [doitsujin/dxvk#1205]
I am trying to run an indie game called " project tetra - using unreal engine " the game working without dxvk but the graphics not clear/normal there is for example some black parts on screen etc.

The game error message is " DX11 feature level 10.0 required to run the engine "

Normally with dxvk i face " missed directX11 error message or update directX etc " and some games that require directX 9 or 10 **working without complaining** with dxvk .. 

I am using DXVK: v1.4 , vulkan packages are installed 
libvulkan-dev-libvulkan1-libvulkan1:i368-mesa-vulkan-drivers/mesa-vulkan-drivers:i3
vulakn-utlis

last time i asked you said vulkan is not installed but how that possible ?

logs/system info etc 
[dxvk-log.tar.gz](https://github.com/doitsujin/dxvk/files/3659628/dxvk-log.tar.gz)

**Comment by K0bin** [comment]
> info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
err:   DxvkInstance::createInstance: Failed to create Vulkan instance

Your graphics driver isnt installed correctly.

**Comment by iqrulltion** [comment]
> Your graphics driver isnt installed correctly.
the default ? installed by Linux or vulkan

**Comment by doitsujin** [comment]
Please post the full wine logs. This isn't a dxvk bug, it's something going horribly wrong either on your setup or inside wine.

**Comment by Leopard1907** [comment]
https://github.com/lutris/lutris/wiki/Installing-drivers

Follow that guide.

**Comment by iqrulltion** [comment]
> Please post the full wine logs. This isn't a dxvk bug, it's something going horribly wrong either on your setup or inside wine.

I  already posted wine log while ruining the game or you asking about  the backtrace? 

> Follow that guide.

 i installed vulakn for Ubuntu/AMD but i might try to install it again from this guide and see what will happen , i am now updating the graphics drivers.

**Comment by doitsujin** [comment]
Sorry, I assumed the files would only contain DXVK logs. In general it's better to upload the raw text files instead of archives because having to unpack log files is quite frankly a pain in the arse.

Anyway, from what I can tell there really is nothing I can do here; there don't seem to be any Vulkan-capable GPUs on your system.

**Comment by varris1** [comment]
What's your GPU? (Your logs just say "Radeon HD"). Does vulkaninfo work?

**Comment by iqrulltion** [comment]
> from what I can tell there really is nothing I can do here; there don't seem to be any Vulkan-capable GPUs on your system.

> Does vulkaninfo work?

I installed Vulkan from the linked guide , but same results.
I did not use this command before as i remember but the output is
```
VULKAN INFO

Vulkan Instance Version: 1.1.70

ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32
/build/vulkan-UL09PJ/vulkan-1.1.70+dfsg1/demos/vulkaninfo.c:2700: failed with VK_ERROR_INITIALIZATION_FAILED

```

**Comment by varris1** [comment]
Ok. So what's your exact GPU?

**Comment by iqrulltion** [comment]
> Ok. So what's your exact GPU?
AMD  [Radeon HD 6610M/7610M] 

what about the erros from vulkan info ?

-
note: i just tested the game, working with dxvk without showing the error but the graphics still the same beside no changes at dxgi log (dxvk)

**Comment by varris1** [comment]
Your GPU is not Vulkan compatible, sorry. There is no way for you to fix that as long as you don't upgrade to a newer GPU.

**Comment by iqrulltion** [comment]
at least we know where is the problem now.. 

done, thanks all.
