### ISSUE TITLE
Full screen window cannot be implemented

### ISSUE THREAD

**Issue by shijiediyo** [doitsujin/dxvk#1206]
### System information
- GPU:RX580
- Driver:19.2.2
- Wine version: WIN10
- DXVK version: 1.4

In the game can not open full-screen window, but I press "win" after the game is full-screen window in the background, click on the game will enter the full-screen state, I found that after the computer screen automatic sleep, wake up the screen can solve the problem of not full-screen window.

Can this problem be solved?

**Comment by doitsujin** [comment]
Can you *please* at the very least tell us which game you're talking about?

In general I don't care about Windows-only issues too much. If your monitor switches off then that sounds like it doesn't handle certain display modes correctly; that's not necessarily something I can fix anyway.

**Comment by shijiediyo** [comment]
[gujianol_dxgi.log](https://github.com/doitsujin/dxvk/files/3665341/gujianol_dxgi.log)
[gujianol_d3d11.log](https://github.com/doitsujin/dxvk/files/3665342/gujianol_d3d11.log)
game：Blade & Soul    Black Desert   
I tried to run on three games and the results were the same.

**Comment by shijiediyo** [comment]
[gujianol_d3d11.log](https://github.com/doitsujin/dxvk/files/3665347/gujianol_d3d11.log)
[Uploading gujianol_dxgi.log…]()

**Comment by shijiediyo** [comment]
I play online games, I try a lot of online games, but there will be this problem, leading to I can not communicate with the players normally, this problem affects the game experience.

Game Name: 逆水寒   古剑奇谭ol (China's game)

**Comment by shijiediyo** [comment]
[GacRunnerNG_d3d11.log](https://github.com/doitsujin/dxvk/files/3665350/GacRunnerNG_d3d11.log)
[GacRunnerNG_dxgi.log](https://github.com/doitsujin/dxvk/files/3665351/GacRunnerNG_dxgi.log)

**Comment by doitsujin** [comment]
Not much I can do here, sorry.
