### ISSUE TITLE
LotRO - Failed to create surface

### ISSUE THREAD

**Issue by trimbode11** [doitsujin/dxvk#1207]
Hi,

since the last Update of Lord of the RIngs Online I am unable to start LotRO in DX11 Mode when I use 64bit Client.
With 32bit (DX11) Client or the 64bit Client with D9VK the game starts with no Problem. Its only a problem with the 64bit client and DX11 (dxvk). When I use the wine DX11 implementation the game starts.

The last messages I get are:

> info:  DXVK: Read 3902 valid state cache entries
> info:  DXVK: Using 4 compiler threads
> err:   Failed to create surface
> 003a:err:ole:CoUninitialize Mismatched CoUninitialize

I use Manjaro (Last Version) with wine 4.16 (Lutris) and DXVK 1.4.1.
Nvidia 1070 Card and a intel CPU (i7 7700)

I testet other DXVK versions and other wine versions. Same error there.
Is it a DXVK Bug or a problem in wine?

[wine.log](https://github.com/doitsujin/dxvk/files/3665531/wine.log)

Greetings

**Comment by Joshua-Ashton** [comment]
Please try setting `dxgi.deferSurfaceCreation = False` in `dxvk.conf`

**Comment by trimbode11** [comment]
Thanks for the repley.
I tryed it with setting:

> dxgi.deferSurfaceCreation = True in dxvk.conf

The game now starts but I only get a black screen (I can hear the ingame music).

In the Log I see many errors like:

> err:   Failed to create surface

Here is the complete log:
[wine2.log](https://github.com/doitsujin/dxvk/files/3665590/wine2.log)

**Comment by doitsujin** [comment]
I don't know what the problem is, but this cannot be fixed inside DXVK. I suggest sticking to D3D9 in this case.

**Comment by trimbode11** [comment]
Hi,
doitsujin, thank you for your help and the tip with the intel GPU.
I disabled the Intel GPU in the Bios and the game now starts without any problem.
