### ISSUE TITLE
Star Wars Battlefront (2015) No Text Rendered

### ISSUE THREAD

**Issue by BuzzBumbleBee** [doitsujin/dxvk#1210]
Game starts and runs fine, but no text shown in any of the in game GUI (See screenshots below)

![Screenshot from 2019-09-30 17-09-43](https://user-images.githubusercontent.com/484334/65896900-046f7380-e3a6-11e9-9eb8-1c75742f6080.png)

### Software information

App : Star Wars Battlefront (2015) (Via Origin)
OS : Arch Linux / Kernel 5.3.1-arch1-1-ARCH
Wine Additions : vcrun2010,vcrun2013,vcrun2015,vcrun2017,allfonts,faudio

### System information
- GPU: AMD Vega 64
- Driver: Vulkan version 1.1.107 / Driver Version 19.2.0
- Wine version:  4.16 (Staging)
- DXVK version: 1.4.1

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
[starwarsbattlefront_d3d11.log](https://github.com/doitsujin/dxvk/files/3672175/starwarsbattlefront_d3d11.log)

- dxgi.log:
[starwarsbattlefront_dxgi.log](https://github.com/doitsujin/dxvk/files/3672178/starwarsbattlefront_dxgi.log)

**Comment by doitsujin** [comment]
You sure this is a DXVK bug and not just something else broken in wine?

**Comment by BuzzBumbleBee** [comment]
It "was" working on 4.16 staging before moving to 1.4.1 but I did have to setup a new prefix when updating DXVK libs. will grab API trace asap

**Comment by doitsujin** [comment]
Closing due to lack of feedback.
