### ISSUE TITLE
Dark Souls 3 Not compiling shaders

### ISSUE THREAD

**Issue by AizerMortenort** [doitsujin/dxvk#1211]
[DarkSoulsIII_d3d11.log](https://github.com/doitsujin/dxvk/files/3672548/DarkSoulsIII_d3d11.log)
[DarkSoulsIII_dxgi.log](https://github.com/doitsujin/dxvk/files/3672549/DarkSoulsIII_dxgi.log)

Dark Souls 3 Does not compile shaders

**Comment by K0bin** [comment]
What does 'Not compiling shaders' mean? How does that show? The logs are completely fine. Please post screenshots of the issue you're having.

**Comment by AizerMortenort** [comment]
I have no .dxvk file created in the dark souls 3 directory.

**Comment by doitsujin** [comment]
I assume you're talking about the state cache. Works fine according to the logs:
```
info:  VK_EXT_shader_demote_to_helper_invocation
```
Note that with Proton, the cache file will **not** be stored inside the game directory.
