### ISSUE TITLE
Can't alt tab in Final Fantasy XIV or League of Legends

### ISSUE THREAD

**Issue by lapinsami** [doitsujin/dxvk#1212]
https://github.com/doitsujin/dxvk/issues/866
https://github.com/Joshua-Ashton/d9vk/issues/76
https://github.com/Joshua-Ashton/d9vk/issues/77
https://github.com/Joshua-Ashton/d9vk/issues/391

Both games (FF14 & LoL) have a separate client that creates the main game window. The main game window is set to "Keep above others" in KDE. Happens on Gnome as well. Alt tabbing works if you uncheck the "Keep above others" box but it's inaccessible if your task manager is on the same monitor as the game. League creates a new window for every match so the setting "resets" after every game. Doesn't matter if the compositor is enabled or disabled. League alt tabs fine when using Gallium Nine.

The bug here isn't that alt tabbing doesn't work; it works perfectly after you uncheck the box. But that shoudn't be the default.

Software information

App : Final Fantasy XIV (using Proton) & League of Legends (D9VK)
OS : Manjaro Linux - every kernel since jan 2019

System information

GPU: Vega 56
Driver: mesa - every version since jan 2019
Wine version: every version since jan 2019 (staging)
DXVK version: every version since jan 2019
D9VK version: every version since may 2019

**Comment by Joshua-Ashton** [comment]
This is an issue because we don't inject our own window proc to handle entering/leaving fullscreen, etc when requested (and also implementing the OCCLUDED response) -- as the game is spamming focus calls.

The reason I am hesitant about implementing this in D9VK, at least [these concerns don't affect DXVK], is because I would also have to implement the whole device loss crap that comes with that in D3D9. The problem with that is qutie a lot of games will instead just crash if they recieve a device loss.

So I'm kinda undecided... Should I implement it, and mirror native crashes across a bunch of games **or** not implement it and have a handful of games where alt-tab is broken.

If you're interested in testing out the former option in D9VK (this does not affect d3d10 or d3d11), there is a https://github.com/Joshua-Ashton/d9vk/tree/wip-alt-tab branch, although it has some issues and doesn't work 100% of the time yet. [I think there is some race going on]

**Comment by alligatorshoes** [comment]
Could you not just set up KDE Window rules for any games that are affected by this instead? This would ensure you don't need to manually uncheck "Keep Above Others" every time you execute the game.

**Comment by doitsujin** [comment]
Fullscreen won't work at all work without "Keep Above Others".

Does this work with wine's DXGI implementation? They do effectively the same thing but implement some more of the DXGI internals, so I'm curious if that works any better.

**Comment by h3fang** [comment]
I use i3wm with Path of Exile. If I switch to another workspace or switch back to the game, or ctrl+alt+F2 to another tty (a new i3wm session), the game / other apps freeze for a long time then switches. 
`setup_dxvk uninstall` then `setup_dxvk install --without-dxgi` makes no difference.

**Comment by K0bin** [comment]
@h3fang That's unrelated to the issue.

**Comment by h3fang** [comment]
@K0bin I thought alt tab and switching from a workspace (fullscreen game) to another workspace (say chromium) are the same things. Sorry if they are not.

**Comment by doitsujin** [comment]
They are not. Your problem also very much sounds like a problem somewhere in your graphics stack; DXVK itself definitely doesn't affect native Linux applications in any way.

**Comment by h3fang** [comment]
@doitsujin Sorry for the disturbance.

**Comment by Vogelchevalier** [comment]
@doitsujin 
> Does this work with wine's DXGI implementation?

No.
@Joshua-Ashton 
>If you're interested in testing out the former option in D9VK

Tested, no difference.

**Comment by Joshua-Ashton** [comment]
Yeah you might need to try that WIP commit a few times, it's hit or miss whether it works due to some race somewhere I haven't found.

**Comment by h3fang** [comment]
@doitsujin Tested with https://github.com/krh/vkcube and it freezes as well. So my problem is related to the nvidia vulkan driver (435.21). Hopefully, my next graphics card will not be nvidia ...

Really sorry for the messing up.

**Comment by clementhk** [comment]
In macOS a new fullscreen is always created in a new workspace, and people can just switch between workspace. I think it's brilliant because then they don't need to deal with all these things, and it's very user friendly.

**Comment by AizerMortenort** [comment]
i have same issue. I am on windows 10 i cant minimize DARK SOULS III and if i change it to windowed mode it means it will random crash latter

**Comment by yCatDev** [comment]
Same issue there but in ALL games that running using DXVK.

**Comment by Blisto91** [comment]
@Vogelchevalier @yCatDev @AizerMortenort Friendly necro ping. Do you still have issues with latest dxvk? :slightly_smiling_face:

**Comment by laqyx** [comment]
bump, issue still exists
seems fixed in d9vk but its still present in DX11 titles
which games are affected seems random, Apex works fine while im forced to either use borderless or DX9 mode in League of Legends.

**Comment by Blisto91** [comment]
@laqyx Do you know of any d3d9 games with alt tab issues or do you only experience it in d3d11?

**Comment by Blisto91** [comment]
With https://github.com/doitsujin/dxvk/pull/2675 merged this Final Fantasy (and likely other games) should behave better
