### ISSUE TITLE
Ni No Kuni Remastered doesn't save game progress

### ISSUE THREAD

**Issue by ChazyTheBest** [doitsujin/dxvk#1213]
When I try to save the game progress nothing happens.

I start the game from a bash terminal so I can see the following lines when I press enter to save:

> searchSaveData Time: 0
> 002a:fixme:thread:RtlCreateUserThread stack_commit != 0 is unimplemented

That's the only log with `DXVK_LOG_LEVEL=debug`

### Software information
Ni No Kuni Remastered, default settings (max).

### System information
- GPU: AMD RADV POLARIS10 (LLVM 8.0.1) (Radeon RX 480 8GB)
- Driver: 19.2.0
- Wine version: wine-staging-4.16-1
- DXVK version: 1.4.1

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log: [NinoKuni_WotWW_Remastered_d3d11.log](https://github.com/doitsujin/dxvk/files/3687266/NinoKuni_WotWW_Remastered_d3d11.log)
- dxgi.log: [NinoKuni_WotWW_Remastered_dxgi.log](https://github.com/doitsujin/dxvk/files/3687267/NinoKuni_WotWW_Remastered_dxgi.log)

**Comment by lieff** [comment]
I do not think it's dxvk issue. More likely ntfs-with-wine issue. Game on NTFS drive? I have it on ext4 drive and it saves progress fine.

**Comment by ChazyTheBest** [comment]
Yes I have the game on a NTFS partition. I'm gonna try mv/cp to a ext4 partition. Thanks.

**Comment by ChazyTheBest** [comment]
I just tried again from a ext4 partition and that doesn't seem to be the problem as I'm getting the exact same result. Maybe I'm missing some package.

I should probably close this since you confirmed it's not a dxvk issue.

**Comment by lieff** [comment]
Note that wine prefix also must be on ext4 partition (and better initially created on it).

**Comment by ChazyTheBest** [comment]
Yes, the wine prefix is in the wineuser home dir and it's ext4. If this is really a filesystem problem, then it must be one hell of a specific problem because every other game I have on the NTFS partition work perfectly.

**Comment by ionenwks** [comment]
Do have to ask "just in case", is this the legit bought version of the game? The group that released it is known to have save issues (_only_ under wine) for pretty much every newer games they put out for nearly a year now. Not that I've tried, I already played this game on PS3 long ago.

**Comment by K0bin** [comment]
Either way, this is not a DXVK issue.

**Comment by ChazyTheBest** [comment]
@ionenwks It's not the legit version. I wanted to try it first and make sure it works fine in Linux before getting it in steam. I didn't know cracked versions had problems saving only in wine? I tried the same game folder in Windows and it saves perfectly fine. I enjoyed the first hour so I guess I'll just buy it and hope the cracked version was really the problem.

@K0bin Yes, I'll close it now. Sorry.

**Comment by ionenwks** [comment]
@ChazyTheBest That explains it then, and it's really just that particular group, not a widespread problem. I wasn't sure if that problem was still around, but this is too much to be a coincidence so I guess it is. I've read they use something weird to obfuscate their binaries which Wine can't fully work with, while it is a Wine bug I don't think it's something anyone is in a hurry to fix since no software "normally" do this.
