### ISSUE TITLE
Battlefront 2 (2017) crashes to desktop on specific maps

### ISSUE THREAD

**Issue by ptkato** [doitsujin/dxvk#1214]
The game only crashes on specific maps, it seems to happen with 100% consistency on Capital Supremacy's Felucia, Kashyyyk and Genosis, the furtherest I could get into it was 5~10 seconds of the initial cinematic, if I join and it's in the middle of the match, it crashes when I pick a class and go to the pick a spawn screen. However, it doesn't crash in the ship phase, I can join the game then just fine, and it plays ok until it goes back to the ground phase, which is followed by a crash.

One thing about those maps is that I can play them if they're in Galactic Assault or Arcade.

### Software information
Battlefront 2, Origin version, all the video options set to low.

### System information
- GPU: RX 550
- Driver: Mesa ACO 19.3.0
- Wine version: Staging 4.14
- DXVK version: 1.4.1

### Apitrace file(s)
I couldn't generate an apitrace log of the crash because whenever I tried, the game couldn't connect to the servers and therefore I couldn't play Capital Supremacy at all. 

### Log files
- d3d11.log: [starwarsbattlefrontii_d3d11.log](https://github.com/doitsujin/dxvk/files/3688101/starwarsbattlefrontii_d3d11.log)
- dxgi.log: [starwarsbattlefrontii_dxgi.log](https://github.com/doitsujin/dxvk/files/3688105/starwarsbattlefrontii_dxgi.log)

**Comment by doitsujin** [comment]
> Driver: Mesa ACO 19.3.0
can you please try with LLVM?

**Comment by ptkato** [comment]
> > Driver: Mesa ACO 19.3.0
> 
> can you please test with LLVM?

It seems that the crashes are gone with LLVM, I can actually get into the match, but that's about it, the game is unplayable. Stutters all over the place, like I said [here](https://github.com/doitsujin/dxvk/issues/1177#issuecomment-526975398).

**Comment by doitsujin** [comment]
That's not really a bug, just what happens in shader-heavy games with LLVM. Anyway, please report this on the [ACO](https://github.com/daniel-schuermann/mesa/issues) bug tracker.
