### ISSUE TITLE
Dark Souls 3 Unable to minimize with ALT TAB

### ISSUE THREAD

**Issue by AizerMortenort** [doitsujin/dxvk#1217]
If i use dxvk with dark souls 3 i  can not minimize 

[DarkSoulsIII_d3d11.log](https://github.com/doitsujin/dxvk/files/3693713/DarkSoulsIII_d3d11.log)
[DarkSoulsIII_dxgi.log](https://github.com/doitsujin/dxvk/files/3693714/DarkSoulsIII_dxgi.log)

**Comment by doitsujin** [comment]
Duplicate of #1212

**Comment by AizerMortenort** [comment]
Dark souls 3 crashes when i change it windowed in order to mimimize . crash is random.
