### ISSUE TITLE
Assassin's Creed IV Black Flag - fog/blur effect glitches

### ISSUE THREAD

**Issue by lostinmymind** [doitsujin/dxvk#1220]
## Please describe your issue as accurately as possible.

Fog and blur effects are weirdly glitched, feeling like misplaced in some cases. Screenshots: https://imgur.com/a/c5w5Mm7 - these are only from the very beginning here but it appears later on in various moments in the game, mostly in stormy weather and in various cutscenes. Sorry for so few screenshots but I didn't have enough time to make screenshots now, I'll update with more screenshots if needed

### Software information
Name of the game - Assassin's Creed IV Black Flag
Settings used - maxed out

### System information
- GPU: Palit GeForce GTX 1060 Super JetStream
- Driver: 430.40, 435.21
- Wine version: 4.14, 4.17
- DXVK version: 1.41 (from D9VK 0.22)

### Apitrace file(s)
- ask me if needed, I'll make an apitrace when I have time

### Log files
- d3d11.log: https://pastebin.com/2vK7gUaw
- dxgi.log: https://pastebin.com/r9iSz8tf

**Comment by doitsujin** [comment]
So what exactly is wrong on those screenshots? I don't know where to look. Also, are you sure that whatever is wrong there isn't just a game bug?

I do need an apitrace to debug this.

**Comment by doitsujin** [comment]
Ok, I reinstalled the game and started a new game, and I **don't** see the issue on my AMD card.

**Comment by lostinmymind** [comment]
Well yes, the settings are all maxed out with HBAO+ high and soft shadows enabled, I'll make more screenshots and try changing settings when I get back home today, I'll also try to make an API trace but idk if it won't just crash without DXVK

**Comment by doitsujin** [comment]
Can you try disabling MSAA and see if that fixes it? If so, probably related to #1216

**Comment by lostinmymind** [comment]
Oh wow, sorry, I wasn't using PC for a few days, I'm sorry. But yeah! This fixed the issue. Thank you! Is it fixable by any means, or is MSAA overall a bit broken on Linux? Meanwhile I think the topic can be closed at this point :)

**Comment by doitsujin** [comment]
MSAA isn't broken on Linux, MSAA is broken in these games. They are doing things that *technically* aren't supposed to work in D3D11 (but do so anyway because vendors implemented workarounds).

Unfortunately, working around this particular type of game bug isn't really possible in DXVK.
