### ISSUE TITLE
In game Hud Apps impact on Performance on Assetto Corsa

### ISSUE THREAD

**Issue by leillo1975** [doitsujin/dxvk#1221]
Performance in Assetto Corsa is great, but if you add some apps to the hud, the performance of the game decreases a lot, even making the game unplayable. In Windows the performance decreases much less when we use these utilities. These apps are really useful because they show interesting information about our driving. Take a look to this video:
https://youtu.be/pn8MsPUAcGA

I don't know if this problem is related to DXVK. If it's not, I apologize

### Software information
Assetto Corsa with medium settings

### System information
- GPU: NVIDIA Geforce GTX-1060-6GB
- Driver: 430.50
- Wine version: tkg-4.0
- DXVK version: 1.4.2

**Comment by K0bin** [comment]
Please make an apitrace of the game with and without Hud apps.

**Comment by leillo1975** [comment]
I don't have idea how to make an apitrace

**Comment by K0bin** [comment]
https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace

Follow this guide but don't use `d3d9.dll`. Copy the files `d3d11.dll`, `dxgi.dll` and `dxgitrace.dll` instead.

**Comment by leillo1975** [comment]
I only have a black screen with the fps counter

**Comment by doitsujin** [comment]
Can you please check if the same performance hit occurs when using DXVK on Windows? If not, it's not my issue.

More data would also be nice, such as whether you are GPU-bound or CPU bound.

**Comment by leillo1975** [comment]
I tried the game in Windows. Using the files d3d11.dll, dxgi.dll and dxgitrace.dll, the performance is much lower (around 30-50 fps) that using DX11 (around 150-200fps). With DXVK, if I use HUD apps the total performance is -30%. In linux this impact is more higher, but FPS without hud apps is very superior.

**Comment by K0bin** [comment]
So, does the HUD also tank the FPS with Windows d3d11 in a similar fashion (without any dlls)?
If you used d3d11.dll, dxgi.dll and dxgitrace.dll there's probably an apitrace file on your desktop now.

**Comment by leillo1975** [comment]
This is the Windows apitrace, but it corresponds to tests done by removing and putting the hud on screen:
https://mega.nz/#!NUIFiCZK!53Y_GyunD9ObI8Zu5zzbwnAQCvJUWHpuYpvzW1lmrd0
I don´t have more time for today, but tomorrow I would make more Windows apitraces with hud and without hud.

**Comment by leillo1975** [comment]
I found this modified Proton version: Proton-GE, that includes a patch for HUD in Assetto Corsa:
https://github.com/GloriousEggroll/proton-ge-custom
I couldn't test it , but I think that the patch for this issue is the following:
https://github.com/GloriousEggroll/proton-ge-custom/blob/proton-ge-4.16/game-patches-testing/wine-patches/winevulkan-childwindow.patch
I don't know if this helps you for something.
Cheers

**Comment by simon50keda** [comment]
I'm gonna try proton-ge today myself to see if it's fixed.

**Comment by leillo1975** [comment]
I know that Proton/Wine-TKG has an option to activate this fix:
https://github.com/Tk-Glitch/PKGBUILDS/tree/master/wine-tkg-git
You can activate on “customization.cfg” on Wine-TKG to avoid this (`# Fix for Assetto Corsa performance drop when HUD elements are displayed - https://bugs.winehq.org/show_bug.cgi?id=46955 _assettocorsa_hudperf_fix="true"` ).

Greetings

**Comment by simon50keda** [comment]
Argh... can't build my own wine properly having issue in multi arch setup :/
Does any of lutris runners have this patch applied?

**Comment by leillo1975** [comment]
I make a petition yesterday on [Lutris forums](https://forums.lutris.net/t/please-include-a-wine-tkg-with-assetto-corsa-fix-activated/8108) and on [Discord](https://discord.gg/a4fpMwR), but I don't have response

**Comment by Furious7c8** [comment]
I have checked this issue on windows and I have observed no impact of the user interface on the performance. 
https://steamuserimages-a.akamaihd.net/ugc/1041968184929623200/E4C920D57756F3250AAF13F5A8258193FFC2B4A5/
https://steamuserimages-a.akamaihd.net/ugc/1041968184929623643/130B90C244CC8C6C96B4A3194A4124EE9FF26F0D/
I think this issue should be closed.

**Comment by Blisto91** [comment]
I have not been able to get this game to work yet, so haven't been able to test. But a wine bug relating specifically to this issue it seems got created the same year as this issue and got fixed mid 2020
https://bugs.winehq.org/show_bug.cgi?id=46955

**Comment by Blisto91** [comment]
@leillo1975 Friendly ping
