### ISSUE TITLE
Vsync does not work while using PRIME Render offloading optimus NVIDIA GPU

### ISSUE THREAD

**Issue by DOGGO20** [doitsujin/dxvk#1222]
This issue seems to only affect DXVK/D9VK. Every other non DXVK game that I have tried, including native Vulkan Vsync works. I can provide logs and screenshots if necessary.

**Comment by doitsujin** [comment]
If vsync doesn't work, it's a driver issue, plain and simple. There's nothing more I can do than use `VK_PRESENT_MODE_FIFO`, and DXVK does that.

**Comment by DOGGO20** [comment]
well, no point in leaving this open then.
