### ISSUE TITLE
Question: retrieve framerate externally

### ISSUE THREAD

**Issue by DjebbZ** [doitsujin/dxvk#1223]
Hello,

I'd like to benchmark/fine tune my machine and was wondering if it's possible to retrieve the framerate (what DXVK_HUD=fps displays) from an external program while a game is running. Maybe written to a file ? To some Unix pipe ? Anything. I'd rather have the fps as data in real time rather than just observing the fps HUD with my eyes.

Thanks in advance!

**Comment by Joshua-Ashton** [comment]
This isn't what the DXVK HUD is intended for, and is very feature creepy.

There are probably some Vulkan layers out there that can do what you want.

**Comment by DjebbZ** [comment]
I know the dxvk_hud is just a graphical overlay. I was just wondering if
the framerate was accessible in another way. If not that's okay.

What do you mean other vulkan layers ? Are there other ways to translate
DirectX to Vulkan in wine?

**Comment by DjebbZ** [comment]
Or other applications that I could use to execute benchmarks?

**Comment by Oschowa** [comment]
You can use the Mesa vulkan overlay to log statistics to a file. (Yes, it also works with nvidia or any other vulkan driver)
https://gitlab.freedesktop.org/mesa/mesa/tree/master/src/vulkan/overlay-layer

**Comment by K0bin** [comment]
> What do you mean other vulkan layers ? Are there other ways to translate
DirectX to Vulkan in wine?

Vulkan has a system called layers that allows for hooking Vulkan function calls. It can be used to build a HUD similar to the DXVK hud or something like RivaTuner on Windows. It's also what the Mesa Vulkan Overlay uses which is why that also works with Nvidia drivers. This has nothing to do with Wine or Direct3D.

**Comment by DjebbZ** [comment]
Your answers are deeply appreciated since I'm no 3d/gfx/c/c++ dev at all. If understand correctly, after installing mesa-overlay, and given a working installation of wine and dxvk I can run something like

```
VK_INSTANCE_LAYERS=VK_LAYER_MESA_overlay VK_LAYER_MESA_OVERLAY_CONFIG=fps,output_file=/path/to/file wine witcher3.exe
```

And get the framerate written to the file?

**Comment by Oschowa** [comment]
Yes, that should work.

**Comment by DjebbZ** [comment]
Can't wait to test! Will report here (just need to to understand how to use
meson to build mesa-overlay since there's no package for my distribution
(Arch)...)

**Comment by Oschowa** [comment]
There actually is a Arch package: https://www.archlinux.org/packages/extra/x86_64/vulkan-mesa-layer/

**Comment by DjebbZ** [comment]
I saw this package but since it's not named "mesa-overlay" I thought it was
something else. I hope to find time to test this today.

**Comment by Guy1524** [comment]
Another solution would be to parse the output of +fps

**Comment by DjebbZ** [comment]
I'm happy to report that the command I wrote above works perfectly :) Thank you guys you rock.

Can I ask you about the file format? It looks like (truncated and added some comments)

``` text
> head code/etc/dxvk-fps/fps.txt
fps, frame_timing(us)
0.57, 3522743
# game menu, extremely high fps but doesn't matter
1340.50, 500559
1499.53, 500158
1448.54, 500503
# ... more of them
# loading screen, doesn't matter too
32.01, 531114
32.11, 529402
32.18, 528306
# ... more of them
# in-game data
61.45, 504513
60.82, 509711
61.53, 503853
```

I perfectly understand the 1st column it's the framerate, but what exactly is this frame_timing (us)? It doesn't look like the time it took to render the frame, because for 60fps each frame would be approximately 16.6ms, i.e. 16666 micro-seconds.

**Comment by Oschowa** [comment]
Looks like the second value is the fps sampling period (0,5s) and not the frametime.

**Comment by DjebbZ** [comment]
Makes sense, it's always the same value for all lines (approximately half a
second).

Thanks everyone, your support is awesome, keep up the good work with dxvk
and long live open source!
