### ISSUE TITLE
Bioshock Remastered 1/2/Infinite have totally messed up graphics

### ISSUE THREAD

**Issue by mmmaisel** [doitsujin/dxvk#1224]
Bioshock Remastered has totally messed up graphics during intro and in main menu with DXVK
both RADV and AMDVLK drivers (see screenshot). Without DXVK the game works well.
Other DXVK games and native vulkan games work perfectly.

This problem affects the whole Bioshock series.

![alt text](https://github.com/mmmaisel/_log/raw/master/bioshock-messed-up-main-menu.png "Messed up main menu")

### Software information
Installed Bioshock Remastered from GOG and started the game with default settings.

### System information
- GPU: RX 5700 XT
- Driver: Mesa 19.2 - RADV
- Wine version: 4.17 staging
- DXVK version: 1.4.2

### Apitrace file(s)
[Apitrace](https://github.com/mmmaisel/_log/raw/master/BioshockHD.trace)

### Log files
[d3d11.log](https://github.com/mmmaisel/_log/raw/master/Bioshockhd_d3d11.log)

[dxgi.log](https://github.com/mmmaisel/_log/raw/master/Bioshockhd_dxgi.log)

**Comment by Oschowa** [comment]
> GPU: RX 5700 XT
Very likely a driver bug, even if it happens on both radv and amdvlk, since they use more or less the same compiler backend. AFAIK these games are known to work fine on other GPU's.

**Comment by doitsujin** [comment]
Indeed, it works fine on my RX 480. Can you try running the game with `RADV_DEBUG=nodcc`?

That said, there seems to be a bug in my swap chain code somewhere, but that will not affect the game, only apitrace.

**Comment by hakzsam** [comment]
It works fine on my Radeon RX 5700 as well. Are you sure you are using RADV (DXVK HUD might help) ? FWIW, AMDVLK used to render something similar on Navi in the past, I have never been able to reproduce something like that with RADV.

**Comment by mmmaisel** [comment]
After clearing all shader caches the game works if I start it explicitly with RADV.
Looks like somehow it started with AMDVLK by default.
