### ISSUE TITLE
any chance to make GW2Taco overlay to work with Guild Wars 2?

### ISSUE THREAD

**Issue by logan001** [doitsujin/dxvk#1225]
There is this nice [GW2Taco](http://www.gw2taco.com/) overlay (32 bits dx11) that should stay on top of Guild Wars 2 (64bits dx9)window. the problems are that overlay window is not transparent. its background is black and is almost always in the background instead on top of GW2 window
these might be a wine problem cause it does the same things on wine without dxvk/d9vk also.

**Comment by doitsujin** [comment]
Probably not. I don't know how that thing works, but multiple Vulkan swap chains on the same window aren't supported, and even if it doesn't need that, I'm not sure how good wine's support for transparent windows is.

**Comment by logan001** [comment]
[Here](https://drive.google.com/open?id=0B21AKedF-JpVb2lHdEtLSWY4a2c) is a trace from GW2Taco. I've took it from windows.

**Comment by Joshua-Ashton** [comment]
The trace is just entirely black for me upon playback.

@doitsujin It's very possible that the transparency it is using is not done through DXGI also -- it could be done through some DWM api call or a combination of the two.

**Comment by logan001** [comment]
im not into programming so i'll guess that its not doable :)

**Comment by Joshua-Ashton** [comment]
The real question would be, does GW2Taco work with DXVK and D9VK together on Windows?

**Comment by logan001** [comment]
yes its working, i can see different fps overlapping each other (mostly the decimals)

**Comment by Joshua-Ashton** [comment]
Please file a bug report at https://bugs.winehq.org/ then.

**Comment by alextpedro** [comment]
It has been reported here: https://bugs.winehq.org/show_bug.cgi?id=48649

**Comment by anolting** [comment]
Hi
is there chance to get this issue reopened again? The programmer of TACO has open sourced is code in this repository  https://github.com/BoyC/GW2TacO.
From the error log wine and TACO writes I can see, that d3d11 swap chain is used while TACo is trying to hook into a running GW2.exe instance to use GW2 internal render engine to paint the additional information TACO can add to the game.
Best Alex

**Comment by K0bin** [comment]
Ask the author of the overlay to support specifying a path to the d3d11 and dxgi dlls it uses internally.

**Comment by anolting** [comment]
Hi @K0bin 
it seems that BoyC had some conversation long time in the past with the wine project were the discussion were around (not sure who asked who) adding support for window overlay into wine.
TacO is not an addon it is its own application looking for a GW2 window and trying to overlay the game window while letting user interactions passing through the overlay window down to the game instance.
With this knowledge it looks that this support should  be added within wine instead of dxvk.
Thanks for the food for thought.
Alex
