### ISSUE TITLE
Forcing anti-aliasing

### ISSUE THREAD

**Issue by BigFatHairyGamer** [doitsujin/dxvk#1229]
Some drivers like AMD Radeon allow us to "force anti-aliasing" in the driver settings across DirectX 9, 10 and 11 games (maybe in Vulcan or Direct 12 but I have not tested those as I do not own any.)

![image](https://user-images.githubusercontent.com/56777037/67155017-26ea1200-f2fe-11e9-9118-ed0a88be5028.png)

Would it be possible for similar to be done when in using DXVK maybe as a config option?
Because some games don't support it in the options or don't do it for cameras in the game, so it would be nice to have.

The driver for AMD and Nvidia can do it, so maybe DXVK can...! Or does it need to be lower level...?
You tell me! 🐻 

Thank you for your time! This feature would be greatly appreciated. 😺

**Comment by doitsujin** [comment]
The option in the AMD control panel doesn't let you enable AA, it lets you switch between regular multisampling and supersampling. This could be done, but a) most D3D10/11 games don't support MSAA to begin with (which is a requirement for this to work) and b) the only thing this would really do in the end is murder performance for almost no visual gain.

So, no, not going to implement it.
