### ISSUE TITLE
4K terrible FPS (any non-native game)

### ISSUE THREAD

**Issue by arrwdodger** [doitsujin/dxvk#1230]
Intel i7 8700k
16GB
Nvidia GeForce GTX 1070
Ubuntu 19.10 (also happened on 18.04)
Title. Specifically games running @ 4K resolution get around 10 - 20 fps. Every game I have played (non-native) had this issue. GTA V, UNDEFEATED, The Witness, The Forest. Diagnosing with Xserver reveals that during runtime my GPU reaches 100% ram usage. Ram usage remains unchanged regardless of resolution but performance does improve (somehow?). Someone on reddit mentioned it could be this (https://github.com/doitsujin/dxvk/issues/1100) problem but I haven't crashed yet.

**Comment by Joshua-Ashton** [comment]
Logs would be a good start here.

**Comment by tgharib** [comment]
If this is by design/intentional (since proton/dxvk uses more RAM), then maybe this should be in a  FAQ somewhere

**Comment by K0bin** [comment]
> my GPU reaches 100% ram usage

So you're talking about **V**RAM? DXVK is pretty bad at resource management on Nvidia gpus. Performance is expected to be much worse when you're running out of VRAM.
But I wouldn't really expect the games you listed to use more than 8GB of VRAM. That doesn't seem right.

**Comment by doitsujin** [comment]
4K performance on a GPU that clearly isn't capable of delivering a playable 4K performance on Windows is not a bug.
