### ISSUE TITLE
Borderlands 3 ~ 900p Fullscreen resolution issue

### ISSUE THREAD

**Issue by Niroc** [doitsujin/dxvk#1231]
Hi,
First, The game does run brilliantly... Sadly though, when fullscreen I'm unable to use 1600x900 resolution. I'll bullet point what happens.

~ when trying to apply this resolution, my physical screen (not the game) displays the message "Unsupported Signal" 
![20191022_162625](https://user-images.githubusercontent.com/12100786/67302759-498c4e80-f4e9-11e9-8d06-8823037c3db7.jpg)

~ my screen defaults internally to 1080p but displays the game in 900p with black border padding

~ when try to swap to another resolution, the game won't let me. I have to set the game to windowed (with borders) then, go back to fullscreen in order to get the game to go into another resolution

900p does work on this screen, I use it on many other titles. Also, I have attached the D3D logs below.

### Software information
~ Lutris patched wine - lutris-wf-nofshack-1.45-x86_64
~ Custom Media Foundation Platform patches to the wine prefix (https://www.thelinuxexp.com/post/borderlands-3-on-linux-it-kinda-works-how-to-step-by-step-guide)
~ Borderlands 3, very low gfx preset

### System information
- GPU: GTX 870m 
- Driver: 430.40
- Wine version: 4.15 (lutris-wf-nofshack-1.45-x86_64)
- DXVK version: 1.4.3

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
[Borderlands3_d3d11.log](https://github.com/doitsujin/dxvk/files/3756624/Borderlands3_d3d11.log)

- dxgi.log:
[Borderlands3_dxgi.log](https://github.com/doitsujin/dxvk/files/3756626/Borderlands3_dxgi.log)

**Comment by doitsujin** [comment]
Does this work if you use wined3d?

**Comment by Joshua-Ashton** [comment]
I also noticed you aren't using FSHack, does anything change if you enable/use that?

**Comment by doitsujin** [comment]
Please don't use fshack as it might mask the problem. I **really** want to know if this is my bug or not.

**Comment by Joshua-Ashton** [comment]
Fair enough

**Comment by Niroc** [comment]
I'm very sorry but, I can't test right now. (also, I'm not sure fs hack is)

**Comment by Niroc** [comment]
so, I won't be able to test it today due to denuvo ~ https://support.codefusion.technology/b3_da2dsa23/?e=88500006&l=english

All I did was change some audio hardware options and now I'm getting the error you receive when it thinks you're trying to run to the game on a new pc.

**Comment by Niroc** [comment]
I've done some testing...

Wined3d ~ Plays Borderlands 3 intro videos but, crashes whilst trying to get to the main menu. 

DXVK (install --without-dxgi) ~ Borks the to prefix preventing the Epic Game Store from launching so, I can't start Borderlands...

Returning to the normal DXVK 1.4.3 install restores the functionality I had at the beginning.

**Comment by doitsujin** [comment]
Can you try setting `dxgi` to `builtin` in your Wine prefix *only* for Borderlands3.exe? That way it shouldn't break EGS.

Just to make double-sure, since quite a few users aren't aware that this functionality exists, this is what it would look like: 
![Bildschirmfoto-1016](https://user-images.githubusercontent.com/25567304/67441264-77ae8300-f5fc-11e9-8bd5-b66cc8527b0c.png)
![Bildschirmfoto-1017](https://user-images.githubusercontent.com/25567304/67441265-77ae8300-f5fc-11e9-9b57-b6fa7cebc95c.png)

**Comment by Niroc** [comment]
I've tried this and the outcome is the same.

**Comment by Niroc** [comment]
OK, it's the same outcome. Maybe it's a Borderlands issue?

Also, I forgot to mention 720p does work.

**Comment by doitsujin** [comment]
Since you're on a laptop, are both displays active in some way?

I kind of suspect that this might be the good old wine multi-monitor issue (there's a reason why DXVK only supports one monitor...); it would report the same display modes for **both** your displays and obviously they won't be correct for one of them.

**Comment by Niroc** [comment]
The Laptop display is disabled in the /etc/X11/nvidia-xorg.conf.d/10-monitor.conf to prevent any performance degradation from screen mirroring so, that screen isn't visible to the rest of the system. (Also, the screen is broken)
![Screenshot_2019-10-24_01-56-24](https://user-images.githubusercontent.com/12100786/67444632-cf9bb880-f601-11e9-84d0-a4655c8883fe.png)

**Comment by Blisto91** [comment]
@Niroc If you are still around and able can you test if this is still an issue?
