### ISSUE TITLE
Surviving the Aftermath - Crashes in the Catastrophe "heat wave"

### ISSUE THREAD

**Issue by SebastianPQ** [doitsujin/dxvk#1234]
I run the game with the latest binaries , the game works but like Proton builds (4.11 and 3.x ) the game crashes the the catastrophe "heat wave" start , i don't know if is some issues with the game per se or is related with the shaders. 

### Software information
Surviving the Aftermath

### System information
- GPU: Nvidia 980 GT
- Driver: Nvidia 430.26
- Wine version: 4.15 staging
- DXVK version: latest - 1.4.3

### Apitrace file(s)
I can't generate the Apitrace, i don't know why but do not generate the file.

### Log files
- d3d11.log:[Aftermath64_d3d11.log](https://github.com/doitsujin/dxvk/files/3776235/Aftermath64_d3d11.log)
- dxgi.log:[Aftermath64_dxgi.log](https://github.com/doitsujin/dxvk/files/3776236/Aftermath64_dxgi.log)

**Comment by doitsujin** [comment]
```
info:    dxgi.deferSurfaceCreation = True
info:    d3d11.maxFeatureLevel = 11_0
```
Please **do not enable** random options if they aren't necessary, the first one could potentially be your problem.

Anyway, without further details I'm neither able nor willing to look further into this issue, there's no clear indication that this is even a DXVK bug and not a wine issue or even game bug. Please provide at least the full wine log.

**Comment by SebastianPQ** [comment]
Yes , sorry about those options , sometimes i test the game in dx10 if it can run, maybe is a game related bug.

**Comment by SebastianPQ** [comment]
> ```
> info:    dxgi.deferSurfaceCreation = True
> info:    d3d11.maxFeatureLevel = 11_0
> ```
> 
> Please **do not enable** random options if they aren't necessary, the first one could potentially be your problem.
> 
> Anyway, without further details I'm neither able nor willing to look further into this issue, there's no clear indication that this is even a DXVK bug and not a wine issue or even game bug. Please provide at least the full wine log.

Why apitrace dont work. it's not generate the trace file , something changed?

**Comment by K0bin** [comment]
The trace file should be in the desktop folder **inside** your wine prefix.

**Comment by SebastianPQ** [comment]
> The trace file should be in the desktop folder **inside** your wine prefix.
Ok , i fund it , in the docs says that is in the game.exe folder. 
I will upload the trace file later.

**Comment by SebastianPQ** [comment]
Sorry , i can't upload the apitrace , its 2.5gb ...

**Comment by doitsujin** [comment]
In that case there's nothing I can do.
