### ISSUE TITLE
S.T.A.L.K.E.R: Call of Pripyat black screen on start(DX11, DX10)

### ISSUE THREAD

**Issue by Gedeon300W** [doitsujin/dxvk#1236]
Software information

Game: STALKER: Call of Pripyat 1.6.0.2(GOG version)
Settings: Enhanced Dynamic Lightning (DX11) (renderer_r4)

System information

OS: OpenSUSE Tumbleweed
Driver mesa: 19.2.1
DXVK version: 1.4.4
GPU: Radeon RX Vega 64
Wine version: 4.18 staging

When trying to run CoP, the game start and show black screen. After intro begin playing music main menu, but screen stays black. On Enhanced Dynamic Lightning (DX10) (renderer_r3) similar results, on Enhanced Dynamic Lightning (DX9) (renderer_r2.5) game plays perfectly and smooth.

**Comment by doitsujin** [comment]
Known issue, install `d3dcompiler` libraries.
https://github.com/doitsujin/dxvk/issues/1143#issuecomment-514186037

**Comment by Gedeon300W** [comment]
I did it. Not stupid, all the instructions and cases not only looked at you, but everywhere on the Internet. Result similar.

**Comment by doitsujin** [comment]
Well, you didn't attach **any** logs or debug info, so I just guessed because that's the only thing I can do.

In any case, the games are known to be broken beyond belief and I don't intend to work around these issues, so you should play them in DX9 mode.

**Comment by Gedeon300W** [comment]
What kind of log do you need? Terminal output?

**Comment by doitsujin** [comment]
If you hadn't ignored the issue template, you'd know that.

But yes, wine terminal output and the `d3d11`/`dxgi` log files created by dxvk.

**Comment by Gedeon300W** [comment]
Sorry. At my first issue on github. I dont know about issue template.

**Comment by doitsujin** [comment]
*Probably* next to the game exe. If you can't find them, just post the terminal output.

**Comment by Gedeon300W** [comment]
Terminal output - https://pastebin.com/S7T9EyQx
xrEngine_d3d11.log  -  https://pastebin.com/9YbCB9nc
xrEngine_dxgi.log  -  https://pastebin.com/YDHdZpwk

**Comment by Gedeon300W** [comment]
If that matters. When the game starts, it first minimize to panel. When you try to expand, it opens in windowed mode and a black screen is already visible there.

**Comment by doitsujin** [comment]
Looks like this game also needs `d3dx11_43` or another one of the `d3dx_**` libraries.

**Comment by Gedeon300W** [comment]
The problem is that they are all installed and registered. Or maybe I doing something wrong?
[image](https://user-images.githubusercontent.com/10392010/68074837-213a0500-fdb1-11e9-9825-ff889dab1b6c.png)

**Comment by Gedeon300W** [comment]
https://github.com/ValveSoftware/Proton/issues/1174#issuecomment-418706266
