### ISSUE TITLE
Heroes of the Storm not showing Wall-Outlines

### ISSUE THREAD

**Issue by kuco87** [doitsujin/dxvk#1237]
The game is running really nicely, but one small detail is really annoying for certain heroes: The wall-outlines (white outlines showing the maps geometry) won't show. 

How to reproduce: Chose the heroe "hanzo" in the collection-tab. Click "try". 

Tried low and extreme graphics settings, no success. Tried mesa-git instead of mesa-aco, no success. Tried DXVK 1.3.4., no success.

How the walls should look for Hanzo:
https://www.youtube.com/watch?v=yz4hOxR_VyU#t=480

### System information
- GPU: RX-580
- Driver: tried mesa-git and mesa-aco (19.3)
- Wine version: tkg-4.6
- DXVK version: 1.4.4 and 1.3.4.

**Comment by doitsujin** [comment]
Can you please record an apitrace?

**Comment by kuco87** [comment]
Thanks for the fast answer. Will try to deliver apitrace. 
Yes, it's reproducable in 1 minute. Just start any map with "hanzo". You dont need to buy him for playing in try-mode. 

It may also be an aco-issue. While on mesa-git I used RADV_PERFTEST=aco. Will try to test it without that option.

**Comment by doitsujin** [comment]
Alright, I can reproduce the problem and I have an idea what it might be; I won't need an apitrace anymore (apparently it's not really possible to record one anyway, I tried).

**Comment by doitsujin** [comment]
Turns out that this is just a simple case of a library missing, `winetricks d3dx11_42` on your Lutris wine prefix should fix the problem:

![Bildschirmfoto-1038](https://user-images.githubusercontent.com/25567304/68077666-13dc4500-fdc8-11e9-9ce8-6e449de3d09d.png)

**Comment by kuco87** [comment]
Hi,

sorry, I couldn't reply ealier. Thank you for your help. Your work is
amazing.


Philip Rebohle <notifications@github.com> schrieb am Sa., 2. Nov. 2019,
23:26:
