### ISSUE TITLE
missing header? dxgi1_5.h

### ISSUE THREAD

**Issue by tco-ne** [doitsujin/dxvk#1239]
im trying to compile it for my system
nvidia: 1070 maxq 8gb
i7 2.2ghz
32ram
ssd

im gettin the folowing output i cant get my head around:

The Meson build system
Version: 0.51.2
Source dir: /home/tc/compiele/DXVK/comp_setup_07_11_2019/dxvk
Build dir: /home/tc/compiele/DXVK/comp_setup_07_11_2019/dxvk/build/dxvk-master/build.64
Build type: cross build
Project name: dxvk
Project version: v1.4.4
C compiler for the build machine: ccache cc (gcc 7.4.0 "cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
C++ compiler for the build machine: ccache c++ (gcc 7.4.0 "c++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
C compiler for the host machine: x86_64-w64-mingw32-gcc (gcc 7.3.0 "x86_64-w64-mingw32-gcc (GCC) 7.3-posix 20180312")
C++ compiler for the host machine: x86_64-w64-mingw32-g++ (gcc 7.3.0 "x86_64-w64-mingw32-g++ (GCC) 7.3-posix 20180312")
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Build machine cpu family: x86_64
Build machine cpu: x86_64
Checking if "winelib check" compiles: NO 
Program x86_64-w64-mingw32-windres found: YES (/usr/bin/x86_64-w64-mingw32-windres)
Library vulkan-1 found: YES
Library d3d11 found: YES
Library dxgi found: YES
Library d3dcompiler_43 found: YES
Library d3dcompiler_47 found: YES
Program glslangValidator found: YES (/usr/bin/glslangValidator)
Run-time dependency threads found: YES 
Dependency threads found: YES (cached)
Build targets in project: 11
Found ninja-1.8.2 at /usr/bin/ninja
[4/214] Compiling C++ object 'src/util/ed6d25d@@util@sta/com_com_guid.cpp.obj'.
FAILED: src/util/ed6d25d@@util@sta/com_com_guid.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/util/ed6d25d@@util@sta -Isrc/util -I../../../src/util -I../../.././include -fdiagnostics-color=always -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O3 -DNOMINMAX -MD -MQ 'src/util/ed6d25d@@util@sta/com_com_guid.cpp.obj' -MF 'src/util/ed6d25d@@util@sta/com_com_guid.cpp.obj.d' -o 'src/util/ed6d25d@@util@sta/com_com_guid.cpp.obj' -c ../../../src/util/com/com_guid.cpp
In file included from ../../../src/util/com/../../d3d11/../dxgi/../dxvk/../util/util_flags.h:5:0,
                 from ../../../src/util/com/../../d3d11/../dxgi/../dxvk/dxvk_include.h:8,
                 from ../../../src/util/com/../../d3d11/../dxgi/dxgi_interfaces.h:3,
                 from ../../../src/util/com/../../d3d11/d3d11_interfaces.h:3,
                 from ../../../src/util/com/com_guid.cpp:3:
../../../src/util/com/../../d3d11/../dxgi/../dxvk/../util/util_bit.h:102:0: warning: ignoring #pragma GCC unroll [-Wunknown-pragmas]
     #pragma GCC unroll 0
 
In file included from ../../../src/util/com/../../d3d11/../dxgi/dxgi_format.h:3:0,
                 from ../../../src/util/com/../../d3d11/../dxgi/dxgi_interfaces.h:5,
                 from ../../../src/util/com/../../d3d11/d3d11_interfaces.h:3,
                 from ../../../src/util/com/com_guid.cpp:3:
../../../src/util/com/../../d3d11/../dxgi/dxgi_include.h:30:10: fatal error: dxgi1_5.h: No such file or directory
 #include <dxgi1_5.h>
          ^~~~~~~~~~~
compilation terminated.
[12/214] Compiling C++ object 'src/spirv/e922df6@@spirv@sta/spirv_compression.cpp.obj'.
In file included from ../../../src/spirv/../util/util_flags.h:5:0,
                 from ../../../src/spirv/spirv_include.h:7,
                 from ../../../src/spirv/spirv_instruction.h:6,
                 from ../../../src/spirv/spirv_code_buffer.h:8,
                 from ../../../src/spirv/spirv_compression.h:5,
                 from ../../../src/spirv/spirv_compression.cpp:1:
../../../src/spirv/../util/util_bit.h:102:0: warning: ignoring #pragma GCC unroll [-Wunknown-pragmas]
     #pragma GCC unroll 0
 
[14/214] Compiling C++ object 'src/spirv/e922df6@@spirv@sta/spirv_code_buffer.cpp.obj'.
In file included from ../../../src/spirv/../util/util_flags.h:5:0,
                 from ../../../src/spirv/spirv_include.h:7,
                 from ../../../src/spirv/spirv_instruction.h:6,
                 from ../../../src/spirv/spirv_code_buffer.h:8,
                 from ../../../src/spirv/spirv_code_buffer.cpp:4:
../../../src/spirv/../util/util_bit.h:102:0: warning: ignoring #pragma GCC unroll [-Wunknown-pragmas]
     #pragma GCC unroll 0
 
[16/214] Compiling C++ object 'src/spirv/e922df6@@spirv@sta/spirv_module.cpp.obj'.
In file included from ../../../src/spirv/../util/util_flags.h:5:0,
                 from ../../../src/spirv/spirv_include.h:7,
                 from ../../../src/spirv/spirv_instruction.h:6,
                 from ../../../src/spirv/spirv_code_buffer.h:8,
                 from ../../../src/spirv/spirv_module.h:5,
                 from ../../../src/spirv/spirv_module.cpp:3:
../../../src/spirv/../util/util_bit.h:102:0: warning: ignoring #pragma GCC unroll [-Wunknown-pragmas]
     #pragma GCC unroll 0
 
[17/214] Compiling C++ object 'src/util/ed6d25d@@util@sta/config_config.cpp.obj'.
ninja: build stopped: subcommand failed.

**Comment by K0bin** [comment]
Your mingw-w64 is too old.

**Comment by doitsujin** [comment]
MinGW 6.0 is required to build.

**Comment by tco-ne** [comment]
there is no version for ubuntu :(

http://mingw-w64.org/doku.php/download

am i fucked or how can i get the 6.00 version for:
OS: Ubuntu 18.04 bionic
Kernel: x86_64 Linux 5.0.0-32-generic  ?

**Comment by K0bin** [comment]
https://launchpad.net/ubuntu/+source/mingw-w64
There are up to date versions for both 19.04 and 19.10. Just update your distro.

Apparently someone packaged up the newer version for18.04.
https://launchpad.net/~mati865/+archive/ubuntu/mingw-w64
