### ISSUE TITLE
Steam Overlay won't hook with DXVK in Windows

### ISSUE THREAD

**Issue by DaRkL3AD3R** [doitsujin/dxvk#1241]
When using DXVK (and D9VK), Steam Overlay will not hook to any game using the wrapper.

### System information
- GPU: 1080 Ti
- Driver: 441.12
- DXVK version: 1.4.4
- OS: Windows 10 1909 x64

**Comment by doitsujin** [comment]
Sounds more like a Steam Overlay issue than a DXVK issue to be honest. Even if it doesn't hook D3D11, it should at least enable its Vulkan layer.

In any case, there's nothing I can do here.
