### ISSUE TITLE
Earth Defense Force 4.1: Some HUD elements are not visible

### ISSUE THREAD

**Issue by junglerobba** [doitsujin/dxvk#1242]
As shown on the screenshots in https://github.com/ValveSoftware/Proton/issues/1193#issuecomment-541857399 since DXVK 1.4.0 some elements like the character model on the menu screen and HUD elements like the minimap and ammo counters are not visible anymore.
Apitrace was created on Windows but since the game was very slow I had to force quit it on the loading screen into the mission, the ingame UI was already visible at that point though, so I hope there's enough in there.

### Software information
Game: Earth Defense Force 4.1

### System information
- GPU: Vega 56
- Driver: Mesa 19.2.3
- Wine version: 4.11 (Proton)
- DXVK version: >= 1.4.0

### Apitrace file(s)
https://mega.nz/#!blFkRIgZ!Jr3HfTnrrdUfQtGctQgSHyXeizKnhoOyNMtbGxvwzWg

### Log files
- d3d11.log: 
[EDF41_d3d11.log](https://github.com/doitsujin/dxvk/files/3827358/EDF41_d3d11.log)

**Comment by doitsujin** [comment]
Replaying the trace looks like this for me, is there anything wrong here? Also, can you reproduce the problem when using DXVK on Windows or does this only happen on Proton?
![Bildschirmfoto-1053](https://user-images.githubusercontent.com/25567304/68530969-9eafc900-030d-11ea-97ed-3d03604fc526.png)

**Comment by junglerobba** [comment]
Your replay looks fine, on that screen the character model on the right would be missing.

I used 1.4.4 on Windows and aside from fullscreen being broken there were no issues, everything showed up correctly.

> Does this mean that 1.3.x works fine even with Proton 4.11?
Yes, I've been using Proton 4.11 for all this and just swapping out the dlls, all 1.3.x releases are fine, 1.4.0 is the first with the issue.

**Comment by doitsujin** [comment]
> I used 1.4.4 on Windows and aside from fullscreen being broken there were no issues, everything showed up correctly.

If that's the case, it's probably not a dxvk bug but some weirdness around mesa (or wine, but unlikely); can you test whether it works with amdvlk? If not, can you bisect which exact commit between 1.3.3 and 1.4 introduced the issue?

**Comment by junglerobba** [comment]
The issue still happens with both amdvlk and mesa-git with and without aco enabled.

> If not, can you bisect which exact commit between 1.3.3 and 1.4 introduced the issue?

Sure, if I did this correctly it seems to be fdf560150f820a0b6ec944b36d638ae9a9579653

**Comment by doitsujin** [comment]
I'll try to get my hands on the game and take a look next week.

**Comment by junglerobba** [comment]
All right, thanks!
Also sorry for reporting this on a weekend, I just finally had the time to look into this and record the apitrace today.

**Comment by doitsujin** [comment]
Turns out this was my bug after all, but the fact that it worked with 1.3.x was pure luck, the issue was present in older DXVK versions too.
