### ISSUE TITLE
GTX 970 memory allocation error on full memory usage.

### ISSUE THREAD

**Issue by MAD-BUG** [doitsujin/dxvk#1243]
Issue from the title happens in different games. I was able to recreate this issue in Arma 3, The Outer Worlds and Squad, but i think i can recreate this issue in every game that uses more than 4Gb of memory. First two of tested games i was able to run without crashes if texture settings was lowered to high or medium. Squad fills video memory instantly which causes crash on spawn in 80% of situations, but chances of crash can be lowered if "keep textures in memory" setting enabled.
I was not been able to find reports for such issues in tested games from other players except for those who have gtx 970. [Arma 3](https://github.com/ValveSoftware/Proton/issues/3004#issue-484666543), [Squad](https://www.protondb.com/app/393380#8jMXnZXfYI)
There is also Nvidia error in dmesg:
NVRM: Xid (PCI:0000:01:00): 31, pid=7425, Ch 00000033, intr 10000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_RAST faulted @ 0x0_00000000. Fault is of type FAULT_PDE ACCESS_TYPE_WRITE

### System information
- GPU: GTX 970
- Driver: from 430 to 435
- Wine version: from 3.16-9 (Proton) to 4.19-staging
- DXVK version: from 1.3.4 to 1.4.4

**Comment by doitsujin** [comment]
Known issue, not a DXVK bug, should already be fixed in the latest Vulkan beta driver. See #1100
