### ISSUE TITLE
Modded FFXIV d96c22b/0924bb4 regression

### ISSUE THREAD

**Issue by fosspill** [doitsujin/dxvk#1247]
Hi!
Certain mods for FFXIV crash with DXVK after commit d96c22b / 0924bb4.
Bisecting revealed this.

While I realize this is not an officially supported use case, it's still seems to be DXVK regression.

### Software information
Final Fantasy XIV - Modded

### System information
- GPU: Vega 56
- Driver: Mesa 20.0.0
- Wine version: 4.19
- DXVK version: After d96c22b / 0924bb4

### Apitrace file(s)
- Sadly, I still don't understand how to make apitraces of FFXIV. It just crashes my game directly. I did however bisect.

### Log files
- d3d11.log:  https://gist.github.com/fosspill/9abe500d3edd2368f1eb72864b3df9ff
- dxgi.log: https://gist.github.com/fosspill/9abe500d3edd2368f1eb72864b3df9ff

**Comment by doitsujin** [comment]
There might be a genuine issue, but it's impossible for me to debug this since mods break terms of service.

> It just crashes my game directly.

Did you copy the appropriate (64-bit) `dxgitrace.dll`, `dxgi.dll` and `d3d11.dll` to the `game` directory? If so, and if that doesn't work, there's not much you can do.

**Comment by fosspill** [comment]
So, this is interesting @doitsujin.

Still trying to get a proper apitrace, but I have other - possibly related - news.
After commit dbc14fe it now _seems_ to be working fine, again.

 I'll be testing a bit more and get an apitrace if it's not resolved.

**Comment by fosspill** [comment]
Alright, after multiple compilations and testing it seems like dbc14fe65cf36e2258361aa8c25e6219ebff76ad is the one that fixed the issue.

Somehow the game needs to be started twice (only the first time) before functioning properly after crashing with an earlier build.

**Comment by doitsujin** [comment]
Well that's weird. Are you building with `-march=native` by any chance, or any additional optimizations?

None of these commits should affect correctness on x86, although a6483e02fe28b5472b237e6fe80fd9226da05378 fixes a potential performance problem.

**Comment by fosspill** [comment]
Just `meson --cross-file build-win64.txt --buildtype release`. 
Would a apitrace still be wanted even though it seems fixed as of dbc14fe?

**Comment by doitsujin** [comment]
if it's possible to provide one, sure, if not, then.. well, it wouldn't work anyway.
