### ISSUE TITLE
Instant Crashes in Warcraft III Reforged 

### ISSUE THREAD

**Issue by BaDitO2** [doitsujin/dxvk#1252]
Hello, 

Warcraft 3 Reforged crashes instantly, as well as the Reforged World editor
 errors in d3d11.log
err:   DxgiSwapChain::GetFrameLatencyWaitableObject: Not implemented
err:   DxgiSwapChain::SetMaximumFrameLatency: Not implemented

### Software information
Warcraft 3 Reforged Beta
Build: 1.32.0.13769

### System information
- GPU: RX480 8GB
- Driver:  AMDGPU 19.0.8
- Wine version:  4.13 staging
- DXVK version: 1.4.5

### Apitrace file(s)
- Put a link here
*edit* wasn't able to do a sucessfull apitrace yet, since the Reforged beta can be only launched via the Battle.net Launcher, and apitrace did only trace the bnet launcher itself. 
*edit* apitrace in my second reponse

### Log files
- d3d11.log: 
[Warcraft III_d3d11.log](https://github.com/doitsujin/dxvk/files/3883960/Warcraft.III_d3d11.log)

- dxgi.log:

[Warcraft III_dxgi.log](https://github.com/doitsujin/dxvk/files/3883961/Warcraft.III_dxgi.log)

*edit* same issue as here
https://forums.lutris.net/t/warcraft-iii-reforged-last-patch-broke-it-anyone-been-able-to-fix-it/7629

**Comment by doitsujin** [comment]
Did this game stop supporting Windows 7 or add D3D12 support or something?

I guess it's *possible* to implement the functions in question (although it's going to be a royal pain in the arse), but it would be weird for a D3D11 game to use these. They are really intended for D3D12.

**Comment by BaDitO2** [comment]
Can't say much about the intentions of the Blizzard Game devs, all I can say  the beta  also crashes instantly on win7 and win8.1. 

Thanks for the tip  I will update with a apitrace as soon as I get to it.

**Comment by doitsujin** [comment]
Do note that I will need an apitrace recorded on Windows; not a DXVK one. wined3d will also most likely not work.

**Comment by BaDitO2** [comment]
Apitrace made on my windows 8.1 machine

[Warcraft_III_apitrace.zip](https://github.com/doitsujin/dxvk/files/3884120/Warcraft_III_apitrace.zip)

**Comment by doitsujin** [comment]
Yeah that unfortunately isn't very useful either since it fails to create the swap chain on Windows 8.1 and then probably just crashes. Do you have access to a Windows 10 machine?

**Comment by BaDitO2** [comment]
That's useful information for me tho, since as far as I know Blizzard intends on keeping Reforged playable in windows 8.1, so in the end of he day it might not be a job for you guys, but Blizzard's job in fixing windows 8.1 compatibility of Warcraft 3 Reforged. 
I will redirect this to the War3 dev team thanks :)

**Comment by doitsujin** [comment]
Well the main problem is that DXVK exposes DXGI 1.5, so the game can **expect** the missing functionality to be present and we'll have to implement it. I just don't have a test case (I can write one, but that won't show me how this API is actually used by real-world applications, and as far as I know it's the only D3D11 game which needs these).

**Comment by BaDitO2** [comment]
okay. I will upload a Windows 10 apitrace tomorrow (Don't have a single one at home, but I got access to them at work).

**Comment by BaDitO2** [comment]
Hello, 

here is the win10 apitrace (I just launched the game entered the main menu and exited again, since the GPU of the win10 machine is really bad, and I doubt it would run a match of Warcraft 3 Reforged without crash)
But I hope it will help you

Even then the APItrace is 500 MB big in a zipped file, and github would not allow this to be uploaded directly, so I had to share it via my public Gdrive: filename "war3_apitrace_win10.zip"

https://drive.google.com/open?id=1bjCsdzYZ3X1_WDTgzNxIXjpbhUthFxyC

**Comment by doitsujin** [comment]
Thanks, this contains the relevant API calls and is quite helpful indeed.

**Comment by doitsujin** [comment]
Could you check if it works with the [dxgi-frame-latency](https://github.com/doitsujin/dxvk/tree/dxgi-frame-latency) branch? It's more or less untested right now (will do that soon) but it implements the missing functions.

**Comment by BaDitO2** [comment]
> Could you check if it works with the [dxgi-frame-latency](https://github.com/doitsujin/dxvk/tree/dxgi-frame-latency) branch? It's more or less untested right now (will do that soon) but it implements the missing functions.

It works with the dxgi-frame-latency build perfectly <3

**Comment by doitsujin** [comment]
Thanks for the feedback; I fixed a few issues and merged it.

Feel free to reopen if for some reason it broke on the `master` branch.
