### ISSUE TITLE
GTA 5 screen nearly completely white in addition to lag.

### ISSUE THREAD

**Issue by Slyfox88** [doitsujin/dxvk#1258]
In addition to Grand Theft Auto V being nearly completely white while playing I had poor relative performance given my GPU and keyboard input lag while playing.

OS: Ubuntu 19.10
KERNEL: 5.3.0-23-generic
CPU: AMD Ryzen 5 2600X Six-Core
GPU: Radeon RX Vega
GPU DRIVER: 4.5 Mesa 19.2.1
RAM: 16 GB
Wine version: 4.20 & staging 4.20
DXVK version: 1.4.5

![GTA5s](https://user-images.githubusercontent.com/58151689/69741444-0b4a0680-1109-11ea-8abc-3c6b3f505754.png)

**Comment by doitsujin** [comment]
This is an ACO bug, not a DXVK bug.

**Comment by doitsujin** [comment]
Should be fixed upstream.
