### ISSUE TITLE
Quake Champions sometimes looks like I have a wallhack

### ISSUE THREAD

**Issue by b4raba** [doitsujin/dxvk#1261]
### Software information
Quake Champions. Graphics settings low, vsync off.

### System information
- GPU: GTX 1070
- Driver: nvidia 440.36
- Wine version: wine-4.20
- DXVK version: 1.4.5 (dxvk-bin from Arch aur) installed but DXVK-HUD reports v1.2.1-6-G894515f6

### Apitrace file(s)
/

### Log files
/
![2019-11-28-223620_1920x1080_scrot](https://user-images.githubusercontent.com/1312349/69884347-464e6480-12d8-11ea-8394-f4400c27f55c.png)

**Comment by K0bin** [comment]
Please use the official builds (as opposed to the AUR one) to make sure you're actually using the latest version.

**Comment by tgharib** [comment]
>DXVK-HUD reports v1.2.1-6-G894515f6

It sounds like there is something wrong with your DXVK installation if DXVK-HUD reports such an old version.

**Comment by doitsujin** [comment]
> G894515f6

FWIW this commit does not even exist in my repository. I don't know which DXVK you're using, but it's **definitely** nothing official, please sort that out first.

**Comment by b4raba** [comment]
> FWIW this commit does not even exist in my repository. I don't know which DXVK you're using, but it's **definitely** not 1.4.5, please sort that out first.

I compiled from master and DXVK_HUD still reports 1.2.1-6-g894515f6. Is it possible steamplay is forcing this version?

**Comment by doitsujin** [comment]
The latest version fo Proton (4.11-9) ships DXVK 1.4.4, so if this is a Proton build, you're likely using something older than that.

**Comment by b4raba** [comment]
OK thanks,  I'll close this since it looks like I've got issues elsewhere.
