### ISSUE TITLE
Star Citizen  dark textures

### ISSUE THREAD

**Issue by gort818** [doitsujin/dxvk#1262]
Looks there there was a bad commit between dxvk 4.2 and 4.3

Textures on some surfaces are complete black.
Here are some screenshots.
#### 4.2

![sc_dxxk4 2-1](https://user-images.githubusercontent.com/9098121/69893750-f321e500-12ca-11ea-82b9-93300312504c.png)

#### 4.3-4.5

![sc_dxvk4 3-1](https://user-images.githubusercontent.com/9098121/69893756-09c83c00-12cb-11ea-89dd-5615d8ca1a66.png)

### Software information
Star Citizen live 3.7.2

### System information
- GPU: Vega 56
- Driver: mesa-aco-git 20.0.0_devel.20191126.6df53a980c0
- Wine version: 4.20 staging
- DXVK version: 4.3-4.5

### Log files
- d3d11.log: https://gist.github.com/gort818/d889fdf817769b34b152ea90fbb414f3
- dxgi.log: https://gist.github.com/gort818/7815c20d73b94581d0e17f2ec72868f1

### Git bisect
Ok performed a bisect
first bad commit: [102a18060e6f474cd25e91c670edd4729df4d50c] [d3d11] Don't spill render pass when rebinding render targets

1. DXVK: v1.4.2-36-gc5676d31 -good
2. DXVK: v1.4.2-54-g9c6209fb -bad
3. DXVK: v1.4.2-45-g950ea21b -bad
4. DXVK: v1.4.2-40-g8446c28d -bad
5. DXVK: v1.4.2-38-g43600215 -good
6. DXVK: v1.4.2-39-g102a1806 -bad

**Comment by doitsujin** [comment]
I need an apitrace to debug this, the bisect alone doesn't tell me why it is wong.

**Comment by gort818** [comment]
Trying to get an apitrace takes over twenty minutes just to load into the game and then crashes, apitrace: warning: caught exception 0xc0000005.

I will keep trying.

**Comment by gort818** [comment]
Here is trace not sure how much it captured as it crashed very early on.
https://drive.google.com/open?id=17TEr0fwws5ZzWotlBwQHfDv6Z6vWd4Ip

**Comment by doitsujin** [comment]
Unfortunately it only shows the main menu (which seems fine) and loading screens, not very useful to debug the problem.

**Comment by gort818** [comment]
Damn ok, we will get you a trace where the bug is present.

**Comment by Alnoroid** [comment]
To get rid of dark texture bug - just copy and replace your d3dcompiler_47.dll from RSI Launcher directory to StarCitizen/LIVE and remove USER/Shaders.

**Comment by gort818** [comment]
@Alnoroid that is a different issue which has nothing to do with dxvk.

**Comment by beniwtv** [comment]
I hope this new trace now can reproduce the issue for you guys:
https://drive.google.com/open?id=1AlRGX5f901ysv8wymtrn29hxpx-h3c71

**Comment by K0bin** [comment]
I can replicate the issue with the trace and have bisected it down to 102a18060e6f474cd25e91c670edd4729df4d50c. To confirm it's actually that commit I also reverted it, which did indeed fix the issue as expected.

**Comment by doitsujin** [comment]
Thanks, the trace was very useful indeed. This should be fixed as of latest master. You can find a pre-compiled build [here](https://git.froggi.es/doitsujin/dxvk/-/jobs/1018/artifacts/download).

**Comment by gort818** [comment]
Awesome! Thank you so much, works great!
