### ISSUE TITLE
[bisected] discarded frames causing stuttery output on XWayland

### ISSUE THREAD

**Issue by aufkrawall** [doitsujin/dxvk#1263]
Since commit 69bad7bf8c01116981e40dd74e09f71e464e2097, frame output on XWayland looks like half of the frames (or more) are discarded. Enabling vsync seems to work around this, or switching into windowed mode. Tested with both Plasma and Sway.
Happens with and without DXVK dxgi and also specifying number of backbuffers to 3 doesn't help (I also tried with d3d11 prefix for the config variable).
With commit a0651392c4180aa37d9a7ad559180ef98daac374 all is fine.

### Software information
Tested with Heroes of the Storm in fullscreen and borderless fullscreen.

### System information
- GPU: RX 570
- Driver: mesa-git 20
- Wine version:  staging 4.21-tkg
- DXVK version: git-master

### Log files
[HeroesOfTheStorm_x64_d3d11.log](https://github.com/doitsujin/dxvk/files/3907101/HeroesOfTheStorm_x64_d3d11.log)
[HeroesOfTheStorm_x64_dxgi.log](https://github.com/doitsujin/dxvk/files/3907102/HeroesOfTheStorm_x64_dxgi.log)

**Comment by doitsujin** [comment]
Is this exclusive to XWayland or does it also happen with plain X11?

I don't really care about XWayland. WSI is known to be broken and have all sorts of issues, don't use it.

**Comment by aufkrawall** [comment]
Seems to happen in every game, native Xorg is fine.

**Comment by aufkrawall** [comment]
For whatever reason, I can't reproduce anymore. This probably strongly points in the direction that  this is out of DXVK's scope. I'll leave this open for a few more days and then close, if you don't mind.

**Comment by LeJimster** [comment]
Not sure if this is related, but they have been working on improving [XWayland stuttery behaviour](https://www.phoronix.com/scan.php?page=news_item&px=XWayland-Multi-Buffering-Lands)

**Comment by aufkrawall** [comment]
@LeJimster Thanks for mentioning, but the linked XWayland improvements are likely unrelated. :)
Maybe it's due to some race condition caused by immature Wayland eco system, who knows. At least I can't reproduce anymore, thus closing.
