### ISSUE TITLE
Memory leak in STAR WARS Jedi: Fallen Order

### ISSUE THREAD

**Issue by FrogTheFrog** [doitsujin/dxvk#1265]
Hello,

I've encountered this memory leak while playing Star Wars after some time, which leads to a major slowdown and a crash (if you try really hard).

I've managed to replicate this issue by spamming Esc key to open and close menu, but I believe that the root cause might be somewhere else - I don't think I've opened menu this many times during normal gameplay.

In addition to required files, I've attached video of me spamming Esc key with full DXVK hud. 

---

### Software information
- Game: STAR WARS Jedi: Fallen Order
- Settings: Epic preset
- Resolution: 2560x1440

### System information
- GPU: GTX 1080
- Driver: 440.36.0
- Wine version: 4.21
- DXVK version: 1.4.6

### Apitrace file(s)
- [starwarsjedifallenorder.trace](https://drive.google.com/open?id=1IMwrsB3o5dryvEjuLXP2EhWoRZE2fz28)

### Log files
- [starwarsjedifallenorder_d3d11.log](https://github.com/doitsujin/dxvk/files/3918681/starwarsjedifallenorder_d3d11.log)
- [starwarsjedifallenorder_dxgi.log](https://github.com/doitsujin/dxvk/files/3918683/starwarsjedifallenorder_dxgi.log)

### Notes
- Apitrace includes crash, however log files had the game exit gracefully.
- [Video](https://youtu.be/yr3kSlZ75X8) reproducing memory leak and an eventual crash.

**Comment by doitsujin** [comment]
Are you **absolutely sure** this isn't just a game bug? DXVK isn't known to leak memory.

**Comment by K0bin** [comment]
It's a game bug.
![grafik](https://user-images.githubusercontent.com/1131720/70095128-46c26480-1624-11ea-9a66-652f9b8de3a2.png)

(F for my poor escape key)

**Comment by doitsujin** [comment]
Thanks for checking.

> Apitrace includes crash, however log files had the game exit gracefully.

FWIW the apitrace seems somewhat broken (not your fault); apitrace thinks it only contains one frame and lacks some references to DXGI objects -> I can't replay it. But yeah, this looks like it creates some framebuffers that it never frees afterwards.

**Comment by Joshua-Ashton** [comment]
> apitrace thinks it only contains one frame and lacks some references to DXGI objects -> I can't replay it

Was dxgi.dll and dxgitrace.dll used?

**Comment by doitsujin** [comment]
Actually, now that Josh mentioned it, was the trace created on Proton? Proton uses Wine's DXGI now, so when recording a trace, you'll probably need to set the environment variable `WINEDLLOVERRIDES=dxgi=n,b` now.

Anyway, it's not important in this case since it seems to happen on Windows as well.

**Comment by FrogTheFrog** [comment]
Ah, dang it! 

Anyway, regarding the apitrace - I'm using proton. I had to enable apitrace by moving dlls, but I did not know about that override. Will do it the next time!

Since, it's a game bug, I'm closing the issue.
