### ISSUE TITLE
Star Citizen crashing with DXVK 1.4.6

### ISSUE THREAD

**Issue by gort818** [doitsujin/dxvk#1266]
When loading into a server in Star Citizen the game seems to crash at compiling shaders.

### Software information
Star Citizen Live 3.7.2

### System information
- GPU:Vega56
- Driver:mesa-aco-git 20.0.0_devel.20191126.6df53a980c0
- Wine version: 4.21 staging
- DXVK version: 1.4.6

### Apitrace file(s)
- We have a member working on a getting on on Windows for both issues.

### Log files
- d3d11.log:
[StarCitizen_d3d11.log](https://github.com/doitsujin/dxvk/files/3920135/StarCitizen_d3d11.log)
- dxgi.log:
[StarCitizen_dxgi.log](https://github.com/doitsujin/dxvk/files/3920136/StarCitizen_dxgi.log)

### Git bisect

Performed a bisect
first bad commit: [00a064e32bcf46e3d0bb536ce11af1b4c22006d8] [dxvk] Don't clear bind mask for unbound UBOs and samplers.

I reverted that commit and tested and I could load the game without crashing.

**Comment by doitsujin** [comment]
I **still** don't have a way to debug these issues since nobody managed to provide an apitrace yet.

Not to mention that this makes absolutely no sense.

**Comment by doitsujin** [comment]
Actually, can you delete your state cache and test again? There used to be a weird issue with RADV crashing when compiling identical pipelines, we might be running into that.

**Comment by doitsujin** [comment]
Well, I'll revert the commit, but please note that the commit itself **is not the cause** of the bug.

**Comment by tannisroot** [comment]
Do you people have some Discord server where you discuss this or what

**Comment by beniwtv** [comment]
Yes, indeed there is: https://discord.gg/meCFYPj

I can confirm that deleting DXVK cache, Mesa cache and game's own shader cache (all 3 I know of) did not help, only switching back to 1.4.5.

**Comment by beniwtv** [comment]
A LUG member has provided a trace from Windows, if it helps:
https://drive.google.com/open?id=1ZVDwO8sEsisGMG_HfQF8PnuG7HEmt475

**Comment by rawfoxDE** [comment]
As long as there is a reduced amount of objects were you spawn into, its doing the job, but once you open a door and there is a new, mutch bigger amount of world geometry, textures and lights and so on, its crashing.
1.4.5 has been working nice with StarCitizen, beside of the dark shadows bug.

**Comment by doitsujin** [comment]
@beniwtv thanks, unfortunately I'm not getting a crash when replaying that apitrace. It also doesn't seem to reproduce the issue in #1262.

**Comment by beniwtv** [comment]
Yep that trace was not done on a planet (which is what happens on issue #1262) - that will need a separate trace

**Comment by Tk-Glitch** [comment]
No crashing on nvidia with 1.4.5 btw, I have tried as hard as I could.

**Comment by doitsujin** [comment]
@Tk-Glitch 1.4.5 or 1.4.6? 1.4.5 is known to work.

**Comment by Tk-Glitch** [comment]
Sorry, edited. I frogged up.

**Comment by beniwtv** [comment]
@Tk-Glitch Did you test the game or the api trace?

**Comment by Tk-Glitch** [comment]
On the game itself. Ran it for 3 hours, landed at Arc Corp and Lorville, disconnected/reconnected there. Then I left my ship fly over ArcCorp planet and Hurston surfaces for a while. No crash during those 3 hours.

**Comment by beniwtv** [comment]
I can now also confirm 1.4.6 + the revert (what's now in the 1.4.6 release tarball) works and does not crash.

**Comment by rawfoxDE** [comment]
Ya, working again, thanks @doitsujin ^^
