### ISSUE TITLE
Can't start FIFA19

### ISSUE THREAD

**Issue by rockybalboa** [doitsujin/dxvk#1268]
Hi,

I'm trying to setup DXK on a new computer, but failed to start FIFA19 with the latest DXVK:
`DxgiFactory::EnumWarpAdapter: Not implemented`

I use Wine Staging 4.21

Here's the log:
[FIFA19_dxgi.log](https://github.com/doitsujin/dxvk/files/3941307/FIFA19_dxgi.log)

Vulkaninfo:
[vulkaninfo.txt](https://github.com/doitsujin/dxvk/files/3941309/vulkaninfo.txt)

Any idea? I have a GTX960 with 435.27.08 Nvidia driver.

**Comment by doitsujin** [comment]
WARP is a software implementation of D3D on Windows, obviously it doesn't exist on Linux. If it *really* requires that, there's no reasonable way to support this (unless it's happy if we just return the first hardware adapter).

Note that Fifa 19 definitely did work with DXVK in the past, did the game receive an update recently?

**Comment by doitsujin** [comment]
FWIW I hacked together a quick fake implementation of that function, which should *hopefully* allow the game to run. Please test with fc91fe1d3417656721132b0dc4c2558407b95ba0

Here's a build: 
[dxvk-master.tar.gz](https://github.com/doitsujin/dxvk/files/3942176/dxvk-master.tar.gz)

**Comment by rockybalboa** [comment]
@doitsujin Thanks, it works now, you're awesome. :) And yes, it worked before with an earlier DXVK release. 

However I still can't start fifaconfig (it's needed to configure the screen resolution and other graphic settings), I'm not sure it's a wine or a DXVK bug:
[fifaconfig.txt](https://github.com/doitsujin/dxvk/files/3946011/fifaconfig.txt)

**Comment by doitsujin** [comment]
Thanks for the feedback. I guess it stopped working when we implemented DXGI 1.4 or 1.5.

The config tool bug looks like a .NET issue, not related to dxvk.

**Comment by mozo78** [comment]
> @doitsujin Thanks, it works now, you're awesome. :) And yes, it worked before with an earlier DXVK release.
> 
> However I still can't start fifaconfig (it's needed to configure the screen resolution and other graphic settings), I'm not sure it's a wine or a DXVK bug:
> [fifaconfig.txt](https://github.com/doitsujin/dxvk/files/3946011/fifaconfig.txt)

You need .Net 4.7.2 or you can tweak the settings from the settings file fifasetup.ini. If I recall corectly it's in the home folder.

**Comment by rockybalboa** [comment]
> You need .Net 4.7.2 or you can tweak the settings from the settings file fifasetup.ini. If I recall corectly it's in the home folder.

Thanks, I've installed Donet 4.7.2 with winetricks and it solved the problem.

**Comment by mozo78** [comment]
You are welcome :)

**Comment by milchevdimitar** [comment]
Мозо, и аз имам такъв проблем само че с пиратската фифа от замундата. Това, което ми хвърля като output:
```
wine-4.10
##################
game:    FIFA19
##################
home: /home/dimitar/GAMES_HDD/fifa_19/FIFA19/game/home

wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
info:  Game: FIFA19.exe
info:  DXVK: v1.2.2
info:  Found built-in config: FIFA19.exe
info:  Effective configuration:
info:    dxvk.useRawSsbo = True
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD Radeon RX 5700 XT (RADV NAVI10):
info:    Driver: 23.0.2
info:    Vulkan: 1.3.238
info:    Memory Heap[0]: 
info:      Size: 7936 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:      Memory Type[7]: Property Flags = 0xc1
info:    Memory Heap[1]: 
info:      Size: 16003 MiB
info:      Flags: 0x0
info:      Memory Type[2]: Property Flags = 0x6
info:      Memory Type[5]: Property Flags = 0xe
info:      Memory Type[6]: Property Flags = 0xe
info:      Memory Type[8]: Property Flags = 0xc6
info:      Memory Type[10]: Property Flags = 0xce
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[3]: Property Flags = 0x7
info:      Memory Type[4]: Property Flags = 0x7
info:      Memory Type[9]: Property Flags = 0xc7
info:  Game: FIFA19.exe
info:  DXVK: v1.2.2
info:  Found built-in config: FIFA19.exe
info:  Effective configuration:
info:    dxvk.useRawSsbo = True
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD Radeon RX 5700 XT (RADV NAVI10):
info:    Driver: 23.0.2
info:    Vulkan: 1.3.238
info:    Memory Heap[0]: 
info:      Size: 7936 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:      Memory Type[7]: Property Flags = 0xc1
info:    Memory Heap[1]: 
info:      Size: 16003 MiB
info:      Flags: 0x0
info:      Memory Type[2]: Property Flags = 0x6
info:      Memory Type[5]: Property Flags = 0xe
info:      Memory Type[6]: Property Flags = 0xe
info:      Memory Type[8]: Property Flags = 0xc6
info:      Memory Type[10]: Property Flags = 0xce
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[3]: Property Flags = 0x7
info:      Memory Type[4]: Property Flags = 0x7
info:      Memory Type[9]: Property Flags = 0xc7
warn:  DxgiAdapter::QueryInterface: Unknown interface query
warn:  17399d75-964e-4c03-99f8-9d4fd196dd62
err:   DxgiFactory::EnumWarpAdapter: Not implemented
wine: Unhandled exception 0x80004001 in thread 41 at address 0x7b453b7e (thread 0041), starting debugger...
Usage:
        winedbg [ [ --gdb ] [ <prog-name> [ <prog-args> ] | <num> | <file.mdmp> | --help ]

```

**Comment by Blisto91** [comment]
@milchevdimitar We do not support pirated content. Please keep such discussions away from here.
