### ISSUE TITLE
DOOM(2016) freezing after 1-30 minutes

### ISSUE THREAD

**Issue by trialism** [doitsujin/dxvk#1269]
### System information
- Setting: 1440p at 144hz and ultra
- GPU: RTX 2080
- Driver: 440.31
- CPU Ryzen 1800x
- Proton version: from 3.16-9 to 4.11-9

The smallest log was 290Mb so I only uploaded the beginning and the end of it [here](https://pastebin.com/mCa7e9r1). The freeze doesn't need any specific trigger to appear - it can happen when no other app runs or when I'm fighting, walking or just standing still.

**Comment by K0bin** [comment]
Doom 2016 uses Vulkan directly. DXVK is not involved at all.
