### ISSUE TITLE
How exactly is determined if D3D_FEATURE_LEVEL_11_0 is supported?

### ISSUE THREAD

**Issue by Rotscha** [doitsujin/dxvk#127]
I'm trying to use DXVK on three different DX11 games (Witcher 3, Elder Scrolls Online, Divinity Original Sin 2).

All of them run with wined3d (well Divinity crashes after startup, but that's another story), but all of them report missing DX11 compatibility when trying to run with DXVK. I've tried with wine-vulkan and wine-2.21-staging. Results are the same.

The d3d11.log states:
**info:  D3D11CreateDevice: Probing D3D_FEATURE_LEVEL_11_0
err:   D3D11CreateDevice: Requested feature level not supported**

However, I've seen people reporting that Witcher 3 and ESO should work. So I have to find out, why it won't work for me.

My GPU is rather old, but according to NVidia it is still fully Vulkan-supported.

- GPU: GTX 680 4GB (Kepler)
- Driver: 390.25 (proprietary)
- Wine version: wine-vulkan (built today), wine-2.21-staging
- DXVK version: prebuilt 0.30 and https://haagch.frickel.club/files/dxvk/latest/64/bin/

So, is it possible that DXVK requires some undocumented hardware capabilities?

**Comment by Yardanico** [comment]
Does vulkan work in Linux?

**Comment by doitsujin** [comment]
The `shaderStorageImageReadWithoutFormat` capability is not supported on your GPU (see [here](https://vulkan.gpuinfo.org/displayreport.php?id=1765#features)), which is required for Unordered Access Views.

**Comment by Rotscha** [comment]
Thanks very much! I guess, there is no possible workaround?

**Comment by doitsujin** [comment]
None that I'm aware of. I mean, you can disable `shaderStorageImageReadWithoutFormat` in the code if you build DXVK yourself and see if it still works, but I have my doubts.

**Comment by Rotscha** [comment]
Ok, I removed the check for **shaderStorageImageReadWithoutFormat** and the games are starting up now. I will have to see what side effect that modification has.

Case closed. Thanks for your help :)

**Comment by Thaodan** [comment]
Maybe add a better error message to avoid issues like this?

**Comment by elovin** [comment]
@Rotscha 
How well does Divinity original sin 2 work ?
