### ISSUE TITLE
Control - CPU usage 100% all the time, and frametimes are so high

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [doitsujin/dxvk#1274]
Control goes up to 450ms frametimes, it stutters all the time, and the movement are so slow. Also, I noticed that GPU usage is at 100% all the time on Linux.

I tested the same game on Windows, and frametimes don't exceed 55 ms, and it is buttery smooth.

![Screenshot from 2019-12-16 01-53-35](https://user-images.githubusercontent.com/29783425/70871654-15458380-1faa-11ea-8a03-0f9f0a6f3399.png)

### Software information
Name of the game: Control
Settings: all are on low, and I disabled SSAO, and screen space reflection.

### System information
- GPU: AMD HD 8750M
- Driver: Mesa 19.3 (Kisak PPA)
- Wine version: 5.0-rc1
- DXVK version: 1.4.6

### Log files
- d3d11.log: 
[Control_DX11_d3d11.log](https://github.com/doitsujin/dxvk/files/3965642/Control_DX11_d3d11.log)
- dxgi.log:
[Control_DX11_dxgi.log](https://github.com/doitsujin/dxvk/files/3965643/Control_DX11_dxgi.log)

**Comment by Joshua-Ashton** [comment]
> I tested the same game on Windows, and frametimes don't exceed 55 ms, and it is buttery smooth.

To rule out this being some weird Wine bug/mouse crap, trying it with DXVK on Windows might be a good idea.

**Comment by doitsujin** [comment]
Please check the system requirements for this game:
https://techreport.com/news/3463808/remedy-control-pc-recommended-requirements/

Now I don't know what your CPU is, but since this is obviously a rather old laptop it's probably quite a bit slower than the minimum required quad-core i5, and your GPU is so far below even the *minimum* requirements it's not even funny. What do you expect?

**Comment by ahmed-elsayed2017** [comment]
> > I tested the same game on Windows, and frametimes don't exceed 55 ms, and it is buttery smooth.
> 
> To rule out this being some weird Wine bug/mouse crap, trying it with DXVK on Windows might be a good idea.

I have just installed Windows a week ago, and I can't boot to it again. It sticks in a weird boot loop. I may install it again.

**Comment by ahmed-elsayed2017** [comment]
> Please check the system requirements for this game:
> https://techreport.com/news/3463808/remedy-control-pc-recommended-requirements/
> 
> Now I don't know what your CPU is, but since this is obviously a rather old laptop it's probably quite a bit slower than the minimum required quad-core i5, and your GPU is so far below even the _minimum_ requirements it's not even funny. What do you expect?
> 
> You'll also want to make sure to use Fsync on Linux and preferably a custom kernel with an alternative scheduler, since CFS is known to be pretty bad with games, but none of that will make this game run particularly well on your hardware. There's also differences in power management between Linux and Windows to take into account, which all affetcs performance.

I know the game requires a better specification, and I know that it will not run well on my old laptop, but my issue is with the constant shuttering that I haven't encountered with any other games. Fsync decreases frametimes a little bit, but valve kernel didn't get any updates from 21 weeks ago. I tried lowering resolution, and that helped to decrease frametimes a lot, and the game is so much smoother now than it was before. I don't know how to use custom kernels on Ubuntu. It was much easier on Manjaro, but I will try to look for something that could help with that.
