### ISSUE TITLE
S.T.A.L.K.E.R.: Call of Pripyat crash at launch (DX11)

### ISSUE THREAD

**Issue by shoober420** [doitsujin/dxvk#1277]
### Software information
S.T.A.L.K.E.R.: Call of Pripyat

Game crashes at launch, works in DX9 mode with D9VK though.

### System information
- GPU: GTX 760
- Driver: NVIDIA 440.44
- Wine version: Proton 4.11-10
- DXVK version: 1.4.6

### Log files
[steam-41700.log](https://github.com/doitsujin/dxvk/files/3966962/steam-41700.log)
[xrEngine_d3d11.log](https://github.com/doitsujin/dxvk/files/3966964/xrEngine_d3d11.log)

**Comment by sputniktr02** [comment]
Try installing these with winetricks or protontricks:

d3dcompiler_42
d3dcompiler_43
d3dcompiler_47
d3dx9
d3dx10_43
d3dx10
d3dx11_42
d3dx11_43

**Comment by shoober420** [comment]
I prefer not to have to install actual Microsoft dll’s on my computer. Here’s a little tidbit that answers some questions.

https://github.com/doitsujin/dxvk/issues/272

**Comment by doitsujin** [comment]
> I prefer not to have to install actual Microsoft dll’s on my computer.
That's your problem and not a DXVK issue.

**Comment by shoober420** [comment]
Why do other DX11 games work but CoF doesn’t? Isn’t the end result here to run games without any need for Microsoft dll’s? How is this invalid?

**Comment by doitsujin** [comment]
It is invalid because the DLLs in question are not and have never been part of DXVK, but wine, and the wine implementation just doesn't work for them (yet). The workaround is to use the Microsoft DLLs.

**Comment by shoober420** [comment]
Ok, I understand now. Thank you for explaining. I will wait on proper support when Wine implements those features and/or install those d3dcompilers.
