### ISSUE TITLE
x32 WINEPREFIX driver loading problem

### ISSUE THREAD

**Issue by sajmonella9** [doitsujin/dxvk#128]
Just one problem. I try run x32 bit's apps on x64. But driver like before don't want load. I try all even install another x64 with sucess . But in another wineprefix x32 still it's the same problem. 

So, on working x64 wineprefix apps working , but x32 no.
And on new x32 wineprefix apps don't working too. This time i check all from beggining. Have the same message , about ICD . How it's work? Its possible or i can only make one working platform. 

I just know one thing, when i don't use export one file like : 
` export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json`

Then x64 winperefix don't work too. So my question is how to export or add another path to lib32. Cuz i think it's source of this problem. 

nvidia_icd.json

`{
    "file_format_version" : "1.0.0",
    "ICD": {
        "library_path": "libGLX_nvidia.so.0",
        "api_version" : "1.0.65"
    }
}
`

**Comment by doitsujin** [comment]
DXVK works without any issues for me in a 32-bit wine prefix. For 32-bit support in a 64-bit prefix, you need to install **both** the 32-bit and 64-bit libraries.

Please confirm that you can run cube.exe (in this case, the 32-bit version) before reporting a DXVK bug. I do **not** feel responsible for fixing broken/incomplete wine setups.

**Comment by ssorgatem** [comment]
It looks like you need a 32 bit nvidia ICD pointing to a 32-bit nvidia driver.

Unrelated to DXVK.
