### ISSUE TITLE
[DXVK 1.5] Battle.net app not launching, works on 1.4.6

### ISSUE THREAD

**Issue by BloodyIron** [doitsujin/dxvk#1282]
I'm using the Lutris installer for both Overwatch and World of Warcraft.

Before the weekend, Overwatch was working, as in the Battle.net app comes up just fine. Then DXVK 1.5 rolled out, and that's the only thing that has changed, and now it seems to crash as it starts up.

I just installed WoW through Lutris and same thing. Battle.net app doesn't come up with DXVK 1.5, but does for 1.4.6.

I'm very confident this is a regression.

* Ubuntu 19.10
* RX 580
* Ryzen 5 2600

**Comment by doitsujin** [comment]
Logs? Anything?

**Comment by doitsujin** [comment]
Battle.net does **not** work for me with 1.4.6.

**Comment by doitsujin** [comment]
Might be a Lutris problem. When launching directly from the terminal, it works for me **with** DXVK 1.5:
![Bildschirmfoto-1108](https://user-images.githubusercontent.com/25567304/70960832-69bb3280-2080-11ea-9e63-fe3cad8502b9.png)

**Comment by doitsujin** [comment]
Ok so my problem was that for some reason i had renderdoc enabled, which of course doesn't work since battle.net is a 32-bit app. Anyway, as you can see, the client works just fine with DXVK 1.5 here.

**Comment by aufkrawall** [comment]
It might sometimes not start, but it has always been like that and it usually works on the 2nd attempt after a `wineserver -k`.
I don't notice any regression with my daily mingw builds here.

**Comment by BloodyIron** [comment]
Sorry, let me clarify further. The battle.net app comes up, and I enter my credentials, then it closes as if it is about to load the full app, and it never comes up.

This is the Lutris log after I enter my credentials:

`info:  Game: Battle.net.exe
info:  DXVK: v1.5
info:  Found config file: /home/bloodyiron/Games/overwatch/dxvk.conf
info:  Effective configuration:
info:    dxgi.nvapiHack = False
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
Xlib:  extension "NV-GLX" missing on display ":0".`

**Comment by doitsujin** [comment]
If that really is all it says, it doesn't even get far enough to create a D3D11 device on your end. Can you try launching it from the terminal? You have to
```
export PATH=$HOME/.local/share/lutris/runners/wine/your-runner/bin:$PATH
export WINEPREFIX=/home/bloodyiron/Games/overwatch
export WINEDLLOVERRIDES=dxgi,d3d11=n
wine /path/to/battle.net.exe
```

**Comment by BloodyIron** [comment]
That worked, even pointed it to the same 4.20 runner... unsure why I'm getting different results. Gonna post the log output in the next response.

> If that really is all it says, it doesn't even get far enough to create a D3D11 device on your end. Can you try launching it from the terminal? You have to
> 
> ```
> export PATH=$HOME/.local/share/lutris/runners/wine/your-runner/bin:$PATH
> export WINEPREFIX=/home/bloodyiron/Games/overwatch
> export WINEDLLOVERRIDES=dxgi,d3d11=n
> wine /path/to/battle.net.exe
> ```

**Comment by BloodyIron** [comment]
This is the output (after I enter login credentials to battle.net) from the test you wanted me to perform:


0009:fixme:win:FlashWindowEx 0x329960 - semi-stub
0009:fixme:win:FlashWindowEx 0x32cb34 - semi-stub
0009:fixme:shell:CustomDestinationList_SetAppID 0x8f6bc98 (L"BlizzardEntertainment.Battlenet.beta"): stub
0009:fixme:shell:CustomDestinationList_BeginList 0x8f6bc98 (0x32c648 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x32c64c): stub
0009:fixme:shell:CustomDestinationList_SetAppID 0x8ec65d8 (L"BlizzardEntertainment.Battlenet.beta"): stub
0009:fixme:shell:CustomDestinationList_BeginList 0x8ec65d8 (0x32bd10 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x32bd14): stub
info:  Game: Battle.net.exe
info:  DXVK: v1.5
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
Xlib:  extension "NV-GLX" missing on display ":0".
0009:err:vulkan:wine_vk_instance_load_physical_devices Failed to enumerate physical devices, res=-3
0009:err:vulkan:wine_vkCreateInstance Failed to load physical devices, res=-3
err:   DxvkInstance::createInstance: Failed to create Vulkan instance
err:   D3D11CreateDevice: Failed to create a DXGI factory
info:  Game: Battle.net.exe
info:  DXVK: v1.5
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
Xlib:  extension "NV-GLX" missing on display ":0".
0009:err:vulkan:wine_vk_instance_load_physical_devices Failed to enumerate physical devices, res=-3
0009:err:vulkan:wine_vkCreateInstance Failed to load physical devices, res=-3
err:   DxvkInstance::createInstance: Failed to create Vulkan instance
err:   D3D11CreateDevice: Failed to create a DXGI factory
0009:fixme:d3d9:d3d9_device_CreateTexture Resource sharing not implemented, *shared_handle 00000000.
0009:fixme:shell:SHGetPropertyStoreForWindow (0x500c6 0x111a8968 0x326d60) stub!
0009:fixme:shell:window_prop_store_SetValue 0x90c7a30, {{9f4c2855-9f79-4b39-a8d0-e1d42de1d5f3},4}, 0x326d50
0009:fixme:shell:window_prop_store_SetValue 0x90c7a30, {{9f4c2855-9f79-4b39-a8d0-e1d42de1d5f3},2}, 0x326d40
0009:fixme:shell:window_prop_store_SetValue 0x90c7a30, {{9f4c2855-9f79-4b39-a8d0-e1d42de1d5f3},3}, 0x326d30
0009:fixme:shell:window_prop_store_SetValue 0x90c7a30, {{9f4c2855-9f79-4b39-a8d0-e1d42de1d5f3},5}, 0x326d20
0009:fixme:shell:window_prop_store_Commit 0x90c7a30
0009:fixme:font:get_nearest_charset TCI failing on 20000000
0009:fixme:font:get_nearest_charset returning DEFAULT_CHARSET face->fs.fsCsb[0] = 20000000 file = L"/usr/share/fonts/truetype/fonts-gujr-extra/aakar-medium.ttf"
0009:fixme:shell:SHGetPropertyStoreForWindow (0x400c0 0x111a8968 0x32af00) stub!
0009:fixme:shell:window_prop_store_SetValue 0x1d7e08, {{9f4c2855-9f79-4b39-a8d0-e1d42de1d5f3},4}, 0x32aef0
0009:fixme:shell:window_prop_store_SetValue 0x1d7e08, {{9f4c2855-9f79-4b39-a8d0-e1d42de1d5f3},2}, 0x32aee0
0009:fixme:shell:window_prop_store_SetValue 0x1d7e08, {{9f4c2855-9f79-4b39-a8d0-e1d42de1d5f3},3}, 0x32aed0
0009:fixme:shell:window_prop_store_SetValue 0x1d7e08, {{9f4c2855-9f79-4b39-a8d0-e1d42de1d5f3},5}, 0x32aec0
0009:fixme:shell:window_prop_store_Commit 0x1d7e08
0009:fixme:wtsapi:WTSRegisterSessionNotification Stub 000400C0 0x00000000
0009:fixme:d3d9:d3d9_device_CreateTexture Resource sharing not implemented, *shared_handle 00000000.
00ed:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts.
00ed:fixme:d3d:state_lastpixel Last Pixel Drawing Disabled, not handled yet
00f3:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
00f3:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
00f3:fixme:ntdll:EtwEventRegister ({d2d578d9-2936-45b6-a09f-30e32715f42d}, 0x1fc6360, 0x5c9f4e0, 0x5cdcb48) stub.
00f8:fixme:thread:SetThreadDescription (FFFFFFFE L"BrokerEvent"): stub
00f3:fixme:thread:SetThreadDescription (FFFFFFFE L"CrRendererMain"): stub
00f9:fixme:thread:SetThreadDescription (FFFFFFFE L"ThreadPoolServiceThread"): stub
00fa:fixme:thread:SetThreadDescription (FFFFFFFE L"ThreadPoolForegroundWorker"): stub
00fb:fixme:thread:SetThreadDescription (FFFFFFFE L"ThreadPoolBackgroundWorker"): stub
00fc:fixme:thread:SetThreadDescription (FFFFFFFE L"Chrome_ChildIOThread"): stub
00ff:fixme:thread:SetThreadDescription (FFFFFFFE L"GpuMemoryThread"): stub
0100:fixme:thread:SetThreadDescription (FFFFFFFE L"Compositor/256"): stub
0101:fixme:thread:SetThreadDescription (FFFFFFFE L"CompositorTileWorker1/257"): stub
0102:fixme:thread:SetThreadDescription (FFFFFFFE L"CompositorTileWorker2/258"): stub
0103:fixme:thread:SetThreadDescription (FFFFFFFE L"CompositorTileWorker3/259"): stub
0104:fixme:thread:SetThreadDescription (FFFFFFFE L"CompositorTileWorker4/260"): stub
0105:fixme:thread:SetThreadDescription (FFFFFFFE L"CompositorTileWorkerBackground/261"): stub
0106:fixme:thread:SetThreadDescription (FFFFFFFE L"ThreadPoolForegroundWorker"): stub
0107:fixme:thread:SetThreadDescription (FFFFFFFE L"ThreadPoolForegroundWorker"): stub
0108:fixme:thread:SetThreadDescription (FFFFFFFE L"ThreadPoolForegroundWorker"): stub
0109:fixme:thread:SetThreadDescription (FFFFFFFE L"ThreadPoolForegroundWorker"): stub
010a:fixme:thread:SetThreadDescription (FFFFFFFE L"ThreadPoolForegroundWorker"): stub
010c:fixme:thread:SetThreadDescription (FFFFFFFE L"ThreadPoolForegroundWorker"): stub
010b:fixme:thread:SetThreadDescription (FFFFFFFE L"ThreadPoolForegroundWorker"): stub
00f3:fixme:time:QueryThreadCycleTime (0xfffffffe,0x32ef80): stub!
008e:fixme:mpr:WNetGetUniversalNameW (L"C:\\Program Files (x86)\\Overwatch\\data\\casc\\data", 0x00000001, 0353D6B0, 0353D6AC): stub
0009:fixme:shell:SHGetPropertyStoreForWindow (0x300f4 0x111a8968 0x329da0) stub!
0009:fixme:shell:window_prop_store_SetValue 0x1d59e2b0, {{9f4c2855-9f79-4b39-a8d0-e1d42de1d5f3},4}, 0x329d90
0009:fixme:shell:window_prop_store_SetValue 0x1d59e2b0, {{9f4c2855-9f79-4b39-a8d0-e1d42de1d5f3},2}, 0x329d80
0009:fixme:shell:window_prop_store_SetValue 0x1d59e2b0, {{9f4c2855-9f79-4b39-a8d0-e1d42de1d5f3},3}, 0x329d70
0009:fixme:shell:window_prop_store_SetValue 0x1d59e2b0, {{9f4c2855-9f79-4b39-a8d0-e1d42de1d5f3},5}, 0x329d60
0009:fixme:shell:window_prop_store_Commit 0x1d59e2b0
0009:fixme:wtsapi:WTSUnRegisterSessionNotification Stub 000400C0
005c:fixme:userenv:UnregisterGPNotification 0000038C
005c:fixme:userenv:UnregisterGPNotification 00000390
00df:fixme:file:ReplaceFileW Ignoring flags 2
005b:fixme:file:ReplaceFileW Ignoring flags 2
011a:fixme:thread:SetThreadDescription (FFFFFFFE L"ThreadPoolForegroundWorker"): stub
011b:fixme:thread:SetThreadDescription (FFFFFFFE L"ThreadPoolForegroundWorker"): stub
0009:fixme:win:UnregisterDeviceNotification (handle=0xcafeaffe), STUB!
011c:fixme:thread:SetThreadDescription (FFFFFFFE L"ThreadPoolSingleThreadCOMSTASharedForegroundBlocking4"): stub
00df:fixme:file:ReplaceFileW Ignoring flags 2
00c7:fixme:iphlpapi:CancelIPChangeNotify (overlapped 0x6556a80): stub
00aa:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
00aa:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0032FE9C
[1217/113910.547:ERROR:browser_process_sub_thread.cc(221)] Waited 12 ms for network service
0009:fixme:wtsapi:WTSUnRegisterSessionNotification Stub 0001008E
0009:fixme:iphlpapi:CancelIPChangeNotify (overlapped 0x75d4e98): stub
0009:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0009:fixme:font:RemoveFontMemResourceEx (0x8fa04371) stub
0009:fixme:font:RemoveFontMemResourceEx (0x8fa325a1) stub
0009:fixme:font:RemoveFontMemResourceEx (0x8fa28fc1) stub
0009:fixme:font:RemoveFontMemResourceEx (0x8fac71c9) stub
0009:fixme:font:RemoveFontMemResourceEx (0x8fb14311) stub
0009:fixme:font:RemoveFontMemResourceEx (0x8fbe7301) stub
0009:fixme:font:RemoveFontMemResourceEx (0x8f871ed9) stub
0009:fixme:font:RemoveFontMemResourceEx (0x8fb567d9) stub
0009:fixme:font:RemoveFontMemResourceEx (0x8f8c1301) stub
003d:fixme:win:UnregisterDeviceNotification (handle=0xcafecafe), STUB!
0009:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0032FE9C
0009:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0009:fixme:ntdll:EtwEventUnregister (0) stub.
0009:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0009:fixme:ntdll:EtwEventUnregister (0) stub.

**Comment by BloodyIron** [comment]
I also want to add that with Lutris I'm using gamemode Lutris wide:

LD_PRELOAD : usr/lib/x86_64-linux-gnu/libgamemodeauto.so

**Comment by lekzz** [comment]
Same for me on plain wine (no lutris) and very easy to reproduce. Uninstall dxvk and it starts again,  install 1.4.6 still starts, update to 1.5 not starting anymore.
Or well it does start, the login window show up and disappears but then nothing happens. The taskbar icon does shows up but can not be clicked in anyway, it only shows "Blizzard Battle.net" on mouseover. If you manually delete the Battle.net.11740 folder it will be recreated and redownloaded on the next start, so it's still doing something.

Also running a full AMD system like the OP, 3600x with RX 5700. Also a very recent wine profile with nothing but battle.net installed.

Hard to get useful logging so far, i will keep trying. What i did notice tho is that Battle.net_d3d9.log only contains logging info from 1.5 while Battle.net_dxgi.log only contains logging from 1.4.6.

**Comment by A6GibKm** [comment]
Thats weird, Bnet working here.

### Setup

Fedora 31 Silverblue
DXVK 1.5
Lutris 0.5.4 (flatpak)
wine: lutris-4.21
AMD ryzen cpu 
AMD RX570 gpu

**Comment by doitsujin** [comment]
@lekzz can you try if `WINEDLLOVERRIDES=d3d9=b` fixes the problem for you? This will enforce the use of wined3d's d3d9 implementation.

**Comment by loathingKernel** [comment]
Had a similar issue. Using wine's dxgi fixed it in my case.

**Comment by lekzz** [comment]
@doitsujin Yes, it does. Battle.net and WoW working nicely again.

**Comment by jarrard** [comment]
Use Lutris terminal toggle with debugging enabled in the game configuration (Lutris option), and after you launch the client right click in Lutris and select show logs. 
(sorry if you already know this but it seemed like you didn't)

**Comment by scurrvy2020** [comment]
I have two AMD systems, one is affected by this and the other is not. 
1. 3700x + 5700XT + Arch = battle.net launches with dxvk 1.5.1
2. 2700X + RX580 + Manjaro = battle.net will not launch with dxvk 1.5.1 but launches with 1.4.6 

I tried to figure out what was different between to the two systems, but even the manjaro system is running unstable.  I tried amdvlk as well, which didn't work. 

I didn't see any errors in the log.

**Comment by aufkrawall** [comment]
Have you installed common native DLLs into the prefix, which usually is considered good practice?
`winetricks corefonts d3dcompiler_42 d3dcompiler_43 d3dcompiler_47 d3dx10_43 d3dx11_42 d3dx11_43 d3dx9_24 d3dx9_25 d3dx9_26 d3dx9_27 d3dx9_28 d3dx9_29 d3dx9_30 d3dx9_31 d3dx9_32 d3dx9_33 d3dx9_34 d3dx9_35 d3dx9_36 d3dx9_37 d3dx9_38 d3dx9_39 d3dx9_40 d3dx9_41 d3dx9_42 d3dx9_43 vcrun2017 vcrun2013 vcrun2012 vcrun2010 vcrun2008 vcrun2005`

**Comment by scurrvy2020** [comment]
I finally got back to this and can confirm that it will run perfectly fine if launched from the terminal.  So, is this a problem with lutris and AMD graphics?

**Comment by diegorodriguezv** [comment]
Hello. I was having similar symptoms as @BloodyIron but in a laptop with nVidia graphics. The problem was that even though the nVidia driver was installed it wasn't being used because the PC uses safeboot (BIOS setting) and the MOK that the installer generated was not registered at the BIOS level. So Ubuntu was using the Intel integrated graphics.
What I did was simply go back to the open source driver (nouveau) and then install again the proprietary one. This generated a new MOK. After rebooting I was presented with a dialog to "Enroll MOK" and now Ubuntu is using the nVidia driver.
After that I was able to use DXVK 1.5.4 for Battle.net again. I hope this helps someone.

**Comment by AlexandarY** [comment]
I had the same issue as **lekzz** after upgrading to dxvk 1.5.5 with wine-staging 5.2. I tried downgrading through all releases back to 1.5.1, but could not get Battle.Net to come up after logging in. Also with 1.5.1 I was able to started **_retail_/Wow.exe** directly, but it wasn't taking in my authentication??
Upgraded wine-staging to 5.3, but did not resolve the issue.
After running **WINEDLLOVERRIDES=d3d9=b wine 'World of Warcraft Launcher.exe'**, battle.net started and I was able to get in the game.

CPU: AMD Ryzen 5 1500X Quad-Core Processor
GPU: Radeon RX570
Mesa: 19.2.8-0ubuntu0~19.10.2
Vulkan: 1.1.114.0-1

P.S. Didn't find any useful logs, so haven't attached any.

**Comment by SveSop** [comment]
@AlexandarY 
Logging the Battle.net app with `DXVK_LOG_LEVEL=debug` you need to look for the logs in the battle.net folder, and that will vary when battle.net app is upgraded.
Eg. `/your/wine/prefix/drive_c/Program Files (x86)/Blizzard App/Battle.net.11864`

When battle.net app is upgraded, it will be Battle.net.11940 or whatever "build" they currently is using.

When it comes to launching wow.exe directly, i think there is a wine "bug", but i have forgotten what it was. Some option you need to enable in winecfg that makes it work, but breaks something else i think.. So best not to bother with that. Afaik it is unrelated to DXVK.

**Comment by BloodyIron** [comment]
Not sure what has directly improved the situation but this issue has seemed to go away in recent history.

**Comment by AlexandarY** [comment]
@SveSop thanks for the info!

I ran Battle.net with DXVK_LOG_LEVEL=debug and got back this:
`
info:  Game: Agent.exe
info:  DXVK: v1.5.5
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Required Vulkan extension VK_KHR_surface not supported
err:   DxvkInstance: Failed to create instance
`
Checked the **Common Issues** section and saw that this error usually means you have issues with vulkan, but I don't think this is the case. Also VK_KHR_surface seems to be part of 1.0.133 and i'm running 1.1.144:
`
ii  libvulkan1:amd64                           1.1.114.0-1                             amd64        Vulkan loader library
ii  libvulkan1:i386                            1.1.114.0-1                             i386         Vulkan loader library
ii  mesa-vulkan-drivers:amd64                  19.2.8-0ubuntu0~19.10.3                 amd64        Mesa Vulkan graphics drivers
`
Running Battle.net with **WINEDLLOVERRIDES=d3d9=b** doesn't produce the error.

**Comment by galitus** [comment]
hey, 

I have the same problem with a vega56 card and lutris.
Everything before dxvk 1.5 is working but 1.5.x won't work with the normal start. 
If you use "run EXE inside wine prefix" in lutris and select the battle.net.exe then it will start and everything works fine but lutris will not recognize anything running.

My guess is, it is this bug: https://github.com/lutris/lutris/issues/2591
because AMD users use mesa, which will build with gallium support, when a newer amd card (radeonsi) is in the system.
Nvidia cards are not using mesa, so no gallium support and so the lutris runner won't trigger the gallium support and won't remove the d3d9.dll, which is needed for any directx 9 stuff. 
Because of the integration of d9vk into dxvk 1.5.x the problem appeared for all amd users and dxvk 1.5.x . 
I never used d9vk before but I guess the same problem would be with dxvk 1.4 in combination of d9vk?

Hopefully this helps.

**Comment by gulafaran** [comment]
battlenet crashes here aswell untill i add WINEDLLOVERRIDES=d3d9=b , wine-staging from git and dxvk from git. on vega56 with radv, and i dont have gallium nine support compiled in so i dont think its the same issue as https://github.com/lutris/lutris/issues/2591

**Comment by galitus** [comment]
yeah, I think you are right.

but I have seen this issue two days ago:

https://github.com/lutris/lutris/issues/2782

I guess this is the exact problem. 

greetings

**Comment by julespetrikov** [comment]
I promised to provide logs for this problem in Twitter, here I am.

Attached are the Battle.net logs, Agent.exe is the problem here. I wanted to provide TERA as well, however I can't bring myself to download the entire game just to try out. However, it should be noted that some DX9 applications like BNet, TERA and Steam games like Remember Me are affected by this, on my workstation - which utilizes integrated Intel GPU.

DXVK version is 1.7 on Arch Linux.

[Agent_dxgi.log](https://github.com/doitsujin/dxvk/files/4933065/Agent_dxgi.log)
[Battle.net_d3d9.log](https://github.com/doitsujin/dxvk/files/4933067/Battle.net_d3d9.log)

**Comment by scurrvy2020** [comment]
When I had this problem I realised it was because I was using amdvlk
instead of radv.  It worked fine with radv.

**Comment by galitus** [comment]
add this 

VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json

under system options as environment variables

It helped me, to get it running again. 
It seems that lutris is starting with one or another ICD files, but doesn't use both if needed.
The battle.net launcher is x86 and overwatch for example is x64 bit, so it won't work with one file for both applications at the same time.
So I guess it's a lutris problem and not dxvk. Including dx9 into dxvk 1.5 just exposed the problem
because in lutris you only can select one file at a time. 
I don't really remember if it matters, but in lutris I choose the i686 one.

Hopefully it helps. : )

**Comment by Blisto91** [comment]
Sorry to necro an old issue. Does any of you still have this problem?

**Comment by Blisto91** [comment]
Sounds good. I didn't notice any dxvk workarounds in the lutris scripts i looked at.

**Comment by Blisto91** [comment]
If any of you still have this issue feel free to comment here again.

**Comment by runboy93** [comment]
Bnet annoyance with DXVK 2.0 release (working with 1.10.3), it will login normally but after that nothing works, whole launcher window is black and doesn't respond.

As workaround disabling DXVK 2.0 when using bnet for updating and such, and enabling again for gaming (start games from .exe)

**Comment by Blisto91** [comment]
@runboy93 Thanks for the report. Post some dxvk logs if you can.
I will see if i can reproduce later today.
