### ISSUE TITLE
Origin crashing with dxvk 1.5

### ISSUE THREAD

**Issue by gort818** [doitsujin/dxvk#1284]
### Software information
Origin game launcher crashes with 1.5
 
### System information
- GPU: Vega 56
- Driver: mesa-git 20.0.0_devel.118529.c06ba835895
- Wine version: 4.19 Staging
- DXVK version: 1.5

### Apitrace file(s)
- will get one shortly

### Log files
- d3d9.log:
- d3d11.log: https://gist.github.com/gort818/d8d094ab78ae883a0a572f7a16bb296e
- dxgi.log: https://gist.github.com/gort818/74cdddab11859e6d9e0b028dccf0df9e

**Comment by doitsujin** [comment]
Relevant bits:
> info:  Required Vulkan extension VK_KHR_get_physical_device_properties2 not supported
> info:  Required Vulkan extension VK_KHR_surface not supported

You're either missing a 32-bit Vulkan driver or loader package, this is not a bug.
