### ISSUE TITLE
The Sims 2 does not launch with DXVK 1.5

### ISSUE THREAD

**Issue by nelsonjchen** [doitsujin/dxvk#1289]
With the latest DXVK 1.5 which includes the changes from D9VK, The Sims 2 (and also at least its sister game The Sims Life Stories) no longer launches. Instead, this dialog appears.

![image](https://user-images.githubusercontent.com/5363/71053426-98321f80-210b-11ea-9ce8-ebcbe0db07cb.png)

https://github.com/Joshua-Ashton/d9vk/releases/tag/0.40.1 still works and does not present that dialog.

### Software information
The Sims 2 Ultimate Collection from Origin. 

### System information
- GPU: RTX 2080
- Driver: 441.41.0
- Wine version:  Windows 10 1903
- DXVK version: 1.5

### Apitrace file(s)
- TO DO? I can get more. I don't know if @Joshua-Ashton was joking or genuinely complaining about having too many of these. 

### Log files
- d3d9.log: https://gist.github.com/nelsonjchen/5395298b6d1ec6846a3f609b6c2762a4
- d3d11.log: None
- dxgi.log: None

**Comment by nelsonjchen** [comment]
@tannisroot mentioned to me that "why am I not affected on Linux? The hell".

**Comment by Joshua-Ashton** [comment]
Please try with `master`:
https://git.froggi.es/doitsujin/dxvk/-/jobs

**Comment by nelsonjchen** [comment]
The latest `master` works.

**Comment by Joshua-Ashton** [comment]
This isn't an issue then.

Sorry about the regression.
