### ISSUE TITLE
Risen 2 - inventory menu cut to the left and right

### ISSUE THREAD

**Issue by aufkrawall** [doitsujin/dxvk#1290]
DXVK:
![Screenshot_20191218_102956](https://user-images.githubusercontent.com/13510490/71075586-9ce6ea00-2184-11ea-87cf-0f4e77ed9b1b.png)

WineD3D/native:
![Screenshot_20191218_104453](https://user-images.githubusercontent.com/13510490/71075600-a1ab9e00-2184-11ea-84f8-1965ac12b095.png)

### Software information
Risen 2, maxed out visuals (except AA & DoF)
The Steam version btw. doesn't start due to copy protection, you need to _fix_ it or use GOG version.

### System information
- GPU: RX 570
- Driver: recent mesa 20 git aco
- Wine version: wine-staging-tkg 5.0
- DXVK version:  dxvk-mingw-git  1.5.r3.ga265af74

### Apitrace file(s)
https://drive.google.com/open?id=1NLGHjgnR567m2oiChddCGdj63qHRWhrQ
(Should be with wined3d, though my desktop folder was rather messy..)

### Log files
[Risen2_d3d9.log](https://github.com/doitsujin/dxvk/files/3977753/Risen2_d3d9.log)

**Comment by aufkrawall** [comment]
Confirmed, thanks!

**Comment by jarrard** [comment]
Why did this get closed? I still have this issue, real pain.

**Comment by K0bin** [comment]
I think the fix is in DXVK 1.5.

**Comment by Joshua-Ashton** [comment]
> hasn't been pushed out to any releases yet.

I don't close issues when they get published in a release, I close them when they reach `master`.
Builds for every commit can be found here: https://git.froggi.es/doitsujin/dxvk/-/jobs

**Comment by Joshua-Ashton** [comment]
@K0bin the fix isn't in 1.5
