### ISSUE TITLE
[D3D9] NFS Carbon: graphics issue

### ISSUE THREAD

**Issue by ViNi-Arco** [doitsujin/dxvk#1295]
### D9VK
http://www.img.tpx.cz/uploads/WITH%20D9VK.png
http://www.img.tpx.cz/uploads/WITH%20D9VK%202.png

### WineD3D
http://www.img.tpx.cz/uploads/WITHOUT%20D9VK.png
http://www.img.tpx.cz/uploads/WITHOUT%20D9VK%202.png

### Software information
Need for Speed: Carbon Collector's Edition (PC DVD), max settings with anti-aliasing.
With WineD3D it works correctly, with d9vk it has graphical issues, i have tested previous versions of d9vk and the same problem occurs.

### System information
- GPU: GTX 650 (Stock Clock)
- Driver: 440.36 (Linux)
- Wine version: 4.21
- DXVK version: v1.5-19-gfae99907

### Apitrace file(s)
- https://drive.google.com/open?id=1sHUHBgXRol-4oisU5UYLjtkH63TXC1Q8

### Log files
- [NFSC_d3d9.log](https://github.com/doitsujin/dxvk/files/3985517/NFSC_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Can you please try with native d3dx9 and d3dcompiler_43 and d3dcompiler_47
(You can use winetricks/protontricks)

**Comment by ViNi-Arco** [comment]
Thank you Joshie! Now it's working 100%, until my fps has increased, have a good night.

http://www.img.tpx.cz/uploads/NFSCarbonPrint01.png
http://www.img.tpx.cz/uploads/NFSCarbonPrint02.png

**Comment by ViNi-Arco** [comment]
After playing for a long time and completing 100% NFS Carbon, I came across some problems showing that installing the native version of 3dx9 and d3dcompiler_43 and d3dcompiler_47 by winetricks was not efficient:

Sometimes the texture error e is not rendered correctly:
http://www.img.tpx.cz/uploads/NFSCarbonBug01.png
http://www.img.tpx.cz/uploads/NFSCarbonBug02.png
http://www.img.tpx.cz/uploads/NFSCarbonBug03.png


I found that disabling MotionBlur solves the rendering problem:
Menu Conf:
http://www.img.tpx.cz/uploads/NFSC01.png
MotionBlur ON:
http://www.img.tpx.cz/uploads/NFSC02.png
MotionBlur OFF:
http://www.img.tpx.cz/uploads/NFSC03.png


There is a camera bug with D9VK that doesn't happen with WineD3D:
http://www.img.tpx.cz/uploads/NFSCarbon-D9VK.png
http://www.img.tpx.cz/uploads/NFSCarbon-WineD3D.png

**Comment by Joshua-Ashton** [comment]
Hi, please provide an apitrace for these bugs.

**Comment by Joshua-Ashton** [comment]
Please re-test and feel free to re-open if you find any more bugs.

**Comment by ViNi-Arco** [comment]
Hello Josh, playing for a while is what I could observe:

The problem with camera and cutscene have been fixed:
http://www.img.tpx.cz/uploads/NFSC-CanFix.png
http://www.img.tpx.cz/uploads/NFSC-CutsceneFix.png


But it may happen that I open Need For Speed and eventually the texture disappears and turns black:
http://www.img.tpx.cz/uploads/NFSCTextureBug01.png
http://www.img.tpx.cz/uploads/NFSCTextureBug02.png
http://www.img.tpx.cz/uploads/NFSCTextureBug03.png
http://www.img.tpx.cz/uploads/NFSCTextureBug04.png

**Comment by ViNi-Arco** [comment]
Hello Josh, playing for a while is what I could observe:

The problem with camera and cutscene have been fixed:
http://www.img.tpx.cz/uploads/NFSC-CanFix.png
http://www.img.tpx.cz/uploads/NFSC-CutsceneFix.png


But it may happen that I open Need For Speed and eventually the texture disappears and turns black:
http://www.img.tpx.cz/uploads/NFSCTextureBug01.png
http://www.img.tpx.cz/uploads/NFSCTextureBug02.png
http://www.img.tpx.cz/uploads/NFSCTextureBug03.png
http://www.img.tpx.cz/uploads/NFSCTextureBug04.png

**Comment by Joshua-Ashton** [comment]
Can you send me logs of a play session where this happened?

**Comment by ViNi-Arco** [comment]
Yes, here:

[NFSC_d3d9.log](https://github.com/doitsujin/dxvk/files/4041942/NFSC_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Hmmm, I'm not entirely sure why then...

**Comment by ViNi-Arco** [comment]
Me too, but there's one thing, I use it in my game:
https://github.com/AeroWidescreen/NFSCHDReflections

I think "maybe" this is not causing this problem, or is it?

**Comment by ViNi-Arco** [comment]
Hi Josh, I want to thank you for the support and say that the texture is gone and black because of the HD Reflections.

**Comment by Joshua-Ashton** [comment]
ah
