### ISSUE TITLE
[d3d9] Warhammer Online No support for SRGB read for B5G6R5 textures

### ISSUE THREAD

**Issue by xpander69** [doitsujin/dxvk#1296]
Ground textures (terrain) is overly bright. Fixed for wined3d with this patch:
https://bugs.winehq.org/attachment.cgi?id=66012

D9VK needs something similar also.

### Software information
Warhammer Online, settings low or high doesn't make any difference.

### System information
- GPU: GTX 1080Ti
- Driver: 440.43.01
- Wine version: 5.0rc1
- DXVK version: 1.5

### Apitrace file(s) (wined3d)
https://mega.nz/#!MOh2VKLb!7qOb_2KdSmX5wQi3UR1sodY0fQ8Yg8qdyt9Gi2372ro

### Log files
- d3d9.log:
[WAR-64_d3d9.log](https://github.com/doitsujin/dxvk/files/3990055/WAR-64_d3d9.log)

**Comment by sigzegv** [comment]
I want also to get that fix on d9vk :)

**Comment by xpander69** [comment]
It's now in wine since 5.1, without the need for patching. works with wined3d. 
DXVK still needs to support this.

**Comment by Joshua-Ashton** [comment]
We could emulate this in the shader but that's kinda stinky.

Would be nice to get proper format support for this...

**Comment by xpander69** [comment]
> We could emulate this in the shader but that's kinda stinky.
> 
> Would be nice to get proper format support for this...

Emulating is stinky for performance or just messy code?
Proper format to support i guess means new vulkan extension from khronos?

**Comment by Joshua-Ashton** [comment]
Both and yes

**Comment by xpander69** [comment]
Ok. If its simple to implement the emulation in shader, i would gladly help testing. But if its pointless then yeah better to wait for support from vulkan, if that ever even is considered being added to vulkan.

**Comment by xpander69** [comment]
Is there a easy way to make a dirty hack for it? like a separate dxvk version or something that breaks other games. i'm not good with the code so i have no idea how to do that. the thing is that i really would like to use vkbasalt or reshade with this game. with opengl reshade doesnt seem to work.

**Comment by SammyJames** [comment]
So I was able to temporarily get around this issue in WAR with a small tweak.

In d3d9_format.cpp `ConvertFormatUnfixed` I changed the returned mapping to the following and terrain looks normal now. This is probably not a viable fix. 

` case D3D9Format::R5G6B5: return {
        VK_FORMAT_R8G8B8A8_UNORM,
        VK_FORMAT_R8G8B8A8_SRGB,
        VK_IMAGE_ASPECT_COLOR_BIT};`

![Uploading Screenshot_2020-04-05_15-38-09.png…](Screenshot)

**Comment by Joshua-Ashton** [comment]
This is just a coincidence cause some stars are aligning and not a viable fix. Nice find though :P

**Comment by SammyJames** [comment]
Haha, yeah, this was mostly me stabbing in the dark around a code base I am unfamiliar with.

**Comment by xpander69** [comment]
thank you @SammyJames  :) workaround is fine for me :)
Works great for me :)

made a patch 
[war_srgb.patch.txt](https://github.com/doitsujin/dxvk/files/4439780/war_srgb.patch.txt)

**Comment by sigzegv** [comment]
thank you @SammyJames

**Comment by sxe** [comment]
Hey @SammyJames thx for "aligning the stars" :)
Works pretty good but there is one annoyance in the game. The minimap is not working correctly anymore. Looks like whenever a map (outside of buildings) is shown it's not rendered correctly. Inside it mostly works. 
Do you have any idea if this is fixable? Would be willing to get you a coffee as a sign of appreciationl. :joy:

**Comment by SammyJames** [comment]
I mean the first 'fix' is likely the culprit of the causing the second issue. I'll poke around and see what I can see.

**Comment by xpander69** [comment]
I tried few different things, but seems that the ground textures go bright when you give it  `VK_FORMAT_UNDEFINED` no matter what.. you can give loads of different things instead of this, then ground textures work correct but minimap is corrupted.
I tried for example `VK_FORMAT_R8G8B8_SRGB` , `VK_FORMAT_B8G8R8A8_SRGB` and VK_FORMAT_R8G8B8A8_SRGB` but all gave same results with ground textures fine and minimap corrupted. you dont even need the `VK_FORMAT_R8G8B8A8_UNORM`

all you need to replace is `VK_FORMAT_UNDEFINED` and the ground will work.

someone on DXVK discord suggested that the way to fix it would be to use compute shaders, cause vulkan dosent have the equivalent for this. But yeah i have no idea how to do that ofc :)

**Comment by xpander69** [comment]
Ok spoofing nvidia card as AMD will make the game use different techiques and it works with DXVK. Minimap is also fine.

https://cdn.discordapp.com/attachments/704023608816566434/704674615427072081/ss_28042020_15.39.56.jpg


dxvk.conf file with `d3d9.customVendorId = 1002` was all that was needed
