### ISSUE TITLE
[d3d8to9] C&C Generals: Unknown format encountered: 65

### ISSUE THREAD

**Issue by Comevius** [doitsujin/dxvk#1297]
C&C Generals is a d3d8 game that can be run with Wine without and with [d3d8to9](https://github.com/crosire/d3d8to9), but it runs better with it.

Since this works with Wine's d3d9 implementation I figured it should (probably) work with yours too.

### System information

- GPU: NVIDIA GeForce GTX 1050 Ti
- Driver: 440.44 (Arch Linux)
- DXVK version: v1.5

### Log files

- [game.dat_d3d9.log](https://github.com/doitsujin/dxvk/files/3990101/game.dat_d3d9.log)

**Comment by Joshua-Ashton** [comment]
So what is the problem with the game?

**Comment by Comevius** [comment]
> So what is the problem with the game?

A runtime error occurs (abnormal program termination) after the first intro video (the EA logo). When I remove DXVK the game works as expected with d3d8to9.

In both cases d3d8 is set to native, builtin for Wine to load d3d8.dll from the game directory.

**Comment by Joshua-Ashton** [comment]
Please try master

**Comment by Comevius** [comment]
> Please try master

The same thing happens.

### System information

- DXVK version: v1.5-20-g90ce37c8

### Log files

 - [game.dat_d3d9.log](https://github.com/doitsujin/dxvk/files/3990425/game.dat_d3d9.log)

**Comment by NerosTie** [comment]
I can confirm, this is what I have:

![Screenshot_20191221_000737](https://user-images.githubusercontent.com/4572452/71297983-fe29db80-2385-11ea-8cea-4c6fb7ee0548.png)

**Comment by ByCybernetik** [comment]
For normal operation d3d8to9 requires a library d3dx9_43.dll

**Comment by ByCybernetik** [comment]
I have the game working, but with stuttering.
![Screenshot_20191221_211111](https://user-images.githubusercontent.com/45942960/71312004-24f41a80-2437-11ea-84ae-12b0216ac10b.jpg)

**Comment by christianddietrich** [comment]
**System information**

    GPU: Intel HD 520
    Driver: Mesa 20.0.4 (Ubuntu 20.04)
    Wine: 5.6
    DXVK version: v1.6.0
    D3D8to9 version: v1.11.0  

**Log files**

    https://pastebin.com/gXbMtuCF
