### ISSUE TITLE
Cryostasis has missing text in menus and crashes on save loading [d3d9]

### ISSUE THREAD

**Issue by tannisroot** [doitsujin/dxvk#1298]
The game is missing text in menus and crashes after loading a save (at least when settings are set to High).
DXVK:
![Screenshot from 2019-12-21 02-25-57](https://user-images.githubusercontent.com/10602045/71298702-5f5baa00-239a-11ea-9482-1a1ce4a6fd94.png)
Wined3d:
![Screenshot from 2019-12-21 02-35-01](https://user-images.githubusercontent.com/10602045/71298732-903bdf00-239a-11ea-8226-5696c210bc07.png)
### System information
- GPU: GTX 1070
- Driver: 440.44
- Wine version: 5.0-rc1
- DXVK version: 90ce37c8

### Apitrace file(s)
dxvk trace with a crash: https://drive.google.com/open?id=1Fgfe45BsMTkBmvSESrLmeDkNINEDRVNt
wined3d trace (which misses text too even though it was present during recording): https://drive.google.com/open?id=1p2Z1l1QA8LCIQCsba-1KuSvNdiLDm7ge

### Log files
- dxgi.log: [cryostasis_dxgi.log](https://github.com/doitsujin/dxvk/files/3990686/cryostasis_dxgi.log)
- d3d9.log: [cryostasis_d3d9.log](https://github.com/doitsujin/dxvk/files/3990688/cryostasis_d3d9.log)
- d3d10.log: empty
- d3d11.log [cryostasis_d3d11.log](https://github.com/doitsujin/dxvk/files/3990690/cryostasis_d3d11.log)
- Wine's Backtrace: [backtrace_cryo.txt](https://github.com/doitsujin/dxvk/files/3990694/backtrace_cryo.txt)

**Comment by soredake** [comment]
@Joshua-Ashton hi, i have this game on steam and can share it to you via [family sharing](https://appuals.com/steam-library-sharing/) anytime!

**Comment by soredake** [comment]
Still a problem with wine 5.12 and dxvk 1.7

**Comment by zlice** [comment]
Same missing text but with Resident Evil 2 (RE2) Remake.
Uses, d3d11, not sure if it's related.
It's there for half a second, and then when the draw is finished it disappears.
Only seems to be the top left corner, can read some on the right and some, other menus show up like "Quit Game".

System information

    GPU: AMD Radeon RX 5700
    Driver: 2.0.151
    Kernel: 5.8-rc5 
    Wine version: 5.13

[re2_d3d11.log](https://github.com/doitsujin/dxvk/files/4951046/re2_d3d11.log)
[re2_dxgi.log](https://github.com/doitsujin/dxvk/files/4951047/re2_dxgi.log)

![re2_dxvk_missing_text](https://user-images.githubusercontent.com/8009811/88008500-68eaf300-cade-11ea-9a02-cfcf95995443.png)
![re2_dxvk_quit](https://user-images.githubusercontent.com/8009811/88008502-6a1c2000-cade-11ea-8b6d-e5a982ddc37f.png)


(unrelated note, if there's a way to hook the exit, where it sets the resolution back to what it was, plz lmk)

**Comment by K0bin** [comment]
RE2 is known to work. Please try installing d3dcompiler and latest RADV. Make a new issue if the problem persists.

**Comment by zlice** [comment]
RE2 issue resoled, had AMDVLK installed. Removed and text is back. (Mesa-20)

**Comment by soredake** [comment]
Still a problem with proton 6.4-GE-1

**Comment by soredake** [comment]
@Joshua-Ashton i still can share you this game via steam, there is no other way to get it legally otherwise.

**Comment by Joshua-Ashton** [comment]
I have the game and have looked into it before -- I have no idea what it doesn't like because it works in 640x480 but not any other resolutions. The crash on load appeared to be stack corruption inside the game itself also.

**Comment by Blisto91** [comment]
@tannisroot @soredake Is this an issue? I see the traces aren't available anymore

**Comment by soredake** [comment]
@Blisto91 unfortunately, disc version of the game is crashes for me, and i can't test steam version for now as installing steam & proton requires a lot of space in ram, and manjaro is heavy. I'll try to find more lightweight distro to test.

**Comment by soredake** [comment]
Yes, that's still a problem, tried with latest dxvk, still no text, still crashes at loading save. I tried to create apitrace, but game does not even showing anything.

Logs:
[Cryostasis_logs.zip](https://github.com/doitsujin/dxvk/files/9188456/Cryostasis_logs.zip)

**Comment by Blisto91** [comment]
@soredake Can you verify that both issues are fixed with this build? https://github.com/doitsujin/dxvk/actions/runs/2935435393

**Comment by soredake** [comment]
@Blisto91 yes, text is rendered correctly now and crash on loading save is gone, this can be closed.

**Comment by Bo9da** [comment]
4 me cryostasis just doesnt launch.... running russian cd license w 1.02 patch, extracted both dx10 dxgi dx9 files, removed dx9 one, nothing changed. Any help?

**Comment by Blisto91** [comment]
Make a new issue and fill out the template
