### ISSUE TITLE
Enforcing custom frame rates, vsync workaround for multi-monitor setups

### ISSUE THREAD

**Issue by trialism** [doitsujin/dxvk#1299]
Hi

I have two monitors with two different maximal v refresh rates: 60hz and 144hz. When I play on the 144hz one I only get fps>60 when I disable vsync. Is it possible that X11 itself limits the fps? If so, can we provide custom vsync info for dxvk games? I tried `dxgi.syncInterval = 1` but it limited my fps to 60 while `dxgi.syncInterval = 144` made my games super-slow.

**Comment by Joshua-Ashton** [comment]
What are your system specs?

What happens if you disconnect the 60Hz monitor?

What happens if you disable compositing?

**Comment by trialism** [comment]
Rtx 2080, manjaro kde.

Since there's only one 144hz monitor, vsync will enable 144fps if I restart the game.

Which compositor? Desktop compositors don't matter.

**Comment by doitsujin** [comment]
> while dxgi.syncInterval = 144 made my games super-slow.

Well yeah, setting the sync interval to 144 means that a game will only present one frame every 144 refresh cycles (so once every 2.4 seconds in your case).

Anyway, it's not DXVK that limits your FPS but something else in the graphics stack. I'm not aware of any workarounds, and it is literally impossible to fix this inside DXVK (like all Vsync-related issues).

**Comment by trialism** [comment]
@doitsujin I only opened this issue because dxgi.syncInterval solved a vsync-related issue for me once(in dark souls 3) and I thought that maybe someone could do some magic because dxvk seems to be pretty powerful but if you say so.
