### ISSUE TITLE
D3D11CreateDevice: Adapter is not a DXVK adapter

### ISSUE THREAD

**Issue by DestroyFX** [doitsujin/dxvk#13]
Hi there, I could not compile this module (Gentoo have the same problem than Ubuntu, failing to compile because no mutex...) So I did download the release precompiled bin.

I get that message in d3d11.log:
D3D11CreateDevice: Adapter is not a DXVK adapter

Tried with heaven and eve-online. Vulkan is supported (AMDGPU+RadeonSI)

**Comment by doitsujin** [comment]
In case of Heaven you need to set both d3d11.dll and dxgi.dll to `native`, **not** `native,builtin`. Otherwise, one of the libraries will load the dxgi.dll that ships with wine, which causes trouble.

As for Eve Online, probably the same issue, but I don't think it will work at this stage.

**Comment by doitsujin** [comment]
The new setup script in `master` fixes this for Heaven and will be included in the next binary release.
