### ISSUE TITLE
[d3d11] Killer Instinct hidden/missing textures

### ISSUE THREAD

**Issue by mimattr** [doitsujin/dxvk#1300]
Unfortunately it appears character models have hidden/missing textures during various in-game _Selection_ and _VS_ screens:
![Screenshot 1](https://i.imgur.com/b5HnqpJ.jpg)
![Screenshot 2](https://i.imgur.com/8BAHLKu.jpg)

_**NOTE:** This issue was also reported on the [Proton tracker](https://github.com/ValveSoftware/Proton/issues/348#issuecomment-568175835)._

### Software information
Name: **Killer Instinct**

### System information
- GPU: **GeForce RTX 2060**
- Driver: **NVIDIA 440.44**
- Wine version: **Proton 4.11-11**
- DXVK version: **1.5-16-g3b180e3bb**

### Apitrace file(s)
- [KillerInstinctX64_r.trace](https://send.firefox.com/download/98e654e07e55adcc/#X0z6zm2V6qr8Yv6VBYpb9A) (expires **December 27**)

### Log files
- [KillerInstinctX64_r_d3d11.log](https://gist.github.com/mimattr/e61d53e6b691831aba67ce888d3206f0)

**Comment by doitsujin** [comment]
> KillerInstinctX64_r.trace (expires December 27)

Please note that I don't plan to work over the holidays. I'll download the thing, but in general, don't expect any new bug reports to get noticed until next year.

**Comment by doitsujin** [comment]
@mimattr Firefox Send does not work, please upload the file on a different service.

**Comment by doitsujin** [comment]
The same thing happens on Windows when replaying your apitrace. Honestly this looks like some sort of game bug, since the game uses a different view-projection matrix for the depth pre-pass than for the color pass. It doesn't seem to be fixable in DXVK.

Might be worth testing if the same thing happens on Windows with DXVK.

**Comment by mimattr** [comment]
> Might be worth testing if the same thing happens on Windows with DXVK.

@doitsujin Thanks for looking into this so soon, currently not able to test on Windows but assuming the result is the same (i.e. visually incorrect) are you suggesting there's no path forward?

**Comment by doitsujin** [comment]
> but assuming the result is the same (i.e. visually incorrect) are you suggesting there's no path forward?

More like the opposite: If it **does** work on Windows, then the bug is definitely elsewhere. We do have some weird cases of that already, e.g. #1152, #444.

**Comment by SirBubbles** [comment]
I actually have some info on this. It seems more related to not having various versions of Visual C Runtime installed in your wine prefix. If you install something like "vcrun2015" in winetricks or protontricks, it should display correctly. 
There are, however, still serious issues with shadowing in the game, where they're too intense and buggy with no clear way to fix them.

**Comment by doitsujin** [comment]
I'll ask again, does this work correctly with DXVK on Windows?

**Comment by SirBubbles** [comment]
> I'll ask again, does this work correctly with DXVK on Windows?

I wouldn't know as of yet, that's for the original person you were communicating with. I was simply interjecting with something I thought was relevant.
I would imagine there's a chance that it wouldn't work correctly on windows though, as simply installing the right vcrun sorts it out.

**Comment by doitsujin** [comment]
I was asking about the shadowing issue you were having. I'm just having a hard time imagining that there are still very basic things not working correctly that are used in pretty much every single game.

**Comment by SirBubbles** [comment]
> I was asking about the shadowing issue you were having. I'm just having a hard time imagining that there are still very basic things not working correctly that are used in pretty much every single game.

Well I still don't have an answer for whether or not it works in Windows, sadly. I'd have to assume that it does, and that something else that I can't account for is at work. No combination of settings or tweaks has thus far managed to fix it, and I don't have much else that I can try.

**Comment by doitsujin** [comment]
That doesn't really look like a lighting issue but more like the exact same problem that already affects the main menu (i.e. failed depth tests because the game uses different MVP matrices).

**Comment by SirBubbles** [comment]
> That doesn't really look like a lighting issue but more like the exact same problem that already affects the main menu (i.e. failed depth tests because the game uses different MVP matrices).

Dangit. That's a tad unfortunate.

**Comment by mimattr** [comment]
Happy new year! :tada:

> If it **does** work on Windows, then the bug is definitely elsewhere. We do have some weird cases of that already, e.g. #1152, #444

The application appears to work as expected on Windows using either the native DX11 implementation or DXVK 1.5:

**Windows 10 (DX11/DXVK 1.5)**
![Screenshot 1](https://i.imgur.com/9UwU0An.jpg)

**Ubuntu 18.04 LTS (Proton 4.11-11/DXVK 1.5)**
![Screenshot 2](https://i.imgur.com/jWPq2ij.jpg)

### System information
- GPU: **GeForce RTX 2060**
- Driver: **NVIDIA 440.44 (Ubuntu 18.04 LTS)**, **NVIDIA 441.66 (Windows 10)**
- Wine version: **Proton 4.11-11**
- DXVK version: **1.5**

### Apitrace file(s)
- [KillerInstinctX64_r.windows10_dx11.trace](https://mega.nz/#!FtZiGKAT!KumXq5uKvMGa-cCYpBCD4sqGaHG1nqx8E4aiGUG3TqQ) (works as expected)
- [KillerInstinctX64_r.ubuntu1804_dxvk15.trace](https://mega.nz/#!tsRmkaYY!UNjFiAjBKhfHVlEPAoFYOIAEt0Pfi4YawOzOt99lKpE) (visual issues)

### Log files
**Windows 10**
- [KillerInstinctX64_r_d3d11.log](https://gist.github.com/mimattr/541ff183a782a877d64f218abecd9024) (works as expected)
- [KillerInstinctX64_r_dxgi.log](https://gist.github.com/mimattr/cf4f0f98fc15c95cae898c6b6d0d494d) (works as expected)

**Ubuntu 18.04 LTS**
- [KillerInstinctX64_r_d3d11.log](https://gist.github.com/mimattr/e61d53e6b691831aba67ce888d3206f0) (visual issues)

> I cannot say with any confidence what exactly the problem is.

Should this now be considered a Wine/Proton issue?

**Comment by vinifmor** [comment]
I have tested it with Lutris using the Wine Steam runner ( lutris-4.21 ). The textures are renderered properly.

**Comment by SirBubbles** [comment]
> I have tested it with Lutris using the Wine Steam runner ( lutris-4.21 ). The textures are renderered properly.

I seem to be able to confirm this, actually, with wine-4.21 (I think) and dxvk 1.5.

**Comment by SirBubbles** [comment]
I have screenies confirming that this bug no longer happens in my setup.
![image](https://user-images.githubusercontent.com/34481000/71893996-c9e15800-3198-11ea-96ae-6885db8bbf05.png)

![image](https://user-images.githubusercontent.com/34481000/71893952-a9190280-3198-11ea-8e21-346178410afb.png)

**Comment by mimattr** [comment]
This issue appears to be resolved with **Proton 5.0-1**

### System information
- GPU: **GeForce RTX 2060**
- Driver: **NVIDIA 440.59**
- Wine version: **Proton 5.0-1**
- DXVK version: **1.5.4**

Many thanks to all involved!
