### ISSUE TITLE
A Hat in Time Freezing Issue at 1080p

### ISSUE THREAD

**Issue by DarkSide1305** [doitsujin/dxvk#1302]
When I try to play A Hat in Time and run at 1080p (my Monitor is 1080p) the games freezes after 2 seconds. The game still works, the display is just frozen. Tabbing out of the game "updates" it, but it freezes after 2 seconds again. This problem doesnt happen at 1600x900

### Software information
A Hat in Time, 1920x1080, max Settings.

### System information
- GPU: R9 390
- Driver: 19.12.2
- Wine version: -
- DXVK version: 1.5

### Apitrace file(s)
- x

### Log files
- d3d9.log: [HatinTimeGame_d3d9.log](https://github.com/doitsujin/dxvk/files/3992594/HatinTimeGame_d3d9.log)
- d3d11.log: x
- dxgi.log: x

**Comment by Joshua-Ashton** [comment]
Works fine here... I'm assuming your native resolution is 1080p?

**Comment by DarkSide1305** [comment]
Yup.

**Comment by Joshua-Ashton** [comment]
Can you try with RADV?

**Comment by DarkSide1305** [comment]
RADV?

**Comment by Joshua-Ashton** [comment]
Are you on Windows or Linux?

**Comment by DarkSide1305** [comment]
Im also using Windows 10, which I didnt mention. (if that makes any difference)

**Comment by Joshua-Ashton** [comment]
Are you playing full screen?

**Comment by DarkSide1305** [comment]
Well, the game forces Borderless Window whenever I try to use 1920x1080. Windowsed, Borderless Window work at 1600x900. Fullscreen 1600x900 has the Freezing problem, and since 1920x1080 forces Fullscreen or Borderless Windowed, the Freezing problems appear there.

**Comment by Joshua-Ashton** [comment]
I can't repro the issue at 1920x1080 or at my native res (3840x2160)...

I'm using whatever the "Catalyst 2020" driver is.

**Comment by DarkSide1305** [comment]
Well, recently my AMD Driver had that massive overhaul. Like, a completely new revision of it. Its th Radeon 19.12.2 Driver

**Comment by Joshua-Ashton** [comment]
Yeah we are using the same driver. No idea then...

**Comment by DarkSide1305** [comment]
Thats... very weird.

**Comment by Joshua-Ashton** [comment]
Are you using a Windows Insider build? There was a DWM regression that could cause this there fairly recently...

**Comment by DarkSide1305** [comment]
Nope. I just looked at the Windows Inside Program and it tells me "First Steps" so I guess I dont?

**Comment by Joshua-Ashton** [comment]
Does this happen to you in other games with DXVK or Vulkan titles?

**Comment by DarkSide1305** [comment]
Uhhh.... I havent tested it on any other game so far, since only A Hat in Time gives me problems.

**Comment by DarkSide1305** [comment]
Also not sure which other game I could try it on lol

**Comment by Joshua-Ashton** [comment]
![image](https://user-images.githubusercontent.com/21316711/71324029-e52e4100-24d1-11ea-89bb-c2bb737b150b.png)

Yeah, I've tried every possible setting at different values and can't reproduce it at all.

The only thing I can think of is... can you try `master`? https://git.froggi.es/doitsujin/dxvk/-/jobs

**Comment by DarkSide1305** [comment]
Downloaded the newest master, #1054, and still the same Issue. Tried a restart but nope. Maybe its that weird Game Feature from the new AMD Driver?

**Comment by DarkSide1305** [comment]
I... fixed it. I had the Driver set to "Gaming". Setting it to "Standard" fixed the issue...
