### ISSUE TITLE
Very low FPS in The Sims 4

### ISSUE THREAD

**Issue by zaps166** [doitsujin/dxvk#1303]
Hi, I tried The Sims 4. I have very low performance with this game using D3D9:

![obraz](https://user-images.githubusercontent.com/6239090/71381277-12aee380-25d3-11ea-8fd8-d36d6a610b8d.png)

The game runs much faster with Wine OpenGL about 55 - 65 FPS.

CPU is i7-8700k, screenshot has all needed GPU info. Similar issue on AMD Radeon GPUs (IIRC Gallium Nine also runs faster).

**Comment by tannisroot** [comment]
Works ok for me with Esync and latest DXVK on maxed out Ultra settings:
![Screenshot from 2019-12-24 03-43-37](https://user-images.githubusercontent.com/10602045/71386560-bf9f5580-25ff-11ea-86b0-891af8680641.png)

**Comment by tannisroot** [comment]
WineD3D also seems to be quite slower. So not sure what's going on with your game.

**Comment by SamStrongg** [comment]
Try to run in windowed mode, turn off vsync or turn off any fps limit if it exists. Disable esync / fsync.

**Comment by zaps166** [comment]
Missing esync, now runs fine :) Thanks for help!

**Comment by yodatak** [comment]
Hi i got the same issue on GTX 970 and disabling esync and fsync didn't changed anything
I try this  on wine 5.5 on Fedora
export DXVK_HUD=full
export WINEFSYNC=0
export WINEESYNC=0
And i got 50 FPS and lag at some times did anything is wrong ?

**Comment by tannisroot** [comment]
Yes, you did the opposite of what is needed to make the game run well. *Enable* Esync and disable DXVK logging or at least leave it at default.
