### ISSUE TITLE
Halo PC retail release/demo version fails to start.

### ISSUE THREAD

**Issue by Vaporeon** [doitsujin/dxvk#1305]
While Halo Custom Edition works, the regular disc release of the game does not as they have slightly different renderers.
The free trial version of the game also does not work and uses the same renderer as the retail release.

### System information
- GPU: AMD RX 580
- Driver:Mesa/radv 19.3.1
- Wine version: wine-staging 5.0-rc2
- DXVK version: v1.5-27-gb4f2094

### Log files
- d3d9.log:
```info:  Game: halo.exe
info:  DXVK: v1.5-27-gb4f2094
info:  Found built-in config:
info:  Effective configuration:
info:    d3d9.customVendorId = 1002
info:    d3d9.customDeviceId = 4172
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  AMD RADV POLARIS10 (LLVM 9.0.0):
info:    Driver: 19.3.1
info:    Vulkan: 1.1.107
info:    Memory Heap[0]: 
info:      Size: 7936 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:    Memory Heap[2]: 
info:      Size: 8192 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:  Process set as DPI aware

**Comment by K0bin** [comment]
Please make an apitrace. It's impossible to fix without one.

**Comment by Vaporeon** [comment]
[halo.zip](https://github.com/doitsujin/dxvk/files/3998931/halo.zip)

**Comment by doitsujin** [comment]
The trace is empty. Please **disable** dxvk to record it, or better yet, record it on Windows if you have access to a Windows system.

**Comment by Vaporeon** [comment]
https://cdn.discordapp.com/attachments/375392801539620876/659392028903211018/halotrial-d3d9trace.7z

When playing back the trace it shows a black screen and I am not sure why. hopefully this is still useful.

**Comment by Vaporeon** [comment]
Here is another trace file that does not show a black screen, however the game is now using its "DisableAlphaRenderTargets" option and will look visually wrong in this trace, but it works.

https://cdn.discordapp.com/attachments/375392801539620876/659451803879866398/halotrial-d3d9trace2.7z

**Comment by Joshua-Ashton** [comment]
Hm, trace replays fine...

Looks like I'll need to try this myself to fix it.

**Comment by NerosTie** [comment]
I have the retail version installed and it works very well.

But I just tested the [demo](https://halo.fr.uptodown.com/windows/telecharger) with DXVK 1.5.4 and I have this bug:

![Screenshot_20200207_111015](https://user-images.githubusercontent.com/4572452/74020707-6c5c4900-499a-11ea-9a67-988040b12976.png)

It's the same bug as this one:
https://github.com/Joshua-Ashton/d9vk/issues/388

But there is one difference, with the demo it tells me I have an ATI Radeon 9600, which is not the case, it should detect a Nvidia GPU.

[halo_demo.log](https://github.com/doitsujin/dxvk/files/4170144/halo_demo.log)

I'll make an apitrace later if needed.

**Comment by Joshua-Ashton** [comment]
@NerosTie The EXE name is `halo_demo.exe`? Looks like we need to add that to the app compat profiles perhaps.

**Comment by NerosTie** [comment]
No, `halo.exe` too...

**Comment by Joshua-Ashton** [comment]
ofc.... bleh ok

**Comment by Joshua-Ashton** [comment]
The trial version works fine here.

**Comment by Joshua-Ashton** [comment]
> But there is one difference, with the demo it tells me I have an ATI Radeon 9600, which is not the case, it should detect a Nvidia GPU.

No, it detecting that GPU is 100% intentional.

**Comment by Vaporeon** [comment]
Closing this as the game runs as expected.

Game performance with is rather low using only DXVK compared with running dgVoodoo2 to wrap the d3d9 and DXVK to wrap dgVoodoo's d3d11 output, I'm not sure if I should open that as an issue though but I don't think adding another wrapper to the mix should be faster that using pure DXVK, it should be the other way around.
