### ISSUE TITLE
Nature Treks VR [587580] black screen but works with WINED3D

### ISSUE THREAD

**Issue by frostworx** [doitsujin/dxvk#1306]
Merry Christmas! :)
just found out that "Nature Treks VR" works with PROTON_USE_WINED3D=1 (stuttering though)
but only draws a black screen with dxvk. This only happens when SteamVR is running.
With SteamVR disabled the in game menu is also drawn correctly on the Desktop Window (can't control it though, then, so can't test it further).
The only err in the debug log is
err:   DXGI: SetGPUThreadPriority: Ignoring
(doesn't appear when SteamVR is disabled).

### Software information
Nature Treks VR [587580]
https://store.steampowered.com/app/587580/Nature_Treks_VR

### System information
- GPU: GeForce RTX 2080
- Driver: nvidia-dkms-440.44-5
- Wine version: wine-4.11 (from proton-4.11-11)
- DXVK version: v1.5 (from proton-4.11-11)

### Log files
- d3d11.log (with steamvr enabled)
[Nature Treks VR_d3d11-withSteamVR.log](https://github.com/doitsujin/dxvk/files/3998577/Nature.Treks.VR_d3d11-withSteamVR.log)

**Comment by K0bin** [comment]
Please add an apitrace. It is impossible to debug this without one.

**Comment by frostworx** [comment]
didn't think that I'd get an answer so soon, thx.
I don't have windows so I put x64 builds (game is 64 bit) of d3d11.dll, dxgi.dll and dxgitrace.dll to the exe and launched it with
WINEDLLOVERRIDES="dxgi,dxgitrace,d3d11,d3d10,d3d9=n,b" PROTON_LOG=1 %command%
(with enabled steamvr)
the game doesn't crash but simply doesn't draw anything, so I forcefully quit it after some seconds.
I hope the trace helps.
[trace.zip](https://github.com/doitsujin/dxvk/files/4000191/trace.zip)

**Comment by frostworx** [comment]
The app works excellent with current dxvk and clean protonprefix with proton-4-11-12!
thank you very much doitsujin!

**Comment by frostworx** [comment]
fyi: looks like it wasn't a dxvk change which fixed this, but a vulkan change in a previous nvidia vulkan beta driver.
now with stable nvidia-440.59 it works again ootb.
