### ISSUE TITLE
[d3d9] Kane & Lynch: Dead Men (8080) Unhandled render state D3DRS_ADAPTIVETESS_Y

### ISSUE THREAD

**Issue by pchome** [doitsujin/dxvk#1307]
The FOURCC value is **KanL**. I doubt it used somewhere in drivers, it looks like it was either for debugging purposes or to be treated as `D3D9Format::Unknown` (Edit: I mean "and applied with D3DRS_ADAPTIVETESS_Y". Name likely was "invented" to be unsupported format.).

Out of curiosity I created a hack to accept this format (where `D3D9Format::ATOC` check is in current code)
https://github.com/doitsujin/dxvk/blob/b4f2094c02bea9b241f558a1c1888ba28a88d3f0/src/d3d9/d3d9_device.cpp#L1695-L1697
and there is indeed noticeable difference (see screenshots). Actually I don't know what I'm doing, so this bug report is FYI.

#### Before
![KanL-default](https://user-images.githubusercontent.com/10661854/71434355-c5269980-26ec-11ea-9ecf-33c8ef697723.png)

#### After
![KanL-hack](https://user-images.githubusercontent.com/10661854/71434361-ce176b00-26ec-11ea-9ec2-4b2e1bf8a4c0.png)

### Software information
- Native dlls: d3dx9_31, d3dcompiler_47, d3dx9_34.dll (present in game's installdir)
- GFWL: xliveless (Bundled version failed to install)
- Maxed settings (upped to AA:8/AF:16).

### System information
- Wine version: Proton-4.11-11 (local build)

### Apitrace file(s)
- 'll try to do on request

### Log files
- d3d9.log: [kaneandlynch_d3d9.log](https://github.com/doitsujin/dxvk/files/3999667/kaneandlynch_d3d9.log)

**Comment by Joshua-Ashton** [comment]
What you linked to was just my code for ADAPTIVENESS_Y and ATOC?

**Comment by Joshua-Ashton** [comment]
IDK what KanL is meant to do, I imagine its meant to signify to the driver that this is **Kan**e and **L**ynch for drive hacks.

Is there an actual problem with the game btw?

**Comment by pchome** [comment]
> What you linked to was just my code for ADAPTIVENESS_Y and ATOC?

Yes, for context.

> Is there an actual problem with the game btw?

No, the game works good.

**Comment by Joshua-Ashton** [comment]
This isn't a bug then.

If there's any difference on native drivers that's noticable, let me know.
(ie. does it look like ATOC or another feature is enabled?)

**Comment by pchome** [comment]
AMD variant. Just for the record[^1]. No LOD-Bias hack or sharpening unlike the initial screenshots.

<img width="400" height="225" alt="Image" src="https://github.com/user-attachments/assets/bb10b992-3670-4bac-a618-6ce021f90d38" /> <img width="400" height="225" alt="Image" src="https://github.com/user-attachments/assets/bca356d2-151d-419f-997c-dec4e60e114e" />

The hack (ported to dxvk-2.7.1): 

[KanL-ATOC.patch](https://github.com/user-attachments/files/28848627/KanL-ATOC.patch)

[^1]: @WinterSnowfall thought about what to do with the game-specific hacks after #4888, so more info if this still relevant ...
