### ISSUE TITLE
[d3d9] Halo CE -> Meter state inverted (And some other things)

### ISSUE THREAD

**Issue by gbMichelle** [doitsujin/dxvk#1309]
Heat meters on plasma weapons show in an on state instead of their off state and vice versa. Btw, you will see that in the native screenshots that a material in the background is almost chrome. That is normal for the rendering mode that I had to put the game in to be able to make a trace that isn't black.

This one needs a few frames.
Frame 105 Native:
![haloce 26 trace_frame_105-1_0](https://user-images.githubusercontent.com/24233409/71448237-bf0ada00-2739-11ea-81ab-faffe976c960.png)
Frame 105 DXVK:
![haloce 26 trace_frame_105-1_1](https://user-images.githubusercontent.com/24233409/71448243-cc27c900-2739-11ea-9dd0-aada88d955fc.png)
Frame 110 Native:
![haloce 26 trace_frame_110-1_0](https://user-images.githubusercontent.com/24233409/71448246-d649c780-2739-11ea-98b8-d856e6ce88bc.png)
Frame 110 DXVK:
![haloce 26 trace_frame_110-1_1](https://user-images.githubusercontent.com/24233409/71448248-dd70d580-2739-11ea-827e-78ae5e20255d.png)
Frame 130 Native:
![haloce 26 trace_frame_130-1_0](https://user-images.githubusercontent.com/24233409/71448249-e497e380-2739-11ea-8004-a9edca77da74.png)
Frame 130 DXVK:
![haloce 26 trace_frame_130-1_1](https://user-images.githubusercontent.com/24233409/71448253-f083a580-2739-11ea-97ef-3acccac8510a.png)

### Software information
Halo CE - DisableAlphaRenderTargets

### System information
- GPU: GTX 1060
- Driver: 
- Wine version: Happens on all platforms
- DXVK version: b4f2094c

### Apitrace file(s)
- https://drive.google.com/open?id=1_K18uC2LezYunf7O464-4nkP3wK5gJ26

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by Vaporeon** [comment]
Does DART allow the creation of working traces?

**Comment by gbMichelle** [comment]
Yep. I had to uninstall Chimera to do so as Chimera blocks DART.

**Comment by Vaporeon** [comment]
Ah ok. I just commented that blocker out.

**Comment by gbMichelle** [comment]
Fixed with 724fe78
