### ISSUE TITLE
Games no longer start with DXVK after upgrading to Wine Staging 3.3.

### ISSUE THREAD

**Issue by Kerrung** [doitsujin/dxvk#131]
Hi! Thank you very match for your greatest, important and in-demand work! I believe that the DXVK project has a great future!

With Wine Staging 2.21 games at least tried to start, without giving out at the same time messages about errors of missing libraries. But after the upgrade to Wine Staging 3.3 games no longer run, giving out messages about the missing libraries. I believe that this may have been caused by add in Wine Staging 3.3 a completely new Vulkan 1.0.51 icd implementation and deletion of the old "Vulkan hack" non-icd implementation, which was in Wine Staging 2.21 and other previous versions of the Wine Staging. But it's probably that the DXVK is not yet fully compatible with this new Wine-Vulkan implementation. Here's what I see now when trying to run any game with DXVK and Wine Staging 3.3:

$ env WINEPREFIX=~/.wine wine64 start /unix '/home/user/.wine/drive_c/Program Files (x86)/World of Warcraft/Wow-64.exe'
000b:fixme:winediag:start_process Wine Staging 3.3 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
002f:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
0031:fixme:ver:GetCurrentPackageId (0x29cfdc0 (nil)): stub
002f:fixme:kerberos:kerberos_SpInstanceInit 65536,0x7f21cd9657a0,(nil): stub
002f:fixme:mpr:WNetGetUniversalNameW (L"C:\\Program Files (x86)\\World of Warcraft\\data\\data", 0x00000001, 0x23c730, 0x23c6f0): stub
0034:fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
0034:fixme:winhttp:WinHttpDetectAutoProxyConfigUrl discovery via DHCP not supported
002f:err:module:import_dll Library vulkan-1.dll (which is needed by L"C:\\windows\\system32\\d3d11.dll") not found
002f:err:module:import_dll Library vulkan-1.dll (which is needed by L"C:\\windows\\system32\\dxgi.dll") not found
002f:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\windows\\system32\\d3d11.dll") not found
002f:err:module:import_dll Library vulkan-1.dll (which is needed by L"C:\\windows\\system32\\d3d11.dll") not found
002f:err:module:import_dll Library vulkan-1.dll (which is needed by L"C:\\windows\\system32\\dxgi.dll") not found
002f:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\windows\\system32\\d3d11.dll") not found

I used both x64 setup_dxvk.sh and x32 setup_dxvk.sh in this fully FRESH wine prefix.

### Software information
World of Warcraft or any other d3d11 game.

### System information
Arch Linux with latest updates
- AMD Radeon HD7770;
- Linux 4.16-rc4 amdgpu+Mesa 17.3.6, packages vulkan-radeon lib32-vulkan-radeon vulkan-icd-loader installed;
- Wine Staging 3.3 
- DXVK 0.30 release: 

### Apitrace file(s)
- Probably, not need in my case;

### Log files
- d3d11.log: I don't have it;
- dxgi.log: 
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  DxgiAdapter: DXGI_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
err:   DxgiAdapter::CheckInterfaceSupport: No D3D10 support
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  DxgiAdapter: DXGI_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
err:   DxgiAdapter::CheckInterfaceSupport: No D3D10 support
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  DxgiAdapter: DXGI_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
err:   DxgiAdapter::CheckInterfaceSupport: No D3D10 support
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  DxgiAdapter: DXGI_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  Enabled device extensions:
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
warn:  DxgiFactory::QueryInterface: Unknown interface query

**Comment by fagoatse** [comment]
Because it's still WIP. 

> Note: As of wine 3.3, wine-mainline and wine-staging do not support the required Vulkan features yet.

**Comment by doitsujin** [comment]
As mentioned in the README, wine-staging 3.3 does not support Vulkan anymore, unlike earlier staging versions. You'll have to use `wine-vulkan` until full Vulkan support lands in mainline.
