### ISSUE TITLE
D9VK: Starcraft 2 units and buildings have no shadows. Croak!

### ISSUE THREAD

**Issue by EldarAgalarov** [doitsujin/dxvk#1313]
Hi. Starcraft 2 works fine with D9VK (now with DXVK), but units and buildings has no shadows. It looks like they are flying above surface. In Wine D3D9 implementation shadows exists, but FPS 2 times slower.

**Comment by Joshua-Ashton** [comment]
This is a known issue and is already tracked at https://github.com/Joshua-Ashton/d9vk/issues/85.
