### ISSUE TITLE
Grand Theft Auto V runs at 10 FPS with vsync enabled

### ISSUE THREAD

**Issue by mrpippy** [doitsujin/dxvk#1314]
Starting with DXVK 1.5, Grand Theft Auto V's opening movie (Rockstar logo) and menus always run at 8-10 FPS. With VSync enabled, the game itself also runs at 10 FPS. With VSync disabled, the game runs normally (60-80 FPS for me). Some people have also found that the borderless window setting restores normal performance: https://github.com/ValveSoftware/Proton/issues/37#issuecomment-567450992.

I was able to bisect the problem down to commit aa40decc.
I can post an apitrace tomorrow.

### Software information
Grand Theft Auto V, from Steam. Build 1868, Online 1.50.
DirectX 11 mode.

### System information
- GPU: GTX 1060 3GB
- Driver: 440.44.0
- Wine version: Proton 4.11-11
- DXVK version: 1.4.6 works normally. 1.5 and master have the problem

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log: empty
- d3d11.log: [GTA5_d3d11.log.gz](https://github.com/doitsujin/dxvk/files/4018103/GTA5_d3d11.log.gz)
- dxgi.log: using Wine DXGI

**Comment by doitsujin** [comment]
Sounds like the game thinks it's minimized for whatever reason. Not sure if there's much I can do there.

I know that GTA V uses PRESENT_TEST before every "real" present, but that should still work just fine.

**Comment by doitsujin** [comment]
Can you test if [this](https://github.com/doitsujin/dxvk/tree/dxgi-present-test) fixes the problem?

We should never return `DXGI_STATUS_OCCLUDED` to the application unless the application window is minimized, but this should fully restore the behaviour before aa40dec.

**Comment by aufkrawall** [comment]
I can't confirm this issue with DXVK git-master in wine-tkg (75Hz):
![Screenshot_20200103_183406](https://user-images.githubusercontent.com/13510490/71738786-ff640980-2e57-11ea-901a-ebce0cbe2a07.png)

But the in-game vsync option is heavily bugged and may jump to half rate, which capped it to 39fps for me (something seems odd about that math), despite of forcing vsync via DXVK. I had to set it to off and restart the game to make it work.

@doitsujin The non-Steam version with just Rockstar Game Launcher should work with the corresponding community patches for wine-tkg:
https://github.com/Tk-Glitch/PKGBUILDS/tree/master/community-patches/wine-tkg-git

**Comment by mrpippy** [comment]
> Can you test if [this](https://github.com/doitsujin/dxvk/tree/dxgi-present-test) branch fixes the problem?
> 
> We should never return `DXGI_STATUS_OCCLUDED` to the application unless the application window is minimized, but this should fully restore the behaviour before [aa40dec](https://github.com/doitsujin/dxvk/commit/aa40decc23f27bcb25bd8e61a76c032fd99ada59).

I tried the branch, it didn't fix the issue. I tried reverting other parts of the patch though, and found that adding the `PRESENT_TEST` check back into `DxgiSwapChain::Present1` does fix it:  https://github.com/doitsujin/dxvk/commit/aa40decc23f27bcb25bd8e61a76c032fd99ada59#diff-ba6fe080f093adac8573732dd035e363

Without that, the while loop in `PresentImage` is regularly looping because of `status == VK_NOT_READY`

**Comment by doitsujin** [comment]
I'm not sure I understand. `PresentImage` is never called when `PRESENT_TEST` is being used.

**Comment by doitsujin** [comment]
Does #ae01bd8 fix the problem? I don't know if the game runs into that issue but it's a genuine bug regardless.

**Comment by andrew-mcmahon** [comment]
I believe that fixes V-Sync for me - at least with VSYNC = Full.  
https://imgur.com/a/HikXstk  

I've compiled the latest and replaced the DXVK files **Proton-4.21-GE-2** comes bundled with - those are found in:
```
/home/mwnn/.steam/steam/compatibilitytools.d/Proton-4.21-GE-2/dist/lib64/wine/dxvk/
/home/mwnn/.steam/steam/compatibilitytools.d/Proton-4.21-GE-2/dist/lib/wine/dxvk/
```
I don't need to apply the workaround with the dxvk.conf file any longer.
60 frames a second is the max on my ASUS PB238Q.  
[settings.txt](https://github.com/doitsujin/dxvk/files/4022116/settings.txt)

**Comment by mrpippy** [comment]
> Does [ae01bd8](https://github.com/doitsujin/dxvk/commit/ae01bd8bd40cd8dbcc35dfedbabe9624d31fa72e) fix the problem? I don't know if the game runs into that issue but it's a genuine bug regardless.

Yep that fixes the problem for me too, thanks!
