### ISSUE TITLE
Random Crashes in A Hat in Time

### ISSUE THREAD

**Issue by DarkSide1305** [doitsujin/dxvk#1315]
In some Areas, mostly the "Seal the Deal" Purple Time Rift as far as I can judge, the game randomly crashes. The Game gets stuck and I have to forcefully close out of the game.

### Software information
A Hat in Time, 1920x1080, Borderless Window, Highest Settings with Anti Aliasing to 4, Motion Blur turned off an FXAA2

### System information
- GPU: R9 390
- Driver: 19.12.2
- Wine version: Using Windows
- DXVK version: 1.5

### Apitrace file(s)
- x

### Log files
- d3d9.log: 
[HatinTimeGame_d3d9.log](https://github.com/doitsujin/dxvk/files/4019628/HatinTimeGame_d3d9.log)
- d3d11.log: x
- dxgi.log: x

**Comment by Joshua-Ashton** [comment]
Do you happen to have a backtrace from the crash?

**Comment by DarkSide1305** [comment]
Sadly not. Sorry, I forgot to respond. I tested out the new master build, and had no problems anymore.

**Comment by Joshua-Ashton** [comment]
Ah yeah, there was a fix for a regression in Hat in there iirc.
