### ISSUE TITLE
[d3d11] Redout crashes on launch (Windows 10)

### ISSUE THREAD

**Issue by mimattr** [doitsujin/dxvk#1321]
Using the DXVK 1.5 binaries on Windows 10 results in an application crash at launch:

![Crash Screenshot](https://i.imgur.com/z8c0666.png)

Fortunately Linux appears to work as expected but perhaps there's an underlying issue worth investigating?

### Software information
- Name: **Redout: Enhanced Edition**

### System information
- GPU: **GeForce RTX 2060**
- Driver: **NVIDIA 440.44**
- Wine version: **Proton 4.11-11**
- DXVK version: **1.5**
- SteamVR version: **1.9.16**

### Apitrace file(s)
- [redout-Win64-Shipping.windows10_dx11_steamvr.trace](https://mega.nz/#!0hxkHaRJ!17MVWXdNWChKQHBCjrlOLmTLcC_1ECXl3rG9RPBXCig) (works as expected)
- [redout-Win64-Shipping.ubuntu1804_dx11_steamvr.trace](https://mega.nz/#!8tZECYqC!2bD0hVrREhgkqfB4sNZI0plGgbARbMn9WAUaMDP8pGk) (works as expected)

### Log files
- [redout-Win64-Shipping_dxgi.windows10_dxvk15_steamvr.log](https://github.com/doitsujin/dxvk/files/4024019/redout-Win64-Shipping_dxgi.windows10_dxvk15_steamvr.log) (launch issue)
- [redout-Win64-Shipping_d3d11.windows10_dxvk15_steamvr.log](https://github.com/doitsujin/dxvk/files/4024018/redout-Win64-Shipping_d3d11.windows10_dxvk15_steamvr.log) (launch issue)
- [redout-Win64-Shipping_d3d11.ubuntu1804_dxvk15_steamvr.log](https://github.com/doitsujin/dxvk/files/4024021/redout-Win64-Shipping_d3d11.ubuntu1804_dxvk15_steamvr.log) (works as expected)
- [steam-517710.ubuntu1804_proton411-11_steamvr.log](https://github.com/doitsujin/dxvk/files/4024022/steam-517710.ubuntu1804_proton411-11_steamvr.log) (works as expected)

**Comment by doitsujin** [comment]
If Linux works then there's no DXVK issue, plain and simple.

**Comment by TheLastRar** [comment]
I believe the issue is that it works on windows with native, but not on windows with dxvk. This does strike me as a dxvk bug even if it only occurs on windows

**Comment by mimattr** [comment]
> this would require the SteamVR runtime to support DXVK.

@doitsujin Unfortunately this issue is consistent whether using VR or not. Perhaps something is broken/missing under-the-hood?

### Apitrace file(s)
- [redout-Win64-Shipping.windows10_dx11.trace](https://mega.nz/#!IxoFES7B!qGc52NRyLftCg17o-TvHJG2tS6BJYMr9O-RjmevCyz8) (works as expected)

### Log files
- [redout-Win64-Shipping_dxgi.windows10_dxvk15.log](https://github.com/doitsujin/dxvk/files/4026124/redout-Win64-Shipping_dxgi.windows10_dxvk15.log) (launch issue)
- [redout-Win64-Shipping_d3d11.windows10_dxvk15.log](https://github.com/doitsujin/dxvk/files/4026126/redout-Win64-Shipping_d3d11.windows10_dxvk15.log) (launch issue)

**Comment by doitsujin** [comment]
I really don't care about Windows-only issues. If it works on Linux, it is not a DXVK bug, period.

99% of the time, if a non-VR app doesn't work, it's because the game loads Windows' DXGI and DXVK's D3D11, or the other way around, and no amount of code is ever going to fix that. This issue simply doesn't exist on Linux since DXVK *replaces* the "system" implmentation of those libraries.

**Comment by mimattr** [comment]
> 90% of the time, if a non-VR app doesn't work, it's because the game loads Windows' DXGI and DXVK's D3D11, or the other way around

> There are also some games that load AMD AGS or NVAPI libraries on Windows, which then explode when using DXVK.

Appreciate the explanation, wasn't aware how volatile other libraries may behave with DXVK (likely the issue here.)
