### ISSUE TITLE
BeamNG.drive abysmal performance with DXVK enabled

### ISSUE THREAD

**Issue by saikat0511** [doitsujin/dxvk#1322]
I get stable 25-30 fps when running the game without DXVK. With DXVK enabled max fps triples (depends on map) but the game freezes and drop frames every second making it literally unplayable. I tried with some other wine version and the results were similar.
Something I noticed is when the game is running fine the gpu usage is around 90-100%, and when it freezes gpu usage drops to 10-20%. 

### Software information
BeamNG.drive, 1980x1080 high preset

### System information
- GPU: GTX 1060 3GB
- Driver: 440.44
- Wine version: Proton 4.11 (Tested with several others same issue)
- DXVK version: 1.5

### Apitrace file(s)
- Could not capture unfortunately..

### Log files
- d3d9.log: [Empty file]

- d3d11.log:
[BeamNG.drive.x64_d3d11.log](https://github.com/doitsujin/dxvk/files/4025000/BeamNG.drive.x64_d3d11.log)

- dxgi.log:
[BeamNG.drive.x64_dxgi.log](https://github.com/doitsujin/dxvk/files/4025007/BeamNG.drive.x64_dxgi.log)

**Comment by saikat0511** [comment]
Sorry I did not mentioned it earlier, I am Pop OS 19.10 with the the pre-installed proprietary nvidia drivers

**Comment by doitsujin** [comment]
I know others had this problem before and it's not a DXVK issue. No idea how to fix it though.

**Comment by saikat0511** [comment]
My specs are as follows:
- CPU: Intel i5 7400
- GPU: GTX 1060 3GB
- RAM: 16GB 2400HZ Single Channel

I think this more than enough for this game to perform decent as it works fine in windows
Also this frametimes graph pretty much describes my problem....

![new](https://user-images.githubusercontent.com/57610828/71826357-ba440f80-30c3-11ea-9da5-5e572d7d2d0a.jpg)

**Comment by doitsujin** [comment]
Can you try lowering texture quality or something to reduce VRAM utilization?

wined3d benefits from very sophisticated memory management in OpenGL drivers, whereas DXVK's memory management is fairly stupid, and on Nvidia, there's the added difficulty that the amount of VRAM allocated by **other** applications (Steam, web browser running in the background) is **not** available to DXVK either, so 2.2GB could be too much already.

**Comment by saikat0511** [comment]
Ok it seems that I have solved the issue. The culprit was IRQBALANCE which is enabled by deault in Pop OS (dunno about other distros). TBH I stumbled upon this by pure luck while looking into cpufreq gnome extension. 

I disabled irqbalance using `sudo apt-get remove irqbalance`
Rebooted once and the issue is COMPLETELY gone !!
I am a happy man now :)
![Screenshot from 2020-01-06 22-04-05](https://user-images.githubusercontent.com/57610828/71833408-d56a4b80-30d2-11ea-9d30-999448a492b0.jpg)


I suggest you put this info in the faq section, might help some other people...

Some some threads regarding this...
http://konkor.github.io/cpufreq/faq/#irqbalance-detected
https://github.com/konkor/cpufreq/issues/48
https://github.com/pop-os/default-settings/issues/60

**Comment by doitsujin** [comment]
Huh, interesting. This sounds like a very system-specific problem however, even on systems with irqbalance active.

You might still be running out of VRAM however, 381MB sysmem seems a bit high just for constant buffers + staging buffers alone. Just in case performance still isn't where you'd expect.

**Comment by saikat0511** [comment]
I am certainly not the only one having this problem, some on Ubuntu 18.04 was having the same problem..
https://askubuntu.com/questions/1067866/ubuntu-18-04-steam-games-frame-rate-drop

Anyways thanks for trying to help, dxvk works great too !!
