### ISSUE TITLE
[D3D9]Half Life 2 shadow maps problem

### ISSUE THREAD

**Issue by DaRkL3AD3R** [doitsujin/dxvk#1325]
When close to objects the shadows drawn from the flashlight clip wrongly.
Native D3D9: https://i.imgur.com/iobHSQJ.png
DXVK 1.5: https://i.imgur.com/ydKCC3y.png
The issue is most obvious when you are close to an object.

### System information
- GPU: 1080 Ti
- Driver: 441.87 (present on earlier versions too)
- DXVK version: 1.5

### Apitrace file(s)
- https://www.mediafire.com/file/rxb1xcu11vserc7/hl2.zip/file

### Log files
- d3d9.log: https://www.mediafire.com/file/wtyyjzmm0ipwm07/hl2_d3d9.log/file

**Comment by DaRkL3AD3R** [comment]
Another example, note the missing shadows through the grate.
Native D3D9: https://i.imgur.com/eXqw760.png
DXVK 1.5: https://i.imgur.com/V2KmfvR.png

**Comment by Joshua-Ashton** [comment]
This is depth bias and needs an extension to work properly.

**Comment by Joshua-Ashton** [comment]
Please re-test with: https://github.com/doitsujin/dxvk/commit/b738c4220b7f2ea71cf2f1f61521a08606ee7022

**Comment by DaRkL3AD3R** [comment]
Problem solved 👍
