### ISSUE TITLE
dxvk and vulkan version

### ISSUE THREAD

**Issue by RDL-28** [doitsujin/dxvk#1326]
My system has vulkan version 1.1.130 installed, why does dxvk show that I have version vulkan 1.1.119?
![image_1](https://user-images.githubusercontent.com/33255217/71944466-2e3b0080-3207-11ea-848b-03ee498855d2.jpg)
![image_2](https://user-images.githubusercontent.com/33255217/71944465-2da26a00-3207-11ea-8f51-9863f8133815.jpg)
![image_3](https://user-images.githubusercontent.com/33255217/71944464-2da26a00-3207-11ea-99b0-dc354182a2f8.jpg)

**Comment by doitsujin** [comment]
Because that's the version the **driver** was written against.
