### ISSUE TITLE
GW2 flickering texture with 1.5.1

### ISSUE THREAD

**Issue by logan001** [doitsujin/dxvk#1329]
With 1.5.1 seems to be some flickering in textures when you rotate camera. 
i've tested the game in windows too. and i get the same flickering with dxvk
The trace is also from windows using dx

### System information
- GPU: nvidia 970
- Driver: 440.43.02
- Wine version: 5.0..... and windows 10
- DXVK version: 1.5.1

**Comment by logan001** [comment]
Seems that flickering starts with b738c4220b7f2ea71cf2f1f61521a08606ee7022

**Comment by doitsujin** [comment]
This isn't really something that can be fixed at the moment due to the lack of Vulkan support for D3D9 depth bias.

**Comment by logan001** [comment]
i've uploaded a short movie there. Watch this area

![Untitled](https://user-images.githubusercontent.com/6472378/72158207-5ae74780-33c2-11ea-82d5-b9a45970e2ab.jpg)

this flickering disappear  if i zoom in. it seems to happen on certain distance from the texture.
I've also notice some small black triangles on the ground while flying over (in game  :D). its like the triangles are render as i get close to them. but that is hard to duplicate cause i have to take similar paths and i've notice this only 2 times so far.

**Comment by Berobad** [comment]
Tried to recreate it ingame, but RADV and AMDVLK show no problem here.
Tried DXVK 1.5.1, 1.5.0 and D9VK 0.40, 0.30 with no visual difference between them.

**Comment by logan001** [comment]
these are my settings. can you try with these settings? try 1.5.1 and walk around and look for far away objects.

![GW_settings](https://user-images.githubusercontent.com/6472378/72200132-25883b80-344e-11ea-805e-ad22ffa21f5d.png)

**Comment by logan001** [comment]
here is another sample
this is with 1.5.1
![Screenshot_20200111_091651](https://user-images.githubusercontent.com/6472378/72200636-8b77c180-3454-11ea-8ba0-2cd8fb64a13f.png)
and this is with b376417f203ae066fe18ca5ed35ada5074bd6897
![Screenshot_20200111_092547](https://user-images.githubusercontent.com/6472378/72200640-9894b080-3454-11ea-9870-d63975cadace.png)

those black triangle change as i move around or just rotate camera while staying in same place

**Comment by Berobad** [comment]
I played around with the settings when I tried to recreate it, but with your settings on the same spot, I can move the camera around as much as I want with both RADV, and AMDVLK with no visual bugs.



![](https://user-images.githubusercontent.com/10475553/72203210-35f9df80-3469-11ea-8fba-b279e2442557.jpg)

**Comment by logan001** [comment]
i see. its this an nvidia only problem? it would be nice if someone else with nvidia can try this.

**Comment by jrugia** [comment]
> i see. is this an nvidia only problem? it would be nice if someone else with nvidia can try this.

Never saw those triangles ingame. I will go to the same spot using your settings and report back.

**Comment by jrugia** [comment]
I've succeeded in reproducing the issue on my system, apparently it only occurs when setting the Shadows to 'Ultra'. I couldn't see them before because I always keep it at 'Medium' to avoid the fps from tanking too low.

Furthermore I played around with the other graphics settings and the issue is present regardless of what I set, the only way to remove them is by setting the Shadows to 'High' or any lower setting.

![GW2](https://user-images.githubusercontent.com/13750621/72387081-fc53fd80-3722-11ea-8802-7556c542c8e4.jpg)

Driver version: 440.43.02
GPU: RTX 2060 Super

**Comment by CME42** [comment]
can you please try this patch?

```diff --git a/src/d3d9/d3d9_util.h b/src/d3d9/d3d9_util.h
index 50be2daf..58e923b3 100644
--- a/src/d3d9/d3d9_util.h
+++ b/src/d3d9/d3d9_util.h
@@ -182,10 +182,9 @@ namespace dxvk {
       case VK_FORMAT_D16_UNORM:
         return float(1 << 16);
 
-      case VK_FORMAT_D24_UNORM_S8_UINT:
-        return float(1 << 24);
 
       default:
+      case VK_FORMAT_D24_UNORM_S8_UINT:
       case VK_FORMAT_D32_SFLOAT_S8_UINT:
       case VK_FORMAT_D32_SFLOAT:
         return float(1 << 23);
```

**Comment by Joshua-Ashton** [comment]
There might be an extra scale NV applies here for depth bias actually -- I don't see how this can happen for `VK_FORMAT_D24_UNORM_S8_UINT` unless that is the case.

**Comment by logan001** [comment]
the patch seems to fix it.

**Comment by Iglu47** [comment]
@jrugia @Berobad +1
only with Settings: Shadows 'Ultra', if change to 'High' or lower - this issue is gone
![2020-01-18_06-42-17](https://user-images.githubusercontent.com/25866099/72770149-0b98e680-3c0e-11ea-98eb-576603df9c1d.png)
![2020-01-21_05-12-42](https://user-images.githubusercontent.com/25866099/72770155-10f63100-3c0e-11ea-86c6-04dc5b2a610d.png)

**Comment by logan001** [comment]
and only with nvidia apparently.
i've uploaded another [trace](https://drive.google.com/open?id=169Qr7-mkzJWN-LlDGw_WsEOsnAVyATHu) taken where these triangles are visible.

**Comment by Iglu47** [comment]
need confirmation that these flickering is not a game bug, 
because windows + native dx9 has a HUGE amount of similar places:
water in home insctance of Rata Sum, floor in Lion's Arch Aerodrome, waterfall in Dragonfall etc.

<details><summary>example: game bug - in home insctance of Rata Sum</summary>
<p>

![gw2_bug-home-inst_rata-sum](https://user-images.githubusercontent.com/25866099/90523605-c160ef00-e175-11ea-995e-c454cf554f93.gif)

</p>
</details>

I see only that d9vk-part has grown enough to reproduce it well

**Comment by logan001** [comment]
this happens only with dxvk on both windows or wine. without dxvk there is no issue. also this seems to happen only with nvida card when shadow is at max (see jrugia comment)

**Comment by Iglu47** [comment]
> this happens only with dxvk on both windows or wine. without dxvk there is no issue. also this seems to happen only with nvida card when shadow is at max (see jrugia comment)

I talked about this: https://github.com/doitsujin/dxvk/issues/1329#issue-547741619
not this: https://github.com/doitsujin/dxvk/issues/1329#issuecomment-576494090

**Comment by logan001** [comment]
the bug is not about the flickering that occurs while walking when almost entire screen turns black for a split second . that is present with dx9 too. it feels like the game tries to load texture for the map or something. it happens more often when you run with pets.
this bug is about some texture not rendering well in certain angles or something.

**Comment by Iglu47** [comment]
i guess, this happens on windows on dx9 too - right?
Lion's Arch Aerodrome: [gw2-floor-above-w3-enter.mp4](https://matrix.org/_matrix/media/r0/download/matrix.org/mUbFPmTsWQOeSmIfBMWLjikQ)

**Comment by logan001** [comment]
that video.... i have no clue.

**Comment by Iglu47** [comment]
Did retest on fresh wine `staging-5.21.r3.gc7ea1850` and nvidia driver `455.46.02`.
current `master` and `1.5.1` (the binary is provided from here: https://github.com/doitsujin/dxvk/releases/download/v1.5.1/dxvk-1.5.1.tar.gz)
![gw2-shadows-ultra-151](https://user-images.githubusercontent.com/25866099/101260889-1b48ed00-3744-11eb-90d2-1755f8e95020.png)
![gw2-shadows-ultra-master](https://user-images.githubusercontent.com/25866099/101260891-1edc7400-3744-11eb-8ee3-4f7cd1e7fe4b.png)

besides this one, other non-specific bugs are similar to bugs in the game.
@logan001 can you test it again?

**Comment by Iglu47** [comment]
Did retest on my old wine ~5.9 (esync).
Seems nvidia specific version driver helps.

**Comment by logan001** [comment]
its not fixed. the bug is still there. its just that this place or probably some more places are fixed. i have to make another trace where the bug is still there.

**Comment by logan001** [comment]
here it is
![Untitled](https://user-images.githubusercontent.com/6472378/101277467-50455600-37bd-11eb-8a23-ee9c5f19596d.jpg)
and [here ](https://drive.google.com/file/d/1iggJyFu6zPdSj2ObeAtDvtwDs1Sd-TAS/view?usp=sharing)is the new trace
what i've also notice aside  the dark/flickering triangle is that the shadow of the character on the ground will turn into a circle when you go high above ground.

**Comment by CME42** [comment]
This is also due to depth bias, use my old patch as a workaround until there is a proper fix: https://github.com/doitsujin/dxvk/issues/1329#issuecomment-574419167

**Comment by logan001** [comment]
:) i know the patch works. its just another example of the bug, cause the area that i mention previously got fixed somehow (game or video driver)

**Comment by Iglu47** [comment]
just put together some information into one post

### Description issue
Guild Wars 2 (on dx9 mode) has shadow issues with the D24->D32 workaround. Seems to be a problem with **Nvidia** only.

### Apitrace
- DXVK on Wine: https://drive.google.com/file/d/1prAPIjpFCPDJywfu_ftf3-DiEYpLioG8/view?usp=sharing

since it is known that dx9 support will be removed from this game (oneday), I will keep apitrace for tests on replays.

### Known solutions (at this moment)
- https://github.com/doitsujin/dxvk/issues/1329#issuecomment-574419167 helps as simple hack just for proof
- @K0bin https://github.com/K0bin/dxvk/tree/depth-wiggle-room helps too in this case

**Comment by Iglu47** [comment]
@logan001 https://github.com/doitsujin/dxvk/commit/e30b783505247753723c95eab5239c802b19b047 helps for me, maybe you know other locations in the game where the issue remains on current master?

**Comment by Iglu47** [comment]
(as far as I understand, this is not yet a proper solution, so it's probably preferable to keep this thread open)

**Comment by LingMan** [comment]
I can reproduce the issue from https://github.com/doitsujin/dxvk/issues/1329#issuecomment-739483408 on AMD with the DX11 renderer and DXVK 2.1 (which contains https://github.com/doitsujin/dxvk/commit/e30b783505247753723c95eab5239c802b19b047, but that would only help DX9 on NV anyway). Screenshot is from the north east of Snowden Drifts:
![Screenshot from 2023-04-12 23-57-55](https://user-images.githubusercontent.com/18645382/231598444-5b774d69-987b-4c86-b4c9-d4800e66a76b.png)

**Comment by Blisto91** [comment]
The game have quite alot of visual bugs on its own from square shadows at Ultra shadows setting to flickering lights on the terrain. I'd except the above to be a game issue but I'll check it out to make sure thanks.

**Comment by Blisto91** [comment]
Tried checking out both @Iglu47's (posted on Discord) and @LingMan's issues ingame but couldn't reproduce those. (tho i don't have flying mount for the one above). But i did reproduce similar in the area which also showed in native game on Windows. So reported with the ingame bug tool.

**Comment by K0bin** [comment]
GW2 no longer supports D3D9.
