### ISSUE TITLE
dxvk1.5.1版本在游戏里输入文字会闪屏和游戏奔溃（d3d9）

### ISSUE THREAD

**Issue by Kakasv123** [doitsujin/dxvk#1330]
在游戏里输入文字，会造成游戏闪屏，纹理丢失，还会游戏奔溃，
![image](https://user-images.githubusercontent.com/59716626/72121219-62dcc280-3395-11ea-8878-03484ec818c1.png)
[client64_d3d9.log](https://github.com/doitsujin/dxvk/files/4043662/client64_d3d9.log)

**Comment by ZachBacon** [comment]
Rough translation 

> Entering text in the game will cause a game splash screen, texture loss, and game crash.

**Comment by K0bin** [comment]
Thank you but did he at least mention what game this is?

**Comment by ZachBacon** [comment]
He didn't. And I don't really speak Chinese to give a proper response, I was merely using Google translate.

**Comment by libcg** [comment]
That looks like Blade & Soul. See https://github.com/Joshua-Ashton/d9vk/issues/318#issuecomment-526990235

**Comment by Joshua-Ashton** [comment]
Hi, can you try with `master`? I pushed something that may affect this... https://git.froggi.es/doitsujin/dxvk/-/jobs

**Comment by Joshua-Ashton** [comment]
`err:   Failed to create swap chain`
Validation layer output is something I'd need to debug this also...

**Comment by Kakasv123** [comment]
我试了刚调整过的dxvk，但是问题还是存在

**Comment by ZachBacon** [comment]
As per Google translate. 

> I tried dxvk just adjusted, but the problem still exists

**Comment by ZachBacon** [comment]
@Joshua-Ashton is there an incomplete information label you could place this under?

**Comment by Kakasv123** [comment]
嘿老哥，https://git.froggi.es/doitsujin/dxvk/-/jobs我在这里尝试了很多，发现在#1065这个版本就有问题，#1064没有问题，我也看了以前的问题帖子，是不是setting dialog mode出了问题，因为你在1月5号的时候修改了它，问题好像没有发生在linux系统，都出在了win10系统，如果可以的能不能删除对setting dialog mode的支持呢

**Comment by ZachBacon** [comment]
Google translated this as 

> Hey brother, https://git.froggi.es/doitsujin/dxvk/-/jobs I tried a lot here and found that there is a problem in this version # 1065, there is no problem in # 1064, I also read the previous problem  Post, is there a problem with the setting dialog mode, because you modified it on January 5th, the problem does not seem to occur in the linux system, it is in the win10 system, if you can delete the setting dialog mode  Support it

**Comment by Joshua-Ashton** [comment]
This should be fixed now. Please re-test on master.

https://git.froggi.es/doitsujin/dxvk/-/jobs

**Comment by Joshua-Ashton** [comment]
Closing as I have tested this fix extensively locally.
