### ISSUE TITLE
[d3d9] Command & Conquer: Renegade - stuttering character animations

### ISSUE THREAD

**Issue by Siltala** [doitsujin/dxvk#1334]
Character walking/running animations stutter heavily in this game with dxvk while other animations work as expected.

Here is a video clearly demonstrating the issue: https://drive.google.com/open?id=1SsKTDAB0j5uWs_eBZP_9pX_2Mm9MzFBH

I also saw the issue a couple of times on wined3d but there it seems random and relatively rare whereas with dxvk it occurs all the time.

### Software information
Game is Command & Conquer: Renegade with all graphics settings maxed.
I note that retail Renegade is (I think) a dx8 game; I'm using the latest [fan patch](http://www.tiberiantechnologies.org/) which, among other things, features an updated dx9 renderer.

### System information
- GPU: Radeon 5700 XT
- Driver: mesa-git (b5c96885) (with ACO)
- Wine version: wine-5.0-rc4 (Staging)
- DXVK version: 1.5.1

### Apitrace file(s)
- Wined3d trace: https://drive.google.com/file/d/118ysEbjIs-tqvtWoegx5P_CzDFRLaMvY/view?usp=sharing
For some reason, running the apitrace with dxvk does not reproduce the problem for me; it seems it only occurs when directly running the game itself with dxvk. I can't do a Windows trace because I don't have Windows.

### Log files
- d3d9.log [game2_d3d9.log](https://github.com/doitsujin/dxvk/files/4049680/game2_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by Joshua-Ashton** [comment]
Can you please make a DXVK trace?

**Comment by Siltala** [comment]
Here you go: https://drive.google.com/open?id=1jfP7X4ZY0WlXehxQcLOO5hnecDD9qQV7
Curiously, the issue also didn't occur when taking the apitrace with dxvk.

I also noticed that the issue doesn't occur if I run the game with vsync enabled through the game settings; perhaps this bug only occurs when the fps level is extremely high?

**Comment by Joshua-Ashton** [comment]
> perhaps this bug only occurs when the fps level is extremely high
Seems to be that way as I can't reproduce it on that trace either.

I'm pretty sure this is a game bug. Can you try with a manual FPS cap with libstrangle etc?

**Comment by Siltala** [comment]
I tried libstrangle out and it seems that the issue doesn't occur with a fps limit of 1000 (or below).
With the limit set to higher than 1000 the issue starts to occur and becomes progressively worse the higher it is.

**Comment by Joshua-Ashton** [comment]
Nothing I can do about that then...
