### ISSUE TITLE
Need for Speed Shift 2 Unleashed & Rivatuner Statistic Server 7.2.3

### ISSUE THREAD

**Issue by rakantoh** [doitsujin/dxvk#1336]
Hi. I use the dlls of dxvk in windows, i put the respective dll (dx9, dx10, dx11) in the install dir of the game, and i use msi afterburner and rivatuner statistic server (RTSS) for monitoring fps, use of hardware and temps.
In borderlands, i put the dxvk d3d9.dll in the install dir of borderlands, and the game runs better that the real dx9, and runs fine with msi afterburner and RTSS running, but with need for speed shift 2 unleashed (shift2) and dxvk d3d9.dll, only keeping installed RTSS, shift2 crashes. If i uninstall RTSS, and i runs shift2 with dxvk d3d9, the game runs fine, or if i open shift2 with real dx9 and RTSS installed and running, shift2 runs fine.
Resuming, The error is with dxvk, shift2 and RTSS installed (not matter if RTSS is open or not).

**Comment by Joshua-Ashton** [comment]
Yep, RTSS has a tendency to break everything at times ranging from DXVK to Renderdoc (I even made a bug report on Renderdoc about random crashes that turned out to be that pile of crap causing it)
