### ISSUE TITLE
It helps fix stuttering Fallout:NV on Win10!!! [THANKS]

### ISSUE THREAD

**Issue by t14462** [doitsujin/dxvk#1337]
DXVK helps with fixing stuttering of Fallout New Vegas on Windows 10! It much better than D3D9on12 and ENBoost!

### Software information
Fallout New Vegas: DXVK's d3d9.dll and dxgi.dll

### System information
- GPU: AMD RX560
- Driver: 20.1.1
- Wine version: Windows 10
- DXVK version: 1.5.1

THANKS GUYS!!!

**Comment by t14462** [comment]
HAPPY NEW YEAR!!!

**Comment by t14462** [comment]
It is 1337 – LEET. LOL

**Comment by mozo78** [comment]
Windows 10 - shame on you...

**Comment by doitsujin** [comment]
Glad to hear it's working well for you, I guess.
