### ISSUE TITLE
[Feature Request] DLL Chainloading

### ISSUE THREAD

**Issue by NikoofDeath** [doitsujin/dxvk#1339]
Would it be possible to implement DLL chainloading into DXVK, to make it easier to load D3D wrappers like ENB, Reshade etc.? I'm not sure if this would be of much use on Linux, but on Windows it would allow these to be used without using DXVK system-wide, which is currently (as far as I am aware) the only way to do this. I am aware wrappers like these have no official support, but it would be nice to at least have the ability to load them.

**Comment by doitsujin** [comment]
No, because these D3D wrappers don't get loaded by D3D11 on Windows, they load D3D11 themselves, so they'd have to do the same thing with DXVK somehow. It's just not our responsibility to load random third-party libraries.

Both ENB and Reshade work on Linux, so there's that.
