### ISSUE TITLE
Path of Exile - Nvidia wine_vkCreateSampler error

### ISSUE THREAD

**Issue by jmis** [doitsujin/dxvk#134]
It looks like DXVK is getting farther than before with the deferred context changes.  I can load the starting cinematic but get an error immediately after.

### Software information
- Game: Path of Exile
- Version: 3.2b - 64bit

### System information
- GPU: Geforce GTX 970
- Driver: 390.25
- Wine version: wine-vulkan 3.3
- DXVK version: 85d28f7328564a484df96a7ffff706c326b1293e

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log: https://pastebin.com/VH5BAmuU
- dxgi.log: https://pastebin.com/hBkm4uHe
- wine backtrace: https://pastebin.com/MZ8Nr1x8

**Comment by doitsujin** [comment]
can you re-run this with `DXVK_DEBUG_LAYERS=1` enabled? There's probably an issue with an invalid combination of sampler parameters somewhere.

**Comment by Thaodan** [comment]
I builded dxvk abou two hours ago and didn't get the errot but a crash too.
I'm running arch and wine-staging 2.2.1.
GPU is NVIDIA Geforce 1080 ti.
Logs are the same without the error in d3d11.log.

**Comment by jmis** [comment]
ParameterValidation(ERROR): object: 0x0 type: 0 location: 1692 msgCode: 308283486: vkCreateSampler(): value of pCreateInfo->maxAnisotropy must be in range [1.0, 16.000000] VkPhysicalDeviceLimits::maxSamplerAnistropy, but 0.000000 found. The spec valid usage text states 'If anisotropyEnable is VK_TRUE, maxAnisotropy must be between 1.0 and VkPhysicalDeviceLimits::maxSamplerAnisotropy, inclusive' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkSamplerCreateInfo-anisotropyEnable-01071)

- Full-trace: https://pastebin.com/6EKNDtWU

**Comment by jmis** [comment]
@Thaodan Your error was related to unimplemented deferred contexts.  A partial implementation has been committed but not in any release.  You need to be on the latest wine-vulkan and dxvk versions.  You'll need to compile both yourself which can be a pain.  I'm on Ubuntu 16.04 and can compile the 64-bit version of wine-vulkan.  I needed to compile DXVK in a container and copy the assemblies over.

**Comment by Thaodan** [comment]
Can you put out the branch?

**Comment by doitsujin** [comment]
@jmis yep, that's a bug on my end. Will take a look at that later, thanks.

**Comment by Thaodan** [comment]
@jmis  is the patch even up to date when talking about wine 3.3?

**Comment by jmis** [comment]
@Thaodan No, you have to manually code the changes.

**Comment by Thaodan** [comment]
Thats what I was asking, do I have to do this?
https://bugs.winehq.org/attachment.cgi?id=59204&action=diff

**Comment by doitsujin** [comment]
Please re-test with 09fd7abde01e7951aa32855606591d09df181b86.

**Comment by jmis** [comment]
@doitsujin This fixed the issue.

I'm able to load the game and select a character.  However, the game is throwing a dx11 exception when loading into a city.  I'm going to email support to see if they can give me anymore insight into error message.  DXVK_DEBUG_LAYERS=1 didn't add any additional information to why the game crash happened.

**Comment by Glog78** [comment]
jmis did you use the patch which thaodan used or not ? I am asking because i get the wic error with wine-vulkan git + dxvk git.

**Comment by jmis** [comment]
Yes, you need to use the CoInitialize fix.
