### ISSUE TITLE
[d3d11] Shroud of the Avatar

### ISSUE THREAD

**Issue by SilentWarrior1** [doitsujin/dxvk#1340]
Shroud of the Avatar.exe
it's f2p mmorpg https://www.shroudoftheavatar.com/
### System information
- GPU: sapphire pulse 5700xt
- Driver: 20.1.1
- Wine version: none
- DXVK version: 1.5.1
gives me this error after launcing:
Switching to resolution 2560x1415 failed, trying lower one
All resolution switches have failed
Screen: DX11 could not switch resolution (2560x1415 fs=0 hz=0)

### Apitrace file(s)
- when trying to trace - it gives me error (d:\Games\Shroud\bin>D:\Games\Shroud\bin\apitrace.exe trace -a d3d11 "D:\Games\Shroud\Shroud of the Avatar.exe"
error: failed to find dxgitrace.dll wrapper (rerun with -v option for more details)

### Log files
- d3d11.log:	
warn:  D3D11CoreCreateDevice: Adapter is not a DXVK adapter
info:  Game: Shroud of the Avatar.exe
info:  DXVK: v1.5.1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_1
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_1
info:  Device properties:
info:    Device name:     : AMD Radeon RX 5700 XT
info:    Driver version   : 2.0.122
info:  Enabled device extensions:
info:    VK_AMD_memory_overallocation_behavior
info:    VK_AMD_shader_fragment_mask
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_full_screen_exclusive
info:    VK_EXT_host_query_reset
info:    VK_EXT_memory_priority
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 1
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 1
info:    logicOp                                : 1
info:    multiDrawIndirect                      : 1
info:    drawIndirectFirstInstance              : 1
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 1
info:    shaderImageGatherExtended              : 1
info:    shaderStorageImageExtendedFormats      : 1
info:    shaderStorageImageReadWithoutFormat    : 1
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 1
info:    shaderInt64                            : 1
info:    variableMultisampleRate                : 1
info:  VK_EXT_conditional_rendering
info:    conditionalRendering                   : 0
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 1
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 1
info:    geometryStreams                        : 1
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 2
info:  DXVK: Read 1 valid state cache entries
info:  DXVK: Using 2 compiler threads
warn:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  88399375-734f-4892-a95f-70dd42ce7cdd
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  72299288-2c68-4ad8-945d-2bfb5aa9c609
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  2c576d2a-0c1c-4d1d-ad7c-bc4faec15abc
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  189819f1-1db6-4b57-be54-1821339b85f7
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  b898d4fd-b5b3-4ffc-8694-0259864ffcf8
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  9b7e4a00-342c-4106-a19f-4f2704f689f0
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  ffffffff-1bbe-4d12-afbf-8fdf7e0a87c7
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  c4fec28f-7966-4e95-9f94-f431cb56c3b8
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  88399375-734f-4892-a95f-70dd42ce7cdd
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  72299288-2c68-4ad8-945d-2bfb5aa9c609
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  2c576d2a-0c1c-4d1d-ad7c-bc4faec15abc
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  189819f1-1db6-4b57-be54-1821339b85f7
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  b898d4fd-b5b3-4ffc-8694-0259864ffcf8
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  9b7e4a00-342c-4106-a19f-4f2704f689f0
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  ffffffff-1bbe-4d12-afbf-8fdf7e0a87c7
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  c4fec28f-7966-4e95-9f94-f431cb56c3b8

**Comment by K0bin** [comment]
You also need to copy DXVK's DXGI.dll into the game folder.

**Comment by doitsujin** [comment]
This. D3D11 alone isn't enough. Moreover, Windows is not our target platform so there's no guarantee it will work.

**Comment by SilentWarrior1** [comment]
thx, with dxgi trace launched the game... but there is no any trace log.
theese are logs when i'm trying to launch the game with d3d11 and dxgi.dll
- d3d11.log:	
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_1
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_1
info:  Device properties:
info:    Device name:     : AMD Radeon RX 5700 XT
info:    Driver version   : 2.0.122
info:  Enabled device extensions:
info:    VK_AMD_memory_overallocation_behavior
info:    VK_AMD_shader_fragment_mask
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_full_screen_exclusive
info:    VK_EXT_host_query_reset
info:    VK_EXT_memory_priority
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 1
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 1
info:    logicOp                                : 1
info:    multiDrawIndirect                      : 1
info:    drawIndirectFirstInstance              : 1
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 1
info:    shaderImageGatherExtended              : 1
info:    shaderStorageImageExtendedFormats      : 1
info:    shaderStorageImageReadWithoutFormat    : 1
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 1
info:    shaderInt64                            : 1
info:    variableMultisampleRate                : 1
info:  VK_EXT_conditional_rendering
info:    conditionalRendering                   : 0
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 1
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 1
info:    geometryStreams                        : 1
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 2
info:  DXVK: Read 1 valid state cache entries
info:  DXVK: Using 2 compiler threads
warn:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT

- dxgi.log:	
info:  Game: Shroud of the Avatar.exe
info:  DXVK: v1.5.1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD Radeon RX 5700 XT:
info:    Driver: 2.0.122
info:    Vulkan: 1.1.129
info:    Memory Heap[0]: 
info:      Size: 7920 MiB
info:      Flags: 0x3
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[4]: Property Flags = 0xc1
info:    Memory Heap[1]: 
info:      Size: 7909 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:      Memory Type[5]: Property Flags = 0xc6
info:      Memory Type[7]: Property Flags = 0xce
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x3
info:      Memory Type[2]: Property Flags = 0x7
info:      Memory Type[6]: Property Flags = 0xc7
info:  Game: Shroud of the Avatar.exe
info:  DXVK: v1.5.1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD Radeon RX 5700 XT:
info:    Driver: 2.0.122
info:    Vulkan: 1.1.129
info:    Memory Heap[0]: 
info:      Size: 7920 MiB
info:      Flags: 0x3
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[4]: Property Flags = 0xc1
info:    Memory Heap[1]: 
info:      Size: 7909 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:      Memory Type[5]: Property Flags = 0xc6
info:      Memory Type[7]: Property Flags = 0xce
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x3
info:      Memory Type[2]: Property Flags = 0x7
info:      Memory Type[6]: Property Flags = 0xc7
info:  Game: Shroud of the Avatar.exe
info:  DXVK: v1.5.1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD Radeon RX 5700 XT:
info:    Driver: 2.0.122
info:    Vulkan: 1.1.129
info:    Memory Heap[0]: 
info:      Size: 7920 MiB
info:      Flags: 0x3
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[4]: Property Flags = 0xc1
info:    Memory Heap[1]: 
info:      Size: 7909 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:      Memory Type[5]: Property Flags = 0xc6
info:      Memory Type[7]: Property Flags = 0xce
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x3
info:      Memory Type[2]: Property Flags = 0x7
info:      Memory Type[6]: Property Flags = 0xc7

**Comment by K0bin** [comment]
Does the game work now? If not, whats the problem?

**Comment by SilentWarrior1** [comment]
it crashes with theese two logs

**Comment by K0bin** [comment]
The logs don't have anything that wouldn't be there if it was working correctly. Check your desktop for the apitrace (and make sure you make the apitrace **without DXVK installed**)

**Comment by SilentWarrior1** [comment]
as i sad, apitrace ggive me no logs at all
it just launch the game...
and yes, i made apitrace without dxvk files

**Comment by doitsujin** [comment]
Well, what's your problem now? Everything seems to be working fine according to those logs.

**Comment by SilentWarrior1** [comment]
> Well, what's your problem now? Everything seems to be working fine according to those logs.
my problem is that the game cann't launch with dxvk. 
my system is win10 x64 1809
> > as i sad, apitrace ggive me no logs at all 
> Yes, that's correct. apitrace is supposed to give you a `.trace` file, not logs.
and no ".trace" files either nor in game, nor in apitrace folders
so, the conlusion is that this game just don't support dxvk?

**Comment by K0bin** [comment]
>  and no ".trace" files either nor in game, nor in apitrace folders

> Check your desktop for the apitrace

**Comment by SilentWarrior1** [comment]
damn, you're right! 
i've uploaded this trace:  https://anonfile.com/7bA3I2M7n6/Shroud_of_the_Avatar.5_7z

**Comment by K0bin** [comment]
Nice file hoster. Downloading that 50mb file is taking me about an hour because it's limiting me to 60kB/s

**Comment by doitsujin** [comment]
Works on Linux, so yeah, can't really do very much here.

**Comment by Kein** [comment]
I'm having similar issue with Untiy 2019 player on Windows 10. Is there any way to disable nvapi workaround in Windows?
