### ISSUE TITLE
[d3d9] Atelier sophie crashes: iBackBuffer > 0 not supported

### ISSUE THREAD

**Issue by exolyte** [doitsujin/dxvk#1341]
Atelier Sophie silently crashes shortly after creating a window. Logs contain
`err:   D3D9: GetBackBuffer: iBackBuffer > 0 not supported`
Game works fine with wined3d.

### Software information
Atelier Sophie: https://store.steampowered.com/app/527270/Atelier_Sophie_The_Alchemist_of_the_Mysterious_Book/

### System information
- GPU: RX570
- Driver: radv-git
- Wine version: proton 4.11
- DXVK version: 64ece363

### Apitrace file(s)
https://mega.nz/#!nMs3kKjI!cgA6Py9CjfoK__PERUmOoewWVjv3jhpxLYNMlA8ZTkI

### Log files
[A17_d3d9.log](https://github.com/doitsujin/dxvk/files/4059802/A17_d3d9.log)

**Comment by doitsujin** [comment]
Can you test if this branch fixes the issue:
https://github.com/doitsujin/dxvk/tree/dxvk-image-renaming

**Comment by exolyte** [comment]
Didn't do any extensive testing, but everything seems to work fine at first glance.

![2020-01-15-02:04:04](https://user-images.githubusercontent.com/2102492/72396008-9758d180-373b-11ea-8005-0102ea6ea524.png)
