### ISSUE TITLE
Mods completely break A Hat in Time

### ISSUE THREAD

**Issue by DarkSide1305** [doitsujin/dxvk#1345]
Every time I install a mod, no matter what kind of Mod it is, the game freezes on the loading screen and in general has really bad performance before being able to load the save file. Without DXVK it works without a problem. Having DXVK installed AND installing mods when the game already is started also works.

### Software information
A Hat in Time, almost max graphic Settings
### System information
- GPU: R9 390
- Driver: 19.12.2
- Wine version: -
- DXVK version: Latest master

### Apitrace file(s)
- -

### Log files
- d3d9.log: [HatinTimeGame_d3d9.log](https://github.com/doitsujin/dxvk/files/4072444/HatinTimeGame_d3d9.log)
- d3d11.log: -
- dxgi.log: -

**Comment by K0bin** [comment]
Please make an apitrace so we can debug this.

**Comment by DarkSide1305** [comment]
How can I do it? I got myself the Trace thing, which is a d3d9. But im using the d3d9.dll from DXVK for the game. So I cant have both installed. Because the Error only appears when I use the DXCK d3d9.dll

**Comment by K0bin** [comment]
Use the Apitrace D3D9.dll. It doesn't matter if you see the error while making the apitrace.

**Comment by DarkSide1305** [comment]
The file is currently uploading. I have Mods installed and got past the point of crashing. I post the Google Drive link to the file once it finished uploading.

**Comment by DarkSide1305** [comment]
https://drive.google.com/open?id=1YxWdNK4tA1iCU3OOTDpgHLttdZ44bS9z

**Comment by Joshua-Ashton** [comment]
Hi, what mods are we talking about? Can you give me one as an example...

**Comment by DarkSide1305** [comment]
It happened with every mod so far. Level, Badges, Hats, doesnt matter. The ones im using right now are "Cooldown Cancel Hats", "Kirby Yarn Hat" and "Aura Badge"

**Comment by K0bin** [comment]
You didn't even enter a level in your apitrace. When you make an apitrace you have to repeat the steps that would normally result in a crash.

**Comment by DarkSide1305** [comment]
I did. The Crash happens while loading Hat Kids Ship, so right after selecting the file.

**Comment by DarkSide1305** [comment]
Or, rather: The Game stopping to load appears when trying to load Hat Kids Ship. Since it doesnt crash, it just gets stuck, which doesnt happen without DXVK.

**Comment by K0bin** [comment]
How long have you waited before killing the game? Might just take a while compiling a bunch of shaders.

**Comment by DarkSide1305** [comment]
Well, it took 2 minutes from starting for me to be able to choose my Save File.
After 5 minutes it finally loaded, but was INCREDIBLY unstable.
After around 7 minutes I was able to walk around, but it seems that every action I did (Jumping, Punching, Dashing, entering a new Area of the ship) froze my game for a few seconds.

After it loaded the first time I tried it a second time.
Took me roughly 2 minutes again before I was able to select my save file.
After around 5 minutes and 30 seconds it loaded into the ship, but repeated the same thing. Literally every action, even if its just turning the camera out stops the game for like 3 seconds.

With Mods and DXVK this problems happens
Without Mods and DXVK this problem doesnt happen
With Mods and without DXVK this problem doesnt happen

**Comment by DarkSide1305** [comment]
Just for comparison:
Without Mods and DXVK I can choose my Save File in 4 Seconds, the Ship is loaded in 20 and is instantly 60FPS Buttery smooth

**Comment by DarkSide1305** [comment]
Interesting. I just tested the "Cooldown Cancel Hats" Mod and my game loaded without a problem.
Adding the "Kirby Yarn Hat" gives me the problems again, and uninstalling it removes the problem again.
Adding the "Aura Badge" gives me the problem again, and uninstalling it removs the problem again.
And then I tried to use the "Aura Badge" alone without any other mod, which also made the problems appear again.

**Comment by DarkSide1305** [comment]
And, keep in mind: Having the game started and installing all 3 Mods works flawlessly.

**Comment by Joshua-Ashton** [comment]
Works fine here:

![image](https://user-images.githubusercontent.com/21316711/73988353-5159ec80-493a-11ea-87f0-6331f7e92f93.png)


![image](https://user-images.githubusercontent.com/21316711/73988305-325b5a80-493a-11ea-9eef-64a277b0b9fe.png)

**Comment by DarkSide1305** [comment]
Yup. Works now. Either some DXVK Update fixed it, the recent Hat in Time Update fixed it, or a combination of the both
