### ISSUE TITLE
D3D9 games do not start 

### ISSUE THREAD

**Issue by logan001** [doitsujin/dxvk#1349]
GW2 does not start with b954ab886f2eaa76393b6f52b921bcb0df0ca308

### System information
- GPU: nvidia 970
- Driver: 440.48.02
- Wine version: 5.0 rcX
- DXVK version: b954ab886f2eaa76393b6f52b921bcb0df0ca308

### Log files
[Gw2-64_d3d9.log](https://github.com/doitsujin/dxvk/files/4075331/Gw2-64_d3d9.log)

**Comment by doitsujin** [comment]
Can you test this branch: https://github.com/doitsujin/dxvk/tree/d3d9-view-fix

Also, next time, please record an apitrace. I coincidentally had one lying around for GW2, but that's not always the case.

**Comment by logan001** [comment]
i will try it a bit later. as for the api trace there is probably nothing to trace since the game just disapear and is stays defunct in the list of processes

**Comment by doitsujin** [comment]
You're supposed to record an apitrace with a configuration that **works** (i.e. wined3d, or Windows if possible), not with DXVK.

**Comment by logan001** [comment]
it does not crush with d3d9-view-fix

**Comment by doitsujin** [comment]
Thanks for confirming.
