### ISSUE TITLE
Atelier Sophie The Alchemist of the Mysterious Book dont start (backbuffer issue?)

### ISSUE THREAD

**Issue by mrdeathjr28** [doitsujin/dxvk#1352]
Atelier Sophie The Alchemist of the Mysterious Book dont start (backbuffer issue?)

Software information

Atelier Sophie The Alchemist of the Mysterious Book

System information

Nvidia Drivers 440.48.02 (run package)

Lubuntu 20.04 x64 - Kernel 5.4.0-8 generic (ubuntu mainline) -

CPUFreq: Performance

CPU: Core i3 8350K Tri-Core (Coffelake 14nm) 5.0Ghz - Zalman CNPS 10x Performa+ - CoolerMaster MasterFan Pro Air Balance (83 CFM)

MEMORY: 12GB DDR4 2400mhz (8x1 - 4x1) Mushkin (dual channel: 37.5 gb/s - Flex Mode)

GPU: Gigabyte Nvidia Geforce GTX 1050 OC (GP107 14nm: 640 Shaders / 40 TMUS / 32 ROPS) Windforce 2GB DDR5 7000Mhz 128Bit (110Gb/s)

MAINBOARD: ASUS Z370-P

Apitrace file(s)

https://mega.nz/#!CR8FWabJ!g2B-BqiJKVtn3mkBN0vASRSsyYYRKqdwiA6cvbn94wc

Log files

[a17_d3d9.log](https://github.com/doitsujin/dxvk/files/4076767/a17_d3d9.log)

**Comment by doitsujin** [comment]
See #1349.
