### ISSUE TITLE
Build failure - error: ‘mutex’ in namespace ‘std’ does not name a type

### ISSUE THREAD

**Issue by h1z1** [doitsujin/dxvk#1353]
Snipping template, not sure it applies.  

I fully accept this may not be the right place but I'm at a loss as to why it's failing.  As per the proton build instructions from Valve, based on vagrant.

```
Project version: v1.5
Native C compiler: gcc (gcc 8.3.0 "gcc (Debian 8.3.0-6) 8.3.0")
Cross C compiler: i686-w64-mingw32-gcc (gcc 8.3.0)
Native C++ compiler: g++ (gcc 8.3.0 "g++ (Debian 8.3.0-6) 8.3.0")
Cross C++ compiler: i686-w64-mingw32-g++ (gcc 8.3.0)
```

[Build output](https://gist.github.com/h1z1/36ccc7b5b1c6f22ab091ed7e21582957)

**Comment by doitsujin** [comment]
https://github.com/doitsujin/dxvk#troubleshooting
