### ISSUE TITLE
Sonic Generations dont start and show direct3d device create error

### ISSUE THREAD

**Issue by mrdeathjr28** [doitsujin/dxvk#1355]
Sonic Generations dont start and show direct3d device create error

![sncgn](https://user-images.githubusercontent.com/6601480/72654939-e1220180-395f-11ea-97ae-dc8752723805.jpg)

Software information

Sonic Generations

System information

Nvidia Drivers 440.48.02 (run package)

Lubuntu 20.04 x64 - Kernel 5.4.0-8 generic

CPUFreq: Performance

CPU: Core i3 8350K Tri-Core 5.0Ghz

MEMORY: 12GB DDR4 2400mhz

GPU: Gigabyte Nvidia Geforce GTX 1050 2GB DDR5

MAINBOARD: ASUS Z370-P

Apitrace file(s)

https://mega.nz/#!Kd9WiapJ!-yfVggCsrJM9V2nfpQqsNy6yoNWvkR91jNucNmmDySM

Log files

[SonicGenerations_d3d9.log](https://github.com/doitsujin/dxvk/files/4079764/SonicGenerations_d3d9.log)

**Comment by Joshua-Ashton** [comment]
That isn't the latest version of DXVK and the trace replays fine.

**Comment by mrdeathjr28** [comment]
Still crash with lastest master

**Comment by doitsujin** [comment]
According to [ProtonDB](https://www.protondb.com/app/71340) this works fine, please test if DXVK 1.5 works for you.

**Comment by BlazeKl** [comment]
Delete GraphicsConfig.cfg from the game files and start the configuration tool with DXVK enabled

**Comment by NerosTie** [comment]
Tested for one hour and I have no issue at all...

**Comment by RinMaru** [comment]
no issues here and im on windows :\

**Comment by mrdeathjr28** [comment]
> Delete GraphicsConfig.cfg from the game files and start the configuration tool with DXVK enabled

Many thanks d9vk works
