### ISSUE TITLE
[d3d9] Issues with Valkyria Chronicles

### ISSUE THREAD

**Issue by Oschowa** [doitsujin/dxvk#1357]
Valkyria Chronicles has 2 issues:
On DXVK master and 1.5.1 the Launcher/Config menu seems to only update it's window once for each time it is focused - which can be triggered with i.e. alt + tab - making it unuseable.
It also shows the following error when you close it:
![Screenshot from 2020-01-18 23-06-36](https://user-images.githubusercontent.com/8129300/72671780-c6c75100-3a4f-11ea-9115-501a8426b257.png)
The launcher works fine with wined3d.

Starting the actual game also seems to display one frame of random old VRAM data with DXVK master, which doesn't happen with 1.5.1 or wined3d. I tried to bisect it, but the result looks like bogus, but here is the bisect log anyways:
[bisect-log.txt](https://github.com/doitsujin/dxvk/files/4082012/bisect-log.txt)

### Software information
Valkyria Chronicles

### System information
- GPU: RX580
- Driver: RADV/ACO 19.3.2
- Wine version: Proton 4.11-12
- DXVK version: 35a9934 and 1.5.1

### Apitrace file(s)
Launcher:
https://drive.google.com/open?id=1tAsHzcz8bL7zuvZxhKbcwMWmbT6886o3
Game:
https://drive.google.com/open?id=19yG5rXh9o1R0vGp92hJjv1fEpBbCqgaC

### Log files
- d3d9.log:
[Launcher_d3d9.log](https://github.com/doitsujin/dxvk/files/4082004/Launcher_d3d9.log)
[Valkyria_d3d9.log](https://github.com/doitsujin/dxvk/files/4082005/Valkyria_d3d9.log)

**Comment by Oschowa** [comment]
I noticed, that the "one random frame" issue also happens with other games, specifically Dragon's Dogma and Metal Gear Rising. But it is really not critial anyways, so feel free to ignore that part :frog:

**Comment by Joshua-Ashton** [comment]
Can you please re-test the launcher/config to see if the refcounting issue is fixed?

**Comment by Oschowa** [comment]
The refcounting issue seems fixed on master.

**Comment by Joshua-Ashton** [comment]
Launcher renders fine for me on Windows + DXVK.

I'll test it under Wine in a bit.

**Comment by Joshua-Ashton** [comment]
Hi, the launcher renders fine for me on `master` + latest Mesa on Wine-tkg...

![Screenshot_20200223_154548](https://user-images.githubusercontent.com/21316711/75115091-975dc280-5653-11ea-9cbe-59962c85d1ff.png)

**Comment by Oschowa** [comment]
Tested with DXVK master on Proton 5.0-3 and it's fine now, thanks.
