### ISSUE TITLE
Why is MinGW64 required?

### ISSUE THREAD

**Issue by hilpara** [doitsujin/dxvk#136]
I just wanted to know why you need MinGW to be able to compile DXVK? The problem is, that Arch doesn't provide MinGW as binary anymore (It can be found on AUR but the package was broken for a while). Now I'm using Solus and it doesn't have MinGW at all. I'm not sure about other distros. So I always have to wait until you release new binaries, which is not so often (for my taste :) )

**Comment by Yardanico** [comment]
@hilpara you can use blackarch repos for MinGW on Arch. And MinGW is required because DXVK needs to compile .dll's for Wine

**Comment by hilpara** [comment]
Ok. I'm now on Solus so that doesn't help. Thanks for the reply! I will have to test if Docker solution works for me.

**Comment by Yardanico** [comment]
@hilpara yeah, it probably would, I know there's some MinGW compilers in docker
