### ISSUE TITLE
[d3d11] Call of Duty: Mordern Warfare Remastered

### ISSUE THREAD

**Issue by byumjin** [doitsujin/dxvk#1360]
Hi,

currently, I'm trying to run CoD:MW Remastered with DXVK with source codes, not the binary ones. When my application is initializing, it crashes after it passes CreateDepthStencilState().

![캡처_2020_01_20_18_20_18_445](https://user-images.githubusercontent.com/22266515/72714190-a4e5df80-3bb1-11ea-9a56-6d830e06e95d.png)

![캡처_2020_01_20_18_20_35_821](https://user-images.githubusercontent.com/22266515/72714192-a57e7600-3bb1-11ea-946a-45bea1f3a516.png)

![캡처_2020_01_20_18_20_51_96](https://user-images.githubusercontent.com/22266515/72714197-a6afa300-3bb1-11ea-9af8-1356a7ad3678.png)

The suspicious thing is, ppDepthStencilState points RasterizerState(instead of DepthStencilState) out before it passes InitReturnPtr().

![캡처_2020_01_20_18_03_05_111](https://user-images.githubusercontent.com/22266515/72714368-f1311f80-3bb1-11ea-9102-828e55c2f9f7.png)

The problem is that it doesn't show any callstacks so that it makes hard to trace where can be cause of this.

So, I want to ask that is there a better way to debug or trace this?
(I tried apitrace but it didn't generate any log files)
Or did you see this kind of issue before?
I already set the log to Trace level but it didn't give much information.

FYI, I had to set custom VenderID at dxvk.config file because I'm currently using NVidia card and it kept trying to load ati dll instead of nvapi64.dll.
Also, I'm using DXVK 1.2.1 version a bit out-dated.

Thank you.

### System information
- GPU: GTX1060 mobile
- Driver: 441.87
- Wine version: 
- DXVK version: 1.2.1

**Comment by doitsujin** [comment]
> So, I want to ask that is there a better way to debug or trace this?

Yes, record an apitrace. I appreciate your debugging efforts but ultimately they don't tell me anything; if the game passes invalid pointers around then that's not a DXVK issue.

FWIW Modern Warfare Remastered [did](https://www.youtube.com/watch?v=DR-jDoTT5V4) work in the past; maybe try an old DXVK version (like 1.0 / 1.0.1) to double-check. If that also doesn't work, probably another one of those Windows-only issues that we cannot fix.

**Comment by byumjin** [comment]
> if the game passed invalid pointers around then it would likely crash on native D3D11 as well.

I also thought of that, but it works well if I just run my game on native.

Currently, trying old version would be the best option.

**Comment by byumjin** [comment]
Finally, I could [trace infomation](https://drive.google.com/open?id=1P0pYdwBs6GlyZCqPEt47ZGm2HmYbq4Oq) via apitrace and found very suspicious parts out.

These are trace when I run CoD:MW remastered on native (Windows).

![캡처_2020_01_22_18_10_09_419](https://user-images.githubusercontent.com/22266515/72880684-ac88be00-3d42-11ea-8f06-cd24ba3436c9.png)

You can see that it creates swapchain before MakeWindowAssociation function call.
But, somehow, dxvk never hook CreateSwapChain function.
So, it seems like it never creates swapchain.
(I've checked that MakeWindowAssociation is hooked correctly)

![캡처_2020_01_22_18_10_21_490](https://user-images.githubusercontent.com/22266515/72880836-fd98b200-3d42-11ea-8f9f-e865fc73068f.png)

After a few threads, it calls GetBuffer() from SwapChain interface right after it passes CreateDepthStencilState(). I think that's why it crashes after it passes CreateDepthStencilState().

Do you have any idea why CreateSwapChain function is not hooked?
Or any suggestions?

**Comment by doitsujin** [comment]
We don't use hooks at all, but it's possible that the game uses Windows DXGI for some reason which simply cannot work with DXVK.

**Comment by byumjin** [comment]
I already uploaded the trace.
You can check trace infomation url [here](https://drive.google.com/open?id=1P0pYdwBs6GlyZCqPEt47ZGm2HmYbq4Oq) or above.

**Comment by byumjin** [comment]
And [this](https://drive.google.com/open?id=1_h4h_Teq_Fow22a1_Zs_wudD1vlaNXJE) is what I run with Dxvk. I think this file does not reflect the trace correctly though when I run my app(with dxvk) on Visual Studio because it doesn't even create d3d11 device.

**Comment by doitsujin** [comment]
The trace replays fine with DXVK.

FWIW one thing I just noticed:

> DXVK version: 1.2.1

How about trying 1.5.1?

**Comment by byumjin** [comment]
I found a similar issue #1109 here.
After I update DXVK from 1.2.1 to 1.5.1, the problem is gone.
