### ISSUE TITLE
Terrain Flickering in Entropia Universe

### ISSUE THREAD

**Issue by PkmX** [doitsujin/dxvk#1364]
# Software information
Entropia Universe VU 17 (D3D11 CryEngine based), any graphic settings

### System information
- GPU: AMD Radeon RX 590
- Driver: Linux 5.4.10 / RADV 19.3.2
- Wine version: 5.0-rc5-staging
- DXVK version: 1.5.1

### Apitrace file(s)
- [apitrace](https://drive.google.com/file/d/1U3R9vY7oxfoP_y1NaLk4rx3maHLd4hlB/view?usp=sharing)

### Log files
- [d3d9, dxgi, d3d11 logs](https://gist.github.com/PkmX/f686cf7caad6811850437c8a0fa131ae)

![Imgur](https://imgur.com/d2jn073.png)

Game shows massive amount of artifacts on distant (and sometimes nearby) terrain and flickers as the camera moves, which isn't present with Wine's own D3D11 implementation. No other rendering issues except this one. Unfortunately it is very laggy (<0.3 fps) and takes nearly half an hour to load during API tracing so I only traced the minimal frames to show the bug with the login portion trimmed.

**Comment by doitsujin** [comment]
This is z-fighting that occurs because the game relies on two *different* vertex shaders to produce the *same* numerical values. I'm not sure if this can be fixed.

FWIW it doesn't happen with amdvlk, but that's probably just luck and can break any time.

**Comment by aufkrawall** [comment]
I wonder if this might be also beneficial for this radv Just Cause 3 issue:
https://gitlab.freedesktop.org/mesa/mesa/issues/851

**Comment by doitsujin** [comment]
Doubt it since that issue is over a year old, whereas the NIR optimizations that break our stuff are very recent.

**Comment by PkmX** [comment]
I can confirm in-game that it is indeed resolved. Thanks for the quick fix!
