### ISSUE TITLE
Gothic 3 Shadows not rendered properly

### ISSUE THREAD

**Issue by VortexAcherontic** [doitsujin/dxvk#1367]
### Software information
- Game: Gothic 3, Community Patch 1.73
- Settings: Very High / 1080p@60
- Distro: openSUSE Tumbleweed (Snapshot: 20200121)
- Kernel: 5.4.12

### System information
- GPU: GTX 1080
- Driver: 440.44
- Wine version: 4.21 (lutris-4.21-x86_64)
- DXVK version: 1.5.1

### Apitrace file(s)
-  [WineD3D](https://drive.google.com/open?id=1MozbySfsQKnxH4s-oJ_fJ_bkx3gX6gav)
- [DXVK](https://drive.google.com/open?id=10Ubp5j8iJ_vNWfDZ-CfTva3wRUdSy5CQ)
(I hope the API Trace is OK since for me the d3dretrace via Wine renders all 3D geometry black)

### Log files
- d3d9.log: https://pastebin.com/6LWbikqD
- dxgi.log: Did not found any, is this normal?

#### WineD3D:
![Screenshot_20200124_113817](https://user-images.githubusercontent.com/11244092/73063886-26828980-3ea0-11ea-829e-b4fe09c5f2c8.png)

#### D9VK/DXVK:
![Screenshot_20200124_115700](https://user-images.githubusercontent.com/11244092/73064082-b45e7480-3ea0-11ea-8af1-a5b4b7c26a02.png)

**Comment by doitsujin** [comment]
The trace is indeed not super useful since it renders all black. Do you have access to a Windows machine or can you try recording the trace with DXVK active (*could* still produce useful results)?

**Comment by doitsujin** [comment]
Can you try latest master ([here](https://git.froggi.es/doitsujin/dxvk/-/jobs/1106)'s a build)?

Apparently this issue was known for a while but the workaround somehow never made it in.

**Comment by doitsujin** [comment]
Attempt number 2, please check if [this](https://git.froggi.es/doitsujin/dxvk/-/jobs/1107) build works.

**Comment by Joshua-Ashton** [comment]
I wonder if we should only do this on AMD?

**Comment by VortexAcherontic** [comment]
So I went trough a lot of test and examined the issue a lot.

1) First as I tinkered around with more recent community patches and other mods the shadow issue magically went away in some of those patches, so I created a test installation and ran each community patch and checked in-game:
- 1.73: Bug described above
- 1.74: Still contains the bug
- 1.75: Fixes the issues but also introduces bad performance

2) The DXVK trace has been added to the initial post but also that one renders 3D geometry black independent of using DXVK to retrace or WineD3D.

3) The new master (Build: 1025): Fixed the issue with 1.73 and 1.74, many thanks :)

4) Yes I do have access to a (outdated because it refuses to update because some build of Win10 refuse to install themselves if the PC is dual booted with a non Windows OS) Windows 10 installation.

**Comment by VortexAcherontic** [comment]
Checked 1.5.2 release and the issue is fixed. I'll close this issue here, thank you for your time to fix this :)

![Screenshot_20200125_115037](https://user-images.githubusercontent.com/11244092/73119972-14b8e900-3f69-11ea-98d5-d5ba1dfe2248.png)

**Comment by jarrard** [comment]
How are you getting 132 FPS? is this gothic3 forsaken gods edition? I can only get 5fps!

**Comment by VortexAcherontic** [comment]
@jarrard It is the Enhanced Edition with Community Patch 1.74.
1.75 introduces very bad performance. With 1.75 I only get 20fps max. Do you have 1.75 installed?

**Comment by jug007** [comment]
That feel when you play gothic 3 and suddently there is a gothic 3 related patch.
For info: I have been playing the normal Gothic 3 Steam version with 50-130 fps.

**Comment by jarrard** [comment]
I just installed whatever steam decides mate. Never heard anything about community patch. 

Anyway Gothic 3, runtime error on launch, only Gothic 3 Forsaken Gods launches up and it gets 5fps with d9vk.

**Comment by jug007** [comment]
Now that you say it.. I have had to do that one or two times in the past with games on Proton. I *think* Gothic 3 might have even been one of those games, but it has been like a year.

**Comment by jarrard** [comment]
The issue is for some reason proton doesn't install the required library addon files such as physX, even if you delete the prefix and run the game again, it ignores the custom installers for those things. Its a odd bug.
