### ISSUE TITLE
We need frog release names

### ISSUE THREAD

**Issue by DadSchoorse** [doitsujin/dxvk#1371]
# Bring back the frogs :frog:

**Comment by BillFleming** [comment]
As D9VK had frog release names this is actually a serious regression, not an enhancement request. 
![image](https://user-images.githubusercontent.com/41557749/73124600-c1439c80-3f62-11ea-9503-b063a6d2a0a5.png) ![image](https://user-images.githubusercontent.com/41557749/73124641-3adb8a80-3f63-11ea-8f71-8c305c97949d.png)
I need a minimum number of frogs to balance the pond in my rig.

**Comment by DadSchoorse** [comment]
# Examples of correct behavior:
## Version 0.40 - Croakacola 🥤🐸
## Version 0.30 - Froglet 🐸🍼
Smol frogs be like: ᵣᵢᵦᵦᵢₜ ᵣᵢᵦᵦᵢₜ :frog: :baby_bottle:
## Version 0.22 - Kero Kero 🐸🐸
Ribbit :frog:
## Version 0.21 - Lollihop
I know, the pun really sucks :lollipop::frog:
## Version 0.20 - Frog Cookie 🐸🍪
henlo 🦢
:frog::cookie::frog: Frog Cookies Detected :frog::cookie::frog:
:frog::cookie::frog: Eat the frog cookies! :frog::cookie::frog:
## Version 0.13f - Hypnofrog
Croak, here to release 0.13f. (the f stands for :frog:)
## Version 0.13 - Hypnotoad
Ribbit, here is 0.13 for you all. It's been a while since we marked a stable release :frog:
:frog::frog: Hypnotoad commands you to download! :frog::frog:
## Version 0.12 - Cool Lookin' Blue Frog
Hi! I'm happy and pleased to release version 0.12 for all you froggos out there :frog: :heart: :smile:
Hope you enjoy, ribbit! :frog:
## Version 0.11 - Poison Dart
hi im release 0.11 now enjoy frog
i called it poison dart because thats like a frog thing isnt it
wahoo

**Comment by t14462** [comment]
NEXT major release must be Toad Hovvard

**Comment by kassindornelles** [comment]
why u not fix developer

**Comment by BillFleming** [comment]
![image](https://user-images.githubusercontent.com/41557749/73506001-c7d67780-4399-11ea-98d9-5cd590c492c0.png)

**Comment by Joshua-Ashton** [comment]
@doitsujin Have a seat:

![froggychair](https://user-images.githubusercontent.com/21316711/73509044-b57a2f00-43d5-11ea-8a8b-c8d061bdeafc.png)

**Comment by ZachBacon** [comment]
Froggin hell, what's with this issue?

**Comment by BillFleming** [comment]
You would think that with many of the devs going to Fosdem that Philip could take the time this weekend to fix this. Sad. ![image](https://user-images.githubusercontent.com/41557749/73603309-512aad00-4546-11ea-95c0-f54dbd763fcd.png)

**Comment by doitsujin** [comment]
What's Fosdem? I heard there's a conference at Brussels called Frogdem, but that can't possibly be what you're referring to, can it?

**Comment by imaami** [comment]
I'm getting sporadic frame rate stutters lately. I'm fairly certain it's because the graphics pipeline needs frog names.

**Comment by BillFleming** [comment]
![image](https://user-images.githubusercontent.com/41557749/74029621-b29db200-4972-11ea-9568-743eaf74a7f0.png)

**Comment by Vash63** [comment]
One note that could move this from a simple regression fix to a true enhancement would be if the release name was also appended to the version number displayed in DXVK_HUD. For example: 
```
DXVK v1.6.0-WetToadsInYourArea
D3D11
GeForce RTX 2080
Driver: 440.48.02
Vulkan: 1.2.131
FPS: 64
```

**Comment by kassindornelles** [comment]
still not fixed, kinda expected anyway.......
i heard dxvk is in maintanance mode right now...

**Comment by DadSchoorse** [comment]
still not fixed!
![grafik](https://user-images.githubusercontent.com/49841484/75187704-e20e3600-574a-11ea-9992-22d242846f1b.png)
Wenn das der Kaiser wüsste!

**Comment by sambow23** [comment]
we cant leave the frogs hanging, bring back froggy release names

**Comment by ZachBacon** [comment]
can we make this a priority number 1 please, this is croaking painful!

**Comment by tuxayo** [comment]
Who would have guessed a side effect of merging D9VK be a frog invasion.

**Comment by Joshua-Ashton** [comment]
🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸
🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸
🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸
🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸
🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸🐸

**Comment by tuxayo** [comment]
**\*The Imperial March plays***

**Comment by Joshua-Ashton** [comment]
bruh
