### ISSUE TITLE
[d3d9] Gothic 3 CPT 1.75: all is black

### ISSUE THREAD

**Issue by ziabice** [doitsujin/dxvk#1372]
As you can see from the attached screenshot, Gothic 3 is rendered all black and with very poor performance. If I followed D9VK development correctly, this should be already been fixed, but not on my end. 

I tried various launch options, different graphic detail, but nothing changed: I got always the same result.

Game renders correctly using WineD3D, but is even more slow and unplayable.

### Software information
Gothic 3, CPT 1.75 beta branch

### System information
- GPU: AMD RX 580 4GB
- Driver: Mesa 19.3.2
- Wine version: Proton 4.11-12
- DXVK version: 1.5.1 (the one bundled with Proton)

### Log files
- d3d9.log: [steam-39500.log](https://github.com/doitsujin/dxvk/files/4111789/steam-39500.log)
- d3d11.log:
- dxgi.log:

![Screenshot_20200125_100259](https://user-images.githubusercontent.com/28961115/73118977-d406a300-3f5b-11ea-8ad3-7c43862eb6b1.png)

**Comment by doitsujin** [comment]
Can you try 1.5.2?

Also, are you using native d3dcompiler and d3dx9 dlls?

**Comment by VortexAcherontic** [comment]
@ziabice I ran the game using `winetricks d3d9` if this helps you out.

**Comment by doitsujin** [comment]
Ok, mystery solved, for some reason your exe name is different than everyone else's (`Gothic3Final.exe` vs `Gothic3.exe`)

You can fix this for the time being by putting the following things into `dxvk.conf`:
```
d3d9.allowLockFlagReadonly = False
d3d9.supportDFFormats = False
```

**Comment by ziabice** [comment]
Thanks to your help it works now.

Here's what I did:

1. created the `dxvk.conf` in my home directory adding the settings you said:

```
d3d9.allowLockFlagReadonly = False
d3d9.supportDFFormats = False
```

(please note: no `[gothic3.exe]` or `[Gothic3.exe]` before the options because it didn't work)

2. Used this launch options in Steam: `PROTON_FORCE_LARGE_ADDRESS_AWARE=1 PROTON_USE_D9VK=1 PROTON_LOG=1 DXVK_HUD=full DXVK_CONFIG_FILE=/home/luca/dxvk.conf %command%`

And the game worked as expected. Like crap, but it worked. I have nearly no GPU utilization and  FPS varying from 10 to 40.

I can see shadows even with DXVK 1.5.1 supplied with Proton 4.11-12, despite what stated in #1367.

**Comment by doitsujin** [comment]
> (please note: no [gothic3.exe] or [Gothic3.exe] before the options because it didn't work)

The game exe is `Gothic3Final.exe` in your case, **not** `Gothic3.exe`. This is the same reason why the default workarounds didn't apply.

> I can see shadows even with DXVK 1.5.1

That's because you set `d3d9.supportDFFormats = False`. Remove that line and you'll get broken shadows.

**Comment by ziabice** [comment]
> > (please note: no [gothic3.exe] or [Gothic3.exe] before the options because it didn't work)
> 
> The game exe is `Gothic3Final.exe` in your case, **not** `Gothic3.exe`. This is the same reason why the default workarounds didn't apply.
> 

You are absolutely correct! :+1: 

Just for the record, into the game dir there are two executables: `Gothic3.exe` and `Gothic3Final.exe`.

Thanks very much for the clarifications! :heart:
