### ISSUE TITLE
Killing Floor poor performace

### ISSUE THREAD

**Issue by siyia2** [doitsujin/dxvk#1373]
Huge stuttering when compilling shaders on killing floor 1 compared to the native opengl api, tested with both aco compiler and llvm 9 no significant change.

### System information

    GPU: AMD RX 550 4GB
    CPU: FX 8300
    RAM: 12GB
    Driver: Mesa 19.3.2
    Wine version: Proton 4.11-12
    DXVK version: 1.5.1 (the one bundled with Proton)

**Comment by doitsujin** [comment]
Yes, that's normal, can't be fixed.

**Comment by siyia2** [comment]
well how come in other high end games like dying light dxvk doesn't stutter?

**Comment by doitsujin** [comment]
They do too.

**Comment by siyia2** [comment]
so if i run the kf and trigger all possible shader compilations , then there wont be any stuttering the second time?

**Comment by LethalManBoob** [comment]
I would like to add the stuttering is still present and makes the game unplayable, even today with the latest codebase.

**Comment by siyia2** [comment]
For me it does not stutter anymore with dx9 and the new shader pipeline.

**Comment by siyia2** [comment]
@LethalManBoob  what mesa version are you using?

**Comment by LethalManBoob** [comment]
> @LethalManBoob what mesa version are you using?

To be clear I am using the latest nvidia driver.

**Comment by siyia2** [comment]
For me with amd and mesa 24.2.0 no stuttering.

**Comment by LethalManBoob** [comment]
> @LethalManBoob For me with amd mesa 24.2.0 and latest dxvk no stuttering.

Well good for you.

**Comment by Blisto91** [comment]
Isn't it just regular Unreal Engine shader stutter like on Windows?

**Comment by LethalManBoob** [comment]
> Isn't it just regular Unreal Engine shader stutter like on Windows?

No this is somthing different. no other unreal engine 2 game stutters like this except unreal 2 but even then not this badly.

**Comment by Blisto91** [comment]
Best would be to open a new issue and fill out the template.
