### ISSUE TITLE
Games stopped working since d9vk was introduced

### ISSUE THREAD

**Issue by Sebastiangperez** [doitsujin/dxvk#1374]
Since d9vk was introduced  many of my games stopped working , if i switch to an old version of dxvk  works great with a few bugs but works.
Today i installed 1.5.2 and still don't work, can be something to do with the new install ?  
My nvidia driver is 430.26  and Fedora 29.

**Comment by lucifertdark** [comment]
You need the newer 440 drivers.

**Comment by Sebastiangperez** [comment]
Shit, Thanks, the documentation is out of date ... checki it.

**Comment by doitsujin** [comment]
Closing because this report contains new information.

Feel free to open a new issue if you are at least willing to tell us **which** games stopped working and can provide log files.
