### ISSUE TITLE
[d3d9] TrackMania United Forever: freeze after choosing a medal ghost

### ISSUE THREAD

**Issue by AlexTMjugador** [doitsujin/dxvk#1375]
This issue was originally reported in #1363 by @Iglu47 and me, but as I like to keep things ordered I opened this issue specifically for it, as the original one has 41 comments and it's getting pretty messy.

> confirm freeze after choosing a medal ghost
track: united => race => bayA1
i checked master-git, dxvk 1.5.1 and d9vk 0.22 version - all 3 freezes
and no freezes on default wineD3D

> It freezes for me on a Nadeo bay track, with both the provided DLL and DXVK 1.5.1, just after choosing a medal ghost. But not all bay tracks are affected.

However, if the shadows are turned down to PC2, @Iglu47 says that the issue is gone:

> PC2 no have this issue and freeze issue - so game still good playble

### Software information
TrackMania United Forever, maximum settings.

### System information
@Iglu47 system specs:
- GPU: NVIDIA GTX 1080 Ti.
- Driver: NVIDIA propietary driver, 440.48.2.
- Wine version: Wine-TkG 5.0.r2.
- DXVK version: DXVK 1.5.1-53-g38a0d2c5.

My system specs:

- CPU: Intel Core i3-2100 @ 3209 MHz.
- GPU: NVIDIA, MSI GeForce GTX 1650 Ventus XS.
- Driver: Debian Bullseye NVIDIA propietary driver, 430.64 (package version 430.64-6).
- Wine version: wine-4.21 (Debian 4.21-2).
- DXVK version: 1.5.2.

### Apitrace file(s)
- https://drive.google.com/open?id=1G0HEoHgXPy-9fvCfNh-Z98Q1cKXFvu0- (provided by @Iglu47)

### Log files
- d3d9.log: https://github.com/doitsujin/dxvk/files/4109102/TmForever_d3d9.log (provided by @Iglu47)
- d3d11.log: N/A.
- dxgi.log: N/A.

**Comment by Iglu47** [comment]
game can show Replay other players, so i made `TmForever.exe /silent /bench=X_BayA1.Replay.gbx` for "less size"
apitrace:https://drive.google.com/open?id=1Rtq8QOEGFc9P1okckZ50_q6eIuBonYkt
d3d9.log:https://drive.google.com/open?id=1sOepD9Wp7XhMBdslfgyOQXzn6DiNhj0M

**Comment by doitsujin** [comment]
What exactly are we supposed to see here? The apitrace replays fine on my end.

Also, I guess it's fine to open a new issue for bugs but please don't spam our bug tracker with **three** issues for one single game.

**Comment by Iglu47** [comment]
yes, this is hopeless because I cannot record a complete trace
the game just stops drawing new frames at the moment when the race should begin
and it does not crash, so have to close it forcibly

**Comment by mrdeathjr28** [comment]
similar problem appears in warriors orochi / orochi 2 / samurai warriors 2
if shader quality stay in low game entry correctly but with shader qualityin medium or more game freeze

**Comment by Iglu47** [comment]
I tried next liquorix version and arch-LTS version of kernel and found (`sudo journalctl -p 3 -xb` and `dmesg`) that "freeze" actually is nvidia Xid error 8 - "GPU stopped processing"

**Comment by Joshua-Ashton** [comment]
Can you get me an `nvidia-bug-report`?

**Comment by Iglu47** [comment]
i made game app to window mode and run nvidia-script after "freeze"- all in one x-session 
@Joshua-Ashton [nvidia-bug-report.log](https://mega.nz/#!rEkHQKaa!kHEvAnkxerg-Yb7y1UM2ndED69AZOAx05U71G9Z3aKQ)

**Comment by CME42** [comment]
The game is using swvp and triggers this validation error on nv:
```
VUID-VkWriteDescriptorSet-descriptorType-00332(ERROR / SPEC): msgNum: 0 - vkUpdateDescriptorSetWithTemplate() failed write update validation for VkDescriptorSet 0x2dda0000002dda[] with error: Write update to VkDescriptorSet VkDescriptorSet 0x2dda0000002dda[] allocated with VkDescriptorSetLayout VkDescriptorSetLayout 0x2ca90000002ca9[] binding #0 failed with error message: Attempted write update to buffer descriptor failed due to: VkDescriptorBufferInfo range is 164096 which is greater than this device's maxUniformBufferRange (65536). The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER or VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC, the range member of each element of pBufferInfo, or the effective range if range is VK_WHOLE_SIZE, must be less than or equal to VkPhysicalDeviceLimits::maxUniformBufferRange (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-00332)
```
