### ISSUE TITLE
(d9vk) GOG Torchlight start menu glide from left to right

### ISSUE THREAD

**Issue by cork** [doitsujin/dxvk#1378]
Everything except the two characters on screen gets a kind of scrolling shutter effect from left to right.

video of rendering bug: https://vimeo.com/387279548

### Software information
Torchlight, nothing changed from wine and game defaults except installing dxvk

### System information
- GPU: GeForce GTX 880M
- Driver: nvidia-dkms 440.44-14
- Wine version: wine-5.0 (Staging)
- DXVK version: dxvk 1.5.2.r4 (c77a9e3bfef67cd5f673b24665aafa8eec4ce662)

### Apitrace file(s)
https://ufile.io/hufjq9dq (note rendering problems not visible when generating this trace)

### Log files
[Torchlight_d3d9.log](https://github.com/doitsujin/dxvk/files/4113838/Torchlight_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Hm, the trace plays back fine. 
![image](https://user-images.githubusercontent.com/21316711/73139884-92185280-406a-11ea-9c8a-48e8c774c90d.png)

I know this game used to work, can anyone else confirm?
