### ISSUE TITLE
Torchligh II GOG crashes during loading (DX9)

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [doitsujin/dxvk#1380]
Torchlight II crashes during loading using d9vk, but it runs fine using wined3d.

### System information
- GPU: AMD Radeon HD 8750M
- Driver: Mesa 19.3.2 (kisak-mesa ppa)
- Wine version: wine-staging 5.0
- DXVK version: 1.5.2

### Log files
- d3d9.log: [Torchlight2_d3d9.log](https://github.com/doitsujin/dxvk/files/4120014/Torchlight2_d3d9.log)
- terminal.log: [Torchlight 2.txt](https://github.com/doitsujin/dxvk/files/4120016/Torchlight.2.txt)

**Comment by doitsujin** [comment]
The game is [known to run](https://github.com/doitsujin/dxvk/issues/1378) more or less fine with DXVK. Please make sure you have native `d3dx9` and `d3dcompiler` libraries installed.

Also, what exactly do you mean by crash?`The terminal output you posted doesn't look like it crashed.

**Comment by ahmed-elsayed2017** [comment]
It gives this message, and I press cancel:

![Runic Games Crash Reporter_001](https://user-images.githubusercontent.com/29783425/73226309-3a680d00-4178-11ea-95b6-ec816d329dbc.png)

**Comment by Joshua-Ashton** [comment]
Does the game work with WineD3D?

**Comment by ahmed-elsayed2017** [comment]
> Does the game work with WineD3D?

Yes.

**Comment by Joshua-Ashton** [comment]
Hm, the trace I have plays back fine with no errors, and I know this used to work 
![image](https://user-images.githubusercontent.com/21316711/73226441-f8cf6600-4167-11ea-8928-6168af455c0c.png)

Did you install native d3dx9 and d3dcompiler? And if so, which versions

**Comment by ahmed-elsayed2017** [comment]
I have d3dx9_24.dll to d3dx9_41.dll, I have also, d3dcompiler_42.dll, d3dcompiler_43.dll, and d3dcompiler_47.dll, and all set to native.

I installed them using winetricks.

**Comment by ahmed-elsayed2017** [comment]
Using AMDVLK instead of RADV gives an error message about a required extension that is not supported

```
D3D9 : Direct3D9 Rendering Subsystem created.
info:  Game: Torchlight2.exe
info:  DXVK: v1.5.2
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Required Vulkan extension VK_KHR_surface not supported
terminate called after throwing an instance of 'dxvk::DxvkError'

abnormal program termination
```

**Comment by Joshua-Ashton** [comment]
Looks like a setup issue if that isn't supported.

**Comment by ahmed-elsayed2017** [comment]
I don't get the same error with RADV. Anyway, I tried Padoka ppa instead of kisak-mesa ppa, and I got the same results.

**Comment by saboya** [comment]
Did you test other games with DXVK? Do they work properly?

**Comment by Kron4ek** [comment]
The game crashes for me too on DXVK 1.5.2, but it works fine on the latest git build.

**Comment by ahmed-elsayed2017** [comment]
> The game crashes for me too on DXVK 1.5.2, but it works fine on the latest git build.

Thanks for confirming the issue.

I can't build DXVK manually, because I have the same build issue as this one https://github.com/doitsujin/dxvk/issues/766

Could you upload the latest git build?

**Comment by Kron4ek** [comment]
https://git.froggi.es/doitsujin/dxvk/-/jobs

**Comment by ahmed-elsayed2017** [comment]
Thanks. The game works now, but the performance is much worse than wined3d. My GPU doesn't wok well with d9vk, but I have to be able to use vkBasalt.

**Comment by Joshua-Ashton** [comment]
@ahmed-elsayed2017 Hi, can you set ``d3d9.floatEmulation = False`` in dxvk.conf and see if that improves performance for you?

**Comment by ahmed-elsayed2017** [comment]
> @ahmed-elsayed2017 Hi, can you set `d3d9.floatEmulation = False` in dxvk.conf and see if that improves performance for you?

I copied a copy of dxvk.conf to the game folder next to the executable of the game, and added this option, and tried the game with it, and without it, and I didn't notice any difference unfortunately.

**Comment by Joshua-Ashton** [comment]
Can you send me logs of you with that option added?

**Comment by ahmed-elsayed2017** [comment]
> Can you send me logs of you with that option added?

[Torchlight2.txt](https://github.com/doitsujin/dxvk/files/4123903/Torchlight2.txt)

**Comment by ahmed-elsayed2017** [comment]
The issue with this game crashing is fixed, so I see no need to keep this issue opened.
