### ISSUE TITLE
Frostpunk (many other ) and 1.5.2 don't run

### ISSUE THREAD

**Issue by Sebastiangperez** [doitsujin/dxvk#1381]
The game runs with 1.4.4 version but do not with 1.5.X 

### Software information
Frostpunk

### System information
- GPU:Nvidia 980
- Driver: 440.44
- Wine version:  4.15 staging
- DXVK version: 1.5.2

### Log files
- d3d9.log:
- d3d11.log: this file is empty
[Frostpunk_dxgi.log]
(https://github.com/doitsujin/dxvk/files/4122143/Frostpunk_dxgi.log)

**Comment by doitsujin** [comment]
Frostpunk works fine with 1.5.2, please make sure that your DXVK is installed correctly. The fact that your log file is empty means that the game does not even try to create a D3D11 device.

**Comment by mozo78** [comment]
Works Ok with 1.5.2 here.

**Comment by Sebastiangperez** [comment]
> Frostpunk works fine with 1.5.2, please make sure that your DXVK is installed correctly. The fact that your log file is empty means that the game does not even try to create a D3D11 device.
> 
> Also it's not clear what "doesn't work" means (does it crash?), and please update your wine while you're at it.

I used the installer properly , the one that came with the lastet versions and the old one using winetricks , in both cases the files were copied in the folders, besides , i did the same using the old dxvk version, the 1.4.4. ( i didn't use both at the same time :P)
When i said that did not run, im runned wine using a virtual desktop for testing pourposes, this windows opened up and then closed after a few seconds. 
I think the problem, in my case, is with the implementation of directx 9, maybe i missed something that i need to install? any configuration?.
Thanks

**Comment by doitsujin** [comment]
Please try setting up a fresh wine prefix and try again.

**Comment by Sebastiangperez** [comment]
Ok, i will do that. 
Thanks

**Comment by mozo78** [comment]
The game runs out-of-the-box. You'll need only Wine and DXVK.

**Comment by Sebastiangperez** [comment]
> The game runs out-of-the-box. You'll need only Wine and DXVK.

Ok ,but, i mean, not for this game only, maybe an standard list of libraries that i need to install like vc2010 , directx. 
I will test the game at night.

**Comment by mozo78** [comment]
You should set separatet prefix for every game. There isn't universal prefix setup.

**Comment by Sebastiangperez** [comment]
I have one for all my games and worked great, i will try to implement that from now on. 
Thanks

**Comment by Iglu47** [comment]
@Sebastiangperez any progress with that?
i have gog version and next quote seems correct
> The game runs out-of-the-box. You'll need only Wine and DXVK. 

this game don't need winetricks or similar workarounds
![frostpunk_gog](https://user-images.githubusercontent.com/25866099/77237037-77c7a480-6bd5-11ea-9553-6dc7e39ac435.png)

**Comment by Sebastiangperez** [comment]
> @Sebastiangperez any progress with that?
> i have gog version and next quote seems correct
> 
> > The game runs out-of-the-box. You'll need only Wine and DXVK.
> 
> this game don't need winetricks or similar workarounds
> ![frostpunk_gog](https://user-images.githubusercontent.com/25866099/77237037-77c7a480-6bd5-11ea-9553-6dc7e39ac435.png)

Yes , i just created a fresh new prefix and installed the game , worked great , maybe there were something odd with my wine default prefix.
