### ISSUE TITLE
Specific Unity games crashing

### ISSUE THREAD

**Issue by TheGamingDreemurr** [doitsujin/dxvk#1385]
### Software information
VRChat
Boneworks
The Forest

Alright so... This is really bizarre.

Basically, what's happening is that if i apply the appropriate dlls for DXVK for certain unity games, like Boneworks, VRChat, or The Forest, those games crash out. And when i check the unity crash logs, it says that Vulkan-1.dll had an access violation. But if I do it in another unity game like Defunct, it works fine.

DXVK also works with other games I've tested that aren't on the same engine and most, if not, all of them are working fine (examples being A Hat in Time, Black Mesa, and others).

Is there an explanation as to why this happens? The specific access violation is 0xc0000005 in the logs for the unity games that crashed.

The games also crash out without being zombie-processes. Just wanna put that out there too.

### System information
- GPU: Geforce GTX 1060 6GB (EVGA OC)
- Driver: 441.99 
- DXVK version: 1.5.2 
- OS: Windows 10

**Comment by Joshua-Ashton** [comment]
DXVK will not work with OpenVR on Windows 10.

**Comment by doitsujin** [comment]
What Joshua said.
