### ISSUE TITLE
[d3d8to9] black texture when using d3d8 to d3d9 wrapper

### ISSUE THREAD

**Issue by l12436** [doitsujin/dxvk#1386]
### Software information
MHOnline

### System information
- GPU: GTX 1060
- Driver:440.48.02
- Wine version: 5.0
- DXVK version: 1.5.2 (git master b1edf227f8a6e87a3115e2b0839d9bfb9454d117)

### ApiTrace
- [trace](https://www.mediafire.com/file/gk3khgt5h72ma52/result.trace.xz/file)

### Log files
- d3d9.log:
[MHClient-Connect_d3d9.log.gz](https://github.com/doitsujin/dxvk/files/4126154/MHClient-Connect_d3d9.log.gz)

With d3d8tod3d9 and without dxvk(d3d9)
![Screenshot_20200129_122240](https://user-images.githubusercontent.com/2596649/73327760-27e1f680-4292-11ea-8e34-6ef9c0385f6f.png)

With d3d8tod3d9 and dxvk(d3d9)
![Screenshot_20200129_122124](https://user-images.githubusercontent.com/2596649/73327776-3e884d80-4292-11ea-864f-5703ab384253.png)

**Comment by Joshua-Ashton** [comment]
apitrace?

**Comment by l12436** [comment]
uploaded, tell me if trace is incorrectly.

**Comment by Joshua-Ashton** [comment]
hm, this replays fine for me

![image](https://user-images.githubusercontent.com/21316711/73381482-bcae1980-42bd-11ea-8e73-bd837fb625fe.png)

**Comment by l12436** [comment]
> hm, this replays fine for me
> 
> ![image](https://user-images.githubusercontent.com/21316711/73381482-bcae1980-42bd-11ea-8e73-bd837fb625fe.png)

I record it by windows, It should be normal. Did I need to record under wine ?

**Comment by RinMaru** [comment]
> > hm, this replays fine for me
> > ![image](https://user-images.githubusercontent.com/21316711/73381482-bcae1980-42bd-11ea-8e73-bd837fb625fe.png)
> 
> I record it by windows, It should be normal. Did I need to record under wine ?
> 
> and by the way, the game is using d3d8, I using wrapper to make it using d3d9

that means its a windows issue and probably wont be fixed especially if it runs fine on wine.

**Comment by Joshua-Ashton** [comment]
can you record one under wine please?

**Comment by l12436** [comment]
[trace](https://www.mediafire.com/file/o2ak2l88w8vgzor/ms-wine.trace.xz/file)
here you are
tell me if something wrong.

**Comment by ViNi-Arco** [comment]
@l12436 Can you try with this new version of d3d8to9 to see if it works?

https://github.com/crosire/d3d8to9/files/4145820/d3d8.zip

**Comment by l12436** [comment]
> @l12436 Can you try with this new version of d3d8to9 to see if it works?
> 
> https://github.com/crosire/d3d8to9/releases/download/v1.11.0/d3d8.dll

no, still black texture.

**Comment by Joshua-Ashton** [comment]
Can you please try with latest master? ( as of https://github.com/doitsujin/dxvk/commit/b9474cf787f52e3faf8fa670bdb85ce058d47ade )

Build: https://git.froggi.es/doitsujin/dxvk/-/jobs/1137

**Comment by l12436** [comment]
> Can you please try with latest master? ( as of [b9474cf](https://github.com/doitsujin/dxvk/commit/b9474cf787f52e3faf8fa670bdb85ce058d47ade) )
> 
> Build: https://git.froggi.es/doitsujin/dxvk/-/jobs/1137

nope, still black texture. 
I update latest d3d8tod3d9 and d9vk.

**Comment by rtentser** [comment]
>> 440.48.02
Did you try 440.59?

**Comment by l12436** [comment]
> > 440.48.02
> 
> Did you try 440.59?

I just tested, nothing changed

**Comment by Blisto91** [comment]
@l12436 Friendly ping. Could you try again with latest version? :slightly_smiling_face:

**Comment by Blisto91** [comment]
Couldn't get the game running at all. If you still have the issue then just comment again.
I've been told it's possible this could be a d3dcompiler issue tho. So you could try some of them from winetricks.
