### ISSUE TITLE
[d3d9] King's Bounty: The Legend water issue

### ISSUE THREAD

**Issue by HanFox** [doitsujin/dxvk#1387]
The game runs fine for the most part, just some weird issues with water "reflections" that I'm not seeing anyone else post on ProtonDB or elsewhere. Even more strange, the "reflections" don't seem to be rendered in Windows at all (i.e. the protagonist isn't mirrored in the surface, or anything like that).

### Software information
Game: King's Bounty: The Legend
Settings: All on max; changing them seems to make no difference to the issue

### System information
- GPU: AMD 5700 XT (tried with and without ACO & with RADV and AMDVLK)
- Driver: mesa-git 1:20.0.0_devel.119683.fe5267d3223-1
- Wine version: Steam Proton 4.11-12
- DXVK version: 1.5.1 & 1.5.3

### Apitrace file(s)
https://www.mediafire.com/file/okuycpq46l4xosd/kb_trace.tar.gz/file

### Log files
[KB_d3d9.log](https://github.com/doitsujin/dxvk/files/4135365/KB_d3d9.log)

### Screenshots
D9VK:
![kings_bounty_legend_water_d9vk](https://user-images.githubusercontent.com/1781312/73474327-3c072000-4386-11ea-9d44-2fc6e0ba374f.jpg)

Windows:
![kings_bounty_legend_water_windows](https://user-images.githubusercontent.com/1781312/73474385-550fd100-4386-11ea-9687-5f8ce9d72e86.jpg)

**Comment by ziabice** [comment]
I have the same behavior:
![Screenshot_20200130_210157](https://user-images.githubusercontent.com/28961115/73485848-2dc7fc80-43a4-11ea-8d86-0c0416d165a8.png)


DXVK 1.5.1 (using Proton 4.11-12), Mesa 19.3.2 and AMD RX 580 4GB.

Seems more a problem with shadows, but there are some minor graphic glitches here and there, mostly in the upper part of the rendered screen.

The game works perfectly, nonetheless.

**Comment by Joshua-Ashton** [comment]
Fixed!

**Comment by HanFox** [comment]
Thanks for the quick fix :1st_place_medal:

**Comment by Joshua-Ashton** [comment]
No worries! Have fun :)
