### ISSUE TITLE
King's Bounty: the Legend (new, 2008) don't run

### ISSUE THREAD

**Issue by Lokidrow** [doitsujin/dxvk#1389]
The game runs with 1.5.2 version but do not with 1.5.2 and 1.5.3
Software information

Frostpunk
King's Bounty: the Legend (new, 2008)

    GPU:Nvidia 970
    Driver: 440.44
    Wine version: 5.0
    DXVK version: 1.5.2 and 1.5.3

Log files
kb_dxgi.log : empty

kb_d3d9.log :
info:  Game: kb.exe
info:  DXVK: v1.5.3
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface

(same as in Frostpunk in other issue)

But, in console there are another log:
WINEPREFIX=/mnt/main/.wine3 wine ./kb.exe
info:  Game: kb.exe
info:  DXVK: v1.5.3
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
0009:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-9
terminate called after throwing an instance of 'dxvk::DxvkError'

abnormal program termination

Fresh empty wine prefix.

Game works perfectly with 1.5.1 version

**Comment by doitsujin** [comment]
> 0009:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-9
terminate called after throwing an instance of 'dxvk::DxvkError'

Means that either either your system or your wine version doesn't support Vulkan 1.1. This is **not** a DXVK regression.

**Comment by Lokidrow** [comment]
openSuse 15.1

Where is log from starting game with 1.5.1 version
info:  Game: kb.exe
info:  DXVK: v1.5.1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
0009:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-9
warn:  Failed to create Vulkan 1.1 instance, falling back to 1.0
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  GeForce GTX 970:
info:    Driver: 440.44.0
info:    Vulkan: 1.1.119

Yes, vulkan 1.1 don't work

**Comment by Lokidrow** [comment]
===========
VULKAN INFO
===========

Vulkan API Version: 1.0.65

seems there are no 1.1 version in my opensuse :(

**Comment by Lokidrow** [comment]
I updated vulkan api and now game is working, issue closed, thanks

**Comment by Joshua-Ashton** [comment]
Yeah, please don't use OpenSUSE Leap for anything. Their Vulkan loader is 3 years old, and the Mesa is 1 year old so it's basically unusable with DXVK.

I'd super duper recommend updating Mesa too while you are at it if you're still using that distro.

**Comment by doitsujin** [comment]
> I'd super duper recommend updating Mesa too while you are at it if you're still using that distro.

OP is on Nvidia (actually a fairly recent version of it) so at least that part is fine.

Anyway I'd not recommend an enterprise distro for gaming purposes since these problems will just keep popping up. Just move to Tumbleweed.
