### ISSUE TITLE
Lineage 2 texture rendering

### ISSUE THREAD

**Issue by guglovich** [doitsujin/dxvk#1391]
Software information
The glow of clothes in the game is crookedly displayed, as if a white translucent film on clothes.
The problem appeared with the upgrade from 1.5.2 to 1.5.3

Screenshots
https://send.firefox.com/download/99a2ce17600f0c03/#82wXyM_rtHGZ_Bdj4LLtqQ
https://send.firefox.com/download/c264bb7a5abb1d65/#fvJt5FezT8PQk931eefZdQ

It should look like this, there are no problems with the native library.
https://imgur.com/BL5PtCD.png

### System information
- GPU: AMD RX 460
- Driver: Mesa RADV 19.3.3
- Wine version: wine-staging 5.0
- DXVK version: dxvk-winelib 1.5.3

### Apitrace file(s)
Did according to the instructions. trace is either not found or not created. DXVK was definitely disabled because hud was not displayed.

### Log files
- d3d9.log: [l2_d3d9.log](https://github.com/doitsujin/dxvk/files/4139610/l2_d3d9.log)

**Comment by doitsujin** [comment]
> Did according to the instructions. trace is either not found or not created.

How exactly did you do it?

We can't do anything without an apitrace so getting that to work should be the top priority.

**Comment by Joshua-Ashton** [comment]
This should be fixed as of 08fc5342a92c57fdd9008e60f357b8baa80cd867

**Comment by guglovich** [comment]
Thank you. The problem is completely resolved.
