### ISSUE TITLE
[d3d9] E.Y.E: Divine Cybermancy graphical artifact when aiming

### ISSUE THREAD

**Issue by TacoDeBoss** [doitsujin/dxvk#1392]
![20200131171054_1](https://user-images.githubusercontent.com/2870898/73583074-d08c8380-4455-11ea-96c2-896f38fadac4.jpg)

### Software information
E.Y.E: Divine Cybermancy (appid 91700), issue occurs on all settings.

### System information
- GPU: Radeon RX 5700XT
- Driver: mesa-git, latest as of writing
- Wine version: Proton 4.11-12
- DXVK version: 1.5.3

### Apitrace file(s)
This game appears to be untraceable from my efforts, resulting in a 124 byte trace and instant game crash on launch. If anyone has some suggestions, please do let me know.

### Log files
- d3d9.log: [EYE_d3d9.log](https://github.com/doitsujin/dxvk/files/4141937/EYE_d3d9.log)

This issue also used to occur on my GTX 1070 with the Nvidia proprietary driver, and the bug has been present since D9VK has existed. It is not present on wined3d.

**Comment by doitsujin** [comment]
> This game appears to be untraceable from my efforts, resulting in a 124 byte trace and instant game crash on launch. 

That's not particularly helpful and means that we won't be able to do anything until someone manages to get this to work. Are you trying to launch it via `apitrace.exe` or did you copy the d3d9.dll from apitrace? Were you using wined3d or dxvk when running apitrace?

**Comment by TacoDeBoss** [comment]
> That's not particularly helpful and means that we won't be able to do anything until someone manages to get this to work. Are you trying to launch it via `apitrace.exe` or did you copy the d3d9.dll from apitrace? Were you using wined3d or dxvk when running apitrace?

I copied the d3d9.dll file to the game directory and used wined3d to run the game. I tried with no success to generate a trace on Windows, but the game ignores any d3d9.dll in the game directory, be it apitrace or DXVK's.

**Comment by DustyCrumpet** [comment]
d3d9.dll needs to be placed in the `steamapps/common/EYE/bin` folder.
I can reproduce this issue with DXVK 1.5.3 on both Linux and Windows 10.

[Windows trace](https://drive.google.com/open?id=1CrUJwZ73gMVjr10QUvW3wysZ_e3TwzZB)

**Comment by doitsujin** [comment]
@DustyCrumpet thanks; annoyingly I cannot reproduce the problem since the trace renders fine. What's your GPU?

**Comment by DustyCrumpet** [comment]
I'm using an AMD Vega 56. Replaying the Windows trace looks correct here too, so here's a trace recorded with DXVK, hopefully it's useful.

[DXVK trace](https://drive.google.com/open?id=16GaniWdSUSrz0MDKA1kx-JEUP9VuQg8s)
