### ISSUE TITLE
Heroes of the Storm (HotS) graphics corruption after update to Mesa 19.3 

### ISSUE THREAD

**Issue by simonvanderveldt** [doitsujin/dxvk#1393]
This might be a Mesa issue since it's manifested itself after updating to 19.3 and when downgrading to 19.2 I don't have any issue but I figured I should check here first if there's an obvious reason this is happening + not sure how much support one gets for bugreports on Mesa when using applications through Wine/DXVK.

I'm seeing some sort of corruption, it looks a bit like it's at the edges of the tiles.
Screenshot below
![hots-mesa-19 3 3-dxvk-1 5 3-corruption](https://user-images.githubusercontent.com/204286/73598368-ca6ed380-4537-11ea-997e-d0f88ceb3a6f.png)

GPU: RX480
Driver: RADV, Mesa 19.3.3 ACO not enabled, although I get the same corruption with ACO enabled.
Wine: Staging 5.0
DXVK: 1.5.3

dxgi and d3d11 logs below
[HeroesOfTheStorm_x64_dxgi.log](https://github.com/doitsujin/dxvk/files/4143195/HeroesOfTheStorm_x64_dxgi.log)
[HeroesOfTheStorm_x64_d3d11.log](https://github.com/doitsujin/dxvk/files/4143196/HeroesOfTheStorm_x64_d3d11.log)

If this is something that is caused by/should be fixed by DXVK I can add an Apitrace of course.

**Comment by doitsujin** [comment]
If this is a Mesa regression, why not report this to Mesa instead?

**Comment by simonvanderveldt** [comment]
> If this is a Mesa regression, why not report this to Mesa instead?

Well, I listed those reasons in the first paragraph of the description. They might not be valid, I don't know.

Anyway, from your response I'm assuming this doesn't ring any bells and that you think it's a Mesa issue?
I've created a bug for Mesa https://gitlab.freedesktop.org/mesa/mesa/issues/2458 so feel free to close if this is not a DXVK bug.

**Comment by doitsujin** [comment]
Well the problem is that with a screenshot alone I can't do much. In general, if an update to software B breaks software A then software B is most likely what broke it.
