### ISSUE TITLE
Walking Dead Season 1 crash at launch

### ISSUE THREAD

**Issue by Animajosser** [doitsujin/dxvk#1394]
When starting The walking dead season 1 it loads up to "loading...." and crashes afterwards. I do have other d3d9 games that work correctly with dxvk/d9vk and it works with the wine opengl based implementation. It might be related to the issue here: https://github.com/doitsujin/dxvk/issues/1380. 
If an apitrace would be useful I will provide one later.

### Software information
Walking Dead Season 1 (GOG version) without settings

### System information
- GPU: GTX 770
- Driver: 19.99.99
- Wine version: 5.0
- DXVK version: 1.5.3

### Log files
[terminal.txt](https://github.com/doitsujin/dxvk/files/4143266/terminal.txt)

**Comment by guihkx** [comment]
I get the exact same error you're getting. I own a GTX 660.

However, setting `PROTON_FORCE_LARGE_ADDRESS_AWARE=1` fixed it for me (I'm running the Steam version of the game). The warnings about `Unknown format encountered` are still there, though.

**Comment by doitsujin** [comment]
You're running out of address space, see #1318 .
