### ISSUE TITLE
VRChat filling VRAM and general lowish performance

### ISSUE THREAD

**Issue by jug007** [doitsujin/dxvk#1395]
Running VRChat has very high VRAM usage when in front of a mirror and has general somewhat low performance (though I do not know if that performance is due to DXVK or VRChat itself). I didn't have any issues with VRAM back when I played on windows. Now when standing in front of a mirror, or sometimes even opening the overlay, the system runs out of VRAM.!

### Software information
VRChat on Steam, using SteamVR with the Valve Index.

### System information
- GPU: Nvida GTX 1080
- Driver: 440.48.02
- Wine version: Proton 4.11-12 (based on Wine 4.11)
- DXVK version: v1.5.1

### Apitrace file(s)
http://motofckr9k.ddns.net/m/VRChat.trace.7z

### Log files
- log of  nvidia-smi: [nvidialog.log](https://github.com/doitsujin/dxvk/files/4143310/nvidialog.log)
- Proton log: [steam-438100.log.zip](https://github.com/doitsujin/dxvk/files/4143307/steam-438100.log.zip)

To run the apitrace I used following command: `PROTON_LOG=1 PROTON_USE_WINED3D=1 "/media/motofckr9k/EffolenaMKII/SteamLibrary/steamapps/common/Proton 4.11/proton" waitforexitandrun /home/motofckr9k/Dokumente/apitrace-9.0.20191126-win64/bin/apitrace.exe trace -a dxgi /media/motofckr9k/EffolenaMKII/SteamLibrary/steamapps/common/VRChat/VRChat.exe && echo %command% >/dev/null`

Because of the low performance I was unable to get in front of a mirror in the apitrace.

I don't really know what I am doing, so please ask if any vital information is missing.

**Comment by doitsujin** [comment]
According to your Steam log, you#re using wined3d.

**Comment by jug007** [comment]
It seems that either DXVK or VRChat have a video memory leak.
As we are talking about VRChat.. It seems that VRChat has a video memory leak..
I was able to get the video memory usage to ~6500mb on normal usage. Changing to an empty world did not free any of that.

**Comment by Joshua-Ashton** [comment]
Is the leak present on Windows with native D3D11?

**Comment by jug007** [comment]
I cannot actually check. Made a bug report anyways: https://vrchat.canny.io/bug-reports/p/video-memory-leak
