### ISSUE TITLE
[d3d9] Jade Empire rendering issue

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#1398]
![jade_empire_dxvk](https://user-images.githubusercontent.com/6306593/73784160-a1e81300-479d-11ea-9e0b-223571775cf5.jpg)

I've recorded the issue in the game's main menu, but the same behaviour shows up during the actual game as well.

[Jade Empire main menu with dxvk](https://drive.google.com/open?id=1GagxvvKbYulYO_OA0flkUVcBFQue_K25)
[Jade Empire main menu with WineD3D](https://drive.google.com/open?id=1Fsko7Tl23dq_obwKV3vgQyGagj2CIqK0)

The second video was recorded in the same Wine prefix, after uninstalling dxvk.

As a side note, I also get extremely similar artifacts in The Witcher EE (this time only in game, the main menu looks fine). Other Bioware Aurora engine titles may similarly be affected.

Both Jade Empire and The Witcher EE work fine in a clean Wine Staging prefix (with a slight CPU affinity issue affecting Jade Empire, but that's beside the point).

### Software information
Jade Empire (GOG version, with the latest official patch).

### System information
- GPU: GeForce GTX 1070
- Driver: 435.21.0
- Wine version: 5.1 Staging
- DXVK version: v1.5.3

### Apitrace file(s)
[JadeEmpire.trace.tar.xz](https://drive.google.com/open?id=1qZ-JCV-F1vk5VOTZ1oTqmddMSL7syW6k)

### Log files
- d3d9.log: [JadeEmpire_d3d9.log](https://github.com/doitsujin/dxvk/files/4155814/JadeEmpire_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by Joshua-Ashton** [comment]
> 435.21.0

Please update your drivers.

**Comment by WinterSnowfall** [comment]
> > 435.21.0
> 
> Please update your drivers.

Ok, I'm on **440.48.2** now and the issue is still there...

**Comment by Joshua-Ashton** [comment]
Looks fine for me on `master` although I did have some work in my tree that may affect it (I pushed that now)

AMD:
![image](https://user-images.githubusercontent.com/21316711/73789968-a3aed800-4797-11ea-9045-57227fe2a151.png)

NV:
![image](https://user-images.githubusercontent.com/21316711/73790068-c9d47800-4797-11ea-87bc-74f3155f4f95.png)

I don't see any validation errors that could be the cause of what you are seeing.

Can you try on `master`?: https://git.froggi.es/doitsujin/dxvk/-/jobs/1132

**Comment by WinterSnowfall** [comment]
Thanks. Not sure what your latest changes were, but it's looking good for me too now. And I also tested The Witcher EE, and it looks good as well, the very similar noisy textures issue is gone. Next time I'll be more patient to wait for the next release, I guess :).
