### ISSUE TITLE
[d3d9] The Witcher EE - missing clouds / sky textures

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#1401]
![witcher_sky_dxvk](https://user-images.githubusercontent.com/6306593/73873391-30ba6580-485a-11ea-9f7c-db85a442281e.jpg)

Related to [#1399](https://github.com/doitsujin/dxvk/issues/1399), regarding the missing sky textures when the in-game visibility range is set to "Far" (anything below will bring back the clouds). 

The sun may be missing as well with dxvk considering the missing reflections/refraction in the water. All I have are cloudy weather saves (still better than negative thoughts), but if you think it's useful, I can dig a little and confirm this as well.

WineD3D will render everything correctly even on "Far":
![witcher_sky_wined3d](https://user-images.githubusercontent.com/6306593/73873117-ab36b580-4859-11ea-8dd5-6d7e1be3eda2.jpg)

### Software information
The Witcher EE (GOG version, latest build).

### System information
- GPU: GeForce GTX 1070
- Driver: 440.48.2
- Wine version: 5.1 Staging
- DXVK version: v1.5.3+87dd8f01

### Apitrace file(s)
[witcher.trace.tar.xz](https://drive.google.com/open?id=1Mce3QY_O7DNZTSCNsU8KxhdTA-u0Kbks)

### Log files
- d3d9.log: [witcher_d3d9.log](https://github.com/doitsujin/dxvk/files/4161493/witcher_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by WinterSnowfall** [comment]
... and the missing sun is confirmed by [#1402](https://github.com/doitsujin/dxvk/issues/1402) :)

**Comment by doitsujin** [comment]
Should be fixed with the PR mentioned above:
![Bildschirmfoto-1154](https://user-images.githubusercontent.com/25567304/73893771-db428080-487a-11ea-9469-b8acf035daf5.png)
