### ISSUE TITLE
Saints Row 4

### ISSUE THREAD

**Issue by NikoBellicRU** [doitsujin/dxvk#1403]
Hello im having a problem in this game for a long time and aparently this got semi fixed on the vulkan beta driver but the bug its still there but now only see it from a bit further away, also this bug is in saints row 3, here's the problem:  
https://github.com/doitsujin/dxvk/issues/1136

In the game at night it glitches dark artifacts and day white artifacts, also i dont have that problem on driver 415 /steamos.

### System information
- GPU:GTX 670
- Driver:440.48.02
- Wine version: Proton 4.11-12 latest
- DXVK version: 1.5.1

**Comment by doitsujin** [comment]
SR4 has always been broken for unknown reasons I think, and I don't plan to spend any more time on it. You can try setting `d3d11.invariantPosition = True` in your dxvk.conf and see if that improves anything.

> also i dont have that problem on driver 415 /steamos.

Kind of sounds like a driver regression then.

**Comment by NikoBellicRU** [comment]
Dude thats a lot i just tried that and worked flawlessly can you merge it into next dxvk release?

**Comment by NikoBellicRU** [comment]
Dude you are awesome that worked flawlessly no more glitches can you merge that into next dxvk release?

**Comment by doitsujin** [comment]
So that setting actually worked?

I can add an app profile to enable it by default, yes. What's the excecutable name for this game?

**Comment by NikoBellicRU** [comment]
Yeah i was surprised too im having this issue for a long time but its all runing fine now with that setting, i played for some hours didn't saw any glitches, i have this on my dxvk.conf file:

[SaintsRowIV.exe] 
d3d11.invariantPosition = True

Also like i said before saints row 3 has the same issue and now both dx9 and dx11 work fine too with this config:

[SaintsRowTheThird_DX11.exe]
d3d11.invariantPosition = True

[SaintsRowTheThird.exe]
d3d9.invariantPosition = True
