### ISSUE TITLE
[d3d11] Bullet Girls Phantasia: Many "d3dcompiler:skip_dword_unknown" Errors

### ISSUE THREAD

**Issue by ryester27** [doitsujin/dxvk#1407]
I was actually trying to diagnose an unrelated issue pertaining to jerky camera movement (maybe performance related?) when I came across these errors. Truthfully, I'm not sure what visual problems these errors are causing because I haven't been able to play the game on Windows yet to compare.

There's 2 different sets of errors I'm seeing:
```
6654.430:002a:0054:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
6654.430:002a:0053:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
6654.430:002a:0051:fixme:d3dcompiler:skip_dword_unknown Skipping 4 unknown DWORDs:
6654.430:002a:0052:fixme:d3dcompiler:skip_dword_unknown Skipping 4 unknown DWORDs:
6654.430:002a:0054:fixme:d3dcompiler:skip_dword_unknown 	0x00000008
6654.430:002a:0053:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
6654.430:002a:0051:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
6654.430:002a:0052:fixme:d3dcompiler:skip_dword_unknown 	0xffffffff
6654.430:002a:0054:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
6654.430:002a:0053:fixme:d3dcompiler:skip_dword_unknown Skipping 3 unknown DWORDs:
6654.430:002a:0051:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
6654.430:002a:0054:fixme:d3dcompiler:skip_dword_unknown 	0x00000008
6654.430:002a:0052:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
6654.430:002a:0053:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
6654.430:002a:0054:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
6654.430:002a:0052:fixme:d3dcompiler:skip_dword_unknown 	0xffffffff
6654.430:002a:0051:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
6654.430:002a:0053:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
6654.430:002a:0054:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
6654.430:002a:0052:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
6654.430:002a:0051:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
6654.430:002a:0053:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
6654.430:002a:0054:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
6654.430:002a:0052:fixme:d3dcompiler:skip_dword_unknown Skipping 4 unknown DWORDs:
6654.430:002a:0051:fixme:d3dcompiler:skip_dword_unknown Skipping 4 unknown DWORDs:
```

And to a lesser extent:
```
warn:  9eb576dd-9f77-4d86-81aa-8bab5fe490e2
warn:  D3D11Query: Unknown interface query
```
Looking at #1200 I saw that an apitrace while using DXVK helped you last time. I have linked one for you below.

### Software information
Bullet Girls Phantasia
Arch Linux

### System information
- GPU: AMD RX 560
- Driver: 19.3.3
- Wine version: Proton-5.0-GE-1
- DXVK version: 1.5.3

### Apitrace file(s)
https://mega.nz/#!CpAV0a5L!JCK4YmA0pCiQaxIUDbgKUkMJsEvBKRJszLyvmhCb10I

### Log files
[steam-1163590.log](https://github.com/doitsujin/dxvk/files/4162883/steam-1163590.log)

**Comment by Joshua-Ashton** [comment]
## d3dcompiler

This is a bug in Wine's `d3dcompiler` implementation which is known to be broken with DXVK

Please install native versions of this lib in winetricks/protontricks and see if it helps your problem.

## query thing

Looks like it's trying to query ID3D11Predicate from something that isn't a predicate?

**Comment by ryester27** [comment]
Now that I look at the mentioned issue again, you were probably asking for a dxvk apitrace for the `d3dcompiler:d3dcompiler_shader_reflection_GetDesc` errors. Luckly I have some of those in my log, too

**Comment by doitsujin** [comment]
`d3dcompiler` is not part of DXVK.
