### ISSUE TITLE
[d3d9] F.R.: Demon Stone - various missing textures

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#1409]
Character textures and portraits are the most obvious, but there may be more things missing in later stages of the game.

DXVK in-game:
![demon_stone_dxvk](https://user-images.githubusercontent.com/6306593/73972126-e5bb5380-4928-11ea-8d0f-c464a7ce88f3.jpg)
WineD3D in-game:
![demon_stone_wined3d](https://user-images.githubusercontent.com/6306593/73972143-ece26180-4928-11ea-9802-6e92a7409d34.jpg)

Summary menu (after exiting a game) with DXVK:
![image](https://user-images.githubusercontent.com/6306593/73972193-05eb1280-4929-11ea-8bc1-fbd8eb7aad00.png)
Summary menu with WineD3D:
![demon_stone_menu_wined3d](https://user-images.githubusercontent.com/6306593/73972221-13a09800-4929-11ea-883d-926d88105e59.jpg)

### Software information
Forgotten Realms: Demon Stone (GOG version).

### System information
- GPU: GeForce GTX 1070
- Driver: 440.48.2
- Wine version: 5.1 Staging
- DXVK version: v1.5.3-4-g08fc534

### Apitrace file(s)
[Demonstone.trace.tar.xz](https://drive.google.com/open?id=10g9ZewWDMBLYp0wTG2jgURvr8BPUScen)

### Log files
- d3d9.log: [demonstone_d3d9.log](https://github.com/doitsujin/dxvk/files/4167388/demonstone_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by doitsujin** [comment]
The apitrace replays fine here. Was it recorded with wined3d? If so, it might be useful to record another one with DXVK enabled as well so that we can see what we're doing wrong.

**Comment by WinterSnowfall** [comment]
> Was it recorded with wined3d? 
Guilty as charged. To keep it in mind for any future bugs I raise, what's usually more useful for you: the WineD3D apitrace or the DXVK apitrace?

> If so, it might be useful to record another one with DXVK enabled as well so that we can see what we're doing wrong.
[Demonstone_dxvk.trace.tar.xz](https://drive.google.com/open?id=1HBjvbFx7Q2R9mOg_guu-nZUtfrQEosjL)

**Comment by doitsujin** [comment]
> what's usually more useful for you: the WineD3D apitrace or the DXVK apitrace?

Usually the wined3d one. Anyway, thanks for doing this so quickly.

**Comment by WinterSnowfall** [comment]
> Anyway, thanks for doing this so quickly.

No problem, happy to oblige if it helps.

Also, a bit off-topic, but I probably should have asked this earlier: just to be sure I don't submit useless stuff, is there like a consolidated list of recommended native stuff which needs to be setup in conjunction with DXVK in order to avoid stumbling into known issues?

I remember you've mentioned **d3dcompiler_43** and **d3dcompiler_47** at some point. Anything else?

**Comment by doitsujin** [comment]
> Anything else?

d3dx9.

**Comment by Joshua-Ashton** [comment]
Can you please try with this build:
[d3d9.zip](https://github.com/doitsujin/dxvk/files/4168212/d3d9.zip)

**Comment by WinterSnowfall** [comment]
> Can you please try with this build:
> [d3d9.zip](https://github.com/doitsujin/dxvk/files/4168212/d3d9.zip)

Magical. It now renders all the previously missing textures alright :), including the lava texture present in the game's main menu, which I failed to notice was missing before.

There's still some weird character model animation slowdowns in the intro sequence which don't show up with WineD3D, but I'll open a separate bug for those in due time.

**Comment by WinterSnowfall** [comment]
And, as a sidenote, while this game is mostly an unplayable slideshow with WineD3D, it runs smooth as butter with DXVK. Now with textures. Kudos for making this playable probably for the first time on Linux.

**Comment by Joshua-Ashton** [comment]
Cool, I merged this into master. If there are any other issues, feel free to make an issue.

Cheers and have fun!
