### ISSUE TITLE
F.E.A.R. 2: Ultimate edition 1.05 (GOG)

### ISSUE THREAD

**Issue by ChazyTheBest** [doitsujin/dxvk#1411]
I also tried the Steam edition, but of the 4 proton versions available none work correctly, either the map doesn't load correctly and you can't see where you are or it crashes during or after loading.

I tried different cracks, with different repacks, but the game crashes after loading with similar error messages in the console.

The GOG installer actually gives an error at the end of the installation process, for many different games actually, but they all worked fine (except this one). So please let me know if this is a problem with dxvk or with my configuration/installation.

Last week I played this game and it worked fine, so I also tried 1.5, 1.5.1 and 1.5.2, the first two versions crash with an error saying "a component crashed and a back trace wasn't possible" or something like that, no luck after all, I remember it was a cracked exe, but of all the sites I tried all give the same or similar error messages in the console.

Please take a look at the log files and let know if you know what's going on. I'm gonna upload the apitrace in a moment.

### Software information
F.E.A.R. 2: Ultimate edition 1.05 (GOG)

### System information
- GPU: Radeon RX 480 8GB
- Driver: AMD RADV POLARIS10 (LLVM 9.0.1): 19.3.3
- Wine version: 5.0
- DXVK version: v1.5.3-11-g88147e19

### Apitrace file(s)
- Coming right away

### Log files
- d3d9.log: [FEAR2_d3d9.log](https://github.com/doitsujin/dxvk/files/4167686/FEAR2_d3d9.log)
- d3d11.log: N/A
- dxgi.log: empty
- console log with more error messages (2 runs, different errors): [FEAR2_console.log](https://github.com/doitsujin/dxvk/files/4167690/FEAR2_console.log)

**Comment by doitsujin** [comment]
See #1318. To fix this, you need to either use a wine build which supports large address awareness and set `WINE_LARGE_ADDRESS_AWARE=1`, or patch the ececutable to set the LAA flag.

**Comment by ChazyTheBest** [comment]
Hmmm that's weird, I was about to run the apitrace, but then thought of using lutris and after importing the steam edition it worked perfectly fine.
