### ISSUE TITLE
[d3d9] Anno 1701 - squares on unexplored area edges

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#1412]
Anno 1701/Anno 1701: The Sunken Dragon with all settings maxed out @ 720p, except for anti-alias (because of an issue that's soon to come in a separate bug).

Unexplored area edges with DXVK:
![anno_1701_dxvk](https://user-images.githubusercontent.com/6306593/73979258-806e5f00-4936-11ea-83e8-980a6719cf79.jpg)
... and with WineD3D:
![anno_1701_wined3d](https://user-images.githubusercontent.com/6306593/73979289-8b28f400-4936-11ea-87a2-e07e461a73e4.jpg)

### Software information
Anno 1701 + The Sunken Dragon Addon (GOG version).

### System information
- GPU: GeForce GTX 1070
- Driver: 440.48.2
- Wine version: 5.1 Staging
- DXVK version: v1.5.3-4-g08fc534

### Apitrace file(s)
[Anno1701AddOn.trace.tar.xz](https://drive.google.com/open?id=1Gehsedh30cliA3YgkkM8lCQiT27fbt0A)

### Log files
- d3d9.log: [Anno1701AddOn_d3d9.log](https://github.com/doitsujin/dxvk/files/4167770/Anno1701AddOn_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by Joshua-Ashton** [comment]
Should be fixed as of https://github.com/doitsujin/dxvk/commit/1f67602b98afdaef5660632d38f3d2cce6568e82

Build: https://git.froggi.es/doitsujin/dxvk/-/jobs/1136

**Comment by WinterSnowfall** [comment]
> Should be fixed as of [1f67602](https://github.com/doitsujin/dxvk/commit/1f67602b98afdaef5660632d38f3d2cce6568e82)

Confirmed as fixed. Thanks a lot!

**Comment by Joshua-Ashton** [comment]
It's my pleasure! :)
