### ISSUE TITLE
A question about DXVK_HUD

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [doitsujin/dxvk#1413]
There is a new HUD called MangoHud that looks like MSI Afterburner, and one of the things that it can provide is GPU_load, and that doesn't work with old GPUs like mine, but DXVK_HUD shows GPU_load for my GPU, so could you explain what is the method DXVK_HUD use to get GPU_load readings, and if it can be used with other HUDs like MangoHud?

**Comment by doitsujin** [comment]
The explanation is a bit technical, but DXVK essentially has a thread that mostly just waits for the GPU to finish executing rendering commands, and measures the time it spends waiting for the GPU, as well as time time it spends doing nothing at all. This is not *perfect*, but quite accurate in practice and works on all systems.

The Mango HUD does not have access to this information and thus cannot trivially implement such a feature. Instead it relies on the GPU load to be reported by your graphics driver, which may or may not work on very old GPUs.

**Comment by ahmed-elsayed2017** [comment]
Ok, thanks for your simple explanation.
