### ISSUE TITLE
F.R.: Demon Stone - opening sequence glitches

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#1414]
Right at the start of a new game, during the in-engine opening intro sequence, the camera passes through the main character and then he seems to move in slow motion for a while. Everything gets back to normal once you briefly see an orc running in the background. 

Other in-engine sequences may be affected, though I haven't seen anything similar during gameplay.

Initially, I thought this was a Wine issue, but it doesn't happen with WineD3D.

Here's what I've recorded (sorry for the frame-skips, but it's the best my modest quad-core can do apparently):

[Intro sequence with DXVK](https://drive.google.com/open?id=1AU5pnDnwPEB2h_JoWx9XGOoNcR3wT66y)
[Intro sequence with WineD3D](https://drive.google.com/open?id=1zyRYmHT8f1OX8TweCAcChq5PPOBU7Ggm)

### Software information
Forgotten Realms: Demon Stone (GOG version).

### System information
- GPU: GeForce GTX 1070
- Driver: 440.48.2
- Wine version: 5.1 Staging
- DXVK version: v1.5.4

### Apitrace file(s)
This part is already captured in the API traces provided with #1409 

### Log files
- d3d9.log: [demonstone_d3d9.log](https://github.com/doitsujin/dxvk/files/4169887/demonstone_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by WinterSnowfall** [comment]
I see this was reported before as part of issue [#321](https://github.com/Joshua-Ashton/d9vk/issues/321) on d9vk. **CartoonFan** has a better capture of the slow-down in his last comment.

**Comment by doitsujin** [comment]
Have you tried enabling vsync? This sounds like the kind of thing that happens when games run at higher frame rates than they are designed for.

**Comment by WinterSnowfall** [comment]
> Have you tried enabling vsync? This sounds like the kind of thing that happens when games run at higher frame rates than they are designed for.
> 
> In any case, this is almost certainly not a bug on our end.

There's no game option for v-sync, but setting d3d9.presentInterval = 1 fixes the issue. Can this be added as a game-specific workaround?

**Comment by NerosTie** [comment]
It looks ok on my side:
https://imgur.com/a/WIbk5OS

**Comment by doitsujin** [comment]
I don't really like the idea of force-enabling vsync since the results depend on each user's monitor. But then again we don't have any other FPS limiter at the moment.

Would be interesting to know at which frame rate it starts breaking, if it's 200 FPS or less then we *definitely* need something else since high refresh rate monitors might start running into the issue otherwise.

**Comment by NerosTie** [comment]
This is the FPS limiter I use for Vulkan applications:
https://github.com/pchome/VkGHL

**Comment by WinterSnowfall** [comment]
> I don't really like the idea of force-enabling vsync since the results depend on each user's monitor. But then again we don't have any other FPS limiter at the moment.

On second thought, I agree and take back my suggestion. Since it won't affect everyone it shouldn't be considered as a workaround.

However, an entry in the [Common-isues](https://github.com/doitsujin/dxvk/wiki/Common-issues) section of the wiki for high refresh-rate problems in general (while not DXVK specific) would be useful for people running into these sort of things and not knowing what they are or how they can be fixed. I would still be one of them if not for the feedback you've provided on this thread.

That being said, I'm quite happy I've figured out one of the last things preventing me from playing this game, so I'm closing this "bug" :). Thanks again for all your inputs.

**Comment by WinterSnowfall** [comment]
> I don't really like the idea of force-enabling vsync since the results depend on each user's monitor. But then again we don't have any other FPS limiter at the moment.

Time leaping into the future/present (depends on your point of view really), now with a dxvk frame limiter at hand (thanks for that @doitsujin!), could we please lock this game to 60 fps?

**Comment by WinterSnowfall** [comment]
Thank you @DadSchoorse !
