### ISSUE TITLE
[d3d9] Evil Genius crashes on main menu load

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#1417]
![evil_genius](https://user-images.githubusercontent.com/6306593/74059272-62fdcb80-49f0-11ea-9241-4630e5af2eb7.jpg)

The game crashes with the above message right after the loading screen/opening cinematic. With WineD3D it loads up just fine. There's really no difference in how it loads between DXVK and WineD3D besides the crash, which is why I haven't recorded anything.

I'm hoping that between the error message and the apidump you can find out why.

As a sidenote, I can't really remember, but I think this was one of the DirectX 8.1 games I got working with DXVK through d3d8to9. Still, I did not remove d3d8to9 while testing with WineD3D, so it shouldn't matter, but I mentioned it in case it somehow does. I can also, of course, remove d3d8to9 and confirm if it is indeed a DirectX 8.1 game or not, if needed.

### Software information
Evil Genius (GOG version).

### System information
- GPU: GeForce GTX 1070
- Driver: 440.48.2
- Wine version: 5.1 Staging
- DXVK version: v1.5.4

### Apitrace file(s)
[EvilGeniusExeStub-Release.trace.tar.xz](https://drive.google.com/open?id=1sdruwLlUTid2CkmvPPtxkwiuulh8Cnru)

### Log files
- d3d9.log: [EvilGeniusExeStub-Release_d3d9.log](https://github.com/doitsujin/dxvk/files/4172562/EvilGeniusExeStub-Release_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by Joshua-Ashton** [comment]
Fixed! Thanks for the report.

**Comment by WinterSnowfall** [comment]
> Fixed! Thanks for the report.

Yes, everything seems to work just fine now. Thanks for fixing it! :)

**Comment by Joshua-Ashton** [comment]
No worries, enjoy!
