### ISSUE TITLE
Source FIlmmaker slow/laggy

### ISSUE THREAD

**Issue by NikoBellicRU** [doitsujin/dxvk#1418]
This game/tool has some issues rendering some menus,the video is laggy also when i try to move the timeline it just fireezes a lot and sometimes crashes.
This is not present with GL only with dxvk, i made a video showing it:
https://www.youtube.com/watch?v=gDKRgyanafg&feature=youtu.be

- GPU: GTX 670
- Driver: 440.59
- Wine version: 
- DXVK version:

**Comment by NikoBellicRU** [comment]
Forgot this, might help

[sfm_d3d9.log](https://github.com/doitsujin/dxvk/files/4172675/sfm_d3d9.log)
[steam-1840.log](https://github.com/doitsujin/dxvk/files/4172682/steam-1840.log)

**Comment by doitsujin** [comment]
What makes you think that this is a DXVK bug and not just a general performance issue when running under wine?

**Comment by NikoBellicRU** [comment]
But it works without dxvk with proton/gl, i showed that in the video.

**Comment by doitsujin** [comment]
It wasn't obvious that the video was showing it running under Proton and not a native Linux build.

Anyway, if it works with GL then just use that. We cannot support this application anyway due to winevulkan limitations.

**Comment by Joshua-Ashton** [comment]
SFM works and performs fine for me on DXVK on Windows -- but yeah it will have issues on Proton due to child window rendering.

As a workaround, you can use the VGUI version of SFM (which is better imo as the engine viewport and the SFM tools are one in the same, and the resolution stuff actually works).

Launch with `-noqt -usevgui`. Then do this in the UI `Windows->Engine Window->Uncheck Auto Hide Engine Window`.

**Comment by Joshua-Ashton** [comment]
It should end up looking like this, just the same thing with more features and less flare:

![image](https://user-images.githubusercontent.com/21316711/74073889-e4128e00-4a03-11ea-809c-d0d6c0eb74b8.png)

**Comment by NikoBellicRU** [comment]
Its still a bit janky guess i still have to use dualboot for this one :(
Thanks anyway :)

**Comment by Joshua-Ashton** [comment]
define: janky?

Are you still experiencing slowdown etc?

**Comment by NikoBellicRU** [comment]
The -usevgui command drops down a lot of performance i just tried on windows also same result, when im manipulating the caracter the fps drop from 30-40 to like 12-15 only without that command is usable for me.

**Comment by Joshua-Ashton** [comment]
Very weird, can you send me a DMX of your scene? I'm getting like 300fps doing pretty much anything (until we get uberlights involved)

**Comment by NikoBellicRU** [comment]
Load the default one then create new project and just add a zombie model then when you go to edit mode press and hold CTRL and select any part of his body and try move the mouse, thats where it drops alot also in when adding models/maps its alot laggy with that command
