### ISSUE TITLE
GTA IV Frame skipping / jumping lag

### ISSUE THREAD

**Issue by NikoBellicRU** [doitsujin/dxvk#1419]
I dont know if you can see this in the video but you can clearly see it in the frametime graph.
https://www.youtube.com/watch?v=clxQTkD14y0&feature=youtu.be

Also for some reason there's a bug with gta4Browser.exe that its constantly using 25% of the cpu and really drops performance without stoping it or kill it soon as i enter the game, not sure if its wine/proton problem tho.

- GPU: GTX 670
- Driver: 440.59
- Wine version: proton 4.11-12
- DXVK version: 1.5.4

[steam-12210.log](https://github.com/doitsujin/dxvk/files/4173034/steam-12210.log)
[GTAIV_d3d9.log](https://github.com/doitsujin/dxvk/files/4173036/GTAIV_d3d9.log)
[LaunchGTAIV_d3d9.log](https://github.com/doitsujin/dxvk/files/4173038/LaunchGTAIV_d3d9.log)

**Comment by doitsujin** [comment]
Low performance is expected on weak hardware, especially if your CPU is weak.

**Comment by NikoBellicRU** [comment]
Where is that file and whats the name? Also i played this game with d9vk before it was merged with dxvk a while ago and it waas working great i played with all very high settings and now with medium settings that wierd lag happends

**Comment by telans** [comment]
I encountered this a few days ago, but didn't think this was DXVK's issue as I also have this issue in Modern Warfare Remastered.

I don't think specs are the issue here, I have an i7-4770 & 980 Ti (not the best, but good enough for GTA IV)

**Comment by Iglu47** [comment]
@NikoBellicRU use this instruction for dx9 games https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace#on-linux 

instead editing setting via `winecfg` try use environment variable through `set launch option...` for steam games, example 
`WINEDLLOVERRIDES="d3d9,d3d11,d3d10,d3d10core,d3d10_1,dxgi=n,b" DXVK_HUD=full %command%`

**Comment by NikoBellicRU** [comment]
https://drive.google.com/file/d/1RDlcqGlgY2yCfETqUI6YoFlpTJDFd9ML/view?usp=sharing
https://drive.google.com/file/d/17h4ugjTxXDnDvhBDWCmlA1-aHKDnIivO/view?usp=sharing

**Comment by ViNi-Arco** [comment]
Hello @NikoBellicRU , very strange that you can't get a good fps in GTA IV with a higher GPU, I can get between 40 ~ 60 FPS on an E8400:

![2020-03-23-163829_1024x768_scrot](https://user-images.githubusercontent.com/57958460/77357303-aef99b00-6d26-11ea-9c87-ae0dd01e5046.png)

![2020-03-23-163732_1024x768_scrot](https://user-images.githubusercontent.com/57958460/77357331-b8830300-6d26-11ea-99de-27393fe965a3.png)

![2020-03-23-163839_1024x768_scrot](https://user-images.githubusercontent.com/57958460/77357348-c0db3e00-6d26-11ea-9a59-08b8472a5381.png)

You can try to disable `gta4Browser.exe`:
![oie_xxydIVOcN9P4](https://user-images.githubusercontent.com/57958460/77357468-fbdd7180-6d26-11ea-8e84-182cdd30a42f.png)

And use `__GL_THREADED_OPTIMIZATIONS` in `Environment Variables` in Lutris.

**Comment by HughJass** [comment]
I also get micro stutters on the steam version, but the cracked version from Razor1911 works fine, overall perfomance is better by about 10 frames. My rig is:
Ryzen 5 2600
RX 590
Mesa 20.1-git
DXVK various versions, from 1.4.0 to 1.6.0
DXVK also works better than Gallium9 for me

**Comment by valgusk** [comment]
[apitrace](https://drive.google.com/open?id=1Lxvy1_Z0Ku9JhHUPgiuEr_SGZH3XIQaQ)
[steam system info](https://gist.github.com/valgusk/3835881a616a64be12d82136ceed0e51)
I recorded it on minimal settings to reduce file size, and without using DXVK, as was recommended in post linked by @Iglu47, but if I launch this same slice with default DXVK settings, it has heavy framegraph spikes. This can be heavily reduced by setting maxFrameLatency=1, but it does not fix it completely.
Another thing I noticed is that comparing to Wine D3D implementation:
- game causes constant 99-100% gpu usage, even if scene is simple. (with vsync on it seems to be 100% even in menu). It is so big, that not only game, but the whole desktop has stutters. On regular wine I see avg. of  30% and max of 70% while having same/more fps most of the time
- game causes significantly bigger PCIe Bandwidth Utilization (70%, while in regular wine it is 10%-20%)

**Comment by NikoBellicRU** [comment]
Dude nice one that fixed 99% of that problem but when Vsync is ON the problem is still there and kinda worse so aparently this " d3d9.presentInterval = 0 " fixed the game with Vsync ON and this " d3d9.maxFrameLatency = 1 " fixed with it OFF , now the game plays very well some times it has that lag but its like for 1-2 seconds and really not that often, also that happends even on windows sometimes so i guess probably its not fully fixable cause as we know this was a bad port. . . 

doitsujin can you check it and merge to next build?

**Comment by bno1** [comment]
>aparently this " d3d9.presentInterval = 0 " fixed the game with Vsync ON
`d3d9.presentInterval = 0` forces Vsync off

**Comment by NikoBellicRU** [comment]
I tried 1 and 2 both with bad performance so maybe 0 its not the solution for vsync but well at least now the game is playable with it off

**Comment by NikoBellicRU** [comment]
Ok now i can confirm that this ia not only on nvidia, i just upgrated to a rx 570 and still having the same problem either on medium/high or very high settings and im getting like 90fps.
The only fix for now is really using this " d3d9.maxFrameLatency = 1 " on dxvk.conf

**Comment by ArturWroblewski** [comment]
The problem still exists.

Tested on:
Ryzen 1700
RAM 32GB
Nvidia GTX 1650 4GB
See it in the frametime graph on Video:

Grand Theft Auto IV
https://youtu.be/GR1NpdFnfZE

Grand Theft Auto The Lost and Damned
https://youtu.be/FtghGB0mTKU

Tip for other users:
To play comfortably, use the command, 
PROTON_USE_WINED3D=1 %command%
but it limits the fps to 30 or less. The simplest option until the problem with DXVK is not fixed.

**Comment by K0bin** [comment]
In your video it looks like the frame time spikes are caused by shader compilation. This can't be fixed.

**Comment by NikoBellicRU** [comment]
> In your video it looks like the frame time spikes are caused by shader compilation. This can't be fixed.

I dont think that is the problem, as mencioned this " d3d9.maxFrameLatency = 1 " fixes most of the problem and also when i use frame limit in this game that doesnt happed but soon as it goes under the capped framerate it starts again.

**Comment by ViNi-Arco** [comment]
@NikoBellicRU Have you tried to disable Vsync in the game instead of using `d3d9.presentInterval=0`, I tried to use `d3d9.maxFrameLatency=1` here and it got really bad, leaving the game default is smooth for me, I could see that there are more people getting along with `d3d9.maxFrameLatency=1` for example here:
https://www.reddit.com/r/pcgaming/comments/gsn6w8/dxvk_works_magic_on_gta_iv/
I think it's best to leave it as an option for the user to choose as it is

**Comment by NikoBellicRU** [comment]
Since i installed mesa ACO ppa it got better but it not fully fixed, also i been using that command for a while now cause it was the only way to not get bad performance, its wierd that you had bad experience with it but what i really think its wierd is that this never been a problem for me on wined3d, i just dont get this

**Comment by WinterSnowfall** [comment]
> but what i really think its wierd is that this never been a problem for me on wined3d, i just dont get this

OpenGL (what wined3d is currently using) and Vulkan (what dxvk is using) are fundamentally different, so are their issues and quirks and also how well they work on certain hardware configurations. Issues are not always caused by something someone can fix or optimize on a global level. 

If wined3d works just fine for you, why are you not using it? Don't get me wrong, I'd also like to live in a world where we can use a single wrapper to get the best performance out of everything in all cases, but for many reasons I don't think that's remotely feasible.

**Comment by rafalb8** [comment]
Limiting FPS to 30 with MangoHud helped with stuttering on DXVK
`MANGOHUD_CONFIG=fps_limit=30`

**Comment by K0bin** [comment]
PR 1714 should fix the problem.

**Comment by ViNi-Arco** [comment]
@K0bin How great that you found out it was a problem and fixed it, you are very smart, funny that my old PC was not tied up by it :smile:

**Comment by NikoBellicRU** [comment]
Awesome the game is really good now :)
Thanks!

**Comment by dstrnad** [comment]
I’m experiencing the same issue with heavy frame time spikes when running GTA 4 as a non-Steam game using Proton Experimental. FPS is good otherwise. Could you let me know what the final solution is? Is it the command d3d9.maxFrameLatency=1, and where should I put the command? Thanks in advance!

**Comment by K0bin** [comment]
It's almost certainly not the same issue. Please open a new issue and provide logs and an apitrace. (And ideally a video too)

**Comment by jika08** [comment]
well in my case, I move gta 4 folder to an SSD It start to feel better, but it did not frame drop anymore
