### ISSUE TITLE
Witcher 3 rendering mess on RX 470 Polaris Manjaro

### ISSUE THREAD

**Issue by zaxxxxx** [doitsujin/dxvk#142]
The witcher 3 doesn't render properly on my system, also the performance is terrible

![screenshot_20180310_113728](https://user-images.githubusercontent.com/19254754/37241454-a0674802-2459-11e8-9a5d-7742051af9ce.png)

### Software information
Witcher 3 GOG version - all details on low

### System information
- OS: Manjaro Linux
- GPU: rx 470 polaris
- Driver: amd radv 17.3.6
- Wine version: wine 3.3-vulkan-git
- DXVK version: tried both the git as well as binaries from github

### Apitrace file(s)
- I'll link it later right now im stuck at error: failed to execute inject

### Log files
[witcher3_d3d11.log](https://github.com/doitsujin/dxvk/files/1799294/witcher3_d3d11.log)
[witcher3_dxgi.log](https://github.com/doitsujin/dxvk/files/1799295/witcher3_dxgi.log)

**Comment by doitsujin** [comment]
Use mesa-git, the game is known to be broken on 17.3.x. I'll update #138 accordingly.
