### ISSUE TITLE
[d3d9] Book of Demons: White Textures

### ISSUE THREAD

**Issue by ryester27** [doitsujin/dxvk#1420]
When you are in town or in the screen before entering town, almost all of the textures other than the character model and HUD is white

**DXVK**
![Screenshot_20200207_215235](https://user-images.githubusercontent.com/17807258/74079507-85024880-4a06-11ea-874f-fe83ea313397.png)
![Screenshot_20200207_215249](https://user-images.githubusercontent.com/17807258/74079512-8d5a8380-4a06-11ea-811b-53ead0f2ee67.png)

**WineD3D**
![Screenshot_20200207_215406](https://user-images.githubusercontent.com/17807258/74079519-9f3c2680-4a06-11ea-8850-9b9143247304.png)
![Screenshot_20200207_215418](https://user-images.githubusercontent.com/17807258/74079534-bed34f00-4a06-11ea-8d02-5840ba426ac4.png)

### Software information
Book of Demons on Arch Linux

### System information
- GPU: AMD RX 560
- Driver: Mesa 19.3.3
- Wine version: Proton 5.0-1
- DXVK version: 1.5.4

### Apitrace file(s)
https://mega.nz/#!bw5USK7Z!dicxTVg15baoWeZMpo_tOlwcZY-ekw2-Bft5VMoOAnM

### Log files
[steam-449960.log](https://github.com/doitsujin/dxvk/files/4173811/steam-449960.log)

**Comment by lucifertdark** [comment]
I can confirm the bug is present with Nvidia hardware GTX1650 & 440.48.02 drivers as well, here are logs from Proton 4.11-12 (no bug) & Proton 5.0-1 (with bug)
https://gist.github.com/lucifertdark/584c14275612e8e3c4a8070d428d8a02
[Proton 4.11-12.steam-449960.log](https://github.com/doitsujin/dxvk/files/4173882/Proton.4.11-12.steam-449960.log)
[Proton 5.0-1.steam-449960.log](https://github.com/doitsujin/dxvk/files/4173883/Proton.5.0-1.steam-449960.log)

**Comment by ziabice** [comment]
Game works well with:
Proton 4.11-12
Mesa 19.3.3 on AMD RX 580

**Comment by ziabice** [comment]
Tested Proton 5.0-1 and it doesn't work, as described.

[steam-449960.log](https://github.com/doitsujin/dxvk/files/4174250/steam-449960.log)

![Screenshot_20200208_141619](https://user-images.githubusercontent.com/28961115/74086073-9fc4d380-4a7f-11ea-91f9-5890e281c936.png)

**Comment by Joshua-Ashton** [comment]
This trace is garbage because you traced OpenGL + WineD3D which is not useful to me.

Please trace Direct3D 9 + WineD3D.

**Comment by Joshua-Ashton** [comment]
https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace

**Comment by ryester27** [comment]
> I can confirm the bug is present with Nvidia hardware GTX1650 & 440.48.02 drivers as well, here are logs from Proton 4.11-12 (no bug) & Proton 5.0-1 (with bug)

D9VK was not the Proton default until 5.0-1. You had to use the PROTON_USE_D9VK variable before. I was getting the same bug with 4.11-12.

> https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace

I forgot how I did this before with Proton because I didn't want to install the wine package for winecfg. I guess my last attempt was not the correct way. Anyways I remember now and the new apitrace is below

**New apitrace**
https://mega.nz/#!K1BEmAQT!0iYXnG2z80jUFD_vQEQ7DAESezUM5awLA1G8okSKatM

**Comment by Joshua-Ashton** [comment]
Thanks for the trace. Fixed! Enjoy :)

**Comment by ryester27** [comment]
Looking good now. Still some visual errors with the UI, but I'll create another ticket for those

![Screenshot_20200209_005324](https://user-images.githubusercontent.com/17807258/74097208-7e8fd180-4ad7-11ea-9988-461103802d44.png)

**Comment by GoulvenC** [comment]
Hi guys, I just have the exact same problem :/
The game work out of the box with Proton 4.11-15, but not with Proton 5.0-1.

**Comment by ryester27** [comment]
> Hi guys, I just have the exact same problem :/
> The game work out of the box with Proton 4.11-15, but not with Proton 5.0-1.

Commits have already been merged to deal with this problem & others I found. Either wait for the next DXVK point release & sequential Proton update, compile your own d3d9.dll from master & put it in the game directory, or use the PROTON_USE_WINED3D=1 command line option in Steam
