### ISSUE TITLE
Resident Evil 2 Remake lag / menu bug

### ISSUE THREAD

**Issue by NikoBellicRU** [doitsujin/dxvk#1424]
This game is really wierd, when i load a save game i have like 20fps then i found a certain area that if i entered it my fps would jump to 45-50fps even when i come back to the start the fps stays there, then theres a bug on menu / inventory that when you open in you go from 50fps to like 13fps but only happends in full screen mode, borderless windowed worked fine in that. Also the game crashes when starting new game if i install media foundation that is required for video playback but dont know if this one is a dxvk problem.

- GPU: GTX 670
- Driver:440.59
- Wine version: Proton 5.0-1
- DXVK version: 1.5.4

   [re2_d3d11.log](https://github.com/doitsujin/dxvk/files/4176929/re2_d3d11.log)
   [steam-883710.log](https://github.com/doitsujin/dxvk/files/4176930/steam-883710.log)

**Comment by doitsujin** [comment]
Low performance on 2GB Nvidia GPUs is not really a bug, it's expected. Close background applications such as web browsers, disable Steam's hardware acceleration to free up some VRAM, and use low texture quality in game.

**Comment by NikoBellicRU** [comment]
This is not my hardware this a bug either dxvk or driver i say again soon as i enter that area of the game i go from 20 to 45-50 all the time even when i go back to the place when i was having 20, also the inventory in full screen drops to like 10-15fps laggy but it doesent happend with borderless or windowed mode. Again not hardware problem.

**Comment by doitsujin** [comment]
Again, low performance is a bug, it's expected on your hardware. Period.

**Comment by NikoBellicRU** [comment]
What about this post from protondb then

RESIDENT EVIL 2 / BIOHAZARD RE:2
a month ago
Performance:Slight Performance Problems

Sometimes fps drops in the map/inventory menu. Makes it hard to interact with the screen.
Stability:Occasionally

Got 3 crashes within 2 hours. Given that there is no autosave, I would save it's a notable problem. Save as often as you can.
Steam Play Proton 4.11-11
Distro:Arch Linux
Kernel:5.4.5-arch1-1
RAM:16 GB
GPU Driver:NVIDIA 440.44
GPU:NVIDIA GeForce RTX 2070 SUPER
CPU:AMD Ryzen 7 3700X 8-Core

**Comment by Joshua-Ashton** [comment]
Logs would be useful if there are crashes

**Comment by doitsujin** [comment]
There are no widespread issues with this game besides it requiring mfplat. I don't know why some individuals have issues, the game works fine here.
