### ISSUE TITLE
[D3D9] Sonic and Sega All-Stars Racing Transformed Collection:  Memory Allocation Error

### ISSUE THREAD

**Issue by vinifmor** [doitsujin/dxvk#1425]
Hello,

I've just installed Proton 5.0-1 that comes with D9VK enabled by default and I'm having issues with Sonic And Sega All-Stars Racing Transformed. After selecting any level to race, the game freezes on the loading screen. The logs point to **DxvkMemoryAllocator: Memory allocation failed**.
I'm attaching the links to the proton logs and the compressed apitrace file. I've tested with two different Nvidia setups:

Setup 1:
GPU: Nvidia GTX 970 4GB
RAM: 16 GB
Ps: I enabled PROTON_FORCE_LARGE_ADDRESS_AWARE=1 for this setup.

Setup 2:
GPU: Nvidia GT 740M 2 GB
RAM: 8GB

The OS, Driver and Kernel are the same for both setups:
OS: Manjaro Linux
Kernel: 5.4.17
Driver: Nvidia 440.59

Game: Sonic And Sega All-Stars Racing Transformed Collection
Steam ID: 212480

### System information
- Wine version: Proton 5.0-1
- DXVK version: 1.5.4

### Apitrace file(s)
- https://drive.google.com/file/d/1XTwWhmT6bg-vbIVhA4or95u-Do2iqcsM/view?usp=sharing

### Log files
- Proton Log (GT 740M): https://drive.google.com/open?id=1AwRON5nV4lpPPL9_rspqizrvINqxVrnU
- Proton Log (GTX 970): https://drive.google.com/open?id=1tkHkthSEQ0cu27JuT_h3rtCJZKpyh8t6 

If any additional information is required to debug, let me know. Thank you for the great work with D9VK / DXVK so far.

**Comment by doitsujin** [comment]
If enabling large address awareness doesn't fix it, you're out of luck, but this is still the same issue as #1318 .

**Comment by vinifmor** [comment]
@doitsujin , after some testing here I've found out that if **vsync is disabled** via the game settings (**/home/$USER/.steam/steam/steamapps/compatdata/212480/pfx/drive_c/users/steamuser/My Documents/SART: settings.xml**) the error doesn't happen and the synchronization is still done. Played for 1 hour a half without any crash. PROTON_FORCE_LARGE_ADDRESS_AWARE was not necessary. I've already had similar issues related to the game's vsync settings as well, but it is not a rule. Just commenting some other cases:
1) Marvel x Capcom Infinite (493840): the screen keeps blinking throughout the game (menus, levels, etc)
2) Tomb Raider (203160): heavy stuttering while vsync is enabled. 
3) GRIP (396900): after playing some levels, suddenly the FPS drops to a half and keeps it constant.

Anyway, I hope this report can help other users as well.
