### ISSUE TITLE
[d3d9] Starcraft 2 hangs/crashes

### ISSUE THREAD

**Issue by LeJimster** [doitsujin/dxvk#1426]
### Software information
Starcraft 2
Using native `d3dx9` and `d3dcompiler` as recommended.
Multiple different maps from the Arcade either hang or crash on the loading screen with the error `e_gfxErrorShaderCompilerFailed`.    
![Screenshot from 2020-02-09 17-15-22](https://user-images.githubusercontent.com/35663469/74107117-c1e45180-4b64-11ea-9aba-d790b8e8dc81.png)
![compiler error](https://user-images.githubusercontent.com/35663469/74107142-096add80-4b65-11ea-997f-78b5ee176583.png)

### System information
- GPU: Radeon Vega 56
- Driver: Mesa 19.3.3 / LLVM 9.0.1
- Wine version: Lutris 4.21-tkg
- DXVK version: 1.5.4

### Apitrace file(s)
[Element Tower Defense](https://drive.google.com/open?id=1h_ryixliY_mHj6te6fEXpruoCB5i3bo3)
[Direct Strike](https://drive.google.com/open?id=13m7VARhotqKeQ_PJUaZr-NysCcf37V8W)
[Hero Line Wars Starlight](https://drive.google.com/open?id=1s5u_XQtcsl2BHWkHhVjEBSLjbVs_2iS8)

### Log files
- d3d9.log: [SC2_x64_d3d9.log](https://github.com/doitsujin/dxvk/files/4177262/SC2_x64_d3d9.log)
- d3d11.log:
- dxgi.log: [SC2_x64_dxgi.log](https://github.com/doitsujin/dxvk/files/4177264/SC2_x64_dxgi.log)

**Comment by doitsujin** [comment]
Can you attach the full wine log as well? `e_gfxErrorShaderCompilerFailed` sounds suspiciously like it's not picking up your d3dcompiler or something.

**Comment by LeJimster** [comment]
Ahhhh, damn, sorry to waste your time.
Yes, you and Josh both said the same thing and I thought I had everything needed already.  I could see `d3dcompiler_43` and `d3dcompiler_47` already set to native (I'm guessing from the Lutris install script), I didn't realise there were more, so I added all of them and it works fine now.
