### ISSUE TITLE
[d3d9] htoL#NiQ: The Firefly Diary - Black box around certain sprites

### ISSUE THREAD

**Issue by sat3ll** [doitsujin/dxvk#1433]
Screenshots and savefile: https://github.com/ValveSoftware/Proton/issues/2166

Launching the game with DXVK or wined3d always results in certain cutscene sprites to be rendered with black boxes around.
![368640_20181230183132_1](https://user-images.githubusercontent.com/37741639/50550097-87ba3800-0c61-11e9-8bda-3c993340c2d1.png)
![368640_20181230182214_1](https://user-images.githubusercontent.com/37741639/50550099-8e48af80-0c61-11e9-8c03-1e79c2c618e8.png)

### Software information
Game: [htoL#NiQ: The Firefly Diary / htoL#NiQ-ホタルノニッキ](https://store.steampowered.com/app/368640/htoLNiQ_The_Firefly_Diary__htoLNiQ/)

### System information
- GPU: AMD Fury X
- Driver: Mesa 19.3.3 + LLVM 9.0.0
- Wine version: Proton 5.0.1 / 5.0
- DXVK version: Proton 5.0.1 / 1.5.4

DXVK_HUD=full
![image](https://user-images.githubusercontent.com/37741639/74150675-53ee6780-4c02-11ea-8960-c4b7d47b7c6c.png)

### Apitrace file(s)
[Hotaru.trace.tar.gz](https://github.com/doitsujin/dxvk/files/4180827/Hotaru.trace.tar.gz)

### Log files
- d3d9.log: 
[Hotaru_d3d9.log](https://github.com/doitsujin/dxvk/files/4180751/Hotaru_d3d9.log)
- proton.log: 
[steam-368640.log](https://github.com/doitsujin/dxvk/files/4180784/steam-368640.log)

### Save file
[savedata.zip](https://github.com/ValveSoftware/Proton/files/2717404/savedata.zip)

Place `savedata.sav` under `SteamLibrary/steamapps/common/htoL#NiQ The Firefly Diary/data/save/`

**Comment by Joshua-Ashton** [comment]
Renders fine for me:

![image](https://user-images.githubusercontent.com/21316711/74556057-f7b67b00-4f54-11ea-9e76-1edc4a02154f.png)


Can you please ensure you are using native d3dx9 and d3dcompiler (43 and 47)

**Comment by sat3ll** [comment]
"Gameplay" renders fine.
Cutscenes do not, use the savefile or try to reach the first "flower/memory artifact".
Further into the "gameplay", when enemies start to appear (much later), you might see wires around the enemy sprites which are absent in Windows.

**Comment by sat3ll** [comment]
Sorry, I forgot to add how to reproduce the issue here.

## Reproduction
- From "Trace Memories Menu" -> click on any leaf/memory fragment (for example 1).
  - Needs savefile: [savedata.zip](https://github.com/ValveSoftware/Proton/files/2717404/savedata.zip)
  - Place `savedata.sav` under `SteamLibrary/steamapps/common/htoL#NiQ The Firefly Diary/data/save/`
- Found during normal gameplay.

**Comment by Joshua-Ashton** [comment]
Ok thanks, I can repro with that :)

**Comment by RinMaru** [comment]
looks like the same issue here 
![Annotation 2020-02-16 183436](https://user-images.githubusercontent.com/15071652/74615079-6299ba80-50eb-11ea-9a95-298e484f901b.jpg)

**Comment by Joshua-Ashton** [comment]
I doubt that is related... The game in this issue uses a color palette in its shaders and something is going wrong there.

That just looks like shadows being broken.

**Comment by RinMaru** [comment]
they only broken on dxvk im asking around to be sure it can be reproed

**Comment by Joshua-Ashton** [comment]
Renders fine on Nvidia: 
![image](https://user-images.githubusercontent.com/21316711/74673475-2af04880-51a7-11ea-9250-94f4aafb2086.png)

The problem appears to be some precision issue on AMD. However, neither NoContraction or RelaxedPrecision fix it or have any effect.

**Comment by Joshua-Ashton** [comment]
Relevant Mesa PR: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/3951

**Comment by Joshua-Ashton** [comment]
This is fixed with latest Mesa.
