### ISSUE TITLE
[d3d9] Close Combat - GtC/PitF - transparency on several menu elements

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#1434]
In several of the relatively new Close Combat series of games, developed by Slitherine Ltd. (which happen to be the only ones compatible with Wine atm) several menu elements are transparent instead of having a solid colour background, as shown in WineD3D. The screenshot only shows a basic prompt, but several other pop-up prompts/progress indicators are also transparent with DXVK.

![close_combat_dxvk](https://user-images.githubusercontent.com/6306593/74184477-8a060880-4c4f-11ea-8286-5ad6ad18d2fc.jpg)

![close_combat_wined3d](https://user-images.githubusercontent.com/6306593/74184487-8e322600-4c4f-11ea-8072-e16ea885a91a.jpg)

### Software information
Close Combat - Gateway To Caen / Close Combat - Panthers In The Fog (GOG versions)

### System information
- GPU: GeForce GTX 1070
- Driver: 440.59.0
- Wine version: 5.1 Staging
- DXVK version: v1.5.4-16-g51903d8

### Apitrace file(s)
[CCE.trace.tar.xz](https://drive.google.com/open?id=1Z2XnOPAQ5Tq-PF6egJZfwF4DgcBwJ26k)

### Log files
- d3d9.log: [CCE_d3d9.log](https://github.com/doitsujin/dxvk/files/4182745/CCE_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by Joshua-Ashton** [comment]
Should be fixed now.

**Comment by WinterSnowfall** [comment]
> Should be fixed now.

It is. Thanks a lot!
