### ISSUE TITLE
After 2caa3c9 Tests D3D11 Going mad 

### ISSUE THREAD

**Issue by t14462** [doitsujin/dxvk#1438]
Tk-Glitch BKGBUILD. Other Commits going to D3D9 allright

**Comment by Waddlen** [comment]
Opening issues like this is almost certainly **not** helpful to the developers, nor was #1423 or #1337. Issues are for reporting bugs or regressions. If you are trying to report a bug, you did not provide enough information.

**Comment by doitsujin** [comment]
The changes after 2caa3c9 do not affect D3D11 in any way.

Closing because this bug report contains no info.
