### ISSUE TITLE
Poor Perfomance with Disco Elysium

### ISSUE THREAD

**Issue by rtentser** [doitsujin/dxvk#1439]
I'm GPU bounded with my GeForce GT 710.
But in Windows 7 i'm GPU bounded too, but the game works 3.5 times faster (6 fps vs 21 on minimals).
I think it's mostly driver's fault (just a guess), but may be you'll want to take a look at it.

**Comment by doitsujin** [comment]
DXVK is known to run poorly on Kepler GPUs, and especially poorly on GPUs with less than 3GB of VRAM, this is not (just) our bug and will not be addressed.

**Comment by rtentser** [comment]
I've tried the game with dxvk on Windows. And there is no graphics again. Looks like NVIDIA didn't implement dxvk fix in windows driver.

**Comment by DocMAX** [comment]
i get the logo and then a black screen with dxvk. what is your config? (winetricks, native libs?)

**Comment by rtentser** [comment]
I'll retest it on Windows soon. If i remember correctly, it just worked for me on Linux, no tricks, no libs but dxvk. Maybe some regression?
