### ISSUE TITLE
[d3d9] BlazBlue: Calamity Trigger crashes with error, also has weirdly stretched effects

### ISSUE THREAD

**Issue by CartoonFan** [doitsujin/dxvk#1440]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
DO NOT use DXVK together with apitrace!

### Software information
BlazBlue: Calamity Trigger (GOG 1207664163)

### System information
- GPU: Nvidia GeForce GTX 960
- Driver: 440.43.2
- Wine version: 5.1.r12.g59d19c89 ( TkG Staging Esync Fsync Vkd3d )
- DXVK version: v1.5.4-19-g313d4698

### Apitrace file(s)
https://drive.google.com/file/d/19fv5GIWaaLjOgJuyhimR-cip-inxDYVK/view?usp=sharing

### Log files
- d3d9.log: [BBCT_d3d9.log](https://github.com/doitsujin/dxvk/files/4197105/BBCT_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

Hello there! Just wanted to let you know that BlazBlue: Calamity Trigger gives an error with DXVK when d3d9 is set to native, as shown here:

![20200213-000332](https://user-images.githubusercontent.com/29664894/74413460-4d274680-4df4-11ea-8a77-2676cd258b20.png)

I've heard of this error happening outside of DXVK, but removing the d3d9 override just gives me a black screen with audio, so I don't really know what's happening.

Some effects are also weirdly stretched:
Native:
![BBCT_2020_02_12_00_59_33_459](https://user-images.githubusercontent.com/29664894/74413640-a55e4880-4df4-11ea-8d45-7e54dd2bfeba.png)
![BBCT_2020_02_12_01_01_44_027](https://user-images.githubusercontent.com/29664894/74413723-d0489c80-4df4-11ea-9820-875ab92dd42f.png)

DXVK:
![20200212-235240](https://user-images.githubusercontent.com/29664894/74413785-ec4c3e00-4df4-11ea-8fc8-ee5119a1a6bb.png)
![20200212-234905](https://user-images.githubusercontent.com/29664894/74413808-fff7a480-4df4-11ea-998a-346a4395453d.png)

Thanks and sorry if this is a known issue already. Unfortunately, I can't test the issues with the effects directly, due to the d3d9 crash.

**Comment by Joshua-Ashton** [comment]
Can you try now? Builds here: https://git.froggi.es/doitsujin/dxvk/-/jobs

**Comment by CartoonFan** [comment]
Sure. I'm going to test it in a little bit, after it builds.

**Comment by CartoonFan** [comment]
All right, so it looks like the crash problem has been solved. When I last checked, there was still another (probably non-DXVK) issue keeping me from checking the stretching issue in-game, but the stretching issue still appears in the apitrace, so I have still have time to figure out how to get this game to work. Thanks for your work!

**Comment by PhantomX** [comment]
This commit fixed Blazblue Central Fiction 1.06+ initrender error too. [Proton#1031](https://github.com/ValveSoftware/Proton/issues/1031).

**Comment by CartoonFan** [comment]
The trace is still broken for me, but the effects are working properly in-game. I'll close this for now, but feel free to reopen it if you want.
