### ISSUE TITLE
Secondary override?

### ISSUE THREAD

**Issue by shmerl** [doitsujin/dxvk#1443]
Is there some ability to enable dxvk that's a secondary override after first level d3d override?

What I mean is some scenario like [Gun](https://www.gog.com/game/gun) with [widescreen fix](https://thirteenag.github.io/wfp#gun), which is essentially a custom hook-like  `d3d9.dll` that modifies game resolution related calls in a way that makes it compatible with modern displays.

For that, d3d9.dll should be set to native override (while the hook dll is placed in the game directory). But that precludes using dxvk as d3d backend since it also requires an override. Is there some way to combine that?

**Comment by Joshua-Ashton** [comment]
Doing so is not possible on our end given we're the actual implementation.

On Windows, you can get away with replacing Windows' ``d3d9.dll``s in System32/SysWOW64 to get around this.

There might be some Wine magic you can do but I am not entirely sure what would be needed for that.

**Comment by Joshua-Ashton** [comment]
I think all you should need to do is put the widescreen fix in the game's binary folder and install DXVK (ie. like the install script) to your prefix's System32/SysWOW64 and set the dll override to `native`.

I figured you have probably already tried that though, but I'm pretty sure that works with apitrace + dxvk...

**Comment by shmerl** [comment]
For some reason I thought that could be a problem. Let me double check.

**Comment by shmerl** [comment]
Yep, it worked. Not sure now why I thought that wasn't usable. Closing.
