### ISSUE TITLE
[d3d9] D&D - ToEE - main menu flickering flame effects

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#1444]
Ambient flame effects shown on the main menu flicker and look off with DXVK. The issue doesn't seem to affect the game, but I haven't yet played that much to be certain.

Best captured on tape... ehm, moving bit maps:
[Main menu with DXVK](https://drive.google.com/open?id=1yZpbKmd9255iDhq4MZZFpVZ6bTDOUmLc)
[Main menu with WineD3D](https://drive.google.com/open?id=1vBFdkQ7SK6eSTPrPD5pswSuUK3cipc-2)

### Software information
D&D - The Temple Of Elemental Evil (GOG version)

### System information
- GPU: GeForce GTX 1070
- Driver: 440.59.0
- Wine version: 5.1 Staging
- DXVK version: v1.5.4-31-g2096a95

### Apitrace file(s)
[ToEE.trace.tar.xz](https://drive.google.com/open?id=1pAGkjjVlHdGs1jEFUqyOUbsmVUdoHRos)

### Log files
- d3d9.log: [ToEE_d3d9.log](https://github.com/doitsujin/dxvk/files/4204116/ToEE_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by Joshua-Ashton** [comment]
Should be fixed now :)

**Comment by WinterSnowfall** [comment]
> Should be fixed now :)

Thanks! Are the build frogs asleep today or was it too small of a change to register? :P

**Comment by Joshua-Ashton** [comment]
I may have forgotten to push there. I will take a look when I'm at my pc next.

**Comment by WinterSnowfall** [comment]
It looks all good now, since 8fabc25 . Thanks!

**Comment by pierrep** [comment]
I can't seem to get this working with the latest dxvk. I can get other games in the same working prefix to work, but with ToEE it seems to use dx7 or dx8 because it falls back on WineD3D. Any suggestions on how to make it work?

**Comment by WinterSnowfall** [comment]
@pierrep You are correct, it is a dx8 game. I've used [d3d8to9](https://github.com/crosire/d3d8to9) to get it to on dx9, therefore DXVK.

**Comment by pierrep** [comment]
Oh what a relief, I thought I was going insane. It's weird though because it's recommended to have a dx9 video card to play it, but that might have been for performance reasons

**Comment by pierrep** [comment]
@WinterSnowfall  at the risk of being annoying, could you point out to me how you go about installing it? Is it just a case of dropping the d3d8.dll in the same directory as the To.exe file and setting up a .dll override?

**Comment by WinterSnowfall** [comment]
> Is it just a case of dropping the d3d8.dll in the same directory as the To.exe file and setting up a .dll override?

Yeah, that would work. But it'll get old really fast if you have more than one dx8 game. I've used a similar approach to the DXVK installer and backed up the existing d3d8.dll found in my prefix's system32 directory and copied over the one provided by d3d8to9. You still need an override in either case.

**Comment by pierrep** [comment]
Excellent, thanks for your help. I tried something like this and failed, but must have been doing the wrong thing. I'll start from scratch and give it another go.
