### ISSUE TITLE
[d9vk] commit bf03fd87325414a877a0c2ea59edd6798e5e9a09 broke GOG Tourchlight

### ISSUE THREAD

**Issue by cork** [doitsujin/dxvk#1446]
GOG Torchright gets junk rendering since:
```
bf03fd87325414a877a0c2ea59edd6798e5e9a09 is the first bad commit
commit bf03fd87325414a877a0c2ea59edd6798e5e9a09
Author: Philip Rebohle <philip.rebohle@tu-dortmund.de>
Date:   Sun Feb 9 20:23:06 2020 +0100

    [d3d9] Implment fixed-function clipping

 src/d3d9/d3d9_fixed_function.cpp | 73 ++++++++++++++++++++++++++++++++++++++++
 1 file changed, 73 insertions(+)
```

![torchligt_bug1](https://user-images.githubusercontent.com/404380/74557031-92b45280-4f5f-11ea-920e-cfec8d8b441f.png)

![torchligt_bug2](https://user-images.githubusercontent.com/404380/74557039-9942ca00-4f5f-11ea-9c78-b09c441fcd7e.png)
### Software information
Torchlight, nothing changed from wine and game defaults except installing dxvk

### System information
- GPU: GeForce GTX 880M
- Driver: nvidia-dkms 440.44-14
- Wine version: wine-5.0 (Staging)
- DXVK version: v1.5.4-13-gbf03fd87 (bf03fd87325414a877a0c2ea59edd6798e5e9a09)

### Apitrace file(s)
https://ufile.io/zoh59sqc

### Log files
[Torchlight_d3d9.log](https://github.com/doitsujin/dxvk/files/4206091/Torchlight_d3d9.log)

**Comment by WinterSnowfall** [comment]
I'm having the same issue with the latest master build (g2096a95).

**Comment by Joshua-Ashton** [comment]
This should be fixed now.

**Comment by cork** [comment]
Yup, works fine. Thanks for the quick fix!
