### ISSUE TITLE
[d3d9] Cross Racing Championship Extreme 2005 has flickering water

### ISSUE THREAD

**Issue by CartoonFan** [doitsujin/dxvk#1450]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
DO NOT use DXVK together with apitrace!

### Software information
Cross Racing Championship Extreme 2005, max settings

### System information
- GPU: Nvidia GeForce GTX 960
- Driver: 440.43.2
- Wine version: 5.1.r15.g49d52336 ( TkG Staging Esync Fsync Vkd3d )
- DXVK version: v1.5.4-35-g50cf3a46

### Apitrace file(s)
https://drive.google.com/file/d/1zc4Flows4G1hFx1dVI6G_iYN5xZgm-Bv/view?usp=sharing

### Log files
- d3d9.log: [crc_d3d9.log](https://github.com/doitsujin/dxvk/files/4207782/crc_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

Hello! I'm reposting an older, unresolved issue: The water flickers sometimes as you drive by it. I think the default color of the water in DXVK may be different from native d3d9, as well.

Here's an image from DXVK:

![20200214-211137](https://user-images.githubusercontent.com/29664894/74582486-4b36c200-4f71-11ea-8be2-9637de9ae7dd.png)

And here's one from native d3d9:
![crc_2020_02_15_01_06_09_900](https://user-images.githubusercontent.com/29664894/74586108-09217680-4f99-11ea-85d8-98dfa5749947.png)

I also have a video of DXVK behavior here: https://drive.google.com/file/d/123Y2fUawvRe3ieLMH_zN1skRS7yJdq3t/view?usp=sharing

Thanks!

**Comment by doitsujin** [comment]
What exacly is it supposed to look like? It's a bit hard to see "flicker" on a static screenshot.

**Comment by CartoonFan** [comment]
Ah, sorry about that. I'm not used to making GIFs (or videos). I'll be updating the main post with a video and a native screenshot when they're available. I guess to describe it...with native, the water is always transparent, with a brown color visible underneath. With DXVK, the water is gray most of the time, but sometimes flickers very quickly between the gray color and the brown color as you drive by it.

**Comment by WinterSnowfall** [comment]
> I'm not used to making GIFs (or videos).

If you're looking for something fairly simple and easy to use, try [simplescreenrecorder](https://www.maartenbaert.be/simplescreenrecorder/).

**Comment by CartoonFan** [comment]
All right, thanks @WinterSnowfall !

**Comment by Joshua-Ashton** [comment]
This should be fixed now! :)

**Comment by CartoonFan** [comment]
Thank you!
