### ISSUE TITLE
Wolcen: Lords of Mayhem - Character head is surrounded by big blob

### ISSUE THREAD

**Issue by DxCx** [doitsujin/dxvk#1452]
### Software information
in `Wolcen: Lords of Mayhem`, when launching the game (and while playing) there is a big blob around the character head. (sometimes it blinks away, but its just there -_-)

Example Picture:
![wolcen-bug](https://user-images.githubusercontent.com/1080411/74593710-c1e9c300-5036-11ea-99ed-b157463f3f66.png)

I'll Try to run the game on windows later this week to provide API Trace + "how it should be".
but i belive i am not the only one it bothers, so if someone else can feel this info by then, it will be great! \o/

### System information
- GPU: GTX 1050
- Driver: 440.59.0
- Vulkan: 1.1.119
- Wine version: Proton 5.0-2
- DXVK version: v1.5.4-3-gfbca62df8

### Apitrace file(s)

* Will provide later (from windows PC), if someone can help with that meanwhile it will be great

### Log files
- d3d11.log:
[Wolcen_d3d11.log](https://github.com/doitsujin/dxvk/files/4208914/Wolcen_d3d11.log)

**Comment by doitsujin** [comment]
I'm aware, but I'll need an apitrace to debug the problem.

**Comment by DxCx** [comment]
Wow, since you responded so fast i'll try to catch up with IRL friend of mine who can help me get those from his windows machine.. stay tuned :P

**Comment by dlshinobi** [comment]
Windows + dx11 (native) = NO BIG BALL HEAD
Windows + dxvk = NO BIG BALL HEAD
WIne + dxvk = BIG BALL HEAD
Wine + wined3d = BIG BALL HEAD

**Comment by DxCx** [comment]
Where did you place the .dll to make it work? (Like load dxvk wolcen on windows)
i am trying to do it with my firend with no success, (not in bin, not in win_x64,not in Wolcen itslef) :\

**Comment by dlshinobi** [comment]
Yes, I put dlls in win_x64 folder, and it just works. p.s. I tested on win 8.1 (lol)
Just retested right now and no visual gliches so far. So it's not dxvk but wine issue.

**Comment by DxCx** [comment]
well thats the first directory i tried, and with `set DXVK_HUD=1` in console, then launch Wolcen.exe, i dont see any indication wolcen is indeed ran by DXVK.. :\
how did you verify you get DXVK backend and not native dx11?

**Comment by dlshinobi** [comment]
First the d3d11.log and dxgi.log were properly filled. Then MSI Afterburner overlay show VULKAN. And the performance different between dx11 and dxvk is noticeable.

**Comment by mozo78** [comment]
Sigh...
@doitsujin 
Here you are:
https://my.pcloud.com/publink/show?code=XZO2sskZx6M8Su7Qauua2YCYTCixryyjkkpy

**Comment by doitsujin** [comment]
Thanks, will take a look later.

One thing you could try is setting `dxvk.enableOpenVR = False` in `dxvk.conf` (also set `DXVK_CONFIG_FILE=/path/to/dxvk.conf`). vrclient is currently causing all sorts of issues unfortunately.

> And the performance difference between dx11 and dxvk is noticeable.

Got any numbers? CryEngine is known not to run very well on DXVK, but if you're on somewhat recent hardware (AMD Polaris / Nvidia Pascal or newer) then it shouldn't be more than a 20% hit. 

Unless of course there's some jankiness going on where the game magically runs much better when it thinks it's on an Nvidia card (*cough* Crysis 3).

**Comment by dlshinobi** [comment]
I didn't do a benchmark, but I was just running around in the beginning area and watched fps for a bit. On my old  GTX 960 (1080p + medium quality settings):
win + dx11 = 50-53 fps
win + dxvk = 34-39 fps
wine + dxvk = 33-35 fps (probably lower because kwin compositor is on)

**Comment by doitsujin** [comment]
Meh, that's pretty low. Might be due to 2GB VRAM though.

**Comment by mozo78** [comment]
Setting `dxvk.enableOpenVR = False` doesn't help with the "afro" problem. It continue to show some VR unable to find strings. 
Reporting Nvidia card doesn't help with performance. It's ~50 on Linux with DXVK and ~150 on Windows.
Intel 9900K, NVIDIA 1080 Ti here.

**Comment by mozo78** [comment]
Do you need some Wine logs?

**Comment by Joshua-Ashton** [comment]
Has anyone tried ``protontricks [appid] d3dcompiler d3dcompiler_43 d3dcompiler_47``? If that fixes it then it's d3dcompiler related.

**Comment by Berobad** [comment]
yes, didn't help

**Comment by DxCx** [comment]
Well, i am not sure how other people tested it but on -another- windows 10, ive tried throwing d3d11 dll in all directories there more or less, (yes including win_x64 where it makes most sense)

Then using sysinternals process explorer ive seen that indeed system32 one is loaded and not local one.. (but funny thing that i do see most of the loaded dlls are from win_x64 system)

Ive left windows systems more then a decade ago but i have to say this really doesnt act as expected and i would really like to see on my own how it works on windows with dxvk.. :/
Any idea if i can do something similar to linux LD_PRELOAD and force it to use my dll? (As trying to replace system32 one ends up with some guard system ?!?! :/)

(p.s, i did try gw2 with dxvk on that system and it works perfectly as expected and reacts to dxvk_hud/log)

**Comment by Berobad** [comment]
As long as dxvks dlls (dxgi.dll, d3d11.dll, ...) are in directory of the exe, windows should prefer them over the system32 ones.

**Comment by DxCx** [comment]
Yeah thats what i know from win 7 and below which i knew great.
But now on windows 10 it doesnt seem to be the case anymore..
And i am launching from cmd so i control the cwd.. 
Dlls from release x64 directory ( in wolcen/win_x64)

**Comment by Mixaill** [comment]
>As long as the dxvk dlls (dxgi.dll, d3d11.dll, ...) are in directory of the exe, windows should prefer them over the system32 ones.

Actually not. Some applications prefer to use system ones using `LoadLibraryEx` with `LOAD_LIBRARY_SEARCH_SYSTEM32` flag.

**Comment by DxCx** [comment]
Yeah well looks like i will have to belive in others when they say they got dxvk to load on windows for this game.. i couldnt, so i cant verify if thats indeed dxvk issue or not..

Do you want to close this issue based on @dlshinobi analysis?

**Comment by dlshinobi** [comment]
Sigh..., ok there is the MSI Afterburner Overlay in Wolcen:
![Wolcen_2020_02_19_10_43_30_714](https://user-images.githubusercontent.com/7222444/74827310-e0d9a500-5315-11ea-90c3-f2a607e496b4.png)
But still I wonder what the actually problem is in **wine** to cause this issue. And not only that, but also there is a bug with clothes (especially with female ones).

**Comment by ForeGone-G** [comment]
> But still I wonder what the actually problem is in **wine** to cause this issue. And not only that, but also there is a bug with clothes (especially with female ones).

That's exactly what I noticed as well. It is, however, not the clothes itself, but rather the character model. If you put a helmet on that hide the hair, you also hide the "afro". So the afro is related to the hair.. very likely at least. You can also see that by changing hair color.

The whole model looks untextured, with the exception of the armor of course.

**Comment by Mixaill** [comment]
>Sigh..., ok there is the MSI Afterburner Overlay in Wolcen:

By the way, DXVK HUD works for me in Wolcen.
![image](https://user-images.githubusercontent.com/704382/74878951-3b581d00-5379-11ea-9f2e-31a476cd91ec.png)

**Comment by liberodark** [comment]
Nvidia 440
GTX 2070
 DXVK 1.5.4

Me too : 

![image](https://user-images.githubusercontent.com/4238928/74934866-7133ea80-53e7-11ea-933f-fec1c42ff6bd.png)

**Comment by DxCx** [comment]
Ok nice. Thanks for helping me out :)
So @doitsujin i assume we should close ticket here..
Any idea where i should open this ticket? Wine bug tracker?

**Comment by Fincer** [comment]
Either Wine bug tracker or existing [Proton GitHub issue for Wolcen](https://github.com/ValveSoftware/Proton/issues/496). Wine bug tracker may get attention of Wine devs, or at least it's possible.
