### ISSUE TITLE
no AllocateLocallyUniqueId procedure entry point in d3d9.dll(and dxgi.dll) on Windows 10

### ISSUE THREAD

**Issue by ptrb78** [doitsujin/dxvk#1453]
I cant run several(or any) games on Windows.
Games tested: Crysis, System Shock 2, Unreal Gold.
I use Archlinux on virtual machine to build dxvk.
i use Tk-Glitch repository to build mingw.
System information
- GPU: gtx 1070
- Driver: 442.19.0
- DXVK version:  latest git
- System: Windows 10 Pro x64

Edit: No problems with officialy released binaries (1.5.4) in dx9 mode. Crysis x64 dont start in dx10 mode with error about no entry point in procedure D3D10CoreGetVersion in d3d10.dll.

**Comment by Joshua-Ashton** [comment]
This is some form of build issue on your end and I have no idea where/how/why you're going wrong.

As for `D3D10CoreGetVersion`, that is a genuine issue.

**Comment by Joshua-Ashton** [comment]
I've done an implementation of D3D10[Core]GetVersion and D3D10[Core]RegisterLayers needed for Crysis here:

https://github.com/doitsujin/dxvk/pull/1454

**Comment by doitsujin** [comment]
> Crysis x64 dont start in dx10 mode with error about no entry point in procedure D3D10CoreGetVersion in d3d10.dll.

You need **both** `d3d10.dll` and `dxgi.dll` to run the game. Just `d3d10.dll` isn't enough.

**Comment by Joshua-Ashton** [comment]
Turns out that the game will always load d3d10.dll from System32/d3d10.dll, which will then load the local d3d10core.dll and query that func.

It does actually work with that PR though magically.

**Comment by ptrb78** [comment]
My builds still not working.
Could you post links with information how to build dxvk with Microsoft Visual Studio?

**Comment by ZachBacon** [comment]
@ptrb78 https://github.com/doitsujin/dxvk/blob/master/README.md#building-dlls build requirements are listed in the readme

**Comment by ptrb78** [comment]
My problem was a build issue. Closing.
