### ISSUE TITLE
[d3d9] World of Warcraft 3.3.5a: all texts missed

### ISSUE THREAD

**Issue by RefiniX** [doitsujin/dxvk#1455]
wined3d
![Wow335_wined3d](https://user-images.githubusercontent.com/61114903/74606448-5a517780-510b-11ea-8872-5e750bba8bf6.jpg)

dxvk 1.5.1 and below (d9vk included)
![Wow335_dxvk_1 5 1](https://user-images.githubusercontent.com/61114903/74606443-59204a80-510b-11ea-9f90-71090db7cda3.jpg)

dxvk 1.5.2 and above (print screen with dxvk 1.5.4)
![Wow335_dxvk_1 5 4](https://user-images.githubusercontent.com/61114903/74606447-5a517780-510b-11ea-89fd-686f64164d06.jpg)
![Wow335_dxvk_1 5 4_playing](https://user-images.githubusercontent.com/61114903/74606681-7229fb00-510d-11ea-8d22-d2d7dda7fedd.jpg)

some extra stuffs may off-topic:
Wow 5.4.8 dxvk 1.5.4 with d3d9 mode
![Wow548_d3d9_dxvk_1 5 4](https://user-images.githubusercontent.com/61114903/74606449-5aea0e00-510b-11ea-907a-7b32e51479f3.jpg)
Wow 5.4.8 dxvk 1.5.4 with d3d11 mode
![Wow548_d3d11_dxvk_1 5 4](https://user-images.githubusercontent.com/61114903/74606450-5b82a480-510b-11ea-825a-3393b12d25a7.jpg)

If you need any further information, please feel free to contact me. thanks.

### Software information
World of Warcraft 3.3.5a

### System information
- OS: Archlinux kernel 5.5.3
- GPU: Intel HD Graphics 4000 (IVB GT2) (0x166)
- Driver: Mesa 20.1.0-devel (git-8f5a252d35) from aur/mesa-git & aur/lib32-mesa-git
- Wine version: wine-staging 5.1 from Archlinux repo 
- DXVK version: 1.5.4

### Apitrace file(s)
https://drive.google.com/file/d/1cdhT87PGL5kA9dZkCFSiR6wTn6a1msfk/view?usp=sharing

### Log files
- d3d9.log: 
https://drive.google.com/file/d/1aCalXWOGnkTUcuAuV0nAqDRNNGXUXhY2/view?usp=sharing
this file will keep increased by the "err: D3D9: Cannot create texture:..." message.

### vulkaninfo outputs
https://drive.google.com/file/d/1pUuMRn3G17t8mbJUmttViyCuNt4xL87d/view?usp=sharing

**Comment by Joshua-Ashton** [comment]
Your hardware doesn't support the format the game is trying to use:

https://vulkan.gpuinfo.org/displayreport.php?id=7904#formats

**Comment by Joshua-Ashton** [comment]
Actually, I think I can workaround this and perhaps simplify the existing implementation of this format, one moment.

**Comment by Joshua-Ashton** [comment]
Please try with this build https://git.froggi.es/doitsujin/dxvk/-/jobs/1158

**Comment by RefiniX** [comment]
Hi Joshua-Ashton,

It works better, thanks!
the text of some areas appeared by running a6d5546.

![Wow_Login](https://user-images.githubusercontent.com/61114903/74616783-d2985700-5164-11ea-9f81-a9020d9097dd.jpg)
![Wow_Playing](https://user-images.githubusercontent.com/61114903/74616785-d3c98400-5164-11ea-8732-41538798c8d7.jpg)

* Apitrace file(s)
https://drive.google.com/file/d/1EOLEGhdgvtss4H8RgrtxguhIrhZiSXEQ/view?usp=sharing
  
* Log file(s)
https://drive.google.com/file/d/1ENm9_dKsUtcd085Rhhe35bgogKHuyC8x/view?usp=sharing
no more "err: D3D9: Cannot create texture:..." message in this file.

**Comment by Joshua-Ashton** [comment]
This should be completely fixed as of `master` now.

**Comment by RefiniX** [comment]
i can confirm that 4cf3ef5 works flawless for me.
Joshua-Ashton and doitsujin, thank you!
