### ISSUE TITLE
(Question) Any way to always force triple-buffering?

### ISSUE THREAD

**Issue by yaskme** [doitsujin/dxvk#1456]
İ'm asking because İ got sick of framerates bouncing around on my 60 Hz monitor.
Triple-buffering would at least allow a more graceful change of pace of the fluidity of animations on-screen.

İ've already tried setting `dxgi.numBackBuffers = 4`, but it only seems to make a difference when Vsync is disabled, which in itself causes way more frame-pacing issues than simply having it on all the time.

That's why İ hope there could be a simple & universal way of always enforcing triple-buffering with activated Vsync, even if the games have not been coded with multiple buffers in mind.

Thanks for any response in advance!

**Comment by doitsujin** [comment]
Triple-buffering is active when the app requests it or if you set `dxgi.numBackBuffers = 3` or higher. If that doesn't work, something is broken on your setup.

**Comment by yaskme** [comment]
@doitsujin 
Thanks for answering!

Like İ already said, `dxgi.numBackBuffers` does make a difference, but _only_ if İ disable Vsync; otherwise, framerate is still locked to a multiple of my 60 Hz monitor.

İs there anything else İ could try to get variable FPS with activated Vsync?

**Comment by Joshua-Ashton** [comment]
> İs there anything else İ could try to get variable FPS with activated Vsync?

The whole point of vsync is that it syncs to the vertical blank of your display.

**Comment by yaskme** [comment]
@Joshua-Ashton 
Obviously İ'm aware of what Vsync is supposed to do...

Let me give an example to make my point more clear:

On my nVidia system, İ can activate triple-buffering system-wide by putting this into xorg.conf:
`Option "TripleBuffering" "True"`
This way, when İ run an OpenGL-utilising app (i.e. Unigine benchmarks), İ can observe that the FPS are gradually changing instead of jumping between 60, 30, 20, 15, …
All of the above while still having a tear-free experience, since Vsync is still applying correctly, even though the FPS are now changing independently from my monitor's refresh rate!

İ hope the above example could make my point clear enough;
really, all İ want to achieve is for my GPU to keep producing new frames, without having to wait on the refresh rate of my monitor, while at the same time still enjoying an absolutely tear-free experience thanks to active Vsync!

İ really hope there is a way this can also be achieved with DXVK…

**Comment by doitsujin** [comment]
Well as mentioned, that *should* work fine as it is, and on both my AMD and Nvidia GPUs it *does* work just fine.
