### ISSUE TITLE
Guild Wars 2 text problem

### ISSUE THREAD

**Issue by logan001** [doitsujin/dxvk#1457]
There is some filled box around all text.

### Software information
Guild Wars 2

### System information
- GPU: nvidia 970
- Driver: 440.58.01
- Wine version: wine-5.1.r15.g49d52336 ( TkG Staging Esync Fsync )
- DXVK version: 4405b51bf39714aaae6ab6e9b85d158b53e8a0b6

### Apitrace file(s)
You can pick one from [here](https://drive.google.com/open?id=0B21AKedF-JpVb2lHdEtLSWY4a2c) 

### Log files
- d3d9.log:
[Gw2-64_d3d9.log](https://github.com/doitsujin/dxvk/files/4213228/Gw2-64_d3d9.log)

**Comment by doitsujin** [comment]
I don't see any obvious issue in the video you uploaded, what are we looking at?

**Comment by doitsujin** [comment]
Confirming that a6d554615e5f939826db758263f9b59ea2333ecc broke this, replaying the trace made it obvious. @Joshua-Ashton
