### ISSUE TITLE
wine-git now supporting DXVK

### ISSUE THREAD

**Issue by schtufbox** [doitsujin/dxvk#146]
As per title, with recent updated the wine dev has updated vulkan from wine-vulkan and as long as the vulkan SDK is installed, as per wine-vulkan, then DXVK works.

**Comment by doitsujin** [comment]
Thanks for the info, I'll test that later.

**Comment by schtufbox** [comment]
Cool, I just compiled and tested and it worked for me (playing ESO as I type lol) but yeah, best to test yourself first :D

**Comment by Yardanico** [comment]
@schtufbox you mean latest wine-git?

**Comment by schtufbox** [comment]
Forget it I'm an idiot, what with messing with various wine versions, I didn't realise I'd selected the wine-git with the vulkan stuff from staging 2.21...It does NOT run in wine-git, sorry for any confusion...Next tiem I'll double check before I get all excited!!
