### ISSUE TITLE
[d3d9] Performance regression in several titles after a recent commit

### ISSUE THREAD

**Issue by ThisNameIsntTaken** [doitsujin/dxvk#1460]
While testing the [Vindictus issue](https://github.com/Joshua-Ashton/d9vk/issues/303) I reported on the D9VK bug tracker a while ago, I've noticed that the game runs noticeably slower than it did a few weeks ago when I last tried. After doing some digging, I found out that the commit causing the problem is 50cf3a4.

I've tried a few other games as well, and some of them also took the 20-25% performance hit.
Other than the games listed below, I've also tested Borderlands 2, that one doesn't seem to be affected.

### Software information
Vindictus, NFS Most Wanted 2005, TrackMania United Forever and potentially many others.

### System information
- GPU: RX 580 4GB
- Driver: RADV ACO Git
- Wine version: 5.1 TkG
- DXVK version: 4cf3ef5

### Apitrace file(s)
- The issue can be reproduced by replaying the [trace](https://mega.nz/#!W5U10SbC!TME6zUcLuTYBTyKPu_s6sBDkRnFPSSYs919K7Frd6BY) from the issue mentioned earlier.

### Log files
- [speed_d3d9.log](https://github.com/doitsujin/dxvk/files/4216832/speed_d3d9.log)
- [TmForever_d3d9.log](https://github.com/doitsujin/dxvk/files/4216833/TmForever_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Can you give numbers?

**Comment by Iglu47** [comment]
I made 14 test through bench in `TrackMania United Forever` option
first 3 with 1.5.4.r34 and other 3 with 1.5.4.r38 then 4 more each again

dxvk-git-1.5.4.r34.g7d3ec74b - 206 207 206 207 [205](https://github.com/doitsujin/dxvk/files/4217395/Bench_1.5.4.r34_test5.txt) 206 [206](https://github.com/doitsujin/dxvk/files/4217396/Bench_1.5.4.r34_test7.txt) (~206,1 fps)
dxvk-git-1.5.4.r38.g4cf3ef53 - 167 166 167 166 [166](https://github.com/doitsujin/dxvk/files/4217397/Bench_1.5.4.r38_test5.txt) [170](https://github.com/doitsujin/dxvk/files/4217398/Bench_1.5.4.r38_test6.txt) 167 (~167,0 fps)
_*couple logs in links_
- nvidia proprietary driver: 440.59; gtx nvidia 1080ti
- arch linux, liquorix-5.4.17
- wine-tkg 5.1.r15.g49d52336

**Comment by Joshua-Ashton** [comment]
[d3d9.zip](https://github.com/doitsujin/dxvk/files/4217675/d3d9.zip)

Can you try with this build?

**Comment by Iglu47** [comment]
> [d3d9.zip](https://github.com/doitsujin/dxvk/files/4217675/d3d9.zip)
> 
> Can you try with this build?

[164](https://github.com/doitsujin/dxvk/files/4217694/Bench_patch_test1.txt) [162](https://github.com/doitsujin/dxvk/files/4217695/Bench_patch_test2.txt) 162 162 [163](https://github.com/doitsujin/dxvk/files/4217696/Bench_patch_test5.txt) (~162,6 fps)

**Comment by ThisNameIsntTaken** [comment]
In TrackMania, the framerate really depends on the environment you are playing in.
- In a stadium level (StadiumA1), the fps went from 206 to 176.
- In a coast level (StarCoastB4), the fps went from 340 to 250.

In NFS Most Wanted 2005, the fps went from 94 to 74.

Vindictus has a framerate cap of 60, but it drops a lot more often than it used to.

The build above doesn't seem to change anything.

**Comment by refelian** [comment]
I also noticed this while playing FF13-2. Going from proton 4 to 5 deteriorated performance (it became choppy and nearly unplayable). I can provide logs if necessary.

**Comment by Joshua-Ashton** [comment]
Please make a separate bug that's something different entirely

**Comment by Joshua-Ashton** [comment]
This perf regression should be fixed in master now,

**Comment by Iglu47** [comment]
dxvk 1.5.4.r42.g760a163f: [208](https://github.com/doitsujin/dxvk/files/4221289/Bench_fixed_test1.txt) [207](https://github.com/doitsujin/dxvk/files/4221290/Bench_fixed_test2.txt) [209](https://github.com/doitsujin/dxvk/files/4221291/Bench_fixed_test3.txt) [207](https://github.com/doitsujin/dxvk/files/4221292/Bench_fixed_test4.txt) (~ 207,8 fps)

**Comment by ThisNameIsntTaken** [comment]
Indeed, performance is back to normal.
