### ISSUE TITLE
[d3d9] Lumino City → switching from fullscreen to windowed, it hangs

### ISSUE THREAD

**Issue by NerosTie** [doitsujin/dxvk#1462]
Title

### System information
- GPU: Nvidia GT 730M
- Driver: Nvidia Vulkan 440.58.01
- Wine version: Proton 5.0
- DXVK version: #1160

### Apitrace file(s)
https://mega.nz/#!6ywwSaJR!xedvFbkgKSmqGiWdyuJ8wSgxWOOSpbPrS3J5JxRZVQM

### Log files
[steam-205020-d9vk.log](https://github.com/doitsujin/dxvk/files/4219310/steam-205020-d9vk.log)
[steam-205020-wined3d.log](https://github.com/doitsujin/dxvk/files/4219311/steam-205020-wined3d.log)

**Comment by Joshua-Ashton** [comment]
This fixed the hang for me, but I still need to fix the other validation error in this title.

**Comment by Joshua-Ashton** [comment]
Ok I fixed those val errors

**Comment by NerosTie** [comment]
Fixed! Thanks :)
