### ISSUE TITLE
[d3d9] Just Cause (6880) crashes to desktop after starting a new game.

### ISSUE THREAD

**Issue by ZereoX** [doitsujin/dxvk#1464]
After selecting "Start Game" -> "New Game", the title will crash once the loading is done. The title usually proceeds to video playback after this loading is finished. 

This occurs on both Proton 5.0-2 and Windows using DXVK 1.5.4 or master (760a163). 18450f46 is the last known functional build that allows you to proceed in game. Starting with 7c53a997, the title will crash during the initial launch of the game and caae5d18 and newer shows the issues described above.

The title does load into game correctly with WineD3D.

Please let me know if any additional information is required or if additional testing is needed.

### Software information
Just Cause ([6880](https://store.steampowered.com/app/6880))

### System information
- OS: Ubuntu 18.04 / Windows 10 Pro 1909
- GPU: Radeon RX 580 / Nvidia GeForce GTX 1060
- Driver: 20.1\~git2002171250.b7e966\~oibaf\~b / 440.59-0ubuntu0.18.04.1
- Wine version: Proton 5.0-2 / Wine-Staging 5.2 w/ Windows Steam
- DXVK version: 1.5.4 / Master (760a163)

### Apitrace file(s)
- https://drive.google.com/open?id=1h9UpN6s69OGkBI3ePbpuyE6_lQxik85E

### Log files
- d3d9.log: [JustCause_d3d9.log](https://github.com/doitsujin/dxvk/files/4220903/JustCause_d3d9.log)

### Bisect w/ froggi.es builds:
master - 760a163 (❌)
1.5.4 - 2435c63 (❌)
1.5.2 - e242d7f (❌)
9919ffe5 (❌)
7de15fe8 (❌)
eed57ed6 (❌)
caae5d18 (❌)
b954ab88 (❌) - Crash during launch
bafcaa0c (❌) - Crash during launch
eb37dfa8 (❌) - Crash during launch
9e5e4c1c (❌) - Crash during launch
7c53a997 (❌) - Crash during launch
18450f46 (✔️)
a7b4c299 (✔️)
1.5.1 - 4308d9b (✔️)

**Comment by Joshua-Ashton** [comment]
Should be fixed now, cheers!

**Comment by ZereoX** [comment]
Thanks. I've confirmed the issue is resolved on master.
