### ISSUE TITLE
[d3d9] steam overlay doesn't work 

### ISSUE THREAD

**Issue by narcissussic** [doitsujin/dxvk#1467]
steam overlay doesn't work when I use dxvk on win10,but other overlay software work normal like rtss and amd relive.
### Software information
all the game?maybe
### System information
- GPU:rx5700
- Driver:19.40.01.22-191211a-351548C-RadeonProEnterprise
- Wine version: 
- DXVK version: 1.5.4

### Log files
- d3d9.log:
[Dishonored_d3d9.log](https://github.com/doitsujin/dxvk/files/4226394/Dishonored_d3d9.log)
[witcher2.EXE_d3d9.log](https://github.com/doitsujin/dxvk/files/4226391/witcher2.EXE_d3d9.log)
- d3d11.log:
- dxgi.log:

**Comment by Joshua-Ashton** [comment]
This isn't our bug.

If you install DXVK in Windows/System32 it works.

**Comment by narcissussic** [comment]
> This isn't our bug. The overlay on x86 just won't hook loose `d3d9.dll`s. (it works on x64)
> 
> If you install DXVK in Windows/SysWOW64 it works too.

you means replace syswow64  d3d9.dll with dxvk's, right?

**Comment by Joshua-Ashton** [comment]
I'm not recommending you do that, but yes.
