### ISSUE TITLE
[D3D9] Oblivion freezes after 1-2 minutes of game play unless music is disabled

### ISSUE THREAD

**Issue by DucDuNord** [doitsujin/dxvk#1470]
The Elder Scrolls IV: Oblivion will freeze after a few minutes of game play unless music is disabled by setting **bmusicenabled=0** in Oblivion.ini.

If winegstreamer is enabled, it will produce a long string of error messages until the application freezes. If winegstreamer is disabled using a DLL override in the Wine Configuration menu, there are no more error messages, yet the freeze still occurs, and just as quickly.

It makes no difference whether or not Oblivion is run from within a virtual desktop or not. 

This problem does not occur if the game is run from a Crossover Office 19.01 bottle with 'Performance Enhanced Graphics' enabled, yet Crossover may be using an older version of DXVK which does not yet support DirectX 9 games (Crossover also still features the bug where the PC's skin is pitch black irrespective of the settings the player uses in the character creation menu). 

The problem also does not occur if the game is run from a Crossover Office 19.01 bottle which does not have 'Performance Enhanced Graphics' enabled, and thus uses WineD3D instead.

###Software information
The Elder Scrolls IV: Oblivion - Game of the Year Edition Deluxe (GOG version)

### System information
- GPU: AMD Vega56
- Driver: AMDGPU, Mesa 20.0.0-devel - padoka PPA
- Wine version: 5.2
- DXVK version: 1.5.4

### Apitrace and log file(s)
These will be added as soon as possible. I need to change my setup to produce new ones as I have been experimenting to find out what was causing the freezes.

**Comment by Joshua-Ashton** [comment]
This isn't our bug. Please make an issue with Wine.

**Comment by WinterSnowfall** [comment]
It's not happening on Wine Staging 5.2 / DXVK 1.5.4 (latest master), at least not with an Nvidia card. I've been playing for 30 minutes now. Although I haven't ever seen it run out of memory so far, I guess it may be related to #1318, especially if you're using a lot of mods.

**Comment by DucDuNord** [comment]
> This isn't our bug. Please make an issue with Wine.

Thanks for your reply. I realised after posting that this bug likely had a different origin; I've just created a new Wine prefix without DXVK, and the same problem occurs. Need to report this with the Wine developers, as you said.

**Comment by Ebeeb513** [comment]
I found it to be some sort of codec issue, I installed   K-Lite Codec Pack and it is running alright now.         https://codecguide.com/download_k-lite_codec_pack_full.htm
