### ISSUE TITLE
Error compiling DXVK-winelib with LTO:

### ISSUE THREAD

**Issue by ViNi-Arco** [doitsujin/dxvk#1473]
Hello, good afternoon! I get this error when compiling dxvk-winelib with LTO:

![oie_Szx65BzVOj4k](https://user-images.githubusercontent.com/57958460/75188877-c5aed100-572b-11ea-928d-b22bfd1fecec.png)

I put the flag like '-flto' in cpp_args and c_args.

**Comment by pchome** [comment]
Some parts of Wine must be built with LTO, at least `wine/libwinecrt0.a`.

**Comment by ViNi-Arco** [comment]
Thanks for the information pchome, I did a little research on 'wine / libwinecrt0.a' and got to that: https://github.com/InBetweenNames/gentooLTO/issues/328

From what I understand, it is possible to partially compile the DXVK with Winegcc / LTO, I may have misunderstood, but from what you said first, I need to compile Wine with LTO in order to compile the DXVK right?

**Comment by pchome** [comment]
@ViNi-Arco 
> I need to compile Wine with LTO in order to compile the DXVK right?

Yes.

**Comment by ViNi-Arco** [comment]
Thank @pchome, you have a good day.
I'll leave this issue open, for me to test and see what will happen, then I'll come back to tell you what happened :+1:.

**Comment by doitsujin** [comment]
We do not plan to support exotic configurations for winelib builds.

**Comment by ViNi-Arco** [comment]
I understand you Philip, it is very complicated to make the LTO work in Wine, you need a patch, and it is very haky, and you can only compile the 32bit part of DXVK-winelib, on the other hand, DXVK with Mingw works perfectly with LTO, see the difference DXVK-Mingw with and without LTO, with LTO it is lighter:

![oie_Q9Rm30sKqkId](https://user-images.githubusercontent.com/57958460/75370369-b9e61a80-58a3-11ea-926a-77f59694ef65.png)

In terms of performance there is an improvement, with LTO there is an increase of 5%~7% depending on the game in my tests, Have a good afternoon.
