### ISSUE TITLE
Terrain not render

### ISSUE THREAD

**Issue by bernardo-bruning** [doitsujin/dxvk#1474]
Currently when running the game it does not render the terrain and some objects like the character's arm

### Software information
 Rust, from steam

### System information
- GPU:  Intel(R) HD Graphics 620
- Driver: Mesa 19.3.4
- Proton 5.0-3

### Log files
- [d3d11.log](https://gist.github.com/bernardo-bruning/c3073d1d4ebb2b3a8c56ad32cba7a307#file-rustclient_d3d11-log)

**Comment by doitsujin** [comment]
Probably a driver bug, the game is known to work.

**Comment by bernardo-bruning** [comment]
Okay, I'll check if I can get the apitracer. 
I find it strange that for wined3d it works right.
thank you for your attention.

**Comment by doitsujin** [comment]
Actually, looking at your log again:
```
err:   Heap 0: 1024 MB allocated, 667 MB used, 1042 MB allocated (driver), 10768 MB budget (driver), 10768 MB total
err:   Heap 1: 1020 MB allocated, 908 MB used, 1021 MB allocated (driver), 1024 MB budget (driver), 1024 MB total
err:   DxvkMemoryAllocator: Memory allocation failed
err:   DxvkMemoryAllocator: Memory allocation failed
err:     Size:      3840
err:     Alignment: 16
err:     Mem flags: 0x1
err:     Mem types: 0x2
```
You're just running out of memory for some reason.

I didn't notice this the first time around since `debug` logging was enabled, please don't do this unless requested since it's mostly useless info.

**Comment by bernardo-bruning** [comment]
Hello, I solved my memory allocation problem by forcing the allocation to ram when dxvk is unable to allocate to the supported and adequate memory. The game is running well and without BUGs so far.
