### ISSUE TITLE
[d3d9] Evenicle - Crash to desktop at startup (wine) / Black screen (proton)

### ISSUE THREAD

**Issue by enimog** [doitsujin/dxvk#1476]
I was a bit hesitant at first to report the issue, the game being a H-game and all, but hey, these games also need some love, don't judge please :)

The issue is the following :

If I try running the game using proton;
- Using version 4.11, the game run properly.
- Using version 5.0.3, the game render as a black screen. I am still able to press the buttons from the main menu and do stuff, I am only unable to see what I am doing.

If I try running the game using the latest wine and DXVK
- I create a new wine prefix and then run setup_dxvk.sh install --symlink
- I cd into the game directory and run "wine Evenicle.exe".
- The game imediately crashes. I get the following backtrace from wine: 
[Evenicle-backtrace.txt](https://github.com/doitsujin/dxvk/files/4253107/Evenicle-backtrace.txt)

If I try running the game using the latest wine without DXVK
- I create a new wine prefix
- I cd into the game directory and run "wine Evenicle.exe".
- The game is working properly without issues

### Software information
Evenicle, steam build
https://store.steampowered.com/app/955560/Evenicle/

### System information
- GPU: Nvidia GTX 970
- Driver: Proprietary, 440.59
- Wine version: 5.2 (staging)
- DXVK version: 1.5.4-55-gfbf76e84+ (Last commit on master).

### Apitrace file(s)
[Evenicle.trace.zip](https://github.com/doitsujin/dxvk/files/4253085/Evenicle.trace.zip)

### Log files
- d3d9.log: [Evenicle_d3d9.log](https://github.com/doitsujin/dxvk/files/4253084/Evenicle_d3d9.log)

**Comment by Blisto91** [comment]
@enimog sorry to necro. Could you try to test if it's still a issue with latest dxvk and drivers? 🙂

**Comment by enimog** [comment]
Hello @Blisto91 :) Tested it, and I'm still having a black screen when starting the game on both steam (latest proton GE) and normal wine 7.12 +dxvk 1.10.1. 
Same old GTX 970, driver 515.57.

I notice that when I move the mouse, the GUI element that is refreshed (ex: the button my mouse is over) is displayed, so yes I guess this is what you means by partial presentation?
![Screenshot_20220705_120930](https://user-images.githubusercontent.com/11507070/177371109-89aa2de2-896e-48fb-beb6-58499116e941.png)

**Comment by artemyto** [comment]
@enimog can you retest this game with d3d9.shaderModel = 1 ?

**Comment by enimog** [comment]
With that option the game crash at startup with "Shader model 2.0 not supported"
