### ISSUE TITLE
Starcarft 2 crashes on startup

### ISSUE THREAD

**Issue by Zemogiter** [doitsujin/dxvk#1478]
Once I click on "Play" button in Blizzard App, it becomes inactive while the game attempts to launch. After few seconds it goes back to "Play" and the game process quits without any error message.
[wine.log](https://github.com/doitsujin/dxvk/files/4255716/wine.log)
### Software information
Name of the game, settings used etc.
Using x64 prefix with DXVK, d3dcompiler42 and d3dcompiler47 installed
### System information
- GPU:GTX 1080 ti
- Driver:440.59
- Wine version: 5.0
- DXVK version: 1.5.4

### Apitrace file(s)
Despite following the instructions on D9VK's repo I haven't found any .trace files

### Log files
- d3d9.log: no log generated
- d3d11.log:
[Battle.net_d3d11.log](https://github.com/doitsujin/dxvk/files/4255675/Battle.net_d3d11.log)
- dxgi.log:
[Agent_dxgi.log](https://github.com/doitsujin/dxvk/files/4255674/Agent_dxgi.log)

**Comment by doitsujin** [comment]
Does it work with wined3d?

The wine log indicates that the game doesn't even get started, which means there's some issue with Battle.net.

**Comment by doitsujin** [comment]
Confirmed that the game **does** work fine for others with DXVK, this is not our bug. Please double-check your setup and/or try setting up Battle.net with Lutris.

**Comment by Zemogiter** [comment]
Tried with lutris and it works. 
[Agent_dxgi.log](https://github.com/doitsujin/dxvk/files/4262958/Agent_dxgi.log)
[SC2_x64_d3d9.log](https://github.com/doitsujin/dxvk/files/4262959/SC2_x64_d3d9.log)
[SC2_x64_dxgi.log](https://github.com/doitsujin/dxvk/files/4262960/SC2_x64_dxgi.log)
[Battle.net_d3d11.log](https://github.com/doitsujin/dxvk/files/4262961/Battle.net_d3d11.log)
[SystemSurvey_dxgi.log](https://github.com/doitsujin/dxvk/files/4262962/SystemSurvey_dxgi.log)

**Comment by doitsujin** [comment]
Probably not our bug then.
