### ISSUE TITLE
Uplay crashes when DXVK is installed

### ISSUE THREAD

**Issue by Shished** [doitsujin/dxvk#1479]
Uplay started to crash right after launch with an unrecoverable error message. When DXVK is not used (after removing its dll overrides in winecfg) it works just fine. Same problem appears when fresh wineprefix is used.

### Software information

Ubisoft Uplay

### System information
- GPU: GTX 1060
- Driver: 440.59
- Wine version: wine TkG Staging Esync Fsync 5.2
- DXVK version: v1.5.4-55-gfbf76e84

### Apitrace file(s)
- Put a link here
N/A

### Log files
- d3d9.log: [upc_d3d9.log](https://github.com/doitsujin/dxvk/files/4257558/upc_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by doitsujin** [comment]
Uplay works fine on my end.

Can you try `WINEDLLOVERRIDES=d3d9=b`? This would make it use DXVK for D3D11, but not D3D9.

**Comment by Shished** [comment]
Yes, that works. I simply removed d3d9.dll from overrides list in winecfg and Uplay works again.

**Comment by Blisto91** [comment]
@Shished Friendly ping. Do you still have this issue with newest uplay and dxvk versions?
