### ISSUE TITLE
[d3d9] VenusBlood FRONTIER International (1189440) - Transitioning to Fullscreen will cause graphical flickering in the title's left pillarbox.

### ISSUE THREAD

**Issue by ZereoX** [doitsujin/dxvk#1481]
### Description:
Transitioning from Windowed to Fullscreen mode will cause graphical flickering to appear in the game's left pillarbox (title has a 4:3 aspect ration). The flicker appears to be remnants of the options menu.

Video: https://www.youtube.com/watch?v=22dym_0aC_I

This occurs on both Proton 5.0-3 and Windows using DXVK 1.5.4 or master (3587bcdb). b954ab88 is the last known functional build that allows you to transition to Fullscreen without any issues. Starting with caae5d18, the title will start rendering part of the in-game Settings menu inside the left pillarbox. 

The title does appear correctly when transitioning to Fullscreen with WineD3D and on native Windows. The issue also does not occur when launching directly into a Fullscreen state.

Please let me know if any additional information is required or if additional testing is needed.

### Notes:
- This game stops rendering new frames the moment you enter the settings menu.
- The in-game exit confirmation prompts is its own window (so... two DXVK_HUD).
- On Mesa if _RADV_DEBUG=zerovram_ is not set, the pillar-boxes will be filled with garbage data causing additional visual corruption:

| AMD Mesa w/o zerovram | Confirmation Prompt |
|-----------------------|:-------------------:|
|![1189440 VenusBlood - Mesa ](https://user-images.githubusercontent.com/761853/75557631-5f1d0200-5a0e-11ea-84d8-6f7038805251.png)|![DXVK_HUD_PROMPT](https://user-images.githubusercontent.com/761853/75557636-617f5c00-5a0e-11ea-8371-8082ebbdf09a.png)|

### Software information
VenusBlood FRONTIER International ([1189440](https://store.steampowered.com/app/1189440))

### System information
- OS: Ubuntu 18.04 / Windows 10 Pro 1909
- GPU: Radeon RX 580 / Nvidia GeForce GTX 970
- Driver: 20.1\~git2002270730.2b155b\~oibaf\~b / 440.59-0ubuntu0.18.04.1
- Wine version: Proton 5.0-3
- DXVK version: 1.5.4 / Master (3587bcdb)

### Apitrace file(s)
- https://drive.google.com/open?id=18horFsT5Ww6ZlH3qEqo9Pm0dR2uaEaGD

### Log files
- d3d9.log: [VBFI_d3d9.log](https://github.com/doitsujin/dxvk/files/4267324/VBFI_d3d9.log)

### Bisect w/ froggi.es builds:
master - 3587bcdb (❌)
1.5.4 - 2435c63 (❌)
1.5.2 - e242d7f (❌)
a57dc752 (❌)
eed57ed6 (❌)
caae5d18 (❌)
b954ab88 (✔️)
9e5e4c1c (✔️)
1.5.1 - 4308d9b (✔️)

**Comment by w-flo** [comment]
According to the trace, this game uses `SwapEffect = D3DSWAPEFFECT_COPY`. I believe this is not fully implemented in dxvk right now, but it looks like some work on it has been started recently. COPY swapeffect semantics were used in dxvk pre-1.5.2 by happenstance and, as I understand it, had to go in order to support multiple backbuffers and GetFrontBufferData.

Related: #1368, even though that one is about a game that claims to use SWAPEFFECT_DISCARD (which is compatible with the current dxvk implementation), but still requires SWAPEFFECT_COPY semantics. Windows drivers just happen to offer COPY semantics when using DISCARD in windowed mode.

**Comment by Joshua-Ashton** [comment]
There is the d3d9_partial_presentation branch if you want to give it a try.

**Comment by ZereoX** [comment]
The d3d9_partial_presentation branch result in the same behaviour as described above.

**Comment by ZereoX** [comment]
Hey @Joshua-Ashton, I've confirmed that enabling "d3d9.noExplicitFrontBuffer" does resolve the issue on this title. RADV still requires the "zerovram" debug option, but otherwise the issue is completely resolved on Nvidia when toggling that option on master (3697583).

MR for enabling that option has been entered.

**Comment by ZereoX** [comment]
@Joshua-Ashton Sorry to bother you, but It would seem that The Elder Scrolls: Online's installer for its launcher also requires partial presentation for its prompts (Don't know if this is already known). The breakage match the commits mentioned in the top post. This only affects the installer portion and not the Launcher itself or the game client.

On b954ab8, the log indicates a failure to create an image view and the installer appears correctly (no DXVK HUD):
> err:   DxvkImageView: Failed to create image view:
err:     View type:       VK_IMAGE_VIEW_TYPE_2D
err:     View format:     VK_FORMAT_UNDEFINED
err:     Subresources:    
err:       Aspect mask:   0
err:       Mip levels:    0 - 1
err:       Array layers:  0 - 1
err:     Image properties:
err:       Type:          VK_IMAGE_TYPE_2D
err:       Format:        VK_FORMAT_D16_UNORM
err:       Extent:        (6a,2,1)
err:       Mip levels:    1
err:       Array layers:  1
err:       Samples:       1
err:       Usage:         27
err:       Tiling:        VK_IMAGE_TILING_OPTIMAL

While on caae5d1 / master (68be040f), no log errors, but the installer's prompt appears as such:
Video: https://www.youtube.com/watch?v=UmaSjU4R_Lw

Log: 
[javaw_d3d9_b954ab8.log](https://github.com/doitsujin/dxvk/files/4581723/javaw_d3d9_b954ab8.log)
[javaw_d3d9_caae5d1.log](https://github.com/doitsujin/dxvk/files/4581724/javaw_d3d9_caae5d1.log)

Would you like an new issue be entered or is this ticket suitable for tracking?

**Comment by Blisto91** [comment]
@ZereoX Is this still a issue with newest dxvk?
If it's about partial representation then i guess it should still be.

**Comment by ZereoX** [comment]
> @ZereoX Is this still a issue with newest dxvk? If it's about partial representation then i guess it should still be. If that was a sure suspected cause ofc.

Yep. Still an issue.
