### ISSUE TITLE
[d3d9] Grand Theft Auto: San Andreas glitched, crashing

### ISSUE THREAD

**Issue by CuBeRJAN** [doitsujin/dxvk#1482]
Whenever I start the game, all text appears as white boxes, and when I try to start a game, it crashes.

### System information
- GPU:Intel HD
- Wine version:5.2-lutris 
- DXVK version:1.5.4

### Log files
Running /home/jan/.local/share/lutris/runners/wine/lutris-5.2-x86_64/bin/wine /home/jan/.lutrisprefix/grandtheftautosanandreas/drive_c/Program Files (x86)/Rockstar Games/GTA San Andreas/gta_sa-mod.exe
esync: up and running.
info:  Game: gta_sa-mod.exe
info:  DXVK: d9vk-0.40.1-croakacola-zero
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
INTEL-MESA: warning: Bay Trail Vulkan support is incomplete
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  Intel(R) HD Graphics (BYT):
info:    Driver: 20.0.0
info:    Vulkan: 1.2.131
info:    Memory Heap[0]: 
info:      Size: 1536 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x7
info:      Memory Type[1]: Property Flags = 0xb
info:  Process set as DPI aware
info:  Game: gta_sa-mod.exe
info:  DXVK: d9vk-0.40.1-croakacola-zero
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
INTEL-MESA: warning: Bay Trail Vulkan support is incomplete
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  Intel(R) HD Graphics (BYT):
info:    Driver: 20.0.0
info:    Vulkan: 1.2.131
info:    Memory Heap[0]: 
info:      Size: 1536 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x7
info:      Memory Type[1]: Property Flags = 0xb
info:  Process set as DPI aware
info:  Device properties:
info:    Device name:     : Intel(R) HD Graphics (BYT)
info:    Driver version   : 20.0.0
info:  Enabled device extensions:
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_host_query_reset
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 0
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 0
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 0
info:    shaderStorageImageExtendedFormats      : 1
info:    shaderStorageImageReadWithoutFormat    : 0
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 0
info:  VK_EXT_conditional_rendering
info:    conditionalRendering                   : 0
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 0
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 0
info:  DXVK: Read 9 valid state cache entries
info:  DXVK: Using 1 compiler threads
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1366
info:      - Height:             768
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: true
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           false
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  640x480
info:    Image count:  3
info:    Exclusive FS: 0
info:  D3D9: Setting display mode: 1366x768@60
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_DITHERENABLE
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_CLIPPING
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1366
info:      - Height:             768
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: true
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           false
info:  D3D9: Setting display mode: 1366x768@60
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  1366x768
info:    Image count:  4
info:    Exclusive FS: 0
wine: Unhandled page fault on write access to 00000050 at address 005DD97C (thread 0009), starting debugger...
Unhandled exception: page fault on write access to 0x00000050 in 32-bit code (0x005dd97c).

**Comment by CuBeRJAN** [comment]
OS is Ubuntu 19.10 btw

**Comment by WinterSnowfall** [comment]
AFAIK Bay Trail iGPUs only support Vulkan 1.0 and won't work with the latest versions of DXVK...

**Comment by doitsujin** [comment]
Yeah we don't really support Bay Trail. Would be interesting if this game works on newer GPUs though.

**Comment by ViNi-Arco** [comment]
Hello @CuBeRJAN, I compiled the DXVK in the latest version for you, before these commits:
https://github.com/doitsujin/dxvk/commit/bafcaa0c0725c690edc30a2a455353cddd42f64f
https://github.com/doitsujin/dxvk/commit/ce5143186085ccf7bd653c90dd81b7b058670f29

Download here:
https://drive.google.com/open?id=1N47-et38GKsMdYWeHQ97vQ9_fqo8wltW


If you continue to see an error, it is because your iGPU does not even support Vulkan 1.0

**Comment by mirh** [comment]
New versions of vulkan did not add any new hardware requirement, and there's no desktop gpu supporting the api in the first place that didn't get updated to 1.2. 
If that's lacking, it's simply a matter of an old driver. 

As for glitches, they may have been solved already with #1455 perhaps.

**Comment by WinterSnowfall** [comment]
> If that's lacking, it's simply a matter of an old driver.

The log files posted on this bug report were captured with Mesa 20.0, which implements Vulkan 1.2. The problem is not with hardware capabilities per se, but hardware age. Intel has not bothered to add Vulkan 1.1+ support on anything under Skylake (hence the warning message), and in terms of iGPUs you might as well say Ivy Bridge instead of Bay Trail.

Someone should really test this game on more recent hardware.

**Comment by ViNi-Arco** [comment]
> Intel has not bothered to add Vulkan 1.1+ support on anything under Skylake (hence the warning message)

Exactly!

> New versions of vulkan did not add any new hardware requirement, and there's no desktop gpu supporting the api in the first place that didn't get updated to 1.2.

More or less, the issue there is hardware, and the developer will decide to support it, in his case, even with a driver offering a newer version of Vulkan, Hardware does not support it.

**Comment by mirh** [comment]
Putting aside I actually see 1.1+ [implemented](https://vulkan.gpuinfo.org/displayreport.php?id=7904#extended), they are [still](https://phoronix.com/scan.php?page=news_item&px=Intel-Gen7-Compute-Cache-Boost) [working](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/3828) on it (and there's [no real](https://bugs.freedesktop.org/show_bug.cgi?id=105226#c2) "nogo")
Of course it is what it is for the moment, and there are no pretensions. But let's wait for OP to reply..

**Comment by TheComputerGuy96** [comment]
> Someone should really test this game on more recent hardware.
@WinterSnowfall No issues here (info in the screenshot):
![Screenshot from 2020-03-23 11-06-41](https://user-images.githubusercontent.com/19169000/77301279-1815ea00-6cf8-11ea-8817-fa6d6243a186.png)

And yes, I use Arch BTW :D

**Comment by HughJass** [comment]
GTA San Andreas runs fine on WINED3D even on a very old hardware. Remember to not disable the frame limiter, as the game logic and physics is tied to FPS, playing at more than 25 fps (yes, the game is stuck at 25 fps :( ) will break the game in many weird, sometimes subtle ways. Same for GTA3 and Vice City

**Comment by mirh** [comment]
This is OT, and it's only SA to be bugged to 25fps. Throw silentpatch at it, and you get 30 like the other games.
