### ISSUE TITLE
[d3d9] Dragon's Dogma Dark Arisen 21:9 menu aspect ratio fix request

### ISSUE THREAD

**Issue by wychuzord** [doitsujin/dxvk#1483]
Please be understanding. 
It's not technically a bug but I didn't see feature request option and I don't know if that's something that can be done through D9VK/DXVK so forgive me if I'm doing it wrong but Dragon's Dogma Dark Arisen (GoG but I'm sure that's how it works on Steam since steam version has a fix for it that probably doesn't work with Linux) has a broken 21:9 mode by default. It's not D9VK/DXVK's fault. The lower 1/3 of every menu screen is cut off and invisible in 21:9. Rest of the game renders fine, it's just the menus.

Can something be done about it through D9VK/DXVK? Maybe it's something easy to fix (stretched 16:9 menus would work good enough for me).
Again sorry if I'm asking impossible and its not the right place for that.

**Comment by Joshua-Ashton** [comment]
We can't really do anything specifically about the menus.

We can force the game to always be 16:9 if there is a problem though. But if the game has options for resolution I'd like to avoid adding a profile.

**Comment by wychuzord** [comment]
No no no, it has other resolution options available. I can play with 16:9 resolution stretched thicc mode or normal through virtual desktop or windowed mode. 
I made an omission: it's menus and UI but I guess that doesn't make a difference.
Thank you anyway. I guess I'll close the 'issue' then.
Hopefully Japanese will one day learn how to make proper PC ports.

**Comment by pchome** [comment]
@wychuzord 
FYI: on [https://www.pcgamingwiki.com/wiki](https://www.pcgamingwiki.com/wiki/Dragon%27s_Dogma:_Dark_Arisen#Video_settings) you usually can find game's WSGF status/rate and possible solution, if you want to force 21:9 aspect ratio.

I personally prefer Wine virtual desktop mode, because 21:9 don't work as expected in almost every case for me (FOV/Aspect/cutscenes/etc.).

**Comment by wychuzord** [comment]
I use wsgf directly. 
Curiously enough I was able to make Agnostic Dragon work when I ran the game through Proton 3.16 but camera was spazzing out and sound was just noise so it wasn't playable anyway.
