### ISSUE TITLE
[d3d9] black squares in dead space

### ISSUE THREAD

**Issue by soredake** [doitsujin/dxvk#1484]
Black squares in intro in dead space (steam version), https://github.com/ValveSoftware/Proton/issues/293#issuecomment-592952438

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
DO NOT use DXVK together with apitrace!

### Software information
Dead space, maximum settings, acrhlinux, aco enabled.

### System information
- GPU: RX 560
- Driver: X.Org Radeon RX 560 Series (POLARIS11, DRM 3.36.0, 5.5.6-17-tkg-pds, LLVM 9.0.1)
- Wine version: latest wine-tkg
- DXVK version: dxvk from git

### Apitrace file(s)
- https://mega.nz/#!MIAGgIKY!eRB1tJwK7KPijL8_Hkb_kf2K71L6zNsUiwTLoOa9PlQ

### Log files
- d3d9.log: [Dead Space_d3d9.log](https://github.com/doitsujin/dxvk/files/4270583/Dead.Space_d3d9.log)
- d3d11.log:
- dxgi.log:

**Comment by K0bin** [comment]
Does that also happen with ACO? I dont remember seeing that problem on Nvidia?

**Comment by soredake** [comment]
I tested with aco only.

**Comment by K0bin** [comment]
Ok, I thought LLVM because of that:
> Driver: X.Org Radeon RX 560 Series (POLARIS11, DRM 3.36.0, 5.5.6-17-tkg-pds, LLVM 9.0.1)

**Comment by Joshua-Ashton** [comment]
Should be fixed now.

**Comment by soredake** [comment]
Yes, fixed, thanks!
