### ISSUE TITLE
[d3d9] Mount & Blade Warband: Artifacts when enabling MSAA

### ISSUE THREAD

**Issue by ScarecrowDM** [doitsujin/dxvk#1486]
Hello.
Mount & Blade Warband exhibits artifacts when MSAA is enabled. It persists when disabled in the same playthrough, i need to quit and start again to get rid of them. Wine3D work as intended.

https://imgur.com/a/SWdvjeG

### Software information
Mount & Blade Warband (Steam, there is a demo also)
Arch btw
Mesa 20 + radv-git, tested with amdvlk-pro as well.

### System information
- GPU: Vega 56
- Driver: radv/aco + amdvlk-pro
- Wine version: Proton 5.0-3
- DXVK version: 1.5.5 (game is hanging for me with 1.5.4)

### Apitrace file(s)
- https://mega.nz/#!X3Yi1IJJ!ZVMVCHOT4I1i896xCGTfrkwI1pU_KN3EF2mc3xZ7OAE

### Log files
- d3d9.log: [mb_warband_d3d9.log](https://github.com/doitsujin/dxvk/files/4270742/mb_warband_d3d9.log)

**Comment by ivan89el** [comment]
This problem occurs in many games.

**Comment by Joshua-Ashton** [comment]
Fixed as of 457c0c30217993520262caa631e2c4ae59bbd16b
