### ISSUE TITLE
(1.0 Beta) 2020 Black Mesa UI Invisible 

### ISSUE THREAD

**Issue by Trippyskittles** [doitsujin/dxvk#1490]
Title as shown :)

**Comment by doitsujin** [comment]
Are you serious?

**Comment by Joshua-Ashton** [comment]
The game is using shared resources for the UI (D3D11 from QT -> D3D9 in Source) which is something we cannot support right now.

The game is also missing some synchronization for these shared resources given it flickers all the time for me on native DirectX on both AMD and Nvidia.

As a workaround you can use ``-useoldgameui`` which will also be much faster...

**Comment by Landgrafxiii** [comment]
Can you please send me what I need do with command useoldgameui. I have steam version Black Mesa, and I have some problem when I start game with Proton 5.0, my game have not menu, and I can't start the game.

**Comment by Joshua-Ashton** [comment]
As a launch argument in Steam.

**Comment by Landgrafxiii** [comment]
Joshua, thank you, but i still not sure, all i do correct. Could you look my screenshots?
![1223](https://user-images.githubusercontent.com/61966718/76332652-16b4ec80-630a-11ea-98c0-7de058068ca3.jpeg)
If you can see, this way do not halp me.
![Снимок экрана от 2020-03-10 20-00-13](https://user-images.githubusercontent.com/61966718/76332713-2c2a1680-630a-11ea-955e-22b4b02c8900.png)
May be you can any ways?
Thank you.

**Comment by aqxa1** [comment]
You need to prefix the option with %command%, which represents the Proton + game command. Like this:
`%command% -useoldgameui`

**Comment by Landgrafxiii** [comment]
Aqxa1, thank you, I will try this way today in the evening. And i am going to send about result as soon as I try this way.

**Comment by jerbear64** [comment]
The correct launch argument is `-oldgameui`.

**Comment by Landgrafxiii** [comment]
So it is very interesting, I think I will try all ways

**Comment by Landgrafxiii** [comment]
So, i tried different ways, and in my case i had good result when i used `%command% -oldgameui`. Anyway, thanks everyone for help. 
![123223](https://user-images.githubusercontent.com/61966718/76424202-5b4f8f00-63c1-11ea-873a-be0c40af537d.jpeg)
![Снимок экрана от 2020-03-11 17-39-23](https://user-images.githubusercontent.com/61966718/76424214-60144300-63c1-11ea-8a42-455a78a7abc5.png)

**Comment by yurakone** [comment]
https://youtu.be/mDa4XNHf0vY
Also issue with dynamic lighting, red lightning from any dynamic light source

**Comment by K0bin** [comment]
@yurakone Please open another issue for that and provide an apitrace.

**Comment by DistantThunder** [comment]
Hello, as always thank you for your work and time.

Is there any hope for this working some day? The old UI has a problem with high resolutions (doesn't scale) and the native port is still... well, we use Proton on this game for a reason after all.

**Comment by K0bin** [comment]
It's unlikely to work any time soon.

**Comment by S4DF1** [comment]
it does not help me can u creat an example but in.bat becose i did not buy it from steam

**Comment by S4DF1** [comment]
it does not help me can u creat an example but in.bat becose i did not buy it from steam

**Comment by S4DF1** [comment]
it does not help me can u creat an example but in.bat becose i did not buy it from steam

**Comment by K0bin** [comment]
We do not support piracy in any way. Go buy it on Steam.

**Comment by S4DF1** [comment]
sorry i'm poor

**Comment by S4DF1** [comment]
i already found it 
it was: 
`bms.exe %command% -oldgameui`

**Comment by doitsujin** [comment]
Closing before we have other "discussions" of this kind here.
