### ISSUE TITLE
[d3d9] Ultra Street Fighter IV: graphics corruption on South East Asia scenario

### ISSUE THREAD

**Issue by vinifmor** [doitsujin/dxvk#1492]
Hello,

I've found a out a strange graphics corruption just happening on the South East Asia scenario of Ultra Street Fighter IV. Below some pictures of what happens:

![sfiv_01](https://user-images.githubusercontent.com/4312414/75740589-ddb3c100-5ce6-11ea-9daa-6d145096196c.png)

![sfiv_02](https://user-images.githubusercontent.com/4312414/75740560-cd9be180-5ce6-11ea-94dc-7b9545d1daff.png)

Sometime also happens a blinking effect around the fighters. 

To reproduce:
1. Go to "Versus" > "Player vs CPU"
2. Choose a fighter and an opponent
3. Choose the South East Asia scenario
4. Play a little bit until the issue happens

These issues don't happen with Wine D3D.

### Software information
Game: Ultra Street Fighter IV
Steam ID: 45760

### System information
- GPU: Nvidia GTX 970 4 Gb
- Driver: Nvidia 440.59
- Wine version: Proton 5.0-3
- DXVK version: 1.5.0 > 1.5.5

### Apitrace file(s)
https://drive.google.com/open?id=1bIP6kygQhaerKGjcslw11wPia1OKt1bG

### Log files
- d3d9.log: [SSFIV_d3d9.tar.gz](https://github.com/doitsujin/dxvk/files/4279121/SSFIV_d3d9.tar.gz)
- proton log: [steam-45760.tar.gz](https://github.com/doitsujin/dxvk/files/4279126/steam-45760.tar.gz)

Thank you for this great project. If anything else is needed to reproduce the behavior, let me know.

**Comment by Joshua-Ashton** [comment]
Hm the trace renders fine on my end on both AMD and NVIDIA...

Any chance you'd be able to record a trace with DXVK so I can compare the two? Thanks. :)

**Comment by vinifmor** [comment]
Sure. Here the [dxvk trace](https://drive.google.com/open?id=1Os53vWxt_vN87yCPeOnJ6hQRZHBIA40J) and a [quick video](https://drive.google.com/open?id=11rjM4mjO9h3tcSK--9fsvV_koysQRF4C)

**Comment by Ahmed-E-86** [comment]
I have a different issue with this game, sometimes one of the character doesn't appear on the screen.

**Comment by vinifmor** [comment]
The issue is not happening anymore with the latest versions of DXVK/Proton/Nvidia drivers. Closing it.
