### ISSUE TITLE
Attempting to daisy-chain D3D8TO9 with DXVK in C&C Generals ZH on Win10

### ISSUE THREAD

**Issue by ghost** [doitsujin/dxvk#1498]
Hello

I got as far as I could yesterday to try daisy-chaining but it doesn't look like it'll work out of the box. I'm thinking I must have misunderstood this project, is this meant to be used only on Linux and Wine? The DXVK installation script seems to be meant only for Linux too.

I'm trying to get a better idea of the lag in C&C Generals that has been plaguing everyone for a long time, to be able to help with workaround/fix efforts. However various various profilers and debuggers these days don't support DX9 let alone DX8.1, with the exception of Intel GPA which supports DX9 and that's how I was able to use it so D3D8TO9 does work it for sure. 

In a way I may already be happy with just that one, so I might get all the things I need from it, but it kinda uses a legacy simple toolset compared to the modern one with later APIs. I'm just being stubborn as I kinda want this to work as an example and for my own enjoyment/challenge :)

----

**UPDATE1:**

I now got rid of the gentool and it's proxy DLL loading feature and tens of other combinations of namings and cleaned out all the experimentation, only placed D3D8TO9's dll as "d3d8.dll" and DXVK's 32-bit "d3d9.dll" into the Generals ZH root, for a long time I haven't seen any indication of it working but later in the evening I noticed a DXVK logfile "d3d9.log" so that's a good sign. 

> info:  Game: game.dat
> info:  DXVK: v1.5.5
> info:  Built-in extension providers:
> info:    Win32 WSI
> info:    OpenVR
> warn:  OpenVR: Failed to locate module
> info:  Enabled instance extensions:
> info:    VK_KHR_get_surface_capabilities2
> info:    VK_KHR_surface
> info:    VK_KHR_win32_surface
> warn:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
> info:  Radeon (TM) RX 480 Graphics:
> info:    Driver: 2.0.127
> info:    Vulkan: 1.2.131
> info:    Memory Heap[0]: 
> info:      Size: 7936 MiB
> info:      Flags: 0x3
> info:      Memory Type[0]: Property Flags = 0x1
> info:    Memory Heap[1]: 
> info:      Size: 12002 MiB
> info:      Flags: 0x0
> info:      Memory Type[1]: Property Flags = 0x6
> info:      Memory Type[3]: Property Flags = 0xe
> info:    Memory Heap[2]: 
> info:      Size: 256 MiB
> info:      Flags: 0x3
> info:      Memory Type[2]: Property Flags = 0x7
> info:  Process set as DPI aware
> info:  Device properties:
> info:    Device name:     : Radeon (TM) RX 480 Graphics
> info:    Driver version   : 2.0.127
> info:  Enabled device extensions:
> info:    VK_AMD_memory_overallocation_behavior
> info:    VK_AMD_shader_fragment_mask
> info:    VK_EXT_depth_clip_enable
> info:    VK_EXT_full_screen_exclusive
> info:    VK_EXT_host_query_reset
> info:    VK_EXT_memory_priority
> info:    VK_EXT_shader_demote_to_helper_invocation
> info:    VK_EXT_shader_stencil_export
> info:    VK_EXT_shader_viewport_index_layer
> info:    VK_EXT_transform_feedback
> info:    VK_EXT_vertex_attribute_divisor
> info:    VK_KHR_create_renderpass2
> info:    VK_KHR_depth_stencil_resolve
> info:    VK_KHR_draw_indirect_count
> info:    VK_KHR_driver_properties
> info:    VK_KHR_image_format_list
> info:    VK_KHR_sampler_mirror_clamp_to_edge
> info:    VK_KHR_swapchain
> info:  Device features:
> info:    robustBufferAccess                     : 1
> info:    fullDrawIndexUint32                    : 1
> info:    imageCubeArray                         : 1
> info:    independentBlend                       : 1
> info:    geometryShader                         : 1
> info:    tessellationShader                     : 0
> info:    sampleRateShading                      : 1
> info:    dualSrcBlend                           : 0
> info:    logicOp                                : 0
> info:    multiDrawIndirect                      : 0
> info:    drawIndirectFirstInstance              : 0
> info:    depthClamp                             : 1
> info:    depthBiasClamp                         : 1
> info:    fillModeNonSolid                       : 1
> info:    depthBounds                            : 1
> info:    multiViewport                          : 1
> info:    samplerAnisotropy                      : 1
> info:    textureCompressionBC                   : 1
> info:    occlusionQueryPrecise                  : 1
> info:    pipelineStatisticsQuery                : 1
> info:    vertexPipelineStoresAndAtomics         : 1
> info:    fragmentStoresAndAtomics               : 0
> info:    shaderImageGatherExtended              : 0
> info:    shaderStorageImageExtendedFormats      : 1
> info:    shaderStorageImageReadWithoutFormat    : 0
> info:    shaderStorageImageWriteWithoutFormat   : 1
> info:    shaderClipDistance                     : 1
> info:    shaderCullDistance                     : 1
> info:    shaderFloat64                          : 0
> info:    shaderInt64                            : 0
> info:    variableMultisampleRate                : 0
> info:  VK_EXT_conditional_rendering
> info:    conditionalRendering                   : 0
> info:  VK_EXT_depth_clip_enable
> info:    depthClipEnable                        : 1
> info:  VK_EXT_host_query_reset
> info:    hostQueryReset                         : 1
> info:  VK_EXT_memory_priority
> info:    memoryPriority                         : 1
> info:  VK_EXT_shader_demote_to_helper_invocation
> info:    shaderDemoteToHelperInvocation         : 1
> info:  VK_EXT_transform_feedback
> info:    transformFeedback                      : 0
> info:    geometryStreams                        : 0
> info:  VK_EXT_vertex_attribute_divisor
> info:    vertexAttributeInstanceRateDivisor     : 1
> info:    vertexAttributeInstanceRateZeroDivisor : 1
> info:  Queue families:
> info:    Graphics : 0
> info:    Transfer : 2
> info:  DXVK: Read 81 valid state cache entries
> info:  DXVK: Using 2 compiler threads
> info:  D3D9DeviceEx: Using extended constant set for software vertex processing.
> info:  D3D9DeviceEx::ResetSwapChain:
> info:    Requested Presentation Parameters
> info:      - Width:              2560
> info:      - Height:             1440
> info:      - Format:             D3D9Format::A8R8G8B8
> info:      - Auto Depth Stencil: true
> info:                  ^ Format: D3D9Format::D24S8
> info:      - Windowed:           true
> info:  Presenter: Actual swap chain properties:
> info:    Format:       VK_FORMAT_R8G8B8A8_UNORM
> info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
> info:    Buffer size:  2560x1440
> info:    Image count:  2
> info:    Exclusive FS: 0
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> warn:  ConvertFormat: Unknown format encountered: 65
> info:  Presenter: Actual swap chain properties:
> info:    Format:       VK_FORMAT_R8G8B8A8_UNORM
> info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
> info:    Buffer size:  2560x1440
> info:    Image count:  2
> info:    Exclusive FS: 0

Note: C&C Generals uses child process for the main engine executable called `game.dat` as other Westwood/EALA games at the time. But it must be started with `generals.exe` or else it won't boot.

AMD GPUPerfStudio still reports DX9 is active and won't work since it doesn't support DX9 anyway ... but then again it doesn't support Vulkan either what was I thinking, the thing is from 2015 with last update on 2016 somewhere.

Intel GPA also won't work now, it launches, doesn't crash, but won't work ... now I figure out it doesn't support Vulkan either, what in the hell was I thinking, how the heck did I miss that, because I got the latest version a week ago I thought it should have but yeah I must have mixed that news with RenderDoc being the one adding Vulkan support.

RenderDoc just won't work either, perhaps it's a RenderDoc problem and not DXVK.
RenderDoc is not a profiler so it will not help me as much but it would be great to make it run just to prove the point, perhaps it may be useful for other DXVK cases if this problem also affects other daisy-chained games. RenderDoc won't launch the game no matter what I try, it'll just crash the game and even one of it's own components. Lastly the only combination that worked the best so far was injecting it into game.dat which is launched by Thyme. (TheAssemblyArmada's project) It doesn't work but it doesn't crash, game runs normally, but no API is detected and can't do anything really so it's so far useless.

**Comment by altimumdelta** [comment]
Well looks like it's working all right ... but it doesn't raise the D3D level, it's still at D3D9 tho. DXVK may work differently than D3D8TO9. Perhaps what I need is something like D3D8TO11 or D3D9TO11 heh.

![GenZH_DX8TO9_DXVK_WorkingExample1](https://user-images.githubusercontent.com/48530820/76093606-8ac95a80-5fc1-11ea-936f-c5f206a62423.jpg)

**Comment by K0bin** [comment]
> Well looks like it's working all right ... but it doesn't raise the D3D level, it's still at D3D9. DXVK may work differently than D3D8TO9 and similar.

You're using D3D8to9 and DXVK as your D3D9 implementation. What exactly did you expect? DXVK gets D3D9 calls from the game.

About the performance: that only happens with DXVK, right?
If thats the case, please make an apitrace with that setting turned on and post it here.

**Comment by jp7677** [comment]
@altimumdelta unlike D3D8TO9, DXVK translates D3D9 directly to Vulkan. It does not first translates D3D9 to 10 or 11. So all is good if you see D3D9 in the HUD.

**Comment by WinterSnowfall** [comment]
@altimumdelta if for some reason you need to translate DX8 to DX11 (I'm not sure how much of a bump you need here), you can try [dgVoodoo 2](http://www.dege.freeweb.hu/). DXVK only translates DX9/10/11 directly to Vulkan, so I don't think it's what you're looking for.

**Comment by altimumdelta** [comment]
> About the performance: that only happens with DXVK, right?
> If thats the case, please make an apitrace with that setting turned on and post it here.

Oh sorry, no, the USA Patriot Missile Assist Datalink was lagging already and for a long long time, perhaps it did not lag on 2003 hardware/drivers/WinXP which I played on myself, it's been my fav RTS for a long time, I was deepely involved in modding and still get back to it every few months/years so I know a lot about it, but I don't think I can remember it not lagging there, or perhaps in the old days I didn't build such crazy defenses. 

I dug into it this time around with my past experience with such tools (which can be quite hard to come randomly across if you're not looking for them specifically, I never knew Intel GPA existed before last week)

All it took was setting NumBeams to zero and everything else still works in the logic behind the feature, except the "binary data stream" just doesn't get drawn:

> Object PatriotBinaryDataStream
>   ; *** ART Parameters ***
>   Draw = W3DLaserDraw ModuleTag_01
>     Texture = EXBinaryStream32.tga
>     NumBeams = 0                      ;Number of overlapping cylinders that make the beam. 1 beam will just use inner data. Current max: 10
>     InnerBeamWidth = 4                ;The total width of beam
>     InnerColor = R:0 G:255 B:0 A:180  ;The inside color of the laser (hot)
>     Tile = Yes                        ;The height of the texture will determine how many times to tile the texture to fit without scaling.
>     ScrollRate = -0.25                 ;Scrolls the texture offset this fast -- towards(-) away(+)
>     Segments = 20                     ;Number of segments -- more segments give smoother curve (but more joints) Current max: 20
>     ArcHeight = 30.0                  ;The height of the arc
>     SegmentOverlapRatio = 0.0000      ;This value overlaps(+) or separates(-) the segments by ratio
>     TilingScalar = 0.25                ;Stretches tiling if value > 1.0, otherwise shrinks it (1.0 is natural)
>  End
> 
>   KindOf = IMMOBILE
>   ClientUpdate = LaserUpdate ModuleTag_02
>     ;nothing
>   End
> 
>   ; A patriot uses this stream as an event triggered thing, not something turned on and off with a state.
>   Behavior = DeletionUpdate ModuleTag_03
>     MinLifetime = 600   ; min lifetime in msec
>     MaxLifetime = 600   ; max lifetime in msec
>   End
> End


The Patriot Assist feature is about other Patriot Missile batteries being able to fire out of their normal range (temporairly switches to a secondary weapon with bonus range) but they have to be withing the certain raidus of the Patriot that actually saw the target within it's normal range, so the others are assisting, and the more patriots you have the more green beams you have all over the freaking place.



It's a 30FPS game so that FPS right there is optimal (perhaps there's a 60FPS hack that I forgot but it affects game speed if modified)

**Comment by doitsujin** [comment]
RenderDoc works fine with DXVK fwiw, you just need to set the environment variable `ENABLE_VULKAN_RENDERDOC_CAPTURE=1` and **not** start the application it through the RenderDoc GUI.

**Comment by altimumdelta** [comment]
I have success!

![GenZH_DX8TO9_DXVK_AMD-RadeonGPUProfiler_WorkingExample](https://user-images.githubusercontent.com/48530820/76125040-43ac8b00-5ffc-11ea-846e-d13d4bc34fa4.png)

**Comment by altimumdelta** [comment]
> RenderDoc works fine with DXVK fwiw, you just need to set the environment variable `ENABLE_VULKAN_RENDERDOC_CAPTURE=1` and **not** start the application it through the RenderDoc GUI.

Yeah it crashes GenZH in all cases on boot, either generals.exe or game.dat crashes.

Whether the env variable set only in Windows (without RenderDoc open), or it's set with both RenderDoc and Windows, or only in Renderdoc. And all those combinations again with or without Capture Child Process.

The error is that renderdoc.dll isn't found in the process.

**Comment by K0bin** [comment]
I implemented the missing texture format.

**Comment by K0bin** [comment]
I assume it's fixed by implementing the missing texture format so I'm gonna close this issue.

If it's still broken, please either reopen or open a new issue.
