### ISSUE TITLE
Black Dragon Viewer does not render certain textures/models correctly

### ISSUE THREAD

**Issue by NodokaHanamura** [doitsujin/dxvk#1499]
Brief Description
-------------------------------
The Black Dragon Second Life Viewer is a specialized third party viewer or 'client' for the Second Life Massive Multiplayer Online Virtual World, mainly used for the creation of machinima, in-world screenshots and although not aimed toward such - general use, developed by NiranV Dean for Windows exclusively.

Black Dragon uses DirectX instead of the standard OpenGL renderer used with Second Life and other viewers, to my knowledge.

Issue
---------------------
The Black Dragon Viewer fails to render facial features on the Utilizator M3 Anime Head properly, and this issue may effect other models.

This includes the following:

- Eye textures do not render.
- Ears appear when they shouldn't be ( when blocked by other parts of the head (the face, etc)

Examples, including expected behavior from within the Native Firestorm Viewer are provided.

Reproduction
----------------
1. Log in.
2. Wear the M3 head
3. The bug will take place.

As far as I am aware, this behavior is not present within the native Windows environment.

![Selection_186](https://user-images.githubusercontent.com/19292481/76124191-28c02380-5fc8-11ea-96e0-a3f59f543e0d.png)

![Selection_188](https://user-images.githubusercontent.com/19292481/76124194-28c02380-5fc8-11ea-9202-192b0d324081.png)

![Selection_187](https://user-images.githubusercontent.com/19292481/76124193-28c02380-5fc8-11ea-8fc0-57506e65dc93.png)

**Comment by doitsujin** [comment]
Can you please **at least upload the DXVK log files** as requested in the issue template, and if possible, record an apitrace?

Please don't assume that we have access to every game ever made.

**Comment by NodokaHanamura** [comment]
Really? I was informed by another Linux SL user that Black Dragon uses Direct3D. I'll go ahead and close this report, my deepest apologies.
