### ISSUE TITLE
[dx9] Rome: Total War crashes on start

### ISSUE THREAD

**Issue by random2324** [doitsujin/dxvk#1501]
Just testing the game. In previous protons versions no prob but in newer ones gets D9VK enabled by default. So there is currently a crash happening in the beginning.

### System information
- GPU: Radeon RX Vega (VEGA10, DRM 3.35.0, 5.4.3-10-tkg-pds, LLVM 11.0.0) (0x687f)
- Driver: Mesa 20.0.0-devel (git-0d99ff54cc)
- Wine version: 5.3 staging
- DXVK version: git head

### Apitrace file(s)
As it works with wined3d, I dont think I can create one, or?

### Log files
No dxvk files created (0 Byte)

[steam-4760.log](https://github.com/doitsujin/dxvk/files/4303897/steam-4760.log)

I try to do my best if you need something else.

**Comment by Joshua-Ashton** [comment]
This game is d3d8.

**Comment by Joshua-Ashton** [comment]
Can you please try installing D3D8To9 in your prefix for the game and seeing if that fixes the problem?

**Comment by random2324** [comment]
[steam-4760.log](https://github.com/doitsujin/dxvk/files/4304985/steam-4760.log)
I tried, set d3d8.dll to native and put it into game dir. No dice.
From the log, it loads native d3d8.dll but still crashes in d3d9. I'm far from being an expert, but this looks strange.

**Comment by Joshua-Ashton** [comment]
I wasn't able to reproduce the crash locally on Windows. I'll try it on Proton tomorrow.

**Comment by random2324** [comment]
Im sorry. There seems to be a problem with the custom proton tkg version I used. Need to figure out what causes this. The game starts fine with d3d8to9 and DXVK fires up but hangs later at loading screen. (wined3d passes this part) Should I still let this open or close?
[steam-4760.log](https://github.com/doitsujin/dxvk/files/4307211/steam-4760.log)

**Comment by Joshua-Ashton** [comment]
Works on my machine 🐸 But I guess it can stay open until the problem is resolved.

**Comment by random2324** [comment]
OK, there is something wrong with my DXVK build. A precompiled DXVK release works but the same version compiled with tkg script fails. Also in another game, Titan Quest, my custom DXVK version crashes at start, somewhere in the entry points, so similar crash like Rome.

Also removing d3d8to9 dll let the game passes the loading screen. Looks like it has somewhere a problem. In the end no DXVK bug here, sorry for wasting your time.

**Comment by random2324** [comment]
In the end it was because of march=native cflags optimization. Something changed in the code or in the compiler toolchain which broke DXVK while it was actually working with that cflag for months before.
https://github.com/Tk-Glitch/PKGBUILDS/issues/515

Just letting you know, if someone else stumbles about this.
