### ISSUE TITLE
DXVK VR performance troubleshooting

### ISSUE THREAD

**Issue by jug007** [doitsujin/dxvk#1503]
Hello,

I have been troubleshooting the low VRChat performance for a bit and noticed a weird issue.
When running in desktop mode with DXVK performance is great on 1440p. We are talking >100fps in full worlds with mirrors and >300 fps in empty ones.
When running in vr mode however performance doesn't look so good. Changing the resolution has no impact whatsoever (as long as it doesn't exceed memory). Framerate is stuck between 60 and 70 fps. Unfortunately using actual VR doesn't work with DXVK on windows for me, so I cannot test the performance any more. These numbers are very similar to what I encounter on linux as well though.
It feels as if the framerate was capped by something, but it is fluctuating between 60 and 70 fps and VRChat doesn't limit the framerate itself in this scenario, SteamVR would either limit it to exactly 60 or to 120 fps, and Vsync is forced of in DXVK config. The nvidia hack is also turned off in the DXVK config.

I would be cool if we could troubleshoot this somehow.

### Software information
VRChat

### System information
- GPU: Nvidia GTX 1080
- Driver: 442.50 (Windows)

- d3d11.log: [VRChat_d3d11.log.txt](https://github.com/doitsujin/dxvk/files/4311868/VRChat_d3d11.log.txt)
- dxgi.log: [VRChat_dxgi.log](https://github.com/doitsujin/dxvk/files/4311852/VRChat_dxgi.log)

**Comment by doitsujin** [comment]
Note that VR requires everything to be rendered twice, so a **very** significant drop in CPU-bound performance is to be expected.

Also I don't think VRChat is the pinnacle of game optmization, so there's that.

**Comment by jug007** [comment]
Without DXVK, the framerate is at the constant frametarget of 144fps in the same scenario on vr.

**Comment by doitsujin** [comment]
While that's weird, I don't think there's much I can do to improve this. As mentioned, DXVK doesn't have much optimization headroom left, and it would be a miracle if managed to squeeze out even 5% out of it at this point.

**Comment by Tomcatt** [comment]
So there will not be any VR support then.

I think you have something great here.  Running your DXVK in windows for Elite looks good.  (In the end, I'll set up a gaming rig for Linux.)
