### ISSUE TITLE
[d3d9] Trine 2 - no text appears on the menu

### ISSUE THREAD

**Issue by Ahmed-E-86** [doitsujin/dxvk#1505]
No text appears on the menu of the game. It is like this issue that was fixed before >>> https://github.com/Joshua-Ashton/d9vk/issues/50

![Screenshot_20200311_182920](https://user-images.githubusercontent.com/29783425/76441848-b933a500-63c8-11ea-9e93-4ad640f2e5fd.png)

### Software information

![Screenshot_20200311_184340](https://user-images.githubusercontent.com/29783425/76441571-4f1b0000-63c8-11ea-9eeb-e5085d71de37.png)

### System information
- GPU: AMD Radeon HD 8750M
- Driver: Mesa 20.0.1
- Wine version:  5.3 - staging
- DXVK version: 1.5.5

### Log files
- d3d9.log:  [trine2_32bit_d3d9.log](https://github.com/doitsujin/dxvk/files/4319507/trine2_32bit_d3d9.log)

- dxgi.log: It is empty.

**Comment by Iglu47** [comment]
I have gog-version
WineD3D:
![WineD3D](https://user-images.githubusercontent.com/25866099/76478414-ac8b6d00-6419-11ea-9803-0fa69629eec1.png)
DXVK:
![DXVK](https://user-images.githubusercontent.com/25866099/76478423-b1502100-6419-11ea-9067-23d3c59df383.png)

- nvidia proprietary driver: 440.64; gtx nvidia 1080ti
- arch linux, liquorix-5.4.17
- wine-tkg-5.3.r14.g5213d551
- dxvk 1.5.5-14

**Comment by K0bin** [comment]
If it also happens with WineD3D, make sire you're using Microsofts d3dcompiler and d3dx9

**Comment by Iglu47** [comment]
@K0bin ty, i found that d3dx9_38=n need for this game
![trine2_wined3d_v3](https://user-images.githubusercontent.com/25866099/76480098-d1361380-641e-11ea-895e-06efd6b1a07d.png)

**Comment by Ahmed-E-86** [comment]
Yeah, that fixed it.
