### ISSUE TITLE
[d3d9] Rocket Leauge uses wined3d instead of DXVK

### ISSUE THREAD

**Issue by Ahmed-E-86** [doitsujin/dxvk#1506]
Rocket Leauge uses wined3d instead of DXVK. I didn't do anything to force the game using wined3d, it just happens automatically.

### System information
- GPU: AMD Radeon HD 8750M
- Driver: Mesa 20.0.1
- Wine version: 5.3 - staging
- DXVK version: 1.5.5

**Comment by Joshua-Ashton** [comment]
Rocket League is DX11 now.

**Comment by doitsujin** [comment]
You're doing something wrong then. No wine logs or anything -> can't help you.

**Comment by Ahmed-E-86** [comment]
> You're doing something wrong then. No wine logs or anything -> can't help you.

I am sorry about that, here is a wine log for this game if you are interested: 
[RocketLeague.txt](https://github.com/doitsujin/dxvk/files/4345970/RocketLeague.txt)

The same issue happens with another DX11 game (Gauntlet Slayer Edition), here is a wine log for the game:
[Gauntlet.txt](https://github.com/doitsujin/dxvk/files/4345979/Gauntlet.txt)

Other games run just fine with DXVK, but these 2 games can't be run using DXVK for some unknown reason to me.
