### ISSUE TITLE
Yomawari: Midnight Shadows crashes instantly

### ISSUE THREAD

**Issue by sat3ll** [doitsujin/dxvk#1507]
The game shows a black window then crashes (quits).

This issue exists in all but the most recent Proton versions. 
Before DXVK was merged/integrated with Proton, the game would crash (using WINED3D).
After DXVK being enabled by default, it would still crash in the same manner.
But, with Proton 5.0-4, the game now works if forced with WINED3D. (although it crashes with DXVK).

A more detailed report/history of the issue can be found here: https://github.com/ValveSoftware/Proton/issues/2157

### Software information
[Yomawari: Midnight Shadows / 深夜廻](https://store.steampowered.com/app/625980/Yomawari_Midnight_Shadows/)

### System information
- GPU: AMD Fury X
- Driver/LLVM version: Mesa 19.3.3 / LLVM 9.0.0
- Wine version: Proton 5.0-4 / wine-5.0-481-g0295175
- DXVK version: Proton 5.0-4 / v1.5.5-21-g3d52ab36a

### Apitrace file(s)
[yomawari2.zip](https://github.com/doitsujin/dxvk/files/4324181/yomawari2.zip)
Apitrace made under Windows, with nvidia gpu.

### Log files
Note: These logs are generated with the game in a broken state/crashing.
- d3d10.log: 0 byte file
- d3d11.log: [yomawari2_d3d11.log](https://github.com/doitsujin/dxvk/files/4324260/yomawari2_d3d11.log)
- proton log: [steam-625980.log](https://github.com/doitsujin/dxvk/files/4324257/steam-625980.log)

Edit:
- Forcing WINED3D proton log: [steam-625980.log](https://github.com/doitsujin/dxvk/files/4324297/steam-625980.log)

**Comment by doitsujin** [comment]
I'm aware. Unfortunately the apitrace isn't very useful since replaying it crashes inside apitrace code, I'll have to wait until I get access to the game to dig any further.
