### ISSUE TITLE
[d3d9] DoDonPachi Resurrection (464450) - Title crashes to desktop after launch.

### ISSUE THREAD

**Issue by ZereoX** [doitsujin/dxvk#1508]
### Description:
This was reported by a user on the Proton Issue Tracker: https://github.com/ValveSoftware/Proton/issues/3629

Attempting to launch DoDonPachi: Resurrection will result in a black screen followed by a crash to desktop. 

This occurs on both Proton 5.0-1 (and up) and Windows using DXVK 1.5.5 or master (14946c59). All point releases since 1.5 were also tested and the issue is present there as well.

Please let me know if any additional information is required or if additional testing is needed.

### Software information
DoDonPachi Resurrection ([464450](https://store.steampowered.com/app/464450))

### System information
- OS: Ubuntu 18.04 / Windows 10 Pro 1909
- GPU: Radeon RX 580 / Nvidia GeForce GTX 970
- Driver: 20.1\~git2003071930.0103f0\~oibaf\~b / 440.64-0ubuntu0\~0.18.04.1
- Wine version: Proton 5.0-4
- DXVK version: 1.5.5 / Master (14946c59)

### Apitrace file(s)
- https://drive.google.com/open?id=1DqhHNL2t0pC9N1e4lH82SDCrNl6nYKfC

### Log files
- d3d9.log: [default_d3d9.log](https://github.com/doitsujin/dxvk/files/4324803/default_d3d9.log)

### Tested froggi.es builds:
master - 14946c59 (❌)
1.5.4 - 2435c63 (❌)
1.5.3 - 6a5d472 (❌)
1.5.2 - e242d7f (❌)
1.5.1 - 4308d9b (❌)
1.5 - 3cdae3a (❌)

**Comment by ryester27** [comment]
I see on ProtonDB that someone was able to get it working with Proton 5.0-1, but didn't specify if they used the PROTON_USE_WINED3D variable. I can give it a try myself at the end of the day (I believe I own this).

Can you upload your Proton log, which contains the wine debug output?

**Comment by Joshua-Ashton** [comment]
Should be fixed now!

**Comment by ZereoX** [comment]
Thanks. I've confirmed the issue is resolved on master.
