### ISSUE TITLE
[Textures DXVK] Devil May Cry 5 - Low res textures & Flickering

### ISSUE THREAD

**Issue by DocTdb** [doitsujin/dxvk#1509]
Hi,
Got a lot of low res textures (screenshots attached) and some flickering in DMC5 with Textures Quality on Ultra, it seems to be a lot better when switching to Medium quality. Tried both LLVM and Aco. Gpu : 5700XT.

`Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] driver: amdgpu  v: kernel  Display: x11 server: X.Org 1.20.7 driver: amdgpu FAILED: ati unloaded: modesetting,radeon  resolution: 1920x1080~60Hz, 1920x1080~60Hz  OpenGL: renderer: AMD NAVI10 (DRM 3.36.0 5.6.0-2-MANJARO LLVM 9.0.1) v: 4.6 Mesa 20.0.1`

Medium quality 

![MediumSetting](https://user-images.githubusercontent.com/54248720/76654137-9b9e4100-656a-11ea-9e72-87507cd44b07.jpg)

Ultra Setting

![UltraSetting](https://user-images.githubusercontent.com/54248720/76654182-af49a780-656a-11ea-8e50-085b62b7c828.jpg)

I've tried rolling back to mesa 19.3.4, rolling back to 5.4 kernel, tried different version of DXVK & Proton and the result is always the same.
What's bugging me is the Vram consumed, ain't it a little low for ultra textures ? I've tried different areas of the game and it barely go above 2.7Gb. Odd...

Don't know if it's DXVK or Mesa related... Just ask if you need some more infos.

**Comment by doitsujin** [comment]
I'm aware of this issue and have already spent a lot of time investigating it. Unfortunately, this isn't just a simple rendering bug, but *something* causes the game itself to unload high-resolution textures.

I can keep this bug open, but it's highly unlikely to ever get fixed, and I'm not sure if it is actually a DXVK bug.

**Comment by doitsujin** [comment]
Actually, vkd3d has the exact same bug. Likely not a DXVK issue.
![Bildschirmfoto-1208](https://user-images.githubusercontent.com/25567304/76658447-744c7180-6574-11ea-89d3-b7b23e5dea8f.png)

**Comment by DocTdb** [comment]
Ok, thanks for your input. Closing the issue.
