### ISSUE TITLE
World of Tanks VK_ERROR_MEMORY_MAP_FAILED

### ISSUE THREAD

**Issue by magist3r** [doitsujin/dxvk#1513]
After one or two battles World of Tanks crashes during load of the hangar after battle. I created fresh wineprefix, but it didn't help.

Here is an error from log:
```
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Memory allocation failed
err:     Size:      134217728
err:     Alignment: 16
err:     Mem flags: 0x6
err:     Mem types: 0xf
err:   Heap 0: 3488 MB allocated, 2280 MB used, 3634 MB allocated (driver), 7402 MB budget (driver), 7936 MB total
err:   Heap 1: 96 MB allocated, 47 MB used, 96 MB allocated (driver), 98 MB budget (driver), 256 MB total
err:   Heap 2: 448 MB allocated, 413 MB used, 486 MB allocated (driver), 8018 MB budget (driver), 8192 MB total
err:   DxvkMemoryAllocator: Memory allocation failed
```

### Software information
World of Tanks 1.8.0

### System information
- GPU: AMD RX 580
- Driver: Mesa 20.0.1 (LLVM 9.0.1)
- Wine version: 5.4-staging
- DXVK version: 1.5.5 (tested 1.4.6 too)

### Apitrace file(s)
- Couldn't get apitrace - WoT doesn't work with wined3d.

### Log files
[worldoftanks_d3d11.log](https://github.com/doitsujin/dxvk/files/4344265/worldoftanks_d3d11.log)
[worldoftanks_dxgi.log](https://github.com/doitsujin/dxvk/files/4344267/worldoftanks_dxgi.log)

**Comment by doitsujin** [comment]
*sigh* #1318

**Comment by Mixaill** [comment]
@magist3r  use `win64/Worldoftanks.exe` to run WoT.
