### ISSUE TITLE
[d3d9] Performance regression in GPU-bound situations on AMD GPUs

### ISSUE THREAD

**Issue by ThisNameIsntTaken** [doitsujin/dxvk#1514]
As of f6b26b3, performance in GPU-bound situations seems to have dropped by about 30-40% in all the games I've tested so far. None of them had any rendering issues. I've also tried reproducing this problem on my laptop's MX130 GPU, but the issue doesn't seem to present there.

### Software information
So far I've tested TrackMania United Forever, NFS Most Wanted 2005, Borderlands 2, GTA IV and Vindictus (well, this one does have a rendering issue, but it's not related and it's already reported on the D9VK bug tracker).

### System information
- GPU: RX 580 4GB
- Driver: Mesa Git on Linux, Radeon Software 20.2.2 on Windows
- Wine version: 5.4-TkG
- DXVK version: 3697583

### Apitrace file(s)
- [Same trace](https://mega.nz/#!W5U10SbC!TME6zUcLuTYBTyKPu_s6sBDkRnFPSSYs919K7Frd6BY) that can be found in Joshua-Ashton/d9vk#303

### Log files
- [Vindictus_d3d9.log](https://github.com/doitsujin/dxvk/files/4355111/Vindictus_d3d9.log)

**Comment by doitsujin** [comment]
Looks like a typo that should be fixed by the above PR.

**Comment by ThisNameIsntTaken** [comment]
Yep, that fixed it. Thanks!
Should I wait until it gets merged before I close the issue?

**Comment by doitsujin** [comment]
This should get closed automatically once the PR gets merged.
