### ISSUE TITLE
[d3d9] Hitman: Blood Money (6860) - Title crashes to desktop when switching resolutions.

### ISSUE THREAD

**Issue by ZereoX** [doitsujin/dxvk#1517]
### Description:
This was reported by a user on the Proton Issue Tracker: https://github.com/ValveSoftware/Proton/issues/142#issuecomment-589237998

In **_Hitman: Blood Money_** (6860) switching to any resolution within the game's options menu will result in a crash to desktop. The game's window becomes blank (black screen), a resolution change occurs (mode switch is observed on Windows), and then the window closes. This occurs on both Proton 5.0-4 and Windows using DXVK 1.5.5 or master (021c593a). Title does not crash when changing resolutions on WineD3D or Native Windows D3D.

Please let me know if any additional information is required or if additional testing is needed.

#### Notes:
- The resolution can still be change using the game's configuration tool (Steam's alternate launch option).
- On Windows 10, if the game is not installed in the default steam library, 'Steam.dll' must be manually copied into the game folder for it to launch (The game is unable to locate Steam otherwise).

### Software information
Hitman: Blood Money (6860)

### System information
OS: Ubuntu 18.04 / Windows 10 Pro 1909
GPU: Radeon RX 580 / Nvidia GeForce GTX 970
Driver: 20.1\~git2003190730.3c0371\~oibaf\~e / 440.64-0ubuntu0~0.18.04.2
Wine version: Proton 5.0-4
DXVK version: 1.5.5 / Master (021c593a)

### Apitrace file(s)
- https://drive.google.com/open?id=1uRxPWvWvPXxqRutcngXIu2cwTmuQUwMs

### Log files
d3d9.log: [HitmanBloodMoney_d3d9.log](https://github.com/doitsujin/dxvk/files/4356087/HitmanBloodMoney_d3d9.log)

### Tested froggi.es builds:
master - 021c593a (❌)
1.5.4 - 2435c63 (❌)
1.5.3 - 6a5d472 (❌)
1.5.2 - e242d7f (❌)
1.5.1 - 4308d9b (❌)
1.5 - 3cdae3a (❌)

**Comment by Joshua-Ashton** [comment]
> On Windows 10, if the game is not installed in the default steam library, 'Steam.dll' must be manually copied into the game folder for it to launch (The game is unable to locate Steam otherwise).

Very weird because Steam puts a `Steam.dll` in your library folder when you make it, did you delete that or is it just not finding that one?

**Comment by ZereoX** [comment]
> Very weird because Steam puts a `Steam.dll` in your library folder when you make it, did you delete that or is it just not finding that one?

The title failed on a fresh install so I googled the error and found a bunch of threads with people mentioning this as a workaround ([Link #1](https://steamcommunity.com/app/6860/discussions/0/364041776198680064/), [Link #2](https://steamcommunity.com/app/6860/discussions/0/558746089175806657/?l=french)). 

It's possible something is up with my library folder, but I assumed it was a common problem with the game and proceeded with reproducing the issue.

**Comment by jhlkek** [comment]
I experience the same issue with the GOG version.

**Comment by DaRkL3AD3R** [comment]
I experience this in many D3D9 games from the mid 00s. Or there will be some other variant of issue on resolution change like loss of exclusive fullscreen.

**Comment by Joshua-Ashton** [comment]
Should be fixed now.

**Comment by ZereoX** [comment]
Thanks. I've confirmed the issue is resolved on master.
