### ISSUE TITLE
Trails of Cold Steel 2 fails to load into game after title

### ISSUE THREAD

**Issue by EuanFH** [doitsujin/dxvk#1518]
### Expected
Game gets into menu successfully after load a save the game has a black screen while it loads the game. Black screen fades out and game loads in.

### What Happens
Game gets into menu successfully after load a save the game has a black screen while it loads the game. Black screen doesn't disappear and the game doesn't load. 

### Software information
Trails of Cold Steel 2

### System information
- GPU: AMD VEGA 64
- Driver: amdgpu
- Wine version & DXVK version: proton-ge-custom 5.4
### Apitrace file(s)
- [ed8_2_PC_US.trace](https://drive.google.com/file/d/1oOWWcr0F5adCLLRPP2YPFYRAUyx0FUUJ/view?usp=sharing) from windows 10

### proton logs
[steam-748490.log](https://drive.google.com/open?id=125OQHi4NbFG_PXKPygJHkQ0K0502aAP7)

If any logs are missing that you need just ask. I was struggling finding information to get the log files needed from proton.
Not sure if this is a DXVK issue but any help pointing me in the right direction would be appreciated.

**Comment by doitsujin** [comment]
I've completed the game with DXVK and it still works completely fine on my end.

**Comment by EuanFH** [comment]
Thank you so much I thought I had all the dependencies needed but it turns out I didn't. Your second edit fixed the problem. Been trying all day to get it working.
It was my bad on the log i was trying different things and sent you to wrong one.
Its cool your a fan of the series been meaning to catch up now the third is coming out next week.

Sorry for wasting your time man. Thanks for all the work you do.
