### ISSUE TITLE
[d3d9] GTA IV - Broken rendering since the last commit

### ISSUE THREAD

**Issue by ThisNameIsntTaken** [doitsujin/dxvk#1519]
As of 1150121, the game looks like this:
![Screenshot_20200320_114951](https://user-images.githubusercontent.com/44706448/77158088-e5bf7f00-6aa2-11ea-9673-d0b341d961a9.png)
With the previous commit, the game looks normal:
![Screenshot_20200320_115815](https://user-images.githubusercontent.com/44706448/77158178-11426980-6aa3-11ea-9194-0c745f04ca2b.png)

I'm well aware the game has some issues right now, but the problem is reproducible using an old trace from Joshua-Ashton/d9vk#99.

### Software information
Grand Theft Auto IV, latest version that has been released yesterday.

### System information
- GPU: RX 580 4GB
- Driver: Mesa Git + ACO
- Wine version: Proton 5.4-TkG
- DXVK version: 1150121

### Apitrace file(s)
- [GTAIV_trace.tar.xz](https://mega.nz/#!DEFnDQLI!G0fkUFzyZSvxbImQbB8xsSFNTX4bt_IWPoOXfbUalG8)

### Log files
- [GTAIV_d3d9.log](https://github.com/doitsujin/dxvk/files/4359165/GTAIV_d3d9.log)
- [GTAIV_dxgi.log](https://github.com/doitsujin/dxvk/files/4359166/GTAIV_dxgi.log)

**Comment by doitsujin** [comment]
I guess the real culprit is f6b26b302d9c0c9760b47b881ce6667f8f021424.

@Joshua-Ashton can we revert this? The whole depth-stencil hazard thing is clearly not working, and was only masked by the fact that we were using `GENERAL` layout for all depth buffers.
