### ISSUE TITLE
Fails to work running nativly on windows :- d3d10core/d3d10 dll errors

### ISSUE THREAD

**Issue by ABagOfPotato** [doitsujin/dxvk#152]
Might just be me being dumb, but should we be compiling from source when testing on Windows? As the release readme says to copy the dll's over to an applications folder and run, however doing so results in a dll error with d3d10core, if a copy of either dxvk's dll's is renamed to said dll it errors on d3d10 which again seems to be bypassed if the same is done, however it still results in a crash as youd probably imagine.

Result is the same on every application I've ran. Including WoW, Witcher 3, Deliverance etc. 

Have seen one or two people testing in Windows and wanted to give it a go, but cant figure out how thats possible unless I get everything to compile in VS and find out whats going on.

Run on Win10 with an RX460, using one driver version behind current.

**Comment by Mixaill** [comment]
Direct3D 10 games currently not supported.

**Comment by ABagOfPotato** [comment]
I can give that a try as I did have afterburner on at the time, however I tried Kingdom Come deliverance which as far as I know is also a DX11 game which also gives the DX10 error, and WoW was also in DX11 mode. Same with Witcher 3, despite it being a DX11 game it still errors with a DX10 dll.

I’ll check again with more DX11 titles in the morning, but so far every DX11 title ive tried has given said same error.

Will post more detailed info in the morning, but it appeared that what it was referencing had been moved to a different dll in wine, at least that’s what I got from a google search.

Apologies for the lack of info, just packed up for the night and will take a more detailed look tomorrow.

**Comment by thirdeyefunction** [comment]
I just tested Witcher 3 with DXVK on Windows and it works fine, with around the same performance as under Wine on Linux. This is with a 980ti and Windows 10. The AMD card could be the difference, there might be a compatibility issue there.

**Comment by ssorgatem** [comment]
AMDVLK (AMD's cross-platform Vulkan driver, used on Windows) is problematic and currently unsupported. 

Last "release" won't work with DXVK on wine at least for some games; I haven't tried it on Windows.
Older "releases" had the exact same bugs on Linux+wine+DXVK than on Windows+DXVK.

**Comment by ssorgatem** [comment]
See this: https://github.com/doitsujin/dxvk/issues/148

**Comment by doitsujin** [comment]
@ABagOfPotato Do you have any overlay software running in the background (RTSS etc.), *anything* that might interfere?

DXVK is obviously not made for Windows, although it *should* work unless a game explicitly requires Windows 10. I recorded [this](https://www.youtube.com/watch?v=FJkVL4JX0jg) video on Windows 10 with AMD's ReLive a while ago (I think that was on one of the 18.2.x drivers), and while that driver certainly has issues with DXVK, I cannot reproduce any DLL errors.

**Comment by SveSop** [comment]
@ABagOfPotato Even tho a game - like World of Warcraft - is in DX11 mode, it does seem to call DX10 functions. This means that sadly DXVK cannot be used, unless DX10 functions gets included.

Not sure if its just "leftover code" that makes this, or that some random function is still using DX10 in those games, but in Windows this is rather problem free to do, and games are made for windows. Wine manages to load this, but DXVK does not have any DX10 functions to it afaik.

Maybe wow at the next xpac where DX9 will be dropped, and DX12 implemented will have some cleanup of the code, and be DX11+12 only? Dunno

**Comment by ABagOfPotato** [comment]
A bit embarrising but it was probably just me forgetting to close Afterburner! I still can't get things to run, however I can at least get past the previous DLL errors after a driver update and without any overlays running.

In regards to WoW yes its using some DX10 calls by the looks of things.

`info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Radeon(TM) RX 460 Graphics:
info:    Driver: 2.0.14
info:    Vulkan: 1.0.65
warn:  DxgiAdapter: DXGI_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
err:   DxgiAdapter::CheckInterfaceSupport: No D3D10 support
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Radeon(TM) RX 460 Graphics:
info:    Driver: 2.0.14
info:    Vulkan: 1.0.65
warn:  DxgiAdapter: DXGI_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
err:   DxgiAdapter::CheckInterfaceSupport: No D3D10 support
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Radeon(TM) RX 460 Graphics:
info:    Driver: 2.0.14
info:    Vulkan: 1.0.65
warn:  DxgiAdapter: DXGI_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
err:   DxgiAdapter::CheckInterfaceSupport: No D3D10 support
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Radeon(TM) RX 460 Graphics:
info:    Driver: 2.0.14
info:    Vulkan: 1.0.65
warn:  DxgiAdapter: DXGI_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  Enabled device extensions:
info:    VK_AMD_rasterization_order
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
warn:  DxgiFactory::QueryInterface: Unknown interface query
`
Then fails to launch. As for Heroes of the storm, it trys to launch, I even once saw the background screen and have seen the cursor several times, but it cannot launch properly.

As for Kindgom Come deliverence it now launches but crashes when finished loading the main menu with the following in the log files.

`err:   DxgiOutput::FindClosestMatchingMode: Not implemented
warn:  DxgiSwapChain: Display mode changes not implemented
info:  DxgiPresenter: Recreating swap chain: 
  Format:       VK_FORMAT_R8G8B8A8_UNORM
  Present mode: VK_PRESENT_MODE_FIFO_KHR
  Buffer size:  1920x1080`

`err:   D3D11DeviceContext::RestoreState: Not implemented`

Also of note is that COD:WW2 won't launch due to it believeing its not being run on a new enough OS, likley due to the following.

`err:   CreateDXGIFactory: Requested version of IDXGIFactory not supported
`

Sorry for being a little off topic but I thought Id do a rundown of how it worked after my silly error before.
