### ISSUE TITLE
runtime text relocations /usr/lib/dxvk/d3d{9,10,11}.dll.so

### ISSUE THREAD

**Issue by stefson** [doitsujin/dxvk#1522]
hey there, I do get this quality assurance warning from my distros package manager when I compile dxvk from source: 

```

 * QA Notice: The following files contain runtime text relocations
 *  Text relocations force the dynamic linker to perform extra
 *  work at startup, waste system resources, and may pose a security
 *  risk.  On some architectures, the code may not even function
 *  properly, if at all.
 *  For more information, see:
 * 
 *    https://wiki.gentoo.org/wiki/Hardened/HOWTO_locate_and_fix_textrels
 * 
 *  Please include the following list of files in your report:
 * TEXTREL usr/lib/dxvk/d3d9.dll.so
 * TEXTREL usr/lib/dxvk/d3d10_1.dll.so
 * TEXTREL usr/lib/dxvk/d3d10.dll.so
 * TEXTREL usr/lib/dxvk/d3d10core.dll.so
 * TEXTREL usr/lib/dxvk/d3d11.dll.so
 * TEXTREL usr/lib/dxvk/dxgi.dll.so

```

wine version: wine-5.2
dxvk version: 1.5.5 and latest master

full build log: [build.log.zip](https://github.com/doitsujin/dxvk/files/4362585/build.log.zip)

**Comment by doitsujin** [comment]
I guess I should make it clearer that I don't really care about winelib builds and will eventually drop support.

It's also not clear at all from the given instructions what the actual problem is and how to fix this in the source code, so I don't plan to address this (non-)issue.
