### ISSUE TITLE
SECTOR 40 The Soviet Legacy VK_ERROR_DEVICE_LOST

### ISSUE THREAD

**Issue by mozo78** [doitsujin/dxvk#1523]
The hame fails with `VK_ERROR_DEVICE_LOST` at the main menu and freezes. I tried with Wine only and it works but you know - it's slow as hell.

### Software information
SECTOR 40 The Soviet Legacy

### System information
- GPU: 1080Ti
- Driver: 440.66.03/440.64
- Wine version: 5.4
- DXVK version: 1.5.5/1.6

### Apitrace file(s)
- Put a link here
https://my.pcloud.com/publink/show?code=XZDl7MkZKM3KWlyoQFRWIl0wtGz3R8sx9PU7
### Log files
- d3d11.log:
[SECTOR40-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/4363198/SECTOR40-Win64-Shipping_d3d11.log)

- dxgi.log:
[SECTOR40-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/4363199/SECTOR40-Win64-Shipping_dxgi.log)

**Comment by doitsujin** [comment]
The apitrace replays fine here and shows no validation errors. Does replaying it trigger the error for you?

**Comment by mozo78** [comment]
Sorry but I don't know how to replay the apitrace :) Thousands of game are working but I get this error for the first time.

dmesg is huge, do you want it?

**Comment by mozo78** [comment]
Ah, almost forgot - I tried the game on Arch and Linux Mint 19.3 with pretty the same result. The problem is not from the OS.

**Comment by mozo78** [comment]
I try to replay the apitrace an it gives me this:
https://i.imgur.com/0T2yTgY.png
What should I check?

**Comment by doitsujin** [comment]
You're supposed to run `d3dretrace.exe xyz.trace` to replay it.

> dmesg is huge, do you want it?

Just `dmesg | tail -n 20` immediately after the hang should suffice.

**Comment by mozo78** [comment]
Thank you, here it is:
https://pastebin.com/R4NSnrzL
After minute or two, the game crashes with:
https://i.imgur.com/GUhU6DG.png

> You're supposed to run `d3dretrace.exe xyz.trace` to replay it.

It seems I can't find d3dretrace.exe in the apitrace archive. I use this:
https://people.freedesktop.org/~jrfonseca/apitrace/

**Comment by mozo78** [comment]
Hello,
I managed to replay the apitrace. It's the same what happens with the game. The game loads and we can see the main menu but we can't use it for it's frozen. No item from the main menu can be chosen or used. If I wait for a couple af minutes, it crashes with:
https://i.imgur.com/GUhU6DG.png

**Comment by mozo78** [comment]
It crosses my mind the problem may be NVIDIA related hence you can't reproduce it. I tried to spoof AMD video card but the game fails with the same error.

**Comment by mozo78** [comment]
Tried with nvapi and nvapi64 - no dice.

**Comment by mozo78** [comment]
Should I wait or I can close the issue?

**Comment by mozo78** [comment]
Roger, you are not interested.
