### ISSUE TITLE
[Suggestion] dxvk hud only.

### ISSUE THREAD

**Issue by JunioJsv** [doitsujin/dxvk#1526]
Is there any possibility that the dxvk hud becomes a separate project that aims to monitor games that use opengl, vulkan and directx? Without having to lose performance with api translations, I wanted to have the possibility to use the dxvk hud separately. I bet the windows community would trade the msi afterbuner for the hud from dxvk without a second thought.

**Comment by Joshua-Ashton** [comment]
Use MangoHUD.

**Comment by JunioJsv** [comment]
but mangohub is only for linux users, and why am i using windows

**Comment by mozo78** [comment]
Just use Linux.

**Comment by JunioJsv** [comment]
I'm almost back to my natural habitat

**Comment by doitsujin** [comment]
No.
