### ISSUE TITLE
[d3d9] Crysis → I can't load the second chapter, it hangs on the loading screen

### ISSUE THREAD

**Issue by NerosTie** [doitsujin/dxvk#1528]
Title

Only with d3d9, it's not an issue with d3d10.

### Software information
Steam command: 
`PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 %command% -dx9`

### System information
- GPU: Nvidia GT 730M
- Driver: Nvidia Vulkan 440.66.03-1
- Wine version: Proton 5.0-5
- DXVK version: 1.6.0

### Apitrace file(s)
https://mega.nz/#!bmhBkSRT!krJY2j6o7DOuXQwWMrlOApw-ldJFfjdIx2fKigAic3k

### Log files
[steam-17300_d9vk.log](https://github.com/doitsujin/dxvk/files/4366389/steam-17300_d9vk.log)
[steam-17300_wined3d.log](https://github.com/doitsujin/dxvk/files/4366390/steam-17300_wined3d.log)

**Comment by Joshua-Ashton** [comment]
Can you re-test this in master? I have issues with running the Crysis on Steam. :-/

**Comment by NerosTie** [comment]
Tested with 1227 and the issue is gone :)
