### ISSUE TITLE
[d3d9] Team Fortress 2: Rocket trails are different

### ISSUE THREAD

**Issue by HunterCZ122** [doitsujin/dxvk#1529]
### Software information
Team Fortress 2, max settings
Rocket trails are really weird looking in DXVK.
This maybe applies to other particles too (like Demoman's bombs).
I uploaded some videos on YT to see difference:
https://youtu.be/HiQNmm0y1Ik - Native DX9
https://youtu.be/az4b3fPPEeo - DXVK

### System information
- GPU: NVIDIA GeForce GTX 1660 Ti
- Driver: 442.74 (Windows)
- DXVK version: v1.6

### Apitrace file(s)
- https://drive.google.com/file/d/1PPUKz6kx9tG4WycQ4JfP0imJ2uIQiKmh/view?usp=sharing

### Log files
- d3d9.log: [hl2_d3d9.log](https://github.com/doitsujin/dxvk/files/4366580/hl2_d3d9.log)

**Comment by Joshua-Ashton** [comment]
This only happens when the vendor id is 10de.

**Comment by Joshua-Ashton** [comment]
Closed as of 457c0c30217993520262caa631e2c4ae59bbd16b
