### ISSUE TITLE
(enhancement) Release DXVK on 2x 3.5" floppy disks

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#1532]
The title was shameless clickbait (or perhaps gibberish for younger folk), but now that I've got your attention I'm going to argue my case.

Since dlls are (usually) highly compressible, why not use XZ Utils for packaging releases?

Here are some comparisons with **DXVK 1.6** on compression:
* `tar -czvf dxvk-1.6.tar.gz dxvk-1.6`
`time (real):  0m1,655s`
`size: 7708662`

* `tar -cJvf dxvk-1.6.tar.xz dxvk-1.6`
`time (real): 0m10,913s`
`size: 2861040`

... and on decompression:
* `tar -xzvf dxvk-1.6.tar.gz`
`time (real): 0m0,220s`

* `tar -xJvf dxvk-1.6.tar.xz`
`time (real): 0m0,367s`

The xz package size is only 37.1% of the gz, and the difference in decompression time is negligible.

This enhancement request was brought to you by:

>            _     _
>           (')-=-(')
>         __(   V   )__
>        / _/'-----'\_ \
>     ___\\ \\     // //___
>     >____)/_\---/_\(____< 
>     
>    The highly efficient packaging frogs consortium

**Comment by Joshua-Ashton** [comment]
How does zstd compare?

**Comment by WinterSnowfall** [comment]
> How does zstd compare?

It's tuned for speed by default:

* `tar -I zstd -cvf dxvk-1.6.tar.zst dxvk-1.6`
`time (real): 0m0,378s`
`size: 7693867`

* `tar -I zstd -xvf dxvk-1.6.tar.zst`
`time (real): 0m0,122s`

... but doesn't make the two floppy disk mark even on max compression:

* `tar -I 'zstd --ultra -22' -cvf dxvk-1.6.tar.zst dxvk-1.6`
`time (real): 0m18,922s`
`size: 3173229`

* `tar -I zstd -xvf dxvk-1.6.tar.zst`
`time (real): 0m0,131s`

But I assume you're pulling the consortium's frog legs, since zstd is not (yet) widely available or recognized by the average user.

I'll close this, since the seeds of high compression rates have been planted in the right spots, come rain or drought. The frogs made me do it, I swear.

Carry on with the stellar work :wink:
