### ISSUE TITLE
WoW crashes with ACCESS_VIOLATION > nvidia 440.58.02

### ISSUE THREAD

**Issue by OneOfOne** [doitsujin/dxvk#1534]
Random crashes in wow, can be between 2 minutes to 20-30 minutes with any nvidia drivers newer than 440.58.02.

### Software information
World Of Warcraft

### System information
- GPU: Nvidia RTX 2080
- Driver: 440.66.04
- Wine version: wine-5.4.r3.gcd7d77fe ( TkG Staging Esync Fsync Vkd3d )
- DXVK version: 1.6 and 1.5.x

The game works perfectly fine with vkd3d/d3d12, also downgrading the driver makes it run fine.

**Comment by OneOfOne** [comment]
![Screenshot_20200328_013621](https://user-images.githubusercontent.com/1080443/77817028-c2de2d80-7095-11ea-981d-9349207b0386.png)

**Comment by doitsujin** [comment]
Logs?

**Comment by cookiEoverdose** [comment]
This is very very likely a driver issue, just do not use beta drivers to play. I had crashes with 440.66.x on loading screens or ALT+TAB very frequently as well. Latest Long Lived Branch Version 440.64 works fine.

**Comment by OneOfOne** [comment]
Rebuilding dxvk with a custom mingw (tkg's) fixed the issue, the binary version still crashes.
