### ISSUE TITLE
LA_Noire_The_VR_Case_Files [722230] only black in HMD - desktop window works

### ISSUE THREAD

**Issue by frostworx** [doitsujin/dxvk#1538]
When trying to play the VR game LA_Noire_The_VR_Case_Files (steamid 722230)
the game renders only in the desktop window, but stays black in the hmd (valve index). the headset and knuckles are recognized correctly (game window shows that moving your head controls the view, and knuckles do work), only the hmd stays black. maybe related to Rockstar Launcher overlay.

### Software information
LA_Noire_The_VR_Case_Files
https://store.steampowered.com/app/722230/LA_Noire_The_VR_Case_Files/
default settings clean wineprefix, proton 5.0-5

### System information
- GPU: GeForce RTX 2080
- Driver: 440.64.0
- Wine version: proton 5.0-5 -> wine-5.0-484-g26aac31
- DXVK version:  proton 5.0-5 ->  DXVK: v1.5.5-21-g3d52ab36a

### Apitrace file(s)
I placed the apitrace dlls d3d11.dll, dxgi.dll and dxgitrace.dll in both the game directory
and in rockstar Launcher directories Program Files/Rockstar Games/Social Club and
Program Files/Rockstar Games/Launch but no trace file was generated. PROTON_USE_WINED3D to disable dxvk didn't help as well. would be glad to upload a trace if I knew how to create one.

### Log files
LANoireVR_dxvk_config.log
Launcher_d3d10.log
SocialClubHelper_d3d11.log
SocialClubHelper_d3d9.log
are 0 sized

[LANoireVR_d3d11.log](https://github.com/doitsujin/dxvk/files/4398772/LANoireVR_d3d11.log)
[Launcher_d3d11.log](https://github.com/doitsujin/dxvk/files/4398773/Launcher_d3d11.log)

steam-722230.log (PROTON_LOG=1 %command% )
has an endless loop with
fixme:vrclient:ivrcompositor_submit_dxvk Unhandled flags 0x8.

[steam-722230.log](https://github.com/doitsujin/dxvk/files/4398787/steam-722230.log)

place tell me if there's anything else I can do to help fixing this.
should I open also a Valve/Proton bug?

**Comment by frostworx** [comment]
I used the dlls mentioned here
https://www.reddit.com/r/linux_gaming/comments/98seei/how_to_record_an_apitrace_for_dxvk/e4ifeia/
which created a 634mb trace (zipped still ~ 500mb)
before splitting/uploading garbage, is that trace helpful or do I have to create one with PROTON_USE_WINED3D=1 %command%

**Comment by frostworx** [comment]
me again, sorry for the noise!
found https://github.com/doitsujin/dxvk/issues/1388#issuecomment-580451910
so I assume PROTON_USE_WINED3D=1 would be required for a useful trace. unfortunately with that var the game simply gets stuck with a block window on the desktop and doesn't trace anything. maybe because vrclient:ivrcompositor_submit_dxvk isn't implemented without dxvk?
attached is at least a zipped "PROTON_LOG=1 PROTON_USE_WINED3D=1 %command%" log
created while trying to get the trace. I hope it helps
[steam-722230.log.zip](https://github.com/doitsujin/dxvk/files/4398885/steam-722230.log.zip)

**Comment by doitsujin** [comment]
That sounds like a problem in Proton's VR bridge, not something that can be fixed inside DXVK.

**Comment by frostworx** [comment]
thanks for the time and the reply! wasn't sure about that, because of the vrclient:ivrcompositor_submit_dxvk reference. *opening a proton bug then*

**Comment by frostworx** [comment]
*closing here* thanks for the time again! take care, doitsujin!

**Comment by frostworx** [comment]
just to understand this correctly:
the warning message 
"warn:  DxbcCompiler: Unsupported custom data block: DxbcCustomDataClass::Opaque"
which is logged permanently while the game is running (with the black screen) suggests that he game is not drawn, because opacity is not implemented (probably the rockstar game launcher overlay messes up things here).
a quick&dirty finds this enum entry:
src/dxbc/dxbc_names.cpp:      ENUM_NAME(DxbcCustomDataClass::Opaque);
so I'm not sure why it is complaining that "DxbcCustomDataClass::Opaque" is a "Unsupported custom data block"
or does it mean that a "Unsupported custom data block" is delivered via "DxbcCustomDataClass::Opaque" (which comes from broken proton vr bridge)?
