### ISSUE TITLE
[d3d9] Trails From Zero: Screen Flickering During Battles in Certain Areas

### ISSUE THREAD

**Issue by RobertTheSable** [doitsujin/dxvk#1540]
When fighting enemies in Stargazer's Tower, the screen flickers a lot, causing fights to be virtually unplayable.

[Video of the issue here if it's useful (possible seizure warning due to the screen flicker)](https://www.youtube.com/watch?v=IwhTalCWCqw)

The issue only seems to occur in Stargazer's Tower, though I haven't finished the game yet so there may be other affected areas I haven't reached.

The issue does not occur with WineD3D

### Software information
The Legend of Heroes: Trails From Zero / Zero no Kiseki

Using the DLSite digital version with the [Geofront translation patch](https://geofront.esterior.net/downloads/). Can't confirm if it occurs in the unpatched game or not.

Installed following [these instructions](https://www.reddit.com/r/Falcom/comments/fiw6ol/trails_from_zero_geofront_translation_out_now/fkjuxrg/), plus amstream and quartz installed via winetricks to get cutscenes to work.

### System information
- GPU: AMD Radeon RX 480
- Driver: 19.2.8 
- Wine version: 5.5
- DXVK version: 1.6

### Apitrace file(s)
- https://www.dropbox.com/s/j454kurbulyqbc5/ED_ZERO.trace.tar.gz?dl=1

### Log files
[ED_ZERO_d3d9.log](https://github.com/doitsujin/dxvk/files/4400841/ED_ZERO_d3d9.log)

**Comment by doitsujin** [comment]
I can't reproduce the problem by replaying your trace; does it trigger the issue on your end?

If not, might be worth recording another trace with DXVK **enabled** so that we can look at any potential differences between the two. Also, maybe try a more recent Mesa version, 19.2 is a bit on the old side when it comes to D3D9 in DXVK.

**Comment by RobertTheSable** [comment]
I tried replaying the trace on my end (I assume "wine *path to apitrace.exe* replay ED_ZERO.trace" in the same prefix is the correct command), but didn't see the issue. No difference replaying a trace with DXVK enabled. 

I did notice this warning was in the ED_ZERO_d3d9.log file but not in the d3dretrace_d3d9.log file, though I don't know if it's useful:
warn:  D3D9InterfaceEx::QueryInterface: Unknown interface query
warn:  02177241-69fc-400c-8ff1-93a44df6861d

For the Mesa version, it's just what comes default on my distro(Kubuntu Eoan), and I'm not sure what the recommended method for getting a newer Mesa driver is.

**Comment by RobertTheSable** [comment]
I tried again with Mesa drives updated to 20.0.99. Still occurs when I  run the game, still doesn't show up when I replay the trace.

Here's the trace file all the same in case it's useful: https://www.dropbox.com/s/iyyfztrxg0uslim/ED_ZERO.trace.2.tar.gz?dl=1

**Comment by doitsujin** [comment]
Ye, doesn't trigger. Not much we can do then; doesn't really help that the game is not available outside Japan.

**Comment by Joshua-Ashton** [comment]
Do you experience the problem in Trails in the Sky? I own that game in the series but not this one.

**Comment by RobertTheSable** [comment]
I haven't experienced it in any of the Trails in the Sky games (including SC and 3rd). But I didn't play those games with DXVK. And since this only occurs in a specific area in Zero, I don't know that similar situations would appear in those games. 

I'll investigate later today to see if I can identify more areas that are affected, or what prefix settings might cause it.

**Comment by Joshua-Ashton** [comment]
Can you enable the HUD and tell me if you see it when it flickers? I remember on Intel there was some bug that caused blank frames to be presented somehow.

Validation layer output would also be useful.

If that doesn't yield anything I might have to get the game, but for that I need to find where to get it. Is it on GOG/Steam/...?

**Comment by RobertTheSable** [comment]
> Can you enable the HUD and tell me if you see it when it flickers? I remember on Intel there was some bug that caused blank frames to be presented somehow. Maybe there's something similar here.
> 
> Validation layer output would also be useful.
> 
> If that doesn't yield anything I might have to get the game, but for that I need to find where to get it. Is it on GOG/Steam/...?

The issue doesn't appear to happen in the unpatched game (tested by removing the DINPUT8.dll the translation patch uses). But I don't see then why the issue wouldn't also occur with wined3d.

What info do you need from the HUD? I can't tell what's supposed to be important there.

For the validation layer - not 100% what  I need to do to enable that. I installed the package andd ran wine with `WINEDEBUG=-all VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation`, but I didn't notice any significant differences in the console output. I'll attach it anyway in case it's helpful. 
[vl.log](https://github.com/doitsujin/dxvk/files/4410825/vl.log)

For buying the game, the easiest option is DLSite: https://www.reddit.com/r/Falcom/comments/7jee3m/how_to_legally_buy_zero_no_kiseki_trails_to_zero/

I included a link to the TL patch and instructions on what workarounds are needed to install it in Wine in the original report.

**Comment by zany130** [comment]
this apparently was fixed in 1.9 as I no longer get this issue. going back to 1.8 on lutris causes this issue to come back so I guess it's been fixed
