### ISSUE TITLE
Wrong Driver-Version in HUD

### ISSUE THREAD

**Issue by evilch3n** [doitsujin/dxvk#1543]
Hi iam wondering where does the dxvk_hud grab the Driver-Versionnumber from, because my dxvk_hud tells me iam using 20.0.2 and my CoreCtrl says iam on 20.1.0.

Now iam a little confused if ive goofed my setup somehow or that one of them is just reporting a wrong version.

### Software information
Path of Exile, dxvk_hud=full

### System information
- GPU: AMD 5700 XT
- Driver: mesa-devel 20.1.0 
- Wine version: Proton 5.0.5
- DXVK version: 1.6

Anymore stuff i can put into this for help? (Iam not a very experienced linux user... yet..! :) )

**Comment by doitsujin** [comment]
DXVK displays the version of your Vulkan driver. If it shows 20.0.2, you are using 20.0.2.

**Comment by evilch3n** [comment]
thanks for the respond, i thought it would take an older mesa version or something!
