### ISSUE TITLE
far mod requires DxgiAdapter::RegisterVideoMemoryBudgetChangeNotificationEvent

### ISSUE THREAD

**Issue by soredake** [doitsujin/dxvk#1544]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Reports with no log files will be ignored.**

### Software information
Nier Automata, [far mod](https://steamcommunity.com/groups/SpecialK_Mods/discussions/3/1334600128973500691/), proton

### System information
- GPU: rx 560
- Driver: Mesa 20.0.3
- Wine version: proton-tkg latest
- DXVK version: 1.6

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
- d3d11.log: [NieRAutomata_d3d11.log](https://github.com/doitsujin/dxvk/files/4421399/NieRAutomata_d3d11.log)
- dxgi.log: [NieRAutomata_dxgi.log](https://github.com/doitsujin/dxvk/files/4421400/NieRAutomata_dxgi.log)

logs from FAR mod:
[crash.log](https://github.com/doitsujin/dxvk/files/4421409/crash.log)
[dinput8.log](https://github.com/doitsujin/dxvk/files/4421410/dinput8.log)
[modules.log](https://github.com/doitsujin/dxvk/files/4421411/modules.log)
[steam_api.log](https://github.com/doitsujin/dxvk/files/4421412/steam_api.log)

related pr https://source.winehq.org/patches/data/174998

**Comment by doitsujin** [comment]
You can use wine's DXGI implementation with DXVK. I'm not sure if this is worth implementing on our end given that it is poorly documented and a **lot** of work.

**Comment by soredake** [comment]
Sadly these changes still not merged https://github.com/wine-mirror/wine/blob/master/dlls/dxgi/adapter.c#L349-L354

**Comment by doitsujin** [comment]
You can compile wine yourself. That's certainly going to be faster than me spending the next couple of days to figure out how exactly this function is supposed to even work.

**Comment by doitsujin** [comment]
I think one of the main problems is going to be that DXVK's memory management doesn't work at all like memory management works on Windows. It is certainly possible to impement this, but it will behave differently from Windows and will almost certainly lead to unexpected behaviour.

**Comment by soredake** [comment]
Ok, i'll ask tkg to rebase this patch.

**Comment by doitsujin** [comment]
Ok, apparently I misunderstood what this method is supposed to do and it's actually a lot simpler than expected. No idea if FAR works, but I guess it's implemented now.

**Comment by soredake** [comment]
@doitsujin thanks, it goes forward, even displays some ui, but still crashes after seconds
![Screenshot_20200403_101348](https://user-images.githubusercontent.com/5204968/78334192-00f6b800-7594-11ea-9fb0-c03b25830ba0.png)
```
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  b18b10ce-2649-405a-870f-95f777d4313a
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  d0223b96-bf7a-43fd-92bd-a43b0d82b9eb
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
```
dxvk+lutris+far logs:
[NieRAutomata.tar.gz](https://github.com/doitsujin/dxvk/files/4425550/NieRAutomata.tar.gz)

**Comment by popsUlfr** [comment]
This is interesting. Have you seen the guide by MiyacoGBF ? 

https://gist.github.com/MiyacoGBF/6fd49ae4a73a9a7f4d13c488bff2da77

I haven't had any luck myself making it work in-game though. But the FAR GUI displays and is usable in the main menu at least.

**Comment by soredake** [comment]
Awesome, it works for me even in-game 
![Screenshot_20200403_122517](https://user-images.githubusercontent.com/5204968/78346105-3b1d8500-75a7-11ea-87e4-d8a1cebb9282.png)

**Comment by soredake** [comment]
https://www.reddit.com/r/SteamPlay/comments/fu5dy3/far_mod_now_works_with_latest_wine/

**Comment by soredake** [comment]
note: i tested with dxvk dxgi with this commit https://github.com/doitsujin/dxvk/commit/079cda1c0ce225be3db68a39383de47904e67cfd
