### ISSUE TITLE
[d3d9] commit 904d3e6 breaks Guild Wars 2

### ISSUE THREAD

**Issue by Berobad** [doitsujin/dxvk#1546]
Commit 904d3e6 breaks Guild Wars 2

![gw2_nod3d9](https://user-images.githubusercontent.com/10475553/78314121-4a75e180-7559-11ea-9658-64c1822bfc53.png)

the log isn't really helpful, it seems that aside from loading the dll, nothing is really done:

```
info:  Game: gw2-64.exe
info:  DXVK: v1.6-12-g904d3e6c
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
```

**Comment by Joshua-Ashton** [comment]
Hi, can you give us more information on how you're using/building DXVK?

Are you using https://git.froggi.es/doitsujin/dxvk/-/jobs builds, or are you building it yourself?

If you're building it yourself, can you let me know what version of MinGW etc you are using?

**Comment by Berobad** [comment]
selfbuild with mingw gcc 9.3.0

```
    meson dxvk "build/x64" \
        --cross-file dxvk/build-win64.txt \
        --prefix "/usr/share/dxvk/x64" \
        --bindir "" --libdir "" \
        --buildtype "release" \
        --strip \
        -D enable_tests=false
    ninja -C "build/x64"
```

**Comment by Berobad** [comment]
Building it with MinGW gcc 9.2.0 does fix it, so it's a problem with 9.3.0

**Comment by Iglu47** [comment]
game: gw2-64.exe build:103099

![gw2-screen](https://user-images.githubusercontent.com/25866099/78406848-34752900-760c-11ea-9c81-36bea5f40595.png)

- nvidia proprietary driver: 440.64; gtx nvidia 1080ti
- arch linux, liquorix-5.5.13
- https://github.com/wine-staging/wine-staging/commit/f9d1798edb5aea67db49ba4663ca7d7568ef0e56
- dxvk 1.6.r17 bbe681d9caa9ace6a51a11f7b3c74f556aac4199

<details><summary>some build output</summary>
<p>

```Meson
The Meson build system
Version: 0.54.0
Source dir: /home/i47/pr-wine/dxvk-git/src/dxvk
Build dir: /home/i47/pr-wine/dxvk-git/src/build/x64
Build type: cross build
Project name: dxvk
Project version: v1.6
C compiler for the build machine: cc (gcc 9.3.0 "cc (Arch Linux 9.3.0-1) 9.3.0")
C linker for the build machine: cc ld.bfd 2.34
C++ compiler for the build machine: c++ (gcc 9.3.0 "c++ (Arch Linux 9.3.0-1) 9.3.0")
C++ linker for the build machine: c++ ld.bfd 2.34
C compiler for the host machine: x86_64-w64-mingw32-gcc (gcc 9.3.0 "x86_64-w64-mingw32-gcc (Arch Linux 9.3.0-1) 9.3.0")
C linker for the host machine: x86_64-w64-mingw32-gcc ld.bfd 2.34
C++ compiler for the host machine: x86_64-w64-mingw32-g++ (gcc 9.3.0 "x86_64-w64-mingw32-g++ (Arch Linux 9.3.0-1) 9.3.0")
C++ linker for the host machine: x86_64-w64-mingw32-g++ ld.bfd 2.34
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Checking if "winelib check" compiles: NO 
Program x86_64-w64-mingw32-windres found: YES (/usr/bin/x86_64-w64-mingw32-windres)
Library vulkan-1 found: YES
Library d3d9 found: YES
Library d3d11 found: YES
Library dxgi found: YES
Library d3dcompiler_43 found: YES
Library d3dcompiler_47 found: YES
Program glslangValidator found: YES (/usr/bin/glslangValidator)
Run-time dependency threads found: YES
Dependency threads found: YES unknown (cached)
Build targets in project: 13
```

</p>
</details>

**Comment by Berobad** [comment]
Had the same problem with the package build on other machines with 9.3.0, but I think I forgot to enable dwarf2, when I built 9.3.0 on those machines. 
(currently recompiling 9.3.0 with dwarf2)

**Comment by Berobad** [comment]
Yes, on mingw 9.3.0 with dwarf2 enabled it works, so dwarf2 seems to be necessary now.
