### ISSUE TITLE
Saints Row 4 broke since driver 440.66.02

### ISSUE THREAD

**Issue by NikoBellicRU** [doitsujin/dxvk#1549]
I dont know if this a problem on amd too but on nvidia this game keeps breaking from time to time, the trees are all black, sometimes no floor or buildings, i posted a video:
https://www.youtube.com/watch?v=RxN_uWjtP1g&feature=youtu.be

GPU:GTX 670
Driver:440.48.02
Wine version: Proton 5.0 (also tried GE and TKG with same results)
DXVK version: 1.6

[steam-206420.log](https://github.com/doitsujin/dxvk/files/4427064/steam-206420.log)

Also the game crashes if i minimize, try to load a new save game or if i get near the bugged trees

**Comment by doitsujin** [comment]
Please try 440.66.08. You're not only using a beta driver, you're using an *outdated* beta driver.

That said, SR4 has a ton of bugs on its own, I've given up on working around them all at this point.

**Comment by NikoBellicRU** [comment]
Im using the latest 440.66.08 but it broke since 440.66.02, also i looked into the log and it has alot of this: D3D11: CopySubresourceRegion: Incompatible texel size, to be honest don't know what it means but doesn't seem right

**Comment by doitsujin** [comment]
It means that the game is broken as fuck. That isn't a DXVK issue, it doesn't even work properly *on Windows*.

Anyway, sounds very much like a driver regression rather than a DXVK problem if it only happens with the beta driver.

**Comment by NikoBellicRU** [comment]
Yeah it's clearly a driver problem but isn't there any workaround? This game had a issue with the Z-fighting fixed on 1.5.5 and it was also a driver regression

**Comment by doitsujin** [comment]
This doesn't look like Z fighting to me. The `d3d11.invariantPosition = True` to work around that is already being used.

Actually, looking at your log:
> info:  DXVK: v1.6-9-g16c3c487-async

Please **do not use** unofficial, patched DXVK builds to report issues.

**Comment by NikoBellicRU** [comment]
I was testing all proton versions and the official proton has the same problem, changed this command in dxvk.conf " d3d11.enableRtOutputNanFixup = True "and it fixed the glowing trees and doesn't crash anymore when i'm close to them but the texture is still bugged

![Screenshot_20200403_150330](https://user-images.githubusercontent.com/50124155/78369145-a160d280-75bc-11ea-9440-72c306880fb7.png)

**Comment by NikoBellicRU** [comment]
Ok so i tried the game again with the latest beta driver (440.66.12) and now the game is still broken but when use the " d3d11.enableRtOutputNanFixup = True " the game is perfect, no crashes or bugs so far and also not sure if was some fix from dxvk or the driver

![Screenshot from 2020-05-05 03-52-49](https://user-images.githubusercontent.com/50124155/81031444-2f61fe80-8e84-11ea-88ef-786258008b71.png)

**Comment by Blisto91** [comment]
Mkay. I've played a bit with my 960 + latest driver and dxvk and haven't noticed any visual issues so i think we can just assume that isn't a problem anymore.

What does it say in a proton log when it hangs?

**Comment by NikoBellicRU** [comment]
On my end visually all looks good i just really need to play in offline mode to stop the stuttering but even then it crashes some times right away and others takes longer, i had a look at the log and i dont see anything obvious but i'm not that into this stuff.

Have a look
https://www.mediafire.com/file/23t72uiauhai1c7/steam-206420.log/file

**Comment by Blisto91** [comment]
I'm not seeing anything obvious either.
Try seeing if disabling fsync and esync helps
```
PROTON_NO_FSYNC=1 PROTON_NO_ESYNC=1 %command%
```

**Comment by NikoBellicRU** [comment]
Ok great with esync / fsync off it seems to be working fine no hangs so far and i played quite a bit, dont really know if will crash later on but so far is looking good.

**Comment by Blisto91** [comment]
It's possible that turning both esync and fsync off reduces the performance of the game.
If it works you can try only turning off fsync and see if that still seems to hold water.
```
PROTON_NO_FSYNC=1 %command%
```

**Comment by Blisto91** [comment]
Ye i see it has issues from what i guess is windows users. So the game itself might just be a bit unstable.
https://steamcommunity.com/app/206420/discussions/0/6202034451742431973/
https://steamcommunity.com/app/206420/discussions/0/3419937087358150285/
https://steamcommunity.com/app/206420/discussions/0/6202034451745223192/

**Comment by Blisto91** [comment]
Could you as a last attempt try and bypass dxvk? The performance might be bad but just as a experiment.
```
PROTON_USE_WINED3D=1 %command%
```

**Comment by NikoBellicRU** [comment]
I tried wined3d today and i get like 5-10fps right at the start all slow motion really unplayable and even worse when i start moving.

**Comment by Blisto91** [comment]
My gut instict is that the hangs above could be the game itself. Or at least not a dxvk issue.

**Comment by pchome** [comment]
@Blisto91 
> Mkay. I've played a bit with my 960 + latest driver and dxvk and haven't noticed any visual issues so i think we can just assume that isn't a problem anymore.

Everything seem ok, except some glitches around characters near light sources.
![Screenshot_20220723_141818](https://user-images.githubusercontent.com/10661854/180603035-b0818fe1-aad3-4672-be0a-a63c433bb72d.png)
Looks ok when near shadows.
![Screenshot_20220723_141903](https://user-images.githubusercontent.com/10661854/180603034-f2a6c3c1-0cd9-4017-8361-613dd42cff70.png)

I played to the city and noticed no other issues.
515.57 + dxvk master branch

**Comment by Blisto91** [comment]
Could maybe be a game issue. :thinking:  I see the same when i use wined3d
