### ISSUE TITLE
Every game in my system doesnt detect the Dedicated GPU

### ISSUE THREAD

**Issue by nesper8** [doitsujin/dxvk#1551]
DRI_PRIME=1 is non-existent in many game dialog screen 

And if I try to override with the radeon icd this happens 

Running /home/nep/.local/share/lutris/runners/wine/lutris-5.5-2-x86_64/bin/wine /home/nep/Games/Deus Ex - Human Revolution/CE/dxhr.exe -
Initial process has started with pid 3344
Game is considered started.
esync: up and running.
info:  Game: dxhr.exe
info:  DXVK: v1.6
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Required Vulkan extension VK_KHR_surface not supported
terminate called after throwing an instance of 'dxvk::DxvkError'
Initial process has exited.
Game is considered exited.
All monitored processes have exited.
Exit with returncode 768

This happens whenever I try to open any game with the radeon_icd lutris detected
Hybrid setup with Intel HD 520 & AMD R5 M330

**Comment by doitsujin** [comment]
You need to use the AMDGPU kernel module to get Vulkan support on your GCN 1.0 GPU, see https://github.com/ValveSoftware/Proton/wiki/For-AMD-users-having-issues-with-non-OpenGL-games.

**Comment by nesper8** [comment]
Thanks that worked
