### ISSUE TITLE
[d3d11] Just Cause 3 flickering terrain

### ISSUE THREAD

**Issue by BlazeKl** [doitsujin/dxvk#1553]
Just Cause 3 has some flickering terrain, changing settings in game makes no difference. This also happen on both LLVM and ACO compilers

The trace (recorded on WIN10) replays with some HUD errors for me but it reproduces the terrain bug

### Software information
Just Cause 3, max settings

### System information
- GPU: AMD RX 470 4GB
- Driver: Mesa-tkg 20.1.0-devel (git-8970b7839a)
- Wine version: Proton 5.0-5
- DXVK version: 1.6-18-g00d371d7

### Apitrace file(s)
- https://drive.google.com/open?id=1HaHi6CG4V3rPMo2_imprxXKEtlfyeaYZ

### Log files (using Wine's DXGI)
- d3d11.log: [JustCause3_d3d11.log](https://github.com/doitsujin/dxvk/files/4435300/JustCause3_d3d11.log)

**Comment by doitsujin** [comment]
See #613 .

**Comment by doitsujin** [comment]
Actually, nevermind, this seems to be a separate issue. Looks like a RADV bug to me since it doesn't happen with AMDVLK.

**Comment by BlazeKl** [comment]
I have only noticed HUD problems on the trace, everything else is rendered properly, even the terrain bug on RADV, I used apitrace's dlls directly from its github page, it's there any fork that works better for this case?

**Comment by doitsujin** [comment]
Not really; sometimes it just bugs out and you can't do much about it.

Can you test whether amdvlk actually fixes the bug in-game on your end?

**Comment by BlazeKl** [comment]
it seems that it only happens on RADV, AMDVLK and -PRO don't have the bug, where should I report bugs to mesa?

**Comment by aufkrawall** [comment]
It's already reported:
https://gitlab.freedesktop.org/mesa/mesa/issues/851
Another bump likely wouldn't hurt though.

**Comment by doitsujin** [comment]
Wasn't that *yet another* problem? What I see when replaying the apitrace is that the terrain geometry is glitching randomly.
