### ISSUE TITLE
GTA IV crashes

### ISSUE THREAD

**Issue by NikoBellicRU** [doitsujin/dxvk#1556]
The game crashes soon as i go outside the house, tried with PROTON_USE_WINED3D=1 %command% and works fine.

GPU:GTX 670
Driver:440.48.08
Wine version: Proton-5.0-6-rc2
DXVK version: 1.6

[steam-12210.log](https://github.com/doitsujin/dxvk/files/4440795/steam-12210.log)

**Comment by mirh** [comment]
Still a thing?

**Comment by NikoBellicRU** [comment]
Not sure if this still happends but i don't have the hardware anymore to test.
