### ISSUE TITLE
Battlefield 2: hexagonal terrain artifacts

### ISSUE THREAD

**Issue by bno1** [doitsujin/dxvk#1558]
Random black hexagons appears on terrain in the distance.

Screenshot:
![Screenshot_2020-04-07_00-50-36](https://user-images.githubusercontent.com/6632595/78608617-e8bfbb00-7869-11ea-864f-f1f2c78a4916.jpg)

### Software information
Battlefield 2 v1.5, Terrain set to High or Medium.

### System information
- GPU: GTX 960m
- Driver: 440.64
- Wine version: 5.5
- DXVK version: 1.6

### Apitrace file(s)
https://drive.google.com/open?id=1bLji2SE4evIUzV_DEtsQKfp7UTdo6mi8

### Log files
[BF2_d3d9_terrain.log](https://github.com/doitsujin/dxvk/files/4440986/BF2_d3d9_terrain.log)

**Comment by doitsujin** [comment]
Does `d3d9.invariantPosition = True` fix this?

Also, please disable overrides such as `d3d9.samplerAnisotropy = 16`.

**Comment by bno1** [comment]
`d3d9.invariantPosition = True` doesn't fix it. Anisotropy doesn't affect it either, but sorry for leaving it enabled. From what I've read online it mostly affects Nvidia cards. Some ATI users fixed it by enabling `Catalyst AI`. Not idea what that setting did.

**Comment by Joshua-Ashton** [comment]
Closed via f549586331bc6e020b6ac6b1bb7653f7db0b5a36

**Comment by bno1** [comment]
@Joshua-Ashton unfortunately `longMad` doesn't solve it for me

**Comment by Joshua-Ashton** [comment]
Fun. Does longMad + invariantPosition work for you?

**Comment by bno1** [comment]
Yep, that works

**Comment by Joshua-Ashton** [comment]
Yeah I just tested on NV myself, cool. I'll add that as well, needs both there.

**Comment by bno1** [comment]
Thanks!
