### ISSUE TITLE
Darksiders II Deathinitive Edition Resolution Problem Regression

### ISSUE THREAD

**Issue by iWeaker4you** [doitsujin/dxvk#1559]
The game suffers from this error every time I initialize it, test it with DXVK 1.5.4 and it works without problems, I have tried compiling the last commit and the problem persists.
I also tried version 1.5.5 and I have the same problem.

I found that starting from this commit causes resolution problems
commit: 

[d3d9] Don't expose formats with alpha as adapter formats
https://github.com/doitsujin/dxvk/commit/cf6142e78225373809286765d681d447e5f7bf68

![Captura de pantalla_2020-04-06_16-01-29](https://user-images.githubusercontent.com/49424816/78617160-500a4a80-782b-11ea-934a-10b09cffd131.png)

**Comment by Joshua-Ashton** [comment]
This should be fixed in `master` now.
