### ISSUE TITLE
Black Desert Online crashes

### ISSUE THREAD

**Issue by kqzkqz** [doitsujin/dxvk#1561]
### Software information
Black Desert Online

### System information
- GPU: AMD Vega 64
- Driver: Mesa 20.0.99 AMD RADV LLVM/ACO
- Wine version: wine-staging-5.5
- DXVK version: 1.6

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:
[BlackDesert32_dxgi.log](https://github.com/doitsujin/dxvk/files/4446755/BlackDesert32_dxgi.log)
[BlackDesert32_d3d11.log](https://github.com/doitsujin/dxvk/files/4446757/BlackDesert32_d3d11.log)
[BlackDesert32_d3d9.log](https://github.com/doitsujin/dxvk/files/4446759/BlackDesert32_d3d9.log)

been playing around with trying to get Black Desert Online working in Wine, and after compiling wine-staging 5.5 found I can actually get it to launch now. 

trying to trace down what is a wine bug and what is a DXVK bug with actually getting into game, so apologies if this is filled with some spam, wanted to get some help on what issue should be reported where.

so far these are my results if anyone wants to try to reproduce:

- using a clean wineprefix, nothing installed but dxvk and d3dcompiler_43 and d3dcompiler_47 (both set to native)

- there's a known [wine bug](https://bugs.winehq.org/show_bug.cgi?id=44985) that affects the launcher, however it seems that with some luck and patience (race condition?) you can get past it by closing the closing the 'DGCefeBrowser.exe has encountered a serious problem and needs to close" window, in my case it'll pop up 3 times in a row if I win the race, or just once and show a black screen on the launcher if I lose

- without DXVK, using just wine3d, as soon as the game launches you get a "Cannot create device" and it closes
- with DXVK, the game launches and _sometimes_ makes it to the main menu
- with DXVK's d3d9 disabled, you get the same "Cannot create device" error when launching" 
- using DXVK without DXGI, the rate at which the game crashes before getting to the main menu seems to drop a lot
- with DXVK d3d11, the game typically crashes when you hit the "Enter game" on the start up screen, however sometimes I've managed to make it farther
- with DXVK for d3d9, wine's build in d3d11, and dxgi disabled, I've consistently succeeded into actually getting in game for a brief second before crashing.

unfortunately I'm not sure how to get a good apitrace, since the game is started by the launcher, so any tips or guidance would be appreciated there. I've attached logs from my latest attempt with DXVK's d3d9, d3d11, and dxgi all enabled, where I made it all the way to character selection.

**Comment by doitsujin** [comment]
Is your mesa-git build up to date (i.e. not more than a few hours old)? Asking because there have been some serious regressions recently which may affect you if you're using an older build.

As for an apitrace, you can basically dump the apitrace DLLs next to the game's executablel, as described here: https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace

That said, there isn't anything in the logs that directly hints at a DXVK issue. However, you seem to be running a 32-bit version of the game which could run into memory issues; there should be a 64-bit executable as well. Does that improve anything?

**Comment by kqzkqz** [comment]
thanks for the tip, just recompiled latest mesa, last one was from about a week ago, so far still getting the same results, but that did remind me about something I derped on and forgot to mention.

to even get it the game to launch, the very first thing I had to do was apply [this patch](https://www.winehq.org/pipermail/wine-devel/2019-July/148646.html) to winevulkan for vulkan child window rendering, so that could also be the culprit, or at least another piece. 

i'll also try to play around with it in a 64 bit prefix, I had thought the game was a 32 bit only but you're correct, there is a 64 bit binary as well. so far I haven't been able to get it to launch in a 64 bit prefix (looks like Xingcode, the anti-cheat doesn't initialize for some reason).

also thanks for the tip on the trace, was able to get a quick trace (unfortunately derped with DXVK on, let me know if you need one with just wined3d) 
here's a [google drive link](https://drive.google.com/file/d/1uFreL6_ixwaRAG9ionYSpciWkpP7g4Vp/view?usp=sharing)

if there's nothing in the logs that you can see that indicate a DXVK issue however, I'll start banging out some reports with wine, but I appreciate you taking a look!

**Comment by Berobad** [comment]
Xigncodes needs it's kernel-driver, if it's not running it closes the game.     
And it's highly unlikely that these kind of root-kit anticheat systems will ever work on wine.     

(at least in the past xigncode itself even broke from windows patches)

**Comment by kqzkqz** [comment]
sorry for the delay, gotcha, was unaware xingcode was kernel-mode, assumed the game just wouldn't start if the driver wasn't present but it does look like the crash once in game is caused by that, I'll close this for now since this isn't a DXVK problem.
