### ISSUE TITLE
[D3D9] a80eea92 breaks input on multiple games

### ISSUE THREAD

**Issue by DaRkL3AD3R** [doitsujin/dxvk#1562]
Launch Half Life 2 using DXVK installed with this commit or later merged. Cannot interact with the main menu whatsoever, the game ignores all keyboard and mouse commands. Other known games affected by this: Call of Duty Modern Warfare 2, Deus Ex, Unreal Tournament.

### System information
- GPU: 1080 Ti
- Driver: 445.78 
- DXVK version: a80eea92 and newer

### Log files
- d3d9.log: https://drive.google.com/file/d/16tQwW8dI15s4S4QLTzAVU4-xrerGmcbV/view

**Comment by Joshua-Ashton** [comment]
Fixed as of https://github.com/doitsujin/dxvk/commit/93b4427a138871e31628297f3b94eac929346c33
