### ISSUE TITLE
L.A.NOIRE

### ISSUE THREAD

**Issue by legluondunet** [doitsujin/dxvk#1564]
Hello,

L.A.NOIRE (Steam version) does no more launch with DXVK >=1.5
I can only launch the game with DXVK 1.4.6 and inferior version.

Could you reproduce this issue?

Thank you for your help.

**Comment by doitsujin** [comment]
Log files?

**Comment by legluondunet** [comment]
sure, I'm working on it :)

**Comment by legluondunet** [comment]
[lanoire08-04-2020 19-57-07.log](https://github.com/doitsujin/dxvk/files/4452094/lanoire08-04-2020.19-57-07.log)
![Capture d’écran de 2020-04-08 19-57-06](https://user-images.githubusercontent.com/325405/78818442-f6de1a80-79d4-11ea-936c-1c1dda338d05.png)
[lanoire08-04-2020 19-57-07.log](https://github.com/doitsujin/dxvk/files/4452110/lanoire08-04-2020.19-57-07.log)
[LANLauncher_d3d9.log](https://github.com/doitsujin/dxvk/files/4452115/LANLauncher_d3d9.log)
[LANoire_d3d11.log](https://github.com/doitsujin/dxvk/files/4452116/LANoire_d3d11.log)


[LANoire_dxgi.log](https://github.com/doitsujin/dxvk/files/4452120/LANoire_dxgi.log)

**Comment by doitsujin** [comment]
Does it work if you disable DXVK's D3D9 implementation (`WINEDLLOVERRIDES=d3d9=b`)?

**Comment by legluondunet** [comment]
Others results with DXVK 1.4.6:
![Capture d’écran de 2020-04-08 20-28-25](https://user-images.githubusercontent.com/325405/78820158-a0261000-79d7-11ea-94fc-e0ec575a1854.png)

DXVK logs:
[LANoire_d3d11.log](https://github.com/doitsujin/dxvk/files/4452185/LANoire_d3d11.log)
[LANoire_dxgi.log](https://github.com/doitsujin/dxvk/files/4452186/LANoire_dxgi.log)

**Comment by doitsujin** [comment]
The DXVK logs don't contain any useful info whatsoever.

Can you please test what happens with **only** DXVK's D3D11 installed?

**Comment by legluondunet** [comment]
> Does it work if you disable DXVK's D3D9 implementation (WINEDLLOVERRIDES=d3d9=b)?
tested with D3D9 build only with DXVK 1.6 changed nothing.
[LANoire_d3d11.log](https://github.com/doitsujin/dxvk/files/4452226/LANoire_d3d11.log)
[LANoire_dxgi.log](https://github.com/doitsujin/dxvk/files/4452227/LANoire_dxgi.log)

> How do you even get the game to work on Linux? I have it, but can't get it to run.
I can launch this game only with a particular Wine build called tkg <=4.5

**Comment by legluondunet** [comment]
Do you need others info?
I will give you every needed info to debug this issue.

**Comment by doitsujin** [comment]
Well, looks like you'll have to bisect the issue and hope that doing so gives me a hint what might be wrong, or just keep using the old DXVK version.

There's just absolutely nothing I can do here. The game just *no longer works*, even on Windows 10 it just doesn't start, and I'm not willing to waste even more time trying to work around whatever issues it might be having.

**Comment by legluondunet** [comment]
"I'm not willing to waste even more time trying to figure out what's going on with a game that you can't even play on the "supported" OS anymore."
I understand your position @doitsujin . However didn't you find funny that a Windows game runs better on Linux that on Windows? :)

I have additional info about this issue.
Tannis from Lutris team asked me to make this test:
- delete d3d9.dll (32 and 64 bits) installed by DXVK 1.6
- launch the game, and finally:

![Capture d’écran de 2020-04-09 12-35-37](https://user-images.githubusercontent.com/325405/78890740-77992700-7a66-11ea-9fc1-ec289ad15c66.png)

But I don't understand what that means?

**Comment by doitsujin** [comment]
> However didn't you find funny that a Windows game runs better on Linux that on Windows?

I can't get the game to run on Linux either, so there's that.

> But I don't understand what that means?

No idea, but as mentioned, not a lot I can do here. I guess disabling D3D9 is a viable workaround though.

**Comment by legluondunet** [comment]
@doitsujin ,
just a last thing, could you tell me if the error message contained in this log file give you a clue?

[LANoire_d3d9.log](https://github.com/doitsujin/dxvk/files/4466569/LANoire_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Fixed!

**Comment by legluondunet** [comment]
Hello @Joshua-Ashton this issue is still not fixed in DXVK >= 1.6
I think this bug is a duplicate of https://github.com/doitsujin/dxvk/issues/1282
I have to disable d3d9 or the game won't start WINEDLLOVERRIDES=d3d9=b or erase manually the d3d9 dll.

**Comment by Joshua-Ashton** [comment]
Works fine for me.

**Comment by Joshua-Ashton** [comment]
Logs?

**Comment by legluondunet** [comment]
> Works fine for me.

You are using the Steam version? with the windows 8.1 patch?

**Comment by Joshua-Ashton** [comment]
I'm using the Steam version with no patches at all.

**Comment by legluondunet** [comment]
> I'm using the Steam version with no patches at all.

Interesting, most gamers needs this patch to launch it with recent Proton version:
https://github.com/ValveSoftware/Proton/issues/544#issuecomment-617386620

Could you tell me which Proton version you are using? Special parameters?

The log:

```
info:  Game: steam.exe
info:  DXVK: v1.6.1+
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to initialize OpenVR
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  GeForce GTX 770:
info:    Driver: 435.21.0
info:    Vulkan: 1.1.109
info:    Memory Heap[0]: 
info:      Size: 2048 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 11969 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
info:  Process set as DPI aware
wine: Unhandled page fault on read access to 0xe7c0f9e0 at address 0x17b90fb (thread 007f), starting debugger...
00c8:fixme:ntdll:EtwEventRegister ({47a9201e-73b0-42ce-9821-7e134361bc6f}, 0x100784a0, 0x10142c18, 0x10142c10) stub.
00c8:fixme:ntdll:EtwEventRegister ({58a9201e-73b0-42ce-9821-7e134361bc70}, 0x100784a0, 0x10142c50, 0x10142c48) stub.
00c8:fixme:ntdll:EtwEventRegister ({3fa9201e-73b0-43fe-9821-7e145359bc6f}, 0x100784a0, 0x10142be0, 0x10142bd8) stub.
00c8:fixme:ntdll:EtwEventRegister ({1432afee-73b0-42ce-9821-7e134361b433}, 0x100784a0, 0x10142c88, 0x10142c80) stub.
00c8:fixme:ntdll:EtwEventRegister ({4372afee-73b0-42ce-9821-7e134361b519}, 0x100784a0, 0x10142cc0, 0x10142cb8) stub.
00c8:fixme:imm:ImmGetOpenStatus (0x3c0018): semi-stub
00c8:fixme:imm:ImmReleaseContext ((nil), (nil)): stub
00c8:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
00c8:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
00c8:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
00c8:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
00c8:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
IPC client is in my process, could/should be using an in-process pipe.IPC client is in my process, could/should be using an in-process pipe.IPC client is in my process, could/should be using an in-process pipe.ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
ILocalize::AddFile() failed to load file "public/steambootstrapper_french.txt".

```

**Comment by legluondunet** [comment]
another log error, I hope this time it will help:

```
[0501/154825.414:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: renderer
err:   Failed to create surface
[0501/154826.121:ERROR:angle_platform_impl.cc(47)] reset(615): Could not create additional swap chains or offscreen surfaces, HRESULT: 0x80070057
[0501/154826.122:ERROR:gl_surface_egl.cc(668)] EGL Driver message (Critical) eglCreateWindowSurface: Bad allocation.
[0501/154826.122:ERROR:gl_surface_egl.cc(1234)] eglCreateWindowSurface failed with error EGL_BAD_ALLOC
[0501/154826.122:ERROR:in_process_command_buffer.cc(592)] ContextResult::kSurfaceFailure: Failed to create surface.
[0501/154826.804:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: renderer
err:   Failed to create surface
[0501/154827.003:ERROR:angle_platform_impl.cc(47)] reset(615): Could not create additional swap chains or offscreen surfaces, HRESULT: 0x80070057
[0501/154827.003:ERROR:gl_surface_egl.cc(668)] EGL Driver message (Critical) eglCreateWindowSurface: Bad allocation.
[0501/154827.003:ERROR:gl_surface_egl.cc(1234)] eglCreateWindowSurface failed with error EGL_BAD_ALLOC
[0501/154827.003:ERROR:in_process_command_buffer.cc(592)] ContextResult::kSurfaceFailure: Failed to create surface.
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  f8fb5c27-c6b3-4f75-a4c8-439af2ef564c
[0501/154827.319:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: renderer
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Unhandled page fault on read access to E78D81A0 at address 017B90FB (thread 0134), starting debugger...
[0501/155021.353:INFO:crash_reporting.cc(247)] Crash reporting enabled for process: gpu-process
warn:  CreateDXGIFactory2: Ignoring flags
info:  Game: steamwebhelper.exe
info:  DXVK: v1.6.1+
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  GeForce GTX 770:
info:    Driver: 435.21.0
info:    Vulkan: 1.1.109
info:    Memory Heap[0]: 
info:      Size: 2048 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 11969 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
warn:  DxgiAdapter::QueryInterface: Unknown interface query
warn:  17399d75-964e-4c03-99f8-9d4fd196dd62
warn:  CreateDXGIFactory2: Ignoring flags
info:  Game: steamwebhelper.exe
info:  DXVK: v1.6.1+
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  GeForce GTX 770:
info:    Driver: 435.21.0
info:    Vulkan: 1.1.109
info:    Memory Heap[0]: 
info:      Size: 2048 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 11969 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
warn:  DxgiAdapter::QueryInterface: Unknown interface query
warn:  17399d75-964e-4c03-99f8-9d4fd196dd62
System page size: 4096
```
