### ISSUE TITLE
dxvk.conf does not support escaped characters

### ISSUE THREAD

**Issue by Ginjirotchi** [doitsujin/dxvk#1567]
Currently, DXVK is set up to read a value in a config file as starting from the first whitespace character after the `=` until either it reaches another whitespace character or the end of the line, meaning that some parameters (for example, `d3d9.customDeviceDesc = Device Name Here`) cannot be used properly within a dxvk.conf file as it will end up being read as `d3d9.customDeviceDesc = Device`.

Could escape character support be added so parameters with whitespace/special characters can be used?

**Comment by doitsujin** [comment]
It doesn't support string options because string options just didn't exist before the addition of D3D9.

Guess we'll need to find some way to support those.

**Comment by doitsujin** [comment]
You should be able to use `d3d9.customDeviceDesc = "Device Name Here"` now.
