### ISSUE TITLE
File not found in wine prefix

### ISSUE THREAD

**Issue by kbr-** [doitsujin/dxvk#1572]
The dxvk-1.6 `setup_dxvk.sh` script didn't work for me. The issue was that `winepath` appended `\r` at the end of the path, so the `dstfile` variable in `installFile` would be garbage and the script would complain with "File not found".

I fixed this by removing the `\r` suffix from `win64_sys_path` and `win32_sys_path` as follows:
```
win64_sys_path=$($wine64 winepath -u 'C:\windows\system32' 2> /dev/null)
win64_sys_path="${win64_sys_path/$'\r'/}"
if $wow64; then
  win32_sys_path=$($wine winepath -u 'C:\windows\system32' 2> /dev/null)
  win32_sys_path="${win32_sys_path/$'\r'/}"
fi
```

**Comment by doitsujin** [comment]
This is already fixed in `master`, see #1569
