### ISSUE TITLE
Install dxvk

### ISSUE THREAD

**Issue by walk5** [doitsujin/dxvk#1573]
I am having trouble installing the tar.gz file. I have the read me page but I do not understand what to do. I do not know what the dxvk directory is and I have been unable to find the .wine-prefix file. 

I am sorry to ask this but I am still knew to linux and I am learning as I go.

**Comment by IroAlexis** [comment]
Hello it is an issue that was fixed [this commit](https://github.com/doitsujin/dxvk/commit/f257a794ccbf2d3efa77d56e220b75f449ab1675)

**Comment by walk5** [comment]
So this is a know issue and the new version of wine will fix the issue?

**Comment by walk5** [comment]
I am knew to this and I am not sure I understand what is being said.

**Comment by walk5** [comment]
Are you refering the the most recent stable wine version.

**Comment by vabenil** [comment]
If you don't intend to use dxvk for development and just want to install it on your machine for playing games then installing through your package manager should be easier. Just search how to install dxvk in <Name of your Linux distribution here> and you should find something.

**Comment by walk5** [comment]
I need the dxvk for using with zbrush and 3d printing software. I will do that search. I tried to install it through winetricks but it fails.

**Comment by doitsujin** [comment]
Can you be a bit more precise? *what* fails? What's the error message?

**Comment by IroAlexis** [comment]
Oh I misunderstood what you were saying. Normally, you have created an wine prefix and you have just use : WINEPREFIX=/path/to/wineprefix /path/to/setup_dxvk.sh install.

But since Wine 5.6, you sould modifify DXVK script (all version) like [here](https://github.com/doitsujin/dxvk/commit/f257a794ccbf2d3efa77d56e220b75f449ab1675) for install him or just wait the next DXVK version.

PS : I don't know if it is clear but I try clear

**Comment by walk5** [comment]
I have no idea how to find the wine prefix. I searched my files and it us not there. At least that I can find. I am not using the 5.6 version of wine. I am using the stalbe version 5.0.

**Comment by Leopard1907** [comment]
If you're new to Linux , maybe you should consider using Lutris for ease of use until you learn/get used to manually using Wine and related components.

**Comment by walk5** [comment]
I had everything running. I just ran into a problem and how nothing is working.

**Comment by walk5** [comment]
We really like kubuntu. It is really not complicated to use. This is the only real issue we have had. Everything else is very awesome.

**Comment by vabenil** [comment]
I recommend you this video: https://www.youtube.com/watch?time_continue=183&v=MaRNZ8r-4Gk&feature=emb_logo

**Comment by vabenil** [comment]
Also your default wineprefix is usually located in the ~/.wine directory. Wine prefixes made using winetricks are usually located in ~/.local/share/wineprefixes.

**Comment by Roesjka** [comment]
Files or directories starting with a .(dot) are hidden files or directories.
A .wine is not a file but usually a hidden directory in your home directory.
If you want to see hidden files or directories open a terminal and type ls -la and it will show everything in your home directory.

**Comment by walk5** [comment]
vabenil, 

I went to the video and then found the website with the instructions. I walked through the first 2 download commands with no issue. Then I entered the  load command `sudo dpkg -i dxvk`
After this I received errors they say

'dpkg: denpendency problems prevent configuration of dxvk-wine64-development:
dxvk-wine64-development depends on libwine-development; however:
Package libwine-development is not installed.

dpkg: error processing package dxvk-wine64-development (--install):
   dependency problems - leaving unconfigured
dpkg: denpendency problems prevent configuration of dxvk:
   dxvk depends on dxvk-wine64-development (>= 0.96+ds1-1) | dxvk-wine32-development (>= 0.96+ds1-1); however:
    Package dxvk-wine64-development is not configured yet.
    Package dxvk-wine32-delepoment is not installed.

dpkg: error processing package dxvk (--install):
    dependency problems - leavjng unconfigured
Processing triggers for man-db (2.8.7-3) ...
Errors were encountered while processing:
    dxvk-wine64-delepoment
    dxvk'

I stopped and did not go on to the next step.

**Comment by walk5** [comment]
Roesjka,

I found the wine files but looking through there I found not prefix file.

**Comment by Roesjka** [comment]
There is no prefix file. .wine is the prefix.
Your problems with dpkg stems from the fact it depends where you installed wine(dev or staging) from. Where did you install wine from Ubuntu repo? or Winehq repo?

**Comment by vabenil** [comment]
walk5 those errors are normal, you are supposed to do a:
`sudo apt install -f`
Which is supposed to fix those errors.

**Comment by vabenil** [comment]
To be more specific those "errors" are simply dependencies missing and the:
`sudo apt install -f`
 installs those dependencies so everything is normal.

**Comment by walk5** [comment]
Roesjka,
I used the wget and the winehq repository for the download.

**Comment by walk5** [comment]
vabenil,
I continued the installmand add the `sudo apt install -f`
That installed. Then I went on to the configuration. I cd into the folder. That went great then I entered `./setup_dxvk.sh`
Then I get 
`Unrecognized option:
Usage: ./setup_dxvk.sh [install|uninstall] [-q|--quiet] [-y|-n]`

**Comment by vabenil** [comment]
do :
`./setup_dxvk.sh install`

**Comment by Roesjka** [comment]
Do note if you have wine-development installed it is from the Ubuntu repo and not from winehq repo.

**Comment by walk5** [comment]
vabenil,
I entered that code and no error message. Does this mean we are good?

**Comment by walk5** [comment]
Also Kubuntu says it needs to update but it will not run the update. When you click update it says fetching updates but it never updates.

**Comment by jug007** [comment]
I don't know about you guys, but I always just "install" DXVK by copying the dll files to where the executable of the program I want to start is.
- Download latest release
- go to x64 directory
- drag and drop all the files to where the program you want to use DXVK for is

**Comment by walk5** [comment]
Jug
You don't actually install the files. You just add them to the directory

**Comment by LordJBeckman** [comment]
> 
> 
> So this is a know issue and the new version of wine will fix the issue?

If the above commit fixes it wouldn't it work to use the latest compiled version of DXVK from:
https://git.froggi.es/doitsujin/dxvk/-/jobs

It should be DXVK version 1.6 plus the 44 additional commits to the code base since this versions release including the above fix without having to build or compile the source yourself.

**Comment by vabenil** [comment]
> vabenil,
> I entered that code and no error message. Does this mean we are good?

You should be good now. Now your default wine prefix should be using dxvk by default.

**Comment by omnitrix9991** [comment]
> I am having trouble installing the tar.gz file. I have the read me page but I do not understand what to do. I do not know what the dxvk directory is and I have been unable to find the .wine-prefix file.
> 
> I am sorry to ask this but I am still knew to linux and I am learning as I go.

Lutris does everything for you, install it and enjoy

**Comment by NTULINUX** [comment]
I kept on getting errors about wine-development and likes missing from my system, plus by default, dxvk_setup.sh wanted to use Debian's packages instead of the newer ones hosted at winehq. I wrote a script that fixes both:

`
#!/usr/bin/env bash

WINE_BINDIR="/opt/wine-devel/bin"

sudo ln -sfv "${WINE_BINDIR}/wine" "${WINE_BINDIR}/wine-development"
sudo ln -sfv "${WINE_BINDIR}/wine64" "${WINE_BINDIR}/wine64-development64"
sudo ln -sfv "${WINE_BINDIR}/wine" "${WINE_BINDIR}/wine64-development"

sudo ln -sfv "${WINE_BINDIR}/wine" "/usr/bin/wine"
sudo ln -sfv "${WINE_BINDIR}/wine" "/usr/bin/wine-development"
sudo ln -sfv "${WINE_BINDIR}/wine64" "/usr/bin/wine64"
sudo ln -sfv "${WINE_BINDIR}/wine64" "/usr/bin/wine64-development"
`

Problems are gone and now I can use DXVK with the latest releases from WineHQ. Cheers!
