### ISSUE TITLE
"BLUE REFLECTION" some shadows stretching and flickering

### ISSUE THREAD

**Issue by jug007** [doitsujin/dxvk#1574]
Some of the shadows in BLUE REFELCTION stretch weirdly around the screen and flicker.
This issue happens on DXVK on windows and linux. Native windows works fine and wined3d does not run.
On linux "d3d9.deferSurfaceCreation = True" was added to dxvk.conf.
The issue does not always appear in the school, but has always appeared in the "common".

### Software information
Game is "BLUE REFLECTION" from steam.

### System information
- GPU: Nvidia GTX 1080
- Driver Linux: 440.82
- Driver Windows: 445.75 
- Wine version: GloriousEggroll Proton-5.6-GE-2
- DXVK version: 1.6

### Apitrace file(s)
- Windows without DXVK: http://motofckr9k.ddns.net/m/BLUE_REFLECTION.7z

### Log files

- d3d9.log: empty
- d3d11.log: [BLUE_REFLECTION_d3d11.log](https://github.com/doitsujin/dxvk/files/4495566/BLUE_REFLECTION_d3d11.log)
- dxgi.log: not created

**Comment by doitsujin** [comment]
It works fine on my AMD card.

Unfortunately RenderDoc just crashes when trying to capture it, so there's not an awful lot of debugging I can do.

**Comment by K0bin** [comment]
`d3d11.constantBufferRangeCheck = True` fixes the issue when replaying your trace.

**Comment by jug007** [comment]
I can confirm that the issue is fixed by that.
