### ISSUE TITLE
Bioshock Remastered low resolution textures

### ISSUE THREAD

**Issue by shoober420** [doitsujin/dxvk#1581]
### Software information
Bioshock Remastered, high settings

### System information
- GPU: GTK 760
- Driver: NVIDIA 440.82
- Wine version: Proton 5.0-6
- DXVK version: 

### Log files
- d3d9.log (with esync and fsync): [BioshockHD_d3d9yes.log](https://github.com/doitsujin/dxvk/files/4500969/BioshockHD_d3d9yes.log)
- d3d9.log (no esync and fsync): [BioshockHD_d3d9no.log](https://github.com/doitsujin/dxvk/files/4500971/BioshockHD_d3d9no.log)
- d3d11.log (with esync and fsync): [BioshockHD_d3d11yes.log](https://github.com/doitsujin/dxvk/files/4500972/BioshockHD_d3d11yes.log)
- d3d11.log (no esync and fsync): [BioshockHD_d3d11no.log](https://github.com/doitsujin/dxvk/files/4500973/BioshockHD_d3d11no.log)

Proton (with esync and fsync): [steam-409710yes.log](https://github.com/doitsujin/dxvk/files/4500974/steam-409710yes.log)
Proton (no esync and fsync): [steam-409710no.log](https://github.com/doitsujin/dxvk/files/4500976/steam-409710no.log)

The games textures are low resolution unless ESync and FSync are disabled (PROTON_NO_ESYNC=1 and PROTON_NO_FSYNC=1).

https://github.com/ValveSoftware/Proton/issues/399

**Comment by doitsujin** [comment]
Not our bug.

**Comment by K0bin** [comment]
I can't reproduce that one either. I've tried the game with DXVK on Windows and textures looked fine in the lighthouse at the beginning.

**Comment by shoober420** [comment]
@K0bin 
Have you tried it on Linux?

**Comment by K0bin** [comment]
No, but going by the fact that it works with DXVK on Windows this most likely isn't a DXVK issue.
What do the textures look like when you run it with WineD3D?

**Comment by shoober420** [comment]
I wanted to clarify it indeed was not a DVXK bug by asking @doitsujin, so you're right, this is not a DXVK issue, but a Wine bug.
