### ISSUE TITLE
Beam.NG requires IDXGIFactory2 and IDXGISwapChain3

### ISSUE THREAD

**Issue by Mixaill** [doitsujin/dxvk#159]
```
warn:  DxgiFactory::QueryInterface: Unknown interface query
warn:  50c83a1c-e072-4c48-87b0-3630fa36a6d0
warn:  94d99bdb-f1f8-4ab0-b236-7da0170edab1
```

Logs was provided be BieHDC from VKx Discord server.

**Comment by doitsujin** [comment]
MinGW headers currently don't seem to have full support for DXGI 1.2 so I'll put that off for a bit. `IDXGISwapChain3` is part of a later revision which I'm not going to support.

**Comment by doitsujin** [comment]
The [dxgi1_2](https://github.com/doitsujin/dxvk/tree/dxgi1_2) branch implements `IDXGIFactory2`. As mentioned, `IDXGISwapChain3` will not be supported.
