### ISSUE TITLE
FFXIV Launcher issue past 1.4.6

### ISSUE THREAD

**Issue by mskdenigma** [doitsujin/dxvk#1591]
I'm having troubles launching Final Fantasy XIV if I used any version of DXVK past 1.4.6 which seems to be when D9VK was introduced, when trying 1.5 or 1.6.1 instead of ffxiv_dx11_d3d11.log being filled this file is generated ffxivlauncher_d3d9.log. I do believe the game is meant to run in dx11 but perhaps the launcher isn't? 

I've attached those logs here as well as a screenshot showing the launcher launching but error out instantly

[ffxivlauncher_d3d9.log](https://github.com/doitsujin/dxvk/files/4519050/ffxivlauncher_d3d9.log)
[ffxivlauncher_d3d11.log](https://github.com/doitsujin/dxvk/files/4519051/ffxivlauncher_d3d11.log)
![Screenshot from 2020-04-22 17-18-59](https://user-images.githubusercontent.com/30030634/80035105-6ec04080-84bd-11ea-8787-1f449bbed8a0.png)

**Comment by doitsujin** [comment]
Just disable DXVK's D3D9 if that's causing an issue.

Note that the HTTPS error has absolutely nothing to do with D3D.

**Comment by mskdenigma** [comment]
Hey so I was able to get it running, wasn't sure if there was an official method to disable it so I just deleted the d3d9.dll so that does solve my issue, should I keep this open for debugging this issue with dxvk's d3d9? that HTTPS error has been something that I've seen with any generic error getting this up and running

**Comment by doitsujin** [comment]
I cannot reproduce the problem, so there's not much I can debug here.
