### ISSUE TITLE
Stalker lost alpha gives Memory allocation failed, Stalker gunslinger gives Memory allocation failed on dx9, dx10 and dx11 

### ISSUE THREAD

**Issue by adcdam** [doitsujin/dxvk#1593]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
Preferably record the trace on Windows, or wined3d if possible.

**Reports with no log files will be ignored.**

### Software information
Name of the game, settings used etc.

### System information
- GPU:rx5700
- Driver:mesa20
- Wine version:5.6 
- DXVK version: 1.61

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by doitsujin** [comment]
No log files or anything for us to work with, but looking at the headline it sounds like another case of #1318 .
