### ISSUE TITLE
Into the Breach is completely black

### ISSUE THREAD

**Issue by gapg64** [doitsujin/dxvk#1595]
this problem does not occur in Wined3d
With DXVK
https://imgur.com/a/5V5ZEez
Without DXVK
https://imgur.com/a/mbOptj5
### System information
- GPU:Intel HD5500
- Driver:Mesa 20.0.4
- Wine version: 5.5
- DXVK version: 1.6.1

### Log files
- d3d9.log:https://drive.google.com/file/d/10Wv0MKoybcKg-lQLrQZiWQR6LU02bC8V/view?usp=sharing

**Comment by doitsujin** [comment]
Can you please provide an apitrace?

We are aware of the issue, but this is actually an OpenGL game that doesn't really use D3D9 for rendering. Not exactly sure what it's doing with the API.

**Comment by gapg64** [comment]
It is not possible for me to do the apitrace since the console always returns this same error, 
I'm not sure if I'm doing something wrong
https://imgur.com/a/RfufXv0

**Comment by gapg64** [comment]
I have solved the problem by removing d3d9

**Comment by doitsujin** [comment]
You have to run `apitrace.exe trace -a d3d9 ...`.

**Comment by gapg64** [comment]
I reopened this problem since although deleting the d3d9 works, this only covers the problem and I have seen several games with this same symptom, so I left the trace of the breach here (I know it takes me a while to upload it I had a few problems to be able to do the apitrace)
Into the Breach(Apitrace)
https://drive.google.com/file/d/1atyKhoH8zT1pScUalaGHRicrWqPrairU/view?usp=sharing

**Comment by airminer** [comment]
I'm facing the same issue - Black screen when DXVK is installed.
Interestingly, I can't seem to get an D3D9 apitrace when DXVK is not installed.

Files:
[Breach.trace](https://mega.nz/file/hF8hmChR#X4q-JKTU-h9aUEHpvs0KYfoJGYPJfA0Jx90gy52z-n4)
[Breach_d3d9.log](https://mega.nz/file/9QtXmCpB#tfc_xWaqUzWHlWtf6ZZGFB6Ej_njFMKF1LtQjD35eLI)
