### ISSUE TITLE
Need for Speed Rivals won't go to fullscreen with DXVK dxgi.dll

### ISSUE THREAD

**Issue by ngleb** [doitsujin/dxvk#1596]
- If dxvk 1.6.1 is installed without dxgi, then the game run in full screen mode. Resolution is set to 1920x1200 (native screen resolution).
- If dxvk 1.6.1 is installed with dxgi, then game will run with some area left below on the screen. From console logs, I can see set resolution to 1920x1185 which is what I see (approx 15 pixels on the bottom of the screen). So the game is still in fullscreen mode, but the bottom area shows desktop. No cursor or something like this.

This did not happen until dxvk 1.6.1 was installed. I used 1.5.x before but they were built with winegcc. I tried dxvk 1.6.1 binary from this github repo, or manually built 1.6.1 (mingw build) and they cause the same issue.

If some other information is necessary, please let me know. I tried to collect all info as described.

### Software information
Need for Speed Rivals, 1920x1200, max graphcis settings.

### System information
- GPU: AMD Radeon RX570
- Driver: amdgpu from linux 5.4.30 / mesa radv 20.0.5 / aco compiler with llvm 9.0.1
- Wine version: 5.6
- DXVK version: 1.6.1 (mingw build)

### Apitrace file(s)
- https://drive.google.com/file/d/1ig0yhsaeHr94sb6jJifh0keBbvsk9IPa/view?usp=sharing

### Log files
- [NFS14_x86_d3d11.log](https://github.com/doitsujin/dxvk/files/4533016/NFS14_x86_d3d11.log)
- [NFS14_x86_dxgi.log](https://github.com/doitsujin/dxvk/files/4533017/NFS14_x86_dxgi.log)

**Comment by ngleb** [comment]
That's strange, but I cannot reproduce this issue anymore.

The only thing that I changed was running the same command once with
DXVK_LOG_LEVEL=none

And after that the game always starts in fullscreen mode. I'm not sure how it was possible, and if it was a coincidence.

**Comment by doitsujin** [comment]
Weird, DXGI hasn't really changed at all since 1.5.x except that I implemented some functions for VRAM budget reporting.

Interestingly though, I'm getting a crash when replaying your apitrace with DXVK's DXGI. Did you record it on Windows or with wined3d?

**Comment by ngleb** [comment]
I did record it on wined3d. Unfortunately I don't have access to Windows right now.

**Comment by ngleb** [comment]
Is it possible that this was a local issue with some other parts of my system? I tried vairous things to reproduce this issue, but no luck. It works fine now, always in fullscreen..

**Comment by doitsujin** [comment]
No idea what this might have been.

Anyway, closing since this seems to have been just a temporary issue and I can't really repro it here either (hacked dxvk to not crash on replaying the trace, working fine).
