### ISSUE TITLE
ESO graphics corruption since builds after 3cb3c05

### ISSUE THREAD

**Issue by schtufbox** [doitsujin/dxvk#160]
With the current commits, the graphics in ESO are all messed up (see attached sacreenshot)  as I generally still play with Wine-staging 3.3 with the vulkan stuff from staging 2.21 I thought I'd test with a proper install of wine-vulkan as well, and the issue was present there also. I had skipped a few versions, so went back and tested...3cb3c05 was the last one that worked properly, every version since has this issue, fo rme at any rate.
Hopefully I attached the log files right, anything else needed let me know? :)

![dxvk-vulkan-char-select](https://user-images.githubusercontent.com/27377883/37353757-ea892ff6-26d7-11e8-92c2-d2c2569b8089.png)
![dxvk-vulkan-ingame](https://user-images.githubusercontent.com/27377883/37353769-edeff8a0-26d7-11e8-80d3-445a66f57c16.png)

### System information
- GPU:Geforce GTX 1050
- Driver:390.25
- Wine version: wine-vulkan
- DXVK version:  ba2c478

[eso64_d3d11.log](https://github.com/doitsujin/dxvk/files/1807679/eso64_d3d11.log)
[eso64_dxgi.log](https://github.com/doitsujin/dxvk/files/1807680/eso64_dxgi.log)

**Comment by doitsujin** [comment]
Please run with `DXVK_DEBUG_LAYERS=1` and post the full console output.

Guess I'll have to disable image mapping *again*.

**Comment by doitsujin** [comment]
Please let me know if e6814332e741ac7222fe1c372fda7aed86ce657b fixes the issue.

**Comment by schtufbox** [comment]
e681433 fixes the issue, nice work :)   In the interest of testing, as requested I attempted to run ba2c478 with DXVK_DEBUG_LAYERS=1 but ESO will hang after login and before character select, so unable to test properly.

**Comment by schtufbox** [comment]
I'll give it another try, I did leave it 20 min or so but maybe not long enough.  I agree not 'nice' work as such but only nice as in the game works.  I'd say perhaps I should just switch to an AMD card, but that doesn't really fix the issue

**Comment by schtufbox** [comment]
It's currently been running for an hour, memory usage has been frozen at 1.3gb and disk read total is staying at 732kb CPU usage sits at 2%.  The ingame music still plays but the loading indicator froze over 45 min ago...I'll keep it going longer.

**Comment by doitsujin** [comment]
Well, it might take *long* to load, but not quite *that* long. Thanks for trying though.

**Comment by schtufbox** [comment]
I gave it another hour after that, as left it when taking dog for a walk, still nothing so just killed wine :D

**Comment by thirdeyefunction** [comment]
What are the other games affected by the reverted performance optimisation?  I would be happy to test but don't own ESO myself.

**Comment by doitsujin** [comment]
@thirdeyefunction Most Cryengine games and The Witcher 3 are known to benefit significantly from this optimization.

@schtufbox I created a new branch [direct-image-mapping](https://github.com/doitsujin/dxvk/tree/direct-image-mapping) which re-enables the optimization by default. I also fixed two issues that **may** have been the reason for the missing textures in ESO. Please test and let me know if it works.

**Comment by shmerl** [comment]
May be it can be toggled with some environment variable, in order not to require building different branches?

**Comment by ssorgatem** [comment]
For what is worth, ESO works on vega+radv with the direct-image-mapping branch, as expected.

I may test it later on my wife's laptop (Windows 10 + some NVIDIA GPU)

**Comment by schtufbox** [comment]
@doitsujin I 'attempted' to compile the direct-image-mapping' but due to the messed up mingw in AUR I was unable to do so...which is why I usually wait for https://haagch.frickel.club/files/dxvk/  as he does daily builds from github.  I had hoped that it was working by now, but alas no.

**Comment by ssorgatem** [comment]
@schtufbox , have you tried the methods suggested in the AUR page?
https://aur.archlinux.org/packages/mingw-w64-gcc/

That's how I managed to install a working crosscompiler...

**Comment by schtufbox** [comment]
That's how I managed to get it installed, but it won't compile

**Comment by thirdeyefunction** [comment]
>Most Cryengine games and The Witcher 3 are known to benefit significantly from this optimization

I was wondering more which games break from the feature, rather than which are helped by it. Other than ESO that is, although I ended up picking it up on sale so I can test it sometime later.

**Comment by Yardanico** [comment]
@schtufbox you can also use blackarch repos for precompiled mingw-w64

**Comment by Thaodan** [comment]
@schtufbox  or use mine: https://thaodan.de/home/bidar/home-thaodan/x86_64/

**Comment by schtufbox** [comment]
Thanks guys, I'm just building a new version of wine-vulkan then I'll give it a go.

**Comment by schtufbox** [comment]
In the end I installed a VM of tumbleweed and compiled from there...test results? 
@doitsujin with the direct-image-mapping build  ESO works flawlessly with the changes you made.
I played for about 5 hours (on and off, not in one sitting!) and noticed no additional issues over the normal branch of DXVK

**Comment by doitsujin** [comment]
Thank you for testing this. This confirms that at least part of the issue was caused by DXVK not checking whether the driver actually supported host-mapped images of a given type.
