### ISSUE TITLE
Ys VIII: Lacrimosa of Dana - Lips don't move during dialogs

### ISSUE THREAD

**Issue by tuxrinku** [doitsujin/dxvk#1601]
During dialogs, the speaking character doesn't move his/her lips. Kinda breaks immersion. Can confirm lips move normally in Windows. I tried with different drivers, Intel or Nvidia, different dxvk versions, nothing helps. I can't manage to launch the game without dxvk, it crashes instantly. To reproduce, just start a new game, it happens at the very first dialog, when Dogi talks to Adol in the ship. Not sure it's a dxvk related issue tho, I can't find anything in the logs.

### Software information
Ys VIII: Lacrimosa of Dana latest update (January 2020). Every settings turned to the max, but the issue is still present with default settings.

### System information
- GPU: Nvidia RTX 2070
- Driver: 440.64
- Wine version: 5.7
- DXVK version: 1.6.1

### Log files
[ys8_d3d11.log](https://github.com/doitsujin/dxvk/files/4544544/ys8_d3d11.log)
[ys8_dxgi.log](https://github.com/doitsujin/dxvk/files/4544545/ys8_dxgi.log)
[wine_log.txt](https://github.com/doitsujin/dxvk/files/4544555/wine_log.txt)

**Comment by Joshua-Ashton** [comment]
Please provide an apitrace.

**Comment by doitsujin** [comment]
Does this happen with DXVK on Windows as well? Asking because animations not working is usually not a rendering issue.

**Comment by tuxrinku** [comment]
Here's the apitrace : https://we.tl/t-g1UEfCXvgW

I'll try dxvk on windows in a while, I'll let you know.
I disabled nvapi, but it didn't change anything.

Thanks for your time
