### ISSUE TITLE
Influence the behavior of DXVK_FILTER_DEVICE_NAME

### ISSUE THREAD

**Issue by plasticbomb1986** [doitsujin/dxvk#1602]
### Software information
For presentation: Call of Duty 2 Single Player (DX9, maximum settings.)

### System information
- GPU0:VEGA64 - connected Display, primary card in vulkan this get GPUid1
- GPU1:VEGA64 - in vulkan this get GPUid0
- Driver: MESA-git (Installed: 20.1.0_devel.122901.b4cc116339f-1)
- Wine version: 5.6-staging (proton-tkg 5.6.1.hotfix.r0.g4c160ec8)
- DXVK version: 1.6.0

### Log files
- d3d9.log:[CoD2SP_s_d3d9.log](https://github.com/doitsujin/dxvk/files/4556290/CoD2SP_s_d3d9.log)
-proton-log:[steam-2630.log](https://github.com/doitsujin/dxvk/files/4556295/steam-2630.log)

 The issue: The two GPu is identical, not counting the primary having the display connected to it. But in vulkan, the primary gpu get GPUid1 isntead of 0, and the secondary get 0 instead of 1, so when the DXVK_FILTER_DEVICE_NAME option looks for VEGA10, it finds both, and chooses 0, what is actually should be 1. However, there is a vulkan layer, to choose by GPUid, and not by name, and it works fine with 64bit games, but its not available for 32bit games, such as CoD2 ( WH40k:Space Marine, SWINE HD Remaster and a lot others). With the DXVK solution the problematic part is: "If the substring matches more than one device, the first device matched will be used."
 What im asking for is an option, to instead of overriding by name and auto id choosing, give a similar option to override it by selecting GPUid right away. Since for checking device name, you need to use vulkaninfo anyway, at the same place you can check for GPUid too.

The mentioned vulkan layer is at: [https://github.com/aejsmith/vkdevicechooser](url)

**Comment by doitsujin** [comment]
Mesa 20.1 is getting a layer similar to vkdevicechooser, and in the meantime, you can use that instead.

I'm not particularly interested in adding this feature to DXVK. The whole feature was added *before* those layers were a thing, and identical GPUs being enumerated in the wrong order isn't really a DXVK issue in the first place.

**Comment by plasticbomb1986** [comment]
> Mesa 20.1 is getting a layer similar to vkdevicechooser, and in the meantime, you can use that instead.
> 
> I'm not particularly interested in adding this feature to DXVK. The device filter was added _before_ those layers were a thing, and identical GPUs being enumerated in the "wrong" order isn't really a DXVK issue in the first place.

Okay, i havent seen that new addition, in this way for sure you are right! Thank you!

**Comment by plasticbomb1986** [comment]
Hi, its me, again!

So yesterday i spent the day to checking it out, and then trying to figure out, how it supposed to work, and why its not working, like, almost et all. The only app what it was sort of working was vulkaninfo, but with games it was off, half off. Could you check in on it too? It might be just me who dont understand something, but...

https://gitlab.freedesktop.org/mesa/mesa/-/issues/2866
