### ISSUE TITLE
[d3d9] Freelancer - dark textures at certain angles (I guess?)

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#1603]
The game runs flawlessly up to a point, but now I get some weird texture flipping to black and back to how it's supposed to be around asteroid stations. It's all I've noticed so far, at least. 

![image](https://user-images.githubusercontent.com/6306593/80999518-7da7db00-8e4d-11ea-98b5-6127729855a8.png)

WineD3D looks fine. 

![image](https://user-images.githubusercontent.com/6306593/80999541-84cee900-8e4d-11ea-9b2a-1b6d8e207b04.png)

Not sure if it's relevant, but I'm passing it through d3d8to9, since it's a dx8 game.

I've played back the trace to see if I managed to capture what I'm seeing in DXVK and it should be pretty conclusive, though I got some error messages during capture.

There are also a ton of ConvertFormat warnings in the logs, though they've always been there without me noticing any graphical glitches. Should I be worried?

### Software information
Freeelancer (retail copy, version 1.1)

### System information
- GPU: GTX 1070
- Driver: 440.82.0
- Wine version: 5.7 Staging
- DXVK version: 1.6.1

### Apitrace file(s)
[freelancer.trace.tar.xz](https://drive.google.com/open?id=1heBMklemyfD1uisPwJLEdvdEuQNmeHMI)

### Log files
- d3d9.log: [freelancer_d3d9.log](https://github.com/doitsujin/dxvk/files/4560091/freelancer_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by Joshua-Ashton** [comment]
Fixed.

**Comment by WinterSnowfall** [comment]
Yey. Indeed, it looks good now. Thanks a lot!
