### ISSUE TITLE
Origin is freezing

### ISSUE THREAD

**Issue by Alllgator343** [doitsujin/dxvk#1604]
Hello! 
I ran "Origin" via "Lutris".
When DXVK enable, games have freezing every two second.
I tried to change version dxvk and add "dxgi.customVendorId = 10DE " in "dxvk.config", but it doesn't help.
[Origin_d3d9.log](https://github.com/doitsujin/dxvk/files/4563749/Origin_d3d9.log)
[Origin_d3d11.log](https://github.com/doitsujin/dxvk/files/4563750/Origin_d3d11.log)
[Origin_dxgi.log](https://github.com/doitsujin/dxvk/files/4563751/Origin_dxgi.log)
[about_system.txt](https://github.com/doitsujin/dxvk/files/4563841/about_system.txt)

**Comment by doitsujin** [comment]
Try disabling D3D9.

**Comment by Alllgator343** [comment]
Even after hours of play? But this happens even when only Origin is running. I know it because my hard disk loaded every two second and i can hear how it happen

**Comment by doitsujin** [comment]
How exactly do you expect me to fix your hard drive problems caused by Origin in DXVK?

**Comment by Alllgator343** [comment]
i don't think the problem is in my hard drive. When i use proton it's normal, when i turn off dxvk in lutris it's the same

**Comment by doitsujin** [comment]
Origin itself does not do any significant amounts of D3D11 rendering.

Just disable DXVK if it doesn't work for you I guess. There's nothing I can fix here, and I never had that problem back in the day when Origin actually *worked* on my system.
