### ISSUE TITLE
[d3d9] Mafia 2 - Mapping memory failed

### ISSUE THREAD

**Issue by hitman249** [doitsujin/dxvk#1605]
### Software information
The game crashes after 10-20 minutes of work  
```
...

mmap() failed: Невозможно выделить память
mmap() failed: Невозможно выделить память
mmap() failed: Невозможно выделить память
mmap() failed: Невозможно выделить память
ALSA lib pcm.c:8526:(snd_pcm_recover) underrun occurred
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED

...

err:   DxvkMemoryAllocator: Memory allocation failed
err:     Size:      4335744
err:     Alignment: 16
err:     Mem flags: 0xe
err:     Mem types: 0xf
err:   Heap 0: 640 MB allocated, 453 MB used, 696 MB allocated (driver), 3387 MB budget (driver), 3840 MB total
err:   Heap 1: 16 MB allocated, 2 MB used, 16 MB allocated (driver), 178 MB budget (driver), 256 MB total
err:   Heap 2: 359 MB allocated, 340 MB used, 383 MB allocated (driver), 4009 MB budget (driver), 4096 MB total
err:   DxvkMemoryAllocator: Memory allocation failed
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
...

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
wine: Assertion failed at address F7F15B49 (thread 003d), starting debugger...
Killed

```

### System information
- GPU: RX 480 4G
- Driver: RADV 20.0.4
- Wine versions: 5.6, 5.7 (standard) \ Proton 5.6 GE-2
- DXVK version: 1.6.1

### Log files
- d3d9.log: [Mafia II.log](https://github.com/doitsujin/dxvk/files/4565300/Mafia.II.log)

**Comment by doitsujin** [comment]
Classic 32-bit out-of-memory issue, see #1318. Use `PROTON_FORCE_LARGE_ADDRESS_AWARE=1`; if that doesn't work, you're sadly out of luck for now.

**Comment by hitman249** [comment]
set
`PROTON_FORCE_LARGE_ADDRESS_AWARE=1`  
`WINE_LARGE_ADDRESS_AWARE=1`

fixed only
`mmap() failed: Невозможно выделить память`

problem still exists
`err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED`

if you switch to d3dx9 then the problem with crashes disappears
also on dxvk at some point the location stops loading and the character falls through the textures

**Comment by hitman249** [comment]
`d3d9.evictManagedOnUnlock = True`
this option fixes the bug
