### ISSUE TITLE
GTA IV HUD BUG

### ISSUE THREAD

**Issue by NikoBellicRU** [doitsujin/dxvk#1608]
There's a bug that when i move the camera to certain angles kinda like a square appears around the HUD but its not constant

GPU:GTX 670
Driver:440.82
Wine version: Proton-5.0-7
DXVK version: 1.6.1

![Screenshot from 2020-05-02 02-15-44](https://user-images.githubusercontent.com/50124155/80851978-c298fb00-8c1c-11ea-9002-973ed02fcc27.png)

![Screenshot from 2020-05-02 02-25-31](https://user-images.githubusercontent.com/50124155/80851982-c88edc00-8c1c-11ea-96d4-4529d3dce964.png)

[steam-12210.log](https://github.com/doitsujin/dxvk/files/4566861/steam-12210.log)

**Comment by jqadev** [comment]
@NikoBellicRU I think that you haven't received feedback because of missing attached apitrace.

**Comment by K0bin** [comment]
I still have a couple of GTA IV apitraces lying around from the last few issues with that game. The PR fixes it.
