### ISSUE TITLE
ESO: weird water reflections

### ISSUE THREAD

**Issue by ssorgatem** [doitsujin/dxvk#161]
With setting above "Low", water reflections in ESO look weird and behave in an unnatural manner.

### System information
- GPU: Vega 56
- Driver: RADV (git)
- Wine version: wine-vulkan
- DXVK version: any

apitrace file: 
https://drive.google.com/open?id=1kF8I2QUashJrbQsYs8r44oZbHw_4Y1Uy

**Comment by ssorgatem** [comment]
I did a video showing it:
https://youtu.be/bC4eZtKqc4c

**Comment by doitsujin** [comment]
I suspect that this happens due to the lack of clipping support in shaders, will try to implement that soon-ish.

**Comment by doitsujin** [comment]
Please re-test with 7f7eedac357e44b4c3e43533882a77295565fb48.

**Comment by ssorgatem** [comment]
Fixed
