### ISSUE TITLE
D3D9: Cannot create texture - Alan Wake crached

### ISSUE THREAD

**Issue by denisoster** [doitsujin/dxvk#1611]
Installed Alan Wake GOG version. For installing using this installer [alan-wake-gog](https://lutris.net/games/install/10036/view)
Open game -> New game -> Watchig video in game -> Crashed game

[lutris-alan-wake.log with error image](https://gist.github.com/denisoster/98fdf518d51aa5f18193bb2a1f686c3e)

cast: @doitsujin @Joshua-Ashton

**Comment by WinterSnowfall** [comment]
I'm not one of the devs, and generally dislike putting words in other people's mouth, but I think they'd appreciate it if people stuck with the issue template they've provided.

That being said, please see [this comment](https://github.com/doitsujin/dxvk/issues/1059#issuecomment-492670404).

Any chance you can test this on something other than a Haswell iGPU? Also, does the problem occur with WineD3D? The last point is particularly important, because if things behave the same with WineD3D, it might just be an issue with Wine, not DXVK.

**Comment by denisoster** [comment]
@WinterSnowfall sorry for not using the template.

I have Intel 4400. Without DXVK game too crahed [lutris-alan-wake-without-dxvk.log](https://gist.github.com/denisoster/04577e5ee2d30230f13ac65e4d6158f0)

**Comment by WinterSnowfall** [comment]
> I have Intel 4400.

Which is a [Haswell iGPU](https://www.notebookcheck.net/Intel-HD-Graphics-4400.91979.0.html), and not really supported, as mentioned by @doitsujin.

I guess you could be hitting #1318. Have you tried setting `WINE_LARGE_ADDRESS_AWARE=1` or using LAA utilities, like the [4GB Patch](https://ntcore.com/?page_id=371)?

It may still not work on your iGPU regardless, but it's worth a shot I guess. That's all I can suggest, I'm afraid. I'll leave you with the experts.

**Comment by Joshua-Ashton** [comment]
Your GPU does not support the required features for this game.

**Comment by denisoster** [comment]
@Joshua-Ashton not supported on wine? 
![image](https://user-images.githubusercontent.com/15886355/80921930-415b7880-8d82-11ea-8218-3bf6dc212017.png)

**Comment by WinterSnowfall** [comment]
@denisoster Not supported by DXVK, because your GPU lacks required Vulkan features.

You can see this in your own logs: `INTEL-MESA: warning: Haswell Vulkan support is incomplete`

It may still be able to work with Wine and WineD3D (OpenGL), but it's not something anyone here can help you fix.

**Comment by denisoster** [comment]
@WinterSnowfall `INTEL-MESA: warning: Haswell Vulkan support is incomplete` this massage I always see. For example DMC: Devil May Cry, Skyrim, Blades Of Time, Life is Strange - working good with dxvk. Therefore, I was surprised that this game does not work
