### ISSUE TITLE
[d3d11] Performance loss

### ISSUE THREAD

**Issue by gadoofou87** [doitsujin/dxvk#1613]
Hey. I noticed a bug that when you save the game, performance drops very much. Before saving, the game runs smoothly and with a good frame rate. Lowering the graphics settings to the bare minimum does not help. I met something similar in Resident Evil 2 Remake.

### Software information
Divinity - Original Sin 2, the problem appears with any graphics settings

### System information
- GPU: GeForce GTX 660
- Driver: 440.82
- Wine version: Wine TkG 5.7
- DXVK version: 1.6.1

### Log files
- d3d11.log: [EoCApp_d3d11.log](https://github.com/doitsujin/dxvk/files/4580074/EoCApp_d3d11.log)
- dxgi.log: [EoCApp_dxgi.log](https://github.com/doitsujin/dxvk/files/4580073/EoCApp_dxgi.log)

![Screenshot_20200504_230242](https://user-images.githubusercontent.com/58735248/81055160-9366e000-8ee1-11ea-9b03-eacd0f567ea0.png)
![Screenshot_20200504_230330](https://user-images.githubusercontent.com/58735248/81055187-9feb3880-8ee1-11ea-93b9-d87dab19ff64.png)

**Comment by doitsujin** [comment]
This is not a bug, it's just that DXVK requires at least 4GB of VRAM to function properly and you only have 2.
