### ISSUE TITLE
[d3d11][dxvk1.6.1] Question about combining with Reshade

### ISSUE THREAD

**Issue by DarknessStorm** [doitsujin/dxvk#1615]
Greetings.
Is there any way to combine dxvk with Reshade dll?
Thx in advance

**Comment by K0bin** [comment]
Install DXVK into your wine prefix and put the Reshade Dll next to the exe of your game. Then make sure you have Microsofts d3dcompiler installed and it should just work.

**Comment by DarknessStorm** [comment]
and if i use windows 10 x64, not linux?

**Comment by K0bin** [comment]
Not possible unless Reshade implements a way to specify which dlls they use internally.

**Comment by Joshua-Ashton** [comment]
I actually PRed that functionality to Reshade @K0bin:

https://github.com/crosire/reshade/pull/164

To answer your question, put the DXVK dlls in a folder somewhere, then set the `RESHADE_MODULE_PATH_OVERRIDE` environment variable to point to that path and use Reshade as normal.

**Comment by DadSchoorse** [comment]
You could also use Reshade in Vulkan mode and use dxvk like always, then you will not need the env var.
