### ISSUE TITLE
[d3d9] Halo 2 Vista sun render bug when AA is enabled

### ISSUE THREAD

**Issue by NukeULater** [doitsujin/dxvk#1616]
### Software information
Halo 2 Vista, High details, ~~AA disabled~~ AA enabled*, 1080p
When looking at the sun it renders as a rectangle/square or at some angles it doesn't render at all, when AA is enabled and using d3d9 to vk wrapper.

[d3d9] :
![image](https://user-images.githubusercontent.com/18323679/81338566-86024f00-90b5-11ea-8ae3-d3534e347274.png)

[d3d9-vk] :
[video](https://youtu.be/Atw7Z0ZfqLs)

### System information
- GPU: GTX 1050
- Driver: 445.87
- Windows version: Windows 10 1909 Build 18363.815
- DXVK version: 1.6.1

### Apitrace file(s)
- [apitrace](https://drive.google.com/open?id=1xzccAwluGQS65lgf3IQHmYvRRfwsUDNn)

### Log files
- d3d9.log: 
[halo2_d3d9.log](https://github.com/doitsujin/dxvk/files/4595378/halo2_d3d9.log)

### Other notes:
- I remember this issue would occur with d3d9 as well if FXAA was enabled in NVIDIA control panel.
Now I can't reproduce it anymore, maybe it got fixed in the meantime?
- With the ApiTrace dlls, the problem does not occur

### UPDATE:
* Nevermind, it seems like i had AA enabled in-game, and it is causing this issue.

**Comment by Joshua-Ashton** [comment]
Please re-test this on latest master.

https://git.froggi.es/doitsujin/dxvk/-/jobs

**Comment by NukeULater** [comment]
> 
> 
> Please re-test this on latest master.
> 
> https://git.froggi.es/doitsujin/dxvk/-/jobs

Issue is still present with [this build](https://git.froggi.es/doitsujin/dxvk/-/jobs/1281).

**Comment by jqadev** [comment]
@Joshua-Ashton is it dependent on VK_EXT_custom_border_color extension?

**Comment by NukeULater** [comment]
Seems fixed with [this latest build](https://git.froggi.es/doitsujin/dxvk/-/commit/4e1ee5bf399a10993d68da5f57d5c74b0235c808).
