### ISSUE TITLE
Proper fix for Scrap Mechanic

### ISSUE THREAD

**Issue by ZakBR** [doitsujin/dxvk#1621]
Hi, Scrap Mechanic still doesn't load properly. I've seen your DX11 fix but wasn't able to apply it. Is there a patch I could run to fix it? Thank you.

**Comment by Iglu47** [comment]
@ZakBR the game does not start even with wined3d now
but you can use wine with old ntdll
for example: https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/5.2-GE-2
![scrap_mech](https://user-images.githubusercontent.com/25866099/81491513-02ed1e80-9298-11ea-9567-3264b84e99b9.png)

**Comment by ZakBR** [comment]
@Iglu47 Hi Dmitry, thank you for replying! I'm using windows, should I download these, extract and run something? I cant find any .exe files in those files.

**Comment by Iglu47** [comment]
i check on master, works fine for me

my spec
- nvidia proprietary driver: 440.82; gtx nvidia 1080ti
- arch linux, liquorix-5.6.11-2
- https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/5.2-GE-2
- dxvk 1.6.1-63-g e7455b6460b9dbfc5ae20e5d829b55f3d796c0cf

[ScrapMechanic_d3d11.log](https://github.com/doitsujin/dxvk/files/4605253/ScrapMechanic_d3d11.log)

**Comment by ZakBR** [comment]
How would you use that in windows?

**Comment by Iglu47** [comment]
@ZakBR https://github.com/doitsujin/dxvk/releases
> Copy DLLs to the directory where the game's executables are, done. 

should be _path-to_\Scrap Mechanic\Release\d3d11.dll (use x32)

also can use "User Environment Variables" 
for example `DXVK_HUD`=`fps,frametimes,compiler,version` 
(full list: https://github.com/doitsujin/dxvk#hud)

**Comment by K0bin** [comment]
You also need to copy dxgi.dll on Windows.

**Comment by ZakBR** [comment]
@K0bin Thank you for your reply. I'm trying to run Scrap Mechanic but it's not loading no matter what. I have a pretty powerful rig, it's something related to DirectX.

**Comment by K0bin** [comment]
So it doesn't work with your normal D3D11 driver? What GPU do you have anyway?

> but it's not loading no matter what

> it's something related to DirectX

That's not helpful at all. Is that with or without DXVK?

**Comment by ZakBR** [comment]
@K0bin Yes, it won't work with my Directx 11 or 12. I'm using windows 10 64 with a Geforce 2080ti from EVGA. Game loads and crashes before the Axolot logo.

There is a long discussion about it here:
https://steamcommunity.com/app/387990/discussions/0/152393186503184409/?ctp=40

**Comment by doitsujin** [comment]
If the game doesn't work on your Windows even *without* DXVK, you probably need to fix your Windows setup.
