### ISSUE TITLE
Assassin's Creed Odyssey hanging on Windows

### ISSUE THREAD

**Issue by PKBeam** [doitsujin/dxvk#1623]
After a certain period of time the game will hang and boot me back out to the desktop.
Sound still plays but the application is not responsive and I have to force quit it.

I don't get these crashes without DXVK.

### System information
- GPU: Radeon RX 5700 XT
- Driver: Adrenalin 20.4.2
- Wine version: N/A 
- DXVK version: 1.6.1

### Apitrace file(s)
(I tried running an apitrace but this caused the game to run unplayably slow.)

### Log files
- d3d11.log: [ACOdyssey_d3d11.log](https://github.com/doitsujin/dxvk/files/4607984/ACOdyssey_d3d11.log)
- dxgi.log: [ACOdyssey_dxgi.log](https://github.com/doitsujin/dxvk/files/4607985/ACOdyssey_dxgi.log)

Thanks for taking the time to view this!

**Comment by doitsujin** [comment]
> err:   DxvkSubmissionQueue: Command submission failed: VK_ERROR_DEVICE_LOST

Sounds like a driver bug or unstable overclock.

**Comment by dominik1411** [comment]
The same error comes up for me too with a 1080 Ti, latest nvidia driver and dxvk 1.7.
This also occours randomly for me even with a hefty gpu underclock.
