### ISSUE TITLE
[d3d11] - Cloudpunk (746850) - Low performance on Nvidia hardware.

### ISSUE THREAD

**Issue by ZereoX** [doitsujin/dxvk#1624]
### Description:
In **_Cloudpunk_** (746850), our Nvidia hardware sees incredibly low and stuttery performance (<10 FPS) when driving around. When idle or when looking at a wall, the framerate will eventually return to normal, but upon resuming your route, the performance almost instantly drops below playable. This occurs on both Proton and Windows.

Video: https://www.youtube.com/watch?v=eRoNZAHX9Oo

Inversely this behavior is not observed on AMD (Mesa / RADV), nor is it seen on either platforms when using WineD3D (PROTON_USE_WINED3D=1 %command%).

We've confirmed the issue persist with either DXVK or Wine's DXGI as well as when attempting to spoof an AMD GPU using DXVK's config options.

Please let me know if any additional information is required or if additional testing is needed.

### Software information
[Cloudpunk](https://store.steampowered.com/app/746850/Cloudpunk/) (746850)

### System information
OS: Ubuntu 18.04.4 / Windows 10 Pro 1909
GPU: Radeon RX 580 / Nvidia GeForce GTX 1060
Driver: 20.0.6\~kisak1\~b / 440.82-0ubuntu0~0.18.04.1
Wine version: Proton 5.0-7
DXVK version: 1.6.1 / Master (aa0b306d)

### Apitrace file(s)
- https://drive.google.com/open?id=1JXnEdXXOndKQWHK-pcDRFh8xjCOqUHkK

### Log files
d3d11.log: [Cloudpunk_d3d11.log](https://github.com/doitsujin/dxvk/files/4610653/Cloudpunk_d3d11.log)
dxgi.log: [Cloudpunk_dxgi.log](https://github.com/doitsujin/dxvk/files/4610654/Cloudpunk_dxgi.log)

### Notes
Several users on [ProtonDB](https://www.protondb.com/app/746850) have also made mention of this, all of which are also on Nvidia hardware. The two user reports from AMD make no mention of performance issues.

### Tested froggi.es builds:
master - aa0b306d (❌)
1.6.1 - dbc9f40a (❌)
1.6 - 9c7945d9 (❌)
1.5.5 - 1e426cdb (❌)
1.5.4 - 2435c636 (❌)
1.5.3 - 6a5d472e (❌)

**Comment by Evernow** [comment]
I can confirm that when I had a Navi GPU (gave up, the drivers are terrible) I could play this game with no performance issues. 

I got a RTX 2060S and I can also play this game now with no performance issues on Manjaro, where do the performance issues occur? According to the report on Steam it occurs anywhere, but I played for ~30 minutes and I had no performance issues, a steady 70fps.

**Comment by doitsujin** [comment]
I'm aware of this, but haven't been able to reproduce this so far, and considering that this works fine on AMD it's probably the driver hitting a pathological path somewhere. DXVK generally does more or less the same things for both vendors, at least on modern GPUs.

**Comment by doitsujin** [comment]
I fixed the validation errors in latest `master`, but that isn't going to improve performance.

@ZereoX any chance the game is running out of VRAM and allocating stuff in sysmem instead? When enabling `DXVK_HUD=memory`, "Sysmem heap 0" should ideally not show more than ~100MB.

That said, 6GB should be *more* than enough for this game.

**Comment by ZereoX** [comment]
Hi @doitsujin,

I ran the latest master w/ `DXVK_HUD=memory` and 'Sysmem' remained in the ~100MB range.

|Sysmem heap 1|
| ---- |
|![Screenshot from 2020-05-12 07-13-01](https://user-images.githubusercontent.com/761853/81680325-f3e5a800-9420-11ea-8275-a241c827122c.png)|

**Comment by doitsujin** [comment]
No idea what's going on then, probably needs to be looked at from the driver side.

**Comment by CME42** [comment]
@ZereoX Do you have any browsers open while playing the game? if so, can you try to close all of them before starting the game?

**Comment by ZereoX** [comment]
Hi @CME42, we tested the game on 2 identical configurations both were seeing the issue while having nothing other than Steam open in the background. The same was also true when we reproduced the issue on Windows. In comparison, these same configurations with an RX 580 did not see any obvious performance troubles when playing the game.

Here is a system report for one of them (I should have included this before. Sorry): 
[[GeForce GTX 1060 6GB][Intel(R) Core(TM) i5-8600 CPU] - SystemReport.zip](https://github.com/doitsujin/dxvk/files/4633994/GeForce.GTX.1060.6GB.Intel.R.Core.TM.i5-8600.CPU.-.SystemReport.zip)

Windows was tested on Nvidia driver 445.87.

**Comment by TjReiny** [comment]
well a few things i did observe on that screenshot: Latest GPU driver is not used, that Framerate graph tolds that its have some serius problems? does not look that nice.

**Comment by doitsujin** [comment]
FWIW I now have an RTX 2060 laptop to play around with and wasn't able to reproduce the issue there, even after ~15 minutes of driving around aimlessly.

**Comment by CME42** [comment]
I've just finished the game on my 1060 and only had this problem in 2 occasions, in one the nvidia xorg driver was eating quite a lot of cpu, but i could never repro this again, the other time i was genuinely running out of videoram because i had too much stuff running in the background. I'm using the latest vulkan beta driver, though.

**Comment by ZereoX** [comment]
@doitsujin I finally managed to get 440.66.14 installed and can confirm that the driver is indeed the cause of the issue. I also confirmed the Vulkan beta driver resolve the issue on Windows as well.

###### Linux:
|440.82.0|440.66.14|
| ---- | ---- |
|![Screenshot from 2020-05-12 07-13-01](https://user-images.githubusercontent.com/761853/81680325-f3e5a800-9420-11ea-8275-a241c827122c.png)|![Screenshot from 2020-05-20 15-06-45](https://user-images.githubusercontent.com/761853/82487343-3efc5c80-9aac-11ea-94dc-96439ea87356.png)|

###### Windows:
|445.87|443.15|
| ---- | ---- |
| ❌ | ✔️ |

**Comment by TjReiny** [comment]
500 points for me on that case, driver issue. GG

**Comment by AlexP11223** [comment]
440.100 driver, GTX 1080, 9900k, PopOS 20.04
Completely unplayable, constantly drops to 5-10 fps. Settings Culling Prediction to 50% did not help.
WineD3D is better, but still some stutters when moving and 30-45 fps (1440p, High settings).

**Comment by ZereoX** [comment]
@AlexP11223 although the versioning on your driver is higher, Nvidia's beta Vulkan driver lives in a seperate branch from the stable release. That driver is available here: https://developer.nvidia.com/vulkan-driver

**Comment by AlexP11223** [comment]
oh, is there any easy way to install it on PopOS/Ubuntu? :)

**Comment by ZereoX** [comment]
Unfortunately there isn't an easy way that I'm aware of similar to using a PPA that is available for those drivers. Using the .run file included in the link above is the only way (that I know).
