### ISSUE TITLE
Performance issues with all DX9 games

### ISSUE THREAD

**Issue by Ahmed-E-86** [doitsujin/dxvk#1627]
When I used D9VK at its early stages the performance was so low, and it is still the same till now. That happens with every DX9 that I used D9VK/DXVK with.

**You can tell the difference between these 2 pictures**

### Half Life 2 (DXVK)

![DXVK](https://user-images.githubusercontent.com/29783425/81831315-7ebbc500-953d-11ea-914f-7df69a59fa3f.png)

### Half Life 2 (wined3d)

![wined3d](https://user-images.githubusercontent.com/29783425/81831297-795e7a80-953d-11ea-9b43-f07edb4c5f97.png)

### System information
- GPU: AMD Radeon HD 8750M
- Driver: Mesa 20.0.6
- Wine version: 5.8 - staging
- DXVK version: 1.6.1

**Comment by doitsujin** [comment]
Yes, we are aware that DXVK doesn't run well on your horrendously outdated mobile hardware that isn't particularly strong to begin with, it works fine on pretty much everything else, and there's really not an awful lot we can or even want to do here.

**Comment by Ahmed-E-86** [comment]
> horrendously outdated mobile hardware

Don't insult my laptop.... It has been a good servant for years, and will be until I say otherwise. Anyway, DX9 games are older than my `horrendously outdated mobile hardware`, and they should run just fine, so don't blame my laptop for your unwillingness to help. I will just use `Gallium9`.

**Comment by bno1** [comment]
I don't want to start an argument, but the 8750m has been released in 2013. Vulkan has been first announced in 2015.

**Comment by Ahmed-E-86** [comment]
> I don't want to start an argument, but the 8750m has been released in 2013. Vulkan has been first announced in 2015.

I thought it was released in 2015. Anyway, I am going to get a new laptop soon, but it is going to be AMD Rayzen APU with no dGPU. I hope it doesn't suck also with DXVK.

**Comment by doitsujin** [comment]
The problem here is that you keep making pretty useless bug reports on hardware that no one else uses and would be pretty much impossible to get these says, and could be slow due to all sorts of reasons, including the driver.

> but it is going to be AMD Rayzen APU with no dGPU. I hope it doesn't suck also with DXVK.

Some (most?) D3D9 games are known to run poorly on APUs, we already know that much. We don't know *why* though. D3D11 should be fine.

**Comment by Ahmed-E-86** [comment]
> Some (most?) D3D9 games are known to run poorly on APUs, we already know that much. We don't know why though. D3D11 should be fine.

That makes it hard to use DXVK for DX9 games even after upgrading my laptop. Would you consider adding an option to install DXVK without d3d9.dll? That will be useful also for people who prefer to use `Gallium9`.

**Comment by TjReiny** [comment]
lol thats just big rofl, ye ur GPU can handle simple/medium d9 titles but, can it Handle Vulkan propetly? thats real required for DXVK, while on ur outdated Hardware it seems to work awefull, i can Report that on my i5-7300HQ and Nvidia1060 it works fine with better perfomance then dx9 on my setup most of it due to better utilization and lower overhead. My guess, better be happy DXVK even runs on that gpu instead of flame that on DXVK.

**Comment by Ahmed-E-86** [comment]
I can play any native Vulkan games without any issues on my outdated GPU that everyone gives me a hard time for using it. It is a laptop, I can't just remove the GPU, and get a new one. I need to change the whole laptop. 

Anyway, I found something that can translate DX9 to DX11, and it gives much better performance. My only request is to have any option to install DXVK without d3d9, something like:
`./setup_dxvk.sh install --without-d3d9`

**Comment by DeeDeeRanged** [comment]
That option is already there. Put a # (hash) before $action d3d9 near the bottom in the setup_dxvk.sh script. Simple as that
Cheers

**Comment by Ahmed-E-86** [comment]
@DeeDeeRanged Thanks.

**Comment by Randalmcdaniel** [comment]
Thats a bit rude, i've tried using DXVK tool across like 40 different games and it's never fixed a single one. The only game its ever fixed is GTA4 and that no longer works with DXVK tool. So what is it that you are you even updating dojitsun? You suck.

**Comment by K0bin** [comment]
DXVK isn't supposed to "fix" D3D9 games. It's supposed to make them work on Linux.
