### ISSUE TITLE
Heroes of The Storm - stuttering during gameplay

### ISSUE THREAD

**Issue by byakku** [doitsujin/dxvk#1629]
**Problem**: During gameplay if there is a graphical effect like spell casted, bleed effect or anything "new", game drops FPS drastically making the gameplay really awful.

Recording:
https://www.youtube.com/watch?v=iyc2A5KV8d8&feature=youtu.be

### Software information
Heroes of The Storm, High/Ultra settings, changing values does not affect the problem

### System information
- **GPU**: NVIDIA GTX 1080 Founders
- **Driver**: 440.82
- **Wine version**: lutris-5.6.2-x86_64
- **DXVK version**: 1.6.1L

Ryzen 7 1700 and 24GB RAM, HW is not the issue of course.

### Apitrace file(s)
Couldn't make it work with the game. I tried on different exe (World of Warcraft WOTKL) just to make it work and then copy setup to HOTS but couldn't make it work. Attached DXVK debug logs tho.

Copied lib to `~/Games/wow335a/lib` and bin contents to root exe folder of wow.
`wine ~/Games/wow335a/apitrace.exe trace -a dxgi ~/Games/wow335a/Wow_o.exe`
```
error: failed to find dxgitrace.dll wrapper (rerun with -v option for more details)
002c:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000022FA90
```

If you have howto for Lutris (as I run game through that) I can retry getting api trace.

### Log files
Exported with:
DXVK_HUD=full
DXVK_LOG_LEVEL=debug
VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation

HeroesOfTheStorm_x64_d3d11.log (**30MB**)
https://www94.zippyshare.com/v/R1jFhZ42/file.html

[Agent_dxgi.log](https://github.com/doitsujin/dxvk/files/4636191/Agent_dxgi.log)
[HeroesOfTheStorm_x64_dxgi.log](https://github.com/doitsujin/dxvk/files/4636192/HeroesOfTheStorm_x64_dxgi.log)
[Agent_dxgi.log](https://github.com/doitsujin/dxvk/files/4636182/Agent_dxgi.log)

**Comment by doitsujin** [comment]
Not a bug, just the regular shader compiler stutter that you're always going to have with DXVK.
