### ISSUE TITLE
wargaming game center black screen when NOT using apitrace

### ISSUE THREAD

**Issue by JAicewizard** [doitsujin/dxvk#1630]
When launching the wargaming game center using DXVK it gives a black screen. A similair issue exists with [directx-d3d](https://bugs.winehq.org/show_bug.cgi?id=48618). For most people using dxvk is a propper workaround, but I got `X11DRV_vkCreateWin32SurfaceKHR Failed to allocate client window`.

I really really tried hard to get an APItrace for you there is just one problem.
When using apitrace it works.
`wine ~/.wineWot/drive_c/ProgramData/Wargaming.net/GameCenter/wgc.exe` black screen.
https://pastebin.com/Bz4myJ50

`wine ~/Downloads/apitrace-latest-win32/bin/apitrace.exe trace -a dxgi ~/.wineWot/drive_c/ProgramData/Wargaming.net/GameCenter/wgc.exe` no black screen.
https://pastebin.com/VZ5LJBL7

### Software information
wargaming game center no settings available

### System information
- GPU: rx 580
- Driver: AMD RADV POLARIS10 (LLVM 10.0.0)
- Wine version: 5.8
- DXVK version: 1.6.1

### Apitrace file(s)
https://pastebin.com/VZ5LJBL7 note that with apitrace the issue doesnt happen. 

### Log files
Maybe im not getting the point but the instructions say that I should use apitrace for this? I already posted the apitrace log.
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by doitsujin** [comment]
Works fine for me.

**Comment by JAicewizard** [comment]
what do you mean disable dxvk dll overrides for wgc.exe? Do you mean uninstall dxvk?
The related issue I linked is a very similar issue in directx-d3d so that is not going to work.
In tat issue it is saaid using dxvk fixes it for a lot of people.
the most interesting thing I noticed is that while using apitrace everything works perfectlly fine. Do you have any idea why that might happpen?

**Comment by doitsujin** [comment]
What is "directx-d3d"? Do you mean wined3d (the OpenGL-based translation)?

Again, please test if it works with wine-staging. No idea why it wouldn't work for you.

**Comment by JAicewizard** [comment]
uuh yes, directx-d3d is what its called on the wine Bugzilla.
I tested with staging, again that also works with apitrace enabled but not without.
Ill head back to wine bugzilla to see is anyone there can reproduce this "workaround".
