### ISSUE TITLE
[d3d9] Serious Sam 2: Water reflections render incorrectly

### ISSUE THREAD

**Issue by ryester27** [doitsujin/dxvk#1637]
### Software information
Serious Sam 2
Arch Linux

### System information
- GPU: AMD RX 560
- Driver: Mesa 20.0.7 / LLVM 10.0.0
- Wine version: Proton 5.0-7
- DXVK version: 1.6-69-g5f4f92002

### Apitrace file(s)
https://mega.nz/file/7wxliAIR#KC1Q8H1-5EtRhe-cb3cdqR94__zthkgUN0HZwAzsLOw

### Log files
[steam-204340.log](https://github.com/doitsujin/dxvk/files/4665538/steam-204340.log)

----------------------------------------

Water reflections appear to render incorrectly depending on the angle and distance that you're looking at them. If you get the camera in the right spot, you can see some other object in the world be reflected, instead of the normal water reflection. Not able to reproduce with WineD3D.

**DXVK**
![Screenshot_20200521_204743](https://user-images.githubusercontent.com/17807258/82621311-c929eb00-9ba8-11ea-9eba-76bf0faf6ef7.png)

**WineD3D**
![Screenshot_20200521_204959](https://user-images.githubusercontent.com/17807258/82621410-1017e080-9ba9-11ea-89b8-23c0ae0aef7d.png)

**Comment by Joshua-Ashton** [comment]
Should be fixed by https://github.com/doitsujin/dxvk/pull/1638 when it gets merged :)
