### ISSUE TITLE
[d3d9] Duke Nukem Forever → The shadows are in the form of squares

### ISSUE THREAD

**Issue by NerosTie** [doitsujin/dxvk#1639]
With dxvk:
![Screenshot_20200523_163547](https://user-images.githubusercontent.com/4572452/82735449-2d23ef00-9d22-11ea-97fd-deb86465571d.png)

gif: https://imgur.com/i7iNe5r

With wined3d:
![Screenshot_20200523_163426](https://user-images.githubusercontent.com/4572452/82735454-3614c080-9d22-11ea-8979-31e35a429ba4.png)

### System information
- GPU: Nvidia GeForce GT 730M
- Driver: nvidia-vulkan 440.66.14
- Wine version: Proton 5.0
- DXVK version: 1.7

### Apitrace file(s)
https://mega.nz/file/KyZ2wAwb#XoZ5Xo-4sCmhcgtkDpSGMdzyEUOShW-89knhkYt-bLQ

### Log files
[steam-57900--dxvk.log](https://github.com/doitsujin/dxvk/files/4672107/steam-57900--dxvk.log)
[steam-57900-wined3d.log](https://github.com/doitsujin/dxvk/files/4672108/steam-57900-wined3d.log)

**Comment by Joshua-Ashton** [comment]
I can't replicate this on my machine on the trace. Can you record a trace with DXVK? Thanks

**Comment by NerosTie** [comment]
Weird... can we suspect an issue with the Nvidia driver?

Trace with DXVK:
https://mega.nz/file/7rQCFIiB#oqudmWzeMiWKpbR3GuJERHtUHDgboJW_AG24rCiatf4

**Comment by Joshua-Ashton** [comment]
I tested on Nvidia as well. I shall look at the DXVK trace later.

**Comment by CME42** [comment]
The game is using DF24 with dxvk which seems to be broken (the dxvk trace is working fine on intel d3d9 where DF24 is supported).
Can you try d3d9.supportDFFormats = False in the dxvk.conf?

**Comment by NerosTie** [comment]
Yes, it fixes the issue :)

**Comment by Joshua-Ashton** [comment]
Should be fixed by this: https://github.com/doitsujin/dxvk/commit/8fdf9e67d39b332999e08318c87befa315f17679

Can you please test! Thanks!

**Comment by NerosTie** [comment]
It's fixed! Thanks :)
