### ISSUE TITLE
need for speed most wanted 2012:trail of green rims with light 

### ISSUE THREAD

**Issue by Eignar17** [doitsujin/dxvk#164]
Maybe that error is the problem:
DxgiOutput::GetGammaControlCapabilities: Not implemented

### Software information
need for speed most wanted 2012

### System information
- GPU:Geforce GTX 1050
- Driver:390.25
- Wine version:  2.21-staging
- DXVK version: 1bfd37a

### Apitrace file(s)
Not possible 

### Log files
- d3d11.log:[d3d11.log](https://github.com/doitsujin/dxvk/files/1814174/d3d11.log)
- dxgi.log: [dxgi.log](https://github.com/doitsujin/dxvk/files/1814175/dxgi.log)

![pantallazo-2018-03-15 01-13-58](https://user-images.githubusercontent.com/8561550/37447312-92e91cd4-27ef-11e8-89ab-726248cd45c5.png)

**Comment by mmtrt** [comment]
Game is crashing upon starting and without dxvk game works but everything is black ingame however when I tested this under windows with dxvk I had above same issue with trees glowing like trail on road.

DXVK version: 4ce64bd8865bbb25baa25d622437c9258126c4d2
WINE version: wine-3.4-96-gf2cb86decb (Staging)
Driver: 390.42

could not get complete trace game crashed on nfs mw logo shows when tracing.

hope this helps
[nfs13.trace.7z](https://mega.nz/#!s0MhnKqa!VbUsy_NaVude-kO_jgGEBFgHaukwZvRo1uPhSXB9Jag)

log is from linux test run crash

[NFS13_d3d11.log](https://github.com/doitsujin/dxvk/files/1844020/NFS13_d3d11.log)
[NFS13_dxgi.log](https://github.com/doitsujin/dxvk/files/1844021/NFS13_dxgi.log)
[terminal.log](https://github.com/doitsujin/dxvk/files/1844022/terminal.log)
[trace.log](https://github.com/doitsujin/dxvk/files/1844030/trace.log)

**Comment by Yardanico** [comment]
@mmtrt works for me on Arch Linux with nvidia proprietary driver

**Comment by Eignar17** [comment]
@doitsujin is fix problem on trace for @mmtrt

**Comment by Eignar17** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ff476520(v=vs.85).aspx

**Comment by mmtrt** [comment]
New test

* wine: 3.6 staging
* dxvk: 320cebb8f975434d46ab91987108fe86742ee9a6

game is stuck on black screen then crashes

logspam
`err:   DxvkSwapchain::recreateSwapchain: Failed to recreate swap chain`

[NFS13_d3d11.log](https://github.com/doitsujin/dxvk/files/1910423/NFS13_d3d11.log)
[NFS13_dxgi.log](https://github.com/doitsujin/dxvk/files/1910424/NFS13_dxgi.log)

**Comment by Eignar17** [comment]
update to Nvidia Driver:396.18.07 fix error
