### ISSUE TITLE
[d3d9] TrackMania United Forever crashes Wine after a recent commit

### ISSUE THREAD

**Issue by ThisNameIsntTaken** [doitsujin/dxvk#1640]
As of 8fdf9e6, TrackMania United Forever seems to crash Wine during starup. I was not able to reproduce this issue on Windows.

### Software information
TrackMania United Forever with shader quality set higher than "PC2".

### System information
- GPU: RX 580 4GB
- Driver: RADV Git + ACO
- Wine version: TkG-5.9
- DXVK version: 4e1ee5b

### Apitrace file(s)
- [Trace](https://drive.google.com/open?id=1Ucgaz-1DIouXWL5890I-6FSzjVBi_0i6) from [here](https://github.com/doitsujin/dxvk/issues/1376#issuecomment-579337088).

### Log files
- [TmForever_d3d9.log](https://github.com/doitsujin/dxvk/files/4675807/TmForever_d3d9.log)
- [wine_output.txt](https://github.com/doitsujin/dxvk/files/4675876/wine_output.txt)

**Comment by Joshua-Ashton** [comment]
Please re-test on latest master.

**Comment by ThisNameIsntTaken** [comment]
Works fine now, thanks!
