### ISSUE TITLE
[d3d9] TrackMania United Forever - Minor rendering issue with electric signs

### ISSUE THREAD

**Issue by ThisNameIsntTaken** [doitsujin/dxvk#1642]
While I was looking at yesterday's crash issue, I found a minor rendering issue on electric signs I didn't notice before. This problem only seems to be present when you are far away from the sign.
Not quite sure how to describe it, so here's an image instead:
![dxvk](https://user-images.githubusercontent.com/44706448/82892428-b704cf80-9f4f-11ea-836b-39bd26bc19d7.png)
It's supposed to look like this:
![native](https://user-images.githubusercontent.com/44706448/82892493-dac81580-9f4f-11ea-963d-d8cd470b6a07.png)

I've tried several DXVK/D9VK versions and it doesn't seem to be a regression.

### Software information
TrackMania United Forever

### System information
- GPU: RX 580 4GB
- Driver: RADV Git + ACO
- Wine version: TkG-5.9
- DXVK version: 67b1ee4

### Apitrace file(s)
- [TmForever.trace.tar.xz](https://mega.nz/file/N0wizKZJ#3D-sn7lQOOOEqQtL-B3Wa_koAxiVdvvsjQZEE_eNCBo)

### Log files
- [TmForever_d3d9.log](https://github.com/doitsujin/dxvk/files/4681699/TmForever_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Should be fixed now :)

**Comment by ThisNameIsntTaken** [comment]
Yep, it's fixed, however, the fix causes the water reflections to be rendered incorrectly.

Before the fix, the water looked normal:
![18](https://user-images.githubusercontent.com/44706448/82914177-77e67680-9f6f-11ea-8694-b1716ab690ad.png)
After a35df1c3b1ddae7fe66583764a561b0a8478637e, it looked like this:
![19](https://user-images.githubusercontent.com/44706448/82914270-964c7200-9f6f-11ea-9194-fb12524c960a.png)
4c1deabcd30cafadae8fbe3270d42f22552917f6 and b958473cc9117780f3846ea40b6358c69083a39c looks like this:
![21](https://user-images.githubusercontent.com/44706448/82914343-af552300-9f6f-11ea-943b-4a1f6f5af024.png)

It should be visible in the trace.

**Comment by Joshua-Ashton** [comment]
Should be fixed now.

**Comment by ThisNameIsntTaken** [comment]
The trace plays fine now. Unfortunately, for some weird reason, the water is still rendered incorrectly ingame. I've made [another trace](https://mega.nz/file/RkATkQoL#0NzokbSz879JKkAvdk7H5Tw9nN4NT_3PBgehapFFRZI), but this time with DXVK. Not sure how useful will that be.

Thank you for looking into this, I know that issues like this are super annoying.

**Comment by Joshua-Ashton** [comment]
Should be fixed fixed now... :frog:

**Comment by ThisNameIsntTaken** [comment]
That did the trick. Thanks!
