### ISSUE TITLE
Compiling shaders early instead of at draw time

### ISSUE THREAD

**Issue by ShabbyX** [doitsujin/dxvk#1646]
I recently learned that dxvk compiles shaders at draw time ([this][1] confirms it). We use to do the same in ANGLE, and I can understand why dxvk would choose to do that.

A while back however, I solved this issue in ANGLE by compiling the shaders at (GL) link time and applying a simple SPIR-V transformation on draw if necessary. dxvk could do the same, which should help reduce the stuttering in some games (VkPipelines are still created at draw time, especially because some internal push constants can only be determined at run time, but it's always possible to compile "the most common" setting at link time and hope for a hit). I intend to move the compilation to (GL) compile time even (which is currently not done because the transform feedback code is generated in GLSL at link time, but that could also be done on SPIR-V directly).

You can take a look [here (see SpirvTransformer)][2] for inspiration.

[1]: https://github.com/doitsujin/dxvk/blob/4fff2343c12f81430d6fd397dc32526ec0537121/src/dxvk/dxvk_shader.h#L308
[2]: https://source.chromium.org/chromium/chromium/src/+/master:third_party/angle/src/libANGLE/renderer/glslang_wrapper_utils.cpp;drc=d89dac6910da75123dce203e3e60eb76eef54b38;bpv=0;bpt=1;l=976

**Comment by Joshua-Ashton** [comment]
We don't use glsl shaders **at all**. We generate SPIR-V directly from DXBC then apply our own transformations if per-say, we need to handle mismatched input layouts or in d3d9, enable flat shading.

**Comment by doitsujin** [comment]
DXVK already does exactly what you propose. The DXBC->SPIR-V translation ha1ppens at `Create{Vertex,Pixel,...}Shader`, at draw time we only fix up binding numbers in SPIR-V etc and create the VkPipeline. Thing is, shaders in shipping D3D11 games are often so complex that drivers take up to several hundred milliseconds to compile all of that to the respective machine code.

**Comment by ShabbyX** [comment]
Excellent, just wanted to make sure this opportunity is not missed.
