### ISSUE TITLE
[d3d9] Anomaly: Warzone Earth (91200) - Title hangs upon reaching the main menu.

### ISSUE THREAD

**Issue by ZereoX** [doitsujin/dxvk#1650]
### Description:
This was reported by a user on the Proton Issue Tracker: https://github.com/ValveSoftware/Proton/issues/3836#issue-613605003

In **_Anomaly: Warzone Earth_** (91200) the game will hang on the very first frame of the main menu (The title normally swoops in from the right). Audio can still be heard, but rendering stops.

This issue occurs on both Proton 5.0-7 and Windows using DXVK 1.7 or master (5558460). Issue is not present on WineD3D or Native Windows D3D.

| DXVK | WineD3D / Native |
| ---- | ---- |
|![Anomaly Warzone Earth - 91200 - DXVK](https://user-images.githubusercontent.com/761853/83662722-e80b8280-a595-11ea-8845-bdbba8f81c63.png)|![Anomaly Warzone Earth - 91200 - WineD3D](https://user-images.githubusercontent.com/761853/83662738-eb9f0980-a595-11ea-9abc-aa477c642af1.png)|

Please let me know if any additional information is required or if additional testing is needed.

#### Notes
- I've attached an Apitrace, but it appears to be broken and does not playback correctly.
- Wine crashes with an "Unhandled division by zero" error.

### Software information
[Anomaly: Warzone Earth](https://store.steampowered.com/app/91200/Anomaly_Warzone_Earth/) (91200)

### System information
OS: Ubuntu 18.04 / Windows 10 Pro 1909
GPU: Radeon RX 580 / Nvidia GeForce GTX 1060
Beta Drivers: 20.2\~git2006031102.30a393\~oibaf\~e / 440.66.15 (443.24 for Windows)
Stable Drivers: 20.0.7\~kisak1\~b / 440.82-0ubuntu0~0.18.04.2 (446.14 for Windows)
Wine version: Proton 5.0-7
DXVK version: 1.7 / Master (5558460)

### Apitrace file
- Link: https://drive.google.com/file/d/1-Ttvg93-xknbshkbN6GcfZmErmfHzV2G/view?usp=sharing

### Log files
d3d9.log: [AnomalyWarzoneEarth_d3d9.log](https://github.com/doitsujin/dxvk/files/4724735/AnomalyWarzoneEarth_d3d9.log)

> warn:  D3D9InterfaceEx::QueryInterface: Unknown interface query
> warn:  02177241-69fc-400c-8ff1-93a44df6861d
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_MULTISAMPLEANTIALIAS
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_CLIPPING

### Tested froggi.es builds:
master - 5558460 (❌) - [#1309](https://git.froggi.es/doitsujin/dxvk/-/jobs/1309)
1.7 - 2e37825 (❌) - [#1286](https://git.froggi.es/doitsujin/dxvk/-/jobs/1286)
1.6.1 - dbc9f40 (❌) - [#1261](https://git.froggi.es/doitsujin/dxvk/-/jobs/1261)
1.5.5 - 1e426cd (❌) - [#1178](https://git.froggi.es/doitsujin/dxvk/-/jobs/1178)
1.5.0 - 3cdae3a (❌) - [#1044](https://git.froggi.es/doitsujin/dxvk/-/jobs/1044)

**Comment by WinterSnowfall** [comment]
Just FYI, with **Wine Staging 5.9**, the game crashes for me with an `Unhandled exception: divide by zero in 32-bit code` when it reaches the main menu even without DXVK (in WineD3D).

**Comment by jrugia** [comment]
I can confirm the same issue on my end. Like @ZereoX I can hear the sound playing, move the cursor but rendering stops. Can also confirm it works fine with WineD3D, played first mission no issues.

Being a 32bit game I thought the game was running out of virtual address space so I patched the exe with Large Address Aware support. Virtual Memory consumption was much less (by about 800mb) however the issue persists.

@Joshua-Ashton  If you don't own the game I can provide you with a gift key.


**System information**

OS: Debian 9
GPU: Nvidia Geforce RTX 2060 Super
Driver: 440.66.15
Wine version: Plain 5.8 Staging (without Proton/Lutris etc).
DXVK version: 1.7

**Comment by Joshua-Ashton** [comment]
@jrugia It's okay, I have the game now.

**Comment by Blisto91** [comment]
Anything i can do to help debug this issue?

**Comment by Blisto91** [comment]
Found this to be a regression in d9vk 0.4.
Appears to work with 0.3
