### ISSUE TITLE
Framerate Drop in Monster Hunter World Armor Screen AMD

### ISSUE THREAD

**Issue by Eckoa** [doitsujin/dxvk#1651]
Recently I switched from a 1080ti to a 5700xt, I noticed some odd behavior in the armor screen that when a lot of higher rank gear is on the screen (blue/gold shiny ones) the frame rate drops to 45-50fps from previous 60fps. This does not happen with VKD3D or on my previous Nvidia GPU. This happens on older DXVK versions as well I tried it on Proton 4.11 with the same behavior. Changing the game graphics settings did nothing to effect this and happened regardless of graphics settings used. If the high rank armor isnt shining on the screen (tested by scrolling to lower rank gear) this does not happen.

**Software information**
Monster Hunter World: Iceborne

**System Information**

OS: EndeavourOS
CPU: Ryzen 5 3600
GPU: AMD 5700xt
Graphics Driver: Mesa 20.2 git
DXVK Version : DXVK 1.7
WINE Version: Proton-5.8-GE-2-MF

![Screenshot from 2020-06-05 00-37-38](https://user-images.githubusercontent.com/66459087/83841371-56e7f900-a6c6-11ea-834c-8f637b323349.png)

**Comment by Eckoa** [comment]
I am currently 24hr denuvo banned for trying other proton versions so am unable to provide anything further at this time

**Comment by doitsujin** [comment]
MHW is known to run very poorly with DXVK (or Proton in general, although vkd3d will give you much better results). It would be very useful to know
a) which GPU your "previous Nvidia GPU" was
b) whether you are GPU-bound or not (set `DXVK_HUD=fps,gpuload`).

**Comment by Eckoa** [comment]
> MHW is known to run very poorly with DXVK (or Proton in general, although vkd3d will give you much better results). It would be very useful to know
> a) which GPU your "previous Nvidia GPU" was
> b) whether you are GPU-bound or not (set `DXVK_HUD=fps,gpuload`).
> 
> Also, make sure to use ACO.
> 
> In general I don't consider performance problems to be fixable at this point though, especially in this game which hits thread synchronization bottlenecks _even on Windows_ and even moreso on wine.

It was a 1080ti (I mentioned it first thing) on vulkan beta driver. I switched between LLVM and ACO primarily using ACO to see if that was the issue but neither did anything. I also tried with/without FSYNC and I always use game mode.

I'm currently Denuvo banned so I can't do anything further till tomorrow, but I will say the performance has been pretty great minus this one oddity.

**Comment by doitsujin** [comment]
FWIW relative performance with D3D11 on my system (Ryzen 2700X + RX 480) compared to Windows is something like 40% in this game which is *exceptionally* bad, and it's probably not just DXVK's fault.

**Comment by Eckoa** [comment]
> FWIW relative performance with D3D11 on my system (Ryzen 2700X + RX 480) compared to Windows is something like 40% in this game which is _exceptionally_ bad, and it's probably not just DXVK's fault.

No doubt, MT Framework engine and MHW does some bizarre stuff. I'm just looking to figure out why this specific menu lags for some reason. If it was a GPU performance issue I'd imagine VKD3D to be worse because in GPU bound scenarios DXVK wins out but for the Armor menu its the opposite. Id even understand if something graphics/CPU heavy was happening but there's nothing really going on and in situations it is happening I can maintain 60FPS so its really strange

**Comment by Eckoa** [comment]
Ban just ended snd having trouble getting apitrace to work following instructions in common issues on the wiki. I did manage a d3d11 log running dxvk debug 
[MonsterHunterWorld_d3d11.zip](https://github.com/doitsujin/dxvk/files/4739447/MonsterHunterWorld_d3d11.zip)
need to try and figure out how to get apitrace to work through proton/steam in the mean time

**Comment by Eckoa** [comment]
Mangohud screens of when the issue occurs

When the frame rate drops
![Screenshot from 2020-06-06 01-04-31](https://user-images.githubusercontent.com/66459087/83938297-997a0600-a798-11ea-9fae-63f7a29126e7.png)

Scroll up on the screen just a bit and it stops
![Screenshot from 2020-06-06 01-04-42](https://user-images.githubusercontent.com/66459087/83938304-b1518a00-a798-11ea-8789-d19ef17a1c44.png)

i understand if this isnt a priority or even a concern, MHW is a flaky beast but its just odd and wanted to do my part if its solvable

**Comment by doitsujin** [comment]
CPU-bound then, not something I can just fix.

**Comment by WinterSnowfall** [comment]
@Eckoa Your GPU could just be entering a lower power state due to perceived under-utilization in that particular spot. It might not be this, but I guess you could try to see if it still happens when something else is stressing the GPU in the background.

**Comment by Eckoa** [comment]
> @Eckoa Your GPU could just be entering a lower power state due to perceived under-utilization in that particular spot. It might not be this, but I guess you could try to see if it still happens when something else is stressing the GPU in the background.

Gonna try and figure it out elsewhere, thanks though
