### ISSUE TITLE
[Guitar Hero III] Frametime spikes when there's video playback

### ISSUE THREAD

**Issue by guihkx** [doitsujin/dxvk#1652]
I'm noticing visible frametime spikes when there's video playing in the game, e.g. when loading the intro videos or in some scenarios where there's video playing in the background. However, these spikes do not occur at all on WineD3D or native D3D9 on Windows.

I was also able to reproduce said spikes on DXVK + Windows, although I felt they were "less terrible" than on DXVK + Wine.

### Software information
Guitar Hero III: Legends of Rock (v1.31)
Lutris v0.5.6
Arch Linux

### System information
- **GPU:** NVIDIA GTX 660
- **Driver:** 440.82
- **Wine version:** `lutris-5.6.2`
- **DXVK version:** 1.7-48 (68ae3f4)

### Apitrace file(s)
- https://drive.google.com/file/d/13fzWY1C2y0lIzQvbssRe2sZ74MmX_ujL/view (recorded on Windows / Native D3D9)

### Log files
- d3d9.log: https://gist.githubusercontent.com/guihkx/bb47183cf2b4224028323bf2f6ccf881/raw/ef1d89b820ea2e933d7ed091420b1f6e671093ad/GH3_d3d9.log

**Comment by guihkx** [comment]
As I'm not sure if the apitrace will help in this case, I made two small videos that illustrate what I mean:

### DXVK (Wine)

https://www.youtube.com/watch?v=K-RLI1HdpMg

### WineD3D

https://www.youtube.com/watch?v=vxj8scZVkSM

**Comment by K0bin** [comment]
Could you try and make an apitrace with DXVK? Maybe the game is doing something differently in that case. The apitrace you've uploaded finishes in 9 seconds for me with 76fps on average so there are no performance problems with that.

**Comment by K0bin** [comment]
Actually, never mind. We found the issue.

**Comment by guihkx** [comment]
Awesome! Thanks for the heads up, I was just about to get a new apitrace.

**Comment by K0bin** [comment]
BTW you should check out Clone Hero which has a Linux port.

**Comment by K0bin** [comment]
Should be fixed in master.

**Comment by guihkx** [comment]
It is! :)

Thank you very much, you guys are awesome!
