### ISSUE TITLE
Star Citizen Crashes After Spawn Using DXVK 1.7

### ISSUE THREAD

**Issue by HMSS013** [doitsujin/dxvk#1656]
Star Citizen game installs and launches without issue. Player spawns on station and can stand up/navigate in the cabin, but game freezes/crashes when opening cabin door:
https://i.ibb.co/swxrrVb/Crash-Point.jpg

Installed Star Citizen using Lutris 0.5.6 and the installer script located on the Lutris page:
https://lutris.net/games/star-citizen/

All dependencies mentioned in GloriousEggroll blog:
https://www.gloriouseggroll.tv/how-to-get-out-of-wine-dependency-hell/

System Information:
AMD FX-8350
ATI Radeon RX 570 - AMDGPU 19.1.0-1
Fedora 31 - Cinnamon 4.4.8-7 (Also Occurs Running Ubuntu - Unity 20.04)
Kernel 5.6.13-200
Lutris Wine Version: 5.5-2 (Also Occurs With Wine Staging 5.7)
DXVK Version: 1.7L-84bb768 (Also Occurs Using DXVK 1.6.1L / 1.6L-ce3d0ab / 1.5.5)

This issue does not occur and game runs, albeit poorly, when DXVK is disabled. (I assume this would be using WineD3D)

I had also considered the possibility that this was hardware related, though game does run without issue on the same machine using native Windows 10.

I've spent weeks trying to determine what is causing this issue before making this thread, but the logs don't seem to provide any information:

[Lutris Debug Output.log](https://github.com/doitsujin/dxvk/files/4742865/Lutris.Debug.Output.log)

[Game.log](https://github.com/doitsujin/dxvk/files/4742867/Game.log)

[StarCitizen_d3d11.log](https://github.com/doitsujin/dxvk/files/4742868/StarCitizen_d3d11.log)

[StarCitizen_dxgi.log](https://github.com/doitsujin/dxvk/files/4742869/StarCitizen_dxgi.log)

**Comment by Joshua-Ashton** [comment]
Your Mesa version is half a year old.

Please try a newer version of Mesa and/or with ACO enabled as well.

**Comment by doitsujin** [comment]
a) please clarify "freezes/crashes". Is this a GPU hang that requires you to reboot or not?
b) I cannot and will not debug the problem unless someone provides an apitrace or bisects the issue.

**Comment by varris1** [comment]
Where exactly did you open the spawn door? I can't reproduce this issue on Port Olisar at least.
