### ISSUE TITLE
various games - artifacts with forced AF

### ISSUE THREAD

**Issue by aufkrawall** [doitsujin/dxvk#1666]
There are colored border artifacts when forcing AF via DXVK config:
![MazeGame-Win32-Shipping_2020_06_14_16_22_00_596](https://user-images.githubusercontent.com/13510490/84596270-f3e02a00-ae5c-11ea-9ea8-863fbd99f328.png)

Forcing AF works without artifacts with Nvidia driver and native D3D9.

### Software information
Latest game version via Steam, maxed out details (issue doesn't show up with lowest details setting)

### System information
- GPU: GTX 1070
- Driver: 451.22
- Wine version: Windows 10
- DXVK version: dxvk-master.9525f53d00e2d6f9597a93ffac3f91b561ab5dc7

I think I already had this issue with radv on Linux some months ago.

### Apitrace file(s)
https://drive.google.com/file/d/1ecpHmCtTnqjKRiV4MoHLya9Twm9GFh6W/view?usp=sharing

### Log files
- d3d9.log:
[MazeGame-Win32-Shipping_d3d9.log](https://github.com/doitsujin/dxvk/files/4776587/MazeGame-Win32-Shipping_d3d9.log)

Edit: Reopening with more appropriate title, as also other games and D3D11 seem affected as well.

**Comment by TjReiny** [comment]
can u try the 443.24 nvidia driver?
the standart nvidia drivers seem to make a mess in some situations.
u can get them from here: https://developer.nvidia.com/vulkan-driver

**Comment by doitsujin** [comment]
tbh I don't think this is worth spending time on since you're using a non-default configuration that is expected to break games that rely on exact behaviour. The fact that it works on native D3D9 doesn't really matter; native drivers may have more accurate heuristics on when to apply the override that we don't, but in the end, changing the configuration isn't expected to work in all cases.

**Comment by aufkrawall** [comment]
Can totally understand this. Though, If I'm not utterly mistaken, I think it was possible to force AF via RADV without those artifacts.
It should be possible to force AF for Vulkan outside of DXVK with libstrangle or VkGHL also with Nvidia, but I'd have to install Linux first to be able to try this. :(

**Comment by aufkrawall** [comment]
I've installed Linux and either RADV handles it better or my memory betrayed me: There are also these artifacts when forcing AF via libstrangle on Nvidia. Thus closing. :)

**Comment by aufkrawall** [comment]
There was this PR by @CME42 , which in its updated form seems to fix the issue for D3D9 without side effects:
https://github.com/doitsujin/dxvk/pull/1673

Though D3D11 seems to show the same issue  in The Forest (Unity Engine):
![theforest](https://user-images.githubusercontent.com/13510490/86540527-64331600-bf06-11ea-8bbf-7dc978a4970d.png)

Perhaps it can be fixed in the same way like for D3D9?

Apitrace:
https://drive.google.com/file/d/1Lb3Fo1E4THuwWtzbbxNiEEGC7p1qXlXm/view?usp=sharing

Logs:
[TheForest_dxgi.log](https://github.com/doitsujin/dxvk/files/4875442/TheForest_dxgi.log)
[TheForest_d3d11.log](https://github.com/doitsujin/dxvk/files/4875443/TheForest_d3d11.log)

**Comment by doitsujin** [comment]
D3D11 samplers are't tied to textures like in D3D9, so no, the fix isn't portable and I don't intend to work around bugs caused by what is literally a hack. If it's broken, don't use it.

**Comment by aufkrawall** [comment]
Sure, no biggie.
If someone came around with a patch for D3D11 I'd gladly try it though.

**Comment by aufkrawall** [comment]
Funny, my memory didn't trick me: The issue indeed doesn't occur when using an AMD GPU (both radv & amdvlk).
