### ISSUE TITLE
[d3d11] Wrong color of trees in World of Warships

### ISSUE THREAD

**Issue by ernstp** [doitsujin/dxvk#1668]
Many of the trees in WoWs have the wrong color. They are often much brighter or just a strange blue-teal color. I think these are billboard style 2d trees. See attached picture.
![wows](https://user-images.githubusercontent.com/877338/84683336-5c033e80-af37-11ea-9927-bdd1c9359555.jpg)

### Software information
World of Warships, all versions for the last months including the latest 0.9.5.
All Foliage quality settings and all other settings as far as I have found.

### System information
- GPU: AMD Fury (FIJI)
- Driver: Tested RADV ACO, RADV LLVM, AMDVLK
- Wine version: 5.7
- DXVK version: 1.7

### Apitrace file(s)
In progress...

### Log files
In progress..

**Comment by ernstp** [comment]
Here's how they should look, from Windows:
![wows2](https://user-images.githubusercontent.com/877338/84683742-f6fc1880-af37-11ea-8152-895f9f4c9fcd.jpg)

**Comment by ernstp** [comment]
[WorldOfWarships64_d3d11.log](https://github.com/doitsujin/dxvk/files/4781687/WorldOfWarships64_d3d11.log)
[WorldOfWarships64_dxgi.log](https://github.com/doitsujin/dxvk/files/4781688/WorldOfWarships64_dxgi.log)

**Comment by ernstp** [comment]
apitrace from Windows.
https://drive.google.com/file/d/1Hsvh1DL23nIO1RM1mgJU-x78_8PWQ7Ie/view?usp=sharing

**Comment by doitsujin** [comment]
I'm unable to download the trace file, because "You need access".

**Comment by ernstp** [comment]
Now!

**Comment by doitsujin** [comment]
Thanks; unfortunately it crashes on replay for some reason, and Renderdoc no longer works with DXVK so I currently have no way to debug this on the Linux side.

**Comment by ernstp** [comment]
I can try apitrace on Linux perhaps... ?

**Comment by doitsujin** [comment]
Well my main issue right now is getting renderdoc to work. For some stupid reason it just crashes everything i'm trying to use it with.

FWIW, I have the game installed anyway and can confirm the issue - it also happens with wined3d by the way - but thanks for providing the trace anyway, *usually* that makes things a lot easier.

**Comment by ernstp** [comment]
Right, so you can get it right in the port with the Fjords "port" for example. There are some color variations in various maps etc.

**Comment by doitsujin** [comment]
Works fine on Windows with DXVK:
![2020 06 16-00 40](https://user-images.githubusercontent.com/25567304/84713121-9f2ad500-af6a-11ea-83c3-9ae1cdfb9b3b.png)

Not entirely sure what's going on yet but this smells like a wine issue, especially given that the *exact same thing* also happens with wined3d.

**Comment by ernstp** [comment]
Do you have an idea for how to research this further?

**Comment by jqadev** [comment]
@doitsujin isn't it related to https://github.com/ValveSoftware/wine/pull/84 ?

**Comment by doitsujin** [comment]
No, this has nothing to do with swap chain formats but **texture** formats.

**Comment by Sigtechnica** [comment]
maybe not related but I had crashes , games not starting with wine-staging 5.11 (64-bit). Full reinstall of wine , nvidia driver update, rolled back dxvk versions ,no luck, at the end I rolled back to wine-staging 5.10 everything started to work again like a charm.

**Comment by doitsujin** [comment]
wine is known to have major stability issues lately, due to a massive ongoing ntdll refactor.

**Comment by ernstp** [comment]
Huh, this is solved for me now! I was running with foliage off for a few weeks so I'm not sure what fixed it really, but there was a big 0.9.6 update today. Anyone can confirm?

**Comment by Blisto91** [comment]
Yes this does not seem to be an issue anymore. I have at least not been able to reproduce with any in-game settings in the same scene and going as far back as proton 4.11

So i think this issue can also be closed.

**Comment by Blisto91** [comment]
@K0bin This one too
