### ISSUE TITLE
[Help] D3D11 apps just crashes :(

### ISSUE THREAD

**Issue by kolyanok** [doitsujin/dxvk#167]
Using dxvk Version 0.31 on SteamOS 2.148 with wine-vulkan builded from source. Vulkan cube.exe works fine, but dxvk apps doesn't :( d3d11-compute.exe crashes instantly...

### Software information
SteamOS 2.148, trying to run d3d11-compute.exe

### System information
- GPU: Nvidia GeForce GTX 1080 Ti
- Driver: Nvidia 387.22.0
- Wine version: wine-vulkan 3.3
- DXVK version: 0.31

### Log files
https://gist.github.com/kolyanok/413bf830ff3f13c717197ff8b41e5d92

So can you please help me to fix this. Thanks :)

**Comment by SveSop** [comment]
@kolyanok You may try a newer build from this site: [https://haagch.frickel.club/files/dxvk/](https://haagch.frickel.club/files/dxvk/)

All the way to the bottom (check dates) is the newest build. Loads of stuff happens here in 7 days, and 0.31 is 7 days old, and 54 commits behind master :)

**Comment by Yardanico** [comment]
@kolyanok these demos require native d3dcompiler-46.dll or d3dcompiler-47.dll (DXVK currently can't run them without this dll).

**Comment by kolyanok** [comment]
Thank you for helping. I just installed a newer build, as recommended by @SveSop,  and now it works great. Demos and games works fine :)
