### ISSUE TITLE
OBS Studio and Texture Problem with The Evil Within Game

### ISSUE THREAD

**Issue by mstfbsrn980** [doitsujin/dxvk#1671]
I am using RTX 2060 (with the latest driver) and the latest OBS Studio software on Windows 10 2004. With the latest version DXVK and The Evil Within game, OBS creates an in-game black screen. When running games without OBS, textures are often late loading. This issue is not available in D9VK versions.

**Comment by doitsujin** [comment]
This kind of problem is precidely why we don't really care about Windows-only issues. The chances of this being our bug in the first place is like 0.01%, and the chance of it being fixable inside DXVK is even lower, so yeah, I really don't care.

**Comment by mstfbsrn980** [comment]
The Evil Within game does not support fullscreen. For this reason, even if GSYNC is running, micro stuttering can not eliminated. The old D9VK can run this game as fullscreen and prevent micro stuttering and run smoothly with OBS Studio. But the new DXVK does not bring the game with fullscreen. It prevents stuttering but does not work properly with OBS. So the problem is the changes with DXVK. It can not give fullscreen modes to games like D9VK. There is also a texture problem.

Changes made with 1000% probability are the cause of this problem. :D

**Comment by K0bin** [comment]
I don't think anything changed in regards to how DXVK handles fullscreen since D9VK got merged. The Evil within doesn't even use D3D9, so D9VK has absolutely nothing to do with it here.

Besides this, 'texture issue' is literally the most generic description of any computer graphics bug.

**Comment by Joshua-Ashton** [comment]
Please report this to the OBS developers so they fix their pile of wank graphics hook.
This is the third report I've had from someone **today** that their hook breaks games, and I've even had it myself in the past.

I really don't know why they shipped it -- it doesn't work in any Vulkan game I tested or with DXVK, it just causes them to crash.
It also crashes if you try to RenderDoc anything too -- which hit me when I was rdocing a Vulkan demo, one time.

/rant Not our bug.

**Comment by mstfbsrn980** [comment]
D9VK comes with D3D11 API support and is outdated. So I wrote D9VK, but older versions of DXVK also work properly with the OBS Vulkan hook. I used another dxgi.dll to prevent micro stuttering for the game and make the game fullscreen without using DXVK. But driver support is disabled. The error is related to D3D11CreateDeviceAndSwapChain. OBS error is not related to DXVK already but this error can be corrected by editing DXVK. I mentioned the reason for this problem. The old DXVK could make the game to fullscreen from borderless but the new DXVK cannot do this.

Also OBS Vulkan support was developed by Ubisoft. And if I tell them this problem, they will make more sense than your reaction. They will say that using Wrapper will force OBS into an error. So here is the right place for the OBS error. Even if DXVK-OBS error is not related to DXVK.

Goodbye...

**Comment by doitsujin** [comment]
The fact that an old version of DXVK works **does not mean** that this is our bug. You're using a third-party app, and that third-party app breaks DXVK, period.

Would be nice if you could bisect the problem to see what exactly caused the regression, but don't expect any support.
