### ISSUE TITLE
[d3d9] shadow and moiré artifacts in Borderlands 2

### ISSUE THREAD

**Issue by aufkrawall** [doitsujin/dxvk#1674]
The shadow maps show artifacts with DXVK in shape of stripes and weird transitions that change a lot when moving. It's not well visible in static screenshots.

There's something that looks like another issue, which is a weird moiré pattern on some textures:
![49520_20200624131912_1](https://user-images.githubusercontent.com/13510490/85587658-4500d280-b642-11ea-89d2-94ceb386b9bf.png)

Both issues aren't there with native D3D9.

It's not related to anisotropic filtering. If I'm not mistaken, the moiré is not there with the DXVK version that ships with Proton 5.0-9. I'm going to recheck that. The other shadow issue definitely is also there with Proton 5.0-9 DXVK version.

### Software information
Latest Borderlands 2 Steam version with max. details, 1440p.

### System information
- GPU: GTX 1070
- Driver: 440.66.17
- Wine version: Proton 5.0-9
- DXVK version: Proton 5.0-9 / Proton 5.0-9 + latest git master

### Apitrace file(s)
Created on Windows with different driver that shows the same issues:
https://drive.google.com/file/d/1mKDa0_Ebde03BkCRox0Ff32WXCIywUzR/view?usp=sharing

### Log files
[Borderlands2_d3d9.log](https://github.com/doitsujin/dxvk/files/4826482/Borderlands2_d3d9.log)

**Comment by CME42** [comment]
Can you try `d3d9.supportDFFormats = False`  in the dxvk.conf?

**Comment by aufkrawall** [comment]
Yes, that fixes both issues entirely. Another nice catch, thanks again!

**Comment by aufkrawall** [comment]
Another issue, maybe unrelated: There are wandering stripe artifacts with SSAO enabled which aren't there with WineD3D. They are most prominent when riding a vehicle. They disappear when turning off SSAO.

**Comment by CME42** [comment]
If it's still an issue on master, yeah, please create a new issue and also make a new trace because Borderlands 2 is now using a different render path.

**Comment by aufkrawall** [comment]
@CME42 Alright, then I'll do so. May I ask if you intend to reopen the updated PR for D3D9 forced AF?

**Comment by aufkrawall** [comment]
@CME42 Thanks for reopening the PR!

Regarding the apitrace: I created the existing one with native D3D9, so wouldn't another apitrace with it be ~identical?

**Comment by CME42** [comment]
Oh right, i somehow thought this was a dxvk trace, sorry, but can you repro the issue when you replay the native trace with dxvk?

**Comment by aufkrawall** [comment]
In that case I'd have to create a new trace regardless, as the issue is not well visible in what I recorded initially.
I haven't replayed any apitraces until now, only rederdoc captures. I'll see to it.

**Comment by aufkrawall** [comment]
I suspect the game's launcher tricked me (well, or I just made a mistake), as the corruption by SSAO definitely is also there with native D3D9. Nothing left to do. :)
