### ISSUE TITLE
[d3d11] - Attack on Titan 2: Final Battle (601050) - Stark disparity in gpu utilization and performance in comparison to native

### ISSUE THREAD

**Issue by papuSpartan** [doitsujin/dxvk#1677]
The game has noticeably worse performance when running using DXVK and utilizes substantially more gpu than on native.

With low graphics preset the game will manage a somewhat consistent ~35 fps when playing a mission, with gpu utilization going no higher than ~60%, but with high preset gpu utilization will stay locked at 100% and is a choppy ~30 fps. 

**This is not a vram issue as the usage only ever went to ~2GB/6GB of my cards vram.**

Running the game natively on windows with all settings maxed out the game would have no problem with a perfectly stable 60 fps with or without vsync. (the game has a 60 fps cap (due to the physics engine I guess))

### Software information
- Game: Attack on Titan 2: Final Battle [https://store.steampowered.com/app/601050/Attack_on_Titan_2__AOT2/](url)

- Graphics settings: low preset, no vsync, no video
- Input Method: gamepad (xbox one controller)
- Launch options: 
"PROTON_LOG=1 VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation DXVK_HUD=full"

### System information
- GPU: Geforce GTX 980 Ti
- Driver: nvidia 440.100.0
- Wine version: wine-5.11 (Staging)
- DXVK version: 1.7-8-g51531e4a7
- Vulkan version: 1.1.119
- Proton version/build: 5.0-9

### Apitrace file(s)
- [https://mega.nz/file/DDhhHZZJ#13wq9e1rSz5QBWY-TjeHqnSRBTQJgQXw34Rzijh9vrQ](url)

### Log files
- Proton log: [https://mega.nz/file/STxVVDjQ#90MU4x254GlC4_6D2NNjO7VQiNTO8AoDPnAhjbUC3NQ](url)
- d3dll.log: [https://mega.nz/file/zGISTCAQ#19_8qDTbUUdF5jUbKjL5zBMNI8YUvjL0fporZcqmAFE](url)

### Notes
The "no video" launch option found in the game launcher is necessary for the game to launch because of an issue with wine.

I found a benchmark of someone playing the game with dxvk with a weaker card (1060 3GB) and they were getting better, more consistent, performance.
[https://www.youtube.com/watch?v=yV4pqMbjr4o](url)

**Comment by doitsujin** [comment]
The apitrace crashes on replay.

In general I don't consider low performance on old GPUs a problem, it's not something DXVK can just magically improve.

**Comment by papuSpartan** [comment]
> The apitrace crashes on replay.
> 
> 
> 
> In general I don't consider low performance on old GPUs a problem, it's not something DXVK can just magically improve. It doesn't matter if the GPU is stronger than a newer one on Windows, it's just that things that are fast in D3D11 aren't necessarily fast in Vulkan on that kind of hardware.
> 
> 
> 
> **Edit:** Why do you have validation layers enabled? That also cripples performance.

I don’t why it crashes for you but I’ll try and replay it myself later.  Validation layers were enabled because I was recommended it to increase verbosity if possible. I wasn’t aware 9 series cards were too much for vulkan, I suppose I could test this on my 2070m if my laptop ever gets back to see if it has insane drops as well.
