### ISSUE TITLE
Issue with AMD Radeon RX 5700 XT

### ISSUE THREAD

**Issue by VGuenat** [doitsujin/dxvk#1683]
Hello there,

I find myself with a problem regarding the setup of DXVK on Archlinux. I am unable to run any game with DXVK enabled, while the games run flawlessly under wined3d (either in wine or proton). Now I assume I must have missed some important and obvious step, but so far I was unable to find which one.
Here is the list of the things I've done:
- check that the device is supported: cf https://en.wikipedia.org/wiki/Radeon_RX_5000_series
- check that I run the latest version of the driver: 2020.Q2.6-1 for amdvlk and 20.1.2-1 for mesa/radv
- check that others have been able to run the games I'm trying to run using DXVK: verified for Starcraft 2 (via a friend using DXVK on an AMD GPU) and for Mirror's Edge (https://www.reddit.com/r/linux_gaming/comments/bbt67l/d9vk_can_now_run_mirrors_edge/)
- enable DXVK in Lutris for the games in question

I don't know if this is a relevant detail, but I am running games from Lutris.

### Software information
Starcraft 2 (wine), Supreme Commander (proton), Star Wars: The Force Unleashed Ultimate Sith Edition (proton), Mirror's Edge (wine)
Basically any game that is not running natively on Linux has the same issue. As mentioned earlier, deactivating DXVK solves the issues.

### System information
- GPU: AMD Radeon RX 5700 XT
- Driver: amdvlk (2020.Q2.6-1), vulkan-radeon (radv, 20.1.2-1, same version for mesa) both 64-bit and 32-bit versions
- Wine version: lutris-5.7.3-x86_64 and proton 5.0-9
- DXVK version: 1.7L-84bb768

### Apitrace file(s)
- Didn't use it yet. Will try to use the Windows release of apitrace in one of the wine prefixes from lutris later on.

### Log files for Starcraft 2
- d3d9.log: [SC2_x64_d3d9.log](https://github.com/doitsujin/dxvk/files/4899728/SC2_x64_d3d9.log)
- d3d11.log: it was empty
- dxgi.log: [SC2_x64_dxgi.log](https://github.com/doitsujin/dxvk/files/4899729/SC2_x64_dxgi.log)

### Log files for Supreme Commander
- screenshot with DXVK_HUD=full. The screen stays black until I kill the application.
![Screenshot_2020-07-10_00-00-06](https://user-images.githubusercontent.com/9852387/87095509-25bc9480-c241-11ea-867b-47bff56650ad.png)
- proton log with WINEDEBUG: [steam-9350.log](https://github.com/doitsujin/dxvk/files/4899746/steam-9350.log)

I apologize if this a gross misconfiguration from my side or if it has already been solved elsewhere, but I couldn't seem to find the necessary information to make DXVK work in my setup.

Thank you for your time

**Comment by doitsujin** [comment]
Can't do much without an apitrace.

Sounds like a driver bug though, DXVK doesn't really care what kind of GPU you have.

**Comment by Oschowa** [comment]
Get rid of amdvlk, which you are using according to your screenshot, and try again.

**Comment by frostworx** [comment]
or explicitly use vulkan-radeon and leave amdvlk untouched:
`VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json %command%`

**Comment by VGuenat** [comment]
Thanks for the quick answer! As @Oschowa mentioned, getting rid of amdvlk solved the issue and everything works smoothly with DXVK. And as @frostworx suggested there is an option in Lutris to select the Vulkan ICD on a per-game basis.

What would be the next step? Reporting the issue upstream to the amdvlk folks?

**Comment by doitsujin** [comment]
If you can get us an apitrace then we can take a look at the shader that's causing problems and check if we're generating valid code, but we need something to work with.

**Comment by VGuenat** [comment]
Took me a while longer than expected to break my setup again and to use apitrace in wine but here is the trace for StarCraft2
[SC2.trace](https://drive.google.com/file/d/1ojQwZTQQk-3wUYpePcKbi8L5PQjVnxyM/view?usp=sharing)

It also contains the Battle.net launcher part, which is working. The game itself crashed at launch, so hopefully you'll get what you need.

Tell me if there's anything more I can do!

**Comment by nhaehnle** [comment]
@doitsujin JFYI, since I happened to come across this issue randomly, we found a DXVK-generated pipeline that uses push constants outside of the range defined in the VkPipelineLayout in a different game. That's out-of-spec behavior, but it seems like validation may not catch it.

**Comment by doitsujin** [comment]
Yes, that's a known long-standing issue with D3D9 shaders. Still waiting for @Joshua-Ashton to fix that.

**Comment by Blisto91** [comment]
@VGuenat Was this issue solved with newer dxvk and or drivers?
I see the issue doitsujin links to got solved if it's the same problem.

**Comment by K0bin** [comment]
Closing this because it's stale.

**Comment by Blisto91** [comment]
If you still have the same issue feel free to comment here again.
