### ISSUE TITLE
[D3D9] The Witcher - garbage at bottom at start of speech

### ISSUE THREAD

**Issue by LinAGKar** [doitsujin/dxvk#1684]
At the start of speech is The Witcher, there is a letterbox effect. This works correctly with WineD3D, but with DXVK, there is garbage at the bottom of the screen, as shown in these videos:

WineD3D: https://giant.gfycat.com/BleakBelovedAfricanwildcat.webm
DXVK: https://giant.gfycat.com/WellgroomedSnivelingGardensnake.webm

### Software information
The Witcher GOG version in Lutris on OpenSUSE Tumbleweed. Video settings maxed out, DoF off, 1920x1080.

### System information
- GPU: GeForce RTX 2080 Ti
- Driver: 440.82
- Wine version: lutris-5.7
- DXVK version: 1.7L-84bb768

### Apitrace file(s)
I am not able to take an apitrace, as the apitrace link under https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace is a dead link.

### Log files
- d3d9.log: [witcher_d3d9.log](https://github.com/doitsujin/dxvk/files/4907131/witcher_d3d9.log)

**Comment by K0bin** [comment]
Use the Windows version of Apitrace.
https://apitrace.github.io/#download

**Comment by LinAGKar** [comment]
Here is a trace: https://drive.google.com/file/d/1ZRISUz61lRxO_OadjKPQNgSC1QXnIU5Z/view?usp=sharing

**Comment by K0bin** [comment]
![grafik](https://user-images.githubusercontent.com/1131720/87232127-eb780200-c3bc-11ea-8e31-5a2ba33be58b.png)
The apitrace doesn't have any letterboxing (or text) at all.

Did you record it using DXVK or WineD3D?

**Comment by LinAGKar** [comment]
This was with WineD3D, and there was letterboxing and text when I played. [Here](https://drive.google.com/file/d/1MS-a42WbrMRbkhYKGZ7_28rqFnm0xHIo/view?usp=sharing) is another one, and [a recording](https://drive.google.com/file/d/1U4rHlJOG_gRxww51RZ4hgtLRH-KspLtj/view?usp=sharing) of when I captured it, and is letterboxing in the second dialogue (with Triss) at 2:37 (though not in the first dialogue that I recorded above).

Maybe it renders with D3D9 and overlays the text and black bars with something else?

**Comment by K0bin** [comment]
I've played around with the game itself and the letterboxing seems kinda random. I've even had it show up with DXVK.

**Comment by LinAGKar** [comment]
Shows up fine as in it reproduces the issue, or it renders correctly?

**Comment by K0bin** [comment]
It renders correctly.

**Comment by LinAGKar** [comment]
Did you manage to reproduce the issue in the actual game?

**Comment by K0bin** [comment]
Yes but it seems really inconsistent. I'm not sure if this isn't a game bug.

**Comment by LinAGKar** [comment]
I've never seen the problem with WineD3D though, so something is different.

**Comment by Blisto91** [comment]
Can reproduce this consistently with proton 5.0. And every version after i cannot anymore so this seems fixed and can be closed.
(R9 380 radv 21.3)

**Comment by K0bin** [comment]
@Blisto91 Thanks for the testing, I really appreciate it.

**Comment by Blisto91** [comment]
Np.
Just trying to go through some of the old ones to see if they can be cleaned out. Will also go through some of the Nvidia ones at some point.
