### ISSUE TITLE
[D3D9] - Tomb Raider: Legend (7000) - Low performance

### ISSUE THREAD

**Issue by aqxa1** [doitsujin/dxvk#1685]
Okay, so another game with a performance issue compared to WineD3D. Possibly related to #1682. 

Early on in the game, performance mostly reaches my refresh rate of 144hz, however about an hour in, fps drops significantly.

These screenshots are with RADV ACO and RadeonSI, although I also tested LLVM and AMDGPU-PRO with little difference in performance.

DXVK (52 fps): 
![DXVK](https://i.imgur.com/pnRDnih.png)

DXVK with full hud:
![DXVK full hud](https://i.imgur.com/HXPMeUM.png)

WineD3D (132 fps)
![WineD3D](https://i.imgur.com/r5yVrVm.png)

EDIT: I also tried dgVoodoo2 as a workaround like in #1675, but it didn't improve things in this case.

### Software information
Tomb Raider: Legend (7000), 1440p, maximum settings except "next-gen effects" and "Anti-aliasing" were disabled.

### System information
- GPU: Radeon RX 5700 XT
- Driver: Mesa-git (ACO and LLVM)
- Wine version: Proton-GE-5.9-ST-3
- DXVK version: 1.7-git (today)

### Apitrace file(s)
- [Windows apitrace](https://mega.nz/file/fGhlBYgQ#p-tJ3WoiWGxqeo0komf-yxbC46NniH95cT2sDoFMCtY)

### Log files
- d3d9.log:
[trl_d3d9.log](https://github.com/doitsujin/dxvk/files/4910769/trl_d3d9.log)

**Comment by doitsujin** [comment]
Can you enable `DXVK_HUD=full`? It's obvious that the GPU doesn't get utilized at all, but we'd need more info on why that is.

**Comment by aqxa1** [comment]
I've added a screenshot with full HUD.

**Comment by doitsujin** [comment]
Hm, nothing suspicious there either.

You sure you don't have Vulkan validation layers enabled or compiled Mesa in debug mode or anything?

**Comment by aqxa1** [comment]
Not to my knowledge, and most of my games perform well. I did test AMDGPU-PRO, which should perform better if it's something strictly to do with Mesa.

That does give me an idea to test DXVK on Windows to see if it's some issue on the Linux side of things, which I will try and get to a bit later.

**Comment by aqxa1** [comment]
So I tested on Windows, this time with the 1.7 binary.

DXVK Windows (61 fps)
![DXVK Windows](https://i.imgur.com/S9sHFUJ.jpg)
Native Windows (176 fps)
![Native Windows](https://i.imgur.com/PgXtZc5.jpg)

**Comment by K0bin** [comment]
Looks like it's locking a POOL_DEFAULT | DYNAMIC texture every frame and needs to synchronize the GPU to do that.

**Comment by K0bin** [comment]
I tried it with DXVK on Windows and it works fine.
![Tomb Raider  Legend Screenshot 2020 07 13 - 13 37 24 15](https://user-images.githubusercontent.com/1131720/87300426-132aaf80-c50e-11ea-9c4b-e7ed0f8e5371.png)

What graphics settings are you using?
![grafik](https://user-images.githubusercontent.com/1131720/87300478-32c1d800-c50e-11ea-8c36-312748e4629f.png)

Can you test if the PR linked above improves things?

**Comment by aqxa1** [comment]
It's "Next Generation Content" that works around the issues; it's not recommended because it breaks water effects and the like, but presumably it changes the way rendering works such that it doesn't trigger the bug.

The PR doesn't seem to be helping, but I'm pretty tired so I may have made a mistake. I'll test it again tomorrow with fresh eyes.

**Comment by K0bin** [comment]
I think I found the issue. The updated PR should fix it.

**Comment by aqxa1** [comment]
Thanks, the new PR fixes the issue completely :+1:. Game now hitting 155 fps, as opposed to 55fps before, so it's now running faster than WineD3D and approaches Windows performance.

Not only that, it also fixes the issue with The Walking Dead, increasing the performance from 41 fps to >144fps (VSync enabled).

**Comment by seanmacky** [comment]
> I tried it with DXVK on Windows and it works fine.
> ![Tomb Raider Legend Screenshot 2020 07 13 - 13 37 24 15](https://user-images.githubusercontent.com/1131720/87300426-132aaf80-c50e-11ea-9c4b-e7ed0f8e5371.png)
> 
> What graphics settings are you using?
> ![grafik](https://user-images.githubusercontent.com/1131720/87300478-32c1d800-c50e-11ea-8c36-312748e4629f.png)
> 
> Can you test if the PR linked above improves things?
> [Here's a build if you can't build it yourself.](https://github.com/doitsujin/dxvk/files/4912163/d3d9_x86.zip)
> 
> EDIT: turned the game to the lowest graphics settings and now it's running poorly.

Hi Kobin.  I was having the same issue. Are you able to link a 64 bit build as that one comes at as x86 instead of x64.

Thank you for your help :)

**Comment by K0bin** [comment]
The changes will hopefully get merged soon. After that the build bot will give you a 64bit dll.

**Comment by seanmacky** [comment]
@K0bin hi! I saw the merge test was cancelled. Any chance of getting the 64 bit build for me to test? Pretty please 🙏

**Comment by seanmacky** [comment]
@K0bin @Joshua-Ashton 

Hi, Any chance of getting the 64 bit build with these fixes for me to test as i have the same issues on the same games. I saw the test was cancelled for pipeline #1231 so the build bot didn't generate the 64bit dll's.

I'm happy to donate $10 to you via paypal for your time doing this ! 

Thank you

**Comment by K0bin** [comment]
FYI the game should be even faster now.

**Comment by aqxa1** [comment]
Just tested the change, and looks to be quite a massive improvement.

I have a new CPU and I couldn't find my old save game. And I tested Proton 5.0-9 compared to Proton Experimental (so there might have been other changes than the PR) so none of this is quite like-for-like, nevertheless:

Both tests with a 5900x and 5700 XT, mesa-git, 5.9.15 kernel:

Proton 5.0-9 (DXVK 1.7.0):
![DXVK 1.7.0](https://i.imgur.com/kiO3JJD.png)

Proton Experimental:
![Proton Experimental](https://i.imgur.com/bVYBWov.png)

So from 246 fps to 445 fps, an 80% performance improvement.

**Comment by K0bin** [comment]
The recent changes aren't even in Proton experimental.

**Comment by aqxa1** [comment]
Interesting, I thought that at first but assumed the performance increase wouldn't have been so large without it. Will retest.
