### ISSUE TITLE
[d3d11] Rendering artifacts in Barn Finders 

### ISSUE THREAD

**Issue by RussianNeuroMancer** [doitsujin/dxvk#1687]
Screenshot: 

![Screenshot_20200713_205753](https://user-images.githubusercontent.com/2613247/87413192-8e6a8f00-c5fc-11ea-8dda-706ac99d39cc.png)

It's looks like what supposed to be light that get through trees on the back (or it's supposed to be shadows of these trees? I not sure) is rendered as constantly flickering black triangles.
After starting new game issue is reproducible with other effects too, so it's not specific to game main menu.

How part from screenshot is supposed to looks like: https://youtu.be/QiA5MHeWtQM?t=587

### Software information
Barn Finders, default settings (high textures, all effects enabled)
Select low textures and disabling all effects doesn't make any difference. 

### System information
- GPU: AMD Radeon Vega 64
- Driver: Mesa 20.1.3
- Wine version: Proton-5.11-GE-2-MF ([game doesn't work with vanilla Proton 5.0-9](https://github.com/ValveSoftware/Proton/issues/4067))
- DXVK version: v1.7-63-gc4f37d39-async

### Apitrace file(s)
I don't have Windows so I can not record apitrace there.
I tried to create apitrace on Linux by following [this DXVK wiki article](https://github.com/doitsujin/dxvk/wiki/Common-issues#apitrace) (tried to do so with PROTON_USE_WINED3D=1) but trace file didn't appear in game folder.

### Log files
- d3d9.log: empty
- d3d11.log: https://gist.github.com/RussianNeuroMancer/f7ca54c0c233e12f824f5c0246237d2b
- dxgi.log: empty

**Comment by K0bin** [comment]
> but trace file didn't appear in game folder.

Check the desktop folder **inside** your wine prefix.

**Comment by doitsujin** [comment]
I tried to run the demo but all I get is a black screen. How do I get around that?

**Comment by doitsujin** [comment]
Ok, got the game to run, works fine on my end (mesa-git, RX 480).

> DXVK version: v1.7-63-gc4f37d39-async

Please don't use unofficial builds to report issues.

**Comment by RussianNeuroMancer** [comment]
@doitsujin 

> works fine on my end (mesa-git, RX 480)

Tested with 20.2~git2007160730.081691 from Oibaf PPA, outcome is still the same:

![Screenshot_20200716_195726](https://user-images.githubusercontent.com/2613247/87669305-5439f280-c7a0-11ea-93c9-7ac9380cbdb4.png)

Anyway, if you can't reproduce this - driver bug then?

> Please don't use unofficial patched builds when reporting issues.

I tried to install official DXVK build via protontricks before writing this bugreport, but after I did this game stopped working, so I had to re-create WINE prefix.

@K0bin 

> Check the desktop folder inside your wine prefix. 

Empty here. (Checked Desktop folder in both user profiles created by Proton.)

> Please also try the game with Microsofts d3dcompiler and d3dx11 DLLs. 

Tried, unfortunately artifacts didn't go anywhere.

**Comment by doitsujin** [comment]
> Anyway, if you can't reproduce this - driver bug then?

Yeah, might be a Vega-specific issue.

**Comment by RussianNeuroMancer** [comment]
> Yeah, might be a Vega-specific issue.

Registered issue at Mesa bugtracker: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3311
