### ISSUE TITLE
Fallout 4 black screen on launch with dxvk dxgi, works with wine builtin dxgi

### ISSUE THREAD

**Issue by Kethen** [doitsujin/dxvk#1692]
### Software information
Fallout 4, default low preset, no godrays

### System information
- GPU: GeForce GTX 1050
- Driver: 440.100.0
- Wine version: PlayOnLinux wine 5.7 amd64 staging
- DXVK version: v1.7

### Apitrace file(s)
- [Fallout4.1.trace.zip](https://github.com/doitsujin/dxvk/files/4931945/Fallout4.1.trace.zip)

### Log files
- d3d11.log:[Fallout4_d3d11.log](https://github.com/doitsujin/dxvk/files/4931878/Fallout4_d3d11.log)
- dxgi.log:[Fallout4_dxgi.log](https://github.com/doitsujin/dxvk/files/4931879/Fallout4_dxgi.log)

### Back Trace
- [backtrace.txt](https://github.com/doitsujin/dxvk/files/4931896/backtrace.txt)

**Comment by doitsujin** [comment]
Works fine on my system.

**Comment by Kethen** [comment]
The same is observed in wine lutris-fshack-5.7-5 and wine-tkg-staging-fsync-vkd3d-git-5.12.r1
Anything else I can provide to help with narrowing down this issue?

**Comment by doitsujin** [comment]
Just use wine's DXGI. I can't reproduce the problem so I can't fix it.

**Comment by Drugoy** [comment]
Sorry to hijack an issue with a bit of off-topic, but @doitsujin is there a way to make use of Proton without steam and/or lutris?

**Comment by K0bin** [comment]
You cam just use regular Wine and run the setup script that's included with DXVK releases.

**Comment by Blisto91** [comment]
@Kethen sorry to Necro and old issue.
Are you able to test if this is still an issue with lat st dxvk and drivers?

**Comment by K0bin** [comment]
Stale
