### ISSUE TITLE
Assassin's Creed Odyssey Infrequent Crashes

### ISSUE THREAD

**Issue by modzilla99** [doitsujin/dxvk#1693]
Assassin's Creed Odyssey crashes infrequently but runs absolutely great otherwise (so thank you sooo much for DXVK!). That happens sometimes right after loading into the game and playing for 10 seconds and if I'm lucky I can even play an hour or more but it always ends in a crash. It the timing is totally inconsistent.

I tried to do an apitrace but I was unable to do so, because it either didn't do anything or when it seems to load the dlls the game was unplayable with 2-4 FPS. I even let it sit there for an hour and played for round about 15 minutes but didn't crash, of course why should it, right? Maybe I did something wrong I am not sure. A trace file wasn't created in any case either. I added the std output, maybe that helps a little. 

**Reports with no log files will be ignored.**

### Software information
Assassin's Creed Odyssey, game settings don't seem to matter, as well as wine version. Tried it why arch, fedora, Lutris and without Lutris and many different wine versions. I even encountered the same behaviour with my RX580 that I had before.

### System information
- GPU: AMD Radeon RX 5700
- Driver: mesa 20.1
- Wine version: 5.7
- DXVK version: 1.7

### Apitrace file(s)
- I can't provide one sadly :( Maybe someone can help

### Log files
- d3d9.log:
[ACOdyssey_d3d9.log](https://github.com/doitsujin/dxvk/files/4933946/ACOdyssey_d3d9.log)

- d3d11.log:
[ACOdyssey_d3d11.log](https://github.com/doitsujin/dxvk/files/4933947/ACOdyssey_d3d11.log)

- dxgi.log:
[ACOdyssey_dxgi.log](https://github.com/doitsujin/dxvk/files/4933948/ACOdyssey_dxgi.log)

- stdout: 
[wine.log](https://github.com/doitsujin/dxvk/files/4933950/wine.log)

**Comment by frostworx** [comment]
maybe related?:
https://github.com/KhronosGroup/Vulkan-Loader/issues/433#issuecomment-659920920

**Comment by doitsujin** [comment]
Make sure to disable the uplay overlay.

I haven't ever had problems with the game so this isn't really something I can work with; I'll leave the bug report open but don't expect anything to change unless someone else with the same problem actually figures out what's wrong.

**Comment by mzanibelli** [comment]
> maybe related?:
> [KhronosGroup/Vulkan-Loader#433 (comment)](https://github.com/KhronosGroup/Vulkan-Loader/issues/433#issuecomment-659920920)

It's definitely not related. Using `lib32-vulkan-icd-loader` version `1.2.147-1` (on Arch) the game _never_ launches.
I did have crashes (very probably from my understanding) related to expiration of timed quests. Maybe check that out?

**Comment by modzilla99** [comment]
> Make sure to disable the uplay overlay.
> 
> I haven't ever had problems with the game so this isn't really something I can work with; I'll leave the bug report open but don't expect anything to change unless someone else with the same problem actually figures out what's wrong.

Thanks, when I'm back home I'll try and make sure I really disabled the overlay since I thought that I already did.

**Comment by modzilla99** [comment]
> > maybe related?:
> > [KhronosGroup/Vulkan-Loader#433 (comment)](https://github.com/KhronosGroup/Vulkan-Loader/issues/433#issuecomment-659920920)
> 
> It's definitely not related. Using `lib32-vulkan-icd-loader` version `1.2.147-1` (on Arch) the game _never_ launches.
> I did have crashes (very probably from my understanding) related to expiration of timed quests. Maybe check that out?

I'm not sure if I understand that right. Do you mean quests that have a limited time to be completed? How do I know it's related, don't they just disappear when the time's up?

**Comment by mzanibelli** [comment]
Hello! Haha, reading that again I must admit it's quite hard to understand indeed.

Yeah, basically I had the game crash twice at the second the timer reaches 0 instead of just having the quest removed from the quest log.
Hope this helps...

**Comment by modzilla99** [comment]
Thanks for all of your help, but it is gpu related, I experienced the same crashing in Windows as well and have since send in the card for repairs! I'll close the issue.

**Comment by Nicholas-Steel** [comment]
> I did have crashes (very probably from my understanding) related to expiration of timed quests. Maybe check that out?

I guess I've got to keep an eye on this, as I too am having random hangs with DXVK & this game but I'm using Windows 10.

A curious thing I've been observing about the crashes is that the hangs involve the game permanantly freezing and when it freezes it's seemingly displaying the first frame that was rendered since I'd last alt-tabbed back in to the game (same frame that Print Screen captures) which makes the freeze kinda jarring lol as I could be running around and then it freezes on an image of somewhere completely different in the game or showing a menu screen.

The game is configured to Borderless Fullscreen but with DXVK it acts like Fullscreen Exclusive. I am also using DXVK within Windows 10, not Linux. Nvidia Geforce 1070Ti.

**Comment by aspire2608-svg** [comment]
Setting -vulkan in Steam launch options worked for me RX 7600 GPU
