### ISSUE TITLE
Gsync is disabled while playing fullscreen DXVK

### ISSUE THREAD

**Issue by tugl** [doitsujin/dxvk#1698]
When playing any game in fullscreen mode using DXVK, the monitor refresh rate is static and Gsync doesn't work. Borderless/windowed mode makes Gsync work as usual.

### System information
- GPU: RTX 2080 Ti
- Driver: 451.67
- Wine version: 
- DXVK version: 1.7

### Log files
- d3d11.log: [FarCryNewDawn_d3d11.log](https://github.com/doitsujin/dxvk/files/4970185/FarCryNewDawn_d3d11.log)
- dxgi.log: [FarCryNewDawn_dxgi.log](https://github.com/doitsujin/dxvk/files/4970186/FarCryNewDawn_dxgi.log)

**Comment by doitsujin** [comment]
DXVK has no control over Gsync. No idea why it wouldn't work, but this sounds like a setup issue elsewhere on your system or a driver bug.

**Comment by tugl** [comment]
Thanks for the reply. Does DXVK use a special fullscreen mode compared to dx11? 

I have reproduced this on 2 systems, Windows v1903 and v2004. Fullscreen in dx9 to 12 does work with Gsync.
