### ISSUE TITLE
[d3d9] NFS3+modern patch shows black screen on start with dxvk

### ISSUE THREAD

**Issue by soredake** [doitsujin/dxvk#1699]
### Software information
Game can be downloaded [here](https://archive.org/details/need-for-speed-iii-hot-Pursuit), and modern patch is [here](https://veg.by/en/projects/nfs3/).

### System information
- GPU: RX 560
- Driver: Mesa 20.1.4 - kisak-mesa PPA
- Wine version: 5.13-staging from ubuntu ppa
- DXVK version: 1.7

### Apitrace file(s)
- [nfs3.trace.zip](https://github.com/doitsujin/dxvk/files/5987909/nfs3.trace.zip)

### Log files
- d3d9.log: [nfs3_d3d9.log](https://github.com/doitsujin/dxvk/files/4970510/nfs3_d3d9.log)
- d3d11.log:
- dxgi.log:

**Comment by soredake** [comment]
Wine 5.16 + latest dxvk, no changes.

**Comment by K0bin** [comment]
This is probably a Wine bug. I've tested a version of the game in #1695 and didnt have that issue with DXVK on Windows.

**Comment by soredake** [comment]
Wine 6.0-rc1 + dxvk 1.7.3, same problem
[wine6.0rc1.log](https://github.com/doitsujin/dxvk/files/5757210/wine6.0rc1.log)

**Comment by soredake** [comment]
Wine 6.7-staging + dxvk 1.8.1, no change.

**Comment by Blisto91** [comment]
@soredake would be able to test again on latest dxvk and driver? 🙂

**Comment by soredake** [comment]
@Blisto91 unfortunately, i don't use linux anymore, but if you can suggest me a live usb distro with latest mesa on which i can install wine i'll test it.

**Comment by Blisto91** [comment]
Hmm i don't know that myself.

Would you be able to try and test it on windows? If that's what you are using ofc.
You could just place the dxvk 1.7 32bit d3d9 dll next to the games exe and see if it reproduces. If yes then try again with latest version.

**Comment by soredake** [comment]
Tried with dxvk 1.7/1.10.1 on manjaro iso, still black screen, works on windows + dxvk.

**Comment by Blisto91** [comment]
Thanks for the testing.
Could i get you to also give it a try with the latest unreleased master build?
You can find a download of it here https://github.com/doitsujin/dxvk/actions/runs/2615690694

**Comment by soredake** [comment]
You can download the game [here](https://veg.by/en/projects/nfs3/) (it's abandonware anyway). I'll test this build later.

**Comment by Blisto91** [comment]
Damn. Thanks for testing tho!

**Comment by pchome** [comment]
> Game can be downloaded [here](https://veg.by/en/projects/nfs3/).

Isn't this just a patch? The same link as in https://www.pcgamingwiki.com/wiki/Need_for_Speed_III:_Hot_Pursuit#Need_For_Speed_III_Modern_Patch
> 1. Download the [Need For Speed III Modern Patch](http://veg.by/en/projects/nfs3/).
> 2. **Copy FEDATA and GAMEDATA directories from the NFS3 CD to a new empty folder.**
> 3. Extract contents of this archive into that folder with replacement of files.
> 4. Run the game.

The patch itself contain a bunch of bundled drivers, which likely outdated a bit and newer versions may contain fixes.
From the patch readme:
```
Recommended:
- nGlide (Glide 3x API emulator) supports fog effect, renders sharp fonts in the menu, uses DirectX 9, supports minimizing and windowed mode (Alt+Enter to switch). Recommended for modern computers with Windows XP/7+.
- dgVoodoo (Glide 3x API emulator) supports fog effect, renders sharp fonts in the menu, supports minimizing and windowed mode (Alt+Enter to switch), uses DirectX 11, but requires very powerful GPU.
- DX7 supports fog effect, but doesn't support minimizing, and FPS may be a little lower than with nGlide or DX8 on the Windows + because of limited Direct3D 7 support. Recommended for old computers with Windows 98/Me/XP.

Other:
- DX8 works smoothly supports fog effect, but doesn't support minimizing, can't display intro video, and on some systems doesn't render dashboard on “In Car” camera view.
- DX6 the same as DX7, but utilizes Direct3D 6. Just for a collection :)
- DX5 is based on the original thrash driver of the NFS3. However, it doesn't support fog effect, it may not work in the Windows 8+, looks worse than others in some details (e.g. artifacts when a large number of spray or dust from under the wheels).
- SoftTri doesn't use hardware acceleration and predictably it looks worst. May not work on Windows 8+. Useful for running the game on virtual machines.
- Glide3x is intended for using with the real 3dfx Voodoo hardware through the Glide 3x API.
```
So, the other options to use with dxvk could be dgVoodoo or DX8+d3d8to9, or manually updated nGlide maybe. On properly patched original game.

**Comment by soredake** [comment]
> Isn't this just a patch? T

Author removed portable version after my last visit, i've now tested nfs3 from here https://archive.org/details/need-for-speed-iii-hot-Pursuit combined with patch from here https://veg.by/en/projects/nfs3/
No luck, just black screen.

**Comment by Blisto91** [comment]
@soredake Can you verify this issue goes away if you make a file called `dxvk.conf` next to the exe and insert `d3d9.enableDialogMode = True`

**Comment by thokkat** [comment]
Works, played a bit no issues observed.

**Comment by soredake** [comment]
@Blisto91 yes, with this option it finally works.
