### ISSUE TITLE
Native UI Development Support?

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [doitsujin/dxvk#1701]
Hi,
 Is it possible to use dxvk to make a DirectX game/programs UI in Linux instead of OpenGL/gtk/Qt/etc, for easier Linux/Windows cross-developing?

**Comment by DadSchoorse** [comment]
One of the developers made [dxvk-native](https://github.com/Joshua-Ashton/dxvk-native).
That's probably what you want, although I don't know how well it works.

**Comment by Joshua-Ashton** [comment]
It should be fine and fairly straight forward to rebase.

I've ported a few games with it, just none of the ports ever got released... :frog:
