### ISSUE TITLE
DXVK_LOG_LEVEL=none creates empty log files

### ISSUE THREAD

**Issue by konomikitten** [doitsujin/dxvk#1703]
I think it would be more preferable if `DXVK_LOG_LEVEL=none` didn't create pointless empty log files, or that there was some way to disable log files entirely.

**Comment by doitsujin** [comment]
DXVK *doesn't* create empty log files when using `none` though?

https://github.com/doitsujin/dxvk/blob/3322da4b94d309132244f97c3a2028660b7f6cd4/src/util/log/log.cpp#L7-L11

Not entirely sure what your problem is, it works as intended here.

**Comment by konomikitten** [comment]
@doitsujin never mind I am apparently a bit daft I had it set to `error` sorry for the bad bug report closing.
