### ISSUE TITLE
StarCraft 1 not running

### ISSUE THREAD

**Issue by guglovich** [doitsujin/dxvk#1706]
The game stopped working on the last update when new APIs were added (10/11), but there may be a coincidence. Was able to run in OpenGL mode using PortBattleNET. So the problem is clearly Vulkan mode. There are no problems with another game(Lineage2). But StarCraft 2 didn't work either.

### Software information
Star Craft 1/2

### System information
- GPU: AMD RX460
- Driver: Mesa RADV 20.1.4-3
- Wine version: 5.14
- DXVK version: dxvk-bin 1.7-1
- Distr: ArchLinux

### Apitrace file(s)
Link for file d3d9 is dead

### Log files
[winedebug.log](https://github.com/doitsujin/dxvk/files/5017554/winedebug.log)
[Agent_dxgi.log](https://github.com/doitsujin/dxvk/files/5017551/Agent_dxgi.log)

**Comment by K0bin** [comment]
You can find the the Windows version of Apitrace on their website: https://apitrace.github.io/

The DLL should be inside the wrappers folder.

**Comment by guglovich** [comment]
> You can find the the Windows version of Apitrace on their website: https://apitrace.github.io/
> 
> The DLL should be inside the wrappers folder.

For d3d9 another utility, this one wrote an API error for me.

**Comment by K0bin** [comment]
What do you mean? What wrote an error? You should use the DLL.

**Comment by guglovich** [comment]
> What do you mean? What wrote an error? You should use the DLL.
I don't understand how to use them.

![изображение](https://user-images.githubusercontent.com/54148165/89218437-af5c4980-d5d6-11ea-8af1-13087aa32c49.png)

**Comment by K0bin** [comment]
Follow this guide: https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace but use the DLL you got from the apitrace download because the download link inside that guide is dead.

**Comment by guglovich** [comment]
> Follow this guide: https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace but use the DLL you got from the apitrace download because the download link inside that guide is dead.

This is what I did. But perhaps this is due to the fact that the games are used in the D3DX9_42.dll folder

**Comment by K0bin** [comment]
Don't confuse D3DX9_42.dll with d3d9.dll. D3D9**X** is a helper library that sits on top of D3D9 and just normal D3D9 calls just like a game would.

You launched apitrace.exe with Wine, which shows that you clearly didnt follow the guide. Which has you put the wrapper dll next to the games exe and just launch the game itself.

**Comment by guglovich** [comment]
> Don't confuse D3DX9_42.dll with d3d9.dll. D3D9**X** is a helper library that sits on top of D3D9 and just normal D3D9 calls just like a game would.
> 
> You launched apitrace.exe with Wine, which shows that you clearly didnt follow the guide. Which has you put the wrapper dll next to the games exe and just launch the game itself.

That's what I did every now and then according to the guide, I don't understand to take a video for you. The file is in the folder, changed the settings in winecfg, the launch command is in the screenshot.

**Comment by K0bin** [comment]
You play the game with the wrapper dll placed next to the games exe. Then you should find a .trace file in the Desktop folder of the Wine prefix you used. Upload that .trace file.

**Comment by guglovich** [comment]
So I don't know how to prove to you that I am doing exactly according to the instructions.

**Comment by K0bin** [comment]
What exactly is the problem then?

**Comment by guglovich** [comment]
> What exactly is the problem then?

Screenshot error. And this is after following the instructions. I repeat to you.

**Comment by K0bin** [comment]
Please follow this exact guide: https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace

What you're doing in that screenshot is wrong.

**Comment by LeJimster** [comment]
I was just playing StarCraft 2, works fine and I just downloaded the original StarCraft and that works fine too...  I don't have the Remastered to test.
I am using an older wine version than you (lutris-5.7)

**Comment by guglovich** [comment]
After upgrading to wine-staging 5.14-2, the problem disappeared.
