### ISSUE TITLE
Damnation (2009) (Blue Omega Entertainment) not run

### ISSUE THREAD

**Issue by legionpheonix** [doitsujin/dxvk#1707]
Good day. There is a problem starting this game with DXVK + dgvoodoo2. The game starts launching and then crashes.
If run only with DXVK or dgvoodoo2, then everything works fine. But I just need them to work together, since dgvoodoo2 has an upscale screen resolution, even if I set a low resolution in the game, the game itself remains in the native resolution of the monitor. At the same time, the HUD remains as it should be, that is, not small, even the subtitles are clearly visible.
With another game, I managed to achieve this effect.

In the dxvk.conf settings, I did not find the option to scale resolution at high resolution. Anisotropia and msaa anti-aliasing does not work either. And in dgvoodoo2 it works correctly.

### System information
- GPU: Nvidia GTX 1070
- Driver: 451.67
- Wine version: i use Windows 
- DXVK version: 1.7

### Log files
[DamnGame_d3d11.log](https://github.com/doitsujin/dxvk/files/5026138/DamnGame_d3d11.log)
[DamnGame_dxgi.log](https://github.com/doitsujin/dxvk/files/5026139/DamnGame_dxgi.log)

**Comment by Blisto91** [comment]
@legionpheonix If you are still around are you able to test this again with latest dxvk/dgvoodoo2/driver ?

**Comment by Blisto91** [comment]
So I've tested this a bit on the Nvidia setup.
This works fine when i tested on linux through proton, but doesn't work with dgvoodoo2 + dxvk on windows no.
I am guessing `warn:  D3D11CoreCreateDevice: Adapter is not a DXVK adapter` means on windows it loads windows own dxgi since it's the same if i only leave the dxvk d3d11 file in place.

**Comment by K0bin** [comment]
Looks like dgvoodoo is trying to load DXVK from C:\Windows\system32 instead of the application folder.

Nothing we can do in that case and it's one of the reasons why Windows is not a supported platform for DXVK.
