### ISSUE TITLE
Dxvk for Old nvidia Drivers. (369.09)

### ISSUE THREAD

**Issue by CloudHaze** [doitsujin/dxvk#1715]
Was wondering if Dxvk works on old Nvidia driver:  369.09
My GPU: GTX 1060 6gb
Current driver: 369.09 (i found this generic latest drivers by microsoft) works good in my system.  As I play games from 2010/2018 
but I tried to run any version of dxvk .dll files in games such Megaman XX,  Torch Light II and so on, and all crashed.
OS: Windows 10.

**Comment by Joshua-Ashton** [comment]
No. Just get a new driver.

**Comment by K0bin** [comment]
There's no good reason to use drivers that old.

**Comment by CloudHaze** [comment]
What about the Nvidia Driver 417.35?

**Comment by Joshua-Ashton** [comment]
Just use the latest drivers *please*. There is no reason to use massively outdated crap other than to give me and you a headache.

**Comment by CloudHaze** [comment]
Awwe is because i tried a driver via Nvidia Official site which is the: Geforce1060 451.67-desktop-win10-64bit-international-dch-whql and gosh, was having issues on my GTX 1060 6gb., like old games such Torch light II the (vsync in game) didn't worked for some reason.
