### ISSUE TITLE
Windows 10  DXGI implementation vs DXVK's version / Question

### ISSUE THREAD

**Issue by seanmacky** [doitsujin/dxvk#1716]
Hi i was wondering would there be any performance impact or gains from using Window 10's own DXGI instead of DXVK's DXGI implementation ?

Specifically with GW2 64bit.

Thank you

**Comment by DadSchoorse** [comment]
DXVK's d3d10 and d3d11 do not work with the windows dxgi. GW2 uses d3d9 iirc and d3d9 doesn't use dxgi, so it doesn't matter which one you use.

**Comment by doitsujin** [comment]
You *cannot* use DXVK with the Windows implementation of DXGI. It simply won't work.

GW2 is a D3D9 game, so it shouldn't need DXGI in the first place.
