### ISSUE TITLE
D3D9] - Tomb Raider: Legend (7000) - Low performance #1685

### ISSUE THREAD

**Issue by seanmacky** [doitsujin/dxvk#1717]
@K0bin @Joshua-Ashton

Hi, Any chance of getting the 64 bit build with these fixes for me to test as i have the same issues on the same games. I saw the test was cancelled for pipeline # 1231 so the build bot didn't generate the 64bit dll's.

I'm not tech savvy enough to build this myself.

I'm happy to donate $10 to you via paypal for your time doing this !

Thank you

**Comment by K0bin** [comment]
https://git.froggi.es/doitsujin/dxvk/-/jobs/1336/artifacts/download?file_type=archive

**Comment by Joshua-Ashton** [comment]
Yes, automated builds for every commit can be found on https://git.froggi.es/doitsujin/dxvk/-/jobs

**Comment by K0bin** [comment]
Please close this issue. The actual problem is fixed.
