### ISSUE TITLE
[d3d9] Mirror's Edge - low CPU performance with amdvlk-pro driver

### ISSUE THREAD

**Issue by aufkrawall** [doitsujin/dxvk#1718]
CPU performance is rather low with amdvlk-pro driver (crashes with open amdvlk 2020.Q3.3-1 driver from Arch repo, so I couldn't test performance with it), no difference between Windows and Linux:
![Screenshot_20200811_135121](https://user-images.githubusercontent.com/13510490/89895499-3794ad00-dbdc-11ea-810a-74ba9f4d33b8.png)
It's 70-80fps with amdvlk-pro, 120-130 with native D3D9 and 170-180 with RADV. Might of course well be a driver issue, but reporting for closure. :)
Unfortunately, RADV is hit very harshly by MSAA performance penalty, so either choice isn't overly compelling. The Nvidia driver shows high CPU and MSAA performance at the same time with this game and DXVK (even faster when GPU bound vs. D3D9 native).

You have to disable Unreal Engine frame rate smoothing in the game's config file to get unlocked fps.

### Software information
Mirror's Edge on Steam, 1440p max. details (no vsync, MSAA nor PhysX)

### System information
- GPU: RX 480
- Driver: amdvlk-pro 20.30-1109583 / 20.8.1
- Wine version: wine-tkg-staging 5.14 / Windows 10 2004
- DXVK version: dxvk-master.d92660923acef5066711af43b8afa3196026eb3c

### Apitrace file(s)
https://drive.google.com/file/d/1DqS-TDmqoOnRuxMXzF4BSjgxJ4OOUuMn/view?usp=sharing

### Log files
[MirrorsEdge_d3d9.log](https://github.com/doitsujin/dxvk/files/5056813/MirrorsEdge_d3d9.log)

**Comment by doitsujin** [comment]
We can't really work around the driver being slow.

**Comment by aufkrawall** [comment]
Ok, I'll pass it to the amdvlk guys then. Doesn't seem to be limited to the D3D9 part of DXVK, also BFV shows higher CPU load and more uneven frame time consistency vs. RADV.

**Comment by aufkrawall** [comment]
Fixed with amdvlk-2020.Q4.6 and recent amdvlk-pro.
