### ISSUE TITLE
About Darksiders Warmastered Edition bad performance

### ISSUE THREAD

**Issue by Galcian79** [doitsujin/dxvk#1719]
So this game has well known issues related to Media Foundation.
Aside that, the game has really bad performance on official Proton 5.0.9 with AMD Ryzen 5 2600 and Nvidia GTX 1060, which is strange since it should be a d3d11game. Frame rate constantly drops from 60 fps to 20 fps, with both cpu and gpu loads sitting around 30 - 40%
Obviously it works flawlessly on Windows.
If you show me a tutorial on how to make a d3d11 api trace i'll be glad to post the log.

**Comment by doitsujin** [comment]
Does it run as badly with DXVK on Windows as well?

**Comment by doitsujin** [comment]
So @K0bin has had a look at the game and it seems like this game tries to read data that's supposed to be write-only, i.e. a game bug.
