### ISSUE TITLE
[D3D9] Guildwars 2 crashes after game update

### ISSUE THREAD

**Issue by logan001** [doitsujin/dxvk#1720]
Today GW2 had an update.
After the update the game crash after launch.
The game works with only wine. it works on windows with dxvk too. only in linux crashes. 
Also the strange thing is that selecting 1.7L-9f6f6a7 for dxvk in lutris the game will not crash. i've try to compile it myself from git but it still crashes. i've tried to get the build for your build server and it still crashes.

### Software information
Name of the game, settings used etc.

### System information
- GPU: nvidia 970
- Driver:   450.56.06 and  450.56.02
- Wine version: wine-5.13 (Staging)
- DXVK version: d92660923acef5066711af43b8afa3196026eb3c / 9f6f6a797931eed1d1ff1357cff16b5b1a80f62d (my buld crashes but the one in lutris works)

### Apitrace file(s)
- [here](https://drive.google.com/drive/folders/11ajwoWEPCePK4PnEMSTaT46DWUK6vRyp?usp=sharing)
edit: trace is from windows
### Log files
- d3d9.log: i have 2 logs in same place as the trace. one log is with latest build form your build server and the other is with lutris own version of dxvk

**Comment by doitsujin** [comment]
Should be fixed by d4f6ccb8a8978ad91af6df4bf8647badbbe267ea.

**Comment by logan001** [comment]
yeap.
thank you
