### ISSUE TITLE
[Question] Shared resources

### ISSUE THREAD

**Issue by Klairm** [doitsujin/dxvk#1722]
Is there a plan in anytime for add shared resources? Some games/modifications and programs requires it like for example:  FiveM, RageMP, alt:V

So is there anytime planned to add it? Anything we can do for help?

Stay safe!

**Comment by doitsujin** [comment]
No, because it's not supported in wine.

**Comment by Klairm** [comment]
Didn't they implement it at least for vulkan? https://www.winehq.org/pipermail/wine-devel/2019-October/153443.html

Also I gave GTA V mods as example but there are other programs that will benefit

Sorry if I annoy you with this, thanks for the answer and your great work on DXVK! ;)

**Comment by doitsujin** [comment]
The patch series was never merged into wine.
