### ISSUE TITLE
Crash on start with every directx9 game on a RX 480

### ISSUE THREAD

**Issue by AlexanderWKoenig** [doitsujin/dxvk#1724]
### Software information
every directx9 game

### System information
- GPU: RX 480
- Driver: mesa-tkg-git 20.3.0 devel
- Wine version: wine-5.7.r0.gc44e0cf60a ( TkG Plain Esync )
- DXVK version: 1.7.1
- Linux 5.7.15-28-tkg-bmq  on Manjaro

[FEAR_d3d9.log](https://github.com/doitsujin/dxvk/files/5071616/FEAR_d3d9.log)

I cant manage to run any d3d9 game on my current setup. I have switched from an nvidia 1060 to a RX 480. Before that, all my games just run pretty well with dxvk.

All i did after changing the cards was to move /etc/X11/xorg.conf to another place to make Xstart and installing mesa-tkg-git 20.3.0 as well as the lib32 version.

All my d3d11 games are working! But every single directx9 game crashes on startup. With a clean WINEPREFIX the d9d3 games are running with opengl. But when I install dxvk into it, they crash. For an example i added the log of FEAR and in the terminal it always crashes like this:

info:    Exclusive FS: 0
info:  Setting display mode: 1920x1080@0
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_DITHERENABLE
wine: Unhandled page fault on read access to 00000014 at address E3F36B9A (thread 0041), starting debugger...
Unhandled exception: page fault on read access to 0x00000014 in 32-bit code (0xe3f36b9a).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:e3f36b9a ESP:02f2bf20 EBP:0000000d EFLAGS:00010246(  R- --  I  Z- -P- )
 EAX:da8645dc EBX:e72ae6c0 ECX:00000000 EDX:da8646a0
 ESI:da81f870 EDI:da8645dc
Stack dump:
0x02f2bf20:  da863c50 00000009 02f2bf54 00000006
0x02f2bf30:  02f2bf48 da8655b8 da8760e4 00000000

**Comment by K0bin** [comment]
Seems like a setup issue on your end:
![grafik](https://user-images.githubusercontent.com/1131720/90195768-9b7cc880-ddca-11ea-8dba-d1ed5497ca99.png)

**Comment by Joshua-Ashton** [comment]
Please make sure to update your Mesa, there was a bug recently.

**Comment by AlexanderWKoenig** [comment]
> Please make sure to update your Mesa, there was a bug recently.

I've tested these mesa versions (all also with lib32) today with the same Issue:

- mesa 20.1.5. Manjaro
- mesa-aco-git 20.1.0_rc4.20200527.648768b32a6-10 chaotic-aur
- mesa-tkg-git 20.3.0_devel.127111.493298528a8-1 chaotic-aur
- mesa-git 20.3.0_devel.127126.92f65e28fee-1 compiled myself from aur

Could it be, that my old NVIDIA GPU left some caches, which break theese d3d9 games? But why would run all d3d11 games...

**Comment by CME42** [comment]
> info:    Driver version   : 2.0.153
Seems like you're using amdvlk and not mesa radv, this driver is currently broken with d3d9 DXVK.

**Comment by AlexanderWKoenig** [comment]
My MangoHud shows, that radv/aco is used in Rocket League. So radv should be working. 
![20200814234359_1](https://user-images.githubusercontent.com/40361614/90295125-6c2c9100-de88-11ea-8128-47da3c607f14.jpg)

**Comment by CME42** [comment]
Rocket League defaults to the 64bit client, FEAR is a 32bit game so i guess there is still some 32bit amdvlk leftover on your system.

**Comment by AlexanderWKoenig** [comment]
> Rocket League defaults to the 64bit client, FEAR is a 32bit game so i guess there is still some 32bit amdvlk leftover on your system.

Yes you are right, Crysis3 32but runs with amdvlk. How do i change this behaviour?
