### ISSUE TITLE
Vinyls not rendering in Soapbox Raceworld (Need for Speed: World) with 1.7.1

### ISSUE THREAD

**Issue by Unaccounted4** [doitsujin/dxvk#1727]
With DXVK 1.7.1 in Lutris, the vinyl stickers on cars in Soapbox Raceworld don't render.
They say a picture is worth a thousand words, so here's two:

**1.7L-9f6f6a7**
![Screenshot_20200814_220844](https://user-images.githubusercontent.com/45717994/90293560-4bf6d500-de7c-11ea-8b49-25ebb95842c0.png)

**1.7.1**
![Screenshot_20200814_201120](https://user-images.githubusercontent.com/45717994/90293575-53b67980-de7c-11ea-86f6-66f3dc368f41.png)

### Software information
Soapbox Raceworld (Need for Speed: World) in Lutris, default settings except for DXVK enabled and MangoHud.

### System information
- GPU: GeForce GTX 1080
- Driver: 450.57
- Wine version: lutris-nfsw-5.4-x86_64
- DXVK version: 1.7.1

### Apitrace file(s)
**EDIT:** [nfsw.trace.tar.xz](https://drive.google.com/file/d/1juiJMPHN0YjQC2wEyKRY4FZUOOzPzWg0/view?usp=sharing)
EDIT2: [nfsw.trace.17L.tar.xz](https://drive.google.com/file/d/14q7ajKdrYc5FAMHBFKPqhnD9jCCqRQnC/view?usp=sharing
)
### Logs
**1.7L-9f6f6a7**
[nfsw_d3d9-1.7.log](https://github.com/doitsujin/dxvk/files/5077333/nfsw_d3d9-1.7.log)
[nfsw_dxgi-1.7.log](https://github.com/doitsujin/dxvk/files/5077334/nfsw_dxgi-1.7.log)

**1.7.1**
[nfsw_d3d9-1.7.1.log](https://github.com/doitsujin/dxvk/files/5077337/nfsw_d3d9-1.7.1.log)
[nfsw_dxgi-1.7.1.log](https://github.com/doitsujin/dxvk/files/5077338/nfsw_dxgi-1.7.1.log)

**Comment by K0bin** [comment]
Your apitrace is an OpenGL apitrace and pretty much empty. Please make a D3D one following this guide: https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace

(The download link in that is dead, you can just download it from the apitrace website instead.)

**Comment by Unaccounted4** [comment]
My bad. I've updated the original post.

**Comment by K0bin** [comment]
The vinyl was visible when you made the trace, right?

It doesn't show up when replaying with DXVK 1.7 or Nvidias D3D9 driver on Windows. 
![grafik](https://user-images.githubusercontent.com/1131720/90297368-823d5000-de8e-11ea-9edf-2d9d92458ac3.png)

**Comment by Unaccounted4** [comment]
No, the trace was captured with 1.7.1. I'll capture another with 1.7.

**Comment by Unaccounted4** [comment]
Added 1.7L-9f6f6a7 trace to the original post.
