### ISSUE TITLE
Teenage Mutant Ninja Turtles (2003)  does not start

### ISSUE THREAD

**Issue by legionpheonix** [doitsujin/dxvk#1731]
I run the tmnt.exe file and nothing happens. The game just crashes instantly. It does not display any errors at startup.

### System information
- GPU: Nvidia GTX 1070
- Driver: 451.67
- Wine version: i use Windows
- DXVK version: 1.7

### Log files
[tmnt_d3d11.log](https://github.com/doitsujin/dxvk/files/5079209/tmnt_d3d11.log)
[tmnt_dxgi.log](https://github.com/doitsujin/dxvk/files/5079210/tmnt_dxgi.log)

**Comment by doitsujin** [comment]
And this game works correctly with wined3d?

**Comment by legionpheonix** [comment]
> А эта игра корректно работает с wined3d?

To make DXVK work. I run all games through the dgvoodoo2 wrapper. TMNT is the first game to refuse to launch with DXVK.

**Comment by doitsujin** [comment]
This doesn't answer my question. Does this game work **without** DXVK and **with** dgvoodoo2 or not?

**Comment by legionpheonix** [comment]
> Это не ответ на мой вопрос. Эта игра работает **без** DXVK и **с** dgvoodoo2 или нет?

Yes, it runs fine with DX9 without wrappers. And with dgvoodoo2 it runs as DX11.

**Comment by K0bin** [comment]
Try using DXVK D3D9 implementation instead of DgVoodoo.

**Comment by legionpheonix** [comment]
Yes it starts without dgvoodoo2.
Is it possible to somehow combine dgvoodoo2 with DXVK?
The reason is simple. We need 4K upscale and anti-aliasing to work correctly, while the HUD interface is in native resolution, without downscaling.
If dxvk.conf had the ability to forcibly set a high resolution, and in the game it's native, it would help me a lot.
[tmnt_d3d9.log](https://github.com/doitsujin/dxvk/files/5079390/tmnt_d3d9.log)

**Comment by tannisroot** [comment]
``` The reason is simple. We need 4K upscale and anti-aliasing to work correctly, while the HUD interface is in native resolution, without downscaling.
If dxvk.conf had the ability to forcibly set a high resolution, and in the game it's native, it would help me a lot.
```
Can you elaborate on that, but in your native language please?

**Comment by legionpheonix** [comment]
> Не могли бы вы уточнить это, но, пожалуйста, на вашем родном языке?

Я понимаю что переводчик гугл так себе.
Старые игры имеют одну особенность, интерфейс (HUD - жизни, количество патронов и т.д.) на 640x480 или 800x600. Через dgvoodoo2 я назначаю разрешение в 4K или 1080p, при этом меняется только 3D окружение, интерфейс игры остаётся в родном разрешении, если в самой игры назначено 640x480. То есть такая обманка upscale. Игра может даже поддерживать 1280x720 widescreen, но при этом если ставишь в самой игре 1920x1080, то интерфейс становиться очень мелким и субтитры в том числе.
В DXVK я не нашёл такой функции, чтобы не пользоваться.
В соседней теме про Властелин Колец, там ещё сложнее ситуация. Так как игры работает исключительно на DX8, у DXVK нету его. Тем самым мне приходится в любом случае использовать совместно dgvoodoo2+DXVK.

**Comment by tannisroot** [comment]
> Так как игра работает исключительно на DirectX8, у DXVK нету самой dll библиотеки. Тем самым мне приходится в любом случае использовать совместно dgvoodoo2+DXVK
Для таких игр можно использовать d3d8to9 вместе с d3d9.dll из DXVK

**Comment by legionpheonix** [comment]
> Для таких игр можно использовать d3d8to9 вместе с d3d9.dll из DXVK

Огромное спасибо за наводку. Работает стабильно и fps не падает.

**Comment by legionpheonix** [comment]
> Для таких игр можно использовать d3d8to9 вместе с d3d9.dll из DXVK

Ещё один нюанс. Когда подставил D3D9.dll от DXVK, он не все настройки от Nvidia подхватил. В режиме DirectX 11 все настройки берёт, но fps проседает.

**Comment by DuckerMan** [comment]
by the way, what is `d3d8to9` ?

**Comment by Blisto91** [comment]
@legionpheonix Is this still a issue with newer versions?
This game seems very hard to get a hold of.

**Comment by Blisto91** [comment]
If any of you still have this issue then comment here again.

**Comment by Iglu47** [comment]
just a little note for Wine users:
it seems that in _some cases_ the use of a virtual desktop can help.

<details><summary>screenshot</summary>
<p>

![tmnt2003_dgvoodoo2](https://user-images.githubusercontent.com/25866099/178157981-3a782975-fcfc-423b-854e-b884d13323e0.png)

</p>
</details>

**Comment by Iglu47** [comment]
just a little note for Wine users:
it seems that in _some cases_ the use of a virtual desktop can help for this game.

<details><summary>screenshot</summary>
<p>

![tmnt2003_dgvoodoo2](https://user-images.githubusercontent.com/25866099/178157981-3a782975-fcfc-423b-854e-b884d13323e0.png)

</p>
</details>
