### ISSUE TITLE
The Lord of the Rings: The Return of the King (2003) low FPS

### ISSUE THREAD

**Issue by legionpheonix** [doitsujin/dxvk#1732]
The game is slow and has an unstable FPS of 60-25

### System information
- GPU: Nvidia GTX 1070
- Driver: 451.67
- Wine version: i use Windows
- DXVK version: 1.7

### Log files
[ROTK_d3d11.log](https://github.com/doitsujin/dxvk/files/5079339/ROTK_d3d11.log)
[ROTK_dxgi.log](https://github.com/doitsujin/dxvk/files/5079340/ROTK_dxgi.log)

**Comment by K0bin** [comment]
Please try the latest master. You can find a build here: https://git.froggi.es/doitsujin/dxvk/-/jobs

If it's still slow, make an apitrace so we can take a look at what the game is doing.
Here's a guide how you make one: https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace
You'll notice that the download link in that guide is dead. Use this one instead: https://ci.appveyor.com/api/projects/jrfonseca/apitrace/artifacts/build/apitrace-latest-win32.7z?branch=master&job=msvc32

**Comment by legionpheonix** [comment]
> Please try the latest master. You can find a build here: https://git.froggi.es/doitsujin/dxvk/-/jobs

Tried the latest master 89d36e1d. No change, same problems.
### Log files
[ROTK_d3d11.log](https://github.com/doitsujin/dxvk/files/5079383/ROTK_d3d11.log)
[ROTK_dxgi.log](https://github.com/doitsujin/dxvk/files/5079384/ROTK_dxgi.log)

> If it's still slow with that, make an apitrace so we can take a look at what the game is doing.

Put the files d3d11.dll and dxgi.dll
The game won't start, no log files are generated.

**Comment by legionpheonix** [comment]
I was able to start the game with d3d8.dll
Here is the .trace file
https://mega.nz/file/EZg02KpA#9Iz2KMM1V7aJVXHEeEN9ADHSaej4MPn5QaO9jLKwMsw

**Comment by legionpheonix** [comment]
Launched the game with dgvoodoo2 d3d8.dll
Then I took the files from apitrace: d3d11.dll, dxgi.dll, dxgitrace.dll
The game started, I managed to choose the language, and then the logo and everything was written down. I waited 10 minutes and no reaction.
Here is the update .trace file
https://mega.nz/file/xExjXJBY#OzXeMGIo4o6PonzFTEc5idPftGG1zjOqHlukih1iISU

**Comment by legionpheonix** [comment]
Thank you very much. As of the latest 1.7.2 from https://git.froggi.es/doitsujin/dxvk/-/jobs, the game works fine. There are no FPS drawdowns.
