### ISSUE TITLE
Borderlands 2 - DXVK 1.7.1 breaks inventory item rendering

### ISSUE THREAD

**Issue by magicmyth** [doitsujin/dxvk#1734]
When using DXVK 1.7 in Proton 5.9 or the DXVK bundled with Proton-5.9-GE-5-ST (seems to be commit 3322da4 ) the inventory renders correctly but somewhere between then and DXVK 1.7.1 this has broken.

Note, as a hail mary I tried `d3d9.supportDFFormats = False` but it made no difference.

### Software information
Borderlands 2 on Steam.

### System information
- GPU: Radeon RX 580
- Driver: Mesa 20.1.5
- Wine version: Proton-5.9-GE-5-ST

- DXVK version: 1.7.1

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log: [Borderlands2_d3d9.tar.gz](https://github.com/doitsujin/dxvk/files/5095820/Borderlands2_d3d9.tar.gz)

If need be I'll have a go at doing an API trace later.

**Comment by magicmyth** [comment]
Screenshot:
![bd2-dxvk-1 7 1-no-inv-img](https://user-images.githubusercontent.com/847415/90625314-45b48000-e211-11ea-9416-2b565fab28fa.jpg)

**Comment by doitsujin** [comment]
Known issue, should already be fixed in master.

**Comment by magicmyth** [comment]
Ah didn't realise one of those last couple of commits had already solved the issue. I shouldn't have been afraid to build and test as I've now successfully built master and it is indeed fixed!

Thanks all!
