### ISSUE TITLE
[d3d9] Hearts of Iron IV - nation flags are not rendered correctly

### ISSUE THREAD

**Issue by ms178** [doitsujin/dxvk#1735]
Both with DXVK 1.7.1 x64 and latest master, there are some rendering issues on Windows 10 using dxgi.dll and d3d9.dll in Hearts of Iron IV. The flags of the nations in the game in several occasions are not rendered correctly, this affects also the rendering of the units (and other parts of the games where flags are shown, the screenshot below illustrates it).

The GPU is a AMD Vega 56 with Adrenalin 20.8.2.

![HoI_IV_DXVK](https://user-images.githubusercontent.com/19559105/90650011-a0fb6800-e23b-11ea-891e-50e3ef9e1942.png)

**Comment by K0bin** [comment]
Try using latest master. 1.7.1 has a regression in D3D9. FWIW DXGI.dll is unnecessary for D3D9 games like Hearts of Iron IV.

**Comment by ms178** [comment]
As stated above, the issue is also reproducable with the latest master. And thanks for the hint about the DXGI.dll, I wasn't aware of it.

**Comment by K0bin** [comment]
If thats the case, please actually provide the logs and (most importantly) the apitrace that the issue template asks for.

**Comment by doitsujin** [comment]
Also, what exactly isn't being rendered correctly? On the screenshot it's not at all obvious what's wrong and what it should look like.

**Comment by DadSchoorse** [comment]
The flags work fine for me on the latest nvidia dev driver.

**Comment by ms178** [comment]
@doitsujin I've attached a screenshot how it should look like.

![HoI_IV_DX9](https://user-images.githubusercontent.com/19559105/90670404-69001f00-e253-11ea-98ba-d0b87c29615b.png)

Here is the log: 
[hoi4_d3d9.log](https://github.com/doitsujin/dxvk/files/5098256/hoi4_d3d9.log)

In there, two warnings stand out:

warn:  ConvertFormat: Unknown format encountered: D3D9Format::AL16
warn:  ConvertFormat: Unknown format encountered: D3D9Format::R16

**Comment by K0bin** [comment]
What exactly is wrong in your screenshots? I see plenty of flags there.

**Comment by DadSchoorse** [comment]
@ms178 can you try to create an apitrace? Here's how: https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace (but download apitrace from https://apitrace.github.io/). The one I created replayed fine for everyone, but there might be a difference on AMD vs nvidia. I'm also not seeing the log spam btw.

**Comment by ms178** [comment]
@DadSchoorse Thanks for the hints. Unfortunately I cannot reproduce the error with the provided d3d9.dll which came with apitrace-latest-win64/lib/wrappers which is dated from 12th August 2020 and smaller in size than latest master. If I use the d3d9.dll from latest DXVK master though, the issue re-appears. 

Is there a way to run both d3d9.dll's at the same time? Or more exactly is there a way to run Apitrace with the DLL provided by DXVK latest master? As both share the same name in the directory, I assume both cannot be run at the same time?

**Comment by ms178** [comment]
Here is the new d3d9.log when run with Apitrace:
[hoi4_d3d9.log](https://github.com/doitsujin/dxvk/files/5098947/hoi4_d3d9.log)

I'll update this post if I upped the trace on my Google drive.

**Comment by ms178** [comment]
@K0bin I've re-tested this with my Vega 56 on the latest Windows 10 Insider Preview 10.0.21354, AMD Driver 27.20.21001.7005 from April 1st 2021 (which comes through Windows Update) and most recent DXVK-fb0b11903 as of April 14th 2021. The game version is at 1.10.4. 

In addition to the already described issues with the nation flags, I now get funny christmas decoration-like graphical issues on the sea water. See the attached screenshot. The screen also flickers which isn't captured in the screenshot (I use a HP 25x, 144 Hz with Freesync enabled). The issue is reproducable in borderless window and fullscreen exclusive mode.

![HOI_IV](https://user-images.githubusercontent.com/19559105/114717874-c8a4c080-9d35-11eb-855e-e04ae9ad7db2.jpg)

**Comment by K0bin** [comment]
Can you find out which DXVK commit caused those?

**Comment by ms178** [comment]
@K0bin I cannot bisect, but I tested recent releases and could narrow it down, 1.8.1 is the first release which introduced the funny colored circles, 1.8 is fine. I hope this narrows it down quite a bit.

**Comment by K0bin** [comment]
Does it happen with this build: https://github.com/doitsujin/dxvk/actions/runs/729499140

**Comment by ms178** [comment]
Yes, the screenshot was taken with the latest DXVK-master. The stability is
better with DXVK-master over DXVK 1.8. While the latter doesn't show the
colored circles, it crashes the game after 5 - 10 minutes and returns to
the desktop. I didn't get such a crash with DXVK-master after an hour of
gameplay.

Am Mi., 14. Apr. 2021 um 15:59 Uhr schrieb Robin Kertels <
***@***.***>:

**Comment by Blisto91** [comment]
I think this one can also be closed.
I can reproduce this on proton 6.3-8 and it now renders fine on 7.0-1 and bleeding edge.

**Comment by DadSchoorse** [comment]
> (Can also test on windows if you want me to)

Yes please, I recall there were some issues specific to native d3d9x.

**Comment by Blisto91** [comment]
Okay yes.
R9 380 driver 21.5.2 win10

I first tried 1.8.1 which i reproed the Missing flags and disco nukes hitting poor Finland.
I then tried 1.10 and the portraits were fixed. But the weird flashing colors (disco nukes) are still present. Also with latest master artifact. I did not notice them on Linux. They are kinda hard to miss.

If you need apitrace or anything just say so and i will make one tomorrow.

**Comment by K0bin** [comment]
That looks like a feedback loop.

**Comment by Blisto91** [comment]
I will attempt a test tomorrow on my gfs Nvidia windows setup of that's of any help.

**Comment by K0bin** [comment]
Not necessary.

**Comment by K0bin** [comment]
Please make an apitrace of that issue.

**Comment by Blisto91** [comment]
Will do when I get home today.
I for the funs tried to launch with the amdvlk driver to see if it could reproduce the issue on Linux. But game wouldn't start with it.
Even tho you said it isn't necessary i will also take a quick peek with another rig on both windows and Linux. Just to see what happens.

**Comment by Blisto91** [comment]
Okay i managed to get it running on `amdvlk` 2021q2.5, which is also around the same time where are amd dropped driver support for my GPU on windows. So i guess it makes sense no newer `amdvlk` works.
Anyway i can reproduce it the issue on linux with that driver. But i'm not able to check if the issue has been fixed in the later versions.

[Trace from windows](https://mega.nz/file/Q8oigLza#65XtVsC_Iivw2d-7Ca77STKNyyOuT4bgnQY2i_-Waac) if that's still relevant.

**Comment by Blisto91** [comment]
Oh my bad. I thought a trace was supposed to be without dxvk enabled so i just plucked it into my windows folder next to the exe.

And if i misunderstand and you are not joking then no i didn't nuke anyone (disco nukes was a joke :grin: ). I can get it showing just by going into country selection by picking germany and it shows in the corner in Findland when Multisample level is on along with weather effects.

**Comment by K0bin** [comment]
> I thought a trace was supposed to be without dxvk enabled so i just plucked it into my windows folder next to the exe

Shouldn't matter whether the trace is made with DXVK.

> And if i misunderstand and you are not joking then no i didn't nuke anyone (disco nukes was a joke grin ). 

Now I'm a bit confused. What did you do to cause the graphical issues in your earlier screenshot then? Did you do the same thing in your apitrace?

**Comment by Blisto91** [comment]
> Now I'm a bit confused. What did you do to cause the graphical issues in your earlier screenshot then? Did you do the same thing in your apitrace?

On windows i launch the game with dxvk. Make sure Multisample level isn't set to 0, i have it at 4 and put weather on so it's easier to notice. 
I then select new game -> click the hitler picture -> when the map shows it will be showing in finland. It's cuz the snow storm effect is showing. It will also appear in other places with flakes flying around.
If weather isn't on you can still get it to appear if you zoom in to some of the border lines between provinces, but it's harder.

Ye i did the same. But without dxvk. I can try to get a trace through proton on linux with the amdvlk driver if you want to.

**Comment by K0bin** [comment]
Okay, I get it now. Looked perfectly fine when replaying the apitrace on Nvidia, so I'm writing this off as an AMD Windows/AMDVLK driver bug. We don't really support either of those, so there's nothing to do here.

**Comment by Blisto91** [comment]
Ye i don't mind. The game has a native version and i use radv anyway.
I just wanted to say the original issue was solved and then didn't notice the OP had another issues :grin:

**Comment by ms178** [comment]
@Blisto91 Thanks, I'll try it out next time I get back to Windows. The native Linux version used to work fine albeit with the latest patch, the game doesn't start anymore but that is off-topic. I couldn't get the Windows version to run either, but that might be due to the same problem with that patch.
