### ISSUE TITLE
It's a miracle! :)

### ISSUE THREAD

**Issue by 12sunflowers** [doitsujin/dxvk#1737]
Just want say THANKS A LOT! :) 
In Unreal Tournament 3 & 4 average fps is increasing to ~20fps when using dxvk. And if use dxvk+scanlinesync, result is superstable fps without drops. It's a miracle! :) I love you friends) Successful development for the future! And god bless to all you!

PS That's on Windows system ;)

**Comment by f3ck4r** [comment]
I came just to let you know that I love you guys too!
Thank you for the incredible effort!! 

VULKAN for the WIN!

Cheers from 127.0.0.1 ;D

**Comment by majinsaiyan** [comment]
> 
> 
> Just want say THANKS A LOT! :)
> In Unreal Tournament 3 & 4 average fps is increasing to ~20fps when using dxvk. And if use dxvk+scanlinesync, result is superstable fps without drops. It's a miracle! :) I love you friends) Successful development for the future! And god bless to all you!
> 
> PS That's on Windows system ;)

Sorry for the OT, but are you talking about scanlinesync in RTSS? How did you get it to work? Running RTSS always crashes any game with dxvk on windows for me.

**Comment by K0bin** [comment]
> Running RTSS always crashes any game with dxvk on windows for me.

The way RTSS interacts with Vulkan is broken so it's really hit or miss with DXVK.

**Comment by majinsaiyan** [comment]
> 
> 
> > Running RTSS always crashes any game with dxvk on windows for me.
> 
> The way RTSS interacts with Vulkan is broken so it's really hit or miss with DXVK.

Yeah you're right. I hope they will update it to support this.

**Comment by steemandlinux** [comment]
80 FPS in GuildWars with the wine-esync too.

**Comment by Kallestofeles** [comment]
Also thought about opening another issue on this topic before stumbling upon this one. I too wish to say HUGE THANKS to the people committed to this project!
Not only has it completely changed the gaming on Linux, but it has even fixed some issues with older games on Windows! I recently tried getting the old Tomb Raider 3-5 games working nicely with AMD 5500 XT + dgVoodoo2 but it always ended up with no textures (everything rendered, but pure white color) whenever any of the DirectX APIs were selected. By injecting the games with DXVK, those issues are now resolved.
What an amazing project, what amazing people, thank you!

*ribbit*

**Comment by 12sunflowers** [comment]
> I recently tried getting the old Tomb Raider 3-5 games working nicely with AMD 5500 XT + dgVoodoo2 but it always ended up with no textures (everything rendered, but pure white color)

Hi!) I am also have same issue with dgVoodoo2 and white textures. I am use older version dgVoodoo2 - 2.54, textures work fine in it. https://www.vogons.org/viewtopic.php?f=59&t=65340&p=735339#p735339

>but it has even fixed some issues with older games on Windows!
Also thanks for info that old games can work with DXVK!
