### ISSUE TITLE
Quake Champions crash at launch on Windows

### ISSUE THREAD

**Issue by 12sunflowers** [doitsujin/dxvk#1738]
Windows 7x64, Windows10x64. Steam. When i start Quake Champions it crash at launch. Sorry.

### Software information
Quake Champions

### System information
- GPU: rx580
- Driver: Adrenaline 20.7.1
- Wine version: 
- DXVK version: 1.7

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
- d3d11.log: https://pastebin.com/raw/4KP1Ds3f
- dxgi.log: https://pastebin.com/raw/xp5jq8jN

PS Quake Champions crash dump http://www.mediafire.com/file/nwb5uoy1myq9x0j/CrashDump.txt/file

**Comment by doitsujin** [comment]
Game runs fine on Linux. There's a reason why we [don't really care](https://github.com/doitsujin/dxvk/wiki/Driver-support#windows-drivers) about Windows, especially for D3D11.
