### ISSUE TITLE
[D3D9] Dungeon & Fighter Some font formats are unrecognized.

### ISSUE THREAD

**Issue by hauntek** [doitsujin/dxvk#1746]
Hello, I'm running the **Dungeon & Fighter** game. I ran a problem

Using the image is DirectX 9, boot can normally enter the game, can run normally, but seems to encounter a problem! That is, the font is incomplete, FPS display in the game is abnormal, even the frame rate will not be displayed, the map and audio are normal, even better than the d3d9 display effect, except for the incomplete display of Chinese font and the rendering of chat box!

![VOJM@RYC9%B Z$8G }N G5](https://user-images.githubusercontent.com/17927997/91081238-6188ad80-e679-11ea-8c40-7ce6ea412d6d.png)

**I am directly in the windows 10 system to replace d3d9. DLL to run the game**

### Software information
**Dungeon & Fighter x64 bit client**, High texture, high quality, shadow, windowing (800x600), vertical synchronous open.

### System information
- GPU:Radeon RX 590
- Driver:20.8.2
- Wine version: -
- DXVK version: 1.7.1

### Log files
[dnf_d3d9.log](https://github.com/doitsujin/dxvk/files/5119572/dnf_d3d9.log)

**Comment by K0bin** [comment]
Does 1.7.0 or master also have this issue?

**Comment by hauntek** [comment]
> 1.7.0或master也存在此问题吗？

Yes, 1.7.0 is the same problem.
### Log files
[dnf_d3d9.log](https://github.com/doitsujin/dxvk/files/5119663/dnf_d3d9.log)

**Comment by K0bin** [comment]
Please make an apitrace so we can look into this.
Here's a guide how you make one: https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace
You'll notice that the download link in that guide is dead. Use this one instead: https://ci.appveyor.com/api/projects/jrfonseca/apitrace/artifacts/build/apitrace-latest-win32.7z?branch=master&job=msvc32

**Comment by nforestcat** [comment]
it gets font not from system but from the folder inside

**Comment by K0bin** [comment]
We still need an apitrace if you want someone to look into this.

**Comment by nforestcat** [comment]
dxvk and apitrace both uses d3d9.dll so i don't know how to use both.
using only apitrace, this is the link
https://drive.google.com/file/d/18BmlF8ivqWOYSDCgJQE3rUwfNKdS781C/view?usp=sharing

**Comment by Blisto91** [comment]
@hauntek @nforestcat Can you check this again with latest version?
I can see missing text in the trace, but that also happens with wined3d so might just be the trace itself.

**Comment by nforestcat** [comment]
> @hauntek @nforestcat Can you check this again with latest version?
> I can see missing text in the trace, but that also happens with wined3d so might just be the trace itself. (or something on my end)

works fine with latest version(both game and dxvk)
