### ISSUE TITLE
[D3D9] Glide Demo running through nGlide crashes after intro

### ISSUE THREAD

**Issue by tannisroot** [doitsujin/dxvk#1748]
Glide demo running using nGlide 2.10 with DXVK (current master) seems to work fine during introduction, but when it tries to render 3D stuff, it crashes. This does not happen with WineD3D.
For reference, here's a video of the demo: https://youtu.be/yXjkdMXjQPU
With DXVK, it crashes at around 1:01 (video timestamp).

### System information
- GPU: GTX 1070
- Driver: 450.66
- Wine version: lutris-5.7-8
- DXVK version: 9433d0cb

### Apitrace file(s)
The issue is not reproducible through Apitrace, but the demo is public and free (http://xona.com/labs/demos/tobecontinued/).
Here it is with nGlide dlls included: 
[tbc.zip](https://github.com/doitsujin/dxvk/files/5130070/tbc.zip)

### Log files
- d3d9.log: [tbc_d3d9.log](https://github.com/doitsujin/dxvk/files/5130073/tbc_d3d9.log)

**Comment by Joshua-Ashton** [comment]
This got fixed already.
