### ISSUE TITLE
[D3D9] Halo CE' Sapien tool has issue with MDI container

### ISSUE THREAD

**Issue by marcospampi** [doitsujin/dxvk#1751]
Halo CE has a set of tools named Halo Editing Kit (HEK) which lets users create their custom content,
one of such tool is Sapien, this tool is the scene editor.

Sapien should look like this:
![sapien_overview_01_large](https://user-images.githubusercontent.com/25354450/91633912-815b0100-e9ec-11ea-80d8-105167386df4.gif)
Though this is what I get using dxvk ( I cannot test in wine's d3d ~since it crashes instantly~ doesn't render game view anymore ):
![Schermata da 2020-08-29 11-42-45](https://user-images.githubusercontent.com/25354450/91634023-591fd200-e9ed-11ea-9d58-f8e4c572293a.png)
I can drag windows , so I can expose the render window, and it's correct nonetheless:
![Schermata da 2020-08-29 11-43-40](https://user-images.githubusercontent.com/25354450/91634030-7f457200-e9ed-11ea-9461-422c58f431b5.png)

### Software information
Name of the game, settings used etc.
**Halo CE Editing Kit - Sapien.exe**
### System information
- GPU: AMD RX 460
- Driver: amdgpu-pro 20.20
- Wine version: 5.15
- DXVK version: 1.7.1

### Apitrace file(s)
- Put a link here

### Log files
[sapien_d3d9.log](https://github.com/doitsujin/dxvk/files/5145074/sapien_d3d9.log)

**Comment by doitsujin** [comment]
Does this work any better on Windows with DXVK? In general, applications that mix D3D with regular GUIs are kind of expected to have issues on wine.

Also, please post the full wine log.

**Comment by marcospampi** [comment]
How do I get the wine log?
I can't try on Windows sadly.

**Comment by doitsujin** [comment]
Basically just redirect stdout + stderr to a file when running the application, i.e. `wine sapien.exe > ~/log.txt 2>&1`

**Comment by marcospampi** [comment]
It is mostly the same as the sapien_d3d9.log
[log.txt](https://github.com/doitsujin/dxvk/files/5145118/log.txt)

**Comment by doitsujin** [comment]
> 0024:fixme:vulkan:X11DRV_vkCreateWin32SurfaceKHR Application requires child window rendering, which is not implemented yet!
> err:   Failed to create surface

Yeah, as expected, wine bug.

I think there's a patch set floating around somewhere to fix this, maybe @Joshua-Ashton knows more, but this is definitely not something we can fix on our end.

**Comment by jqadev** [comment]
https://github.com/ValveSoftware/wine/pull/91
