### ISSUE TITLE
Truck Life black screen at startup

### ISSUE THREAD

**Issue by IvoAndonov** [doitsujin/dxvk#1752]
I just installed Truck Life for the first time since it was released and at first looked OK - the intro video played fine. But after that I got stuck to a black screen with a white stripe on it and my guess is that this is the brightness setting screen. There are no controls on that screen, so there's nothing I can do to get to the menu.

The game requires DX11 only, so I copied the 64-bit d3d11.dll and dxgi.dll to the main dir of the game. There's only 1 warning in the logs that's worth mentioning: warn:  DXGI: MakeWindowAssociation: Ignoring flags. The other warnings are for VR which I don't have (and I doubt that my video card would support anyway).

### Software information
Truck Life, game default settings - never got the chance to reach the main menu with the options.

### System information
- GPU: GTX 1050 Ti 4GB
- Driver: 450.66
- Wine version: 5.16 
- DXVK version: 1.7 & 1.7.1 - both with the same result as described above.

### Log files
[TruckLife_d3d11.log](https://github.com/doitsujin/dxvk/files/5147203/TruckLife_d3d11.log)
[TruckLife_dxgi.log](https://github.com/doitsujin/dxvk/files/5147204/TruckLife_dxgi.log)

**Comment by mozo78** [comment]
This isn't a DXVK bug. The game is running fine with Windows Media Foundation installed.
