### ISSUE TITLE
PGA TOUR 2K21 validation errors with 3D image views

### ISSUE THREAD

**Issue by hakzsam** [doitsujin/dxvk#1756]
See https://gitlab.freedesktop.org/mesa/mesa/-/issues/3472

### Software information
PGA TOUR 2K21, default settings.

### System information
- GPU: AMD NAVI10
- Driver: RADV
- Proton version: Proton 5.0-9
- DXVK version: v1.7-8-g51531e4a7

### Apitrace file(s)
- https://people.freedesktop.org/~hakzsam/golf.trace

### Log files
```
VUID-VkImageSubresourceRange-layerCount-01721(ERROR / SPEC): msgNum: 1022674482 - Validation Error: [ VUID-VkImageSubresourceRange-layerCount-01721 ] Object 0: handle = 0xa98c000000a98c, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x3cf4c632 | vkCreateImageView: pCreateInfo->subresourceRange.layerCount is 0. The Vulkan spec states: If layerCount is not VK_REMAINING_ARRAY_LAYERS, it must be greater than 0 (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkImageSubresourceRange-layerCount-01721)
    Objects: 1
        [0] 0xa98c000000a98c, type: 10, name: NULL
```

**Comment by doitsujin** [comment]
It seems like the trace is broken since it does not contain DXGI initialization calls, which makes it not replayable; it might be necessary to set `WINEDLLOVERRIDES=dxgi=n`.
