### ISSUE TITLE
[d3d9] Battle Engine Aquila → broken textures

### ISSUE THREAD

**Issue by NerosTie** [doitsujin/dxvk#1757]
WineD3D:
![battle-engine-aquila-wined3d](https://user-images.githubusercontent.com/4572452/92332572-33df3380-f07f-11ea-904a-e964a1586740.png)

DXVK:
![battle-engine-aquila-dxvk](https://user-images.githubusercontent.com/4572452/92332576-3b9ed800-f07f-11ea-97bf-b37b9258c374.jpg)

### System information
- GPU: Nvidia Geforce 730M
- Driver: 450.66
- Wine version: Proton 5.0-9 
- DXVK version: 1347

### Apitrace file(s)
https://mega.nz/file/j6JwmIra#MSxWfQyvzIKfcA0cMBkTk4YUnZS4ZEEq6x-wht7VHko

### Log files
[steam-1346400-wined3d.log](https://github.com/doitsujin/dxvk/files/5180089/steam-1346400-wined3d.log)
[steam-1346400-dxvk.log](https://github.com/doitsujin/dxvk/files/5180088/steam-1346400-dxvk.log)

**Comment by K0bin** [comment]
@NerosTie At some point we must surely be done with your library of games. :D

Anyway, thanks for the good bug report.

**Comment by NerosTie** [comment]
Tested with Proton 6.3 and DXVK 1.8.1 and it works perfectly, thanks!

@K0bin my library is bigger and bigger 😱
