### ISSUE TITLE
Assasin's Creed Odyssey on Windows 10 is constantly flickering on the top-left part of the monitor no matter what.

### ISSUE THREAD

**Issue by GrTsPat** [doitsujin/dxvk#1760]
After the loading screen and when the game engine has loaded being on the main menu. The game gets almost totally unresponsive to the mouse or keyboard inputs.

**Comment by doitsujin** [comment]
This is due to some DXGI nonsense and I honestly can't be bothered to work around that. Just use borderless mode, with DXVK there's basically no difference to "real" fullscreen mode anyway.

**Comment by GrTsPat** [comment]
Thanks a lot for the answer! I will try the borderless mode then. And sorry for the absense of log files but it was an optical issue and thought the log files wouldn't show anything useful. Thanks again and I muchly appreciate your efforts with DXVK.
