### ISSUE TITLE
Need for Speed Heat missing ground texture

### ISSUE THREAD

**Issue by Linubuser** [doitsujin/dxvk#1764]
NFS HEAT missing ground texture with DXVK 1.7.1 as per attached pictures.

What I tried:

1. Proton 5.0-9 with DXVK 1.7.1 = missing texture
2. Windows 10 with DXV 1.7.1 = missing texture
3. Windows 10 with D3D11 = no problem,

I created the API trace with the 3 files provided with pierre-loup. Hopefully this will be useful. 
Thanks for the great work!!

### Software information
NFS Heat, any settings

### System information
- GPU: Nvidia GTX 970
- Driver: 450.66
- Wine version: Proton 5.0-9
- DXVK version: 1.7.1 

### Apitrace file(s)
[https://drive.google.com/file/d/1ru2Cq-xLxPre0ghI8ncR9EnNnKdelOaZ/view?usp=sharing](url)
[https://drive.google.com/file/d/1zm7GmifS9ByPy6UZXHTH8z1WySfe_0vb/view?usp=sharing](url)
[https://drive.google.com/file/d/1Y-CveCEb-VvLZr_e4rtXjDJIvOw8f6G8/view?usp=sharing](url)

### Log files
[https://drive.google.com/file/d/1J9z2Gy9ZONaLZbaGnbT5yIK6okvS8uoA/view?usp=sharing](url)
[https://drive.google.com/file/d/15ycs4RkzA6pWIfQWqBqSILrWsO_rNHlx/view?usp=sharing](url)
[https://drive.google.com/file/d/1VYXqqZEA33zipNqiKJwmpHflHsweeLVV/view?usp=sharing](url)

DXVK
<img width="960" alt="DXVK 1 7 1" src="https://user-images.githubusercontent.com/38225213/92981095-741b2900-f466-11ea-86b6-a7dfff2fb8a5.png">

D3D11
<img width="960" alt="DX11" src="https://user-images.githubusercontent.com/38225213/92981108-84cb9f00-f466-11ea-910e-f9d02da08b98.png">

**Comment by Joshua-Ashton** [comment]
I'm confused as to what these log files are because they certainly aren't ours.

I've never seen ``HackerSwapchain`` before but Google tells me it might be related to Nvidia 3D Vision or something called Helix Mod.

Please disable any mods/graphics API hooks you might be using.

**Comment by Linubuser** [comment]
Humm I don't have any mods installed. 

Maybe, I am doing something wrong all I did is start the game in steam with the command below and gathered all the log files from the "game.exe" directory.

DXVK_LOG_LEVEL=debug %command%

**Comment by Linubuser** [comment]
Here are the logs again. I created the logs with a new prefix and completely reinstalled game by using this launch option in steam.

DXVK_LOG_LEVEL=debug %command%

[https://drive.google.com/file/d/1xYpMW8vpbrYHonN9ki0omQiZdqCWxOMw/view?usp=sharing](url)
[https://drive.google.com/file/d/1Y3cIda83EQinPtvj87WixWlBkS6ZAUNW/view?usp=sharing](url)
[https://drive.google.com/file/d/1SJmDRRtFSmxChH50Ib49RONa1plKzpqL/view?usp=sharing](url)
[https://drive.google.com/file/d/1-SCNLIWmN5VDgLX5R88IYw9msTgkAzUn/view?usp=sharing](url)
[https://drive.google.com/file/d/1criQAn_0q3d9k4imyOA6cbFvV2kJRH0t/view?usp=sharing](url)
[https://drive.google.com/file/d/104ygCFQaXuoINLBlQJ66IVku0v_i-f7K/view?usp=sharing](url)
[https://drive.google.com/file/d/1qBWU_eKgiTtSnwyhsiddIpnHz8vkTru5/view?usp=sharing](url)
[https://drive.google.com/file/d/1Li92nAm1IR_Oe0gktWGC2-_ELy9vH_q1/view?usp=sharing](url)

**Comment by K0bin** [comment]
Can you make another apitrace with DXVK installed?

**Comment by Linubuser** [comment]
I can't confirm that 4801fbe fixes it as the build gives me a black screen with proton5.0-9 and crashes with windows 10.
Here is the DXVK trace in case it is still required:
[https://drive.google.com/file/d/15slxv98IR8pcTwcuTT4Q94njsiH4_i0g/view?usp=sharing](url)

**Comment by K0bin** [comment]
The black screen is fixed but we still don't know what causes the missing textures. It's difficult to debug this because both your traces don't really work and renderdoc doesn't work properly either.

**Comment by Linubuser** [comment]
Thx to have looked into it. I would not be surprise that this is a game bug that somehow doesn't show up with d3d11. The game had a lot of texture problem at launch on PC. I will keep the issue opened and close it if it miraculously gets fixed in a future patch.

**Comment by NikoBellicRU** [comment]
Same problem here.
Apitrace

[https://mega.nz/file/JUxwxayK#2hOwgoMog0hnwFYEugyMjTZb-T13sJ1_7rqPUW9Obmw](url)

**Comment by BlazeKl** [comment]
This issue is also present when using DXVK on Windows, the ground textures are just in very low res, it also affects some buildings

**Comment by doitsujin** [comment]
I can reproduce the problem with one of the provided traces, but it seems to be an extremely complicated problem that would require debugging the game on the Windows side to see what DXVK is doing wrong. Unfortunately, this does not seem to be possible as the game itself actively prevents debugging, and the trace crashes during replay on native D3D11.

**Comment by BiZkViT96** [comment]
@doitsujin Sorry for necroposting, but for some reason, the fix doesn't work for Intel Arc GPUs. I [found this](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/1198) out when I tried to fix the same Intel driver issue on Windows using DXVK. Just to find that DXVK itself had the same bug, it's a pretty stupid situation. Also, you can see people on [ProtonDB](https://www.protondb.com/app/1222680) with Intel Arc still mention this bug. Is there any setting I can change in the dxvk.conf file to make it work for Arc?

**Comment by Blisto91** [comment]
Could try `dxgi.hideIntelGpu = True`

**Comment by BiZkViT96** [comment]
Nope. dxgi.log confirm that hideIntelGpu is enabled.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/0e4e8921-d514-45ac-a1f9-ec8bb48d4326" />

[NeedForSpeedHeat_d3d11.log](https://github.com/user-attachments/files/27863228/NeedForSpeedHeat_d3d11.log)
[NeedForSpeedHeat_dxgi.log](https://github.com/user-attachments/files/27863229/NeedForSpeedHeat_dxgi.log)

I also tried dxvk-1.9.2, which was the first version that had the fix, just to eliminate any possible regression.

**Comment by Blisto91** [comment]
Try giving current master a spin https://github.com/doitsujin/dxvk/actions/runs/25849618334

Edit: Download link is at the bottom past all the warnings

**Comment by BiZkViT96** [comment]
Tried suggested build with dxgi.hideIntelGpu = True and without, no difference.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/ccd4762f-69b8-4bc7-babc-dd7f30dfc6e7" />

**Comment by Blisto91** [comment]
I'll give it a poke next time i switch to Intel

**Comment by BiZkViT96** [comment]
That would be great. I really appreciate it.

**Comment by BiZkViT96** [comment]
@Blisto91 Just wanted to tell you that the game has some CPU issues and it's not DXVK or Intel Arc related. Video cutscenes will stutter and the CPU load will be very high, but there are workarounds. PCGW has a [page](https://www.pcgamingwiki.com/wiki/Need_for_Speed_Heat#Pre-rendered_cutscenes_stutter) about these issues.

**Comment by Blisto91** [comment]
@BiZkViT96 confirmed the issue. Just gonna quote @doitsujin here.

> oh this was the game that used the textureQueryLod thing
> ...
> i won't say no to one [a apitrace], but chances are that this is just a hw bug
> unfortunately neither vulkan nor d3d specs say anything about how this is supposed to behave with aniso
> ...
> either way, ye, shader in question uses `textureQueryLod` on aniso sampler and works fine on amd
> no real workaround possible on our end, should probably be looked at from the mesa side

So I think it would be better to try your luck at reporting it at Intels own (Windows) tracker https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT.
I'll look in to reporting it for their Linux driver.

You can link this apitrace as an easy way to reproduce when replayed with dxvk https://drive.proton.me/urls/PHHFH84RHC#txnUywyzY8Bx

A non ideal workaround you could use is to make a file called `dxvk.conf` next to the games exe and insert `d3d11.samplerAnisotropy = 0`. This will disable Anisotropic Filtering which is worse quality than if it worked properly, but better than being fully broken.
