### ISSUE TITLE
VK_ERROR_DEVICE_LOST with Wow and Thief 2014

### ISSUE THREAD

**Issue by arabcian** [doitsujin/dxvk#1766]
In some games randomly getting vk_error_evice_lost error game freezes i can only kill it.

Thief 2014 - Max Settings other than SSAA

### System information
- GPU: 1050Ti Mobile
- Driver:450.66
- Wine version: Staging 5.7
- DXVK version: 1.7.1

d3d11.log
https://paste.ee/p/j22pY
dxgi.log
https://paste.ee/p/wKJOe

**Comment by doitsujin** [comment]
Thief works fine on my end, please try a different driver version.

**Comment by Thaodan** [comment]
I had a similar issue when tabbing out of a game where I the resolution is different from the one on my default resolution. Maybe thats how he triggered that?

**Comment by Iglu47** [comment]
@Thaodan is there any chance there is some other app running at the same time that uses Vulkan like MangoHud 0.5.1?
also give the output of `dmesg | grep Xid` after the game has frozen, but in the same session
(something like NVRM Xid 31 expected)

**Comment by Thaodan** [comment]
The Xid message is this one I get whenever this error ocurs:
Sep 13 23:52:49 odin kernel: NVRM: Xid (PCI:0000:01:00): 32, pid=315883, Channel ID 000000ab intr 00040000

There's no vulkan app running, just opengl apps like kwin.

**Comment by arabcian** [comment]
Hello again sorry im late. That VK_ERROR_DEVICE_LOST somehow gone by itself. Im not having that anymore, i guess i did built my kernel with -O3 before it started happening. But now i have another problem while playing games with wine sometimes game just hangs, im having to kill it, i havent faced an erro yet but ill keep an eye on it. Im not sure if this is related to DXVK.

**Comment by arabcian** [comment]
I'm trying to spot the reason. I moved to 5.9rc6 kernel and updated to nvidia-drivers-455.23.04 from 450.66

**Comment by K0bin** [comment]
Try the latest master version of DXVK. It contains a workaround for a problem in the latest Nvidia graphics driver.

**Comment by arabcian** [comment]
> Try the latest master version of DXVK. It contains a workaround for a problem in the latest Nvidia graphics driver.

You mean the latest state of the git version?

**Comment by arabcian** [comment]
Today i faced another vk_error_device_lost error with nvidia-drivers-455.23.04 and 5.8 Kernel. I wonder if that's caused by my kernel config.

**Comment by arabcian** [comment]
I remember one of the later drivers added an update to Vulkan to 1.2 after a long time at 1.1 I think 1.2 is still not stable enough.

Vulkan documentation says this:

A logical device may become lost for a number of implementation-specific reasons, indicating that pending and future command execution may fail and cause resources and backing memory to become undefined.

Typical reasons for device loss will include things like execution timing out (to prevent denial of service), power management events, platform resource management, implementation errors.

Applications not adhering to valid usage may also result in device loss being reported, however this is not guaranteed. Even if device loss is reported, the system may be in an unrecoverable state, and further usage of the API is still considered invalid.

When this happens, certain commands will return VK_ERROR_DEVICE_LOST. After any such event, the logical device is considered lost. It is not possible to reset the logical device to a non-lost state, however the lost state is specific to a logical device (VkDevice), and the corresponding physical device (VkPhysicalDevice) may be otherwise unaffected.

In some cases, the physical device may also be lost, and attempting to create a new logical device will fail, returning VK_ERROR_DEVICE_LOST. This is usually indicative of a problem with the underlying implementation, or its connection to the host. If the physical device has not been lost, and a new logical device is successfully created from that physical device, it must be in the non-lost state.

Whilst logical device loss may be recoverable, in the case of physical device loss, it is unlikely that an application will be able to recover unless additional, unaffected physical devices exist on the system. The error is largely informational and intended only to inform the user that a platform issue has occurred, and should be investigated further. For example, underlying hardware may have developed a fault or become physically disconnected from the rest of the system. In many cases, physical device loss may cause other more serious issues such as the operating system crashing; in which case it may not be reported via the Vulkan API.

When a device is lost, its child objects are not implicitly destroyed and their handles are still valid. Those objects must still be destroyed before their parents or the device can be destroyed (see the Object Lifetime section). The host address space corresponding to device memory mapped using vkMapMemory is still valid, and host memory accesses to these mapped regions are still valid, but the contents are undefined. It is still legal to call any API command on the device and child objects.

Once a device is lost, command execution may fail, and commands that return a VkResult may return VK_ERROR_DEVICE_LOST. Commands that do not allow runtime errors must still operate correctly for valid usage and, if applicable, return valid data.

Commands that wait indefinitely for device execution (namely vkDeviceWaitIdle, vkQueueWaitIdle, vkWaitForFences or vkAcquireNextImageKHR with a maximum timeout, and vkGetQueryPoolResults with the VK_QUERY_RESULT_WAIT_BIT bit set in flags) must return in finite time even in the case of a lost device, and return either VK_SUCCESS or VK_ERROR_DEVICE_LOST. For any command that may return VK_ERROR_DEVICE_LOST, for the purpose of determining whether a command buffer is in the pending state, or whether resources are considered in-use by the device, a return value of VK_ERROR_DEVICE_LOST is equivalent to VK_SUCCESS.

The content of any external memory objects that have been exported from or imported to a lost device become undefined. Objects on other logical devices or in other APIs which are associated with the same underlying memory resource as the external memory objects on the lost device are unaffected other than their content becoming undefined. The layout of subresources of images on other logical devices that are bound to VkDeviceMemory objects associated with the same underlying memory resources as external memory objects on the lost device becomes VK_IMAGE_LAYOUT_UNDEFINED.

The state of VkSemaphore objects on other logical devices created by importing a semaphore payload with temporary permanence which was exported from the lost device is undefined. The state of VkSemaphore objects on other logical devices that permanently share a semaphore payload with a VkSemaphore object on the lost device is undefined, and remains undefined following any subsequent signal operations. Implementations must ensure pending and subsequently submitted wait operations on such semaphores behave as defined in Semaphore State Requirements For Wait Operations for external semaphores not in a valid state for a wait operation.

**Comment by Joshua-Ashton** [comment]
You don't need to post the whole Vulkan spec on device loss, we know what it means.

**Comment by doitsujin** [comment]
That, and it's completely useless without knowing what exactly is causing the crash anyway. Especially since it's working on other setups.

**Comment by arabcian** [comment]
> That, and it's completely useless without knowing what exactly is causing the crash anyway. Especially since it's working on other setups.

Ok ive added option "NoFlip" "True" in nvidia device section of my xorg.conf file. After a few hours of gaming the problem hasnt reoccured yet.

**Comment by WinterSnowfall** [comment]
I did, at one point in the past, run across a similar problem and it was while using PRIME render offload on an external GPU, but I haven't seen any such behaviour on my current desktop rig. Perhaps these type of multi-GPU setups have something to do with it?

**Comment by arabcian** [comment]
> I did, at one point in the past, run across a similar problem and it was while using PRIME render offload on an external GPU (on a laptop with Intel HD graphics), but I haven't seen any such behaviour on my current desktop rig. Perhaps these type of multi-GPU setups have something to do with it?

Yea, maybe because im on prime offloading too. And setting OpenGL Flipping of solved my problem. For the last 2 days there no freezes anymore. Maybe you should mark it as a workaround.

Setting Option "noflip" "true" in xorg.conf, works around the problem.

**Comment by arabcian** [comment]
After 1 week today got 2 hangs in thief after playing a while. One got recovered after a like 10 second freeze. Second one couldnt recover and needed a kill. So im not sure about noflip it maybe eased a bit but still happens randomly. My next stop will be destroying my wine prefix and creating a new one.

**Comment by arabcian** [comment]
Ok ive reinstalled my OS, Destroyed my prefix, Tried different kernel versions none of them change anything. Now i downgraded my Nvidia-Drivers package to 440.100-r2. Which uses an older Vulkan version. Performance drop is noticable, starting to test it tomorrow.

**Comment by arabcian** [comment]
Installed latest nvdia-drivers package yesterday which is 455.45.01. 1 day past still havent got any vk_error_device_lost errors yet, i hope it goes like that.

**Comment by arabcian** [comment]
Sad news that thing still happening with 455.45.01 may people with the same problem leave some hardware info here? So we can guess what may be causing the hang.

**Comment by arabcian** [comment]
Everything i tried failed, im still having that bug with 460.32.03 driver. Could it be related to dxvk?

**Comment by Evolve-Git** [comment]
> Sad news that thing still happening with 455.45.01 may people with the same problem leave some hardware info here? So we can guess what may be causing the hang.

Hey i'm having the same issue with graphically "intensive" games (newer than 2015-ish). Pretty much tried everything you mentioned myself and didn't find anything helpful on the internet so i'm just living with it. Sometimes i can play a whole day without any issues while other times it's hanging constantly. My setup is Ryzen 1600x with a GTX680.

**Comment by sfjuocekr** [comment]
I'm getting the device lost with 1.9.1, but 1.8.1 and 1.9 seem to work fine for me.

It is also a very specific crash and happens usually only at Karazhan on Wednesday. We are there with like a 100 people at the stone and the warlocks are farming shards on horde players trying to run in while we summon even more people. Strangely enough going into AV or any other graphically intensive areas does not seem to crash 1.9.1.

Usually I can stand around and heal my friends for a while, but then a random amount of time later the screen freezes and WoW closes. Upon logging in it only takes a few seconds to crash again.

I'm using the latest Vulkan beta: 470.56.05

**Comment by Blisto91** [comment]
@arabcian @sfjuocekr Friendly ping. Please try with latest dxvk and driver. 515 drivers especially

**Comment by sfjuocekr** [comment]
Oh, I didn't have this issue anymore since 1.10 or 495. I'm currently on 515.49.10 and have been using VKD3D for WoW.

**Comment by Blisto91** [comment]
If any of you still have still have this issue just comment here again.
