### ISSUE TITLE
[d3d9] Silverfall crashes on startup

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#1770]
Silverfall crashes on startup with a "Failed to create surface" error. WineD3D works just fine.

### Software information
Silverfall (GOG version).

### System information
- GPU: GeForce GTX 1080
- Driver: 440.100.0
- Wine version: 5.9 Staging
- DXVK version: v1.7.1-7-g41a49a9

### Apitrace file(s)
[silverfall.trace.tar.xz](https://drive.google.com/file/d/1ml2DYvlhSTM1Po3bIlvAAy66ygIqBC1K/view?usp=sharing)

### Log files
- d3d9.log: [silverfall_d3d9.log](https://github.com/doitsujin/dxvk/files/5246018/silverfall_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by Joshua-Ashton** [comment]
Do the Wine logs mention child window rendering?

This looks like it could be that.

**Comment by WinterSnowfall** [comment]
> Do the Wine logs mention child window rendering?

Yeah, it is that. Sorry, I had wine logging disabled. 

So there's no chance of it working with DXVK any time soon then, I take it?

**Comment by Joshua-Ashton** [comment]
It's a Wine bug.
