### ISSUE TITLE
[d3d9] Trails in the Sky SC → Fog has no effect on some objects

### ISSUE THREAD

**Issue by NerosTie** [doitsujin/dxvk#1771]
DXVK:
![Screenshot_20200919_212701](https://user-images.githubusercontent.com/4572452/93688917-fe4c3880-fac9-11ea-80a7-8e5de795772a.png)
![Screenshot_20200919_213236](https://user-images.githubusercontent.com/4572452/93688919-00ae9280-faca-11ea-8c52-3eca57e6cf2d.png)

WineD3D:
![Screenshot_20200919_213120](https://user-images.githubusercontent.com/4572452/93688911-f55b6700-fac9-11ea-85db-dce5c44fb3d4.png)
![Screenshot_20200919_212935](https://user-images.githubusercontent.com/4572452/93688912-f8565780-fac9-11ea-879e-6ecffc73f46c.png)

### System information
- GPU: Nvidia GTX 730M
- Driver: Nvidia Beta 455.23.04
- Wine version: Proton 5.0-9
- DXVK version: 1347

### Apitrace file(s)
https://mega.nz/file/3yQGiSbT#YvwQQY-V5VMOYLNo3oNtbrrlbDit7VpQZNUq020qtNU

### Log files
[steam-251290-dxvk.log](https://github.com/doitsujin/dxvk/files/5250584/steam-251290-dxvk.log)
[steam-251290-wined3d.log](https://github.com/doitsujin/dxvk/files/5250585/steam-251290-wined3d.log)

**Comment by Joshua-Ashton** [comment]
Fixed, thanks for the great report! 😄
