### ISSUE TITLE
The Witcher 3 crashes when using nvidia 450.66

### ISSUE THREAD

**Issue by tuxrinku** [doitsujin/dxvk#1772]
I tried installing the latest nvidia driver 450.66, but it randomly crashes when I play The Witcher 3 while the previous driver 440.100 works perfectly, but the 450 driver has a way better performance. It also feezes the game sometimes when I adjust sound/brightness and gnome OSD shows up.
In the changelog of the 450.66 driver, there's this thing `Fixed triple buffering support of Vulkan X11 swapchains when applications are syncing to vblank`. Could it be the cause of the issue since I had no problems on previous versions?

Sadly there's nothing shown in dxvk, wine or system logs when it freezes/crashes.

### Software information
The Witcher 3, ultra settings, 1920x1080 on Ubuntu 20.04.

### System information
- GPU: Nvidia RTX 2070 Super
- Driver: 450.66
- Wine version: 5.7
- DXVK version: 1.7.1L

**Comment by WinterSnowfall** [comment]
>     * DXVK version: 1.7.1L

Does this mean you're using the latest dev build? I've had similar issues with The Witcher 3 ever since switching to the 450 Nvidia driver branch (including on 450.57), but I haven't seen crashes since 16a51f3 . Then again I haven't played all that much lately. Going back to 440.100 also makes it rock solid again (no crashes) regardless of the DXVK version you use, as you've also noted.

**Comment by tuxrinku** [comment]
I tried to compile `master`, but I get the following error : 
`Compiling C++ object 'src/util/ed6d25d@@util@sta/log_log_debug.cpp.obj'.
FAILED: src/util/ed6d25d@@util@sta/log_log_debug.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/util/ed6d25d@@util@sta -Isrc/util -I../src/util -I.././include -fdiagnostics-color=always -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O3 -DNOMINMAX -MD -MQ 'src/util/ed6d25d@@util@sta/log_log_debug.cpp.obj' -MF 'src/util/ed6d25d@@util@sta/log_log_debug.cpp.obj.d' -o 'src/util/ed6d25d@@util@sta/log_log_debug.cpp.obj' -c ../src/util/log/log_debug.cpp
In file included from ../src/util/log/log_debug.h:5,
                 from ../src/util/log/log_debug.cpp:1:
../src/util/log/log.h:50:10: error: ‘mutex’ in namespace ‘std’ does not name a type`

The driver 440.100 worked perfectly yea, but there's a performance bump by ~15 fps with 450.66, so I'd like to use this one.
The 1.7.1L is how lutris named it, but I also tried with `743f309` and it still crashes.

**Comment by K0bin** [comment]
> error: ‘mutex’ in namespace ‘std’ does not name a type

https://github.com/doitsujin/dxvk#troubleshooting

**Comment by WinterSnowfall** [comment]
> but I also tried with `743f309` and it still crashes.

743f309 precedes 16a51f3, so I'm not too surprised you still get crashes. You also don't **have** to compile master yourself, since you can usually find relatively new builds [here](https://git.froggi.es/doitsujin/dxvk/-/jobs).

**Comment by tuxrinku** [comment]
I managed to compile master, and it seems stable. I played for like 15 minutes but there wasn't a single crash. I'll try more longer sessions to test it but so far it seems that it's fixed.

**Comment by mozo78** [comment]
Should 41a49a9c do the job?

**Comment by WinterSnowfall** [comment]
> Should [41a49a9](https://github.com/doitsujin/dxvk/commit/41a49a9c1436bfb0a0c9441a3343f14c9317bbd3) do the job?

Yes, pretty much anything that comes after 16a51f3 should be fine, including 41a49a9.

**Comment by mozo78** [comment]
Thank you very much :)
