### ISSUE TITLE
Freedom Fighters low and not stable FPS

### ISSUE THREAD

**Issue by legionpheonix** [doitsujin/dxvk#1774]
The game produces low FPS in places, especially in those places where the effect of explosions and dust occurs.
I am using the game together with dgvoodoo2 + dxvk (anti-aliasing, anisotropic filtering)

### System information
- GPU: Nvidia GTX 1070
- Driver: 452.06
- Wine version: i use Windows 10 (2004)
- DXVK version: 1.7.1

### Apitrace file(s)
https://mega.nz/file/ERYiTCbb#xQQdYBS2vd0UxaYRH_D_gaXCRwOU-d1Ds3KR7eGPGbc

### Log files
[Freedom.Exe_d3d11.log](https://github.com/doitsujin/dxvk/files/5265547/Freedom.Exe_d3d11.log)
[Freedom.Exe_dxgi.log](https://github.com/doitsujin/dxvk/files/5265548/Freedom.Exe_dxgi.log)

**Comment by K0bin** [comment]
Why are you using DgVoodoo with DXVK on Windows? DXVK is almost certainly gonna be slower than the Nvidia d3d11 driver, especially with dgvoodoo involved.

**Comment by legionpheonix** [comment]
> Почему вы используете DgVoodoo с DXVK в Windows? DXVK почти наверняка будет медленнее, чем драйвер Nvidia d3d11, особенно с dgvoodoo.

To be able to use the Nvidia driver settings, for example, it is convenient to use sharpness when anti-aliasing.

**Comment by doitsujin** [comment]
> I am using the game together with dgvoodoo2

Not really our problem then. dgvoodoo2 is known not to perform very well.
