### ISSUE TITLE
DXVK and D3D9Ex

### ISSUE THREAD

**Issue by Infest-SBT** [doitsujin/dxvk#1775]
If I'm guessing correctly, DXVK doesn't currently have support for D3D9Ex. Some games may require d3d9ex for better minimize. Will this feature be added in the future?

**Comment by Joshua-Ashton** [comment]
D3D9Ex is supported aside from some things nothing uses (ComposeRects and resource residency.)

**Comment by Infest-SBT** [comment]
At the moment we are talking about Fallout New Vegas and dll-extension NVTF. DXVK breaks the D3D9Ex enable setting.

**Comment by Joshua-Ashton** [comment]
How does it break? Please provide logs/apitrace etc like the template asks for.

**Comment by Infest-SBT** [comment]
The game freezes when I minimize the game. Everything works on the original d3d9.

**System information**
GPU: Nvidia GTX 1066
Driver: 441.66
Wine version: Windows 10 (2004)
DXVK version: 1.7.1

**Log files**
[FalloutNV_d3d9.log](https://github.com/doitsujin/dxvk/files/5267130/FalloutNV_d3d9.log)

**Comment by K0bin** [comment]
We need an apitrace to debug this. The log files alone dont tell us much.

**Comment by Infest-SBT** [comment]
How do I create apitrace-file?

**Comment by K0bin** [comment]
Follow this guide: https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace but use the download like on this page instead: https://apitrace.github.io/

**Comment by Infest-SBT** [comment]
Sorry, I was wrong. This problem does not apply to DXVK. I close this issue.
