### ISSUE TITLE
Crysis.exe 32bit crashes after loading level in dx10 mode

### ISSUE THREAD

**Issue by AlexanderWKoenig** [doitsujin/dxvk#1777]
Hello,

the GOG Version of Crysis is crashing for me after a level loaded. 
Since I am running an AMD CPU, i had to use this fix to get crysis 32bit running but just in dx9 mode:
https://www.pcgamingwiki.com/wiki/Crysis#Game_crashes_on_machines_with_AMD_CPUs

The 64bit version of this game does crash on start for me, with or without the fixed dll mentionen in pcgamingwiki.

I've also followed the instructions from this issue: https://github.com/doitsujin/dxvk/issues/783

So i've created a clean wineprefix, installed dxvk and used `winetricks d3dx10_43 d3dcompiler_43`

### System information
- GPU: RX 480
- Driver: MESA 20.3.0 RADV
- Wine version: Wine TkG 5.17
- DXVK version: 1.7.1

### Log files
[Crysis_d3d9.log](https://github.com/doitsujin/dxvk/files/5271867/Crysis_d3d9.log)
[Crysis_d3d11.log](https://github.com/doitsujin/dxvk/files/5271868/Crysis_d3d11.log)
[Crysis_dxgi.log](https://github.com/doitsujin/dxvk/files/5271869/Crysis_dxgi.log)
[Game.log](https://github.com/doitsujin/dxvk/files/5271870/Game.log)

Terminal output:
0024:fixme:d3dcompiler:d3d10_shader_reflection_GetDesc iface 2F59699C, desc 0031DB9C partial stub!
0024:fixme:d3dcompiler:skip_dword_unknown Skipping 4 unknown DWORDs:
0024:fixme:d3dcompiler:skip_dword_unknown 	0x85ca1431
0024:fixme:d3dcompiler:skip_dword_unknown 	0x9145a899
0024:fixme:d3dcompiler:skip_dword_unknown 	0x5646c808
0024:fixme:d3dcompiler:skip_dword_unknown 	0x1ab12d53
0024:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
0024:fixme:d3dcompiler:skip_dword_unknown 	0x00000001
0024:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
0024:fixme:d3dcompiler:skip_dword_unknown 	0x00000008
0024:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
0024:fixme:d3dcompiler:skip_dword_unknown 	0x00000008
0024:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
0024:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
0024:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
0024:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
0024:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
0024:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
0024:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
0024:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
0024:fixme:d3dcompiler:skip_dword_unknown Skipping 2 unknown DWORDs:
0024:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
0024:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
0024:fixme:d3dcompiler:d3d10_shader_reflection_GetDesc iface 2F59699C, desc 0031D830 partial stub!
0024:fixme:faultrep:ReportFault 0031DC68 0x0 stub

**Comment by unic0rn** [comment]
having the same problem on A8-7600. i've even added all the d3dcompiler* dlls found in system32 in winecfg and set them to disabled except _42, _43 and _47 installed using winetricks (game supposedly requires _43, but dxvk requires _47, with _47 disabled it falls back to dx9), and it still throws that built-in d3dcompiler error. how, i have no idea.

**Comment by unic0rn** [comment]
it honestly makes no sense. i've checked it with winedebug to see all dll/loaddll traces, both d3dcompiler_43 and d3dcompiler_47 are installed using winetricks and set to native, and those are the only d3dcompiler dlls that are being loaded at all. d3d10 is built-in as it should be i guess, it loads native _47, then _43 gets loaded. yet either when launching the 32bit version, or when loading save in the 64bit version with graphics set to very high, the game crashes with all the d3dcompiler fixme messages, suggesting it's using built-in d3dcompiler. how, when it's not loading it at all?

as mentioned, 64bit with high settings works (not sure for how long, but i've walked around for few minutes and it was fine). on very high it actually loads, you can make a few steps if you're lucky, then it crashes. 32bit crashes at the start. no idea what's going on.

**Comment by unic0rn** [comment]
here's the log from `WINEPREFIX=/home/uni/games/crysis WINEESYNC=1 DXVK_HUD=fps,api,version,devinfo,drawcalls,memory,gpuload WINEDEBUG=+loaddll,+dll,+d3dcompiler,+d3d10 wine Crysis.exe >test.log 2>&1`. 64bit version, c1-launcher (opensource, makes no difference except 32bit works just like 64bit instead of crashing right away), very high settings. the game launches, loading a save ends up in a crash more or less one-two seconds into the gameplay. as mentioned, d3dcompiler_* dlls were installed using winetricks. up to date manjaro kde, wine-staging, all versions in the log.

[test.log](https://github.com/doitsujin/dxvk/files/5273683/test.log)

**Comment by unic0rn** [comment]
fixed. in the most counterintuitive way possible.

set d3dx10_34.dll to built-in, problem solved. those shader reflection partial stub fixmes are not the problem, those still appear, but the game works, both 32bit and 64bit (using c1-launcher if it makes a difference), with everything set to very high. i still have d3dcompiler_34.dll set to disabled if that matters, didn't bother to check without that.

**Comment by AlexanderWKoenig** [comment]
> fixed. in the most counterintuitive way possible.

Hi unic0rn, thanks for looking into this, but i have no success following your instructions.
Here is what i did:
Create a clean wineprefix, execute setup_dxvk.sh, execute `winetricks d3dx10_43 d3dcompiler_43 d3dcompiler_47 d3dcompiler_42`, set *d3dcompiler_34 to disabled and *d3dx10_34 to built-in. So I end up with the following overrides:
![Bildschirmfoto_2020-09-24_18-27-38](https://user-images.githubusercontent.com/40361614/94173191-d545f200-fe93-11ea-8c09-1311cfc8f89a.png)

But the 32bit and 64bit version keeps crashing when loading. With or without c1-launcher (I didnt know this, guess it has fixed 64bit for me)

Here is the Terminaloutput from the 32bit version:
0024:fixme:d3dcompiler:d3d10_shader_reflection_GetDesc iface 07299794, desc 0031DD9C partial stub!
0024:fixme:d3dcompiler:skip_dword_unknown Skipping 4 unknown DWORDs:
0024:fixme:d3dcompiler:skip_dword_unknown 	0x6a9cd7f0
0024:fixme:d3dcompiler:skip_dword_unknown 	0x52639a1b
0024:fixme:d3dcompiler:skip_dword_unknown 	0xf0a36782
0024:fixme:d3dcompiler:skip_dword_unknown 	0xdf7dbb4d
0024:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
0024:fixme:d3dcompiler:skip_dword_unknown 	0x00000001
0024:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
0024:fixme:d3dcompiler:skip_dword_unknown 	0x00000008
0024:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
0024:fixme:d3dcompiler:skip_dword_unknown 	0x00000008
0024:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
0024:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
0024:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
0024:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
0024:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
0024:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
0024:fixme:d3dcompiler:skip_dword_unknown Skipping 1 unknown DWORDs:
0024:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
0024:fixme:d3dcompiler:skip_dword_unknown Skipping 2 unknown DWORDs:
0024:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
0024:fixme:d3dcompiler:skip_dword_unknown 	0x00000000
0024:fixme:d3dcompiler:d3d10_shader_reflection_GetDesc iface 07299794, desc 0031DC80 partial stub!
wine: Unhandled page fault on read access to 00000004 at address 3804A200 (thread 0024), starting debugger...
Unhandled exception: page fault on read access to 0x00000004 in 32-bit code (0x3804a200).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:3804a200 ESP:0031e294 EBP:044be36c EFLAGS:00010246(  R- --  I  Z- -P- )
 EAX:0269c610 EBX:00000000 ECX:037212e8 EDX:00000000
 ESI:00000001 EDI:0376cfbc
Stack dump:
0x0031e294:  0441cb00 0376cf70 380454ac 0376cf70
0x0031e2a4:  03770330 0441cb00 00000000 044be36c
0x0031e2b4:  00000000 00000000 00000000 00000000
0x0031e2c4:  00000000 0031e2ec 0441cb00 00000000
0x0031e2d4:  0a9c0d1c 0eae93c0 00ab0500 00000000
0x0031e2e4:  384ae318 38087b8c 00000000 00000000
Backtrace:
=>0 0x3804a200 EntryPoint+0xffffffff() in cryrenderd3d10 (0x044be36c)
0x3804a200 EntryPoint+0xffffffff in cryrenderd3d10: movl	0x4(%edx),%edx
Modules:
Module	Address			Debug info	Name (77 modules)
PE	  320000-  342000	Deferred        msvfw32
PE	  400000-  417000	Deferred        crysis
PE	 2780000- 2b0b000	Deferred        d3dcompiler_47
PE	 2cc0000- 2cd2000	Deferred        compressati2
PE	 3230000- 32a4000	Deferred        d3dx10_43
PE	 4b90000- 4d97000	Deferred        d3dcompiler_43
PE	 5ca0000- 5cd3000	Deferred        fmod_event
PE	 7620000- 77c2000	Deferred        fmodex
PE	 77d0000- 780a000	Deferred        fmod_event_net
PE	 7f90000- 7fe2000	Deferred        goggame-1809223221
PE	10000000-1001d000	Deferred        intellaptopgaming
PE	30000000-301fa000	Deferred        cry3dengine
PE	30500000-30813000	Deferred        cryaction
PE	31000000-31204000	Deferred        cryaisystem
PE	31500000-31699000	Deferred        cryanimation
PE	32000000-320e1000	Deferred        cryentitysystem
PE	32500000-3256c000	Deferred        cryfont
PE	33500000-3353d000	Deferred        cryinput
PE	34000000-34069000	Deferred        crymovie
PE	35000000-35421000	Deferred        cryphysics
PE	35500000-355ad000	Deferred        cryscriptsystem
PE	36000000-360b9000	Deferred        crysoundsystem
PE	36500000-36727000	Deferred        crysystem
PE	38000000-388ec000	Export          cryrenderd3d10
PE	39000000-392ef000	Deferred        crygame
PE	39500000-39613000	Deferred        crynetwork
PE	60000000-6005d000	Deferred        ijl15
PE	61b00000-61b28000	Deferred        sechost
PE	62340000-62371000	Deferred        uxtheme
PE	62800000-6283a000	Deferred        usp10
PE	639c0000-63a81000	Deferred        winmm
PE	64b40000-64b59000	Deferred        shcore
PE	64d80000-64d94000	Deferred        hid
PE	64f40000-64f4e000	Deferred        vulkan-1
PE	65200000-65328000	Deferred        ole32
PE	65800000-65814000	Deferred        xinput1_3
PE	65980000-6598c000	Deferred        version
PE	66340000-6634d000	Deferred        d3dx10_34
PE	66400000-66473000	Deferred        dbghelp
PE	66640000-66666000	Deferred        msacm32
PE	66a00000-66a0c000	Deferred        mswsock
PE	67800000-67856000	Deferred        combase
PE	68ac0000-68acc000	Deferred        powrprof
PE	68c40000-68c99000	Deferred        shlwapi
PE	69180000-69191000	Deferred        pdh
PE	6a300000-6a426000	Deferred        oleaut32
PE	6a540000-6a84e000	Deferred        d3d11
PE	6a900000-6a97f000	Deferred        setupapi
PE	6aec0000-6aeca000	Deferred        psapi
PE	6b4c0000-6b54f000	Deferred        wininet
PE	6c0c0000-6c0da000	Deferred        imm32
PE	6c2c0000-6c2d0000	Deferred        wsock32
PE	6c7c0000-6c8cc000	Deferred        d3d10core
PE	6c9c0000-6ca03000	Deferred        d3d10
PE	6d5c0000-6d61d000	Deferred        dsound
PE	6dbc0000-6dbdf000	Deferred        mpr
PE	6e680000-6e6d1000	Deferred        avifil32
PE	6e8c0000-6ea20000	Deferred        comctl32
PE	6f400000-6f610000	Deferred        dxgi
PE	6fdc0000-6fe4f000	Deferred        rpcrt4
PE	70340000-70365000	Deferred        mmdevapi
PE	7b000000-7b0e0000	Deferred        kernelbase
PE	7b620000-7b7dc000	Deferred        kernel32
PE	7bc30000-7bc34000	Deferred        ntdll
PE	7e410000-7e414000	Deferred        msvcr80
PE	7e4f0000-7e4f7000	Deferred        gdi32
PE	7e6a0000-7e6a4000	Deferred        ucrtbase
PE	7e790000-7e794000	Deferred        advapi32
PE	7e820000-7e908000	Deferred        user32
PE	ee0e0000-ee0e3000	Deferred        winepulse
PE	ee640000-ee64b000	Deferred        dinput8
PE	f6d00000-f6d04000	Deferred        msvcrt
PE	f6dd0000-f6dd4000	Deferred        winevulkan
PE	f7010000-f7014000	Deferred        iphlpapi
PE	f7060000-f7064000	Deferred        winex11
PE	f7110000-f7114000	Deferred        ws2_32
PE	f7170000-f7a47000	Deferred        shell32
Threads:
process  tid      prio (all id:s are in hex)
00000020 (D) Z:\mnt\home\Games\Crysis\Crysis\Bin32\Crysis.exe
	00000024    0 <==
	000000e8    0
	00000124    0
	00000128    0
	0000012c    0
	00000168   -2
	0000016c   -2
	00000170   -2
	00000174   -2
	00000178   -2
	0000017c   -2
	00000180   -2
	00000184   -2
	00000188   -2
	0000018c   -2
	00000190    0
	00000194    0
	00000198    0
	0000019c    0
	000001a0    0
	000001a4    0
	000001a8    0
	000001ac   15
	000001b0    0
	000001b4   15
	000001b8   15
	000001bc    2
	000001c0   15
	000001c4    0
	000001c8    0
	000001cc    2
	000001f0    1
	000001f4    0
	00000208    1
	00000214    0
00000038 services.exe
	0000003c    0
	00000040    0
	0000004c    0
	0000005c    0
	00000070    0
	00000088    0
	00000094    0
	000000c8    0
00000044 winedevice.exe
	00000048    0
	00000054    0
	00000058    0
	000000b0    0
00000060 plugplay.exe
	00000064    0
	00000074    0
	00000078    0
	0000007c    0
	0000009c    0
00000068 explorer.exe
	0000006c    0
	000000b4    0
	000000b8    0
00000080 winedevice.exe
	00000084    0
	0000008c    0
	00000090    0
	00000098    0
	000000a4    0
	000000a8    0
	000000ac    0
000000c0 rpcss.exe
	000000c4    0
	000000d0    0
	000000d4    0
	000000d8    0
	000000dc    0
	000000e0    0
System information:
    Wine build: wine-5.17-98-g36e6ea9767 ( TkG Plain Esync Vkd3d )
    Platform: i386 (WOW64)
    Version: Windows 10
    Host system: Linux
    Host version: 5.8.10-17-tkg-bmq

**Comment by unic0rn** [comment]
try `winetricks d3dx9 d3dx10 vcrun2005`, then check the overrides (d3dx10_34 and so on). also, no need to set windows version to 10, got it at 7 (default). my prefix is honestly a mess, i was testing everything including gallium nine, but this should give you identical config afaik. to be clear, the above will install whole bunch of dlls, only d3dx10_34 should be set to built-in as far as d3dx* goes.

if all else fails, try disabling mango perhaps? DXVK_HUD is enough for quick diagnostics. i don't think those logs can help in this case, maybe some heavy wine trace. in general i'm not sure if it's related to dxvk at all, assuming your case is identical as mine. something somewhere goes haywire, i figured since it's loading that dll and it's not a compiler - so doesn't have to be native - i'll check what happens when i'll set it to builtin (had d3dx9 and d3dx10 installed via winetricks already) - and amazingly, it worked. with d3dx10_34 set to builtin there's no point in installing only that dll via winetricks, it won't be used, but d3dx10 will install a lot more. wether any of those additional dlls are used, i don't know - i did loaddll tracing and posted the log above, but seeing how those crashes make little sense, i don't even trust those logs.

let me know how it goes, if it won't help i may try reinstalling the game in a fresh prefix later to check the exact steps to reproduce my setup.

**Comment by K0bin** [comment]
> Create a clean wineprefix, execute setup_dxvk.sh, execute winetricks d3dx10_43 d3dcompiler_43 d3dcompiler_47 d3dcompiler_42, set *d3dcompiler_34 to disabled and *d3dx10_34 to built-in. So I end up with the following overrides:

This makes absolutely no sense. First of all, `winetricks d3dx10_43` installs Microsofts d3dx10 implementation and sets it to native so Wine actually picks that up. Then you set it back to builtin to reverse that. So the winetricks install had no effect.

> set *d3dcompiler_34 to disabled

DXVK uses d3dcompiler_43 internally to implement D3D10 shader reflection. If Crysis uses D3D10 shader reflection, you need some implementation of that dll. Setting it to disabled is a terrible idea. Wine's implementation has been very problematic in  the past.

What you should do is use the Microsoft implementation of both `d3dx10` and `d3dcompiler_43`.

**Comment by unic0rn** [comment]
you're confusing _43 with _34.

**Comment by AlexanderWKoenig** [comment]
> try `winetricks d3dx9 d3dx10 vcrun2005`, then check the overrides (d3dx10_34 and so on)

Big thanks guys! Its way easier than expected:
All I did was a clean wineprefix, run setup_dxvk.sh and `winetricks vcrun2015`

So I guess this is not a dxvk issue.
