### ISSUE TITLE
[d3d9] [regression?] Serious Sam 2 → Some textures are black

### ISSUE THREAD

**Issue by NerosTie** [doitsujin/dxvk#1779]
DXVK:
![Screenshot_20200926_013002](https://user-images.githubusercontent.com/4572452/94324322-aade5c80-ff99-11ea-88ac-9d81da72a147.png)

WINED3D:
![Screenshot_20200926_012901](https://user-images.githubusercontent.com/4572452/94324327-b0d43d80-ff99-11ea-936f-52bbb90f0539.png)

It the same issue I reported last year https://github.com/Joshua-Ashton/d9vk/issues/317#issuecomment-529136753 and fixed with 
https://github.com/Joshua-Ashton/d9vk/commit/db9f2f3bf5fdecbf1fc3a66a358ba34425403acc But it looks like the issue is back...
### Software information
Settings are set to "high".

### System information
- GPU: Nvidia GT 730M
- Driver: 455.23.04
- Wine version: Proton 5.0-9
- DXVK version: 1347

### Apitrace file(s)
https://mega.nz/file/Pi4CiQqB#-G6BsBVV4z2PkD0WwpsBRK1coeaeKQAyqI48Wsf8Ydg

### Log files
[steam-204340-dxvk.log](https://github.com/doitsujin/dxvk/files/5285862/steam-204340-dxvk.log)
[steam-204340-wined3d.log](https://github.com/doitsujin/dxvk/files/5285863/steam-204340-wined3d.log)

**Comment by NerosTie** [comment]
Found from where it comes from:

DXVK 1276 → black textures
DXVK 1275 → no black textures

So the regression comes from this commit: https://git.froggi.es/doitsujin/dxvk/-/commit/f88f424da47ae9631c781165f3809e42fc7c476e

**Comment by Joshua-Ashton** [comment]
Thanks for bisecting this is very helpful! I am going to take a look now 😄

**Comment by Joshua-Ashton** [comment]
Your driver does not support
```
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 0
info:    customBorderColorWithoutFormat         : 0```

Unfortunately, I removed a hack that we had from before I made and used this extension.

I think it should be supported in the latest Vulkan beta driver, not sure why this hasn't made it to mainline yet given it's had support since May...

Maybe it's something to do with your card generation :l

**Comment by NerosTie** [comment]
`VK_EXT_custom_border_color`?

Er, I'm stupid 🤦

I already found the solution 1 month ago with Crysis: Proton 5.0-9 doesn't support `VK_EXT_custom_border_color`...

I should have tested with Proton-GE and Proton-tkg (actually, it works with both!) before opening an issue, sorry 😬
(Proton 5.0-9 is old, I'm innocent!)

I can close it, thanks :)
