### ISSUE TITLE
Issue building 32bit LTO'd dxvk with binutils 2.35.1

### ISSUE THREAD

**Issue by FireBurn** [doitsujin/dxvk#1782]
This is only on 32bit, and previously worked with 2.34

[build.log](https://github.com/doitsujin/dxvk/files/5296981/build.log)

This is more of an FYI, I've reported the issue with Gentoo here https://bugs.gentoo.org/745372 and I'll try and find how to report it upstream with the binutils folk

**Comment by FireBurn** [comment]
https://sourceware.org/bugzilla/show_bug.cgi?id=26675

**Comment by FireBurn** [comment]
I've also been maintaining a winelib build, this continues to build, it's only the mingw build that fails

**Comment by doitsujin** [comment]
Anything we can do to work around that? The linker error doesn't really make all that much sense to me since it involves the C++ standard library.

**Comment by FireBurn** [comment]
The work around if to not use LTO, or go back to an older version of ld.bfd, also reverting this commit https://github.com/bminor/binutils-gdb/commit/041d1c2d4f03a134cb7574e4d62d2ce4418503ff fixes it

**Comment by doitsujin** [comment]
We aren't using LTO by default though?

**Comment by FireBurn** [comment]
Then you're fine, I'll update the title

**Comment by TheGreatMcPain** [comment]
I can confirm that [this binutils commit](https://sourceware.org/git/?p=binutils-gdb.git;a=commitdiff;h=04e433a8571e727108b8f1b9a04ba5c7ab20112c#patch2) fixes this.

**Comment by doitsujin** [comment]
Thanks, do we know when the fix will make it into a release?

**Comment by TheGreatMcPain** [comment]
According to [https://sourceware.org/bugzilla/show_bug.cgi?id=26675#c19](https://sourceware.org/bugzilla/show_bug.cgi?id=26675#c19) it should already be in 2.36.

**Comment by GloriousEggroll** [comment]
Not sure who said they weren't using lto, but from the proton binutils script for `build-mingw-w64.sh`:

```
        pushd binutils/
            if [ ! -e Makefile ]; then
                ../../$BINUTILS_SRCDIR/configure \
                    --prefix=$DST_DIR/ \
                    --build=$BUILD_ARCH \
                    --host=$HOST_ARCH \
                    --target=$WIN32_TARGET_ARCH \
                    --enable-lto \
                    --enable-plugins \
                    --enable-deterministic-archives \
                    --disable-multilib \
                    --disable-nls \
                    --disable-werror \
                    $BINUTILS_EXTRA_CONFIGURE
            fi
            make $JOBS configure-host
            make $JOBS LDFLAGS=-all-static
            make $JOBS install
        popd
```

and from the gcc build options:
```
        pushd gcc/
            if [ ! -e Makefile ]; then
                #arguments mostly taken from Arch AUR mingw-w64-gcc PKGBUILD,
                #except "--disable-dw2-exceptions" swapped for "--disable-sjlj-exceptions --with-dwarf2"
                #for performance reasons on 32-bit
                LDFLAGS=-static PATH=$NEWPATH:$PATH ../../$GCC_SRCDIR/configure \
                    --prefix=$DST_DIR/ \
                    --build=$BUILD_ARCH \
                    --host=$HOST_ARCH \
                    --target=$WIN32_TARGET_ARCH \
                    --enable-static \
                    --enable-shared \
                    --enable-languages=c,lto,c++ \
                    --disable-multilib \
                    --enable-threads=posix \
                    --enable-fully-dynamic-string \
                    --enable-libstdcxx-time=yes \
                    --enable-libstdcxx-filesystem-ts=yes \
                    --enable-cloog-backend=isl \
                    --enable-libgomp \
                    --enable-lto \
                    --disable-sjlj-exceptions \
                    --with-dwarf2 \
                    $GCC_EXTRA_CONFIGURE
            fi
            PATH=$NEWPATH make $JOBS all-gcc
            PATH=$NEWPATH make $JOBS install-gcc
        popd
```

--enable-lto is set in the compile options for both

**Comment by Iglu47** [comment]
`GNU Binutils 2.36.1 release`
https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=f35674005e609660f5f45005a9e095541ca4c5fe https://ftp.gnu.org/gnu/binutils/binutils-2.36.1.tar.gz
