### ISSUE TITLE
Gujian 3 corrupted graphics on Nvdia

### ISSUE THREAD

**Issue by 3kinox** [doitsujin/dxvk#1784]
As can be seen in attached images, in some areas, graphics get corrupted on my Nvidia card, In particular on characters (main or NPC). This also happens near water, not sure if it is lighting related or something.
Also, it does not happen on my integrated intel card, only on Nvidia card. Does not happen on Geforce now either.
I attached log, and ran with vk validation layers already, did not see any particularly meaningul errors.

API trace makes the game freeze at launch so can't provide one seems. If I can add anything to help don't hesitate.

+ Images of the issue:
![20200927143649_1](https://user-images.githubusercontent.com/42655690/94782075-0316c380-03cb-11eb-9d25-119f1e219eb3.jpg)
![20200927141700_1](https://user-images.githubusercontent.com/42655690/94782081-0447f080-03cb-11eb-8d63-6414d05e50b2.jpg)
![20200927141655_1](https://user-images.githubusercontent.com/42655690/94782084-0447f080-03cb-11eb-968b-1c37d276bbef.jpg)

### Software information
Game: Gujian3
API: dx11
Settings: any (tried from lowest to highest)

### System information
- GPU: GTX 1070
- Driver: 450.66
- Wine version: proton 5.09 
- DXVK version: 1.7.8

### Apitrace file(s)
Freeze game at launch

### Log files
- d3d9.log: empty
- d3d11.log: [Gujian3_d3d11.log](https://github.com/doitsujin/dxvk/files/5310292/Gujian3_d3d11.log)
- dxgi.log: empty
[Gujian3_dxvk_config.log](https://github.com/doitsujin/dxvk/files/5310291/Gujian3_dxvk_config.log)

**Comment by doitsujin** [comment]
Does this work with wined3d?

**Comment by 3kinox** [comment]
![20201003184026_1](https://user-images.githubusercontent.com/42655690/94996946-1763e780-05a8-11eb-904a-69d9e87a7468.jpg)
![20201003184017_1](https://user-images.githubusercontent.com/42655690/94996947-18951480-05a8-11eb-808f-3f00655868ff.jpg)

I attached wined3d images, there are other bugs (like no hair and kinda broken clothes), but not this one indeed.

**Comment by doitsujin** [comment]
How exactly do you reproduce this bug? The game seems to look fine on the latest Nvidia Vulkan beta driver:

![Screenshot_20201003_214431](https://user-images.githubusercontent.com/25567304/95000510-a8938800-05c1-11eb-8f44-178c0219dce8.png)

**Comment by 3kinox** [comment]
Oh yeah sorry for not being precise enough: The bug only happens in some areas. The one I showed you is when going outside of the village later in the story - when switching protagonist - At that time, it happens at multiple times in the village too, notably during a fight included in the story, and almost directly after switching characted while teaching martial arts to children, and near the a river with a boat. Otherwise, it also happens _near the fountain in the capital_ (nearer in the story for you). I can send more screenshots if it helps.
In the very first parts I did not have any issues, need to at least go until the capital - is half an hour of playing I'd say to get there.

I will also try latest beta drivers just in case.

**Comment by doitsujin** [comment]
Please provide a savegame if possible, I don't really have the time to play through the entire game to (maybe) find a spot where the bug appears.

**Comment by LordJBeckman** [comment]
Online game, syncs against the server so that's going to be a problem and while offline was considered the game appears to be done with patches and nothing like this was implemented.

There's the config file in the game folder but I think that's about all you can find locally, shame as once the game is finished it's possible to do chapter replays which would have aided with hopping around to later areas (It's a lengthy game even without the grind for levels/items and the usual.) even just getting through the prologue part and getting to the chapters after is a couple of areas and one dungeon so a few hours minus what might be possible to do by skipping through cutscenes and dialogue.

**Comment by 3kinox** [comment]
Okay, as @LordJBeckman said, no way to transfer saves ... But, I managed to get an apitrace, turns out, load time is tied to framerate .... So it was just excruciatingly slow. With DXVK_ASYNC=1 I ended up managing to get to a state where I could get it done. There goes the link: https://we.tl/t-Lif4srxNYK (on wetransfer since firefox send is dead and github won't take such large files...)

**Comment by doitsujin** [comment]
@3kinox thanks, but the trace file is broken since it does not contain any DXGI calls, and I can therefore not replay it.

Did you copy **both** `dxgi.dll` and `dxgitrace.dll` from apitrace next to the game, and did you also set the DLL override for dxgi to `native`? (`WINEDLLOVERRIDES=dxgi=n`)

**Comment by 3kinox** [comment]
@doitsujin I did copy both but indeed, I did not put the override. I'm on proton, and I've added the WINEDLLOVERRIDES=dxgi=n in launch option now. Here's the result: https://we.tl/t-HACeB5xUD8
I stayed at bug position at the end - you can ignore the few first tries, hard to control anything at sub 1 fps ;p

**Comment by doitsujin** [comment]
Thanks, that one works. Seems like an Nvidia-only problem, it works fine on RADV but I can reproduce the bug on NV.

**Comment by 3kinox** [comment]
Just chiming in to say the bug is still present with latest driver/dxvk (in proton ge). Any other thing I can do to help ?

**Comment by Blisto91** [comment]
@3kinox Friendly ping. Could i get you to try this again with latest dxvk and drivers?

**Comment by 3kinox** [comment]
@Blisto91 I tried with latest dxvk git and nvidia 515.57, no luck bug is still there.

**Comment by Blisto91** [comment]
Made a trace so just adding it to the issue here. https://mega.nz/file/MpYW2ByB#Eq4bO7kfyx5yPbn3luhKLFXDSNSZYBKJruTe07PtYb8

It is a bit cursed since it doesn't show the main menu or loading screen so you can see the world blinking and everything loading in. The actual ingame time is at the end when you see the main character.

**Comment by doitsujin** [comment]
Does the above PR fix the issue?
