### ISSUE TITLE
Possible regression - NosTale is not interpreting clicks correctly (because some kind of built-in anticheat?)

### ISSUE THREAD

**Issue by HoshiYamazaki** [doitsujin/dxvk#1787]
Game does not interpret clicks correctly - it's not possible to walk around with character and also clicking on items is causing odd behaviour (they are changing to random quotes).
Same issue appears on mac since years: https://bugs.winehq.org/show_bug.cgi?id=42999
Not sure if wine or dxvk bug, on gallium nine and steam proton it works fine.

### Software information
NosTale, wine with desktop emulation (because for some sake wayland (or xwayland) can't handle mouse clicks on one of my monitors, and if I will emulate desktop it does work fine).

### System information
- GPU: rx5700 XT
- Driver: AMDGPU
- Wine version: 5.18
- DXVK version: 1.7.1

### Apitrace file(s)
- For some reason when I launched apitrace with:
`wine apitrace-latest-win32/bin/apitrace.exe trace -a dxgi GF_Login.exe`
I was not able to get log in the directory, this is possible other issue.

### Log files
- d3d9.log: It's empty for some reason.
- d3d11.log: Same as d3d9.log
- dxgi.log: 
[gfclient_dxgi.log](https://github.com/doitsujin/dxvk/files/5322053/gfclient_dxgi.log)
- wine.log:
[nt_wine.log](https://github.com/doitsujin/dxvk/files/5322055/nt_wine.log)

**Comment by HoshiYamazaki** [comment]
Hmm, that's interesing, it doesn't work on wine 5.18 on Arch with DXVK 1.7, but appear to function properly on Steam Proton with the same DXVK number. Probably wine issue, I installed dxvk via:
`export WINEPREFIX=~/.wine ./setup_dxvk.sh install`

**Comment by K0bin** [comment]
This is almost certainly not a DXVK bug. DXVK has nothing to do with input.

**Comment by HoshiYamazaki** [comment]
Gonna close that and reopen if I will be sure that's DXVK bug and will be not getting resolved.
