### ISSUE TITLE
Deus Ex Mankind Divided from gog.com exits after launcher without any error-message in wine.

### ISSUE THREAD

**Issue by roidal** [doitsujin/dxvk#1788]
The gog.com version from Deus Ex Mankind Divided exits immediately after klicking the play-button in the launcher.
There are no error-messages in STDOUT/STDERR.
It doesn't seem to be a crash either since no infos in dmesg and coredumpctl.

Without DXVK the game can be launched from wine resulting in alot of graphical errors.

### Software information
Deus Ex Mankind Divided Digital Deluxe

### System information
- GPU: Navi 14 [Radeon RX 5500]
- Driver: radeonsi/mesa-20.1.9
- Wine version: wine-5.18 (Staging)
- DXVK version: 1.7.2

### Apitrace file(s)
apitrace.exe could not be found

### Log files
- d3d11.log: [DXMD_d3d11.log](https://github.com/doitsujin/dxvk/files/5353409/DXMD_d3d11.log)
- dxgi.log: [DXMD_dxgi.log](https://github.com/doitsujin/dxvk/files/5353407/DXMD_dxgi.log)

If more Informations are needed let me know!

**Comment by roidal** [comment]
Looks like the dedcompiler_47 has to be installed.
Now i can run the game but it crashes during the intro when starting a new game with:
`err:   D3D11RasterizerState: Antialiased lines not supported`

Is there a way to bypass that?
[DXMD_d3d11.log](https://github.com/doitsujin/dxvk/files/5353662/DXMD_d3d11.log)
[DXMD_dxgi.log](https://github.com/doitsujin/dxvk/files/5353663/DXMD_dxgi.log)

**Comment by roidal** [comment]
Now it seems to be something else, it is crashing with a memory violation (while compiling shaders?).

Sorry for the inconvenience by creating this bugreport.

**Comment by doitsujin** [comment]
The steam version works fine here; unless there is a difference to the GoG build there's going to be something wrong on your end.

**Comment by roidal** [comment]
[stdouterr.txt](https://github.com/doitsujin/dxvk/files/5354960/stdouterr.txt) containing the console output. If i should enable some WINEDEBUG let me know.

Interessting might be 
[Deus Ex -  Mankind Divided.log](https://github.com/doitsujin/dxvk/files/5354966/Deus.Ex.-.Mankind.Divided.log)
containing:
`14:48:40:047 (00000416) > [Crash] Unhandled exception at address 0x0000000041725c9b (code: 0xc0000005): "Access violation"`

Which seem to be a common problem on Windows too?

Thank you for investigating!

**Comment by jrugia** [comment]
@roidal : d3dcompiler_47 is for DX12 while **d3dcompiler_43** is for **DX11**. You might want to double check that out.

I tried this on my system with very similar setup, GOG version too. Game is running fine for me, benchmark and first mission loaded without issues. Details below.

System information

 OS: Debian 9.12
 CPU: Core i5-4590
 GPU: Navi 14 [Radeon RX 5500]  - 8GB Model
 Driver: radeonsi/mesa-20.1.9
 Wine version: wine-5.9 (Staging)
 DXVK version: 1.7.2

First Mission:
![2](https://user-images.githubusercontent.com/13750621/95592757-5e8b2600-0a49-11eb-940a-22f7e96a7d41.jpg)

Graphics settings:
![1](https://user-images.githubusercontent.com/13750621/95592762-5fbc5300-0a49-11eb-8c31-8d70a03f8777.jpg)

Wine overrides used:
![Screenshot at 2020-10-09 16-10-06](https://user-images.githubusercontent.com/13750621/95593400-eec96b00-0a49-11eb-9c5d-c20873a1865d.png)

**Comment by roidal** [comment]
Thanks for your reply!

I'am not able to get the game running, even when trying to copy your setup.
The only difference i see is that i have a newer LLVM and wine-version.

Meanwhile i'am out of ideas.

@jrugia how do you launch the game, and in which directory is it installed?

**Comment by roidal** [comment]
update:

after setting `RADV_DEBUG=errors`
i have following lines in stderr:
`../src/amd/vulkan/radv_descriptor_set.c:494: VK_ERROR_OUT_OF_POOL_MEMORY`

**Comment by jrugia** [comment]
@roidal I use my own scripts for running Wine games (No lutris, steamplay....etc). I kept the game installed, will give it another try tomorrow with Wine 5.18 to match your setup even closer and report back.

Afraid I can't help much about the error in radv debug though. It's beyond my understanding.

**Comment by roidal** [comment]
Update:

Seem to be a problem with wine itselfe.

After changing to wine from lutris (version 5.7) the benchmark works.
