### ISSUE TITLE
Trackmania 2020 through Uplay launch crash

### ISSUE THREAD

**Issue by vilhub** [doitsujin/dxvk#1789]
Hi,

Since about two weeks ago, Trackmania 2020 stopped working. It used to work three weeks ago but my GPU drivers updated from 440 to 450 and Trackmania also had an update. The game runs fine if I disable DXVK.

The main error I see in the logs is
```
warn:  winevulkan detected, disabling exclusive fullscreen support
err:   Failed to create surface
```
and the game won't launch from the Uplay portal.
If I add dxgi and d3d9 params to defer surface creation, the game runs but I get a black screen with the game music.

Not sure if it's relevant but if I don't specify vendorId and deviceId as dxgi parameters, I get
```
ERROR: Could Not Get Primary Adapter Handle
ERROR: Could Not Get Primary Adapter Handle
```
however I didn't specify them before the updates and the game ran fine. If I do specify them, these errors disappear but the surface creation error still makes it crash

### Software information
Trackmania 2020 through the Uplay portal

### System information
- GPU: 2x Geforce RTX 2070 (no SLI, only one is used for gaming normally)
- Driver: 450.66
- Wine version: 5.18
- DXVK version: 1.7.2

### Log files
- d3d9.log: NA
- d3d11.log: [Trackmania_d3d11.log](https://github.com/doitsujin/dxvk/files/5360131/Trackmania_d3d11.log)
- dxgi.log: [Trackmania_dxgi.log](https://github.com/doitsujin/dxvk/files/5360134/Trackmania_dxgi.log)

**Comment by doitsujin** [comment]
> err:   Failed to create surface

Sounds like a winevulkan issue, this cannot be fixed on our end.

**Comment by Iglu47** [comment]
> Since about two weeks ago

can you try on wine 5.16 or older?

**Comment by Iglu47** [comment]
I tried wine-5.16, 5.17, 5.18. game works/no crash on any version. 
nvidia driver vulkan beta (I'm still on 455.22.4) 
game version: 202010090924-202010091058
[wine-5.18-console-output.log](https://github.com/doitsujin/dxvk/files/5360501/wine-5.18-console-output.log)

**Comment by vilhub** [comment]
Thanks for testing! Here's my wine log with 5.18. Seems like instead of the "Presenter" log lines that you get I get this "failed to create surface".
[wine-5.18.log](https://github.com/doitsujin/dxvk/files/5360967/wine.log)
I will test with older wine versions

**Comment by vilhub** [comment]
Alright, I figured it out.
When I first installed the game 2 months ago, Trackmania could not find my GPU so I had to manually set my GPU name in `$prefix/drive_c/users/$username/My Documents/Trackmania/Config/Default.json`, the lines `"Adapter" : "",` to `"Adapter" : "Geforce RTX 2070",`.

What happened was that when the game updated, the Trackmania GPU key names in the mapping changed so my GPU could not be found once again because the correct name changed from `Geforce RTX 2070` to `NVIDIA Geforce RTX 2070`. After updating everything (Trackmania, wine, Nvidia driver) if I just leave it blank as `"Adapter" : "",` it is now able to find my GPU so I recommend leaving it blank.

If someone runs into similar issues with Trackmania with GPU not found you can find the list of GPU key names in `$prefix/drive_c/users/$username/My Documents/Trackmania/Config/GfxDevicePerfs.txt`.
Thanks for the help!

**Comment by Iglu47** [comment]
Oh, good. because I additionally tried 440.100 450.66 450.80.2 455.28 455.26.1 - and everything works fine
![tm2020_wine_518_450 66](https://user-images.githubusercontent.com/25866099/95679608-a68e8200-0bdc-11eb-9a61-dacec3064d8b.png)

**Comment by Voyajer** [comment]
> 

Leaving default.json blank or adding the appropriate string for my GPU doesn't seem to make a difference and neither let the game launch.
