### ISSUE TITLE
[d3d9] Guilty Gear Xrd -Revelator- rendering issues 

### ISSUE THREAD

**Issue by ranplayer** [doitsujin/dxvk#1790]
Some rendering issues happen during the fights: on some characters presentations and scenarios. WineD3D renders everything normally.

Some pictures from the character "Sol Bad Guy" battle presentation

![20201013161252_1](https://user-images.githubusercontent.com/69990640/95908650-b8565d80-0d73-11eb-821f-b8bd5940dd6d.jpg)
[DXVK 1.7.2]

![20201013161559_1](https://user-images.githubusercontent.com/69990640/95908681-c2785c00-0d73-11eb-9602-2a12db613d84.jpg)
[WineD3D]

### Software information
Guilty Gear Xrd -Revelator- (SteamId: 520440)

### System information
- GPU: GT 750M | GTX 960
- Driver: 450.66
- OS: ArchLinux
- Wine version: Proton 5.0-9 | Proton GE 5.9-GE-8-ST
- DXVK version: 1.7.0 -> 1.7.2

### Apitrace file(s)
I've tried to retrieve the Apitrace following this tutorial (https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace), but unfortunately this file (https://people.freedesktop.org/~jrfonseca/apitrace/apitrace-msvc-latest.7z) is unavailable. I've attached the proton logs to try helping you out.

### Log files
[steam-520440.tar.gz](https://github.com/doitsujin/dxvk/files/5373732/steam-520440.tar.gz)

If more logs and information are required, let me know.

**Comment by DadSchoorse** [comment]
> I've tried to retrieve the Apitrace following this tutorial (https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace), but unfortunately this file (https://people.freedesktop.org/~jrfonseca/apitrace/apitrace-msvc-latest.7z) is unavailable. I've attached the proton logs to try helping you out.

Use the downloads on https://apitrace.github.io/ instead.

**Comment by ranplayer** [comment]
Sure... I'm going to follow the tutorial and attach the logs here ASAP. Thanks @DadSchoorse

**Comment by ranplayer** [comment]
Apitrace uploaded to Mega ->  https://mega.nz/file/B8Fi0L6b#0mpQO3rTlY4sz7IK6GyQMtY6yHIUKxNi899iECARmSI

**Comment by DadSchoorse** [comment]
Might be float emulation related, one draw results in vertex explosions with good looking input.

**Comment by ranplayer** [comment]
@DadSchoorse you are right. Disabling float emulation (`d3d9.floatEmulation = False`) fixed the battle presentation issues. I'm going to play a full arcade session to see if there are any drawbacks related. Thanks.

**Comment by ranplayer** [comment]
I've just played a full arcade/episode will float emulation disabled, and all the glitches disappeared. No performance regressions noticed.

I've tested in a middle-end hardware (Nvidia GTX 970 4GB, 16 GB RAM, Core-i5 3.7Ghz) and a low-end one (Nvidia GT 740M, 8 GB RAM, Core i7 3.1Ghz).

Unfortunately I have no AMD hardware to test and give a feedback.

The game executable is `GuiltyGearXrd.exe`

**Comment by K0bin** [comment]
Should be fixed by c13395db970d16a5631a7c0926e2c4529d2710c3

**Comment by ranplayer** [comment]
Fixed indeed. Thank you guys.
