### ISSUE TITLE
NFS Most Wanted Black Edition v 1.3 (2005) lighting problems

### ISSUE THREAD

**Issue by IvoAndonov** [doitsujin/dxvk#1792]
On NFS MW 2005 there are lighting problem:
• the sky looks bright white when it should be gray; this bright white sky sometimes flickers and when it starts flickering, this also causes some kind of a brightness bug - all shadows become pitch black.
• when exiting a tunnel, there's this bright white light instead of the road. When you exit the tunnel and it's behind you, that light disappears and everything returns to normal.

### Software information
NFS Most Wanted Black Edition v 1.3 (2005)

### System information
- GPU: 1050 Ti 4GB
- Driver: 455.28
- Wine version: 5.19
- DXVK version: 1.7.2

### Apitrace file(s)
https://drive.google.com/file/d/1N8VLXEqINZhb3CuAFbxk0jGxKgs1BDUK/view?usp=sharing
(this is the first time I use apitrace, I hope I did it right)

### Log files
https://drive.google.com/file/d/1kQ-rWBCl0cDBgGiXcS3R2UyHf8UkaO0H/view?usp=sharing

###Screenshots
The sky in Linux: https://i.imgur.com/v1JSQ45.png
The light when exiting a tunnel: https://i.imgur.com/hgrlV2o.png

The sky in Windows: https://i.imgur.com/8YnPah9.png (ignore the top left info, this is a screenshot from Windows 7).

**Comment by ViNi-Arco** [comment]
@IvoAndonov For real? I always thought that that glow in the sky was the Bloom effect.
https://img.tpx.cz/uploads/NfsMwBloomBug.png
Apparently I was duped by the Graphic Bug 😂😂

In the Log he reports this:
warn:  DxsoCompiler::processInstruction: unhandled opcode: Phase
warn:  DxsoCompiler::processInstruction: unhandled opcode: Phase

**Comment by IvoAndonov** [comment]
With overbright (bloom) effect the sky doesn't look like this in Windows and the light at exiting a tunnel doesn't exist there. So this must be a D3D9 problem.
As for the logs error - I have no idea what it means.

**Comment by K0bin** [comment]
Those log errors aren't really errors. They aren't a problem.

**Comment by NerosTie** [comment]
Could it be normal?
https://tweakguides.pcgamingwiki.com/NFSMW_6.html

**Comment by ViNi-Arco** [comment]
@NerosTie 

> Could it be normal?
https://tweakguides.pcgamingwiki.com/NFSMW_6.html

I knew it! this glow is too beautiful to be a bug.

I took advantage and researched more, in this video [GGB](https://www.youtube.com/watch?v=ONtF3FVdknk) is running NFS Most Wanted on Windows 7 and has that same glow in the sky.

**Comment by ViNi-Arco** [comment]
but the right thing is to wait, maybe there is a bug involved in this, I will investigate further.

**Comment by ViNi-Arco** [comment]
@IvoAndonov 
I can't find something that relates that glow to a bug, but I found a way to decrease it.
En you will need [NFSMWExOpts](https://github.com/ExOptsTeam/NFSMWExOpts), you use this [config](https://img.tpx.cz/uploads/ConfigBloomExtraOpts.png), in my game it was like [this](https://img.tpx.cz/uploads/NfsMwBloom.png), much better right.

if you can, use [NFSMW HD Reflections](https://github.com/AeroWidescreen/NFSMWHDReflections), it [corrects some problems](https://img.tpx.cz/uploads/NFSMWhdreflectionfixes.png) and improves the graphics of the game, I use it on my NFSMW.

**Comment by IvoAndonov** [comment]
> @IvoAndonov
> I can't find something that relates that glow to a bug, but I found a way to decrease it.
> En you will need [NFSMWExOpts](https://github.com/ExOptsTeam/NFSMWExOpts), you use this [config](https://img.tpx.cz/uploads/ConfigBloomExtraOpts.png), in my game it was like [this](https://img.tpx.cz/uploads/NfsMwBloom.png), much better right.
> 
> if you can, use [NFSMW HD Reflections](https://github.com/AeroWidescreen/NFSMWHDReflections), it [corrects some problems](https://img.tpx.cz/uploads/NFSMWhdreflectionfixes.png) and improves the graphics of the game, I use it on my NFSMW.

I found another way to remove this glow and keep HDR on - set visual treatment to low and disable overbright but increase road reflections to high. But I'll try your way too, though I used something similar on NFSU2 and it kept crashing on startup until I removed the dll in question.
Btw, how did you fix the stretching of the heat level and speedometer circles? I'm using nfsmwres.exe (there's an easy way to make it work on Linux) and all vehicles' resolutions are OK, only the HUD circles are stretched.

**Comment by ViNi-Arco** [comment]
> I found another way to remove this glow and keep HDR on - set visual treatment to low and disable overbright but increase road reflections to high. But I'll try your way too.

great that you were already getting around this, I hope you like my solution.

> Btw, how did you fix the stretching of the heat level and speedometer circles?

I'm using [Widescreen Fix](https://github.com/ThirteenAG/WidescreenFixesPack/releases/tag/nfsmw), here @ThirteenAG and @AeroWidescreen did a wonderful job.

**Comment by IvoAndonov** [comment]
> > I found another way to remove this glow and keep HDR on - set visual treatment to low and disable overbright but increase road reflections to high. But I'll try your way too.
> 
> great that you were already getting around this, I hope you like my solution.
> 
> > Btw, how did you fix the stretching of the heat level and speedometer circles?
> 
> I'm using [Widescreen Fix](https://github.com/ThirteenAG/WidescreenFixesPack/releases/tag/nfsmw), here @ThirteenAG and @AeroWidescreen did a wonderful job.

This doesn't work on Linux. Typical...

**Comment by NerosTie** [comment]
@IvoAndonov you need to add "dinput8" in winecfg → library to make this fix work.

**Comment by ViNi-Arco** [comment]
@IvoAndonov 
> This doesn't work on Linux. Typical...

Of course it works, I use Widescreen Fix on NFS MW on Linux for 2 years, working 100%.

See which executable you are using in your NFSMW, there is one that doesn't work. You can create a `global.ini` text file with [this configuration](https://img.tpx.cz/uploads/configUltimateAsiLoader.png) and paste it into the `scripts folder` along with `NFSMostWanted.WidescreenFix.asi`

Do what @NerosTie said, if you haven't already.

**Comment by IvoAndonov** [comment]
> @IvoAndonov you need to add "dinput8" in winecfg → library to make this fix work.

Still not working. Screw it, I'll live with stretched HUD. The most important thing is that the cars aren't stretched.

**Comment by K0bin** [comment]
So this isn't a bug after all?

Feel free to reopen, if it is.
