### ISSUE TITLE
Bullets Per Minute graphical issues

### ISSUE THREAD

**Issue by Monsterovich** [doitsujin/dxvk#1793]
The graphical artifacts appear in dxvk v1.7.2, dxvk v1.7.1. They also appear in dxvk v1.7 but to a much lesser degree.

dxvk v1.7: https://www.youtube.com/watch?v=r-2Oj7pspsI
dxvk v1.7.2: https://www.youtube.com/watch?v=9l52CGf8j_w

### Software information
Game: BPM: Bullets Per Minute (v1.41159)
Settings: any

### System information
- GPU: Mesa DRI Intel(R) HD Graphics 520 (SKL GT2)
- Driver: Mesa 20.2.1 - kisak-mesa
- Wine version: wine-5.19 (Staging)

### Apitrace file(s)
https://drive.google.com/file/d/1x4p6B4aE1IA4hGiacAzlKONIGbcSFsmG/view?usp=sharing
The apitrace is taken with wine in dxvk v1.7. I don't have windows and wined3d is not working (black screen).

### Log files
- d3d11.log: [BPMGame-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/5385576/BPMGame-Win64-Shipping_d3d11.log)
- dxgi.log: [BPMGame-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/5385574/BPMGame-Win64-Shipping_dxgi.log)

**Comment by doitsujin** [comment]
Can you try `d3d11.enableRtOutputNanFixup = True`?

**Comment by Monsterovich** [comment]
> Can you try `d3d11.enableRtOutputNanFixup = True`? Artifacts like this are usually caused by games being dumb and not really DXVK bugs.

I see no difference. The artifacts are still present with this option enabled (dxvk 1.7.2).

**Comment by doitsujin** [comment]
Just tested this on Windows with native D3D11, happens there as well. Not a DXVK bug.
