### ISSUE TITLE
[d3d11] Assassin's Creed Odyssey Crash/Close on Launch (Windows)

### ISSUE THREAD

**Issue by computeteen5** [doitsujin/dxvk#1794]
I'd really like to use dxvk for Assassin's Creed Odyssey since I've seen it massively improve performance, but I can't seem to get it to work. It'll open and run the splash screen for a few seconds, but silently crash/close before opening the main game window. The cache formed is only ~1KB.

dxvk Version 1.7.2

i7-7700 @ 4.0 GHZ
16 GB DDR4-2400
NVIDIA GTX GeForce 1070
Samsung EVO 950
WD Passport 4 TB
WD Passport 2 TB
WD Passport 2 TB
[ACOdyssey_d3d11.log](https://github.com/doitsujin/dxvk/files/5394745/ACOdyssey_d3d11.log)

[DxDiag.txt](https://github.com/doitsujin/dxvk/files/5394747/DxDiag.txt)

[SYSINFO.zip](https://github.com/doitsujin/dxvk/files/5394748/SYSINFO.zip)

[ACOdyssey.dxvk-cache.zip](https://github.com/doitsujin/dxvk/files/5394750/ACOdyssey.dxvk-cache.zip)

**Comment by K0bin** [comment]
You forgot to copy dxgi.dll.

**Comment by computeteen5** [comment]
Having both dxgi.dll and d3d11.dll in the game folder didn't help.
[ACOdyssey_dxgi.log](https://github.com/doitsujin/dxvk/files/5397082/ACOdyssey_dxgi.log)
[ACOdyssey_d3d11.log](https://github.com/doitsujin/dxvk/files/5397083/ACOdyssey_d3d11.log)

**Comment by doitsujin** [comment]
We don't support Windows for a reason. Probably either some overlay (uplay? third-party crap?) crashing the game for you.

**Comment by Ryusennin** [comment]
Odyssey+DXVK works fine in both Win7 and Win10. I didn't have to disable any overlay.

https://i.imgur.com/7ciw46J.jpg

If you're using RTSS, make sure to check "Custom Direct3D Support" in the game's profile.

**Comment by computeteen5** [comment]
> Odyssey+DXVK works fine in both Win7 and Win10. I didn't have to disable any overlay.
> 
> https://i.imgur.com/7ciw46J.jpg
> 
> If you're using RTSS, make sure to check "Custom Direct3D Support" in the game's profile.

Tried RTSS with both Custom Direct3D Support and disabled Application detection level. No dice either time. The uPlay Overlay is disabled as well. I'd love to get this working because I've seen the performance improvements running this way.

**Comment by doitsujin** [comment]
You may need to *uninstall* RTSS since its own Vulkan layer is known to cause problems with DXVK and is always active, whether the app is running or not.

**Comment by doitsujin** [comment]
FWIW you may also want to switch to borderless or windowed mode, proper fullscreen seems to crash on some setups for some reason.

**Comment by Sailorcat666** [comment]
Did you fix it? I'm having that exact problem with Origins and I don't know what to do :(

**Comment by computeteen5** [comment]
Nope. Still broken for me.

**Comment by Sailorcat666** [comment]
Maybe it's just because we don't have the original version of the game, at least I don't have it, I do play from a crack file :/
how about you?

**Comment by K0bin** [comment]
Piracy is explicitly discouraged and unsupported.

**Comment by doitsujin** [comment]
We obviously do not and will never support cracked versions of any game.

**Comment by Sailorcat666** [comment]
Then take your support and do whatever you want with it because I don't remember asked you for any support :), but surprise!! a lot of people on the world use games with crack versions :O!!!, and probably they do with dxvk, by the way I was just asking to the person who initiated the post, no need of post your politics of "please don't sue me" haha

**Comment by Noren971** [comment]
Exact same problem! Any solution since?

**Comment by doitsujin** [comment]
Use borderless windowed instead of exclusive fullscreen mode?

Anyway, closing, just use native D3D11 if you can't get DXVK to work on Windows.

**Comment by jejay** [comment]
Its awesome and a huge compliment that people are trying to use dxvk under windows!

**Comment by quentin452** [comment]
dxvk is work for me on windows
