### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Aeirex** [doitsujin/dxvk#1795]
While trying to build DXVK, the compiler fails. I am using Fedora 33 with the latest libraries.

[dxvk.log](https://github.com/doitsujin/dxvk/files/5395045/dxvk.log)

**Comment by Joshua-Ashton** [comment]
Your MinGW is missing threading support. Please read the README.

`/usr/lib/gcc/x86_64-w64-mingw32/10.2.1/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lpthread`

**Comment by Aeirex** [comment]
For anyone having issues with this, follow this.
https://bugzilla.redhat.com/show_bug.cgi?id=1889044
