### ISSUE TITLE
dxvk 1.7.2 breaks Death Stranding

### ISSUE THREAD

**Issue by elogicuk** [doitsujin/dxvk#1796]
When i launch Death Stranding with dxvk 1.7.1 it works

when i use the latest 1.7.2 i get this error 

![Screenshot from 2020-10-17 17-15-54](https://user-images.githubusercontent.com/25700447/96333817-9ecc5300-109e-11eb-9c1c-219badef1e78.png)

**Comment by mozo78** [comment]
Working fine here. You have to make a d3d12 winetricks override.

**Comment by elogicuk** [comment]
Im new to linux gaming and linux in general, please can you show me how mozo78
thank you

**Comment by mozo78** [comment]
Here you are:
https://github.com/Matoking/protontricks

**Comment by elogicuk** [comment]
hey mozo78 i have wintricks installed 

now all i need todo is this?

Add "d3d12.dll" to the dll-overrides set to "native".

**Comment by mozo78** [comment]
Get the d3d12 dll from latest ProtonGE and put in the game's root directory. You can find it in /dist/lib64/wine/vkd3d-proton/.

**Comment by elogicuk** [comment]
thanks so much
