### ISSUE TITLE
Every game crashes on Windows with dxvk

### ISSUE THREAD

**Issue by AndreyRGW** [doitsujin/dxvk#1800]
I'd really like to use dxvk in Windows because I've seen it improve performance, but I can't run it. Each game starts for a few seconds, but then closes before opening the game window.

Windows 10 
DXVK 1.7.2
GTX 1660 (Standard 456.71)

[PaintTheTownRed_d3d11.log](https://github.com/doitsujin/dxvk/files/5433014/PaintTheTownRed_d3d11.log)
[PaintTheTownRed_dxgi.log](https://github.com/doitsujin/dxvk/files/5433015/PaintTheTownRed_dxgi.log)
[SRTTR_d3d11.log](https://github.com/doitsujin/dxvk/files/5433018/SRTTR_d3d11.log)
[SRTTR_dxgi.log](https://github.com/doitsujin/dxvk/files/5433019/SRTTR_dxgi.log)
[gta_sa_d3d9.log](https://github.com/doitsujin/dxvk/files/5433021/gta_sa_d3d9.log)
[CivilizationV_DX11_d3d11.log](https://github.com/doitsujin/dxvk/files/5433022/CivilizationV_DX11_d3d11.log)
[CivilizationV_DX11_dxgi.log](https://github.com/doitsujin/dxvk/files/5433023/CivilizationV_DX11_dxgi.log)

I tried 4 drivers: 
460.20
457.00
456.71
456.55

**Comment by K0bin** [comment]
Windows is unsupported and a lot of games simply refuse to work with DXVK on Windows.

Do make sure you're not running any overlays like RivaTuner/MSI Afterburner, Steam overlay, Uplay, Origin, etc.

**Comment by AndreyRGW** [comment]
> Windows is unsupported and a lot of games simply refuse to work with DXVK on Windows.
> 
> Do make sure you're not running any overlays like RivaTuner/MSI Afterburner, Steam overlay, Uplay, Origin, etc.

I turned off all the overlays. I tried dxvk in different games: with dx9, dx9 and 64bit, dx11 etc.

**Comment by AndreyRGW** [comment]
> Windows is unsupported and a lot of games simply refuse to work with DXVK on Windows.

https://www.youtube.com/watch?v=QJfw6DnOD6E
But on this video dxvk works.

**Comment by K0bin** [comment]
It works with some games and doesnt work with others.

**Comment by doitsujin** [comment]
SotTR works fine here on Windows (AMD GPU). I don't have any of the other games.

Windows not a supported platform for *this very reason*, there's no telling why it's broken for you.
