### ISSUE TITLE
Titanfall 2 (DxbcCompiler: Unsupported custom data block: Opaque)

### ISSUE THREAD

**Issue by 0neGuyDev** [doitsujin/dxvk#1802]
### Software information
- Game: Titanfall 2
- DXVK Conf: `dxgi.nvapiHack = False`
- Other settings: Mostly default from the Lutris install, tried reverting no difference

### System information
- GPU: GTX 1650 
- Driver: nvidia 455
- Kernel: 5.9.1
- Wine version: fshack-5.6.5
- DXVK version: 1.7.1L-743f309 (Tho 1.7 and 1.6.1L also fails)

### Log files
[Pastebin](https://pastebin.com/XR6BiPJm)
It's for the most part just me being spammed with `warn:  DxbcCompiler: Unsupported custom data block: DxbcCustomDataClass::Opaque`

### Extra info
It should be noted that it worked this Sunday, and only stopped working around Monday/Tuesday-ish. I can't seem to find anything that's been updated and changed, with a reinstall of the game it still did not fix the issue

**Comment by K0bin** [comment]
Are there any actual issues with the game?
That log line doesn't really mean anything.

**Comment by 0neGuyDev** [comment]
Right, I somehow forgot that part, and I also have no clue whether it's even important. When the game gets past the first few launch screens it just goes black, and at best if your lucky it's going to give you a frozen image of the main menu, nothing else.

**Comment by doitsujin** [comment]
> DXVK Conf: dxgi.nvapiHack = False

why?

Not sure if this is causing any issues but in general it's not recommended to change config options *unless it is necessary*.

**Comment by 0neGuyDev** [comment]
I got it working yesterday not knowing what fixed it, but may suspicions seem to be that when started through just `startx` it doesn't work but when started through a proper DM like LightDM it works, so obviously it's something that LightDM does automatically, other games not using DXVK seems to be working... Is there any way to possibly do something on DXVK's end or would this only be fixable with a Xorg config change of some kind...?

I doubt this could be the case but it could possibly be using the iGPU, at least is there a way to confirm any of this? As in which GPU it's using and possibly a way to tell it.

Logically I'd think it'd be using the default display, but possibly this is only on Xorg/NVIDIA's side...

**Comment by 0neGuyDev** [comment]
I think this was some sort of Xorg config issue... After doing multiple things (I didn't test which ones did they job I just know something fixed it) it seem to be working again, if the error happens again and I can confirm it's an actual issue with DXVK I'll re-open the issue

Things I did:
 - Added `modprobe nvidia` to `.xinitrc`
 - Added `nvidia` module to `mkinitcpio.conf`

Beyond many other things but those are the changes I'd say would be most likely to be what fixed it.

**Comment by Hentilador** [comment]
> ### Software information
> * Game: Titanfall 2
> * DXVK Conf: `dxgi.nvapiHack = False`
> * Other settings: Mostly default from the Lutris install, tried reverting no difference
> 
> ### System information
> * GPU: GTX 1650
> * Driver: nvidia 455
> * Kernel: 5.9.1
> * Wine version: fshack-5.6.5
> * DXVK version: 1.7.1L-743f309 (Tho 1.7 and 1.6.1L also fails)
> 
> ### Log files
> [Pastebin](https://pastebin.com/XR6BiPJm) It's for the most part just me being spammed with `warn: DxbcCompiler: Unsupported custom data block: DxbcCustomDataClass::Opaque`
> 
> ### Extra info
> It should be noted that it worked this Sunday, and only stopped working around Monday/Tuesday-ish. I can't seem to find anything that's been updated and changed, with a reinstall of the game it still did not fix the issue

this happens to me on windows too.

**Comment by K0bin** [comment]
It's irrelevant on Windows too...
