### ISSUE TITLE
BLAZBLUE: Cross Tag Battle controller input stops working with DXVK

### ISSUE THREAD

**Issue by ILOVEPIE** [doitsujin/dxvk#1803]
DXVK prevents controller input from working.

I was using steam input, not sure if that was a factor.

**Comment by doitsujin** [comment]
So what exactly is the problem? Does controller input work with wined3d or what? Why no logs?

**Comment by ILOVEPIE** [comment]
The controller input stops working as soon as DXVK is used. I'll include
some logs in a bit.

**Comment by doitsujin** [comment]
> The controller input stops working as soon as DXVK is used.

So does this mean that controller input works fine when using wined3d instead? Please be more precise.

Also, which API does this even use? D3D9 *sort of* messes with window messages (not that it should affect controllers of all things) but D3D11 literally doesn't, so even if it doesn't work, there's probably nothing we can do anyway.

**Comment by ILOVEPIE** [comment]
I think the game uses D3D9, but i'm not 100% certain ill have to double
check.

**Comment by Blisto91** [comment]
@ILOVEPIE Am i correct in assuming that your controller issue [has been resolved](https://github.com/ValveSoftware/Proton/issues/2832#issuecomment-892073554)?

**Comment by ILOVEPIE** [comment]
I'll double check.

**Comment by Blisto91** [comment]
@ILOVEPIE Friendly ping :slightly_smiling_face:

**Comment by ILOVEPIE** [comment]
yeah, the issue is resolved, the secondary controller issue is something that needs to be fixed in steam input so i'll create a new issue on that.
