### ISSUE TITLE
2 games running without fonts - any ideas?

### ISSUE THREAD

**Issue by IvoAndonov** [doitsujin/dxvk#1804]
2 games - "Next Stop 2" and "Next Stop 3" - run without fonts which makes them unplayable.

API traces don't seem to work for these 2 games, IDK why. I did it following the instructions and yet no file was created. So all I can provide are the d3d11 and dxgi logs. There are some warnings inside these logs but I'm not a programmer and I don't understand what do these warnings mean.

### Software information
Next Stop 2
Next Stop 3
default settings the games were installed with.

### System information
- GPU: GTX 1050 Ti 4GB
- Driver: 455.38
- Wine version: 5.20 
- DXVK version: 1.7.2

### Apitrace file(s)
- Put a link here

### Log files
[NextStop3_d3d11.log](https://github.com/doitsujin/dxvk/files/5471841/NextStop3_d3d11.log)
[NextStop3_dxgi.log](https://github.com/doitsujin/dxvk/files/5471842/NextStop3_dxgi.log)

**Comment by K0bin** [comment]
Do the fonts work with WineD3D?

**Comment by IvoAndonov** [comment]
> Do the fonts work with WineD3D?

I have no idea how to use WineD3D outside of Steam Proton. I only know library override in winecfg.

**Comment by IvoAndonov** [comment]
I found a way to fix the problem. It turned out I had to run "winetrucks corefonts".
