### ISSUE TITLE
[d3d11] MGSV crashes on startup with AMD cards

### ISSUE THREAD

**Issue by ZioPao** [doitsujin/dxvk#1806]
MGSV GZ and TPP crashes on startup with an AMD card. Some people in a discord server of mine managed to get it running on Pascal and later cards, but that's it. Maxwell is a wild card too.

### Software information
Windows 10 2004
Metal Gear Solid V: Ground Zeroes \ The Phantom Pain, every settings.

### System information
- GPU: RX 590
- Driver: 20.10.1
- DXVK version: 1.7.2

### Log files
[mgsvtpp_dxgi.log](https://github.com/doitsujin/dxvk/files/5496229/mgsvtpp_dxgi.log)
[mgsvtpp_d3d11.log](https://github.com/doitsujin/dxvk/files/5496230/mgsvtpp_d3d11.log)

**Comment by doitsujin** [comment]
The game works fine on RADV. We do not care about Windows-specific crashes since there's simply nothing we can do about those anyway.
