### ISSUE TITLE
Is it possible to merge dgVoodoo2?

### ISSUE THREAD

**Issue by clebercasali** [doitsujin/dxvk#1809]
dgVoodoo2 is another DirectX implementation.
It implements Glide, DirectDraw, D3D3/5/6/7, D3D8 and D3D9 on top of DirectX 11/12.
It's open source now: https://github.com/dege-diosg/dgVoodoo2
It already works on wine when combined with dxvk by using dll overrides.
Some DirectX 8 games that are unplayable slow with wine3d3, run very well with dgVoodoo2+dxvk.
Turning it into a single solution would reduce the overhead and make older games more accessible.

**Comment by K0bin** [comment]
> https://github.com/dege-diosg/dgVoodoo2

It's not. That GitHub repo has next to no source code.

**Comment by WinterSnowfall** [comment]
> Some DirectX 8 games that are unplayable slow with wine3d3, run very well with dgVoodoo2+dxvk.

Note that you can also use [d3d8to9](https://github.com/crosire/d3d8to9) to get those DX8 games working with DXVK. I've been doing just that for a while now and most of the bugs I've come across in DX8 games have been reported and fixed.

**Comment by clebercasali** [comment]
> Note that you can also use [d3d8to9](https://github.com/crosire/d3d8to9) to get those DX8 games working with DXVK. I've been doing just that for a while now and most of the bugs I've come across in DX8 games have been reported and fixed.

Last time I've tried with Phantasy Star Online : Blue Burst, it gave me a lot of black textures. I'll give it another shot. Thanks.
