### ISSUE TITLE
Support for volk metaloader?

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#181]
sorry if you are already aware of it but would be interesting to see if some overhead can be removed by using it or it's a thing to ask to wine vulkan devs?
https://github.com/zeux/volk
"volk is a meta-loader for Vulkan. It allows you to dynamically load entrypoints required to use Vulkan without linking to vulkan-1.dll or statically linking Vulkan loader. Additionally, volk enables loading Vulkan entrypoints directly from the driver which **can increase performance by skipping loader dispatch overhead.**

volk is written in C89 and supports Windows, Linux and Android.

**Comment by doitsujin** [comment]
> Additionally, volk enables loading Vulkan entrypoints directly from the driver which **can increase performance by skipping loader dispatch overhead.**

DXVK already does exactly that. The only difference is that DXVK statically links against vulkan-1.dll to get access to `vkGetInstanceProcAddr` and `vkGetDeviceProcAddr`, but there's no need to change that.
