### ISSUE TITLE
Slow NosTale performance in comparision with Gallium Nine or Windows native performance

### ISSUE THREAD

**Issue by HoshiYamazaki** [doitsujin/dxvk#1810]
As title says - despite the game being freaking p2w circlejet and I shouldn't play or support it, I decided to do that since I have friends here and I was active in community in the past.

### Software information
I use r5 3600 + rx5700 XT setup with 3200mhz 32GB of RAM, so there should not be any CPU bottleneck.
Game works without fps dropdowns on my rig on Windows/Gallium Nine.
The issue is mostly visible when you enter area with many people (for example nosville or the nosmarket area).
Also the FPS counter is beetwen 30-50 FPS in DXVK HUD, which, I think is bad performance since it should be constant 60 FPS for game from mid 2000 era. I tested it on actual 5.13-1 steam proton release.

### System information
- GPU: rx5700 XT
- Driver: AMDGPU (kernel 5.9.6, tested on many other kernel versions before too)
- Wine version: 5.13
- DXVK version: 1.7.2

### Apitrace file(s)
https://share.froggi.es/cedc91762a8e [Password: h4ppycr0w] [8 weeks expiration from today (11 november)]

### Log files
- d3d9.log: 
[NostaleClientX_d3d9.log](https://github.com/doitsujin/dxvk/files/5523732/NostaleClientX_d3d9.log)

**Comment by K0bin** [comment]
Are you sure the game doesn't slow down on Windows or Gallium Nine.
The game is really inefficient.

**Comment by HoshiYamazaki** [comment]
> Are you sure the game doesn't slow down on Windows or Gallium Nine.
> The game is really inefficient.
> 
> Can you reupload your apitrace?

The apitrace is still available, you can download it still for next two weeks.
Also the game doesn't slowdown on Windows/Gallium Nine, the performance is better because in nosville (when you are around many people) you don't get instant framedrops to 30 fps, and on DXVK you do. Also, Gallium Nine have really better performance than DXVK, probably even better performance than Windows, what I saw from my testing.

I want also to note that I tested the game yesterday with mesa-git and the performance issue persists. Gonna answer next questions on VKx discord or here in next week, I'm pretty busy nowadays.

**Comment by HoshiYamazaki** [comment]
So, I'm here again. The issue remains even on Windows - and I supposed the problem exists in Mesa and AMDGPU/AMDVLK (AMDVLK has the same performance penalty, but thats normal, since it's not very different from AMDGPU). So conclusion is clear - something is wrong in DXVK.

D9 on Windows:
![image](https://user-images.githubusercontent.com/21007545/103440830-2b6fc180-4c49-11eb-9306-0b61c5bf1490.png)

DXVK on Windows:
![image](https://user-images.githubusercontent.com/21007545/103440840-36c2ed00-4c49-11eb-9ba6-e8f5a25c48c1.png)

DGVoodoo:
![image](https://user-images.githubusercontent.com/21007545/103441676-db482d80-4c4f-11eb-8841-2ebe38fdf47e.png)

**Comment by K0bin** [comment]
Just gonna dump CME's findings from GitHub here:

![image](https://user-images.githubusercontent.com/1131720/107163066-c164dd80-69a7-11eb-8dbf-046ea4c65d6e.png)

>  seems like the game spams SetTransform(.., D3DTS_VIEW,..) like crazy

So I guess the solution would be to calculate the `NormalMatrix` and the `InverseView` on the GPU inside the fixed function vertex shader.

@Joshua-Ashton

**Comment by Blisto91** [comment]
Now i haven't compared to Gallium Nine, but comparing 1.7.2 to 1.10.1 this seems like it has improved a lot. Unless someone complains maybe this one can be closed? Tho dunno if there are still improvements to be had.

With the fps cap it's hard to compare proper numbers, but the GPU load also kinda speaks for itself.

<details>
  <summary>Linux</summary>
  
![Screenshot_20220409_201914](https://user-images.githubusercontent.com/47954800/162587668-a2b77ae5-13b3-43eb-b29e-72941d40b9f6.png)
![Screenshot_20220409_201742](https://user-images.githubusercontent.com/47954800/162587672-d239a5e9-f032-41d8-b0d5-a59a0633ca7f.png)
</details>

<details>
  <summary>Windows</summary>
  
![Capture2](https://user-images.githubusercontent.com/47954800/162587690-c0622c58-08a0-454e-9a79-ed46b90faeb3.PNG)
![Capture1](https://user-images.githubusercontent.com/47954800/162587708-e706771f-f20d-49c7-b22a-d5df6917990e.PNG)
</details>

**Comment by K0bin** [comment]
How fast does it run on Windows without DXVK at that spot?

**Comment by Blisto91** [comment]
Native windows d9 is slighty worse it seems looking at cpu and gpu usage.

<details>
  <summary>dxvk 1.10.1 windows</summary>
  
![Capture3](https://user-images.githubusercontent.com/47954800/162592497-406fee6b-8848-4bd2-b3c0-26d33a629a85.PNG)
</details>

<details>
  <summary>Native d9 windows</summary>
  
![Capture4](https://user-images.githubusercontent.com/47954800/162592490-72021bdf-197d-48c6-b56c-213566022958.PNG)
</details>

**Comment by Blisto91** [comment]
Some more tests.
Unless my memory is just really shit or i missed it last time then it seems they've added a slider allowing to raise the framerate cap all the way up to 200 in a update.

Here are some tests with dxvk 1.10.1

<details>
  <summary>Windows</summary>

**Without dxvk & framecap @ 200**
![nos_upt_nati](https://user-images.githubusercontent.com/47954800/164535529-78674a69-21c0-4aca-a000-7f1edcfbd19f.PNG)

**With dxvk & framecap @ 200**
![nos_upt_dxvk](https://user-images.githubusercontent.com/47954800/164535638-4e80b92e-2a01-4fff-b945-3e2c38df9a67.PNG)

</details>

Linux tests are on proton 5.13 to get around the inputs not working wine bug. Also uses dxvk 1.10.1

<details>
  <summary>Linux</summary>

**With dxvk & framecap @ 60 (default)**
![Screenshot_20220421_210202](https://user-images.githubusercontent.com/47954800/164536033-b1ca2f12-a07a-4208-bafb-090ad114b5bb.png)


**With dxvk & framecap @ 200**
![Screenshot_20220421_205850](https://user-images.githubusercontent.com/47954800/164536051-dcd1fbbe-a2c9-46cb-95c4-038adcff95dd.png)

</details>

The old framerate cap seems to be what caused all the extra frame timing variations as when it is raised to 200 as above you can see the graph is much nicer on windows. Even if the fps doesn't rise much from it.
Native dx9 and dxvk on windows seems to be at least on par and maybe dxvk goes ahead slightly also judging from gpu and cpu usage.

Linux seems to outperform windows with and without dxvk when i raise the framcap to 200 with around 15 - 20 more fps in this short test.
I also made a test where i set the framecap back to the 60 default and you can see the fps instead seems to stick in the low to mid 50's. Also frame timings are worse. So i would suggest raising the fps limit in the settings app.

**Comment by HoshiYamazaki** [comment]
@Blisto91 Yes, I tried game on 1280x1024 windowed mode and I got similar performance to your, still using r5 3600/rx5700 XT/3200mhz clocked RAM's. But I would not agree that game performs better on Linux - the game performs slighty worse after logging into international first server, to first channel, while being in nosville. I tested both operating systems on FullHD resolution using Xorg. I got around 45-60 fps in Windows and around 40-55 in Linux, so not really big difference, I would estimate it as 5-10%.

I think this game just can't sometimes achieve 60 fps no matter what, I heard from some people years ago that they tried to launch game on NVidia Titan X and had similar results. But, even if Linux has worse performance, it's not really noticeable and, because of that, I'm closing issue by now. If somebody does not agree - please post feedback here.

**Comment by Blisto91** [comment]
Ah that sucks. My tests weren't totally scientific either hehe.
But at least it seems to not be as bad as it used to be. Hopefully the game itself or wine/dxvk can improve a bit more here and there in the future.

**Comment by HoshiYamazaki** [comment]
> Ah that sucks. My tests weren't totally scientific either hehe. But at least it seems to not be as bad as it used to be and the game itself seems to be quite heavy. Hopefully the game or wine/dxvk can improve a bit more here and there in the future.

Sorry for mislead, I redone the tests and maybe because I'm little busy I didn't notice that game has better performance on Linux. On Windows - it has similar performance, it's around 40-50 fps, on Linux - 45-55 fps. I was switching the resolutions and I noted wrong fps scores... (I even use scaling for 4k display, so I must do bunch stuff around while testing). Anyway, as I said - the game engine is not able to achieve 60 fps sometimes no matter what, and if game runs better on Linux than on Windows, it's good reason to close this issue.

Again, sorry for posting wrong results - I really appreciate your work guys, and I hope you all will have good evening. Thanks!
