### ISSUE TITLE
Artificial Intelligence Machine: Objects randomly flicker

### ISSUE THREAD

**Issue by GranMinigun** [doitsujin/dxvk#1813]
Recently I started to get random glitches in games running through DXVK. Seemingly random objects may flicker from time to time, or constantly, or even never appear. In A.I.M., it can be gliders and entrance gates (animated objects?), or grass. In Tribes: Vengeance, it's interface elements like text or buttons, and even clouds in the main menu. I was able to get a trace for the former game, but the latter refuses to run.

It seems that more you play, more glitches will appear.

I feel like #1808 is related.

### Software information
- A.I.M.: Artificial Intelligence Machine, through d3d8to9
- Tribes: Vengeance, native D3D9 game

### System information
- GPU: Intel HD Graphics 630 (KBL GT2)
- Driver: Mesa 20.2.2
- Wine version: 5.20 Staging
- DXVK version: 1.7.2

### Apitrace file(s)
- [A.I.M.](https://drive.google.com/file/d/1tM7xTRKsK-zfJTZHKPStdangcJOO11VI/view?usp=sharing)

### Log files
- [AIM.EXE_d3d9.log](https://github.com/doitsujin/dxvk/files/5526526/AIM.EXE_d3d9.log)
- [TV_CD_DVD_d3d9.log](https://github.com/doitsujin/dxvk/files/5526611/TV_CD_DVD_d3d9.log)

**Comment by GranMinigun** [comment]
Updated Mesa to 20.2.4, Wine to 6.0-rc2 Staging, DXVK to 1.7.3. Ran Giants: Citizen Kabuto through dgVoodoo 2.72, D3D11 backend. Behaviour is similar - objects constantly flicker. Do you need an apitrace and in which setup (i.e., running through dgVoodoo or plain native DX7)? Maybe more test-subjects?

Logs:
- [Giants_d3d11.log](https://github.com/doitsujin/dxvk/files/5719829/Giants_d3d11.log)
- [Giants_dxgi.log](https://github.com/doitsujin/dxvk/files/5719830/Giants_dxgi.log)

Screenshot (note missing parts of the landscape):
![screenshot](https://user-images.githubusercontent.com/11149380/102694660-49e6bd80-4244-11eb-8bbd-4a279db15ee7.png)

**Comment by K0bin** [comment]
> Do you need an apitrace and in which setup (i.e., running through dgVoodoo or plain native DX7)? Maybe more test-subjects?

With dgVoodoo.

**Comment by GranMinigun** [comment]
After upgrading to Mesa 20.2.6 and Wine 6.0-rc3 all mentioned problems are gone. Guess the issue can be closed.
