### ISSUE TITLE
Assasin's Creed Valhalla gets stuck on splash screen

### ISSUE THREAD

**Issue by deton24** [doitsujin/dxvk#1815]
Looks like DXVK doesn't work in Valhalla. Currently, can't verify that on my end. It's just for your info so please speak out
https://www.gamingonlinux.com/forum/topic/4676/post_id=30671

DXVK in this game would be highly appreciated, since it requires Feature List 12_0 which means that it doesn't work on anything below GTX 9XX and Radeon GCN 2.0.

**Comment by K0bin** [comment]
Assassin's Creed Valhalla uses D3D12. DXVK doesn't implement D3D12.

**Comment by Joshua-Ashton** [comment]
We are aware it doesn't work rn, for DX12 go here:

https://github.com/HansKristian-Work/vkd3d-proton/
