### ISSUE TITLE
eFootball PES 2020 (996470): Rendering issues

### ISSUE THREAD

**Issue by ScarecrowDM** [doitsujin/dxvk#1816]
Hello. :) 
I'm seeing some artifacts and minor corruption, both Windows and linux.

[Artifacts](https://i.imgur.com/S3Iujyu.jpg)

[The target where the ball supposed to land is corrupted](https://i.imgur.com/LqRr9XT.jpg)

### Software information
eFootball PES 2020, DX11, 64bits, Steam (996470).
This game have a free version (eFootball PES 2020 LITE) in case apitrace is not enough.

### System information
- OS: Arch btw
- GPU: Vega 56;
- Driver: mesa 20.2.2 / mesa-git;
- Wine version: lutris-5.7-11 (seems to be current enough);
- DXVK version: 1.7.2 / master.

### Apitrace file(s)
[PES2020.trace](https://drive.google.com/file/d/1N4oovgdenPw35mUpgN7nNFymJPQ3FQux/view?usp=sharing)

Just a warning (since is not dxvk related): the game is kind of broken thanks to apitrace, mainly broken animations.
That said, i was able to replay the trace and reproduce the issue.

### Log files

[d3d11 and dxgi logs](https://drive.google.com/file/d/1NEnB-zfNecSWfaqJnmnxz_d1WrxSvABf/view?usp=sharing)

Thanks.
I'm on discord if you guys need anything else.
I know is friday, so feel free to ignore this until next month. :frog:

**Comment by doitsujin** [comment]
I'm actually aware of this problem and tried to debug it at some point. IIRC it was working fine on RADV at the time (but not on the Windows driver), don't have the slightest clue what's going on there.

**Comment by ScarecrowDM** [comment]
I don't know if it helps, but i was doing some bisect and commit 23691cd0ff6d9a2af6c84872cacf08e8cb5079c0 seems to make these issues worse.
Notice how in the commit before (ce33b60f9cdacea0014622beb0d8a20997c421ec), [the issue is way less severe](https://i.imgur.com/iSi0XXd.png) (just one strip on the left player and the player in the right is not even affected somehow).

**Comment by doitsujin** [comment]
I can't replay the trace, it just crashes halfway trough.

Anyway, probably a game bug. If anything, 23691cd should stop this kind of stuff from happening since we no longer accidentally read outside of vertex buffer ranges; if the game does some crazy out-of-bounds index buffer reads there's not much we can do without potentially murdering performance.

**Comment by vaslabs** [comment]
Hello. Have the same problem on pes 2021, any workarounds  u may know?

**Comment by doitsujin** [comment]
no.

**Comment by vaslabs** [comment]
thanks for the response. If you don't mind I'll dump some info here since I have a laptop that the game works perfectly (although on low graphics) while my RX 5700 xt has the issue

no issues:
```
warn:  Skipping Vulkan 1.0 adapter: llvmpipe (LLVM 11.0.0, 256 bits)
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  Intel(R) UHD Graphics (CML GT2):
info:    Driver: 20.3.3
info:    Vulkan: 1.2.145
info:    Memory Heap[0]: 
info:      Size: 23849 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0xf
info:  Process set as DPI aware
...
warn:  D3D11CoreCreateDevice: Adapter is not a DXVK adapter
info:  Game: PES2021.exe
info:  DXVK: v1.7.2-7-g6a10c81d-async
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to initialize OpenVR
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
....
warn:  Skipping Vulkan 1.0 adapter: llvmpipe (LLVM 11.0.0, 256 bits)
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  Device properties:
info:    Device name:     : Intel(R) UHD Graphics (CML GT2)
info:    Driver version   : 20.3.3
info:  Enabled device extensions:
info:    VK_EXT_4444_formats
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state
info:    VK_EXT_full_screen_exclusive
info:    VK_EXT_host_query_reset
info:    VK_EXT_robustness2
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_driver_properties
info:    VK_KHR_image_format_list
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_swapchain
```
(to be edited with info from other machine)

**Comment by doitsujin** [comment]
It's known to be an AMD-specific issue that happens on all drivers.

**Comment by vaslabs** [comment]
Yeah, I tried downgrading mesa-vulkan-drivers all the way to 20.0 and it was still happening although lines were thinner as suggested above . Oh well ... Thanks for the responses

**Comment by vaslabs** [comment]
I'm trying to test this by grabbing DLLs from the releases of GE proton and I've reached
(v1.6.1-63-ge7455b64)
The issue is minimal around (v1.7-63-gc4f37d39)  .
I have to stop testing though for today as Konami is banning for 24 hours if you restart too many times and I want to play a bit :)

I'll continue tomorrow maybe with a smarter way of backtracing this

For anyone that wants to do a workaround and make the game less annoying, this is what I did

- copy the GE release you are using (I've used 5.21....) and rename it (in compatibilitytool.vdf )
- get dlls from an old GE proton (e.g. 5.9-GE-1-MF-1) and find in dist/lib[64] dxvk .
- copy them across (separate lib64 from lib)
restart steam and choose the name you used in compatibilitytool.vdf


it doesn't seem to me an issue in dxvk (at least not a regression) although I haven't tested versions before 1.6.1 , but if I find some regression I'll post it here.

**Comment by tuxtergames** [comment]
> I'm trying to test this by grabbing DLLs from the releases of GE proton and I've reached
> (v1.6.1-63-ge7455b64)
> The issue is minimal around (v1.7-63-gc4f37d39) .
> I have to stop testing though for today as Konami is banning for 24 hours if you restart too many times and I want to play a bit :)
> 
> I'll continue tomorrow maybe with a smarter way of backtracing this
> 
> For anyone that wants to do a workaround and make the game less annoying, this is what I did
> 
> * copy the GE release you are using (I've used 5.21....) and rename it (in compatibilitytool.vdf )
> * get dlls from an old GE proton (e.g. 5.9-GE-1-MF-1) and find in dist/lib[64]/wine/dxvk .
> * copy them across (separate lib64 from lib) to their respective directories (delete the dxvk files first)
>   restart steam and choose the name you used in compatibilitytool.vdf
> 
> it doesn't seem to me an issue in dxvk (at least not a regression) although I haven't tested versions before 1.6.1 , but if I find some regression I'll post it here.

Tks for reply, I'll test it later, I give you a feeedback

**Comment by tuxtergames** [comment]
> I'm trying to test this by grabbing DLLs from the releases of GE proton and I've reached
> (v1.6.1-63-ge7455b64)
> The issue is minimal around (v1.7-63-gc4f37d39) .
> I have to stop testing though for today as Konami is banning for 24 hours if you restart too many times and I want to play a bit :)
> 
> I'll continue tomorrow maybe with a smarter way of backtracing this
> 
> For anyone that wants to do a workaround and make the game less annoying, this is what I did
> 
> * copy the GE release you are using (I've used 5.21....) and rename it (in compatibilitytool.vdf )
> * get dlls from an old GE proton (e.g. 5.9-GE-1-MF-1) and find in dist/lib[64]/wine/dxvk .
> * copy them across (separate lib64 from lib) to their respective directories (delete the dxvk files first)
>   restart steam and choose the name you used in compatibilitytool.vdf
> 
> it doesn't seem to me an issue in dxvk (at least not a regression) although I haven't tested versions before 1.6.1 , but if I find some regression I'll post it here.
this version its not  avaiable  for me, I try with "Proton-5.8-GE-1-MF" and follow your steps, now I see less glitch, but still there.

**Comment by Ahmed-E-86** [comment]
The graphical artifacts are almost unnoticeable after using DXVK 1.7

**Comment by tuxtergames** [comment]
> The graphical artifacts are almost unnoticeable after using DXVK 1.7

I got less using dxvk libs from 5.8xxx versions, this version still the same thing here

**Comment by pendingchaos** [comment]
After quickly checking a similar game (eFootball PES 2021 LITE), I think this is the same issue as https://github.com/doitsujin/dxvk/issues/1818 and https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/8835 should have fixed it

**Comment by Ahmed-E-86** [comment]
> After quickly checking a similar game (eFootball PES 2021 LITE), I think this is the same issue as #1818 and https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/8835 should have fixed it for RADV

I can confirm that is fixed. I have reported this issue at Mesa GitLab repo, and I was told that it is DXVK bug. Anyway, I am glad that it is fixed.

**Comment by vaslabs** [comment]
good, will update on my machine and test it asap

**Comment by vaslabs** [comment]
I can confirm as well, fixed for me too!

**Comment by tuxtergames** [comment]
> I can confirm as well, fixed for me too!

I need to use mesa git to get this fix? sorry my newbie question its my first AMD gpu on linux, I was always using nvdia....

**Comment by Ahmed-E-86** [comment]
> > I can confirm as well, fixed for me too!
> 
> I need to use mesa git to get this fix? sorry my newbie question its my first AMD gpu on linux, I was always using nvdia....

Yes. Which Linux distro do you use?

**Comment by tuxtergames** [comment]
> > > I can confirm as well, fixed for me too!
> > 
> > 
> > I need to use mesa git to get this fix? sorry my newbie question its my first AMD gpu on linux, I was always using nvdia....
> 
> Yes. Which Linux distro do you use?

I'm on Fedora kde 33

**Comment by vaslabs** [comment]
I'm on fedora 33 as well, you can get recent builds with this https://copr.fedorainfracloud.org/coprs/che/mesa/

**Comment by tuxtergames** [comment]
> I'm on fedora 33 as well, you can get recent builds with this https://copr.fedorainfracloud.org/coprs/che/mesa/

tks for reply, enabling this repo I got some conflicts and broken dependencies, its normal? sorry for asking here, I know its not a git mesa toppic.

**Comment by vaslabs** [comment]
If I recall correctly you can uninstall 2 libraries and it should work for the rest, one of them was mesa-filesystem . if you can't send me an email with your error logs (should be visible on my profile) and I can help you out

**Comment by tuxtergames** [comment]
> If I recall correctly you can uninstall 2 libraries and it should work for the rest, one of them was mesa-filesystem . if you can't, send me an email with your error logs (should be visible on my profile) and I can help you out (or post it here if people don't mind)
> edit:
> Look for i686 repos that maybe conflicting e.g.
> `sudo dnf remove mesa-filesystem.i686`
> 
> **another edit:**
> wait have you just done
> `dnf copr enable che/mesa`
> I got a lot of conflicts by just doing that, make sure you enable all the repos described in installation instructions
> then do
> `dnf update --refresh`
> and there should be no conflicts

@vaslabs tks for reply, now everything is fine, the problem that I was creating llvm repo or mesa-libdrm not both, I was thinking that was two diferents drivers, tks so much!
now lets try to play football again without glitchs, tks again....

**Comment by vaslabs** [comment]
I guess this issue can be closed now @doitsujin , thanks for having us here :)
