### ISSUE TITLE
Dead Cells bugged textures

### ISSUE THREAD

**Issue by QuImUfu** [doitsujin/dxvk#1818]
Dead Cells with DX11 renders bugged on DXVK, works fine with vanilla wine.  
![deadcells_bugged](https://user-images.githubusercontent.com/9885301/99236830-fc67d280-27f7-11eb-939e-88b5e29fbe0b.png)  

### Software information
Dead Cells (over Wine)

### System information
- GPU: AMD Radeon HD 7850
- Driver: AMDVLK 2020.Q4.2 and Mesa 20.3.0-devel (git-fb1793b 2020-11-08 groovy-oibaf-ppa) (ACO)
- Wine version: wine-5.20 (Staging)
- DXVK version: v1.7.2

### Apitrace file(s)
- https://dl.dropbox.com/s/attupmraruya2xs/deadcells.trace.tar.xz

### Log files
- d3d11.log:
[deadcells_d3d11.log](https://github.com/doitsujin/dxvk/files/5545361/deadcells_d3d11.log)
- dxgi.log:
[deadcells_dxgi.log](https://github.com/doitsujin/dxvk/files/5545368/deadcells_dxgi.log)

**Comment by doitsujin** [comment]
Seems like a driver bug with first-gen GCN? The trace replays fine on my Polaris.

**Comment by QuImUfu** [comment]
Seems to happen with navi as well:  
https://gitlab.freedesktop.org/mesa/mesa/-/issues/3796

**Comment by QuImUfu** [comment]
On my Polaris card (RX460) the game/apitrace crashes (page fault).  
backtrace:
```
=>0 0x00000000 (0x0031f3b8)
  1 0xf76a811b in dxgi (+0x6811a) (0x0031f3e8)
  2 0x012ff4d1 in d3d11 (+0x7f4d0) (0x0031f458)
  3 0x01328a52 in d3d11 (+0xa8a51) (0x0031f8e8)
  4 0x01329ab9 in d3d11 (+0xa9ab8) (0x0031fa58)
  5 0x012b903c D3D11CoreCreateDevice+0xa7b() in d3d11 (0x0031fc58)
  6 0x012b952d D3D11CoreCreateDevice+0xf6c() in d3d11 (0x0031fd20)
  7 0x012b9bc3 D3D11CoreCreateDevice+0x1602() in d3d11 (0x0031fdc8)
  8 0x004b7ea3 retrace::Retracer::retrace+0x1b2(call=0xd455f0) in d3dretrace (0x0031fdfc)
  9 0x004badca retrace::retraceCall+0x19(call=0xd455f0) in d3dretrace (0x0031fe0c)
  10 0x004baf57 retrace::RelayRunner::runRace+0x56() in d3dretrace (0x0031fe48)
  11 0xde5ccaad (0x0031fe48)
  12 0x004bc10c main+0xb6b(argc=0x2, argv=0xd17d18) in d3dretrace (0x0031fee0)
  13 0x005a08f6 __scrt_common_main_seh+0xf9() in d3dretrace (0x0031ff28)
  14 0x7b62ce9c EntryPoint+0xffffffff() in kernel32 (0x0031ff5c)
  15 0x7bc59c37 EntryPoint+0xffffffff() in ntdll (0x0031ff5c)
  16 0x7bc59e70 EntryPoint+0xffffffff() in ntdll (0x0031ffec)
```

**Comment by doitsujin** [comment]
Stack trace is not very useful, please post DXVK logs instead. If you can't even create a device then chances are that Vulkan isn't working on your setup.

**Comment by QuImUfu** [comment]
It was a weird setup issue with leftover icd files containing old Vulkan version values, causing this issue on any dxvk version >1.5.1.  
Sorry.  
The apitace and the game work fine on a Polaris card.

**Comment by liberodark** [comment]
Have same issue with mesa 20.3.1 only + DXVK 1.7.3.

**Comment by pendingchaos** [comment]
The Mesa issue (https://gitlab.freedesktop.org/mesa/mesa/-/issues/3796) has been closed by https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/8835

**Comment by pendingchaos** [comment]
It appears the very latest AMDVLK (2021.Q1.2 and newer, I think) has a "PadVertexBuffers" option to workaround this issue: https://github.com/GPUOpen-Drivers/xgl/blob/88a4f8c5657824f93790eefe3c9e078806c2a768/icd/settings/settings_xgl.json#L512-L523
