### ISSUE TITLE
Test Drive Unlimited 2 - Windows 10 Crash

### ISSUE THREAD

**Issue by crowbar01** [doitsujin/dxvk#1819]
Currently running an nVidia RTX series card, with DXVK being the only way to reliably play this game on the RTX series of cards, that said, I have been getting random crashes with the latest version. Log files attached.
[TestDrive2_d3d9.log](https://github.com/doitsujin/dxvk/files/5546057/TestDrive2_d3d9.log)

### Software information
Test Drive Unlimited 2 - 1440p Resolution, Max Graphical Settings

### System information
- GPU: Geforce RTX 2080Ti
- Driver: 457.30
- DXVK version: 1.7.2

**Comment by crowbar01** [comment]
Second, different crash log.
[TestDrive2_d3d9.log](https://github.com/doitsujin/dxvk/files/5546081/TestDrive2_d3d9.log)

**Comment by mozo78** [comment]
Just use Linux, the game runs perfectly well.
https://youtu.be/N1xExhJzPkI
https://youtu.be/nY4w9IiI25s

**Comment by K0bin** [comment]
It's running out of address space. That's a known issue and there isn't much that can be done on the DXVK side.
More information here: #1318 

You could try using a patcher to set the LAA flag of the executable. https://ntcore.com/?page_id=371

**Comment by doitsujin** [comment]
Closing as we're basically already discussing that at #1318.
