### ISSUE TITLE
The Last Blade 2 runs choppy

### ISSUE THREAD

**Issue by ngoquang2708** [doitsujin/dxvk#1822]
On DXVK, the intro and the gameplay run very choppy while CPU and GPU are not utilized much.
Game runs fine on WineD3D.

### Software information
The Last Blade 2
Steam link: https://store.steampowered.com/app/702110/THE_LAST_BLADE_2/

### System information
- GPU: NVIDIA Geforce 1650
- Driver: 455.45.1
- Wine version: Proton 5.13-2
- DXVK version: v1.7.2-4-g280cd4b4

### Apitrace file(s)
- https://drive.google.com/drive/folders/1htZw8qHut7a_hfT5Eg6Enx8rScModKrz?usp=sharing

### Log files
- d3d9.log: [LastBlade2App_d3d9.log](https://github.com/doitsujin/dxvk/files/5567675/LastBlade2App_d3d9.log)

**Comment by K0bin** [comment]
Can you make an apitrace that actually shows gameplay? Yours is over after 5 seconds and you just quit from the menu.

**Comment by ngoquang2708** [comment]
I have added 2 more apitrace files with longer gameplay time in the Drive folder. Please check it out.

**Comment by ngoquang2708** [comment]
Game runs normally with current Proton Experimental 6.3-20210823.

**Comment by K0bin** [comment]
Nice.
