### ISSUE TITLE
Trine 4 Melody of Mystery Artefacts

### ISSUE THREAD

**Issue by mozo78** [doitsujin/dxvk#1826]
There are graphical artefacts in the latest version of the game with the new DLC Melody of Mystery. I can't provide an apitrace for the game miserably crashes with apitrce libraries both on Linux and Windows:
https://i.imgur.com/X5ZSmEo.png
https://i.imgur.com/bpTTRpq.png

The game doesn't run without DXVK so I can't see if the problems are present with WineD3D. The graphical problems occurs in areas with glowing objects:
https://i.imgur.com/SS7Up9Z.png

There are problems ingame too where are clouds, lanterns, etc.

I tried with severel older DXVK versions but the problem persists. 

Here you are the Wine log:
https://pastebin.com/X6785MuJ

### Software information
Trine 4: The Nightmare Prince - Melody of Mystery

### System information
- GPU: NVIDIA GTX 1080Ti
- Driver: 455.38
- Wine version: 5.21
- DXVK version: 1.7.2

### Log files
- d3d11.log:
[trine4_d3d11.log](https://github.com/doitsujin/dxvk/files/5573900/trine4_d3d11.log)

- dxgi.log:
[trine4_dxgi.log](https://github.com/doitsujin/dxvk/files/5573902/trine4_dxgi.log)

**Comment by doitsujin** [comment]
Does `d3d11.enableRtOutputNanFixup = True` help?

**Comment by mozo78** [comment]
In dxvk.conf, right?
Unfortunately not.

**Comment by doitsujin** [comment]
Just tested this on Windows, works fine there. Probably not a DXVK bug.

**Comment by mozo78** [comment]
So I have to file a Wine bug? But the game doesn't run with Wine only, it'll be funny :)

**Comment by doitsujin** [comment]
Not really sure what's going on yet. The game seems to be doing all sorts of broken stuff so we may just need to work around a few things. You might also want to test on Windows on your end to see if it really works fine.

**Comment by mozo78** [comment]
I never used any game on Windows with DXVK and I don't feel confident. Actually I not use Windows at all. This installation from the screenshot is only for apitraces :)
I'll try and will inform you what's going on, thank you very much!

**Comment by doitsujin** [comment]
To test on Windows, just copy the 64-bit d3d11.dll and dxgi.dll into the game's installation directory, should work fine.

Anyway, game *seems* to be working fine with the proprietary AMD driver even on Linux, but with RADV I have the exact same artifacts. Gonna have to compare the two to see what's going on.

**Comment by mozo78** [comment]
Thank you, I'll try with NVIDIA on Windows soon.

**Comment by mozo78** [comment]
I can confirm - there are the same artefacts on Windows.

**Comment by doitsujin** [comment]
Turns out that this is an extremely annoying problem with numerical precision *somewhere*, and very hard to debug. Only happens on RADV+ACO on my end, the other AMD drivers as well my RTX 2060 are fine.

**Comment by mozo78** [comment]
Thank you for your efforts. We'll live with it :)

**Comment by doitsujin** [comment]
Should be fixed in latest master.

**Comment by mozo78** [comment]
Yes it's perfect now. Thank you very much!
https://i.imgur.com/fOvCSuU.png
