### ISSUE TITLE
Shadow of War hangs on Creating new state cache file

### ISSUE THREAD

**Issue by elogicuk** [doitsujin/dxvk#1827]
First of all: Thank you very much for this awesome project. I've been using it for running many games successfully. However I have one game, that makes problems.

Game: Middle Earth: Shadow of War

Lutris
Wine 5.21
Dxvk 1.7.2
GeForce RTX 2060 SUPER 
Drivers: 455.38

Game fails to start, gets to this stage in the lutris logs and does nothing

warn:  DXVK: No state cache file found
warn:  DXVK: Creating new state cache file
info:  DXVK: Using 10 compiler threads

i left it for 2 hours and still nothing.

[ShadowOfWar_d3d11.log](https://github.com/doitsujin/dxvk/files/5577518/ShadowOfWar_d3d11.log)
[ShadowOfWar_dxgi.log](https://github.com/doitsujin/dxvk/files/5577519/ShadowOfWar_dxgi.log)
[ShadowOfWar.dxvk-cache.zip](https://github.com/doitsujin/dxvk/files/5577520/ShadowOfWar.dxvk-cache.zip)

**Comment by doitsujin** [comment]
It probably hangs *after* creating a new cache file, i.e. immediately after device creation.

Please post the full wine log, I see no evidence that this is a DXVK problem.

**Comment by Blisto91** [comment]
@elogicuk Friendly ping. Could you retest if this is still and issue with newer dxvk, driver, wine etc? 🙂
