### ISSUE TITLE
[D3D9] Blood Rayne

### ISSUE THREAD

**Issue by ByCybernetik** [doitsujin/dxvk#1828]
sags in places fps

### Software information
Blood Rayne, high settings.

### System information
- GPU: Radeon RX 590
- Driver: RADV ACO
- Wine version: Proton 5.0-10
- DXVK version: d3d8to9 + dxvk Master

### Apitrace file(s)
https://drive.google.com/file/d/13wN65c383z6tqdtn-y2gY75HNlfKgEhY/view?usp=sharing

### Log files
- d3d9.log: [rayne1_d3d9.log](https://github.com/doitsujin/dxvk/files/5577522/rayne1_d3d9.log)

**Comment by doitsujin** [comment]
And what is the problem exactly?

**Comment by ByCybernetik** [comment]
If you run the game through WineD3D, D3D Native, dgVoodoo + DXVK, then the performance will be fine.

**Comment by ByCybernetik** [comment]
Poor performance is only seen through dxvk (d3d9) and Gallium Nine.

**Comment by jrugia** [comment]
@ByCybernetik 

Is this version the new "Terminal Cut" release, you're referring to? Also can you please try it with dgVoodoo+DXVK? 

If you can share a few screenshots and the savegame I could test it out.

**Comment by ByCybernetik** [comment]
@jrugia Via dgVoodoo(d3d8) + dxvk(d3d11) works well.

**Comment by Blisto91** [comment]
Tried testing this. I was not able to get this running with `d3d8to9` as it just crashes when try to launch with it.
But with `dgVoodoo` + `dxvk` it seems to run fine yes. Better than native d3d8 + `WINED3D`.

So unless me not being able to get `d3d8to9` to work then i don't think there is a issue here anymore.

**Comment by Blisto91** [comment]
anti aliasing crash has been fixed in 1.10.2

**Comment by Blisto91** [comment]
This should be fixed by https://github.com/doitsujin/dxvk/pull/3765
@ByCybernetik If you are still around then you are welcome to verify.

**Comment by ByCybernetik** [comment]
> Это должно быть исправлено в [ #3765. ](https://github.com/doitsujin/dxvk/pull/3765) @ByCybernetikЕсли вы все еще здесь, пожалуйста, проверьте.

It's working fine now.
