### ISSUE TITLE
Screen Flickering

### ISSUE THREAD

**Issue by Elvindmx** [doitsujin/dxvk#1829]
Hi all, hoping you all find well

I just recently installed the DXVK on my Assassins Creed Origins game, and it was doing really great the first couple of minuts, but then after i restarted the PC it began to do screen flickering everytime i play the game. I have changed a lot of settings and yet the problem persist. Its doing the same also in AC Odyssey. Any help about how to fix the issue? i do really want to play Origins and since the game has serious stuttering issues i want to get the DVXK working. This are my specs:

Windows 10
RX Vega 8GB
Ryzen 5 2600X
16GB Dal Channel
250GB SSD
Radeon Adrenaline Software 20.11.1

Regards

DMX

**Comment by doitsujin** [comment]
Sounds like a driver problem to me.

**Comment by shoummashams** [comment]
Same thing happening for me on Radeon Adrenalin 20.9.1 with a 5600X and RX580.

**Comment by doitsujin** [comment]
What do you guys mean by screen flickering exactly anyway?

Then again, the game works perfectly fine on RADV and Nvidia, so yeah, probably not our bug.

**Comment by shoummashams** [comment]
Both of my monitors will just flicker non-stop (flash black and then show the screen) when the Odyssey window is focussed on. Happens a bit faster than every second. If I alt-tab away, the screens are fine.

**Comment by Ryusennin** [comment]
I have a setup similar to OP, and both games run fine on Win10 (AMD driver 20.11.2).

Check the following points:
- use fullscreen instead of borderless
- force the frame limiter to 60
- enable vsync

Also, Vulkan on Win10 only seems to support 60 Hz (Win7 will accept any refresh rate).

**Comment by Elvindmx** [comment]
Hi

I just fixed the flickering by changing the V-Sync from adaptative to ON(never thought about that).

Thanks guys for the support.

Regards

**Comment by doitsujin** [comment]
Are any of you using variable refresh rate (i.e. FreeSync) by any chance?

Wonder if that's one of the "known issues" in their recent driver releases.

**Comment by shoummashams** [comment]
Nope, fixed refresh rate here. I'm now on a 5700XT on 20.11.2 and in fullscreen, 60Hz, VSync on. The issue seems to have become one of more inconsistent flickering which shows previous screens (e.g. flickers and shows the loading screen when in the menu) and is mostly limited to the game the monitor is on, with my 2nd monitor flickering much more intermittently. Happens with both 1.7.2 and 1.7.3

**Comment by Blisto91** [comment]
@Elvindmx @shoummashams Friendly ping. If you are still around could you retest this with latest drivers and dxvk?

**Comment by shoummashams** [comment]
> @Elvindmx @shoummashams Friendly ping. If you are still around could you retest this with latest drivers and dxvk?

Will do so in about a week once I'm back with my computer

**Comment by Blisto91** [comment]
@shoummashams @Elvindmx Friendly double ping :eyes:  :grin:

**Comment by shoummashams** [comment]
@Blisto91 sorry, totally forgot and I was away again when you sent the double ping. Just tested on my 5700XT on 22.5.1 with the latest DXVK, and the screen flickering is no longer present! Performance improvement isn't as high as others have claimed but still better so all good.

**Comment by Blisto91** [comment]
Thanks for checking!
