### ISSUE TITLE
[D3D9] Oblivion: Poor FPS while Anti-Aliasing Is Enabled

### ISSUE THREAD

**Issue by jamsz** [doitsujin/dxvk#1830]
With hardware AA off: runs average with WineD3D, near perfectly with both Gallium and D9VK
**With hardware AA on:** runs not-so-good with WineD3D, near perfectly with Gallium, **poor with D9VK**

### Software information
The Elder Scrolls IV: Oblivion Deluxe from GOG, 8x AA enabled

### System information
- GPU: R9 380 4GB
- Driver: mesa 20.3.0-rc2
- Wine version: staging-5.21 w/ fsync patch
- DXVK version: latest master (same problem with 1.7.2)

### Apitrace file
https://mega.nz/file/hrgm2LwD#cmkeE33OYI_ogITAox6Cu-A1vnwExPloXAnnj7JJ8zI
(could not reproduce in WineD3D so traced with D9VK)

### Log files
- d3d9.log:
[Oblivion_d3d9.log](https://github.com/doitsujin/dxvk/files/5578844/Oblivion_d3d9.log)

**Comment by doitsujin** [comment]
MSAA perf is always rather bad on DXVK, but that doesn't really seem like something we can fix on our end.

**Comment by jamsz** [comment]
> MSAA perf is always rather bad on DXVK with RADV, but that doesn't really seem like something we can fix on our end.

Ah thanks. It's running well with AMDVLK now. Closing the issue.
