### ISSUE TITLE
Skyrim LE gamepad dont work with DXVK?

### ISSUE THREAD

**Issue by POUnavy11** [doitsujin/dxvk#1837]
Hello everyone my 5500xt kind of struggled in 4k ultra settings, now it runs it just fine in 50fps with VULKAN 32 installed. I watch it in MSI AB to test temps and such looking good. But my main concern is that once i install the 32 versions in Fallout NV and also Skyrim LE, the gamepad stops working any help? Do i need to use xpadder? dont want to but i will.

**Comment by POUnavy11** [comment]
also getting a few crashes in SK LE?

**Comment by jrugia** [comment]
DXVK doesn't touch the input system, it may be that these games are installing some addiotional dll's which interfere with the gamepad.

Skyrim LE is 32bit, it may be that this is hitting the 4gb virtual memory limit and crashing. Have you enabled Large Address Aware?

**Comment by Squall-Leonhart** [comment]
Skyrim LE's input support is a little fucky in that Graphics wrappers and injectors CAN break gamepad support, 

However, this is only the case for the basic DI support, if you mod the games config file to enable xinput, you should have no issues as long as xpadder is simulating an xbox controller.

**Comment by Blisto91** [comment]
@POUnavy11 Is this still a issue? Was this on Windows or Linux

**Comment by K0bin** [comment]
DXVK does not interact with input at all.
