### ISSUE TITLE
DirectX Wrapper

### ISSUE THREAD

**Issue by aerayth** [doitsujin/dxvk#1839]
For old games, has anyone thought of adding it into DXVK where it converts API calls to DirectX9? DirectX9 is very similar to older versions of DirectX. I've worked with DIrectX6-7-8 for over 10 years and there are wrappers already available that can be used. The reason for doing this would mainly to have better compatibility with older DirectX games.
https://github.com/narzoul/DDrawCompat
https://github.com/crosire/d3d8to9

**Comment by K0bin** [comment]
WineD3D works well enough for those games. No one is particularly interested in reimplementing DirectDraw and stuff.

**Comment by doitsujin** [comment]
There's nothing stopping you from using d3d8to9 in combination with DXVK. There's no reason for us to pull third-party projects into DXVK.

**Comment by aerayth** [comment]
@doitsujin these wrappers do not work in Vulkan, the API does not work when used alone. Anyway it is fine just was suggesting.

**Comment by doitsujin** [comment]
d3d8to9 does work, not sure what you're on about. There may be bugs, but it does run.

Not sure about the DirectDraw thing but there's really no good reason not to just use wined3d for that.
