### ISSUE TITLE
[D9VK] Warlock: Master of the Arcane crashes on loading

### ISSUE THREAD

**Issue by GloriousEggroll** [doitsujin/dxvk#1840]
Details/description:
This game used to work in 19.x versions of mesa. Seems it no longer works. Tested on both RX 580 and Navi 5600M. 
Works on Nvidia just fine. 
Works on wined3d just fine.
Crashed at around 76% loading bar with mesa
Crashed after pressing 'New Game' at the main menu with amdvlk

Reproduce:
MESA:
Open the game. click new game, click start -- expect crash around 76% loading bar

AMDVLK:
Open the game. click new game -- expect crash before create new game screen.

### Software information
Warlock: Masters of the Arcane
Steam Play/Proton (any version)
Fedora 33

### System information
- GPU: RX 580, 5600M (tested both)
- Driver: Mesa-git, Mesa-20.2.3
- Wine version: 5.22 (also tried previous versions)
- DXVK version: git (also tried previous versions)

### Apitrace file(s)
wined3d Apitrace: 
https://drive.google.com/file/d/1iMvyz1Xc1lFzNr2bX9mkxCILqrB61Rrv/view?usp=sharing

d9vk Apitrace:
https://drive.google.com/file/d/1iGbIyagxg_kr2SqkgfTT_ZKtgWWYugiL/view?usp=sharing

### Log files
Crash wine/proton log with +wined3d,+d3d9:
[steam-203630.log](https://github.com/doitsujin/dxvk/files/5618858/steam-203630.log)

Crash d3d9 log:
[Game_d3d9.log](https://github.com/doitsujin/dxvk/files/5618920/Game_d3d9.log)

**Comment by K0bin** [comment]
Both apitraces replay fine with DXVK, so unfortunately I can't debug this without the game itself.

**Comment by GloriousEggroll** [comment]
> Both apitraces replay fine with DXVK, so unfortunately I can't debug this without the game itself.

Josh should have the game, I gifted it to him to fix a previous bug in d9vk

**Comment by GloriousEggroll** [comment]
Just tested, seems something has fixed it since the bug was opened. closing
