### ISSUE TITLE
[D9VK] Gothic 3 with CP 1.75 slower performance than with CP 1.74

### ISSUE THREAD

**Issue by TomadeTT** [doitsujin/dxvk#1841]
dear DXVK/D3D9 developers.

I tried both Versions (1.75 and 1.74). And Version 1.75 seems to perform very slow (also in comparison to playing under windows). I noticed that the gpu usage with CP 1.75 is much lower than with CP 1.74 (please see HUD).I can confirm that the problem still persist when using newer Versions of Mesa and Linux Kernel.

This figure is about Version 1.74 (FPS=good)
![G3_CP_1_74_good_performance](https://user-images.githubusercontent.com/75376330/100884123-65ff0680-34b1-11eb-9994-af3a97226455.png)
This figure is about Version 1.75 (FPS=not good)
![G3_CP_1_75_slow_performance](https://user-images.githubusercontent.com/75376330/100884124-66979d00-34b1-11eb-8d6f-5e67b9957277.jpg)

[Gothic3_d3d9_Gothic3_CP_1_75.log](https://github.com/doitsujin/dxvk/files/5629782/Gothic3_d3d9_Gothic3_CP_1_75.log)
[Gothic3_d3d9_Gothic3_CP_1_74.log](https://github.com/doitsujin/dxvk/files/5629787/Gothic3_d3d9_Gothic3_CP_1_74.log)

### Software information
Gothic 3 GOG german version. I made a video with the comparison. with: DXVK_HUD=full 
https://youtu.be/A1to5r6acHs 

### System information
- GPU: Radeon 580X
- Driver: MESA 18.3.6
- Wine version: lutris-5.7-11-x86_64
- DXVK version: 1.7.2-5-g13052d49

### API Traces for 1.74 and 1.75 (D3D9)
http://www.ib-guder.de/Traces_Gothic3_CP1_74_CP1_75.tar.xz

**Comment by doitsujin** [comment]
Can you please provide an apitrace?

**Comment by TomadeTT** [comment]
thank you for your reply. I'm working on it. I have to get a little into it to understand what I do (I still don't know how to apitrace gothic3 which uses d3d9).

**Comment by SveSop** [comment]
@TomadeTT 
From what some googling got me to conclude, is that this game has "horrible" performance with CP 1.75 even on Windows machines. I am not saying that DXVK cant fix that, and make it faster than windows, but chances are that.. well.. it is what it is for such a old game.

Few snippits kinda suggested "this old game is single-thread only", and chances are it may actually be faster on older "fewer-but-more-HZ-cores" machines vs "newer-with-many-cores" machines.

[https://www.pcgamingwiki.com/wiki/Gothic_3](https://www.pcgamingwiki.com/wiki/Gothic_3)

>  If you experience problems try Community Patch 1.73 or Community Patch 1.74 instead.[4]

**Comment by TomadeTT** [comment]
@doitsujin 
Traces: http://www.ib-guder.de/Traces_Gothic3_CP1_74_CP1_75.tar.xz

@SveSop: Perhaps there is a still a margin for improvement and perhaps its also a benefit for other games/applications. I felt that it is worth to open an issue. Kind regards. Tom

**Comment by LordJBeckman** [comment]
Using D3D9 which indeed is single threaded but unsure why 1.75 would be slower, towards the end of the whole debacle leading to the community patching up the game they resolved numerous memory leaks and performed a number of optimizations plus a few new features were provided through I think it was Spellbound who were developing Arcania at the time.
(That entire development after Piranha split from Jowood is a bit of a mess and a lengthy process of developments and updates as the community got involved in keeping the game updates going.)

What's in the changelog here.
https://upload.worldofplayers.de/files8/Changelog_en.txt

A number of stuff, resource cache changes, multi-threading (Dual core I presume.) maybe something in the ini file that could be tinkered with.

FXAA, higher shadow quality (That's a performance decrease.) and a big number of other additions.

**Comment by TomadeTT** [comment]
@LordJBeckman Hello. I tried reducing all options to minimum in 1.75. The GPU usage decreases (from 10...30 % to 3...5 %) but the framerate does not increase. One more fact: CPU usage stays below 50% all time when playing (only one core is used). Have a good weekend.

**Comment by TomadeTT** [comment]
one last comment: I edited the ge3.ini Timer Settings... and BIG surprise: GPU usage increases, FPS increases ... now I look if there are some sideeffects.

;Timer.ThreadSafe - false=off, true=default, use thread safe timer to avoid fast day/night cycles or slowdown issues
Timer.ThreadSafe=false

**Comment by TomadeTT** [comment]
no issue of dxvk, but of the game/patch 1.75 itself. Changing "Timer.ThreadSafe=true" to "Timer.ThreadSafe=false" solves the problem.
