### ISSUE TITLE
Performance tanks in Mass Effect when looking at occluded part of the level

### ISSUE THREAD

**Issue by mirh** [doitsujin/dxvk#1845]
So, I like to benchmark the game in the comm room on the Normandy, since I found out (once the door closes) that I can get the highest framerates of all the game there. 
I just walk against the FTL comm link at the bottom of it, and then stare at the empty wall. 
In D3D9 I get around 420 fps, while dxvk gives me around 350, not that bad I thought. 

I just figured out though, that if I just rotate the camera to "face the rest of the ship", while D3D9 only slows down to about 360fps, dxvk gets almost *3* times slower at 130. 

### Software information
Mass Effect 1, max in-game settings, no mods. 

### System information
- GPU: Radeon R9 290
- Driver: 20.11.2
- Wine version: Windows 7 SP1
- DXVK version: 1.7.3

### Apitrace file(s)
- [Apitrace](https://mega.nz/file/BN4zVYQI#t720f9B95CccQKNstiqRRlM8CfGdHCdWrNWIFsZ1yyk)

### Log files
- [d3d9.log](https://github.com/doitsujin/dxvk/files/5649612/MassEffect_d3d9.log)

**Comment by doitsujin** [comment]
Are you CPU-bound or GPU-bound? That kind of info is **extremely** important when dealing with performance issues.

Also, be aware that DXVK is known not to perform well on first- and second-gen GCN cards due to some limitations around how they handle depth buffers.

**Comment by mirh** [comment]
I think it's actually both in the apitrace you can find. 
I lowered the resolution to 640x480, and D3D9 wasn't actually affected at all (even though I could have swore gpu usage at 97% meant it was gpu-bound). 

But then this had a big effect on DXVK. When I'm staring at the wall I gain those 70fps that I was missing earlier. 
While I'm staring behind my shoulders, I'm still getting the same ~130 fps.

**Comment by K0bin** [comment]
I can confirm that it's slower when looking at the wall that has geometry behind it and the hit is much larger than with Windows D3D9. Windows D3D9 pretty much runs the same and DXVK drops from 550 fps to 430 for me.

Fully CPU bound of course. I dont really know why though. There's nothing that obviously sticks out.

**Comment by K0bin** [comment]
Can you try this?

[d3d9.zip](https://github.com/doitsujin/dxvk/files/5691568/d3d9.zip)

**Comment by mirh** [comment]
This is enormously better. Performance hit is around 20% now, which is *more or less* the same ballpark of the one you get with native D3D9.

**Comment by K0bin** [comment]
How about this one: 
[d3d9.zip](https://github.com/doitsujin/dxvk/files/5698779/d3d9.zip)

Does it yield similar results to yesterdays build?

**Comment by mirh** [comment]
Yes.

**Comment by unic0rn** [comment]
A8-7600, mesa 20.2.3, comm room scenario:
dxvk-master: 60fps (vsync - 88% gpu utilization) vs slightly above 48fps
pull request #1857 : 60fps (vsync - 88% gpu utilization) vs slightly below 48fps

The difference is perhaps 0,5fps or even less, but it does seem to perform worse. Not sure how random it is, rotating the camera seems to change that number a lot, but when looking straight at the door dxvk-master reports 31 render passes, #1857 32.

So no performance gain on radv.

**Comment by K0bin** [comment]
A performance drop is expected because the game is simply doing a lot more when you look at that other wall.

It was just a special case for mirh where the cpu didnt submit work early enough so it would work for the gpu.

**Comment by unic0rn** [comment]
I did expect a performance drop, I was just thinking it's some generic performance improvement for that case, and the way you explain it, I guess it's related to way higher framerates he's having. Nevermind, don't mind me, I was just reporting 0,5fps drop in my case, which is acceptable.

**Comment by K0bin** [comment]
[d3d9.zip](https://github.com/doitsujin/dxvk/files/5710304/d3d9.zip)

How about this one? Still improved? That should hopefully not cause any performance regressions on other systems.

**Comment by mirh** [comment]
Yup. I also noticed a very marked 40% improvement in my "worst case spot" on the citadel.

**Comment by iWeaker4you** [comment]
> [d3d9.zip](https://github.com/doitsujin/dxvk/files/5710304/d3d9.zip)
> 
> How about this one? Still improved? That should hopefully not cause any performance regressions on other systems.

Thank you, its fixed FFXIII-2 Regression

**Comment by K0bin** [comment]
Fixed.

**Comment by mirh** [comment]
Cool, now, how about tackling performance being "in general" slower?
On my desktop the difference is about 15-20% as I mentioned in the opening, but on my 950M I can get north of 50% faster framerate with native d3d9 (in fact, with a slightly different "not really much to render" camera angle from the same scenario above I can even near twice as much fps)

**Comment by K0bin** [comment]
There's nothing obviously wrong with DXVK that we could just optimize.
Is performance an issue anyway? As mentioned, on my system it runs at 500 fps with DXVK.
Sure it would be nice to reach the 600 fps that Nvidias D3D9 manages but no one's gonna notice the difference.

**Comment by mirh** [comment]
I'm not talking about cpu limited situations here though (and in fact these last numbers were taken from W10, which would make even an nvidia suck there). 
And yes, it's kind of a big deal when it can make the difference between "playable" and "unplayable" (I have a dedicated gpu in my laptop thankfully, so here if any we are talking about "bearable" vs "great", but still)

**Comment by K0bin** [comment]
What kinds of numbers are you getting anyway where this is a problem and what settings and resolution?

Mass Effect is pretty much **ALWAYS** CPU limited on my system.

**Comment by mirh** [comment]
Increase the resolution then?
I'm using a 6500U+950M laptop now personally, so 1080p is already enough to run around the 60fps mark. 

In the most gpu-limited scene I can find score is 52 fps vs 35. 
In the most stupid one which is the one in the apitrace (which anyway still isn't cpu-limited without having a big ass gpu) 85 vs 51. Which become 120 vs 60 when I stare to the ceiling. 

That doesn't sound really trifles.

**Comment by mirh** [comment]
I feel like the d3d9 improvements of the last week turned out to improve some spots by 10-20%, so I did some extra looking around..
Would you be up taking another issue, if it's for a 30% hit over native d3d9 in the main menu (which IIRC has a hidden 3D scene rendered behind)?

**Comment by doitsujin** [comment]
If it's still that ancient Maxwell GPU then I don't think there's any point whatsoever in looking into this, we can't make anything pre-Turing go fast, and in general we simply cannot expect to match Nvidia's D3D9 performance when GPU-bound considering how much emulation we have to do for features that native simply solves with hardware.

**Comment by mirh** [comment]
Wops, sorry, yes. No, that was with a 2080 in 5K now.

> when GPU-bound considering how much emulation we have to do for features that native simply solves with hardware

Wasn't Vulkan supposed to be more low level? (like, I get that floating rules themselves might be different, but I thought these cases were more the exception than the average)
