### ISSUE TITLE
[d3d9] Mercenaries 2: World in Flames → crashes after the first logo

### ISSUE THREAD

**Issue by NerosTie** [doitsujin/dxvk#1846]
Launch the game, there is the EA logo then it crashes. It doesn't crash with WINED3D.

### System information
- GPU: Nvidia Geforce 730M
- Driver: 455.45.01
- Wine version: 5.22
- DXVK version: 1.7.3

### Apitrace file(s)
https://mega.nz/file/nuhzCSjA#o-DcimafkI7-zBJbqcZsZrRsjrk0lNuTL6iCe9PopwQ

### Log files
[mercenaries-2-dxvk-2.log](https://github.com/doitsujin/dxvk/files/5660209/mercenaries-2-dxvk-2.log)
[mercenaries-2-dxvk.log](https://github.com/doitsujin/dxvk/files/5660210/mercenaries-2-dxvk.log)

**Comment by nipnipj** [comment]
I also experience crashes when usin version 1.7.3. on directx11 games, everything work fine reverting to 1.7.2.

**Comment by doitsujin** [comment]
this is a d3d9 game, not d3d11.

**Comment by K0bin** [comment]
The apitrace replays fine with DXVK. Can you make another one with DXVK installed so I can try to compare the traces?

**Comment by NerosTie** [comment]
https://mega.nz/file/f6BFkADY#jjR2g2RveCfxHxjJffTm42Qm1J-dFNVYstzhpVy9HTg

After several launches to test to make this trace, it doesn't necessarily crash after the first logo. But in every cases, I can't get past the main menu. Something else, sometimes the game has sound, sometimes not. I don't have this issue with WINED3D. I hope this trace with DXVK will help.

**Comment by K0bin** [comment]
The demo goes ingame with DXVK but crashes inside the graphics driver after a bit. I have no idea whats going on to be honest.

**Comment by K0bin** [comment]
Actually, it seems stable with `d3d9.evictManagedOnUnlock = True`. So it might be just another case of #1318.

**Comment by NerosTie** [comment]
Unfortunately, it still crashes with `d3d9.evictManagedOnUnlock = True`

**Comment by K0bin** [comment]
I can't reproduce it then.

**Comment by NerosTie** [comment]
Tested with DXVK 1.9.1 / Wine-staging 6.13 and I don't experience this crash anymore. Can be closed!

**Comment by Ghostassassin1p** [comment]
the game works perfectly for me but after 30m of gameplay the game crash i ve updated everything i ve got on this desktop but what ever i do its still crash
