### ISSUE TITLE
Far Cry 5 and  Far Cry New Dawn

### ISSUE THREAD

**Issue by Alex-Kraynov** [doitsujin/dxvk#1848]
Grass is flickering in FarCry 5 and Far Cry New Dawn.(Windows 10 20H2, Nvidia Pascla GPU, driver 457.30 )
https://drive.google.com/file/d/1oeuLJLDoFzT27ozZkVIkyFEjd4KgVa7h/view?usp=sharing
https://drive.google.com/file/d/1jbrYMi6nzQfkBBmGnbil6UzDFWBdec6o/view?usp=sharing

**Comment by mozo78** [comment]
DXVK is for Linux. Please use appropriate OS.

**Comment by Alex-Kraynov** [comment]
> DXVK is for Linux. Please use appropriate OS.

FarCry 5 and ND works MUCH better with DXVK, man. Only that grass bug...

**Comment by mozo78** [comment]
There's no grass flickering on Linux :)

**Comment by Alex-Kraynov** [comment]
> There's no grass flickering on Linux :)

There is no Linux on my PC! lol

**Comment by mozo78** [comment]
And that's where you make the great mistake ;)

**Comment by Alex-Kraynov** [comment]
> And that's where you make the great mistake ;)

Maybe:) But DXVK really helps with some games in Windows.

**Comment by K0bin** [comment]
First of all: are you sure this isn't a game bug?

If you are, please provide the logs and apitrace that were asked for in the issue template?

Besides this, the FC engine has been really problematic on DXVK. FC Primal regularly breaks for no reason at all.

**Comment by Alex-Kraynov** [comment]
> First of all: are you sure this isn't a game bug?
> 
> If you are, please provide the logs and apitrace that were asked for in the issue template?
> 
> Besides this, the FC engine has been really problematic on DXVK. FC Primal regularly breaks for no reason at all.

It is not a game bug. Works at native DX11 without that problem. How can i provide logs?

**Comment by Alex-Kraynov** [comment]
[FarCry5_d3d11.log](https://github.com/doitsujin/dxvk/files/5675635/FarCry5_d3d11.log)
[FarCry5_dxgi.log](https://github.com/doitsujin/dxvk/files/5675636/FarCry5_dxgi.log)

**Comment by Alex-Kraynov** [comment]
[FarCryNewDawn_d3d11.log](https://github.com/doitsujin/dxvk/files/5675637/FarCryNewDawn_d3d11.log)
[FarCryNewDawn_dxgi.log](https://github.com/doitsujin/dxvk/files/5675638/FarCryNewDawn_dxgi.log)

**Comment by doitsujin** [comment]
These games are known to be broken for some unknown reason, also, wrong OS:

**Comment by dominik1411** [comment]
d3d11.invariantPosition = True fixes the issue for me (RTX 2080 Ti on Windows FC5)

**Comment by K0bin** [comment]
Doesn't fix FC Primal.

**Comment by dominik1411** [comment]
> 
> 
> That doesn't fix FC Primal.

Why bring up FC Primal, this thread (as far as I see) is only about FC5 and FCND.

**Comment by K0bin** [comment]
Mostly because it's the same engine and Primal is known to be broken. I thought it might be related.
