### ISSUE TITLE
Borderlands 2 

### ISSUE THREAD

**Issue by rakantoh** [doitsujin/dxvk#1849]
I played borderlands 2 a few months with other version of dxvk, and works fine, but with latest versions of dxvk, the game stop responding ramdomly, i can play 1 hour or play 5 minutes, and the game simply crash without error message. I played without dxvk and the problem is gone.
I don´t know if this problem occurs in borderlands the pre-sequel. Maybe yes.

**Comment by K0bin** [comment]
Almost certainly running out of address space (see #1318).
Try setting `d3d9.evictManagedOnUnlock = True` in your DXVK config (more about that in the README)

**Comment by rakantoh** [comment]
I put the suggested config, and at the moment the problem of crash has disappeared, but now when the character walk or run, i can see as if the camera jump, as if had short frame cuts...

**Comment by K0bin** [comment]
You'll have to pick between either of those. It's not something that can be fixed unfortunately.

**Comment by rakantoh** [comment]
why close the issue? please leave open or reopen it, for author's knowlegment and possible fix.

**Comment by K0bin** [comment]
It is a known issue #1318 and there's simply nothing we can do about it.
