### ISSUE TITLE
[d3d9] slowdown in Valley Benchmark 1.0

### ISSUE THREAD

**Issue by rox4d** [doitsujin/dxvk#1851]
A huge slowdown introduced by f3a82a0 in Valley Benchmark 1.0 in D3D9 mode, reverting it restore performance (amd rx560 - it is the same for wine and windows7)

**Comment by doitsujin** [comment]
can you please be more specific? what is your "huge slowdown" in numbers? are you running a desktop or notebook with eGPU?

**Comment by rodrigo21** [comment]
I also have problems with this commit in some D3D9 games like Test Drive Unlimited 2. Reverting it also fix the problem of slowndown for me.
I'm using an AMD RX 550 2GB.

**Comment by rox4d** [comment]
I was not make a full benchmark for numbers, but with first scenes it more than twice slower with this commit (~20 vs ~44 fps), card is desktop pci-e 4Gb polaris 11, at linux radv used.

**Comment by rox4d** [comment]
Numbers are (with wine-4.9.5-staging) :
FPS: 26.7
Score: 1115
Min FPS: 16.6
Max FPS: 45.0
And without this commit:
FPS: 43.7
Score: 1830
Min FPS: 18.8
Max FPS: 84.3
I was wrong - fps dropout are less than twice:)

**Comment by SveSop** [comment]
Tested with nVidia RTX2070 DX9 - 1440p
Driver: 455.46.02
Wine: custom wine-staging-6.0-rc2

DXVK: 65635b23c1e8575362722c99e6ffdf9d9df64116
FPS: 94.7
Score: 3964
Min FPS: 45.8
Max FPS: 166.9

DXVK: 65635b23c1e8575362722c99e6ffdf9d9df64116 with revert f3a82a0bcc427394ab86b6a646c9a5487afcbcfc
FPS: 134.7
Score: 5634
Min FPS: 48.0
Max FPS: 245.7

**Comment by K0bin** [comment]
Fixed. Looking forward to reports that the revert makes other games slower.

**Comment by rsw0x** [comment]
> Fixed. Looking forward to reports that the revert makes other games slower.

4b66327 causes a major slowdown in Everquest, should I open an issue for it or is there an umbrella issue it falls under?

**Comment by K0bin** [comment]
[d3d9-everquest.zip](https://github.com/doitsujin/dxvk/files/5743120/d3d9-everquest.zip)

@rsw0x Please test this build.
