### ISSUE TITLE
Cyberpunk 2077 crash NVRM: Xid 31 (...) FAULT_PTE/PDE ACCESS_TYPE_READ

### ISSUE THREAD

**Issue by ygaeon** [doitsujin/dxvk#1853]
Running into similar issue as https://github.com/doitsujin/dxvk/issues/1169 while running Cyberpunk 2077.

The game, seemingly randomly, crashes with very specific kernel errors:
```
kernel: NVRM: Xid (...): 31, ..., Ch 00000033, intr 10000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_T1_7 faulted @ 0x1_fa4f0000. Fault is of type FAULT_PDE ACCESS_TYPE_READ
kernel: NVRM: Xid (.): 31, ..., Ch 00000034, intr 10000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_T1_6 faulted @ 0x2_36e40000. Fault is of type FAULT_PDE ACCESS_TYPE_READ
kernel: NVRM: Xid (...): 31, ..., Ch 00000033, intr 10000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_T1_8 faulted @ 0x2_01e80000. Fault is of type FAULT_PTE ACCESS_TYPE_READ
```

I've prior also noticed a little more information in the logs (not sure if it's related):
```
kernel: NVRM: Xid (...): 13, ..., Graphics Exception: ESR 0x51e224=0x80000009 0x51e228=0x3c180001 0x51e22c=0x1d95900 0x51e234=0xac801fc0
kernel: NVRM: Xid (...): 13, ..., NVRM: Graphics TEX Exception on (GPC 3, TPC 4):     TEX LAYOUT
```

### Software information
- Game: Cyberpunk 2077
- OS: Arch Linux, kernel 5.9.13-arch1-1
- WM: i3-blocks, no compositor in use

### System information
- GPU: GeForce GTX 1080
- Driver: 455.45.1
- Wine version: Proton 5.13-4 (wine-5.13-716-g7f9f4285c2d)
- DXVK version: ~~v1.7.3-4-g03f11baf~~ v1.7.3-5-g495b2a09
- .aur mesa-git: 21.0.0_devel.132248.b5485128135-1
- [vkd3d-proton](https://github.com/HansKristian-Work/vkd3d-proton/tree/master) ~~vkd3d-1.1-1735-g49ed5beb~~ vkd3d-1.1-1739-g793fce06

### Apitrace file(s)
- _Unsure how to run a trace on DX12 .. please advice_

### Log files
- d3d9.log: n/a
- d3d11.log: n/a
- dxgi.log: (attached)
[Cyberpunk2077_dxgi.log](https://github.com/doitsujin/dxvk/files/5683823/Cyberpunk2077_dxgi.log)

Edit: Updated to master and tried again, same problem. Also attached the dxgi log.

**Comment by K0bin** [comment]
DXVK does not support D3D12. Proton is using VKD3D-Proton and the problems with Cyberpunk are well known.
