### ISSUE TITLE
Support for rome total war d3d8to9

### ISSUE THREAD

**Issue by siyia2** [doitsujin/dxvk#1859]
No crashes.
Requested feature: if possible to run dxvk over d3d8to9 https://github.com/crosire/d3d8to9/releases

### Software information
Rome Total War Collection, reportedly a d3d8 game

### System information
- GPU: RX 5500 XT
- Driver: amdgpu Mesa
- Wine version: 5.0
- DXVK version: 1.7

**Comment by Joshua-Ashton** [comment]
I have no idea what the actual issue is cause you ignored the template entirely.

Please fill it out.

**Comment by siyia2** [comment]
Not a bug really more liek request. Dxvk doesnt activate for this game, later i found out this  is d3d8 game, then used https://github.com/crosire/d3d8to9/releases, but dxvk still doesnt activate.

**Comment by Joshua-Ashton** [comment]
Please just fill out the basic information on the template so I have some idea as to what setup/system you are running so I can actually help you.

**Comment by siyia2** [comment]
ok form filled

**Comment by WinterSnowfall** [comment]
> Requested feature: if possible to run dxvk over d3d8to9 https://github.com/crosire/d3d8to9/releases

It's already possible. I've been doing it for a few years now and have reported several bugs for D3D8 games which got fixed in DXVK thanks to @Joshua-Ashton .

All you have to do is grab the d3d8.dll from d3d8to9, copy it to your Wine prefix in the **windows/syswow64** and **windows/system32** dirs (it's also a good idea make a backup of the existing dlls first), then add an override in wine for d3d8 -> native. D3D8 games should now translate D3D8 -> D3D9 via d3d8to9, then D3D9->Vulkan with DXVK.

**Comment by siyia2** [comment]
Then why does DXVK_HUD=full doesnt show on rome total war with d3d8t9 enabled?

**Comment by siyia2** [comment]
lol taht did it!

`d3d8 -> native in winecfg `

**Comment by siyia2** [comment]
@Joshua-Ashton @WinterSnowfall Could this be mentioned in the wiki somehow i wouldnt be able if use d3d8to9 with dxvk if it werent for your comment!?

**Comment by WinterSnowfall** [comment]
> lol that did it!

Keep in mind that unless you specify an override, Wine will just use the builtin module for a dll that it also provides. That's how things work. With no override you'd fall back to WineD3D. It's not a DXVK specific thing, so I don't see why it would be documented here.

**Comment by siyia2** [comment]
i thought it was native,builtin by default shoulkd have worked out of the box

**Comment by WinterSnowfall** [comment]
> i thought it was native,builtin by default should have worked out of the box

Last I checked it was the other way around. Builtin then native by default.

**Comment by siyia2** [comment]
oh my mistake, anyways thx, i am closing this since it is not dxvk related
