### ISSUE TITLE
World of Warships crashes every time at "synchronizing", with latest proton, works with proton 3.16-9, much like last time

### ISSUE THREAD

**Issue by Darxus** [doitsujin/dxvk#1860]
Only difference I see is last time it was crashing at "logging in": https://github.com/doitsujin/dxvk/issues/1834

https://github.com/ValveSoftware/Proton/issues/333

Last time it was looking like a problem with the way DXVK reports its version info to the game:  https://github.com/doitsujin/dxvk/issues/1834#issuecomment-734266900

**Comment by Darxus** [comment]
The game did have lots of updates this morning, including WorldOfWarships.exe.

**Comment by Darxus** [comment]
This patch was a successful workaround last time:  https://github.com/doitsujin/dxvk/issues/1834#issuecomment-734288119
But would cause problems with other games that depend on the version info: https://github.com/doitsujin/dxvk/issues/1834#issuecomment-734268676

**Comment by doitsujin** [comment]
More like a problem with how the game reacts to our version info. Still no idea how to work around that since we obviously don't have access th the game code, but you can always just build a custom DXVK without it.

**Comment by Darxus** [comment]
Like last time, this seems to have been fixed on the server side.  I can get to the main menu, no local files have been updated.

**Comment by RonnySvedman** [comment]
Im now where it is only working with older proton's  , not 5.13 or the experimental one.
