### ISSUE TITLE
Where to get help building/installing dxvk

### ISSUE THREAD

**Issue by bebing2** [doitsujin/dxvk#1861]
Hello, this is not an "issue" per se. I have questions about building and installing, so I searched for a mailing list, bulletin board, irc channel etc. and could not find any. So my main question would be if any of those are available and if so, where they could be found. Thank you.

**Comment by K0bin** [comment]
The readme has build instructions.

**Comment by bebing2** [comment]
Thanks for the reply! Do I need to even build it or is there already any pre-build binaries?

Thanks!
Blair

**Comment by ZachBacon** [comment]
There's https://github.com/doitsujin/dxvk/releases for release builds if that's what you're looking for.

Or if you want git builds theres something that I think @Joshua-Ashton had setup, not sure if it's still available or not. I don't exactly remember the url

**Comment by bebing2** [comment]
Well I didn't want to pollute this area with my questions, but if it's appropriate I can give more info. Also, I thought my issue was in mingw-w64 but the IRC channel(#mingw-w64) told me to talk to the divx people. I am on LFS so unfortunately no apt-get etc. for me :(. Normally I don't mind building things, but it seems some of these projects and build systems are a bit over my head, so if I don't have to build anything, that's even better! So anyway, I started trying to build dxvk and am getting issues about not finding x86_64-w64-mingw32-gcc as expected, so I go to build mingw-w64 and that's really where it seems my issues are. So I try to build mingw-w64(do I even need to? are there binaries anywhere), and as far as I know this is gcc for windows environment. So I was trying to find out what packages I needed to install and there is no clear answer because many of the packages are for people using windows. I came up with trying, mingw-w64-v8.0.0.tar.bz2(linux), mingw-w64-install.exe(windows, wine), and GCC-10.2.0-crt-8.0.0-with-ada-20201019.7z(windows, wine?). There isn't much documentation or help available on this front. I didn't want to trouble dxvk about this, and that's why also I was looking for a more casual form of communication. Sorry if this is the wrong place.

**Comment by bebing2** [comment]
Some time in the past I believe I was able to get it working more or less by poaching debian libs and binaries, but I have been having issues with wine/battle.net and in trying to resolve them I've been building/installing 64 bit and 32 bit libs. I think my ultimate issue is inside qt-webengine and that seems dependent upon dxvk

**Comment by bebing2** [comment]
So I'm not even clear on the correct approach or which packages I need to install. I think most people are able to use apt-get and similar, so I am not finding much help. So much confusion on my end over linux vs. windows, 64 bit vs. 32 bit. For example battle.net is 32 bit but when it uses the webkit that is the 64 bit version, so I believe I only need 64 bit versions.

**Comment by bebing2** [comment]
Thank you so much for the help! Will check it out.

**Comment by bebing2** [comment]
When I try to build mingw-w64 it complains about missing headers, so then I build and install mingw-w64-headers that is containted within mingw-w64 as if it is a standalone package and then go back to building mingw-w64, but then the _mingw.h triggers dozens of errors. I've tried messing around with the configure options:
./configure --host=i686-w64-mingw32 --target=i686-w64-mingw32 --disable-multilib
./configure --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --disable-multilib
./configure --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --enable-targets=all --enable-lib32
./configure --enable-targets=x86_64-w64-mingw32,i686-w64-mingw32
but not finding anything that will work

**Comment by bebing2** [comment]
The initial errors I'm getting in wine with battle.net are:
[1220/013656.672:ERROR:dxva_video_decode_accelerator_win.cc(1397)] DXVAVDA fatal error: could not LoadLibrary: msmpeg2vdec.dll: Module not found. (0x7E)
[1220/013656.675:ERROR:dxva_video_decode_accelerator_win.cc(1405)] DXVAVDA fatal error: could not LoadLibrary: msvproc.dll: Module not found. (0x7E)
[1220/013656.766:ERROR:proxy_config_service_win.cc(136)] WinHttpGetIEProxyConfigForCurrentUser failed: 0
[1220/013656.769:ERROR:proxy_config_service_win.cc(136)] WinHttpGetIEProxyConfigForCurrentUser failed: 0
[1220/013657.154:ERROR:network_change_notifier_win.cc(142)] WSALookupServiceBegin failed with: 0
[1220/013657.342:ERROR:ssl_client_socket_impl.cc(959)] handshake failed; returned -1, SSL error code 1, net_error -202
It's hard to know which error messages are the show-stoppers. I am able to login to diablo 2(32 bit) and world of warcraft(64 bit) fine. Also hard to know if a solution can be fixed with overiding dlls or a winetricks command as opposed to futzing with source code.

**Comment by K0bin** [comment]
None of those errors have anything to do with DXVK.

**Comment by bebing2** [comment]
Thank you sir! I know qt has vulkan stuff in it, and saw the leading dxv connected with video accelerator based dlls (msmpeg2vdec.dll, msvproc.dll) and thought dxvk might generate them. Maybe I'll give up trying to get DXVK to build. Too bad. Thanks again.

**Comment by bebing2** [comment]
Oh and also the symptom I'm seeing in wine/battle.net is being stuck at the login with the spinning icon, which is usually fixed by turning off hardware acceleration in the browser. I already did a lot with the ssl/gnutls side of things, so the ssl error might be a red herring because I can log in to diablo 2 and world of warcraft and steam and banks etc. So I was thinking qtwebengine uses vulkan/dxvk and the symptom is the same with browser acceleration. Oh well, might be a dead end for me. I bet you who knows all this stuff are the package maintainers. They are able to get this stuff going so most people just have to apt-get everything.

**Comment by Joshua-Ashton** [comment]
There are binary releases on the Github releases page:
https://github.com/doitsujin/dxvk/releases

Back to building:

MinGW is a pretty easy build -- it builds exactly the same as GCC. If you're having a problem with it, there's probably something fundamentally broken with your setup.

That being said, I don't think you're going to find LFS support here or anywhere else given how niche it is; the LFS guide is more of a learning tool than something that will get something usable on your system -- it may be worth switching to an actual distro if you plan to use Linux as an end user.
