### ISSUE TITLE
GTA 4 rendering bugs on Big Navi (RX 6800 XT)

### ISSUE THREAD

**Issue by yoyossef** [doitsujin/dxvk#1862]
I'm having some heavy rendering issues with Grand Theft Auto IV: Complete Edition on Steam, running on a Radeon RX 6800 XT, the visible rendered part is also very blurry.

![20201221110458_1](https://user-images.githubusercontent.com/31565280/102772560-0301e080-4388-11eb-8175-2fc26f10bdef.jpg)

### Software information
Grand Theft Auto IV: Complete Edition, settings cranked to the max possible, 1440p @ 60 or 165fps.

### System information
- GPU: AMD Radeon RX 6800 XT
- Driver: Mesa 21.0.0-devel (git-f9ceab7b23)
- Proton version: Proton-GE 5.21-GE-1
- Wine version: wine @ cf49617 (https://github.com/GloriousEggroll/proton-ge-custom/tree/5.21-GE-1)
- DXVK version: dxvk @ 6a10c81 (https://github.com/GloriousEggroll/proton-ge-custom/tree/5.21-GE-1)

**Comment by doitsujin** [comment]
are we sure this isn't a driver bug?

**Comment by Joshua-Ashton** [comment]
Can you try launching the game with `RADV_DEBUG=nodcc %command%` set as your launch options?

**Comment by yoyossef** [comment]
> Can you try launching the game with `RADV_DEBUG=nodcc %command%` set as your launch options?

Reposting from the Discord to maintain consistency: 

Seems to run fine with the launch argument.
![20201221134458_1](https://user-images.githubusercontent.com/31565280/102778902-aa384500-4393-11eb-8414-85dd943b422e.jpg)

**Comment by niko1point0** [comment]
Did you say Discord discussion? Can you post a link to the server?

**Comment by yoyossef** [comment]
> Did you say Discord discussion? Can you post a link to the server?

VKx discord server: https://discord.gg/mjWm8DK

**Comment by jarrard** [comment]
Try using LLVM compiler. There is a bug with ACO with GTA5 and perhaps this is similar for GTA4?

**Comment by NO-ob** [comment]
RADV_DEBUG=nodcc fixed the glitches for me in proton with a 5700xt thankyou

**Comment by pryvisee** [comment]
Any fix on this on Windows?

**Comment by K0bin** [comment]
Nope

**Comment by doitsujin** [comment]
Should be fixed on master with latest mesa-git as well.

**Comment by Squall-Leonhart** [comment]
VK_EXT_attachment_feedback_loop_layout is simply not available in any driver made by amd.

**Comment by Blisto91** [comment]
It's available in mesa radv 22.2 which is the amd driver primarily supported by dxvk

**Comment by Squall-Leonhart** [comment]
contributiive effort, is not *made by*

**Comment by Blisto91** [comment]
Technically i don't think amd contributes to radv 👀 
Anyway. I'm not sure I understand your point. Aren't you commenting in this old issue because you have the problem? 🤔

**Comment by Squall-Leonhart** [comment]
Mainly to point out that AMD's own drivers don't have the extension so the issue remains, so thats the reason for no fix for Windows users.

People are using this to make GTA4 perform better on Windows, so Radeon owners luck out

**Comment by K0bin** [comment]
DXVK is built for Linux.

You should complain to AMD and tell them to implement the extension.

**Comment by Joshua-Ashton** [comment]
You can go complain here:

**Comment by MagicAl6244225** [comment]
AMD states support of VK_EXT_attachment_feedback_loop_layout as of Adrenalin Edition 23.2.1 - January 24th, 2023

https://www.amd.com/en/support/kb/release-notes/rn-rad-win-vulkan

**Comment by jarrard** [comment]
> 

I'm pretty sure that is for Windows drivers.  MESA-RADV/AMDVLK could be behind.

**Comment by K0bin** [comment]
@jarrard RADV has supported this for ages.

**Comment by Blisto91** [comment]
amdvlk should also include it with their 2023Q1.1 release.

**Comment by paperlyly** [comment]
i have this problem, but im on intel, what would be the solution in this case?

**Comment by Blisto91** [comment]
If you mean Intel Linux then you likely need to wait until this has been https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/17892

**Comment by Ciro23** [comment]
> Can you try launching the game with `RADV_DEBUG=nodcc %command%` set as your launch options?

I had the same problem on Debian 12 with a Radeon RX 7600 and adding that launch option fixed it for me too.
I installed the game via Lutris (0.5.12) and in "Configure" section of GTA IV > "System options > "Environment variables" I added a new variable with `RADV_DEBUG` as the key and `nodcc %command%` as the value.

**Comment by K0bin** [comment]
@Ciro23 Make sure your Vulkan driver is not ancient.

**Comment by Ciro23** [comment]
I'm aware of Debian slow rolling policy and currently I'm fine with it. All the games I played right now worked fine as they did on Pop_OS, until it decided to completely destroy it self from a day to another.

**Comment by Ciro23** [comment]
> @Ciro23 Make sure your Vulkan driver is not ancient.

I'm aware of Debian slow rolling policy and currently I'm fine with it. All the games I played right now worked fine as they did on Pop_OS, until it decided to completely destroy it self from a day to another.
