### ISSUE TITLE
Icarus demo has horizontal line artifacts on Intel Skylake with wine-dxvk installed

### ISSUE THREAD

**Issue by dxvkbob** [doitsujin/dxvk#1868]
As per the title, Icarus demo has various lines displayed on the title screen and during gameplay. These disappear when wine-dxvk is uninstalled.

![Icarus1](https://user-images.githubusercontent.com/76689666/103216440-fb08ea00-490d-11eb-8ecf-42e23b681283.jpg)
![Icarus2](https://user-images.githubusercontent.com/76689666/103216443-fba18080-490d-11eb-865a-3c0d3bb70d4c.jpg)

Demo download from: https://www.dropbox.com/s/n63a08l4ujg81gt/Icarus.zip?dl=0

My system: Intel Skylake (HD Graphics 530), Fedora 33, Wine-dxvk version: 1.7.2

**Comment by mozo78** [comment]
There are no probems at all:
![Screenshot_20201228_152033](https://user-images.githubusercontent.com/38666396/103217072-5fcd4000-4920-11eb-96bf-fc13382a129b.png)

**Comment by dxvkbob** [comment]
Thanks for testing. Can anyone try with Intel/Mesa? This configuration doesn't work for me.

**Comment by doitsujin** [comment]
which api is this even?

**Comment by dxvkbob** [comment]
Xorg X11 Intel video driver: 2.99.917
Mesa (jnc. Vulkan): 20.2.6

**Comment by dxvkbob** [comment]
warn:  D3D11CoreCreateDevice: Adapter is not a DXVK adapter
info:  Game: Icarus.exe
info:  DXVK: v1.7.2
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_1
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_1
info:  Device properties:
info:    Device name:     : Intel(R) HD Graphics 530 (SKL GT2)
info:    Driver version   : 20.2.6
info:  Enabled device extensions:
info:    VK_EXT_4444_formats
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state
info:    VK_EXT_host_query_reset
info:    VK_EXT_robustness2
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_image_format_list
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 1
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 1
info:    logicOp                                : 1
info:    multiDrawIndirect                      : 1
info:    drawIndirectFirstInstance              : 1
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 0
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 1
info:    shaderImageGatherExtended              : 1
info:    shaderStorageImageExtendedFormats      : 1
info:    shaderStorageImageReadWithoutFormat    : 0
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 1
info:    shaderInt64                            : 1
info:    variableMultisampleRate                : 1
info:  VK_EXT_conditional_rendering
info:    conditionalRendering                   : 1
info:  VK_EXT_4444_formats
info:    formatA4R4G4B4                         : 1
info:    formatA4B4G4R4                         : 0
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_extended_dynamic_state
info:    extendedDynamicState                   : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 0
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 1
info:    robustImageAccess2                     : 1
info:    nullDescriptor                         : 1
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 1
info:    geometryStreams                        : 1
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 0
info:  DXVK: Read 4 valid state cache entries
info:  DXVK: Using 2 compiler threads
warn:  winevulkan detected, disabling exclusive fullscreen support
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  960x540
info:    Image count:  3
info:    Exclusive FS: 1
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  960x540
info:    Image count:  4
info:    Exclusive FS: 1

**Comment by Joshua-Ashton** [comment]
Are you sure it's not just the [Moiré effect](https://en.wikipedia.org/wiki/Moir%C3%A9_pattern) from some sort of scaling?

**Comment by mozo78** [comment]
Nope, see the plane's flame from my screenshot :)

**Comment by doitsujin** [comment]
@Joshua-Ashton sampler rounding issues again? you know, the `TRUNC_COORD` one on AMD?

**Comment by dxvkbob** [comment]
Hmm, seems like the demo has been updated. I now have options on the title screen and more graphical effects that weren't there before. More significantly, the artifact lines have gone as well. Not sure if it's worth keeping this bug report open. Unfortunately I don't have the old version of the demo any more.
