### ISSUE TITLE
SimCity 2013 doesn't render

### ISSUE THREAD

**Issue by sykhro** [doitsujin/dxvk#1869]
This issue applies to both the launcher and the game.
The [launcher](https://user-images.githubusercontent.com/8491400/103227617-10dad700-492f-11eb-977a-7800e4832eed.png) is rendered as a bunch of squares but still seems to respond do HID events.
With random clicking in the bottom-right area (or by setting `-state:SimCity` in the game launch options) it's possible to boot the game up, which presents [the same rendering issues](https://user-images.githubusercontent.com/8491400/103227711-4aabdd80-492f-11eb-9db2-d5c7ff9db226.png)  (and a somewhat functional mouse cursor)

WineD3D doesn't seem to work either due to unsupported formats (DF16, DF24) and only displays the mouse cursor

_Note: I'm using a virtual desktop because I got sick of the game resetting my resolution every time it booted up. The configuration file doesn't seem to be human-readable_

### Software information
SimCity 2013 (Origin), `-state:SimCity` to bypass the server-selection game launcher

### System information
- GPU: Radeon RX 580 2048SP
- Driver: amdgpu on 5.10.1, mesa 20.3.1
- Wine version: 6.7-staging
- DXVK version: 1.8.1

### Apitrace file(s)
- [SimCity-wined3d-6.7.zip](https://github.com/doitsujin/dxvk/files/6405613/SimCity-wined3d-6.7.zip)
- [SimCity-dxvk-1.8.1.zip](https://github.com/doitsujin/dxvk/files/6405648/SimCity-dxvk-1.8.1.zip)

### Log files
- d3d9.log: [SimCity_d3d9.log](https://github.com/doitsujin/dxvk/files/5747962/SimCity_d3d9.log)
- d3d11.log: Not generated
- dxgi.log: Not generated

**Comment by sykhro** [comment]
Tried again with 525fd53bbc6c2c0ff73560bca9f543652035eddc, rendering is still broken but stuff moves around.

**Comment by K0bin** [comment]
We need the apitrace to debug this.

**Comment by sykhro** [comment]
> We need the apitrace to debug this.

Whoops sorry, this time I managed to record one but forgot to add it in the report.

**Comment by firescry** [comment]
I'm not sure if it's still needed, but as label `needs apitrace` is set, I collected and I'm sharing apitrace too.
It seems that I experience the same problem as sykhro. Game launcher and main menu are rendered in full as mosaic of small, colourful squares. In main game view 3D objects look fine, but 2D interface is missing and square artefacts are still visible, as in this [screenshot](https://user-images.githubusercontent.com/49809580/132999226-e2611b50-6a14-4c01-a987-62a57733f464.png).
Issue is visible while I use dxvk - I've checked v1.9.1 and master (dd7ffbc) - both are affected. Game renders without this problem with naive wine d3d implementation.

### Software information
SimCity 2013 (Origin)

### System information
- GPU: AMD Radeon RX 580
- Driver: mesa 21.2.1 @ linux 5.14.2
- Wine version: wine-6.16 (Staging)
- DXVK version: v1.9.1 and master (dd7ffbc)

### Apitrace file(s)
- [SimCity.tar.xz](https://drive.google.com/file/d/1U-C71zzHbZsjo6D1L0aZn5ji6lUea0rE/view?usp=sharing)

### Log files
- d3d9.log: [SimCity_d3d9_v1.9.1.log](https://github.com/doitsujin/dxvk/files/7150140/SimCity_d3d9_v1.9.1.log) and [SimCity_d3d9_dd7ffbc.log](https://github.com/doitsujin/dxvk/files/7150141/SimCity_d3d9_dd7ffbc.log)
- d3d11.log: not created or created empty
- dxgi.log: not created or created empty

**Comment by firescry** [comment]
Thank you @Joshua-Ashton 🐸
