### ISSUE TITLE
Longer launch time

### ISSUE THREAD

**Issue by liberodark** [doitsujin/dxvk#1874]
### Description :
Hi now when run game in GPU Intel / AMD game make long time to run.
I think is more in Unity Games.
Now is x6 much longer 10sec for run in normal time now is 60sec
If you dont use DXVK game run at 10sec.
In some games I have x6 call in `warn:  OpenVR: Failed to initialize OpenVR`
I dont know for what is calling OpenVR x6 times
PS : I dont use OpenVR, if you want other games log no problem.

### Informations :
We tried to find the problem on our side but we do not understand why since v30 of our system with Mesa 20.3.x
and LLVM 11 we have this concern.
Since the problem is present only when DXVK is activated I allow myself to submit an issue to you in order to find a solution.

### Software information
Batocera v30 : 
Full Screen 1920x1080 + ESYNC + FSYNC

### System information
- Kernel 5.10.4
- GPU: AMD Vega 7
- Driver: Mesa 20.3.1
- Wine version : Proton 5.13.4 or Lutris 5.7-11
- DXVK version: 1.7.3 or 1.7.2

### Apitrace file(s)
- https://gofile.io/d/RjCUDv
- https://uptobox.com/xnhdyu91hmui

### Log files
- d3d9.log:
- d3d11.log: [Windlands_Win_x64_d3d11.log](https://github.com/doitsujin/dxvk/files/5758079/Windlands_Win_x64_d3d11.log)
- dxgi.log: [Windlands_Win_x64_dxgi.log](https://github.com/doitsujin/dxvk/files/5758080/Windlands_Win_x64_dxgi.log)

**Comment by doitsujin** [comment]
Not a bug, just sounds like slow shader compile times (which is expected if you use LLVM with RADV for whatever reason).

**Comment by liberodark** [comment]
I think there is something.
As I told you before.
On mesa 20.1.x + LLVM 9
We don't have that worries.
