### ISSUE TITLE
Visage (594330): rendering issues

### ISSUE THREAD

**Issue by diegoviola** [doitsujin/dxvk#1876]
I'm running into some rendering issues with Visage, the rendering issues usually happen in one place but not another, I'm not sure what causes the problem.

I've installed Visage from Steam using flatpak (if that matters), I'm also using the flatpak version of Proton-GE 5.21-GE-1.

My distro is Arch Linux.

### Software information

Visage.

### System information
- GPU: AMD Ryzen 5 2400G APU (Vega 11 integrated graphics)
- Driver: Mesa 20.3.1
- Wine version: 5.21
- DXVK version: 1.7.3

### Apitrace file(s)

https://drive.google.com/file/d/1JUMR6gqpgsQOyLJU7oB774xq6He4bBtD/view?usp=sharing

### Log files
- d3d11.log: https://0x0.st/-rhT.txt

### Screenshots

![visage1](https://i.imgur.com/2wmuLCR.jpg)
![visage2](https://i.imgur.com/8ieZZOe.jpg)
![visage3](https://i.imgur.com/8iu09Uo.jpg)

**Comment by doitsujin** [comment]
Can you please either record an apitrace or give clear instructions on how to reproduce the problem? "Happens in some places" isn't particularly helpful.

**Comment by diegoviola** [comment]
@doitsujin https://drive.google.com/file/d/1JUMR6gqpgsQOyLJU7oB774xq6He4bBtD/view?usp=sharing

**Comment by doitsujin** [comment]
Thanks. Does replaying the trace show these issues on your end? It seems to replay just fine on both my Polaris GPU and Renoir (which is also Vega-based).

**Comment by diegoviola** [comment]
> Does replaying the trace show these issues on your end?

Yes, it does.

> It seems to replay just fine on both my Polaris GPU and Renoir (which is also Vega-based).

Interesting.

**Comment by doitsujin** [comment]
I suppose you should file a Mesa bug report then since this seems specific to Raven/Picasso.

**Comment by diegoviola** [comment]
> I suppose you should file a Mesa bug report then since this seems specific to Raven/Picasso.

Thanks, I'll do that.

**Comment by diegoviola** [comment]
@doitsujin looks like it was a RADV bug (I couldn't reproduce it with AMDVLK).

I ended up compiling Mesa master and it's already fixed there. Thanks again.

**Comment by diegoviola** [comment]
This issue has been fixed: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4129
