### ISSUE TITLE
[properties] section is deprecated in Meson 0.56

### ISSUE THREAD

**Issue by Kron4ek** [doitsujin/dxvk#1877]
c/cpp args and link args are now ignored if they are in the [properties] section, and Meson shows a warning. Commit [bbba6a7](https://github.com/mesonbuild/meson/commit/bbba6a7f365f8b7dc7f2d4c3ce7f3e5f4c05fc5e).

It's probably a good idea now to use both sections simultaneously. New Meson version just ignores [properties] (yes, it shows the warning, but does not interrupt the build process). And older Meson versions will probably just ignore the new section, but i haven't tested this on older versions, so just an assumption.

```
[properties]
c_link_args = ['-static', '-static-libgcc']
cpp_link_args = ['-static', '-static-libgcc', '-static-libstdc++']
needs_exe_wrapper = true

[built-in options]
c_link_args = ['-static', '-static-libgcc']
cpp_link_args = ['-static', '-static-libgcc', '-static-libstdc++']
needs_exe_wrapper = true
```

Due to this, 32-bit build of DXVK 1.7.3 was compiled without -msse and -msse2 as it was built using Meson 0.56 (right?), at least i guess so given the upload date.

**Comment by doitsujin** [comment]
Yes, I'm aware of the problem. Feel free to file a PR; I'm still on vacation.

**Comment by pchome** [comment]
> *Changed in 0.55.0* putting `<lang>_args` and `<lang>_link_args` in the
properties section has been deprecated, and should be put in the built-in
options section.

So not the whole properties section, according to the commit.

**Comment by iWeaker4you** [comment]
Breaks Proton Build.

**Comment by ZachBacon** [comment]
> Breaks Proton Build.

Next step would be to update protons build procedure to use newer meson then.

**Comment by pchome** [comment]
or, just put cross-files where Meson can find them and use ones for all mingw projects.

https://mesonbuild.com/Cross-compilation.html#cross-file-locations
> ...
> These files can be loaded automatically without adding a path to the cross file. For example, if a ~/.local/share/meson/cross contains a file called x86-linux, then the following command would start a cross build using that cross files:
`meson builddir/ --cross-file x86-linux`
