### ISSUE TITLE
Building dxvk-1.7.3

### ISSUE THREAD

**Issue by sildeag** [doitsujin/dxvk#1881]
Input: ./package-release.sh master ~/dxvk-1.7.3/target --dev-build
Output:
everything good until
[121/265] Compiling C++ object src/dxgi/dxgi.dll.p/dxgi_adapter.cpp.obj
FAILED: src/dxgi/dxgi.dll.p/dxgi_adapter.cpp.obj 
...

x86_64-w64-mingw32-g++ -Isrc/dxgi/dxgi.dll.p -Isrc/dxgi -I../../../src/dxgi -I../../../include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O3 -DNOMINMAX -MD -MQ src/dxgi/dxgi.dll.p/dxgi_adapter.cpp.obj -MF src/dxgi/dxgi.dll.p/dxgi_adapter.cpp.obj.d -o src/dxgi/dxgi.dll.p/dxgi_adapter.cpp.obj -c ../../../src/dxgi/dxgi_adapter.cpp
In file included from ../../../src/dxgi/dxgi_adapter.cpp:8:
../../../src/dxgi/dxgi_factory.h:13:41: error: ‘IDXGIFactory7’ was not declared in this scope; did you mean ‘IDXGIFactory2’?
   13 |   class DxgiFactory : public DxgiObject<IDXGIFactory7> {
      |                                         ^~~~~~~~~~~~~
      |                                         IDXGIFactory2
...

What am I doing wrong?

Ubuntu 20.10 
Project name: dxvk
Project version: v1.7.3
C compiler for the build machine: cc (gcc 10.2.0 "cc (Ubuntu 10.2.0-13ubuntu1) 10.2.0")
C linker for the build machine: cc ld.bfd 2.35.1
C++ compiler for the build machine: c++ (gcc 10.2.0 "c++ (Ubuntu 10.2.0-13ubuntu1) 10.2.0")
C++ linker for the build machine: c++ ld.bfd 2.35.1
C compiler for the host machine: x86_64-w64-mingw32-gcc (gcc 9.3.0 "x86_64-w64-mingw32-gcc (GCC) 9.3-posix 20200320")
C linker for the host machine: x86_64-w64-mingw32-gcc ld.bfd 2.34
C++ compiler for the host machine: x86_64-w64-mingw32-g++ (gcc 9.3.0 "x86_64-w64-mingw32-g++ (GCC) 9.3-posix 20200320")
C++ linker for the host machine: x86_64-w64-mingw32-g++ ld.bfd 2.34

Intel HD Graphics card.

**Comment by Joshua-Ashton** [comment]
Out of date MinGW.

**Comment by sildeag** [comment]
@Joshua-Ashton where does one get a more current version of minGW or which compiler version do you recommend?
