### ISSUE TITLE
dx11 feature 10 required on nvidia optimus

### ISSUE THREAD

**Issue by whinis** [doitsujin/dxvk#1884]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
Preferably record the trace on Windows, or wined3d if possible.

**Reports with no log files will be ignored.**

### Software information
Currently tried Satisfactory and Outer Worlds using Proton 5.21-GE and get the infamous `dx11 feature 10 required` error. However vulkaninfo and Dota2 seem to run without issues under the vulkan API. I have attached my vulkaninfo output below
[vulkaninfo.txt](https://github.com/doitsujin/dxvk/files/5762325/vulkaninfo.txt)
I can also run https://github.com/srmojuze/Refresh2025 without issues. 

I have tried launching through both on-demand with `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia` as well as just forcing the nvidia gpu to be on and bypass the intel without success.

### System information
- GPU: Nvidia 980M/Intel(R) HD Graphics 4600 (HSW GT2) (OPTIMUS)
- Driver: Nvidia-455
- Wine version: Proton-5.21-GE
- DXVK version: Proton-5.21-GE

**Comment by doitsujin** [comment]
Setup issue on you end. No log files -> no idea what's wrong though.

**Comment by whinis** [comment]
Its setup with proton, How would I get logs from proton ?

**Comment by whinis** [comment]
If I run the steam command with `DXVK_LOG_LEVEL=debug` all I get is the following 
[FactoryGame-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/5762452/FactoryGame-Win64-Shipping_d3d11.log)

I also have an empty d3d9.log file and an empty dxvk_config file

**Comment by doitsujin** [comment]
Either your Optimus setup is broken somehow or the game just insists on picking the Intel GPU for no particular reason. Try `DXVK_FILTER_DEVICE_NAMES=GeForce`, if that doesn't work, fix your Optimus stuff.

**Comment by whinis** [comment]
Using the filter device names works without issue however oddly enough it also works perfectly if I run certain games just through wine. Would I need to report this to proton then ?

**Comment by whinis** [comment]
Knowing what to look for it appears to be known https://github.com/ValveSoftware/Proton/issues/3215 Will close this and thank you.
