### ISSUE TITLE
Subnautica stalls for ~5000 miliseconds while in game since wine-6.0~rc5

### ISSUE THREAD

**Issue by braiam** [doitsujin/dxvk#1892]
After upgrading to wine-staging 6.0~rc5 with dxvk 1.7.3 or master, Subnautica stalls for 5 seconds and shows a red-hearing message that reads 

```
0024:err:sync:RtlpWaitForCriticalSection section 000000018168C330 "?" wait timed out in thread 0024, blocked by 0000, retrying (60 sec)
```
Downgrading to rc4 is a workaround. Wine without dxvk doesn't show this behavior. VSYNC on and off shows the issue.

### Software information
Subnautica, 1080p, High settings on everything, off motion blur

### System information
- GPU: RX 590
- Driver: amdgpu
- Wine version: 6.0~rc5 and 6.0~rc6
- DXVK version: master

### Apitrace file(s)
- Using apitrace make the game unplayable at 7 FPS which makes it very difficult to know if the issue appears.

### Log files
- d3d9.log:
- [Subnautica_d3d11.log](https://github.com/doitsujin/dxvk/files/5791856/Subnautica_d3d11.log)
- [Subnautica_dxgi.log](https://github.com/doitsujin/dxvk/files/5791857/Subnautica_dxgi.log)

**Comment by Iglu47** [comment]
apparently, this may not be related to DXVK or even "regular" Wine
@braiam more info can be found here:
https://github.com/wine-staging/wine-staging/commit/b8ca0eae9f47491ba257c422a2bc03fc37d13c22#comments
https://bugs.winehq.org/show_bug.cgi?id=50292
https://bugs.winehq.org/show_bug.cgi?id=50448

**Comment by doitsujin** [comment]
How is a performance regression after a wine update related to DXVK exactly when the exact same DXVK version works fine on another wine build?

**Comment by braiam** [comment]
@doitsujin consider this an early canary. Wine without dxvk doesn't have any indication off issues (in my case, even the performance isn't affected). Meanwhile, using dxvk has a very noticeable and reproducible issue. Once wine 6.0 hits more usable channels, users would notice that only when using dxvk, these stalls occur, and will reach the logical conclusion that dxvk is responsible.

As a wine client, this library is affected by the actions of the host program. I believe it would be useful that developers of this project are aware of changes of wine and if they need the host to make some changes, they communicate directly with wine developers.

I would also report a bug on Wine if there was any issue with the latest staging version, but I can't find any issue to report that doesn't involve dxvk. Wine developers would understandably recommend me to report this issue with dxvk.

**Comment by braiam** [comment]
@Iglu47 I would have to compile wine-rc5 without that patch to verify that is the one causing issues with dxvk. I'm going  to do that next.

**Comment by Joshua-Ashton** [comment]
This simply isn't our bug.

**Comment by Iglu47** [comment]
> @Iglu47 I would have to compile wine-rc5 without that patch to verify that is the one causing issues with dxvk. I'm going to do that next.

and is there any result?
just ../wine-staging/patches/patchinstall.sh DESTDIR="." `--all -W ntdll-NtAlertThreadByThreadId`

or maybe alternatively: some users report that applying this patch - helps
https://bugs.winehq.org/show_bug.cgi?id=50448#c15
`wget https://bugs.winehq.org/attachment.cgi?id=69112 -O 69112.patch`

**Comment by braiam** [comment]
@Iglu47 Yes, applying both patches seems to fix the issue. Will close this for now and report my finding upstream.
