### ISSUE TITLE
New "built-in options" meson section doesn't work on older meson

### ISSUE THREAD

**Issue by aeikum** [doitsujin/dxvk#1893]
Older meson ([<0.55](https://github.com/mesonbuild/meson/commit/bbba6a7f365f8b7dc7f2d4c3ce7f3e5f4c05fc5e#diff-63b5f5df61c22a95c0426608acba139fff698bdbb0e69436e52887173295f42fR164)) doesn't support the `built-in options` section introduced in 77af1026e24e8b913459c3dbef485fe7799a6a46. This means the link args get dropped, so the resulting binary depends on mingw-w64's libraries instead of pulling them in statically. E.g. when trying to load d3d11 in Wine:

    err:module:import_dll Library libgcc_s_seh-1.dll (which is needed by L"C:\\windows\\system32\\d3d11.dll") not found

Since it's only a deprecation, I suggest reverting the change until newer Meson is more widely distributed. Here's Debian's current distribution, for example: https://packages.debian.org/search?keywords=meson

**Comment by aeikum** [comment]
Cc @Kron4ek

**Comment by doitsujin** [comment]
sigh...

Apparently reverting this change breaks newer meson versions so we might have a bit of a problem here.

**Comment by FireBurn** [comment]
It doesn't break newer versions, it just printed lots of deprecation warnings

DEPRECATION: c_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: c_link_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: cpp_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: cpp_link_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: fortran_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: fortran_link_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: objc_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: objc_link_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: objcpp_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: objcpp_link_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: c_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: cpp_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: c_link_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: cpp_link_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
The Meson build system
Version: 0.56.2
