### ISSUE TITLE
GTA IV rendering issue - black screen and visual stutter - gf 960 at win10

### ISSUE THREAD

**Issue by kluczm** [doitsujin/dxvk#1895]
I tried out dxvk on fresh install of GTA IV complete edition on windows 10, and instantly after the game load the game render stopped working correctly, showing black screen with some additional artifacts, as seen here: 

https://imgur.com/a/vrHH9xB

### Software information
GTA IV complete, windows 10(fully updated, if it does matter), game set to 1080p, on medium settings

### System information
- GPU: gtx 960
- Driver: 461.9.0
- DXVK version: v1.7.3

### Apitrace file
https://drive.google.com/file/d/1Ey1m0J8VeF2c2V0ILkxph439onqS9pSS/view?usp=sharing

### Log files
- d3d9.log: https://pastebin.com/pHe3bV1B

**Comment by K0bin** [comment]
Game is more or less fine for me (even on Windows) and the trace replays without issues too.

**Comment by kluczm** [comment]
as per request from discord im posting second trace:

https://drive.google.com/file/d/1Gqk9_3Gn83KExeeeSIZxq2HDKzLw0vSu/view?usp=sharing

**Comment by mozo78** [comment]
Windows (Crap) 10 invasion in our beatiful project :(

**Comment by jarrard** [comment]
Try deleting dxvk.cache file and mesa_shader cache files in your .cache directory. And try again. Try 460 driver even (I assume 461 is latest).

**Comment by Blisto91** [comment]
@kluczm are you able to try again with latest dxvk and graphics driver?
