### ISSUE TITLE
F1 2018 corruption on characters in CG

### ISSUE THREAD

**Issue by JaxLinAMD** [doitsujin/dxvk#1897]
Operating System            : Ubuntu 20.04
ASIC                                 :  Navi 10
DRIVER                             : amdvlk https://github.com/GPUOpen-Drivers/AMDVLK

setup steam
Set resolution to 1920x1080
Set quality to Ultra High
When entering time trial mode choose "Classic F1 Cars" otherwise corruption is obscured by car cockpit view.

**Comment by JaxLinAMD** [comment]
add barrier in generated SPIRV can workaround this issue.

**Comment by doitsujin** [comment]
Which shader exactly?

We generate barriers when the orginal DirectX shader contains barriers. If there is none, this is a game bug.

**Comment by JaxLinAMD** [comment]
do you need the spirv file or renderdoc capture?

**Comment by doitsujin** [comment]
The SPIR-V so I can correllate it to the original shader.

**Comment by JaxLinAMD** [comment]
[spirv.zip](https://github.com/doitsujin/dxvk/files/5820168/spirv.zip)

**Comment by JaxLinAMD** [comment]
*_edited.dis shows where I added barriers

**Comment by doitsujin** [comment]
Same bug as in F1 2019. We have a workaround for that already which we can enable for both games.

**Comment by JaxLinAMD** [comment]
Hi @doitsujin  thank you for this. I have steam proton environment now, could you tell me how to verify with the workaround you enabled? can I replace some dx binaries of steam proton?

**Comment by doitsujin** [comment]
DXVK binaries are located in `.steam/steam/steamapps/common/Proton 5.13/dist/lib64/wine/dxvk` and can just be replaced.

**Comment by JaxLinAMD** [comment]
thank ya!

**Comment by JaxLinAMD** [comment]
hi @doitsujin  when building dxvk, I encountered following errors:

In file included from ../../../../../root/Downloads/dxvk-master/src/dxgi/dxgi_adapter.cpp:8:
../../../../../root/Downloads/dxvk-master/src/dxgi/dxgi_factory.h:13:41: error: ‘IDXGIFactory7’ was not declared in this scope; did you mean ‘IDXGIFactory2’?
   13 |   class DxgiFactory : public DxgiObject<IDXGIFactory7> {
 do you know how to resolve it?

**Comment by doitsujin** [comment]
The latest MinGW release (8.0, not to be confused with the GCC version) ships up to date DXGI headers which are required to build DXVK.

**Comment by JaxLinAMD** [comment]
thanks, it works :)
