### ISSUE TITLE
Planet Coaster dxvk no subtable 3d graphic adpater

### ISSUE THREAD

**Issue by vfioexperte** [doitsujin/dxvk#1898]
My problem is Plamet coaster crash with "Eroor no subtable 3d graphic adpater"
I use PROTON_USE_WINED3D=1  WINEDLLOVERRIDES=d3d9=b and it work on opengl.
### Software information
Planet Coaster
Appid: 493340

### System information
- GPU: AMD RX vega 64 and AMD rx 580
- Driver:mesa 20.3rc2
- Wine version: Proton 5.13.5 on steam clinet
- DXVK version: 1.7.3-36

star option with Proton: 
acohas teste,too on mesa
DXVK_HUD=full    RADV_DEBUG=llvm DRI_PRIME=1 DXVK_FILTER_DEVICE_NAME=580  PULSE_LATENCY_MSEC=60     %command%

the game Craft the World has tested work good iwth this options.

here a image:
![1](https://user-images.githubusercontent.com/62846024/104723829-1b1f1280-5730-11eb-9ed1-4fd1677ad46b.png)

**Comment by vfioexperte** [comment]
apitrace can not not work download from github slow and break.

**Comment by doitsujin** [comment]
Logs please.

**Comment by vfioexperte** [comment]
the game crash with the last update.
I have the download from apitrace starte waintig for downloads.
I have a archlinux apitrace version tested but not work with Proton.

**Comment by doitsujin** [comment]
Can you please post DXVK logs? Asking for the second time now.

**Comment by vfioexperte** [comment]
Planet Coaster not work.
DXVK_HUD=full  DXVK_ASYNC=1 RADV_PERFTEST=aco  DXVK_FILTER_DEVICE_NAME="AMD RADV POLARIS10"  PULSE_LATENCY_MSEC=60   %command%

**Comment by vfioexperte** [comment]
I have a problem with apitrace.exe and Planet Coster.
How start apitrace.exe with the steam client and the game?
The problem is drm protection of the game.exe not allow start without steam client.

**Comment by K0bin** [comment]
https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace

Follow this guide except that you use d3d11.dll, dxgi.dll and dxgitrace.dll instead of d3d9.dll.

**Comment by doitsujin** [comment]
The device name is shown in the HUD.

Also, maybe start by not setting any environment variables.

**Comment by vfioexperte** [comment]
I have with the steam tinker laucher
->custom command ->apitrace.exe #argc  trace -a dxgi  PlanetCoaster.exe
Ich start with a Planet Coaster Runtime ERROR.
dlls in folder Planet Coader copy
![2](https://user-images.githubusercontent.com/62846024/104751165-4b2cdc80-5755-11eb-8f36-0d385c646fb2.png)

**Comment by K0bin** [comment]
Just follow the guide I posted...

**Comment by vfioexperte** [comment]
here a trace filevon Panet Coster
https://github.com/vfioexperte/wine_hardened_script/raw/master/PlanetCoaster.trace.tar.xz

**Comment by doitsujin** [comment]
Third time: Can you *please* post DXVK log files?

**Comment by vfioexperte** [comment]
I have a problem i not found log files
  VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation DXVK_LOG_LEVEL=debug DXVK_LOG_PATH="dxvk_log" %command%
where is the fodler?

**Comment by doitsujin** [comment]
Try setting `DXVK_LOG_PATH` to `$HOME` and then look in your home directory.

**Comment by vfioexperte** [comment]
steam eroor
warn:  DXVK: No adapters found. Please check your device filter settings and Vulkan setup.

**Comment by doitsujin** [comment]
Do you even have a Vulkan driver installed? What does `vulkaninfo` say exactly?

**Comment by vfioexperte** [comment]
yes mesa and craft the world run at vulkan.
vulkaninfo
ERROR: [Loader Message] Code 0 : /usr/lib32/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib32/amdvlk32.so: wrong ELF class: ELFCLASS32
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 2.  Skipping ICD.
The selected gpu (0) is not a valid GPU index. The available GPUs are in the range of 0 to 18446744073709551615.

**Comment by vfioexperte** [comment]
yuzu emu vulkan work crorrect

**Comment by vfioexperte** [comment]
I have all in a docker contiern archlinux, too

**Comment by doitsujin** [comment]
Try uninstalling amdvlk. There's clearly some brokenness going on there (and I wouldn't be surprised if it's the new device selection layer they added for absolutely no reason).

**Comment by vfioexperte** [comment]
I remvoe amdvlk and vulkaninfo work
Thnkas

**Comment by vfioexperte** [comment]
I have no porblem more.
AMD-vlk is buggy thank you.

**Comment by barni2000** [comment]
Hello @vfioexperte next time if you have install amdvlk and radv, maybe you need to select the vulkan driver manually https://wiki.archlinux.org/index.php/Vulkan#Selecting_vulkan_driver

**Comment by vfioexperte** [comment]
VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json
this command wirth amdvlk installed not work vulkan carsh bei Palnet Coaster.
vulkan info crash again.
all other games work with installed amd-vlk.
is a bug in amdvlk from archlinux distro.
barni2000 Thnaks.
