### ISSUE TITLE
Extremely low fps in some UE4 games

### ISSUE THREAD

**Issue by Evolve-Git** [doitsujin/dxvk#1900]
I had a pretty smooth experience with dxvk (wine/proton) so far. Until i got my hands on these UE4 games: The Beast Inside, Moto racer 4. I have decent fps in the menu but when i load actual gameplay fps plummets to unplayable numbers (~9-11fps +- a couple fps depending on the settings) even when i return to the main menu. I also tried the same games in wined3d11 mode and got a lot higher fps of ~30. Then i launched them on windows and got ~60 fps. The only thing in common these games have is UE4 so i tried more games on this engine: Hellblade: Senuas sacrifice have the same issue while Hello Neighbour and Little Nightmares run great.

### Software information
The Beast Inside, Moto racer 4, Hellblade: Senuas Sacrifice (settings do not matter)

### System information
- GPU: GTX 680
- Driver: Nvidia 455.45
- Wine version: Proton 5.21 GE (also tried 5.21 tkg, 5.13, 5.0, 4.11, wine 6.0 tkg, 5.21)
- DXVK version: The ones built into these packages

### Log files
- d3d11.log: https://drive.google.com/drive/folders/1fKboEDPG_p3EJ_CvNCAVchAX0f1d43mY

**Comment by K0bin** [comment]
Kepler (the architecture of your GPU) is known to do poorly with modern titles and especially with DXVK.
How much VRAM does your card have? If it's 2GB then that is a huge problem for modern games.

**Comment by Evolve-Git** [comment]
Yeah, it's a 2gb card. So it's a hardware issue?

**Comment by K0bin** [comment]
Yes, kinda. There isn't much we can do.

**Comment by Evolve-Git** [comment]
But the HUD reports up to 1.5gb and it's almost playable in wined3d11. Oh well, dxvk is still awesome, gonna play other games until i save up for a new vcard. Thanks.

**Comment by K0bin** [comment]
> But the HUD reports up to 1.5gb

That's just how much the game uses. Other programs (browser, desktop environment, etc) also take some VRAM.
