### ISSUE TITLE
[d3d9] Trails in the Sky FC - Crash after title screen.

### ISSUE THREAD

**Issue by orbea** [doitsujin/dxvk#1902]
When running the GOG version of Trails in the Sky FC (https://www.gog.com/game/the_legend_of_heroes_trails_in_the_sky) and using `ed6_win_DX9.exe` or the `ed6_win.exe` with d3d8to9 (https://github.com/crosire/d3d8to9) the game will crash when starting a new game after the title screen.
```
.exeCreateFile failed. Error: 32 
.exeCreateFile failed. Error: 32
```
The game does not crash with wine vanilla when dxvk is uninstalled from the prefix.

### Software information
game:  https://www.gog.com/game/the_legend_of_heroes_trails_in_the_sky

I installed `d3dcompiler_43`, `d3dx9_43`, `amstream` and `quartz` using winetricks. I also installed LAVFilters (https://github.com/Nevcairiel/LAVFilters) using the installer and enabled the SoraVoice patch (https://github.com/ZhenjianYang/SoraVoice).
```
export WINEDLLOVERRIDES='dinput8=n,b'
```

### System information
- GPU: `AMD Radeon RX 5700 XT`
- Driver: `Mesa 21.1.0-devel (git-b603875482)`
- Wine version: `wine-vanilla-5.22`
- DXVK version: `1.7.3`

### Apitrace file(s)
[ed6_win_DX9.trace.xz.txt](https://github.com/doitsujin/dxvk/files/5839577/ed6_win_DX9.trace.xz.txt)

### Log files
- d3d9.log: [ed6_win_DX9_d3d9.log](https://github.com/doitsujin/dxvk/files/5839521/ed6_win_DX9_d3d9.log)

**Comment by orbea** [comment]
@Joshua-Ashton Is there anymore information I can provide to help debug this?

**Comment by Joshua-Ashton** [comment]
This game definitely used to work -- can you try an older version?

**Comment by orbea** [comment]
@Joshua-Ashton 

I first tested this again with dxvk-1.8.1, wine-6.3 and the current latest mesa commit (https://gitlab.freedesktop.org/mesa/mesa/-/commit/20bd9fc54700950cab88bc13f0446b2c14f86033) and the issue vanished. I guess I will close this until I can reproduce it again.
