### ISSUE TITLE
PPSSPP D3D11 backend crash on start

### ISSUE THREAD

**Issue by mirh** [doitsujin/dxvk#1904]
### Software information
PPSSPP 1.10.3, d3d11 backend. 

### System information
- GPU: GTX 950M
- Driver: 460.89
- Wine version: W10 H2
- DXVK version: 1.7.3

### Apitrace file(s)
- I guess you can take it however you want? Just [download](https://www.ppsspp.org/files/1_10_3/ppsspp_win.zip) the thing and set the rendering backend to direct3d 11. 

### Log files
- [d3d11.log](https://github.com/doitsujin/dxvk/files/5846198/PPSSPPWindows_d3d11.log)

Stack trace didn't have anything useful at all.

**Comment by doitsujin** [comment]
You need to use both d3d11.dll **and** dxgi.dll, it obviously will not work with Microsoft's DXGI implementation.

**Comment by mirh** [comment]
I throwed all the dlls in the ppsspp folder, just to be on the safe side, and it still crashed.

**Comment by doitsujin** [comment]
Works fine for me on wine.

**Comment by mirh** [comment]
You are right, I just checked with procmon, and the local dxgi copy isn't touched.

**Comment by mirh** [comment]
So weird though.
The sources show [nothing crazy](https://github.com/hrydgard/ppsspp/blob/dd5a459e001df45fa556a50a9ba12094efe748e1/Common/GPU/D3D11/D3D11Loader.cpp#L29) is going on. And I have just checked my [KnownDLLs](https://itm4n.github.io/windows-dll-hijacking-clarified/) and there's no trace of dxgi. 
But it works in W7 with the dGPU. 

So, if this is a W10 problem, my educated guess is that one of the other libraries the program uses is loading the dll its own special way first, and either:
* this unknown system library hadn't the same dependency on dxgi in W7, or nonetheless they loaded it with a normal LoadLibrary
* in older OSs without advanced switchable graphics capabilities, the driver force-injects nvdxgiwrap.dll asap, and that is pre-loading dxgi in the proper fashion for everybody
