### ISSUE TITLE
Wiki: Aco is now the default for AMD RADV (Mesa 20.0)

### ISSUE THREAD

**Issue by Thaodan** [doitsujin/dxvk#1905]
The Wiki refers to use:
`RADV_PERFTEST=aco`

for AMD RADV. However this now default since mesa 20.0:
https://gitlab.freedesktop.org/mesa/mesa/-/commit/0c569e22d1d038f651d5b5aa3cc46e7a5c6e152f

**Comment by doitsujin** [comment]
Just changed the recommended version to 20.2 which iirc was the one that enabled ACO by default.
