### ISSUE TITLE
game screen is complete black after launch

### ISSUE THREAD

**Issue by l12436** [doitsujin/dxvk#1906]
### Software information
ミラクルハート] クリス ナイトメア -Chris Nightmare-
screen is complete black
![image](https://user-images.githubusercontent.com/2596649/105429499-83b84300-5c8c-11eb-93c7-4d84c3ef2f79.png)

### System information
- GPU: GTX 1060
- Driver: nvidia 455.45.01
- Wine version: wine 6.0
- DXVK version: 1.7.3

### Apitrace file(s)
https://www.mediafire.com/file/zr5oc1rdth6teii/dump.gz/file

### Log files
- d3d9.log: [stdout.gz](https://github.com/doitsujin/dxvk/files/5852852/stdout.gz)

**Comment by K0bin** [comment]
Please retest with the latest master.

**Comment by l12436** [comment]
after certain version of dxvk, my dxvk + wine will just crash after wine launched....
nothing appear

environment ubuntu 20.04.2
driver nvidia 460.91.03
