### ISSUE TITLE
Spec Ops: The Line - God Rays rendering issue

### ISSUE THREAD

**Issue by gabriele2000** [doitsujin/dxvk#1908]
### Software information
Spec Ops: The line - DXGI latest release

### System information
- GPU: Nvidia GTX1050TI 4GB (notebook)
- Driver: Nvidia-460
- Wine version: Latest staging (6.0)
- DXVK version: Latest release 1.7.3
### Trace files:
https://mega.nz/file/tp10QCQT#uoaTnly6UzNyR0U-JPQ6PrwrHndprgRFmH0L9C8vC-M

### Log files
- d3d9.log: [SpecOpsTheLine_d3d9.log](https://github.com/doitsujin/dxvk/files/5866512/SpecOpsTheLine_d3d9.log)

![SpecOpsTheLine 2021-01-25 13-47-54](https://user-images.githubusercontent.com/12186181/105708297-875dfb00-5f14-11eb-86e7-15ac73f19e9e.png)
![SpecOpsTheLine 2021-01-25 13-47-49](https://user-images.githubusercontent.com/12186181/105708242-71e8d100-5f14-11eb-8f67-0588dcc85eac.png)

**Comment by gabriele2000** [comment]
Apitrace uploaded

**Comment by gabriele2000** [comment]
The issue seems releated to a particular fog effect too, post-processing stuff I guess, later in that level, that diagonal line was still there, acting as "saturation" thing

**Comment by doitsujin** [comment]
The apitrace renders fine on my Polaris card as far as I can tell. Not sure if the Nvidia driver is screwing up somewhere but it doesn't look like we're doing anything wrong.

**Comment by gabriele2000** [comment]
> 
> 
> The apitrace renders fine on my Polaris card as far as I can tell. Not sure if the Nvidia driver is screwing up somewhere but it doesn't look like we're doing anything wrong.

Today my pop_os updated the nvidia driver to its nvidia driver made for that distro... I'll test again

**Comment by WinterSnowfall** [comment]
Initially this kind of looked like yer' old Nvidia Optimus diagonal screen tearing to me, based on the screenshots screenshots. But I played back the api trace on my (desktop) GTX 1080, and I'm seeing the same thing (with 460.32.03) . So yes, probably an Nvidia issue, since AMD seems fine as per the above.

**Comment by gabriele2000** [comment]
> Initially this kind of looked like yer' old Nvidia Optimus diagonal screen tearing to me, based on the above screenshots. But I played back the api trace on my (desktop) GTX 1080, and I'm seeing the same thing (with 460.32.03) . So yes, probably an Nvidia issue, since AMD seems fine as per the above.

Yeah I confirm, updated everything... I even converted my NTFS SSD to a BRTFS one so windows can read it and linux too...
Guess what? Now Deep Rock Galactic finally starts but crashed after you press "escape" and your player shows up... but that's not releated to this bug report.

Though I have to disable the game's motion blur, maybe one post-processing effect less causes some benefits (aside from more FPS)

**Comment by gabriele2000** [comment]
![SpecOpsTheLine 2021-01-26 23-53-41](https://user-images.githubusercontent.com/12186181/105916844-db123680-6031-11eb-8143-d7408dd66dcf.png)

Ok so here you can see better that on the upper level the god rays are rendered... on the other side no godrays are rendered, but the lens flares are rendered...

Curious enough, motion blur is disabled in engine.ini, on windows no motion blur is present, though on linux it's still on, and I wonder why

**Comment by gabriele2000** [comment]
Bug still present on wine 6.2 staging + dxvk 1.8

**Comment by gabriele2000** [comment]
Bug still present on wine 6.3 staging + dxvk 1.8 and also on dxvk git - commit 7410707

**Comment by pchome** [comment]
It will be present until someone find that "broken" shader file between huge lot of other shader files used by the game, then ping people from Nvidia to look at it. This could be easier if something will fail validation, but both vulkan and spirv validations are ok here.

Use `DXVK_SHADER_DUMP_PATH=/path/to/dir` to get shaders and have fun.

p.s. Damn CEG. Anyway ...
