### ISSUE TITLE
[d3d9] TrackMania Nations Forever - low performance

### ISSUE THREAD

**Issue by flgx16** [doitsujin/dxvk#1910]
~22 FPS with DXVK
~85 FPS with wined3d
~135 FPS with DXVK and this DXVK config (suggested by CME on Discord):
```
d3d9.swvpFloatCount = 128
d3d9.swvpIntCount = 16
d3d9.swvpBoolCount = 16
```

### Software information
[TrackMania Nations Forever](https://store.steampowered.com/app/11020/TrackMania_Nations_Forever)
32-bit
TmForever.exe
[Very high preset with AA off & 16x Anisotropic filtering](https://user-images.githubusercontent.com/26440060/106263105-3c99f700-6224-11eb-9a97-fe5071a58097.png)

### System information
- GPU: NVIDIA GeForce GTX 1660 SUPER
- Driver: 455.50.04
- Wine version: 5.13 (Proton)
- DXVK version: 1.7.3

### Apitrace file(s)
[Apitrace with Proton & DXVK](https://www.dropbox.com/s/ey2ozlrdme36arm/TmForever.zst?dl=1)

### Log files
[TmForever_d3d9.log](https://github.com/doitsujin/dxvk/files/5893303/TmForever_d3d9.log)

**Comment by Iglu47** [comment]
It looks like `d3d9.swvpFloatCount = 128` is causing some problem. Trackmania player ghost is dark/black now.
![tmf](https://user-images.githubusercontent.com/25866099/110462412-b655b800-80e1-11eb-8505-0200698fbb74.png)
left - build from site. right - local build with revert  https://github.com/doitsujin/dxvk/commit/ff9d451a4e823904540b3618461b429575f398dc

I found that similar is used for another 32 bit game, but it doesn't use such a small value: https://github.com/doitsujin/dxvk/blob/787297ee4e46ccf8e4f6da39d37c8d2742b0359f/src/util/config/config.cpp#L271
@CME42 advised me to increase the value to `256` and with him there is no such problem anymore.

I did some tests and found that the value `256` also causes a slight drop in performance.
gtx 1080ti on 455.50.10 driver version
`d3d9.swvpFloatCount = 128`: [`279`](https://github.com/doitsujin/dxvk/files/6108061/1.1.txt) [`279`](https://github.com/doitsujin/dxvk/files/6108068/1.2.txt) `279` `280` [`279`](https://github.com/doitsujin/dxvk/files/6108071/1.5.txt)  `278` [`280`](https://github.com/doitsujin/dxvk/files/6108073/1.7.txt) (~279,14±0,81 fps)
`d3d9.swvpFloatCount = 256`: `276` [`277`](https://github.com/doitsujin/dxvk/files/6108079/2.2.txt) `276` [`276`](https://github.com/doitsujin/dxvk/files/6108083/2.4.txt) `278` `278` [`278`](https://github.com/doitsujin/dxvk/files/6108085/2.7.txt) (~277,00±1,02 fps)
~`-0,7677%` (**but there must still be an Observational error)
Also I did additional tests with `d3d9.swvpFloatCount = 256` `d3d9.swvpIntCount = 32` `d3d9.swvpBoolCount = 32`:
`275` `278` `277` `278` `276` `277` `276` (~276,71±1,10 fps)
this gives a slightly more performance loss (but it is so small also that it may be an Observational error), so it looks likes only increase `d3d9.swvpFloatCount` be preferable.

`d3d9.swvpFloatCount = 192` still causes the described problem as with `128`
