### ISSUE TITLE
[d3d9] Cubic Castles fails to create DX9 device

### ISSUE THREAD

**Issue by flgx16** [doitsujin/dxvk#1911]
The game tries to use `A2R10G10B10` when windowed and DXVK does not allow that. Removing `&& !Windowed` from [this check](https://github.com/doitsujin/dxvk/blob/v1.7.3/src/d3d9/d3d9_monitor.cpp#L41) lets the game launch. This game works with wined3d.

### Software information
[Cubic Castles](https://store.steampowered.com/app/317470/Cubic_Castles)
32-bit
Cubic.exe

### System information
- GPU: NVIDIA GeForce GTX 1660 SUPER
- Driver: 455.50.04
- Wine version: 5.13 (Proton)
- DXVK version: 1.7.3

### Apitrace file(s)
[Apitrace](https://www.dropbox.com/s/ulcxmuwc2l04cb9/Cubic.trace?dl=1)

### Log files
[Cubic_d3d9.log](https://github.com/doitsujin/dxvk/files/5893826/Cubic_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Please try with this, (or latest master)

[dxvk-format-exposure.tar.gz](https://github.com/doitsujin/dxvk/files/5936526/dxvk-format-exposure.tar.gz)

**Comment by flgx16** [comment]
It works now, thanks
