### ISSUE TITLE
[d3d11] Just cause 4 texture flickering

### ISSUE THREAD

**Issue by MoeezHyper** [doitsujin/dxvk#1915]
### Software information
Just cause 4 weird texture flickering issue tried it on max settings as well as low settings.

### System information
- GPU: AMD Radeon RX 580
- Driver: 21.1.1
- DXVK version: 1.7.3

### Log files
D3D11
[JustCause4_d3d11.log](https://github.com/doitsujin/dxvk/files/5900482/JustCause4_d3d11.log)

DXDI
[JustCause4_dxgi.log](https://github.com/doitsujin/dxvk/files/5900483/JustCause4_dxgi.log)

### Screenshots
![2021 02 01-00 22](https://user-images.githubusercontent.com/78319617/106395369-c5cb4c80-6423-11eb-8302-1f07f217b3e4.png)
![2021 02 01-00 23](https://user-images.githubusercontent.com/78319617/106395371-c8c63d00-6423-11eb-87e5-64cd3e259351.png)

**Comment by doitsujin** [comment]
apitrace?

**Comment by aufkrawall** [comment]
Happens also on Linux with RDNA2 cards and amdvlk-pro driver, whereas amdvlk-open is fine. So I think this can be closed (and ideally reported to amdvlk bug tracker).
