### ISSUE TITLE
Metal Gear Solid V The Phantom Pain got crash

### ISSUE THREAD

**Issue by numity** [doitsujin/dxvk#1916]
MGSV got crashed at start up.
I've tried to reinstall the game, change install location, disable geforce experience, make the game runs as administrator, still not working.

**Software information**
Metal Gear Solid V The Phantom Pain

**System information**
GPU: RTX 3080
Driver: the latest driver 461.40
Wine version: N/A windows 10 64bit
DXVK version: Latest from master  dxvk-1.7.3

**Log files**
mgsvtpp_d3d11.log : [mgsvtpp_d3d11.log](https://github.com/doitsujin/dxvk/files/5906152/mgsvtpp_d3d11.log)
mgsvtpp_dxgi.log : [mgsvtpp_dxgi.log](https://github.com/doitsujin/dxvk/files/5906157/mgsvtpp_dxgi.log)

Please help!

**Comment by K0bin** [comment]
Just play the game with regular D3D11. On Nvidia hardware that's almost always faster than using DXVK.

**Comment by numity** [comment]
> Just play the game with regular D3D11. On Nvidia hardware that's almost always faster than using DXVK.

I have reason to use dxvk. I want to play with vulkan so I can use reshade with the game

**Comment by K0bin** [comment]
ReShade supports D3D11 just fine.

**Comment by numity** [comment]
> ReShade supports D3D11 just fine.

in this case this game doesn't work with reshade at all. always crash, there are a lot of people try RTGI shader with this game through dxvk, that's why I want to use it.

**Comment by doitsujin** [comment]
The game works fine on Linux. Either use that or stick to native D3D11.
