### ISSUE TITLE
Planet Zoo crash at start... again.

### ISSUE THREAD

**Issue by Galcian79** [doitsujin/dxvk#1917]
Since Planet Zoo was updated some days ago, it crashes again at start with C++ Runtime Library error. 
I remember on first start it complained nvidia drivers were too old, but worked. Now it crashes most of the times.

Most relevant info from the log: VK_ERROR_DEVICE_LOST

[https://drive.google.com/file/d/1wcMBoBeJzBe7TZX_F07ykdxg8kdsNxOx/view?usp=sharing](url)

System info: Proton-5.13-5, DXVK-1.7.3-28-g8163eb41, GTX 1060 6GB driver version 460.32.03-1

**Comment by doitsujin** [comment]
Nvidia driver is crashing for some reason, can't really debug that.

**Comment by Galcian79** [comment]
I managed to manually edit the game config file, resetting it to borderless window. Now it works, the only issue is the underside desktop bar stays on screen. So the crash happens only when fullscreen is set.

**Comment by doitsujin** [comment]
Can you please try to record an apitrace?

**Comment by Galcian79** [comment]
> Can you please try to record an apitrace?

I did an apitrace the Valve way.
Hope it helps.
[https://drive.google.com/file/d/1Nn3oWta7u-zmLplee6-2zBuU_Ds-GTIQ/view?usp=sharing](url)

**Comment by ZereoX** [comment]
For added visibility, the issue does not appear to affect Turing-based GPUs (1660ti), but reproduces consistantly on **Maxwell** and **Pascal** (GTX 960 & 1060). The title either hangs on a black screen upon reaching the main, or in the rare ocassioned it got past, would render at ~5 FPS (confirmed on both Proton 5.13-5 and Windows when using DXVK).


https://user-images.githubusercontent.com/761853/107223052-b4fe7600-69e3-11eb-9289-c14e2fb85cba.mp4

**Comment by Galcian79** [comment]
Best way to workaround this is to set the game to borderless window and enable virtual desktop in winecfg.

**Comment by Galcian79** [comment]
> For added visibility, the issue does not appear to affect Turing-based GPUs (1660ti), but reproduces consistantly on **Maxwell** and **Pascal** (GTX 960 & 1060). The title either hangs on a black screen upon reaching the main, or in the rare ocassioned it got past, would render at ~5 FPS (confirmed on both Proton 5.13-5 and Windows when using DXVK [master and older releases]).
> 
>  Planet.Zoo.-.703080.-.GTX.960.Performance.mp4

It seems the same issue has been reported on rtx2060 on protondb
https://www.protondb.com/app/703080

**Comment by Blisto91** [comment]
@Galcian79 Friendly ping. Are you still having this issue with latest proton and drivers?

**Comment by Galcian79** [comment]
> @Galcian79 Friendly ping. Are you still having this issue with latest proton and drivers?

Dear friend, i'm Leprotto and no i switched to RDNA2 about one year ago 😂
