### ISSUE TITLE
Uninstall issue

### ISSUE THREAD

**Issue by xuijuthub** [doitsujin/dxvk#1918]
Hi.
1) Installed dxvk following a guide trying to make chromium work on wine via winetricks dxvk_install iirc.
2) Did not work -> virtual display enabled, did not work.
3) Had a need to install SumatraPDF, get this error:
`0168:err:vulkan:get_vulkan_driver Wine was built without Vulkan support.
0168:err:vulkan:wine_vk_init Failed to load Wine graphics driver supporting Vulkan.
0168:err:module:LdrInitializeThunk "winevulkan.dll" failed to initialize, aborting
0168:err:module:LdrInitializeThunk Initializing dlls for L"Z:\\home\\user\\SumatraPDF-3.2-64-install.exe" failed, status c0000142`
For a fact I know I do not have vulkan, had no idea what was dxvk and that vulkan is tied to it until now.
Running `WINEPREFIX=/home/user/.wine ./setup_dxvk.sh uninstall`
Get `wine: configuration in L"/home/user/.wine" has been updated.
/home/user/x64/dxgi.dll: File not found. Skipping.
/home/user/x32/dxgi.dll: File not found. Skipping.
/home/user/x64/d3d9.dll: File not found. Skipping.
/home/user/x32/d3d9.dll: File not found. Skipping.
/home/user/x64/d3d10.dll: File not found. Skipping.
/home/user/x32/d3d10.dll: File not found. Skipping.
/home/user/x64/d3d10_1.dll: File not found. Skipping.
/home/user/x32/d3d10_1.dll: File not found. Skipping.
/home/user/x64/d3d10core.dll: File not found. Skipping.
/home/user/x32/d3d10core.dll: File not found. Skipping.
/home/user/x64/d3d11.dll: File not found. Skipping.
/home/user/x32/d3d11.dll: File not found. Skipping.`
Note: it is not the first time I run the uninstaller.
Trying to run SumatraPDF installer again, does not work, same error.
winecfg removed dxvk library override, disabled virtual desktop -> same error.
How do I get original drivers back? I create new wine prefix and it works, but restoring original is preferred.

Either instructions are not clear (should include step for restoration), or uninstaller does not do a good job.
Aside from this, project itself seems very promising, big thumbs up!:)

**Comment by doitsujin** [comment]
You need to run the script from a directory that actually contains the DXVK files, which yours does not for whatever reason, which leads me to believe that you probably didn't install it with the script to begin with which also means that the uninstaller will not work.

Just create a fresh wine prefix to save everyone a big headache.

**Comment by xuijuthub** [comment]
Yes it was installed with winetricks and I have no idea where it placed the files.
Just assumed script should work wherever it is runned from as it is reading which wineprefix to work on. (Also found script linked to this hub in forum where someone was being guided trying to uninstall.)

OK, will recreate wine prefix then.
