### ISSUE TITLE
Install missing folders

### ISSUE THREAD

**Issue by Yabbo** [doitsujin/dxvk#1919]
i did a git clone of the repo and when i run the installer its looking for x32 and x64 directories inside the git repo which dont exist.

 ./setup_dxvk.sh install                                                                                                                                            ✔
wine: configuration in L"/home/yabbo/.wine" has been updated.
wine: configuration in L"/home/yabbo/.wine" has been updated.
/home/yabbo/dxvk/x64/dxgi.dll: File not found. Skipping.
/home/yabbo/dxvk/x32/dxgi.dll: File not found. Skipping.
/home/yabbo/dxvk/x64/d3d9.dll: File not found. Skipping.
/home/yabbo/dxvk/x32/d3d9.dll: File not found. Skipping.
/home/yabbo/dxvk/x64/d3d10core.dll: File not found. Skipping.
/home/yabbo/dxvk/x32/d3d10core.dll: File not found. Skipping.
/home/yabbo/dxvk/x64/d3d11.dll: File not found. Skipping.
/home/yabbo/dxvk/x32/d3d11.dll: File not found. Skipping.

**Comment by ZachBacon** [comment]
So... You cloned the project and tried to install it, before building the project?

**Comment by Joshua-Ashton** [comment]
Use ./package_release.sh to actually build the project then run the setup in that.
