### ISSUE TITLE
Vulkan 1.1 support?

### ISSUE THREAD

**Issue by romulasry** [doitsujin/dxvk#192]
https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html

**Comment by Kerrung** [comment]
No
https://github.com/roderickc/wine-vulkan/issues/18
https://github.com/roderickc/wine-vulkan/issues/14

**Comment by doitsujin** [comment]
Vulkan 1.1 is not yet availabe in wine and it's not even needed.
