### ISSUE TITLE
global ban for no reason

### ISSUE THREAD

**Issue by geiaaa** [doitsujin/dxvk#1920]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
Preferably record the trace on Windows, or wined3d if possible.

**Reports with no log files will be ignored.**

### Software information
Name of the game, settings used etc.

### System information
- GPU:
- Driver:
- Wine version: 
- DXVK version: 

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:
- Hello.I am writing this letter to you in order to tell you tha I have been global permanent ban while I was playing gta rp onnew generation 2 server and my game crashed,I tried to re join and a window appeard on my screen and it was telling me tha I have been permanent ban for:hacker please help

**Comment by K0bin** [comment]
The readme clearly warns that this could happen. 

> ## Online multi-player games
> Manipulation of Direct3D libraries in multi-player games may be considered cheating and can get your account banned. This may also apply to single-player games with an embedded or dedicated multiplayer portion. Use at your own risk.

https://github.com/doitsujin/dxvk#online-multi-player-games
