### ISSUE TITLE
[d3d11] Mega Man Legacy Collection 2 Mangled Screen

### ISSUE THREAD

**Issue by Kontrabant** [doitsujin/dxvk#1922]
The game screen is split diagonally, with the upper left displaying part of the image backwards, while the lower right is garbage.  Looking at the title screen in Renderdoc, the image is drawn correctly to the internal framebuffer, things become mangled during the final renderpass when the internal framebuffer is drawn to the swapchain image.

Internal FB0 after color pass 1
![Screenshot from 2021-02-07 17-03-37](https://user-images.githubusercontent.com/547897/107160811-88584900-6966-11eb-8ee9-db2b62be6f92.png)

Swapchain image after color pass 3
![Screenshot from 2021-02-07 17-04-07](https://user-images.githubusercontent.com/547897/107160824-95753800-6966-11eb-9c84-82b2d96cf56c.png)

### Software information
Mega Man Legacy Collection 2 (default settings)

### System information
- GPU: NVIDIA Geforce GTX 960
- Driver: 460.39
- Wine version: 6.0-staging
- DXVK version: 1.7.3

### Apitrace file(s)
Apitrace (recorded on Windows):
https://drive.google.com/file/d/1ycUI6pVVTLvOwJ1c5jAgtLJfKKLfKyuy/view?usp=sharing

Renderdoc captures:
https://drive.google.com/file/d/1dltq6yndWdMm2TcPRNbNssK4blVvrchh/view?usp=sharing

### Log files
- d3d11.log:
[MMLC2_d3d11.log](https://github.com/doitsujin/dxvk/files/5940102/MMLC2_d3d11.log)

**Comment by doitsujin** [comment]
Thanks for the trace, was just an oversight because no one ever uses two-byte formats for vertex input.
