### ISSUE TITLE
banned in team fortress 2

### ISSUE THREAD

**Issue by BigFatHairyGamer** [doitsujin/dxvk#1923]
hello developer!

i recently got VAC (VALVE anti cheat) banned in Team Fortress 2 and I was wondering if maybe dxvk could be the cause?
i will admit, i was using lmaobox but that doesn't get detected by VAC and i was only banned after i started using dxvk with 

maybe you should look into that you can get banned for dxvk in Valve anti cheat? is this a known issue? i would expect it should be if this is a VALVe project.

also if you can unban me please that would be great if anyone at VALVe sees this but i know its a long shot

thank you for the project :)

**Comment by samzanemesis** [comment]
lmao

**Comment by Joshua-Ashton** [comment]
lmao
