### ISSUE TITLE
Many programs crash immediately with the Intel Windows driver

### ISSUE THREAD

**Issue by mirh** [doitsujin/dxvk#1924]
Just about every d3d9 program I could find (except the [most stupid](http://masm32.com/board/index.php?topic=7604.0) of samples) crashes if I disable my 950M from device manager. 
Normal d3d9, nor vkcube or basemarkgpu seems to be affected by this behaviour. 
Yes I have also verified the dxvk dll isn't getting hijacked like in #1904

### Software information
Just about everything, but the following log is from unigine sanctuary. 

### System information
- GPU: HD 520
- Driver: 27.20.100.9168
- Wine version: Windows 10
- DXVK version: 1.7.3

### Crash stack
```
Unigine.exe caused an Access Violation at location 14E938BA in module igvk32.dll Reading from location 00000004.

Registers:
eax=00000000 ebx=232cfdd8 ecx=00000000 edx=00000000 esi=232cfdd8 edi=00000000
eip=14e938ba esp=1d69fa80 ebp=1d69fabc iopl=0         nv up ei pl nz na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010206

AddrPC   Params
14E938BA 00000001 1D69FB30 1D69FC30  igvk32.dll!SetDriverStoreDir
14E935DD 232CFDD8 00000000 00000001  igvk32.dll!SetDriverStoreDir
624B00E3 00000001 00000000 158DE6E8  d3d9.dll!Direct3D9EnableMaximizedWindowedModeShim
624BED13 00000006 00000001 00000000  d3d9.dll!Direct3D9EnableMaximizedWindowedModeShim
62448F34 00000006 00000003 00000000  d3d9.dll!Direct3D9EnableMaximizedWindowedModeShim
62447959 62555370 62555388 0ABB7BAC  d3d9.dll!Direct3D9EnableMaximizedWindowedModeShim
62555388 0ABB7BA8 BDF61EA0 00000000  d3d9.dll!Direct3D9EnableMaximizedWindowedModeShim
777875F4 FFFFFFFF 777A735F 00000000  ntdll.dll!__RtlUserThreadStart
777875C4 62555370 0ABB7BA8 00000000  ntdll.dll!__RtlUserThreadStart@8
```

**Comment by K0bin** [comment]
Intels Vulkan driver on Windows is notoriously bad. DXVK works fine on Intel GPUs on Linux.

**Comment by doitsujin** [comment]
I mean you could always try running these demos with Vulkan validation layers enabled to see if we're hitting some weird edge case on Intel's Windows driver (also, for the love of god, please post log files as requested by the issue template, why does nobody do that anymore?), but we have no plans to support it.

**Comment by mirh** [comment]
Because I thought this problem was unrelated and preceding any actual operation with the vulkan driver itself. 
Indeed, I have been fiddling with vkconfig for the past 10 minutes, and even if I enable every validation area the log isn't any longer than the normal one by dxvk. 

[Unigine_d3d9_intel.log](https://github.com/doitsujin/dxvk/files/5944873/Unigine_d3d9_intel.log)
[Unigine_d3d9_nvidia.log](https://github.com/doitsujin/dxvk/files/5944874/Unigine_d3d9_nvidia.log)

Though I guess I was also misdiagnosing the problem too, now that I tried to force the intel gpu from the nvidia control panel.

**Comment by doitsujin** [comment]
To be clear, validation layer output would **not** be inside the DXVK logs, but rather in stdout (i.e. console output), or a separate file if you instruct the layer to dump it somewhere (should also be doable with vkconfig).

**Comment by mirh** [comment]
Yes, the logs I have attached are dxvk's. 
I'm just saying the ones from the vulkan configurator don't contain any additional information besides that.

**Comment by doitsujin** [comment]
Nothing for us to fix here then.

**Comment by mirh** [comment]
I very much suspect you are missing some d3d9 entry point.. 
https://github.com/apitrace/apitrace/issues/704

**Comment by K0bin** [comment]
If some part of the Intel driver stack or any other Windows component calls undocumented D3D9 apis, that's not our problem.

**Comment by mozo78** [comment]
@mirh
Windows -> closed source -> it's your choice. Happy using :)
