### ISSUE TITLE
Deus Ex: Human Revolution - Director's Cut doesn't work with D3D11

### ISSUE THREAD

**Issue by jqadev** [doitsujin/dxvk#1925]
### Software information
Deus Ex: Human Revolution - Director's Cut on Proton 5.13-6 works only with D3D9 and there is a black screen with D3D11.
This issue doesn't exist on Proton 5.0-10.
When D3D9 is selected then my dedicated and integrated GPU's models are correctly recognized in opposite to D3D11. 

### System information
- GPU: Nvidia 930MX (notebook)
- Driver: 460.32.03
- Proton 5.13-6
- DXVK version: v1.7.3-37-g3f91cdbc

### Log files
- d3d9.log: [d3d9-steam-238010.log](https://github.com/doitsujin/dxvk/files/5976695/d3d9-steam-238010.log)
![d3d9-settings-1](https://user-images.githubusercontent.com/20422423/107863994-96bbce80-6e58-11eb-9ae0-a0d2ec6ca37d.png)
![d3d9-settings-2](https://user-images.githubusercontent.com/20422423/107863999-97ecfb80-6e58-11eb-9f45-ff8db05bf18c.png)
- d3d11.log: [d3d11-steam-238010.log](https://github.com/doitsujin/dxvk/files/5976696/d3d11-steam-238010.log)
![d3d11-settings-1](https://user-images.githubusercontent.com/20422423/107863996-97ecfb80-6e58-11eb-9520-e527762c2106.png)
![d3d11-settings-2](https://user-images.githubusercontent.com/20422423/107863998-97ecfb80-6e58-11eb-9b6f-1fdda8d302ad.png)

**Comment by doitsujin** [comment]
Are you sure this is a DXVK issue? The game is known to [work fine](https://www.protondb.com/app/238010) with Proton 5.13-5, which uses the exact same DXVK version as 5.13-6 minus some Nioh 2 workaround whcih doesn't affect this game.

**Comment by jqadev** [comment]
Thank you! `WINEDLLOVERRIDES=dxgi=n %command%` solved the problem.
