### ISSUE TITLE
win\linux pip not working in window game mode

### ISSUE THREAD

**Issue by shikulja** [doitsujin/dxvk#1929]
In windowed mode, browser pip (opera) does not work on top of the game.

The same problem was on both windows and linux

### Software information
WOW (2004)  Maximize window mode
Win10 х64\Zorin 15.3

### System information
- GPU: rx580
- Driver: lastest
- DXVK version:  1.7.3

**Comment by doitsujin** [comment]
I don't have the slightest idea what you're actually trying to do, but in fullscreen mode (including borderless fullscreen) we're requesting the window to be on top of all others, which is necessary for it to actually cover stuff like the task bar. That's not a bug though, the alternative would be broken fullscreen mode.

**Comment by shikulja** [comment]
@doitsujin 
I just need normal mode so that dxvk does not overlap windows.
So that I can watch PIP videos from the browser while playing wow\hots
Also in windowed mode, switching resolution, crashes the game.

**Comment by doitsujin** [comment]
Well then don't use fullscreen mode if you want overlapping windows? I still don't understand your problem.

Also, no logs or anything else that could be useful, but I guess expecting people to spend 30 seconds to even *read* the issue template is too much at this point.

**Comment by shikulja** [comment]
@doitsujin 
I am not using fullscreen mode. I use "Maximize window mode" in the game settings
That is, dxvk overrides the browser pip in this mode
I read that logs are needed. I didn't think that log would say anything for this task. I'll try to attach.

**Comment by doitsujin** [comment]
and what does "maximize window" mean exactly? Borderless fullscreen mode?

**Comment by shikulja** [comment]
![WoWScrnShot_021721_185322](https://user-images.githubusercontent.com/3386359/108230245-9caff900-7151-11eb-8ed9-ddfa3337e5b2.png)

[WoW_d3d9 not working pip mode.zip](https://github.com/doitsujin/dxvk/files/5996901/WoW_d3d9.not.working.pip.mode.zip)

**Comment by shikulja** [comment]
[WoW_d3d9 crush changing resolution in windows mode.zip](https://github.com/doitsujin/dxvk/files/5996903/WoW_d3d9.crush.changing.resolution.in.windows.mode.zip)

**Comment by shikulja** [comment]
it should be like this: but pip is not there with dxvk

![image](https://user-images.githubusercontent.com/3386359/108231642-01b81e80-7153-11eb-9ac9-caace126c3f5.png)

**Comment by wu-yue** [comment]
I don't know if you are using Linux.

JFYI, I play WoW Classic on Debian GNOME, and I need Input Method window to pop up, so I can communicate.

After GNOME 3.38, GNOME won't do window composing for full-screen window, they say it would improve performance. Something called Unredirect Fullscreen Window.

However this would make any window else can not show up in front of the game window.

The solution is to disable this function, I do this with a GNOME extension: https://extensions.gnome.org/extension/1873/disable-unredirect-fullscreen-windows/

**Comment by shikulja** [comment]
Yes I played on linux, but mostly on windows
This problem exists on both systems, this problem occurs not only in wow, but also in the new heroes of the storm
This problem affects not only the pip browser, but all video players that play videos over windows.

Yes I played on linux, but mostly on windows
This problem exists on both systems, this problem occurs not only in wow, but also in the new heroes of the storm
This problem affects not only the pip browser, but all video players that play videos over windows.

**Comment by SveSop** [comment]
@shikulja 
[https://us.forums.blizzard.com/en/wow/t/wow-classic-crashes-whenever-i-change-to-windowed-mode/245863/28](https://us.forums.blizzard.com/en/wow/t/wow-classic-crashes-whenever-i-change-to-windowed-mode/245863/28)
This mentions problems with things like "discord overlay" with WoW classic.

Not exactly your problem, but it seems as one can "force" WoW to start with `-windowed` mode... Maybe the ingame option "windowed mode - maximized" dont really do what you think? :) (Would not be the first time blizzard settings is a bit ambiguous).

**Comment by Blisto91** [comment]
@shikulja Friendly ping. Do you still have this issue?

**Comment by wu-yue** [comment]
I switched to XFCE desktop here, and everything works normally, even I switch on Display Full screen Window directly in Xfwm compositor settings. I could see CJK input method window during WoW. Didn’t try PiP.
________________________________
发件人: Blisto91 ***@***.***>
发送时间: Tuesday, August 30, 2022 7:40:17 PM
收件人: doitsujin/dxvk ***@***.***>
抄送: Wu Yue ***@***.***>; Comment ***@***.***>
主题: Re: [doitsujin/dxvk] win\linux pip not working in window game mode (#1929)


@shikulja<https://github.com/shikulja> Friendly ping. Do you still have this issue?

―

**Comment by shikulja** [comment]
@Blisto91 
Yes, on new builds, everything is still the same.
The windows overlap each other, because of this pip is not possible. Maybe this is justified, but I would like to have at least an option to get 1-in-1 windows working.

**Comment by shikulja** [comment]
https://github.com/doitsujin/dxvk/issues/2640

**Comment by Joshua-Ashton** [comment]
Not really fixable on our side without breaking apps. Best there is is d3d9 dialog mode or the already disable full screen exclusive in d3d11.
