### ISSUE TITLE
DXVK_HUD not appearing.

### ISSUE THREAD

**Issue by neilm-fourjs** [doitsujin/dxvk#1932]
I'm running Kubuntu 20.04 LTS with NVidia drivers.
Using Steam Proton experimental to run cyberpunk 2077.
It runs but I wanted to enable DXVK_HUD, so far I've tried.
Adding it my .profile
Adding it to the steam command setting for the game, ie: DXVK_HUD=1 %command%
Adding it the user_settings.py in ~/.steam/steam/steamapps/common/Proton - Experimental
But I still don't see any hud when the game runs.

Any ideas why not ?

**Comment by Oschowa** [comment]
Cyberpunk runs on d3d12, so DXVK isn't used and you can't enable the HUD.
