### ISSUE TITLE
Warzone VK_KHR_surface not supported

### ISSUE THREAD

**Issue by PauloKim1246** [doitsujin/dxvk#1933]
apitrace log was blank

### Software information
Call Of Duty: Warzone (Modern Warfare 2019)

### System information
- GPU: GTX 1050
- Driver: 27.21.14.6089
- Windows 10
- DXVK version: v1.8 

### Log files
- d3d11.log: No log

- dxgi.log:
[ModernWarfare_dxgi.log](https://github.com/doitsujin/dxvk/files/6015575/ModernWarfare_dxgi.log)

**Comment by K0bin** [comment]
> info:  Required Vulkan extension VK_KHR_surface not supported

That indicates that there's an issue with your graphics driver. It's not installed correctly.

Also, CoD MW (and Warzone) uses D3D12.

**Comment by doitsujin** [comment]
Yeah, wrong API + also it's a setup issue on your end, not a bug.

**Comment by PauloKim1246** [comment]
You can force run on DX11 on the launch arguments.

**Comment by PauloKim1246** [comment]
> Yeah, wrong API + also it's a setup issue on your end, not a bug.

You can force the game to run on DX11 on the launch arguments.
cant see whats wrong with my setup, updated driver and everything.
