### ISSUE TITLE
GTA IV Mapping memory failed

### ISSUE THREAD

**Issue by Luis-Douet** [doitsujin/dxvk#1935]
Hi,

This seems to be related to issue #1318 and #1556 but I am not sure. After the game loads up from a save and you try to leave your safe-house, the game crashes immediately. I have the game installed in a 64-Bit wine prefix using Vulkan loader radeon_icd.x86_64.json. If I change the Vulkan loader to radeon_icd.i686.json, I am able to exit the safe-house but the game still crashes after 20-30 minutes. Disabling DXVK and using WineD3D results in no crashes.

**What I have tried**

- I have replicated this same issue with the (1.0.8.0 / 1.1.3.0) version of the game.

- Tried Wine TKG 5.19 and Wine Staging 6.2 with 32-Bit and 64-Bit prefixes but the game still crashes.

- Used DXVK 1.7.2 and 1.7.3 and the crash still occurs.

- Enable WINE_LARGE_ADDRESS_AWARE=1 which had no effect and the game crashes.

**Software information**

Grand Theft Auto IV: The Complete Edition (Version 1.0.7.0 / 1.1.2.0)

**In Game Settings**

Video Mode: 2560 x 1440 (144 Hz)
Texture Quality: High
Shadow Quality: Very High
Reflection Resolution: Very High
Water Quality: Very High
Texture Filter Quality: Anisotropic x16
Night Shadows: Off
View Distance: 100
Detail Distance: 100

**System information**

GPU: Radeon RX 580
Driver: Mesa 20.3.4 RADV ACO
Wine version: Wine TKG 6.2 (x64)
DXVK version: 1.8

**Apitrace file & Log files**

The trace and log files included are based on the Software information and System information above.

https://www.swisstransfer.com/d/8ad6f5e9-61d3-4e4a-8171-3889fa57782e

**Comment by K0bin** [comment]
Can you upload DXVK logs please? This very much sounds like issue 1318 but we'd need logs to confirm.

**Comment by Luis-Douet** [comment]
Apologies, are you referring to the d3d9.log generated by DXVK? It is in the link above with the traces.

**Comment by doitsujin** [comment]
Well yeah, it's known at this point that DXVK eats too much memory/address space, and no, we don't have a fix.

**Comment by Luis-Douet** [comment]
Should this issue be closed then?

**Comment by K0bin** [comment]
Closing because this is almost certainly #1318 again. Nothing we can do.
