### ISSUE TITLE
GTX 1050 & RX570 on COD:Modern Warfare 2019

### ISSUE THREAD

**Issue by PauloKim1246** [doitsujin/dxvk#1936]
apitrace is blank

### Software information
Call Of Duty:Modern Warfare 2019
### **YOU CAN RUN THE GAME ON DX11 BY USING THE -D3D11 ARGUMENT**

We tested with 2 GPU's

### System information 1
- GPU: GTX 1050 2GB
- Driver: 27.21.14.6089
- Windows 10
- DXVK version: v1.8

### Log files 1
- dxgi.log:[ModernWarfare_dxgi (2).log](https://github.com/doitsujin/dxvk/files/6019391/ModernWarfare_dxgi.2.log)

### System information 2
- GPU: RX570
- Driver: 20.45.33.01-210127a-363700E-RadeonSoftwareAdrenalin2020
- Windows 10
- DXVK version: v1.8

### Log files 2
- dxgi.log:[ModernWarfare_dxgi_2.log](https://github.com/doitsujin/dxvk/files/6019393/ModernWarfare_dxgi_2.log)

**Comment by K0bin** [comment]
Same thing as with your previous issue #1933.
