### ISSUE TITLE
Guild Wars 2: Window Switching Behaviour Regression

### ISSUE THREAD

**Issue by konomikitten** [doitsujin/dxvk#1937]
When using DXVK 1.7.3 alt-tabing away from the game window when the game is in Full Screen results in the game window moving to the background as you'd expect. But doing so on on DXVK 1.8 results in the window minimizing instead of just moving to the background as it did in the previous version.

### Software information
Guild Wars 2

### System information
- GPU: GeForce GTX 960
- Driver: 455.50.04
- Wine version: lutris-5.7-11-x86_64
- DXVK version: 1.7.3 and 1.8

### Apitrace file(s)
Will provide if needed.

### Log files for 1.7.3
- d3d9.log: [Gw2-64_d3d9.log](https://github.com/doitsujin/dxvk/files/6022413/Gw2-64_d3d9.log)

### Log files for 1.8
- d3d9.log: [Gw2-64_d3d9.log](https://github.com/doitsujin/dxvk/files/6022414/Gw2-64_d3d9.log)

**Comment by Joshua-Ashton** [comment]
This is not a regression and matches behaviour on Windows.

If you want the old behaviour, revert https://github.com/doitsujin/dxvk/commit/59816a71b95564426c43c05cbe193c53f986f454 or play in borderless windowed.

**Comment by konomikitten** [comment]
What an annoying behaviour, verified on Windows myself thanks for your time.
