### ISSUE TITLE
Windows 10: Guildwars2 Crash with Version 1.8

### ISSUE THREAD

**Issue by WanYaa** [doitsujin/dxvk#1939]
Hi 
under Windows 10 the new version 1.8 crashes with 

--> Crash <--
Exception: c0000005
Memory at address 00000000`00000020 could not be read
App: Gw2-64.exe 
Pid: 10540
BaseAddr: 00007FF634370000
ProgramId: 101
Build: 111959
Module: nvoglv64.dll
.......
*--> Error Logs <--*
17:48:39Z More than one view in the "ui_LoadingInfo" addon have the id ""; ids must be unique.

previous version 1.7.3 works fine

**Comment by DxCx** [comment]
I can confirm i have the same issue

**Comment by mozo78** [comment]
I can confirm - this is a Linux project.

**Comment by doitsujin** [comment]
Try current master, 1.8 has a D3D9 regression that is already fixed.

**Comment by hk3wx** [comment]
I'm having the same issue.

**Comment by DxCx** [comment]
> Try current master, 1.8 has a D3D9 regression that is already fixed.

Thanks @doitsujin ! Using latest master (https://haagch.frickel.club/files/dxvk/r3546.5e55ced8/) fixed the crush
