### ISSUE TITLE
Crash repport at Fusion 360 launch

### ISSUE THREAD

**Issue by gillg** [doitsujin/dxvk#194]
When I run Fusion360 application, I get an error on a sub component.

I ran ```wineprefix/Fusion360/drive_c/users/guigi/Local\ Settings/Application\ Data/Autodesk/webdeploy/production/6a0c9611291d45bb9226980209917c3d/FusionLauncher.exe```

It lanches fusion, but it load an external exe component (AdCefWebBrowser.exe) and it make a crash repport. Fusion 360 continue to start, but some functionnalities are broken.

Crash report concern :
C:/users/xxxxxx/Local\ Settings/Application\ Data/Autodesk/webdeploy/production/8556a3e1d81f6c5f0bca3f1440fbfa311d80a809/WIN64/AdCefWebBrowser.exe

Last running logs before report.

```
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkGetPhysicalDeviceDisplayPropertiesKHR".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkGetPhysicalDeviceDisplayPlanePropertiesKHR".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkGetDisplayPlaneSupportedDisplaysKHR".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkGetDisplayModePropertiesKHR".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkCreateDisplayModeKHR".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkGetDisplayPlaneCapabilitiesKHR".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkCreateDisplayPlaneSurfaceKHR".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkCreateSharedSwapchainsKHR".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkGetPhysicalDeviceSurfaceCapabilities2KHR".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkGetPhysicalDeviceSurfaceFormats2KHR".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkCreateDebugReportCallbackEXT".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkDestroyDebugReportCallbackEXT".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkDebugReportMessageEXT".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkDebugMarkerSetObjectTagEXT".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkDebugMarkerSetObjectNameEXT".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkGetPhysicalDeviceExternalImageFormatPropertiesNV".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkGetDeviceGroupSurfacePresentModesKHX".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkGetPhysicalDevicePresentRectanglesKHX".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkEnumeratePhysicalDeviceGroupsKHX".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkGetPhysicalDeviceExternalBufferPropertiesKHX".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkGetPhysicalDeviceExternalSemaphorePropertiesKHX".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkGetPhysicalDeviceGeneratedCommandsPropertiesNVX".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkReleaseDisplayEXT".
0030:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkGetPhysicalDeviceSurfaceCapabilities2EXT".
info:  Intel(R) HD Graphics 520 (Skylake GT2):
info:    Driver: 17.2.8
info:    Vulkan: 1.0.54
0030:fixme:wbemprox:enum_class_object_Next timeout not supported
0030:fixme:win:EnumDisplayDevicesW ((null),0,0x23e090,0x00000000), stub!
0030:fixme:d3d9:Direct3DShaderValidatorCreate9 stub
warn:  D3D11Device::QueryInterface: Unknown interface query
warn:  6543dbb6-1b48-42f5-ab82-e97ec74326f6
0055:fixme:system:SystemParametersInfoW Unknown action: 116
```
I don't know if issue concern D3D11Device (so dxvk dlls ?) or d3d9:Direct3DShaderValidatorCreate9 (imlementation missing on d3d9)
If this bug concern your project I could make more tests and provide logs.

### Software information
Autodesk Fusion360, latest version (2.0.3803)

### System information
- GPU: Intel HD 520 (Skylake GT2)
- Driver: mesa 18.0.99
- Vulkan: 1.0.57
- Wine version: 3.4
- DXVK version: 0.31

### Wine trace output
- [basic_trace.log](https://github.com/doitsujin/dxvk/files/1845441/basic_trace.log)

### Apitrace file(s)
- [apitrace_dxvi.log](https://github.com/doitsujin/dxvk/files/1845404/apitrace_dxvi.log)

### Log files
- d3d11.log:
- dxgi.log:

**Comment by doitsujin** [comment]
A backtrace would be helpful

Also, please keep in mind that applications which mix d3d9 and d3d11 just won't work with dxvk, you'll need to use wined3d for those.

**Comment by Kerrung** [comment]
You use an unsupported version of Mesa 17.2, but at least 18.0 is required at minimum.

**Comment by gillg** [comment]
I updated my original cmment with new details. I updated mesa driver to 18.0.99, add apitrace log, but I can't add dxvk logs, because no files are generated... I checked on current foder and into app folder, all are writables, but nothing appear... I think my launcher not use d3d directly, d3d is used by sub processes...

In all cases, somthing seems interesting in apitrace :

```
491 ID3D11BlendState::Release(this = 0x157a3ce0) = 7
492 ID3D11RasterizerState::Release(this = 0x157a9260) = 3
493 ID3D11DepthStencilState::Release(this = 0x157a4080) = 7
494 ID3D11SamplerState::Release(this = 0x157a9340) = 49
495 ID3D11DeviceContext::Release(this = 0x157a14d0) = 6
496 ID3D11DeviceContext::ClearState(this = 0x157a49b0)
497 ID3D11DeviceContext::Release(this = 0x157a49b0) = 0
498 ID3D11Device::QueryInterface(this = 0x157a1330, riid = IID_ID3D11InfoQueue, ppvObj = ?) = E_NOINTERFACE
499 ID3D11VertexShader::Release(this = 0x157aa4a0) = 0
500 ID3D11PixelShader::Release(this = 0x157aa940) = 0
501 ID3D11Device::Release(this = 0x157a1330) = 3
502 ID3D11ClassLinkage::Release(this = 0x157aa420) = 0
503 ID3D11Device::Release(this = 0x157a1330) = 1
```

If you see an idea to enable dxvk logs don't hesitate...

**Comment by gillg** [comment]
Other thing, ```004a:err:ole:CoGetClassObject class {54e211b6-3650-4f75-8334-fa359598e1c5} not registered```, maybe a link with apitrace error on QueryInterface https://msdn.microsoft.com/en-us/library/windows/desktop/dn280396(v=vs.85).aspx

**Comment by gillg** [comment]
So, I made more tests and only one issue concern dxvk.

* ```{54e211b6-3650-4f75-8334-fa359598e1c5} not registered``` is about other thing (https://bugs.winehq.org/show_bug.cgi?id=44865)

* ```ID3D11Device::QueryInterface(this = 0x157a1330, riid = IID_ID3D11InfoQueue, ppvObj = ?) = E_NOINTERFACE```
```
0030:fixme:d3d9:Direct3DShaderValidatorCreate9 stub
warn:  D3D11Device::QueryInterface: Unknown interface query
warn:  6543dbb6-1b48-42f5-ab82-e97ec74326f6
```
I think, this concern dxvk.
I don't know why but this interface https://msdn.microsoft.com/en-us/library/windows/desktop/ff476538(v=vs.85).aspx seems fully not implemented... 

Do you think that it's possible to fix it ?

**Comment by doitsujin** [comment]
I honestly have no idea what the DirectManipulation thing is about. Doesn't seem to be related to D3D11 in any way though.

As for `ID3D11InfoQueue`, it's part of the D3D11 debug interfaces, and there should be no need for me to implement them. Applications should (and typically do) expect them to be unavailable.

**Comment by gillg** [comment]
Finally I summarise. DirectManipulation is definitely not related to directx. It could be solved using win 7 (implementation stat on win 8).

ID3D11InfoQueue is related to dxvk, but not blocking if not implemented.

So no real bug on dxvk :)
