### ISSUE TITLE
Any chances for Android?

### ISSUE THREAD

**Issue by RusJJ** [doitsujin/dxvk#1941]
Is there any chance for this? There's HL2 on Android that uses DX9 -> OGL -> GLES conversion. With a VERY POOR performance.

**Comment by doitsujin** [comment]
No.

**Comment by Joshua-Ashton** [comment]
Not like you could use it their, a developer would have to integrate it into their game.

Not to mention how bad Android vulkan implementations are...

**Comment by ThieuMinh26** [comment]
use turnip + zink
