### ISSUE TITLE
[DXVK 1.8] symlink install option reverses bits

### ISSUE THREAD

**Issue by rosettet** [doitsujin/dxvk#1942]
Using the symlink option links the 64bit dlls to system32 and the 32bit dlls to syswow64, games would not run before reversing this manually.

**Comment by Joshua-Ashton** [comment]
You are wrong.

**Comment by doitsujin** [comment]
https://www.howtogeek.com/326509/whats-the-difference-between-the-system32-and-syswow64-folders-in-windows/
