### ISSUE TITLE
Skyrim Special Edition: Rendering issues with menu spell effects

### ISSUE THREAD

**Issue by pajicadvance** [doitsujin/dxvk#1943]
The visuals seem to render correctly but they have artifacts over them. The artifacts are different every time the game is launched. See attached screenshots for examples.

### Software information
Skyrim Special Edition, Windows 10 20H2

### System information
- GPU: AMD Radeon RX 580
- Driver: 21.2.2
- DXVK version: 1.8 async

### Apitrace file(s)
- Was unable to generate the trace. Nothing happens when running the command from the issue template.

### Log files
- d3d11.log: https://paste.ee/p/dUYCQ
- dxgi.log: https://paste.ee/p/a1Fpy

### Screenshots
![Screenshot_4](https://user-images.githubusercontent.com/32738446/109228044-93fa9b00-77c1-11eb-90e4-41339a8c5cb0.png)
![Screenshot_1](https://user-images.githubusercontent.com/32738446/109228048-952bc800-77c1-11eb-9b7b-525ab7abf53e.png)
![Screenshot_2](https://user-images.githubusercontent.com/32738446/109228049-965cf500-77c1-11eb-85e8-528879b7d5b7.png)
![Screenshot_3](https://user-images.githubusercontent.com/32738446/109228053-96f58b80-77c1-11eb-9e7d-df05c1d6ab8a.png)

**Comment by doitsujin** [comment]
> DXVK version: 1.8 async

Please do not report bugs when using inofficial patches that are **known** to introduce all sorts or breakage.

Does this work on
- 1.8 from our release page
- 1.7.3 from our release page?

**Comment by pajicadvance** [comment]
> Please do not report bugs when using unofficial patches that are known to introduce all sorts or breakage.

Sorry about this, I was not aware that this is an unofficial build.

Interestingly enough, the issue is present in the 1.8 release, but in 1.7.3 it is not there.

1.8:

![1 8](https://user-images.githubusercontent.com/32738446/109239235-47b95600-77d5-11eb-83ee-2be11a733eaa.png)

logs:

[1.8_dxgi.log](https://github.com/doitsujin/dxvk/files/6046733/1.8_dxgi.log)
[1.8_d3d11.log](https://github.com/doitsujin/dxvk/files/6046735/1.8_d3d11.log)

1.7.3:

![1 7 3](https://user-images.githubusercontent.com/32738446/109239274-63246100-77d5-11eb-8ce3-3379d93a03cc.png)

logs:

[1.7.3_dxgi.log](https://github.com/doitsujin/dxvk/files/6046740/1.7.3_dxgi.log)
[1.7.3_d3d11.log](https://github.com/doitsujin/dxvk/files/6046741/1.7.3_d3d11.log)

**Comment by doitsujin** [comment]
I actually managed to reproduce this on AMDVLK locally, but yeah, seems like a driver bug.

**Comment by Blisto91** [comment]
Is this still a issue with the latest windows or amdvlk driver? 
I am not able to test myself but i see in the amdvlk issue Joshua made a dev asked for a retest of some of the issue and it was closed as fixed.

**Comment by pajicadvance** [comment]
> Is this still a issue with the latest windows driver or linux amdvlk driver? I am not able to test myself with newer than 2021Q2 but i see in the amdvlk issue Joshua made a dev asked for a retest of the issues and it was closed as fixed.

It is not an issue anymore, I completely forgot to close this issue, lol. Thanks for the reminder.

**Comment by Blisto91** [comment]
Yay great to hear!
