### ISSUE TITLE
TES-4 (Oblivion) permanent crash on quick save, BUT no any issues until F5 pressed (One hour test in game no issue with autosave or manual save via menu)

### ISSUE THREAD

**Issue by Bxaa** [doitsujin/dxvk#1945]
(!) The same thing happens with the default config.

info:  Game: Oblivion.exe
info:  DXVK: v1.8
info:  Found config file: dxvk.conf
info:  Effective configuration:
info:    dxgi.numBackBuffers = 3
info:    d3d9.floatEmulation = True
info:    d3d9.shaderModel = 3
info:    d3d9.deferSurfaceCreation = True
info:    d3d9.evictManagedOnUnlock = True
info:    d3d9.invariantPosition = True
info:    d3d9.samplerAnisotropy = 16
info:    d3d9.maxAvailableMemory = 4096
info:    d3d9.dpiAware = True
info:    dxvk.hud = compiler
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  GeForce GTX 1060 6GB:
info:    Driver: 461.40.0
info:    Vulkan: 1.2.155
info:    Memory Heap[0]: 
info:      Size: 6052 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 8125 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[8]: Property Flags = 0x6
info:      Memory Type[9]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[10]: Property Flags = 0x7
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  GeForce GTX 1060 6GB:
info:    Driver: 461.40.0
info:    Vulkan: 1.2.155
info:    Memory Heap[0]: 
info:      Size: 6052 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 8125 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[8]: Property Flags = 0x6
info:      Memory Type[9]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[10]: Property Flags = 0x7
info:  Process set as DPI aware
info:  Game: Oblivion.exe
info:  DXVK: v1.8
info:  Found config file: dxvk.conf
info:  Effective configuration:
info:    dxgi.numBackBuffers = 3
info:    d3d9.floatEmulation = True
info:    d3d9.shaderModel = 3
info:    d3d9.deferSurfaceCreation = True
info:    d3d9.evictManagedOnUnlock = True
info:    d3d9.invariantPosition = True
info:    d3d9.samplerAnisotropy = 16
info:    d3d9.maxAvailableMemory = 4096
info:    d3d9.dpiAware = True
info:    dxvk.hud = compiler
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  GeForce GTX 1060 6GB:
info:    Driver: 461.40.0
info:    Vulkan: 1.2.155
info:    Memory Heap[0]: 
info:      Size: 6052 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 8125 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[8]: Property Flags = 0x6
info:      Memory Type[9]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[10]: Property Flags = 0x7
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  GeForce GTX 1060 6GB:
info:    Driver: 461.40.0
info:    Vulkan: 1.2.155
info:    Memory Heap[0]: 
info:      Size: 6052 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 8125 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[8]: Property Flags = 0x6
info:      Memory Type[9]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[10]: Property Flags = 0x7
info:  Process set as DPI aware
info:  Device properties:
info:    Device name:     : GeForce GTX 1060 6GB
info:    Driver version   : 461.40.0
info:  Enabled device extensions:
info:    VK_EXT_4444_formats
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state
info:    VK_EXT_full_screen_exclusive
info:    VK_EXT_host_query_reset
info:    VK_EXT_memory_priority
info:    VK_EXT_robustness2
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_image_format_list
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_float_controls
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 0
info:    shaderStorageImageExtendedFormats      : 1
info:    shaderStorageImageReadWithoutFormat    : 0
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 0
info:  VK_EXT_4444_formats
info:    formatA4R4G4B4                         : 1
info:    formatA4B4G4R4                         : 1
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_extended_dynamic_state
info:    extendedDynamicState                   : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 1
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 0
info:    robustImageAccess2                     : 0
info:    nullDescriptor                         : 1
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 1
info:  DXVK: Read 453 valid state cache entries
info:  DXVK: Using 3 compiler threads
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              2880
info:      - Height:             1800
info:      - Format:             D3D9Format::X8R8G8B8
info:      - Auto Depth Stencil: true
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           false
info:  Setting display mode: 2880x1800@0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  2880x1800
info:    Image count:  2
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  2880x1800
info:    Image count:  3
info:    Exclusive FS: 0

**Comment by K0bin** [comment]
Please make an apitrace and provide the rest of the information that you deleted from the issue template.

**Comment by doitsujin** [comment]
Can you test current `master` as well? 1.8 has a known regression that can crash some D3D9 games.

**Comment by Bxaa** [comment]
Used https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace
(apitrace-latest-win32\lib\wrappers)
No crash with it on quick save with trace wrappers. Is it normal?
Trace:
https://drive.google.com/file/d/1LwdHFIc1VKtxEh_kQPNKz8HfH_EplZaT/view?usp=sharing

**Comment by doitsujin** [comment]
> And yes - no such issues with 1.7.3 and early versions

Yes, that's why I asked to do *current* master which already has a fix for the regression I mentioned. If you need a build, feel free to ask, I can always upload one.

**Comment by Bxaa** [comment]
Yes, dxvk is solvation for my projects
Full remasters:
https://www.nexusmods.com/newvegas/mods/69848
https://www.nexusmods.com/oblivion/mods/50381

**Comment by doitsujin** [comment]
Bit of a delay, but here you go. [dxvk-master.tar.gz](https://github.com/doitsujin/dxvk/files/6052626/dxvk-master.tar.gz)

**Comment by Bxaa** [comment]
Thanks, it worked perfectly and no strange stuttering like with 1.8 version, no crash on quick save.

(Q) Is it possible - use it with reshade? 
I tried to use asi injector, but reshade not load. I mean without enabling reshade globally for all vulkan api (if it enable it work fine)

**Comment by Joshua-Ashton** [comment]
I added support for Reshade for this, yes. I don't remember the environment variable though.

**Comment by Bxaa** [comment]
Do i need close this issue?

**Comment by Joshua-Ashton** [comment]
No.
