### ISSUE TITLE
[Question] Incompatible Graphic Card

### ISSUE THREAD

**Issue by Lucas559-noob** [doitsujin/dxvk#1946]
I have a Intel HD Graphics 4000 and it don't work for windows but for other devices it work, so if I use this, what happens to game? just a crash or it can break my pc?

**Comment by mozo78** [comment]
If you are using Linux the game will run. On Windows it shouldn't run because of the Intel drivers and your video card. That's it.

**Comment by K0bin** [comment]
The Intel HD 4000 does not support Vulkan.

**Comment by mozo78** [comment]
It support Vulkan on Linux via Mesa drivers. Intel are too lazy to support this GPU on Windows.

**Comment by K0bin** [comment]
Even with Mesa Vulkan support on anything older than Broadwell is incomplete and broken.
