### ISSUE TITLE
GTR2 rendering issue d3d9

### ISSUE THREAD

**Issue by mickski56** [doitsujin/dxvk#1947]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

With d3d9 after commit 338f6dfb0efe6536c5954ae0d6fba60809952da8 I see rendering issues, black areas in first screen grab, the second one is there for comparison.

![Grab_001](https://user-images.githubusercontent.com/35852605/109321232-d1563b80-7848-11eb-9994-18dcda613026.jpg)
![Grab_003](https://user-images.githubusercontent.com/35852605/109321241-d2876880-7848-11eb-908a-c8220f08b69a.jpg)

### Software information
Name of the game, settings used etc.
GTR2 d3d9
### System information
- GPU: nvidia 780ti
- Driver: nvidia binary 460.56
- Wine version: 6.2 staging
- DXVK version:  latest git db69ade7e7a7d460fef8893d8bb5c1922fa8ba64
- and a0cf5926d89a812b9932e793e34e036fe68c6230

### Apitrace file(s)
to follow if required

### Log files
- d3d9.log: 
[GTR2_d3d9.log](https://github.com/doitsujin/dxvk/files/6050711/GTR2_d3d9.log)
[GTR2_d3d9-working.log](https://github.com/doitsujin/dxvk/files/6050748/GTR2_d3d9-working.log)

- d3d11.log:
- dxgi.log:

**Comment by K0bin** [comment]
Thanks for bisecting this. Please do provide that apitrace so we can reproduce the issue and try to fix it.

**Comment by mickski56** [comment]
api trace
https://mega.nz/file/DggmAYYL#1ZkpyN_aKuyA2jh00LwAPvFg3ZYkzNilhjEtXdtpsjA
I didn't get any incorrect rendering with this is that expected ?

**Comment by K0bin** [comment]
Did you drive to a spot where the issue usually shows up? The trace is very short and the majority of time is spent in the menu so I cant really see anything.

**Comment by mickski56** [comment]
Yes I got as far as the end of the pit lane frame rate made the game uncontrollable. But there were black patches in the mid and far distance when I was running git latest. The issue is always in the mid to far distance.

**Comment by mickski56** [comment]
alternate api trace using spectator cam. 2 laps on board with an ai car. Definitely shows black artefacts with affected dxvk versions.
https://mega.nz/file/rlgxFSwC#a1thLW43MuI1LjiRGNoL0jewS85x5HkjOaNfWqa6rR4

**Comment by mickski56** [comment]
It's always on the kerbs and off to the sides never on track, don't know whether that helps at all.
![GRAB_004](https://user-images.githubusercontent.com/35852605/109389844-273ce900-7906-11eb-9bca-5472bd54d39f.jpg)

**Comment by K0bin** [comment]
Fixed.

**Comment by mickski56** [comment]
Big thank you to the all who work on dxvk

**Comment by Joshua-Ashton** [comment]
<3
