### ISSUE TITLE
[dxvk 1.8] Overwatch won't launch with proper dll locations

### ISSUE THREAD

**Issue by rosettet** [doitsujin/dxvk#1949]
Overwatch starts in a black screen before crashing on manjaro linux 5.10. I was able to fix this by swapping the 32bit and 64bit dlls in their respective folders.

**Comment by K0bin** [comment]
Where exactly did you put the dlls respectively?

The 64 bit dlls go into system32 and the 32 bit ones into syswow64. (Yes, very intuitive.)

**Comment by doitsujin** [comment]
Yeah, except that you're probably using wined3d now.

Instead of coming up with this syswow64 nonsense from #1942 yet again, how about you post information about your system and tell us what kind of problem you have?
