### ISSUE TITLE
Prime Crash.

### ISSUE THREAD

**Issue by artivision** [doitsujin/dxvk#195]
When i run VKmark via terminal on a Fedora-27 Prime Laptop, Radv warnings come first then Intel warnings and always starts on Amd Hainan, it gives 1000 points.

When i run an app like Unigine via terminal with Wine-DXVK, the opposite happens, Intel warnings come first then Radv warnings and the DXVK_HUD shows Intel IvyBridge. When 3D starts it crashes.

env DRI_PRIME=1 doesn't do anything. Any Ideas?

**Comment by doitsujin** [comment]
For 32-bit apps, try `export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.i686.json`.

DXVK uses the device that the D3D11 application selects, and most apps just pick the first one they can find, which can cause these problems. I'll think of a way to deal with that.

**Comment by artivision** [comment]
Works great, Heaven 720p Low @25fps on Hainan. Is there something more permanent like blacklisting Intel?

**Comment by doitsujin** [comment]
There's no clean solution yet. What you *could* do is create a symlink to the aforementioned JSON file in `~/.local/share/vulkan/icd.d`, which prioritizes your AMD card, but it'll make it appear twice in the device list (including vulkaninfo etc.).

**Comment by artivision** [comment]
Your solution:
export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.i686.json

must be written to:
~/.bashrc

same for the x86_64.json and works fine, probably for Nvidia dGpu to.

Also i want to ask how to install both 32bit and 64bit DXVK to the same Wine prefix.

**Comment by doitsujin** [comment]
you *can* do it for both at the same time, `VK_ICD_FILENAMES` is basically a colon-separated list.

As for installing both 32-bit and 64-bit DXVK, just install them to different directories and run the setup script for both. It'll work.

**Comment by artivision** [comment]
I should learn to read documents slower. I works as you said:

To   ~/.bashrc   or to   ~/.profile   or to   /etc/environment (without export)  depending of the situation you add:

export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json

**Comment by artivision** [comment]
https://github.com/doitsujin/dxvk/issues/195

Write to ~/.bashrc and then update bashrc with: source ~/.bashrc.

Replace radeon with nvidia if you have Nvidia.

Prime doesn't work here.
