### ISSUE TITLE
Warcraft 3 map editor doesn't work with dxvk but works with wined3d

### ISSUE THREAD

**Issue by Monsterovich** [doitsujin/dxvk#1954]
### Software information
Warcraft 3, worldedit.exe. The game itself works fine. 

https://www.youtube.com/watch?v=evgHvVTtO_Y

The map editor window freezes that's why I had to CTRL+C it.

### System information
- GPU: Mesa Intel(R) HD Graphics 520 (SKL GT2) (0x1916)
- Driver: Mesa 20.3.4 - kisak-mesa PPA
- Wine version: wine-6.3 (Staging)
- DXVK version: 1.8

### Apitrace file(s)
This seems to be a framebuffer issue. Should I do apitrace too?

### Log files
- d3d9.log: [worldedit_d3d9.log](https://github.com/doitsujin/dxvk/files/6055376/worldedit_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Needs child window.

**Comment by Blisto91** [comment]
@Monsterovich Friendly ping. Could i get you to test this again? Preferably with a wine build that includes child window patch like proton or wine GE and i think bottles soda. Maybe lutris wine also include it. Not 100% sure.

**Comment by Monsterovich** [comment]
> Friendly ping. Could i get you to test this again? Preferably with a wine build that includes child window patch like proton or wine GE and i think bottles soda. Maybe lutris wine also include it. Not 100% sure.

Still not working in wine-7.16 (Staging).

**Comment by Monsterovich** [comment]
Working in wine proton 7.0-3.

**Comment by Blisto91** [comment]
Thanks for testing. Then it's correct what Josh said above. Need the child window patch or some other wine work.
