### ISSUE TITLE
Amid Evil (UE4) Yellow graphics / color corruption

### ISSUE THREAD

**Issue by DefectiveByDesign** [doitsujin/dxvk#1956]
Amid Evil on FX9800P GCN 1.2 / windows 10 / 21.2.1 has color corruption. Last tested with 1.8.1, but older version didn't work either. Version 1.0 mentions a bug fix for yellow graphics in UE4, but apparently it didn't fix Amid Evil.

That apitrace program doesn't work. I get an error: "failed to find dxgitrace.dll wrapper" No idea how to fix this when the dll is there. Maybe there's some special way to install this tool, but it isn't explained, and I just copied the files into the game directory. I doubt log files will show anything, since the game isn't crashing, just shows color corruption.

Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
Preferably record the trace on Windows, or wined3d if possible.

**Reports with no log files will be ignored.**

### Software information
Name of the game, settings used etc.

### System information
- GPU:
- Driver:
- Wine version: 
- DXVK version: 

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by doitsujin** [comment]
The game is [known to work](https://www.protondb.com/app/673130) on Linux, so this will be another driver bug. We should really just go back to ignoring Windows-only driver issues since there's nothing we can do to fix them anyway.

**Comment by DefectiveByDesign** [comment]
GCN is GCN. The support misconception stems from OEMs like Dell, who pay for a provider monopoly, which isn't necessary when you can just get drivers directly from AMD. Dell might give you a year while AMD will keep supporting GCN until they declare driver EOL, which hasn't happened. Regardless, GCN 1.0 will hit EOL first, being as it doesn't support dx12, while APUs are all based on GCN 1.2+ Keep in mind AMD also sold desktop APUs directly. so Dell doesn't have a support monopoly even if they wanted it.

Anyway, let's talk about this apitrace program which is a mess. I copied the file and dll into the game's binary directory which contains AmidEvil-Win64-Shipping.exe. That is the correct main exe, AFAIK. The apitrace program however, does not do anything except throw a missing dll error that isn't missing. It doesn't even launch the game, and I used the provided command syntax. The problem might be that the program is running in the program files directory, which is normally locked unless running under administrator. If there is a specific way to run the tool correctly, it isn't made obvious. Perhaps I need to run the tool in a user directory, with only the dll in the exe folder, but that wasn't made clear.

**Comment by K0bin** [comment]
You didn't do it correctly.
Here's a guide: https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace

But as doitsujin said, this is probably a waste of time as the issue is most likely a driver problem.

**Comment by DefectiveByDesign** [comment]
I can't run wine config under windows. I did get the tool to run, as stated in my edit, but it produced 0kb files. Also, how am I supposed to use dxgi.dll? Should I copy the wrapper dlls into apitrace binary? I can't overwrite the dxvk dlls, or it won't work, afaik.

**Comment by K0bin** [comment]
There's a Windows section in that guide that doesn't use Wine. And yes, you have to copy over d3d11.dll, dxgi.dll and dxgitrace.dll. After that you just start the game as you would normally. Leave the apitrace tool alone.

**Comment by DefectiveByDesign** [comment]
Wait, wut? If you overwrite the dxvk dlls, it won't run under vulkan, and completely invalidate any dxvk related issue.

Also, IDK how this worked, but I got log files in the game directory, maybe from dxgitrace.dll, although this is clearly breaking security protocol. Of course, this might be security theater where the OS only prohibits the user and not actual program behavior.
[AmidEvil-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/6067296/AmidEvil-Win64-Shipping_dxgi.log)
[AmidEvil-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/6067297/AmidEvil-Win64-Shipping_d3d11.log)

**Comment by K0bin** [comment]
> Wait, wut? If you overwrite the dxvk dlls, it won't run under vulkan, and completely invalidate any dxvk related issue.

Please do that anyway. It records the D3D11 commands and those are identical regardless of whether or not DXVK is installed.

**Comment by DefectiveByDesign** [comment]
7zip tracefile (smaller size) 382mb
https://ufile.io/5ct39l7d
tar.gz (if need this specific format) 592mb
https://ufile.io/sljk6v0r
2 files, 900mb=level load 169mb=menu load
