### ISSUE TITLE
After updating to 1.8.1, edge smoothing in Sims 2 causes rainbow artifacts

### ISSUE THREAD

**Issue by voicemxil** [doitsujin/dxvk#1957]
![image](https://user-images.githubusercontent.com/69059862/109726274-670f0500-7b80-11eb-9837-d8e2fbe010cc.png)

**Comment by voicemxil** [comment]
GPU: RX 480 4GB
Driver: 20.11.1
Wine version: N/A, windows 10 20H2
DXVK version: 1.8.1
Gonna try a driver update, but version 1.8.0 works fine. Happens when edge smoothing is turned to any level
[Sims2EP9RPC_d3d9.log](https://github.com/doitsujin/dxvk/files/6072297/Sims2EP9RPC_d3d9.log)

**Comment by Joshua-Ashton** [comment]
Do you have an apitrace? This is probably an amdvlk bug

**Comment by voicemxil** [comment]
> Do you have an apitrace? This is probably an amdvlk bug

i'm not on linux, just regular old windows 10, so i don't think amdvlk applies here 🧍‍♂️ - dxvk just happens to make it work much better on modern systems 
![image](https://user-images.githubusercontent.com/69059862/109737673-6d0ee100-7b94-11eb-8643-f9ad43bdc895.png)

i can.. attempt to get an apitrace? but it was making the game crashy without dxvk and was already nearing a gigabyte before the game even finished loading lol.

**Comment by rafaelaalvesn** [comment]
![Sims2EP9RPC 2021-03-03 11-15-36](https://user-images.githubusercontent.com/29284998/109819308-ae45d600-7c12-11eb-9ef8-f83f403ccc51.png)

Same problem with AMD RX 580

**Comment by VawalPerf** [comment]
Same problem in Serious Sam Games(Test in 3:BFE, HD The Second Encounter)
1.7.3 good

**Comment by Blisto91** [comment]
Are any of you on windows (or linux with amdvlk) able to test this with the latest driver?

**Comment by leonsims** [comment]
I tested it on Windows 10 with AMD driver 22.5.1.
At least I don't see any artifacts anymore.

**Comment by K0bin** [comment]
I'm gonna close this then. We don't work around bugs in the proprietary AMD driver anyway, so there isn't anything to do here either way.
