### ISSUE TITLE
Metal Gear Rising: Revengeance: visual artifacts when MSAA is enabled

### ISSUE THREAD

**Issue by oltolm** [doitsujin/dxvk#1961]
Metal Gear Rising: Revengeance has visual artifacts when MSAA is enabled. Everything is OK when MSAA is disabled.

![mgrr](https://user-images.githubusercontent.com/1674229/109859919-cd1d8a00-7c5d-11eb-9a19-f90cfbae0647.jpg)

### Software information
Metal Gear Rising: Revengeance. Graphics preset: high.

### System information
- GPU: AMD Radeon RX 580
- Driver: 21.2.3
- Windows version: Windows 10
- DXVK version: 1.8.1

### Apitrace file(s)
https://drive.google.com/file/d/1nAkxJxYMRG5u2uWhPSQk-A5mjGZk2Z0o/view?usp=sharing

### Log files
[METAL GEAR RISING REVENGEANCE_d3d9.log](https://github.com/doitsujin/dxvk/files/6078572/METAL.GEAR.RISING.REVENGEANCE_d3d9.log)

**Comment by doitsujin** [comment]
The trace replays fine on RADV. Just use 1.7.3 with official AMD drivers for now.

**Comment by doitsujin** [comment]
Does this work with <https://github.com/doitsujin/dxvk/actions/runs/619081557>?

FWIW, I cannot reproduce this with open AMDVLK on my RX 480.

**Comment by Oschowa** [comment]
At least on amdvlk-pro 20.45 on a RX580 on linux it doesn't help, still broken.

**Comment by oltolm** [comment]
> 
> 
> Does this work with https://github.com/doitsujin/dxvk/actions/runs/619081557?

No, I get the same result.

**Comment by oltolm** [comment]
AMD still has not fixed the problem even in the latest drivers. It's obvious that they don't care. Closing.
