### ISSUE TITLE
[D3D9/NFS:MW 2005] FPS Counters report wrong values

### ISSUE THREAD

**Issue by MinePro120** [doitsujin/dxvk#1964]
### Software information
Need For Speed Most Wanted 2005 Black Edition ("speed.exe")

### System information
- OS: Windows 10
- GPU: R5 M335
- Driver: 20.10.12-200422a-354674C-Dell
- Wine version: -
- DXVK version: 1.8.1

### Files
- d3d9.log: [speed_d3d9.log](https://github.com/doitsujin/dxvk/files/6093592/speed_d3d9.log)

### Issue description
Hello. Even though various FPS counters (AMD Radeon Software, MSI Afterburner) report 30-40 FPS while using DXVK, I can tell those values are pretty inaccurate. On some locations the FPS is ~60 and on others ~15, as far my eyes can tell. Is this possible? Are my eyes deceiving me? The D3D9 which runs on 30 FPS seems way smoother in general (though I experience some awful flickering issues with D3D9 and thus the change to Vulkan).

**Comment by doitsujin** [comment]
FPS is the average number of frames presented in a given time interval, it doesn't say anything about smoothness. So, no, the FPS counters are very definitely not reporting wrong values here, even though your experience may not be good.

**Comment by MinePro120** [comment]
The game seems choppy and by observing various parts of the screen, the FPS were the first thing that came to mind. Anyway, is there anything I could try to improve the performance?

**Comment by mozo78** [comment]
Yes, don't use Windows at first place, it's a disaster. It runs pretty smooth on Linux.

**Comment by MinePro120** [comment]
Not exactly the solution I was looking for, but I will try on Arch. Last time I tried to run it with wine (only), it didn't even start.

**Comment by mozo78** [comment]
It runs fine, I played it a lot. And the idea is to migrate to Linux, not just install it for one game. Use Linux on a daily basis and as a main OS.
