### ISSUE TITLE
Just 2 questions about Unreal Engine, dxvk and texture flickering.

### ISSUE THREAD

**Issue by JohnnyDilinjer** [doitsujin/dxvk#1967]
Sorry if I'm writing in the wrong place, but I have 2 questions about Unreal Engine 4 and dxvk .. Why in 99.9% of cases UE4 and dxvk can cause texture flickering on GFX7? At the same time, in version dxvk-1.00, the flickers are minimal, but the further the version, the flickers increase.. As far as I know, this is related to nvidia and it is possible to replace DeviceID and VendorID.. Is there a way to fix this?

**Comment by doitsujin** [comment]
I don't know what you're talking about, there has never been a report about texture flickering in UE4.

Then again, most people already moved on to more recent GPUs, so probably you're running into some sort of driver issue.

**Comment by JohnnyDilinjer** [comment]
Excuse for troubling.
