### ISSUE TITLE
Portal 2 crashes after a short while when running in -vulkan mode

### ISSUE THREAD

**Issue by ShygalCoco** [doitsujin/dxvk#1968]
Portal 2 crashes after a short while when running in -vulkan mode on a GTX 1660 Ti graphics card

Crash is mainly replicatable via a loading screen or playing a level for a short period of time

I'm only able to fix this issue for myself by downgrading to an older driver version for the graphics card, specifically 446.14 instead of the latest (currently 461.72)

### Software information
Portal 2, maximum graphical settings with VSync disabled, -vulkan mode

### System information
- Device: Dell G3 15 Gaming Laptop
- OS: Windows 10 64-Bit
- CPU: Intel Core i5 9th Gen
- RAM: 8 GB 2933 MHz
- GPU: Nvidia GeForce GTX 1660 Ti Max-Q Design 6 GB
- Driver: GeForce Game Ready Driver 461.72
- DXVK version: Native to Portal 2

### Log files
[portal2_d3d9.log](https://github.com/doitsujin/dxvk/files/6105550/portal2_d3d9.log)

**Comment by doitsujin** [comment]
Can't reproduce here, but for some reason your graphics driver crashes.

**Comment by ShygalCoco** [comment]
NVidia Control Panels System Information Save:
[NVIDIA System Information 03-09-2021 13-55-55.txt](https://github.com/doitsujin/dxvk/files/6110810/NVIDIA.System.Information.03-09-2021.13-55-55.txt)

**Comment by pdaniell-nv** [comment]
I wasn't able to reproduce this for myself on my RTX 2070 laptop after playing Portal 2 in -vulkan mode for about 30 minutes. My GPU is not exactly the same as yours, but should be close enough. If you are willing and able, would you mind trying the latest Vulkan beta driver 458.06, which you can find here:
https://developer.nvidia.com/vulkan-driver

**Comment by ShygalCoco** [comment]
> Another question, are you running fullscreen?

i'm running borderless windowed

**Comment by ShygalCoco** [comment]
> @ShygalCoco does the window cover your whole screen?

it does, yes. 1920x1080, 60hz

**Comment by ShygalCoco** [comment]
> I wasn't able to reproduce this for myself on my RTX 2070 laptop after playing Portal 2 in -vulkan mode for about 30 minutes. My GPU is not exactly the same as yours, but should be close enough. If you are willing and able, would you mind trying the latest Vulkan beta driver 458.06, which you can find here:
> https://developer.nvidia.com/vulkan-driver

i just tried what you requested, using the latest beta 458.06. my game still crashes after a short while, the same error appearing in the d3d9 log

**Comment by iWeaker4you** [comment]
@ShygalCoco  try fullscreen mode

**Comment by Joshua-Ashton** [comment]
It would not make a difference, borderless window that covers the screen and fullscreen are functionally identical in DXVK

**Comment by ShygalCoco** [comment]
joshua is correct, i just tried the game in fullscreen mode and it still crashed

**Comment by DaRkL3AD3R** [comment]
> It would not make a difference, borderless window that covers the screen and fullscreen are functionally identical in DXVK

Even on Windows? I know in Vulkan games if I am playing in true exclusive fullscreen, the Windows volume overlay doesn't appear over the game like it does in borderless windowed, as well as taking longer to alt tab. This applies to DXVK as well, not just Vulkan in general.

**Comment by Joshua-Ashton** [comment]
Yes

**Comment by sevgajuk** [comment]
I have exactly the same problem but with a GTX 1650.

**Comment by YurgenSchn** [comment]
Well, bringing this up again. I'm crashing using -vulkan. I got an RX6600 on 22.11.2 drivers. It crashes Steam aswell. I have two monitors plugged in, the main on 1080p 144hz, and the other is 1600x900 75hz. The game is at borderless windowed. Setting it to fullscreen bugs the screen (can still hear the UI while i move the mouse), requiring a restart, but then crashes on launch. Removing -vulkan and launching reset settings, at least i didn't have to touch cfg files.

**Comment by soyfeo123** [comment]
i still have the problem
