### ISSUE TITLE
Cities: Skylines - game crashes when full zoom into buildings then scrolling cursor hangs

### ISSUE THREAD

**Issue by mmtrt** [doitsujin/dxvk#197]
### Software information
- Game: Cities: Skylines
### System information
- GPU: GTX 650
- Driver: 390.42
- Wine version: wine-3.4-96-gf2cb86decb (Staging)
- DXVK version: 4ce64bd8865bbb25baa25d622437c9258126c4d2

### Notes
Game is eating more ram 6.3+gb with lowest graphics and with default graphics preset it runs with full ram usage going for more pc crawls I think could be memory leak? darkness issue like on #177

### Apitrace file(s)
- [Cities.trace.7z](https://mega.nz/#!ck02WayK!_wgX3M5H6GI1-afQvtpZWPfD-2ciZw1zyYPr4nF-s0w)

### Log files
- [Cities_d3d11.log](https://github.com/doitsujin/dxvk/files/1844042/Cities_d3d11.log)
- [Cities_dxgi.log](https://github.com/doitsujin/dxvk/files/1844043/Cities_dxgi.log)
- [terminal.log](https://github.com/doitsujin/dxvk/files/1844044/terminal.log)
- [tracing.log](https://github.com/doitsujin/dxvk/files/1844045/tracing.log)

### Game create its own log files when crashing
- [error.log](https://github.com/doitsujin/dxvk/files/1844048/error.log)
- [output_log.txt](https://github.com/doitsujin/dxvk/files/1844049/output_log.txt)

### Screenshots
![screenshot_20180323_103919](https://user-images.githubusercontent.com/2322598/37860734-c349026c-2f4d-11e8-868a-b466b715d76d.png)
![screenshot_20180323_104153](https://user-images.githubusercontent.com/2322598/37860735-c381027a-2f4d-11e8-8a6e-d7a279867a93.png)
![screenshot_20180323_104356](https://user-images.githubusercontent.com/2322598/37860736-c3b5dc52-2f4d-11e8-8815-ee7f787621c4.png)
![screenshot_20180323_104437](https://user-images.githubusercontent.com/2322598/37860737-c3ea54d2-2f4d-11e8-9cc3-6d774aede64e.png)

**Comment by doitsujin** [comment]
Since this crash seems to occur in `d3d11.dll`, can you post the wine backtrace?

Other than that, the game requires steam output and fails to compile a shader, which *could* be the reason why this game crashes.
```
err:   DxbcCompiler: Invalid sampled type: DxbcResourceReturnType::Mixed
err:   D3D11Device::CreateGeometryShaderWithStreamOutput: Not implemented
```

**Comment by mmtrt** [comment]
[backtrace.txt](https://github.com/doitsujin/dxvk/files/1844317/backtrace.txt)

**Comment by doitsujin** [comment]
That looks like an unhandled dxvk exception somewhere (which in itself is a bug already).

Anyway, `err:   DxbcCompiler: Invalid sampled type: DxbcResourceReturnType::Mixed` should be fixed, stream output is still not supported and will be tracked in meta-isssue #135. Closing this since a fix for this issue very likely depends on that feature.
