### ISSUE TITLE
Dragon's Dogma Square Artifacting

### ISSUE THREAD

**Issue by lemonzest79** [doitsujin/dxvk#1972]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

When accessing the Equipment Screen and rotating the avatar square artifacts appear over them, this does not occur with DXVK 1.7.3

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
Preferably record the trace on Windows, or wined3d if possible.

**Reports with no log files will be ignored.**

### Software information
Name of the game, settings used etc.

Dragon's Dogma Dark Arisen, Maxed everything

### System information
- GPU: Radeon RX 5600 XT (NAVI10)
- Driver: Mesa RADV git dfb0e0d
- Wine version: Wine-Staging 6.3 + Win Steam

- DXVK version: 1.8/1.8.1

### Apitrace file(s)
- Put a link here 
- https://1drv.ms/u/s!AgH-T_tmw6C2gYA0GpIDKpJ11JgIwA?e=Uqh5Pf 
- https://1drv.ms/u/s!AgH-T_tmw6C2gYA1WR-WfUcpRG1n1g?e=Ma2akz

### Log files
- d3d9.log: 
- [DDDA_d3d9-180.log](https://github.com/doitsujin/dxvk/files/6112915/DDDA_d3d9-180.log)
- [DDDA_d3d9-173.log](https://github.com/doitsujin/dxvk/files/6113042/DDDA_d3d9-173.log)

![367500_20210310030009_1](https://user-images.githubusercontent.com/40669977/110570882-901a3180-814e-11eb-820f-04c32d7a039a.png) <-- bad

![367500_20210310023057_1](https://user-images.githubusercontent.com/40669977/110570955-b63fd180-814e-11eb-8f9d-8dd45c0e8ab5.png) <-- good

**Comment by Oschowa** [comment]
This doesn't occur on RX580/Polaris with RADV.

**Comment by lemonzest79** [comment]
![367500_20210310022222_1](https://user-images.githubusercontent.com/40669977/110599112-6ecf3a80-817a-11eb-901e-3a00cf61c0c1.png)

Another Pic

**Comment by doitsujin** [comment]
We don't need more pictures, one is enough...

Does this work with Mesa 20.3.4?

**Comment by lemonzest79** [comment]
I'm on the Fedora Linux 34 Pre-Release, so the lowest I think I can currently go is 21.0.0 rc5, So I just tried downgrading to the supplied mesa and it still artifacts on 1.8/1.8.1 and 1.7.3 is still free of artifacts. the mesa git I'm getting is from the copr

https://copr.fedorainfracloud.org/coprs/xxmitsu/mesa-git/

**Comment by lemonzest79** [comment]
I'll close this, now I know its a mesa issue, thanks for the help
