### ISSUE TITLE
[question] Graphics APIs for dummies, dxvk edition

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#1974]
_Please describe your issue as accurately as possible._ 

For the first time in my history of reporting bugs here I'm going to ignore the rest of the template. After all, I'm only keeping up with the fashion :frog:.

I know I could have asked on discord, because there is such a thing, but I don't really use it and figured the answers to this "issue" might help other potentially interested poor souls in the future.

Let's say I have this friend (don't we all!) that would want do dust off the old C/C++ book and look into gaining sufficient knowledge to contribute to [this sort of stuff](https://github.com/AlpyneDreams/d8vk) or experiment with something more basic, yet similar. How does one go about learning these things from scratch or close to scratch?

Is there a recommended starting point for newbies/dummies in terms of graphics APIs? Is it worth starting with OpenGL over the d3d stuff?

My friend truly appreciates any hints you, or any other experienced people, can provide. Sorry for clogging the issue tracker with such nonsense - promise to close it soon. I personally blame this awful friend of mine and will never forgive him! :frog:

**Comment by WinterSnowfall** [comment]
Closing, as it's not an issue... that friend I mentioned would still appreciate some pointers though. There's just too much stuff out there and too few guideposts, as a wise man once said.

**Comment by Joshua-Ashton** [comment]
I don't really have any advice other than just going in and trying to make what you want to make and bashing rocks together until you get there. :smile: This is what I did.

**Comment by WinterSnowfall** [comment]
> bashing rocks together until you get there.

Ironically, that's also my usual approach. Figured I'd try to do things by the book for once, but oh well... \*grabs the old pickaxe and heads into the mine\* :pick: .

**Comment by Faalagorn** [comment]
@WinterSnowfall going a bit offtopic I guess, but you can also take a look at GRVK at https://github.com/libcg/grvk - it's a similar project inspired by DXVK on its early stages just doing Mantle instead of D3D.

**Comment by WinterSnowfall** [comment]
@Faalagorn Thanks for the suggestion. Stuff like this is not exactly entry level, so a bit over my head at the moment, but I'll keep it in mind. I'm still on rasterization 101 atm. 

I'm at least somewhat familiar with the math involved along the way (I guess it might put other people off?)... it's all interesting, yet daunting as a programming topic. Graphics APIs look like a nightmare within a complex dream, to draw an analogy to a once popular movie, but I guess once you get to know the devil a bit, he does not seem that bad.
