### ISSUE TITLE
Far Cry 5 light/rendering bug

### ISSUE THREAD

**Issue by darko664** [doitsujin/dxvk#1978]
**I uploaded a Video to see the Rendering Issues.**
https://youtu.be/OZ_wv0AdO2Y

### Software information
Game: Far Cry 5
The Graphic settings make no difference to the problem.

### System information
- Win10 Build 19042
- CPU: Xeon X5690
- GPU: Vega64 liquid
- Driver: 21.2.3
- DXVK version: 1.8.1

### Apitrace file(s)
I tried to trace the game but it didnt work because of ubisoft connect launcher.

### Log files
- d3d11.log:
[FarCry5_d3d11.log](https://github.com/doitsujin/dxvk/files/6151157/FarCry5_d3d11.log)
- dxgi.log:
[FarCry5_dxgi.log](https://github.com/doitsujin/dxvk/files/6151158/FarCry5_dxgi.log)

**Comment by doitsujin** [comment]
1.8.1 is known not to work on the AMD Windows driver, please go back to 1.7.3 or use Linux.

**Comment by darko664** [comment]
OMG, thanks! :D
It works and the increase in performance is incredible.
80-100fps with DXVK vs 45-70fps in DX11
