### ISSUE TITLE
Warframe x64 misses D3D11DeferredContext::MapImage

### ISSUE THREAD

**Issue by NeroBurner** [doitsujin/dxvk#198]
### Software information
Warframe, started using [Lutris](https://lutris.net/games/warframe/). The launcher uses https://github.com/GloriousEggroll/warframe-linux

Using DXVK at startup (before any window appears) Warframe crashes
```
5.477 Sys [Info]: Resource load completed in one pass and 1.3s (inherited 9 of 1550), Frame peak: 217ms
5.495 Gfx [Info]: Creating dynamic texture: /Textures/DynamicTexture0
err:   D3D11DeferredContext::Map: Not implemented
5.497 Gfx [Warning]: D3DAssert: DeviceContext().Map(texData.mTexture, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped) returned 0x80004001

5.497 Error [Info]: Assertion Failure
Error [Debug]: Loaded unexpected version of dbghelp.dll from C:\windows\system32\dbghelp.dll
```

### System information
- GPU: GeForce GTX 780 Ti
- Driver: 390.42.0
- Wine version: wine-staging 3.4
- DXVK version: 0.31 (binary release)

### Apitrace file(s)
I was not able to generate a trace
```
wine apitrace.exe trace -v -a dxgi Warframe.x64.exe  -log:/Preprocessing.log -dx10:1 -dx11:1 -threadedworker:1 -cluster:public -language:en -fullscreen:0 
000b:fixme:winediag:start_process Wine Staging 3.4 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
info: did not find Z:\mnt\tux_data\Games\Lutris\warframe\drive_c\Program Files\Warframe\Downloaded\Public\..\wrappers\RelWithDebInfo\dxgitrace.dll
info: found Z:\mnt\tux_data\Games\Lutris\warframe\drive_c\Program Files\Warframe\Downloaded\Public\..\lib\wrappers\dxgitrace.dll
inject -D "Z:\mnt\tux_data\Games\Lutris\warframe\drive_c\Program Files\Warframe\Downloaded\Public\..\lib\wrappers\dxgitrace.dll" -- Warframe.x64.exe -log:/Preprocessing.log -dx10:1 -dx11:1 -threadedworker:1 -cluster:public -language:en -fullscreen:0
error: failed to execute inject
002f:fixme:kernelbase:AppPolicyGetProcessTerminationMethod 0xfffffffffffffffa, 0x23fd00
```

starting warframe without `apitrace.exe` works
```
wine Warframe.x64.exe  -log:/Preprocessing.log -dx10:1 -dx11:1 -threadedworker:1 -cluster:public -language:en -fullscreen:0
```

### Log files
- d3d11.log: [Warframe.x64_d3d11.log](https://github.com/doitsujin/dxvk/files/1844239/Warframe.x64_d3d11.log)
- dxgi.log: [Warframe.x64_dxgi.log](https://github.com/doitsujin/dxvk/files/1844241/Warframe.x64_dxgi.log)
- Game log: [warframe-dxvk-crash.txt](https://github.com/GloriousEggroll/warframe-linux/files/1844204/dxvk-crash.txt)

**Comment by doitsujin** [comment]
Please re-test with latest `master` where this method is supported (see #93).

**Comment by NeroBurner** [comment]
tried with master

I got just a little further
```
5.377 Gfx [Info]: Creating dynamic texture: /Textures/DynamicTexture0
err:   D3D11DeferredContext::MapImage: Not implemented
5.380 Gfx [Warning]: D3DAssert: DeviceContext().Map(texData.mTexture, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped) returned 0x80004001
```

[dxvk-crash-master.txt](https://github.com/doitsujin/dxvk/files/1844370/dxvk-crash-master.txt)

updating the title

**Comment by Altosk** [comment]
AC:Black flag also need mapimage as well

**Comment by doitsujin** [comment]
Alright, thanks for the info, will bump priority for that function a bit.

**Comment by doitsujin** [comment]
Please test with 675b1c5b8c682a4b1d335eee07ab9386c95dd7f2. Note that the image-specific code is mostly untested at the moment, will work on that later.

**Comment by doitsujin** [comment]
Please test with 675b1c5b8c682a4b1d335eee07ab9386c95dd7f2. Note that the image-specific code is mostly untested at the moment, will work on that later.

**Comment by MEXAHOTABOP** [comment]
works thanks a lot 
(tested on orbiter)

**Comment by doitsujin** [comment]
Stutter is probably caused by shader compilation, will try to address that at some point.
