### ISSUE TITLE
[D3D9]Dragon Nest Water is not displaying correctly

### ISSUE THREAD

**Issue by dnblank123** [doitsujin/dxvk#1980]
### Software information
Dragon Nest

### System information
- GPU: Nvidia GTX 1050ti
- Driver: 456.98
- Windows 10
- DXVK version: 1.8.1

### Apitrace file(s)
- https://drive.google.com/file/d/1daCTTV76LHC_Jxf_47L4iSmj4JAlHJo-/view?usp=sharing

### Log files
- d3d9.log: [DragonNest_x64_d3d9.log](https://github.com/doitsujin/dxvk/files/6153977/DragonNest_x64_d3d9.log)

[without DXVK]
![DN 2021-03-17 12-35-12 Wed](https://user-images.githubusercontent.com/67945097/111421215-951b4a00-8727-11eb-9e53-e319ccbf552b.png)

[with DXVK]
![DN 2021-03-17 13-07-09 Wed](https://user-images.githubusercontent.com/67945097/111421270-af552800-8727-11eb-9e55-e5b014cf4cbc.png)

**Comment by K0bin** [comment]
Can you try turning putting `d3d9.allowLockFlagReadonly = False` into your DXVK config (dxvk.conf in your user directory or right next to the games exe) and report back whether that fixes it?

**Comment by dnblank123** [comment]
> Can you try turning putting `d3d9.allowLockFlagReadonly = False` into your DXVK config (dxvk.conf in your user directory or right next to the games exe) and report back whether that fixes it?

It did fixed, Thank you!

**Comment by K0bin** [comment]
Reopening this so we can make it work out of the box.

**Comment by K0bin** [comment]
Should be fixed out of the box now. Pls re-open if the issue comes back.
