### ISSUE TITLE
[D3D9] Medieval II: Total War Retail Graphical Issue

### ISSUE THREAD

**Issue by tpurde** [doitsujin/dxvk#1985]
Medieval II: Total War with it's retail release on DVD has black lines on the campaign map. I have tested battles and haven't seen this issue. This also doesn't happen with WineD3D.

I have been using Lutris, as it really made installing a DVD game with Wine a lot easier. I hope that won't cause any problems for tackling this issue.

DXVK:
![unknown](https://user-images.githubusercontent.com/62025836/111910416-56142e00-8a72-11eb-8276-409de2b0b71d.png)

WineD3D (How it should look):
![Screenshot_20210321_181427](https://user-images.githubusercontent.com/62025836/111910435-64fae080-8a72-11eb-90a9-cad2e287231a.png)
### Software information
Medieval II: Total War (Tested both the main game and the expansion, I have logs for the expansion.)
Highest graphic settings, 1920x1080

### System information
- GPU: Nvidia GeForce GTX 1050Ti
- Driver: 460.67
- Wine version: lutris-5.7-11-x86_64 (The game needs .NET which can't be installed on newer Wine versions.)
- DXVK version: v1.7.3L-03f11ba on Lutris, tried with other, older versions and had no luck.

### Apitrace file(s)
I haven't had the chance to create apitrace files as of now, but I'll make sure to add them soon.

### Log files
- d3d9.log: [kingdoms_d3d9.log](https://github.com/doitsujin/dxvk/files/6177737/kingdoms_d3d9.log)
The dxgi.log is empty.

**Comment by DadSchoorse** [comment]
Looks like a duplicate of #1669.

**Comment by tpurde** [comment]
Apparently it is. I should have checked better. It's my fault. Sorry for the disturbance and I'll add my report there.
