### ISSUE TITLE
GODS Lands of Infinity display incorrectly

### ISSUE THREAD

**Issue by l12436** [doitsujin/dxvk#1988]
GODS Lands of Infinity show incorrect display when using dxvk d3d9.dll
![Screenshot_20210323_095018](https://user-images.githubusercontent.com/2596649/112084527-eca43480-8bc3-11eb-8006-2234268b5f57.png)
It should be like this
![image](https://user-images.githubusercontent.com/2596649/112089988-aa7ff080-8bcd-11eb-8f39-aaa92c9d3cd0.png)

### Software information
GODS Lands of Infinity

### System information
- GPU: GTX 1060
- Driver: nvidia 460.67
- Wine version: 6.4.0
- DXVK version: 1.8.1

### Apitrace file(s)
- [trace](https://www.mediafire.com/file/dq5yjfnono63oze/gods_apitrace.trace.xz/file)

### Log files
- d3d9.log: [d3d9.log.gz](https://github.com/doitsujin/dxvk/files/6186518/d3d9.log.gz)
- d3d11.log: none
- dxgi.log: none

**Comment by doitsujin** [comment]
> DXVK version: 1.8.1

Please test with the latest release, you're two versions behind.

**Comment by DadSchoorse** [comment]
Still present, SetGammaRamp needs to reject invalid gamma ramps.
