### ISSUE TITLE
[d3d9] Sega Rally Evo → crashes when loading the level

### ISSUE THREAD

**Issue by NerosTie** [doitsujin/dxvk#1989]
After selecting a race, there is a loading screen then it crashes. It works with WineD3D.

### Software information
[config.ini](https://github.com/doitsujin/dxvk/files/6200313/config.txt)

### System information
- GPU: AMD Radeon RX 580
- Driver: Mesa 20.3.4
- Wine version: Staging 6.4
- DXVK version: 1.8.1

### Apitrace file(s)
https://mega.nz/file/zuYlEaZa#EzEFHOLjG0B8fRPJnaLKLmPNPOVcWVqEKBUrQhXqHjc

### Log files
[sega-rally_dxvk.log](https://github.com/doitsujin/dxvk/files/6200312/sega-rally_dxvk.log)

**Comment by K0bin** [comment]
Replays fine with DXVK. I assume you made the trace with WineD3D. Can you make another one with DXVK so I can see which call causes the crash and compare the traces?

**Comment by NerosTie** [comment]
@K0bin 
https://mega.nz/file/juoGBQAR#JgceuZPAyO8Cl7NSc0Gay68MsYUdOYXWa4v8z71Rb6Y

Have you looked at the log file? There are many errors called 

`err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED`

**Comment by DadSchoorse** [comment]
sounds like #1318.

**Comment by K0bin** [comment]
Pretty sure it's that.

**Comment by NerosTie** [comment]
It looks like I don't experience this bug anymore.

Tested with:
DXVK 1.9.1
Wine lutris-fshach-6.14-3
Mesa 21.2.1
