### ISSUE TITLE
Vulkan Multi-GPU

### ISSUE THREAD

**Issue by artivision** [doitsujin/dxvk#199]
It is a good idea to take advantage of the Vulkan Multi-GPU functionality. I don't know maybe have more command queues and divide command buffers between them. Some classes can be specified as suitable to run to the secondary GPU. Example: if there is a Prime Laptop you can do Post-processing on Intel and you don't need to copy anything back to the dGpu.

**Comment by doitsujin** [comment]
DXVK is an API wrapper, it just doesn't work that way.

**Comment by viggy96** [comment]
I realise this is a small portion of the market, but would it be possible to support multi-GPU for games that do already support it in DX11?

**Comment by K0bin** [comment]
There are some hints games use in NvAPI but most SLI stuff is a hack in the driver that needs to be done on a game by game basis.
