### ISSUE TITLE
Assassins Creed III doesn't revert monitor back at 144hz when exit.

### ISSUE THREAD

**Issue by artivision** [doitsujin/dxvk#1990]
Assassins Creed III Remastered has a cap at 60 fps and uses the monitor at 60hz regardless of the resolution. The monitor provides both 60 and 144hz at all resolutions. Dxvk doesn't revert the monitor back at 144hz when exit the game. I revert it myself with Xfce monitor settings.

**Comment by doitsujin** [comment]
DXVK **does** revert the display mode if the game actually exists cleanly. If it crashes while exiting then there's not an awful lot we can do.

**Comment by artivision** [comment]
[ACIII_d3d11.log](https://github.com/doitsujin/dxvk/files/6207011/ACIII_d3d11.log)
[ACIII_dxgi.log](https://github.com/doitsujin/dxvk/files/6207014/ACIII_dxgi.log)

I think it doesn't, i'm saying this again and sorry if i bother but is time to equip with 144hz+ monitors and LK switches based input devices. The timings of Dxvk are a lot better and consistent but many things are not perfect yet.

**Comment by doitsujin** [comment]
Can you post a full wine log as well please?

**Comment by artivision** [comment]
[ACIII_terminal.log](https://github.com/doitsujin/dxvk/files/6208918/ACIII_terminal.log)

It exits normally from the exit in game button, no dlls or wine server in my ram. It doesn't even make attempt to restore at 155hz. The restoring at 155 attempt you see from previous log is when i alt tab and minimize the game's window, it works there but not when exit.

**Comment by doitsujin** [comment]
Installed the game to test, works fine here.

**Comment by artivision** [comment]
Solved, i can always exit the game with ALT+F4 from in game or exit to games main menu and then ALT+F4. I think this is a universal solution if normal exit doesn't work.
