### ISSUE TITLE
DXVK not working anymore in any game. 

### ISSUE THREAD

**Issue by tusty76** [doitsujin/dxvk#1993]
so a guy actually had the same problem and fixed it by patching the binary but like(His name is Fabi). If he could help since windows is not supported anymore and since he did it. I would appreciate.
### Software information
Name of the game, settings used etc.
Star wars: Jedi Fallen Order 
### System information
- GPU:RX 580 8Gb
- Driver:21.3.1
- Wine version: 
- DXVK version: 1.8.1

### Log files

-d3d11.log: [starwarsjedifallenorder_d3d11.log](https://github.com/doitsujin/dxvk/files/6219794/starwarsjedifallenorder_d3d11.log)
- dxgi.log: [starwarsjedifallenorder_dxgi.log](https://github.com/doitsujin/dxvk/files/6219799/starwarsjedifallenorder_dxgi.log)

**Comment by doitsujin** [comment]
The game works fine on supported platforms. There's nothing to fix here and if you can't get DXVK to work on Windows, just don't use it.
