### ISSUE TITLE
Is it possible to use DXVK in a native app without Wine?

### ISSUE THREAD

**Issue by lindevel** [doitsujin/dxvk#1994]
In the Wiki, everything is written only in the context of Wine, but can I use DXVK in a native application? For example to port a D3D9 game from Windows to Linux without completely rewriting the rendering to another API

Probably this question has already been asked by someone, but unfortunately I did not find it

**Comment by DadSchoorse** [comment]
Josh has a fork that allows you to use dxvk for native apps, it's even available as an option in Portal 2: https://github.com/Joshua-Ashton/dxvk-native

**Comment by lindevel** [comment]
Thanks
