### ISSUE TITLE
AM2R lags on certain effects.

### ISSUE THREAD

**Issue by Miepee** [doitsujin/dxvk#1999]
On certain effects, AM2R lags immensely, crawling down to 15-5fps, depending on the condition.
This has been tested on AM2R 1.5.2, but will have slightly stronger results with [Another Memetroid 2 Remake](https://www.reddit.com/r/AM2R/comments/m8tpia/another_memetroid_2_remake_update_previously_am2r/), due to it having custom palettes.

This mostly happens when placing a Powerbomb near enemies (the more enemies are hit / die by it, the slower the game runs), powerbombing the Tester bossfight, being in the Serris bossfight, or when a Gamma Metroid dies.

[Here](https://cdn.discordapp.com/attachments/509717926807601182/826491176537292851/save2) is a Save file to test out scenario 1 very quickly. Place it into `WINEPREFIX/drive_c/users/USER/Local Settings/Application Data/AM2R`. In-game, exit the room by going to the left, jump down a bit and go through the left door. Place a Powerbomb there.

Here are two videos showcasing it:
With DXVK:
https://cdn.discordapp.com/attachments/297940849369546752/826484233979297832/2021-03-30_17-51-19.mp4
(Mangohud was enabled here, but I confirmed the issue is not mangohud related)

With WineD3D:
https://cdn.discordapp.com/attachments/297940849369546752/826484261925290004/2021-03-30_17-52-48.mp4

### Software information
AM2R 1.5.2 / the `Another Memetroid 2 Remake` mod.
In-game display settings: Fullscreen=disabled, window size=stretch, vsync=disabled, sensitivity mode=enabled

### System information
- GPU: AMD RX 570
- Driver: 2.0.179 (Vulkan: 1.2.170)
- Wine version: wine-6.5 (Staging)
- DXVK version: d9vk-0.40.1-croakacola-zero

### Apitrace file(s)
Trying to create an Apitrace on Linux crashes wine. I will edit this message later and create an apitrace from Windows.

### Log files
- d3d9.log: [AM2R_d3d9.log](https://github.com/doitsujin/dxvk/files/6230639/AM2R_d3d9.log)

**Comment by WinterSnowfall** [comment]
If you're launching the game from a terminal, it's worth trying out `DXVK_LOG_LEVEL=none`.

Had a potentially similar problem with Freelancer, where bringing up the ingame map would spam `warn:  ConvertFormat: Unknown format encountered:` messages and cause a temporary, but drastic, drop in framerate.

**Comment by Joshua-Ashton** [comment]
``DXVK: d9vk-0.40.1-croakacola-zero``

Dude that thing is ancient...

**Comment by iWeaker4you** [comment]
D9VK has not been used for a long time, it is already part of DXVK, it is a sooo old version

**Comment by Miepee** [comment]
Updated DXVK, it was an outdated version issue.
Closing the issue, and sorry for any inconvenience.
