### ISSUE TITLE
[d3d9] Dragon Nest - Effect issue

### ISSUE THREAD

**Issue by dnblank123** [doitsujin/dxvk#2001]
**Software information**

- Dragon Nest

**System information**

- GPU: Nvidia GTX 1050ti
- Driver: 456.98
- Windows 10
- DXVK version: 1.8.1

**Apitrace file(s)**
https://drive.google.com/file/d/16wglxk14gdbaiNRUuDXEdAmQb3ZOigrV/view?usp=sharing

**Log files**
d3d9.log: [DragonNest_x64_d3d9.log](https://github.com/doitsujin/dxvk/files/6240190/DragonNest_x64_d3d9.log)

[w/o DXVK]
![DN 2021-03-31 16-12-43 Wed](https://user-images.githubusercontent.com/67945097/113227239-be5ddd80-92c4-11eb-90d5-c2def661be36.png)![DN 2021-03-31 16-11-43 Wed](https://user-images.githubusercontent.com/67945097/113227232-bc941a00-92c4-11eb-9416-2876ce5fc117.png)

[DXVK]
![DN 2021-03-31 16-07-55 Wed](https://user-images.githubusercontent.com/67945097/113227273-dafa1580-92c4-11eb-980a-9d70c13e5a45.png)![DN 2021-03-31 16-06-58 Wed](https://user-images.githubusercontent.com/67945097/113227277-ddf50600-92c4-11eb-818c-affe1267bae4.png)

Currently using a fix provided by a modder. I'll just drop the DLL.
[dv-d3d_x64.zip](https://github.com/doitsujin/dxvk/files/6333599/dv-d3d_x64.zip)
The issue only happens if you have AMD/ATI card.
Also tried using customVendor/Device, it didn't work.

**Comment by algermakiputin** [comment]
Hi is this dragon nest sea on Linux using Wine?

**Comment by dnblank123** [comment]
> Hi is this dragon nest sea on Linux using Wine?

Windows 10

**Comment by dnblank123** [comment]
Fixed my issue by changing this value  `alphaSizeId = m_module.constf32(4096.0f);` to `(256.0f)` then enabled `d3d9.alphaTestWiggleRoom = true`

**Comment by DadSchoorse** [comment]
I tried to look into this, but I can't reproduce the issue using the apitrace, even with 1.8.1.

**Comment by dnblank123** [comment]
Closing since the game is changing to DX11.
