### ISSUE TITLE
[WINDOWS 10] [AMD] [D3D9] Dragon Nest hangs at random interval

### ISSUE THREAD

**Issue by frusio** [doitsujin/dxvk#2003]
Greetings, devs. I have a problem that annoy me, So i played a d3d9 based game named Dragon Nest. A generic Korean online MMORPG. At first month dxvk running great, but recently it crashes at random interval. It can be 5 to 2 hrs at max. Checked the log and the line ended with this error code;

err:   DxvkSubmissionQueue: Command submission failed: VK_ERROR_OUT_OF_DEVICE_MEMORY

Game : Dragon Nest
Graphic setting : Low to high

### System information
- GPU: Sapphire RX 560 Pulse 2GB
- Driver: 20.12.1 (tried 21.3.1, it has same error)
- Wine version: Tought i don't use wine? I dont clearly understand. I'm on latest Windows 10
- DXVK version: 1.8.1

Apitrace link : https://drive.google.com/file/d/1qCJCXfO6Wsg1KQNSwo72D8V_hP_48lYM/view?usp=sharing
Log link :  https://drive.google.com/file/d/1GeKmZiAGLC7OX8-eNHDlGW82DOMEIU-x/view?usp=sharing

Any kind of help is greatly appreciated. Thank you.

**Comment by K0bin** [comment]
> err: DxvkSubmissionQueue: Command submission failed: VK_ERROR_OUT_OF_DEVICE_MEMORY

This suggest it's another case of #1318. Unfortunately there's nothing we can do about that. Try to lower your texture details.

**Comment by Joshua-Ashton** [comment]
@K0bin No, its not an address space issue as it says **device** memory.

This guy literally just doesn't have enough VRAM.

Try enabling `d3d9.memoryTrackTest = True`

**Comment by frusio** [comment]
> 
> 
> @K0bin No, its not an address space issue as it says **device** memory.
> 
> This guy literally just doesn't have enough VRAM.
> 
> Try enabling `d3d9.memoryTrackTest = True`

Okies, i'll try this right away. Thank you so much for the guidance.

**Comment by frusio** [comment]
@Joshua-Ashton Man, you are my life saver, your config fix my problem. Now the gaming session remains 8 hrs (which my daily gaming time a day). Thank you so much for the help!

**Comment by deton24** [comment]
Same error in the log started happening suddenly in Call of Duty 4 (CoD4) OG using older 10.0.17763.1 DXVK 2.0.
`d3d9.memoryTrackTest = True` helped for freeze on startup. Thx.

Edit. Interestingly, the freezes on black screen on launch started later happening. 
The dissapear till I restart PC from a cold boot. It is like that every single day. When I restart for the second time, the same issue happens.
Now it shows `VK_ERROR_OUT_OF_DEVICE_MEMORY` in the log
Setting `d3d9.enableDialogMode = True` fixes the issue (but I think it might slightly mess with mouse feeling).

Tried restarting the driver with CRU utility (restart64), logging out, closing explorer, all compatibility options, setting memory in the conf file, using dsoal. Nothing. It looks like it has some issue with creating window IG. When it starts succesfully, it starts always minimized.
