### ISSUE TITLE
[D3D11] League of Legends crash RiotClientUxRender.exe. error RiotClientUx.exe

### ISSUE THREAD

**Issue by CGCathuman** [doitsujin/dxvk#2009]
After installing DXVK, RiotClientUxRender.exe crashes and RiotClientUx.exe starts up in black. If d3d11 is removed in winecfg, then the login launcher becomes normal, but the login to the main launcher gets errors.
I also tried to install d9vk separately, the same problems are found. 

### Software information
League of Legends

### System information
- GPU: NVIDIA Corporation GP107 [GeForce GTX 1050] 
- Driver: 460.67
- Wine version: 6.5-dev
- DXVK version:  1.8.1

### Apitrace file(s)
[trace.zip](https://github.com/doitsujin/dxvk/files/6254743/trace.zip)

### Log files
[LeagueClient_d3d9.log](https://github.com/doitsujin/dxvk/files/6254736/LeagueClient_d3d9.log)
[LeagueClient_dxgi.log](https://github.com/doitsujin/dxvk/files/6254737/LeagueClient_dxgi.log)
[RiotClientUxRender_d3d11.log](https://github.com/doitsujin/dxvk/files/6254738/RiotClientUxRender_d3d11.log)
[RiotClientUxRender_dxgi.log](https://github.com/doitsujin/dxvk/files/6254739/RiotClientUxRender_dxgi.log)

without dxvk:
![Screenshot_20210404_195407](https://user-images.githubusercontent.com/81894696/113512813-c7c69e80-957f-11eb-8444-fc2c38cdb1b2.png)

with dxvk:
![Screenshot_20210404_195054](https://user-images.githubusercontent.com/81894696/113512830-eb89e480-957f-11eb-821b-3023c56a534f.png)

**Comment by K0bin** [comment]
> err:   D3D11DXGIResource::GetSharedHandle: Stub

I think that means, it's trying to use shared resources.
If that's the case, I recommend disabling DXVK specifically for the launcher, as that's unlikely to work anytime soon.

**Comment by doitsujin** [comment]
It is impossible to support shared resources at the moment.

**Comment by CGCathuman** [comment]
> > err:   D3D11DXGIResource::GetSharedHandle: Stub
> 
> I think that means, it's trying to use shared resources.
> If that's the case, I recommend disabling DXVK specifically for the launcher, as that's unlikely to work anytime soon.

How to disable DXVK only for the launcher?
