### ISSUE TITLE
[Question] Is there a linux native replacement for DX11?

### ISSUE THREAD

**Issue by IvoAndonov** [doitsujin/dxvk#2013]
Is there a linux native replacement for DX11, meaning a d3d11.so or something else that linux will recognize as native and will use it as a native replacement of DX11? I know the question sounds weird but I don't wanna install the Windows version of the game bc it runs worse than the native linux version (native in linux - ultra settings; windows version - high settings at best).
I downloaded a mod for ETS2 which fixes the bad HDR SCS Software have made and almost everything is perfect with the exception of the fact that the sky is black. This happens because the person who made the mod, made the skybox textures for DX11. That's why I'm hoping that there's a native linux replacement for DX11. Ofc I could put the d3d11.dll and dxgi.dll in the folder where the executable file of the game is but I seriously doubt that this would work as intended.

**Comment by doitsujin** [comment]
The Linux version of the game obviously doesn't support D3D11.
