### ISSUE TITLE
ID3D11Device::OpenSharedResource implementation with Patch wine

### ISSUE THREAD

**Issue by Smeagolworms4** [doitsujin/dxvk#2014]
Hello

Developer Derek Lesho to create an implementation of shared resources in Wine-Devel

https://www.winehq.org/pipermail/wine-devel/2019-October/153443.html

does this patch change the situation for
ID3D11Device :: OpenSharedResource.

The other ticket https://github.com/doitsujin/dxvk/issues/899 being closed.
I understand that this ticket was also impacted: https://github.com/doitsujin/dxvk/issues/1747

Thank you for your reply.

**Comment by doitsujin** [comment]
This patch was never accepted upstream though so I don't really see how that helps?

We can start implementing this functionality once there is an *actual* solution for that in wine, and I would really appreciate if people would stop nagging us about it. We're aware it's an issue for a handful of applications (really, it's just a very small number of games that are affected).
