### ISSUE TITLE
Assassin's Creed 1 shows black screen in Dx10 mode.

### ISSUE THREAD

**Issue by MasterMynk** [doitsujin/dxvk#2015]
I have an install of Assassin's Creed 1 and if I try to launch AssassinsCreed_Dx10.exe with wine it shows the intro video and then just shows thr black screen. I can hear the sounds and if I wait enough the intro vid starts playing again.

The Dx9 version runs fine. The Dx10 version runs fine on Windows 10 so not an issue with my game install.

System:
Arch Linux
Ryzen 7 2700x
Radeon Rx 470

I had asked this on r/archlinux and someone over there said that I could open an issue here.

**Comment by K0bin** [comment]
Have you installed d3dcompiler?

`winetricks d3dcompiler_43`

If it's not that, we'd need logs.

**Comment by doitsujin** [comment]
AC1 is known to work with DXVK.

**Comment by MasterMynk** [comment]
> Have you installed d3dcompiler?
> 
> `winetricks d3dcompiler_43`
> 
> If it's not that, we'd need logs.

No I haven't tried d3dcompiler. Could you link an article on how to set it up? I don't have winettricks installed. I'm just using the wine from terminal.

**Comment by MasterMynk** [comment]
> AC1 is known to work with DXVK and is in fact the game I initially tested the D3D10 code with. Probably something missing on your setup, need a full wine log to tell what it is.

How could I get the wine log? I'm ready to post it here. (Sorry for such stupid questions, I'm still a beginner in this stuff)

**Comment by K0bin** [comment]
> Could you link an article on how to set it up?

You literally just need to copy and paste that line I posted into your terminal.

**Comment by MasterMynk** [comment]
Theres a lot of output when running the game and I don't think I will be able to paste it here. I tried putting thr output into a file but that didn't work.

> > Could you link an article on how to set it up?
> 
> You literally just need to copy and paste that line I posted into your terminal.

Yes I did this, it installed something but even after that the game didn't run.

Umm... I think I'll just close this issue as it might just be my Arch install. I was thinking of switching to Manjaro soon so hopefully things improve then. Thanks anyways and sorry for wasting your time.

**Comment by MasterMynk** [comment]
Hey guys I think its fixed. Now I don't know if the Manjaro installation fixed it or running `setup_dxvk --with-d3d10` fixed it. I think its the latter. I had run `setup_dxvk` first but I had run it without the --with-d310 flag so that might be it. Sorry for the trouble.
