### ISSUE TITLE
[D3D9] Red Orchestra 2

### ISSUE THREAD

**Issue by ByCybernetik** [doitsujin/dxvk#2016]
When loading some maps nothing is displayed except the HUD.
DXVK
![20210407125156_1](https://user-images.githubusercontent.com/45942960/113892716-f7b7b100-97ce-11eb-9d76-9c4fa8f2ec51.jpg)
D3D9 Native
![20210407001929_1](https://user-images.githubusercontent.com/45942960/113892865-1f0e7e00-97cf-11eb-91d8-c83c65283b6a.jpg)

### Software information
Red Orchestra 2: Heroes of Stalingrad with Rising Storm, ultra settings.

### System information
- GPU: Radeon RX 590
- Driver: RADV 
- Wine version: Proton 6.3-1
- DXVK version: Master

### Apitrace file(s)
- D3D9 Native
- https://drive.google.com/file/d/1Abixr2wdveoFsXSEVa6N22J3MhLHeH8D/view?usp=sharing

### Log files
- d3d9.log
- [ROGame_d3d9.log](https://github.com/doitsujin/dxvk/files/6272688/ROGame_d3d9.log)

**Comment by K0bin** [comment]
This comment is to document my findings, Josh told me he'll do the rest.

![image](https://user-images.githubusercontent.com/1131720/116761709-a3dc6880-aa18-11eb-89a6-0ae8f4e72c04.png)

The game sets a float constant to infinity, which most likely causes issues with D3D9s funky floating point rules. The infinity is then multiplied with a value that's 0, which causes it to become NaN. Apparently D3D9 expects anything * 0 = 0.

`9343501 @1 IDirect3DDevice9::SetPixelShaderConstantF(this = 0xc8e95a0, StartRegister = 0, pConstantData = [-inf, -0.000144277, 0, 0], Vector4fCount = 1) = D3D_OK`

**Comment by K0bin** [comment]
Should be fixed by c13395db970d16a5631a7c0926e2c4529d2710c3
