### ISSUE TITLE
[W10] AC Odyssey - crash when try to run the game

### ISSUE THREAD

**Issue by Acutake** [doitsujin/dxvk#2017]
Good day,

first, thank you for this kind of tools to help make games running with more fps 👍 

I am not a programmer, I am just poor gamer. I have Ryzen 5 3600, 16gb 3600Mhz RAM, RX 6800 XT with newest Adrenaline driver. Clean Windows 10 with newest updates. No "booster" tools, just pure Windows.

I want to play AC Odyssey with atleast 60fps without drops (but on my rig is not possible, even on Volumetric Cloud to low sometimes it drops below 60 or 55).

On Reddit I get advice to use DXVK. The tutorial was easy, download the ZIP file and put all *.dll files to folder where .exe is. So I done it. BVefore it I set the game to run in Windowed mode. 

But when I run the game, it shows the game was crashed, it's not running. The log says "Adapter is not a DXVK adapter".

So it's not that easy to just put the files to folder or I missing something?

Thank you :-) 

> warn:  D3D11CoreCreateDevice: Adapter is not a DXVK adapter
info:  Game: ACOdyssey.exe
info:  DXVK: v1.8.1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  Device properties:
info:    Device name:     : AMD Radeon RX 6800 XT
info:    Driver version   : 2.0.179
info:  Enabled device extensions:
info:    VK_AMD_memory_overallocation_behavior
info:    VK_AMD_shader_fragment_mask
info:    VK_EXT_4444_formats
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state
info:    VK_EXT_full_screen_exclusive
info:    VK_EXT_host_query_reset
info:    VK_EXT_memory_priority
info:    VK_EXT_robustness2
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_image_format_list
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_float_controls
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 1
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 1
info:    logicOp                                : 1
info:    multiDrawIndirect                      : 1
info:    drawIndirectFirstInstance              : 1
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 0
info:    fragmentStoresAndAtomics               : 1
info:    shaderImageGatherExtended              : 1
info:    shaderStorageImageExtendedFormats      : 1
info:    shaderStorageImageReadWithoutFormat    : 1
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 1
info:    shaderInt64                            : 1
info:    variableMultisampleRate                : 1
info:  VK_EXT_4444_formats
info:    formatA4R4G4B4                         : 1
info:    formatA4B4G4R4                         : 1
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 0
info:    customBorderColorWithoutFormat         : 0
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_extended_dynamic_state
info:    extendedDynamicState                   : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 1
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 1
info:    robustImageAccess2                     : 1
info:    nullDescriptor                         : 1
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 1
info:    geometryStreams                        : 1
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 2
info:  DXVK: Read 0 valid state cache entries
info:  DXVK: Using 7 compiler threads
warn:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
warn:  DxbcCompiler: Unsupported custom data block: DxbcCustomDataClass::Opaque
warn:  DxbcCompiler: Unsupported custom data block: DxbcCustomDataClass::Opaque
warn:  DxbcCompiler: Unsupported custom data block: DxbcCustomDataClass::Opaque
warn:  DxbcCompiler: Unsupported custom data block: DxbcCustomDataClass::Opaque
warn:  DxbcCompiler: Unsupported custom data block: DxbcCustomDataClass::Opaque
warn:  DxbcCompiler: Unsupported custom data block: DxbcCustomDataClass::Opaque
warn:  DxbcCompiler: Unsupported custom data block: DxbcCustomDataClass::Opaque
warn:  DxbcCompiler: Unsupported custom data block: DxbcCustomDataClass::Opaque
warn:  D3D11CoreCreateDevice: Adapter is not a DXVK adapter
info:  Game: ACOdyssey.exe
info:  DXVK: v1.8.1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
warn:  OpenVR: Failed to locate module
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  189819f1-1db6-4b57-be54-1821339b85f7
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  b898d4fd-b5b3-4ffc-8694-0259864ffcf8
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  9b7e4a00-342c-4106-a19f-4f2704f689f0
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  c4fec28f-7966-4e95-9f94-f431cb56c3b8
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  ffffffff-1bbe-4d12-afbf-8fdf7e0a87c7
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  c4fec28f-7966-4e95-9f94-f431cb56c3b8
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_10_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_10_0
info:  Device properties:
info:    Device name:     : AMD Radeon RX 6800 XT
info:    Driver version   : 2.0.179
info:  Enabled device extensions:
info:    VK_AMD_memory_overallocation_behavior
info:    VK_AMD_shader_fragment_mask
info:    VK_EXT_4444_formats
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state
info:    VK_EXT_full_screen_exclusive
info:    VK_EXT_host_query_reset
info:    VK_EXT_memory_priority
info:    VK_EXT_robustness2
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_image_format_list
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_float_controls
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 0
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 1
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 0
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 1
info:    shaderStorageImageExtendedFormats      : 1
info:    shaderStorageImageReadWithoutFormat    : 0
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 1
info:  VK_EXT_4444_formats
info:    formatA4R4G4B4                         : 1
info:    formatA4B4G4R4                         : 1
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 0
info:    customBorderColorWithoutFormat         : 0
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_extended_dynamic_state
info:    extendedDynamicState                   : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 1
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 1
info:    robustImageAccess2                     : 1
info:    nullDescriptor                         : 1
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 1
info:    geometryStreams                        : 1
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 2
info:  DXVK: Read 0 valid state cache entries
info:  DXVK: Using 7 compiler threads
warn:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT

**Comment by doitsujin** [comment]
> But when I run the game, it shows the game was crashed, it's not running. The log says "Adapter is not a DXVK adapter".

You need `dxgi.dll` as well.

**Comment by Acutake** [comment]
Thank you for your help.

So I deleted all files.

1) I go there - [https://github.com/doitsujin/dxvk/releases](url) and download **dxvk-1.8.1.tar.gz**
2) There are x32, x64 folders and setup_dxvk.sh . I open x64 folder and copy all 6 *.dll files to directory where the .exe is (D:\Steam games\steamapps\common\Assassins Creed Odyssey) - see img below
3) Run the game (using .exe or Steam) - Get crash info panel

If it's something bad with my computer, don't put effort to help me, I just want to know if I do something bad :-)

![folder](https://user-images.githubusercontent.com/7790249/114027892-28075a00-9878-11eb-9114-8b71b54edf72.jpg)
![crash](https://user-images.githubusercontent.com/7790249/114028142-6ef54f80-9878-11eb-8bf0-154d739434c5.jpg)

**Comment by LordJBeckman** [comment]
DXGI.dll and D3D11.dll should be all that is required here though I would also try with disabling the UPlay overlay since it has some other hooks (D3D9 ones I believe.) which might interfere a bit otherwise if this is left enabled.
(With Windows it's a bit of all or nothing you can't easily skip the overlay/Uplay launcher and how it injects with the DXVK files in the game folder as it's all started up.)

I haven't tested this against Odyssey though only Origins. (Odyssey had some rough issues that needed a couple of patches so outside of using ReShade I avoided any additional complications, Valhalla ended up utilizing D3D12 improving performance without DXVK's use.)

**Comment by spajdrEX** [comment]
You need to unzip only dxgi.dll and d3d11.dll, rest of the dxvk .dll files must be skipped/removed

**Comment by JorgePozoR** [comment]
I'm not having any issue with DXVK 1.9.1 and Odyssey under W10. It is important to run it Windowed or Borderless Windowed, and completely disable/remove all overlay programs (including but not limited to Windows own Game Bar, Steam overlay if using Steam, Ubisoft overlay from within  Uplay, and any and all GPU management program like MSI Afterburner and such).
Also, within Uplay I had to disable not only the in-game Overlay, but also the In-game Notifications.

I'm using nvidia latest public driver on W10 21H1. Running with HAGS on, not sure if this makes any difference to DXVK.

**Comment by Ryusennin** [comment]
I have no overlay conflict (Uplay, Radeon and even Reshade) with AMD drivers + DXVK in this game.

**Comment by FyiurAmron** [comment]
`warn: D3D11CoreCreateDevice: Adapter is not a DXVK adapter` and `warn: D3D11DXGIDevice::QueryInterface: Unknown interface query` may suggest that the `d3d11.dll` is loaded, but DXVK's `dxgi.dll` is either not provided or doesn't load (which is possible for many reasons). The solution I used (and which did wonders) was to rename DXVK's `dxgi.dll` to `dxgj.dll` and to change the imported DLL name accordingly in `d3d11.dll` (DXVK's one, not the system's :) - indeed, by looking at the logs it came to me as obvious that the DXVK's `dxgi.dll` is not even loaded, because DXVK's `d3d11.dll` tries to load system's one (dxgi's logs were empty).

YMMV, but this trick really helps on Windows.
