### ISSUE TITLE
Elder Scrolls Online: Missing textures on ANV

### ISSUE THREAD

**Issue by jpgrego** [doitsujin/dxvk#202]
### Software information
- Elder Scrolls Online
- Settings: Low

### Notes
So I was excited to use dxvk now that the Intel driver restriction was lifted. It works, but there seems to be a texture problem with ESO. 

### System information
- GPU: Intel HD 620
- Driver: 18.0.99
- Wine version: 3.4
- DXVK version: https://github.com/doitsujin/dxvk/commit/ac94c423800900ccfe346a1561aae5220d523b1a

### Apitrace file(s)
- https://mega.nz/#!olsn2RLJ!1xz4dZNRuG-UWuVF2TZi3P4PUd8NJasKbxVBnrmMfj8
### Log files
- [eso64_d3d11.log](https://github.com/doitsujin/dxvk/files/1844623/eso64_d3d11.log)
- [eso64_dxgi.log](https://github.com/doitsujin/dxvk/files/1844624/eso64_dxgi.log)

### Screenshots
![2018-03-24-170538_1920x1080_scrot](https://user-images.githubusercontent.com/461654/37867048-ea78878a-2f8a-11e8-9d38-e065df3dfbb9.png)
![2018-03-24-170613_1920x1080_scrot](https://user-images.githubusercontent.com/461654/37867052-f40a2b82-2f8a-11e8-9054-a785d56f38ae.png)

**Comment by doitsujin** [comment]
There has been very little testing so far with ANV, and their hardware may have limitations that DXVK does not respect properly. Can you run the game with
```
export WINEDEBUG=-all
export DXVK_DEBUG_LAYERS=1
```
and post the **full** console output?

Your apitrace renders fine on RADV:
![bildschirmfoto-564](https://user-images.githubusercontent.com/25567304/37867298-50899f0e-2f96-11e8-98a5-6ab84d230648.png)

**Comment by jpgrego** [comment]
Sure. You want me to replay the existing trace with those parameters, not make a new one, correct?

Also, just to be sure I didn't misunderstand: that trace was made without DXVK being applied, as the text that shows when one wants to make a new issue seemed to ask not to use DXVK with apitrace. Did I get that correctly?

**Comment by doitsujin** [comment]
@jpgrego yes and yes :)

**Comment by jpgrego** [comment]
Here it goes! Let me know if there's anything else you need.
[console_output.log](https://github.com/doitsujin/dxvk/files/1844673/console_output.log)

Also, that trace ends before I got into the world, for some reason the game crashed loading it. If you need a longer trace just say the word.

**Comment by doitsujin** [comment]
So the Vulkan validation layers don't have any objections. Might actually be a driver bug, in which case you might want to report it to Mesa. Sadly I don't have any Intel hardware to test on right now.

A longer trace won't really tell me anything I don't already know, so that's not necessary.

**Comment by jpgrego** [comment]
Yeah, I figured that might be it, as even without dxvk textures are missing, albeit different ones. It improved slightly with dxvk, as I can at least see the floor!

Thanks anyway man, I'll see about reporting this to Mesa. Keep up the good work!

**Comment by doitsujin** [comment]
Can you test this with latest mesa-git and DXVK? ANV has received some love for DXVK as of late, would be good to know if the game works properly now.

**Comment by jpgrego** [comment]
Hey, sorry for the delay. I'll compile the latest mesa and DXVK then. I'll be sure to chime in once I tested it.

**Comment by jpgrego** [comment]
I tried to run ESO with dxvk 0.70 and the latest wine (wine-3.9-124-g185d9ee7ebf5) but I get the following messages. Do you have any idea what's wrong?
[eso64_d3d11.log](https://github.com/doitsujin/dxvk/files/2320025/eso64_d3d11.log)
[eso64_dxgi.log](https://github.com/doitsujin/dxvk/files/2320027/eso64_dxgi.log)

**Comment by K0bin** [comment]
Something is wrong with your Vulkan setup. The readme also says that only Wine 3.10 and newer are supported.

**Comment by jpgrego** [comment]
Ah goddamn it, my bad. Thought I was using the latest version. Will compile a newer version and report back. Thanks.

**Comment by jpgrego** [comment]
I can run it now. And the reported issue is gone! The game now seems to function as it should. My only problem now is the low FPS, and the game is only kinda playable on low graphical settings. But I guess that is to be expected with onboard graphics.

Thanks and keep up the good work.

**Comment by doitsujin** [comment]
Thanks for the feedback.
