### ISSUE TITLE
Dal Segno (dxvk/src/util/config/config.cpp)

### ISSUE THREAD

**Issue by trenton4k** [doitsujin/dxvk#2022]
https://store.steampowered.com/app/638930/Dal_Segno/

game need  to run d3d9.deferSurfaceCreation = True

**Comment by doitsujin** [comment]
Please either file a PR to add it or give us at least a log file that shows the exe name.

**Comment by trenton4k** [comment]
[steam-638930.log](https://github.com/doitsujin/dxvk/files/6329115/steam-638930.log)

**Comment by trenton4k** [comment]
Command: ['/mnt/06C2B2D2C2B2C569/Steam/steamapps/common/Dal Segno/DST.exe']
