### ISSUE TITLE
"This application could not be started"

### ISSUE THREAD

**Issue by doonoo** [doitsujin/dxvk#2027]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
Preferably record the trace on Windows, or wined3d if possible.

**Reports with no log files will be ignored.**

### Software information
the setup software itself

### System information
- GPU: AMD 3200G
- Driver: vulkan_radeon
- Wine version: 6.6
- DXVK version: 1.8.1

### Apitrace file(s)
- Put a link here
![Screenshot_2021-04-17_21 20 28](https://user-images.githubusercontent.com/18385494/115131157-d1122b00-9fc3-11eb-9bb4-38412d117377.png)

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:
`wine: configuration in L"/home/doonoo/.wine" has been updated.
removed '/home/doonoo/.wine/dosdevices/c:/windows/system32/dxgi.dll'
'/usr/share/dxvk/x64/dxgi.dll' -> '/home/doonoo/.wine/dosdevices/c:/windows/system32/dxgi.dll'
removed '/home/doonoo/.wine/dosdevices/c:/windows/syswow64/dxgi.dll'
'/usr/share/dxvk/x32/dxgi.dll' -> '/home/doonoo/.wine/dosdevices/c:/windows/syswow64/dxgi.dll'
removed '/home/doonoo/.wine/dosdevices/c:/windows/system32/d3d9.dll'
'/usr/share/dxvk/x64/d3d9.dll' -> '/home/doonoo/.wine/dosdevices/c:/windows/system32/d3d9.dll'
removed '/home/doonoo/.wine/dosdevices/c:/windows/syswow64/d3d9.dll'
'/usr/share/dxvk/x32/d3d9.dll' -> '/home/doonoo/.wine/dosdevices/c:/windows/syswow64/d3d9.dll'
removed '/home/doonoo/.wine/dosdevices/c:/windows/system32/d3d10core.dll'
'/usr/share/dxvk/x64/d3d10core.dll' -> '/home/doonoo/.wine/dosdevices/c:/windows/system32/d3d10core.dll'
removed '/home/doonoo/.wine/dosdevices/c:/windows/syswow64/d3d10core.dll'
'/usr/share/dxvk/x32/d3d10core.dll' -> '/home/doonoo/.wine/dosdevices/c:/windows/syswow64/d3d10core.dll'
removed '/home/doonoo/.wine/dosdevices/c:/windows/system32/d3d11.dll'
'/usr/share/dxvk/x64/d3d11.dll' -> '/home/doonoo/.wine/dosdevices/c:/windows/system32/d3d11.dll'
removed '/home/doonoo/.wine/dosdevices/c:/windows/syswow64/d3d11.dll'
'/usr/share/dxvk/x32/d3d11.dll' -> '/home/doonoo/.wine/dosdevices/c:/windows/syswow64/d3d11.dll'`

**Comment by Joshua-Ashton** [comment]
Gonna need more info than that.

**Comment by doonoo** [comment]
> Gonna need more info than that.

https://forum.plutonium.pw/topic/9652/plutonium-bo2-waw-linux-tutorial?_=1618707581225

I tried follow this guide above for WAW, I did everything until the step to install dxvk, I installed dxvk-bin from the AUR, and when that didn't work, I downloaded it from the download page on here. Still returned the same thing

**Comment by doitsujin** [comment]
and this doesn't happen without DXVK?

**Comment by doonoo** [comment]
> and this doesn't happen without DXVK?
> 
> Also would be nice to at least mention the name of the application in the bug report......

I'm just trying to understand if dxvk installed or not? I hadn't even messed with BO2 yet

**Comment by doitsujin** [comment]
Well, my problem is that I *don't understand* what you're trying to do here and what your issue is. Which application exactly is it that shows the "application could not be started" window?

**Comment by doonoo** [comment]
> Well, my problem is that I _don't understand_ what you're trying to do here and what your issue is. Which application exactly is it that shows the "application could not be started" window? And does that even work on wine _without_ DXVK? Can you post a full wine log?

Oh, dxvk itself does this error when I try to install it. I'll post a full log when I get chance

**Comment by doitsujin** [comment]
DXVK **cannot** produce this error message because there is plain and simply no code for it.

Probably just a messed up wine prefix or something, nothing to fix here.
