### ISSUE TITLE
Mirror’s Edge: Crashes before starting the first level

### ISSUE THREAD

**Issue by SolarWave2** [doitsujin/dxvk#2028]
Mirror’s Edge crashes during the loading screen before the start of the first level. The training level works fine, but the bug happens after completing the training level. Skipping the training level and heading straight to the first level causes the same crash during the first level's cutscene. And the same error message appears with the development release of wine from the loading screen before the start of the first level as well as the cutscene for the first level if the training level is skipped:

err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_MEMORY_MAP_FAILED
wine: Unhandled page fault on write access to 00000000 at address 7AA6BD8C (thread 0188), starting debugger...

### Software information
Mirror's Edge 1.01

### System information
- GPU: AMD Radeon RX 580
- Driver: 21.0.1
- Wine version: Development release 6.6
- DXVK version: v1.7.3-4-g03f11baf

### Log files
[log.txt](https://github.com/doitsujin/dxvk/files/6330556/log.txt)

**Comment by DadSchoorse** [comment]
Sounds like a classic case of #1318 , make sure that you are using a wine build with forced large address awareness.

**Comment by mirh** [comment]
The game hardly uses 1GB even on highest settings on windows normally, and I'm not aware of texture mods. 
Unless OP has a 8K screen or something, this doesn't sound just a tiny matter.

**Comment by SolarWave2** [comment]
The issue was on my end. I did a rebuild of Wine development release 6.6, and now the crash doesn't happen anymore.
