### ISSUE TITLE
[WINDOWS 7][AMD][D3D9] Tom Clancy's Rainbow Six: Lockdown; Graphical Artifacts + Shadow Issues

### ISSUE THREAD

**Issue by springwurm** [doitsujin/dxvk#2029]
### Software information
- Name: Tom Clancy's Rainbow Six: Lockdown
- Settings: All Max (i can provide a Screenshot, but it's in German. i haven't found a way to change the menu language)

### System information
- GPU: AMD Radeon RX 570
- Driver: 2.0.179
- OS: Windows 7

### Apitrace file(s)
- https://mega.nz/file/jMkwTZrb#JQwazE_ebyetlcR-M7nS1tc-iiiufFHU0tZfj0T7JRs

### Log files
- d3d9.log: [windows_7_lockdown_d3d9.log](https://github.com/doitsujin/dxvk/files/6330593/windows_7_lockdown_d3d9.log)

### Note
Happens on Linux with Proton too. See: https://github.com/ValveSoftware/Proton/issues/2862

### Screenshots

![windows_7_20210413162324_1](https://user-images.githubusercontent.com/65482005/115136208-af925d00-a01e-11eb-9644-22930c836f04.jpg)
![windows_7_20210413162327_1](https://user-images.githubusercontent.com/65482005/115136211-b15c2080-a01e-11eb-9fbd-f6b6da7099c5.jpg)
![windows_7_20210413162333_1](https://user-images.githubusercontent.com/65482005/115136212-b15c2080-a01e-11eb-9da0-002bfff61f80.jpg)
![windows_7_20210413162335_1](https://user-images.githubusercontent.com/65482005/115136213-b28d4d80-a01e-11eb-9ce9-949524884355.jpg)

**Comment by Joshua-Ashton** [comment]
Probably needs feedback loop ext

**Comment by FurtadoPires** [comment]
This also affects Linux with amdgpu and mesa, but the glitched line in the middle of the screen was fixed in recent versions, so only the shadows issue remains

**Comment by springwurm** [comment]
> This also affects Linux with amdgpu and mesa, but the glitched line in the middle of the screen was fixed in recent versions, so only the shadows issue remains

please be a bit more specific about the mesa version you use.

**Comment by FurtadoPires** [comment]
> please be a bit more specific about the mesa version you use.

Mesa 21.0.2

Sorry, I should've been more specific, it's working with more recent wine / dxvk (not sure) using the GE fork

There're more details in my Proton Issue that you linked

**Comment by Blisto91** [comment]
Just noting that i also reproduce this on my R9 380 and mesa.
Both the line down the middle and shadow issue

**Comment by Blisto91** [comment]
Seems fixed in 2.3
