### ISSUE TITLE
Please add the official documentation to the Wiki about using DXVK HUD.

### ISSUE THREAD

**Issue by Kerrung** [doitsujin/dxvk#203]
Please add the official documentation to the Wiki about using DXVK HUD. I was able to find out how to use it only after I looked at the code for the patch that adds the DXVK HUD functionality. In my opinion this is not the easiest way to get documentation.

DXVK_HUD=fps
or
DXVK_HUD='fps device_info dxvk_info'

**Comment by Yardanico** [comment]
Just make a PR to readme :)

**Comment by Kerrung** [comment]
> Just make a PR to readme :)

Thank you

**Comment by Yardanico** [comment]
@Kerrung well, I mean I'm sorry that you had to look into source code, but you can always help others by improving wiki/readme

**Comment by Kerrung** [comment]
> @Kerrung well, I mean I'm sorry that you had to look into source code, but you can always help others by improving wiki/readme

I do not have permission to edit the wiki.

**Comment by Yardanico** [comment]
@Kerrung yeah, it's disabled in this repo, but you can still make a PR to Readme (and you don't really need to close this issue, maybe maintainer decides to  edit the wiki)

**Comment by Kerrung** [comment]
I found that it already exists in the readme, but as previously it was not there, I did not know that it was already added.

DXVK_HUD=1

**Comment by doitsujin** [comment]
The `DXVK_HUD` entry has been there ever since the HUD was added, and that was... 10 weeks ago I think?

**Comment by Yardanico** [comment]
@doitsujin @Kerrung talks about arguments like `fps`, `device_info`

**Comment by doitsujin** [comment]
But there are no such arguments. What exactly are you talking about?

**Comment by Yardanico** [comment]
@doitsujin ah, author of this issue was probably thinking that https://github.com/doitsujin/dxvk/pull/105 was merged
