### ISSUE TITLE
[Question] Does it auto update?

### ISSUE THREAD

**Issue by Toadfield** [doitsujin/dxvk#2031]
I wonder if it auto updates.
If it doesn't auto update,then this is a feature request for a separate version that auto updates,cause it would take a long time to update it manually for all my prefixes.

**Comment by Joshua-Ashton** [comment]
This is very clearly out of scope, and you know this.

**Comment by doitsujin** [comment]
> it would take a long time to update it manually for all my prefixes.

Just use the symlink option when installing it manually into a prefix and replace the DLLs?
DXVK is the absolute last thing that should download random stuff from the internet. Use Lutris for more convenient version updates.

**Comment by Toadfield** [comment]
> Just use the symlink option when installing it manually into a prefix and replace the DLLs?

What Symlink option?
I don't have any idea how to do that.

> Use Lutris for more convenient version updates.

I hate Lutris so much,cause:
1.I can't just launch games in the file manager
2.Adding games takes too long
3.I have to configure the winecfg of every prefix myself
4.I hate the ui

**Comment by doitsujin** [comment]
> What Symlink option?

`--symlink` as described in the readme.

**Comment by Toadfield** [comment]
But that only shows how I can update it for one prefix.
I want to update it for all prefixes that are located in one specific folder with only one command.

**Comment by Joshua-Ashton** [comment]
Symlink the same dlls into different prefixes

**Comment by Toadfield** [comment]
What I mean is,if I for example have many prefixes located in one folder,can I then select,that the dlls get installed to all prefixes in those folder?

**Comment by Toadfield** [comment]
I have another idea,what about an env var that if enabled auto updates dxvk?
Cause then we wouldn't need a different version for that.

**Comment by Joshua-Ashton** [comment]
No
