### ISSUE TITLE
Atelier Mysterious Trilogy Deluxe Pack (dxvk/src/util/config/config.cpp)

### ISSUE THREAD

**Issue by trenton4k** [doitsujin/dxvk#2035]
https://store.steampowered.com/bundle/20340/Atelier_Mysterious_Trilogy_Deluxe_Pack/

Command: ['/mnt/d68cd39d-6f9a-440c-853d-daddc3902ce8/Steam Games/steamapps/common/Atelier Sophie DX
Atelier_Sophie_DX_Launcher.exe
Atelier_Lydie_and_Suelle_DX.exe
Atelier_Lydie_and_Suelle_DX_Env.exe

Command: ['/mnt/d68cd39d-6f9a-440c-853d-daddc3902ce8/Steam Games/steamapps/common/Atelier Firis DX
Atelier_Firis_DX_Launcher.exe
Atelier_Firis_DX.exe
Atelier_Firis_DX_Launcher

Command: ['/mnt/d68cd39d-6f9a-440c-853d-daddc3902ce8/Steam Games/steamapps/common/Atelier Sophie DX
Atelier_Sophie_DX_Launcher.exe
Atelier_Sophie_DX.exe
Atelier_Sophie_DX_Env.exe

game need to run d3d9.deferSurfaceCreation = True

thx for your good work

**Comment by doitsujin** [comment]
We already have app profiles for all these games. Why did the exe names change all of the sudden?

**Comment by DadSchoorse** [comment]
Probably because it's the Deluxe Pack pack. :frog:

**Comment by trenton4k** [comment]
release todate  all DLCs and the new content included (Remaster)

**Comment by doitsujin** [comment]
i'm assuming the _env/_launcher executables don't need the workaround?

**Comment by doitsujin** [comment]
Added these in 4eb884303af9500de9690e924891e754c8bc7d6a.

**Comment by ryester27** [comment]
Am I missing something? Just tried Sophie DX with Proton-6.8-GE-1, and I still have the white screen at startup. This Proton-GE release should have a DXVK up to b84a03b4d4dc4907dde30d71e6823f45dad038f7, and I see d3d9.deferSurfaceCreation has been applied in the logs. I cleared the prefix before trying.

Logs attached:
[steam-1502970.log](https://github.com/doitsujin/dxvk/files/6456509/steam-1502970.log)
[Atelier_Sophie_DX_dxgi.log](https://github.com/doitsujin/dxvk/files/6456510/Atelier_Sophie_DX_dxgi.log)
[Atelier_Sophie_DX_d3d11.log](https://github.com/doitsujin/dxvk/files/6456511/Atelier_Sophie_DX_d3d11.log)
[Atelier_Sophie_DX_d3d9.log](https://github.com/doitsujin/dxvk/files/6456512/Atelier_Sophie_DX_d3d9.log)
