### ISSUE TITLE
[d3d9] GTA San Andreas - Broken rendering

### ISSUE THREAD

**Issue by NorbertHarangozo** [doitsujin/dxvk#2041]
As of b9512a40630c1e9030aa7958ce2456664bc3b059, rendering in GTA San Andreas is broken:
![image](https://user-images.githubusercontent.com/44706448/115788448-e6bc9180-a3c3-11eb-84ab-28f84f6ae9e8.png)

### Software information
GTA San Andreas, Steam version downgraded to 1.0.
Installed mods: Silent Patch, Widescreen fix.

### System information
- GPU: R7 260X 2GB
- Driver: RADV Git (21.2.0_devel.138607.abcefaffb16)
- Wine version: wine-tkg-staging-fsync-git-6.6.r6.g425f75f8
- DXVK version: 13f5353

### Apitrace file(s)
- [Same trace](https://mega.nz/file/Zpg2DYhJ#TzBB0fc4OehG3ERzHrywNXRo24q1rDicjnNEPGFVmlA) that can be found in #1664, the issue should be reproducible with the native trace.

### Log files
- [gta-sa_d3d9.log](https://github.com/doitsujin/dxvk/files/6361434/gta-sa_d3d9.log)

**Comment by K0bin** [comment]
I already fixed an issue with that commit, please retest with master.
