### ISSUE TITLE
Rocket League no longer running on NVIDIA

### ISSUE THREAD

**Issue by LiamDawe** [doitsujin/dxvk#2042]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

### Software information

Rocket League just refuses to work now. Black screen. It gives an almost fullscreen-window and then just stops from there.

![115989532-bbe65f00-a5b6-11eb-8977-097eea1e1c16](https://user-images.githubusercontent.com/83223/115992629-8f3a4380-a5c6-11eb-8aaa-a899e211f710.jpg)

### System information
- GPU: NVIDIA 1080
- Driver: 465.24.02
- Wine version: 6.7 staging (tested also with 6.6 and a bunch of older, all the same)
- DXVK version: 1.8.1

### Log files
[Sugar-lastPlay.log](https://github.com/doitsujin/dxvk/files/6371872/Sugar-lastPlay.log)

Some interesting bits:

> err:   DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
> err:   DxvkDevice: waitForIdle: Operation failed
> err:   DxvkSubmissionQueue: Command submission failed: VK_ERROR_DEVICE_LOST

So, an NVIDIA driver issue? It definitely worked fine previously.

**Comment by xpander69** [comment]
The log you pasted has super old DXVK

`info:  DXVK: v1.4.6-1-g1ae7d4b30`

**Comment by LiamDawe** [comment]
Shouldn't do, it says later in the log: 

> info:  DXVK: v1.8.1

**Comment by LiamDawe** [comment]
Okay this is a Heroic bug, it's not setting DXVK correctly.

Did a manual install, works fine.
