### ISSUE TITLE
[d3d9] Lightning Returns: Final Fantasy XIII

### ISSUE THREAD

**Issue by dlshinobi** [doitsujin/dxvk#2046]
Hi, 

The game renders without any graphical issues with DXVK 1.7.0, but going up to 1.8.1+, the 3D elements (world, models) is a mess, 2D elements (GUI) is fine.

If it's DXVK regression then it's between 1.7.0 - 1.7.1 releases.
Can't bisect any further, 'cause don't have DXVK build setup.

If it's nVidia driver problem, then why it's working with 1.7.0 and not 1.7.1 or above?

So to sum up: no matter of the drivers or wine/proton version, it works with 1.7.0, but not with 1.7.1 or above.

`winetricks d3dx9` didn't help.

P.S. Unrelated with the issue, but game spams a lot of this message, so can we just print this once?
https://github.com/doitsujin/dxvk/blob/525fd53bbc6c2c0ff73560bca9f543652035eddc/src/d3d9/d3d9_swapchain.cpp#L658

---

DXVK v.1.7.0:
![1 7 0](https://user-images.githubusercontent.com/7222444/116659699-a7310f00-a99a-11eb-8fb9-bc9804773277.png)

DXVK 1.8.1:
![1 8 1](https://user-images.githubusercontent.com/7222444/116659712-ac8e5980-a99a-11eb-814c-34572d8bf5e7.png)

### Software information
Lightning Returns: Final Fantasy XIII

### System information
- GPU: nVidia GTX 960
- Driver: stable (465.24.02), vulkan-dev (455.26.01, 455.50.14)
- Wine version: proton 5.13, proton 6.3 (experimental)
- DXVK version: 1.7.0 - 1.8.1 + master artifact.

### Apitrace file(s)
- apitrace: https://drive.google.com/file/d/1pNDpECJ_WH6iWzTLPTYCmLOxrXJ5_wOF/view?usp=sharing

### Log files
- d3d9.log: https://drive.google.com/file/d/1_u7Tm9Gs4A3gME8RQqEdW9seroolKmnO/view?usp=sharing

**Comment by Joshua-Ashton** [comment]
Does https://github.com/doitsujin/dxvk/pull/2050 fix the issue?

**Comment by dlshinobi** [comment]
> Does #2050 fix the issue?

Aha, works like a charm! Thank you! :thumbsup:
