### ISSUE TITLE
Problem with DX11's Advanced menu in Gothic 2 Gold

### ISSUE THREAD

**Issue by pm4rcin** [doitsujin/dxvk#2051]
### Description of the problem
Hi, I can't activate DX11's advanced menu in Gothic 2 Gold under wine. On Windows it works normally but here I can't activate that overlay. The "basic" settings overlay works normally. First [screenshot](https://imgur.com/dEUYk23.png) shows basic menu and [second](https://imgur.com/qXkO2NZ) shows advanced. Here's the talk with the author of renderer. https://github.com/Kirides/GD3D11/issues/46

> It uses a separate idxgi surface for the direct2d stuff from AntTweakBar iirc.
>
>Idk how that interferes with Linux / DXVK.
>
>It's basically some sort of child window inside the games window, that shares the same device for rendering.

### Software information
Gothic 2 Night of the Raven (gog version with Union patches installed through Lutris with default settings in Gothic.ini and SystemPack.ini)

### Reproduce G2NR installation
>     1. Install the game on prefix (I used gog version with automatic install from Lutris) and set prefix to 64-bit
> 
>     2. Add vcrun2008, vcrun2010, directmusic with winetricks in prefix and make sure you have wine-mono installed globally or install dotnet40 with winetricks in prefix
> 
>     3. Download [Resource Manager](https://worldofplayers.ru/resources/136/updates) and place it in the prefix folder
> 
>     4. In Resource Manager on Union tab install "PlayerKit 2.8 + Patch for 64-bit systems" AND Union (minimum 1.0j)
> 
>     5. Make sure that dsound is set to exactly "dsound(built-in, external)" and override ddraw to "ddraw(external, built-in) in winecfg
> 
>     6. [Download](https://github.com/Kirides/GD3D11/releases) and unpack DX11 files to Gothic2/System folder
> 
>     7. (Optional) Download normalmaps from [here](https://www.worldofgothic.de/dl/download_590.htm) and unpack them in System/GD3D11/Textures/replacements

### System information
- GPU: GTX 1650
- Driver: 465.27
- Wine version: 6.7
- DXVK version: 1.8.1
- Dist: Arch 5.11.16

### Apitrace file(s)
[Apitrace](https://gist.github.com/pm4rcin/72fcae0d9028d7b89340c15f4ba6f0a3)

### Log files
- [d3d11.log](https://gist.github.com/pm4rcin/d427e8abebfdc13d59f531c5abf08a38)
- [dxgi.log](https://gist.github.com/pm4rcin/6c500e3baeeeec80c8fb99d21d3fc77f)

**Comment by K0bin** [comment]
From the linked issue:

> It uses a separate idxgi surface for the direct2d stuff from AntTweakBar iirc.

AntTweakBar seems to query some undocumented interface off of the D3D11Device.

https://github.com/tschw/AntTweakBar/blob/4ff73b96515164cbe66b484022e56e771ea6c224/Renderer/compile/TwDirect3D11.cpp#L483

I guess we could just implement that and return the device itself. I dont really understand why they arent just querying the regular D3D11Device.

**Comment by doitsujin** [comment]
Does this work with wined3d?

**Comment by K0bin** [comment]
My bad, I assumed it corresponded to the log warning:
```
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  6543dbb6-1b48-42f5-ab82-e97ec74326f6
```

**Comment by pm4rcin** [comment]
Hi, sorry for late response. I've created .trace file and compressed it with zstd because I couldn't strip it under wine. So I loaded the game with wine vanilla 6.8, loaded save and clicked ctrl+f11 four times. [Here's the link](https://www.mediafire.com/file/ypngevw98o6mvzh/Gothic2.trace.tar.zst/file) to that file. If you have a suggestion to make it weight less please tell me.

**Comment by LDS1** [comment]
@pm4rcin it works fine for me in G2 (using proton + protontricks for configs). 
But in G1 Union prevents mouse cursor from appearing when dx11 ui is displayed, I had to disable union for the configuration.
Btw, I'm using avx build

**Comment by Blisto91** [comment]
I cannot reproduce this. Even with the dx11 versions that came out around the time this issue was created and with 1.8.1 dxvk.
The advanced menu shows fine for me.

This is on amd. If a test on nvidia is desired then i can try to set that up.

**Comment by Blisto91** [comment]
I have now tried this on a 960 470.103 with wine 7.6, dxvk 1.8.1 and the GD3D11 version around the time of this issue and i still cannot reproduce it.

I think this one can be closed. Lot's of dxvk, wine & GD3D11 versions have been released since. If it's still a problem for the OP the issue can just be reopened.

**Comment by pm4rcin** [comment]
@Blisto91 do you use GOG version or Steam?

**Comment by Blisto91** [comment]
Oh right... I again forget there can be differences between them. I am using the steam version.

My apologies. I will try the GOG version.

**Comment by pm4rcin** [comment]
I made it work with bottles. I'll try to post the config in case someone has problems.

**Comment by Blisto91** [comment]
Out of curiosity do you know the specific change that made it work? Or is it just a standard bottle with caffe or lutris wine.

**Comment by pm4rcin** [comment]
I think it was "Use virtual desktop". With that fullscreen problems are gone (I'm on [dwl](https://github.com/djpohly/dwl) so stability might be problematic in edge cases but it's really rare) and the advanced menu appears. I've used standard "Gaming" bottle with caffe. I'll make sure it was that option later.
