### ISSUE TITLE
[d3d9] Second Sight → missing HUD, subtitles, transition effect during cutscenes...

### ISSUE THREAD

**Issue by NerosTie** [doitsujin/dxvk#2056]
There are many issues with DXVK and Second Sight.

First, the HUD and the subtitles are missing:

WINED3D:
![Screenshot_20210510_200000](https://user-images.githubusercontent.com/4572452/117716616-1a782380-b1da-11eb-93b1-0b47d5486844.png)

DXVK:
![Screenshot_20210510_195457](https://user-images.githubusercontent.com/4572452/117716628-1e0baa80-b1da-11eb-9888-d6e8e8372da0.png)

Before the main menu, there is a screen with the title of the game, it's missing with DXVK:

WINED3D:
![Screenshot_20210510_201933](https://user-images.githubusercontent.com/4572452/117717762-85762a00-b1db-11eb-8e8e-7c72b480479a.png)

DXVK:
![Screenshot_20210510_215638](https://user-images.githubusercontent.com/4572452/117717708-71cac380-b1db-11eb-9000-ea5a379e7613.png)

During the cutscene of the first level, there are a transition effect which is missing with DXVK. Also notice that the 2 videos begin at the same time, so the black screen with the word "ISOLEMENT" is missing with DXVK.

WINED3D:
https://streamable.com/lsq57d

DXVK:
https://streamable.com/xaoip4

### System information
- GPU: AMD RX 580
- Driver: Mesa 21.1.0
- Wine version: proton-experimental (2021/05/07)
- DXVK version: 1.8.1 (also tested with the last [dev build,](https://github.com/doitsujin/dxvk/actions/runs/821617018) same results)

### Apitrace file(s)
I can't get one... I've tried everything but the wrapper does nothing or it's ignored. I even tried with a GOG version found *somewhere* but with the same result... If someone knows how to get one, please upload it, it would be a great help!

### Log files
[steam-11550_dxvk.log](https://github.com/doitsujin/dxvk/files/6454676/steam-11550_dxvk.log)
[steam-11550_wined3d.log](https://github.com/doitsujin/dxvk/files/6454677/steam-11550_wined3d.log)

**Comment by Joshua-Ashton** [comment]
I cannot do anything without an apitrace I am afraid.

**Comment by NerosTie** [comment]
I tried for 2+ hours to have an apitrace but with no success, I really don't know what's the issue with this game or where I do something wrong :/

**Comment by DadSchoorse** [comment]
> I can't get one... I've tried everything but the wrapper does nothing or it's ignored. I even tried with a GOG version found somewhere but with the same result... If someone knows how to get one, please upload it, it would be a great help!

Just an uneducated guess, maybe the game load d3d9.dll from the windows directory directly.

You can check that by looking at the log if you put the wrapper next to the .exe, if this is still the only place that `d3d9.dll` shows up then it doesn't load the wrapper.

```
19933.741:010c:0110:trace:loaddll:build_module Loaded L"C:\\windows\\system32\\d3d9.dll" at 62440000: native
```

If that's the case try putting the apitrace wrapper in `windows/syswow64` in the prefix and and use `APITRACE_FORCE_MODULE_PATH` to point towards the directory you moved the original dll to.

**Comment by NerosTie** [comment]
No luck, or I'm not doing it right.

**Comment by Oschowa** [comment]
I recorded an apitrace (using wined3d) that shows the problem:
https://drive.google.com/file/d/1Q0qLpyR_fbjD1P6JCRHS_BZCanGjg2Zv/view?usp=sharing

**Comment by NerosTie** [comment]
@Oschowa Thanks!
But how did you manage to do it? I'm very curious.

**Comment by Oschowa** [comment]
What DadSchoorse guessed was right, the game only loads d3d9.dll from the windows directory, so i copied wined3d's d3d9.dll form syswow64 to /tmp/wined3d, dumped the apitrace d3d9.dll into syswow64 and ran the game with `APITRACE_FORCE_MODULE_PATH="/tmp/wined3d" WINEDLLOVERRIDES="d3d9=n,b" wine game.exe.
This needs to be done manually and not from steam or using the proton run script because otherwise your modification to the prefix' syswow64 will be overwritten.

**Comment by NerosTie** [comment]
Tested and everything is fixed, thanks! :)
