### ISSUE TITLE
Reshade compute shader issue - shader not optimizing?

### ISSUE THREAD

**Issue by gabriele2000** [doitsujin/dxvk#2058]
I've got 2 version of the RTGI shader.
RTGI 0.22 - uses compute shader: always takes 32ms of frametime (should be GPU-accelerated, so it should be less ms-hungry)
RTGI 0.21 - is a standard shader: takes up to 12ms, could even take less (depends on scene complexity)

Now, I read somewhere that if that happens, maybe the driver fails to optimize the shader.
I don't know if the issue is from:
-DXVK
-Wine
-Nvidia

**Comment by gabriele2000** [comment]
> DXVK just naively translates the DXBC shader code to SPIR-V, so the driver probably doesn't optimize it as efficiently as it does the D3D shader if it's much slower than on Windows. Not really something we can really fix on our end, though.

So basically for compute shaders to run efficently we'll have to wait Nvidia?
What about AMD? Is this an issue with AMD too?

**Comment by Blisto91** [comment]
@gabriele2000 Friendly ping. Even if this isn't a dxvk issue i'm just checking in on if you still have this problem with newest dxvk, RTGI and driver?

**Comment by gabriele2000** [comment]
> @gabriele2000 Friendly ping. Even if this isn't a dxvk issue i'm just checking in on if you still have this problem with newest dxvk, RTGI and driver?

You know, right now I'm using the latest RTGI version (0.32.2) and I guess it's compute shader again, because it got eventually removed for compatibility reasons.
Now I'm using AMD FSR too, so the frametime lowers as well, though.

I guess it's "fixed" for now, RTGI is still a lot demanding, but it's way less demanding now than a year ago, or when it was first introduced as compute shader.

**Comment by K0bin** [comment]
Either way, optimizing shaders is the job of the driver.
