### ISSUE TITLE
Halo 2 fog drawing only in half

### ISSUE THREAD

**Issue by NukeULater** [doitsujin/dxvk#2059]
### Software information
Halo 2 for Windows Vista with Project Cartographer mod
High settings, no MSAA enabled.

### Broken behaviour
![image](https://user-images.githubusercontent.com/18323679/118024161-07468e80-b367-11eb-8aeb-385f8f8c2098.png)

### Normal behaviour (d3d9)
![image](https://user-images.githubusercontent.com/18323679/118024204-1594aa80-b367-11eb-966c-508c4e65a47d.png)

### System information
- GPU: GTX 1050
- Driver: 466.27.0
- Windows 10 version: - 20H2 build 985

### Apitrace file(s)
- [apitrace](https://drive.google.com/file/d/1Aa57W5m2pbyAqNGyL3hDMJLTftD13U_s/view?usp=sharing)

### Log files
- d3d9.log: 
[halo2_d3d9.log](https://github.com/doitsujin/dxvk/files/6468283/halo2_d3d9.log)

### Notes:
Tested and broken with: https://github.com/doitsujin/dxvk/commit/b84a03b4d4dc4907dde30d71e6823f45dad038f7
Works with: https://github.com/doitsujin/dxvk/commit/13f53531e512f1b140dafef25b0bf13739fbad04

**Comment by Joshua-Ashton** [comment]
Fixed by 0520ce944813d936e61a559b6bde62b19326599b
