### ISSUE TITLE
Atelier Sophie DX still white screen after 4eb8843 commit

### ISSUE THREAD

**Issue by ryester27** [doitsujin/dxvk#2063]
Probably should have created a new issue for this instead of responded to a closed one

Just tried Sophie DX with Proton-6.8-GE-1, and I still have the white screen at startup. This Proton-GE release should have a DXVK up to b84a03b4d4dc4907dde30d71e6823f45dad038f7, and I see d3d9.deferSurfaceCreation has been applied in the logs. I cleared the prefix before trying.

Logs attached:
[steam-1502970.log](https://github.com/doitsujin/dxvk/files/6456509/steam-1502970.log)
[Atelier_Sophie_DX_dxgi.log](https://github.com/doitsujin/dxvk/files/6456510/Atelier_Sophie_DX_dxgi.log)
[Atelier_Sophie_DX_d3d11.log](https://github.com/doitsujin/dxvk/files/6456511/Atelier_Sophie_DX_d3d11.log)
[Atelier_Sophie_DX_d3d9.log](https://github.com/doitsujin/dxvk/files/6456512/Atelier_Sophie_DX_d3d9.log)

_Originally posted by @ryester27 in https://github.com/doitsujin/dxvk/issues/2035#issuecomment-837787385_

**Comment by doitsujin** [comment]
> info:  DXVK: v1.8.1-async

Please do not report bugs with unofficial patch sets.

**Comment by ryester27** [comment]
Sorry about that. I reuploaded the logs using Proton 6.3-3 and the latest DXVK build 0520ce944813d936e61a559b6bde62b19326599b
[Atelier_Sophie_DX_d3d9.log](https://github.com/doitsujin/dxvk/files/6478802/Atelier_Sophie_DX_d3d9.log)
[Atelier_Sophie_DX_d3d11.log](https://github.com/doitsujin/dxvk/files/6478803/Atelier_Sophie_DX_d3d11.log)
[steam-1502970.log](https://github.com/doitsujin/dxvk/files/6478804/steam-1502970.log)

If this doesn't show you anything different, then I guess it's up to Wine to fix?

**Comment by doitsujin** [comment]
According to https://www.protondb.com/app/1502970 it works fine for other users with the workaround, so not sure what's wrong here.

**Comment by ryester27** [comment]
> According to https://www.protondb.com/app/1502970 it works fine for other users with the workaround, so not sure what's wrong here.

I figured it out. It was mesa-tkg-git causing the issue. Reverted back to the mesa package provided by the official Arch repos, and everything worked fine again.

The game window starts up minimized, but I doubt that's a DXVK problem
