### ISSUE TITLE
Is it possible to start minecraft on vulkan?

### ISSUE THREAD

**Issue by Aspector1** [doitsujin/dxvk#2066]
Is it possible to start minecraft on vulkan? Some games created on unity with opengl support conversion to vulkan.

**Comment by ZachBacon** [comment]
Nope, dvxk is a direct3d to vulkan project, not an OpenGL to vulkan one.

**Comment by Aspector1** [comment]
> Nope, dvxk is a direct3d to vulkan project, not an OpenGL to vulkan one.

But some games built on opengl can easily convert to vulkan. Such as "It's winter" or "ravenfield".

**Comment by ZachBacon** [comment]
> > Nope, dvxk is a direct3d to vulkan project, not an OpenGL to vulkan one.
> 
> But some games built on opengl can easily convert to vulkan. Such as "It's winter" or "ravenfield".
> 

Again, not the scope of the project, it's direct3d to vulkan, ever heard of the adage, do one thing, and do it right? Yeah it's a direct3d to vulkan project, not OpenGL to vulkan.

**Comment by Joshua-Ashton** [comment]
No

**Comment by Faalagorn** [comment]
> Is it possible to start minecraft on vulkan? Some games created on unity with opengl support conversion to vulkan.

You can use zink, but it's out of scope of this project: https://docs.mesa3d.org/drivers/zink.html
