### ISSUE TITLE
Kingdoms of Amalur: Re-Reckoning anisotropy rendering artifacts

### ISSUE THREAD

**Issue by Darkloke** [doitsujin/dxvk#2069]
Greetings. I have a problems with this game after enabling anisotropic filtering (d3d11.samplerAnisotropy = X) through dxvk.conf (only this line enabled, other values by default). As shown on screens: the greater the level of anisotropy, the more red pixels it shows.

AF x2
![amalur_vk_x2](https://user-images.githubusercontent.com/4979638/119254650-2394c780-bbc0-11eb-8c97-85c374445836.png)
AF x4
![amalur_vk_x4](https://user-images.githubusercontent.com/4979638/119254655-28597b80-bbc0-11eb-977a-c9e8fbfde04a.png)
AF x8
![amalur_vk_x8](https://user-images.githubusercontent.com/4979638/119254662-2d1e2f80-bbc0-11eb-8cdf-fbc07a8c7545.png)
AF x16
![amalur_vk_x16](https://user-images.githubusercontent.com/4979638/119254644-1e377d00-bbc0-11eb-8eee-5d57522c905b.png)

### Software information
Kingdoms of Amalur: Re-Reckoning [GOG 1.5 (42638)]

### System information
- GPU: Geforce GTX 1060 6Gb
- Driver: 457.51
- Windows version: Windows 10 20H2
- DXVK version: 1.8.1

### Log files
[koa_d3d11.log](https://github.com/doitsujin/dxvk/files/6527809/koa_d3d11.log)
[koa_dxgi.log](https://github.com/doitsujin/dxvk/files/6527810/koa_dxgi.log)

**Comment by doitsujin** [comment]
This is not a bug; if you mess around with settings and override the game's settings then this kind of thing may happen. Some rendering techniques the game uses just don't play nicely with anisotropic filtering.

**Comment by ro6yn** [comment]
I have same issue on latest versions of drivers, same version of game, same GPU, DXVK 1.9.2. Is it possible now to fix these red artifacts and keep anisotropic filtering enabled?
