### ISSUE TITLE
create a patreon page

### ISSUE THREAD

**Issue by techsupp82** [doitsujin/dxvk#207]
it´s the best way to finance projects, open source/ every project need finance, that´s it.

some examples

https://www.patreon.com/antergos
https://www.patreon.com/libretro
https://www.patreon.com/godotengine
https://www.patreon.com/solus
https://www.patreon.com/Nekotekina
https://www.patreon.com/yorikvanhavre
https://www.patreon.com/marcjeanmougin
https://www.patreon.com/lutris
https://www.patreon.com/kozec
https://www.patreon.com/kovidgoyal
https://www.patreon.com/openfl
https://www.patreon.com/flibitijibibo
https://www.patreon.com/armory

**Comment by kiljacken** [comment]
Or go with (LiberaPay)[https://en.liberapay.com/] to avoid the nasty Patreon ToS.

**Comment by mdrost** [comment]
IMHO better is payment per fixed issue via platforms like https://www.bountysource.com/
