### ISSUE TITLE
Assassin's creed 3 broken snow

### ISSUE THREAD

**Issue by somebody1121** [doitsujin/dxvk#2071]
The snow doesn't work properly ~~on AMD, but spoofing as an NVIDIA make it work  properly.~~

Bug:
![snowBug](https://user-images.githubusercontent.com/82600134/119680595-9eb8e080-be41-11eb-9796-134ef91f8e45.png)

~~Spoofed as NVIDIA~~ With low quality:
![fixed](https://user-images.githubusercontent.com/82600134/119680963-f0fa0180-be41-11eb-9a63-e8e9a27be5ed.png)

### Software information
The executable name is AC3MP.exe and AC3SP.exe
Happens on the max setting of enviroment quality.

### System information
- GPU: RX 580
- Driver: mesa 21.1.1
- Wine version: lutris 6.4
- DXVK version: 1.8.1

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log: [AC3SP_d3d9.log](https://github.com/doitsujin/dxvk/files/6547494/AC3SP_d3d9.log)
- d3d11.log: [AC3SP_d3d11.log](https://github.com/doitsujin/dxvk/files/6547492/AC3SP_d3d11.log)
- dxgi.log: [AC3SP_dxgi.log](https://github.com/doitsujin/dxvk/files/6547488/AC3SP_dxgi.log)

**Comment by doitsujin** [comment]
Does this even work on Windows?

**Comment by somebody1121** [comment]
> Does this even work on Windows?

I don't have install windows to test but setting dxgi.customDeviceId = 0402 dxgi.customVendorId = 10de on dxvk.conf makes it work properly

**Comment by somebody1121** [comment]
I thought that it was fixed, but no, since spoofing as nvidia reset the graphic configuration to the lowest value, by setting the enviroment quality to the max it happens, with the other two doesn't.

**Comment by Blisto91** [comment]
@somebody1121 Friendly ping. Could i get you to retest this with latest dxvk and drivers? :slightly_smiling_face:

**Comment by somebody1121** [comment]
> @somebody1121 Friendly ping. Could i get you to retest this with latest dxvk and drivers? slightly_smiling_face

Sorry for not replying sooner. It appears to be fixed, tested on the lastest drivers and dxvk.
![fix](https://user-images.githubusercontent.com/82600134/196751584-d60e5fed-f4fe-43b3-bae1-2175b8cce4a7.png)
