### ISSUE TITLE
DXVK is not compatible w/ wine >=6.8

### ISSUE THREAD

**Issue by ElJdP** [doitsujin/dxvk#2072]
I've played Rocket League for a while now. I obviously use the Heroic Launcher, and since ~4 days, Rocket League does not launch anymore, as the terminal screenshot shows below. It is not a problem with Rocket League alone, because I have tried with other games as well – the same log appears, no matter the game. I also asked in winehq, and they said it was a DXVK issue and not a wine one, so that's why I'm asking here. 

### System information
- GPU:AMD® Radeon(tm) vega 3 graphics
- Driver:00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 IOMMU
- Wine version: 6.8
- DXVK version: 9

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
- d3d11.log:
![image](https://user-images.githubusercontent.com/68053570/119962621-85ca3f80-bfa7-11eb-8627-8daa059c5cd3.png)

- dxgi.log:

**Comment by Joshua-Ashton** [comment]
This isn't a DXVK issue. Your Vulkan driver setup is broken.

Can you try with `WINEDLLOVERRIDES=dxgi=n`, it looks like you are using Wine's DXGI and not ours so it's probably falling back to lavapipe or something stupid.

**Comment by doitsujin** [comment]
Probably just lavapipe issues again... nothing to do with wine 6.8.

We'll have a new release soon-ish that blacklists lavapipe for good, because somehow games keep picking that over actual GPUs for no real reason. In the meantime, use DXVK's DXGI, use ```DXVK_FILTER_DEVICE_NAME```, or grab [this](https://github.com/doitsujin/dxvk/actions/runs/861945123) build.

**Comment by maxiking01** [comment]
I also have problems with DXVK on wine 6.8>= . It occurs when trying to launch Steam either on Intel or Nvidia GPU. The logs are in [here](https://www.dropbox.com/sh/nogr9632sx4sxrc/AACe2kJ2MRzLEdUspSpO-tr8a?dl=0) . Logs are for two graphics cards and with and without dxvk. Problem also manifests in other programs like Foobar2000 by crashing.

**Comment by doitsujin** [comment]
@maxiking01 and what problems do you have exactly?

**Comment by maxiking01** [comment]
The main issue is steam hangs in main window when I install dxvk. There aren't any crashes. It affects other programs as well. In case foobar2000 app crashes. When I don't install the dxvk steam starts normally. I looked at logs in both cases, but I couldn't notice anything suspicious. I'll provide additional logs if you need it.

**Comment by doitsujin** [comment]
Steam works fine here with wine-tkg 6.9 and it worked fine with 6.8.
