### ISSUE TITLE
crash on launch Stalker SoC with d3dx9 gtx 950

### ISSUE THREAD

**Issue by JIuBeP** [doitsujin/dxvk#2073]
**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
Preferably record the trace on Windows, or wined3d if possible.

### Software information
Stalker Shadow of Chernobyl settings high - dynamic lighting

### System information
- GPU: gtx 950
- Driver: 461.72
- Windows 7
- DXVK version: 1.8.1 

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log: 
[XR_3DA_d3d9.log](https://github.com/doitsujin/dxvk/files/6565744/XR_3DA_d3d9.log)

**Comment by Joshua-Ashton** [comment]
You don't have a Vulkan driver installed.

**Comment by JIuBeP** [comment]
in fact, I have a vulkan driver, and I played Fallout 3\ NV without any problems, MSI Afterburner identified as a vulkan, but for some reason in Stalker such a problem.

**Comment by Joshua-Ashton** [comment]
I mean, you can't. It says

`info:  Required Vulkan extension VK_KHR_surface not supported` which implies you have no driver.

Something about your setup must have changed since then, I imagine Fallout 3 with DXVK wouldn't work either/
