### ISSUE TITLE
[Question] How can I install it with --symlink and --with-d3d10

### ISSUE THREAD

**Issue by Toadfield** [doitsujin/dxvk#2078]
I want to install it with the --symlink cause I can update it for every prefix and --with-d3d10 cause I want d3d10 compatibility.
So how exactly can I do that?
I assume that I have to install it to let's call it prefix x via
```
export WINEPREFIX=path/to/prefix\ x
./setup_dxvk.sh install
```
normally,and then install the it to let's say prefix y via
```
export WINEPREFIX=path/to/prefix\ y
./setup_dxvk.sh install --symlink --with-d3d10
```
and then when I want to update it I have to update the dxvk from prefix x to update prefix y,but I don't know if that is how it works.

**Comment by Joshua-Ashton** [comment]
You don't need ``--with-d3d10`` for d3d10 to work.

**Comment by Toadfield** [comment]
But what does `--with-d3d10` do then?
And also,how can I install it with `--symlink` correctly?
And also,if I just install it with --symlink for the first time,where does it point to?

**Comment by Toadfield** [comment]
So I created a prefix and installed dxvk with `--symlink`,but it doesn't seem like it created symlinks of the the dxvk dll,so what do I do wrong?

**Comment by doitsujin** [comment]
`--with-d3d10` just copies `d3d10.dll` as well, which is actually *not* needed for D3D10 to work.
`--symlink` makes it create symlinks to the DLLs *inside the wine prefix*, so you'll need to look there.

**Comment by Toadfield** [comment]
> --with-d3d10 just copies d3d10.dll as well, which is actually not needed for D3D10 to work since the important bit is d3d10core.dll.

So what is the advantage of using it then?
>--symlink makes it create symlinks inside the wine prefix to the DLLs inside the directory you're installing DXVK from.

So if I got it right then when I install it with the --symlink option and then copy that prefix with the symlink and update one of the prefixes dxvk,then it is updated for all of them?
But then,hw can I update it correctly,do I just have to install the normal dxvk to any prefix or do I need to install it with --symlink? (cause then I couldn't update all prefix dxvk version with winetricks).

**Comment by doitsujin** [comment]
> So if I got it right then when I install it with the --symlink option and then copy that prefix with the symlink and update one of the prefixes dxvk,then it is updated for all of them?

No, because the symlinks don't point to any prefix but rather the files inside your DXVK directory. So you'd have to replace the files in there in order to get all your prefixes updated.

> So what is the advantage of using it then?

There is none these days, which is why it is disabled by default.......

**Comment by Toadfield** [comment]
> You'd have to replace the files in there in order to get all your prefixes updated and also use the symlink options for all your prefixes.

Which files do I have to replace and how?
Do I just have to download the latest dxvk,then delete everything in the old dxvk folder and place the new ones in and then all the symlink prefixes are updated or how should I do that?
And also,can I make a bash script that updates dxvk?

**Comment by doitsujin** [comment]
> Do I just have to download the latest dxvk,then delete everything in the old dxvk folder and place the new ones in and then all the symlink prefixes are updated or how should I do that?

Yes. Let's say you unpacked your dxvk to `$HOME/dxvk` (which would be where `setup-dxvk.sh` as well as the `x32` and `x64` directories are) and use the symlink option, simply delete it and unpack a newer version to `$HOME/dxvk` in order to update. That's the whole point of that option.
