### ISSUE TITLE
assertion fails on amdvlk

### ISSUE THREAD

**Issue by niansa** [doitsujin/dxvk#2082]
Subnautica.exe: /builddir/amdvlk-2021.Q2.3/llvm-project/llvm/include/llvm/Support/Casting.h:269: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::ConstantInt; Y = llvm::Value; typename llvm::cast_retty<X, Y*>::ret_type = llvm::ConstantInt*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
Game: `Subnautica, version DVD`
Distro: `Void Linux`
Kernel: `5.11.22_1 #1 SMP 1621481187 x86_64 GNU/Linux`

**Comment by doitsujin** [comment]
Probably a driver bug. Need an apitrace to confirm; game seems to work fine here on RADV and you didn't provide any instructions on how to reproduce the problem.

**Comment by niansa** [comment]
Issue occured right on startup, I solved it by installing another distro
