### ISSUE TITLE
GW2 dxvk with other addons?

### ISSUE THREAD

**Issue by YamiN0Neko** [doitsujin/dxvk#2083]
Hello, is there a possible way to use dxvk with other addons like radial mount, arcdps, and reshade? 
I tried putting the dll of the dxvk next to the exe of the gw2 and the dll of radial mount and arcdps in the bin64 but only radial and arcpds was being detected and I tried using just reshade along as well but even when installing reshade for vulkan it didnt detected while the dll of the dxvk was in the 64 or next to the exe.

If there is no possible way to get all this addons to work together with dxvk then I will just continue using d912pxy for now.

**Comment by Joshua-Ashton** [comment]
For Reshade you can use the env var `RESHADE_MODULE_PATH_OVERRIDE` to point to a directory containing DXVK dlls for Reshade to use.

As for the others, you'd need to ask their authors. AFAIK ArcDPS uses some weird DWM stuff for it's overlay so it should work in theory. I have no idea about Radial Mount.
