### ISSUE TITLE
[d3d9] Resident Evil 0 (339340) - Frametime issue on some scenes

### ISSUE THREAD

**Issue by ScarecrowDM** [doitsujin/dxvk#2084]
### Software information
Resident Evil 0 (steam AppID 339340).
When switching to some scenes, framerate is cut by half with terrible frame spikes. 

Video demonstrating the issue: https://drive.google.com/file/d/1B2bNTYVpMZlbLcmAXbfLJNmwV6Gkaf1J

I can reproduce this issue as well on windows with DXVK.
Wine3D works fine, however.

### System information
- GPU: Vega 56;
- Driver: Mesa 21.1.1;
- Wine version: Proton / Proton Experimental;
- DXVK version: master (f4cbc9ae9d4795c5fa4d37715c09b59fcb0358bd)

### Apitrace file(s)
- https://drive.google.com/file/d/11Kl5JpH373kKZrQJsT80ockmhAggUMwK

### Log files
- d3d9.log: https://drive.google.com/file/d/1XSVRpXtW8JIDjv37uTR-t1FRMIz4I8U4 (log lists dxvk as being on 1.8.1 version due to proton experimental being weird for whatever reason)

**Comment by K0bin** [comment]
Putting this here so it doesnt get lost:
The game stalls on a D3DPOOL_DEFAULT + D3DUSAGE_DYNAMIC vertex buffer that it locks like once per frame. DXVK chooses the direct mapping mode, so it has to wait for the previous frame.

**Comment by ScarecrowDM** [comment]
I don't know if this issue got fixed on master or mitigated somehow, but i can't reproduce this behavior in game anymore (i didn't try to reproduce it with the trace yet).
I'll play a bit longer tonight, but so far so good.

- GPU: Vega 56;
- Driver: Mesa 21.3.0;
- Wine version: Proton 6.3-7;
- DXVK version: master.

[https://i.imgur.com/gpUEktT.png](https://i.imgur.com/gpUEktT.png)
