### ISSUE TITLE
DeBlob 2 won't start

### ISSUE THREAD

**Issue by niansa** [doitsujin/dxvk#2087]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
Preferably record the trace on Windows, or wined3d if possible.

**Reports with no log files will be ignored.**

### Software information
OpenSuse Tumbleweed, De Blob 2 (from Discord Store)

### System information
- GPU: Radeon RX 580
- Driver: amdvlk
- Wine version: 6.9
- DXVK version: 1.8.1

### Apitrace file(s)
- Wasn't able to download apitrace since my connection is way too slow (about 20 KB/s right now). Sorry.

### Log files
- [deblob2_20210606_12_38_13.log](https://github.com/doitsujin/dxvk/files/6604033/deblob2_20210606_12_38_13.log)
- [deBlob2_d3d11.log](https://github.com/doitsujin/dxvk/files/6604034/deBlob2_d3d11.log)
- [deBlob2_dxgi.log](https://github.com/doitsujin/dxvk/files/6604035/deBlob2_dxgi.log)
- [wine.log](https://github.com/doitsujin/dxvk/files/6604044/wine.log)

**Comment by niansa** [comment]
Might be a wine issue too, same problem occurs without dxvk!

**Comment by doitsujin** [comment]
Going by the wine log, it looks like the app calls directly into kernel32 where it crashes, so yeah, not our bug.
