### ISSUE TITLE
[d3d9] No menu sounds on GTA IV after alt-tabbing

### ISSUE THREAD

**Issue by zanesix** [doitsujin/dxvk#2089]
There is a minor issue with GTA IV Complete edition where if you alt-tab out of the game, all menu sounds will disappear until you restart the game. This can be easily reproduced in the main menu, just start up the game, alt-tab in and back out, and move around in the menus and hear no sound. I have tested this on 2 PCs with one other person reporting it as well. 
### Software information
Grand Theft Auto IV Complete Edition, version 1.2.0.43, with these setting changed in dxgi.conf:
dxgi.maxFrameLatency = 1
d3d9.maxFrameLatency = 1 

### System information
- GPU: GTX 1070
- Driver: 466.47
- Wine version: N/A
- DXVK version: 1.8.1, also tested with latest dev build

### Apitrace file(s)
N/A

### Log files
- d3d9.log: https://drive.google.com/file/d/1AAaS3PMfeIVAHaAsdv4B6Mv_nCe_eRtJ/view?usp=sharing
- d3d11.log: N/A
- dxgi.log: https://drive.google.com/file/d/1zkJJWwnksn_8Qs27urBrhXYajph473Fz/view?usp=sharing

**Comment by Squall-Leonhart** [comment]
don't use the dxgi file for GTA IV

**Comment by K0bin** [comment]
GTA IV does weird stuff when you alt-tab, especially on Windows. There should be no way that DXVK ever influences sound and I have no idea what is going on.

**Comment by Squall-Leonhart** [comment]
I have a reproduction, its probably window handle related.

**Comment by Markie98** [comment]
Also having this issue, replicated it in the first attempt. Loading screen sounds and a few other small sounds in-game seem like they might break too.

**Comment by CraezyDud** [comment]
not on older versions of the game (i tested 1.0.7.0.)

**Comment by Adiker** [comment]
The issue doesn't happen for me on newest game version (1.0.8.0) on Linux but it exists on Windows 10. For me it seems it's related to the freeze during loading missions after alt-tabbing out of the game.

**Comment by Markie98** [comment]
Just tested it, this problem is fixed with DXVK 1.9.3.

**Comment by Adiker** [comment]
> Just tested it, this problem no longer happens with DXVK 1.9.3.

Just tested now with 1.9.4 and really this is fixed ! I wonder what was the issue there...
