### ISSUE TITLE
[d3d9] [OMSI 2] [x86] DXVK State cache simply refuses to generate on some systems only?

### ISSUE THREAD

**Issue by sjain882** [doitsujin/dxvk#2092]
I am not even sure if this is a DXVK issue, or some setting we are missing, but currently I am redistributing DXVK via a .zip file in Google Drive (not sure if that affects it) bundled with a DXVK configuration file (and the GitHub is included as a link to the source with it). 

NOTE: This is on the Windows platform.

Once the users install DXVK, however, it seems for some people there is no Omsi.dxvk-cache file being generated at all for them. Even after 10-20 minutes of gameplay.

This is simply after a normal install of it. I double checked with them that they do not have any environment variables related to DXVK set.

The logfile reports `warn: DXVK: No state cache file found`. If I send my cache file to them, however, this entry disappears from the logfile and it seems that DXVK is loading it normally.

I got them to verify the game files via Steam, to eliminate any potential installation differences (its really unlikely anyway since entire game is packed into one .exe and like two .dll files, rest is game resource files like models, etc).

We tried `streams64 -s -d *.*` in the game directory to remove any potential "this file has been blocked because its from another computer" checkboxes in file properties.

On my system, however, as soon as I load into the game, I immediately have an Omsi.dxvk-cache state file and it grows in size as I continue playing as normal.

### Software information
Game: [OMSI 2](https://store.steampowered.com/app/252530/OMSI_2_Steam_Edition/)
Graphics API: DirectX 9
Architecture: x86

### System information
- GPU: Varies
- Driver: Varies
- Wine version: N/A
- DXVK version: v1.8.1 (Latest from github releases)

### Log files
Here are some d3d9.log files from different users who experienced the issue:

https://pastebin.com/raw/pDaPQRFx - Failing to find state cache
https://pastebin.com/raw/VK5SZyKZ - This is from a different user who had the same issue, but this log is from after I sent them my state cache file. You can see it loading properly.
https://pastebin.com/raw/4x7dd3tS - Another user who had the file fail to generate, but somehow the log is saying "Read 0 valid state cache entries". This user also had an extremely giant steam overlay, if it means anything

My state cache file: https://ufile.io/axagx3in

dxvk.conf: https://pastebin.com/raw/sk4yQPyS

Also, this is probably unrelated to DXVK, but one user had this issue:

- Before installing DXVK, the game was working and displaying fine. After, though, the aspect ratio is very stretched / wide, abnormally. OMSI has an option to set the aspect ratio manually ingame, and we verified that this value is as it should be. We tried forcing aspect ratio in dxvk.conf, but it didnt do a thing. Tried playing with AMD display scaling options, nothing worked. He then uninstalled DXVK completely (I verified this) and even reinstalled the game and its still occurring. Anything similar has been encountered before?

His log: https://pastebin.com/raw/NhiNcSmp

Should be noted that OMSI is a fullscreen borderless game, i.e. not exclusive fullscreen

Once again apologies if this isnt an issue with DXVK.

**Comment by SirFrags** [comment]
Steam adds the environment variable to processes it launches:
 `DXVK_STATE_CACHE_PATH=<steamapps>\shadercache\<appid>\DXVK_state_cache`

The cache may have been redirected there.

**Comment by doitsujin** [comment]
Note that the user running the app needs to have write access to the directory that DXVK creates the cache in. By default, this will be the directory that contains the executable, you might want to point `DXVK_STATE_CACHE_PATH` to some place in your home directory where you're guaranteed to have write access (the directory must already exist).

**Comment by Blisto91** [comment]
@sjain882 Did you figure out this or are you having issues?

**Comment by Blisto91** [comment]
Comment here if you still have the issue
