### ISSUE TITLE
Hdr support for win10 for amd

### ISSUE THREAD

**Issue by chumik6000** [doitsujin/dxvk#2099]
Dear developers. Is it possible to add HDR support for dxvk? I am not an IT specialist, but as i understood, such thing can be used ib vulkan now. I do not know where to ask this question( so do not juzgame severamente for this post. if u can add hdr support in dxvk for win 10 i can test it so many time as it need. Ty for your work. dxvk is really magic for a lot of old game, couse they get big FPS boost!
VK_EXT_hdr_metadata

**Comment by doitsujin** [comment]
We do not plan to support HDR since there is no support for it on the Linux graphics stack right now.

**Comment by chumik6000** [comment]
i can test it for u))

**Comment by doitsujin** [comment]
That's not quite how software development works, I'm afraid. Without being able to test locally it's straight-up not feasible to implement such a large feature.
