### ISSUE TITLE
Graphical artifacts in ELEX

### ISSUE THREAD

**Issue by Kron4ek** [doitsujin/dxvk#2100]
There are black squares near some objects.

The bad commit is 38649372bf908edc85c7634af6d4eef9b135c3ea, reverting it fixes the issue.

![elex](https://user-images.githubusercontent.com/13851877/121905618-c82fa280-cd43-11eb-81c3-2a9097f04893.jpg)

### System information
- GPU: AMD RX 560
- Driver: Mesa 21.1.2
- DXVK version: 30a1a29aa612c7a796d3cc1a4b320a24829ed286

### Apitrace file(s)
[ELEX.trace.xz](https://drive.google.com/file/d/1Av4lpRGo-H4ED-FjAydzWE15uTHglFac/view?usp=sharing)

### Log files
- d3d11.log: [ELEX_d3d11.log](https://github.com/doitsujin/dxvk/files/6648889/ELEX_d3d11.log)
- dxgi.log: [ELEX_dxgi.log](https://github.com/doitsujin/dxvk/files/6648892/ELEX_dxgi.log)

**Comment by doitsujin** [comment]
Thanks for the detailed report, should be fixed now.
