### ISSUE TITLE
Koi x Shin Ai Kanojo (Koikake) hangs on start

### ISSUE THREAD

**Issue by DavidHusicka** [doitsujin/dxvk#2104]
When I start the game without DXVK (therefore with wined3d) it starts normally and can be played. When started with DXVK, even the game window won't show up and game has to be killed. 

### Software information
Koi x Shin Ai Kanojo, env vars: LC_ALL=ja_JP.UTF8

### System information
- GPU: NVIDIA GeForce GTX 960
- Driver: 465.31
- Wine version: wine-6.10.r3.ge3cca687 ( TkG Staging Esync Fsync )
- DXVK version: 1.8.1

### Apitrace file(s)
[trace.zip](https://github.com/doitsujin/dxvk/files/6657001/trace.zip)

### Log files
- d3d9.log: [koikake_d3d9.log](https://github.com/doitsujin/dxvk/files/6656983/koikake_d3d9.log)

**Comment by DavidHusicka** [comment]
Tested with DXVK version 1.9 and the issue is still present.

**Comment by Blisto91** [comment]
Still an issue.
Can be tested with the trail version http://ustrack.amusecraft.com/koikake/download.html

**Comment by kichirouhoshino** [comment]
Tried it on the latest Proton-GE 9-22 and it seems to be fixed. It also fixed another visual novel (Miagete Goran, Yozora no Hoshi wo Interstellar Focus) which used to just instantly crash after the config screen.
