### ISSUE TITLE
[d3d9] evictManagedOnUnlock higher memory usage in 1.9

### ISSUE THREAD

**Issue by BlueAmulet** [doitsujin/dxvk#2106]
After updating DXVK to 1.9, I've noticed the memory usage in Soulstorm is higher than it was in 1.8.1. I've made sure to test multiple times, and to set up the skirmish with the same settings each time.
In DXVK 1.8.1, memory usages sits at around 2.57GiB
In DXVK 1.9, memory usage is now at 2.78GiB

Related to #1318

### Software information
Dawn of War: Soulstorm (Steam)
EXE's are marked as LAA
`d3d9.evictManagedOnUnlock=True`

### System information
- GPU: NVIDIA GeForce GTX 1050 Ti
- Driver: 465.89
- Windows version: Windows 10 64bit 2004 (19041.928)
- DXVK version: 1.9

### Apitrace file(s)
https://drive.google.com/file/d/1cVC3IYGgcbFqd1fXKJ_clfi0AS_VDRGt/view?usp=sharing

### Log files
[soulstorm_d3d9_19.log](https://github.com/doitsujin/dxvk/files/6659939/soulstorm_d3d9_19.log)
[soulstorm_d3d9_181.log](https://github.com/doitsujin/dxvk/files/6659955/soulstorm_d3d9_181.log)

**Comment by doitsujin** [comment]
where's the problem exactly if we're even below native D3D9?

**Comment by BlueAmulet** [comment]
That memory usage has gone up compared to 1.8.1?

**Comment by doitsujin** [comment]
But it doesn't matter because we still have one full gigabyte to work with before address space is exhausted. This issue is purely academic.

If you provide a trace, we can take a quick look, but a) if anything, DXVK is expected to eat **more** memory than native D3D9 so this is an outlier to begin with, and b) we're more interested in issues that are, well, actual issues.

**Comment by Joshua-Ashton** [comment]
This is probably just our staging upload changes

**Comment by BlueAmulet** [comment]
After performing a bisect, I got 4261ff6ec1aa7efdc6d7bf6a5b9434c2eb6cc184 as the commit that increased memory. And this isn't really an academic issue, I'm simply picking the first 7 races from the list for testing consistency and simplicity sake, but for example, picking "Emperor's Children" as one of the races, it's now the difference between 3.25GiB (in 1.8.1) and the game crashing before being able to start the match. Some of the other various races are also fairly memory hungry too.

**Comment by doitsujin** [comment]
> it's now the difference between the match starting at 3.25GiB (in 1.8.1) and the game crashing before being able to start the match

would have been nice to know that right from the start.........

**Comment by BlueAmulet** [comment]
Got an apitrace https://drive.google.com/file/d/1cVC3IYGgcbFqd1fXKJ_clfi0AS_VDRGt/view?usp=sharing

**Comment by K0bin** [comment]
Should be fixed in 1.9.1.
