### ISSUE TITLE
Rendering issues in Far Cry 1 & 5

### ISSUE THREAD

**Issue by MASTERSLAYER007** [doitsujin/dxvk#2108]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.
In far cry 1 the water transparency breaks, the pre baked reflections become more obvious or the water become more opaque compared to DX9, this was on maximum/ultra high quality for water. In far cry 5 everything becomes Blue in game and in the bench mark it turns pitch black.

### Software information
Name of the game, settings used etc.
Far cry 1 and 5, Max settings for 1 and any setting on 5

### System information
- GPU:Rx 550
- Driver:21.5.1
- Wine version: None/ Windows 10
- DXVK version: 1.8.1

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by K0bin** [comment]
First of all: normally you should make multiple issues for multiple games. FC5 (and Primal) is known to be very problematic and we have no idea how to fix it. Try older versions of DXVK because this isn't likely to get fixed anytime soon.

Now as to FC1:
We need those logs and the apitrace. Please also at the very very least add a screenshot of what the problem looks like...

**Comment by MASTERSLAYER007** [comment]
My harddrive got corrupted so I cant give you the log files and the games I had are also gone, I have slow internet so downloading then back will take alot of time and am having my exams so can't find enough time to do it. Sorry.

**Comment by MASTERSLAYER007** [comment]
> First of all: normally you should make multiple issues for multiple games. FC5 (and Primal) is known to be very problematic and we have no idea how to fix it. Try older versions of DXVK because this isn't likely to get fixed anytime soon.
> 
> Now as to FC1:
> We need those logs and the apitrace. Please also at the very very least add a screenshot of what the problem looks like...

I saw some videos for far cry 5 showing that it worked fine so I didn't know about that. Also for far cry 1 the screenshots were also lost when my HDD got corrupted but it can be easy to spot since you have a large ocean in the 1st level, also I forgot to say I think I used DXVK 1.8.1 with async patch I think not sure, if that makes a difference

**Comment by MASTERSLAYER007** [comment]
I only tried 4 games I think, in crysis i couldn't get it to work since the game would switch over to DX9 and crash if I put both DX9 dlls and dx10 dlls, in MW1 and WAW it worked fine for me and i saw large improvements in performance.

**Comment by K0bin** [comment]
> used DXVK 1.8.1 with async patch 

Don't use that patch, it can literally break games.

> My harddrive got corrupted so I cant give you the log files and the games I had are also gone, I have slow internet so downloading then back will take alot of time and am having my exams so can't find enough time to do it. Sorry.

Can't fix it without an apitrace.

> I only tried 4 games I think, in crysis i couldn't get it to work since the game would switch over to DX9 and crash if I put both DX9 dlls and dx10 dlls, in MW1 and WAW it worked fine for me and i saw large improvements in performance.

A lot of games simply do not work with DXVK on Windows. Windows also isn't a supported platform for the D3D10 and D3D11 versions of DXVK.

**Comment by MASTERSLAYER007** [comment]
How does it break games? I thought it was supposed to just add async compute support which improves performance, or is it like in DOOM where some settings such as SMAA didn't support async compute so it was deactivated if you chose that setting

**Comment by MASTERSLAYER007** [comment]
I will send some screenshots and the API trace when my exams finish and I get the games downloaded again.

**Comment by Joshua-Ashton** [comment]
The async patch has nothing to do with async compute or compute at all.

It just doesn't render if a pipeline has not compiled in time, that is all.

**Comment by doitsujin** [comment]
Good luck with your exams but right now there's nothing actionable here. Feel free to open a new report for FC1 with the requested info when you get to it.

**Comment by K0bin** [comment]
Tried FC1, works perfectly fine on Nvidia. Water looks identical.

D3D9:
![image](https://user-images.githubusercontent.com/1131720/122640317-3c30c880-d0ff-11eb-9d80-46f9ecfc3fca.png)

DXVK:
![image](https://user-images.githubusercontent.com/1131720/122640301-24f1db00-d0ff-11eb-8306-ce098ca6c43a.png)
