### ISSUE TITLE
[d3d9] Far Cry 1 - Water reflections look different compared to native

### ISSUE THREAD

**Issue by NorbertHarangozo** [doitsujin/dxvk#2112]
DXVK:
![dxvk](https://user-images.githubusercontent.com/44706448/122642262-c67e2a00-d109-11eb-9ea1-7a5993738957.png)

Native:
![native](https://user-images.githubusercontent.com/44706448/122642266-cc740b00-d109-11eb-9c78-6f29ccc1badf.png)

DXVK with ```d3d9.customVendorId = 10DE```:
![10de](https://user-images.githubusercontent.com/44706448/122643167-984f1900-d10e-11eb-86f5-7c2b40aa4973.png)

### Software information
Far Cry 1 at max settings, 8xMSAA.

### System information
- GPU: R7 260X 2GB
- Driver: RADV (21.2.0_devel.141347.82de184c3a2)
- Wine version: wine-tkg-staging-fsync-git-6.10.r6.g876024f4
- DXVK version: 81664fc

### Apitrace file(s)
- [FarCry.7z](https://mega.nz/file/MsBVSSTA#8fROTvZGoTVBCFZoBL7PoxQta6Wb68Zjdgbt0hngp_U) - this one was made on Windows
- [FarCry_10de.zip](https://mega.nz/file/Jowk3JpA#R_C3VUNP7sjZVo2smtcRyRkhs-HbcV7Tikv4brEov-0) - and this one was made with DXVK with ```d3d9.customVendorId = 10DE```

### Log files
- [FarCry_d3d9.log](https://github.com/doitsujin/dxvk/files/6680645/FarCry_d3d9.log)

**Comment by mirh** [comment]
https://cookieplmonster.github.io/2018/07/07/farcry-d3d9-bug/
@CookiePLMonster does it make sense that the gpu vendor would make a difference?

**Comment by CookiePLMonster** [comment]
> https://cookieplmonster.github.io/2018/07/07/farcry-d3d9-bug/
> @CookiePLMonster does it make sense that the gpu vendor would make a difference?

If the game has a vendor-specific hack, yes. With a cutting-edge game like Far Cry this wouldn't surprise me much.

**Comment by dinushlakmal** [comment]
[FarCry.7z](https://mega.nz/file/MsBVSSTA#8fROTvZGoTVBCFZoBL7PoxQta6Wb68Zjdgbt0hngp_U) - this one was made on Windows how to installhis one?

**Comment by Blisto91** [comment]
That is a trace made with apitrace. It's not something you install but instead devs use for debugging.
