### ISSUE TITLE
[Win10] [dx11] DXVK works in Phantasy Star New Genesis. But does not when trying to switch to base PSO2

### ISSUE THREAD

**Issue by OCRBonk** [doitsujin/dxvk#2115]
Not sure if this is an issue you can potentially fix or not.
But basically, Sega is dumb and doesn't properly support any way to really vsync the game to display. What ever they are doing for borderless display isn't recognized by Nvidia's drivers that support Multi Plane Overlay, so the game can't directly drive the display and trying to force Vsync on or off doesn't work. So the game stutters like crazy and has tons of frame pacing issues.

Pre-NGS update, the 2016 DX9 engine did still support FSE via config file. (Which was also needed in order to get proper frame pacing and reduce stutter in that version) But now that's gone in the DX11 client, even for base PSO2.
Until I thought to try DXVK, I had been playing the game on my W7 boot drive with RTSS Scanline Sync. (As that's the only way you can get proper frame pacing and vsync in Windows 7 anymore. Aero is a joke and it's a stuttering mess with it turned on.)
But i'd like to use downsampling to improve image quality(Needed because the TAA is terrible. And in base PSO2 before the engine update you could force SGSSAA through Nvidia's drivers.), but without proper fullscreen or flipmodel support the game is a stuttering mess. And SS doesn't work with custom non native resolutions sadly. If it does I have never been able to get it to work.

DXVK seems to work great for NGS, but with Base PSO2 the game just hard locks (Which also happens in Windows 7) when the game tries to initialize what I assume is an entirely separate engine to get it up and running.  I don't know if this is something that can be looked into or not, but this is basically the last hope to continue playing B-PSO2 with proper frame pacing as I doubt Sega will fix anything.

Windows 10 20H2
Nvidia 466.63 (RTX 2080)
DXVK 1.9 release.

EDIT: CLOSE THIS. Turns out Rivatuner Statistics Server is responsible for this. Disabling support for PSO2 allows it to work.

**Comment by doitsujin** [comment]
For the record, RTSS is known to cause all sorts of issues in combination with DXVK.
