### ISSUE TITLE
[Suggestion] Use win32 api to replace std::mutex.

### ISSUE THREAD

**Issue by expnkx** [doitsujin/dxvk#2116]
std::mutex is not available on all mingw-w64 platforms. Enabling threading support will add bloat.

Here is a very simple implementation you can just copy from. Then the dependency of std::mutex will go away.
https://github.com/expnkx/fast_io/blob/master/include/fast_io_hosted/threads/mutex/win32_critical_section.h
You can also use Rtl apis. They do exactly the same thing but RTL apis are not available on windows 95/98 and ME. I do not see a performance difference here for using Rtl Apis. So just use win32 apis are good enough.
https://github.com/expnkx/fast_io/blob/master/include/fast_io_hosted/threads/mutex/rtl_critical_section.h

std::mutex might use mcfgthread implementation since a lot of people are using GCC with MCF gthread. This probably not works since MCF gthread uses unimplemented APIs in ntdll.dll.
https://github.com/expnkx/fast_io/blob/master/include/fast_io_hosted/threads/mutex/mcf_gthread_mutex.h

Of course there is another thing you can theoretically improve but hard to achieve probably. You can just remove entire iostream/fstream from your code. iostream is extremely bloat, and it adds binary bloat for each dll for 800kbs (since compilers do not remove dead virtual functions.) If you can find out a way to avoid iostream, The dll size will reduce to probably 200-300kb.

**Comment by doitsujin** [comment]
`std::mutex`, `std::condition_variable` etc. are part of the C++ standard. Supporting that is not "bloat", it's essential, and we should not have to cater to distros which refuse to support this for absolutely no reason whatsoever.

**Comment by expnkx** [comment]
> `std::mutex`, `std::condition_variable` etc. are part of the C++ standard. Supporting that is not "bloat", it's essential, and we should not have to cater to distros which refuse to support this for absolutely no reason whatsoever.

I do not think you have ever built cross toolchains or canadian cross toolchain by yourself.
std::mutex and std::condition_variable were never actually implemented in libstdc++. Neither libc++ supported that in windows either.

The problem is that a default built GCC cross toolchain on Windows has no std::mutex. That is why it is common you see distributions do not have them. The reason is that GCC never actually supported them before.

One implementation that satisfies the standard is the GCC with MCF gthread, but it does not work on WINE since wine does not support all NT apis, particularly the undocumented ones.

And they requires another dynamic linking to threading which leads to dll hell.

So it is clearly a huge bloat.

https://github.com/expnkx/GCC12-canadian-cross-toolchain

I have a default GCC12 toolchain you can test it. No, there is no std::thread or std::mutex support, nor it does not even have std::lock_guard.

**Comment by Joshua-Ashton** [comment]
> I do not think you have ever built cross toolchains or canadian cross toolchain by yourself.

"Canadian Cross" (stupid name) has literally nothing to do with any of this. All that is building a compiler for another platform on a platform with another compiler. There is no reason that it could not be built with winpthreads even in this situation.

And yes, I have built MinGW with winpthreads myself before -- it is not difficult.

> The problem is that a default built GCC toolchain targetting Windows has no std::mutex. 

Build one that has it.

> I have a default GCC12 toolchain you can test it. No, there is no std::thread or std::mutex support, nor it does not even have std::lock_guard.

Ok, so build it with that.

> For example, just #include<iostream> bloats 800kb which is ridiculous.

DCE would like to have a word with you.

__

This is all not to say that the winpthreads impl is perfect, but it's good enough and it makes what we're writing portable -- except I guess except if you decide to not support basic C++ functionality in your compiler :v

**Comment by expnkx** [comment]
> > I do not think you have ever built cross toolchains or canadian cross toolchain by yourself.
> 
> "Canadian Cross" (stupid name) has literally nothing to do with any of this. All that is building a compiler for another platform on a platform with another compiler. There is no reason that it could not be built with winpthreads even in this situation.
> 
> And yes, I have built MinGW with winpthreads myself before -- it is not difficult.
then you introduce extra dependency of dll hell, binary bloat and performance lost.

I always build GCC by using Canadian cross compile since linux toolchain is much more stable than msys2.

> 
> > The problem is that a default built GCC toolchain targetting Windows has no std::mutex.
> 
> Build one that has it.
> 
> > I have a default GCC12 toolchain you can test it. No, there is no std::thread or std::mutex support, nor it does not even have std::lock_guard.
> 
> Ok, so build it with that.

That is bloat.

> > For example, just #include bloats 800kb which is ridiculous.
> 
> DCE would like to have a word with you.

DCE does not remove that bloat. There are no way to remove dead virtual functions. I bet you never tried that before.

**Comment by Joshua-Ashton** [comment]
> That is bloat and also it does not work on windows 95 or even windows xp due to buggy implementation.

Please look at your system clock.

**Comment by Joshua-Ashton** [comment]
>  I failed to see how std::locale, std::filesystem and iostream or threading are basic functionalities. They are failures.

I think locales are shit too, but filesystem is alright and the threading stuff is perfectly fine.

**Comment by expnkx** [comment]
> > That is bloat and also it does not work on windows 95 or even windows xp due to buggy implementation.
> 
> Please look at your system clock.

Ha, that is something you should look at tbh. Are you surprised that 32mb memory was considered luxury for windows 95 while 64 gb memory for windows 10 is still extremely laggy?
Binary bloat is a serious performance issue right now.

> I think locales are shit too, but filesystem is alright and the threading stuff is perfectly fine.

1. filesystem uses locale so it is not thread-safe. 
2. C++17 filesystem has no at-series apis. Every C++17 filesystem API usage is, defacto, a TOCTOU vulnerability. It is just as bad as gets() since there is no way to use it without vulnerability.
3. threading stuff is nonsense too because you do not have process.

**Comment by Joshua-Ashton** [comment]
> Ha, that is something you should look at tbh. Are you surprised that 32mb memory was considered luxury for windows 95 while 64 gb memory for windows 10 is still extremely laggy?
Binary bloat is a serious performance issue right now.

Yes, I am sure a 2MB dll is the real problem here -- not all the dynamic allocations by the application :V

Yes locales suck in C/C++, everybody knows this by now.

Threading stuff works fine without process handles, no idea what you are going on about.

Anyway, this issue is leading to nothing. So I am going to close it.

**Comment by doitsujin** [comment]
Excuse the vocabulary, but why the absolute fuck would we care about Win95 support? This project cannot run on those platforms anyway, Windows 7 is required as a baseline.

There are arguments to be made against relying on winpthread in particular since the implementation is not as good as it could be, and we might consider rolling our own implementation for that reason at some point (we already had to replace `std::thread` to make Wine happy), but as Josh mentioned, using STL here is what makes most of the code portable, which is a concern now that we have native Linux games shipping with DXVK. Even so, we'll still be relying on things like `std::lock_guard` and `std::unique_lock`, neither of which directly interact with any OS libraries, so there is really no reason at all to force us to reimplement these as well.

If you choose to use a toolchain which doesn't support these, not our problem. Building mingw-w64 with threading support on Linux isn't hard, and it's what I've been using for development from the very start, not to mention that pre-compiled packages for e.g. Arch ship this by default.

**Comment by expnkx** [comment]
> Excuse the vocabulary, but why the absolute fuck would we care about Win95 support? This project cannot run on those platforms anyway, Windows 7 is required as a baseline.
> 
> There are arguments to be made against relying on winpthread in particular since the implementation is not as good as it could be, and we might consider rolling our own implementation for that reason at some point (we already had to replace `std::thread` to make Wine happy), but as Josh mentioned, using STL here is what makes most of the code portable, which is a concern now that we have native Linux games shipping with DXVK. Even so, we'll still be relying on things like `std::lock_guard` and `std::unique_lock`, neither of which directly interact with any OS libraries, so there is really no reason at all to force us to reimplement these as well.
> 
> If you choose to use a toolchain which doesn't support these, not our problem. Building mingw-w64 with threading support on Linux isn't hard, and it's what I've been using for development from the very start, not to mention that pre-compiled packages for e.g. Arch ship this by default.

C++ standard library is nowhere portable. Here is clearly an example. No std::mutex support in GCC by default. Linus Torvalds was totally correct. You will finally get into trouble with this. Even using libpthread you will finally get into trouble for things like std::call_once.

I mention Windows 95 is that why people like me are using default toolchain without winpthread, since it breaks things. Building toolchains for twice is nowhere fun.

Writing a mutex based on win32 CreateSection is extremely easy tbh. And yes it does solve problems and make DXVK dll smaller. Also we completely get rid of problem.

**Comment by Joshua-Ashton** [comment]
Do you mean CriticalSection? If so, then that sucks. You'd probably want an SRW lock instead. https://docs.microsoft.com/en-us/windows/win32/sync/slim-reader-writer--srw--locks

**Comment by expnkx** [comment]
> Do you mean CriticalSection? If so, then that sucks. You'd probably want an SRW lock instead. https://docs.microsoft.com/en-us/windows/win32/sync/slim-reader-writer--srw--locks

SRW lock sucks even more tbh. msvc's implementation is clearly an example.
