### ISSUE TITLE
diablo II ran with the d2dx wrapper crashes nvidia driver

### ISSUE THREAD

**Issue by voguelike** [doitsujin/dxvk#2118]
[d2dx](https://github.com/bolrog/d2dx) is a glide-wrapper than turns diablo II into a well behaved directx 11 window. when ran with the latest dxvk release and the latest dxvk-bin from the aur, the game does not launch and instead shows a d2dx error and crashes. 

### Software information
Diablo II ran with glide (3dfx) through the d2dx wrapper

### System information
- GPU: NVIDIA GeForce GTX 680
- Driver: 465.31
- Wine version: wine-staging 6.11
- DXVK version: 1.9 and 1.8.1

### Apitrace file(s)
[trace.tar.gz](https://github.com/doitsujin/dxvk/files/6692311/trace.tar.gz)
i don't know if this is traceable. it says that it never used the dxgitrace.dll but here's the one i got out of it just in case.

### Log files
- d3d11.log: [Game_dxgi.log](https://github.com/doitsujin/dxvk/files/6692313/Game_dxgi.log)
- dxgi.log: [Game_d3d11.log](https://github.com/doitsujin/dxvk/files/6692314/Game_d3d11.log)

**Comment by doitsujin** [comment]
That's some sort of setup issue on your end.

**Comment by voguelike** [comment]
thank you. i was missing lib32-nvidia-utils.
now i can get the game working through d2dx without dxvk, but it doesn't work with reshade. if i add in reshade then a lot of the game's textures are missing and it's not playable. and since the game works just fine with wine3d, i can't get an apitrace.

if i run it through dxvk, reshade or not, i get: 
> err:   DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
> err:   DxvkSubmissionQueue: Command submission failed: VK_ERROR_DEVICE_LOST

- d3d11.log: [Game_d3d11.log](https://github.com/doitsujin/dxvk/files/6697305/Game_d3d11.log)
- dxgi.log: [Game_dxgi.log](https://github.com/doitsujin/dxvk/files/6697306/Game_dxgi.log)

**Comment by doitsujin** [comment]
driver crash, could be all sorts of things. Really need an apitrace to debug that, and if it works fine with wined3d then I don't see why you couldn't get one.

**Comment by voguelike** [comment]
maybe i'm doing it wrong, but when i launch an apitrace, the game runs like normal and once i close it there's no game.trace and it says:
`
apitrace: unloaded from C:\Program Files\Diablo II\ProjectD2\Game.exe
`
`
warning: C:\Program Files\Diablo II\ProjectD2\apitrace-10.0-win32\bin\..\lib\wrappers\dxgitrace.dll was never used: application probably does not use this API
`

i launch the apitrace with this command:
`wine apitrace-10.0-win32/bin/apitrace.exe trace -a dxgi Game.exe -3dfx`

and i have added and replaced the neccesary dlls from apitrace (d3d11.dll, dxgi.dll, and dxgitrace.dll), as well as the dll overrides for these. i've tried both `-a dxgi` and `-a d3d11` with the same results.

**Comment by doitsujin** [comment]
do you have the DLL overrides for d3d11 and dxgi set to native,builtin? If so, that should work.

**Comment by voguelike** [comment]
that was it, the dll overrides were missing. i think i forgot to add them back when i reset the prefix while troubleshooting

though now the game crashes when i run the apitrace correctly so i don't know if it'll be useful.

[trace.tar.gz](https://github.com/doitsujin/dxvk/files/6705395/trace.tar.gz)

**Comment by doitsujin** [comment]
sigh, no, not useful since it looks like it somehow managed to crash during device creation for some reason.

You don't happen to have access to a Windows machine to do the whole trace thing on?

**Comment by voguelike** [comment]
yes i do! here's the apitrace from windows

[Game.zip](https://github.com/doitsujin/dxvk/files/6707286/Game.zip)

**Comment by doitsujin** [comment]
Thanks. Does the commit above fix the issue? Build should be available [here](https://github.com/doitsujin/dxvk/actions/runs/968443723) in a few minutes.

**Comment by voguelike** [comment]
yes it does, everything works perfectly now, thank you so much!
