### ISSUE TITLE
[Win 7] Phantasy Star Online 2 New Genesis - "Entry point not found"

### ISSUE THREAD

**Issue by OCRBonk** [doitsujin/dxvk#2121]
DXVK works on Windows 7 with this game, however whenever the game starts this error pops up
https://u.cubeupload.com/MrBonk/dxvk.jpg
"The procedure entry point DXGId3d10GetLayeredDeviceSize could not be located in the dynamic link library dxgi.dll"

To bypass this error I have to hit Ctrl+Alt+Delete to bring up the TM Menu and then cancel out and it will let me hit "ok" after that the game works just fine.

Is this a known W7 issue with DXVK or just this game maybe? If it's a known unfixable problem please feel free to close this.  It would just be nice to be able to not have to do that every time I start the game. 
Thanks for all the hardwork on this great program!

R5 3600x
RTX 2080 466.63 here.

**Comment by K0bin** [comment]
That's a undocumented API that is called by one of the Windows dxgi or d3d11.dlls. Some games insist on loading the dlls located in C:\Windows\System32. In that case the game simply won't work with DXVK on Windows. Do not try to replace the system dll files with DXVK.

**Comment by OCRBonk** [comment]
Ah I see. The game does work fine once you bypass this error message. I didn't know what it was related to however. 
Given some of the shoddy technically decisions with this new version makes sense I suppose.

**Comment by doitsujin** [comment]
Yeah, this is a case of a game picking up the wrong d3d11.dll.

**Comment by OCRBonk** [comment]
Ok, that's good to know. I didn't know if it was something that could be fixed or not. (FWIW it definitely doesn't happen in Windows 10. I just have my w7 drive booted up more often) Thank you for taking the time to write replies.
