### ISSUE TITLE
[d3d9] GTA IV Can't open xbox game bar and can't take a 30 seconds replay using xbox game bar

### ISSUE THREAD

**Issue by ClonkAndre** [doitsujin/dxvk#2123]
When i try to open the game bar it says "The Xbox Game Bar is not supported for the current settings of this game."

Edit: You can open the xbox game bar by pressing **Windows Key** + **G** if it's activated in your windows settings.

**Comment by doitsujin** [comment]
We do not intend to support Xbox Game Bar, this is stil primarily a Linux project.
