### ISSUE TITLE
[Windows 10] [D3D9] - ArmA 2 texture rendering issues

### ISSUE THREAD

**Issue by DeltaPony** [doitsujin/dxvk#2124]
### Software information
ArmA 2 Operation Arrowhead, Settings default (bug presents on any settings and on any game on this engine - ArmA 2, ArmA 2 Operation Arrowhead, Take On Helicopters and DayZ on it's very old versions which are no longer officially supported and only exist in old pirated servers)

### System information
- GPU: Asus GTX 750 1GB GDDR5
- Driver: 466.27
- Wine version: Done on Windows 10 20H2
- DXVK version: 1.9 (bug presents at any D3D9 version)

### Apitrace file(s)
- https://drive.google.com/u/0/uc?id=1NL4OhATo03mS9lhLF6shTutKJflTqdLG&export=download - these were done on the dll's provided by apitrace, bug does not exist there, only on VULKAN, so i am not sure if it will help but here you go, packed into default zip because i dont know how to make those strange .tar.gz archives

### Log files
also i attached some screenshots so you can see the issues i mean, textures get messed up

[arma2oa_d3d9.log](https://github.com/doitsujin/dxvk/files/6719109/arma2oa_d3d9.log)
[arma2oa_dxgi.log](https://github.com/doitsujin/dxvk/files/6719110/arma2oa_dxgi.log)

![arma2oa 2021-06-26 02-32-45-857](https://user-images.githubusercontent.com/86499226/123491484-df19a300-d627-11eb-8b53-620c04259d76.jpg)
![arma2oa 2021-06-26 02-32-50-067](https://user-images.githubusercontent.com/86499226/123491487-e04ad000-d627-11eb-867a-18f24e56fcfb.jpg)
![arma2oa 2021-06-26 02-32-52-101](https://user-images.githubusercontent.com/86499226/123491488-e04ad000-d627-11eb-8aa6-972d278ffa27.jpg)
![arma2oa 2021-06-26 02-33-00-231](https://user-images.githubusercontent.com/86499226/123491489-e0e36680-d627-11eb-8ea2-5e5cd989d7b8.jpg)
![arma2oa 2021-06-26 02-33-21-656](https://user-images.githubusercontent.com/86499226/123491492-e0e36680-d627-11eb-97a8-258a797ad50f.jpg)
![arma2oa 2021-06-26 02-32-22-052](https://user-images.githubusercontent.com/86499226/123491495-e17bfd00-d627-11eb-98c0-c1c70385942b.jpg)
![arma2oa 2021-06-26 02-32-39-032](https://user-images.githubusercontent.com/86499226/123491496-e17bfd00-d627-11eb-9673-82dca055422c.jpg)

please fix if it is possible, that would be very great because it gives life to this old game and boosts it's performance!

p.s if you will get a licensed copy of the game, then run without BattlEye (you will see popup when starting the game from steam) because it may not let the dll do be loaded, it is not a problem because many servers dont use it or even have their modded clients

**Comment by DeltaPony** [comment]
After changing visual settings that require render to restart, bug fixes itself for a very short period of time, in log that moment is always followed by D3D9DeviceEx::ResetSwapChain, this is just what i saw while was testing dxvk and with bug, maybe this information will give you any clue about the issue

**Comment by DeltaPony** [comment]
Also if you will work on fixing this issue please create entry related to this fix in dxvk.conf

**Comment by DeltaPony** [comment]
if any additional info is required please write a comment here, i will respond

**Comment by mmrsz** [comment]
This is still an ongoing issue! Windows 10, Arma 2 directx 9. I have the same thing, the textures are striped.
In addition, there is a problem when 3D models disappear, as if blinking. Did you find a solution?

**Comment by DeltaPony** [comment]
Apitrace

https://drive.google.com/file/d/1AYhcjAjN7YS8f0fTp156gySTwXUhv8ZA/view?usp=sharing

file ArmA2OA.trace.zip.
