### ISSUE TITLE
DXVK fixes Gwent render issues but why?

### ISSUE THREAD

**Issue by magist3r** [doitsujin/dxvk#213]
Hi! This is maybe an offtopic and not an issue, but a question.
With wine-staging 3.4 I see some render issues of premium cards in Gwent: The Witcher Card Game. After installing DXVK these render issues are gone, but I didn't even setup vulkan SDK as described in wine-vulkan readme! I just installed precompiled libraries from [here](https://haagch.frickel.club/files/dxvk/) and run setup_dxvk.sh script. And I don't see any d3d11.log or dxgi.log in this WINEPREFIX. So, DXVK is not used by gwent, but it fixes render issues. How this is possible?

P.S. After 'setup_dxvk.sh reset' render issues come back.

**Comment by ssorgatem** [comment]
Maybe Gwent tries to use the D3D11 dlls, it fails and silently falls back to another renderer, possible D3D9 or OpenGl.

Try **deleting** the d3d11.dll and dxgi.dll files in your prefix and see what happens.

**Comment by magist3r** [comment]
Yes, you are right. Thanks.
