### ISSUE TITLE
Star Wars - The Old Republic - Regression

### ISSUE THREAD

**Issue by SveSop** [doitsujin/dxvk#2130]
This is run via Steam. Star Wars - The Old Republic retail client.
The issue is severe stuttering especially when turning around and/or running.

Upon updating Proton to Proton-6.3-5, dxvk was also upgraded from DXVK-1.8.1 -> DXVK-1.9. There was no issues before DXVK-1.9, and replacing the dxvk dll's in the Proton-6.3-5 folders with those of DXVK-1.8.1 brings performance back to what it was.

I did some regression testing for this, and found that after  https://github.com/doitsujin/dxvk/commit/4261ff6ec1aa7efdc6d7bf6a5b9434c2eb6cc184 this issue started happening. The issue does improve a bit with DXVK-1.9+GIT, but not enough for it to be playable. 
Mentioned this here: https://github.com/doitsujin/dxvk/pull/1987
https://github.com/ValveSoftware/Proton/issues/4326#issuecomment-869030604

### Software information
Star Wars - The Old Republic - retail client
Steam - Proton-6.3-5 (Also tested with Proton-GE-6.10-1)

### System information
- GPU: nVidia RTX2070
- Driver: 470.42.01 (Also happens with 465.31)
- Wine version: Proton-6.3-5
- DXVK version: DXVK-1.9

### Apitrace file(s)
https://filebin.net/aa7561eozmq5zzb0
This was made in Windows 10 without DXVK. I was not able to do a apitrace with latest or 10, but used apitrace-7. It did playback fine.
Hopefully it is usable.

### Log files
[swtor_d3d9.zip](https://github.com/doitsujin/dxvk/files/6729202/swtor_d3d9.zip)
[swtor_dxgi.zip](https://github.com/doitsujin/dxvk/files/6729203/swtor_dxgi.zip)

**Comment by SveSop** [comment]
Incidentally the GUI option that has to do with "scale nameplates in the distance" (or whatever wording it was) is something that is causing severe stuttering. Maybe related to some alignment thingy when the text is scaled down by the game?

If you feel it could be useful i can do a apitrace with this option disabled for comparison maybe? (But that will have to wait until tomorrow...)

**Comment by K0bin** [comment]
> If you feel it could be useful i can do a apitrace with this option disabled for comparison maybe?

Yes, that could be useful.

**Comment by SveSop** [comment]
@K0bin 
Hopefully the link works: [https://drive.google.com/file/d/1tTm1BOgUfJOgP2XKITNrVt3groSzlYs2/view?usp=sharing](https://drive.google.com/file/d/1tTm1BOgUfJOgP2XKITNrVt3groSzlYs2/view?usp=sharing)
I played back this trace on my main box with wine/DXVK and i can clearly see a drop in perf when i enable the option mid-run.

Hopefully you will get something out of it :)

PS. The trace starts with the option: "Scale Nameplates with Distance" disabled, and i enable it mid-run.

**Comment by K0bin** [comment]
That PR should fix it.

**Comment by SveSop** [comment]
> That PR should fix it.

Yep. Just tested it, and it seems buttery smooth now :) Thanks!
