### ISSUE TITLE
[x32/d3d9] 1.9 Blank Screen in Unreal Tournament 3

### ISSUE THREAD

**Issue by s7hoang** [doitsujin/dxvk#2131]
I get a blank screen when using the x32/d3d9.dll with Unreal Tournament 3 running on Windows 10.  The console works but backspacing text does not remove the characters leaving you with garbled text.  This is specifically with version 1.9.

I can confirm it works fine with 1.8.1, 1.7.3, 1.6.1 & 1.5.5 (I stopped here).

A diff of the log files from 1.8.1 and 1.9 shows these lines as the only significant differences (other than version number change):

`1.9:`
    info:    VK_EXT_conservative_rasterization
    info:    shaderStorageImageExtendedFormats      : 0

`1.8.1:`
    [empty]
    info:    shaderStorageImageExtendedFormats      : 1

### Software information
 - Latest Unreal Tournament 3 version 2.1 (patch 5)

### System information
- GPU: Radeon RX Vega 56
- Driver: 21.5.2
- Wine version: N/A
- DXVK version: 1.9

### Log files
- d3d9.log:
[UT3_d3d9 (1.9).log](https://github.com/doitsujin/dxvk/files/6729793/UT3_d3d9.1.9.log)
[UT3_d3d9 (1.8.1).log](https://github.com/doitsujin/dxvk/files/6729794/UT3_d3d9.1.8.1.log)

### apitrace
https://drive.google.com/file/d/1cW4TwcgJ_n6VcyKvq5puqj702ZxgpyAP/view?usp=sharing

**Comment by doitsujin** [comment]
Does 1.8.1 work? This isn't really clear from the report.

`shaderStorageImageExtendedFormats` being 0 is expected since the feature isn't used for D3D9, and we (finally) disabled the feature for llvmpipe compatibility.

**Comment by s7hoang** [comment]
The issue specifically happens with the release 1.9 d3d9.dll though.  When I replace the d3d9.dll file with the one provided in apitrace the issue does not occur.

Does it still make sense to do the api trace in this case?

**Comment by K0bin** [comment]
Yes.

**Comment by doitsujin** [comment]
The whole point of recording a trrace is to record what the game does so we can replay it with DXVK and (hopefully) see the breakage there.

**Comment by s7hoang** [comment]
Ok.  The instructions said to reproduce the issue which I can't so that's why I asked.

Updated the original post.

**Comment by doitsujin** [comment]
Works fine on RADV, not really sure what the proprietary driver is choking on.

**Comment by doitsujin** [comment]
Same problem as #2110, this is a driver bug.
