### ISSUE TITLE
D3D9 - Everquest Crashes with DXVK 1.9 on Windows

### ISSUE THREAD

**Issue by Momozeel** [doitsujin/dxvk#2132]
Hi, I was so excited when I discovered DXVK 1.9 yesterday as since i installed Everquest (EQEMU client) on my brand new PC (5600X / AMD 6800XT / 32go RAM) it was running very poorly in some areas like Plane of Knowledge, going down to 8-9 FPS with crazy stuttering making it almost unplayable, when in most situations I was at 60-80FPS average.
On windows, I just replaced d3d9.dll and dxgi.dll in the game's folder and suddently, all was running much smoother, without lag/stutter, felt like a miracle (although some UI textures like icons were a bit more pixelized).

Unfortunately after going around a bit, the client keeps on crashing and almost systematically upon zoning.

I was not able to make a trace as when i follow your "Making a Trace" and place the DLL in the game folder, the game doesnt launch for "not being able to launch graphics DLLs". But here are the games logs upon crashing : 

Thanks for your help,

[EQLOGS.zip](https://github.com/doitsujin/dxvk/files/6731293/EQLOGS.zip)

### Software information
Everquest (EQEMU Client)

### System information
- GPU: AMD Radeon 6800XT
- Driver: 21.6.1
- Wine version: None (Windows 10)
- DXVK version: 1.9 : https://github.com/doitsujin/dxvk/releases/download/v1.9/dxvk-1.9.tar.gz
 

### Apitrace file(s)
https://drive.google.com/file/d/11cZKy39yZaoRtAR5C77T8Fe9dVM0xCev/view?usp=sharing

**Comment by K0bin** [comment]
I can't fix this without an apitrace. Please try again.

**Comment by Momozeel** [comment]
Alright, I'm going to try again. For your information, if that can help, I have been trying with previous versions of DXVK and the 1.2.3 is not crashing anymore at all, but does not provide the graphic fluidity expected (just like the DX9 June 2010 classic raw install). Both the solution and the issue came in further versions I guess.

**Comment by Momozeel** [comment]
> I can't fix this without an apitrace. Please try again. You don't need the dxgi.dll (if you use that, you'll also have to copy over dxgitrace.dll).

Following your advice and  the guidelines (https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace) I only copied the d3d9.dll, d3d11.dll from this link (https://ci.appveyor.com/api/projects/jrfonseca/apitrace/artifacts/build/apitrace-latest-win32.7z?branch=master&job=msvc32), but contrary to other DLLs, it doesn't work and i get a "Error : Failed to load the graphics DLL!" each time i clic on the .exe of the game...

**Comment by K0bin** [comment]
You only need the d3d9.dll. Make sure there's no dxgi.dll and no d3d11.dll in the game folder.

**Comment by Momozeel** [comment]
> You only need the d3d9.dll. Make sure there's no dxgi.dll and no d3d11.dll in the game folder.

I just did that on a fresh version of the game with no other (no dxgi.dll and no d3d11.dll) and i still get the Error : Failed to load the graphics DLL! with that version of the d3d9.dll, which i don't get with the version from the repo (1.9).

**Comment by doitsujin** [comment]
Sounds like #1318?

i.e. try some sort of 4GB patch on the game.

**Comment by Momozeel** [comment]
Unfortunately there is no way for me to make a trace with the DLLs provided for now, but i can explain a bit better my issue : 

> Sounds like #1318?
> 
> i.e. try some sort of 4GB patch on the game.

Thanks doitsujin, the 4GB patch is already applied on the .exe

**Comment by doitsujin** [comment]
This is frustrating. We cannot debug the problem.

**Comment by doitsujin** [comment]
Videos don't help.

**Comment by Momozeel** [comment]
> This is frustrating. We cannot debug the problem, so the only solution will be to use older DXVK versions.

Yeah the Trace version of the DLL just wont launch the game...
Do you think i could activate the trace from the dxvk.conf last section ? : 

# APITrace Mode
#
# Makes all host visible buffers cached and coherent
# Improves performance when apitracing, but also can impact
# some dumb games.
#
# Supported values:
# - True/False

# d3d9.apitraceMode = False
# d3d11.apitraceMode = False

**Comment by Momozeel** [comment]
> > This is frustrating. We cannot debug the problem, so the only solution will be to use older DXVK versions.
> 
> Yeah the apitrace version of the DLL just wont launch the game...
> Each i replace the d3d9.dll from the apitrace-latest-win32 folder in my game folder (overriding the 1.9 package one), i get this Error : Failed to load the graphics DLL!
> 
> Isn't there anything else to do be able to produce a trace ?

**Comment by Momozeel** [comment]
Looking at the DLL involved by the game, i noticed that both are active : 

d3d9.dll   DXVK   (Game Folder)
d3dx9_30.dll  Microsoft    (Windows\SysWOW64\d3dx9_30.dll

Could that be source of some conflicts ? 
P.S : Still trying to figure out how to make a trace via : https://github.com/apitrace/apitrace/blob/master/docs/USAGE.markdown

**Comment by doitsujin** [comment]
d3d**x**9 is just a helper library and a different thing, that's not an issue.

The alternative way of recording a trace is to run `apitrace.exe -a d3d9 game.exe` without having the DLL in there, maybe try that. But it's weird that the DLL way doesn't work when DXVK works...

**Comment by Momozeel** [comment]
I'm afraid that's a little beyond my skills...
I got a hold on a "apitrace-latest-win32" with a "apitrace.exe".
I then tried to execute the following command from Win+R : 

C:\Users\zeel\Downloads\DXVK\apitrace-latest-win32\apitrace-latest-win32\bin\apitrace.exe -a d3d9 C:\EQ\Project Lazarus2\eqgame.exe

But i got System Errors saying VCRUNTIME140D.dll, ucrtbased.dll and MSVCP140D.dll are not found. I a obviously not doing this right...

**Comment by K0bin** [comment]
Do you have some overlay running like RivaTuner/MSI Afterburner or anything like that? I've successfully apitraced Everquest 2 in the past and all i had to do was drop the dll next to the games exe. I did use the Steam version of the game.

**Comment by Momozeel** [comment]
Thanks for trying to help guys i really appreciate.
I dont think so, I only have AMD overlay FPS/GPU temperatures displayed and taking it out doesnt make the game launch neither.
I am using a customized version of the game, not from Steam, but it should not matter most as it using the original engine.
Interestingly, i noticed that the improvement in fluidity (with crashes though then), started with DXVK v1.7.1. Previously, it doesn't improve the overall graphic experience (but still crashes when original d3d9.dll does not).

**Comment by FelisMalum** [comment]
I believe I am having the same problems. EQ runs scenery on modern hardware just fine but its the PC/NPC that seem to give all the issues. The current 1.9.2 version and all versions that I tried back to 1.5 crash shortly after log-in, the versions prior to that do not seem do have a d3d9 file that EQ runs off of. The problem with api tracing is how EQ starts. If you direct the trace to start eqgame.exe wich is the main file it fails stating you have to run launchpad.exe. The launchpad.exe is just a front-end and not the actual game. I did try to see what I can come up with and included what trace I did get. The eqgame trace i did come up with is 24g and guessing not what is needed.
[launchpad.1.zip](https://github.com/doitsujin/dxvk/files/7492501/launchpad.1.zip)
[launchpad.zip](https://github.com/doitsujin/dxvk/files/7492502/launchpad.zip)
t.

**Comment by Blisto91** [comment]
Are any of you still experiencing this issue? They seem to have recently changed to a 64bit client so if the original issue was a 32bit memory one that shouldn't be a problem anymore.
Tho i will run around with 1.9.2 on win10 to test a bit.

**Comment by Blisto91** [comment]
Roger. I only tried running around for a while with the steam version not the others.

**Comment by FelisMalum** [comment]
Aparently some eq clients are not properly updating. Win11 was reporting 64
bit and a thorough file check from the eq launcher was reporting fine but
ram use would never exceeded the 32 bit limit. Did a full reinstall and ram
use now frequently brakes 2g+ and lag has been completely eliminated along
with some huge graphic changes. No longer have a reason to use any 3rd
party dx9 drivers.

Roland Hromek

**Comment by Blisto91** [comment]
Sounds good Felis.

If anyone in here still experience random crashes while playing a 32bit version the try K0bin's new PR https://github.com/doitsujin/dxvk/pull/2663
Link to latest version as of this moment: https://github.com/doitsujin/dxvk/actions/runs/2430711234

**Comment by K0bin** [comment]
This should be fixed now. Please reopen if it's not.
