### ISSUE TITLE
[Help] Out of RAM Battlefield 1 results in a system freeze 

### ISSUE THREAD

**Issue by toza-mimoza** [doitsujin/dxvk#2135]
Problem: 
- Game starts and runs fine until it slowly consumes more and more memory resulting in 29/32 GB of RAM before the system is unresponsive

Report (apitrace fails since some dlls are missing):
```
vkBasalt err:   no good config file
skipping config: /home/galaktoza/.config/MangoHud/wine-explorer.conf [ not found ]
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/galaktoza/.config/MangoHud/wine64-preloader.conf [ not found ]
skipping config: /home/galaktoza/.config/MangoHud/MangoHud.conf [ not found ]
010c:err:module:import_dll Library MSVCP140D.dll (which is needed by L"Z:\\home\\galaktoza\\.local\\share\\Steam\\steamapps\\common\\Battlefield 1\\apitrace.exe") not found
010c:err:module:import_dll Library VCRUNTIME140D.dll (which is needed by L"Z:\\home\\galaktoza\\.local\\share\\Steam\\steamapps\\common\\Battlefield 1\\apitrace.exe") not found
010c:err:module:import_dll Library VCRUNTIME140_1D.dll (which is needed by L"Z:\\home\\galaktoza\\.local\\share\\Steam\\steamapps\\common\\Battlefield 1\\apitrace.exe") not found
010c:err:module:import_dll Library ucrtbased.dll (which is needed by L"Z:\\home\\galaktoza\\.local\\share\\Steam\\steamapps\\common\\Battlefield 1\\apitrace.exe") not found
010c:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\galaktoza\\.local\\share\\Steam\\steamapps\\common\\Battlefield 1\\apitrace.exe" failed, status c0000135
```
### Software information
OS:
- Arch Linux - Garuda, 5.12.13-zen1-2-zen kernel 
- ran system update, which updated the NVIDIA graphics driver but no change was noticed

Wine / Proton: 
- Bf1 runs through Steam using Proton-GE-6.9 compatibility layer
- Wine 6.11 latest 
- installed latest dxvk from this repo on the default Wine prefix

Game settings used: 
- Vsync off 
- Graphics low
- Borderless window mode 60Hz
- DX12 disabled
- Steam launch options: `gamemoderun PROTON_USE_D9VK=1 PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 DXVK_CONFIG_FILE=/home/galaktoza/dxvk.config %command%`
- disabled Steam overlay

Other setting: 
- suspended Compositor before launching

### System information
- GPU: Nvidia 1660 SUPER
- Driver: Driver Version: 465.31
- Wine version: 6.11
- DXVK version: 1.9

### Apitrace file(s)
- Failed apitrace, starting the game using `wine bf1.exe` results in an error window since it thinks that Origin is not installed. 

### Log files
- d3d9.log: cannot find 
- d3d11.log: cannot find 
- dxgi.log: cannot find 

### Related 
- This also happens when running Doom Eternal but very rarely in comparison to this game.

It's probably stupid me missing some basic concepts but I cannot find the solution online, no matter how I describe the problem. From what I have read it seems that an aggressive caching policy may be the cause.

**Comment by Blisto91** [comment]
@toza-mimoza Is this still a issue with newer dxvk/proton/updated system and packages?

**Comment by Blisto91** [comment]
Played a bit of campaign with 7.0-2rc (dxvk 1.10.1). Then again with 1.9 shoved into same proton. I then installed proton-6.9-GE-1 played a bit of multiplayer with the same launch options as yours (except your conf settings which i don't know off). It was also with same game settings.
I didn't notice anything odd and my memory usage was very stable.

R9 380 mesa 22.0.1, 5.17 regular arch kernel, KDE Plasma wayland.

**Comment by K0bin** [comment]
Unfortunately there's not enough info for us to do anything and the game runs fine for everyone else.

**Comment by toza-mimoza** [comment]
> @toza-mimoza Is this still a issue with newer dxvk/proton/updated system and packages?

Hi @Blisto91 

You can close this issue since it was not related at all with this. It was a **file indexer** continuously storing files in RAM and not releasing them. That's why it happened with multiple high end games but rarely with normal operations in the system. **Disabling that** solved the issue. 

I hope it helps someone because it was not apparent right away what the issue was.

I totally forgot I submitted this issue, sorry.
