### ISSUE TITLE
World of Final Fantasy has rendering issues with dxvk's dxgi

### ISSUE THREAD

**Issue by alasky17** [doitsujin/dxvk#2136]
World of Final Fantasy has trouble rendering on AMD with dxvk's dxgi.  The main menu renders correctly, but once you start an actual game (selecting new game is sufficient), the screen is mostly black with some occasional artifacts. ![woff-graphics-dxvk-dxgi](https://user-images.githubusercontent.com/40211296/124016024-ce13bd80-d9aa-11eb-9eea-622d3f3ac89d.png) With wine's dxgi, the game renders correctly on AMD.   

As a note - this game also has a rendering issue on NVIDIA #1216 

### Software information
World of Final Fantasy (552700)
Tested dxgi=n against dxgi=b

### System information
- GPU: AMD RX 570
- Driver: 21.1.2
- Vulkan: 1.2.168
- Wine version: Proton 6.3-5
- DXVK version: 1.9

### Apitrace file(s)
- Game exited immediately when I tried to run with apitrace

### Log files
- d3d11.log:[WOFF_d3d11-working-wine-dxgi.log](https://github.com/doitsujin/dxvk/files/6743334/WOFF_d3d11-working-wine-dxgi.log)
[WOFF_d3d11-black-screen-dxvk-dxgi.log](https://github.com/doitsujin/dxvk/files/6743335/WOFF_d3d11-black-screen-dxvk-dxgi.log)
- dxgi.log: [WOFF_dxgi-black-screen-dxgk-dxgi.log](https://github.com/doitsujin/dxvk/files/6743329/WOFF_dxgi-black-screen-dxgk-dxgi.log)
- Proton logs: [WOFF-black-screen-dxvk-dxgi-proton.log](https://github.com/doitsujin/dxvk/files/6743324/WOFF-black-screen-dxvk-dxgi-proton.log)
[WOFF-working-wine-dxgi-proton.log](https://github.com/doitsujin/dxvk/files/6743325/WOFF-working-wine-dxgi-proton.log)

**Comment by doitsujin** [comment]
The game is broken so rendering issues on Nvidia are expected, and cannot be fixed.

DXGI normally has no influence on rendering whatsoever so this makes no sense at all; really need some sort of apitrace to debug this.

**Comment by doitsujin** [comment]
Game itself works fine here with DXVK's DXGI, at least the prologue. If there's anything else I need to do to reproduce the problem, please give detailed instructions on how to do so.

**Comment by alasky17** [comment]
Thank you for taking a look!  I tried using mesa-git (head at 669b6889e4b0ed4e3ca597dee8a1ab6834bac560) and it visually changed the graphical glitching a bit, but it was still totally unplayable.  The prologue has the bad graphics on my rig, so I don't have any other ideas on how you can repro right now.  I'm pretty sure that the difference is dxgi since the only thing I'm doing is switching between WINEDLLOVERRIDES=dxgi=b and =n 

Sorry about the debug logs -- here are some hopefully cleaner logs with mesa-git just in case that is useful.  I also asked someone over here to take a look too  :+1: 
[WOFF_d3d11-wine-dxgi-mesa-git.log](https://github.com/doitsujin/dxvk/files/6749164/WOFF_d3d11-wine-dxgi-mesa-git.log)
[WOFF_dxgi-dxvk-dxgi-mesa-git.log](https://github.com/doitsujin/dxvk/files/6749165/WOFF_dxgi-dxvk-dxgi-mesa-git.log)
[WOFF_d3d11-dxvk-dxgi-mesa-git.log](https://github.com/doitsujin/dxvk/files/6749166/WOFF_d3d11-dxvk-dxgi-mesa-git.log)

**Comment by alasky17** [comment]
I asked someone else to test the game on AMD and they saw the nearly black graphical glitching with both dxvk's dxgi and wine's dxgi (with mesa-git and a rx580).  So it seems likely that it is just by chance that I'm seeing a difference in behavior when switching dxgi, probably dependent on the exact GPU.  Feel free to close this :)

**Comment by alasky17** [comment]
Leaving a new comment instead of editing the last one.  Turns out they had a typo in the launch options and actually they are seeing the same thing as me - switching back to wine's dxgi fixes the graphical failure.  So the failure does seem to be happening only with dxvk's dxgi.  I have a feeling the difference from what you are seeing could be explained by the GPU since we both have similar models (rx580 and 570) vs your 6900XT.

**Comment by doitsujin** [comment]
Can you try the `woff` branch ([this](https://github.com/doitsujin/dxvk/actions/runs/992220156) build)?

This is provides a really dirty hack for the Nvidia problem, but it's the only thing that's actually going wrong on the DXVK side of things. I'm not seeing any other relevant Vulkan validation errors, which are not GPU-dependent. The game does not change behaviour based on the DXGI implementation as far as I can tell.

**Comment by doitsujin** [comment]
Edit: Actually managed to reproduce this on the Renoir APU in my laptop, the new branch fixes it there as well.

**Comment by alasky17** [comment]
@doitsujin That build fixed the problem for me as well!  I dropped it into Proton 6.3-5 and WOFF was rendering correctly (with dxvk's dxgi of course).  Thank you!

**Comment by doitsujin** [comment]
Cool, gonna merge that then.

**Comment by shinra358** [comment]
as of today, this is also an issue on AMD still on windows.
