### ISSUE TITLE
Star Wars Battlefront 2 (2017, frostbite) lags when i do alt + tab or play for a long time

### ISSUE THREAD

**Issue by KotoWhiskas** [doitsujin/dxvk#2139]
### Description

When I press alt tab and then re-enter the game, fps goes from 50 to ~ 20. Also, the same lag occurs when I play 30+ minutes.

### Software information
Kde Neon
Star Wars Battlefront 2 (2017, frostbite)  ([origin installed with lutris](https://lutris.net/games/origin/)) without fsync and esync

### System information
- GPU: AMD RX470
- Driver: 4.6 Mesa 21.1.4 (kisak-mesa PPA) + kernel 5.8.0-59-generic drivers
- Wine version: 6.10-5-x86_64
- DXVK version: 1.9 (also tested with 'master')

### Apitrace file(s)
- [DXVK apitrace](https://drive.google.com/file/d/16FVlXCDzMird0cPzg2Mp54qv0iHIJtye/view?usp=sharing) (WineD3D crashes)

### Log files

- d3d11.log:[starwarsbattlefrontii_d3d11.log](https://github.com/doitsujin/dxvk/files/6755963/starwarsbattlefrontii_d3d11.log)
- dxgi.log: [starwarsbattlefrontii_dxgi.log](https://github.com/doitsujin/dxvk/files/6755961/starwarsbattlefrontii_dxgi.log)

**Comment by doitsujin** [comment]
are you running out or VRAM by any chance?

**Comment by KotoWhiskas** [comment]
@doitsujin I don't think so. When vram is completely full (4gb), the game has a normal FPS, and when I alt tab, the game starts to slow down with the same vram value. Also, if vram is freed (3,6/4gb) there are still lags

**Comment by KotoWhiskas** [comment]
You were right, it was vram. I tested this on windows (dxvk), and lags appeared only during long play, but not after alt tab, so this is more DE problem
