### ISSUE TITLE
Wine Developers Are Creating Their Own Vulkan Loader Library

### ISSUE THREAD

**Issue by Kerrung** [doitsujin/dxvk#214]
Hi! This is maybe an off-topic and not an issue, but in my opinion this is important news.

While mainline Wine development code has enough Vulkan support that it can run the few Windows Vulkan games like Wolfenstein and DOOM along with the Vulkan code samples and the Vulkan information utility, it's currently dependent upon the Windows Vulkan SDK being manually installed on the system. That's now changing with Wine developers working on their own Vulkan loader library. 

Roderick Colenbrander continues leading the work on Wine's Vulkan support and today published his own vulkan-1 implementation:
https://www.phoronix.com/scan.php?page=news_item&px=Wine-Vulkan-Loader-Plans
The approach he's going with for handling the Vulkan loader on Wine is writing his own simplistic loader for the time being that can be easily redistributed as part of Wine itself. Those wanting the more featureful default Vulkan loader that is part of the LunarG Vulkan SDK can continue to download and install it yourself. 

This loader library is needed for loading the Vulkan ICD "driver" code written for Wine that in turn interfaces with the host system's Vulkan support. This vulkan-1.dll loader written by Roderick is just about one thousand lines of code as he skipped support for some non-basic features like not supporting multiple installable client drivers (ICDs) and also not supporting Vulkan layers. If you want any extra functionality for now you will need to install the LunarG SDK. 

With this simple Vulkan library it is enough now to handle Wolfenstein as well as the Vulkan cube demo and vulkaninfo among other possible Windows Vulkan programs. 

The patches can now be tried for testing:
https://www.winehq.org/pipermail/wine-devel/2018-March/124876.html
If all goes well perhaps we will see this for Friday's Wine 3.5 release so that Vulkan can be working out-of-the-box on Wine.

Source:
https://www.phoronix.com/scan.php?page=news_item&px=Wine-Own-Vulkan-1

**Comment by doitsujin** [comment]
Yeah, read that on Phoronix already, but it only becomes relevant when it actually lands in wine-mainline (probably for 3.5), so *right now* this is irrelevant.

**Comment by qwertychouskie** [comment]
This seems to have gotten into 3.5, has anyone tested to see if it works with DXVK?

**Comment by libcg** [comment]
it does.

**Comment by qwertychouskie** [comment]
Cool!
