### ISSUE TITLE
sekiro framerate cap with dxvk

### ISSUE THREAD

**Issue by FischerandomONLY** [doitsujin/dxvk#2140]
hello for some reason sekiro defaults to 4k30hz instead of 60 like in dx11. i need dxvk for better performance. anyone got a fix?
### System information
- GPU: rx 580 8gb
- Driver:21.6.1
- Wine version: i use windows
- DXVK version: 1.9

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by doitsujin** [comment]
We do not support Windows.

And this really isn't anything we can fix. If the win32 APIs do not report a 60 Hz display mode then DXVK cannot know it is there, and if DXVK *does* report a 60 Hz mode then the game is just too dumb to use it for whatever reason.
