### ISSUE TITLE
Question: Enable DXVK_HUD on 64bit Compile

### ISSUE THREAD

**Issue by Xiseous** [doitsujin/dxvk#2141]
I have the HUD working via variables on the 32bit compile, however the stats don't show up on the 64bit compiles when setting an environment label on windows or compiling with the selected info.

Is this supposed to be like this or is there a way to enable those stats?

Thanks!

**Comment by doitsujin** [comment]
Sounds like a user error, there is no difference between 32-bit and 64-bit builds regarding the HUD.

**Comment by Xiseous** [comment]
How could this be a user error if the same compile but 32bit variant shows
the hud when launching the same game, but not the 64bit.

I know the 64bit variant has loaded since the game does not crash on it's
specific points.

**Comment by K0bin** [comment]
Does that game have both a 32bit and 64bit exe?

**Comment by Xiseous** [comment]
> Does that game have both a 32bit and 64bit exe?

32 only

**Comment by Xiseous** [comment]
> > Does that game have both a 32bit and 64bit exe?
> 
> 32 only

But the 32bit version of DXVK makes it crash whilst trying to take a screenshot via Steam and sometimes in the photomode of the game, without DXVK it will crash on map load and screenshot, on 64bit it will let you screenshot and load the map and even use photo mode.

**Comment by K0bin** [comment]
> 32 only

The 64 bit version of DXVK will not get loaded by 32 bit games and that's why you're not seeing the DXVK_HUD.

**Comment by Xiseous** [comment]
> > 32 only
> 
> The 64 bit version of DXVK will not get loaded by 32 bit games and that's why you're not seeing the DXVK_HUD.

If it's not loading then how come the game is running and not crashing?

**Comment by doitsujin** [comment]
> If it's not loading then how come the game is running and not crashing?

It simply does not load the DLLs and uses native D3D11 instead.

Anyway, closing.
