### ISSUE TITLE
Blade and Soul UE3 - Not Render Textures in v1.9

### ISSUE THREAD

**Issue by roskiboy** [doitsujin/dxvk#2142]
### Software information
Blade and Soul UE3
Settings: optimize everything, only set the maximum on visibility objects and textures.

I share files to see the cause of the problem.
In version 1.7.3 to 1.8.1 it works correctly.
But in the new version 1.9 is where this error is generated

### System information
- GPU: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz 6 Cores
- Driver: AMD RADEON 21.6.1 - 21.20.01.14-210617a1-368764E-RadeonSoftware
- Wine version: none
- DXVK version:  Vulkan Driver Version 2.0.183, Vulkan API Version 1.2.174

### Apitrace file(s)
[BNS APITRACE.zip](https://github.com/doitsujin/dxvk/files/6759219/BNS.APITRACE.zip)

### Log files
[Client_d3d9.log](https://github.com/doitsujin/dxvk/files/6759220/Client_d3d9.log)

![1](https://user-images.githubusercontent.com/6926155/124369904-95881400-dc36-11eb-87c3-3714e77df479.png)
![2](https://user-images.githubusercontent.com/6926155/124369905-9620aa80-dc36-11eb-806c-18efeb39bbb4.png)
![3](https://user-images.githubusercontent.com/6926155/124369906-96b94100-dc36-11eb-9c27-1135d6c789d6.JPG)

**Comment by doitsujin** [comment]
Please try current master ([this](https://github.com/doitsujin/dxvk/actions/runs/996295533) build).

Also, your apitraces are more or less empty DirectDraw traces for some reason, rather than D3D9, i.e. rather useless.

**Comment by roskiboy** [comment]
@doitsujin 
The build you gave me worked perfectly, is it version 1.9?

**Comment by roskiboy** [comment]
@doitsujin 
is there any way to use the dedicated memory of the gpu to more than 50%?
Some configuration or it is already a problem of the executable (game).
Example in this game only uses 10% of memory but uses 80% of GPU in threads. But is there a way with the "dll" or some configuration to force the use of the memory of the gpu?

**Comment by K0bin** [comment]
It will use as much VRAM as the game requests. We can't just arbitrarily move stuff around as that would either break the game or make it **very** slow.

It's not really surprising that UE3 games designed in a time where most GPUs only had 2GB of VRAM, don't manage to use all 8GB.

**Comment by roskiboy** [comment]
@K0bin @doitsujin 
Thank you for responding and waiting for future updates.
Have a great day team .....
