### ISSUE TITLE
Room 54 ~2-5 FPS

### ISSUE THREAD

**Issue by dreamhunt** [doitsujin/dxvk#2145]
The game Room 54 runs very slow with ~2-5 FPS. The symptoms are just like they were in Days Gone - smooth 60 FPS at the initial dev screens and 2-5 FPS in main menu and in game. With Wine the game is running normally and not laging, just with lower FPS because of DX11 - ~40 FPS on high settings.

Arch Linux
NVIDIA GTX 1080Ti, driver 470.42.01
DXVK v.1.9
- d3d11.log
[Room54_d3d11.log](https://github.com/doitsujin/dxvk/files/6763351/Room54_d3d11.log)
- dxgi.log
[Room54_dxgi.log](https://github.com/doitsujin/dxvk/files/6763352/Room54_dxgi.log)
- Apitrace
https://u.pcloud.link/publink/show?code=XZJFpPXZXJEWw226i45bx4FIxb9tbQdOoqAV

**Comment by doitsujin** [comment]
does this happen on Windows with DXVK?

The game does not use any of the not really implemented DXGI functionality like Days Gone, and the trace replays perfectly fine here, so there's no reason for the game to be slow.

**Comment by dreamhunt** [comment]
On Windows with DXVK there's no problem.

**Comment by doitsujin** [comment]
Game works fine here, not sure what's wrong on your end.
![Bildschirmfoto](https://user-images.githubusercontent.com/25567304/124612354-8a212c80-de72-11eb-9a64-43b924ed651e.png)

**Comment by dreamhunt** [comment]
This is the only one game with this problem for me. I try at least 7-8 games a day and I'm sure all is working fine on my end. I'll try master and I will get back to you shortly.

**Comment by dreamhunt** [comment]
It's the same with master. Later I'll try on Linux Mint and I'll report the result to you.

**Comment by dreamhunt** [comment]
Unfortunately the problem occurs on Mint too:
![Screenshot from 2021-07-06 20-33-01](https://user-images.githubusercontent.com/9913684/124643327-a5536280-de99-11eb-9841-367731d6d461.png)
It may be a NVIDIA problem then.

**Comment by K0bin** [comment]
Does it happen with the latest master build of DXVK too?

**Comment by doitsujin** [comment]
Already asked that and apparently it's still broken for them.

**Comment by K0bin** [comment]
I didnt see a response to your question.

**Comment by doitsujin** [comment]
This:

> It's the same with master. Later I'll try on Linux Mint and I'll report the result to you.

Tested this on my mobile RTX 2060 and it works fine there as well, so not sure what's going on here.

**Comment by dreamhunt** [comment]
I really don't know what is happening here. Unfortunately I don't have an AMD video card to try it. If you need some info I'll be happy to provide it.

**Comment by WinterSnowfall** [comment]
> I really don't know what is happening here.

I see there's a lot of "warning" spam in the logs you've attached. Have you tried setting `DXVK_LOG_LEVEL=none` ?

**Comment by dreamhunt** [comment]
No but now I tried it and it actually solves the problem! 290 FPS :)
Thank you very much!!!

**Comment by WinterSnowfall** [comment]
You're very welcome. Alternatively just launch the game directly (using the UI), not from a terminal emulator. Keep in mind the latter can also cause noticeable slowdowns in Wine when verbose logging is triggered (unless you also disable Wine logs with `WINEDEBUG=-all`, of course). Simply redirecting stdout off screen might solve it as well, I guess.

**Comment by dreamhunt** [comment]
I tried that previously with `WINEDEBUG=-all` and using the UI, but it doesn't help :)
