### ISSUE TITLE
Resident Evil Village has degraded performance with DXVK dxgi.

### ISSUE THREAD

**Issue by rbernon** [doitsujin/dxvk#2146]
The game calls CreateDXGIFactory repeatedly, which can be time consuming as it enumerates the adapters (although it may depend on the hardware or driver).

Proton had a hack in Wine DXGI to keep a single instance of the factory for that game (https://github.com/ValveSoftware/wine/commit/57f8d20c216ddfae0d598b4cb3c93d5e6cb7ea10), and switching to DXVK dxgi introduced a regression.

**Comment by DadSchoorse** [comment]
I think #2053 is supposed to help here, but doitsujin doesn't like it.

**Comment by rbernon** [comment]
Indeed, I searched the issues but not the PRs.

**Comment by Joshua-Ashton** [comment]
Hm, that PR should be in Proton Experimental still? Is it not?

**Comment by rbernon** [comment]
Looks like it isn't, it's been (incorrectly) dropped between experimental-6.3-20210616 and experimental-6.3-20210625, probably during the 6.3-5 release.
