### ISSUE TITLE
[d3d9] Port Royale 3 hangs when transitioning to city view

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#2148]
The game hangs (background music still plays and the "loading" ship wheel still turns, yet the city view never renders on screen) while transitioning from map view to city view. Occasionally I have been able to get a city view after multiple tries, but hangs are the standard behavior. WineD3D works just fine. I've captured a trace with 3 transitions, but annoyingly it worked just fine (without any hangs) on replay with DXVK. I was able to reproduce the hangs both on an Nvidia card and an Intel iGPU. They only show up when using DXVK. 

Here's a [screen capture](https://drive.google.com/file/d/1Qcr7ftu2Q0BA5VcmKNn-3XU6TXzV-UH0/view?usp=sharing).

Initially I suspected a memory allocation issue and tried enabling LAA and setting various d3d9 memory limits without any results.

Hopefully you can figure out what's going on here, since I'm out of ideas.

Also, as far as I can tell, this is not a regression since I noticed the same problem a while ago with DXVK 1.8.1, but did not have the time to look into it until now.

### Software information
Port Royale 3

### System information
- GPU: GTX 1080
- Driver: 465.31
- Wine version: 6.12 Staging
- DXVK version: 1.9-f903400

### Apitrace file(s)
[PortRoyale3.trace.tar.xz](https://drive.google.com/file/d/1xnUgYD7Yb4WUhxa_G-Xap1KFd55aoZ4G/view?usp=sharing)

### Log files
- d3d9.log: [PortRoyale3_d3d9.log](https://github.com/doitsujin/dxvk/files/6777316/PortRoyale3_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by Blisto91** [comment]
Can confirm on R9 380 mesa git.

Made a PR

**Comment by WinterSnowfall** [comment]
> Can confirm on R9 380 mesa git.

I was actually hoping someone would confirm this on AMD last year when I reported the issue (and the fix), but better late than never. Thanks for testing this and for the PR!

**Comment by Blisto91** [comment]
@WinterSnowfall Can you quickly try something? I'm running into something weird with this issue.

Can you try to use this version with the game without the conf option and see if it still happens?
It's the 1.10.1 version that comes along with steam proton 7.0-2rc, which for some reason i cannot reproduce it with. Only the versions i download from the github i can reproduce the the issue with.

[dxvk-1.10.1-proton.tar.gz](https://github.com/doitsujin/dxvk/files/8497117/dxvk-1.10.1-proton.tar.gz)

**Comment by WinterSnowfall** [comment]
> I'm running into something weird with this issue.

I'm not sure what's going on here either, but I am seeing the same thing. Can't get the game to lock up on transition with the proton version you provided, however with the release version of dxvk (taken from this github) it locks up immediately...

**Comment by Blisto91** [comment]
For more info see discussion in PR https://github.com/doitsujin/dxvk/pull/2610
