### ISSUE TITLE
Elder Scrolls IV: Oblivion has glitching video and sound cuts out every ~20s (Regression)

### ISSUE THREAD

**Issue by alasky17** [doitsujin/dxvk#2149]
Originally reported here: https://github.com/ValveSoftware/Proton/issues/718#issuecomment-875107087

The Elder Scrolls IV: Oblivion (22330) has a regression between v.1.8.1 (included in Proton 6.3-4) and v.1.9 (included in Proton 6.3-5).  When starting a new game, the video will glitch out and pause frequently, and the audio will cut out for a second every ~20s.  To reproduce, just start a new game and let the opening cutscene play for ~1 minute.

I ran a git bisect which blamed the following commit.  The commit didn't revert cleanly so I was unable to confirm if this is the commit at fault.
4261ff6ec1aa7efdc6d7bf6a5b9434c2eb6cc184 is the first bad commit
commit 4261ff6ec1aa7efdc6d7bf6a5b9434c2eb6cc184
Author: Robin Kertels <robin.kertels@gmail.com>
Date:   Fri Apr 2 01:37:33 2021 +0200

    [d3d9] Use staging buffer for managed copies

### Software information
The Elder Scrolls IV: Oblivion (22330) (GOTY edition)

### System information
GPU: AMD RX 570
Driver: 21.1.2
Vulkan: 1.2.168
Wine version: Proton 6.3-5
DXVK version: 1.9

### Apitrace file(s)
Game crashes with the apitrace files for d3d9 in the .exe folder (following Joshie's instructions)

### Log files
I collected logs from both the "working" version before the regression and capturing the bug after the regression.  
- d3d9.log:
[Oblivion_d3d9-correct-old-version.log](https://github.com/doitsujin/dxvk/files/6778956/Oblivion_d3d9-correct-old-version.log)
[Oblivion_d3d9-glitching-regression.log](https://github.com/doitsujin/dxvk/files/6778957/Oblivion_d3d9-glitching-regression.log)
- proton log:
[oblivion-6.3-4-working-correctly.log](https://github.com/doitsujin/dxvk/files/6778961/oblivion-6.3-4-working-correctly.log)
[oblivion-6.3-5-glitching.log](https://github.com/doitsujin/dxvk/files/6778962/oblivion-6.3-5-glitching.log)

**Comment by K0bin** [comment]
Can you reproduce it on master?

**Comment by alasky17** [comment]
@K0bin Yes.  Same issue present with dxvk head at e23792ef91cd80a823f4d91b9c4680445092f4c9 built with Proton 6.3-5.

**Comment by alasky17** [comment]
@K0bin That fixed the problem, thank you!
