### ISSUE TITLE
Ambitious project ?

### ISSUE THREAD

**Issue by RSF-Deus** [doitsujin/dxvk#215]
I don't get what it does... Is this a Vulkan interpreter that transforms D3D11 calls into Vulkan ? If this is it, it's a very ambitious project !! As someone else stated, a patreon / othercrowdfoundingsolution could be very interesting ! I'm sure plenty of developpers would be interested.

**Comment by Kerrung** [comment]
YouTube video: https://youtu.be/_lWe5gY9P0I
DXVK ( bd71f25) | Battlefield 1 (DX11.1) | NVIDIA | Capture Card.
Settings: Medium Graphics/High Textures at 1080p
Got my hands a capture card to remove any issues from OBS, so these videos will represent what real world performance is.
Specs:
Motherboard : GIGABYTE Z97M-DS3H
CPU: Intel Core i5 4690K 4.7GHz 
RAM: 16GB 2400MHz DDR3 
Graphics Card: MSI GTX 1060 GAMING X 6G 
OS: Arch Linux/WM: xfce4
Wine: wine-staging-3.4

**Comment by RSF-Deus** [comment]
Very interesting ! Thanks !
