### ISSUE TITLE
[d3d9] - Don't Starve Together (322330) - Title crashes at launch on v1.9 and newer.

### ISSUE THREAD

**Issue by ZereoX** [doitsujin/dxvk#2150]
### Description:
While testing titles that require child vulkan windows, we found that **_Don't Starve Together_** (322330), which previously worked on Proton-Experimental, is now crashing since DXVK was bumped to v1.9 (this also extends to Proton 6.3-5). The title launches correctly on v1.8.1. This was confirmed on both Proton and Windows.

I've tested a few CI builds and a1f3f6c seems to be the last known-good commit (last commit before the nv12 changes).

| v1.9 - ❌ | a1f3f6c - ✔️ |
| ---- | ---- |
|![image](https://user-images.githubusercontent.com/761853/124962925-31c26a00-dfed-11eb-8d53-68dd9a21e882.png)|![image](https://user-images.githubusercontent.com/761853/124963115-6b937080-dfed-11eb-9935-0beb2c353a4f.png)|

Please let me know if any additional information is required or if additional testing is needed.

### Software information
[Don't Starve Together](https://store.steampowered.com/app/322330/Dont_Starve_Together/) (322330)

### System information
OS: Ubuntu 20.04 / Windows 10 Pro 20H2
GPU: Radeon RX 5700 XT / Nvidia GeForce GTX 1060
Driver: 21.2\~git2107080600.cf66cc\~oibaf\~f / 465.31-0ubuntu0.20.04.1
Wine version: Proton 6.3-5
DXVK version: 1.9

### Apitrace file
- Link: https://drive.google.com/file/d/1VcuHiCLOyTG1bPA_5xkN0_C0G4aVgFyu/view?usp=sharing

### Log files
d3d9.log: [dontstarve_steam_d3d9.log](https://github.com/doitsujin/dxvk/files/6786161/dontstarve_steam_d3d9.log)

```
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_LASTPIXEL
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_DITHERENABLE
```

### Tested CI builds:
main - e23792e - (❌)
v1.9 - dca6346 - (❌)
0fe8f2e - (❌)
0af7229 - (❌)
383cde2 - (❌)
a1f3f6c - (✔️)
0520ce9 - (✔️)
13f5353 - (✔️)
v1.8.1 - 5083b84 - (✔️)

**Comment by K0bin** [comment]
Fixed by #2158
