### ISSUE TITLE
[d3d9] Broken rendering in StarCraft 2 after latest commits

### ISSUE THREAD

**Issue by pppbb** [doitsujin/dxvk#2164]
![Zrzut ekranu z 2021-07-15 01-09-34](https://user-images.githubusercontent.com/33740721/125869534-6f7fef2a-0f8d-4bc6-9186-f08bebb15e59.png)

### Software information
StarCraft 2, 1080p, max settings

### System information
- GPU: Radeon 6900x
- Driver: Mesa 21.2.0-git
- Wine version: staging 6.12
- DXVK version: git-master

### Apitrace file(s)
- [apitrace](https://1drv.ms/u/s!AsGasIBm9m3Ahs8XS_cPGwg9FvaKxw?e=lHSyd4)

### Log files
[SC2_x64_d3d9.log](https://github.com/doitsujin/dxvk/files/6826710/SC2_x64_d3d9.log)
[SC2_x64_dxgi.log](https://github.com/doitsujin/dxvk/files/6826711/SC2_x64_dxgi.log)

**Comment by doitsujin** [comment]
can you please clarify "latest commits"?

**Comment by wu-yue** [comment]
Also confirm this bug at my end:
    GPU: Radeon RX590
    Driver: Mesa  21.1.4-1 (Debian Experimental)
    Wine version: official staging 6.10

**bisect**
**not working**
dxvk-master-d3112c320b1a2de3018612b7a4530b7bc3d84968 
[d3d9] Add dirty texture tracking

dxvk-master-8eeff90e0af5f8d0838a5028d30e74bdeea643a6 
[d3d9] Only use staging buffers for uploads once we've stalled on the

**working**
dxvk-master-ed24c17d53c663cf4e52189d0e8618f285a13ad4 
[d3d9] Validate srcRect and dstPoint in UpdateSurface

**Comment by K0bin** [comment]
Can you please make an apitrace? I don't have the game, so I can't fix this without one.

**Comment by pppbb** [comment]
> Can you please make an apitrace? I don't have the game, so I can't fix this without one.

[apitrace](https://1drv.ms/u/s!AsGasIBm9m3Ahs8XS_cPGwg9FvaKxw?e=lHSyd4)

**Comment by bno1** [comment]
Same issue. Fixed by @K0bin's pull request (rebased on the current master)

GPU: GTX 1070
Driver: 470.57.02
Wine: lutris-6.10-7
