### ISSUE TITLE
[d3d11] Metro 2033 crashes

### ISSUE THREAD

**Issue by flgx16** [doitsujin/dxvk#2165]
Metro 2033 (not Redux) crashes on launch after selecting D3D10 or D3D11 in video options. It uses D3D9 by default, which works.

### Software information
[Metro 2033](https://steamcommunity.com/app/43110)
Select DirectX 10 or DirectX 11 in video options.

### System information
- GPU: NVIDIA GeForce GTX 1660 SUPER
- Driver: 470.42.01
- Wine version: Proton Experimental (6.3)
- DXVK version: 1.9

### Apitrace file(s)
- [d3d11 apitrace](https://mega.nz/file/lb4E3Q7K#obVsQD004uKx-MamA7MoSRuPaeuCNKzuiRPKV-b1_EY)

### Log files
- [metro2033_d3d11.log](https://github.com/doitsujin/dxvk/files/6834891/metro2033_d3d11.log)
- [metro2033_dxgi.log](https://github.com/doitsujin/dxvk/files/6834890/metro2033_dxgi.log)

**Comment by flgx16** [comment]
Installing `d3dx11_42` with winetricks/protontricks fixes this.

**Comment by Sol1vaN** [comment]
> Installing `d3dx11_42` with winetricks/protontricks fixes the crash.

what means d3dx11_42?
you simply chage the d3d11.dll to d3d11_42.dll ?
