### ISSUE TITLE
Regression 1.9 dx9

### ISSUE THREAD

**Issue by Bxaa** [doitsujin/dxvk#2167]
Example with dx9 witcher 1
(no such issue with previous released versions)
<a href="https://ibb.co/b1JgRbS"><img src="https://i.ibb.co/b1JgRbS/witcher-2021-07-18-06-32-10.png" alt="witcher-2021-07-18-06-32-10" border="0"></a>

**Comment by K0bin** [comment]
Already fixed in master.

**Comment by Bxaa** [comment]
@K0bin

Hi,
I did test this build
Yes, textures upload fixed, but it randomly crash the game
(tested on witcher 1)

dxvk.hud = compiler
d3d9.memoryTrackTest = True
d3d9.samplerAnisotropy  = 16
d3d9.invariantPosition = false
d3d9.evictManagedOnUnlock = True
d3d9.dpiAware = True
d3d9.deferSurfaceCreation = True
d3d9.floatEmulation = false
dxgi.numBackBuffers = 3
d3d9.shaderModel = 3
d3d9.presentInterval = 1

Do you need a trace? (or maybe dx9 already fixed in some custom build?)

**Comment by shmerl** [comment]
Was this fixed in the upstream version? I'm still getting some black texture artifacts in TW1 with dxvk master (Mesa main, radv).

**Comment by Blisto91** [comment]
Ye open a new issue 🙂

**Comment by K0bin** [comment]
@Bxaa Please don't just blindly use config options you find somewhere. Most of those don't make any sense at all.
