### ISSUE TITLE
[d3d9] - Senren * Banka (1144400): Performance Regression since 1.9 

### ISSUE THREAD

**Issue by Theucalyptus** [doitsujin/dxvk#2168]
### Description
Since DXVK 1.9, the game is very sluggish, ~20fps at all time while with older versions (1.8.1 works fine) the game behaved normally (constant 60fps, the framerate is locked by default, and unlocking it doesn't help)

### Software information
Senren * Banka Steam Release (1144400), default settings

### System information
- GPU: AMD RX Vega 56
- Driver: Mesa 21.1.5 Archlinux
- Wine version: 6.12-staging, lutris-6.10-7, Proton 6.3-5
- DXVK version: 1.9, and d3112c320b1a2de3018612b7a4530b7bc3d84968

### Apitrace file(s)
- Link: https://drive.google.com/file/d/1EoETOTnsoQ69haUDRCjUuwSBYQA-xhwp/view?usp=sharing 
- Note: recorded on Windows 10

### Log files
- d3d9.log: [SenrenBanka_d3d9.log](https://github.com/doitsujin/dxvk/files/6835999/SenrenBanka_d3d9.log)

**Comment by K0bin** [comment]
That trace only contains 298 frames and finishes in 5 seconds. That's not long enough to investigate performance.

**Comment by K0bin** [comment]
I can reproduce the problem with 1.9.

The current master version of DXVK causes a black screen in the game but after I fixed that, performance was fine again.

**Comment by Theucalyptus** [comment]
This build works fine. I was about to report the black screen issue as it affected many KiriKiri based VNs.
PS: sorry about the short trace, the issue happened even in the splash screen so I didn't bother to trace for very long, will do it next time.

**Comment by Theucalyptus** [comment]
(maybe I shouldn't have close the issue ? I dunno)
