### ISSUE TITLE
FF XII TZA loops endlessly on EnumOutputs

### ISSUE THREAD

**Issue by GitArUs** [doitsujin/dxvk#217]
The game starts and kind of works with plain wine 3.4, however it is not very playable, because most of world textures are missing.
With DXVK the game "hangs" at startup using 100% cpu before it displays anything (I mean it displays empty, 100% transparent, unresponsive window). I tried to to some debugging and found out, that it can not get past enumerating outputs, where output numbers go from 0 to infinity. I have added some more logging to dxgi to show the effect (although apitrace shows the same). Console window shows nothing more besides those lines which are visible in dxgi.log.
When in DxgiAdapter::EnumOutputs I addded Output=nullptr before DXGI_ERROR_NOT_FOUND is returned (like it is done in wine's dxgi), the loop started to alternate between outputs 0 and 1 instead of continuously increasing the output number. I haven't any ideas how to find a workaround or solution.
Unigine Heaven works with DXVK pretty well, Unigine Superposition shows something too, so my environment shoud be ok I suppose.

### Software information
Final Fantasy XII The Zodiac Age (Steam)

### System information
- GPU: GeForce GTX 670
- Driver: 390.42
- Wine version: 3.4
- DXVK version: current git master

### Apitrace file(s)
Apitrace dump shows only this: 
[FFXII_TZA.dump.txt](https://github.com/doitsujin/dxvk/files/1853291/FFXII_TZA.dump.txt)

### Log files
- d3d11.log: 
[FFXII_TZA_d3d11.log](https://github.com/doitsujin/dxvk/files/1853292/FFXII_TZA_d3d11.log)

- dxgi.log: 
[FFXII_TZA_dxgi.log](https://github.com/doitsujin/dxvk/files/1853293/FFXII_TZA_dxgi.log)

**Comment by Altosk** [comment]
how did u get this game to run on wine i cant get it to run at all

**Comment by doitsujin** [comment]
@GitArUs can you create an apitrace on Windows or with wined3d, or is this what you were doing already?

> When in DxgiAdapter::EnumOutputs I addded Output=nullptr before DXGI_ERROR_NOT_FOUND is returned (like it is done in wine's dxgi)

This might actually be the correct thing to do. It's not documented anywhere on MSDN, but most DXGI and D3D11 methods seem to reset the pointers prior to returning an error code.

@Altosk this is not a wine support thread.

**Comment by GitArUs** [comment]
Unfortunately I haven't Windows at all. And I could not get any trace with wined3d so far, but I'll try again different way. If a trace of working program is necessary and if I won't be able to obtain it on Linux, I'll look for a computer with Windows to get it.
I can also provide output from wined3d with WINEDEBUG=+dxgi, but I'm not sure if it would help at all (I haven't seen anything interesting, but I'm not a programmer).

**Comment by GitArUs** [comment]
Congratulations, looks like commit 6babc22 fixed it. Well, kind of. Now I can see all-white screen and something crashes immediately after showing it (the process is not terminated though and the all-white window stays on the screen). This should probably go to separate issue, but anyway:
- console output after last "Compiling shader":
[consoleout.txt](https://github.com/doitsujin/dxvk/files/1857115/consoleout.txt)
- dxgi.log: 
[FFXII_TZA_dxgi.log](https://github.com/doitsujin/dxvk/files/1857117/FFXII_TZA_dxgi.log)
- d3d11.log: 
[FFXII_TZA_d3d11.log](https://github.com/doitsujin/dxvk/files/1857118/FFXII_TZA_d3d11.log)

I tried winedebug on minidump but it does not show anything sane (backtrace is just one line with one hexadecimal number). But maybe I am doing it wrong, never used winedebug before.
Output of winedebug:
[winedebug.txt](https://github.com/doitsujin/dxvk/files/1857164/winedebug.txt)

You can close this case if You feel like it, or I can check which line(s) exactly fixed the issue if You want. But I can not continue until after holidays, so Happy Easter :)

**Comment by doitsujin** [comment]
That crash might very well be a related issue. FWIW, the fix only applies to DXGI methods, not to D3D11 methods. An apitrace would be *really* helpful to see what the game is trying to do, and more importantly, to (possibly) reproduce the issue.

**Comment by GitArUs** [comment]
Understood. I'll get the trace, but it has to wait a few days.

**Comment by GitArUs** [comment]
I tried the game with latest commits and it still behaves the same way.
I have managed to get apitraces, although it was tricky.
Here is the apitrace taken on Windows 10. Keep in mind, that I used quite different hardware (ati radeon mobility 5450 or something like that):
[FFXII_TZA-until-menu-windows.7z](https://drive.google.com/open?id=12Jm8W2GkL_Q8zGuTF0l_Vh3XHKS4MymO)
I was able to replay it on Windows, but under wine apitrace crashes when I try to replay it, with both wined3d and dxvk:
[apitrace-backtrace.txt](https://github.com/doitsujin/dxvk/files/1872068/apitrace-backtrace.txt)
On the console there also was:
[apitrace-crash-console.txt](https://github.com/doitsujin/dxvk/files/1872083/apitrace-crash-console.txt)
Apitrace dump looks ok though.

And here is the apitrace taken with wined3d (with builtin dxgi and d3d11, but native d3dx11_42.dll and d3dx11_43.dll):
[FFXII_TZA-until-menu-wined3d.7z](https://drive.google.com/open?id=19dyoBXKcl0lT_QwHcCBcfH-ZUtwEB3nM)
I could replay it on wine when using wined3d, with dxvk it surprisingly shows something more than game itself (loading icon), but then the whole XWindows becomes unresponsive, I have to log in remotely and kill apitrace.

**Comment by Progman-DT** [comment]
Doesn't the game use Denuvo? I think it's not supported by Wine yet.

**Comment by GitArUs** [comment]
Sure, here You are:
[FFXII_TZA_until_crash_dxvk.zip](https://github.com/doitsujin/dxvk/files/1910442/FFXII_TZA_until_crash_dxvk.zip)

And below - console output captured with WINEDEBUG="+loaddll,+relay,+seh,+tid", 500 lines before and 500 lines after exception 0xc0000005.
[lines_before_after_crash.txt](https://github.com/doitsujin/dxvk/files/1910439/lines_before_after_crash.txt)

**Comment by GitArUs** [comment]
I have just recompiled DXVK from current git master and now the game works and looks good ! :) It means that changes made during last 4 days fixed it. Thank You !

**Comment by doitsujin** [comment]
Alright, thanks :+1:

**Comment by Progman-DT** [comment]
The game still hangs once you go through the Iron Gate in the beginning. The music keeps playing but the screen is black and DXVK HUD is frozen.
Arch Linux, Wine Staging 3.6, GeForce GTX 770, latest driver and latest dxvk.

**Comment by GitArUs** [comment]
I don't know who commented on this, but yes, game hangs when crossing areas, but only when vsync is disabled. With vsync enabled in game options and in system options it is ok. Feel free to make a new report or wait until I do it. Or maybe it will be resolved automagically like this issue.
