### ISSUE TITLE
The Witcher 3 - Config option "dxgi.tearfree = true" has no effect

### ISSUE THREAD

**Issue by gabriele2000** [doitsujin/dxvk#2170]
That option should cap the framerate at 120fps (120hz screen) while adding lower input lag, I use it in every game, it's the best vsync in my opinion, but this is the only game which that option has no effect.
The location of dxvk.conf is correct, I'm certain, because the .log shows that the options are active, I also enabled the anisotropic filtering, and that does work.

fps in the top-left corner
![FPS to the left](https://user-images.githubusercontent.com/12186181/126072355-a412121b-4b6f-49c9-996d-c2958e31cb10.png)

### System information
- GPU: Nvidia Geforce GTX 1050TI (4GB - laptop)
- Driver: 465.31
- Wine version: 6.12-tgk-staging
- DXVK version: dxvk-master-d3112c320b1a2de3018612b7a4530b7bc3d84968 (1.9 latest master git)

### Log files
- d3d11.log: [witcher3_d3d11.log](https://github.com/doitsujin/dxvk/files/6836488/witcher3_d3d11.log)
- dxgi.log: [witcher3_dxgi.log](https://github.com/doitsujin/dxvk/files/6836489/witcher3_dxgi.log)

**Comment by DadSchoorse** [comment]
Nvidia doesn't support MAILBOX, so it's expected that tearFree won't work.

**Comment by gabriele2000** [comment]
> Nvidia doesn't support MAILBOX, so it's expected that tearFree won't work.

This "MAILBOX" it's only present in The Witcher 3? Because tearfree works in every other game

**Comment by doitsujin** [comment]
Mailbox does **not** cap the frame rate, so everything is working as intended. Use `dxgi.syncInterval = 1` in order to force Vsync.

**Comment by gabriele2000** [comment]
> This option should **not** cap the frame rate by design, so everything seems to be working as intended. Use `dxgi.syncInterval = 1` in order to force regular Vsync.

In every game tearFree also cap my framerate to 120fps, but it saves the latency cost of normal vsync... that is weird based on what you said months ago
