### ISSUE TITLE
Does D3D9 Support VMR9?

### ISSUE THREAD

**Issue by BruceMok** [doitsujin/dxvk#2172]
[https://docs.microsoft.com/en-us/windows/win32/directshow/video-mixing-renderer-filter-9](https://docs.microsoft.com/en-us/windows/win32/directshow/video-mixing-renderer-filter-9)

Does D3D9 of this source Support VMR9?

**Comment by K0bin** [comment]
That's part of DirectShow, not Direct3D9.
