### ISSUE TITLE
[D3D11] Kingdom Hearts III - Massive FPS drop after entering menu

### ISSUE THREAD

**Issue by corossig** [doitsujin/dxvk#2182]
Kingdom Hearts III runs very well on dxvk until going inside menu, then there is a massive FPS drop (60fps ->12fps).
Lines corresponding to actions inside d3d11.log: 
- line 39602 : entering menu
- line 44378 : exiting menu

![1_before_menu](https://user-images.githubusercontent.com/1239678/126895385-32af39dc-3dfc-4772-9d3e-3fe913445b02.png)
![2_inside_menu](https://user-images.githubusercontent.com/1239678/126895388-4cef2cb5-e6ed-4b71-bfda-f2fdcd3c9b65.png)
![3_after_menu](https://user-images.githubusercontent.com/1239678/126895394-87f455fd-47f4-41a8-8bf2-ebe05d9eaafb.png)

### Software information
 - Game: Kingdom Hearts III

### System information
- GPU: AMD RX 460
- Driver: Mesa 21.1.5
- Wine version: 5.22 staging
- DXVK version: v1.9-69-gb4e6f81c

### Apitrace file(s)
- Gzip compressed : https://we.tl/t-TvpIZL5L7H

### Log files
- d3d9.log: Empty
- d3d11.log: [KINGDOM HEARTS III_d3d11.log](https://github.com/doitsujin/dxvk/files/6873673/KINGDOM.HEARTS.III_d3d11.log)
- dxgi.log: [KINGDOM HEARTS III_dxgi.log](https://github.com/doitsujin/dxvk/files/6873674/KINGDOM.HEARTS.III_dxgi.log)

**Comment by K0bin** [comment]
> ### Apitrace file(s)

> * Put a link here

Please do that.

**Comment by doitsujin** [comment]
Also, pleeeeeeeeeeease do not use `DXVK_LOG_LEVEL=debug`. There's nothing happening there except that the game compiles shaders, which is normal.

Random guess: Your card only having 2GB of VRAM is what's causing issues because dxvk's memory management isn't great.

**Comment by corossig** [comment]
You are right, maybe the problem is 2GB, I had firefox launched in background. Without firefox, the problem is really hard to reproduce, so it seems linked.

**Comment by bno1** [comment]
Try disabling hardware acceleration in firefox, this might free up some vram.

**Comment by doitsujin** [comment]
Kind of surprised that the amd driver is seemingly shitting the bed here, usually this kind of thing isn't an issue, but anyway, not something we can (easily) fix on our end right now.
