### ISSUE TITLE
Operation Flashpoint: Red River (44340) - Main menu UI elements not being rendered

### ISSUE THREAD

**Issue by Vinjul1704** [doitsujin/dxvk#2184]
In the game "Operation Flashpoint: Red River" (Steam ID: 44340), the main menu UI elements are not being rendered when using DXVK. This was tested on Linux with various Proton versions, as well as on Windows 10. The attached apitrace file was done on Windows 10 with DXVK. The attached log is from the same test run. A separate apitrace done by a different user (from what it seems like) without DXVK can be found in this Proton issue: https://github.com/ValveSoftware/Proton/issues/4995

**Software**
Operation Flashpoint: Red River
(Steam, D3D9)

**System**
- GPU: Nvidia GTX 1060 6GB
- Driver: 466.47 (Windows), 470.57.02 (Linux)
- Wine: Steam Proton (latest 5.x, 6.x, experimental, ge)
- Windows: 10 Enterprise LTSC 2019
- DXVK: Release 1.9 (also tested last D9VK before merge)

**Apitrace**
https://www.swisstransfer.com/d/1ff705b3-7659-4281-b87d-f0d7cfd41114

**Log**
https://gist.githubusercontent.com/Vinjul1704/1a9d0b77efbbb5a3db018905290c70a0/raw/a8d166eeb70318e1d031c5fa5ff28cf9a502e3c7/RedRiver_d3d9.log

**Comment by Vinjul1704** [comment]
I also just tried latest master and 1.8.1 and they both give the same result.

**Comment by Vinjul1704** [comment]
Seems like my original apitrace upload got corrupted. Here is a new and uncompressed one (same apitrace): https://www.swisstransfer.com/d/1813d5d9-8c08-4551-93db-aaabb7b9c44a

**Comment by jarrard** [comment]
This game for me requires a custom OFFLINE GWFL xlive.dll and ini file. However even if you do get to main menu it won't render as you guys point out. For me the game crashes before it gets to menu but plays the intro fine. 

I've very surprised you were able to get a apitrace as I couldn't.  (even under windows). 

https://github.com/ValveSoftware/Proton/issues/4995

@doitsujin Hopefully this apitrace helps sometime to get this game resolved. (I know your ultra busy, but this is a little gem of the past :) )

**Comment by Blisto91** [comment]
@Vinjul1704 @jarrard Can you check if this is still an issue? This game seems hard to get a hold on.
If yes then please upload a new trace as the ones above doesn't seem to be up anymore

**Comment by jarrard** [comment]
Here is my apitrace I believe on windows 10. I'll test this out sometime today but I see no reason why it would suddenly start working, it was a extreme case of DXVK incompatibility that from my understanding nobody wanted to look at or fix from the proton/dxvk team as its a older game that has been discontinued. (and has annoying GFWL issues)

https://www.dropbox.com/sh/umeo4j8lqnrnkhe/AAD4-rcqOg2ob9N5i3VtNB6Ka?dl=0

**Comment by Blisto91** [comment]
Can confirm it is still an issue with dxvk.

**Comment by jarrard** [comment]
Yeah its a bit of a mystery, uses Same engine as Dirt 3 I think (one of those) and that works.. OFP2 normal works last I checked.. It's just Red River has something unique going on with its rendering pipeline that DXVK just does not want to accept.

I haven't tested it out on NVIDIA or Intel hardware so maybe their drivers respond differently with it... doubtful

**Comment by Blisto91** [comment]
I tried on windows with dxvk and it was the same, so definitely a dxvk thing yes.

**Comment by Blisto91** [comment]
Don't think other drivers will matter here either

**Comment by Vinjul1704** [comment]
I did my initial testing on an Nvidia GPU and had the same issue, so yeah.

**Comment by WinterSnowfall** [comment]
@Vinjul1704 Could you please test with the below build and let me know if it improves things?

[d3d9.dll.zip](https://github.com/doitsujin/dxvk/files/10971416/d3d9.dll.zip)

**Comment by jarrard** [comment]
I will once I get the chance. My GPU atm is causing HUGE issues.  
Guess I could test this under Windows!

**Comment by Vinjul1704** [comment]
> @Vinjul1704 or @jarrard Could you please test with the below build and let me know if it improves things?
> 
> [d3d9.dll.zip](https://github.com/doitsujin/dxvk/files/10971416/d3d9.dll.zip)

Nope, that doesn't seem to change anything. The UI is still missing and ingame-geometry is as broken as before.

**Comment by WinterSnowfall** [comment]
> Nope, that doesn't seem to change anything. The UI is still missing and ingame-geometry is as broken as before.

Thank you for testing. There were some differences between the state recorded in the trace and how it played out with dxvk that I had corrected. But if that doesn't do anything for the game I'm out of ideas, sadly.

**Comment by baazthefalcon** [comment]
so whats the status on this ? still not fixed...game works properly without dxvk

**Comment by jarrard** [comment]
I do believe OFP2 normal works fine under DXVK.  Haven't confirmed this myself tho.

**Comment by baazthefalcon** [comment]
> That is the current status yes. It will be looked at again don't worry. If you are on Windows just play without.

I want to use RTX Remix on this game, and Remix is created based on dxvk, untill dxvk dont fix it... i cannot try...

**Comment by Vinjul1704** [comment]
> I do believe OFP2 normal works fine under DXVK. Haven't confirmed this myself tho.

If by OFP2 you mean Dragon Rising, then yes, that one works fine.

**Comment by baazthefalcon** [comment]
Thank you @K0bin working on it so fast, i have tried the package #3666 but no luck with x32 d3d9.dll game doesn't boot and i am on windows 11 pro latest build, game needs to run as administrator otherwise ithe gives securom error 2000, hope this info helps , if u need any help feel free to ask.

**Comment by K0bin** [comment]
I don't have access to the actual game and Windows is not really a supported platform for DXVK. Maybe post DXVK logs and I'll see if there's anything obvious in there.

**Comment by baazthefalcon** [comment]
for some reason game is not able to works with any of the dxvk , i think this is happening due to windows 11 (this is new) before it worked , cannot get logs if dxvk will not work, i will report as soon as figure out this.

**Comment by WinterSnowfall** [comment]
> for some reason game is not able to works with any of the dxvk , i think this is happening due to windows 11 (this is new) before it worked

Probably worth making sure it's not this: https://github.com/doitsujin/dxvk/wiki/Windows#dozen

**Comment by baazthefalcon** [comment]
game didn't boot still somehow gave log 
[RedRiver_d3d9.log](https://github.com/doitsujin/dxvk/files/14310382/RedRiver_d3d9.log)
[RedRiverLauncher_d3d9.log](https://github.com/doitsujin/dxvk/files/14310383/RedRiverLauncher_d3d9.log)

**Comment by Blisto91** [comment]
The main game log doesn't contain anything so doesn't look like dxvk even gets to get going properly.

**Comment by jarrard** [comment]
The first thing you must do is ensure you successfully bypass the GFWL system. If you haven't tried the hacked or faked DLL's for that then you won't get far!

**Comment by baazthefalcon** [comment]
i have that already

**Comment by K0bin** [comment]
> I want to use RTX Remix on this game, and Remix is created based on dxvk, untill dxvk dont fix it... i cannot try...

FYI that isn't gonna work anyway. The game doesn't use fixed function rendering.

**Comment by baazthefalcon** [comment]
> From a quick test, looks like #3852 fixes both the UI and ingame render issues. Thanks!

game is x32bit so can u confirm if its using vulkan api, if u used x64 dll then game will fine it doesnt uses vulkan api
u can check it with msi afterburner

**Comment by Vinjul1704** [comment]
> > From a quick test, looks like #3852 fixes both the UI and ingame render issues. Thanks!
> 
> game is x32bit so can u confirm if its using vulkan api, if u used x64 dll then game will fine it doesnt uses vulkan api u can check it with msi afterburner

That comment is about it working fine on Linux. I didn't try DXVK on Windows.

**Comment by baazthefalcon** [comment]
> > I want to use RTX Remix on this game, and Remix is created based on dxvk, untill dxvk dont fix it... i cannot try...
> 
> FYI that isn't gonna work anyway. The game doesn't use fixed function rendering.

that will be seen later, as remix is improved day by day

**Comment by Blisto91** [comment]
It is based on working with games that use fixed function pipelines so there are alot of games it simply can't work with because of how they render.

**Comment by baazthefalcon** [comment]
> It is based on working with games that use fixed function pipelines so there are alot of games it simply can't work with because of how they render.

i am aware of that and i am also aware of this game is dx9c

**Comment by jarrard** [comment]
Sadly I'm unable to test this myself as it won't work on my 4090 under Windows or Linux, even after following 4 different guides on getting it working.  It seems it can only work on OLDER RTX drivers (not 40 series) and GTX cards, or AMD/Intel. 

Bit of a shame.

**Comment by K0bin** [comment]
@jarrad The game or DXVK does nothing that shouldn't work on Nvidia Ada Lovelace.

**Comment by Blisto91** [comment]
Indeed it works fine on my 4080 through Proton. Remember to disable esync and fsync and also install gfw.

**Comment by jarrard** [comment]
> Indeed it works fine on my 4080 through Proton. Remember to disable esync and fsync and also install gfw.

Are you also able to get it working under Windows11? on a RTX40?  

I have been trying there also and it just won't work, just silently quits, nothing even pops up.  I have  GFW installed and tried workarounds.

**Comment by Blisto91** [comment]
> Are you also able to get it working under Windows11? on a RTX40?

Yes. Though on Windows i use Xliveless not a full gfw install https://community.pcgamingwiki.com/files/file/576-xliveless/

**Comment by jarrard** [comment]
Yeah I've tried all that, no luck for me sadly.  Some people say downgrade GPU driver but I can't do that.

**Comment by Vinjul1704** [comment]
> Yeah I've tried all that, no luck for me sadly. Some people say downgrade GPU driver but I can't do that.

Does it not launch at all for you, even on Windows without DXVK?

What GFWL method are you using? For me, just installing the full thing from here and using an offline account worked fine: https://www.pcgamingwiki.com/wiki/Games_for_Windows_-_LIVE#Download

**Comment by jarrard** [comment]
I tried all methods.  No run under Windows or Linux.

**Comment by Blisto91** [comment]
Post a log

**Comment by jarrard** [comment]
Unfortunately there are just not logs.  DXVK initializes just fine.  The game EXE just quits silently.

**Comment by baazthefalcon** [comment]
so i tested again with latest dxvk and its working with vulkan and everything is rendering properly, just want to thank you guys who worked on this, really appreciated.

**Comment by baazthefalcon** [comment]
still pointing this that yesterday i installed graphics from game ready drivers to studio drivers.

**Comment by Levan7** [comment]
It crashes for me on linux the latest dxvk-2.6.1 build and so does it on windows

**Comment by jarrard** [comment]
haven't tested it for some time, worth a try again. Although not playing anything atm since gamescope is borked under arch, again.

**Comment by Levan7** [comment]
It works under windows i retested. I will give linux a try but checked proton db and it looks like this game is all broken under linux might be that 
https://www.protondb.com/app/44340
