### ISSUE TITLE
Error in dxva_video_decode_accelerator_win.cc

### ISSUE THREAD

**Issue by Arndorferd** [doitsujin/dxvk#2185]
Getting :
[444:448:0725/234745.504:ERROR:mf_helpers.cc(14)] Error in dxva_video_decode_accelerator_win.cc on line 361

trying to run this game on Proton or Wine, its a Visual Novel game

### Software information
The Pirates Fate (Game), Proton/WIne (Runner), Manjaro (OS), Lutris

### System information
- GPU: Intel(R) HD Graphics 4000 (IVB GT2)
- Driver: 21.1.5
- Wine version: wine-valve 6.3.20210616-1
- DXVK version: Same errors on v1.9L-8b6ac52, 1.9L, 1.81L

### Log files
- d3d11.log: [RealGameUnpacked_d3d11.log](https://github.com/doitsujin/dxvk/files/6875755/RealGameUnpacked_d3d11.log)
- dxgi.log: [RealGameUnpacked_dxgi.log](https://github.com/doitsujin/dxvk/files/6875756/RealGameUnpacked_dxgi.log)

**Comment by doitsujin** [comment]
> [444:448:0725/234745.504:ERROR:mf_helpers.cc(14)] Error in dxva_video_decode_accelerator_win.cc on line 361

This is not an error from DXVK. Does the game work with wined3d?

Also, note that Vulkan support on your GPU is dodgy at best so please don't expect DXVK to work very well on it, especially for D3D11 games.

**Comment by iWeaker4you** [comment]
Intel HD 4000 has very incomplete Vulkan support , the solution for you is to disable DXVK and use WineD3D instead.

**Comment by Faalagorn** [comment]
Alternatively, there's Gallium Nine with Crocus drivers, too, but that's up to @Arndorferd to verify how the game performs on those. :)

**Comment by Arndorferd** [comment]
getting the same error with an nvidia rtx 2080 Ti so its not that

**Comment by Arndorferd** [comment]
Couldnt ever figure out how to try to get gallium nine to work either

**Comment by Blisto91** [comment]
@Arndorferd Could i get you to check again with latest dxvk?

**Comment by Hideman85** [comment]
Getting same issue [0928/213818.236:ERROR:mf_helpers.cc(12)] Error in dxva_video_decode_accelerator_win.cc on line 355
- Game: Grounded
- OS: Ubuntu 22.04 (All up to date)
- Runner: Lutris wine Proton 7.28
- (GPU): Intel Iris Xe

**Comment by Blisto91** [comment]
Which dxvk version and which drivers

**Comment by Hideman85** [comment]
Defaults from lutris as:
- DXVK 1.10.3
- VKD3D 2.6
- D3D Extra 2

Could you give me a hand how to get the Intel Iris Xe driver version? :thinking: 
Gonna check if I can grab the logs.

**Comment by Blisto91** [comment]
I will try to check out grounded tomorrow on steam. See if i Notice anything.

**Comment by K0bin** [comment]
> Getting same issue [0928/213818.236:ERROR:mf_helpers.cc(12)] Error in dxva_video_decode_accelerator_win.cc on line 355

That's a Wine issue, not a DXVK one.

**Comment by Hideman85** [comment]
I found the following https://github.com/ValveSoftware/Proton/issues/4102 people noticing that the fix made by proton is not anymore working since the latest version of this game.

**Comment by K0bin** [comment]
Does it work if you disable DXVK? `PROTON_USE_WINED3D=1`

**Comment by Blisto91** [comment]
Or in lutris tick the dxvk option so it is off.

**Comment by Hideman85** [comment]
Yes I tried to turn off, use the env var and even install with winetricks d3dx11_43 none of these options work, even worse it does not show loading screen.
Will try the option to force dx11

**Comment by K0bin** [comment]
If it doesn't work with WineD3D either, it's a Wine bug.

**Comment by Hideman85** [comment]
Will wait a Proton fix then, I guess it would be faster to come :sweat_smile:

**Comment by Blisto91** [comment]
Fwiw I'm not sure that it's the `dxva_video_decode_accelerator_win.cc` error that's the issue here (but don't know so maybe). But i don't think it's dxvk etiher
But i will check it myself tomorrow. If i reproduce and figure something out i will long you in the proton issue

**Comment by Hideman85** [comment]
That would be awesome, thank you in advance mate :slightly_smiling_face:

**Comment by Blisto91** [comment]
You should post in the Proton issue.

**Comment by KeebWasTaken** [comment]
> 
you right, will share it there too, hopefully someone figures out a fix
