### ISSUE TITLE
Drastic performance drop while using DXVK on Windows with GTA IV

### ISSUE THREAD

**Issue by two1212** [doitsujin/dxvk#2187]
**With** **DXVK**, the game just constantly remains at around 7-10 FPS and GPU usage is 100% with CPU being used around 50%, **Without** **DXVK**, the CPU is around 100% and GPU is around 60-70% but with higher FPS (20-35). These performance drops are only prevalent on GTA IV, other games run fine with DXVK on Windows. It should be noted that I have an older Intel CPU (E5800) and 2GB RAM.
### Note
I have tested the same game with DXVK on a AMD laptop (R5 2500U/Vega 8) and that is completely fine with around 30 FPS with stable framtimes.

### Software information
Grand Theft Auto IV The Complete Edition  V1.2.0.43
### System information
- GPU:  Nvidia GT 1030 2GB GDDR5
- Driver: 471.41
- OS: Windows 8.1 (Build 9600) 
- DXVK version: 1.9

### Apitrace file
- https://drive.google.com/file/d/1YMLmQ0nySRehpt6FmQrHq4DVA6j2dSg9/view?usp=sharing

### Log files
[GTAIV_d3d9.log](https://github.com/doitsujin/dxvk/files/6876060/GTAIV_d3d9.log)

**Comment by K0bin** [comment]
DXVK does very poorly on 2GB cards. It's possible that GTA IV managed to exceed the 2GB of VRAM. 

There isn't really anything we can do here.

**Comment by two1212** [comment]
> DXVK does very poorly on 2GB cards. It's possible that GTA IV managed to exceed the 2GB of VRAM.
> 
> There isn't really anything we can do here.

I am afraid you may be right since I saw the memory bus usage of the card and it was at 80% constant, it never goes that high even with much more intensive games like BF4 and always stays in the range of 10-20% from what I have noticed

**Comment by K0bin** [comment]
Try DXVK master and see if that makes a difference.

**Comment by mirh** [comment]
I know of #1318, but OP is just playing a 2008 game in full hd. 
Cards with less than 4 times as much memory should be fine with it.

**Comment by K0bin** [comment]
> I know of #1318

That is about system memory. This is about VRAM.

**Comment by two1212** [comment]
Sorry for the late reply, I just tested the lastest release/master build and it seems to mitigate some of the issues (around 30 FPS in very less intensive areas) which seems much better than before and I have been trying to install my old retail version from 2008 to test DXVK on that, will update after that

**Comment by two1212** [comment]
Hey, after countless hours of reading through different forums, threads and posts and also trial and error, I finally found that any GTA IV version which is higher than 1.0.7.0 performs very bad with DXVK and from what I can speculate.. it seems to be stressing the memory and the memory bus of the GPU but I don't know why it does so.. Anyways, the older versions of the game (<1.0.8.0) work fine from what I have tested at least on my Nvidia/Intel system with any DXVK version with DX9 support but I have read many posts, blogs and comments where people were experiencing similar problem to mine with a higher end GPU(GTX 1070, 1060, RTX 2060 Super and so on).
It may be a Nvidia Specific issue since I couldn't find any problems with my AMD APU with that specific game version or maybe I don't know but I think this issue should be known. Though Thanks for the help either way K0bin.

**Comment by K0bin** [comment]
>  finally found that any GTA IV version which is higher than 1.0.7.0 performs very bad with DXVK

There was a bit of a problem with DXVK 1.9, thats fixed now. The game runs very well for me on my Nvidia GPU. As I said, most likely out of VRAM. I think the game has config options to adjust the amount of size of the texture pool the game will use. Try playing around with that.
