### ISSUE TITLE
doubt: Any way to force exclusive fullscreen ?

### ISSUE THREAD

**Issue by ranplayer** [doitsujin/dxvk#2189]
Hi,

Is there any way to force exclusive fullscreen through dxvk settings ? I have some titles that don't allow the user to change the window mode through their interfaces, configuration files or parameters.

Regards

**Comment by doitsujin** [comment]
On Windows we already use the exclusive fullscreen hint if available. On Linux, the concept doesn't really exist.

**Comment by ranplayer** [comment]
Thanks for the explanation regarding fullscreen on Linux.

Regards
