### ISSUE TITLE
dxvk 1.9/1.9.1: some textures/elements not show (Heroes of Might and Magic V: Tribes of the East, dx9)

### ISSUE THREAD

**Issue by jl452** [doitsujin/dxvk#2194]
try with standalone Proton-6.1-GE-2/6.13-GE-1

dxvk1.8/1.8.1 work (not long play time, but seems like all ok)
dxvl1.9/1.9.1 work not all graphics (in menu no some elements (scrollbar, buttons border, ...), on map not see some objects)

dx9, x86 game

only this warnings in log:
> warn:  OpenVR: Failed to locate module
> warn:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
> warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_DITHERENABLE

**Comment by K0bin** [comment]
I need an apitrace to debug this. And please at least add some screenshots so we have any idea what's actually wrong with it.

**Comment by WinterSnowfall** [comment]
Dropping by to say I've played the game a bit, went into towns, started a few battles and looked at every menu and sub-menu I can think of, and they all looked fine to me. This is on Nvidia 470.57.02 with 1.9.1.

**Comment by K0bin** [comment]
I do not own the game, I can not fix this until someone provides an apitrace.

**Comment by jl452** [comment]
sorry, many work now (and before i done update all drivers and kernel (and amdvlk now not work for me, but with mesa-vulkan bugs reproduce))
i will make screenshots soon

**Comment by K0bin** [comment]
I need an apitrace, not a screenshot.

**Comment by jl452** [comment]
[H5_Game.trace.1.7z](https://we.tl/t-ekcd9kdhUC) 30mb 1week link

Proton-6 15-GE-2_dxvk191_1
![Proton-6 15-GE-2_dxvk191_1](https://user-images.githubusercontent.com/14292072/130055820-cf80e64d-5f90-432e-bc1b-f1583db6fe61.png)
Proton-6 15-GE-2_dxvk191_2
![Proton-6 15-GE-2_dxvk191_2](https://user-images.githubusercontent.com/14292072/130055810-773d74a3-3c06-4e40-a6b7-df3396a2af74.png)

Proton-6 15-GE-2_dxvk181_1
![Proton-6 15-GE-2_dxvk181_1](https://user-images.githubusercontent.com/14292072/130055823-6c2f411e-68a9-4eba-a37e-4a7fe5db8614.png)
Proton-6 15-GE-2_dxvk181_2
![Proton-6 15-GE-2_dxvk181_2](https://user-images.githubusercontent.com/14292072/130055821-1996f6bb-e5a9-46d4-b729-77569bbe146c.png)

Proton-6 15-GE-2_wined3d
![Proton-6 15-GE-2_wined3d](https://user-images.githubusercontent.com/14292072/130055826-592df0c9-d8a3-4a73-ab68-bff7093010c9.png)

**Comment by WinterSnowfall** [comment]
Interesting. Looks fine on Nvidia even on 1.9.1, as per below:

![HoMMV](https://user-images.githubusercontent.com/6306593/130062141-919259eb-a72b-48ec-9f5b-23674838e64e.png)

**Comment by jl452** [comment]
is label "needs apitrace" actual?

**Comment by K0bin** [comment]
I haven't looked at it yet.

**Comment by jl452** [comment]
[H5_Game.trace.1.7z](https://we.tl/t-4LopnvGNxp) 30mb 1week link

**Comment by K0bin** [comment]
Looks like this:
![image](https://user-images.githubusercontent.com/1131720/131263349-2fa3807c-8def-4e26-ac37-f27a9399634d.png)
with D3D9 on Windows, so either the apitrace is broken or it's not a DXVK bug.

At any rate, the trace only contains 14 frames which is not nearly enough.

**Comment by jl452** [comment]
fixed in dxvk 1.9.2
