### ISSUE TITLE
D3D9 Float behavior Megaissue

### ISSUE THREAD

**Issue by K0bin** [doitsujin/dxvk#2195]
DXVK does not emulate some aspects of the D3D9 floating point behavior properly resulting in visual issues.

**Comment by K0bin** [comment]
Impacts:

#2016
#2107
#2186
#1619

**Comment by CME42** [comment]
https://github.com/doitsujin/dxvk/issues/1875

**Comment by Koncord** [comment]
Зюзшшшшшшщщшшлщщлщщшщд. Щщзз на антибиотики посадили за из самых щзжззз не
ззззз не знаю почему здравствуйте зл.   От. Зззщззз не былое и зззззне не
знаю почему не отвечаете в

пн, 9 авг. 2021 г., 07:47 CME ***@***.***>:

**Comment by K0bin** [comment]
#1790

**Comment by DadSchoorse** [comment]
#1983

**Comment by K0bin** [comment]
c13395db970d16a5631a7c0926e2c4529d2710c3
