### ISSUE TITLE
black screen in Days Gone but can hear game starting (game sounds)

### ISSUE THREAD

**Issue by malonzat** [doitsujin/dxvk#2196]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
Preferably record the trace on Windows, or wined3d if possible.

**Reports with no log files will be ignored.**

### Software information
Name of the game, settings used etc.

### System information
- GPU:gtx 1050ti
- Driver:471.41
- Wine version: 
- DXVK version: 1.7.1
  Os: win 10

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
- d3d11.log:yes
-  @[dxgi.log:yes
[DaysGone_d3d11.log](https://github.com/doitsujin/dxvk/files/6904424/DaysGone_d3d11.log)
[DaysGone_dxgi.log](https://github.com/doitsujin/dxvk/files/6904425/DaysGone_dxgi.log)

**Comment by malonzat** [comment]
I also tried with 1.9.1 before Rolling back to 1.7.1,same thing happens.
I get black screen but i hear sound(game start and menu sound) when starting days gone game, matter of fact i tried every game same issue happening, please assist,,thanks!

**Comment by doitsujin** [comment]
The game is [known to work](https://www.protondb.com/app/1259420) on Proton, probably not our bug.

**Comment by malonzat** [comment]
> The game is [known to work](https://www.protondb.com/app/1259420) on Proton, probably not our bug.


hello! Thanks for your reply,what do you suggest me to do so i can get it to work properly?

**Comment by K0bin** [comment]
Install Linux or uninstall DXVK.

**Comment by malonzat** [comment]
> Install Linux or uninstall DXVK.
Ah, ill go for the second one,thanks for your help!
