### ISSUE TITLE
[Documentation] Provide apitrace instructions for steam/proton

### ISSUE THREAD

**Issue by TRPB** [doitsujin/dxvk#2197]
I was about to report a bug in Elite Dangerous with messed up colours on smoke effects as of the latest in-game update but this bug report page requires an apitrace file, unfortunately it's not clear how to do this through steam (proton). I tried adding 

```
apitrace.exe trace -a dxgi  %command%
```
However it doesn't launch which implies apitrce.exe isn't included in the prefix. Is there an easy way to include apitrace.exe reports from within steam?

**Comment by K0bin** [comment]
The guide over here is still pretty good:
https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace

**Comment by K0bin** [comment]
You added an apitrace to your original issue, so I think it's safe to say that you did figure it out.
Closing this.
