### ISSUE TITLE
Elite Dangerous Odyssey Update 6 smoke rendered as rainbows

### ISSUE THREAD

**Issue by TRPB** [doitsujin/dxvk#2198]
### Software information

Elite Dangerous Odyssey Update 6. When running the game smoke effects anywhere in the game are replaced with incorrectly rendered textures:

![20210729181834_1](https://user-images.githubusercontent.com/2454540/127650077-67c7eb1b-c980-4dcf-b7fc-a4423f4e560d.jpg)

This screenshot is from the menu but it happens in game anywhere smoke is drawn.

What I have tried:

- A clean wine prefix (I deleted compdata/359320 and let it rebuild) as this game computes shaders on startup  both in steam and in game, I thought it could be an invalid cache
- Ultra graphics preset
- Low graphics preset
- This update introduced AMD FSR 1.0, I can't see how FSR would introduce rendering issues on specific textures but I tried turning it off anyway and it didn't make any difference. 

None of these helped and the problem persists.  This didn't happen in the earlier version of ED and if I launch the older expansion, Horizons, it works fine. It's something about the update 

### System information
- GPU: Radeon VII
- Driver: MESA
- Wine version: Proton (Latest on steam as of  30/07/2021, Proton-GE 6.5 also has the same issue)
- DXVK version: v1.8.1-36-g9e646a34-async

### Apitrace file(s)

If you can provide instructions for running this through steam I'll happily provide it

### Log files
- d3d9.log:

[EDLaunch_d3d9.log](https://github.com/doitsujin/dxvk/files/6907398/EDLaunch_d3d9.log)

- d3d11.log:

[EliteDangerous64_d3d11.log](https://github.com/doitsujin/dxvk/files/6907401/EliteDangerous64_d3d11.log)

- dxgi.log:

[EliteDangerous64_dxgi.log](https://github.com/doitsujin/dxvk/files/6907402/EliteDangerous64_dxgi.log)

**Comment by K0bin** [comment]
> v1.8.1-36-g9e646a34-async

Does it happen with unpatched DXVK builds? (without the async hack)

**Comment by TRPB** [comment]
Yes, that was the log from proton-GE this is the log file from the latest proton (standard):


[EliteDangerous64_d3d11.log](https://github.com/doitsujin/dxvk/files/6907579/EliteDangerous64_d3d11.log)

[EliteDangerous64_dxgi.log](https://github.com/doitsujin/dxvk/files/6907583/EliteDangerous64_dxgi.log)

This just reports DXVK 1.9, the exact same thing happens.

**Comment by doitsujin** [comment]
Gonna need an apitrace.

**Comment by TRPB** [comment]
I'll try to get an APItrace but to run the game

1. Update wine mono in the prefix as per https://github.com/redmcg/wine-mono/wiki#with-protontricks
2. Run `protontricks -c 'mkdir ../../compatdata/359320/pfx/drive_c/users/steamuser/Local\ Settings/Application\ Data/Elite\ Dangerous\ Launcher_evidencehere' 359320`
3. Launch the game and select Odyssey (The top default option if you have the latest DLC) in the launcher.
4. Wait for the main menu (it takes a long time and looks like it's frozen, just wait). The menu shows a ship with the smoke effect as per the screenshot

If for some reason a new character doesn't have a ship/smoke on the menu you can start the tutorial and there's smoke in the first base.

**Comment by TRPB** [comment]
Here's an API trace, it's too big to attach and most of this is from the "Preparing planet generation system" shader compilation outlined here: https://github.com/ValveSoftware/Proton/issues/150 

If you start from the end (or are able to work out where it draws the menu by looking for text from the screenshot above), the smoke is on the screen when that menu is drawn.

I've uploaded the trace go google drive here: https://drive.google.com/file/d/1fqcT4EuNenAVdORAYcpCsxLySMlZOc2O/view?usp=sharing

**Comment by Oschowa** [comment]
The trace replays fine here on RADV and Polaris, but from your log files it looks like you are using amdvlk and not Mesa driver:  
`Device name:     : AMD Radeon VII`
Please try to uninstall amdvlk and try again.

**Comment by TRPB** [comment]
Oh, thanks! I had thought  AMDVLK had to be manually enabled  on a per game basis, I didn't realise it had become the default on Arch. (I don't even know how it decides which is the default when both are installed).

Using `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json %command%` fixes the issue.

**Comment by doitsujin** [comment]
AMDVLK ships with a layer that hides RADV devices by default, which can be disabled by setting `DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1` (or just uninstalling AMDVLK, as was suggested).

**Comment by mikoThyr** [comment]
Looks like my problem.

> glxinfo
> Vendor: AMD (0x1002)
> Device: AMD Radeon RX 580 Series (polaris10, LLVM 13.0.1, DRM 3.42, 5.15.48-1-MANJARO) (0x67df)
> Version: 22.2.0

> vulkaninfo
> deviceName        = AMD Radeon RX 580 Series (RADV POLARIS10)
> apiVersion        = 4206809 (1.3.217)
> vendorID          = 0x1002
> deviceID          = 0x67df
> deviceType        = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU

I'm starting game by lutris and steam proton. When I set llvm by enviromental variables (RADV_DEBUG=llvm) then I see incorectly rendered fog, smoke textures. Without llvm the game fps are lower but graphic is rendered correctly.
![Screenshot_20220618_212607](https://user-images.githubusercontent.com/94358914/175025596-ee353fb6-6764-4a41-bf1c-6899ab3448a9.png)
