### ISSUE TITLE
Alan Wake: Flashing lights and coloured frames

### ISSUE THREAD

**Issue by NotBigIntoBooks** [doitsujin/dxvk#2199]
When playing Alan Wake using DXVK on Windows, when looking in some directions there are flashing lights at the top of the screen, and some frames are black or a filtered colours. These anomalies are linked to framerate so are difficult to capture screens of.

![AlanWake_2021_07_30_13_38_38_212](https://user-images.githubusercontent.com/32595548/127655917-e2125c8d-2fb9-4f0a-bff9-93c8811eb1e2.jpg)
![AlanWake_2021_07_30_13_39_06_155](https://user-images.githubusercontent.com/32595548/127655921-676b3505-7eac-45f6-80c9-1b979b297621.jpg)
![AlanWake_2021_07_30_13_39_07_184](https://user-images.githubusercontent.com/32595548/127655933-0ce3993a-bf89-4941-80a6-bfe3963dd39f.jpg)

### Software information
Alan Wake (Steam)
Settings: 4x AA and the rest in the screenshot.
![AlanWake_2021_07_30_13_47_12_084](https://user-images.githubusercontent.com/32595548/127655972-c8d644bd-f381-4db9-92a2-d566ab4c7332.jpg)

### System information
- GPU: AMD RX 6700 XT 
- Driver: 21.7.2 (latest)
- Wine version: NA
- DXVK version: 1.9.1 (latest binary)

### Apitrace file(s)
https://mega.nz/file/uNtQHDwZ#V5iSB9z7z5fzWFLMErw9MHg4ebC3OLEEingz5bCvVxs

### Log files
[AlanWake_d3d9.log](https://github.com/doitsujin/dxvk/files/6907598/AlanWake_d3d9.log)

Thanks for making DXVK, its very useful for working around AMD not optimizing older APIs in the Windows drivers for their newer cards.

**Comment by K0bin** [comment]
I can't reproduce the problem and there are no validation errors either. This is probably an AMD Windows driver bug.

**Comment by NotBigIntoBooks** [comment]
What are appropriate next steps other than a bug report with AMD?

**Comment by Squall-Leonhart** [comment]
try with DXVK 1.7.3

**Comment by NotBigIntoBooks** [comment]
Thanks for the suggestion, the issues don't appear with 1.7.3.

**Comment by Squall-Leonhart** [comment]
Probably the same as #2179

**Comment by K0bin** [comment]
It is indeed. Feedback loop.

**Comment by Blisto91** [comment]
@NotBigIntoBooks Friendly ping.
Could you try this again with 1.10.2 and latest driver?

**Comment by NotBigIntoBooks** [comment]
> @NotBigIntoBooks Friendly ping. Could you try this again with 1.10.2 and latest driver?

Unfortunately not, I'm not near my desktop and won't be for a while

**Comment by NotBigIntoBooks** [comment]
@Blisto91 I've now had the opportunity to check. With 1.10.3 the issue appears to be resolved.
