### ISSUE TITLE
Gothic 3: Regression 1.9.1 (dx9)

### ISSUE THREAD

**Issue by Bxaa** [doitsujin/dxvk#2200]
1) Enabling evictManagedOnUnlock -  texture uploading bug
<a href="https://ibb.co/1zYss12"><img src="https://i.ibb.co/1zYss12/Gothic3-2021-07-30-22-42-32.png" alt="Gothic3-2021-07-30-22-42-32" border="0"></a>
2) Missed textures (not depend on evictManaged)
Example Gothic3:
<a href="https://ibb.co/rknNJZ2"><img src="https://i.ibb.co/rknNJZ2/Gothic3-2021-07-30-22-41-25.png" alt="Gothic3-2021-07-30-22-41-25" border="0"></a>

Also this build still have texture upload issue (random)
https://github.com/doitsujin/dxvk/actions/runs/1040312362

**Comment by K0bin** [comment]
The issue template exists for a reason. Please provide the required info and the apitrace. You hardly even bothered to tell us which game has the issue.

**Comment by Bxaa** [comment]
```
Missed textures (not depend on evictManaged)
Example Gothic3:
```

**Comment by Bxaa** [comment]
Used for trace: https://ci.appveyor.com/api/projects/jrfonseca/apitrace/artifacts/build/apitrace-latest-win32.7z?branch=master&job=msvc32

As i said trace not useful in this case
No issue with trace version. Is it igore dxvk.conf?
----------------------------------------
d3d9.samplerAnisotropy  = 16
d3d9.evictManagedOnUnlock = True
d3d9.deferSurfaceCreation = True
d3d9.shaderModel = 3
---------------------------------------

**Comment by K0bin** [comment]
Please also provide logs.

**Comment by Bxaa** [comment]
Used for trace: https://ci.appveyor.com/api/projects/jrfonseca/apitrace/artifacts/build/apitrace-latest-win32.7z?branch=master&job=msvc32

As i said trace not useful in this case
No issue with trace version. Is it igore dxvk.conf?

d3d9.samplerAnisotropy  = 16
d3d9.evictManagedOnUnlock = True
d3d9.deferSurfaceCreation = True
d3d9.shaderModel = 3

Trace (no issue)
https://drive.google.com/file/d/16BZstlrKyBg4Tdo0pokR_rbks0vsBK3H/view?usp=sharing

**Comment by jarrard** [comment]
I had to use amdvlk driver to resolve my texture related issues in this game. Radv was buggy.

**Comment by K0bin** [comment]
I already fixed the bug in the PR linked above, this has nothing to do with Radv.
