### ISSUE TITLE
Max Payne 3; Tessellation Issue

### ISSUE THREAD

**Issue by jarrard** [doitsujin/dxvk#2202]
Max Payne 3 has broken tessellation when using DXVK but not Wined3d11

### Software information
Max Payne 3, Just enable tessellation for issue to show.

### System information
- GPU: 6800XT
- Driver: RADV
- Wine version: ProtonGE-6.13  AND Proton6.3-5
- DXVK version:  1.9.1

### Apitrace file(s)
- soon

### Log files
- d3d11.log: [MaxPayne3_d3d11.log](https://github.com/doitsujin/dxvk/files/6911043/MaxPayne3_d3d11.log)
- dxgi.log: [MaxPayne3_dxgi.log](https://github.com/doitsujin/dxvk/files/6911042/MaxPayne3_dxgi.log)
- proton log: [steam-204100.log](https://github.com/doitsujin/dxvk/files/6911041/steam-204100.log)
- Gist:  https://gist.github.com/jarrard/83901432e10599bab09c96d6ba471f0d

Thought I'd open this issue here since I discovered DXVK is causing the problem from what I can tell. 

Any suggestions welcome, I've tried invariantgeom already.  Yes I tested with MANGOHUD and VKBASALT disabled, no change.

**Comment by doitsujin** [comment]
Can we have an apitrace and some sort of screenshot that shows what exactly is broken? Given that this is a Rockstar game, getting it to run is very hard and I'd like to avoid wasting countless hours fighting their stupid Social Club crap.

Also, the game has been known to work in the past, probably a driver bug or something.

**Comment by jarrard** [comment]
1) I'll sort out the apitrace for you.  (will a linux apitrace do?)
2) The issue can be seen at the main menu where the main character is sitting down at chair.
3) Tessellation is off by default, most people won't see the issue.
4) Game works fine without tessellation. 
5) WineD3D11 does not produce this issue, seems DXVK related. I've tried other drivers also.

This is probably a DXVK+AMDGPU related problem is my guess.

**Comment by doitsujin** [comment]
p sure this is a RADV bug, works fine on the proprietary driver.

**Comment by jarrard** [comment]
Yeah I couldn't get any debug tools to work either, even when disabling the rockstar launcher and using a few different methods.

Additionally when I try and run DXVK under windows10 I get a SWAP_CHAIN error so I couldn't test to see if the tessellation issue was present there.
