### ISSUE TITLE
Question about DXVK's d3d9.presentInterval feature

### ISSUE THREAD

**Issue by RSF-Deus** [doitsujin/dxvk#2204]
Thanks to your previous messages, I've been able to experiment with the config file to great effect.
There is something which particuarly caught my attention, the d3d9.presentInterval feature will indeed repeat frames x number of times, which is super handy for games that are locked to 60 FPS, they will still run at 60 FPS, but Vulkan will make the GPU send 120 FPS to the monitor (of course if the refreshrate can support it)

That made me think, this could be a golden opportunity to have black frame insertion at a software level universally for Vulkan, so everyone get to enjoy it and not only people who have very expensive monitors or TVs. I searched for a software solution for a very long time and the only one that exists is inside MAME (it's a retro emulator), but no projects outside of it so far.

**Comment by K0bin** [comment]
See #1847
