### ISSUE TITLE
Super Mecha Champions

### ISSUE THREAD

**Issue by kodatarule** [doitsujin/dxvk#2205]
The game either works one time with DXVK absolutely fine or it takes 50 tries or more to get into it, while it works every single time with WINED3D(but the performance isn't the best). I tried doing apitrace both of DXVK and WineD3D, but WineD3D simply doesn't run the game and the apitrace is like 2kb which probably won't be useful, but I'll leave it anyways. I have tried using latest Proton-GE, I have tried using older Proton-GE, still the same issue and the last working Proton with the game is 5.13-6 and requires to be ran through terminal konsole -e %command%. Trying to use a dxvk.conf file with dxgi.deferSurface or d3d9.deferSurface doesn't help either.

### Software information
Name of the game, settings used etc.
Super Mecha Champions - Steam Game (AppID: 1368910)

### System information
- GPU:RTX 3070
- Driver:470.57.02
- Wine version: 5.13(for valve's Proton), 6.9/6.12/6.13/6.14(all of Proton GE's versions that I've tried)
- DXVK version: v1.7-8-g51531e4a7 (for valve's Proton), latest for Proton GE

### Apitrace file(s)
- https://drive.google.com/file/d/12D5ZxC6TxGuwQPnzLLwtLW0TAhKChmTs/view?usp=sharing

### Log files
- d3d9.log:
[client_d3d9.log](https://github.com/doitsujin/dxvk/files/6915550/client_d3d9.log)

- d3d11.log:
[client_d3d11.log](https://github.com/doitsujin/dxvk/files/6915553/client_d3d11.log)

- dxgi.log:
[client_dxgi.log](https://github.com/doitsujin/dxvk/files/6915557/client_dxgi.log)

I also found some rendering logs, which I'll upload as well:
[render_d3d11.log](https://github.com/doitsujin/dxvk/files/6915560/render_d3d11.log)
[render_dxgi.log](https://github.com/doitsujin/dxvk/files/6915561/render_dxgi.log)

**Comment by doitsujin** [comment]
How do I run the game? It instantly closes on my end even with wined3d.

**Comment by kodatarule** [comment]
> How do I run the game? It instantly closes on my end even with wined3d.

For Proton 5.0-10/5.13-6 you can use this command - PROTON_USE_WINED3D=1 konsole -e %command%.
For 6.3-5 sadly the launcher doesn't work. The Apitrace was recorded with Proton GE 6.14, because it was the only one able to record apitrace everything else instantly crashed for whatever reason.

**Comment by doitsujin** [comment]
Ok, got it to work, but yeah, it randomly hangs. Unfortunately I do not know how to debug such issues further since it doesn't appear to hang in DXVK code.

**Comment by spalius** [comment]
If this requires Shared Resources, it probably won't work, since support for Shared Resources isn't there yet.

**Comment by doitsujin** [comment]
i think that's just a helper process that runs a CEF instance or something. wined3d doesn't fully support those either afaik.

**Comment by kodatarule** [comment]
It could be, because from what I've seen the game starts with the Client.exe and then transitions to Render.exe which most of the time fails while the launcher works. Might try to get another log in a bit of both client and render.
