### ISSUE TITLE
Batman Arkham Knight : lighting issue ?

### ISSUE THREAD

**Issue by 4ymen** [doitsujin/dxvk#221]
Hello,
so in Batman Arkham Knight there is an issue with lighting effect ??? First seconds of [this video](https://youtu.be/jyU7QhH1PQ0) showcase the problem. You can see it even in the benchmark mode of the game at the early stage and on different scenes([video link](https://youtu.be/NqF6sbKIPyA)). I managed to get in the benchmark mode with apitrace (trace about 15% of the benchmark) and exit the game without crashes.
Hope it helps.

### Software information
Batman Akham Knight on SSD.
All settings to normal, nvidia gameworks, AA and post-processing effects OFF

### System information
- GPU: Nvidia GTX 970
- Driver: 391.01
- OS: Windows 10 Pro 64 bits
- DXVK version: **057d74e**

### Apitrace file(s)
- benchmark trace: https://drive.google.com/open?id=1D_82dIMqEWnRXfiLqrcvF52gyhISHHYF
- old benchmark crash trace (mb useless): https://drive.google.com/open?id=1qW2wGHAuGOepz2ifmXinFqTjwppQ_7LD

### Log files
- d3d11.log: [BatmanAK_d3d11.log](https://github.com/doitsujin/dxvk/files/1858105/BatmanAK_d3d11.log)
- dxgi.log: [BatmanAK_dxgi.log](https://github.com/doitsujin/dxvk/files/1858108/BatmanAK_dxgi.log)

**Comment by DonHugo69** [comment]
I am experiencing something similar, even though it seems to affect the lightning/reflections on surfaces:
![batman](https://user-images.githubusercontent.com/10484857/38765577-a420dcd4-3fc4-11e8-9ea4-a0ff335a1a9a.png)
The effect can be seen well on the box in the front right and on the tubes on the right, especially if you compare it to @4ymen 's video of the benchmark.

**System information**

- GPU: AMD R290
- Driver: Mesa 18.0
- OS: Arch Linux

```
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
WARNING: radv is not a conformant vulkan implementation, testing use only.
info:  AMD RADV HAWAII (LLVM 6.0.0):
info:    Driver: 18.0.0
info:    Vulkan: 1.0.57
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
WARNING: radv is not a conformant vulkan implementation, testing use only.
info:  AMD RADV HAWAII (LLVM 6.0.0):
info:    Driver: 18.0.0
info:    Vulkan: 1.0.57
info:  D3D11CreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
warn:  Vulkan extension VK_KHR_maintenance2 not supported
info:  Enabled device extensions:
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_maintenance1
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
warn:  D3D11RasterizerState: Depth clamp not properly supported
warn:  D3D11RasterizerState: Depth clamp not properly supported
warn:  DxgiFactory::MakeWindowAssociation: Ignoring flags
info:  DxgiVkPresenter: Recreating swap chain: 
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_FIFO_KHR
  Buffer size:  1920x1080
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
WARNING: radv is not a conformant vulkan implementation, testing use only.
```

**Comment by kgudalov** [comment]
I have exactly the same problem. Can be clearly seen on this screenshot 
![2018-04-30 12-20-36](https://user-images.githubusercontent.com/38583143/39418539-6c1dd136-4c74-11e8-8b0a-ca2e3dc47b43.png)


### System information
- GPU:NVIDIA GTX 1060 6GB
- Driver:369.18 (old compiler)
- Wine version: wine-staging 3.7
- DXVK version: master
### Log files
- d3d11.log:
[BatmanAK_d3d11.log](https://github.com/doitsujin/dxvk/files/1959805/BatmanAK_d3d11.log)

- dxgi.log: 
[BatmanAK_dxgi.log](https://github.com/doitsujin/dxvk/files/1959808/BatmanAK_dxgi.log)

**Comment by 4ymen** [comment]
This specific issue was an nvidia compiler bug. With the new nvidia driver it's fixed on Windows and Linux.
The #335 should be close too.
But 2 bugs remain with this game :(
Detective mode that crash the game but I can't apitrace it + texture streaming quality like other batman games(#347).

PS: I should have closed this issue a few weeks ago :grin:
