### ISSUE TITLE
Final Fantasy XIV: Stuttering on DXVK 1.9 or higher

### ISSUE THREAD

**Issue by vyfvyf** [doitsujin/dxvk#2210]
I am having heavy stutters in Final Fantasy XIV on DXVK 1.9 or higher, master included.
Looks like its happening when game loads player characters. If i go to cities game stutters heavily on load and then having occasional hiccups when new players appear on screen. Outside of that game runs fine.

! However i found out if i reverse [this commit](https://github.com/doitsujin/dxvk/commit/e64a8ee61a0669b317043bb211f1c519bd4c47af) i can run latest DXVK version just fine.

### Software information
Final Fantasy XIV

### System information
- GPU: GTX 1080
- Driver: 470.57.02
- Wine version: 6.3, but this happens on any wine5, wine6 or proton versions
- DXVK version: 1.9, 1.9.1

#### 1.9.1 Release version:
- d3d11.log: [ffxiv_dx11_d3d11.log](https://github.com/doitsujin/dxvk/files/6942068/ffxiv_dx11_d3d11.log)
- dxgi.log: [ffxiv_dx11_d3d11.log](https://github.com/doitsujin/dxvk/files/6942068/ffxiv_dx11_d3d11.log)

#### master with reversed commit:
- d3d11.log: [ffxiv_dx11_d3d11.log](https://github.com/doitsujin/dxvk/files/6942140/ffxiv_dx11_d3d11.log)
- dxgi.log: [ffxiv_dx11_dxgi.log](https://github.com/doitsujin/dxvk/files/6942141/ffxiv_dx11_dxgi.log)

**Comment by doitsujin** [comment]
Can't reproduce, game runs perfectly fine here.

Reverting that commit is obviously not an option because doing so would introrduce a bug, and I don't really see why it would be any worse than 1.8.1 which had the same behaviour.

**Comment by vyfvyf** [comment]
I am not asking to revert commit, just saying that i can run 1.9.1 or master without any stuttering if i revert it myself. Thought that will help.

I am certainly not confusing with shader compile, because i have tried with or without dxvk/GLCache and behavior is always the same:

I can load into crowded area on 1.8.1 with no cache at all, run around and everything will be smooth.

But if try the same on 1.9.1 there will be heavy initial stutters and then like every 5 sec. I can stand there for an hour and there still will be same stutters, so i dont think this is cache related. And areas where is no people around have no stutter at all.

Maybe this is my system issue, but i have no idea at all what can cause this.

**Comment by doitsujin** [comment]
Are you on Wayland or something? We changed some presentation stuff but it hasn't caused issues for anybody as far as I'm aware and like I said, there's no issue on my end.

**Comment by vyfvyf** [comment]
I am on X11, dual monitor setup. I have tried to unplug second monitor, it got a little better but still _**worse**_ than 1.8.1.

**Comment by yuiiio** [comment]
I have a similar problem.
 (gtx1050, 470.57.02 and 470.56.05, not xwayland or prime, directory driven Xorg by nvidia)

```dxgi.maxFrameLatency = 1```
is reduce the stutter.
my system is always 100% gpu bound.

**Comment by vyfvyf** [comment]
Can confirm that `dxgi.maxFrameLatency = 1` helps for me.
Stuttering on entering cities is completely gone, there is still some when just running around, but much less now.

**Comment by taylor85345** [comment]
I've also been having this issue, primarily when running the game with a large number of hi-res texture mods installed. Removing mods mitigates but doesn't entirely eliminate the issue. Both @vyfvyf's patched dxvk and the `dxgi.maxFrameLatency = 1` solution completely resolved the issue for me.

I am running a GTX 1660Ti (Mobile) with 470.57.02 drivers. It is worth mentioning that I was unable to replicate this issue with an identical install and mod deployment on my old gaming rig running an AMD R9 380X, so this may be an Nvidia-specific issue.

**Comment by Ammako** [comment]
The game is borderline unplayable in cities for me, above Standard graphics settings. Turning off SSAO somewhat mitigates this, but not completely, and that isn't ideal when I used to be able to run the game fine on High (Laptop). I fully expect lower framerates in crowded areas, especially with the influx in the game's popularity lately, but the stuttering drops my framerate below 1 for a good 2-5 seconds at a time every few seconds, just by being in the city, not even anywhere near the big crowd.

GTX 1060 (3GB), 470.63.01 drivers, 5.10.56 kernel, running on X11, if that matters. No game mods whatsoever. I'll try the new Proton GE, but how would someone go about applying this frame latency config otherwise?

**Comment by vyfvyf** [comment]
After playing with ```dxgi.maxFrameLatency = 1``` for a few days, i can say that it _helps_, but **does not** completely eliminate issue for me. Cities are much better, but there is still random stutter that can happen even in barren areas.

Best option for me still is to play on dxvk with reversed commit, which runs game flawlessly in any situation.

@Ammako please refer to readme about ```DXVK_CONFIG_FILE``` launch option. If you are on Steam add %command% after.

**Comment by taylor85345** [comment]
@Ammako You just have to create a text file called `dxvk.conf` with the line `dxgi.maxFrameLatency = 1` in the same folder as your ffxiv_dx11.exe executable. Stuttering exists for me, but is virtually unnoticeable without monitoring it on something like mangohud

**Comment by Ammako** [comment]
Yeah, I'm just using new Proton GE that has the fix built-in. I was mostly asking for anyone else who might end up here and would need to know how to apply the fix.

Stuttering is essentially gone now, what little bit of stuttering there might be left isn't noticeable because it only happens at times where the framerate is already unstable anyway.

**Comment by GingerBobRoss** [comment]
Commenting to report that the stutter was indeed an issue with the previous release.
The game ran completely fine before using previous Protons/ DXVK builds, but with ProtonGE 6.14 (Used for the NO Steam 1 command) It became completely unplayable in cities given i had 75-90 fps. 
Raids and everything was smooth.
This fixed everything <3

**Comment by doitsujin** [comment]
Can anyone test if `dxvk.halveNvidiaHVVHeap = True` improves things?

**Comment by Ammako** [comment]
With or without `maxFrameLatency = 1`

**Comment by doitsujin** [comment]
Without.

**Comment by yuiiio** [comment]
thanks, doitsujin for looing this!
I can confirm ```dxvk.halveNvidiaHVVHeap = True``` reduce the stutter.

**Comment by doitsujin** [comment]
Well now I got two conflicting answers with someone on Discord saying that it doesn't solve the problem.

**Comment by yuiiio** [comment]
default-settings  => cause stutter   : (vidmem-heap2) 220MB (91%).
```dxgi.maxFrameLatency = 1```  => reduce stutter : (vidmem-heap2) 160MB (66%).
```dxvk.halveNvidiaHVVHeap = True``` => reduce stutter : (vidmem-heap2) 107MB (43%).

**Comment by doitsujin** [comment]
Interesting, thanks for gathering that data. Frame latency affecting this certainly makes more sense now.

**Comment by Tractix** [comment]
This issue seems to have been fixed for me on the latest nvidia driver 470.62.05 (vulkan dev driver) with RTX 2060 Super.

**Comment by doitsujin** [comment]
Added a workaround, should run better now (although performance may drop a little).

**Comment by BonsaiDen** [comment]
Just wanted to leave a comment I case somebody else finds this, I also ran into the stutter issues with DXVK v1.10.1 but none of the suggestions in this thread fixes the issue for me, in the end I had to set the following two config options which finally fixed the issue for me:

```
dxgi.syncInterval = 0
dxgi.maxFrameRate = 60
```

**Comment by LuxasXIV** [comment]
> RTX 3090, Kernel 5.14, NVIDIA 470.74, Xorg, Gnome, and DXVK latest release (1.9.2):
> 
> https://software.opensuse.org/package/dxvk
> 
> With Lutris installer script, XIV Launcher Wine 6 (6.10) edition.
> 
> I can confirm that it is not shader compiler caching. The stutter is permanent. For some reason it gets worse if I look at the floor of the gold saucer's "Round Square" and run in circles. Then I get a severe amount of stutter.
> 
> I then did the `dxgi.maxFrameLatency = 1` trick and it completely solved the stutters. I can run in circles for days without any stutter. It also reduced the game's input lag. Spinning the camera is noticeably more responsive for some reason...
> 
> I swear, the gameplay feels way more responsive, it went from feeling like syrup (maybe 100ms of latency?) to feeling almost like on Windows.
> 
> I am playing at 4K 60 fps BTW, and it is very smooth after the config tweak... And I realize that the config change disabled the normal "3 frames of buffering" to a single (1) frame of buffering which probably increases load on the graphics card. But it is way smoother than 3 frames of buffering.
> 
> I have not tested `dxvk.halveNvidiaHVVHeap = True` and I am going to bed now, just found this issue on my phone while researching.
> 
> What's the theory? That queueing 3 frames uses too much memory? @doitsujin

Where exactly is the file that needs to be edited? I´d like to try this fix for my stutter

**Comment by Blisto91** [comment]
In a `dxvk.conf` file you need to create yourself next to the exe (or where ever the logs generate).
Note that `dxvk.halveNvidiaHVVHeap` isn't a thing anymore

**Comment by K0bin** [comment]
FWIW that workaround shouldn't be necessary anymore.
