### ISSUE TITLE
Grand Theft Auto IV: Issue with DXVK.

### ISSUE THREAD

**Issue by MatthewPaanoTorres** [doitsujin/dxvk#2229]
Matthew Paano Torres here, when I previously installed DXVK 1.9.1 with the NBPack mod for GTA IV, it worked perfectly fine and I could play the game as normally without any technical issues for Grand Theft Auto IV. However, when I used the same NBPack version along with the latest version of DXVK (1.9.1), the game gave me a black screen and was in windowed mode instead of being fullscreen, same problem applied to DXVK 1.7.3. I used the x32 bit directory with the d3d9.dll and dxgi.dll log files with every version and I was receiving the same problem. So, I am basically forced to use D3D9 (DirectX 9) forever?

DIRECTX 9 LOG (1.7.3):
https://pastebin.com/Gia2hgEq

**Comment by Joshua-Ashton** [comment]
`v1.7.3-async` we don't support async builds.

**Comment by MatthewPaanoTorres** [comment]
Oops. Wrong file!
Oh yeah, I previously tested with the non-async builds and they happen as well.

**Comment by K0bin** [comment]
We need an apitrace with NBPack installed anyway.

**Comment by Blisto91** [comment]
@MatthewPaanoTorres Friendly ping

**Comment by K0bin** [comment]
Closing because of a lack of feedback.
