### ISSUE TITLE
I don't know what is the problem here this is GTAIV_d3d9.log file

### ISSUE THREAD

**Issue by ezzfarrag40** [doitsujin/dxvk#2232]
info:  Game: GTAIV.exe
info:  DXVK: v1.7.1
info:  Found built-in config:
info:  Effective configuration:
info:    d3d9.customVendorId = 1002
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface

**Comment by Joshua-Ashton** [comment]
Nor do I.

**Comment by K0bin** [comment]
There is no problem with that log you posted.
