### ISSUE TITLE
[d3d9] Guild Wars 2: glitches in some elements of Waypoints

### ISSUE THREAD

**Issue by Iglu47** [doitsujin/dxvk#2236]
The rotating element under the waypoints (teleportation points) is shifted to the side (possibly only to the right) when the camera rotates.

https://user-images.githubusercontent.com/25866099/129045823-57485a17-8a2e-4bbb-8c30-f0dd6c0e2f1f.mp4

(Looks like a projection from above, which is displayed on the ground or on the plane on which the characters move.
The character stands where the center of rotation of this element should be.)

Bisecting test give me that first bad commit is [`5e48035`](https://github.com/doitsujin/dxvk/commits/5e48035e992d52c9862b2d2ef5ac1e92112cde90)
Revert `5e48035e992d52c9862b2d2ef5ac1e92112cde90` on today [`master`](https://github.com/doitsujin/dxvk/commits/7acbd0f4e1a140c00fad20cafdfb13d0cb592991) happens without conflicts and helps also.

### Software information
Guild Wars 2 (64-bit client version) (official site: https://account.arena.net/welcome)
build: 118189

<details><summary>game grafical settings</summary>
<p>

![gw2-settings](https://user-images.githubusercontent.com/25866099/129045402-cdf8f277-30b0-4d7c-ab1a-8f9b7988fe60.png)

</p>
</details>

### System information
- GPU: Nvidia GTX 1080 Ti
- Driver: 470.63.01 (proprietary)
- Wine version: Wine-Staging-6.14 (with some TkG-patches)
- DXVK version: 7acbd0f4e1a140c00fad20cafdfb13d0cb592991 (binary build provided by https://github.com/doitsujin/dxvk/actions/runs/1119904150)

### Apitrace file(s)
- DXVK on Wine: https://drive.google.com/file/d/1IIDzXWICfejgWo-xIShRZbs14MG_HL8p/view?usp=sharing

### Log files
- d3d9.log: [Gw2-64_d3d9.log](https://github.com/doitsujin/dxvk/files/6969075/Gw2-64_d3d9.log)

**Comment by Berobad** [comment]
Same on RADV.

And it's not only waypoint, it's every aoe circle of the game

**Comment by logan001** [comment]
it seems that the center of the circle is somehow on the exterior of the circle. usually mouse is in the center of the circle but now i get the mouse on the edge of the circle. also if you move the camera the circle on the ground starts shaking (noticed on golem II bullet marks and also in auric basin meta with plant circle)

**Comment by Joshua-Ashton** [comment]
Any other traces? I can't repro with that one.

**Comment by Iglu47** [comment]
@Joshua-Ashton thanks, I checked on the fresh build that contain this commit (https://github.com/doitsujin/dxvk/actions/runs/1136486769)
The initial described issue is gone. 🎉
