### ISSUE TITLE
Witcher 3 crashes

### ISSUE THREAD

**Issue by Tebeas** [doitsujin/dxvk#2238]
Well there is not much to add, every time I try to open the Witcher 3, it crashes on start.

### Software information
Witcher 3
Everything is on ultra with a bunch of mods, most notably W3EE.

### System information
- GPU: RTX 2060
- Driver: 471.68
- Wine version:  None, using Cuckdowns 10
- DXVK version: 1.9.1 

### Apitrace file(s)
None, will add if needed.

### Log files
[witcher3_d3d11.log](https://github.com/doitsujin/dxvk/files/6971902/witcher3_d3d11.log)
[witcher3_dxgi.log](https://github.com/doitsujin/dxvk/files/6971903/witcher3_dxgi.log)

I should add, that this is the only game that crashes, and everything Vulkan related seems to be fine, layers don't over lay.

**Comment by doitsujin** [comment]
Witcher 3 is known to work fine for pretty much everyone else so this is probably some problem on your end. We cannot provide support for issues specific to individual Windows setups.
