### ISSUE TITLE
Tekken 7: No aiming arrow in Ultimate Tekken Bowling

### ISSUE THREAD

**Issue by TiZ-EX1** [doitsujin/dxvk#224]
Hello! I really appreciate the work you're doing here. I'm looking forward to someday being able to play Tekken 7 without booting my spare Windows partition. There are a few issues with it but I figured I'd start with this one since a fix for it will probably help other games.

The aiming arrow does not appear in Ultimate Tekken Bowling. Another effect that is missing are these streak things that go through the air in fever mode, after getting a strike. The arrow actually doesn't appear in wined3d either. I did record two videos: Here's [one in DXVK.](https://www.youtube.com/watch?v=9x4dnjRT9sA) And here's [another in wined3d.](https://www.youtube.com/watch?v=rCyuGiO2w1I) Here is [what it's supposed to look like.](https://www.youtube.com/watch?v=yKU40QuJxuY)

If it's any relevance, Tekken 7 is an Unreal Engine 4 game. My pockets aren't deep enough to provide a copy of Tekken 7 for testing while it's not on sale, but I'll happily buy you or anyone else the bowling DLC.

It's the least I can do for a really incompetent initial issue report. I'm not sure how to generate the apitrace for this particular program, because it's 64-bit, but Steam has to be running for it to start, and Steam is 32-bit. If I try to start either of the game executables, it starts Steam first, which seems to cause apitrace to not work. I can't run 64-bit apitrace on Steam; it fails immediately. I haven't tried running 32-bit apitrace because I feel like it would fail as soon as it gets to Tekken. I'll happily generate it with some guidance on how to proceed. I'd also be willing to generate it from Windows if you think it'd be more helpful made from there.

I also don't have the log files... I don't know where they are. They're not in Tekken 7's install directory. They're not in the directory where its actual binary is. They're not anywhere inside the prefix. My wine prefixes are kind of sandboxed; they only have access to their own drive_c and a select few folders inside of HOME, so I think that because my current directory was somewhere that the prefix couldn't access, it just didn't write any. I must apologize for being so incompetent on this, but I wanted to go ahead and open the issue anyways to ask how to proceed apitrace-wise since I don't know what to do there anyways.

### Software information
Tekken 7. Initially run in "Medium" preset, which has 70% rendering scale, most settings at medium. Run again on "Ultra", which is 100% scale, everything on ultra or high.

### System information
- GPU: GeForce GTX 1060
- Driver: Nvidia 390.48
- Wine version: Staging 3.4
- DXVK version: Last tested on ae88f83

### Apitrace file(s)
- [Wine, crash at character select](https://drive.google.com/open?id=1MDAIDyC2AK2n4JAfk8p-cL2e99VVYawp)
- [Windows](https://drive.google.com/open?id=1lRZFJ_I9YOThjzqLzL3HReNkKSJsfKkD)

### Log files
- [d3d11.log](http://paste.ubuntu.com/p/ymWtfrfpG7/)
- [dxgi.log](http://paste.ubuntu.com/p/P5b59Gy4cD/)

**Comment by doitsujin** [comment]
The log files are located in the working directory of the game, which is *usually* the same as the directory where the binaries are located, but this game is apparently an exception. You can try to locate them however, if the name of the executable is `game.exe` then the name of the d3d11 log file will be `game_d3d11.log`. If all else fails, you can just dump the command line output to a file.

As for the apitrace, either try to start the game from the command line while Steam is already running (this works for a small number of games), or set the launch options inside steam to ``C:\full\path\to\apitrace.exe trace -a dxgi %command%` for that game.

**Comment by TiZ-EX1** [comment]
I've added the logs and apitraces. Using launch options is what worked for me. I couldn't get a full trace from Wine because it was crashing at the character select screen. I did remember to switch dxgi and d3d11 to builtin for it. I've added that trace anyways. Then I rebooted to Windows and got a full trace there.

**Comment by TiZ-EX1** [comment]
bd17be4 fixes this issue for me!

I have a couple more issues to get through before I can actually use my laptop for competitive casuals, and I'll be creating issue reports for them later when I have time to do the apitraces.

Thank you very much!

**Comment by doitsujin** [comment]
Interesting, thanks for reporting back.
