### ISSUE TITLE
Unreal Engine 4.2x support

### ISSUE THREAD

**Issue by Kein** [doitsujin/dxvk#2245]
It looks like UE4 D3D11RHI implementation really does not like DXVK in any capacity. Attempt to launch leads to crash with error message saying swapchain creation failed. **Host OS:** Windows 10x64

The log isnt very useful and suggested **apitrace** does not work for me properly, however I can do better, I've built a small starter-pack template Puzzle game that can be used to repro the issue 100%:

https://www.dropbox.com/s/9bz44glh3wvkmna/WindowsNoEditor.7z?dl=1

DXVK already "installed" via "d3d11.dll", it is inside `.\Engine\Binaries\Win64\`

***Alternatively***, this can be reproduced by installing any UE 4.2x version, creating new started project either "FPS Template" or whatever, and building it/packaging for Windows.

**Comment by K0bin** [comment]
Why are you trying to run the UE4 editor with DXVK on Windows?

> DXVK already "installed" via "d3d11.dll", it is inside .\Engine\Binaries\Win64\

You also need dxgi.dll. Otherwise it'll crash.

**Comment by Kein** [comment]
Oh my bad, this wasnt obvious.
