### ISSUE TITLE
Secret World Legends: D3D11DeviceContext: CopySubresourceRegion: Mismatched Resource types

### ISSUE THREAD

**Issue by farmboy0** [doitsujin/dxvk#225]
The game runs very slow.

### Software information
Secret World Legends, DirectX 11 mode
Wine 3.4
Mesa 18.0
LLVM 6

### System information
- GPU: R9 380X
- Driver: RADV
- Wine version: 3.4
- DXVK version: https://haagch.frickel.club/files/dxvk/r862.6babc22/32

### Apitrace file(s)
- Not working on vanilla wine

### Log files
- d3d11.log: [SecretWorldLegendsDX11_d3d11.log](https://github.com/doitsujin/dxvk/files/1861423/SecretWorldLegendsDX11_d3d11.log)

- dxgi.log: [SecretWorldLegendsDX11_dxgi.log](https://github.com/doitsujin/dxvk/files/1861424/SecretWorldLegendsDX11_dxgi.log)

**Comment by farmboy0** [comment]
Should i add an apitrace with DXVK since it basicly runs even if very slow?

**Comment by doitsujin** [comment]
A DXVK apitrace would help, yes.

**Comment by farmboy0** [comment]
Unfortunately TSW will reproducibly crash when being run with apitrace.
The only other thing I can offer is the logs with log level debug:
[SecretWorldLegendsDX11_d3d11.log](https://github.com/doitsujin/dxvk/files/1908656/SecretWorldLegendsDX11_d3d11.log)

**Comment by doitsujin** [comment]
Damn. Guess I'll have to add some more debug output to the D3D11 stuff so that we can get at least some idea what's going on.

**Comment by doitsujin** [comment]
Please try with a6767ebd5263247dae5b9983e8750f5ede94575d and post new logs.

**Comment by farmboy0** [comment]
[SecretWorldLegendsDX11_d3d11.log](https://github.com/doitsujin/dxvk/files/1910386/SecretWorldLegendsDX11_d3d11.log)

**Comment by doitsujin** [comment]
Thanks. Looks like in D3D11 you can copy data between 2D and 3D images, I'll have to figure out whether that is possible in Vulkan.

**Comment by doitsujin** [comment]
Should be fixed as of fcdba67b88fc17f5d9e44efb97973a0dd56e40c9. Please let me know if there are still issues.

**Comment by StBoom** [comment]
Hello doitsujin,

short feedback on the topic: After linking the two dlls into the games folder, the game also runs in DX11.
I didn't notice any bugs in the quick check.

Do you need more information?

Great Work!
Greetings StBoom
