### ISSUE TITLE
Sine Mora EX (606730) - Too fast above 60 fps

### ISSUE THREAD

**Issue by kturques** [doitsujin/dxvk#2257]
### Software information

Game: Sine Mora EX (606730)

The game runs too fast when above 60 fps. Seems like the fps affects the game engine speed.

On my PC, by default the game runs uncapped above 60 fps.

DXVK_FRAME_RATE=60 fix this issue.

### System information
- GPU: AMD Radeon RX 5700XT
- Driver: Mesa 21.1.6
- Wine version: Proton 6.3-6
- DXVK version: 1.9.1

UPDATE:
> Exclusive fullscreen forces 60Hz refresh rate. Software cap is automatically applied if the game detects frame rates higher than 60 FPS. If the game is too fast, cap the frame rate or enable software cap in game manually by changing software_sync=0 to 1 in configuration file.  Vertical sync (Vsync) is forced on by default. Used as frame rate cap.
SOURCE: https://www.pcgamingwiki.com/wiki/Sine_Mora_EX#Run_the_game_at_screen_refresh_rate

Should be auto locked at 60, but that part is not working.
My monitor is 144hz

**Comment by doitsujin** [comment]
Please post logs so that we can actually add an app profile for this.

**Comment by kturques** [comment]
Proton Log: [steam-606730.log](https://github.com/doitsujin/dxvk/files/7033285/steam-606730.log)
