### ISSUE TITLE
Resident Evil 5 stutters/freezes with dxvk

### ISSUE THREAD

**Issue by NikoBellicRU** [doitsujin/dxvk#2266]
The game stutters / freezes a lot with dxvk but with wined3d it's very acceptable / playable.

I recorded 2 videos with both dxvk and wined3d, i also forgot to enable the graph but it's very noticeable without it still.

DXVK
https://www.youtube.com/watch?v=b9mkGL_YN28

WINED3D
https://www.youtube.com/watch?v=hC1CLy4uidQ

I deleted the steam shader cache in between tests.

### Software information

RESIDENT EVIL EVIL 5, game settings are maxed, HIGH / 8X AA / 1920x1080

### System information
- GPU: RX 570 8GB
- Driver: 21.2.1-1
- Wine version: Proton experimental, same issue with others
- DXVK version: 1.9.1

### Apitrace file(s)
- https://mega.nz/file/VBRWGbIZ#qGRuQdT1rrTZpOMvy00x7WzimnsvfaHtJsO4iasppvE

### Log files
- d3d9.log:  [re5dx9_d3d9.log](https://github.com/doitsujin/dxvk/files/7072788/re5dx9_d3d9.log)

**Comment by kattjevfel** [comment]
Looks to me like it's compiling shaders

**Comment by NikoBellicRU** [comment]
> Looks to me like it's compiling shaders

But is it normal to freeze this much compiling with dxvk but not on wined3d?

**Comment by K0bin** [comment]
Yes, that's normal. If you think there's something wrong then please provide the necessary apitrace.

**Comment by NikoBellicRU** [comment]
> Yes, that's normal. If you think there's something wrong then please provide the necessary apitrace.

I just think its wierd the way it acts on dxvk, in wined3d it stutters just a bit in the begining and then the game is fully playable mostly but with dxvk it just keeps freezing a lot on each map i go to, so maybe something is not right?

Here's the trace
https://mega.nz/file/VBRWGbIZ#qGRuQdT1rrTZpOMvy00x7WzimnsvfaHtJsO4iasppvE

**Comment by K0bin** [comment]
Same problem as #2084 and #2453.

**Comment by JavaDaVinci** [comment]
I have the same issue in 2025 with latest proton GE 9-22. I am experiencing severe stuttering during gameplay in Resident Evil 5. Interestingly, the benchmark doesn’t show any of these issues. It only happens during actual gameplay. The stuttering is so bad in co-op that it even causes players to get kicked from my session. I think some kind of regression happened.

**Comment by Blisto91** [comment]
@JavaDaVinci Do you mean from the start or after having played for a while?

**Comment by K0bin** [comment]
Additionally: 

- Is it limited to specific game modes or levels? I just test the start of the game which is mostly annoying QTEs.
- Operating System
- Wine version
- Hardware? (Especially the GPU)
- GPU driver version
- Do you have the game on Steam or anywhere else?
- How do official Proton versions fare?
