### ISSUE TITLE
dxvk above 1.6.1 don't work with GPU: NVIDIA GeForce GTX 660

### ISSUE THREAD

**Issue by edvejak** [doitsujin/dxvk#2267]
Hi. dxvk above 1.6.1 don't work with GPU: NVIDIA GeForce GTX 660/PCIe/SSE2 
I have trouble with gta v: https://github.com/ValveSoftware/Proton/issues/37#issuecomment-907627410

**Comment by K0bin** [comment]
Please provide logs, the apitrace, screenshots, your driver and Wine version.

**Comment by edvejak** [comment]
ValveSoftware/Proton#37 (comment)

**Comment by gabriele2000** [comment]
Latest driver 470.63.01 breaks gpu "favourite" selection somehow, games will launch with integrated GPU instead of Nvidia GPU, DX11 games however, works fine, with Nvidia GPU

**Comment by Blisto91** [comment]
@edvejak Did you manage to resolve this issue?
