### ISSUE TITLE
Driver San Francisco runtime error on Windows 8

### ISSUE THREAD

**Issue by nikita-stepan0v** [doitsujin/dxvk#2275]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
Preferably record the trace on Windows, or wined3d if possible.

**Reports with no log files will be ignored.**

### Software information
Driver San Francisco

### System information
- GPU: GTX 750
- Driver: 391
- DXVK version: 1.91

### Log files
- d3d9.log: [Driver_d3d9.log](https://github.com/doitsujin/dxvk/files/7103635/Driver_d3d9.log)
- ![Безымянный](https://user-images.githubusercontent.com/90024150/131958204-d7fdb21b-283e-41fa-a420-0cd86b4c1354.png)

**Comment by nikita-stepan0v** [comment]
![Безымянный](https://user-images.githubusercontent.com/90024150/131958204-d7fdb21b-283e-41fa-a420-0cd86b4c1354.png)

**Comment by K0bin** [comment]
Please provide an apitrace. Also update your graphics driver, the one you have installed is ancient.

**Comment by doitsujin** [comment]
We cannot support Windows 8.
