### ISSUE TITLE
Pathfinder: Wrath of the Righteous abnormally poor performance

### ISSUE THREAD

**Issue by jebevassve** [doitsujin/dxvk#2276]
Game: Pathfinder: Wrath of the Righteous

Unusually poor performance or GPU underutilization most of the time (FPS hovering at around 10-15), DXVK HUD/MangoHUD both reporting 100% GPU utilization, GPU temperatures suggest that is not the case. Another user on Steam with the same GPU has reported identical behavior.
**However sometimes when launched the game performs as it should (FPS is a stable 60 throughout)**, I have been trying to reliably replicate this for the past day with no success.
With WineD3D the game performs as it should (hovers at around 40-50 FPS on average), but the game crashes on the first loading screen after the main menu.
I have attached d3d11.log files for both properly and poorly performing P:WotR, a dxgi.log file and an Apitrace .trace, which like WineD3D crashed on the first loading screen after the main menu.

### System information
- OS: Kubuntu 20.04
- GPU: Nvidia GTX 1050 2GB
- CPU: AMD Ryzen 3 1200 (4) @ 3.700GHz
- RAM: 8GB DDR4 @ CL15 2666
- Driver: 460.91.03
- Wine version: Tested with Wine Staging 6.16 / Lutris Wine 6.13, 6.14, 6.0 / Proton Experimental, 6.3-6 / Proton GE 6.16, 6.13, 6.8
- DXVK version: Mostly 1.9.1, earlier versions bundled with Lutris Wine, Proton & GE exhibit identical behavior.

### Apitrace file(s)
- https://mega.nz/file/n44wQAwQ#iL3yBw8t4MFKrZ2xUDn0dpZV5kQmhVZCTLCKnci85eQ

### Log files
- d3d11.log (Proper performance): [Wrath_d3d11.log](https://github.com/doitsujin/dxvk/files/7105711/Wrath_d3d11.log)
- d3d11.log (Poor performance): [Wrath_d3d11.log](https://github.com/doitsujin/dxvk/files/7105717/Wrath_d3d11.log)
- dxgi.log(File is identical for proper/poor performance): [Wrath_dxgi.log](https://github.com/doitsujin/dxvk/files/7105735/Wrath_dxgi.log)

**Comment by doitsujin** [comment]
2GB of VRAM is not enough to run this game on DXVK, when replaying the trace I already see usage go up to 2.4GB. This is especially problematic on Nvidia where `VK_EXT_memory_priority` is not supported and the game cannot use video memory that's already in use by background processes.

**Comment by jebevassve** [comment]
Thank you for the swift response!
I suppose I'll likely have to play it on Windows then, though I still find it odd that when it works it works perfectly, with 2GB VRAM on the GPU and all.

**Comment by K0bin** [comment]
> I still find it odd that when it works it works perfectly, with 2GB VRAM on the GPU and all.

Nvidias Windows D3D11 driver actually has memory management unlike DXVK (doubly so on the Nvidia Linux Vulkan driver).
