### ISSUE TITLE
[D3D11] World of Warcraft sporadic shader flicker

### ISSUE THREAD

**Issue by insunaa** [doitsujin/dxvk#2277]
Using the latest master after some time shadow related shaders are starting to flicker (for a single frame shadows are drawn wrong and the next frame they're drawn correctly again).

When trying to apitrace the game crashes with an access violation before it even gets to rendering, so I can't provide an apitrace unfortunately.

https://www.youtube.com/watch?v=pMusCvBGdQw
this shows the issue in question

Sometimes liquid textures become flat colors for a while and then later turn back to textured surfaces (the texture just fades away to solid and after a minute or two slowly fades back to correctly textured)
![image](https://user-images.githubusercontent.com/3718129/132024127-6ad50713-ca26-49b0-86de-b384bdd71bb8.png)

Correctly textured:
![2021-09-03_17-24](https://user-images.githubusercontent.com/3718129/132029734-33eb8676-7d7d-4578-a65c-a154b8786a06.png)

The screenshots were taken at different angles/distances to show that it really is a solid color, the effect is persistent to angle changes, distance changes and off-screen-culling

Using VKD3D and running the game in dx12 mode, none of these issues are present.

### Software information
Name of the game, settings used etc.

WoWClassic.exe version 2.5.2
any settings
(my current settings are every graphical setting at maximum except liquid detail which is one below maximum)
Resolution is 2560x1440
and the game runs vsynced to 120hz

### System information
- GPU: NVIDIA GeForce RTX 3080
- Driver: 470.56.5
- Wine version: wine-6.16.r2.g4b48df50 ( TkG Staging Esync Fsync Vkd3d DXVK-Compatible )
- DXVK version: v1.9.1-92-g69588b02+

Edit: Confirmed that the issue also occurs on f0e9700f

### Apitrace file(s)
- Game crashed before rendering anything
Tho I do have a 100mb apitrace file, no idea how useful that would be tho

### Log files
[WoWClassic_dxvk_dxgi_logs.zip](https://github.com/doitsujin/dxvk/files/7107010/WoWClassic_dxvk_dxgi_logs.zip)
The logs were taken such that both issues occurred during the logging. First I was at the place where the flickering issue is very prominent, the same place as seen in the video.
Then I re-logged to a character that has the liquid in view. At first the liquid was fully textured and slowly faded into the flat color (same area as seen in the screenshots above)
I quit the game immediately after the liquid texture had fully turned to a solid color.

**Comment by doitsujin** [comment]
Can't debug this with out a trace, I'm afraid. If D3D12 works better, just use that.

**Comment by insunaa** [comment]
D3D12 is less performant and for some reason I can't select D3D12 with newer versions of wine
Wine Version 6.0:
```
9/3 18:47:01.708  Adapter 0: "NVIDIA GeForce RTX 3080" family:Unknown type:Unknown vendor:0x10de device:0x2206 driver(0xffffffffffffffff) location:0 dx11:true dx12:true
9/3 18:47:01.708  	Monitor 0 "Generic Non-PnP Monitor" Size(2560x1440) Pos(0, 0)
9/3 18:47:01.708  	Monitor 1 "Generic Non-PnP Monitor" Size(1920x1080) Pos(2560, 360)
```
Wine Version 6.16:
```
9/3 18:40:05.663  Adapter 0: "NVIDIA GeForce RTX 3080" family:Unknown type:Unknown vendor:0x10de device:0x2206 driver(0xffffffffffffffff) location:0 dx11:true dx12:false
9/3 18:40:05.663  	Monitor 0 "Generic Non-PnP Monitor" Size(2560x1440) Pos(0, 0)
9/3 18:40:05.663  	Monitor 1 "Generic Non-PnP Monitor" Size(1920x1080) Pos(2560, 360)
```

I'll try again with the apitrace, but I'm pretty sure the program will just die again

**Comment by doitsujin** [comment]
The whole point of an apitrace is to record what the game does so that replaying it on DXVK triggers the bug. Then again, apitrace is super buggy with multithreaded renderers so it might not work correctly.

Speaking of, does WOW still have the "D3D11 Legacy" render path? Might be worth trying that.

**Comment by insunaa** [comment]
It does and I'll try thank you!
Sorry, I misunderstood what apitraces are for. I'll try to get you one asap!

**Comment by insunaa** [comment]
OK, I'm getting an apitrace made today, a friend has offered to make one for me.
In the meantime: I can force the exact same shader-flicker issue to also occur on vkd3d-proton if I set the config `force_static_cbv`.
Without that it doesn't occur on vkd3d-proton at all

**Comment by insunaa** [comment]
Closing the issue due to reproducibility issues. I'll re-open if I can confirm more parts of this.
