### ISSUE TITLE
When i try to build dxvk i get an error "‘std::cv_status’ has not been declared"

### ISSUE THREAD

**Issue by DNRAWW** [doitsujin/dxvk#2279]
When i run ./package-release.sh master /home/dnraww/.wine/dxvk --no-package this error happens
### System information
- GPU: Nvidia GTX 1650
- Driver: nvidia-driver-470.57.02
- Wine version: 6.0.1
- DXVK version: latest

### Error
https://pastebin.com/Qze5tQ1s

**Comment by DadSchoorse** [comment]
This is probably https://github.com/doitsujin/dxvk#troubleshooting just with a different error message since dxvk doesn't use `std::mutex` anymore.

**Comment by DNRAWW** [comment]
This is it! Thanks!

**Comment by DNRAWW** [comment]
But now there is another issue...

https://pastebin.com/xHPp6n8c

**Comment by DadSchoorse** [comment]
Your mingw-w64 headers are too old, dxvk requires version 8 or higher.

**Comment by DNRAWW** [comment]
I just tried `sudo apt install dxvk`, should've done that first i guees :)

**Comment by K0bin** [comment]
> I just tried sudo apt install dxvk, should've done that first i guess :)

Or preferably use the official DXVK releases here on GitHub and the setup script. Your distro is probably shipping an outdated version of DXVK.
