### ISSUE TITLE
World of Warcraft (TBC Classic) - performance issue

### ISSUE THREAD

**Issue by sfjuocekr** [doitsujin/dxvk#2280]
I have found a specific spot in the game world where there is a 50% performance decrease observed when changing a single setting inside the game.

This does not happen on Windows, the DXVK version used is irrelevant.

Here is a video showing the location and method to reproduce this:

https://www.youtube.com/watch?v=QRXRTnNUs_0&ab_channel=SjoervanderPloeg

I also observe a crash at the gates of Karazhan with 1.9.1, any version before that works fine. This evening we will raid it again, Ill open another issue with logs for that crash.

**Comment by K0bin** [comment]
Hardware? And please make an apitrace of that spot.

**Comment by sfjuocekr** [comment]
Working on it, but getting in-game with apitrace enabled is nearly impossible!

[WoWClassic_d3d11.log](https://github.com/doitsujin/dxvk/files/7128779/WoWClassic_d3d11.log)
[WoWClassic_dxgi.log](https://github.com/doitsujin/dxvk/files/7128780/WoWClassic_dxgi.log)

I have a GTX970, 32GB RAM and an AMD R5 3600.

**Comment by K0bin** [comment]
We can't look into this without an apitrace.

**Comment by sfjuocekr** [comment]
http://downloads.sjoer.org/WoWClassic.trace.tar.gz

**Comment by doitsujin** [comment]
It's normal for DXVK to have different performance behaviour compared to Nvidia, there is no issue here.

As for the crash, you'll need to record a trace on Windows for us to be able to debug that.

**Comment by doitsujin** [comment]
Ok, someone reuploaded the trace on a site that I can actually access and it's broken. You need to copy `d3d11.dll`, `dxgi.dll` **and** `dxgitrace.dll` from the apitrace directory next to the game, just d3d11 isn't enough.

**Comment by sfjuocekr** [comment]
Sorry, my server suffered a full disk I had to take it down to increase the disk space :(

I did have those three files copied over into the game folder. I got them from here: https://github.com/apitrace/apitrace

I can tell you I am not CPU bound, my VRAM is only utilized at 21% there and GPU utilization is at 100% due to VSYNC being off. I can even put everything to low, then set liquid details to ultra and have 250ish FPS. Move the camera just tad to the right and it drops to sub 60 FPS. In contrast to every other zone with "liquid" in it, like Zangarmarsh, Hellfire Peninsula is the only place where this performance decrease occurs.

**Comment by sfjuocekr** [comment]
![Screenshot_20210908_225426](https://user-images.githubusercontent.com/398018/132584276-e9a286e5-adca-4b8f-bb18-709f3465460f.png)
![Screenshot_20210908_225459](https://user-images.githubusercontent.com/398018/132584290-ce869b9e-5fcb-4e81-a754-55ecd2051413.png)

I just think it is a pretty big discrepancy, I put the three files into the game folder again and will make another trace for you.

**Comment by sfjuocekr** [comment]
http://downloads.sjoer.org/WoWClassic-new.trace.tar.gz

**Comment by doitsujin** [comment]
Same problem, it's missing all the DXGI calls. If this was done on Windows then there's a chance that the game simply does not load the DXGI DLL from the game's directory, in which case we're basically just screwed.

**Comment by sfjuocekr** [comment]
Ah ok, so I need to make the apitrace on Windows?

I do not have a Windows install.

**Comment by Blisto91** [comment]
@sfjuocekr Friendly ping. Is this still an issue with latest dxvk and drivers? :slightly_smiling_face:

**Comment by sfjuocekr** [comment]
I have not flown past the place recently, but I will have a look!

Also have a working Windows installation now where I could make an apitrace if needed!

**Comment by Blisto91** [comment]
Sounds good! And ye that would be great 🙂

**Comment by sfjuocekr** [comment]
The FPS drop is less profound now, it maybe goes from 300 to 150. But, previously I had the 3060 and now I have the 3080.

Will give it a go on Windows today or tomorrow to see what the behavior is there.

**Comment by Blisto91** [comment]
@sfjuocekr Sorry for pinging again. Did you get to check this on native windows? 🙂

**Comment by sfjuocekr** [comment]
Sorry, completely forgot to check!

Ill do it right now, got to reboot anyway!

**Comment by Blisto91** [comment]
It sounds like it's the game doing it then.
But sure a trace would be nice to verify anything doesn't stick out.

**Comment by Blisto91** [comment]
@sfjuocekr Friendly ping :grin:

**Comment by Blisto91** [comment]
@sfjuocekr Innocent ping pong hello 👋

**Comment by sfjuocekr** [comment]
I'm god awful when it comes to booting to Windows to run some tests as I usually just want to get out asap before I get suckered into yet another Edge/Office advertisement.

There is a reboot on my agenda for nvme firmware, I'll try to not forget about us <3

**Comment by sfjuocekr** [comment]
http://downloads.sjoer.org/apitrace/WowClassic.zip

There you go, bit late <3
