### ISSUE TITLE
GTA Vice city & San Andreas transparency issues on cars (windows 10) 

### ISSUE THREAD

**Issue by Mrblubb** [doitsujin/dxvk#2283]
The games have weird pixelated glass bug on cars which flickers when moving the mouse. Especially noticeable on infernus in vice city and taxi on san andreas. Could be possible on other cars as well. Running without dxvk fixes the issue. 

DXVK with & without Async have the same issue.

Running both games with skygfx, project2dfx mod on Windows 10 with NVIDIA driver 471.41. 

With SA when rendering pipeline is used neo in skygfx, the issue is gone (probably due to different reflection shader) but always happen in VC on every reflection setting. 

Also turning off MSAA doesn't fix the issue.

### Screenshots
-San Andreas

![Grand Theft Auto  San Andreas Screenshot 2021 09 09 - 19 50 12 63](https://user-images.githubusercontent.com/88938655/132706908-9e307ed8-6e31-44ba-8f79-c2c6a7a288c1.png)
![Grand Theft Auto  San Andreas Screenshot 2021 09 09 - 19 51 00 22](https://user-images.githubusercontent.com/88938655/132706916-b9b2fc52-a609-49b8-89e2-665751107363.png)

-Vice City

![Grand Theft Auto Vice City Screenshot 2021 09 09 - 19 43 57 78](https://user-images.githubusercontent.com/88938655/132707075-2c85a791-18e9-4842-a668-f75cc6cb64ad.png)

### Software information
GTA San Andreas/Vice City, MAX settings, SKYGFX, Project2DFX, 4X AA / 1920x1080

### System information
- GPU: GTX 1060 6GB
- Driver: 471.41
- Wine version: None
- DXVK version: 1.9.1/ 1.9.1 Async Patched (latest releases)

### Apitrace file(s)
- (Not available)

### Log files
GTA SA
- d3d9.log: 
[gta_sa_d3d9.log](https://github.com/doitsujin/dxvk/files/7137531/gta_sa_d3d9.log)

GTA VC
- d3d9.log: 
[gta-vc_d3d9.log](https://github.com/doitsujin/dxvk/files/7137533/gta-vc_d3d9.log)

**Comment by doitsujin** [comment]
> (Not available)

..............................

**Comment by Mrblubb** [comment]
I don't know how to use Apitrace.

**Comment by GreyXor** [comment]
@Mrblubb Thank you for your feedback. Here is a small guide to follow to make an apitrace. it will be very useful to determine more quickly the source of the problem. https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace

**Comment by Mrblubb** [comment]
Thanks for the help. But the problem is I can't use both Dxvk & Apitrace at the same time since they have same dll names d3d9.dll & the mods already use other dll names like for eg. ASI loader d3d8 etc.

**Comment by doitsujin** [comment]
you're not supposed to use apitrace and dxvk at the same time, just apitrace.

**Comment by Mrblubb** [comment]
oh ok got it ! but didn't knew it was so resource heavy & made my game almost unplayable. Not to mention the huge file it generates. I quickly reproduced the issue again then quit the game lol. Now the size is somewhat bearable. 
Here it is for VC
https://we.tl/t-mk52L1qlBq

Also SA doesn't launch with apitrace for some reason. Shows this error
![Screenshot (19)](https://user-images.githubusercontent.com/88938655/132764465-1b95a602-8ec3-4fb5-a4a5-a2699491696f.png)

**Comment by HunterCZ122** [comment]
Reproduced this issue.
[Native D3D9](https://youtu.be/uCyTgNim5k8)
[DXVK](https://youtu.be/rwT7C_kvLJk)
[Apitrace](https://drive.google.com/file/d/1gQvXpXrvI9DsHCT3RNJsQtvzf2kGVu49/view?usp=sharing)

**Comment by Mrblubb** [comment]
> Reproduced this issue. [Native D3D9](https://youtu.be/uCyTgNim5k8) [DXVK](https://youtu.be/rwT7C_kvLJk) [Apitrace](https://drive.google.com/file/d/1gQvXpXrvI9DsHCT3RNJsQtvzf2kGVu49/view?usp=sharing)

Glad to see I'm not the only one experiencing this. Thanks man. Hope this gets fixed soon, after what the travesty remasters are already!

**Comment by Blisto91** [comment]
@Mrblubb @HunterCZ122 Could i get you guys to test this issue again?
Maybe even with latest master as a bunch of the codebase have been touched lately. You can grab a build here https://github.com/doitsujin/dxvk/actions/runs/2615690694

**Comment by Blisto91** [comment]
Thanks for checking.
I will try to do some testing when i have some time.

**Comment by K0bin** [comment]
Nice find. Dropping this here for reference: https://github.com/aap/skygfx/blob/926616a3f31deaf0d300b3752383314db28994f0/src/main.cpp#L122

**Comment by HunterCZ122** [comment]
Can't reproduce it anymore on GTA San Andreas and Vice City. Maybe recent commits fixed it somehow. I think the issue can be closed. The broken HUD is different issue, which is already reported.
![Screenshot_20220813_004904](https://user-images.githubusercontent.com/23011428/184454168-d92460fa-92e6-4b4b-82c9-10a538d7a3dd.png)
![Screenshot_20220813_004407](https://user-images.githubusercontent.com/23011428/184454139-9d27eb9a-7f5a-4834-a343-48bae42cef79.png)
