### ISSUE TITLE
DXVK Skyrim SE low fps. Windows 11, AMD.

### ISSUE THREAD

**Issue by chumik6000** [doitsujin/dxvk#2288]
I get low fps using dxvk+enb. Around 30 fps. Without dxvk i get 60 fps. With dxvk 2 memory heap go above 100 %. Can someone help me to find a fix? TY!

### Software information
Windows 11 beta latest update.
CPU ryzen 5800x
32 ram 3200 gz
SSD sumsung 980 pro 1T.

### System information
- GPU: amd RX 6900 XT
- Driver: Amd Adrenalin 21.8.2 Optional
- DXVK version: 1.9.1

### Log files
- d3d11.log: https://file.io/NDQRHRHexrhV
- dxgi.log: https://file.io/5Mt21bcP54fp

**Comment by doitsujin** [comment]
Just don't use DXVK if it's slower for you? ENB in particular is known not to work well and that will not change.

**Comment by chumik6000** [comment]
Well dxvk give me big boost but now it is broken for me now. I just cant understand is it a problem in windows 11 or amd drivers?

**Comment by doitsujin** [comment]
Don't know, don't care. Windows isn't our target platform and Windows 11 especially is completely outside of our control, hell, it doesn't even work on my PC.
