### ISSUE TITLE
Lower than expected performance comparing to intel cpu.

### ISSUE THREAD

**Issue by arabcian** [doitsujin/dxvk#2289]
Hello i have a Legion 5 Pro laptop which has AMD 5800h and RTX 3060. In some games i get lower than expected performance from my setup. For example in Thief 2014 benchmark i get 120FPS in Windows but only 50 FPS in Linux. On my older laptop which has 1050ti and i5 8300h i was getting 100FPS in Windows and 80FPS in Linux using dxvk. I tried to downgrade it didnt help at all. I get normal FPS in Divinity Original Sin 2 but not in SKyrimSE, Fallout4, Thief 2014, and Cyberpunk 2077.

Its on Gentoo Linux, LTO'ed kernel 5.14 Xanmod and nvidia-drivers 470.63.01

**Comment by doitsujin** [comment]
Large performance differences compared to Windows Nvidia drivers are expected.

Make sure you're running a wine version with esync or fsync enabled as well.

**Comment by arabcian** [comment]
Im thinking im clear enough, there is large performance gap comparing the intel setup vs amd setup. using GE proton 6.16 with Fsync already. Nvidia's power management works as always.

**Comment by doitsujin** [comment]
Well yeah and none of that is our problem. DXVK works fine on AMD CPUs as long as your system is configured correctly.
