### ISSUE TITLE
FarCry4 black screen. Retested

### ISSUE THREAD

**Issue by steemandlinux** [doitsujin/dxvk#229]
SC(ERROR / SPEC): object: 0x0 type: 0 msgNum: 3 - Attachment 4 not written by fragment shader
SC(ERROR): object: 0x0 type: 0 location: 806 msg_code: 3: Object: 0x0 | Attachment 4 not written by fragment shader
info:  DxgiPresenter: Recreating swap chain: 
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_FIFO_KHR
  Buffer size:  1781913377x0
ParameterValidation(ERROR / SPEC): object: 0x0 type: 10 msgNum: 165676898 - vkCreateImage: parameter pCreateInfo->extent.height (= 0) is greater than 0. The spec valid usage text states 'extent::height must be greater than 0.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageCreateInfo-extent-00945)
ParameterValidation(ERROR): object: 0x0 type: 10 location: 182 msg_code: 165676898: Object: 0x0 | vkCreateImage: parameter pCreateInfo->extent.height (= 0) is greater than 0. The spec valid usage text states 'extent::height must be greater than 0.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkImageCreateInfo-extent-00945)

### Software information
FarCry4 Medium Settings

### System information
- GPU: RX560
- Driver: mesa-git, llvm-svn
- Wine version: vulkan 3.4
- DXVK version: a2f05467c7d3789a42471170242f76d75e7cd02f

[FarCry4_d3d11.log](https://github.com/doitsujin/dxvk/files/1865361/FarCry4_d3d11.log)
[FarCry4_dxgi.log](https://github.com/doitsujin/dxvk/files/1865362/FarCry4_dxgi.log)
[FarCry4_wine.log](https://github.com/doitsujin/dxvk/files/1865366/FarCry4_wine.log)

**Comment by xpander69** [comment]
Works for me, but framerate is super low no matter the settings low or max, still same fps. GPU usage goes up to 35% only so bottlenecking somewhere else.

![ss_04042018_12 57 46](https://user-images.githubusercontent.com/1345116/38301590-a856d31c-3808-11e8-9a63-642fb2deaaa2.png)

log: https://pastebin.com/xd3uzraN
dxvk version: e06300d

**Comment by doitsujin** [comment]
General rule of thumb: if things don't work on RADV, try again with `RADV_DEBUG=nohiz`.

The validation errors seem to be caused by some issues in the swap chain code, doesn't look like they are responsible for the black screen issue though.

**Comment by davvvve1** [comment]
For me to get it to run is turning virtual desktop on with lower resolution than the screen .

**Comment by steemandlinux** [comment]
Fixed by llvm update.
