### ISSUE TITLE
Building issue with compilers updated

### ISSUE THREAD

**Issue by Jhoules** [doitsujin/dxvk#2290]
Problem compiling even though using the POSIX gcc and g++ for x64 and i686. Also have gcc/g++ 10.

`
$ /package-release.sh master ~/.local/share/lutris/runtime/dxvk/dxvktop --no-package
The Meson build system
Version: 0.53.2
Source dir: /home/thejhoule/dxvk
Build dir: /home/thejhoule/.local/share/lutris/runtime/dxvk/dxvktop/dxvk-master/build.64
Build type: cross build
Project name: dxvk
Project version: v1.9.1
C compiler for the build machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C linker for the build machine: cc ld.bfd 2.34
C++ compiler for the build machine: c++ (gcc 9.3.0 "c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C++ linker for the build machine: c++ ld.bfd 2.34
C compiler for the host machine: x86_64-w64-mingw32-gcc (gcc 9.3.0 "x86_64-w64-mingw32-gcc (GCC) 9.3-posix 20200320")
C linker for the host machine: x86_64-w64-mingw32-gcc ld.bfd 2.34
C++ compiler for the host machine: x86_64-w64-mingw32-g++ (gcc 9.3.0 "x86_64-w64-mingw32-g++ (GCC) 9.3-posix 20200320")
C++ linker for the host machine: x86_64-w64-mingw32-g++ ld.bfd 2.34
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Compiler for C++ supports link arguments -Wl,--file-alignment=4096: YES 
Compiler for C++ supports arguments -msse3: YES 
Library vulkan-1 found: YES
Library d3d9 found: YES
Library d3d11 found: YES
Library dxgi found: YES
Library d3dcompiler_43 found: YES
Library d3dcompiler_47 found: YES
Program glslangValidator found: YES (/usr/bin/glslangValidator)
Run-time dependency threads found: YES
Dependency threads found: YES unknown (cached)
Build targets in project: 13

Found ninja-1.10.0 at /usr/bin/ninja
[11/273] Generating 'src/dxvk/1752c3e@@dxvk@sta/dxvk_blit_frag_1d.h'.
../../../../../../../../dxvk/src/dxvk/shaders/dxvk_blit_frag_1d.frag
[13/273] Generating 'src/dxvk/1752c3e@@dxvk@sta/dxvk_blit_frag_2d.h'.
../../../../../../../../dxvk/src/dxvk/shaders/dxvk_blit_frag_2d.frag
[15/273] Generating 'src/dxvk/1752c3e@@dxvk@sta/dxvk_blit_frag_3d.h'.
../../../../../../../../dxvk/src/dxvk/shaders/dxvk_blit_frag_3d.frag
[17/273] Generating 'src/dxvk/1752c3e@@dxvk@sta/dxvk_clear_buffer_f.h'.
..............................................................
[134/273] Compiling C++ object 'src/dxgi/cde8a16@@dxgi@sha/dxgi_adapter.cpp.obj'.
FAILED: src/dxgi/cde8a16@@dxgi@sha/dxgi_adapter.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/dxgi/cde8a16@@dxgi@sha -Isrc/dxgi -I../../../../../../../../dxvk/src/dxgi -I../../../../../../../../dxvk/./include -fdiagnostics-color=always -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O3 -DNOMINMAX -D_WIN32_WINNT=0xa00 -msse3 -MD -MQ 'src/dxgi/cde8a16@@dxgi@sha/dxgi_adapter.cpp.obj' -MF 'src/dxgi/cde8a16@@dxgi@sha/dxgi_adapter.cpp.obj.d' -o 'src/dxgi/cde8a16@@dxgi@sha/dxgi_adapter.cpp.obj' -c ../../../../../../../../dxvk/src/dxgi/dxgi_adapter.cpp
In file included from ../../../../../../../../dxvk/src/dxgi/dxgi_adapter.cpp:8:
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:13:41: error: ‘IDXGIFactory7’ was not declared in this scope; did you mean ‘IDXGIFactory2’?
   13 |   class DxgiFactory : public DxgiObject<IDXGIFactory7> {
      |                                         ^~~~~~~~~~~~~
      |                                         IDXGIFactory2
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:13:54: error: template argument 1 is invalid
   13 |   class DxgiFactory : public DxgiObject<IDXGIFactory7> {
      |                                                      ^
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:75:13: error: ‘DXGI_GPU_PREFERENCE’ has not been declared
   75 |             DXGI_GPU_PREFERENCE   GpuPreference,
      |             ^~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:20:31: error: ‘HRESULT dxvk::DxgiFactory::QueryInterface(const IID&, void**)’ marked ‘final’, but is not virtual
   20 |     HRESULT STDMETHODCALLTYPE QueryInterface(
      |                               ^~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:24:31: error: ‘HRESULT dxvk::DxgiFactory::GetParent(const IID&, void**)’ marked ‘final’, but is not virtual
   24 |     HRESULT STDMETHODCALLTYPE GetParent(
      |                               ^~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:28:28: error: ‘BOOL dxvk::DxgiFactory::IsWindowedStereoEnabled()’ marked ‘final’, but is not virtual
   28 |     BOOL STDMETHODCALLTYPE IsWindowedStereoEnabled() final;
      |                            ^~~~~~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:30:31: error: ‘HRESULT dxvk::DxgiFactory::CreateSoftwareAdapter(HMODULE, IDXGIAdapter**)’ marked ‘final’, but is not virtual
   30 |     HRESULT STDMETHODCALLTYPE CreateSoftwareAdapter(
      |                               ^~~~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:34:31: error: ‘HRESULT dxvk::DxgiFactory::CreateSwapChain(IUnknown*, DXGI_SWAP_CHAIN_DESC*, IDXGISwapChain**)’ marked ‘final’, but is not virtual
   34 |     HRESULT STDMETHODCALLTYPE CreateSwapChain(
      |                               ^~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:39:31: error: ‘HRESULT dxvk::DxgiFactory::CreateSwapChainForHwnd(IUnknown*, HWND, const DXGI_SWAP_CHAIN_DESC1*, const DXGI_SWAP_CHAIN_FULLSCREEN_DESC*, IDXGIOutput*, IDXGISwapChain1**)’ marked ‘final’, but is not virtual
   39 |     HRESULT STDMETHODCALLTYPE CreateSwapChainForHwnd(
      |                               ^~~~~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:47:31: error: ‘HRESULT dxvk::DxgiFactory::CreateSwapChainForCoreWindow(IUnknown*, IUnknown*, const DXGI_SWAP_CHAIN_DESC1*, IDXGIOutput*, IDXGISwapChain1**)’ marked ‘final’, but is not virtual
   47 |     HRESULT STDMETHODCALLTYPE CreateSwapChainForCoreWindow(
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:54:31: error: ‘HRESULT dxvk::DxgiFactory::CreateSwapChainForComposition(IUnknown*, const DXGI_SWAP_CHAIN_DESC1*, IDXGIOutput*, IDXGISwapChain1**)’ marked ‘final’, but is not virtual
   54 |     HRESULT STDMETHODCALLTYPE CreateSwapChainForComposition(
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:60:31: error: ‘HRESULT dxvk::DxgiFactory::EnumAdapters(UINT, IDXGIAdapter**)’ marked ‘final’, but is not virtual
   60 |     HRESULT STDMETHODCALLTYPE EnumAdapters(
      |                               ^~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:64:31: error: ‘HRESULT dxvk::DxgiFactory::EnumAdapters1(UINT, IDXGIAdapter1**)’ marked ‘final’, but is not virtual
   64 |     HRESULT STDMETHODCALLTYPE EnumAdapters1(
      |                               ^~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:68:31: error: ‘HRESULT dxvk::DxgiFactory::EnumAdapterByLuid(LUID, const IID&, void**)’ marked ‘final’, but is not virtual
   68 |     HRESULT STDMETHODCALLTYPE EnumAdapterByLuid(
      |                               ^~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:79:31: error: ‘HRESULT dxvk::DxgiFactory::EnumWarpAdapter(const IID&, void**)’ marked ‘final’, but is not virtual
   79 |     HRESULT STDMETHODCALLTYPE EnumWarpAdapter(
      |                               ^~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:83:31: error: ‘HRESULT dxvk::DxgiFactory::GetWindowAssociation(HWND__**)’ marked ‘final’, but is not virtual
   83 |     HRESULT STDMETHODCALLTYPE GetWindowAssociation(
      |                               ^~~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:86:31: error: ‘HRESULT dxvk::DxgiFactory::GetSharedResourceAdapterLuid(HANDLE, LUID*)’ marked ‘final’, but is not virtual
   86 |     HRESULT STDMETHODCALLTYPE GetSharedResourceAdapterLuid(
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:90:31: error: ‘HRESULT dxvk::DxgiFactory::MakeWindowAssociation(HWND, UINT)’ marked ‘final’, but is not virtual
   90 |     HRESULT STDMETHODCALLTYPE MakeWindowAssociation(
      |                               ^~~~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:94:28: error: ‘BOOL dxvk::DxgiFactory::IsCurrent()’ marked ‘final’, but is not virtual
   94 |     BOOL STDMETHODCALLTYPE IsCurrent() final;
      |                            ^~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:96:31: error: ‘HRESULT dxvk::DxgiFactory::RegisterOcclusionStatusWindow(HWND, UINT, DWORD*)’ marked ‘final’, but is not virtual
   96 |     HRESULT STDMETHODCALLTYPE RegisterOcclusionStatusWindow(
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:101:31: error: ‘HRESULT dxvk::DxgiFactory::RegisterStereoStatusEvent(HANDLE, DWORD*)’ marked ‘final’, but is not virtual
  101 |     HRESULT STDMETHODCALLTYPE RegisterStereoStatusEvent(
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:105:31: error: ‘HRESULT dxvk::DxgiFactory::RegisterStereoStatusWindow(HWND, UINT, DWORD*)’ marked ‘final’, but is not virtual
  105 |     HRESULT STDMETHODCALLTYPE RegisterStereoStatusWindow(
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:110:31: error: ‘HRESULT dxvk::DxgiFactory::RegisterOcclusionStatusEvent(HANDLE, DWORD*)’ marked ‘final’, but is not virtual
  110 |     HRESULT STDMETHODCALLTYPE RegisterOcclusionStatusEvent(
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:114:28: error: ‘void dxvk::DxgiFactory::UnregisterStereoStatus(DWORD)’ marked ‘final’, but is not virtual
  114 |     void STDMETHODCALLTYPE UnregisterStereoStatus(
      |                            ^~~~~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:117:28: error: ‘void dxvk::DxgiFactory::UnregisterOcclusionStatus(DWORD)’ marked ‘final’, but is not virtual
  117 |     void STDMETHODCALLTYPE UnregisterOcclusionStatus(
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:120:28: error: ‘UINT dxvk::DxgiFactory::GetCreationFlags()’ marked ‘final’, but is not virtual
  120 |     UINT STDMETHODCALLTYPE GetCreationFlags() final;
      |                            ^~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/dxgi/dxgi_factory.h:122:31: error: ‘HRESULT dxvk::DxgiFactory::CheckFeatureSupport(DXGI_FEATURE, void*, UINT)’ marked ‘final’, but is not virtual
  122 |     HRESULT STDMETHODCALLTYPE CheckFeatureSupport(
      |                               ^~~~~~~~~~~~~~~~~~~
In file included from ../../../../../../../../dxvk/src/dxgi/dxgi_include.h:14,
                 from ../../../../../../../../dxvk/src/dxgi/dxgi_format.h:3,
                 from ../../../../../../../../dxvk/src/dxgi/dxgi_adapter.h:6,
                 from ../../../../../../../../dxvk/src/dxgi/dxgi_adapter.cpp:6:
../../../../../../../../dxvk/src/dxgi/../util/com/com_pointer.h: In instantiation of ‘static void dxvk::ComRef_<T, Public>::incRef(T*) [with T = dxvk::DxgiFactory; bool Public = true]’:
../../../../../../../../dxvk/src/dxgi/../util/com/com_pointer.h:136:23:   required from ‘void dxvk::Com<T, Public>::incRef() const [with T = dxvk::DxgiFactory; bool Public = true]’
../../../../../../../../dxvk/src/dxgi/../util/com/com_pointer.h:57:13:   required from ‘dxvk::Com<T, Public>::Com(T*) [with T = dxvk::DxgiFactory; bool Public = true]’
../../../../../../../../dxvk/src/dxgi/dxgi_adapter.cpp:63:21:   required from here
../../../../../../../../dxvk/src/dxgi/../util/com/com_pointer.h:27:39: error: ‘class dxvk::DxgiFactory’ has no member named ‘AddRef’
   27 |     static void incRef(T* ptr) { ptr->AddRef(); }
      |                                  ~~~~~^~~~~~
../../../../../../../../dxvk/src/dxgi/../util/com/com_pointer.h: In instantiation of ‘static void dxvk::ComRef_<T, Public>::decRef(T*) [with T = dxvk::DxgiFactory; bool Public = true]’:
../../../../../../../../dxvk/src/dxgi/../util/com/com_pointer.h:141:23:   required from ‘void dxvk::Com<T, Public>::decRef() const [with T = dxvk::DxgiFactory; bool Public = true]’
../../../../../../../../dxvk/src/dxgi/../util/com/com_pointer.h:98:13:   required from ‘dxvk::Com<T, Public>::~Com() [with T = dxvk::DxgiFactory; bool Public = true]’
../../../../../../../../dxvk/src/dxgi/dxgi_adapter.cpp:63:21:   required from here
../../../../../../../../dxvk/src/dxgi/../util/com/com_pointer.h:28:39: error: ‘class dxvk::DxgiFactory’ has no member named ‘Release’
   28 |     static void decRef(T* ptr) { ptr->Release(); }
      |                                  ~~~~~^~~~~~~
[137/273] Compiling C++ object 'src/dxgi/cde8a16@@dxgi@sha/dxgi_main.cpp.obj'.
FAILED: src/dxgi/cde8a16@@dxgi@sha/dxgi_main.cpp.obj 
......................
[147/273] Compiling C++ object 'src/dxbc/5c53ffa@@dxbc@sta/dxbc_options.cpp.obj'.
ninja: build stopped: subcommand failed.
`
anyone has any idea what I'm doing wrong?

### System information
- GPU: GTX 1650 
- Driver: nvidia-470
- Wine version:  wine-6.0.1
- DXVK version: 1.9.1

**Comment by Joshua-Ashton** [comment]
Get a newer mingw.

**Comment by Jhoules** [comment]
like which one? I already have mingw-w64 in the newest...

**Comment by Joshua-Ashton** [comment]
If you did it would work. Your headers are old.

**Comment by doitsujin** [comment]
mingw-headers needs to be 8.0 or higher for this to work.
