### ISSUE TITLE
[d3d9] Sanctum 2 - flickering surfaces

### ISSUE THREAD

**Issue by HenryJk** [doitsujin/dxvk#2291]
Using proton+dxvk because the linux native version has sound and graphical issue. On the level shown on apitrace, the white floor near enemy spawn is flickering on linux. The game also does not launch with wined3d so I can't make comparison. However, this issue is not found on windows.

### Sanctum 2 (appid 210770)
Max Settings except no MSAA

### System information
- CPU: Intel© Core™ i7-9750H CPU @ 2.60GHz × 6
- GPU: NVIDIA NVIDIA GeForce GTX 1650 with Max-Q Design
- Driver: 470.63.01
- Wine version: Proton 6.3-3
- DXVK version: 1.9-1

### Apitrace file(s)
- https://drive.google.com/file/d/1AIMuGzoHFk4_5c9Re8gwdpIWQEBFpgzn/view?usp=sharing

### Log files
- d3d9.log:
[SanctumGame-Win32-Shipping_d3d9.log](https://github.com/doitsujin/dxvk/files/7149649/SanctumGame-Win32-Shipping_d3d9.log)
- d3d11.log:
[SanctumGame-Win32-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/7149651/SanctumGame-Win32-Shipping_dxgi.log)
- dxgi.log:
[SanctumGame-Win32-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/7149650/SanctumGame-Win32-Shipping_d3d11.log)

**Comment by HenryJk** [comment]
Side note, the apitrace and the log file doesn't come from the same run. The log file is running on linux while the apitrace file is on windows. They just have the same level selected to possibly give more info to the bug.

**Comment by HenryJk** [comment]
Yes,

https://user-images.githubusercontent.com/25541369/148123171-0f820b70-a78a-4276-8f23-f2369c0d3aa0.mp4

This is on Proton Experimental

**Comment by K0bin** [comment]
Could you upload your save file?

**Comment by HenryJk** [comment]
[local.zip](https://github.com/doitsujin/dxvk/files/7814583/local.zip)

**Comment by K0bin** [comment]
Can you try running the game with a DXVK config file and add the line `d3d9.invariantPosition = True` to that?

**Comment by Blisto91** [comment]
I have not been able to reproduce this either on my amd setup or my nvidia 960 with 470.103 driver. I tried a few different dxvk versions including 1.9 & 1.9.1

**Comment by Blisto91** [comment]
@HenryJk Friendly ping

**Comment by HenryJk** [comment]
https://user-images.githubusercontent.com/25541369/177167590-8187ecf8-0be6-4eed-9b9a-d21c5e02762f.mp4

**Comment by Blisto91** [comment]
Roger. I will try to check again on my Nvidia setup.

**Comment by Blisto91** [comment]
I have been trying for a little while now to try and reproduce this and i sadly still haven't been able to.

Why does it appear like your whole game is shaking slighty when i look at your videos in full screen? Does that also happen ingame or is that the recording?

**Comment by Blisto91** [comment]
@HenryJk Please retest with dxvk 2.0 if you can :slightly_smiling_face: 
Note you need 510 driver or above.

**Comment by HenryJk** [comment]
Hi, I currently have a hardware issue on my laptop, will retest when I finished fixing it.

**Comment by HenryJk** [comment]
https://user-images.githubusercontent.com/25541369/201538934-edce2fe1-c4a4-4bd0-83cc-d5a100e73a1b.mp4

and yes, the shaking happens in-game

**Comment by Blisto91** [comment]
Very very strange :eyes:

**Comment by Blisto91** [comment]
@HenryJk Is it possible to get a fresh test of this with latest dxvk and driver?

**Comment by HenryJk** [comment]
Fixed, completely fixed, I'm surprised.

**Comment by Blisto91** [comment]
Huzzah!
I still have no clue what the issue was.

**Comment by HenryJk** [comment]
I think I can help bisect which patch is fixing it if I have time for it.

**Comment by Blisto91** [comment]
Sure hehe
