### ISSUE TITLE
Alien Isolation crashes on startup due to page fault

### ISSUE THREAD

**Issue by radgeRayden** [doitsujin/dxvk#2292]
### Software information
Game is Alien Isolation played through the Heroic Games Launcher (which uses legendary under the hood) on Linux (Pop_OS! 21.04). 

When dxvk is installed in the prefix, I get a wine crash with a page fault and a backtrace (included in the end). Game works normally using wine d3d11 implementation. Game runs with dxvk if d3d11.dll is set to native, but dxgi is set to builtin. However it won't use my dedicated graphics card in that case (and doesn't seem to respect the device filter env variable, or more likely doesn't detect my dedicated gpu at all).

### System information
- GPU: NVIDIA GeForce GTX 1660 Ti Mobile 
- Driver: 470.57.2
- Wine version: lutris-ge-6.15-1-x86_64
- DXVK version: v1.9.1-105-gdd7ffbc8 (but same issue on latest release)

### Apitrace file(s)
I don't think I can make an api trace under legendary. If someone knows how to do that, please tell me.

### Log files
- d3d11.log:
[AI_d3d11.log](https://github.com/doitsujin/dxvk/files/7152599/AI_d3d11.log)
- dxgi.log:
[AI_dxgi.log](https://github.com/doitsujin/dxvk/files/7152602/AI_dxgi.log)

Here's also the backtrace from the wine crash:
[backtrace.txt](https://github.com/doitsujin/dxvk/files/7152606/backtrace.txt)

**Comment by doitsujin** [comment]
> err:   Failed to create swap chain
> err:   D3D11CreateDevice: Failed to create swap chain

There's some sort of configuration problem on your end, the dedicated GPU cannot display anything on screen.

**Comment by radgeRayden** [comment]
I have played other games with dxvk on, including Control with the exact same setup (same wine version, same launcher) as the one causing the issue here. Also play dxvk titles on steam without an issue.
Using the dedicated GPU, of course.

**Comment by doitsujin** [comment]
There's still something wrong on your system, probably some 32-bit stuff missing.

**Comment by radgeRayden** [comment]
I have done some research, double checked a few things. My most likely suspicion was that I lacked 32-bit vulkan libraries. That turned out to be installed, and everything was in the right place. In the end, I tried setting dxgi.dll to builtin again in winecfg, and to my surprise it worked. I have no idea what changed between then and now. It properly detects my dedicated gpu and the game runs at the expected level of performance. Dxvk's dxgi.dll still a no-go.

I'm satisfied with the result as I get to play the game, but will let it for you to decide whether to close or not.

**Comment by doitsujin** [comment]
Given that the problematic code lives in d3d11.dll I don't really see why that would change anything. Without installed Vulkan libraries/drivers the messages would have been different, the problem is just that the Nvidia driver cannot create a presentable surface for whatever reason, so maybe some sort of PRIME issue.

Anyway, not much we can do here.
