### ISSUE TITLE
Poor performance in AVICII Invector (Unity 2019.2.10f1)

### ISSUE THREAD

**Issue by adolfintel** [doitsujin/dxvk#2293]
The Unity game AVICII Invector runs very slow on DXVK, about 1/5th of the framerate that I get on WineD3D or natively on Windows.

With WineD3D the game is playable in 1080p, or even 1440p (on my miserable RX550) but on DXVK the performance is in the range of 10-30fps for 1080p and 5-20fps for 1440p and I can't figure out why, usually DXVK runs significantly better, especially with Unity games.

Rendering is correct, no instability in the game itself. WineD3D does not render the game correctly.

### Software information
* AVICII Invector, latest steam version
* Manjaro 21 with Linux 5.14 kernel
* Xorg
* Tested with and without gamescope, ESYNC, DXVK_ASYNC, no difference

### System information
- GPU: AMD RX550
- Driver: RADV POLARIS (Mesa 21.2.1)
- Wine version: 6.16 (ge), 6.17-staging
- DXVK version: both 1.9.1 and current master

### Log files
- d3d9.log: N/A
- d3d11.log: [AVICII Invector_d3d11.log](https://github.com/doitsujin/dxvk/files/7157082/AVICII.Invector_d3d11.log)
- dxgi.log: [AVICII Invector_dxgi.log](https://github.com/doitsujin/dxvk/files/7157083/AVICII.Invector_dxgi.log)

### Apitrace
[https://downloads.fdossena.com/avicii.trace.tar.xz](https://downloads.fdossena.com/avicii.trace.tar.xz)

**Comment by doitsujin** [comment]
Is your VRAM full by any chance? Your card only has 2GB which is the minimum requirement for the game *on Windows*, and DXVK can always do with a little more.

Not really seeing any obvious problem here, and [protondb](https://www.protondb.com/app/986800) reports also don't complain about performance.

**Comment by adolfintel** [comment]
Nope, even at 1440p it doesn't even get to 1GB of usage, this is a very lightweight game.

It's 100% GPU bound, even at 640x480.

Anything else that I can try?

**Comment by doitsujin** [comment]
Note that background applications also eat VRAM.

> It's 100% GPU bound, even at 640x480.

That kind of implies that something is taking a *very* slow data path though. There's no reason for this to happen (unless.... we're not talking about an external GPU, are we?)

On my end, even the trace replays at well over 100 FPS without the GPU breaking a sweat, so not sure what else it could be.

**Comment by adolfintel** [comment]
Just to be sure I started Xorg without DE or any other application, it's not a VRAM issue, it runs the same. Besides, if it was insufficient VRAM wouldn't WineD3D be affected too?
The PC is a desktop, PCI-E x16, so it's not a bandwidth issue (unless it's the bandwidth between the GPU and the VRAM, which isn't great on this card).
I could try with my GTX1080 if you want, but it will probably brute force past this.

Are you aware of any "trick" specific to unity games that I may have overlooked? I'm kinda new to linux gaming but I'm a developer too so I can try anything that comes to your mind.

**Comment by adolfintel** [comment]
A quick update on this.

As I suspected, I wasn't able to replicate the issue on either a GTX1080 or a 6900XT, they both have virtually identical performance compared to WineD3D. I also tried an R9 290X, getting lower performance with DXVK than WineD3D but still very playable. I cannot explain why this specific game hates the RX550 so much when other unity games, heavier ones, run way better.

The only thing out of the ordinary that I see is that WineD3D fakes the GPU ID and pretends to be an ATI Radeon HD5600 Series card. Faking the GPU ID and name with DXVK had no effect so I don't think that's the problem.

I should point out that the RX550 doesn't get hot at all despite DXVK claiming 100% GPU usage, which makes me thing of a GPU-VRAM bandwidth limitation. Is DXVK more bandwidth hungry than WineD3D?

**Comment by Kron4ek** [comment]
Out of curiosity i just tried the game on RX 560 and it works good with DXVK (both 1.9.1 and current master). That's on Mesa 21.2.1 and linux 5.10. It's really weird that it works so badly on RX 550.

**Comment by adolfintel** [comment]
@Kron4ek Very strange indeed. What's your wine version?

**Comment by Kron4ek** [comment]
Wine-Staging 6.17, i also tried Proton 6.3-6 - the game performs pretty much identically in both cases. Also, your apitrace replays well for me.

**Comment by adolfintel** [comment]
Just tested both from your builds, no change.
Would a trace taken from outside be useful? Capturing the vulkan calls generated by DXVK

**Comment by Kron4ek** [comment]
I see we have different kernel versions, maybe there is a regression in 5.14? I doubt that, but who knows. You could try 5.10.

**Comment by adolfintel** [comment]
No luck :(
I'll try to capture a vulkan trace and see if it reveals anything

**Comment by adolfintel** [comment]
I captured a single frame using RenderDoc, it's here if it can be useful: [https://downloads.fdossena.com/avicii.renderdoc.tar.xz](https://downloads.fdossena.com/avicii.renderdoc.tar.xz)

640mb seems quite a lot for a single frame, but I'm not familiar with RenderDoc so I don't know if that's normal.

**Comment by K0bin** [comment]
Is it a D3D11 or Vulkan Renderdoc capture?

**Comment by adolfintel** [comment]
@K0bin Vulkan. There's a D3D11 capture in the original post

**Comment by doitsujin** [comment]
Vulkan captures are not portable, which means it's unlikely anyone will be able to open it unless they also have a Polaris GPU.

**Comment by adolfintel** [comment]
Oh, I didn't know that. Anything else I can capture?

**Comment by adolfintel** [comment]
I just noticed some very odd behavior while capturing with RenderDoc.
Some times (1 in 5 or so), when the game is launched with `renderdoccmd capture wine "AVICII Invector.exe"`, it runs properly, but not if I launch it directly.
I see no difference in the captures though, odd.

**Comment by adolfintel** [comment]
I just tested the game with AMDVLK instead of RADV and it runs properly, so it may not be a DXVK bug.

**Comment by Oschowa** [comment]
Can you try on RADV with this commit reverted https://gitlab.freedesktop.org/mesa/mesa/-/commit/4889cd7345ecbea4703ff15bd8b9409ae816f93c ?

**Comment by adolfintel** [comment]
@Oschowa no change

**Comment by adolfintel** [comment]
I'm closing this, it was a VRAM bandwidth issue.
