### ISSUE TITLE
No DX9 support for nvidia gpu since new driver - 470.63.01

### ISSUE THREAD

**Issue by gabriele2000** [doitsujin/dxvk#2295]
I'll attach a log of a random DX9 game, since it'll select the Intel GPU, but on DX11 games everything is detected and, of course, the nvidia gpu will be used.

Before the driver update, everything was fine, but after I updated, steam no longer worked, wine wasn't the problem since I even rolled back to 6.16 to test if 6.17 was the problem.
Steam was only part of the problem... in time, I discovered that ALL DX9 games won't see the Dedicated GPU.
I think it's an issue with Prime or something, but it detects every GPU available.

Setting the variable that allows to only choose the preferred GPU won't work, restarting the system in "nvidia only" won't work, nothing running on DX9 will actually run.

### System information
- GPU: Nvidia GTX1050TI
- Driver: 470.63.01
- Wine version: 6.17-staging-tgk-amd64
- DXVK version: 1.9.1-105-gdd7ffbc8

### Log files
- d3d9.log: [FEAR2_d3d9.log](https://github.com/doitsujin/dxvk/files/7172382/FEAR2_d3d9.log)

**Comment by Joshua-Ashton** [comment]
You probably forgot to update your 32-bit NVIDIA driver.

**Comment by gabriele2000** [comment]
> You probably forgot to update your 32-bit NVIDIA driver.

strange... apt should've updated it... let me check

**Comment by gabriele2000** [comment]
> You probably forgot to update your 32-bit NVIDIA driver.

Damn, I should've figured it out earlier... I purged nvidia* then reinstalled the driver, boom it worked.

Thanks a lot, sorry for the trouble
