### ISSUE TITLE
FPS does not rise above 60

### ISSUE THREAD

**Issue by ekrem007** [doitsujin/dxvk#2298]
### Software information
Tested in GTA: Vice City, reVC and Call of Duty 4: MW, same behavior :(
### System information
- **GPU**: nVidia GeForce GTX 660M
- **Driver**: 425.31.0
- **OS**: Windows 10 21H1 (19043.1237)
- **DXVK version**: 1.9.1
### dxvk.conf file
```
dxvk.hud = full
d3d9.presentInterval = 0
d3d9.maxFrameRate = 0
```
### Apitrace files
- https://drive.google.com/drive/folders/16W8cSbbMfI47jFkMBSYdUA3m9XTVv03l?usp=sharing

### Log files
- [gta-vc_d3d9.log](https://github.com/doitsujin/dxvk/files/7192679/gta-vc_d3d9.log)
- [reVC_d3d9.log](https://github.com/doitsujin/dxvk/files/7192683/reVC_d3d9.log)
- [iw3mp_d3d9.log](https://github.com/doitsujin/dxvk/files/7192702/iw3mp_d3d9.log)

_P.S. Sorry for my English_

**Comment by doitsujin** [comment]
Doesn't look like a bug, just probably a weird driver setting somewhere.

**Comment by ekrem007** [comment]
I don't think so, because my driver settings is all default and fps isn't locked when games launched without dxvk.
Maybe is not bug, but wrong dxvk.conf file settings.

**Comment by Evernow** [comment]
> GPU: nVidia GeForce GTX 660M
> Driver: 425.31.0

Worth noting that this hardware is not supported anymore by NVIDIA. Only [desktop Kepler is supported](https://nvidia.custhelp.com/app/answers/detail/a_id/5202/~/support-plan-for-kepler-series-geforce-gpus-for-desktop), not [Laptops](https://nvidia.custhelp.com/app/answers/detail/a_id/4780/kw/Kepler).

**Comment by K0bin** [comment]
That's the fullscreen optimization in Windows 10. It automatically switches your game from exclusive fullscreen to borderless windowed when there's something in front of it. When that happens, the game is limited by the refresh rate of your monitor.

**Comment by ekrem007** [comment]
> 
> 
> That's the fullscreen optimization in Windows 10. It automatically switches your game from exclusive fullscreen to borderless windowed when there's something in front of it. When that happens, the game is limited by the refresh rate of your monitor.

But, FPS is locked when there is nothing over game window (Fullscreen Mode) and unlocked when there is something over it (Borderless Windowed). So, it works the other way around.

**Comment by K0bin** [comment]
Either way, there's nothing we can do about weird Windows compositor behavior.
