### ISSUE TITLE
Offworld Trading Company (Unity 5.6.3p1) near-instacrash with HUD enabled.

### ISSUE THREAD

**Issue by zekesonxx** [doitsujin/dxvk#23]
I'm getting immediate crashes with `DXVK_HUD=1` in Offworld Trading Company.

The game seems to work pretty well without the HUD enabled, though.

### Software information
Offworld Trading Company (Unity 5.6.3p1)

### System information
- GPU: GTX 970
- Driver: prop 387.34
- Wine version: Wine 2.21-staging

### Apitrace file(s)
- [Offworld.trace.gz](https://github.com/doitsujin/dxvk/files/1649803/Offworld.trace.gz) (gzipped not for size but to trick GitHub into hosting the bloody thing)

### Log files
- d3d11.log: [d3d11.log](https://github.com/doitsujin/dxvk/files/1649805/d3d11.log)
- dxgi.log: [dxgi.log](https://github.com/doitsujin/dxvk/files/1649804/dxgi.log)

Also, fun in dmesg:
```
[229371.058294] NVRM: Xid (PCI:0000:0b:00): 69, Class Error: ChId 004b, Class 0000b197, Offset 00001168, Data 00000600, ErrorCode 00000005
```

**Comment by doitsujin** [comment]
The HUD used SRGB-formatted vertex input, which Nvidia apparently does not support., 05f00088919467b312888f15d8f38f66b1b0e7f5 should fix this, please report back whether this works for you.

**Comment by zekesonxx** [comment]
Tested on 05f0008, HUD works fine now.

Fun screenshot:

![](https://puu.sh/z6TrB.png)

Although, it's rendering very dark and with scanlines. Same map, but on Unity's OpenGL renderer (`-force-glcore`):

![](https://puu.sh/z6TDA.png)

**Comment by doitsujin** [comment]
Good to hear that the HUD works.

Sadly your apitrace file is broken. If it had worked correctly, it would have resulted in a file of several hundred Megabytes. When recording the trace, *do not* use DXVK.

**Comment by zekesonxx** [comment]
so I cannot get apitrace to give me a dxgi trace at all.

`WINEDEBUG=-all,fixme-all,+debugstr wine ./apitrace-mingw/x86/bin/apitrace.exe trace --api dxgi -v Offworld.exe` just [outputs](https://github.com/doitsujin/dxvk/files/1653566/Offworld.trace.gz) useless trace files.

It looks like it should be working, too:

```
info: did not find C:\Program Files (x86)\Steam\steamapps\common\Offworld Trading Company\apitrace-msvc\x86\bin\..\wrappers\RelWithDebInfo\dxgitrace.dll
info: found C:\Program Files (x86)\Steam\steamapps\common\Offworld Trading Company\apitrace-msvc\x86\bin\..\lib\wrappers\dxgitrace.dll
inject -D "C:\Program Files (x86)\Steam\steamapps\common\Offworld Trading Company\apitrace-msvc\x86\bin\..\lib\wrappers\dxgitrace.dll" -- Offworld.exe
warn:debugstr:OutputDebugStringA "apitrace: loaded into C:\\Program Files (x86)\\Steam\\steamapps\\common\\Offworld Trading Company\\Offworld.exe\n"
apitrace: loaded into C:\Program Files (x86)\Steam\steamapps\common\Offworld Trading Company\Offworld.exe
warn:debugstr:OutputDebugStringA "apitrace: tracing to C:\\Program Files (x86)\\Steam\\steamapps\\common\\Offworld Trading Company\\Offworld.1.trace\n"
warn:debugstr:OutputDebugStringA "[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.\n"
warn:debugstr:OutputDebugStringA "[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.dll.\n"
warn:debugstr:OutputDebugStringA "apitrace: loaded into C:\\Program Files (x86)\\Steam\\steamapps\\common\\Offworld Trading Company\\Offworld_Data\\Plugins\\tachyon.exe\n"
warn:debugstr:OutputDebugStringA "apitrace: unloaded from C:\\Program Files (x86)\\Steam\\steamapps\\common\\Offworld Trading Company\\Offworld_Data\\Plugins\\tachyon.exe\n"
warn:debugstr:OutputDebugStringA "apitrace: unloaded from C:\\Program Files (x86)\\Steam\\steamapps\\common\\Offworld Trading Company\\Offworld.exe\n"
apitrace: unloaded from C:\Program Files (x86)\Steam\steamapps\common\Offworld Trading Company\Offworld.exe
```

Any thoughts?

**Comment by doitsujin** [comment]
Um, that's tricky. Buf I've encountered the same problem with some of Microsoft's D3D11 samples, apparently apitrace detaches itself after the very first DXGIFactory gets destroyed.

In any case I did fix a rather severe bug in DXVK today which *might* have been the reason why it doesn't render correctly - although to be honest, it doesn't look like the same issue.

**Comment by zekesonxx** [comment]
Retested on e4d49ae, rendering issue remains.

**Comment by zekesonxx** [comment]
Rendering issue gone, appears to renders correctly as of 8f134ba.

![ss-11-02-2018-153642](https://user-images.githubusercontent.com/965509/36078205-9d447064-0f41-11e8-94de-7a7e559b519c.png)

**Comment by doitsujin** [comment]
Good to hear.

Could you bisect the exact commit that fixed it? Knowing what exactly fixed the issue might help fixing similar issues in the future.
