### ISSUE TITLE
[d3d11] Guild Wars 2 64bit - Crash during start up

### ISSUE THREAD

**Issue by hel-ish** [doitsujin/dxvk#2307]
GW2 has gotten a new update to use DX11 utilizing BGFX. When trying to launch the game on Windows with DX11+DXVK 1.9.2 the game crashes after the launcher.

[image](https://user-images.githubusercontent.com/47311546/134703657-919112bf-0f5a-4e87-87ba-133c84a06d54.png)

DXVK with DX9 works fine.

System information
- CPU: Intel 9600k @4.8GHz 6x
- GPU: RTX 2060 OC
- Driver: 472.12
- DXVK version: 1.9.2 
- Windows 10

### Log files
- d3d9.log: -
- d3d11.log :[Gw2-64_d3d11.log](https://github.com/doitsujin/dxvk/files/7226965/Gw2-64_d3d11.log)
- dxgi.log: Blank file, isn't generated due to the crash.

**Comment by K0bin** [comment]
Please make an apitrace.

**Comment by hel-ish** [comment]
> Please make an apitrace.

https://drive.google.com/file/d/1jBLuYUxIPHQAZy-btGLhP-zLnfANghm8/view?usp=sharing

**Comment by doitsujin** [comment]
This is not our bug, according to your log it's using Windows DXGI which cannot work with DXVK.
