### ISSUE TITLE
DXVK HUD with more options (wine version, arch 32 or 64bits)

### ISSUE THREAD

**Issue by mrdeathjr28** [doitsujin/dxvk#2308]
DXVK HUD can have more options like: wine version used and arch used 32 or 64bits like mangohud
this will be usefull in some games (assasins creed hd liberation, black flag, test drive unlimited 2 and others) where mangohud give a crash, dxvk hud work without issues in before cited titles

### System information
- GPU: Nvidia Geforce GTX 1050
- Driver: 470.62.02
- Wine version: 6.16
- DXVK version: 1.9.2

Thanks

**Comment by doitsujin** [comment]
Just use Mangohud if you want that kind of information?

DXVK has no business whatsoever asking for the wine version.

**Comment by mrdeathjr28** [comment]
> Just use Mangohud if you want that kind of information?
> 
> DXVK has no business whatsoever asking for the wine version etc.

this topic is open because before cited apps dont work with mangohud, dxvk can add this options

**Comment by doitsujin** [comment]
well then why not report that to mangohud and see if that can be fixed?

**Comment by mrdeathjr28** [comment]
> well then why not report that to mangohud and see if that can be fixed?

issue stay reported but dont have fixed
