### ISSUE TITLE
black or badly rendered areas in Split Second game

### ISSUE THREAD

**Issue by cipitaua** [doitsujin/dxvk#2309]
Split Second game shows black areas, bad rendered, in all the 3d scenes:

![Screenshot_20210925_114124](https://user-images.githubusercontent.com/4388859/134766975-96a4ee48-29fb-475c-b10a-0220af171ec2.png)
![Screenshot_20210925_114101](https://user-images.githubusercontent.com/4388859/134766976-f8edc65b-b3c1-4d2a-aa4b-574ae9edbe1b.png)
![Screenshot_20210925_114012](https://user-images.githubusercontent.com/4388859/134766977-917aa8f4-c641-4096-9da2-edca6834dac7.png)

The game demo is freely available:
https://www.gamepressure.com/download.asp?ID=27258

### Software information
Split Second is a well known game: https://en.wikipedia.org/wiki/Split/Second

### System information
- GPU: UHD Graphics 620 (KBL GT2)
- Driver: intel-media-va-driver 21.1.1
- Wine version:  wine-6.17 (Staging)
- DXVK version: 1.9.2

### Log files
- d3d9.log: [log.txt](https://github.com/doitsujin/dxvk/files/7229509/log.txt)

**Comment by K0bin** [comment]
Please make an apitrace.

**Comment by cipitaua** [comment]
here is the apitrace

https://we.tl/t-S2KUBz0mt1

**Comment by K0bin** [comment]
Your apitrace ends in the main menu. You need to make one that goes in game where the problem would normally occur.

**Comment by cipitaua** [comment]
Actually the problem is well visible also in the main menu, see the third image in the first post.

**Comment by K0bin** [comment]
![image](https://user-images.githubusercontent.com/1131720/134974670-ebe59ce1-4ec6-43c5-817d-7a89b8fde594.png)

Can't tell whats wrong here.

**Comment by cipitaua** [comment]
Yes it looks correct. With driver you mean libvulkan_intel.so or the xorg modesetting driver? Where should I bug report? thank you

**Comment by K0bin** [comment]
Mesa Intel ANV

**Comment by cipitaua** [comment]
bug filed
https://gitlab.freedesktop.org/mesa/mesa/-/issues/5421

**Comment by K0bin** [comment]
I'm gonna close this then. Feel free to reopen if it does turn out to be a DXVK bug after all.

**Comment by K0bin** [comment]
Please reupload the apitrace. The demo doesn't work for me.

**Comment by K0bin** [comment]
Pretty sure it is a driver bug.
