### ISSUE TITLE
 STATE_CACHE_PATH environment variable disable cache

### ISSUE THREAD

**Issue by Bxaa** [doitsujin/dxvk#2310]
The following environment variable if used just make a empty folder and disable cache (cache not create)
DXVK_STATE_CACHE_PATH=/some/directory

(Windows)

**Comment by doitsujin** [comment]
I have no idea what any of this is supposed to mean, but DXVK does **not** create the directory if it doesn't already exist.

**Comment by doitsujin** [comment]
It doesn't disable the cache.
