### ISSUE TITLE
[d3d9] Euro Truck Simulator: Weird black rendering

### ISSUE THREAD

**Issue by HunterCZ122** [doitsujin/dxvk#2312]
### Software information
Euro Truck Simulator, D3D9 SM 3.0
Screenshots are self explanatory, some weird rendering going on.

DXVK:
![dxvk](https://user-images.githubusercontent.com/23011428/134815231-5a7e606a-365a-4a6e-ae25-88afc2ca15b8.png)
![dxvk2](https://user-images.githubusercontent.com/23011428/134815520-5d4eb628-eb94-41d8-8a57-8d34e51982fd.png)

WineD3D:
![wined3d](https://user-images.githubusercontent.com/23011428/134815246-10971eca-4b23-4b57-babf-294f27e38fa3.png)
![wined3d2](https://user-images.githubusercontent.com/23011428/134815443-11fe5873-6b3d-4c10-b900-991d6753d4d6.png)

### System information
- GPU: NVIDIA GeForce GTX 1660 Ti
- Driver: 470.62.02
- Wine version: Proton Experimental
- DXVK version: v1.9.2

### Apitrace file(s)
- https://drive.google.com/file/d/1tkXJhBGzQyp-sUM7OW2fWcnxu78Qtqdf/view?usp=sharing (captured with WineD3D)

### Log files
- d3d9.log: [game_d3d9.log](https://github.com/doitsujin/dxvk/files/7231681/game_d3d9.log)

**Comment by K0bin** [comment]
The vertex shader uses the LIT instruction with negative inputs. DXVK implements this with POW which is undefined on negative inputs and produces NANs for the tex coord.

**Comment by SegoItCh** [comment]
So how to fix it? I have same issue for Fallout 4 on Windows

**Comment by K0bin** [comment]
The issue in Euro Truck was fixed by us and it'll just work with any somewhat recent DXVK build.

Fallout 4 is a different game that uses a different graphics API. It's completely unrelated. If you want us to take a look, open a new issue and provide the necessary information (logs & apitrace).
