### ISSUE TITLE
Fallout New Vegas: Antialiasing White Dot Flickers

### ISSUE THREAD

**Issue by cheesemanhugs** [doitsujin/dxvk#2319]
When using Dxvk I get these white dots that pop up during gameplay randomly. They don't appear all the time but its enough to be annoying. They usually appear on creatures and npcs. I only get this issue when the games antialiasing is set to the max (8x). I can replicate the issue consistently by killing the fire ants around vault 11. Their bodies start to have the white spot flicker after killing a few. 

Ps: Tried my best to make an apitrace but kept running across issues. Used the pre made apitrace files. Whenever I put the d3d9.dll file in my root folder I get an assertion failed error when starting the game. Ignoring it starts the game fine (at a very low fps might I add) but I cant replicate the white dot flicker with the apitrace dll. Also, I tried using the dxvk dll instead but that stopped the apitrace file from being created at all.

### Software information
Fallout New Vegas. Max Settings. Bloom, HDR, Vsync off. Using Reshade Shaders (tested without reshade. Had same issue)

### System information
- GPU: GTX 2080ti
- Driver: Latest Nvidia Drivers
- Wine version: Not using
- DXVK version: 1.9.2

### Log files
- d3d9.log: 
[FalloutNV_d3d9.log](https://github.com/doitsujin/dxvk/files/7255604/FalloutNV_d3d9.log)

**Comment by Leopard1907** [comment]
> I can replicate the issue consistently by killing the fire ants around vault 11. Their bodies start to have the white spot flicker after killing a few.

Does it happen on native D3D9? 

Sharing a save file where people won't struggle that much to reach those ants might be a good start.

**Comment by K0bin** [comment]
Please add an apitrace, your save game and some screenshots.

**Comment by cheesemanhugs** [comment]
> > I can replicate the issue consistently by killing the fire ants around vault 11. Their bodies start to have the white spot flicker after killing a few.
> 
> Does it happen on native D3D9?
> 
> Sharing a save file where people won't struggle that much to reach those ants might be a good start.

I tried with native d3d9 (reshades d3d9). Didn't get the issue. Ill also record a vid as late as tomorrow

**Comment by cheesemanhugs** [comment]
> Please add an apitrace, your save game and some screenshots.
> 
> > I cant replicate the white dot flicker with the apitrace dll.
> 
> That's normal. We will be able to replay that apitrace with DXVK later and probably see the problem. Very low FPS is also to be expected.

Link to a folder that contains a video example, apitrace, save file, and the logs I got when using the apitrace if that's needed.
https://www.mediafire.com/file/rc1vvhcxbht5nu4/Dxvk+Sparkle+bug.7z/file

Also I was having a harder time getting the issue to happen when I tested without most all my mods. That being said the issue still happened. Just keep in mind that the issue was most likely amplified by something I had installed (for the save file and vid I uninstalled all my mods except essential stabilizers like nvtf and anti crash. I did indeed test without any mods at all and still got the issue)

**Comment by Blisto91** [comment]
Can any of you see if it's still a issue with the latest drivers and dxvk.

**Comment by Blisto91** [comment]
Okay i tried the save game on linux. nvidia 960, dxvk 1.9.2 & various driver versions with the oldest one being 470.74. I was not able to reproduce it after several attempts. This was with highest settings and no mods.
Next test would be on windows i guess. Tho i will not be downgrading drivers there as the windows setup on the same pc is not my own. Not sure when i will have time for it.

**Comment by Blisto91** [comment]
@cheesemanhugs @urmamphat Friendly ping.

**Comment by Blisto91** [comment]
Just as fyi i tried reproducing this again. Still nothing. One of the times with reshade.
Also didnt reproduce when i tried on windows. But as said i didn't downgrade my driver's there

**Comment by Blisto91** [comment]
If any of you still see this issue with latest master then write here again

**Comment by whinix** [comment]
> If any of you still see this issue with latest master then write here again

I still have that issue. Saw people on reddit posting about that too. Lowering anti-aliasing to 4x and 2x does not help. Switching HDR off does eliminate it but the game looks terrible without it. 

It's mostly on creatures, especially bloatflies, geckos. Less visible on humans. Looks bad on the NCR ghouls.  

![ScreenShot2](https://user-images.githubusercontent.com/60192589/191988577-e7110a92-c7e4-4d19-a6a6-36b253579491.jpg)

Not a game breaking issue but annoying when it happens

**Comment by Blisto91** [comment]
Please post dxvk logs or your pc specs and drivers. Which dxvk versions have you tested?
Also it would be really really great you we're able to to capture this with apitrace https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

**Comment by whinix** [comment]
> Please post dxvk logs or your pc specs and drivers. Which dxvk versions have you tested? Also it would be really really great you we're able to to capture this with apitrace https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

I'm attaching the log, i'll check the apitrace later

[FalloutNV_d3d9.log](https://github.com/doitsujin/dxvk/files/9634953/FalloutNV_d3d9.log)

**Comment by Blisto91** [comment]
You driver is very old. Could you try updating it and then checking with latest master? :slightly_smiling_face: 
You can grab a build here. https://github.com/doitsujin/dxvk/actions/runs/3112725862 
You need relatively up to date drivers to use it

**Comment by whinix** [comment]
> 

I updated the drivers and used the build you linked. It's still there and i feel like the game is more stuttery when combat starts

[FalloutNV_d3d9.log](https://github.com/doitsujin/dxvk/files/9635143/FalloutNV_d3d9.log)

![Clipboard01](https://user-images.githubusercontent.com/60192589/192000764-713c8b8c-0363-4a4d-9f1d-5f880fdff566.jpg)

**Comment by Blisto91** [comment]
Thanks for testing

**Comment by whinix** [comment]
> Thanks for testing. Hopefully you'll be able to capture a apitrace. Since you are on windows you are by default not gonna be tracing with dxvk at the same time so the issue won't show itself when you do it. But just do what you would normally do to reproduce it anyway, we can then replay it along with dxvk to see if anything sticks out.

here's my trace file: https://www.mediafire.com/file/ahsafsn1s9nwfpq/FalloutNVtrace.7z/file

i tried to quickly massacre a bloatfly with a riot shotgun and then hit the corpse - that produces the most flickering in the game for me

**Comment by Blisto91** [comment]
Thanks i see the issue in the trace. Theres colored dots appearing near the end with dxvk and wined3d (latter being a linux thing).
When i replay it natively on Windows i also see some white flashes/dots that come up sometimes. Is that normal and something you see in the native game too?

**Comment by K0bin** [comment]
If you made the trace on Windows, did you see the white dots when you made the trace?

**Comment by whinix** [comment]
> 

the white flashes (always associated with blood events) are only with dxvk, never in native game.


> If you made the trace on Windows, did you see the white dots when you made the trace?

no, you cant see it when you do the trace on windows

**Comment by Blisto91** [comment]
Are you able to provide a save game from the same location?
Wanna test a bit and see what i can find.

**Comment by whinix** [comment]
> Are you able to provide a save game from the same location? Wanna test a bit and see what i can find.
> 
> Edit: This is what i see on native d3d9 with the trace https://www.reddit.com/r/fnv/comments/asree9/help_hdr_anti_aliasing_causes_this_visual_glitch/ It seems this can be a issue with the game when HDR + AA. At least for older drivers. But yes it seems dxvk does add something extra here

the location doesn't matter, just find any bloatfly and hit the corpse, the bigger the caliber the more flickering happens (shotguns are "good"). 

Yes, when i disable HDR the issues disappears (while still using dxvk). HDR+AA is fine when using the native game.

**Comment by whinix** [comment]
> Edit: This is what i see on native d3d9 with the trace https://www.reddit.com/r/fnv/comments/asree9/help_hdr_anti_aliasing_causes_this_visual_glitch/ It seems this can be a issue with the game when HDR + AA. At least for older drivers. But yes it seems dxvk does add something extra here

I have disabled AA and without it the issue is gone. The reddit post describes a different case though, for me the flickering is only on blood decals, not anywhere else. It's not random like described there.

**Comment by Blisto91** [comment]
I am reproducing white flashes on the fly blood decals in the native d3d9 game on windows on my R9 380 amd card. dxvk doesn't seem to make the issue worse or colors appear.
Will test on Nvidia here later

**Comment by Blisto91** [comment]
So yes i am not reproducing  on native Nvidia, but do reproduce with dxvk + nvidia. I am starting to think this might actually be a game bug that the native Nvidia driver just works around since this happens on my native amd system and also from looking at old forum topics.
Tho i am not sure since i don't have technical insight to look into it.

**Comment by K0bin** [comment]
Forcing centroid for texture coord pixel shader inputs fixes the issue but that's not a correct fix.

**Comment by vlad54rus** [comment]
Reproducible on Nvidia after removing FalloutNV.exe from their driver profile, looks like Nvidia applies certain fixes to avoid this issue. 100% game bug.

**Comment by GnomeBeans** [comment]
I had a similar issue when setting up a modded play through on linux while using proton. At first I disable msaa and the white dots I was seeing went away. Ultimately what fixed for me was to replace my wine prefix d3d9.dll with those from dxvk then in winecfg set to d3d9 native, builtin. I'm on radv btw.
