### ISSUE TITLE
86148ec0: "Implement DXVK pieces required for DX11 DLSS support" Breaks Origin

### ISSUE THREAD

**Issue by gardotd426** [doitsujin/dxvk#2321]
### Software information
Origin crashes using current master of DXVK. 1.9.2 works. After bisecting I found that "86148ec070628f5a89fbb0a91603bae2ce89529a:  Implement DXVK pieces required for DX11 DLSS support" is the offending commit. Reverting it fixes the issue

### System information
- GPU: Nvidia RTX 3090
- Driver: 470.74
- Wine version:  All wine versions after 6.6
- DXVK version: Current master

### Apitrace file(s)
[Origin.4.trace.tar.gz](https://github.com/doitsujin/dxvk/files/7266989/Origin.4.trace.tar.gz)

### Log files
- d3d9.log: [Origin_d3d9.log](https://github.com/doitsujin/dxvk/files/7266926/Origin_d3d9.log) 
- d3d11.log: [Origin_d3d11.log](https://github.com/doitsujin/dxvk/files/7266929/Origin_d3d11.log)
- dxgi.log: [Origin_dxgi.log](https://github.com/doitsujin/dxvk/files/7266931/Origin_dxgi.log)

**Comment by doitsujin** [comment]
Do other 32-bit apps work or is it only Origin?

**Comment by gardotd426** [comment]
Battle.Net works. Not sure if Ubisoft Connect is 32-bit or not, but it works as well. I know Battle.Net is 32-bit, though, and it works fine.

**Comment by doitsujin** [comment]
Fixed on master.
