### ISSUE TITLE
Assassin's Creed Origins DXVK not starting in NEW AMD GPU RX 6600 XT with driver 21.9.2 at DXVK 1.9.2

### ISSUE THREAD

**Issue by z3wi** [doitsujin/dxvk#2322]
Hello Everyone hope doing fine and healthily

I have a big issue in Assassin's Creed Origins game  in RX 6600 XT  GPU at AMD driver 21.9.2 ( latest one )...the game wont run in DXVK i have a black screen after Intro videos especialy in game menu and game not running anymore

i dont know if the DXVK version 1.9.2 is compatible with the latest AMD radeon driver 21.9.2

any help or suggestion will be much appreciated

### Software information
Game ; Assassin's Creed Origins 
Everything's on Very high
Monitor ; Borderless windows
Sync ; off
Resolution ; 1920x1080 (Native)

### System information
- GPU: RX 6600 XT
- Driver: AMD Radeon 21.9.2
- Wine version: Windows 10 Pro
- DXVK version: 1.9.2

### Apitrace file(s)
- Put a link here

### Log files
( i tryed to start game withoout D3D9.dll but its same not working )
[ACOrigins_d3d9.log](https://github.com/doitsujin/dxvk/files/7273368/ACOrigins_d3d9.log) 
[ACOrigins_d3d11.log](https://github.com/doitsujin/dxvk/files/7273369/ACOrigins_d3d11.log)
[ACOrigins_dxgi.log](https://github.com/doitsujin/dxvk/files/7273370/ACOrigins_dxgi.log)

**Comment by doitsujin** [comment]
Another day, another Windows-specific issue that I *really* don't care about.

Try switching to borderless window instead of fullscreen mode, if that doesn't work, you're on your own.

**Comment by z3wi** [comment]
Thank you for your reply buti tryed it before testing all Monitor mods ( fullscreen ,windowed,bordeless) nothing work im pretty sur the probleme caused by the driver but i hope if someone had the same probleme and can suggest me a solution
