### ISSUE TITLE
Guild wars 2 DX11 mode doesn't work with DXVK

### ISSUE THREAD

**Issue by RyzenDew** [doitsujin/dxvk#2324]
Tried Running Guild wars 2 in DX11 mode with newest DXVK on Nvidia Drivers 510.10 and newest game ready drivers on windows 10 and windows 11 RTM and windows 11 insider

same result everytime also added log if you need more info let me know how
![image](https://user-images.githubusercontent.com/84041391/136130971-1fc54c37-e654-4400-8563-6a5a394c92f0.png
[Gw2-64_d3d11.log](https://github.com/doitsujin/dxvk/files/7290420/Gw2-64_d3d11.log)
)

**Comment by DxCx** [comment]
I was successfully running both dx9 and dx11 gw2 with dxvk..
A. Did u ensure dx9 version works locally? (so you know vulkan is setup correctly)
B. Did u also copy dxgi.dll?
C. For Dx9 dlls need to be in gw2/bin64, for dx11 it should be in gw2/

Btw ive found out that as for now, dx9 dxvk version runs the best (out of dx9, dx11, and dx11vk), dx11vk one gives me around 10 less fps and Abit more stuttering, i hope that anet will improve dx11 in the future and it will run better xD

**Comment by doitsujin** [comment]
The game is known to work with DXVK, it probably loads dxgi.dll from system32 or you just forgot to copy it or something.

**Comment by J0s3f** [comment]
Is there any way to prevent it from loading dxgi.dll from system32?

**Comment by Squall-Leonhart** [comment]
DX11 does not work with DXVK,

![image](https://user-images.githubusercontent.com/1098176/176653004-6fdf24e9-8c96-40f5-8a40-238067b8271a.png)

**Comment by K0bin** [comment]
> Delete the dxvk version of the d3d9 file from the bin64 folder in order to use dxvk with d3d11

That's just wrong. If the game decides to use D3D9, it will just use your normal d3d9 driver (because you deleted DXVK after all). If it decides to use D3D11, deleting d3d9.dll has absolutely no effect.

**Comment by Squall-Leonhart** [comment]
DXVK's D3D9 file in /bin64/ prevents GW2 from loading the D3D11 and DXGI files from the root directory when the game is configured to D3D11, the game is loading the D3D9 file into the launcher and breaking the DLL search order.

**Comment by Gazareth** [comment]
@Squall-Leonhart How did you get this to work?

I'm getting this same problem as OP and I've tried deleting all dxgi/d3d9/d3d11 files from both the root folder and /bin64/, starting from scratch with dxvk today. Using the resource monitor, it always seems to be associated with d3d9 and dxgi from /System32/, unless I put dxvk's d3d9 into /bin64/ at which point it _will_ use that and vulkan will load, but I'll be on d3d9->vk 😩

I really want to use d3d11->vk because dx11 performace has really come a long way in GW2 and I'm hoping that will translate into vulkan and push it even higher.

**Comment by Squall-Leonhart** [comment]
dxvk's d3d11 and dxgi go into the same folder as gw2-64.exe, nothing goes into bin64.

**Comment by Gazareth** [comment]
Yeah I am doing that, I just tested out the dx9 version of vk in order to verify that at least _that_ would work. It does, but dx11 doesn't.

Interestingly if I install the dx11 version of reshade, that works, and resouce monitor says it's using the dxgi in the gw2 root folder.

Trying dxgi from dxvk just causes the same crash as shown by OP:

![image](https://user-images.githubusercontent.com/11911259/187297204-3ae94bf1-a459-4817-937e-d12bf7e4b94e.png)

I wondered if it was something on my PC, I uninstalled a couple of overlay programs that were showing up, and also deleted everything in the GW2 folder. Could it be that my GW2 is not installed in /Program Files/?

**Comment by Squall-Leonhart** [comment]
you need  both the dxgi and the d3d11 file.

**Comment by Gazareth** [comment]
Yep got that as well.

Here's my GW2 root folder:

![image](https://user-images.githubusercontent.com/11911259/187298630-db2fc299-0b80-4e96-a6e6-cbfc011974eb.png)

And my /bin64/

![image](https://user-images.githubusercontent.com/11911259/187298778-770dd78a-6793-4b95-8466-86f6652b5044.png)

And I'm getting that error when I try to load up the DX11 mode of GW2

**Comment by Squall-Leonhart** [comment]
it could be due to being blocked on the file properties.

**Comment by RyzenDew** [comment]
It just doesn’t work as said it should it errors out I’ve tried everything also and nothing works but my performance is amazing with dx11 now Sent from my iPhoneOn Aug 29, 2022, at 6:30 PM, Squall Leonhart ***@***.***> wrote:﻿
it could be due to being blocked on the file properties.

**Comment by Squall-Leonhart** [comment]
more than likely this https://reverseengineering.stackexchange.com/questions/29872/program-doesnt-load-a-custom-dll-from-main-directory-how-can-i-inject-a-dll

**Comment by Gazareth** [comment]
Thanks for that. Lots of info there. I'm not in a position to create a launcher, (GW2 has one anyway, so not sure if that would work), but I did try some of the DLL redirect stuff out. No beans.

The fact that GW2 will load Reshade's dxgi suggests it's capable of loading custom dll's. I'm wondering if it's specifically the d3d11 that it won't load or doesn't like for some reason.

@Squall-Leonhart  are you able to get yours to load on the latest GW2 and dxvk? Just want to make sure they haven't introduced a hard-coded path to d3d11 in a later version of GW2.

**Comment by Sildurs-shaders** [comment]
Manually patching the Gw2-64.exe file to load d3d11.dll works but it's not optimal in case of updates.

**Comment by SourceRyan** [comment]
> Manually patching the Gw2-64.exe file to load d3d11.dll works but it's not optimal in case of updates. UPDATE: For some reason d3d9.dll is being loaded from the base64 folder, modding it to load d3d11.dll also in the bin64 folder works and the game runs in vulkan mode without the need of modifying the exe files directly.

Any chance you could provide that modded DLL? I'm running into the same issues as described above on every device I test with.

**Comment by Espionage724** [comment]
I put `d3d11.dll` and `dxgi.dll` in the root GW2 folder (next to `Gw2-64.exe`) and `d3d9.dll` in the `bin64` folder (next to `CoherentUI_Host.exe`).

GW2 starts in D3D11 mode and runs through DXVK for me on Windows 10 and I don't have to modify the exe or use an injector.

**Comment by SourceRyan** [comment]
This issue is still occurring for me, and the SelectRenderer workaround doesn't seem to fix it anymore. Specifically, DX11 will fail to initialize the 3D renderer, and will fall back to the DX9 renderer, which works.

**Comment by Blisto91** [comment]
Coherent UI will be replaced in the game sometime here in Q1. Might make things eas

**Comment by K0bin** [comment]
@SourceRyan On Linux or on Windows? Can you post a fresh set of DXVK logs?

**Comment by SourceRyan** [comment]
This is on Windows. Here are the logs:
[Gw2-64_d3d11.log](https://github.com/doitsujin/dxvk/files/10508918/Gw2-64_d3d11.log)
[Gw2-64_d3d9.log](https://github.com/doitsujin/dxvk/files/10508919/Gw2-64_d3d9.log)

**Comment by K0bin** [comment]
If it's on Windows, there's probably nothing we can do about it.

**Comment by Squall-Leonhart** [comment]
under windows 10 you need to mess with knowndll's a bit to get dxvk loaded by guildwars 2.

**Comment by SourceRyan** [comment]
> under windows 10 you need to mess with knowndll's a bit to get dxvk loaded by guildwars 2.

Any links, suggestions, or tips on how to go about doing that? I tried searching but I haven't seen much discussion of working with KnownDLLs in regards to DXVK or Guild Wars 2

**Comment by Espionage724** [comment]
> This issue is still occurring for me, and the SelectRenderer workaround doesn't seem to fix it anymore. Specifically, DX11 will fail to initialize the 3D renderer, and will fall back to the DX9 renderer, which works.


DXVK works fine for me with GW2 today on Windows 10 21H2:

![Image](https://i.imgur.com/5Yeh11L.jpg)

`d3d11.dll` and `dxgi.dll` in the root GW2 folder next to `Gw2-64.exe`, and `d3d9.dll` in `bin64` folder. I'm not using KnownDlls or anything special afaik, but I do have UAC disabled. I'm using DXVK 1.10 with an older AMD graphics driver.

**Comment by SourceRyan** [comment]
For what it's worth, all of the devices I have access to and have tested on have been either Nvidia or Intel integrated graphics. I'll have an AMD device available in a few weeks and can see if that makes any difference.

**Comment by Blisto91** [comment]
The newest update makes the game use CEF (Chromium Embedded Framework) instead of CoherentUI by default so this might work better now if it is of interest.

**Comment by Espionage724** [comment]
So this was fun to figure out :p 

- `x64` DXVK dlls
- `d3d11.dll` to root GW2 folder (next to `Gw2-64.exe`)
- `d3d9.dll` to `bin64\cef` folder (next to `CefHost.exe`)
- `dxgi.dll` to `bin64\cef` folder (next to `CefHost.exe`)
- `dxvk.conf` to root GW2 folder (next to `Gw2-64.exe` for async/hud/etc configs)

**Comment by djsolarix** [comment]
> So this was fun to figure out :p
> 
> * `x64` DXVK dlls
> * `d3d11.dll` to root GW2 folder (next to `Gw2-64.exe`)
> * `d3d9.dll` to `bin64\cef` folder (next to `CefHost.exe`)
> * `dxgi.dll` to `bin64\cef` folder (next to `CefHost.exe`)
> * `dxvk.conf` to root GW2 folder (next to `Gw2-64.exe` for async/hud/etc configs)

Tried this, still errors out. Oddly I noticed it gets stuck on "Initializing" while the splash screen is loading before login but the results are still the same after trying to hit play. "Unable to Initialize 3D Output...."

**Comment by brittyazel** [comment]
> So this was fun to figure out :p
> 
> * `x64` DXVK dlls
> * `d3d11.dll` to root GW2 folder (next to `Gw2-64.exe`)
> * `d3d9.dll` to `bin64\cef` folder (next to `CefHost.exe`)
> * `dxgi.dll` to `bin64\cef` folder (next to `CefHost.exe`)
> * `dxvk.conf` to root GW2 folder (next to `Gw2-64.exe` for async/hud/etc configs)

Are you on Nvidia by any chance? For AMD GPUs all that is necessary to get DXVK working is putting `d3d11.dll` and `dxgi.dll` in the root of the GW2 folder. No modifications are necessary to the bin64/cef folder. 

One interesting thing that I see when looking inside bin64/cef is that there's bundled vulkan .dll files included by default, so I wonder if on AMD GPUs when using DXVK Chromium is natively rendering using Vulkan. That would be wild if so.
