### ISSUE TITLE
TES IV Oblivion Windowed Mode - Failed to Create Surface

### ISSUE THREAD

**Issue by MalonnBethesda** [doitsujin/dxvk#2325]
I can't launch Oblivion in windowed mode.  It runs fine in full screen.  It also runs fine in windowed mode without DXVK.  It's a clean installation, no mods.  I am launching it through Lutris.  I've tried without, but it still crashes.  I can't offer many troubleshooting steps because I haven't been able to find much online to guide me.

GTX 1080
Driver: 470.63.01-0ubuntu0.20.04.2
Wine is 6.18 development
DXVK is 1.9.2

A search engine turned up little specific to my issue

[Oblivion_d3d9.log](https://github.com/doitsujin/dxvk/files/7293492/Oblivion_d3d9.log)
.

**Comment by Joshua-Ashton** [comment]
Needs child window patches.

**Comment by MalonnBethesda** [comment]
In Lutris, I've set an environemnt variable named "_childwindow_fix" and set it's value to true (and "true" with quotes), as well as set a command prefix name "_childwindow_fix="true"" and the game still crashes.

Do I need to download something?  A quick search doesn't turn up much more than the command.

**Comment by MalonnBethesda** [comment]
I read that the default wine (from WineHQ) does not support child windows.  That's the Wine I was using.  I hear wine-tkg supports child windows.
Is there a way to add child window support into the vanilla Wine?

**Comment by Joshua-Ashton** [comment]
Not without recompiling it.
