### ISSUE TITLE
DXVK: No adapters found

### ISSUE THREAD

**Issue by alvinhanaji** [doitsujin/dxvk#2328]
Not sure if this is the right place but, I'm on a RK3399 with mali-T860 on a devterm, but getting an issue not being able to run anything. Even after installing all drivers for both arm64 as well as armhf, still getting issues of

Required Vulkan extension VK_KHR_surface not supported or DXVK: No adapters found with D3DllCreateDevice: No default adapter found.

Also I get a lot of D3DllCreateDevice: Failed to create a DXGI factory errors in general with a lot of games, was wondering if you had any tips or advice? Was wondering if maybe I installed things in a wrong order as well.

**Comment by IsaacMvmv** [comment]
try to run vkcube, vkmark... to check if your gpu supports vulkan/has vulkan drivers installed

**Comment by Blisto91** [comment]
@alvinhanaji Friendly ping. Did you ever figure this out?

**Comment by K0bin** [comment]
Closing this because there's nothing we can do about it anyway.
