### ISSUE TITLE
1.9.2 breaks shadows in Payday 2 on windows, 1.9.1 works fine.

### ISSUE THREAD

**Issue by MatthewCAbel** [doitsujin/dxvk#2331]
### Software information
Shadows were on high on my first test, but changing the setting didn't do anything
Screenshot of 1.9.2: https://imgur.com/a/egJQLld
Screenshot of 1.9.1: https://imgur.com/a/nlt7GLY

### System information
- GPU: Nvidia GTX 1660
- Driver: 496.13
- Wine version: N/A
- DXVK version: 1.9.2

### Apitrace file(s)
- https://mega.nz/file/jdhijSYZ#a4BcQ5Et4wTLvdYJ1ukWq65TbDp3nrFxbLBi3Ohpqj4

### Log files
- d3d9.log: https://pastebin.com/bn9V8z78
- d3d11.log:
- dxgi.log:

**Comment by K0bin** [comment]
Please check the latest master. Black Mesa had a similar regression and that was already fixed. So hopefully it's the same for Payday 2.
