### ISSUE TITLE
GTA IV dies randomly

### ISSUE THREAD

**Issue by CraezyDud** [doitsujin/dxvk#2333]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

Gta iv dies randomly while playing, only on dxvk
whole video memory seems to corrupt, looks horrible

>**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include >log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
>In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
>In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
>Preferably record the trace on Windows, or wined3d if possible.
>
>**Reports with no log files will be ignored.**

i think it could break my card while testing, the effects are horrible, i have to force shut down too (pls dont hurt me)

### Software information
GTA IV: COMPLETE EDITION

### System information
- GPU: Radeon RX Vega 64
- Driver:
- Wine version: proton experimental
- DXVK version: 

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by CraezyDud** [comment]
but thats what it is
just while playing
https://www.protondb.com/app/12210
check out some other reports

**Comment by K0bin** [comment]
You didn't even mention your driver version or the DXVK version.

**Comment by CraezyDud** [comment]
mesa, up to date, using dxvk from proton experimental

**Comment by CraezyDud** [comment]
also, changing settings kills it too

**Comment by K0bin** [comment]
> mesa, up to date

That just means that the exact version you're using depends on your distro which conveniently you didnt mention either.

**Comment by CraezyDud** [comment]
how do i check, i'm on arch
stay calm

**Comment by CraezyDud** [comment]
i think it crashed on reflection and shadow

**Comment by K0bin** [comment]
I just played the game for 15 minutes and changed the graphics settings (including reflection and shadows).

Didn't crash for me.

**Comment by CraezyDud** [comment]
did you use any launch flags, if yes, which

**Comment by K0bin** [comment]
> i also alt+tabbed multiple times
the game has issues with that

Yeah, I wasted hours trying to find out whats going on there. No dice. That's not going to get fixed any time soon.

> did you use any launch flags, if yes, which

None

**Comment by CraezyDud** [comment]
did it die when you alt tabbed

**Comment by CraezyDud** [comment]
everything looks soooo trippy afterwards
like gpu mem real overloaded with stuff

**Comment by CraezyDud** [comment]
okay, i tried using amdvlk instead of mesas amd vulkan driver, same issue

**Comment by CraezyDud** [comment]
i had `lib32-amdvlk` installed, it seemed to have used that instead of `lib32-vulkan-radeon`
which tells me, its a `lib32-amdvlk` issue, because with just `lib32-vulkan-radeon` installed, it worked nicely

**Comment by CraezyDud** [comment]
i'll say if there are any more problems
