### ISSUE TITLE
OCCT doesn't render correctly

### ISSUE THREAD

**Issue by Evernow** [doitsujin/dxvk#2334]
When running OCCT with hardware rendering enabled, it doesn't render properly (as can be seen in the apitrace), it is completely black unless you resize the window, which then allows you to see the menus for a split second.

WineD3D and Windows allow you to run OCCT and replay the Apitrace fine in my testing.

### Software information
OCCT, a free software to test system stability (Windows exclusive, possible to run via Wine) , I fully know it's pointless to run this in Linux, but I am simply reporting this since it seems like an actual bug.

### System information
- GPU: RTX 3080 & UHD 630
- Driver: 496.13 (Windows) & Mesa 21.2.3
- Wine version: Wine 6.16
- DXVK version: 1.9.2

### Apitrace file(s)
Recorded on Windows, at least in my testing it's replayable in Wine with WineD3D (does not exhibit the issue) and DXVK.

https://drive.google.com/file/d/1HxM1mihAio_rt3a8aKgMMD0jUdk0I-6L/view?usp=sharing

### Log files
Will add these momentarily 

- d3d9.log:
[OCCT(3)_d3d9.log](https://github.com/doitsujin/dxvk/files/7358583/OCCT.3._d3d9.log)
- d3d11.log: This would not get generated 

- dxgi.log:
[OCCT(3)_dxgi.log](https://github.com/doitsujin/dxvk/files/7358584/OCCT.3._dxgi.log)

**Comment by doitsujin** [comment]
This requires partial presentation, which we cannot support in any reasonable way at the moment.

**Comment by Ryusennin** [comment]
Looks like a similar problem to GravityMark?

**Comment by Blisto91** [comment]
@Evernow Hi there. If you are still around would you be able to check this out again with PR https://github.com/doitsujin/dxvk/pull/3392 ?
You can find a build of it here https://github.com/doitsujin/dxvk/actions/runs/4893877539

**Comment by Blisto91** [comment]
Finally got the original app running now. I'm not seeing the issue with the version from back when this issue was made. The newest version wont launch but that isn't a dxvk issue
