### ISSUE TITLE
[d3d9] Payday 2 doesn't start up

### ISSUE THREAD

**Issue by gabsF** [doitsujin/dxvk#2336]
The game starts up with a black screen, after a few seconds it crashes, I even tested with the latest development build and still no results. Tested with 1.9.1, it also crashed.

While I was doing the trace part, the ``.trace`` file just got only 2 bytes, I'm guessing it won't help much? But I'm uploading it anyway.
A box text also appeared.
![image](https://user-images.githubusercontent.com/43124504/137636642-ef2a3c9e-e870-44b3-84b7-41a09a449ed4.png)
I've pressed "retry" and another box text appeared.
![image](https://user-images.githubusercontent.com/43124504/137636662-6b14980e-3240-4ee9-9a7e-5575b84781d0.png)
And the game closed itself.

### Software information
PAYDAY 2
The effects are turned off, graphics and shadows are on Low, frame rate limit on 45.
![image](https://user-images.githubusercontent.com/43124504/137635808-6c86efa3-9c1e-4e3e-957a-feb4e2b022b5.png)
Also, this image is without the d3d9.dll ;p

### System information
- GPU: AMD Radeon R7 M260
- Driver: 
- Wine version: 
- DXVK version: 1.9.2

### Apitrace file(s)
- https://drive.google.com/file/d/1xCPZFMtzFJC3zws5RmgshXLAnY7CzFhL/view?usp=sharing

### Log files
- d3d9.log: https://drive.google.com/file/d/1dWhgFPAZ7FSGJ4eu1uKDfykb-ch9CWrv/view?usp=sharing
- d3d11.log:
- dxgi.log:

**Comment by doitsujin** [comment]
The game is known to work, does 1.9 run?

**Comment by gabsF** [comment]
Tested with no overlays, no Steam, no Discord and no RivaTuner, even tested 1.8 versions and still no results.

**Comment by Evernow** [comment]
As per [the project wiki](https://github.com/doitsujin/dxvk/wiki/Driver-support)

> Unsupported. Any issues that are exclusive to Windows will be ignored.

**Comment by Evernow** [comment]
> That's only for D3D10/11. 9 is somewhat supported on Windows.

May want to update the wiki to reflect that

**Comment by Blisto91** [comment]
Also not able to reproduce this on my amd setup on windows using dxvk 1.9.2.

**Comment by Blisto91** [comment]
@gabsF Friendly ping. Are you still having this issue?

**Comment by gabsF** [comment]
Hi, sorry about late response.

Unfortunately, my game still doesn't start up, even with the most recent version, 1.10.1. :/
The current version I have from the Driver of AMD is 21.5.1.

Even with no Lua mods, it doesn't work.

**Comment by Evernow** [comment]
> Hi, sorry about late response.
> 
> Unfortunately, my game still doesn't start up, even with the most recent version, 1.10.1. :/ The current version I have from the Driver of AMD is 21.5.1.
> 
> Even with no Lua mods, it doesn't work.

Can you try this on a Windows clean install or Linux?

**Comment by Blisto91** [comment]
Actually could you try with with the latest unreleased master version? We just had some luck in the similar issue above.

You can grab a download of it here.
https://github.com/doitsujin/dxvk/actions/runs/2605265111

**Comment by HajimeSait0** [comment]
Afraid I have to chime in on this too, as my copy of Payday 2 sits at pre-loading blackscreen then crashes.
I don't recall what version of DXVK I was using prior to now when it was working, but I tried out 1.10.3 and 1.10.2 with the crash still occuring.

I'm downloaded WinDbg to parse the MDMP crash files in case they provide any insights, but they appear to be identical content to the crashlogs the game naturally generates. I have posted as many details as I can about my PC as well as the full contents of the crash log under DXVK 1.10.2 here https://pastelink.net/4v9whtz4

I hope I was helpful and I hope we can resolve this issue :)

**Comment by Blisto91** [comment]
@HajimeSait0 I'm gathering this on linux?

**Comment by HajimeSait0** [comment]
No, I commented in the pastelink that this was Windows 10 version 21H1 build 19043.1889

I am however embarrassed to admit that I just tried (one of?) the latest master builds I could get my hands on, and the game has currently successfully booted to main menu. The relevant build was located here https://github.com/doitsujin/dxvk/actions/runs/2852177417

I will edit this comment further if I have any additional trouble or seemingly Vulkan-related crashes. At least something that's changed has improved support with PD2. Sorry to bother you fine folks :)

**Comment by Blisto91** [comment]
Oh yea missed that. Just saw `VkLayer_steam_fossilize` and my mind went to linux. Nvm then :grin: 

Sounds good :+1:

**Comment by K0bin** [comment]
It's most likely crashing in an unrelated Vulkan layer. Try uninstalling Riva Tuner and any other overlay software.

**Comment by MilesFox92** [comment]
This also happens to me. It's been working fine last year and in march for me, but now the game just doesn't start on any version of the DXVK. Even without the RivaTuner
