### ISSUE TITLE
Fatal Frame Maiden of Black Water: OpenSharedResource Not implemented and Gst data stream errors

### ISSUE THREAD

**Issue by Mershl** [doitsujin/dxvk#2348]
### Description
Games renders out of window and shows long hangs/very low FPS.

![image](https://user-images.githubusercontent.com/520251/139291499-d461c6a5-3f81-4a71-8117-9bd9388f52f6.png)

### Software information
FATAL FRAME / PROJECT ZERO: Maiden of Black Water (1732190)

### System information
- GPU: RX6800
- Driver: mesa-git (27th of October)
- Wine version: 6.16-ge
- DXVK version: 1.9.2

### Log files
```
winegstreamer error: typefind: Internal data stream error.
winegstreamer error: typefind: ../src-gstreamer/plugins/elements/gsttypefindelement.c(1232): gst_type_find_element_loop (): /GstBin:bin27/GstDecodeBin:decodebin27/GstTypeFindElement:typefind:
streaming stopped, reason error (-5)
err:   D3D11Device::OpenSharedResource: Not implemented
```
Full log: [fatalframe5_dxvk192.log](https://github.com/doitsujin/dxvk/files/7435643/fatalframe5_dxvk192.log)

**Comment by dlove67** [comment]
@Mershl I believe this is fixed with [this pull request](https://github.com/doitsujin/dxvk/pull/2516). I can get in game successfully with Proton Bleeding Edge (though videos still need to be transcoded).
