### ISSUE TITLE
Anno 1800 random crashes with "Unespected DirectX error" and VK_ERROR_DEVICE_LOST

### ISSUE THREAD

**Issue by juliotux** [doitsujin/dxvk#2349]
Anno 1800 randomly crashes after some time of game play. The time or action this occurs seems to be random. When it freezes and crash, a small window pops up like the screenshot bellow.

This problem happens with DX11 and DX12.

![Screenshot from 2021-10-31 17-32-30](https://user-images.githubusercontent.com/497246/139702787-874cc25f-7dff-41ee-a5ec-6c07dc1aca03.png)

It also show some messages in the terminal:

```
err:   DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
err:   DxvkSubmissionQueue: Command submission failed: VK_ERROR_DEVICE_LOST
wine: Unhandled page fault on read access to FFFFFFFFFFFFFFFF at address 0000000142D6B52D (thread 04a4), starting debugger...
```

### Software information
Anno 1800 from Ubisoft Connect using Proton Experimental

### System information
- GPU: NVidia RTX 2060
- Driver: 470.74
- Wine version: Proton 6.3-7 (Experimental)
- DXVK version: 1.9.2

### Log files
- d3d9.log: empty
- d3d11.log: [Anno1800_d3d11.log](https://github.com/doitsujin/dxvk/files/7454515/Anno1800_d3d11.log)
- dxgi.log: [Anno1800_dxgi.log](https://github.com/doitsujin/dxvk/files/7454518/Anno1800_dxgi.log)

**Comment by doitsujin** [comment]
Can't reproduce, game works fine on my system

**Comment by juliotux** [comment]
@doitsujin investigating it a bit more I found that this problem also appear for some users in Windows. So, it seems to be a Anno bug.
[Bug in Ubisoft forum](https://forums.ubisoft.com/showthread.php/2258178-Anno-1800-crashes-and-says-quot-an-unexpected-Directx-error-occurred-Present-failed-quot/page7)

**Comment by lokok8** [comment]
I can confirm that this bug happens on Windows. It occured often to some of my friends in Online play - all using Windows. One of them has a 5600XT so doesnt appear to be Nvidia specific.
