### ISSUE TITLE
IronCAD 2019 does not work with DXVK 1.9.2

### ISSUE THREAD

**Issue by andyholst** [doitsujin/dxvk#2351]
Following things were given:

HOME_PATH="/home/ubuntu"
WINE_PATH="${HOME_PATH}/.ironcad"
ARCHITECTURE="win64"
WINE="wine64"

I executed following commands:

```
WINEPREFIX="${WINE_PATH}" WINEARCH="${ARCHITECTURE}" winetricks -q dxvk
WINEPREFIX="${WINE_PATH}" WINEARCH="${ARCHITECTURE}" winetricks -q win10

WINEPREFIX="${WINE_PATH}" WINEARCH="${ARCHITECTURE}" ${WINE} IronCADDCS2019_x64.exe

WINEPREFIX="${WINE_PATH}" WINEARCH="${ARCHITECTURE}" ${WINE} \
"${WINE_PATH}"/drive_c/Program\ Files/IronCAD/2019/bin/IRONCAD.exe
```

Downloading the IronCADDCS2019_x64.exe can be problematic with Wine since the exe file installer requires dependencies that I've not figured out yet. I just got the IronCADDCS2019_x64.exe through VirtualBox through Windows. Download link is https://community.ironcad.com/index.php?/files/file/13-ironcad-2019-release-version/

The installent went ok, beware that when you start the application you have to hit the return key at least once maybe twice for it start, otherwise it just stays idle. Once started, you select a new 3D scene. Then you will be notified in the terminal that 3D scene can't be created and application crashes within a minute or two.

`0680:fixme:vulkan:X11DRV_vkCreateWin32SurfaceKHR Application requires child window rendering, which is not implemented yet!
err:   Failed to create surface`

![IronCAD_D3D11](https://user-images.githubusercontent.com/2061391/140564589-921eab44-747e-41d3-98d7-8bdc0d55af04.png)

I tested by creating a new 3D scene with both DirectX 9 and DirectX 11, same result. To select rendering driver go to menu->tools->Options->Rendering then there you can select either DirectX9 or DirectX11.

### Software information

- Distro: Ubuntu 20.04
- Application: IronCAD 2019

### System information
- GPU: Advanced Micro Devices, Inc. [AMD/ATI] Baffin [Radeon RX 460/560D / Pro 450/455/460/555/555X/560/560X]
- Driver: 

> filename:       /lib/modules/5.4.139-0504139-generic/kernel/drivers/gpu/drm/amd/amdgpu/amdgpu.ko
> version:        5.11.19.21.30
> license:        GPL and additional rights
> description:    AMD GPU
> author:         AMD linux driver team

- Wine version: 

> wine-staging-amd64/focal,now 6.20~focal-1 amd64 [installed]
> wine-staging-i386/focal,now 6.20~focal-1 i386 [installed]
> wine-staging/focal,now 6.20~focal-1 amd64 [installed]
> winehq-staging/focal,now 6.20~focal-1 amd64 [installed]
> winetricks/focal,focal,now 0.0+20200412-1 all [installed]

- DXVK version: 1.9.2

### Apitrace file(s)

Unsuccesful with the command ```WINEPREFIX="${WINE_PATH}" WINEARCH="${ARCHITECTURE}" ${WINE} apitrace-latest-win64/bin/apitrace.exe trace -a dxgi "${WINE_PATH}"/drive_c/Program\ Files/IronCAD/2019/bin/IRONCAD.exe``` application wouldn't even start.

### Log files

- d3d9.log: [IRONCAD_d3d9.log](https://github.com/doitsujin/dxvk/files/7488247/IRONCAD_d3d9.log)
- d3d11.log: [IRONCAD_d3d11.log](https://github.com/doitsujin/dxvk/files/7488031/IRONCAD_d3d11.log)
- dxgi.log: [IRONCAD_dxgi.log](https://github.com/doitsujin/dxvk/files/7488033/IRONCAD_dxgi.log)
- d3d9_wine.log: [IRONCAD_d3d9_wine.log](https://github.com/doitsujin/dxvk/files/7488299/IRONCAD_d3d9_wine.log)
- d3d11_wine.log: [IRONCAD_d3d11_wine.log](https://github.com/doitsujin/dxvk/files/7488303/IRONCAD_d3d11_wine.log)

**Comment by WinterSnowfall** [comment]
I've seen your posts on the Wine bug pertaining to vulkan child window support, so you **are** aware this is still an unfixed Wine issue with only an experimental patch available...

Secondly, you're trying to get DXVK working with llvmpipe? [Really?](https://github.com/doitsujin/dxvk/wiki/Driver-support)

**Comment by andyholst** [comment]
@WinterSnowfall 'vulkaninfo | grep amd' gives me 

> GPU id 	: 0 (AMD RADV POLARIS11)

I didn't try anything to get DXVK work especially with llvmpipe, and yes, I've run several other kind of CAD Windows applications in Wine and several of Steam games with Proton (Wine) without bothering about the graphic driver details.

I am aware of this bug exist, I didn't mind reporting it here since I'm not sure how the WineHQ bug community and DXVK community works together by implementing/fixing DirectX to Vulkan DirectX 9/11 transformation features to Wine upstream.

**Comment by WinterSnowfall** [comment]
> I'm not sure how the WineHQ bug community and DXVK community works together by implementing/fixing DirectX 9/11 to Vulkan transformation rendering features to Wine upstream.

They don't - they're entirely separate projects. DXVK is indeed included in Proton but not in Wine.

This is a Wine bug, not a DXVK bug, so not much good will come out of reporting it here.

As to your setup, I guess it looks fine as per your output above, but then why do all the logs you've captured default to llvmpipe? llvmpipe/lavapipe is a software vulkan implementation, so don't expect it to work properly. You are warned as such in the logs you've shared: `WARNING: lavapipe is not a conformant vulkan implementation, testing use only.`

**Comment by andyholst** [comment]
Noted.

**Comment by andyholst** [comment]
At least this issue '"fixme:vulkan:X11DRV_vkCreateWin32SurfaceKHR Application requires child window rendering, which is not implemented yet!"' was mentioned here in the DXVK community in the past https://github.com/doitsujin/dxvk/issues/879

**Comment by WinterSnowfall** [comment]
> At least this issue '"fixme:vulkan:X11DRV_vkCreateWin32SurfaceKHR Application requires child window rendering, which is not implemented yet!"' was mentioned here in the DXVK community in the past #879

I'm aware of the bug because I raised an issue about it here myself (https://github.com/doitsujin/dxvk/issues/1770). It's not something which can be fixed in DXVK, though it affects it in a manner in which all vulkan apps running in Wine are affected.

**Comment by andyholst** [comment]
> > At least this issue '"fixme:vulkan:X11DRV_vkCreateWin32SurfaceKHR Application requires child window rendering, which is not implemented yet!"' was mentioned here in the DXVK community in the past #879
> 
> I'm aware of the bug because I raised an issue about it here myself (#1770). It's not something which can be fixed in DXVK, though it affects it in a manner in which all vulkan apps running in Wine are affected.

I looked at one of the patches that Patrik suggest works, https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-patches/misc/childwindow.patch https://github.com/Frogging-Family/wine-tkg-git/issues/358. By looking at what commit it applies to I can see that it applies to Wine mainline commit bca1b7f , the patch is applied for Wine version 6.20 and above. I did run the building and installation of the repository in a container context with the commands:

```
WORKDIR /usr/src/wine-tkg-git/wine-tkg-git

RUN sed -i "/'jack2'                 'lib32-jack2'/d" PKGBUILD
RUN sed -i "/'gst-plugins-good'      'lib32-gst-plugins-good'/d" PKGBUILD
RUN bash -c 'yes | PKGDEST=/tmp/wine-tkg makepkg --noconfirm -s'
```

I executed it literally the same way as the pipeline is executed for the Arch Linux distro https://github.com/Frogging-Family/wine-tkg-git/blob/master/.github/workflows/wine-arch.yml since that distro has best support (least complications) for multi-arch compilation compared to Ubuntu/Debian.

You can easily redirect the rendering to X11 and still preserve the bare metal speed if it's OCI container like Docker.

I don't get the child window error anymore, now it's 

> err:   D3D11CreateDevice: Failed to create a DXGI factory

So at least some progress.

**Comment by andyholst** [comment]
I applied by running the child window patch from  https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-patches/misc/childwindow.patch and by installing the Wine version 6.20 by the following commands on my Arch Linux distro

```
cd /usr/src/wine-tkg-git/wine-tkg-git # checked out git commit 6bffd57

sed -i "/'jack2'                 'lib32-jack2'/d" PKGBUILD
sed -i "/'gst-plugins-good'      'lib32-gst-plugins-good'/d" PKGBUILD
sudo bash -c 'yes | PKGDEST=/tmp/wine-tkg makepkg --noconfirm -s'

sudo pacman -U --noconfirm /tmp/wine-tkg/wine-tkg-staging-fsync-git-6.20.*.pkg.tar.zst
```

Following things were given:

> HOME_PATH="/home/winer"
> WINE_PATH="${HOME_PATH}/.ironcad"
> ARCHITECTURE="win64"
> WINE="wine64"


I executed with following commands:

```
WINEPREFIX="${WINE_PATH}" WINEARCH="${ARCHITECTURE}" winetricks -q dxvk
WINEPREFIX="${WINE_PATH}" WINEARCH="${ARCHITECTURE}" winetricks -q win10

WINEPREFIX="${WINE_PATH}" WINEARCH="${ARCHITECTURE}" ${WINE} IronCADDCS2019_x64.exe

WINEPREFIX="${WINE_PATH}" WINEARCH="${ARCHITECTURE}" ${WINE} \
"${WINE_PATH}"/drive_c/Program\ Files/IronCAD/2019/bin/IRONCAD.exe
```

Once started,after selecting a 3D scene. Then you will be notified in the terminal that 3D scene can't be created and application crashes within a minute or two. No more '"fixme:vulkan:X11DRV_vkCreateWin32SurfaceKHR Application requires child window rendering, which is not implemented yet!", that seems to be fixed with the mentioned applied patch above.

### Software information

- Distro: Arch Linux

> LSB Version:	1.4
> Distributor ID:	Arch
> Description:	Arch Linux
> Release:	rolling "archlinux:base-devel-20211017.0.36769"
> Codename:	n/a

- Application: IronCAD 2019

### System information
- GPU: Advanced Micro Devices, Inc. [AMD/ATI] Baffin [Radeon RX 460/560D / Pro 450/455/460/555/555X/560/560X]
- Driver: radv

> driverID                                                = DRIVER_ID_MESA_RADV
> driverName                                          = radv
> driverInfo                                             = Mesa 21.2.4
> conformanceVersion                            = 1.2.3.0

 
- Wine version: wine-tkg-staging-fsync-git 6.20.r10.gdf26057d-326

- DXVK version: 1.9.2

### Apitrace file(s)

Not available.

### Log files

- d3d9.log: [IRONCAD_d3d9.log](https://github.com/doitsujin/dxvk/files/7490738/IRONCAD_d3d9.log)
- d3d11.log: [IRONCAD_d3d11.log](https://github.com/doitsujin/dxvk/files/7490725/IRONCAD_d3d11.log)
- dxgi.log: [IRONCAD_dxgi.log](https://github.com/doitsujin/dxvk/files/7490723/IRONCAD_dxgi.log)
- d3d9_wine.log: [IRONCAD_d3d9_wine.log](https://github.com/doitsujin/dxvk/files/7490736/IRONCAD_d3d9_wine.log)
- d3d11_wine.log: [IRONCAD_d3d11_wine.log](https://github.com/doitsujin/dxvk/files/7490726/IRONCAD_d3d11_wine.log)

**Comment by doitsujin** [comment]
What exactly is the problem now and how exactly are we supposed to fix it?

**Comment by andyholst** [comment]
> What exactly is the problem now and how exactly are we supposed to fix it?
> 
> Also
> 
> > 0200:fixme:d3dcompiler:D3DCompile2 HLSL shader compilation is not yet implemented.
> 
> not a dxvk problem, you'll need some native d3dcompiler libraries.

Ok, I close the issue again and dig deeper into what d3dcompiler libraries I'm missing.

**Comment by andyholst** [comment]
> What exactly is the problem now and how exactly are we supposed to fix it?
> 
> Also
> 
> > 0200:fixme:d3dcompiler:D3DCompile2 HLSL shader compilation is not yet implemented.
> 
> not a dxvk problem, you'll need some native d3dcompiler libraries.

I needed to install the d3dcompiler_47 library. I see still rendering issues, but it's app related.

![IRONCAD_2019](https://user-images.githubusercontent.com/2061391/140616692-b2649519-dfac-40a8-af82-3ad6efa5987e.png)

Thank you for your time.

**Comment by lorn10** [comment]
For the sake of completeness it should be added here: 

CAD and stock Wine users should look into this matter with **Gallium Nine** instead of DXVK. (The later is also in 2023 still broken because of the missing Vulkan "child window rendering support" in Wine.)

Yes, d3d9 is super old but even in 2023 some CAD software still comes with a fallback for this ancient rendering path. Furthermore, it looks that at least IronCAD 2019 effectively had some support for d3d9.

Finally it is confirmed for **[Autodesk-Fusion-360](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux)** that the mentioned "child window rendering support" is working with Gallium Nine. More information can be found [here](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/311).

Note, - regarding newer Wine releases (from 7.x and up) I would clearly not recommend to install the native Windows 7 gdiplus.dll via winetricks. It causes more problems than it helps. If a native MS gdiplus.dll is really needed then get a newer one from Windows 10 and make a manual override via `winecfg`. :wink:
