### ISSUE TITLE
Cursor bug

### ISSUE THREAD

**Issue by alexbonetti123** [doitsujin/dxvk#2352]
Hi, I'm reporting a problem. The mouse cursor is disappearing in the games I tested. Mouse works, but cursor does not appear

**Reports with no log files will be ignored.**

### Software information
Name of the game, settings used etc.

### System information
- GPU: r9 270x
- Driver: Radeon Software 25.1.2
- Wine version: 
- DXVK version: 

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by llde** [comment]
Which games you tested? 
Post the relevant DXVK log and the relvant apitrace. Fill also the Wine (if applicable) and the DXVK info

**Comment by doitsujin** [comment]
No info, no support.
