### ISSUE TITLE
AC Odyssey Glitches with DXVK on Windows

### ISSUE THREAD

**Issue by sathish8839** [doitsujin/dxvk#2355]
Hi ,

AC Odyssey Glitches while using DXVK on Windows 11 . It occurs only in Night time . Day time is smooth and no glitches are present .

Please refer the video down below: 
https://user-images.githubusercontent.com/63190978/141231347-d43d8663-e7da-4f45-9069-0e3c38787059.mp4

Many other users complained about this too , please refer the below link:
https://githubmemory.com/repo/doitsujin/dxvk/issues/2326

Game name : AC Odyssey
Settings : Everything to Max except Depth of Field

### System information
- GPU: RX 6800M
- Driver: Adrenalin 21.11.1 Optional
- DXVK version: DXVK 1.9.2
-Windows version: Win 11

### Log files
- d3d11.log:[ACOdyssey_d3d11.log](https://github.com/doitsujin/dxvk/files/7517402/ACOdyssey_d3d11.log)
- dxgi.log:[ACOdyssey_dxgi.log](https://github.com/doitsujin/dxvk/files/7517403/ACOdyssey_dxgi.log)

**Comment by doitsujin** [comment]
https://github.com/doitsujin/dxvk/issues/2326
