### ISSUE TITLE
Parallels Display Adapter DXVK driver

### ISSUE THREAD

**Issue by aksum3** [doitsujin/dxvk#2356]
Hello.  I am a M1 MacBook owner who wants to run FFXIV.  As I understand it, the present Mac version is a CodeWeavers CrossOver wrapper around Wine.

IIRC, the pipeline is DX <-> DXVK <-> Vulkan <-> MoltenVK <-> Metal.  As an alternative, I installed Windows 11 ARM on Parallels 17 and the VM itself runs at bare metal speed (but no 3D acceleration).

The only problem is that the VM uses a [Parallels Display Adapter](https://kb.parallels.com/en/122807) to translate DirectX to OpenGL.  It reminded me of DXVK.

If this VM driver was just a wrapper around DXVK instead, it would be like Wine, but more stable/less buggy.  Maybe it would also be more performant.  But I am not a low-level coder.

@doitsujin is this something you can do on a contract basis, or anyone else with the necessary knowledge if he is not available?

**Comment by K0bin** [comment]
> I installed Windows 11 ARM on Parallels 17 and the VM itself runs at bare metal speed

No it does not. Parallels has a virtual GPU for Windows that works by passing the graphics calls to the host OS (Mac OS) and translating them to Metal.

It dies not support Vulkan at all, so needless to say, DXVK won't work on that.

As you correctly pointed out, Crossover is shipping a forked version of DXVK that works on Mac OS, so I suggest you use that.

**Comment by aksum3** [comment]
> As you correctly pointed out, Crossover is shipping a forked version of DXVK that works on Mac OS, so I suggest you use that.

Would [virgrlrenderer with Vulkan](https://gitlab.freedesktop.org/virgl/virglrenderer/-/milestones/2) solve the VM problem?

**Comment by doitsujin** [comment]
We're not interested in supporting Mac OS directly, and DXVK is not designed to be used as a Windows display driver since it reimplements the whole D3D11 runtime rather than the DDI.

That being said, I don't really see how running the Windows version of the game through a VM and then translating D3D11->Vulkan->Metal would be any better than running the exact same Windows version through Wine while translating D3D11->Vulkan->Metal. If performance is low, this is likely due to the combination of wrappers which are all running on top of x86 emulation, but none of this would change with a VM.

**Comment by aksum3** [comment]
@K0bin The game runs at 25-30fps inside the VM which is pretty shocking, I did not expect it to even run.  I guess this has something to do with the unified video memory for the M1 GPU's.  ![Screen Shot 2021-11-12 at 9 36 26 AM](https://user-images.githubusercontent.com/84574720/141389004-d0f95ae3-48f6-484e-b546-6ce267eab33d.png)

**Comment by K0bin** [comment]
> I guess this has something to do with the unified video memory for the M1 GPU's

No, this has nothing to do with unified memory.

**Comment by aksum3** [comment]
Ok, to make sure I understand this right, it is a direct D3D <-> Metal translation?

**Comment by K0bin** [comment]
Parallels GPU driver is most likely a DDI (Direct3D device driver interface) to Metal translation layer.

**Comment by aksum3** [comment]
> We're not interested in supporting Mac OS directly, and DXVK is not designed to be used as a Windows display driver since it reimplements the whole D3D11 runtime rather than the DDI.
> 
> That being said, I don't really see how running the Windows version of the game through a VM and then translating D3D11->Vulkan->Metal would be any better than running the exact same Windows version through Wine while translating D3D11->Vulkan->Metal. If performance is low, this is likely due to the combination of wrappers which are all running on top of x86 emulation, but none of this would change with a VM.

I heard that the Apple M1 chip is able to directly run some x86 instructions with Rosetta 2, while Windows WOW64 is supposedly already slower because of having to work with 32-bit programs and having to work with less consistent development libraries and hardware.  On top of that, the VM does not run any x86 instructions directly.

Is that what you were referring to?

**Comment by mikwayhk** [comment]
> [@K0bin](https://github.com/K0bin) The game runs at 25-30fps inside the VM which is pretty shocking, I did not expect it to even run. I guess this has something to do with the unified video memory for the M1 GPU's. ![Screen Shot 2021-11-12 at 9 36 26 AM](https://user-images.githubusercontent.com/84574720/141389004-d0f95ae3-48f6-484e-b546-6ce267eab33d.png)

I'm trying to run FFXIV on the parallels 26 on my M4 Pro, could you describe how to get it done? I know there is XIV Mac out there but my country version is not supported so I have to use parallels, also tried with Crossover but no luck it just won't open.
I could login through the custom launcher but it shows Direct X error (30000000) after it try to start the real game.

<img width="1254" height="740" alt="Image" src="https://github.com/user-attachments/assets/bcf90b43-0df6-442f-9dc8-76021488f07f" />

Then I downloaded this and put the d3d11.dll & dxgi.dll into the game folder, it just showed different error.

![Image](https://github.com/user-attachments/assets/7b93192a-2e0f-4743-9061-6c574fb510fb)
