### ISSUE TITLE
Cold Steel Subs (game translation overlay) doesn't become transparent when finished loading

### ISSUE THREAD

**Issue by jrobeson** [doitsujin/dxvk#2358]
When running ColdSteelSubs.exe on Linux/Wine , the program starts up full screen with a black background, but then is supposed to become transparent when finished loading.  I tested this behaviour on a friend's windows 10 VM remotely and it definitely does so.  However, it does not do so when running on Linux with wine, either with dxvk or wined3d.

If this ends up being an issue with wine itself, then feel free to close, but i'm not sure how to tell otherwise.

### Software information
Cold Steel Subs v2.4 (available at https://drive.google.com/file/d/14CjlTl_MG0Yj6wNHSM-4S2yVwH6U3oM_/view

### System information
- GPU: nvidia 960M
- Driver: 495.44.0 (but occurred during the 470.x series as well)
- Wine version: 6.14  (and and every version up to 6.19)
- DXVK version:  v1.9.2-21-g2e66f45a

### Apitrace file(s)
https://www.dropbox.com/s/iehegmyfm0f6oks/coldsteelsubs.trace.gz?dl=0

The tracing crashed wined3d, so no log file provided for that.

### Log files
- d3d11.log: [ColdSteelSubs_d3d11.log](https://github.com/doitsujin/dxvk/files/7523661/ColdSteelSubs_d3d11.log)
- dxgi.log: [ColdSteelSubs_dxgi.log](https://github.com/doitsujin/dxvk/files/7523659/ColdSteelSubs_dxgi.log)

**Comment by doitsujin** [comment]
This is expected since the overlay application creates its own window that covers the game's window. I don't think it is any way to fix this on wine, as all overlays of this type have this problem regardless of which API they use.
