### ISSUE TITLE
[d3d10] Support for effects framework

### ISSUE THREAD

**Issue by nsivov** [doitsujin/dxvk#2360]
Currently effects framework is not supported in dxvk's d3d10. At the same time with recent improvements in Wine's d3d10 it got better, and I was able to run some games with it (there is one important fix pending, but we'll get there). So I'd like to start this discussion on how this support could be introduced in dxvk now. 

First, I don't know if there is a reason to ship d3d10.dll in dxvk at all, since all it should be doing is to forward to d3d10core, that dxvk has as well. Is it simply to have a complete set of modules, regardless of how there are actually used?

Is there any interest in having effects support in dxvk in a first place, or maybe, at least for Proton, we should simply stop using dxvk's d3d10 and use the one from Wine?

**Comment by Joshua-Ashton** [comment]
DXVK works with the D3D10.dll from both Wine and Windows. We do not install D3D10.dll by default, only D3D10Core.dll

**Comment by Joshua-Ashton** [comment]
I did not intend to close this but if that answers your question, it probably can be.

**Comment by nsivov** [comment]
What do you mean by not installing it? As far as I can see it's still in the list of dlls to copy to the prefix, in latest proton experimental. It is also present in release packages. And that's how relevant error message for effect functions were spotted. Are you suggesting we should remove d3d10 copy from proton startup script?

**Comment by Joshua-Ashton** [comment]
Yes. We also do not install it by default in our `setup_dxvk.sh` script.

**Comment by nsivov** [comment]
Alright, thank you.
