### ISSUE TITLE
[d3d9] LEGO Harry Potter: Years 1-4

### ISSUE THREAD

**Issue by ziemia** [doitsujin/dxvk#2366]
Lego games using directx 9 have a texture problem.
The game starts correctly on Proton 4.11-13, on higher versions of Proton it played correctly with PROTON_USE_WINED3D = 1.
The problem is reported on the protondb portal by other players.

### Software information
LEGO Harry Potter: Years 1-4

### System information
- GPU: Nvidia GTX 1070
- Driver: 470.63.01
- Wine version: => Proton 5.x-x
- DXVK version: v1.9.2

### Log files
[steam-21130.log](https://github.com/doitsujin/dxvk/files/7534614/steam-21130.log)

**Comment by K0bin** [comment]
How about you go a bit more into detail? Screenshots of the problem would also be nice.

As far as I'm concerned, the game works without any issues. (Proton Experimental)

![20211115001327_1](https://user-images.githubusercontent.com/1131720/141702530-e62b3fc7-abf8-44da-bba5-890e958fccb4.jpg)

**Comment by ziemia** [comment]
I attach a short video. Video from the phone quickly, before the work, I did not have time to set up the OBS.
Game run on  on Proton Experimental.

https://user-images.githubusercontent.com/40964591/141750345-176be56d-3805-4950-808b-8c3a0ae9850b.mp4

**Comment by K0bin** [comment]
Do other games work on your system? This might be a hardware defect.

I have the exact same GPU and the game works just fine with the same DXVK version.

**Comment by ziemia** [comment]
Currently all other games (native and proton) are working great,
https://steamcommunity.com/profiles/76561198349055922/games/?tab=all

I'll try to generate an Apitrace when I come home from work.

**Comment by K0bin** [comment]
An apitrace won't help. The game works perfectly for me, so there's nothing I can do.
