### ISSUE TITLE
Broken texture quality - METAL GEAR SOLID V: GROUND ZEROES

### ISSUE THREAD

**Issue by AlfredoRodda** [doitsujin/dxvk#2367]
### Description
If the texture preset setting is set to anything above Medium, for example "High & Extra High", the quality actually drops to the Low preset.

### Screenshots

**Medium**
![m1](https://user-images.githubusercontent.com/92961316/141800349-9fd78aea-6733-4a7f-82e5-f82704f139c3.png)
**Extra High**
![ex1](https://user-images.githubusercontent.com/92961316/141800365-419dc030-f057-4d08-92d5-8e69341c9926.png)
**Medium**
![m2](https://user-images.githubusercontent.com/92961316/141800430-64424020-d70a-43ff-942f-cefe8bdca214.png)
**Extra High**
![ex2](https://user-images.githubusercontent.com/92961316/141800465-4d8669ab-95f5-4d8c-a9ed-fa0bf5ae1396.png)
**Medium**
![m3](https://user-images.githubusercontent.com/92961316/141800483-f8bc9b59-b4f7-4495-8565-97f1f7dbeb6c.png)
**Extra High**
![ex3](https://user-images.githubusercontent.com/92961316/141800512-adc2c045-b4c8-41e7-8b8d-9df82a67a84f.png)

### Software information
METAL GEAR SOLID V: GROUND ZEROES (1.005)

### Steps to reproduce
1. Start the game.
2. Go to Options -> Graphics Settings -> Textures
3. Compare the Texture quality preset setting between Medium and Extra High in the main menu and in game.

### System information
- GPU: (Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e7))
- Driver: Mesa/RADV(OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.2.5)
- Wine/Proton version: Wine 6.20, Wine TkG 6.21, and Proton 6.3-7
- DXVK version: 1.9.2

### Apitrace file(s)
- I can not seem to get the game to run following the instructions at https://github.com/apitrace/apitrace

### Log files
- d3d11.log:[MgsGroundZeroes_d3d11.log](https://github.com/doitsujin/dxvk/files/7539463/MgsGroundZeroes_d3d11.log)
- dxgi.log:[MgsGroundZeroes_dxgi.log](https://github.com/doitsujin/dxvk/files/7539466/MgsGroundZeroes_dxgi.log)

**Comment by AlfredoRodda** [comment]
Thanks, managed to get it to create something but the game did not launch still.
[MgsGroundZeroesTrace.zip](https://github.com/doitsujin/dxvk/files/7540378/MgsGroundZeroesTrace.zip)

**Comment by AlfredoRodda** [comment]
I noticed the trace uploaded was empty. This one has some content, but the came still crashes while launching.
[MgsGroundZeroes.trace.zip](https://github.com/doitsujin/dxvk/files/7573171/MgsGroundZeroes.trace.zip)

**Comment by Blisto91** [comment]
@AlfredoRodda Friendly ping. Could i get you to check if this is still an issue with latest dxvk and driver?

**Comment by AlfredoRodda** [comment]
Hi @Blisto91, I went back and tested this out and the issue is present still with the  following setup:

Wine 7.14
DXVK 1.10.3
Mesa 22.1.4

**Comment by Blisto91** [comment]
Thanks for checking 👍 
I also have the game now so will try to reproduce when i have time

**Comment by Blisto91** [comment]
So i am seeing some weirdness where the texture quality seems to go back and forth in quality depending on setting. But i see similar with wined3d.
Here are some screenshots with wined3d (without dxvk) where you'll notice the high setting takes a dip in quality.

<details>
  <summary>Textures low</summary>

![Screenshot_20220825_211429](https://user-images.githubusercontent.com/47954800/186750645-d34b56f2-3894-404c-9721-635eee1aa970.png)

</details>

<details>
  <summary>Textures medium</summary>

![Screenshot_20220825_211818](https://user-images.githubusercontent.com/47954800/186750665-340af664-77cf-4091-bca0-08529624575d.png)

</details>

<details>
  <summary>Textures high</summary>

![Screenshot_20220825_211534](https://user-images.githubusercontent.com/47954800/186750675-3e2d4b09-77f6-4606-827f-8c20f7d92e73.png)

</details>

<details>
  <summary>Textures very high</summary>

![Screenshot_20220825_211618](https://user-images.githubusercontent.com/47954800/186750703-43c0ceb5-1345-45f2-8aef-2fdb4f3480c7.png)

</details>

**Comment by Blisto91** [comment]
Actually with some more testing we found that it breaks when it sees a vram value of 4096 or above. Probably a integer overflow in some internal game logic.
So we are going to work around it by capping our maximum reported vram at 4095. `dxgi.maxDeviceMemory = 4095`

**Comment by Blisto91** [comment]
You can check with latest master build. It should be working now.
You can grab it here https://github.com/doitsujin/dxvk/actions/runs/2931047801

**Comment by AlfredoRodda** [comment]
I can confirm that this issue is resolved, Thank you @Blisto91.
