### ISSUE TITLE
Senren * Banka window goes black when workspace in GNOME is changed or when you run the game in full-screen

### ISSUE THREAD

**Issue by DavidHusicka** [doitsujin/dxvk#2368]
Senren * Banka window goes black when workspace in GNOME changes or when you run the game in full-screen.

### Software information
Senren * Banka with latest proton experimental

https://store.steampowered.com/app/1144400/SenrenBanka/

### System information
- GPU: AMD Renoir / NVidia GTX 960
- Driver: Mesa 21.2.5-1 from Arch Linux repos / NVidia 470 driver
- Wine version: Proton experimental
- DXVK version: Proton experimental

### Apitrace file(s)
[SenrenBanka traces.zip](https://github.com/doitsujin/dxvk/files/7555035/SenrenBanka.traces.zip)

### Log files
[SenrenBanka_d3d9 logs.zip](https://github.com/doitsujin/dxvk/files/7555053/SenrenBanka_d3d9.logs.zip)

**Comment by Blisto91** [comment]
@K0bin Fixed in dxvk 1.10.1
With the trial i can reproduce in 1.10 that it's black when launched in fullscreen or when in windowed is minimized and brought back. The latter I'm guessing is what made it happen on workspace change in gnome. Tho the same doesn't happen on kde.

**Comment by Blisto91** [comment]
@DavidHusicka Are you able to verify the above?

**Comment by DavidHusicka** [comment]
It doesn't go black anymore on Proton Experimental.
