### ISSUE TITLE
[BISECTED] Missing geometry on Deadspace 3 and Time Shift

### ISSUE THREAD

**Issue by mupuf** [doitsujin/dxvk#2369]
When running the a Deadspace 3 and a [Time Shift](https://git.froggi.es/Riesi/tracehub/src/branch/master/traces/d3d9/TimeShift%20[native].trace.tar.xz) apitrace, some geometry started disappearing.

The issue is reproducible on Mesa 21.2.5 / Mesa main on Polaris10/Vega10/Renoir/Navi10/Navi21 and was bisected to https://github.com/doitsujin/dxvk/commit/530f87f158b361853022607eee54cdae2c2f7f8f. Reverting the commit fixes the issues.

Here are some examples of mis-rendering:

# Time shift
## Good

![image](https://user-images.githubusercontent.com/310883/142214497-02465edc-d9ab-4664-bcf4-99819568b526.png)

## Bad

![image](https://user-images.githubusercontent.com/310883/142214398-b3c5cc20-5c74-4f86-806e-b2e5764e55ae.png)

# Deadspace 3

### Good

![image](https://user-images.githubusercontent.com/310883/142214733-9fb2ac7c-b8e4-47ca-9ebb-2b087f96d761.png)

### Bad

![image](https://user-images.githubusercontent.com/310883/142214655-47b2d494-bf76-461b-9be5-5648e9f660f8.png)

### Good

![image](https://user-images.githubusercontent.com/310883/142214823-bb4de242-bc34-4e38-8a53-f47fef653925.png)

### Bad

![image](https://user-images.githubusercontent.com/310883/142214865-9ea3248f-f587-4182-b7f0-a7f0c4934c8d.png)

**Comment by K0bin** [comment]
Thanks for bisecting it. I'll take a look.

**Comment by K0bin** [comment]
![20211117152430_1](https://user-images.githubusercontent.com/1131720/142220318-ae76223e-f01c-4960-9038-6d8e217eecea.jpg)
![20211117152526_1](https://user-images.githubusercontent.com/1131720/142220322-9a568286-bf4c-4e95-bc14-fc18c2570869.jpg)
![20211117153343_1](https://user-images.githubusercontent.com/1131720/142220324-e1d08b7e-5370-4713-b684-2c19f904f81b.jpg)

Can't reproduce on Nvidia. :(

**Comment by mupuf** [comment]
Mind contacting me on IRC (mupuf on liberachat/oftc), so I can give you the link to the trace I am using? This may be due to missing workarounds.

**Comment by Iglu47** [comment]
> ![20211117152430_1](https://user-images.githubusercontent.com/1131720/142220318-ae76223e-f01c-4960-9038-6d8e217eecea.jpg) ![20211117152526_1](https://user-images.githubusercontent.com/1131720/142220322-9a568286-bf4c-4e95-bc14-fc18c2570869.jpg) ![20211117153343_1](https://user-images.githubusercontent.com/1131720/142220324-e1d08b7e-5370-4713-b684-2c19f904f81b.jpg)
> 
> Can't reproduce on Nvidia. :(

@K0bin probably is not master. on your screenshots show version 1.9.2, but this does not include 530f87f158b361853022607eee54cdae2c2f7f8f, as far as I understand.

**Comment by mupuf** [comment]
@K0bin instructed me to try the [last commit of his pull request](https://github.com/doitsujin/dxvk/pull/2364/commits/d88afc4a008be35fff51b2c99f40529ffb48fd3e), and it indeed fixes the issue.
