### ISSUE TITLE
Grand Theft Auto V Wayland Forced V-Sync ~10fps performance on high end system

### ISSUE THREAD

**Issue by EuanFH** [doitsujin/dxvk#2376]
Have a feeling its this issue [1314](https://github.com/doitsujin/dxvk/issues/1314) but instead cropping up because of wayland.
I assume this is probably a mixture of how the compositor, DXVK, and GTA V interact.
Most wayland compositors force vsync so no way to disable most games including gta iv handle this fine.
I have vsync disabled in the game.
Can't tell where the bug would lie on this one. if its a compositor problem, xwayland problem, dxvk problem, or GTA V problem.
On x11 gpu will get close to 100% but will fluctuate during gameplay on wayland the gpu will be pegged at 100%.
notable difference to [1314](https://github.com/doitsujin/dxvk/issues/1314) is that the menus run at a locked 60 its just in game where the fps problems occur.
If this is not a dxvk issue do you have any idea which project the issue would most likely be the cause of this issue.

Reproduce:
Run GTA V on a wayland compositor and run the benchmark mode it will be apparent the performance problems with gpu hitting 100%

### Software information
Grand Theft Auto V

### System information
- GPU: AMD Radeon RX 6800 XT
- Driver: mesa 21.2.5
- Wine version: Proton-6.20-GE
- DXVK version: dxvk @ 8912c7a

**Comment by doitsujin** [comment]
No idea what this is, maybe try wined3d and see if that works but I don't really see how this would be a bug on our end.

**Comment by EuanFH** [comment]
Yeah just reported here first because i seen the issue from a while ago and they seem semi related. 

just seems odd because this is the only game i get the problem was wondering how i could figure out what part of the stack is causing the issue and then report to the right project. High GPU seems to suggest it would be how dxvk is handling the game or how the game is handling the forced vsync.

I have a feeling this is probably a specific game issue than anything else.

Once i have provided more details and you figure its definitely not dxvks problem it would be nice if you could point me in the right direction of a project to report this too also fair if you have no idea which part of the stack the problem is coming from haha.

Will:
- see if wined3d works. 
- provide dxvk logs
- provide a video as well so you can see the issue.
- try and recreate this issue on xorg if there is a way to force vsync on that as well.

**Comment by EuanFH** [comment]
Going to close this off.
The issue resolved its self.
No idea what happened same setting as yesterday but magically started getting normal FPS.

Sorry for wasting your time.
