### ISSUE TITLE
Compile Error 'cv_status'

### ISSUE THREAD

**Issue by Slyfox88** [doitsujin/dxvk#2377]
[11/275] Compiling C++ object src/util/libutil.a.p/util_monitor.cpp.obj
FAILED: src/util/libutil.a.p/util_monitor.cpp.obj
...
error: ‘cv_status’ in namespace ‘std’ does not name a type
  279 |     std::cv_status wait_until(std::unique_lock<dxvk::mutex>& lock, const std::chrono::time_point<Clock, Duration>& time) {
      |          ^~~~~~~~~
...
error: ‘std::cv_status’ has not been declared
  310 |       if (!result && wait_for(lock, timeout) == std::cv_status::no_timeout)
      |                                                      ^~~~~~~~~
...
error: ‘std::this_thread’ has not been declared
  120 |         std::this_thread::sleep_for(sleepDuration);

**Comment by DadSchoorse** [comment]
See https://github.com/doitsujin/dxvk#troubleshooting

**Comment by Slyfox88** [comment]
I set both to:
/usr/bin/x86_64-w64-mingw32-gcc-posix
/usr/bin/x86_64-w64-mingw32-g++-posix
But got the same error.

**Comment by DadSchoorse** [comment]
Did you do the same with i686-w64-mingw32-gcc and i686-w64-mingw32-g++?

**Comment by Slyfox88** [comment]
Even though my system is x64 that got it to work. Maybe someone can update the guide. Thanks.

**Comment by TheIronWolfModding** [comment]
I was getting all sorts of problems until I set up a docker using this exact Arch Linux build and using commands in this activity:

https://github.com/Joshua-Ashton/arch-mingw-github-action/blob/master/Dockerfile
