### ISSUE TITLE
Nvidia Flow SDK demo doesn't launch..

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#238]
### Software information
you must be registered to obtain sdk at : https://github.com/NVIDIAGameWorks/Flow
this demo has D3D12 and D3D11 exes and it's is nice because it needs sparse textures /tiled textures so may be requesting D3D11.2 or even 11.3 context for 3D Sparse textures support..
anyway don't know if it's sparse tex related as it's failing in DXGI 
fails with:

> warn:  CreateDXGIFactory2: Ignoring flags
> err:   CreateDXGIFactory: Requested version of IDXGIFactory not supported
> err:   1bc6ea02-ef36-464f-bf0c-21ca39e5168a

good is thath demo has source code included..
I'm using Flow 1.0.1.. Flow 1.1 is coming soon seems with Vulkan support so maybe nice to compare DXVK with native support once it ships..

### System information

- GPU:Nvidia 970
- Driver: 391.35
- Wine version:none 
- DXVK version: latest

### Log files
- d3d11.log:
[DemoAppRelease_win64_d3d11.log](https://github.com/doitsujin/dxvk/files/1874022/DemoAppRelease_win64_d3d11.log)

- dxgi.log: 
[DemoAppRelease_win64_dxgi.log](https://github.com/doitsujin/dxvk/files/1874021/DemoAppRelease_win64_dxgi.log)

some lines having DXGIFactory calls:
```
AppGraphCtx* AppGraphCtxCreateD3D11(int deviceID)
{
	AppGraphCtxD3D11* context = new AppGraphCtxD3D11;

	HRESULT hr = S_OK;

	// enumerate devices
	IDXGIFactory1* pFactory = NULL;
	CreateDXGIFactory1(IID_PPV_ARGS(&pFactory));
	IDXGIAdapter1* pAdapterTemp = NULL;
	IDXGIAdapter1* pAdapter = NULL;
	DXGI_ADAPTER_DESC1 adapterDesc;
	int adapterIdx = 0;
	while (S_OK == pFactory->EnumAdapters1(adapterIdx, &pAdapterTemp))
	{
		pAdapterTemp->GetDesc1(&adapterDesc);

		context->m_dedicatedVideoMemory = (size_t)adapterDesc.DedicatedVideoMemory;

		if (deviceID == adapterIdx)
		{
			pAdapter = pAdapterTemp;
			break;
		}
		else
		{
			pAdapterTemp->Release();
		}
		adapterIdx++;
	}

	D3D_DRIVER_TYPE driverTypes[] =
	{
		D3D_DRIVER_TYPE_UNKNOWN,
		D3D_DRIVER_TYPE_HARDWARE,
		D3D_DRIVER_TYPE_WARP,
		D3D_DRIVER_TYPE_REFERENCE,
	};
	UINT numDriverTypes = 4;

	D3D_FEATURE_LEVEL featureLevels[] =
	{
		D3D_FEATURE_LEVEL_11_1,
		D3D_FEATURE_LEVEL_11_0,
		D3D_FEATURE_LEVEL_10_1,
		D3D_FEATURE_LEVEL_10_0,
	};
	UINT numFeatureLevels = 4; 
```

**Comment by doitsujin** [comment]
I don't have any plans to support D3D11.2+ or DXGI1.3+. DXGI1.2 will be necessary to emulate a proper Dx11.1 environment at some point, but the priority on that is very low.
