### ISSUE TITLE
The Guild 3 overview map artifacts

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#2380]
On some maps in The Guild 3 the overview map when you press m will have graphical artifacts.
I have  narrowed it down to start happening in DXVK 1.9.0. In 1.8.1 it seems fine.

(The game will have to be started in safe mode or else it will crash at the intro videos unless their files are removed)

<details>
  <summary>When run through Proton 6.3-8 & Experimental</summary>
  
![2021-11-16_20-45](https://user-images.githubusercontent.com/47954800/142056255-d58e84dd-44af-4537-b3bf-e1e9281f22d6.png)
</details>
<details>
  <summary>When run through Proton 5.13-6</summary>
  
![2021-11-16_20-49](https://user-images.githubusercontent.com/47954800/142056272-324a7845-e084-42e4-b0b0-ed3b2b7b4a7e.png)
</details>

### Software information
The guild 3. 
Haven't found that settings affect the issue

The issue seems to happen by varying degree on all maps except Paris and Vienna & Presporok. Not sure what is special about those two.

### System information
- GPU: AMD R9 380
- Driver/LLVM version: Mesa 21.2.5/13.0.0
- Kernel version: 5.15.2-arch1-1
- Link to full system information report as Gist: https://gist.github.com/Blisto91/f403fe74c9cab93b7f0857e3ffaf5f0a
- Proton version: Experimental

### Apitrace file(s)
I tried getting a Apitrace on windows by putting the dll's in the same folder as the executable, but the game slowed down so much i waited for 1,5 - 2 hours just for it to get into the main menu and then i had to get to bed. If it is needed i will try again. 

Edit: [Apitrace made through proton](https://mega.nz/file/YwQlBYYC#fJ5vvo_8uko4ZI4yw8Wh2SgH65GhnEV30yLmJLsJGd8)

### Log files
[Guild3_d3d11.log](https://github.com/doitsujin/dxvk/files/7604795/Guild3_d3d11.log)
[Guild3_dxgi.log](https://github.com/doitsujin/dxvk/files/7604796/Guild3_dxgi.log)

**Comment by doitsujin** [comment]
Can you try to get a trace on Linux instead? Not 100% guaranteed to be useful, but should be significantly faster since DXVK has optimizations to speed up apitrace capture.

**Comment by Blisto91** [comment]
Okay so i'm very much a newb at wine and wasn't able to get the game to launch with the vanilla version of it.
I instead put the apitrace dll's into the games folder and then launched it through steam proton experimental. I hope this will do.
If not i will try to get it working through wine or launching the game through steam with `PROTON_USE_WINED3D` if that is sufficient.

I have updated the opening post with the apitrace.

**Comment by doitsujin** [comment]
Thanks, this should work again now.

**Comment by Blisto91** [comment]
Thanks. Good work. :tada:
