### ISSUE TITLE
Destroy All Humans Flickering On Intel Iris Xe

### ISSUE THREAD

**Issue by ruineka** [doitsujin/dxvk#2381]
OS: Pop OS 21.04
Driver: Intel Mesa 21.3.0
Graphics: Intel Iris XE 96 EU

I created a trace running on Mesa 21.3.0 for the game here..
https://mega.nz/file/usNgjTCB#LJzY1QqS64EFxO2wNQjhiRRnkBmn8wSMAn-DyyFsiBY

The game runs perfectly performance wise, but the buildings flicker as well as a few objects in the game.

I have a ticket open here https://gitlab.freedesktop.org/mesa/mesa/-/issues/5662#note_1166985 as well since I'm not certain of what the current issue is and if its a DXVK issue or a Mesa driver.

**Comment by doitsujin** [comment]
We're [aware](https://github.com/doitsujin/dxvk/issues/2374) that Iris XE is broken with DXVK, please don't open a report for every single game now.

**Comment by doitsujin** [comment]
FWIW, I tried to replay the trace but on RADV it just hangs my GPU and on Windows with native D3D11 it just shows a black window with nothing in it; does it do anything on your end?
