### ISSUE TITLE
STAR WARS Empire at War / Force of Corruption Stutters

### ISSUE THREAD

**Issue by Slyfox88** [doitsujin/dxvk#2382]
With any of the popular mods this game stutters. The only reason anyone still plays this game is for the mods. Also tried a version of dxvk with Sporif/dxvk-async patch which might have helped a bit. Played on a modern system (amd/mesa) that is more than capable.
Mods: Awakening the Rebellion, Empire at War: Remake.
Tried on 2160P, 1440P high settings, widescreen, v-sync both on/off.
Radeon RX Vega 56 (VEGA10, DRM 3.41.0, 5.13.0-7620-generic, LLVM 12.0.0)
Mesa 21.2.2
Wine 6.14-GE
DXVK 1.9.2

**Comment by K0bin** [comment]
> **Reports with no log files will be ignored.**

> ### Software information
> Name of the game, settings used etc.

> ### System information
> - GPU:
> - Driver:
> - Wine version: 
> - DXVK version: 

> ### Apitrace file(s)
> - Put a link here

> ### Log files
> - d3d9.log:
> - d3d11.log:
> - dxgi.log:

There's a reason why the issue template asks for all that. Please actually fill that out.

**Comment by Slyfox88** [comment]
Added:
Tried on 2160P, 1440P high settings, widescreen, v-sync both on/off.
Radeon RX Vega 56 (VEGA10, DRM 3.41.0, 5.13.0-7620-generic, LLVM 12.0.0)
Mesa 21.2.2
Wine 6.14-GE
DXVK 1.9.2

**Comment by K0bin** [comment]
Logs, apitrace?

And most importantly: what mods?

**Comment by Slyfox88** [comment]
Added:
Mods: Awakening the Rebellion, Empire at War: Remake.

**Comment by K0bin** [comment]
Now the apitrace please.

**Comment by Slyfox88** [comment]
How do you do that?

**Comment by doitsujin** [comment]
and this doesn't happen with wined3d and on windows?

**Comment by Slyfox88** [comment]
On Windows it's fine.

**Comment by K0bin** [comment]
Do you have both mods installed or does it happen with either one?

**Comment by Slyfox88** [comment]
Same issue on either one. The mods are exclusive from each other. It's safe to assume the other major mods for the game have a similar issue.

**Comment by K0bin** [comment]
Does it run better with WineD3D? I'm not sure this is a DXVK problem, I made an apitrace and replaying it runs at 280 fps average.

**Comment by Slyfox88** [comment]
Did you make sure the mod was enabled? You have to go to Options then Mods to select the mod and it will restart the game with the mod.

**Comment by K0bin** [comment]
I set the launch option according to the readme.

**Comment by K0bin** [comment]
Can you please

* test it on Windows with DXVK.
* make an apitrace of a problematic scene

**Comment by Slyfox88** [comment]
I can try apitrace when I have some free time on Linux.

**Comment by Slyfox88** [comment]
When I try to download the apitrace binary the site says ""Artifact not found or access denied." I downloaded the source but ./configure didn't work and there's no instructions on how to compile it.

**Comment by K0bin** [comment]
Download it from here: https://github.com/apitrace/apitrace/releases

**Comment by Slyfox88** [comment]
Done.

[https://drive.google.com/drive/folders/1QPbGpRJc4NcwzM0I7DpRvtQm4rWwL8aw?usp=sharing](https://drive.google.com/drive/folders/1QPbGpRJc4NcwzM0I7DpRvtQm4rWwL8aw?usp=sharing)

**Comment by Slyfox88** [comment]
Has anyone looked into this?

**Comment by K0bin** [comment]
Not yet.

**Comment by Blisto91** [comment]
So i think i see what you mean.
I started the game with `Empire at War: Remake` and the main menu background battle stutters a lot. But GPU utilization is very low (below 10% when it's worst). This also happens with WINED3D. This is even with everything set to low and also a low resolution.
Haven't tried actual gameplay yet or any other mods.

This is with proton 7.0-2, R9 380, mesa 22.1, fsync enabled etc.
`d3d9.apitraceMode = True` didn't have an effect.

<details>
  <summary>Screenshot</summary>
  
![Screenshot_20220529_203206](https://user-images.githubusercontent.com/47954800/170886167-9ab133aa-722b-48ef-9ee1-c7018f7576fe.png)
</details>

**Comment by K0bin** [comment]
I can reproduce the issue on Linux. When I run it on Windows with DXVK, the stuttering does happen a couple of times but it's gone afterwards and there's nothing that indicates it's caused by DXVK.

So this is most likely a Wine issue rather than a DXVK one.

**Comment by Blisto91** [comment]
@Slyfox88 If you are up for it you could attempt to make a issue at the [Wine issue tracker](https://bugs.winehq.org/)
Maybe they'll be able to help or provide some info
