### ISSUE TITLE
Nvidia Flex 1.2.0 SDK demo has some issues on Nvidia ..

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#239]
you must be registered to obtain sdk at : https://github.com/NVIDIAGameWorks/FleX
this demo has D3D12 and D3D11 and CUDA support..
running D3D11 demo really renders almost correctly..
anyway getting some shader errors:
```
err:   DxvkComputePipeline: Failed to compile pipeline
err:     cs  : CS_8a6159ac7c5bccd66bc2d1a29fb907198435dd3d
err:   DxvkComputePipeline: Failed to compile pipeline
err:     cs  : CS_602ccce08f9e896153ebb133d8532e474bc47dbc
err:   DxvkComputePipeline: Failed to compile pipeline
err:     cs  : CS_2daa880347a06470dce13bfddeeb534fa9ada4d1

```
BAD SPIR-V FILES->
[FleX-master.zip](https://github.com/doitsujin/dxvk/files/1874047/FleX-master.zip)

### System information
- GPU: gtx 970
- Driver: 391.35
- Wine version:none  
- DXVK version: latest

### Log files
- d3d11.log:
[NvFlexDemoReleaseD3D_x64_d3d11.log](https://github.com/doitsujin/dxvk/files/1874040/NvFlexDemoReleaseD3D_x64_d3d11.log)

- dxgi.log: 
[NvFlexDemoReleaseD3D_x64_dxgi.log](https://github.com/doitsujin/dxvk/files/1874041/NvFlexDemoReleaseD3D_x64_dxgi.log)

**Comment by doitsujin** [comment]
Please test with 492c7384bca4916cd8a03fbf709519612b0001ac, which implements the missing instructions.

**Comment by oscarbg** [comment]
Some notes:
yes using https://github.com/doitsujin/dxvk/commit/492c7384bca4916cd8a03fbf709519612b0001ac fixes all issues on Nvidia GPU..
now interesting part is I test on AMD Vega GPU on Windows latest driver and intial simulation (Pout purri) works but changing to other "Bunny Bath Dam" cause immediate GPU crash and AMD driver forces a GPU reset (like a TDR)..
even more interesting is switch to "rigid fluid coupling" Works for a few seconds until complete driver crash..
as you see this is not the tipical app crash as normally they don't cause GPU driver reset on Windows like a TDR..
maybe a good motivation to integrate VulkanAfterCrash.h as mentioned on other issue..
 (tested with latest versión also https://github.com/doitsujin/dxvk/commit/492c7384bca4916cd8a03fbf709519612b0001ac )

I attach full outut below
```
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Radeon RX Vega:
info:    Driver: 2.0.18
info:    Vulkan: 1.1.70
info:  D3D11CreateDevice: Probing D3D_FEATURE_LEVEL_11_1
info:  D3D11CreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  Enabled device extensions:
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Radeon RX Vega:
info:    Driver: 2.0.18
info:    Vulkan: 1.1.70
info:  DxgiPresenter: Recreating swap chain:
  Format:       VK_FORMAT_R8G8B8A8_UNORM
  Present mode: VK_PRESENT_MODE_FIFO_KHR
  Buffer size:  1280x720
Reshaping
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Radeon RX Vega:
info:    Driver: 2.0.18
info:    Vulkan: 1.1.70
info:  D3D11CreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  Enabled device extensions:
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
Compute Device: Radeon RX Vega

warn:  DxvkQueryPool: Failed to get query data for 20:2 with: VK_NOT_READY
warn:  DxvkQueryPool: Failed to get query data for 20:2 with: VK_NOT_READY
err:   DxvkDevice: Command buffer submission failed: VK_ERROR_DEVICE_LOST
err:   DxvkDevice: Command buffer submission failed: VK_ERROR_DEVICE_LOST
err:   DxvkSwapchain::getFramebuffer: Failed to acquire image
err:   DxvkDevice: Command buffer submission failed: VK_ERROR_DEVICE_LOST

```

**Comment by doitsujin** [comment]
I do not and will not support AMD's Windows driver (or amdvlk, for that matter) - closing since the original issue has been resolved.
