### ISSUE TITLE
Assassins Creed Odyssey Particle bug

### ISSUE THREAD

**Issue by Blitz195** [doitsujin/dxvk#2390]
Hello sorry i couldnt apitrace get to work so i couldnt get logs i have same issue with this guy on ubisofts forum

https://discussions.ubisoft.com/topic/121223/odd-graphics-issues-windows-11-amd-5700xt-odyssey-v1-5-4?lang=en-US

Just putting the same image from there because when i took a screenshot it cames as black and white 
![0042ede3-8dd4-4cf1-9231-5c0c7b0e8b5b](https://user-images.githubusercontent.com/44959860/144939615-10fc6cd0-c26f-4b37-abae-4ba221c807fa.png)

and this happens only when i use dxvk

 System information
Processor: AMD Ryzen 5 2600 Six-Core Processor             (12 CPUs), ~3.8GHz
Memory: 16384MB RAM
GPU:Radeon RX 580 Series 8171 MB Vram
Driver:21.10.2
Operating System: Windows 10 Pro 64-bit (10.0, Build 19043) (19041.vb_release.191206-1406)
DXVK version: 1.9.2

Edit: I tried again with apitrace but couldnt even get to the main menu in like 20 minutes am i doing something wrong ?

**Comment by doitsujin** [comment]
This is a known AMD driver bug and not our issue, has been reported multiple times here already. #2355
