### ISSUE TITLE
Saints Row 2 Crash

### ISSUE THREAD

**Issue by EtaYorius** [doitsujin/dxvk#2394]
Saints Row 2 seems to load fine but after playing around for about 1-2 minutes the game crashes. Also, some shadows are messed up as the side of the character will darken up instead of lightening with light sources.

Presing F12 on Steam to take screenshot also crashes the game.

Using a GTX1070 nV latest drivers on Win10 20H2.

**Comment by K0bin** [comment]
Logs?

**Comment by EtaYorius** [comment]
[sr2_pc_d3d9.log](https://github.com/doitsujin/dxvk/files/7688657/sr2_pc_d3d9.log)

**Comment by EtaYorius** [comment]
I crashed several times after posting that last one. Let me know if you need a new log after each crash.

**Comment by K0bin** [comment]
Probably #1318

**Comment by K0bin** [comment]
Closing this for now because it's probably the good old address space issue and there's not much we can do about that.
