### ISSUE TITLE
Saints Row 3 Remastered crashes on launch

### ISSUE THREAD

**Issue by lajby95** [doitsujin/dxvk#2397]
Saints Row The Third Remastered crashes on launch. Process appears in task manager, memory size grows quickly to about 1.6GB, and then terminates, and the game's crash report window appears.

The game has heavy stuttering and bad fluctuating frametimes, which makes it unplayable for me. DXVK works fine for many people and it fixes these stutters. But for some people, including myself, the game refuses to launch with DXVK.

### Software information
Game: Saints Row The Third Remastered. Crashes on launch, any settings.

### System information
- GPU: GTX1650 Mobile and AMD Vega 10 (crashes on both)
- Driver: Geforce 497.09
- Windows 10 21H1
- DXVK version: 1.9.2

### Apitrace file(s)
- [https://drive.google.com/file/d/1yUwqp-OzFm0JGVwrb6k6evJ0If7LCmqX/view?usp=sharing](https://drive.google.com/file/d/1yUwqp-OzFm0JGVwrb6k6evJ0If7LCmqX/view?usp=sharing)

### Log files
- All logs are here: [logs_github_issue.zip](https://github.com/doitsujin/dxvk/files/7704020/logs_github_issue.zip)
- This includes the crash dump generated by the game itself, and DXVK d3d11 and dxgi logs.

**Comment by K0bin** [comment]
> The game refuses to launch from outside the Epic Games Launcher. Let me know how I can launch the game from epic games, so that it does an apitrace. I tried to do an apitrace with just the game executable, but it did not generate an apitrace file.

Here's a guide on how to do it: https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace

**Comment by doitsujin** [comment]
Trace replays fine here.

This is another classic Windows issue that we cannot provide any sort of support for, if it works for *some* people then clearly DXVK *is* able to run the game and there's a million different reasons why it might be broken for some others.

**Comment by lajby95** [comment]
I updated the AMD drivers and now the game works fine with DXVK, so issue fixed.
