### ISSUE TITLE
Warframe random VK_ERROR_DEVICE_LOST crashes

### ISSUE THREAD

**Issue by Monsterovich** [doitsujin/dxvk#2401]
The game crashes more frequently on open world locations. The crash happens every ~30 min, sometimes rarer.

### Software information
The game runs just fine even on medium/high settings (I have 60-70 fps on open world maps). I tried it on low settings to avoid issues and, unfortunately, it crashes too.
I've never had issues in Warframe on an Intel GPU (Intel HD Graphics 620), but it's a much slower GPU, though. It's barely playable.

I've run many Unreal Engine 4 games on my current GPU, never got a VK_ERROR_DEVICE_LOST crash.

### System information
- GPU: NVIDIA GeForce GTX 960
- Driver: 470.86
- Wine version: wine-7.0-rc1 (Staging)
- DXVK version: 1.9.2

### Log files
- d3d9.log: The game doesn't use d3d9.
- d3d11.log: [Warframe.x64_d3d11.log](https://github.com/doitsujin/dxvk/files/7722889/Warframe.x64_d3d11.log)
- dxgi.log: [Warframe.x64_dxgi.log](https://github.com/doitsujin/dxvk/files/7722891/Warframe.x64_dxgi.log)

Looks like NVidia driver issue? Thoughts?

**Comment by Monsterovich** [comment]
I've bought an extra memory stick (+16GB) and the crashes are gone (it seems).

**Comment by Blisto91** [comment]
@Monsterovich I sadly can't say why it stopped crashing for you.
Has this been true since then?

**Comment by Monsterovich** [comment]
> I sadly can't say why it stopped crashing for you.
> Has this been true since then?

Yes. I also have replaced by GPU with RTX 3060 ti.

**Comment by Monsterovich** [comment]
Crashes are probably caused in situations with low amount of video memory, although I don't know why increasing the amount of RAM fixed it. Probably because of the dual channel memory mode.

**Comment by Blisto91** [comment]
> Yes. I also have replaced by GPU with RTX 3060 ti.
Nice! gz :grin: 

Would you be fine with the issue being closed then? If you run into anymore issues you are ofc welcome to open a new one.
