### ISSUE TITLE
i can't get 1.92 to load in Skyrim, with Nvidia Drivers 471.41

### ISSUE THREAD

**Issue by XDbored1** [doitsujin/dxvk#2402]
i can't get 1.92 to load in Skyrim, with Nvidia Drivers 471.41, and i was wondering if the new version needed newer drivers or something if so what version? does it need a specific newer version of Vulkan?

i can't find anywhere to ask about this so i am posting it as a issue for now

**Comment by XDbored1** [comment]
1.92 is still not loading with driver version, 497.9, vulkan 1.2.182
1.91 still loads

**Comment by K0bin** [comment]
Are you talking about classic Skyrim or Skyrim Special Edition? Please post logs.

**Comment by XDbored1** [comment]
Classic Skyrim and pretty sure there were no logs for 1.9.2 i could post 1.9.1 logs but i don't think those would be useful

**Comment by XDbored1** [comment]
wait i just saw it 32bit vs 64bit did i fuck and copy the wrong dll? probably

**Comment by K0bin** [comment]
You need to copy over the 32bit d3d9.dll right next to the exe of the game. If there are no logs, the game isn't even loading DXVK. I'm closing this for now because this is almost certainly a setup issue. Feel free to reopen if there's an actual bug.

**Comment by XDbored1** [comment]
yeah that was it i still can't find the logs but its working
