### ISSUE TITLE
Devil May Cry HD Collection Fails To Launch Re: DXVK Update

### ISSUE THREAD

**Issue by shklein** [doitsujin/dxvk#2404]
I am testing Devil May Cry HD Collection (631510) on Proton - Experimental (experimental-6.3-20211215) and the game is crashing on launch. On the current Proton version (6.3-8) the game launches but runs into issues elsewhere. In testing a fix for these issues, we found that the version of DXVK currently in Experimental is causing the launch to fail. I ran a bisect to determine the "bad" commit:
---------------------------------------------------------------------------------------------- 
5b725205efd6f69cf9500a4fdfb5ca21c1a862bf is the first bad commit
commit 5b725205efd6f69cf9500a4fdfb5ca21c1a862bf
Author: Philip Rebohle philip.rebohle@tu-dortmund.de
Date: Wed Nov 3 16:07:46 2021 +0100

[dxvk] Introduce DxvkFramebufferInfo

Stores all info that is currently held by the DxvkFramebuffer class,
but is not heap-allocated and will not create an actual framebuffer
object.
--------------------------------------------------------------------------------------------

### Software information
Devil May Cry HD Collection (631510)

### System information
Ubuntu 20.04
- GPU: NVIDIA GeForce RTX 3060 Laptop GPU
- Driver: nvidia-driver-470
- Proton: experimental-6.3-20211215
- DXVK version: 0c2551f8 Merge commit 'v1.9.2-33-g1fd037c'

[dmcLauncher_d3d11.log](https://github.com/doitsujin/dxvk/files/7737325/dmcLauncher_d3d11.log)
[dmcLauncher_dxgi.log](https://github.com/doitsujin/dxvk/files/7737326/dmcLauncher_dxgi.log)

**Comment by doitsujin** [comment]
can we please have an apitrace or something?

**Comment by shklein** [comment]
Site is refusing my uploads for .zip and .gz. Trace can be downloaded here: 
https://www.codeweavers.com/xfer/sklein/dmcLauncher.trace.gz

**Comment by K0bin** [comment]
That says it requires a password.

**Comment by shklein** [comment]
Apologies - I didn't set it up to do that, not sure why. Please try going here: https://www.codeweavers.com/xfer/sklein/DMC/ and using key "dmctrace".

**Comment by doitsujin** [comment]
Thanks; does https://github.com/doitsujin/dxvk/commit/3bfad1e70e73e9098c2540d73d93ebbec728655f fix the issue?

**Comment by shklein** [comment]
Yes, it does.
