### ISSUE TITLE
[Feature Request] enforce a high priority context VK_EXT_global_priority

### ISSUE THREAD

**Issue by mercuriete** [doitsujin/dxvk#2407]
**Motivation:**
I would like to play a game while doing cryptocurrency mining (opencl)

for example I would like to force a high priority context using a environment variable like:

DXVK_FORCE_HIGH_PRIORITY=1 %command%

**expected behaviour:**

all DXVK games run in a high priority context (VK_EXT_global_priority) and I hope to have more fps when using my graphic card on compute tasks at the same time.

**actual behaviour:**

bad fps when mining.

Thanks for your amazing work.

**Comment by Joshua-Ashton** [comment]
No.

**Comment by mercuriete** [comment]
Why not?
Out of scope of this library?
Please, could you explain a little bit more than a simple no?
@Joshua-Ashton 

Remember that you could leave this issue open instead of closed.

**Comment by DadSchoorse** [comment]
If you really need this you can write a vulkan layer that forces high priority. I even wrote one in the past https://github.com/DadSchoorse/vk-force-priority, no idea if it still works tho.

**Comment by mercuriete** [comment]
Thanks, i will try to do It :)
