### ISSUE TITLE
Halo Infinite needs ID3D11Device5::CreateFence()

### ISSUE THREAD

**Issue by nsivov** [doitsujin/dxvk#2409]
This was tested against current proton experimental_6.3. The game is using d3d11 for intro video player, to get as far as CreateFence() you'll need attached winegstreamer workaround for color format. With that next crash according to game's own log is this:

 d3d11Device5->CreateFence( m_state->m_sampleReadFenceValue++, D3D11_FENCE_FLAG_SHARED, __uuidof(ID3D11Fence), reinterpret_cast<void**>(m_state->m_sampleReadFence.GetAddressOf())) failed (HR=0x80004001): Not implemented.

Corresponding dxvk error on missing method appears as well.

[0001-winegstreamer-Return-D3DFMT_A8B8G8R8-from-the-source.txt](https://github.com/doitsujin/dxvk/files/7760692/0001-winegstreamer-Return-D3DFMT_A8B8G8R8-from-the-source.txt)
[crash_info_2 (1).txt](https://github.com/doitsujin/dxvk/files/7760695/crash_info_2.1.txt)

**Comment by doitsujin** [comment]
I'm aware and there's a partial implementation [here](https://github.com/doitsujin/dxvk/tree/d3d11-fence), but given that this is a D3D12 game I'd be very surprised if it didn't require D3D12<->D3D11 interop which we can't really support at the moment.

**Comment by doitsujin** [comment]
Merged fence stuff into master, I'll probably bug Derek to update his patches for the 1.10.x branch too.
