### ISSUE TITLE
Ghost Recon Advanced Warfighter 2 does not render shadows at all

### ISSUE THREAD

**Issue by Alexithymia2014** [doitsujin/dxvk#2410]
Ghost Recon Advanced Warfighter 2 and its predecessor (GRAW) do not render shadows with DXVK or WineD3D. There is an old wine bug that could be relevant, https://bugs.winehq.org/show_bug.cgi?id=38015 something to do with cascaded shadows? 

### Software information
Ghost Recon Advanced Warfighter 2 downloaded from Amazon Games since it's no longer on another online store. I've maxed out the settings but I've also tried disabling Dynamic Shadows or enabling them at low, medium, and high.

### System information
- GPU: AMD Raven Ridge Vega 10
- Driver: Mesa 21.3.2
- Wine version: Tested on 6.21-devel and 7.0-rc2
- DXVK version: Tested on 1.9.2 and latest master (as of two days ago)
- Fedora 35 

### Apitrace file(s)
[Apitrace](https://drive.google.com/file/d/1fAYc6fBldHG-9XnVt26cqSRvY2kSlB9n/view?usp=sharing)

### Log files
- d3d9.log: https://drive.google.com/file/d/1CIp1-ECqnLKarAl59Ka_RON9mvaTMNZI/view?usp=sharing
- d3d11.log: N/A
- dxgi.log:https://drive.google.com/file/d/1L-Sok3HzlLzLmVHJiwU50ozKUmiwKf81/view?usp=sharing

**Comment by doitsujin** [comment]
Looks like all your google drive links require a password.

**Comment by Alexithymia2014** [comment]
> Looks like all your google drive links require a password.

My apologies, I just changed the permissions. Can you try now?

**Comment by Alexithymia2014** [comment]
I got around to installing Windows 11 and the shadows do render when I play. When I drop in the DXVK DLLs next to the game exe, the shadows no longer render.

**Comment by Blisto91** [comment]
@Alexithymia2014 Can i get you to test this issue again?
Your trace is weird when i replay it with either wined3d or dxvk. The world doesn't seem to load in at all with both once you load the game.

**Comment by Alexithymia2014** [comment]
I'll try to recreate the trace for you

**Comment by Alexithymia2014** [comment]
Hi @Blisto91, the shadows work now in 1.10.2! Out of curiosity, was there a specific fix for this?

**Comment by Blisto91** [comment]
Not as far as i know. But there have been some general dx9 fixes which might affect a bunch of games.
Glad to hear  it's working! 🙂
