### ISSUE TITLE
Unable to release video memory

### ISSUE THREAD

**Issue by tkp206093** [doitsujin/dxvk#2413]
In Final Fantasy VII-Remake Intergrade, if you continue to play, the video memory will increase sharply, and then finally the game will crash.

### Software information
Final Fantasy VII-Remake Intergrade, Material: High Shadow: Low Number of Characters: 8.

### System information
- GPU:3080TI
- Driver:497.29
- Wine version: 
- DXVK version:1.9.2

### Log files
- d3d9.log:N/A
- d3d11.log:
[ff7remake__d3d11.log](https://github.com/doitsujin/dxvk/files/7771234/ff7remake__d3d11.log)

- dxgi.log:
[ff7remake__dxgi.zip](https://github.com/doitsujin/dxvk/files/7771235/ff7remake__dxgi.zip)

**Comment by tkp206093** [comment]
I follow this mod guide:
https://www.nexusmods.com/finalfantasy7remake/mods/66?tab=posts&BH=11

**Comment by doitsujin** [comment]
What does "Unable to release video memory" mean in this context?

**Comment by tkp206093** [comment]
> What does "Unable to release video memory" mean in this context? Is that an error message from the game or something?



> What does "Unable to release video memory" mean in this context? Is that an error message from the game or something?

My graphics card has 11GB of video memory.If this module is installed, it will gradually increase during the game. When it exceeds, the game will freeze and the FPS will plummet. At the end of 26GB, the game crashes and automatically shuts down.

**Comment by tkp206093** [comment]
Also https://github.com/doitsujin/dxvk/issues/2412 This not are piracy.
Epic Games\FFVIIRemakeIntergrade\ff7remake.exe will generate log file byte is 0kb
Epic Games\FFVIIRemakeIntergrade\End\Binaries\Win64\ff7remake_.exe will also generate a log file at the same time and it has content
So you can only go to ff7remake_.exe to taket the log file
https://www.nexusmods.com/finalfantasy7remake/mods/66?tab=posts
And share the discussion of this module. I don't know what version other people are using, but everyone said in unison to close the GeForce Experience IN-GAME OVERLAY, otherwise the game will not open smoothly.

**Comment by tkp206093** [comment]
> What does "Unable to release video memory" mean in this context? Is that an error message from the game or something?

![image](https://user-images.githubusercontent.com/29872453/147506479-a6768826-bbd8-474e-9bd7-5f1bcdcba37b.png)
I'm sorry that my English is bad and I can't express it well, just like this post

**Comment by tkp206093** [comment]
> Also #2412 This not are piracy. Epic Games\FFVIIRemakeIntergrade\ff7remake.exe will generate log file byte is 0kb Epic Games\FFVIIRemakeIntergrade\End\Binaries\Win64\ff7remake_.exe will also generate a log file at the same time and it has content So you can only go to ff7remake_.exe to taket the log file https://www.nexusmods.com/finalfantasy7remake/mods/66?tab=posts And share the discussion of this module. I don't know what version other people are using, but everyone said in unison to close the GeForce Experience IN-GAME OVERLAY, otherwise the game will not open smoothly.

![image](https://user-images.githubusercontent.com/29872453/147506635-633b6313-d3da-4474-b03a-ef15e985a6c1.png)

**Comment by tkp206093** [comment]
> > What does "Unable to release video memory" mean in this context? Is that an error message from the game or something?
> 
> ![image](https://user-images.githubusercontent.com/29872453/147506479-a6768826-bbd8-474e-9bd7-5f1bcdcba37b.png) I'm sorry that my English is bad and I can't express it well, just like this post

![image](https://user-images.githubusercontent.com/29872453/147506776-e14819bf-8389-4339-a251-ad07c652c95c.png)

**Comment by tkp206093** [comment]
> Also #2412 This not are piracy. Epic Games\FFVIIRemakeIntergrade\ff7remake.exe will generate log file byte is 0kb Epic Games\FFVIIRemakeIntergrade\End\Binaries\Win64\ff7remake_.exe will also generate a log file at the same time and it has content So you can only go to ff7remake_.exe to taket the log file https://www.nexusmods.com/finalfantasy7remake/mods/66?tab=posts And share the discussion of this module. I don't know what version other people are using, but everyone said in unison to close the GeForce Experience IN-GAME OVERLAY, otherwise the game will not open smoothly.

![image](https://user-images.githubusercontent.com/29872453/147506973-86829385-768f-4d54-978a-1547d05f5cfd.png)

**Comment by tkp206093** [comment]
> Also #2412 This not are piracy. Epic Games\FFVIIRemakeIntergrade\ff7remake.exe will generate log file byte is 0kb Epic Games\FFVIIRemakeIntergrade\End\Binaries\Win64\ff7remake_.exe will also generate a log file at the same time and it has content So you can only go to ff7remake_.exe to taket the log file https://www.nexusmods.com/finalfantasy7remake/mods/66?tab=posts And share the discussion of this module. I don't know what version other people are using, but everyone said in unison to close the GeForce Experience IN-GAME OVERLAY, otherwise the game will not open smoothly.

![image](https://user-images.githubusercontent.com/29872453/147507166-ea0e70f6-1c45-4186-86e5-e3edaa7b02e3.png)

**Comment by tkp206093** [comment]
> Also #2412 This not are piracy. Epic Games\FFVIIRemakeIntergrade\ff7remake.exe will generate log file byte is 0kb Epic Games\FFVIIRemakeIntergrade\End\Binaries\Win64\ff7remake_.exe will also generate a log file at the same time and it has content So you can only go to ff7remake_.exe to taket the log file https://www.nexusmods.com/finalfantasy7remake/mods/66?tab=posts And share the discussion of this module. I don't know what version other people are using, but everyone said in unison to close the GeForce Experience IN-GAME OVERLAY, otherwise the game will not open smoothly.

![image](https://user-images.githubusercontent.com/29872453/147507280-b0bbd383-45e9-4828-aa4f-5f7403136c63.png)

**Comment by tkp206093** [comment]
> Also #2412 This not are piracy. Epic Games\FFVIIRemakeIntergrade\ff7remake.exe will generate log file byte is 0kb Epic Games\FFVIIRemakeIntergrade\End\Binaries\Win64\ff7remake_.exe will also generate a log file at the same time and it has content So you can only go to ff7remake_.exe to taket the log file https://www.nexusmods.com/finalfantasy7remake/mods/66?tab=posts And share the discussion of this module. I don't know what version other people are using, but everyone said in unison to close the GeForce Experience IN-GAME OVERLAY, otherwise the game will not open smoothly.

![image](https://user-images.githubusercontent.com/29872453/147507349-eacfe402-57ec-430c-88e4-74c9029adcce.png)

**Comment by K0bin** [comment]
Can you please not turn this issue into the mirror of an entire NexusMods thread?

**Comment by doitsujin** [comment]
That, and we kind of need an apitrace here. The game is doing some broken shit that *cannot* work properly (creating views with typeless formats and reinterpreting BC1 as BC5 etc) so I kind of need to know what's it's trying to do, and also whether it is trying to use any of the DXGI memory APIs.

**Comment by Oschowa** [comment]
Here is a trace: https://drive.google.com/file/d/1VlNg9FA8ehjhsqMTcZPde9Sazfu_-M8g/view?usp=sharing

**Comment by tkp206093** [comment]
I see have some some one said
Maybe the memory leak with Vulkan is only on Nvidia cards.

**Comment by K0bin** [comment]
You truly deserve better service given how much you paid for DXVK!

**Comment by doitsujin** [comment]
DXVK does not leak memory, it reuses its internal allocations as it always has. It's certainly not the best memory mangement in the world but I doubt it has anything to do with the issue at hand.

**Comment by seanmacky** [comment]
> I just came from a report post of 2018 stating exactly the same about other game The AUDACITY of acting like you dont know what he means when your faulty software has been leaking memory since always in multitude of games, god according to the last author post it is even leaking memory adresses……. And hes like “i just wont rewrite it to handle memory like dx11 does” (aka PROPERLY)…. Why dont you just say you dont care about mid-end cards having rampant issues? Its always one of you two saying “yes, its this, its that” but the thing NEVER gets fixed.

Well said !  He IS PAID to have this working correctly.
I.guess gaslighting some people is easier than fixing the issue. 🐔

**Comment by seanmacky** [comment]
> I just came from a report post of 2018 stating exactly the same about other game The AUDACITY of acting like you dont know what he means when your faulty software has been leaking memory since always in multitude of games, god according to the last author post it is even leaking memory adresses……. And hes like “i just wont rewrite it to handle memory like dx11 does” (aka PROPERLY)…. Why dont you just say you dont care about mid-end cards having rampant issues? Its always one of you two saying “yes, its this, its that” but the thing NEVER gets fixed.
![Screenshot_20220106-201038](https://user-images.githubusercontent.com/66341372/148367033-87b80143-fd5b-437f-a08f-ede2dcc5b0d2.png)

**Comment by Miepee** [comment]
I get that it can be infuriating if you can't play a game you really want to play, but the behaviour here just achieves that the devs don't even want to fix this issue.
If you want this issue fixed, try to help with apitraces, reproduction cases etc. 
Causing drama here won't lead to anything.

To throw some ideas in here:
- I don't see the WINE version being specified in the first comment
- Can this be reproduced when compiling dxvk from source?
- Can this be reproduced on AMD GPUs?

**Comment by seanmacky** [comment]
> DXVK does not leak memory, it reuses its internal allocations as it always has. It's certainly not the best memory mangement in the world but I doubt it has anything to do with the issue at hand.

Perhaps if we contact your employer and email the screenshots highliting the disgusting disdain you have  for people looking for help... What was it .."entitled cesspool" . That will look good on your resume or I might email Phoronix so they can do an article

**Comment by LapisRain** [comment]
> Perhaps if we contact your employer and email the screenshots highliting the disgusting disdain you have for people looking for help... What was it .."entitled cesspool" . That will look good on your resume or I might email Phoronix so they can do an article

Unfortunately `entitled idiot complains on GitHub issue` usually doesn't make for a good article.
