### ISSUE TITLE
`setup_dxvk.sh` issue with Wine-GE

### ISSUE THREAD

**Issue by CommandMC** [doitsujin/dxvk#2415]
Currently, the `setup_dxvk.sh` script uses `wine --version` to check if the wine executable is valid: If the output contains "wine", it's considered a wine executable.  
This presents an issue with Wine-GE, as their version string is `7.0rc2-GE-1 (Staging)`.

I've asked around on the GE discord and the people there said that using `wineserver --version` would be better. In Wine-GE, this correctly returns "Wine 7.0-rc2".

In general, I'm not really sure why this check is present. Has there ever been a case where someone specified an unrelated executable as their Wine executable?

**Comment by braiam** [comment]
This check has been there since the [creation of the script.](https://github.com/doitsujin/dxvk/commit/174dbcafa6cfce1f117f7b608d54fc4847cea355) So "why" might be not apparent. Probably check that the wine executable is a wine executable.

**Comment by SveSop** [comment]
> This check has been there since the [creation of the script.](https://github.com/doitsujin/dxvk/commit/174dbcafa6cfce1f117f7b608d54fc4847cea355) So "why" might be not apparent. Probably check that the wine executable is a wine executable.

The check is there because when making dlloverrides you use wine's regedit function to input data in the registry (the overrides). So the general idea is to actually check that you have wine installed before attempting to add dlloverrides. If wine is not present - abort 😄 

[setup_dxvk.sh](https://github.com/doitsujin/dxvk/blob/master/setup_dxvk.sh#L97-L112)

**Comment by shmerl** [comment]
Sounds like a problem with GE. Why did it drop Wine from the version output?

**Comment by Blisto91** [comment]
Is this still an issue with Wine-GE?
If yes i think you are welcome to open a PR so that the script can accept both `wine --version` `wineserver --version` containing the string "wine"

**Comment by Blisto91** [comment]
Closure reason https://github.com/doitsujin/dxvk/pull/3097
