### ISSUE TITLE
[Skyrim Special Edition] No Text In Books

### ISSUE THREAD

**Issue by ccuntd** [doitsujin/dxvk#2419]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
Preferably record the trace on Windows, or wined3d if possible.

I tried tracing it, but the game turned into a slideshow 1 frame per minute (in the menu)
(unmodded)

**Reports with no log files will be ignored.**

### Software information
Skyrim Special Edition

### System information
- GPU: AMD ATI Radeon RX 6600M
- Driver: vulkan radeon (mesa, tried amdvlk, but didn't launch)
- Wine version: Proton-Ge-Custom-7.0rc3-GE-1 (also with normal proton)
- DXVK version: Don't know how to see, but newest from https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/7.0rc3-GE-1 (released today)

### Apitrace file(s)
- Put a link here
didn't work :(

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:
none there

**Comment by ccuntd** [comment]
if you wanna take a look at this fat boy:
[SkyrimSE.trace](https://drive.google.com/file/d/1VqGvFVmaMkpWGUxzYyKjckg5REtT0G_3/view?usp=sharing)
40.2MB in 3 frames? lol.

**Comment by Oschowa** [comment]
If the trace is only 3 frames and doesn't actually show the missing text in the books, it's useless. You're going to have to suffer through the low performance to get a useful trace of the issue. If you are using proton, then just copying the d3d11, dxgi and dxgiretrace dlls from apitrace next to the game .exe and doing nothing else should trace the game with dxvk and be reasonably fast. The trace will be in the `drive_c/users/steamuser/Desktop` directory of the wineprefix.

**Comment by ccuntd** [comment]
i cant even input, my i tried it until now

**Comment by rsw0x** [comment]
put the example dxvk.conf in the folder next to the executables(I believe it should be picked up this way when using proton anyways) and enable apitrace mode options, it should run much faster when using apitrace.
https://github.com/doitsujin/dxvk/blob/master/dxvk.conf

apitrace mode options are at the bottom

the traces are highly compressable btw

**Comment by ccuntd** [comment]
thanks, i'll try it

**Comment by ccuntd** [comment]
doesn't work, i'll spam until i get it done. see ya

**Comment by ccuntd** [comment]
worked, after forcing the working directory, (chose wrong one automatically)

**Comment by ccuntd** [comment]
proton-ge loaded into my mod loader when it shouldn't automatically, and it was some mod.
