### ISSUE TITLE
Metal Gear Solid V: The Phantom Pain Crashes

### ISSUE THREAD

**Issue by romulasry** [doitsujin/dxvk#242]
In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!
-- Can't get this to work

### Software information
Metal Gear Solid V: The Phantom Pain

### System information
- GPU: RX 480
- Driver: Amdgpu
- Wine version:  3.5
- DXVK version: git20180404

### Apitrace file(s)
- Put a link here

~/.wine/drive_c/Program Files (x86)/Steam/steamapps/common/MGS_TPP> wine apitrace-msvc/x86/bin/apitrace.exe trace -a dxgi mgsvtpp.exe
inject: error: failed to execute mgsvtpp.exe (2)
002e:fixme:kernelbase:AppPolicyGetProcessTerminationMethod 0xfffffffa, 0x33fe3c
0009:fixme:kernelbase:AppPolicyGetProcessTerminationMethod 0xfffffffa, 0x33fe3c

**How do I fix this? Could someone link me to the right file to use?**

### Log files
- d3d11.log: [mgsvmgo_d3d11.log](https://github.com/doitsujin/dxvk/files/1878326/mgsvmgo_d3d11.log)
- dxgi.log: [mgsvmgo_dxgi.log](https://github.com/doitsujin/dxvk/files/1878325/mgsvmgo_dxgi.log)

**Comment by AccountOneOff** [comment]
For the apitrace try this:

- Copy `apitrace.exe` to the folder that contains the game's exe. From the looks of it `MGS_TPP`
- Copy the apitrace lib folder `apitrace-msvc/x64/lib` one folder lower. In this case `steamapps/common`
- Rename `mgsvtpp.exe` to `mgsvtpporig.exe`
- Rename `apitrace.exe` to `mgsvtpp.exe`
- Right-click MGSV > Properties > Set launch options: `trace -a dxgi mgsvtpporig.exe`

Then launch the game through Steam.

**Comment by romulasry** [comment]
Seem like it won't even launch in vanilla wine, let me post the bug there.

**Comment by romulasry** [comment]
Wine bug.
