### ISSUE TITLE
Input issues in Dark Souls II

### ISSUE THREAD

**Issue by StenniHub** [doitsujin/dxvk#2424]
Hey, as I speedrun Dark Souls II I still often have to boot up the original game, and it has quite a few issues on modern hardware and Windows 10/11. I know using DXVK directly on Windows is not the intended use case, but it helps greatly for me with some inconsistencies in frame rate and stuttering. I have a couple issues still though that I handle with workarounds, but it would be awesome if someone could look into it as it has been many years since I really touched C/C++. I have compiled new DLLs from the master branch, which included some rendering fixes for D3D9 that are working nicely.

First issue is when running the game windowed it automatically goes into borderless, something it doesn't do without DXVK. I thought this feature was nice, but it seems the mouse cursor position is not correct, making it difficult to use menus. If I use something like Borderless Gaming on top it seems to fix the issue, probably by moving the window position as it goes into borderless, which DXVK does not seem to do (unless this is some issue in how windows handles it).

Second issue is if I play fullscreen. This fixes the mouse position mentioned above but instead I get a pretty noticeable increase in input lag (at least with controller). Especially camera movements or changing character direction get a very sluggish feel.

I can put together some log files etc. if needed, but it probably is not that helpful as there is no crash or anything.

### Software information
Game: Dark Souls II (mostly tested on patch 1.02, but applies for latest patch)
All settings on highest, motion blur and depth of field off, 1440p resolution

### System information
- GPU: RTX 3080
- Driver: 497.29
- CPU: Ryzen 5900x
- Wine version: NA
- DXVK version: 1.9.2 (master branch)

**Comment by StenniHub** [comment]
Can also confirm that offsetting the initial window position more makes the offset in mouse cursor position even worse, so it is definitely related.

**Comment by K0bin** [comment]
Are you talking about the original DS2 or the Scholar of the First Sin version?

**Comment by StenniHub** [comment]
> Are you talking about the original DS2 or the Scholar of the First Sin version?

The original version. I can also check scholar tomorrow since I have not played it recently, but I haven't had as many issues with it in the past as it uses D3D11.

**Comment by K0bin** [comment]
Can you make an apitrace? I don't have the original version.

**Comment by lextra2** [comment]
Mouse offset in menus could be due to incorrect window resolution/aspect ratio. IIRC the same thing happens in sleeping dogs on windows with dxvk.

And increased input lag in exclusive fullscreen could be due to vulkan always selecting the lowest "60hz" (59.94 over 60.00) of your displays EDID. This Hz thing has been an issue forever with almost all vulkan apps.

**Comment by StenniHub** [comment]
> Can you make an apitrace? I don't have the original version.

I tried downloading the apitrace files, but unfortunately the links in the trace guide are dead :(

**Comment by StenniHub** [comment]
> Mouse offset in menus could be due to incorrect window resolution/aspect ratio. IIRC the same thing happens in sleeping dogs on windows with dxvk.

I am pretty confident it is not due to aspect ratio/resolution since the window does not appear resized in any way. What I meant by offsetting the window above is that I moved the window further out from the top left corner. This would offset the registered mouse position in game by a similar/same amount when it went back into borderless.

> And increased input lag in exclusive fullscreen could be due to vulkan selecting 60hz from your displays edid. this hz thing has been an issues for many vulkan apps for a very long time now (on windows anyways).

Could be, it does seemingly put my screen into 60Hz and freesync is not working too well (black screens for a while when tabbing out etc.). Not sure this alone is enough to account for the large increase in input lag though, because I used to set my old monitor manually to 60Hz when playing this game in the past without DXVK and input lag was much better.

**Comment by StenniHub** [comment]
@K0bin I am experiencing the same issues when using DXVK for the scholar version. The game also doesn't seem to want to close properly when I use DXVK, so I have to force close it with task manager after the window disappears.

**Comment by K0bin** [comment]
That's an entirely different issue from what you described before. DXVK got a change to make it exit cleanly after 1.9.2. Try a build of master for that particular issue.

**Comment by StenniHub** [comment]
> That's an entirely different issue from what you described before. DXVK got a change to make it exit cleanly after 1.9.2. Try a build of master for that particular issue.

Yes I did not have that issue in the original version of Dark Souls II, only in scholar. I also built the DLLs for that from master.

**Comment by K0bin** [comment]
If the exit issue in Scholar persists, please open a separate issue for that. Scholar of the First Sin uses D3D11 and the original uses D3D9, so the problem is unrelated. I can't reproduce that though. I played through Scholar of the First Sin a few weeks ago  using Proton Experimental (which ships DXVK master) and it ran perfectly start to finish.

We also still need the apitrace of the original game to look into the other issues.

**Comment by StenniHub** [comment]
@K0bin as I mentioned earlier I was not able to download the required files for generating an apitrace for d3d9. I tried the links in this guide: https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace but just get an error. Is there somewhere else I can get these files?

I also wanna make it clear that the issues I originally submitted for D3D9 were also reproducable for Scholar, both the mouse cursor offset in windowed and the input lag in fullscreen. Since you have Scholar, did you attempt to play in windowed, drag the window a little bit away from the top right corner and then attempt to use the mouse in menus inside the game?

**Comment by K0bin** [comment]
https://github.com/apitrace/apitrace/releases/download/10.0/apitrace-10.0-win32.7z

This link works.

**Comment by K0bin** [comment]
I tried the main menu of Scholar in windowed mode and it's neither borderless nor is the mouse cursor off.

**Comment by StenniHub** [comment]
Ok, that is unfortunate that it does not seem reproducible in wine. I have no idea what causes it, but the input lag I get using a controller (and I tested two different ones) is noticeably higher for me in fullscreen only when I run through DXVK. I tried a few different compatibility settings since windows is apparently doing something funky then to make it borderless fullscreen, but it had no effect. I uploaded an apitrace for the original game here (which I could not manage to generate using the d3d9 and dxgi DLLs from DXVK) in case there is still some way it can be useful: https://drive.google.com/file/d/1eK4c9Y1nYK9iRVvcKNTIxekGLGyo5fwE/view?usp=sharing 

Any tips/guide for how to set up breakpoints for debugging? Haven't worked with creating DLLs before and re-compiling with logging here and there did not really get me anywhere so far in figuring stuff out.

**Comment by StenniHub** [comment]
Haven't found a solution to the input lag in fullscreen, but after testing some different settings in dxvk.conf I figured out how to make the game behave as expected for windowed. Seems the culprit is the built in vsync (and potentially conflicts with g-sync) that you can't normally turn off in game, so adding these to the conf file stopped the game acting as exclusive fullscreen for me (works for both regular DS2 and Scholar of the First Sin):

dxgi.syncInterval = 0
dxvk.tearFree = True


Alternatively just adding this also did the trick for me for d3d9:

d3d9.enableDialogMode = True
