### ISSUE TITLE
The Witcher 2 EE (GOG) crashing issues

### ISSUE THREAD

**Issue by MaartenVaanThomm** [doitsujin/dxvk#2428]
Hi Guys,

I have strange crashing on Witcher 2 lately. I have the latest GOG version. I thought it was beacuse of 4k textures, but I've reinstalled the game and installed 2k version mod instead. The outcome is the same, game is still crashing. I have no idea what to do. I'm using ENB and it's libraries run dxvk injector as a proxy. Could it be the reason? I'm attaching my log, any help would be much appreciated

### System information
- GPU: 16 GB 130W RTX 3080 (Laptop) 
- Driver: 497.29 (latest)
- Wine version: not sure what it is, not using? (I'm on Win10)
- DXVK version: 1.9.2 (latest)

### Log files
[witcher2_d3d9.log](https://github.com/doitsujin/dxvk/files/7836301/witcher2_d3d9.log)

**Comment by K0bin** [comment]
Known issue: #1318

Try creating a DXVK config file with the line `d3d9.evictManagedOnUnlock = True`. More info about that is in the README and in https://github.com/doitsujin/dxvk/blob/master/dxvk.conf.

**Comment by MaartenVaanThomm** [comment]
Thanks, which 3GB patchers you have on your mind? Never seen anything like that. I'm aware only of the method of checking if app can handle >2GB address space in CFF explorer. I've checked that for witcher2.exe and it is ticked

**Comment by K0bin** [comment]
I don't have any particular one in mind but a quick Google search should find one.

But it seems to be already large address space (3GB) aware, going by your findings.

So yeah, try the config option and if that doesn't help, get rid of the texture mod.

**Comment by MaartenVaanThomm** [comment]
Thanks, and if I am combining ENB libraries (d3d9.dll file) with dxvk (dxvk.dll and dxgi.dll files), then in dxvk.conf the line should look like this:

d3d9.evictManagedOnUnlock = True

or this?

dxvk.evictManagedOnUnlock = True

**Comment by K0bin** [comment]
`d3d9.evictManagedOnUnlock = True`

**Comment by MaartenVaanThomm** [comment]
I've enabled it and game didn't crashed since then (played approx. 3h), but now strange microstuttering occured. Any adviced how to get rid of it?

**Comment by K0bin** [comment]
That's why the option is not enabled by default. Some games rely on having the contents of textures available to the CPU immediately, so we must keep them in RAM. But keeping them in RAM leads to crashes because we run out of address space.
There is no solution right now.

**Comment by MaartenVaanThomm** [comment]
I see, would it make sense to try BCDEDIT /set IncreaseUserva (#MB) on  64 bit win 10?
I have 32 gigs of ram, maybe setting this to i.e 10 gb would fix the crashing?
