### ISSUE TITLE
DXVK_CUSTOM_VENDOR_ID and DXVK_CUSTOM_DEVICE_ID not working

### ISSUE THREAD

**Issue by MordragTV** [doitsujin/dxvk#243]
I am starting dxvk with DXVK_CUSTOM_VENDOR_ID=1002 DXVK_CUSTOM_DEVICE_ID=6810
nevertheless the DXVK_HUD shows that my integrated GPU is used.
I tried to start the game with `env DRI_PRIME=1` ,wich i am using for steam games but that isnt working too.

### Software information
I try to play Gothic 2 ,with the integrated gpu everything works fine its just extremly laggy.

### System information
- GPU: Radeon R9 270x ,intel hd 4000
- Driver: Mesa 18.0
- Wine version: Wine Staging Nine 3.5
- DXVK version: e06300d with 2 line fix (see [Gothic 2 Thread](https://github.com/doitsujin/dxvk/issues/200)

### Log files
- d3d11.log: [d3d11](https://pastebin.com/g5RrrbPz)
- dxgi.log: [dxgi](https://pastebin.com/sKCLGffq)

**Comment by Yardanico** [comment]
DXVK_CUSTOM_VENDOR_ID and DXVK_CUSTOM_DEVICE_ID  are ONLY used to fake GPU model for a game, not to change between integrated and discrete GPU

**Comment by MordragTV** [comment]
Oh ok than this can be closed

**Comment by TiZ-EX1** [comment]
In addition to `DRI_PRIME=1`, you also need `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json`. Adjust the paths according to where they are on your system.

**Comment by LeJimster** [comment]
Is there a list of vendor id and device id's for reference?  The last time I tried to launch Alan Wake with DXVK, the game was detecting my card as a Radeon 9300 or something ancient and failed to launch.  I wanted to try DXVK_CUSTOM_VENDOR_ID and DXVK_CUSTOM_DEVICE_ID to see if it helped, but I couldn't find any details.

**Comment by Guy1524** [comment]
@LeJimster You just need to look it up.  Searching RX 480 PCI ID gives me this on google: 

https://www.techpowerup.com/vgabios/184327/amd-rx480-8192-160603

Device Id: | 1002 67DF

So the Vendor ID is 1002 and the Device ID is 67DF
