### ISSUE TITLE
[d3d9] Dungeons Fighter Online (Steam ID 495910) has button text partially missing

### ISSUE THREAD

**Issue by gofman** [doitsujin/dxvk#2430]
After starting the actual game from launcher some buttons have text partially missing. E. g, buttons at the bottom right to "Start game": " erver" instead of "Server" and "  it  ame" instead of "Exit game". There is similarly missing text elsewhere. After doing something (like connecting to another server) the pattern of missing letters changes.

The game's launcher currently does not start in released Wine or Proton (needs some WIP patches) but the issue is reproducible on Windows with dxvk's d3d9.dll dropped in.

Incidentally the same issue happens with both dxvk and wined3d under Wine.

I have partially debugged the issue and suppose that has something to do with the game expecting persistent texture locking memory addresses. The attached hack to wined3d (for illustration) fixes the issue.

The apitrace seems to break as well with the game probably around the same issue. The apitrace recorded on Windows replays without any text on the buttons at all on the same Windows machine (all that with native Windows d3d9) and similarly on Linux.
[test.txt](https://github.com/doitsujin/dxvk/files/7839495/test.txt)

**Comment by K0bin** [comment]
Do you perhaps also know what kind of resource causes the problem? Specifically the D3DUSAGE flags and the D3DPOOL used to create it and the D3DLOCK flags passed when locking it?

**Comment by K0bin** [comment]
Fixed by the PR.
