### ISSUE TITLE
Fatal frame project zero maiden ID3D11Device::OpenSharedResource implementation

### ISSUE THREAD

**Issue by Gaming1992** [doitsujin/dxvk#2434]
I tried fatal frame project zero maiden,but when i start a new game i get an error ID3D11Device::OpenSharedResource implementation I'm using linux mint 20.2, kernel 5.4.0.74 and wine 7.0 rc4 stagging, does anyone know how to fix the game

**Comment by doitsujin** [comment]
We can't support shared resources at the moment.
