### ISSUE TITLE
Games Refuse to launch with latest nvidia 511.23 drivers

### ISSUE THREAD

**Issue by antisect** [doitsujin/dxvk#2435]
On windows using the latest nvidia 511.23 drivers any game using dxvk doesn't launch, worked fine on the previous drivers.
No error or anything, and all logfiles are blank

### System information
- GPU: rtx 3080ti
- Driver: 511.23
- Wine version: 
- DXVK version:  1.9.3

**Comment by doitsujin** [comment]
There's nothing we can do here. If the log files are empty, this means that pretty much none of our code even gets executed.

**Comment by antisect** [comment]
yeah its weird, just reverted back to the previous NVidia drivers and everything is fine.
tried 511.23 again and nothing launches and no logfiles :/

**Comment by doitsujin** [comment]
Random guess but we had something similar happen on Intel before, if the Vulkan driver loads the D3D runtime it'll be stuck in an infiite recursion. Again, this cannot be fixed on our end and the only solution is to not use DXVK on such drivers.

**Comment by antisect** [comment]
managed to fix it by disabling Ansel using NvCameraConfiguration.exe.
https://nvidia.custhelp.com/app/answers/detail/a_id/4932/~/my-game-ready-driver-no-longer-has-program-files%5Cnvidia-corporation%5Cansel

Ansel On:
Game refuses to launch even though task is running in taskmanager (have to force close game in task manager)

Ansel Off (using the above nvidia tool):
Everything works fine
