### ISSUE TITLE
Steam flatpak working badly with dxvk version of dxgi?

### ISSUE THREAD

**Issue by Keelhauled** [doitsujin/dxvk#2436]
Dxvk dxgi is spamming something that greatly reduces game fps and prevents changing resolution, window state and refresh rate.
Problem can be fixed by using the wine version of dxgi with `WINEDLLOVERRIDES="dxgi=b"`.
I haven't seen anyone else with this issue so maybe it's the flatpak steam.

### Software information
Monster Hunter Rise
Flatpak version of Steam

### System information
- GPU: Nvidia GTX 2070
- Driver: 495.46
- Wine version: 
- DXVK version: 1.9.3

### Log files
- dxgi.log: [MonsterHunterRise_dxgi.log](https://github.com/doitsujin/dxvk/files/7872369/MonsterHunterRise_dxgi.log)
- proton log: [steam-1446780.log](https://github.com/doitsujin/dxvk/files/7872372/steam-1446780.log)

**Comment by doitsujin** [comment]
What is it spamming exactly? The log looks very short, don't really see any spamming in there.

**Comment by Keelhauled** [comment]
The proton log is the one with the spam

**Comment by Whatcookie** [comment]
I have the exact same issue (unable to change resolution, and reduced framerate) when not running with `WINEDLLOVERRIDES="dxgi=b"`. The issue doesn't seem to be related to flatpak steam since I also have the issue, not using flatpak steam.

**Comment by Keelhauled** [comment]
@Whatcookie Do you also have the 495.46 driver? Maybe running arch as well? I'm struggling to think of things that could affect this from the outside since proton is very self contained.

**Comment by Oschowa** [comment]
@Whatcookie uses a RX570 with RADV on Arch. On my system (6700xt, RADV, Arch) i can't seem to reproduce this problem with dxvk's dxgi. Here is a WINEDEBUG="trace+dxgi" log with wine's dxgi in case it is helpful in any way 
[steam-1446780.zip](https://github.com/doitsujin/dxvk/files/7875676/steam-1446780.zip)

**Comment by Blisto91** [comment]
@Keelhauled Is this still an issue with the newest steam flatpak and newer dxvk (like in proton experimental) ?

**Comment by Keelhauled** [comment]
I'd say this can be closed, flatpak steam and runtime steam to have same fps now.
