### ISSUE TITLE
DXVK 1.9.3 extremely poor performance on FFXIV

### ISSUE THREAD

**Issue by Raymyn** [doitsujin/dxvk#2438]
When using DXVK 1.9.3 with Final Fantasy XIV, the game launches and is only able to run at 1-8 FPS with minimal CPU usage and 100% GPU usage. Running with 1.9.2 works flawlessly.

Visually comparing the log files between 1.9.2 and 1.9.3, I am only noticing the mention of `info:  DXGI: NvAPI workaround enabled, reporting AMD GPU` as the difference. Everything else appears to be the same.

### Software information
Game: Final Fantasy XIV

### System information
- GPU: NVIDIA RTX 3060 Laptop
- Driver: 495.46.0
- Wine version: 6.21
- DXVK version: 1.9.3

### Log files
I included both 1.9.2 and 1.9.3 log files for comparison.

- d3d11.log: 
[1.9.3-ffxiv_dx11_d3d11.log](https://github.com/doitsujin/dxvk/files/7875612/1.9.3-ffxiv_dx11_d3d11.log)
[1.9.2-ffxiv_dx11_d3d11.log](https://github.com/doitsujin/dxvk/files/7875613/1.9.2-ffxiv_dx11_d3d11.log)
- dxgi.log: 
[1.9.3-ffxiv_dx11_dxgi.log](https://github.com/doitsujin/dxvk/files/7875606/1.9.3-ffxiv_dx11_dxgi.log)
[1.9.2-ffxiv_dx11_dxgi.log](https://github.com/doitsujin/dxvk/files/7875614/1.9.2-ffxiv_dx11_dxgi.log)

**Comment by doitsujin** [comment]
Works flawlessly on my mobile 2060 as well as on my desktop.

**Comment by Raymyn** [comment]
Unfortunately, that setting was enabled after I noticed I had the issue. Was trying it per the recommendation of someone on a Discord I am part of. I attached the new log files below, with the setting disabled... Still extremely poor performance.
[ffxiv_dx11_d3d11.log](https://github.com/doitsujin/dxvk/files/7875740/ffxiv_dx11_d3d11.log)
[ffxiv_dx11_dxgi.log](https://github.com/doitsujin/dxvk/files/7875741/ffxiv_dx11_dxgi.log)

As for the error message, yeah, that's what I was told as well during troubleshooting, but that was the only discrepancies that I could see :(.

**Comment by LinuxDonald** [comment]
I have the same problem too with 1.9.3.
1.9.2 works.

I have an laptop with Intel gpu and nvidia 3060.

**Comment by Raymyn** [comment]
If I can figure out how to successfully install the mingw-w64 compiler on Fedora 35, I was going to try reverting commits. Since LinuxDonald has a 3060 as well, wonder if it is specific to the RTX 3060 Mobile and/or other 30-series cards?

**Comment by Raymyn** [comment]
So, interestingly, the issue for the extreme performance loss was the commit that implemented the fix for FFXIV.
[[util] Shrink Nvidia HVV heap for Final Fantasy XIV ](https://github.com/doitsujin/dxvk/commit/4c88335f665a9b5c612374672fe2f4236aa67f27)

Removing this commit, FFXIV booted normally for me, with flawless performance on 1.9.3. I also tested setting `dxvk.shrinkNvidiaHvvHeap = False` in the dxvk.conf file, and FFXIV launched on the official released 1.9.3 without issue. Below is the attached logs for 1.9.3 with the override in the dxvk.conf file.

[ffxiv_dx11_d3d11.log](https://github.com/doitsujin/dxvk/files/7876130/ffxiv_dx11_d3d11.log)
[ffxiv_dx11_dxgi.log](https://github.com/doitsujin/dxvk/files/7876131/ffxiv_dx11_dxgi.log)

Though, why can I put `dxvk.shrinkNvidiaHvvHeap = True` in the conf file for 1.9.2, and not have issues? This is extremely confusing :(.

**Comment by doitsujin** [comment]
Weird, the game was working fine before Nvidia even *had* a HVV heap.....

I'm getting seriously annoyed with this, the game has extreme performance issues if we **don't** limit the HVV allocation size (#2210), and now on *some* systems it have extreme performance issues if we **do** limit it. What the hell is going on here and what the absolute fuck am I supposed to do now?

**Comment by doitsujin** [comment]
Ah, wait a minute.

Do you have resizeable BAR enabled?

**Comment by doitsujin** [comment]
Does https://github.com/doitsujin/dxvk/tree/hvv-rbar-fix resolve this? Build [here](https://github.com/doitsujin/dxvk/actions/runs/1703092426) (in progress at the time of writing).

**Comment by Raymyn** [comment]
Yep. That build does appear to work.
[ffxiv_dx11_d3d11.log](https://github.com/doitsujin/dxvk/files/7876240/ffxiv_dx11_d3d11.log)
[ffxiv_dx11_dxgi.log](https://github.com/doitsujin/dxvk/files/7876241/ffxiv_dx11_dxgi.log)

**Comment by LinuxDonald** [comment]
Thank you it works :)

**Comment by doitsujin** [comment]
Merged.
