### ISSUE TITLE
Poor performance for God of War PC

### ISSUE THREAD

**Issue by MrSupersaiyan** [doitsujin/dxvk#2439]
I know the game dropped recently and this software isn't optimized for it. Can you please add support for GOW for GPUs that don't have Directx Feature 11_1.  My integrated graphics has 12_1 support and but my older GPU 960M which far outperforms any integrated graphics card doesn't have it. Thanks to NVIDIA for abandoning older GPU users.

**Comment by doitsujin** [comment]
DXVK already supports FL 11_1 on all Nvidia and AMD GPUs that can run it.

GoW performs poorly on Nvidia at the moment, that is most likely a driver issue and not something we can fix on our end.
