### ISSUE TITLE
Days gone

### ISSUE THREAD

**Issue by Dzafoo** [doitsujin/dxvk#2440]
Hi, its possible that you check if its possible days gone with dxvk 1.9.3? I tryed it with 1.7.14 and the game start but with 3fps and no textures. When i tryed dxvk 1.9.3 the game crashed maybe after 5 seconda after i started it. Thank you

**Comment by Dzafoo** [comment]
this is the d3d11.log, i dont know if this help you

warn:  D3D11CoreCreateDevice: Adapter is not a DXVK adapter
info:  Game: DaysGone.exe
info:  DXVK: v1.9.2-mac-2-g8c27a3f5
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  Device properties:
info:    Device name:     : Apple M1 Pro
info:    Driver version   : 0.2.1911
info:  Enabled device extensions:
info:    VK_EXT_host_query_reset
info:    VK_EXT_robustness2
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_driver_properties
info:    VK_KHR_image_format_list
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 1
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 1
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 1
info:    drawIndirectFirstInstance              : 1
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 0
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 0
info:    vertexPipelineStoresAndAtomics         : 0
info:    fragmentStoresAndAtomics               : 1
info:    shaderImageGatherExtended              : 1
info:    shaderStorageImageExtendedFormats      : 0
info:    shaderStorageImageReadWithoutFormat    : 1
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 0
info:  VK_EXT_4444_formats
info:    formatA4R4G4B4                         : 0
info:    formatA4B4G4R4                         : 0
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 0
info:    customBorderColorWithoutFormat         : 0
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 0
info:  VK_EXT_extended_dynamic_state
info:    extendedDynamicState                   : 0
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 0
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 0
info:    robustImageAccess2                     : 1
info:    nullDescriptor                         : 0
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 0
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 0
info:  DXVK: Using 6 async compiler threads
info:  DXVK: Read 384 valid state cache entries
info:  DXVK: Using 6 compiler threads
info:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
warn:  D3D11CoreCreateDevice: Adapter is not a DXVK adapter
info:  Game: DaysGone.exe
info:  DXVK: v1.9.2-mac-2-g8c27a3f5
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  Device properties:
info:    Device name:     : Apple M1 Pro
info:    Driver version   : 0.2.1911
info:  Enabled device extensions:
info:    VK_EXT_host_query_reset
info:    VK_EXT_robustness2
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_driver_properties
info:    VK_KHR_image_format_list
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 1
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 1
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 1
info:    drawIndirectFirstInstance              : 1
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 0
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 0
info:    vertexPipelineStoresAndAtomics         : 0
info:    fragmentStoresAndAtomics               : 1
info:    shaderImageGatherExtended              : 1
info:    shaderStorageImageExtendedFormats      : 0
info:    shaderStorageImageReadWithoutFormat    : 1
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 0
info:  VK_EXT_4444_formats
info:    formatA4R4G4B4                         : 0
info:    formatA4B4G4R4                         : 0
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 0
info:    customBorderColorWithoutFormat         : 0
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 0
info:  VK_EXT_extended_dynamic_state
info:    extendedDynamicState                   : 0
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 0
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 0
info:    robustImageAccess2                     : 1
info:    nullDescriptor                         : 0
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 0
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 0
info:  DXVK: Using 6 async compiler threads
info:  DXVK: Read 384 valid state cache entries
info:  DXVK: Using 6 compiler threads
info:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
err:   DxvkGraphicsPipeline: Failed to compile pipeline
err:     vs  : VS_5308bfc181737a1a8a14dab942c8d221b452b5f0
err:     gs  : GS_76236841d41d77ba77dcad0869fc375cbf3da1b7
err:     fs  : FS_e97b32badfb1083514a753d542b4a841e166044d
err:     attr 0 : location 0, binding 0, format VK_FORMAT_R32G32B32A32_SFLOAT, offset 0
err:     binding 0 : binding 0, stride 16, rate 0, divisor 0
err:   DxvkGraphicsPipeline: Failed to compile pipeline
err:     vs  : VS_5308bfc181737a1a8a14dab942c8d221b452b5f0
err:     gs  : GS_76236841d41d77ba77dcad0869fc375cbf3da1b7
err:     fs  : FS_b2ea3dba2a11bc5debbac55ca3fce4de82099eaf
err:     attr 0 : location 0, binding 0, format VK_FORMAT_R32G32B32A32_SFLOAT, offset 0
err:     binding 0 : binding 0, stride 16, rate 0, divisor 0
err:   DxvkGraphicsPipeline: Failed to compile pipeline
err:   DxvkGraphicsPipeline: Failed to compile pipeline
err:     vs  : VS_5308bfc181737a1a8a14dab942c8d221b452b5f0
err:     vs  : VS_5308bfc181737a1a8a14dab942c8d221b452b5f0
err:     gs  : GS_76236841d41d77ba77dcad0869fc375cbf3da1b7
err:     gs  : GS_76236841d41d77ba77dcad0869fc375cbf3da1b7
err:     fs  : FS_3c951eb08b42417670ccc2b2bb64c388b9ba5024
err:     fs  : FS_f10848293396e8fc3651d68531f8a7a53aef0c29
err:     attr 0 : location 0, binding 0, format VK_FORMAT_R32G32B32A32_SFLOAT, offset 0
err:     attr 0 : location 0, binding 0, format VK_FORMAT_R32G32B32A32_SFLOAT, offset 0
err:     binding 0 : binding 0, stride 16, rate 0, divisor 0
err:     binding 0 : binding 0, stride 16, rate 0, divisor 0
err:   DxvkGraphicsPipeline: Failed to compile pipeline
err:     vs  : VS_5308bfc181737a1a8a14dab942c8d221b452b5f0
err:     gs  : GS_76236841d41d77ba77dcad0869fc375cbf3da1b7
err:     fs  : FS_f10848293396e8fc3651d68531f8a7a53aef0c29
err:     attr 0 : location 0, binding 0, format VK_FORMAT_R32G32B32A32_SFLOAT, offset 0
err:     binding 0 : binding 0, stride 16, rate 0, divisor 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_A2B10G10R10_UNORM_PACK32
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1728x1117
info:    Image count:  3
info:    Exclusive FS: 1
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_A2B10G10R10_UNORM_PACK32
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  1728x1117
info:    Image count:  3
info:    Exclusive FS: 1
warn:  DxgiSwapChain::GetFrameStatistics: Semi-stub
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_A2B10G10R10_UNORM_PACK32
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1728x1117
info:    Image count:  3
info:    Exclusive FS: 1
err:   DxvkImageView: Failed to create image view:
err:     View type:       VK_IMAGE_VIEW_TYPE_2D
err:     View format:     VK_FORMAT_B8G8R8A8_UNORM
err:     Subresources:    
err:       Aspect mask:   1
err:       Mip levels:    0 - 1
err:       Array layers:  0 - 1
err:     Image properties:
err:       Type:          VK_IMAGE_TYPE_3D
err:       Format:        VK_FORMAT_B8G8R8A8_UNORM
err:       Extent:        (1,1,1)
err:       Mip levels:    1
err:       Array layers:  1
err:       Samples:       1
err:       Usage:         17
err:       Tiling:        VK_IMAGE_TILING_OPTIMAL

**Comment by Joshua-Ashton** [comment]
We do not support Apple hardware or software here. Your best bet is to contact whoever makes your `1.9.2-mac` build or MoltenVK.
