### ISSUE TITLE
Dark Souls 3: Unstable frame rate on macOS

### ISSUE THREAD

**Issue by a-poptsov** [doitsujin/dxvk#2442]
Frame rate of the game in a static scene is around 40-50(video setting/resolution almost don't affect it) but could be droped to 20(or even lower in rare cases). CPU/GPU utilisation is not "criminal" in these cases 

I understand that issue could be related to MoltenVK project but as there are some errors related to D3D11Device I am posting it here. 

```
warn:  D3D11Device: Vertex input 'COLOR1' not defined by input layout
err:   D3D11: Cannot create texture:
err:     Format:  86
err:     Extent:  512x512x1
err:     Samples: 1
err:     Layers:  1
err:     Levels:  10
err:     Usage:   8
err:     Flags:   0
```

[DarkSoulsIII_d3d11.log](https://github.com/doitsujin/dxvk/files/7880883/DarkSoulsIII_d3d11.log)

### Software information
Dark Souls 3

### System information
- Hardware: Macbook Pro M1 Max
- OS: 12.1 
- Crossover: 21.1
- DXVK version:  v1.9.3-mac-async https://github.com/marzent/dxvk/releases/tag/v1.9.3-mac

**Comment by K0bin** [comment]
We don't support Mac OS. Dark Souls 3 works perfectly on real Vulkan drivers. I played it a month ago. This is most likely a MoltenVK bug or limitation.
