### ISSUE TITLE
Ghost Recon: Breakpoint runs at 15-20fps

### ISSUE THREAD

**Issue by Alexithymia2014** [doitsujin/dxvk#2444]
Ghost Recon: Breakpoint runs at 15-20FPS with the Vulkan backend and can even go down to 5FPS if I maximize the window sometimes. The frametime is 50-100ms and it slows down my entire KDE desktop when in Windowed mode. I'm running Arch Linux with Linux 5.16. I've tried mesa-21.3.3 and mesa-git as of a few days ago and there's been no change. This game ran fine in February 2021. I've used all kinds of Wine versions from 6.14 to 7.0-rc5. I've tried DXVK 1.7.11 through 1.9.2 with no change. AMDVLK doesn't seem to work at all with this game, only radeon vulkan.

I am not sure how to grab an apitrace for Vulkan as the D3D11 version of the game doesn't launch with a generic DirectX error. If there is a way, I'd be make a trace.

### Software information
Name of the game, settings used etc.
Ghost Recon: Breakpoint, Vulkan renderer. I've tried maximum graphics settings and the minimum with no effect. Fullscreen, borderless, and window mode produces the same issue. 

### System information
- OS: Arch Linux
- GPU: Radeon 5700xt
- Driver: mesa-21.3.3 and mesa-git
- Wine version: tkg-wine 7.0-rc6, wine 7.0-rc5 plain, lutris-6.21, and lutris 6.14
- DXVK version: 1.9.2, 1.9.3, and master.

### Log files
dxgi, d3d9 and d3d11 log files: https://drive.google.com/file/d/1qG72dpZcoCRDy1hDeeLNzqrkYcbjL8WB/view?usp=sharing

![Screenshot of benchmark](https://user-images.githubusercontent.com/33267923/149847384-6af69b54-19e5-44a2-a11e-787e41a3b7b8.png)

**Comment by doitsujin** [comment]
DXVK is not involved when using the native Vulkan version of the game. You'll want to report this to mesa instead.

As for why the D3D11 version of the game does not launch, I don't know, but your d3d11.log is empty so it apparently errors out before even creating a device for some reason.

**Comment by Alexithymia2014** [comment]
Thanks! I wasn't sure if DXVK gets invoked when using Vulkan directly.
