### ISSUE TITLE
Tes 4 Oblivion aniso dont work

### ISSUE THREAD

**Issue by N4gibator** [doitsujin/dxvk#2445]
With DXVK on,anisotropic filtering through NVIDIA control panel dont work.

### Software information
TES IV:Oblivion, All max/no aa/hdr on

### System information
- GPU:Geforce 1060 6GB
- Driver:472.12
- Wine version: 
- DXVK version: 1.9.3

### Apitrace file(s)
- Put a link here

### Log files

- d3d9.log:
[Oblivion_d3d9.log](https://github.com/doitsujin/dxvk/files/7894111/Oblivion_d3d9.log)

- d3d11.log:
- dxgi.log:

**Comment by Joshua-Ashton** [comment]
Not our bug. You should report this to NVIDIA.

**Comment by Joshua-Ashton** [comment]
There is also the `d3d9.samplerAnisotropy` option you can use instead.
