### ISSUE TITLE
[[NVIDIA GT 940MX]] [[DXVK Windows 10]] God of War - Crash on startup.  Log file included

### ISSUE THREAD

**Issue by MatoHUB** [doitsujin/dxvk#2446]
I tried God of War on 1.01 version (day 1 patch) and the game just refuses to run. Checked the processes on task bar and it seems it only reaches past to a certain point where it reaches 500 megabytes of memory usage, then the process just hangs and terminates.

**Software Information**

God of War (2018, 2022 PC Release, Steam)/ version 1.01

**System Information**
GPU: NVIDIA GT 940MX 2GB (GDDR5) 
Driver: GeForce Game Ready Driver 511.23
OS: Windows 10
DXVK version: 1.9.3

**Apitrace Files**
None.

**Log Files**
[GoW_dxgi.log](https://github.com/doitsujin/dxvk/files/7898146/GoW_dxgi.log)
(d3d11.log file is empty, cannot upload)

**Comment by DadSchoorse** [comment]
Windows is unsupported, the game works on linux. But your problem might be related to #2435.

**Comment by doitsujin** [comment]
There's an infinite recursion issue going on like I described in [this](https://github.com/doitsujin/dxvk/issues/2435#issuecomment-1013282833) comment, nothing we can do here.

**Comment by MatoHUB** [comment]
Thanks for the information. I managed to fix it by deactivating Nvidia Ansel using the tool that OP used.
