### ISSUE TITLE
GTA 4 seems to be capped at 30 fps

### ISSUE THREAD

**Issue by chariotiscariot** [doitsujin/dxvk#2447]
GTA4 seems to be capped at 30fps after copying d3d9.dll and dxgi.dll to it's main folder. I've tried messing with the graphics settings on the game but the framerate doesn't improve. I was getting an average of 50fps with the graphics settings below before this change so I'm wondering if I've missed a step.

### Software information & Settings
GTA 4 version 1.0.7.0
Resolution - 1366 x 768
Texture quality - High
Reflection quality - High
Water quality - Low
Shadow quality -High
Night Shadows - Off
Texture filter quality - Anisotropic x16
View distance - 21
Detail distance - 12
Vehicle density - 14
Definition - On
VSync - On

### System information
- GPU: NVIDIA GTX 950M
- Driver:  511.23.0
- DXVK version: v1.9.3
- OS: Windows 11

### Log files
- d3d9.log: [PlayGTAIV_d3d9.log](https://github.com/doitsujin/dxvk/files/7908954/PlayGTAIV_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by K0bin** [comment]
It picks a 60hz display mode. Aside from that, any kind of frame rate limiting is entirely up to the application (unless you explicitly enable the DXVK framerate limiter, which as far as I can tell from the logs, you didn't.)

It's probably just slow on your GPU.

**Comment by TedHartDavis** [comment]
> It picks a 60hz display mode. Aside from that, any kind of frame rate limiting is entirely up to the application (unless you explicitly enable the DXVK framerate limiter, which as far as I can tell from the logs, you didn't.)
> 
> It's probably just slow on your GPU.

I have a feeling that the Nvidia drivers, or some sort of power limiting setting, or some sort of weird half-vsync (60hz display mode as you mentioned) might be doing it.
One should be able to go over 30FPS when staring at a blank wall, or something.

**Comment by K0bin** [comment]
Either way, this is probably not a DXVK issue. Whenever I've tested GTA IV, it was running at >60FPS.
