### ISSUE TITLE
Low performance for Ys IX Monstrum Nox

### ISSUE THREAD

**Issue by AyraHikari** [doitsujin/dxvk#2450]
I'm used dxvk latest and got 9-13 fps while in the town with vulkan, however when used directx 11 it got 24-30 fps or even more if used 60 fps settings.
I tried capture apitrace, but the game refused to load and will never responding, so i need kill the game task.

### Software information
Ys IX - Monstrum Nox
- Fps was limited to 30
- Disabled anti-aliasing
- Rest of settings was default

### System information
- GPU: AMD R7 250x
- Driver: AMD Radeon 21.5.2
- Wine version: Windows 11
- DXVK version: 1.9.3

### Log files
- [ys9_d3d11.log](https://github.com/doitsujin/dxvk/files/7919383/ys9_d3d11.log)
- [ys9_dxgi.log](https://github.com/doitsujin/dxvk/files/7919384/ys9_dxgi.log)

![Ys IX Monstrum Nox_2022 01 23-05 04](https://user-images.githubusercontent.com/36266025/150656921-b7355d12-0625-42f1-8c79-bd95e165d36c.png)
![Ys IX Monstrum Nox_2022 01 23-04 27_3](https://user-images.githubusercontent.com/36266025/150656700-e8df6452-31fa-400d-8b5a-219f9152eebb.png)

**Comment by doitsujin** [comment]
Your GPU doesn't have enough VRAM to run the game adequately, not much we can or are willing to do here.
