### ISSUE TITLE
Dyson Sphere Program severe performance issues

### ISSUE THREAD

**Issue by iczero** [doitsujin/dxvk#2451]
The game runs at below 5 fps when using dxvk, but runs fine under wined3d (more than 45 fps on average). Replaying captured apitrace from wined3d with dxvk yields a similar decrease in performance.

Others have replicated this issue, see <https://www.protondb.com/app/1366540>.

### Software information

- Game: [Dyson Sphere Program](https://store.steampowered.com/app/1366540/)
- Game version: 0.9.24.11209
- Engine: Unity

### System information
- GPU: Nvidia GeForce GTX 1050
- Driver: Nvidia 495.46
- Wine version: Wine 6.3-3, Proton Experimental
- DXVK version: 1.9.3

### Apitrace file(s)
- <https://hellomouse.net/~iczero/dyson-sphere-program.trace> (under wined3d)
- <https://hellomouse.net/~iczero/dyson-sphere-program-dxvk.trace> (under dxvk)

### Log files

- d3d11.log: [DSPGAME_d3d11.log](https://github.com/doitsujin/dxvk/files/7919961/DSPGAME_d3d11.log)
- dxgi.log: [DSPGAME_dxgi.log](https://github.com/doitsujin/dxvk/files/7919962/DSPGAME_dxgi.log)

**Comment by doitsujin** [comment]
are you running out of vram or something?

**Comment by iczero** [comment]
Yeah, it does look like I ran out of VRAM. I'll go test on a bigger GPU, sorry.

**Comment by iczero** [comment]
Yep, it works fine on a GPU with more VRAM. Sorry about the false report.

**Comment by awsms** [comment]
Could this be reopened please?

**Comment by iczero** [comment]
@awsms can you do an apitrace? https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

Also you might want to file a new issue. It's probably a different problem this time.

**Comment by Blisto91** [comment]
A new issue would be best yes
