### ISSUE TITLE
Black Mesa dynamic lighting issue

### ISSUE THREAD

**Issue by yurakone** [doitsujin/dxvk#2458]
Hello! I use dkvk since version 1.9.2, thank you for this amazing thing, is very helpful!

**The issue**

The red lighting from dynamic or switchable light sources on prop models. The issue is still with version 1.9.4
Watch video on  [YouTube](https://youtu.be/mDa4XNHf0vY)

**System configuration:**

> Apple MacPro 5.1(4.1) Early 2009
> CPU: 2x Intel Xeon X5670@2.93GHz. 12 Cores / 24 Threads
> RAM: 16Gb ECC DDR3@1066MHz
> GPU: Sappfire Radeon RX570@4Gb
> OS: Windows 10 Pro 21H1

**Logfile**

[bms_d3d9.log](https://github.com/doitsujin/dxvk/files/7938834/bms_d3d9.log)

**Comment by K0bin** [comment]
[Please make an apitrace of the issue.](https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace)

**Comment by yurakone** [comment]
I tried, but there is no such problem with the tracer, except for very low fps
Trace file [download](https://drive.google.com/file/d/1e0zNxCZPFK4XuLxE9XJ3QdxY7ow8Oydv/view?usp=sharing)

**Comment by K0bin** [comment]
> I tried, but there is no such problem with the tracer, except for very low fps

That's to be expected. The problem will show up when we replay the apitrace.

**Comment by yurakone** [comment]
Okay, pay attention to the lighting of gun from flash of the shot.

**Comment by K0bin** [comment]
![20220127154234_1](https://user-images.githubusercontent.com/1131720/151381683-999c0cd3-7346-478f-a1e2-a7ac35a7978b.jpg)

I can't reproduce the problem.

**Comment by yurakone** [comment]
I'm sorry, but how i can do it? where I can find this option?

**Comment by K0bin** [comment]
What option?

**Comment by nipkownix** [comment]
He's probably talking about the PR?

**Comment by yurakone** [comment]
Sorry I’m noob on github, and I’m just noob. I don’t understand what’s mean a FETCH4 for single channel texture formats #2462

**Comment by niobium93** [comment]
That's a pull request for a commit that will fix your issue. You can either wait for it to be pulled and eventually a make it into the next stable version of DXVK or build it yourself and test it.
