### ISSUE TITLE
Gothic2 crashes with err:   D3D11RasterizerState: Antialiased lines not supported 

### ISSUE THREAD

**Issue by stefson** [doitsujin/dxvk#2467]
I keep seeing a lot of crashes in Gothic2 Night of the Raven. I use the d3d11 renderer with your dxvk libs and play through wine. The game freezes quite often after I attacked a zombie enemy, so I read through the d3d11 log, saw the errors about antialiased lines and decided to produce an apitrace to open a bug here. 

### Software information
Gothic2 Night of the Raven

### System information
- GPU: Amd rx570
- Driver: amdgpu 
- Wine version:  6.0.2
- DXVK version:  1.9.4 

### Apitrace file(s)
I used apitrace-latest:  

//Edit: I hope mediafire will serve the file longer than just three days: 

https://www.mediafire.com/file/ibw6aihychsw8vk/Apitrace.tar.xz/file

### Log files

```
err:   D3D11RasterizerState: Antialiased lines not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  6543dbb6-1b48-42f5-ab82-e97ec74326f6
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
err:   D3D11RasterizerState: Antialiased lines not supported
err:   D3D11RasterizerState: Antialiased lines not supported
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1680x1050
info:    Image count:  3
info:    Exclusive FS: 1
err:   D3D11RasterizerState: Antialiased lines not supported
err:   D3D11RasterizerState: Antialiased lines not supported
```

- d3d9.log: [Gothic2_d3d9.log.zip](https://github.com/doitsujin/dxvk/files/7963464/Gothic2_d3d9.log.zip)
- d3d11.log: [Gothic2_d3d11.log.zip](https://github.com/doitsujin/dxvk/files/7963467/Gothic2_d3d11.log.zip)
- dxgi.log: [Gothic2_dxgi.log.zip](https://github.com/doitsujin/dxvk/files/7963465/Gothic2_dxgi.log.zip)

I really hope to have provided all the details you need to reproduce it, ping me anytime if you need additional informations.

**Comment by Squall-Leonhart** [comment]
duplicate of https://github.com/doitsujin/dxvk/issues/200

4Gb patch the game.

**Comment by Squall-Leonhart** [comment]
also see https://github.com/kirides/GD3D11/issues/14#issuecomment-739528956

**Comment by stefson** [comment]
Yes, that posting is mine, haven't changed the prefix since then. 

Laa Flag is set for Gothic2.exe and GothicStarter.exe

**Comment by stefson** [comment]
alright Gentlemen, here is my verdict: 

* The crash itself, or rather hang, is most likely an application bug in the GD3D11 renderer library. There was an update to it recently, problem is gone now. 
 

these errors: 
```
err:   D3D11RasterizerState: Antialiased lines not supported
```

are, lets say, kind of false positives in the logs. I don't know if that concept exists, but it seems they happen to be logged on a regular base, without any real crash.
