### ISSUE TITLE
Black surfaces in Black Mesa

### ISSUE THREAD

**Issue by niobium93** [doitsujin/dxvk#2470]
![dm_bounce0000](https://user-images.githubusercontent.com/1523948/151693926-91eb8645-b5ee-40be-985e-30a3358bd353.jpg)
![dm_bounce0001](https://user-images.githubusercontent.com/1523948/151693929-d5d9a1e4-87fa-4093-b30e-2e29639046a8.jpg)

### Software information
Black Mesa
I'm running it with `d3d9.floatEmulation = False` because of #2469 

### System information
- GPU: AMD Radeon RX 5700 XT
- Driver: mesa-tkg-git-22.0.0_devel.149535.37989670b98-1-x86_64
- Wine version: proton-tkg-git-7.1.r0.gf5ca8f5a-1-x86_64
- DXVK version: v1.9.4-2-gb220c898

### Apitrace file(s)
- [bms black surface.trace](https://mega.nz/file/iFgAhbjD#mz8pcQTjvmze1wy9F8qzO9VZbJ7XKSV0lG51HxeeQ2U)

### Log files
- d3d9.log: [bms_d3d9.log](https://github.com/doitsujin/dxvk/files/7965620/bms_d3d9.log)
- dxgi.log: [bms_dxgi.log](https://github.com/doitsujin/dxvk/files/7965621/bms_dxgi.log)

**Comment by DadSchoorse** [comment]
Does it work with `d3d9.floatEmulation = True`?

**Comment by niobium93** [comment]
Yes it seems to work fine with `True`. I might have created this second report prematurely. Should I close this?

**Comment by DadSchoorse** [comment]
Yeah, this is not a bug then, just the game relying on werid d3d9 behavior.
