### ISSUE TITLE
Flickering Artifacts in GTAIV

### ISSUE THREAD

**Issue by jeb-sl** [doitsujin/dxvk#2471]
When playing GTA4 (only during actual gameplay, not present in menus and loading screens), the full length of one of the diagonals is filled with pixelated flickering green-ish squares.
Screenshot: https://imgur.com/a/dP8jL2W

Fixes from already existing issues such as adding command-line options or changing the DXVK version don't have any effect.
Many other (newer) games are working perfectly fine, so this doesn't seem like a driver or hardware problem

- GPU: Intel UHD Graphics
- Driver: driver: i915 v: kernel (kernel v.5.15.16-200.fc35.x86_64, mesa 21.3.4)
- Wine version: lurtis-ge-7.1.1-x86_64
- DXVK version: 1.9.4, 1.9.2, 1.7.3 (same behavior on all versions)

### Log files
- d3d9.log: https://pastebin.com/1LQt4DTQ
- d3d11.log: (not uses D3D11)
- dxgi.log: https://pastebin.com/kSCrpj7S

**Comment by K0bin** [comment]
Same as #1862

Another instance of feedback loops causing problems.

**Comment by jeb-sl** [comment]
> Same as #1862
> 
> Another instance of feedback loops causing problems.

So no fix for now? As mentioned, none of the workarounds do anything.

**Comment by K0bin** [comment]
The workarounds only work for RADV, you're using ANV.
As far as I know, there's nothing you can do right now.

**Comment by K0bin** [comment]
Try `INTEL_DEBUG=norbc` and `INTEL_DEBUG=nohiz`.

**Comment by i1u5** [comment]
> Try `INTEL_DEBUG=norbc,nohiz`.

Had the same issue, that seemed to fix it for me. ty.
