### ISSUE TITLE
Mary Skelter 2 Backround bar textures, graphics issues.

### ISSUE THREAD

**Issue by Ross-Carran** [doitsujin/dxvk#2472]
The forward graphics during conversations is fine, anything in the backround is in bars, does not render monsters at all.
Game crashes if trying to run with PROTON_USE_WINED3D=1

![20220201173344_1](https://user-images.githubusercontent.com/19828845/151914947-8625a1ef-d952-4777-afe9-7a3bb66361f1.jpg)

Dxgi log: [MarySkelter2_dxgi.log](https://github.com/doitsujin/dxvk/files/7975983/MarySkelter2_dxgi.log)
DX11 log: [MarySkelter2_d3d11.log](https://github.com/doitsujin/dxvk/files/7975987/MarySkelter2_d3d11.log)
Dx9 log: [MarySkelter2_d3d9.log](https://github.com/doitsujin/dxvk/files/7975990/MarySkelter2_d3d9.log)
proton log: [steam-1496250.log](https://github.com/doitsujin/dxvk/files/7975993/steam-1496250.log)

**Comment by KingKrouch** [comment]
> This looks awfully similar to the [World of Final Fantasy](https://github.com/doitsujin/dxvk/issues/1216) issue.
It's worth mentioning that World of Final Fantasy and most of Compile Heart's recent games (Although from what I see, most those games, outside of the Mary Skelter games, use deferred rendering (and thus no MSAA) outside of character rendering) use Orochi 3/4, so it's entirely plausible that the same issue applies here.
