### ISSUE TITLE
Saints Rows 3 at 1 fps!!

### ISSUE THREAD

**Issue by SaintsWalker23** [doitsujin/dxvk#2473]
Saints Row 3 runs smoothly for several minutes with DXVK, around 50 fps, but always at some point the fps drops to 1. And I have to close the game.

I would like some solution, I'm still a beginner with DXVK.
Is there any setting to alleviate this?
Versions of DXVK used (1.8.1 and 1.9) 1.9 has been the most durable until the fps starts to drop.

forgive my bad english.

**Comment by Leopard1907** [comment]
Don't ignore the issue template.

You lack hw info, logs, software info etc.

**Comment by SaintsWalker23** [comment]
> Não ignore o modelo de problema.
> 
> Você não tem informações de hw, logs, informações de software etc.

hi, thanks for replying.

the log is here
but I have no idea where to get the other information you asked for.

Log:
info:  Game: SaintsRowTheThird.exe
info:  DXVK: v1.8.1
info:  Found config file: dxvk.conf
info:  Effective configuration:
info:    d3d9.presentInterval = 0
info:    d3d9.maxAvailableMemory = 128
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  Intel(R) UHD Graphics 620:
info:    Driver: 0.402.1472
info:    Vulkan: 1.2.177
info:    Memory Heap[0]: 
info:      Size: 1979 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[1]: Property Flags = 0x7
info:      Memory Type[2]: Property Flags = 0xf
info:  Process set as DPI aware
info:  Device properties:
info:    Device name:     : Intel(R) UHD Graphics 620
info:    Driver version   : 0.402.1472
info:  Enabled device extensions:
info:    VK_EXT_4444_formats
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state
info:    VK_EXT_full_screen_exclusive
info:    VK_EXT_host_query_reset
info:    VK_EXT_robustness2
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_image_format_list
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_float_controls
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 0
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 0
info:    shaderStorageImageExtendedFormats      : 1
info:    shaderStorageImageReadWithoutFormat    : 0
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 0
info:  VK_EXT_4444_formats
info:    formatA4R4G4B4                         : 1
info:    formatA4B4G4R4                         : 0
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_extended_dynamic_state
info:    extendedDynamicState                   : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 0
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 0
info:    robustImageAccess2                     : 0
info:    nullDescriptor                         : 1
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 0
warn:  DXVK: State cache version not supported
warn:  DXVK: Creating new state cache file
info:  DXVK: Using 2 compiler threads
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              800
info:      - Height:             600
info:      - Format:             D3D9Format::X8R8G8B8
info:      - Auto Depth Stencil: true
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           false
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R8G8B8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  800x600
info:    Image count:  3
info:    Exclusive FS: 0
info:  Setting display mode: 800x600@0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_R8G8B8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  800x600
info:    Image count:  3
info:    Exclusive FS: 0
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_MULTISAMPLEANTIALIAS

**Comment by gabriele2000** [comment]
> info: Driver version : 0.402.1472

Very strange driver version, are you on Windows or Linux?
If you're on linux install intel drivers

**Comment by SaintsWalker23** [comment]
> > informações: Versão do driver: 0.402.1472
> 
> Versão do driver muito estranha, você está no Windows ou Linux? Se você estiver no linux, instale os drivers intel, incluindo drivers vulkan

Thanks for replying! 
OS: Windows 10
Driver: Intel uhd 620 

I've been using the dxvk 1.5.1 version and so far it's a little stable.

**Comment by Blisto91** [comment]
@SaintsWalker23 Is it correct you are using the directx 9 graphics?
Does it change anything if you use directx 10/11 instead?

In dx9 mode does it help if you make a file called `dxvk.conf` next to the games .exe with this?
```
d3d9.memoryTrackTest = True
```
Or maybe
```
d3d9.maxAvailableMemory = 2048
d3d9.memoryTrackTest = True
```

To verify that the game picks of the conf file you can also add `dxvk.hud = 1` and see that the hud shows up ingame.

**Comment by Blisto91** [comment]
@SaintsWalker23 Friendly ping

**Comment by K0bin** [comment]
Closing due to the lack of feedback.

**Comment by rtentser** [comment]
Have pretty similar issue both on linux with proton-ge 7.43 and on windows with dxvk 2.0.

DirectX 9 with dxvk gives better performance (after shader stutter) than native dx9/dx11. It's about steady 100+ fps on linux and 60+ fps on windows (2560x1440, ultra graphics). But after a while (about half an hour in game, but it differs every time), the performance degrades to 5-6 fps, which makes game unplayable. Exit to main menu fixes it in both OS.

My GPU is rx 6600, CPU is r5 2600. The game seems to be CPU-limited with dx9/dx11, dxvk fixes it. Can't test on linux right now, can test on windows. Maybe amd related (i've read some protondb reports, no mentions of similar problem, all of them from nvidia users iirc).

> d3d9.memoryTrackTest = True

There was some changes in 2.0, can it still help?

**Comment by rtentser** [comment]
> d3d9.memoryTrackTest = True

Didn't help

> d3d9.maxAvailableMemory = 2048
> d3d9.memoryTrackTest = True

Didn't help too

**Comment by Blisto91** [comment]
I'll see if i can reproduce here when i have time.

**Comment by K0bin** [comment]
Please make an apitrace. @rtentser

**Comment by K0bin** [comment]
Also, please clarify whether you're using D3D9 or D3D11 and whether or not you're talking about the remaster.

**Comment by rtentser** [comment]
It's original steam version, not a remaster. It's dx9 problem, dx11 runs more stable, but performance is worse, it's cpu limited

I'll make apitrace later

**Comment by rtentser** [comment]
> Now copy those DLL files into the same folder as the game's .EXE.
> Launch the game and try to reproduce your issue as fast as possible, then exit the game after that (using ALT+F4 is fine).

I can only reproduce the issue with dxvk libraries, will apitrace help?

**Comment by K0bin** [comment]
It might. Just make sure its long enough.

**Comment by rtentser** [comment]
How long?

**Comment by SaintsWalker23** [comment]
Thanks for the answers, and sorry for taking so long to reply.
I finished the game a long time ago. I just used some old versions of dvk and it stopped crashing.

Of course, this was a specific and isolated solution for this Saints 3 case. For other games I wasn't so successful.

**Comment by Blisto91** [comment]
@SaintsWalker23 Which is the latest version of dxvk where the issue doesn't occur?

@rtentser If you want to trace together with dxvk on Windows you can put the apitrace dll's next to the games exe and then use the env var `APITRACE_FORCE_MODULE_PATH` pointing to a another folder where the dxvk dll's are located.

**Comment by rtentser** [comment]
With apitrace the game starts to 9 fps in main menu. So, i didn't play much. Second file is probably a launcher

Without env var: [](https://disk.yandex.ru/d/J7FeVCpZJML7jwl)
With env var pointing to dxvk: [](https://disk.yandex.ru/d/D_uE93FmlfvD4Q)

**Comment by K0bin** [comment]
That hoster limits download speed to 30 KB/s for free users. Can you please upload it to some site that doesn't take hours to download?

Besides that, the first link seems to be dead.

**Comment by SaintsWalker23** [comment]
@Blisto91 the most stable version I used for me in saints rows 3 was: dxvk-1.5.2
remembering that I'm using the game's directx 11

**Comment by rtentser** [comment]
> That hoster limits download speed to 30 KB/s for free users

Pretty strange, i've used it without logging in, always fast experience. But it was a long time ago

dxvk: [link](https://drive.google.com/file/d/189LIpXxMb9ez5V27hfVCWpBkSoH49_Ew/view?usp=share_link)
no-dxvk: [link](https://drive.google.com/file/d/14RtcwL1TKQ6w8r2KVdvxYijw0qOw_hG0/view?usp=share_link)

**Comment by rtentser** [comment]
> remembering that I'm using the game's directx 11

DirectX 11 stable, but slow

**Comment by Blisto91** [comment]
Mkay i've manged to reproduce both with wined3d and dxvk on Linux.

@rtentser Did you manage to reproduce this on Windows with dxvk but not without?

**Comment by rtentser** [comment]
Yes, i've played for a while with native dxvk, didn't reproduce the problem

**Comment by rtentser** [comment]
Just played it without dxvk for a couple of hours, no issue

**Comment by K0bin** [comment]
@rtentser What GPU and driver are you using?

**Comment by rtentser** [comment]
RX 6600
On windows it's AMD Software: Adrenalin Edition 22.11.2
On linux it was probably mesa 22.3.1, i was on manjaro unstable

**Comment by K0bin** [comment]
And it happened on both Windows and Linux?

**Comment by rtentser** [comment]
Yes
Linux has better performance on dx9, but still, after a while the issue happened, performance became about 6 fps
@Blisto91 reproduced it on linux, i guess

**Comment by K0bin** [comment]
I cannot reproduce this. I've played for around 20 minutes and it ran at >100fps 4k with 8x MSAA the entire time.

**Comment by rtentser** [comment]
It happens for me after about half an hour. Sometimes earlier

**Comment by Blisto91** [comment]
Just posting the trace i made which i and another can reproduce the issue with.

https://mega.nz/file/RpBUwCCJ#P0I58vUqSM10rp2pfGtoP6ck6f7TZqmz3jgetkCG7M4

**Comment by K0bin** [comment]
```505383999 @1 IDirect3DDevice9Ex::SetStreamSourceFreq(this = 0xf49a260, StreamNumber = 1, Setting = 2147483649) = D3D_OK

505384001 @1 IDirect3DDevice9Ex::SetStreamSourceFreq(this = 0xf49a260, StreamNumber = 0, Setting = 1073751824) = D3D_OK

505384012 @1 IDirect3DDevice9Ex::DrawPrimitive(this = 0xf49a260, PrimitiveType = D3DPT_POINTLIST, StartVertex = 0, PrimitiveCount = 40000) = D3D_OK```

**Comment by K0bin** [comment]
Turns out my theory was correct. That PR will fix it.
