### ISSUE TITLE
Humans/player not rendering correctly in Hitman 2: Silent Assassin

### ISSUE THREAD

**Issue by szskill** [doitsujin/dxvk#2476]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
Preferably record the trace on Windows, or wined3d if possible.

**Reports with no log files will be ignored.**

### Software information
Game: Hitman 2: Silent Assassin
OS: Kubuntu 21.10
Memory: 16GB
Graphics Platform: X11
I also used d3d8to9 to make it work with DXVK

### System information
- GPU: AMD RADV RENOIR
- Driver:
- Wine version: 5.0.3
- DXVK version: v1.9.4-4-g58909e45

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log: https://pastebin.com/kZvr5Lmr
- d3d11.log: Not created
- dxgi.log: Not created

### -
With DXVK: https://imgur.com/a/kSKARyc
Without DXVK: https://imgur.com/a/dqpiYAD

**Comment by K0bin** [comment]
> Apitrace file(s)
> Put a link here

Please do that.

**Comment by Redundanz** [comment]
probably related to #1386
d3d8to9 seems to be responsible for this - for more background see also -> https://github.com/crosire/d3d8to9/issues/17 & possible solution: https://github.com/crosire/d3d8to9/issues/25#issuecomment-312400311

**Comment by szskill** [comment]
> probably related to #1386 d3d8to9 seems to be responsible for this - for more background see also -> [crosire/d3d8to9#17](https://github.com/crosire/d3d8to9/issues/17) & possible solution: [crosire/d3d8to9#25 (comment)](https://github.com/crosire/d3d8to9/issues/25#issuecomment-312400311)

Seems to have fixed it. Thanks!
