### ISSUE TITLE
Idle Calibur does not start, shows light flickering (Arch linux)

### ISSUE THREAD

**Issue by CygnusTerminal** [doitsujin/dxvk#2479]
When trying to start the game, it hangs on the starting screen, light flickering and repeating every 3 seconds. On Windows, this "light" is part of the start menu. Game never starts, and never crashes either. 

### Software information
Idle Calibur, defaults settings since i can't even start the game

### System information
- GPU: GTX 1650 GDDR6 (laptop)
- Driver: 510.47.03
- Wine version: 7.1-GE-2 (Proton)
- DXVK version: v1.9.4-async

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log: empty
- d3d11.log: [Game_d3d11.log](https://github.com/doitsujin/dxvk/files/8008110/Game_d3d11.log)
- dxgi.log: [Game_dxgi.log](https://github.com/doitsujin/dxvk/files/8008111/Game_dxgi.log)
- proton log: [steam-1674890.log](https://github.com/doitsujin/dxvk/files/8008116/steam-1674890.log)

**Comment by K0bin** [comment]
> Put a link here

Please do that.

**Comment by doitsujin** [comment]
Please do not report bugs here when using an unofficial fork.

**Comment by doitsujin** [comment]
fwiw I just installed the game to test and found the following:
- the exact same thing happens with wined3d
- the main menu is not being rendered with D3D11 at all (or really any D3D from what I can tell)

The game just seems to be stuck in an infinite initialization loop for some reason, doesn't look like our bug.

**Comment by CygnusTerminal** [comment]
Sorry, i overstimated my issue-reporting capabilities. You can close this issue if you want, since it seems to be a Proton issue. Thanks for the help anyway!
