### ISSUE TITLE
AMD cards are not initialized only for Dx11 Windows

### ISSUE THREAD

**Issue by ufukbakan** [doitsujin/dxvk#2481]
Hello, im using your project on Windows. I copied DLL files to game executable location. In Dx9 mode it just works, but for Dx11 it could not initalize graphics device and error log says: err:   D3D11CreateDevice: Failed to create swap chain.

### Software information
- League of legends
- Is this information matter idk:
- 1920x1080, High settings, vsync off, fullscreen
- Prefer Dx9 legacy mode is unchecked (when its checked dxvk succeeds to convert dx9 to vulkan)

### System information
- GPU: RX570 4GB
- Driver: Radeon Software 22.1.1
- Wine version: not wine Windows 10 64bit but game is 32 bit so 32bit DLL files are used.
- DXVK version: 

### Log files
- d3d9.log: 0 KB
- d3d11.log: [League of Legends_d3d11.log](https://github.com/doitsujin/dxvk/files/8009997/League.of.Legends_d3d11.log)
- dxgi.log: Non exists

**Comment by K0bin** [comment]
You forgot to copy dxgi.dll.

**Comment by doitsujin** [comment]
Either that or the game refuses to load dxgi.dll from the game directory (some do this by accident, some do this as a kind of terrible anti-cheat measure), in which case there's really nothing you can do.

**Comment by ufukbakan** [comment]
> You forgot to copy dxgi.dll.

no, i did copy. 

> Either that or the game refuses to load dxgi.dll from the game directory (some do this by accident, some do this as a kind of terrible anti-cheat measure), in which case there's really nothing you can do.

Okay thanks i will try to find a way thats a game specific problem as you described.
