### ISSUE TITLE
Remedy Control micro stutter.

### ISSUE THREAD

**Issue by artivision** [doitsujin/dxvk#2486]
Well people report this on Windows to, even on --DX11 mode. So 60 solid Fps no bad frame times shown in my overlay graph and what the hell - micro stutter with no frame down. Probably inside game engine wrong frame distance? I don't know.

Ryzen quad - Polaris 4GB.

**Comment by K0bin** [comment]
> So 60 solid Fps no bad frame times shown in my overlay graph and what the hell - micro stutter with no frame down

I don't really understand what you mean. Is there a problem or not?

**Comment by doitsujin** [comment]
Do you have desktop effects on or something?

Game runs perfectly fine here, although there have been reports about poor frame times with DXVK in this game which I haven't been able to reproduce. Can always use D3D12 though.

**Comment by artivision** [comment]
**https://easyupload.io/atjtv0**

Tested with no compositor but there is no problem there. Compositors today have **Unredirect** support for full screen windows.

**Vkd3d-proton-git** indeed solves 2/3 of the problem but gets 10% lower fps.

No other Dxvk games have similar problems except Control.

I will test with no **Freesync** tomorrow, **Vsync** doesn't change anything.

Dxvk.conf **-maxFrameLatency** doesn't max at **16ms** at all and **-syncInterval** at 2 gives weird unmatched **Freesync** times.

**Comment by doitsujin** [comment]
Still can't reproduce it here so not much I can do.

**Comment by artivision** [comment]
Partially 2/3 solved, behaves like Vkd3d now. Must lower everything till perform above 60fps (me 70) and in combination disable MSAA completely. To raise quality for the loss, activate FSR via a kron4ek tkg build the simplest way: **wine game.exe** to something like **/home/user/kron/bin/wine game.exe** (same prefix doesn't matter), or use VkBasalt with a config file that at least specify CAS On.
