### ISSUE TITLE
Gta 4 does not start

### ISSUE THREAD

**Issue by PonchoNz** [doitsujin/dxvk#2487]
a black screen appears and after 10 seconds it closes
- GPU: GTX 760M
- Driver: 425.31
- DXVK version: 1.9.4

### Log files
[GTAIV_d3d9.log](https://github.com/doitsujin/dxvk/files/8035978/GTAIV_d3d9.log)
[GTAIV_dxgi.log](https://github.com/doitsujin/dxvk/files/8035979/GTAIV_dxgi.log)

**Comment by K0bin** [comment]
The game works with DXVK. No idea why it doesn't work for you, there's nothing to go by in the logs either.

**Comment by Leopard1907** [comment]
Try using a newer driver instead of a one from 2019.

**Comment by runboy93** [comment]
> Try using a newer driver instead of a one from 2019.

That seems to be latest version for GTX 760M:
https://www.nvidia.com/Download/driverResults.aspx/145874/en-us

**Comment by K0bin** [comment]
The game works with DXVK. This is either a problem with the graphics driver or a Windows problem. Either way, there's nothing we can do.
