### ISSUE TITLE
About native d3dcompiler_47.dll?

### ISSUE THREAD

**Issue by Vosester** [doitsujin/dxvk#249]
> In addition to the DLLs, the following standalone programs are included in the project. Most of them require a native d3dcompiler_47.dll, which you can retrieve from your Windows installation in case you have one.
  

I am confused is this a build requirement or run time?
Do I need to build against a native d3dcompiler_47.dll when compiling.
or
Do I build with the wine d3dcompiler_47.dll and set an override to native and drop the dll in with the exe?

**Comment by neVERberleRfellerER** [comment]
> Do I build with the wine d3dcompiler_47.dll and set an override to native and drop the dll in with the exe?

This one - native `d3dcompiler_47.dll` is needed at runtime. It is also needed for various games (some need `d3dcompiler_43.dll` and e.g. Gothic 2 GD3D11 needs even `d3dx11_43.dll`).

**Comment by doitsujin** [comment]
It is a requirement ***only*** for the executables at runtime. As for games, the requirements don't change with dxvk, if a game needs native libraries with wined3d, it will need the same native libraries with dxvk.
