### ISSUE TITLE
Age of Empires 2 Definitive Edition stutters unless apitrace mode is set

### ISSUE THREAD

**Issue by EmmerichFrog** [doitsujin/dxvk#2491]
### Software information
the game stutters regular intervals with dxvk, it's very noticeable online and as the game goes on it only gets worse. One other way to repro 100% of the time  is to run the ingame benchmark: small stutters can be noticed (they are much more subtle this way and you might think it's just the benchmark that it's heavy but it's not that) every few second for the whole duration. This also does not happen with wined3d and the game runs as expected.
It might be a game bug since the same (or at least very similar) issue happens on windows for some people (seems the common thing is having an amd gpu), so it might not be reproducible on other hw.
Having apitrace mode on also makes the benchmark score noticeably higher (at least 100-150 points on my laptop, 150-200 on my desktop), so it's not just placebo. 

The bug has been present since one game update about a year ago, and I have played it on several wine, proton, dxvk build over the months.

### System information
- GPU: happens both on a vega 8 laptop and a 6700xt
- Driver: happens both on current mesa stable and various git builds
- Wine version: tried proton experimental, 6.3 and various GE builds
- DXVK version: lastest master, but it also happens on older versions

### Log files
the logs are taken on my vega 8 laptop without apitrace mode

[AoE2DE_s_d3d11.log](https://github.com/doitsujin/dxvk/files/8049048/AoE2DE_s_d3d11.log)
[AoE2DE_s_dxgi.log](https://github.com/doitsujin/dxvk/files/8049049/AoE2DE_s_dxgi.log)

**Comment by doitsujin** [comment]
Can't confirm, getting the same benchmark score with and without apitrace mode here. Also means that enabling it won't hurt though.
