### ISSUE TITLE
God Of War - low use of the video card

### ISSUE THREAD

**Issue by vitleonskot** [doitsujin/dxvk#2498]
God of War
low use of the video card at times, causing the fps to drop a lot even on vulkan.

RX 6600XT
16GB RAM
RYZEN 5 3600

**Comment by doitsujin** [comment]
We already have optimizations which should help God of War performance a fair bit, a build of the current code is [here](https://github.com/doitsujin/dxvk/suites/5291698905/artifacts/164013988).

**Comment by DistantThunder** [comment]
Hello,

Sorry to piggy back on this issue even though it's closed but at the moment, using Mesa 22.x.x and DXVK 1.10.1 on Proton Experimental, I'm still seeing those recurrent framedrops and low GPU usage, I get the impression that Gamemode helps a bit but not enough for it to be unnoticeable.

With Mangohud, I can see the GPU utilization dropping  and visually it feels like the kind of stuttering you'd sometime have on SLI/Crossfire configuration, with what looks like every second or third frame taking too look to render at some point.


I'm using a 5800x with 64 GB RAM and 6900XT 16 GB VRAM, Arch Linux.

In Proton logs, I can see this:

>info:  DXVK: v1.10.1
info:  Found config file: dxvk.conf
info:  Found built-in config:
info:  Effective configuration:
info:    d3d11.ignoreGraphicsBarriers = True
info:    d3d11.relaxedBarriers = True
info:    dxgi.nvapiHack = False
info:    dxgi.maxFrameLatency = 1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
--
info:  DXVK: Read 13833 valid state cache entries
info:  DXVK: Using 10 compiler threads
info:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  2560x1440
info:    Image count:  3
info:    Exclusive FS: 2

So it looks like the latest  mitigation is enabled.

Does it looks

**Comment by doitsujin** [comment]
Could be running into compositor issues, could just be ordinary CPU limits which are still going to be a thing if you're not playing at 4k, could be anything really. The game is being tested with pretty much every single DXVK change and does not have any known problems that could really be fixed on our end.

**Comment by DistantThunder** [comment]
Eventually was a environment (mine) problem:

I had Swap activated and though I had plenty of file cache to use left, the kernel decided it was a good idea to swap the game. 

It would systematically doing that no matter how much time I restarted it. When turning it off, I immediately saw much better frametimes. I have my swappiness at  5 but it appears I'll need to maybe put Steam and children in a specific systemd slice.
