### ISSUE TITLE
[[NVIDIA GTX 950]] [[Windows 11]] God of War - Fix won't work, err msg "You need at least D3D_Feature_Level_11_1."

### ISSUE THREAD

**Issue by RevengerMH** [doitsujin/dxvk#2499]
### Software information
God of War (Update 6 and 7, to "b8168279-RUI")

### System information
- GPU: Nvidia GTX 950M
- OS: Windows 11
- Driver: 511.65
- DXVK version: 1.9.4

### Log files
- dxgi.log: [GoW_dxgi.log](https://github.com/doitsujin/dxvk/files/8060426/GoW_dxgi.log)

**Comment by doitsujin** [comment]
> err:   DxvkInstance::createInstance: Failed to create Vulkan 1.1 instance

Your setup does not seem to have Vulkan support enabled.
