### ISSUE TITLE
Wine 3.0

### ISSUE THREAD

**Issue by Raffarti** [doitsujin/dxvk#25]
Wine 3.0 doesn't load DXVK, plus it breaks horribly when dxgi and d3d11 are set to native.
(for those curious, in Unigine Valley wine 3.0 range from 6 to 11 fps on my system, DXVK from 40 to 80 fps)

**Comment by Raffarti** [comment]
Ah, that's right! Everything's probably fine then.

**Comment by doitsujin** [comment]
You could try [wine-vulkan](https://github.com/roderickc/wine-vulkan). Haven't looked into it myself though.

**Comment by Raffarti** [comment]
I'll look into it too.
I'm doing some benchmarking with unigine valley (dxvk, d3d9, gallium nine ...), shall I post results here?

**Comment by Raffarti** [comment]
@doitsujin I've managed to have the triangle test working on wine-vulkan, but there are some caveats:
 -  wine pass linux' `VK_ICD_FILENAMES` to windows, breaking things up. Workaround is to set it empty (or pointing to windows ICDs) in windows registry.
- Dlls redirections it's a wine staging feature, so wine-vulkan doesn't play well with the current script.
 I'll see tomorrow if I can have it working using overrides on both 32 and 64 bit dlls at the same time.

**Comment by Raffarti** [comment]
I couldn't find a reliable way to load d3d11 and dxgi other than using staging's dll redirections.

**Comment by doitsujin** [comment]
Thanks for testing this, which means that we'll stick to wine-staging for a little longer.

**Comment by Raffarti** [comment]
I'm going to patch redirections into wine-vulkan to do some benchmark with Unigine Valley, there shouldn't be any difference in performances though?
