### ISSUE TITLE
[D3D9] FLOWERS window / screen flicker on scene transition

### ISSUE THREAD

**Issue by noarchwastaken** [doitsujin/dxvk#2500]
With DXVK, the visual novel FLOWERS flickers when there's a scene transition.

Here's what it's supposed to look like:
https://sam.nl.tab.digital/s/4LCArt7C3DPS5Wp

With DXVK:
https://sam.nl.tab.digital/s/bEnpCryDME6SJk7

This issue doesn't exist when using WineD3D.

### Software information
- Game: FLOWERS series
- Link: https://store.steampowered.com/app/452440/Flowers_Le_volume_sur_printemps/

The bug is present in all four volumes across all languages; the apitrace below is captured from the Japanese version of the fourth release.

### System information
- GPU: Intel UHD 630
- Driver: Mesa 21.3.5
- Wine version: wine-7.1_1 from Void Linux
- DXVK version: 1.9.4

### Apitrace file(s)
(Recorded on a separate Windows machine)
https://sam.nl.tab.digital/s/YMcN9KfHsR3Cr5t

### Log files
- d3d9.log: https://sam.nl.tab.digital/s/QadWxomAoQPrn8f
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by Blisto91** [comment]
@noarchwastaken Hi there. Going by your trace this issue seems to have been fixed with dxvk 1.10.
Are you able to verify?
