### ISSUE TITLE
[d3d11] [regression] [dissected] Automobilista 2 (1066890) severe performance regression since v1.9.4

### ISSUE THREAD

**Issue by ZakMcKrack3n** [doitsujin/dxvk#2502]
Regression (77fps->30fps with the same scene) did start with the following commit:
https://github.com/doitsujin/dxvk/blob/d34bbdb58e547c943ef1eaeac38a88c35f51f52a/src/dxvk/dxvk_memory.cpp#L421

As the master branch has additional changes I am unable to say how this translates to current code base.

### System information
- GPU: AMDGPU POLARIS11 (rx 460) 2GB
- Driver: 21.3.6
- Wine version: Proton 7 with self built drop in dlls
- DXVK version: master / v1.9.4 branch

Commenting the condition and code in 1.9.4 branch will restore performance to 1.9.3 levels.
Unfortunately setting log levels completely freezes my game launch and I can not provide any of them.

Other games tested with 1.9.4 vs 1.9.3 showed no obvious performance change (Assetto Corsa / Dirt Rally 2.0)

**Comment by doitsujin** [comment]
"Just" installed the game (why exactly is this 80GB?) and even at 1080p lowest settings it requires more than 3GB of VRAM, so yeah, this is not going to run well on a 2GB GPU. Not much we can do here.

**Comment by doitsujin** [comment]
> As I understand the code should help with memory pressure , is there some hidden overhead for the GPUs memory controller or CPU in certain edge cases ?

Not really, and 100% GPU load indicates that the GPU is just busy fetching data over system RAM because there seems to be one allocation that gets paged out into system RAM. Again this isn't really something we can improve on right now, and I would suggest just using an older DXVK build for this game that happens to work.

**Comment by ZakMcKrack3n** [comment]
But I already showed that my VRAM is not exhausted, and 100% GPU load is because it renders as much frames as possbile?
Checking radeontop with v1.9.2 vs v1.9.4 with proton 7 shows me that v1.9.4 uses LESS VRAM and GTT:

```
radeontop for v1.9.2:
All values at 100% utilisation except
Vertex Grouper + Tesselator 76%
Texture Addresser 93%
Primitive assembly 76,76%

1987M / 1991 VRAM 99,82%
1903 / 3063 GTT 62,12%

radeontop for v1.9.4:
All pipes pretty much 100% only depth block util. 80%

1761M / 1991 VRAM 88,47%
507 / 3063 GTT 16,54%
```
So by NOT allocating as much video memory it somehow saturates PCIe bus because it accesses system RAM.
Ok , as I am on PCIe 2.0 and my card has PCI 3.0 8x so it essentially kills performance.

I guess you can close it (wontfix :-1: ), I do not have the skill to optimize dxvk code, I just thought that hitting vram limit with 4 and later 8 gb cards could impact performance too, but I have no way to test.

**Comment by ZakMcKrack3n** [comment]
I tried the branch , unfortunately it exactly matches v1.9.4 performance wise.

**Comment by doitsujin** [comment]
Not much we can do then. I'm not going to revert the changes because they genuinely help in other situations.

**Comment by ZakMcKrack3n** [comment]
Ok , I am now in the process in making the chunksize configurable , because it seems this was the right call.

With a chunksize of 16 I now get v1.9.2 ish performance (a bit less than stock v1.9.3), will test various chunk sizes to see what works best.

Right now I am hacking it in as dxvk option because it is already accessible in dxvk_memory.cpp :+1:

**Comment by ZakMcKrack3n** [comment]
Also tested using more VRMA than available by increasing the texture detail:

Automobilista 2 slightly overcommiting ~110%
```
128MB: 25.9
  1MB: 29.5
```
Automobilista 2 overcommiting ~ 150%
```
128MB: 9.6
  1MB: 7.7
```

And finally Dirt Rally 2.0 with over 147% mem usage
```
128MB: 52.6
  1MB: 39.5
```
So an all size fits nobody situation I guess :)

**Comment by doitsujin** [comment]
I'm not interested in making the chunk size configurable, even if 16M works well *right now* there's no guarantee that it will work in the future since it depends what the driver does behind your back. Not to mention that we already use small chunks for small resources.

Ideally we'd have TTM page out memory allocations that aren't used while keeping all high-priority allocations in VRAM at all times, the information is there, but I don't think the driver does that at the moment. This probably does already work better on Windows even with DXVK than it does on Linux.

**Comment by ZakMcKrack3n** [comment]
> I'm not interested in making the chunk size configurable, even if 16M works well _right now_ there's no guarantee that it will work in the future since it depends what the driver does behind your back. Not to mention that we already use small chunks for small resources.
> 
> Ideally we'd have TTM page out memory allocations that aren't used while keeping all high-priority allocations in VRAM at all times, the information is there, but I don't think the driver does that to the necessary extent at the moment. This probably does already work better on Windows even with DXVK than it does on Linux.

No problem, I did it only for faster testing.
I think there is everything said and done, if there is anything more I should test, say the word, otherwise this issue can be closed.

**Comment by ZakMcKrack3n** [comment]
Retested with never DXVK versions:

Sample race cockpit view from back of the grid:
v1.9.3   -> 62.2 fps
v1.9.4   -> 27.7 fps
v1.10.0 -> 72.6 fps 
v1.10.1 -> 73.1 fps

Sample race menu looking over grid:
v1.9.3   -> 39.8 fps
v1.9.4   -> 21.8 fps
v1.10.0 -> 38.9 fps 
v1.10.1 -> 38.7 fps

Whatever optimizations took place also fixed the issues I had with v1.9.4. :+1:

**Comment by ZakMcKrack3n** [comment]
Just for future reference:
Unfortunately after a new round of testing, there are still combinations of races with "clear" weather that essentially half the frame rate with > 1.9.3 versions on my RX460 hardware.

**Comment by emansom** [comment]
Is there a way to migrate other applications running (e.g. Firefox) from VRAM to system memory (GTT), so that more becomes available for DXVK?

Having for example GameMode do that on enablement, would solve issues on e.g. a PCIe bandwidth (64 bits bus) and VRAM (2 GB) limited RX 550.

**Comment by emansom** [comment]
@yuzhaogoogle MGLRU for GTT next? :smiley:

**Comment by Blisto91** [comment]
I do not know of a way and without any insight i would imagine that would be a job for the kernel or the applications themselves.

I don't know if you know @ yuzhaogoogle but if not then please don't ping random people from random issues.
If you have a issue with or question about dxvk feel free to open a new one 🙂
