### ISSUE TITLE
Amid Evil needs actual Nvidia Gpu reported as Nvidia Gpu please , else i cant use its RTX d3d12 features please

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [doitsujin/dxvk#2503]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
Preferably record the trace on Windows, or wined3d if possible.

**Reports with no log files will be ignored.**

### Software information
Name of the game, settings used etc.
Amid Evil 
### System information
- GPU: RTX 2080
- Driver: shouldnt matter
- Wine version: im on Windows 7
- DXVK version: 1.9.4

### Apitrace file(s)
- Put a link here
not required
### Log files
- d3d9.log:not required
- d3d11.log:not required
- dxgi.log:not required

**Comment by Blisto91** [comment]
If you don't want dxvk to report your gpu as amd you can create a file called `dxvk.conf`` in the same folder as the games exe and the dxvk files with this line
```
dxgi.nvapiHack = False
```

**Comment by washingleavesandthensome23-434** [comment]
dxvk.enableAsync = True
dxgi.nvapiHack = False


already done that ....still dont get RTX features unlocked

**Comment by Blisto91** [comment]
dxvk only handles dx9, dx10 and dx11 to vulkan.

In proton `vkd3d-proton` is used for dx12 to vulkan.
https://github.com/HansKristian-Work/vkd3d-proton#a-note-on-using-vkd3d-proton-on-windows

But i don't know about using it on windows 7 or windows at all for that matter.

**Comment by washingleavesandthensome23-434** [comment]
yes im using a patched pack to get it ....running in dx12, .....atleast it should...but its not running in dx12 according to amid evils settings

got if from here >

https://www.youtube.com/watch?v=I0Fq9qGk0zQ

**Comment by doitsujin** [comment]
> already done that ....still dont get RTX features unlocked

You need to set the environment variable `VKD3D_CONFIG=dxr` and obviously run the game in D3D12 mode to enable DXR.

**Comment by washingleavesandthensome23-434** [comment]
dxvk.enableAsync = True
dxgi.nvapiHack = False
VKD3D_CONFIG = dxr


nopes still tells me to relaunch in dx12 mode

**Comment by K0bin** [comment]
> dxvk.enableAsync = True

That option doesnt exist.

**Comment by washingleavesandthensome23-434** [comment]
it does ....for the async fork 

https://github.com/Sporif/dxvk-async/releases

**Comment by Blisto91** [comment]
> VKD3D_CONFIG = dxr

That option is not for the `dxvk.conf` file. You have to set it as a environment variable.
If you run the game through steam you can add this to the games launch properties.
```
VKD3D_CONFIG=dxr %command%
```

**Comment by washingleavesandthensome23-434** [comment]
VKD3D_CONFIG=dxr %command% -dx12

i get the message dx12 is not supported on your system

**Comment by Blisto91** [comment]
If the game says "dx12 is not supported on your system" then i would guess it will detect that you are on windows 7 and refuse to enable dx12.
And i would guess you wouldn't be able to work around that.

**Comment by doitsujin** [comment]
I somehow missed the whole Windows 7 thing.

Can we ***PLEASE*** stop with this kind of bullshit? D3D12 is not supported on Windows 7 unless the game explicitly ships the [12-on-7](https://devblogs.microsoft.com/directx/porting-directx-12-games-to-windows-7/) runtime, and vkd3d-proton will not change that since games tend to actually check the Windows version. Yes, exceptions where it *does* work may exist, but it's not the norm, nor expected, and by opening bug reports when running an *explicitly unsupported configuration* here just wastes everybody's time.
