### ISSUE TITLE
All of the fnaf and fan games just don’t work 

### ISSUE THREAD

**Issue by Thekraydot** [doitsujin/dxvk#2507]
The sound is there but the gameplay doesn’t show up

**Comment by Thekraydot** [comment]
I’m on Linux mint btw

**Comment by doitsujin** [comment]
um, what?

**Comment by Thekraydot** [comment]
Five Nights At Freddy’s 1 2 3 4 doesn’t work when used with dxvk only thing that works is sound

**Comment by Thekraydot** [comment]
I don’t speak fluent English sorry

**Comment by nanokatze** [comment]
Please fill out the issue template found at https://github.com/doitsujin/dxvk/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Evernow** [comment]
> I don’t speak fluent English sorry

Doesn't excuse you from not using the issue template.

**Comment by K0bin** [comment]
We can't do anything here without more information. Feel free to reopen when someone has provided that.
