### ISSUE TITLE
Dragon Nest - font rendering issue

### ISSUE THREAD

**Issue by dnblank123** [doitsujin/dxvk#2509]
### Software information
Dragon Nest 
Settings: All low

### System information
- GPU: 1050 TI
- Driver: 511.72
- Wine version: 
- DXVK version: 1.9.4 #2157 

### Apitrace file(s)
https://drive.google.com/file/d/1B_71ky9IgRH5ui5zOlASUnsMAEOH3nhg/view?usp=sharing

### Screenshots
w/o DXVK
![good](https://user-images.githubusercontent.com/67945097/154921417-87f3f684-39eb-4568-b4ca-b2fd9a6e2d3f.png)

with DXVK
![brok](https://user-images.githubusercontent.com/67945097/154921519-88cafdb0-fbf0-45fa-9767-fc2fccfe96bc.png)

### Log files
- d3d9.log: [DragonNest_x64_d3d9.log](https://github.com/doitsujin/dxvk/files/8107754/DragonNest_x64_d3d9.log)

**Comment by K0bin** [comment]
That PR should fix it.
