### ISSUE TITLE
DXVK Windows - Nioh 2 No Cutscenes

### ISSUE THREAD

**Issue by Zeinder** [doitsujin/dxvk#2510]
Nioh 2 when using dxvk in windows with it yields the same lack of video playback as linux. I would expect the mfplat based issues that prevent playback would not be present in windows. I don't know how to do indepth logging in windows or I would provide a log file.

Windows 10
5800x
5700xt

**Comment by doitsujin** [comment]
What do i need to do to get to a point where the game would play pre-rendered video? Is starting a new game enough?

I'll look into this, if the game relies on more D3D11 video interfaces we might be somewhat screwed but we got Nier Replicant to work as well, so there's that.

**Comment by Zeinder** [comment]
If you start the game, a video will play right after the company logo. Or it would, but instead provides an error about video.
![image](https://user-images.githubusercontent.com/7060121/155255563-2a8f4a90-53c2-4c05-a41b-7cff755fc9d7.png)

**Comment by Oschowa** [comment]
The game, like Nioh 1 and other KT games, uses shared resources for the videos, so it not working with DXVK is expected.

**Comment by Zeinder** [comment]
I take it's not possible or not currently planned then?

**Comment by Oschowa** [comment]
On windows it might never work with DXVK.

**Comment by Blisto91** [comment]
Shared resources have been implemented so this now works on Linux. Probably doesn't work on windows as it is tied together with some wine work. 
But remember that Windows isn't officially supported.
