### ISSUE TITLE
abnormal program termination

### ISSUE THREAD

**Issue by yjacks** [doitsujin/dxvk#2519]
No log at Windows and wined3d

### Software information
Touhou 18th 東方虹龍洞　～ Unconnected Marketeers.

### System information
- GPU:AMD HD4350
- Driver:radeon
- Wine version: wine7.3
- DXVK version: 1.9.4

### Log files
- d3d9.log:https://fars.ee/6mam
- d3d11.log:none
- dxgi.log:none

### others
2 end of line
0024:err:vulkan:wine_vk_instance_load_physical_devices Failed to enumerate physical devices, res=-3
0024:err:vulkan:wine_vkCreateInstance Failed to load physical devices, res=-3
terminate called after throwing an instance of 'dxvk::DxvkError'

**Comment by K0bin** [comment]
That GPU does not support D3D11, let alone Vulkan.

**Comment by yjacks** [comment]
I speak the Intel HD (Haswell) GT1,It's support Vulkan 1.1 and dx11_1,but problem not change.

**Comment by K0bin** [comment]
Vulkan support on anything prior to Broadwell is incomplete and Intels Windows Vulkan drivers are known to be problematic.

Besides this, your log shows that there's no Vulkan driver installed.
