### ISSUE TITLE
Running the game Frostpunk in windows + dxvk environment has low performance

### ISSUE THREAD

**Issue by semmyenator** [doitsujin/dxvk#2520]
### Software information
Frostpunk
(https://store.steampowered.com/app/323190/Frostpunk/)

### System information
- GPU: NVIDIA GeForce GTX 1660 SUPER
- Driver: 511.23.0
- Wine version: N/A (windows 11)
- DXVK version: v1.9.4

### Apitrace file(s)
- N/A

### Log files
- d3d11.log:[Frostpunk_d3d11.log](https://github.com/doitsujin/dxvk/files/8168307/Frostpunk_d3d11.log)
- dxgi.log:[Frostpunk_dxgi.log](https://github.com/doitsujin/dxvk/files/8168308/Frostpunk_dxgi.log)

### Additional info
- Game can work with dxvk
- But the relative performance is worse than Dx11
- How does it look with DXVK:
![FPDX11](https://user-images.githubusercontent.com/73735725/156333599-650adca6-d14b-45fa-b1d0-90c1d37859f5.jpg)
![FPDXVK](https://user-images.githubusercontent.com/73735725/156333610-6e5b5820-f8c8-409d-9811-f494616005b0.jpg)

**Comment by doitsujin** [comment]
What's the issue here? DXVK is expected to be slower than Nvidia D3D11.

**Comment by semmyenator** [comment]
> What's the issue here? DXVK is expected to be slower than Nvidia D3D11.

There's nothing special about it, it's just that I've tried different graphics cards and it doesn't seem to improve much in terms of performance, which confuses me
