### ISSUE TITLE
sekiro heavy flickering

### ISSUE THREAD

**Issue by yoshidinn** [doitsujin/dxvk#2523]
so i'm a windows user, only trying this out bc ive seen people report dxvk working on sekiro on windows with improved performance, needed a bump since my gpu is old/weak. downloaded 1.9.4 put it on sekiros folder and the game would boot but flicker heavily on the title screen and by heavy flickering i mean almost every letter of the title screen disappearing and reappearing rapidly, thought that was a shader loading situation closed n booted the game up again or tried to at least, wouldn't open until i deleted every dxvk file from the foulder. After that i bumped down to 1.8, not entirely sure if this is what caused the game to be able to open after the first time but still heavy flickering. 
i tried messing with a bunch of things to troubleshoot was thinking it might be a driver issue or version of the game issue then i bumped all the way down to version 1.5.2 and the flickering was entirely gone, but the fps would drop to 1 and the game would freeze

 am aware this application isn't really made for me but if possible and if any of this rung any bells i'd like to know what this is a symptom of? just the fact im running windows or a driver issue? maybe this doesn't work on every version of sekiro?

**Comment by doitsujin** [comment]
No idea which gpu/driver you're on but the game runs perfectly fine on Linux.
