### ISSUE TITLE
GTA V rendering issues with MSAA enabled

### ISSUE THREAD

**Issue by adolfintel** [doitsujin/dxvk#2525]
When MSAA is enabled, some transparencies are not rendered correctly (see attached screenshots).

Sometimes this happens immediately after launching the game or it can take a few minutes or a few character switches. It does not happen when MSAA is disabled.

Foliage becomes either invisible or semi translucent, occasionally the wrong LOD is rendered, broken shadows on foliage was also observed once but I wasn't able to replicate it. Other transparencies (like particle effects, wires, etc.) are also affected occasionally.

Changing graphics settings or pressing Alt+Enter solves this issue temporarily, but it occurs again after a few minutes.

### Software information
GTA V (tested current version as well as older 1.41 version, same result)

### System information
- GPU: AMD Radeon RX 6900 XT
- Driver: RADV Mesa 21.3.7
- Wine version: Latest version of wine-ge (https://github.com/GloriousEggroll/wine-ge-custom/releases)
- DXVK version: 1.10 (also tested on 1.9.4 and current master)
- OS: Manjaro (Kernel 5.16)

### Apitrace file(s)
I was unable to make a caputre so I'm open to suggestions. I tried the following commands:
* `apitrace trace --api dxgi --output "C:\gtav.trace" PlayGTAV.exe`: this causes the game to crash while loading
* `apitrace trace --api dxgi --output "C:\gtav.trace" GTA5.exe`: the game works but apitrace fails to inject its DLL

### Log files
[logs.zip](https://github.com/doitsujin/dxvk/files/8190358/logs.zip)
Note: the logs mention a dxvk.conf file, I used it to test various settings but it was empty when the screenshots and these logs were made.

### Screenshots
![glitch](https://user-images.githubusercontent.com/16307689/156877101-34f0d89d-2d06-4e6b-8dc2-d3292de32b72.png)
![glitch 2](https://user-images.githubusercontent.com/16307689/156877096-265c0471-5462-4966-ba61-cd31adbd3934.png)
![glitch 3](https://user-images.githubusercontent.com/16307689/156877098-39373240-6b7d-4970-858e-f9bd17422099.png)
![glitch4](https://user-images.githubusercontent.com/16307689/156877102-81640eec-e7f2-4974-a738-96501d4adfd9.png)
![glitch5](https://user-images.githubusercontent.com/16307689/156877103-eb54b4c3-d470-48a5-a874-a9f2b1adfb7a.png)

**Comment by Oschowa** [comment]
Can you also provide screenshots of how it's supposed to look? It doesn't look obviously broken to me.  
Also you could try with RADV_DEBUG=nodcc,notccompatcmask,nohiz, RADV_DEBUG=llvm or using AMDVLK.  
  
As for recording an apitrace, you want to download the win64 release from [here](https://github.com/apitrace/apitrace/releases/tag/10.0) and place the `d3d11.dll`, `dgxi.dll` and `dxgiretrace.dll` from there next to the game's .exe and then run the game. The trace file will be in `$WINEPREFIX/drive_c/users/$USER/Desktop`

**Comment by adolfintel** [comment]
Sure, here's how the tree from the first screenshot is supposed to look like
![image](https://user-images.githubusercontent.com/16307689/156881040-1fac4f77-ecdd-4eea-b9ad-54d3241a3bde.png)

And the same tree again during the day for better clarity
![image](https://user-images.githubusercontent.com/16307689/156881089-5593e83d-6e38-4ce4-9f4c-6b8d2cd6df60.png)

Copying the DLLs from apitrace just makes the game crash instantly.

AMDVLK seems to render correctly, and I also found another game with rendering issues with MSAA that worked fine 2 weeks ago, so it may be a Mesa or a RADV bug introduced with 21.3.7 (I'm guessing Mesa since this other game doesn't use vulkan)

**Comment by Oschowa** [comment]
Try the RADV_DEBUG options i mentioned earlier and open a bugreport on the [Mesa gitlab](https://gitlab.freedesktop.org/mesa/mesa/-/issues). If you can it would probably be helpful to record a renderdoc capture of the issue or to bisect Mesa if you think it's a regression introduced with 21.3.7.

**Comment by adolfintel** [comment]
I managed to build the current mesa master and it doesn't seem to have this problem. I wasn't able to test the other problematic game because I couldn't figure out how to build a 32 bit version of mesa.

I'm closing the issue since it's clearly not a DXVK problem.
