### ISSUE TITLE
GTA 5 Settings don't apply/work

### ISSUE THREAD

**Issue by Od1sseas** [doitsujin/dxvk#2528]
### Software information
Grand Theft Auto 5

### System information
- GPU: GTX 1660 Super
- Driver: 511.79
- Wine version: I'm running Windows 11
- DXVK version: 1.10

### Log files
[GTA5_d3d11.log](https://github.com/doitsujin/dxvk/files/8198680/GTA5_d3d11.log)
[GTA5_dxgi.log](https://github.com/doitsujin/dxvk/files/8198682/GTA5_dxgi.log)

**Comment by doitsujin** [comment]
yes they do.
