### ISSUE TITLE
Poor performance in Mortal Kombat 11

### ISSUE THREAD

**Issue by SeraphisCain** [doitsujin/dxvk#2532]
### Software information
Mortal Kombat 11
Settings used: Both high preset and low preset

### System information
- GPU: NVIDIA GTX 1650 Super
- Driver: 510.54
- Wine version: 7.0
- DXVK version: 1.10-async

First off, apologies for the lack of log files. They're not where they're supposed to be for some reason, and even when setting a different location via DXVK_LOG_PATH they don't seem to be getting generated. I'll absolutely post them if I can figure out why they're not being generated.

The issue: Extremely poor performance in MK11 relative to hardware. I *should* be able to hit 60 FPS easily on the high preset, but even on the low preset my framerate hangs around the 40-45 FPS mark. I have a bad feeling that it's going to end up being a VRAM issue that nothing can be done about (I have 4GB, which would be sufficient for this game on high settings on Windows, but possibly not sufficient here), but I figured I might as well confirm it before giving up. In the absence of logs, here's a couple screenshots of DXVK_HUD and my NVIDIA profile:
![2022-03-10_00-54](https://user-images.githubusercontent.com/67637185/157602108-c702889b-4ec5-4917-a6a9-e4d6af40c229.png)

![2022-03-10_00-55](https://user-images.githubusercontent.com/67637185/157602123-a0b09028-00c5-4c9f-bcd1-d4188b2e6f0e.png)

**Comment by doitsujin** [comment]
You're running out oif VRAM, try lowering your settings.

**Comment by doitsujin** [comment]
As mentioned, your 4GB GPU is effectively a 3GB GPU on Linux due to some Nvidia driver jank, and DXVK doesn't have sophisticated memory management like Windows does.

You could try convincing the game that you have less VRAM than you actually do (something like `dxgi.maxDeviceMemory = 2048` in dxvk.conf) and see if that helps, but there's not much we can really do here, the game seems to require 5-6 GB to run well.

**Comment by Blisto91** [comment]
@SeraphisCain If you are still around can you give this a go with lastest master. Handling of vram should at least have improved a bunch

**Comment by Blisto91** [comment]
@SeraphisCain Double friendly ping

**Comment by SeraphisCain** [comment]
> @SeraphisCain Double friendly ping

Thanks for the pings but I've long moved back to Windows for gaming (and no longer use this GPU). This was actually the "last straw" that got me to move back after having several issues on Linux. Happy to hear that it's been resolved though!
