### ISSUE TITLE
[Feature Request] Write procces name to dxvk-cache.

### ISSUE THREAD

**Issue by begin-theadventure** [doitsujin/dxvk#2533]
If cache is opened in a text editor it only has "DXVK" in a standard text, I think it would be great if it also included name of the process, something like DXVK-processname.
Why?
Currently there's no way to verify if a cache is for x process, name of the file is easy to change, it's somewhat possible with entries (merge a trusted cache with a random one, all entries merged=not for this process) but not really.

If cache was used for more processes they would all appear in it in a standard text.

This would come in handy while exchanging caches.

**Comment by doitsujin** [comment]
I don't understand why this is needed. The files are already named after the executable.

**Comment by begin-theadventure** [comment]
Isn't it harder to change the binary?

**Comment by begin-theadventure** [comment]
Isn't it much harder to change the binary?
