### ISSUE TITLE
Civilization IV: Beyond the Sword: Broken UI rendering

### ISSUE THREAD

**Issue by K0bin** [doitsujin/dxvk#2535]
The UI in Civ 4: Beyond the Sword is not rendered correctly:
![image](https://user-images.githubusercontent.com/1131720/157888287-948e9be5-dcaa-4b03-b87a-e30181019824.png)

The fun part is that the issue can not be reproduced reliably. On some runs it looks perfectly fine:
![image](https://user-images.githubusercontent.com/1131720/157888399-07146de1-6c08-4cce-a26a-7bb4441a6ae0.png)

First reported here: https://github.com/GloriousEggroll/protonfixes/pull/67

The UI is rendered using the fixed function pipeline.

### Software information
Civilization IV: Beyond the Sword

### System information
- GPU: Nvidia RTX 3090
- Driver: 470.62.20
- Wine version: Proton 7
- DXVK version: 1.10

### Apitrace file(s)
https://drive.google.com/file/d/17rMHDRPljLGrikF11_tYczSK5AkJ_jE5/view?usp=sharing

### Log files
- d3d9.log: Irrelevant.

**Comment by wodim** [comment]
I am seeing something similar in WoW:

![image](https://user-images.githubusercontent.com/1001553/159191723-3838e19e-1024-41aa-92ed-fb87d6c29761.png)

Is this the same bug?

**Comment by thisismyaccount1996** [comment]
I have this exact same issue on Civilization 4 (Beyond the Sword) with DXVK 1.10.  Rolling back to DXVK 1.9.4 fixes the issue.  Other information is below.

```
$ uname -a
Linux zzzzzz 5.17.0-1-MANJARO

$ wine --version
wine-7.4
```

Something between DXVK 1.10 and 1.9.4 must have broken this.
