### ISSUE TITLE
Question, is it possible for DXVK to support DXGI Flipmode on an OS that doesnt include DXGI Flipmode but only bitblt ?

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [doitsujin/dxvk#2537]
is it possible as said for DXVK to use Vulkan Apis to substitute DXGI Flipmode to get DXGI Flipmode apps to work on OS that only supports bitblt ?

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace.
Preferably record the trace on Windows, or wined3d if possible.

**Reports with no log files will be ignored.**

### Software information
Name of the game, settings used etc.

### System information
- GPU: RTX 2080 ti
- Driver: 473.04
- Wine version: 
- DXVK version: 1.10

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by doitsujin** [comment]
> on OS that only supports bitblt

Are we talking about Windows 7 here?

Depends on whether the app you're trying to run works with DXVK, in general it should work, much like we also expose D3D11.1 on Windows 7, but we're not really giving much thought to maintaining compatibility to that OS.

**Comment by washingleavesandthensome23-434** [comment]
app works with dxvk, question was if for example using special k which uses dxgi flipmode , would it be possible to get special k to run on w7 by using dxvk ...

**Comment by doitsujin** [comment]
Don't know, just test it for yourself? SpecialK doesn't support Windows 7 and I don't know if flip model swap chains are really the only issue.

Also, don't expect SK's frame limiter to work with DXVK, for some reason it **really** doesn't like the way we implement frame latency events.

**Comment by washingleavesandthensome23-434** [comment]
know anyone who could or would be willing to help get special k to run on w7? would even pay if i must, also interesting bout the frame limiter issue , not sure if fixable?

**Comment by doitsujin** [comment]
No.
