### ISSUE TITLE
I cann't compile the files..

### ISSUE THREAD

**Issue by Sebastiangperez** [doitsujin/dxvk#254]
I cann't compile the files i have all installed but when i run the command 

meson.build:1:0: ERROR: Compiler /usr/bin/x86_64-w64-mingw32-gcc can not compile programs.

I dont know what is the problem .. 

Thanks

**Comment by addeps3** [comment]
Which command?

**Comment by Sebastiangperez** [comment]
Sorry 
this command
meson --cross-file build-win64.txt --prefix /home/sebastian/Descargas/dxvk-master build.w64

**Comment by Sebastiangperez** [comment]
Yep , i made a simple c++ hello word and works ..

**Comment by ssorgatem** [comment]
...with wine, right? a hello_world.exe?

**Comment by Sebastiangperez** [comment]
Yes yes , it was an exe file i run with wine , no problems.

**Comment by Sebastiangperez** [comment]
ok , i found the problem , i dont have threads installed , but now gave me another error , Unknown compilers .. 

meson.build:1:0: ERROR: Unknown compiler(s): ['c++', 'g++', 'clang++']
The follow exceptions were encountered:
Running "c++ --version" gave "[Errno 2] No such file or directory: 'c++': 'c++'"
Running "g++ --version" gave "[Errno 2] No such file or directory: 'g++': 'g++'"
Running "clang++ --version" gave "[Errno 2] No such file or directory: 'clang++': 'clang++'"

**Comment by Kerrung** [comment]
So, may be close it?
