### ISSUE TITLE
Jan Zeleny's Mashinky - menus and windows are missing background and fonts

### ISSUE THREAD

**Issue by kubapet** [doitsujin/dxvk#2541]
Broken rendering of game UI - menus and windows are missing background (and fonts in some cases). It works well with Proton 7.0-1 and 6.8-3 and it used to work on Experimental as well, but the last couple of weeks it is broken (it stated with the main menu and later it started to appear even in the game). Tried even the Proton bleeding edge branch and it is broken there as well. The game uses DX9 only and it seems to be some recent regression.

See the attached picture for details.

Name of the game with compatibility issues: Jan Zeleny's Mashinky
Steam AppID of the game: 598960
System Information
GPU: RTX 2060
Driver/LLVM version: nvidia 510.54-9.1
Kernel version: 5.16.11-1-default (OpenSuSE Tumbleweed)
Link to full system information report as [Gist](https://gist.github.com/):
Proton version: Experimental

I currently do not want to spend more time on investigating how to generate the different api traces, but it can be reproduced by installing the game in steam and changing enforcing the Proton Experimental as compatibility layer. 

See the report I recently created in Proton GitHub repo: https://github.com/ValveSoftware/Proton/issues/5679
Let me know if you still need more information, in that case I will try to allocate some time to investigate more during the upcomming few weeks..

![mashinky](https://user-images.githubusercontent.com/8698550/158220917-d168814b-ecee-47de-9470-6a3fd49d622f.png)

**Comment by K0bin** [comment]
I fixed a similar bug in another game recently, try a build of DXVK master.
https://github.com/doitsujin/dxvk/actions/runs/1976990024

**Comment by K0bin** [comment]
If that does not fix it, then please provide the apitrace and logs. I don't own that game.

**Comment by kubapet** [comment]
I assume, the fix you made is already available on the proton experimental bleeding edge branch.. It is probably related to https://github.com/doitsujin/dxvk/issues/2535 right? 

The thing is that I do not know how to build dxvk, which I would probably figure out but then I also need to let Proton use it somehow, which I don't know either and it seems like it would take me a lot of time - I d probably also need to install some dev packages and I don't know if it is possilbe to generated from the Game's Proton's wine prefix or if I have to create new one and install the game from scratch and then use WineD3D and then replace the libs as described in the how to?

**Comment by kubapet** [comment]
> That's why I linked the CI page. Just download the zip from there, grab the 32bit d3d9.dll and put that into the game folder right next to the .exe file.

It is 64bit it seems, but either way, I tried to download the pre-build apitrace files and when I access the link (https://ci.appveyor.com/api/projects/jrfonseca/apitrace/artifacts/build/apitrace-latest-win64.7z?branch=master&job=msvc64) I get: `{"message":"Artifact not found or access denied."}`

**Comment by Blisto91** [comment]
@kubapet 
Try 10.0 found here https://github.com/apitrace/apitrace/releases :)

**Comment by kubapet** [comment]
Ok, here is some trace_dump generated by the game probably

[trace_dump.log](https://github.com/doitsujin/dxvk/files/8247910/trace_dump.log)

and here is the apitrace:

https://uloz.to/tamhle/36P8RvWo6uQD/name/Nahrano-14-3-2022-v-20-16-05#!ZGx3ZmR2ZmyvMTDlZGp2BQSxAGZmL0EEqGMTo2cSna40EGIyMt==

**Comment by K0bin** [comment]
That file hoster appears to be blocked in Germany for whatever reason so I can't access it.

**Comment by kubapet** [comment]
OK, I created an account on mega: https://mega.nz/file/CoshxQLJ#pFHO6jrPOHxOVQPpUoimifjCUgAPp_xLGkVa34za10k

**Comment by K0bin** [comment]
Thanks for the apitrace. That PR should fix it.

**Comment by kubapet** [comment]
Woho! that was fast :) thanks a lot! I wish I could contribute more, but I have no experience directx and vulkan so far 😐

**Comment by kubapet** [comment]
I confirm the bug has been fixed
![image](https://user-images.githubusercontent.com/8698550/158343415-8d75c822-a83b-434c-b393-3d329fa595e0.png)
