### ISSUE TITLE
black windows in dotnet applications

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [doitsujin/dxvk#2542]
try using the visual studio installer (or the reshade installer) with wine 7.4, it renders fine with wined3d and it doesn't render fine with dxvk, with dxvk, the window is black unless you move you mouse in which case the portion of ui element you are hovering over reveals itself and turns the rest of the window black. 
![image](https://user-images.githubusercontent.com/45927311/158269928-0068df2b-4d6b-4ab4-ae14-f97d551aaca1.png)

the easy solution to this would be add some env variable that disables dxvk or the tougher one, which is patching dxvk

**Comment by doitsujin** [comment]
Needs more info, especially log files. This is probably some partial present bullshit though which we don't support.

**Comment by Etaash-mathamsetty** [comment]
[ReShade_Setup_5.0.2_d3d9.log](https://github.com/doitsujin/dxvk/files/8307918/ReShade_Setup_5.0.2_d3d9.log)
this is the dxvk log, dosen't seem like anything special is in there

**Comment by Etaash-mathamsetty** [comment]
this bug is also easily reproduceable, so you can go download reshade and get extra info if needed

**Comment by xpander69** [comment]
Similar issue with Warhammer Online Return of Reckoning Launcher. dotnet40
works with wined3d, but doesn't with DXVK.

![26032022_15 55 45](https://user-images.githubusercontent.com/1345116/160242698-71718077-ace0-4b65-9115-10fec3c5b91e.png)
log: [RoRLauncher_d3d9.log](https://github.com/doitsujin/dxvk/files/8355565/RoRLauncher_d3d9.log)


Launcher can be downloaded from here: http://launcher.returnofreckoning.com/RoRLauncher.exe
no account needed, but it will start to download files, be aware

**Comment by Faalagorn** [comment]
It seems to be the exact case of #2278 as indeed it seems to be a partial present.

For Tarkov the workaround was to force wined3d for DX9 since it's what launcher uses and the actual game uses DX11.

**Comment by SpookySkeletons** [comment]
VRCX also seems to suffer from partial present issue.
Not a massive handicap, but what makes partial so stubborn to address?

**Comment by xpander69** [comment]
You could try this: https://github.com/doitsujin/dxvk/issues/2568#issuecomment-1085832406

Works with Warhammer: Return of Reckoning launcher. Might work with other dotnet launchers as well

**Comment by Etaash-mathamsetty** [comment]
can confirm that this fix works

**Comment by Etaash-mathamsetty** [comment]
![image](https://user-images.githubusercontent.com/45927311/161403843-ae886d2a-a448-4e2e-92fb-5ca479769d79.png)
that looks a bit better

**Comment by K0bin** [comment]
Why are you running the Visual Studio installer with DXVK?

**Comment by Etaash-mathamsetty** [comment]
> Why are you running the Visual Studio installer with DXVK?

because i have it installed in my main wine prefix...
