### ISSUE TITLE
[D3D9] Rayman Origins: Mostly missing Electoon hair in World 1 Finale

### ISSUE THREAD

**Issue by Sterophonick** [doitsujin/dxvk#2545]
In Rayman Origins, every single world has a finale at the end. In the world 1 finale, the hair from little creatures known as Electoons is supposed to grow and create a pathway for the player to traverse to get to the end. When using DXVK, this hair is mostly missing, but little chunks of it are still visible. 

### DXVK
![image](https://user-images.githubusercontent.com/34801996/158523232-2e56d24c-471f-434b-87b7-2496ce372d5b.png)

### Correct Behavior (Achieved with dgVoodoo2)
![image](https://user-images.githubusercontent.com/34801996/158523265-3077c9c0-be9a-4572-81fe-2360ba566daf.png)

### Software information
Rayman Origins (207490), default settings

### System information
- GPU: Mesa Intel CometLake-U GT2 [UHD Graphics]
- Driver: Mesa 21.3.7
- Wine version: GE-Proton7-9
- DXVK version: https://github.com/doitsujin/dxvk/commit/89b1f025ebad7498ac21e5726306245ebc646e59 (with async)

### Apitrace file(s)
[Rayman Origins.trace](https://anonfiles.com/r9q787O7x7/Rayman_Origins.trace_7z)

### Log files
[Rayman Origins_d3d9.log](https://github.com/doitsujin/dxvk/files/8259168/Rayman.Origins_d3d9.log)

**Comment by DadSchoorse** [comment]
That PR fixes the issue for me on nvidia, please test.

**Comment by Sterophonick** [comment]
> That PR fixes the issue for me on nvidia, please test.

That fixed it! Fantastic work!
![image](https://user-images.githubusercontent.com/34801996/158600087-6b94d088-fbb3-4bb1-82e5-ff284e70d13d.png)
