### ISSUE TITLE
Remedy's Control D3D11 crush during fighting scene.

### ISSUE THREAD

**Issue by artivision** [doitsujin/dxvk#2548]
Good day, not a serious problem since can by bypassed with Vkd3d-Proton but i thought that i should write it anyway. During fighting Anchor the game will crush with i serious D3D11 message on Radv - Polaris Gpu.

**Comment by K0bin** [comment]
What's the message? We need logs and an apitrace of it happening.

**Comment by doitsujin** [comment]
At the very least provide log files and a savegame so we can actually **try** to reproduce the problem. I'm not going to spend 20 hours playing a game I don't like because someone with a track record of filing useless reports and feature requests isn't providing the info we need.

**Comment by artivision** [comment]
https://easyupload.io/gnkrdj

=> Active Investigations on the map => Play the Right Slot Machine => Choose the Anchor boss

**Comment by K0bin** [comment]
And what is the D3D11 message you were talking of?

**Comment by doitsujin** [comment]
Seems to work fine here.

**Comment by doitsujin** [comment]
Might be specific to the GOG build somehow, found someone else who could reproduce the crash in that section on Nvidia using the GOG version but it doesn't crash on my system using the Steam build and Proton 7.0 (with dxvk master).

**Comment by Iglu47** [comment]
Are you sure there is no such problem on Windows?
https://www.pcgamingwiki.com/wiki/Control#Crash_to_desktop_when_fighting_Anchor_boss
https://www.reddit.com/r/controlgame/comments/ilex75/anchor_boss_fight_crash/
People on Youtube are still talking about this problem:
https://www.youtube.com/watch?v=PBAZ5Uzp2rU&lc=UgyPqjcWNdm_lQ3JVZt4AaABAg.9Y-SvjEXvgt9Y-U9HIvRpB&t=9222s

**Comment by artivision** [comment]
Cannot help any more cause i don't have the game now, using it only for tests and yes its Gog. It crushes every single time on all my computers (all Polaris Gpu), on all Mesa Radv versions, all Linux operating systems and Kernels and at least on the last three Dxvk versions. Shows a critical D3D11 error that i don't remember now. I don't use Windows.

**Comment by doitsujin** [comment]
https://www.gog.com/forum/control/ctd_in_anchor_fight game bug, nothing we can do here.
