### ISSUE TITLE
Fatal Error: Uploading texture failed! D3DERR_INVALIDCALL

### ISSUE THREAD

**Issue by Augusto7743** [doitsujin/dxvk#2559]
Tested in both WINE 6.X (last versions) and 7.2 in an clean WINE environment (delete all WINE folder and created an new one only installing gecko, MONO and DXVK).

DXVK 1.9.4 works without problems.
DXVK 1.10 works without problems with Raine emulator (use SDL OpenGL), but crash Visual Pinball 10.6.
When Visual Pinball load data (table) to start and before render the table window happen an crash with the message

Fatal Error: Uploading texture failed! D3DERR_INVALIDCALL 0x8876086c: invalid call at RenderDevice.cpp:1365

DXVK coders need any other information ? Please reply with any command thus I can to do any command to written logs.

Thanks very much for read.

**Comment by doitsujin** [comment]
Can you please post log files?

**Comment by K0bin** [comment]
https://github.com/vpinball/vpinball/blob/master/RenderDevice.cpp#L1605

Try #2553

**Comment by Augusto7743** [comment]
Thanks for your reply.
How create and where is the log files ?

**Comment by Augusto7743** [comment]
I need to add other information ... excuse me for not added in first reply.
OS Ubuntu 20.04  WINE 7.2 Nvidia driver 470.86 Geforce GT 640 (Vulkan 1.2)

**Comment by K0bin** [comment]
Please just try this build: https://github.com/doitsujin/dxvk/suites/5745004471/artifacts/190599030

It probably fixes the issue.

**Comment by Augusto7743** [comment]
Please that file is exactly the compiled DXVK ?
Only need extract and install ?

**Comment by K0bin** [comment]
Yes.

**Comment by Augusto7743** [comment]
Trying
https://github.com/doitsujin/dxvk/suites/5745004471/artifacts/190599030
"Page Not Found" in github
not is possible download the file

**Comment by K0bin** [comment]
You need to be logged in to download it. Works fine for me.

**Comment by Augusto7743** [comment]
Teste with your new dxvk-merge-b8e348e9e348e7e9c837c121bb12a9ecc61c8eaa.
The problem was fixed.
Analyzing and comparing between 1.9.4 and dxvk-merge-b8e348e9e348e7e9c837c121bb12a9ecc61c8eaa running Visual Pinball 10.6 :
- somes tables are using less GPU.
- I not have information if table physics are done using CPU or GPU, but now physics are better. Perhaps DXVK using less CPU and thus being better used in WINE Visual Pinball ?
- others tables are having same GPU usage, but with much better physics.

If you need any log please reply me. I only need information about what command to do and where copy the log.
Thanks very much for your work in DXVK.
Have an nice week.

**Comment by K0bin** [comment]
Physics (in D3D9 games) are done on the CPU and DXVK has nothing to do with that. What you're seeing is probably placebo.
