### ISSUE TITLE
Hearthstone instantly crashes - Access Violation

### ISSUE THREAD

**Issue by Komoszek** [doitsujin/dxvk#256]
Since wine-staging 3.5, starting Hearthstone with DXVK leads to instant crash. Without it, the only problem is permanent black screen.

### Software information
Hearthstone with default settings (DirectX11).

### System information
- GPU: GTX 960M
- Driver: Proprietary NVIDIA drivers 390.48.0
- Wine version: wine-staging 3.5-1
- DXVK version: [(acaf6c9)](https://github.com/doitsujin/dxvk/commit/acaf6c9e877dbf37d03032203b0dfc4814241c81)

### Apitrace file(s)
- [Google Drive](https://drive.google.com/open?id=1oRM0BJMjDvCdyE932BJzshD5Lr0RRDa5)

### Log files
- [d3d11.log](https://github.com/doitsujin/dxvk/files/1887177/Hearthstone_d3d11.log)
- [dxgi.log](https://github.com/doitsujin/dxvk/files/1887176/Hearthstone_dxgi.log)

### Additional files generated by the game itself
- [Google drive](https://drive.google.com/open?id=1ThvQ711EAVVvDRZH3eNVd0nTyx_q7yG2)

### Wine Output
- [wineoutput.log](https://github.com/doitsujin/dxvk/files/1887241/wineoutput.log)

**Comment by doitsujin** [comment]
I cannot replay the trace because it requires DXGI 1.2. Was that trace recorded on wined3d?

**Comment by Komoszek** [comment]
wined3d by launching apitrace windows executable via wine. Probably wrong way of doing this but i couldn't find another way.

**Comment by Komoszek** [comment]
[CrashBacktrace.log](https://github.com/doitsujin/dxvk/files/1887609/backtrace.log)

**Comment by Komoszek** [comment]
It's working again with the recent commits. Thanks!
