### ISSUE TITLE
[d3d9] Texture rendering issues. GTA:SA(MP)

### ISSUE THREAD

**Issue by Akkiop** [doitsujin/dxvk#2560]
Texture rendering issues. Game gta sa, with mod multiplayer - samp. There are no other problems. It should be:
![normal](https://user-images.githubusercontent.com/55927540/160106888-8807ae63-6431-4354-9b01-dd759adec7dd.png)
How displayed:
![fafaf](https://user-images.githubusercontent.com/55927540/160107042-8b50f5b9-fb1a-403d-8dbb-23524cd6be17.png)
[gta_sa_d3d9.log](https://github.com/doitsujin/dxvk/files/8349809/gta_sa_d3d9.log)

**Comment by K0bin** [comment]
I need an apitrace to fix that.

**Comment by Akkiop** [comment]
I tried to run it through apitrace for several hours and didn’t give any result, either I didn’t understand how to use it, or it doesn’t work on GTA sa, I checked everything works on other games, and when I try to start GTA sa, nothing happens at all, please help how it's right to do it for gta sa

**Comment by K0bin** [comment]
The issue you linked was fixed. I've had people make GTA SA apitraces in the past. Just copy the 32bit d3d9.dll in the folder where the gta sa exe is, run the game, do what you need to do to show what would be broken with DXVK. Then upload the .trace file that was created on your desktop.

**Comment by K0bin** [comment]
How do you even open that inventory in GTA San Andreas, i didnt even know the game has an inventory.

**Comment by Akkiop** [comment]
The fact is that this is not just gta sa, but with a mod for multiplayer, and this inventory is a server thing made on textdrives, I tried to use build of maste : [https://github.com/doitsujin/dxvk/actions/runs/2034097211](url)  the same error is there. When I just throw d3d9.dll (apitrace) into the root folder with the game, it does not start

**Comment by Akkiop** [comment]
How can you use both dxvk and apitrace at the same time if they are both d3d9.dll

**Comment by K0bin** [comment]
> How can you use both dxvk and apitrace at the same time if they are both d3d9.dll

You don't. I don't need you to use apitrace with DXVK, apitrace with normal Windows d3d9 is fine too and will allow me to see the issue when replaying the apitrace file.

**Comment by Akkiop** [comment]
https://drive.google.com/file/d/16-pYYrX0kJ98ADJJeEgwgW0WX6mM82xT/view?usp=sharing

**Comment by K0bin** [comment]
Should be fixed now.
