### ISSUE TITLE
[d3d9] Limbo: freezes after solving the last chapter puzzle

### ISSUE THREAD

**Issue by ranplayer** [doitsujin/dxvk#2564]
The game freezes after solving the last chapter puzzle and you are not able to see the ending.

**Reports with no log files will be ignored.**

### Software information
Name of the game: Limbo
Settings: default

### System information
- GPU: GTX 970 4Gb
- Driver: 510.60.02
- Wine version: Proton 7.0-1
- DXVK version: 1.9.4

### Apitrace file(s)
- [api trace](https://mega.nz/file/1p8zGbyK#1O6ddqTjQwxiHCa57-pRnwjcXxf6q0ZCaKiRREaW40s)

### Log files
- [d3d9.log](https://github.com/doitsujin/dxvk/files/8357822/limbo_d3d9.tar.gz)
- [proton log](https://github.com/doitsujin/dxvk/files/8357823/steam-48000.tar.gz)

**Comment by K0bin** [comment]
Would what you did in the apitrace usually have caused freezing with DXVK?

When I replay the trace, it doesn't freeze, you just jump around a couple of times and then quit out.

**Comment by ranplayer** [comment]
The game freezes only with DXVK. With the API trace's DLLs the ending is rendered. The issue happens after the character passes below the saw.

I'm goinf to test with WineD3D as well.

Thanks for the quick response.

**Comment by K0bin** [comment]
Can you upload your save pls?

**Comment by ranplayer** [comment]
Sure. As soon as I get home I will.

**Comment by ranplayer** [comment]
[savegame.tar.gz](https://github.com/doitsujin/dxvk/files/8361512/savegame.tar.gz)
Path: Steam-folder/userdata/<user-id>/48000/remote/

**Comment by K0bin** [comment]
Turns out that people have had this issue on Windows too: https://steamcommunity.com/app/48000/discussions/0/828927580808437726/

Does it work if you limit the frame rate to 60 fps? To do that put `DXVK_FRAME_RATE=60 %command%` into the steam launch options.

**Comment by ranplayer** [comment]
It did the trick. Since it is not a DXVK problem, I'm going to close the issue. Thank you very much for your help an attention.

**Comment by Joshua-Ashton** [comment]
Should add it for default.for the game
