### ISSUE TITLE
DXVK 1.10.1 better performance in Visual Pinball

### ISSUE THREAD

**Issue by Augusto7743** [doitsujin/dxvk#2567]
Comparing the performance using Visual Pinball between 1.10.1 and previous versions.
Ubuntu 20.04 Geforce GT 640 driver 470.

Visual Pinball 9 in DVXK previous version GPU usage was 100 % and with 1.10.1 GPU usage is below 75 %.
Visual Pinball 10.6 in DVXK previous version GPU usage was 45 % and with 1.10.1 GPU usage is below 37 %.

Even physics not are related with GPU now with 1.10.1 the physics are better perhaps because anything is freeing CPU resources.
In any way Visual Pinball using WINE and current DXVK are much better.

Thanks very much for all optimizations.

**Comment by TedHartDavis** [comment]
It's warming to see your kind words about the project helping you out! (:

Those behind DXVK are awesome.

However, I fail to see the problem this issue concerns.

**Comment by Augusto7743** [comment]
Bad understand.
I only had reported about current version have an better performance using Visual Pinball in WINE and say thanks.
In other words report to developer about results using current version.
I have been using DXVK for several previous versions and current version is much more faster than any previous version when using Visual Pinball.

"Even physics not are related with GPU now with 1.10.1 the physics are better perhaps because anything is freeing CPU resources."
DXVK creator had replied me saying physics not are related with GPU.
Thus is how now in current version DXVK use less CPU.

**Comment by K0bin** [comment]
Good to know it's faster now.
