### ISSUE TITLE
avp dx11 benchmark d3d11.dll not found

### ISSUE THREAD

**Issue by addeps3** [doitsujin/dxvk#257]
I have installed apitrace to my linux OS, but where do I get apitrace.exe?

### Software information

avp dx11 benchmark, gta5

### System information
- GPU:gtx 770
- Driver:  NVIDIA 390.48
- Wine version: wine-3.5
- DXVK version: master

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log:

**Comment by doitsujin** [comment]
Clearly a setup issue, install **both** 64-bit and 32-bit dxvk libraries if you are using a 64-bit wine prefix.
