### ISSUE TITLE
DXVK 1-10-1 only reporting log

### ISSUE THREAD

**Issue by Augusto7743** [doitsujin/dxvk#2577]
Few softwares are written logs.
Perhaps is an good information to share with DXVK developer.
Thus I need post here logs about ccleaner and Visual Pinball.

Thanks very much for developing DXVK.
Have an nice week.
[DXVK.zip](https://github.com/doitsujin/dxvk/files/8393755/DXVK.zip)

**Comment by WinterSnowfall** [comment]
I've always used dxvk to get 900+ fps in ccleaner :+1:

**Comment by K0bin** [comment]
What exactly is the problem here?

**Comment by Augusto7743** [comment]
Not problems.
Only reporting log to share with DXVK developer.
I only had copied logs created in few software folders because have information inside.
Perhaps have any important information ?

**Comment by K0bin** [comment]
They don't. Great that it works well for you, nothing for us to do here.
