### ISSUE TITLE
[dx3d11] Crysis Remastered

### ISSUE THREAD

**Issue by Johnnii360** [doitsujin/dxvk#2578]
I can't start Crysis Remastered with PROTON_ENABLE_NVAPI=1. I also asked in [this forum ](https://github.com/ValveSoftware/Proton/issues/5165) but they really can't help me yet. So Blisto91 suggested me to try to ask you if you maybe have any ideas.

### Software information
Steam Game-ID: 1715130
Crysis Remastered
Using GE-Proton7-10 but it's also with Valve's Proton 7.0-1

### System information
- GPU: Nvidia RTX 2070
- Driver: 510.60.02
- Wine version: 7.0
- DXVK version: v1.10.1

### Apitrace file(s)
I have no idea how to do this with Steam Proton. But I can show you the Proton Logs.

### Log files
With PROTON_ENABLE_NVAPI=1: [steam-1715130_1.log](https://github.com/doitsujin/dxvk/files/8398338/steam-1715130_1.log)
Without: [steam-1715130.log](https://github.com/doitsujin/dxvk/files/8398342/steam-1715130.log)

**Comment by doitsujin** [comment]
Resource sharing with Vulkan is unimplemented right now and will require Proton patches.

**Comment by Johnnii360** [comment]
Meh, it's working with software RT enabled but cost a lot of performance. But I think or hope you fix it soon. ;) Thx!

**Comment by K0bin** [comment]
The software RT runs extremely poorly on Nvidia GPUs with DXVK. It's fine on AMD GPUs.
