### ISSUE TITLE
Cursor stuck on game after opening and closing Steam overlay

### ISSUE THREAD

**Issue by sh0tx420** [doitsujin/dxvk#2581]
Opening the Steam overlay causes the mouse cursor to be stuck on the game screen forever until the game is restarted. Happens every single time.
#2174 may be related.

The game has its own cursor and the mouse cursor that gets bugged into the screen can not actually interact with the game's UI.

### Software information
- Game: [PAYDAY 2](https://store.steampowered.com/app/218620/PAYDAY_2/)

### System information
- GPU: NVIDIA GeForce GTX 1660 SUPER
- Driver: 512.15.0
- DXVK version: 1.10.1
- OS: Windows 10 

### Apitrace file(s)
I was unable to provide a trace file as it does not apparently get created for some reason

### Log files
- payday2_win32_release_d3d9.log: https://pastebin.com/BknXC0tL

**Comment by Blisto91** [comment]
It creates a log in your steam folder called `GameOverlayRenderer.log`

Here is one generated with the native game with me going into a offline match opening the overlay, left clicking and exiting the overlay and then they game.
[GameOverlayRenderer_native.log](https://github.com/doitsujin/dxvk/files/8411921/GameOverlayRenderer_native.log)

Here is same with dxvk.
[GameOverlayRenderer_dxvk.log](https://github.com/doitsujin/dxvk/files/8411922/GameOverlayRenderer_dxvk.log)
