### ISSUE TITLE
D3D FIX for DIRT 5

### ISSUE THREAD

**Issue by milo-it** [doitsujin/dxvk#2583]
Hello
are you able to issue a fix D3D DX12 for gtx960m cards or all non dx11, to be able to play DIRT 5 ?
thanks

**Comment by Blisto91** [comment]
I think you meant to open a issue at the [`vkd3d-proton` repo](https://github.com/HansKristian-Work/vkd3d-proton). dxvk doesn't handle dx12 games.

**Comment by K0bin** [comment]
And please actually tell us what's wrong with Dirt 5.

**Comment by Blisto91** [comment]
If i were to take a guess the 900 and 1000 series m cards can't launch dx12 games through vkd3d-proton. I think (at least some of them) are based on the 700 series which had sketchy support for even same dx11 feature levels (afaik).
That said the card still have driver support from nvidia, but i haven't been able to figure out why they don't work when i've tried to help people. A person with a 1050m get black screen with cursor on launch on age of empires 4 with vkd3d-proton as an example, same as 700 series cards.

**Comment by doitsujin** [comment]
Pascal and Maxwell 2 **can** run vkd3d-proton, albeit very poorly.

Anyway, wrong project and not enough info given for us to really do anything.

**Comment by Blisto91** [comment]
The 960m is stilling getting the latest drivers from Nvidia so i would it has support. Tho the `GM107` (series) chip based on doesnt have anymore yes. Gpu's can be confusing sometimes.
That said it isn't a dxvk issue either way.

**Comment by milo-it** [comment]
Hi.
The error I'm getting is
s_cpuReadbackBuffers[readbackBufferIndex][qID]->Map(0, &range, (void**)&pMappedMem)' failed with 'HR = 0x887a0005, Reason = Istanza del dispositivo GPU sospesa. Utilizzare GetDeviceRemovedReason per determinare l'azione appropriata.

**Comment by Blisto91** [comment]
@milo-it Can you make a issue at https://github.com/HansKristian-Work/vkd3d-proton instead? :)

**Comment by milo-it** [comment]
done
