### ISSUE TITLE
Total War: Shogun 2 using DXVK DXGI bypass laucnher selector for directx API

### ISSUE THREAD

**Issue by llde** [doitsujin/dxvk#2589]
Hi, When starting Total War : Shogun 2 using DXVK's DXGI skip the initial selector that allow to choose betwee DX9 and DX11 graphics
IT works on Wine DXGI
Also it reports a wrong VRAM size (2.9 G), different from the one reported with Wine DXGI (3.8G Still wrong)
### Software information
Total War : Shogun 2, at the start, graphic settings are not important

### System information
- GPU: RX580 8G
- Driver: RADV 22.0.1
- Wine version:  7.5
- DXVK version:  42c66c410e213f7504903744a5684a4e453f71f2

### Apitrace file(s)
- Seems to be unable to generate one, and not even sure if it should

### Log files
- dxgi.log:
[Shogun2_dxgi.log](https://github.com/doitsujin/dxvk/files/8430587/Shogun2_dxgi.log)

**Comment by doitsujin** [comment]
So what's the actrual issue here? Does the game default to D3D9 or D3D11?

> Also it reports a wrong VRAM size (2.9 G), different from the one reported with Wine DXGI (3.8G Still wrong)

This is not wrong. The game is 32-bit, and 32-bit DXGI does not support reporting more than 4GB of memory, so we decided to clamp the returned value to 3 GB.

**Comment by llde** [comment]
With DXVK DXGI the game default to D3D9

I can generate apitrace for other 32bit games fine (Oblivion for example). I will try again this evening

**Comment by Blisto91** [comment]
I'm not even able to launch the game when forced through proton (7.0-2rc dxvk 1.10.1) in dx11 mode. Only dx9 mode works.
In wine i can't get any of them working even after trying to install the deps included. But that probably more me being a newb at wine.

**Comment by Blisto91** [comment]
When i launch it through proton the only way i can get it not to appear is if i launch the game and then exit without it crashing.
That is because on a regular exit it writes everything down into the preferences file.
When you do a regular exit without the game crashing it will put this line into there
```
gfx_dx11_checked true; # gfx_dx11_checked <bool>, Have we checked that user wants dx11? #
```
This tells the game i have already answered the dialog and it shouldn't appear at next launch. If i set it to true or delete this line it will show again.
It seems to me it is by design that it will only show it once unless something goes wrong.

**Comment by llde** [comment]
Ok this is strange, I retryed after compiling  anew Wine Tkg (latest master + a couple of patches more on top), and DXVK and I'm not experiencing this anymore, the selector shows.
I'm puzzled, all'anima de li mejo mortacci loro

**Comment by Blisto91** [comment]
@llde Have this been a issue since?

**Comment by llde** [comment]
Not sure, I cannot test these days.

**Comment by Blisto91** [comment]
No worries :+1:

**Comment by K0bin** [comment]
The launcher shows up for me too.
