### ISSUE TITLE
[d3d9] The Godfather:The Game crashes at launch with DXVK, works with wined3d

### ISSUE THREAD

**Issue by Leopard1907** [doitsujin/dxvk#2590]
### Software information

The Godfather: The Game, any  graphical setting

Game works with wined3d and dgVoodoo2+DXVK.

Attempting to use DXVK without any other wrappers leads to a crash at boot.

This patch/mod is needed in order to avoid movies playing at launch, which normally causes a crash at launch on any system that is newer than XP.

https://cookieplmonster.github.io/mods/godfather/#silentpatch

Tests were done with this applied, in both `wined3d only`, `dxvk only` and `dxvk+dgvoodoo2` cases.

### System information
- GPU: NV GTX 1050
- Driver: 510.54
- Wine version: 7.5
- DXVK version: 1.10.1 and `master`

### Apitrace file(s)
- [godfather.trace.tar.gz](https://github.com/doitsujin/dxvk/files/8431096/godfather.trace.tar.gz)

Trace was captured with wined3d. Reproduces crash with DXVK.

### Log files
- d3d9.log: [godfather_d3d9.log](https://github.com/doitsujin/dxvk/files/8431168/godfather_d3d9.log)
- Wine output: 
[wine-output.txt](https://github.com/doitsujin/dxvk/files/8431243/wine-output.txt)

**Comment by K0bin** [comment]
The problem here is that Recreating the back buffer after Reset() fails because of an unsupported sample count.

**Comment by doitsujin** [comment]
Fixed now.
