### ISSUE TITLE
RESIDENT EVIL 6 in-engine cutscenes stutter a lot

### ISSUE THREAD

**Issue by kassindornelles** [doitsujin/dxvk#2593]
In-engine cutscenes in RESIDENT EVIL 6 stutter a lot, replaying cutscenes doesn't fix the issue (i thought it was shader compilation stuff but it really does not seems like it)

what it looks like:
https://www.youtube.com/watch?v=cm4og_gee4g

### Software information
RESIDENT EVIL 6 (Steam)

### System information
- GPU: RX 560 4 GB
- Driver: MESA 21.3.7 RADV (Vulkan-radeon/lib32-vulkan-radeon arch package)
- Wine version: Proton Experimental
- DXVK version: 1.10/1.10.1

### Apitrace file(s)
https://drive.google.com/file/d/199v5IcQUmRIpojeHsgiKoOeAG6vouuf-/view?usp=sharing

**Comment by Blisto91** [comment]
How do the stats look during the cutscenes if you run it with `DXVK_HUD=full %command%`

**Comment by K0bin** [comment]
I played the first half hour of the game yesterday and the game seems to compile on average 20-30 graphics pipelines per camera cut. So I strongly suspect this is just shader compilation stutter.

**Comment by Yasand123** [comment]
I think this should be re-opened. Another Capcom game behaves the exact same, _Dead Rising 2: Off the Record_. It would stutter like crazy every time you enter an area or rotate the camera.

So it behaves as if:
1. It takes much longer to compile shaders compared to other games.
2. It re-compiles the shaders again when rebooting.

Curiously this does NOT happen in _Dead Rising 2_, only _Dead Rising 2: Off the Record_. Even though it's 95% the same game. Same areas, same graphics, same models, same textures, etc. Which makes me think they did something unique to the rendering pipeline in DR2:OTR, which carried over to Resident Evil 6. The games can be considered unplayable to many.

**Comment by K0bin** [comment]
@Yasand123 What's your DXVK version, hardware and driver version?

**Comment by Yasand123** [comment]
Current set-up: 
- DXVK v2.3-7-g494f7fd38df9b0e
- NVIDIA GeForce RTX 2060 SUPER
- Driver: NVIDIA
- Version: 580.95.05
- AMD Ryzen 3700x

Notes:
- Proton/DXVK versions don't seem to matter, at least the versions I tried, starting from Proton v8.16 upto Proton v10.20.
- Same goes for the Nvidia driver (1 year worth of updates)
- Using `PROTON_USE_WINED3D=1 %command%` improves the situation a lot, but comes with its own issues, but they're not related to shaders.

**Comment by K0bin** [comment]
I just tried it and it ran pretty smoothly. Can you make a video?
