### ISSUE TITLE
God Of War 3 isn't being launched

### ISSUE THREAD

**Issue by Kashio** [doitsujin/dxvk#2596]
### Software information
God Of War

### System information
- GPU: GTX 960M 
- Driver: 512.15
- Wine version: Windows 10 64bi so no wine
- DXVK version: 1.10.1

Full spec is lenovo y700 spec's

### Apitrace file(s)
[GoW_api_trace.zip](https://github.com/doitsujin/dxvk/files/8456636/GoW_api_trace.zip)

### Log files
- d3d11.log: No data was written to log file
- dxgi.log: 
[GoW_dxgi.log](https://github.com/doitsujin/dxvk/files/8456637/GoW_dxgi.log)

Just as written in the title, I just copied relevant dlls to GOW folder, tried to launched via steam/directly and nothing is being launches, although a process of GOW is being created but I just remain on the desktop

**Comment by doitsujin** [comment]
God of War 3 isn't on PC.

I assume you mean the 2018 God of War, which works fine with DXVK on supported platforms. Windows [isn't one of them](https://github.com/doitsujin/dxvk/wiki/Driver-support#windows).
