### ISSUE TITLE
Gamma slider not working in Witcher 3

### ISSUE THREAD

**Issue by ekianjo** [doitsujin/dxvk#260]
### Software information
Witcher 3, GOG version, 1.31, high settings

### System information
- GPU: nVidia 970 GTX
- Driver: 390.x
- Wine version: 3.5
- DXVK version: 0.41

The game works pretty much perfectly apart from this little detail: the Gamma slider has no effect whatsoever in the options.

**Comment by doitsujin** [comment]
Pretty sure that this is a farly common issue with the DXGI code. No fix planned for this particular issue so far, but I'll leave this open nonetheless.

**Comment by doitsujin** [comment]
Fixed in dd3f4c89ac31aa983c1297ab23da1f6cb12ea82b.

**Comment by Evernow** [comment]
> Fixed in [dd3f4c8](https://github.com/doitsujin/dxvk/commit/dd3f4c89ac31aa983c1297ab23da1f6cb12ea82b).

I don't believe this is fixed unfortunately, the gamma slider does not work with Proton 5.0-4

**Comment by jp7677** [comment]
@Evernow newer Proton versions use Wine's dgi.dll, but this fix was made in DXVK's dxgi.dll. Try using DXVK's dxgi.dll by specifying `WINEDLLOVERRIDES=dxgi=n` in the game's launch options.

**Comment by Evernow** [comment]
@jp7677 Just saw this, yep that fixed it thanks
