### ISSUE TITLE
game pixels look bad. "SetRenderState: Unhandled render state"

### ISSUE THREAD

**Issue by lordsas** [doitsujin/dxvk#2601]
I try Metin2 play.
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_LASTPIXEL
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_MULTISAMPLEANTIALIAS
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state D3DRS_DITHERENABLE
and not work function.

and the state of the game:

Directx9 Game
[Image](https://i.hizliresim.com/moy4ra2.jpg)
CPU: %1
GPU: %5

DXVK Vulkan Game
[Image](https://i.hizliresim.com/83ayshs.jpg)
CPU: %5
GPU: %47

**Comment by Blisto91** [comment]
What do you mean by look bad. You mean the sharpening effect or what is it is in the dxvk picture?

Also which version of dxvk, your system specs wine/windows version?

**Comment by K0bin** [comment]
Those log lines are pretty useless.

I need an apitrace, full logs and information about your system.

**Comment by Blisto91** [comment]
Does this game even use dx9 on it's own? I can only get dxvk to attatch to the little anti cheat thing that pops up before it starts. The game itself runs through WINED3D. I think it might be dx8? Unsure

**Comment by Joshua-Ashton** [comment]
These images look identical

**Comment by lordsas** [comment]
@Blisto91 Windows10 and AMD graphic card r590 nitro+

Yes Game is Directx9.

and I install WINED3D  OpenGL;
CPU: %8
GPU: %41
[Image](https://i.hizliresim.com/ehoglnk.jpg)

just, vulkan(dxvk) have graphic problem.

but cpu and gpu problem is present in all of them. (WINED3D and DXVK)

**Comment by K0bin** [comment]
Still need the apitrace.

**Comment by Blisto91** [comment]
I can't find that the game have built in support for dx9 (i'm using the steam version). But i can see a wrapper to translate dx8 to dx9 have a thread on the forum and if i use that i can get dxvk working. 
But i cannot reproduce a difference in the images with or without dxvk either on Windows or Linux. Even when i set the resolution to 16 bit.

<details>
  <summary>With dx9 wrapper + dxvk</summary>
  
![withdxvk](https://user-images.githubusercontent.com/47954800/163056833-5cba9622-9c45-46d3-b53b-6f44f63bfbd6.PNG)
![dx](https://user-images.githubusercontent.com/47954800/163056852-8bd81c13-3af0-487f-9467-fdc7c0bd0039.PNG)
</details>

<details>
  <summary>With dx9 wrapper</summary>
  
![withoutdxvk](https://user-images.githubusercontent.com/47954800/163056866-966c038e-21d4-4897-9b5c-3747184c5c9a.PNG)
![dxu](https://user-images.githubusercontent.com/47954800/163056891-cd92edfb-b77a-4bed-892a-221ba8f72152.PNG)
</details>

**Comment by Blisto91** [comment]
@lordsas Friendly ping
