### ISSUE TITLE
DXVK 1.10, D3D9, no log file created, but DXVK seems to work (HUD is enabled) 

### ISSUE THREAD

**Issue by MalonnBethesda** [doitsujin/dxvk#2602]
I just updated my prefix (created from scratch, not overwritten) to Wine 7.6 Staging and DXVK is not generating a log file.  I'm running it through Lutris on a D3D9 game.  The HUD works, however, which I have to assume means DXVK is working?  But, is it 100%?  Wine is a custom build (wine-tkg-git).  Anyone have any ideas?

I'd post the log file, but I don't have one :smiley:

EDIT:
Here's the Wine log:
```
Start monitoring process.
gamemodeauto: 
002c:fixme:winediag:LdrInitializeThunk Wine TkG (staging) 7.6 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
0110:fixme:ver:GetCurrentPackageId (00FCF2FC 00000000): stub
010c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0070:fixme:imm:ImeSetActiveContext (0x59910, 0): stub
0070:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000059910): stub
010c:fixme:imm:ImeSetActiveContext (0x1067638, 1): stub
010c:fixme:imm:ImmReleaseContext (00040056, 01067638): stub
Initial process has exited (return code: 0)
010c:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x230 for device 0.
010c:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
wine: Unhandled page fault on read access to EA191C30 at address EA191C30 (thread 010c), starting debugger...
018c:fixme:imm:ImeSetActiveContext (0x495f0, 1): stub
018c:fixme:imm:ImmReleaseContext (0000000000020074, 00000000000495F0): stub
wine client error:174: write: Bad file descriptor
wine client error:170: write: Bad file descriptor
Monitored process exited.
Exit with return code 0
```

EDIT2:
Odd!  I just launched the game for the 6 or 7 time and it created a log.  I'm clueless.

**Comment by Blisto91** [comment]
If the hud shows then dxvk should be working fine.

If nothing else is specified then dxvk itself default sets the log [level to info.](https://github.com/doitsujin/dxvk/blob/cd8a2bcfcd9670dc8211ac82565080d0f62feb5e/src/util/log/log.cpp#L90) Which should create a basic log file
In proton it is set to none per default unless you have [PROTON_LOG enabled](https://github.com/ValveSoftware/Proton/blob/0623da2af422e34101787cb772bbefece6a9885b/proton#L1053)
Lutris, if i understand the code correctly, defaults to [not show debug information](https://github.com/lutris/lutris/blob/58baae92a9915e2f0037b794ab92d1413b6ca641/lutris/runners/wine.py#L446) which also [disables dxvk logging.](https://github.com/lutris/lutris/blob/58baae92a9915e2f0037b794ab92d1413b6ca641/lutris/runners/wine.py#L851)

Maybe you messed with debug information in lutris or ran your game from outside lutris the time it showed up?
Hope this helps.

**Comment by MalonnBethesda** [comment]
Good thoughts; appreciate the input, but I don't think so.  I have changed nothing in Lutris from when the log was created (older versions of Wine) to now, when it's hit or miss (mostly miss) that a log gets created.  Also, I always launch via Lutris.

But, you said DXVK should be working fine, so that takes care of my concern.  I just thought not generating a log implies DXVK is not working right.  I mean the docs say to verify DXVK is working by looking for the log.  They also say to look for the HUD.  So... whatever.

**Comment by Blisto91** [comment]
What was the content of the log?
Just the regular info lines?

**Comment by Blisto91** [comment]
I have tried launching a old dx9 game i installed in my wine prefix through lutris around 10 times and it did not create a log file. As i would expect.
I then in lutris went the games configurations and under Runner options set Output debugging info to enabled. It now made a log. Also as i would expect. :)

**Comment by Blisto91** [comment]
Was this issue solved? 👀

**Comment by K0bin** [comment]
What's the problem here in the first place?

**Comment by MalonnBethesda** [comment]
Well, I've been away from the particular D3D9 game I posted about, but launched it today after seeing these posts (sorry for not responding earlier), and it created a log.  It's been over a month and I don't remember if debugging was enabled or disabled in Lutris last time I tried.  I tend to keep it enabled, but I don't remember.  Maybe I was troubleshooting something and it was disabled (wouldn't think so because you want logging for troubleshooting).  So, I don't know.

**Comment by Blisto91** [comment]
Roger.
If you run in to trouble again or have any questions don't be afraid to make a new issue 🙂

**Comment by MalonnBethesda** [comment]
Will do.  Thanks for your help, @Blisto91

**Comment by Blisto91** [comment]
@K0bin Can be closed.

**Comment by MalonnBethesda** [comment]
Oops, my bad.  Brain fart.
