### ISSUE TITLE
Payday 2: Steam Overlay causes windows cursor to appear

### ISSUE THREAD

**Issue by MatthewCAbel** [doitsujin/dxvk#2603]
### Software information
Payday 2 latest version, settings seem to be irrelevant to issue

### System information
- GPU: Nvidia GTX 1660
- Driver: 512.15
- Wine version: 
- DXVK version: 1.10.1

### Apitrace file(s)
- https://www.dropbox.com/s/tue797hel6remmg/payday2_win32_release.7z?dl=0

### Log files
- d3d9.log: [payday2_win32_release_d3d9.log](https://github.com/doitsujin/dxvk/files/8467774/payday2_win32_release_d3d9.log)
- d3d11.log:
- dxgi.log:

**Comment by Blisto91** [comment]
Sorry for the delay in answering here. The devs are not sure what can be done here. See the previous same issue for tracking it. https://github.com/doitsujin/dxvk/issues/2581

@K0bin This one can maybe be closed as a duplicate.
