### ISSUE TITLE
The shadows in alien rage are broken

### ISSUE THREAD

**Issue by barfin** [doitsujin/dxvk#2613]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/doitsujin/dxvk/wiki/Making-a-Trace.
Preferably record the trace on Windows, or wined3d if possible.

**Reports with no log files will be ignored.**

### Software information
[Alien Rage - Unlimited](https://store.steampowered.com/app/217920/Alien_Rage__Unlimited/)

### System information
- GPU: GTX 970
- Driver: 510.60.02
- Wine version: 7.6 Staging
- DXVK version: dxvk-mingw-git 1.10.1.r13.g3672375b-1

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:[ShippingPC-AFEARGame_d3d9.log](https://github.com/doitsujin/dxvk/files/8497528/ShippingPC-AFEARGame_d3d9.log)
- d3d11.log:
- dxgi.log:[ShippingPC-AFEARGame_dxgi.log](https://github.com/doitsujin/dxvk/files/8497529/ShippingPC-AFEARGame_dxgi.log)
- wine log: [alienrage.txt](https://github.com/doitsujin/dxvk/files/8497576/alienrage.txt)

![image](https://user-images.githubusercontent.com/37030489/163620837-36269780-5d5d-42b6-887f-e8682003ba4b.png)

**Comment by K0bin** [comment]
Please add an apitrace so we can look into this.

**Comment by barfin** [comment]
> Please add an apitrace so we can look into this.

I tried and i can't, the final size is way too big for my internet speed to upload however there is a free demo for this game in steam with very low download size, you can see for yourself

**Comment by Blisto91** [comment]
Cannot reproduce in the demo on R9 380 mesa git. (proton)
Will try on Nvidia setup when i have time.

Does it appear with all ingame settings?

**Comment by barfin** [comment]
> Cannot reproduce in the demo on R9 380 mesa git. (proton) Will try on Nvidia setup when i have time.
> 
> Does it appear with all ingame settings?

yes i tried high and low shadow settings
it didn't change a thing

**Comment by Alejandro9509** [comment]
yes, i can reproduce it.. , its a NVIDIA related issue i think 
![Captura desde 2022-04-15 13-49-52](https://user-images.githubusercontent.com/103089262/163630747-83bb9d9c-d4a4-4fe5-9491-bc0ef9c0d27a.png)

**Comment by Alejandro9509** [comment]
> Please add an apitrace so we can look into this.

its ok ? 

https://drive.google.com/file/d/1L2X0oZOvL-uZWU6VJnDp-XUzYu1fF0LY/view?usp=sharing

**Comment by springwurm** [comment]
Hi, i have the same Issue, but without dxvk too.

I'm not sure if that has anything to do with the Shadow Settings at all.
Changing from High to Medium in the Postprocess Quality Settings removes the Lines.

### System information
- GPU: AMD Radeon RX 570
- Driver: 2.0.213
- OS: Windows 10
- DXVK version: 1.10.1

### Apitrace file(s):
- ![ShippingPC-AFEARGame.trace](https://mega.nz/file/DM9U3DpA#1gC1DPGo3KaeQAlv2hlmR2K_EATzwH3CXcTSgCIfNLs), the trace includes the switch between Postprocess Quality from High to Medium

### Screenshots:
#### Postprocess Quality: High
![Alien Rage - Unlimited_2022 04 19-15 10_dxvk](https://user-images.githubusercontent.com/65482005/164161695-b745f73a-191e-427c-bc24-9b6b1f235963.png)
![Alien Rage - Unlimited_2022 04 19-15 12_no_dxvk](https://user-images.githubusercontent.com/65482005/164161705-62e9a1a7-28c1-4cf2-b667-460cedd4ead9.png)
#### Postprocess Quality: Medium
![Alien Rage - Unlimited_2022 04 20-08 21_dxvk_postprocess_quality_medium](https://user-images.githubusercontent.com/65482005/164164007-63761e43-0d34-4430-8d27-460ceb137549.png)
![Alien Rage - Unlimited_2022 04 20-08 17_no_dxvk_postprocess_quality_medium](https://user-images.githubusercontent.com/65482005/164163999-98ff0f63-8905-4d37-a7c6-8fd62a0c8bfa.png)

### Screen Recordings:
- ![Alien Rage - Unlimited_2022.04.19-14.55_no_dxvk.mp4](https://mega.nz/file/TQl12JAL#xjiOFIJVAnpWG4BcLsa3dUylm9qa38Ja4l7b9tCXVYQ)
- ![Alien Rage - Unlimited_2022.04.19-15.01_dxvk.mp4](https://mega.nz/file/uEklUbiQ#HMTm4t22uuA4QFoPS_TGueEHPEreQypWHBsv3y73zdM)

**Comment by Blisto91** [comment]
You mean you see them on native d3d9 on windows with amd? 👀

**Comment by springwurm** [comment]
> You mean you see them on native d3d9 on windows with amd? eyes

Yes

**Comment by Blisto91** [comment]
Roger.

Will check on my setup on windows and also double check on linux messing with post processing when i get home.

**Comment by Blisto91** [comment]
So i finally got home several months later :grin: (sorry about the wait)
I tried testing the demo on windows with my R9 380 both with and without dxvk. But i wasn't able to reproduce even after messing with the settings.

Haven't tried on the nvidia.

**Comment by Blisto91** [comment]
Wasn't able on the nvidia setup too and also have the full game to try now.
The only way i was able to reproduce this was (tested on the amd setup now) was to do a reverse of this https://steamcommunity.com/app/217920/discussions/0/451850849191942988/?ctp=4#c351659808478195889

My `FloatingPointRenderTargets` was already set to true. Setting it to false produced the issue.
Didn't find any dxvk config that worked around the issue when it was set to false

**Comment by Blisto91** [comment]
Pr above should fix this. Read it's description for more info.
