### ISSUE TITLE
LEGO Star Wars: The Skywalker Saga graphical glitches

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#2614]
In the Episode IV: A New Hope, story mission Hunk of Junk, in the hangar when i turn my camera in certain directions graphical glitches appear on screen.
This does not appear on native windows 10.
WINED3D have it's own host of huge graphical glitches and i can hardly see the main menu with it, so didn't try to load the save game with it.

<details>
  <summary>dxvk glitches</summary>
  
![Screenshot_20220417_140239](https://user-images.githubusercontent.com/47954800/163715141-9fe153d1-1fbb-494f-a77c-116212cd55e6.png)
![Screenshot_20220417_140124](https://user-images.githubusercontent.com/47954800/163715149-7bcaa5d3-fd9b-4a50-b2e7-3c448342512d.png)
</details>

### Software information
LEGO Star Wars: The Skywalker Saga.
Tried on high and low settings

### System information
- GPU: R9 380
- Driver: Mesa 22.0.1 / pretty new mesa-git
- Wine version: proton 7.0-2rc
- DXVK version: 1.10.1 / master

### Apitrace file(s)
Working on this. On windows the main menu buttons never show up with the apitrace active so can't get into the save game.

Edit: I made a trace on linux by dumping the trace files into the games folder and launching through steam as normal. Hope it'll do else i'll try to get it working on windows without dxvk.
https://mega.nz/file/B5ZRnIaa#FubV9LMqEr7aID99wrAGCqlWN2bZekAvvJSXSiaoX-E

### Log files
Made with trace log level
[LEGOSTARWARSSKYWALKERSAGA_DX11_d3d11.log](https://github.com/doitsujin/dxvk/files/8501612/LEGOSTARWARSSKYWALKERSAGA_DX11_d3d11.log)
[LEGOSTARWARSSKYWALKERSAGA_DX11_dxgi.log](https://github.com/doitsujin/dxvk/files/8501614/LEGOSTARWARSSKYWALKERSAGA_DX11_dxgi.log)

**Comment by Oschowa** [comment]
The trace replay looks fine here on a 6700XT, can you reproduce the glitches when replaying the trace on your end? If yes then this is very likely a driver and not a dxvk issue. You can try if RADV_DEBUG=nohiz fixes it and should open an issue on the [mesa gitlab](https://gitlab.freedesktop.org/mesa/mesa/-/issues) instead.

**Comment by Blisto91** [comment]
@Oschowa Hi.
I have never tried to view a trace before now and i'm having trouble with it xd. I tried to install `apitrace` through pacman and run  `qapitrace LEGOSTARWARSSKYWALKERSAGA_DX11.trace`. But when i try to replay or enable thumbnails or anything it crashes. I'm probably missing something obvious. :)

I can still reproduce it with `RADV_DEBUG=nohiz`

**Comment by doitsujin** [comment]
You'll need to replay it with the Windows version of apitrace (`wine d3dretrace.exe frog.trace`).

**Comment by Blisto91** [comment]
Thanks got it working.

Ye i see it in the replay. I will make a mesa issue.

**Comment by Blisto91** [comment]
I haven't gotten to this point yet on the steam deck but i'm gonna close this as it pretty much seems like a driver issue with the tonga gpu's

**Comment by K0bin** [comment]
I played through the game on the Steam Deck and didnt notice anything.
