### ISSUE TITLE
Tekken 7 - full system lockup (FIX) sortof.

### ISSUE THREAD

**Issue by Zuiron** [doitsujin/dxvk#262]
So yesterday or whatever i posted an issue where with DXVK tekken 7 full system lockup. was told it was driver issue. but i tried mesa-git and latest llvm and all sorts of nonsense always same result. full system lockup.

 ive found a fix. sortof. the thing is. i changed the graphics config for tekken so now atleast it boots! but theres a problem. colors are weird and ingame characters are invisible. you see only hair.

RADV_DEBUG nohiz - makes it so characters are visible, without it you ONLY see hair.

picture1 menu: https://i.imgur.com/W8ZBiRG.png
picture2 ingame: https://i.imgur.com/5CQnEaZ.png

below is config or lines you need to add in order to get tekken to boot.

### Software information
Tekken 7 -> edit Engine.ini to below.
ADD to bottom of file:
[/script/engine.renderersettings] 
r.defaultFeature.MotionBlur=False
r.MotionBlurQuality=0

Thanks @Kliesen for figuring out exactly what setting causes full system crash.

### System information
- GPU: Vega 64
- Driver: 18.0.0
- Wine version: Staging 3.5
- DXVK version: DXVK-bin

**Comment by doitsujin** [comment]
I don't have the game so I cannot test this, and I don't know what the default settings are and what they do, but as for the `nohiz` issue, please report that bug to [Mesa](https://bugs.freedesktop.org/).

**Comment by Zuiron** [comment]
will do later today when i have time.

**Comment by TiZ-EX1** [comment]
Oh hay, another person trying to play T7. I'm willing to pony up $25 to help @doitsujin get and test the game if you are too. Is that something you'd want, @doitsujin?

**Comment by Zuiron** [comment]
T7 is cheap on g2a. i bought it there for a friend.

**Comment by TiZ-EX1** [comment]
Key reseller? I mean, if that's something he would be comfortable going in on but it seems like he's not particularly interested in having this game for himself. So I'm asking if you want to go halfsies on getting it for him.

**Comment by Kliesen** [comment]
https://prnt.sc/j327om Zuiron's workaround works on my system without "nohiz". testing what parameter in Engine.ini fixes the issues is a good idea imo.

**Comment by Zuiron** [comment]
might tweak the settings even more to get better graphics. might be the settings thats causing it but havent played with it yet.

**Comment by Kliesen** [comment]
it seem's that r.MotionBlurQuality=0 fixes the GPU hang startup.

**Comment by Zuiron** [comment]
good to know. however removing all the other settings change the graphics?

**Comment by hakzsam** [comment]
I can confirm the GPU hang with latest mesa/llvm on vega56. it's similar to Hellblade. I have a local change that "fixes" it but it's not yet ready.

**Comment by Kliesen** [comment]
Samuel's patch fixes the hang and now motion blur works in-game.
