### ISSUE TITLE
Need for Speed SHIFT 2 Unleashed graphical artefacts

### ISSUE THREAD

**Issue by Jacques4v7W** [doitsujin/dxvk#2621]
Hi,

I just want to start of by saying thank you for the awesome job you guys are doing with DXVK, it has definitely improved over the years and especially helps in DX9 games where AMD lost optimizations for DX9 Unreal Engine 3 games after the removal of "Radeon Additional Settings" in 17.7.2 without a care of even finding someone who owns the game to test for the bug we have been reporting since 2017, even though they told me they were apparently working on a fix in 2018.

Back to the top of NFSP Shift 2 Unleased:

### Software information
Need for Speed Shift 2 Unleashed, Highest settings, 3840x2160p, also using AMD Virtual Super Resolution.
So the game seems to be working 90% correctly, the only problem with using DXVK with it are these purple squared artefacts that pop up randomly across the screen, and they multiply as the race progresses. At first I assumed it was related to dirt splatting on the windscreen of the car, but when I zoomed out to exterior view the squares were still present.
But from what I remember, DXVK improved the CPU overhead in the game by quite some margin, so it would be great to be able to use DXVK properly with it.

### System information
- GPU: MSI Radeon RX 480 8G Gaming X
- Driver: 22.4.1
- Wine version: Testing on latest version of Windows 10, unfortunately I could not get Linux to work properly with my NTFS formats.
- DXVK version: 1.10.1 (latest version, but was present as long as I can remember).

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
[shift2u_d3d9.log](https://github.com/doitsujin/dxvk/files/8522281/shift2u_d3d9.log)

**Comment by K0bin** [comment]
Please upload an apitrace and also some screenshots or a video so we know what you're talking about.

**Comment by Jacques4v7W** [comment]
> Please upload an apitrace and also some screenshots or a video so we know what you're talking about.

Hi @K0bin , thank you for your response. I can upload an image for you so long and will try apitrace later when I can do some further reading on its' usage.

I think I might have found the culprit to the issue, when I was looking at the font in the game menu, I noticed it had this strange smoothness to it and then I remember reading a few years in the past that NFS Shift2 uses Morphological Anti-Aliasing for both presets. Furthermore, it also got me thinking now that I pretend myself reading in the past that MLAA is only supported in DirectX11; therefore, I disabled Anti-Aliasing in the game and I only had time to test one lap now, but I did not notice any artefacts popping up during that lap.

Here is the screenshot:
![NFSP_SHIFT_2_purple_rectangular_artefacts](https://user-images.githubusercontent.com/5221051/164339017-622dfb64-be9e-45f5-ae0b-37064e9bfff6.png)

Kind regards
HitBM47

**Comment by K0bin** [comment]
I think MLAA can be implemented with D3D9.

If the game allows you to enable it with D3D9, then it should probably work unless it's also broken without DXVK.

**Comment by Jacques4v7W** [comment]
> I think MLAA can be implemented with D3D9.
> 
> If the game allows you to enable it with D3D9, then it should probably work unless it's also broken without DXVK.

Hi @K0bin ,

The anti-aliasing option works with the native D3D9 implementation of the game, but it causes the purple artefacts when enabling the AA with DXVK. I guess it is not major issue for me, since I can use 3840x2160 VSR on 1080p and the normal preset AA just gave it that extra perfect smoothness. In contrast, I think it is a problem when someone relies on the in-game AA (which is MLAA in this case) to smooth their native resolution out for them.

DXVK seems like it is benefiting CPU performance by quite some margin in this game on top of disabling "Origin in-game overlay" (which also causes major performance drops in this game), since this game is heavy singlethread-/API- bound.

Kind regards

**Comment by K0bin** [comment]
That's all great but without the apitrace I cannot look into this.

**Comment by Jacques4v7W** [comment]
> That's all great but without the apitrace I cannot look into this.

Ok so I was able to create an apitrace through command-line a few minutes after understanding how the basic parameters, etc works, I just want to make sure if did it in a way that would be useful to you and since it is a massive 1.75GB file to upload.

I removed the Vulkan wrappers from DXVK and replaced them with the 32bit wrappers from apitrace, otherwise the utility would not be able to track the D3D9 calls made from the game.

Just to check that it was working I ran "apitrace dump shift2u.trace" and after 4minutes I Ctrl+C'ed it when it was already at 80k lines of shaders and code.

Will this be fine for you?, since I did try closing Shift2 as quickly as possible after doing 1/4 of a lap. I might only be able to upload later, since it will hogg our Internet.

**Comment by K0bin** [comment]
Huge files are perfectly normal. I suggest compressing them because that usually halves the size. It's also correct that you made it without DXVK, I will be able to replay it **with** DXVK and hopefully see the bug. I also don't need you to play the game for very long, just long enough so the bug *would* show up if you were using DXVK.

**Comment by K0bin** [comment]
![image](https://user-images.githubusercontent.com/1131720/170784321-5dc46854-74f8-46fd-bc7f-8e9f9449dbaf.png)

Looks fine here.

**Comment by Jacques4v7W** [comment]
Hi @K0bin , excuse me for only replying after such a long time.

I see you did the test on a Nvidia RTX 3090, whereas I did the test on my Radeon RX 480. Therefore, that is unfortunately already a mismatch in drivers.

Furthermore, did you test on Linux or Windows? I tested on Windows 10.

Kind regards

**Comment by K0bin** [comment]
> Furthermore, did you test on Linux or Windows? I tested on Windows 10.

I tested it on Linux but the Nvidia driver is pretty much identical on Windows and Linux so it'll look exactly the same on Windows.

> I see you did the test on a Nvidia RTX 3090, whereas I did the test on my Radeon RX 480. Therefore, that is unfortunately already a mismatch in drivers.

Exactly. It's most likely a driver bug.

**Comment by K0bin** [comment]
We don't support Windows and I don't have any AMD hardware to test it on. Driver bugs with AMDs Windows driver have unfortunately been somewhat common.

**Comment by Jacques4v7W** [comment]
@K0bin I see, I remember reading in one of the DXVK guides that it is sometimes beneficial/recommended to do the apitrace tests or some of the tests on Windows. I guess that DXVK guide was outdated then.

I would have liked to move over to Linux, but the last time I tried a few months ago, it seemed as if the NTFS formats I have my HDD drives in caused Doom (2016) to stop loading assets for starting a level. Otherwise, I would try using DXVK in WINE on Linux, but at the moment it is not feasible to move over to Linux.

**Comment by Jacques4v7W** [comment]
Hi @K0bin , so just to clarify, we should no longer report bugs then if we are on a Windows distribution? Since the D3D9 frontend in DXVK is advanced enough now.

Thank you for your help anyway Kobin. Furthermore, yes this issue which I was experiencing with Doom was specifically on PopOS with the downloadable Steam and recommended Proton for Doom, but my drives is and was formatted to NTFS, since I have very large files on my secondary HDD's, which I cannot simply re-download when considering to make the move to Linux.
I would've liked to move to Linux otherwise, since I have done C++ programming on it before.

Ok, I see, so the artefacts are specifically related to AMD's Windows Vulkan driver and I actually thought they were on their game with at least their implementation of the Vulkan API. I recently also discovered that they only re-included previously lost Unreal Engine 3 (DirectX9) optimizations for Navi RX 6000 GPUs when most of us reported the issue on Polaris and Vega for years. One can notice this when using the NimeZ modded drivers with the Navi Kernel.

**Comment by K0bin** [comment]
> we should no longer report bugs then if we are on a Windows distribution? Since the D3D9 frontend in DXVK is advanced enough now.

No, please do keep opening bug reports if you run into bugs, even if you use Windows. DXVK is far from perfect.
It doesn't matter as much which OS you use to create the apitrace. One made on Linux with DXVK is usually fine as well.
