### ISSUE TITLE
Update "Making a Trace" wiki windows section

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#2622]
I couldn't find that github allowed a easy way to make a PR for a wiki (sigh) so i'll make an issue instead. Hope that is alright.

The Windows sections for how to make a trace seems to be copied straight from the Linux section.
I think it should be updated and remove (or correct to windows equivalent) Linux specific stuff like desktop path and maybe add another  compression format example (maybe) more relevant to windows.
Might clear up some confusions for a few people and might make 1 or 2 more post one that otherwise wouldn't at the start.

**Comment by K0bin** [comment]
Feel free to send an improved version. ;)

**Comment by Blisto91** [comment]
Ah yes. The ease and convenience of GitHub :grin:

Here you go.
https://github.com/Blisto91/dxvk-wiki
I've just removed the wine desktop path and assumed the windows user know where their desktop is hehe.

**Comment by Blisto91** [comment]
Btw does the guide also work for dx10 games even tho it doesn't mention `d3d10.dll` ? 

Also do you think it would make sense to add a extra bullet at the end of the linux instructions saying they can remove the apitrace dll's and revert winecfg when done?

**Comment by K0bin** [comment]
Thanks, I incorporated your changes.

> Btw does the guide also work for dx10 games even tho it doesn't mention d3d10.dll ?

d3d10.dll calls into d3d10core.dll

> Also do you think it would make sense to add a extra bullet at the end of the linux instructions saying they can remove the apitrace dll's and revert winecfg when done?

I added a brief sentence.
