### ISSUE TITLE
Mafia The City Lost Heaven low FPS

### ISSUE THREAD

**Issue by Dantec116** [doitsujin/dxvk#2625]
Hi! I'm using the Widescreen Fix for Mafia The City Lost Heaven. To fix the flickering shadows, I use DX VK. But FPS starts to fluctuate around 57-61. Because of this, the image twitches, it is uncomfortable to play. What to do?

**Comment by Blisto91** [comment]
See if enabling Vertical synchronization and Triple buffering in the games settings help.

**Comment by K0bin** [comment]
If you want us to take a look at it, we need logs, info about your system and most importantly an apitrace.

**Comment by Blisto91** [comment]
See https://github.com/doitsujin/dxvk/wiki/Making-a-Trace for how to make a apitrace. Ask if you are in doubt.

For the logs they should generate next to the games exe when using dxvk directly or on windows. If you are using proton or lutris you have to enable logging trough there or launch with `DXVK_LOG_LEVEL=info`

**Comment by Dantec116** [comment]
Как прописать vsync чтобы он был включен в DXVK.config?

**Comment by Blisto91** [comment]
You can try if these help
```
d3d9.syncInterval = 1
d3d9.numBackBuffers = 3
```

**Comment by Dantec116** [comment]
The frame rate issue has been resolved. Installed Widescreen fix, renamed d3d8.dll from it to dinput8.dll. Connected enb converter for Mafia. And I installed the Riva Tuner program, set the screen refresh rate to 60 fps in it. As a result, the game began to hold frames stably, the shadows do not flicker. So everything turned out okay.
