### ISSUE TITLE
d3d9.forceSwapchainMSAA = 16 Causes "could not initalize renderer" error

### ISSUE THREAD

**Issue by LethalManBoob** [doitsujin/dxvk#2627]
https://gist.github.com/LethalManBoob/b91334617d753f8a2f1e21a3227427f0
2 different games same issue. Although in killing floors case, it just hangs at a black screen on boot.
It used to work on both games. Not anymore.

**Comment by DadSchoorse** [comment]
Nobody except Intel supports MSAA x16, try x8.

**Comment by doitsujin** [comment]
As was mentioned, most GPUs can't do MSAAx16 and a 3070 is no exception.

**Comment by LethalManBoob** [comment]
> As was mentioned, most GPUs can't do MSAAx16 and a 3070 is no exception.

Thats strange. It worked fine on windows. I suppose this is a linux thing huh? 

But it USED TO WORK. Thats the main complain I have. On linux, 16x used to work.

**Comment by DadSchoorse** [comment]
Even if it used to work (which I doubt, nvidia never supported x16 afaik), this isn't about DXVK. DXVK just exposes the MSAA levels supported by the vulkan driver, and your driver only supports a maximum of x8.

**Comment by LethalManBoob** [comment]
> Even if it used to work (which I doubt, nvidia never supported x16 afaik), this isn't about DXVK. DXVK just exposes the MSAA levels supported by the vulkan driver, and your driver only supports a maximum of x8.

I dont see a reason to doubt me. I know i used it before. Distincltly lutris had an antialiasing option in the past. and I could utalize 16x through there. Also 16x is avaliable in the nvidia driver and i can use it in opengl games np.

**Comment by LethalManBoob** [comment]
> There's nothing to address here. Nvidia does not support 16x MSAA on current drivers, period. Neither does AMD and never has. If this has "worked in the past" then I strongly suspect that the option just didn't get applied on your end.
So then why does 16xmsaa work on opengl games? Demonstrably?

**Comment by doitsujin** [comment]
OpenGL isn't Vulkan for starters.

**Comment by LethalManBoob** [comment]
> OpenGL isn't Vulkan for starters.
> 
> We could emulate 16xMSAA for D3D9, but there are no plans to do so since it's kind of pointless and no shipping game requires that. D3D11 only requires x4 anyway with x2 and x8 being optional.

dgvoodoo uses 16xmsaa and it does help in some old games that dont like high resolutions.

I understand it may seem pointless but a lot of people would appreciate the additional anti aliasing. I was around the guru 3d forums a few years ago researchings sgssaa flags. The difference is huge when you have go above the traditional 8x.

Im talking about alpha and inner surface aliasing. Some games really benefit from the fix.

As an example. The the id tech 5 games, 16x msaa is a HUGE step up from 8x due to inner surface aliasing.

[https://youtu.be/NbrA4Nxd8Vo?t=269] This is what i am talking about
