### ISSUE TITLE
Kingdom Hearts 3 lighting, reflection, particle effects issues

### ISSUE THREAD

**Issue by KingYozora** [doitsujin/dxvk#2630]
The game has lighting/texture? issues and reflection issues (green tinge on skin, blood eyes, red light reflection on water, etc.).  Also particles issues on some enemy attacks (black box around some of the effects).  SEE SCREENSHOTS BELOW.

### Software information
Kingdom Hearts 3 Remind - Epic Game Store

### System information
- GPU: Intel Xe i5 1135G7
- Driver: 30.0.101.1660
- Wine version: Windows 10
- DXVK version: 1.10.1 master & async

### Apitrace file(s)
- Put a link here

### Screenshots
- https://imgur.com/a/1VaFqBD

### Log files
[KINGDOM HEARTS III_dxgi.log](https://github.com/doitsujin/dxvk/files/8546953/KINGDOM.HEARTS.III_dxgi.log)
[KINGDOM HEARTS III_d3d11.log](https://github.com/doitsujin/dxvk/files/8546954/KINGDOM.HEARTS.III_d3d11.log)

**Comment by K0bin** [comment]
Please make an apitrace.

**Comment by doitsujin** [comment]
Please also test this on something that isn't Intel's Windows driver. There's a reason why the [wiki](https://github.com/doitsujin/dxvk/wiki/Driver-support#intel-drivers) **strongly** recommends against using it.

**Comment by Blisto91** [comment]
@KingYozora Friendly ping.

**Comment by Blisto91** [comment]
Got to check the game out myself now on AMD (Windows) and haven't spotted anything unusual while playing for a little while.

**Comment by K0bin** [comment]
Closing it due to a lack of feedback and because it worked fine on Blistos system. Feel free to reopen if you ever respond back.
