### ISSUE TITLE
Crysis Remastered crash at launch

### ISSUE THREAD

**Issue by blueclouds8666** [doitsujin/dxvk#2631]
Using Crysis Remastered with the latest DXVK binaries (1.10.1 at this time) will make it crash at launch, before the main renderer window or screen pops up. Previous versions of DXVK binaries suffer from the same (tested 1.9.2, 1.8.1, 1.7.3). This also applies to previous versions of the game (2020 and 2021 builds tested).

The game works fine, but has rendering issues on campaign with the Windows 7 default d3d11 library. this is only because the game engine uses rendering features that are not available in Windows 7 (Shader Model 5.0+, DirectX 11.2 or 11.3 maybe)

The game works and renders perfectly fine with WineD3D 7.3, albeit with a performance impact due to the OpenGL wrapping. Totally playable but only with good hardware specifications.

### Software information
Crysis Remastered, lowest ingame settings, both windowed and fullscreen tested, 1024x768, steam, latest version 2022.

### System information
- GPU: NVIDIA GTX 960 4GB
- Driver: 472.12 WHQL, default settings
- Wine version: Windows 7 SP1 with updates x64
- DXVK version: 1.10.1 release, public official binaries

### Apitrace file(s)
Launching the game with apitrace (10.0, x64) and the known working wined3d only results in "Failed creating the Direct3D device.". i'm instead providing an apitrace for the game running with Windows 7 default d3d11 library:
GitHub is not letting me upload it, so here is a mirror:
https://mega.nz/file/SKIVkSQT#sn_OMSNigFKunCS8EytZ8FxetMoo7jz0W4_hx-E7Gvw

### Log files
[CrysisRemastered_d3d11.log](https://github.com/doitsujin/dxvk/files/8565906/CrysisRemastered_d3d11.log)
[CrysisRemastered_dxgi.log](https://github.com/doitsujin/dxvk/files/8565905/CrysisRemastered_dxgi.log)

**Comment by doitsujin** [comment]
The game is known to work fine on Linux (minus accelerated raytracing since that requires Vulkan interop).

**Comment by blueclouds8666** [comment]
do you have any close idea of why is this crash happening? so i can at least try to develop a solution by myself

is it because of the dxgi detection or the renderer side?

**Comment by K0bin** [comment]
I tried Crysis Remastered with DXVK on Windows at some point after it launched and IIRC it didn't work for with the DXVK dxgi.dll for whatever reason but the WineD3D dxgi.dll worked.

**Comment by blueclouds8666** [comment]
@K0bin i don't know how i didn't give that a thought before but... it works! performance is absolutely great and i couldn't find any noticeable issues. thank you very much for your help.

here it is running at low setting (i was previously getting 20 fps with wined3d):
![crysisremastered-dxvk-win7](https://user-images.githubusercontent.com/52018385/165593894-96851266-4842-4dba-bb66-0bf8c7989961.png)

**Comment by K0bin** [comment]
I'll just close this then. Great that you managed to make it work. DXVKs dxgi.dll works with the game on Linux and we don't really support using it on Windows.
