### ISSUE TITLE
assassin's creed origin crash after splash screen

### ISSUE THREAD

**Issue by Phazdelta** [doitsujin/dxvk#2632]
Hello 

assassin's creed origin, crash after splash screen

### System information
- GPU:6900XT
- Driver:22.4.2
- Wine version: 
- DXVK version: 1.10.1 with Async

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:
- 
[ACOrigins_d3d11.log](https://github.com/doitsujin/dxvk/files/8573144/ACOrigins_d3d11.log)

**Comment by doitsujin** [comment]
Game works fine on supported platforms, please stop spamming us with useless bug reports from your broken Windows setups.

**Comment by regtoaccess** [comment]
Clear driver caches before execution. For the sh!t manufacturer, you can clear the caches from within the driver panel (graphics/advanced/reset shared cache). Cannot remember if that's also available in the nvidia driver interface. But you can manually clear the caches for both manufacturers from appdata > local directory.
