### ISSUE TITLE
Executable selection when multiple .exe are present

### ISSUE THREAD

**Issue by Cianez** [doitsujin/dxvk#2634]
I was wondering if there's a way to make DXVK only work on 1 specific executable in the same directory instead of all of them.
I've been testing it with the game XIII, it works fine, but it also translates XIIIEd.exe (map editor) to Vulkan along with XIII.exe (main game) because they're both in the same directory. This breaks the object selection in XIIIEd for some reason, it doesn't happen when there's no DXVK translation.

I was thinking of some kind of .conf command like "dxvk.executable = XIII.exe" to point out which executables I want to use DXVK with and leave the others alone.

EDIT: I'm on Windows 10 Pro 64 bit, by the way.

Thank you in advance.

**Comment by Kron4ek** [comment]
This can be done via winecfg, it allows to set different dlls overrides for different applications.

You can disable DXVK only for XIIIEd.exe. Run winecfg, on the Applications tab press "Add application" and add XIIIEd.exe, then in the Libraries tab add and override d3d11, d3d10, d3d10_1, d3d10core, d3d9, dxgi to builtin.

<details>
  <summary>Screenshots</summary>
  
![winecfg_apps](https://user-images.githubusercontent.com/13851877/165848171-e8c12e12-fad6-4676-ba2b-00b7d48f829a.png) 

![winecfg_libs](https://user-images.githubusercontent.com/13851877/165848175-f0b9ac49-f3fa-4dcd-866d-5fe7cb1b176f.png)
  
</details>

**Comment by Cianez** [comment]
> 

Ah, sorry I should've mentioned that I'm on Windows 10. Never used Linux. Can you do something like this in Windows?

**Comment by doitsujin** [comment]
No, this is not possible on Windows.
