### ISSUE TITLE
Call of Duty: Black Ops poor performance

### ISSUE THREAD

**Issue by BlueGoliath** [doitsujin/dxvk#2636]
When playing the original Call of Duty: Black Ops, the performance will be extremely poor, almost "slow-motion" like with occasional stuttering. Happens in both Singleplayer/zombies and multiplayer. Disabling both PROTON_NO_ESYNC and PROTON_NO_FSYNC doubles the framerate and reduces the issues above, but it's clearly not running how it should.

### Software information
Call of Duty: Black Ops(42700). Low or high settings, don't matter.

### System information
- GPU: NVIDIA GTX 1080
- Driver: 11.510.68.02. Happens in previous driver releases.
- Wine/DXVK version: whatever is included in Proton GE 7.16. Happens in previous Wine/DXVK versions. 
- OS: Arch.

**Comment by K0bin** [comment]
Does it run better with WineD3D? I'm not sure if this is a DXVK issue rather than a Wine one.

Please upload an apitrace so I can take a quick look.

**Comment by BlueGoliath** [comment]
Uploading but it seems to be pretty big at 1.7GB. Is that normal?

I made it via disabling DXVK in the config file and used Nvidia's FPS/rendering overlay from nvidia-settings to confirm I was running WineD3D. I then used Protontricks to override the DLLs. Seems to have worked but let me know if it isn't ideal.

**Comment by K0bin** [comment]
Yes, 2GB is a perfectly normal size for an apitrace. You can usually get it down quite a bit by compressing it as a zip/7z/tar.xz.

**Comment by BlueGoliath** [comment]
Alright, done. Should be here:

https://drive.google.com/file/d/1UjqlCEWUmGU-_whGES5H_BoDvv7QSf8k/view?usp=sharing

**Comment by BlueGoliath** [comment]
Was the Apitrace any good? Can anyone reproduce the performance issues?

**Comment by K0bin** [comment]
I haven't looked into it yet.

**Comment by K0bin** [comment]
You deleted the apitrace.

**Comment by BlueGoliath** [comment]
Still available if you aren't logged into Google. I don't have a lot of space left so if no one wants to look into it then I'll just delete it. Not complaining, just saying I don't have much space.

I'll re-upload as compressed.

**Comment by K0bin** [comment]
> Still available if you aren't logged into Google

The site says you moved it into the bin.

**Comment by BlueGoliath** [comment]
Don't know, I was able to download it again while not logged in.

Here is the compressed version:

https://drive.google.com/file/d/1LyWuBtJRXdo8NWAYLZTShCeWb6-d5rJU/view?usp=sharing

**Comment by K0bin** [comment]
The new link is not public. I can't access it.

**Comment by BlueGoliath** [comment]
Yeah forgot to change it. Fixed.

**Comment by K0bin** [comment]
That trace quits the game around 2 seconds after loading the level. And in those two seconds there's nothing obviously wrong.
I don't think I'll be able to do anything here without having access to the game and even then, chances are, the game just pushes a lot of draw calls. CoD games famously never really drop in price on Steam for some reason, so not a lot I can do for you here.

I guess you could try creating a dxvk config file (see README.md) and setting `d3d9.apitraceMode = True`.

**Comment by Blisto91** [comment]
Also, just as a sanity check, do you have a iGPU in your setup?
How is GPU utilization when you launch with `DXVK_HUD=full %command%` in steam?

**Comment by BlueGoliath** [comment]
> That trace quits the game around 2 seconds after loading the level. And in those two seconds there's nothing obviously wrong. I don't think I'll be able to do anything here without having access to the game and even then, chances are, the game just pushes a lot of draw calls. CoD games famously never really drop in price on Steam for some reason, so not a lot I can do for you here.
> 
> I guess you could try creating a dxvk config file (see README.md) and setting `d3d9.apitraceMode = True`.

Alright, spent more time in-game this time with that flag set. It's around 8 GB uncompressed so hopefully it provides better info.

**Comment by BlueGoliath** [comment]
> Also, just as a sanity check, do you have a iGPU in your setup? How is GPU utilization when you launch with `DXVK_HUD=full %command%` in steam?

Not an iGPU.

**Comment by Blisto91** [comment]
Can you post a ingame screenshot with the full hud enabled.

**Comment by K0bin** [comment]
So, does apitraceMode help or not? And make sure you remove the apitrace dll before you try.

**Comment by BlueGoliath** [comment]
![20220530095450_1](https://user-images.githubusercontent.com/10172435/171022015-3ffd0414-2531-4625-babe-ba8681becdc0.jpg)
![20220530095542_1](https://user-images.githubusercontent.com/10172435/171022023-26a32f7c-df0a-49b8-8d1c-114b92d84ccb.jpg)
![20220530101740_1](https://user-images.githubusercontent.com/10172435/171022029-ef949203-d9d1-406c-af25-26bd3f14d828.jpg)

**Comment by K0bin** [comment]
Are you sure this is better and Windows and not just a problem with the game itself.

Draw calls jump between 2000 which is pretty normal and 10,000 which is a lot for a d3d9 game.

You also never answered my question about whether `d3d9.apitraceMode = True` impacts performance.

**Comment by BlueGoliath** [comment]
It is worse on Linux. Windows does not have this performance problem.

`d3d9.apitraceMode = True` helps with performance when making a trace, yes. Still runs terribly.

**Comment by BlueGoliath** [comment]
No.

**Comment by BlueGoliath** [comment]
Don't know what to tell you. I use Gnome X11. Maybe this is only an issue with Pascal and older. 

Even on Proton GE 7.30 and the newest drivers this is still an issue for me.

**Comment by NRngnl** [comment]
> Don't know what to tell you. I use Gnome X11. Maybe this is only an issue with Pascal and older.
> 
> Even on Proton GE 7.30 and the newest drivers this is still an issue for me.

I use KDE Wayland. I don't know if there is any difference.
I played the first 2 single player mission without any problem.
Maybe as you said this is only an issue with Pascal and older.

**Comment by Blisto91** [comment]
![Screenshot_20220829_185452](https://user-images.githubusercontent.com/47954800/187254442-5fdac37c-2d55-4e70-8285-1d5aa90c242f.png)

Is it in general or specific maps or effects?
I haven't compared to windows yet. Will do that in a moment.

**Comment by Blisto91** [comment]
I haven't really played much but i tried comparing the same scene on windows with and without dxvk.

native
![native](https://user-images.githubusercontent.com/47954800/187262153-e2772a33-a76d-42c4-b100-eac66a19b457.png)

dxvk
![dxvk](https://user-images.githubusercontent.com/47954800/187262183-574fc1dc-2f4c-4ecd-a77a-acbacf346886.png)


Dxvk actually gives me a nice boost. The performance dip i get on linux seems to be wine or something else

**Comment by BlueGoliath** [comment]
Maybe it's a CPU issue? Are there any known performance issues with first gen Ryzen?

I also get performance issues in Borderlands 2 when enabling PhysX(low -> high). If Black Ops uses PhysX maybe that's to blame?

**Comment by K0bin** [comment]
> Maybe it's a CPU issue? Are there any known performance issues with first gen Ryzen?

Pretty much every performance problem with D3D9 games these days is on the CPU side of things. GPUs are orders of magnitudes faster these days than when those games were released. 

@Blisto91 Has tried that level you picked for your apitrace on Windows with DXVK and on Proton and it runs very well on Windows and terribly on Proton. That means we're likely looking at a Wine problem here.

**Comment by Blisto91** [comment]
@BlueGoliath okay you are right. There are big issues with this game on linux in some places. But it' something else besides dxvk.
Here is windows with dxvk vs proton on linux. wined3d on linux shows similar

Windows:
![dxvk](https://user-images.githubusercontent.com/47954800/187288709-3cd472c1-e71f-43d2-aa6a-eecbfef3eaa0.png)

Linux proton:
![Screenshot_20220829_213519](https://user-images.githubusercontent.com/47954800/187288738-8b553993-5e9a-4954-bc9c-77ace4097b73.png)

**Comment by Blisto91** [comment]
I dunno if the game uses physx. I tried to install newer physx into prefix as a test. But didn't do anything.

**Comment by K0bin** [comment]
I'm pretty sure it doesn't use PhysX.

**Comment by KagoraTheGrindcoreAddict** [comment]
It seems to be an issue with the CFS kernel scheduler and possibly the game's DRM as switching to a Project C kernel scheduler solves the issue entirely (PDS/BMQ).
 I haven't been able to get Bgamer working on linux to fully test the theory though. (Bgamer is an alt-client for offline/lan co-op that disables the DRM)
I have tested this and reproduced it on multiple kernel versions, GPU driver versions, and DXVK versions over the past few months.

### Sys Info
* CPU: 5950x
* GPU: 1080-ti
* Driver: 525.60.11
* OS: Artix 
* Kernel: 6.1.1 compiled using the Linux-TKG scripts (both screenshots use the exact same config options, only difference is the kernel scheduler)
* Proton: Proton-GE 7-42 (I have had the same results with more versions, 7-42 was used for the screenshots)

The 14 FPS one is CFS, the one that is CPU bound at 139 FPS was with PDS, BMQ gives the same result as PDS.
I think I tested BORE on accident and it gives the same result as CFS but don't quote me on it.
![CFS](https://user-images.githubusercontent.com/103851071/209241655-fb9c97ec-4d69-4e4a-9dd9-7c806b3189d6.jpg)
![PDS](https://user-images.githubusercontent.com/103851071/209241656-41382a86-0c83-4d7e-8fc3-99202257a399.jpg)
Ignore the round, it's a strategy testing mod I use to disable zombie spawns for consistent FPS testing

I think that's every important detail to it? If not let me know if I missed anything.
