### ISSUE TITLE
Possibly working with CEMU with Reshade on Vulkan rendering.

### ISSUE THREAD

**Issue by damazy85** [doitsujin/dxvk#2641]
Hi, i've read on reddit, that you can use this as a workaround for CEMU(Emulator) with Reshade(postprocessing app) working with Vulkan. CEMU and Reshade work with opengl, but not vulkan. How do i install it in my windows? Sorry, im a noob. I don't understand this instructions here. Is it possible with win10?

**Comment by K0bin** [comment]
DXVK implements D3D9, D3D10 and D3D11 on top of Vulkan.

CEMU doesn't use either of those. Whatever you read somewhere, you must have misunderstood it.

**Comment by damazy85** [comment]
Of course CEMU uses Vulkan, i didnt misunderstand nothing you asshole.

**Comment by ZachBacon** [comment]
And dxvk translates direct3d 9 through 11 into Vulkan. And your point is?

**Comment by K0bin** [comment]
> Of course CEMU uses Vulkan, i didnt misunderstand nothing you asshole.

CEMU does not use Direct3D9, Direct3D10 or Direct3D11, therefore it has absolutely nothing to do with DXVK. The fact that both DXVK and CEMU use Vulkan doesn't matter at all.

And immediately resorting to instulting the people you're asking for help is not gonna change that either.

**Comment by damazy85** [comment]
You insulted me first by saying i misunderstood. How do you know the information i got is not wrong? You insulted me first you prick. And then you marked it as closed. You didn't help in any manner. Also, this might have everything to do with CEMU, because reshade works with d3d10 and thats why im asking. Fuck you man.
