### ISSUE TITLE
Assassin's Creed Brotherhood: Shadows don't render correctly on AMD

### ISSUE THREAD

**Issue by K0bin** [doitsujin/dxvk#2642]
Initially reported on Discord by EIREXE.

The issue is fairly obvious in this picture:

https://cdn.discordapp.com/attachments/853130811581530145/975008692925767751/unknown.png

Apitraces:
- https://drive.google.com/file/d/1QmpkWNnr5-8Q5kE6d0WGNS3tTYp7p6db/view
- https://drive.google.com/file/d/1045yJsFI9Elb-20Om4mg-tc9qzlN6QJH/view

It renders correctly on Nvidia GPUs. @CME42 identified the D24->D32 workaround as the cause of it. Forcing that makes it possible to reproduce it on Nvidia hardware.

**Comment by CME42** [comment]
The issue is due to depth bias, changing the RValue from 1<<23 to 1<<24 for D32 fixes shadow acne.
