### ISSUE TITLE
Repeatable stutter in Rogue Company

### ISSUE THREAD

**Issue by ryao** [doitsujin/dxvk#2643]
### Software information
Install Steam via flatpak and run Rogue Company. Running it outside of flatpak is known to be broken on both Arch Linux and Gentoo Linux due to EAC failing to load. It works inside flatpak.

Start the game and go into the shooting gallery. Then try killing the bots. The game will freeze on every kill until the bot has respawned. This is a repeatable stutter. No amount of entries in the dxvk state cache will fix it. Live matches have stutter too, but the shooting gallery's stutter is easily reproducible and can be repeated as many times as you wish.

### System information
- GPU: RTX 3080
- Driver:  Nvidia 515.43.04
- Wine version: Proton Experimental Bleeding Edge (as of 05/14/2022)
- DXVK version: 1.10.1 (or whatever proton experimental runs).

### Apitrace file(s)
It is an EAC game. I doubt EAC will allow apitrace to be run since other EAC games have empty API trace files.

**Comment by K0bin** [comment]
Without an apitrace, there's not much we can do.

Have you enabled the HUD to make sure it's really not shader compilation stutter (pipeline count would increase whenever it happens)?

**Comment by rezzafr33** [comment]
I think it was flatpak driver issue, 3 days ago 515 driver wasn't available due to an issue, fixed yesterday https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/107.

**Comment by ryao** [comment]
> I think it was flatpak driver issue, 3 days ago 515 driver wasn't available due to an issue, but it is fixed [flathub/org.freedesktop.Platform.GL.nvidia#107](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/107).

It would not be a flatpak issue. I had compiled the 515 driver specifically for flatpak using the instructions there.

**Comment by ryao** [comment]
I made some progress in figuring out why the game "only works in flatpak". It turns out that it just wants older libraries and will happily run on Ubuntu 20.04 (or any kernel that has a Ubuntu 20.04 userland). I have yet to narrow down the root cause, but I documented my most recent findings here:

https://github.com/anyc/steam-overlay/issues/313

Interestingly, with this setup, I see a very slight, less than 100ms, stutter now on each kill in the firing range.

**Comment by ryao** [comment]
> Have you enabled the HUD to make sure it's really not shader compilation stutter (pipeline count would increase whenever it happens)?

I will try that tomorrow. I had injured myself shortly after making this issue, so I put it down until now. I just started looking into this game's issues again today.

**Comment by wils0nyan** [comment]
hello, after browsing this thread I follow a few more of things you've said about this issue and tried disabling transparent hugepages and an issue i've had for a while with warhammer online (return of reckoning) seems to be fixed

basically at some point when playing the game, something would trigger and it would pause every few seconds but now it seems to be way better (fingers crossed at least so far)

echo never > /sys/kernel/mm/transparent_hugepage/enabled

**Comment by ryao** [comment]
After additional testing, I am no longer able to reproduce this issue. It is possible that the Rogue Company developers made some performance enhancements (especially since they are asking for people to report performance issues). I am closing this as resolved.
