### ISSUE TITLE
Low performance on Eiyuden Chronicle: Rising

### ISSUE THREAD

**Issue by Zeioth** [doitsujin/dxvk#2649]
CPU: Ryzen 5950X
GPU: AMD RX 6700
Drivers: Open source
Environment: Sway

The game runs about 70fps at 1080p. But the cpu/gpu usage is barely 5-15%. It is a Unity game.

Some people report 150-200fps on nvidia on max settings.

**Comment by K0bin** [comment]
Please provide an apitrace.

**Comment by doitsujin** [comment]
> But the cpu/gpu usage is barely 5-15%. It is a Unity game.

Your hardware is probably running at idle clock speeds then.

**Comment by liberodark** [comment]
Have same issue this game have low FPS.

**Comment by Blisto91** [comment]
Make a [apitrace](https://github.com/doitsujin/dxvk/wiki/Making-a-Trace) if you can.

Also what is your hardware and driver version.

**Comment by Zeioth** [comment]
Hey I created a .trace file. Hope it helps

https://we.tl/t-iG2iPNmOOW

**Comment by Zeioth** [comment]
I detected a problem with MangoHud reporting the GPU usage of the wrong card. Might be the issue. Researching:
https://github.com/flightlessmango/MangoHud/issues/746

**Comment by doitsujin** [comment]
Game runs at like 350 FPS here, hitting over 400 in the opening sequence.
![Bildschirmfoto](https://user-images.githubusercontent.com/25567304/170484176-0d8acaed-29cd-499a-899b-320cf1421b85.png)

Again, please make sure it's not a power management issue on your end. I don't see any reason to believe this is a DXVK bug.

**Comment by Zeioth** [comment]
Thank you so much for testing.

It's true it has 100% GPU usage on your end. On mine is barely 4%.

I tried to enable (and disable) the kernel parameters radeon.dpm=1 amdgpu.runpm=1 but no result. Also I checked on corectl that the GPU speed is maximum while playing(2658hz). The issue is GPU usage for some reason.

I wonder if it's an sway/wayland/xwayland thing. I will try with a different desktop environment.

**Comment by Zeioth** [comment]
Ok I figured out: 

I had to pass DXVK_FILTER_DEVICE_NAME="AMD RADV NAVI22" in order for DXVK to use the right GPU for the game. Now I get 500+ FPS and GPU usage 100%.

![screenshot_2022-05-30_01-21-24_537624905](https://user-images.githubusercontent.com/3357792/170895294-77f3f46f-21c9-4949-96d3-2800465a7f43.png)

**Comment by Blisto91** [comment]
Ah yes. Linux and multi GPU setups are a never ending joy 😁 
Glad you got it working.
