### ISSUE TITLE
Vsync Not Working? 

### ISSUE THREAD

**Issue by ekianjo** [doitsujin/dxvk#265]
### Software information
Seen in Witcher 3, but I have no idea if it is related to that game or a widespread issue at this stage.

### System information
- GPU:GTX970 nVidia
- Driver: 390.x
- Wine version: 3.5 
- DXVK version: 0.41
- OS: Linux Mint 18.3
- Compositor: Compton

Vsync on/off does not seem to change the rendering at all, which always shows some slight tearing especially visible in rapidly moving scenes. I do not have tearing problems with other games on the same distro/hardware, so wondering if it's just because Vsync is not properly supported yet or not.

**Comment by doitsujin** [comment]
Vsync *is* properly supported and should work fine, although it's not the first time I hear Nvidia users having issues with it (usually the other way around though). Can you try running the game from an X.org session rather than Wayland?

**Comment by doitsujin** [comment]
Ah, must have mixed up Compton with Weston, sorry.

But yeah, compositors can very well cause vsync-related issues if not configured properly, that's worth checking.

**Comment by xpander69** [comment]
go to nvidia-settings and under Display Configurations choose Advanced and enable ForceCompositionPipline for you monitor, that will fix the tearing. no need for vsync, which causes input lag.

You can also save this to your Xorg configuration so it will be enabled on every reboot.

that issue shouldn't even be here.

**Comment by Yardanico** [comment]
@xpander69 stop recommending that, it usually makes performance like 30% worse

**Comment by xpander69** [comment]
what? what DE? i have ran several test with it on and off, performance is always about same, +/- 1-2%

**Comment by ekianjo** [comment]
@doitsujin you can close this issue. I changed compositor and the tearing disappeared, so it's probably a Compton related issue in my case. Thanks for your answer!

**Comment by ccl2of4** [comment]
I am also having vsync issues on nvidia.

I'm playing Fallout 4, GTA V, and BeamNG.drive. All of these games exhibit a similar vsync issue for me: when my fps is at 60, I get no tearing, but when my fps drops below 60 I regularly experience tearing.

I have tried running my games in an environment with no compositor whatsoever, so it cannot be related to that.

@doitsujin I see you've said vsync is properly supported. Is there any information I can provide that might help diagnose this issue?

### System info
* GPU:GTX970 nVidia
* Driver: 396.24.0
* Wine version: 3.7-staging
* DXVK version: 0.50
* OS: Arch Linux

Thank you for the work you're doing, this is an amazing project
