### ISSUE TITLE
DXVK Skyrim LE memory allocate crash

### ISSUE THREAD

**Issue by blant221** [doitsujin/dxvk#2651]
I don't know why, but when using DXVK i have allocate memory crashes from Heap Replacer or Crash Fixes with couple of minutes gameplay.
DXVK give me boost about 10fps indoor/outdoor and remove micro stuttering when i fight or explore the world.

What i tried:
Disable heap replacer and enable UseOSAllocators & AlignHeapAllocate in Crash Fixes.
Disable Memory Optimizer and remove Memory Optimizer.exe file in Skyrim directory.
Enable in dxvk.conf d3d9.evictManagedOnUnlock
Add VRAM memory in dxvk.conf from my GTX 1080Ti in values - dxgi.maxDeviceMemory & dxgi.maxSharedMemory

Please help with that strange problem.
Thank you for reading! Maybe someone give me hints what to do :)

PS. Without DXVK everything is fine.

SYSTEM: Windows
LOG:
[TESV_d3d9.log](https://github.com/doitsujin/dxvk/files/8764794/TESV_d3d9.log)

**Comment by K0bin** [comment]
Most likely another instance of #1318.

Try #2524.

**Comment by Blisto91** [comment]
@blant221 You can grab a build of it here.

https://github.com/doitsujin/dxvk/actions/runs/2198005772

**Comment by blant221** [comment]
> @blant221 You can grab a build of it here. https://github.com/doitsujin/dxvk/actions/runs/2198005772
> 
> Just use it the same way as a proper release.

Thank you! dxvk.conf i can use same?

**Comment by Blisto91** [comment]
Yep should be fine

**Comment by blant221** [comment]
> Yep should be fine

Really, thanks ;) Time for testing!

**Comment by Blisto91** [comment]
Just note async won't do anything with this version since it isn't officially supported.
But it doesn't hurt leaving it there.

**Comment by blant221** [comment]
> Just note async won't do anything with this version since it isn't officially supported. But it doesn't hurt leaving it there.

Still same problem. I have crash to desktop in about 1-2 minutes with d3d9.evictManagedOnUnlock or without.
[TESV_d3d9.log](https://github.com/doitsujin/dxvk/files/8766078/TESV_d3d9.log)

**Comment by Blisto91** [comment]
I can try testing a bit if i have time this weekend. (Not a dev btw so i can't fix anything myself)

**Comment by K0bin** [comment]
It's probably not because of managed textures then. I'd need an apitrace to know more.

**Comment by blant221** [comment]
> It's probably not because of managed textures then. I'd need an apitrace to know more.

It's weird but with apitrace i don't have crashin 1-2 minutes, but game working like slideshow, very low fps. Right now passed about 10 minutes and still testing

**Comment by K0bin** [comment]
Nothing weird about that. With apitrace it's not using DXVK but instead recording every single D3D9 call which is slow.

**Comment by blant221** [comment]
> Nothing weird about that. With apitrace it's not using DXVK but instead recording every single D3D9 call which is slow.

Thank you for answer :) Still game is running without any crashes from apitrace

**Comment by K0bin** [comment]
Yeah, that's expected. There should be a .trace file on your desktop. Please compress and upload that.

**Comment by blant221** [comment]
> Yeah, that's expected. There should be a .trace file on your desktop. Please compress and upload that.

GOD DAMN! That file is 50GB size! .trace file.

**Comment by blant221** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/106177163/170139162-2832a1cd-0bbe-472f-b3d0-c1515cf4d8cb.jpg)

**Comment by K0bin** [comment]
O_O How long did you play with apitrace? Starting the game and running around for a minute is easily long enough.

Just delete that and make a new one but this time quit earlier.

**Comment by blant221** [comment]
If i play for about one minute, then this file is 8GB size x
![Bez tytułu](https://user-images.githubusercontent.com/106177163/170141356-c3400068-93c2-4b02-af3e-2ce5cdd5a656.jpg)
D

**Comment by K0bin** [comment]
Zip that and it'll be 4GB.

**Comment by blant221** [comment]
> Zip that and it'll be 4GB.

Ok i zip that and where i can upload 4GB file?

**Comment by blant221** [comment]
> Zip that and it'll be 4GB.

Ok i upload that file to google drive. In 20 minutes i give you a link.

**Comment by blant221** [comment]
> Zip that and it'll be 4GB.

https://drive.google.com/file/d/1QNAUDBuCSJfadUWkojGcP5W1Wd4cpNP4/view?usp=sharing
Here is the trace file.

**Comment by blant221** [comment]
> Zip that and it'll be 4GB.

If i may ask, do you check that .trace file? I am terribly anxious for a solution, although yes, I am aware that it may not work

**Comment by K0bin** [comment]
The game uses D3DPOOL_SYSTEMMEM in addition to D3DPOOL_DEFAULT textures, that's why the PR didn't work.

**Comment by K0bin** [comment]
#2663 should fix this.

**Comment by blant221** [comment]
> #2663 should fix this.

I check that build tonight :)

**Comment by blant221** [comment]
> #2663 should fix this.

If i load game indoor in a cave, everything is fine, but when i wanna go outdoor, then when it loads the game to a open world game crashes. I don't even have time to see on the screen game picture.

**Comment by K0bin** [comment]
Please upload logs of a crash.

**Comment by blant221** [comment]
> Please upload logs of a crash.
[TESV_d3d9.log](https://github.com/doitsujin/dxvk/files/8837992/TESV_d3d9.log)

**Comment by Blisto91** [comment]
The dxvk logs should to as a starter i think

**Comment by blant221** [comment]
> Please upload logs of a crash.

Here is trace file -> https://drive.google.com/file/d/1kqsuU4UkC8T2i2024-Fmgr2wrgZyynfL/view?usp=sharing

**Comment by blant221** [comment]
> Please upload logs of a crash.

I hope this is what you want? :)

**Comment by K0bin** [comment]
I fixed the issue with Skyrim in my PR.

**Comment by K0bin** [comment]
Closing this as it's already tracked by #1318
