### ISSUE TITLE
Batman:Arkham Knight sample mask and multisampling behavior problem

### ISSUE THREAD

**Issue by viktoriiapalianytsia** [doitsujin/dxvk#2653]
I have encountered a problem with Batman's cloak in the game Batman:Arkham Knight. It is always flickering and it looks like it is caused by DXVK.

Firstly the Mesa issue was created: [6078](https://gitlab.freedesktop.org/mesa/mesa/-/issues/6078). You can find most of information in this issue, but in general it appears that sample mask out behavior with multisampling is a problem here. It looks like DXVK is expecting GL behavior. It expects sample mask to be disabled for single sampled target, while VK behavior is different - per the Vulkan spec, shader writes to the sample mask work regardless of whether multisample is enabled.

**Trace**
[BatmanAK](https://mega.nz/file/9qJiHLhb#39jkKUbTbK0naEn6Qf_cBrwMYgCV9rp2MfPv3_xGgy8)

**Comment by doitsujin** [comment]
Is the D3D behaviour documented anywhere?

**Comment by Blisto91** [comment]
@viktoriiapalianytsia i see this have been worked around in the driver but if you are still around i think the devs would like some more info about the original issue if possible

**Comment by Blisto91** [comment]
@viktoriiapalianytsia Friendly double ping.

**Comment by viktoriiapalianytsia** [comment]
All the info I had about this misrendering is in the original [issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/6078). I can also provide the trace that was used while working with workaround in this [link](https://mega.nz/file/9qJiHLhb#39jkKUbTbK0naEn6Qf_cBrwMYgCV9rp2MfPv3_xGgy8).
