### ISSUE TITLE
AC Origins won't launch with Uplay overlay disabled.

### ISSUE THREAD

**Issue by Vladjaye** [doitsujin/dxvk#2655]
![winorigins](https://user-images.githubusercontent.com/35933475/170796331-ea66d849-b9f5-468f-a0c9-410b5ed0e789.png)
DXVK 1.10.1 (did try older versions too)
Nvidia Driver: 512.95 (same for the last few versions)
GPU: 3080Ti
Windows 11 x64 21H2
Assassin's Creed Origins (Steam + Ubisoft Connect)

Hello, not sure if it is okay to share issues with the Windows OS, but I have an issue with AC Origins game. If I launch it with Uplay (Ubisoft Connect) overlay enabled - it runs fine with the exception of freesync\g-sync not working - the display I have stays at 144hz. Game runs at about 80-130 fps, so it is not really smooth with static refresh rate. 
If I do disable Uplay Overlay (hoping that it will fix the non-working adaptive sync) - the game does not start, it gets stuck on the small rectangular logo\splash on desktop. Weirdly enough the disabled overlay should have helped with performance in general from what I understand. Does not matter if set game settings to Fullscreen or Borderless 
Any suggestions?
Thanks!
[ACOrigins_d3d11.log](https://github.com/doitsujin/dxvk/files/8789981/ACOrigins_d3d11.log)
[ACOrigins_dxgi.log](https://github.com/doitsujin/dxvk/files/8789982/ACOrigins_dxgi.log)

**Comment by doitsujin** [comment]
No idea why this wouldn't work *without* the overlay since we generally recommend disabling overlays, but this is one of the many many reasons why we don't really provide support for Windows systems.

**Comment by qinlili23333** [comment]
Have you also disabled Steam Overlay?
Overlays use injection to show additional information on game interface and usually they choose to inject graphics related API so they can directly draw content above game.
RTSS and other tools that can show content above game also use this type of injection, except NVIDIA Share (it is powered by GPU driver functions). There is no way to control these tools' injecting orders since all tools detect and inject by themselves. 

U can use ProcessExplorer to see all DLL files loaded by the game, and maybe u will find something weird.

**Comment by Vladjaye** [comment]
Yes, I did try with steam overlay disabled too - did not help. Weirdly enough, AC Odyssey (I guess pretty similar to Origins) works very good with both Steam and Uplay overlays on the same exact system and its variables. Will try ProcessExplorer shortly - thanks! :)

**Comment by Vladjaye** [comment]
Update:
ProcessExplorer did not show anything different vs launching AC Odyssey. Same dlls, not really anything third-party.

**Comment by Vladjaye** [comment]
Can't update yet - they cancelled the update until something will be fixed. Can't test anything because of this.

**Comment by qinlili23333** [comment]
> Can't update yet - they cancelled the update until something will be fixed. Can't test anything because of this.

Seems that the newer Denuvo has some compability issues. Console's update isn't cancelled. Wait a few days and see whether ubi will fix it and release again.

**Comment by Vladjaye** [comment]
Still waiting for Ubisoft to push the Steam ver. update.
Meanwhile I did manage to test the same scenario on pretty similar specs machine with different environment - 3900X, 3080Ti, Windows 11, older GPU driver version. Motherboard manufacturer is ASUS vs my MSI. The results are exactly the same - game fails to start.

**Comment by Ryusennin** [comment]
Strange that Ubiconnect overlay would force vsync. I don't have any issue with Freesync unlocked.

Have you tried editing your dxvk.conf file?

dxgi.syncInterval = 0
d3d9.presentInterval = 0

**Comment by Vladjaye** [comment]
I did try to play with dxvk.conf settings and just tried the lines above - did not help. Monitor still stuck at 144hz.
One interesting thing though, is that both fullscreen and borderless-window modes don't work with freesync - 144hz. Completely windowed mode though, the one with borders etc. works with freesync. As soon as I press ALT+ENTER to force fullscreen -monitor returns to 144hz. Also, as mentioned before, all this works only if Uplay overlay is active. Otherwise game does not start in any mode.

**Comment by smintman** [comment]
> > Update:
> > ProcessExplorer did not show anything different vs launching AC Odyssey. Same dlls, not really anything third-party.
> 
> Have you installed today's 1.60 patch of AC Origins released a few hours ago? Install and try again. Today's patch seems to use a newer version of VMProtect and Denuvo that the executable file size changes a lot. After update i tested both overlay and non-overlay with DXVK, everything works well on my Windows PC. Maybe it's ubi's bug instead of DXVK's.

I'm using 1.6 on my steamdeck and this version has broken AC: Origins it seems to have issues with Win 7 machines, so not sure if issues with dxvk or bad release?

Posted bug here with log https://github.com/ValveSoftware/Proton/issues/928

**Comment by Ryusennin** [comment]
Probably not related to DXVK. On Ubi forum, several people complain that the last patch (with the super useful "Assassin's Creed Franchise" store shortcut) has broken Win7 support.

**Comment by smintman** [comment]
> Probably not related to DXVK. On Ubi forum, several people complain that the last patch (with the super useful "Assassin's Creed Franchise" store shortcut) has broken Win7 support.

Think you right, but is there any config in dxvk that can make the game run more like its not on windows 7? I think the default pfx in proton are windows 10 based, but maybe there is something the real windows 10 does that we can configure dxvk to do? if anyone know?

**Comment by Vladjaye** [comment]
Did update the game - still the same behavior.  Does not work without overlay. Works with overlay, but monitor does not catch the Freesync state or something - stays at 144hz and because of this the game is not really smooth. Eh, had such high hopes for the patch.

**Comment by Blisto91** [comment]
Can any of you check if anything has changed with dxvk master in relation to this issue? Alot of changes have been made since.
You can grab a build here https://github.com/doitsujin/dxvk/actions/runs/2940494057

Note you need relatively up to date drivers to use it

**Comment by Vladjaye** [comment]
Still does not work for me. The same behavior as before - stuck on splash. When using with UbiConnect overlay ON - the game still does not work with freesync either. I can set it to 90fps lock and my monitor would still report 144hz refresh rate.

**Comment by K0bin** [comment]
I'm going to close this. I'm sorry that it doesn't work but there's nothing we can do here. The game works on Linux.

**Comment by qinlili23333** [comment]
> Still does not work for me. The same behavior as before - stuck on splash. When using with UbiConnect overlay ON - the game still does not work with freesync either. I can set it to 90fps lock and my monitor would still report 144hz refresh rate.

Maybe it's ubi's overlay bug.
A small guess: delete libEGL.dll and libGLESv2.dll to force ubi use soft rendering for overlay may help.(didn't tried, since i can run game both overlay on and off, without freesync monitors)

**Comment by Vladjaye** [comment]
There is definitely something happening with the overlay. I got these observations:
1. When I try to use the attached build in other AC game, Odyssey, the overlay is really buggy. Basically if I open overlay within a game and close it - it technically gets closed (not clickable etc.), but it is still being shown within the game. Also the game shows a notification about controller being connected as an overlay message - after timeout it disappears, but with the dxvk build it technically disappears, but practically "last frame" of it continues to be drawn on screen even if it is no longer interactable. Never had any AC Odyssey issues with DXVK before.
2. I did try to delete the GL dlls of the Ubisoft Connect and run AC Origins. With overlay off, as expected, same behavior of being stuck on splash screen. With overlay on - the game loads, still stuck at 144hz freesync, but the overlay has exactly the same behavior as in AC Odyssey - after any interaction, last state of overlay keeps being shown after technically being closed. Not sure if it makes sense and if it can lead anywhere. Thank You to anyone, who dedicated time to this. :)

**Comment by qinlili23333** [comment]
> There is definitely something happening with the overlay. I got these observations:
> 
> 1. When I try to use the attached build in other AC game, Odyssey, the overlay is really buggy. Basically if I open overlay within a game and close it - it technically gets closed (not clickable etc.), but it is still being shown within the game. Also the game shows a notification about controller being connected as an overlay message - after timeout it disappears, but with the dxvk build it technically disappears, but practically "last frame" of it continues to be drawn on screen even if it is no longer interactable. Never had any AC Odyssey issues with DXVK before.
> 2. I did try to delete the GL dlls of the Ubisoft Connect and run AC Origins. With overlay off, as expected, same behavior of being stuck on splash screen. With overlay on - the game loads, still stuck at 144hz freesync, but the overlay has exactly the same behavior as in AC Odyssey - after any interaction, last state of overlay keeps being shown after technically being closed. Not sure if it makes sense and if it can lead anywhere.
>    Thank You to anyone, who dedicated time to this. :)

seems that the overlay keeps rendering at a high framerate, cause the freesync failure and continuous drawing.
this may also explain why fps is lower when overlay turn on in R6S on my laptop, even in native vulkan. (at least the performance downgrade has existed since the new version of overlay)
