### ISSUE TITLE
Alt tabbing in GTA 4 for more than a few seconds causes game resolution to be lowered significantly (from 1440p to 480p), unable to change resolution back since the resolution in GTA 4 requires commandline arguments in order to change the resolution

### ISSUE THREAD

**Issue by BUNGUS-is-stupid** [doitsujin/dxvk#2656]
### Software information
Grand Theft Auto 4
Normal in game settings (dxvk.conf is unchanged)

### System information
- GPU: NVIDIA RTX 2060
- Driver: 512.95
- Wine version: On Windows (Sorry if problems on windows aren't supported)
- DXVK version: v.10.1

### Log files
- d3d9.log: 
[PlayGTAIV_d3d9.log](https://github.com/doitsujin/dxvk/files/8791158/PlayGTAIV_d3d9.log)

- d3d11.log:
- dxgi.log:

**Comment by K0bin** [comment]
GTA IV has a bunch of bugs related to alt+tab. It seems to be super sensitive to the exact window messages it receives.

No idea what's wrong or how to debug this, so don't expect a fix for this any time soon.

**Comment by BUNGUS-is-stupid** [comment]
Okay thanks for the reply, also I play GTA 4 in windowed borderless mode since that is meant to help with alt+tabbing, but I really appreciate the reply

**Comment by lextra2** [comment]
I guess you already did this, considering your title?
Try making a shortcut with `-nomemrestrict -norestrictions`
Or make a text file and name it `commandline.txt` with the same commands and move it to the same folder as GTAIV.exe

This should unlock resolution in the game graphic settings.

Also, does the same happen without dxvk?

**Comment by deton24** [comment]
Similar issues on AMD (Polaris), I think not always, but I'm able to change my resolution back to normal on R* Launcher version of the game.
It even happened that it switched the resolution to the lowest on startup, not only after alt tabbing.
JFI also once when I showed up ENB panel in-game using DXVK and I think Reshade, it made the game stutter for too long and the game crashed, but I think it didn't happen more than twice if at all in normal gameplay.

**Comment by VermiumSifell** [comment]
Same problem!

**Comment by Blisto91** [comment]
@BUNGUS-is-stupid @deton24 @VermiumSifell Please try with this PR https://github.com/doitsujin/dxvk/pull/3316. You can find a download of it here https://github.com/doitsujin/dxvk/actions/runs/4537356630

**Comment by K0bin** [comment]
This is hopefully fixed now.
