### ISSUE TITLE
Fail with build

### ISSUE THREAD

**Issue by rolexlinux** [doitsujin/dxvk#2657]
Everything was going well but after some time the build fails on this part
```
In file included from /usr/include/X11/Xlib.h:44,
                 from ../wine-mirror-git/dlls/winex11.drv/systray.c:31:
../wine-mirror-git/include/processthreadsapi.h:43:11: error: expected identifier or ‘(’ before numeric constant
   43 |     ULONG ControlMask;
      |           ^~~~~~~~~~~
make: *** [Makefile:226351: dlls/winex11.drv/systray.o] Error 1
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().
    Aborting...

```
I'm running arch with the latest kernel (5.18.0-arch1-1) x64 fresh install

**Comment by Blisto91** [comment]
Why are you making a issue here and not at the wine-tkg-git repo? :thinking: Am i missing something?
Someone have already [opened a issue](https://github.com/Frogging-Family/wine-tkg-git/issues/779) in that repo.

**Comment by doitsujin** [comment]
Wrong project, your error comes from building wine.
