### ISSUE TITLE
Titanfall 2 + Northstar crashes while loading dxvk

### ISSUE THREAD

**Issue by BotchedRPR** [doitsujin/dxvk#2658]
### Software information
Game: Titanfall 2 + Northstar (Regular game works fine)
Software: Pop_OS, Steam Proton (tried every version from Experimental to 5.0_10, and 7.3-GE-1), DXVK 1.10.1
Launcher: Steam

### System information
- GPU: 1080ti
- Driver: 510.69.02
- Wine version: in Software information
- DXVK version: 1.10.1 also tried master branch

### Apitrace file(s)
not traceable, file isn't even created.

### Log files
none are created, seems like the game has trouble actually loading dxvk. here's the northstar log file if that'd help
https://pastebin.com/ngBj7f5u

Northstar does work with wined3d (obviously very poorly). Also, regular game works fine. I can provide more logs, however by myself I only could get the northstar log. Seems like the northstar launcher crashes while loading dxvk.

**Comment by K0bin** [comment]
Are you trying to start the client or server version?

**Comment by BotchedRPR** [comment]
> Are you trying to start the client or server version?

Client version.

**Comment by BotchedRPR** [comment]
This is caused by Northstar shipping with a broken DXVK release. You need to copy the latest release's dlls into Titanfall2/bin/x64_retail, and then installing the latest DXVK release into your prefix. Here's the latest release of Northstar running on DXVK:
![image](https://user-images.githubusercontent.com/68894028/170865539-6167eb95-fb39-47f6-acdb-ffcf66be3aba.png)

**Comment by GeckoEidechse** [comment]
Wait, I'm a bit confused. The only file we ship in that directory is the `wsock32.dll` (`Titanfall2/bin/x64_retail/wsock32.dll`) which shouldn't be related to DXVK in any way...

**Comment by BotchedRPR** [comment]
we're chatting about this on discord, let's see what wacky stuff is going on here

**Comment by GeckoEidechse** [comment]
To follow this up based on discussions on Discord, it seems the "botched" DXVK version is being downloaded by Steam itself. I'm putting "botched" in quotes as it works fine with vanilla game but Northstar does a few things differently that cause it not to work, the cause of which is yet to be determined.

Northstar only ships `d3d11.dll` for dedi and that's it. `bin/` folder of [`v1.7.2` release](https://github.com/R2Northstar/Northstar/releases/tag/v1.7.2) for example:
```
$ tree bin/
bin/
├── x64_dedi
│   ├── d3d11.dll
│   ├── GFSDK_SSAO.win64.dll
│   └── GFSDK_TXAA.win64.dll
└── x64_retail
    └── wsock32.dll

2 directories, 4 files
```

**Comment by K0bin** [comment]
The d3d11 version they ship for the dedicated server is a pure stub.

**Comment by KyleGospo** [comment]
Wine should be default configured to use native D3DX libraries and none of what any game ships with

**Comment by GeckoEidechse** [comment]
Turns out the DXVK dlls were created by ReShade not Steam.

**Comment by BotchedRPR** [comment]
It was ReShade causing it that I previously installed on my Windows machine. Damn.
