### ISSUE TITLE
Crash at createDxgiFactory on Wine-staging 3.5

### ISSUE THREAD

**Issue by kiroma** [doitsujin/dxvk#266]
I've tried to run DXVK  on wine-staging 3.5 using the version from [https://repos.wine-staging.com/alesliehughes/](https://repos.wine-staging.com/alesliehughes/).  
[Traceback](https://gist.github.com/kiroma/1b074dca2aba57a15c3b2438a71c98dc)
I have dxvk and shaderc compiled from source from master trees.
I'm on Kubuntu 17.10, nvidia drivers 390.48 from [graphics-drivers](https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa) ppa.

### Software information
dxgi-factory.exe

### System information
- GPU: GTX 950M
- Driver: 390.48
- Wine version: 3.5-staging
- DXVK version: compiled from master

### Log files
- d3d11.log: empty
- dxgi.log: empty

**Comment by doitsujin** [comment]
Sounds more like a driver/wine issue than anything else. Do you have the Intel Vulkan driver installed? If so, you might need to remove it or set `VK_ICD_FILENAMES` to the Nvidia driver's `json` file..

**Comment by kiroma** [comment]
No I don't have them installed.

**Comment by doitsujin** [comment]
Must be an issue with wine's Vulkan implementation.

**Comment by kiroma** [comment]
I've tried it again with 3.6-Staging and 3.6-Devel and it crashed again, should I file a bug report to them?

**Comment by kiroma** [comment]
Wine 3.10-staging every sample is crashing with the same error message: `002e:err:d3dcompiler:compile_shader HLSL shader parsing failed.`

**Comment by doitsujin** [comment]
You'll have to use native d3dcompiler DLLs for games that use them.
