### ISSUE TITLE
Far Cry 4 crash at startup [DX11, apitrace included, AMD RX 400 series]

### ISSUE THREAD

**Issue by deton24** [doitsujin/dxvk#2666]
Uplay overlay disabled (didn't help).

One report [here](https://forums.guru3d.com/threads/dxvk-1-7-1-a-vulkan-based-translation-layer-for-dx-9-10-11.433720/page-7#post-5917004) says FC4 worked with dxvk-async 1.8.1 on W10 and 5700 XT, I checked dxvk-async 1.8.1 (with and without specific for async dxvk.conf `dxvk.enableAsync = true` parameter), and it's still the same. In other [report](https://www.reddit.com/r/Amd/comments/lcv6p9/gta_v_or_far_cry_4_with_dxvk/), it worked on W10 20H2 and driver 21.5.2 and dxvk-async 1.8.1 on 5700XT: "Performance [was] worse with Vulkan than DX11, even if it's more consistent. There [were] visual glitches with shadow rendering". Current dxvk_async doesn't work either.
Looks like the same issue exist on Proton to this day ([link](https://github.com/ValveSoftware/Proton/issues/2143#issuecomment-939612943)) as you see responses below, but it [works ](https://www.protondb.com/app/298110) on SteamDeck via Proton.

If I leave only d3d11.dll the game launches, I can hear the sound, but the screen is black, and it doesn't make the game full screen like FC4 does on startup. I tried minimizing and maximizing.

I tried leaving only dxgi.dll, but it showed errors of d3d10 libraries on initialization, I copied them from dxvk as well, but still crash like when only dxgi.dll and d3d11.dll are copied, or all of the libraries.

Far Cry 3 using DX9 also crashes (I can create another issue with apitrace later).

### Software information
Far Cry 4 Uplay (DX11), maximum details except soft shadows, FHD 16:10, SMAA.

### System information
- GPU: RX 470
- Driver: 22.5.2 (the newest optional)
- DXVK version: 1.10.1
- Windows 10

### Apitrace file(s)
 - (it's small, made with -skipintro closed the game after "logging in" - when main menu is shown) (https://disk.yandex.com/d/mP8LfvtD-p1xGg)

### Log files
- d3d11.log: [FarCry4_d3d11 crashed.log](https://github.com/doitsujin/dxvk/files/8838140/FarCry4_d3d11.crashed.log)
- dxgi.log: [FarCry4_dxgi.log](https://github.com/doitsujin/dxvk/files/8838135/FarCry4_dxgi.log)
- d3d11.log (closed on intros): [FarCry4_d3d11_closed on intros.log](https://github.com/doitsujin/dxvk/files/8838143/FarCry4_d3d11_closed.on.intros.log)
- d3d11.log (closed in main menu with intros skipped): [FarCry4_d3d11 closed in menu w_o intros.log](https://github.com/doitsujin/dxvk/files/8838145/FarCry4_d3d11.closed.in.menu.w_o.intros.log)

As for a apitrace, I had a headache making it. I needed to copy everything from lib\wrappers to bin folder, then only launched the game, and it created the trace on desktop. It would be nice to add an information about this method in [bug_report.md](https://github.com/doitsujin/dxvk/commit/6a80b51dc3dd84c5e36a7e3375ffd0db7a041970#diff-185833cb26d7ac66a4d39042fd576a820c2c2c6d05ad18973bb9c7dce77267c5) if apitrace doesn't work for someone. I also tried --api instead of -a and specifying --output [path\name.trace] so I either tried:
`apitrace.exe trace --api dxgi D:\Gry\Far Cry 4\bin\FarCry4.exe --output D:\Gry\Far Cry 4\bin\application.trace
`
and also:
`apitrace.exe trace --api dxgi D:\Gry\Far Cry 4\bin\FarCry4.exe`
with described in bug_report.md:
`apitrace.exe trace -a dxgi D:\Gry\Far Cry 4\bin\FarCry4.exe`
I was launching it all from bat located in D:\Downloads\apitrace-11.1-win64\bin which was launching the game itself, so I assume it worked correctly.

**Comment by Blisto91** [comment]
I am able to launch it on linux through proton. Tho it seems finicky and can easily freeze during startup if i alt tab or anything, so i don't touch it until i get to the main menu.
R9 380 mesa 22.1 (linux open source drivers)

Anyway try disabling or [enabling](https://github.com/doitsujin/dxvk/issues/2655) ubisoft overlay (switching it from what ever it is at the moment)
Also try with latest master https://github.com/doitsujin/dxvk/actions/runs/2434778593

I will try to check it out on windows or amdvlk (amd's own linux vulkan driver) when i have time.

**Comment by Blisto91** [comment]
Okay i tried on windows 10 with dxvk 1.10.1 (d3d11.dll & dxgi.dll) and didn't encounter any issues.
This is with the 21.5.2 driver as it is the latest i can use since amd dropped support for my card last year.

Are you able to try and downgrade your graphics driver?

**Comment by deton24** [comment]
>  it seems finicky and can easily freeze during startup if i alt tab or anything (maybe just randomly), so i don't touch it until i get to the main menu.

Yeah, I noticed that on me end too when used only d3d11.dll. I waited patiently till the sound with intro skipped starts playing.

Just tried out with either disabled and enabled overlay again using various library combinations I mentioned, but it's the same. With only d3d11.dll it even crashes when overlay is enabled (so there is no black screen with sound I mentioned).

Downloaded the latest master from the link above. Still nothing. Behavior is exactly the same as I described above.

Thanks for fast response!

**Comment by deton24** [comment]
Checked the 21.5.2 from a year a go, and nothing. Both master, 1.10.1, 1.8.1 checked. Overlay enabled and disabled.

When I leave only dxgi.dll and d3d11.dll, it always shows:

> The procedure entry point DXGID3D10RegisterLayers could not be located in the dynamic link library C:\Windows\System32\d3d10core.dll

It's shown three times and then crashes.

or it's about d3d10_1core.dll when d3d10_1.dll is deleted

I have Directx updated using 2011 dxsetup and dxwebsetup.exe but the files doesn't seem to be part of the DirectX installers.
Could you upload me your d3d10_1core.dll and d3d10_1.dll from system32 so I could put it to bin directory to check whether it is not bound to my old W10 build?

Maybe you could also update drivers on your end to see whether it works and whether DXGID3D10RegisterLayers is not bound to my old W10 build?
But it may crash on newer drivers without that error anyway, seeing by last people [reports](https://github.com/ValveSoftware/Proton/issues/2143#issuecomment-939612943) from 10 days even on Nvidia so it's still worth trying out.

**Comment by doitsujin** [comment]
> Maybe you could also update drivers on your end to see whether it works and whether DXGID3D10RegisterLayers is not bound to my old W10 build?

We don't implement that function since it's not part of the public API. The most likely cause is that the game does not load our dxgi.dll and instead uses the one from System32, which is impossible to work around on our end and does not happen on Linux.

**Comment by Blisto91** [comment]
@deton24 I can't update my graphics drivers if that's what you mean.
I think my win 10 is up to date, tho i am not sure. Directx (at least the newer version) should be included with windows 10 and is updated through windows update.

I was using 1.10.1

**Comment by deton24** [comment]
If you running into any issues on unsupported Windows version on newer
drivers installation, you can use DDU in Safe Mode to u install the drivers
and eventually install them via Device manager and then run
ccc2_install.exe.

Tomorrow I'll check if replacing dxgi.dll in system32 fixes any issues (or
syswow64 should be checked as well?).

sob., 4 cze 2022, 23:48 użytkownik Blisto91 ***@***.***>
napisał:

**Comment by doitsujin** [comment]
> Tomorrow I'll check if replacing dxgi.dll in system32 fixes any issues

Please don't do that, it'll break your Windows install.

**Comment by deton24** [comment]
Thanks for advise. It wasn't like I wasn't afraid a bit.

Ahh. You can't update because the support for these cards had been dropped.

You probably, but know one of the older AMD cards was still supported, and that's why older GCNs can still have newer drivers after some tweaking, here are unofficial drivers:
https://forums.guru3d.com/threads/3rd-party-driver-amernime-zone-radeon-insight-22-5-1-whql-driver-pack-released.436611/

**Comment by Blisto91** [comment]
It's fine. I mainly use linux at the time being and the open source driver supports my cards fully still.

**Comment by RareMv** [comment]
Hey @deton24 . The Guru3D and Reddit post were both done by me, in the same timeframe. It was the first time I managed to get Far Cry 4 working with DXVK at that time. I didn't really get around playing the game, so I haven't tested the game since to see if something changed. I remember uPlay also working at that time as well.

**Comment by Blisto91** [comment]
@deton24 Any update on this?

**Comment by deton24** [comment]
Still stuck on old W10 build.

Amernimer drivers didn't fix the issue, but they have experimental option
of DX11 enhancements for GCN cards which AMD introduced not long time ago.

Tried replacing all DirectX libraries from newer build, but system hangs on
black screen with cursor - probably it cannot initialize explorer or dwm.
I had backup of files and I was replacing everything in built-in Windows
RTE. Risky if you don't have complete DVD with your build to open it's
archives with 7zip, because RTE doesn't have all the libraries in hidden
partition, and it's easy to forget about something during replacing and
ending up without backup files.

So, it still crashes for me.

niedz., 3 lip 2022, 13:28 użytkownik Blisto91 ***@***.***>
napisał:

**Comment by RareMv** [comment]
The NimeZ DXNAVI module for DX11 improvements are more or less only 100% reliable just on RDNA1 (and RDNA2 of course).

Using them on anything other than RDNA is just luck of the draw.

**Comment by deton24** [comment]
Well. It wouldn't make much sense to enable anyone using it on older cards than RDNA. In official drivers it's limited for RDNA2 for most extent (in newer drivers RDNA1 doesn't benefit from DX optimization without this mod too much - drivers use different libraries). As for testing it on older cards, it will be the best to test in specific titles, where the performance gains using new DX optimizations are the biggest on RDNA and RDNA2 (e.g. God of War). But from the technical side, also GCNs use the same AMD libraries for DX11 like RDNA2 in this mod now, and only few games are buggy in this way, so it may simpl,y work. But, it's also worth testing whether anything changed for old DX11 games. Personally I tested mentioned in this thread Far Cry 4. The drivers also allow using different kernel (GPUV).

I tried to compare the results of "AMD 22.5.1 with GPUV 21.40 / LTS 22.2.3 Kernel" with DX optimizations vs official 22.5.2, and in FC4 in more demanding place it was one or two FPS better using modded drivers (36-37 vs 35) and I think that small difference is repetitive.
Additionally, I noticed that I have slightly fewer FPS (38 vs 36 FPS) when UI/CCC is installed. It happened on the official drivers before and the change was repetitive also using official drivers.

During that time I also compared various modded kernels - modded AMD 22.5.1 with GPUV 21.30 / LTS 21.11.3 with modded AMD 22.5.1 with GPUV 21.40 / LTS 22.2.3, and the latter achieved more FPS in Far Cry 4 (44 vs 47 FPS in other place nearby first safe house). Old 4 core CPU, geometry, environment low, shadow medium, fur on, SMAA, the rest max. CSGO FPS Benchmark got min. 53 FPS using AMD 22.5.1 Installation for Desktop/Mobile with DX optimizations vs 57-58 "AMD 22.5.1 with GPUV 21.30 / LTS 21.11.3" and "AMD 22.5.1 with GPUV 21.40 / LTS 22.2.3 Kernel Installation for Desktop/Mobile" respectively (at the limit of the measurement error) unfortunately I forgot to make another pass when I got the 53 FPS result.

Every FC4 result was received after restart, otherwise results were bigger.
Using official drivers, I also noticed that till I didn't restart the PC after installing new drivers, I got a bit worse max FPS in Furmark.
Every driver version was installed after cleanup in DDU.

**Comment by Blisto91** [comment]
@deton24 friendly ping. Have you tried updating yet? 🙂 
Also try latest master if you can.

**Comment by deton24** [comment]
No.
I'll try master in some free time and let you know about it.

niedz., 9 paź 2022, 15:07 użytkownik Blisto91 ***@***.***>
napisał:

**Comment by deton24** [comment]
Tested latest master with artifact produced:
https://github.com/doitsujin/dxvk/actions/runs/3204372286
And still nothing (same error d3d10core.dll error). Temporary tested on 22.7.1 drivers (but I believe older drivers create more in-game problems then with game initialization itself in case of DXVK).

After replacing d3d10core.dll from newer build (but it's much smaller), it still crashes without specific error  - d3d12.dll related crash in Event Log - so I replaced d312.dll from newer build as well (but not matching to core), and now it crashes both with overlay disabled and enabled with FC64.dll in Event Log. But it is the same even without DXVK, so replacing libraries creates a new problem on my end, so don't bother. I don't know whether it would even work with the same build libraries. Previously my friend didn't have d312.dll in system32 when I replaced everything, now I found d312.dll from elsewhere and oly replaced core and d312.

With my normal system libraries it still works without DXVK of course (and loads the whole game world correctly).

I'll let you know immediately when I'll be able to test on newer W10 build (doesn't seem to be soon, though, sorry).

**Comment by K0bin** [comment]
This is almost certainly either a driver bug or an something that only happens on Windows. In either of those cases, there's nothing we can do. There's a reason why Windows isn't officially supported by DXVK D3D10 and D3D11,

**Comment by CortexReaver** [comment]
I've got the same Issue with Far Cry 3 but on Windows 7 with NVidia card (I decided not to make a new issue because of that). The error were looking similar for d3d11: DXGID3D10GetLayeredDeviceSize in dxgi.dll. May be this will be useful for someone.
Btw, any news on this problem? This Dunia engine is very finicky on its own, works awful with the default d3d9.dll and crashes every 10 minutes with d3d11.dll.

**Comment by Blisto91** [comment]
No specific progress has been made no since i don't think any devs here have the issue on Linux. 
If it doesn't work with the commits that have been made on the [1.10.x branch](https://github.com/doitsujin/dxvk/commits/1.10.x) since 1.10.3 then there won't ever anything from the DXVK side that makes it work on your Windows 7 install as the next major version requires a driver bump and old drivers won't be supported anymore.

**Comment by K0bin** [comment]
I'm closing this because the game appears to work on Linux. This is probably another Windows issue that we can't do anything about.

**Comment by CortexReaver** [comment]
Far cry 3 seems to be working fine on Windows 10 22H2.
