### ISSUE TITLE
Missing Particle Effects in Sonic Adventure 2

### ISSUE THREAD

**Issue by TBirdSoars** [doitsujin/dxvk#2672]
Some particle effects are missing from stages in Sonic Adventure 2 when using DXVK, such as the smoke effects at the start of the stage "Iron Gate":

Without DXVK:
![20220608204808_1](https://user-images.githubusercontent.com/31261091/172741174-84b5b637-32c8-4b68-b6ba-29a916451c76.jpg)

With DXVK:
![20220608204853_1](https://user-images.githubusercontent.com/31261091/172741192-509b55e2-cc85-4b2c-a0eb-7cca79d0fc6d.jpg)

### Software information
Sonic Adventure 2, Steam, 32-bit, D3D9, Windowed, 1280x720

### System information
- GPU: RTX 2070 Super
- Driver: 512.77
- Windows 10
- DXVK version: [Artifacts (Package) 1241](https://github.com/doitsujin/dxvk/actions/runs/2453640073), also occurs on [1.10.1](https://github.com/doitsujin/dxvk/releases/tag/v1.10.1)

### Apitrace file(s)
https://mega.nz/file/bOJDjK5b#PhHebE2q_OuGQUBuBX7oQunqoMczGL2tSiDjtJlt95M

### Log files
[sonic2app_d3d9.log](https://github.com/doitsujin/dxvk/files/8865855/sonic2app_d3d9.log)

**Comment by Blisto91** [comment]
Hi there. I will try to test this later on linux when i have time.
In the mean time can you check if anything changes when you make a file called `dxvk.conf` next to the games .exe and insert
```
d3d9.floatEmulation = Strict
```
To verify that the game picks up the conf file you can also add dxvk.hud = 1 and check that the hud shows up ingame.

**Comment by TBirdSoars** [comment]
I've added `dxvk.conf` to the game folder and the DXVK HUD does appear.

The particle effects reappear with `d3d9.floatEmulation = Strict`, as well as when set to `True` and `Auto`. According to the log, it looks like that value was being set to `False` without `dxvk.conf`.

**Comment by Blisto91** [comment]
Thanks for testing.
The current value is to work around issues in the game from the days of yore https://github.com/Joshua-Ashton/d9vk/issues/292

But back then strict wasn't a options so we just need to verify it doesn't regress anything else.

I will check it out here later on Linux/windows.

**Comment by K0bin** [comment]
Can't reproduce:
![image](https://user-images.githubusercontent.com/1131720/173119725-01da3a6a-086f-4b61-a6a5-f35333ce7467.png)

**Comment by Blisto91** [comment]
Can reproduce here.
This was with proton 7.0-3RC, amd R9 380 and mesa 22.1.1

DXVK
![Screenshot_20220610_221527](https://user-images.githubusercontent.com/47954800/173144136-89d3f226-c5ee-4c31-a147-af748afad6ff.png)

WINED3D
![Screenshot_20220610_221631](https://user-images.githubusercontent.com/47954800/173144188-274a9aa4-48da-46ff-8364-69e3a46ce5b9.png)

**Comment by K0bin** [comment]
Can you try #2677? You can find a build here: https://github.com/doitsujin/dxvk/actions/runs/2477933077

Please make sure it doesn't bring back this issue: https://github.com/Joshua-Ashton/d9vk/issues/292

**Comment by Blisto91** [comment]
@TBirdSoars May i also say thanks for a nicely made and filled out issue.

**Comment by TBirdSoars** [comment]
@K0bin I'm not getting that issue with #2677. I've heard of that issue before, though I've never personally encountered it. I could be wrong, but I thought that issue was GPU-dependent, only occurring on systems with integrated graphics. It should be fixed for anyone using the SA2 Mod Loader: https://github.com/X-Hax/sa2-mod-loader/commit/13d518555ca3c77311ad13923cf4a909bf868e5f
