### ISSUE TITLE
CP2077 crashes on win7 if using dxvk

### ISSUE THREAD

**Issue by adi8900** [doitsujin/dxvk#2686]
cp2077 version is 1.3, i know in newer they removed w7 support
system spec:
Ryzen 7 2700@4ghz all cores
4x8gb ddr4 3000mhz team group
mx500 500gb
rx580 4gb nitro+
b450 tomahawk max
Windows 7 with all latest esu updates installed

dxgi.log
warn:  CreateDXGIFactory2: Ignoring flags
info:  Game: Cyberpunk2077.exe
info:  DXVK: v1.10.1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Radeon RX 580 Series:
info:    Driver: 2.0.179
info:    Vulkan: 1.2.170
info:    Memory Heap[0]: 
info:      Size: 3840 MiB
info:      Flags: 0x3
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 16103 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x3
info:      Memory Type[3]: Property Flags = 0x7
info:      Memory Type[4]: Property Flags = 0x1
warn:  DxgiAdapter::QueryInterface: Unknown interface query
warn:  7abb6563-02bc-47c4-8ef9-acc4795edbcf

**Comment by doitsujin** [comment]
The game uses D3D12 so yeah obviously it won't work with this. We also do not, under any circumstances, provide support for Windows 7.

**Comment by adi8900** [comment]
Oh ok, didn't know
Thanks for answer
