### ISSUE TITLE
Ran into -bash: ./setup_dxvk.sh: Permission denied when trying to run the ./setup_dxvk.sh install command

### ISSUE THREAD

**Issue by Froggio5543** [doitsujin/dxvk#2687]
When executing the ./setup_dxvk.sh install command I recive the message that permission is denied. Have I done something wrong?

**Comment by Blisto91** [comment]
Try to make sure it has execute permission by running `chmod +x` on it.
(cd to it first)
```
chmod +x setup_dxvk.sh
```

**Comment by Blisto91** [comment]
@Froggio5543 Did you manage to get it working?

**Comment by Blisto91** [comment]
If you still have issues feel free to comment here again.
Or if you run into another problem open a new one :slightly_smiling_face:
