### ISSUE TITLE
Kingdom Come crash/freeze/PC lockup. Hardware or DXVK related?

### ISSUE THREAD

**Issue by jarrard** [doitsujin/dxvk#269]
Wanting to post this issue to get feedback from other KCD users, basically this game runs pretty good, EXCEPT there have been issues on load screens going into infinite loading or freezing. 

I have had a issue where the BAR cutscene freezes the game or my PC (only hard reboot possible), often it is just a blank screen as game prepares for the loading screen, I don't believe I have ever got to this loading screen. (at start of game)

I don't know whats going on here or if its a videocard or Ryzen 1600 related issue (C6 disabled). But it would be great if other KCD users could report their experiences with this game and if they have had odd freezes like this happen.

I'm thinking of doing some testing under Windows to see if DXVK is more stable in that situation, if it is then perhaps CPU or GPU thermal related issue?  I will get some log files sorted out also, but when the system freezes there may be nothing logged.

### Software information
Kingdom Come Deliverance, Medium settings, no FSAA or Blur

### System information
- GPU: 1080ti
- Driver: 390.48 & 396.24
- Wine version: 3.5 Staging & 3.7/3.8 Stagings
- DXVK version: 0.41 - 0.50+
- Ubuntu Maui Kernel 4.15 & Manjaro MATE/KDE
- Ryzen 1600 CPU with C6 state disabled (otherwise it just crashes non stop)

### Apitrace file(s)
- I've obtained a builtin wine trace file of the bar scene, preparing to upload it.
https://mega.nz/#!euhy1aIb!p_XpTrm4W8QlPW7m7fBFxGTXtphAWSQ42Ov0-TZtF6k

The bar scene is at the end, I quit the game once I confirmed the cut scene was rendering.

### Log files
- d3d11.log: [KingdomCome_d3d11.log](https://github.com/doitsujin/dxvk/files/1900694/KingdomCome_d3d11.log)
- dxgi.log: [KingdomCome_dxgi.log](https://github.com/doitsujin/dxvk/files/1900695/KingdomCome_dxgi.log)

**Comment by jarrard** [comment]
Ok I did some more testing with FPS set to 60, which doesn't seem to work for loading screens. However setting vsync on does limit loading screens to 60fps.

This did not resolve the issue with it crashing on the starter game bar scene where some people are having a discussion around the table, well that's what should happen. 

I did discover that the system isn't actually freezing, only the backbuffer or drawscreen whatever it is, is. I can Ctrl-F1 and login and reboot system **in the blind**. The screen is frozen on whatever KCD had up, in this case it was the initial blackscreen before the load icon appearance.

SO, there seems to be some sort of issue with DXVK crashing at this point, its very easy to test, just start a new game, after talking to your mother, go down to the town centre and head straight to the tavern, the cut scene will automatically trigger and this screen freeze will occur. 

Maybe it doesn't happen on other nvidia driver versions, or perhaps AMD cards are immune to this type of issue in KCD. More feedback needed. Again, no logs appear to be generated, I will look into that.

PS. e_VolumetricFog = 1 I believe causes flickering black squares on the screen.

**Comment by jarrard** [comment]
Added some log files, not sure how informative they are, I just left DXVK as default logging which seems to have most the modes turned on?

In these logs I these addition configurations set in the user.cfg (+exec user.cfg)

e_VolumetricFog = 1    (This is what I think causes the black squares on screen)

(The below are just tweaks to the ambient occlusion so it looks a bit better, I'd be surprised if that has a negative effect since the feature is enabled with or without these adjustments).
r_ssdo=1
r_ssdoAmountAmbient=1.42
r_ssdoAmountDirect=2
r_ssdoAmountReflection=2
r_ssdoHalfRes=2
r_ssdoRadius=0.1
r_ssdoRadiusMin=0.1
r_ssdoRadiusMax=0.1
e_svoTI_SSAOAmount=1.4
e_svoTI_SpecularAmplifier = 0.82
e_svoTI_DiffuseBias = -0.011
e_svoTI_TemporalFilteringBase = 1

**Comment by xpander69** [comment]
if you have a laptop/other pc and ssh running you can log into your machine to check logs like dmesg and stuff like that. i have used it few times to see that the driver crashed.

**Comment by jarrard** [comment]
I do have a laptop, might attempt that sometime. Not something I have really done before so it will be a NOOB experiment. Ultimately it be nice if other KCD owners chimed in about this issue but atm it seems very few have the game.

**Comment by xpander69** [comment]
i will try to find time to test this also. haven't tried with the last patch, but it was working fine before.

**Comment by jarrard** [comment]
Yes thought keep in mind the game appears to work fine (minus those block sq from efog) until you explore around and experience the bar talk cutscene, which does it every time for me. 

I can wander around forever and get into fights and even talk with father etc... and no issue, it just happens at that initialisation of the cut scene at the tavern. It's one of those issues people can easily miss if they don't truly spend time to play the actual game.

**Comment by doitsujin** [comment]
Works for me, but if you are getting a GPU hang there must be something wrong.

**Comment by jarrard** [comment]
Maybe fullscreen 4k has something to do with it, might do some window mode 1080p tests, and also test with playonlinux  (using Lutris atm).

**Comment by xpander69** [comment]
Confirming this issue. on 1440p high settings GTX 1070 396.18 drivers with old compiler enabled

this is what i get when i ssh into the machine and look for dmesg:

`[145447.467231] NVRM: GPU at PCI:0000:0a:00: 
GPU-617b1efe-512a-6598-6182-ba598a019f69
[145447.467233] NVRM: GPU Board Serial Number: 
[145447.467236] NVRM: Xid (PCI:0000:0a:00): 69, Class Error: ChId 004b, 
Class 0000902d, Offset 00000250, Data 000002ff, ErrorCode 0000000c`

looks like driver crash? 

at least pc doesnt freeze as i can kill the process from ssh with the command:
`pkill KingdomCome.exe`

everything returns to normal then

**Comment by xpander69** [comment]
Ok a little more digging. seems black screen happens when debug layers are enabled, doesnt matter if new or old compiler.

game starts fine with new compiler also just 2x slower perf and still freezes with music playing when going into tavern, same dmesg output

**Comment by jarrard** [comment]
Pretty sure I have tested it with debug layers disabled

**Comment by xpander69** [comment]
my english to describe things sucks, so i try better :)

**debug layers enabled:**
`__GL_NextGenCompiler=0`  black screen after initial videos when launching the game, menu music playing
`__GL_NextGenCompiler=1`  black screen after initial videos when launching the game, menu music playing

**debug layers disabled:**
`__GL_NextGenCompiler=0` goes into game - fps ~50 - black screen entering tavern, freezes, music still playing
`__GL_NextGenCompiler=1` goes into game - fps ~25 - black screen entering tavern, freezes, music still playing

**Comment by xpander69** [comment]
yeah so if i use __GL_NextGenCompiler=0 on the new driver its the same as with 390.48.

**Comment by jarrard** [comment]
But you can't get past that initial tavern scene also I assume?

**Comment by xpander69** [comment]
thats what i wrote yeah

**Comment by xpander69** [comment]
he has AMD afaik yeah.
Need someone else to get this confirmed also. We bought have Ryzen CPU's might be this is doing something to the nvidia driver why it locks up. someone with Intel CPU should test this also

**Comment by xpander69** [comment]
Its going offtopic but i have a Launch day ryzen 1700X, week 7 to be exact.  and im just fine with C6 enabled also since kernel 4.15, before that i had random lockups when idle. I dont seem to have the segfault issue also, i ran ryzen-kill.sh 2 times 4 hours in row and no segfault, though some suggest it might still happen when you run longer, anyway its quite un-realistical load for me anyway to worry about. But ryzen cpu's can behave weird with some game engines + wine combination, 1  good example is dunia engine games (Farcry 3, 4 and primal) where fps is locked down to 20 with ryzen no matter the settings, but once you disable half of the cores then the framerate is 3x up

**Comment by jarrard** [comment]
I say its something to do with DXVK and NVIDIA drivers, some bug, because it happens consistently at that specific tavern scene (likely also other scenes if we could ever get to them).

**Comment by martinprochazka** [comment]
Just trying KC:D with just released DXVK 0.42. I'm not sure what tavern scene are you guys talking about, but what happens to me is very often when I fast travel or go to sleep game just freezes and terminal is spamming

info:  DxgiVkPresenter: Recreating swap chain: 
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  1920x1080
err:   DxvkSwapchain::recreateSwapchain: Failed to recreate swap chain

It make the game absolutely unplayable because of the way saving in KC:D works. Otherwise the games runs "kinda" smoothly 30-40 fps, in more populated areas sometimes drops to 15-25. And it's a dope, can't wait to play it :smiley:  

Mint 18.3 Cinnamon, Wine 3.6, Nvidia GTX 960 - 390 driver, AMD A8 7600, Linux 4.13-ubuntu

**Comment by doitsujin** [comment]
Can't reproduce. The swap chain issues seem to be a common thing on Nvidia, but please don't ask me what's causing those.

**Comment by jarrard** [comment]
Yeah the introduction area tavern scene which has the 3 guys arguing about political stuff seems to affect NVIDIA users only. I have not tested past that point so I can't really be sure what happens when you sleep and save on NVIDIA cards.

**Comment by martinprochazka** [comment]
Oh, this scene! Well it didn't crash for me there. Does it crash with certain dialog choices there?

**Comment by xpander69** [comment]
for me it crashes right when i go near the tavern, loading screen coming up, i think there should be some "cinematic" or free camera stuff coming up? no idea, i can't even get to the point where it shows the tavern from inside, so i am unable to get pass that to do some further testing

**Comment by jarrard** [comment]
yeah same as xpander69

**Comment by jarrard** [comment]
I have since moved to a arched based distro (manjaro) and am running MATE desktop (kde/kwin has issues with NVIDIA cards) and compiled dxvk 0.42 from master manually and the same issue occurs.

I have 396.18 Nvidia drivers with the new compiler disabled along with wine 3.6 staging (pba patched version). Bit of a shame it wasn't some sort of configuration issue, this seems to be a serious problem for at least 10 series nvidia cards atm. 

Hope a solution is found eventually.

**Comment by jarrard** [comment]
I think I did download the master and not 0.42

**Comment by jarrard** [comment]
With latest master and wine3.8staging this game still locks up with nvidia cards, it seems to lock up the entire x server allot of the time but you can terminal in to fix it I hear, which isn't very practical! 

The lockup happens at the bar scene as always. I tried to do a apitrace under windows but it just has a black screen and runs at 0.5fps.

**Comment by jarrard** [comment]
I DID IT! I got a trace out of builtin wine, I loaded up a save file before the tavern and walked through and the cutscene worked, although it was around 1 frame per 3 seconds LMAO

Now the trace file is 25.2GB, is it worth doing a apitrace trim on the file (backing up original) or does that make it useless?   I can upload it to mega nz in a few packages I think.

**Comment by jarrard** [comment]
The crashing issue no longer happens for me with 0.60+ and Wine3.11Staging.

If I could get one other NVIDIA user to confirm that the game passes the first BAR cut-scene at the start village (just walk under the archway into seating area) then I will close this issue.
