### ISSUE TITLE
26bd31f3-f3d6-416b-9af0-b12cc89f9719. This is the name of the son I want to take down the ban 

### ISSUE THREAD

**Issue by Trizz4** [doitsujin/dxvk#2690]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/doitsujin/dxvk/wiki/Making-a-Trace.
Preferably record the trace on Windows, or wined3d if possible.

**Reports with no log files will be ignored.**

### Software information
Name of the game, settings used etc.

### System information
- GPU:
- Driver:
- Wine version: 
- DXVK version: 

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by Joshua-Ashton** [comment]
I think you should give your child a better name -- 26bd31f3-f3d6-416b-9af0-b12cc89f9719 is just not in this season.

**Comment by Trizz4** [comment]
?

‫בתאריך יום ב׳, 20 ביוני 2022 ב-13:33 מאת ‪Joshie‬‏ <‪
***@***.***‬‏>:‬

**Comment by Joshua-Ashton** [comment]
¿

**Comment by Trizz4** [comment]
So you take my ban off



‫בתאריך יום ב׳, 20 ביוני 2022 ב-13:33 מאת ‪Joshie‬‏ <‪
***@***.***‬‏>:‬

**Comment by Joshua-Ashton** [comment]
You're in the wrong place, we are nothing to do with bans from games.

**Comment by Trizz4** [comment]
What? What is



‫בתאריך יום ב׳, 20 ביוני 2022 ב-13:51 מאת ‪Joshie‬‏ <‪
***@***.***‬‏>:‬

**Comment by Trizz4** [comment]
This is my son's name Can you download it for me? In FIEVM



‫בתאריך יום ב׳, 20 ביוני 2022 ב-13:51 מאת ‪Joshie‬‏ <‪
***@***.***‬‏>:‬

**Comment by Joshua-Ashton** [comment]
We are not FiveM. DXVK does not even work with FiveM. We cannot help you.

**Comment by GreyXor** [comment]
> We are not FiveM. DXVK does not even work with FiveM. We cannot help you.

Hello, even with https://github.com/doitsujin/dxvk/pull/2516 ?
