### ISSUE TITLE
NieR Replicant framerate lock

### ISSUE THREAD

**Issue by SuperSamus** [doitsujin/dxvk#2691]
I will preface this by saying that I do not own the game.
Commit 12c51f1c3df70e220dd02754650a3226fe02c602 limited NieR Replicant's framerate to 60 fps, due to the fact that the initial version of the game didn't have a framerate lock despite not being meant to run at high refresh rates.
After an update, the game added a native (and terrible) framerate lock. So, in theory, DXVK's frame limiter has no purpose anymore. In fact, it is harmful to those who want to mod the game, since there are mods that allow to make the game properly work at high refresh rates.
In short (in theory):

- People who play the game vanilla will find DXVK's framerate limiter useless;
- People who want to mod the game will have to manually override DXVK's options.

Still, I don't know whether these mods are actually usable on Linux, and my assumption that DXVK's frame limiter has no use might be wrong. In the latter case, the best solution would then be to document the need of overriding DXVK's settings on places like [PCGamingWiki](https://www.pcgamingwiki.com/wiki/NieR_Replicant), [Special K's wiki](https://wiki.special-k.info/SpecialK/Custom/Replicant), or the (obsolete) [Nexus mod](https://www.nexusmods.com/nierreplicant/mods/3).

**Comment by doitsujin** [comment]
I deliberately kept the frame rate lock active by default since the built-in one doesn't really work as intended. Since the game is unplayable at higher frame rates anyway, I don't really see a problem, and if you go out of your way to install mods that fix this you can probably also create your own dxvk.conf to disable the FPS limiter.

**Comment by SuperSamus** [comment]
> the built-in one doesn't really work as intended.

Both PCGamingWiki and Special K say that the built-in limiter caps the framerate at 57-58 FPS, which is less than 60. That's why I'm assuming that DXVK's frame limiter doesn't do anything.

I repeat:
- If the vanilla experience is improved by having DXVK's frame limiter, I agree that it should be kept, since the vanilla experience has priority over the mod experience (and I'll add documentation for Linux users on the mod).
- If the vanilla experience is exactly the same, then there is no reason to keep DXVK's limiter, since it hinders mods users.

So: is the vanilla experience (with the game FPS limiter) improved by DXVK's frame limiter?

**Comment by doitsujin** [comment]
> That's why I'm assuming that DXVK's frame limiter doesn't do anything (since it's set to cap it at 60 FPS).

Yes, but it can be disabled via the configuration file that the game provides.

**Comment by SuperSamus** [comment]
The problem in my opinion isn't about capping the framerate by default, the problem is that this behavior is **hidden**. 

I know about the configuration file, but if someone is looking to cap the framerate to 60 stable FPS, they are going to read a guide that says: "Unlock the game's framerate (by either using the configuration file or downgrading it), then add your own framerate limiter. You *must* put a framerate limiter, otherwise the game will not run properly!". No one is going to skip the second step, because they won't know that DXVK is already putting one.

To recap, if DXVK's limits the framerate "invisibly", it:

- Changes nothing to vanilla users.
- Changes nothing to people who want a stable 60 FPS, because they were already going to cap it manually (since they didn't know about it).
- Users who wanted to use mods to uncap the framerate will find the game capped at 60 FPS for seemingly no reason, and will have to investigate why (since there is no documentation), because they don't know about this hidden frame limiter. And maybe they won't even find out why.

So, if I didn't make it clear, that's the problem I have about it.

(And having documentation being different between Linux and Windows isn't worth it in this case.)

**Comment by Kaldaien** [comment]
Agreed, this is very problematic.

I know -of- the existence of forced framerate limits in various games, but I do not know how to disable it. It's not clearly documented anywhere, it's just a bit of random trivia that I know about as the developer of mods for NieR: Automata and Replicant, that DXVK is a major obstacle for no reason.

**Comment by Blisto91** [comment]
The cap was removed in 2.4 https://github.com/doitsujin/dxvk/pull/3942
