### ISSUE TITLE
[D3D9] One Piece Pirate Warriors 3 shadow bug

### ISSUE THREAD

**Issue by wwsnkneo** [doitsujin/dxvk#2693]
For starters, thank you very much. Because it's thanks to this project that it's possible to fix many bugs that happen when using an AMD GPU in this game (in Treasure Events and Cutscenes). However, when DXVK corrects some things but shadows end up with bugs, as shown in the images I will leave below.

1 - [https://i.imgur.com/meCJB9L.png](https://i.imgur.com/meCJB9L.png)
2 - [https://i.imgur.com/6fEyFHp.png](https://i.imgur.com/6fEyFHp.png)
3 - [https://i.imgur.com/MR2R5wU.png](https://i.imgur.com/MR2R5wU.png)
4 - [https://i.imgur.com/txI0XS4.png](https://i.imgur.com/txI0XS4.png)

### **Software Information:**

One Piece Pirate Warriors 3 - D3D9
DXVK-Async 1.10.1

### **System Information:**

- GPU: RX 570 4GB
- Driver: 22.5.1
- Windows 10 21H2

### **Log:**

[oppw3_d3d9.log](https://github.com/doitsujin/dxvk/files/8970420/oppw3_d3d9.log)

### **Trace:**

[https://drive.google.com/file/d/1ocmehfbccW3f-HaQeuSOhJ4I_d9Swp2h/view?usp=sharing](https://drive.google.com/file/d/1ocmehfbccW3f-HaQeuSOhJ4I_d9Swp2h/view?usp=sharing)

**Comment by Blisto91** [comment]
> I didn't put a trace because in it the problem does not reproduce.

That is normal and expected. The trace doesn't run with dxvk, it just tries to capture all directx api calls. The devs can then replay the trace on Linux with or without dxvk to look into the issue.
So if you could make one that would be great.

**Comment by wwsnkneo** [comment]
> > I didn't put a trace because in it the problem does not reproduce.
> 
> That is normal and expected. The trace doesn't run with dxvk, it just tries to capture all directx api calls. The devs can then replay the trace on Linux with or without dxvk to look into the issue. So if you could make one that would be great. Just get ingame where it would normally reproduce.

All right then. I post the trace in the main post.

**Comment by WWSNK** [comment]
I updated my driver (to the beta versions) and updated to the lastest version of DXVK and i think the problem is gone. Thanks a bunch.

[https://i.imgur.com/x1sI0Ue.png](https://i.imgur.com/x1sI0Ue.png)

**Comment by Blisto91** [comment]
I still see it in the trace with dxvk master and a mesa git from yesterday. So not fixed for me.
