### ISSUE TITLE
Batman: Arkham Knight massive FPS loss when looking into specific directions

### ISSUE THREAD

**Issue by lextra2** [doitsujin/dxvk#2695]
With the PC Performance Test (built-in benchmark) during specific sections, the FPS drops massively, from around 70 to around 40.

OS: WIndows 10 21H2
GPU: AMD Radeon RX 5700 - Drivers 22.5.2 WHQL
CPU: AMD Ryzen 9 3900X

The following graphic settings were used:
![batman](https://user-images.githubusercontent.com/20690384/175793494-ac9ac91c-64ae-49d5-8430-429c9be915b8.png)

Note: Does not happen with Native DX11 and disabling Gameworks Enhanced Rain & Light Shafts does NOT make a difference.

[Here is a RenderDoc capture](https://drive.google.com/file/d/1d7lf-tXZmlMKOgBeJFc1rHQWHt-zqpT9/view?usp=sharing)

**Comment by K0bin** [comment]
Renderdoc captures aren't portable. They can only be replayed on a system with a GPU of the same architecture and the same driver.

**Comment by doitsujin** [comment]
Yes, drawing 10000 objects when looking in one direction is slower than drawing 3000 objects when looking elsewhere. This is normal and has happened in literally every 3D game ever made that doesn't have an FPS cap.

**Comment by doitsujin** [comment]
> Does not happen with Native DX11

DXVK isn't native D3D11, and AMD's new driver is expected to outperform our implementation in almost all situations. You're also running it on a driver that is **known** to perform poorly in GPU-bound scenarios.

**Comment by lextra2** [comment]
> DXVK isn't native D3D11

Yes. I know. My point is, this performance degredation only happens with DXVK

> and AMD's new driver is expected to outperform our implementation in almost all situations.

I wouldn't bet on AMD backporting their driver improvements for RDNA1 gpus

> You're also running a Vulkan driver that is **known** to perform poorly with DXVK especially in GPU-bound scenarios.

So you are saying, vulkan on windows is inferior to vulkan on linux?

**Comment by K0bin** [comment]
> So you are saying, vulkan on windows is inferior to vulkan on linux?

On AMD GPUs: Yes, absolutely. On Nvidia GPUs it's practically identical.

**Comment by lextra2** [comment]
> 

Thanks for the info.
