### ISSUE TITLE
Call of Duty: Black Ops III has GPU usage and FPS spikes on the main menu.

### ISSUE THREAD

**Issue by tpurde** [doitsujin/dxvk#2697]
This problem only happens on the main menu, where you start a game, choose gamemode or custommize weapons. The same thing does not happen with the Options menu in game, nor do the lag spikes happen in game. Just the menu. Tried the game both with Glorious Eggroll's Proton version 7-22 and Proton 7.0-3, with the same results. My DXVK logs are going to be from Proton-GE, due to it being the best Proton version to play Black Ops 3. The spikes are that the GPU usage jumps from around 50% to 10% regularly, such as every 5 or so seconds.

### Software information
Call of Duty: Black Ops III, tested with Fsync both enabled and disabled, tested with Feral's Gamemode both enabled and disabled, no change in result.

### System information
- GPU: Geforce GTX 1050ti
- Driver: 515.48.07
- Wine version: Wine Staging 7.0
- DXVK version: v1.10.1-async

### Apitrace file(s)
Couldn't create one for now, I can do it later if absolutely needed.

### Log files
- d3d11.log: 
[BlackOps3_d3d11.log](https://github.com/doitsujin/dxvk/files/8998476/BlackOps3_d3d11.log)

- dxgi.log:
[BlackOps3_dxgi.log](https://github.com/doitsujin/dxvk/files/8998477/BlackOps3_dxgi.log)

**Comment by K0bin** [comment]
> Couldn't create one for now, I can do it later if absolutely needed.

It is needed.

**Comment by tpurde** [comment]
> > Couldn't create one for now, I can do it later if absolutely needed.
> 
> It is needed.

Alright, if I may ask, what should I do to create it on Proton?

And a quick note, WineD3D does not work with the game, so I have to do it with DXVK.

**Comment by K0bin** [comment]
Proton & DXVK is fine.

**Comment by tpurde** [comment]
Alright then. Again, how exactly am I going to use it with Proton?

**Comment by K0bin** [comment]
https://github.com/doitsujin/dxvk/wiki/Making-a-Trace

**Comment by tpurde** [comment]
Here is the link for the Apitrace: https://drive.google.com/file/d/17hcXdecAuEy00cLtIVe6Wsp2LjX-U-QJ/view?usp=sharing

**Comment by tpurde** [comment]
Just a quick note, this issue seems to be marked as d3d9 but I think the game runs on DirectX 11. Was that intentional?

**Comment by KagoraTheGrindcoreAddict** [comment]
This issue is related to the a steam client update and the game constantly pinging the servers to check for DLC, if you install all DLC (this includes the gamemodes multiplayer/campaign/zombies) the stutters stop and I can confirm this is the case.

There is a huge thread about it here
https://steamcommunity.com/app/311210/discussions/0/5135803832916918329/

**Comment by tpurde** [comment]
Well that might be it. I only have Zombies and it's DLC's installed. Going to try out now.

**Comment by tpurde** [comment]
You are correct, @KagoraTheGrindcoreAddict. Installing all the DLCs fixed the issue. Closing, as it is not DXVK related.
