### ISSUE TITLE
Graphic tearing on I/O

### ISSUE THREAD

**Issue by Nerus87** [doitsujin/dxvk#2699]
When the game loading the world, starts tearing a lite bit (it is annoyed thing).
It looks like I/O block the rendering queue (waiting for loading?).
This problem not exists natively.

### Software information
ESO, other games have same effect

### System information
- Platform: Windows
- GPU: MSI Radeon 6900 XT
- Driver: 22.5.2
- Wine version: N/A
- DXVK version: dxvk-1.10.1

### Apitrace file(s)
N/A

### Log files
- [eso64_d3d11.log](https://github.com/doitsujin/dxvk/files/9000126/eso64_d3d11.log)
- d3d11.log: N/A
- [eso64_dxgi.log](https://github.com/doitsujin/dxvk/files/9000125/eso64_dxgi.log)

**Comment by K0bin** [comment]
> VK_PRESENT_MODE_FIFO_KHR

DXVK enables vsync, if there's still tearing, then your graphics driver and/or the Windows compositor messed up.

**Comment by Blisto91** [comment]
@Nerus87 Friendly ping

**Comment by K0bin** [comment]
I don't exactly understand the problem. As I wrote earlier, the logs show that DXVK enables vsync. Anything else is outside of our control anyway.

**Comment by Nerus87** [comment]
To be honest after last update of DXVK i can't reproduce problem :)
So can be closed.
