### ISSUE TITLE
Building error: dxgi presenter

### ISSUE THREAD

**Issue by onassif** [doitsujin/dxvk#270]
I'm trying to build dxvk but am getting errors:

In file included from ../../src/dxgi/dxgi_presenter.cpp:5:0:
src/dxgi/dxgi@sha/dxgi_presenter_frag.h:3:16: error: stray ‘@’ in program
 const uint32_t @BASENAME@[] = {
                ^
src/dxgi/dxgi@sha/dxgi_presenter_frag.h:3:25: error: stray ‘@’ in program
 const uint32_t @BASENAME@[] = {
                         ^
In file included from ../../src/dxgi/dxgi_presenter.cpp:6:0:
src/dxgi/dxgi@sha/dxgi_presenter_vert.h:3:16: error: stray ‘@’ in program
 const uint32_t @BASENAME@[] = {
                ^
src/dxgi/dxgi@sha/dxgi_presenter_vert.h:3:25: error: stray ‘@’ in program
 const uint32_t @BASENAME@[] = {
                         ^
src/dxgi/dxgi@sha/dxgi_presenter_vert.h:3:27: error: redefinition of ‘const uint32_t BASENAME []’
 const uint32_t @BASENAME@[] = {
                           ^
In file included from ../../src/dxgi/dxgi_presenter.cpp:5:0:
src/dxgi/dxgi@sha/dxgi_presenter_frag.h:3:17: note: ‘const uint32_t BASENAME [257]’ previously defined here
 const uint32_t @BASENAME@[] = {
                 ^~~~~~~~
../../src/dxgi/dxgi_presenter.cpp: In member function ‘dxvk::Rc<dxvk::DxvkShader> dxvk::DxgiPresenter::createVertexShader()’:
../../src/dxgi/dxgi_presenter.cpp:377:38: error: ‘dxgi_presenter_vert’ was not declared in this scope
     const SpirvCodeBuffer codeBuffer(dxgi_presenter_vert);
                                      ^~~~~~~~~~~~~~~~~~~
../../src/dxgi/dxgi_presenter.cpp: In member function ‘dxvk::Rc<dxvk::DxvkShader> dxvk::DxgiPresenter::createFragmentShader()’:
../../src/dxgi/dxgi_presenter.cpp:387:38: error: ‘dxgi_presenter_frag’ was not declared in this scope
     const SpirvCodeBuffer codeBuffer(dxgi_presenter_frag);
                                      ^~~~~~~~~~~~~~~~~~~

### System information
- GPU: gtx 1060
- Driver: 384.111
- Wine version: 3.5
- DXVK version: master-654e9e6
- OS: Ubuntu 17.10

**Comment by doitsujin** [comment]
Hm, apparently it doesn't compile the GLSL shaders properly. What Meson version are you using?

**Comment by onassif** [comment]
Here's what the ./package-release.sh configures:
The Meson build system
Version: 0.42.1
Source dir: /home/onassif/_repos/dxvk
Build dir: /home/onassif/_repos/dxvk/dxvk-master/build.64
Build type: cross build
Project name: dxvk
Native C compiler: ccache cc (gcc 7.2.0)
Cross C compiler: /usr/bin/x86_64-w64-mingw32-gcc (gcc 6.3.0)
Native C++ compiler: ccache c++ (gcc 7.2.0)
Cross C++ compiler: /usr/bin/x86_64-w64-mingw32-g++ (gcc 6.3.0)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Build machine cpu family: x86_64
Build machine cpu: x86_64
Library vulkan-1 found: YES
Library d3d11 found: YES
Library dxgi found: YES
Library d3dcompiler_47 found: YES
Program glslangValidator found: YES (/usr/local/bin/glslangValidator)
Dependency threads found: YES
Configuring setup_dxvk.sh using configuration

**Comment by doitsujin** [comment]
Yeah, that's outdated, I think DXVK requires at least 0.43. Please try to get your hands on a more recent version (it's currently at 0.45 afaik).

**Comment by onassif** [comment]
Thanks, building worked with meson 0.46
