### ISSUE TITLE
Onechanbara Z2: Chaos missing effects

### ISSUE THREAD

**Issue by ShinyaOsen** [doitsujin/dxvk#2701]
Weapon, healing, money orbs, and quick time event prompts do not render. Works with wined3d but stuff get rendered in front of objects that should obscure the object

Windows
![20220701021959_1](https://user-images.githubusercontent.com/49567246/176836963-4ce1c79c-6e2e-40a2-801e-50afd561e353.jpg)
![20220701022249_1](https://user-images.githubusercontent.com/49567246/176836982-2eca5990-b398-4e3c-85ec-e6976658ca97.jpg)

DXVK
![20220701020838_1](https://user-images.githubusercontent.com/49567246/176835137-b5e0125c-45a8-42b1-a502-3fbccf09b854.jpg)
![20220701021126_1](https://user-images.githubusercontent.com/49567246/176835096-2d8fe95a-bcd3-4abb-8be1-51f8598e440d.jpg)

### Software information
Onechanbara Z2: Chaos
Fullscreen 1920x1080

### System information
- GPU:Vega 56
- Driver: Mesa 22.1.2
- Wine version: Proton 7.0-3
- DXVK version: 1.10.1 and dxvk-master-e81094533

### Apitrace file(s)
Done on windows
https://drive.google.com/file/d/12T8acPDT9V6Q5Dd4CK04yD2NmMlVdx12/view?usp=sharing

### Log files
- d3d9.log:[OnechanbaraZ2_d3d9.log](https://github.com/doitsujin/dxvk/files/9026502/OnechanbaraZ2_d3d9.log)
- d3d11.log:[OnechanbaraZ2_d3d11.log](https://github.com/doitsujin/dxvk/files/9026504/OnechanbaraZ2_d3d11.log)
- dxgi.log:[OnechanbaraZ2_dxgi.log](https://github.com/doitsujin/dxvk/files/9026511/OnechanbaraZ2_dxgi.log)

**Comment by doitsujin** [comment]
The game uses an uninitialized depth buffer for its particle rendering pass, so all the data in it is zero and the depth test always fails. It's broken the same way on wined3d's Vulkan backend as on DXVK.

Not sure why this works on Windows. Even if we're supposed to initialize D24S8 depth buffers to a different value then this cannot work correctly, and at best I'd expect the same results as on Wine's OpenGL backend.
