### ISSUE TITLE
PAYDAY 2 blackscreen for a while, then crashes

### ISSUE THREAD

**Issue by JasonSlav** [doitsujin/dxvk#2702]
### Software information
PAYDAY 2 latest version, lowest settings except for:
resolution: 1280x720
use hq weapons
frame rate limit: 60
streaming chunk: 1024

also i used 4gb patcher [here,](https://ntcore.com/?page_id=371) but it doesn't matter which exe i use.

### System information
- GPU: GTX 950M
- Driver: 516.40
- Wine version: -
- DXVK version: 1.10.1

### Apitrace file(s)
https://drive.google.com/file/d/1ERcQSTF8IW2RucWozZvoYA9xJBwz2X4J/view?usp=sharing

### Log files
- d3d9.log: https://drive.google.com/file/d/1WKDm8nSFCLc1L7AmdC8wwAnc--2UIayj/view?usp=sharing
- d3d11.log: -
- dxgi.log: -

**Comment by Blisto91** [comment]
I haven't been able to reproduce this with my amd R9 380 on windows. It sounds a bit like this issue https://github.com/doitsujin/dxvk/issues/2336 which is wasn't able to reproduce either.

Can you check if the latest master build helps you? You can find a down load of it here. https://github.com/doitsujin/dxvk/actions/runs/2601899023

**Comment by JasonSlav** [comment]
> I haven't been able to reproduce this with my amd R9 380 on windows. It sounds a bit like this issue #2336 which i wasn't able to reproduce either.
> 
> Can you check if the latest master build helps you? You can find a download of it here. https://github.com/doitsujin/dxvk/actions/runs/2604934947

its the same blackscreen, then crashing without any error messages. here's the log:
[payday2_win32_release_d3d9.log](https://github.com/doitsujin/dxvk/files/9035625/payday2_win32_release_d3d9.log)

**Comment by JasonSlav** [comment]
oh my god, sorry im new to github 🤦

**Comment by Blisto91** [comment]
Oh i just noticed according to the log above that your driver version is 398.140.0 not 516.40. then that new version i gave you won't work.
Could you try updating your driver to the latest version? 🙂

**Comment by Blisto91** [comment]
Glad to hear it. I wasn't actually convinced that would do it 😁

**Comment by Blisto91** [comment]
@JasonSlav Would you be able to test something for me?

Could you try if it also works with this build https://github.com/doitsujin/dxvk/actions/runs/2605265029
This is from the 1.10.x branch for a new point release that doesn't include all the latest master changes. I'm curios if the commit that fixed it is also included there or is unique to the master branch.
