### ISSUE TITLE
[d3d9] Shogun 2 crash on battle exit

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#2703]
In dx9 mode shogun 2 can or will crash on battle exit if Terrain Quality is set to high.
It does not matter if all other setting are off or low, just that Terrain Quality is set to High. Doesn't happen with the setting set to low.
First discovered in https://github.com/doitsujin/dxvk/issues/2591 but i don't think it is directly related to that issue.

Way to reproduce
1. Start shogun 2 in dx9 mode
2. Make sure Terrain Quality is set to High
3. Go to historical battles and start Toba Fushimi
4. Once in the battle press escape and Concede Defeat
5. Observe crash before you get back to menu

If it doesn't crash the first time then try again.
Doesn't happen in wined3d

### Software information
Shogun 2 Terrain Quality High

### System information
- GPU: R9 380
- Driver: 1 week old mesa-git
- Wine version: Proton 7.0-3 
- DXVK version: Latest unmap branch (doesn't help). Also happens on 1.10.1

### Apitrace file(s)
Apitrace pending

### Log files
[Shogun2_d3d9.log](https://github.com/doitsujin/dxvk/files/9033618/Shogun2_d3d9.log)
[Shogun2_d3d11.log](https://github.com/doitsujin/dxvk/files/9033619/Shogun2_d3d11.log)
[Shogun2_dxgi.log](https://github.com/doitsujin/dxvk/files/9033621/Shogun2_dxgi.log)

Errors can also be seen at the end of the proton log
[steam-34330.log](https://github.com/doitsujin/dxvk/files/9033625/steam-34330.log)

**Comment by K0bin** [comment]
This is caused by running out of address space.

Curiously, it's not buffers or constants that cause it (partially because we are already doing a bunch of tricks to avoid that) but StateBlocks instead.

![image](https://user-images.githubusercontent.com/1131720/216778406-7e5161e2-030b-4827-9ad0-1f1669b2c83e.png)

> warn:  state blocks: 8314 memory of one: 190616 memory of state: 188792 total (MB): 1511

**Comment by K0bin** [comment]
Fixed by #3248
