### ISSUE TITLE
Spellforce platinum edition crash on save

### ISSUE THREAD

**Issue by 234523413432634** [doitsujin/dxvk#2710]
Game crashes when autosaving(with ESC button), quicksaving(F7) and on manual save. Happens both on windows and linux.

With dxvk 1.5.4 the game doesn't crash, but savegame preview is a black square.
Also on linux framerate is very low if i don't constantly move the cursor.

### Software information

Spellforce: Platinum Edition steam

### System information
- GPU: rx5700xt
- Driver: 22.10.01.03 on windows / Mesa 22.0.1 on linux
- Wine version: Proton GE 7-24
- DXVK version: 1.10.1

### Apitrace file(s)
Windows: https://drive.google.com/file/d/1PJis9yE40_K-85_cEfd73kr39xamYXPm/view?usp=sharing

### Log files

- d3d9.log: [SpellForce_d3d9.log](https://github.com/doitsujin/dxvk/files/9078842/SpellForce_d3d9.log)

**Comment by Blisto91** [comment]
Hi there.
Could you quickly check if anything changes with this build.
https://github.com/doitsujin/dxvk/actions/runs/2641529958

**Comment by K0bin** [comment]
That PR should fix it.

**Comment by 234523413432634** [comment]
That fixed the crashing for me. However, this brought another problem - RDNA cards don't render some interface elements in spellforce(healtbars, manabars, circles around selected units etc.) on windows with native d3d9.
Previous versions of DXVK fixed this, but dxvk with crash fix makes parts of the interface disappear again both on windows and linux.

**Comment by Blisto91** [comment]
In which version did it used to work? 1.10.1?
Are those elements displayed in the trace and can you provide screenshots.

**Comment by K0bin** [comment]
Please add some screenshots of what it looks like with DXVK and what it should look like.

**Comment by 234523413432634** [comment]
Here is how it looks in 1.10.1 - all hud elements working as they should
![20220710173800_1](https://user-images.githubusercontent.com/108991310/178149707-b06ef12c-3048-4299-8f28-99f22880ed41.jpg)
Here is how it looks with dxvk from spellforce branch. It also looked like that when i was making a trace on windows.
![20220710173954_1](https://user-images.githubusercontent.com/108991310/178149787-a65c98e4-3a3e-41f8-a877-832af41c2121.jpg)

**Comment by K0bin** [comment]
Your apitrace never has those health bars. It ends pretty much immediately after the cutscene.

**Comment by 234523413432634** [comment]
Should i make another one where i select a unit with a healthbar after a cutscene?

**Comment by K0bin** [comment]
I've already identified an issue. I hope that's also what causes the missing health bars.

For reference in the future:

This is a regression caused by the null descriptor changes. Before that we used the resource-bound spec constant to get the value 0, 0, 0, 1 for unbound resources. Now we sample the null descriptor and get the value 0, 0, 0, 0.

**Comment by K0bin** [comment]
I've updated the PR with a fix for the missing UI elements.

**Comment by 234523413432634** [comment]
Quickly checked it on linux and windows - UI is now displayed correctly and the game doesn't crash when saving.
I didn't expect to get a complete fix in just a day. Thank you very much!)
