### ISSUE TITLE
Assassin's Creed Origins Freezes since the 1.6 update

### ISSUE THREAD

**Issue by smintman** [doitsujin/dxvk#2712]
Ever since the Assassins creed origins update to 1.6, the game is unplayable. The game will randomly freeze after a few mins and must be forced quit. 

The audio continues to play when the game freezes. 

Note: The same issue appears to affect Windows 7 users, but windows 10 users don't have any issues? Issue has been reported to [Ubisoft](https://discussions.ubisoft.com/topic/161188/tu-1-6-0-experiencing-crashes-freezes-when-playing-assassin-s-creed-origins-on-steam-deck-post-here?lang=en-US), but its been about 1 month since the issue happened and there has been no fix.

The issue can sometimes happen when the game is starting, but it does seem to happen when there is a lot happening on the screen. Sometimes you can go into the game and if you dont move then the game does not crash, but if you start moving about then the game will eventually freeze.

I'm using the version of the game bought via ubisoft connect, but the same issue affects the version available on steam.

My feelings are that when they built the game they introduced some dependency on an api or something only available on windows 10? 

### System information (Steam deck)
- GPU: AMD Custom GPU 0405 
- Driver: 
- Wine version: Proton 7.03 or Experimental (Bleeding edge) Also tried Proton GE various versions
- DXVK version: ??

### Log files
- d3d9.log:
[ACOrigins_d3d9.log](https://github.com/doitsujin/dxvk/files/9082342/ACOrigins_d3d9.log)

- d3d11.log:
[ACOrigins_d3d11.log](https://github.com/doitsujin/dxvk/files/9082348/ACOrigins_d3d11.log)

- dxgi.log:
[ACOrigins_dxgi.log](https://github.com/doitsujin/dxvk/files/9082352/ACOrigins_dxgi.log)

**Comment by smintman** [comment]
If there is anything else I can provide or you want me to try please let me know, there are lot of people waiting on a fix for this issue. Lots of reports in [Steam support forum](https://steamcommunity.com/app/582160/discussions/1/) and ubisoft forum etc.. its such a same because the game worked amazingly on the previous 1.5.1 version of the game!

**Comment by Blisto91** [comment]
It doesnt necessarily sound like this is a dxvk issue, but to try and get some more details could you try a couple of things?
If possible launch game with wined3d and see if the issue persists.
```
PROTON_USE_WINED3D=1 %command%
```

You can also try turning off fsync and esync
```
PROTON_NO_FSYNC=1 PROTON_NO_ESYNC=1 %command%
```

**Comment by smintman** [comment]
PROTON_USE_WINED3D=1 apart from looking and performing awful, yes it did freeze when I did that.

PROTON_NO_FSYNC=1 PROTON_NO_ESYNC=1  Does the same

I'm on the steam deck beta channel..

So does using PROTON_USE_WINED3D=1 rule out dxvk?

**Comment by Blisto91** [comment]
Most likely i would say yes. 
For the dxvk devs to look into it (if they don't have it ready themselves that is) they would need [a apitrace if you could provide that](https://github.com/doitsujin/dxvk/wiki/Making-a-Trace).

Do you have a setup with windows 10? If so try installing the game there and use it along with dxvk and see if the same issue occurs.

**Comment by doitsujin** [comment]
I do have the game and might give it a test later, but if it freezes in the exact same way on wined3d, and only started doing so since a game patch that most likely *did not* touch the D3D11 rendering code in any meaningful way, it's highly unlikely to be our bug.

**Comment by smintman** [comment]
Ok understood thanks for your help.

**Comment by Blisto91** [comment]
Most reports on protondb are with Amd or steam decks. Tho there's a few NVidia ones that seem to indicate the same issue, so shouldn't be GPU specific from what I'm observing.

**Comment by enigmaxg2** [comment]
> Most reports on protondb are with Amd or steam decks. Tho there's a few Nvidia ones that seem to indicate the same issue, so shouldn't be GPU specific from what I'm observing.

I'm on a GTX 1060 3GB, and running KDE Neon, the game worked almost flawless before but since 1.6.0 I have the same freezing issue (sometimes when loading, sometimes after 2 mins of gameplay, or after 5...)

**Comment by Blisto91** [comment]
@enigmaxg2 looks like they are figuring something in the proton issue. https://github.com/ValveSoftware/Proton/issues/928#issuecomment-1180913739

**Comment by doitsujin** [comment]
Seems like there's a wine fix for this: https://gitlab.winehq.org/wine/wine/-/merge_requests/427
