### ISSUE TITLE
[Questions] Very Stuttering Shaders Compiling Process?

### ISSUE THREAD

**Issue by 0-Satanael** [doitsujin/dxvk#2713]
I Just Got A Couple of Questions
1- Any possibility in the future to implement Async Compiling or something similar for faster performance?
2- any idea how to make DXVK keep compiled shaders instead of re-compiling them every time i close and open the game?
3- does dxvk got a config file which i can play around with?

### Software information
God of War Highest Preset @ 1080p [Directx 11]

### System information
- CPU: Ryzen 1600x
- GPU: RTX 3060 Ti
- Driver: 512.95
- OS : Windows 11 21H2 build 22000.778
- DXVK version: 1.10.1

### Log files
sorry i don't have a log file because i uninstalled the game and re-downloading it gonna take forever due to limited quota In my country.

**Comment by K0bin** [comment]
It's not that we don't want people to use DXVK but if you're using Windows with a Nvidia GPU, you should just use the regular D3D11 driver. It'll most likely be faster. Especially in God of War.

**Comment by doitsujin** [comment]
> Any possibility in the future to implement Async Compiling or something similar for faster performance?

Yes, an upcoming version of DXVK (**not** 1.10.2) will have a solution to that problem.

> any idea how to make DXVK keep compiled shaders instead of re-compiling them every time i close and open the game?

This shouldn't happen since the Nvidia driver should already be caching our Vulkan shaders.

**Comment by Blisto91** [comment]
About the third question, yes you can create file called `dxvk.conf` and put it next to the games exe. (Usually)
It's options with the default values are listed here https://github.com/doitsujin/dxvk/blob/master/dxvk.conf
Either check the logs for the uncommented config option to see if they are picked up. Or enable the hud and verify it shows `dxvk.hud = 1` to know if it's in the correct spot.

Tho it's only meant to be used for games that have issues and won't help with shader stutter.

**Comment by VladWinner** [comment]
> Any possibility in the future to implement Async Compiling or something similar for faster performance?

@0-Satanael You mean this patch? https://github.com/Sporif/dxvk-async

> if you're using Windows with a Nvidia GPU, you should just use the regular D3D11 driver

@K0bin not always. Here is an example with MWR H1-Mod [d3d11]:
![image](https://user-images.githubusercontent.com/13555921/178486287-ef474c47-e5bf-4116-9489-5f2f981798c9.png)

**Comment by K0bin** [comment]
@VladWinner God of War is the complete opposite though. It's easily 20-30% slower on Nvidia GPUs with DXVK.

**Comment by 0-Satanael** [comment]
alright thanks to all of you i will go ahead and close this ticket.
