### ISSUE TITLE
wiki update for apitrace

### ISSUE THREAD

**Issue by okias** [doitsujin/dxvk#2719]
New version 11.1
Also instead of using not so effective xz, please rather point users to using `apitrace repack -b` which enable brotli compression (or see https://github.com/apitrace/apitrace/issues/656#issuecomment-621347127 for other compression algo recomendations)

**Comment by Riesi** [comment]
I tried the repack feature a bit and it seems that `apitrace repack --brotli=2 <input>.trace <output>.trace` is a good compromise. The default compression level is extremely slow and this setting was fast and halved the trace size.

@K0bin maybe add something like this to the apitrace section in the wiki:
``` 
Compress the .trace file by either utilizing `apitrace repack --brotli=2 <input>.trace <output>.trace` (can be done with the Linux version) or with an external tool in a common file format like `.tar.xz`. Then share it using a common file sharing service like Google Drive or Mega.
```

**Comment by K0bin** [comment]
Done.

https://github.com/doitsujin/dxvk/wiki/Making-a-Trace

**Comment by Riesi** [comment]
yeah the apitrace version to download is outdated in the windows section

**Comment by K0bin** [comment]
Done.
