### ISSUE TITLE
Typo on Wiki page for driver support

### ISSUE THREAD

**Issue by CorruptComputer** [doitsujin/dxvk#2720]
https://github.com/doitsujin/dxvk/wiki/Driver-support

> The general recommendation to avoid issues is to keep your drivers up to date as much as possible, **regardless or vendor**, in order to reduce the risk of running into driver bugs.

should be

> The general recommendation to avoid issues is to keep your drivers up to date as much as possible, **regardless of vendor**, in order to reduce the risk of running into driver bugs.

I would have just edited and fixed this myself, but it seems that editing the wiki is disabled for non-members of the repo.

**Comment by doitsujin** [comment]
fixed.
