### ISSUE TITLE
DXVK NOT WORK ON VULKAN 1.2 GPU?

### ISSUE THREAD

**Issue by Nerboruto** [doitsujin/dxvk#2727]
DXGI LOG
info:  Game: valley.exe
info:  DXVK: v1.10.1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  Skipping Vulkan 1.2 adapter: Quadro K420
warn:  DXVK: No adapters found. Please check your device filter settings and Vulkan setup.

**Comment by MuaDib1988** [comment]
Hi, I think you should provide more data. 
your driver version? 
which GPU?
....

**Comment by Blisto91** [comment]
As said above please provide some more information about your setup.

If you have `inxi` installed then post a log from `inxi -GSC`
Or a system information report from steam (Steam -> Help -> System Information -> wait 15 seconds and copy)

Put them in a text file or a github gist.

**Comment by doitsujin** [comment]
Current master requires a Vlkan 1.3 capable driver and has required `VK_KHR_dynamic_rendering` for a while, which your driver also does not support.

Kepler GPUs are no longer supported.

**Comment by Nerboruto** [comment]
Microsoft Windows [Versione 10.0.19041.804]
KEPLER GPU K620 EQUIVALENT TO GT 710 
driver 472.98 
latest is 473.47 kepler is legacy gpu only security fix
old dxvk version work ... ok raise requirement...

**Comment by Nerboruto** [comment]
> Current master requires a Vlkan 1.3 capable driver and has required `VK_KHR_dynamic_rendering` for a while, which your driver also does not support. Kepler GPUs are no longer supported.
> 
> You can use DXVK 1.10.2, but future versions will no longer work.

it is not possible to leave the old path for cards that do not support this extension?
