### ISSUE TITLE
[Windows D3D9] Guitar Hero World Tour crash after intro videos (before main menu)

### ISSUE THREAD

**Issue by TheDeusDeceptor** [doitsujin/dxvk#2730]
Guitar Hero World Tour crash after intro videos (before main menu, right after it says to "press any button to continue")
Theres a mod called GHWT:Definitive Edition with its own .exe which loads with DXVK much further - into menu, but after you pick an instrument and move to songs setlist it crashes too

### Software information
Guitar Hero World Tour for PC (D3D9)

### System information
- GPU: RX 580 8gb
- Driver: 22.4.2
- DXVK version: 1.10.2
- Windows 10 21H2

### Apitrace file(s)
https://www95.zippyshare.com/v/AXbaRrfV/file.html
mirror: https://drive.google.com/file/d/17rc3-DNxEAsGo40Swc1ylS80JCoiMe-I/view?usp=sharing

### Log files
- d3d9.log: [GHWT_d3d9.log](https://github.com/doitsujin/dxvk/files/9128646/GHWT_d3d9.log)
[GHWT_Definitive_d3d9.log](https://github.com/doitsujin/dxvk/files/9128650/GHWT_Definitive_d3d9.log)

**Comment by Blisto91** [comment]
Hi there.
Your trace link doesn't appear to be working for me. It just writes `403 Forbidden`

**Comment by TheDeusDeceptor** [comment]
> Hi there. Your trace link doesn't appear to be working for me. It just writes `403 Forbidden`
https://drive.google.com/file/d/17rc3-DNxEAsGo40Swc1ylS80JCoiMe-I/view?usp=sharing

**Comment by K0bin** [comment]
Logs indicate this is another case of #1318.

Try #2663

**Comment by K0bin** [comment]
This should be fixed now. Please reopen if it's not.

**Comment by TheDeusDeceptor** [comment]
> This should be fixed now. Please reopen if it's not.
Ive used build from here - https://github.com/doitsujin/dxvk/actions/runs/2685945402
issue present

**Comment by K0bin** [comment]
That build is 12 days old. It doesn't have the fix.

**Comment by TheDeusDeceptor** [comment]
> That build is 12 days old. It doesn't have the fix.
please can you share the build with the fix?

**Comment by Blisto91** [comment]
@TheDeusDeceptor The fix should be available in latest master which you can find a build of here https://github.com/doitsujin/dxvk/actions/runs/2841941581

**Comment by TheDeusDeceptor** [comment]
yes it works now! just used "d3d9.allowDirectBufferMapping = false"
now it gives about 30fps boost and less microstutters 
thanks everyone!

**Comment by idkwhatisthis123** [comment]
bruh the link is dead

**Comment by idkwhatisthis123** [comment]
how am i supposed to play ghwt now

**Comment by K0bin** [comment]
What link are you even talking about?

**Comment by GT210-1650** [comment]
Hello to everyone.
How can I Disable direct buffer mapping for GHWT ?
Windows 11
Ram 8
GTX 1650
Intel(R) Core(TM) i5-10300H
Please help me, thank you.

**Comment by GT210-1650** [comment]
so that means there is no way I can fix the crash?

**Comment by K0bin** [comment]
Does it still crash? We haven't gotten feedback in a year and you can't buy the game anymore.

Obviously we should aim to fix any issues DXVK has with the game.

But just as a general recommendation: @GT210-1650 Check out [Clone Hero](https://clonehero.net/).

**Comment by GT210-1650** [comment]
I downloaded the crack Version Of GHWT.
I don't how to use your fix or instruction to fix the crash or how to Disable direct buffer mapping.
I have clone hero but there is a new mod called Definitive Edition for GHWT and I wanted to try that...
