### ISSUE TITLE
Ghost Recon Future Soldier crashes with DX11 only

### ISSUE THREAD

**Issue by Alexithymia2014** [doitsujin/dxvk#2738]
Ghost Recon Future Soldier crashes with a Yeti dump error when using DX11 for the Campaign. It seems to work fine in the main menu and even multiplayer but not in the campaign (which is probably the only thing that works nowadays). 

I've tested this with Proton Experimental bleeding edge but occurs in other Proton versions. Additionally, you need to run protontricks uplay for Uplay to install. For whatever reason, Steam doesn't install Uplay for this game anymore. This game works fine in DX9 mode though!

### Software information
Ghost Recon Future Soldier DX11 (default mode)
Proton Experimental and Proton 7.0-3
This also occurs on my Steam Deck.
### System information
- GPU: Vega Mobile 10 but I've tested it on my Radeon 5700XT 
- Driver: mesa-22.1.3
- Wine version:  wine-7.0 (Proton)
- DXVK version:  1.10.2

### Log files
https://drive.google.com/file/d/1b3p4LRmyDiM8hu3xnNaiU8sRk9FJOBbL/view?usp=sharing 
These contain the dxvk and proton logs.

**Comment by Alexithymia2014** [comment]
An apitrace crashes when using WINED3D: https://drive.google.com/file/d/1D5mGl0IOlNtWjKR9y-L6ENmMI0Og1hVT/view?usp=sharing

Is there another way to get a trace? Using DXVK causes the game to slow down and I figured that was useless since the wiki says use WINED3D only.

**Comment by doitsujin** [comment]
> Is there another way to get a trace?

Yes, by doing it on Windows, which is probably necessary here.

**Comment by xv0t** [comment]
> Is there another way to get a trace? Using DXVK causes the game to slow down and I figured that was useless since the wiki says use WINED3D only.

On Windows, the game slows down/has very poor framerate while using DXVK if Punkbuster is not properly installed. Took me a while to figure that one out.

**Comment by Alexithymia2014** [comment]
apitrace v11.1 is here: https://drive.google.com/file/d/1yVfhW7ZWc72dAcf4HrGabdNVHyv3y4KH/view?usp=sharing

**Comment by Blisto91** [comment]
Trace plays fine. 
But i can reproduce in the actual game both with dxvk and wined3d.

**Comment by Alexithymia2014** [comment]
Doitsujin mentioned in discord it was likely hitting the memory limit since the game is 32bit. It is unfixable right?

**Comment by Blisto91** [comment]
Wouldn't say it's unfixable. Might be memory issues, but could be other stuff.

**Comment by Probotector** [comment]
Black background in DX9 mode, only showd the HUD but the rest of elements is a black background, tested with a GTX 1070, I can't play this game :(

And yes, DX11 mode crash in campaign mode.

**Comment by Blisto91** [comment]
Logs please.

**Comment by K0bin** [comment]
Apitrace please.

**Comment by Probotector** [comment]
I can't trace this game, when I extract the dlls in the same game exe's directory, the game not startup.

Tested with  proton 7.04 and experimental

I used this guide: https://github.com/doitsujin/dxvk/wiki/Making-a-Trace 

But the game not start...

**Comment by Blisto91** [comment]
Then some logs will have to do. Tho they probably wont tell much. They should appear in either the games root directory or next to the exe when you start the game with `PROTON_LOG=1 %command%`

Can try the game myself here later on the Nvidia setup when i have time

**Comment by Blisto91** [comment]
So i don't think the original issue is dxvk since i can start the campaign fine in dx11 mode on windows with 1.10.3.
But it also isn't d3dcompiler, d3dx11 or similar since i tried installing that with winetricks into the proton prefix and it's the same. Maybe some wine thing.

**Comment by Alexithymia2014** [comment]
Hi @Blisto91,

Dx9 mode for this game is no longer working correctly. The UI renders but the game itself is black. I can see the cross hairs and team mate names but no 3d graphics. Just black. Anything you can suggest I try before I prepare an API trace?

**Comment by Blisto91** [comment]
@Alexithymia2014 Hello and thank you for the report. This seems to be an issue with the d3dcompiler_47 dll as it works when i install the windows version with winetricks. Did this used to work without having to do that?

**Comment by Alexithymia2014** [comment]
It used to work fine without installing d3dcompiler_47, but I only remember it working probably around the time I filed this report. I'll give it a shot with that dll install. Thanks!

**Comment by Blisto91** [comment]
Hmm ok. The d3dcompiler_47 dll in Proton doesn't seem to have been updated since april 2022

**Comment by Alexithymia2014** [comment]
Ah I see. Well either way it's working in DX9 mode again with that dll installed using proton tricks. Thanks for your assistance!

**Comment by mbriar** [comment]
>  The d3dcompiler_47 dll in Proton doesn't seem to have been updated since april 2022

vkd3d, which implements the d3dcompiler stuff, was updated 2 month ago, in experimental at least.

**Comment by Blisto91** [comment]
Ah didn't realize it was dependent on the separate module.
It's also a issue with proton 7.0-6 so logically it should be a regression in 7.0-4 when the vkd3d module was updated in stable. Will compile 7.0-3 here later and check out. Thanks

**Comment by intelfx** [comment]
DX9 seems to be working here on Steam Deck with either Valve's Proton (7.0-3, 7.0-6, 8.0-4, experimental as of 2023-11-09) or GE-Proton8-23.

DX11 crashes though, with or without d3dcompiler_47 override. After the prologue mission, the cutscene sequence _does_ load with DX11, as well as the firing range. The actual mission after the cutscene sequence crashes as well.

Is this fixable, is there anything that I can help with?

**Comment by Blisto91** [comment]
It is not much pointing to this being a dxvk issue. It works fine with dxvk on Windows and it crashes the same with wined3d (reading what i wrote above at least, haven't tested right now)

**Comment by Alexithymia2014** [comment]
This issue seems to be resolved in Proton 9.0.
