### ISSUE TITLE
How to troubleshoot video issues on games

### ISSUE THREAD

**Issue by iojeda** [doitsujin/dxvk#2740]
Hi Guys,
Thanks for all the work you guys put on this software.
I am using wine to play windows games and most work fine but some have minor issues.
I know this might not be the place for this question but I couldn't find any place where this is explained.
So hopefully you guys can point me in the right direction to learn more.
I would like to be able to troubleshoot why a particular game might have graphical issues.
For example (textures not loaded properly, rendering issues or any other graphical glitches)
I will put some examples of games that I have issues with but don't know how to troubleshoot them.

Anno2205
![image](https://user-images.githubusercontent.com/5243583/180403754-5c951743-0f6f-42f0-905b-91974329acaf.png)

Any or documentation on how to troubleshoot etc will be more than welcome.
Thanks.

**Comment by Blisto91** [comment]
Do you have steam?
If yes could you post a steam system information report?
In steam -> help -> system information -> wait at least 15 seconds since it will be collecting even when text have appeared -> copy the text and post it here as a GitHub gist or a text file

**Comment by doitsujin** [comment]
There aren't any known graphics issues with this game on [protondb](https://www.protondb.com/app/375910). Make sure your game install isn't corrupted and you're using a supported driver.

**Comment by iojeda** [comment]
Hi @Blisto91 
I am not using Steam I am using just Wine.
I have done this to make the game work

Added those overrides to winecfg
      "nvapi,nvapi64": "disabled",
      "xaudio2_7": "native,builtin"

And added these environment variables
      DXVK_HUD=0
      DXVK_STATE_CACHE=0
      PYTHONIOENCODING=utf8

I can still add here the steam system info dump if that helps.
[steamsysteminfo.txt](https://github.com/doitsujin/dxvk/files/9167630/steamsysteminfo.txt)

Hi @doitsujin
The game is not corrupted as there was sum checks done and they passed.

**Comment by doitsujin** [comment]
Make sure you have the necessary d3d11+dxgi overrides for DXVK as well.

**Comment by Blisto91** [comment]
Ah. You can probably get the same details from `inxi` but I'm more used to steam report myself. The lines i was interested in was at vulkan icds to see if you had amdvlk installed. But i see you don't and have overrides for radv enabled anyway.
And also `graphics-details` to see get a hint if your driver was functioning. But it looks fine.

Yes as said above make sure dxvk is getting picked up by settings the overrides to native. But if you are using the setup script that should happen on its own.

**Comment by iojeda** [comment]
Thanks guys for the help.
@doitsujin  @Blisto91 Make sure you have the necessary d3d11+dxgi overrides for DXVK as well.
How can I do that or check that?

**Comment by Blisto91** [comment]
In winecfg you should have have overrides for d3d11 & dxgi set to native (and d3d10core & d3d9 for games that use those)

Ignore the d3dx9_X ones. They a from a unrelated winectricks install
![Screenshot_20220722_171445](https://user-images.githubusercontent.com/47954800/180470143-4dc63b48-3d1a-4b64-8b33-a0bcc09bf74c.png)

**Comment by iojeda** [comment]
@Blisto91 Thanks a lot.

I got it sorted.
I had to do this...
![image](https://user-images.githubusercontent.com/5243583/180472807-ac4b5b8b-3eb1-4ba5-af78-d3896748a33b.png)

I thought this was part of Wine already but I realized it is not and had to be added /installed into the wineprefix, so my bad...
Once I added it to the prefix, boom!! It worked fine :D 
Thanks a lot for your kind help guys.

**Comment by Blisto91** [comment]
np.
Ye dxvk is a seperate project so without it dx9 - dx11 games will be running through wined3d instead which is dx to opengl.
