### ISSUE TITLE
Rainbow colored screen Unreal Engine 4 or 4.2x

### ISSUE THREAD

**Issue by jackbingow** [doitsujin/dxvk#2744]
Any Unreal game causes 
Rainbow colored screen Unreal Engine 4 or 4.2x

### Software information
Stray lowest settings
Gta vice city definitve edition lowest settings(gta vice city definitive edition(dx11) without dxvk has no graphical glitches.)

### System information
- GPU:AMD Radeon 530
- Driver:19.12.3(update making vulkan to not work)
- Wine version: None Windows 7
- DXVK version: lastest 1.10.2 

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
[Stray-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/9170193/Stray-Win64-Shipping_d3d11.log)
- dxgi.log:
[Stray-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/9170222/Stray-Win64-Shipping_dxgi.log)

![screenshot](https://user-images.githubusercontent.com/109824205/180514036-9e351ca3-69f6-40d6-a06a-ffc38fa5541d.jpg)

**Comment by Blisto91** [comment]
Windows 7 is not supported. Windows AMD drivers are known to have issues and need to be up date with the latest version.
Nothing can be done here sadly.

**Comment by jackbingow** [comment]
cannot update vulkan stops working. 20.3.1 also work.Any newer driver only directx 11 work

**Comment by K0bin** [comment]
Windows 7 is 13 years old and GPU vendors have dropped driver support for it. You really need to update to Windows 10 or switch to Linux. This is clearly a driver bug, so there's nothing we can do about this either way.

**Comment by jackbingow** [comment]
I have ubuntu 20.03. is there dx11 wrapper only

**Comment by Blisto91** [comment]
dxvk includes vulkan translators for dx11. It's the d3d11 and dxgi files.
If you are using wine just install dxvk with the setup script. See the readme.
If you are using lutris, bottles or steam proton then dxvk should already be included.

**Comment by jackbingow** [comment]
On Nvidia GPU on old laptop there is no issue . Could be vulkan version 1.2 nvidia versus 1.1 AMD?
Nvidia drivers updates is not dependent on intel as AMD driver.
first dxvk version to support vulkan 1.2? so i can download older version.

**Comment by Blisto91** [comment]
Don't think so. 1.10.2 should work afaik and if there were any missing vulkan extensions or similar it would say in the log. 
It mostly just looks like amds windows 7 drivers working as they should. Or something other on windows 7 in combination. Not sure. 
amd's windows drivers have always been a bit iffy together with dxvk so it's always recommended to get the latest ones available aren't those arent on windows 7. The latest legacy release is mostly just a security update and doesn't include any of the past bug fixes afaik.

**Comment by jackbingow** [comment]
will it work on ubuntu 16 or 18?

**Comment by Blisto91** [comment]
I don't see why not as long as the drivers aren't too old.
But i'm not too familiar with ubuntu so you you should probably ask in some ubuntu community

**Comment by K0bin** [comment]
No.

It will work in Ubuntu 22.

**Comment by jackbingow** [comment]
How turn off all dx11 options one by one?.how to turn off Postprocessing effects in dxvk. 
could color conversion of textures be an issue VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT?

**Comment by K0bin** [comment]
Those aren't options you can turn off and there's absolutely nothing you can do to make it work except for **updating your OS to something recent**.

**Comment by jackbingow** [comment]
@K0bin  I did read about dxvk will upgrade(to newer vulkan version),but i was asking about older versions of dxvk?
On ubuntu 20 work without issues but will work on ubuntu 16 or 18. Oldest dxvk version which gpu driver need?

**Comment by K0bin** [comment]
>  I did read about dxvk will upgrade(to newer vulkan version),but i was asking about older versions of dxvk?

That's future DXVK versions, not the one you tried. Your graphics driver is simply broken and you'll have to update your OS to install one that's fixed.

**Comment by jackbingow** [comment]
@K0bin issue is windows bug. On ubuntu 20 game works without issue. But asking about downgrading to ubuntu(have recovery partition with ubuntu 16) in case won't boot?
Where can find info about mesa RADV version history and compatibility of each version of ubuntu/linux kernel version?

**Comment by K0bin** [comment]
Ubuntu 16 is not gonna work. Why can't you just use an OS that's not 5 years old?

**Comment by jackbingow** [comment]
Ubuntu 18 i read support vulkan 1.1 in amd driver for linux. So Ubuntu 18 is oldest dxvk will work?

**Comment by K0bin** [comment]
No. The Vulkan version is pretty meaningless and DXVK will soon require Vulkan 1.3.

Use Ubuntu 22.

**Comment by jackbingow** [comment]
@K0bin if you don't understand .What are driver requirements of dxvk 0.7?.need to test.upgrade may be buggy on old OS.

**Comment by Blisto91** [comment]
Can't really say much else than to install it and try then. 
For amdvlk or amdgpu-pro (very close to the windows driver) it is always recommended to get the latest drivers as said since they've had random rainbow puke issues from time to time in the past and they aren't getting much specific support in dxvk. They also aren't the recommend driver to use on linux. Radv is, which has nothing to do with amd's own driver.

**Comment by Joshua-Ashton** [comment]
@jackbingow We do not support anything below the latest stable release of Mesa. You are going to need to either get an updated driver somehow or upgrade your OS.
Asking "what's the oldest version that works?" is just looking to either run terribly or cause issues.
Using 8 year old drivers for a game released a month ago is going to give you a bad time. There is no way around that.
