### ISSUE TITLE
Ninja Blade - Strange glitch in one character 

### ISSUE THREAD

**Issue by corvusd** [doitsujin/dxvk#2745]
### Software information
Ninja Blade

### System information
- GPU: NVIDIA GeForce GTX 1660 SUPER
- Driver: NVIDIA 510.60.02
- Wine version: lutris-fshack-7.2-x86_64
- DXVK version: 1.10.2

### Apitrace file(s)
https://mega.nz/file/xZYzVCJR#i7QcdaRd111x0U75ZztkZyV8HXjqiSsBQwE7Mu4SKV0

### Log files
[NinjaBlade_d3d9.log](https://github.com/doitsujin/dxvk/files/9172145/NinjaBlade_d3d9.log)
[NinjaBlade_dxgi.log](https://github.com/doitsujin/dxvk/files/9172146/NinjaBlade_dxgi.log)

I only have one graphic issue with this game, a not serious. This issue in the body in this main character, very weird. Not is a feature in PC windows native or Xbox360 this character look right:
![20220620005412_1](https://user-images.githubusercontent.com/10695292/180567955-753dca3d-bc55-4373-9ea1-fdeffec58ba9.jpg)
![20220620005435_1](https://user-images.githubusercontent.com/10695292/180567959-6c873316-bf31-4144-be0c-f045049f4066.jpg)
![20220620005440_1](https://user-images.githubusercontent.com/10695292/180567961-82077583-5072-47a2-a8f2-69bc2aacc3c5.jpg)

I played in lutris with lutris-fshack-7.2-x86_64 and DXVK v1.10.2, D3D extras v2 and DXVK NVAPI v0.5.4. With the newer lutris wine version, I could see the FMV perfectly.

My PC:
OS: Ubuntu 20.04.4 LTS KERNEL: 5.15.35-xanmod1 CPU: AMD Ryzen 5 3400G with Radeon Vega Graphics GPU: NVIDIA GeForce GTX 1660 SUPER GPU DRIVER: NVIDIA 510.60.02 RAM: 16 GB

**Comment by Blisto91** [comment]
Hi there and thank you for a nicely filled out issue.

Can you verify that the issue goes away if you make a file called `dxvk.conf` next to the games exe and insert `d3d9.alphaTestWiggleRoom = True`

To be sure that the conf file is picked up you can also add `dxvk.hud = 1` and see the hud shows up ingame

**Comment by corvusd** [comment]
Fix the problem like charm! Thanks! :)

**Comment by Blisto91** [comment]
I do fear that with this fix he will be a worse ninja. Fully visible now 😔. Might get fired
