### ISSUE TITLE
Tom Clancy’s The Division Inconsistent frame pacing

### ISSUE THREAD

**Issue by nutta-git** [doitsujin/dxvk#2746]
**Issue:**
    Constant frame pacing issue while playing the game, I thought it was shaders; however the hitching remained consistent through out hours of game play. This issue seems to only be effecting Proton version Proton 7.0xx, using older version Proton 6.3-8 with DXVK v1.9.2-13-g714ca482 the game seems to run fine without the mentioned issue. This could be a Proton Issue, but since its frame hitching, I thought it was best to report here.

**Software info:**

Tom Clancy’s The Division™
https://store.steampowered.com/app/365590/Tom_Clancys_The_Division/

**System Info:**
OS : Arch Linux
GPU: AMD ATI Radeon RX 5700
CPU: AMD  R7 3700x
Driver: mesa 22.1.3-1
Wine Version: Proton 7.0-3
DXVK Version: 1.10.1-57-g279b4b7e

**Logs**:

Unfortunately, the game does not start with WINED3D to get an API trace following the guide: https://github.com/doitsujin/dxvk/wiki/Making-a-Trace. I couldn't screen record due to CPU usage causing more hitching and GPU recording was poor quality with random pink frames. I tried logging MANGOHUD frame time data, however stopping the logging cause a game crash with no log data.

**Comment by doitsujin** [comment]
You could try Proton 6.3 with DXVK 1.10.2 and see if the problem is there.

That said, bad frame pacing can be caused by literally anything (compositor, wine, dxvk), and I've seen people complain about the same thing in Prey going from 1.9->1.10 without but I'm unable to reproduce that here, so it's almost impossible to really do anything about that kind of problem.

**Comment by nutta-git** [comment]
I use KDE with compositing turned off with x11. 

I replaced the following:
Proton 6.3/dist/lib64/wine/dxvk/d3d9.dll
Proton 6.3/dist/lib64/wine/dxvk/d3d10_1.dll
Proton 6.3/dist/lib64/wine/dxvk/d3d10.dll
Proton 6.3/dist/lib64/wine/dxvk/d3d10core.dll
Proton 6.3/dist/lib64/wine/dxvk/d3d11.dll
Proton 6.3/dist/lib64/wine/dxvk/dxgi.dll

files with DXVK 1.10.2's files (verified with mangohud) and deleted the old WINE pfx. I did not see any frame pacing issue. Looks like I will report this to the proton project.

**Comment by Maneatuer** [comment]
> You could try Proton 6.3 with DXVK 1.10.2 and see if the problem is there.
> 
> That said, bad frame pacing can be caused by literally anything (compositor, wine, dxvk), and I've seen people complain about the same thing in Prey going from 1.9->1.10 without but I'm unable to reproduce that here, so it's almost impossible to really do anything about that kind of problem. Doesn't help that this game isn't one that I can easily test on my end.

How can I apply proton 6.3 with dxvk 1.10 while using steam play tool? Could you give me some guidance maybe some link about this? Thank you in advance!

**Comment by Blisto91** [comment]
If you have already installed proton 6.3 in steam then just download the release from here https://github.com/doitsujin/dxvk/releases
Extract the files in the x32 folder into 
```
~/.steam/steam/steamapps/common/Proton 6.3/dist/lib/wine/dxvk/`
```
And extract the files in the x64 folder into
```
/home/kasphor/.steam/steam/steamapps/common/Proton 6.3/dist/lib64/wine/dxvk/
```

To undo just verify the integrity of proton 6.3 files through the steam UI

**Comment by Maneatuer** [comment]
I have tried exactly this, the game (Nioh 2) just won't load up :(  Still thanks for your reply.

**Comment by Blisto91** [comment]
Does it start if you launch the game with `PROTON_USE_WINED3D=1 %command%` ?
