### ISSUE TITLE
Controller input not working - Resident Evil 4 UHD

### ISSUE THREAD

**Issue by kTeo-0** [doitsujin/dxvk#2751]
With only the latest build installed, the inputs for my Dualshock 4 does not work when trying to boot RE4UHD.

this is the version i'm using:
https://github.com/doitsujin/dxvk/suites/7491174833/artifacts/307575916

The game runs on 32bit d3d9

**Comment by kTeo-0** [comment]
ok, tried rolling back a few build and found one that had it working.
https://github.com/doitsujin/dxvk/actions/runs/2671698082

I can't use 1.10.2 or 1.10.1 since it does something to the inventory, the 3d models get misplaced. The most recent builds solved this problem.

![aa](https://user-images.githubusercontent.com/106371533/180631647-9b0c7584-bb87-424a-86c0-cf7b78521ed9.png)

**Comment by doitsujin** [comment]
Does controller input work with wined3d? Mouse/Keyboard stuff I'd understand, but we don't really interact at all with controller input.

**Comment by kassindornelles** [comment]
> With only the latest build installed, the inputs for my Dualshock 4 does not work when trying to boot RE4UHD.
> 
> this is the version i'm using: https://github.com/doitsujin/dxvk/suites/7491174833/artifacts/307575916
> 
> The game runs on 32bit d3d9

Are you on Windows or linux?
What GPU and driver version?

**Comment by kTeo-0** [comment]
> Does controller input work with wined3d? Mouse/Keyboard stuff I'd understand to some degree, but we don't really interact at all with controller input.

nope, tried using it with both d3d9 from dxvk and wine3d and none worked.

**Comment by kTeo-0** [comment]
> Are you on Windows or linux? What GPU and driver version?

Windows 10 Home 64-bits (10.0, 19044)
GTX 980 Ti, driver version 516.40

**Comment by Blisto91** [comment]
If you are using steam then try switching to the beta client

**Comment by kassindornelles** [comment]
> > Are you on Windows or linux? What GPU and driver version?
> 
> Windows 10 Home 64-bits (10.0, 19044) GTX 980 Ti, driver version 516.40

DXVK is not supposed to mess with input, can you try launching the game using steam big picture mode?
If you are using a pirated copy of the game that's on you and nobody here will support you

**Comment by brad86m** [comment]
Use DS4Windows and make sure to tick the 'Hide DS4 Controller' box, otherwise RE4 will see both the controllers native dinput and the xinput it is emulating. This messes things up.  

If using Steams native wrapper for DualShock 4, it should do this automatically.

**Comment by Blisto91** [comment]
dxvk master uses vulkan 1.3 and steam somewhat ties it's controller support together with the overlay (afaik) which only supports vulkan 1.3 in the client beta for now. Unless something changed since i wrote.
So trying that first could be a quick thing.

**Comment by Blisto91** [comment]
@kTeo-0 Friendly ping

**Comment by kassindornelles** [comment]
Closable issue, DXVK has nothing to do with input :shrug:

**Comment by Blisto91** [comment]
Dxvk can mess with input in a few cases. Maybe mostly dx9 games.

Tho since this is a controller i'm almost certain this is just a steam overlay issue.
