### ISSUE TITLE
Stray crashing under Intel ANV

### ISSUE THREAD

**Issue by CallumDev** [doitsujin/dxvk#2752]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/doitsujin/dxvk/wiki/Making-a-Trace.
Preferably record the trace on Windows, or wined3d if possible.

**Reports with no log files will be ignored.**

### Software information

Stray will crash using DXVK with Intel Xe with a fairly generic "Fatal Error!" message box. Game launches under WineD3D.

### System information
- GPU: Intel(R) Xe Graphics (TGL GT2), i7-11370H
- Driver: Mesa 22.1.3 ANV
- Wine version: Proton Experimental (experimental-7.0-20220714b)
- DXVK version: v1.10.1

### Apitrace file(s)
Captured with `PROTON_USE_WINED3D11=1`
- https://drive.google.com/file/d/17GzjKdgG_MiIk24knDJ8xWJyskzz5FbN/view?usp=sharing

### Log files
- d3d9.log: (empty)
- d3d11.log: [Stray-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/9175835/Stray-Win64-Shipping_d3d11.log)
- dxgi.log: [Stray-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/9175836/Stray-Win64-Shipping_dxgi.log)
- steam-1332010.log: [steam-1332010.log](https://github.com/doitsujin/dxvk/files/9175837/steam-1332010.log)

**Comment by doitsujin** [comment]
Should probably be reported to mesa since the game works fine on AMD and NV. I don't have any Intel hardware to test on, but I replaying the trace I don't really see any obvious issue on our end.

**Comment by CallumDev** [comment]
Reported to Mesa here: https://gitlab.freedesktop.org/mesa/mesa/-/issues/6924

**Comment by jackbingow** [comment]
@doitsujin what is d3dextra in lutris\Wine?

**Comment by AlexBozhenk** [comment]
The trace works fine on dxvk/mesa head. The game fails with "Fatal error!" box. But it looks like Proton issue. The gabe works fine on Proton 6.3.8 and smaller version. [The thread](https://github.com/ValveSoftware/Proton/issues/6017#issuecomment-1195747010) in Proton repo shows that it's more likely not dxvk issue. (Tried to copy dxvk from newer protons and it doesn't affect the issue)

**Comment by Blisto91** [comment]
We know it's not a dxvk issue. We are waiting for it to be fixed in ANV

**Comment by llandwerlin-intel** [comment]
I'm experiencing an assert in debug builds : 
```
4\Stray-Win64-Shipping.exe: ../src/vulkan/wsi/wsi_common_x11.c:908: x11_surface_get_formats2: Assertion `f->sType == VK_STRUCTURE_TYPE_SURFACE_FORMAT_2_KHR' failed. 
```
This doesn't look like it's coming from DXVK after grepping the code.

I can get the game starting by commenting that assert in Mesa on an ADL GPU.

For it to work on DG2, I need to set `export force_vk_vendor=-1` which is usually a sign that XeSS is involved.

As far as we understand the XeSS library is expecting to find the driver binary in the distribution (which is not the case in wine/proton).

**Comment by K0bin** [comment]
Supposedly fixed on the Mesa side.

**Comment by Blisto91** [comment]
Fixed by https://gitlab.winehq.org/wine/wine/-/merge_requests/3104 which is also included in Proton Experimental
