### ISSUE TITLE
Assassin's Creed Brotherhood/windows state cache

### ISSUE THREAD

**Issue by njmdietrich** [doitsujin/dxvk#2760]
I am using dxvk on windows to improve performance in assassin's creed brotherhood. However, something seems to be broken with the state cache. If I understand correctly, when a driver update happens, the shaders in the state cache are recompiled when starting the game, and then everything is supposed to work like before. I installed a driver update, and the game stutters as if I had never built up a shader cache. According to the log over 15000 state cache entries exist.

**Comment by doitsujin** [comment]
It only works when the game loads all shaders before they are used. Some don't do this, so yes, stutter is expected in those cases.

This also extends to almost all UE4 games using D3D11 and a few others.

**Comment by njmdietrich** [comment]
I thought the whole point of the state cache was so you would only encounter stutter the first time a shader is encountered, regardless of driver updates etc? Or what is the point of it then?

**Comment by doitsujin** [comment]
Well yes, but the game still needs to actually create the shader before we can compile everything. If the game doesn't do that, there's going to be stutter, even (although usually to a lesser degree) with native D3D drivers. This isn't a bug, this is literally just games being dumb.
