### ISSUE TITLE
Multiple regressions with League of Legends

### ISSUE THREAD

**Issue by r2rX** [doitsujin/dxvk#2763]
Hello there,

DXVK 1.10.2 works well with League of Legends although I decided a few days back to try a newer artifact/build of DXVK and it doesn't work. As a result, I sifted through the artifacts released since 1.10.2 Stable and found two specific commits that are progressively regressive. Testing was done on Fedora 36 KDE through Lutris 0.5.10.1 and Lutris-GE-7.0-3-LoL & Lutris-GE-7.0-4-LoL (this series of LoL specific WINE prefixes are the easiest/most convenient to get LoL working).

### Test Results
1.10.2 Stable to commit [6ac5ca3] - Works fine overall. Client window and game window, when match starts, work correctly.

Commit [0f6ba59] to [e28b268] - Client window works fine but the game window fullscreens to a black screen, although the LoL mouse cursor shows and is responsive. At this point, nothing happens and I have to close the process manually.

Commit [330ff8f] to the most current ([ea76bfd] as of writing this post) - Client window works fine but the game window doesn't load. It shows the game window process in the taskbar but that's as far as it goes. At this point, I have to close the process manually.

To replicate my test method, simply load the game client, create and start any game mode/type (Practice Tool is the best in order to test and not potentially get reported/banned for afk'ing).

### Software information
On my system, the game is using DirectX11 (d3d11). If using the latest GE-LoL 7.0-4, the game will load the main client (LeagueClientUX.exe) and once creating/joining a game, the game window itself opens in a separate process (LeageofLegends.exe). In-game settings are set to 1920x1080, with all details set to High and FPS set to match 144fps.

The default directory structure the game installs to is C:\Riot Games; the launcher is located in \Riot Games\League of Legends and the game executable is located in \Riot Games\League of Legends\Game.

### System information
- GPU: AMD RX 6800M
- Driver: Mesa 22.2.0-devel
- Wine version: Lutris-GE-7.0-3-LoL & Lutris-GE-7.0-4-LoL
- DXVK version: 1.10.2 Stable up to to latest commit ea76bfd

### Apitrace file(s)
[6ac5ca3](https://mega.nz/file/OaZAnYCY#558uMcNTDEYeLpDtWip2rmbCgPUqjMZ6bobm9klsiWY) as reference for last working version
[0f6ba59](https://mega.nz/file/uTxj3bzL#VOP8dT5Me2cBUzUUJoT0b0YfvDP_RjWJMiWp_UA5ktk)
[330ff8f](https://mega.nz/file/OTBjwTCa#oRWnat0i_9MNZIcaZSEbhQxDJs_deu4cKt9ob0VqrAw)

**Comment by K0bin** [comment]
Please provide an apitrace.

**Comment by doitsujin** [comment]
I don't play the game, it's not on Steam, and I'm not really willing to install the game and create an account and go through whatever pain is required to get the thing running at all, since that can easily take an entire work day that I could be spending on more useful things.

Please also provide the info that's asked for in the issue template. You didn't even tell us whether this is with D3D9 or D3D11.

**Comment by r2rX** [comment]
@K0bin @doitsujin My apologies for not providing the additional information earlier. The apitrace files and game info has been updated in the initial post.

**Comment by doitsujin** [comment]
The first trace replays fine here. My guess is that there's an issue with the wine build simply being too old; there are some known issues with the current master branch on older wine but those seem to have been resolved (see #2729), not entirely sure what the cause is though.

**Comment by r2rX** [comment]
As far as I have understood, @GloriousEggroll bases his custom WINE builds on the most recent bleeding-edge proton experimental wine repo.

**Comment by doitsujin** [comment]
someone on Discord mentioned that the winevulkan build in GE-7.0-4-LoL doesn't support Vulkan 1.3 yet so that's going to be a problem.

**Comment by r2rX** [comment]
Interesting. Out of curiosity, is commit [6ac5ca3] the last version to work before depending on Vulkan 1.3?

**Comment by doitsujin** [comment]
Yes, it is.

**Comment by kassindornelles** [comment]
League of legends works with dxvk master
@r2rX use the TKG wine build on lutris
https://github.com/Frogging-Family/wine-tkg-git/actions/runs/2756890985

**Comment by r2rX** [comment]
Thanks for your time & effort, @doitsujin. I'll bring it up on GE's Discord channel and report back here with any updates.

Also, cheers for the heads-up on the TKG build @kassindornelles .

**Comment by kassindornelles** [comment]
> Thanks for your time & effort, @doitsujin. I'll bring it up on GE's Discord channel and report back here with any updates.
> 
> Also, cheers for the heads-up on the TKG build @kassindornelles .

with the TKG build you might crash in the riotclient in the first boot, just kill all processes and try again and you are going to be set! have fun!

**Comment by r2rX** [comment]
Hey @doitsujin . It's been confirmed that the latest DXVK artifacts work fine with League. It was a matter of @GloriousEggroll 's build of winevulkan to be updated, so you were on point about that.

Once again, cheers!
