### ISSUE TITLE
[DX9] Tomb Raider Underworld broken due stutter 

### ISSUE THREAD

**Issue by Alejandro9509** [doitsujin/dxvk#2764]
Hello guys, I have been testing the TRUnderworld game and there is literally a stutter every time I take a step, I have tried it with WineD3D and it works without problem except for visual bugs, but it does not have this problem, I link  2 videos with the mentioned

I have tried it on my machine with a GTX 1060 and with the RTX 3080, and it is the same problem.

Link: 
Video 1
https://www.youtube.com/watch?v=mWtFpBRe2Fc

Video 2
https://www.youtube.com/watch?v=4-ozC-TDIHc

### System information
- GPU: GTX 1060 and RTX 3080
- Driver: 515.49.10 Vulkan Beta 
- Wine version: Proton Experimental
- DXVK version: 1.10.1, 1.10.2, master-git

### Apitrace file(s)
- Progress....

**Comment by doitsujin** [comment]
This is not a bug, as you can quite clearly see there are pipelines being compiled whenever the game stutters.

D3D9 support for pipeline libraries is not implemented yet so there is no way to fix this currently.
