### ISSUE TITLE
DXVK on a DirectX 9Ex game

### ISSUE THREAD

**Issue by Cianez** [doitsujin/dxvk#2771]
I tried to use DXVK 1.10.2 on the game Perilous Warp, which uses either OpenGL or DirectX 9Ex (I've set it to DirectX 9Ex), but it just doesn't work.
I've used the x64 DLLs (all of them for convenience) since the game has a x64 executable.
Is there something I'm missing or is DirectX 9Ex the issue here?
Any help is appreciated.

My PC:
i5-3340
GTX 1070 Ti (Driver version 516.59.0.0)
12 GB DDR3
Windows 10 Pro 64 bit

**Comment by doitsujin** [comment]
Can you please at least describe what the problem is? D3D9Ex should work just fine.

**Comment by Cianez** [comment]
Well it just doesn't use DXVK at all, it starts up normally like always. I can play but it seems that it's not using/reading DXVK at all. I've also tried to use a dxvk.conf with "dxvk.hud = fps" but nothing shows up at the top left corner of the screen.

**Comment by Riesi** [comment]
Please provide the information that is asked for in the issue template. You currently dont really provide anything... not even what game you are trying to run.

**Comment by Riesi** [comment]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and, if possible, a D3D11/D3D9 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced.
In order to create a trace for **D3D11/D3D10**: Run `wine apitrace.exe trace -a dxgi YOURGAME.exe`.
In order to create a trace for **D3D9**: Follow https://github.com/doitsujin/dxvk/wiki/Making-a-Trace.
Preferably record the trace on Windows, or wined3d if possible.

**Reports with no log files will be ignored.**

### Software information
Name of the game, settings used etc.

### System information
- GPU:
- Driver:
- Wine version: 
- DXVK version: 

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by Cianez** [comment]
Apitrace doesn't seem to work (no .trace file on my desktop, only a "dxgitrace.pdb" file in the executable folder) when I launch the game.
The game also produces no log files for d3d9 because apparently DXVK isn't picked up at all (or Apitrace if it should also create log files).
Most of the informations you ask to give have already been written in the first post but I'll rewrite them here just in case:


### Software information

The game's name is Perilous Warp, highest settings, 1440x900 resolution, 75 Hz.

### System information

* GPU: ZOTAC GeForce GTX 1070 Ti AMP! Edition, 8 GB VRAM.
 
* Driver: 516.59.0.0 (Game Ready Driver)
 
* Wine version: Not using Wine. Windows 10 Pro 64 bit
 
* DXVK version: 1.10.2


### Apitrace file(s)

No .trace file has been created upon launching the game

### Log files

* d3d9.log: Not present

* d3d11.log: Not present

* dxgi.log: Not present

[dxgitrace.pdb](https://mega.nz/file/91gRgYSY#L6cOFuUtqj4-ihWcnsY-00q8UIS2RV8E02BhIxBSfV0)

**Comment by Blisto91** [comment]
Do you also have a `system` folder besides the `system64` folder? I see on steamdb that the game has both 32bit and 64bit. If yes try putting the 32 bit DLLs in there.
Also some games are a bit weird with how they pick up the files so the conf file might need to be in the games root folder and not next to the exe

**Comment by Cianez** [comment]
> Do you also have a `system` folder besides the `system64` folder? I see on steamdb that the game has both 32bit and 64bit. If yes try putting the 32 bit DLLs in there. Also some games are a bit weird with how they pick up the files so the conf file might need to be in the games root folder and not next to the exe
> 
> Another quick thing to try would be also to try putting the dxvk dll's in the root folder aswell

Yes, the game does have a system folder besides the system64, and I've already tried to use the 32 bit DLLs in there but the game just don't pick them up just like in the 64 bit folder for some reason (also, the game provides no option to launch it in either 32 or 64 bit, I have to launch it directly from the respective executables; thankfully that works).
Although, I didn't try to put the DLLs elsewhere, like in the root folder. I'm going to try that right now and report back by editing this post (Black Mesa also has this, you have to put the files in the "bin" folder and not in the executable one in order to make DXVK work).

**Comment by a1batross** [comment]
@Cianez `ref_d3d9.dll` sounds like something engine developer used to split the engine code and whole renderer. You better not touch it. Just saying.

**Comment by Cianez** [comment]
> @Cianez `ref_d3d9.dll` sounds like something engine developer used to split the engine code and whole renderer. You better not touch it. Just saying.

In fact the game doesn't start up without it, but it also doesn't read any other DLLs apart from that, unfortunately.

**Comment by Blisto91** [comment]
I will check it out once I'm home from vacation, the game looks cool enough that i might get it myself

**Comment by Cianez** [comment]
> I will check it out once I'm home from vacation, the game looks cool enough that i might get it myself

Haha ok. Thanks. Though I don't own the game, I'm currently playing the demo so you can playtest it before actually buying it (I'm waiting for a feature that will make me buy it).

**Comment by Blisto91** [comment]
I've tested the demo now on windows. It does indeed seem like dxvk isn't getting picked up. Probably `ref_d3d9.dll` not allowing the local dxvk dll to be used.
Don't think much can be done here.
It works fine on Linux since with wine dxvk usually gets loaded as "windows own files" in the system folder.

Tho the game seems to run decently with dx9 from a very short test with my R9 380

**Comment by K0bin** [comment]
Probably hardcoded to load C:\Windows\system32\d3d9.dll.

Not much we can do in that case.

**Comment by Cianez** [comment]
> I've tested the demo now on windows. It does indeed seem like dxvk isn't getting picked up. Probably `ref_d3d9.dll` not allowing the local dxvk dll to be used. Don't think much can be done here. It works fine on Linux since with wine dxvk usually gets loaded as "windows own files" in the system folder.
> 
> Tho the game seems to run decently with dx9 from a very short test with my R9 380

It does run extremely well in some areas, even 300+ fps, but in some other areas it goes down to 60-70 fps.
Oh well, maybe it'll be further optimised in the future.
Thanks for testing and helping me out!

**Comment by K0bin** [comment]
> It does run extremely well in some areas, even 300+ fps, but in some other areas it goes down to 60-70 fps.
Oh well, maybe it'll be further optimised in the future.

Only if someone provides an apitrace.

**Comment by Blisto91** [comment]
They mean with directx 9 on windows :eyes:

**Comment by K0bin** [comment]
Oh. :)
