### ISSUE TITLE
Assassin's Creed Syndicate freezes on startup

### ISSUE THREAD

**Issue by popsUlfr** [doitsujin/dxvk#278]
So Assassin's Creed Syndicate freezes on the first frame with DXVK : 
![screenshot_20180414_173549](https://user-images.githubusercontent.com/1030423/38771623-ac159670-4026-11e8-8e19-087bf73d2f3e.png)
*Wine*

The only way out is to kill the process.

On Windows 10 with DXVK enabled it goes through the startup videos and to a black menu with useable cursor. It then spouts this error :
```
The procedure entry point DXGID3D10RegisterLayers could not be located in the dynamic link library
C:\Windows\SYSTEM32\d3d10core.dll.
```

![screenshot_14](https://user-images.githubusercontent.com/1030423/38771645-f266655a-4026-11e8-893c-e11d88089586.png)
*Windows 10*

Does it need some DirectX10 functions to work ? Or something with the nvidia driver.
#274 Seems to be related

### Software information
Assassin's Creed Syndicate v1.51 Uplay

### System information
- GPU: Nvidia Geforce GTX 980Ti
- Driver: 390.48 on Linux, 391.35 on Windows
- Wine version: 3.6 Staging
- DXVK version: [5fa8174](https://github.com/doitsujin/dxvk/commit/5fa8174816bd0d7a038f5ac59686ff7d21d25ecf)

### Apitrace file(s)
`apitrace.exe` is unable to produce any trace on this uplay game. I tried injecting `dxgitrace.dll` and it produced this weird trace. Not sure if it's of any use.
- [ACS.trace](https://u.teknik.io/Ejcls.trace)

### Log files
* Wine :
  - d3d11.log: 
[ACS_d3d11.log](https://github.com/doitsujin/dxvk/files/1910741/ACS_d3d11.log)

  - dxgi.log: 
[ACS_dxgi.log](https://github.com/doitsujin/dxvk/files/1910743/ACS_dxgi.log)

* Windows 10 :
  - d3d11.log: 
[ACS_d3d11.log](https://github.com/doitsujin/dxvk/files/1910744/ACS_d3d11.log)

  - dxgi.log: 
[ACS_dxgi.log](https://github.com/doitsujin/dxvk/files/1910745/ACS_dxgi.log)

**Comment by ZereoX** [comment]
I can also confirm a similar behaviour is observed on Tom Clancy's Ghost Recon Wildlands, but Wine crashes to desktop instead of hanging:
![grw - wine 3 5 staging dxvk 0 42](https://user-images.githubusercontent.com/761853/38772600-c6038722-4008-11e8-8d65-7a5ae46c4494.png)

# System information
GPU: Nvidia Geforce GTX 1080
Driver: 390.42
Wine version: 3.5 Staging
DXVK version: [5fa8174](https://github.com/doitsujin/dxvk/commit/5fa8174816bd0d7a038f5ac59686ff7d21d25ecf)

# Log files

- Wine :
  - [GRW_d3d11.log](https://github.com/doitsujin/dxvk/files/1911099/GRW_d3d11.log)
  - [GRW_dxgi.log](https://github.com/doitsujin/dxvk/files/1911100/GRW_dxgi.log)
  - [GRW Wine-Staging 3.5 Backtrace.txt](https://github.com/doitsujin/dxvk/files/1911102/GRW.Wine-Staging.3.5.Backtrace.txt)

Note: Wined3d does not even initialized a window before crashing.

**Comment by doitsujin** [comment]
@popsUlfr Does this game work with wined3d?

Based on your trace, the game seems to require support for `D3D11VideoDevice`, which DXVK does not and will never support, but it *might* be optional.

@ZereoX please open a separate issue, yours is obviously unrelated.

**Comment by popsUlfr** [comment]
@doitsujin 
> Does this game work with wined3d?

It freezes at the same point heh...

> Anyway, I cannot debug this issue without a proper apitrace.

It seems like most if not all Ubisoft/Uplay games are non-apitraceable from what I've seen. The process forks and calls Uplay, I guess ? So Apitrace exits and Uplay manages to start the process after all, it is just a pain.
I'll try to find more usable information if possible. Thank you.

**Comment by doitsujin** [comment]
If it does that, it might as well be a wine issue, similar to the one in Fallout 4 in case you're aware of that. Do you by any chance have a Windows install around where you can test that?

In case of forking executables, what you could try is to rename the program's executable to something like `ACS.orig.exe` and create a new file `ACS.exe` which would be an executable shell script like this:
```bash
#!/bin/bash
wine /something/apitrace.exe trace -a dxgi ACS.orig.exe
```
No guarantee that it works, it's a bit of a last-resort strategy but it might help.

**Comment by doitsujin** [comment]
@popsUlfr Please test this with the latest Nvidia beta driver, 396.18.05.

**Comment by mozo78** [comment]
The last beta Nvidia driver doesn't help either:
https://imgur.com/SeY7xok
https://imgur.com/e7GGTX9
https://imgur.com/vQwOlYF

**Comment by berillions** [comment]
Same problem than Nvidia user with my AMD Rx580 : 
[](https://imgur.com/a/FnWf5Zd)

**Comment by berillions** [comment]
@doitsujin I forgot to add the both log, sorry.

[ACS_d3d11.log](https://github.com/doitsujin/dxvk/files/2087371/ACS_d3d11.log)
[ACS_dxgi.log](https://github.com/doitsujin/dxvk/files/2087373/ACS_dxgi.log)

**Comment by doitsujin** [comment]
So, can someone try to record an apitrace? There are instructions on [the Wiki](https://github.com/doitsujin/dxvk/wiki/Common-issues) on how to do that for games which don't like being traced the normal way.

**Comment by mozo78** [comment]
I tried it but with apitrace the game crashes after the splash screen. Here you are the created file:
https://my.pcloud.com/publink/show?code=XZSzkf7ZqYwCHmIN217puIlLlzMmI8htLx2X

**Comment by doitsujin** [comment]
The renderig issues should be fixed with 9520c9b1b88fbb0749a18afa34505ba6034e5aa4.

**Comment by mozo78** [comment]
I don't know how to use this so I'll wai for someone else to try it. Will this fix be icluded in the next version of DXVK?

**Comment by mozo78** [comment]
Thank you! I'll try it and will report back ASAP!

**Comment by mozo78** [comment]
Unfortunately I get this after the intro movie:
![1](https://user-images.githubusercontent.com/38666396/44983990-dd1c5c00-af83-11e8-8150-c2e14b63b0ff.png)

**Comment by doitsujin** [comment]
Please test with 396.54.**02**. The game requires an updated revision of the `VK_EXT_vertex_attribute_divisor` extension which your current driver does not support.

**Comment by dreamhunt** [comment]
Yes silly me... It now works, GREAT job doitsujin!!!

**Comment by mozo78** [comment]
Hello doitsujin! I'm sorry for the reopening but what settings do you use for Assassin's Creed: Origins? I'm constantly getting:

https://pastebin.com/xdetMNf8

And DXVK logs are empty...

**Comment by doitsujin** [comment]
AC:Origins doesn't work on Linux due to DRM issues. I ran the game on Windows for testing.

**Comment by mozo78** [comment]
Ah, I see. Thank you for the clarification. Best regards!

**Comment by Firelfy** [comment]
Been following along here and am interested to test out that dxvk build with my copy of AC. I've got the correct nvidia drivers according to nvidia-smi.

My issue is I can't seem to find where I should put the dll's, in drive_c in the respective folders or is there a global proton dxvk folder I'm missing?

Cheers!

**Comment by mozo78** [comment]
You have to put the x64 dlls in the game's exe directory or in the wine's system 32 :)

**Comment by Firelfy** [comment]
Awesome, placing the dll's with the exe worked. Still unsure why installing the dll's to the wine prefix didn't work... Will have to look into that one.

**Comment by doitsujin** [comment]
If play it through Proton, you'll have to replace the DXVK DLLs inside the Proton install directory (in `proton-3.7/lib64/wine/dxvk` or something like that).

**Comment by howels** [comment]
Game closes after loading main menu. Menu appears, window closes.
[steam-368500.log](https://github.com/doitsujin/dxvk/files/3014998/steam-368500.log)
