### ISSUE TITLE
Spider-man: Shattered Dimensions Lightning is messed up while using dxvk

### ISSUE THREAD

**Issue by Laezor** [doitsujin/dxvk#2780]
### Its not a very major problem. I think the lightning of the game is messed up while using dxvk. The color of the suits are wrong.

I tried to do a trace but the game wouldn't run with the trace dll files. But it does run with dxvk d3d9.dll.

**Reports with no log files will be ignored.**

### Software information
Spider-man: Shattered Dimensions
32-bit
directx: 9.0c

![20220802191321_1](https://user-images.githubusercontent.com/32393101/182422720-9ee38992-e1f4-49a8-aaa8-7e610df669bb.jpg)

### System information
- GPU: Radeon (TM) RX 480 Graphics
- Driver: 21.50.21.11-220428a-379219C-AMD-Software-Adrenalin-Edition
- Wine version: Using windows 10
- DXVK version: Latest version (dxvk 1.10.3)

### Apitrace file(s)
- Put a link here
the game wouldnt run with apitrace dlls

### Log files
- d3d9.log: [Game_d3d9.log](https://github.com/doitsujin/dxvk/files/9243830/Game_d3d9.log)

### Images

- Before using dxvk 

![20220802190200_1](https://user-images.githubusercontent.com/32393101/182421065-737b83d6-5b3f-424d-823b-1f91c40482e6.jpg)
![20220802190204_1](https://user-images.githubusercontent.com/32393101/182421071-1bffbb7b-6f52-485d-9761-67057d3daeb0.jpg)
![20220802190211_1](https://user-images.githubusercontent.com/32393101/182421076-e8d35912-5f89-4d17-ac6f-efac0d2c4431.jpg)
![20220802190155_1](https://user-images.githubusercontent.com/32393101/182421080-dfa1f915-fdb7-4e67-8c73-1bfa8d141114.jpg)
- After using dxvk

![20220802190445_1](https://user-images.githubusercontent.com/32393101/182421267-e30d6021-e68c-436d-a7c4-0da1e9ab0cf2.jpg)
![20220802190450_1](https://user-images.githubusercontent.com/32393101/182421271-c7538104-9e11-4d20-b6ca-53947e6b45da.jpg)
![20220802190436_1](https://user-images.githubusercontent.com/32393101/182421279-e7e25ac8-e36a-411f-bf70-d22003937733.jpg)
![20220802190441_1](https://user-images.githubusercontent.com/32393101/182421282-898be4f5-4790-4dec-bb77-ab2cd2fd182a.jpg)

**Comment by Iglu47** [comment]
> I tried to do a trace but the game wouldn't run with the trace dll files. But it does run with dxvk d3d9.dll.

this game is no longer available for purchase on Steam, so you'll have to get apitrace somehow.
just for sure: since you know the game is 32-bit did you double-check that the 32-bit apitrace dll was used?

**Comment by Laezor** [comment]
> this game is no longer available for purchase on Steam, so you'll have to get apitrace somehow. just for sure: since you know the game is 32-bit did you double-check that the 32-bit apitrace dll was used?

apitrace-10.0-win32.7z I assume its this one?

**Comment by Iglu47** [comment]
> apitrace-10.0-win32.7z I assume its this one?

yes, this correct. try latest https://github.com/apitrace/apitrace/releases/download/11.1/apitrace-11.1-win32.7z

**Comment by Laezor** [comment]
I dragged and dropped d3d9.dll since the game is using dx9. I get the same error as the previous versio
![pCy9Mq5nNf](https://user-images.githubusercontent.com/32393101/182452983-df1cca6d-84f7-41a2-9e66-e2f89e462a49.png)
n

**Comment by Iglu47** [comment]
Sadly, I'm out of ideas. Maybe changing Windows compatibility will help, or an antivirus is present and interferes. I do not know.

**Comment by Laezor** [comment]
I think the trace worked! I have to uncheck the windows compatibility mode! 

I uploaded the trace in mega I hope thats alright!

- trace: [trace file](https://mega.nz/file/BlIyTahS#T5N-6pJ3QlpjGomZXetdArZNq2j4aE5tIy7xR2B7bPo)

**Comment by K0bin** [comment]
Trace works, I'll take a look.

**Comment by K0bin** [comment]
Trace works, I'll take a look.

**Comment by K0bin** [comment]
That PR should fix it.

**Comment by Irinu** [comment]
Hello so how do you disable fetch4 or what should i do to fix this issue im having this issue on linux and would like to fix it as well so what do i do with the trace fill or how do i restrict fetch4 to single channel format thank you

**Comment by Iglu47** [comment]
> Hello so how do you disable fetch4 or what should i do to fix this issue im having this issue on linux and would like to fix it as well so what do i do with the trace fill or how do i restrict fetch4 to single channel format thank you

thanks for the response, we have already received everything need and the problem will be fixed soon (thanks @K0bin)

**Comment by Irinu** [comment]
so will this problem be fixed for windows and Linux, also will this problem be a file fix or a program fix thank you

**Comment by K0bin** [comment]
Use this build: https://github.com/doitsujin/dxvk/suites/7638569632/artifacts/317650751

**Comment by Irinu** [comment]
@K0bin what do i do with this how do i set this up i’m on linux btw so is it going to be different for me

**Comment by Iglu47** [comment]
> @K0bin what do i do with this how do i set this up i’m on linux btw so is it going to be different for me

For Proton 7.0 you can temporarily (you can make a backup or download/restore Proton 7.0 completely) replace `~/.local/share/Steam/steamapps/common/Proton 7.0/dist/lib/wine/dxvk/d3d9.dll` with the version from the build from the link above. You need to use the x32 version. 
Or wait. Sooner or later it will be in Proton anyway.

**Comment by Irinu** [comment]
@K0bin thank you it works on 7.0 proton but is it possible to use it on Proton GE or if you could make it work on if possible if not it's okay but if you are able to the one that I am using is Proton 7.1-GE 2 thanks again. P.S the reason that I need it on Proton GE is that i am using proton tricks to get the sound working and the sound doesn't work on 7.0

**Comment by Iglu47** [comment]
@Irinu the same for Proton-7.1-GE-2
but this path `~/.local/share/Steam/steamapps/compatibilitytools.d/Proton-7.1-GE-2/files/lib/wine/dxvk/d3d9.dll`

**Comment by Irinu** [comment]
hello yes i have tried this but every time i try to boot up the game it crashes i click play and then it starts up and then closes i will try this again thought to make sure

**Comment by Irinu** [comment]
@K0bin ya it keeps crashing what should i do?

**Comment by Iglu47** [comment]
> hello yes i have tried this but every time i try to boot up the game it crashes i click play and then it starts up and then closes i will try this again thought to make sure

probably related to increased minimum requirements (depends on hardware, distribution, Wine build, etc.)
@Irinu could you try this build? https://github.com/Iglu47/dxvk/suites/7640254756/artifacts/317762439 - it's based on 1.10.3 and has no increased minimum requirements yet
(**don't download or use unverified files** full build log here: https://github.com/Iglu47/dxvk/actions/runs/2786804851)

**Comment by Irinu** [comment]
yes i will try it right now

**Comment by Irinu** [comment]
@Iglu47 hello I have tried but to still no prevail i click play starts then crashes is there any way i can get xact to work on proton 7.0.3 i have tried protontricks but still ends up not working

**Comment by Iglu47** [comment]
> @Iglu47 hello I have tried but to still no prevail i click play starts then crashes is there any way i can get xact to work on proton 7.0.3 i have tried protontricks but still ends up not working

then it's probably a problem unrelated to dxvk. maybe it's worth clearing the cache (looks like Game.dxvk-cache), but that's all I can advise at the moment.

**Comment by Irinu** [comment]
@Iglu47 i was wrong it worked all it needed was a restart thank you so much yall are the best

**Comment by Iglu47** [comment]
ah, somehow misread about that it works on proton 7.0, then everything should be fine.
thanks for the tests.

**Comment by Laezor** [comment]
> Use this build: https://github.com/doitsujin/dxvk/suites/7638569632/artifacts/317650751

Alright I was finally able to test it out. The fix is working! 
![20220803130729_1](https://user-images.githubusercontent.com/32393101/182584059-3192f525-d3af-4b64-9800-c3fbaee7c021.jpg)

![20220803130935_1](https://user-images.githubusercontent.com/32393101/182584072-11cdec52-0f77-4e93-83f8-461019fc4559.jpg)

The lightning texture problem was also in-game too. But it seems the fix worked in-game too!

**Comment by K0bin** [comment]
Great, thanks for confirming.

**Comment by K0bin** [comment]
I'd prefer to keep this open until we merge the fix.

**Comment by Laezor** [comment]
Oh, sorry for that then! Quick question is there a discord server?

**Comment by Irinu** [comment]
@Laezor for spider-man shattered dimensions no but for steam deck yes there is just search steam deck discord and you’ll find it

**Comment by mahoneyd** [comment]
Hi, this works great for the color, however on steam deck dvxh-async really boosts performance. Is it possible you can post a build with this fix and dxvh-async. Thanks a lot.

**Comment by K0bin** [comment]
No. DXVK Async is not officially supported.
