### ISSUE TITLE
black mesa no ui or background when starting game

### ISSUE THREAD

**Issue by amnnoob** [doitsujin/dxvk#2785]
as in the title, nothing shows up when i start black mesa , i use 7launcher to play
![Uploading 16596174485131087937058.jpg…]()

**Comment by amnnoob** [comment]
i tried and nothing works

**Comment by K0bin** [comment]
thekovic is exactly right. The new Black Mesa UI cannot work on Windows with DXVK.

I also have no idea what 7launcher is but given that they advertise a modded CSGO client, I'm gonna assume it's piracy.

**Comment by amnnoob** [comment]
iys not piracy its a launcher for the game you need the oficial data

**Comment by K0bin** [comment]
Either way, point still stands. -oldgameui works around the issue and the game is known to work fine.

**Comment by amnnoob** [comment]
it does not
i have windows 7 ultimate 64bits
4gb ram
and an intel gma 4500mhd graphics driver

**Comment by Joshua-Ashton** [comment]
Intel GMA does not even support Vulkan or DirectX 11.

**Comment by amnnoob** [comment]
my pc supports directx 11 and i can prove it
![Uploading 16596938975811285036831.jpg…]()
