### ISSUE TITLE
Warriors Orochi 3 Ultimate Definitive Edition crashes when going to Preparation Screen on Steam Deck

### ISSUE THREAD

**Issue by AJuujarvi** [doitsujin/dxvk#2787]
Whenever I try to run Warriors Orochi 3 Ultimate Definitive Edition on my Steam Deck, the game crashes once it gets to the Preparation screen after clicking on Story Mode. It closes the game entirely. When I test it in Desktop Mode, it works. This appears to be a regression as it worked recently. I narrowed it down to be working with DXVK commit 73b27a7eab and crashing as of commit ea76bfd019. This was by comparing the DXVK included with experimental-bleeding-edge-7.0-21099-20220728-pf97544-wf05d1d-d73b27a-vd00d03 and experimental-bleeding-edge-7.0-21137-20220729-pf97544-wf05d1d-dea76bf-vd00d03 respectively. It appears to be a race condition as it is "fixed" with heavy Proton logging.

You can quickly skip all the cutscenes by pressing Start and selecting Skip. It doesn't change anything if you let them play or skip them.

### Software information
Warriors Orochi 3 Ultimate Definitive Edition
Settings Used: Medium preset, 1280 x 720 resolution, Fullscreen, Vsync 60.

### System information
- Valve Steam Deck
- OS Build: 20220802.1
-Kernel Version: 5.13.0-valve21-1-neptune-02209-g2a5bdc1101a0
- Wine version: Proton experimental-bleeding-edge-7.0-21669-20220804-pf97544-w097fc8-d37a2b0-vd00d03
- DXVK version: v1.10.1-448-g37a2b025

### Apitrace file(s)
Attempting to get an API trace causes the game to crash on boot.

### Log files
- d3d9.log: [WO3U_d3d9.log](https://github.com/doitsujin/dxvk/files/9262596/WO3U_d3d9.log)
- d3d11.log:[WO3U_d3d11.log](https://github.com/doitsujin/dxvk/files/9262597/WO3U_d3d11.log)
- dxgi.log:[WO3U_dxgi.log](https://github.com/doitsujin/dxvk/files/9262598/WO3U_dxgi.log)

**Comment by doitsujin** [comment]
Can you post the full Proton log?

I **strongly** doubt that any of the commits in question are even capable of introducing a race condition, but I wouldn't be surprised if the game code had a bunch of those.

**Comment by doitsujin** [comment]
I can't seem to run the game on my desktop, all I'm getting is a black screen after the initial K-T logo where presumably a video is supposed to be playing, but it's impossible to progress past that. Using Proton-Experimental.

**Comment by doitsujin** [comment]
Managed to get this to work on my Deck, the above commit should fix this. You were spot-on, it's a race condition.

**Comment by Kanadeforever** [comment]
Consistent with @XanderXA's description, not only Orochi3 DE, Koei Tecmo's other games also have this problem, it seems that 3D games made with the same engine will have this problem
