### ISSUE TITLE
Path of Exile fails to launch with "Failed to create WIC Factory"

### ISSUE THREAD

**Issue by gravndal** [doitsujin/dxvk#28]
Wine proper has the same issue for whatever it's worth: https://bugs.winehq.org/show_bug.cgi?id=42695

### Software information
DXVK https://github.com/doitsujin/dxvk/commit/05f00088919467b312888f15d8f38f66b1b0e7f5

https://www.pathofexile.com/
Also available on steam if that's of interest: http://store.steampowered.com/app/238960/Path_of_Exile/

Everything low with:
```
[DISPLAY]
directx_version=11
```
The game defaults to dx11 on Windows 7+ afaik.

### System information
- GPU: RX480
- Driver: mesa 17.3.2
- Wine version: Staging 2.21

### Apitrace file(s)
Running `$ apitrace trace -o poe.trace wine /path/to/PathofExile_x64.exe` did not generate a trace.

### Log files
- d3d11.log: [d3d11.log](https://github.com/doitsujin/dxvk/files/1652008/d3d11.log)
- dxgi.log: [dxgi.log](https://github.com/doitsujin/dxvk/files/1652009/dxgi.log)

**Comment by doitsujin** [comment]
Not directly related to D3D11, this is something that needs to be fixed in Wine.

**Comment by gravndal** [comment]
Yeah I completely missed the `++ b/dlls/ole32/compobj.c` in https://bugs.winehq.org/attachment.cgi?id=59204&action=diff making it seem like the diff only touched `b/dlls/dxgi/utils.c`.

Anyway, running it with the relevant bit of the patch applied yields a different results:
* Game reports an exception:
![2018-01-22-15 22 42](https://user-images.githubusercontent.com/4656860/35225433-9a247df2-ff88-11e7-99e0-cfb52943c82e.png)
* d3d11.log: [d3d11.log](https://github.com/doitsujin/dxvk/files/1652284/d3d11.log)
* dxgi.log: [dxgi.log](https://github.com/doitsujin/dxvk/files/1652286/dxgi.log)

Still no apitrace.

**Comment by kakra** [comment]
@gravndal Did you have any progress in solving this last exception you reported? Because I'm stuck at the same stage.

**Comment by gravndal** [comment]
@kakra The game runs just fine with Mesa 18.1.1, and recent builds of DXVK and Wine Staging with the relevant half of the patch I linked applied, namely:
```diff
--- a/dlls/ole32/compobj.c
+++ b/dlls/ole32/compobj.c
@@ -3213,6 +3213,7 @@
 {
     MULTI_QI multi_qi = { iid };
     HRESULT hres;
+    CoInitialize(NULL);
 
     TRACE("(rclsid=%s, pUnkOuter=%p, dwClsContext=%08x, riid=%s, ppv=%p)\n", debugstr_guid(rclsid),
           pUnkOuter, dwClsContext, debugstr_guid(iid), ppv);
```

**Comment by FedoraTipper** [comment]
It seems that non-ge builds of wine struggle with this. 3.11 PBA and staging cause the error, however 3.5 ge build works fine.

**Comment by kakra** [comment]
Meanwhile, I've fixed another problem (PoE couldn't load textures). My wine patchsets include the windowscodecs patches from staging which fixes this problem and it runs flawlessly. I'm currently in the process of upgrading the patches to wine-3.12. You can have a look here:

https://github.com/kakra/wine

Please export patches from the branches as you feel needing them. `patches-3.xx/wincodecs` is definitely one of the needed patches. The patches are based against vanilla wine and work with dxvk. I'm running it successfully: PoE works mostly without stutters (only when shaders are seen the first time), and works pretty well in 4k resolution (40+ fps) without dynamic resolution dropping it back to 1/2 resolution.

The pulseaudio patches allow PoE to see your headset/headphones as a separate device so you can assign them within PoE.

The rest are some more or less necessary bugfixes and performance patches you may want to use. This patchset also runs other games here like Skyrim SE and Witcher 3 with DXVK without problems so far.
