### ISSUE TITLE
Graphical glitches on SAO: Fatal Bullet

### ISSUE THREAD

**Issue by salvadorp2001** [doitsujin/dxvk#280]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

Character models have a weird bug where it looks like some of the polygons are slightly glitching around. I don't quite know how to explain it so here's a video: https://www.youtube.com/watch?v=pEvG3razCBs
It's recorded on dxvk v0.41-git (8508994) although the issue remains on v0.42-git (56ce794). The game so far seems otherwise playable, just some stutters when new shaders appear though that might just be because my GPU barely meets minimum.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

Sadly it crashes on start without dxvk so I can't do an apitrace.

### Software information
Sword Art Online: Fatal Bullet
Settings used (although it seems to happen no matter what settings I use):
Antialiasing Medium
Ambient Occlusion Off
Shadow Quality Medium
Motion Blur On
Texture Quality Medium
V-Sync Off
Depth of Field Off
Screen Percentage 100%
Resolution 1366x768
Borderless Window
60FPS

### System information
- GPU: R7 360 2GB
- Driver: Mesa 18.0.0-3 (AMDGPU on Arch Linux)
- Wine version: wine-staging-nine 3.5
- DXVK version: git master (56ce794)

### Apitrace file(s)
Couldn't do an apitrace since it crashes without dxvk

### Log files
- d3d11.log: [SAOFB-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/1911264/SAOFB-Win64-Shipping_d3d11.log)

- dxgi.log: [SAOFB-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/1911263/SAOFB-Win64-Shipping_dxgi.log)

**Comment by doitsujin** [comment]
You can record an apitrace with dxvk enabled as well. It isn't useful if the game crashes for example, but in this case it should be fine.

I've seen similar artifacts before in some games, probably a driver/llvm issue. If you can, please test if the artifacts go away with latest mesa-git and latest llvm-svn.

**Comment by salvadorp2001** [comment]
After waiting quite a bit for it to build (apparently the Arch Linux pkgbuild doesn't use more than one make job >:( ), I tried with mesa-git 18.1.0 (6a519a157b) and the glitches remained. Also, I tried to record apitrace but it complained about "Unknown interface query" and then crashed with a message saying "Fatal error". These are the d3d11 and dxgi logs from that run: 
[SAOFB-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/1911730/SAOFB-Win64-Shipping_d3d11.log)
[SAOFB-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/1911731/SAOFB-Win64-Shipping_dxgi.log)

**Comment by exolyte** [comment]
[This](https://patchwork.freedesktop.org/patch/224448/) mesa patch fixes similar issues in a bunch of other games.

**Comment by hakzsam** [comment]
Just tried the game, I confirm that https://cgit.freedesktop.org/mesa/mesa/commit/?id=73df16dcee79e2281c8d8a830dbbe6655359c82d fixes the issue.

The fix will be in mesa 18.0.5 and 18.1.1.
