### ISSUE TITLE
DXVK in system32, doesn't work | Don't try unless you know how to recover

### ISSUE THREAD

**Issue by rogue-agent** [doitsujin/dxvk#2801]
Hello world,

This will be a short stupid idea that i had. I wish it would work in the future.
There is an Unity game that I wanted to run in DXVK to see if I would get better performance on my Vega 8 GPU. As the d3d is not packaged with the game but directly invoked (supposedly) from UnityPlayer.dll at the Windows pre-packaged d3d inside C:\Windows\system32 I went ahead and booted into advanced mode and pulled up CMD to copy the files from latest release into the system32. I exited Advanced mode and I received a black screen after the loading icon.

I hope we can use Vulkan instead of DX on Windows in the future. For now atleast, I will go back in to start the recovery script. (On my github profile)

For now, I will try to create a custom UnityPlayer.dll that pulls on a specific d3d that I can replace.

**Comment by K0bin** [comment]
You can use DXVK with some games by simply placing the DXVK dlls next to the .exe file of the game. That works with most D3D9 games and quite a few D3D11 games. Besides that, there's not much we can do and that's one of the reasons why we don't really support Windows.
