### ISSUE TITLE
Witcher 3 Freezing at Loading Screen

### ISSUE THREAD

**Issue by ekianjo** [doitsujin/dxvk#281]
### Software information
Witcher 3 (GOG version) 1.31

### System information
- GPU: GTX970
- Driver: 396.x (latest)
- Wine version: 3.5
- DXVK version: 0.42
- Linux Mint 18.3

Witcher 3 used to work nicely with 0.41. In the meantime I updated the nVidia driver to 396 and DXVK to 0.42, and now while the game starts and reaches the menu, when loading my last save the game freezes at the loading screen and the process has to be killed since nothing is happening. Not sure if it's a nVidia driver regression or DXVK? 

I updated DXVK over my previous WINEPREFIX that was using 0.41 - I assume this was OK to do so.

**Comment by doitsujin** [comment]
Works fine on RADV as well, but please try what @Glog78 suggested, the game is known to be broken with the new shader compiler (although most people seem to get into the game at least).

**Comment by ekianjo** [comment]
Thanks, I will try @Glog78 's recommendation and report back.

**Comment by ekianjo** [comment]
mm, I can now get into the game, but it stutters like every 2 seconds, and after playing a few minutes it halts to a freeze again. 

@doitsujin is it possible to me to come back to 0.41 version of DXVK using the 0.41 installer, just to see if this changes anything?

**Comment by doitsujin** [comment]
Just download the 0.41 dlls and see if it works?

**Comment by ekianjo** [comment]
OK will check it out tomorrow.

**Comment by ekianjo** [comment]
I did not downgrade to 0.41, and I am closing this issue. Just trying to start the game several times made the issue go away. Maybe at first there were too many many shaders being compiled at once, every subsequent launch of the game made it smoother and smoother, and now it works just like before. 

Note: I did use __GL_NextGenCompiler=0 however.
