### ISSUE TITLE
DXVK Crashes after skipping Vulkan adapter(s)

### ISSUE THREAD

**Issue by eyand** [doitsujin/dxvk#2811]
Was working fine with no issues until this last week. Now, certain games crash out with either no report, or "no compatible graphics card found". Looking at the end of the Proton logfile I got when starting Apex Legends shows two warnings for skipping the two adapters (my graphics card and llvmpipe) with no description, and then reporting that no adapters were found.

### Software information
Tested not working with Apex Legends and HOI3.

### System information
- GPU: Nvidia 1070ti
- Driver: nvidia-driver-515.65.01
- Wine version: 5.0-3
- DXVK version: 1.5.4

### Apitrace file(s)
- Put a link here

### Log files

[apex_noload.log](https://github.com/doitsujin/dxvk/files/9301584/apex_noload.log)

**Comment by Blisto91** [comment]
The wine version and dxvk aren't the ones you use in the log which experimental and dxvk master (well close to)

Anyway master dxvk requires vulkan 1.3 now which needs at least the 510 driver for Nvidia. Which means it's not the 515 that is used.
Are you sure you have 515 installed? Both 64 and 32 bit?
Also are you using flatpak?

**Comment by eyand** [comment]
Sorry, between Vulkan, DXVK, and Proton all the versions it gets confusing to keep all of the versions and configurations and such straight, I appreciate you taking a look.

I can paste the result of ```apt search nvidia``` but it's very long, and appears to have multiple driver versions installed? Here is an excerpt that should give you an idea:

```
p   libnvidia-common-390                           - Shared files used by the NVIDIA libraries               
v   libnvidia-common-390:i386                      -                                                         
p   libnvidia-common-418                           - Transitional package for libnvidia-common-430           
p   libnvidia-common-418-server                    - Shared files used by the NVIDIA libraries               
v   libnvidia-common-418-server:i386               -                                                         
p   libnvidia-common-430                           - Transitional package for libnvidia-common-440           
p   libnvidia-common-435                           - Transitional package for libnvidia-common-455           
v   libnvidia-common-435:i386                      -                                                         
p   libnvidia-common-440                           - Transitional package for libnvidia-common-450           
v   libnvidia-common-440:i386                      -                                                         
p   libnvidia-common-440-server                    - Transitional package for libnvidia-common-450-server    
p   libnvidia-common-450                           - Transitional package for libnvidia-common-460           
p   libnvidia-common-450-server                    - Shared files used by the NVIDIA libraries               
v   libnvidia-common-450-server:i386               -                                                         
p   libnvidia-common-455                           - Transitional package for libnvidia-common-460           
p   libnvidia-common-460                           - Transitional package for libnvidia-common-470           
p   libnvidia-common-460-server                    - Transitional package for libnvidia-common-470-server    
p   libnvidia-common-465                           - Transitional package for libnvidia-common-470           
i   libnvidia-common-470                           - Shared files used by the NVIDIA libraries               
v   libnvidia-common-470:i386                      -                                                         
p   libnvidia-common-470-server                    - Shared files used by the NVIDIA libraries               
v   libnvidia-common-470-server:i386               -                                                         
p   libnvidia-common-495                           - Transitional package for libnvidia-common-510           
p   libnvidia-common-510                           - Shared files used by the NVIDIA libraries               
v   libnvidia-common-510:i386                      -                                                         
p   libnvidia-common-510-server                    - Shared files used by the NVIDIA libraries               
v   libnvidia-common-510-server:i386               -                                                         
p   libnvidia-common-515                           - Shared files used by the NVIDIA libraries               
v   libnvidia-common-515:i386                      -                                                         
p   libnvidia-common-515-server                    - Shared files used by the NVIDIA libraries               
v   libnvidia-common-515-server:i386

```
I'm way out of my depth so idk if it's typical to have the libraries etc... for 7 versions of the driver or not.

It's been a while since I got this set up, but I don't think that flatpak was used at any step since it was all handled by Steam/Proton.

**Comment by Blisto91** [comment]
No problem. 
I'm not very familiar with apt myself or drivers installed through it so I've asked if some else is able to provide assistance 👍

**Comment by Blisto91** [comment]
The kind shy folks in the discord said i could point to this 😁 

https://github.com/lutris/docs/blob/master/InstallingDrivers.md

The `i` in your list is apparently the one you have installed which is the 470 driver. So we need to update it. Might as well go for latest.

**Comment by eyand** [comment]
I suppose that this is getting into apt support territory rather than anything to do with dxvk, but I'm going to throw out what I'm seeing after running both the command in InstallingDrivers.md to add the ppas, as well as the command in the last comment, in case anyone knows what's obviously wrong (probably that I need to uninstall the existing driver before reinstalling). I'll follow up if I can resolve the issue myself and get upgraded to 515.

```
$ sudo apt install nvidia-driver-515
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-driver-515 : Depends: libnvidia-gl-515 (= 515.65.01-0ubuntu0.20.04.1) but it is not going to be installed
                     Depends: libnvidia-extra-515 (= 515.65.01-0ubuntu0.20.04.1) but it is not going to be installed
                     Depends: libnvidia-decode-515 (= 515.65.01-0ubuntu0.20.04.1) but it is not going to be installed
                     Depends: libnvidia-encode-515 (= 515.65.01-0ubuntu0.20.04.1) but it is not going to be installed
                     Depends: xserver-xorg-video-nvidia-515 (= 515.65.01-0ubuntu0.20.04.1) but it is not going to be installed
                     Depends: libnvidia-cfg1-515 (= 515.65.01-0ubuntu0.20.04.1) but it is not going to be installed
                     Depends: libnvidia-fbc1-515 (= 515.65.01-0ubuntu0.20.04.1) but it is not going to be installed
                     Recommends: libnvidia-compute-515:i386 (= 515.65.01-0ubuntu0.20.04.1)
                     Recommends: libnvidia-decode-515:i386 (= 515.65.01-0ubuntu0.20.04.1)
                     Recommends: libnvidia-encode-515:i386 (= 515.65.01-0ubuntu0.20.04.1)
                     Recommends: libnvidia-fbc1-515:i386 (= 515.65.01-0ubuntu0.20.04.1)
                     Recommends: libnvidia-gl-515:i386 (= 515.65.01-0ubuntu0.20.04.1)
E: Unable to correct problems, you have held broken packages.
```
P.S. To make this issue more searchable for anyone in the future, I want to paste the warnings and errors from the Proton log here:

```
warn:  Skipping Vulkan 1.2 adapter: NVIDIA GeForce GTX 1070 Ti
warn:  Skipping Vulkan 1.1 adapter: llvmpipe (LLVM 12.0.0, 256 bits)
warn:  DXVK: No adapters found. Please check your device filter settings and Vulkan setup.
warn:  OpenXR: Unable to get required Vulkan Device extensions size
44868.121:0140:018c:trace:loaddll:free_modref Unloaded module L"C:\\windows\\system32\\wineopenxr.dll" : builtin
44868.121:0140:018c:fixme:virtual:NtQueryVirtualMemory (0xffffffffffffffff,0x7fddc4eb0000,info_class=3,0x6017e220,48,(nil)) Unknown information class
err:   D3D11CreateDevice: No default adapter available
44868.121:0140:018c:err:seh:NtRaiseException Unhandled exception code c0000409 flags 1 addr 0x140e1e528
wine client error:194: sendmsg: Socket operation on non-socket
pid 62107 != 62106, skipping destruction (fork without exec?)
```

**Comment by eyand** [comment]
Ok got this solved with the driver update, just had to use ```$ sudo aptitude install nvidia-driver-515``` since it's better than regular old ```apt``` at handling the dependency issues that come with upgrading the nvidia drivers, since they are bundled with like 20 dependencies and libraries.

Not sure what happened to cause the issue in the first place, I think I may have told apt to remove unused packages which may have triggered the issue, or something else (dxvk/vulkan) upgraded to a new version but not the nvidia drivers.

If I knew more about the Proton/Vulkan backrooms and how it all worked I'd make a feature request for a more clear error message that asks the user to upgrade their driver in a case like mine.

Thanks to everyone for the support.

**Comment by Blisto91** [comment]
Glad you got it working.

For the feature request i have already made something similar for proton/steam
https://github.com/ValveSoftware/Proton/issues/6067

**Comment by JJones780** [comment]
**My problem was multiple GPUs**
My AMD CPU+GPU was interfering resulting in the "skipping Vulkan adapters". I had to specify my dedicated NVIDIA GPU by setting environment variable when running steam  i.e.    export  DXVK_FILTER_DEVICE_NAME="NVIDIA"; steam
Where "NVIDIA" is unique to a single card as found running command: vulkaninfo

**Persistant single game fix:**
Alternatively I was also able to fix it for the single game via browsing to the games local files ( where the exe is stored ) and adding the file  **dxvk.conf** containing the line:
`dxgi.nvapiHack = False`

I'm very hesitant to manually upgrade my nvidia drivers so I wasn't able to check if a newer Proton etc would fix the problem as well. re: https://github.com/doitsujin/dxvk/wiki/Driver-support.

**Comment by Blisto91** [comment]
@JJones780 I'm unsure if you are asking a question or have an issue?
If either then please open a new issue.

**Comment by JJones780** [comment]
I see that I was unclear. My apologies. I've added a clearer first line and slightly modified the second.

**Comment by Ramen-LadyHKG** [comment]
> **Another Potential Solution** For me this same problem was caused by multiple GPUs. My AMD CPU+GPU was interfering resulting in the "skipping Vulkan adapters". I had to specify my dedicated NVIDIA GPU by setting environment variable when running steam i.e. `export DXVK_FILTER_DEVICE_NAME="NVIDIA"; steam` Where "NVIDIA" is unique to a single card as found running command:` vulkaninfo`
> 
> **Persistant single game fix:** Alternatively I was also able to fix it for the single game via browsing to the games local files ( where the exe is stored ) and adding the file **dxvk.conf** containing the line: `dxgi.nvapiHack = False`
> 
> I'm very hesitant to manually upgrade my nvidia drivers so I wasn't able to check if a newer Proton etc would fix the problem as well. re: https://github.com/doitsujin/dxvk/wiki/Driver-support.

That fix my problem on Arch Linux. 
I couldn't run any game with my Nvidia. DXVK kept complaining no VK adaptor was found.
I try 'VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json vkcube' 
proves vulkan had no issues with my Nvidia.
no idea why it all just happened like this 3 months ago.


> System & Driver details: 
> lutris 0.5.13-6,  nvidia/535.113.01, 6.5.6-arch2-1-surface
> 
> My hardware: Surface Book 2 15" (i7-8650u, Nvidia GTX1060)
