### ISSUE TITLE
Nvidia driver will crash

### ISSUE THREAD

**Issue by bianchifan** [doitsujin/dxvk#2814]
System: Dell Studio XPS 1340, LInux MInt 20.3, Wine 7.0
Silhouette Studio does not run and in the WineHQ DB i found the tip with dxvk which should change the status from garbage to silver.
I did install latest version and SS did start up with Fonts missing in GUI dialogs.
The bad side: Other wine programs react now extremely slowly, IrfanView and Foxit Editor are no more usable. They need moe than 2 minutes to start, every action needs 30 to 180 seconds.
The same after uninstalling dxvk, wine programs are out of order.
Winecgf says "NVidia RnadR is broken" I should switch to Nouveau.
But Nouveau isn't possible for me because it slows down LInux programs which make use of the graphic processor.
![Bildschirmfoto vom 2022-08-11 08-33-04](https://user-images.githubusercontent.com/17491743/184079995-38066672-1caf-49ef-8272-c338d937bae6.png)

**Comment by xpander69** [comment]
I dont think this is the right place to report those types of issues. First of all thats Vista era laptop with Nvidia 9400M right? that doesn't even support vulkan correctly iirc? you are probably running old 340.xx drivers that are not supported by DXVK.
Your best bet is to run without DXVK. for the fonts missing you might want to install corefonts via winetricks. But no idea if thats the issue with it.

**Comment by Iglu47** [comment]
DXVK currently minimally requires the 470.x version of the nvidia driver. What version does the Dell Studio XPS 1340 support?

**Comment by Blisto91** [comment]
As said above this GPU does not support vulkan and only the 340 drivers so it won't work with dxvk sadly.

**Comment by bianchifan** [comment]
340 drivers are installed...
![Bildschirmfoto vom 2022-08-11 09-50-11](https://user-images.githubusercontent.com/17491743/184087976-b5bc87ab-deed-4817-a25d-65041543aac4.png)
![Bildschirmfoto vom 2022-08-11 09-49-49](https://user-images.githubusercontent.com/17491743/184087987-675b917f-5ce6-4d2c-bef8-fd8424d66f39.png)

**Comment by xpander69** [comment]
Yeah, you are out of luck with DXVK. That GPU doesnt support vulkan and the drivers don't either.
