### ISSUE TITLE
[d3d9] GTA San Andreas: Broken HUD (regression)

### ISSUE THREAD

**Issue by HunterCZ122** [doitsujin/dxvk#2818]
Discovered regression with HUD when investigating #2283 with latest master and #2817
Works fine with 1.10.x branch
![Screenshot_20220812_205748](https://user-images.githubusercontent.com/23011428/184436028-fd008033-7e79-456f-873e-940b744fda78.png)
![Screenshot_20220812_210347](https://user-images.githubusercontent.com/23011428/184436071-3097836c-b162-46e7-8966-76910d32ff21.png)

### Software information
Grand Theft Auto: San Andreas, Very High 8xMSAA

### System information
- GPU: NVIDIA GeForce GTX 1660 Ti
- Driver: 515.49.10
- Wine version: Proton Experimental
- DXVK version: v1.10.1-572-g46cb05ce and #2817

### Apitrace file(s)
- [gta-sa.trace](https://drive.google.com/file/d/1IFngaIANvHmiubWnoc_tf2AN0g32w7uS/view?usp=sharing)

### Log files
- d3d9.log: [gta-sa_d3d9.log](https://github.com/doitsujin/dxvk/files/9329555/gta-sa_d3d9.log)

**Comment by Blisto91** [comment]
Regression happened in the flat shading pr.
Works with the master commit before 4f0c217
Broken on master after flat shading was merger. Only tested 7789fd5 of the 4 commits.
