### ISSUE TITLE
Warhammer: End times vermintide doesnt work

### ISSUE THREAD

**Issue by Gibbz** [doitsujin/dxvk#282]
Warhammer: End times vermintide doesnt work under dxvk.
It works with some issues under regular wine staging.

http://store.steampowered.com/app/235540/Warhammer_End_Times__Vermintide/

https://pastebin.com/8Z32mGY4

**Comment by doitsujin** [comment]
How about describing what "doesn't work" means and filling in the issue template and actually? I didn't make it for fun.

**Comment by doitsujin** [comment]
Closing this due to the lack of information.
