### ISSUE TITLE
[d3d9] Images are never created with VK_IMAGE_USAGE_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT

### ISSUE THREAD

**Issue by werman** [doitsujin/dxvk#2825]
Looking through the code (as of 6baaa3a) to see how `VK_EXT_attachment_feedback_loop_layout` is used, I noticed that `VK_IMAGE_USAGE_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT` is never added to images even though there are transitions to `VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT`.

**Comment by Joshua-Ashton** [comment]
Good catch!
