### ISSUE TITLE
doesn't install

### ISSUE THREAD

**Issue by Toni500github** [doitsujin/dxvk#2827]
i have wine 7.15 with wineprefix and when try to install dxvk it gives me this
setup_dxvk.sh: 31: 0: not found
wine: configuration in L"/home/user/.wine" has been updated.
setup_dxvk.sh: 86: Bad substitution

**Comment by Blisto91** [comment]
Can you sho2 the full command you use when calling the setup script?
Also is that the full output of the error?

**Comment by doitsujin** [comment]
Make sure to execute the script directly and **not** source it into a different shell.
