### ISSUE TITLE
Any possibility on supporting HDR?

### ISSUE THREAD

**Issue by Abraham19970226** [doitsujin/dxvk#2832]
I'm a Windows user, found DXVK improves some gaming performance significantly. Really appreciate your work, but I also found using DXVK disables HDR in games even with HDR monitor and RTX 3090, any chance we are fixing this?

If not, still I appreciate your work very much!

**Comment by doitsujin** [comment]
The Linux desktop ecosystem does not support HDR at the moment, so this is not possible for us.
