### ISSUE TITLE
[d3d9] Venetica - Gold Edition - crash on startup 

### ISSUE THREAD

**Issue by dlshinobi** [doitsujin/dxvk#2837]
Game doesn't work with dxvk-master, fine with v.1.10.3.
Using dxvk-master, the ONLY "fix" I found was to set workaround option "d3d9.textureMemory = 0".
Other values: 128, 256, 512, 1024, 2048, doesn't work either.
I guess it's another "unmap memory" bug.
P.S. Game executable name: "Venetica.exe"

### Software information
Venetica - Gold Edition

### System information
- GPU: nVidia GTX 960
- Driver: 515.49.10
- Wine version: proton 7.0-4
- DXVK version: 1.10.3, 2.0 (master)

### Apitrace file(s)
- https://drive.google.com/file/d/1pjbEh0vYcl0OrlQy3aNCb75hN4YfRSru/view?usp=sharing

### Log files
- https://drive.google.com/file/d/1Tra4RdioSCceME-gbnHoETFktbXub4uD/view?usp=sharing

**Comment by doitsujin** [comment]
Can you test if it works with this PR: https://github.com/doitsujin/dxvk/pull/2833

This should work around crashes when the game performs out-of-bounds writes to a mapped resource.

**Comment by dlshinobi** [comment]
> Can you test if it works with this PR: #2833
> 
> This should work around crashes when the game performs out-of-bounds writes to a mapped resource.

Already tried, no dice.
