### ISSUE TITLE
[d3d11] PickCrafter crashes after alt-tabbing and opening window again

### ISSUE THREAD

**Issue by SlimDread** [doitsujin/dxvk#2840]
### Software information
Pickcrafter, default settings

### System information
- GPU: NVIDIA Geforce GTX 1050
- Driver: Latest Vulkan Beta (516.89)
- DXVK version: dxvk-master-85cc87e42a9adaa631593abfd06ec281001eae63
- OS: Windows 10 64bit

### Log files
- d3d11.log: [PickCrafter_d3d11.log](https://github.com/doitsujin/dxvk/files/9388024/PickCrafter_d3d11.log)
- dxgi.log: [PickCrafter_dxgi.log](https://github.com/doitsujin/dxvk/files/9388025/PickCrafter_dxgi.log)

**Comment by Blisto91** [comment]
I am not reproducing on Linux through proton or regular wine. This is the steam version and with a amd R9 380.

Does this also happen with 1.10.3?
Also try latest master. https://github.com/doitsujin/dxvk/actions/runs/2890252958

**Comment by Blisto91** [comment]
Regression in 1.5.
With 1.4.6 i am able to get back ingame after a alt tab on windows. Haven't checked the mouse issue on linux without fshack yet.

**Comment by doitsujin** [comment]
I hate Windows issues.

Guess we'll just force-disable exclusive fullscreen on Windows for D3D11 apps then if it causes issues since it doesn't really do anything useful anyway. We can't emulate DXGI behaviour correctly with Vulkan WSI.

**Comment by Blisto91** [comment]
Original hunch was wrong. Didn't notice it was also a issue in windowed mode.

Issue starts at this commit https://github.com/doitsujin/dxvk/commit/2d0c9127f339b60e6f4de7bd8cb40168399e7390 
Here it crashes for me after alt tab out and in

Next commit makes it not directly crash for me but instead the game stops responding and you cant get it in focus again
https://github.com/doitsujin/dxvk/commit/aa40decc23f27bcb25bd8e61a76c032fd99ada59

**Comment by Blisto91** [comment]
@SlimDread Are you able to confirm that this now works with dxvk 2.3?
