### ISSUE TITLE
Possible Helix Toolkit dx9 issues

### ISSUE THREAD

**Issue by BareGamer** [doitsujin/dxvk#2860]
I was making something akin to Minecraft with PascalABC.NET's "Graph3D" library which is based on HelixToolkit, as far as I understand. As it is windows-only, I decided to see if it would be practical to try the game on Linux,  so I started with dxvk to see if the graphics will be translated correctly. d3d9 was the only dll that worked, but with severe graphical issues(video and log attached). I tried that on Windows, so the issue might be in AMD's Vulkan drivers, but I am not sure about that, so the results of testing on Linux will be added later too.

Tested with the latest 1.10.3 binary release. 

### System information
- GPU: Vega 8
- Driver:  Adrenalin 10.21.10044.0
- Wine version: tested on Windows 11
- DXVK version: 1.10.3

The app doesn't seem to be traceable: the trace size is 2.6 MB, plus no issues occur. Afterburner doesn't show FPS either
[HelixToolkitCraftABC_d3d9.log](https://github.com/doitsujin/dxvk/files/9396452/HelixToolkitCraftABC_d3d9.log)
[dxvk.webm](https://user-images.githubusercontent.com/78811370/185987383-5c4d8f67-ce28-423d-990b-28995052e168.webm)
.
Edit: oh, I missed issue #2749 somehow

**Comment by K0bin** [comment]
I need a trace to look into this.

Could be a case of #2749

**Comment by BareGamer** [comment]
Yeah, looks like it. Missed that one somehow. I haven't had success with tracing the app, but I can upload it here

**Comment by BareGamer** [comment]
[HelixToolkitCraftABC.zip](https://github.com/doitsujin/dxvk/files/9396601/HelixToolkitCraftABC.zip)

**Comment by K0bin** [comment]
That just ends instantly. Does it work on Windows if you only have those 2 files?

**Comment by BareGamer** [comment]
Forgot about the textures folder. You need to extract it to the same directory as the exe. No geometry is rendered.
[textures.zip](https://github.com/doitsujin/dxvk/files/9396620/textures.zip)

**Comment by K0bin** [comment]
Same thing with the textures. It just exits instantly.

**Comment by BareGamer** [comment]
That’s weird. Does it say anything in the console window for a split second maybe? I am going to look into why it doesn’t work meanwhile.

**Comment by BareGamer** [comment]
Doesn't sound helpful, but on my machine, it works. However, I did a trace. Maybe it will somehow hel
[HelixToolkitCraftABC.zip](https://github.com/doitsujin/dxvk/files/9396786/HelixToolkitCraftABC.zip)
p

**Comment by Blisto91** [comment]
@BareGamer Can you test this issue with https://github.com/doitsujin/dxvk/pull/3392 ?
You can grab a build here https://github.com/doitsujin/dxvk/actions/runs/4893877539

**Comment by BareGamer** [comment]
Sorry for the late reply. I finally got to test the latest release (2.2) with the app. Weirdly, it introduced another issue. A log is created but is empty because the app crashes, likely because it skips the Vulkan adapter for some reason. There is a log attached with all the info the app outputs before crashing.
[HelixToolkitCraftABC_d3d9.log](https://github.com/doitsujin/dxvk/files/11568270/HelixToolkitCraftABC_d3d9.log)

**Comment by Blisto91** [comment]
You need to update your GPU driver. Requirements were raised with the dxvk 2.0 release

**Comment by BareGamer** [comment]
Retested with the new drivers. All of the artifacts are gone, the app actually feels more responsive now.
