### ISSUE TITLE
Heroes of the Storm regression: White loading screen

### ISSUE THREAD

**Issue by EntropicEffect** [doitsujin/dxvk#287]
Starting with commit [f567921](https://github.com/doitsujin/dxvk/commit/f5679211cd188845b894b1e0bd1ed627bbf50b47) the loading screen of HotS is just a completely white screen and nothing progresses from there (fwiw the cursor is visible).

### Software information
Heroes of the Storm
Shaders set to ultra 
Tried turning down the gamma setting, no effect.

### System information
- GPU: NVIDIA 960m
- Driver: 390.48
- Wine version: 3.6-staging-pba 
- DXVK version: [f567921](https://github.com/doitsujin/dxvk/commit/f5679211cd188845b894b1e0bd1ed627bbf50b47)  (works with [654e9e6](https://github.com/doitsujin/dxvk/commit/654e9e6fd8ff94ab2c6a4c0cf2f65f3173de7e10) )

### Apitrace file(s)
https://drive.google.com/open?id=1nRKzXuupbLBLU_2nxqVOkyAtukuXZoE8

### Log files
- d3d11.log:
```
   info:  D3D11CreateDevice: Probing D3D_FEATURE_LEVEL_11_0
   info:  D3D11CreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
```
- dxgi.log: 
```


 info:  Enabled instance layers:
   info:  Enabled instance extensions:
   info:    VK_KHR_surface
   info:    VK_KHR_win32_surface
   info:  Intel(R) HD Graphics 530 (Skylake GT2):
   info:    Driver: 18.0.0
   info:    Vulkan: 1.0.57
   info:  GeForce GTX 960M:
   info:    Driver: 390.48.0
   info:    Vulkan: 1.0.65
  warn:  Vulkan extension VK_KHR_maintenance2 not supported
  info:  Enabled device extensions:
  info:    VK_KHR_descriptor_update_template
  info:    VK_KHR_maintenance1
  info:    VK_KHR_shader_draw_parameters
  info:    VK_KHR_swapchain
  warn:  DxgiFactory::MakeWindowAssociation: Ignoring flags
  warn:  DxgiSwapChain: Display mode changes not implemented
  info:  DxgiPresenter: Recreating swap chain:
   Format:       VK_FORMAT_B8G8R8A8_UNORM
   Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
   Buffer size:  1920x1080
```

**Comment by doitsujin** [comment]
Can you record an apitrace with dxvk instead of wined3d? wine does not implement the relevant functionality so the trace is not useful.

**Comment by MeissnerEffect** [comment]
> That said, does the game lock up or does it just render everything in white?

It doesn't lock up, music starts playing, and I can hear the sound of clicking menus if a randomly click around the screen

> Can you record an apitrace with dxvk instead of wined3d?

[apitrace with dxvk](https://drive.google.com/open?id=1iKC38lzFDIAH4BaHOUcL7YveczZ5Ec1S)

Didn't have wine debugging on earlier  seems like the logs are more verbose now

[d3d11 log](https://drive.google.com/open?id=1FGe9emokj76Yw45DsXO0hiq3xs7pNTY0)
[dxgi log](https://drive.google.com/open?id=127tqyJ0xoDzSIl62qEffP_Nv8YiyVl2S)

**Comment by simonvanderveldt** [comment]
First of all: thanks for the quick fix!

> Thanks. Looks like this is actually a game bug: Instead of setting Scaling and Offset in DXGI_GAMMA_CONTROL to (1,1,1) and (0,0,0) respectively, it sets both values to (1,1,1).

It sounds like this is something the developer (Blizzard in this case) did wrong. Is this something we should report to them?
