### ISSUE TITLE
Warcraft III: Reforged - 1.33.0.19203

### ISSUE THREAD

**Issue by DistantThunder** [doitsujin/dxvk#2872]
Hi, 

As usual, thank you for your hard work.
So Warcraft III : R. now works quite ok with latest Wine-GE and DXVK 1.10.3. However I've noticed that sometimes, it often slows down a lot during the same scene.

Illustration:
[debug_wow3_seq.webm](https://user-images.githubusercontent.com/3923810/186980271-1f66b3d6-e7a2-48e2-b73a-eccafc07c9bc.webm)

**Reports with no log files will be ignored.**

### Software information
Warcraft III - Max settings

### System information
- CPU: 5800X
- RAM: 64GB
- GPU: 6900XT
- Driver: Mesa 22.1.6-1 / AMDGPU 5.18.16
- Wine version: Wine-GE-7.26
- DXVK version: 1.10.3

### Apitrace file(s)
- N/A

### Log files
Logs:
* [Warcraft III.logs.tar.gz](https://github.com/doitsujin/dxvk/files/9436040/Warcraft.III.logs.tar.gz)

**Comment by Blisto91** [comment]
Please make a apitrace of the scene if you can https://github.com/doitsujin/dxvk/wiki/Making-a-Trace

**Comment by K0bin** [comment]
Whats wrong here? A 20 year old RTS game not being able to saturate a 6900XT is pretty expected.

**Comment by orklann** [comment]
@DistantThunder Do you use Lutris to run Warcraft III Reforged, or just vanilla Wine? I can not make Lutris to run it.

**Comment by orklann** [comment]
@DistantThunder What wine version did you use?
https://github.com/GloriousEggroll/wine-ge-custom
or 
https://github.com/GloriousEggroll/proton-ge-custom ?

**Comment by Blisto91** [comment]
@orklann Please refrain from double posting and also pinging people twice. Also there is no need to post two place.
And they are using the top one

**Comment by DistantThunder** [comment]
> Whats wrong here? A 20 year old RTS game not being able to saturate a 6900XT is pretty expected.
I don't know about maxing the GPU, but I certainly hope it could maintain 144 fps?


> Please make a apitrace of a troubling scene if you can https://github.com/doitsujin/dxvk/wiki/Making-a-Trace

I'll try though it's unlikely it'll run with Wine's D3D11.

**Comment by DistantThunder** [comment]
> @DistantThunder Do you use Lutris to run Warcraft III Reforged, or just vanilla Wine? I can not make Lutris to run it.

I couldn't run it until using latest Wine-GE-Custom (as specified in the description). It now runs from Lutris as well. No ESYNC nor FSYNC.

**Comment by Blisto91** [comment]
> I'll try though it's unlikely it'll run with Wine's D3D11.

That's fine. A trace with dxvk should do.

> It now runs from Lutris as well. No ESYNC nor FSYNC.

Does it work with ESYNC or FSYNC? If so then it's possible that can boost your performance.

**Comment by DistantThunder** [comment]
@Blisto91  How do you run an apitrace within Proton/Lutris?

**Comment by Blisto91** [comment]
If dxvk is already enabled in lutris or proton then the correct overrides should already be set. In that case you can just dump the apitrace DLLs mentioned in the guide next to the exe and then go ingame. The trace will appear in the desktop folder of the wine prefix used.
Remember to delete the apitrace DLLs after you are done.

**Comment by DistantThunder** [comment]
Ah yes, I'm under 1 fps. This won't yield proper results though because the perf problem is at a random. I also see it with WoW. 

Sometimes it runs OK, and then suddenly, on the same scene, it's starts hoovering a lot. I'd need to be able to activate the trace at those precise times. 

In its current form, I can't even notice when the problem is happening or not.

**Comment by orklann** [comment]
@DistantThunder I have some random crashes (sometimes) while using Lutris and the wine version you mentioned, so I just want to know which installation script you used?

[Battle.net](https://lutris.net/games/battlenet/)
or
[Warcraft III Reforged](https://lutris.net/games/warcraft-iii-reforged/)

**Comment by DistantThunder** [comment]
The second one.

**Comment by orklann** [comment]
Thank you.

**Comment by Blisto91** [comment]
Did you ever figure out if there was a issue with your system? :eyes:

**Comment by SoongVilda** [comment]
> Whats wrong here? A 20 year old RTS game not being able to saturate a 6900XT is pretty expected.

What?
![obrazek](https://user-images.githubusercontent.com/61845673/193568104-8c318512-3ecb-41d6-bf6a-462c046d4fcd.png)

**Comment by Blisto91** [comment]
I think he means the game is based on the original Warcraft 3 with a modified engine and graphics.

**Comment by K0bin** [comment]
Just look at the game. They replaced some textures and some models with higher fidelity versions but it's still far from a demanding game for the GPU.

**Comment by DistantThunder** [comment]
> Did you ever figure out if there was a issue with your system? eyes

Unfortunately, no.

Also, I don't really understand why I'm wrong to expect such a non-demanding game to run at max display refresh rate without drops. I don't understand why it being old and minimalist (vs modern games) has to do with maxing the GPU.

I may close and re-open this issue if I can ever accurately pinpoint what's going on. I've noticed this problem on other DXVK games as well now that I pay attention.

Just some moments where games will suddenly drop and struggle while the GPU is slowing down as well. Weird.

**Comment by Blisto91** [comment]
Hope you figure something out!

If the game ever goes on sale I'll get it myself probably. Then i can check out how it behaves on my pc.

**Comment by WinterSnowfall** [comment]
> Just some moments where games will suddenly drop and struggle while the GPU is slowing down as well. Weird.

I doubt it's the same problem I was having a while back, but thought I'd mention it anyway, maybe it helps in your case as well: my now ancient MB apparently has a very poor ASPM implementation which can cause stutter and occasional heavy frame drops while gaming. Disabling it altogether in the BIOS turned everything smooth as silk (in situations when the GPU can keep up, of course). It was an absolute PITA to get to the bottom of it, as you can imagine...

Oh, and also disable DXVK logging if you're launching your games from the terminal, as that also helps sometimes, depending on how "chatty" DXVK turns out to be because of what certain games are doing.

**Comment by DistantThunder** [comment]
> > Just some moments where games will suddenly drop and struggle while the GPU is slowing down as well. Weird.
> 
> I doubt it's the same problem I was having a while back, but thought I'd mention it anyway, maybe it helps in your case as well: my now ancient MB apparently has a very poor ASPM implementation which can cause stutter and occasional heavy frame drops while gaming. Disabling it altogether in the BIOS turned everything smooth as silk (in situations when the GPU can keep up, of course). It was an absolute PITA to get to the bottom of it, as you can imagine...
> 
> Oh, and also disable DXVK logging if you're launching your games from the terminal, as that also helps sometimes, depending on how "chatty" DXVK turns out to be because of what certain games are doing.

How did you figure it out? Did something appear in kernel logs?

When I have these perf loss, I try to look around the system CPU/ Mem / I/O nothing out of the ordinary.

Besides, for some reason, I already run with "pcie_aspm=off".

**Comment by WinterSnowfall** [comment]
> How did you figure it out? Did something appear in kernel logs?

Unfortunately, no. I tried disabling all possible power management options, including ACPI, and eventually narrowed it down to ASPM. But, as far as the kernel was concerned, everything looked fine on default verbosity.

> Besides, for some reason, I already run with "pcie_aspm=off".

Not that it helps the issue at hand, but probably for the best on a desktop system anyway.
