### ISSUE TITLE
Ys SEVEN regression, game displays white screen on boot and then black screen with white text boxes on main menu

### ISSUE THREAD

**Issue by AJuujarvi** [doitsujin/dxvk#2874]
When you boot the game it displays a pure white screen. When you get to the main menu it is a black screen with white boxes where text should be. I performed a bisect and found the problem commit to be c12cd1952cf8593f3f6064f7b785c7fc7bcf1c74
This was done in Proton using everything else frozen except for the DXVK directory.

### Software information
Ys Seven, fresh install

### System information
- GPU: Nvidia RTX 3060TI
- Driver: 515.65.01
- Proton version: 7.0-4
- DXVK version: e4fd5e9e8d335e8a2c0814829207cbd421f7e40e dxvk (v1.10.3)

### Log files
- d3d9.log:
[Ys7_d3d9.log](https://github.com/doitsujin/dxvk/files/9436286/Ys7_d3d9.log)

**Comment by Blisto91** [comment]
Just fixed an hour ago hehe https://github.com/doitsujin/dxvk/commit/bfd47ec8767e7589f86ce4b54372669da2963907

But thanks for wanting to take time bisecting it anyway :+1: :slightly_smiling_face:

**Comment by K0bin** [comment]
We just fixed that.

https://github.com/doitsujin/dxvk/commit/bfd47ec8767e7589f86ce4b54372669da2963907
