### ISSUE TITLE
[d3d9] Heroes Of Annihilated Empires crashes on startup

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#2879]
The game crashes on startup with DXVK (either 1.10.3 or current master), works fine with WineD3D. Tried limiting d3d9 total available memory to 2048 MB + memorytracktest (otherwise the game will complain about "insufficient memory"), however the crash still persists.

Captured a trace of loading up the game's menu, which crashes apitrace when trying to replay with DXVK :sweat_smile:, but similarly plays just fine with WineD3D.

P.S.: It appears WineD3D also needs the "videomemorysize=2048" winetrick to run the game properly, but with that set up it's all good.

### Software information
Heroes Of Annihilated Empires (GOG version)

### System information
- GPU: Nvidia GTX 1080
- Driver: 515.65.01
- Wine version: 7.15 Staging
- DXVK version: 1.10.3 / master 7ebd359

### Apitrace file(s)
[engine.trace.tar.xz](https://drive.google.com/file/d/1oin7VSkjLAQze1Zbq15qynm_F17V2xf1/view?usp=sharing)

### Log files
- d3d9.log: [engine_d3d9.log](https://github.com/doitsujin/dxvk/files/9443414/engine_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by Blisto91** [comment]
Such a nice sight with a well filled out issue 😁

**Comment by Joshua-Ashton** [comment]
Closed by https://github.com/doitsujin/dxvk/commit/c49b1ee3909fd48bde7598de9c60c3b53916d9dd
