### ISSUE TITLE
La Pucelle: Ragnarok - Rendering errors

### ISSUE THREAD

**Issue by AGraber** [doitsujin/dxvk#2883]
Rendering is broken on the entire game, aside from the startup logos and some menus (eg. gamepad/keyboard config and save/load menus) that were implemented as part of the PC version of the game.

### Software information
La Pucelle: Ragnarok - Default settings - [Store Page](https://store.steampowered.com/app/1866420/La_Pucelle_Ragnarok/)

### System information
- GPU: AMD Custom GPU 0405
- Driver: 4.6 (Compatibility Profile) Mesa 22.0.2 (git-71648faf15)
- Wine version: Proton 7.0-4
- DXVK version: [v1.10.3](https://github.com/doitsujin/dxvk/releases/tag/v1.10.3)

### Apitrace file(s)
(recorded on Windows with D3D11)
[LaPucelle_en.zip](https://github.com/doitsujin/dxvk/files/9455478/LaPucelle_en.zip)

### Log files
(recorded on Linux)
- [LaPucelle_en_d3d11.log](https://github.com/doitsujin/dxvk/files/9455600/LaPucelle_en_d3d11.log)
- [LaPucelle_en_dxgi.log](https://github.com/doitsujin/dxvk/files/9455601/LaPucelle_en_dxgi.log)

**Comment by Blisto91** [comment]
Hi and thank you for a nicely filled out issue report.
Can you post a screenshot of what the issue looks like? I've tried replaying your trace on my Nvidia setup (will try amd later) but it looked fine to menu.

**Comment by doitsujin** [comment]
![Bildschirmfoto](https://user-images.githubusercontent.com/25567304/187519316-476b1534-6c36-4481-b2b7-87fecb92ea48.png)
what exactly am I looking at here? Looks fine at a first glance.

**Comment by AGraber** [comment]
Sorry, I was about to post the screenshots but got sidetracked, here they are:
![image](https://user-images.githubusercontent.com/18301034/187520719-04c1a44b-6f55-4174-8ffd-8b190fc5d165.png)
![image](https://user-images.githubusercontent.com/18301034/187520832-091007f6-6ac6-4205-8dbc-c538f54a5fcd.png)
![image](https://user-images.githubusercontent.com/18301034/187520870-66681d03-854a-4e66-b149-edf2ad04b503.png)

**Comment by AGraber** [comment]
The same screenshots on Windows 11:
![LaPucelle_en_20220830_203633](https://user-images.githubusercontent.com/18301034/187521184-fb9efac2-2547-48f2-a9bf-f8e9796875e8.png)
![LaPucelle_en_20220830_203643](https://user-images.githubusercontent.com/18301034/187521180-697793bf-687c-46aa-a430-cf334ae6dde1.png)
![LaPucelle_en_20220830_203656](https://user-images.githubusercontent.com/18301034/187521176-6166b7cf-7e6e-4ea0-8a87-a97141f7b91b.png)

**Comment by Blisto91** [comment]
Could you try running the game with proton experimental. If that changes nothing then running with `PROTON_USE_WINED3D=1 %command%`
And if that also does nothing try using dxvk on windows and see if the same happens.

**Comment by doitsujin** [comment]
When replaying the trace it looks exactly the same here. Likely unrelated to DXVK.

**Comment by AGraber** [comment]
> Could you try running the game with proton experimental. If that changes nothing then running with `PROTON_USE_WINED3D=1 %command%` And if that also does nothing try using dxvk on windows and see if the same happens.

Using Proton Experimental behaves the same.
WineD3D causes the game to crash (on both experimental and 7.0-4).

Here's a proton log that ran with 7.0-4 and dxvk:
[steam-1866420.log](https://github.com/doitsujin/dxvk/files/9455908/steam-1866420.log)

> When replaying the trace it looks exactly the same here. Likely unrelated to DXVK.

Hmm, yeah, I also tried playing my Windows apitrace file on linux (apitrace's windows version on linux under same proton configuration as the game) on my Steam Deck, but it also seemed to look fine... the game on the other hand looks like on the screenshots.

It'd be great if you have time to help see what's the problematic component, but if it is indeed unrelated to DXVK then you can close this as well.

**Comment by AGraber** [comment]
Log of Proton 7.0-4 with WineD3D (which ends up crashing):
[steam-1866420.log](https://github.com/doitsujin/dxvk/files/9456012/steam-1866420.log)

**Comment by Blisto91** [comment]
Could you try installing `d3dcompiler_47` for the game with protontricks? Or winetricks set to the games wine prefix

**Comment by AGraber** [comment]
> Could you try installing `d3dcompiler_47` for the game with protontricks? Or winetricks set to the games wine prefix

Installing `d3dcompiler_47` with Protontricks and the game now displays properly with DXVK!
Here's the relevant log files if helpful:
[LaPucelle_en_d3d11.log](https://github.com/doitsujin/dxvk/files/9456500/LaPucelle_en_d3d11.log)
[LaPucelle_en_dxgi.log](https://github.com/doitsujin/dxvk/files/9456501/LaPucelle_en_dxgi.log)
[steam-1866420.log](https://github.com/doitsujin/dxvk/files/9456502/steam-1866420.log)

May I ask why does this fix work? What implements `d3dcompiler_47` if the normal version is missing?

**Comment by Blisto91** [comment]
I noticed in your proton log that it loads wines builtin of that DLL and saw there were some d3dcompiler fixme's that looked suspicious.

Builtin means that its using wines own version which seem to be incomplete or buggy here. When you use winetricks you install the official Microsoft DLL into your prefix and set it to be used.
Valve can't include that on their own for legal reasons or as a safety precaution relating to that at least. Simplified explanation maybe.

It would be appreciated if you could open a proton compatability issue and mention this workaround. Then there might also come eyes on that the wine version have issues with the game

**Comment by AGraber** [comment]
Thanks a lot for the explanation and the help everyone!

**Comment by otterboi12** [comment]
I'm sorry, but I'm completely new to linux. This thread seems really helpful, but I cannot get the gui for protontricks to work, nor do I understand how to install d3dcompiler from there. Can anybody explain this process further?

**Comment by otterboi12** [comment]
Specifically on the version Steam Deck uses

**Comment by Blisto91** [comment]
@otterboi12 Hi i was gonna take some screenshots showing how to do it. But it seems the protontricks gui indeed doesn't work on steam deck at the moment. https://github.com/Matoking/protontricks/issues/164
Sadly i wasn't even able to get the command line version working either.
