### ISSUE TITLE
Red Faction Armageddon anisotropy filtering overide

### ISSUE THREAD

**Issue by MartianMadman** [doitsujin/dxvk#2884]
Hey there, I feel I have been putting off reporting this issues for too long now. So basically dxvk anisotropy filtering override does not like Red Faction Armageddon and causes bizzare green pixels. One might ask why not use the ingame anisotropy filtering instead, well because the way the game handles anisotropy filtering is not good. You can see if you zoom in how the tiled floor on the bottom image retains it's detail as the texture gets further away from the view meanwhile the top image with the ingame aniso filtering gets blurred. Red Faction Armageddon can use either dx9 or dx11 and this issue happens with both of them.
![anisobug](https://user-images.githubusercontent.com/89256728/187549232-1c39b936-4d16-41fd-aa26-b8c19177870e.jpg)

\system info/
OS - ubuntu 22.04
GPU - nvidia gtx 1050ti
dxvk version - steam proton experimental

**Comment by doitsujin** [comment]
If it breaks the game then don't use the option. This kind of thing happening is entirely expected for games that rely on linear filtering behaving like, well, just plain linar filtering.

**Comment by MartianMadman** [comment]
Should I close this then?

**Comment by aufkrawall** [comment]
Yes, common issue with Nvidia & DXVK. Also happens in more recent Unreal Engine games like Stray, but was already an issue with ancient D3D9 games: https://github.com/doitsujin/dxvk/issues/1666

**Comment by MartianMadman** [comment]
Understood.
