### ISSUE TITLE
Insurgency Sandstorm crashing with Proton Experimental and dxvk (DX11)

### ISSUE THREAD

**Issue by puresick** [doitsujin/dxvk#2886]
After updating Proton Experimental recently via Steam Insurgency Sandstorm stopped working running with DX11.

I have [reported that issue on the Proton GitHub repository](https://github.com/ValveSoftware/Proton/issues/1651#issuecomment-1223200695), but we did only got so far.

@alasky17 in that issue above wondered if this might be a regression on dxvk and suggested me to open an issue here.

To summarize that issue:

Insurgency Sandstorm is an Unreal Engine game, which stopped running after updating Proton Experimental a few days ago. It does work enforcing DX12 via Steams startup parameters, but that has other problems by itself. Before that Proton update it worked quiet smooth. 

### Software information
Name of the game, settings used etc.
- Name: Insurgency Sandstorm
- Resolution: 2560x1440
- Display mode: Windowed (borderless)
- Vertical Sync: on
- Gamma 2.2
- Anti-aliasing: FXAA
- View Distancen Quality: Medium
- Texture Quality: High
- Effects Quality: Medium
- Foliage Quality: Medium
- Shadow Quality: Medium
- Post-processing Quality: Medium
- Frame Smoothing: on
- Frame Limiter: 90fps
- Resolution Scale: 100
- Motion Blur: on
- Scope Settings: Normal
- Dismeberment: On
- Ragdoll Count: Medium
- Foliage Interactions: Off
- Ambient Occlusion: On
- Anisotrophic Filtering: Off
- Tessellation: Off
- Screen Space Reflections: Off
- Dynamic Shadow Resolution: 256x256
- Cascaded Shadow Map Resolution: 256x256
- Texture Streaming Pool: off
- Hierarchical LOD Transition Method: Fixed Distance

### System information

- Kernel: Linux 5.19.5
- Gnome 42.4 (Wayland)
- CPU: AMD Ryzen 7 3700X
- RAM: 32GB
- GPU: AMD Radeon™ RX 5500 XT
- Driver: amdgpu
- Wine version: Proton Experimental
- DXVK version: [dxvk @ c49b1ee](https://github.com/ValveSoftware/dxvk/tree/c49b1ee3909fd48bde7598de9c60c3b53916d9dd)

### Apitrace file(s)
Sadly an api trace was not possible. It seems no `.trace` file is being generated at all.

I did follow the instructions from here: https://github.com/Joshua-Ashton/d9vk/wiki/Making-a-Trace
I tried putting the dlls into the same directory as the games `.exe` aswell as replacing the corresponding files with the ones in the `Proton Experimental` steam application folder, both with no usable result.

It is definetely possible that I made a mistake here. If you have any tips how to do an apitrace properly with Steam and Proton Experimental I am more than happy to try it again.

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by doitsujin** [comment]
Does D3D11 mode work with wined3d?

**Comment by doitsujin** [comment]
When exactly does the crash happen and what do I need to do to reproduce this?

So far the game is working fine here, it's not clear to me what I'm looking at.

**Comment by puresick** [comment]
@doitsujin Excuse me for the spare information on the issue. Below I try to give as much information as I can:

> When exactly does the crash happen and what do I need to do to reproduce this?

The game starts flawelessly into the main menu. I can navigate around without issue, change settings and so on. I can also choose which gamemode I want to play and start connecting to official and community servers. The region settings are always set to Europe.
The moment the loading screen after connecting to any server reaches between ~70% and 100% the game crashes reproducable.

I did try some different configurations/settings which I listed [in the Proton issue thread](https://github.com/ValveSoftware/Proton/issues/1651#issuecomment-1229536322), but they did not improve the situation.

> It's also not clear which Vulkan driver you are using (RADV, AMDVLK, or the proprietary driver?).

I am using `amdvlk`.

> Please post Proton logs so I can at least try to figure out what could potentially be going wrong here [...]

Of course, you find the log attached here:
[20220901-insurgency_sandstorm_proton_experimental.log](https://github.com/doitsujin/dxvk/files/9472357/20220901-insurgency_sandstorm_proton_experimental.log)

I also updated my system information above to be complete and matching [the info from the Proton issue](https://github.com/ValveSoftware/Proton/issues/1651#issuecomment-1229531732).

**Comment by Blisto91** [comment]
Do note that amdvlk is not directly supported. RADV is the primarily targeted driver.
Could you try with that and see if the issue still occurs?

**Comment by puresick** [comment]
@Blisto91 It seems you are onto something! Using RADV the game runs fine, i.e. no crashing during connecting to a server.

**Comment by K0bin** [comment]
Like Blisto said, AMDVLK is not supported.

**Comment by Blisto91** [comment]
@puresick if you want to you can try to report the issue at the amdvlk repo https://github.com/GPUOpen-Drivers/AMDVLK

**Comment by puresick** [comment]
@Blisto91 Yes I will do that, thank you!

Thank you all for your help :muscle:
