### ISSUE TITLE
[feature] able to define configuration properties through an environment variable

### ISSUE THREAD

**Issue by ranplayer** [doitsujin/dxvk#2894]
It would be useful if we were able to define the configuration properties through an environment variable (e.g: `DXVK_CONFIG=dxgi.syncInterval=1,d3d11.samplerAnisotropy=16`). 

It would be easier and faster for testing and customizing than creating a `dxvk.conf` file for every game. Also for integrating with GUIs (Steam, Lutris, etc...)

**Comment by pchome** [comment]
`alias dxvk='echo -e ${DXVK_CONFIG//,/\\n} > /tmp/dxvk.conf; $@'`

```
export DXVK_CONFIG=dxgi.syncInterval=1,d3d11.samplerAnisotropy=16
export DXVK_CONFIG_FILE=/tmp/dxvk.conf
dxvk less ${DXVK_CONFIG_FILE}
```
:man_shrugging:

**Comment by doitsujin** [comment]
This was actually planned and I just kind of forgot about it.
