### ISSUE TITLE
Bloodstained - Ritual of the Night Craft hanging

### ISSUE THREAD

**Issue by VladimirVSC** [doitsujin/dxvk#2898]
The game hangs very often during any crafting process. I have tried to run the game without DXVK installed and the bug didn't occur (though the graphic was totally corrupted, of course)

### Software information
Bloodstained - Ritual of the Night

### System information
- GPU: Geforce GTX 760
- Driver: 470.129.06
- Wine version: 7.0; 7.16
- DXVK version: 1.10.3

### Log files
[BloodstainedRotN-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/9518750/BloodstainedRotN-Win64-Shipping_d3d11.log)

[BloodstainedRotN-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/9518857/BloodstainedRotN-Win64-Shipping_dxgi.log)

[CraftBug.log](https://github.com/doitsujin/dxvk/files/9520424/CraftBug.log) (if necessary)

**Comment by Riesi** [comment]
Is there more to do or only crafting something?
I crafted like ~ 50 things and it didn't crash. How likely is the crash for you?

Cant repro on proton 7.0-4 or BE.
Also cant repro with BE + dxvk 1.10.3 from github.

I am on the 515.49.14 nvidia vulkan beta, but I think nvidia isnt supporting your card anymore?

**Comment by VladimirVSC** [comment]
> Is there more to do or only crafting something? I crafted like ~ 50 things and it didn't crash. How likely is the crash for you?

Only crafting, dismantling, cooking and spells enhancement. The game hangs when ingredients start fusing or dismantling. How often? Well, it depends. Sometimes, the first fusion hangs everything, sometimes the fifth or tenth one. I'd say, one of ten times certainly works.

**Comment by WinterSnowfall** [comment]
Older Nvidia drivers had a memory allocation issue, but I believe the workaround for it was removed at some point. Maybe using an older dxvk version would help? [This](https://github.com/doitsujin/dxvk/commit/16a51f3c03d5bc52ba67101fb5a5cd5b8d96fa94) is the commit that fixed it.

**Comment by WinterSnowfall** [comment]
It appears the workaround is still there on the 1.10.x branch, so you can try setting `dxvk.shrinkNvidiaHvvHeap = True` to see if it helps.

**Comment by Blisto91** [comment]
@VladimirVSC Friendly ping

**Comment by Blisto91** [comment]
Closed since the GPU is longer supported and we weren't able to reproduce.
If anyone still has this issue with 2.0 then feel free to open a new issue.
