### ISSUE TITLE
Fallout 4 Black Flickering Textures with Motion Blur Enabled

### ISSUE THREAD

**Issue by ghost** [doitsujin/dxvk#2899]
Aware, enabled Motion Blur (which enabled by default) will make game with DXVK produce black flickering textures, you can turn off it with BethINI, or manually with
[Imagespace]
bMBEnable=0 

in Documents\MyGames\Fallout4Prefs.ini

Fallout 4, Windows 11

### System information
- GPU: 1650 Super
- Driver: 516.94
- DXVK version: 1.10.3

### Log files
[Fallout4_d3d11.log](https://github.com/doitsujin/dxvk/files/9524158/Fallout4_d3d11.log)
[Fallout4_dxgi.log](https://github.com/doitsujin/dxvk/files/9524159/Fallout4_dxgi.log)

**Comment by Blisto91** [comment]
Hi there.
If possible include a screenshot or video of the issue so the devs know what to look for.

And if you are able to make a apitrace that would be great. https://github.com/doitsujin/dxvk/wiki/Making-a-Trace
When making a apitrace without dxvk the issue wont reproduce on screen but the devs can replay it on linux with dxvk and see if it appears. So just try to use it where the issue usually reproduces.

**Comment by Blisto91** [comment]
Yes that is normal. They usually compress well so just zip it up and upload it to a file sharing or cloud service.

**Comment by SegoItCh** [comment]
Also found out it adds big noticeable screen tearing in comparison to default d3d11
https://mega.nz/file/sxwlCLKa#7ubeme6-n7B9TOl1j57nN2Mnm3tdE1NxGCVdrmA8BBA

**Comment by Blisto91** [comment]
I haven't been able to reproduce so far when i've tried. Not really noticing anything obvious in the trace either.
Can you try latest master. You can grab a build of it here https://github.com/doitsujin/dxvk/actions/runs/3083080801

**Comment by SegoItCh** [comment]
You tried with Motion Blur on and Uncapped fps?(VSync off)

**Comment by Blisto91** [comment]
Yes. Tho my rig isn't very chad (R9 380 & i5-6600k) so my fps isn't through through the roof.
The thing i see in the video you posted above are the black objects. But i'm so sure about the flickering textures you talk about.

**Comment by K0bin** [comment]
> Also found out it adds big noticeable screen tearing in comparison to default d3d11

If you enable vsync, it won't tear. If you dont, there will be tearing unless you have a VRR screen. Same as with regular D3D11 too.

**Comment by bowes332frank** [comment]
Disable Motion Blur Did Work!

**Comment by Blisto91** [comment]
What do you mean by it did work

**Comment by Blisto91** [comment]
@SegoItCh Did you get to try with latest master? https://github.com/doitsujin/dxvk/actions/runs/3248541628
Also try to update to the newly released Nvidia driver.

**Comment by SegoItCh** [comment]
I switched to RX 6600, will test with Current-gen update in 2023

**Comment by Blisto91** [comment]
@StellarHarbour Friendly ping to retest with the current gen update

**Comment by StellarHarbour** [comment]
I installed it, but I'm fed up with Windows which getting worse on daily basis, so I moved to Linux, which uses DXVK by default, but I'm not sure it's same back-end, maybe will install later on Laptop
