### ISSUE TITLE
Ni no Kuni II: Only windowed mode available

### ISSUE THREAD

**Issue by tonix64** [doitsujin/dxvk#291]
The game only offers windowed mode when dxvk is enabled, while with wined3d it allows all possible modes (fullscreen...). It also will revert to windowed even if fullscreen was saved from a previous wined3d run.

### Software information
Ni no Kuni II: Revenant Kingdom

### System information
- GPU: GTX 760
- Driver: 390.48.0
- Wine version: 3.6-staging
- DXVK version: https://github.com/doitsujin/dxvk/commit/98b8d410168e526dba6fe1950df111a631e6a8de

### Apitrace files
- [wined3d trace](https://ufile.io/ac21r)
- [dxvk trace](http://www.filedropper.com/nino2-dxvktrace)

### Log files
- d3d11.log: [Nino2_d3d11.log](https://github.com/doitsujin/dxvk/files/1914939/Nino2_d3d11.log)
- dxgi.log: [Nino2_dxgi.log](https://github.com/doitsujin/dxvk/files/1914941/Nino2_dxgi.log)

**Comment by tonix64** [comment]
Retested with https://github.com/doitsujin/dxvk/commit/8125d53e58f0c08394e2e730bc88cbc57234a147

Now I can see all fullscreen/windowed options on the menu on dxvk, but going from windowed to fullscreen with dxvk makes the application freeze on a fullscreen state but missing around a band of around 100px at the bottom.

If I instead do windowed->windowed fullscreen->fullscreen it works, and on further starts it starts in fullscreen successfully.

Attaching two apitraces going from windowed to fullscreen in case it's of any help:

- [https://uploadfiles.io/13juk](wined3d windowed->fullscreen)
- [https://uploadfiles.io/zt67w](dxvk windowed->fullscreen)

I had to kill the application with dxvk so not sure if the dxvk will reach the interesting part.

**Comment by doitsujin** [comment]
Please test if 9de3a619c2acdb226ca8a00cf205ea23c4989da2 fixes the problem.
