### ISSUE TITLE
Steam Deck - Heroic Launcher - Bioshock Remastered - 'dxvk::DxvkError'

### ISSUE THREAD

**Issue by adtither** [doitsujin/dxvk#2910]
Bioshock Remastered used to work fine for me but for some reason when I attempt to launch it now via the Heroic Launcher I encounter a 'dxvk::DxvkError'. Anyone have any ideas why this is happening? Thanks!

System Info:
Heroic Version: 2.4.3 Chopper
Legendary Version:  0.20.28 Dark Energy (hotfix #2)
OS: Freedesktop SDK KERNEL: 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3 ARCH: x64
CPU: AMD Custom APU 0405 @1.78 GOVERNOR: schedutil
RAM: Total: 14.49 GiB Available: 11.08 GiB
GRAPHICS: GPU0: VanGogh [AMD Custom GPU 0405] VRAM: 512MB DRIVER:  
PROTOCOL: x11

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallVkd3d": true,
	"preferSystemLibs": false,
	"enableFSR": false,
	"maxSharpness": 2,
	"enableResizableBar": false,
	"language": "",
	"launcherArgs": "",
	"nvidiaPrime": false,
	"enviromentOptions": [
		{
			"key": "PROTON_NO_ESYNC",
			"value": "1"
		},
		{
			"key": "PROTON_NO_FSYNC",
			"value": "1"
		},
		{
			"key": "DXVK_ASYNC",
			"value": "1"
		}
	],
	"wrapperOptions": [],
	"savesPath": "",
	"showFps": false,
	"targetExe": "",
	"useGameMode": false,
	"wineCrossoverBottle": "Heroic",
	"winePrefix": "/home/deck/Games/Heroic/Prefixes/BioshockRemastered",
	"wineVersion": {
		"bin": "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-33/proton",
		"name": "Proton - GE-Proton7-33",
		"type": "proton"
	},
	"useSteamRuntime": false,
	"eacRuntime": false,
	"battlEyeRuntime": false,
	"gogSaves": []
}

Game launched at: Mon Sep 12 2022 23:28:31 GMT+0100 (Irish Standard Time)

Launch Command: SteamGameId=heroic-BioshockRemastered PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 DXVK_ASYNC=1 STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/deck/.var/app/com.heroicgameslauncher.hgl/.steam/steam STEAM_COMPAT_DATA_PATH=/home/deck/Games/Heroic/Prefixes/BioshockRemastered STEAM_COMPAT_APP_ID=0 PROTON_LOG_DIR=/home/deck/.var/app/com.heroicgameslauncher.hgl /app/bin/heroic/resources/app.asar.unpacked/build/bin/linux/legendary launch bc2c95c6ff564a16b26644f1d3ac3c55 --language en  --no-wine --wrapper "'/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-33/proton' run"

Game Log:
[cli] INFO: Logging in...
[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Checking for updates...
[Core] INFO: Getting authentication token...
[cli] INFO: Launching bc2c95c6ff564a16b26644f1d3ac3c55...
Proton: Upgrading prefix from 7.0-100 to GE-Proton7-33 (/home/deck/Games/Heroic/Prefixes/BioshockRemastered/)
Proton: Prefix has an invalid version?! You may want to back up user files and delete this prefix.
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
*** MESA_GLSL_CACHE_DIR is deprecated; use MESA_SHADER_CACHE_DIR instead ***
*** MESA_GLSL_CACHE_MAX_SIZE is deprecated; use MESA_SHADER_CACHE_MAX_SIZE instead ***
*** MESA_GLSL_CACHE_DIR is deprecated; use MESA_SHADER_CACHE_DIR instead ***
*** MESA_GLSL_CACHE_MAX_SIZE is deprecated; use MESA_SHADER_CACHE_MAX_SIZE instead ***
wine: configuration in L"/home/deck/Games/Heroic/Prefixes/BioshockRemastered/pfx" has been updated.
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API FAIL] SteamAPI_Init() failed
terminate called after throwing an instance of 'dxvk::DxvkError'

**Comment by doitsujin** [comment]
Can you please post the DXVK log files that should be somewhere near the game exe?

**Comment by Blisto91** [comment]
Attach it as a file or GitHub gist if you can. Not directly in to a message 👀

**Comment by adtither** [comment]
I wasn't able to find a DXVK log, closest I could find was a d3d9.log which only gets output if I set the Wine Version to Wine-GE-Proton7-28

[BioshockHD_d3d9.log](https://github.com/doitsujin/dxvk/files/9556292/BioshockHD_d3d9.log)

**Comment by doitsujin** [comment]
The d3d9 log **is** the DXVK log c:

Important line:
```
info:  Required Vulkan extension VK_KHR_surface not supported
```

Means that Vulkan in general cannot work and that there's some serious misconfiguration on your end. No idea how this can even happen on the Deck, but please make sure that native Vulkan applications (like `vkcube`) work and consider setting up a clean wine prefix for the game.

**Comment by adtither** [comment]
Just did a clean install of the game and prefix and still hitting the same issue. I haven't had any issues with other games so seems weird for Vulkan to be generally broken.

I'm not sure how to test out vkcube.

**Comment by Etaash-mathamsetty** [comment]
> Just did a clean install of the game and prefix and still hitting the same issue. I haven't had any issues with other games so seems weird for Vulkan to be generally broken.
> 
> I'm not sure how to test out vkcube.

something is probably messed up with your flatpak installation
heroic recently updated the flatpak platform runtime to 22.08, and so maybe try to see if you can install vulkan for the 22.08 runtime. (it might fix your issue?)

**Comment by adtither** [comment]
> > Just did a clean install of the game and prefix and still hitting the same issue. I haven't had any issues with other games so seems weird for Vulkan to be generally broken.
> > I'm not sure how to test out vkcube.
> 
> something is probably messed up with your flatpak installation heroic recently updated the flatpak platform runtime to 22.08, and so maybe try to see if you can install vulkan (or mesa) for the 22.08 runtime. (it might fix your issue?)

Thanks for the info. I'm not amazingly experienced with Linux could you please explain how I would install vulkan for the runtime. I've attempted reinstalling heroic before but didn't solve the issue

**Comment by Etaash-mathamsetty** [comment]
> > > Just did a clean install of the game and prefix and still hitting the same issue. I haven't had any issues with other games so seems weird for Vulkan to be generally broken.
> > > I'm not sure how to test out vkcube.
> > 
> > 
> > something is probably messed up with your flatpak installation heroic recently updated the flatpak platform runtime to 22.08, and so maybe try to see if you can install vulkan (or mesa) for the 22.08 runtime. (it might fix your issue?)
> 
> Thanks for the info. I'm not amazingly experienced with Linux could you please explain how I would install vulkan for the runtime. I've attempted reinstalling heroic before but didn't solve the issue

I think you would have to install org.freedesktop.Platform.GL.default then pick version 22.08 from the list

**Comment by adtither** [comment]
> 

Looks like I already have that installed to 22.08

**Comment by Blisto91** [comment]
@adtither Did you figure out your issue? :slightly_smiling_face:

**Comment by adtither** [comment]
@Blisto91 It seems like Heroic Launcher install had just become corrupted in some way. I fixed it by doing a reinstall:

flatpak install com.heroicgameslauncher.hgl --reinstall

**Comment by Blisto91** [comment]
Good to hear! :grin:
