### ISSUE TITLE
DCS World Error Shader "/shaders/deferred/Compose.fx" failed to compile

### ISSUE THREAD

**Issue by Slyfox88** [doitsujin/dxvk#2916]
Please describe your issue as accurately as possible.

Installed DCS World (non-steam), plus vcrun2019, corefonts, xact, d3dcompiler_43, d3dcompiler_47. DLL overrides of wbemprox and msdmo. Based on https://github.com/TheZoq2/dcs_on_linux

Got Error: DX11 Renderer - Error Shader "/shaders/deferred/Compose.fx" failed to compile. Reason: /shaders/deferred/Compose.fx:33:1: E5000: syntax error, unexpected KW_DEPTHSTENCILSTATE

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Name of the game, settings used etc.
DCS World
### System information
- GPU: AMD Radeon RX 6800 XT (navi21, LLVM 14.0.0, DRM 3.42, 5.15.0-47-generic)
- Driver: 4.6 (Compatibility Profile) Mesa 22.2.0-rc3
- Wine version: 7.2, Crossover 22.0
- DXVK version: 1.10.3, Crossover 22.0

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:
[dcs_log.txt](https://github.com/doitsujin/dxvk/files/9562241/dcs_log.txt)

**Comment by Joshua-Ashton** [comment]
Not a DXVK bug. This is a Wine D3DX9 or D3DX11 bug.

**Comment by LegacyHornet** [comment]
i deleted compose.fx and then dcs crashed on startup so i repaired and it seems to work fine
