### ISSUE TITLE
[QUESTION] Is DXVK limited to 24 GB RAM only?

### ISSUE THREAD

**Issue by rado84-github** [doitsujin/dxvk#2917]
Ever since the first version of DXVK was released I've noticed that in logs it reports "Memory heap 24018 MiB" which I suppose is the RAM. But I have 32 GB (31,3 GiB). So is DXVK limited to 24 GB RAM only or is that memory heap something else?

**Comment by K0bin** [comment]
What you're seeing there is the size of the Vulkan system memory heap. DXVK gets the value straight from the driver.

No game even gets remotely close to 24GB, let alone 32. Just to put this into perspective, if a game uses one gigabyte of HOST_VISIBLE Vulkan memory, that's a lot.

**Comment by rado84-github** [comment]
I see. I was wondering if that difference between memory heap and my real quantity of RAM could be the reason for the poor performance on some games or maps of these games, like Fjords on WOT (https://github.com/doitsujin/dxvk/issues/2909#issuecomment-1245902919), but I guess it's something else.

**Comment by K0bin** [comment]
It's not.
