### ISSUE TITLE
Project Cars 2 demo has black screen then crashes

### ISSUE THREAD

**Issue by ZeroFault** [doitsujin/dxvk#292]
Project Cars 2 demo

The game starts with a black screen and crashes a short while later.

### System information
- GPU: GTX 1080
- Driver: 391.35
- Wine version: Native Windows 10
- DXVK version: [75c928f](https://github.com/doitsujin/dxvk/commit/75c928fc878b7b3025c0d1b81e43ee5af8bb082b)

### Apitrace file(s)
[apitrace](https://mega.nz/#!HHhFzQwa!YSFux9-ph85RilhZ-yKomt7aCmTbm1gzKtQTNuJbkWE)

### Log files
[d3d11.log](https://github.com/doitsujin/dxvk/files/1917682/d3dretrace_d3d11.log)
[dxgi.log](https://github.com/doitsujin/dxvk/files/1917683/d3dretrace_dxgi.log)

[vulkanlog.txt](https://github.com/doitsujin/dxvk/files/1917684/vulkanlog.txt)

There are 2 graphics pipelines not compiling.

**Comment by doitsujin** [comment]
While almost certainly doesn't cause the crash, there's a bug in my `GenerateMips` implementation. Guess I'll have to create and use render passes manually instead of relying on Vulkan's blitting.

The messages about format mismatches *should* be irrelevant, Final Fantasy XIV has that issue as well and seems to render properly on Nvidia (see #208).

**Comment by doitsujin** [comment]
Looking at your trace again it seems that either apitrace doesn't pick it up or something is **really** broken. The game never actually writes any data to its constant buffers for some reason, which is why nothing gets rendered.

**Comment by ZeroFault** [comment]
It's the apitrace that is broken. The game itself on DXVK renders fine until I get to the map loading screen where it will crash near the end. So, I'm not sure how we are going to fix this without an apitrace.

**Comment by empiredave** [comment]
does dxvk 0.60 make a difference?

**Comment by ZeroFault** [comment]
Closing for duplicate issue https://github.com/doitsujin/dxvk/issues/375
