### ISSUE TITLE
[d3d9] [regression] Fairy Fencer F borderless/windowed option makes game window disappear

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#2920]
Since https://github.com/doitsujin/dxvk/commit/cc11bb824045505439604d2bc1af9d805749ed09 in Fairy Fencer F when you click either the borderless or windowed option the game window disappears and can't be opened again. After some seconds it reappears since i can't confirm the new option selection.

### Software information
Fairy Fencer F started in fullscreen

### System information
- GPU: R9 380
- Driver: mesa  22.1.7
- Wine version: proton 7.0-4 and experimental
- DXVK version: https://github.com/doitsujin/dxvk/commit/cc11bb824045505439604d2bc1af9d805749ed09

### Log files
Log from bad commit
[FairyFencer_dxgi.log](https://github.com/doitsujin/dxvk/files/9568611/FairyFencer_dxgi.log)

Log from good commit
[FairyFencer_d3d9-good.log](https://github.com/doitsujin/dxvk/files/9568613/FairyFencer_d3d9-good.log)

**Comment by Blisto91** [comment]
CC @gofman

**Comment by gofman** [comment]
The issue is reproducible on Windows with dxvk as well. It doesn't look like the blamed commit was wrong per se, it is just that before the commit window size was updated right after fullscreen restore (which was still breaking things elsewhere).
