### ISSUE TITLE
setup_dxvk.sh fails on wine64 only setup (without wow64)

### ISSUE THREAD

**Issue by okias** [doitsujin/dxvk#2921]
https://github.com/doitsujin/dxvk/blob/v1.10.3/setup_dxvk.sh#L63

By looking at the script, it seems that when `wine` is symlinked to `wine64` then `system32` dxvk dlls are overwritten by  `syswow64`.

Maybe looking for `wine32` instead of `wine` could make sense?

Possible solutions:

 - look for `wine32` instead of `wine`
 - write the native 64-bit version as last (so overwrite 32-bit, which gets pointed into the same location as 64-bit)
 - determine whether or not the paths are identical.

**Comment by doitsujin** [comment]
We haven't really supported this because there's no real use case for it. Yes, it can be fixed, but it is very, very **very** low on the priority list.

**Comment by okias** [comment]
```bash
sed -i 's/wine="wine"/wine="wine32"/' setup_dxvk.sh
```
I currently patched it like this and does work. Yeah, it's as you say, it seems that minimum of people using pure wine64.

**Comment by Blisto91** [comment]
Closure reason https://github.com/doitsujin/dxvk/pull/3097
