### ISSUE TITLE
Regression(?) in Days Gone - game locked to around 4fps

### ISSUE THREAD

**Issue by adamdmoss** [doitsujin/dxvk#2933]
The game starts okay, and the logo cinematics look okay (I think), but everything from the title screen onward seems to be locked to a pretty consistent 4fps.  It's hard to casually diagnose without mangohud (https://github.com/flightlessmango/MangoHud/issues/835) but it appears that the CPU is almost entirely idle, and render settings don't affect the frame rate so I believe it's not at all GPU limited either.

Proton experimental 'default branch' is fine, it's 'bleeding-edge' that has regressed, FWIW bleeding-edge was fine a day earlier.

### Software information
'Days Gone' (on Steam) - tried various in-game graphical settings from ultra low to ultra high.

### System information
- GPU: RTX 3080
- Driver: 515.65.01
- Wine version: Proton Experimental **bleeding-edge** 2022-09-16
- DXVK version: presumably around 4fb6c200d7accabeac3b097e904e226a2929f6e5

**Comment by adamdmoss** [comment]
I attempted to regress-test/bisect the issue but started rabbit-holing into DXVK build issues on my local machine.

**Comment by doitsujin** [comment]
The commit above fixes this for me.

**Comment by adamdmoss** [comment]
Verified here too - thanks!!
