### ISSUE TITLE
Source 2 (or S&Box) Hammer tool flickers

### ISSUE THREAD

**Issue by Danct12** [doitsujin/dxvk#2937]
### Software information
Game is S&Box, in developer mode there is Hammer tool for making maps. When run with DXVK, the hammer tool flickers very badly.

This does not happen with WineD3D.

### System information
- GPU: NVIDIA Geforce 1050 Ti
- Driver: Proprietary (515.65.01)
- Wine version: Valve's Wine fork (24d60b5e24b8c2d6b769a482990824fc47548c5b)
- DXVK version: 9fa587e13c469bde8761175f4fa1ae6dfdcf6d17

### Apitrace file(s)
- Put a link here

I wasn't able to get apitrace replay to show up with this trace.

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

None of the file shows up in game directory, I've tried looking at compat pfx, but no dice, so here's a video instead. Please let me know how I can help.

https://user-images.githubusercontent.com/19162768/190871381-33ff1fb0-aac9-49bb-9d10-0bdc21c25b88.mp4

**Comment by doitsujin** [comment]
Can we have *any* sort of log files please? Preferably the full Wine console output?

Generally, I wouldn't recommend using DXVK for "desktop" applications like this since we don't really support things like partial presentation and things like GDI interop properly. It's not really a priority since it's a huge amount of highly cursed work that's never going to get even close to Windows levels of compatibility anyway.

**Comment by Danct12** [comment]
The game uses D3D11. Here are the logs dropped by DXVK, I made a typo in the environment variable so nothing was dropped earlier.

[sbox_d3d9.log](https://github.com/doitsujin/dxvk/files/9592435/sbox_d3d9.log)
[sbox_d3d11.log](https://github.com/doitsujin/dxvk/files/9592436/sbox_d3d11.log)
[sbox_dxgi.log](https://github.com/doitsujin/dxvk/files/9592437/sbox_dxgi.log)

And here is the Wine console output:
[sbox_output.log](https://github.com/doitsujin/dxvk/files/9592438/sbox_output.log)

**Comment by Blisto91** [comment]
I noticed you are using dxvk-async in the log. Does the issue also occur with regular dxvk?
Not that i expect a difference. Just as a sanity check.

**Comment by Danct12** [comment]
Yes, it also does happen with regular DXVK.

**Comment by Blisto91** [comment]
@Danct12  Hello. Can try and check this out with PR https://github.com/doitsujin/dxvk/pull/3392 ?
You can find a build of it here https://github.com/doitsujin/dxvk/actions/runs/4893877539

**Comment by Danct12** [comment]
S&Box and Source 2 uses DirectX 11 I believe, so this PR doesn't fix S&Box.

Aside from that, with GE-Proton-8-2 this seems to have been fixed in some DXVK commit.

**Comment by Blisto91** [comment]
Yes but wasn't sure what the editor was application was made with. Some of these Windows UI frameworks use d3d9 for some UI stuff. But glad it's working now!
