### ISSUE TITLE
Insanely low performance in God of War and nothing else

### ISSUE THREAD

**Issue by pibberflibbits** [doitsujin/dxvk#2938]
I am running God of War on a 3080, and a 12900k. I have the latest kernel, the latest drivers, and am using proton-experimental (but this issue exists on all versions of proton). When I launch God of War through Steam or Lutris I get around 25 fps, on lowest settings and at 10% resolution scaling. It says only 20-30% of my CPU is being used (which might actually be normal?), but my GPU is being used as expected. 

I am using all of the ProtonDB recommended settings for both launch options as well as the steam play settings. Again, every other game in my steam library runs perfectly, and utilizes the CPU properly. I am also running gamemode but this issue existed before use.

I am using 2 monitors with Xrandr but have tried disabling xrandr and running on one monitor, and have even unplugged the monitor from my GPU. 

Any help would be greatly appreciated!

### Software information
God of War
issue persists on all settings. 

### System information
- GPU: RTX 3080
- Driver: 515.65.01
- Kernel: 5.19.9-arch1-1
- Wine version:  Proton Experimental
- DXVK version: [9fa587e](https://github.com/doitsujin/dxvk/commit/9fa587e13c469bde8761175f4fa1ae6dfdcf6d17)

### Log files
[GoW_d3d11.log](https://github.com/doitsujin/dxvk/files/9592693/GoW_d3d11.log)
[GoW_dxgi.log](https://github.com/doitsujin/dxvk/files/9592694/GoW_dxgi.log)

**Comment by doitsujin** [comment]
Works fine on both my AMD desktop and the RTX 2060 on my laptop (some 40 FPS at 1440p Original preset, no DLSS).

Can you run the game with `DXVK_HUD=full` and post a screenshot when it's slow?

**Comment by pibberflibbits** [comment]
![20220917180436_1](https://user-images.githubusercontent.com/79475082/190881199-bf974e46-8c62-4862-9485-2404170f10a9.jpg)

**Comment by doitsujin** [comment]
33% GPU utilization but nothing suspicious in the HUD. Just seems **extremely** CPU-bound for some weird reason.

Please try `WINE_CPU_TOPOLOGY=8:0,1,2,3,4,5,6,7`, maybe the game really doesn't like Alder Lake and its weird cache topology on Linux for whatever reason. If that doesn't help, I'm pretty much out of ideas though, assuming you don't have any insane launch options set (e.g. Vulkan validation, excessive wine logging, etc).

**Comment by pibberflibbits** [comment]
Yeah no clue whats happening, but I just installed GoW on my GPU pass through Win11 VM and the issue persisted even there, so there is definitely something bigger here. It's just so odd that this only manifests with this game, very strange.

**Comment by Iglu47** [comment]
> 12900k

@pibberflibbits Have you already tried disabling low-power cores?
As far as I know, there is a known issue with this hybrid architecture where low-power cores interfering with many "legacy" applications is involved.

**Comment by Iglu47** [comment]
> Kernel: 5.19.9-arch1-1

@pibberflibbits could you also make a test not on the 5.19 branch?

**Comment by pibberflibbits** [comment]
Reverting the Kernel made everything run as normal! Thanks a ton guys, I definitely would not have figured this out on my own!

**Comment by Joshua-Ashton** [comment]
If you go back to 5.19, can you send the output `dmesg` when the game is running to see if there is anything of interest?

**Comment by pibberflibbits** [comment]
> If you go back to 5.19, can you send the output `dmesg` when the game is running to see if there is anything of interest?

https://pastebin.com/L2LuYw5d

**Comment by Iglu47** [comment]
> > If you go back to 5.19, can you send the output `dmesg` when the game is running to see if there is anything of interest?
> 
> https://pastebin.com/L2LuYw5d

could you try add `split_lock_detect=off` boot parameter for kernel 5.19 and made retest?

**Comment by Iglu47** [comment]
> > If you go back to 5.19, can you send the output `dmesg` when the game is running to see if there is anything of interest?
> 
> https://pastebin.com/L2LuYw5d

@pibberflibbits could you try add `split_lock_detect=warn` boot parameter for kernel 5.19 and made retest?

**Comment by Iglu47** [comment]
> https://pastebin.com/L2LuYw5d
```
[  329.065344] x86/split lock detection: #AC: GoW.exe/4190 took a split_lock trap at address: 0x140b33cbf
[  329.066055] x86/split lock detection: #AC: GoW.exe/4143 took a split_lock trap at address: 0x140b35229
[  329.092907] x86/split lock detection: #AC: GoW.exe/4189 took a split_lock trap at address: 0x140b33cbf
[  329.122778] x86/split lock detection: #AC: GoW.exe/4191 took a split_lock trap at address: 0x140b33cbf
[  329.212372] x86/split lock detection: #AC: GoW.exe/4188 took a split_lock trap at address: 0x140b33cbf
[  329.392868] x86/split lock detection: #AC: GoW.exe/4192 took a split_lock trap at address: 0x140b33cbf
[  329.676301] x86/split lock detection: #AC: GoW.exe/4187 took a split_lock trap at address: 0x140b33cbf
```
the reason is that for intel at 5.19 kernel the default value of `split_lock_detect` was changed from `warn` to `sequential`.
but it can be still manually returned (or setted to `off`)
more info: https://www.phoronix.com/news/Linux-5.19-Split-Lock

**Comment by Iglu47** [comment]
> https://pastebin.com/L2LuYw5d

@pibberflibbits could you try add `split_lock_detect=off` boot parameter for kernel 5.19 and made retest?

**Comment by pibberflibbits** [comment]
Yup that fixed it, it seems to be running the same as it did on 5.18 now, if not a bit more stable. I can finally update my system now! But what exactly did that fix, if you don't mind me asking?

**Comment by farfromrefug** [comment]
Does anyone knows how to set `split_lock_detect=off` on PopOs?

**Comment by Iglu47** [comment]
> Does anyone knows how to set `split_lock_detect=off` on PopOs?

@farfromrefug sorry, I've never used Pop_Os, but it should probably be exactly the same as on Ubuntu
https://duckduckgo.com/?q=how+to+add+kernel+boot+parameters+via+GRUB+on+Ubuntu

**Comment by Iglu47** [comment]
> Does anyone knows how to set `split_lock_detect=off` on PopOs?

@farfromrefug sorry, I've never used Pop_Os, but it should probably be exactly the same as on Ubuntu
https://duckduckgo.com/?q=how+to+permanently+add+kernel+boot+parameters+via+GRUB+on+Ubuntu

**Comment by farfromrefug** [comment]
@Iglu47 actually found out that on PopOS you need to do `sudo kernelstub --add-options split_lock_detect=off`
thanks!

**Comment by Moswdys** [comment]
> > https://pastebin.com/L2LuYw5d
> 
> @pibberflibbits could you try add `split_lock_detect=off` boot parameter for kernel 5.19 and made retest?

how do i do that again?

**Comment by Moswdys** [comment]
> Depends on your boot loader. You can see some examples on the Arch wiki https://wiki.archlinux.org/title/kernel_parameters If in doubt about a specific distro I'd reach out to any help forums or chats from your distro

ya have a discord where you can tell me how to do this comfortably? also im on ubuntu if its needed to be known

**Comment by Blisto91** [comment]
I don't use Ubuntu myself but i think they have a lot of help forums and chats which might be better to seek out https://ubuntu.com/community/support

**Comment by Moswdys** [comment]
> I don't use Ubuntu myself but i think they have a lot of help forums and chats which might be better to seek out https://ubuntu.com/community/support

aiiight ill listen to ya ill come back if i realise im starting do damage my brain

**Comment by Moswdys** [comment]
> I don't use Ubuntu myself but i think they have a lot of help forums and chats which might be better to seek out https://ubuntu.com/community/support

do i access the kernel settings from bios settings or?

**Comment by Blisto91** [comment]
It's usually a file on system and or a command. It's better to try and ask via one of the forums above.

**Comment by Moswdys** [comment]
> I don't use Ubuntu myself but i think they have a lot of help forums and chats which might be better to seek out https://ubuntu.com/community/support

hey man i managed to do the parameter thing but the game still runs low on fps like 20

**Comment by luisalvarado** [comment]
Is this still happening? I am asking because the only think that I can think as a difference are my kernel parameters in the grub file which are:

`GRUB_CMDLINE_LINUX_DEFAULT="mitigations=off nvidia-drm.modeset=1 ibt=off split_lock_detect=off split_lock_mitigate=0 nokaslr"
GRUB_CMDLINE_LINUX="vdso=0 ignore_rlimit_data nvidia-drm.modeset=1 sched_migration_cost=512 pci=nommconf preempt=full nohz_full=all threadirqs"`

I have an Nvidia card just in case. The following shows the current performance: https://www.youtube.com/watch?v=GE1u3DeLD5s

But again, it was the only thing I found as a difference. I am also playing on steam and using proton experimental at the moment.

**Comment by marcusziade** [comment]
for Arch, this is what fixed it for me

```shell
[marcus@arch ~]$ cat /boot/loader/entries/arch.conf 
title Arch Linux
linux /vmlinuz-linux
initrd /intel-ucode.img
initrd /initramfs-linux.img
options root=UUID=8cbc0d27-c578-43a5-8c4c-a6f8a9c179c1 rw split_lock_detect=off amdgpu.ppfeaturemask=0xffffffff
```

14700K, 7900XTX

`sudo reboot` after adding that in the boot config.

**Comment by kode54** [comment]
Or you can turn off split lock mitigation with a sysctl at runtime, and turn it back on when you're done with the game.

https://wiki.cachyos.org/configuration/general_system_tweaks/#6-disabling-split-lock-mitigate

**Comment by marcusziade** [comment]
Is there a reason I would do this over what I currently have?

**Comment by kode54** [comment]
Not really, actually. I was misinformed by someone who thought this was a security feature, but in actuality, it's designed to spite developers who make the mistake of using split locks. While they're generally a bad idea, because there is no performant way to implement them, it was the kernel devs who decided "the way to fix this is to default all users to be punished by making them even 1000x slower, that'll get the devs to stop doing this"

Except it's proprietary software, for a proprietary operating system that will either never punish devs for using split locks, or if they do, they'll make workarounds for common apps so nobody will notice anyway.
