### ISSUE TITLE
[request] Expose VXAO via DXVK?

### ISSUE THREAD

**Issue by RareMv** [doitsujin/dxvk#2940]
So DXVK is able to emulate all DirectX9-10-11 calls through Vulkan. 

DXVK also allows to set a custom device ID, for device spoofing.

Is it possible to make DXVK expose Nvidia's VXAO option in games, if you don't have a Maxwell GPU or newer?

It's only present in like 4 games total to my knowledge. Rise of the Tomb Raider, Final Fantasy 15, I think Division 1 and I think Shadow of the Tomb Raider. And it's only present in DX11, not DX12.

It's a voxel based AO solution, similar to a path traced AO option like ReShade MXAO. Or you can think of it a precursor to Nvidia's work on RT ambient occlusion.

I'm really not sure if this is within's DXVK or any developer's means, but I wanted to ask.

**Comment by doitsujin** [comment]
VXAO works in FFXV if you have a supported GPU . I don't know about the other games, they may require some sort of nvapi magic that probably doesn't work on Linux.

**Comment by RareMv** [comment]
I only tried on Windows, on 5700 XT and NimeZ 22.8.2 drivers. Used DXVK 1.10.3, set the Nvapi to not report as an AMD GPU (so False) and set the device ID to an RTX 3080.

Rise of the Tomb Raider in DX11 would still not expose VXAO.

**Comment by doitsujin** [comment]
DXVK supports all the features necessary, if the game decides to only expose VXAO on an actual Nvidia GPU due to some vendor library interactions (which cannot ever work with DXVK on Windows) then there's nothing we can do on our end.
