### ISSUE TITLE
[d3d9] Far Cry 2 Shadow Acne

### ISSUE THREAD

**Issue by TacoDeBoss** [doitsujin/dxvk#2941]
During my latest playthrough of Far Cry 2, I noticed DXVK has some shadow acne issues in this game. Tested with Steam Deck and RX 5700XT.

### Software information
Far Cry 2, highest settings, D3D9 renderer

### System information
- GPU: Radeon RX 5700XT
- Driver: Mesa 22.1.7 / Mesa git
- Wine version: Proton 7.0-4, Proton Experimental Bleeding Edge
- DXVK version: All versions (tested 1.5, 1.10.3, and whatever Bleeding Edge ships)

### Apitrace file(s)
-[ Put a link here ](https://drive.google.com/file/d/1YViHJrsw8rtKP0ohaJgJrTeHDEXj6bA4/view)

![Image](https://i.imgur.com/bl7JTAg.jpg)

**Comment by K0bin** [comment]
![image](https://user-images.githubusercontent.com/1131720/191346953-8b20d8ab-e5ea-4ed9-b8d1-6ab3f67c8ab1.png)
Looks fine here but the game sets a depth bias so I strongly suspect it's another case of this one: #2892
