### ISSUE TITLE
[d3d9] Far Cry 2 Redux Mod - DXVK is 4-5 FPS slower than WineD3D

### ISSUE THREAD

**Issue by TacoDeBoss** [doitsujin/dxvk#2942]
Exclusively when using the Ultra High graphics preset included with the Far Cry 2 Redux mod, DXVK runs at 42 FPS vs WineD3D's 47 FPS in the same scene. DXVK is faster on all other graphics settings, so this is not really a big problem.
Just posted here in case developers can learn anything from this edge case.

### System information
- GPU: Radeon RX 5700 XT
- Driver: Mesa 22.1.7
- Wine version: Proton 7.0-4
- DXVK version: 1.10.3

### Apitrace file(s)
- [Put a link here](https://drive.google.com/file/d/1D5sEqNYb3EgGg3SmsG3KsRIcflqyo2iS/view?usp=sharing)

**Comment by K0bin** [comment]
No idea whats going on here.
WineD3D seems slightly faster for @CME42 like you describe.

Meanwhile DXVK is 3x faster than WineD3D on my system and the game runs comfortably at ~100 FPS even when I reduce CPU clocks to 2.2Ghz. Throwing `perf` at it doesn't show anything obvious to optimize on our side. The most notable thing is that the game spends a lot of time in `IsBadWritePtr`.

**Comment by Blisto91** [comment]
@TacoDeBoss Could i get you to reevaluate this?

**Comment by TacoDeBoss** [comment]
> @TacoDeBoss Could i get you to reevaluate this?

Sure thing! I had a look today on the latest Proton Experimental main branch, with DXVK commit 4c09b00 (latest as of posting) and cannot replicate the issue. WineD3D clocked in at 53-55 FPS, and DXVK at 60-62 FPS on the same highest settings, at the same location.

![Screenshot_20241114_110132](https://github.com/user-attachments/assets/21740153-e83d-45dc-9f3b-7aa46482df7e)
![Screenshot_20241114_110330](https://github.com/user-attachments/assets/f06389c8-516e-47cc-bb1e-cfd1b9ebc4ca)


[System info](https://gist.github.com/TacoDeBoss/e958e96bc79ed5c53604b978c37bc5e9)
