### ISSUE TITLE
build dxvk master error

### ISSUE THREAD

**Issue by guangli0510** [doitsujin/dxvk#2943]
Please describe your issue as accurately as possible.
I got the dxvk throgh "git clone --recursive https://github.com/doitsujin/dxvk.git"
then i install  meson mingw-w64 glsllang (build from the glslang project)
also set the following configure
sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
   sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
   sudo update-alternatives --set i686-w64-mingw32-gcc /usr/bin/i686-w64-mingw32-gcc-posix
   sudo update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix
 ./package-release.sh master ./ --no-package

error log:
./package-release.sh master /data/dxvk/dxvk --no-package

[164/274] Compiling C++ object 'src/d3d11/bca5607@@d3d11@sha/d3d11_buffer.cpp.obj'.
FAILED: src/d3d11/bca5607@@d3d11@sha/d3d11_buffer.cpp.obj
x86_64-w64-mingw32-g++ -Isrc/d3d11/bca5607@@d3d11@sha -Isrc/d3d11 -I../../src/d3d11 -I../.././include -I../.././include/vulkan/include -I../.././include/spirv/include -fdiagnostics-color=always -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ 'src/d3d11/bca5607@@d3d11@sha/d3d11_buffer.cpp.obj' -MF 'src/d3d11/bca5607@@d3d11@sha/d3d11_buffer.cpp.obj.d' -o 'src/d3d11/bca5607@@d3d11@sha/d3d11_buffer.cpp.obj' -c ../../src/d3d11/d3d11_buffer.cpp
In file included from ../../src/d3d11/d3d11_device.h:19,
                 from ../../src/d3d11/d3d11_buffer.cpp:3:
../../src/d3d11/d3d11_features.h:84:5: error: 'D3D11_FEATURE_DATA_D3D11_OPTIONS5' does not name a type; did you mean 'D3D11_FEATURE_DATA_D3D11_OPTIONS4'?
   84 |     D3D11_FEATURE_DATA_D3D11_OPTIONS5                 m_d3d11Options5               = { };
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_FEATURE_DATA_D3D11_OPTIONS4
../../src/d3d11/d3d11_features.h:104:5: error: 'D3D11_SHARED_RESOURCE_TIER' does not name a type; did you mean 'D3D11_TILED_RESOURCES_TIER'?
  104 |     D3D11_SHARED_RESOURCE_TIER DetermineSharedResourceTier(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_TILED_RESOURCES_TIER
[165/274] Compiling C++ object 'src/d3d11/bca5607@@d3d11@sha/d3d11_annotation.cpp.obj'.
FAILED: src/d3d11/bca5607@@d3d11@sha/d3d11_annotation.cpp.obj
x86_64-w64-mingw32-g++ -Isrc/d3d11/bca5607@@d3d11@sha -Isrc/d3d11 -I../../src/d3d11 -I../.././include -I../.././include/vulkan/include -I../.././include/spirv/include -fdiagnostics-color=always -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ 'src/d3d11/bca5607@@d3d11@sha/d3d11_annotation.cpp.obj' -MF 'src/d3d11/bca5607@@d3d11@sha/d3d11_annotation.cpp.obj.d' -o 'src/d3d11/bca5607@@d3d11@sha/d3d11_annotation.cpp.obj' -c ../../src/d3d11/d3d11_annotation.cpp
In file included from ../../src/d3d11/d3d11_device.h:19,
                 from ../../src/d3d11/d3d11_state_object.h:3,
                 from ../../src/d3d11/d3d11_context_imm.h:8,
                 from ../../src/d3d11/d3d11_annotation.cpp:3:
../../src/d3d11/d3d11_features.h:84:5: error: 'D3D11_FEATURE_DATA_D3D11_OPTIONS5' does not name a type; did you mean 'D3D11_FEATURE_DATA_D3D11_OPTIONS4'?
   84 |     D3D11_FEATURE_DATA_D3D11_OPTIONS5                 m_d3d11Options5               = { };
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_FEATURE_DATA_D3D11_OPTIONS4
../../src/d3d11/d3d11_features.h:104:5: error: 'D3D11_SHARED_RESOURCE_TIER' does not name a type; did you mean 'D3D11_TILED_RESOURCES_TIER'?
  104 |     D3D11_SHARED_RESOURCE_TIER DetermineSharedResourceTier(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_TILED_RESOURCES_TIER
[167/274] Compiling C++ object 'src/d3d11/bca5607@@d3d11@sha/d3d11_blend.cpp.obj'.
FAILED: src/d3d11/bca5607@@d3d11@sha/d3d11_blend.cpp.obj
x86_64-w64-mingw32-g++ -Isrc/d3d11/bca5607@@d3d11@sha -Isrc/d3d11 -I../../src/d3d11 -I../.././include -I../.././include/vulkan/include -I../.././include/spirv/include -fdiagnostics-color=always -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ 'src/d3d11/bca5607@@d3d11@sha/d3d11_blend.cpp.obj' -MF 'src/d3d11/bca5607@@d3d11@sha/d3d11_blend.cpp.obj.d' -o 'src/d3d11/bca5607@@d3d11@sha/d3d11_blend.cpp.obj' -c ../../src/d3d11/d3d11_blend.cpp
In file included from ../../src/d3d11/d3d11_device.h:19,
                 from ../../src/d3d11/d3d11_blend.cpp:2:
../../src/d3d11/d3d11_features.h:84:5: error: 'D3D11_FEATURE_DATA_D3D11_OPTIONS5' does not name a type; did you mean 'D3D11_FEATURE_DATA_D3D11_OPTIONS4'?
   84 |     D3D11_FEATURE_DATA_D3D11_OPTIONS5                 m_d3d11Options5               = { };
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_FEATURE_DATA_D3D11_OPTIONS4
../../src/d3d11/d3d11_features.h:104:5: error: 'D3D11_SHARED_RESOURCE_TIER' does not name a type; did you mean 'D3D11_TILED_RESOURCES_TIER'?
  104 |     D3D11_SHARED_RESOURCE_TIER DetermineSharedResourceTier(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_TILED_RESOURCES_TIER
[168/274] Compiling C++ object 'src/d3d11/bca5607@@d3d11@sha/d3d11_cmdlist.cpp.obj'.
FAILED: src/d3d11/bca5607@@d3d11@sha/d3d11_cmdlist.cpp.obj
x86_64-w64-mingw32-g++ -Isrc/d3d11/bca5607@@d3d11@sha -Isrc/d3d11 -I../../src/d3d11 -I../.././include -I../.././include/vulkan/include -I../.././include/spirv/include -fdiagnostics-color=always -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ 'src/d3d11/bca5607@@d3d11@sha/d3d11_cmdlist.cpp.obj' -MF 'src/d3d11/bca5607@@d3d11@sha/d3d11_cmdlist.cpp.obj.d' -o 'src/d3d11/bca5607@@d3d11@sha/d3d11_cmdlist.cpp.obj' -c ../../src/d3d11/d3d11_cmdlist.cpp
In file included from ../../src/d3d11/d3d11_device.h:19,
                 from ../../src/d3d11/d3d11_cmdlist.cpp:2:
../../src/d3d11/d3d11_features.h:84:5: error: 'D3D11_FEATURE_DATA_D3D11_OPTIONS5' does not name a type; did you mean 'D3D11_FEATURE_DATA_D3D11_OPTIONS4'?
   84 |     D3D11_FEATURE_DATA_D3D11_OPTIONS5                 m_d3d11Options5               = { };
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_FEATURE_DATA_D3D11_OPTIONS4
../../src/d3d11/d3d11_features.h:104:5: error: 'D3D11_SHARED_RESOURCE_TIER' does not name a type; did you mean 'D3D11_TILED_RESOURCES_TIER'?
  104 |     D3D11_SHARED_RESOURCE_TIER DetermineSharedResourceTier(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_TILED_RESOURCES_TIER
[169/274] Compiling C++ object 'src/d3d11/bca5607@@d3d11@sha/d3d11_class_linkage.cpp.obj'.
FAILED: src/d3d11/bca5607@@d3d11@sha/d3d11_class_linkage.cpp.obj
x86_64-w64-mingw32-g++ -Isrc/d3d11/bca5607@@d3d11@sha -Isrc/d3d11 -I../../src/d3d11 -I../.././include -I../.././include/vulkan/include -I../.././include/spirv/include -fdiagnostics-color=always -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ 'src/d3d11/bca5607@@d3d11@sha/d3d11_class_linkage.cpp.obj' -MF 'src/d3d11/bca5607@@d3d11@sha/d3d11_class_linkage.cpp.obj.d' -o 'src/d3d11/bca5607@@d3d11@sha/d3d11_class_linkage.cpp.obj' -c ../../src/d3d11/d3d11_class_linkage.cpp
In file included from ../../src/d3d11/d3d11_device.h:19,
                 from ../../src/d3d11/d3d11_class_linkage.cpp:2:
../../src/d3d11/d3d11_features.h:84:5: error: 'D3D11_FEATURE_DATA_D3D11_OPTIONS5' does not name a type; did you mean 'D3D11_FEATURE_DATA_D3D11_OPTIONS4'?
   84 |     D3D11_FEATURE_DATA_D3D11_OPTIONS5                 m_d3d11Options5               = { };
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_FEATURE_DATA_D3D11_OPTIONS4
../../src/d3d11/d3d11_features.h:104:5: error: 'D3D11_SHARED_RESOURCE_TIER' does not name a type; did you mean 'D3D11_TILED_RESOURCES_TIER'?
  104 |     D3D11_SHARED_RESOURCE_TIER DetermineSharedResourceTier(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_TILED_RESOURCES_TIER
ninja: build stopped: subcommand failed.

**Comment by Joshua-Ashton** [comment]
Need a newer MinGW.

**Comment by pchome** [comment]
Could be checks in "windows" platform section of main meson.build. Something like
```python
if cpp.get_id() == 'gcc' and cpp.version().version_compare('>=10.0') == false
  error('Mingw-w64 compiler and headers at least version 10.0 required')
endif
```
I don't have mingw, can't check if it actually work.

**Comment by bmcpt** [comment]
I'm getting this error on latest ubuntu with gcc 10:

```
> x86_64-w64-mingw32-gcc --version
x86_64-w64-mingw32-gcc (GCC) 10-posix 20220113
```

**Comment by guangli0510** [comment]
> I'm getting this error on latest ubuntu with gcc 10:
> 
> ```
> > x86_64-w64-mingw32-gcc --version
> x86_64-w64-mingw32-gcc (GCC) 10-posix 20220113
> ```

maybe you need a newer glslangValidator.
