### ISSUE TITLE
[d3d9] Drakensang - The Dark Eye - Objects blinking

### ISSUE THREAD

**Issue by dlshinobi** [doitsujin/dxvk#2944]
The game runs great with DXVK, except some objects blinking when moving or rotating the camera.
The issue also appear with WINED3D, but works fine on windows native D3D9.
Don't know how useful the apitrace will be, but managed to make it at very painful 1-2fps.

Few very shorts videos of the issue:
- https://drive.google.com/file/d/1oJxLmNzhZeGuL54a1_9tRqhy2SSlF3MZ/view?usp=sharing
- https://drive.google.com/file/d/1LRAjrFHX_W0MlQEgM0rCFUdCuyO-k94Z/view?usp=sharing

### Software information
Drakensang - The Dark Eye

### System information
- GPU: nVidia GTX 960
- Driver: 515.49.14
- Wine version: proton 7.0-4
- DXVK version: 1.10.3, 2.0 master (5c22e2fbda34a622919e4808bb268cedf6ea5bd8)

### Apitrace file(s)
- Put a link here: https://drive.google.com/file/d/1kl1Sgbsy6VU19htHhmJz82rD7qeLfYOd/view?usp=sharing

### Log files
- d3d9.log: https://drive.google.com/file/d/1Z4SINgIYNVQpJLWyVIqAUxlW30rW4tHX/view?usp=sharing

**Comment by dlshinobi** [comment]
> If you have access to windows can you see if it happens when you use dxvk there?
> 
> If yes then could you try to make a trace on windows without dxvk also? I do indeed see the staff disappear shortly in one spot when i replay the trace, but it also happens when i replay it on windows without dxvk. So it seems to be baked into the trace.

Yeah, managed to run "windows + dxvk" combo and no issue. I guess it's the wine or drivers problem. Sorry for the noise. Closing the issue.

**Comment by Blisto91** [comment]
If you post a proton log we can check if anything obvious sticks out
