### ISSUE TITLE
Assassin's Creed: Odyssey Screen Flickering

### ISSUE THREAD

**Issue by pulentiu** [doitsujin/dxvk#2955]
Before listing my issue, I should probably mention that I am on Windows 10, but I don't know if it makes any difference in this specific situation:
In Assassin's Creed: Odyssey the game starts flickering like hell right from the start (except for videos like the Ubisoft and AMD intro videos) and the screen turns white and then normal very, very fast. If i try (very heavy emphasis on try) to load a save, my whole pc freezes on the loading screen and I have to restart it.
I'm pretty sure it's a problem from DXVK with AC: Odyssey in particular because Watch Dogs 2 runs seamlessly on the exact same computer with the exact same DXVK version

### System information
- GPU: AMD Radeon RX Vega 10
- Driver: 27.20.21034.37
- DXVK version: 1.10.3

### Apitrace file(s)
When using Apitrace the screen flickering stopped and the performance was extremely poor, but I decided to leave [a link to the .trace file](https://drive.google.com/file/d/13gd3s2UVwwVZX2Ye8NroaELLJJ8k-Y8i/view?usp=sharing) anyway.

### Log files
- d3d11.log:
[ACOdyssey_d3d11.log](https://github.com/doitsujin/dxvk/files/9639089/ACOdyssey_d3d11.log)

- dxgi.log:
[ACOdyssey_dxgi.log](https://github.com/doitsujin/dxvk/files/9639093/ACOdyssey_dxgi.log)

**Comment by doitsujin** [comment]
Probably an AMD driver bug specific to Vega, the game runs fine on my 6900XT both on Linux *and* on Windows.

**Comment by Ryusennin** [comment]
Win10 + Vega 56 + Radeon 22.9.2 + DXVK 1.10.3 = no issue.

**Comment by Blisto91** [comment]
@pulentiu as said above this could seem like a driver issue. Are you able to update your graphics drivers? 
You'll also need vulkan 1.3 to try latest master but i see your current drivers only say 1.2

**Comment by pulentiu** [comment]
I updated my GPU's Driver to the latest version (30.0.15021.11005), but the flickering still happens. I also tried the master branch on both drivers, and on the old driver it said something about a missing graphics device, while on the newest driver the game just starts and closes after 5 seconds with no error message or anyhting

**Comment by Blisto91** [comment]
Share a new log from a time where it shuts down after 5 seconds

**Comment by pulentiu** [comment]
[ACOdyssey_dxgi.log](https://github.com/doitsujin/dxvk/files/9677167/ACOdyssey_dxgi.log)
[ACOdyssey_d3d11.log](https://github.com/doitsujin/dxvk/files/9677168/ACOdyssey_d3d11.log)

**Comment by Blisto91** [comment]
@pulentiu Friendly ping. Could i get you to try again with latest dxvk and drivers?
