### ISSUE TITLE
[D3D9] Raiden III: Digital Edition crashes ingame

### ISSUE THREAD

**Issue by waspennator** [doitsujin/dxvk#2956]
Hello, I posted about this on Valve's Proton github page and they told me to mention this up here too, for some reason Raiden III Digital Edition crashes when trying to get in game with DXVK. Tested it out on Steam Deck and my Windows 11 laptop and the same issue seems to happen between both devices.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Raiden III: Digital Edition

### System information
- GPU: AMD Van Gogh for Steam Deck, GTX 1650 for the Windows Laptop
- Driver: Mesa 22.0.2 for Steam Deck, Nvidia 516.94 for Windows Laptop
- Wine version: 7.0 on Steam Deck 
- DXVK version: 1.10.3

### Apitrace file(s)
I've been trying to get an Apitrace on windows and I can consistently get it to crash with the d3d9.dll from the 1.10.3 download, but when I try using the Apitrace version of the dll, it doesn't crash. Don't know if i'm doing something wrong or not.

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
- d3d9.log: [Raiden3_d3d9.log](https://github.com/doitsujin/dxvk/files/9641643/Raiden3_d3d9.log)
- d3d11.log:
- dxgi.log:

**Comment by Blisto91** [comment]
> I've been trying to get an Apitrace on windows and I can consistently get it to crash with the d3d9.dll from the 1.10.3 download, but when I try using the Apitrace version of the dll, it doesn't crash. Don't know if i'm doing something wrong or not.

That is fine an expected. apitrace doesn't go trough dxvk on windows by default. It's used to capture all api calls of the game, in this case native directx, and then the devs can replay it themselves with or without dxvk to see if anything stick out.
So if you are able to make a trace to after the point where it usually crashes that would be great.

**Comment by waspennator** [comment]
Alright then, made a trace log accordingly. It usually crashes as soon as you try to start a new game from what i've noticed. ProtonDB reports seem to vary on what was the last version that worked, some say it was 4.11-13 on Deck, others say it's 4.26 or 4.29. I can also say that it works fine when using wined3d too.

[Raiden3.zip](https://github.com/doitsujin/dxvk/files/9641664/Raiden3.zip)

**Comment by Blisto91** [comment]
You mean it usually crashes before it gets to the part in the screenshot below right?

<details>
  <summary>Screenshot</summary>

![Screenshot_20220925_215909](https://user-images.githubusercontent.com/47954800/192162843-2d04eb45-c369-4111-ae3e-4c3273812290.png)
</details>

**Comment by waspennator** [comment]
Yep, on my end it starts the screen transition (Future wall stuff covers the screen), then halfway I hear the sound stutter and stop, then it just silently exits on Deck and Windows.

**Comment by Blisto91** [comment]
Can confirm the crash in the actual game with wined3d, dxvk and dxvk on windows.
Mostly tested with dxvk on windows and i found that it's been crashing like that ever since d9vk 0.13 which is also the first version that could really display anything with the game.
0.12 doesn't crash but instead there are no visuals and the whole screen is just one big color like white, orange or green depending on scene. But i can hear from the music i get past the crash when i press start new game.

Haven't found any config options that change the outcome.

**Comment by waspennator** [comment]
Surprised it's still crashing with wined3d, unless it's something with proton or Linux, since I was able to get the game working with it on deck.

**Comment by Blisto91** [comment]
Oh really? 🤔 
I will have to try messing around with that again then

**Comment by waspennator** [comment]
All I know is with the Steam version on deck, I ran it with the latest Experimental build of Proton, set it to use "PROTON_USE_WINED3D=1 %command%" and somehow it got past the screen transition when starting a new game without issue.

Only thing keeping me from testing further is that... I'm not really that good at shmups.

**Comment by Blisto91** [comment]
Oh yea. It does work with wined3d :sweat_smile: 
Dunno why i thought it didn't. My bad :grin:

**Comment by Blisto91** [comment]
Made a couple of trace myself.
One with dxvk so it crashes while tracing and one with wined3d where it doesn't so they can be compared.

https://mega.nz/file/doJgyDiC#c1tsSpOnraq5oMM65NYHGJPNRTvqryYlKUvPHitub9g

**Comment by K0bin** [comment]
I can't reproduce the crash with the apitrace and I don't have the game.

**Comment by waspennator** [comment]
> I can't reproduce the crash with the apitrace and I don't have the game.

Was it with the latest devbuild of dxvk? Dunno why it wouldn't be crashing on your end, but only crashing on my and Blistos devices

**Comment by waspennator** [comment]
Oooohhhhhh, yeah I wonder what dxvk is doing then that the apitrace isn't picking up?

**Comment by waspennator** [comment]
Tested again on deck. Still seems to crash running with the latest proton Experimental with dxvk. Didn't even stutter before dying on my end, it just silently died twice on the spot the 2 times u tested it.

**Comment by K0bin** [comment]
I've tried looking into it but the game crashes in game code, so it's not obvious what we're doing wrong.

**Comment by waspennator** [comment]
Tested out Raiden 3 Digital Edition on my Windows 11 laptop with the latest dev build of DXVK and yep, seems like it's actually working, thanks again for fixing this.

**Comment by Blisto91** [comment]
Chad @WinterSnowfall
