### ISSUE TITLE
assassins creed origins dosent work it is stuck at black screen i tried everything but it works fine without running vulkan it used to work now its not working

### ISSUE THREAD

**Issue by CaplessCrusader** [doitsujin/dxvk#2959]
assassins creed origins dosent work it is stuck at black screen i tried everything but it works fine without running vulkan it used to work now its not working
### Software information
Assassins creed origins

### System information
- GPU:Vega 11 Radeon
- Driver:Amd Software:Adrenaline Edition 22.5.1
- Windows version: 10
- DXVK version: 1.10.3

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
- d3d9.log:[ACOrigins_d3d9.log](https://github.com/doitsujin/dxvk/files/9652845/ACOrigins_d3d9.log)
- d3d11.log:
[ACOrigins_d3d10.log](https://github.com/doitsujin/dxvk/files/9652846/ACOrigins_d3d10.log)
- dxgi.log:
[ACOrigins_dxgi.log](https://github.com/doitsujin/dxvk/files/9652853/ACOrigins_dxgi.log)

**Comment by CaplessCrusader** [comment]
![Screenshot (75)](https://user-images.githubusercontent.com/114471641/192472680-742e6320-a64e-4de1-a9d0-65767b928495.png)

**Comment by K0bin** [comment]
The game works on Nvidia and RADV, so this is almost certainly a driver bug.

Report this to AMD.

**Comment by CaplessCrusader** [comment]
> 

the game worked fine after first time playing with vulkan then this occurs the next time i went in

**Comment by CaplessCrusader** [comment]
![image](https://user-images.githubusercontent.com/114471641/192481861-37869a5a-3af2-47a2-ba15-1d071b0b9421.png)

**Comment by doitsujin** [comment]
Any reason you're using an outdated driver?

**Comment by CaplessCrusader** [comment]
ah damn reporting dosent help

**Comment by CaplessCrusader** [comment]
> 

no im using literally the most latest or the second most anyways same thing

**Comment by CaplessCrusader** [comment]
works

> The game works on Nvidia and RADV, so this is almost certainly a driver bug.
> 
> Report this to AMD.
![image](https://user-images.githubusercontent.com/114471641/192524954-b16a39ad-26ec-4dfb-84bd-5c0a3d136525.png)
 without using vulkan runs fine

**Comment by doitsujin** [comment]
Well yeah and we already established that it works for other people including myself. Not much we can do here, closing.
