### ISSUE TITLE
[d3d9] [regression] One Piece Pirate Warriors 3 black sky

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#2960]
Noticed by @WWSNK https://github.com/doitsujin/dxvk/pull/2958#issuecomment-1258944660

Since https://github.com/doitsujin/dxvk/commit/f2950953e0d03e62070c234db6edc7974211365f the sky in the game is black.

### Software information
One Piece Pirate Warriors 3.

### System information
- GPU: R9 380
- Driver: 22.1.7
- DXVK version: https://github.com/doitsujin/dxvk/commit/f2950953e0d03e62070c234db6edc7974211365f

### Apitrace file(s)
Taken from https://github.com/doitsujin/dxvk/issues/2693

https://drive.google.com/file/d/1ocmehfbccW3f-HaQeuSOhJ4I_d9Swp2h/view?usp=sharing

**Comment by Joshua-Ashton** [comment]
:(

Guess its still causing issues, bleh.

**Comment by K0bin** [comment]
I don't get why this works fine for WineD3D but doesn't work for us.

**Comment by Blisto91** [comment]
Same issue with the sky in Far Cry 2.
Trace from https://github.com/doitsujin/dxvk/issues/2941 can be used
