### ISSUE TITLE
Heroes of Might and Magic V corruptions and lockups on Haswell

### ISSUE THREAD

**Issue by friedc** [doitsujin/dxvk#2962]
### Software information
Heroes of Might and Magic V shows graphics corruptions when using dxvk that do not happen with wined3d. I captured an apitrace with dxvk v1.10.1 using apitrace-11.1-win32. Replaying the attached trace with apitrace-11.1-win64 and dxvk is a reproducible way to totally crash my graphical session (Gnome Shell using Wayland).

I also captured a trace with wined3d but I noticed that a trace captured with wined3d can not be replayed with dxvk. Curiously, the trace captured with dxvk can not be replayed with wined3d either. This is why I didn't include the wined3d trace here.

I could not create a renderdoc capture from the trace because this would crash wine:

```
$ ENABLE_VULKAN_RENDERDOC_CAPTURE=1 WINEDLLOVERRIDES="d3d9,d3d11,dxgi=n,b" wine apitrace.exe replay H5_Game_trimmed_packed.trace
Z:\REDACTED\.steam\steam\steamapps\common\Heroes of Might and Magic 5\bin\H5
_Game.exe
[0x7B60D190] ANOMALY: Instruction "lea" is modifying the stack
[0x7B60D1A8] ANOMALY: Instruction "lea" is modifying the stack
info:  Game: H5_Game.exe
info:  DXVK: v1.10.1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
0: debug: apitrace: warning: caught exception 0xc0000005
apitrace: warning: caught exception 0xc0000005
0: error: caught an unhandled exception
wine: Unhandled page fault on read access to 0000000000000017 at address 00007F51BE4D173F (thread 0100), starting debugger...
...
```

I know that Haswell is a bit old but a crash of the graphical session is a bit much. That may be a Mesa bug, but for reporting a bug to Mesa I need a renderdoc capture ...

### System information
- GPU: Intel(R) HD Graphics 4600 (HSW GT2)
- Driver: Mesa 22.0.5
- Wine version: wine-6.0.3 (Ubuntu 6.0.3~repack-1)
- DXVK version: v1.10.1

### Apitrace file(s)
[H5_Game_trimmed_packed.trace.zip](https://github.com/doitsujin/dxvk/files/9659345/H5_Game_trimmed_packed.trace.zip)

### Log files
[H5_Game_d3d9.log](https://github.com/doitsujin/dxvk/files/9659356/H5_Game_d3d9.log)

**Comment by Blisto91** [comment]
Can you post a screenshot of the graphical corruptions. Didn't notice anything obvious in the trace on my R9 380.

Also try latest master and see if it makes a difference https://github.com/doitsujin/dxvk/actions/runs/3137839527

**Comment by friedc** [comment]
I have an image captured by a smartphone. A screenshot wasn't possible because the graphical session crashed.

![IMG_20220927_232528](https://user-images.githubusercontent.com/52925889/192641833-689fb0d7-c1f3-46ce-88b3-a53a2f17275d.png)

**Comment by K0bin** [comment]
This is almost certainly a driver bug.

Vulkan support on anything before Maxwell is incomplete.

Nothing we can do here.

**Comment by friedc** [comment]
Is there a way for me to get a renderdoc?

**Comment by K0bin** [comment]
It it crashes, not really.

Just attach the apitrace.
