### ISSUE TITLE
[d3d9] [regression] GTA SA ENBSeries out of body experience

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#2969]
When playing the original GTA SA with ENBSeries ever since commit https://github.com/doitsujin/dxvk/commit/1e1ef8f1bd3970f75f70ef6e4113dcdb30ba0633 when i bike up next to a car the torso will stay back sideways on the bike and the rest will be in the car door. Sometimes the car driver disappears at the same time.
Doesn't happen in the game without ENBSeries

<details>
  <summary>Screenshot</summary>

![Screenshot_20220930_185241](https://user-images.githubusercontent.com/47954800/193325592-f63914fa-1855-412c-818a-f64e15f5649c.png)

</details>

### Software information
Original GTA SA with ENBSeries (0.430 used here)

### System information
- GPU: R9 380
- Driver: Mesa 22.1.7
- Wine version: upstream 7.18 and WINE-GE 7-29
- DXVK version: https://github.com/doitsujin/dxvk/commit/1e1ef8f1bd3970f75f70ef6e4113dcdb30ba0633

### Apitrace file(s)
I have had trouble getting apitrace to work with the game at the same time as ENBSeries.
I tried replaying the traces from https://github.com/doitsujin/dxvk/issues/2900 with master but didn't see anything.

Edit: Managed to trace. This includes one from master and one from the commit before the regression.
https://mega.nz/file/9lh1TQwR#ElGj3w8dIavxvO7FACp_1fAMWRPp7QkhOSqD46sdBHU

### Log files
[gta_sa_d3d9.log](https://github.com/doitsujin/dxvk/files/9686577/gta_sa_d3d9.log)

**Comment by HunterCZ122** [comment]
@Blisto91 Is this Steam version or original v1.0 DVD version? Judging by your screenshot (broken aspect ratio and thinner font shadows) it seems to be Steam version. All mods are mainly made for v1.0 in mind and can be broken on different versions.

**Comment by Blisto91** [comment]
It's the rockstar games launcher version.

**Comment by nipkownix** [comment]
While ENB was never meant to be used with anything but version v1.0, that might not matter here since Blisto mentioned it was fine before commit 1e1ef8f. Hmm.

**Comment by Blisto91** [comment]
Where does it say it's only meant for the original dvd version 🤔 
Can't find that mentioned anywhere in the readme or install notes. Last update was in 2020 from what i can see.
For 0.313 it even mentions that it changed the code of a file to work with both 1.0US and steam version.

**Comment by Blisto91** [comment]
Don't know if it helps but i've made two traces. One on master and one with the commit before https://github.com/doitsujin/dxvk/commit/1e1ef8f1bd3970f75f70ef6e4113dcdb30ba0633
I've added them to the first post

**Comment by K0bin** [comment]
@kdobrowo
