### ISSUE TITLE
File not found. Skipping.

### ISSUE THREAD

**Issue by themainliner** [doitsujin/dxvk#2972]
I feel like I should be apologizing already as I am **sure** this is not a bug, but a pebkac.

This is on antiX Linux 21 Core (Debian 11, non-systemd base), nvidia driver: , dxvk latest, ...

### Software information
World of Warcraft, trying to install DXVK into the wine prefix.

### System information
- GPU: GeForce GTX 1050 Ti
- Driver: 515:76 [vulkan]
- Wine version: winehq-staging 7.18
- DXVK version: 1.10.3

Here's what I'm doing:
From unpacked release folder:
```
mailiner@moonbasebeta:~/Downloads/dxvk-1.10.3
$ export WINEPREFIX="/home/mainliner/.wow/"
mailiner@moonbasebeta:~/Downloads/dxvk-1.10.3
$ ./setup_dxvk.sh install
wine: configuration in L"/home/mainliner/.wow" has been updated.
/home/mainliner/Downloads/dxvk-1.10.3/x64/dxgi.dll: File not found. Skipping.
/home/mainliner/Downloads/dxvk-1.10.3/x32/dxgi.dll: File not found. Skipping.
/home/mainliner/Downloads/dxvk-1.10.3/x64/d3d9.dll: File not found. Skipping.
/home/mainliner/Downloads/dxvk-1.10.3/x32/d3d9.dll: File not found. Skipping.
/home/mainliner/Downloads/dxvk-1.10.3/x64/d3d10core.dll: File not found. Skipping.
/home/mainliner/Downloads/dxvk-1.10.3/x32/d3d10core.dll: File not found. Skipping.
/home/mainliner/Downloads/dxvk-1.10.3/x64/d3d11.dll: File not found. Skipping.
/home/mainliner/Downloads/dxvk-1.10.3/x32/d3d11.dll: File not found. Skipping.
```

I just know I'm doing something (not doing something) really stupid.

Be gentle.

**Comment by Blisto91** [comment]
How does the content of your `dxvk-1.10.3` folder look?
It includes a `x32` & `x64` folder with the DLLs inside both right?

**Comment by WinterSnowfall** [comment]
Could be some ownership/permission issues on the dxvk folder or subfolders perhaps.

**Comment by pga256** [comment]
> Could be some ownership/permission issues on the dxvk folder or subfolders perhaps.

I think the problem is the ownership of the .wine folder.
the user is logged in as "mailiner" but the home folder that contains .wine is "mainliner". Two different users perhaps?

**Comment by K0bin** [comment]
@themainliner Did you check the permissions of the .wine in your home directory?

**Comment by penmerchant** [comment]
> 
mine doesnt include these files

**Comment by penmerchant** [comment]
> How does the content of your `dxvk-1.10.3` folder look? It includes a `x32` & `x64` folder with the DLLs inside both right?

mine doesnt include these files

**Comment by Blisto91** [comment]
Where did you get it from

**Comment by penmerchant** [comment]
@Blisto91 Oh my bad. I git clonned the file from the repo lol. Silly mistake
