### ISSUE TITLE
Graphic bugs on SoulWorker

### ISSUE THREAD

**Issue by fantasyair18** [doitsujin/dxvk#2973]
### Software information
Game name:SoulWorker
Question:Graphic error
![1](https://user-images.githubusercontent.com/51155995/193421446-aff980a0-a863-405c-8428-0c8f3b53e2c1.png)
![2](https://user-images.githubusercontent.com/51155995/193421449-cfb351c8-7a46-4edf-9b5f-31369a46b2a4.png)

### System information
- GPU:Radeon RX 570 Series
- Driver:22.20.19.15-220922a1-383925E-AMD-Software-Adrenalin-Edition
- Wine version: 
- DXVK version: 1.10.3

### Apitrace file(s)
Unable to trace game with apitrace

### Log files
- d3d9.log:[SoulWorker_d3d9.log](https://github.com/doitsujin/dxvk/files/9690858/SoulWorker_d3d9.log)
- d3d11.log:
- dxgi.log:

**Comment by Blisto91** [comment]
Try and check with latest master https://github.com/doitsujin/dxvk/actions/runs/3161863316

**Comment by fantasyair18** [comment]
> Try and check with latest master https://github.com/doitsujin/dxvk/actions/runs/3161863316

d3d9.log:[SoulWorker_d3d9.log](https://github.com/doitsujin/dxvk/files/9690915/SoulWorker_d3d9.log)

**Comment by Blisto91** [comment]
The game doesn't work on Linux because of anti cheat. But i can reproduce on Windows.
It appears to be a regression as it works in a old version i tried. Gonna try to see if i can pinpoint the commit

**Comment by fantasyair18** [comment]
> The game doesn't work on Linux because of anti cheat. But i can reproduce on Windows. It appears to be a regression as it works in a old version i tried. Gonna try to see if i can pinpoint the commit

Thank you

**Comment by K0bin** [comment]
We need that apitrace to fix this.

Please give it another go: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

**Comment by Blisto91** [comment]
I have an apitrace. Will upload here later

**Comment by Blisto91** [comment]
https://mega.nz/file/8ohnGDDL#eIRUiJBKs4nsFMxeK2yLRg_NVyVYeypHjtBPIbP9vuU

Issue only happens with AMD's own driver (Windows/amdvlk) not with Linux radv. Haven't tried on Nvidia.
I'm guessing from the commit it breaks this could be a driver issue?  https://github.com/doitsujin/dxvk/commit/23691cd0ff6d9a2af6c84872cacf08e8cb5079c0

**Comment by doitsujin** [comment]
Yes, this is an extremely common issue on Windows AMD drivers. Can't really fix.

**Comment by fantasyair18** [comment]
I tried to use version 1.7 and it looks fine, but the shadows have bugs.
![dxvk](https://user-images.githubusercontent.com/51155995/193440353-5e9921df-6400-4caf-99c3-5b14621e7406.png)

**Comment by Blisto91** [comment]
You'll sadly have to deal with the issues above until (or if) amd fixe the original issue. Or play the native version.
You could try reporting a bug to amd, but dunno how much they care about games that use dxvk on Windows.

**Comment by fantasyair18** [comment]
I tried removing the latest driver.
Using the driver from Windows Update, it looks ok.
Driver:26.20.12028.2
![3](https://user-images.githubusercontent.com/51155995/193467973-5e2584fb-38b2-44e6-ae83-3f746ecfa4ee.png)
Thank you for helping

**Comment by Blisto91** [comment]
Oh that's great to hear. Didn't notice you weren't using the latest driver.
My card isn't supported anymore with amd's own drivers so couldn't test the latest one myself

**Comment by s09289728096** [comment]
I just noticed this issue and try to fix it. Here is the result.

`commit b34421b055df5c81192faac800906be5985fe175 (HEAD)
Author: Philip Rebohle <philip.rebohle@tu-dortmund.de>
Date:   Mon Jul 4 16:13:06 2022 +0200

    [dxvk] Always enable extendedDynamicState feature`

I found this commit led to the bad displaying, and the git diff is:

`elwin@DESKTOP-A0VR4BU:~/dxvk/master$ git diff f19607c1
diff --git a/src/dxvk/dxvk_adapter.cpp b/src/dxvk/dxvk_adapter.cpp
index 1ceda524..8ba0359d 100644
--- a/src/dxvk/dxvk_adapter.cpp
+++ b/src/dxvk/dxvk_adapter.cpp
@@ -328,7 +328,7 @@ namespace dxvk {
     DxvkNameList extensionNameList = extensionsEnabled.toNameList();

     // Enable additional device features if supported
-    enabledFeatures.extExtendedDynamicState.extendedDynamicState = m_deviceFeatures.extExtendedDynamicState.extendedDynamicState;
+    enabledFeatures.extExtendedDynamicState.extendedDynamicState = VK_TRUE;

     enabledFeatures.ext4444Formats.formatA4B4G4R4 = m_deviceFeatures.ext4444Formats.formatA4B4G4R4;
     enabledFeatures.ext4444Formats.formatA4R4G4B4 = m_deviceFeatures.ext4444Formats.formatA4R4G4B4;
diff --git a/src/dxvk/dxvk_context.cpp b/src/dxvk/dxvk_context.cpp
index b66169d8..261752da 100644
--- a/src/dxvk/dxvk_context.cpp
+++ b/src/dxvk/dxvk_context.cpp
@@ -19,9 +19,6 @@ namespace dxvk {
     m_gfxBarriers (DxvkCmdBuffer::ExecBuffer),
     m_queryManager(m_common->queryPool()),
     m_staging     (device, StagingBufferSize) {
-    if (m_device->features().extExtendedDynamicState.extendedDynamicState)
-      m_features.set(DxvkContextFeature::ExtendedDynamicState);
-
     // Init framebuffer info with default render pass in case
     // the app does not explicitly bind any render targets
     m_state.om.framebufferInfo = makeFramebufferInfo(m_state.om.renderTargets);
@@ -4988,13 +4985,8 @@ namespace dxvk {

     // Vertex bindigs get remapped when compiling the
     // pipeline, so this actually does the right thing
-    if (m_features.test(DxvkContextFeature::ExtendedDynamicState)) {
-      m_cmd->cmdBindVertexBuffers2(0, m_state.gp.state.il.bindingCount(),
-        buffers.data(), offsets.data(), lengths.data(), nullptr);
-    } else {
-      m_cmd->cmdBindVertexBuffers(0, m_state.gp.state.il.bindingCount(),
-        buffers.data(), offsets.data());
-    }
+    m_cmd->cmdBindVertexBuffers2(0, m_state.gp.state.il.bindingCount(),
+      buffers.data(), offsets.data(), lengths.data(), nullptr);
   }`

This commit use another bind method and the argument **lengths.data()** is suspicious.

Thus I fix the display issue even in tag v2.3 with this.

`elwin@DESKTOP-A0VR4BU:~/dxvk/dxvk$ git diff
diff --git a/src/dxvk/dxvk_context.cpp b/src/dxvk/dxvk_context.cpp
index 80c2620d..17109b64 100644
--- a/src/dxvk/dxvk_context.cpp
+++ b/src/dxvk/dxvk_context.cpp
@@ -5677,7 +5677,7 @@ namespace dxvk {
     // Vertex bindigs get remapped when compiling the
     // pipeline, so this actually does the right thing
     m_cmd->cmdBindVertexBuffers(0, m_state.gp.state.il.bindingCount(),
-      buffers.data(), offsets.data(), lengths.data(),
+      buffers.data(), offsets.data(), nullptr,
       newDynamicStrides ? strides.data() : nullptr);
   }`

I think my problem has solved. I'm not understatnding about vulkan, so I don't know if this change makes another issue.
