### ISSUE TITLE
[D3D11] Metal: Hellsinger crashes while loading a new game.

### ISSUE THREAD

**Issue by r2rX** [doitsujin/dxvk#2975]
So the game is [Metal: Hellsinger](https://store.steampowered.com/app/1061910/Metal_Hellsinger/), it's a Unity engine based game and it runs on DX11. My first run was with the stable release of dxvk, v10.3.0, which runs fine for the exception of lighting related artifacts. I then tested with the most recent artifact (2382 as of writing) and experienced a crash to desktop, with an error dialogue box, after a few seconds of a new game loading. 

![metal_error](https://user-images.githubusercontent.com/18622885/193712645-622e3087-eae1-4c59-894a-b783261dc822.png)

My next step was to sift through alot of artifact releases to try and pinpoint when the break started. Eventually, I found that artifact 1591 was the last version that works without crashing and has the lighting artifacts fixed (so the graphics are perfect).

The issue starts with artifact 1598 (_[dxbc] Fix UAV write test_). All (randomly selected) artifacts beyond 1598 results with the game crashing.

To replicate the issue, simply run the game using dxvk artifact 1598, select New Game, choose any difficulty level and select Continue. It will crash after a few seconds, during the loading screen, eventually showing the error message. This can be tested either with the full release or demo.

### System information
- GPU: AMD RX 6800M
- Driver: Mesa 22.3.0-devel (40c32df)
- Wine version: Proton Experimental & GE-Proton7-30
- DXVK version: [v1.10.3](https://github.com/doitsujin/dxvk/releases/tag/v1.10.3), artifact [#1591](https://github.com/doitsujin/dxvk/actions/runs/2705648941) and [#1598](https://github.com/doitsujin/dxvk/actions/runs/2707796110)

### Apitrace file(s)
- [apitrace - 1598 (crashes)](https://mega.nz/file/nPg0GahS#7EAnMo62MvsdDd8xyg7NUH9rdxe36ii1XCALWsfSegc)
- [apitrace - 1591 (working)](https://mega.nz/file/iOY13YSZ#cZVoArDF8ECMLLc7_VbZMayWZ2OPYY0UprswcByD5uA)

**Comment by Blisto91** [comment]
Can confirm with the demo.

Could you make a apitrace with a version where it doesn't crash? :slightly_smiling_face:

**Comment by r2rX** [comment]
> Can confirm with the demo.
> 
> Could you make a apitrace with a version where it doesn't crash? slightly_smiling_face (demo didn't want to launch with apitrace for me on a quick try)

My original post was updated with links for the apitraces.

**Comment by doitsujin** [comment]
Should be fixed with the above commit.

**Comment by r2rX** [comment]
Happy to confirm it's fixed. Thanks!
