### ISSUE TITLE
Games that use D3D9x almost exclusively

### ISSUE THREAD

**Issue by ColonelGerdauf** [doitsujin/dxvk#2978]
There are a number of games, and game engines (latter example being Game Maker Studio v1), that only use d3d9.dll for creation of the environment and interface object. They tend to use 9ex for the actual legwork of rendering. I have confirmed this with a Ghidra inspection.

![image](https://user-images.githubusercontent.com/6895655/194586714-22941599-481d-4f0f-88d9-fc4ddc666b9b.png)

What can be done in this situation? GMS1 games come with their own d3dx9_43.dll file that points to the regular DirectX call stack. Is there a way to migrate the functions to Vulkan?

**Comment by K0bin** [comment]
D3D**X** (not to be confused with D3D9Ex) is a helper library that just calls regular D3D9 internally.

The Microsoft implementation of D3DX9_43 will work just fine with DXVK. Alternatively, Wine has an implementation of D3DX9_43 as well.
