### ISSUE TITLE
Resident Evil 2 Remake  For Directx11 水流穿模

### ISSUE THREAD

**Issue by sotqngv07** [doitsujin/dxvk#2980]
生化危机2重制版 在象棋插销关卡，放下高台位置，会出现水流层次问题。水花会在高台上面，正常是在高台下面。还有水泥走廊也会被水流波纹影响到，虽然水泥遮挡了水，但是还是看到水的波纹

**Comment by Blisto91** [comment]
> Resident Evil 2 Remake In the chess latch level, if you put down the high platform, there will be a water flow level problem. The water splash will be on the high platform, normally under the high platform. There are also cement corridors that are also affected by water ripples. Although the cement blocks the water, the ripples of the water can still be seen.

Google translate

**Comment by Blisto91** [comment]
@sotqngv07 
Please try to fill out the issue template. We need to know your operating system, graphics card and driver version, which dxvk version you used.
Post the logs that appear next to the games exe and make a apitrace.
Also if you can post a screenshot of the issue.

请尝试填写问题模板。 我们需要知道您的操作系统、显卡和驱动程序版本，您使用的是哪个 dxvk 版本。
发布出现在游戏 exe 旁边的日志并制作 apitrace。
另外，如果您可以发布问题的屏幕截图。

https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

**Comment by kassindornelles** [comment]
> 生化危机2重制版 在象棋插销关卡，放下高台位置，会出现水流层次问题。水花会在高台上面，正常是在高台下面。还有水泥走廊也会被水流波纹影响到，虽然水泥遮挡了水，但是还是看到水的波纹

can you screenshot/record it please?
i can try to reproduce your problem but i'm not sure of what platform you are talking about, it can be literally anything in the sewers section

**Comment by Blisto91** [comment]
@sotqngv07 Friendly ping
