### ISSUE TITLE
GTA IV Loading Times

### ISSUE THREAD

**Issue by Jax765** [doitsujin/dxvk#2982]
Loading times when using DXVK are noticeably longer compared to running the game in its vanilla state. One example being the initial loading into the map from the main menu.

### Software information
GTA IV Complete Edition, Steam version

### System information
- GPU: RTX 3080
- Driver: 516.94
- DXVK version: 1.10.3
- Windows 10 Home

### Log files
- d3d9.log: 
[GTAIV_d3d9.log](https://github.com/doitsujin/dxvk/files/9739639/GTAIV_d3d9.log)

**Comment by Blisto91** [comment]
I tried timing it on my AMD setup on windows 10. R9 380 and Intel i5-6600k
Both with native amd with dxvk from i pressed start game to i was in Niko's appartment took 15 seconds. Maybe dxvk was half a second slower.

Does this always happen. Do you alt tab before you enter loading screens?

**Comment by K0bin** [comment]
13s for me with DXVK.

I don't know how long it takes with Nvidias D3D9 driver but I don't really see a good reason to invest any time into this when the difference is likely around 5 seconds at worst.

**Comment by Jax765** [comment]
No alt-tabbing. These are the times I get between pressing "start game" and the game loading into the apartment.

D3D9 - 15 seconds
DXVK - 33 seconds

Should probably also mention that I'm using an i7 12700k. Game is installed on an NVME SSD.

**Comment by Blisto91** [comment]
Can you quickly check with latest master? <https://github.com/doitsujin/dxvk/actions/runs/3204372286>
Not that i expect a difference.

**Comment by Jax765** [comment]
Loading times were worse with that version. 42 seconds instead of 33.

**Comment by K0bin** [comment]
Do you have any mods installed? Also are you playing the base game or the DLC?

Loading consistently takes 14 seconds for me.

**Comment by Jax765** [comment]
Base game. I tested with a clean vanilla install, and then with mods installed. Same result both times.

**Comment by K0bin** [comment]
Complete edition on Steam, literally just downloaded for testing it.

**Comment by Blisto91** [comment]
I will check on windows on my Nvidia setup later

**Comment by Jax765** [comment]
Think I might have found a cause. Testing further to narrow things down first.

**Comment by Jax765** [comment]
Seems the combo of dxvk & a launch command, "-managed", was causing the issue. Removing that command fixed it.

**Comment by K0bin** [comment]
If it's stuttery, that's the fault of the game. I've already optimized DXVK to work well with the way the game handles its textures without that option.

**Comment by K0bin** [comment]
Loading times with the -managed option seems to depend on the absolute frame rate. So make sure your vsync setting is the same when comparing DXVK and the Nvidia D3D9 driver.

If I disable vsync, the loading screen runs at 1000+ FPS and the loading is done in 14 seconds (just like without the managed option). If vsync is enabled, it's locked to 165 FPS (refresh rate of my screen) and loading takes 23 seconds. Both of those are with DXVK.
