### ISSUE TITLE
PAYDAY 2 few patches ago everything was fine

### ISSUE THREAD

**Issue by nullifiedcatt** [doitsujin/dxvk#2983]
### Software information
PAYDAY 2, High settings. 

### System information
- GPU: NVIDIA GeForce RTX 3060
- Driver: 517.48
- Win version: 10 x64 Home Edition
- DXVK version: 1.10.3

### Log files
- d3d9.log: [payday2_win32_release_d3d9.log](https://github.com/doitsujin/dxvk/files/9747683/payday2_win32_release_d3d9.log)
- crash.txt: [crash.txt](https://github.com/doitsujin/dxvk/files/9747721/crash.txt)

**Comment by K0bin** [comment]
Try uninstalling RivaTuner Statistics Server and MSI Afterburner. Those are known to break Vulkan applications.
