### ISSUE TITLE
Fresh git compile shows ver 1.10.1 instead of 1.10.3 latest?

### ISSUE THREAD

**Issue by cglmrfreeman** [doitsujin/dxvk#2986]
Please describe your issue as accurately as possible.

~~When building as of commit 4bcabe8d460b39baa824ddd215bddfb5aedcb0fa with `./package-release.sh /path/ --no-package`, the Meson build system outputs version `v1.10.1` and the build itself references nonexistant git commit [g4bcabe](https://github.com/doitsujin/dxvk/commit/g4bcabe). Setting `DXVK_HUD` to `version` shows `1.10.1-937-g4bcabe8d`.~~

EDIT: I've just realized the `g` is supposed to be dropped and must stand for `git`, and the correct commit build is shown, 4bcabe8d, however this doesn't explain why I'm getting a ver `1.10.1` and not the current release of `1.10.3`.

### Software information
Overwatch 2 via Lutris, yadda yadda

### System information
- GPU: NVIDIA GeForce GTX 1080
- Driver: 515.76
- Wine version: caffe-7.18
- DXVK version: 4bcabe8d460b39baa824ddd215bddfb5aedcb0fa

### Apitrace file(s)
Will provide if requested but I don't see this as a game specific issue.

### Log files
Will provide if requested but I don't see this as a game specific issue.

**Comment by K0bin** [comment]
1.10.2 and 1.10.3 aren't based off of master but the 1.10.x branch instead.

That's why the HUD shows 1.10.1+ for development versions. There's nothing wrong here, you'll see the proper version once we tag the next release based on master.

**Comment by cglmrfreeman** [comment]
Ah that's fair, however I'm not entirely sure how I would have known that, but now I know.

**Comment by K0bin** [comment]
> however I'm not entirely sure how I would have known that

No way for you to know that unless you follow the development closely.

Nothing wrong with asking, don't worry about it.
