### ISSUE TITLE
Borderlands 2. Closing the application after loading the save.

### ISSUE THREAD

**Issue by AnimeAnalPRO** [doitsujin/dxvk#2993]
After loading the save, the game freezes for a couple of seconds and then the game closes. When I first played with DXVK for several hours, everything was fine, but the next day such a problem began to occur. With the help of DXVK, I can play almost on high.

### Software information
Borderlands 2 Steam, 1080p

### System information
- GPU: NVidia 1050 Ti 4Gb
- Driver: 516.94
- Windows 10 x64 
- DXVK version: 1.10.3

### Apitrace file(s)
I have not been able to reproduce this error.

### Log files
- d3d9.log:
[d3d9.zip](https://github.com/doitsujin/dxvk/files/9800114/d3d9.zip)

- d3d11.log: -
- dxgi.log: -

**Comment by Blisto91** [comment]
Hello.
Try and see if it works better with latest master. https://github.com/doitsujin/dxvk/actions/runs/3259837904
There have been improvements to memory management in relation to d3d9 32 bit games.

**Comment by K0bin** [comment]
What Blisto said.

This is another instance of a game running out of address space (#1318). It should hopefully work much better with the latest version of DXVK.

**Comment by AnimeAnalPRO** [comment]
The new build helped. Tested 5-6 runs everything works fine. Thanks!
