### ISSUE TITLE
Fallout New Vegas (Steam) - VATS delay

### ISSUE THREAD

**Issue by Jax765** [doitsujin/dxvk#2994]
Using VATS often results in a delay until the shot percentages actually load in. With DX9, the percentages generally load instantly. With DXVK, they can either take a bit longer than DX9, or significantly longer (several seconds).

- GPU: RTX 3080
- Driver: 522.25
- DXVK version: 1.10.3
- Windows 10 Home

### Log files
[FalloutNV_d3d9.log](https://github.com/doitsujin/dxvk/files/9804326/FalloutNV_d3d9.log)

**Comment by K0bin** [comment]
> info:    d3d9.evictManagedOnUnlock = True
> info:    dxvk.enableAsync = true

Use an official build and remove those 2 options.

**Comment by Jax765** [comment]
d3d9.evictManagedOnUnlock = True prevents the game from constantly crashing when using DXVK.

**Comment by mbriar** [comment]
Try with a recent master build of DXVK and without the option, it should improve the memory related crashes: https://github.com/doitsujin/dxvk/actions/runs/3259837904

**Comment by K0bin** [comment]
Please make an apitrace of the issue and upload that.

**Comment by doitsujin** [comment]
What on earth is VTAS?

**Comment by Blisto91** [comment]
V.A.T.S
It's the non realtime combat system in the fallout games https://fallout.fandom.com/wiki/VATS

**Comment by doitsujin** [comment]
Ah that thing, I thought this was a mod or something.

Please assume that we generally have no idea about the game in question even if it's as popular as Fallout.

**Comment by Blisto91** [comment]
I will try to see if i can reproduce this here later when i have time. (But apitrace would still be appreciated)

**Comment by Jax765** [comment]
> Try with a recent master build of DXVK and without the option, it should improve the memory related crashes: https://github.com/doitsujin/dxvk/actions/runs/3259837904

VATS delay still occurs with that build. Also doesn't seem to play well with msi afterburner (overlay doesn't show up when using that specific build).

Regarding apitrace, I tried it out, but while it did produce a file on my desktop, msi afterburner indicated that the game was running in d3d9 instead of vulkan. VATS issue wasn't occurring as a result.

**Comment by K0bin** [comment]
>  Also doesn't seem to play well with msi afterburner (overlay doesn't show up when using that specific build).

The Vulkan integration of MSI Afterburner is broken and we don't support that.

> Regarding apitrace, I tried it out, but while it did produce a file on my desktop, msi afterburner indicated that the game was running in d3d9 instead of vulkan. VATS issue wasn't occurring as a result.

That's fine. Please still upload the apitrace.

**Comment by K0bin** [comment]
This seems to be a rather wide spread game bug. If you google "Fallout VATS delay" or "Fallout VATS lag", there are a lot of results.

**Comment by Jax765** [comment]
Uploading the apitrace file now. Regarding afterburner, it works fine with 1.10.3 and prior versions. Just seems to have issues with the recent master build.

VATS lag has been a thing with the game from what I recall. But DXVK seems to exacerbate it. As I said, I tested DX9 & Vulkan, and the former had very little delay when initiating it.

**Comment by K0bin** [comment]
Absolutely no idea what's going on. There's nothing in DXVK, that can delay things by seconds while still rendering frames.

This seems to be some super weird timing bug in the engine that's somehow triggered by DXVK.
I can't fix this.

**Comment by Jax765** [comment]
https://drive.google.com/file/d/1GEI5uYNcvntBZ6m1y9P1T8BxIfMtLpsl/view?usp=sharing

**Comment by K0bin** [comment]
> The delay is actually a hardcoded 2 second wait, it was added as a workaround in one of the updates to address the hit percentages not always calculating correctly. I've tried to figure out what the bug they were trying to fix was but have been unsuccessful so far. You can lower the wait to 500ms in my Tweaks engine plugin if you add the line bFixVATSLag=1 under the [Tweaks] heading, but note that it causes the hit percentages to be slightly different.

https://www.reddit.com/r/fnv/comments/nxuor9/vats_hit_percentages_are_slow_to_load_when/

No clue, why this only happens with DXVK for you but I also don't see how D3D9 would be involved with that. There's nothing we can do here.

**Comment by vlad54rus** [comment]
The same issue happens in Fallout 3 - there's an 1+ seconds delay when using DXVK, while on native d3d9 it's almost always instant.
