### ISSUE TITLE
black screen on assassin's creed origins as soon I open the game

### ISSUE THREAD

**Issue by sikh08** [doitsujin/dxvk#2995]
First time I played; it went well. I played perfectly until I shutdown my pc
I deleted the files (d3d11.dll, dxgi.dll)and it worked well, but I put the files in the game root again, the game gets stuck

AMD radeon software shows this error

![amd error](https://user-images.githubusercontent.com/116125319/196584061-968ce7ea-6fe5-4c66-b39f-91421261465c.PNG)

something curious in amd radeon software was this notification.

![radeon wattman](https://user-images.githubusercontent.com/116125319/196584315-b85ee28a-8162-4951-9ce2-33d1ef36c513.PNG)
radeon wattman settings have been restored due to an unexpected system failure

capture from my background system

![background](https://user-images.githubusercontent.com/116125319/196584978-0a0bc17b-6d5c-43a7-80c3-5094b633884c.PNG)

I tried to delete save game 
Changed resolution
Changed graphics settings
Graphic drivers are up to update
Tried with an old version of dxvk 

but unfortunely nothing worked

### Software information
windows 10 21H1 (compilation 19043.1889)
assassin's creed Version 1.5.1
settings used low

### System information
- GPU: RX 5500 XT MECH 4GB
- Driver: 22.5.1
- DXVK version:  1.10.3

### Log files
- d3d9.log: [ACOrigins_d3d9.log](https://github.com/doitsujin/dxvk/files/9816392/ACOrigins_d3d9.log)

- d3d11.log: [ACOrigins_d3d11.log](https://github.com/doitsujin/dxvk/files/9816388/ACOrigins_d3d11.log)

- dxgi.log: [ACOrigins_dxgi.log](https://github.com/doitsujin/dxvk/files/9816386/ACOrigins_dxgi.log)

I would appreciate your support

**Comment by Blisto91** [comment]
Try to give latest master a spin. https://github.com/doitsujin/dxvk/actions/runs/3268994708

**Comment by sikh08** [comment]
> Try to give latest master a spin. https://github.com/doitsujin/dxvk/actions/runs/3268994708

sorry I don't know what you want me to do

**Comment by Blisto91** [comment]
Download the artifact called `dxvk-master-53a0c3726c311ea01846f83afa670972f502b619` from the link above and use the same dll's with the game as when you downloaded the 1.10.3 release.

**Comment by K0bin** [comment]
Try with the DXVK version linked on that page.

**Comment by sikh08** [comment]
I decide to reinstall the game and use d3d11.dll, dxgi.dll and now is working. I reboot the game and my pc several times to make sure and its working.
think just a reinstall to make it work.
thank you so much for your help, youre doing a very good job keep it up
