### ISSUE TITLE
enum adtapters error with multi gpu 

### ISSUE THREAD

**Issue by Huge-Toon** [doitsujin/dxvk#2999]
My laptop is on win11, with amd radeon integrated gpu and nvidia dedicated gpu installed simultaneously.when I try to launch game, it occurs game crash, and logs file as shown below. finally I temporarily solve the problem by disabling my integrated gpu in device manager.
dxgi.logs:
info:  Game: ACOdyssey.exe
info:  DXVK: v1.10.3-async
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
err:   DxvkInstance::enumAdapters: Failed to enumerate adapters

**Comment by Blisto91** [comment]
Could you try to reinstall the gpu driver for your integrated gpu? Might be an issue with it's vulkan driver.

**Comment by doitsujin** [comment]
This error is shown only if the `vkEnumeratePhysicalDevices` call fails, which will affect all Vulkan applications. We can't do anything about broken setups.
