### ISSUE TITLE
Please make VK_KHR_descriptor_update_template optional

### ISSUE THREAD

**Issue by pchome** [doitsujin/dxvk#300]
With patches applied from current `renderdoc` branch I able to use `vulkan` implementation from `wine-staging-2.21` again.

Not sure if it should change things more than `min. supported WINE version`. Also no noticeable changes so far I checked, except list of supported extensions reported by tools like `vulkanCapsViewer` (**10** - `wine 3.6` vs **37** - `wine 2.21`).

wine-staging 3.6:
```
warn:  Vulkan extension VK_EXT_vertex_attribute_divisor not supported
warn:  Vulkan extension VK_KHR_maintenance2 not supported
info:  Enabled device extensions:
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_maintenance1
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
```
wine-staging 3.6 + vulkan from 2.21:
```
info:  Enabled device extensions:
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
```

**Comment by Kerrung** [comment]
Why are you still using Wine Staging 2.21?
Really why?!?! o_O

**Comment by doitsujin** [comment]
I won't support outdated wine versions forever. `VK_KHR_descriptor_update_template` is required because it improves performance over the old code path, and I **will not** maintain multiple code paths that do essentially the same thing.

> except list of supported extensions reported by tools like vulkanCapsViewer (10 - wine 3.6 vs 37 - wine 2.21).

That's because the Vulkan implementation from 2.21-staging is **broken**. It reports extensions that it does not support, and that can lead to issues especially with 32-bit applications.

**Comment by doitsujin** [comment]
By the way, the incorrect extension reporting is also the reason why it doesn't even make sense to make it optional. It won't work, because 2.21-staging will report the extension as supported, and then crash because it doesn't implement the required functions.

**Comment by pchome** [comment]
Understood.
