### ISSUE TITLE
[Windows D3D9] Guitar Hero World Tour Definitive Edition crash after 3-4 songs played

### ISSUE THREAD

**Issue by TheDeusDeceptor** [doitsujin/dxvk#3000]
Guitar Hero World Tour with Definitive Edition mod crashes after few songs played (3-4 in my expirience)

### Software information
Guitar Hero World Tour Definitive Edition for PC (D3D9)

### System information
- GPU: RX 580 8gb
- Driver: 22.8.1
- DXVK version: 1.10.3
- Windows 10 21H2

### Apitrace file(s)
- [apitrace](https://drive.google.com/file/d/1knbE04Le-8o3hKNCSZudRGqQmzNeUVIk/view?usp=sharing) (it doesnt crash without DXVK but maybe it will help)

### Log files
- d3d9.log:
[GHWT_Definitive_d3d9.log](https://github.com/doitsujin/dxvk/files/9827656/GHWT_Definitive_d3d9.log)

**Comment by Blisto91** [comment]
Hello. This should already be solved on master.
Try download it from here and see if it helps https://github.com/doitsujin/dxvk/actions/runs/3268994708

**Comment by TheDeusDeceptor** [comment]
> Hello. This should already be solved on master. Try to download it from here and see if it helps https://github.com/doitsujin/dxvk/actions/runs/3268994708
> 
> 1.10.3 doesn't contain the memory handling improvements

No CTDs now. Thank you! It worked!
