### ISSUE TITLE
Uncharted Dx feature level 11.1 error fix for 750ti plz fix latest release legendary  Uncharted need fix.

### ISSUE THREAD

**Issue by zubair47** [doitsujin/dxvk#3004]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Name of the game, settings used etc.

### System information
- GPU:
- Driver:
- Wine version: 
- DXVK version: 

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by zubair47** [comment]
Need fix for UNCHARTED getting dx error on 750ti.

**Comment by K0bin** [comment]
Uncharted uses Direct3D 12. DXVK only implements D3D9, 10 and 11.

**Comment by zubair47** [comment]
Sir I just want to know will your team Launching any fix for this issue just like God of war, death stranding,ac vadhala .

**Comment by Blisto91** [comment]
DXVK doesnt handle DirectX 12 games. vkd3d-proton does.
On the next major release of both of the above kepler cards won't be supported anymore as there will be a driver requirement bump. Kepler was always a bit iffy with their Vulkan support and even some DirectX 11 features. So they tend to have more issues specific to them than newer cards.

**Comment by pchome** [comment]
750ti is Maxwell 1 card.
Not sure how it work with DirectX 12 games, I have card but no singe DirectX 12 game in my library to check.

**Comment by Blisto91** [comment]
Ah ye. Keep forgetting the weird mixed names. My bad :slightly_smiling_face: 
But anyhow the issue should be reported at the vkd3d-proton issue.
