### ISSUE TITLE
The Infectious Madness of Doctor Dekker flickers

### ISSUE THREAD

**Issue by friedc** [doitsujin/dxvk#3005]
Intro sequence flickers like mad. Haven't tested more.

### Software information
https://store.steampowered.com/app/545540/The_Infectious_Madness_of_Doctor_Dekker/

### System information
- GPU: AMD RADV POLARIS10 (aka RX480)
- Driver: Mesa 22.0.5
- Wine version: wine-6.0.3 (Ubuntu 6.0.3~repack-1)
- DXVK version: v1.10.3

### Apitrace file(s)
[timodd_trimmed_packed.zip](https://github.com/doitsujin/dxvk/files/9844203/timodd_trimmed_packed.zip)

### Log files
[timodd_d3d9.log](https://github.com/doitsujin/dxvk/files/9844204/timodd_d3d9.log)

**Comment by WinterSnowfall** [comment]
To whom it may concern, I'm getting `557: warning: shared surfaces unsupported` when replaying the attached trace.

**Comment by K0bin** [comment]
#2749 

The game seems to ping pong between redrawing the entire screen and only updating a part of it on the side.

For example:

Frame 100:
`36128 @0 IDirect3DSwapChain9Ex::Present(this = 0xcdc08f0, pSourceRect = [{left = 0, top = 0, right = 3840, bottom = 2160}], pDestRect = [{left = 0, top = 0, right = 3840, bottom = 2160}], hDestWindowOverride = NULL, pDirtyRegion = NULL, dwFlags = 0x0) = D3D_OK`

Frame 101:
`34756 @0 IDirect3DSwapChain9Ex::Present(this = 0xcdc08f0, pSourceRect = [{left = 2975, top = 1785, right = 3750, bottom = 1907}], pDestRect = [{left = 2975, top = 1785, right = 3750, bottom = 1907}], hDestWindowOverride = NULL, pDirtyRegion = NULL, dwFlags = 0x0) = D3D_OK`

**Comment by K0bin** [comment]
The game actually uses SWAP_EFFECT_DISCARD. So we could probably just ignore the src and dst rects.
