### ISSUE TITLE
Apex Legends: Crash within 5 minutes of entering game

### ISSUE THREAD

**Issue by git-iso** [doitsujin/dxvk#3012]
Apex Legends crashes within 5 minutes once entering a game. Logs give `err:   DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
err:   DxvkDevice: waitForIdle: Operation failed`. 

Running `sudo dmesg` after crash gives `NVRM: Xid (PCI:0000:01:00): 31, pid=13799, name=R5Apex.exe, Ch 00000063, intr 10000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_T1_1 faulted @ 0x0_bb3ad000. Fault is of type FAULT_PDE ACCESS_TYPE_READ`

### System information
- GPU: GTX 1060 6G
- Driver: NVIDIA 520.56.06
- Wine version: Proton 7.0-4
- DXVK version: 1.10.3

### Log files
- d3d11.log: [r5apex_d3d11.log](https://github.com/doitsujin/dxvk/files/9869871/r5apex_d3d11.log)
- dxgi.log: [r5apex_dxgi.log](https://github.com/doitsujin/dxvk/files/9869874/r5apex_dxgi.log)
- apex log : [steam-1172470.log](https://github.com/doitsujin/dxvk/files/9869886/steam-1172470.log)

**Comment by Blisto91** [comment]
@git-iso Could you also give proton experimental a spin just for good measure? 🙂

**Comment by git-iso** [comment]
@Blisto91 Same crash within a few minutes of entering a game.
[steam-1172470.log](https://github.com/doitsujin/dxvk/files/9870513/steam-1172470.log)

**Comment by xpander69** [comment]
Probably some sort of GPU driver/Pascal GPU combination problem or similar. Have you checked if you maybe running out of VRAM on your card?
Works without issues here with the 520.56.06 driver and RTX 3080. Can play hours without issues.

**Comment by git-iso** [comment]
@xpander69 GPU memory hovers around 20%, GPU usage around 98%

**Comment by xpander69** [comment]
> @xpander69 GPU memory hovers around 20%, GPU usage around 98%
Does it also crash like that with older nvidia drivers or vulkan betas?. It surely sounds more like some sort of hardware issue, OC going wrong. RAM being broken or whatnot. There sould be alot of pascal gpu users and apex players around. Havent heard any other talk about having this issue.
I remember i had that Xid31 issue on my 1080Ti with Dirt Rally 2.0  way back also, but it turned out to be my unstable RAM OC. Not trying to say its exactly same thing for you, but yeah...

**Comment by git-iso** [comment]
@xpander69 I only had occasional crashes with previous NVIDIA drivers but 520.56.06 seems to always crash. I don't have any OC on my hardware and other Vulkan games seem fine. If I had to guess it has something to do with the shaders, I'll try to experiment and see if I can fix it.

**Comment by git-iso** [comment]
After much experimentation and testing with`DXVK_HUD` I was able to stop my crashing. In the first few minutes of loading a game, there seems to be a stutter in the frametime that sometimes goes as high as 1200. By limiting my fps  with `+fps_max 60` I was able to stop the stutter from instantly crashing my game. Once in a game, if my GPU usage goes too high (above 70%) my game crashes, so keeping the framelimiter on is necessary. I also let the shaders compile in the menu fully instead of in game.

If I had to guess it has something to do with shader compilation, and since it only started after the latest NVIDIA driver it may be that `VK_EXT_graphics_pipeline_library` that was introduced in it makes the shader process too heavy on my GPU.

**Comment by K0bin** [comment]
> If I had to guess it has something to do with shader compilation, and since it only started after the latest NVIDIA driver it may be that VK_EXT_graphics_pipeline_library that was introduced in it makes the shader process too heavy on my GPU.

Shader compilation happens entirely on the CPU and if the generated shaders crash the GPU despite being valid, that would be a major driver bug.

**Comment by Blisto91** [comment]
@git-iso Can you try again with the new Nvidia driver and latest dxvk? :slightly_smiling_face:

**Comment by wael444** [comment]
i have never had this happen to me, since 520 and onwards.

**Comment by K0bin** [comment]
@git-iso Does it still crash on newer (520+) drivers?

**Comment by git-iso** [comment]
Running DXVK 2.0 on Proton Experimental with driver 520.56.06 still  quickly crashes above 60 fps in-game. It can also occasionally crash with 60 fps limit if GPU usage goes too high.

**Comment by K0bin** [comment]
> if GPU usage goes too high.

Make sure you're not running an unstable OC.

**Comment by Blisto91** [comment]
@git-iso Friendly ping

**Comment by git-iso** [comment]
@Blisto91 I upgraded to a 3060 TI recently and it seems fine, maybe Pascal GPU wasn't working well. I'll close the thread.

**Comment by Blisto91** [comment]
Coolio :+1: 
Good luck with your new GPU :slightly_smiling_face:
