### ISSUE TITLE
EA App fails unable to find d3d10_1.dll

### ISSUE THREAD

**Issue by FireBurn** [doitsujin/dxvk#3014]
I've just tried the new EA App and it fails due to

0328:err:module:import_dll Library d3d10_1.dll (which is needed by L"C:\\windows\\system32\\d2d1.dll") not found
0328:err:module:import_dll Library d2d1.dll (which is needed by L"C:\\Program Files\\Electronic Arts\\EA Desktop\\EA Desktop\\EADesktop.exe") not found
0328:err:module:LdrInitializeThunk Importing dlls for L"C:\\Program Files\\Electronic Arts\\EA Desktop\\EA Desktop\\EADesktop.exe" failed, status c0000135

This dll was removed in https://github.com/doitsujin/dxvk/pull/2881

Going back to commit c49b1ee3909fd48bde7598de9c60c3b53916d9dd got things starting but it doesn't render correctly

### Software information
Name of the game, settings used etc.

### System information
- GPU: Radeon 6800M
- Driver: radv latest git
- Wine version: wine-staging 7.19 & wine-proton 7.0.4
- DXVK version: latest from git

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:
[logs.tar.gz](https://github.com/doitsujin/dxvk/files/9889748/logs.tar.gz)

**Comment by K0bin** [comment]
D3D10_1.dll is provided by Wine. Make sure your prefix is configured to use the builtin version of that DLL.

**Comment by WinterSnowfall** [comment]
,,, I'm guessing something is (horribly) wrong with your prefix. Both dlls are present in Wine by default.

**Comment by K0bin** [comment]
I assume that solved the issue for you?

**Comment by FireBurn** [comment]
It allows the app to load, thanks

It still doesn't render correctly,but that's a separate issue
