### ISSUE TITLE
Empire Total War invisible game objects

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3017]
While i was testing the `surface-factory` branch in random games i noticed a bug in the Windows version of Empire Total War.
If you turn on both Volumetric effects and Anti Aliasing then most of the terrain and objects become invisible.

This also happens with wined3d on Linux and with dxvk on Windows. Doesn't happen with native Windows without dxvk.
I think the trace i made through proton just have the issue baked into it so i also recorded one on Windows and when replaying that one on Linux with dxvk the issue doesn't show so i included both.

I haven't played with config options yet, so this might be something that can just be solved through that. Making the issue first so i won't forget about it.

<details>
  <summary>Screenshot</summary>

![Screenshot_20221030_190747](https://user-images.githubusercontent.com/47954800/198896297-5553b3f2-ba49-44c2-b863-c658f615aee5.png)
</details>

### Software information
Empire Total War.
Volumetric effects and Anti Aliasing turned on

### System information
- GPU: R9 380
- Driver: mesa-git
- Wine version: Proton experimental & 7.0-3 
- DXVK version: master, 1.10.3 & 1.5

### Apitrace file(s)
https://mega.nz/file/A1wVSKoR#NmJqOV_pXo-_jOv-NhUZ0IuyT4MTSavA1ULyxlax7sA

### Log files
[Empire_d3d9.log](https://github.com/doitsujin/dxvk/files/9896589/Empire_d3d9.log)

**Comment by Blisto91** [comment]
The config options I've tried haven't had an effect.
Tho i found this to be a regression in d9vk 0.20

**Comment by mbriar** [comment]
Did you try native d3dx9 and d3dcompiler? Being either backed into the trace or not might point in that direction.

**Comment by Blisto91** [comment]
Game only load's `d3dx9_40.dll` and it's already native. Also the issue shows on Windows with dxvk.

**Comment by mbriar** [comment]
Oh right, overlooked that part, never mind.
