### ISSUE TITLE
feature/idea: virtual cpu driver to vk adapter (more cpu virtual cores)

### ISSUE THREAD

**Issue by goofyseeker311** [doitsujin/dxvk#3019]
ie, map the gpu cores to virtual cpu cores (windows/linux) to be directly programmed with normal performance/efficiency core x86 program code logic

**Comment by goofyseeker311** [comment]
yes or cpu code programming without any gpu apis (dx, vulkan, gpu assembler), so kinda cuda but cpu programming only, think java cpu threads to vulkan

**Comment by Blisto91** [comment]
I think you'll find that is out of scope for this project.
This is about implementing d3d9 - d3d11 through Vulkan to be able to play Winodws games on Linux.

**Comment by goofyseeker311** [comment]
well x86/arm to vulkan translation layer, but just an idea, if not inside this project, take it or leave it

**Comment by K0bin** [comment]
There's a reason why the GPU and CPU are distinct devices. They don't work the same and they have different strengths and weaknesses. What you're proposing is impossible and even if it wasn't, it would be a bad idea because GPUs are very slow at the type of work that CPUs do.

**Comment by goofyseeker311** [comment]
of course its possible, try threadripper

**Comment by K0bin** [comment]
That does that have to do with anything? Threadrippers are CPUs with a lot of cores. That's not the same as a GPU.

**Comment by goofyseeker311** [comment]
programming a gpu is like avx-512 instructions, or more like avx-20480 instructions

**Comment by doitsujin** [comment]
and what exactly does this have to do with D3D11->VK translation? Exactly, **nothing**.
