### ISSUE TITLE
Plants VS Zombies Battle For neighborvile DirectX Error

### ISSUE THREAD

**Issue by NeedsArt** [doitsujin/dxvk#3021]
here is the log as the file is too big for github https://drive.google.com/file/d/1DZxasQq2vC8c48aIQ_qNnLbHRjz8dPUi/view?usp=share_link 

used launch settings = PROTON_NO_ESYNC=1 PROTON_USE_WINED3D=1 %command%

Tested all Wine/Proton Versions Ie Proton Experimental + 7.0-4

Linux Mint 20.3 Cinnamon

Kernel 5.4.0-128-generic

NVIDIA Corporation Device 2482 or 3070ti

Driver Version =  nvidia-driver-520 Version 520.56.06-0ubuntu0.20.04.1 NVIDIA driver metapackage

Api = D3D11 DXGI

![Screenshot from 2022-10-28 12-46-20](https://user-images.githubusercontent.com/89006981/199163877-2db5f02c-017a-4682-b4d3-ecf8fae783e4.png)

**Comment by Blisto91** [comment]
Hello.
When you launch with `PROTON_USE_WINED3D=1` you won't be using dxvk. Please remove that part and try again.

**Comment by NeedsArt** [comment]
Thanks for telling me that. i will keep it in mind in the future. will test again

**Comment by NeedsArt** [comment]
Wine 3D Issue
