### ISSUE TITLE
Dragon Age Origins OOM crash when alt-tabbed

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3022]
When you alt tab from fullscreen Dragon Age Origins with dxvk it appears to leak memory and will then crash shortly after.
If you alt tab out and in quickly you can find that Vidmem Heap 2 can go from below 100MiB up to ~1600MiB or more.
On master dxvk `d3d9.allowDirectBufferMapping = False` appears to work around the issue.

### Software information
Dragon Age Origins.
Fullscreen.

### System information
- GPU: R9 380
- Driver: week old mesa-git
- Wine version: WINE-GE 7-32
- DXVK version: every dxvk and d9vk version I've tried.

### Apitrace file(s)
https://mega.nz/file/x9JBGBgb#koBerUeBmvsniZI8n8N14lHcpZ1mXfIXmQyn03X2QJk

Trace is recorded with dxvk where i in the main menu alt tab and sit at desktop until it crashes.

### Log files
[DAOrigins_d3d9.log](https://github.com/doitsujin/dxvk/files/9913086/DAOrigins_d3d9.log)

**Comment by K0bin** [comment]
Once you alt tab out the game starts calling Lock(DISCARD) on three different directly mapped buffers over and over and over again.
