### ISSUE TITLE
Add FPS limit to a few wayforward games.

### ISSUE THREAD

**Issue by Bitwolfies** [doitsujin/dxvk#3024]
Shantae and the Pirate's Curse, and Mighty Switch Force! Collection are all broken when run above 60, but run at 144 by default. The exe's for the respective games are "ShantaeCurse.exe" and "MSFC.exe"

**Comment by Blisto91** [comment]
I'm guessing this is also relevant for the other few Shantae games and the individual games within the `Mighty Switch Force! Collection` ? 👀

**Comment by Bitwolfies** [comment]
> I'm guessing this is also relevant for the other few Shantae games and the individual games within the `Mighty Switch Force! Collection` ? 👀

The collection uses a single exe for all its games, so the one limiter will do. The other shantaes are surprisingly fine.

Have not tested if Mighty Switch Force Hose It Down needs a limit though.
