### ISSUE TITLE
Star Wars Jedi Fallen Order doesn't start

### ISSUE THREAD

**Issue by thepopgame2099** [doitsujin/dxvk#3026]
I put the DXVK files in the .exe library, but when i run the game, it stay like this
![imagen_2022-11-04_100558831](https://user-images.githubusercontent.com/117390126/200008282-b13086f7-2067-456a-a937-972829d58554.png)

### Software information
Star Wars Jedi Fallen order, All in epic, v-sync On, 60Hz 

### System information
- GPU: Rtx 3060 TI 
- Driver: 526.47
- Wine version: 7.20
- DXVK version: 1.10.3

### Log files
- d3d9.log:  
[starwarsjedifallenorder_d3d9.log](https://github.com/doitsujin/dxvk/files/9939628/starwarsjedifallenorder_d3d9.log)

- d3d11.log: [starwarsjedifallenorder_d3d11.log](https://github.com/doitsujin/dxvk/files/9939629/starwarsjedifallenorder_d3d11.log)

- dxgi.log: [starwarsjedifallenorder_dxgi.log](https://github.com/doitsujin/dxvk/files/9939630/starwarsjedifallenorder_dxgi.log)

**Comment by thepopgame2099** [comment]
> 

Windows

**Comment by K0bin** [comment]
Nothing we can do then. DXVK is hit or miss on Windows and we cannot fix that.

**Comment by Blisto91** [comment]
Could be a driver or overlay issue as i am not reproducing this on windows with my R9 380
Try to turn off all overlays such as Geforce Experience and EA overlay. If you have MSI afterburner and Riva statistics server then try to uninstall them as they can interfere with dxvk. Even if you dont have them open

**Comment by thepopgame2099** [comment]
> Could be a driver or overlay issue as i am not reproducing this on windows with my R9 380 Try to turn off all overlays such as Geforce Experience and EA overlay. If you have MSI afterburner and Riva statistics server then try to uninstall them as they can interfere with dxvk. Even if you dont have them open

BRO THX SO MUCH, THATS WORK, I JUST TURN OFF THE NVIDIA OVERLAY AOISHDOASHD THXXXX
