### ISSUE TITLE
Pac Man Championship edition dx Failed to create d3d device error

### ISSUE THREAD

**Issue by chaogamer** [doitsujin/dxvk#3030]
i had been getting the failed d3d device error on my game.
i soon figured out that it had something to do with the lines "warn:  DXVK: No adapters found. Please check your device filter settings and Vulkan setup." so i am here to get help

### Software information
Pac Man Championship edition DX

### System information
- GPU: Intel  UHD graphics 620
- Driver: Intel Drivers likely
- Wine version: Steam Proton Experimental
- DXVK version: v1.10.1

### Log files
- d3d9.log:
info:  Game: PAC-MAN.exe
info:  DXVK: v1.10.1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  Skipping Vulkan 1.2 adapter: Intel(R) UHD Graphics 620 (WHL GT2)
warn:  Skipping Vulkan 1.1 adapter: llvmpipe (LLVM 12.0.0, 256 bits)
warn:  DXVK: No adapters found. Please check your device filter settings and Vulkan setup.
info:  Process set as DPI aware

**Comment by Blisto91** [comment]
Hello.
Proton experimental which uses dxvk master have some months ago bumped the minimum driver requirments.
So you'll need to have at least anv (mesa) 22.0 to be able to use experimental/dxvk master.

**Comment by K0bin** [comment]
What Blisto said. DXVK requires Vulkan 1.3 support and the driver on your system does not support that.
