### ISSUE TITLE
The Witcher 3 wont open (Windows 10 - GTX1660Ti)

### ISSUE THREAD

**Issue by danilomrx0** [doitsujin/dxvk#3034]
I have tested two DXVK versions, 1.10 and 1.10.3 and the game simply wont open (I open the game through steam, the title gets green, but nothing more happens.)

**Comment by Blisto91** [comment]
Please fill out the issue template with logs and all

**Comment by doitsujin** [comment]
The game has been working fine for four years at this point so yeah, setup issue of sorts.

**Comment by danilomrx0** [comment]
> Please fill out the issue template with logs and all
> 
> Also note that this game is known to work on Linux so there's probably some Windows or setup issue. Maybe driver.

Sorry, I've never done this, where is this template for me to fill?

I am running the latest driver for my card (522.25). I've tried using an older one (471.68) that I saw a guy using in a Youtube video doing benchmark of this same game and the game launches, I could open my save, but the game was running at about 5fps and it crashes in 20 seconds or so.

If you don't support Windows at all, I do understand and I apologize.

**Comment by Blisto91** [comment]
No worries. 🙂 
The issue template is the text that should appear in your text field when you make a new issue, tho it is also possible to select blank ofc.

Next to the exe of the game or in the games root folder you should find a couple of logs including the words d3d11 and dxgi. Post them here.

One thing to try is latest master as alot of changes have happened since 1.10.3. You can find a download here https://github.com/doitsujin/dxvk/actions/runs/3414979655
If the above doesn't work i would also like you to try and disable any game overlays which might be running since they can sometimes break when running together with dxvk. Stuff such as Geforce Experience Overlay and any game launchers (steam, gog galaxy etc)
If you have RivaTuner Statistics Server overlay installed then also try to shut that off or even uninstall. It has a vulkan layer implementation and can interfere even when the program itself isn't running.
The general Windows notes can be found here https://github.com/doitsujin/dxvk/wiki/Windows

**Comment by danilomrx0** [comment]
### Software information
Name of the game, settings used etc.

### System information
- GPU: GTX 1060Ti
- Driver: 536.61
- Wine version: - - 
- DXVK version: 1.10.3 and "dxvk-master-ecc230238913d2599db276573d7590ed4a898524"

### Apitrace file(s)
- I was not able to use it. No trace files were created

### Log files
- dxvk - 1.10.3 - 
[dxvk-1.10.3 logs.zip](https://github.com/doitsujin/dxvk/files/9965897/dxvk-1.10.3.logs.zip)

- dxvk-master-ecc230238913d2599db276573d7590ed4a898524 - 
[dxvk-master-ecc230238913d2599db276573d7590ed4a898524 logs.zip](https://github.com/doitsujin/dxvk/files/9965898/dxvk-master-ecc230238913d2599db276573d7590ed4a898524.logs.zip)

MSI Afterburner and RTSS were closed. Steam overlay was disabled too. I don't use GeForce Experience, I only install drivers using NVCleanstall (Only driver and Phys).

With both versions the game won't open, it only shows up in green on Steam and stay that way untill I shut it off (through Steam or task manager).

Both DXVK versions were used in GTA4 without problems (as a comparison basis).

**Comment by courrier1** [comment]
Same problem here, 

### System information
- Windows: 10 (64bit)
- GPU: GTX 970
- Driver: 526.47
- Wine version: -
- DXVK version: 2.0

**Comment by doitsujin** [comment]
https://github.com/doitsujin/dxvk/wiki/Windows

**Comment by Blisto91** [comment]
Also note if you have RTSS installed it can still cause shenanigans even when it's closed. So it's better to uninstall when testing that

**Comment by danilomrx0** [comment]
> https://github.com/doitsujin/dxvk/wiki/Windows
> 
> fwiw this might just not work for you on Windows because of the game's Ansel intergration or something. Again, the game works fine in general, there's no bug we can fix.

I hate Ansel.

@Blisto91 I understand that RTSS may cause issue, but I use MSI Afterburner and RTSS to undervolt and monitor my GPU all the time.

I thank you guys for trying to help. this mod is a incredible and I will try it on all the games I can!

Not much more to add here, for me the issue can be closed.

**Comment by courrier1** [comment]
> Also note if you have RTSS installed it can still cause shenanigans even when it's closed. So it's better to uninstall when testing that

I have it fully uninstalled and still not working.

> there's no bug we can fix.

I agree. 
I wanted to add a small detail, I tried using an old version "0.96" and the game shows a black screen then it is terminated and a .crachinfo file is created, while with the recent versions the witcher3.exe just process keeps running in the background.

**Comment by t0b118** [comment]
I can confirm that after reading here and doitsujin mentioning, disabling Ansel made the game run again with DXVK 2.0 on windows 10, I disabled it using nvidiaInspector.

**Comment by courrier1** [comment]
> I can confirm that after reading here and doitsujin mentioning, disabling Ansel made the game run again with DXVK 2.0 on windows 10, I disabled it using nvidiaInspector.

It is working now, thank you! And the software is NvidiaProfileInspector.

**Comment by danilomrx0** [comment]
> > I can confirm that after reading here and doitsujin mentioning, disabling Ansel made the game run again with DXVK 2.0 on windows 10, I disabled it using nvidiaInspector.
> 
> It is working now, thank you! And the software is NvidiaProfileInspector.

I have absolutely forgotten about NVIDIA Inspector. I´ve used it to disable Ansel and it worked! It helped a bit with the stutters, as expected.
