### ISSUE TITLE
[d3d9] Sonic & Sega All-Stars Racing Transformed Collection: performs poorly when Risezable BAR is enabled

### ISSUE THREAD

**Issue by ranplayer** [doitsujin/dxvk#3038]
This old game performs poorly (inconsistent fps, and huge drops) when Resizable BAR is enabled on the BIOS (not a DXVK bug, since it's the same for Windows). I was just wondering if there is a possible workaround on the DXVK's side. This feature does improve performance in newer games, and it would be nice to keep it enable on the system. I've tried setting `RADV_PERFTEST=nosam`, but no success. Is there any DXVK's property that I could try ?

### Software information
Name: Sonic & Sega All-Stars Racing Transformed_Collection
SteamId: 212480

### System information
- GPU: RX 6700 XT 12 Gb
- Driver: Mesa 22.2.2
- Wine version: Proton 7.0-4 / 7.0-5 (Experimental)
- DXVK version: 1.10.3 and latest changes from master

### Log files
- [d3d9_resizable_bar.log](https://github.com/doitsujin/dxvk/files/9961661/ASN_App_PcDx9_Final_d3d9-resizable-bar.log)
- [d3d9_no_resizable_bar.log](https://github.com/doitsujin/dxvk/files/9961663/ASN_App_PcDx9_Final_d3d9-no-resizable-bar.log)

**Comment by doitsujin** [comment]
For context, this is usually caused by games reading from memory that's only supposed to be written to, and sadly not uncommon at all. Like Josh said, `d3d9.apitraceMode = True` in dxvk.conf (see https://github.com/doitsujin/dxvk/wiki/Configuration) should help.

**Comment by ranplayer** [comment]
Thanks for the explanation, folks. That property did trick ! It's running smoothly now with Resizable BAR enabled.

**Comment by Blisto91** [comment]
@ranplayer Can you test if it has the same effect when you instead add `d3d9.allowDirectBufferMapping = False`
Use it with proton experimental.

**Comment by ranplayer** [comment]
@Blisto91 , this property helps a little, but the apitrace mode provides a solid and consistent performance.

**Comment by Blisto91** [comment]
Just noting here that https://github.com/doitsujin/dxvk/pull/3039 might be a temporary workaround until the devs have looked into the issue more
