### ISSUE TITLE
compiling doesn't work 

### ISSUE THREAD

**Issue by Lan3boy** [doitsujin/dxvk#3043]
<root@dxvk>#:meson --cross-file build-win64.txt --buildtype release --prefix /your/dxvk/directory build.w64
`The Meson build system
Version: 0.63.3
Source dir: /home/jetson/dxvk
Build dir: /home/jetson/dxvk/build.w64
Build type: cross build
Project name: dxvk
Project version: v1.10.1
C compiler for the host machine: x86_64-w64-mingw32-gcc (gcc 12.2.0 "x86_64-w64-mingw32-gcc (GCC) 12.2.0")
C linker for the host machine: x86_64-w64-mingw32-gcc ld.bfd 2.38
C++ compiler for the host machine: x86_64-w64-mingw32-g++ (gcc 12.2.0 "x86_64-w64-mingw32-g++ (GCC) 12.2.0")
C++ linker for the host machine: x86_64-w64-mingw32-g++ ld.bfd 2.38
C compiler for the build machine: cc (gcc 12.2.0 "cc (GCC) 12.2.0")
C linker for the build machine: cc ld.bfd 2.39.0
C++ compiler for the build machine: c++ (gcc 12.2.0 "c++ (GCC) 12.2.0")
C++ linker for the build machine: c++ ld.bfd 2.39.0
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Library d3d9 found: YES
Library d3d11 found: YES
Library dxgi found: YES
Library d3dcompiler_47 found: YES
Program x86_64-w64-mingw32-windres found: YES
Compiler for C++ supports arguments -msse: YES 
Compiler for C++ supports arguments -msse2: YES 
Compiler for C++ supports arguments -msse3: YES 
Compiler for C++ supports arguments -mfpmath=sse: YES 
Compiler for C++ supports arguments -Wimplicit-fallthrough: YES 
Compiler for C++ supports arguments -Wno-missing-field-initializers: YES 
Compiler for C++ supports arguments -Wno-unused-parameter: YES 
Compiler for C++ supports arguments -Wno-cast-function-type: YES 
Compiler for C++ supports arguments -Wno-unused-private-field: NO 
Compiler for C++ supports arguments -Wno-microsoft-exception-spec: NO 
Compiler for C++ supports arguments -Wno-extern-c-compat: NO 
Compiler for C++ supports arguments -Wno-unused-const-variable: YES 
Compiler for C++ supports arguments -Wno-missing-braces: YES 
Compiler for C++ supports arguments -DNOMINMAX: YES 
Compiler for C++ supports arguments -D_WIN32_WINNT=0xa00: YES 
Compiler for C++ supports arguments -DDXVK_WSI_WIN32: YES 
Compiler for C supports arguments -msse: YES 
Compiler for C supports arguments -msse2: YES 
Compiler for C supports arguments -msse3: YES 
Compiler for C supports arguments -mfpmath=sse: YES 
Compiler for C supports arguments -Wimplicit-fallthrough: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -Wno-cast-function-type: YES 
Compiler for C supports arguments -Wno-unused-private-field: NO 
Compiler for C supports arguments -Wno-microsoft-exception-spec: NO 
Compiler for C supports arguments -Wno-extern-c-compat: NO 
Compiler for C supports arguments -Wno-unused-const-variable: YES 
Compiler for C supports arguments -Wno-missing-braces: YES 
Compiler for C supports arguments -DNOMINMAX: YES 
Compiler for C supports arguments -D_WIN32_WINNT=0xa00: YES 
Compiler for C supports arguments -DDXVK_WSI_WIN32: YES 
Compiler for C++ supports link arguments -static: YES 
Compiler for C++ supports link arguments -static-libgcc: YES 
Compiler for C++ supports link arguments -static-libstdc++: YES 
Compiler for C++ supports link arguments -Wl,--file-alignment=4096: YES 
Compiler for C supports link arguments -static: YES 
Compiler for C supports link arguments -static-libgcc: YES 
Compiler for C supports link arguments -static-libstdc++: YES 
Compiler for C supports link arguments -Wl,--file-alignment=4096: YES 
Program glslangValidator found: YES (/usr/bin/glslangValidator)
Run-time dependency threads found: YES
Dependency threads found: YES unknown (cached)
Build targets in project: 12

dxvk v1.10.1

  User defined options
    Cross files: build-win64.txt
    buildtype  : release
    prefix     : /your/dxvk/directory

`Found ninja-1.11.1 at /usr/bin/ninja 
<root@dxvk>#:ninja install
ninja: error: loading 'build.ninja': No such file or directory
<root@dxvk>#:ls
build.w64	 dxvk.conf  meson.build        package-release.sh  setup_dxvk.sh  VP_DXVK_requirements.json
build-win32.txt  include    meson_options.txt  README.md	   src
build-win64.txt  LICENSE    package-native.sh  RELEASE		   version.h.in
<root@dxvk>#:cd build.w64
<root@build.w64>#:ninja install
[2/278] Compiling C++ object src/wsi/libwsi.a.p/win32_wsi_window_win32.cpp.obj

FAILED: src/wsi/libwsi.a.p/win32_wsi_window_win32.cpp.obj 

x86_64-w64-mingw32-g++ 

-Isrc/wsi/libwsi.a.p -Isrc/wsi -I../src/wsi -I../include -I../include/vulkan/include -I../include

/spirv/include -fdiagnostics-color=always 

-D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 

-O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-

initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable 

-Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 

-MD -MQ src/wsi/libwsi.a.p/win32_wsi_window_win32.cpp.obj -MF src/wsi/libwsi.a.p

/win32_wsi_window_win32.cpp.obj.d -o src/wsi/libwsi.a.p

/win32_wsi_window_win32.cpp.obj -c ../src/wsi/win32/wsi_window_win32.cpp

In file included from ../src/wsi/win32/../wsi_window.h:8,

                 from ../src/wsi/win32/wsi_window_win32.cpp:1:

../src/wsi/win32/../../vulkan/vulkan_loader.h:7:10: fatal error: vulkan/vulkan.h: No such file or directory

    7 | #include <vulkan/vulkan.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

[11/278] Compiling C++ object src/util/libutil.a.p/util_shared_res.cpp.obj
ninja: build stopped: subcommand failed. 

I haven't found anything else that solves this problem

**Comment by DadSchoorse** [comment]
Did you clone the sub modules? Otherwise `git submodule update --init --recursive` might help.

**Comment by ViNi-Arco** [comment]
>[root@dxvk](mailto:root@dxvk)#:meson --cross-file build->win64.txt --buildtype release --prefix /your/dxvk/directory >build.w64
>
> User defined options
> Cross files: build-win64.txt
> buildtype : release
> prefix : /your/dxvk/directory

Sup Lan3boy,
You entered the wrong directory, the correct one would be:
`meson --cross-file build-win64.txt --buildtype release --prefix /home/jetson/dxvk build.w64`

Aren't you going to pass any different FLAGs?
Then there is no reason to compile on your own, [here](https://github.com/doitsujin/dxvk/actions) is always the latest commit.

**Comment by Blisto91** [comment]
@Lan3boy Friendly ping
