### ISSUE TITLE
[DX9] WHQL regression in Lost Devices - Resource Management DX9.L

### ISSUE THREAD

**Issue by adamjer** [doitsujin/dxvk#3044]
### Software information
WHQL Microsoft Conformance Tests
CMD you need to apply
lostdev.exe -dx9 -!losttexture -M:1 -dx9 -whql -logclean
lostdev.exe -dx9.1 -M:1 -dx9 -whql -logclean

### Regression point
https://github.com/doitsujin/dxvk/commit/9c22a585434ace22072e9014aa99098af4894caa

### Platform
11th Gen Intel(R) Core(TM) i7-1180G7 @ 1.30GHz

### Test binaries
~~Lost Devices.zip~~ [redacted]

**Comment by doitsujin** [comment]
It's not clear to me what the test is actually trying to test and what it is that DXVK is actually doing wrong.

Also please note that fixing real-world games has a higher priority for us than conformance tests that we *don't have access to* for obvious reasons, and blindly fixing these tests is likely to introduce regressions elsewhere.

**Comment by K0bin** [comment]
The docs say that locking D3DPOOL_DEFAULT textures isn't allowed and a quick test on the Nvidia D3D9 driver has verified this. So this is also what we implement.

Sonic Generations basically relies on this to run well. (See #3009)

If you have access to a spec or any other kind of more detailed documentation on how this is exactly supposed to work, then please either share it (if you're allowed to) or submit a fix.

**Comment by K0bin** [comment]
Please check whether #3045 fixes it.
