### ISSUE TITLE
Release 2.0: missing files in source code archive (.zip/.tar.gz)

### ISSUE THREAD

**Issue by tjkl1** [doitsujin/dxvk#3048]
While building dxvk 2.0, files below ./include/{spirv,vulkan} are expected. Yet the files from the submodules are missing in the archive, thus dxvk cannot be build from the archives:

> [    6s] C++ linker for the build machine: c++ ld.bfd 2.39.0.20220810-1
>[    6s] Build machine cpu family: x86_64
>[    6s] Build machine cpu: x86_64
>[    6s] Host machine cpu family: x86_64
>[    6s] Host machine cpu: x86_64
>[    6s] Target machine cpu family: x86_64
>[    6s] Target machine cpu: x86_64
>[    6s] Library d3d9 found: YES
>[    6s] Library d3d11 found: YES
>[    6s] Library dxgi found: YES
>[    6s] Library d3dcompiler_47 found: YES
>[    6s] Program x86_64-w64-mingw32-windres found: YES
>[    6s] 
>[    6s] meson.build:124:0: ERROR: Include dir ./include/vulkan/include does not exist.

**Comment by DadSchoorse** [comment]
Those archives are generated by github.

**Comment by doitsujin** [comment]
Yeah, doesn't look like there's anything we can do about that.

Apparently people have been complaining about that for [almost 7 years](https://stackoverflow.com/questions/34719785/how-to-add-submodule-files-to-a-github-release) at this point.

**Comment by tjkl1** [comment]
Worked up until this release, but i didn't check if those folders were in submodules before 2.0 or not.

**Comment by K0bin** [comment]
DXVK didn't use submodules before 2.0.

**Comment by eli-schwartz** [comment]
I really don't think this bug report has anything to do with what github may or may not do. The more general question is "maybe the project should provide release tarballs".

It's very easy to do that, you can just run `meson dist --no-tests` and upload the resulting `meson-dist/*.tar.xz` file. This will include submodules.

**Comment by ILoveAlgorythms** [comment]
So, how to fix that?

**Comment by K0bin** [comment]
Clone the repo and run `git submodule update --init --recursive`
