### ISSUE TITLE
Cyberpunk crashes on the Cyberpunk logo after launching the game

### ISSUE THREAD

**Issue by Zeioth** [doitsujin/dxvk#3050]
Cyberpunk crashes 3 seconds after launching the game (during the cyberpunk logo). I'm almost certain this is a game bug and not DXVK's fault, as one week ago I was able to play the game perfectly well. But just to be sure:

### Software information
* Cyberpunk
* No special args passed, just PROTON_LOG

### System information
- GPU: 6700XT
- Driver:  Mesa  22.2.3-1
- Wine version:  Proton experimental.
- DXVK version: v1.10.3 (most likely)

### PROTON_LOG
[steam-1091500.log](https://github.com/doitsujin/dxvk/files/9991635/steam-1091500.log)

### Apitrace file(s)
- WIP

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by mbriar** [comment]
Also maybe try without vkbasalt and weird env vars you might be setting like vk_x11_override_min_image_count.

**Comment by K0bin** [comment]
That's a good point. @Zeioth please try that.

**Comment by Zeioth** [comment]
As stated in the description:

"No special args passed, just PROTON_LOG"

**Comment by Zeioth** [comment]
Hey I isolated the issue. I tried AMDVLK for the first time ever, and that fixed the issue. I can reproduce the issue consistently.

On my 6700RX, the game runs fine with AMD_VULKAN_ICD=AMDVLK but it crashes with AMD_VULKAN_ICD=RADV. Reporting to mesa.
