### ISSUE TITLE
Despite using the command to set the GPU, DXVK uses the wrong GPU until I physically disable it in Device manager.

### ISSUE THREAD

**Issue by cpufreak** [doitsujin/dxvk#3052]
Hello! so I'm not sure what all I should include here as I was having a low FPS issue, which I traced back to the game (Euro Truck sim 2) using the wrong GPU (a display adapter for a secondary screen) despite using DXVK_FILTER_DEVICE_NAME="Device" which in this case is an Intel Arc A770. it will use the 770 if I disable the display adapter card (GT1010) in Device manager, but with it enabled it won't use the arc card at all. am I doing something wrong?

**Comment by Blisto91** [comment]
Where are you using the env var and what platform and service are you playing through.
Post a dxvk log if you can.

**Comment by cpufreak** [comment]
> Where are you using the env var and what platform and service are you playing through. Post a dxvk log if you can.

platform is Windows, and I'm using it through the steam launch options.

which log would you like? the one with the display adapter enabled or disabled?

**Comment by Blisto91** [comment]
I don't think you can set environment variables through steam launch options on Windows. It's a Linux only feature afaik. So you'll have to set it through the Windows environment variables window

**Comment by K0bin** [comment]
> DXVK_FILTER_DEVICE_NAME="Device"

Just to rule that out, you did replace "Device" with the name of your GPU, right?

**Comment by cpufreak** [comment]
> > DXVK_FILTER_DEVICE_NAME="Device"
> 
> Just to rule that out, you did replace "Device" with the name of your GPU, right?

yes

**Comment by cpufreak** [comment]
> I don't think you can set environment variables through steam launch options on Windows. It's a Linux only feature afaik. So you'll have to set it through the Windows environment variables window

and this may explain it, lemme give it a try

**Comment by Blisto91** [comment]
https://www.makeuseof.com/how-to-use-environment-variables-in-windows-10/

**Comment by Blisto91** [comment]
Don't add quotation marks when setting the value through the GUI on Windows

**Comment by Joshua-Ashton** [comment]
Steam doesn't support env vars on Windows.
