### ISSUE TITLE
sleeping dogs definitive edition startup crash fix

### ISSUE THREAD

**Issue by RICKY-1122** [doitsujin/dxvk#3055]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Name of the game, settings used etc.

### System information
- GPU:
- Driver:
- Wine version: 
- DXVK version: 

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by Blisto91** [comment]
I think you forgot to fill out the template 🙂

**Comment by doitsujin** [comment]
Game is known to work: https://www.protondb.com/app/307690

Closing since there's nothing actionable here.
