### ISSUE TITLE
RTSS overlay not visible

### ISSUE THREAD

**Issue by abi-21** [doitsujin/dxvk#3056]
Using Windows 10. In previous versions rivatuner overlay was working but in 2.0 it's not showing anything.

**Comment by K0bin** [comment]
RivaTuner needs to be updated to support Vulkan 1.3

**Comment by abi-21** [comment]
Workaround found by reddit user [jaKz9](https://www.reddit.com/user/jaKz9) in [here](https://www.reddit.com/r/pcgaming/comments/yyfy4w/if_anyone_is_having_issues_with_dxvk_20_and_rtss/).
In RivaTuner, set Application Detection Level to High and it will work.

**Comment by Ryusennin** [comment]
No need for workarounds, the latest RTSS betas have been compatible with Vulkan 1.3 for quite some time.
