### ISSUE TITLE
Supreme Commander: Forged Alliance crash after loading screen

### ISSUE THREAD

**Issue by iczero** [doitsujin/dxvk#3058]
The game crashes immediately after the loading screen (appears to be segmentation fault) on dxvk 2.0. dxvk 1.10.3 does not have this issue.

I did a `git bisect` and the commit https://github.com/doitsujin/dxvk/commit/d8933ca175aac5598cc6abf3ea5384553c5f01b4 appears to be the issue. Reverting this commit on latest master (8f8a93696d36adca8efeed4e16dc6b3deea27268) fixes the issue. 

Unfortunately I can't seem to get any debugger to actually work.

### Software information
Supreme Commander: Forged Alliance (Steam appid 9420 and FAF versions both crash)
Graphics API: d3d9

### System information
- GPU: Intel i7-12700h integrated graphics (ADL GT2)
- Driver: Mesa 22.1.7 (`iris`), kernel 6.1.0-rc3+
- Wine version: Proton Experimental (`wine-7.0`)
- DXVK version: 2.0

### Apitrace files
Apitrace hangs on both dxvk and wined3d. Not sure how to obtain.

### Log files
- d3d9.log: [ForgedAlliance_d3d9.log](https://github.com/doitsujin/dxvk/files/9996477/ForgedAlliance_d3d9.log)

**Comment by Blisto91** [comment]
Arg feck 😢

**Comment by Blisto91** [comment]
Can confirm.
Thanks for the report.

**Comment by Blisto91** [comment]
@iczero If you want to use a prebuilt version with the fix before a dxvk release is out then you can use the CI artifacts from here https://github.com/doitsujin/dxvk/actions/runs/3504484566
It should stay up for 3 months
