### ISSUE TITLE
[d3d9] Black Mesa lighting breaks on Intel, but is fixed with AMD vendor ID

### ISSUE THREAD

**Issue by TacoDeBoss** [doitsujin/dxvk#3061]
### Software information
Black Mesa (362890)

### System information
- GPU: Intel Corporation DG2 [Arc A380] (rev 05)
- Driver: Mesa 22.2.3
- Wine version: Proton Experimental
- DXVK version: 2.0

### Screenshots
d3d9.customVendorId = 8086
![](https://i.imgur.com/3BhgYso.png)

d3d9.customVendorId = 1002
![](https://i.imgur.com/Ah472de.png)

**Comment by Blisto91** [comment]
Quick note that this even happens when you on Windows spoof the vendor id to Intel without dxvk.
This was tested on a AMD R9 380 so dunno if anything is actually different with Intels own d3d9 driver.

**Comment by Evernow** [comment]
> Quick note that this even happens when you on Windows spoof the vendor id to Intel without dxvk. This was tested on a AMD R9 380 so dunno if anything is actually different with Intels own d3d9 driver.

Apologies, but from this wording you're saying on Windows it is possible to spoof the vendor id to something else without DXVK, how is this possible?

**Comment by Blisto91** [comment]
> Apologies, but from this wording you're saying on Windows it is possible to spoof the vendor id to something else without DXVK, how is this possible?

https://www.pcgamingwiki.com/wiki/Black_Mesa#Flashlight_not_working_on_Intel_GPU
It's a launch argument for Black Mesa
