### ISSUE TITLE
DXVK 2.0 broke Debian 11 compatibility due to Vulkan 1.3 dependency

### ISSUE THREAD

**Issue by SSUPII** [doitsujin/dxvk#3062]
### Software information
Debian 11 Bullseye (Stable)

### System information
- GPU: NVIDIA GTX 1050 / Intel UHD Graphics 630
- Driver: Proprietary NVIDIA 470.141.03 / Mesa 20.3.5
- Wine version:  N/A
- DXVK version: 2.0

```
warn:  Skipping Vulkan 1.2 adapter: NVIDIA GeForce GTX 1050
warn:  Skipping Vulkan 1.2 adapter: Intel(R) UHD Graphics 630 (CFL GT2)
warn:  Skipping Vulkan 1.0 adapter: llvmpipe (LLVM 11.0.1, 256 bits)
warn:  DXVK: No adapters found. Please check your device filter settings and Vulkan setup.
```

By default Debian 11 Bullseye has no video drivers support for Vulkan 1.3 (while having the library as a backport), rendering the new version of DXVK unusable. Drivers with Vulkan 1.3 support are under unstable branches.

A backport of a newer Nvidia driver version is currently being discussed here: https://forums.debian.net/viewtopic.php?p=762377

**Comment by Iglu47** [comment]
sorry, what exactly is the DXVK problem here?
if Debian keeps obsolete Vulkan/driver packages what is the reason for not doing it for DXVK also in the same way?

**Comment by Redundanz** [comment]
> DXVK 2.0 broke Debian 11 compatibility

gave me the chuckles

**Comment by Blisto91** [comment]
@SSUPII Yes dxvk 2.0 raised the driver requirements to 510 and mesa 22.0 for Nvidia and amd/Intel respectively.
The 1.10.3 version is still backwards compatible and should in general work for most games 🙂

**Comment by SSUPII** [comment]
> > DXVK 2.0 broke Debian 11 compatibility
> 
> gave me the chuckles

Yeah. I love my system yet I wish some packages got slightly more frequent updates.

**Comment by SSUPII** [comment]
> @SSUPII Yes dxvk 2.0 raised the driver requirements to 510 and mesa 22.0 for Nvidia and amd/Intel respectively.
> The 1.10.3 version is still backwards compatible and should in general work for most games 🙂 

I can confirm the previous version does work wonderfully. I will give an hand in backporting 510/510 on the linked forums once I give my current exams.

**Comment by SSUPII** [comment]
> > @SSUPII Yes dxvk 2.0 raised the driver requirements to 510 and mesa 22.0 for Nvidia and amd/Intel respectively.
> > The 1.10.3 version is still backwards compatible and should in general work for most games 🙂 
> 
> I can confirm the previous version does work wonderfully. I will give an hand in backporting 510/510 on the linked forums once I give my current exams. ^.^

**Comment by K0bin** [comment]
There isn't really anything for us to do here.

The release notes are perfectly clear about the driver requirements and if users decide to go with a slow moving distro like Debian, they should also stick with older DXVK versions until the required drivers are available.

**Comment by kolAflash** [comment]
It's actually broken on every Linux distro from before 2022.  
The needed Vulkan-Loader-1.3 was released in February 2022: https://github.com/KhronosGroup/Vulkan-Loader/tags?after=v1.3.205
