### ISSUE TITLE
[d3d9-native] Counter Strike: Global Offensive, Danger Zone edges are not rendered.

### ISSUE THREAD

**Issue by alou-S** [doitsujin/dxvk#3064]
The red zone or the danger zone edges are not being rendered when using dxvk on CS;GO. I have also tested with the latest 2.0 build of dxvk-native.

### Software information
Counter Strike: Global Offensive 
### System information
- GPU: Radeon 6600M (but seems to be GPU agnostic) 
- DXVK version: 2.0 (CS:GO by default uses 1.9)

More information is available on : https://github.com/ValveSoftware/csgo-osx-linux/issues/2897

Thought of moving this here since native has been mainlined here.

**Comment by alou-S** [comment]
> Seems fine when running the Windows version via Proton.
Seems like a issue with either CS:GO Linux or the dxvk-native then :thinking:

**Comment by K0bin** [comment]
DXVK Native 2.0 uses the exact same code. So if it doesn't work with DXVK Native 2.0 and it works in the Windows version with DXVK 2.0, we're looking at a bug in the Linux port.

**Comment by alou-S** [comment]
But again it works find on Valve's own Translation layer ToGL and both ToGL and dxvk-native seem to use the same so called "d3d9 device" in CS:GO Linux. Probably a problem that can be fixed from either side.

**Comment by Blisto91** [comment]
I think K0bin means that there is probably some game code in the Linux version that might be causing the issue when vulkan is selected.
fwiw you are not alone in thinking that the native version is kinda bleh.

**Comment by project22329** [comment]
This is a pretty annoying bug and is a big disadvantage for those who are experiencing in.

This issue might have to do with your machine having two GPUs and CSGO not being able to deal with that. My laptop has "Intel Iris Xe Graphics" and an "NVIDIA GeForce RTX 3070", everything is fully updated and latest drivers. Once I disable the Intel drive and launch CSGO, I am able to see the red zone. However, there are other displays issues present in Competitive mode when Intel Iris Xe Graphics is disabled, but works fine when re-enabled.

**Comment by K0bin** [comment]
The CSGO developers need to fix this, we can't.
