### ISSUE TITLE
[DX9] WHQL regression in "Get DC"

### ISSUE THREAD

**Issue by adamjer** [doitsujin/dxvk#3066]
Software information
WHQL Microsoft Conformance Tests
CMD you need to apply
getdc.exe -M:1 -dx9 -whql -logclean

Regression point
https://github.com/doitsujin/dxvk/commit/bc31ebe1518ef7d68bbd87417334abd828085c01

Platform
11th Gen Intel(R) Core(TM) i7-1180G7 @ 1.30GHz

Test binaries
~~Get DC.zip~~ [redacted]

**Comment by K0bin** [comment]
If that particular commit regressed something, that's likely an issue with your Vulkan driver.

**Comment by Joshua-Ashton** [comment]
Hello! Thank you for testing against DXVK, but I don't really feel comfortable with you sharing Microsoft WHQL test binaries here.

We don't reverse engineer anything Windows/DX/Microsoft or use any leaked/etc code/tests for the project.

Maybe it's completely fine and you got permission for this, but until there is something in writing I have removed the link.

I just wouldn't want it to taint anyone here or the project.
