### ISSUE TITLE
Star Citizen hangs if ran with any DXVK version.

### ISSUE THREAD

**Issue by arabcian** [doitsujin/dxvk#3067]
Hi im having problems with star citizen that the game runs without DXVK but doesnt work when any version of DXVK is used.

Ryzen 5800H RTX, 3060 Mobile, Gentoo Linux Kernel 6.0.7, Glibc-2.36-r5, Nvidia-drivers-525.53

Please tell me which logs are needed.

**Comment by Blisto91** [comment]
dxgi and d3d11 logs which are usually located next to the games exe or in the games root folder

**Comment by doitsujin** [comment]
Game is known to work fine at least with the various 1.10 releases for other people at least on Linux, so there's that.

**Comment by arabcian** [comment]
Oh i havent tried 1.10 thinking it wouldnt run. Ill try it tomorrow and report here.

**Comment by doitsujin** [comment]
well what i#m saying is that it's likely one of the numerous [Windows problems](https://github.com/doitsujin/dxvk/wiki/Windows) that prevent a large number of mostly D3D11 games from working.

**Comment by eaglemmoomin** [comment]
I've been running it for years. You might want to read through the resources here https://github.com/starcitizen-lug

**Comment by arabcian** [comment]
Tried it, got different symptoms with different DXVK and Wine versions. There is no dxgi.log in the game prefix at least i couldnt find it. Only d3d9.log


[StarCitizen_Launcher_d3d9.log](https://github.com/doitsujin/dxvk/files/10009895/StarCitizen_Launcher_d3d9.log)

**Comment by arabcian** [comment]
> Tried it, got different symptoms with different DXVK and Wine versions. Game didnt work. Worked till games loading screen without dxvk and hang. There is no dxgi.log in the game prefix at least i couldnt find it. Only d3d9.log. I wonder if this is related to Gentoo or RTX 3060 Mobile. Gives different errors with different wine and dxvk configurations.
> 
> [StarCitizen_Launcher_d3d9.log](https://github.com/doitsujin/dxvk/files/10009895/StarCitizen_Launcher_d3d9.log) [Game.log](https://github.com/doitsujin/dxvk/files/10009949/Game.log) [lutris.log](https://github.com/doitsujin/dxvk/files/10009972/lutris.log) [lutris2.log](https://github.com/doitsujin/dxvk/files/10009985/lutris2.log) [lutris3.log](https://github.com/doitsujin/dxvk/files/10009999/lutris3.log)

Ive changed 525 driver with nvidia-drivers-515.49.24 there is some advancement, now it hangs on loading screen just after we start the game and join the server. So this is not related to DXVK at all. Ill try different configurations from Lutris with every single Nvidia driver in the repo thank you for your help and thread can be closed.
