### ISSUE TITLE
Error Compiling in Ubuntu 22.04 

### ISSUE THREAD

**Issue by G2a1c2e5l1A** [doitsujin/dxvk#3074]
Hello,
I installed all dependencies and also checked the vulkan drivers status.

After getting  ‘std::cv_status’ error, I applied 
update-alternatives --config x86_64-w64-mingw32-gcc
update-alternatives --config x86_64-w64-mingw32-g++
update-alternatives --config i686-w64-mingw32-gcc
update-alternatives --config i686-w64-mingw32-g++

And it was fixed as described on the troubleshootings section.

However I'm still getting the following errors:

`[165/278] Compiling C++ object src/d3d11/d3d11.dll.p/d3d11_annotation.cpp.obj
FAILED: src/d3d11/d3d11.dll.p/d3d11_annotation.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/d3d11/d3d11.dll.p -Isrc/d3d11 -I../src/d3d11 -I../include -I../include/vulkan/include -I../include/spirv/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/d3d11/d3d11.dll.p/d3d11_annotation.cpp.obj -MF src/d3d11/d3d11.dll.p/d3d11_annotation.cpp.obj.d -o src/d3d11/d3d11.dll.p/d3d11_annotation.cpp.obj -c ../src/d3d11/d3d11_annotation.cpp
In file included from ../src/d3d11/d3d11_device.h:19,
                 from ../src/d3d11/d3d11_state_object.h:3,
                 from ../src/d3d11/d3d11_context_imm.h:8,
                 from ../src/d3d11/d3d11_annotation.cpp:3:
../src/d3d11/d3d11_features.h:84:5: error: ‘D3D11_FEATURE_DATA_D3D11_OPTIONS5’ does not name a type; did you mean ‘D3D11_FEATURE_DATA_D3D11_OPTIONS4’?
   84 |     D3D11_FEATURE_DATA_D3D11_OPTIONS5                 m_d3d11Options5               = { };
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_FEATURE_DATA_D3D11_OPTIONS4
`

What would this be about? How could I fix it?

Thanks!

**Comment by K0bin** [comment]
Your Mingw is too old.

**Comment by G2a1c2e5l1A** [comment]
> Your Mingw is too old.

Thanks K0bin, I'm going to reinstall it.

`mingw-w64/jammy,jammy,now 8.0.0-1 all [installed]
  Development environment targeting 32- and 64-bit Windows`

I installed through apt-get.

I will installed v10 from here:
[https://launchpad.net/ubuntu/+source/mingw-w64](url)

**Comment by Blisto91** [comment]
@G2a1c2e5l1A Did you solve your issue? 🙂

**Comment by shmerl** [comment]
I was hit by this after recent updates to Mingw in Debian testing.

A bunch of errors like this:

```
../source/src/vulkan/../util/log/../thread.h: In member function ‘bool dxvk::condition_variable::wait_for(std::unique_lock<dxvk::mutex>&, const std::chrono::duration<_Rep1, _Period1>&, Predicate)’:
../source/src/vulkan/../util/log/../thread.h:321:54: error: ‘std::cv_status’ has not been declared
  321 |       if (!result && wait_for(lock, timeout) == std::cv_status::no_timeout)
      |                                                      ^~~~~~~~~
```

My mingw packages:

```
dpkg --list | rg mingw
ii  binutils-mingw-w64-i686                       2.39.90.20230110-1+10.3          amd64        Cross-binutils for Win32 (x86) using MinGW-w64
ii  binutils-mingw-w64-x86-64                     2.39.90.20230110-1+10.3          amd64        Cross-binutils for Win64 (x64) using MinGW-w64
ii  g++-mingw-w64                                 12.2.0-14+25.2                   all          GNU C++ compiler for MinGW-w64
ii  g++-mingw-w64-i686                            12.2.0-14+25.2                   all          GNU C++ compiler for MinGW-w64 targeting Win32
ii  g++-mingw-w64-i686-posix                      12.2.0-14+25.2                   amd64        GNU C++ compiler for MinGW-w64, Win32/POSIX
ii  g++-mingw-w64-i686-win32                      12.2.0-14+25.2                   amd64        GNU C++ compiler for MinGW-w64, Win32/Win32
ii  g++-mingw-w64-x86-64                          12.2.0-14+25.2                   all          GNU C++ compiler for MinGW-w64 targeting Win64
ii  g++-mingw-w64-x86-64-posix                    12.2.0-14+25.2                   amd64        GNU C++ compiler for MinGW-w64, Win64/POSIX
ii  g++-mingw-w64-x86-64-win32                    12.2.0-14+25.2                   amd64        GNU C++ compiler for MinGW-w64, Win64/Win32
ii  gcc-mingw-w64                                 12.2.0-14+25.2                   all          GNU C compiler for MinGW-w64
ii  gcc-mingw-w64-base:amd64                      12.2.0-14+25.2                   amd64        GNU Compiler Collection for MinGW-w64 (base package)
ii  gcc-mingw-w64-i686                            12.2.0-14+25.2                   all          GNU C compiler for MinGW-w64 targeting Win32
ii  gcc-mingw-w64-i686-posix                      12.2.0-14+25.2                   amd64        GNU C compiler for MinGW-w64, Win32/POSIX
ii  gcc-mingw-w64-i686-posix-runtime              12.2.0-14+25.2                   amd64        GNU Compiler Collection for MinGW-w64, i686/POSIX
ii  gcc-mingw-w64-i686-win32                      12.2.0-14+25.2                   amd64        GNU C compiler for MinGW-w64, Win32/Win32
ii  gcc-mingw-w64-i686-win32-runtime              12.2.0-14+25.2                   amd64        GNU Compiler Collection for MinGW-w64, i686/Win32
ii  gcc-mingw-w64-x86-64                          12.2.0-14+25.2                   all          GNU C compiler for MinGW-w64 targeting Win64
ii  gcc-mingw-w64-x86-64-posix                    12.2.0-14+25.2                   amd64        GNU C compiler for MinGW-w64, Win64/POSIX
ii  gcc-mingw-w64-x86-64-posix-runtime            12.2.0-14+25.2                   amd64        GNU Compiler Collection for MinGW-w64, x86-64/POSIX
ii  gcc-mingw-w64-x86-64-win32                    12.2.0-14+25.2                   amd64        GNU C compiler for MinGW-w64, Win64/Win32
ii  gcc-mingw-w64-x86-64-win32-runtime            12.2.0-14+25.2                   amd64        GNU Compiler Collection for MinGW-w64, x86-64/Win32
ii  mingw-w64                                     10.0.0-3                         all          Development environment targeting 32- and 64-bit Windows
ii  mingw-w64-common                              10.0.0-3                         all          Common files for Mingw-w64
ii  mingw-w64-i686-dev                            10.0.0-3                         all          Development files for MinGW-w64 targeting Win32
ii  mingw-w64-tools                               10.0.0-3                         amd64        Development tools for 32- and 64-bit Windows
ii  mingw-w64-x86-64-dev                          10.0.0-3                         all          Development files for MinGW-w64 targeting Win64
```

All look pretty recent.

**Comment by shmerl** [comment]
Oh, I think I see what's going on. Debian first remove ming alternatives and now it introduced it back. What fun.

After doing the suggested update-alternatives step it all works again.
