### ISSUE TITLE
Image flicker in Battlefield Bad Company 2

### ISSUE THREAD

**Issue by Alllgator343** [doitsujin/dxvk#3078]
https://user-images.githubusercontent.com/39007688/202687975-d5678292-a082-419f-b2f8-c01babbef7ef.mp4

### Software information
Battlefield Bad Company 2 (Origin version (via Lutris))

### System information
- GPU: Intel Core2 Quad Q8400 bits: 64 type: MCP arch: Core Yorkfield rev: A cache: L1: 256 KiB L2: 4 MiB
- Driver: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 515.65.01
- Wine version: lutris-ge-proton7-33-x86_64
- DXVK version: 1.10.3

### Apitrace file(s)
The game don't work without enabled dxvk.

**Comment by Blisto91** [comment]
> The game don't work without enabled dxvk

That is fine, just make a apitrace together with dxvk.
Also include dxvk logs please

Does this also happen with dxvk 2.0?

**Comment by Alllgator343** [comment]
> > The game don't work without enabled dxvk
> 
> That is fine, just make a apitrace together with dxvk. Also include logs please
> 
> Does this also happen with dxvk 2.0?

Tell me, please, where can I find the logs?

**Comment by Blisto91** [comment]
They are usually located next to the games exe or in the root of the game folder.
If you are using lutris you will have to enable "Output debugging info" in your games runner options before they appear.

**Comment by Alllgator343** [comment]
> > The game don't work without enabled dxvk
> 
> That is fine, just make a apitrace together with dxvk. Also include logs please
> 
> Does this also happen with dxvk 2.0?

### Log files
[BFBC2Game_d3d11.log](https://github.com/doitsujin/dxvk/files/10042622/BFBC2Game_d3d11.log)
[BFBC2Game_dxgi.log](https://github.com/doitsujin/dxvk/files/10042623/BFBC2Game_dxgi.log)

### Apitrace file(s)
https://drive.google.com/file/d/1d8snIcPF6tfH5sKH25xSRaHiTDDohdau/view?usp=share_link

After enable apitrace i got this
![Снимок экрана_2022-11-18_20-20-15](https://user-images.githubusercontent.com/39007688/202743006-5d89f7db-2be6-49e6-8ab4-3dc96ef28322.png)

**Comment by Alllgator343** [comment]
> Does this also happen with dxvk 2.0?

I will try tomorrow.

**Comment by Blisto91** [comment]
Found the black flickering to be a regression in https://github.com/doitsujin/dxvk/commit/f5fa7a909961692431306f0c07f583a54cfece49

**Comment by Blisto91** [comment]
This build here should help the issue <https://github.com/doitsujin/dxvk/actions/runs/3500385814>

You can also just make a file called `dxvk.conf` next to the games exe and insert `d3d11.floatControls = False` if that is easier.

**Comment by Alllgator343** [comment]
Using dxvk  2.0 the problem is gone. Thank you very much!

**Comment by Blisto91** [comment]
@Alllgator343 you mean standard 2.0 or the build above?

**Comment by Alllgator343** [comment]
>
I mean this :) 

> > Does this also happen with dxvk 2.0?
> 
> I will try tomorrow.

**Comment by Blisto91** [comment]
Huh weird it still happens for me in the trace with 2.0

Just gonna install the game and check

**Comment by Blisto91** [comment]
Good to hear 🙂👍
