### ISSUE TITLE
Portal 2 using dxvk without crediting

### ISSUE THREAD

**Issue by Kilrha** [doitsujin/dxvk#3080]
Ok I know this isn't really an "issue" but I noticed that the new portal 2 patch implemented dxvk 2.0 without any credit for the developer to be noticed anywhere. Are you fine with this?

**Comment by Blisto91** [comment]
Joshua-Ashton, one of the dxvk devs, is involved with these source game titles and has said he wanted to update them to use dxvk 2.0. So if hasn't done it himself i imagine he pushed for it 🙂 

Also per the dxvk license a direct creditation is not strictly required.

**Comment by Kilrha** [comment]
ok thanks for clarifying!
