### ISSUE TITLE
dvk 2.0 not available on lutris

### ISSUE THREAD

**Issue by liukliukliuk** [doitsujin/dxvk#3081]
i've compiled it but it doesn't show in the selection list

**Comment by Blisto91** [comment]
If you've put the folder in the same place as the other dxvk versions then you just have to write the name of the 2.0 folder in the lutris selection field. 

Also note that the dxvk devs are not involved with lutris development so you should make an issue at the lutris GitHub instead 🙂

**Comment by K0bin** [comment]
Report this to Lutris instead.
