### ISSUE TITLE
Blade & Soul UE4 Close Client DXVK 2.0

### ISSUE THREAD

**Issue by roskiboy** [doitsujin/dxvk#3082]
Please describe your issue as accurately as possible.

Hello, there is a problem with BNS, which when entering the selected character the game loads 20% after the client closes automatically.

PD: BNS UE4 Work in v1.10.3 

### Software information
Blade & Soul UE4

### System information
- GPU: Readon RX580 
- Driver: 21.50.21.11-220428a-382767C-AMD-Software-Adrenalin-Edition
- Vulkan API: Version 1.3.206
- Vulkan Driver: Version 2.0.220
- DXVK version: 2.0

### Apitrace file(s)
- [BNSR Apitrace.zip](https://github.com/doitsujin/dxvk/files/10046285/BNSR.Apitrace.zip)

### Log files
- d3d11.log: [BNSR_d3d11.log](https://github.com/doitsujin/dxvk/files/10046287/BNSR_d3d11.log)
- dxgi.log: [BNSR_dxgi.log](https://github.com/doitsujin/dxvk/files/10046294/BNSR_dxgi.log)

**Comment by Blisto91** [comment]
Hello there.
Sadly it seems like the apitrace is empty.

**Comment by roskiboy** [comment]
> Hello there. Sadly it seems like the apitrace is empty.

the apitrace (BNSR.1.trace) is a second test that I did only with the d3d11.dll, it may be the reason that it is empty.
I'll check it again

**Comment by roskiboy** [comment]
[BNSR.trace.zip](https://github.com/doitsujin/dxvk/files/10048054/BNSR.trace.zip)
[BNSR_d3d11.log](https://github.com/doitsujin/dxvk/files/10048055/BNSR_d3d11.log)
[BNSR_dxgi.log](https://github.com/doitsujin/dxvk/files/10048056/BNSR_dxgi.log)
@Blisto91

**Comment by Blisto91** [comment]
Thanks for trying again but sadly the trace is still empty. Usually they are several hundreds of MB if not a few GB.

I will try to install the game myself here when i have time and do a bisect.

**Comment by roskiboy** [comment]
> Thanks for trying again but sadly the trace is still empty. Usually they are several hundreds of MB if not a few GB.
> 
> I will try to install the game myself here when i have time and do a bisect.

is what the trace returns before the game exits. Thank you very much, the game weighs 70GB and the installation is 160GB. 
Sorry for the inconvenience. Have nice day

**Comment by doitsujin** [comment]
Is the game also known to be broken on Linux?

Not really too much of an incentive to look into it since pretty much all UE4 are fine witrh DXVK, and this being some F2P MMO means that there's probably some sort of anti-cheat involved.

**Comment by roskiboy** [comment]
> 

I am using a bypass on any edition of the UE4. The problem is that it works perfectly in version 1.10.3 but not in v2.0

**Comment by doitsujin** [comment]
do we know **for sure** that this is a DXVK bug and not a problem elsewhere (third-party Vulkan layers fucking things up etc)?

**Comment by roskiboy** [comment]
> do we know **for sure** that this is a DXVK bug and not a problem elsewhere (third-party Vulkan layers fucking things up etc)?
> 
> Again, given that the game is not on Steam, and given that games based on the same engine are known to work fine with 2.0, and given that this is a Windows report where all sorts of things go wrong all the time, there's really not much of an incentive to put significant effort into this.

It's only in dxvk v2.0, minor versions works perfect, never crashes. I think it was the configuration of the DX12 with the functions that they integrated.

In the dxvk file reconfigure the d3d11.maxFeatureLevel = 12_1 to 11_1 as it is working in version 1.10.3 but still not working in v2.0

**Comment by roskiboy** [comment]
> do we know **for sure** that this is a DXVK bug and not a problem elsewhere (third-party Vulkan layers fucking things up etc)?

I'm sure it's DXVK v2.0 because v1.10.3 or lower works correctly.

In the config file change the value d3d11.maxFeatureLevel = 12_1 to 11_1 similar to DXVK v1.10.3 d3d11.maxFeatureLevel = 11_1 but it doesn't work on DXVK v2.0

**Comment by doitsujin** [comment]
I get that it worked in an older version but that doesn't prove much. Feel free to to a git bisect to work out at which exact commit the issue started, if it's the Vulkan 1.3 thing then there's just not much we can really do.

**Comment by roskiboy** [comment]
> I get that it worked in an older version but that doesn't prove much. Feel free to to a git bisect to work out at which exact commit the issue started, if it's the Vulkan 1.3 thing then there's just not much we can really do.

ok, I'll check the git actions builds

**Comment by Blisto91** [comment]
@roskiboy is this with specific graphical settings?
I didn't have issues launching the game with everything set to 2 or 1 on a Nvidia 960 and dxvk 2.0

If you haven't already then also make sure to update your GPU driver to the latest version.

**Comment by roskiboy** [comment]
> @roskiboy is this with specific graphical settings? I didn't have issues launching the game with everything set to 2 or 1 on a Nvidia 960 and dxvk 2.0
> 
> If you haven't already then also make sure to update your GPU driver to the latest version.

oooohhh !!! 
I have the latest version
![image](https://user-images.githubusercontent.com/6926155/203884183-a74dfced-2061-4b11-a530-8ae92c181527.png) ..

I have tried up to the last build that is active from gitactions and it continues with the problem. I'm going to try resetting the default graphics settings.

**Comment by Blisto91** [comment]
@roskiboy Friendly ping. Did you figure something out?

**Comment by Blisto91** [comment]
@roskiboy Double friendly ping

**Comment by Blisto91** [comment]
I finally got around to testing this issue on Windows with my 7900XTX
Lastest driver, dxvk 2.0, every preset and window mode plus vsync on/off. Have still not been able to reproduce

**Comment by K0bin** [comment]
Closing due to a lack of feedback. Feel free to reopen.
