### ISSUE TITLE
Grand Theft Auto IV Aldereny disappering randomly

### ISSUE THREAD

**Issue by CarCrasher730** [doitsujin/dxvk#3084]
Alderney is disappering randomlu in Grand Theft Auto IV. By that I mean when you go to that part of the map you see the map disappering and reappering but its in low quality and often disappears again. It happens mostly when you alt+tab the game or/and when you are far from Alderney it will happen. But if you load the save and happened to save in the safehouse in Aldereny it wont happen or if you stay in the map for a few minutes and look at the directions it will go away or start a mission there. It happens if you play for a long time and might not always occur. It happened on previous DXVK versions too. Also im using NVCleanstall to remove a few nvidia driver bloatware features. And im sure its DXVK as when i remove it, it wouldnt happen.

### Software information
Grand Theft Auto IV
I'm using a texture mod https://www.nexusmods.com/gta4/mods/105 but i have applied community mods like zolikapatch, scripthook and made the game use 4gb ram and commandline

### System information
- GPU:NVIDIA GeForce GTX 1050 Ti
- Driver:522.25
- OS:Windows 10 Enterprise LTSC Version 21H2 (OS Build 19044.1889)
- DXVK version: 2.0

### Log files
[GTAIV_d3d9.log](https://github.com/doitsujin/dxvk/files/10046934/GTAIV_d3d9.log)
[PlayGTAIV_d3d9.log](https://github.com/doitsujin/dxvk/files/10046935/PlayGTAIV_d3d9.log)

**Comment by K0bin** [comment]
> It happens mostly when you alt+tab the game

Yeah alt tabbing is broken in GTA IV with DXVK. 

It's been a known issue for years. No idea how to fix it.

**Comment by Blisto91** [comment]
@CarCrasher730 Please try with this PR https://github.com/doitsujin/dxvk/pull/3316. You can find a download of it here https://github.com/doitsujin/dxvk/actions/runs/4537356630

**Comment by K0bin** [comment]
This is hopefully fixed now.
