### ISSUE TITLE
Assassin's Creed Odyssey

### ISSUE THREAD

**Issue by Sabyseo** [doitsujin/dxvk#3088]
The game gets stuck on the launch screen or just crashes when i try to launch the game with DXVK what can i do?
AMD driver version: 22.2 Windows 10

**Comment by Blisto91** [comment]
Please fill out the issue template with GPU, logs etc

**Comment by drfriooo** [comment]
mine works but performance is terrible, dx11 much more smooth, AMD 22.10.2 and rx 550

**Comment by drfriooo** [comment]
> Game works fine here.
> 
> See https://github.com/doitsujin/dxvk/wiki/Windows.

are you using async version?

**Comment by Blisto91** [comment]
He is the creator of dxvk so no he isn't using the async version 😁

**Comment by drfriooo** [comment]
> He is the creator of this dxvk version so no he isn't using async 😁

sorry, noob here xd, well ill try, thing is 1st time i launched ac odyssey it was fine just some stuttering cause by shaders then i  switched to dx11, but when 2,0 lauch i switched back, but it was far worst, then i used 1.10.3 and same so i dont know

**Comment by doitsujin** [comment]
Shader stutter is normal and has been around for almost five years at this point, I don't understand why people are still surprised/complaining about that.

2.0 has a solution but it requires driver support, wich AMD simply does not have.

**Comment by drfriooo** [comment]
> Shader stutter is normal and has been around for almost five years at this point, I don't understand why people are still surprised/complaining about that.
> 
> 2.0 has a solution but it requires driver support for certain Vulkan extensions, which AMD simply does not have.

I know, just saying cause in origins dvxk works wonder, and in odyssey not, guess its just something with my pc
