### ISSUE TITLE
Plants vs Zombies Garden Warfare 2 Deluxe Edition regression, no longer boots.

### ISSUE THREAD

**Issue by AJuujarvi** [doitsujin/dxvk#3090]
When attempting to boot the game, it throws up an error and a black screen. This happens on Desktop and Steam Deck with SteamOS 3.3 and 3.4. I have a screenshot of the error. As of writing this post, I believe the regression just happened in the past 15 hours.
![Screenshot from 2022-11-21 10-16-46](https://user-images.githubusercontent.com/102748015/203118351-661d9322-ef45-44b2-8224-e7f87aa2e1d2.png)

I believe I bisected it down to the first failing version and the last working version. Those are what is listed with the Proton Experimental Bleeding edges I tested anyway.

Failing DXVK version: dd7ec24269900d2bc017c3cebcd38ef24e3d391f dxvk (v2.0-8-gdd7ec242)

Working DXVK version: 3393c5f4ffd509c7c812ca54853a829910f23f90 dxvk (v2.0-7-g3393c5f4)

### Software information
Plants vs Zombies Garden Warfare 2 Deluxe Edition. Playing via Steam.
No settings changed as it cannot boot.

### System information
Desktop System. Running Ubuntu 22.04, Gnome.
- GPU: Nvidia RTX 3060 Ti
- Driver: 515.65.01
- Proton version: experimental-bleeding-edge-7.0-29435-20221121-p02d7b6-w983de7-ddd7ec2-v3c9aa7
- DXVK version: dd7ec24269900d2bc017c3cebcd38ef24e3d391f dxvk (v2.0-8-gdd7ec242)

Steam Deck
- SteamOS - 3.4
- Driver for GPU: 4.6 (compatibility Profile) Mesa 22.2.0 (git-3ff70c3315) 

additionally
- SteamOS - 3.3.2
- Driver for GPU: 4.6 (Compatibility Profile) Mesa 22.0.2 (git-71648faf15

### Log files
Attaching logs for the game and for the launcher, both were created. I believe the game is the problem one.
- d3d9.log: Game: 
[GW2.Main_Win64_Retail_d3d9.log](https://github.com/doitsujin/dxvk/files/10058596/GW2.Main_Win64_Retail_d3d9.log)
Launcher: 
[Link2EA_d3d9.log](https://github.com/doitsujin/dxvk/files/10058619/Link2EA_d3d9.log)

- d3d11.log: Game: 
[GW2.Main_Win64_Retail_d3d11.log](https://github.com/doitsujin/dxvk/files/10058601/GW2.Main_Win64_Retail_d3d11.log)
Launcher: 
[Link2EA_d3d11.log](https://github.com/doitsujin/dxvk/files/10058618/Link2EA_d3d11.log)

- dxgi.log: Game: 
[GW2.Main_Win64_Retail_d3d9.log](https://github.com/doitsujin/dxvk/files/10058604/GW2.Main_Win64_Retail_d3d9.log)
Launcher: 
[Link2EA_dxgi.log](https://github.com/doitsujin/dxvk/files/10058615/Link2EA_dxgi.log)

**Comment by doitsujin** [comment]
We already reverted the problematic commit.
