### ISSUE TITLE
Can't find any .DLL files, only .DEF files

### ISSUE THREAD

**Issue by thomasexe** [doitsujin/dxvk#3091]
It's just that! i'm trying to use the d3d11.def and dxgi.def, even if i try to rename it windows 11 won't open.
The error message is 0xc000012f "d3d11.dll was not designed to be executed on windows or has an error."

![Screenshot_53](https://user-images.githubusercontent.com/118857345/203431098-f9bca73d-ca04-446d-9cfa-082dba32d390.png)

![Screenshot_54](https://user-images.githubusercontent.com/118857345/203431300-6682b00f-b85b-4cec-9a15-961c1a3f7ca1.png)

**Comment by mbriar** [comment]
You have to download the compiled dll's from the release page, https://github.com/doitsujin/dxvk/releases/download/v2.0/dxvk-2.0.tar.gz

**Comment by K0bin** [comment]
You can't just rename .def files to .dll.
