### ISSUE TITLE
Soul hackers 2 missing effects

### ISSUE THREAD

**Issue by LynnAlice** [doitsujin/dxvk#3094]
While the game runs fine it‘s missing magical effects and the graphic effect for, for example, the teleportation circles.
Missing rain effects:

https://user-images.githubusercontent.com/85197579/188305343-bd755602-4400-43f1-aae4-33d04a2637d7.png

Missing triangles graphics effect

https://user-images.githubusercontent.com/85197579/188305309-e0adddac-b11f-4716-90f6-11b965e48a66.png

Issue was reported to proton GitHub already, but still unresolved

https://github.com/ValveSoftware/Proton/issues/6139

About sportscaster and the rest of information: I looked the guide up, but the steam deck is my first Linux device and I seriously don’t understand all these steps and report this as good as I can. Sorry for the inconvenience. 

### Software information
Soul Hackers 2 on steam with every graphic setting tested and all of them are affected

### System information
- GPU: AMD steam deck APU
- Driver:
- Wine version: GE-Proton 7-41 and Proton 7.0.4
- DXVK version: 

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see:

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by K0bin** [comment]
> Apitrace file(s)
Put a link here

Please do that.

**Comment by Blisto91** [comment]
Yes as said above a thing to try is to install `d3dcompiler_47` with protontricks/winetricks.
Kinda forgot to suggest that back after i asked if the issue was also present with wined3d.

**Comment by LynnAlice** [comment]
The d3dcompiler_47 did the trick and now the effects all work.

**Comment by Blisto91** [comment]
Roger. Then it's a wine (proton wine) issue as dxvk doesn't take care of those dll's
But good to hear you got it working.
