### ISSUE TITLE
Heroes of the Storm logs and trace

### ISSUE THREAD

**Issue by Raffarti** [doitsujin/dxvk#31]
### Software information
Heroes of the Storm, lowest settings.

### System information
- GPU: RX480
- Driver: mesa-git
- Wine version: 2.20-staging
- DXVK version: 0.21 363a0f8a6b5a941e69c56fe62a288bac68af26f2

### Issues
- [x] Ground texture is blinking at high settings - fixed by 9fbddf57df9c88d9ec3bea3020bf413fd6a4c83c
- [x] Health bars and other UI elements blink - fixed by 9fbddf57df9c88d9ec3bea3020bf413fd6a4c83c
- [x] The entire unit get coloured by hoovering instead of its border - fixed by 9fbddf57df9c88d9ec3bea3020bf413fd6a4c83c

**Comment by doitsujin** [comment]
mesa-git is broken and requires `export RADV_DEBUG=nohiz` to work correctly, as is mentioned on the driver support page in the Wiki. Let me know if there are any other issues.

**Comment by Raffarti** [comment]
You're right, it's working. I though of having it tested with nohiz set, maybe I've messed up something. I'll put into bashrc to avoid future issues.

**Comment by Raffarti** [comment]
They changed a lot of stuff since last time I've played, but afaict main issues are:
- Health bars are blinking
- Ground is blinking (squared shapes, only at higher settings)
- Talent UI component is invisible
![screenshot_20180125_164751](https://user-images.githubusercontent.com/2591059/35399475-92c53e48-01f4-11e8-8d9b-6b0bc13dea81.png)
I'll try to make a better trace, hopefully it will not get too big.

**Comment by Raffarti** [comment]
I've added a trace with maximum settings and updated the post above

**Comment by doitsujin** [comment]
Alright, thanks for the update, will take a look.

**Comment by doitsujin** [comment]
Please re-test with commit 9fbddf57df9c88d9ec3bea3020bf413fd6a4c83c - it should at least fix the ground problem.

**Comment by Raffarti** [comment]
Everything's fine now. 
![screenshot_20180129_202859](https://user-images.githubusercontent.com/2591059/35530005-12bad432-0533-11e8-91f8-e90395ed6b43.png)
wine-vulkan is somewhat prone to crash though. It was crashing on loading screen before 9fbddf57df9c88d9ec3bea3020bf413fd6a4c83c, now it crashed when I took the screenshots... I'll investigate more later.

**Comment by Raffarti** [comment]
wine-vulkan crashes when the in-game screenshot functionality is used. Nothing notable in log files.

**Comment by doitsujin** [comment]
Hm, can you post a trace where you take a screenshot? If there's nothing in the logs, I have no idea where to start.

**Comment by Raffarti** [comment]
Looks like it's related to wine itself rather than to dxvk. Wine staging 2.20 doesn't crash with dxvk, wine-vulkan crashes with both dxvk and wine builtin libs. The trace exits cleanly.

**Comment by doitsujin** [comment]
alright, in that case, I'll close this - thanks for testing this so quickly!
