### ISSUE TITLE
How to active HUD

### ISSUE THREAD

**Issue by yuceltoluyag** [doitsujin/dxvk#310]
https://aur.archlinux.org/packages/dxvk-git/ ~  installed this pack
everything is so beautiful and it works fine in games (so thank u)
but i have a problem I could not activate HUD(FPS,memories etc)  the on-screen indicators

### I tried 2 games and did not get results
The Walking Dead  http://store.steampowered.com/agecheck/app/207610/?l=turkish
The Hunter  Classic http://store.steampowered.com/app/253710/theHunter_Classic/

### System information
- GPU: Linux arch 4.16.3-1-ARCH #1 SMP PREEMPT Thu Apr 19 09:17:56 UTC 2018 x86_64 GNU/Linux
- Driver:  GeForce GTX 950/PCIe/SSE2 390.48  
- Wine version:  wine-3.6
- DXVK version: 0.42

ı usefull this script

```
#! /bin/sh 
# script by xpander

# Read the file location and go into it
BINDIR="$(dirname "$(readlink -fn "$0")")"
cd "$BINDIR"
 

# Define directories.
gamedir=$BINDIR
winebindir="$BINDIR"/wine-staging/bin
wineprefixdir="$BINDIR"/_DXVK_prefix

# Disable debugging
export WINEDEBUG=-all

# Vulkan stuff
export DXVK_DEBUG_LAYERS=1
export DXVK_HUD=devinfo,fps,frametimes
DXVK_HUD=1

# Start Steam in prefix
PATH="$winebindir:$PATH" env WINEPREFIX="$wineprefixdir" wine "$BINDIR/_DXVK_prefix/drive_c/Program Files (x86)/Steam/Steam.exe" -no-cef-sandbox
```

**Comment by doitsujin** [comment]
Those are D3D9 games. DXVK only supports D3D11.
