### ISSUE TITLE
Forza Horizon 5 Xid 31 and 13

### ISSUE THREAD

**Issue by wael444** [doitsujin/dxvk#3105]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
+ Game: Forza Horizon 5
+ Distro: KISS Linux

### System information
- GPU: RTX 2060
- Driver: 525.60.11-1
- Wine version: 7.0 (Proton Experimental)
- Wine version: 7.0 (Proton Experimental bleeding-edge)
- DXVK version: Unable to retrieve, MangoHud doesn't work, neither does `DXVK_HUD`

Log files unable to retrieve.

`NVRM: Xid (PCI:0000:01:00): 31, pid=17601, name=ForzaHorizon5.e, Ch 00000025, intr 00000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_GCC faulted @ 0x5580_00008000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ`
```
[ 7442.425225] NVRM: Xid (PCI:0000:01:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception on GPC 0: 3D WIDTH ZT Violation. Coordinates: (0x31e, 0x184)
[ 7442.425259] NVRM: Xid (PCI:0000:01:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception: ESR 0x500420=0x80000004 0x500434=0x184031e 0x500438=0x5050000 0x50043c=0x0
[ 7442.425316] NVRM: Xid (PCI:0000:01:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception on GPC 1: 3D WIDTH ZT Violation. Coordinates: (0x326, 0x178)
[ 7442.425356] NVRM: Xid (PCI:0000:01:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception: ESR 0x508420=0x80000004 0x508434=0x1780326 0x508438=0x5050000 0x50843c=0x0
[ 7442.425415] NVRM: Xid (PCI:0000:01:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception on GPC 2: 3D WIDTH ZT Violation. Coordinates: (0x328, 0x178)
[ 7442.425448] NVRM: Xid (PCI:0000:01:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception: ESR 0x510420=0x80000004 0x510434=0x1780328 0x510438=0x5050000 0x51043c=0x0
[ 7442.425840] NVRM: Xid (PCI:0000:01:00): 13, pid=1331, name=ForzaHorizon5.e, Graphics Exception: ChID 0024, Class 0000c597, Offset 00000000, Data 00000000
```

With `dxvk.shrinkNvidiaHvvHeap = True` and `DXVK_CONFIG_PATH=/home/wael/dxvk.conf` in the command launch parameters, the game will load and go to the festival and going out to drive, and then crash specifically with Xid 13. with 31 it crashes whilst its loading - before reaching the festival and into the actual game.

what is more painful is that Nvidia has been solving Xid 31 errors with many games, and not this one.

**Comment by Blisto91** [comment]
`dxvk.shrinkNvidiaHvvHeap` has been removed as a option with dxvk 2.0 which proton experimental includes. So i'm guessing the changed behavior with that is on proton stable?

> DXVK version: Unable to retrieve, MangoHud doesn't work, neither does DXVK_HUD

No logs are created or hud shown if you run the game with `PROTON_LOG=1 DXVK_HUD=full %command%` ?

**Comment by mbriar** [comment]
FH5 is a DX12 game.

29 Nov 2022, 16:22 by ***@***.***:

**Comment by wael444** [comment]
Well FH5 being Dx12, would that mean DXVK has issues with it?

The game runs perfectly fine on other platforms such as AMD.

> No logs are created or hud shown if you run the game with 

Not explicitly logs, there is no clear location where those are stored. but huds do not appear at all - including mangohud.

**Comment by Blisto91** [comment]
Oh right xd.
You should make an issue at https://github.com/HansKristian-Work/vkd3d-proton then 🙂

**Comment by mbriar** [comment]
DXVK doesn't handle DX12

29 Nov 2022, 16:26 by ***@***.***:

**Comment by wael444** [comment]
that would explain why the hud doesn't show up.

NVIDIA reports it is using Vulkan via the API indicator.

**Comment by wael444** [comment]
well, honestly i'm not exactly sure because i remember it very clearly using DXVK.

**Comment by Blisto91** [comment]
If it was mangohud that reported it in the past then that is a known bug, at least in the past that it would call vkd3d-proton for dxvk.

**Comment by mbriar** [comment]
That's impossible, neither FH4 or 5 ever supported DX11 and DXVK doesn't deal with DX12.

29 Nov 2022, 16:35 by ***@***.***:

**Comment by K0bin** [comment]
As others have noted, it's a D3D12 games

**Comment by wael444** [comment]
okay.
