### ISSUE TITLE
DXVK 2.0 crash with 20XX game (Epic)

### ISSUE THREAD

**Issue by mmbossoni** [doitsujin/dxvk#3107]
Using DXVK 2.0 with 20XX game makes it crash. If I use wine d3d implementation game boots normally (although I have missing textures).
Game needs d3dcompiler_47 to run

### Software information
Game: 20XX
default settings

### System information
- GPU: NVIDIA GTX 1070
- Driver: 525.60.11
- Wine version: tried with Staging 7.22 and 7.20
- DXVK version: 2.0 (as used by Heroic games launcher 2.5)

### Log files
[20XX_d3d9.log](https://github.com/doitsujin/dxvk/files/10123020/20XX_d3d9.log)

**Comment by mmbossoni** [comment]
Looking at ff xiv bug, using d3d9.textureMemory = 0 make the game work.

**Comment by Blisto91** [comment]
Try with latest master. There have been a fix to a potential crash with `d3d9.textureMemory` after the release of 2.0
You can grab a build here https://github.com/doitsujin/dxvk/actions/runs/3564902601

**Comment by mmbossoni** [comment]
No dice. Same crash.

**Comment by Blisto91** [comment]
Try to make a apitrace of the game. https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

Either without dxvk or if with dxvk then together with `d3d9.textureMemory = 0`

**Comment by mmbossoni** [comment]
current dxvk (crash)
[20XX.trace.tar.gz](https://github.com/doitsujin/dxvk/files/10124700/20XX.trace.tar.gz)

**Comment by mmbossoni** [comment]
Trace with textureMemory=0
https://drive.google.com/file/d/1euWIgWSShp8uptzSih4QIlGoU4uPdRNY/view?usp=share_link

**Comment by Blisto91** [comment]
Thank you. The issue reproduces in the trace :+1:
