### ISSUE TITLE
Parsing EDID info fails on Github CI builds

### ISSUE THREAD

**Issue by Areteic** [doitsujin/dxvk#3108]
With DXVK build with commit aa71e7e Sekiro fails to start with following error message:

"sekiro.exe - Fatal Application Exit
Unhandled Exception! See console output for more infos!    ExpCode: 0xC0000005    ExpFlags: 0    ExpAddress: 0x00007FF97D1E5870 "

With DXVK 2.0 it works OK. Trying to nail down which commit broke Sekiro I came across two commits:
1) https://github.com/doitsujin/dxvk/commit/dd7ec24269900d2bc017c3cebcd38ef24e3d391f
2) https://github.com/doitsujin/dxvk/commit/aa71e7e323f80ff20e87ccb9d8a94b5fb1047179

First one is already reverted but it still made bit harder (for me) to track down second commit that lead to crashes.

### Software information
Sekiro: Shadows Die Twice

### System information
- GPU: GeForce RTX 4090
- Driver: 526.98
- Wine version: n/a; Windows version 22H2 (22621.900)
- DXVK version: v2.0-16-gaa71e7e3+   commit aa71e7e323f80ff20e87ccb9d8a94b5fb1047179

### Log files
- d3d9.log: empty log file
- d3d11.log: empty log file
- dxgi.log: attached but there is nothing interesting
[sekiro_dxgi.log](https://github.com/doitsujin/dxvk/files/10123450/sekiro_dxgi.log)
- also attaching modenginecrash.log. I understand it is 3rd party tool but its crashlog at least has something there at the end
[modenginecrash.log](https://github.com/doitsujin/dxvk/files/10123457/modenginecrash.log)

Thanks!

**Comment by doitsujin** [comment]
Sekiro works here (on Linux) on current `master`, please make sure to test an up to date build.

That said, we recently added some code to report the display's HDR capabilities but we don't support HDR yet, and it's also impossible to support it at all in games that only support it via NVAPI/AMDAGS (which at least to my knowledge is the case for Sekiro). It's possible that things just break due to that right now.

**Comment by Areteic** [comment]
Sorry for not mentioning it in OP but yes, I started to have crashes exactly on up to date 9f7066677731e9a7ef2fa16cf85e36fd32c3313a build first and then started searching for commits that broke it for me.

Sekiro does start in HDR first and I play in HDR mode too so it could be it.

**Comment by K0bin** [comment]
DXVK doesn't support HDR and especially not the way HDR is implemented in Sekiro.

**Comment by doitsujin** [comment]
Can you try this branch and post a new log? https://github.com/doitsujin/dxvk/tree/dxgi-printf-debug-stuff

**Comment by doitsujin** [comment]
Can reproduce with the github builds, parsing the monitor EDID fails. No idea why, not sure why it's specific to the CI builds either (local builds work). This affects **all** games that ever query display information.

**Comment by Areteic** [comment]
Here is log with [dxgi-printf-debug-stuff ](https://github.com/doitsujin/dxvk/tree/dxgi-printf-debug-stuff)branch
[sekiro_dxgi.log](https://github.com/doitsujin/dxvk/files/10128919/sekiro_dxgi.log)

**Comment by K0bin** [comment]
#3109 fixes the crash.

**Comment by Areteic** [comment]
Yes, it does not crash now, thank you very much!
