### ISSUE TITLE
Trials of mana crashes when calling flammie (changing to the flying open world)

### ISSUE THREAD

**Issue by terry98** [doitsujin/dxvk#3113]
Hi, everytime I call flammie the game crashes in the loading screen.

I'm not using a dxvk.conf file:

Also, I'm using dxvk 2.0 if I use 1.10.3 it plays fine, so the error is with the latest version only.

my specs

Win 10 21H2
Ryzen 7 5800x 3D
RX 6800

**Comment by K0bin** [comment]
Please make an apitrace.

**Comment by terry98** [comment]
Ok, besides being an extremely slow process (the game played like at 2fps) it didn't crash where the dxvk 2.0 would a 100% of the times. The game loaded the open world just fine, I used the win64 11.1 apitrace files.

In any case, here is the apitrace maybe it helps in finding a problem anyway.

[https://drive.google.com/file/d/1RxJDsYqJ87hxRziusN-bWCOQBhaI3YYV/view?usp=sharing](https://drive.google.com/file/d/1RxJDsYqJ87hxRziusN-bWCOQBhaI3YYV/view?usp=sharing)

**Comment by Blisto91** [comment]
> it didn't crash where the dxvk 2.0 would a 100% of the times. The game loaded the open world just fine, I used the win64 11.1 apitrace files.

That is fine and normal as apitrace doesn't go through dxvk on Windows by default.
Sadly it doesn't crash for me when replayed toget with dxvk on Linux (R9 380).
I will try to test it ingame

**Comment by terry98** [comment]
got it, if you want to reproduce the errorit is like this, right now I'm in the second story (after completing the game once and a witch appears)
1- appear in any dungeon/town
2- select the item to call flammie
3- screen changes to loading screen with yellow bar
4- yellow bar won't complete and the music keeps going as usual
4a- sometime when alt-tabbing you can see a dialog box saying the game crashed, but not always.

I tried in my laptop when you can clearly hear the fans slowing when the game crashes and my desktop.

**Comment by Blisto91** [comment]
I have not been able to make it crash on my Linux setup with a AMD R9 380 and the mesa drivers. Sadly my GPU is not supported by AMD anymore so i can't try dxvk 2.0 with their drivers on either Windows or Linux.

<details>
  <summary>Screenshot</summary>
  
![Screenshot_20221204_172451](https://user-images.githubusercontent.com/47954800/205503305-06c886cb-99bf-46ac-a462-4ee2a2db5bef.png)
</details>

But I'm also going to give it a shot on my Steam Deck

**Comment by terry98** [comment]
weird error, let's hope something can be found using the apitrace.

**Comment by Blisto91** [comment]
Didn't experience a crash on the Deck either. Could be a driver issue.
Can you post dxvk logs from a time it crashed? They should appear in the games base folder or next to the exe.

**Comment by terry98** [comment]
that's weird also, there are no logs, I'm using 22.10.3, right now I'm out, I will try again later

**Comment by terry98** [comment]
well, I updated to drivers 22.11.2 and the error persists, here are the logs:

[https://drive.google.com/file/d/1WiBPsAiBoB6BAo6E8-3BbE7H0Lsl0wsy/view?usp=share_link](https://drive.google.com/file/d/1WiBPsAiBoB6BAo6E8-3BbE7H0Lsl0wsy/view?usp=share_link)

could it be that we need gpl support on windows for dxvk 2.0 to work correctly on some games?

**Comment by doitsujin** [comment]
> could it be that we need gpl support on windows for dxvk 2.0 to work correctly on some games?

No, RADV doesn't support it either at the moment.

**Comment by terry98** [comment]
oks, well I will just keep using 1.10.3 for the moment

**Comment by Blisto91** [comment]
You could try to make a bug report to AMD and see if anything comes out of it.

**Comment by Blisto91** [comment]
Hello. Could you give it a try again with latest master?
You can grab it from here https://github.com/doitsujin/dxvk/actions/runs/3736849094

**Comment by terry98** [comment]
sure! just downloaded the build gonna finish something and try it, I'll report back later.

**Comment by terry98** [comment]
OK! I just tried the latest master you suggested and everything worked as expected, no lockups with music on the background or anything, tried moving to different villages and calling flammie multiple times and everytime the loading screen passed with no issues or crashes just the usual stuttering as shaders are being cached and still the no gpl support in the log, besides from that I'm keeping this versions xD

**Comment by Blisto91** [comment]
Awesome good to hear. Doitsujin just worked around a amd driver issue. Read here if interested https://github.com/doitsujin/dxvk/issues/3138#issuecomment-1358748842

**Comment by terry98** [comment]
oh.. thanks for the info, I saw the issue when it opened but didn't know it was solved, great work Doitsujin, is bothersome when your work is fine and bugs like this keep appearing.
