### ISSUE TITLE
[d3d9] Phantasy Star Online Blue Burst missing textures with DXVK 2.0

### ISSUE THREAD

**Issue by sodaboy581** [doitsujin/dxvk#3117]
Using an NVIDIA 3090 card with 526.98 driver (also happens with AMD cards), textures are missing when playing Phantasy Star Online Blue Burst in D3D9 mode.

We are utilizing D3D8to9 to elevate the game to D3D9, which works fine otherwise when you play vanilla Direct3D 9, but with DXVK we have missing texture problems.

In the screenshots attached, you can see that the Gol Dragon's monitors are blank (they flicker in real time), the laser panel in the Forest is blank, and the laser effect for doorways in CCA is completely missing.

Running this under straight Windows 11.
![pso133146478979985817](https://user-images.githubusercontent.com/48497880/205505853-ed737699-c079-49ed-8459-d56fdade9aff.png)
![pso133146478433965829](https://user-images.githubusercontent.com/48497880/205505865-f4b3e861-c4b7-4aa0-93b6-6476e20c8817.png)
![pso133146478242960077](https://user-images.githubusercontent.com/48497880/205505872-141266f9-679d-48ea-b2fd-9cb009c2175a.png)

I'm also uploading shots of how they SHOULD look like...

![pso133146485348188990](https://user-images.githubusercontent.com/48497880/205506014-0184bbb7-306e-4f5c-9dda-faa29dc08c07.png)

![pso133146485816619457](https://user-images.githubusercontent.com/48497880/205506022-9c5d692b-e31b-4016-a80e-cc3d1eed3c2c.png)
![pso133146486079441087](https://user-images.githubusercontent.com/48497880/205506026-b4eb796a-55de-4d03-b1a4-8a85fe8239f5.png)

Here's the log file from the game...

[psobb_d3d9.log](https://github.com/doitsujin/dxvk/files/10149113/psobb_d3d9.log)

**Comment by sodaboy581** [comment]
You can reproduce, if you have the time, by following these steps:

1. Download the game client at https://ephinea.pioneer2.net/ 
2. Make a "Sandbox" account on the same website.
3. Configure the game from the launcher to use Vulkan.
4. Log into the game.
5. Once on a ship, create an Episode 2 game.
6. Type "/warpme 15" without the quotations and hit enter.
7. You should see the Gol Dragon monitor glitch immediately.

**Comment by Blisto91** [comment]
Hello. The "Game Download" button on the site gives me a "404 Not Found"

It might be worth trying out [d8vk](https://github.com/AlpyneDreams/d8vk) since if that ever merged into dxvk (nothing is official or decided afaik) i imagine d3d8to9 together with dxvk would become unsupported. It's still early in development but you can find the latest builds here https://github.com/AlpyneDreams/d8vk/actions/workflows/artifacts.yml?query=branch%3Amaster++

**Comment by sodaboy581** [comment]
> Hello. The "Game Download" button on the site gives me a "404 Not Found"
> 
> It might be worth trying out [d8vk](https://github.com/AlpyneDreams/d8vk) since if that ever gets merged into dxvk (nothing is official or decided afaik) i imagine d3d8to9 together with dxvk would become unsupported. It's still early in development but you can find the latest builds here https://github.com/AlpyneDreams/d8vk/actions/workflows/artifacts.yml?query=branch%3Amaster++
> 
> Edit: now the download worked

Yeah, that was my bad, I was refreshing the installer with the latest patches. 

We could add d3d8 to VK, but a lot of people prefer d3d9 because of shader support.

**Comment by K0bin** [comment]
Please make an apitrace of the game.

**Comment by sodaboy581** [comment]
OK, so, I've made a trace.

Strangely while making the trace with apitrace 11.1, the issue isn't present.  Don't know if that's normal or not, but yeah, here's the trace file compressed to a 7-zip archive.

I was unable to upload the trace through GitHub as the file exceeded 25MB and 7z wasn't allowed.  (Tried ZIP too but then it was twice the size.)

You can download the trace from https://files.pioneer2.net/PsoBB.trace.7z

Thanks.

**Comment by K0bin** [comment]
> Strangely while making the trace with apitrace 11.1, the issue isn't present. Don't know if that's normal or not, but yeah, here's the trace file compressed to a 7-zip archive.

That's normal.

**Comment by Blisto91** [comment]
Thanks for the trace.
This seemed to have worked back in d9vk 0.13f and then regressed in 0.20

**Comment by WindSpirit48** [comment]
STOP HACKING USERS!

**Comment by K0bin** [comment]
The problem here is that there's something wrong with how DXVK handles fixed function projected texture coordinates.

The game sets `TEX1` as the only tex coord FVF bit. So we end up with a tex coord size of 2.
Meanwhile it sets 259 as the texture transform flags which is equivalent to `PROJECTED | COUNT3`.

DXVK ends up clamping to the texcoord size of 2 and thus uses the y coord as the value that the projection divides by.
That is most likely wrong. Changing it to z fixes the issue. Additionally the docs say the following:

>  The D3DTTFF_PROJECTED flag causes the rasterizer to divide the first two elements by the third (or n) element

Now the question is how exactly this is supposed to work. We don't want to break #3293 again.

**Comment by nolrinale** [comment]
Hello, I wanted to also offer my input as i've been witnessing the same issues with this specific game lately, I've tested with D8VK as I just want to run the game with its native API without need to use D3D8to9/Reshade and the game behaves with the same graphic issues as mentioned above by the OP.

Tested in both Linux (Fedora 40) under Wine 9.5 Staging and on a Steam Deck
