### ISSUE TITLE
[d3d11] TRAHA Global shadow issue

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3118]
Original report https://github.com/ValveSoftware/Proton/issues/6361

Game have a issue with a bunch of shadows following you around

<details>
  <summary>Screenshot</summary>
  
![Screenshot_20221204_203914](https://user-images.githubusercontent.com/47954800/205511739-69d7d41f-db0e-4425-86cd-e8cb6e4c694f.png)
</details>

### Software information
TRAHA Global (Free to play)
ULTRA settings

### System information
- GPU: R9 380
- Driver: 22.2.3
- Wine version: Proton-Next & experimental
- DXVK version: 1.0, 1.10.x, 2.0

### Apitrace file(s)
Made through proton with dxvk 2.0

https://mega.nz/file/4kg1nSpC#9fji8uiZdzBXh6v6QqrVXzrjxJhvxImG1MMfjN0pJGY

### Log files
[RapaNui-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/10149325/RapaNui-Win64-Shipping_d3d11.log)
[RapaNui-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/10149326/RapaNui-Win64-Shipping_dxgi.log)

**Comment by doitsujin** [comment]
Based on the trace, this looks like a game bug.

**Comment by Big-FG** [comment]
> Based on the trace, this looks like a game bug. Happens on Windows too when replaying it.

perhaps it is AMD specific and all the game footage Ive seen has been Nvidia? I havent seen this occur for any YT videos with it but i also cant be 100% on if theyre all running Nvidia or not.

**Comment by Blisto91** [comment]
It works fine on native Windows with my R9 380.
Tho haven't been able to find anything that helps on dxvk Linux. (not a dev)

**Comment by Blisto91** [comment]
For some reason the issue appears when it sees a AMD or Nvidia vendor id. We can work around it by telling we are on Intel.
