### ISSUE TITLE
Need for Speed Payback lighting issue

### ISSUE THREAD

**Issue by AccountOneOff** [doitsujin/dxvk#312]
Car is surrounded by a big shadow. Here's a short video of the problem:

https://www.youtube.com/watch?v=eAdxD4dHEP8

### Software information
Need for Speed Payback
High settings

### System information
- GPU: GTX 960
- Driver: 396.18
- Wine version: 3.5 Staging
- DXVK version: 8508994

*Sorry for the old DXVK version. Apitrace wasn't working so I tested with an old commit. The problem was with apitrace itself and I forgot to switch out the dlls. It still occurs with the latest version though.

### Apitrace file(s)
- https://drive.google.com/open?id=1a9L1Cv8JcQYWMXYoOWyspleCPDP1iuwt

There's a bunch of irrelevant trace at the beginning because I was waiting on the game's day/night cycle. The problem is shown towards the end of the trace.

### Log files
- d3d11.log: [NeedForSpeedPayback_d3d11.log](https://github.com/doitsujin/dxvk/files/1933445/NeedForSpeedPayback_d3d11.log)
- dxgi.log: [NeedForSpeedPayback_dxgi.log](https://github.com/doitsujin/dxvk/files/1933446/NeedForSpeedPayback_dxgi.log)

**Comment by kgudalov** [comment]
The same is observed in Dishonored 2.

Software information:

Dishonored 2 ( Steam version)
Low settings

System information:

Linux mint 18.3
GPU: GTX 1060
Driver: 396.18
Wine version: 3.6 Staging
DXVK version: 8125d53

Log files:

d3d11.log:  
[Dishonored2_d3d11.log](https://github.com/doitsujin/dxvk/files/1934411/Dishonored2_d3d11.log)
dxgi.log
[Dishonored2_dxgi.log](https://github.com/doitsujin/dxvk/files/1934412/Dishonored2_dxgi.log)

**Comment by kgudalov** [comment]
Yes, with the latest version everything is fixed. But with the old compiler, there is a problem with lighting from local sources. There is no such problem with the new compiler. Waiting for a new driver from Nvidia.

**Comment by kgudalov** [comment]
@doitsujin Yes, with the latest version everything is fixed. But with the old compiler, there is a problem with lighting from local sources. There is no such problem with the new compiler. Waiting for a new driver from Nvidia.

**Comment by AccountOneOff** [comment]
The lighting issue is no longer present on the latest commit!
