### ISSUE TITLE
dxvk is hacking your system

### ISSUE THREAD

**Issue by WindSpirit48** [doitsujin/dxvk#3120]
Once you open the file, and create the config, it deletes your system restore points so you can't Undo the hack it does.
It buries itself in the VRAM.

The authors of this should be shamed for doing this. Please everyone report them before they do more damage.

### System information
- GPU: 105O TI
- Driver: 
- Wine version: 
- DXVK version:  Latest

**Comment by K0bin** [comment]
It doesn't do any of that.

**Comment by WindSpirit48** [comment]
> It doesn't do any of that.

REPORTED.  Finally someone saw through this bull shit.
