### ISSUE TITLE
STOP HACKING USERS!

### ISSUE THREAD

**Issue by WindSpirit48** [doitsujin/dxvk#3121]
Please STOP HACKING PEOPLE

**Comment by WindSpirit48** [comment]
Dont use anything from their profile their files hack your system and gpu!

**Comment by K0bin** [comment]
The code is literally right here for anybody to check and clearly shows we're doing none of that.

**Comment by WindSpirit48** [comment]
> 

Code is different than what is in the file!

**Comment by K0bin** [comment]
No, it's not.
