### ISSUE TITLE
STOP HACKING USERS! 

### ISSUE THREAD

**Issue by WindSpirit48** [doitsujin/dxvk#3122]
This file will hack your system and destroy your restore points so you can undo the damage be warned!

**Comment by nipkownix** [comment]
🤡

**Comment by bno1** [comment]
where did you download dxvk from?

**Comment by K0bin** [comment]
Virus Total:

[d3d9.dll](https://www.virustotal.com/gui/file/77dd1541f2f6c4e85190d1fecb3acb3048b4e9c7057f19313ea2112fa2853460)
[d3d10.dll](https://www.virustotal.com/gui/file/dc0b0c0ffb194d1d93e312107e6c2014481b92b79dd8cfe0b33079bd87db6db5)
[d3d11.dll](https://www.virustotal.com/gui/file/84f0ea810489c2d2cad6c5caa00badacf11fe260aadbb1850b4f38fc5812e781)
[dxgi.dll](https://www.virustotal.com/gui/file/6690e20576c51d211f609b3a3ea2ce8098c306add48b4b1a9300f4cecb62c5a1)

**Comment by Iglu47** [comment]
just friendly reminder: https://github.com/doitsujin/dxvk/wiki/Windows#dll-loading-issues
**Note: DO NOT** replace Windows DLLs in `System32` or `SysWOW64` with DXVK's. This **will** break your Windows install.
