### ISSUE TITLE
[d3d9] S4 League missing textures with DXVK 2.0

### ISSUE THREAD

**Issue by Kethen** [doitsujin/dxvk#3123]
With the same trace captured with wined3d, texture issues were not observed under dxvk-1.10.3 replay, only on dxvk-2.0 replay

Below are screenshots from frame 3633

Tested on an intel laptop with UHD Graphics 620, AMD RX 580, and a mobile GTX 1050 owned by a friend

Might be related to #3117

### dxvk-1.10.3
<img src="https://user-images.githubusercontent.com/22017945/205997109-79f2dba7-c7e6-425f-9726-fe308da45311.png" width=500px>

### dxvk-2.0
<img src="https://user-images.githubusercontent.com/22017945/205997180-e7551f7b-b817-4ee0-9d43-0f3bc48c17d3.png" width=500px>

### Software information
S4 League, runs on d3d9

### System information
- GPU: Intel(R) UHD Graphics 620 (KBL GT2), AMD Radeon RX 580 Series (RADV POLARIS10), NVIDIA GeForce GTX 1050
- Driver (INTEL and AMD): 22.2.3 mesa on fedora, vulkan version 1.3.224
- Driver (NVIDIA): 520.56.6 proprietary, vulkan version 1.3.205
- Wine version: Wine-GE-Proton7-34
- DXVK version: 2.0

### Apitrace file(s)
- https://drive.google.com/file/d/1YdLZL5yCmJwthho_FzWNt64BJDgMPZsq/view?usp=sharing

**Comment by Blisto91** [comment]
Broke some the alpha test changes. Last working commit is https://github.com/doitsujin/dxvk/commit/2c713a34c9088dd726fd4d10cd022ed0be49e2fb and knwn bad commit is https://github.com/doitsujin/dxvk/commit/85cc87e42a9adaa631593abfd06ec281001eae63
I'm not able to test the commits in between as the trace crashes with them but should be the one of those https://github.com/doitsujin/dxvk/compare/2c713a3...85cc87

**Comment by doitsujin** [comment]
Thanks for the trace and bisect. The PR above should fix this.
