### ISSUE TITLE
Star Citizen lighting issues

### ISSUE THREAD

**Issue by ZeroFault** [doitsujin/dxvk#313]
The lighting is black for most of the screen.

![starcitizen](https://user-images.githubusercontent.com/3112580/39088807-fc154d2e-4575-11e8-99cd-bd2a0ad5af1f.png)

### System information
- GPU: GTX 1080
- Driver: 391.35
- Wine version: Native Windows 10
- DXVK version: [f71f527](https://github.com/doitsujin/dxvk/commit/f71f527b4d4297e2b45bd0ba352bd8a5ac9cccc2)

### Apitrace file(s)
[trace](https://mega.nz/#!aCZjWKja!O-1CFF5WVztAsdSuePxM2k1_62psySO7tvkycvdmlPk)

### Log files
[StarCitizen_d3d11.log](https://github.com/doitsujin/dxvk/files/1934992/StarCitizen_d3d11.log)
[StarCitizen_dxgi.log](https://github.com/doitsujin/dxvk/files/1934993/StarCitizen_dxgi.log)
[vulkanlog.txt](https://github.com/doitsujin/dxvk/files/1934994/vulkanlog.txt)

**Comment by doitsujin** [comment]
That a regression or did that never work to begin with?

**Comment by ZeroFault** [comment]
Never worked to begin with.

**Comment by shrimpza** [comment]
For more background; the same issue is present with plain Wine, even without DXVK.

**Comment by ZeroFault** [comment]
As of [f4a92a6](https://github.com/doitsujin/dxvk/commit/f4a92a685f8b2f135dc6fe493ea9ce726aa79a52) the lighting issues seems to be fixed. However, I am now receiving a crash in some places.
This error looks to be the cause of the crash
```
err:   D3D11: Incompatible UAV formats
  Base format: 27
  View format: 42
```

**Comment by ZeroFault** [comment]
Commit [fb3dbd8 ](https://github.com/doitsujin/dxvk/commit/fb3dbd8bcd4e7acdfe8c956633ec1b703a323afc)
fixed the crash. Thank you.
