### ISSUE TITLE
WoW 3.3.5a Crash on Debian - NVidia 510.85.02

### ISSUE THREAD

**Issue by kgilmore17** [doitsujin/dxvk#3130]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Name of the game, settings used etc.
World of Warcraft 3.3.5a 

Any help would be greatly appreciated. Running native is trash and I'd very much like to get this operating. Vulkan is running properly on my GPU AFAIK, I attached my vulkaninfo output.

### System information
- GPU: NVidia Quadro K620M
- Driver: 510.85.02
- Wine version: wine-7.0
- DXVK version: 2.0-async (I've also tried using winetricks)

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

Here's the output when I run "wine wow.exe", I have tried editing various settings in dxvk.conf to no avail.

This is on a fresh wine32 prefix as well. I have tried using both winetricks as well as manually downloaded 32-bit dxvk dlls.

[wow_d3d9.log](https://github.com/doitsujin/dxvk/files/10199253/wow_d3d9.log)

[2022-12-10 00.08.28 Crash.txt](https://github.com/doitsujin/dxvk/files/10199255/2022-12-10.00.08.28.Crash.txt)

[vulkaninfo.txt](https://github.com/doitsujin/dxvk/files/10199259/vulkaninfo.txt)

**Comment by kgilmore17** [comment]
NVM - I was running wine stable at 7.0 and needed 7.1 minimum. My bad. Thank you!

**Comment by Blisto91** [comment]
Hello.
Do i understand correctly that you solved your issue? 🙂

**Comment by xpander69** [comment]
I think he resolved the issue yes. But he is also using async dxvk it seems, so that should be removed from here anyway
