### ISSUE TITLE
Floodland game crash

### ISSUE THREAD

**Issue by ghost** [doitsujin/dxvk#3134]
After the game had been opened for a while, it is crashing.

### Software information
Floodland

[https://store.steampowered.com/app/1336180/Floodland/](url)

### System information
- GPU: R9 290X
- Driver:  Vulkan 1.3.235
- Wine version: wine-8.0-rc1 (Staging)
- DXVK version: v2.0-34-gc55c0936

### Log files
- d3d11.log: [Floodland_d3d11.log](https://github.com/doitsujin/dxvk/files/10208647/Floodland_d3d11.log)
- dxgi.log: [Floodland_dxgi.log](https://github.com/doitsujin/dxvk/files/10208650/Floodland_dxgi.log)

**Comment by Blisto91** [comment]
How long time does it approximately take for a crash to occur and does it also happen with with 1.10.3?

I can see that it complains about shared resources once which requires some proton experimental patches. Tho i don't know how relevant that is.

**Comment by Blisto91** [comment]
Is that in regards to shared resources or dxvk 1.10.3?

Also how long does it usually take to occur? 🙂

**Comment by doitsujin** [comment]
For the record, shared resources **require** Proton patches. There's no way to support them on plain Wine.

**Comment by Iglu47** [comment]
> * Wine version: wine-8.0-rc1 (Staging)

@archlinuxlovers could you try a wine-staging 7.15? (although this won't solve the problem properly)
or/and also could you confirm "the crash doesn't happen on Proton 7.0-5"?

**Comment by Blisto91** [comment]
@archlinuxlovers Friendly ping
