### ISSUE TITLE
Witcher 3 (v4.0) - HairWorks doesn't work after game update

### ISSUE THREAD

**Issue by zaps166** [doitsujin/dxvk#3136]
The game doesn't display hair with HairWorks enabled. Moreover there is notably lower FPS when it's enabled.

![W3](https://user-images.githubusercontent.com/6239090/207592266-1f8a4fe1-ab26-4290-a55b-7f787b94407b.png)

### Software information
The Witcher 3 (v4.0) DX11
Manjaro Linux

### System information
- GPU: Radeon RX 6900XT and GeForce RTX 2060
- Driver: Mesa 22.3.0 and NVIDIA 525.60.11
- Wine version: proton-7.0-6-rc4
- DXVK version: 1.10.3 (the same on current master c55c09368b8e7d878cbe602b6d380ba0d1e6e1b3)

### Log files
- d3d11.log: [witcher3_d3d11.log](https://github.com/doitsujin/dxvk/files/10227699/witcher3_d3d11.log)
- dxgi.log: [witcher3_dxgi.log](https://github.com/doitsujin/dxvk/files/10227700/witcher3_dxgi.log)

When HairWorks in enabled, in wine/proton logs I noticed:
- thousands/millions of empty lines
- a lot of `04a0:074c:fixme:d3dcompiler:D3DCompile2 Ignoring flags 0x8800.`

**Comment by Blisto91** [comment]
@zaps166 Hello. From what I've gathered this might be a issue with proton `d3dcompiler_47.dll` so a install of the `d3dcompiler_47` windows version through protontricks or winetricks should work around it.

**Comment by zaps166** [comment]
@Blisto91 Thanks, it's working now!
