### ISSUE TITLE
New World Support

### ISSUE THREAD

**Issue by Codfired** [doitsujin/dxvk#3137]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Is possible to plan implement Support for New World ? This Game Crash on time with Easy-Anti-Cheat Error ... Unfortunately is the Game a Fail-Development under Directx11  with compare on Directx12. Massive Polygone and calculation geneerate much CPU-Overheads. Here would dxvk very effective or ?

### System information
- GPU: RTX 2080
- Driver: 562
- DXVK version: 2.0

### Apitrace file(s)
- not exist

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
not log exist/generated

**Comment by K0bin** [comment]
If the anti cheat isn't happy with DXVK, there's simply nothing we can do.

**Comment by doitsujin** [comment]
Sounds like the anti-cheat is doing exactly what it's designed to do, nothing we can do here.
