### ISSUE TITLE
Dragon Age Inquisition rendering regression

### ISSUE THREAD

**Issue by portentum** [doitsujin/dxvk#314]
As of dcb5b2a game world is black.
![2018-04-21_17 38 33_i3shot](https://user-images.githubusercontent.com/2179882/39089017-8d58aa34-45ac-11e8-96f6-44d942d3569b.png)

### Software information
Dragon Age: Inquisition

Settings: Ultra/High mixture

### System information
- GPU: Radeon RX 570 8GB
- Driver: mesa git [8f13975](https://cgit.freedesktop.org/mesa/mesa/commit/?id=8f13975713a7a7b8d625e3561a7fc9ce202ac64b)
- Wine version: staging git [eb4096d](https://github.com/wine-staging/wine-staging/commit/eb4096dc6205691378af8726ccabb3831753eb7e)
- DXVK version: git f71f527

### Apitrace file(s)
- [DAI.win7.bench.trace.tar.xz](https://ufile.io/u9dxq) ([mirror](https://mega.nz/#!KbYCSCgL!xfD8Ua2_o1sgQStimTnC0YQnrjKIdaMTlJtIH-F5bRM))
Trace is from Windows 7 as the game will not run under wined3d.
It's also ridiculously large at 1.7GiB compressed, 3.2GiB uncompressed.
I'm unable to replay the trace so I don't know how useful it will be.

### Log files
- d3d11.log:
[DragonAgeInquisition_d3d11.log](https://github.com/doitsujin/dxvk/files/1935017/DragonAgeInquisition_d3d11.log)
- dxgi.log: 
[DragonAgeInquisition_dxgi.log](https://github.com/doitsujin/dxvk/files/1935018/DragonAgeInquisition_dxgi.log)

**Comment by doitsujin** [comment]
For future reference, it's better to use something like Google Drive or Mega to host apitrace files. That hoster only allows me to download it at 300 kB/s, it's taking ages.

Anyway, if you can't replay it locally it's probably useless and i won't be able to debug the issue. Can you record one with dxvk directly? Since this is probably a shader issue it should be fine.

**Comment by portentum** [comment]
[DAI_dxvk_bench.tar.xz](https://mega.nz/#!zCZwkAoQ!yNhAmdalFwskAtRlv1rW77QjvDnOoKgEfJAVUxA8RYI)

This one starts to replay at least. Unfortunately the replay crashes for me before showing the issue. Hopefully it's more useful to you. 2¾ hours to record this thing. :persevere:

**Comment by doitsujin** [comment]
Thanks. I'm currently trying to debug another regression caused by that commit in Kingdom Come: Deliverance, which may or may not be related. I'll give you an update once I figure this out.

**Comment by doitsujin** [comment]
2f20a61342472cdb218f47ad8b94c129109d0337 should fix this. Essentially this is a game bug, it binds a multisampled image to a slot that expects a non-multisampled image. It's pure luck that this ever worked in the first place.

**Comment by portentum** [comment]
Confirming fixed by 2f20a61.
