### ISSUE TITLE
[DX11] Escape from Tarkov crashes while loading the "Lighthouse" map since DXVK 1.10.1.

### ISSUE THREAD

**Issue by Vinjul1704** [doitsujin/dxvk#3140]
The game Escape from Tarkov crashes while loading the "Lighthouse" map since commit 48046e009c9d3d8bd4f8128d4e893990908c2819. The crash occurs during the "loading loot" section in the loading screen and I am not aware of a workaround via game or DXVK options. Versions before that commit work perfectly fine.

### Software information
Game: [Escape from Tarkov](https://www.escapefromtarkov.com/)
Settings: Any

### System information
- GPU: AMD Radeon RX 6700 XT
- Driver: Mesa 22.3.1
- Wine version: lutris-7.2-2-x86_64
- DXVK version: 1.10.1+ / Commit 48046e009c9d3d8bd4f8128d4e893990908c2819

### Apitrace files
Since the game uses BattlEye and blocks additional DLLs in the game folder on Windows, the traces had to be done on Linux. It also crashes at an earlier point in the loading screen when doing an apitrace and I'm not sure if that's a problem. Just to be safe, I made both a broken (release 1.10.1) and a working (release 1.10) trace. WineD3D is completely broken in that game, so I wasn't able to use that for traces.

- Broken (1.10.1): https://drive.google.com/file/d/1nS1RMqll5dI-3wy2xyjx87rlDrKdthux
- Working (1.10): https://drive.google.com/file/d/1Q0OYukx9tchQP-usOMMexlKgsJ4Ua6M9

### Logs (first bad commit)
- d3d11.log: [EscapeFromTarkov_d3d11.log](https://github.com/doitsujin/dxvk/files/10263885/EscapeFromTarkov_d3d11.log)
- dxgi.log: [EscapeFromTarkov_dxgi.log](https://github.com/doitsujin/dxvk/files/10263887/EscapeFromTarkov_dxgi.log)

### Logs (last good commit)
- d3d11.log: [EscapeFromTarkov_d3d11.log](https://github.com/doitsujin/dxvk/files/10263890/EscapeFromTarkov_d3d11.log)
- dxgi.log: [EscapeFromTarkov_dxgi.log](https://github.com/doitsujin/dxvk/files/10263894/EscapeFromTarkov_dxgi.log)

### Video examples
Crash (first bad commit): https://youtu.be/FGA2IluBIGg
Working (last good commit): https://youtu.be/PFGNbzPyf1I

**Comment by doitsujin** [comment]
Shared Resources are only supported on Proton, not on regular wine builds.

**Comment by Vinjul1704** [comment]
That makes sense. It does indeed work when using Proton 7 as well as wine builds in Lutris that are based on Proton, such as lutris-GE-Proton7-33-x86_64. I should have checked that beforehand, my bad.

However, is it not possible to add checks in DXVK, to ensure it at least does not crash on versions that don't have it? It clearly works on DXVK versions without it at all.

**Comment by Blisto91** [comment]
Proton 7 does not have the shared resources wine patches yet, only experimental. So it might be some kind of issue with the lutris wine.

**Comment by Blisto91** [comment]
@Vinjul1704 Am i correct in that this was a solved issue when not using lutris wine?

**Comment by Blisto91** [comment]
@Vinjul1704 friendly ping

**Comment by Vinjul1704** [comment]
Sorry, I completely missed the first ping. I believe so, yes, but I can't test it myself currently. I'll ask some others if they have time to confirm it though.

**Comment by Blisto91** [comment]
@Vinjul1704 Was this able to be confirmed?

**Comment by Faalagorn** [comment]
It seems to happen for me too, sadly. Loading into Lighthouse crashes the game (it used to work fine), loading into Streets of Tarkov map works fine.

Can't test it with different Wine version right now, as it only works for me lutris-GE-Proton-8.4 for some reason :thinking: …
![screenshot_2023-12-23-185652](https://github.com/doitsujin/dxvk/assets/4951331/fe3d48eb-86f2-4da0-bde4-a023fe4b94b4)

**Comment by Vinjul1704** [comment]
On a fresh install, it does indeed crash when using the older lutris-7.2-2 wine version. Using a newer version, like wine-ge-25, works fine.

**Comment by Faalagorn** [comment]
Okay, I tried with the new Wine version, it seems to load, so I guess it might be fixed upstream, or is dependant on some patches that are applied by some Wine forks that may correlate with something on DXVK?[](url)
![screenshot_2023-12-26-221209](https://github.com/doitsujin/dxvk/assets/4951331/800d0221-cf26-4205-9610-4c7ec48ac1f6)
(same installation, just replaced the Wine version to the one I compiled today)
