### ISSUE TITLE
Instructions about mingw on Debian will need updating

### ISSUE THREAD

**Issue by shmerl** [doitsujin/dxvk#3143]
Debian unstable made mingw posix and mingw win32 non coinstallable, so new method is simply choosing one option instead of using update-alternatives.

**Comment by doitsujin** [comment]
We should probably just remove distro-specific instructions altogether and instead state more clearly what is required.

Anyway, that's something for after the holidays.

**Comment by shmerl** [comment]
This is obsolete now, Debain introduced alternatives for it again.
