### ISSUE TITLE
Project Torque - Wont start. unimplemented function d3dx9_36.dll.D3DXGatherFragments

### ISSUE THREAD

**Issue by Jackster** [doitsujin/dxvk#3144]
Cross-posting from Proton https://github.com/ValveSoftware/Proton/issues/3359

### Software information
ProjectTorque https://store.steampowered.com/app/1112400/Project_Torque__Free_2_Play_MMO_Racing_Game/
Note that the Steam release has obfuscation. 

DirectX 9 game built using .NET 3.5 and DirectX9 SDK Nov 07 on VS 2008.

The game had run on Deck before but had to install:
- d3dx9_36 - Microsoft Directx 9.0c
- dotnet35sp1 - .Net 3.5 Service Pack 1
- mfc90 - Visual C++ 2008 Redistributable
https://community.projecttorque.racing/threads/steam-deck-support-it-works.1618/#post-9316
This stopped working after a month or so. Not sure as to why.

### System information
- GPU: Steam Deck
- Driver:
- Wine version: 7.0
- DXVK version: 1.10.3
- Proton: 1667938887 proton-7.0-5

### Apitrace file(s)
WORKING ON IT

Windows, if it is of any use idk? https://www.dropbox.com/s/5kzjtzmq4tjmbq8/PTtrace.zip?dl=0

### Log files
- d3d9.log: [GameLogic_v1_d3d9.log](https://github.com/doitsujin/dxvk/files/10282536/GameLogic_v1_d3d9.log)
- d3d11.log:
- dxgi.log:

[DXVK.log](https://github.com/doitsujin/dxvk/files/10282465/DXVK.log)
[WINED3D.log](https://github.com/doitsujin/dxvk/files/10282466/WINED3D.log)

**Comment by mbriar** [comment]
DXVK doesn't implement d3dx9, this is a wine bug.

**Comment by Jackster** [comment]
> DXVK doesn't implement d3dx9, this is a wine bug.

Ah thought so. Got a bit confused as to what is what.
