### ISSUE TITLE
Rise of the Tomb Raider crashes with DXGI_ERROR_DEVICE_RESET

### ISSUE THREAD

**Issue by github-anton** [doitsujin/dxvk#3147]
Rise of the Tomb Raider crashes in  Soviet Installation 20% with DXGI_ERROR_DEVICE_RESET. 

Second d3d11.log from this modified files:

dxvk_device.cpp:

void DxvkDevice::waitForIdle() {
    this->lockSubmission();
    VkResult status = m_vkd->vkDeviceWaitIdle(m_vkd->device()) ;
    if ( status != VK_SUCCESS)
      Logger::err(str::format("DxvkDevice: waitForIdle: Operation failed: ", status));
    this->unlockSubmission();
  }

d3d11_swapchain.cpp:

 HRESULT STDMETHODCALLTYPE D3D11SwapChain::Present(
          UINT                      SyncInterval,
          UINT                      PresentFlags,
    const DXGI_PRESENT_PARAMETERS*  pPresentParameters) {
    auto options = m_parent->GetOptions();

    if (options->syncInterval >= 0)
      SyncInterval = options->syncInterval;

    if (!(PresentFlags & DXGI_PRESENT_TEST)) {
      bool vsync = SyncInterval != 0;

      m_dirty |= vsync != m_vsync;
      m_vsync  = vsync;
    }

    HRESULT hr = S_OK;

    if (!m_presenter->hasSwapChain()) {
      RecreateSwapChain(m_vsync);
      m_dirty = false;
    }

    if (!m_presenter->hasSwapChain())
      hr = DXGI_STATUS_OCCLUDED;

    VkResult status = m_device->getDeviceStatus() ;
    if (status != VK_SUCCESS) {
      hr = DXGI_ERROR_DEVICE_RESET;
      Logger::err(str::format("Present(): status=", status));
    }
...

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Name of the game, settings used etc.

### System information
- GPU: Intel iRISxe
- Driver: mesa
- Wine version: wine-8.0-rc1 (Staging)
- DXVK version: dxvk-master-20221215

### Apitrace file(s)
Don't run with apitrace files.

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:
[ROTTR_d3d11.log](https://github.com/doitsujin/dxvk/files/10300509/ROTTR_d3d11.log)
[ROTTR_dxgi.log](https://github.com/doitsujin/dxvk/files/103
[ROTTR_d3d11.log](https://github.com/doitsujin/dxvk/files/10300544/ROTTR_d3d11.log)
00510/ROTTR_dxgi.log)

**Comment by doitsujin** [comment]
Yeah, that's a GPU driver crash. Game should run fine on AMD/Nvidia so probably just a result of ANV not really getting as much testing as it deserves, especially since a native version exists.

**Comment by Iglu47** [comment]
just another fresh confirmation: seems no crash at Nvidia Pascal.

### Software information
Rise of the Tomb Raider [391220]
(non-Exlusive) Fullscreen 1080p, High preset

### System information
- GPU: Nvidia GTX 1080Ti
- Driver: proprietary 525.60.11
- Wine version: 7.15 (Staging + some TkG patches [no fshack])
- DXVK version: v2.0-45-g https://github.com/doitsujin/dxvk/commit/12901b52f19ea1d3eece450a009f4602b5f2adc3

### Apitrace files
- main menu (DXVK on Wine): [link to Google Drive](https://drive.google.com/file/d/1kgZuSDqkS4PC2i1bX5FYXIVK2UunkSi7/view?usp=share_link)
- in-game Benchmark (DXVK on Wine) (~11GB): [link to Google Drive](https://drive.google.com/file/d/1mCuGbIO6sbUv1GUV-5nKKTqIJqVhBHxm/view?usp=share_link)

### Log files
- d3d11.log: [ROTTR_d3d11.log](https://github.com/doitsujin/dxvk/files/10304915/ROTTR_d3d11.log)
- dxgi.log: [ROTTR_dxgi.log](https://github.com/doitsujin/dxvk/files/10304916/ROTTR_dxgi.log)

*The apitrace can be replayed on linux with [Apitrace](https://github.com/apitrace/apitrace/releases) and something like `wine64 d3dretrace.exe "C:/ROTTR.trace"` command.

**Comment by Schlaefer** [comment]
The games crashes reproducible on DXVK (and even Linux native) in the game's build-in benchmark at the end of the second benchmark scene here.

**System information**
    GPU: Intel Arc A750
    Driver: mesa-git

- [ROTTR_d3d11.log](https://github.com/doitsujin/dxvk/files/10374169/ROTTR_d3d11.log)
- [ROTTR_dxgi.log](https://github.com/doitsujin/dxvk/files/10374167/ROTTR_dxgi.log)
- [Freezing Recording.webm](https://user-images.githubusercontent.com/143224/211336990-55567e8d-7b4a-44d7-8f6a-514a77acaf85.webm)

**Comment by doitsujin** [comment]
If the native Linux version crashes then maybe report that to mesa?

We can't really fix Intel driver problems.

**Comment by Iglu47** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/8037

**Comment by Blisto91** [comment]
@github-anton Do i understand correct that this issue has been solved in mesa?
