### ISSUE TITLE
GTA IV Crash Issue.

### ISSUE THREAD

**Issue by Laksh2007** [doitsujin/dxvk#3148]
Recently my friend and I were playing Grand Theft Auto IV. The performance was so bad we thought of finding a solution and we came across DXVK. To install DXVK it was simple drag and drop d3d9.dll and dxgi.dll. After the installation we opened the game and we were greeted with a black screen with the game crashing afterwards. How do I fix this?

### Software information:
Grand Theft Auto IV downgraded to Patch 8 (1.0.8.0).
Settings used: 1366x768 Medium with sliders set at 25.

### System information
- GPU: Intel UHD 620
- Driver: 0.4
- DXVK version: 1.10.3

### Log files
- d3d9.log: Blank

**Comment by K0bin** [comment]
If d3d9.log is blank, it never even loads DXVK.

**Comment by Blisto91** [comment]
Make sure your graphics drivers and system is up to date. I don't know what 0.4 is.
If the dxvk logs are empty then it doesn't even get to initialize properly.

**Comment by Laksh2007** [comment]
That's the issue I tried the latest version which gives me D3D Fatal Error and DXVK skips it entirely. Also how do I fix this?

**Comment by K0bin** [comment]
Impossible to say without logs or anything.

**Comment by Laksh2007** [comment]
Hmmm, ok. Let me try to fix this.
