### ISSUE TITLE
Overwatch 2 - Random crashing

### ISSUE THREAD

**Issue by Nanotwerp** [doitsujin/dxvk#3152]
### Software information
Game: Overwatch 2
Settings: Max

### System information
- GPU: AMD Radeon RX 6800XT
- Driver: Mesa-git
- Wine version: 8.0-rc2
- DXVK version: Commit 12901b52f19ea1d3eece450a009f4602b5f2adc3
- OS: Fedora Rawhide

Overwatch 2 randomly crashes during gameplay and outputs this error in the terminal:
```

free(): invalid pointer
0660:err:seh:call_stack_handlers invalid frame 000000002F00DF20 (000000002EE12000-000000002EF10000)
0660:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
```

**Comment by Blisto91** [comment]
Hello.
Why do you suspect dxvk? Does it not happens without?
Also please post dxvk logs from a time it crashed

**Comment by Iglu47** [comment]
hmm Overwatch 2 was broken on wine since 7.14 https://bugs.winehq.org/show_bug.cgi?id=53765, and it does indeed seem to not crash at start on wine-8.0-rc2, however there is still no guarantee that all regressoins have been fixed.

any logs?

**Comment by Nanotwerp** [comment]
> Hello. Why do you suspect dxvk? Does it not happens without? Also please post dxvk logs from a time it crashed

Ahh, I was wrong to suspect DXVK to be causing the issue. It's a problem of Overwatch 2 [conflicting with relatively recent changes to Wine's ntdll code](https://gitlab.winehq.org/wine/wine/-/merge_requests/1152). Closing, my apologies!
