### ISSUE TITLE
ret instruction error

### ISSUE THREAD

**Issue by ecoling** [doitsujin/dxvk#3154]
We meet some strange dxbc like this.

MS DX10/11 PS Instructions:
...
label l[0]
ret
mov r0, r4
ret

when compile this code to SPIRV, the first ret instruction emit a OpFunctionEnd Instructions.
but this function isn't actually end, the OpFunctionEnd should be generated by the second ret instruction.

**Comment by Joshua-Ashton** [comment]
Please provide an example HLSL shader that can generate the problem code with FXC.

**Comment by ecoling** [comment]
[SHADER4E7219D3.zip](https://github.com/doitsujin/dxvk/files/10322945/SHADER4E7219D3.zip)
this is the dxbc binary code.

**Comment by ecoling** [comment]
> Please provide an example HLSL shader that can generate the problem code with FXC.

hi, a dxbc binary file is provided now.

**Comment by Joshua-Ashton** [comment]
Can you please provide the HLSL that generates this?

If you are generating your own DXBC, then yes, it probably doesn't work if it relies on patterns FXC will not emit.

**Comment by ecoling** [comment]
> Can you please provide the HLSL that generates this?
> 
> If you are generating your own DXBC, then yes, it probably doesn't work if it relies on patterns FXC will not emit.

What I encountered was this DXBC binary file. I don't have HLSL file. this binary file is not generate by me.

**Comment by K0bin** [comment]
Does anything use that shader?

I don't know how far we're willing to go to accommodate broken DXBC but it would at the very least be nice to know what it would fix.

**Comment by doitsujin** [comment]
We could work around this, but I'd also like to know what the use case here is other than intentionally feeding us broken code.

**Comment by doitsujin** [comment]
Also, can you please post the **unmodified** shader binary? I don't know *what* the shader file you attached is but it's most certainly not a DXBC binary, and I can't disassemble it to see the code.

**Comment by ecoling** [comment]
> Also, can you please post the **unmodified** shader binary as you would pass it to D3D11? I don't know _what_ format the shader file you attached is in but it's most certainly not a DXBC binary, so I can't even disassemble it to see the code.

We tested our code using some test shaders, and this shader caused a crash in DXBC. this shader is downloaded from the SandBox website. Attached is the asm code.
[SHADER4E7219D3.zip](https://github.com/doitsujin/dxvk/files/10334019/SHADER4E7219D3.zip)

**Comment by doitsujin** [comment]
Is there really no way for you to extract the shader binary that you're passing to your own D3D11 application? There's no way to generate this code with FXC that I know of, and there is no way to compile DXBC assembly to a binary either. I can't work with this.

If you want us to implement label/call instructions then we **need** a valid shader binary. I could try to generate a similar binary by hand but that's a significant amount of work.

**Comment by doitsujin** [comment]
https://github.com/doitsujin/dxvk/tree/dxbc-dead-code may or may not fix this. As mentioned, I'm unable to test this, and this will require significant amounts of testing especially with tessellation shaders.

**Comment by ecoling** [comment]
> https://github.com/doitsujin/dxvk/tree/dxbc-dead-code may or may not fix this. As mentioned, I'm unable to test this, and this will require significant amounts of testing especially with tessellation shaders.

Thank you, This commit of yours can solve my problem. I tested my shader locally, and it passed.

**Comment by ecoling** [comment]
> https://github.com/doitsujin/dxvk/tree/dxbc-dead-code may or may not fix this. As mentioned, I'm unable to test this, and this will require significant amounts of testing especially with tessellation shaders.

tested one crash because lack of this line:

&& ins.opClass != DxbcInstClass::Interface

**Comment by doitsujin** [comment]
what do you mean exactly? `DxbcInstClass::Interface` does not exist.
