### ISSUE TITLE
[Feature Request] SMAA/FXAA Implementation

### ISSUE THREAD

**Issue by brad86m** [doitsujin/dxvk#3160]
Vulkan does not work with Nvidia Control Panel AA solutions like FXAA, SSAA, SGSAA, and the only way to get AA on games that do not natively have it would be to use DSR to downsample the image from a higher internal resolution. The issue with this is that Nvidia uses a simple bicubic filter for downsampling, resulting in a lot of shimmering being missed. Especially on specular edges.
Combining FXAA with downsampling works really well, and the option to implement via DXVK directly, and not having to use something like Reshade, would be very welcome.

**Comment by doitsujin** [comment]
This is outside the scope of what DXVK is supposed to do.

[vkBasalt](https://github.com/DadSchoorse/vkBasalt) already does what you want.
