### ISSUE TITLE
Trainz Railroad Simulator 2004 proton experimental validation error

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3166]
When testing [Trainz](https://u7-trainz.de/downloads.html) from issue https://github.com/doitsujin/dxvk/issues/2429 i tried launching `run_directx.bat` through Proton experimental as a non Steam game with validation layers on 
```
VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation DXVK_DEBUG=validation PROTON_LOG=1 %command%
```
Like with regular Wine it crashes at start with with dxvk 2.0 together with Vulkan validation but unlike regular Wine Proton experimental throws out the error below.

```
err:   VUID-VkSubmitInfo2-semaphore-03881: 
err:   Validation Error: [ VUID-VkSubmitInfo2-semaphore-03881 ] Object 0: handle = 0x27d60e0000000019, type = VK_OBJECT_TYPE_UNKNOWN; Object 1: handle = 0x7edf8b70, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0x966cd5a6 | vkQueueSubmit2(): pSubmits[0].pSignalSemaphoreInfos[0] signal value (0x1) in VkQueue 0x7edf8b70[] must be greater than current timeline semaphore VkNonDispatchableHandle 0x27d60e0000000019[] value (0x6e696168) The Vulkan spec states: If the same semaphore is used as the semaphore member of both an element of pSignalSemaphoreInfos and pWaitSemaphoreInfos, and that semaphore is a timeline semaphore, the value member of the pSignalSemaphoreInfos element must be greater than the value member of the pWaitSemaphoreInfos element (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkSubmitInfo2-semaphore-03881)
```

### Software information
Trainz Railroad Simulator 2004. 
Version 4.0 from U7-Trainz.de (Berliner_U-Bahn_v4.1.exe)

### System information
- GPU: R9 380X
- Driver: days old mesa-git
- Wine version: proton experimental

### Log files
[trainz_d3d9.log](https://github.com/doitsujin/dxvk/files/10339549/trainz_d3d9.log)

**Comment by K0bin** [comment]
Unfortunately, I cannot reproduce it with the apitraces in the original issue.

**Comment by Blisto91** [comment]
Nevermind. Doitsujin says it's a Proton Experimental issue not dxvk directly.
