### ISSUE TITLE
[Regression] GRID 2 texture artifacts

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3168]
Since commit https://github.com/doitsujin/dxvk/commit/2a7706ba5395e197c80d59420043c06d511b8047 the game have issues with some textures. I've only tested on AMD setup's but it affects both my R9 380X and Steam Deck

<details>
  <summary>Screenshot</summary>

![Screenshot_20230104_204924](https://user-images.githubusercontent.com/47954800/210842431-0fc04570-9ce9-4c9c-b90c-d52ea9e7b15a.png)
</details>

The issue goes away again by launching with `d3d11.floatControls = False` but don't know if that is the correct thing to do.

### System information
- GPU: R9 380X
- Driver: weekish old mesa-git
- Wine version: Proton Experimental
- DXVK version: https://github.com/doitsujin/dxvk/commit/2a7706ba5395e197c80d59420043c06d511b8047 and above

Plus Steam Deck on beta branch

### Apitrace file(s)
I have made an Apitrace on Windows but the issue doesn't reproduce with it, only ingame. If you want it anyway just say so.

### Log files
[grid2_avx_d3d11.log](https://github.com/doitsujin/dxvk/files/10354265/grid2_avx_d3d11.log)
[grid2_avx_dxgi.log](https://github.com/doitsujin/dxvk/files/10354268/grid2_avx_dxgi.log)

(Ignore the `info:    dxgi.customVendorId = 8086`. I forgot to take it out and is unrelated)

Edit: Also noticed later it can cause the screen to go mostly black or white when driving the map above

**Comment by Iglu47** [comment]
this seems to show up as a UI issue for nvidia during a race (doesn't reproduce on apitrace either).

<details><summary>screenshot - "white artifacts during race"</summary>
<p>

![grid2_nvidia](https://user-images.githubusercontent.com/25866099/210869105-8991ea20-ddde-4c68-bc3d-db62d4f46766.png)

</p>
</details>

For vanilla/staging Wine Windows d3dcompilers helps, but I don't know why dlls workaround doesn't work for Proton (`d3d11.floatControls = False` still helps).

@Blisto91 need tests with vanilla/staging and windows d3dcompilers

**Comment by Blisto91** [comment]
@Blisto91 you Blisto you lazy bum. Retest this issue ASAP!

**Comment by Blisto91** [comment]
> Yo Blisto you lazy bum.

No u!
Gotem


The issue seems to have been fixed in Proton 8. I can still reproduce by using the Proton 7 Experimental beta branch, but not with 8. If i take the dxvk dll's from 7 Experimental and put into 8 it is also still fine.
@Iglu47 are you able to confirm that the issue is no more?

**Comment by Iglu47** [comment]
> @Iglu47 are you able to confirm that the issue is no more?

yea, game hud during race no longer broken on proton8 for nvidia

https://github.com/doitsujin/dxvk/assets/25866099/a3f5284f-6701-46cc-acc0-7f1be9ada8f0

#### System information
- GPU: NVIDIA GeForce GTX 1080 Ti (Pascal)
- Driver: NVIDIA 525.116.04 (proprietary)
- Wine version: proton-8.0-2d
- DXVK version: DXVK supplied with Proton 8.0-2  (https://github.com/doitsujin/dxvk/commit/caf31033d711460e86781b16a4d9b0f41fa9e817)

**Comment by Blisto91** [comment]
Thanks! :+1:
