### ISSUE TITLE
Shutdown crash after storing private references to context shaders

### ISSUE THREAD

**Issue by rlocatti-nv** [doitsujin/dxvk#3169]
Starting with commit 8758bcedae4cd95827acb801be0aba2ae3edc3f1 a few applications started crashing on shutdown inside `RtlAcquireSRWLockExclusive`. Reverting this commit fixes the issue.

Here is a backtrace of the crash:
```
 	ntdll.dll!RtlAcquireSRWLockExclusive()	Unknown
>	[Inline Frame] d3d11.dll!dxvk::mutex::lock() Line 182	C++
 	[Inline Frame] d3d11.dll!std::lock_guard<dxvk::mutex>::{ctor}(dxvk::mutex &) Line 427	C++
 	[Inline Frame] d3d11.dll!dxvk::DxvkMemoryAllocator::free(const dxvk::DxvkMemory &) Line 443	C++
 	d3d11.dll!dxvk::DxvkMemory::free() Line 56	C++
 	d3d11.dll!dxvk::DxvkMemory::~DxvkMemory() Line 50	C++
 	d3d11.dll!dxvk::DxvkImage::`scalar deleting destructor'(unsigned int)	C++
 	[Inline Frame] d3d11.dll!dxvk::D3D11Texture2D::{dtor}() Line 1175	C++
 	d3d11.dll!dxvk::D3D11Texture2D::`scalar deleting destructor'(unsigned int)	C++
 	[Inline Frame] d3d11.dll!dxvk::ComObject<ID3D11Texture2D1>::ReleasePrivate() Line 67	C++
 	d3d11.dll!dxvk::D3D11Texture2D::Release() Line 1203	C++
 	Ashes_DX11.exe!...()	Unknown
```

### Software information
Reproduced on an internal Ashes of the Singularity frame capture. It also happens on other titles.
I can try reproducing it in a real application if the bug is not obvious.

### System information
- GPU: NVIDIA GeForce RTX 3060 Ti
- Driver: 527.56.0
- Wine version: Windows 11
- DXVK version: f94b42f23f34cc92c9115764f800292e6d7a2c50

### Log files
- d3d9.log: [Ashes_DX11_d3d9.log](https://github.com/doitsujin/dxvk/files/10355729/Ashes_DX11_d3d9.log)
- d3d11.log: [Ashes_DX11_d3d11.log](https://github.com/doitsujin/dxvk/files/10355731/Ashes_DX11_d3d11.log)
- dxgi.log: [Ashes_DX11_dxgi.log](https://github.com/doitsujin/dxvk/files/10355733/Ashes_DX11_dxgi.log)

**Comment by doitsujin** [comment]
The reason why we don't crash without that commit is most likely because we're straight-up leaking the D3D11 device.

What exactly is happening anyway? This sounds like the underlying DXVK device already got destroyed by the time the texture gets destroyed (which however should hold a strong reference to the D3D11 device), so this should be impossible, not sure what to make of this.
