### ISSUE TITLE
Suggestion: Registry or .ini file for settings

### ISSUE THREAD

**Issue by SveSop** [doitsujin/dxvk#317]
Probably been suggested before, but seeing as there are some game/app specific things being added every now and then in the source code as a "setting", having this in either registry or in a settings.ini file would be highly beneficial especially for testing.

eg. [https://github.com/doitsujin/dxvk/commit/01147492d5d8a27fff9a329faa43b9bf77ce1e07](https://github.com/doitsujin/dxvk/commit/01147492d5d8a27fff9a329faa43b9bf77ce1e07) is a specific setting for ManiaPlanet.exe. 
There was another a bit back too i dont remember atm.

I see something being done with [https://github.com/doitsujin/dxvk/commit/e53cb72e39610915a4fce49253e61635369281c4](https://github.com/doitsujin/dxvk/commit/e53cb72e39610915a4fce49253e61635369281c4) aswell, but was not immediately clear how this is meant to be used.

As i said.. probably something that has been talked about, and is being considered, but what is the best solution tho? Registry setting, or .ini file? And if so.. where should the .ini file be? c:\windows? Game folder? What do ppl think is the most convenient? :)

**Comment by baka0815** [comment]
I think registry settings in ``\HKEY_LOCAL_MACHINE\SOFTWARE\DXVK\<Name of .exe>`` would be a nice way to do this.
This way there could be multiple settings under this key like ``ForceTex2DArray REG_DWORD 0x1``.

**Comment by SveSop** [comment]
And perhaps a "Default" key if you want something to be set for all running apps, unless a override in the <name of .exe> key.

**Comment by ssorgatem** [comment]
I'm not a fan of dealing with registry keys, so I'd prefer something like an INI file... maybe in the same location the log files would be generated. This would also allow different settings for games/apps sharing the same executable name.

**Comment by pchome** [comment]
One here for `DXVK.ini` (or so):
* It's a bit easier to edit text file and/or share between WINE prefixes
* It can contain comments to clarify what each options for
* It can contain multiple sections
* It's easier to switch options by commenting/uncommenting (`;`) them 
* It have simple format widely known to most gamers

```ini
[default]
; PossibleOption explanation text
; PossibleOptionDefault=1

; Explanation text
ForceTex2DArray=0

[Name of .exe]
ForceTex2DArray=1
LogLevel=debug
```

Search path can be set to `C:\windows` (system root variable (?)), than to game root directory, so users can have either one config for each game in prefix or per-game config files.

**Comment by pchome** [comment]
Also [here](https://github.com/brofield/simpleini) (simpleini) is the link I have posted before in another issue.
I'm not looked further than README, but it looks like single header file `SimpleIni.h` with simple and powerful API. This can save some time.

**Comment by SveSop** [comment]
Did not think about that @pchome Having comments (if its doable) is quite useful. I tend to make comments in my scripts just if i change a setting or whatever, and forget what it did.. so that is absolutely useful.

Do not like the "per game.ini" tho, as having multiple .ini files could be a mess.. Having a system .ini would be nice, and easy to backup incase you need to recreate the prefix :)

**Comment by ssorgatem** [comment]
That all seems much easier to handle with an INI file with dedicated driver sections.

Driver, and not vendor, because one vendor can have more than one different driver (e.g. AMD: Windows driver vs AMDVLK vs RADV).

**Comment by pchome** [comment]
@doitsujin 
Is there any plans/thoughts for this issue?

This should also fix some problems with #60 / #268 , so I'm asking is it worth to spend time on fixing build problems (supposing env vars will not be used anymore)? 
I'll better try to help resolve this issue, if this welcomed and you have final view what should it be ( `.ini`/`tool`/[imgui](https://github.com/ocornut/imgui) (is it possible ?) /... ).

**Comment by doitsujin** [comment]
@pchome yes, there are plans to add support for configuration files, but it has low priority and I have my hands full at the moment. I don't really want to have to deal with this right now.

**Comment by doitsujin** [comment]
Latest `master` adds support for a configuration file. Documentation is available [https://github.com/doitsujin/dxvk/wiki/Configuration](on the Wiki).
