### ISSUE TITLE
[d3d9] [OMSI 2] [x86] When trying to switch to drivers view (with any bus) the game crashes.

### ISSUE THREAD

**Issue by Tonyy1** [doitsujin/dxvk#3172]
Hello, I recently switched from v1.10.1 to v2.0, in terms of hoping that the mirror reflection issues with MSAA enabled were finally fixed, and suddenly, the game crashes every time I spawn a bus and try to switch to a cockpit view. After many unsuccessful attempts to try and make it work by fiddling with various settings, even trying it with MSAA disabled, I then tried to roll back to v1.10.3, with out-of-box settings, and everything worked just fine.

### Software information
OMSI 2 + "out-of-box" DXVK settings.

### System information
- GPU: Nvidia GeForce RTX 3060 - Laptop
- Driver: 527.56
- DXVK version: 2.0 (32-bit)
- Vulkan: 1.3.224

### Apitrace file(s)
[Omsi.zip](https://drive.google.com/file/d/1qisA16305zBLuv5IjS7cjX9uN5MgGPc8/view)

### Log files
[Omsi_d3d9.log](https://github.com/doitsujin/dxvk/files/10366130/Omsi_d3d9.log)

**Comment by Blisto91** [comment]
I own the game myself so i can test here later, but in the meantime would you be able to make a apitrace of the actions that make it crash together with dxvk? (the apitrace is without dxvk so it won't crash when making it)

**Comment by Blisto91** [comment]
The trace seems to crash a while in on Linux wine with or without dxvk. But thx anyway.
Will try to reproduce ingame.

**Comment by Blisto91** [comment]
So I've not been able to reproduce a crash on Linux on my AMD setup when i switch to drivers view. Haven't messed with graphics settings yet.

<details>
  <summary>Screenshot</summary>

![Screenshot_20230108_171142](https://user-images.githubusercontent.com/47954800/211207162-0f545260-48d0-46a4-bffb-9dafdb7ce117.png)
</details>

**Comment by Tonyy1** [comment]
Weird. I'll try to update Vulkan and Nvidia drivers tomorrow. I really hope this has nothing to do with me running Reshade as well. I'll update you on the situation.

**Comment by Blisto91** [comment]
Reshade could maybe cause issues so might be worth trying without. I will do a test on Nvidia Windows when i have the time

**Comment by Blisto91** [comment]
I've tested on Windows 10 with a GeForce 960 with same driver as you and dxvk 2.0.
But still haven't been able to make it crash

**Comment by Tonyy1** [comment]
Hello, as suspected, the problem was with Reshade being outdated. I updated it and haven't experienced any crashes. Thank you for your time and dedication.
