### ISSUE TITLE
Sekiro regression in 1.10

### ISSUE THREAD

**Issue by Keelhauled** [doitsujin/dxvk#3179]
There seems to be some sort of regression in dxvk 1.10 in regards to sekiro in the form of stuttering. Specifically at least 1.10, 1.10.3 and 2.0 have the problem but 1.9.4 doesn't. Relevant proton issue https://github.com/ValveSoftware/Proton/issues/2444.

### System information
- GPU: Nvidia 2070
- Driver: 525.78.01

**Comment by mbriar** [comment]
From a glance, all the reports i've seen about it are on nvidia.

**Comment by Keelhauled** [comment]
The stuttering happens everywhere for me.

**Comment by Keelhauled** [comment]
I was thinking of trying out some of the commits between 1.10 and 1.9.4 but sadly the github actions artifacts have expired. Is there any other source of those old builds?
Also here are my full specs https://gist.github.com/Keelhauled/0411e93dfdb7ab976fb3acd50fb1b314

**Comment by doitsujin** [comment]
Managed to reproduce this on my laptop and bisected it to 26381fd5df976cc20ab5a5ffc55143067e1e4972.

I don't understand why this only affects Nvidia, this makes zero sense to me right now. There's nothing wrong with this commit and it does not have any unwanted side effect in this game.

**Comment by doitsujin** [comment]
So after a bit more digging it turns out that there's frequent memory allocations now because the game is weird.

This branch fixes it for me: https://github.com/doitsujin/dxvk/tree/sekiro-memory-workaround

**Comment by Keelhauled** [comment]
Thank you, that seems to fix it perfectly.

**Comment by fuyuki94370** [comment]
I was having the same problem, and want to add that https://github.com/doitsujin/dxvk/tree/sekiro-memory-workaround fixed it for me as well. Thanks.
