### ISSUE TITLE
[Regression] Jade Empire: Special Edition (7110) videos play incorrectly

### ISSUE THREAD

**Issue by alasky17** [doitsujin/dxvk#3182]
Jade Empire: Special Edition no longer plays videos correctly.  This can be easily seen by just launching the game and looking at the videos that play before the main menu. See screenshots posted by @legluondunet on the github issue where this was first reported: https://github.com/ValveSoftware/Proton/issues/2112#issuecomment-1365141049 ![jade-good-video](https://user-images.githubusercontent.com/40211296/211895246-c9ce0f85-365d-42b8-9a42-9ae2658ee223.png)
![jade-bad-video](https://user-images.githubusercontent.com/40211296/211895253-062e3486-017d-4990-8bae-7a4bfdcb8c45.png)

### Software information
Jade Empire: Special Edition (7110)

### System information
- GPU: AMD Radeon RTX 570 Series 
- Driver: 22.3.2   Vulkan 1.3.230
- Wine version: Regression between Proton 5.0-10 and Proton 5.13-1
- DXVK version: Regression between [2e378257ea88827f0a4e55a132895130519184d3] [meta] Release 1.7 (good) and 4439e8adb358c0c4b7ae65aae09acc6f521a7321 [dxvk_config] Add new dxvk_config library (bad)  
My builds weren't completing properly, so I was unable to narrow it down further.

### Apitrace file(s)
- Unfortunately I was unable to get an apitrace, even with the new technique :/ 

### Log files
- d3d9.log: [JadeEmpire_d3d9.log](https://github.com/doitsujin/dxvk/files/10395157/JadeEmpire_d3d9.log)

**Comment by Blisto91** [comment]
Thanks for the report.
I can try to see if i am able to get a apitrace of the issue here later.

**Comment by Blisto91** [comment]
I have bisected this to be either
https://github.com/doitsujin/dxvk/commit/2bf9f298af776a0ac44f9f53b27956ae3da03b99
or
https://github.com/doitsujin/dxvk/commit/9fe1b9d03ff89faeb210a577baad4aee0e49fedb

I can't test the first one directly as the game will crash when the videos or supposed to start. The second one is the commit right after and have the broken videos

**Comment by Blisto91** [comment]
Managed to trace the game but the issue just gets baked into it so i'm uploading a working made with 1.7 and a broken made with 1.7.1.

https://mega.nz/file/V9JxALQD#CsgYjEhTN5S-NuUnGYhgrVZNnmJEcUugXowCvvkdPPQ

**Comment by K0bin** [comment]
The issue here seems to be how the data for the format converter is packed. The format is YUY.

**Comment by Blisto91** [comment]
This appears to work again when changing <https://github.com/doitsujin/dxvk/blob/1482715fd1f1c310cd183d61f9039ff11425eee4/src/d3d9/d3d9_format.cpp#L196>
to `VK_FORMAT_G8B8G8R8_422_UNORM`, but i don't know if that is correct so just posting it here on the issue so it doesn't get lost before it's looked at.
Same for https://github.com/doitsujin/dxvk/issues/3189

**Comment by legluondunet** [comment]
just tested with Proton experimental, the cinematics played nicely, bravo!
