### ISSUE TITLE
Fail on compiling

### ISSUE THREAD

**Issue by Neptuneia** [doitsujin/dxvk#3185]
[178/290] Compiling C++ object src/d3d11/d3d11.dll.p/d3d11_blend.cpp.obj
FAILED: src/d3d11/d3d11.dll.p/d3d11_blend.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/d3d11/d3d11.dll.p -Isrc/d3d11 -I../../dxvk/src/d3d11 -I../../dxvk/include -I../../dxvk/include/vulkan/include -I../../dxvk/include/spirv/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/d3d11/d3d11.dll.p/d3d11_blend.cpp.obj -MF src/d3d11/d3d11.dll.p/d3d11_blend.cpp.obj.d -o src/d3d11/d3d11.dll.p/d3d11_blend.cpp.obj -c ../../dxvk/src/d3d11/d3d11_blend.cpp
In file included from ../../dxvk/src/d3d11/d3d11_device.h:19,
                 from ../../dxvk/src/d3d11/d3d11_blend.cpp:2:
../../dxvk/src/d3d11/d3d11_features.h:84:5: error: ‘D3D11_FEATURE_DATA_D3D11_OPTIONS5’ does not name a type; did you mean ‘D3D11_FEATURE_DATA_D3D11_OPTIONS4’?
   84 |     D3D11_FEATURE_DATA_D3D11_OPTIONS5                 m_d3d11Options5               = { };
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_FEATURE_DATA_D3D11_OPTIONS4
../../dxvk/src/d3d11/d3d11_features.h:104:5: error: ‘D3D11_SHARED_RESOURCE_TIER’ does not name a type; did you mean ‘D3D11_TILED_RESOURCES_TIER’?
  104 |     D3D11_SHARED_RESOURCE_TIER DetermineSharedResourceTier(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_TILED_RESOURCES_TIER
[179/290] Compiling C++ object src/d3d11/d3d11.dll.p/d3d11_annotation.cpp.obj
FAILED: src/d3d11/d3d11.dll.p/d3d11_annotation.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/d3d11/d3d11.dll.p -Isrc/d3d11 -I../../dxvk/src/d3d11 -I../../dxvk/include -I../../dxvk/include/vulkan/include -I../../dxvk/include/spirv/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/d3d11/d3d11.dll.p/d3d11_annotation.cpp.obj -MF src/d3d11/d3d11.dll.p/d3d11_annotation.cpp.obj.d -o src/d3d11/d3d11.dll.p/d3d11_annotation.cpp.obj -c ../../dxvk/src/d3d11/d3d11_annotation.cpp
In file included from ../../dxvk/src/d3d11/d3d11_device.h:19,
                 from ../../dxvk/src/d3d11/d3d11_state_object.h:3,
                 from ../../dxvk/src/d3d11/d3d11_context_imm.h:8,
                 from ../../dxvk/src/d3d11/d3d11_annotation.cpp:3:
../../dxvk/src/d3d11/d3d11_features.h:84:5: error: ‘D3D11_FEATURE_DATA_D3D11_OPTIONS5’ does not name a type; did you mean ‘D3D11_FEATURE_DATA_D3D11_OPTIONS4’?
   84 |     D3D11_FEATURE_DATA_D3D11_OPTIONS5                 m_d3d11Options5               = { };
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_FEATURE_DATA_D3D11_OPTIONS4
../../dxvk/src/d3d11/d3d11_features.h:104:5: error: ‘D3D11_SHARED_RESOURCE_TIER’ does not name a type; did you mean ‘D3D11_TILED_RESOURCES_TIER’?
  104 |     D3D11_SHARED_RESOURCE_TIER DetermineSharedResourceTier(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_TILED_RESOURCES_TIER
[180/290] Compiling C++ object src/d3d11/d3d11.dll.p/d3d11_buffer.cpp.obj
FAILED: src/d3d11/d3d11.dll.p/d3d11_buffer.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/d3d11/d3d11.dll.p -Isrc/d3d11 -I../../dxvk/src/d3d11 -I../../dxvk/include -I../../dxvk/include/vulkan/include -I../../dxvk/include/spirv/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/d3d11/d3d11.dll.p/d3d11_buffer.cpp.obj -MF src/d3d11/d3d11.dll.p/d3d11_buffer.cpp.obj.d -o src/d3d11/d3d11.dll.p/d3d11_buffer.cpp.obj -c ../../dxvk/src/d3d11/d3d11_buffer.cpp
In file included from ../../dxvk/src/d3d11/d3d11_device.h:19,
                 from ../../dxvk/src/d3d11/d3d11_buffer.cpp:3:
../../dxvk/src/d3d11/d3d11_features.h:84:5: error: ‘D3D11_FEATURE_DATA_D3D11_OPTIONS5’ does not name a type; did you mean ‘D3D11_FEATURE_DATA_D3D11_OPTIONS4’?
   84 |     D3D11_FEATURE_DATA_D3D11_OPTIONS5                 m_d3d11Options5               = { };
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_FEATURE_DATA_D3D11_OPTIONS4
../../dxvk/src/d3d11/d3d11_features.h:104:5: error: ‘D3D11_SHARED_RESOURCE_TIER’ does not name a type; did you mean ‘D3D11_TILED_RESOURCES_TIER’?
  104 |     D3D11_SHARED_RESOURCE_TIER DetermineSharedResourceTier(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_TILED_RESOURCES_TIER
[181/290] Compiling C++ object src/d3d11/d3d11.dll.p/d3d11_class_linkage.cpp.obj
FAILED: src/d3d11/d3d11.dll.p/d3d11_class_linkage.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/d3d11/d3d11.dll.p -Isrc/d3d11 -I../../dxvk/src/d3d11 -I../../dxvk/include -I../../dxvk/include/vulkan/include -I../../dxvk/include/spirv/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/d3d11/d3d11.dll.p/d3d11_class_linkage.cpp.obj -MF src/d3d11/d3d11.dll.p/d3d11_class_linkage.cpp.obj.d -o src/d3d11/d3d11.dll.p/d3d11_class_linkage.cpp.obj -c ../../dxvk/src/d3d11/d3d11_class_linkage.cpp
In file included from ../../dxvk/src/d3d11/d3d11_device.h:19,
                 from ../../dxvk/src/d3d11/d3d11_class_linkage.cpp:2:
../../dxvk/src/d3d11/d3d11_features.h:84:5: error: ‘D3D11_FEATURE_DATA_D3D11_OPTIONS5’ does not name a type; did you mean ‘D3D11_FEATURE_DATA_D3D11_OPTIONS4’?
   84 |     D3D11_FEATURE_DATA_D3D11_OPTIONS5                 m_d3d11Options5               = { };
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_FEATURE_DATA_D3D11_OPTIONS4
../../dxvk/src/d3d11/d3d11_features.h:104:5: error: ‘D3D11_SHARED_RESOURCE_TIER’ does not name a type; did you mean ‘D3D11_TILED_RESOURCES_TIER’?
  104 |     D3D11_SHARED_RESOURCE_TIER DetermineSharedResourceTier(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_TILED_RESOURCES_TIER
[182/290] Compiling C++ object src/d3d11/d3d11.dll.p/d3d11_cmdlist.cpp.obj
FAILED: src/d3d11/d3d11.dll.p/d3d11_cmdlist.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/d3d11/d3d11.dll.p -Isrc/d3d11 -I../../dxvk/src/d3d11 -I../../dxvk/include -I../../dxvk/include/vulkan/include -I../../dxvk/include/spirv/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/d3d11/d3d11.dll.p/d3d11_cmdlist.cpp.obj -MF src/d3d11/d3d11.dll.p/d3d11_cmdlist.cpp.obj.d -o src/d3d11/d3d11.dll.p/d3d11_cmdlist.cpp.obj -c ../../dxvk/src/d3d11/d3d11_cmdlist.cpp
In file included from ../../dxvk/src/d3d11/d3d11_device.h:19,
                 from ../../dxvk/src/d3d11/d3d11_cmdlist.cpp:2:
../../dxvk/src/d3d11/d3d11_features.h:84:5: error: ‘D3D11_FEATURE_DATA_D3D11_OPTIONS5’ does not name a type; did you mean ‘D3D11_FEATURE_DATA_D3D11_OPTIONS4’?
   84 |     D3D11_FEATURE_DATA_D3D11_OPTIONS5                 m_d3d11Options5               = { };
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_FEATURE_DATA_D3D11_OPTIONS4
../../dxvk/src/d3d11/d3d11_features.h:104:5: error: ‘D3D11_SHARED_RESOURCE_TIER’ does not name a type; did you mean ‘D3D11_TILED_RESOURCES_TIER’?
  104 |     D3D11_SHARED_RESOURCE_TIER DetermineSharedResourceTier(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_TILED_RESOURCES_TIER
[183/290] Compiling C++ object src/d3d11/d3d11.dll.p/d3d11_context_def.cpp.obj
FAILED: src/d3d11/d3d11.dll.p/d3d11_context_def.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/d3d11/d3d11.dll.p -Isrc/d3d11 -I../../dxvk/src/d3d11 -I../../dxvk/include -I../../dxvk/include/vulkan/include -I../../dxvk/include/spirv/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/d3d11/d3d11.dll.p/d3d11_context_def.cpp.obj -MF src/d3d11/d3d11.dll.p/d3d11_context_def.cpp.obj.d -o src/d3d11/d3d11.dll.p/d3d11_context_def.cpp.obj -c ../../dxvk/src/d3d11/d3d11_context_def.cpp
In file included from ../../dxvk/src/d3d11/d3d11_device.h:19,
                 from ../../dxvk/src/d3d11/d3d11_context_def.cpp:2:
../../dxvk/src/d3d11/d3d11_features.h:84:5: error: ‘D3D11_FEATURE_DATA_D3D11_OPTIONS5’ does not name a type; did you mean ‘D3D11_FEATURE_DATA_D3D11_OPTIONS4’?
   84 |     D3D11_FEATURE_DATA_D3D11_OPTIONS5                 m_d3d11Options5               = { };
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_FEATURE_DATA_D3D11_OPTIONS4
../../dxvk/src/d3d11/d3d11_features.h:104:5: error: ‘D3D11_SHARED_RESOURCE_TIER’ does not name a type; did you mean ‘D3D11_TILED_RESOURCES_TIER’?
  104 |     D3D11_SHARED_RESOURCE_TIER DetermineSharedResourceTier(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_TILED_RESOURCES_TIER
[184/290] Compiling C++ object src/d3d11/d3d11.dll.p/d3d11_context_ext.cpp.obj
FAILED: src/d3d11/d3d11.dll.p/d3d11_context_ext.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/d3d11/d3d11.dll.p -Isrc/d3d11 -I../../dxvk/src/d3d11 -I../../dxvk/include -I../../dxvk/include/vulkan/include -I../../dxvk/include/spirv/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/d3d11/d3d11.dll.p/d3d11_context_ext.cpp.obj -MF src/d3d11/d3d11.dll.p/d3d11_context_ext.cpp.obj.d -o src/d3d11/d3d11.dll.p/d3d11_context_ext.cpp.obj -c ../../dxvk/src/d3d11/d3d11_context_ext.cpp
In file included from ../../dxvk/src/d3d11/d3d11_device.h:19,
                 from ../../dxvk/src/d3d11/d3d11_context_ext.cpp:5:
../../dxvk/src/d3d11/d3d11_features.h:84:5: error: ‘D3D11_FEATURE_DATA_D3D11_OPTIONS5’ does not name a type; did you mean ‘D3D11_FEATURE_DATA_D3D11_OPTIONS4’?
   84 |     D3D11_FEATURE_DATA_D3D11_OPTIONS5                 m_d3d11Options5               = { };
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_FEATURE_DATA_D3D11_OPTIONS4
../../dxvk/src/d3d11/d3d11_features.h:104:5: error: ‘D3D11_SHARED_RESOURCE_TIER’ does not name a type; did you mean ‘D3D11_TILED_RESOURCES_TIER’?
  104 |     D3D11_SHARED_RESOURCE_TIER DetermineSharedResourceTier(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_TILED_RESOURCES_TIER
[185/290] Compiling C++ object src/d3d11/d3d11.dll.p/d3d11_context_imm.cpp.obj
FAILED: src/d3d11/d3d11.dll.p/d3d11_context_imm.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/d3d11/d3d11.dll.p -Isrc/d3d11 -I../../dxvk/src/d3d11 -I../../dxvk/include -I../../dxvk/include/vulkan/include -I../../dxvk/include/spirv/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/d3d11/d3d11.dll.p/d3d11_context_imm.cpp.obj -MF src/d3d11/d3d11.dll.p/d3d11_context_imm.cpp.obj.d -o src/d3d11/d3d11.dll.p/d3d11_context_imm.cpp.obj -c ../../dxvk/src/d3d11/d3d11_context_imm.cpp
In file included from ../../dxvk/src/d3d11/d3d11_device.h:19,
                 from ../../dxvk/src/d3d11/d3d11_state_object.h:3,
                 from ../../dxvk/src/d3d11/d3d11_context_imm.h:8,
                 from ../../dxvk/src/d3d11/d3d11_context_imm.cpp:2:
../../dxvk/src/d3d11/d3d11_features.h:84:5: error: ‘D3D11_FEATURE_DATA_D3D11_OPTIONS5’ does not name a type; did you mean ‘D3D11_FEATURE_DATA_D3D11_OPTIONS4’?
   84 |     D3D11_FEATURE_DATA_D3D11_OPTIONS5                 m_d3d11Options5               = { };
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_FEATURE_DATA_D3D11_OPTIONS4
../../dxvk/src/d3d11/d3d11_features.h:104:5: error: ‘D3D11_SHARED_RESOURCE_TIER’ does not name a type; did you mean ‘D3D11_TILED_RESOURCES_TIER’?
  104 |     D3D11_SHARED_RESOURCE_TIER DetermineSharedResourceTier(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_TILED_RESOURCES_TIER
[186/290] Compiling C++ object src/d3d11/d3d11.dll.p/d3d11_context.cpp.obj
FAILED: src/d3d11/d3d11.dll.p/d3d11_context.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/d3d11/d3d11.dll.p -Isrc/d3d11 -I../../dxvk/src/d3d11 -I../../dxvk/include -I../../dxvk/include/vulkan/include -I../../dxvk/include/spirv/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -msse -msse2 -msse3 -mfpmath=sse -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-unused-parameter -Wno-cast-function-type -Wno-unused-const-variable -Wno-missing-braces -DNOMINMAX -D_WIN32_WINNT=0xa00 -DDXVK_WSI_WIN32 -MD -MQ src/d3d11/d3d11.dll.p/d3d11_context.cpp.obj -MF src/d3d11/d3d11.dll.p/d3d11_context.cpp.obj.d -o src/d3d11/d3d11.dll.p/d3d11_context.cpp.obj -c ../../dxvk/src/d3d11/d3d11_context.cpp
In file included from ../../dxvk/src/d3d11/d3d11_device.h:19,
                 from ../../dxvk/src/d3d11/d3d11_state_object.h:3,
                 from ../../dxvk/src/d3d11/d3d11_context_imm.h:8,
                 from ../../dxvk/src/d3d11/d3d11_context.cpp:5:
../../dxvk/src/d3d11/d3d11_features.h:84:5: error: ‘D3D11_FEATURE_DATA_D3D11_OPTIONS5’ does not name a type; did you mean ‘D3D11_FEATURE_DATA_D3D11_OPTIONS4’?
   84 |     D3D11_FEATURE_DATA_D3D11_OPTIONS5                 m_d3d11Options5               = { };
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_FEATURE_DATA_D3D11_OPTIONS4
../../dxvk/src/d3d11/d3d11_features.h:104:5: error: ‘D3D11_SHARED_RESOURCE_TIER’ does not name a type; did you mean ‘D3D11_TILED_RESOURCES_TIER’?
  104 |     D3D11_SHARED_RESOURCE_TIER DetermineSharedResourceTier(
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     D3D11_TILED_RESOURCES_TIER
[187/290] Compiling C++ object src/d3d11/d3d11.dll.p/d3d11_cuda.cpp.obj
ninja: build stopped: subcommand failed.

**pardon my formatting for the text, im not too sure how to format text like that as im new to using github**

**Comment by Joshua-Ashton** [comment]
Your MinGW is out of date.
