### ISSUE TITLE
[d3d9] Sid Meier's Pirates! - borked video playback

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#3189]
Video playback is broken with dxvk, works fine with WineD3D. I've captured a trace, but what I'm actually seeing is not visible during replay (it does raise some warnings though - hopefully that's enough to figure out what's going on), so here's [a video as well](https://drive.google.com/file/d/17Lol3kxQTvxsldFCoggWjj87gkuCR_99/view?usp=share_link).

### Software information
Sid Meier's Pirates! (GOG version).

### System information
- GPU: Nvidia GTX 3060
- Driver: 525.60.11
- Wine version: Wine Staging 7.22
- DXVK version: af05265

### Apitrace file(s)
[Pirates!.trace.tar.xz](https://drive.google.com/file/d/1Jn0q1qGliQo0ylKq4gmaKMKYcplikVGL/view?usp=share_link)

### Log files
- d3d9.log: [Pirates!_d3d9.log](https://github.com/doitsujin/dxvk/files/10420967/Pirates._d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by K0bin** [comment]
What do you mean "is broken"? Is it a black screen? Does it show garbage data? Does it crash?

**Comment by Blisto91** [comment]
The videos have garbled colors.
<details>
  <summary>Screenshot</summary>

![Screenshot_20230115_202411](https://user-images.githubusercontent.com/47954800/212562609-73b5b653-f8d6-4cd0-a9d2-e479e4f99498.png)
</details>

Same as https://github.com/doitsujin/dxvk/issues/3182 it's regression with either
https://github.com/doitsujin/dxvk/commit/2bf9f298af776a0ac44f9f53b27956ae3da03b99
or
https://github.com/doitsujin/dxvk/commit/9fe1b9d03ff89faeb210a577baad4aee0e49fedb

First one is a crash and second one shows the issue.
