### ISSUE TITLE
NieR Automata: Lighting artifacts

### ISSUE THREAD

**Issue by AniLeo** [doitsujin/dxvk#319]
Description: When Ingame looking at areas with direct lighting, artifacts appear all over the place. When looking at a shadow spot which doesn't have any direct lighting, the artifacts don't show (it happens with or without Fullscreen Mode, I just happened to be on Windowed mode when taking the second screenshot).

![bug](https://user-images.githubusercontent.com/10283761/39157118-447d3856-4751-11e8-94ee-77d44632d8ba.png)
![no-bug](https://user-images.githubusercontent.com/10283761/39157152-7b84c986-4751-11e8-86ac-47f84a692e63.png)

@kd-11 also managed to get this artifact output before when developing with Vulkan for RPCS3 and mentioned that it was a memory barrier issue, if that helps narrowing down the issue.

### Software information
NieR Automata via Wine Steam
Tested several graphical settings combinations including minimal, none fix the issue

### System information
- GPU: GeForce 960M
- Driver: Proprietary NVIDIA 387.34
- Wine version: wine-3.6 Staging (also tested on wine-3.5 Staging)
- DXVK version: 0.42 (also tested on 0.41, unfortunately I'm not able to build the project to check the latest git as well)

### Apitrace file(s)
I will provide one as soon as I'm able to, need someone to indicate how to set Wine back to using the default D3D11 DLLs so I can capture it as I haven't found a way to do so

### Log files
- d3d11.log: [NieRAutomata_d3d11.log](https://github.com/doitsujin/dxvk/files/1940268/NieRAutomata_d3d11.log)
- dxgi.log: [NieRAutomata_dxgi.log](https://github.com/doitsujin/dxvk/files/1940267/NieRAutomata_dxgi.log)

**Comment by doitsujin** [comment]
You might want to update your driver, that version is ancient and known to have issues with DXVK.

**Comment by AniLeo** [comment]
Thanks for the heads up, nvidia-387 is actually the latest drivers Ubuntu 17.10 offers so I didn't even notice there were new ones. 
I have now added the ppa:graphics-drivers/ppa and am installing nvidia-396, will report back as soon everything is updated.

**Comment by libcg** [comment]
`__GL_NextGenCompiler=0`

**Comment by AniLeo** [comment]
Graphical Issues are fixed on nvidia-396
`__GL_NextGenCompiler=0` also provides a speed boost over not using it, bringing performance to about the same as on Windows (suffering from the same slow motion issue you mentioned on the linked thread above becuase it's a 960M but that's the card being well below game requirements)

Anyways, DXVK looking really cool, hoping that Special K injection will eventually work under Wine for that sweet performance boost, already finished the game on my Windows Desktop once and it's truly deserving of the love it's receiving :smile: 

Closing the issue as solved
