### ISSUE TITLE
NVIDIA Profile Inspector settings are ignored by DXVK (Windows)

### ISSUE THREAD

**Issue by softsoundd** [doitsujin/dxvk#3192]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Game: Mirror's Edge (2008)
NVIDIA Profile Inspector changes: Antialiasing Transparency = 8x

### System information
- GPU: RTX 3080
- Driver: 528.02
- Wine version: N/A
- DXVK version: 2.0

Changes made in Profile Inspector are not reflected in the game, in my case, setting the supersampling setting for transparent textures. Verified that these changes work when the game is run without DXVK.

**Comment by mbriar** [comment]
This setting will only have an effect if you actually use nvidia's d3d9 driver, it won't work when running on the vulkan driver and thus won't work with DXVK. There is nothing DXVK can do about it and DXVK doesn't interact nor knows anything about nvidia profile settings in the first place.

**Comment by doitsujin** [comment]
That pretty much sums it up.

DXVK has its own set of [configuration options](https://github.com/doitsujin/dxvk/wiki/Configuration) that can be used, including full supersampling if you use a [current development build](https://github.com/doitsujin/dxvk/actions).

**Comment by softsoundd** [comment]
This is good to know, thanks for explaining the reasoning. Unfortunately, the supersampling option does not target transparency supersampling - which is what I'm concerned with

**Comment by mirh** [comment]
[AFAIK](https://www.pcgamingwiki.com/wiki/Nvidia_Profile_Inspector#Antialiasing) transparency supersampling is just MSAA with a touch of SSAA only selectively applied to transparent parts. 
And so "supersampling without asterisks" is never going to have less coverage/quality (let's not mention performance tho).

The problem with your case isn't that "transparency" isn't being targeted (I suppose leaves are the best improvement in #3176) but probably that such forcing is nowhere as complex and refined as the driver hacks that evolved over two decades of d3d9.

**Comment by FranTesla** [comment]
you can use DX9FSAAViewer.exe to see the samples used, and more important, also in textures, with and without Supersample, also the ForceD3D9On12 "Wrapper" will work with Supersample forced in the nvidia profile
(in DX9FSAAViewer go to the options and change the MSAA level) 

DX9FSAAViewer MSAA 8x + Supersample 
comparison [https://imgsli.com/MzEzNDc3](https://imgsli.com/MzEzNDc3) 

I think an option to force Supersample for DirectX9 should be included in DXVK, specially for Linux, is a nice feature to have in older games, but I guess is a niche one...

**Comment by Blisto91** [comment]
See config options https://github.com/doitsujin/dxvk/blob/0fd00087e9c7aa395b98d233e360ab5a36f2fcee/dxvk.conf#L244
