### ISSUE TITLE
Trails of Cold Steel crash on startup

### ISSUE THREAD

**Issue by Bry253** [doitsujin/dxvk#3195]
Game works on previous version (1.10.3), but crashes on a white screen after a while on startup using dxvk 2.0. (Windows 10)

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Trails of Cold Steel 1

### System information
- GPU: Ice Lake GT1
- Driver: 31.0.101.2115
- DXVK version: 2.0 & 1.10.3

### Log files
- d3d11.log:[ed8_d3d11.log](https://github.com/doitsujin/dxvk/files/10439011/ed8_d3d11.log)
- dxgi.log:[ed8_dxgi.log](https://github.com/doitsujin/dxvk/files/10439015/ed8_dxgi.log)

**Comment by Blisto91** [comment]
Hello.

If possible try to get a apitrace of the game. https://github.com/doitsujin/dxvk/wiki/Using-Apitrace
Just use those dll's instead of dxvk and then get past on startup where it usually crashes.

**Comment by doitsujin** [comment]
I tested this game not too long ago with 2.0 on RADV, works fine.

**Comment by Bry253** [comment]
Sorry for the late reply, here's an apitrace

https://drive.google.com/file/d/1squst-IMAhNmhbtHircgZVQ-NlmR9-QM/view?usp=sharing

**Comment by doitsujin** [comment]
Yeah, no obvious bug on our end. You might want to file a bug with Intel's Windows driver since that's where the problem is.

**Comment by Bry253** [comment]
Okay thank you
