### ISSUE TITLE
[d9d9] Wakaba-iro no Quartet crash at startup

### ISSUE THREAD

**Issue by Nekotekina** [doitsujin/dxvk#3197]
### Software information
Game crashes at startup, seems to work fine with wined3d.
```
wine: Unhandled page fault on execute access to 00000000 at address 00000000 (thread 07c4), starting debugger...
...
Unhandled exception: page fault on execute access to 0x00000000 in 32-bit code (
0x00000000).
0260:fixme:dbghelp_dwarf:dwarf2_read_range no entry found
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:00000000 ESP:0032e99c EBP:0032ea08 EFLAGS:00010246(  R- --  I  Z- -P- )
 EAX:0032e9cc EBX:021d3998 ECX:00000000 EDX:712d4050
 ESI:00000000 EDI:00000000
Stack dump:
0x0032e99c:  6253444f 712d4050 0032e9cc 0032ea08
0x0032e9ac:  624d2b91 00000001 021d2b50 00000000
0x0032e9bc:  00000000 0000006c 0032ea5c 0032ea28
0x0032e9cc:  3b9f9493 00000000 00000000 00000000
0x0032e9dc:  00000000 00000000 00000000 00000002
0x0032e9ec:  021cd6a8 0000006c 0032ea10 0032ea58
Backtrace:
=>0 0x00000000 (0x0032ea08)
  1 0x624d2d7d in d3d9 (+0x92d7d) (0x0032ea68)
  2 0x624733dd in d3d9 (+0x333dd) (0x0032eb08)
  3 0x62474103 in d3d9 (+0x34103) (0x0032eb88)
  4 0x6245ff16 in d3d9 (+0x1ff16) (0x0032ece8)
  5 0x624612eb in d3d9 (+0x212eb) (0x0032f44c)
  6 0x624421d7 in d3d9 (+0x21d7) (0x0032f52c)
  7 0x00469143 in wakabaironoquartet_trial (+0x69143) (0x0032f684)
  8 0x004772cc in wakabaironoquartet_trial (+0x772cc) (0x0032fee4)
  9 0x004c810e ??4SThreadParam@@QAEAAU0@$$QAU0@@Z+0x9aee() in wakabaironoquartet
_trial (0x0032ff30)
  10 0x7b62df20 WriteTapemark+0x100(device=7FFD1000, type=<is not available>, co
unt=<is not available>, immediate=<is not available>) [Z:\usr\src\packages\BUILD
\dlls\kernel32\tape.c:317] in kernel32 (0x0032ff48)
  11 0x7bc57ba7 RtlWakeConditionVariable+0x57(variable=7B62DF10) [Z:\usr\src\pac
kages\BUILD\dlls\ntdll\sync.c:766] in ntdll (0x0032ff5c)
  12 0x7bc58260 RtlCreateUserThread(entry=004C8192, arg=7FFD1000) [Z:\usr\src\pa
ckages\BUILD\dlls\ntdll\thread.c:261] in ntdll (0x0032ffec)
0x00000000: -- no code accessible --

```
Demo version can be found at https://trial.getchu.com/D100/1047311/WakabaironoQuartet_trial.zip

### System information
- GPU: AMD Radeon RX 5500 XT
- Driver: MESA 22.3.3
- Wine version: 7.0.1
- DXVK version: 2.0

### Apitrace file(s)
I'll provide it later if necessary.

### Log files
- d3d9.log:
[WakabaironoQuartet_trial_d3d9.log](https://github.com/doitsujin/dxvk/files/10448216/WakabaironoQuartet_trial_d3d9.log)

**Comment by K0bin** [comment]
> You don't have permission to access /D100/1047311/WakabaironoQuartet_trial.zip on this server.

**Comment by Nekotekina** [comment]
Maybe it'll work from here: https://www.getchu.com/soft.phtml?id=1047311&gc=gc
![image](https://user-images.githubusercontent.com/6028184/213238423-e6bca3d3-b4cd-4d1e-96c6-d48bb8ad939c.png)

**Comment by K0bin** [comment]
That apitrace crashes in apitrace code with both DXVK and WineD3D unfortunately.

**Comment by mbriar** [comment]
You should make the apitrace without DXVK and let it render at least a bit.

**Comment by Nekotekina** [comment]
Made an apitrace:
https://mega.nz/file/IuwTxYAA#iXpO9kPXEpovIHs7Vvujq--X-etXFdSy0s54RWSUCZs

**Comment by Blisto91** [comment]
Do note that the minimum supported wine version for dxvk 2.0 is 7.1
Tho i don't know if it would crash when below is used.

**Comment by Nekotekina** [comment]
Okay, maybe it's wine issue then.

**Comment by mbriar** [comment]
The trail version works fine for me with DXVK as well, you need to kill the process when it asks you to insert something at the end of the installation procedure so that it doesn't delete itself again. After that it launches and runs fine.

**Comment by Nekotekina** [comment]
1.10.3 works fine.
I tried update wine to 8.0-rc4 and it also works with dxvk 2.0.
I guess this can be closed then.
