### ISSUE TITLE
D3D11_FORMAT... was not declared in this scope.

### ISSUE THREAD

**Issue by SchrodingersKage** [doitsujin/dxvk#3201]
Hey, guys! I am getting this error that I think is caused by my some missing headers. I am not sure though. I have tried a bunch of things like recloning dxvk, getting another headers file. I am not sure what to make of it anymore. Here is the code that I think has the significant error. I have marked the lines with little pointers so that they are easier to find.

The Meson build system
Version: 0.61.2
Source dir: /home/daxkharris/dxvk
Build dir: /home/daxkharris/Games/genshin/dxvk-master/build.64
Build type: cross build
Project name: dxvk
Project version: v2.0
C compiler for the host machine: x86_64-w64-mingw32-gcc (gcc 10.0.0 "x86_64-w64-mingw32-gcc (GCC) 10-posix 20220113")
C linker for the host machine: x86_64-w64-mingw32-gcc ld.bfd 2.38
C++ compiler for the host machine: x86_64-w64-mingw32-g++ (gcc 10.0.0 "x86_64-w64-mingw32-g++ (GCC) 10-posix 20220113")
C++ linker for the host machine: x86_64-w64-mingw32-g++ ld.bfd 2.38
C compiler for the build machine: cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
C linker for the build machine: cc ld.bfd 2.38
C++ compiler for the build machine: c++ (gcc 11.3.0 "c++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
C++ linker for the build machine: c++ ld.bfd 2.38
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64

Executing subproject libdisplay-info 

libdisplay-info| Project name: libdisplay-info
libdisplay-info| Project version: 0.0.0
libdisplay-info| C compiler for the host machine: x86_64-w64-mingw32-gcc (gcc 10.0.0 "x86_64-w64-mingw32-gcc (GCC) 10-posix 20220113")
libdisplay-info| C linker for the host machine: x86_64-w64-mingw32-gcc ld.bfd 2.38
libdisplay-info| C compiler for the build machine: cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
libdisplay-info| C linker for the build machine: cc ld.bfd 2.38
libdisplay-info| Program tool/gen-search-table.py found: YES (/home/daxkharris/dxvk/subprojects/libdisplay-info/tool/gen-search-table.py)
libdisplay-info| Library m found: YES
libdisplay-info| Compiler for C supports arguments -Wundef: YES
libdisplay-info| Compiler for C supports arguments -Wmissing-prototypes: YES
libdisplay-info| Compiler for C supports arguments -Walloca: YES
libdisplay-info| Compiler for C supports arguments -Wdeclaration-after-statement: YES
libdisplay-info| Compiler for C supports arguments -Wconversion: YES
libdisplay-info| Compiler for C supports arguments -Wno-unused-parameter: YES
libdisplay-info| Compiler for C supports arguments -Wno-missing-field-initializers: YES
libdisplay-info| Compiler for C supports arguments -Werror=implicit: YES
libdisplay-info| Build targets in project: 2
libdisplay-info| Subproject libdisplay-info finished.

Library d3d9 found: YES
Library d3d11 found: YES
Library dxgi found: YES
Library d3dcompiler_47 found: YES
Program x86_64-w64-mingw32-windres found: YES
Compiler for C++ supports arguments -msse: YES 
Compiler for C++ supports arguments -msse2: YES 
Compiler for C++ supports arguments -msse3: YES 
Compiler for C++ supports arguments -mfpmath=sse: YES 
Compiler for C++ supports arguments -Wimplicit-fallthrough: YES 
Compiler for C++ supports arguments -Wno-missing-field-initializers: YES 
Compiler for C++ supports arguments -Wno-unused-parameter: YES 
Compiler for C++ supports arguments -Wno-cast-function-type: YES 
Compiler for C++ supports arguments -Wno-unused-private-field: NO                                                 <----
Compiler for C++ supports arguments -Wno-microsoft-exception-spec: NO                                        <----
Compiler for C++ supports arguments -Wno-extern-c-compat: NO                                                        <----
Compiler for C++ supports arguments -Wno-unused-const-variable: YES 
Compiler for C++ supports arguments -Wno-missing-braces: YES 
Compiler for C++ supports arguments -DNOMINMAX: YES 
Compiler for C++ supports arguments -D_WIN32_WINNT=0xa00: YES 
Compiler for C++ supports arguments -DDXVK_WSI_WIN32: YES 
Compiler for C supports arguments -msse: YES 
Compiler for C supports arguments -msse2: YES 
Compiler for C supports arguments -msse3: YES 
Compiler for C supports arguments -mfpmath=sse: YES 
Compiler for C supports arguments -Wimplicit-fallthrough: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES (cached)
Compiler for C supports arguments -Wno-unused-parameter: YES (cached)
Compiler for C supports arguments -Wno-cast-function-type: YES 
Compiler for C supports arguments -Wno-unused-private-field: NO                                                      <----
Compiler for C supports arguments -Wno-microsoft-exception-spec: NO                                             <----
Compiler for C supports arguments -Wno-extern-c-compat: NO                                                             <----
Compiler for C supports arguments -Wno-unused-const-variable: YES 
Compiler for C supports arguments -Wno-missing-braces: YES 
Compiler for C supports arguments -DNOMINMAX: YES 
Compiler for C supports arguments -D_WIN32_WINNT=0xa00: YES 
Compiler for C supports arguments -DDXVK_WSI_WIN32: YES 
Compiler for C++ supports link arguments -static: YES 
Compiler for C++ supports link arguments -static-libgcc: YES 
Compiler for C++ supports link arguments -static-libstdc++: YES 
Compiler for C++ supports link arguments -Wl,--file-alignment=4096: YES 
Compiler for C supports link arguments -static: YES 
Compiler for C supports link arguments -static-libgcc: YES 
Compiler for C supports link arguments -static-libstdc++: YES 
Compiler for C supports link arguments -Wl,--file-alignment=4096: YES 
Program glslangValidator found: YES (/usr/bin/glslangValidator)
Run-time dependency threads found: YES
Dependency threads found: YES unknown (cached)
Build targets in project: 14

Any help will be appreciated I will probably be fairly active as I want to fix this and get this working.
Thank you in advance!

**Comment by doitsujin** [comment]
reminder that DXVK needs MinGW 10.0 to build, which is **NOT** GCC 10.0 (the required mingw version ships GCC 12.x).

**Comment by SchrodingersKage** [comment]
I got all of that stuff through mingw. What information would be beneficial in a report like this. I am new to linux, so I am unaware of what stuff is actually important. This was just what was put in my terminal after I threw in the ./release.sh file command.

**Comment by mbriar** [comment]
> I got all of that stuff through mingw

You need at least mingw version 10.0 to build latest DXVK. From the looks of it, you currently have version 8.0.

**Comment by SchrodingersKage** [comment]
According to my package manager I have 10.3, however there are some 8.0 packages that are installed as well.

**Comment by SchrodingersKage** [comment]
Alright I have no clue which packages I need to install. I found a common files package. However It didn't install the entire compiler, and I don't know where to look or start. I am running Pop_OS!.

**Comment by WinterSnowfall** [comment]
Compiling dxvk on the current Ubuntu LTS or Debian Stable is not possible without resorting to external package sources, since both ship outdated versions of mingw. It is orders of magnitude easier to setup a build environment on Arch, so maybe give than a go if you don't want to spend ages hacking together something functional on other distros? I've also worked with Debian Testing in the past (which ships mingw 10.0), but to be honest the setup is a lot more straight forward on Arch (or Arch-based distros like Manjaro, for example). If you want to stick to using Pop_OS!, then simply create a VM or a docker container for your Arch-based build environment. Oh, and welcome to the wonderfully complicated world of Linux :smile:.

**Comment by SchrodingersKage** [comment]
I looked into it, and turns out I was just completely misunderstanding the readme. I didn't need to build it I just wanted to compile it into a wineprefix.
