### ISSUE TITLE
Prototype 2 rendering textures black

### ISSUE THREAD

**Issue by CarnageDevs** [doitsujin/dxvk#3202]
Upon starting a new game in Prototype 2, all the textures are seemingly rendered black:

![image](https://user-images.githubusercontent.com/17109829/213861583-5faf78bf-1d55-4d46-800a-2777b9a947d1.png)

### Software information
Prototype 2 (Steam)

**In-game graphics settings:**
Resolution: 1920x1080
Anti-Alias Level: High
VSync Enabled: On
Shadow Detail: High
Ambient Occlusion: On
Motion Blur: On
Effects Quality: High
Prop Draw Distance: High

**Steam launch options:** `DXVK_FRAME_RATE=60 taskset -c 0-7 %command%`

### System information
- GPU: AMD RX 7900 XTX
- Driver: Mesa 23.1.0-devel (git-4fb2463a37)
- Wine version: Proton Experimental
- DXVK version: 2.0

### Apitrace file(s)
- [prototype2-trace.tar.xz](https://mega.nz/file/tZ1AgYYQ#FXS_Hw4J6F7PuI4IzJWZDVhxR0261i_vOf09fPF1TqI)

Trace was made under Linux, I included both a trace done with `PROTON_USE_WINED3D=1 %command%` as well as one without (using DXVK). The WineD3D trace crashed after the first loading screen upon starting a new game, as soon as the first cutscene showed. DXVK trace was able to get past those cutscenes to the start of the game where the rendering issues are present.

### Log files
- d3d9.log: [prototype2_d3d9.log](https://github.com/doitsujin/dxvk/files/10471907/prototype2_d3d9.log)
- d3d11.log: N/A
- dxgi.log: [prototype2_dxgi.log](https://github.com/doitsujin/dxvk/files/10471909/prototype2_dxgi.log)

**Comment by mbriar** [comment]
It seems to render correctly here, so it might be a driver issue, can you try RADV_DEBUG=nohiz,nodcc or using amdvlk?

**Comment by CarnageDevs** [comment]
RADV_DEBUG=nohiz,nodcc fixed it for me, thanks!

**Comment by mbriar** [comment]
@CarnageDevs please open a bug report about that here then: https://gitlab.freedesktop.org/mesa/mesa/-/issues

**Comment by CarnageDevs** [comment]
Opened a bug report: https://gitlab.freedesktop.org/mesa/mesa/-/issues/8127

Seems like only `nodcc` is necessary to get the textures rendering correctly
