### ISSUE TITLE
State of Decay 2 invisible character models for certain characters

### ISSUE THREAD

**Issue by CarnageDevs** [doitsujin/dxvk#3203]
On State of Decay 2, some characters will have invisible models with only their clothes visible:

![image](https://user-images.githubusercontent.com/17109829/213865269-bb3d57c3-f0dd-4ca3-abd1-cae4e758a9d3.png)

I'm not sure if this is specific to the characters or the clothes they are wearing as others have mentioned this issue on ProtonDB being specific to some clothes, however, changing the character above to use different clothes didn't fix the issue for me.

This only affects DXVK and the models render when running the game with WineD3D using `PROTON_USE_WINED3D=1 %command%`, but it has its own set of issues where there are white boxes around all the UI elements which DXVK doesn't have.

Reading online, it looks like the issue happens on Windows too as shown [here](https://steamcommunity.com/app/241540/discussions/0/626329821078618719/) and [here](https://steamcommunity.com/app/241540/discussions/0/864980734722143873/), and is fixable by setting Anti-Aliasing & Anisotropic Filtering to use the application's settings using your GPU graphical control panel.

**To reproduce the issue:**
1. Go to campaign and start a new community
2. Choose to reply the tutorial if already beaten before
3. Pick any difficulty
4. Play as the Odd Couple (Ashton and Grace)
5. Skip the initial cutscene and look at Grace, she should have no model while her clothes are visible

### Software information
State of Decay 2 (Steam)

### System information
- GPU: AMD RX 7900 XTX
- Driver: Mesa 23.1.0-devel (git-4fb2463a37)
- Wine version: Proton Experimental
- DXVK version: 2.0

### Apitrace file(s)
- [StateOfDecay2-trace.tar.xz](https://mega.nz/file/cI9n2KSL#3ip7gLX3F-0Cjlng6GtWYCSnalu20r7e9OpsiEVCSqQ)

Trace was made under Linux using DXVK as the issue is not present on WineD3D and the game would crash on launch when attempting to use the apitrace on WineD3D.

### Log files
- d3d9.log: N/A
- d3d11.log: [StateOfDecay2-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/10472072/StateOfDecay2-Win64-Shipping_d3d11.log)
- dxgi.log: [StateOfDecay2-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/10472073/StateOfDecay2-Win64-Shipping_dxgi.log)

**Comment by mbriar** [comment]
I can reproduce this on RDNA2 and RADV as well. However, it seems to render correctly with AMDVLK and, according to protondb, also on nvidia.

**Comment by doitsujin** [comment]
Seems to be a Mesa regression of sorts, trace replays correctly with 22.3 but not current main. I'll bisect.

**Comment by mbriar** [comment]
fwiw, to reproduce without staring at apitrace the whole time, `d3dretrace.exe --snapshot=33205621 --headless StateOfDecay2-Win64-Shipping.trace` produces a frame that shows the issue.

**Comment by doitsujin** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/8128

**Comment by doitsujin** [comment]
Closing since there's a RADV MR to fix this: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/20829
