### ISSUE TITLE
[D3D9] Incorrectly Rendered Loading Progress Bar in DuLuDuBi Star

### ISSUE THREAD

**Issue by Sterophonick** [doitsujin/dxvk#3206]
### Software information
DuLuDuBi Star (Non-Steam)
Game can be found [here](https://archive.org/details/duludubistar_202007).

### Running the Game
Needs `LC_ALL=zh_CN` set to work, else it crashes.
Would recommend renaming the game executable to something more readable.
Locale emulator is not compatible with Wine.

### System information
 - Steam Deck
 - Driver: Mesa 22.2.0 (git-17e5312102)
 - Wine version: Wine `lutris-fshack-7.2-x86_64`
 - DXVK version: V1.10.3 (Still happens on master)

### Apitrace file(s)
[game.trace.zip](https://github.com/doitsujin/dxvk/files/10473643/game.trace.zip)
(I nested a `.7z` inside of a `.zip` to cheat GitHub)

### Log files
[game_d3d9.log](https://github.com/doitsujin/dxvk/files/10473637/game_d3d9.log)
[game_dxgi.log](https://github.com/doitsujin/dxvk/files/10473638/game_dxgi.log)

### Screenshots
![Screenshot 2023-01-21 19-46-31](https://user-images.githubusercontent.com/34801996/213898719-a28c2cd3-d15d-49d0-9144-43b15bcb0609.png)
![Screenshot 2023-01-21 19-46-36](https://user-images.githubusercontent.com/34801996/213898720-125272ef-fb43-45fd-b8d6-fee27f512afa.png)

### Correct Behavior
![image](https://user-images.githubusercontent.com/34801996/213898475-c4cc7116-e9a7-4d14-ac2f-f1e3315cd54a.png)

### Notes
This could potentially be annoying to test, because after enough times of launching before a restart, this specific loading screen stops showing up because it all loads faster.

**Comment by Blisto91** [comment]
Seem to be a regression from https://github.com/doitsujin/dxvk/commit/609856db35c674b5b61bdfdb62fbb92baed5ca37
Tested on R9 380X mesa-git with the apitrace

**Comment by Blisto91** [comment]
Changing the line `m_backBuffers.resize(NumBackBuffers + 1);` in the above commit back to `m_backBuffers.resize(NumBackBuffers);` gets rid of the issue. This is equivalent to what `d3d9.noExplicitFrontBuffer = True` does today and so that also gets rid of it.
doitsujin wants some feedback from Josh before accepting that as a fix so just noting this info here for now.

**Comment by Sterophonick** [comment]
For the record, if this ends up being the fix, `ｿﾖﾁ昻ﾇﾇ.exe` is the actual name of the game executable.

**Comment by K0bin** [comment]
`SWAPEFFECT_DISCARD` + `BackBufferCount = 1`. So this will be fixed by #3392
