### ISSUE TITLE
[d3d9] Koko kara Natsu no Innocence! (ここから夏のイノセンス！) black square glitch

### ISSUE THREAD

**Issue by Nekotekina** [doitsujin/dxvk#3208]
Appears in main menu after hovering the mouse over menu items.
![image](https://user-images.githubusercontent.com/6028184/214126937-76b8664a-2b02-48b6-8eaf-eeef2e32e8dd.png)

Wined3d seems to work fine.

### Software information
Trial version can be downloaded at https://www.getchu.com/soft.phtml?id=853845&gc=gc
Note that due to some bug in Wine, `GameData/movie.int` file must be deleted in order for the game to start.

### System information
- GPU: AMD Radeon RX 5500 XT
- Driver: MESA 22.3.3
- Wine version: 8.0-rc5
- DXVK version: 2.0

### Apitrace file(s)
- https://mega.nz/file/8rR0STZD#mJq3Dwcz7UKlGqt4VbBUoB_ZNGMALRWyDq_iKbYhT3M

### Log files
- d3d9.log: [cs2_d3d9.log](https://github.com/doitsujin/dxvk/files/10482905/cs2_d3d9.log)
- dxgi.log: empty

**Comment by Nekotekina** [comment]
I see, thanks for the information

**Comment by Blisto91** [comment]
You could try making a `dxvk.conf` where the d3d9 log appeared and insert `d3d9.shaderModel = 1` and see if that changes the issue.

**Comment by Nekotekina** [comment]
> You could try making a `dxvk.conf` where the d3d9 log appeared and insert `d3d9.shaderModel = 1` to see if that changes the issue.

Hmm, it doesn't seem to have any effect.

**Comment by Blisto91** [comment]
Ah ye i see, the config doesn't have an effect on this one. Tho it behaves like a classic Partial Presentation issue.

**Comment by K0bin** [comment]
This is indeed another instance of #2749
