### ISSUE TITLE
Battlefield 1 half black screen problem. Half dark screen in game menu too

### ISSUE THREAD

**Issue by mozo78** [doitsujin/dxvk#321]
The game runs with very good performance but in the intro movie it has one half normal picture and one half black. Later in the game, when escape is pressed, the menu has similar problem, not black, but darker. See the screenshots:
https://s9.postimg.cc/uzyz1q3pb/Screenshot_20180424_121545.png
https://s9.postimg.cc/cx5waina7/Screenshot_from_2018-04-24_20-50-29.png
https://s9.postimg.cc/5v7ynxtun/Screenshot_from_2018-04-24_20-51-41.png

The game doesn't run with vanilla wine so apitrace isn't of much use.

### Software information
Battlefield 1

### System information
- GPU: GTX 1080 Ti
- Driver: 396.18/390.48
- Wine version: 3.5
- DXVK version: latest, various versions

### Apitrace file(s)
- https://pastebin.com/mdJeVkf8

### Log files
- d3d11.log:
https://pastebin.com/1hHYHdWS
- dxgi.log: 
https://pastebin.com/Gn1rX0C7
- wine.log
https://pastebin.com/yc4kiv0R

**Comment by doitsujin** [comment]
I'm aware of this issue but nobody has managed to record an apitrace so far. Can't fix.

**Comment by ZeroFault** [comment]
Here is the apitrace [trace](https://mega.nz/#!WHZ3WJhL!YnNF8f53GD7MVkIDz111VKBuMOPCjmjwjNmxw8nWp3g)

**Comment by elovin** [comment]
Battlefield 1 works fine on AMD even without feature level 11.1

**Comment by ZeroFault** [comment]
Feature level 11_1 was only needed for replaying the apitrace

**Comment by doitsujin** [comment]
Fixed in the Nvidia 396.54.02 driver, see #267 .
