### ISSUE TITLE
Dxvk 2.1 release is missing setup_dxvk.sh script

### ISSUE THREAD

**Issue by Mikaka27** [doitsujin/dxvk#3210]
In tar.gz with released dxvk 2.1 setup_dxvk.sh script is missing, check out comparison screenshots with 2.0 release and 2.1
![image](https://user-images.githubusercontent.com/9214100/214506453-0a67a7b2-4cce-4abb-adfd-68b42aa4a1f0.png)

![image](https://user-images.githubusercontent.com/9214100/214506552-4383c6f1-5058-477d-9d10-78f8915c94d8.png)

**Comment by Blisto91** [comment]
Hello.

As said in the release notes the install script has been removed
> Note: The setup script setup_dxvk.sh was no longer deemed useful and got removed. This change will only affect users who manually install DXVK into a wine prefix, rather than using it through Proton or Lutris.

You can still keep the script around from the old releases and use that together with newer if desired.

Also see the original PR https://github.com/doitsujin/dxvk/pull/3097

**Comment by Mikaka27** [comment]
You're right, I missed that, sorry.
