### ISSUE TITLE
Jedi Fallen Order crash

### ISSUE THREAD

**Issue by Silent-Remux** [doitsujin/dxvk#3215]
```
warn:  D3D11: Failed to write shared resource info for a texture
info:  Setting timer interval to 500 us
err:   DxvkSubmissionQueue: Command submission failed: VK_ERROR_DEVICE_LOST
```

I did forget to disable steam overlay so may be related.

dxvk.conf settings:
`dxvk.enableGraphicsPipelineLibrary = True`

### Software information
Jedi Fallen Order, max settings, windowed fullscreen.

### System information
- GPU: Nvidia 4090
- Driver: 528.24
- Wine version: Windows 11
- DXVK version: 2.1

### Log files
[starwarsjedifallenorder_d3d11.log](https://github.com/doitsujin/dxvk/files/10513457/starwarsjedifallenorder_d3d11.log)
[starwarsjedifallenorder_dxgi.log](https://github.com/doitsujin/dxvk/files/10513458/starwarsjedifallenorder_dxgi.log)

**Comment by llde** [comment]
Seems the game is trying to use a shared resource. This isn't actually supported on windows.

**Comment by mbriar** [comment]
Make sure you place the DXVK dlls also in `SwGame/Binaries/Win64/`, Unreal Engine 4 games always ship 2 .exe files. Also disable Origin overlay and stuff if that still exists. If it still doesn't work, it's likely an unfixable dxvk on windows issue and time to give up.

**Comment by Silent-Remux** [comment]
> Make sure you place the DXVK dlls also in `SwGame/Binaries/Win64/`, Unreal Engine 4 games always ship 2 .exe files. Also disable Origin overlay and stuff if that still exists. If it still doesn't work, it's likely an unfixable dxvk on windows issue and time to give up.

Yes I put d3d11.dll and dxgi.dll in that folder. I can play fine for a few hours. The crash is seemingly random. It's EA client now not Origin and yes I disabled that overlay too.

**Comment by Silent-Remux** [comment]
> Seems the game is trying to use a shared resource. This isn't actually supported on windows.

I am aware dxvk is not technically supported on Windows but I have followed all the necessary steps in the tips section and thought its worth raising a crash issue. It could've been steam overlay so will report back later on if disabling that fixes it.

**Comment by doitsujin** [comment]
`VK_ERROR_DEVICE_LOST` indicates a driver crash, not really something we can really look into.

Also:
> dxvk.conf settings:
> `dxvk.enableGraphicsPipelineLibrary = True`

Please don't do this. Setting this to `True` literally doesn't do anything other than reduce GPU performance, it's meant for debugging purposes only.

**Comment by Evernow** [comment]
> > Seems the game is trying to use a shared resource. This isn't actually supported on windows.
> 
> I am aware dxvk is not technically supported on Windows but I have followed all the necessary steps in the tips section and thought its worth raising a crash issue. It could've been steam overlay so will report back later on if disabling that fixes it.

https://github.com/doitsujin/dxvk/wiki/Feature-support#shared-resources

**Comment by gardotd426** [comment]
> > Seems the game is trying to use a shared resource. This isn't actually supported on windows.
> 
> I am aware dxvk is not technically supported on Windows but I have followed all the necessary steps in the tips section and thought its worth raising a crash issue. It could've been steam overlay so will report back later on if disabling that fixes it.

I can tell you that I've had Jedi Fallen Order since the week it came out, back when I was on AMD, and I've been running a 3090 for almost 2.5 years now, and I've never had a single crash in this game, on Linux. 

DXVK is not developed for Windows. You are free to use it because this is open-source and that's how FOSS works, as it should. But this isn't a bug, and since the NV drivers and Windows itself are closed-source, there's not much that can be done to help. 

For Windows users, DXVK is a "if it works for you and improves things, great! Use it. If not, it's not supported, sorry."

**Comment by Etaash-mathamsetty** [comment]
> > > Seems the game is trying to use a shared resource. This isn't actually supported on windows.
> > 
> > 
> > I am aware dxvk is not technically supported on Windows but I have followed all the necessary steps in the tips section and thought its worth raising a crash issue. It could've been steam overlay so will report back later on if disabling that fixes it.
> 
> I can tell you that I've had Jedi Fallen Order since the week it came out, back when I was on AMD, and I've been running a 3090 for almost 2.5 years now, and I've never had a single crash in this game, on Linux.
> 
> DXVK is not developed for Windows. You are free to use it because this is open-source and that's how FOSS works, as it should. But this isn't a bug, and since the NV drivers and Windows itself are closed-source, there's not much that can be done to help.
> 
> For Windows users, DXVK is a "if it works for you and improves things, great! Use it. If not, it's not supported, sorry."

I don't think that DXVK not being developed for windows even matters here, if the game uses shared resources, it's simply impossible to support on windows as far as my knowledge goes.
