### ISSUE TITLE
(Black Mesa) MSAA alphatest new option from dxvk 2.1 makes the entire game blurry

### ISSUE THREAD

**Issue by Deus-nsf** [doitsujin/dxvk#3218]
It's the d3d9.forceSampleRateShading option, Black Mesa is one of the games that work really well with dxvk's MSAA, and enabling alpha test coverage works very well too, but it kind of blurs the entire picture and not just the parts that should recieve the alpha test coverage pass.

It is a massive step in the right direction though, I hope this can be improved, and if not, maybe Vulkan has some supersampling options instead of multisampling? That would be incredible too (even though it would mean a massive increase in GPU utilization).

I should add that it does this at x2, x4, x8, and x16 MSAA, actually, the higher it is, the blurrier it becomes I feel.

GPU is GTX 1080 Ti on the latest proprietary drivers (528.24)

**Comment by K0bin** [comment]
> but it kind of blurs the entire picture and not just the parts that should recieve the alpha test coverage pass.

> maybe Vulkan has some supersampling options instead of multisampling

`foceSampleRateShading` enables sample rate shading. So it will apply MSAA on the entire image, not just the polygon edges. This is super sampling.

That option is a hack and we generally don't want to put a lot of effort into those. If it doesn't work or doesn't look good with Black Mesa, don't use it.

**Comment by Deus-nsf** [comment]
Yeah again, I've been testing SRS on many games that natively support MSAA, and in 90% of cases this feature just works, it's a godsend for AMD and Intel cards that doesn't have drivers wizardry to force exotic super sampling options. I don't have a list but so many games I've tested are compatible with this and it makes them look so much better. It is a very important feature and I'm so glad it exists.
