### ISSUE TITLE
Why should install x64 dlls in system32 and x32 dlls in syswow64?

### ISSUE THREAD

**Issue by nerun** [doitsujin/dxvk#3228]
In README, installation instructions says:
```
WINEPREFIX=/path/to/wineprefix
cp x64/*.dll $WINEPREFIX/drive_c/windows/system32
cp x32/*.dll $WINEPREFIX/drive_c/windows/syswow64
winecfg
```
Why should i install x64 DLLs in System32 instead of Syswow64?

And, why should i install x32 DLLs in Syswow64 instead of System32?

**Comment by mbriar** [comment]
Because on a 64 bit windows install and o 64 bit wine prefixes, system32 contains 64 bit dlls and syswow64 contains 32 bit dll. Syswow64 stands for 'system windows on windows 64'.

**Comment by Blisto91** [comment]
As mbriar said that is just a quirk of how Windows does things.

https://www.ibm.com/support/pages/why-do-64-bit-dlls-go-system32-and-32-bit-dlls-syswow64-64-bit-windows

**Comment by nerun** [comment]
Thank you!
