### ISSUE TITLE
Black Texture Issue (Game : Control )

### ISSUE THREAD

**Issue by py-nux** [doitsujin/dxvk#3229]
All game launch perfectly but texture stay "black"

(use launcher Heroic with Crossover with dxvk 1.10

[Calluna-lastPlay.log](https://github.com/doitsujin/dxvk/files/10545665/Calluna-lastPlay.log)

**Comment by Blisto91** [comment]
Hello.

Mac is sadly not directly a supported platform.
Also note that dxvk 1.10 is very outdated by now

**Comment by K0bin** [comment]
Like Blisto said, we don't support Mac OS and the game is known to work fine on every platform that properly supports Vulkan.

It looks like some shaders fail to compile so you'll have to report that to MoltenVK or SPIRV-Cross.
