### ISSUE TITLE
Mono game hangs on minimize

### ISSUE THREAD

**Issue by Csimbi** [doitsujin/dxvk#3233]
Please describe your issue as accurately as possible.
I start the game and it works fine.
I minimize it - to read emails or something.
Clicking on the task bar on the app brings it back up with a pitch black window and the game seems to be hung up.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Bloons TD 6 (on Steam). Running as Windowed on Windows 10.

### System information
- GPU: RTX 3060Ti
- Driver: 528.24
- Wine version:  N/A
- DXVK version: 2.0

### Apitrace file(s)
Does not run, it says:
```
Failed to initialize graphics.
Make sure you have DirectX 11 installed, have up to date drivers for your graphics card and have not disabled
3D acceleration in display settings.
InitializeEngineGraphics failed

```
### Log files
- d3d11.log: https://pastebin.com/SYm18tAf
- dxgi.log: https://pastebin.com/cva0UMi8

**Comment by K0bin** [comment]
> warn:  D3D11: Failed to write shared resource info for a texture
> warn:  D3D11Device::OpenSharedResourceGeneric: Handle not found: 0xc0000a02

Shared resources are not supported on Windows.

**Comment by Csimbi** [comment]
@K0bin 
Thanks! Would that go away if the game were running in full screen?
(I am not sure what a shared resource info is, why that happens and how to avoid.)

**Comment by Blisto91** [comment]
Shared resources is if a game need to "share resources" between two different graphics API devices or processes. E.g. a game might be using both Direct3D 9 and Direct3D 11 and want to share some information between the two.
This explanation might not be entirely correct in the details.

But anyway, the shared resources implementation requires some Proton patches and aren't supported on Windows. 
If that is even what causes the issue. Haven't tested this yet.

**Comment by K0bin** [comment]
Go to the Nvidia control panel and set the presentation mode to native and see if that helps.

**Comment by Csimbi** [comment]
@Blisto91 Thanks for the explanation - seems there is nothing I can do there.

@K0bin Changed it the 'prefer native' - no change, still hangs.

**Comment by Blisto91** [comment]
Mkay i did a quick test of this on Windows with AMD. I'm not reproducing the issue with either dxvk 2.0 or 2.2

**Comment by Blisto91** [comment]
@Csimbi Could i get you to retest this with dxvk 2.3?

**Comment by Csimbi** [comment]
> @Csimbi Could i get you to retest this with dxvk 2.3?

Tested DXVK 2.3 vs. Bloons TD 6 v38.3 with default config (no specific config file).
It works, minimizing to task bar and bringing it back up no longer causes a hang.
Great stuff, thank you!

**Comment by Blisto91** [comment]
The cache warnings are fine. 
The shared resources ones is a feature that isn't supported on Windows and can cause issues in some games. But you seem to be able to play fine so I assume they arent much notable here.
