### ISSUE TITLE
Feature Request: DDraw Vulkan Conversion

### ISSUE THREAD

**Issue by ShadowLite1** [doitsujin/dxvk#3234]
This feature can be utilized for games that use DirectX 7 as concurrently there is no other feature that a wrapper has, this can be used for games like SCP Nine-Tailed Fox and other games that use DirectX 7, by having this feature, it can make it easy to use programs like ReShade for DirectX 7 games.

**Comment by K0bin** [comment]
WineD3D handles DirectX 7 and earlier just fine and on Windows there's DgVoodoo.

We have no plans to support anything below DirectX 8.

**Comment by ShadowLite1** [comment]
That is not entirely true, as I have tested WineD3D and DgVoodoo on all settings to no avail that it help, because mainly the OpenGL wrapper does not work with games such of how I ran it.

**Comment by Blisto91** [comment]
I think K0bin meant performance wise barring any bugs.

Be sure to report that on the wine bug tracker if you can.

**Comment by shmerl** [comment]
One use case where this can be useful is bad performance of OpenGL in new Wow64 mode in Wine. I get like 1 fps in Vampire: The Masquerade - Redemption. And unless someone will make an OpenGL extension for it, it won't really improve.

So it would be useful to be able to translate DirectDraw (DX7) into Vulkan to be able to use Wine without 32-bit system runtime with decent performance.

**Comment by Blisto91** [comment]
It is not on the table for dxvk to take on such a project nor merge with one. 
People are of course welcome to fork and try their hand at it none the less.

**Comment by shmerl** [comment]
Well, the alternative could be Wine's own Vulkan backend for DirectDraw which gets some traction even if slowly.

**Comment by PlayNeth** [comment]
I'd love to see that as well. WINE's own implementation is okay, but its _very_ inaccurate and inefficient. DGVoodoo no longer works since 2.82, and the only other option right now for Linux is DXGL which still being worked on and personally I haven't had good luck with it.
DDrawCompat as mentioned beforehand is the only wrapper able to fix some major oddities in older games and sadly it doesn't work on anything else but Windows.
