### ISSUE TITLE
[d3d9] Zwei: The Ilvard Insurrection - constant flickering

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#3238]
The game constantly flickers on each frame. The flickering is fixed either by setting `d3d9.noExplicitFrontBuffer = True` or by using #2967. A d3d8 executable is also shipped with the game (ZWEI2P.exe) and is affected by the same problem.

I'll keep this open for tracking until the above PR is merged under some form ideally.

### Software information
Zwei: The Ilvard Insurrection

### System information
- GPU: RTX 3060
- Driver: 525.78.01
- Wine version: 7.22 Staging
- DXVK version: 2.1

### Apitrace file(s)
[ZWEI2PDX9.trace.tar.xz](https://drive.google.com/file/d/1P_PvYVK0iJEHRnTv-R8HZOOQIrhukFti/view?usp=share_link)

### Log files
- d3d9.log: [ZWEI2PDX9_d3d9.log](https://github.com/doitsujin/dxvk/files/10660800/ZWEI2PDX9_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

**Comment by Blisto91** [comment]
Welcome to the future Winter! It must feel great touching modern API's like d3d9? 😁
