### ISSUE TITLE
Splitgate Unable To Load (Freezes On Launch)

### ISSUE THREAD

**Issue by RitzDaCat** [doitsujin/dxvk#3240]
**Game**
Name: Splitgate (Free on steam)
Settings: Default
Error when: On launch immediately the pop up freezes

**System Info:** 
GTX 4090
7950x
OS: Windows 11

**DXVK**
Latest: 2.1
**Logs:** 
[PortalWars-Win64-Shipping_d3d9.log](https://github.com/doitsujin/dxvk/files/10669183/PortalWars-Win64-Shipping_d3d9.log)
[PortalWars-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/10669184/PortalWars-Win64-Shipping_d3d11.log)
[PortalWars-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/10669185/PortalWars-Win64-Shipping_dxgi.log)

**Comment by Blisto91** [comment]
I quickly launched this on Windows with AMD and dxvk 2.1 and didn't experience the same issue.

A few things to try to see if any of them help.

1. Try https://github.com/doitsujin/dxvk/wiki/Windows#nvidia-gpus
2. At `Splitgate\PortalWars\Binaries\Win64` make a file called `dxvk.conf` and instert `dxgi.nvapiHack = False`
3. Make sure GPU driver is up to date.
4. Try latest master build https://github.com/doitsujin/dxvk/actions/runs/4626931879

**Comment by PaulAnthonyReitz** [comment]
I will try this and report back, thanks!

**Comment by Blisto91** [comment]
@RitzDaCat Friendly ping

**Comment by RitzDaCat** [comment]
Same issue unfortunately. Let me know if there's any other configurations I
can test.

**Comment by RitzDaCat** [comment]
Howdy,

Was just able to login without a black screen, hoped in a custom and
appears to be working as intended!
