### ISSUE TITLE
meson.build:133:0: ERROR: Include dir ./include/vulkan/include does not exist.

### ISSUE THREAD

**Issue by nukeCrayon** [doitsujin/dxvk#3244]
Hi. 
I'm having a hard time to install dxvk on my system.
I don't know if this is the right place to ask this or in arch forum but I'll try it here anyways.

I tried to run `./package-release.sh master . --no-package `

but this gives me the error message of
 `meson.build:133:0: ERROR: Include dir ./include/vulkan/include does not exist.`

I already search in google but I can't see any answers. 
Thank you.

**Comment by Blisto91** [comment]
Remember to include `recursive` when cloning so you also get the submodules like so `git clone --recursive https://github.com/doitsujin/dxvk.git`

If you have already cloned you should be able to fetch them with `git submodule update --init --recursive`

**Comment by nukeCrayon** [comment]
thank you very much @Blisto91.
