### ISSUE TITLE
Need Assassin's Creed® Syndicate more fps

### ISSUE THREAD

**Issue by ChieuNguyen2002** [doitsujin/dxvk#3245]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Name of the game, settings used etc.

### System information
- GPU: GTX-1650
- Driver: 528.49
- Wine version: Nope
- DXVK version: 2.1

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by Blisto91** [comment]
I'm gonna give you the benefit of doubt here and just tell you this is not how you should make an issue. If you have problems with something then please fill out the issue with proper information and describe what the actual issue is 🙂

**Comment by Evernow** [comment]
You didn't even try...

**Comment by ChieuNguyen2002** [comment]
> 

The game when using the default DX11, sometimes the game frame is jerked from 70fps to 30fps even down to 5fps on window 11 22h2. and using vulkan ( dxvk ) it is stable at 40fps with no frame lag but i need a higher and more stable fps than DX11

**Comment by Blisto91** [comment]
What is your GPU and driver.
Post the dxvk logs that appear next to the games exe or in it's root folder.

**Comment by ChieuNguyen2002** [comment]
[ACS_d3d11.log](https://github.com/doitsujin/dxvk/files/10707619/ACS_d3d11.log)
[ACS_dxgi.log](https://github.com/doitsujin/dxvk/files/10707623/ACS_dxgi.log)

**Comment by Blisto91** [comment]
I notice you also have a iGPU.
If you make a file called `dxvk.conf` (.conf is the extension so make sure it isn't just a text file called dxvk.conf.txt) next to where you found the logs and then insert `dxvk.hud = full` can you then verify your Nvidia GPU shows up in the hud?

**Comment by doitsujin** [comment]
We can't just make games run 75% faster. Nvidia's D3D11 driver in particular is known and expected to significantly outperform DXVK especially on older systems.

**Comment by SparkFrenzy475** [comment]
Has the problem been solved? If yes, what did you do to solve it?
