### ISSUE TITLE
Re: DXVK How to use 

### ISSUE THREAD

**Issue by nukeCrayon** [doitsujin/dxvk#3246]
Hi.
in the instruction in the "**How to use**" section of the front page, it says here:
```
WINEPREFIX=/path/to/wineprefix
cp x64/*.dll $WINEPREFIX/drive_c/windows/system32
cp x32/*.dll $WINEPREFIX/drive_c/windows/syswow64
winecfg
```
Please correct me if I'm wrong but isn't it the x64/*.dll to be copied in syswow64?

**Comment by Blisto91** [comment]
Hello!

It isn't very intuitive I know but this is actually just a quirk of how Windows separates 64 & 32bit system files on 64bit systems. So it is correct that system32 is 64bit and syswow64 is 32bit.

https://www.ibm.com/support/pages/why-do-64-bit-dlls-go-system32-and-32-bit-dlls-syswow64-64-bit-windows

**Comment by nukeCrayon** [comment]
thank you again @Blisto91
