### ISSUE TITLE
[d3d9] Metal Slug: renders a black window while the sound keeps playing normaly

### ISSUE THREAD

**Issue by ranplayer** [doitsujin/dxvk#3247]
The game launches a black window, while the sound keep playing normally. Same behaviour with `WineD3D`. The current workaround is to install `d3dcompiler_46`  through wine/protontricks. I'm just wondering if there is a possible fix/workaround on the DXVK's side (I'm attaching an API trace)

### Software information
- Name: Metal Slug
- SteamId: 366250

### System information
- GPU: RX 6700 XT
- Driver: Mesa 22.3.4
- Wine version: Proton 7.0-6, Proton Experimental (as of 2023/02/10) and [GEProton-7-49](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton7-49)
- DXVK version: the ones used by these Proton builds

### Apitrace file(s)
- [mslug1.trace.tar.gz](https://github.com/doitsujin/dxvk/files/10713830/mslug1.trace.tar.gz)

### Log files
- d3d9.log: 
[mslug1_d3d9.tar.gz](https://github.com/doitsujin/dxvk/files/10713844/mslug1_d3d9.tar.gz)

**Comment by K0bin** [comment]
If it's fixed by installing D3DCompiler, this is a bug in Wines implementation of D3DCompiler and you should open a bug Wine report.

**Comment by ranplayer** [comment]
Thanks for the explanation @K0bin . Sorry for the noise.
