### ISSUE TITLE
Devil May Cry 5: enviorment bugging in and out

### ISSUE THREAD

**Issue by sushithebird** [doitsujin/dxvk#3249]
![20230212083258_1](https://user-images.githubusercontent.com/125208115/218324456-8e203fae-a229-44ba-88bb-aff0014f392a.jpg)
![20230211204226_1](https://user-images.githubusercontent.com/125208115/218324460-4fb020bb-f9d7-4393-91a8-1d7c15baa8fa.jpg)
![20230211204229_1](https://user-images.githubusercontent.com/125208115/218324465-f24570b4-fee0-4f6b-aba0-1e5c3ef96e3a.jpg)
![20230212083236_1](https://user-images.githubusercontent.com/125208115/218324471-e23400eb-582b-4ad6-bde9-ebe929474dd0.jpg)
these should explain my problem my pc is a pretty strong pc with 20 gbs of storage so please help I love dmc5 and cant play

**Comment by K0bin** [comment]
It really doesn't explain the problem. I don't know what the game normally looks like.

You've also left out all the necessary information that the issue template asked for as well as the logs and the apitrace.

**Comment by sushithebird** [comment]
![download](https://user-images.githubusercontent.com/125208115/218326022-b3ae3a5e-863f-4221-9a85-f314f815aba8.jpg)
this is what it is supposed to look like

**Comment by sushithebird** [comment]
there is supposed to be buildings and some times the floor glitches in and out

**Comment by sushithebird** [comment]
here is a bunch of random stuff that can possibly help
[dxgi.log](https://github.com/doitsujin/dxvk/files/10716723/dxgi.log)
cant get the configs

**Comment by Blisto91** [comment]
Does this also happen without reshade?

**Comment by K0bin** [comment]
You're not even using DXVK, are you? DXVK isn't compatible with ReShade on Windows.

**Comment by kassindornelles** [comment]
You need to post more information...

Are you on Windows or Linux?
If on linux are you using proton? 
What proton version?
what GPU is that? AMD, NVIDIA or Intel?
what driver are you using?
Also the game defaults to Directx 12, are you on 12 or 11? 
check the dmc5config.ini file in the game main folder and show what is in the line that says "TargetPlatform="

Also what kobin said above, DXVK and reshade on windows is messy if not completely broken.
If the game is running on directx 12 you are likely not even using DXVK at all since it supports only DX 9/10/11

**Comment by sushithebird** [comment]
Windows, Intel, idk what driver, Direct 11,

**Comment by sushithebird** [comment]
but it is automatticly direct 12 but I changed it

**Comment by K0bin** [comment]
I strongly suspect youre not even using DXVK and even if you are, this is most likely an Intel driver bug. If you can't even be bothered to find out what driver version you're using and provide actual DXVK logs, I don't see the point of this.

**Comment by sushithebird** [comment]
where can I see what driver I have?

**Comment by K0bin** [comment]
In the DXVK logs for example

**Comment by sushithebird** [comment]
yeah cant find them could you explain more?

**Comment by sushithebird** [comment]
[Render]
PCTargetAPIFallback=Enable
Capability=DirectX11
TargetPlatform=DirectX11
UseOptimizeShader=Enable
LastCrashReport=
[RenderConfig]
FovHackEnable=false
RenderingMethod=Interlaced
ImageQualityRate=0.5
Fov=40
FullScreenDisplayMode=177
FullScreenMode=true
WindowMode=FullScreen
VSync=false
FramerateSetting=VARIABLE
AntiAliasing=FXAA_TAA
MotionBlurEnable=false
DepthOfFiledEnable=true
ShadowQuality=LOW
ContactShadowSetting=CUSTOM
DynamicShadowEnable=true
ShadowCacheEnable=false
TransparentBufferQuality=NONE
MeshQuality=LOW
TextureQuality=LOWEST
StreamingTextureLoadLevelBias=1
SamplerQuality=Trilinear
AOSetting=NONE
SSRSetting=OFF
SSSSSetting=OFF
BloomEnable=false
LensFlareEnable=false
ChromaticAberration=false
EffectVolume=0.300000012
ColorSpace=SRGB
here are my configs

**Comment by K0bin** [comment]
The config file of the game is completely useless to us.

DXVK creates files called `DMC5_d3d11.log` and `DMC5_dxgi.log` right next to the exe or your game. If those files don't exist, you aren't using DXVK to begin with.

**Comment by sushithebird** [comment]
there is only one called amd_ags_x64.dll but no I do not have DMC5_d3d11.log or DMC5_dxgi.log

**Comment by mbriar** [comment]
If those log files are not created next to the .exe then you're not even using DXVK.

**Comment by sushithebird** [comment]
how do i use them

**Comment by Blisto91** [comment]
Before that, do you know what dxvk is and what it does?

**Comment by mbriar** [comment]
You need to get rid of reshade and place the 64bit dxgi.dll and d3d11.dll from DXVK next to the .exe. But yes, usually there is rarely a good reason to use it on windows.

**Comment by sushithebird** [comment]
where do i get it also i dont use nvidia

**Comment by Blisto91** [comment]
https://github.com/doitsujin/dxvk/releases

> also i dont use nvidia.

Og sorry I'm probably mixing issues in my head.

**Comment by sushithebird** [comment]
k hope this works

**Comment by Blisto91** [comment]
Next to the exe

**Comment by sushithebird** [comment]
did not work should I just give up?

**Comment by Blisto91** [comment]
You should at least look for help elsewhere since this isn't dxvk. What ever is the cause of the issue.
dxvk also isn't meant to "fix games"
