### ISSUE TITLE
Multiple games cause GPU hang

### ISSUE THREAD

**Issue by qsniyg** [doitsujin/dxvk#325]
Mass effect worked fine for ~5-10 minutes, then it caused the GPU hang. Saints Row was probably close to ~30 minutes to an hour. This was under DXVK 0.42. I'm aware of #252,  but this is under an NVIDIA card (Intel CPU). It seems to be similar to #269, but with different games, and an Intel CPU.

I'm going to try soon with master, and attach logs.

### Software information
Mass Effect: Andromeda - Ultra settings
Saints Row 3 - Ultra settings

### System information
- GPU: GTX 660 Ti (2GB VRAM)
- Driver: NVIDIA 390.48
- Wine version: Wine-staging 3.6
- DXVK version: 0.42

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log:

**Comment by jarrard** [comment]
You should try also at low graphics settings to see if its a specific setting doing the crashing.

**Comment by qsniyg** [comment]
Good idea, I'll try that as well.

**Comment by doitsujin** [comment]
Please test with latest `master` and enable Vulkan validation layers (i.e. `export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation`).

**Comment by winiciuscota** [comment]
@doitsujin playing mk x on playing on 3840x1024 and max settings causes my gpu to hang on x-ray moves and some fatalities. On 1280x1024 the fps drops a lot on these situations but is able to run fine. Settinng VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation would help on this situation?

**Comment by doitsujin** [comment]
Vulkan validation layers could maybe help debug the issue if it is a DXVK bug.

**Comment by Guy1524** [comment]
Have you tried the 396 beta drivers?  They work better in general.

**Comment by sambow23** [comment]
I don't recommend 396.18.05 as it caused performance issues in FC5, and maybe other games.
Your best chance is to use the 396.18.02 drivers.

**Comment by jarrard** [comment]
Was the performance issue not related to the new shader compiler which can be turned off?

**Comment by kas0079** [comment]
I found a spot in NieR:Automata where the GPU hang happens in a fairly consistent way.

**Software information**
NieR:Automata with settings `Anti-aliasing: x2, effects: High, and Ambient Occlusion: On`, are sufficient to cause the crash. (the rest of the graphics settings can be off or low)
Ran the game with `DXVK_HUD=1 DXVK_LOG_LEVEL=debug VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation WINEARCH=win64`
The hang occurs in the level: "Bunker", while running around or sometimes just on exiting the menu.

**System information**
GPU: GTX 1060 (6GB VRAM)
Driver: NVIDIA 390.48-12 
Wine version: Wine-staging 3.7
DXVK version: `Master`

**Log files**
d3d11.log: [NieRAutomata_d3d11.log](https://github.com/doitsujin/dxvk/files/1976060/NieRAutomata_d3d11.log)
dxgi.log: [NieRAutomata_dxgi.log](https://github.com/doitsujin/dxvk/files/1976061/NieRAutomata_dxgi.log)

I tried `winetricks vulkansdk` with `DXVK_DEBUG_LAYERS=1` but then I got the error:
> "ERROR : Graphic::Startup() FAILED.
> No Graphic Memory"

When launching the game. I can try with a clean wine prefix and look into apitrace tomorrow, if it would help the debugging.

**Comment by doitsujin** [comment]
@kas0079 There's a bit of a game bug with Nier and MSAA enabled. a55bee95548e0c0b2237bb54f6f98ed08f98c112 should hopefully fix this particular issue.

**Comment by kas0079** [comment]
@doitsujin Thanks, that solved it for me.

**Comment by sdack** [comment]
Try disabling "Allow Flipping" in the Nvidia driver settings. This has stopped the hangs for two games so far.

https://github.com/doitsujin/dxvk/issues/341#issuecomment-392338148

**Comment by jarrard** [comment]
It should be mentioned that some games will hang if you don't enable the new compiler. I have noticed that a few times, so now I never disable it (might be 1 exception but I can't remember what).

**Comment by doitsujin** [comment]
Please test if this is still an issue with 396.26.**10** (see #433).

**Comment by mmatis** [comment]
I have frequent crashes in Skyrim Special Edition usually during combat involving lots of fire and effects, or when I die. At first I thought it was just one problematic region, but it seems connected to the amount of lights or effects on screen. Sound/music continues to play and system is semi-responsive. I can ctrl-alt-F2 to a tty and kill skyrim from there and then the system is fine. Here are the facts:

- Card NVidia GTX 660Ti, 2GB
- Wine 3.10 (compiled manually)
- DXVK 0.6.3
- Binary Driver 396.45
- GPU temp at time of crash ~60 degrees C
- VRAM usage at time of crash ~1600MB (on medium settings)

Here is what I have tried with no effect:

- Setting graphics options as low as they will go.
- With/Without Sync to Vblank
- With/Without Full Composition Pipeline
- With/Without Allow Clipping
- Rolled back driver to 390.77
- Tried a nightly build of master from 7/27
- Tried in windowed/borderless mode
- Disabled as many mods as possible while still allowing my test save to work.
- Test save freezes ~7 out of 10 times at some point during battle. 
- See attached debug logs

I'm fairly confident it isn't mods. I remember experiencing this same type of freeze back when I was just trying to get the game to run well before I installed any mods. I just hadn't played long enough to realize at the time how persistent it would be. However, if the log files I've attached don't reveal anything I'll start a new game 100% vanilla and try to reproduce the same behavior.
[SkyrimSE_d3d11.log](https://github.com/doitsujin/dxvk/files/2238857/SkyrimSE_d3d11.log)
[SkyrimSE_dxgi.log](https://github.com/doitsujin/dxvk/files/2238858/SkyrimSE_dxgi.log)



Please let me know if there is any more information I can provide or other things I could try. Thank you.

**Comment by qsniyg** [comment]
I have tried Saints Row 3 for a few hours and no crashes so far (Nvidia 396.54). I'll try Andromeda once I get a chance, hopefully with the same results.

**Comment by Skipperro** [comment]
I have a similar problem with **Assassin's Creed IV: Black Flag**.
In prologue everything is working fine, perfect graphic quality on ultra settings, constant 60 FPS.
As soon as I leave first island and arrive at Abstergo office or Havana, GPU freezes. Trying to load again also freeze GPU in black screen between loading animation and game. Since with frozen GPU there is a massive input lag, often PC reset is the quickest recovery from this freeze.

Only way to actually see Havana is to disable DXVK, but then performance drop unplayable to 2-3 FPS. 

Tried following settings:

- Game settings - everything - low, high, vsync on/off, AA on/off, fog, shadows ect.
- DXVK versions: from 0.52 to 0.71
- Wine Versions: from 3.9 staging to 3.14 staging.
- Driver version: 396.45 and 396.54
- NVIDIA Setting: Allow flipping on/off, Vsync on/off, Composition Pipeline on/off.
- VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation
- GL_NextGenCompiler=0/1

System: Linux Mint 18
GPU: Titan Xp

Right now game is unplayable past prologue. 👎

**Comment by jarrard** [comment]
Tried 396.54.02?

**Comment by Skipperro** [comment]
> Tried 396.54.02?
Ummm.... I'm not sure. I've installed 396.54-0ubuntu0~gpu14.04.1 version from repository.
Where can I get this version?

**Comment by Skipperro** [comment]
Unfortunately with driver 396.54.2 it works exactly the same. :-1: 
As soon as loading game-save is finished everything stops.

![dxvk](https://user-images.githubusercontent.com/20705647/44989383-f5917400-af8d-11e8-859b-ff34571f7a41.png)

**Comment by qsniyg** [comment]
Interestingly enough, other games have worked fine, I haven't had any GPU hangs with Saints Row 3 (one of the two games that were broken), but Mass Effect Andromeda still causes them.

NVIDIA 410.73
DXVK 0.92

**Comment by doitsujin** [comment]
Refer to #906 for the AC:Black Flag issue.
