### ISSUE TITLE
Presentation issues on Wayland since DXVK version 1.9.2 - heavy stuttering despite stable frame times + adaptive sync issues

### ISSUE THREAD

**Issue by fililip** [doitsujin/dxvk#3251]
All DX9 & DX11 (possibly DX10 too) games suffer from heavy stuttering despite stable frame times on Wayland (tested on both KDE Plasma and GNOME) since DXVK 1.9.2.

Adaptive sync does not help - anything above 60 fps forces the refresh rate to the maximum available one (165hz in my case). 60 fps seems to work just fine with adaptive sync - the refresh rate is set.

Enabling/disabling vsync, fiddling with frame rate limiting (above 60 fps) and similar solutions do not change the status quo, even with adaptive sync.

### Software information
Any game rendered via DXVK (DX11 Unity games, DX9 games like Black Mesa, etc.)

### System information
- GPU: AMD Radeon RX 6600 XT
- Driver: amdgpu, Mesa RADV 22.3.4
- Wine version: any (tested on Lutris' 6.22, Proton 7.0, as well as Proton Experimental)
- DXVK version: >=1.9.2, 1.9.1 and below work fine

### Apitrace file(s)
- [MEGA download link](https://mega.nz/file/w8R3HRrR#8jkL23dFqSTTrkymajdPtlmz_Ity32n2oLu50QmssaM)

### Log files
No log files seem to be generated.

**Comment by doitsujin** [comment]
Been running KDE Wayland on a single monitor setup (144Hz with VRR) for well over a year now and can't confirm this in any way.

**Comment by fililip** [comment]
After further testing I've concluded that this seems to happen in select games, not all are susceptible to this.
Black Mesa (DX9) and some Unity games (DX11) on DXVK >=1.9.2 have this issue, while Ghostrunner (DX11), BeamNG.drive (DX11) do not.

Is there anything that changed the presentation framework in DXVK after 1.9.1?

**Comment by doitsujin** [comment]
I've tested Black Mesa in the past and it was fine here too.

Not sure what we changed but I don't think there's any real bug on our end.

**Comment by fililip** [comment]
Alright, I think I've figured it out - using the `ondemand` fixes the issue. I have no idea why, but it does.
