### ISSUE TITLE
Beyond Divinity unable to launch

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3253]
Port of https://github.com/Joshua-Ashton/d9vk/issues/215 with fresh logs and trace.
Don't know if the external link from the original issue is helpful https://sourceforge.net/p/dxwnd/discussion/general/thread/29148efa/

Game will complain about "not enough texture memory" on launch and then shut down again. Works with wined3d.
Haven't found any config options yet that affect it.

![Screenshot_20230215_180449](https://user-images.githubusercontent.com/47954800/219103498-3fc3a222-8320-425f-a931-2e9047c5e779.png)

### Software information
Beyond Divinity

### System information
- GPU: 7900xtx
- Driver: mesa-git
- Wine version: Proton-experimental
- DXVK version: master

### Apitrace file(s)
https://mega.nz/file/NwAQWBLT#6LRgvL21HHC21orA2d91Pghc-PWvECWqCIhnvN0UC0E
(Replays fine)

### Log files
[div_d3d9.log](https://github.com/doitsujin/dxvk/files/10745632/div_d3d9.log)

**Comment by WinterSnowfall** [comment]
@Blisto91 Have you also tried the infamous `d3d9.allowDirectBufferMapping = False`?

**Comment by Blisto91** [comment]
Fixed by https://github.com/doitsujin/dxvk/pull/3288 :tada:
