### ISSUE TITLE
Killer Is Dead crashing

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3254]
Port of https://github.com/Joshua-Ashton/d9vk/issues/258 with fresh logs and all (at least i think it's the same issue)

Game crashes a little bit inside the first cutscene in the second chapter, just before the character speaks and subtitles appear. Works with wined3d.

### Software information
Killer Is Dead

### System information
- GPU: 7900xtx
- Driver: mesa-git
- Wine version: Proton experimental
- DXVK version: Master

### Apitrace file(s)
https://mega.nz/file/k5gTkJxY#Xz6wxVTAinEGvPJZQD-xNWsFWHBpPbNtjdO-sSuwRAQ
(Replays fine)

### Log files
[KidGame_d3d9.log](https://github.com/doitsujin/dxvk/files/10746007/KidGame_d3d9.log)
[KidGame_d3d11.log](https://github.com/doitsujin/dxvk/files/10746010/KidGame_d3d11.log)
[KidGame_dxgi.log](https://github.com/doitsujin/dxvk/files/10746011/KidGame_dxgi.log)
[Launch-backup-2023.02.15-18.52.42.log](https://github.com/doitsujin/dxvk/files/10746025/Launch-backup-2023.02.15-18.52.42.log)

Game itself is d3d9

**Comment by Blisto91** [comment]
Trace where it crashes with dxvk
https://mega.nz/file/ptYCCIiJ#h2q06OrOLFa4pCO9QaysYGW2awG_w8EQkr1gH58dugo

**Comment by NerosTie** [comment]
Can you test "Method 3" from https://www.pcgamingwiki.com/wiki/Killer_Is_Dead#Crash_after_boss_fights ?

It worked on my side.

**Comment by Blisto91** [comment]
For some reason i'm not able to get it to crash all of a sudden even without the method

**Comment by Blisto91** [comment]
I'm gonna close this because it seems to have fixed itself.
If you still have a issue related to dxvk @NerosTie then just say so and we can reopen.
