### ISSUE TITLE
NFS Most Wanted 2012 segfaults with DXVK's DXGI

### ISSUE THREAD

**Issue by TheComputerGuy96** [doitsujin/dxvk#3259]
So NFS Most Wanted 2012 segfaults with DXVK's DXGI (Wine's DXGI works fine but DXVK v2.0 or v2.1 broke this)

This issue only happens on NVIDIA for some reason (if I switch to my AMD iGPU the game works fine)

WineD3D obviously works fine because it doesn't use DXVK DLLs

### Software information
As you can see in the title, it's NFS Most Wanted 2012 (that Criterion game with Burnout characteristics)

Settings don't matter as the game crashes before creating a window

### System information
- GPU: NVIDIA GTX 1650 Ti/AMD Renoir iGPU
- Driver: 525.89.02 (NVIDIA)/Mesa 22.3.4 (AMD)
- Wine version: v8.1 (staging)
- DXVK version: v2.1 (this also happens with DXVK v1.10.3; other versions untested)

### Apitrace file
[NFS13.zip](https://github.com/doitsujin/dxvk/files/10771772/NFS13.zip)

The trace was done with DXVK v2.1 (so the game obviously crashed) and it's under 10 KiB

### Log files
- d3d11.log: https://pastebin.com/zH4pBBQG
- dxgi.log: https://pastebin.com/8irmmdty
- Wine crash log: https://pastebin.com/eC0Whc2h

**Comment by mbriar** [comment]
You should make the apitrace with something that doesn't crash.

**Comment by TheComputerGuy96** [comment]
Setting `DXVK_FILTER_DEVICE_NAME=NVIDIA` variable makes DXVK's DXGI work :thinking:

**Comment by mirh** [comment]
By any chance, could you try drivers older than 522?

**Comment by Riesi** [comment]
Game seems to launch fine for me with only one Nvidia GPU also running `525.89.02`.
So this is very likely to do with the multiple devices.
I might be able to get my intel iGPU going too, but not sure when I can try that.

**Comment by Blisto91** [comment]
@TheComputerGuy96 Friendly ping. Please retest this when you when you have time

**Comment by Blisto91** [comment]
@TheComputerGuy96 Double friendly ping.
I just tried starting the game in Steam via Proton Experimental Bleeding Edge with dxvk 2.1 and KDE Plasma X11. Nvidia GPU hooked up to monitor in a system also with a AMD iGPU. Nvidia driver is 550.40.71

**Comment by TheComputerGuy96** [comment]
> Nvidia driver is 550.40.71.

Why isn't it 560 though? Is there some mysterious issue (like swapchain recreation loop)?

**Comment by Blisto91** [comment]
Because it's what I had installed

**Comment by TheComputerGuy96** [comment]
> It's what I had installed

Right now I can't run any DXVK game on my NVIDIA GPU with the 560 driver (the swapchain keeps getting recreated with the `nvidia` driver being displayed in `perf top` and the window just hangs) so this issue will have to remain in a non-binary state for now

**Comment by mirh** [comment]
Dxvk 2.4.1 changelog specifically mentioned some swapchain issue being fixed.

**Comment by TheComputerGuy96** [comment]
Update: I was able to test the game with NVK instead and the relevant segfault seems fixed in DXVK 2.2 (which is the next version after 2.1); I'm not sure if commit https://github.com/doitsujin/dxvk/commit/83a294285e90c65554bc851c4d4a126aa15916a4 was the one that fixed it though

**Comment by mirh** [comment]
I'm skeptical you should consider this "good for sure" when you straight-up changed the driver.

**Comment by Riesi** [comment]
If nobody can reproduce or verify the bug then it basically doesnt exist.

If one can reproduce again, we can reopen.
