### ISSUE TITLE
Battle.net crashes with DXVK, runs fine without

### ISSUE THREAD

**Issue by Smoerrebroed** [doitsujin/dxvk#3261]
I have run into a situation where it is not possible to successfully start the Battle.net client with DXVK enabled. Trying to do so, winedbg opens automatically after a couple of seconds.

I'm running Arch Linux with the latest nVidia drivers:

Kernel 6.1.12
nVidia 525.89.02
Wine Staging 8.1
(DXVK 2.1)

After setup_dxvk uninstall, things work fine, but then I don't have acceleration which gives me approx. 60 fps in WoW vs. 180 fps with DXVK active. It's noteworthy that WoW itself runs just fine with DXVK enabled, so this seemingly affects only Battle.net.

**Comment by Blisto91** [comment]
Hello.
Please share dxvk logs.

**Comment by Blisto91** [comment]
I haven't been able to reproduce so far.
This is with regular wine 8.1 on Arch and a 7900xtx with mesa git

<details>
  <summary>Screenshot</summary>

![Screenshot_20230218_162914](https://user-images.githubusercontent.com/47954800/219874243-fe0f47a2-7315-4574-9a25-ff7e3f435dbc.png)
</details>

**Comment by Smoerrebroed** [comment]
Ooops, sorry for that. Wanted to add this once I get back to my main machine, but You guys are fast ...

Anywhere, here's the log from Battle.net:
> info:  Game: Battle.net.exe
> info:  DXVK: v2.1
> info:  Built-in extension providers:
> info:    Win32 WSI
> info:    OpenVR
> info:    OpenXR
> info:  OpenVR: could not open registry key, status 2
> info:  OpenVR: Failed to locate module
> info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x6fa837c0
> info:  Required Vulkan extension VK_KHR_surface not supported
> err:   DxvkInstance: Failed to create instance

However, this is the log from Wow.exe:

> warn:  DXGIDeclareAdapterRemovalSupport: Stub
> warn:  CreateDXGIFactory2: Ignoring flags
> info:  Game: Wow.exe
> info:  DXVK: v2.1
> info:  Built-in extension providers:
> info:    Win32 WSI
> info:    OpenVR
> info:    OpenXR
> info:  OpenVR: could not open registry key, status 2
> info:  OpenVR: Failed to locate module
> info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x2d4ad3f20
> info:  Enabled instance extensions:
> info:    VK_KHR_get_surface_capabilities2
> info:    VK_KHR_surface
> info:    VK_KHR_win32_surface
> info:  NVIDIA GeForce GTX 1080:
> info:    Driver: 525.89.2
> info:    Vulkan: 1.3.224
> info:    Memory Heap[0]: 
> info:      Size: 8192 MiB
> info:      Flags: 0x1
> info:      Memory Type[7]: Property Flags = 0x1
> info:    Memory Heap[1]: 
> info:      Size: 48164 MiB
> info:      Flags: 0x0
> info:      Memory Type[0]: Property Flags = 0x0
> info:      Memory Type[1]: Property Flags = 0x0
> info:      Memory Type[2]: Property Flags = 0x0
> info:      Memory Type[3]: Property Flags = 0x0
> info:      Memory Type[4]: Property Flags = 0x0
> info:      Memory Type[5]: Property Flags = 0x0
> info:      Memory Type[6]: Property Flags = 0x0
> info:      Memory Type[8]: Property Flags = 0x6
> info:      Memory Type[9]: Property Flags = 0xe
> info:    Memory Heap[2]: 
> info:      Size: 246 MiB
> info:      Flags: 0x1
> info:      Memory Type[10]: Property Flags = 0x7
> info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
> info:  Adapter LUID 0: 0:3f6
> err:   readMonitorEdidFromKey: Failed to get EDID reg key size
> err:   DXGI: Failed to parse display metadata + colorimetry info, using blank.
> info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
> info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
> warn:  DXGI: MakeWindowAssociation: Ignoring flags

Looks a bit inconsistent to me. BTW, mesa version is also the latest available (22.3.4) in case that's important.

**Comment by Blisto91** [comment]
> info: Required Vulkan extension VK_KHR_surface not supported

This indicates a driver issue. Make sure you also have the 32bit Vulkan driver installed `lib32-nvidia-utils`

**Comment by Smoerrebroed** [comment]
Yep, that seems to work now. Thanks! Looks like there's a dependency missing in the dxvk-bin package for Arch, and lib32-nvidia-utils was removed as a consequence.

**Comment by Blisto91** [comment]
Np. Have fun :slightly_smiling_face:

**Comment by NguyenHoangHieu22GIT2** [comment]
> > info: Required Vulkan extension VK_KHR_surface not supported
> 
> This indicates a driver issue. Make sure you also have the 32bit Vulkan driver installed `lib32-nvidia-utils`

I'm so glad I found your comment :) this does fix my mortal kombat komplete edition. Thank you so much.
