### ISSUE TITLE
[D3D11] Distance performance issues

### ISSUE THREAD

**Issue by CommanderAlchemy** [doitsujin/dxvk#3263]
![image](https://user-images.githubusercontent.com/3089330/219903141-38173ab3-0d0f-4fb4-a324-a6402572baa1.png)

### Software information
[Distance](https://store.steampowered.com/app/233610/Distance), (everything maxed out)
Shadows and Reflections tank the performance

### System information
- CPU: 5900X
- GPU: 6900XT
- Driver: Mesa 22.3.4
- Wine version:  Proton 7.0-6
- DXVK version:  1.10.3

### Apitrace file(s)
- tbd

### Log files
- [d3d11.log](https://gist.github.com/CommanderAlchemy/4a2ac295a5545432f1d62dd18e0b6326)
- [dxgi.log](https://gist.github.com/CommanderAlchemy/5d8884b75f7dd61bc274c47528f38506)

**Comment by Blisto91** [comment]
Apparently this game is ultra weird and tanks massively in perf if it sees too many cores.
Try to launch with `WINE_CPU_TOPOLOGY=4:0,1,2,3`and see if that doesn't fix it for you.
More or less cores only seem to make it worse.

**Comment by Blisto91** [comment]
If it is of interest to anyone

![Screenshot_20230219_011819](https://user-images.githubusercontent.com/47954800/219905436-8ca52da1-0bb0-4b25-8e0b-1b9a3323444a.png)

**Comment by CommanderAlchemy** [comment]
> Apparently this game is ultra weird and tanks massively in perf if it uses too many cores. Try to launch with `WINE_CPU_TOPOLOGY=4:0,1,2,3` and see if that doesn't fix it for you. More or less cores only seem to make it worse (at least for me)

Odd I remember that I tried to do it before but it seems that this somewhat worked. 
I get around 100-200FPS now, though there are some real slowdowns to sub 30 from time to time depending on whats happening.

I'm trying to find a way to repro it as quick as possible and then run an apitrace to upload. Is there a way to run api trace from steam or do I need a fresh wineprefix?

**Comment by Blisto91** [comment]
If it's through steam with dxvk activated then you can just put the apitrace dlls next to the exe and start the game as normal. The trace file should appear in the desktop folder of the games compatdata prefix.
