### ISSUE TITLE
[D3D9] Dungeon & Fighter UI rendering black screen color square problem.

### ISSUE THREAD

**Issue by hauntek** [doitsujin/dxvk#3266]
Hello, I'm running the **Dungeon & Fighter** game. I ran a problem

Using the image is DirectX 9, The latest version of dxvk 2.0 and 2.1 crashes and exits the game directly and cannot run, but I use dxvk1.10.1 and everything is normal. When I switch back to dxvk1.10.2 or 1.10.3, the black screen, blurred screen, models, etc. cannot be normal.

![8TE5`K8Q{J8}0GNIM`2M9 K](https://user-images.githubusercontent.com/17927997/221091449-42a0ed57-db12-45d5-af0b-5d43893bf295.png)

![5AF_`_1)AR YG53%_} F33M](https://user-images.githubusercontent.com/17927997/221090807-8bc980f0-3922-473a-aafc-ee25096a9728.png)

**I am directly in the windows 10 system to replace d3d9. DLL to run the game**

### Software information
**Dungeon & Fighter x64 bit client**, High texture, high quality, shadow, windowing (800x600), vertical synchronous open.

### System information
- GPU:Intel UHD Graphics 730
- Driver:31.0.101.2111
- Wine version: -
- DXVK version: 1.10.2 and 1.10.3

### Log files
[dnf_d3d9.log](https://github.com/doitsujin/dxvk/files/10820654/dnf_d3d9.log)

**Comment by hauntek** [comment]
@K0bin @nforestcat @Blisto91

**Comment by Blisto91** [comment]
Hello.

If possible see if you can make a apitrace without dxvk and attach it here. Will potentially make it easier for the devs to look at the issue.
https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

**Comment by hauntek** [comment]
https://drive.google.com/file/d/1EM6VCAfMWpoygel5V3nvWzrdp1iZiRLE/view?usp=share_link

@Blisto91

**Comment by Blisto91** [comment]
I have been unable to reproduce the issue on Linux amd with both the trace and ingame.
Might be a Intel Windows driver issue.

![Screenshot_20230224_210818](https://user-images.githubusercontent.com/47954800/221281847-b0c316c2-d976-4840-9094-17079387b7d3.png)

**Comment by hauntek** [comment]
[dnf_d3d9-dxvk1.10.2.log](https://github.com/doitsujin/dxvk/files/10832874/dnf_d3d9-dxvk1.10.2.log)

[dnf_d3d9-dxvk2.1.log](https://github.com/doitsujin/dxvk/files/10832876/dnf_d3d9-dxvk2.1.log)
[dnf_dxgi-dxvk2.1.log](https://github.com/doitsujin/dxvk/files/10832879/dnf_dxgi-dxvk2.1.log)

The cause of the dxvk1.10.2-1.10.3 color blurred screen, and the cause of the dxvk2.0-2.1 program crash and exit actually appeared on the intel gpu, because I tested dxvk1.10.2~dxvk2.1 on the nvidia gpu computer and everything is normal.

@Blisto91

**Comment by hauntek** [comment]
The above problems only appear in Intel Windows driver issue, nvidia gpu and amd gpu are all normal.

@Blisto91

**Comment by K0bin** [comment]
Make sure your GPU driver is up to date. The one you're using seems a bit old at this point.
