### ISSUE TITLE
DXVK ELDER SCROLL ONLINE WINE STAGING 3.6 GTX 1080 TI

### ISSUE THREAD

**Issue by linuxhell** [doitsujin/dxvk#327]
WINE STAGING 3.6
DXVK
LINUX MINT 18
NVIDIA DRIVER 396.18.05/368.18
gtx 1080 ti

the only thing that needs to be fixed to stay 100% are small freezes with 1 second duration (like pause/recharge) that occur from time to time and always in the same interval

the rest is all ok !!!  fps 80/90/100 

my youtube movie running ELDER SCROLL ONLINE DXVK
https://www.youtube.com/watch?v=XRGEOYdjCpo&t=2s

**Comment by doitsujin** [comment]
This is not a place to advertise Youtube channels.
