### ISSUE TITLE
Dawn of Magic 2 - Crash upon starting a new game.

### ISSUE THREAD

**Issue by jrugia** [doitsujin/dxvk#3271]
Attempting to launch Dawn of Magic 2 in dxvk causes it to crash upon attempting to start a new game (game loads fine up to the main menu and character creation). Being a 32bit game I suspected maybe it's running out of virtual memory but it doesn't appear to be the case. Tried various dxvk releases but still same error occurs. Game otherwise works fine in WineD3D.

Let me know if I missed anything in the report.

### Software information
- Name of the game: Dawn of Magic 2 (GOG release)
- Settings used: Tried max settings and lowest, seems to be irrelevant what is set.

### System information
- GPU: AMD RX 6800
- Driver: Mesa 22.3.6
- Wine version: 8.2 Staging, 7.15 Staging
- DXVK version: 2.1, 1.10.3, 1.9.4

### Apitrace file(s)
Link - https://drive.google.com/file/d/1k4X_gRU-T8jrf3dubxDhYHSsS4hr5Tm-

### Log files
- d3d9.log:  [dawnofmagic2_d3d9.log](https://github.com/doitsujin/dxvk/files/10864693/dawnofmagic2_d3d9.log)

##Additional:

The game crashes with the below error
![1](https://user-images.githubusercontent.com/13750621/222248508-dbcf9919-53b6-40e8-b341-9c518454b6d0.jpg)

**Comment by Blisto91** [comment]
Thank you for the issue. Trace replays fine but can confirm ingame.

**Comment by Blisto91** [comment]
I can get ingame if i turn off "Landscape bump-mapping"

**Comment by K0bin** [comment]
> 3618418 @0 IDirect3DDevice9::SetTextureStageState(this = 0x7cf04f0, Stage = 13, Type = D3DTSS_TEXTURETRANSFORMFLAGS, Value = D3DTTFF_DISABLE) = D3D_OK
3618418: warning: failed with 0x8876086c (D3DERR_INVALIDCALL): Invalid call

> Stage identifier of the texture for which the state value is set. Stage identifiers are zero-based. Devices can have up to eight set textures, so the maximum value allowed for Stage is 7.
