### ISSUE TITLE
Borderlands 1 GOTY Enhanced Crashing on Windows with DXVK

### ISSUE THREAD

**Issue by xEden95x** [doitsujin/dxvk#3274]
Hi all,

Borderlands 1 has terrible frame pacing issues with DX on Windows - DXVK seems like it fixes them, but I'm getting constant crashes.

Originally, I was having SteamOverlayVulkanLayer64.dll crash on me - renaming this in Steam seemed to fix that.

Now I'm running into a new error, where vulkan-1.dll seems to be causing the crash. I've attached my logs and the crash reports to this post.

Would anyone be able to offer some insight into this?

Many thanks

[BorderlandsGOTY_d3d11.log](https://github.com/doitsujin/dxvk/files/10874187/BorderlandsGOTY_d3d11.log)
[BorderlandsGOTY_dxgi.log](https://github.com/doitsujin/dxvk/files/10874188/BorderlandsGOTY_dxgi.log)
[Report.txt](https://github.com/doitsujin/dxvk/files/10874197/Report.txt)

**Comment by xEden95x** [comment]
Error codes are 0000000000000007 and c0000409 if that helps at all!

**Comment by Blisto91** [comment]
I see that you have RTSS installed. Can you either try to uninstall that or update it if it's out of date.

**Comment by xEden95x** [comment]
...hah! I actually just did a fresh boot after updating my graphics drivers and it doesn't crash when RTSS isn't open.

Unfortunately the stutters *are* still there, but that's not a DXVK issue.
