### ISSUE TITLE
Hud permanently enabled for all games

### ISSUE THREAD

**Issue by zxcvghjiop** [doitsujin/dxvk#3277]
**Problem Description**
I enabled the DXVK fps hud via Steam launch options for ONE game through "DXVK_HUD=1 %fps%". The hud is now enabled in ALL of my games launched through Steam or Lutris, despite removing the launch option, and I can't find a way to disable it. Furthermore, I can't get it to display any different information - other launch options affecting the hud no longer work, nor does editing user_settings.py.

**System**
DXVK version 1.10.3
Lutris 0.5.12
Proton experimental-7.0-20230227
Drivers: Nvidia version 525.85.05

**Comment by K0bin** [comment]
You must have a set up a global environment variable for the HUD somewhere or set up a config file used by all games that enables it.

**Comment by zxcvghjiop** [comment]
>You're sure, what you're seeing is the DXVK HUD and not for example the Steam FPS counter?

Absolutely. I can enable them both concurrently. Give me a moment and I can upload a screenshot.

**Comment by Blisto91** [comment]
Also if you can then share logs from a game. Then we can check if it's a config file it's picking up

**Comment by doitsujin** [comment]
Either way, this is 100% a user error and not a bug. DXVK **never** stores any environment variables or configuration persistently on its own.

**Comment by zxcvghjiop** [comment]
Here is a screenshot from Crusader Kings 2. As you can see both DXVK's hud and Steam's are visible in the upper corners.

![ck2SS](https://user-images.githubusercontent.com/126891269/222779792-2e963ca5-a91c-4b76-bb2d-51e928d1d28f.jpg)

`echo $DVXK_HUD` reveals, uh, nothing. Just a blank line. I have already rebooted several times.

Which game logs would contain the information you are looking for?

**Comment by mbriar** [comment]
That is not the DXVK HUD, but the nvidia driver hud.

**Comment by zxcvghjiop** [comment]
Well that's embarrassing. It turned on with the launch command I listed above. How do I turn it off?

**Comment by K0bin** [comment]
Check the Nvidia X11 Settings.

**Comment by mbriar** [comment]
https://superuser.com/questions/1441505/how-to-turn-off-this-kind-of-fps-counter-overlay

**Comment by zxcvghjiop** [comment]
Hey hey, it worked! Thanks for the help lol.
