### ISSUE TITLE
Windows: New Nvidia feature can break DXVK

### ISSUE THREAD

**Issue by Nicholas-Steel** [doitsujin/dxvk#3279]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Windows 10, 22H2

### System information
- GPU: Geforce 1070Ti
- Driver: 527.56 & older
- DXVK version: 2.1

Problem:
I've read https://github.com/doitsujin/dxvk/wiki/Windows and was wondering if mention of this (DXGI) setting should be added to that article.

In Anno 1800 I've observed certain graphics don't render in the game while using DXVK with the **__DXGI Presentation Model__** enabled in the Nvidia Control Panel. What graphics don't render? Floating icons over the top of buildings (production paused, production slowed from worker shortage, storage full, missing resources etc.)

**Comment by K0bin** [comment]
There is nothing we can do about that.

This setting makes Vulkan use DXGI internally. DXVK replaces DXGI with something that uses Vulkan internally, so you end up with infinite recursion.

Problems like these that are entirely out of our control are the main reason why we don't support Windows.

**Comment by Nicholas-Steel** [comment]
> There is nothing we can do about that.
> 
> This setting makes Vulkan use DXGI internally. DXVK replaces DXGI with something that uses Vulkan internally, so you end up with infinite recursion.
> 
> Problems like these that are entirely out of our control are the main reason why we don't support Windows.

I understand, I just meant that maybe mention of avoiding this setting could be added to the Windows guide.

**Comment by K0bin** [comment]
I added a note to the wiki.

https://github.com/doitsujin/dxvk/wiki/Windows#nvidia-gpus
