### ISSUE TITLE
[d3d9] TrackMania United Forever - Performance regression

### ISSUE THREAD

**Issue by NorbertHarangozo** [doitsujin/dxvk#3283]
Starting with 996acbe3f2eba97a6d3e725a8e7748aa0dd6764a, performance has dropped quite substantially. The exact degree depends on the map, the most extreme example I have found so far was going from ~160 fps to 67 fps on "StarStadiumB3". I used this map for tracing.

### Software information
TrackMania United Forever

### System information
- GPU: GTX 1660 Super
- Driver: 525.89.2
- Wine version: wine-tkg-staging-fsync-git-8.3.r2.gaa366375
- DXVK version: 996acbe3f2eba97a6d3e725a8e7748aa0dd6764a

### Apitrace file(s)
- [TmForever.7z](https://mega.nz/file/Ito3ECJa#EuF4UtF6WQTsoGGpUjZR2liEzdv_OWgrSQf7Xy_kSys)

### Log files
- [TmForever_d3d9.log](https://github.com/doitsujin/dxvk/files/10937065/TmForever_d3d9.log)

**Comment by K0bin** [comment]
Please test that PR, it should fix the issue.

**Comment by NorbertHarangozo** [comment]
I can confirm that the PR fixed the issue, great work!

**Comment by K0bin** [comment]
Thanks for the great bug report!
