### ISSUE TITLE
[Windows] Mouse smooth input

### ISSUE THREAD

**Issue by Mitradis** [doitsujin/dxvk#3287]
On Windows with this wrapper mouse move very smoothly, delayed as if on ice. It is possible reduce mouse input lag? Perhaps there are some settings.

### Software information
any games

### System information
- GPU: 1060
- Driver: latest
- Wine version: 
- DXVK version: 

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:

**Comment by K0bin** [comment]
DXVK does not impact Input at all. There's no code that touches anything mouse related.
