### ISSUE TITLE
GPU DX11 can run DX12 games if using DXVK ?

### ISSUE THREAD

**Issue by Augusto7743** [doitsujin/dxvk#3290]
Hello.
Thanks DXVK creator. Your software is an amazing solution for any WINE user.

Well ... is possible the sequence below ?
Linux host using an Nvidia GPU DX11 ( Kepler 600 series ) > WINE + DXVK 1.10.3 > DX12 game

If DXVK translate DX12 in host Vulkan driver in logic is possible run softwares requiring DX12.

Thanks for reading.
Have an nice week.

**Comment by K0bin** [comment]
DXVK does not support D3D12, vkd3d-Proton does. But even with that, your GPU needs to support the features requires for D3D12. Kepler does not.

**Comment by Augusto7743** [comment]
Thanks for replying.
Any plans to support D3D12 in DXVK future versions ?

**Comment by Blisto91** [comment]
No d3d12 is different enough (or close enough to Vulkan) that it makes sense to keep it separate. vkd3d-proton handles that side which the devs also contribute to.

**Comment by K0bin** [comment]
And even if we did, your GPU is physically not capable of D3D12. The hardware can't support it.

**Comment by Augusto7743** [comment]
GT 640 does 803.3 GFLOPS
https://www.techpowerup.com/gpu-specs/geforce-gt-640-rev-2.c2377

GT 1030 does 1,127 GFLOPS
https://www.techpowerup.com/gpu-specs/geforce-gt-1030.c2954

GT 1030 run RE4 demo in 45 FPS.
GT 1030 is more of half performance of GTX 670
GTX 670 does 2.634 TFLOPS
https://www.techpowerup.com/gpu-specs/geforce-gtx-670.c362

However Geforce 600 not does D3D12.
For me analyzing the performance is as being possible run D3D12 software over Vulkan 1.2.

Thanks for all replies.

"And even if we did, your GPU is physically not capable of D3D12. The hardware can't support it."
Even for GTX 670 using Vulkan 1.2 ?

**Comment by mbriar** [comment]
Vulkan 1.2 isn't enough to support d3d12 feature level 12_0 with vkd3d-proton. And besides, vkd3d-proton performs horribly on all nvidia gpus older than Turing anyways.

**Comment by Augusto7743** [comment]
I when created that topic was to understand if was or not possible run D3D12 games using Vulkan 1.2 in Kepler.
After I had replied to understand some details about as work the convertion between D3D12 code in Vulkan and not for demanding any code for Kepler.
