### ISSUE TITLE
Race Driver Grid Random Crashes to Desktop  or  DxvkMemoryAllocator: Memory allocation failed

### ISSUE THREAD

**Issue by xatornet** [doitsujin/dxvk#3294]
Using DXVK, either version 2.1 or 1.10.3-Async, all seem to crash randomly given some minutes. The log shows 
err:   DxvkMemoryAllocator: Memory allocation failed sometimes, or simply won't give any error on the log, and crash to desktop.

### Software information
Name of the Game: Race Driver: Grid
Settings Used: Irrelevant, it happens on any setting
OS System: Windows 11 Pro Build 22621.1413

### System information
- GPU: Nvidia RTX 3090
- Driver: 531.29
- Wine version: None (Windows native OS used)
- DXVK version: v1.10.3-async / 2.1

### Log files
[DXVK2.1.log](https://github.com/doitsujin/dxvk/files/11017894/DXVK2.1.log)
[DXVK1.10.3.log](https://github.com/doitsujin/dxvk/files/11017909/DXVK1.10.3.log)

**Comment by Blisto91** [comment]
Hello.

If possible please try to make a apitrace 🙂 

Also quickly test with 2.1 if making a file called `dxvk.conf` next to where the log appeared and inserting `d3d9.allowDirectBufferMapping = false` helps.
You can check in the log files afterwards if it was picked up.

**Comment by K0bin** [comment]
#1318 strikes again

**Comment by doitsujin** [comment]
For 32-bit games on Windows you might want to patch the executable to enable the large address aware flag. Running out of address space is extremely common.

**Comment by K0bin** [comment]
The game sat at a comfortable 700MB when I tried it with DXVK. Does it only crash on particular courses?

**Comment by xatornet** [comment]
> Hello.
> 
> If possible please try to make a apitrace 🙂
> 
> Also quickly test with 2.1 if making a file called `dxvk.conf` next to where the log appeared and inserting `d3d9.allowDirectBufferMapping = false` helps. You can check in the log files afterwards if it was picked up.

Hi, If I use the d9d3.dll from the apitrace the game wont crash... maybe I'm not doing it right? 

I'm going to try the dxvk.conf you suggested. Thanks

**Comment by Blisto91** [comment]
> Hi, If I use the d9d3.dll from the apitrace the game wont crash... maybe I'm not doing it right?

That is fine and expected. apitrace is it's own thing and doesn't go through dxvk by default, it instead "records" all the d3d api calls the game makes and the devs can then look at them afterwards with out without dxvk.
So just upload a file where you've played a bit. If it usually crashes relatively fast then just play till after that if performance isn't too horrible.

**Comment by K0bin** [comment]
> Edit: I saw K0bin have the game so maybe this is unnecessary.

But I cant reproduce the problem.

**Comment by xatornet** [comment]
> 

Then here you have it:

https://drive.google.com/file/d/1bvYg_rbcjml_dRjCoZ-QJVnnLfTZOcm6/view?usp=sharing

**Comment by K0bin** [comment]
There's nothing obviously wrong with the apitrace either. It doesn't use a lot of memory.

**Comment by xatornet** [comment]
Ok, I've been tinkering some more. I've narrowed the problem to the way the bloody game detectss the resolution, or should I say, limits the resolution output.

On system/hardware_settings_restrictions.xml, there's this line:

`    <data>
        <res mem="270" maxWidth="1280" />
    </data>`

It tries to limit the memory and maxWidth resolution for the game to detect on first boot. But it's a cluster fuck, as some systems won't detect the resolution properly, others will need maxWidth adjusted to their real max res, other won't need it, and others will refuse to work at all. And If you delete that limitation alltogether, it will randomly work or not. So, **to sum up, I think it has nothing to do with DXVK, so I'm gonna close the issue, not without apologizing for wasting your time.**

Thank you guys and sorry for the inconvenience

**Comment by xatornet** [comment]
My dear friends, I'm back for more :-? 

I've revisited everything in this game, and made some other tinkering. Even downloaded other EGO Engine games to tinker some more. I can say that the game works normally on my end, but, as soon as I put DXVK the game crashes to desktop every time a race is loading. And this is the log:

[grid_d3d9.log](https://github.com/doitsujin/dxvk/files/11022192/grid_d3d9.log)

On some systems it seems to be working fine, but on the one with my RTX 3090 it goes mad.

**Comment by K0bin** [comment]
There's probably nothing we can do here. DXVK hasn't even allocated a lot of memory. Just 162 MB of system memory.

Can you make another apitrace?

**Comment by xatornet** [comment]
> There's probably nothing we can do here. DXVK hasn't even allocated a lot of memory. Just 162 MB of system memory.
> 
> Can you make another apitrace?

https://drive.google.com/file/d/1s4oP82qN94yd9mqavH97LgbKKW7-7e3m/view?usp=sharing

Maybe EGO Engine 1.0 is not very friendly of DXVK. Dirt 2, which uses the same engine, does not really like DXVK too, not even the hud works...

**Comment by K0bin** [comment]
Dirt 2 seems to work fine: https://www.protondb.com/app/690790
Same for GRID: https://www.protondb.com/app/255220

**Comment by jrugia** [comment]
From my experience the first GRID and Dirt games easily ran out of virtual memory on Linux, especially with dxvk.

As doitsujin already mentioned, patching the exe with large address aware flag helps. I haven't had a single memory issue in years since doing so.

**Comment by xatornet** [comment]
> From my experience the first GRID and Dirt games easily ran out of virtual memory on Linux, especially with dxvk. I don't know about Windows but maybe the issue is related?
> 
> As doitsujin already mentioned, patching the exe with large address aware flag helps. I haven't had a single memory issue in years since doing so.

Until further testing, seems that patching with 4GB kinda works. It also breaks the shitty drm from the steam release, but it's fixeable. I'll test it in GOG release tomorrow, and if all works, I'll close the issue.

Thanks you guys

**Comment by xatornet** [comment]
Alright, After testing it on GOG an Steam this are the results:

**DXVK works fine.** 

On AMD GPUs seems that disabling the mem restriction kinda improves the crashing threshold.

The game needs a hardware_settings_restrictions.xml mod to properly fix the pile of s*** of settings detection that it has. (Doing it now, check PCGW)

And, as you guys suggested, **4GB patch for the exe file is NEEDED** in order for it not to crash with DXVK. Warning to users: **_Steam exe file will crash if 4GB patch is applied without removing DRM first._** 

Anyway, thanks for everything guys!! You rock :-)
