### ISSUE TITLE
Resident Evil 4 Crash

### ISSUE THREAD

**Issue by 47MWCSBN** [doitsujin/dxvk#3295]
Hi everyone, i try running Resident Evil 4 with dxvk on windows, and apparently it crash. i check someone with similar spec and they work perfectly.
[https://www.youtube.com/watch?v=1rpD6b_eOBc&lc=UgwyvGRDu7IucNLYSbF4AaABAg.9nQEpjah-LH9nQswvOmUo1](url)

**Software information**
Resident Evil 4 (2005) ROW Steam Version

**System information**
- CPU: Intel i7-1065G7
- GPU: Intel Iris Plus Graphics
- Driver: 31.0.101.2115/31.0.101.1960
- Windows 10 Pro 21H2 19044.2728
- DXVK version: 2.1 

**Log files**
[bio4_d3d9.log](https://github.com/doitsujin/dxvk/files/11021100/bio4_d3d9.log)

**Comment by K0bin** [comment]
Most likely a driver bug.

**Comment by 47MWCSBN** [comment]
Can you tell me which version driver will work?

**Comment by Blisto91** [comment]
We don't know alot of (if any) Windows Intel users so no. Mostly only Linux gets official testing.

**Comment by K0bin** [comment]
> Can you tell me which version driver will work?

The Nvidia one. I don't have any Intel HW, so I have no idea about their drivers.

**Comment by 47MWCSBN** [comment]
maybe someone can check this matter?

**Comment by K0bin** [comment]
![20230321213659_1](https://user-images.githubusercontent.com/1131720/226734732-83cf490a-e541-4722-b2a2-a689bd6b0969.jpg)

Yup, works fine on Nvidia drivers.

**Comment by 47MWCSBN** [comment]
Too bad in Intel cant run :(

**Comment by K0bin** [comment]
Report the bug to Intel.

**Comment by K0bin** [comment]
@adamjer @kdobrowo

**Comment by LethalManBoob** [comment]
broken for me right now

**Comment by Blisto91** [comment]
Make a new issue please
