### ISSUE TITLE
Dragon Age: Inquisition crashes withouth an error message before it's window is visible [Windows]

### ISSUE THREAD

**Issue by janos666** [doitsujin/dxvk#3296]
### Software information
Dragon Age: Inquisition
**EA App**

### System information
- GPU: RTX3080
- Driver: 531.29
- Wine version:  native Window 11 22H2
- DXVK version: 2.1 (same with 2.0 and 1.10.3)

### Log files
[DragonAgeInquisition_dxgi.log](https://github.com/doitsujin/dxvk/files/11021529/DragonAgeInquisition_dxgi.log)
The d3d11 log file is empty.

It happens with the game set to either FullScreen/Borderless/Window. Launching the exe directly drops me to a working EA App. Launching it from the EA App results in an error message which states that the EA App must be restarted before it can work again.
It used to work back in the days of the Origin client (I can't remember which DXVK version I used back then).

This is strange because Mass Effect 3 Legendary works with the AE App and DXVK-2.1, although HDR10 isn't working.

**Comment by K0bin** [comment]
If the d3d11.log file is empty, that means that the game has likely loaded d3d11.dll from C:\Windows\System32 instead. A lot of games do that and there's nothing we can do about it.

**Comment by janos666** [comment]
Can the EA App play any part in what the game exe loads?
The local exe file I have was signed in 2015 and I was able to run DAI with DXVK sometime in 2022. This comment also shows that DAI could run with DXVK on Windows 7 in 2018: [https://github.com/doitsujin/dxvk/issues/293#issuecomment-382469112](https://github.com/doitsujin/dxvk/issues/293#issuecomment-382469112)

**Comment by Nerellus** [comment]
The apitrace I made in #293 was not made with dxvk, I don't remember if I ever tried dxvk on Windows. 

That said, I'm currently not able to launch Dragon Age: Inquisition through EA App on Linux either. I don't know when it broke, but it doesn't look like a dxvk issue to me. It doesn't launch with wined3d either (and it should).

Does the game launch without dxvk on Windows for you @janos666? This just looks like EA App breaking stuff to me.

**Comment by mirh** [comment]
Can you try with an nvidia driver older than 526?
