### ISSUE TITLE
[question - DXVK Native] ETS2/ATS and mods supporting only DX11

### ISSUE THREAD

**Issue by rado84-github** [doitsujin/dxvk#3297]
I have a question about DXVK Native but since the native repository has been closed, I have to ask here.

The games ETS2 and ATS both have native linux versions but modders, whether due to laziness, ignorance or carelessness don't generate the mipmaps for the textures when creating their mods. Textures without mipmaps appear black when the mod is used in the native Linux version of the game.

So my question is: does the presence of DXVK native mean that I can put the .so files where the linux game executable file is and if I use a mod without mipmaps, it will appear normal - as it would on Windows?

**Comment by K0bin** [comment]
No. DXVK Native has to be implemented by the game developer. It's not a drop in solution.

Just use the Windows version with Proton to fix your problem.
