### ISSUE TITLE
[d3d9] [bisected] Warhammer 40,000: Space Marine - Anniversary Edition shadow artifacts as of f295095

### ISSUE THREAD

**Issue by TacoDeBoss** [doitsujin/dxvk#3298]
### System information
- GPU: Radeon RX 5700 XT / GeForce GTX 1070 / Steam Deck
- Driver: Mesa 22.3.6 / Nvidia 525.89.02 (Linux), Nvidia 531.29 (Windows) / lib32-vulkan-radeon 23.1.0_devel.166652.steamos_3.5.1-1
- Wine version: Proton Experimental
- DXVK version: 2.1

### Apitrace file(s)
[SpaceMarine.trace.tar.zst](https://drive.google.com/file/d/19bak_JPlhoJkGVW4WgG07Q0QFijbRWaT/view)

In Warhammer 40,000: Space Marine - Anniversary Edition, you will notice a shadow in the form of a line across the screen that will follow the player wherever they move.

This is a regression between 1.10.3 and 2.0, bisected to f295095. This commit also shows an issue where the sky ingame is black, but that issue was solved by 49854db.

<details>
  <summary>f295095 (first bad, see under the crosshair)</summary>
  
  ![Screenshot](https://cdn.discordapp.com/attachments/582000248310988816/1087658822719512646/warhammer-f295095.png)
</details>

<details>
  <summary>d221bb7a (last good)</summary>
  
  ![Screenshot](https://cdn.discordapp.com/attachments/582000248310988816/1087658822207811604/warhammer-d221bb7a.png)
</details>

<details>
  <summary>49854db (regular sky, but black line still present - this behavior still in 2.1 and master)</summary>

  ![Screenshot](https://cdn.discordapp.com/attachments/582000248310988816/1087658821700288562/warhammer-49854db.png)
</details>

**Comment by mrdeathjr28** [comment]
Curiously in my case works ok with dxvk 2.1 on my intel uhd 630

https://www.youtube.com/watch?v=aHe0mJOob5E

**Comment by K0bin** [comment]
No, it doesn't. The issue can be seen at https://youtu.be/aHe0mJOob5E?t=6033

**Comment by mrdeathjr28** [comment]
curiously i dont see it, only see shadow of player-wall and chainsaw sword but sky are ok

**Comment by K0bin** [comment]
I already know the issue and I'm investigating on how to fix it.
