### ISSUE TITLE
Hitman Absolution needs "Class linkage"

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#33]
I only see in d3d11.log errors like:
warn:  D3D11RasterizerState: Depth clamp not properly supported
err:   D3D11RasterizerState: Antialiased lines not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
err:   DxbcCompiler: Unhandled PS SV input: DxbcSystemValue::SampleIndex

**Comment by doitsujin** [comment]
Please stick to the issue template and at least describe what the game does. Class linkage not being implemented is only an issue if the game actually relies on it rather than just using dummy objects, and if that's all the errors you're getting I don't think the game actually needs it.

**Comment by exolyte** [comment]
The game crashes a few seconds after opening the launcher. It does launch with wined3d, though I wasn't able to get an apitrace through wine. Will try on windows later.
[HMA_d3d11.log](https://github.com/doitsujin/dxvk/files/1670583/HMA_d3d11.log)
[HMA_dxgi.log](https://github.com/doitsujin/dxvk/files/1670584/HMA_dxgi.log)

**Comment by doitsujin** [comment]
Thanks. Based on the logs, class linkage is a non-issue for this game (AFAIK even wined3d doesn't support it properly). The only real issue I see is that a bunch of shaders fail to compile:
`err:   DxbcCompiler: Unhandled PS SV input: DxbcSystemValue::SampleIndex`

Shouldn't be too hard to fix.

**Comment by doitsujin** [comment]
8a3dcf7c99f386e6ae5abe508c79a7847724ed84 implements `SampleIndex`, with some luck this might work now.

**Comment by exolyte** [comment]
Only tested the starting area, but it seems to work with some minor bugs.

Enabling MSAA makes the game look like this: https://pomf.pyonpyon.moe/dmhatt.png
Windows of a van look like this with bloom enabled: https://pomf.pyonpyon.moe/rudfve.png
And like this with bloom disabled: https://pomf.pyonpyon.moe/qpjfsb.png
Under some very specific angles they render correctly: https://pomf.pyonpyon.moe/mbbvtj.png

I tried making an apitrace on windows, but for some reason apitrace stops after recording 1 frame.
[HMA_d3d11.log](https://github.com/doitsujin/dxvk/files/1671271/HMA_d3d11.log)
[HMA_dxgi.log](https://github.com/doitsujin/dxvk/files/1671272/HMA_dxgi.log)

**Comment by doitsujin** [comment]
Fixed in 9fbddf57df9c88d9ec3bea3020bf413fd6a4c83c.
