### ISSUE TITLE
README instructions seem to be incorrect

### ISSUE THREAD

**Issue by GenericEric** [doitsujin/dxvk#3303]
```
WINEPREFIX=/path/to/wineprefix
cp x64/*.dll $WINEPREFIX/drive_c/windows/system32
cp x32/*.dll $WINEPREFIX/drive_c/windows/syswow64
winecfg
```

The x64 dlls should probably be going into the syswow64 folder and x32 dlls to the system32 folder.

**Comment by K0bin** [comment]
See #3228

**Comment by GenericEric** [comment]
Thanks I searched and somehow didn't find those...

**Comment by IroAlexis** [comment]
When you have wine/wine64 binaries and a wine prefix in win64, you can just use winepath for determine correctly who architecture directory like this:
```
# 32bits
WINEPREFIX=/path/to/prefix wine winepath -u 'c:\\windows\\system32'
```
```
# 64bits
WINEPREFIX=/path/to/prefix wine64 winepath -u 'c:\\windows\\system32'
```
