### ISSUE TITLE
[d3d9] Need for Speed Carbon crashing at startup in 32Bit Nvidia driver

### ISSUE THREAD

**Issue by Riesi** [doitsujin/dxvk#3306]
In response to #3301 for better tracking of the issue.

The game crashes right on startup on Nvidia with a SIGFPE due to divide by zero inside their spirv compiler. You can look at my gdb output to see the faulting instruction and that the base address of the libraries can be found in proc_map.

I took an apitrace with dxvk by setting `handle SIGFPE nostop ignore noprint` on the games process via gdb.
~~Replaying the apitrace doesn't reproduce the crash though.~~
See my comment below on how to reproduce with the apitrace. https://github.com/doitsujin/dxvk/issues/3306#issuecomment-1490042349

It all comes down to this:
```
   0xf0edd213:	subsd  %xmm2,%xmm0
=> 0xf0edd217:	divsd  %xmm0,%xmm1
   0xf0edd21b:	movsd  %xmm1,0x7c(%esp)
   
f0e00000-f295f000 r-xp 00000000 103:02 4783793                           /usr/lib32/libnvidia-glvkspirv.so.530.30.02
```

[gdb_output.txt](https://github.com/doitsujin/dxvk/files/11049648/gdb_output.txt)
[proc_map.txt](https://github.com/doitsujin/dxvk/files/11049649/proc_map.txt)
core dump:
https://drive.google.com/file/d/1OOlknB5avRgtJ2PI3I4_Ocku0mVV1o6B/view?usp=share_link

### Software information
Need for Speed - Carbon DVD version 1.2

### System information
- GPU: GTX970
- Driver: 530.30.02
- Wine version: wine-8.3.r0.g575f6f67 ( TkG Staging Esync Fsync )
- DXVK version: d11878e

### Apitrace file(s)
https://drive.google.com/file/d/1Mp4mpLqY7_P4aEakisewqGL8Tkw_UlG6/view?usp=share_link

**Comment by dungeon007** [comment]
Sounds like connected to WINE's msvcr* & friends see2 check bug:
https://github.com/iXit/wine-nine-standalone/issues/80#issuecomment-820648805
If you read a bug, you will see that this even depends how drivers are compiled, so on some might or might not happen. And then read a WINE bug too...
 Anyway, both potentionaly affected apps (on some hw or  drivers) ships their own msvcrt or msvct71. So, if that, here quick check should be to override msvcr71 to native.

**Comment by Riesi** [comment]
thanks for the comments
But the main thing is that the Nvidia's spirv compiler should not crash on a FPE that a game enables.
So a workaround to not pass setting the exception enable to the linux side is okey, but in reality it should probably still be fixed on a driver level.
iirc my install is at version 1.2 or so, since its a disc install and I never bothered to patch it more.

**Comment by dungeon007** [comment]
Sure, either drivers could workaround it or workarounds could go anywhere for this. 
 As i see, in proton they added hacks for 2 apps to disable sse2 in msvcr* (probably because this is staying like that for decade plus :D): 
https://github.com/ValveSoftware/wine/commits/f497ac98efbb3c924a7ab9630963b88e20385ca4/dlls/msvcrt

**Comment by mrdeathjr28** [comment]
In my case run ok with my intel uhd 630 with lastest mesa oibaf

![nfca](https://user-images.githubusercontent.com/6601480/227777277-4d54e8f5-60f2-40c7-bacb-5bfda1dd365a.png)

![nfcb](https://user-images.githubusercontent.com/6601480/227777282-a0d1066c-0424-43e5-a208-815a21c0d220.png)

**Comment by K0bin** [comment]
Well yeah, it can't crash in the Nvidia driver if you're using an Intel GPU to run the game...

**Comment by mrdeathjr28** [comment]
> Well yeah, it can't crash in the Nvidia driver if you're using an Intel GPU to run the game...

is only for add game runs ok on intel igpu (my case), confirm issue could be fault of nvidia driver

**Comment by Riesi** [comment]
So I managed to find a trigger sequence with the Apitrace :frog: 
Currently running the `530.41.03` driver, but its the same on older ones too.

# Setup
Some steps might not be needed, but it worked for me so I kept it that way. :sweat_smile: 
The paths in the files need to be changed to the ones you are using!

Get wine-reload and place it in your debugging directory:
https://gist.githubusercontent.com/rbernon/cdbdc1b0e892f91e7449fcf3dda80bb7/raw/d8cf549bf751d99ed0fe515e36f99ff5c01b7287/WineReload.py

Make a GDB config file (I called it `gdb.stuff`):
```
set confirm off
set pagination off
handle SIGUSR1 noprint nostop
handle SIGSYS noprint nostop
source /home/stefan/WineReload.py
```

Make a script to attach to d3dretrace when you launch it i.e. `retrace.sh`: 
```
#!/bin/bash
while :
do
gdb -x /home/stefan/gdb.stuff -p $(pgrep d3dretrace)
done
```

Compile this dxvk branch, which triggers a SIGTRAP on d3d9 device creation:
https://github.com/Riesi/dxvk/tree/SIGTRAP

# Trigger-Sequence

1) Start the attach script with `sudo ./retrace.sh`
2) Launch d3dretrace with the apitrace that I posted above. I normally do this by running qapitrace in wine and loading the trace before hand. Make sure to **use the 32Bit Apitrace exe**!
 

```
c                               # go to dxvk SIGTRAP
wine-reload                     # get the symbols
break pthread_create            # break at thread creations
c                               # adding a number doesnt work here
c 3                             # let retrace create its threads
thread apply 1 2 3 set $mxcsr=0x1926  # enable FPEs on retrace threads
c 24                                  # high number to skip all other breakpoints
#voila we crash in the Nvidia spirv compiler
```

**Comment by Riesi** [comment]
![image](https://user-images.githubusercontent.com/27691485/235293663-01955f47-a796-4cd5-9d75-49911af99bf3.png)

**Comment by Riesi** [comment]
Ok works on wine 8.0 but not on 8.6, so its a wine regression.
will bisect and play a bit to confirm it fully working on dxvk.
