### ISSUE TITLE
Vampire: The Masquerade - Bloodline (Unofficial Patch) glitches

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3312]
Running Vampire: The Masquerade - Bloodline with the Unofficial Patch mod (game wont launch without) visual glitches can be observed like parts of people being offset from their model. This does not happen with Wined3d

<details>
  <summary>Example screenshot</summary>
  
![Screenshot_20230326_175855](https://user-images.githubusercontent.com/47954800/227789520-6ef0405d-c039-4790-870f-78e10e5da496.png)
</details>

Unofficial Patch can be downloaded here https://www.moddb.com/mods/vtmb-unofficial-patch/downloads/unofficial-patch-1131
Happens both with the Basic install and the Extras option. Once installed launch the game with `-game Unofficial_Patch`

Savegame made with basic install of Unofficial Patch: 
[Vampire-000.zip](https://github.com/doitsujin/dxvk/files/11072234/Vampire-000.zip)
Goes into `steamapps/common/Vampire The Masquerade - Bloodlines/Unofficial_Patch/save/`

### Software information
Vampire: The Masquerade - Bloodline (Unofficial Patch)

### System information
- GPU: 7900xtx
- Driver: mesa-git
- Wine version: Proton bleeding edge
- DXVK version: master (not a regression from what i know)

### Apitrace file(s)
https://mega.nz/file/9gYmUQJA#Ecg9aurL1Ri5e3z3mFVFCi3nI4EQVGcfD25ZK_ru6R4

### Log files
[Vampire_d3d9.log](https://github.com/doitsujin/dxvk/files/11072249/Vampire_d3d9.log)

**Comment by mbriar** [comment]
Sounds to me like it might be an RDNA3 specific Mesa bug, works fine here on a 6700XT and has done so since basically forever.

**Comment by Blisto91** [comment]
Oh you are right. Doesn't happen with amd pro. Didn't even cross my mind it could be a driver bug. Thanks!
Will make a mesa issue after checking if it's a regression.

**Comment by Blisto91** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/8712
