### ISSUE TITLE
[Feature request] Print driver name in log

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3313]
Just like the recent hud driver rework https://github.com/doitsujin/dxvk/commit/255ab1a63c07ec47ac20eb4416e1287b195be349 enabled the hud to show the driver name, e.g. RADV, it would be nice if it was also printed in the dxvk log alongside the already present driver and api version.

Would be a nice little detail and might even help a few people who are using a different Vulkan driver than they think but don't know to spot it from the version number.

**Comment by mbriar** [comment]
Not against this, but you can already tell e.g. AMDVLK and RADV clearly apart by the device name, a RADV device will always have RADV in the string somewhere, while AMDVLK is just $GPU_MARKETING_NAME.

**Comment by Blisto91** [comment]
True ofc. For that part i was more thinking from the perspective of someone new to this or not too well versed like random Proton issue reporters

**Comment by mbriar** [comment]
Sure, but amdvlk's driverName is `AMD open-source driver`, not sure if that really clears up much confusion in not too well versed folks.

**Comment by Blisto91** [comment]
Oh. Great catchy name :grin: 
Never actually seen the canon code name

**Comment by doitsujin** [comment]
306919047bffb3d8f30159c219722741728904e2

Not sure why github didn't auto-close.
