### ISSUE TITLE
(DXVK 2.1.0) Skyrim Ann. Edition D3D11RasterizerState: Antialiased lines not supported

### ISSUE THREAD

**Issue by rado84-github** [doitsujin/dxvk#3318]
Please describe your issue as accurately as possible.
In random locations of the map Skyrim Special Edition from GOG (with the Anniversary Edition update from GOG) keeps crashing with this error:
"D3D11RasterizerState: Antialiased lines not supported" written in d3d11.log. Reading through that file, one can also find these error messages:

warn:  D3D11DeviceFeatures: External memory features not supported
warn:  DXVK: Updating state cache version to v17
warn:  DXVK: Skipped 11 invalid state cache entries
warn:  DXVK: Creating new state cache file

### Software information
setup_the_elder_scrolls_v_skyrim_anniversary_upgrade_1.6.659.0.8_(64bit)_(59094).exe
Ultra settings with TAA, Windowed Borderless

### System information
- GPU: GTX 1660 Ti
- Driver: 525.89.02
- Wine version: 8.4
- DXVK version: 2.1.0 (x64), 2.0.0 (x64). Tried with 1.10.3 as well but that version can't even run the game properly.

### Apitrace file(s)
[SkyrimSE.trace.zip](https://github.com/doitsujin/dxvk/files/11083869/SkyrimSE.trace.zip)
Note: when the apitrace files are in the game dir (d3d11.dll, dxgi.dll and dxgitrace.dll), the trace file is created upon clicking the game exe but the game itself refuses to even run. Its window flashes in like 250 ms and then disappears without a trace (no pun intended). So for the required log files below I had to put the normal dll files of v2.1.0 for the game to run.

### Log files
[skyrim-game-logs.zip](https://github.com/doitsujin/dxvk/files/11083910/skyrim-game-logs.zip)

**Comment by rado84-github** [comment]
Yep. I can make a video, if you want.

**Comment by jrugia** [comment]
@rado84-github can you please upload a savegame where the crash occurs instantly like in the video?

I have the GOG version installed and so far haven't ran into any issues.

**Comment by rado84-github** [comment]
I will but I'll have to start over to reach the first crashing point bc after this many crashes, it seems that the game won't recognise its own save files anymore.

**Comment by rado84-github** [comment]
Well, here it is: save 078. Altough now after reinstalling the game and starting over, it doesn't crash anymore anywhere, not even at the location of save 078. I had installed the game same way the first time and yet after the second installation it doesn't crash anymore and I can't find a logical explanation.
But you still can try with save 078 to see whether it will crash on your side. Just load 078 and walk forward until you uncover Ivarstead.

[Skyrim Special Edition GOG.zip](https://github.com/doitsujin/dxvk/files/11128323/Skyrim.Special.Edition.GOG.zip)

**Comment by jrugia** [comment]
@rado84-github  Gave it a shot with your save file.  Successfully discovered Ivarstead, walked around for a few minutes and talked to some npc's. Didn't encounter any issues.


Tested on

GPU: RX 6800
Driver: Mesa 23.0.1
Wine version: 8.4 Staging
DXVK version: 2.1.0

**Comment by rado84-github** [comment]
The weird thing is that neither did I, which I find very weird. Well, I guess we can close this and if the problem occurs again, I'll reopen it.
