### ISSUE TITLE
Demul (Dreamcast emulator) draws nothing but black

### ISSUE THREAD

**Issue by gamax92** [doitsujin/dxvk#332]
http://forum.emu-russia.net/viewtopic.php?p=26178#p26178
Trying out Demul with DXVK, when starting a game, nothing gets drawn to the screen except for solid black.  
I only have access to Windows atm, I'll test again later under wine if necessary.

EDIT: Retested under latest nvidia beta driver, no change. Screen is still solid black.

### Software information
Demul (Dreamcast emulator) v0.7 180428 with gpuDX11 plugin

### System information
- GPU: NVidia GTX 650 Ti
- Driver: 397.40 (Windows)
- Wine version: (Windows 7)
- DXVK version: dxvk nightly r1038 7cb7e4a944b4c68c47693d76934bb1d7b0ebc11a

### Apitrace file(s)
- Put a link here
[demul-trace.zip](https://github.com/doitsujin/dxvk/files/1958196/demul-trace.zip)

### Log files
- d3d11.log: 
[demul_d3d11.log](https://github.com/doitsujin/dxvk/files/1958197/demul_d3d11.log)

- dxgi.log: 
[demul_dxgi.log](https://github.com/doitsujin/dxvk/files/1958198/demul_dxgi.log)

**Comment by saboya** [comment]
It works with gpuDX11old plugin.

**Comment by doitsujin** [comment]
Looks like the emulator heavily relies on UAV rendering. 9aa73d1148190a3785a8a0868887fcdd550ad31f fixes part of the issue but it doesn't render correctly yet.

**Comment by Eignar17** [comment]
@doitsujin  is fix error work fine

**Comment by doitsujin** [comment]
Apparently works now for the most part, closing.
