### ISSUE TITLE
Not launching

### ISSUE THREAD

**Issue by mCaoz** [doitsujin/dxvk#3326]
Game is not launching and nothing appears when im trying to start game with dxvk.
I think im having this issue because of "info:  OpenVR: could not open registry key, status 2 line" . But i couldn't find any solutions.

### Software information
Hogwarts legacy

### System information
- GPU: Rx540 and Radeon R5
- Driver: 23.3.2
- Wine version: -
- DXVK version: 2

### Log files
[HogwartsLegacy_dxgi.log](https://github.com/doitsujin/dxvk/files/11130716/HogwartsLegacy_dxgi.log)

**Comment by mbriar** [comment]
Hogwarts is a d3d12 game and doesn't run on DXVK.  You can try to use [vkd3d-proton](https://github.com/HansKristian-Work/vkd3d-proton) together with DXVK, but it generally has horrible performance and compatibility on the AMD windows vulkan driver and is not worth using over native d3d12 (and also will not make games run on GPUs not meeting the game's minimum requirements).

> "info: OpenVR: could not open registry key, status 2 line"

this message is harmless.

**Comment by mCaoz** [comment]
even god of war has the same issue i can't run some of the games with dxvk

**Comment by mbriar** [comment]
```
warn:  Skipping Vulkan 1.2 adapter: Radeon 500 Series
warn:  Skipping Vulkan 1.2 adapter: AMD Radeon R5 Graphics
info:  Radeon 500 Series:
info:    Driver: 2.0.258
```
Driver is too old for DXVK 2.0 and newer, which requires vulkan 1.3. You can try to update the driver or use DXVK 1.10.3 if there is no driver update available (although at least for the  RX540 I think there should be). Of course this will still not work for Hogwarts, but might for GoW.

**Comment by mCaoz** [comment]
i tried 1.10.3 and now im getting this error "warn:  CreateDXGIFactory2: Ignoring flags"

**Comment by mbriar** [comment]
Post full log, that message is again most likely not the problem.

**Comment by mCaoz** [comment]
[HogwartsLegacy_dxgi.log](https://github.com/doitsujin/dxvk/files/11130748/HogwartsLegacy_dxgi.log)

**Comment by Blisto91** [comment]
I see you are either using amdvlk or amd pro drivers. It is likely you will have a easier time using radv instead since they are recommended for both dxvk and vkd3d-proton on AMD

**Comment by mbriar** [comment]
That's from Hogwarts again.. Hogwarts can not run on DXVK, there is no point to try

> I see you are either using amdvlk or amd pro drivers. It is likely you will have a easier time using radv instead since they are recommended for both dxvk and vkd3d-proton on AMD

It's windows.

**Comment by Blisto91** [comment]
Oh right didn't notice Windows. Bed time soon.

Yes dxvk can do nothing for Hogwarts Legacy on it's own since it's d3d12. You'll need to use dxvk's dxgi together with vkd3d-proton's dlls. Also update your driver to the newest.
Tho note that even then vkd3d-proton and AMD's own drivers can be hit or miss. And with Windows in the mix even more so.

**Comment by mbriar** [comment]
Using vkd3d-proton on windows AMD is pretty much always pointless because the performance is abysmal if it works at all, so might as well not bother.

**Comment by Blisto91** [comment]
Hehe yes pretty much. The Vulkan "mod" on nexusmods ,which is just vkd3d-proton and dxvk dxgi bundled, seems popular ish for some reason xd. But it doesn't work well for AMD users (which is to be expected for on Windows)

**Comment by K0bin** [comment]
- Hogwarts Legacy is a D3D12 game. DXVK does not implement D3D12.
- Your driver is only supports Vulkan 1.3. Both DXVK and vkd3d-Proton require Vulkan 1.3.
- We don't really support Windows and it's probably gonna be slower than your regular graphics driver anyway.
