### ISSUE TITLE
GPL Performance No where as good as dxvk-async on GTA V

### ISSUE THREAD

**Issue by CosmicFusion** [doitsujin/dxvk#3333]
Please describe your issue as accurately as possible.

When playing GTA V with an empty state cache (i lost mine) i get the following performance:

Just running normally : 40->70fps and a good amount of stutter

RADV_PERFTEST=gpl : 40->70fps and a good amount of stutter

DXVK_ASYNC=1 (when that existed) : 70->90fps and almost no stutter

### Software information

GTA V

Dials: Everything on HIGH
Shadows: Softest
Post-effects: normal
Antialiasing: 8x

### System information
- GPU: Gigabyte RX 580 8GB
- Driver: 
Mesa: `23.1~git2304040600.e84cf8~oibaf~k`
Kernel: 6.2.6
- Wine version: GE-Proton-7-53
- DXVK version: DXVK 2.1

**Comment by Blisto91** [comment]
Do note that neither ASYNC (which this dxvk repo does not support) nor GPL touches anything to do with general performance outside of shader compilation.

**Comment by doitsujin** [comment]
daily reminder that games which stutter on Windows due to late shader compiles will stutter even more so with DXVK, GPL does not change that.

**Comment by CosmicFusion** [comment]
> Do note that neither ASYNC (which this dxvk repo does not support) nor GPL touches anything to do with general performance outside of shader compilation.
> 

Yes i know but GTA V general performance is tied with the state cache as all three methods start equalizing when the state cache builds up

But los santos takes a long time to do that and I'm an annoying brat who wants it no stutter now! :P

**Comment by K0bin** [comment]
> Yes i know but GTA V general performance is tied with the state cache as all three methods start equalizing when the state cache builds up

No, it's not.

**Comment by CosmicFusion** [comment]
Oh well it is for me :P
________________________________

**Comment by CosmicFusion** [comment]
Also should i try this?

https://github.com/doitsujin/dxvk/issues/3311

**Comment by emansom** [comment]
GTA V is a CPU bound/heavy game. What CPU does your system have?

Try frame capping it to 60 (or even lower, e.g. 45) using the the environment variable `DXVK_FRAME_RATE` (or via config).

**Comment by Blisto91** [comment]
> Also should i try this?
> 
> #3311

You can download latest master from the CI here https://github.com/doitsujin/dxvk/actions/runs/4609600345

**Comment by CosmicFusion** [comment]
> > Also should i try this?
> > 
> > #3311
> 
> You can download latest master from the CI here https://github.com/doitsujin/dxvk/actions/runs/4609600345
> The newly released GE-Proton-7-54 already has it included along with Proton Experimental on steam

Thank you

**Comment by CosmicFusion** [comment]
> GTA V is a CPU bound/heavy game. What CPU does your system have?
> 
> Try frame capping it to 60 (or even lower, e.g. 45) using the environment variable `DXVK_FRAME_RATE` (or via config).
> 
> If that resolves the stutters completely, you need a better CPU to be able to push higher frame rates. (_and Rockstar Games needs to find better programmers_).
> 
> Also disable MSAA and other AA, only enable FXAA.
> 
> The AA implementation in the game is notoriously heavy on the GPU, where as FXAA is highly optimized.
> 
> Shadows to Soft.

Oh someone explained why my general performance sucked until the shader cache was richer

The Game is heavly CPU bound as you said

And my puny i5-4750s was busy compiling shaders and when it's not performance is good

**Comment by Blisto91** [comment]
Hope the above change makes it work better for you 🙂

**Comment by emansom** [comment]
> Oh someone explained why my general performance sucked until the shader cache was richer
> 
> The Game is heavly CPU bound as you said
> 
> And my puny i5-4750s was busy compiling shaders and when it's not performance is good

Running the game here on a low-end quad core (no SMT) Skylake Xeon and RX 580.

With GPL enabled (via `RADV_PERFTEST=gpl`) and frame cap to 45, there's no stuttering and frametime graph is flat. Even without prewarmed cache.

Make sure to remove mesa shader cache and dxvk state cache files when running different versions of Mesa and DXVK.

Upgrading to a more powerful processor, like the Zen 3 based Ryzen 5 5600 is another option to reach 60+ FPS without heavy frametime variance.

**Comment by CosmicFusion** [comment]
> Hope the above change makes it work better for you in general 🙂 

Ok that dxvk async you gave me completely removed stutter

And that config upped general performance


So all good now

**Comment by Blisto91** [comment]
Cool. Enjoy the game!
