### ISSUE TITLE
Dark Romance: Vampire in Love black screen

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3336]
Dark Romance: Vampire in Love has a black screen, except for the cursor with a white square around it, when using dxvk. Wined3d is fine and so is native, but also reproduces with dxvk on Windows.

`d3d9.allowDirectBufferMapping = False` gets rid of the issue which is weird.

### Software information
Dark Romance: Vampire in Love Collector's Edition

### System information
- GPU: AMD 7900xtx
- Driver: mesa-git / Windows 23.4.1
- Wine version: Experimental
- DXVK version: Any

#### SEIZURE WARNING! 
https://mega.nz/file/54gWGJCQ#GYWrfVak_SL-HC3jljgGK8o1jfH2FgWjiJACEfwOfko
#### SEIZURE WARNING! 
If there are stripes appearing in the main menu when replaying with `d3d9.allowDirectBufferMapping = False` then those can be ignored as they aren't a thing in the actual game.

### Log files
[DarkRomance_VampireInLove_CE_d3d9.log](https://github.com/doitsujin/dxvk/files/11165014/DarkRomance_VampireInLove_CE_d3d9.log)

**Comment by K0bin** [comment]
The game updates buffers with NOOVERWRITE and then overwrites data that's in use.

**Comment by axeldavy** [comment]
The game requests Software Vertex Processing. Thus it assumes all vs computation is done right away. NOOVERWRITE or not doesn't matter when you use software vertex processing.
