### ISSUE TITLE
Warhammer End Times - Vermintide: Black screen on start

### ISSUE THREAD

**Issue by Zlopez** [doitsujin/dxvk#334]
After starting the game I ended with black screen. I hear the sound but nothing else. Even the DXVK_HUD disappeared after few seconds.

### Software information
System: Fedora 27 x86_64
Game: Warhammer End Times - Vermintide - Steam version

### System information
- GPU: GeForce GTX 960
- Driver: 390.48-1.fc27.x86_64
- Wine version: wine-staging 3.6
- DXVK version: 0.42

### Log files
- d3d11.log: [vermintide_d3d11.log](https://github.com/doitsujin/dxvk/files/1958771/vermintide_d3d11.log)
- dxgi.log: [vermintide_dxgi.log](https://github.com/doitsujin/dxvk/files/1958772/vermintide_dxgi.log)

**Comment by doitsujin** [comment]
Please test with latest `master`, the binary releases do not reflect the current state of development.

Anyway, this error indicates that dxvk is doing something illegal on the Vulkan side of things:
`err:   DxvkDevice: Command buffer submission failed: VK_ERROR_DEVICE_LOST`

Please `export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation` and write both the standard output and error streams to a file. You might have to run the steam client with all that stuff enabled if the game launches itself through steam.

Or try to record an apitrace as requested in the issue template........

**Comment by Zlopez** [comment]
I tried it with the [1bcae90d](https://github.com/doitsujin/dxvk/commit/1bcae90dd0267a5a38e4a6aeb9a702e820f9012a) and the game is now starting, but it crashed when switched to borderless fullscreen.

I'm adding the game log when running with borderless fullscreen and `export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation`

## Log files
* d3d11.log: [vermintide_d3d11.log](https://github.com/doitsujin/dxvk/files/1959028/vermintide_d3d11.log)
* dxgi.log: [vermintide_dxgi.log](https://github.com/doitsujin/dxvk/files/1959031/vermintide_dxgi.log)
* game.log: [vermintide.log](https://drive.google.com/file/d/1-diqB1HYd9xaPkLlTauteAEaSLZggv8e/view?usp=sharing)

**Comment by Zlopez** [comment]
I noticed the same issue with black screen on start when the game isn't started in windowed mode and resolution 1280x720 (this is probably some default configuration).
I tried to start it in fullscreen, borderless fullscreen and in resolution 1920x1080. Encountered the same issue as above.
I updated the wine-staging to version 3.7 and used DXVK commit: https://github.com/doitsujin/dxvk/commit/ba53cf92acbdf60458e69ec7fcbabc1e597ae73d

##Log files
* d3d11.log:  [vermintide_d3d11.log](https://github.com/doitsujin/dxvk/files/1961669/vermintide_d3d11.log)
* dxgi.log: [vermintide_dxgi.log](https://github.com/doitsujin/dxvk/files/1961675/vermintide_dxgi.log)

**Comment by Zlopez** [comment]
I want to record an apitrace. Is there a way to temporary disable DXVK in wineprefix?
Or should I ran the apitrace with DXVK?

**Comment by doitsujin** [comment]
In order to use wined3d instead of dxvk, launch the game (or better, Steam) with: 
`export WINEDLLOVERRIDES=d3d11,dxgi=b`

If that doesn't work (wined3d has its own issues), you can try recording one with DXVK.

**Comment by Zlopez** [comment]
After few retries I was able to get into game with DXVK enabled, no luck without it.
The game crashed when I tried to change the display mode to fullscreen.
I hope this will help to find the issue.

* vermintide-apitrace-dxvk.log : [vermintide-apitrace.log](https://github.com/doitsujin/dxvk/files/1971979/vermintide-apitrace.log)

**Comment by doitsujin** [comment]
Those logs are sadly completely useless. I won't be able to debug the issue if apitrace doesn't work.

**Comment by MEXAHOTABOP** [comment]
seems like fixed 
played a round without any problems

**Comment by Zlopez** [comment]
@MEXAHOTABOP 
Did you tried to change the resolution?
This issue happens after change of resolution and switching to/from fullscreen.

**Comment by MEXAHOTABOP** [comment]
oh i read only first post 
i alerdy remove the game so test it later

**Comment by doitsujin** [comment]
Ping?

**Comment by Zlopez** [comment]
https://github.com/ValveSoftware/Proton/issues/1085

**Comment by doitsujin** [comment]
Closing then.
