### ISSUE TITLE
Grand Theft Auto IV crashing at startup with dxvk installed

### ISSUE THREAD

**Issue by CarCrasher730** [doitsujin/dxvk#3343]
### Software information
Game: Grand Theft Auto IV
I decided to upgrade my pc and do a clean install of Windows 10 and GTA 4. So I added a few new mods that I hadn't used before but the game crashes at start if you have dxvk installed otherwise it loads in like normal. Im also using fastman92 limit adjuster so if it crashes i get a error from that but removing the limit adjuster you get a black screen then it exits to desktop. Also I have a another GTA 4 that has GTAIVSA mod applied and the dxvk there works just fine altough its not using all the same mods.
### System information
- GPU: NVIDIA GeForce GTX 1050 Ti
- Driver: Game Ready Driver version 531.41
- OS: Windows 10 Enterprise LTSC Version 21H2 (OS Build 19044.2788)
- DXVK version: 2.1
- Game version: 1070
### Apitrace file(s)
If I do a apitrace the game starts like normal for some reason.

### Log files
https://www.mediafire.com/file/4jxvqrpeo3b4fkc/logs.zip/file

**Comment by Blisto91** [comment]
Hello.
Please list all the mods you are using in the crashing install. The dxvk logs doesn't contain anything interesting.

**Comment by K0bin** [comment]
The game is known to work fine on Linux.

So this is either some Windows issue that we can't do anything about or some incompatibility with whatever fastman92 is.

**Comment by CarCrasher730** [comment]
The mods I'm using are: Tweak All Peds mod, ultimate textures v.2.0, 4K2K Allagga Graphics Mod 1.0, IV-LANE (Base and EFLC versions), Various Fixes, More Visible Interiors, Lord Neophytes HQ texture pack, HD Textures for Middle Park, Liberty Island, Airport and Outlook Park, GTA IV HD Protagonists, Vegetation Textures by BisonSales Variety Pack, 2k Trees and Vegetation Textures, Halt Traffic Behind, Potential Grim, Responsive Plus, Recoil Fix, Improved Animations Pack, Realism Traffic/Pedestrian Mini-Mod, Vehicle Interior Overhaul, IV improved weapon spec, IV vehicle pack 1.7, IV vehshare 1.2, Vanilla Car Steering Wheel Pack 1, GTA TBoGT Cars Working Steering Wheel pack, Enterable Cablecar, Car Shop 15, GTA V Speedo (+HQ & LQ Interior & Steering Wheel), Comet and Roman's Taxi HQ Interior, rancher collison fix and sultan trunk fix, IV Fixes & Improvements, IV Burnout FX, scripthookdotnet, First Person V1.3, Realistic Driving EFLC, Dashboard Camera, Colored Radio Complete, Exaggerated blood, gta 4 plane improvements, Robbery Mod, Various Pedestrian Actions, Replaced Esperanto by Roman's Taxi in cab depot, Mirror Fix, Drunk Peds, Project Birds, IVTweaker, Divingmod, fastman92 limit adjuster, Windows Mobile Theme, Windows XP Themes for GTA IV, IV Presence and IV Presence Dependencies, IV Project 2DFXv4.3, Dialogue System, IV TLAD and TBOGT Vehicle Pack 1.2, [III/VC/SA] Largeaddress – Recognize 3/4 GB of RAM, GTA IV Downgrader 1.9 downgraded to 1070 with all mods selected which are ColAccel, FusionFix, ScriptHook for 1070, Simple Traffic Loader, Steam Achievements, xlive, ZMenuIV, and ZolikaPatch. I also have JackIVFixes which might be outdated and I have done performance improvements like giving the GTA 4 executables largeaddress aware, changed some settings in nvidia control panel and changed stream.ini to use 4gb of ram.

**Comment by CarCrasher730** [comment]
> The game is known to work fine on Linux.
> 
> So this is either some Windows issue that we can't do anything about or some incompatibility with whatever fastman92 is.
> 
> See https://github.com/doitsujin/dxvk/wiki/Windows

The game would still crash even if i removed the limit adjuster

**Comment by K0bin** [comment]
![20230408182633_1](https://user-images.githubusercontent.com/1131720/230732198-5e5e18d6-8e69-4fc6-91eb-4de0fcf5d89c.jpg)

The game works fine here. It's either an issue with your Windows setup or or of your million mods. In either case there's pretty much no chance we'll ever figure out what's going on.

**Comment by CarCrasher730** [comment]
Looks like it might be the mods as removing some of them causes the game to not start

**Comment by CarCrasher730** [comment]
It was caused by fastman's limit adjuster, to get both dxvk and the limit adjuster to work you had to open the ini in fastman's limi adjuster and disable the crash exception handler
