### ISSUE TITLE
Regression - Unravel Two (1225570) hangs with black screen on deck instead of playing logo and getting to main menu

### ISSUE THREAD

**Issue by alasky17** [doitsujin/dxvk#3351]
### Software information
Game: Unravel Two (1225570)
Failure: Dev logos before main menu are just black (but audio can be heard) and game stays black instead of playing logos and immediately moving to main menu.  Often will crash the deck (audio can have very high pitched horrible whine when this happens).
Failure happens with Steam Deck (SteamOS Stable, 3.4.6)
Failure did *not* happen with my AMD Desktop.

### System information
- GPU: AMD Vangogh 0405 (Steam Deck)
- Driver: radv Mesa 23.1.0-devel (git-16283f7b97)
- Wine version: 8.0
- DXVK version: HEAD at 01dc9ddc7de154d8066856e3257c544dbaf93689 
       Bisected and found first bad commit:
commit af0009c5debe33cffd5e412d0ff3d8adcd064c55
Author: Robin Kertels <robin.kertels@gmail.com>
Date:   Sat Apr 8 03:15:39 2023 +0200

    [d3d9] Use DxvkFormatInfo for video formats
    
    And fix UYUY and YUY2 in the process.

-----------------------
System that did *not* experience failure:
- GPU: AMD RX 570
- Driver: radv Mesa 23.0.0

**Comment by K0bin** [comment]
Curious that this uses D3D9 to display videos and D3D11 for the actual game.

**Comment by K0bin** [comment]
I replaced the DXVK dlls in Proton 7.0 and the intro works fine.
![image](https://user-images.githubusercontent.com/1131720/232234692-77e997a0-9a76-496b-8c9b-ce355e40c0ae.png)

I've also logged all D3D9 calls that interact with textures and it never does anything with the video formats that commit changed.

Are you sure about that bisect?

**Comment by Blisto91** [comment]
I can reproduce the same issue on my rdna3 GPU. I cannot reproduce it with my old R9 380x.
With the rdna3 GPU when testing with amd pro drivers instead of radv looks to have the same issue. Here the game just crashes instead of the GPU hanging.

**Comment by K0bin** [comment]
https://drive.google.com/file/d/1eDTchlO7Ga-zj5pxWvGTVfxQqGR96Au_/view?usp=sharing

Apitrace of the intro.
