### ISSUE TITLE
Adding a wine setup script

### ISSUE THREAD

**Issue by es20490446e** [doitsujin/dxvk#3359]
Maybe we could add:
https://aur.archlinux.org/cgit/aur.git/tree/setup_dxvk.sh?h=dxvk-bin

To this repo.

If you agree, I can make a pull request.

**Comment by mbriar** [comment]
This script originally came from here and got removed because once in a blue moon someone had unreasonable complaints about it.

**Comment by es20490446e** [comment]
What were those complains about?

Why did you choose to agree with that person?

The problem of not having such script that I'm finding is that each distro is using their own command for installing dxvk, so there's no consensus how it shall be named or how it shall behave.

So in [exeCute](https://gitlab.com/es20490446e/exeCute) I don't know which command to call.

**Comment by es20490446e** [comment]
You mean this: https://github.com/doitsujin/dxvk/pull/3097

**Comment by es20490446e** [comment]
@doitsujin Sorry, I feel this was a bad move.

This script is useful because it allows installing dxvk just with Wine, and more importantly in a standard way across distros.

Without it some distros now ship it anyways, others use their own script, and others skip it. So now you have no standard.

**Comment by es20490446e** [comment]
Closed as **duplicate** of https://github.com/doitsujin/dxvk/issues/3211.
