### ISSUE TITLE
"failed to fast clear 17" messages in console with Kingdom Come

### ISSUE THREAD

**Issue by craftyguy** [doitsujin/dxvk#336]
### Software information
Kingdom Come: Deliverance, v 1.43. Settings @ low, res @ 2560x1440

### System information
- GPU: AMD RX 580
- Driver: Mesa 18 git master branch
- Wine version: 3.7
- DXVK version: Git master

When run from the console, this message is printed multiple times per second: `failed to fast clear 17`

**Comment by doitsujin** [comment]
Not a bug, that's a message from RADV.

**Comment by doitsujin** [comment]
Well yeah, but that's out of my control.
