### ISSUE TITLE
[question] graphic pipeline on anv is usable on dxvk ?

### ISSUE THREAD

**Issue by mrdeathjr28** [doitsujin/dxvk#3360]
Hi

Today has landed in mesa git lab this commits

anv: implement VK_EXT_graphics_pipeline_library​

https://gitlab.freedesktop.org/mesa/mesa/-/commit/3d49cdb71ee8cb07ca922b9ffa15edd27627959c

also add feature for be possible use in dxvk

[quote]props->graphicsPipelineLibraryIndependentInterpolationDecoration = true;
[/quote]

anv: introduce a base graphics pipeline object

https://gitlab.freedesktop.org/mesa/mesa/-/commit/b2d3d818d57b9288fcdd98965c81d981540b1aba

anv: Only enable GPL if ANV_GPL=true, or if zink or DXVK are the engine.​

https://gitlab.freedesktop.org/mesa/mesa/-/commit/647ca8165407fcdb2695917599a803f8b0c804bb​
 
graphic pipeline is usable with before commits, oibaf drivers must stay around tomorrow

**Comment by Blisto91** [comment]
You can see in a games dxvk log if it works and is enabled.
Or if you have either the `full` or  `pipelines` turned on with the dxvk hud look if the `Graphics Shaders` line shows.

**Comment by mrdeathjr28** [comment]
now graphic pipeline appears on anv with dxvk

![dxvk](https://user-images.githubusercontent.com/6601480/232696684-6e8bd197-8852-4b50-a854-06b8c12c5e02.png)

**Comment by Blisto91** [comment]
Sounds good 👍
Sad it missed the 23.1 branch point but glad to see it merged.
