### ISSUE TITLE
dxvk-installer: a replacement for: setup_dxvk.sh

### ISSUE THREAD

**Issue by es20490446e** [doitsujin/dxvk#3364]
Because of bug https://github.com/doitsujin/dxvk/issues/3211, I have made [dxvk-installer](https://gitlab.com/es20490446e/dxvk-installer).

**Comment by Blisto91** [comment]
Please don't open and close a issue just to make an announcement

**Comment by es20490446e** [comment]
Just in case someone searches for it, as the other thread title doesn't have the appropriate keywords.
