### ISSUE TITLE
D3D11: Failed to write shared resource info for a texture

### ISSUE THREAD

**Issue by Silent-Remux** [doitsujin/dxvk#3367]
### Software information
Name of the game, settings used etc

Somerville - Xbox Game Pass 
https://store.steampowered.com/app/1671410/Somerville/

### System information
- GPU: 4090
- Driver: 531.61
[Somerville_d3d11.log](https://github.com/doitsujin/dxvk/files/11273688/Somerville_d3d11.log)

- DXVK version: 2.1, Wndows 11

No state cache file created as a result.

**Comment by Blisto91** [comment]
Shared resources aren't supported on Windows. Needs wine patches to work.

**Comment by Silent-Remux** [comment]
> Shared resources aren't supported on Windows. Needs Wine patches to work.

Sure but shouldn't it have made a state cache? I have no such cache next to the exe or inside my preconfigured C:\DXVK_CACHE folder

**Comment by Blisto91** [comment]
Cache files aren't created anymore unless needed. With gpl capable drivers (Nvidia only on Windows) most of the cache will reside in the drivers own cache now (afaiu)
