### ISSUE TITLE
DXVK_FRAME_RATE reacts "slowly" to sudden framerate changes (throttles increase from low fps to high fps)

### ISSUE THREAD

**Issue by user3287** [doitsujin/dxvk#3369]
When the framerate changes very suddenly, DXVK_FRAME_RATE kind of throttles performance, I noticed this in Apex while using a script that limits the framerate to 30Hz for about 30 milliseconds.

So basically, when the 30 milliseconds are over, the game takes like 3 seconds to climb back up to 144Hz, where if I do not use DXVK_FRAME_RATE, it goes up to 144Hz instandly.

Game: Apex
Driver: Mesa23.1/AMD/Wayland
Wine: GE-Proton7-55
DXVK: ? Latest?

I suggest to add a little note in the read.me and the docs next to DXVK_FRAME_RATE and then to close this issue, as it isn't exactly an issue that needs fixing, but it took me a while to figure out, and if it would've been written there, it would surely have saved me a little bit of time/ frustration/ ranked points ;)

**Comment by doitsujin** [comment]
This isn't intended behaviour and I also cannot confirm this. If anything, the frame rate will briefly overshoot the target value since the limiter runs at vkQueuePresent time on a worker thread, rather than the application thread.

**Comment by doitsujin** [comment]
I don't have Apex installed, no. I just modified our basic triangle test app (somewhere in https://github.com/doitsujin/dxvk-tests) to swap between 30 and unlimited fps every couple of seconds and ran it with `DXVK_FRAME_RATE=100 DXVK_HUD=full`.

**Comment by Blisto91** [comment]
If you encounter it again and it seems to indicate dxvk weirdness you are ofc welcome to open the issue again
