### ISSUE TITLE
Deep Rock Galactic 

### ISSUE THREAD

**Issue by jarrard** [doitsujin/dxvk#337]
**REFER TO LAST POST FOR CURRENT STATUS**

Just wanting to open this issue up to see if fellow DXVK afiliarnos can chime in on getting this title working under DXVK. Its based off Unreal4 like ARK is and has no COOKED content (for opengl mode, use d3d11).

_You get a message that shows up saying global shader cache file missing GlobalShaderCache-GLSL_150.bin and the application is built to load COOKED content but that is not provided. I tried using -game argument and the error message goes away, however title sits at 16% CPU usage indefinitely so perhaps it can't run uncooked (-game) mode._ 
(this is because its running in opengl mode, use argument -d3d11)

EDIT: Game claims to be DX11 but I'm not so certain its running in that mode because DXVK logs are not made, could be running opengl. 

**(USE -d3d11 argument on game exe, game often defaults to opengl and will half the time not launch correctly and CPU cycle at 16% forever)**

### Software information
Deep Rock Galactic

### System information
- GPU: 1080Ti
- Driver: 396.18
- Wine version: 3.7staging (FO4/SSE patch)
- DXVK version: lastest master

### Apitrace file(s)
- coming soon
### Log files
- d3d11.log: [CrashReportClient_d3d11.log](https://github.com/doitsujin/dxvk/files/1969392/CrashReportClient_d3d11.log)
- dxgi.log: [CrashReportClient_dxgi_2.log](https://github.com/doitsujin/dxvk/files/1969515/CrashReportClient_dxgi_2.log)

**Comment by jarrard** [comment]
That seems quite odd, they advertise as DirectX11, what on earth could be going on here? Maybe its a matter of getting it to run correctly under DX11. It's Unreal Engine 4 so I don't see why that isn't the default.

Hopefully someone else who has it can chime in as perhaps my test setup is wrong somehow.

**Comment by jarrard** [comment]
I discovered something with this game, under windows if I go -opengl argument it pops up with the EXACT same error, so for some reason it looks like to be switching to opengl under wine by default instead of dx11. Not sure if there is a DX11  flag yet, testing required.

**Comment by jarrard** [comment]
Wine errors on launch that MAY be of some interest (could be nothing)

Some general WINE errors: 
[0503/112247:ERROR:network_change_notifier_win.cc(170)] WSALookupServiceBegin failed with: 8
006a:err:dc:CreateDCW no driver found for L"\\\\.\\DISPLAY2\\Monitor0"
003c:err:winediag:wined3d_dll_init Setting multithreaded command stream to 0.
003c:err:ole:CoGetClassObject class {294935ce-f637-4e7c-a41b-ab255460b862} not registered
003c:err:ole:CoGetClassObject class {294935ce-f637-4e7c-a41b-ab255460b862} not registered
003c:err:ole:create_server class {294935ce-f637-4e7c-a41b-ab255460b862} not registered
003c:err:ole:CoGetClassObject no class object {294935ce-f637-4e7c-a41b-ab255460b862} could be created for context 0x17
0075:err:winediag:wined3d_dll_init Setting multithreaded command stream to 0.
Assert( Assertion Failed: Attempting to use a Windows-Vista+ only path root on an older version of Windows for game 379430 ):c:\buildslave\steam_rel_client_win32\build\src\clientdll\userremotestorage.cpp:2270

DXVK related errors: Likely cause of crash.

0105:err:d3dcompiler:compile_shader HLSL shader parsing failed.
0105:err:d3dcompiler:compile_shader HLSL shader parsing failed.

**Comment by doitsujin** [comment]
Those errors are *not* DXVK-related. Make sure to use native `d3dcompiler` DLLs (not sure which version, if them game is older then you probably need _42 and _43).

**Comment by jarrard** [comment]
ok, I just assumed they were DXVK related because they appeared directly in the middle of the DXVK debug read out.

**Comment by jarrard** [comment]
Ok I have this game working 60+ fps now, turns out it doesn't like __GL_YIELD (NVIDIA) so be sure to not set that (I had NOTHING set). You do need dx 42/43 files and probably -d3d11 argument set. 

I run at 4k as usual and have settings on HIGH-EPIC with low FSAA and get 60-80fps area (its quite variable), when I set the MAX fps cap to anything I notice frame skipping so keep that in mind.

If anyone else has this game please feel free to comment, it be great to hear from AMD users about its performance.

**Comment by doitsujin** [comment]
Can you record an apitrace?

**Comment by jarrard** [comment]
I will certainly look into it. But the issue isn't normally present at the start of a mission, starts happening as you more further down, and when you return back to the drop pod to exit the mission, the issues start subsiding etc... In fact sometimes when you look in a certain direction the artifacts go away.

I just updated to 396.24 Nvidia drivers and will do some more testing, might also try the new compiler and see what happens. If the problems still persist I will look into exactly howto do a apitrace.,

**Comment by doitsujin** [comment]
You might want to keep an eye on #267 in that case, there's some discussion going on about the new shader compiler. I'll close this since there seem to be no bugs here, although I would like you to submit a trace for be to be able to test the game on different GPUs and drivers.

**Comment by jarrard** [comment]
Just got a question about apitrace doitsujin, you say not to run it with DXVK, are you asking to have a apitrace ran with default wined3d11 wrapper?   
and for games that have a issue at particular points (like 30mins into a mission), does it require me to play to thought said mission with wined3d11 to get the apitrace or am I misunderstanding what apitrace does?

**Comment by jarrard** [comment]
I recorded a trace file of 1 mission where the graphics glitching occurs, and well its 14gb...

**Comment by jarrard** [comment]
This no longer appears to work properly. Get 1-4fps now. Shame

**Comment by Xjs** [comment]
Hi. Not sure if I'm in entirely the right place, but maybe somebody can help. Disclaimer: I'm pretty new to running games using DXVK, I only just discovered that it comes bundled with CrossOver 20. 

I have a M1 MacBook Air and CrossOver 20.0.4 (which appears to bundle dxvk-v1.5.1-8-g7443ead4_x86_64.tar.bz2). After setting FSD-Win64-Shipping.exe to use »native« versions of d3d11.dll and dxgi.dll I was able to launch the game and move around with more than ~1 FPS, and use the settings menu properly. 

However, everything is really dark. There appears to be a lighting source missing (?). I turned the Gamma value all the way up to be able to see anything at all. See screenshots, I don't really know how to describe it.

Any pointers to how this could be resolved? The logs appear not to contain anything out of the ordinary, I've attached them here. Am I in the right place anyway? Should I go complain to CrossOver instead? Is this a M1 limitation?

I'm happy to help trace this if you're interested. Let me know what I can do :)

<img width="1680" alt="Screenshot 2021-06-25 at 23 05 09" src="https://user-images.githubusercontent.com/58270/123485140-d0bc8e80-d609-11eb-9685-5d6cf621dc55.png">
<img width="1680" alt="Screenshot 2021-06-25 at 23 05 05" src="https://user-images.githubusercontent.com/58270/123485159-d7e39c80-d609-11eb-852c-80bda72f3a0d.png">
<img width="1680" alt="Screenshot 2021-06-25 at 23 04 59" src="https://user-images.githubusercontent.com/58270/123485167-db772380-d609-11eb-8d66-552a99c8925a.png">
<img width="1680" alt="Screenshot 2021-06-25 at 23 04 49" src="https://user-images.githubusercontent.com/58270/123485174-dd40e700-d609-11eb-8500-e306e7e80553.png">
<img width="1680" alt="Screenshot 2021-06-25 at 23 04 46" src="https://user-images.githubusercontent.com/58270/123485185-e16d0480-d609-11eb-91e3-d5b4e5f1d39b.png">


[FSD-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/6718830/FSD-Win64-Shipping_d3d11.log)
[FSD-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/6718831/FSD-Win64-Shipping_dxgi.log)

**Comment by cdavis5e** [comment]
> I have a M1 MacBook Air and CrossOver 20.0.4 (which appears to bundle dxvk-v1.5.1-8-g7443ead4_x86_64.tar.bz2). After setting FSD-Win64-Shipping.exe to use »native« versions of d3d11.dll and dxgi.dll I was able to launch the game and move around with more than ~1 FPS, and use the settings menu properly.

Sorry, but this is the wrong place. That version of DXVK was modified. If you're having issues with CrossOver, I encourage you to file a bug and/or support ticket with [CodeWeavers](https://www.codeweavers.com). Also, I'm pretty sure neither Phillip nor Joshua provide support for Mac OS at all, let alone Apple Silicon.

**Comment by Xjs** [comment]
Thanks, I'll try my luck with CodeWeavers.

**Comment by Jhonsak** [comment]
> Ok, ahora tengo este juego funcionando a más de 60 fps. Resulta que no le gusta __GL_YIELD (NVIDIA), así que asegúrate de no configurarlo (no tenía NADA configurado). Necesitas archivos dx 42/43 y probablemente el argumento -d3d11 configurado.
> 
> Corro a 4k como siempre y tengo configuraciones en HIGH-EPIC con FSAA bajo y obtengo un área de 60-80 fps (es bastante variable), cuando configuro el límite de fps MÁXIMO en cualquier cosa, noto saltos de cuadros, así que tenlo en cuenta.
> 
> Si alguien más tiene este juego, no dude en comentarlo. Sería genial escuchar a los usuarios de AMD hablar sobre su rendimiento.
> 
> PD: Aún no he probado ninguna partida en línea ni la estabilidad a largo plazo.
> 
> ACTUALIZACIÓN: El juego funciona razonablemente bien, excepto que hay una falla gráfica que ocurre en algunos de los biomas.
> 
> Incluí una imagen de lo que sucede. Básicamente, parece que se está produciendo un estiramiento de polígonos. No estoy seguro de cómo obtener un registro de ningún tipo para este tipo de error, pero los problemas más comunes ocurren en misiones de tipo cristal y solo cuando desciendes un poco comienza a intensificarse.
> 
> ![captura de pantalla en 2zzzzz](https://user-images.githubusercontent.com/17428910/39566905-4f7e1ee8-4efc-11e8-83eb-ad058c35dfb3.jpg)
> 
> y otro ejemplo
> 
> ![captura de pantalla en 1zzzzz](https://user-images.githubusercontent.com/17428910/39567016-b950a638-4efc-11e8-84be-383b07bb9602.jpg)


Ok wait, how do I do all that? or rather what did you do to get to that point, I have tried to solve that problem, I really don't know much about programming and I would like to check if it can work for me too, by the way I am trying it in lethal company but nothing at all
