### ISSUE TITLE
dxvk to exagear

### ISSUE THREAD

**Issue by SolusMonahus** [doitsujin/dxvk#3372]
Please describe yo ur issue as accurately as possible.
Used in exagear via termux x11
https://4pda.to/forum/index.php?showtopic=992239&view=findpost&p=116886871

### Software information
Name of the game, settings used etc.

### System information
- GPU: adreno 618-660
- Driver: adreno turnip
- Wine version: 7.7-8.2
- DXVK 1.0-2.1

Dx10-11 does not work in exagir in dhvk from 1.0 to 2.1.
 Versions 0.92-0.96 work. Tested in Bioshock, Crisis (artifacts present), Heaven Benchmark 4.0, The Choice of Life Middle Ages 2.

**Comment by K0bin** [comment]
Android is not a supported platform in any way.

**Comment by SolusMonahus** [comment]
Not supported by the developer dxvk?

**Comment by K0bin** [comment]
Yes.

Especially if the only way to use it involves getting an emulator owned by Huawei from some random russian website.

**Comment by SolusMonahus** [comment]
I understood you. I'm sorry for the inconvenience.

**Comment by SolusMonahus** [comment]
I understood you. I'm sorry for the inconvenience.
