### ISSUE TITLE
3DMark Vantage crashes on startup, D3D11: Cannot create texture: Format:  6 Extent:  5x1x1

### ISSUE THREAD

**Issue by birdie-github** [doitsujin/dxvk#3374]
### Software information
```
md5sum 3DMark_Vantage_v113_installer.exe 
98350d90f56f163be21a448b92516337  3DMark_Vantage_v113_installer.exe
```
Downloaded from: https://benchmarks.ul.com/legacy-benchmarks

### System information
- GPU: GTX 1660 Ti
- Driver: 530.41.03
- Wine version: 8.6
- DXVK version: 2.1

### Apitrace file(s)
No idea how to use them because the benchmark crashes with them long before being able to render anything or even initialize D3D11.

### Log files
[logs.zip](https://github.com/doitsujin/dxvk/files/11294606/logs.zip)

### Installation instructions
1. Download and install the exe
2. Install DXVK 2.1
3. Launch `wine 3DMarkVantage.exe`, use `3DMVA-JP3EX-Z01J4-UUCBJ-1HDA7-7FXUX-KM6VQ-9Y9T1` to register
4. Launch `wine 3DMarkVantageCmd.exe --config_file="test_config/extreme.txt" --disable_system_info`

The benchmark crashes.
![crash](https://user-images.githubusercontent.com/4958603/233610183-bc7e26ed-188f-4b29-b11a-e3bb45a3a581.png)
[logs.zip](https://github.com/doitsujin/dxvk/files/11294732/logs.zip)

**Comment by doitsujin** [comment]
The format in question is `DXGI_FORMAT_R32G32B32_FLOAT`, if this is not supported with the required usage flags then there's basically nothing we can do.

**Comment by birdie-github** [comment]
> Also note that this should work as-is on RADV since RGB32 formats are somewhat supported there.

Are you implying it's a bug/missing feature in NVIDIA binary drivers?

**Comment by doitsujin** [comment]
It's not a bug, Nvidia just does not support the format, probably for good reason, and DXVK does not emulate it.

But again, since there is no relevant game or application which hard-requires this format for images, there's no real incentive for us to emulate it either.

**Comment by birdie-github** [comment]
Understood, thanks a lot for the info.

**Comment by mrdeathjr28** [comment]
> > Also note that this should work as-is on RADV since RGB32 formats are somewhat supported there.
> 
> Are you implying it's a bug/missing feature in NVIDIA binary drivers?

In my case with my uhd 630 (lastest mesa 23.2-git) works

![3dnva](https://user-images.githubusercontent.com/6601480/233667640-06c1767e-44cb-4745-a84b-6b7306182601.png)

![3dmvb](https://user-images.githubusercontent.com/6601480/233667677-fdcb5d7c-30cf-42a8-9611-f4fe43d57c3e.png)

![3dmvc](https://user-images.githubusercontent.com/6601480/233667708-6dc6b33b-9da5-4a7e-bdac-1ac531c63b8c.png)
