### ISSUE TITLE
Is another 1.10.x release planned?

### ISSUE THREAD

**Issue by frantisekz** [doitsujin/dxvk#3377]
There seem to be bunch of fixes accumulated in the 1.10.x branch. Are there plans to make another 1.10.x release (and releases moving forward), or would only the 2.x releases continue going forward?

This is relevant for ditro packaging which is the reason I am asking, thanks!

**Comment by doitsujin** [comment]
We do not have any immediate plans to make another 1.10 release, no.

**Comment by frantisekz** [comment]
Thanks for the reply!
