### ISSUE TITLE
`dxvk::thread` wrapper issues

### ISSUE THREAD

**Issue by anon-apple** [doitsujin/dxvk#3378]
In short, the `dxvk::thread` utility designed to re-implement `std::thread` has some odd and incorrect behavior as far as I can tell. The `ThreadFn` it holds internally is usually never destructed, which leads to it leaking memory and never properly calling `std::terminate` on incorrect thread usage (for example having the thread object destructed before detach or join is called).

This issue stems from the fact that the `ThreadFn` currently is refcounted and attempts to reference itself via manually incrementing the refcount in its constructor to prevent itself from being destructed while the thread is executing (since the `std::function` it holds needs to stay alive I guess). Since it only calls `decRef` after the thread is done executing however it never actually is freed as `decRef` only decrements the refcount, the freeing logic is in the `Rc` object which is usually destructed in the `dxvk::thread` before the thread finishes execution, thus not freeing it typically.

There's a few ways this could probably be fixed, one approach I tried that worked was just to have the `ThreadFn` reference itself with a `Rc` object and `std::move` that into the threadProc's ownership so it can be destructed when the thread ends, but that's just a bit complicated. Personally I'd just rewrite it entirely to remove the `ThreadFn` and just hold a `std::function` that is allocated on the heap and freed when the thread is done since there's no need for refcouting here I think. This would also fix the slightly incorrect behavior this model has right now where `std::terminate` is only called when the thread finishes (well with the fix at least), rather than where it is supposed to be called in `dxvk::thread`'s destructor (if it is to match `std::thread`'s behavior at least).

Unsure if either of those suggestions would be viable options for whatever the thread wrapper is trying to accomplish (otherwise I'd make a PR for it), but hopefully this helps.

**Comment by doitsujin** [comment]
The wrapper only exists for the purpose of making wine work, which requires us to use win32 APIs natively rather than winpthreads. As long as that is guaranteed, I don't really care what the implementation looks like, I didn't write this in the first place.

**Comment by pchome** [comment]
IIRC the thread wrapper was introduced for "winelib build", when dxvk was built as linux native library to replace wine "builtin" `*.dll.so` libs. Since winelib build support is long gone maybe its fine to use `std::thread` again (like it was before for mingw builds)?

**Comment by doitsujin** [comment]
FWIW another reason why we need the wrapper is so that we can control the thread size, since some games default to absurdly small stacks which aren't enough for shader compilation. The need for that isn't going away.

**Comment by doitsujin** [comment]
I reimplemented the wrapper in [this branch](https://github.com/doitsujin/dxvk/compare/thread-rework) which should address most issues.

**Comment by pchome** [comment]
How dxvk affected by CPU topology overrides in proton?

When an game need override on high-core system and limit is set to e.g. 4 cores, is it possible for dxvk to use threads on other free cores? I guess `::GetSystemInfo()` will report 4 cores and threads created via win32 API will unlikely go outside reported topology. Setting `dxvk.numCompilerThreads` option to higher count can make things even worth (?).

But should work fine if someone use topology override to limit number of cores used by a game, to have some cores free for other tasks.

**Comment by doitsujin** [comment]
> When an game need override on high-core system and limit is set to e.g. 4 cores, is it possible for dxvk to use threads on other free cores?

No, it's not. The override applies to **all** threads created on the win32 side, this isn't something we can really change.

**Comment by gabriele2000** [comment]
After this change I've noticed audio crackling in at least two games: The Cycle - Frontier and Ghost Recon - Wildlands.

**Comment by Blisto91** [comment]
@gabriele2000 Hello. Could you be more specific? Does it happen just generally when playing and does it not happen with the dxvk commit before?
What is your CPU.

**Comment by gabriele2000** [comment]
> @gabriele2000 Hello. Could you be more specific? Does it happen just generally when playing and does it not happen with the dxvk commit before? What is your CPU.

i7-7700HQ, Kernel 6.3, it happens when playing (of course) and that commit is the culprit because the previous one doesn't have the issue

**Comment by Blisto91** [comment]
Mkay.
I wasn't able to reproduce anything so far in the game. That was with a 7950x (also tried restricting threads to the game) and 6.2.12 Arch kernel

**Comment by doitsujin** [comment]
This change does not really affect how anything operates and does not introduce any extra CPU load. If this causes audio issues (obligatory reminder that DXVK does not interact with audio **at all**), there's a problem elsewhere on your system.

**Comment by gabriele2000** [comment]
Yeah see my edit. I guess there's something wrong in a totally random way
because it was fine the day before.
I guess it's the kernel that contains a bug or something.
