### ISSUE TITLE
Black screen with Reshade shader - Lightroom

### ISSUE THREAD

**Issue by jeeyi345** [doitsujin/dxvk#3379]
The issue is found on Windows 10 and involved reshade, I think it's not offically supported, so just report for acknowledgement.
It probably out of scope, but I'm grateful if it gets attention someday

### Please describe your issue as accurately as possible.
Reshade effect not work as expected, games didn't crash

I'm using DXVK with Reshade Vulkan mode, qUINT shader pack.
I'm glad to find out most of the reshade effect works, like MXAO, ADOF, SSR ...
But on Lightroom, which should be able to adjust color related stuff like RGB, gamma, level..., it just went all black when enabled.
The game isn't crash, and can use other mentioned reshade effect.

[reshade](https://reshade.me/)
[qUINT](https://github.com/martymcmodding/qUINT)
[qUINT_lightroom](https://github.com/martymcmodding/qUINT/blob/master/Shaders/qUINT_lightroom.fx)

### If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows
on Windows 10, with Borderless Fullscreen or windowed mode

### Software information
Name of the game, settings used etc.

Reshade with following:
Resident Evil 2
Outer Wilds
DreadOut

### System information
- GPU: NVIDIA GeForce GTX 1050 TI
- Driver: 531.41
- Wine version: On Windows 10
- DXVK version: 2.1

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

**Comment by doitsujin** [comment]
how do I test this?

**Comment by jeeyi345** [comment]
### Windows
On Windows, 
#### DXVK
I put dxvk's dx11.dll, dxgi.dll first.
#### Reshade
download reshade, locate game excutable, check game API (Vulkan), the effect want to use(qUnit/lightroom in this case), reshade will download the effect .fx files, put into the folder created same as the excutable.

If success, there'll be a reminder on top of the screen when game started.
The default key of reshade console is Home
[Windows installation guide](https://reshademanager.com/installation-guide)

### Linux
On Linux, there's a script to install, not tested personally
[Linux install script](https://linux-gaming.kwindu.eu/index.php?title=Reshade)

Sorry for the inconvenient.

**Comment by mbriar** [comment]
If reshade is hooking vulkan and not d3d11, then how can this be even DXVK's fault? Does this shader work with native vulkan games?

**Comment by jeeyi345** [comment]
>If reshade is hooking vulkan and not d3d11, then how can this be even DXVK's fault?
DXVK translate d3d to vulkan, if I understand correctly. You mean if reshade is hooking d3d11?

The game use d3d11, with DXVK dlls it's excute with Vulkan. Checked by enable DXVK_FRAME_RATE.
![image](https://user-images.githubusercontent.com/12745397/234391839-69563528-0efd-470e-bb79-9cdd3eb1bff2.png)

Without DXVK dll, reshade hooked in vulkan mode won't be active. It just like normal excution. For reference:
![image](https://user-images.githubusercontent.com/12745397/234394582-efa67fc3-582c-489a-bc78-8c1aabeb4661.png)


>Does this shader work with native vulkan games?
I'll install DOOM & Talos principle for verification. DOOM with reshade vulkan worked if I remembered correctly.

**Comment by doitsujin** [comment]
Seems to work fine here?
![Bildschirmfoto-99](https://user-images.githubusercontent.com/25567304/234556853-8d951833-158d-4ba4-927c-b4232e76b991.png)

Note that you will want ReShade to hook D3D11, not Vulkan. If there are issues with the Vulkan side of things then that's outside the scope of DXVK.

**Comment by jeeyi345** [comment]
I understand it works on your side, and it's outside of the scope. Thank you for your time. It's fine If you want to close this topic.
May I ask how do you use DXVK with reshade under linux?

For me, in Windows, I ran into the problem same dll name. 
these are some related post I found, just for record:

this is what works for me:
https://www.reddit.com/r/GodofWar/comments/tejr2g/how_to_use_dxvk_vulkan_reshade/

reshade provide a global varible RESHADE_MODULE_PATH_OVERRIDE , but don't really work:
https://reshade.me/forum/addons-discussion/8476-addons-and-dxvk

so ReShade to hook D3D11 isn't work for windows unfortunatly.

**Comment by jeeyi345** [comment]
I see, no further question.
