### ISSUE TITLE
Kingdom Come: Garbled Graphics

### ISSUE THREAD

**Issue by Mushoz** [doitsujin/dxvk#338]
I am using Wine Staging 3.6.1 on Fedora 28 to try and play Kingdom Come: Deliverance. However, the graphics are extremely garbled and colorful. I am using DXVK version 0.42. I have tried compiling from master, but I am unable to compile the dll, because I am not sure which wingw64 package I need. The 3 biggest issues that stand out from the logs are the following 3 errors:

err:   D3D11: Cannot map a device-local image
warn:  D3D11RasterizerState: Depth clamp not properly supported
warn:  Vulkan extension VK_KHR_maintenance2 not supported

### Software information
Kingdom Come: Deliverance.
Medium settings preset

### System information
- GPU: Vega 64
- Driver: 18.0.1
- Wine version: 3.6.1 staging
- DXVK version: 0.42

### Log files

d3d11.log:

info:  D3D11CreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  D3D11CreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  D3D11CreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  D3D11CreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  D3D11CreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
err:   D3D11: Cannot map a device-local image
warn:  D3D11RasterizerState: Depth clamp not properly supported
err:   D3D11: Cannot map a device-local image
err:   D3D11: Cannot map a device-local image
err:   D3D11: Cannot map a device-local image
err:   D3D11: Cannot map a device-local image
err:   D3D11: Cannot map a device-local image
err:   D3D11: Cannot map a device-local image

dxgi.log:

info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV VEGA (LLVM 6.0.0):
info:    Driver: 18.0.1
info:    Vulkan: 1.0.57
info:  AMD RADV VEGA (LLVM 6.0.0):
info:    Driver: 18.0.1
info:    Vulkan: 1.0.57
warn:  Vulkan extension VK_KHR_maintenance2 not supported
info:  Enabled device extensions:
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_maintenance1
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
warn:  Vulkan extension VK_KHR_maintenance2 not supported
info:  Enabled device extensions:
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_maintenance1
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV VEGA (LLVM 6.0.0):
info:    Driver: 18.0.1
info:    Vulkan: 1.0.57
info:  AMD RADV VEGA (LLVM 6.0.0):
info:    Driver: 18.0.1
info:    Vulkan: 1.0.57
warn:  Vulkan extension VK_KHR_maintenance2 not supported
info:  Enabled device extensions:
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_maintenance1
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
warn:  DxgiDevice::SetMaximumFrameLatency: Stub
warn:  DXGI: MakeWindowAssociation: Ignoring flags
err:   DXGI: CheckInterfaceSupport: No D3D10 support
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV VEGA (LLVM 6.0.0):
info:    Driver: 18.0.1
info:    Vulkan: 1.0.57
info:  AMD RADV VEGA (LLVM 6.0.0):
info:    Driver: 18.0.1
info:    Vulkan: 1.0.57
warn:  Vulkan extension VK_KHR_maintenance2 not supported
info:  Enabled device extensions:
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_maintenance1
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
warn:  Vulkan extension VK_KHR_maintenance2 not supported
info:  Enabled device extensions:
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_maintenance1
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DxgiVkPresenter: Recreating swap chain: 
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  2048x1152

**Comment by doitsujin** [comment]
Use mesa-git and latest llvm-svn.
