### ISSUE TITLE
Legacy 1.10.3 branch?

### ISSUE THREAD

**Issue by Fierelier** [doitsujin/dxvk#3381]
I'd personally like to see a 1.10.3 branch, in case people are interested to fix up DXVK for older GPUs. As someone who enjoys the build-quality of older laptops, I'm not really looking to upgrade past an Intel HD 4000. Technically, I would never need more.

It came somewhat as a shock that even DX9 is off the table for these chips (Crocus + Gallium Nine fills that niche some, but not always). I understand why you've went this path, but I would at least appreciate *something* for legacy computers. I think a new branch wouldn't disrupt things much.

**Comment by mbriar** [comment]
`MESA_VK_VERSION_OVERRIDE=1.3` can probably be used to run newer versions of DXVK on old intel gpu that are supported by hasvk as before 2.0. But I'd expect you'll hit tons of drivers bugs on these GPUs anyways that nobody will care to workaround.

**Comment by canteroman** [comment]
Que es ese link? Nisiquiera funciona

**Comment by Blisto91** [comment]
No the old 1.10.x branch got deleted in this repo. 
I still have a version of it at my fork https://github.com/Blisto91/dxvk/tree/1.10.x

**Comment by WinterSnowfall** [comment]
If people are still looking for a 1.10.x branch these days (for whatever reason), it's probably best to send them this way: https://github.com/pythonlover02/DXVK-Sarek

**Comment by Fierelier** [comment]
@WinterSnowfall
Thank you for the link, starred it! :>

Due to the apparent lack of interest of hardware preservation from the project lead, I will re-close as "not planned" lol 👎
