### ISSUE TITLE
RaceRoom Racing Experience (211500) Crashes when trying to do a race 

### ISSUE THREAD

**Issue by AJuujarvi** [doitsujin/dxvk#3386]
Was reported on the Proton github tracker here: https://github.com/ValveSoftware/Proton/issues/1321#issuecomment-1517844544

When you try to start a race, on the Deck it crashes completely. User reports that they get an indefinite black screen on their AMD desktop. I am not able to recreate this on an Nvidia desktop, and I do not have an AMD desktop local to me at the moment.

It works with Proton 8.0-1d, but fails with experimental-bleeding-edge-8.0-42015-20230428-pd8a0cb-w8e76cc-d5c8ed4-vc74ffa. Putting the DXVK from Proton 8.0-1d into the Proton Experimental BE build, that build now works.

DXVK in Proton 8.0-1d: caf31033d711460e86781b16a4d9b0f41fa9e817 dxvk (v2.1-4-gcaf31033)
DXVK in Proton Experimental BE:  5c8ed491ab6cb4c74b16d2551353429ac2c80a36 dxvk (v2.1-67-g5c8ed491)

Repro steps:
1. Select Single Player
2. Select Single Event
3. Press Go Race in the lower right
4. After it finishes loading, press any key/touch screen to go to black screen/crash.

### Software information
RaceRoom Racing Experience (211500), default settings.

### System information
System: Steam Deck, reported on Proton Github by a user with a Radeon rx6600 so it appears to affect AMD systems. Does not repro on an Nvidia Desktop.
- Steam OS Version: 3.4.6
- Steam OS Bios: F7A0115
- Wine version: Proton experimental-bleeding-edge-8.0-42015-20230428-pd8a0cb-w8e76cc-d5c8ed4-vc74ffa
- DXVK version: 5c8ed491ab6cb4c74b16d2551353429ac2c80a36 dxvk (v2.1-67-g5c8ed491)

### Log files
[steam-211500.log](https://github.com/doitsujin/dxvk/files/11367272/steam-211500.log)

**Comment by K0bin** [comment]
Apitrace courtesy of @Blisto91: https://mega.nz/file/UwhkSLZa#Ic8WumHRf1kYovA-SL8KZae8AgmIgEKZWSBEEhv8Pbw

He also bisected it down to d9a6b40ae399f190fc41c7aa2806d56a64bec5f9.
