### ISSUE TITLE
[Feature Request] Resolution custom (Like Dgvoodoo2)

### ISSUE THREAD

**Issue by UserGit-2021** [doitsujin/dxvk#3387]
it would be nice to add a function to install resolutions that are not supported above.

Example:

Comparison of in-game interface size at 2560x1440 set directly in game options menu(up) and 2560x1440 forced through dgVoodoo 2 with resolution in game options menu set to 1280x720(down).
![изображение](https://user-images.githubusercontent.com/91757058/235534939-7c31dcca-813d-4015-a4fc-e8e9f5a63a55.png)

Example in the game there is no HUD scaling in 4k
Deus Ex Human Revolution
ingame 1920x1080
DXVK 4k
4k game with hud 1920x1080

**Comment by doitsujin** [comment]
Not sure what it is you're asking exactly but [gamescope](https://github.com/ValveSoftware/gamescope) already allows you to "fake" resolutions.

Custom resolutions aren't something that DXVK can do in any meaningful way, those **must** be set on a system level in some way, which is exactly how things like Nvidia's DSR work on Windows.

**Comment by UserGit-2021** [comment]
> Not sure what it is you're asking exactly but [gamescope](https://github.com/ValveSoftware/gamescope) already allows you to "fake" resolutions.
> 
> Custom resolutions aren't something that DXVK can do in any meaningful way, those **must** be set on a system level in some way, which is exactly how things like Nvidia's DSR work on Windows.

Thanks for the answer!

**Comment by DinJerr** [comment]
> Not sure what it is you're asking exactly but [gamescope](https://github.com/ValveSoftware/gamescope) already allows you to "fake" resolutions.
> 
> Custom resolutions aren't something that DXVK can do in any meaningful way, those **must** be set on a system level in some way, which is exactly how things like Nvidia's DSR work on Windows.

What dgVoodoo2 does is not 'faking' the resolution like FSR/DSR or gamescope's upscaling. It is actually setting the ingame resolution to the one set by the user (ie. 1920 x 1440), even if the game has a hard limit on supported resolution (maxes out at 1024 x 768 for example). Another app that can do this is Universal Resolution Changer v2.

**Comment by UserGit-2021** [comment]
> 



> Not sure what it is you're asking exactly but [gamescope](https://github.com/ValveSoftware/gamescope) already allows you to "fake" resolutions.
> 
> Custom resolutions aren't something that DXVK can do in any meaningful way, those **must** be set on a system level in some way, which is exactly how things like Nvidia's DSR work on Windows.

Why not add the ability to set a fake resolution under windows? Why not add the ability to set a fake resolution under windows? Developer D8vk agreed to add the feature.
![изображение](https://github.com/doitsujin/dxvk/assets/91757058/5118463d-b039-44eb-9d06-2950151de090)

**Comment by K0bin** [comment]
> Why not add the ability to set a fake resolution under windows? Why not add the ability to set a fake resolution under windows?

Because we don't really support Windows.
