### ISSUE TITLE
Multiview?

### ISSUE THREAD

**Issue by yaomtc** [doitsujin/dxvk#3393]
> [Only the view mask is used as input, and since we do not use MultiView, it is always 0](https://github.com/doitsujin/dxvk/blob/c6668ffbaae41719b20cb9160dcbc2198ba7b88b/src/dxvk/dxvk_shader.cpp)

I'm assuming MultiView refers to [VK_KHR_multiview](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#VK_KHR_multiview). Does DirectX 11 have anything similar that would benefit VR performance via multiview? All I can find is [OpenGL's version](https://community.arm.com/arm-community-blogs/b/graphics-gaming-and-vr-blog/posts/optimizing-virtual-reality-understanding-multiview) and [view instancing in DirectX 12](https://andrewcjp.wordpress.com/2019/07/09/view-instancing-in-directx-12/) (allegedly benefits single pass VR rendering but I don't see mention of VR in documentation)

Recently [NVK gained support for multiview](https://www.collabora.com/news-and-blog/blog/2023/05/03/introducing-multiview-for-nvk/). RADV also supports it. Not sure about Nvidia's proprietary drivers.

**Comment by doitsujin** [comment]
D3D11 does not support Multiview, no. There's vendor extensions for it, but they are poorly documented and incompatible with how Multiview works in Vulkan.

**Comment by yaomtc** [comment]
Thanks! Sounds like it's more for games built for the Quest and other standalone systems that use Vulkan.
