### ISSUE TITLE
[V Rising] crash after start

### ISSUE THREAD

**Issue by Nerus87** [doitsujin/dxvk#3398]
Game crash onto the Windows desktop after the start.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows 
🟢

### Software information
V Rising https://steamdb.info/app/1604030/

### System information
- OS: Windows 10 x64
- GPU: MSI RX 6900 XT
- Driver: 23.4.2/23.4.3
- Wine version: N/A
- DXVK version: Current dxvk-2.1

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace
❌ 

### Log files
[VRising_dxgi.log](https://github.com/doitsujin/dxvk/files/11412234/VRising_dxgi.log)
[VRising_d3d11.log](https://github.com/doitsujin/dxvk/files/11412235/VRising_d3d11.log)

**Comment by doitsujin** [comment]
Game seems to require shared resources which we cannot support on Windows.
