### ISSUE TITLE
Does this work for WPF as well?

### ISSUE THREAD

**Issue by vadi2** [doitsujin/dxvk#340]
Just curious, since WPF (Windows Presentation Framework) is DX-based, would improvements dxvk is bringing translate to WPF-based applications as well?

**Comment by doitsujin** [comment]
Highly doubt it and I don't plan to support such applications.

Reasons why this won't work are:
- DXVK's DXGI implementation is incomplete and broken
- It doesn't support D3D<->GDI interop (*might* be an issue)
- It doesn't any D3D version but D3D11, but WPF probably requires D3D9

**Comment by vadi2** [comment]
Makes sense - thanks for your work!

**Comment by cagnulein** [comment]
Is there any news about it?

**Comment by K0bin** [comment]
IIRC WPF is built on D3D9.
