### ISSUE TITLE
 DXVK: No state cache file found

### ISSUE THREAD

**Issue by RomarioGee** [doitsujin/dxvk#3400]
Hello,

I am actually desperate so decided to create account just to ask this question. Windows 11, dxvk-2.1.tar version.
GTA 4 keeps crashing (last time it said I have run out of video memory). I think that might be the missing cache file. I can't find it anywhere. Not in C:\STEAM\steamapps\shadercache nor in the root game directory. I have tried adding dxvk.conf file with 
DXVK_STATE_CACHE_PATH=\C:\STEAM\steamapps\common\Grand Theft Auto IV\GTAIV
I also tried putting it in Steam launch options. Tried different combinations with the slashes the other way. Please can someone give me the correct way how to generate that state cache??? Please

info:  Game: GTAIV.exe
info:  DXVK: v2.1
info:  Found built-in config:
info:    d3d9.supportDFFormats = False
info:    dxgi.emulateUMA = True
info:    d3d9.customVendorId = 1002
info:  Effective configuration:
info:    d3d9.customVendorId = 1002
info:    dxgi.emulateUMA = True
info:    d3d9.supportDFFormats = False
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Vulkan: Found vkGetInstanceProcAddr in vulkan-1.dll @ 0x7bd6b770
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce RTX 3080:
info:    Driver: 531.79.0
info:    Vulkan: 1.3.236
info:    Memory Heap[0]: 
info:      Size: 10067 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 16336 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 214 MiB
info:      Flags: 0x1
info:      Memory Type[4]: Property Flags = 0x7
info:  Process set as DPI aware
info:  Device properties:
info:    Device name:     : NVIDIA GeForce RTX 3080
info:    Driver version   : 531.79.0
info:  Enabled device extensions:
info:    VK_EXT_attachment_feedback_loop_layout
info:    VK_EXT_conservative_rasterization
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state3
info:    VK_EXT_fragment_shader_interlock
info:    VK_EXT_full_screen_exclusive
info:    VK_EXT_graphics_pipeline_library
info:    VK_EXT_hdr_metadata
info:    VK_EXT_memory_priority
info:    VK_EXT_non_seamless_cube_map
info:    VK_EXT_robustness2
info:    VK_EXT_shader_module_identifier
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_external_memory_win32
info:    VK_KHR_external_semaphore_win32
info:    VK_KHR_pipeline_library
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 0
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 1
info:    shaderResourceResidency                : 0
info:    shaderResourceMinLod                   : 0
info:    sparseBinding                          : 0
info:    sparseResidencyBuffer                  : 0
info:    sparseResidencyImage2D                 : 0
info:    sparseResidencyImage3D                 : 0
info:    sparseResidency2Samples                : 0
info:    sparseResidency4Samples                : 0
info:    sparseResidency8Samples                : 0
info:    sparseResidency16Samples               : 0
info:    sparseResidencyAliased                 : 0
info:  Vulkan 1.1
info:    shaderDrawParameters                   : 0
info:  Vulkan 1.2
info:    samplerMirrorClampToEdge               : 1
info:    drawIndirectCount                      : 1
info:    samplerFilterMinmax                    : 0
info:    hostQueryReset                         : 1
info:    timelineSemaphore                      : 1
info:    bufferDeviceAddress                    : 0
info:    shaderOutputViewportIndex              : 1
info:    shaderOutputLayer                      : 1
info:    vulkanMemoryModel                      : 1
info:  Vulkan 1.3
info:    robustImageAccess                      : 0
info:    pipelineCreationCacheControl           : 1
info:    shaderDemoteToHelperInvocation         : 1
info:    shaderZeroInitializeWorkgroupMemory    : 0
info:    synchronization2                       : 1
info:    dynamicRendering                       : 1
info:  VK_AMD_shader_fragment_mask
info:    extension supported                    : 0
info:  VK_EXT_attachment_feedback_loop_layout
info:    attachmentFeedbackLoopLayout           : 1
info:  VK_EXT_conservative_rasterization
info:    extension supported                    : 1
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_extended_dynamic_state3
info:    extDynamicState3AlphaToCoverageEnable  : 0
info:    extDynamicState3DepthClipEnable        : 1
info:    extDynamicState3RasterizationSamples   : 0
info:    extDynamicState3SampleMask             : 0
info:  VK_EXT_fragment_shader_interlock
info:    fragmentShaderSampleInterlock          : 0
info:    fragmentShaderPixelInterlock           : 0
info:  VK_EXT_full_screen_exclusive
info:    extension supported                    : 1
info:  VK_EXT_graphics_pipeline_library
info:    graphicsPipelineLibrary                : 1
info:  VK_EXT_memory_budget
info:    extension supported                    : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 1
info:  VK_EXT_non_seamless_cube_map
info:    nonSeamlessCubeMap                     : 1
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 1
info:    robustImageAccess2                     : 1
info:    nullDescriptor                         : 1
info:  VK_EXT_shader_module_identifier
info:    shaderModuleIdentifier                 : 1
info:  VK_EXT_shader_stencil_export
info:    extension supported                    : 0
info:  VK_EXT_swapchain_colorspace
info:    extension supported                    : 0
info:  VK_EXT_hdr_metadata
info:    extension supported                    : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  VK_KHR_external_memory_win32
info:    extension supported                    : 1
info:  VK_KHR_external_semaphore_win32
info:    extension supported                    : 1
info:  VK_NVX_binary_import
info:    extension supported                    : 0
info:  VK_NVX_image_view_handle
info:    extension supported                    : 0
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 1
info:    Sparse   : 0
warn:  DXVK: No state cache file found
info:  DXVK: Graphics pipeline libraries supported
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              3840
info:      - Height:             2160
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           false
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Color space:  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  3840x2124
info:    Image count:  3
info:    Exclusive FS: 0
info:  Setting display mode: 3840x2160@0
info:  Setting display mode: 3840x2160@0
info:  DXVK: Using 16 compiler threads
info:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce RTX 3080:
info:    Driver: 531.79.0
info:    Vulkan: 1.3.236
info:    Memory Heap[0]: 
info:      Size: 10067 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 16336 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 214 MiB
info:      Flags: 0x1
info:      Memory Type[4]: Property Flags = 0x7
info:  Process set as DPI aware
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              3840
info:      - Height:             2160
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           false
info:  Setting display mode: 3840x2160@144
info:  Setting display mode: 3840x2160@144
warn:  D3D9DeviceEx::QueryInterface: Unknown interface query
warn:  4a5db83a-855b-445d-9bd7-a22b9ad1a220
warn:  D3D9DeviceEx::QueryInterface: Unknown interface query
warn:  db6f6ddb-ac77-4e88-8253-819df9bbf140
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Color space:  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  3840x2160
info:    Image count:  3
info:    Exclusive FS: 0
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 182
warn:  D3D9DeviceEx::SetRenderState: Unhandled render state 183
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              3840
info:      - Height:             2160
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           false
info:  Setting display mode: 3840x2160@144
info:  Setting display mode: 3840x2160@144

**Comment by mbriar** [comment]
The state cache missing is never a fatal error and it's also not useful anymore for d3d9 games.

**Comment by RomarioGee** [comment]
> The state cache missing is never a fatal error and it's also not useful anymore for d3d9 games.

But what about all those warnings in the log???

**Comment by Blisto91** [comment]
Warnings are usually not fatal and most of the time not important. Tho can ofc be useful for debugging some issues types.

the dxvk state cache file is not created anymore unless needed. In the past a empty one would always be created even if it wasn't used.
> info: DXVK: Graphics pipeline libraries supported

This is the feature that mostly has made them obsolete.

**Comment by mbriar** [comment]
None of those warnings matter. You're issue is probably that the game runs out of 32bit address space. You want to make sure that the .exe is patched to be large address aware so that it can use 4 instead of 2GB of RAM. You can find a patcher here: https://www.techpowerup.com/forums/threads/large-address-aware.112556/

**Comment by RomarioGee** [comment]
Thnx guys for such promptly response. I just installed big texture pack so that migh have been the problem (game uses 5500 of vram go figure).
But I rather remove all mods and jus keep this amazing tool. I managed to make windows autohdr work in this game and it looks amazing. That exe fix might do the trick...I remeber something from Skyrim legendary edition.

**Comment by Blisto91** [comment]
> big texture pack

Could you link it? Then i can try to check it out

**Comment by RomarioGee** [comment]
> > big texture pack
> 
> Could you link it? Then i can try to check it out
I haven't tried the large address aware fix yet. As I am not at the pc right now. But if you have the game installed that would be great 
https://www.nexusmods.com/gta4/mods/105?tab=description&BH=1
The only other mod is fusion fix. And it's gta 4 complete edition on steam lateste version no downgrade. The game would crash after about an hour of play woth no prompts. But yesterday after the texture pack. It was a popup with red cross sighn...that I ran out of video memory or something. Hope this helps

**Comment by Blisto91** [comment]
@RomarioGee Is this still an issue today?
I tried the mod a while back but i am unsure if i got it running properly or was in the right area.

**Comment by K0bin** [comment]
> Please can someone give me the correct way how to generate that state cache???

It should just work without you having to do anything.

**Comment by anthoncast** [comment]
It's weird cause sometimes DXVK will create cache, but its size will be just 1kb, even if the vulkan cache through steam is disabled and all.

It worked with Async sooooo, maybe you should try Async, it works for me to create cache and run the game smoothly.

**Comment by Blisto91** [comment]
State cache isn't used much anymore so that is expected
