### ISSUE TITLE
Black Mesa Hud

### ISSUE THREAD

**Issue by lotexiu** [doitsujin/dxvk#3404]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Black Mesa
Full Graphics
DirectX 9

### System information
- GPU: RTX 2060
- Driver: Last Version - 531.79
- Wine version: none -Windows
- DXVK version: 2.1

### Apitrace file(s)
[bms_d3d9.log](https://github.com/doitsujin/dxvk/files/11415381/bms_d3d9.log)
- I'm sorry, but I didn't understand how it works and how to perform the procedure

### Log files
I'm sorry but I'm not using wine and proton and I don't know how to use them in windows

**Comment by Blisto91** [comment]
What is your issue?

**Comment by lotexiu** [comment]
Hello, I'm sorry I can't help much, but I'm having problems with the black table hud when I try to use dxvk.
The game opens normally but the game hud does not appear
I tried both versions, since in releases, version 1.10 said about black table (I tested it to see if I could change something)

**Comment by lotexiu** [comment]
do you want me to redo it with version 2.1?

**Comment by Blisto91** [comment]
Launch the game with `-oldgameui`
The main menu uses shared resources which dxvk does not support on Windows.

**Comment by lotexiu** [comment]
ok i will try here

**Comment by lotexiu** [comment]
Thank you, it worked.
Thanks for the help and sorry for the inconvenience
[bms_d3d9.log](https://github.com/doitsujin/dxvk/files/11415425/bms_d3d9.log) 2.1

**Comment by Blisto91** [comment]
np
