### ISSUE TITLE
Dxvk can't detect the dxvk.conf file in certain games

### ISSUE THREAD

**Issue by g-k-m** [doitsujin/dxvk#3406]
### System information
- GPU: Amd Vega 56
- Driver: 23.4.2
- DXVK version: 2.1
- OS: Windows 10 21H2 v19044.2846

So yeah this one is really simple. For most of the games i've tried dxvk detects the dxvk.conf file correctly (i put it next to the exe) and then in the log xxx_dxgi.log i get like:

info:  Found config file: dxvk.conf
info:  Effective configuration:
info:    dxvk.hud = 1

however in certain games like diablo 3 these lines are simply missing, yet the same copied .conf file is right next to the exe and nothing changed, dxvk just cannot detect that the .conf file is right there

![image](https://user-images.githubusercontent.com/37273303/236703327-eac2ecfc-81f0-4da5-9c8b-a39518425711.png)

How the log looks like:
![image](https://user-images.githubusercontent.com/37273303/236703380-f35d78b2-9e93-43f7-907c-3a5338c40de3.png)

How it should look like:
![image](https://user-images.githubusercontent.com/37273303/236703423-a8e4132c-c5c0-427a-ae5f-9851619353aa.png)

like it's literally right there but dxvk just doesn't see it, and obviously i wouldn't care about a few lines in the log missing but i get no HUD at all in-game which is an issue

**Comment by K0bin** [comment]
It's possible that the game switches the working directory before loading d3d11.dll. In that case it would look somewhere else for the config file.

As a workaround you can set the environment variable `DXVK_CONFIG_FILE` to the path of your config file.
