### ISSUE TITLE
Disabling the DXVK Vsync on Windows

### ISSUE THREAD

**Issue by fatality342** [doitsujin/dxvk#3410]
Considering that DXVK does work on Windows I figured someone might have an answer.

Recently started using DXVK and saw some massive improvements (55 FPS average —> 90 FPS average on Dying Light, no more stutters and less jitter when moving the camera in cities on AC Origins for example).

However from what I understood, there seems to be a forced Vsync that comes natively with DXVK. Can it be turned off? I tried creating a dxvk.conf file and putting `dxgi.syncInterval = 0` inside, placed it along with the .dlls in the game folder but it doesn’t seem to do anything, mouse movement still feels sluggish and the input lag is still noticeable and I always prefer playing with Vsync off because of it. Using Windows 10. GPU is an AMD R9 380X. Is there something I’m missing?

### Software information
Dying Light, no FPS cap, ingame Vsync Off, 120Hz, Exclusive Fullscreen

### System information
- GPU: AMD Radeon R9 380X
- Driver: 21.5.2
- Wine version: Using Windows 10, not Linux
- DXVK version: 1.10.3

**Comment by Blisto91** [comment]
>  tried creating a dxvk.conf file and putting dxgi.syncInterval = 0 inside

That is the one yes if playing d3d11 or d3d10 games. For d3d9 you'd use `d3d9.presentInterval = 0`
Note that not all games will pick up the conf file next to the dll's since it depends on their working directory so you'll have to check in the logs if the options are picked up. It's the same location the logs are generated you'd want to wput the conf file.
Besides that you can use the environment variable `DXVK_CONFIG_FILE` to point to a `dxvk.conf` file you've placed somewhere and it should always get picked up. If you set it through the Windows gui you might have to reboot first, not sure.

**Comment by mbriar** [comment]
DXVK doesn't force any vsync by default and just using the in-game setting should work fine.

10 May 2023, 11:26 by ***@***.***:

**Comment by fatality342** [comment]
Thanks for all of the help, I did set it through the Windows GUI and I haven't actually restarted the PC since then, will try that later today and report back.

**Comment by doitsujin** [comment]
As was mentioned, DXVK **does not** force Vsync, and if the in-game options do not work then setting `syncInterval` won't help either. There's likely something wrong with the way your driver is configured.

**Comment by fatality342** [comment]
Update: restarting the PC didn't seem to help but setting maxFrameLatency to 1 for sure did, there's no noticeable input lag anymore, game is running smooth as butter and is very responsive now. Will mark this as solved and hopefully this thread helps someone in the future if they somehow end up dealing with a similar nuisance.

A big thanks to everyone that tried to help, especially doitsujin for his solution and DXVK itself, a very impressive project. Will continue to use it and test it in other titles for sure.

Best regards
