### ISSUE TITLE
God Of War stutters a lot

### ISSUE THREAD

**Issue by Joovsr** [doitsujin/dxvk#3412]
God of war stutters a lot. 

Same problem in windows 11 (with dxvk 2.1)

### Software information
God Of War, high graphic preset

### System information
- GPU: rx5700
- Driver: RADV MESA 22.0.3
- Wine version: Proton GE 8.3, 7.53, Wine 8,2
- DXVK version: 2.1

### Apitrace file(s)
https://www.upload.ee/files/15216603/GoW.trace.html

### Proton log file

https://www.upload.ee/files/15216674/Proton_log.txt.html
https://github.com/doitsujin/dxvk/files/11441117/Proton_log.txt

**Comment by doitsujin** [comment]
^ this is the correct answer, there's no bug here.
