### ISSUE TITLE
DLLs Untrusted By EAC.

### ISSUE THREAD

**Issue by SirSAC** [doitsujin/dxvk#3414]
The "d3d11.dll" and "dxgi.dll" triggers the EasyAntiCheat and blocks the DLLs saying 'Untrusted file'.
I think this issue can be fixed by making the DLLs to have any kind of certificate, like ReShade which it works fine with games that have EAC.

I'm in for testing this issue by trying in games that have EAC.

### Software information
All games with EasyAntiCheat from Steam like Crossout or War Thunder.

### System information
- GPU: NVIDIA GeForce GT 1030
- Driver: 531.79.0
- Vulkan version: 1.3.236
- DXVK version: v2.1

**Comment by Riesi** [comment]
The anticheat is just doing its job. Nothing dxvk can do about it when a game refuses to load it on windows.

Also you wont get a (**advertised by random reddit people**) performance boost anyway, so not worth risking a ban by trying to bypass things.

**Comment by Riesi** [comment]
Also looking up your GPU shows it having only 2GB of VRAM. That will also play very badly with dxvk's higher VRAM consumption and worse memory management.

**Comment by SirSAC** [comment]
Maybe you are right but is my choice and my own risk, also for League of Legends is x2 FPS boost (from 102 avg to 220 avg) and LoL have too an Anti Cheat but is much smarter than dumb EAC.
Also if u know how to add a certificate to the DLLs please let me know how or give me a link about how to do it.

Btw it should be allowed or ignored that kind of modification on the game bcs is not a modification of how it looks or some addition to give different advantages against other players, it just act like I have better GPU or drivers (GT 1030 with DXVK or GTX 1080 with native DX is the same thing in term of functionality).

Thanks anticipated and have a nice day :)

**Comment by K0bin** [comment]
Take this to either Epic Games or the developer of the game you want to play.

There is nothing we can do about it.

**Comment by Redundanz** [comment]
a certificate does nothing if the dll is not whitelisted by eac devs through its file hash.
what you actually can do is ask the eac devs to include dxvk .dlls in their whitelist. regardless of any pseudo "certificate".

**Comment by SirSAC** [comment]
> a certificate does nothing if the dll is not whitelisted by eac devs through its file hash. what you actually can do is ask the eac devs to include dxvk .dlls in their whitelist. regardless of any pseudo "certificate".

Good to know, I will search to see if I can manipulate the hash of the file to be different or to change it.

**Comment by Blisto91** [comment]
You really should not mess around with anti cheat.

**Comment by bno1** [comment]
About digital signatures, Microsoft's dlls are digitally signed with their private key. It's impossible to convince EAC that dxvk dlls are signed by Microsoft unless you can obtain their private key and sign them yourself. Don't waste your time on that.

**Comment by SirSAC** [comment]
Is not a waste of time, at least for me, I don't have anything good to do with my time.
Also how to update/upgrade the submodule hash, if I changed the repo with a fork but is identically. maybe with some additions but not much.

**Comment by mbriar** [comment]
It is a waste of time because it will not work. You can't fake a cryptographic hash.

**Comment by Blisto91** [comment]
And the point of anti cheat is that they shouldn't allow any random file to do what ever they want. If you could just circumvent that easily it would destroy the point.

This will not be officially supported and Windows isn't either. So if it doesn't work that is just that and we advise that you shouldn't mess with anti cheat in general.
