### ISSUE TITLE
Stuck at splash screen. Ghost recon Wildlands

### ISSUE THREAD

**Issue by Rozin14** [doitsujin/dxvk#3418]
Wildlands gets stuck at its splash logo screen, whatever DXVK version used. I even used async version. The logs attached is when i used DXVK (dxgi log was not created when using dxvk 2.2, it was created when using latest async version). And api trace log when its dlls are used (apitrace didnt create d3d11 and dxgi logs). The game crashes when the api trace is being generated

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Ghost recon wildlands

### System information
- GPU: RTX 3070 Laptop
- Driver: 531.61
- Windows version:  W11 22H2
- DXVK version: 2.2, 1.10.1, 1.10.3

### Apitrace file(s)
https://drive.google.com/file/d/1JM9WlZUoMfQGgAqWjQC9N3NPIuMblSjU/view?usp=share_link
### DXVK log file(s)
[GRW_d3d11.log](https://github.com/doitsujin/dxvk/files/11478810/GRW_d3d11.log)
[GRW_dxgi.log](https://github.com/doitsujin/dxvk/files/11478811/GRW_dxgi.log)

**Comment by K0bin** [comment]
Both Windows and Nvidia Optimus, so I assume this is something well out of our control.

**Comment by Rozin14** [comment]
the laptop has mux switch. its on and its similar to desktop. no igpu is on.

**Comment by Blisto91** [comment]
I can quickly try it later both on Linux and Windows with AMD. But i don't expect to see anything.

**Comment by Rozin14** [comment]
> I can quickly try it later both on Linux and Windows with AMD. But i don't expect to see anything.

But my gpu is nvidia

**Comment by K0bin** [comment]
> the laptop has mux switch. its on and its similar to desktop. no igpu is turned on.

That doesn't matter. Optimus still causes problems.

**Comment by Rozin14** [comment]
Can the api trace log be decoded to find what makes it stuck?

**Comment by Blisto91** [comment]
Probably not. Since i don't think the game itself is the issue looking at ProtonDB.
Have you tried turning off Ubisoft overlay?

**Comment by Rozin14** [comment]
yes. and the anitcheat is off using a nexusmod dll. So anticheat is not the one conflicting

**Comment by Blisto91** [comment]
We had a opposite at one point where people couldn't launch a game with the overlay was turned off hehe https://github.com/doitsujin/dxvk/issues/2655
Overlays are fun

**Comment by Blisto91** [comment]
> yes. and the anitcheat is off using a nexusmod dll. So anticheat is not the one conflicting

What nexusmod dll?

**Comment by Blisto91** [comment]
Tried with it on Windows but still not reproducing

**Comment by wiryfuture** [comment]
I *may* have this issue. Running in bottles and it gets stuck at splash but *also* it creates a black window that is only part of my screen's full size at ~ 1080p (I have an ultrawide) with the game's icon and title, which is resizeable. It stays like this.

**Comment by wiryfuture** [comment]
Very very fast reply, the game appears to work for me if you set the wine "windows" version to 7. On 10, 8.1 and 8 it didnt seem to work, but set to 7 it seems to launch very quickly (even faster compared to what I remember it being like natively launching on windows).
I suggest you try this out.
- Cheers

**Comment by Blisto91** [comment]
@Rozin14 could you try this again with dxvk 2.3 and latest driver?

**Comment by Rozin14** [comment]
> @Rozin14 could you try this again with dxvk 2.3 and latest driver?

Sorry for being late. Gmail android for some reason didn't notify me about your reply. 

Unfortunately, it crashes suddenly after splash logo. 
[GRW_dxgi.log](https://github.com/doitsujin/dxvk/files/12699417/GRW_dxgi.log)

**Comment by Rozin14** [comment]
Any ideas to solve this?

**Comment by Blisto91** [comment]
Reinstall your graphics drivers. Clean install if Nvidia have setup a option or tool.

**Comment by Rozin14** [comment]
Just did DDU. Still same error. Strange

**Comment by Blisto91** [comment]
Could try to install the vulkan runtime seperately https://vulkan.lunarg.com/sdk/home
Though that shouldn't be necessary in general as the driver installation should just work and come with all it needs.

**Comment by Rozin14** [comment]
<img width="292" alt="image" src="https://github.com/doitsujin/dxvk/assets/70478114/cc70682c-e7b1-4b63-9893-67abacb6af4d">
Strange

**Comment by Rozin14** [comment]
> Reinstall your graphics drivers. Clean install if Nvidia have setup a option or tool.

Fixed the vulkan issue finally. It was the amd driver conflicting. Anyways there's a slight progress I'd say. The game is still stuck in splash logo, but now theres also a black window. Just like philipwilk's case above. But he's in linux and fixed it by changing windows comparability something.

**Comment by Rozin14** [comment]
@Blisto91 Used DXVK GPLASYNC 2.3 and conf file with enableasync=true.    IT'S WORKING NOW!!!
![Screenshot (51)](https://github.com/doitsujin/dxvk/assets/70478114/bf8ef050-5527-44e1-9c0f-bedafde90d1a)
  Game boots up. rtss overlay reports vulkan API used.  Now i can play without the horrible dx11 stuttering. Gameplay is butter fluid now. DXVK is a god send for old titles.

**Comment by Rozin14** [comment]
Additional: i found that if i remove amd ags dll that came with the game, it doesn't work. Stays at windowed black screen. Dxvk (async true or flase) only works if that dll is present in the root folder. But this is opposite of what dxvk windows wiki says.

**Comment by Blisto91** [comment]
Maybe there was some bad cache. Not sure.

> But this is opposite of what dxvk windows wiki recommends.

What wiki is that. Not surprised a game might not like that. Usually better just to spoof another vendor id
