### ISSUE TITLE
OpenGL to Vulkan (DXVK) please

### ISSUE THREAD

**Issue by SirSAC** [doitsujin/dxvk#3419]
I wish OGL to DXVK for some weird games I have on my CD/DVD discs.
It should be easy to implement because Vulkan and OpenGL is made by Khronos Group.

### Software information
Valley.exe, Heaven.exe from Unigine

### System information
- GPU: GT 1030, GT 730 (this one is only for PhysX)
- Driver: 531.79
- Windows version: 11 Enterprise
- DXVK version: 2.2 with the latest fix

**Comment by mbriar** [comment]
There is already wined3d, which can also be used on windows, for translating D3D to opengl, there is just almost no reason to use it on windows because native d3d drivers exist and are better almost all of the time. OpenGL also being made by Khronos doesn't mean anything, you'd probably have to completely rewrite DXVK to make it work on OpenGL.

**Comment by SirSAC** [comment]
Yea but I'm using Windows not Linux.
I will move to Linux when will work with EAC (Easy Anti Cheat).

**Comment by mbriar** [comment]
Like I said, you can use wined3d D3D -> OpenGL translation on windows as well. I just don't know why you would even want to, just use native D3D drivers.

**Comment by mbriar** [comment]
Oh wait, just mean OpenGL to vulkan translation? For that there is already zink and also dozen for translating OpenGL to D3D12. DXVK definitely won't support that ever.

**Comment by SirSAC** [comment]
I cant because is running on opengl32.dll not on some kind of d3d9.dll

**Comment by SirSAC** [comment]
I use Process Explorer and shows me only opengl32.dll is loaded and nothing about DirectX

**Comment by Blisto91** [comment]
You will want to look in to Zink not dxvk. It won't be supported here.
I have no idea about the status of being able to use Zink on Windows tho.

> It should be easy to implement because Vulkan and OpenGL is made by Khronos Group.

You probably don't mean it in a bad way, but please understand that is 100% not true and is a massive effort. The people working on Zink is doing amazing work and it certainly isn't easy.

**Comment by doitsujin** [comment]
Zink already exists, and implementing all of OpenGL from scratch would take *literal decades*.

**Comment by SirSAC** [comment]
Ok, I will take a look at Zink.
