### ISSUE TITLE
game is not runing

### ISSUE THREAD

**Issue by ahmadreza-ms** [doitsujin/dxvk#3423]
after i adding the file and run . game not opening 
![Annotation 2023-05-17 095819](https://github.com/doitsujin/dxvk/assets/75027468/1bb8c3b2-1a26-4b98-be9e-b145f0ddd08c)

**Comment by SirSAC** [comment]
Is just staying on background? do u have sound at least?

**Comment by SirSAC** [comment]
Also let me know if is DirectX 9 game or 11.

**Comment by K0bin** [comment]
Please provide the necessary information about your system and the DXVK logs. All of that should have been in the issue template.

Also read up on problems within using DXVK on Windows here: https://github.com/doitsujin/dxvk/wiki/Windows

**Comment by ahmadreza-ms** [comment]
> Also let me know if is DirectX 9 game or 11.

11.1

**Comment by SirSAC** [comment]
Did u put the DXGI and D3D11?

**Comment by Blisto91** [comment]
That is not how it works. dxvk already use 1.3 core features. 
Anyway this is offtopic.

@ahmadreza-ms As K0bin wrote above we need some basic system info like GPU and drivers. Also please post dxvk logs so we can see dxvk version used.
This is almost certain not a dxvk issue as this game gets tested fairly often on Linux.
