### ISSUE TITLE
Halo online black texture issue

### ISSUE THREAD

**Issue by Minelelol** [doitsujin/dxvk#3429]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Halo Online Ms23 (Using the Eldewrito Mods) 
Everything is on High except for Shadow Quality (low) , and Motion blur is off
Some part of the game texture and weapon scope are black.

One of my friend play with dxvk and he has encountered these issue too hes using an Intel Arc GPU

### System information
- GPU: RX 570 4GB RED Dragon
- Driver: Amernimezone custom driver 23.4.2 ( Issue also appear on AMD Official Driver )
- Windows Version : W10 Pro 21H2
- DXVK version: 2.2

### Apitrace file(s)

Last Resort : https://drive.google.com/file/d/1GaTeAk2k_rhUsxC-ci6b4kAI2aKyP9gL/view?usp=share_link
Edge : https://drive.google.com/file/d/1yevOuJKd-mUyDoaqWw08x6HPOr1RNwRR/view?usp=share_link
Narrows : https://drive.google.com/file/d/14VxvO6iEu8S8t4FvNbhUobarNbycOYbl/view?usp=share_link

Last Resort Skyboxes water are black
![Last Resort Normal](https://github.com/doitsujin/dxvk/assets/89744342/e906d94b-1360-46b9-8284-95deb13668ac)
![Last Resort DXVK](https://github.com/doitsujin/dxvk/assets/89744342/db497c0f-4638-4549-a7f8-b4ce1ebb52d8)

Edge Grass are black
![EDGE NORMAL](https://github.com/doitsujin/dxvk/assets/89744342/6fa2a230-aed4-47a4-94c4-dd0cb1ec34a5)
![EDGE DXVK](https://github.com/doitsujin/dxvk/assets/89744342/44b01434-597a-47f0-ac5f-8e678488f04d)
![Battle_RIF Acc NORMAL](https://github.com/doitsujin/dxvk/assets/89744342/758cf709-6818-49a0-8e40-3a2cef0724fa)
![Battle Rif Acc DXVK](https://github.com/doitsujin/dxvk/assets/89744342/95ed1b58-8741-4375-b0a4-08af838bfa78)
![EDGE Pistol Power Normal](https://github.com/doitsujin/dxvk/assets/89744342/c4ef6b39-387e-4402-9065-7cc794f99e02)
![EDGE Pistol Power DXVK](https://github.com/doitsujin/dxvk/assets/89744342/baf23589-5600-4c29-aa10-d994f8faa352)

Narrows Floor are black
![Narrows Normal](https://github.com/doitsujin/dxvk/assets/89744342/e3ba28f5-e4f0-4ddb-8b67-13130cdd8704)
![Narrows DXVK](https://github.com/doitsujin/dxvk/assets/89744342/63215adb-52ef-4248-829d-c8f8182b038a)

**Comment by Blisto91** [comment]
@Minelelol Hello and thank you for the issue. Can you verify that the issue goes away ingame when you make a file called `dxvk.conf` next to the exe (or where ever the logs appear) and insert `d3d9.floatEmulation = Strict` ?

**Comment by Minelelol** [comment]
Dang nice it did fixed the issue
![screenshot-2023 05 18-18 55 29](https://github.com/doitsujin/dxvk/assets/89744342/ba247773-8030-47c1-89d6-057546532322)
thank you so much<3
is there a link that shows all of dxvk config commands that would be nice

**Comment by Minelelol** [comment]
yep, I guess there no reason to keep this issue open I assumed

**Comment by Blisto91** [comment]
The above PR will close it when merged. Might as well set the config for the exe internally in dxvk.
