### ISSUE TITLE
Tomb Raider Anniversary (Steam)

### ISSUE THREAD

**Issue by SillySwitch** [doitsujin/dxvk#3438]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Name of the game, settings used etc.

### System information
- GPU: GTX 3050 TI - Laptop Edition
- Driver: Nvidia Driver 525
- Wine version: Proton Experimental
- DXVK version: Proton Experimental

### Friends System information for further testing
- GPU: AMD Vega 56
- Driver: Mesa Version 23.03-1
- Wine version: Proton Experimental
- DXVK version: Proton Experimental

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

###
When testign Tomb Raider Anniversary, a friend and I were playing through Croft Manor and noticed that there is a heavy dip in fps performance in front of the hedge maze when you go to the back area. 
The dip can go even below 30fps, but maintains a consistent 130-144 everywhere else. 

When testing on my PC, I did switch OpenGL useing code PROTON_USE_WINED3D=1  %command% and this maintained a 144fps pretty consistently even when looking at the hedge maze. 
I have included a log with my report. 
I can also confirm the same issue is happening with my friends hardware, who is using AMD with mesa drivers, so I do not think this is a Nvidia issue.

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.
[steam-8000.log](https://github.com/doitsujin/dxvk/files/11525370/steam-8000.log)

**Comment by K0bin** [comment]
> Apitrace file(s)
Put a link here
For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

Please do that. I need the apitrace to look into this.

Please also upload your save and a bunch of screenshots so I know precisely what you're talking about.

**Comment by Blisto91** [comment]
https://mega.nz/file/Jo41FYAb#_B-vqrtbG-9NEyBq0PPlevdxAVkZuyW6J_FnIBb4u4A made together with `d3d9.apitraceMode = True` with also seems to alleviate the issue quite a bit. Tho performance isn't stiller in those areas considering my specs (7950x & 7900xtx

**Comment by Blisto91** [comment]
We might also wanna cap the fps to 60 for this and it's related games as the physics and AI can become quite buggy otherwise apparently.
Managed to stretch Lara's hair quite long

**Comment by SillySwitch** [comment]
Hey @K0bin and @Blisto91 
I'm on Pop_OS, and have Gnome as a my Interface. 
So the .trace file is not showing up, not sure if this is a Gnome issue or not. 

I can confirm I folllowed the steps, and say that Tomb Raider Anniversary was showing up as a 32bit game .exe and I copied over the .dll files (d3d9.dll, d3d11.dll, dxgi.dll and dxgitrace.dll) and made sure to run the game with  PROTON_USE_WINED3D=1  %command% so as to not be using any Vulkan codes. 

I was unable to produce a .trace file with this however. 
I can confirm the game was running at a stable 144fps during this testing though, even when looking at the hedge maze 

Here are screen shots with Vulkan running, showing the dips
The AMD mesa ones are from my friend, the others are from me using Nvidia 

[TR-Anniversary hedge maze.zip](https://github.com/doitsujin/dxvk/files/11525577/TR-Anniversary.hedge.maze.zip)
https://drive.google.com/file/d/1XNvqYbb6kr9BwmPIh3cSdFbo4CTGuPJG/view?usp=sharing

**Comment by mbriar** [comment]
PROTON_USE_WINED3D=1 will prevent apitrace from working because it will set the relevant dlls to `buildin`, for apitrace to work they have to be either `native` (proton default, will trace with DXVK) or `native,buildin` (will trace with wined3d). For this issue it seems totally fine to trace with DXVK though.

**Comment by SillySwitch** [comment]
@mbriar When I ran it vanilla without anything in command the game ran to a crawl on single digit fps, and still didn't create a .trace file 
So maybe there is some files I am not deleting or some setting I am not setting. 

When I removed the .dll files it went back to full 144fps, but then did the dips when running on Vulkan whenever I went to view the hedge maze

**Comment by K0bin** [comment]
You didn't upload the save either.

**Comment by SillySwitch** [comment]
I found the trace file
I'll include it here, along with the save file 

Save file 
https://drive.google.com/file/d/12H8dZJKbFnBLYIUbqVqp_qtl8RyScW9y/view?usp=sharing

Trace File 
https://drive.google.com/file/d/1MLsgrTCq0EazuafpXoAJ4srYrMj1SslS/view?usp=sharing

**Comment by K0bin** [comment]
Thanks for the bug report!

We've fixed the issue. It should run very well now.

**Comment by SillySwitch** [comment]
Thanks for looking into this, I look forward to seeing the update on Steam
