### ISSUE TITLE
Less of an issue, more of a question; regarding shader cache files and Steam

### ISSUE THREAD

**Issue by ShinChaosBahamut** [doitsujin/dxvk#3440]
Question, when Steam writes a game's shader cache files to the shadercache folder due to the shader pre-cache option being enabled, does that prevent the game in question from reading its related cache files?

(game in question is Black Mesa btw; dxvk dll used is 2.2)

**Comment by mbriar** [comment]
No, the game will read the cache file just fine. Side note, but with dxvk >= 2.0 and GPL the cache file doesn't really help that much anymore either way and probably doesn't exactly nothing for games that don't use tessellation or geometry shaders like Black Mesa.
