### ISSUE TITLE
What are the specifics vulkan features to enable pipeline libraries?

### ISSUE THREAD

**Issue by braiam** [doitsujin/dxvk#3443]
While vulkaninfo claims that I have `graphicsPipelineLibraryIndependentInterpolationDecoration` and `graphicsPipelineLibrary` as supported, DXVK claims I do not. I use Sifu in this example, but also happens on Warframe. Using wine-ge-proton 7-41 or wine 8.0.

[Sifu-dxgi.log](https://github.com/doitsujin/dxvk/files/11538526/Sifu-Win64-Shipping_dxgi.log)
[Sifu-d3d11.log](https://github.com/doitsujin/dxvk/files/11538534/Sifu-Win64-Shipping_d3d11.log)

```
info:  AMD Radeon RX 590 Series (RADV POLARIS10):
info:    Driver : radv 22.3.6
```

https://gist.github.com/braiam/f66f4bd4a848c0e348525e6b23f882a9

https://github.com/doitsujin/dxvk/blob/3d5becaf6a3ff228873e2416f9ad96f056ae2ede/src/dxvk/dxvk_device.cpp#L50

**Comment by Blisto91** [comment]
It first got enabled in radv by default here with the release of mesa 23.1.0. Before that because it was still being tested and features being worked on you had to manually enabled it with a env var `RADV_PERFTEST=gpl`

**Comment by DadSchoorse** [comment]
> While vulkaninfo claims that I have `graphicsPipelineLibraryIndependentInterpolationDecoration` and `graphicsPipelineLibrary` as supported, DXVK claims I do not.

vulkaninfo only claims that lavapipe supports those features, your old radv version does not. If you want to use GPL with your gpu you should use at least mesa 23.1.

**Comment by K0bin** [comment]
Update your driver. :)
