### ISSUE TITLE
[d3d9] Injustice God Among Us: perfomance issues during scenario transitions

### ISSUE THREAD

**Issue by ranplayer** [doitsujin/dxvk#3450]
Hello,

In the first Injustice, when we have scenario transitions during a fight (when a player hits the opponent next to edge of the screen), I've observed strange frame spikes and stuttering (and they don't go away after subsequent runs). I've tested the game with **Proton 8.0** and **Mesa 23.1.0**. It might be a game/unreal issue, but I'm attaching the trace anyway to check if something is wrong on the Linux side.

### Software information
Name of the game: Injustice God Among Us
Settings: maxed out (transparency anti-aliasing disabled)
Resolution tested: 1080p

### System information
- GPU: RX 6700 XT (12 Gb)
- Driver: Mesa 23.1.0
- Wine version: Proton 8.0-2
- DXVK version: provided by the Proton

### Apitrace file(s)
- [api trace](https://mega.nz/file/Y9dQ2RLJ#shsfPpujNNcbUfDqEOlaoCS2bWxkJefqpIWwhrfhWaM)

### Log files
Please attach Proton or Wine logs as a text file:
- [d3d9_logs.tar.gz](https://github.com/doitsujin/dxvk/files/11567487/d3d9_logs.tar.gz)

**Comment by Blisto91** [comment]
I see the frame timings/spikes mentioned on Linux when doing scene transitions in the game. Haven't checked on Windows yet.

**Comment by K0bin** [comment]
I tried it on Windows and those spikes during scene transitions happen there as well.

**Comment by ranplayer** [comment]
Ok, folks... thank you for the investigation. Should I close this issue or leave it for others with the same doubt ?

**Comment by K0bin** [comment]
There's still some small performance tweak I'd like to make for the game, so leave it open for now.

**Comment by K0bin** [comment]
We just merged an optimization for the game but don't expect any major improvements. It's an issue with game code, not how they use D3D9, so there's not a lot we can do.

**Comment by ranplayer** [comment]
I see...  I've heard this game port was not so well done. Thank for digging into the issue and for the improvements. I'll test the game with these changes this week.
