### ISSUE TITLE
[d3d9] AquaNox 2 regression (possibly other games as well)

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#3452]
Rendering is broken on master vs 2.2.

<details>
<summary>Here is master</summary>

![Master](https://github.com/doitsujin/dxvk/assets/6306593/26fffa92-59fa-4317-af08-66aca8d00256)

</details>

<details>
<summary>Here is 2.2</summary>

![2 2](https://github.com/doitsujin/dxvk/assets/6306593/91796f2b-7f8f-436f-81ba-3934f8261bb5)

</details>

Bisecting has pinpointed:
```
8560efa3c7c4dbdb8b9fcb6e0aed282b43781c56 is the first bad commit
commit 8560efa3c7c4dbdb8b9fcb6e0aed282b43781c56
Author: Joshua Ashton <joshua@froggi.es>
Date:   Wed May 24 13:27:53 2023 +0100

    [d3d9] Unbind RTs which are unwritten by a PS
    
    Otherwise we can end up with feedback loops on RTs with a 0 color mask.
    
    Closes: #3447

 src/d3d9/d3d9_device.cpp | 21 ++++++++++++++++++---
 1 file changed, 18 insertions(+), 3 deletions(-)
```

### Software information
AquaNox 2 (GOG)

### System information
- GPU: Nvidia RTX 3060
- Driver: 530.41.03
- Wine version: 8.8 Staging
- DXVK version: e065497

### Apitrace file(s)
[AN2.trace.tar.xz](https://drive.google.com/file/d/1ibk6J-pfpYbV7p4gZ-a9hY03B0opQ_ZK/view?usp=share_link)

### Log files
[AN2.log](https://github.com/doitsujin/dxvk/files/11569375/AN2.log)

**Comment by Joshua-Ashton** [comment]
Thanks, I will take a look tomorrow
