### ISSUE TITLE
Grand Theft Auto IV blue sceen

### ISSUE THREAD

**Issue by CaveSpiderII** [doitsujin/dxvk#3456]
Please describe your issue as accurately as possible.
There is a bad bug with grand theft auto iv.The computer turned off and restarted with blue sceen through dxvk.
If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Name of the game, settings used etc.

### System information
- GPU:Intel(R) Iris(R) Xe Graphics
- Driver:0.404.1069
- Wine version: 1.2.195
- DXVK version: 1.7.3

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.
[PlayGTAIV_d3d9.log](https://github.com/doitsujin/dxvk/files/11577032/PlayGTAIV_d3d9.log)

**Comment by mbriar** [comment]
Pretty much guaranteed to be an Intel driver bug.

**Comment by K0bin** [comment]
What mbriar said.

**Comment by CaveSpiderII** [comment]
What can I do by using dxvk with intel graphic card
