### ISSUE TITLE
[d3d11] Lara Croft and the Temple Of Osiris: hanging in a black screen if exclusive fullscreen is enabled

### ISSUE THREAD

**Issue by ranplayer** [doitsujin/dxvk#3458]
In Lara Croft and the Temple Of Osiris, if you enable the "Exclusive Fullscreen" option, the game hangs in a black screen before reaching the main menu. I know in Linux we don't have this concept, but some users just won't know why the game is not working.  For WineD3D it reaches the main menu normally with this option enabled. 

Perhaps the issue might be related to WM messages ? (like https://github.com/doitsujin/dxvk/issues/2569 that was fixed by https://github.com/doitsujin/dxvk/pull/2588)

### Software information
Name of the game:  Lara Croft and the Temple Of Osiris 

### System information
- GPU: RX 6700 XT
- Driver: Mesa 23.1.1 (also happens with previous versions)
- Wine version: Proton 8.0-2
- DXVK version: provided by Proton

### Apitrace file(s)
- I've tried to get a trace, but it won't produce any file (even with WineD3D). Wrappers from: https://github.com/apitrace/apitrace/releases/download/11.1/apitrace-11.1-win64.7z

### Log files
- [LC2_d3d11.log.tar.gz](https://github.com/doitsujin/dxvk/files/11591680/LC2_d3d11.log.tar.gz)
- [steam-289690.tar.gz](https://github.com/doitsujin/dxvk/files/11591683/steam-289690.tar.gz)

**Comment by Blisto91** [comment]
Hi there and thank you for the issue.
I can kinda reproduce. It is a bit weird since i have been able to get through some times. I think both exclusive fullscreen and vsync has to be turned on at the same time maybe? Tho messing back and forth with the settings i can get in with both exclusive and vsync maybe once and then subsequent tries it halts. I think.

**Comment by Blisto91** [comment]
From what i can find it seems to be a regression with commit https://github.com/doitsujin/dxvk/commit/67bd2b5e76539a272581386aba4c3b177af1b546
Also doesn't seem to be tied to vsync also being on as thought at first, just seems more like to happen then but can also make it happen without.

**Comment by ranplayer** [comment]
I was able to get a trace (the .exe was actually 32bits). Also I've found a game specific logging file.

[game_log_no_wrapper.tar.gz](https://github.com/doitsujin/dxvk/files/11592456/game_log_no_wrapper.tar.gz)

[apitrace.tar.gz](https://github.com/doitsujin/dxvk/files/11592458/apitrace.tar.gz)
