### ISSUE TITLE
Borderlands 2 cursor missaligned when using DSR.

### ISSUE THREAD

**Issue by TheDeeGee** [doitsujin/dxvk#3460]
Using DSR 2.25x DL causes the cursor to be missaligned and making it impossible to click certain parts of the menu.

### Software information
Borderlands 2 GOTY (Steam)

### System information
- GPU: RTX 4070 Ti
- Driver: 531.79
- Wine version: N/A
- DXVK version: 2.2

**Comment by K0bin** [comment]
We don't really support Windows, even less so when using driver options that only exist on Windows.

**Comment by doitsujin** [comment]
Mouse cursor position really isn't something that we have any control over to begin with.

**Comment by Joshua-Ashton** [comment]
This isn't something we can solve from our side, sorry.

**Comment by K0bin** [comment]
You could try creating a config file with `d3d9.dpiAware = True`, maybe that helps. See the README for instructions on how to do that.

**Comment by TheDeeGee** [comment]
> You could try creating a config file with `d3d9.dpiAware = True`, maybe that helps. See the README for instructions on how to do that.

May work, but i'll stick to D3D9 after all, since you can't force Anti-Aliasing with Vulkan/DX11/DX12. And Borderlands 2 needs SGSSAA to look smooth.
