### ISSUE TITLE
DXVK version string in DXVK_HUD not longer displaying since 2.1

### ISSUE THREAD

**Issue by Trinity3e** [doitsujin/dxvk#3463]
Starting with v2.1, I cannot longer see the dxvk version in the DXVK_HUD, the installation process is the same as in v2.0 for me, and I could replicate the fact that in 2.0 the dxvk version appears in exactly the same environment, wine prefix version etc on my few PC's with amdgpu.

It shows up the same in v2.2.

Is this known, can I override it somehow?

<img width="206" alt="image" src="https://github.com/doitsujin/dxvk/assets/123660226/3a647854-c5a6-46d4-a3ac-58c6a5106d12">

**Comment by K0bin** [comment]
Does this happen with our release builds or only with builds you compiled yourself? Make sure to fetch the git tags.

Somewhat off topic but you should really use RADV instead of AMDVLK.

**Comment by Trinity3e** [comment]
I am using the release builds.

Hmm, will try to set in the environment AMD_VULKAN_ICD=RADV to see if something changes, maybe performance slightly.

**Comment by WinterSnowfall** [comment]
Are you exporting your own DXVK_HUD env variable, and if so, is there a "version" in it?

**Comment by Trinity3e** [comment]
DXVK_HUD=1
Oh, the documentation changed to require either =full or =version,etc . My bad guys.
