### ISSUE TITLE
[d3d9] Xenus 2 White gold: no ripples on the water.

### ISSUE THREAD

**Issue by CortexReaver** [doitsujin/dxvk#3467]
Something to do with bump maps\spec maps of the water.

![01-06-2023 012218](https://github.com/doitsujin/dxvk/assets/34350690/529960a0-c773-4785-afbb-76d24c5ea9fe)

Originally it should look like this:

![01-06-2023 012415](https://github.com/doitsujin/dxvk/assets/34350690/a2b5e4f3-ef1b-4492-a337-753744446315)

### System information
- GPU: GTX 1050 Ti
- Driver: 531.79 (this bug was on previous version drivers as well)
- OS: Windows 10 2H22
- DXVK version: 2.0, 2.1, 2.2

### Apitrace file(s)
It is working fine with with the Apitrace though, don't know if it helps
https://drive.google.com/file/d/1CyvuyY4YDf6T1iK2-nN6VjKRK5vKZh5K/view?usp=sharing

### Log files

[Xenus_d3d9.log](https://github.com/doitsujin/dxvk/files/11619394/Xenus_d3d9.log)

**Comment by CortexReaver** [comment]
Tested it a bit more: without antialiasing (in game options, not dxvk.conf) everything's fine.

**Comment by Blisto91** [comment]
Hello and thank you for the issue.
Interestingly while testing this on Linux it seems the game doesn't even allow me to turn on AA when it sees i have a AMD gpu. Neither with wined3d nor dxvk since when leaving it the graphics menu it will back it back to "no". If i spoof myself to be a Nvidia GPU i can turn it on, but the issue doesn't reproduce for me so far.

**Comment by K0bin** [comment]
![image](https://github.com/doitsujin/dxvk/assets/1131720/d7fcd756-bb27-4fe1-8e8c-fc7e4afb5b32)

Did you make the apitrace with anti aliasing enabled? It renders correctly when replaying it.

**Comment by CortexReaver** [comment]
> Did you make the apitrace with anti aliasing enabled? It renders correctly when replaying it.

As I wrote in first message

> It is working fine with with the Apitrace though, don't know if it helps

Yes, I'm pretty sure I traced it with AA on. Can it be the older version of apitrace itself? because dll's in this archive are older then 2.1 and 2.2 versions of dxvk.

**Comment by CortexReaver** [comment]
Here's another one, now I've explicitly entered video options and changed AA mode.
https://drive.google.com/file/d/14CTroTVJZ6x2VK5IzhrXCUDY2l0J5M82/view?usp=drive_link

**Comment by Blisto91** [comment]
ye it's the newest version. The apitrace and dxvk are unrelated projects.

The new traces also replay fine for me. Gonna check out the game on Windows later (on AMD)

**Comment by K0bin** [comment]
I appreciate the effort but the new traces replay fine too. I don't have the game so I cant really do anything about it.

**Comment by Blisto91** [comment]
I tried on Windows with dxvk and spoofing to Nvidia so i could turn on AA, but I've still yet to reproduce the issue.

**Comment by CME42** [comment]
I can repro it on pascal (1060) with the apitrace, so probably a pascal specific driver bug.

**Comment by Blisto91** [comment]
@CortexReaver Is this still an issue with latest driver?

**Comment by CortexReaver** [comment]
I've upgraded my graphics card to a RX 6600 recently, so I cannot say for sure for an entire pascal GPU family. Latest I've tried Xenus 2 with 1050 ti I think was in februrary and I remember the water ripples being there... So this was fixed since the 2.3 version.
