### ISSUE TITLE
Test Drive Unlimited 2: Shadows problem

### ISSUE THREAD

**Issue by Nero536** [doitsujin/dxvk#3469]
Shadows don't fall on the grass

### Software information

Test Drive Unlimited 2, high settings

### System information
- GPU: GTX 750 TI
- Driver: 535.98
- OS: Windows 10 21H1 
- DXVK version: 2.2

Directx: 
![d3d9](https://github.com/doitsujin/dxvk/assets/135334701/d0115565-4678-4552-a2d1-be4fc8edf059)

Vulkan: 
![dxvk](https://github.com/doitsujin/dxvk/assets/135334701/7349eeaf-98d0-475d-b9a1-18bac8c609ad)

### Apitrace file(s)

https://mega.nz/file/lng11TAS#QubfhxZ_dLe-OySxkdZWX82zIXIyjpSCXOzqGMxl6dU

### Log files

[TestDrive2_d3d9.log](https://github.com/doitsujin/dxvk/files/11636100/TestDrive2_d3d9.log)

**Comment by K0bin** [comment]
Thanks for the good bug report. The apitrace was very useful.

We've fixed the issue, have fun with the game.
