### ISSUE TITLE
batman arkham city texture error

### ISSUE THREAD

**Issue by Eignar17** [doitsujin/dxvk#347]
texture in high to quality at low

not correct texture load
in DXVK:
newly started the game:
![screenshot at 2018-05-05 15 10 36](https://user-images.githubusercontent.com/8561550/39667224-a1e5e60e-5076-11e8-8faf-a4337172e480.png)

after loading it completely
![screenshot at 2018-05-05 14 01 13](https://user-images.githubusercontent.com/8561550/39666939-9699466a-5071-11e8-96af-2b7549987339.png)
![screenshot at 2018-05-05 14 01 30](https://user-images.githubusercontent.com/8561550/39666950-bf9536dc-5071-11e8-9b79-ea02f9168690.png)

in wined3d:
![screenshot at 2018-05-05 14 08 36](https://user-images.githubusercontent.com/8561550/39666959-e0dc0b18-5071-11e8-8769-123e145a8fb3.png)
![screenshot at 2018-05-05 14 08 57](https://user-images.githubusercontent.com/8561550/39666961-f95595a6-5071-11e8-9dae-ab8737515e09.png)

### Software information
batman arkham city,DX11

### System information
- GPU:NVIDIA GeForce GTX 1050
- Driver:396.18.07
- Wine version: Wine-staging-3.7
- DXVK version: f4a92a6

### Apitrace file(s)
-not work 

### Log files
- d3d11.log:[BatmanAC_d3d11.log](https://github.com/doitsujin/dxvk/files/1977009/BatmanAC_d3d11.log)
- dxgi.log: [BatmanAC_dxgi.log](https://github.com/doitsujin/dxvk/files/1977010/BatmanAC_dxgi.log)

**Comment by doitsujin** [comment]
No apitrace, can't debug.

**Comment by K0bin** [comment]
Here's a [trace](https://mega.nz/#!0fICUT6A!f_PPRfqTzwFH-GzGEUbo0xzMW9tZGIfFCpYQP_98790).

**Comment by Eignar17** [comment]
@doitsujin is apitrace to @K0bin

**Comment by Eignar17** [comment]
@K0bin is your video card nvidia or amd?

**Comment by doitsujin** [comment]
One thing that comes to mind, is this game based on some sort of Unreal Engine 3?

Bioshock Infinite also has a bit of a problem when it comes to textures and messing around with the configuration files fixes it for that game. There seems to be an issue with VRAM detection in UE3, but I'm not sure what's wrong there.

**Comment by K0bin** [comment]
I'll try and test some config tweaks later today.

**Comment by K0bin** [comment]
I tried some kind of tweak I found for Bioshock Infinite and some kind of Arkham City tweak tool that changes the texture streaming.

Both don't really change anything. I couldn't really find anything about broken textures on Google.

**Comment by K0bin** [comment]
Works in 0.65.

![image](https://user-images.githubusercontent.com/1131720/44125929-810f3214-a035-11e8-9e3b-035de49ec202.png)

**Comment by 4ymen** [comment]
Yes, fixed with latest master for Arkham Knight too
![batman arkham knight screenshot 2018 08 15 - 02 54 04 29](https://user-images.githubusercontent.com/37885401/44126273-968afb1c-a037-11e8-9a31-ed69b00adeea.png)
