### ISSUE TITLE
[d3d9] THE KING OF FIGHTERS XIII: STEAM EDITION: Missing Graphics

### ISSUE THREAD

**Issue by waspennator** [doitsujin/dxvk#3472]
Was testing out this game on my steam deck when I noticed it had some weird graphical quirks going on that were also reported on the proton github page for this game (But didn't seem to be present when using proton 4.11-13) so I figured i'd hop on my windows laptop to test it out on there with DXVK and noticed these issues (Since testing it out on deck requires a command to skip the videos or else it crashes the game and dunno how to setup the commands to skip videos and make a log file)

DXVK:
![KOF DXVK 1](https://github.com/doitsujin/dxvk/assets/78768499/852c22f9-0e06-4fb0-b0c3-088f5f3d1c14)
![KOF DXVK 2](https://github.com/doitsujin/dxvk/assets/78768499/477987ea-3653-4614-9c84-20cac40e0790)

How it should look:
![KOF 1](https://github.com/doitsujin/dxvk/assets/78768499/f722364e-2f67-41d0-9851-51c5f9e21d4e)
![KOF 2](https://github.com/doitsujin/dxvk/assets/78768499/2fa53706-3524-46ef-b6aa-21d2e2b34b22)

### Software information
THE KING OF FIGHTERS XIII: STEAM EDITION

### System information
- GPU: AMD Van Gogh for Steam Deck, GTX 1650 for the Windows Laptop
- Driver: Mesa 22.2.0 for Steam Deck,   Nvidia 531.79 for Windows Laptop
- Wine version: 8.0 on Steam Deck
- DXVK version:  https://github.com/doitsujin/dxvk/actions/runs/5126995523, also tested on latest dev build available at time (Respect all PS input elements for registers)

### Apitrace file(s)
- https://www.mediafire.com/file/5u08nqdf4yndrik/kofxiii.zip/file
 Mediafire link since it's apparently too big for github.

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

[kofxiii_d3d9.log](https://github.com/doitsujin/dxvk/files/11641930/kofxiii_d3d9.log)

**Comment by WinterSnowfall** [comment]
Looks good here with my self-built 8b6cbda.

![KOFXIII](https://github.com/doitsujin/dxvk/assets/6306593/b8018865-5484-493d-a440-3eb694476eed)

**Comment by waspennator** [comment]
On Deck at least, the only launch command I used was the -v one cause the game would die trying to play the intro FMV after the logos. Was able to replicate the graphcial issue on there for all versions up to 4.11-13, though I couldn't test out 5.0-10 cause it would not launch on my deck.

On Windows if I run it normally it looks visually fine, albeit things are running faster cause the game doesn't have a framerate cap. But if I toss in DXVK, while it does run at a more normal framerate (I know why it was capped), but the visual issues happen, like it only renders like specific assets on one side and everything else is just not showing up. (If you jump over your opponent, you'll go invisible while your opponent shows up instead.)

**Comment by WinterSnowfall** [comment]
I have played a few matches and not noticed anything off. That being said PCGW does mention graphical issues on AMD cards with the game. Not sure if anyone on AMD has tested it up till now.

**Comment by K0bin** [comment]
The apitrace replays fine (mines a couple of apitrace bugs).

**Comment by Blisto91** [comment]
I can reproduce the issue. But only when i do a resolution change in the game, not out of the box without switching resolution after having started.

**Comment by WinterSnowfall** [comment]
We've talked about it on Discord, but for the sake of clarity I'll sum it up here as well: the bug is related to the game depending on proper device lost behavior (it calls TestCooperativeLevel() then attempts a device reset) and also the proper release of D3DPOOL_DEFAULT resources on device reset. I've captured two traces, [one with WineD3D](https://drive.google.com/file/d/1pkM1EoIQbLqdetj650-lcJcjkow_AU0-/view?usp=sharing) and [one with DXVK](https://drive.google.com/file/d/17E52n9FPnzpu-Sj1mj5g67qWiAkddWyp/view?usp=sharing) to highlight the differences (these can be seen even on the first 2 frames).

**Comment by K0bin** [comment]
To go a bit more into detail, it _seems_ like the game relies on D3D9 failing in Reset when there's any alive D3DPOOL_DEFAULT resources. 

That's just a theory for now.

**Comment by K0bin** [comment]
After a bunch of experimentation, we've basically confirmed that theory now.

**Comment by waspennator** [comment]
Can confirm on my end the graphics look fine now using the latest dev build, thanks.
