### ISSUE TITLE
Gta 4 not launching with new dxvk versions

### ISSUE THREAD

**Issue by HEKJJBVCG** [doitsujin/dxvk#3473]
Hey, so I tried to use dxvk 2.0, 2.1, 2.2 but none of them works with gta 4 when i launch the game nothing happens. I can see the game running in task manager but the game window just doesnt pop up on my screen, only dxvk 1.10.3  and older works for me but I would really like to use the new versions with the game. If anyone could help me it would mean alot thanks.

**Comment by Blisto91** [comment]
Post dxvk logs.
Likely means outdated driver or old GPU that doesn't get new features anymore in the drivers.

**Comment by HEKJJBVCG** [comment]
> Post dxvk logs. Likely means outdated driver or old GPU that doesn't get new features anymore in the drivers.

[GTAIV_dxgi.log](https://github.com/doitsujin/dxvk/files/11643033/GTAIV_dxgi.log)

is it this one dxgi.log?

**Comment by HEKJJBVCG** [comment]
> Post dxvk logs. Likely means outdated driver or old GPU that doesn't get new features anymore in the drivers.

[GTAIV_d3d9.log](https://github.com/doitsujin/dxvk/files/11643037/GTAIV_d3d9.log)

here is also d3d9.log

**Comment by HEKJJBVCG** [comment]
idk if its my driver tho, since the new dxvk versions work fine in mafia 2.

**Comment by Blisto91** [comment]
Log just ends early.
What is your GPU and driver version

**Comment by HEKJJBVCG** [comment]
> Log just ends early.
> What is your GPU and driver version

Gtx 1060 3gb, driver version 535.98 (latest)

**Comment by HEKJJBVCG** [comment]
The strange thing is, the new versions did work in gta 4 before but suddenly stopped working which idk why

**Comment by Blisto91** [comment]
I would either try to downgrade to the driver version before or delete cache.
If you have a .cache file next to exe try to remove that and also look up how to clear Nvidia driver cache. Just a shot in the dark.

**Comment by HEKJJBVCG** [comment]
> I would either try to downgrade to the driver version before or delete cache.
> If you have a .cache file next to exe try to remove that and also look up how to clear Nvidia driver cache. Just a shot in the dark.

Thanks, will try clearing the nvidia driver cache.

**Comment by HEKJJBVCG** [comment]
> I would either try to downgrade to the driver version before or delete cache.
> If you have a .cache file next to exe try to remove that and also look up how to clear Nvidia driver cache. Just a shot in the dark.

Did not work unfortunately, guess im gonna have to use the older dxvk versions.

**Comment by Blisto91** [comment]
Sorry not sure what the issue could be, there was quite alot of changes for dxvk 2.0 and the game in general works with dxvk, moreso with 2.2. 
Since you say it used to work i'm doubting it's dxvk itself.

**Comment by HEKJJBVCG** [comment]
> Sorry not sure what the issue could be, there was quite alot of changes for dxvk 2.0 and the game in general works with dxvk, moreso with 2.2. 
> Since you say it used to work i'm doubting it's dxvk itself.
> 
> If you haven't already i'd suggest taking a skim through the Windows section in the wiki <https://github.com/doitsujin/dxvk/wiki/Windows>

Thanks for the help anyway :)

**Comment by K0bin** [comment]
![20230603190749_1](https://github.com/doitsujin/dxvk/assets/1131720/95e38da7-b63e-4037-be38-d7ae28310bad)

Works for me. No idea why it doesn't work for you but it's almost certainly something out of our control anyway.

**Comment by HEKJJBVCG** [comment]
> ![20230603190749_1](https://user-images.githubusercontent.com/1131720/243116903-95e38da7-b63e-4037-be38-d7ae28310bad.jpg)
> 
> Works for me. No idea why it doesn't work for you but it's almost certainly something out of our control anyway.

damn yeah i honestly dont know why it doesnt work for me, its super strange.

**Comment by noniegamed** [comment]
delete dxvk's dxgi.dll, it may cause problems in newer versions. dxvk works without it.
