### ISSUE TITLE
The Sims 2 & DXVK2.2: wrong neighborhood texture size/tiling

### ISSUE THREAD

**Issue by Armi1P** [doitsujin/dxvk#3474]
On DXVK versions prior to 2.2, everything looked like on native D3D9, but on DXVK2.2, tiling for the neighborhood terrain texture is wrong, scaled to much smaller size, looking repetitive. 

D3D9/DXVK2.1: 
![2 1](https://github.com/doitsujin/dxvk/assets/10885794/95079c3c-e844-41c6-84c7-ba94a33b8440)
DXVK2.2: 
![2 2](https://github.com/doitsujin/dxvk/assets/10885794/5f238269-d5ec-47fe-8442-302db53c72d2)

### Software information
The Sims 2  Ultimate Collection

### System information
- GPU: AMD RX560
- Driver: 23.3.2
- Wine version: None, running on W11 22H2
- DXVK version: 2.2

### Apitrace file(s)
When I place the apitrace DLLs in the exe dir, the game freezes before showing the neighborhood. If I try `apitrace -m Sims2EP9.exe`, as mentioned in #3444, I get no trace file.

### Log files
DXVK's log: [Sims2EP9_d3d9.log](https://github.com/doitsujin/dxvk/files/11645120/Sims2EP9_d3d9.log)
Sims 2's config log: [ARMI1P-PC-config-log.txt](https://github.com/doitsujin/dxvk/files/11645135/ARMI1P-PC-config-log.txt)

**Comment by Joshua-Ashton** [comment]
Would you be able to bisect the issue?

**Comment by K0bin** [comment]
Bisected down to 80f7d2abd8cdedb48b82b9dd0bec0b605fd8410d.

**Comment by Armi1P** [comment]
Artifact from [K0bin:sims2-fix](https://github.com/K0bin/dxvk/tree/sims2-fix) works. Thank you!
