### ISSUE TITLE
[d3d11] Black surfaces in Watch Dogs (and Bad Blood) with DXVK 2.0 and newer. Is my GPU too old?

### ISSUE THREAD

**Issue by ozz-is-here** [doitsujin/dxvk#3478]
### Software information
Name of the game, settings used etc.

* Watch Dogs, any settings. Tested EGS version and retail version.
* Fedora 38, `Linux desktop 6.3.5-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 30 15:44:17 UTC 2023 x86_64 GNU/Linux`
* KDE Plasma 5.27.5, Wayland

### System information
- GPU: Radeon RX 460 [https://www.techpowerup.com/gpu-specs/asus-rog-strix-rx-460-gaming.b3758](ASUS ROG STRIX RX 460 GAMING)
- Driver: RADV 23.1.1
- Wine version: [https://copr.fedorainfracloud.org/coprs/patrickl/wine-tkg-testing/](8.8 TkG) (but actually this happens in older versions too)
- DXVK version: 2.2 (from the releases page)

### Apitrace file(s)
I can't even run the game with Apitrace (see the attached log below), the trace file is empty.

### Log files
[glxinfo.txt](https://github.com/doitsujin/dxvk/files/11649164/glxinfo.txt)
[game.log](https://github.com/doitsujin/dxvk/files/11649165/game.log)
[dnf info mesa-vulkan-drivers.txt](https://github.com/doitsujin/dxvk/files/11649166/dnf.info.mesa-vulkan-drivers.txt)

### Screenshots
![watch_dogs](https://github.com/doitsujin/dxvk/assets/53562626/a5768733-c318-412d-9c20-7d1cd41e592d)
![bad_blood](https://github.com/doitsujin/dxvk/assets/53562626/b0548035-a984-461b-a336-05e12612d58a)

**Comment by Blisto91** [comment]
Your gpu should be fine. 
I have had trouble even getting this game to run with Steam Proton so haven't been able to test on Linux yet with my 7900xtx. But i did test a bit on Windows with dxvk where i didn't see anything immediately off.

**Comment by doitsujin** [comment]
What settings are being used?

Last time I tested the game was with 2.1 or something and it was fine there, if it's broken for you with that version then there's probably some Polaris-specific driver jank going on.

**Comment by ozz-is-here** [comment]
>What settings are being used?
This happened on any settings. However, I tested it in Lutris with lutris-GE-Proton8-4 a couple of days ago, and it was fine. I don't know why, but this used to happen even in Lutris three months ago. Now lutris-GE-Proton8-4 works fine. Maybe the problem is related to Wine, not to DXVK.

**Comment by doitsujin** [comment]
Yeah, just tested myself with my existing Ubisoft Connect prefix (which happens to be on the same Lutris wine build that you mentioned) and it runs fine, probably not our issue.
