### ISSUE TITLE
Fallout 4 freezes during game save loading screen

### ISSUE THREAD

**Issue by DrewJaworskiRIS** [doitsujin/dxvk#348]
The game freezes (all graphics cease, background music continues until buffer runs out) a few seconds after starting the save loading screen (with the rotating model and tips/etc); alt-tab works and Fallout4.exe can be killed to start again. Switching the two DXVK libraries to builtin in winecfg makes the problem go away (saved games load just fine, performance is lower). The problem does not seem to coorelate with any particular settings or save locations; a few weeks ago it seemed to only happen when loading saves where I was in combat or inside buildings (I was too lazy to report it, sorry!), but now it happens with any save.

With builtin libraries, the same point in time has a 0.5s-1s freeze, but then it starts back up and continues loading. That might be related?

### Software information
Fallout 4 (Steam)
all possible graphics settings attempted, no difference

### System information
- GPU: GeForce GTX 1050 (2MB)
- Driver: 396.24.0
- Vulkan: 1.1.70
- Wine version: 3.6
- DXVK version: https://github.com/doitsujin/dxvk/commit/f4a92a685f8b2f135dc6fe493ea9ce726aa79a52

### Log files
[Fallout4_d3d11.log](https://github.com/doitsujin/dxvk/files/1977164/Fallout4_d3d11.log)
[Fallout4_dxgi.log](https://github.com/doitsujin/dxvk/files/1977165/Fallout4_dxgi.log)

**Comment by sdack** [comment]
Hey there, sounds like the game might be compiling shaders in those 0.5s-1.0s and if so this could mean there are still problems with the new shader compiler. You could try the latest Vulkan driver 396.18.07, see here: https://developer.nvidia.com/vulkan-driver

Or try setting the variable __GL_NextGenCompiler=0 to turn off the new compiler.

**Comment by jarrard** [comment]
Are you running mods?

Also is this the survival mode sleeping at bed saving your talking about or when you move inside a building and it loads a area and saves?

**Comment by DrewJaworskiRIS** [comment]
I am not running any mods, and I am not in survival mode. This is only during the loading screen (where it shows some random game model spinning and has a loading icon in the corner) that shows when I try to load my saved game from the main menu.

**Comment by jarrard** [comment]
Ok, I have not played it enough maybe to encounter this issue. I played up to where preston is and maybe loaded a couple times.

**Comment by doitsujin** [comment]
Can you share a save that doesn't load? I cannot reproduce this issue.

**Comment by DrewJaworskiRIS** [comment]
I started a new game to try this out, and never had any problems (was expecting it to freeze when I left Vault 111, but it kept running just fine). I then loaded my previous saves and it all works just fine. I am confused, but expecting it to start failing again eventually... We'll see!

**Comment by jarrard** [comment]
I have started to get this issue when loading a game. So I don't think its been resolved. 

Also there is a texture issue on specific textures in the game.

**Comment by doitsujin** [comment]
Reopening because apparently this issue still exists.

Since my first request got ignored:

> Can you share a save that doesn't load? I cannot reproduce this issue.

**Comment by jarrard** [comment]
Here is a save file & a image of the missing textures. Its obvious when looking across from the crashed veribird on the building you meet preston on. 

Save file is just after I killed the deathclaw. You can create a quitsave file by exiting game to desktop, if it crashes at this point it will screenfreeze and possibly corrupt that save.

[Quicksave0_EADE4B8EM4A617272617264_Commonwealth_000107_20180510095052_3_2.fos.zip](https://github.com/doitsujin/dxvk/files/1991449/Quicksave0_EADE4B8EM4A617272617264_Commonwealth_000107_20180510095052_3_2.fos.zip)

![fallout4blend](https://user-images.githubusercontent.com/17428910/39867599-c479aaee-5494-11e8-8b1a-d0477c7e364c.jpg)

**Comment by jarrard** [comment]
Here is a interior exit to outside save file that works without a issue. For reference, it's before killing the deathclaw and on top of the building which you can spot the texture issues from.

[Exitsave0_EADE4B8E_4A617272617264_ConcordMuseum01_000059_20180510062722_3_2.fos.zip](https://github.com/doitsujin/dxvk/files/1991465/Exitsave0_EADE4B8E_4A617272617264_ConcordMuseum01_000059_20180510062722_3_2.fos.zip)

**Comment by frostworx** [comment]
I had a crashing savegame almost at the same position (saved after having killed the raiders in front of the building before entering it for the first time) some weeks ago. afair it was night in game too.
restarted from scratch as it is almost at the beginning and I'm playing without any major issues since then
(I'm somewhere near level 30 atm, so it works fine).

**Comment by DrewJaworskiRIS** [comment]
Like I mentioned before, and the reason I closed this issue; the problem was completely resolved by starting a new game. After that I was able to load my old game without it freezing while loading and have been playing a lot without problems since!

**Comment by frostworx** [comment]
the bug was reopened so it might be good to know that it tends to crash in that location in general

**Comment by sdack** [comment]
You should try to to compare it to DX11 over OpenGL when you think you have found a location to verify your findings.

**Comment by jarrard** [comment]
Yes I will be doing that. I can also boot into windows and do a trace via that method. At least then it will be a clear trace without any wine related issues piled on top.

**Comment by frostworx** [comment]
@jarrard yes, I've seen that texture on several buildings (afair always only on big ones like factories).

**Comment by jarrard** [comment]
You mean you've seen it but it wasn't messed up or it looks like my screenshot which shows what I suspect is broken alpha blending.

**Comment by frostworx** [comment]
nope, same broken alpha blending. looks almost like in your scrot, but more "glowing orange" usually.

**Comment by jarrard** [comment]
Ok cool, I also spotted some broken alpha blending on the generates at the starting intro vault where the roaches get zapped. 

There is also a alpha blend issue of some kind on the NPC and character eyelids, its most obvious when you observe it through fog or glass.

**Comment by jarrard** [comment]
Started a whole new game, everything fine until I get to concord and about a hr into the game. Basically did same thing I did last time, went and helped preston (this time I just went via rooftop to the armor and then inside from top of building). I noticed that my saves after about 1hr point were not working even if I was inside, I don't think it's directly related to facing the deathclaw or anything.

And yes I started a new game, then tried to load a save from the new game, didn't work, saves were still not loading from a certain point (typically after 1hr or so they just don't work for me).

Have you guys tried my corrupted saves above? can you get them to load?

**Comment by jarrard** [comment]
Tried to apitrace fallout4 under windows, even after disabling the launcher it just quits out without a trace. No idea what's wrong.

apitrace trace -a dxgi "D:\SteamLibrary\steamapps\common\Fallout 4\Fallout4.exe"

I also tried to do the steamapp launch method but it does not work due to x86 and no dxgi bug nonsense.

**Comment by jarrard** [comment]
I think I know what's going on here, fallout4.exe is offloaded to another exe which tricks apitrace into thinking its closed.

Also I would like to confirm the fault save files WORK under windows and NOT under Linux. The mystery deepens!

**Comment by jarrard** [comment]
If you do,
set SteamAppID=377160, then
apitrace trace -a dxgi "x:\SteamLibrary\steamapps\common\Fallout 4\Fallout4.exe"

It will produce this trace file, however it does not load into the game. 
This is probably not useful as we want a trace file with the process of loading one of those non functional save files (which work under windows)

[Fallout4.zip](https://github.com/doitsujin/dxvk/files/1997317/Fallout4.zip)

**Comment by jarrard** [comment]
OK so normal wine fallout4 with build in dll's (non dxvk) works thought fps is terrible but it loads the save games just fine. I created a trace file but have no idea where on the disk drive it is.

**Comment by darkskyabove** [comment]
Here is where I am at solving this. (Note: I recently switched from a minimalist Arch/Openbox/ALSA to Arch/Budgie/Pulseaudio. I use [dxvk-bin](https://aur.archlinux.org/packages/dxvk-bin/) from the AUR)

1. Seems to be audio-related. Bad saves came by saving after audio events which killed audio. Saves made indoors w/o audio issues would not load: suspect inability to load all the indoor audio.
2. Default Pulseaudio is usually adequate for most use cases but fails at high demand (real-time, as required by Ardour).
3. I set Pulseaudio to have real-time priority (well, at least as good as I had for running Ardour) by adding to my existing file /etc/security/limits.d/99-audio.conf:
```
@audio - rtprio 70
@audio - memlock unlimited
@pulse-rt - rtprio 70
@pulse-rt - nice -11
```
Yesterday, w/Wine-Staging 3.7 + DXVK 0.50, I was able to play for a few hours without any audio freezes and all saves reloaded fine. Today, w/Wine-Staging 3.8 + DXVK 0.51, same good result; if anything, framerate appears a bit more stable.

My specific fix won't work for everyone (there are similar fixes for different systems). Hopefully, this helps.

**Comment by doitsujin** [comment]
@jarrard I was able to reproduce this issue with one of your saves. It's a game bug, 26b319b29bdf8fa65b57cde93981beda5a0c78f9 implements a workaround for this issue.

Make sure that the name of your game exe is `Fallout4.exe` (dxvk is case sensitive at the moment).

**Comment by jarrard** [comment]
Nice, I will test that out this evening.

**Comment by jarrard** [comment]
Appears this bug still exists.

**Comment by DrewJaworskiRIS** [comment]
I have been playing without any loading problems since the fix. However, and I'm too lazy to report it, there are instances of major graphics glitches; I can't determine the correlating aspect of it, but sometimes random polys fill the screen with (usually dark red) textures. They seem to emanate from specific places on the screen, but when I move around I can't seem to tie them to anything particular. Just some random spot or area of a building wall or something.

**Comment by jarrard** [comment]
With mods the game takes 60sec or more to load, this is normal and related to esp/esm parsing or something.

There are also semi-freezes with certain scenes and loading, but game recovers. Could be shader compiling related.

I'll test some more today, hopefully my saves still work, went to concord, killed stuff, returned to red rocket+, see how it goes.

**Comment by ccl2of4** [comment]
@DrewJaworskiRIS I'm pretty sure the nvidia vulkan beta driver fixes that issue
