### ISSUE TITLE
Titanfall 2, Apex massive framerate drop with specific VFX

### ISSUE THREAD

**Issue by rurigk** [doitsujin/dxvk#3481]
Please describe your issue as accurately as possible.
Some VFX makes the games to have a massive framerate drop
This issue has been happening to me for a very long time, it first i was thinking that it was just Apex Legends but i noticed that specific VFX makes Titanfall 2 have this issue as well

Why i make an issue with 2 games?
Because Titanfall 2 and Apex games share game engine (i know apex uses more updated engine)
And i think the VFX that make games drop framerate share common traits

How to reproduce:
Framerate drop is more noticeable with 1440p or 4k

In Apex Legends throw from 1 to 3 thermites and look from close distance, this happens as well with Holosprites, some HUD effects are affected as well and are the worst, like healing zones from special events (not available for the moment)

Other VFX which are much more bigger and take a lot more of screen space are not affected

In Titanfall 2 inside a Titan make enemy Monarch Titan hit you with "Energy Siphon", inside a Titan make enemy Scorch Titan hit you with "Flame Core"

This issue happens for me with both DXVK and vkd3d-proton and i'm not sure if it is something to do with mesa

### Software information
Titanfall 2 and Apex Legends 
Tested on low and high settings
Resolutions tested: 1080p, 1440p, 4k

### System information
- Distro: Arch Linux
- GPU: RX 6700 XT, RX 570
- Driver: mesa 23.1.1-1, vulkan-radeon 23.1.1-1 (no amdvlk installed)
- Wine version: I'm using proton experimental but this issue affects multiple older versions (tested on 6.3 and newer)
- DXVK version: The one included with proton (current proton experimental)

I'm gonna try to upload the apitrace of Titanfall 2 as soon as one of my friends help me to replicate the issue

**Comment by doitsujin** [comment]
> In Apex Legends throw from 1 to 3 thermites and look from close distance, this happens as well with Holosprites, some HUD effects are affected as well and are the worst, like healing zones from special events (not available for the moment)

I have roughly no idea what any of these words mean. Can you show a picture? Do we even have solid proof that the same performance drop does not occur on Windows in the same situations?

It's fairly normal for transparency-heavy effects to tank performance especially if they cover large portions of the screen, but that's not really a DXVK problem, that's just a general graphics problem. Not sure if that descriptions apply though.

**Comment by Blisto91** [comment]
@rurigk Friendly ping

**Comment by rurigk** [comment]
I was unable to test this because i had no time
I recently got a steam deck so i'm gonna be able to test this by myself

I didn't forget, just had no time in this months

**Comment by rurigk** [comment]
I'm now unable to test this since i cant launch the game
EA App always tell me "Failed To Launch, An Error On Our End Caused Your Launch To Fail" on every EA Launcher game

I'm trying to fix that before i can test this

**Comment by amenokagaseo** [comment]
I'm experiencing this as well, makes Titanfall 2 basically unplayable with more than one enemy Monarch and makes Frontier Defense completely unplayable on higher difficulties.

It seems to be tied to some kind of glitch effect on Titan's "screen" that only happens if you get hit with arc (from Ronin's Arc Wave, Monarch's Energy Siphon, Arc Grenades, or an Arc Titan's field in FD) or get Flame Cored. Also seems to be a hardware bug of some kind since I've seen multiple topics about it on Windows with AMD cards.

**Comment by rurigk** [comment]
@amenokagaseo it seems that this is the case

I think the game "reads/writes" the rendered frame to a "texture" and then compose the glitch effect using that "texture" in postprocessing 

I'm not sure if it's a AMD hardware issue or a driver issue but at this point I think it's not a DXVK issue

It may be possible to make a workaround but I think it may not be the correct way to do fix the issue

**Comment by ishitatsuyuki** [comment]
What’s your texture filtering settings? If you are on aniso settings, does it improve if you set it to bilinear?

**Comment by Blisto91** [comment]
Doing some quick comparisons in Apex Legends of native Windows vs Linux dxvk + radv the fps seems about the same.
This is with a RX 6800 at 1080p highest settings (no supersampling).

<details>
  <summary>Native d3d11</summary>

![image](https://github.com/doitsujin/dxvk/assets/47954800/1193c65b-41c4-4896-bfc3-b4d26d19744b)
![image](https://github.com/doitsujin/dxvk/assets/47954800/6ce17131-75f6-4abc-8b7c-d18b8aea289a)
![image](https://github.com/doitsujin/dxvk/assets/47954800/a555f8f9-6f9d-4d92-92bf-1962f3b33041)
</details>

<details>
  <summary>Linux dxvk radv</summary>

![Screenshot_20231229_184433](https://github.com/doitsujin/dxvk/assets/47954800/cbcf06fe-3b5d-4a93-8c25-a8c03db24332)
![Screenshot_20231229_184447](https://github.com/doitsujin/dxvk/assets/47954800/b1ddbf07-9926-4344-ba68-8a9952c6ac45)
![Screenshot_20231229_184515](https://github.com/doitsujin/dxvk/assets/47954800/b77cb0e2-6455-4771-8ac2-b711b08f12eb)
</details>

<details>
  <summary>Same but with dxvk hud</summary>

![Screenshot_20231229_184759](https://github.com/doitsujin/dxvk/assets/47954800/5b43b25f-a866-499a-8a62-2f8dec82b4d4)
![Screenshot_20231229_184813](https://github.com/doitsujin/dxvk/assets/47954800/bcfbf1e7-c93b-4296-b756-6807268ba14a)
![Screenshot_20231229_184850](https://github.com/doitsujin/dxvk/assets/47954800/199b2fc9-6f72-4dc2-ba22-d632299f4216)
</details>


The game does not want to cooperate with apitrace so far so instead made a renderdoc capture.
Made on a RX 6800 with radv 23.3.1
https://drive.proton.me/urls/CVG0Z0T8KM#Z4RJKDmAfe1F

**Comment by p0358** [comment]
For posterity I will also mention that in Titanfall 1 **on Windows**, the arc effect was also said to be problematic in the same way (some people reported the fps drops to be insufferable, I personally never noticed them much). So it definitely doesn't sounds like it stems from DXVK and probably isn't fixable without some game modding...
