### ISSUE TITLE
DXVK HUD applies to the EVE Online launcher rather than the game

### ISSUE THREAD

**Issue by foundObjects** [doitsujin/dxvk#3483]
When launching EVE from flatpak Steam with DXVK_HUD=1 the hud is applied to the launcher process but not the subsequent game clients that the launcher spawns. See screenshot below for details.

Is there some way to exclude `evelauncher.exe` from HUD hooking and instead hook the `exefile.exe` game clients?

### Software information
EVE Online via flatpak Steam, any settings

### System information
ryzen 6000 series integrated GPU + nvidia 3060
nvidia-dkms 520.56.06 - all versions affected, I've also tested 530.xx and 535.xx
whatever Wine+DXVK ship with Proton-GE 8.4

![eve launcher bug](https://github.com/doitsujin/dxvk/assets/28817345/812ed2ae-fd75-4d2d-8e46-79c5fe30eda8)

**Comment by Blisto91** [comment]
It should still show ingame as it should apply to each window that uses dxvk. You aren't using the DirectX 12 in the game itself?

**Comment by WinterSnowfall** [comment]
I believe the game is currently using d3d12 FL11_0, whereas the launcher may still be using d3d9 (or d3d11). Which explains the behavior above.

**Comment by K0bin** [comment]
The HUD is applied to everything that renders with DXVK.

Like the others here have already said, the game itself is likely using D3D12.

**Comment by foundObjects** [comment]
Ah, thanks. I double checked and you're absolutely right, the game is using DX12.

**Comment by Blisto91** [comment]
There have been requests for a similar debug hud for vkd3d-proton, but it isn't a thing at the moment.
