### ISSUE TITLE
Bug in Conflict: Vietnam

### ISSUE THREAD

**Issue by HQSantosilva** [doitsujin/dxvk#3485]
I've tried to use the software in this game to check if it can solve the shaking camera problem this game has with directx 11. It worked fine, but every time you try to walk uphill or down through a slope, the character gets stuck in the air, or simply can't move
![bug](https://github.com/doitsujin/dxvk/assets/110571779/bb2947a0-c78c-4ee1-a164-dad3090ec7a0)

**Comment by Blisto91** [comment]
> directx 11.

The game looks to be DirectX 9 looking at gaming wiki?

We would really like some additional info as this isnt alot.
I'm guessing this doesn't without dxvk? Is the fps unlocked or locked?

**Comment by K0bin** [comment]
> the character gets stuck in the air, or simply can't move

That's almost certainly not a DXVK bug. DXVK has nothing to do with game physics or movement.

**Comment by HQSantosilva** [comment]
> > directx 11.
> 
> The game looks to be DirectX 9 looking at gaming wiki?
> 
> We would really like some additional info as this isnt alot. Usually as a minimum also include dxvk logs. I'm guessing this doesn't happen without dxvk? Is the fps unlocked or locked?

The installer had a directx9 file with it, so its like the old cd installation games

**Comment by HQSantosilva** [comment]
> 



> > the character gets stuck in the air, or simply can't move
> 
> That's almost certainly not a DXVK bug. DXVK has nothing to do with game physics or movement.

It's wierd because this bug only happened when i tried to run with DXVK, i played the game for a while and it never happened before.

**Comment by Blisto91** [comment]
The physics can bug out at high fps.
