### ISSUE TITLE
How to setup on windows?

### ISSUE THREAD

**Issue by tonibm19** [doitsujin/dxvk#349]
It would be awesome if a windows tutorial was added. I know DXVK is compilable in windows and some people have even got it to run. 
I would love to try it, but I don't know what to do with the dll .

**Comment by doitsujin** [comment]
Copy DLLs to the directory where the game's executables are, done.

Note that some games refuse to load DXVK, but there's nothing we can do about it.

**Comment by grappas** [comment]
@doitsujin I've tried putting dxvk files to folder with Arma 3. I've had an "entrypoint not found" error related to DXGID3D10GetLayeredDeviceSize function in d3d10core.dll library. What would've caused that?

**Comment by doitsujin** [comment]
No idea, DXVK doesn't implement or touch any of those D3D10 functions.

**Comment by grappas** [comment]
@doitsujin Arma 3 is working preety good: https://www.youtube.com/watch?v=pwD4fvB4eZw

**Comment by lieff** [comment]
@grappas You can try also https://github.com/Joshua-Ashton/dxup among with dxvk.

**Comment by grappas** [comment]
@lieff Already tried that. Not instantly crashes but still dead end. I'm wondering: why on Wine with pure dxvk Arma 3 works like a charm and on Windows 10 do not.

**Comment by grappas** [comment]
@doitsujin Is there anything to do in regedit to make it work on Windows?

**Comment by doitsujin** [comment]
I don't use Windows, sorry.

**Comment by grappas** [comment]
@doitsujin It seems to search for Wine version of this library and finds unfortunately an original one.

**Comment by grappas** [comment]
Solved: https://www.reddit.com/r/arma/comments/8pnnwc/arma_3_performance_tweak_with_rdxvk_and_rdxup/

**Comment by CloudHaze** [comment]
I know this post is from 2018, but I was wondering how to install this Dxvk for old games such torchlight II
I downwloaded the last version 1.7 but there is not .dll files inside? :O

Sorry for being that noob =(

**Comment by K0bin** [comment]
You have to open the .tar file. The dlls are in there.

**Comment by imicomputer** [comment]
I wanna try this with Fable The Anniversary, classic a DX9 game now on St#@m. Already put the Dlls in the same forlder of the FableAnniversary.exe file, how to tell if DXVK working or not? Because when I run it on window mode, title still say its a DX9.
