### ISSUE TITLE
Dxvk not working (on windows) after 1.10.3

### ISSUE THREAD

**Issue by Mzed3D** [doitsujin/dxvk#3495]
Hi! I know DXVK is intended to work with Wine but   it produces very good results also on Windows. Anyway I'm experiencing an issue in every game I try: it only works untill 1.10.3 version. Starting from 2.0 every game crashes, regardless of the directx version the game uses. Am I doing something wrong? Am I missing something?

**Comment by Blisto91** [comment]
Post a dxvk log

**Comment by K0bin** [comment]
Your graphics driver is probably too old. DXVK 2.0 requires a Vulkan 1.3 capable driver.

**Comment by Mzed3D** [comment]
Hi, the driver seems to be capable of Vulkan 1.3.215. Here you can find three logs, Alan Wake (Directx9), Skyrim (first version, Directx9) and Hellblade (Directx11).
[alanwake_d3d9.log](https://github.com/doitsujin/dxvk/files/11758013/alanwake_d3d9.log)
[TESV_d3d9.log](https://github.com/doitsujin/dxvk/files/11758014/TESV_d3d9.log)
[HellbladeGame-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/11758017/HellbladeGame-Win64-Shipping_d3d11.log)
[HellbladeGame-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/11758019/HellbladeGame-Win64-Shipping_dxgi.log)

**Comment by mbriar** [comment]
Still looks like an ancient intel windows driver, but even if it was up to date, most likely a driver issue and not fixable in DXVK.

**Comment by Mzed3D** [comment]
Is it possible to use Mesa drivers on Windows?

**Comment by Mzed3D** [comment]
But on the release notes of the driver I'm using is written that it's "conformant with the Vulkan 1.3 specification", so why isn't it working? The driver is the latest version (5th april 2023)

[https://downloadmirror.intel.com/776138/ReleaseNotes_101.2121_WHQL.pdf](url)

**Comment by Mzed3D** [comment]
Also, is there an updated build of the 1.10 branch?

**Comment by Blisto91** [comment]
> But on the release notes of the driver I'm using is written that it's "conformant with the Vulkan 1.3 specification", so why isn't it working? The driver is the latest version (5th april 2023)

I don't know, nothing stick out in the logs. A driver issue could still be likely or some other shenanigans going in (look through windows section of wiki, e.g. overlays and such). 2.0 was a big release that changed alot of stuff and now depend on some new Vulkan extensions.

> Also, is there an updated build of the 1.10 branch?

Not besides the 1.10.3 release and the commits in the 1.10.x branch https://github.com/doitsujin/dxvk/commits/1.10.x

**Comment by Mzed3D** [comment]
So, just yesterday Intel released new graphics drivers, but still the games crash with dxvk 2.0. Here are the logs, is there some new info compared to the old drivers?
[HellbladeGame-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/11776028/HellbladeGame-Win64-Shipping_dxgi.log)
[HellbladeGame-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/11776030/HellbladeGame-Win64-Shipping_d3d11.log)
[alanwake_d3d9.log](https://github.com/doitsujin/dxvk/files/11776032/alanwake_d3d9.log)
[TESV_d3d9.log](https://github.com/doitsujin/dxvk/files/11776035/TESV_d3d9.log)

**Comment by Iglu47** [comment]
@Mzed3D do you use any third-party software? e.g. MSI Afterburner + Rivatuner Statistics Server.
Perhaps such overlays may not be compatible with Vulkan 1.3 while older versions of DXVK will work fine.

**Comment by Mzed3D** [comment]
I have installed them but when I launched the games those softwares were not running. I only had the environment variable DXVK_HUD=full set in Windows.

**Comment by BiZkViT96** [comment]
I cannot reproduce the problem, here is Alan Wake log. There is differences in my log and log from OP, maybe GPU/driver is lacks needed instructions... anyway I hope devs will find something useful in it. DXVK 2.2, Windows 11, UHD 770, driver v4382.

[alanwake_d3d9.log](https://github.com/doitsujin/dxvk/files/11781323/alanwake_d3d9.log)

**Comment by Blisto91** [comment]
> I have installed them but when I launched the games those softwares were not running.

Try to remove them anyway as the wiki says and see if it helps

> Note: The RTSS overlay is implemented as a Vulkan layer, and gets loaded even if the application is not running. Recent RTSS versions should work with DXVK, but if not, the software may need to be uninstalled.


Also try to turn off Steam overlay.

**Comment by totyaxy** [comment]
Hi, confirmed, AMD 7850 / driver: 22.6.1 on Win10 x64

**Comment by Blisto91** [comment]
Yes the AMD 7850 doesn't have driver support for Vulkan 1.3 so it can only use dxvk 1.10.3 and below

**Comment by totyaxy** [comment]
> 

Thanks for the answer!
