### ISSUE TITLE
Grim Dawn - GOG - Latest version -  Game won't launch after nvidia driver update

### ISSUE THREAD

**Issue by man2too** [doitsujin/dxvk#3498]
I installed DXVK with winetricks and everything worked fine with nvidia-530.41.03-17.
After I updated nvidia and nvidia-utils I can't start the game.
How can I fix that? Or should I just downgrade to the older nvidia version?(If that''s the problem)

### Software information
Grim Dawn v1.1.9.8

### System information
- GPU: GTX 1050 TI
- Driver: nvidia-535.54.03-2
- Wine version: wine-8.10 (Staging)
- DXVK version: v2.2

### Log files
[game.log](https://github.com/doitsujin/dxvk/files/11762478/game.log)

**Comment by doitsujin** [comment]
Your driver install seems to be broken somehow:
```
010c:err:vulkan:wine_vk_instance_load_physical_devices Failed to enumerate physical devices, res=-3
010c:err:vulkan:wine_vkCreateInstance Failed to load physical devices, res=-3
```

**Comment by man2too** [comment]
I had a system update today, now it works fine idk.

**Comment by WinterSnowfall** [comment]
Note that you always need to reboot after you update your Nvidia drivers, otherwise any OpenGL/Vulkan application will fail to start.
