### ISSUE TITLE
How about a mac version?

### ISSUE THREAD

**Issue by jerkstore369** [doitsujin/dxvk#350]
I'm sick of scumbag devs ignoring the mac. Come on, man :p

**Comment by doitsujin** [comment]
> I'm sick of scumbag devs ignoring the mac.
You're not doing Mac users any favour with that kind of attitude.

Anyway, to all Mac users out there: Thank Apple for creating their own proprietary mess that makes it harder than necessary to support their platform. I realize that MoltenVK is a thing but it's not feature-complete enough yet to back a full D3D11 implementation.

**Comment by ssorgatem** [comment]
There's nothing Linux-specific to DXVK.

As long as you have a working Vulkan implementation and Wine supporting it, it will work.

OSX has neither. You should ask Apple or MoltenVK to get a complete-enough Vulkan implementation, then ask the Wine devs to support it.

And at that point , DXVK will just work on the Mac.
