### ISSUE TITLE
Blank Screen on Watch Dogs Legion using dxvk

### ISSUE THREAD

**Issue by Akami23** [doitsujin/dxvk#3503]
Im trying to use dxvk on this game but always get blank screen, in the log says that dxgi: createswapchainforhwnd: unsupported device type, but im applying on another game and its run flawlessly, whats wrong?
### Software information
Watch Dogs Legion

### System information
- GPU: Radeon Vega 3
- Driver: 23.3.5
- Wine version: 
- DXVK version: 2.2.0 and 1.0.3 

### Apitrace file(s)
- https://drive.google.com/file/d/1J5lTc-9goOM6DQhDWnrkHB62pquUa5Jl/view?usp=sharing
### Log files
- https://drive.google.com/file/d/1-bH7V6YIZgxgC9_RfxLlItOmd8qwWMzA/view?usp=sharing

**Comment by Akami23** [comment]
in windows platform

**Comment by mbriar** [comment]
This game uses D3D12 which dxvk doesn't support. There is vkd3d-proton that you can use for D3D12 -> vulkan in addition to the dxvk.dll from dxvk, but it's pretty much guaranteed to be slower and more broken on amd windows drivers.

**Comment by doitsujin** [comment]
D3D12 games don't work with a D3D11 implementation, big surprise.

**Comment by artemyto** [comment]
Watch Dogs: Legion has both D3D11 and D3D12 renderers. You can launch it with dx11 using -DX11 launch option

https://www.pcgamingwiki.com/wiki/Watch_Dogs:_Legion#Issues_fixed
