### ISSUE TITLE
Borderlands 2 strange stuttering

### ISSUE THREAD

**Issue by ignacioat2** [doitsujin/dxvk#3506]
Please describe your issue as accurately as possible.

I have been looking for optimizing guides for borderlands 2 because i have a laptop with pretty good specs and the fps drops were crazy in that game so thats why i installed dxvk butt an abnormal stuttering had appeared after putting the d3d9 and dgi files in the win 32 borderlands 2 folder i waited because maybe something was loading but after an hour the stutter didnt stop. Is there any way of fixing it or any step im missing?

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Name of the game, settings used etc.

### System information
- GPU:
- Driver:
- Wine version: 
- DXVK version: 

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

**Comment by K0bin** [comment]
You didn't provide any logs, information about your system or the apitrace.

What you're seeing is probably shader compilation but you've given us nothing to work with so guessing is the best we can do.

**Comment by ignacioat2** [comment]
And how do i fix that?

**Comment by Blisto91** [comment]
Don't use dxvk or get a driver that supports `VK_EXT_graphics_pipeline_library` which is only Nvidia at the moment afaik.
Even then some engines like UE4 might still stutter, but that is because the engine itself doesn't prepare shaders in advance by default.

**Comment by ignacioat2** [comment]
and where can i get those drivers and what do i need to do with them?

**Comment by mbriar** [comment]
The only driver that supports VK_EXT_graphics_pipeline_library on Windows is nvidia's, and it does so by default for a while now. If you have a GPU from a different vendor, there is nothing you can do on windows.

**Comment by Blisto91** [comment]
Yes if you are not using Nvidia all you can do is wait.

**Comment by ignacioat2** [comment]
im using nvidia and i still get the fps drops and dxvvk doesnt work

**Comment by Blisto91** [comment]
What do you mean it doesn't work and what is your driver version.

fwiw these unreal engine games are usually extra bad since alot of them don't load shaders up front which means they are first compiled when encountered ingame. I don't remember how Borderlands 2 behaves in that regards specifically.

**Comment by ignacioat2** [comment]
i have a 3060 like the laptop version and an i 7 and the last drivers available i use like dxvk and the stuttering stays there

**Comment by K0bin** [comment]
Make sure your drivers are up to date.

Aside from that, there's nothing we can do with the limited amount of information you've given us.

**Comment by mbriar** [comment]
> i use like dxvk and the stuttering stays there

Does that mean that the game stutter with DXVK in the same way it does without DXVK? In that case I don't see any issues here anyways, since DXVK's goal isn't really to fix or improve games.

**Comment by ignacioat2** [comment]
it stutters worse the fps is overall normal but it stutters a lot like the game doesnt run smoothly
