### ISSUE TITLE
Do I need to winetricks install `d3dx9_**.dll`

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [doitsujin/dxvk#3507]
Do I need to use `winetricks` to install d3xd9 libraries, or is this something that is already included in DXVK.

I get these errors (on 32-bit games):
```sh
err:module:import_dll Library d3dx9_31.dll ...
err:module:import_dll Library d3dx9_43.dll ...
```

**Comment by mbriar** [comment]
d3dx9 is not provided by dxvk, although wine should have build-in DLLs for those that work most of the time.

**Comment by Kallinteris-Andreas** [comment]
The DXVK README says it supports dx9 though

**Comment by Blisto91** [comment]
d3dx are seperate helper libraries. Either the Windows version (winetricks) or wine version (baring any bugs) should work fine with dxvk.

**Comment by Kallinteris-Andreas** [comment]
For people coming lookig here for a fix, simply put `d3dx9_XX.dll` in the game folder as the game directory
