### ISSUE TITLE
Regression in Counter Strike: Global Offensive

### ISSUE THREAD

**Issue by adamjer** [doitsujin/dxvk#3520]
There are corruptions visible
![image](https://github.com/doitsujin/dxvk/assets/26136487/05698b32-61e2-4573-9d94-fead4043968d)

Exact regression point
https://github.com/doitsujin/dxvk/commit/1850819483a1a5e061da18c8bfd615988af3b316

### Software information
Counter Strike Global Offensive

### System information
- GPU: NVidia RTX 2080
- Driver: 31.0.15.3203
- OS: Windows 10

- GPU: Intel(R) UHD Graphics
- Driver: latest
- OS: Windows 10

### Apitrace file(s)
Unfortunatelly I was not able to capture APItrace file, game crashes with apitrace attached.

**Comment by K0bin** [comment]
Do you happen to know the D3DPOOL of the problematic buffers?

**Comment by HunterCZ122** [comment]
[Apitrace](https://drive.google.com/file/d/1tEAgbEX65CzJtOQoYDYQgaP-TN4vk-YE/view?usp=sharing) (with DXVK)
To make apitrace you need to add -insecure to launch options otherwise CS:GO will crash.
Unfortunately I couldn't make apitrace with WineD3D because it gets stuck at loading screen for over 10min (and I really don't want to wait that long).

**Comment by adamjer** [comment]
I did exactly as you mentioned.
Added -insecure option in Steam app launch parameters and copied ApiTrace "d3d9.dll" into "..\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\bin" directory.
Game does not launch at all.

**Comment by WinterSnowfall** [comment]
Perhaps you are aware of this, but the Wine override for d3d9 when using apitrace should be set to "n,b", not simply "n", since it's a simple pass-through, and stuff will crash otherwise.

**Comment by Blisto91** [comment]
Not on Windows 😉

**Comment by adamjer** [comment]
Yes, exactly I tried it on Windows 10.
