### ISSUE TITLE
DXVK 1.10.3 not works with Dgvoodoo2 on windows

### ISSUE THREAD

**Issue by Aztec2012** [doitsujin/dxvk#3522]
DXVK 1.10.3 not works with Dgvoodoo2 on windows. Black window open and closes after few seconds.

**Comment by K0bin** [comment]
Please add logs, the game you're trying to run and information about your system.

**Comment by Blisto91** [comment]
If my memory don't completely fail me then i think dgvoodoo usually try to load something from the System directory which is why it doesn't work on Windows.
But yes a log should show that

**Comment by K0bin** [comment]
https://github.com/doitsujin/dxvk/issues/1707#issuecomment-1186163469

Same problem as in your other issue.

**Comment by Aztec2012** [comment]
Hitman Codename 47 here is a log
[hitman_dxgi.log](https://github.com/doitsujin/dxvk/files/11801849/hitman_dxgi.log)

**Comment by Blisto91** [comment]
Nothing sticks out in the log.

I quickly tried Hitman Codename 47 on Windows with dgvoodoo2 plus dxvk and it indeed didn't work.
I then tried the same on Linux with both the community Vulkan driver and AMD's own and it worked both times. I don't think there is anything for dxvk to do here.
