### ISSUE TITLE
Supporting by Turnip Freedreno

### ISSUE THREAD

**Issue by Ilya114** [doitsujin/dxvk#3523]
Hi, can you add info in Wiki that Mesa (latest stable release, 23.1.2) Turnip Freedreno (Open-source drivers for Qualcomm Adreno GPU's) supporting? It working fine with [Box64](https://github.com/ptitSeb/box64), [Box86](https://github.com/ptitSeb/box86) + Wine

<details>

![photo_2023-06-20_18-46-57](https://github.com/doitsujin/dxvk/assets/93242944/c2455184-6d2b-4954-9fb1-c80425b55a0f)
</details>

**Comment by K0bin** [comment]
Android is not a supported platform and Linux on Qualcomm based laptops is exceedingly rare.

**Comment by Ilya114** [comment]
But here using same Turnip drivers as in another Linux systems

**Comment by doitsujin** [comment]
There's a difference between it *working fine* and *actually being supported*. It might work just fine for *some* games (probably not all, especially D3D11, but who knows), but that doesn't mean we're committing any resources to testing it, or specifically cater to it.
