### ISSUE TITLE
VK_EXT_transform_feedback dont appear avalaible on intel anv

### ISSUE THREAD

**Issue by mrdeathjr28** [doitsujin/dxvk#3526]
VK_EXT_transform_feedback dont appear avalaible on intel anv

### System information
- GPU: Intel UHD 630 CFL GT2
- Driver: Oibaf Mesa
- Wine version:  8.9 Staging
- DXVK version:  Git

![anvtffdb](https://github.com/doitsujin/dxvk/assets/6601480/d6973b4b-6877-4f49-8ac2-61c0130fe95d)

gpuinfo native show hardware support

![tffbc](https://github.com/doitsujin/dxvk/assets/6601480/b0e16582-3277-494b-9640-f73fdc8f6a44)

gpuinfo using wine show hardware support too

![tffbwn](https://github.com/doitsujin/dxvk/assets/6601480/89b1f32d-5848-4db4-a8f5-e8ce13c58172)

**Comment by K0bin** [comment]
Call of Juarez: Bound in Blood is a D3D9 game. D3D9 does not support transform feedback so we also don't enable the Vulkan feature.

**Comment by K0bin** [comment]
D3D10 and 11.
