### ISSUE TITLE
[d3d9] Drakensang: The Dark Eye - the intro video doesn't play

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#3528]
It works fine with WineD3D.

The game seems to request the following while playing the intro:

```
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1280
info:      - Height:             720
info:      - Format:             D3D9Format::Unknown
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::Unknown
info:      - Windowed:           true
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1280x720
info:    Image count:  2
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  1280x720
info:    Image count:  3
info:    Exclusive FS: 0
```

But the screen doesn't appear to resize down from 1080p (the resize is quite visible with WineD3D as it happens right on the first frame of the intro video).

### Software information
Drakensang: The Dark Eye (GOG)

### System information
- GPU: Nvidia RTX 3060
- Driver: 530.41.03
- Wine version: 8.10 Staging
- DXVK version: 80b27f9

### Apitrace file(s)
[drakensang.trace.tar.xz](https://drive.google.com/file/d/1zb5acvBoZZ1KL_NurxdcTiXCfG9JPbPR/view?usp=sharing)

### Log files
[drakensang.log](https://github.com/doitsujin/dxvk/files/11838031/drakensang.log)

**Comment by K0bin** [comment]
Replaying it with DXVK on Windows:
![image](https://github.com/doitsujin/dxvk/assets/1131720/c261d3f1-b08c-4b9b-bf03-8fc140c4b60f)

Replaying it with Windows D3D9 (apitrace has issues with strides):
![image](https://github.com/doitsujin/dxvk/assets/1131720/7c75aa99-b1c6-458b-ab80-d82446b99d98)

This is probably an issue with the multi swapchain workaround in WineVulkan.

**Comment by WinterSnowfall** [comment]
> This is probably an issue with the multi swapchain workaround in WineVulkan.

What exactly does that workaround do? Only present on the first created swapchain or something of the sort?
