### ISSUE TITLE
How to install v2.2?

### ISSUE THREAD

**Issue by z0rti** [doitsujin/dxvk#3538]
I'm using wine (8.10) manually on ubuntu.
I got a (working) wineprefix in ~/games/
Where do i put the *.dll files? just "cp *.dll ~/games/drive_c/windows/system/"?

**Comment by Blisto91** [comment]
There is a small guide in the readme if it's able to provide enough info https://github.com/doitsujin/dxvk#how-to-use
For the first line you'd then just modify it to point at your prefix.
