### ISSUE TITLE
Ghost Recon: Wildlands - Deadlocks when you interact with a specific type of phone

### ISSUE THREAD

**Issue by gabriele2000** [doitsujin/dxvk#3540]
A little context.
In this game, you gather piece of intel in various ways.
In the "Fallen Ghosts" DLC, there's a mission (an early one too) that asks you to find intel of the enemy.

Now, remember the intel thing?
The types are:
- you pull out your phone, you take a photo of a map
- you pull out your phone, you take a photo of documents
- **you pick this phone laying on a table, you pull out your phone and you "transfer stuff" to your phone**
There's an animation on the guest phone's screen, the second animation should be your phone's screen that lights up and kinda mimic the animation of the other phone, think of the "file transfer" thing in the first Avatar movie.

This last animation is responsible and looking at the log it's something about DX11 shaders, I don't know.

### Software information
Ghost Recon: Wildlands, DX11, mixed settings, they don't matter.

### System information
- GPU: Nvidia GTX1050TI 4GB
- Driver: 535.54.03
- Wine version: 7.20-tkg, tested with 8.11-tkg (self-compiled) a few minutes ago to no avail
- DXVK version: 0f4458e173749187c3900533196bf0327bc9fe80

### Apitrace file(s)
- [Part 1](https://mega.nz/file/Mldx1YrC#iyzmwjg0JiiumAPGwRnID0I6Ol2ZTA259a1DgNaODcQ)
- [Part 2](https://mega.nz/file/4h93Bb6T#ldFsg1KIrvUQdQPBQA8ezo3t8Ia8KJbGhyz1gyc0Rm0)

### Log files
Please attach Proton or Wine logs as a text file:
11MB log file? No thanks: 
[wildlands-spam.zip](https://github.com/doitsujin/dxvk/files/11873817/wildlands-spam.zip)

Looking at the logs, there's spam about "turf effects", the moving-grass thing.
Note that it works perfectly as far as I'm concerned, so that should be just spam, but nonetheless, it's better to have it than not to have it.

**Comment by doitsujin** [comment]
Never played the game, how long does it take to get to the point where this can be reproduced for someone who has absolutely no clue what to do?

Also, does this work with wined3d? The logs are awfully unspecific but if the issue was missing support for something I'd expect a crash, not a deadlock, if D3D11 was actually the issue here.

**Comment by gabriele2000** [comment]
> Never played the game, how long does it take to get to the point where this can be reproduced for someone who has absolutely no clue what to do and isn't willing to learn the game in detail?
> 
> Also, does this work with wined3d? The logs are awfully unspecific but if the issue was missing support for something I'd expect a crash, not a deadlock, if D3D11 was actually the issue here.

It doesn't even open without DXVK.
I've updated the description with the apitrace files btw, if you don't like telegram let me know and I'll try to provide a different sharing method

**Comment by gabriele2000** [comment]
@doitsujin Any news? Can you view the apitrace without problems?

**Comment by Blisto91** [comment]
I dunno about doit (whom you are asking and not me: 😁), but at least I don't seem to be able to download the traces. I assume you need a account.
Haven't personally had time to try this yet.

**Comment by gabriele2000** [comment]
> I dunno about doit (whom you are asking and not me 😁), but at least I don't seem to be able to download the traces. I assume you need a account. Haven't personally had time to try this yet.

Ok, it seems that I'll need to upload it in a classic cloud space then.
See, it was a test since Telegram has infinite cloud space, basically

**Comment by Blisto91** [comment]
I personally use mega, but that is because I have a account there. Also proton drive but that is a payed account.

**Comment by gabriele2000** [comment]
> I personally use mega, but that is because I have a free account there. Also proton drive tho that is a payed account.

Fixed, thanks for the suggestion!
Try now

**Comment by doitsujin** [comment]
The game submits command lists multiple times, this is legal but DXVK does not properly implement this without a workaround.

Can you test if commit 878da4984b91b898831001d393ee6f6fad7d3087 improves anything?

**Comment by gabriele2000** [comment]
> The game submits command lists multiple times, this is legal but DXVK does not properly implement this without a workaround.

So it this specific context (the animation with the two phones) why would the game do that?
What is exactly this "multiple command lists"?

> Can you test if commit [878da49](https://github.com/doitsujin/dxvk/commit/878da4984b91b898831001d393ee6f6fad7d3087) improves anything?

Sure, I'll test it in a few minutes and will report back!

**Comment by doitsujin** [comment]
No idea then, the trace crashes on replay and I'm not exactly convinced that DXVK is even the problem here.

**Comment by Blisto91** [comment]
So i've played a phone Intel mission in the Eastern Precinct but i haven't gotten it to crash with either Proton Experimental or Bleeding Edge

**Comment by gabriele2000** [comment]
> So i've played a phone Intel mission in the Eastern Precinct but i haven't gotten it to crash with either Proton Experimental or Bleeding Edge

The problem is that I can't open the game using wine's DirectX

**Comment by Blisto91** [comment]
Can you start the game with `WINEDEBUG=+loaddll` and then share the output? Just to main menu should be fine.

**Comment by Blisto91** [comment]
@gabriele2000 Is this still an issue you are experiencing?

**Comment by gabriele2000** [comment]
> @gabriele2000 Is this still an issue you are experiencing?

No clue, I uninstalled this game after this.
In doubt I'll close this issue.
