### ISSUE TITLE
Failed to create swapchain/crash on nearly every game on DXVK 2.2

### ISSUE THREAD

**Issue by jacob1218** [doitsujin/dxvk#3543]
I am getting a mix of different issues, but the biggest of which is Failed to create swapchain or Failed to create DXGI factory.
Some games, like Just Cause 4 (which has caused a consistent VK_DEVICE_LOST in the past) now don't even get far enough to produce log files.

### Software information
Almost any software with DXVK 2.2
### System information
- GPU: Intel ARC A770 16GB
- Driver: 31.0.101.4514
- Wine version: N/A (Windows 11 22H2)
- DXVK version: 2.2

### Apitrace file(s)
N/A

### Log files
Trying to find the game that could reliably reproduce one of these issues. will update soon

**Comment by K0bin** [comment]
I'm leaning towards blaming Intel's driver until someone has the same issue on Linux with an AMD or Nvidia GPU.

**Comment by WinterSnowfall** [comment]
Note that if you're on a dual GPU system (that includes having an iGPU active) do make sure the right GPU is the one selected for rendering. In some situations in the past we've seen Vulkan drivers mix up the ordering and having a disabled (as in not used for rendering) iGPU listed on the first position in the device list. This can be worked around by making sure your dGPU gets sellected, by using `DXVK_FILTER_DEVICE_NAME`.

**Comment by jacob1218** [comment]
> I'm leaning towards blaming Intel's driver until someone has the same issue on Linux with an AMD or Nvidia GPU.

You're right as after 2 system restarts, I was unable to reproduce this issue. However, I will be opening a separate one for Just Cause 4, as that seems to be an unrelated issue.
