### ISSUE TITLE
Assasin's Creed Origins - White Dots & Lines

### ISSUE THREAD

**Issue by senu1337** [doitsujin/dxvk#3545]
If you go out of the animus and stand with Layla at the entrance and look in the direction of the cave, you will see white dots or lines. These only appear when you look from a certain angle and only on edges. I also noticed that the whole thing seems to occur only in dark scenes. If you go out of the cave everything is normal. No lines, no dots.

![outside](https://github.com/doitsujin/dxvk/assets/138375026/615f7394-25e7-472a-b2c6-f37699c171d1)
![cave1](https://github.com/doitsujin/dxvk/assets/138375026/42dfc0c7-ffce-4234-9be3-8e180017f56c)
![cave2](https://github.com/doitsujin/dxvk/assets/138375026/804e22d1-db86-49dd-9add-4ec8cedd2a04)

### Software information

Assasin's Creed Origins (through Ubisoft Launcher)

### System information
- GPU: AMD Radeon 7900 XT
- Driver: 23.5.2
- Windows version: W11 22H2
- DXVK version: 2.2

[ACOrigins_d3d11.log](https://github.com/doitsujin/dxvk/files/11929595/ACOrigins_d3d11.log)
[ACOrigins_dxgi.log](https://github.com/doitsujin/dxvk/files/11929596/ACOrigins_dxgi.log)

**Comment by mbriar** [comment]
You should make an apitrace, although this is most likely an amd windows vulkan driver problem and not a dxvk bug, like all of the other AC:O issues that have been reported before.

**Comment by Blisto91** [comment]
In the first screenshot where you are outdoors i am unsure what i should look at. Unless you mean the lines on the clouds.
In the other two i guess you mean the bright lines at the edges of stuff.

If you are not able to get a apitrace then a save game in a buggy location would be good too. I don't know how far this is in the game.

**Comment by senu1337** [comment]
The first image only serves as a reference. There are no problems.
Exactly, in the other two pictures I mean the bright lines.

I put the files d3d9.dll, d3d11.dll, dxgi.dll and dxgitrace.dll from the apitrace into the game folder, but my game runs like on 1FPS. I can't even get to the start screen.

**Comment by Blisto91** [comment]
Is it possible for you to share a save game instead if apitrace doesn't want to cooperate?

**Comment by senu1337** [comment]
> Is it possible for you to share a save game instead if apitrace doesn't want to cooperate?

[savegames.zip](https://github.com/doitsujin/dxvk/files/11929690/savegames.zip)

**Comment by K0bin** [comment]
> I put the files d3d9.dll, d3d11.dll, dxgi.dll and dxgitrace.dll from the apitrace into the game folder, but my game runs like on 1FPS. I can't even get to the start screen.

That's normal. You just need to have some patience and power through.

**Comment by senu1337** [comment]
So we can say that there is neither a problem with the GPU, nor with DXVK. So the problem lies somewhere outside. (Quote from mbriar: "_amd windows vulkan driver problem_")

**Comment by Blisto91** [comment]
This does seem like a likely driver related issue. I can reproduce with amdvlk (AMD's own driver) on Linux, but not radv.
apitrace: https://drive.proton.me/urls/08D98GNA6M#ZZSKXmDXVS1U

**Comment by Blisto91** [comment]
@senu1337 Are you able to verify that this works now with the latest amd driver?

**Comment by Blisto91** [comment]
Confirmed myself that AMD have fixed it in amdvlk 2023.Q3.3 Linux driver and 23.9.2 Windows driver.
