### ISSUE TITLE
DxvkMemoryAllocator: Memory allocation failed

### ISSUE THREAD

**Issue by DrPHDCat** [doitsujin/dxvk#3548]
Please describe your issue as accurately as possible.

Castle Crashers is crashing on startup, in the log it tries to allocate apparently 64mb of memory and fails, i have no idea how does this happen 

### Software information
Castle Crashers, default settings

### System information
- GPU: AMD ATI Radeon HD 8670M
- Driver: amdgpu
- Wine version: Proton 8.0-2
- DXVK version: idk
- RAM: 8GiB

```info:  DXVK: Read 0 valid state cache entries
err:   DxvkMemoryAllocator: Memory allocation failed
err:     Size:      65536
err:     Alignment: 16
err:     Mem flags: 0x1
err:     Mem types: 0x0
err:   DxvkMemoryAllocator: Memory allocation failed```
[steam-204360.log](https://github.com/doitsujin/dxvk/files/11958760/steam-204360.log)

**Comment by Blisto91** [comment]
The log you posted is from 7.0-6, but i assume it's just cuz the same issues is present there.

Something odd seems to be going on with your drivers.
```
info:  Game: castle.exe
info:  DXVK: v1.10.3
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
MESA-INTEL: warning: Haswell Vulkan support is incomplete
ac_compute_device_uuid's output is based on invalid pci bus info.
info:  D3D9: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  Null hardware (RADV NAVI10):
info:    Driver: 23.1.3
info:    Vulkan: 1.3.246
info:  Process set as DPI aware
info:  Device properties:
info:    Device name:     : Null hardware (RADV NAVI10)
info:    Driver version   : 23.1.3
```

**Comment by DrPHDCat** [comment]
That's odd. I just spent hours configuring the drivers yesterday. AMDVLK doesnt even work for some reason.

**Comment by Blisto91** [comment]
@DrPHDCat Did you manage to figure out your issue?

**Comment by DrPHDCat** [comment]
i installed windows over linux instead of dealing with the problem so i would say no

**Comment by Blisto91** [comment]
Sorry to hear that. Hope you are having fun with the game at least 🙂
