### ISSUE TITLE
[d3d9] Fallout New Vegas, Fallout 3 has missing polygons every frame on Z1 Extreme APUs

### ISSUE THREAD

**Issue by 143mailliw** [doitsujin/dxvk#3552]
In both Fallout New Vegas and Fallout 3, the ground and the interior of buildings will have a seemingly random amount of polygons either removed or have their textures replaced with solid colors (usually black, but I've seen pink and yellow occasionally as well). This issue seems to resolve itself nearly entirely if Anisotropic Filtering was disabled in the game's launcher.

I was not able to reproduce this issue on other RDNA3 hardware (RX 7900XT), only the Z1 Extreme. It's possible this also happens on other Phoenix APUs.

### Software information
I tested both Fallout New Vegas and Fallout 3, both on Ultra settings & 1080p. The log file provided below is from Fallout New Vegas.

### System information
- GPU: Radeon 780M ([AMD/ATI] Phoenix1 [1002:15bf]) (GFX1103_R1)
- Driver: RADV, Mesa 23.1.3
- Wine version: Proton 8-2
- DXVK version: 2.1

### Apitrace file(s)
I was unable to take a trace as I did not have access to Windows on this device and attempting to use WineD3D resulted in the game crashing immediately.

### Log files
[steam-22380.log](https://github.com/doitsujin/dxvk/files/11965729/steam-22380.log)

**Comment by Blisto91** [comment]
Hi there and they you for the issue 👋 

If it doesn't reproduce on other rdna3 hardware then it's possible it could be a driver issue. These games in general run pretty well except for some at times hard to reproduce graphical problems that are game bugs.
Can you share a video or screenshot of the issue?

> I was unable to take a trace as I did not have access to Windows on this device and attempting to use WineD3D resulted in the game crashing immediately.

Making a apitrace with dxvk is fine for this kind of issue if that is possible.

Also have you checked proton experimental to see if it's still present with newer dxvk? I don't believe it will change anything but would be nice with a quick check.

**Comment by j7126** [comment]
I was also able to reproduce this issue on the AMD z1 extreme.

Here is a short video of the issue in fallout 3:

https://github.com/doitsujin/dxvk/assets/35882868/3403c7dc-fc41-4424-9ec3-0b68ff82aaec

You can see the ground flickering.

**Comment by 143mailliw** [comment]
> I was also able to reproduce this issue on the AMD z1 extreme.
> 
> Here is a short video of the issue in fallout 3:
> fo.mp4
> 
> You can see the ground flickering.

Can confirm that this is the same issue I'm having in Fallout New Vegas. It occurs in both games.

**Comment by Blisto91** [comment]
Yes a mesa issue would be the way

**Comment by 143mailliw** [comment]
For reference, the Mesa issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/9318
