### ISSUE TITLE
[d3d9] Artificial Academy 2 Character face artifact

### ISSUE THREAD

**Issue by Arkblade2015** [doitsujin/dxvk#3555]
If "Render 2" is enabled in the game settings, 
In certain scenes, artifacts appear on the faces of characters in certain settings.
See the video below for more information. Artifacts can be found on the sides and bottom of the nose.
https://drive.google.com/file/d/1FRCaOBTqm5DSZf12gBo9KR1cTEldXU54/view?usp=sharing

This problem does not occur with dgVoodoo2 or native, so i can assume that it is specific to dxvk.
Symptomatically, it seem to be a z-fighting, but
d3d9.floatEmulation = Strict
did not bring any solution.

### Software information
Artificial Academy 2 (with AA Unlimited)

### System information
- CPU: i7 6700
- GPU: Nvidia GeForce GTX 1070
- Driver: 536.40
- DXVK version: 2.2

### Apitrace file(s)
https://drive.google.com/file/d/1KrvUNgP2FwtpE_qW3IJs7nTA41x3Xrkt/view?usp=sharing

**Comment by Blisto91** [comment]
I've not been able to reproduce it in the trace with my amd card using either radv or amdvlk so far and i don't have a Nvidia ready at the moment to check on.

Might be a possibility that it's a depth bias issue and it will get fixed when Nvidia supports the `VK_EXT_depth_bias_control` extension along with https://github.com/doitsujin/dxvk/pull/3501 being used.
But i'll let the devs comment on if it actually seems like that is a the issue.

**Comment by Arkblade2015** [comment]
https://github.com/doitsujin/dxvk/actions/runs/5467864893
Since it appears that the https://github.com/doitsujin/dxvk/pull/3501 fixes have already been incorporated into the master branch, I have investigated using the above build.
So far the problem appears to be resolved. i will continue to investigate and report back if anything comes up.

**Comment by Blisto91** [comment]
Nvidia don't implement the extension yet, so that is probably unrelated. That is not to say it can't have been fixed on current master vs 2.2

**Comment by Blisto91** [comment]
@Arkblade2015 Is there any update on this issue? Even on my Nvidia GPU i am not seeing the issue in the trace when replaying with dxvk 2.2

**Comment by Blisto91** [comment]
@Arkblade2015 Friendly ping
