### ISSUE TITLE
[build] error cv_state in namespace std does not name a type

### ISSUE THREAD

**Issue by FNsi** [doitsujin/dxvk#3557]
In file included from ../src/util/util_fps_limiter.cpp:3

../src/util/thread.h:261:10

**Comment by netborg-afps** [comment]
You are probably doing a mistake when building. I know I did recommend you latest dxvk version in another thread, and due to other comment there I just discovered that there are automatic builds available via github actions?!

So this one should be the from the current head of master:
https://github.com/doitsujin/dxvk/actions/runs/5467864893

**Comment by FNsi** [comment]
I know I did recommend you latest dxvk version in another thread, and due to other comment there I just discovered that there are automatic builds available via github actions?!
> 
> 
> 
> So this should be the build from the current master branch:
> 
> https://github.com/doitsujin/dxvk/actions/runs/5467864893

Nice! Thank u again!

**Comment by DadSchoorse** [comment]
You are using the wrong mingw: https://github.com/doitsujin/dxvk#troubleshooting

**Comment by FNsi** [comment]
> You are using the wrong mingw: https://github.com/doitsujin/dxvk#troubleshooting

I am using mingW-w64 11.0.0.1, do you think it's because of the bcc-mingw-w64?

**Comment by Blisto91** [comment]
@FNsi Friendly ping. Did you figure out your issue?

**Comment by FNsi** [comment]
> @FNsi Friendly ping. Did you figure out your issue?

No clue, my SSD crashed, now I have to use windows for a while 😂

**Comment by Blisto91** [comment]
@FNsi Did you come back to Linux since and tried again? 👀

**Comment by FNsi** [comment]
> @FNsi Did you come back to Linux since and tried again? 👀 

Sorry, I am using wsl nowadays...
But, I think it's the time to give it a try...again
