### ISSUE TITLE
dxvk-cache is on system, not with dlls and exe

### ISSUE THREAD

**Issue by terry98** [doitsujin/dxvk#3558]
Hi, I've been playing Aliens Fireteam Elite on Steam on Windows and it works perfectly.. more than an issue is a question.. I'm using dxvk 2.2 and my logs are picking the dxvk state cache entries (like 2000 entries) and it's true because I can close the game and reopen it and the actions that should stutter for the first time doesn't. The thing is that the dxvk-cache file is not with the game exe and the dlls, I'm using a dxvk.conf file in the same location and it is found but I don't have any location settings for the cache location set and is nowhere to be found... where could the .dxvk-cache file be then?

System Info
OS: Windows 10 Pro
DXVK: 2.2
GPU: RX 6800
CPU: 5800X3D

**Comment by Blisto91** [comment]
From a quick check on Linux the cache file appears in `Aliens Fireteam Elite/Endeavor/Binaries/Win64/` which is also here i put the `dxvk.conf`

**Comment by terry98** [comment]
yeah that's where the DLLs and dxvk.conf reside, what I did was to add the environment setting for the shader cache location and it now created a new .dxvk-cache file in that location, still don't know where it was reading from before but it's sure reading it now from the new location.

**Comment by Blisto91** [comment]
I took a peek at this quickly on Windows.
It appears in the games shader cache folder in Steam. So mine shows up in `C:\Program Files (x86)\Steam\steamapps\shadercache\1549970\DXVK_state_cache` (1549970 is the games app id in steam).
This is like on Linux where cache in general is directed in to the Steam `shadercache` folder so i guess that Windows client also sets `DXVK_STATE_CACHE_PATH` when "Enable Shader Pre-caching" is on. Turning it off makes it appear in the game folder.
Might be a new thing on Windows with the updated UI.

<details>
  <summary>Steam option screenshot</summary>

![image](https://github.com/doitsujin/dxvk/assets/47954800/ffd37b54-c7aa-4816-a874-2f5ee529490f)
</details>
