### ISSUE TITLE
CSGO Dxvk Native stutters after a wile.

### ISSUE THREAD

**Issue by artivision** [doitsujin/dxvk#3559]
All Csgo updates, all kernels, all mesa versions, all native.dlls to the latest, all game settings, all Radeon PC's. After a wile the -vulkan argument stutters. Nothing suspicious from terminal launch.

**Comment by K0bin** [comment]
We can't really do anything about CSGO. Please redirect this to the CSGO team.

https://github.com/ValveSoftware/csgo-osx-linux

**Comment by Blisto91** [comment]
CSGO uses a pretty outdated version of dxvk by now. 
The stutter after a while issue has been heard before, but none of the dxvk devs have been able to reproduce afaik.

**Comment by Joshua-Ashton** [comment]
This isn't a CSGO bug but rather a Steam.Overlay bug.

**Comment by d10sfan** [comment]
Does that mean that disabling the steam overlay would help with the csgo stutters? Or is it more complicated than that?

**Comment by artivision** [comment]
> This isn't a CSGO bug but rather a Steam.Overlay bug.

People you are fast to close the issue. I wrote latest Dxvk version, meaning i have replace the .dll with v2.2. Also the overlay is disabled by forever.
