### ISSUE TITLE
Lower performance than expected with old nvidia dx9 sample

### ISSUE THREAD

**Issue by mirh** [doitsujin/dxvk#3574]
So, while investigating d3d9 having been [nerfed](https://github.com/elishacloud/dxwrapper/issues/164) in newer W10 versions, I eventually got to find a scenario where even dxvk is somewhat subpar. And unlike a lot of other times, this affects linux too!

| Scenario | FPS |
| ------------- | ------------- |
| 950M W10 d3d9 | 700 |
| 950M W10 dxvk | 480 |
| 2080 W10 d3d9  | 1550 |
| 2080 W10 dxvk   | 1700 |
| 2080 W7 d3d9  | 2150 |
| 2080 W7 dxvk110  | 2500 |
| 2080 wine dxvk  | 2200 |

(btw no shit that I wasn't getting much confirmation at the end of #1845 and #1901, when moving from the laptop to the desktop can lead to such night and day relative twists)

### Software information
Nvidia HDR with 2x FP16 MRTs sample
On linux I suppose you can even download the original [here](http://download.nvidia.com/developer/SDK/Individual_Samples/samples.html#HLSL_HDR_FP16x2), but on windows you either hex edit the exe to accept a custom d3d9.dll or you need [my version](https://github.com/mirh/HDR_FP16x2).

### System information
- GPU: 950M and 2080 super
- Driver: 531.41 (950M), 536.67 (2080 W10), 474 (2080 W7), 530 (2080 linux)
- Wine version: W10 22H2, W7 SP1 and manjaro 22.1 with wine 8.11
- DXVK version: 2.2 anywhere except on W7 with the old 1.10.3

### Apitrace file(s)
- [HDR_FP16x2 2006.zip](https://github.com/doitsujin/dxvk/files/12136933/HDR_FP16x2.2006.zip)

### Log files
- [HDR_FP16x2 2006_d3d9.log](https://github.com/doitsujin/dxvk/files/12136954/HDR_FP16x2.2006_d3d9.log)

**Comment by doitsujin** [comment]
So what's the actual problem here?

Not sure how much I really care about an ancient demo that literally does like 50 draw calls, is **entirely** CPU-limited, and still runs at 1400 FPS on my system and according to your numbers still runs better than any Windows setup. The real-world significance seems rather... low?

**Comment by mirh** [comment]
Windows 7 with dxvk is faster than linux with dxvk. 

---
As for the 950M, you were on the right track this was eventually a problem with switchable graphics, but there's still something that doesn't check out. 
After observing that using the integrated HD 520 graphics with dxvk could somehow give me better numbers, I did force the [DXGI layering](https://www.pcgamingwiki.com/wiki/Nvidia_Profile_Inspector#Layer_Vulkan.2FOpenGL_on_DXGI_swapchain) (`Composed: Flip` presentation) and that made the nvidia card almost double its framerate. 

You might then be easily inclined to blame optimus for not being meant to push hundreds and hundreds of frames, I guess.. but yet the default mode otherwise was still just the usual `Composed: Copy with GPU GDI`. I.e. the normal one for d3d9 too (at least in windowed mode), both with the igp and the dgpu, and even on the desktop. 
And so there's still this weird mystery left (even though it has at least a solution already), of why dxvk has this overhead even though flipping the frames the same way. But I suppose this is probably too windows-y of a quirk for your tastes.

**Comment by K0bin** [comment]
> And so there's still this weird mystery left (even though it has at least a solution already), of why dxvk has this overhead even though flipping the frames the same way

DXVK does another copy internally because we cannot implement D3D swapchains directly with Vulkan swapchains.

Either way, this is a tiny benchmark. In actual games, we're pretty much always on par with Windows D3D9 from what I've seen.

**Comment by lorn10** [comment]
Sorry for jumping-in. 

@mirh If you will look again into this matter then please include in your testing also the native D3D9 implementation in Mesa. I think it would be nice to see where it stands in regard to the original D3D9 support of Windows 7/10/11. :wink:

**Comment by mirh** [comment]
> DXVK does another copy internally because we cannot implement D3D swapchains directly with Vulkan swapchains.

I'm not sure how that answers my question. 
I'm comparing DXVK in windows with DXVK in linux. If the later is slower (on the platform where you can control everything), then you have a problem. 

> If you will look again into this matter then please include in your testing also the native D3D9 implementation in Mesa.

I'm afraid that isn't an option on nvidia, you are free to do this yourself.

**Comment by mirh** [comment]
Ok, just for the records, I think I have cracked the nut of why (old) DXVK *in windows* is even ***faster*** than DXVK *in linux* too.
Basically there's also some non-trivial amount of GDI/font activity going on under the hood, and wine [never](https://bugs.winehq.org/show_bug.cgi?id=56166) really cared for it (on top of the fact that W7 is certainly hard to beat, with its kernel-side hardware acceleration)

| Scenario | FPS |
| ------------- | ------------- |
| 2080S W7 dxvk110  | 2550 |
| 2080S W7 dxvk110 apitrace  | 2660 |
| 2080S wine-staging dxvk23  | 2150 |
| 2080S wine-staging-8.8 dxvk23  | 2300 |
| 2080S wine-staging-8.8 dxvk23 cached | 2500 |

There has yet to be a match, but most likely this isn't a monkey for you to take care of.
