### ISSUE TITLE
DXVK 2.0+ crashing even with Vulkan 1.3 support 

### ISSUE THREAD

**Issue by nerdsuryansh** [doitsujin/dxvk#3575]
Hello Dev's, so actually i am having a issue here, which was happening long time ago but didn't reported it here, i have **Intel HD Graphics 620** which does supports **Vulkan 1.3.215** unfortunately it crashes in every game, the only solution is that i have to use below versions, like DXVK 1.10.3, and my question is that why it is crashing even though it supports Vulkan 1.3.215 which is the requirement mentioned in DXVK 2.0 Description. Thanks.

Specifications (just in case)

Processor: Intel Core i3-7020U
IGPU: Intel HD Graphics 620
Ram: 8GB
OS: Windows 10 Home 22H2

**Comment by doitsujin** [comment]
Log file?

**Comment by nerdsuryansh** [comment]
alright wait, currently playing alien isolation with 1.10.3 with a-sync, let me use 2.2 a-sync and create log file

**Comment by nerdsuryansh** [comment]
there we go, it crashed at main menu.
[AI_d3d11.log](https://github.com/doitsujin/dxvk/files/12138557/AI_d3d11.log)
[AI_dxgi.log](https://github.com/doitsujin/dxvk/files/12138558/AI_dxgi.log)

**Comment by nerdsuryansh** [comment]
if you need without a-sync logs, just tell me.

**Comment by Blisto91** [comment]
Nothing sticks out in the log except the game wanting to use shared resources which isn't supported on Windows.
But since you say it happens for all games you try that is likely unrelated and I would say there is probably some driver or setup issue going on.

**Comment by nerdsuryansh** [comment]
currently i have driver version  **31.0.101.2125** from official intel's website. 
![Screenshot (44)](https://github.com/doitsujin/dxvk/assets/113819548/44a970d6-a65c-4843-9291-a24a727db4ad)

**Comment by nerdsuryansh** [comment]
so, what should i do? recent driver update was **31.0.101.2125** downloaded from official intel's website.

**Comment by mbriar** [comment]
There might not be anything you can do, I would put close to zero faith into intel's vulkan driver for old gpus on windows (and not much more on linux).

**Comment by nerdsuryansh** [comment]
sad, then 1.10.3 is my only option here. can't even enjoy the improvements in 2.0+ versions

**Comment by WinterSnowfall** [comment]
> (and not much more on linux).

The situation on Linux is, fortunately, **a lot** better than on Windows. I haven't had problems with ANV when using it with dxvk. Sadly, the Windows drivers for pre-Gen12 iGPUs have mostly been abandoned at this point (or switched to "legacy support model" if you want the official wording).

**Comment by nerdsuryansh** [comment]
i see. Thanks for replying.

**Comment by Flopster101** [comment]
I got the same issue here.

Specs:
CPU: Intel Celeron G3930
iGPU: Intel UHD Graphics 610
RAM: 8 GB
OS: Windows 11 22H2

After resetting commits and rebuilding dxvk several times I found out that the commit where this issue starts occurring is 343eba693d9866f1dcc1dda07a9eaeb20162dbd1. I tried to revert it but since there have been a lot of changes since then I wasn't successful in fixing the conflicts.

Probably not that useful of information, but maybe it can help in some way.

**Comment by Blisto91** [comment]
I would think that is likely a driver issue. I'm not aware of any issues with the dynamic rendering work on other drivers.

**Comment by Ash69123** [comment]
similiar thing happened to me but the my game ( nsuns4) crashed with empty dxgi log file

**Comment by Blisto91** [comment]
Post the logs

**Comment by Blisto91** [comment]
@nerdsuryansh Friendly ping. Can you give this another go with latest driver and dxvk

**Comment by Flopster101** [comment]
I just updated the driver to 31.0.101.2127 (latest version at the moment) and DXVK to 2.3.1. Games are still crashing or freezing in the same way.

Here are a few logs:

[CoD2SP_s_d3d9.log](https://github.com/doitsujin/dxvk/files/14781353/CoD2SP_s_d3d9.log)
[CoDWaW_d3d9.log](https://github.com/doitsujin/dxvk/files/14781355/CoDWaW_d3d9.log)  (the only one that gets to the main menu, but then crashes immediately upon loading any mission)
[farcry3_d3d11_d3d11.log](https://github.com/doitsujin/dxvk/files/14781357/farcry3_d3d11_d3d11.log)
[farcry3_d3d11_dxgi.log](https://github.com/doitsujin/dxvk/files/14781358/farcry3_d3d11_dxgi.log)
[Townscaper_d3d11.log](https://github.com/doitsujin/dxvk/files/14781376/Townscaper_d3d11.log)

**Comment by nerdsuryansh** [comment]
> @nerdsuryansh Friendly ping. Can you give this another go with latest driver and dxvk

hey, i don't play games anymore, but i did used DXVK 2.3 version and it didn't worked, but if the latest version fixed this then please can someone test it out?

**Comment by K0bin** [comment]
This very much appears to be a driver issue. Sorry but there isn't a lot we can do about it.

**Comment by nerdsuryansh** [comment]
Update: Intel has released New Driver for Intel HD Graphics 620 (ver. 31.0.101.2128, date 3/5/24)

its been two months but i looked up now.

Although i didn't tested the latest version of DXVK on it, but i would in foreseeable future.

**Comment by kangurek-kao** [comment]
Tested DXVK 2.0+ on the 31.0.101.2130 drivers - still crashes regardless of driver install procedure (update from OEM or clean install after wiping the OEM driver out via newest DDU build)
