### ISSUE TITLE
Secret Files: Tungusta doesn't seem to render the characters in the game

### ISSUE THREAD

**Issue by stuart-bowyer** [doitsujin/dxvk#3580]
**Please describe your issue as accurately as possible.**

Secret Files: Tungusta doesn't seem to render the characters in the game. They are just displayed as grey silhouettes as shown in the screenshot below.

I have tried all different settings, Anti-Aliasing disabled, enabled etc and none of them helped.

I am running it on a Steam Deck and I also tried it on a T480s with Intel UHD 630 and it was the same issue.

![image](https://github.com/doitsujin/dxvk/assets/5384693/b5ed1983-bab5-47e2-84c4-b26da95368eb)

### Software information
Secret Files: Tungusta from GOG using Heroic Launcher
I tried using Proton 8.0, Proton 7.0 and various versions of Proton-GE

### System information
- GPU: Steam Deck
- Driver: Unknown
- Wine version: Version used in Proton 8.0 and Proton 7.0 sorry I am not sure how to get this currently
- DXVK version: Version used in Proton 8.0 and Proton 7.0 sorry I am not sure how to get this currently
### Apitrace file(s)
- Put a link here: https://drive.google.com/file/d/1sB7n76seAc6Wb24YxcmXuQbKaTJXUaVN/view?usp=sharing

### Log files
Attached.
[steam-heroic-0.log](https://github.com/doitsujin/dxvk/files/12158136/steam-heroic-0.log)
[steam-heroic-Secret Files Tunguska.log](https://github.com/doitsujin/dxvk/files/12158137/steam-heroic-Secret.Files.Tunguska.log)

**Comment by K0bin** [comment]
The apitrace looks the same when replaying it with the Nvidia Windows D3D9 driver.
![image](https://github.com/doitsujin/dxvk/assets/1131720/54fe5951-f955-402c-a2ad-763c080de966)

That indicates this is not a DXVK issue but some other Wine component.

**Comment by stuart-bowyer** [comment]
Hi @K0bin  thanks for checking this, would you have some guidance as to where I should open this bug, which project? I originally contacted the guys on the Proton-GE project over Discord and they suggested it was a DXVK issue. Thanks for any tips.

Stuart.

**Comment by Blisto91** [comment]
Hi there Stuart. 
d3dx9 dll's are handled by Wine itself. They have a bug tracker here https://bugs.winehq.org/
I can see it's the `d3dx9_26`dll that's the cause here as when i set it as builtin the issue appears. 
Out of the box in Steam it renders fine since it installs the native Windows version during first time setup, so had to force it to use the builtin one for it to appear.

I think it might be the same issue reported here https://bugs.winehq.org/show_bug.cgi?id=48097 so you could try commenting on that.

**Comment by stuart-bowyer** [comment]
Hi @Blisto91,
thanks very much for your detailed reply and for investigating it. I will reported it at winehq then and comment on that other bug. It looks like it was open for a long time, I guess they are not as quick as you guys 😁

Thanks also for the workaround, I will use this for now and its also a very handy tip because I was not aware I could install the native stuff 👍

Thanks again guys for all your hard work, you are legendary! Finally I can play many games without the need for a bloated Windows installation 😊

Stuart.
