### ISSUE TITLE
Just cause 2 not working in latest dxvk

### ISSUE THREAD

**Issue by ajay9634** [doitsujin/dxvk#3587]
Just cause 2 works in dxvk 0.96 but not in latest dxvk .
This is dx 11 issue, please fix it.

**Comment by Blisto91** [comment]
Fill out the issue template

**Comment by K0bin** [comment]
![image](https://github.com/doitsujin/dxvk/assets/1131720/2b3a3c4e-6a17-4246-b73f-c880a219d40d)

Same.

The issue template is there for a reason, plase provide the requested information (GPU, driver, etc).
Feel free to reopen when you do.

**Comment by ajay9634** [comment]
### Software information
Name of the game- Just cause 2 in Exagear emulator

### System information
- GPU: Android snapdragon 
- Driver: aderno 618
- Wine version: 7.1
- DXVK version: 2.2 and 0.96

**Comment by ajay9634** [comment]
I will send a screenshot and log

**Comment by ajay9634** [comment]
![Screenshot_2023-07-27-21-18-38-063_com.ludashi.benchmark.jpg](https://github.com/doitsujin/dxvk/assets/78233144/d930eef8-8514-447b-a7e8-0458eebb2074)

Error in dxvk 2.2

**Comment by ajay9634** [comment]
![Screenshot_2023-07-27-21-21-08-881_com.ludashi.benchmark.jpg](https://github.com/doitsujin/dxvk/assets/78233144/ce632720-7c0b-42a7-b592-f5dd28ddb6cd)

No error in dxvk 0.96

**Comment by ajay9634** [comment]
Any idea?

**Comment by K0bin** [comment]
Android is not a supported platform.

**Comment by ajay9634** [comment]
Dxvk log not created after  installing dxvk 2.2  but log created after installing dxvk 0.96 .

Exagear is Ubuntu 18+ wine

**Comment by ajay9634** [comment]
If you have an Android phone please test it out.

**Comment by Blisto91** [comment]
Logs files are not created by default in Wine anymore. You have to set a path with `DXVK_LOG_PATH`

**Comment by ajay9634** [comment]
JustCause2_d3d11.log


warn:  D3D11DeviceFeatures: External memory features not supported
info:  D3D11CoreCreateDevice: Maximum supported feature level: D3D_FEATURE_LEVEL_11_1
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_10_1
info:  Device properties:
info:    Device : Turnip Adreno (TM) 618
info:    Driver : turnip Mesa driver 23.1.99
info:  Enabled device extensions:
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_robustness2
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_pipeline_library
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 1
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 1
info:    logicOp                                : 1
info:    multiDrawIndirect                      : 1
info:    drawIndirectFirstInstance              : 1
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 1
info:    shaderImageGatherExtended              : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 1
info:    shaderResourceResidency                : 0
info:    shaderResourceMinLod                   : 0
info:    sparseBinding                          : 0
info:    sparseResidencyBuffer                  : 0
info:    sparseResidencyImage2D                 : 0
info:    sparseResidencyImage3D                 : 0
info:    sparseResidency2Samples                : 0
info:    sparseResidency4Samples                : 0
info:    sparseResidency8Samples                : 0
info:    sparseResidency16Samples               : 0
info:    sparseResidencyAliased                 : 0
info:  Vulkan 1.1
info:    shaderDrawParameters                   : 1
info:  Vulkan 1.2
info:    samplerMirrorClampToEdge               : 1
info:    drawIndirectCount                      : 1
info:    samplerFilterMinmax                    : 1
info:    hostQueryReset                         : 1
info:    timelineSemaphore                      : 1
info:    bufferDeviceAddress                    : 0
info:    shaderOutputViewportIndex              : 1
info:    shaderOutputLayer                      : 1
info:    vulkanMemoryModel                      : 1
info:  Vulkan 1.3
info:    robustImageAccess                      : 0
info:    pipelineCreationCacheControl           : 1
info:    shaderDemoteToHelperInvocation         : 1
info:    shaderZeroInitializeWorkgroupMemory    : 0
info:    synchronization2                       : 1
info:    dynamicRendering                       : 1
info:  VK_AMD_shader_fragment_mask
info:    extension supported                    : 0
info:  VK_EXT_attachment_feedback_loop_layout
info:    attachmentFeedbackLoopLayout           : 0
info:  VK_EXT_conservative_rasterization
info:    extension supported                    : 0
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_extended_dynamic_state3

**Comment by ajay9634** [comment]
JustCause2_d3d10.log is empty

JustCause2_dxgi.log is empty

**Comment by ajay9634** [comment]
![Screenshot_2023-07-27-22-34-28-527_com.ludashi.benchmark.jpg](https://github.com/doitsujin/dxvk/assets/78233144/dcd9b79e-1fe1-4659-a6df-f0d068db7caf)

This is the error in wine, dxvk 2.2 after setting dxvk log path

**Comment by ajay9634** [comment]
I tested in dxvk 1.10.3 too
So I got this JustCause2_d3d11.log


info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_10_1
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_10_1
info:  Device properties:
info:    Device name:     : Turnip Adreno (TM) 618
info:    Driver version   : 23.1.99
info:  Enabled device extensions:
info:    VK_EXT_4444_formats
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state
info:    VK_EXT_host_query_reset
info:    VK_EXT_robustness2
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_image_format_list
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_float_controls
info:    VK_KHR_swapchain
info:    VK_KHR_timeline_semaphore
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 1
info:    logicOp                                : 1
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 0
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 1
info:    shaderStorageImageExtendedFormats      : 0
info:    shaderStorageImageReadWithoutFormat    : 0
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 1
info:  VK_EXT_4444_formats
info:    formatA4R4G4B4                         : 1
info:    formatA4B4G4R4                         : 1
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_extended_dynamic_state
info:    extendedDynamicState                   : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 0
info:  VK_EXT_non_seamless_cube_map
info:    nonSeamlessCubeMap                     : 0
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 1
info:    robustImageAccess2                     : 1
info:    nullDescriptor                         : 1
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 1
info:    geometryStreams                        : 1
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  VK_KHR_buffer_device_address
info:    bufferDeviceAddress                    : 0
info:  VK_KHR_timeline_semaphore
info:    timelineSemaphore                      : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 0
warn:  DXVK: State cache version not supported
warn:  DXVK: Creating new state cache file
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  800x585
info:    Image count:  4
info:    Exclusive FS: 1
info:  Setting display mode: 800x600@60
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  800x600
info:    Image count:  4
info:    Exclusive FS: 1

**Comment by ajay9634** [comment]
This is dxvk 0.96 and this is JustCause2_d3d11.log (works perfectly)

info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_10_1
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_10_1
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_driver_properties
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
warn:  DXVK: State cache entry size changed
warn:  DXVK: Creating new state cache file
info:  DXVK: Using 4 compiler threads
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  800x585
  Image count:  3
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_FIFO_KHR
  Buffer size:  800x600
  Image count:  4

**Comment by Blisto91** [comment]
Nothing sticks out in the logs. 
I am unsure if there is a dxvk issue here or if it's some Wine (besides d3dcompiler as mentioned above) or driver issue. ProtonDB is a bit of a mess for this game.

**Comment by ajay9634** [comment]
No problem, I will stick to dxvk 0.96
It's best compatible for dx10 and dx11.
Tomb raider 2013 works good  without any graphics issue in this dxvk.
Thanks for help

**Comment by Alien989** [comment]
problem is in aderno dxvk 32bit, not 64bit... in android box64 work  dxvk 2.2 dx10/11 perfect but, in android box86 and exagear dxvk 2.2 32bit dont work dx10/11
