### ISSUE TITLE
Halo Online Water Issue

### ISSUE THREAD

**Issue by Minelelol** [doitsujin/dxvk#3594]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Halo Online ms23 Eldewrito
High Detail Water ( Aka water distortion/wave ), Deloads when its not being interfered with object such as
Firing projectile, grenade, and vehicles etc

High detail water effect only appears when the game effect setting is set to high
I was planning to create a band aid mods that disable the high quality water but keep the distortion effect from object touching it

on a side note I have a feeling its not dxvk issue but rather an issue with amd vulkan driver, as my friend has never encountered this issue before on his end.
### System information
- GPU: Rx 570 4GB Red Dragon
- Driver: Amernimezone Custom Driver 23.4.2
- Windows version : W10 Pro 21H2
- DXVK version: 2.2 Gpl Async, Base 2.2

Conf :
d3d9.floatEmulation = Strict
d3d9.samplerAnisotropy = 16
d3d9.allowDirectBufferMapping = False
dxvk.trackPipelineLifetime = True
dxvk.maxChunkSize = 1
dxvk.gplAsyncCache= True

even without conf the issue still exist

### Apitrace file(s)
https://drive.google.com/file/d/19gtsVSv6Ub_e81ZhXmT1-S-0sWCHUn29/view?usp=sharing

### Video link on how it look like
https://www.youtube.com/watch?v=C5lboAfSeoY

### Log files ( Probably wont help )
[eldorado_d3d9.log](https://github.com/doitsujin/dxvk/files/12208510/eldorado_d3d9.log)

**Comment by Blisto91** [comment]
Why did you close the issue? 🤔

**Comment by Minelelol** [comment]
there was no comment lol, so I might as well close the issue if there are no response

**Comment by Blisto91** [comment]
It's vacation time and I personally didn't have a comment before I could check out the trace 🙂

**Comment by Blisto91** [comment]
Looks to be a regression with https://github.com/doitsujin/dxvk/commit/438ae5cdfce7e7b2b0b34b22caac5bf3310ccc41
