### ISSUE TITLE
Just Cause 4 VK_DEVICE_LOST before gameplay

### ISSUE THREAD

**Issue by Jacoby1218** [doitsujin/dxvk#3595]
On DXVK versions 2.0 and above, the game crashes with a VK_DEVICE_LOST error.
### Software information
game is Just Cause 4

### System information
- GPU: Intel ARC A770 (also tried Nvidia GTX 980, no change.)
- Driver: 31.0.101.4576
- Wine version: N/A (was tested on windows 11 22H2)
- DXVK version: 2.2

### Apitrace file(s)
https://drive.google.com/file/d/11MpmYwWZrBbmwHjaapaHuBaMHjxkf_yD/view?usp=drive_link

### Log files
[JustCause4_d3d11.log](https://github.com/doitsujin/dxvk/files/12209343/JustCause4_d3d11.log)
[JustCause4_dxgi.log](https://github.com/doitsujin/dxvk/files/12209344/JustCause4_dxgi.log)

**Comment by jacob1218** [comment]
should also add: while testing this you may run into a crash before the game starts on DXVK 2.2 specifically (dxgi.dll), if that happens idk what i changed if anything but now it seems to work ok

**Comment by Blisto91** [comment]
> the game crashes with a VK_DEVICE_LOST error.

Usually means the driver crashed.

I haven't tried on Windows but i did poke on Linux with a couple of AMD drivers (GPU is 7900xtx) and haven't encountered any crashes. Also tried spoofing GPU id to Intel without issue.

**Comment by Electron-PSO** [comment]
I'm helping someone with a Just Cause DXVK issue.

Here is a screen grab of the error they are getting.
They are using an A770 with an i9-9990k
1440p
Windows 11
Driver version 5081

![Just_Cause_4_DXVK](https://github.com/doitsujin/dxvk/assets/134448040/66a98e1e-4b87-45e4-a5a9-f341f1e02853)

**Comment by mbriar** [comment]
Tell them to not use dxvk and maybe report the issue to intel. It's almost certainly an intel driver issue.

**Comment by Electron-PSO** [comment]
Hello @mbriar ,

I'm not sure intel will get to it.  Which is why we try DXVK.

They are getting 20fps low everything in this game with ARC A770

The GPU is using 50W only, which points the driver being the issue.

Intel uses a DXVK type work around for some games, but they have to be put on the "Happy" list.

Many thanks,

-E

**Comment by Blisto91** [comment]
I am at least not seeing any issues on Linux AMD with the radv driver and dxvk 2.3.
A dxvk log as minimum is needed to see if anything sticks out, but i suspect it won't tell much.

I suspect it might be more useful to make a comment here https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/651
It's intended to gather issues on Windows and Intel people also interact there

**Comment by Electron-PSO** [comment]
Thanks,

I'll point them to the page you posted.

I decided to get the game on Steam, but I'll never play it, as it isn't my type of game.

However, I will try some things to see if anything helps.

Good luck >Everybody

-E

**Comment by Blisto91** [comment]
@Jacoby1218 Is this still the case with the latest drivers?

I see the d3d11 native performance issue got solved in a recent driver

**Comment by Electron-PSO** [comment]
I believe it did.  It was added to the intel "White List" for the dx11 wrapper.

It would be nice if intel let us add games ourselves.  Even if it was with disclaimers etc

**Comment by Blisto91** [comment]
@Jacoby1218 @Electron-PSO Are you able to give this another shot with latest dxvk and driver

**Comment by Blisto91** [comment]
@Jacoby1218 @Electron-PSO friendly ping

**Comment by K0bin** [comment]
Closing this due to a lack of feedback and because the game works on other drivers. It's most likely an Intel Windows driver issue, so out of our control anyway.
