### ISSUE TITLE
Watch Dogs 2/Far Cry 5 freezing after some time in gameplay

### ISSUE THREAD

**Issue by Jacoby1218** [doitsujin/dxvk#3596]
I've been trying to track down this issue for a while, but there's nothing different printed in the logs when this happens, and because it used to work, not sure how useful an apitrace would be.
PCGamingWiki actually appears to have done some tracking on this issue, saying that the last known version to work was DXVK 1.3.3.
I am unable to test that, as doing so with that version results in a VK_DEVICE_LOST for me. (it should work on Nvidia 30/40 series GPUs however.)
### Software information
WATCH_DOGS 2
settings used were maximum available, though i tried lower and it made no difference

### System information
- GPU: Intel ARC A770
- Driver: 31.0.101.4576
- Wine version: N/A (was tested on Windows 11 22H2)
- DXVK version: assumed affecting 1.3.4-2.2

### Apitrace file(s)
Will do if requested

### Log files
N/A (there's no hints as to why this might be happening in them)

**Comment by doitsujin** [comment]
What does "after some time in gameplay" mean here exactly?

**Comment by jacob1218** [comment]
It's random and dependent on how much movement the player does, Sorry, should have been clearer. In Far Cry 5, all you need to do to reproduce it is run the benchmark. In Watch_Dogs 2, you just get in a car, drive for 3-4 blocks, and it will freeze.
Should also add: once the game locks up, exiting will result in a GPU driver crash.

**Comment by Blisto91** [comment]
@Jacoby1218 Friendly ping. Is this still an issue today with latest driver and dxvk?

**Comment by Jacoby1218** [comment]
Seems to be fixed, closing

**Comment by metalbody** [comment]
how did you fix btw

**Comment by Jacoby1218** [comment]
I didn't do anything, but the issue seemed to have gone away. Is it still there? I no longer have the A770 to test with
