### ISSUE TITLE
Bioshock Infinite Entry Point Not Found

### ISSUE THREAD

**Issue by AsrielDewitt** [doitsujin/dxvk#3599]
Game create these errors when launching from the exe itself

![image](https://github.com/doitsujin/dxvk/assets/48144566/75127c34-9e98-452e-83c7-45a47c422155)
![image](https://github.com/doitsujin/dxvk/assets/48144566/e6b5d351-462e-46f3-bbac-c21044d8b749)

### Software information
Bioshock Infinite, Max settings except AA turned off, DX11

### System information
- GPU:GTX1650
- Driver:53667
- Wine version: Non/ Running Natively, using the .dll itself 
- DXVK version: 2.2

### Apitrace file(s)
- Non Made

### Log files
[BioShockInfinite_dxgi.log](https://github.com/doitsujin/dxvk/files/12251844/BioShockInfinite_dxgi.log)
[BioShockInfinite_d3d11.log](https://github.com/doitsujin/dxvk/files/12251845/BioShockInfinite_d3d11.log)

**Comment by AsrielDewitt** [comment]
Trouble shooting this further, version 2.0 doesn't work, same error

and using 1.10.3 caused this
![image](https://github.com/doitsujin/dxvk/assets/48144566/2702bfeb-2d42-4fb7-9f06-dd21488be3fd)

**Comment by Joshua-Ashton** [comment]
Can you please try the latest GitHub actions build?

**Comment by AsrielDewitt** [comment]
> Can you please try the latest GitHub actions build?

![image](https://github.com/doitsujin/dxvk/assets/48144566/b4443f96-7f3b-4cde-9626-a72fd791376f)

**Comment by Iglu47** [comment]
I just tested the GOG version (Steam version takes a long time to download with my internet) on Windows. Works fine. So far no idea what could be the problem. Maybe it has something to do with overlays?

<details><summary>screenshot</summary>
<p>

![bioshock_infinite](https://github.com/doitsujin/dxvk/assets/25866099/3080a233-56ae-4cb1-b0dc-e8a00f6b3c8d)

</p>
</details>

- GPU: NVIDIA GeForce GTX 1080 Ti (Pascal)
- Driver: 531.79 (Windows 10)
- Wine version: Windows 10 22H2
- DXVK version: https://github.com/doitsujin/dxvk/commit/b0b46fd075e9e8f735ed6cee184c1b912863b401

[BioShockInfinite_d3d11.log](https://github.com/doitsujin/dxvk/files/12261669/BioShockInfinite_d3d11.log)
[BioShockInfinite_dxgi.log](https://github.com/doitsujin/dxvk/files/12261670/BioShockInfinite_dxgi.log)

**Comment by Iglu47** [comment]
Also checked 536.67 version - still works fine.
> Maybe it has something to do with overlays?

at least RTSS doesn't seem to cause problem.

<details><summary>screenshot</summary>
<p>

![bioshock_infinite_53667](https://github.com/doitsujin/dxvk/assets/25866099/0537c658-1f19-4d85-ae56-ebbe905e52ca)

</p>
</details>

**Comment by AsrielDewitt** [comment]
> 

Have you try the steam version?

**Comment by AsrielDewitt** [comment]
> Also checked 536.67 version - still works fine.
> 
> > Maybe it has something to do with overlays?
> 
> at least RTSS doesn't seem to cause problem.
> 
> screenshot

Have you tried the steam version? Because that what's I'm using

**Comment by Iglu47** [comment]
I checked: 2K launcher and steam version launch without errors on linux with current proton experimental_8.0 and proton experimental_8.0 + manually [updated dxvk files](https://github.com/doitsujin/dxvk/actions/runs/5733397351)

[steam-8870-dxvk-master.log](https://github.com/doitsujin/dxvk/files/12264572/steam-8870.log)

<details><summary>screenshot</summary>
<p>

![bioshock_infinite_steam](https://github.com/doitsujin/dxvk/assets/25866099/53f9a1ec-b8e2-4e20-bf70-f30c30932716)

</p>
</details>

**Comment by AsrielDewitt** [comment]
> 



> I checked: 2K launcher and steam version launch without errors on linux with current proton experimental_8.0 and proton experimental_8.0 + manually [updated dxvk files](https://github.com/doitsujin/dxvk/actions/runs/5733397351)
> 
> [steam-8870-dxvk-master.log](https://github.com/doitsujin/dxvk/files/12264572/steam-8870.log)
> 
> screenshot

Odd, that makes... no sense why It doesn't work on Native Windows 11

**Comment by Blisto91** [comment]
> warn:  D3D11InternalCreateDevice: Adapter is not a DXVK adapter

This line usually indicates that it is trying to use a `dxgi.dll` that isn't dxvk's own, e.g. the one in the Windows system folder which won't work. Can happen if the game hardcode it's path

**Comment by Blisto91** [comment]
Checked on Windows. The error in the opening post only happens to me if i also put the `d3d9.dll` in next to the exe. Only putting dxgi and d3d11 makes it run fine for me.

**Comment by Blisto91** [comment]
I am not longer reproducing this on Windows for some reason even when i put all the dlls next to the exe

**Comment by Blisto91** [comment]
@AsrielDewitt Are you able to still reproduce the original issue?
