### ISSUE TITLE
Witcher 3 new Nvidia shader compiler

### ISSUE THREAD

**Issue by malek69** [doitsujin/dxvk#360]
Missing terrain rendering issue when using the new Nvidia shader compiler
https://youtu.be/Pzu4SwOD6l0
wine vanilla 3.7, nvidia 396.24, dxvk 0.50,
__GL_NextGenCompiler=1 DXVK_HUD=fps,frametimes,devinfo,memory wine64 ./Witcher3.exe
time: 2:11 __GL_NextGenCompiler=0 DXVK_HUD=fps,frametimes,devinfo,memory wine64 ./Witcher3.exe
### Software information
Witcher 3, setings: medium

### System information
- GPU: nvidia geforce gtx 750 ti(Kepler)
- Driver: 396.24
- Wine version: vanilla wine 3.7
- DXVK version: 0.50

### Apitrace file(s)
- Put a link here

### Log files
[witcher3_d3d11.log](https://github.com/doitsujin/dxvk/files/1984107/witcher3_d3d11.log)
[witcher3_dxgi.log](https://github.com/doitsujin/dxvk/files/1984109/witcher3_dxgi.log)
- d3d11.log:
- dxgi.log:

**Comment by doitsujin** [comment]
Fixed in 396.18.07, please use that.

**Comment by Yardanico** [comment]
@doitsujin just FYI: there's already a 396.18.08 version out :)

**Comment by malek69** [comment]
I need downgrade driver?
