### ISSUE TITLE
Checkered boxes visuals in Need for Speed 2015 

### ISSUE THREAD

**Issue by Algocalmin** [doitsujin/dxvk#3600]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
![20230803222541_1](https://github.com/doitsujin/dxvk/assets/122108202/50553b14-4ae3-4782-a306-f024de92add4)
![20230803222918_1](https://github.com/doitsujin/dxvk/assets/122108202/9e869edf-407d-4ac2-b4bb-1d70cb2ac00c)
![20230803223554_1](https://github.com/doitsujin/dxvk/assets/122108202/908a554a-09b8-43ab-99dd-01daf0fe5f10)

Max settings TAA 1920x1080

### System information
- GPU: RX 5600 XT 6GB 
- Driver: 23.7.2
- Windows version : W10 Pro 21H2
- DXVK version: 2.2
- 
### Log files
[NFS16_d3d11.log](https://github.com/doitsujin/dxvk/files/12254451/NFS16_d3d11.log)
[NFS16_dxgi.log](https://github.com/doitsujin/dxvk/files/12254452/NFS16_dxgi.log)

**Comment by Blisto91** [comment]
Try to record a apitrace if you can.
Since the apitrace DLLs replace the dxvk ones it won't show when you try but just get to a part where it normally shows and then we can replay the trace with dxvk to see if it reproduces.

**Comment by doitsujin** [comment]
Probably an AMD driver bug as usual, game generally seems to run fine for people: https://www.protondb.com/app/1262540

**Comment by Blisto91** [comment]
I quickly checked with radv (23.1.5) and played a bit with amdvlk (2023Q2.3) on Linux but haven't seen the issue yet. Will check on Windows later.
Does it always happen or only in specific locations or weather?

**Comment by Blisto91** [comment]
Played a bit on Windows with dxvk 2.2 and 23.10.23.03 (Ratchet and Clank driver) on my 7900xtx. Haven't encountered the issue.

**Comment by Algocalmin** [comment]
Nope. Issues still persists, and without modding the game to skip the game intro, the apitrace is to large to send.



https://github.com/doitsujin/dxvk/assets/122108202/9dc30d2c-5f47-437a-a340-9f0e97ea6c46

System information
GPU: RX 5600 XT 6GB
Driver: 23.7.2
Windows version : W10 Pro 21H2
DXVK version: 2.2

Max settings; TAA; 2k res

**Comment by Blisto91** [comment]
> Nope. Issues still persists, and without modding the game to skip the game intro, the apitrace is to large to send.

Yes that is normal. You'd usually compress and upload it somewhere.
Does it happen anywhere in the game?

**Comment by Algocalmin** [comment]
Will figure out a way for better compression & send method.
<i>Does it happen anywhere in the game?</i>
All the time everywhere, doesn't matter if played full online or "Play Alone" mode.

**Comment by Algocalmin** [comment]
API-trace 1- un-modded game: https://mega.nz/file/Ez10mAxJ#Sr7MdmV15gvTViPpP1EnRqrJPj3QzhhuAizP4xuqUJA

API-trace 2- with skip intro video mod (*just in case): https://mega.nz/file/h60ADbIS#j3NTzwZDBz3p3iCJa3W85_b6EYOzpD_HQ9Xb1ShJUxc

However don't think the game can be traced due to being only an always online game.
EA being EA:
![image](https://github.com/doitsujin/dxvk/assets/122108202/e9c05553-6c3c-46da-ad63-9e182b45f620)

**Comment by Blisto91** [comment]
Ye the trace end before getting ingame.

This seems like a likely driver issue, maybe rdna2 specific. Can check that later when i have time since i have to test something with a rdna2 card on Windows anyway.

**Comment by mbriar** [comment]
RX 5600 XT is RDNA1.

**Comment by Blisto91** [comment]
Sorry ye my bad. Thx for preventing my brain from potentially getting confused in the future

**Comment by Algocalmin** [comment]
EDIT : As of 22-09-2023 with the latest AMD drivers 23.9.2 performance is on par with what I had back in the day when using Dx11 + DXgi

This time however when using Dx11 + DXgi on top of the new driver, the game start in 4 blocks - 1 black left corner / the rest in white then the following error appears then the game closes itself:
![](https://cdn.discordapp.com/attachments/999416766285488200/1154853531216515173/P_20230922_214727.jpg)

if worth investigation please continue , if not, proposal to close with comment, thank you.
