### ISSUE TITLE
ok, so this is still being updated.

### ISSUE THREAD

**Issue by DOOMMARINE117** [doitsujin/dxvk#3605]
im assuming by judging the description. 

this let's you run any windows application on let's say arch linux? it work?

**Comment by Blisto91** [comment]
It's purpose is to help make d3d9 - d3d11 games work on Linux together with Wine yes.
Most games should work baring any bugs. 🙂

**Comment by DOOMMARINE117** [comment]
> It's purpose is to help make Direct3D 9 - 11 games work on Linux together with Wine yes. Most games should work baring any bugs. 🙂

nice, will games from xp days work with this app too like war of the ring, age of mythology, starcraft, star wars empire at war, resident evil 1-5, blood, legendary(greek mythology shooter), clive barker undying, sas secure tomorrow, wolfenstein return to castle, doom 3, quake 1-4 and etc?

**Comment by Blisto91** [comment]
I haven't looked up all those games but anything that uses DirectX 9 to 11 ( and in the future also 8 ) to render it's graphics dxvk can help with. What a game uses can usually be looked up at pcgamingwiki.com

Wine, which is the general Windows application to Linux translation layer, also have it's own graphical translation layer built in called wined3d and it can also handle DirectX prior to 9 and 8. So hopefully the games should work, again baring any bugs.

**Comment by DOOMMARINE117** [comment]
> I haven't looked up all those games but anything that uses DirectX 9 to 11 ( and in the future also 8 ) to render it's graphics dxvk can try to help with. What a game uses can usually be looked up at pcgamingwiki.com
> 
> Wine, which is the general Windows application to Linux translation layer, also have it's own graphical translation layer built in called wined3d and it can also handle DirectX prior to 9 and 8. So hopefully the games should work, again baring any bugs.

awesome.

how to install it? this app?

**Comment by Blisto91** [comment]
If you use some like Proton through Steam then it is already included and enabled automatically. Graphical Wine frontends like Lutris, Bottles and Heroic Launcher etc also include it and usually enable it for anything gaming related, or at least have a easy switch in the UI to turn it on.

To manually install it in something like regular system Wine there is a small guide in the readme https://github.com/doitsujin/dxvk#how-to-use

**Comment by DOOMMARINE117** [comment]
> If you use Proton through Steam then it is already included and enabled automatically. Graphical Wine frontends like Lutris, Bottles and Heroic Launcher etc also include it and usually enable it for anything gaming related, or at least have a easy switch in the UI to turn it on.
> 
> To manually install it in something like regular system Wine there is a small guide in the readme https://github.com/doitsujin/dxvk#how-to-use

i have installed wine-staging, wine-gecko, wine-mono and wine tricks installed earlier.

i mainly use dvd games and epic games store and gog galaxy. 

so i see there is a git clone part for build instructions?

**Comment by DOOMMARINE117** [comment]
> 



> Yes it can be found here https://github.com/doitsujin/dxvk#build-instructions
> 
> Prebuilt master commits from the last 3 months can also be downloaded from the CI if that is of interest https://github.com/doitsujin/dxvk/actions/workflows/artifacts.yml?query=branch%3Amaster
> 
> And regular stable prebuilt releases can be found here. https://github.com/doitsujin/dxvk/releases
> 
> I believe winetricks can also install dxvk.

i was trying to load winetricks. somereason it won't open. 

what is Cl?

**Comment by Blisto91** [comment]
Continuous Integration. Automatic building and testing of commits to make sure they compile.
