### ISSUE TITLE
DXVK on Gameloop Emulator

### ISSUE THREAD

**Issue by aaliyaan** [doitsujin/dxvk#3608]
Hello,

I am currently attempting to utilize DXVK within the Gameloop Emulator on Windows 10 to enhance my experience while playing PUBG Mobile. Gameloop employs various launchers to ensure the proper execution of PUBG Mobile on the emulator.

Here's the process:

AppMarket.exe: This launcher, resembling an AppStore, needs to be opened initially. Notably, DXVK functions smoothly at this stage, and I can observe the Heads-Up Display (HUD) without encountering any crashes or errors.

PUBG Mobile Launch: Once within AppMarket.exe, I proceed to open the PUBG Mobile application. This action triggers the launch of "AndroidEmulatorEn.exe," the component responsible for initiating the game itself. However, here is where the main challenge arises.

Out of a hundred attempts, I have only managed to successfully implement DXVK on "AndroidEmulatorEn.exe" once. Strangely, I am uncertain about the specific factors that led to its successful execution the first time, as subsequent attempts following a system restart have proven unsuccessful.

It appears that "AndroidEmulatorEn.exe" does not readily recognize the DXVK files that have been added to the directory containing this particular executable.

For context, I am utilizing an RTX 2070 Super graphics card paired with an i7-10700K processor.

Any insights or suggestions regarding this issue would be greatly appreciated.

Thank you,

**Comment by K0bin** [comment]
I don't know how Game loop works but I'd expect it to use the host Vulkan and OpenGL driver instead of D3D11.

Either way, I don't know what you're hoping to achieve here.

**Comment by Alialhonety** [comment]
هل وصلت لحل او لطريقه ارجو الرد
