### ISSUE TITLE
Blaster Master 3 (Steam ID 1588380) misses Text Box textures 

### ISSUE THREAD

**Issue by maldun** [doitsujin/dxvk#3611]
Hi!

The Linux version of Blaster Master 3 is missing the textboxes. (You see it immediately at the beginning of the game)
I reported the issue already on [Proton Github](https://github.com/ValveSoftware/Proton/issues/5887) but no solution insight.
The problem seems to be related to AMD drivers since it works fine on my old GeForce 750Ti and [other reports](https://www.protondb.com/app/1588380) also suggest that it is not trouble with NVidia cards but AMD cards (considering the Deck also has an AMD card). So I suspect driver issues. 

With further digging I found out today that there was already a related issue: [https://github.com/doitsujin/dxvk/issues/2946](https://github.com/doitsujin/dxvk/issues/2946), so maybe the problems are related because the textboxes are very likely part of a texture layer too (they are textures after all ...), so I hope you could have a look and find something to resolve the issue.

How it looks:
![image](https://github.com/doitsujin/dxvk/assets/874010/e6fc1c5f-605f-4349-81e3-cf560fabd2f6)
How it should look like:
![image](https://github.com/doitsujin/dxvk/assets/874010/3990bdf6-6310-4478-a0bf-43075e5b5320)

### Software information
Blaster Master Zero 3 
(Tested with all Proton versions currently available including GE)
PROTON_USE_D3D=1 %command%

### System information

Fedora release 37 (Thirty Seven) x86_64 
 Kernel: 6.3.12-100.fc37.x86_64 
DE: Plasma 5.27.4 
WM Theme: Breeze 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze-dark [GTK2/3] 
CPU: AMD Ryzen 9 5900X (24) @ 3.700GHz 
 GPU: AMD ATI Radeon RX 6600/6600 XT/6600M 
Memory: 13947MiB / 31959MiB 

### Trace File
[game.trace.zip](https://github.com/doitsujin/dxvk/files/12312449/game.trace.zip)

### Log files
[steam-1588380.log](https://github.com/doitsujin/dxvk/files/12312451/steam-1588380.log)

**Comment by K0bin** [comment]
![image](https://github.com/doitsujin/dxvk/assets/1131720/49142145-341e-4885-a661-0ebf913b4a98)

Works when replaying your apitrace. Did you make the apitrace with DXVK, WineD3D or on Windows? Can you make one with DXVK?

**Comment by maldun** [comment]
I removed now the PROTON_USE_D3D=1 flag so it should run with DXVK, so same issue
I see you use an NVidia card so maybe it is related to AMD cards after all? It worked fine on my same machine with NVidia.

[game.7.trace.zip](https://github.com/doitsujin/dxvk/files/12315664/game.7.trace.zip)
[steam-1588380.log](https://github.com/doitsujin/dxvk/files/12315668/steam-1588380.log)

**Comment by Blisto91** [comment]
Trace is fine for me on my AMD too. Will check it out ingame.

As a quick sidenote, `PROTON_USE_D3D` isn't a env var. Don't know if you intended to use `PROTON_USE_WINED3D`

**Comment by K0bin** [comment]
Yeah the new trace replays fine as well.

**Comment by Blisto91** [comment]
Can reproduce ingame when using your mesa (radv) version. Seems to be fine again with mesa 23.1.0 so if you are able to update your driver it should solve itself.

**Comment by maldun** [comment]
@Blisto91 You are correct I updated Fedora to Fedora 38 which ships with the more recent mesa drivers and it works now. I think this issue can be closed. Thanks you all for your time and the help!
