### ISSUE TITLE
World in Conflict - serious problem on startup with DXVK d3d10 32 bit and minor problem with d3d9 32 bit

### ISSUE THREAD

**Issue by Nikanoru** [doitsujin/dxvk#3613]
When trying out World in Conflict with DXVK d3d10 32 Bit I get an error message saying:

<img width="316" alt="Screenshot 2023-08-11 093743" src="https://github.com/doitsujin/dxvk/assets/83954293/25d743b5-7237-48e7-b90c-a794900cf6bb">

<img width="314" alt="Screenshot 2023-08-11 094751" src="https://github.com/doitsujin/dxvk/assets/83954293/7f6e3fea-3182-423f-ac9a-5972c61c5e68">

"wic.exe - Entry Point Not Found. The procedure entry point D3D11CoreCreateDevice@24 could not be located in the dynamic link library D:\Spiele\World in Conflight - Complete Edtition\D3D10CORE.DLL." This error message pops up several times before Windows switches to the game, once ingame all I get is a black screen, more of those error messages and an unresponsive game that I have to force close. I also get the message detailed below when running the game with the d3d9 dxvk variant.

When trying out World in Conflict with DXVK d3d9 32 Bit I get a message saying:

<img width="309" alt="Screenshot 2023-08-10 183649" src="https://github.com/doitsujin/dxvk/assets/83954293/672ac72c-61f1-45bd-9564-2972a5f267ea">

"Serious problems found when starting World in Conflict. Error: No appropriate 3D graphics card detected. Unable to run World in Conflict. It is highly recommended that you try to fix these problems before runing the game. Press OK to quit or press Cancel to try to start the game anyway."

If I press cancel, it starts the game but sets the resolution 1024x768 and graphics detail to very low. Everything seems to work fine, I can just change the resolution and graphics settings to my preferred option.

### Software information
World in Conflict - Complete Edition (from GOG)

### System information
- GPU: RTX 2070
- Driver: 532.34
- OS version:  Windows 11 22H2
- DXVK version: Tested many different ones from 1.6 to latest 2.2

### Apitrace file(s)
- The Issue does not show up when using the apitrace dlls

**Comment by Blisto91** [comment]
Where did you get the d3d10.dll. dxvk don't ship that anymore since 2.0 and it's recommend to just use windows own (or wines on Linux). Just in system folder not next to exe.
What dxvk DLLs are you using

**Comment by Nikanoru** [comment]
> Where did you get the d3d10.dll. dxvk don't ship that anymore since 2.0 and it's recommend to just use windows own (or wines on Linux). Just the default in system folder not next to exe. What dxvk DLLs are you using. For d3d10 you should just need d3d10core, d3d11 and dxgi

As I mentioned in my post, I used many different versions, from 1.6 up to 2.2, some older versions have the d3d10.dll. Regardless of that, the error occurs.

**Comment by Blisto91** [comment]
What DLLs are you using.

**Comment by Nikanoru** [comment]
I had been using d3d9.dll, d3d10core.dll, d3d11.dll dxgi.dll from dxvk 2.2 and also d3d10.dll and d3d10_1.dll from older versions. If I put all and ONLY the dll's from dxvk in the game's folder, I get the error you see in the 3rd screenshot of my initial post, if I use all the dll's expect for the d3d9.dll from dxvk 2.2 like you suggested, it does work actually. That was helpful thank you. 

It only works however if I set the "myDX10Flag " value in the games "Game Options.txt" to 1 and set the file to read-only otherwise it will not use dx10 and this vulkan or it will just crash the game, but that is unrelated to dxvk I believe, since the game has this issue even with normal windows dll's

**Comment by Blisto91** [comment]
Ye some games can be a bit moody when putting all DLLs next to the exe. Maybe something with the both pinging some in system folder and next to exe. So starting trying with just the ones needed for the API one wants to use is usually best.
E.g. Bioshock Infinete complaining when putting d3d9 DLL next to exe along with d3d11 and dxgi, whereas leaving d3d9 out makes it start fine <https://github.com/doitsujin/dxvk/issues/3599>

**Comment by WinterSnowfall** [comment]
@Nikanoru Are you still having any problems with the game or can we close this issue?

Seems to work fine here in d3d9 mode on Wine Staging, whereas d3d10, even with the read-only config file hack will cause the game to crash on load with an access violation (bit that seems more of a Wine problem, as it also happens with WineD3D).

**Comment by Nikanoru** [comment]
Sorry, sure you can close it. :)

Thanks for the help
