### ISSUE TITLE
Injustice: Gods Among Us alpha to coverage issues

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3617]
In Injustice: Gods Among Us when you set "Transparency Anti Aliasing" to "Alpha to Coverage" visual issues in GUI elements among others can be seen, like dots on some elements and missing effects. Ingame one can also observe a gray transparent pattern moving on the screen in at least one cutscene.

According to the devs this seems like a alpha to coverage dithering issue which would need a new extension to handle properly and is likely related to https://github.com/doitsujin/dxvk/issues/3380

<details>
  <summary>Screenshots</summary>
  
  #### View in original size to see the issue properly. Background is black because i deleted videos while testing
  
 ### Setting on
 
![Screenshot_20230814_143400](https://github.com/doitsujin/dxvk/assets/47954800/7b4967dd-f9d4-4fee-94cf-ae199b5efecc)
![Screenshot_20230814_143440](https://github.com/doitsujin/dxvk/assets/47954800/7031f2dc-8cc9-4bfa-a5ed-33bfaa2428cb)

### Setting off

![Screenshot_20230814_143628](https://github.com/doitsujin/dxvk/assets/47954800/a3fe6522-ff20-4225-a0bb-6af13c18df3e)
![Screenshot_20230814_143815](https://github.com/doitsujin/dxvk/assets/47954800/0daead71-b783-4b1d-91bf-b9cd3f421398)
</details>

### Software information
Injustice: Gods Among Us
Transparency Anti Aliasing = Alpha to Coverage

### System information
- GPU: 7900xtx
- Driver: days old mesa-git
- Wine version: Proton Experimental
- DXVK version: Any tested

### Apitrace file(s)
https://drive.proton.me/urls/6V9C8F3BWG#6Nnk5eTqHhUv

### Log files
[Injustice_d3d9.log](https://github.com/doitsujin/dxvk/files/12334735/Injustice_d3d9.log)

**Comment by K0bin** [comment]
Related to #3380
