### ISSUE TITLE
ERROR: Subproject exists but has no meson.build file

### ISSUE THREAD

**Issue by Crd5** [doitsujin/dxvk#3618]
### Software information
Trying to build dxvk (./package-release.sh master /your/target/directory --no-package)

### System information
- GPU: Apple M1 Pro
- Driver:
- Wine version: 8.0.1 (stable)
- DXVK version: latest

### Log files
[meson-log.txt](https://github.com/doitsujin/dxvk/files/12335802/meson-log.txt)

**Comment by doitsujin** [comment]
https://github.com/doitsujin/dxvk#build-instructions
