### ISSUE TITLE
THE QUARRY presentation problem.

### ISSUE THREAD

**Issue by artivision** [doitsujin/dxvk#3620]
Good day. Using AmdGpu and Picom here. With the **unredir-if-possible = true** option all games work fine and exhibit Freesync well. But with the game THE QUARRY presentation is choppy on all screen modes until i kill the compositor.

**Comment by adolfintel** [comment]
I don't have Picom installed but I played through that game on an AMD GPU a few months ago and it's perfect with DXVK.
As far as I know, modern compositors disable compositing when an application enters fullscreen (as in, it creates a window without borders that takes up the whole screen), so either Picom doesn't do it or the game does something weird and it doesn't trigger that behavior. It works on KDE so I'm guessing the first.

**Comment by Blisto91** [comment]
@artivision Hi there. Do you still have the issue to this day?
