### ISSUE TITLE
Borderlands 1: Game of the Year Enhanced, intermittent poor performance

### ISSUE THREAD

**Issue by kode54** [doitsujin/dxvk#3623]
### Software information
Game: Borderlands 1: Game of the Year Enhanced (Steam)

### System information
- GPU: Intel Arc A770 LE 16GB
- Driver: Mesa 23.3.0 devel.176563.f7e39c6f854
- Wine version: GE Proton8-11
- DXVK version: as bundled with GE Proton8-11

### Apitrace file(s)
https://f.losno.co/BorderlandsGOTY.trace

### Log files
https://f.losno.co/steam-729040.log.zst
Edit: Replaced the log, it seems I forgot to remove the apitrace DLLs before running this step.

### Perfetto log
https://f.losno.co/trace.perfetto-trace.2.zst

This trace shows an inordinate amount of time being spent in dxvk-submit for every rendered frame.

Edit 2: This trace may be a lot more useful:
https://f.losno.co/trace.perfetto-trace.3.zst

**Comment by K0bin** [comment]
That trace shows 30s of menu + loading and the ingame part is over after 2 seconds.

I don't own BL1 but I've tested BL2 quite a lot over the years and that one runs extremely well.

How do I use the perfetto files?

**Comment by kode54** [comment]
Yeah, sorry, I don't know for sure either, I've filed a bug with Mesa as well.

This describes the tracing I was using, and a locally run web site that loads and displays the traces (It needs to be unpacked first)

https://docs.mesa3d.org/perfetto.html

**Comment by kode54** [comment]
I won't be able to validate any of this any more for quite a while, since my A770 is now out of order and needs to be RMAed. I'll be on an RX 480 for the indefinite future, which seems to run this game just fine.

**Comment by K0bin** [comment]
That basically confirms that this isn't our bug but an ANV problem instead.

**Comment by kode54** [comment]
This is a very strange issue, too, because the performance depends on the presentation surface size, not the render resolution. It's rendering 1920x1080 the whole time, but slows down depending on how large the presentation surface is. At 3840x2160, it slows down considerably, shrinking the window to 1920x1080 speeds it up considerably. Removing the 200% scaling from XWayland speeds up the full screen presentation, which is now 1920x1080 as well, and shrinking it to a 1920x1080 window at 100% scale, or effectively half resolution, speeds it up to a playable 60fps.

I have reported this to Mesa, and nobody has responded to my post yet.

**Comment by kode54** [comment]
Again, sorry for the false alarm, and I verified the same issue occurred with my Radeon card. It was the game’s default enabled “Smoothed 22-62 fps” frame limiter, I never realized how bad it was. And the Proton issue I wasn’t following had a mention of the limiter buried deep within it, too.
