### ISSUE TITLE
[regression] Project: Snowblind shadow issues.

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3628]
Since commit https://github.com/doitsujin/dxvk/commit/80f7d2abd8cdedb48b82b9dd0bec0b605fd8410d shadows in Project: Snowblind have issues such as appearing small and offset from the character casting them.

<details>
  <summary>Screenshot</summary>

![image](https://github.com/doitsujin/dxvk/assets/47954800/5ef967c7-8a27-4f34-96c4-58577703bd3e)
</details>

### Software information
Project: Snowblind
Shadows enabled

### System information
- GPU: 7900xtx
- Driver: mesa-git
- Wine version: Proton Experimental
- DXVK version: https://github.com/doitsujin/dxvk/commit/80f7d2abd8cdedb48b82b9dd0bec0b605fd8410d and above

### Apitrace file(s)
https://drive.proton.me/urls/WVP280QRFM#mdsOwJTHtuu5

### Log files
[Snowblind_d3d9.log](https://github.com/doitsujin/dxvk/files/12389025/Snowblind_d3d9.log)
[snowblind.sp_d3d9.log](https://github.com/doitsujin/dxvk/files/12389095/snowblind.sp_d3d9.log)

**Comment by ViNi-Arco** [comment]
Hey @Blisto91, how did you get your game with black bars, can you teach me?

**Comment by ViNi-Arco** [comment]
> It's just the game running with 1440x1080 resolution while my monitor is 1920x1080

Did you create a personalized resolution, or was it all automated and you didn't know how?

I usually have to use xrandr --set "Center" to get black bars in games without Widescreen support..

**Comment by Blisto91** [comment]
I just selected the highest resolution the configuration window allowed me, haven't personally touched anything else. I've never tried messing with xrandr myself, but i imagine the behavior differs from game to game.
