### ISSUE TITLE
Fallout 4: F4SE (resolved) and Texture related issue(s)

### ISSUE THREAD

**Issue by jarrard** [doitsujin/dxvk#363]
**F4SE Issue:**
Fallout4 script-extender (f4se) fails to initialize, this is a wine bug... Use the following wine patches to fix -> https://github.com/hdmap/wine-hackery/tree/master/f4se

**Texture Alpha Blend issue:**
There are also a few textures in the game that come out mostly/all black, this is likely a alphablending issue.

**First** is the eyelash region of NPC and player characters, it appears black and even renders above glass textures for example when you observe yourself in front of mirror at gamestart and also when looking through the cryogenic chamber at your partner. (images provided)

**Second** texture issue is with a overlayed texture (foliage/rust?) on top of the electricity generators seen inside the vault (the ones that spark) and also on a few building types seen around concord. (images provided)

### Software information
Fallout 4, 
High settings, godrays are enabled as they work for me. 
Graphical settings don't appear to have any consequence.

### System information
- GPU: NV Geforce 1080ti
- Driver: 396.24
- Wine version: 3.7 Staging (Fallout4/Taskbar Patches)
- DXVK version: latest master (issue exists with in 0.42/50 also)

### Apitrace file(s)
- https://mega.nz/#!r2IFnLBD!LT8o3Jr0ULrGL3EGE2L02zkhKs8M7fCQ2c0AK0X_Djc

This has me load a savegame inside the museum (which freezes when loaded by dxvk), there are no broken textures except for eyelashes at this point. I will try to produce another apitrace of outside region.
[Save8_3DD5671AM466F7879_ConcordMuseum01_000104_20180511101022_3_2.fos.zip](https://github.com/doitsujin/dxvk/files/1997347/Save8_3DD5671AM466F7879_ConcordMuseum01_000104_20180511101022_3_2.fos.zip)  (this one I believe)

### Log files
- d3d11.log:[Fallout4_d3d11.log](https://github.com/doitsujin/dxvk/files/1997460/Fallout4_d3d11.log)
- dxgi.log: [Fallout4_dxgi.log](https://github.com/doitsujin/dxvk/files/1997459/Fallout4_dxgi.log)
- f4se.log: [f4se.log](https://github.com/doitsujin/dxvk/files/1997457/f4se.log)  _This error message does not appear with built-in_ (but doesn't work so needs wine patches at top)

It should actually be this: [f4se.log](https://github.com/doitsujin/dxvk/files/1997544/f4se.log)  and the f4se version should show up in the settings menu at bottom-right. Not sure if this is something DXVK can resolve.

### Images of texturing issues (resized and cropped)
![screenshot at 2018-05-11 18-30-10](https://user-images.githubusercontent.com/17428910/39955925-7d90e1e6-5616-11e8-902c-cf12c0d2ae2f.png)
![screenshot at 2018-05-11 17-10-08](https://user-images.githubusercontent.com/17428910/39955931-8f53f9e0-5616-11e8-8c88-d3f781b49fa0.png)
![screenshot at 2018-05-10 19-16-48](https://user-images.githubusercontent.com/17428910/39955938-ac452ee8-5616-11e8-9b41-de4a1d670006.png)

Eyelash Images coming soon...

**Comment by doitsujin** [comment]
> The apitrace file is 2.7gb compressed, should this be uploaded to dropbox?

I don't care *where* you upload it, please just upload it somewhere. Apitrace files are *always* that big because they contain literally every single D3D call the game makes.

**Comment by jarrard** [comment]
Ok, I will upload my first wine builtin apitrace to dropbox and update the first post with it. 

I can generate more if need be.

**Comment by jarrard** [comment]
I got a reply back from the f4se team about the trampoline issue. Perhaps this feature can be worked into dxvk? I dunno if wine in general is to blame or if its something dxvk can fix.

> Since branch instructions have a range that is smaller than the address space on 64-bit operating systems, we need to allocate a buffer that is adjacent to the game's code, called a "branch trampoline". Without that, the game's code and our DLL's code may be located too far away in memory to branch directly to each other.
> 
> Either WINE's loader is not supporting ASLR and loads executables at a very low address all of the time, or the functions for querying the state of memory are not implemented correctly.

**Comment by ssorgatem** [comment]
as for F4SE, could you try it on Windows + DXVK? Maybe it's just a Wine problem, getting more verbosy with DXVK.

**Comment by jarrard** [comment]
Yes I will give that a go sometime. I wish I knew why apitrace didn't work with fallout4 under windows, it seems to just quit.

I'm not sure how to setup dxvk under windows but I assume dropping the dll's into the game directory will suffice.

**Comment by hdmap** [comment]
I filed a bug report on winehq for f4se with more info there. With [these patches](https://github.com/hdmap/wine-hackery/tree/master/f4se) f4se starts fine and it still runs fine with dxvk for me.

**Comment by jarrard** [comment]
Ok cheers for that, I will test that out today. I switched to Antergos from Manjaro so gotta configure everything over again. 

Oddly enough the binary nvidia driver from their website doesn't install so I can't test 396.18.11 at this time (blank screen with cursor, no display error, shrug).

**Comment by jarrard** [comment]
AND we have it fixed fella's
It was either latest wine3.9+staging or the wine-ge related patches (gallium9 can be ignored for nvidia users).

Anyway as celebration of no more graphics oddities, here is a screen shot of a wall, as it was intended.

![fo4 fix screenshot_20180608_020605](https://user-images.githubusercontent.com/17428910/41113468-dea4f936-6ac0-11e8-81ff-a92f4b78c1d6.png)

**Comment by SegoItCh** [comment]
I have same thing on Windows
