### ISSUE TITLE
gta 4 does not lauch

### ISSUE THREAD

**Issue by pinturajin** [doitsujin/dxvk#3638]
### Software information gta 4
without the d3d9.dll it works fine but as soon as i place it in the game folder and try to lauch the game it shows the following error:
the exception unknown software exception occurred in the application at location

### System information
- GPU: amd a6 7310 with amd r4 igpu 
- Driver: adrenaline 17.7
- DXVK version: 2.2

### Log files
info:  Game: LaunchGTAIV.exe
info:  DXVK: v2.2
info:  Found config file: dxvk.conf
info:  Vulkan: Found vkGetInstanceProcAddr in vulkan-1.dll @ 0x7386bad0
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface

**Comment by K0bin** [comment]
The Windows driver for that GPU probably doesn't support the required Vulkan extensions and features.

**Comment by pinturajin** [comment]
is there anything i can do plz help. here is my gpu driver info :
Radeon Settings Version - 2017.1026.251.3303
Driver Packaging Version - 17.10.3901.1004-171026a-319526C-HP
Provider - Advanced Micro Devices, Inc.
2D Driver Version - 8.1.1.1599
Direct3D® Version - 9.14.10.01261
OpenGL® Version - 6.14.10.13476
OpenCL™ Version - 22.19.180.1025
AMD Mantle Version - 9.1.10.0189
AMD Mantle API Version - 102400
AMD Audio Driver Version - 10.0.1.1
Vulkan™ Driver Version - 1.5.0
Vulkan™ API Version - 1.0.39

**Comment by Joshua-Ashton** [comment]
> Vulkan™ API Version - 1.0.39

no.

**Comment by pinturajin** [comment]
i downgraded my driver so dxvk can work it was not working before as well with the updated driver

**Comment by Blisto91** [comment]
Your GPU driver needs to support Vulkan 1.3 to be able to run dxvk 2.0 and above, but your GPU isn't receiving new features anyway from amd.
If you fully upgraded your driver you might be able to run dzvk 1.10.3 but I can't promise it will be a good time.
