### ISSUE TITLE
Dirt Rally 2.0 flickering

### ISSUE THREAD

**Issue by adolfotregosa** [doitsujin/dxvk#3641]
There is flickering on screen, textures flickering? amdvlk does not work with this gpu ( for me it doesn't) so I can only test mesa-radeon radv. I tested  23.1.6 and 23.3 devel. I dunno if this comes from the driver of from dxvk. Any variable I can try to fix this ? 

Video showing the issue.
https://youtu.be/kjmljh4sSYc

### Software information
Dirt rally 2.0 , 1280x720, medium settings, AF 8x , 2x msaa

Asus rog Ally
- GPU: 780M
- Driver: Mesa 23.1.6
- Wine version: proton 8.0-3
- DXVK version: proton 8.0-3

**Comment by Blisto91** [comment]
Would guess a driver issue is likely.

Please attach a log. Proton or dxvk.
Also try to make an apitrace of the issue.

**Comment by adolfotregosa** [comment]
Didn't have much luck with the api trace but here's proton log:

[steam-690790.log](https://github.com/doitsujin/dxvk/files/12448771/steam-690790.log)

**Comment by adolfotregosa** [comment]
dxvk logs:

[dirtrally2_d3d11.log](https://github.com/doitsujin/dxvk/files/12448796/dirtrally2_d3d11.log)
[dirtrally2_dxgi.log](https://github.com/doitsujin/dxvk/files/12448797/dirtrally2_dxgi.log)

**Comment by adolfotregosa** [comment]
it seams to be an issue with mesa. closing

https://gitlab.freedesktop.org/mesa/mesa/-/issues/9318
