### ISSUE TITLE
Overcooked! All You Can Eat (1243830) broken fire particle effect

### ISSUE THREAD

**Issue by edisionnano** [doitsujin/dxvk#3644]
### Software information
Overcooked! All You Can Eat
From Steam (ID 1243830) using Proton Experimental Bleeding Edge

### System information
- GPU: 1650
- Driver: 535.104.05
- Proton version: Experimental Bleeding Edge

### Screenshot
![bug](https://github.com/doitsujin/dxvk/assets/26039434/b61fa506-ad8d-4686-bb11-41af6b32376d)

### Apitrace file(s)
[- link](https://drive.google.com/file/d/1s4fXSTVQhJRW76HBAEeojVcULYODraI-/view?usp=sharing)

### Log files
https://drive.google.com/file/d/1UCQAQlzaDkXlIAtuSjPEKDVXNLcIBPFU/view?usp=sharing

**Comment by Blisto91** [comment]
Found it to be a game bug also present in the Native game. https://steamcommunity.com/app/1243830/discussions/1/6006138415303808167/#c6006138415310257539
