### ISSUE TITLE
test drive unlimeted 2 sudden crash on 3rd lincince test on c4 

### ISSUE THREAD

**Issue by takuminightcore** [doitsujin/dxvk#3645]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Name of the game, settings used etc.
test drive unlimited 2  tdu world mod

### System information
- GPU: nvidia rtx 2070
- Driver:536.67.0
- Wine version: n/a
- DXVK version: dxvk 2.0

### Apitrace file(s)
[exceptions.log](https://github.com/doitsujin/dxvk/files/12460206/exceptions.log)

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

**Comment by Blisto91** [comment]
Hello. Please try a test with latest master which can be downloaded here https://github.com/doitsujin/dxvk/actions/runs/5983863808

If the issue still occurs then post dxvk, which appear next to exe or at the base of the game folder usually. Also make a apotrace without dxvk getting past the part where it usually crashes (it should crash with just apotrace) then share it here. Compress it first and then upload to a storage site so it can be shared easier.

**Comment by HunterCZ122** [comment]
Since you're using some kind of mod and Windows, can you try applying LAA flag to game's executable with [this tool](https://www.techpowerup.com/forums/threads/large-address-aware.112556/) for example? Some mods can take high amount of address space, and DXVK can additionally add too. Proton by default enables LAA for these problematic 32bit games.
