### ISSUE TITLE
Osiris: New Dawn, player model rendering issues (affects other Unity software)

### ISSUE THREAD

**Issue by schtufbox** [doitsujin/dxvk#365]
When playing Osiris: New Dawn, using DXVK; the ground is rendered correctly, but character and weapon models are completely messed up.  If run without DXVK, the ground textures are messed up, but character models render perfectly.
Possibly related; if using Worlds Adrift Island Creator, the same issue occurs, this is also a Unity engine game.
Sidenote:  I no longer have an Nvidia GTX1050 for testing, it died.

### Software information
Osiris: New Dawn

### System information
- GPU: AMD RX460
- Driver: Mesa 18.0.3
- Wine version: staging 3.8
- DXVK version:  581e505

### Log files

[OsirisNewDawn_d3d11.log](https://github.com/doitsujin/dxvk/files/1997521/OsirisNewDawn_d3d11.log)
[OsirisNewDawn_dxgi.log](https://github.com/doitsujin/dxvk/files/1997522/OsirisNewDawn_dxgi.log)

###Screenshots
First person mode, no weapon/item drawn, looks okay:
![1st person nothign wielded](https://user-images.githubusercontent.com/27377883/39956542-b9ad6d84-55da-11e8-874f-9be6ed6e8a27.png)
Switch to third person view or draw a weapon, it looks like this:
![3rd person or gun out](https://user-images.githubusercontent.com/27377883/39956544-beb910bc-55da-11e8-91da-16b77dfa0ba2.png)

Anything else needed let me know?

**Comment by doitsujin** [comment]
Unity Engine almost universally requires Stream Output (#135) and this game is no exception, it doesn't make much sense to look into that until this feature is implemented.
