### ISSUE TITLE
how to install dxvk on arch linux? 

### ISSUE THREAD

**Issue by DOOMMARINE117** [doitsujin/dxvk#3650]
how do you install dxvk?

**Comment by mbriar** [comment]
Have you looked at the readme?

**Comment by DOOMMARINE117** [comment]
> Have you looked at the readme?

i tried reading it. but, had no clue what to do first.

**Comment by Blisto91** [comment]
If just for regular system Wine without a external Wine manager you'd download the latest release from here https://github.com/doitsujin/dxvk/releases (top download under assets). Then you follow this section in readme https://github.com/doitsujin/dxvk#how-to-use

When it says to do overrides that means set the DLL names to `native` under the libraries tab in winecfg.
(gif below shows `native, builtin`)

![image](https://user-images.githubusercontent.com/10602045/78906537-29951b00-7a88-11ea-8142-3681f1ba8af0.gif)

**Comment by mbriar** [comment]
If the readme is too much for you, you should probably stick to something that handles installing dxvk for you. Like steam proton, lutris, bottles, ...

**Comment by DOOMMARINE117** [comment]
> If the readme is too much for you, you should probably stick to something that handles installing dxvk for you. Like steam proton, lutris, bottles, ...

ok, installed teh dxvk with git clone. does that count as install?

**Comment by Blisto91** [comment]
No. Follow the guide above or utilize third party tools to manage it like bottles, Heroic, Lutris or Steam.

**Comment by DOOMMARINE117** [comment]
i got installed.

thanks.

**Comment by survivorr9049** [comment]
i have the similiar issue. my operators program is windows 10. i tried read me instructors but it did not worked and spam: 'export 'is not recognized as an internal or external command, operable program or batch file.

**Comment by Blisto91** [comment]
The instructions are for Linux. 
You should never put dlls such as provided by dxvk into your system folders on Windows as you will very likely wreck your OS.

For Windows you just put them next to the games exe (choose correct bitness) and it should usually work. Though note Windows is not officially supported.
