### ISSUE TITLE
[Windwos10] Battlefield 2 Hud not displaying

### ISSUE THREAD

**Issue by Nerus87** [doitsujin/dxvk#3651]
When I start the game on SP mode, and die I can't select the respawn point on the map view and I can't select any type of soldier/weapon. Frame does not appear but is still selectable because I can hear the sound on button selection, even view is not shown/rendered.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Name of the game, settings used etc.

### System information
- GPU: Raadeon 6900 XT
- Driver: 23.7.2
- Wine version: N/A
- DXVK version: 2.2
- OS: Windows 10

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
[BF2_d3d9.log](https://github.com/doitsujin/dxvk/files/12504019/BF2_d3d9.log)

**Comment by Blisto91** [comment]
Please make an apitrace if possible. 
When making one without dxvk on Windows it's expected that the issue will not reproduce when making it but we will replaying it together with dxvk to see if it then does.

**Comment by BaumTV** [comment]
Well i have a problem with Battlefield 2 is crashing when i press "join Match" using DXVK 2.2 on Wine 8.0.1

Playing on Android with a SD 8+ Gen 1 with Adreno 730

**Comment by Blisto91** [comment]
Android is not a supported platform. 
I am not aware of any issues with Battlefield 2 currently on Linux related to dxvk. If you do find some do open an issue of course

**Comment by Blisto91** [comment]
Finally managed to reproduce the original issue. See https://github.com/doitsujin/dxvk/pull/3797#issue-2080902765
