### ISSUE TITLE
[d3d9] Trine 3: crashes when finishing some levels

### ISSUE THREAD

**Issue by ranplayer** [doitsujin/dxvk#3655]
Trine 3 crashes when finishing some levels ( **A Tumble Down** and **The Redwood Forest**). The crash won't happen with WineD3D. On **A Tumble Down** I was also able to reproduce the crash when just trying to click on "Go back to the map" by the end of the level. I've also tried adding the following DXVK's properties with no success: `d3d9.allowDirectBufferMapping = False;  d3d9.cachedDynamicBuffers=True`

![trine_error](https://github.com/doitsujin/dxvk/assets/69990640/27a2bb16-e815-49c7-aebd-708cd8a026e6)

### Software information
Game: Trine 3 (Steam Id: 319910)
Settings: Maxed out at 1080p.
Exe: 64-bit

### System information
- GPU: RX 6700 XT
- Driver: Mesa 23.1.6
- Wine version: Proton 8.0-3 and Experimental (2023/08/31)
- DXVK version: Used by Proton

### Apitrace file(s)
- [api trace](https://mega.nz/file/M1lm3CwB#E2s3PDbEtD0GBmphr84Mdsz8QUBVS8El_ZsXb8OS8kM)

### Log files
- [steam-319910-proton-experimental.tar.gz](https://github.com/doitsujin/dxvk/files/12523192/steam-319910-proton-experimental.tar.gz)

**Comment by Blisto91** [comment]
I already tried reproducing this when I saw the Proton issue but have not been able to at any specific levels.
The game can however sometimes racy crash on startup and seems to have some weird racy or periodic issues going on at times.

**Comment by ranplayer** [comment]
I haven't experienced any other random crash... just when finishing these two levels. I had opened the Proton issue first because I thought it was a wine bug (by the error dialog). But testing the game with WineD3D I haven't experienced any crash (though the OpenGL graphics are darker and sometimes hard to understand)

**Comment by Blisto91** [comment]
Can't say I know much specific about the issues except that the game was behaving very strangely.
Though will try to poke at it again

**Comment by ranplayer** [comment]
I believe it was a Mesa  issue. I've just tried using Proton 8.0-5 (RC) and Mesa 23.3.1 and it's working normally now. I'm going to close this one.
