### ISSUE TITLE
Native Access

### ISSUE THREAD

**Issue by paranoidi** [doitsujin/dxvk#3658]
### Software information

Trying to run Native Access application with a wine 8.15 with DXVK fails. After removing DXVK overrides from winecfg it works properly.

### System information

- GPU: Nvidia 2070 Super
- Driver: 470.199.02
- Wine version: 8.15
- DXVK version: 2.2

![native access](https://github.com/doitsujin/dxvk/assets/504877/04cf8c1d-88a6-4ebf-9429-6f0dc90455dc)

**Comment by Blisto91** [comment]
For dxvk 2.0 and above you need to minimum use the 510 drivers

**Comment by K0bin** [comment]
> The popup seems to complain about OpenGL though?

It's OpenGL ES through ANGLE, so it's OpenGL on D3D11.

Like Blisto says, your driver is too old.

**Comment by paranoidi** [comment]
@K0bin & @Blisto91 Thanks for pointing out that I'm running such old drivers. I verified that it now works as it should. What's even better one VST that I'm interested in works now as well!

**Comment by bhechinger** [comment]
@paranoidi Just curious what you're doing. I toyed around with that stuff under Wine but until controllers become supported sadly it's not super useful. :(

**Comment by K0bin** [comment]
>  but until controllers become supported sadly it's not super useful. :(

Controllers work fine.

**Comment by mbriar** [comment]
I don't think they are talking about game controllers.

**Comment by paranoidi** [comment]
@bhechinger I'm running Bitwig Studio and bunch of Windows VSTs with Yabridge. MIDI-controllers work fine once they are properly configured to your liking. Sadly manufacturers rarely provide Linux support so you have to rely on open source software or more realistically Windows VM. But that's usually just one time setup. 

Check out https://linuxmusicians.com/ for example :)

**Comment by bhechinger** [comment]
@paranoidi But Native Access? That's NI, right?

The problem I've run into is the NI hardware doesn't use MIDI it uses NKS which is completely unsupported. I have plans to add support for that but it's going to be a lot of work and I honestly don't have the time, sadly.

I love linuxmusicians.com. :-D

Thanks for letting me know!
