### ISSUE TITLE
Assassin's Creed Unity has messed up graphics

### ISSUE THREAD

**Issue by mozo78** [doitsujin/dxvk#366]
Assassin's Creed Unity has messed up graphics with little textures at all. Here you are some screenshots:
https://imgur.com/s28zTvE
https://imgur.com/as6dMkl
With regular Wine the game crashes at "Press any button" dialog after some movies in the begining, so I don't know how much apitrace will be helpful but I'll apply it here.

### Software information
Assassin's Creed Unity. I tried it with different video settings.

### System information
- GPU: Nvidia GTX 1080 Ti
- Driver: 396.24
- Wine version: 3.7/3.8/3.7-staging
- DXVK version: latest 12.05.2018

### Apitrace file(s)
[apitrace.zip](https://github.com/doitsujin/dxvk/files/1997738/apitrace.zip)

### Log files
- d3d11.log:
https://pastebin.com/CB24gzzD
- dxgi.log: 
https://pastebin.com/BdyDP6ki

**Comment by Eignar17** [comment]
@mozo78 update drivers to 296.18.11 https://developer.nvidia.com/vulkan-driver.

**Comment by mozo78** [comment]
I'll try, thank you :)

**Comment by doitsujin** [comment]
Can you record an apitrace on Windows? I cannot debug the problem without one.

Also, your "apitrace" is not an apitrace but console output.

**Comment by mozo78** [comment]
I don't use Windows and never will sorry for that :)
Actually the game runs with latest beta drivers, great work doitsujin, Nvidia!
https://imgur.com/uz7qW82
https://imgur.com/lxZo4BG

**Comment by doitsujin** [comment]
Okay, cool, thanks for reporting back :+1:

**Comment by mozo78** [comment]
Thanks to you for yor great work. It's incredible!
