### ISSUE TITLE
csgo on windows 10

### ISSUE THREAD

**Issue by hz2018tv** [doitsujin/dxvk#3660]
is there a setup guide for using latest dxvk on csgo on windows 10/11? copied the dll to the directory where csgo.exe is, didnt seem to work, copied the dll to a \bin directory the game wont start (maybe vac thinks it is a hack?) . searched online, most csgo related info are for linux. thx.

**Comment by Blisto91** [comment]
Don't think you can use dxvk on Windows without disabling anti cheat with `-insecure` which mean you can't join servers that requires it.

[Obligatory disclaimer](https://github.com/doitsujin/dxvk#online-multi-player-games) of it being at your own risk trying random tools and dll's together with anti cheat enabled games and not advisable.

**Comment by hz2018tv** [comment]
got it. that is what I suspected. thx
