### ISSUE TITLE
Far Cry 3: text and UI elements not visible with d3dx:D3DX11GetImageInfoFromMemory

### ISSUE THREAD

**Issue by Fabxx** [doitsujin/dxvk#3669]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Far Cry 3, running from farcry3_d3d11.exe
running from farcry3.exe, which should be d3d9 makes
the game go blackscreen.
on DX11 mode, text and some UI menu elements are not visible.

### System information
- GPU: RTX 3060 Dual OC 12GB
- Driver: 535.98
- Wine version: 8-14
- DXVK version: lastes one from winetricks.

### Apitrace file(s)
- If i try to use Apitrace without dxvk i cannot reproduce this issue, instead i get a different behavior.

### Log files
[log.txt](https://github.com/doitsujin/dxvk/files/12706207/log.txt)

**Comment by Blisto91** [comment]
The d3d11 issue is a Wine bug since dxvk doesn't implement the d3dx dll's. Installing the native `d3dx11_43` dll through winetricks should work around it.

The d3d9 issue i will poke a bit at

**Comment by Blisto91** [comment]
d3d9 mode stops working for me since commit https://github.com/doitsujin/dxvk/commit/14946c599f7450cda1c46efb3177d7b549873669

**Comment by axet** [comment]
Seems like D3DX11GetImageInfoFromMemory has been implemented by wine, but not implemented by dxvk (I could be mistaken)

https://www.phoronix.com/news/Wine-Staging-6.16

**Comment by mbriar** [comment]
D3DX11 will not be implemented by DXVK, D3DX works on top of D3D and wine's implementation (and also microsoft's implementation that can be installed with winetricks) should work with DXVK.

**Comment by axet** [comment]
Thanks mbriar. Indeed installing d3dx11_43 fixing the issue. I guess phoronix article about D3DX11GetImageInfoFromMemory has been implemented in wine 6.16 isn't correct. I'm using wine 8.21 and this method still throws an exception "Not implemented"

**Comment by K0bin** [comment]
The patch probably just hasn't made it from Staging into regular Wine yet.
