### ISSUE TITLE
How to add custom DXVK versions to Lutris 

### ISSUE THREAD

**Issue by Librix2** [doitsujin/dxvk#3671]
Hello
Instruction from this movie https://github.com/lutris/docs/blob/master/HowToDXVK.md

When i make command 
_/home/player1/dxvk/package-release.sh master /home/player1/.local/share/lutris/runtime/dxvk/dxvk-async_ 

player1@Player ~]$ /home/player1/dxvk/package-release.sh master /home/dxvk-async
DEPRECATION: c_link_args in the [properties] section of the machine fils] section.
DEPRECATION: cpp_link_args in the [properties] section of the machine fons] section.
The Meson build system
Version: 1.2.1
Source dir: /home/player1/dxvk
Build dir: /home/player1/.local/share/lutris/runtime/dxvk/dxvk-async/dx
Build type: cross build
Project name: dxvk
Project version: v1.0.1
C compiler for the host machine: x86_64-w64-mingw32-gcc (gcc 12.2.0 "x8
C linker for the host machine: x86_64-w64-mingw32-gcc ld.bfd 2.38
C++ compiler for the host machine: x86_64-w64-mingw32-g++ (gcc 12.2.0 "
C++ linker for the host machine: x86_64-w64-mingw32-g++ ld.bfd 2.38
C compiler for the build machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20230
C linker for the build machine: cc ld.bfd 2.41.0
C++ compiler for the build machine: c++ (gcc 13.2.1 "c++ (GCC) 13.2.1 2
C++ linker for the build machine: c++ ld.bfd 2.41.0
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Checking if "winelib check" compiles: NO 
Library vulkan-1 found: YES
Library d3d11 found: YES
Library dxgi found: YES
Library d3dcompiler_43 found: YES
Library d3dcompiler_47 found: YES
Program glslangValidator found: YES (/usr/bin/glslangValidator)
Run-time dependency threads found: YES
Dependency threads found: YES unknown (cached)
Build targets in project: 11
NOTICE: Future-deprecated features used:
 * 0.56.0: {'meson.source_root'}

dxvk v1.0.1

  User defined options
    Cross files : /home/player1/dxvk/build-win64.txt
    bindir      : x64
    buildtype   : release
    libdir      : x64
    prefix      : /home/player1/.local/share/lutris/runtime/dxvk/dxvk-a
    strip       : True
    enable_tests: false

Found ninja-1.11.1 at /usr/bin/ninja
WARNING: Running the setup command as `meson [options]` instead of `mesecated.
[5/190] Compiling C object src/util/libutil.a.p/sha1_sha1.c.obj
In function ‘SHA1Update’,
    inlined from ‘SHA1Pad’ at ../../../../../../../../dxvk/src/util/sha
../../../../../../../../dxvk/src/util/sha1/sha1.c:131:25: warning: ‘SHAn of size 1 [-Wstringop-overread]
  131 |                         SHA1Transform(context->state, (uint8_t 
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/util/sha1/sha1.c:131:25: note: referen]’ {aka ‘const unsigned char[64]’}
../../../../../../../../dxvk/src/util/sha1/sha1.c: In function ‘SHA1Pad
../../../../../../../../dxvk/src/util/sha1/sha1.c:51:1: note: in a call
   51 | SHA1Transform(uint32_t state[5], const uint8_t buffer[SHA1_BLOC
      | ^~~~~~~~~~~~~
In function ‘SHA1Update’,
    inlined from ‘SHA1Pad’ at ../../../../../../../../dxvk/src/util/sha
../../../../../../../../dxvk/src/util/sha1/sha1.c:131:25: warning: ‘SHAn of size 1 [-Wstringop-overread]
  131 |                         SHA1Transform(context->state, (uint8_t 
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/util/sha1/sha1.c:131:25: note: referen]’ {aka ‘const unsigned char[64]’}
../../../../../../../../dxvk/src/util/sha1/sha1.c: In function ‘SHA1Pad
../../../../../../../../dxvk/src/util/sha1/sha1.c:51:1: note: in a call
   51 | SHA1Transform(uint32_t state[5], const uint8_t buffer[SHA1_BLOC
      | ^~~~~~~~~~~~~
In function ‘SHA1Update’,
    inlined from ‘SHA1Pad’ at ../../../../../../../../dxvk/src/util/sha
../../../../../../../../dxvk/src/util/sha1/sha1.c:131:25: warning: ‘SHAn of size 8 [-Wstringop-overread]
  131 |                         SHA1Transform(context->state, (uint8_t 
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/util/sha1/sha1.c:131:25: note: referen]’ {aka ‘const unsigned char[64]’}
../../../../../../../../dxvk/src/util/sha1/sha1.c: In function ‘SHA1Pad
../../../../../../../../dxvk/src/util/sha1/sha1.c:51:1: note: in a call
   51 | SHA1Transform(uint32_t state[5], const uint8_t buffer[SHA1_BLOC
      | ^~~~~~~~~~~~~
[10/190] Compiling C++ object src/util/libutil.a.p/com_com_guid.cpp.obj
FAILED: src/util/libutil.a.p/com_com_guid.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/util/libutil.a.p -Isrc/util -I../../../.././../../../dxvk/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=OMINMAX -MD -MQ src/util/libutil.a.p/com_com_guid.cpp.obj -MF src/util//util/libutil.a.p/com_com_guid.cpp.obj -c ../../../../../../../../dxvk/
In file included from ../../../../../../../../dxvk/src/util/com/../../d
                 from ../../../../../../../../dxvk/src/util/com/com_gui
../../../../../../../../dxvk/src/util/com/../../d3d11/d3d11_include.h:2 D3D11_FORMAT_SUPPORT2’
   28 | typedef enum D3D11_FORMAT_SUPPORT2 {
      |              ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/x86_64-w64-mingw32/include/d3d11_1.h:99,
                 from ../../../../../../../../dxvk/src/util/com/../../d
/usr/x86_64-w64-mingw32/include/d3d11.h:1720:14: note: previous definit
 1720 | typedef enum D3D11_FORMAT_SUPPORT2 {
      |              ^~~~~~~~~~~~~~~~~~~~~
../../../../../../../../dxvk/src/util/com/../../d3d11/d3d11_include.h:4def int D3D11_FORMAT_SUPPORT2’
   41 | } D3D11_FORMAT_SUPPORT2;
      |   ^~~~~~~~~~~~~~~~~~~~~
/usr/x86_64-w64-mingw32/include/d3d11.h:1733:3: note: previous declarat2 D3D11_FORMAT_SUPPORT2’
 1733 | } D3D11_FORMAT_SUPPORT2;
      |   ^~~~~~~~~~~~~~~~~~~~~
In file included from ../../../../../../../../dxvk/src/util/com/../../d
                 from ../../../../../../../../dxvk/src/util/com/../../d
../../../../../../../../dxvk/src/util/com/../../d3d11/../dxvk/dxvk_buffrSliceHandle dxvk::DxvkBuffer::rename(const dxvk::DxvkBufferSliceHandle
../../../../../../../../dxvk/src/util/com/../../d3d11/../dxvk/dxvk_buffember of ‘std’
  206 |       return std::exchange(m_physSlice, slice);
      |                   ^~~~~~~~
[12/190] Compiling C++ object src/vulkan/libvkcommon.a.p/vulkan_loader.
FAILED: src/vulkan/libvkcommon.a.p/vulkan_loader.cpp.obj 
x86_64-w64-mingw32-g++ -Isrc/vulkan/libvkcommon.a.p -Isrc/vulkan -I../.../../../../../../../dxvk/include -fdiagnostics-color=always -D_FILE_OF1z -O3 -DNOMINMAX -pthread -MD -MQ src/vulkan/libvkcommon.a.p/vulkan_lo.p/vulkan_loader.cpp.obj.d -o src/vulkan/libvkcommon.a.p/vulkan_loader.rc/vulkan/vulkan_loader.cpp
In file included from ../../../../../../../../dxvk/src/vulkan/vulkan_lo
                 from ../../../../../../../../dxvk/src/vulkan/vulkan_lo
../../../../../../../../dxvk/src/vulkan/../util/rc/util_rc_ptr.h:121:6: not name a type
  121 | std::ostream& operator << (std::ostream& os, const dxvk::Rc<T>&
      |      ^~~~~~~
../../../../../../../../dxvk/src/vulkan/../util/rc/util_rc_ptr.h:4:1: n‘<ostream>’; did you forget to ‘#include <ostream>’?
    3 | #include <functional>
  +++ |+#include <ostream>
    4 | 
[15/190] Compiling C++ object src/vulkan/libvkcommon.a.p/vulkan_present
ninja: build stopped: subcommand failed.

This last error stopped instalation.

### Software information
Ea app

### System information
- GPU: Intel UHD graphics 605
- Driver: VGA compatible controller: Intel Corporation GeminiLake [UHD Graphics 605] (rev 03) (prog-if 00 [VGA controller])
- Wine version: Wine-Staging 8.15
- DXVK version: Vulkan-based D3D11 implementation for Linux / Wine

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

**Comment by HunterCZ122** [comment]
If I get it right, then you're trying to compile older version of DXVK with async patch. You really don't need to patch DXVK with async. It will be far easier to update your Mesa drivers to use mesa-git since anv (Intel's open-source Vulkan driver) supports GPL. If there's upstream issue with some game not working properly, then async will not fix it.

**Comment by Blisto91** [comment]
1.0.1 is god awful old and will have a whole bunch of compiler errors that will have to be fixed manually when using a updated compiler compared to back then. 
I'm unsure if you meant to compile 1.0.1, the instruction video is just very old. There generally shouldn't be any need to use such an old version
Also note that the async versions isn't supported here so any issues specific to compiling those be taken up at their respective repositories.

If you are just looking to use stable versions then pre compiled versions can be downloaded here https://github.com/doitsujin/dxvk/releases
