### ISSUE TITLE
Blur: d3dcompiler:D3DCompile2 broken on recent DXVK

### ISSUE THREAD

**Issue by Fabxx** [doitsujin/dxvk#3673]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Blur, prefix with vcrun2019 dxvk 2

shader compiler fixed with dxvk1030 package, might work with higher version until certain version of DXVK (1.8 or lower)

### System information
- GPU: RTX 3060
- Driver: 535.98
- Wine version: 8-14
- DXVK version: lastes from winetricks

### Apitrace file(s)
- cannot use

### Log files

Only repeated message:
```0024:err:d3dcompiler:D3DCompile2 Shader log:
0024:err:d3dcompiler:D3DCompile2     memory:1:337: E5017: Aborting due to not yet implemented feature: Instruction type HLSL_IR_RESOURCE_LOAD.```

**Comment by Blisto91** [comment]
dxvk doesn't implement the d3dcompiler dll's, they are included in Wine (Windows versions can also be used).

**Comment by Fabxx** [comment]
I tried, but also in wine the compiler seems to be broken

**Comment by Blisto91** [comment]
I meant a issue should be made at the wine tracker. 

To work around it in the meantime you can install the native ones with winetricks. Don't know the exact one needed here there is `d3dcompiler_42 d3dcompiler_43 d3dcompiler_46 d3dcompiler_47`

**Comment by K0bin** [comment]
D3DCompiler is not part of DXVK. It's implemented in Wine

**Comment by doitsujin** [comment]
yeah, this has nothing to do with DXVK whatsoever.
