### ISSUE TITLE
DXVAD fails to load libraries running EVE Online

### ISSUE THREAD

**Issue by stuffnex** [doitsujin/dxvk#3674]
Hello,
I am cross-posting from EVE forum dev for this issue I can't find a fix.
Disclaimer: I am very poor in IT skills and please I beg you to do not take assumptions and guide me accordingly, if you have the time and the patience to explain also I will very keen to do my best to learn something new.

**The Issue:**
On Ubuntu 23.04
Graphics: Intel® HD Graphics 4400 (HSW GT2)
I had to change the hard disk forcing me a fresh OS install and of Eve Online.
Followed the work of Anderson Geten in [this post](https://forums.eveonline.com/t/did-the-last-update-break-eve-under-linux/355870/33) after the assistance provided (Reno Arkasson is me) I manage to make it work well enough.

**Outputs say:**
Appears DXVAD struggle to reach the level required d3d12 and d3d11 to eventually failing to load msmpeg2vdec.dll and failing the execution of DirectXRedist.exe, Trinity platform dx11 results invalid and crash.

Under steam tha game manage get loaded twice (once in 40 the second in 70 minutes) but completely frozen and with repetitive request to kill the process for not responding.
But it loaded.
This make me think that the issue is software not hardware (Steam always got awful performances on Eve with my pc.. while though wine it's playable).

The best results I achieved gives this output when I execute eve.exe with `WINEPREFIX=$HOME/wineprefixes/eve/ wine eve.exe `
Here follows the full output up to the launcher loaded:

_[In preview the Markdown styling was messed up, this is the link to pastebin.com](https://pastebin.com/WZ4GNZx8)_

At this point the **Launcher** successfully starts. Now it's time to hit _Play Now_ to load the game and here come the troubles, first the terminal output:

_[In preview the Markdown styling was messed up, this is the link to pastebin.com](https://pastebin.com/fcscazTA)_

Now the following output comes from the EVE LogLite, a diagnostic feature of the launcher:

_[In preview the Markdown styling was messed up, this is the link to pastebin.com](https://pastebin.com/WkMqUjvB)_

I will **[link](https://forums.eveonline.com/t/sep-2023-new-install-fails/420836/11)** my post on the devs Eve Online forum for your information, perhaps, as I made you open half of a dozen tabs of links here the last pastebin about a curious think might save time spotting more mistakes in my workaround: **[here the link](https://pastebin.com/bmSW9cmA)**. I have the feeling I am changing parameters on two different interfaces, reading my posts something changed getting better with the string WINEPRE... and deteriorated with wine eve.exe... Idk...
 I really hope you could help me out in this.
Thanks in advance for your time, hope to hear from you!

**Comment by K0bin** [comment]
DXVA has nothing to do with DXVK.

**Comment by Blisto91** [comment]
I haven't read through every detail yet but it seems like you are using lavapipe which is a software Vulkan renderer. I assume you wouldn't want to use your Intel GPU driver though. Is that right?

**Comment by stuffnex** [comment]
Yeah... I guess... the Intel GPU is all I have!

**Comment by stuffnex** [comment]
> DXVA has nothing to do with DXVK.

ehm... hold on... isn't DXVK the engine to emulate the Direct X through DXVA (genereated by DXVK?) I am very confused..

**Comment by Blisto91** [comment]
DXVA is video acceleration. DXVK only handles translation of Direct3D 9 - 11 graphics to Vulkan.

I believe your problem might be your Vulkan drivers. I'm not familiar enough with Ubuntu to give advice on how to install them properly there, but if you could seek support on that front it might work better.

**Comment by stuffnex** [comment]
I see... Thank you @Blisto91 it's a good lead! I will go in that direction then! Thanks for your time and explanation!

**Comment by mbriar** [comment]
Your Intel GPU is an old Haswell model that doesn't support vulkan 1.3, so that's probably the problem. You can try to either use DXVK 1.10.3 or set `MESA_VK_VERSION_OVERRIDE=1.3` as environment variable.

**Comment by stuffnex** [comment]
@mbriar I'll be honest: I have no idea of where I could change this variable, but something I might do is to install DXVK 1.10.3 as you suggest! Trying now!

**Comment by Blisto91** [comment]
In the first log they are using 1.10.1 but it's still picking llvmpipe (lavapipe) so I think the Intel vulkan driver might just not be installed or setup properly.

**Comment by stuffnex** [comment]
> Your Intel GPU is an old Haswell model that doesn't support vulkan 1.3, so that's probably the problem. You can try to either use DXVK 1.10.3 or set `MESA_VK_VERSION_OVERRIDE=1.3` as environment variable.
....
yup I was noticing.... I am using the 1.10.1 already

**Comment by stuffnex** [comment]
https://pastebin.com/i3ms6401
omg....

**Comment by stuffnex** [comment]
Yeah.. I see.. would be to much asking how I can change these settings?

Il Lun 25 Set 2023, 19:59 Blisto91 ***@***.***> ha scritto:

**Comment by stuffnex** [comment]
All right... appears to me that vulkan indeed wasn't actually installed (at least properly) following https://linuxconfig.org/install-and-test-vulkan-on-linux I added the repository but still apt is unable to locate the last package vulkan-utils.

Launching the application now gives:
`...
info:  Required Vulkan extension VK_KHR_surface not supported
terminate called after throwing an instance of 'dxvk::DxvkError'
`
the launcher starts with the same log in Eve LogLite

**Comment by Blisto91** [comment]
> info:  Required Vulkan extension VK_KHR_surface not supported

This means there still is an issue with the Vulkan drivers. Make sure both 64bit and 32bit are installed.

**Comment by WinterSnowfall** [comment]
> apt is unable to locate the last package vulkan-utils.

If you're looking for vkinfo, vkcube and friends, those are under `vulkan-tools`.

I'm on Ubuntu 22.04, have no PPA, and I simply use the distro's packages, namely:
`sudo apt-get install libvulkan1 libvulkan1:i386 mesa-vulkan-drivers mesa-vulkan-drivers:i386 vulkan-tools`

As Blisto mentioned, it's rather important at time to ensure you have the 32-bit packages as well, otherwise some older apps/games will give you a hard time.
