### ISSUE TITLE
[D3D11] Star Wars Battlefront II crashed after launch with Proton with DXVK 2.3

### ISSUE THREAD

**Issue by tujhen** [doitsujin/dxvk#3675]
Since releasing Proton-GE 8-14 and newer I encountered the following bug: when I try to install Star Wars Battlefront II and prefix with Proton with DXVK 2.3 onboard, the game launch, but instantly crashed. On Proton-GE 8-13 and older I cant reproduce this bug, and cant reproduce it with official Valve 8.0-3 Proton, that use DXVK 2.2, all fine.

I try to debug it with PROTON_LOG=1 and folks help me to find one interesting error message, that I think is problem:
err: D3D11: GetImage: BufferId > 0 not supported

I attach log file bellow (it's very huge)

### Software information
Star Wars Battlefront II (2017)

### System information
- System: openSUSE Tumbleweed
- GPU: RX6900XT
- Driver: AMDGPU (Kernel 6.5.4)
- Wine version:  Proton-GE since 8-14
- DXVK version:  DXVK 2.3
- Mesa: 23.1.7

### Log files
[steam-1237950.log](https://drive.google.com/file/d/1Cyx53KgOsQ_P4PRnnbGynM9xOOFaHkvR/view?usp=sharing)

**Comment by doitsujin** [comment]
> err: D3D11: GetImage: BufferId > 0 not supported

This has never been supported even on older DXVK versions.

Please try using DXVK 2.3 on top of Proton 8.0-3 to confirm it's not just some weird issue with GE.

**Comment by spacepetunia** [comment]
> > err: D3D11: GetImage: BufferId > 0 not supported
> 
> This has never been supported even on older DXVK versions.
> 
> Please try using DXVK 2.3 on top of Proton 8.0-3 to confirm it's not just some weird issue with GE.

So I need to download DXVK 2.3 from Release page and copy DLLs to Star Wars Battlefront prefix and if something not ok, send logs with PROTON_LOG=1 again?

**Comment by Blisto91** [comment]
@tujhen do you hit the same issue with Proton 8.0-4 or Experimental?

**Comment by Blisto91** [comment]
@tujhen Friendly ping

**Comment by tujhen** [comment]
> @tujhen Friendly ping

Absolutely sorry, forgot about it. I think, we can close. Game works correctly without any issues after some updates. With Proton-8.0-4 and GE-25 exactly.
