### ISSUE TITLE
Neptunia Sisters VS Sisters GOG have serious rendering issues (works ok with wined3d)

### ISSUE THREAD

**Issue by mrdeathjr28** [doitsujin/dxvk#3678]
Hi

### Software information

Neptunia Sisters VS Sisters GOG have serious rendering issues (works ok with wined3d), this game use unity engine

dxvk-2.3-git

![npsvs](https://github.com/doitsujin/dxvk/assets/6601480/9bd8b125-8f81-4539-955a-449ce7ed141b)

dxvk-2.2

![dxvk22](https://github.com/doitsujin/dxvk/assets/6601480/4b532833-b12e-416e-90b7-a8010b5a52d5)

wined3d

![wn817a](https://github.com/doitsujin/dxvk/assets/6601480/dba6894c-5177-4110-9cab-72cffc08f69d)

### System information
- GPU: Intel UHD 630 CFL GT2
- Driver: Mesa 23..3-dev
- Wine version:  8.17 Staging
- DXVK version:  Tested 2.3git-2.3-2.2

### Apitrace file(s)
- update: game dont allow trace, crash at begins

### Log files

[neptunia-sisters-vs-sisters_d3d11.log](https://github.com/doitsujin/dxvk/files/12775361/neptunia-sisters-vs-sisters_d3d11.log)

**Comment by HunterCZ122** [comment]
![nvidia](https://github.com/doitsujin/dxvk/assets/23011428/ad32d1bf-c53c-418d-b33e-9a3bb3783ceb)
Can't reproduce on nvidia, and also on anv which is weird...
Where it does exactly happen?

**Comment by mrdeathjr28** [comment]
update my mesa 23.3 drivers and downgrade wine to 8.16 staging because 8.17 staging fuck various things in my case

![fxd](https://github.com/doitsujin/dxvk/assets/6601480/dd54ee6e-45d7-4b0b-b6b6-3501ab136c12)

and stay fixed now 

thanks
