### ISSUE TITLE
suggestion: generic wrapper properties for some specific properties (config)

### ISSUE THREAD

**Issue by ranplayer** [doitsujin/dxvk#3684]
Hello,

Would it be possible to add some generic wrapper properties for some specific properties like: 
```
# dxgi.numBackBuffers = 0
# d3d9.numBackBuffers = 0
# dxgi.syncInterval = -1
# d3d9.presentInterval = -1
```

something like: `dxvk.syncInterval and dxvk.numBackBuffers`

Just explaining my use case: sometimes I override the game's vsync settings (due to bugs, for instance), and I use the new `DXVK_CONFIG` envvar to do so. But I need to know if the game uses D3D9 or another API version to add the right property (in the vsync case, the specific property has different names)

**Comment by K0bin** [comment]
Just set up a global config file. This seems like such a niche use case.
