### ISSUE TITLE
New World: Stuttering/Bad Frame Pacing compared to Windows

### ISSUE THREAD

**Issue by Faugus** [doitsujin/dxvk#3686]
As the title says, the game runs significantly worse on Linux.
Here's a footage comparing:
https://youtu.be/-gN14wkNcX8
Proton Log:
[steam-1063730.zip](https://github.com/doitsujin/dxvk/files/12826761/steam-1063730.zip)

I don't know if you can see from the video that the game feels choppy on Linux while it's smooth on Windows.
I recently played God of War (D3D11/DXVK) and the game ran very smoothly.
Is there anything we can do to improve the performance of New World on Linux?

Another thing I noticed with this game is that if I activate the Resizable Bar/SAM in the BIOS, the game stutters a lot more.
With VKD3D we have that `VKD3D=no_upload_hvv` parameter that helps solve problems some games suffer from when activating Resizable Bar/SAM.
Is there anything similar with DXVK?

I don't think it's a problem with my system, as the other games I usually play run fine.

Arch XFCE X11 (I've also tried KDE X11 and Wayland)
Kernel 6.5.5
Mesa 23.3.0-devel
Proton Experimental (also tried some Proton-GE versions)
CPU: AMD Ryzen 5 5600X
GPU: AMD Radeon RX 6800 XT
MOBO: Asus B550-A Rog Strix
RAM: Netac 32GB 3600MHz
Storage: Netac NVMe 2TB

**Comment by Blisto91** [comment]
Are the stutters constant or do they fade over time when running around in the same area?

> With VKD3D we have that VKD3D=no_upload_hvv

dxvk doesn't have similar no, you'd have to disable it in BIOS.

Does anything change if you install the native `d3dcompiler_47` into the prefix through winetricks or protontricks? I see quite a lot of spam in your log from the Wine one.

**Comment by doitsujin** [comment]
> Is there anything similar with DXVK?

Yes, `DXVK_CONFIG=d3d11.cachedDynamicResources=a`.

**Comment by Faugus** [comment]
> Does anything change if you install the native d3dcompiler_47 into the prefix through winetricks or protontricks?
I tried to install with Protontricks, but nothing changed, unfortunately.

> Yes, DXVK_CONFIG=d3d11.cachedDynamicResources=a.
I was testing again and looks Resizable Bar/SAM impacts negatively more on Windows.
I thought ReBar could be contributing to the Linux bad performance, but looks like it's not.

**Comment by Blisto91** [comment]
Does the issue not happen without dxvk? Just trying with wined3d

**Comment by Faugus** [comment]
I just tried with wined3d and it's basically the same + graphical glitches

**Comment by Blisto91** [comment]
Then it's very likely something outside the control of dxvk.
I can not test with dxvk Windows to check there because of Anti Cheat.

**Comment by Blisto91** [comment]
@Faugus Do you still have this issue today? I play a bunch of New World now and then and even though i mostly don't play with hud on i can't say I've really noticed this anymore.

**Comment by Faugus** [comment]
@Blisto91 I just installed New World to test and looks like it is a lot better now. Some small stutters when loading new areas, but that's normal.
