### ISSUE TITLE
Elder Scrolls Online: Unable to initialize render device

### ISSUE THREAD

**Issue by julianovs** [doitsujin/dxvk#369]
### System information
- GPU: 1080 TI
- Driver:396.18.11
- Wine version: 3.7 stagging
- DXVK version: 13 MAY BINARY 64 BIT
[eso64_d3d11.log](https://github.com/doitsujin/dxvk/files/1998523/eso64_d3d11.log)
[eso64_dxgi.log](https://github.com/doitsujin/dxvk/files/1998524/eso64_dxgi.log)

**Comment by julianovs** [comment]
The game works on earlier versions of dxvk with high fps 90-98 (gtx 1080 ti), however small lags/freezes (1-2 seconds duration) every 5 seconds but fps remains high
I downloaded the dxvk from May 13th already compiled in the 64 bit version to test and the game did not run "Unable to initialize render device"

**Comment by ssorgatem** [comment]
It works for me (Vega 56).

**Comment by varris1** [comment]
Nvidia GTX 970
Driver version: 396.18.11
DXVK: c17f4e2

ESO runs fine for me. Did you try one of haagch's builds available here? https://haagch.frickel.club/files/dxvk/

**Comment by julianovs** [comment]
yeah, the game works on earlier versions but haagch latest 64 bit binary (13th may) not work  here gtx 1080 ti

**Comment by julianovs** [comment]
i will try c17f4e2

**Comment by varris1** [comment]
A few people had issues with haagch's builds for some reason.

Doitsujin released a new official dxvk version. Can you try that instead? https://github.com/doitsujin/dxvk/releases

**Comment by julianovs** [comment]
c17f4e2 work but small lags/freezes (1-2 seconds duration) every 5 seconds and fps is 93-97

**Comment by ssorgatem** [comment]
If it was a problem specific to haagch's builds, maybe this is not the right place to report it, since it could very well be a problem in the build environment and not DXVK itself

**Comment by julianovs** [comment]
version 0.51 does not work too
Unable to initialize render device

**Comment by julianovs** [comment]
I believe the settings are correct because it does not work when I get the 64 bit binaries from the latest haagch directory, however when I get the directory r1102.c17f4e2 it works
Yes my prefix is clean just being used by steam and my eso is inside the steam folder in the default folder steamapps/common and they are outside the prefix
My prefix is configured in windows 10 mode with the dlls d3d11 and dxgi for the steam in which I use to run eso

**Comment by ssorgatem** [comment]
Again, is this ESO-specific? Other D3D11 apps do run fine?

**Comment by julianovs** [comment]
far cry 5 run fine

**Comment by ssorgatem** [comment]
The game is 64-bit only.
The launcher is 32-bit, but it doesn't use D3D11 AFAIK.

**Comment by julianovs** [comment]
omg nvidia driver 396.24,2 fixed small lags/freezes  :)   game run great here !!!

only dxvk c17f4e2   work here, all the newer versions after that I'll get "Unable to initialize render device "

**Comment by ssorgatem** [comment]
So the first bad commit would be 368eea73108159a430f27f5bcef0e3dafcb0dd63 ?
Have you tried reverting it?

**Comment by julianovs** [comment]
I will try delete all my wine prefix, create new one and test again

**Comment by julianovs** [comment]
sorry, I was setting up the dlls in the wrong way
all DXVK versions work now !!!
the only problem is that the game has a small bottleneck every 5 seconds but fps is 85-92 :(
doitsujin, Do you have any idea what that might be?

**Comment by doitsujin** [comment]
Might be shader compilation, should go away. Also make sure to set your CPU governor to `performance`.

**Comment by kimamb** [comment]
@julianovs I have the same problem.

How did you solve it?

**Comment by julianovs** [comment]
@kimamb 
to correct bottlenecks every 5 seconds:
>>> do not run the game using the eso launcher
the eso launcher that causes this problem !!
run the game directly from eso64.exe
use the eso launcher only to check game updates !!

copy dxgi.dll and d3d11.dll to your eso client folder where eso64.exe is located
on steam it is located in: steam\steamapps\common\zenimax online\the elder scrolls online\game\client

**Comment by kimamb** [comment]
@julianovs Not that part. How did you get it to work at all? I get the same error as you did: "Unable to initialize render device"

**Comment by kimamb** [comment]
It launches fine when it's normal. But once I add the two .dll files, it gives me that error on startup.

**Comment by julianovs** [comment]
@kimamb 
if you copy the dlls inside wine prefix \ windows \ system32  you get the error "Unable to initialize render device"
you need copy dlls inside steam\steamapps\common\zenimax online\the elder scrolls online\game\client   and work at all  !! :)

open winecfg   set windows 10  and add to libraries  d3d11 (native windows)   and dxgi (native windows)

**Comment by kimamb** [comment]
Well, then we don't have the same problem. I'm starting to think it might
be a permission problem on the two files. I'll check when I get home.

**Comment by kimamb** [comment]
It wasn't just a permissions issue.

I wonder what the problem could be.

**Comment by kimamb** [comment]
Apparently, if I set Wine to use d3d11 and dxgi only natively. And I remove the files completely, it gives the same error. It's like it can't read the files.

**Comment by julianovs** [comment]
you should copy the two dlls into the folder of your eso, they should stay together with your eso64.exe
your winecfg should contain both dlls as "native windows" and "windows 10 mode"
on the wine staging tab uncheck all options

here I did this and all versions of dxvk worked

**Comment by julianovs** [comment]
here was giving  because I was not pasting the dlls inside the folder of my eso leaving them with the executable eso64.exe

**Comment by kimamb** [comment]
I don't seem to have the same problem as you had.

I'm starting to believe that my Wine version doesn't have vulkan support.

**Comment by julianovs** [comment]
use lutris

**Comment by kimamb** [comment]
I've never used it. I'll see if that'll work.

**Comment by julianovs** [comment]
I use linux mint 18.3 and download Wine Staging branch here using apt-get :
https://wiki.winehq.org/Ubuntu

And download latest binary DXVK dlls here:
https://haagch.frickel.club/files/dxvk/

I find this way easier !!
