### ISSUE TITLE
Civilization: Beyond Earth options menu crash

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3691]
Civ Beyond Earth crashes if once you get to the main menu you then press the options button. I have bisected this to not always be the case and that it seems to start with commit https://github.com/doitsujin/dxvk/commit/b746e1352b4c93b7d5f51d013f6aaef249c8aecd

While the logs makes it appear as a 32bit memory crash it acts a bit special in that the sequence above is the only way I've gotten it to crash in the little testing I've done so far. If i instead go in and play a game (starts fine without a crash) i can then access the options menu fine from there. Same if i from in game exit back to the main menu it will also work fine then.

### Software information
Sid Meier's Civilization: Beyond Earth

### System information
- GPU: 7900 xtx
- Driver: Few days old mesa-git
- Wine version: Proton Experimental
- DXVK version: https://github.com/doitsujin/dxvk/commit/b746e1352b4c93b7d5f51d013f6aaef249c8aecd and above

### Apitrace file(s)
Pending. Isn't cooperating on Linux at least so far.

Edit: Windows native trace https://drive.proton.me/urls/ZW6SBVVEE8#3YcjC5XZx662

### Log files
[CivilizationBE_DX11_dxgi.log](https://github.com/doitsujin/dxvk/files/12907847/CivilizationBE_DX11_dxgi.log)
[CivilizationBE_DX11_d3d11.log](https://github.com/doitsujin/dxvk/files/12907848/CivilizationBE_DX11_d3d11.log)
[CivilizationBE_DX11_d3d9.log](https://github.com/doitsujin/dxvk/files/12907849/CivilizationBE_DX11_d3d9.log)

**Comment by c3Ls1US** [comment]
@Blisto91 I have encountered a similar menu-crashing issue in another game using Proton 8.04.

This hasn't happened before and I would like to compare your logs in order to precisely discern whether the bug is a regression from DXVK or wine, so would you mind providing another debug log, perhaps by setting the `PROTON_LOG` environment variable?

**Comment by Blisto91** [comment]
[steam-65980.log](https://github.com/doitsujin/dxvk/files/13261158/steam-65980.log)

Note that the commit bisected above was in use before Proton 8.
The easiest way to find if it's a dxvk regression is just to shove a old dxvk version in to the new Proton. E.g the one from 7.0-6.

**Comment by Blisto91** [comment]
Added a Windows native trace
