### ISSUE TITLE
Discord Overlay doesn't work dxvk 2.3 x32

### ISSUE THREAD

**Issue by CiPHER-9932** [doitsujin/dxvk#3693]
Discord Overlay doesn't appears in game when using x32 d3d9.dll, but it works on x64 built, If possible in next update I request your team to make it work on x32 version.

For dxvk config make addition of Anti Aliasing for x32 built, which will help older games have better AA without relying on other tools like Reshade.

### Game information
Need for Speed Most Wanted 2005

### System information
- GPU: NVIDIA GTX 1650 4GB
- CPU: RYZEN 4600H
- RAM: 16GB DDR4
- DXVK version: 2.3

**Comment by Blisto91** [comment]
By your wording so you mean it works in 2.2?
I assume you are using Windows also?

**Comment by K0bin** [comment]
The Discord overlay is entirely outside of our control. There's nothing we can do to make that work.
