### ISSUE TITLE
[d3d11] - Red Faction Guerrilla Re-Mars-tered (667720) - Graphical aberrations are present when looking at the skybox.

### ISSUE THREAD

**Issue by ZereoX** [doitsujin/dxvk#3696]
Large black circles are visible in-game (incorrectly rendered lens flare?) upon looking up at the sky box in all outdoor areas of the game. Issue  can also be reproduced on Steam Deck, but is not present on Windows or WineD3D

|DXVK|WineD3D|
| ---- | ---- |
|![DXVK](https://github.com/doitsujin/dxvk/assets/761853/a72ff207-4804-4492-84f7-7f1f1037ccc7)|![WineD3D](https://github.com/doitsujin/dxvk/assets/761853/be3d1c43-1893-4677-9d97-2a7d2608b050)|

### Software information
[Red Faction Guerrilla Re-Mars-tered (667720)](https://store.steampowered.com/app/667720/Red_Faction_Guerrilla_ReMarstered/)

### System information
- GPU: RX 6800 / Steam Deck
- Driver: Mesa 23.3.0-devel ([16e1163651](https://gitlab.freedesktop.org/mesa/mesa/-/commit/16e1163651)) / SteamOS 3.5.1
- Wine version: Proton 8.0-4b
- DXVK version: DXVK-git ([f45911a](https://github.com/doitsujin/dxvk/commit/f45911a28f6e6184f82487e983b4a6af6923e61c)) / v2.3-5-g83dc4678df76578

### Apitrace file(s)
- Title launches directly to a crash reporter when attempting to trace on Linux or Windows.

### Log files
Link: [steam-667720.log](https://github.com/doitsujin/dxvk/files/13110195/steam-667720.log)

**Comment by HunterCZ122** [comment]
> is not present on Windows

Can you try it on Windows with DXVK?

Also, can you reproduce it with another Vulkan driver, such as AMDVLK or lavapipe, just to be sure it's not a RADV/ACO bug?

**Comment by Blisto91** [comment]
Can confirm the issue. Tested with both amdvlk and radv and a regression test back to dxvk 0.7, but was the same. Haven't found any configs to affect it either.
Can't get apitrace working either and the game crashes with validation layers.

**Comment by Riesi** [comment]
So the first capture that I managed to get was with dxvk, so the issue might be baked in.
Its made via gfxreconstruct, so not sure how useful it is anyway.
https://drive.google.com/file/d/1gzT_mdnG0pd7l-2v03J6dYsn234fBN58/view?usp=sharing

To replay one will need a gfxreconstruct build with d3d11 support from the CI. Its only a 64bit build, but replayer worked with my 32bit capture.
https://github.com/LunarG/gfxreconstruct/actions/runs/6253122914?pr=1267

How to replay:
https://github.com/LunarG/gfxreconstruct/blob/dev/USAGE_desktop_D3D12.md#replaying-api-calls

**Comment by K0bin** [comment]
Replaying the gfxreconstruct capture with Nvidias D3D11 driver reproduces the issue unless I rename gfxrecon-replay.exe to rfg.exe (the name of the game's exe).

So seems like Windows drivers ship a workaround for the game and the game itself is broken.
