### ISSUE TITLE
DXVK not loading any graphics devices

### ISSUE THREAD

**Issue by gkapaya** [doitsujin/dxvk#3697]
I was playing OMSI 2 using DXVK, and closed it down to view some tips on DXVK. One of which was to close GeForce Experience. After, DXVK woudn't load my GPU, it would load my integrated graphics (Intel(R) Iris(R) Xe Graphics). I then tried to reinstall Vulkan and the Nvidia drivers and now, it can't load any of them.

### Software information
OMSI 2

### System information
- GPU: NVIDIA GeForce RTX 4050 Laptop GPU
- Driver: Vulkan 1.3.260
- Wine version: N/A
- DXVK version: 2.3

[Omsi_d3d9.log](https://github.com/doitsujin/dxvk/files/13121779/Omsi_d3d9.log)

**Comment by HunterCZ122** [comment]
Reinstalling Vulkan by what? Vulkan drivers are provided by your GPU vendor. 
Please completely reinstall your GPU drivers.
Also for that GE tip, you just need to disable overlay, nothing else.

**Comment by gkapaya** [comment]
> Reinstalling Vulkan by what? Vulkan drivers are provided by your GPU vendor. Please completely reinstall your GPU drivers. Also for that GE tip, you just need to disable overlay, nothing else.

https://vulkan.lunarg.com/sdk/home
I meant the SDKs. I'll try reinstalling the GPU drivers. Thank you

**Comment by HunterCZ122** [comment]
> > Reinstalling Vulkan by what? Vulkan drivers are provided by your GPU vendor. Please completely reinstall your GPU drivers. Also for that GE tip, you just need to disable overlay, nothing else.
> 
> https://vulkan.lunarg.com/sdk/home I meant the SDKs. I'll try reinstalling the GPU drivers. Thank you

You don't need them. It's only meant for developers. The SDK probably replaced Vulkan Loader provided by GPU drivers which then broke it somehow. Just for precaution remove them too (preferable before reinstalling GPU drivers).

**Comment by gkapaya** [comment]
Removed SDK, Reinstalled both and to avail sadly. It looks like the GPU can't communicate with Vulkan. Should I try rolling them back?

**Comment by gkapaya** [comment]
I rolled the driver back to v537.72 and it works like a treat now, thanks for the help anyways:)
