### ISSUE TITLE
Diablo III characters dark/unlit

### ISSUE THREAD

**Issue by LeJimster** [doitsujin/dxvk#370]
All characters appear dark/unlit in the menus and in-game.

### Software information
Diablo III x64
Everything on high/1440p

### System information
- GPU: Vega 56
- Driver: Mesa 18.2.0-devel (git-26ddc4f9e1)
- Wine version: wine-staging-nine 3.8-1
- DXVK version: 20180513.516d7f0-1

### Apitrace file(s)
- I couldn't get a trace, not sure if I'm doing something wrong, sorry..

### Log files
`DXVK_LOG_LEVEL` was set to `debug`
- d3d11.log: [Diablo III64_d3d11.log](https://github.com/doitsujin/dxvk/files/1998894/Diablo.III64_d3d11.log)
- dxgi.log: [Diablo III64_dxgi.log](https://github.com/doitsujin/dxvk/files/1998895/Diablo.III64_dxgi.log)

### Screenshots
- DXVK:
![diii-broken_lighting](https://user-images.githubusercontent.com/35663469/39971616-30174be0-56f6-11e8-8db9-116a0d58dbe1.jpg)
- Wine:
![diii-correct_lighting](https://user-images.githubusercontent.com/35663469/39971554-1bb1c69a-56f5-11e8-9518-2751df4874bb.jpg)

**Comment by Kerrung** [comment]
@LeJimster, as I see it is in Wine that does not work the shadow mapping at all, but in works in DXVK.

**Comment by doitsujin** [comment]
I'm aware of this bug but I won't be able to fix it without an apitrace.

**Comment by LeJimster** [comment]
I try to get an apitrace for a few hours last night but it just makes small 2.5k trace files with unhandled exceptions in the log window.  Anybody got a clue how I can get a trace?

**Comment by Kerrung** [comment]
> I try to get an apitrace for a few hours last night but it just makes small 2.5k trace files with unhandled exceptions in the log window. Anybody got a clue how I can get a trace?

@LeJimster, try it on Windows, but you need to do this without using DXVK.

**Comment by LeJimster** [comment]
@Kerrung I tried it on windows, but it doesn't write any trace files at all!  I did manage to get a wine trace when I used `apitrace trace wine "Diablo III64.exe" -launch`, but I'm not sure thats helpful.

**Comment by Kerrung** [comment]
>I tried it on windows, but it doesn't write any trace files at all! I did manage to get a wine trace when I used apitrace trace wine "Diablo III64.exe" -launch, but I'm not sure thats helpful.

@LeJimster, in order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

**Comment by ZeroFault** [comment]
The problem with this game is that it tries to bind a VK_IMAGE_VIEW_TYPE_2D_ARRAY in to a slot that expects a VK_IMAGE_VIEW_TYPE_CUBE_ARRAY. Fixing this issue will require a large rewrite on how image views are handled and won't be fixing (for now) since we can't get a working apitrace yet.

**Comment by jarrard** [comment]
I use to have Diablo III, then blizzard revoked my copy because it was Russian with English language files (apparently I'm an illegal hacker). Otherwise I'd do a trace, then again I'm Nvidia hardware atm. 

What I would suggest is booting into windows and attempting a apitrace from there.

**Comment by doitsujin** [comment]
Please test if this branch fixes the issue: https://github.com/doitsujin/dxvk/tree/image-view-fixes

**Comment by LeJimster** [comment]
Tested that branch and it appears to have fixed the issue from the testing I've just done.  Many Thanks =)
