### ISSUE TITLE
Days Gone extremely low frame rate.

### ISSUE THREAD

**Issue by GurnBlanston** [doitsujin/dxvk#3700]
Name of the game, settings used etc.
Game: Days Gone from GOG.
Issue: Main screen and game play nets 0.2 FPS or lower, also GPU usage is approximately zero. 

    GPU: Radeon RX 6400
    Driver: Mesa 23.2.1
    Wine version: wine-8.18 (Staging)
    DXVK version: v2.3-12-gf45911a2

Apitrace file(s)
https://drive.google.com/file/d/1L3x3Ih_zvgw-YrFRqxPvhUgURemmXA3j/view?usp=sharing

**Comment by StepanBakshayev** [comment]
Almost same effect with

```
info:  Device properties:
info:    Device : Intel(R) Xe Graphics (TGL GT2)
info:    Driver : Intel open-source Mesa driver 23.2.1
info:  Game: DaysGone.exe
info:  DXVK: v2.3
wine-8.0 (Ubuntu 8.0~repack-4)
```

Menu fps stays on 20, but I don't expect from integrated graphics much. In game there is 0.2 fps.

**Comment by StepanBakshayev** [comment]
I used dxvk-2.0, dxvk-2.1, dxvk-2.2, dxvk-2.3 and got same result.

**Comment by GurnBlanston** [comment]
I also tried 1.9 (where it was supposed to be fixed), 1.92, 1.94, 2.00, 210, 220, 230 and 2.3.12.  

I hate to bug Phillip, he's made so much possible, I tried DXVK_ASYNC=1 (or something like that) and all the permutations I could derive from the proton page but to no avail.  

I always buy GOG whenever possible, of course if Steam has a Linux port that gets bought as well.  I can wait until this title is working again, preferably under GOG an I can certainly wait until Philip can take a peek, it's only a game after all.

**Comment by WinterSnowfall** [comment]
Strange. I had a go at it when it came out on GOG a few days ago and it was buttery smooth on my 3060, 60+ fps, no stutters whatsoever. Quite surprising for a UE4 title, in fact.

**Comment by jrugia** [comment]
Got the game a few days ago - GOG version too. Works fine for me on a low end machine.

GPU: RX 560 2GB
Wine: Staging 8.18
Mesa: 23.2.1

Performance about 35fps using a mix of low/medium, 1280x720 resolution.

**Comment by GurnBlanston** [comment]
So far I've tried it on the following cards: 5700g vega 8, 5600g vega 7, RX 6400, RX 7600, GTX 1650 and they all behaved the same, 0.2 FPS which makes me think my DXVK is somehow broken, I compiled it with mingw  12.2.1-3, however I still got the same thing when I used winetricks dxvk. 

On each test, I start with a fresh $WINEPREFIX, then do a symbolic link to 'GOG Games'.   All systems above had 32 GB of RAM except for the one with the GTX 1650 which had 16 GB.  This one is a real puzzler.

**Comment by Blisto91** [comment]
Does it work with wined3d?

**Comment by StepanBakshayev** [comment]
I have visual issues (it is a mess of purple color) with wine native rendering and it is slow as dxvk.

**Comment by adolfintel** [comment]
This is a very old issue, you need to use a version of wine that supports fsync, like proton or wine-ge

**Comment by WinterSnowfall** [comment]
@adolfintel Oh, yeah, that makes a lot of sense now. I don't use fsync, but rather the esync patches that come included with Wine Staging. @GurnBlanston Can you try running it with `WINEESYNC=1`?

**Comment by GurnBlanston** [comment]
@WinterSnowfall You got it, setting WINEESYNC=1 worked!  I was afraid I'd have to put training wheels on my motorcycle to play the game at 0.2 FPS!

It's still a little slow on my RX 6400 but now I have an excuse to use my RX 7600.

Thank you for the solution and thank you to everyone else who helped me resolve this issue.

**Comment by GurnBlanston** [comment]
Use WINEESYNC=1 when launching the game.

**Comment by Alexander88207** [comment]
Hello, what about platforms that dont have esync?

Reopening, happens on FreeBSD too.

Wine 10.0-rc2
AMD RX 6700 XT
DXVK 2.5.1
mesa-devel 24.3.b.1891

**Comment by mbriar** [comment]
DXVK can't do anything about a game running slow due to missing esync.

**Comment by Alexander88207** [comment]
I can understand that, but I still find it kind of strange.

For me this would be the first game that would be unplayable without esync.

That it then only runs under one frame... But then completly fine when i open the menu etc...

Scenes that I crawled through before, run better on the 2nd run, a similar behavior as with shader cache.
