### ISSUE TITLE
God Of War does not launch

### ISSUE THREAD

**Issue by pratved64** [doitsujin/dxvk#3701]
I've been trying to get GOW 4 to run on my pc using dxvk version 2.3 (latest at the time of post) to get around the "d3d_feature_level_11_1" issue. But on running the application, there is no window pop-up or anything, task manager shows the "God Of War" task at minimal load. I've tried several different versions of dxvk but none of them seem to work.

Hardware:
i5-7200U
8GB RAM
Nvidia 940MX

Software:
Windows 10 (64-bit)
Nvidia 542.92 graphics drivers

When I delete the dxgi.dll file (seen as solution on another post here), the window pops up but crashes after 10-15 seconds. Both log files are attached below:
[GoW_d3d11.log](https://github.com/doitsujin/dxvk/files/13196197/GoW_d3d11.log)

This log file is only created on versions 1.9.3 and older. It remains completely blank on version 2.3
[GoW_dxgi.log](https://github.com/doitsujin/dxvk/files/13196198/GoW_dxgi.log)

Any help is appreciated, thank you

**Comment by K0bin** [comment]
Why are you trying to use DXVK on Windows? It'll most likely be slower than the regular D3D11 driver anyway.

**Comment by mbriar** [comment]
> to get around the "d3d_feature_level_11_1" issue

You can try `DXVK_CONFIG="d3d11.maxFeatureLevel = 11_1`, but DXVK doesn't magically implement features on your GPU that the hardware doesn't support. If the game actually uses unsupported 11_1 features, it will not work.

**Comment by pratved64** [comment]
Oh I see, I'll try that and update. Thank you!

**Comment by Blisto91** [comment]
Can you also attach a d3d11 log file from where dxgi.dll is present. It needs it to work.

**Comment by pratved64** [comment]
[GoW_d3d11.log](https://github.com/doitsujin/dxvk/files/13196387/GoW_d3d11.log)
The d3d11 log file is always empty unless I delete the dxgi.dll file. It's always created when I run the application but never has anything written to it

**Comment by pratved64** [comment]
> > to get around the "d3d_feature_level_11_1" issue
> 
> You can try `DXVK_CONFIG="d3d11.maxFeatureLevel = 11_1"` as environment variable or the same option in a dxvk.conf file , but DXVK doesn't magically implement features on your GPU that the hardware doesn't support. If the game actually uses unsupported 11_1 features, it will not work.

I added the dxvk.conf file but the same issue persists, the application will not launch. Is it a hardware compatibility issue for sure then?

Here's the log file after adding the .conf file: [GoW_d3d11.log](https://github.com/doitsujin/dxvk/files/13196403/GoW_d3d11.log)

**Comment by Blisto91** [comment]
Odd.
Not sure why the dxgi log just goes in to a small loop either.
The dxgi.dll is needed. It will not work without even if it seems to get further.

There is likely something system or install specific going on, but not sure what.

**Comment by pratved64** [comment]
I messed with the default GPU settings and it seems to prefer the external card. Then again, I can't say for sure because the window won't load.

Thank you anyway though

**Comment by Ryusennin** [comment]
> Why are you trying to use DXVK on Windows? It'll most likely be slower than the regular D3D11 driver anyway.

Actually, no.

GOW 2018 on Windows still performs notoriously bad with AMD GPUs. DXVK not only boosts performance by around 10 fps, but also fixes the terrible frame pacing of that PC port (especially in the lake region). Not perfect, but much better than native DX11.

**Comment by aufkrawall** [comment]
23.20 branch AMD Windows drivers apparently have greatly improved performance for me in GoW with 6700 XT.

But yes, AMD D3D11 e.g. still can have more shader compile stutter than DXVK + graphics pipeline library enabled driver. Though amdvlk doesn't support it anyway...

**Comment by K0bin** [comment]
Anyway, God of War is known to work fine on Linux and we don't support Windows.
