### ISSUE TITLE
Guild Wars 2 Unable to Initialize 3D Renderer.

### ISSUE THREAD

**Issue by magnapeccatrix** [doitsujin/dxvk#3702]
Below is the error if you use x64 dvxk folder on gw2 64 bit but game seems to run if you copy paste x32 dxvk folder, why is that?
![image](https://github.com/doitsujin/dxvk/assets/15203877/42ec495c-5b25-435f-949f-380b5b839a58)

**Comment by Blisto91** [comment]
The first error is because the game doesn't like the dxvk d3d9 dll being next to the exe (at least on Windows). Only use d3d11 and dxgi.
The second is because the game is 64-bit so when you try to use the x32 version the game will start without dxvk

**Comment by magnapeccatrix** [comment]
thank you for your reply @Blisto91 but game does not launch and gives the error in my first post when I use d3d11 and dxgi as you say it should work.

**Comment by Blisto91** [comment]
Post the d3d11 and dxgi logs that appear

**Comment by magnapeccatrix** [comment]
[1029/142810.865:WARNING:spdy_session.cc(3541)] Received HEADERS for invalid stream 3

[Gw2-64_d3d11.log](https://github.com/doitsujin/dxvk/files/13197909/Gw2-64_d3d11.log)

**Comment by Blisto91** [comment]
> warn:  D3D11InternalCreateDevice: Adapter is not a DXVK adapter

This line means it's not using dxvk's dxgi.
Make sure both `d3d11.dll` and `dxgi.dll` (x64 versions) are located in the main game folder where `Gw2-64.exe` is also found.

**Comment by magnapeccatrix** [comment]
![image](https://github.com/doitsujin/dxvk/assets/15203877/66a9744f-5f41-48af-a042-db54be2414a7)
they are in the same folder as gw2 64 exe

**Comment by Blisto91** [comment]
Delete and re extract them if you haven't already tried. To make sure they are both same version

**Comment by magnapeccatrix** [comment]
> Delete and re extract them if you haven't already tried. To make sure they are both same version

thanks but I already fresh copy pasted a few times and from multiple downloads from github. Game detects and properly works with any other .dll addons such arcdps but when I remove all them and place dvxk it does not work at all. I don't think game does not recognize the dvxk, it actually loads it thus leading this error about 3d renderer otherwise game loads just fine upon removing the dvxk dlls. 

if anyone knows what is the problem here, please let us know, thank you.

**Comment by K0bin** [comment]
To quote the wiki article for Windows: 

> Some games fail to load all required DXVK DLLs even when they are correctly placed next to the game's executable. Applicatons may choose to only load DLLs from the system's System32 directory rather than the exxecutable path, in which case the game will either crash or continue using the native D3D implementation. A common scenario that causes a crash is when the game loads dxgi.dll from System32, but then uses the d3d11.dll provided by DXVK.

**Comment by Blisto91** [comment]
Don't know what the issue is then. Tested it on Windows yesterday.

**Comment by magnapeccatrix** [comment]
> To quote the wiki article for Windows:
> 
> > Some games fail to load all required DXVK DLLs even when they are correctly placed next to the game's executable. Applicatons may choose to only load DLLs from the system's System32 directory rather than the exxecutable path, in which case the game will either crash or continue using the native D3D implementation. A common scenario that causes a crash is when the game loads dxgi.dll from System32, but then uses the d3d11.dll provided by DXVK.

Guild Wars 2 is known for able to run .dll from its own game folder. There is no problem in here.

**Comment by K0bin** [comment]
The game is known to work on Linux and we don't really support Windows.

**Comment by Vframe101** [comment]
writing here in case someone has same problem, the issue indeed is windows forcing to load native dxgi.dll from system32, due to security filters on unknown dll files

the way to force it to load the one from dxvk, is right click dxgi.dll> go to properties>general tab> checkmark "unblock" click apply

this basically tells windows to trust dll file to be loaded and eliminated all errors for me, explains why I didnt have this issue with windows 10 ever...
