### ISSUE TITLE
F.I.S.T. issue with d3d11.samplerAnisotropy adding a strange tonemap (Win)

### ISSUE THREAD

**Issue by Hexaae** [doitsujin/dxvk#3704]
### Software information
Game: F.I.S.T. Forged in Shadow Torch (Epic, PC Windows 11 22H2) DX11

### System information
- GPU: 1070 8GB
- Driver: 537.58 SD WHQL (Windows 11)
- DXVK version: 2.3

### Log files
[https://paste.sh/DH0Amqgu#5NnSAes-NpaslZRsBGvyrWU7](https://paste.sh/DH0Amqgu#5NnSAes-NpaslZRsBGvyrWU7)

The issue is that when I force anisotropic filter from dxvk.conf, e.g. "**d3d11.samplerAnisotropy=8**" I get this strange pink tonemapping effect in this game: https://imgsli.com/MjE3MDY4
Looks like a kind of bit depth issue...

**Comment by K0bin** [comment]
That option is a hack. If it doesn't work with a game, don't use it. We don't really want to add a bunch of heuristics on top of it to avoid cases like this.

**Comment by Hexaae** [comment]
Mmmh... Do you know other solutions to force AF in a promoted dx11->vk game then? I've set AFx16 from NVidia Control Panel but it seems to work only in DX mode. When dxvk is enabled this game ignores those settings (is this a bug, shouldn't work for VK games too?).

**Comment by K0bin** [comment]
> Ignoring that conf hack option, I don't understand why the game does not apply forced AF (through Engine.ini or NVidia CP) when promoted to Vulkan with dxvk. Of course both work when the game runs in DX11/12.

Forcing it through Nvidia CP is quite similar to what DXVK does with the config option, except that Nvidia probably has a bunch of heuristics to make sure it's only applied to textures that are used to *texture* geometry. It's likely that they simply didn't implement this hack for Vulkan. No idea whats going on with the UE4 config option. If that works for D3D11, it should also work when DXVK is involved.

**Comment by doitsujin** [comment]
> That option is a hack. If it doesn't work with a game, don't use it

This.
