### ISSUE TITLE
GTA IV - [FusionFix dev team request] PostFX corruption/inconsistency with D3D9 using FusionFix

### ISSUE THREAD

**Issue by valentyn-l** [doitsujin/dxvk#3708]
I will try to describe the issue as accurately and succinctly as possible.

A new version of FusionFix (a mod which restores/fixes many graphical feature/errors which were present in the PC version) was recently released which restores the Depth of Field shader to the game. Members of the mod's development community (including myself) have noticed graphical inconsistencies with the original renderer when running the game under DXVK 2.3.

These inconsistencies can be described in the following ways:

1. Bright outlines around distant buildings, and player character when falling through map;
2. Corrupted UVs in post processing, such as fog and PostFX.

Please note the distant blurred buildings in the background that exhibit bright outlines around them, as well as some of the trees just below them:

 D3D9 (original renderer)
![D3D9](https://github.com/doitsujin/dxvk/assets/60371520/45d6ce0a-e0e1-46af-893a-e8e88e180cdc) 

DXVK
![DXVK](https://github.com/doitsujin/dxvk/assets/60371520/6f8449a3-79f1-4849-856c-dc734e48e24f)

### Software information
Grand Theft Auto IV (GTA IV) - The Complete Edition

### System information
- GPU: RTX 3080 Ti 
- Driver: 545.84
- Wine version: Windows 11 (Linux to be tested)
- DXVK version: 2.3

### Apitrace file(s)
- https://drive.google.com/file/d/1wAdpJ9YAms_M6iLKVvnQ7hEHU67Qfc7g/view?usp=sharing

### Additional links:

[FusionFix Git Page](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix)

Save file for testing, at location/time-of-day in pics above: [SGTA400.zip](https://github.com/doitsujin/dxvk/files/13230407/SGTA400.zip)

Please don't hesitate to contact myself or the project's team for assistance. We would love to help fix this issue. 😊

**Comment by K0bin** [comment]
Can you make an apitrace with the mod? There's a guide for how to do that in our wiki.

**Comment by valentyn-l** [comment]
> Can you make an apitrace with the mod? There's a guide for how to do that in our wiki.

Absolutely. Here's the link: https://drive.google.com/file/d/1wAdpJ9YAms_M6iLKVvnQ7hEHU67Qfc7g/view?usp=sharing

**Comment by Blisto91** [comment]
Bisected to have regressed with commit https://github.com/doitsujin/dxvk/commit/65635b23c1e8575362722c99e6ffdf9d9df64116

**Comment by valentyn-l** [comment]
Another picture displaying the issue:

![20231105132139_1](https://github.com/doitsujin/dxvk/assets/60371520/2f240d9f-8a19-47b1-8c94-8ee1dd008546)

As you can see, when falling through the map the player character has a bright outline around them which is absent in D3D9.

**Comment by recore67** [comment]
seems to me its a transparency issue due to altering with the shaders?

**Comment by RecklessGlue540** [comment]
> seems to me its a transparency issue that i assume FusionFix alters with the shaders?

It's a regression that also happens on a vanilla game. It's not related to FusionFix.

**Comment by Markie98** [comment]
Why isn't this fix in DXVK already? Considering it had a new release about a month ago and the issue has been here for months now. Not complaining just wondering.

**Comment by valentyn-l** [comment]
> Because it breaks other games.

They literally have the ability to isolate code to certain executables like for eg:

if exe = GTAIV.exe then execute "x" fix

**Comment by Blisto91** [comment]
K0bin is a dev fwiw so he knows.

**Comment by Parallellines0451** [comment]
The PC version of GTA IV mistakenly has the depth buffer sampler used by fog set to use linear filtering, whereas consoles correctly use point. Reverting that change fixes the issue without having to do anything on DXVK's side, so this issue may be closed.

![Screenshot 2024-06-23 002726](https://github.com/doitsujin/dxvk/assets/133058741/526a92e0-0e14-4d1d-a1a2-f6f0e078dde0)
![Screenshot 2024-06-23 002402](https://github.com/doitsujin/dxvk/assets/133058741/f70837b2-e194-43e4-a1d4-3daaf6ab2116)

**Comment by K0bin** [comment]
Thanks for the heads up.
