### ISSUE TITLE
Invalid Vulkan usage for indirect draws with Age of Darkness

### ISSUE THREAD

**Issue by hakzsam** [doitsujin/dxvk#3709]
See https://gitlab.freedesktop.org/mesa/mesa/-/issues/8764 for more information but DXVK (tested with v2.3) generates invalid Vulkan usage for that game. Indirect draw offset can be ~0  (this should be a multiple of 4) and this hangs with RADV.

This should probably be "fixed" in DXVK.

**Comment by doitsujin** [comment]
Does 2ed1778df9ea5d81fff22f76f125b08995454847 fix the issue? This really sounds like a rather absurd game bug.
