### ISSUE TITLE
BlitzFX (Witcher 3 mod) only works with old version of DXVK, on Linux, and has major graphical issues.

### ISSUE THREAD

**Issue by t0mtee** [doitsujin/dxvk#3711]
Please describe your issue as accurately as possible.
There is a Witcher 3 mod called [BlitzFX](https://www.nexusmods.com/witcher3/mods/6447/) that greatly improves visuals, however the game doesn't load with DXVK, even when following the instructions in the comments. This may be an issue with the mod, however it's been seemingly discontinued as the dev is working on a seperate mod for the Next-Gen update, so it'd be great if it could maybe be fixed on DXVK's end.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Witcher 3 1.32, BlitzFX installed. Tried the ASI loader method and the Debug Console method.

### System information
- GPU: RX 6700 XT
- Driver: 23.8.1 
- DXVK version: 2.3

### Apitrace file(s)
[Mediafire Download](https://www.mediafire.com/file/6x5wlj53a6o6gl0/apitrace.zip/file)

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
[logs.zip](https://github.com/doitsujin/dxvk/files/13257879/logs.zip)

**Comment by Blisto91** [comment]
Testing on Linux through Proton and just using the regular installation instructions i am able to get the game launching with the mod up until commit https://github.com/doitsujin/dxvk/commit/6d72bc94f45617f707fd135d28292987315bac80
By launching i mean that i can get to main menu and also use the mod menu fine, but it will crash shortly after starting to play in the actual game.

**Comment by OsoaGH** [comment]
I just tried this on Windows, using DXVK release 1.8.1 (so before that commit), and the same error occured.

**Comment by Blisto91** [comment]
From what i can tell using this together with the `Ultimate ASI Loader` method will make it also load the `d3d11.dll` in the system32 directory which is why that doesn't work on Windows because it might hook on to the wrong one.

On Linux i can recreate a crash in the same place with dxvk 1.8.1 by making Proton use wined3d and then placing dxvk dll's next to exe with a added native override. The Proton log indicate that both dxgi and d3d11 from the exe folder gets loaded but also d3d11 from system32. 
If i don't use wined3d and have dxvk 1.8.1 both in my wine system32 (don't do this on Windows) and also next to exe it will start correctly but the mod won't work. It only works if i delete the dxvk DLLs next to the exe so everything uses the system32 DLLs (again don't put dxvk in there on Windows).  As said i am thinking this indicates it hooks on to the wrong thing when dxvk is placed next to the exe.

That is something dxvk can't do anything about and is one of the reasons why Windows can't be properly supported.


Why the other method described doesn't work i don't know.

**Comment by OsoaGH** [comment]
Hmm that's interesting... honestly just gives me another reason to switch to Linux.
Is there no workaround on Windows? Absolutely none?
Furthermore, do you think the issue with the regressed commit can be fixed so outdated versions don't have to be used?

**Comment by Blisto91** [comment]
> Hmm that's interesting... honestly just gives me another reason to switch to Linux.

Well it doesn't seem to be all sunshine and rainbows on Linux either. I have to turn off Nvidia hairworks for it to even start with the mod. 
The TAA option seems broken and there are some other graphical issues. At least with 1.8.1.

> Is there no workaround on Windows? Absolutely none?

I do not know as i haven't really messed with mixing translation layers or similar and such mods and tools on Windows. At least not from the official side of dxvk there isn't.

> Furthermore, do you think the issue with the regressed commit can be fixed so outdated versions don't have to be used?

I am not a dev so i can't answer that specifically. I assume so, but i don't have any technical insight on the matter. If i were you I'd just play the native game on Windows if the mod is important to you.

**Comment by OsoaGH** [comment]
So ideally, DXVK will be updated to fix the regression in the commit, and we can then see if the graphical issues persist.

However, this is just a mod for an outdated version of a game. I can completely understand if this issue never gets updated, or the issues fixed. Thanks a bunch for the help and explanation so far.

**Comment by t0mtee** [comment]
Hello again. Just want to check if there's any chance of this issue being looked into - I understand it's very niche and thus don't want to place any pressure on anyone to try resolve it.

**Comment by t0mtee** [comment]
I've reinstalled Linux lately and have since gotten around to trying Blitz with DXVK 1.8.1.
My experience was that on 1.8.1, the game could be loaded and played and it all worked (including TAA and HairWorks), but it was a bit iffy getting there.

![image](https://github.com/user-attachments/assets/48d5b90d-3787-4409-b054-0a00724f095f)
Here is the game with Blitz (with TAA) loaded. To get here, the game has to have been launched at least once without the ASI loader installed, and then once again with the ASI loader and Blitz installed so TAA can be disabled, and then once more so that the game loads and TAA can be enabled.

In my experience, TAA had to be disabled at boot to avoid huge issues, such as this:
![image](https://github.com/user-attachments/assets/e123a3d5-9915-4dc7-9632-6ae2ce02e8b0)

I think this is really promising. Even back on 1.8.1, Blitz WAS working - even if getting there was dodgy. With any luck, the only issue preventing Blitz from working on modern DXVK versions is the crash when starting the game.

**Comment by t0mtee** [comment]
The creator of BlitzFX made a surprise return and updated the mod - which now works perfectly on DXVK (at least on Linux) after adding WINEDLLOVERRIDES="D3D11=n,b". No need for the ASI loader or anything like that, it's basically plug and play.
Happy to close this :)
![image](https://github.com/user-attachments/assets/f9fb2f9e-2b19-4bf2-a399-7b7b06eaa08f)
