### ISSUE TITLE
Heroes of the storm missing elements

### ISSUE THREAD

**Issue by Amosar** [doitsujin/dxvk#372]
Some spells have no picture and the profile picture is not displayed if the player is not in-game. The problem occurs with wine directx 11 dll too.
Example with dxvk:
![dxvk+hots+gazlowe](https://user-images.githubusercontent.com/14032531/39976496-ef4e718e-572b-11e8-8396-4e6458cc032a.png)

How it look on windows or with directx 9 on wine:
![windows+hots+gazlowe](https://user-images.githubusercontent.com/14032531/39976474-e0d862f4-572b-11e8-9cb9-39742fecaa41.png)

### Software information
Heroes of the storm

### System information
- GPU: Nvidia GTX970M
- Driver: 396.24
- Wine version: 3.8-staging
- DXVK version:  https://github.com/doitsujin/dxvk/commit/a90c2843a756b05043682d69de0aa8d8d5afd5a5

### Apitrace file(s)
- https://drive.google.com/file/d/1qwrTllvQfafz0UY5XQfIM2AZJ5_fAbdM/view?usp=sharing

### Log files
- d3d11.log: https://pastebin.com/3vfbqj89
- dxgi.log: https://pastebin.com/W4F5cVrJ

**Comment by doitsujin** [comment]
I tried replaying your trace on Windows with native D3D11 but there just are no such elements. Did you record the trace with Wine/DXVK or on Windows?

**Comment by Amosar** [comment]
Sorry, I opened this problem too quickly
It's a wine problem, not a dxvk problem.

I'm so sorry because someone sent the fix on a wine problem and I did not try it because I thought it was related to another problem.
https://bugs.winehq.org/show_bug.cgi?id=43775

**Comment by simonvanderveldt** [comment]
@Amosar Which dll do you mean exactly? I've got no icons for the majority of spells and talents as well after the latest update

**Comment by MeissnerEffect** [comment]
@simonvanderveldt 

```
Copy /${YOURFULLPATH}//Heroes of the Storm/Support64/d3dcompiler_47.dll to ~/.HotSPREFIX/drive_c/windows/system32/ f

Copy /${YOURFULLPATH}/Heroes of the Storm/Support64/d3dx11_42.dll to ~/.HotSPREFIX/drive_c/windows/system32
```

**Comment by simonvanderveldt** [comment]
@MeissnerEffect copying `d3dx11_42.dll` seems to have done the trick :) Thanks!
