### ISSUE TITLE
[Feature request] Support mining cards.

### ISSUE THREAD

**Issue by Allegorii** [doitsujin/dxvk#3720]
Recently I read this article:https://niconiconi.neocities.org/tech-notes/nvidia-cmp-170hx-review/ it seems that CMP series mining cards only limit the fp32 performance of fma, is it possible to make dxvk output fma-less instructions to take advantage of the gaming performance of the mining card.

**Comment by doitsujin** [comment]
DXVK is a translation layer that uses Vulkan with SPIR-V shaders, it's not a GPU driver that needs to deal with weird quirks like this.

TL;DR: No idea what the situation here is, but we have no agency over it anyway. If Nvidia does not provide a compliant Vulkan implementation for these cards with some sort of PRIME support for presentation, DXVK cannot work on them. If the driver does provide these features, it'll work fine out of the box.
