### ISSUE TITLE
[d3d9] Medieval 2 black loading screen in windowed mode with dxvk

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3724]
The game can still have black loading screens with dxvk when it is run in [windowed mode](https://www.pcgamingwiki.com/wiki/Medieval_II:_Total_War#Video). Doesn't happen without dxvk (tested on Windows).

### Software information
Total War Medieval 2.
[windowed mode](https://www.pcgamingwiki.com/wiki/Medieval_II:_Total_War#Video)

### System information
- GPU: RX 6800
- Driver: Adrenalin 23.11.1. Haven't tested Linux yet.
- DXVK version: master

### Apitrace file(s)
https://drive.proton.me/urls/613B5Y9KWG#53STJVAgRxn6
One made with Windows native and one with Windows dxvk as it is baked in

### Log files
[medieval2_d3d9.log](https://github.com/doitsujin/dxvk/files/13400452/medieval2_d3d9.log)

**Comment by K0bin** [comment]
Does `d3d9.deviceLossOnFocusLoss = True` help?

**Comment by K0bin** [comment]
There's likely something wrong with GetFrontBufferData here.
