### ISSUE TITLE
[REQUEST] Add Toggle Option for Backface Culling On/Off in dxvk.conf

### ISSUE THREAD

**Issue by Mrblubb** [doitsujin/dxvk#3728]
Few older games on PC render incorrectly (eg. GUN ) and some textures appear transparent when overlapped with another object. This is because of backface culling with D3D9. An flag to toggle it off with dxvk might fix this issue.

**Comment by WinterSnowfall** [comment]
d3d8/9 allow applications to control back face culling via [a render state](https://learn.microsoft.com/en-us/windows/win32/direct3d9/d3dcull). Adding a toggle for it makes no sense, it should seamlessly work much, like on native drivers.

If you've noticed a particular issue with a game (e.g. GUN) please fill in the issue template and attach logs and a trace.

**Comment by K0bin** [comment]
What youre describing doesn't even sound like backface culling.

**Comment by Mrblubb** [comment]
Yes it is! The game refuse to render inside polygons of any object and make it transparent. It is exactly what this article shows : https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Backface-Cull-Object-renders-transparent-when-facing-away-from-view.html

**Comment by WinterSnowfall** [comment]
@Mrblubb Like @K0bin mentioned, I doubt it will do anything, but since you sound like someone who wants to try it anyway, plopping a `rs[D3DRS_CULLMODE] = D3DCULL_NONE;` instead of [this line](https://github.com/doitsujin/dxvk/blob/1b31aa5dbca0749d0737cff02043acb061332fb6/src/d3d9/d3d9_device.cpp#L7388) should do the trick, assuming the game doesn't mess with this render state itself.

**Comment by WinterSnowfall** [comment]
> Or could you please be kind enough to provide me just this version please!!

The repo has a GitHub Actions builder that comes along with the project once you fork it, but sure, here's a build with the above change: https://github.com/WinterSnowfall/dxvk/suites/18696011657/artifacts/1088163286

Remember that this is incorrect behavior d3d-wise, even if it somehow works for this game.

**Comment by WinterSnowfall** [comment]
> But I wonder what could that issue be actually if not backface culling anyways??

No idea. I have the game on PC, so could check what's going on, but it's highly likely it's just a game bug (ergo, something they messed up while porting the game over from consoles).

**Comment by Mrblubb** [comment]
Yeah probably that's the case because I just watched some xbox gameplay of if and it's exactly the same there too. Only doesn't happen in the ps2 version, and PC version is xbox port. 
Something unrelated but do you know when a game doesn't apply normal map + its alpha spec channel ingame ??
It's this game Dead to Rights (old classic) and it has all the proper normal maps with proper alpha channels but ingame no specular is shown despite texmod actually showing it's loading it.
I'm actually a small modder and make texture mods and simple fixes :)
