### ISSUE TITLE
World Of Warcraft - Worked only on dx9 mode

### ISSUE THREAD

**Issue by spirtirs** [doitsujin/dxvk#3729]
### Software information
when starting a private server for the World of Warcraft game using DXVK - it only works in D3D9 mode. He doesn't want to work with DX11 code and writes an error. Or the source starts DX9 if it sees the file to DX9
btw. Thats game client used this server https://pandawow.me/files/PandaWoW%205.4.8.torrent

### System information
- GPU: RX 460
- Driver: 31.0.23001.3004
- Wine version: 
- DXVK version: 2.3

### Apitrace file(s)
https://drive.google.com/file/d/1aV3UYxkFt0jVVKKct7ma0DUln-ZA-Yo3/view?usp=sharing

### Log files
https://dropmefiles.com.ua/en/kmQAV8xMH

**Comment by Blisto91** [comment]
Not 100% sure what is going on with it besides it seemingly is trying to load the wrong dxgi (not dxvks) file at some point on Windows. Tho i can't recreate that on Linux as it seems fine with them being next to the exe there, but maybe that could be a Wine vs Windows implementation detail i don't know about.
Either way i can confirm the clients d3d11 doesn't work on Windows with dxvk, but it seems to work fine on Linux with Proton.

**Comment by Blisto91** [comment]
Checked with process explorer and it seems to be the case that it loads dxgi from Windows system folder yes

**Comment by K0bin** [comment]
Please read the Windows page in the DXVK wiki for more information about why it doesn't work.
