### ISSUE TITLE
(d3d error 0x80004005) Mortal Kombat Komplete Edition Crashes on Launch

### ISSUE THREAD

**Issue by KutaG59** [doitsujin/dxvk#3730]
Please describe your issue as accurately as possible.
Mortal Kombat Komplete edition cannot launch due to a constant error (in title) even with all required components installed on my system.

### Software information
Game: Mortal Kombat Komplete Edition.
Platform: Steam / Proton Used: Experimental/Most recent (8.0.4)
Launch Options: None / Mods used: None / Configs made: None

### System information
- GPU: RX 6600 XT
- Driver: AMD Radeon RX 6600 XT (navi23, LLVM 16.0.6, DRM 3.54, 6.5.12-300.fc39.x86_64) / 4.6 Mesa 23.2.1
- Wine version: Wine-8.19 (staging) [also tested on stable]
- DXVK version: 2.3

### Apitrace file(s)
- Put a link here: **Doesnt open after adding dll files???? no idea why, will upload if able to get them**

### Log files
Please attach Proton or Wine logs as a text file:
- https://paste.gloriouseggroll.tv/?6763179eadd0d5a3#7uUrM11sBQbfc3tQArcMDoU6TeQwnyEGUu1iDq6mMwFT (Proton Log)  [Mega](https://mega.nz/file/04gxAaiK#TjHaJFauldYdmebtep9d8ff_FLKgnvckhayyUaVI1xM) for log in case link expires 
- https://paste.gloriouseggroll.tv/?f5c04ec5f0f518df#Fs5oG71Y4EM3Gxjm1hyxiwQSDsHzG8xPz8WpcAMJbRhW (WINE FILE) [game doesnt even open with wine, awesome] [Mega](https://mega.nz/file/d4QHkIJb#UTwT6qMCIB0ZKQu4pdRRK6pjzC_S2EfDQ1yL9Q3zVJI) for log in case link expires

**Comment by Blisto91** [comment]
Hi there.
I've not been able to reproduce this issue. Testing the Steam version with both Proton experimental and 7.0-6 i am able to get ingame fine, also when using 2.3 specifically. Same when i use wined3d and Wines builtin d3dcompiler + d3dx9
