### ISSUE TITLE
Dxvk native cross compile fails for 32-bit

### ISSUE THREAD

**Issue by tjhexf** [doitsujin/dxvk#3731]
### Software information
Fedora 39 Workstation Edition
gcc 13.2.1

build log:
[log.txt](https://github.com/doitsujin/dxvk/files/13517227/log.txt)

**Comment by Blisto91** [comment]
@tjhexf Are you still having issues compiling?

**Comment by Blisto91** [comment]
@tjhexf Friendly ping
