### ISSUE TITLE
Need for Speed: The Run - in-game information messages are blank

### ISSUE THREAD

**Issue by Yar4e** [doitsujin/dxvk#3732]
In-game information messages are blank in this game. You can see them a lot in the beginning of the game or when you failed the race.
How it looks now:
![2023-11-30_22-58](https://github.com/doitsujin/dxvk/assets/12473584/5b1f11f3-2226-46bd-8457-c32a9c6d7179)

How it must looks like:
![2023-11-30_23-22](https://github.com/doitsujin/dxvk/assets/12473584/f9962abf-892d-41d0-bb1a-09721727ed8c)

### Software information
Need for Speed: The Run, ultra settings, vsync on

### System information
- GPU: AMD 780M (GFX1103_R1)
- Driver: Mesa 23.2.1 and 23.3.0
- Wine version: Proton Experimental and GE Proton 8-22
- DXVK version: 91f7f43c35f240231c9e5efd0b24a27da5c16a8a dxvk (v2.3-19-g91f7f43c)

### Apitrace file(s)
https://drive.google.com/file/d/1TOpTObWNUOKK51tbJVFvfVIhYUiu3TxM/view?usp=drive_link
### Log files
[steam-14818695545664569344.log.zip](https://github.com/doitsujin/dxvk/files/13517994/steam-14818695545664569344.log.zip)

**Comment by K0bin** [comment]
Please provide an apitrace.

**Comment by Blisto91** [comment]
@Yar4e The issue seems to be baked in to the trace.
Could you try installing the Windows version of `d3dcompiler_43` and `d3dcompiler_47` into your prefix with protontricks/winetricks? I see a whole bunch of messages from the Wine ones in your log. If that doesn't help then try with `d3dx11_43` also.

**Comment by Yar4e** [comment]
@Blisto91 Installed `d3dcompiler_43` and `d3dcompiler_47` using protontricks - this doesn't help. Installing `d3dx11_43` doesn't help either..

**Comment by Blisto91** [comment]
Does it show correctly with wined3d?

**Comment by Yar4e** [comment]
If 'WINEDLLOVERRIDES="*d3d9,*d3d10,*d3d10_1,*d3d10core,*d3d11,*dxgi=b" %command%' is the correct way to run app with wined3d from Steam then wined3d show the same incorrect message window in this game.. So it's not a DXVK problem but WINE. How to make sure app use wined3d not dxvk?

**Comment by Blisto91** [comment]
In proton you need to do `PROTON_USE_WINED3D=1` the Proton script might overrule you otherwise (at least used to).
So `PROTON_USE_WINED3D=1 %command%` in full

**Comment by Yar4e** [comment]
Yes it's not DXVK bug. Using wined3d shows the same problem..

**Comment by casasfernando** [comment]
@Yar4e did you try to report this bug to Wine? I’m having the same problem and I tried a few searches there without success.

**Comment by Yar4e** [comment]
> [@Yar4e](https://github.com/Yar4e) did you try to report this bug to Wine? I’m having the same problem and I tried a few searches there without success.

Nope, I have an excuse: I can't remember the password from bugs.winehq.org)

**Comment by casasfernando** [comment]
Ok. I may report it myself. It’s kind of a weird bug, no obvious Wine errors.
Thanks
