### ISSUE TITLE
Forcing NVidia specific features in Just Cause 2 with DXVK

### ISSUE THREAD

**Issue by KainXVIII** [doitsujin/dxvk#3733]
While DXVK fixes various crashes issues with this game, but also i can't enable Bokeh Filter and GPU water simulation anymore (they just disappear in graphics settings)

### Software information
Just Cause 2

### System information
- GPU: GTX 970
- Driver: 537.58
- DXVK version: 2,3
- Windows 10

**Comment by Blisto91** [comment]
I believe this needs Nvapi to show and so we won't be able to get it working on Windows with dxvk.
Not able to check at the moment.

**Comment by Blisto91** [comment]
It turns out that this doesn't actually work on Linux either even with nvapi. But one of the dxvk-nvapi devs looked at a log and there is a function without implementation that could very likely be the cause.
So this indeed seems like it needs Nvapi and therefor wont work on Windows.

**Comment by K0bin** [comment]
Those features are never gonna work with DXVK on Windows.

**Comment by K0bin** [comment]
Apparently there are no public headers for the missing NvAPI functions. So it's not gonna be implemented for Linux either.
