### ISSUE TITLE
UPlay won't launch when DXVK is applied

### ISSUE THREAD

**Issue by afettouhi** [doitsujin/dxvk#374]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
I am running uplay on my 64 bit Arch Linux install. I was testing out uplay wine (installed via winetricks in a 64 bit PREFIX). I wanted to test Watch Dogs which I own on uplay. Installing uplay and downloading Watch Dogs went fine but when I applied dxvk uplay would launch anymore. I just get this error:

[af@andre ~]$ env WINEPREFIX="/home/af/.local/share/wineprefixes/uplay" /usr/bin/wine C:\\Program\ Files\ \(x86\)\\Ubisoft\\Ubisoft\ Game\ Launcher\\Uplay.exe
000b:fixme:winediag:start_process Wine Staging 3.8 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
[af@andre ~]$ 002f:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files (x86)\\Ubisoft\\Ubisoft Game Launcher\\libcef.dll") not found
002f:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files (x86)\\Ubisoft\\Ubisoft Game Launcher\\libcef.dll") not found
002f:err:module:import_dll Library libcef.dll (which is needed by L"C:\\Program Files (x86)\\Ubisoft\\Ubisoft Game Launcher\\upc.exe") not found
002f:err:module:attach_dlls Importing dlls for L"C:\\Program Files (x86)\\Ubisoft\\Ubisoft Game Launcher\\upc.exe" failed, status c0000135

### System information
- GPU: Nvidia 1080 GTX
- Driver: 396.24
- Wine version: 3.8-staging
- DXVK version: 0.51

**Comment by afettouhi** [comment]
I installed dxvk into my wine PREFIX this way:

WINEARCH=win64 WINEPREFIX=~/.local/share/wineprefixes/uplay setup_dxvk64

**Comment by doitsujin** [comment]
You need to set up the 32-bit DXVK DLLs as well, with that, Uplay should work (at least it does on my end).

If that doesn't work, you can always create a per-application DLL override in winecfg, setting `d3d11.dll` and `dxgi.dll` to **builtin** for Uplay.exe.

**Comment by doitsujin** [comment]
Yep.

**Comment by afettouhi** [comment]
Well I tried to add the 32-bit dlls as well. Still will not launch. Not it outputs

000b:fixme:winediag:start_process Wine Staging 3.8 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
[af@andre ~]$ 002e:fixme:kerberos:kerberos_SpInstanceInit 65536,0x7da103a0,(nil): stub
002e:fixme:d3d:wined3d_dxtn_init Wine cannot find the txc_dxtn library, DXTn software support unavailable.
002e:err:vulkan:wine_vk_init Failed to load libvulkan.so.1
002e:err:vulkan:wine_vk_init Failed to load Wine graphics driver supporting Vulkan.
002e:err:module:attach_dlls "winevulkan.dll" failed to initialize, aborting
002e:err:module:attach_dlls Initializing dlls for L"C:\\Program Files (x86)\\Ubisoft\\Ubisoft Game Launcher\\upc.exe" failed, status c0000142

**Comment by Altosk** [comment]
do u have 32 bit vulkan drivers installed?

**Comment by afettouhi** [comment]
No didn't. I have now and uplay starts. Many thanks!
