### ISSUE TITLE
Persona 5 Royal menu flickering

### ISSUE THREAD

**Issue by BuyMyMojo** [doitsujin/dxvk#3745]
When opening menus such as the graphics options or the phone messages there is a ton of flickering

https://github.com/doitsujin/dxvk/assets/46948241/79af0915-4c72-4cb6-b6f6-795970d50211

### Software information
Name of the game, settings used etc.

### System information
- GPU: Intel Arc A770
- Driver: 31.0.101.5074
- Wine version: Native Windows Environment
- DXVK version: commit 1b31aa5 artifacts

### Apitrace file(s)
[P5R.trace.7z](https://drive.google.com/file/d/1kog_VGpQkHQoCOgxXe77z6J6cZsnAjdq/view?usp=sharing)

### Log files
[P5R_d3d11.log](https://github.com/doitsujin/dxvk/files/13669242/P5R_d3d11.log)
[P5R_dxgi.log](https://github.com/doitsujin/dxvk/files/13669246/P5R_dxgi.log)

**Comment by mbriar** [comment]
Pretty much guaranteed an intel driver bug.

**Comment by doitsujin** [comment]
Trace replays fine here, probably an Intel driver bug.

**Comment by BuyMyMojo** [comment]
opened an issue on the intel support repo for now then, thanks you two!

**Comment by Blisto91** [comment]
@BuyMyMojo Is this still an issue to this day?

**Comment by BuyMyMojo** [comment]
> @BuyMyMojo Is this still an issue to this day?

I haven't check in a while, since making the issue my hardware has substantially changed and I'm back on Linux so I don't have a windows environment to test DXVK under windows but 3 weeks ago someone in my other issue [mentioned it is no longer an issue](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/639#issuecomment-2462430505)
