### ISSUE TITLE
[d3d11] Kingdom Hearts 1.5 + 2.5 ReMIX games crash on FMV play

### ISSUE THREAD

**Issue by Plasmap0wer** [doitsujin/dxvk#3747]
I was trying out the wrapper on the old Kingdom Hearts games, but it crashes when you go to an FMV sequence like starting a new game or an opening movie. I only tested out two games but I assume the rest of the games have the same issue. It works fine if you're starting from a preexisting save file where no FMV loads.

### Software information
Kingdom Hearts 1.5 + 2.5 ReMIX; tested Kingdom Hearts II Final Mix and Kingdom Hearts: Birth By Sleep Final Mix

### System information
- GPU: Nvidia GeForce RTX 3080 (220A)
- Driver: 546.33
- Wine version: Windows 11
- DXVK version: 2.3

### Apitrace file(s)
[KINGDOM HEARTS II FINAL MIX.trace]
(https://drive.google.com/file/d/1m_EFMAThWi5NLGGn_5-NGPCnwFPMpyaE/view?usp=drive_link)
[KINGDOM HEARTS Birth by Sleep FINAL MIX.trace]
(https://drive.google.com/file/d/1I6uMN8xvC4CVyha4hjSfP5t1ZaRv_fSj/view?usp=drive_link)

### Log files
Please attach Proton or Wine logs as a text file:
[KINGDOM HEARTS II FINAL MIX_d3d11.log](https://github.com/doitsujin/dxvk/files/13680232/KINGDOM.HEARTS.II.FINAL.MIX_d3d11.log)
[KINGDOM HEARTS Birth by Sleep FINAL MIX_d3d11.log](https://github.com/doitsujin/dxvk/files/13680233/KINGDOM.HEARTS.Birth.by.Sleep.FINAL.MIX_d3d11.log)

**Comment by mbriar** [comment]
These games use D3D12 for rendering, which DXVK doesn't even implement, so I'm assuming you use vkd3d-proton in addition to DXVK's DXGI.dll. If only FMVs don't work then it's pretty likely because shared resources are not, and will likely never be, supported on windows with DXVK+vkd3d-proton. It works on linux/proton using a special wine interface. There is nothing you can do on windows other than just not using DXVK.

**Comment by mbriar** [comment]
That won't work on windows, which this issue is about. Of course the easiest fix on windows is to just not use dxvk and be done with it.

**Comment by Kurumi78** [comment]
> Use mf-install which is a Media Foundation workaround for Wine/Proton. 

Unfortunately that does not work here. It fixes Kingdom Hearts 3 though.

**Comment by doitsujin** [comment]
fixed in vkd3d-proton.
