### ISSUE TITLE
ambient occlusion compatibility nvidia inspector

### ISSUE THREAD

**Issue by trashlll** [doitsujin/dxvk#3748]
Good afternoon I use the ambient occlusion compatibility setting - "0x00000013 (ArmA 2: Operation Arrowhead, Take-on helicopters, ArmA 3, ArmA 2)" in the GTA SA game via NVIDIA INSPECTOR. The thing is that when installing dxvk AO stopped working, is there a way to fix this?

### Software information
GTA SA, Nvidia inspector

### System information
- GPU: rtx 3050
- Driver: 536.67
- Wine version: Windows 10
- DXVK version: 2.3

**Comment by mbriar** [comment]
No, if these only apply when you use nvidia's D3D driver then there is nothing DXVK can do about that.

**Comment by doitsujin** [comment]
What mbriar said above. Driver-side hacks do not apply to Vulkan.
