### ISSUE TITLE
GTA IV Refuses to launch with DXVK

### ISSUE THREAD

**Issue by JSkes** [doitsujin/dxvk#3752]
GTA IV Simply refuses to launch when DXVK is installed, nothing shows up whatsoever.
I've tried adding
dxgi.maxFrameLatency = 1
d3d9.maxFrameLatency = 1
to my dxvk.conf file but it still would not launch.

### Software information
Grand Theft Auto IV v1.0.8.0
1920x1080@75Hz

### System information
- GPU: NVIDIA GeForce GTX 960 2GB
- Driver: 545.92
- Wine version: 
- DXVK version: 2.3

### Log files
[LaunchGTAIV_d3d9.log](https://github.com/doitsujin/dxvk/files/13701176/LaunchGTAIV_d3d9.log)

**Comment by Blisto91** [comment]
> info:  Required Vulkan extension VK_KHR_surface not supported

This line indicates there is an issue with your Vulkan driver installation. I would try to reinstall drivers or trying a older one.

**Comment by JSkes** [comment]
Am I able to just update my Game Ready Driver instead? Since I'm not using the latest one right now.

**Comment by mbriar** [comment]
It should be impossible to end up with a normal nvidia driver installation without vulkan drivers, so who knows what you did to break it and how to fix it. But probably just reinstalling will work.

**Comment by JSkes** [comment]
Alright after updating the game works fine now, I still have no idea how my Vulkan drivers broke
