### ISSUE TITLE
Mortal Shell (1110910) has low performance in certain scenarios

### ISSUE THREAD

**Issue by simifor** [doitsujin/dxvk#3754]
### Software information
Mortal Shell.
1680x1050, fullscreen, unlimited framerate.
Vsync, film grain and indie mode disabled.
Individual graphic options set to high.

Performance compared to vkd3d-proton, and windows.
The performance can be observed in the main menu with a certain background, the background depends on where you are in the game world, so I recommend using my save file to get it.
[MortalShell.zip](https://github.com/doitsujin/dxvk/files/13707092/MortalShell.zip)

![Mortal Shell  _20231217_162941](https://github.com/doitsujin/dxvk/assets/70454800/51d0c8dc-a4f6-4d7e-b1ee-e736519d5d8f)
![Mortal Shell  _20231217_163219](https://github.com/doitsujin/dxvk/assets/70454800/1fbf811e-b8fb-4e5d-aebf-8b77f8c317ee)
Linux
dxvk = 61 FPS
vkd3d-proton = 110 FPS

Windows
dx11 = 110 FPS
dx12 = 102 FPS

I tested proton 5.0, 5.11, 6.3, 8.0.4, 8 RC, EXP BE and there were no differences with the performance.

### System information
- GPU: RX 6600
- Driver: mesa 23.3.1
- Wine version: 8/7
- DXVK version: 2.3

### Apitrace file(s)
When using wined3d the main menu looks like this, so I don't think a wined3d trace would be useful (I don't even know if it would be useful at all in this case as, to my eyes, it at least renders correctly). If you think it would be helpful, I could trace from windows 
![Y1218_142046](https://github.com/doitsujin/dxvk/assets/70454800/675d05a3-d459-4ba6-93b1-330caeefe9a1)

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
[steam-1110910.log](https://github.com/doitsujin/dxvk/files/13707033/steam-1110910.log)

**Comment by mbriar** [comment]
> When using wined3d the main menu looks like this, so I don't think a wined3d trace would be useful 

You can apitrace just fine with DXVK almost all of the time.

**Comment by simifor** [comment]
https://mega.nz/file/1z0BiC4I#N6dbaZ9AS1srEvmjpUdOBEp2wQWaWimeN7OWMaP2aGY here's the compressed trace taken with dxvk. 550MB compressed, 1.7GB uncompressed

**Comment by simifor** [comment]
I've now tested the game on windows with dxvk and on linux with amdvlk and the results are weird.

Main menu performance:
Native DX11                      =~110FPS
RADV VKD3D-PROTON     =~110FPS
Native DX12                      =~102FPS
AMDVLK DX11                   =~97FPS
Windows+DXVK                 =~90FPS
RADV+DXVK                      =~61FPS
AMDVLK+VKD3D-PROTON=~60FPS

Ingame tested location:
RADV+DXVK                      =~111FPS
Native DX12                       =~109FPS
RADV+VKD3D-PROTON     =~97FPS
AMDVLK+DXVK                  =~97FPS
AMDVLK+VKD3D-PROTON=~92FPS
Windows+DXVK                 =~85FPS
Native DX11                       =~79FPS

Windows+VKD3D-PROTON makes the game crash

So the results are a mixed bag. Native DX11 is the fastest in the main menu, but it's the slowest in the in game performance.

RADV+DXVK is tied in last places with AMDVLK+VKD3D-PROTON for the main menu, but RADV+DXVK is tied to Native DX12 in the first place for in game performance.

RADV+DXVK and windows+DXVK lose performance versus native DX11 in the main menu, but they gain performance in game.

**Comment by simifor** [comment]
I progressed further into the game so that I'm now in an icy location, so I have more comparison points now.
Location 1 is the only tested scene to not be icy.
<table>
<tr>
 <td>
 <td>RADV DXVK|VKD3D-PROTON
 <td>AMDVLK DXVK|VKD3D-PROTON
 <td>Windows DX11|DXVK
 <td>Windows DX12
<tr>
 <td>Menu
 <td>61|110
 <td>97|60
 <td>110|90
 <td>102
<tr>
 <td>Location1
 <td>111|97
 <td>97|92
 <td>79|85
 <td>109
<tr>
 <td>Location2
 <td>74|83
 <td>81|66
 <td>85|75
 <td>84
<tr>
 <td>Location3
 <td>75|109
 <td>106|67
 <td>103|95
 <td>101
</table>

**Comment by simifor** [comment]
I compiled a fresh mesa-git and the performance in snowy region is good now, menu performance is tied to amdvlk now and the ingame have it as the fastest dx11 implementation. I don't know what commit fixed it, but it must have been between 551924aa879 and cfba24ccb54
