### ISSUE TITLE
[d3d11] Soulworker - 

### ISSUE THREAD

**Issue by MUKZET** [doitsujin/dxvk#3756]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Name of the game, settings used etc.

Soulworker KR
https://store.steampowered.com/app/1825750/_/

### System information
- GPU: AMD Radeon RX 6900 XT
- Driver: 23.30.13.01-231128a-398226C-AMD-Software-Adrenalin-Edition (2.0.283)
- Wine version: Windows 11
- DXVK version: 2.3

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.
[SoulWorker_d3d11.log](https://github.com/doitsujin/dxvk/files/13727766/SoulWorker_d3d11.log)
[SoulWorker_dxgi.log](https://github.com/doitsujin/dxvk/files/13727767/SoulWorker_dxgi.log)

![20231220_222308](https://github.com/doitsujin/dxvk/assets/122770487/ba5192fa-8006-430c-b911-202b031d1d4d)

DirectX version of the game has been updated. (DX9 -> DX11)

after this update, I cannot run the game with DXVK (d3d11, version 2.3)

**Comment by Blisto91** [comment]
How do you enable that. The game still uses d3d9 here

**Comment by MUKZET** [comment]
> How do you enable that. The game still uses d3d9 here

KR server is now using d3d11 from today (12/20/2023)

**Comment by MUKZET** [comment]
> Am i correct in assuming i can't access that outside Korea without jumping through a bunch of hoops?
> 
> Also can you post logs from a up to date dxvk. Your logs are from a very old version
> 
> Edit: Also make a apitrace without dxvk

just need vpn to play this game outside Korea

I tried several versions of dxvk such as 1.5.3, 1.7, 2.0, 2.3 but nothing works in d3d11

[SoulWorker_d3d11.log](https://github.com/doitsujin/dxvk/files/13730456/SoulWorker_d3d11.log)
[SoulWorker_dxgi.log](https://github.com/doitsujin/dxvk/files/13730457/SoulWorker_dxgi.log)
version 2.3 log file

https://drive.google.com/file/d/18tJtRnajYaHX2rLoLHFey9UPBsbYHoJ_/view?usp=sharing

apitrace files without dxvk

**Comment by Blisto91** [comment]
> just need vpn to play this game outside Korea

Does that work with the Steam version? I read claims i would need a Korean phone number.

The trace replays fine with dxvk here. 
```
warn:  D3D11InternalCreateDevice: Adapter is not a DXVK adapter
```
This line could indicate that the game is just trying to load the wrong dxgi at some point, e.g. Windows own which won't work. If it's just that that is the case then it won't work on Windows.

**Comment by MUKZET** [comment]
> > just need vpn to play this game outside Korea
> 
> Does that work with the Steam version? I read claims i would need a Korean phone number.
> 
> The trace replays fine with dxvk here.
> 
> ```
> warn:  D3D11InternalCreateDevice: Adapter is not a DXVK adapter
> ```
> 
> This line could indicate that the game is just trying to load the wrong dxgi at some point, e.g. Windows own which won't work. If it's just that that is the case then it won't work on Windows.

Soulworker KR server is on Steam now. you can play without Korean phone number.

btw, it means I can't use dxvk anymore on that game right?
I need to get used on d3d11.

Thank you for the answer.

**Comment by K0bin** [comment]
> btw, it means I can't use dxvk anymore on that game right?
I need to get used on d3d11.

Not on Windows.

**Comment by MUKZET** [comment]
> > > just need vpn to play this game outside Korea
> > 
> > 
> > Does that work with the Steam version? I read claims i would need a Korean phone number.
> > The trace replays fine with dxvk here.
> > ```
> > warn:  D3D11InternalCreateDevice: Adapter is not a DXVK adapter
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This line could indicate that the game is just trying to load the wrong dxgi at some point, e.g. Windows own which won't work. If it's just that that is the case then it won't work on Windows.
> 
> I believe it does come down to people forgetting to copy dxgi.dll in addition to d3d11.dll for this issue. I had someone else test dxvk 2.3 on the korean version and it worked without any problems for them.

![20231221_222530](https://github.com/doitsujin/dxvk/assets/122770487/d2119a19-cb81-45f1-8bab-eef623aee647)


It didn't work for me

**Comment by MUKZET** [comment]
> > > > > just need vpn to play this game outside Korea
> > > > 
> > > > 
> > > > Does that work with the Steam version? I read claims i would need a Korean phone number.
> > > > The trace replays fine with dxvk here.
> > > > ```
> > > > warn:  D3D11InternalCreateDevice: Adapter is not a DXVK adapter
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > This line could indicate that the game is just trying to load the wrong dxgi at some point, e.g. Windows own which won't work. If it's just that that is the case then it won't work on Windows.
> > > 
> > > 
> > > I believe it does come down to people forgetting to copy dxgi.dll in addition to d3d11.dll for this issue. I had someone else test dxvk 2.3 on the korean version and it worked without any problems for them.
> > 
> > 
> > ![20231221_222530](https://private-user-images.githubusercontent.com/122770487/292216986-d2119a19-cb81-45f1-8bab-eef623aee647.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNjY0NTIsIm5iZiI6MTcwMzE2NjE1MiwicGF0aCI6Ii8xMjI3NzA0ODcvMjkyMjE2OTg2LWQyMTE5YTE5LWNiODEtNDVmMS04YmFiLWVlZjYyM2FlZTY0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQxMzQyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWIzZTMzNDBhNWQ3ZDlhMTA2ZTM2ZjQ5NjViMjA4ZTE3NTViODVjYzdiZGZiZmU1ODI3MTI3OGQxNDAyZjZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HvrifYnqG_Bj-dVjK8KJGIUxEokQOBezW6E5xwM5mks)
> > It didn't work for me
> 
> After doublechecking your game files against the ones listed on SteamDB it looks like you might be missing d3dx9_43.dll that ships with the game. Try verifying your game files and reinstalling dxvk.

![image](https://github.com/doitsujin/dxvk/assets/122770487/5b6a0286-eb0b-449f-9d87-d66bdfa9d805)




I tried but nothing changed with d3dx9_43.dll

**Comment by Blisto91** [comment]
Seems to just want to use the dxgi in system32 folder. So there is nothing for dxvk to do here

![image](https://github.com/doitsujin/dxvk/assets/47954800/ce77a5d5-468d-4e8b-9809-394bd1632298)

**Comment by Sia-Aruhu** [comment]
> Issue can be solved by hex editing BaseDX11.dll imports and replacing `DXGI.dll` with `DXGJ.dll` and renaming the dll appropriately. However it seems the anticheat XignCode3 doesn't particularly like dxvk and the game will be closed after around 2 minutes. This can be fixed by moving the game on a seperate partition like with dx9 previously. You are doing this at your own risk.
> 
> (Ignore the version name, its a custom build but the same should work with base dxvk) ![image](https://private-user-images.githubusercontent.com/16194579/292280893-137ce0a3-232d-4939-82dc-be73c5c3db4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMDU4MjYsIm5iZiI6MTcwMzIwNTUyNiwicGF0aCI6Ii8xNjE5NDU3OS8yOTIyODA4OTMtMTM3Y2UwYTMtMjMyZC00OTM5LTgyZGMtYmU3M2M1YzNkYjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAwMzg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5Y2YyYzc1MDMxMThkNGJlYjkxNWY3YmZjOTJiMWNiOWNmNjY0YTgxYzFhMTAxMjJjZDhlZjM1ZTZmNDgwMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k4nuXCzQEKj_TltYNA7DJwsPlKmjw-WPDRIc9L97OmM)


Glad it actually works. Could you please share how to fix it or the modified BaseDX11.dll file?

**Comment by MUKZET** [comment]
> Issue can be solved by hex editing BaseDX11.dll imports and replacing `DXGI.dll` with `DXGJ.dll` and renaming the dll appropriately. However it seems the anticheat XignCode3 doesn't particularly like dxvk and the game will be closed after around 2 minutes. This can be fixed by moving the game on a seperate partition like with dx9 previously. You are doing this at your own risk.
> 
> (Ignore the version name, its a custom build but the same should work with base dxvk) ![image](https://private-user-images.githubusercontent.com/16194579/292280893-137ce0a3-232d-4939-82dc-be73c5c3db4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjE2NDMsIm5iZiI6MTcwMzIyMTM0MywicGF0aCI6Ii8xNjE5NDU3OS8yOTIyODA4OTMtMTM3Y2UwYTMtMjMyZC00OTM5LTgyZGMtYmU3M2M1YzNkYjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA1MDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZjg1ZmMzYzk5ODRiZTBkYzI2YzUwMDUwZTc0NDczYjMxMGM0ODk3ZjFhNGEwNzQzNTU3MTk3NDM0MzM4ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1ZYpDSI3ozNJX4DymPQgnbftFGrLAUFnOGcTTdqzd3M)

![20231222_140219](https://github.com/doitsujin/dxvk/assets/122770487/bfcaac41-ef9c-4741-ba3f-cffca332aee2)




Thank you.

I tried your method and I made it.

**Comment by Blisto91** [comment]
Maybe put a disclaimer to use at your own risk.
