### ISSUE TITLE
[d3d11] Far Cry 3 and 4, dark (transparent) squares around some buildings and objects

### ISSUE THREAD

**Issue by Flopster101** [doitsujin/dxvk#3758]
### Software information
This is happening in Far Cry 3 and 4, both latest versions running from Steam. Tried a variety of graphics settings with no change. Does NOT affect the DX9 mode in Far Cry 3.
The games also seem to be a bit brighter than they should be due to this issue.

I tested on Windows 11 too and the same issue happens (with DXVK 2.3). It doesn't happen without DXVK, though this seems to have been an issue in the stock D3D11 renderer at some point according to [this post](https://community.intel.com/t5/Intel-ARC-Graphics/Dark-boxes-around-buildings-graphical-glitch-Far-Cry-3-AND-Far/m-p/1498224) on Intel community.

### System information
- GPU: Intel(R) Xe Graphics (TGL GT2)
- Driver: Mesa 23.1.9-manjaro1.1 (**Linux**) / 31.0.101.5081 (**Windows**)
- Wine version: GE-Proton8-25 and latest Proton Experimental
- DXVK version: 2.3

### Screenshots
![Screenshot_20231221_134749](https://github.com/doitsujin/dxvk/assets/50512583/5ee3beb3-857a-4052-9df6-5e11db3e1017)
![Screenshot_20231221_140902](https://github.com/doitsujin/dxvk/assets/50512583/f0558cf3-1cbb-407c-be47-94955d745a46)

### Apitrace file(s)
[Here](https://www.mediafire.com/file/oju7jkw5tt64mhj/FC3_4_APITRACE.7z/file)

### Log files
[steam-2.tar.gz](https://github.com/doitsujin/dxvk/files/13745828/steam-2.tar.gz)

**Comment by Flopster101** [comment]
Well, after looking at dxvk.conf for a while I decided to try my luck by setting `dxgi.hideIntelGpu = True`, and that seems to have fixed it!

![Screenshot_20231221_223225](https://github.com/doitsujin/dxvk/assets/50512583/66d1bb8c-4c59-42eb-afb5-9c4e187ceb03)
![Screenshot_20231221_224250](https://github.com/doitsujin/dxvk/assets/50512583/9606d92c-aea6-4bac-b4d6-384cbcd23bc2)

So... Would that be considered as fixed or just a workaround for now? I imagine I'm not the only one experiencing this.

**Comment by doitsujin** [comment]
This is a known game issue, they make assumptions on clear value rounding behaviour depending on GPU vendors which do not necessarily hold true on Vulkan drivers. We should already have an app profile for these games, can add the Intel option to that.

**Comment by Flopster101** [comment]
Oh, alright. Good to know that it's a quick fix.

**Comment by zbag89** [comment]
sorry i have the same problem here, but a have no clue how can i fix with your files, can you be more specific about the steps that i should go through?

**Comment by Flopster101** [comment]
> sorry i have the same problem here, but a have no clue how can i fix with your files, can you be more specific about the steps that i should go through?

I believe there was a fix merged for this already, but anyway, this is what I had done if I remember correctly.

* Get a copy of the **dxvk.conf** file from [here](https://github.com/doitsujin/dxvk/blob/master/dxvk.conf).
* Copy the file to the directory where the game executables are.
* Open **dxvk.conf** and find this line:

```
# dxgi.hideIntelGpu = Auto
```
* Change it to:

```
dxgi.hideIntelGpu = True
```
* Save and run the game. Problem should be fixed now.

**Comment by zbag89** [comment]
unfortunately it didnt work again, do you possibly know any othe changes in it?
or any other way?
3 years ago i changed some stuff in .xml file in the documents, but i dont remember it right now, it wasnt a good solution though
for more information i have dx12
