### ISSUE TITLE
Quake Champions crashes on certain effects

### ISSUE THREAD

**Issue by Zeioth** [doitsujin/dxvk#377]
### System information
- GPU: Nvidia GTX 1050 ti
- Driver: 396.24
- Wine version: staging-3.8-x86_64
- DXVK version: 0.50

### Log files
[QuakeChampions_dxgi.log](https://github.com/doitsujin/dxvk/files/2007447/QuakeChampions_dxgi.log)
[QuakeChampions_d3d11.log](https://github.com/doitsujin/dxvk/files/2007448/QuakeChampions_d3d11.log)

### Comments
After shader cache is full, the game run smoothly at 80fps (min settings). But it crashes some times in the middle of the match. There are some errors on the logs:

```
warn:  D3D11Query: Unsupported query type 6
warn:  D3D11RasterizerState: Depth clamp not properly supported
err:   D3D11Device::CreateBuffer: D3D11_BIND_STREAM_OUTPUT not supported
err:   D3D11Device::CreateGeometryShaderWithStreamOutput: Not implemented
err:   D3D11DeviceContext::SetPredication: Stub
```

**Comment by doitsujin** [comment]
Game requires stream output, which is not unlikely to cause the issue (see #135).

**Comment by Zeioth** [comment]
3 People (Including me) have reported exactly the same issue. The acid effect of the game is the only one that seems to use steam output.

> The crashes happen 100% of the time on these 3 specific occations:
> After loading the map "Lockbox"
> After loading the map "Vale of pnath"
> When the character/champion named "Sorlag" uses his ability: Acid spit.

Steam output is also required for high settings in "Texture quallity", and "Ilulimation" options.

**Comment by pandasauce** [comment]
As of now, it seems that the game won't start at all, because it requires x64 VC 2015 redistributables that Wine won't install.

**Comment by Zeioth** [comment]
That's not DXVK fault... but I'll take a look.
