### ISSUE TITLE
Cyberpunk 2077 at ~15 FPS but with Proton ~50FPS

### ISSUE THREAD

**Issue by DocMAX** [doitsujin/dxvk#3770]
I have a strange issue where Cyberpunk 2077 is at ~15 FPS with wine+dxvk+vkd3d but with Proton i get about ~50FPS.
No issues with other games or GPUs.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Cyberpunk

### System information
- GPU: AMD RX570
- Driver: Kernel 6.6.8-arch1-1
- Wine version:  wine-ge-custom GE.Proton8.25-1, also tried wine, wine-staging 8.21
- DXVK version: dxvk-bin 2.3-1
- VKD3D version: vkd3d-proton-bin 2.11.1-1

### Apitrace file(s)
- i get no output

### Wine Log
[wine.log](https://github.com/doitsujin/dxvk/files/13777969/wine.log)

**Comment by mbriar** [comment]
And why would that be a DXVK issue? The game uses d3d12. Make sure to enable esync on wine-staging, it's expected to be slow on upstream wine without esync/fsync.

**Comment by DocMAX** [comment]
Great thanks man! WINEESYNC=1 did it!

**Comment by DocMAX** [comment]
Hmm, FPS increased to 33 fps with, but proton still has more (50 fps).
I know it's not an dxvk issue but maybe someone has an idea?
