### ISSUE TITLE
GTA IV refuses to work when I install DXVK

### ISSUE THREAD

**Issue by dypaez** [doitsujin/dxvk#3772]
Info

GPU: Nvidia Geforce GTX 1050 Ti
RAM: 8 GB
CPU: AMD A8-7600 Radeon R7
OS: Windows 10 Pro x64
Driver Version: 546.33 GRD
--

I've been trying to run the latest steam version without any mods but DXVK, yet I can't get it to work.
The game does not show any error messages when it crashes.

[GTAIV_d3d9.log](https://github.com/doitsujin/dxvk/files/13780896/GTAIV_d3d9.log)

**Comment by K0bin** [comment]
The game is known to work fine.

If it doesn't work on your system, it's something out of our control and there's most likely nothing we can do.

**Comment by dypaez** [comment]
I fixed the problem. First I disabled my integrated graphics in BIOS, and tried starting GTA IV, and it worked, but I wanted to keep my integrated graphics on for dual monitor. So then I researched a bit and found out about "DXVK_FILTER_DEVICE_NAME", using that in my steam launch parameters solved it for me.

**Comment by K0bin** [comment]
DXVK_FILTER_DEVICE_NAME is an environment variable. Just putting that into your launch options does nothing.
