### ISSUE TITLE
Can't Cap FPS

### ISSUE THREAD

**Issue by SmashingMist27** [doitsujin/dxvk#3775]
I'm using windows10. Tried using both nvidia control panel and rivatuner to cap fps but does not work.

### Software information
Assassins Creed 3 Remastered

### System information
- GPU: RTX3090
- Driver: Latest
- Wine version: N/A, Dont own/use
- DXVK version: 2.3

**Comment by Blisto91** [comment]
dxvk comes with it's own fps cap option. Either the environment variable https://github.com/doitsujin/dxvk#frame-rate-limit (does not go in the config file) or via a [`dxvk.conf`](https://github.com/doitsujin/dxvk/blob/a7a63b37c3b7a8280c6a8487a2f21fe9dd8dbe0e/dxvk.conf#L40) file places next to exe.

**Comment by K0bin** [comment]
> Tried using both nvidia control panel and rivatuner to cap fps but does not work.

If those dont work, that's not a DXVK problem. It's a problem with Riva Tuner or Nvidias FPS limiter. On top of that, like Blisto said, DXVK has a FPS limiter of its own.
