### ISSUE TITLE
Game crash after unlocking system with physlock

### ISSUE THREAD

**Issue by leewdch** [doitsujin/dxvk#378]
I'm using [physlock](https://github.com/muennich/physlock) on my system to lock my pc when I'm afk but after unlocking it I always find my game crashed with that error window. Do I need to use apitrace for a relevant log? I don't know if this is a driver issue or a physlock issue

### Software information
Final Fantasy XIV: Stormblood

### System information
- GPU: NVIDIA GTX 980Ti
- Driver: 396.24
- Wine version: wine-3.8 (stable)
- DXVK version: 0.51

### Apitrace file(s)
- \<Later edit\>

### Log files
- d3d11.log:
```
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
warn:  D3D11DeviceContainer::QueryInterface: Unknown interface query
warn:  6543dbb6-1b48-42f5-ab82-e97ec74326f6
warn:  D3D11Device: No matching border color found for (-3.40282e+038,0,0,0)
err:   DxvkQueryPool: Failed to create query pool
```
- dxgi.log: https://pastebin.com/6ShTRf4H

![image](https://user-images.githubusercontent.com/11262717/40128177-4917a67a-5931-11e8-9ab5-eb99bf9a9641.png)

**Comment by doitsujin** [comment]
I cannot support third-party solutions which mess around with the window system in an undefined way, and the DXGI log indicates that physlock is doing that.

**Comment by leewdch** [comment]
Apparently dxvk crashes when I switch vt as well with ctrl + alt + {1..9-0} https://github.com/muennich/physlock/issues/64#issuecomment-390958026

**Comment by doitsujin** [comment]
Works fine on my end.
