### ISSUE TITLE
UK Truck Simulator has weird black stuff on grass and trees

### ISSUE THREAD

**Issue by GTAbestplayer123** [doitsujin/dxvk#3780]
### Software information
UK Truck Simulator version 1.32 with max settings without anti aliasing turned on

### System information
- GPU:Nividia Geforce GTX 1650 4GB EVGA
- Driver:461.7
-Windows 11 22H2

- DXVK version: 2.3

### Apitrace file(s)
- https://drive.google.com/drive/folders/1OIrgTzsDVRrk7SOAHBMb-yFo7JOpVhLS?usp=drive_link

![ukts_00002](https://github.com/doitsujin/dxvk/assets/110957726/b9d0c524-13ab-4cf7-9e59-b993aea87cf3)
![Screenshot 2024-01-03 195619](https://github.com/doitsujin/dxvk/assets/110957726/963091d9-27c9-4864-8e4b-a40fbafde9c5)

**Comment by Blisto91** [comment]
Hi there and thank you for the issue. Can you verify that the issue goes away by putting a file called `dxvk.conf` next to the games exe and inserting `d3d9.floatEmulation = Strict` in to it?

**Comment by GTAbestplayer123** [comment]
Your fix fixed the game.I no longer see those weird black stuff .

**Comment by GTAbestplayer123** [comment]
Oh ok.

**Comment by Blisto91** [comment]
@GTAbestplayer123 I gather this is the first game which isn't available online?
Can you send how the path to the exe looks from the games folder? I can see the apitrace that contains actual data is called `game.trace` so the main exe doesn't have a unique name.
Basically i'll want to know what the name of the default game install folder is called and then from there the path to the exe.

**Comment by GTAbestplayer123** [comment]
The game used to be avilable digitally but SCS took the site to buy the game down. Game.exe is used for game configuration and license activation i believe.
![Screenshot 2024-01-03 214503](https://github.com/doitsujin/dxvk/assets/110957726/dae41c55-626a-4d32-8f2b-c2657a6a8fe9)

**Comment by Blisto91** [comment]
Before we let you get back to driving trucks in peace can you verify that the issue is gone without any config files if you use the download at the bottom of this page https://github.com/doitsujin/dxvk/actions/runs/7398166082 ?

**Comment by GTAbestplayer123** [comment]
It fixed the problem although the 32 bit files will  cause the game not to run at all but the  64 bit files works fine.
![ukts_00005](https://github.com/doitsujin/dxvk/assets/110957726/fa1cece0-b904-4413-802c-fbbea2678277)

**Comment by Blisto91** [comment]
Is the game 32bit? If yes then using the 64bit files means it isn't using dxvk

**Comment by GTAbestplayer123** [comment]
I remeber running the game on Windows XP many years ago so i think it is 32 bit.

**Comment by Blisto91** [comment]
Sorry the crash was a brainfart from me. This should hopefully work with the 32bit version <https://github.com/doitsujin/dxvk/actions/runs/7398629921>

**Comment by GTAbestplayer123** [comment]
The game now runs correctly.

**Comment by GTAbestplayer123** [comment]
It also fixed that annoying bug on  Windows 10 and 11 when the game will suddenly crash after a certain amount of time without any fixes apply to it.
