### ISSUE TITLE
GTA: SA (classic) Flashing screen, broken screenshots

### ISSUE THREAD

**Issue by Corrado346** [doitsujin/dxvk#3781]
The game window flashes black when the window is out of focus (eg. clicking on another program on another monitor)
Pressing PRTSC captures the frame when the last black screen flash happened (issue mentioned above)
It also happens with screen snipping
The game also takes a little bit longer to quit

### Software information
Grand Theft Auto: San Andreas (classic) 
- Windowed borderless, 1920x1080

### System information
- GPU: NVIDIA GeForce GTX 1650
- Driver: 546.33
- DXVK version: 2.3

When I install apitrace my game does not want to run
I can't really screenshot how any of this looks like

these are all just little inconveniences that make playing the game a little more annoying
the old api didnt have these issues it just had some rendering issues which where fixed by insalling dxvk but it also introduced these new bugs

**Comment by K0bin** [comment]
You didn't mention Wine so I assume you're on Windows. It's completely normal that printscreen doesn't capture fullscreen games.

**Comment by Corrado346** [comment]
> You didn't mention Wine so I assume you're on Windows. It's completely normal that printscreen doesn't capture fullscreen games.

It's not fullscreen it's running in windowed borderless mode.

**Comment by K0bin** [comment]
If printscreen doesn't work, it's in fullscreen.

**Comment by Corrado346** [comment]
> If printscreen doesn't work, it's in fullscreen.

It works but it captures the frame before the black screen occurs.
And a black screen occurs when I press printscreen or open screen snipping tool or when I click on a program on another screen.

Here is a video of what I mean: https://youtu.be/c2LT39FtW6Q?si=AKCuBIloib_bs4te
A black screen doesn't appear in the video it just kind of snaps into a frame but I am seeing a black flash on my screen.

**Comment by Corrado346** [comment]
> Install SilentPatch; it should help.
> 
> DXVK is known not to always work well with overlays on Windows. See https://github.com/doitsujin/dxvk/wiki/Windows.

I already have SilentPatch and it does not help.

Also I didn't mention that my game uses a [mod](https://www.mixmods.com.br/2022/10/iii-vc-sa-windowed-mode/) that makes it run in windowed borderless mode so it may be interfering with DXVK somehow. _I'm using this mod to fix the window minimizing in fullscreen mode when I click on another program on another monitor, the mod worked without issues prior to installing DXVK._

I found a fix that resolves all of the issues I mentioned before (requires mod to replicate): 
While in game press alt+enter (to enter windowed with borders mode) and then again press alt+enter (to enter windowed borderless mode again) and that's it, that fixed all of the issues I had.

A little annoying having to do that every time to have normally functioning screenshots and for the screen not to flicker when I click on something on another monitor but there isn't much more I can do about it.

It is what it is.

**Comment by Corrado346** [comment]
Due to inactivity and no official solution being found I'm assuming that there will be no official solution.
Solution provided by me works well enough for me and I am going to keep on using it, for anyone else who comes across this issue and they don't find my solution helpful, I'm sorry.
God bless.
