### ISSUE TITLE
[regression, d3d9] Supreme Ruler Ultimate alt tab render freeze

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3784]
Since commit https://github.com/doitsujin/dxvk/commit/52ac271acba015ddc9bf35604656615f228a67bb when you alt tab in Supreme Ruler Ultimate the renderer will freeze and not snap out of it when you focus on the game again.
Note that the commit itself will show the game as only a black screen, which is fixed a couple of commits later, but i can see with the dxvk hud not updating that it should be the one.

`d3d9.deviceLossOnFocusLoss` does not make a difference.

### Software information
Supreme Ruler Ultimate

### System information
- GPU: RX 6800
- Driver: few days old mesa main
- Wine version: Proton Experimental
- DXVK version: https://github.com/doitsujin/dxvk/commit/52ac271acba015ddc9bf35604656615f228a67bb and up

### Apitrace file(s)
Two traces where i go to the main menu then hover back and forth on the buttons -> alt tab -> hover back and forth again before quitting. One made with dxvk master and one made with wined3d.
https://drive.proton.me/urls/M6DB662QVR#XZTSivf5Fw2P

Observe that when replaying with dxvk before the commit, e.g. 2.2, that the wined3d one will show me hovering over the buttons fine the second time after alt tabbing where as the dxvk one will end early before second attempt. When replaying with dxvk including the commit, e.g 2.3, both traces will end early and not show the hovering after alt tab.

### Log files
[SupremeRulerUltimate_d3d9.log](https://github.com/doitsujin/dxvk/files/13833572/SupremeRulerUltimate_d3d9.log)
[steam-314980.log](https://github.com/doitsujin/dxvk/files/13833573/steam-314980.log)

**Comment by K0bin** [comment]
I strongly suspect this is a game bug. The game leaks a state block in both the WineD3D apitrace as well as the DXVK one.

I've also written a quick test to verify that this will indeed make D3D9Device::Reset fail.

Lastly, there's this: https://steamcommunity.com/app/314980/discussions/0/1652171126118360822/
