### ISSUE TITLE
INSIDE (2016) on Ubuntu 22.04 with a Weaker GPU Card (GTX 760, 2GB VRAM)

### ISSUE THREAD

**Issue by aabbtree77** [doitsujin/dxvk#3789]
*INSIDE (2016): Default Wine 8.0.2*
![Screenshot from 2024-01-09 00-24-32](https://github.com/doitsujin/dxvk/assets/9137133/c950c379-8bea-4d79-b099-aa8f0a0cd6c3 "INSIDE rendered with default wine, horrid.")

*INSIDE (2016): Wine with dxvk 1.10.2. Notice reflections, shadows, and the two platforms between the boy and the wagon.*
![Screenshot from 2024-01-08 22-03-31](https://github.com/doitsujin/dxvk/assets/9137133/6c30ea30-d74c-425e-b769-57e09b91b31e "INSIDE rendered with wine and dxvk, wonderful.")

INSIDE (2016) is a 2.5D platformer game with amazing graphics which is also notoriously difficult to render properly on Linux. Often the frames are too dark even with the brightest settings, and some important details may be missing. dxvk solves this problem admirably. Notice how the default wine (v8.0.2) misses the two tiny platforms that are essential to solve the puzzle. Without them it is not possible to open the door and progress to the next level.

P.S.

This is not an issue, but one amazing case for the use of dxvk and a personal note/memo how to run a Windows game on Ubuntu 22.04 with GTX 760 (a low-end desktop GPU with 2GB VRAM). The newest dxvk v2.3 crashes, while dxvk v1.10.2 does wonders, see the results above, also clf. the issues #2727 and #2493.

0. Install the latest GPU driver for *your specific card*, vulkan, wine. For GTX 760, January 2024, it is only 470.223.2, not 535 something. Some useful links:

    [NVDIA driver versions](https://www.nvidia.com/download/index.aspx)

    [How to Enable Vulkan Rendering in Wine Games using DXVK](https://linuxhint.com/enable-vulkan-rendering-in-wine-games/)

    [How to Install Wine on Ubuntu 22.04 or 20.04](https://www.linuxcapable.com/how-to-install-wine-on-ubuntu-linux/)

    I am not sure if these Vulkan libs are essential, but I have installed them along with vulkan-tools.

1. Install the latest dxvk that *works with older NVIDIA cards such as GTX 760*:

    Download and extract dxvk v1.10.2 (not the newer ones) from [releases](https://github.com/doitsujin/dxvk/releases).

    cd dxvk-1.10.2

    chmod +x setup_dxvk.sh

    mkdir /home/tokyo/Games/wpr1.10.2

   (Use your own "/home/username", and a path, mine is "/home/tokyo").

    WINEPREFIX=/home/tokyo/Games/wpr1.10.2 ./setup_dxvk.sh install

    Notice that newer dxvk versions do not have a script, you have to follow a few manual instructions shown in dvxk readme.md. Version 1.10.2 still has the script setup_dxvk.sh that does it all, no need to copy anything manually, and no need to use winecfg to add DLL overrides for "d3d11, d3d10core, dxgi, and d3d9".

    Ignore all the warnings and errors unless they result in a crash. I get "Could not find dependent assembly LMiscrosoft.Windows.Common-Controls", "Haswell Vulkan support is incomplete", "failed to create ifstub...", "failed to marshall the interface..." and so on. Plenty of null exceptions from Unity will appear later on, none of them seem to matter.

2. Install the game:

    cd into a mounted game folder.

    WINEPREFIX=/home/tokyo/Games/wpr1.10.2 wine setup.exe

3. Start the game:

    cd /home/tokyo/Games/wpr1.10.2/drive_c/Program Files (x86)/Inside

    WINEPREFIX=/home/tokyo/Games/wpr1.10.2 wine INSIDE.exe

    To log FPS and debug:

    DXVK_HUD="1" DXVK_LOG_LEVEL=debug DXVK_DEBUG_LAYERS=1 WINEPREFIX=/home/tokyo/Games/wpr1.10.2 WINEDEBUG=-all,+vulkan wine INSIDE.exe &> output.txt

**Comment by Blisto91** [comment]
1.10.3 is the last stable release to work on older drivers just as a quick fyi. 
Branch https://github.com/doitsujin/dxvk/commits/1.10.x/ have some extra commit back ports on top that didn't make it to a stable release outside 2.0+
