### ISSUE TITLE
Installing on Debian 12 (Bookworm)

### ISSUE THREAD

**Issue by tomcass240** [doitsujin/dxvk#3793]
I am using Wine 8 (latest stable version on Debian). DXVK version 2.3 (latest vesrion) and my graphics card has latest nvidia drivers installed.

The problem I'm having seems quite a simple one. When I install DXVK the same way as the instructions on the readme file then for some reason it can't import the 32-bit dll files when running an exe on a 64-bit wine prefix. I already set the overrides in winecfg. If I manually put the 32-bit dxvk dll files in the folder where the exe is, dxvk works fine, but doing it the normal way throws up an error about not being able to import the required dll files such as dxgi.dll etc.

Does anyone know why this is? Is it a bug?

**Comment by Blisto91** [comment]
Could you share terminal output with error?

**Comment by Blisto91** [comment]
@tomcass240 Friendly ping

**Comment by K0bin** [comment]
Like Blisto said, please post the actual error.
I'll close the issue for now but don't hesitate to re-open it when you can provide that.
