### ISSUE TITLE
[Rendering issues in GTA San Andreas]

### ISSUE THREAD

**Issue by Blazepoint5** [doitsujin/dxvk#3794]
### Software information
GAME- GTA SANANDREAS
SETTINGS - 720P, no AA, high visuals effects.
OS- WIN11

### System information
- GPU: Intel HD 520
- Driver: 103.76.0
- Wine version: 
- DXVK version: 1.10.2

### Apitrace file(s)
- 
![GTA_ San Andreas 11_01_2024 19_24_12](https://github.com/doitsujin/dxvk/assets/154701981/0e3e9426-8ea7-4864-9604-aec3c1378266)

**Comment by Blisto91** [comment]
Sorry but older dxvk versions aren't supported. This also looks like a likely driver issue.
You should also use dxvk 1.10.3 which is the newest release before the driver requirements bump

**Comment by K0bin** [comment]
Besides that, this is almost certainly a driver bug.
