### ISSUE TITLE
Far Cry 2 unbootable

### ISSUE THREAD

**Issue by Azusa-mikan** [doitsujin/dxvk#3801]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Game: Far Cry 2
DirectX: 10
Window: True

### System information
- GPU: NVIDIA GeForce GTX 1050
- GPU: Intel(R) UHD Graphics 610
- Driver: NVIDIA 536.23.0
- Driver: Intel Corporation 103.67.0
- Wine version: native Windows
- DXVK version: 2.3

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files

[FarCry2_dxgi.log](https://github.com/doitsujin/dxvk/files/13971690/FarCry2_dxgi.log)

**Comment by Blisto91** [comment]
Which DLLs are you trying with. You have to use d3d10core, d3d11 and dxgi. Maybe it also wants d3d9 from dxvk at the same time but don't know.

**Comment by Azusa-mikan** [comment]
> Which DLLs are you trying with. You have to use d3d10core, d3d11 and dxgi. Maybe it also wants d3d9 from dxvk at the same time but don't know.

wtf,I put d3d9,d3d10core,d3d11 into the game directory and it worked! Thank you very much!
