### ISSUE TITLE
EverQuest: Frequent crashes after client update to DX11

### ISSUE THREAD

**Issue by rennil42** [doitsujin/dxvk#3804]
EverQuest has run on DX9 for many years with great performance on Linux with DXVK. On 2024-01-17 they rolled out an update to use DX11 which causes frequent crashes.

### Software information
EverQuest - when loading into the zone called Laurion Inn the game consistently crashes for me on the loading screen. The game log dbg.txt is linked under log files.
This is the lines in the game log file I suspect:
[Thu Jan 18 15:42:58 2024]:UNSUPPORTED: FromDX11( DXGI_FORMAT ) - Unknown format 98
[Thu Jan 18 15:42:58 2024]:UNSUPPORTED: ComputeTextureSize() - Unknown format 98
[Thu Jan 18 15:43:19 2024]00747:Dump generation request succeeded: C:\Crash\76840a7b-e13c-4746-9cb1-c4db1a449add.dmp
[Thu Jan 18 15:43:19 2024]00748:Fatal error occurred in mainthread! (Release Client #630)

It makes reference to a generated dump, however I am not finding that dump anywhere on my system. Not sure if that would that been useful either.

### System information
- GPU: AMD 7900XTX
- Driver: radv - Mesa 23.3.2-1pop0~1704238321~22.04~36f1d0e
- Wine version: 9.0.0
- DXVK version: 2.3

### Apitrace file(s)
Crash only happens with DXVK installed. Is it still meaningful to do an apitrace with DXVK disabled? With WineD3D the game is missing most textures and is mostly unplayable.
apitrace with DXVK enabled: https://mega.nz/file/0eME3Y6Y#qtOwEi7gx7JnRVssl5zo4LZY_oot9RAgz9SeOmYv8nQ

### Log files
Wine stdout+stderr log: https://mega.nz/file/xbdBXAzA#vcdwgiRMC0Hg69GZnI1R6nFOkodBad9yWyzk_rPEGzI
EQ game log with some crash info: https://mega.nz/file/ce0FSSxL#o_G8KIu4u5z3j7SaqgMqMBlbknoNNKicOeV8RqM_aNQ

**Comment by pbulat** [comment]
I'm experiencing the exact same bug with the two same UNSUPPORTED lines in the EverQuest log file. This bug is not specifically related to the Laurion Inn zone from the latest expansion, it looks like it could happen anywhere, sometimes entering the zone crashes the client, and sometimes it works fine. This might be related to some specific texture (illusion spell ?) on a player character present in that zone at that time.

Playing on Steam with Proton Experimental but I have the same issue using Bottles with DXVK 2.3.

GPU: AMD Radeon™ RX 6600

**Comment by ryao** [comment]
> This is the lines in the game log file I suspect:
> [Thu Jan 18 15:42:58 2024]:UNSUPPORTED: FromDX11( DXGI_FORMAT ) - Unknown format 98
> [Thu Jan 18 15:42:58 2024]:UNSUPPORTED: ComputeTextureSize() - Unknown format 98
> [Thu Jan 18 15:43:19 2024]00747:Dump generation request succeeded: C:\Crash\76840a7b-e13c-4746-9cb1-c4db1a449add.dmp

Format 98 is DXGI_FORMAT_BC7_UNORM, which is a texture compression format. The game log file lines you provided were generated by the game itself, since I cannot find anything in either wine or dxvk's source tree that would print those lines.

> Crash only happens with DXVK installed.

Assuming that you are using proton, I wonder if using `WINEDLLOVERRIDES=dxgi=n %command%` in your launch options makes any difference.

> Is it still meaningful to do an apitrace with DXVK disabled? With WineD3D the game is missing most textures and is mostly unplayable.

One of the contributors who looks at apitrace files might find it helpful.

**Comment by Blisto91** [comment]
In regards to the apitrace then when a crash is involved it is usually preferred to make it without dxvk with the assumption that it will then crash the same when replayed with dxvk later. Though sometimes that isn't the case, or possible, and then one with dxvk might be fine too or one of each for comparison. 
But i will let the devs comment if the trace is fine.

**Comment by ryao** [comment]
@rennil42 @pbulat Would either of you be able to confirm/deny whether using `WINEDLLOVERRIDES=dxgi=n %command%` in your launch options makes any difference?

**Comment by pbulat** [comment]
I tried yesterday and still crashed.

**Comment by doitsujin** [comment]
Is the game 32-bit only? If so, there's a good chance it's just running out of address space.

The logs don't really point to anything specific.

**Comment by pbulat** [comment]
It's 64-bit only since february 2022.

**Comment by rennil42** [comment]
How about the apitrace, did that provide any information? Is there anything else we can provide?

**Comment by xaldaren** [comment]
Having the same issue/errors but with a 3070ti and on garuda arch linux.  Steam, Lutris, Wine all do the same.

**Comment by Blisto91** [comment]
@rennil42 Could you make a apitrace with wined3d? Just the area in the area it most consistently crashes getting past the point where it usually does. If you are able to despite the graphical errors

**Comment by K0bin** [comment]
> FWIW, some GIMP users are having the same issue:

That texture format log has to be a game problem. DXGI Format 98 is DXGI_FORMAT_BC7_UNORM  and DXVK supports that just fine. A lot of games use it without any issues too.
GIMP having problems with that format is pretty meaningless for us.

**Comment by rennil42** [comment]
@Blisto91 I have tried with no luck to get EQ to run with WineD3D and apitrace but I can't get the game to launch at all. I think I have found a zone where I can reliably recreate a crash so I will try tomorrow to see if I can run an apitrace on Windows 10 (not happy about booting up that mess).

I did create a clean wineprefix for the apitrace testing (only installed corefonts with winetricks) to avoid any presence of DXVK or other conflicting libraries. Interestingly I get most textures rendered with this and no crashes. I may have to do more testing. Maybe @pbulat or one of the other Linux EQ players can test this as well? (Wine 9.0 from WineHQ)

**Comment by Blisto91** [comment]
@rennil42 were you able to make any progress on a apitrace without dxvk?

**Comment by rennil42** [comment]
@Blisto91 I can play the game with poor performance without DXVK with a clean prefix and only installing corefonts. The crash keeps happening with DXVK.
To reproduce it today in an attempt to ensure that I would capture things in Windows with apitrace enabled, I did the following.

- On Linux laptop
  - Fresh prefix (with corefonts)
  - install DXVK 2.3
  - log into game and wait for a crash

- On Windows Desktop
  - With apitrace
  - different account

Once I experienced a crash on the laptop I started logging in on the desktop computer and the laptop again. Both characters logged into the game and I waited 7-8 min before the crash happened on the laptop. I gave it a few sec before I quit out on the Windows computer. I agree with people that it is probably a character/pet/mount texture causing the crash since it is so intermittent. 

Here is the new apitrace from Windows: https://mega.nz/file/FOEgGTDT#a5jWfAHGsGeWmZYlBzqnRQC-lnsD9LEeWSXoRnNYheE
(It contains 4 trace files as that was what was created when starting the game but I would expect that it is only the 1.7GB one that is interesting)

Let me know if there is anything else I can gather or test.

**Comment by Blisto91** [comment]
@rennil42 Thank you very much for the valiant attempt. I am sad to say though that i do not see a crash when replaying that trace.
Here when i have some time i will try testing in game again. I have played quite as a lot as a new low level character without encountering anything, but i will look in to getting a Level 100 character with access to those zones.

**Comment by Blisto91** [comment]
Understood. Will see if i can figure it out 😁

**Comment by doitsujin** [comment]
I'm honestly just at a loss here. Game deliberately (and successfully) creates a BC7 texture and **then** complains that it doesn't know how to deal with BC7 textures. No idea why it doesn't do this on wined3d, there are no related feature queries or anything.

**Comment by rennil42** [comment]
I have been playing on and off for the past week with Wine 9.13 and DXVK 2.4. I have not experienced any crashes so far. Has anyone else experienced this bug lately?

**Comment by pbulat** [comment]
I haven't crashed for a long time, playing on Steam with Proton Experimental. Also, the June patch fixed the blank textures, so maybe that bug is gone for good now, hard to say.

**Comment by rennil42** [comment]
I believe the missing textures are unrelated to this issue and were fixed in Wine 9.11 (https://bugs.winehq.org/show_bug.cgi?id=56755)
My gut feeling regarding this issue is that it was a problem/bug in EQ that was silently fixed by them, maybe a broken or buggy texture? I will continue to play with DXVK enabled to see if I have any crashes but I suspect the problem is fixed.

**Comment by rennil42** [comment]
It has been 2 weeks with no crashes for me. I will go ahead and close this issue if there are no objections.

**Comment by rennil42** [comment]
Issue does not seem to happen anymore. We can only speculate what the issue was.
