### ISSUE TITLE
"Not found compatible memory type" under wine-9.0, with wayland driver and wow64

### ISSUE THREAD

**Issue by ya-isakov** [doitsujin/dxvk#3805]
Hello! I'm trying to test new wine release, 9.0, with two exciting features: wow64 and wayland driver. I've compiled wine with only wayland driver, no X11, on Gentoo, set driver via regedit, and trying to run some games. So far, I tried two 32-bit games - Hand of Fate and Evil Genius, and in both, wine crashed with 
```
0148:fixme:vulkan:wine_vkAllocateMemory Using VK_EXT_external_memory_host
0148:fixme:vulkan:wine_vkAllocateMemory Not found compatible memory type
```

I also tried 64-bit game Abzu, and it worked correctly, without complains about memory type, so, my suspicion, is that something might be wrong with combination of wow64, wayland and vulkan.

### Software information
Hand of Fate, Evil Genius
Default wine settings except using Wayland driver, and setting overrides for DXVK.
Wine compiled with --enable-win64 --enable-archs=x86_64,i386

### System information
- GPU: AMD Radeon Graphics (RADV GFX1103_R1)
- Driver: mesa-23.3.3
- Wine version: 9.0
- DXVK version: 2.3

### Apitrace file(s)
- Unfortunately, I cannot get Apitrace as requested, as on pure wayland, wined3d doesn't work, as it requires opengl, which is not availble for wayland.

### Log files
[hand_of_fate.log](https://github.com/doitsujin/dxvk/files/13981875/hand_of_fate.log)

**Comment by K0bin** [comment]
> 0148:fixme:vulkan:wine_vkAllocateMemory Using VK_EXT_external_memory_host
0148:fixme:vulkan:wine_vkAllocateMemory Not found compatible memory type

That sounds like 32on64 is not yet working for WineVulkan.

**Comment by ya-isakov** [comment]
Hmm, I'll try to find 32-bit vulkan game, then, to confirm, thank you!

**Comment by ya-isakov** [comment]
Found SuperTuxKart, which supports both vulkan and 32-bit binaries on Windows, and, yes, it fails with a bit different error, but, still related with vkAllocateMemory:
```
0120:fixme:vulkan:wine_vkAllocateMemory Using VK_EXT_external_memory_host
015c:err:virtual:allocate_virtual_memory out of memory for allocation, base (nil) size 02000000
```
And 64-bit build perfectly. So, closing this ticket, sorry for the noise!
