### ISSUE TITLE
How do I provide Steam Proton with a path to DXVK DLLs?

### ISSUE THREAD

**Issue by eugrus** [doitsujin/dxvk#3806]
I've got DXVK from a binary archive on GitHub. Now I have DLLs in /opt/dxvk-1.10.3/x32 and /opt/dxvk-1.10.3/x64/
Also did run the setup script that copied some DLLs to ~/.wine/dosdevices/c:/windows/system32/
Copying them manually into ~/.steam/steam/steamapps/compatdata for each particular games would be tedious. Could I provide a full path to DLLs via WINEDLLOVERRIDES or some other env vars ("launch option" on Steam)?

**Comment by eugrus** [comment]
Well, looks like Steam does include dxvk on its own and doesn't rely on the system...

Will have to look into other reason why my Vulcan layer doesn't work for DirectX

**Comment by ryao** [comment]
This is filed against the wrong project. You want:

https://github.com/ValveSoftware/Proton

**Comment by K0bin** [comment]
Yes, Proton does indeed already ship a newer version of DXVK than 1.10.3. Make sure your driver is installed correctly.

Feel free to reopen the issue when you have logs you want us to take a look at.

**Comment by begin-theadventure** [comment]
Symlink to steamapps/common/Proton /dist/ lib lib64 /wine/dxvk

**Comment by eugrus** [comment]
> Yes, Proton does indeed already ship a newer version of DXVK than 1.10.3. Make sure your driver is installed correctly.
> 
> Feel free to reopen the issue when you have logs you want us to take a look at.

I've been told that 1.10.3 were the last version of DXVK with support for GeForce GT 730M / nvidia-tesla-470-driver - is that correct?

**Comment by K0bin** [comment]
Yes, that is correct and that would also be why Proton doesn't work on your system.

**Comment by Blisto91** [comment]
Proton 7.0-6 is the last proton version before the driver bump. Includes dxvk 1.10.x
