### ISSUE TITLE
[DIRTY TEXTURE RENDERING WRONG]: Resident Evil 3 Crossover

### ISSUE THREAD

**Issue by niosz** [doitsujin/dxvk#3810]
Hi,
i've made an intensive tests of the problem with various configuration and DXVK versions, MoltenVK versions, Crossover versions, Wine versions.... for try to fix or help to solve the rendering issue, not jet found the problem.

In all versions combinations still remain following bad rendering about (i think) skin effect shader present in RE3 (non-rt DX11).
Same game (non-rt DX11) running with AGTK not present this bad visualization, but rendering perfectly.

SOME SCREEN SHOTS : 
![Screenshot 2024-01-18 alle 11 59 17](https://github.com/doitsujin/dxvk/assets/58999172/0ec12f3b-fb45-44b0-9312-a34eb0f66a3b)

![Screenshot 2024-01-18 alle 12 05 14](https://github.com/doitsujin/dxvk/assets/58999172/587e5162-a88f-4aa9-ab68-1a4bcfeb5eda)

![Screenshot 2024-01-18 alle 11 13 05](https://github.com/doitsujin/dxvk/assets/58999172/10b5fd0d-63ff-48c6-a454-d0e21a2c1a0a)

<img width="1007" alt="Screenshot 2024-01-18 alle 11 12 23" src="https://github.com/doitsujin/dxvk/assets/58999172/fec5ab8d-b524-4f5e-b9ba-09daf082ad4d">

MAIN TEST VERSIONS (others are mixing libraries with custom wine alterations)
crossover 23.7.1, 23.0.1, 22.1.1, 22.0.1, 22.0.0, 21.0.1

Operative system : Sonoma 14.2.1
Apple M2

**Comment by Blisto91** [comment]
Sorry but old dxvk versions are not supported (i assume you can't use 2.3) and MacOS isn't officially supported either by this project.
Without having checked ingame on Linux yet i assume this is more likely a MoltenVK problem and so it's probably better to make a issue at their repository.

**Comment by K0bin** [comment]
What Blisto said.

Mac OS is not a supported platform for DXVK and this is a MoltenVK bug anyway given that the game renders fine on both AMD and Nvidia GPUs.
