### ISSUE TITLE
Some NVIDIA GameWorks effects disappear as a graphics option

### ISSUE THREAD

**Issue by kesu1** [doitsujin/dxvk#3814]
Some graphics options disappear when using DXVK.
Options that disappear are NVIDIA GameWorks related like HFTS shadows and TXAA, but not PCSS.
Tried DXVK versions: 1.3.3 and 

### Software information
- Watch Dogs 2 version 1.17 (latest patch)
- On Windows 11 build 22631.3085

### System information
- GPU: RTX 3070
- Driver: 551.23
- Wine version: not relevant (Windows)
- DXVK version: 1.3.3 and 2.3

**Comment by kesu1** [comment]
Putting the config in does not make it appear.
Tried with DXVK 1.3.3 because 2.3 crashes the game with or without the config suddenly. (this did not happen before; could start the game just fine with v2.3)
`WatchDogs2_dxgi.log` has these lines in it, so the config is loaded successfully:
`info:  Effective configuration:`
`info:   dxgi.hideNvidiaGpu = False`

**Comment by kesu1** [comment]
UPDATE: Successfully loaded the game with DXVK 2.3 (possibly by closing Afterburner and RTSS) and TXAA appears again, but not HTFS shadows.

**Comment by doitsujin** [comment]
HFTS might require NVAPI extensions to work, which we don't support (and wouldn't be able to on Windows anyway).
