### ISSUE TITLE
[d3d9] UNDER NIGHT IN-BIRTH II Sys:Celes, minor texture misalignment

### ISSUE THREAD

**Issue by FrozenFish24** [doitsujin/dxvk#3818]
A very minor issue in Under Night II, the circular gauge in the bottom middle of the screen is slightly misaligned. It looks to be drawn in quadrants, which are slightly off in dxvk.

dxvk:
![under night dxvk](https://github.com/doitsujin/dxvk/assets/12547453/afc17796-df44-4685-bd70-7b2c3c0a7932)

windows:
![under night windows](https://github.com/doitsujin/dxvk/assets/12547453/e7ef01cc-f5a4-41ce-ae00-6177a964651e)

wined3d:
![under night wined3d](https://github.com/doitsujin/dxvk/assets/12547453/033de67f-121c-4397-b42e-84a75031ae20)

### Software information
UNDER NIGHT IN-BIRTH II Sys:Celes

### System information
- GPU: GTX 1070ti
- Driver: 545.29.06
- Wine version: proton experimental-8.0-20240111c
- DXVK version: 2.3-28-geb806952d8d0da9

### Apitrace file(s)
https://mega.nz/file/VIAhkQDA#f3QdlxPbFcPz5B3wLaVZl25d87skmKcsXqKzKQDnfdM

### Log files
[steam-2076010.log](https://github.com/doitsujin/dxvk/files/14071239/steam-2076010.log)

**Comment by Blisto91** [comment]
Hello and thanks you for the issue.

I have bisected this to start appearing since https://github.com/doitsujin/dxvk/commit/65635b23c1e8575362722c99e6ffdf9d9df64116

Tested on a RX 6800 with radv main

**Comment by FrozenFish24** [comment]
Thanks @Blisto91!

**Comment by FrozenFish24** [comment]
Thanks for the fix @Blisto91 🙂
