### ISSUE TITLE
[GTA IV CE (Steam)] I use all methods to remove VRam restrictions in-game, but nothing work for me

### ISSUE THREAD

**Issue by NightWolf69** [doitsujin/dxvk#3822]
I drag-n-drop all files from "`dxvk-2.3.tar.gz`" archive, from "x32" folder, into root game folder.

After that, I download "`dxvk.conf`", and uncomment two line:
```
dxgi.maxDeviceMemory = 4096
dxgi.maxSharedMemory = 4096
```
![dxvk conf](https://github.com/doitsujin/dxvk/assets/72456318/2d8157e1-3ff9-44a3-aaf2-a504a860b851)

After that, I create the text file «`commandline.txt`», and add to it three command:
`-avaliblevidmem 4096 -nomemrestrict -norestrictions`
![commandline txt](https://github.com/doitsujin/dxvk/assets/72456318/0099d36c-3614-4364-bc79-a3ee1b2b1d7f)

After that, I also add launch options in steam, with the same commands:
![Steam](https://github.com/doitsujin/dxvk/assets/72456318/044a8f9d-cc85-4d98-825b-d6e2a1a78ce0)

My GTA IV request the Rock Star Game Launcher, when I start the game from the Steam.
In RSGL, I don't have any places to set the launch options
![RockStar Game Louncher](https://github.com/doitsujin/dxvk/assets/72456318/d91f1ab3-7db9-4949-8543-02847de4dd52)

After all of this, in graphic options I see only **512Mb** of VRam, instead of **4096Mb** that I sets and have...
![20240128072540_1](https://github.com/doitsujin/dxvk/assets/72456318/3ab9c7a6-6233-4adf-ac41-cb3778a738e5)
![20240128072948_1](https://github.com/doitsujin/dxvk/assets/72456318/8baddb72-b9a2-4613-acee-4439a7fbdfcc)

Someone, please tell me, what I'm doing wrong? 🙏

### Software information
Grand Theft Auto IV: The Complete Edition (Steam) - _Latest Steam version, without any mods installed_

### System information
- CPU: Intel Core i7-4790k CPU 4.00GHz
- GPU: Nvidia GeForce GTX 960 GDDR5 (128bit) 4096MB
- Driver: 551.23 (Game Ready)
- RAM: Kingston HyperX FURY Black DDR3-1600 4x8 32768MB PC3-12800
- OS: Win10 Pro 22H2 (build 19045.3930)
- Wine version: N/A
- DXVK version: 2.3

**Comment by NightWolf69** [comment]
I've checked, if the «`commandline.txt`», «`dxvk.conf`» and the `Steam launch options` if they work. Yes, they work.
In **Steam** and **commandline** I was sets the resolution options, and they actually work, and change the game resolution.
In «`dxvk.conf`» I was change the aspect ratio, and it also works, and it changes the game aspect ratio.

**Comment by Blisto91** [comment]
You have a spelling error in your launch options. It's `-availablevidmem` not `-avaliblevidmem`.

You can also remove the extra config options and dxvk files besides `d3d9.dll`. While GTA IV is one of the rare d3d9 games that also interact with dxgi (added in a post release game update afaik) it wants to load it from the system folders and not the local one so it doesn't add anything to try and use it on Windows. 
At least out of the box without using some external tools to force load the local one. But i don't have any experience with that and it isn't necessary as it just needs d3d9 to render.

**Comment by NightWolf69** [comment]
> You have a spelling error in your launch options. It's `-availablevidmem` not `-avaliblevidmem`.

Omg, it really is, I feel myself so dumb... Thank you!
