### ISSUE TITLE
MySims (PC) Select Bug

### ISSUE THREAD

**Issue by Blayer98** [doitsujin/dxvk#3825]
A bug is causing the areas where you can click on your Sim’s clothing, hairstyle, facial features, building pieces while building homes, and the areas to paint walls, floors or building pieces to instead be located at the top middle of the screen, this also causes the game to be unplayable on new save games since you cannot progress the tutorial after entering build mode to create your house.

I figured I’d post this here since I’m not sure what is causing the bug, if it’s wine or DXVK.

I did see a post regarding the MySims Wii titles where the same issue occurred in Dolphin for a user, and supposedly, setting EFB Copies to RAM fixed the issue, which could mean it’s due to textures? I’m not entirely sure.

### Software information
MySims (PC)
Application Type: 32-Bit
Resolution: 1280x800
Fullscreen: Yes

### System information
- GPU: AMD AMD Custom GPU 0405 (vangogh, LLVM 15.0.7, DRM 3.54, 6.1.52-valve9-1-neptune-61)
- Driver: 4.6 (Compatibility Profile) Mesa 23.1.3 (git-58f7632462)
- Wine version: 8.0 (Proton Experimental)
- DXVK version: v2.3-28-geb806952d8d0da9

### ApiTrace files
https://drive.google.com/file/d/1JHTwm1POpFewKKkZr_YoMRJnwIIgatoQ/view?usp=drive_link

### Log files
[steam-15313046569196978176.zip](https://github.com/doitsujin/dxvk/files/14103354/steam-15313046569196978176.zip)
Sorry, I have to provide the proton log as a zip file due to the size of the log file, I’m not sure why it’s so large…

**Comment by Blisto91** [comment]
The apitrace doesn't seem downloadable unless one has been given access.

> I’m not sure what is causing the bug, if it’s wine or DXVK.

You can try launching the game with `PROTON_USE_WINED3D=1 %command%` so it will run without dxvk if that works. If it then doesn't occur, while not a 100% guarantee, it's usually a good indication whether it's a dxvk issue.

**Comment by Blayer98** [comment]
Hi there, sorry I’ve just tried to allow access, can you download it now?

Yes, I was apitracing, which is why I had the d3d9.dll in the game folder. :)

I’ve just tried it without DXVK and I used PROTON_USE_WINED3D=1 and now, the selectable area is in the dead Center of the screen, not on the top middle like before when I ran with DXVK normally…

**Comment by Blisto91** [comment]
You mean it is also buggy with wined3d but in s different way?

**Comment by Blayer98** [comment]
> You mean it is also buggy with wined3d but in s different way?
> 
> Edit: Yes i can download now

Yeah, the select bug also happens on wined3d, the hitboxes are just in the Center of the screen rather than the top middle of the screen.

**Comment by Blisto91** [comment]
How did you get it running with Proton? I am having issues even getting it to launch without instant crashing through the EA app

**Comment by Blayer98** [comment]
I installed the game via a physical copy of the game I have, and I have an external disc drive that I installed the game with, then I ran the DirectX setup, and also installed the VP6 encoding on the prefix since I have The Sims 3 installed on my Steam Deck as well, and then I let the disc check do it’s thing when I launch the game and then once the EA logo pops up I can simply take the disc out and disconnect the drive. :)

**Comment by Blayer98** [comment]
@Blisto91 Sorry for the tag, did you manage to figure anything out from the apitrace at all? :)

**Comment by Blisto91** [comment]
I can't look at it from a technical point of view as i am just a tester. I didn't see any difference in trace between playing it with and without dxvk so i am unsure how useful it is.

Plan to check it out on Windows and see if it behaves with dxvk there

**Comment by K0bin** [comment]
![image](https://github.com/doitsujin/dxvk/assets/1131720/2abc7a0d-5add-4372-a187-045c626ab110)

Looks fine to me?
Please post some screenshots and how it's supposed to look. I don't quite understand your explaination of the problem.

**Comment by Blayer98** [comment]
@K0bin Did you try and attempt to select the walls and flooring while in paint mode? Because it doesn’t work for me in both DXVK (Proton) and also WineD3D…

**Comment by K0bin** [comment]
Ah so it uses D3D9 to determine what your mouse is hovering over and that's wrong when using D3D9, right?

**Comment by Blayer98** [comment]
> Ah so it uses D3D9 to determine what your mouse is hovering over and that's wrong when using D3D9, right?

I think that might be what’s happening, the same issue can be reproduced while building houses

**Comment by Blayer98** [comment]
https://github.com/doitsujin/dxvk/assets/6663677/c6681693-0558-4716-848e-43fd25902474

Here’s a video demonstrating the issue, same thing happens with this “select bug”

**Comment by Blisto91** [comment]
I have confirmed dxvk to introduce this issue on Windows just as a quick fyi.
Not a regression as it also shows with d9vk 0.13f and dxvk config options haven't been found to influence it

**Comment by K0bin** [comment]
That PR above reportedly fixes the issue.

**Comment by Blayer98** [comment]
Great! 😁 Weird they relied on an error to get the result they wanted, maybe that’s due to how the game was ported from Wii to PC?

**Comment by K0bin** [comment]
Thanks for the good bug report.
