### ISSUE TITLE
Call of Duty Black Ops 1 can't set resotluion higher than 1440x1080 on a 2560x1440 monitor

### ISSUE THREAD

**Issue by KoleckOLP** [doitsujin/dxvk#3829]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Call of Duty Black Ops 1, I can't seem to be able to set any resolution than 1440x1080 even tho my monitor is 2560x1440
so I can't use 1080p or 1440p
I can't go higher even in windowed mode.

### System information
- GPU: Nvidia Geforce RTX 3070
- Driver: 551.23
- Wine version: I'm on Windows 10
- DXVK version: 2.3, 2.2, 2.1, I didn't try older

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

**Comment by KoleckOLP** [comment]
[BlackOps_d3d9.log](https://github.com/doitsujin/dxvk/files/14151143/BlackOps_d3d9.log)

**Comment by Blisto91** [comment]
Try with latest master https://github.com/doitsujin/dxvk/actions/runs/7758776435

**Comment by KoleckOLP** [comment]
With the latest master it works correctly, prolly no need for the log but here it is anyway.
[BlackOps_d3d9.log](https://github.com/doitsujin/dxvk/files/14151861/BlackOps_d3d9.log)

**Comment by Blisto91** [comment]
Sounds good. The fix made it in recently and so isn't in a stable release yet. https://github.com/doitsujin/dxvk/issues/3214#issuecomment-1900723570
