### ISSUE TITLE
World Of Tanks renders garbage on RADV.

### ISSUE THREAD

**Issue by leonmaxx** [doitsujin/dxvk#383]
In WoT 1.0.1 instead of hangar with tank i see only garbage, but UI is rendered correctly.
Screenshot: https://imgur.com/a/ewJ4wVz
I'm not sure if it's DXVK bug or Mesa bug.

### World Of Tanks 1.0.1
Both "Standard" and "Improved" graphics engines rendered garbage.

### System information
- GPU: AMD Radeon R9 Fury
- Driver: Mesa 17.3.9
- Wine version: 3.8-staging
- DXVK version: 0.51

### Apitrace file(s)
* Still trying to get apitrace running under wine.

### Log files
- d3d11.log: [WorldOfTanks_d3d11.log](https://github.com/doitsujin/dxvk/files/2019519/WorldOfTanks_d3d11.log)

- dxgi.log: [WorldOfTanks_dxgi.log](https://github.com/doitsujin/dxvk/files/2019520/WorldOfTanks_dxgi.log)

**Comment by leonmaxx** [comment]
Without DXVK (on wined3d) it doesn't get that far, it fails right after login with:
```
0042:fixme:d3d_shader:shader_glsl_handle_instruction Backend can't handle opcode dcl_input_ps_sgv.
apitrac0042:fixme:d3d_shader:shader_glsl_handle_instruction Backend can't handle opcode dcl_input_ps_sgv.
e: warning: caught exception 0xc0000005
```
If I get apitrace of WoT on Windows 7 will it help?

**Comment by Kerrung** [comment]
@leonmaxx, please, read that:
https://github.com/doitsujin/dxvk/wiki/Driver-support

**Comment by leonmaxx** [comment]
Oh, sorry, it was some time since I read your driver support page.
Closed.
