### ISSUE TITLE
Is possible run command inside Steam Proton for install DXVK alternate versions ?

### ISSUE THREAD

**Issue by Augusto7743** [doitsujin/dxvk#3830]
Hello.
Thanks for reading my topic.
Here Ubuntu 20.04.6 and Steam for Linux with Proton 8 and Experimental.
Is possible run command for internally install DXVK current and alternate versions inside Steam Proton installation ?
Only manually copying DXVK files not work. Is as if need change in registry settings too.

Have an nice day.

**Comment by Blisto91** [comment]
It should work if you replace the Proton dxvk files that Proton copies over.
So e.g if i wanted to replace them in Proton Experimental i would extract them in `~/.steam/steam/steamapps/common/Proton - Experimental/files/lib64/wine/dxvk/` (default system install path not using flatpak or similar) for the 64-bit files. And also do the same for 32-bit in it's respective path.
Though note these will be overwritten when the Proton files are updated.

**Comment by Augusto7743** [comment]
Thanks very much for your reply.
I have done exactly it. Not work and that error not is related with video card drivers or game trying load own d3d files.
I want try install dxvk using command because the install mode does changes in registry settings. Perhaps doing it can work.

**Comment by Blisto91** [comment]
All the wine overrides using the old install script are already default in Proton.
Anyway the method above should work if the game is also using the same proton as the one you replaced the files in as that is how it is commonly done.

**Comment by Sterophonick** [comment]
@Augusto7743 You can also copy the files from the DXVK release that you want into the executable's directory since both Windows and WINE prioritize the nearest DLL it can load, it'll work by default in Proton since the necessary DLL overrides are already set.

**Comment by Blisto91** [comment]
Do note though that for some games it's possible for that to lead to a situation where it will try to some of the dxvk files from the local folder and some of the dxvk files from the system folder. So it can be finicky.
Though for most part games should be fine in general with it. Just something to keep in mind

**Comment by Augusto7743** [comment]
I have done copy of dxvk old version compatible with kepler in correct paths and not work.
Well ... I have done an test using Proton 7 and was possible run a DX11 game using kepler.
Perhaps doing an test downloading an DX12 demo is possible see if run using Proton 7 with kepler.
Have some good DX12 games not requiring powerful GPUs .. perhaps can run in kepler.

However I want understand if is possible run command or scripts internally for Proton.
Thanks for all replies.

**Comment by Blisto91** [comment]
You could modify the proton script in your proton installation i guess, but that would also get overridden when a Proton update occurs ofc.
