### ISSUE TITLE
Which file version should i choose for AMD graphics card

### ISSUE THREAD

**Issue by CiPH3R-NFS** [doitsujin/dxvk#3832]
My friend got a AMD Radeon RX 560X
I know to pick 32bit for old games
but since he got AMD card which file should i go with to work for AMD card
D3d9, D3d10core, D3d11 ?

**Comment by Blisto91** [comment]
Depends on what the game uses. If it uses d3d9 then usually only `d3d9.dll` is nedded. For d3d11 games you need `d3d11.dll` and `dxgi.dll` and for d3d10 you need `d3d11.dll`, `dxgi.dll` and `d3d10core.dll`.
It's the same whether the card is AMD, Nvidia or Intel etc

**Comment by CiPH3R-NFS** [comment]
Ok so it doesn't matters which file i use
so I need to pick file as per game built
doesn't matter what GPU it is dxvk works universally

**Comment by Blisto91** [comment]
> doesn't matter what GPU it is and dxvk works universally

Yes as long as the Vulkan driver supports what dxvk needs.
That said some drivers might have more issues with dxvk in general than others.

**Comment by CiPH3R-NFS** [comment]
Noted
Thanks for your support
I'll troubleshoot more & find fix for AMD users
My friend is trying to run NFS MW 2005 & he gets black screen as in game is not loading entirely for him only game Ui is visible or it doesn't starts, but when he installs a AMD fix which contain d3d9.dll file & dgvoodoo.conf file game works all good but with some limitations, so Im trying to help him out with use of Dxvk+ his AMD GPU

**Comment by K0bin** [comment]
![image](https://github.com/doitsujin/dxvk/assets/1131720/aa224054-75c3-49b4-be2a-b8bc814be12c)

Works fine here. If the game doesn't work on AMD GPUs, I blame their drivers.

> but when he installs a AMD fix which contain d3d9.dll file & dgvoodoo.conf file game works all good but with some limitations

That "AMD fix" will replace the D3D9 implementation just like DXVK would. So there's no way to use that with DXVK.

**Comment by CiPH3R-NFS** [comment]
I as a modder for NFS MW made texture mod
which loads upto 2000 textures & i have NVIDIA card

I tested 2 different methods to troubleshoot Nextgengraphics is base mod which loads textures

> Method 1: without d3d9.dll, other d3d9 file with DX9 and Reshade DX9 d3d9 file in all 3 scenario textures do not load completely loads 50% and game crashes after couple minutes.

> Method 2: I use d3d9.dll file from dxvk-v2.3 32Bit and all textures are loaded without any errors and game crashes.

I know it's games fault, just trying to get an alternative working for AMD users
