### ISSUE TITLE
Regression in 2.3 Sends Guild Wars Framerate from 300+ Down to 1.5 FPS

### ISSUE THREAD

**Issue by ChthonVII** [doitsujin/dxvk#3837]
Title basically says it all. Prior versions of DXVK easily had 300+ FPS running Guild Wars on my hardware, but version 2.3 has 1.5 FPS. The system is basically locked up and I can't reliably alt+tab out to close the program.

### Software information
Guild Wars

### System information
- GPU: nvidia 1080
- Driver: 525.147.05
- Wine version: GE-Proton-8-26 (clarification: This is "wine GE proton," which doesn't expect a steam runtime and doesn't come with prepackaged DXVK binaries.)
- DXVK version: 2.3

I did not attempt api trace or logs due to the system being locked up. Perhaps someone with newer hardware might be able to.

(FYI: [The Guild Wars client](https://www.guildwars.com/en/download) can be downloaded for free, and the problem manifests immediately on the log-in screen, so reproducing this bug does not require an account.)

[Edit: It appears this problem is specific to the combination of [Wine-GE-Proton8-26](https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton8-26) and [dxvk 2.3](https://github.com/doitsujin/dxvk/releases/tag/v2.3). If I swap out dxvk 2.3 for 2.2, it works. If I swap out Wine-GE-Proton8-26 for vanilla wine 9.1 (devel), it also works.]

**Comment by Blisto91** [comment]
You mean that if you replace the dxvk files in Proton with an older version like 2.2 the issue stops?
Is that 2.3 stable or the one that comes with Proton GE?

**Comment by ChthonVII** [comment]
> You mean that if you replace the dxvk files in Proton with an older version like 2.2 the issue stops?

That is correct. Replacing the files with those from 2.2 fixes the problem.

> Is that 2.3 stable or the one that comes with Proton GE?

The problem exists with both the binaries from this repo and the binaries extracted from lutris.
("Wine GE Proton" builds don't come with DXVK binaries. Instead they expect lutris or heroic launcher to provide them.)

**Comment by jrugia** [comment]
Works fine here with below setup.

System information

    CPU: Intel i7-3770
    GPU: Nvidia GTX 1080
    Driver: 545.29.02
    Wine version: Wine Staging 9.0 (Flags used - WINEDEBUG=-all  WINEESYNC=0  DXVK_LOG_LEVEL=none)
    DXVK version: 2.3

![1](https://github.com/doitsujin/dxvk/assets/13750621/5763c4bc-f2d4-4283-8b6f-232e08085d7c)

**Comment by Blisto91** [comment]
I am not seeing an immediate difference here either between 2.2 and 2.3 on my RX 6800. This is ran through Lutris with Wine GE 26

@ChthonVII It would be interesting with some dxvk logs or Wine logs including dxvk output.
Also a screenshot of the game ran with `DXVK_HUD=full`. Or just a phone picture of the screen if the PC grinds too much to a halt for a proper screenshot

**Comment by jrugia** [comment]
It might be worth trying out a different Wine version.  I don't recall the exact version but it would tank the fps on this game as low as 20fps. Changing the Wine version was all I did and the performance went back up.

**Comment by ChthonVII** [comment]
@jrugia 

Yep, that seems to be it. The problem is specific to the combination of [Wine-GE-Proton8-26](https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton8-26) and [dxvk 2.3](https://github.com/doitsujin/dxvk/releases/tag/v2.3). If I swap out dxvk 2.3 for 2.2, it works. If I swap out Wine-GE-Proton8-26 for vanilla wine 9.1 (devel), it also works.

**Comment by Blisto91** [comment]
Did you come to a conclusion in regards to this? 👀

**Comment by ChthonVII** [comment]
> Did you come to a conclusion in regards to this? 👀

Only that the problem seems to be specific to the combination of this one particular version of dxvk and one particular version of wine-ge. So I just avoid this combination. As for what goes so terribly wrong when these two are put together, I haven't a clue.

**Comment by Blisto91** [comment]
When I tested myself I used that Wine version but wasn't at least immediately seeing anything off. This was on AMD though not Nvidia.

**Comment by mirh** [comment]
Can't you just try to bisect either of them?

**Comment by Blisto91** [comment]
Quickly tried logging in with my 4080 this time but i am not seeing an issue so far.

**Comment by Blisto91** [comment]
@ChthonVII Is there any update on this?

**Comment by jrugia** [comment]
I play the game occasionally every week.  Never noticed such an issue.

Played it again today under these conditions:

- Wine Staging 9.21
- DXVK 2.5
- GTX 1080 - Driver 560.xx (forgot exact version)

and

- Wine Staging 9.21
- DXVK 2.5
- RX 6800 - Mesa 24.2.6

**Comment by ChthonVII** [comment]
>Is there any update on this?

I stopped trying to get that particular version of wine-ge and that particular version of dxvk to work together. I've never reproduced the problem except with that specific combination.

Subsequently, the PC I was using died, so I don't even have that wine prefix anymore.

**Comment by Blisto91** [comment]
If the same issue shows up again feel free open again.
