### ISSUE TITLE
EVE Online - stuck at splash screen

### ISSUE THREAD

**Issue by HolimaX** [doitsujin/dxvk#3845]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
EVE Online - latest version with new launcher, including EVE Vanguard

### System information

```
$ inxi -Gxxx
Graphics:
  Device-1: Intel DG2 [Arc A770] driver: i915 v: kernel arch: Gen-12.7 pcie:
    speed: 2.5 GT/s lanes: 1 ports: active: HDMI-A-1,HDMI-A-2 empty: DP-1,
    DP-2, DP-3, DP-4, HDMI-A-3 bus-ID: 03:00.0 chip-ID: 8086:56a0
    class-ID: 0300
  Display: wayland server: X.org v: 1.20.14 with: Xwayland v: 22.1.9
    compositor: gnome-shell v: 44.8 driver: X: loaded: modesetting
    unloaded: fbdev,vesa dri: iris gpu: i915 display-ID: 0
  Monitor-1: HDMI-A-1 model: BenQ G2420HDBL serial: RAB03454SL000
    res: 1920x1080 dpi: 92 size: 477x268mm (18.78x10.55") diag: 604mm (23.8")
    modes: max: 1920x1080 min: 720x400
  Monitor-2: HDMI-A-2 model: Philips FTV serial: 16843009 res: 1920x1080
    dpi: 76 size: 640x360mm (25.2x14.17") diag: 734mm (28.9") modes:
    max: 1920x1080 min: 640x480
  API: EGL v: 1.5 hw: drv: intel iris platforms: device: 0 drv: iris
    device: 1 drv: swrast surfaceless: drv: iris wayland: drv: iris x11:
    drv: iris inactive: gbm
  API: OpenGL v: 4.6 vendor: intel mesa v: 23.1.9 glx-v: 1.4 es-v: 3.2
    direct-render: yes renderer: Mesa Intel Arc A770 Graphics (DG2)
    device-ID: 8086:56a0 display-ID: :0.0
  API: Vulkan v: 1.3.243 layers: 1 surfaces: xcb,xlib,wayland device: 0
    type: discrete-gpu driver: mesa intel device-ID: 8086:56a0 device: 1
    type: cpu driver: mesa llvmpipe device-ID: 10005:0000

$ sh Lejupielādes/winetricks list-installed
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20240105-next - sha256sum: 5068a499d055eb4fe83f10dcb870bd2a3ae7c65cf65bb997c117cba7a02eb2bc with wine-8.21 (Staging) and WINEARCH=win64
w_workaround_wine_bug-50894
ucrtbase2019
vcrun2019
d3dcompiler_43
d3dx9
d3dcompiler_47
dxvk
vcrun2013
```

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

[eve-online-backtrace.txt](https://github.com/doitsujin/dxvk/files/14207648/eve-online-backtrace.txt)

**Comment by Blisto91** [comment]
Might be worth trying a clean prefix https://github.com/doitsujin/dxvk/issues/3844#issuecomment-1932801681

I didn't reproduce any issues with the launcher when I tried to install in yesterday together with dxvk.

**Comment by EntropicEffect** [comment]
I had the same when they deprecated the old launcher. Reinstallling the launcher and game fixed the problem for me.

**Comment by HolimaX** [comment]
> I had the same when they deprecated the old launcher. Reinstallling the launcher and game fixed the problem for me.

What do you mean by "reinstalling"? Once CCP deprecated old one, they did forced in-place update. That means that after that you uninstalled newly installed EVE Online and installed it again and everything worked?

**Comment by HolimaX** [comment]
Seems like it magically got resolved afterv I did clean reinstall and used shell script to launch game directly from its install directory, instead of using shrtcut.

Closing.
