### ISSUE TITLE
[ENHANCEMENT] Custom Downsampling Resolution

### ISSUE THREAD

**Issue by shinra358** [doitsujin/dxvk#3846]
Hello, i would like to request the ability to in put a custom resolution and if it exceeds what the device can handle, it will automatically downsample the internal resolution to fit the current monitor's resolution like in dgvoodoo2.

**Comment by ZeusThundr** [comment]
I'm unfamiliar with dgvoodoo2 but you might find success using [gamescope](https://github.com/ValveSoftware/gamescope) on Xorg from what I've heard this might not work on Wayland. try something like in steam launch options `gamescope -f -w 1600 -h 900 %command%` or in lutris in the system options section you can enable gamescope and adjust various settings in the lutris gui.

**Comment by shinra358** [comment]
im on windows 10, is that for that OS?

**Comment by Blisto91** [comment]
Hi there.

> im on windows 10, is that for that OS?

No it's a Linux only thing.

As of writing the previous reply on such a request is still valid. See https://github.com/doitsujin/dxvk/issues/1539#issuecomment-605723214
So it isn't on the table for dxvk to implement something like this and Linux users are referred to use something like gamescope as said above.
