### ISSUE TITLE
[ENHANCEMENT] Phong Lighting

### ISSUE THREAD

**Issue by shinra358** [doitsujin/dxvk#3847]
I would like to request the graphical option of enabling phong lighting

**Comment by Joshua-Ashton** [comment]
That's not how this works, DXVK uses shaders from the game.

**Comment by shinra358** [comment]
Dgvoodoo2 does it and this is similar so i thought this would be able to as well. Maybe i dodnt say it corrected but i believe it uses shaders from the game also

**Comment by K0bin** [comment]
DGVoodoo2 mostly targets older graphics APIs and games than DXVK where this is possible.
