### ISSUE TITLE
supercan game dxvk Error E1005 Out of memory

### ISSUE THREAD

**Issue by kaplan-025** [doitsujin/dxvk#3851]
Please describe your issue as accurately as possible.
not working with apitrace no trace file is generated game won't open
[supercan_d3d9.log](https://github.com/doitsujin/dxvk/files/14279021/supercan_d3d9.log)
the game opens, in the main menu I say start game and the game gives this error Error E1005 Out of memory
![Ekran görüntüsü 2024-02-14 064151](https://github.com/doitsujin/dxvk/assets/160018739/712e59bb-1477-49c2-a7df-de8728306108)
![Ekran görüntüsü 2024-02-14 150257](https://github.com/doitsujin/dxvk/assets/160018739/3c19ac7b-133d-4a08-8cca-3179f199cb98)

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Name of the game, settings used etc.
supercanoyun free game
https://fb.watch/qcnBt7gr-0/

### System information
- GPU: AMD Radeon™ RX 5500 XT 8gb OC 
- Driver: 31.0.24002.92
- Wine version: DXVK on Windows
- DXVK version: 2.3

### Apitrace file(s)
- Put a link here
- not working with apitrace no trace file is generated game won't open

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

**Comment by Blisto91** [comment]
Where do you download it. The Facebook links doesn't work for me and I'm having trouble figuring our their own website.

**Comment by kaplan-025** [comment]
@Blisto91
links on facebook page downloading from here does not support https browser gives privacy error
Press Advanced and then continue to 93.155.106.35, click on Continue and the game installation file will download
http://93.155.106.35/SuperCan/supercan_setup.exe
http://93.155.106.35/SuperCan/supercan2_setup.exe

**Comment by Blisto91** [comment]
I think you didn't mean to close the issue.

I am not immediately reproducing any issues when testing on Nvidia through Proton on Linux (even when i disable forced LAA). 
This is with maximum settings and playing through the first small level.
<details>
  <summary>Screenshot</summary>

![image](https://github.com/doitsujin/dxvk/assets/47954800/5f2bb34a-df66-457c-a854-d860cc8d1253)
</details>
