### ISSUE TITLE
The Hurricane of the Varstray -Collateral hazard-: Starting crash

### ISSUE THREAD

**Issue by waspennator** [doitsujin/dxvk#3853]
On Windows without DXVK it works fine, as soon as I put the DX11 api in, it crashes with this weird message.
![Screenshot 2024-02-14 221848](https://github.com/doitsujin/dxvk/assets/78768499/78cef500-3bd4-456d-8d8b-a299695b5271)

On my oled Steam Deck with latest proton experimental build, it just launches, then silently crashes after being on a black screen for a few seconds, from personal testing and checking the proton report for the game, it worked with 6.3-5 (DXVK 1.9) and started breaking on deck somewhere between 6.3-8 (DXVK v1.9.2-13-g714ca482)

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
The Hurricane of the Varstray -Collateral hazard-

### System information
- GPU: AMD Van Gogh for Steam Deck, GTX 1650 for the Windows Laptop
- Driver: Mesa 23.1.3 for Steam Deck, Nvidia 551.52 for Windows Laptop
- Wine version: 8.0
- DXVK version: Latest nightly at the time (2/14/24, [d3d9] Fail GetRTData if src and dst have mismatching sizes)

### Apitrace file(s)
Tried getting an Apitrace for it, but every time I try it crashes with this message.
![Screenshot 2024-02-14 222437](https://github.com/doitsujin/dxvk/assets/78768499/b9dbc9d7-8caa-4ca4-8dba-73f3dd865eb2)

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
[Varstray_steam_d3d11.log](https://github.com/doitsujin/dxvk/files/14291839/Varstray_steam_d3d11.log)
[varstray_steam_crash_2024_2_15T5_18_50C0.zip](https://github.com/doitsujin/dxvk/files/14291847/varstray_steam_crash_2024_2_15T5_18_50C0.zip)

Proton log from Steam deck
[steam-416380.log](https://github.com/doitsujin/dxvk/files/14291902/steam-416380.log)

**Comment by Blisto91** [comment]
Could you on Steam Deck try installing the Windows native version of `d3dx11_42` with winetricks or protontricks and see if it makes a difference?

In regards to the Windows logs, assuming you copied both `d3d11.dll` and `dxgi.dll`,  i can see that the game appears to want to use the dxgi from the system folders so it likely never worked with dxvk there.

> warn:  D3D11InternalCreateDevice: Adapter is not a DXVK adapter

**Comment by waspennator** [comment]
Actually I just tried it with both files on windows "d3d11.dll and dxgi.dll" and it works, so it seems like I goofed up and forgot about it.

I'll try installing d3dx11_42 on deck though and see if it changes anything.

**Comment by Blisto91** [comment]
Coolio sounds good.
d3dx11 is not implemented by dxvk so this is a Wine issue. If you could mention it in the Proton issue for the game that would be great.

I can see there are already issues created on the upstream Wine tracker about the two d3dx11 functions that gets mentioned. Going to make a note of it.
