### ISSUE TITLE
Ultra Street Fighter 4 - Game with DXVK runs only in Borderless Windowed Fullscreen?

### ISSUE THREAD

**Issue by pokeshark** [doitsujin/dxvk#3854]
Ultra Street Fighter 4 runs in exclusive fullscreen usually.
with DXVK, the game runs in borderless windowed fullscreen, although I haven't changed any settings.

How can I force exclusive fullscreen from dxvk.conf?

### Software information
Ultra Street Fighter 4 - Fullscreen On, 1440p

### System information
- GPU: AMD RX6600XT
- DXVK version: dxvk-2.3 (d3d9.dll, 32 bits)

Log: 
[SSFIV_d3d9.log](https://github.com/doitsujin/dxvk/files/14314367/SSFIV_d3d9.log)

**Comment by qinlili23333** [comment]
How do u distinguish borderless or exclusive fullscreen? If u use volume key or Win+G, the fullscreen optimization on win10+ may describe why u got this.
FSO is a feature introduced from win10 that converting exclusive fullscreen to borderless with flip model. When FSO works, u may recognize the game always runs in borderless mode even set to exclusive fullscreen. Sometimes a game is not compact with FSO so the system disabled it, however DXVK may makes it qualified for FSO (how windows detect a game is qualified is unknown, as windows is not opensourced), this is what u see on ur device.
U can use https://github.com/GameTechDev/PresentMon to check the game.
> 'Hardware: Legacy Flip' indicates true exclusive fullscreen, but not borderless. 'Hardware Composed: Independent Flip' indicates either fullscreen optimized or borderless. Finally, both 'Composed: Copy with GPU GDI' and 'Composed: Flip' correspond to windowed presentation mode. (Quoted from https://www.reddit.com/r/vulkan/comments/m7m7e3/composed_flip_on_windows_10/  ) 
And only  'Composed: Copy with GPU GDI' will cost heavy GPU resouces for dwm compose. Any 'Hardware' method will not cost performance so u dont need to care whether it's exclusive.

On NVIDIA GPU, set vulkan present method to prefer DXGI swapchain can make most games with DXVK running in 'Hardware Composed: Independent Flip'. I'm not sure whether AMD has similar feature but some articles said it has.
