### ISSUE TITLE
DXVK suddenly causing game to be run as background process rather than app.

### ISSUE THREAD

**Issue by 909990999900** [doitsujin/dxvk#3858]
I'm new to this whole submitting issues thing so sorry if I do it wrong but basically I've never had a problem using DXVK before with this game, although the other day there was a small windows update(windows 11)and now whenever I launch this game it will not actually fully open and instead it will launch as a background process.  If I take out the DXVK 2.2 dll files it will launch as intended.

Vulkan will works fine on my system as I can plays emulators that use the backend no problem but for whatever reason reason I just can't get this game to launch with any version of DXVK I have for some reason. Any advice would be greatly appreciated 

I also know for a fact it's not my gfx driver as the game and DXVK already worked on it a few days ago it stopped working after some windows update. I even rolled back my gfx version just to check and nothing 

### Software information
Game is. WWE 2k19 720P 

### System information
- GPU: amd radeon 760m
- Driver: version 24.1.1
- DXVK version: 2.2 or asych 1.6
[WWE2K19_x64_dxgi.log](https://github.com/doitsujin/dxvk/files/14318916/WWE2K19_x64_dxgi.log)

[WWE2K19_x64_d3d11.log](https://github.com/doitsujin/dxvk/files/14318912/WWE2K19_x64_d3d11.log)

**Comment by K0bin** [comment]
> info:  D3D11On12CreateDevice: Chosen feature level: D3D_FEATURE_LEVEL_12_1
err:   D3D11On12CreateDevice: Device not a vkd3d-proton device.

The game is trying to use D3D11On12 which only works together with VKD3D-Proton.
It also probably doesn't work on Windows.

**Comment by 909990999900** [comment]
So what does that mean? Or what can I do about it? Again the game ran completely fine on Monday with the same gfx driver.

**Comment by 909990999900** [comment]
> > info:  D3D11On12CreateDevice: Chosen feature level: D3D_FEATURE_LEVEL_12_1
> 
> err:   D3D11On12CreateDevice: Device not a vkd3d-proton device.
> 
> 
> 
> The game is trying to use D3D11On12 which only works together with VKD3D-Proton.
> 
> It also probably doesn't work on Windows.


So what does that mean? Or what can I do about it? Again the game ran completely fine on Monday with the same gfx driver.

**Comment by K0bin** [comment]
Either try throwing in D3D12.dll from vkd3d-Proton and hope that works. If it doesn't, either play it without DXVK or install Linux.

**Comment by 909990999900** [comment]
> Either try throwing in D3D12.dll from vkd3d-Proton and hope that works. If it doesn't, either play it without DXVK or install Linux.

Ok thanks I'll try and give that a shot. I just wonder why it would stop working all of a sudden. It's an older game that used dx11. Is it trying to run it in dx12 now or something? 

Also I read somewhere that I didn't need dxgi and just the d3d11.dll 

This caused the app to actually launch but it crashed before it could fully open. 

Also the dxgi. DLL log if I delete my old existing ones is completely blank when you launch again so it's specifically that DLL that's causing the issue I think. 



And thanks for the help I really appreciate it

**Comment by K0bin** [comment]
> Also I read somewhere that I didn't need dxgi and just the d3d11.dll

That's wrong. D3D11 **always** needs DXGI and DXVK does not work with the DXGI provided by Windows itself.

**Comment by Blisto91** [comment]
Make sure you don't have this installed on your system https://github.com/doitsujin/dxvk/wiki/Windows#dozen

**Comment by K0bin** [comment]
> So was there something in the log showing why dxgi is causing it to run as a background process then?

It's not running in the background, it's basically not running at all. The game is trying to use D3D11on12 which, like I told you, doesn't work with DXVK unless you also install VKD3D-Proton.

> Last I removed dxgi all together and put the d3d12 and d3d12 core both from the proton download and the game now launches, tho I'm not sure dxgi is actually working?

Post some logs I guess. It's possible that the game is hardcoded to load D3D12.dll from C:\Windows\System32. That's a very common problem when trying to use DXVK on Windows.

> Also is it common for a game to just stop working with DXVK? Like literally nothing has changed it shouldnt be doing this. I've been searching for a solution for like 2 days now haha

It's possible that some other component on your system injects itself into the game and makes it use 11on12. Some kind of overlay for example. No idea what though.

It's kinda common for games to randomly stop working with DXVK **on Windows**. It's not at all common on Linux. We don't really support Windows because there are a lot of issues outside of our control that break DXVK. (Like this one)

**Comment by 909990999900** [comment]
> Make sure you don't have this installed on your system https://github.com/doitsujin/dxvk/wiki/Windows#dozen

thanks ill look into it, how would I even be able to tell?

**Comment by K0bin** [comment]
Search for the OpenCL™, OpenGL®, and Vulkan® Compatibility Pack in the Windows store and if it says "Installed" uninstall it.

**Comment by 909990999900** [comment]
> Search for the OpenCL™, OpenGL®, and Vulkan® Compatibility Pack in the Windows store and if it says "Installed" uninstall it.

It works now!! That was what was causing all this fucking bullshit.

**Comment by 909990999900** [comment]
> Make sure you don't have this installed on your system https://github.com/doitsujin/dxvk/wiki/Windows#dozen

That is what was causing the issue. Thank you so much man I just wasted 2 days trying to figure this out so your a fucking hero
