### ISSUE TITLE
Crash introduced in  [d3d9] Upload DYNAMIC+SYSMEM vertex and index data for each draw (!5312ef1)

### ISSUE THREAD

**Issue by R1chterScale** [doitsujin/dxvk#3860]
Running a copy of New Vegas using the New Vegas Reloaded graphics mod and noticed a replicable crash was present when starting a new game (and in a few other areas) when on the latest commit. Git bisect revealed it to be [d3d9] Upload DYNAMIC+SYSMEM vertex and index data for each draw (!5312ef1)

### Software information
Fallout New Vegas with the New Vegas Reloaded mod (along with other general libraries and QoL mods, but NVR is the one that causes it, specifically the Interior Shadows setting).

### System information
- GPU: RX 7900XT
- Driver: Mesa-git (RADV)
- Wine version: 8.0 (from Proton-GE, but crashes on other versions)
- DXVK version: Built from commit 5312ef1

### Apitrace file(s)
[FalloutNVout.trace](https://mega.nz/file/AcUBkJIK#0IPaEzvTmKNJqMVBlD-ISMo0rxmTjco-1q7gYIqKjpI)
Worth noting is it had to be made with DXVK, WineD3D was not an option

### Log files
[game.log](https://github.com/doitsujin/dxvk/files/14337863/game.log)

**Comment by Blisto91** [comment]
Hello and thank you for the well made issue.

While i was reproducing ingame i took the liberty of making a trace with a older version of dxvk so it gets past the crash if that shows up to be useful to the devs. It still crashes when replayed with the offending commit.
https://drive.proton.me/urls/NDRYZRMZAR#NhFx277Hu4YE

**Comment by K0bin** [comment]
The mod ends up unbinding the index buffer before drawing with it. So it might accidentally rely on the behavior of #3852.

**Comment by R1chterScale** [comment]
Thanks again for looking at this and finding a fix so quickly :)
