### ISSUE TITLE
Lower FPS in GPU bound Scenarious

### ISSUE THREAD

**Issue by Kipas39** [doitsujin/dxvk#3866]
I was benchmarking games, DX (9,10,11) VS DXVK, and I noticed one tendency, if FPS locked on the same number with same graphics settings, GPU usage is higher with DXVK than just native DX. And in GPU bound scenarious i have lower FPS with DXVK than DX.

Is this GPU overhead related, just like GPU takes more time to transfer commands from DX to Vulkan, and we see lower FPS. Maybe this is related to the driver, or some Windows thing. Thank you in advance for your answer, I’m making a video on YouTube about DXVK performance in Windows and I want to check this point.

NFS Heat: DX11- 66% GPU Usage DXVK- 76% GPU Usage:
![Nested Sequence 02 00_14_09_27 Still002](https://github.com/doitsujin/dxvk/assets/160784539/e9a58df0-a35b-4809-80a6-f133a3df1b3f)

GPU bound scenario in NFS Heat: DX11- 77 FPS DXVK- 69 FPS:
![Nested Sequence 02 00_15_03_09 Still004](https://github.com/doitsujin/dxvk/assets/160784539/efd59019-b9fa-411a-8527-b07897007746)

Same with DX9, F.E.A.R.: DX9- 362 FPS DXVK- 273 FPS
![Nested Sequence 02 00_16_32_35 Still006](https://github.com/doitsujin/dxvk/assets/160784539/fa3f1ee0-4d3e-4bd0-9cd8-5c064bf890b4)

BUT in scenarios with CPU Bound FPS increasing, Dishonored: DX9- 339 FPS DXVK- 429 FPS
![Nested Sequence 02 00_17_13_46 Still007](https://github.com/doitsujin/dxvk/assets/160784539/104fd9e3-dd00-4287-adb5-e7b1fedc92bf)

So my question is why FPS lower in GPU bound scenarios.

### System information
- GPU: RTX 2060 6GB
- CPU: i5-12400F
- Driver: 551.23
- OS: Windows 11
- DXVK version: 2.3

**Comment by K0bin** [comment]
FPS is higher on the native graphics driver because it doesn't have to go through Vulkan and can thus generate more optimal shader code. The mapping of D3D to Vulkan isn't always perfect and Vulkan doesn't expose every single hardware feature perfectly either.
