### ISSUE TITLE
DXVK ac odyssey cpu spikes system freeze

### ISSUE THREAD

**Issue by lotloren** [doitsujin/dxvk#3868]
Using verson 1.3 with async
Driver version  - 442.59
1060 - 6 gb msi.
Basically game launches fine it gets the nice "boost" from dxvk but every 10 - 40 secons on irregular intervals CPU usage spikes up to 100 % and freezes for 4-5 seconds then in restores. I read that it could be shaders but I left for like an hour just standing there so that they can compile but the freezes continue. Also my cachefile " is only 280ish Kbs is that normal?
[ACOdyssey_d3d11.log](https://github.com/doitsujin/dxvk/files/14391806/ACOdyssey_d3d11.log)
[ACOdyssey_dxgi.log](https://github.com/doitsujin/dxvk/files/14391807/ACOdyssey_dxgi.log)

**Comment by mbriar** [comment]
Have you tried a more recent dxvk version and not ancient nvidia drivers? Neither old versions nor dxvk-async are supported here.

**Comment by K0bin** [comment]
> Also my cachefile " is only 280ish Kbs is that normal?

Yes, that is normal.

Your driver is indeed pretty ancient. Please try updating it.

**Comment by lotloren** [comment]
any newer driver than this one any game literally becomes unplayable stutterfest 471.96, 511.79 and so on so forth and yes I do DDU and consecutevily cuz I am stuck with 442.59 I can't use any of the newer dxvk version because at least of own shallow understanding they are not compatible with the older driver who doesnt support vulkan 1.3.

**Comment by K0bin** [comment]
Then you're on your own. We don't support outdated drivers.
