### ISSUE TITLE
[RESOLVED] witcher3.exe crash

### ISSUE THREAD

**Issue by 88i** [doitsujin/dxvk#387]
### Software information
The Witcher 3
Postprocessing: everything enabled except ambient occlusion
Graphics : low
System gamma: off
Hairworks: off
Hardware cursor: off
Other graphics settings: low or medium

KDE Plasma crashed when I tried to switch back to fullscreen wine TW3 from a different app. I needed to press the power button 3 seconds because switching to another TTY terminal also didn't work, the system was completely stuck.

### System information
- GPU: Nvidia GTX 1050 2GB
- Driver: 390.48
- Wine version:  wine-3.8 (Staging)
- DXVK version: 0.51

### Log files
[d3d11.log](https://paste.debian.net/plainh/9ca8d75b)

[dxgi.log](https://paste.debian.net/plainh/6ad30552)

### witcher3.exe_crash_20180420_181340733.crashinfo
[crashinfo](https://paste.debian.net/plainh/ef88f59d)

**Comment by Yardanico** [comment]
Try with latest nvidia drivers.

**Comment by doitsujin** [comment]
Please update your driver, DXVK doesn't support the 390 series.

**Comment by Kerrung** [comment]
@88i, known driver bug, already fixed in the latest version of Nvidia blob driver.

**Comment by Kerrung** [comment]
@88i, maybe you should close it?
