### ISSUE TITLE
Quake Champions: Major performance drop when splashing liquids.

### ISSUE THREAD

**Issue by ElectricLizzzard** [doitsujin/dxvk#3871]
Easy to reproduce: Enter the Awoken map, start shooting water floor with rockets. Works same with acid on Vale of Pnath or Lockbox.
Game just dropping framerate from 120-180fps to 20-30fps as soon someone splashes the water or acid, and when camera is pointed in that direction, even through walls.
 
Low settings, 1080p 100% rendering scale. Changing the "Advanced" settings not affecting anything.

- GPU: Radeon R9 380 RADV Tonga
- Driver: Mesa 22.3.6
- Wine version: GE-Proton-32
- DXVK version: dxvk-git

**Comment by ElectricLizzzard** [comment]
Oh, boy... I will try to set this thing up

**Comment by ElectricLizzzard** [comment]
> Hi there. Could I get you to make an apitrace?

Did that. The trace file is here but it's only 3.1KiB, which is not right. Done with WINED3D.

**Comment by doitsujin** [comment]
Game seems to run fine here; can you check on your end if any numbers are suspiciously high in the DXVK HUD when this happens?

**Comment by ElectricLizzzard** [comment]
This all i got. As soon i shoot the water i lose 15% or performance. When there is the 4v4 mayhem, my game turns into slideshow. All settings low, and even disabled fancy water features in advanced settings, unfortunately there is no *legal* way to disable the water.

![photo_2024-02-28_03-12-31](https://github.com/doitsujin/dxvk/assets/118171017/a6ff8e11-dd3e-457f-a937-01a82fa55b64)
![photo_2024-02-28_03-12-45](https://github.com/doitsujin/dxvk/assets/118171017/ae80514d-ca97-4cce-821f-80fead7456de)

**Comment by mbriar** [comment]
Post a screenshot of when it's actually at 20-30 fps. It's potentially just running out of vram. And maybe consider not running on 2 year old drivers.

**Comment by ElectricLizzzard** [comment]
> Post a screenshot of when it's actually at 20-30 fps. It's potentially just running out of vram. And maybe consider not running on 2 year old drivers.

In on Debian 12, all the same even with Mesa 24.
I can do that, but it has to be 4v4 online match on that particular map, on that particular part of the map. But i have and idea...

**Comment by ElectricLizzzard** [comment]
Not a DXVK bug. Quake Champions has a very small VRAM leak (had it since 2017) that slowly degrades the game, especially noticeable on long gaming sassions. The game uses maximum of 2800MB of VRAM on largest maps, and slowly VRAM usage getting up to higher and higher numbers until GPU getting out of VRAM. To resolve this you must just restart the game.
