### ISSUE TITLE
GTAIV.dxvk-cache file size

### ISSUE THREAD

**Issue by fenderjaguarnet** [doitsujin/dxvk#3874]
has anyone else noticed that the GTAIV.dxvk-cache file is not getting above 1kb nowadays?

I know you are going to say "we don't support windows", but it worked perfectly before.

also, it does not really stutter at all, so I should not complain, but I just wonder why the file is not increasing in size?

**Comment by mbriar** [comment]
The cache file is not necessary anymore in recent versions of DXVK and drivers that support VK_EXT_graphics_pipeline_library, other than for some edge cases with geometry and tesselation shaders. It being small and not growing is expected and not a problem.

**Comment by fenderjaguarnet** [comment]
> The cache file is not necessary anymore in recent versions of DXVK and drivers that support VK_EXT_graphics_pipeline_library, other than for some edge cases with geometry and tesselation shaders. It being small and not growing is expected and not a problem.
thanks for the quick reply

but I do not understand why with (gearbox) halo combat evolved, but cache file grows rapidly to over 300kb, and it stutters as its doing so for the first time when it 'see' the shader (but not again). with GTA IV, it does not stutter and only 1kb cache file.....

**Comment by K0bin** [comment]
Halo Combat Evolve might use fixed function rendering. DXVK generates shaders for each pipeline configuration. This can lead to a LOT of shaders which are also generated just in time when they are also needed for rendering, hence the stuttering.

GTA IV does not use fixed function rendering. It uses a limited number of shaders. mbriar is 100% correct.
