### ISSUE TITLE
Monster hunter world iceborne failed to start

### ISSUE THREAD

**Issue by sodomon2** [doitsujin/dxvk#3875]
Hi, I have installed Monster hunter world and tried to run it with dxvk 1.10.3 (my PC is haswell and only supports up to vulkan 1.2).

the game runs and everything works fine until I hit start game, when I do that in the middle of the load the game sends an error and closes the game, here below I leave the error

![MHw](https://github.com/doitsujin/dxvk/assets/49420637/cf79158b-8e4c-42ce-bf5f-2aa3597a8381)

the truth I do not know why this happens, try the game on another machine using the same dxvk and if it worked, do not know if it is a problem of the vulkan or if it is a problem with my PC

### Software information
Monster Hunter World Iceborne

### System information
- GPU: Intel HD Graphics 4600
- Driver: mesa-24.0.1
- Wine version: wine-9.0
- DXVK version: 1.10.3

### Log files
[game.log](https://github.com/doitsujin/dxvk/files/14449970/game.log)

**Comment by K0bin** [comment]
Vulkan support on any Intel GPU before Skylake is quite dodgy. Additionally we don't support outdated versions of DXVK. The game works on 2.3 on AMD, Nvidia and modern Intel GPUs.

**Comment by sodomon2** [comment]
> Vulkan support on any Intel GPU before Skylake is quite dodgy. Additionally we don't support outdated versions of DXVK. The game works on 2.3 on AMD, Nvidia and modern Intel GPUs.

Yes, I know that, but wouldn't there be a way to make it work?

I was able to run the game with WineD3D, but the performance is very bad, besides the graphical glitches.

try to do this issue https://github.com/doitsujin/dxvk/issues/3381#issuecomment-1522100178

but it still doesn't work.

**Comment by WinterSnowfall** [comment]
> Yes, I know that, but wouldn't there be a way to make it work?

Relieving some memory pressure might get it to work (at least longer). Not sure why you only have 1.5 GB of VRAM allocated to the GPU though, but that's up to the driver really. Are you on a 4 GB of RAM system by any chance?

> This error has only happened to me with MHW. With other games like Styx Shard of darkness everything worked normally and without errors, or dying light itself.

Honestly, consider yourself fortunate on this front.

**Comment by WinterSnowfall** [comment]
> My system has 4GB of ram, and the GPU ram is 2 (shared with the ram).

Ok, then there's not much you can really do on this hardware. The driver will typically allocate half the system memory for VRAM use in the case of Intel UMA at least.

Note that dxvk is known to take up a bit more VRAM than native d3d11 or opengl-based translations such as those done by WineD3D, so it's not a particularly good option on a memory-constrained system. You should be able to use it with most d3d9 games and possibly some d3d11 games, but MHW seems to need a bit more memory at the very least.

**Comment by sodomon2** [comment]
> > My system has 4GB of ram, and the GPU ram is 2 (shared with the ram).
> 
> Ok, then there's not much you can really do on this hardware. The driver will typically allocate half the system memory for VRAM use in the case of Intel UMA at least.
> 
> Note that dxvk is known to take up a bit more VRAM than native d3d11 or opengl-based translations such as those done by WineD3D, so it's not a particularly good option on a memory-constrained system. You should be able to use it with most d3d9 games and possibly some d3d11 games, but MHW seems to need a bit more memory at the very least.

Oh, I get it, I get it, it's still a little weird actually.

**Comment by WinterSnowfall** [comment]
> So, would the solution be to upgrade the hardware or just have a dedicated GPU?

Both would work - the main factor here being your budget.

For gaming purposes, it's obvious a dedicated GPU is highly recommended, but if you must have a thin-and-light laptop with only an iGPU for example, make sure it comes with as much RAM as you can afford, and that said RAM is reasonably fast, since it will double as your VRAM. 

More modern iGPUs (such as those based on Intel Xe for example, on the ones generally from AMD) pack more of a punch and are generally enough these days for light gaming on a budget, so it depends more on what else you intend to do with your system. The above still applies for desktop iGPUs, meaning you're really depended on your system RAM for VRAM size and performance.

**Comment by sodomon2** [comment]
> > So, would the solution be to upgrade the hardware or just have a dedicated GPU?
> 
> Both would work - the main factor here being your budget.
> 
> For gaming purposes, it's obvious a dedicated GPU is highly recommended, but if you must have a thin-and-light laptop with only an iGPU for example, make sure it comes with as much RAM as you can afford, and that said RAM is reasonably fast, since it will double as your VRAM.
> 
> More modern iGPUs (such as those based on Intel Xe for example, on the ones generally from AMD) pack more of a punch and are generally enough these days for light gaming on a budget, so it depends more on what else you intend to do with your system. The above still applies for desktop iGPUs, meaning you're really dependent on your system RAM for VRAM size and performance.

Okay, I think I understand, if I had I don't know, let's say 16GB of ram on this PC, maybe it could work?

I mean, because of the issue that the ram is shared with the VRAM.

**Comment by WinterSnowfall** [comment]
> Okay, I think I understand, if I had I don't know, let's say 16GB of ram on this PC, maybe it could work?

Perhaps. It would get you beyond the crash you're seeing now most likely, but there are no guarantees beyond that. As @K0bin also mentioned initially, using a Haswell iGPU in general is rather unfortunate in this day and age, especially in conjunction with Vulkan (therefore also dxvk). Having hardware with Vulkan 1.3 support and using the latest version of dxvk is a must both performance wise and when reporting issues here - older versions of dxvk are no longer supported at this point.
