### ISSUE TITLE
new vulkan extensions added to latest windows amd drivers but not loaded by dxvk

### ISSUE THREAD

**Issue by terry98** [doitsujin/dxvk#3878]
Hi, mostly as the title says I have just installed latest windows amd drivers 24.2.1 as of Feb 26 and they include the vulkan extension VK_EXT_graphics_pipeline_library among others, after installing it and trying Aliens Fireteam Elite with dxvk 2.3 the log shows:

`info:  VK_EXT_graphics_pipeline_library`
`info:    graphicsPipelineLibrary                : 0`

any idea?

OS: Windows 11
DXVK: 2.3

**Comment by K0bin** [comment]
AMD disables the extension specifically for DXVK because their implementation is broken at the moment.

**Comment by Blisto91** [comment]
This is now enabled in the 24.6.1 driver

**Comment by terry98** [comment]
OMG! Gonna test ASAP! thanks!
