### ISSUE TITLE
Graphical Hooking Support

### ISSUE THREAD

**Issue by Singest** [doitsujin/dxvk#388]
Sorry for making a new issue to ask this but I didn't see any other contact points. I am wondering if it will ever be possible to use things like reshade  that change the dxgi file with dxvk. It doesn't seem like that would be possible to me but I am not the one with the knowledge so I thought I would ask. Anyways reshade makes games like ESO look really good. Dxvk is a really cool project and it's hard to believe it has developed this quickly. Thanks for being a code wizard.

**Comment by doitsujin** [comment]
In theory there's nothing stopping Reshade from working with DXVK. I guess you might run into issues because *both* Reshade and DXVK DLLs are considered "native" (rather than builtin), but I don't think it is possible to fix that.

**Comment by ssorgatem** [comment]
Any idea on why ReShade would not work with DXVK?
Or how could it be debugged?

**Comment by etey339** [comment]
The problem I was seeing is that reshade uses it's own dxgi.dll wich overides dxvk's.

**Comment by Guy1524** [comment]
@etey339 have you tried putting the retrace dll in the game directory, with DXVK installed to system32/syswow64

**Comment by etey339** [comment]
I will go ahead and try that when I get back to my pc but wouldn't the version in the game directory just overide the one in systemwow64?

**Comment by jarrard** [comment]
Reshade and ENB are meant to chain link back to the stock dxgi.dll's,  They do not replace its code but execute the dxvk dll's after it injects stuff into memory. 

I currently use a dxgi.dll injector called dynamic performance for fallout4, it works without a issue.

**Comment by Riesi** [comment]
Has anyone successfully tested Reshade with DXVK? For me the game I am testing does not start anymore when using the 32Bit Reshade.dll and with the 64Bit Dll I only get a purple screen. The DXVK log files are empty in both situations. The Reshade log does not have any errors. 
I have also tried running the whole setup on Windows, but it seems Windows does not like replacing its own Dlls in the system folders with the DXVK versions. Reshade on its own works on Windows.

**Comment by ssorgatem** [comment]
Is there some demo app or something where we might be able to test ReShade?

**Comment by etey339** [comment]
This is the official ReShade application compatibility list: https://reshade.me/compatibility

**Comment by etey339** [comment]
Also I was tired so sorry if some of the stuff I said earlier in the thread made no sense.

**Comment by jarrard** [comment]
I was trying to get reshade working on Warthunder but it didn't trigger, could be just game specific issue as I have not tried with other games yet. Was thinking maybing it can't hook through d3d11.dll for some reason?

I have got performance tuner dxgi.dll working for Fallout4.

**Comment by SirBubbles** [comment]
I've tried a few sweetfx and reshade presets on Fallout4 and gotten nowhere, unfortunately. Anything I can contribute, logfiles, anything like that?
Wine-staging 3.9 latest dxvk, etc.

**Comment by jarrard** [comment]
Have you applied this wine patch?
https://github.com/hdmap/wine-hackery/tree/master/f4se

Yes its for f4se but it basically hooks into the game memory so perhaps applying this to your wine will also fix reshade?

**Comment by SirBubbles** [comment]
jarrard, unfortunately I have those patches applied, and it seems to have no effect.

**Comment by jarrard** [comment]
I tried fallout4 with ENB but it just crashes back to desktop. There was one instance where it did load up but it crashed very soon afterwards. So it appears to at least be trying to work but I would say DXVK is interfering.

**Comment by SirBubbles** [comment]
I'm not so sure about that. I tried ReShade, one of the current enhancement tools for Fallout4 without dxvk, and it seems to crash regardless. I did try an older SweetFX version, but it doesn't seem to work. Doesn't crash the game though.

**Comment by doitsujin** [comment]
ReShade now seems to work with latest `master` according to some people on Reddit.
