### ISSUE TITLE
FAR CRY 3 Deluxe Edition 1.05 - Ubisoft Connect: crashes at launch with DXVK >= 2.x

### ISSUE THREAD

**Issue by legluondunet** [doitsujin/dxvk#3882]
Please describe your issue as accurately as possible.

Hello,
I own FAR CRY 3 Deluxe Edition 1.05 on Ubisoft Connect.
This version crashes at launch with DXVK >= 2.x if game set to use Directx  11 mode

### Software information
Far Cry 3 Deluxe Edition v1.05

### System information

Manjaro 23.1.3 Vulcan
Kernel: x86_64 Linux 6.6.10-1-MANJARO
Proc: AMD Ryzen 9 5900HX
GPU: AMD Radeon RX 6600M
Drivers: Mesa 23.3.3
Resolution: 1920x1080
32 Go RAM
DE: Xfce4
- Wine version:  8.21
- DXVK version:  2.1 et 2.3

### Apitrace file(s)
- Put a link here
I can not obtain one as I can not reproduce the crash with Wine D3D

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace
[log.zip](https://github.com/doitsujin/dxvk/files/14474976/log.zip)

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

**Comment by Blisto91** [comment]
Hi there. Please attach a wine or proton log.

**Comment by K0bin** [comment]
> I can not obtain one as I can not reproduce the crash with Wine D3D

That doesn't matter. Make an apitrace where it does not crash and we'll hopefully be able to replay the apitrace with DXVK and reproduce the crash that way.

**Comment by legluondunet** [comment]
I launched OS update today, MESA updated to 2.3.5 and kernel to x86_64 Linux 6.6.16-2-MANJARO.
After that, I can not reproduce the crash.
Thank you anyway.
