### ISSUE TITLE
[d3d9] Warcraft III blurry screen

### ISSUE THREAD

**Issue by Redv123** [doitsujin/dxvk#3883]
There is a blurry screen issue when running Warcraft III. No problems with dxvk 2.2 and WINED3D.

![Bug](https://github.com/doitsujin/dxvk/assets/161664341/39004761-5ad5-43d9-92fc-817e1bf9826b)

### Software information
Warcraft III 1.27

### System information
- GPU: AMD 7600 XT
- Driver:  Mesa 24.0.1
- Wine version: wine-ge-8-26
- DXVK version: 2.3 and 6b3b934

### Apitrace file(s)
https://mega.nz/file/gPgAVT5S#jyTlhPXOF7IwZBaTSP5NnS9WPiizXd2VY_mWPG7M15E

### Log files
https://mega.nz/file/BHRE1bCB#3YfxnF5uMaXCYpPX3Jptjz96PKFMcBsvbwBrVASQyhA

**Comment by Redv123** [comment]
It seems to be a problem with FSR, and the game works normally after turning it off.

**Comment by doitsujin** [comment]
How exactly does a D3D9 game have FSR?

The screenshot looks like either it's displaying uninitialized data (X11?) or you're hanging your GPU. Either way, doesn't reproduce in the apitrace.

**Comment by mbriar** [comment]
Probably a problem with the FSR hack in proton ge and radv, pretty sure i've seen similar reports before. RADV_DEBUG=nodcc might help, but either way very unlikely to be related to dxvk.

**Comment by Redv123** [comment]
Because Lutris enables FSR feature by default, I didn't change the default option. After adding RADV_DEBUG=nodcc, the game is displayed normally.
