### ISSUE TITLE
Call of Duty MW2 Campaign remastered, crash on Cliffhanger, Gulag and Just like old times

### ISSUE THREAD

**Issue by legoliamneeson** [doitsujin/dxvk#3884]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
For Call of Duty MW2CR, there are unavoidable crashes that is caused by dxvk, there are crashes on the cliffhanger, gulag and second last ,mission of the game, and they cause the steam deck to hard crash.

### System information
- GPU:Steam Deck
- Driver:
- Wine version: PROTON_GE-32/PROTON 9.0
- DXVK version: 2.3

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

**Comment by legoliamneeson** [comment]
I was not able to upload the log file as it was 75mb

**Comment by legoliamneeson** [comment]
[steam-16260836948233420800.zip](https://github.com/doitsujin/dxvk/files/14488136/steam-16260836948233420800.zip)

**Comment by Blisto91** [comment]
Could you try to try to turn either `CACHE SUN SHADOW MAPS` *on* or `shadows` *off*.

I'd that helps the issue then it is this issue https://github.com/doitsujin/dxvk/issues/3073
See also
https://github.com/doitsujin/dxvk/issues/2735
https://github.com/doitsujin/dxvk/issues/3227

**Comment by legoliamneeson** [comment]
turning off CACHE SUN SHADOW MAPS or turning off shadows does not help, it still crashes on these missions

**Comment by Blisto91** [comment]
@legoliamneeson Are you able to give this a retest with dxvk master?

**Comment by legoliamneeson** [comment]
> @legoliamneeson Are you able to give this a retest with dxvk master?

sorry for the delat i just reinstalled it on my steam deck, Cliffhanger does not crash, Ill update as I play through the game again

**Comment by legoliamneeson** [comment]
> @legoliamneeson Are you able to give this a retest with dxvk master?

just finished the game with the updated dxvk, 0 crashes at all, and worked pretty much flawlessy, only real issue I noticed was how the cutscene audio could be choppy when generating shaders, but other then that, perfect
