### ISSUE TITLE
[D3D11] LOD / Object rendering issues in Escape From Tarkov (Unity 2019.3.39)

### ISSUE THREAD

**Issue by MadByteDE** [doitsujin/dxvk#3885]
### Software information
**Name**: Escape From Tarkov
**Settings used**: [Gist](https://gist.github.com/MadByteDE/58feabec0d78230b613a4ce407f2cf3d)
**Engine**: Unity (v2019.3.39)

### System information
- GPU: NVIDIA RTX 4070
- Driver: 4.6.0 NVIDIA 535.161.07
- Wine version:  Lutris runners, tested:  wine-ge-8-26, wine-9.0-stable, wine-9.2-staging
- DXVK version: 2.3
- **Steam hardware report:** [Gist](https://gist.github.com/MadByteDE/72c86ff476152f294b2e607da3509c5e)

## Description

**Video of the issue**:
[Youtube](https://www.youtube.com/watch?v=dprs9WrLZKU)

In `Escape From Tarkov`, objects don't render properly using DXVK. Using Wined3d the issue does not occur (as seen in the video). 

In the video right at the beginning you can see some kind of viewport issue on the left corner of the screen,  when I move the camera. Objects pop in and out all the time which does not happen using wined3d. 

Also when I move forward, some objects in the distance are rendered much later using DXVK, especially bushes and trees.

I tested different LOD and render distance settings, the problem is slightly reduced on higher LOD / rendering distances, but still very noticeable.

I know of at least one other person having the same issues, using an RTX 2060 and driver version 545.29.06.

### Log files
[eft.log](https://github.com/doitsujin/dxvk/files/14500464/eft.log) (DXVK_DEBUG_LEVEL=debug)

### API trace files
[Google Drive (~2Gb)](https://drive.google.com/file/d/1e64S9xGW_pA67oxvcoc-OtgjHcigBqHg/view?usp=drive_link)
**Note:** Generated using DXVK instead of WineD3D because the game always crashed on launch using WineD3D and apitrace.

**Comment by MadByteDE** [comment]
I'm unable to create an API trace because there's a launcher in between and I cannot launch the game executable directly.

**Comment by Blisto91** [comment]
Running through the launcher should be fine in regards to a apitrace. If the DLLs are just next to the games exe they should (in most cases) get picked up when the game starts.

**Comment by MadByteDE** [comment]
> Running through the launcher should be fine in regards to a apitrace. If the DLLs are next to the games exe they should (in most cases) get picked up when it starts if the guide has been followed.

I had to setup the game without Lutris in the why for it to work. On Lutris, it either page faulted or gave me an mem access violation. 

apitrace is in OP.

**Comment by MadByteDE** [comment]
I've now tested a great number of prior versions and found that the issue described here is introduced in DXVK v1.2.1.
v1.2 does not have any foliage/trees/bushes not rendering or popping in and out on the left edge of the screen, but all tested versions after v1.2 do. 

[v1.2.1 tag / commits](https://github.com/doitsujin/dxvk/commits/v1.2.1/)

Here are two screenshots to compare between 1.2 and 1.2.1.
![dxvk1_2](https://github.com/doitsujin/dxvk/assets/4752038/6ad34ebd-96b6-48a7-9e32-ff9438577eae)
![dxvk1_2_1](https://github.com/doitsujin/dxvk/assets/4752038/18e2bace-88ef-43a0-9e99-13e4e830b827)

It might be hard to spot but there are numerous trees and bushes in the distance that are not rendered. The video above does show the issue much better.

**Comment by MadByteDE** [comment]
When commit 7d9a75c82c1c9aaa976041ba9b4ac7bc4504ef03 is disabled, the issue does not occur & all trees and bushes are rendered correctly.

**Comment by MadByteDE** [comment]
I tested the same game setup on a Radeon 5700XT GPU and the issues do not occur, so this might be an Nvidia exclusive bug.

**Comment by doitsujin** [comment]
Should be fixed as of f06c6463157c72d294720812c5d5445abf3ceb71.

**Comment by MadByteDE** [comment]
yep, looks good. Thanks!
