### ISSUE TITLE
Control is missing texts under 2.3, works fine with 2.2

### ISSUE THREAD

**Issue by alirezasamimi100** [doitsujin/dxvk#3886]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

Control is missing texts (sometimes partially.) I got screenshots from menu but it's the same in the game.
2.2:
![DXVK2 2](https://github.com/doitsujin/dxvk/assets/22843642/d250a834-a0ad-4a22-a536-876682c0cddf)
2.3:
![DXVK2 3](https://github.com/doitsujin/dxvk/assets/22843642/1bce3352-2c6e-4007-971c-230a32ca23b0)

### Software information
Name of the game, settings used etc.
Control Ultimate Edition (also the same for Control Standard Edition)
I changed many settings but non affected the issue.
### System information
- GPU: NVIDIA RTX 3060 Laptop
- Driver: 550.54.14
- Wine version: Wine-GE-8.26
- DXVK version: 2.3

### Apitrace file(s)
- Put a link here
https://drive.google.com/drive/folders/19rl79TDTX04H2Cisd7vFI7BlFC-MsB64?usp=sharing
The game crashes after launch when using apitrace and doesn't even get to the menu.
For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
The same link as apitrace.
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

**Comment by Blisto91** [comment]
Hi there and thank you for the issue. 
I can reproduce this when using 2.3 (the text is fully gone for me) but it seems to have been fixed on master already. In the very next commit after release even https://github.com/doitsujin/dxvk/commit/5828f0e2b9b233b32f7b5edb54dc4e04014d3b55
Are you able to verify this? You can download the current as of now dxvk master build here https://github.com/doitsujin/dxvk/actions/runs/8157916998

**Comment by alirezasamimi100** [comment]
Yes it's working fine. Thank you!

**Comment by Blisto91** [comment]
The issue was kept open as a reminder of a game that had issues with the commit to be possibly be looked in to again.
