### ISSUE TITLE
Skeleton Boomerang rendering regression when booting the game

### ISSUE THREAD

**Issue by AJuujarvi** [doitsujin/dxvk#3888]
Skeleton Boomerang now boots to a black screen when you boot the game. It renders properly using the DXVK from the Proton 9 Beta, which is 2e4c34f5694c9bf07ff0a353a160a47a1d599e17. However if I try and use Proton Experimental Bleeding Edge, it will black screen. That uses 428c98bc6365a71951449af97e868b02497c5de9 as a commit currently.

If I put the DXVK version from Proton 9 Beta into Proton Experimental Bleeding Edge, then the game will render correctly upon the game booting up.

Don't worry about the game failing to start a New Game, that is non-regressive and unrelated to this issue.

### Software information
Skeleton Boomerang (658150)

### System information
- GPU: AMD 7900XT
- Driver: Mesa 23.3.5-arch1.1
- Wine version: working: proton-9.0-beta14
- failing: experimental-bleeding-edge-9.0-84317-20240306-pe5aac5-wd78dcf-d4b0e31-vbd1af8
- DXVK version: working: 2e4c34f5694c9bf07ff0a353a160a47a1d599e17
- failing: 428c98bc6365a71951449af97e868b02497c5de9

### Log files
[steam-658150.log](https://github.com/doitsujin/dxvk/files/14511899/steam-658150.log)

**Comment by doitsujin** [comment]
Bisected to 5312ef1cf9c201d20048f9e796d21b436420fd49 @K0bin
