### ISSUE TITLE
After a few seconds of the game, Assassin's Creed Unity crashes/hangs up my system.

### ISSUE THREAD

**Issue by Kerrung** [doitsujin/dxvk#389]
Using DXVK, the game hasn't any rendering distortions, but after a few seconds of playing the game, Assassin's Creed Unity totally crashes/hangs up my system. After that, the only thing I can do is hard reboot. Unfortunately, I absolutely could not write down the apitrace using DXVK because here does not appear the  *.trace file. I assume that this is due to the strict binding of all games of Ubisoft to Uplay.

Using WineD3D, the game has heavy rendering distortions because of which I can hardly see anything in the game, and after a few seconds of playing the game crashes. Unfortunately, I absolutely could not write down the apitrace using WineD3D because here does not appear the  *.trace file.

In addition, I tried to write down the apitrace on the MS Windows, but there does not appear the  *.trace file too.

### Software information
Assassin's Creed Unity, minimal graphics settings used.

### System information
- OS: Arch Linux
- GPU: AMD Radeon HD 7770
- Driver: today's latest Mesa-git + amdgpu kernel driver
- Wine version: today's latest Wine-git + Staging-git patchset
- DXVK version: a39b9cb

### Apitrace file(s)
- Unfortunately I could not write it down.

### Log files
- [ACU_dxgi.log](https://github.com/doitsujin/dxvk/files/2030574/ACU_dxgi.log)
- [ACU_d3d11.log](https://github.com/doitsujin/dxvk/files/2030575/ACU_d3d11.log)

### Terminal output
- [acu-log.txt](https://github.com/doitsujin/dxvk/files/2030644/acu-log.txt)

**Comment by doitsujin** [comment]
Plesase create a hang report (see #252).

**Comment by Kerrung** [comment]
@doitsujin, I just did it. Thank you.

**Comment by Kerrung** [comment]
@doitsujin, I just did it. Thank you.
Should I now close this issue here because I created a hang report [there](https://github.com/doitsujin/dxvk/issues/252)?

**Comment by Kerrung** [comment]
@doitsujin, now [it fixed](https://github.com/doitsujin/dxvk/issues/252#issuecomment-393898603) [for me](https://github.com/doitsujin/dxvk/issues/252#issuecomment-393935457)!
Thank you and @hakzsam very much!
