### ISSUE TITLE
Carrie's Order Up: Black screen issue

### ISSUE THREAD

**Issue by waspennator** [doitsujin/dxvk#3891]
Unsure if this was also fixed with the Skeleton Boomerang pr fix or not so reporting just to be safe. Game doesn't seem to render on my oled Deck anymore with latest proton Experimental unless you force the game to use Wined3d, tried it on my windows laptop and it seemed to work fine there. Game also crashes if you press start on the title screen, but that's unrelated to the visual regression.

### Software information
Carrie's Order Up

### System information
- GPU: AMD Van Gogh
- Driver: Mesa 23.1.3
- Wine version: 9.0
- DXVK version: Unsure what version is being used in proton

### Apitrace file(s)
- 

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
[steam-522490.log](https://github.com/doitsujin/dxvk/files/14514504/steam-522490.log)

**Comment by Blisto91** [comment]
Thank you for the issue. I saw your comment in the Proton issue so i had already started poking.
Apitrace: https://drive.proton.me/urls/42TMV2GV8C#LUnhdYuFG2P0

**Comment by K0bin** [comment]
Thanks for reporting the bug. The PR linked above should fix it.
