### ISSUE TITLE
[d3d9] Unbind buffers in EndScene & Reset commit breaks 'Mount&Blade'

### ISSUE THREAD

**Issue by aur-r** [doitsujin/dxvk#3892]
Please describe your issue as accurately as possible.

After commit 49b18f0, more precisely the second part of it, line 1614, game "Mount and Blade"(https://www.gog.com/game/mount_blade) fails to run. After a smooth game cinematic intro the game gets stuck in loading and the image starts to flicker/stutter heavily until the game is killed. For another d3d9 game, Dragon Age Origins, the game cinematic intro is completely black, but the game ultimately loads and seems to run fine. 

### System information
- GPU: AMD 6600XT
- Driver: RADV - Mesa-23.3.6
- Wine version:  9.3
- DXVK version: git

### Log files
[MandB.log](https://github.com/doitsujin/dxvk/files/14514775/MandB.log)

**Comment by Blisto91** [comment]
Hi there. Forget to say thank you for the issue. So thanks! 

I've made some apitrace for the devs.
Dragon Age Origins. This one will show a black intro with the offending commit.
https://drive.proton.me/urls/51YC0GAEBM#Z1rsauiRLKAP

Mount and Blade. This one will end early with the offending commit. Plays all the way with commits prior.
https://drive.proton.me/urls/Y8VRDBMNZC#0wKeq08eOsWM
