### ISSUE TITLE
Support creating D3D9 device without a window

### ISSUE THREAD

**Issue by K0bin** [doitsujin/dxvk#3894]
In spite of what the documentation says, it's possible to create a D3D9 device with NULL passed for both `PresentationParams::hDeviceWindow` and `FocusWindow`. This will still create an implicit swapchain and you can query the backbuffers and render to those. You can even call `Present` and that returns `S_OK`.

According to Wine commit logs, Planetary Annihilation: Titans depends on this. This also makes the "visuals" Wine test crash with DXVK.

**Comment by Joshua-Ashton** [comment]
I seem to remember this not working for me which is why the DXVK tests all have windows.

**Comment by K0bin** [comment]
![image](https://github.com/doitsujin/dxvk/assets/1131720/fe7ea35c-0bfd-440c-900b-6f682ea616c0)
