### ISSUE TITLE
ComputeMark 2.1 launches GUI but don't launch benchmarks

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#39]
This benchmark is interesting because should be a DX11 app using purely compute+UAV features (2D and 3D RWTextures) so could be good getting it right as doesn't use pretty much any other DX11 features..
tested on NV 390.65 and GTX 970

seems there is only missing API function
"err:   D3D11Device::GetUnorderedAccessViewDescFromResource: Not implemented"

[d3d11.log](https://github.com/doitsujin/dxvk/files/1670640/d3d11.log)
[dxgi.log](https://github.com/doitsujin/dxvk/files/1670641/dxgi.log)

attaching benchmark here because can be difficult to find..
[ComputeMark2.zip](https://github.com/doitsujin/dxvk/files/1670646/ComputeMark2.zip)

**Comment by doitsujin** [comment]
Implemented the missing methods. The benchmark should start now but it causes a GPU hang at the moment.

**Comment by oscarbg** [comment]
thanks..

just in case it helps I reported a year ago support for this program by Wine D3D11 backend
(https://bugs.winehq.org/show_bug.cgi?id=42504)
and a Wine dev fixed in this commit
"wined3d: Fix handling of SM4+ integer registers"
https://source.winehq.org/git/wine.git/?a=commit;h=b1b880fc75932c890ea070311793111e738ebf52
don't know if it can help.. just saying..

**Comment by doitsujin** [comment]
That bug is unrelated. Out-of-bounds access to images may cause the freezes, but I'm not sure.

**Comment by oscarbg** [comment]
Hi,
just compiling latest amdvlk dev Branch which includes fix from (https://github.com/doitsujin/dxvk/issues/43)
computemark Works so closing issue.. as now seems a RADV issue..
