### ISSUE TITLE
fornite error level 10

### ISSUE THREAD

**Issue by Eignar17** [doitsujin/dxvk#390]
![captura de pantalla -2018-05-23 13-43-17](https://user-images.githubusercontent.com/8561550/40445178-008838a6-5e91-11e8-8940-eba33f3f58e1.png)

### System information
- GPU:Nvidia 1050 OC
- Driver:NVIDIA 396.18.11
- Wine version: Wine 3.7
- DXVK version: 531732f 

### Apitrace file(s)
not running game in wine

### Log files
- d3d11.log:
[EpicGamesLauncher_d3d11.log](https://github.com/doitsujin/dxvk/files/2032455/EpicGamesLauncher_d3d11.log)
- dxgi.log: 
[EpicGamesLauncher_dxgi.log](https://github.com/doitsujin/dxvk/files/2032456/EpicGamesLauncher_dxgi.log)

**Comment by Yardanico** [comment]
You won't be able to play Fortnite anyway (it uses BattleEye anticheat software which is incompatible with Wine)

**Comment by doitsujin** [comment]
From the log file:

> err:   ExtensionSet::addInstanceExtensions: Failed to query instance extensions

You don't have Vulkan set up correctly (probably a missing 32-bit driver/loader/whatever).

**Comment by Eignar17** [comment]
@doitsujin in wined3d running fortnite all bug  on dxvk is send msj :/

**Comment by Yardanico** [comment]
@Eignar17 don't lie. You can't run Fortnite in Wine.

**Comment by Eignar17** [comment]
@Yardanico  can't run Fortnite in Wine ok.
![captura de pantalla -2018-05-23 14-21-44](https://user-images.githubusercontent.com/8561550/40446526-20fe3db6-5e95-11e8-9656-a33c179bb2d1.png)
![captura de pantalla -2018-05-23 14-22-23](https://user-images.githubusercontent.com/8561550/40446538-2a2550aa-5e95-11e8-83ec-b621b76b70bf.png)

**Comment by Yardanico** [comment]
@Eignar17 try to get into the ACTUAL game :)

**Comment by Eignar17** [comment]
@Yardanico  lol lost texture on battle royale
