### ISSUE TITLE
Titan Quest Anniversary Edition. Dynamic shadows are not displayed correctly at night.

### ISSUE THREAD

**Issue by Krovok** [doitsujin/dxvk#3901]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
When night falls in the game, the shadows of trees and objects begin to flicker strongly. There is no such thing in DX 11. I tested it on different versions of the game and on different operating systems.

### System information
- GPU: RTX 4080 or GTX 1060 6 gb
- Driver: 551.23 and all the past ones.
- Wine version: Win 10 Pro. 64bit. Version 22H2. and 20H2.
- DXVK version: 2.3 and all the past ones.

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

**Comment by Blisto91** [comment]
Hi there.

Please provide logs and a apitrace

**Comment by K0bin** [comment]
According to PCGamingWiki, the game supports both D3D11 and D3D9. Which one are you using?

**Comment by Blisto91** [comment]
@Krovok Friendly ping

**Comment by Blisto91** [comment]
After testing for a while on my 4080 i have not been able to reproduce any issue where it looks different from native.
Also haven't seen similar reports on ProtonDB looking at the newer ones.
