### ISSUE TITLE
Helldivers DX11 mode does not allow HDR toggle to work

### ISSUE THREAD

**Issue by GloriousEggroll** [doitsujin/dxvk#3905]
When I launch the game using `--use-d3d11` for DX11 mode, in either KDE6 with HDR enabled and gamescope, or just using gamescope inside a gamescope session, both with various required HDR options enabled (including DXVK_HDR=1 for dxvk), I am not able to toggle the in-game HDR setting. I can use the same settings in other games to enable HDR with no problems. GPU is 7900 XTX, latest mesa git, kernel 6.7.6. Command used is:
`gamescope -W 3840 -H 2160 -w 3840 -h 2160 --hdr-enabled -- env DXVK_HDR=1 %command% --use-d3d11`

**Comment by Joshua-Ashton** [comment]
Does HDR work with d3d11 on Windows?

**Comment by Trevonn** [comment]
> Does HDR work with d3d11 on Windows?

I just tested this on Windows 11
7900 XTX - 24.3.1
LG C2

HDR only works if you remove the `--use-d3d11` launch option

**Comment by doitsujin** [comment]
Thanks for confirming. So yeah, everything working as intended I suppose.
