### ISSUE TITLE
[Kontakt 7] Kontakt 7 crashes after installing dxvk.

### ISSUE THREAD

**Issue by kaisar149** [doitsujin/dxvk#3907]
I had Kontakt 7 working properly before I installed DXVK. The only reason I did it was because some other plugins had stuck GUIs that were only solvable with this dll (Namely Audio Modelling SWAM and Parallax Audio Virtual Sound Stage Studio 2)

I tried narrowing down the problem and reset my wine and found out that kontakt indeed stopped working as soon as I install   dxvk.

Here's the backtrace that I saved After the crash.
[backtrace.txt](https://github.com/doitsujin/dxvk/files/14572304/backtrace.txt)

### Software information
Native Instruments Kontakt 7
Crashes on both standalone and Yabridge/LinVst modes
Currently, it's the only app that crashes with dxvk installed

### System information
- GPU: Intel(R) HD Graphics 520 (SKL GT2 
- Driver: Intel open-source Mesa driver 24.0.2
- Wine version: wine-9.3
- DXVK version: v2.3

### Log files
[kontakt7.log](https://github.com/doitsujin/dxvk/files/14572245/kontakt7.log)

**Comment by doitsujin** [comment]
Not our bug:
```
03e4:fixme:vulkan:X11DRV_vkCreateWin32SurfaceKHR Application requires child window rendering, which is not implemented yet!
err:   D3D11SwapChain: Failed to recreate surface: VK_ERROR_INCOMPATIBLE_DRIVER
err:   DXGI: CreateSwapChainForHwnd: Failed to create swap chain, hr -2147467259
```

You'll need a wine build with child window rendering patches from Proton.

**Comment by kaisar149** [comment]
Thank you @doitsujin. After waiting for it to build the wine-tkg build, it finally works. Took a long time to build because of my PC but it was worth it :)
