### ISSUE TITLE
Flickering object in The Witcher 3

### ISSUE THREAD

**Issue by 88i** [doitsujin/dxvk#391]
### Software information
The Witcher 3
Postprocessing: everything enabled except ambient occlusion
Graphics : low
System gamma: off
Hairworks: off
Hardware cursor: off
Other graphics settings: low or medium

I used The Witcher 3 on Debian Testing with driver 390.48 and I had a crash. This issue was a know problem of the 390.48 driver and fixed in 396.24 so I needed to use the newer driver. But updating to version 396 via the package manager in Debian Testing (and even in Debian Sid) isn't possible. The only distros that are able to install driver 396 via the package manager seem to be Ubuntu (only via a PPA) and Arch Linux (and their derivatives) It's not possible to install the 396 driver via the package manager in very popular distros like Fedora, SUSE Tumbleweed, Debian, .. So I installed Antergos and I have version 396.24 and the performance (especially during the cutscenes) is better. But now I have a constantly present flickering objects issue (that I didn't have with driver 390 and DXVK version 0.51). 

I indicated one of the flickering objects here with an arrow:
[image #1](https://i.imgur.com/HEUrJF3.jpg) 
[image #2](https://i.imgur.com/r1wnYt9.jpg)

### System information
- GPU: Nvidia GTX 1050 2GB
- Driver: 396.24
- Wine version:  wine-3.8 (Staging)
- DXVK version: 0.52

### Log files
[d3d11.log](https://paste.debian.net/plainh/7e25f887)

[dxgi.log](https://paste.debian.net/plainh/b86ac667)

Many objects are flickering all the time in the Novigrad map. It makes the game unplayable. 

Is this a known issue?

**Comment by Yardanico** [comment]
@jarrard you can get into a tty anyway

**Comment by jarrard** [comment]
To do what?

The driver fails extremely hard, there is no display unit connected sort of error. tty in won't give you anything unless you intend to uninstall it.

**Comment by doitsujin** [comment]
As far as I know, the 390.48 driver doesn't support xorg 1.20 either, so they are probably running an older version (it's *Debian* Testing anyway, not *Arch* Testing or Gentoo or anything like that).

**Comment by 88i** [comment]
There is this problem with driver 396.18.11 on Antergos  (and probably also Arch Linux):
https://forum.antergos.com/topic/9928/nvidia-driver-version-396-18-11-issues/2

I understand why you are using a development version of the Nvidia driver. I personally won't install this driver because I don't have a testing system, and I would like to be able to update the driver via a package management system because I know that I will have unresolvable problems otherwise.

I have one last question before I will close the issue. How is the Vulkan support on the open-source AMD drivers. Will I have the same amount of issues when I use a RX 560 4GB with the padoka PPA for example?  Which one has the most complete Vulkan support right now?

**Comment by jarrard** [comment]
396.24 on the other hand works fine with xorg1.20. Sometimes Nvidia make me wonder!

**Comment by doitsujin** [comment]
@88i I'm not *using* that driver since I'm on RADV anyway, but people have successfully run The Witcher 3 with the latest beta drivers. Waiting for packages to be updated is of course reasonable.

RADV runs very well with some games but not at all with others (see #252). Right now, Nvidia should offer the least problematic Vulkan experience, although I hope for RADV to catch up.

**Comment by 88i** [comment]
@doitsujin Thank you for the replies. I'll wait until Nvidia releases a new driver.

**Comment by varris1** [comment]
@88i They released 396.24.02 yesterday. You could try that.
