### ISSUE TITLE
Colours look washed up after the latest update of Age of Empires 2 Definitive Edition

### ISSUE THREAD

**Issue by mihai-preda** [doitsujin/dxvk#3912]
Due to poor performance of Age of Empires 2 DE on DX11, on Radeon RX6600M, I'm using dxvk.
After the latest update of AOE2DE, the colours look washed up.
Any idea how I can gather logs about it to post them here?

**Comment by Blisto91** [comment]
If you are on Windows then dxvk logs from the game should just appear next to the games exe or root game folder (exe plus d3d11 and dxgi in the name).
Screenshots or pictures of the screen with and without dxvk to show what you mean would probably also be needed here.
Also maybe some etup details like are you using a HDR or SDR monitor.

**Comment by mihai-preda** [comment]
[AoE2DE_s_d3d11.log](https://github.com/doitsujin/dxvk/files/14628478/AoE2DE_s_d3d11.log)
[AoE2DE_s_dxgi.log](https://github.com/doitsujin/dxvk/files/14628479/AoE2DE_s_dxgi.log)

**Comment by mihai-preda** [comment]
@Blisto91  I'm sure it isn't a dxvk issue. However, I can try to report it, in case a fix can be applied.
The game itself is a dumpster fire when it comes to bugs. I was lucky to find dxvk to play it for a while.

**Comment by Blisto91** [comment]
Include the other information from my comment also

**Comment by mihai-preda** [comment]
The tracer file is not generated. I've copied the dll files into the game directory where the EXE is located, but no joy.

**Comment by mihai-preda** [comment]
Closing this issue as it it's a game issue.

**Comment by Blisto91** [comment]
I tried running it on Linux at least shortly and wasn't able to see any difference between dxvk and wined3d

**Comment by mihai-preda** [comment]
Thanks, @Blisto91. The game itself has been a major PITA since release.
I'm running it on Windows, which is even stranger.
