### ISSUE TITLE
"Windows 11" Kingdom Come Deliverance - Crash on start up.

### ISSUE THREAD

**Issue by shankly1985** [doitsujin/dxvk#3917]
Please describe your issue as accurately as possible.
When loading up the game it crashes on the start up splash screen. 

Steps I have tried is running old AMD drivers, tested different versions of DXVK without any luck. The game loads up fine on DX11. 

Image of the crash.
<img width="610" alt="Screenshot (1)" src="https://github.com/doitsujin/dxvk/assets/27680082/aa2d6b8f-eff8-43ee-954b-642382041bbe">

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
ingdom Come Deliverance,  DX11 ultra settings.

### System information
- GPU: RX 7900XT
- Driver: Adrenalin 24.3.1 (WHQL Recommended)
- Wine version:  N/A
- DXVK version: Tried 1.7, 2.2, 2.3, 2.3.1

**Comment by K0bin** [comment]
Please upload the DXVK logs.

**Comment by shankly1985** [comment]
> Please upload the DXVK logs.

Hello 
Please see attached.

[KingdomCome_d3d11.log](https://github.com/doitsujin/dxvk/files/14675642/KingdomCome_d3d11.log)
[KingdomCome_dxgi.log](https://github.com/doitsujin/dxvk/files/14675643/KingdomCome_dxgi.log)

**Comment by K0bin** [comment]
This: https://github.com/doitsujin/dxvk/wiki/Windows#dll-loading-issues

One of the reasons why Windows is not a supported platform for DXVK.

**Comment by Blisto91** [comment]
What K0bin refers to is that this line combined with the empty dxgi log means the game is trying to load Windows own instead of dxvks. That wont work.

> warn:  D3D11InternalCreateDevice: Adapter is not a DXVK adapter
