### ISSUE TITLE
Causes flickering depth buffer in TES: Oblivion

### ISSUE THREAD

**Issue by adamnorbacker** [doitsujin/dxvk#3918]
Without DXVK the depth buffer is working always, but as soon as DXVK is loaded, the depth buffer flickers while moving the camera.
This can be easily seen with Reshade v6.0.1 and the detect depth shader.

### Software information
The elder scrolls IV: Oblivion
Default settings.

### System information
- GPU: RTX 4090
- Driver: 551.86
- Wine version: 
- DXVK version: 2.3.1 x86
- Windows 11

**Comment by K0bin** [comment]
Please make a video of the issue, I have no idea what you're talking about.

The depth buffer is used for a lot more than just ReShade effects so if DXVK had problems with that, it would be extremely obvious by just playing the game. The game itself renders fine though.

**Comment by Blisto91** [comment]
@adamnorbacker Friendly ping

**Comment by Blisto91** [comment]
@adamnorbacker double friendly ping

**Comment by tiramoi** [comment]
![Oblivion 2024-06-30 00-38-07](https://github.com/doitsujin/dxvk/assets/174202621/847db893-1aca-470a-b273-a887bd3d35df)
@K0bin this is what it looks like

**Comment by K0bin** [comment]
And which ReShade shader causes that?

**Comment by tiramoi** [comment]
Reshade 6.1.1. Also using an RX 6600, Driver ver. 24.5.1, Dxvk ver. 2.3.1

**Comment by tiramoi** [comment]
This causes some issues with shaders like MXAO with visual artifacting, gonna send screenshot in a sec

**Comment by tiramoi** [comment]
![sdlkjalsdjlakdjlkdla](https://github.com/doitsujin/dxvk/assets/174202621/033db8d0-90f2-4fee-bc02-d4ee853a74b0)

**Comment by tiramoi** [comment]
I can also confirm what the OP posted. Depth buffer works fine on dx9. Things i've tried: turning off forced msaa and anisotropy from dxvk.conf, experimented with all the generic depth buffer options under reshade addon. No dice.

**Comment by tiramoi** [comment]
> And which ReShade shader causes that?

Oh my bad, I misread that as reshade version. That's just the display depth shader showing that, but the issue can also be observed when using the various debug views from the different shaders. Let me check if turning off all shaders fixes the issue.

**Comment by K0bin** [comment]
Did you have to install any shaders with ReShade or is it literally just ReShade?

**Comment by Blisto91** [comment]
I've tried reproducing both on Nvidia and AMD on Linux but have been unable to so far.
In the "Generic Depth" addon I've set "Copy depth buffer before clear operations" to get it to work. Then i just turn on `DisplayDepth` with `RESHADE_DEPTH_INPUT_IS_REVERSED` set to 0.

<details>
  <summary>Screenshot</summary>

Nvidia
![image](https://github.com/doitsujin/dxvk/assets/47954800/7146b8c5-13be-445e-aa53-1ea202755a70)

AMD
![image](https://github.com/doitsujin/dxvk/assets/47954800/d72b53f5-d127-4a7c-b35b-c99f3123f658)
</details>

**Comment by tiramoi** [comment]
> Did you have to install any shaders with ReShade or is it literally just ReShade?

I have shaders with reshade:
Techniques=Smart_Sharp@Smart_Sharp.fx,CA@ChromaticAberration.fx,SMAA@SMAA.fx
TechniqueSorting=Daltonize@Daltonize.fx,Deband@Deband.fx,LUT@LUT.fx,UIMask_Top@UIMask.fx,ContrastAdaptiveSharpen@CAS.fx,Smart_Sharp@Smart_Sharp.fx,CA@ChromaticAberration.fx,SMAA@SMAA.fx,UIMask_Bottom@UIMask.fx,ADOF@qUINT_dof.fx,Bloom@qUINT_bloom.fx,Debanding@qUINT_deband.fx,DELC_Sharpen@qUINT_sharp.fx,Lightroom@qUINT_lightroom.fx,MXAO@qUINT_mxao.fx,AdvancedCRT@CRT.fx,Technicolor@Technicolor.fx,Technicolor2@Technicolor2.fx,DisplayDepth@DisplayDepth.fx

**Comment by tiramoi** [comment]
Also my reshade ini and log i guess 
[reshade.zip](https://github.com/user-attachments/files/16041965/reshade.zip)

**Comment by Blisto91** [comment]
You sent ReShadePreset.ini twice. Don't know if that was intended

**Comment by tiramoi** [comment]
> You sent ReShadePreset.ini twice. Don't know if that was intended

my bad.
[reshade.zip](https://github.com/user-attachments/files/16042000/reshade.zip)

**Comment by Blisto91** [comment]
I am still not reproducing, at least on Linux, using your preset and the settings from your ReShade.ini.
I am using the d3d9 version of reshade fwiw

**Comment by tiramoi** [comment]
> I am still not reproducing, at least on Linux, using your preset and the settings from your ReShade.ini. I am using the d3d9 version of reshade fwiw

Am using windows 11 like op if it makes a difference. Also here's a vid of the issue https://www.youtube.com/watch?v=kMfvoKc8w4o

**Comment by K0bin** [comment]
Make sure you don't have any other Vulkan layers installed.

**Comment by tiramoi** [comment]
> Make sure you don't have any other Vulkan layers installed.

I don't remember consciously installing any. I don't know what a Vulkan layer is either. How do I check?

**Comment by Blisto91** [comment]
Can you send a dxvk log by the way. It should appear next to the games exe

**Comment by tiramoi** [comment]
> Can you send a dxvk log by the way. It should appear next to the games exe

[Oblivion_d3d9.zip](https://github.com/user-attachments/files/16042178/Oblivion_d3d9.zip)
is it this?

**Comment by K0bin** [comment]
Does it work if you remove your samplerAnisotropy config? That can cause problems.

**Comment by tiramoi** [comment]
> Does it work if you remove your samplerAnisotropy config? That can cause problems.

@K0bin nope. Removed dxvk.conf altogether. Disabling anisotropy and msaa doesnt work.

**Comment by Blisto91** [comment]
@tiramoi Which API do you use for Reshade along with dxvk? d3d9 or Vulkan?
Using the Vulkan version on Windows (didn't work out of the box on Linux) i can see that the DisplayDepth option is kinda fecked with dxvk. Though not exactly in the same way as shown in your screenshot. More like it blinks wildly or doesn't show anything when looking certain directions.
The d3d9 version along with dxvk still works fine though. Was also what i used on Linux.

**Comment by tiramoi** [comment]
@Blisto91 also dx9 on windows 11 have issues for me for oblivion. Can't use the HDR option in oblivion, and if I use a workaround for fixing HDR, it breaks the shadows. I just hope using d3d9 with dxvk wont carry over those issues

**Comment by Blisto91** [comment]
> How do I use d3d9 along with dxvk?

If you install the d3d9 version of reshade and then just leave that d3d9.dll with the game you can put the dxvk dll in another folder and then point to it with environment variable `RESHADE_MODULE_PATH_OVERRIDE`. Will make reshade use it instead of the Windows system one.

**Comment by adamnorbacker** [comment]
Will that enforce vulkan hdr compatible swapchains by doing that?

**Comment by adamnorbacker** [comment]
> > How do I use d3d9 along with dxvk?
> 
> If you install the d3d9 version of reshade and then just leave that `d3d9.dll` with the game you can put the dxvk dll in another folder and then point to that folder with environment variable `RESHADE_MODULE_PATH_OVERRIDE`. Will make reshade use it instead of the Windows system one.

Will that enforce vulkan hdr compatible swapchains by doing that?

**Comment by Blisto91** [comment]
I'm a tester fwiw not a dev. Do you just mean the games own "HDR" option?

**Comment by adamnorbacker** [comment]
Nah, Vulkan makes dx9 games compatible with HDR such as windows autoHDR or Special-K etc. Im just wondering if doing your proposal would make the actual renderer dx9 again and therefore disabling the possibility to use HDR.

**Comment by Blisto91** [comment]
I have no idea how Reshade works. It would still be using dxvk (Vulkan) in this scenario.
Try i guess.

**Comment by K0bin** [comment]
Either way this very much seems like it's not a DXVK bug but rather a bug with something else on your system. Some Vulkan layer or maybe ReShade or SpecialK.

**Comment by emoose** [comment]
Seeing this happen on fresh Windows install too, though only once OR is installed, without OR it seems no depth buffers are valid for ReShade.

With native D3D9 + OR, ReShade shows 2 clears for the depth buffer consistently, and no flicker happens.
With DXVK + OR, ReShade usually shows 5 clears for the depth buffer, but sometimes seems to add an extra clear for 1 frame, which throws off the detection and causes flicker.

OR.E3.3.3.2mc.Mcstfuerson.Preset.zip from https://github.com/mcstfuerson/TES-Reloaded/releases/tag/v3.3.2 is the OR build used to test that.

**Comment by K0bin** [comment]
> With native D3D9 + OR, ReShade shows 2 clears for the depth buffer consistently, and no flicker happens.
With DXVK + OR, ReShade usually shows 5 clears for the depth buffer, but sometimes seems to add an extra clear for 1 frame, which throws off the detection and causes flicker.

That sounds like a ReShade problem, not a DXVK one. DXVK can't control or influence what ReShade does.
I don't even know whether you're using the D3D9 version of ReShade with DXVK or the Vulkan version of ReShade.

**Comment by emoose** [comment]
It's ReShade VK as mentioned.

Might have narrowed my issue down to games "Window Reflections" setting, with that turned off the depth flicker mostly disappears & ReShade works fine with it.

That reflections setting uses some fSecondsBetweenWindowUpdate timer to say when to update, default is 10 secs but changing to 1 second makes the flicker constant (now I wonder if timer could be removed from game so the clear for it would be present every frame - probably wouldn't be great for performance though...)

Anyway I guess my issue probably is just down to ReShade's detection, still find it a bit strange that D3D9 doesn't show any extra clears for these reflections though.

**Comment by Blisto91** [comment]
Does it look correct with the d3d9 version of reshade + dxvk?

**Comment by K0bin** [comment]
> It's ReShade VK as mentioned.

Then it's pretty much guaranteed to be a ReShade bug, not a DXVK one.
