### ISSUE TITLE
[regression] Frostpunk crashing

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3920]
Since commit https://github.com/doitsujin/dxvk/commit/1085ba713e8b3c2dd7de5e395eeeb5f1a8bc06dd Frostpunk crashes on startup.

<details>
  <summary>Error popup</summary>
  
![image](https://github.com/doitsujin/dxvk/assets/47954800/c8527951-1cf3-49a3-bbe6-41350c275b9d)
</details>

Note that i do not have a HDR capable monitor

### Software information
Frostpunk

### System information
- GPU: RX6800
- Driver: Few days old mesa main and amdvlk  2024Q1.2
- Wine version: Proton Bleeding Edge
- DXVK version: https://github.com/doitsujin/dxvk/commit/1085ba713e8b3c2dd7de5e395eeeb5f1a8bc06dd and above

### Apitrace file(s)
TBD

### Log files
I only open the game shortly and then shut down or else the log will quickly grow very large even without the crash happening
[steam-323190.tar.gz](https://github.com/doitsujin/dxvk/files/14696240/steam-323190.tar.gz)

**Comment by doitsujin** [comment]
Should be fixes in 274248654090aa23f96d2b073c5674261931a29b.

**Comment by Blisto91** [comment]
Confirmed
