### ISSUE TITLE
Subnautica: Crashing upon Launch

### ISSUE THREAD

**Issue by JohnnYDeveloperAHK** [doitsujin/dxvk#3926]
### Software information
Subnautica, Default settings on-game install used etc.

### System information
- GPU: **GTX 1070**
- Driver: **537.58**
- Wine version: 
- DXVK version: DXVK Async 2.0 / DXVK 2.3
- Vulkan version on Windows: Checked using CMD, it is **1.3.242**

### Apitrace file(s)
- don't know how to do this yet

### Log files
DXVK Config maybe something conflicts with the game, but I have tried without changing anything in the 'dxvk.conf'
[dxvk.txt](https://github.com/doitsujin/dxvk/files/14742264/dxvk.txt) I changed it to TXT format so I could upload it.
D3D11 Log
[Subnautica_d3d11.log](https://github.com/doitsujin/dxvk/files/14742286/Subnautica_d3d11.log)
DXGI Log
[Subnautica_dxgi.log](https://github.com/doitsujin/dxvk/files/14742288/Subnautica_dxgi.log)

>  I've tried DXVK 2.3, DXVK Async 2.0, and GPL Sync, and none of them work with this game. I Usually just use Async as my preferred type.

_Also I'm playing from the Epic Games Launcher... Unsure if it might work on Steam._

After Starting up the game, the game completely crashes with the UnityCrash handler starting up, and after a second or less it closes too.

**Comment by JohnnYDeveloperAHK** [comment]
There's been a past issue 6 years ago: https://github.com/doitsujin/dxvk/issues/102
Has anything changed since then?

**Comment by JohnnYDeveloperAHK** [comment]
There's been a similar issue 6 years ago: https://github.com/doitsujin/dxvk/issues/102
Has anything changed since then?

**Comment by Blisto91** [comment]
Using the Steam version the game starts fine here with both Linux Proton and Windows using a RTX 4080. Don't think it should matter if it is the Epic version maybe besides trying to turn off the overlay if it has one. 
Try to update your driver and check out the Windows section in the readme https://github.com/doitsujin/dxvk/wiki/Windows

**Comment by K0bin** [comment]
Most likely just another Windows issue:
https://github.com/doitsujin/dxvk/wiki/Windows

**Comment by JohnnYDeveloperAHK** [comment]
Will try updating the Driver, and will post here if anything changed.

**Comment by JohnnYDeveloperAHK** [comment]
Found the issue, It was because both of the Driver being outdated and RTSS hooking onto the game.

Updating the Driver, and Closing RTSS fixed the issue. Hope this helps anyone else with the same problem
