### ISSUE TITLE
Halo ce direct x9.0b

### ISSUE THREAD

**Issue by Omar10012** [doitsujin/dxvk#3929]
Halo ce direct x9.0b is not installed
I use mobox wow64 esync enabled 
I tried different dxvk versions 
I tried different wine versions
I tried different emulators like winlator and box64droid
I even tried different halo ce versions 
The same problem happen
![Screenshot_٢٠٢٤٠٣٢٨_١٩٥٨٥١_com termux x11](https://github.com/doitsujin/dxvk/assets/165278899/0df1bb79-6b9a-4a17-a082-27b128c3b759)

### Software information
Halo CE (from ~~steamunlocked~~)

### System information
- Phone: vivo Y51
- GPU: adreno 610 (snapdragon 662)
- Driver: turnip zink 3.5
- Dri3 enabled
- Esync enabled
- Wine version: 8.18 staging
- DXVK version: tried a lot and the same thing
(in the picture dxvk gplasync 2.2)
- OS: Android 13

### Log files
[halo_d3d9.log](https://github.com/doitsujin/dxvk/files/14789497/halo_d3d9.log)
[halo_dxgi.log](https://github.com/doitsujin/dxvk/files/14789502/halo_dxgi.log)
Mayabe you will see different dxvk version on the log because i tried a lot of dxvk versions

**Comment by doitsujin** [comment]
we do not support pirated software.
