### ISSUE TITLE
[Regression] World of Warcraft causes GPU hang

### ISSUE THREAD

**Issue by Kerrung** [doitsujin/dxvk#393]
[Regression]
World of Warcraft totally hangs my system with latest DXVK or with 0.52, but works fine with 0.51.
After this hang happens, the only thing I can do is a hard reboot.

### Software information
World of Warcraft, highest graphics settings used.

### System information
- OS: Arch Linux
- GPU: AMD Radeon HD7770
- Driver: today's latest Mesa-git, but this hang happens with any other Mesa stable version too.
- Wine version: today's latest Wine-git + Staging-git, but this hang happens with any other Wine version too.
- DXVK version: 49bda46 or/and 0.52, no difference, it both lead to hang. 

### Apitrace file(s)
- I have no idea how to get it.

### Log files
- terminal output:
[wow-os-hang-log.txt](https://github.com/doitsujin/dxvk/files/2039293/wow-os-hang-log.txt)

- d3d11.log: 
[Wow-64_d3d11.log](https://github.com/doitsujin/dxvk/files/2039299/Wow-64_d3d11.log)

- dxgi.log: 
[Wow-64_dxgi.log](https://github.com/doitsujin/dxvk/files/2039302/Wow-64_dxgi.log)

**Comment by Yardanico** [comment]
It must be an issue in the driver

**Comment by Kerrung** [comment]
@Yardanico 
>It must be an issue in the driver

I already checked this version. I also tried Mesa 18.0.4 and Mesa 18.1.0, but there's no difference. Hangs happen only if I use the latest DXVK, but do not happen if I use DXVK 0.51.

**Comment by doitsujin** [comment]
Please bisect.

**Comment by doitsujin** [comment]
@Kerrung please bisect to figure out the exact commit that causes the issue. This is critical.

**Comment by Kerrung** [comment]
@doitsujin 
It seems that I should try to test each commit between 0.51 and 0.52

**Comment by doitsujin** [comment]
@Kerrung just use `git bisect` (see [here](https://git-scm.com/docs/git-bisect)).

**Comment by TestMode1** [comment]
This could be due to game window settings. Can you try with windowed, fullscreen, etc?

**Comment by SveSop** [comment]
AMD related i guess. Used nVidia 369.24.02 driver, and latest git and do not crash in World of Warcraft atm.

Did not do a lengthy run, so was just popping a few places with my mage.

**Comment by Korvox** [comment]
I can reproduce it with a 580, so its an AMD bug, and it does happen on both trunk and release Mesa.

**Comment by doitsujin** [comment]
@Korvox @Kerrung Please test again with latest `master`. a0e0ba1cc8f62ff2f9ea8cac4415ad268447e8c6 fixes a regression that was causing GPU hangs in Far Cry 3, this issue is probably the same.

**Comment by Kerrung** [comment]
@doitsujin, iI just tested a0e0ba1 and it fixed for me.
Thank you very much!
Do you need any more help from me? Unfortunately, I did not have time to do what [you asked for](https://github.com/doitsujin/dxvk/issues/393#issuecomment-392077699).
Is this still relevant and should I still do this?

**Comment by Kerrung** [comment]
@doitsujin, iI just tested a0e0ba1 and it fixed for me.
Thank you very much! You are a real code wizard! Thank you for everything you do!
Do you need any more help from me? Unfortunately, I did not have time to do what [you asked for](https://github.com/doitsujin/dxvk/issues/393#issuecomment-392077699).
Is this still relevant and should I still do this?

**Comment by doitsujin** [comment]
Thanks for reporting back. There's no need to bisect anymore since the issue was fixed.

**Comment by Kerrung** [comment]
@doitsujin, I apologize for this offtopic, but I assume that [this information can be useful to you](https://github.com/roderickc/wine-vulkan/issues/14#issuecomment-392101551). Wine will soon receive the full support of Vulkan 1.1 and, as I suppose in the future Wine will continue to receive all updates of the latest versions of Vulkan.
Can DXVK really benefit from the support of Vulkan 1.1+ in Wine?
Thank you.
