### ISSUE TITLE
X-Men Origins: Wolverine missing/black textures

### ISSUE THREAD

**Issue by kevinwidjaja21** [doitsujin/dxvk#3930]
Dark texture when running the game using DXVK 2.3.1. No issue when gallium nine is used. Tested on Renoir RADV iGPU, RTX 2070 NVK and R9 380X RADV.

![Screenshot_20240329_155814](https://github.com/doitsujin/dxvk/assets/19798208/b6bda1b9-5e7d-4db8-9f4a-f708ea4f4b9e)
![Screenshot_20240329_155918](https://github.com/doitsujin/dxvk/assets/19798208/2c36505f-2d67-401b-942e-ef3ebb725197)

### Software information
- X-Men Origins: Wolverine with recommended setting from PCGW.

### System information
- GPU: Renoir Vega 6 RADV iGPU, RTX 2070 NVK and R9 380X RADV
- Driver: Mesa 24.1.0-devel
- Wine version: 9.5 Staging and Wine-GE 8.26
- DXVK version: 2.3.1

### Apitrace file(s)
- Backtrace ([Wolverine.7z](https://drive.google.com/file/d/10trNcX4InotfB91aMOdw9CSMW7GbklBQ/view?usp=sharing))

Weirdly, the backtrace doesn't show the issue on replay.

### Log files
[wine.log](https://github.com/doitsujin/dxvk/files/14801388/wine.log)

**Comment by mrdeathjr28** [comment]
Hi

in my case stay works with renoir igpu oc 2300mhz (wine 9.5 vanilla + dxvk 2.3.1 + mesa drivers 24.1 03-02)

![wolva](https://github.com/doitsujin/dxvk/assets/6601480/1245750d-ec73-4b53-b847-2216cfa9edee)

![wolvb](https://github.com/doitsujin/dxvk/assets/6601480/23b0d6e4-5749-4a4a-9f91-8fd61f06106d)


and i use custom settings in wengine.ini and marked as read only for prevent game change settings

![wolvc](https://github.com/doitsujin/dxvk/assets/6601480/ffdfbc3f-c982-482a-bc84-34683d0957e8)

![wolvd](https://github.com/doitsujin/dxvk/assets/6601480/875b0474-8995-49f2-a8e3-310cbac90d72)

![wolve](https://github.com/doitsujin/dxvk/assets/6601480/1ba13a8e-545d-4c7c-aaff-fadfc3507436)

**Comment by K0bin** [comment]
![image](https://github.com/doitsujin/dxvk/assets/1131720/d7b36d9a-3068-4f72-9aef-2a8c343cf2f3)
Looks fine when replaying the apitrace.

**Comment by K0bin** [comment]
![image](https://github.com/doitsujin/dxvk/assets/1131720/af478a8b-64ea-49fb-931f-c94f5fe200ed)
The game itself looks fine too.

**Comment by Blisto91** [comment]
@kevinwidjaja21 I haven't been able to reproduce either so far. Could you send you config file?

**Comment by Blisto91** [comment]
@kevinwidjaja21 Friendly ping

**Comment by kevinwidjaja21** [comment]
Hi sorry. I think I will close the issue as I was able to fix it by making the config read only.
