### ISSUE TITLE
Joe Danger 1: Runs uncapped at display rate

### ISSUE THREAD

**Issue by waspennator** [doitsujin/dxvk#3931]
Joe Danger 1 recently started working on deck thanks to proton Experimental, but the game has an issue where the framerate is determined by your devices refresh rate. It works fine at 60 fps on an LCD Deck, but on an OLED Deck running at 90 fps, this makes the game go turbo since the game speed is tied to the framerate.

https://www.pcgamingwiki.com/wiki/Joe_Danger

### Software information
Joe Danger 1

### System information
- GPU: AMD Van Gogh 
- Driver: Mesa 23.1.3
- Wine version: 9.0
- DXVK version: Unsure what version is being used in proton

### Apitrace file(s)
- 

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

[steam-229890.log.txt](https://github.com/doitsujin/dxvk/files/14816810/steam-229890.log.txt)

**Comment by ranplayer** [comment]
@waspennator this game uses OpenGL instead of DirectX

**Comment by waspennator** [comment]
> @waspennator this game uses OpenGL instead of DirectX

I thought it used directx looking at the system requirements,  still it would be nice if there could be some way of limiting the framerate to 60 outside of doing it through the Steam deck ui or locking it through the launcher.

**Comment by mbriar** [comment]
It's opengl: https://www.pcgamingwiki.com/wiki/Joe_Danger#Other_information
system reqs will just mention directx a lot of the time because that's what people know.
DXVK can't do anything about framerate limits in opengl games.

**Comment by waspennator** [comment]
> It's opengl: https://www.pcgamingwiki.com/wiki/Joe_Danger#Other_information system reqs will just mention directx a lot of the time because that's what people know. DXVK can't do anything about framerate limits in opengl games.

On second thought yeah just disregard this report, I'm dumb and dunno how I missed that.

**Comment by Blisto91** [comment]
> It's opengl: https://www.pcgamingwiki.com/wiki/Joe_Danger#Other_information system reqs will just mention directx a lot of the time because that's what people know. DXVK can't do anything about framerate limits in opengl games.

I totally didn't just add that to the page after you wrote it was OpenGL :no_mouth:

**Comment by ranplayer** [comment]
The game has a builtin FPS locker if you click on Custom settings (but only 30 FPS):
![joe-danger](https://github.com/doitsujin/dxvk/assets/69990640/495494f1-d293-4c3b-b0b9-995576f1af4e)

So far I haven't faced issues playing it at 75hz.
