### ISSUE TITLE
Elder Scrolls Online makes system stutter when nearing 100% GPU usage

### ISSUE THREAD

**Issue by zastrixarundell** [doitsujin/dxvk#3932]
### Software information
Elder Scrolls Online (steam gameid: 306130), running on Steam Flatpak and latest Proton-GE

### System information
- GPU: 6600XT
- Driver: Mesa 23.3.6
- Wine version: Proton GE-Proton9-1
- DXVK version: 2.3.0/1.3.274

### Apitrace file(s)
[eso64.trace](https://drive.google.com/file/d/1b7fsLRR5g_F_QX4_pEnObHQOqQgs7XGD/view?usp=sharing)

### Log files
(it was 37MB and GitHub limit is 25MB)
[steam-306130.log](https://drive.google.com/file/d/1gd1nDZi72ezdsoAaf9yo2WBWb29409oq/view)

### Additional Assets
Elder Scrolls GPU usage example:
> Generally the whole system starts stuttering a little bit and my camera snapshots from one place to another.

![image](https://github.com/doitsujin/dxvk/assets/30195425/0be11918-c91f-4d67-9142-d9133d0aa64f)
![image](https://github.com/doitsujin/dxvk/assets/30195425/046fcc88-8518-43dd-8b8a-9506e196c6bd) 

Wither 3 GPU usage example:
![image](https://github.com/doitsujin/dxvk/assets/30195425/d5210766-9e91-4327-ba7e-4f7236c3038e)

Doom Eternal GPU usage example:
> It isn't DXVK but just to show that it's not happening on other "engines".

![image](https://github.com/doitsujin/dxvk/assets/30195425/f8ca8e87-ad62-4ae7-8bc7-caa2f298a3cc)

**Comment by mbriar** [comment]
this seems like something completely outside of DXVK's control

**Comment by zastrixarundell** [comment]
Ah I did comment on MangoHud's Discord server and got told it might be a DXVK bug. If it's not can you lead me to the correct location to report it?

**Comment by mbriar** [comment]
As a quick guess i'd either suspect:

- desktop/compositor, so maybe try a different one, like you already said
- powermanagement and/or kernel driver, maybe try what is mentioned in this comment: https://gitlab.freedesktop.org/drm/amd/-/issues/1500#note_825883 or report a bug in this gitlab if nothing else helps
- potentially also vulkan driver, you could try with amdvlk instead of mesa

**Comment by zastrixarundell** [comment]
This is using wayland to disable compositor is a no-go:
* Switched to gnome, same issue
* I don't see that helping out as the issue is during light load, this is under 99% GPU load and 100W
* I'll try out with amdvlk in a sec, I'll have to figure it out how to run it on fedora kinoite

**Comment by mbriar** [comment]
> I don't see that helping out as the issue is during light load, this is under 99% GPU load and 100W

I wouldn't trust the default powermanagment under almost full gpu load either

> I'll try out with amdvlk in a sec, I'll have to figure it out how to run it on fedora kinoite

you can just extract the release archive from their github, edit the path in the .json, and use it with VK_ICD_FILENAMES=/path/to/icd.json on any distro

**Comment by mbriar** [comment]
Yeah, flatpak is going to make it complicated (as usual). You'd need a flatpak runtime extension for amdvlk, which i'm not sure even exists.

**Comment by zastrixarundell** [comment]
Oh I think I managed to actually make it work with amdvlk the first time. Because now when I changed the filepaths (and kept the original ones) it gives me an error that vulkan doesn't want to start (at least on the global override).

Is there a way to check if I'm using amdvlk?

**Comment by mbriar** [comment]
> Is there a way to check if I'm using amdvlk?

DXVK_HUD=full, it will say something like `6600XT (RADV)` in the device string for mesa/radv, and will be missing the (RADV) on amdvlk.

**Comment by zastrixarundell** [comment]
Ok I'm running amdvlk on the flatpak version :tada: 

... still have the stutters though:
> I opened a game cinematic just because it has a darker screen so it's easier to read the values.

![image](https://github.com/doitsujin/dxvk/assets/30195425/caef1b0c-2bbc-4df0-8a7c-df344b26982c)

**Comment by mbriar** [comment]
Does your motherboard bios allow you to enable ReBAR/above 4g decoding (i can tell from the dxvk hud that it's disabled)? It shouldn't be causing these issues either way, but might be interesting to see if enabling that changes anything.

**Comment by zastrixarundell** [comment]
Well it's definitely better and more fluid, but it's still does stutter from time to time which isn't present in other games. I don't have a problem with disabling the option to see the root cause of the fix. 

But thanks for the tip, it'll be helpful in the future!

**Comment by zastrixarundell** [comment]
Something is definitely up with this game:
![image](https://github.com/doitsujin/dxvk/assets/30195425/a11ec175-4505-4333-a3f7-aec68ab671aa)

System became borderline unusable.

**Comment by zastrixarundell** [comment]
So I got a 7800X3D and it's still an issue. The FPS cap is higher a bit, yes, but still happens:
(CPU label is wrong, I've yet to manually update it)

![image](https://github.com/doitsujin/dxvk/assets/30195425/186c078d-5af7-48c1-91f6-e613ba6e77df)

**Comment by zastrixarundell** [comment]
Also happening on a 7900XTX + 7800X3D

**Comment by zastrixarundell** [comment]
Weird enough I don't see the issue when running via Heroic. So most likely it was an issue with Steam's proton.
