### ISSUE TITLE
Ghostrunner Crash

### ISSUE THREAD

**Issue by 7AllenWalker7** [doitsujin/dxvk#3935]
I can launch Ghostrunner DX11 on dxvk with nvidia card on windows 10?
Now I have crash on start screen.

```
info:  Memory type mask for sparse resources: 0x2
warn:  DXVK: No state cache file found
info:  DXVK: Graphics pipeline libraries supported
info:  DXVK: Using 8 compiler threads
warn:  D3D11Texture2D::QueryInterface: Unknown interface query
warn:  696442be-a72e-4059-bc79-5b5c98040fad
warn:  D3D11DXGIDevice::QueryInterface: Unknown interface query
warn:  189819f1-1db6-4b57-be54-1821339b85f7
info:  DXVK: Using 8 compiler threads
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Color space:  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR (dynamic: yes)
info:    Buffer size:  3440x1440
info:    Image count:  3
info:    Exclusive FS: 1
warn:  DXVK: Creating new state cache file
warn:  D3D11: Failed to write shared resource info for a texture
warn:  D3D11Device::OpenSharedResourceGeneric: Handle not found: 0x40000642
```

**Comment by 7AllenWalker7** [comment]
I have not tried to do this before, it was needed now for checks)
The game has dx11 and dx12 modes, I wanted to run dx11 on vulcan

**Comment by mrdeathjr28** [comment]
In my case dx11 works (ghostrunner gog version) using dxvk 2.3.1 but i use linux only

![grdx11a](https://github.com/doitsujin/dxvk/assets/6601480/d831eb57-0bae-41eb-8efc-386f8781bddf)

![grdx11b](https://github.com/doitsujin/dxvk/assets/6601480/326574d7-522c-47c8-90f2-d96d63cac455)

**Comment by K0bin** [comment]
The game works with DXVK on Linux. Windows isn't exactly a  supported platform for DXVK and the problems there are usually outside of our control anyway.
