### ISSUE TITLE
Is not a but request 

### ISSUE THREAD

**Issue by kedrick021** [doitsujin/dxvk#3937]
Can you make dxd 11 for Mali GPU please 🥺 I really like to sone good game but dxd 11 🙏

**Comment by Blisto91** [comment]
Using dxvk on any device is just about having proper Vulkan drivers (1.3 for dxvk 2.0+) and software to run the games (e.g Wine on Linux).
dxvk only officially supports Linux and the drivers mentioned here https://github.com/doitsujin/dxvk/wiki/Driver-support

**Comment by K0bin** [comment]
Mali GPUs are missing various hardware features that are required to run D3D11 games.
