### ISSUE TITLE
[regression, d3d9] Cloudphobia crashing on startup

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#3938]
Originally reported at https://github.com/ValveSoftware/Proton/issues/7633

I have bisected this crash to be a regression starting from commit https://github.com/doitsujin/dxvk/commit/1f88ee595f4c3a2300388a1068ab865ea3215277

### Software information
[Cloudphobia](https://store.steampowered.com/app/329340/cloudphobia/)

### System information
- GPU: RX 6800
- Driver: mesa main
- Wine version: Proton 7.0-6 -> Bleeding Edge
- DXVK version: https://github.com/doitsujin/dxvk/commit/1f88ee595f4c3a2300388a1068ab865ea3215277 and up

### Apitrace file(s)
Reproduces the issue
https://drive.proton.me/urls/E9FGM9DE4C#Jg93l0R0AgGv

Edit: added a wined3d trace in addition to the dxvk trace captured from before the crashing commit. 
I noticed the dxvk trace crashes both when replayed with the dxvk commit (but not prior) and wined3d. The wined3d trace crashes with neither. Maybe the game chooses a different path or something. Credit to @WinterSnowfall for getting me to check

### Log files
[steam-329340.log](https://github.com/doitsujin/dxvk/files/14875531/steam-329340.log)

**Comment by waspennator** [comment]
I can confirm it happens on my windows laptop too using DXVK, if I launch it without it, it's fine. Made a trace running through native windows.

[cloudphobia.zip](https://github.com/doitsujin/dxvk/files/14968544/cloudphobia.zip)

**Comment by WinterSnowfall** [comment]
There's a call to `CheckDepthStencilMatch()`, using D32 as the depth stencil format, that works with dxvk but returns D3DERR_NOTAVAILABLE with WineD3D, the latter of which should be the correct behavior. I'll PR something to check the depth stencil formats as well during that call, to ensure we actually support them. That's not currently being done.
