### ISSUE TITLE
MGSV: TPP black screen (only UI visible) on Windows

### ISSUE THREAD

**Issue by EQQx110** [doitsujin/dxvk#3939]
Everything is black apart from UI like loading screens, menus, etc... The game runs fine apart from that. Latest driver which works is 24.1.1.

### Software information
Metal Gear Solid V: The Phantom Pain, with VSR.

### System information
- GPU: RX 6700 XT
- Driver: 24.3.1
- Windows 10
- DXVK version:  2.3.1

### Log files
[mgsvtpp_d3d11.log](https://github.com/doitsujin/dxvk/files/14880277/mgsvtpp_d3d11.log)
[mgsvtpp_dxgi.log](https://github.com/doitsujin/dxvk/files/14880278/mgsvtpp_dxgi.log)

**Comment by Blisto91** [comment]
Hi there. 
As you are hinting at i think this is just a driver issue. I can reproduce something similar ish with amdvlk 2024.Q1.2 on Linux but it works fine again with 2024.Q1.3 so this will likely solve itself on next Windows driver update.
Radv on Linux is also fine

**Comment by EQQx110** [comment]
Thank you for the answer. I'll keep playing with the old driver until the next update.
