### ISSUE TITLE
Elder Scrolls Online: Enabling Fullscreen & Borderless Window with vsync disabled and >60 fps will freeze the game

### ISSUE THREAD

**Issue by varris1** [doitsujin/dxvk#394]
TESO will freeze at random when Fullscreen & Borderless Window modes are enabled **and** Vsync is disabled (+ having more than 60 fps). I have to switch to window mode and force fullscreen via my window manager to be able to play.

Music will still play and it's still possible to switch to a different workspace and kill the process.

Setting "Subsampling Quality" to high will freeze the game immediately.
![teso-subsampling](https://user-images.githubusercontent.com/38386180/40556316-8d0003e2-604c-11e8-9707-a330b6959c81.png)

### Software information
The Elder Scrolls Online
Game Settings: [UserSettings.txt](https://github.com/doitsujin/dxvk/files/2040084/UserSettings.txt)

### System information
- GPU: NVIDIA GTX 970
- Driver: 396.24.02
- Wine version: wine-staging 3.8
- DXVK version: 84a62f79

### Apitrace file(s)
Tracing will reduce the fps below 60 fps, making the issue disappear.

### Log files
- d3d11.log:
[eso64_d3d11.log](https://github.com/doitsujin/dxvk/files/2040222/eso64_d3d11.log)

- dxgi.log: 
[eso64_dxgi.log](https://github.com/doitsujin/dxvk/files/2040223/eso64_dxgi.log)

**Comment by zaps166** [comment]
DXVK games freezes on nvidia drivers on full screen, vsync off (>60 fps) and flipping on (see https://github.com/doitsujin/dxvk/issues/267#issuecomment-387233232).

**Comment by varris1** [comment]
@zaps166 
That's it. I suspected a regression from 0.40 and 0.42, but after restarting the bisect 4 times, it still froze.

What a waste of time. Thanks for telling me so I can lay this to rest.

**Comment by ssorgatem** [comment]
I've noticed the same issue on AMD (Vega 56, mesa-git).
But I wasn't sure whether it was due to mesa or LLVM or something else.

If it's happening on NVIDIA too it looks like it could be a DXVK issue.

Also, it takes very long to reproduce (maybe ~2h or more of playing before it freezes), at least at "Medium" subsampling quality on a 4K monitor.
