### ISSUE TITLE
Severe performance issues in Payday 2 (Windows)

### ISSUE THREAD

**Issue by LONINFINITY** [doitsujin/dxvk#3940]
Running Payday 2 on Windows 11 23H2 with DXVK included (32x d3d9.dll) causes a severe drop in performance and framerate, consistently around 15fps (normally up to 300 without DXVK). Attempts to use older versions of DXVK (down to 2.1, older versions than that cause unrelated issues) yielded the same issue.
D3D9 log appears to contain some possibly useful information and has been included alongside the apitrace.

### Software information
[Payday 2](https://store.steampowered.com/app/218620/PAYDAY_2/)
Game version 240.5, both modded and unmodded

### System information
- OS: Windows 11 23H2 (Build 22631.3296)
- GPU: AMD RX 7800xt
- Driver: Adrenalin 24.3.1 (Driver version 23.40.27.01)
- DXVK version: 2.1-2.3.1
- Wine version: N/A

### Apitrace file(s)
[API Trace](https://drive.google.com/file/d/1qAumTGEynfIsQX6B_ivqp5q7VZ5x-_sr/view?usp=sharing)
[D3D9 Log](https://drive.google.com/file/d/16QlMGE10YrkFT9piZSh8ydg_r2hwU00q/view?usp=sharing)

**Comment by Blisto91** [comment]
Newer Windows AMD drivers are known to not work with dxvk. Try installing 23.8.2

**Comment by LONINFINITY** [comment]
That's... unfortunate, given I updated to prevent instability in Helldivers 2. I take it this is just something I'll have to wait for AMD to fix rather than something on DXVK's end?

**Comment by LONINFINITY** [comment]
That's a shame - thank you for the quick response regardless! Marking this as closed since it's not a DXVK issue.
