### ISSUE TITLE
[Command and Conquer Generals - Zero Hour] DXVK affecting pathfinding of Steam version

### ISSUE THREAD

**Issue by Sokol550** [doitsujin/dxvk#3941]
Command and Conquer Generals - Zero Hour
Framerate capped to 60 FPS.

### System information
- GPU: Radeon 6800 XT
- Driver: 24.3.1
- DXVK version: 2.3.1
- OS: Windows 11 23H2

### Apitrace file(s)
https://drive.google.com/file/d/1VVUQD5VDbVPwNIR3vv8yQtt7lkNhNTwr/view?usp=sharing

When playing GenZH via the newly released Steam version, some AI pathfinding is affected in a negative way. Most notably resource gatherers will abandon proper pathing to supply drop points and go across the map often being destroyed by enemies. Tested with and without mods, on a fresh install, with and without RTSS running, and finally with and without DXVK. Disabling DXVK solved the pathfinding issue. The Steam version apparently uses a new executable in comparison to older versions of the game, aside from that I have no clue as to how DXVK is even touching pathfinding code.

Edit: Closed and reopened after additional testing listed for Windows machines, issue continues.

**Comment by WinterSnowfall** [comment]
Granted I don't have this on Steam, but have played it using retail copies. I'm not sure how you can use dxvk with this game since it uses d3d8, which dxvk doesn't (yet) support.

**Comment by Sokol550** [comment]
Forgot to mention I'm using d3d8to9 to make dxvk work. Never had this issue in the past with both retail copies and Origin versions. However, if using d3d8to9 could be enough to screw with things I can close this and clock it up to a me problem.

**Comment by WinterSnowfall** [comment]
It could affect things to some degree, yes.

I'd recommend giving [d8vk](https://github.com/AlpyneDreams/d8vk/releases/tag/d8vk-v1.0) a go directly and see if you can reproduce the problem there. Apart from some minor menu slowdowns the retail version of the game is known to work well with d8vk, but I admit I never tried it with d3d8to9 + dxvk.

**Comment by Sokol550** [comment]
Unfortunately d8vk would only run for about 20 or so seconds in game then crash to desktop, capping the framerate to 30 fps did seem to fix it though. Guess it's just an engine bug. Appreciate the help regardless.
