### ISSUE TITLE
Higher fps in borderlands 2 but high stuttering in combat

### ISSUE THREAD

**Issue by alexhudg06** [doitsujin/dxvk#3947]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Name of the game, settings used etc.
Borderlands 2 max settings

### System information
- GPU: PowerColor RX 7800xt
- Driver:24.3.1
- Wine version: I probably need wine lmao
- DXVK version: 2.3.2

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

**Comment by K0bin** [comment]
This is probably just caused by the AMD Windows driver not supporting VK_EXT_graphics_pipeline_libraries.

**Comment by alexhudg06** [comment]
> This is probably just caused by the AMD Windows driver not supporting VK_EXT_graphics_pipeline_libraries.

It seems to have gotten better once I let the shaders cache per area but could that really be the cause?

**Comment by Blisto91** [comment]
Yes. The extension mentioned above is specifically used to help such issues. Though Unreal Engine games are in general just not great in that regard.

**Comment by mbriar** [comment]
Yes, that is most likely the case. You can stand around in on spot as long as you want, it will still stutter on every new effect/material/object/whatever. Without VK_EXT_graphics_pipeline_libraries, DXVK can't precompile any shaders. That said, amdvlk enabled VK_EXT_graphics_pipeline_libraries for DXVK with the last update, so it's only a matter of time until it hits windows.

**Comment by alexhudg06** [comment]
> Yes, that is most likely the case. You can stand around in on spot as long as you want, it will still stutter on every new effect/material/object/whatever. Without VK_EXT_graphics_pipeline_libraries, DXVK can't precompile any shaders. That said, amdvlk enabled VK_EXT_graphics_pipeline_libraries for DXVK with the last update, so it's only a matter of time until it hits windows.

so these files exist but there's
 no way to implement them right now?

**Comment by Blisto91** [comment]
It's a driver thing. The Windows driver doesn't expose the extension for dxvk at the moment. Likely next release

**Comment by mbriar** [comment]
It's not files, it's a vulkan extension and they are implemented in the linux vulkan driver. You will have to wait for AMD to update the windows driver.

**Comment by alexhudg06** [comment]
> It's not files, it's a vulkan extension and they are implemented in the linux vulkan driver. You will have to wait for AMD to update the windows driver.

Ah I see, unfortunate but your saying since this recent update happened with dxvk that amd is soon to update?

**Comment by mbriar** [comment]
AMD updated their linux vulkan driver with universal VK_EXT_graphics_pipeline_libraries support recently (before they explicitly disabled it for DXVK because it was apparently broken. The linux and windows drivers share the same base, so it is likely that this update will hit the windows driver soon.
