### ISSUE TITLE
Dirt 4 freezes after loading

### ISSUE THREAD

**Issue by AccountOneOff** [doitsujin/dxvk#395]
Dirt 4 loads into the menus and character creation but freezes when continued and it finishes loading.

### Software information
Dirt 4

### System information
- GPU: GTX 960
- Driver: 396.24
- Wine version: Staging 3.8
- DXVK version: b78130d

### Apitrace file(s)
- https://drive.google.com/open?id=1ZDIfmSaw4DXzve3JRCZrzl1YMy_U9Y8x

### Log files
- [dirt4_d3d11.log](https://github.com/doitsujin/dxvk/files/2041248/dirt4_d3d11.log)

- [dirt4_dxgi.log](https://github.com/doitsujin/dxvk/files/2041249/dirt4_dxgi.log)

Edit: Since I don't own this game I'll only be able to test it [until Sunday when the free weekend is over.](https://store.steampowered.com/app/421020/DiRT_4/)

**Comment by rafalcieslak** [comment]
When I switched from `396.24` to `396.24.02` it fixed similar freezes in a lot of games. Maybe it could help you too?

**Comment by doitsujin** [comment]
Haven't tested the game yet, but the latest set of commits up to a2d9874b26a57de512f7c31990051d8c495a4d63 implements a feature required some of the shaders. Previously those shaders did not compile at all.

**Comment by doitsujin** [comment]
@AccountOneOff I've been able to complete the tutorial with latest `master`, there shouldn't be any issues caused by DXVK.

**Comment by AccountOneOff** [comment]
Fixed in latest master.
