### ISSUE TITLE
Eschatos: Debug runtime popup

### ISSUE THREAD

**Issue by waspennator** [doitsujin/dxvk#3951]
Game seems to work fine, but testing on deck, if I run it with dxvk, this box pops up before launch, if I force wined3d it launches without the box. Same on my windows laptop running normally

![320141813-79036bb2-aaef-41cd-b104-effec9f4a01b](https://github.com/doitsujin/dxvk/assets/78768499/10c900d8-bb46-4914-9ee1-3c9413ccd09e)

### Software information
Eschatos

### System information
- GPU: AMD Van Gogh 
- Driver: Mesa 23.1.3
- Wine version: 9.0
- DXVK version: Unsure what version is being used in proton

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

[steam-378770.log](https://github.com/doitsujin/dxvk/files/14963363/steam-378770.log)

**Comment by Blisto91** [comment]
Can confirm it shows the popup when dxvk is used on Windows also. dgvoodoo2 is fine.

**Comment by WinterSnowfall** [comment]
Could you try with this build: [dxvk-devel.zip](https://github.com/doitsujin/dxvk/files/14968012/dxvk-devel.zip), and see if that does anything?

**Comment by waspennator** [comment]
Testing on my windows laptop, tried with both regular DXVK and the build you provided, still results in the same pop up.

**Comment by WinterSnowfall** [comment]
Thanks for trying it out. Is the trace captured with dxvk, WineD3D or native Windows?

**Comment by waspennator** [comment]
I'm guessing native windows, unsure cause I just downloaded the api trace files, slapped in the d3d9 one and ran it.

**Comment by WinterSnowfall** [comment]
I don't see anything out of the ordinary in the trace, except an early call to: `IDirect3DDevice9Ex::CreateQuery(this = 0xa5f5dc0, Type = D3DQUERYTYPE_VERTEXSTATS, ppQuery = ?) = D3DERR_NOTAVAILABLE`, which apparently fails on native, but should work fine with dxvk.

Here's a dxvk build that returns D3DERR_NOTAVAILABLE for that call to test with: [dxvk-devel-2.zip](https://github.com/doitsujin/dxvk/files/14968192/dxvk-devel-2.zip)

**Comment by waspennator** [comment]
Tried out that Devel-2 build and yep, that seems to fix it, Eschatos launched without that debug pop up box now.

**Comment by WinterSnowfall** [comment]
Yeah, thought so. According to official specs VERTEXSTATS is only available in debug runtimes: https://learn.microsoft.com/en-us/windows/win32/direct3d9/queries , so it sort of makes sense.

Still, a very silly check for a game to implement. I'll PR something to remove it, but I'm not sure if Josh or others need those queries for debugging/perf. testing or anything else, so we'll see how it goes.

**Comment by K0bin** [comment]
>  but I'm not sure if Josh or others need those queries for debugging/perf

Would be news to me and if Josh says so, we can still put it behind an environment variable.

**Comment by WinterSnowfall** [comment]
> > but I'm not sure if Josh or others need those queries for debugging/perf
> 
> Would be news to me and if Josh says so, we can still put it behind an environment variable.

I wouldn't bother if it's not explicitly needed then, since native doesn't support it.
