### ISSUE TITLE
GTA 4 wont open at all

### ISSUE THREAD

**Issue by GarbageMod** [doitsujin/dxvk#3952]
Hi there,

I got the latest DXVK release 2.3.1 but GTA IV won't work with it as soon as I put the 32bit d3d9.dll in the root folder the game does not open at all, I have to close in task manager.

I have a 3050 TI for a GPU and a AMD 7 5800H for a CPU, I don't believe these are outdated? I have the latest drivers installed, any ideas? no version will work, I tried version 1.0 and version 1.3 at least that opens the game and gives me a black screen before it crashes but these versions won't even open the game.

**Comment by Blisto91** [comment]
Logs please. They appear in the games folder usually next to the exe.

**Comment by GarbageMod** [comment]
> Attach dxvk logs please. They appear in the games folder usually next to the exe.

Only version 1.3 gave me logs, the rest didnt


info:  Game: GTAIV.exe
info:  DXVK: v1.3-2
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
err:   DxvkInstance::enumAdapters: Failed to enumerate adapters
info:  Game: GTAIV.exe
info:  DXVK: v1.3-2
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
err:   DxvkInstance::enumAdapters: Failed to enumerate adapters
info:  Game: GTAIV.exe
info:  DXVK: v1.3-2
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
err:   DxvkInstance::enumAdapters: Failed to enumerate adapters

**Comment by Blisto91** [comment]
> the rest didnt

Are you sure about that? Not even an empty log?
If no logs gets created then dxvk doesn't even get to initialize. But that doesn't sound right if an older version does

**Comment by GarbageMod** [comment]
> > the rest didnt
> 
> Are you sure about that? Not even an empty log? If no logs gets created then dxvk doesn't even get to initialize. But that doesn't sound right if an older version does

Just double checked and used the newest version again, yup, no logs, any ideas what may cause this?

**Comment by Blisto91** [comment]
Not personally no. But i am not a dev.

**Comment by mirh** [comment]
Can't you try any version between 2.3 and 1.3 (which is almost 5 years old by now)?
Also, what if you disable either the igpu or the dgpu?

**Comment by bloomingchad** [comment]
did you override the ddls in winecfg?

**Comment by Blisto91** [comment]
@GarbageMod friendly ping

**Comment by Blisto91** [comment]
@GarbageMod Double friendly ping
