### ISSUE TITLE
fallout 76 not open with  dxvk

### ISSUE THREAD

**Issue by Zengash** [doitsujin/dxvk#3953]
When I open the game, a black screen appears and the RTX 3070 game doesn't load, my friend with the AMD RX6570XT is working perfectly =/

obs drive updated latest version of my nvidia

**Comment by Blisto91** [comment]
Hi there. Please fill out the issue template

**Comment by Zengash** [comment]
who would be a friend?

**Comment by Blisto91** [comment]
Don't know but we at minimum need either dxvk logs or Proton/Wine logs to look at what is going wrong.

**Comment by Zengash** [comment]
where do I find these logs?

**Comment by Zengash** [comment]
[Fallout76_d3d11.log](https://github.com/doitsujin/dxvk/files/14964796/Fallout76_d3d11.log)
