### ISSUE TITLE
dxvk doesn't work on nvidia cards?

### ISSUE THREAD

**Issue by Zengash** [doitsujin/dxvk#3954]
Good morning, I can't run dxvk with nvidia cards? I'm using the great updated driver from Nvidia and it simply doesn't open the games using this dvxk. I tested Fallout 76 and God of War and it doesn't work, could you help me? Just below is the log for Fallout 76 and God of War

### System information
- GPU: RTX 3070
- Driver: 552.12
- Wine version: 
- DXVK version: 2.3.1

[GoW_dxgi.log](https://github.com/doitsujin/dxvk/files/14967387/GoW_dxgi.log)
[Fallout76_dxgi.log](https://github.com/doitsujin/dxvk/files/14967389/Fallout76_dxgi.log)

**Comment by Blisto91** [comment]
I would try to reinstall the driver

**Comment by Zengash** [comment]
I did this friend, I was using a previous drive 537.58 and I put the current one in thinking that could be why it isn't working but I wasn't successful

**Comment by Blisto91** [comment]
Not sure then. Windows isn't officially supported and there are a lot of environment, setup and game details that can be outside the devs control.
You can check out the Windows section on the wiki https://github.com/doitsujin/dxvk/wiki/Windows though I'm not sure any of the mentioned issues apply here.

**Comment by K0bin** [comment]
What Blisto said, DXVK isn't officially supported on Windows. Those games work fine on Linux, even on a Nvidia GPU.
