### ISSUE TITLE
Mass effects out of memory error wit DXKVv2.xx (works with DXKVv1.10.3)

### ISSUE THREAD

**Issue by FlaubertNHR** [doitsujin/dxvk#3958]
Mass effect doesn't work in WINE with DKV versions v2,x, but it WORKS with older version (v1.10.3). Black screen when starting game, with music.

err:virtual:allocate_virtual_memory out of memory for allocation, base (nil) size 00670000
err:   Exception on CS thread!
err:   DxvkDescriptorPool: Failed to create descriptor pool

### Software information
Mass Effect Ultimate Edition on WINE Prefix 32bits

### System information
- GPU: -
- Driver: Intel HD Graphics
- Wine version: WINEHQ Staging (9.6)
- DXVK version: 2.1+

### Apitrace file(s)
https://drive.google.com/file/d/1eEQPZT-C_rsCj_U38bYkDdrgSZOIZLoc/view?usp=sharing

### Log files
Please attach Proton or Wine logs as a text file:
Started initial process 23417 from gamemoderun /opt/wine-staging/bin/wine /home/nhr/Juegos/mass-effect/drive_c/Mass Effect Ultimate Edition/MassEffectLauncher.exe
Start monitoring process.
gamemodeauto: 
002c:fixme:winediag:loader_init wine-staging 9.6 is a testing version containing experimental patches.
002c:fixme:winediag:loader_init Please mention your exact version when filing bug reports on winehq.org.
0024:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
0144:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:fixme:exec:SHELL_execute flags ignored: 0x00000100
Initial process has exited (return code: 0)
015c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
015c:fixme:gameux:GameExplorerImpl_VerifyAccess (016792D0, L"C:\\Mass Effect Ultimate Edition\\Binaries\\MassEffect.exe", 0051EB98)
info:  Game: MassEffect.exe
info:  DXVK: v2.3.1
info:  Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @ 0x766337b0
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  Skipping CPU adapter: llvmpipe (LLVM 15.0.7, 256 bits)
info:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  Intel(R) UHD Graphics (ICL GT1):
info:    Driver : Intel open-source Mesa driver 24.0.5
info:    Memory Heap[0]: 
info:      Size: 11758 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:      Memory Type[1]: Property Flags = 0x7
info:      Memory Type[2]: Property Flags = 0xf
info:  Process set as DPI aware
warn:  D3D9InterfaceEx::QueryInterface: Unknown interface query
warn:  02177241-69fc-400c-8ff1-93a44df6861d
015c:fixme:system:NtUserSystemParametersInfo Unimplemented action: 59 (SPI_SETSTICKYKEYS)
015c:fixme:system:NtUserSystemParametersInfo Unimplemented action: 53 (SPI_SETTOGGLEKEYS)
015c:fixme:system:NtUserSystemParametersInfo Unimplemented action: 51 (SPI_SETFILTERKEYS)
info:  Device properties:
info:    Device : Intel(R) UHD Graphics (ICL GT1)
info:    Driver : Intel open-source Mesa driver 24.0.5
info:  Enabled device extensions:
info:    VK_EXT_conservative_rasterization
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_bias_control
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state3
info:    VK_EXT_fragment_shader_interlock
info:    VK_EXT_graphics_pipeline_library
info:    VK_EXT_non_seamless_cube_map
info:    VK_EXT_robustness2
info:    VK_EXT_shader_module_identifier
info:    VK_EXT_shader_stencil_export
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_maintenance5
info:    VK_KHR_pipeline_library
info:    VK_KHR_present_id
info:    VK_KHR_present_wait
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 0
info:    wideLines                              : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 0
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 1
info:    shaderResourceResidency                : 0
info:    shaderResourceMinLod                   : 0
info:    sparseBinding                          : 0
info:    sparseResidencyBuffer                  : 0
info:    sparseResidencyImage2D                 : 0
info:    sparseResidencyImage3D                 : 0
info:    sparseResidency2Samples                : 0
info:    sparseResidency4Samples                : 0
info:    sparseResidency8Samples                : 0
info:    sparseResidency16Samples               : 0
info:    sparseResidencyAliased                 : 0
info:  Vulkan 1.1
info:    shaderDrawParameters                   : 0
info:  Vulkan 1.2
info:    samplerMirrorClampToEdge               : 1
info:    drawIndirectCount                      : 1
info:    samplerFilterMinmax                    : 0
info:    hostQueryReset                         : 1
info:    timelineSemaphore                      : 1
info:    bufferDeviceAddress                    : 0
info:    shaderOutputViewportIndex              : 1
info:    shaderOutputLayer                      : 1
info:    vulkanMemoryModel                      : 1
info:  Vulkan 1.3
info:    robustImageAccess                      : 0
info:    pipelineCreationCacheControl           : 1
info:    shaderDemoteToHelperInvocation         : 1
info:    shaderZeroInitializeWorkgroupMemory    : 0
info:    synchronization2                       : 1
info:    dynamicRendering                       : 1
info:  VK_AMD_shader_fragment_mask
info:    extension supported                    : 0
info:  VK_EXT_attachment_feedback_loop_layout
info:    attachmentFeedbackLoopLayout           : 0
info:  VK_EXT_conservative_rasterization
info:    extension supported                    : 1
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_depth_bias_control
info:    depthBiasControl                       : 1
info:    leastRepresentableValueForceUnormRepresentation : 0
info:    floatRepresentation                    : 1
info:    depthBiasExact                         : 1
info:  VK_EXT_extended_dynamic_state3
info:    extDynamicState3AlphaToCoverageEnable  : 0
info:    extDynamicState3DepthClipEnable        : 1
info:    extDynamicState3RasterizationSamples   : 0
info:    extDynamicState3SampleMask             : 1
info:    extDynamicState3LineRasterizationMode  : 1
info:  VK_EXT_fragment_shader_interlock
info:    fragmentShaderSampleInterlock          : 0
info:    fragmentShaderPixelInterlock           : 0
info:  VK_EXT_full_screen_exclusive
info:    extension supported                    : 0
info:  VK_EXT_graphics_pipeline_library
info:    graphicsPipelineLibrary                : 1
info:  VK_EXT_line_rasterization
info:    rectangularLines                       : 1
info:    smoothLines                            : 0
info:  VK_EXT_memory_budget
info:    extension supported                    : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 0
info:  VK_EXT_non_seamless_cube_map
info:    nonSeamlessCubeMap                     : 1
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 1
info:    robustImageAccess2                     : 1
info:    nullDescriptor                         : 1
info:  VK_EXT_shader_module_identifier
info:    shaderModuleIdentifier                 : 1
info:  VK_EXT_shader_stencil_export
info:    extension supported                    : 1
info:  VK_EXT_swapchain_colorspace
info:    extension supported                    : 0
info:  VK_EXT_swapchain_maintenance1
info:    swapchainMaintenance1                  : 0
info:  VK_EXT_hdr_metadata
info:    extension supported                    : 0
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  VK_KHR_external_memory_win32
info:    extension supported                    : 0
info:  VK_KHR_external_semaphore_win32
info:    extension supported                    : 0
info:  VK_KHR_maintenance5
info:    maintenance5                           : 1
info:  VK_KHR_present_id
info:    presentId                              : 1
info:  VK_KHR_present_wait
info:    presentWait                            : 1
info:  VK_NV_raw_access_chains
info:    shaderRawAccessChains                  : 0
info:  VK_NVX_binary_import
info:    extension supported                    : 0
info:  VK_NVX_image_view_handle
info:    extension supported                    : 0
info:  VK_KHR_win32_keyed_mutex
info:    extension supported                    : 0
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 0
info:    Sparse   : n/a
warn:  DXVK: Updating state cache version to v17
info:  DXVK: Read 207 valid state cache entries
warn:  DXVK: Creating new state cache file
info:  DXVK: Graphics pipeline libraries supported
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1920
info:      - Height:             1080
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::Unknown
info:      - Windowed:           true
info:      - Swap effect:        3
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Color space:  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR (dynamic: no)
info:    Buffer size:  1920x1060
info:    Image count:  4
info:    Exclusive FS: 0
info:  DXVK: Using 8 compiler threads
015c:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Color space:  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR (dynamic: no)
info:    Buffer size:  1920x1080
info:    Image count:  4
info:    Exclusive FS: 0
015c:err:virtual:allocate_virtual_memory out of memory for allocation, base (nil) size 00670000
err:   Exception on CS thread!
err:   DxvkDescriptorPool: Failed to create descriptor pool
Monitored process exited.
Exit with return code 0

**Comment by doitsujin** [comment]
Can you test current `master`? I changed a few things to reduce the amount of descriptor memory we use in some cases, but this really just smells like the game *barely* runs to begin with and has literally no address space headroom.

**Comment by mrdeathjr28** [comment]
In my case works but this game dont work for muggles* XD (harry potter joke)

![msefa](https://github.com/doitsujin/dxvk/assets/6601480/04a0fd71-0798-4479-8c9f-1071f1b1a93c)

![msefc](https://github.com/doitsujin/dxvk/assets/6601480/4c3d2bc7-3e7b-41d2-90c4-7b815338da8f)

![msefd](https://github.com/doitsujin/dxvk/assets/6601480/fac3d0da-ba1a-4648-9e63-aebf503861f2)

![msefe](https://github.com/doitsujin/dxvk/assets/6601480/16372541-ef6f-489a-a520-339e62230d48)

back to serious wine have a huge changes recently and change require mesa driver 24.1 minimum as march 02 of 2024 because them add this:

VK_EXT_map_memory_placed

this extension in my test solve suddenly crashes in various games (various related to virtual memory)

and need wine 9.4 or newer

however non graphic related topic, this game need some kind of magic** for appear sound (in my case with virtual desktop, maybe with fullscreen mode could be different)

**you need run some app once stay in game main menu for appear game on taskbar, after this you can select game on taskbar and gameshow sound normally (maybe in future video show more detailed this situation, in before times this occur with some unreal engine 3 games)

**Comment by NHerreroReder** [comment]
My bad. It was "Legendary Edition".
Regarding DXVK, I tested 2.3.1 versión (it doesn't work). Tried to build "máster", but failed due to compilation errors.
Last DXVK versión that works is 1.10.3. From v2.1 all them failed to run game.
.

**Comment by mirh** [comment]
MELE doesn't have the launcher in the root folder (and neither an exe named `MassEffect`), and I'm pretty sure it shouldn't even start in a 32-bit prefix.

**Comment by Riesi** [comment]
> My bad. It was "Legendary Edition". Regarding DXVK, I tested 2.3.1 versión (it doesn't work). Tried to build "máster", but failed due to compilation errors. Last DXVK versión that works is 1.10.3. From v2.1 all them failed to run game. .

you dont have to build yourself
just get the latest CI artifact:
https://github.com/doitsujin/dxvk/actions/runs/8675377536

**Comment by Blisto91** [comment]
@FlaubertNHR Please try to give this another swing with dxvk master if you are able.

**Comment by FlaubertNHR** [comment]
It seems to work right now. Thanks a lot
