### ISSUE TITLE
bad perfomance with nvidia cards

### ISSUE THREAD

**Issue by Zengash** [doitsujin/dxvk#3959]
I managed to run dvxk in fallout, but the performance is worse than in dx11, did I do something wrong? On my friend's AMD card it had more frame stability, on mine with Nvidia I lose a lot of performance

**Comment by Blisto91** [comment]
How much of a performance drop are you seeing. dxvk does not guarantee a performance boost versus native and Nvidia have pretty good d3d11 drivers afaik.
While there is a goal of being roughly at least as fast as native or as a bonus faster this is not always the case right now.

**Comment by K0bin** [comment]
DXVK is built for Linux. It's far from guaranteed to be faster than regular D3D11 drivers on Windows.
