### ISSUE TITLE
Overwatch crashes on startup 

### ISSUE THREAD

**Issue by MeissnerEffect** [doitsujin/dxvk#396]
### Software information
Overwatch. First time attempting to play it, crashes immediately on startup before anything shows up on screen. Seems to work with wine3d.

Seems the error that causes it is in the dxgi.log

```
err:   DxvkSurface::createSurface: Surface not supported by device

err:   DXGI: DxgiSwapChain: Failed to create presenter or back buffer
```

### System information
- GPU: nvidia 960M
- Driver: 396.24
- Wine version: 3.8-staging
- DXVK version: master (tested with a6ace79 as well)

### Apitrace file(s)
[Without DXVK](https://drive.google.com/file/d/1x6JlZMqBsQH0do0rc4GZ9hYbWjMVKnSG/view?usp=sharingl)
[With DXVK](https://drive.google.com/open?id=14DmM5TOGBWLh5fKcFBM8F5BWCjXuajek)

### Log files
[d3d11.log](https://drive.google.com/open?id=1r9-iprwI9sumrTcMONl55jO-xpelD2zz)
[dxgi.log](https://drive.google.com/open?id=14hx3pL_uqmIpLoOGMjzufm1s5zj3uZjG)

**Comment by exolyte** [comment]
You should try blacklisting your intel vulkan driver with the VK_ICD_FILENAMES environment variable.

For example: `export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json` makes sure dxvk will only use the 64 bit amd vulkan driver. I'm not sure how the nvidia file is called and the path may be different on your distro.

**Comment by varris1** [comment]
Did you start OW directly or through Battle Net?

If you did start it through BNet, disable streaming in the settings menu.

**Comment by MeissnerEffect** [comment]
@exolyte that fixed it, I find it strange that it loads the correct driver for other games without the env var (even in the same wine prefix)

@varris1 always directly!
