### ISSUE TITLE
When i play undertale with wine d3d,I try full screen,its bugged,on Winlator 6.1

### ISSUE THREAD

**Issue by Flisau** [doitsujin/dxvk#3960]
[Please](url
![Screenshot_20240419-000634](https://github.com/doitsujin/dxvk/assets/158436025/bb9b4070-0b4d-45dc-8fe8-6cf0c26ae466)
![Screenshot_20240419-000634](https://github.com/doitsujin/dxvk/assets/158436025/a001d8f1-139a-487d-8827-8d7dbc4c6e18)
) describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Name of the game, settings used etc.

### System information
- GPU:
- Driver:Turnip(Adreano) 
- Wine version:WineD3D
- DXVK version: 

### Apitrace file(s)
- Put a link here
![Screenshot_20240419-000634](https://github.com/doitsujin/dxvk/assets/158436025/513af13e-a9dd-4b12-bb7c-d937ce603f48)

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

**Comment by mbriar** [comment]
Neither wined3d nor android are supported here.

**Comment by K0bin** [comment]
What mbriar said.
