### ISSUE TITLE
Game Capped at 60 FPS

### ISSUE THREAD

**Issue by SvarunSoda** [doitsujin/dxvk#3969]
I have a question regarding this library, used with a video game from 2009 called Battlestations: Pacific. It's 32-bit, it uses DirectX 9 and Games for Windows LIVE (GFWL), on Windows 10.

We worked on a mod project for that game that involved creating a custom version of the [XLiveLessNess project](https://github.com/GlitchyScripts/xlivelessness), with the aim of restoring multiplayer functionality after GFWL got disbanded, and some other stuff. In our case, that involved creating a custom `xlive.dll` file that the game loads at startup, that included all our required modifications.

 We were successfully able to achieve most of our goals with that project, however we noticed an oddity;

For some reason, whenever the game loads a custom `xlive.dll` file, it appears to cap it's maximum framerate at 60 FPS during normal runtime... This doesn't only happen with our `xlive.dll` variant, but also with [other variations of Xliveless](https://community.pcgamingwiki.com/files/file/576-xliveless/) that are commonly used with other games, such as GTA 4. That was extremely puzzling to us, as the `xlive.dll` file we created didn't make any modifications to the way the game handled graphics or drawing stuff to the screen. Without a custom `xlive.dll`, the game returns to running normally at well above 60 FPS.

After doing some searching online, I saw [several posts](https://steamcommunity.com/app/12840/discussions/0/1739968490553203643/) about other games from the simillar time, suggesting this DXVK project that is often used with DirectX games.
I was wondering whether it would be possible to change the max framerate of a DirectX 9 game using this library, which appears to somehow be capped by the custom `xlive.dll` file.

I followed [your tutorial](https://github.com/doitsujin/dxvk/wiki/Using-Apitrace) on setting up the `Apitrace` 32-bit debug logging, and have put a link to a trace of the game down below under the system information. I simply entered & exited the game, while it was running at a capped 60 FPS. I ran this on the latest version of DXVK `Apitrace`.

I have also tried running the game with the latest DXVK release v2.3.1, and I noticed it produced another debug log. I have also attached that log to this post underneath the `Apitrace` log, in case that's helpful.

Thanks for reading my post, any guidance is appreciated. Let me know if anything else is required in order to give you a better idea of the situation.

### Game information
- Name: Battlestations: Pacific (2009)
- DirectX: 9
- Architecture: 32-bit
- OS: Windows 10

### System information
- GPU: Nvidia GTX 1060
- Driver: 546.17
- DXVK version: 2.3.1

### Trace/Log files
https://drive.google.com/file/d/1UnoPn4FCp25HVsgcTDnFSLeNuKfdHoC2/view?usp=sharing
[battlestationspacific_d3d9.log](https://github.com/doitsujin/dxvk/files/15084235/battlestationspacific_d3d9.log)

**Comment by Blisto91** [comment]
I'm not personally seeing an issue so far. Here i am running the game with xliveless from pcgamingwiki and vsync off.

<details>
  <summary>screenshots</summary>

![pacific-native](https://github.com/doitsujin/dxvk/assets/47954800/450c8bfd-0d78-4c1d-bf5b-9b3f371d8f19)
![pacific-dxvk](https://github.com/doitsujin/dxvk/assets/47954800/c6f39d65-cfdf-453e-a619-8026ef86a14d)
</details>

**Comment by SvarunSoda** [comment]
> I'm not personally seeing an issue so far. Here i am running the game on Windows 11 with xliveless from pcgamingwiki and vsync off.
> 
> screenshots
> ![pacific-native](https://private-user-images.githubusercontent.com/47954800/325178131-450c8bfd-0d78-4c1d-bf5b-9b3f371d8f19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5OTIzMzcsIm5iZiI6MTcxMzk5MjAzNywicGF0aCI6Ii80Nzk1NDgwMC8zMjUxNzgxMzEtNDUwYzhiZmQtMGQ3OC00YzFkLWJmNWItOWIzZjM3MWQ4ZjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDIwNTM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MTEyMzE2NTQ3OTdiZWNmMzNhNDdjNWNkZjc4MjY4OTQzODVlYWI2NWNkNjFmNjE4ZmQyMDcyODk3NjM5NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.piEoJkNPPv232TPC3XXdDFfpjvjLM1zYTwIFv0ZDKhM) ![pacific-dxvk](https://private-user-images.githubusercontent.com/47954800/325178153-c6f39d65-cfdf-453e-a619-8026ef86a14d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5OTIzMzcsIm5iZiI6MTcxMzk5MjAzNywicGF0aCI6Ii80Nzk1NDgwMC8zMjUxNzgxNTMtYzZmMzlkNjUtY2ZkZi00NTNlLWE2MTktODAyNmVmODZhMTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDIwNTM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MDA5OGQ1NDk1MTgzZmVhYmY2YmQxYjQ1ZDZlZWQyMzUwNTE0ZjQyZmQ3NjNiMjg3NjJlZjBhODEwYTRjZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rxlmwpEaEamPYbqOvGTp7ig9xpN68Ofm7k-GDwUceWM)

Thank you for your reply;

I sincerely apologize for the confusion, but I found out what the issue was. XLiveLessNess limits FPS, and ours was outdated so we didn't have access to the FPS changing functions.

Cheers!
