### ISSUE TITLE
[d3d9] DxvkContext::updatePushConstants always uses complete layout to update push constant

### ISSUE THREAD

**Issue by linqun** [doitsujin/dxvk#3971]
I encounter multiple d3d9 app hang issue with AMDVLK driver after enable graphics pipeline library.
and it looks all hang issues are due to incompatible pipeline layout is used in dxvk.

DXVK creates two pipeline layout  independentLayout and completeLayout.
- independentLayout  is used by graphics pipeline library and base pipeline.
- completeLayout is used by optimized pipeline.

But it looks DXVK sometimes use completeLayout to update resources, then draw with pipeline which is created from independentLayout.

After checking the source code, I found DxvkContext::updatePushConstants always uses complete layout to update push constant.
it looks incorrect. could you have a look? thanks!
- In AMDVLK driver,  independentLayout and completeLayout are incompatible for all resources, include push constant.

**Comment by doitsujin** [comment]
The Vulkan spec states:

> Pipeline Layout Compatibility
> Two pipeline layouts are defined to be “compatible for [push constants](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#descriptorsets-push-constants)” if they were created with identical push constant ranges.

The wording of the spec strongly suggests that `VK_PIPELINE_LAYOUT_CREATE_INDEPENDENT_SETS_BIT_EXT` **only** affects descriptor set compaibility, which we do honor, and that DXVK doesn't do anything illegal here.

**Comment by doitsujin** [comment]
Either way, here's a workaround, please let me know if that fixes problems for now:
https://github.com/doitsujin/dxvk/tree/amdvlk-push-constants

**Comment by doitsujin** [comment]
We have a different bug with push constants in that the D3D9 front-end declares different push constant ranges for vertex and fragment shaders, maybe that's the problem? Unfortunately that is far more difficult to fix.

**Comment by doitsujin** [comment]
https://github.com/doitsujin/dxvk/tree/push-const-fix This branch should fix the problem.

I also bumped the version number to 2.3.2 so that the driver can disable GPL for versions ≤2.3.1.

**Comment by linqun** [comment]
Verified with some d3d9 apps, include GTA4, Tropico4 and Team Fortress2. It works with AMD driver. Thank you very much for the quick fix. Please let me know once the change is merged. thanks!

**Comment by doitsujin** [comment]
Merged, thanks for confirming.
