### ISSUE TITLE
[d3d9] Cars TVG 2006 issue with textures(?)

### ISSUE THREAD

**Issue by amadeuskurisu02** [doitsujin/dxvk#3974]
This game have an issue starting with dxvk 2.3. I also tested latest artifacts from github and the issue is still present. I think it's texturing issue. In folder which contains apitrace files there are also videos with this issue with dxvk 2.3 and 2.3.1 and video with dxvk 2.2. With wined3d game just freezes before I can reproduce this issue.
![Screenshot_20240425-112725_mpv](https://github.com/doitsujin/dxvk/assets/152798631/0e51f34c-f9b6-491d-8cae-8469ef48afe7)
![Screenshot_20240425-112718_mpv](https://github.com/doitsujin/dxvk/assets/152798631/3c985f2e-5da8-45c8-acc5-137f5efa722e)
![Screenshot_20240425-112708_mpv](https://github.com/doitsujin/dxvk/assets/152798631/716c5b25-d46d-46e0-98d7-b0a66fe448a5)

### Software information
Cars, 2x aa(setting it to off dosen't change anything)

### System information
- GPU: adreno 650
- Driver: turnip 24.1.0-devel
- Wine version:  9.3
- DXVK version: 2.3, 2.3.1, 2.2

### Apitrace file(s)
https://drive.google.com/drive/folders/1N0k40hYbfLr60JbTlfwXZaoyAAAcApDo?usp=sharing

**Comment by Blisto91** [comment]
Hi there. I've tried replaying the trace on my Nvidia dGPU and AMD iGPU (radv) and haven't spotted anything. So unless the trace just doesn't reproduce it this is likely a Turnip specific issue.
I have the game so will try to check it out later

**Comment by amadeuskurisu02** [comment]
I also tried with different mesa turnip version. Nothing changed. Only lowering dxvk to 2.2 or lower solved the issue.

**Comment by Blisto91** [comment]
I've tested the Steam version for a bit on my Nvidia card with 2.3.1 but haven't been able to reproduce anything so far

**Comment by amadeuskurisu02** [comment]
> I've tested the Steam version for a bit on my Nvidia card with 2.3.1 but haven't been able to reproduce anything so far

In Tailfin Pass and in this region? It dosen't appear everywhere.

**Comment by Blisto91** [comment]
Ah no. I downloaded a 100% save now and tried driving in the area of your screenshots a few times but still nothing so far.

**Comment by amadeuskurisu02** [comment]
> Ah no. I downloaded a 100% save now and tried driving in the area of your screenshots a few times but still nothing so far.

Strange. Then I just don't know why I'm facing this issue only with 2.3 and onwards and why it isn't there with 2.2 and lower.

**Comment by Blisto91** [comment]
I tried with AMD radv (amdvlk crashes) but still saw nothing.
Think it might be an idea to make a mesa issue and see if the Turnip devs can figure something out

**Comment by mbriar** [comment]
Most likely a driver issue that's only triggered by newer dxvk (generally the most likely on drivers other than radv or nvidia proprietary, which are not that well tested with dxvk)

**Comment by amadeuskurisu02** [comment]
> I tried with AMD radv now (amdvlk crashes) but still saw nothing. Think it might be an idea to make a mesa issue and see if the Turnip devs can figure something out

Also it only triggers on very specific spots(coords).

**Comment by amadeuskurisu02** [comment]
Retested it with some older drivers and everything is fine.
