### ISSUE TITLE
RAFT not work :(

### ISSUE THREAD

**Issue by Snipy44** [doitsujin/dxvk#3977]
### Software information
Raft in Full Screen

### System information
- GPU: RTX 4090
- Driver: 552.22
- Wine version: Windows 11
- DXVK version:  2.0

Raft video game not work with DXVK :(

**Comment by Blisto91** [comment]
Test with latest release and post logs please

**Comment by Blisto91** [comment]
@Snipy44 Friendly ping

**Comment by Snipy44** [comment]
i finish the game now but thx lol
