### ISSUE TITLE
32-bit linking failure

### ISSUE THREAD

**Issue by SR-dude** [doitsujin/dxvk#398]
Compiling 64-bit went ok. However linking dxvk for 32-bit failed.

[2/16] Linking target src/dxgi/dxgi.dll.
FAILED: src/dxgi/dxgi.dll 
...
src/dxvk/libdxvk.a(vulkan_dxvk_vulkan_loader.cpp.obj): In function `dxvk::vk::LibraryLoader::sym(char const*) const':
/home/XXX/src/dxvk/build32/../src/dxvk/vulkan/dxvk_vulkan_loader.cpp:6: undefined reference to `vkGetInstanceProcAddr'

Perhaps I should just skip the 32-bit altogether.

### System information
Mesa version: OpenGL version string: 3.0 Mesa 18.0.4 (git-3b49ab6219)
vulkan SDK version: 1.1.70.1
mingw64 provided by crosstool-ng.

**Comment by doitsujin** [comment]
Works for me. Are you using the `package-release` script or building manually?

**Comment by SR-dude** [comment]
I'm invoking meson manually.

My question should be is vkGetInstanceProcAddr() defined in the RADV driver
or the vulkanSDK?

**Comment by doitsujin** [comment]
It's part of the Vulkan loader.

**Comment by doitsujin** [comment]
I'm shipping the `.lib` files required for linking with DXVK.

Please test if the package-release script works for you, it builds both 64-bit and 32-bit binaries.

**Comment by SR-dude** [comment]
I see it. OK you can close this.

But before I go, can you tell me where I get a good vulkan loader?
From mesa? from the SDK?

**Comment by doitsujin** [comment]
Wine provides its own loader, there's noting else you have to do.
