### ISSUE TITLE
Gothic 3

### ISSUE THREAD

**Issue by badewiese** [doitsujin/dxvk#3980]
### System information
- GPU: GTX 1070
- Driver: 546.33
- Wine version: - Windows 10
- DXVK version: 2.3.1

Incorrect operation of lighting from a torch
apitrace
https://drive.google.com/file/d/17XOd7zT2Gn6GeDAx6t9BN9gsC8Pbsjhm/view?usp=sharing

![Gothic3_2024_05_02_01_22_22_939](https://github.com/doitsujin/dxvk/assets/112763675/79929bb3-b17b-4fb5-8f18-603f9a7e21df)
![Gothic3_2024_05_02_01_21_01_124](https://github.com/doitsujin/dxvk/assets/112763675/9b9e87d8-dc7c-49dc-b974-33062bb524e9)

**Comment by Blisto91** [comment]
Hi there and thank you for the report.
If you could make a apitrace of the issue then that would be very helpful.

**Comment by badewiese** [comment]
> Hi there and thank you for the report. If you could make a apitrace of the issue then that would be very helpful.

Are there instructions on how to do this?

**Comment by Blisto91** [comment]
Yes https://github.com/doitsujin/dxvk/wiki/Using-Apitrace#on-windows

**Comment by badewiese** [comment]
> Yes https://github.com/doitsujin/dxvk/wiki/Using-Apitrace#on-windows
> 
> These files will replace the dxvk DLLs so won't have the issue while using them. But just make one in a location where you usually reproduce the issue and then we will replay then together with dxvk to see if it reproduces.

I did everything as in the instructions. The Gothic3.trace file weighs 1Gb. I compressed it into a zip archive to 462Mb. Alas, in 2024, I still have slow ADSL Internet in the private sector. We are waiting for the file to be uploaded to Google Drive.

**Comment by badewiese** [comment]
https://drive.google.com/file/d/17XOd7zT2Gn6GeDAx6t9BN9gsC8Pbsjhm/view?usp=sharing

**Comment by badewiese** [comment]
How long will it take to fix this lighting problem?

**Comment by Blisto91** [comment]
Unknown as the game is not playing well with debugging tools so far. That includes apitrace

**Comment by Blisto91** [comment]
A build with the fix can be downloaded here https://github.com/doitsujin/dxvk/actions/runs/9005724963

**Comment by badewiese** [comment]
> A build with the fix can be downloaded here https://github.com/doitsujin/dxvk/actions/runs/9005724963

Thank you very much. Now the torch lighting is working again. Will this fix be included in the main DXVK composition in the future?

**Comment by Blisto91** [comment]
Yes it will be included in the next release
