### ISSUE TITLE
Enquiry for more support for Left 4 Dead 2

### ISSUE THREAD

**Issue by Feiyunruoyi** [doitsujin/dxvk#3987]
As is known that Left 4 Dead 2 is a game remaining lively most based on its workshop and mods, but the case is, too many mods will lead the game to crash, however, without those mods, the game becomes boring.
Thanks to your contribution, with the aid of  "d3d9.dll" file, Left 4 Dead 2 now becomes less likely to crash, but still, game crashes are still there occasionally, Left 4 Dead 2 players really hope that you could update something new to prevent the game from crashing

**Comment by doitsujin** [comment]
We can't fix broken mods and we also can't fix 32-bit address space limitations.
