### ISSUE TITLE
Dxvk problems

### ISSUE THREAD

**Issue by Lennrj** [doitsujin/dxvk#3989]
windows 11 last Driver.
Rtx 3070
Ryzen 3600
asus tuf b450m

Dxvk not work with monitor using HDR10 LG ultragear

can solved this?

**Comment by K0bin** [comment]
I don't understand the problem here. Are you claiming that DXVK doesn't work with your monitor?!
That's impossible.

Or just that DXVK doesn't support HDR? If that's it, I'd like to remind you that Windows is not a supported platform for DXVK.

**Comment by Lennrj** [comment]
forgive my interpretation, the monitor is not the problem.

only dxvk doesn't work with hdr10 in games here

**Comment by K0bin** [comment]
HDR support on Windows isn't planned as Windows is not a supported platform for DXVK.
