### ISSUE TITLE
Is a Frame-Rate-Limiter possible with Vulkan?

### ISSUE THREAD

**Issue by jarrard** [doitsujin/dxvk#399]
I'm wanting to bring this up for discussion after having issues with limited the framerate of games like Warthunder and such without VSYNC because that can cause significant latency and frame pulsing effects which are undesirable.

Is DXVK or Vulkan for that matter capable of limiting framerate via some universal function, I have tried ENB as a limited but it doesn't seem to work in that manner under DXVK (fps still exceed set limit). So can we get this feature sometime as a variable to be set, such as DXVK_LIMIT_FPS = ###?

Do you have a idea on howto implement this? please do tell! 

PS. The old libstrangle works great for OPENGL but I doubt its code can be useful here.

**Comment by doitsujin** [comment]
DXVK could implement it in theory, but I'm rather reluctant to implement features which are not really part of the core API. There's no universal way to limit the frame rate in Vulkan applications.

For the same reason I have rejected pull requests adding system monitoring capabilities to the HUD - such features should ideally be implemented in a separate Vulkan layer that can be used with **all** applications, not just DXVK.

That said, there's a new-ish Vulkan extension for frame pacing that might be worth looking at, but for the time being i'll opt to "no".

**Comment by jarrard** [comment]
Frame pacing could help smooth out the ganeplay. The issue I see happening is if a game goes about my refresh rate the frames desync (no tearing) and it looks like a lower framerate experience at that stage. 

I use vsync where possible but it introduces lag which could be avoid if we can keep the frame rate below the refresh. Wish NVIDIA brought fast sync to linux.

**Comment by jarrard** [comment]
Frame syncing becomes very choppy after your display hz rate is reached. Basically you could have 200fps but with a 60hz screen it looks like 20-30fps.

**Comment by jarrard** [comment]
May not be a issue for AMD cards, also 144hz is pretty high so the problem is likely less prominent., Get a 60hz screen.

**Comment by xpander69** [comment]
im with nvidia and my second monitor is 60hz, not seen this issue there either, so i dunno.
Is this a DXVK thing only? as i have tested with Xonotic, CSGO and few other games where i can reach those insane high FPS numbers. With DXVK i haven't seen a game that runs so good except WoW which can get up to 190 FPS in places and didnt notice any problem there also. Haven't tried WoW on my 60hz monitor though

**Comment by jarrard** [comment]
No its certain games have bad frame syncing above refresh rates. A good example is Warthunder, I have had many different desktops to prove this to be the case. The problem doesn't really happen under Windows however so there is that. 

Either way a frame-rate limiter would reduce GPU temps without the added latency so there isn't just 1 reason to limit it in this way.

**Comment by jarrard** [comment]
This branch now works with vulkan apps now.

https://gitlab.com/torkel104/libstrangle/tree/test

**Comment by tingvarsson** [comment]
Not only the test branch but also master and latest release tag (0.0.4).

**Comment by pchome** [comment]
Created an [ebuild](https://github.com/pchome/dxvk-gentoo-overlay/tree/master/games-util/libstrangle), in case someone want it.

**Comment by jarrard** [comment]
> Not only the test branch but also master and latest release tag (0.0.4).


You will get the following error for certain hardware (possibly nvidia only issue?). Or certain software. 
IE. Warthunder would spit this error out with the 0.4/master build unless he has updated it already since yesterdays test build release.

**Strangle: Failed to get function vkGetInstanceProcAddr**

**Comment by pchome** [comment]
> Do you have a idea on howto implement this?

#### A rough but somehow working example
1. `git clone https://github.com/LunarG/VulkanTools`
2. `cd VulkanTools && for d in assistant_layer demo_layer starter_layer; do rm -r layer_factory/$d; done`
3. `mkdir -p layer_factory/fps_limit_layer`
4. `echo '#include "fps_limit.h"' > layer_factory/fps_limit_layer/interceptor_objects.h`
5. Create `layer_factory/fps_limit_layer/fps_limit.h` file and add following code:
```c++
#pragma once

#define ONE_BILLION 1000000000
typedef int64_t nanotime_t;

const char *env_var = "FPS";

class FPSLimit : public layer_factory {
  public:
    FPSLimit() {
      const char *frames_limit = getenv(env_var);
      if ( frames_limit ) {
        fprintf(stderr, "Vulkan FPS limit: %s fps\n", frames_limit);

        double tmp = strtod( frames_limit, NULL );
        if ( tmp )
          targetFrameTime = 1000000000.0 / tmp;
      }

      if ( targetFrameTime <= 0 )
        fprintf(stderr, "Vulkan FPS limit: disabled\n", frames_limit);
    };


    // TODO: implement
    void limiter() { }


    VkResult PostCallQueuePresentKHR(VkQueue queue, const VkPresentInfoKHR *pPresentInfo) {
      limiter();
      return VK_SUCCESS;
    }

  private:
    long targetFrameTime = 0;
};

FPSLimit fps_limit;
```
6. Copy/Paste `limiter()` code from [libstrangle](https://gitlab.com/torkel104/libstrangle/blob/5ddec2f0ba00fd38943aea4e7fc2399a11bca940/src/libstrangle.c#L110) (line 110-167, replace `void limiter() { }` stub).
  Replace `config.targetFrameTime` with `targetFrameTime`, remove `config.glfinish` part.
7. `mkdir -p build && cd build`
8. 
```
cmake \
-DBUILD_TESTS=OFF \
-DBUILD_LAYERSVT=OFF \
-DBUILD_VKTRACE=OFF \
-DBUILD_VIA=OFF \
-DBUILD_LAYERMGR=OFF \
-DBUILD_VKTRACE_REPLAY=OFF \
-DVULKAN_HEADERS_INSTALL_DIR=/usr \
-DVULKAN_LOADER_INSTALL_DIR=/usr \
-DVULKAN_VALIDATIONLAYERS_INSTALL_DIR=/usr \
..
```
9. `make && cd layers`
10. `FPS=25.5 DXVK_HUD=1 VK_LAYER_PATH=. VK_INSTANCE_LAYERS="VK_LAYER_LUNARG_fps_limit_layer" wine d3d11-triangle.exe`

**Comment by jarrard** [comment]
Nice,
However libstrangle has been updated for vulkan and works in my testing so far. But a built in solution would be handy.

**Comment by pchome** [comment]
> But a built in solution would be handy.

It's not a built in solution, it's Vulkan layer (created using [Vulkan Layer Factory](https://github.com/LunarG/VulkanTools/tree/master/layer_factory)).
Those steps will produce two files for you: `VkLayer_fps_limit_layer.json` and `libVkLayer_fps_limit_layer.so`

I decided to create one, because  `libstrangle` sometimes refuses to work for me, and disabled VSync leads to 500-1k fps in menus/maps/pause/etc. While `< 60fps` in game.

_P.S. What really would be handy -- if @doitsujin (or someone who speak vulkan) will create such layer (called e.g. `DXVK_helpers_layer`), and will move HUD, tweaks, limiter and other useful stuff there._

**Comment by pchome** [comment]
@pchome 
> P.S. What really would be handy -- if @doitsujin (or someone who speak vulkan) will create such layer ...

Well, I decided to do it by myself, for my own needs.
Here is the repo, which currently is the rough copy of `libstrangle` functionality as a Vulkan layer.
https://github.com/pchome/VkGHL

**Comment by jarrard** [comment]
@pchome talking to you mate.

Your code above and your website have issues. Above I get this.

> 
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> VkLayer_utils_LIBRARY
>     linked by target "VkLayer_fps_limit_layer" in directory /home/riddick/Downloads/VulkanTools/layer_factory
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/riddick/Downloads/VulkanTools/build/CMakeFiles/CMakeOutput.log".
> 


Looks to me you missed a step on both counts (pasted code steps and project page).

**Comment by infinitecurse** [comment]
I somehow ended up here. I think you can remove the wontfix label per https://github.com/doitsujin/dxvk/commit/30a1a29aa612c7a796d3cc1a4b320a24829ed286 commit.
