### ISSUE TITLE
Fallout: New Vegas through Mod Organizer not detecting graphics card

### ISSUE THREAD

**Issue by Castor215** [doitsujin/dxvk#3997]
Please describe your issue as accurately as possible.
When I start the Fallout Game Launcher through Mod Organizer, I can only select `llbmpipe (LLVM 17.0.6)` under Graphics Adapter. It used to detect my card but now it doesn't.

When I use Mod Organizer to start Skyrim (Anniversary Edition), it detects my card fine.

### Software information
Fallout: New Vegas (GOG edition) with Mod Organizer

### System information
- GTX 1050 Ti
- Driver: 535.161.08-2
- Wine version: wine-9.8 (Staging)
- DXVK version: 2.3.1

**Comment by Blisto91** [comment]
That usually means there an issue with the graphics driver. 32bit in this case i imagine.

**Comment by Castor215** [comment]
> That usually means there an issue with the graphics driver. 32bit in this case i imagine.

Installing `nvidia-driver-libs:i386` (I am on Debian) actually fixed the issue. Thank you.
