### ISSUE TITLE
Kingdom Come Deliverance crashing with DXVK injected in windows 10

### ISSUE THREAD

**Issue by pahan3000** [doitsujin/dxvk#4004]
Kingdom Come Deliverance stopped working with DXVK on my laptop  after i'd updated the driver. Rolling back to the previous driver didn't solve the issue. Dx9 based games still work fine with DXVK. So I think something is wrong with loading the dxgi.dll.

### System information
- GPU:GTX 1660ti
- Driver:552.44
- OS: Windows 10
- DXVK version: 2.3.1

 Log files:

[KingdomCome_d3d11.log](https://github.com/doitsujin/dxvk/files/15351552/KingdomCome_d3d11.log)
[KingdomCome_dxgi.log](https://github.com/doitsujin/dxvk/files/15351553/KingdomCome_dxgi.log)

**Comment by Blisto91** [comment]
gplasync isn't supported here. Please try with regular dxvk

**Comment by pahan3000** [comment]
[KingdomCome_d3d11.log](https://github.com/doitsujin/dxvk/files/15351552/KingdomCome_d3d11.log)
[KingdomCome_dxgi.log](https://github.com/doitsujin/dxvk/files/15351553/KingdomCome_dxgi.log)
Same thing

**Comment by Blisto91** [comment]
There are no errors in the logs. 
I would try to delete the dxvk cache file (in game folder) and maybe Nvidia Vulkan cache

**Comment by pahan3000** [comment]
Disabling Ansel did the trick. Thank you so much
