### ISSUE TITLE
PROTOTYPE ™ missing shadows and weak other graphical effects

### ISSUE THREAD

**Issue by Mrblubb** [doitsujin/dxvk#4008]
When using dxvk shadows, bloom and other graphical effects are missing/weakened/not rendered correctly

![Untitled-1](https://github.com/doitsujin/dxvk/assets/88938655/7c82c3e4-0c85-4537-a0df-bfca397b663d)
![Untitled-2](https://github.com/doitsujin/dxvk/assets/88938655/4917a0e8-0b7e-437b-9e35-de71541a9608)
![Untitled-3](https://github.com/doitsujin/dxvk/assets/88938655/95346009-da7f-41f9-b5b5-ff73f5dc22c2)
![Untitled-4](https://github.com/doitsujin/dxvk/assets/88938655/acb1d2f9-dba8-4ccb-86ab-1f74839764df)
![Untitled-5](https://github.com/doitsujin/dxvk/assets/88938655/2b0b51a1-d43c-468a-ab0c-7ed7ad5d5643)
![Untitled-6](https://github.com/doitsujin/dxvk/assets/88938655/eb88edc3-50b1-4378-9948-192da61b15e3)

### Software information
PROTOTYPE PC Max settings with emoose patch

### System information
- GPU: GTX 1060 6GB stock
- CPU: FX 8350 stock
- Driver: 546.17
- Windows: Win 10 x64 
- DXVK version: 2.3.1 

### Apitrace file(s)
https://we.tl/t-Bu8NKoCMzb

### Log files
[prototypef_d3d9.log](https://github.com/doitsujin/dxvk/files/15362704/prototypef_d3d9.log)

**Comment by K0bin** [comment]
This might just be a game bug:
https://www.pcgamingwiki.com/wiki/Prototype#No_shadows_with_AMD.2FATI_graphics_cards

**Comment by WinterSnowfall** [comment]
@Mrblubb Out of curiosity, does `dxgi.nvapiHack = False` do anything for the missing shadows?

**Comment by Mrblubb** [comment]
That happens on AMD cards and the fix provided in that makes shadows and some effects pixelated and not exactly accurate. With dxvk on nvidia it should render everything correctly

**Comment by K0bin** [comment]
![image](https://github.com/doitsujin/dxvk/assets/1131720/a085e734-a881-49de-9baf-d18cf3e10b13)

Works fine when replaying the apitrace.

**Comment by Mrblubb** [comment]
> @Mrblubb Out of curiosity, does `dxgi.nvapiHack = False` do anything for the missing shadows?

didn't tried it I'll try

**Comment by Mrblubb** [comment]
@K0bin that's good anyway it could render that way with only dxvk ?

**Comment by K0bin** [comment]
No, it's probably something that's baked into the apitrace.

**Comment by Mrblubb** [comment]
Oh ok. Just tried with dgvoodoo and everything is rendered correctly there. But performance is not so good as dxvk

**Comment by Blisto91** [comment]
Does it look correct if you create a file called `dxvk.conf` next to the games exe and insert `d3d9.supportDFFormats = False`

**Comment by Mrblubb** [comment]
> Does it look correct if you create a file called `dxvk.conf` next to the games exe and insert `d3d9.supportDFFormats = False`

I'll try.

**Comment by Blisto91** [comment]
Can you can get a couple of screenshots that better show the smoke difference between d3d9 and dxvk

**Comment by Mrblubb** [comment]
> Can you can get a couple of screenshots that better show the smoke difference between d3d9 and dxvk

Ok I'll make a good comparison.

**Comment by Mrblubb** [comment]
Alright, its hard to get perfect one to one comparison given the scene is dynamic every time. So the density and transparency depends on it. I tried and got a close shot though
![vlcsnap-2024-05-18-19h47m07s599](https://github.com/doitsujin/dxvk/assets/88938655/7065adc4-e450-458e-983d-303e86d72301)
![vlcsnap-2024-05-18-19h45m37s228](https://github.com/doitsujin/dxvk/assets/88938655/0a9b733c-717a-4a8b-b07a-32e68e469ae0)

**Comment by Mrblubb** [comment]
A video comparison. 


https://github.com/doitsujin/dxvk/assets/88938655/9381d681-af60-452c-894f-39c66038e8ba

D3d9

https://github.com/doitsujin/dxvk/assets/88938655/ae1e06a6-95cd-4b3a-8abd-a96bb42f8a64

**Comment by Blisto91** [comment]
I am not completely sure what i should look at as i am not sure i see a difference.
You could try to get a apitrace of just the smoke.

Or see if `d3d9.floatEmulation = Strict` makes a difference

**Comment by Mrblubb** [comment]
Ok I'll try it & yeah it's pretty hard to notice sometimes. Smoke actually flickers when using mouse or pop-in pop-out or doesn't fade correctly. Hopefully this will fix it.

**Comment by K0bin** [comment]
I honestly don't see problem in the DXVK video clip.

**Comment by WinterSnowfall** [comment]
@Mrblubb The shadows should work fine with Nvidia on latest master now, without having to mess with any config options. To fix this on AMD and potentially also Intel, we'd still need a config option for the game though. I'll leave that to @Blisto91, since he has the game.

**Comment by Mrblubb** [comment]
Wonderful! Thanks a million @WinterSnowfall @K0bin @Blisto91 & everyone in the team. The game is looking and performing better than ever. And yeah about the smoke quality I played some scenarios multiple times and it seems smoke pop-in with mouse moving is vanilla issue so its fine for now, if only I could find any other perceivable difference further. 
Cheers guys! 😁

**Comment by Blisto91** [comment]
Thank you for a well made issue report.

**Comment by Debbir94** [comment]
today 11/23/2024 its working on AMD 6700xt, now shows correctly.

> Does it look correct if you create a file called `dxvk.conf` next to the games exe and insert `d3d9.supportDFFormats = False`

today 11/23/2024 its working on AMD 6700xt, now shows correctly.
