### ISSUE TITLE
EVE online, parts of the UI missing

### ISSUE THREAD

**Issue by ForlornWongraven** [doitsujin/dxvk#401]
Parts of the 2d UI are missing with dxvk 0.53 and earlier. The 3d parts work flawlessly! This way EVE remains unplayable with dxvk as vital parts cannot be seen (but clicked).

EVE online current version, tested setting were max or min (aka potato mode)

### System information
- GPU: RX470
- Driver: AMD Radeon RX 470 Graphics (POLARIS10 / DRM 3.23.0 / 4.16.11-200.fc27.x86_64, LLVM 5.0.1), version: 4.5 Mesa 17.3.6 Direct Render: Yes
- Wine version: 3.8
- DXVK version: 0.53

### Log files
[exefile_d3d11.log](https://github.com/doitsujin/dxvk/files/2045700/exefile_d3d11.log)
[exefile_dxgi.log](https://github.com/doitsujin/dxvk/files/2045698/exefile_dxgi.log)

### Screenshots (I coloured private informations)
Wine 3.8 with dxvk:
![bildschirmfoto von 2018-05-28 18-23-21](https://user-images.githubusercontent.com/5302836/40623646-35226d14-62a8-11e8-993f-9f59c9978bca.png)

Game companies own wine wrapper with wine 2.10 and no dxvk:
![bildschirmfoto von 2018-05-28 18-26-45](https://user-images.githubusercontent.com/5302836/40623747-b7b8dc18-62a8-11e8-9efa-503de5b27c36.png)

**Comment by doitsujin** [comment]
Please update your drivers, Mesa 17.3 is not supported due to known issues with DXVK.

**Comment by ForlornWongraven** [comment]
Ok. You can for close this now as I am currently unable to update to Fedora28 which has Mesa 18. A project still requires me to run 27 for a cpl more weeks.

**Comment by doitsujin** [comment]
You could compile a Mesa version locally without affecting your system-wide install. Just set `VK_ICD_FILENAMES=/path/to/your/local/install/share/vulkan/icd.d/radeon_x86_64.json` to run the game with your own build.

**Comment by ForlornWongraven** [comment]
Project finished, updated to F28. DXVK works flawlessly so far! Thanks!

**Comment by doitsujin** [comment]
Nice, thanks for reporting back.
