### ISSUE TITLE
Question about NVIDIA shader cache

### ISSUE THREAD

**Issue by Tiagoquix** [doitsujin/dxvk#4014]
Hi there.

In version [2.0](https://github.com/doitsujin/dxvk/releases/tag/v2.0), the following was stated:

> On Nvidia drivers, the on-disk shader cache will be significantly larger than with previous versions of DXVK. It may be necessary to bypass the size limit by setting the environment variable `__GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1`, or setting a new limit manually via `__GL_SHADER_DISK_CACHE_SIZE` (in bytes).

In [NVIDIA Beta driver version 460](https://www.nvidia.com/download/driverResults.aspx/167671/en-us/), the default was changed from 128 MB to 1024 MB:

> Increased the default size for new OpenGL/Vulkan Shader Disk Cache location to 1024MB. Note that caches with paths containing "/.nv/ will continue to use the previous default of 128MB unless the size is manually overridden. For more information see the "OpenGL Shader Disk Cache" section in the "Specifying OpenGL Environment Variable Settings" chapter of the README.

Taking this into consideration, is it still necessary or recommended that NVIDIA users on Linux increase the cache size globally?

I primarily play games via Steam using Proton-GE.

I haven't had any problems with cache generation so far, but I would like to know if, somehow, DXVK's information about increasing the cache is still relevant to this day or if DXVK/Proton somehow already remedy this (for example, by setting the variable for specific games or creating a per-game cache folder isolated from the system, just like Lutris does).

To be clear, I'm not talking about Steam shader pre-caching. When it's turned off, it's the system that compiles the shaders, and that's what I'm talking about.

Considering that such information about increasing cache size is still relevant, and considering that nothing has been done on the DXVK/Proton side (I'm not saying nothing has been done; I'm just hypothesizing as I'm not sure), shouldn't then DXVK or Proton do something about it, since it seems like there isn't much cooperation, so far, from NVIDIA's side?

Thanks in advance for your attention.

**Comment by thanhdoan1201** [comment]
![image](https://github.com/doitsujin/dxvk/assets/109785213/360ad9d4-4a8b-477f-8fdb-4e767085b10d)
i always set unlimited cache folder  and i no care global settings

**Comment by doitsujin** [comment]
1GB is probably good enough for *most* games but there's still plenty of examples where it just isn't; I'd expect any modern D3D11 game with >20k shaders to run into issues. The nasty thing about GPL is that it essentially doubles the number of pipelines that need to be cached, and even if the driver *tries* to deduplicate things (not sure if it does) there will always be scenarios where doing so just isn't possible.

I'd also expect almost all recent D3D12 games to need significantly more storage than this, but for different reasons. Those just tend to ship significantly more and significantly bigger shaders than your average D3D11 one.
