### ISSUE TITLE
Everquest missing old textures

### ISSUE THREAD

**Issue by kai4785** [doitsujin/dxvk#4023]
When playing Everquest Live (ie: via Steam), some textures appear to fail to render, and models appear as white. Shadows seem to work so they appear ghostly. It appears that it's mostly with what appear to be the very oldest textures that have been in the game for 20+ years.
This has been reported in a few places on Reddit as well:
https://www.reddit.com/r/everquest/comments/199dhsy/texture_issues_with_dx11_update_linux_via_steam/
https://www.reddit.com/r/everquest/comments/1ahs9gc/weaponsshields_are_rendering_as_plain_white/
https://www.reddit.com/r/everquest/comments/1cwgqwz/old_models_on_linux/

You can replicate this by launching the Free to Play version of the game, disabling new character models, and choosing a server. The next screen is the character select, and your "old" models will be untextured and appear white.
![image](https://github.com/doitsujin/dxvk/assets/729693/a9ecea5b-57b6-4441-9d18-69de1026bc22)

The only time "failed" appears in Everquest logs are:
```
kai@overmind:~/.steam/steam/steamapps/common/Everquest F2P$ grep -i Failed Logs/*
Logs/dbg.txt:[Thu May 23 13:47:53 2024]00061:D3DXCreateEffectFromFile failed. (RenderEffects\SPL/SkinMeshCBS1_VSB.fxo)
Logs/dbg.txt:[Thu May 23 13:47:53 2024]00062:CEffect::CreateEffect [SPL/SkinMeshCBS1_VSB.fxo] failed.
Logs/dbg.txt:[Thu May 23 13:48:06 2024]00434:Failed to open Z:\home\kai\.steam\steam\steamapps\common\Everquest F2P\frg_chr.s3d.
Logs/dbg.txt:[Thu May 23 13:48:06 2024]00501:Failed to open Z:\home\kai\.steam\steam\steamapps\common\Everquest F2P\fro_chr.s3d.
Logs/dbg.txt:[Thu May 23 13:48:07 2024]00588:Failed to open Z:\home\kai\.steam\steam\steamapps\common\Everquest F2P\aam_chr.s3d.
```

My system:
Ubuntu 20.04
Steam
Proton 9.0-1
NVIDIA GeForce RTX 2060
Driver version 525.105.17

**Comment by Blisto91** [comment]
Hi there.
I am very certain that this is not a dxvk issue. It happens with wined3d too on Linux and not with dxvk on Windows.

**Comment by kai4785** [comment]
Oh good, I like certainty. Should I submit a WINE bug? Or maybe Proton?

**Comment by Blisto91** [comment]
A Wine bug would probably be best yea. I thought i had already made one actually but apparently not.

**Comment by doitsujin** [comment]
Based on the log, using native `d3dx11_43` might help (or some other d3dx library, would need the *full* wine log to be sure), but yeah, probably a wine problem.

**Comment by doitsujin** [comment]
Looking at a full wine log that @Blisto91 provided, it's more likely to be an issue with wine's wincodecs. There's some jank around BGRA8 -> R5G6B5 conversion that appears to be unsupported, which may explain why this only affects *some* textures but not all.

**Comment by Blisto91** [comment]
Yes we've found this to indeed be causes by Wines `WindowsCodecs.dll`

**Comment by kai4785** [comment]
Thanks! That makes it sound like we have hope. I looked at creating a winehq bug, but their page on "[When to submit a bug](https://wiki.winehq.org/Bugs)" suggests that they don't want my bug report from a Steam/Proton environment. I can submit a bug for Proton, if that's helpful. It looks like there's a [compatibility report](https://github.com/ValveSoftware/Proton/issues/1885) for a different issue, but not one for this issue.

**Comment by Czahrien** [comment]
After seeing the comment above by @Blisto91 I figured I could probably track this one down. I submitted a bug report with a small patch that fixes the issue for me over at https://bugs.winehq.org/show_bug.cgi?id=56755

**Comment by Czahrien** [comment]
A [commit](https://gitlab.winehq.org/wine/wine/-/commit/dcb5c97d02d58a0478e735eb7158c9bf3239791c) was made to the wine project yesterday to implement the bitmap conversion to fix this issue.

**Comment by Blisto91** [comment]
Commit has been picked for Proton Bleeding Edge. @Czahrien Thank you for the help!

**Comment by kai4785** [comment]
Verified fixed! Thanks so much
![image](https://github.com/doitsujin/dxvk/assets/729693/dbeb583b-73e6-4461-9e03-34479a45cf56)
