### ISSUE TITLE
Failure to create DxvkInstance running Elder Scrolls due to VK_KHR_surface not supported error

### ISSUE THREAD

**Issue by chadotter** [doitsujin/dxvk#403]
After clicking Play in the Elder Scrolls Online launcher the following error appears.

Your DirectX version is unsupported. Get Help:
 https://help.elderscrollsonline.com/app/answers/detail/a_id/32155

The dxgi log indicates that a dxvk instance isn't being created.

### Software information
Elder Scrolls Online through Steam.  Running under Ubuntu 18.04, but also had the same issue while running 17.10.
[vulkaninfo.txt](https://github.com/doitsujin/dxvk/files/2046237/vulkaninfo.txt)

### System information
- GPU: Nvidia GeForce 1050 Ti
- Driver: 396.24 (390.x had the same error)
- Wine version: 3.8 (also tried a number of earlier Wine releases)
- DXVK version: 0.53 (downloaded from releases page)

### Log files
- eso64_d3d11.log:
err:   D3D11CreateDevice: Failed to create a DXGI factory

- eso64_dxgi.log: 
err:   Required Vulkan extension VK_KHR_surface not supported
err:   Required Vulkan extension VK_KHR_win32_surface not supported
err:   DxvkInstance: Failed to create instance

Attached output from vulkaninfo.

**Comment by doitsujin** [comment]
Something's wrong with your Vulkan setup, not a DXVK bug. Please make sure that your wine version actually has Vulkan support.

**Comment by MeissnerEffect** [comment]
Try exporting 
`VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json`

**Comment by chadotter** [comment]
Any idea how to tell if my wine version has vulkan support?  I'm using 3.8 through PlayOnLinux.

**Comment by pchome** [comment]
@chadotter 
PlayOnLinux builds have no vulkan support.

**Comment by chadotter** [comment]
Thanks, I didn't realize that.  I'll close this issue.
