### ISSUE TITLE
Is DXVK_FRAME_RATE programmed to work with Direct3D 12 (vkd3d) games?

### ISSUE THREAD

**Issue by Tiagoquix** [doitsujin/dxvk#4032]
Hi there.

I would like to know if the env. variable `DXVK_FRAME_RATE` is programmed to work with Direct3D 12 (vkd3d) games.

If not, could you make it work with them?

Thanks in advance for your attention.

**Comment by K0bin** [comment]
`DXVK_FRAME_RATE` only works with DXVK, hence the DXVK in the name.
