### ISSUE TITLE
Ubisoft Connect launcher main window not working

### ISSUE THREAD

**Issue by Tiagoquix** [doitsujin/dxvk#4033]
Hello there.

Firstly, I'm not sure if this is the correct place to report this issue (maybe Proton is more adequate), but I imagine it is.

When I try to open the new Ubisoft Connect launcher (previously known as UPlay) on my PC, the system freezes for about 10 seconds and then forcibly returns to the login screen, resulting in a forced logout.

Strangely, the problem only occurs if I explicitly try to open the main launcher window (the launcher itself on the foreground). If the launcher operates in the background, it works normally.

Tested with Watch Dogs 1 via Steam, which requires the Ubisoft Connect launcher. Trying to open the main launcher window with protontricks results in freezing, while playing the game (the launcher staying in the background) works normally.

My reason for suspecting this here (DXVK) is the correct place to make the report is because there are several game launchers in [this file](https://github.com/doitsujin/dxvk/blob/master/src/util/config/config.cpp) that have the option `dxvk.maxChunkSize` set to `1` (for some reason I don't know).

I'm on Fedora Linux 40 KDE, X11, NVIDIA GeForce GTX 1050 Ti (proprietary driver), with the latest system updates applied.
Using Proton-GE 9.5.

I play Watch Dogs 1 with both overlays (Steam and Ubisoft) disabled to avoid issues (some users on ProtonDB stated there are issues with the game when playing with the overlays), but I don't know if this somehow is related to the launcher freezing.

**To test**
Either download a game which requires the Ubisoft Connect launcher (UPlay), and then try to launch the Ubisoft Connect launcher from the game installation folder, or [download the Ubisoft Connect installer](https://www.ubisoft.com/en-us/ubisoft-connect) and create a "Non-Steam Game" Proton prefix for it.

To run the launcher with protontricks, use the following command (using Watch Dogs 1, app ID 243470 as an example):
```
flatpak run --command=protontricks-launch com.github.Matoking.protontricks --appid 243470 "/mnt/HDD/SteamLibrary/steamapps/compatdata/243470/pfx/drive_c/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/UbisoftConnect.exe"
```

--------------------------------

Thanks in advance for your attention.

**Comment by doitsujin** [comment]
I don't know what the problem is I've never seen anything like this and can't reproduce it. Have you tried running uplay without dxvk?
