### ISSUE TITLE
EA Origin launcher question

### ISSUE THREAD

**Issue by Tiagoquix** [doitsujin/dxvk#4034]
Hi there.

As I stated in #4033, there are various Windows-only game launchers that have the option `dxvk.maxChunkSize` set to `1` for some reason I don't know.

Considering it's still possible to use Origin (the old app, now replaced by EA Desktop), should we set `dxvk.maxChunkSize` to `1` for it as well?

I personally use the Origin launcher when playing EA games because the new EA Desktop launcher has problems (stuttering in games, achievements not unlocking etc.), while the Origin launcher works fine and I can just delete a DLL file to entirely disable the in-game overlay.

Thanks in advance for your attention.

**Comment by K0bin** [comment]
The point of setting the chunkSize to 1 is to minimize VRAM fragmentation at the cost of performance for launcher apps, so it takes less VRAM away from the actual game.

I'd be fine with doing that for Origin too. You could open a PR.

**Comment by K0bin** [comment]
I think you generally overestimate the impact of that option.
