### ISSUE TITLE
Watch Dogs 1 doesn't respect minimized state

### ISSUE THREAD

**Issue by Tiagoquix** [doitsujin/dxvk#4039]
### Software information
Watch Dogs 1 (Steam version), High settings.
Game only supports DX11. (https://www.pcgamingwiki.com/wiki/Watch_Dogs#API)

Problem: mouse clicks seem to pass through windows and translate as inputs to the game even if the game is minimized. Easily reproducible. It's even possible to hear the game audio when the game thinks it is in the foreground again, when in reality it is minimized.

### System information
- GPU: NVIDIA GeForce GTX 1050 Ti
- Driver: 550.78 (proprietary driver)
- Wine version: the one included with GE-Proton 9.5 - https://github.com/ValveSoftware/wine/tree/cd0172ffb83cb7e92d8884117725ae4ef1bedfd8 / https://github.com/wine-staging/wine-staging/tree/cab93f47b8d095eb968bb3c7debf9117a91307ce
- DXVK version: the one included with GE-Proton 9.5 - https://github.com/doitsujin/dxvk/tree/6b76d70d9dc585b98f1e16ed0af2d93914549827 / https://github.com/jp7677/dxvk-nvapi/tree/b989684810bd6d1111b683d466c0d94178e6ec6a

### Apitrace file(s)
#4038

### Log files
Proton log: https://0.jaegers.net/?704347fe24125b32#AhQT22RipzKNESdgU6Da2iUmRGJoMuVrwG2DzmfatQfx

### Additional information
Game launch options: `PROTON_LOG=1 DXVK_FRAME_RATE=60 gamemoderun %command%`
I suspect this is a cross-platform issue, but I'm not sure.

**Comment by Blisto91** [comment]
Do you know if it behaves this same way with wined3d?

**Comment by Blisto91** [comment]
Add `PROTON_USE_WINED3D=1` to your launch options

**Comment by mbriar** [comment]
I doubt apitrace will be useful here. Probably unrelated to D3D and rather some window management bug in wine. Or even some desktop compositor or xwayland problem.

**Comment by K0bin** [comment]
If the same issue happens with WineD3D as well, it is indeed probably not our bug like mbriar says.

**Comment by mbriar** [comment]
Doesn't really sound like a game bug to me, I doubt this happens on windows. But I also don't think it's a DXVK bug.
