### ISSUE TITLE
Issue with Ghostbusters: The Video Game Remastered

### ISSUE THREAD

**Issue by KeyofBlueS** [doitsujin/dxvk#4045]
Dear dxvk developers,

Hi! after reporting an issue on Valve's Proton github about a problem I'm experiencing with Ghostbusters: The Video Game Remastered on Proton, I was redirected to this repo, so I'm reporting it here as well:

When running the game with Proton versions 8 and 9, there are severe and unpleasant artifacts on the characters' face, neck, and chest.

In that report on Valve's Proton, someone mentioned using Proton 5.13, so I decided to give it a try. While my controller isn't correctly detected and the performance is significantly worse compared to the latest Proton versions, **the artifacts are not present in 5.13**. This indicates a serious **regression in the newer Proton versions**.

Further tests reveals that even Proton 6.3-8 and 7.0-6 are affected, so Proton 5.13-6 is the last version unaffected by this issue.

I've attached a video that demonstrates these artifacts, along with logs from Proton 5.13-6 and 9.0-1.

Furthermore, the game won't play high-quality MP4 videos, defaulting instead to lower-resolution OGV videos. Is it truly impossible to fix this issue also?

I hope someone can investigate this problem and looking forward to hearing from you soon.

Thank you and best regards!

### Software information
Ghostbusters: The Video Game Remastered

### System information
- GPU: nvidia GTX970
- Driver:  535.161.08
- Proton version: 6.3-8; 7.0-6; 8.0-5; 9.0-1
- DXVK version: The one included within Proton I guess? sorry I don't know how to check

### Apitrace file(s)
- [Link](https://www.dropbox.com/scl/fi/8898he5mw1wenrhugiyf9/ghost.trace.7z?rlkey=2mh3nq3zyhtzcq2gdz5ct60xt&st=8u2v8lq0&dl=0)

### Log files

https://github.com/ValveSoftware/Proton/assets/45725677/8b03a8a9-ced2-491d-8ea5-1489dacda1c7

[steam-1449280_proton-5.13-6.log](https://github.com/user-attachments/files/15519109/steam-1449280_proton-5.13-6.log)

[steam-1449280_proton-9.0-1.log](https://github.com/user-attachments/files/15519113/steam-1449280_proton-9.0-1.log)

**Comment by Blisto91** [comment]
Hi there and thank you for the well made issue. The PR above should work around the problem

**Comment by KeyofBlueS** [comment]
Hi, thank you for your quick reply!

I tried your patch, but unfortunately, the flickering is still there.

I've never compiled and installed DXVK before, so I might have made a mistake, but I don’t think so. Here’s what I did following the DXVK readme:

-     Cloned the DXVK repo
-     Edited the file ./src/util/config/config.cpp as per your PR
-     Compiled
-     Installed the DLLs in the game prefix
-     Added DLL overrides with Protontricks
-     Started the game

**Comment by mbriar** [comment]
Installing the dlls to the prefix doesn't work with proton because they will be overridden again on every launch by the proton launch script. You need to replace the dlls in the proton distribution or put them next to the game's .exe. There's no need to add dll overrides because those are done by default anyways.

**Comment by KeyofBlueS** [comment]
I didn't know that, thanks for the clarification!

I tried placing the DLLs next to the game's .exe, but that didn't work for some reason.

However, I managed to get it working by setting the DXVK_CONFIG_FILE=/xxx/dxvk.conf environment variable in Steam. This points to the dxvk.conf file where, as in the PR, I added `d3d11.longMad = True`!

**Comment by mbriar** [comment]
> I tried placing the DLLs next to the game's .exe, but that didn't work for some reason.

probably didn't work because it's an Unreal Engine game and the real exe is in `Whatever/Binaries/Win64/Whatever-Shipping.exe`

**Comment by KeyofBlueS** [comment]
No it's not. It's on Infernal Engine, and there is only one exe in the game.
