### ISSUE TITLE
Generic EXE names in util/config/config.cpp

### ISSUE THREAD

**Issue by Tiagoquix** [doitsujin/dxvk#4048]
Hi there.

The file https://github.com/doitsujin/dxvk/blob/master/src/util/config/config.cpp has generic EXE names, which makes me think that we should use more folder-based paths to apply fixes. As far as I understand it, DXVK can also be used to run normal apps (and not only games), so generic names (generally short names) *may* cause conflict for some apps (or, even, for non-related games) due to the fact that the fixes are applied globally to a specific EXE name.

**Some examples below.**

--------------------------------------

https://github.com/doitsujin/dxvk/blob/c2fd91f835741d7f38a1b7af8b982935dfbad241/src/util/config/config.cpp#L20-L23

https://github.com/doitsujin/dxvk/blob/c2fd91f835741d7f38a1b7af8b982935dfbad241/src/util/config/config.cpp#L130-L133

https://github.com/doitsujin/dxvk/blob/c2fd91f835741d7f38a1b7af8b982935dfbad241/src/util/config/config.cpp#L170-L173

https://github.com/doitsujin/dxvk/blob/c2fd91f835741d7f38a1b7af8b982935dfbad241/src/util/config/config.cpp#L190-L193

https://github.com/doitsujin/dxvk/blob/c2fd91f835741d7f38a1b7af8b982935dfbad241/src/util/config/config.cpp#L238-L242

https://github.com/doitsujin/dxvk/blob/c2fd91f835741d7f38a1b7af8b982935dfbad241/src/util/config/config.cpp#L262-L269

--------------------------------------

And many others.

As much as, until then, I have not seen any report because of the generic EXE names, I still think we should remedy them and avoid them as much as possible.

Thank you for your attention.

**Comment by Blisto91** [comment]
We would have to be careful though so as not to regress anything. 
There is a small chance that if a game is available on different stores it might have different folder name or structure. Or if a game have a old retail version that have changed those with time through updates or when added to a digital store later. Though this is probably pretty uncommon.

Adding a folder would also mean the config wouldn't apply to a game if a user or modder decided to change the name of the game folder. If that is even something we want to take in to consideration

**Comment by doitsujin** [comment]
Which of these exe names are used in more than one game?
