### ISSUE TITLE
Possible combination of options in dxvk.conf

### ISSUE THREAD

**Issue by Tiagoquix** [doitsujin/dxvk#4049]
Hello there.

In the file https://github.com/doitsujin/dxvk/blob/master/dxvk.conf, there are some "duplicate" options for Direct3D 9 (`d3d9`) and Direct3D 10+ (`dxgi`).

Examples:

https://github.com/doitsujin/dxvk/blob/c2fd91f835741d7f38a1b7af8b982935dfbad241/dxvk.conf#L34-L41

https://github.com/doitsujin/dxvk/blob/c2fd91f835741d7f38a1b7af8b982935dfbad241/dxvk.conf#L44-L53

Forgive my ignorance here, but as I understand it, it seems there is no real utility for keeping them separate.

So I ask: wouldn't it be more simpler (and even somewhat more useful) to have a unique option?

Example: instead of having `dxgi.maxFrameRate` and `d3d9.maxFrameRate`, we could only have `dxvk.maxFrameRate`, with the same logic. Then, the user chooses the desired value and DXVK does the work of knowing if the game is D3D9/10/11. Same logic would apply to other options.

Is there a reason for this combination not to exist?

Thanks in advance for your attention.

**Comment by doitsujin** [comment]
It has been considered, but it also breaks existing configurations, and in some cases, games that support both APIs only require options for one but not the other.

**Comment by lextra2** [comment]
And what about keeping the old, but adding a new, shorter option?

Example: `dxgi.maxFrameRate` & `d3d9.maxFrameRate` gets a third variable, `maxFrameRate` (effectively adjusting both, dxgi and dx9)

Would be less clutter for users with a custom config
Another positive is, the user doesn't have to figure out first, what directX version the game uses.

**Comment by doitsujin** [comment]
> That's weird. In this case, couldn't DXVK figure out what's the best option to apply (d3d9 or dxgi) and then proceed from there?

What I mean is something like the D3D9 version of a game requiring a vendor override but not the D3D11 one (or vice versa).

**Comment by Blisto91** [comment]
fwiw there is already a unified frame rate option via the environment variable `DXVK_FRAME_RATE`.
For the most part it is not expected that most users should mess with the config options. They are mostly there for debug purposes or working around issues.
