### ISSUE TITLE
[d3d9, regression] Myst V freeze/crash upon resolution change

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#4052]
When attempting to change resolution in Myst V the game will error "initializing your video card" and then freeze until you restart the game
Bisected to start with either 52ac271acba015ddc9bf35604656615f228a67bb, 8f740c53b4be564e1a8857f1e09e41e31dd7a681 or b8d36eeaccdbe1196a0183c8d2bbeb9e9d463e6f. Two commits had to be skipped since the game wouldn't start with them.

`d3d9.countLosableResources = False` works around the issue.

### Software information
Myst V

### System information
- GPU: RX 7900 xtx
- Driver: mesa main
- Wine version: Proton Bleeding Edge

### Apitrace file(s)
https://drive.proton.me/urls/Y3Y418SP34#esWLnSJGvH9E

### Log files
[steam-208110.log](https://github.com/user-attachments/files/15533888/steam-208110.log)

**Comment by K0bin** [comment]
This looks like a game bug. Replaying the apitrace with native D3D9 fails the reset call just like DXVK does.

**Comment by Blisto91** [comment]
Checking the game on Windows it doesn't crash natively, but it does still crash with dxvk there. It seems like apitrace itself might not like the event where it switches resolution as even a native captured trace will crash in that spot when replayed on Windows

**Comment by K0bin** [comment]
An apitrace made with the Nvidia D3D9 driver on Windows also fails when replaying it with the very same Nvidia D3D9 driver on Windows. Same issue as DXVK. So I guess we should just disable the losable counting for the game...

**Comment by Blisto91** [comment]
Worked around via https://github.com/doitsujin/dxvk/pull/4051
