### ISSUE TITLE
SHADE : Wrath of Angels - Freeze on Loading Screens

### ISSUE THREAD

**Issue by Mrblubb** [doitsujin/dxvk#4057]
With dxvk "Shade wrath of angels" launches fine but when trying to load into game, freezes completely in the loading screens 

![vlcsnap-2024-06-06-19h37m55s334](https://github.com/doitsujin/dxvk/assets/88938655/a5c21626-8436-42e4-a97e-399478c4fd36)
![vlcsnap-2024-06-06-19h38m01s608](https://github.com/doitsujin/dxvk/assets/88938655/c3297346-b7fd-4b88-a9ed-164bc6dd5fa3)

### Software information
Shade wrath of angels PC Max settings with dsoal eax enabled

### System information
- GPU: GTX 1060 6GB stock
- CPU: FX 8350 stock
- Driver: 555.85
- Windows: Win 10 x64
- DXVK version: 2.3.1

### Apitrace file(s)
https://we.tl/t-fo0rx5zQXD

### Log files
[SHADE_d3d9.log](https://github.com/user-attachments/files/15635466/SHADE_d3d9.log)

**Comment by Blisto91** [comment]
@mrdeathjr28 thanks for checking. Might be better to test with 2.3.1 to make sure

**Comment by Mrblubb** [comment]
@mrdeathjr28 Just checked with the older version and it still freezes on windows. I think the issue is something with parsing shaders during loading assets.

**Comment by dnblank123** [comment]
Works fine on my setup, maybe it's area specific?
- GPU: 1050 Ti
- Windows 10

**Comment by Mrblubb** [comment]
@dnblank123 That's nice. Which version do you have 1.1 or 1.2 ?

**Comment by dnblank123** [comment]
@Mrblubb 1.01

**Comment by Mrblubb** [comment]
Re-installed game without the update and @dnblank123 is right. Game works with dxvk. It's just with the update 1.2 the game freezes on loading.

**Comment by Blisto91** [comment]
Got my hands on the game now.
Is it even on a new game loading screen? I haven't immediately hit the issue so far with version 1.2 of the game on my RX 7900 XTX

**Comment by Mrblubb** [comment]
@Blisto91 Great news! But for me for some weird reason, even a newly installed game just freezes mid loading. I tried many times. Doesn't happen with 1.01 whatsoever. Could it be that I'm using cracked version that's why ?

**Comment by Blisto91** [comment]
Don't know. But we can't provide support for the pirated version at least (i assume that is what you meant)

**Comment by Mrblubb** [comment]
I completely understand. Also game doesn't have any issues with dx9 so no worries :)

**Comment by Blisto91** [comment]
Played for a while on my RTX 4080 now too but haven't hit any issues

**Comment by Mrblubb** [comment]
Great! I assume its entirely a crack issue then not dxvk. You can safely close this issue report as fixed.
