### ISSUE TITLE
[d3d9] Alan Wake (2010) crashes after getting past the menu

### ISSUE THREAD

**Issue by ldinino** [doitsujin/dxvk#4058]
Please describe your issue as accurately as possible.
When launching the game, it initially will get you to the main menu. As soon as the game begins and starts rendering, it hangs indefinitely.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Name of the game, settings used etc.

### System information
- GPU: Intel Arc (Core Ultra 7 155H)
- Driver: 31.0.101.5522 (latest)
- Wine version: na
- DXVK version: 2.3.1

### Apitrace file(s)
- Put a link here
API trace was too big, could not get it to capture the crash with dxvk.

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
[AlanWake_d3d9.log](https://github.com/user-attachments/files/15651576/AlanWake_d3d9.log)
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

**Comment by Blisto91** [comment]
Assuming you have already read https://github.com/doitsujin/dxvk/wiki/Windows this is likely just a driver issue. On Linux with my AMD GPU i don't have any issues in the game even if i spoof a Intel GPU. I can also see on ProtonDB that at least one Intel Arc user have played it in the past.
