### ISSUE TITLE
Don`t work - dxvk.deviceFilter with 2 gpu windows and linux

### ISSUE THREAD

**Issue by LordOri** [doitsujin/dxvk#4060]
### Software information
OS Win10 and Linux Mint in general with any game

### System information
- GPU1:GTX 960 2Gb Black Edition 
- Driver: In DxDiag.txt

- GPU2:MSI Radeon RX 470 4Gb
- Driver: In DxDiag.txt

- DXVK version: 2.3.1

[DxDiag.txt](https://github.com/user-attachments/files/15675826/DxDiag.txt)

The essence of the problem is that the filter for video cards does not work, without dxvk my ​​RX470 always works without exception, and when using dxvk it selects the GTX 960, in the dxvk.conf configuration file in the uncommented dxvk.deviceFilter parameter I specify the name of the video card differently, but in any case it does not filter out unnecessary GTX 960, the name was indicated exactly as in devinfo

**Comment by LordOri** [comment]
and which version supports it?

**Comment by Blisto91** [comment]
Current master https://github.com/doitsujin/dxvk/actions/runs/9404927528

**Comment by LordOri** [comment]
Everything worked, thank you very much! Do you know when this filter will be introduced into the stable version?

**Comment by Blisto91** [comment]
It will be in the next release, but don't have a specific date.

**Comment by LordOri** [comment]
Thanks for the answer, I would also like to know a little about whether functions will be added to the file type configuration
- monitor source selection
-forced selection of application permission

That's all, once again very grateful and good luck with the project!

**Comment by Blisto91** [comment]
> forced selection of application permission

What do you mean by this. Administrator mode?

**Comment by LordOri** [comment]
Sorry, I expressed it poorly through the translator, I meant forced window size like 720p, 1080p, 2K

**Comment by K0bin** [comment]
There are no plans to add that. Try using Gamescope.
