### ISSUE TITLE
StarCraft 2 lighting on the Void Thrashing mission

### ISSUE THREAD

**Issue by WapMap** [doitsujin/dxvk#4063]
OS: Windows 10 Pro (22H2)
GPU: RX 6600 XT
Driver: 24.5.1
DXVK version: 2.3.1
Graphics settings in game: maximum
Original API: DirectX 9 (64 bit)

The lighting feels like it's being cut off by a square, at the top left of the screen. Maybe this bug is on other missions too.

Screenshot of bug:
![0](https://github.com/doitsujin/dxvk/assets/99033824/717b0778-612e-47d8-8f35-9d9f2fad8e87)

**Comment by Blisto91** [comment]
Hi there. If able then please make an apitrace. Will make it easier to look in to

**Comment by WapMap** [comment]
> Hi there. If able then please make an apitrace. Will potentially make it easier to look in to

Unfortunately I have no idea how to do it.

**Comment by Blisto91** [comment]
https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

**Comment by WapMap** [comment]
Here's my apitrace: https://drive.google.com/file/d/1ktPFF8LxPbr63tK_Kwr9Qfm_prpIvZ4R/view?usp=sharing

**Comment by Blisto91** [comment]
Thank you.
I also got to poke at it a bit in game in the mean time and it seems like it is likely a AMD driver issue. I can reproduce with AMD's Linux driver but not with radv (not AMDs own driver) and it also doesn't reproduce on Nvidia.

I have gone ahead and made a issue for their open source Linux driver https://github.com/GPUOpen-Drivers/AMDVLK/issues/366
A fix there will likely carry over to the Windows driver also.
