### ISSUE TITLE
Incorrect primary team color for non-standard clothing in Team Fortress 2

### ISSUE THREAD

**Issue by WapMap** [doitsujin/dxvk#4067]
- OS: Windows 10 Pro (22H2, 19045.4474)
- GPU: RX 6600 XT
- Driver: 24.5.1
- DXVK version: most likely 2.3.1 or 2.3 (Don't know exactly what version is used in the official version of Team Fortress 2)
- Original API: DirectX 9

As I know Team Fortress 2 uses DXVK for Vulkan, so I decided to report this visual bug here.

Screenshot of bug:
![image](https://github.com/doitsujin/dxvk/assets/99033824/edcb3b3a-0d8f-480c-8c24-3a7910b60e73)

In this case, the coloring of the hat, glasses, and pants is not correct.

**Comment by Blisto91** [comment]
Hi there. 
Is this only with specific outfits? If so would you be able to make a apitrace?

**Comment by WapMap** [comment]
For some reason apitrace doesn't want to record in inventory, main menu, gear, etc things.

**Comment by Blisto91** [comment]
No problem. I will try to poke at the game locally.

**Comment by WapMap** [comment]
And yes, so far it's only noticeable with non-standard clothing.

**Comment by Blisto91** [comment]
I have not been able to reproduce this so far in either Linux or Windows with the same hat

**Comment by WapMap** [comment]
Did you use the DLL from Github or the command to run -vulkan in General?

**Comment by Blisto91** [comment]
The latter

**Comment by WapMap** [comment]
Then I guess it's a bug on my end. Thanks for your time.

**Comment by Blisto91** [comment]
No need to close it yet. I will poke some more later.

**Comment by WapMap** [comment]
By the way, I was wondering if these commands have some effect on this? Commands: **r_threaded_particles 1**; **r_threaded_renderables 1**; **snd_mix_async 1** and **mat_queue_mode 2**. I usually enter them through the console in the main menu. They are related to graphics.

**Comment by WapMap** [comment]
> @WapMap Are you using an outdated FPS configuration? It may have an effect on the cosmetics. I have played TF2 on Linux for quite some time now and have not seen any visual bug like that. Also, make sure you are using the DXVK version and not the Legacy OpenGL version of the game.
> 
> About the ConVars and launch option you mentioned, have a look at https://docs.comfig.app/latest/tf2/misconceptions/ (https://github.com/mastercomfig/mastercomfig). Quoting the page here and some observations of mine:
> 
>     * `r_threaded_particles 1`: is the default value.
> 
>     * `r_threaded_renderables 1`: not used by the game. Keep it at `0` (the default value).
> 
>     * `snd_mix_async 1`: is related to the sound system, but only works for the Xbox 360. Keep it at `0` (the default value).
> 
>     * `mat_queue_mode 2`: AFAIK, forces the multi-threaded system. This is not necessary; the default value, `mat_queue_mode -1`, will automatically determine the best threading mode for your system.
> 
>     * `-threads` launch option: the Source Engine automatically determines the value for this, and caps it at `3`, due to performance issues with higher values. Valve also [recommends](https://www.reddit.com/r/GlobalOffensive/comments/5y8r7v/in_depth_discussion_of_the_threads_launch_option/dep5yno/) removing this launch option.
> 
> 
> I would say the visual bug you are seeing is probably related to a FPS. config, a launch option or a mod. Please test TF2 in a [clean state](https://docs.comfig.app/latest/setup/clean_up/) and see if the issue persists. (Make a backup of your `tf/cfg` and `tf/custom` folders. Your video options may be reset after testing, so remember to reapply them.)

Nah, nothing changed after a complete reset and running in “standard” mode, the bug still remains. I wrote in the beginning that I ran it on Windows and it works on it through DirectX 9.

**Comment by Blisto91** [comment]
`%command%` isn't a thing on Windows

**Comment by WapMap** [comment]
The bug persists regardless of my actions, whether I'm sitting in the main menu or playing a round, it stays the same.

**Comment by WapMap** [comment]
The only coloring on the hat was green. There's nothing else painted.

**Comment by WapMap** [comment]
> Default paints:
> 
> ![image](https://private-user-images.githubusercontent.com/30274161/338957636-fba716b2-cff9-4a94-bb7c-d0fa2cf5a69c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTQ2MzcsIm5iZiI6MTcxODE5NDMzNywicGF0aCI6Ii8zMDI3NDE2MS8zMzg5NTc2MzYtZmJhNzE2YjItY2ZmOS00YTk0LWJiN2MtZDBmYTJjZjVhNjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDEyMTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyOTUxZmRiNTk2OWIyMTJkZjAyZWJmNzYwODIzN2IwNDJjZWY1MzIzOWUzYmU4NDExODU4ZWZjYzZmOTAyYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IdiHmPO4urZcUxLvFSfxUv55goAASUN_0KbGd98gcYA)
> 
> Light green paint on hat:
> 
> ![image](https://private-user-images.githubusercontent.com/30274161/338957875-b830de55-0b37-4581-af6a-b7ca276ab88d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTQ2MzcsIm5iZiI6MTcxODE5NDMzNywicGF0aCI6Ii8zMDI3NDE2MS8zMzg5NTc4NzUtYjgzMGRlNTUtMGIzNy00NTgxLWFmNmEtYjdjYTI3NmFiODhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDEyMTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZDA0NWYyMmNkNWQ2NGM0OTZjZDg0NjY2YmE4MWExYjI5OWZkNmI5M2JmODlhOWVkMzI1YTM2ZWVmMGM0ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oyM7sRkfEv_DSiN7wHQ1A8llmCZtnhdhapL56P7L8t8)
> 
> Lime green paint on hat:
> 
> ![image](https://private-user-images.githubusercontent.com/30274161/338958112-330dc28c-4e64-44c8-9c53-a7cc146863a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTQ2MzcsIm5iZiI6MTcxODE5NDMzNywicGF0aCI6Ii8zMDI3NDE2MS8zMzg5NTgxMTItMzMwZGMyOGMtNGU2NC00NGM4LTljNTMtYTdjYzE0Njg2M2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDEyMTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZjZiMDdhOTkxZTFkMDBlMDg2Mzk0NGY3YzIxMjk2NzdmNzkzMDc0NTk5NGE5NTY5YzA1ZjNiYTZmYjBjNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GANvOrGRPkWAJ6A-Oh-Hyz-c_4mFphrdVVK3o9WAqPI)
> 
> Still unable to reproduce on Linux.

Here's what it looks like in the original. I don't use any graphics presets, just the console commands listed above and the graphics settings in the game itself.
![image](https://github.com/doitsujin/dxvk/assets/99033824/92fc14e3-9b1d-4064-a7ac-1cc9b2d098ce)

**Comment by WapMap** [comment]
The problem turned out to be on AMD's side, in the 6000 series. You can see it in the comments: https://steamcommunity.com/sharedfiles/filedetails/?id=3228732058

**Comment by K0bin** [comment]
So am I understanding this correctly:

It renders correctly with DXVK on both Nvidia and AMD Linux (RADV)?

**Comment by WapMap** [comment]
As I understand it renders normally everywhere except 6000 series with standard AMD drivers, I haven't checked with other drivers. I found this out from the tests here and a lot of comments on the link above.

**Comment by WapMap** [comment]
Recently driver 24.6.1 was released, after installing it, the bug was fixed. I will test it more and then close this issue. Unless, of course, something new comes along.
