### ISSUE TITLE
Question about frame rate option rework

### ISSUE THREAD

**Issue by Tiagoquix** [doitsujin/dxvk#4069]
Hi there.

Thanks for listening to my suggestion to consolidate both max. frame rate options!

I have a question about this rework:

https://github.com/doitsujin/dxvk/blob/018db92342769fa847d356e5f578c43c89b46a18/dxvk.conf#L46-L51

What exactly does it mean when it says "`if the actual display mode does not match the game's one.`"?

Thanks in advance for your attention.

**Comment by Blisto91** [comment]
Some games rely on vsync to cap their framerate and will try to set the refresh rate accordingly to e.g 60. In some environments like Linux Wayland or Wine fshack it is not possible for the game to change the display mode. That means if my display have a refresh of 120hz that will be the games cap instead in the intended 60.
The work will attempt to detect such a scenario where the game reports a refresh rate but the games fps is running well above that and then enabled a fps limit to that game chosen refresh rate
