### ISSUE TITLE
Sleeping Dogs Definitive Edition crashes when loading new game

### ISSUE THREAD

**Issue by AccountOneOff** [doitsujin/dxvk#407]
The game boots to menu but crashes almost immediately upon starting a new game or running the benchmark. 

### Software information
Sleeping Dogs Definitive Edition
Medium preset and lowest

### System information
- GPU: GTX 960
- Driver: 396.24.0
- Wine version: [Patched](https://github.com/lutris/buildbot/blob/master/runners/wine/patches/strider.patch) Wine 3.8 
- DXVK version:  3b70e23

### Apitrace file(s)
- https://drive.google.com/open?id=1M4wOl8sJnlo3niYSkcLOIO8975j5FIzW

### Log files

- [sdhdship_d3d11.log](https://github.com/doitsujin/dxvk/files/2052537/sdhdship_d3d11.log)
- [sdhdship_dxgi.log](https://github.com/doitsujin/dxvk/files/2052538/sdhdship_dxgi.log)

**Comment by doitsujin** [comment]
Thanks for providing the trace, fc8573891e1532489c7ed98825af200c1060f3a9 should fix the issue. Please let me know if there are still issues.

**Comment by pchome** [comment]
@doitsujin 
> Please let me know if there are still issues.

Randomly crashing, no errors in logs and dumps, I spent entire hour with validation layers enabled (~5fps) and had no luck to catch it. Now with the second try I finally caught it, but this is the only information I have. Hope it will be helpful.

[vulkanlog.txt](https://github.com/doitsujin/dxvk/files/2065034/vulkanlog.txt)

**Comment by doitsujin** [comment]
@pchome that issue is unrelated. Seems like something's wrong with queries, but i'm unable to reproduce it with the apitrace and I have no idea why this might happen.

**Comment by romrompanpan** [comment]
@doitsujin how to fix that problem with that vertex attribute

**Comment by Raxxyr** [comment]
i got the same problem, how to fix?

**Comment by K0bin** [comment]
Please open a new issue. Whatever was the problem here was fixed almost 4 years ago.
