### ISSUE TITLE
Gears of War (2007 - GFWL)

### ISSUE THREAD

**Issue by RSNTM3NT** [doitsujin/dxvk#4073]
This game is basically the old/abandonware versions. And since I need to play this with a "cr4ck3d" executables, I get this message:

Error:
"d3d9.dll: You cannot run the game with modified executable code. Please reinstall the game"

I'm currently testing DXVK on abandoned/older versions game for research purpose. Maybe it's sketchy reasons behind it, but does it matter? Other abandoned games works fine (DiRT 2, Old GTA Trilogy, Old Halo 1-2 with Chimera and Project Cartographer and old Burnout Paradise, because the remaster doesn't support Steam Deck).

Also found DXVK much better on delisted titles like DiRT 3, GRID 1 & 2, etc).

**Comment by doitsujin** [comment]
The game is known to have a check to prevent you from modding the game or otherwise replacing DLLs. This is just working as intended.

Also, please understand that we cannot support games which are no longer obtainable through legal methods.

**Comment by matcarfer** [comment]
1. Patch the game with latest official TU3.
2. Apply corresponding crack.
3. Apply xliveless as shown in https://www.pcgamingwiki.com/wiki/Gears_of_War
4. Copy 32bit files to Binaries folder.
5. Enjoy Gears of War. Also, tested DXVK-GPLASYNC and had still better 0.1% Lows. And no problems with fullscreen or borderless. Also limit game to 60fps. Can also do Frame Gen with Lossless scaling to 120fps easily.
