### ISSUE TITLE
DXVK v2.0-26 not works for Death Stranding Director's Cut on Proton

### ISSUE THREAD

**Issue by AlvaroDavi5** [doitsujin/dxvk#4078]
When I starts Death Stranding Director's Cut from my Steam client on Ubuntu, the screen became black with glitchs and then the game crash without log error. The only logs that I received using another DXVK versions is: `An Access Violation (C0000005h) has occurred in thread 'Main' at instruction location 00000001419A4004h`.
But the DS Standart Edition works on Heroic Games Launcer with Wine-GE-Proton8-26 and the DS Director's Cut works perfectly on Windows 11 (I had dual boot).

### Software information
**Game:** Death Stranding Director's Cut
Tested resolutions: 1600x900 and 1280x720
Steam game lauch options: `gamemoderun mangohud PROTON_USE_D12VK=1 %command%` (also tested without launch options)

### System information
- OS: Ubuntu 20.04 LTS x64
- GPU: AMD ATI Radeon Vega 8 Picasso
- CPU: AMD Ryzen 5
- Driver: amdgpu
- Wine version: tested with Proton Experimental, Proton 9.0-2, Proton 7.0-6, Proton GE 7-42 and Proton GE 9-7
- DXVK version: D12VK

### Error occurrence print
![Screenshot from 2024-06-14 11-51-55](https://github.com/doitsujin/dxvk/assets/52904236/ae4f45f9-a094-4119-a3fc-66a747857259)

### Log files
[steam-1850570.log](https://github.com/user-attachments/files/15861471/steam-1850570.log)

**Comment by K0bin** [comment]
> DXVK version: D12VK

That's not DXVK but VKD3D-Proton. Please open your issue there.

> info:    Driver: 21.2.6

Try a more recent driver. LTS distros are really poor choices for playing cutting edge video games.
