### ISSUE TITLE
C&c generals zhor bug on dxvk+d8vk

### ISSUE THREAD

**Issue by Azedin1111** [doitsujin/dxvk#4087]
![Screenshot_2024-06-23-15-05-41-373_com ludashi benchmark](https://github.com/doitsujin/dxvk/assets/114381457/5702a86c-084b-47c5-8ef4-b797c616e527)
On turnip android

**Comment by Azedin1111** [comment]
![Screenshot_2024-06-24-00-33-47-053_com ludashi benchmark](https://github.com/doitsujin/dxvk/assets/114381457/58a5325c-d107-427c-ab9b-e06d94f7468b)
![Uploading Screenshot_2024-06-24-00-32-01-076_com.ludashi.benchmark.jpg…]()

**Comment by Azedin1111** [comment]
![Uploading Screenshot_2024-06-24-00-33-47-053_com.ludashi.benchmark.jpg…]()

**Comment by Azedin1111** [comment]
![Screenshot_2024-06-24-00-32-01-076_com ludashi benchmark](https://github.com/doitsujin/dxvk/assets/114381457/9fe1ec1a-e20c-45df-b4ef-8805e4f4b3bf)

**Comment by Blisto91** [comment]
This is a regression from commit https://github.com/doitsujin/dxvk/commit/7df8017e46692e972c710435261950c941b03acd
The as of writing current version of PR https://github.com/doitsujin/dxvk/pull/4036 improves it so it is only a bit over half the ground that is black, like seen above, versus below a quarter of it on the regressing commit.

**Comment by Blisto91** [comment]
Apitrace captured with wined3d https://drive.proton.me/urls/KRKSTRGW78#6yVyH6GGidSU

**Comment by Azedin1111** [comment]
![Screenshot_2024-06-25-01-39-33-326_com ludashi benchmark](https://github.com/doitsujin/dxvk/assets/114381457/ae19175a-b509-4af9-b58e-269168be6e42)

**Comment by Azedin1111** [comment]
![Screenshot_2024-06-25-01-42-26-269_com android chrome](https://github.com/doitsujin/dxvk/assets/114381457/2ca66d31-3d83-4296-a553-843a3e286ee3) 
Works
