### ISSUE TITLE
16-bit color mode

### ISSUE THREAD

**Issue by nolrinale** [doitsujin/dxvk#4088]
Is not really a bug but wanted to know if its possible to force 16-bit color in d3d8 and d3d9 games?

**Comment by nolrinale** [comment]
Well in PSO I can select in the options to go to either 32-bit and 16-bit, but when I tried to go 16-bit the game always defaults to 32 bit regardless. I assume it might happen with other games too thats why im not sure if its a bug from dxvk as is not honoring this setting change or something else entirely...

**Comment by K0bin** [comment]
What's the advantage of picking 16bit formats over 32?

> I think theres a confusion with this game from the previous PR but PSOBB is actually natively a d3d8 game not a d3d9 game but people use the d3d9 plugin to mod the client with shaders and whatnot

That doesn't really matter for us. There were some genuine DXVK bugs which that plugin hit and even besides that, we're looking to add D3D8 support soon-ish.

**Comment by nolrinale** [comment]
Well there isn't really an advantage/disadvantage more like being able to use all the options the game has to offer kind of situation.
In my case it's also a preference for the aesthetic factor of this specific color depth for some games but again this is all very subjective!

**Comment by nolrinale** [comment]
Closing this one as it looks like the 16-bit color functionality is there as long you manage to run the games in proper real full screen (not borderless/windowed modes) and to also free up space in your bug tracker.

Thanks again guys and amazing job as usual!
