### ISSUE TITLE
A problem with mouse control

### ISSUE THREAD

**Issue by Alllgator343** [doitsujin/dxvk#409]
When i move a computer mouse right or left to change camera angle, in a game the camera starts randomly spin.

### Software information
Battlefield Bad Company 2, Battlefield 3 (only after i used pop up menu in the game), Medal of Honor 2010, Mass Effect 3.

### System information
- GPU: Geforce 1050 Ti
- Driver: 396.24
- Wine version: 3.9
- DXVK version: 0.53
- Ubuntu 16.04 (Unity)

### Log files
- d3d11.log:
- dxgi.log: 
[Origin_dxgi.log](https://github.com/doitsujin/dxvk/files/2058658/Origin_dxgi.log)
[Origin_d3d11.log](https://github.com/doitsujin/dxvk/files/2058659/Origin_d3d11.log)
[BFBC2Game_dxgi.log](https://github.com/doitsujin/dxvk/files/2058660/BFBC2Game_dxgi.log)
[BFBC2Game_d3d11.log](https://github.com/doitsujin/dxvk/files/2058661/BFBC2Game_d3d11.log)
[bf3_dxgi.log](https://github.com/doitsujin/dxvk/files/2058662/bf3_dxgi.log)
[bf3_d3d11.log](https://github.com/doitsujin/dxvk/files/2058663/bf3_d3d11.log)

**Comment by doitsujin** [comment]
Not a DXVK bug.
