### ISSUE TITLE
Extend LongMad fix to Watch_Dogs 2 and Legion

### ISSUE THREAD

**Issue by toboggan7** [doitsujin/dxvk#4090]
The recent LongMad fix for Watch_Dogs (8d96535) should be extended to Watch_Dogs 2 and Watch_Dogs Legion, as it makes the appearance of outlines correct.

Below are videos captured in Watch_Dogs 2, showing the difference with and without it on. **EPILEPSY WARNING** for these, I repeatedly enable and disable NetHack to trigger outlines around the player character.

LongMad enabled:
https://github.com/doitsujin/dxvk/assets/63753664/cd7bb441-93dc-4138-97d5-5915d66ba381

LongMad disabled (notice the flashing outline patches):
https://github.com/doitsujin/dxvk/assets/63753664/989800aa-7a81-407a-b937-27a879bfeb97

Don't have an example for Legion, but can confirm it is visible when using DirectX 11. Does not appear on VKD3D or Windows.

**Comment by Blisto91** [comment]
Thank you for the report
