### ISSUE TITLE
GNOME HDR

### ISSUE THREAD

**Issue by Anuskuss** [doitsujin/dxvk#4101]
Can `DXVK_HDR` be made to work with [GNOME's experimental Rec. 2020 PQ](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2879) HDR mode? I was wondering if I could force DXVK to display in HDR even if the colors were not completely correct. Just asking if it could be done today because knowing GNOME, a proper solution could take a few years.

**Comment by Joshua-Ashton** [comment]
Not really on its own, without Gamescope you'd always be having 8bpc, and be missing the swapchain formats that allow DXVK, and such to expose full support to the game. You'd also be missing the EDID/metadata stuff for the game to read.

I recommend switching to KDE Plasma or using a Gamescope DRM session if you want to use HDR.
