### ISSUE TITLE
Share Assassin's Creed fixes with other games of the franchise

### ISSUE THREAD

**Issue by Tiagoquix** [doitsujin/dxvk#4102]
https://github.com/doitsujin/dxvk/blob/1783b9591af787bc41dcdf8994158f67bb00fae5/src/util/config/config.cpp#L20-L23

https://github.com/doitsujin/dxvk/blob/1783b9591af787bc41dcdf8994158f67bb00fae5/src/util/config/config.cpp#L278-L281

I think it would be feasible to share those same fixes with the following games: AC 3, AC 3 Remastered, AC 4, AC Rogue, AC Unity and AC Syndicate.

The first three use the same engine, AnvilNext, and the last two use AnvilNext 2.0.

Original AC 3 is known to have many bugs, and AC 3 Remaster also remastered the bugs.

AC4 has issues with AMD GPUs: https://www.pcgamingwiki.com/wiki/Assassin%27s_Creed_IV:_Black_Flag#Game_freezes_on_AMD_GPUs

As little evidence as this is, I think it is still valid, considering that:
- all games were released within a 3-year period;
- it's Ubisoft[^1];
- the games basically feel the same in the technical side of things, so I wouldn't be surprised if they also shared the same DXVK problems.

-------------------

Even though it's not DXVK's fault, it would be nice to have FPS limit for the original AC3: according to PCGW, frames above 80 cause physics issues. (See https://www.pcgamingwiki.com/wiki/Assassin%27s_Creed_III, CTRL+F "120+ FPS".) I think 60 FPS limit is OK here.

I'm not sure if AC3 and AC3 remaster share the same EXE name, but since Ubisoft also remastered the bugs then we should remaster the FPS limit too.

[^1]: Consider, for example, the Disrupt engine, which is used by Watch Dogs 1, 2 and Legion (being released on 2014, 2016 and 2020, respectively), and all of them share the same bug related to Long Mad. See https://github.com/doitsujin/dxvk/issues/4090.

**Comment by doitsujin** [comment]
> As little evidence as this is, I think it is still valid

No, it is not. I will consider it valid when you provide solid proof that these games do actually suffer from the exact same issue and require the same workaround.

Case in point, I did not find issues with Black Flag when testing it some years ago other than an MSAA-related game bug.
