### ISSUE TITLE
[d3d8] C&C: Generals/Zero Hour - menu slowdown

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#4112]
The game drops to ~15 fps when menus that are "heavy" on the UI like options or skirmish are accessed. This doesn't happen with WineD3D. The game is perfectly playable otherwise. Note that the game engine is capped at 31.2 fps.

The game and its addon are also available on Steam now, and are rather popular even these days, so we should look into this.

P.S.: The above problem is unaffected by cachedDynamicBuffers.

### Software information
C&C: Generals (& Zero Hour), retail.

### System information
- GPU: RTX 4070
- Driver: 535.183.01
- Wine version: 9.12 Staging
- DXVK version: fe9c875

### Apitrace file(s)
[generals.trace.tar.xz](https://drive.proton.me/urls/8XC0DHRN6M#YBYdw3mz1spl)

### Log files
- d3d8.log: [generals_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/11440472/generals_d3d8.log)

**Comment by Eonfge** [comment]
I've noticed a similar problem with transparent UI elements. In-game, tooltip balloons and the Generals Powers menu seem to cause similar lag spikes when they're being rendered.

I've never been able to pin point the problem so I hope that @WinterSnowfall has all the into you need.
