### ISSUE TITLE
[d3d8] Phantasy Star Online Blue Burst broken reflection/animated texture effects regression

### ISSUE THREAD

**Issue by nolrinale** [doitsujin/dxvk#4119]
There's a small regression with the graphic effects used in reflection/refraction of surfaces that was previously fixed in this PR https://github.com/doitsujin/dxvk/pull/4015 which is affecting PSOBB again the latest dxvk with the d3d8 update. 

I tested this in both in Wine on my Desktop PC and also on my Steam Deck and both places displays the same issues. 

![image](https://github.com/doitsujin/dxvk/assets/5244595/95b07e63-4437-41d9-b87a-6b9ff6c0fd67)

### Software information
Phantasy Star Online Blue Burst ver. 1.25.11 (official client)
client mirror [here](https://archive.org/details/psobb_jp_setup_12511_20240109)
test server patch [here](https://kiyomizu.moe/psobb/patch/PATCH_EN.zip)
(simply add wsock32 and psobb.cfg to the main game folder and add it as an
 override to winecfg, accounts are autocreated upon login) 

Windowed Mode
1280x920
high end setting

### Apitrace
[trace 1 seaside area](https://drive.google.com/file/d/10JEyMC7JMbKVDEbCDq2TotpN-RftCc3M/view?usp=sharing)
[trace 2 plant area](https://drive.google.com/file/d/1hUXxssZTXW8kfIKjzkFPGA3f2jXDFF7m/view?usp=sharing)

### System information
- GPU: RX6600
- Driver: Mesa 24.1.2 (Fedora 40)
- Wine version: 9.5 Staging
- DXVK version: the one available here https://github.com/doitsujin/dxvk/actions/runs/9826812319

**Comment by Blisto91** [comment]
To use d3d8 with dxvk you have to use both the d3d8 and d3d9 DLLs as the former in dependent on the latter.

**Comment by nolrinale** [comment]
Alrighty I didnt know, thank you Blisto

The game now launchs properly but then it is suffering of the same graphic issue that was fixed earlier by @K0bin in his previous PR with the reflection effects, water splashes and whatnot

![image](https://github.com/doitsujin/dxvk/assets/5244595/261578e0-4509-4498-b754-41f6aae88abf)

**Comment by nolrinale** [comment]
This is the PR that previously fixed this issue
https://github.com/doitsujin/dxvk/pull/4015

**Comment by Blisto91** [comment]
Thanks for reporting it. We will take a look

**Comment by Blisto91** [comment]
If you could make a d3d8 apitrace of the issue then that would be really helpful. I am having some trouble getting the game working for some reason.

**Comment by nolrinale** [comment]
Sorry for the delay I was able to get you a [trace](https://drive.google.com/file/d/1hUXxssZTXW8kfIKjzkFPGA3f2jXDFF7m/view?usp=sharing) in the same room with water I shared with Kobin back then, close to the end of the recording i'm running in circles splashing water so you can see the effect behavior
[trace](https://drive.google.com/file/d/1hUXxssZTXW8kfIKjzkFPGA3f2jXDFF7m/view?usp=sharing)

**Comment by Blisto91** [comment]
Was able to poke at it on Windows. It seems that the fixes have only helped d3d8to9 + dxvk d3d9 while d8vk + dxvk d3d9 still shows both the original monitor issue and the water splash issue.

d3d8 Windows apitraces: https://drive.proton.me/urls/6TF8S6PT40#MDBBe0JgWvtF
The water splash issue reproduces fine in the trace and can be seen working with d3d8to9 and dxvk while not with d8vk + dxvk d3d9.
The monitors are baked in to the traces so i made a native one where it works and one with dxvk where it doesn't

**Comment by nolrinale** [comment]
I was gonna post yet another apitrace of the seaside area of the first screenshot that in addition to the water splash effects you can also see all the moving texture effects that were broken previously too all in the same area for more convenience so here you have it too and im gonna ninja edit it at the original post as well 

[trace2 beach area](https://drive.google.com/file/d/10JEyMC7JMbKVDEbCDq2TotpN-RftCc3M/view?usp=sharing)

More ninjas 🥷
