### ISSUE TITLE
Far Cry 5 Arcade Editor shows a white screen instead of the game in the editor window

### ISSUE THREAD

**Issue by NullTheSecond** [doitsujin/dxvk#412]
![screenshot_20180602_105844](https://user-images.githubusercontent.com/31949120/40871931-5e5a5096-6688-11e8-8ef0-53ffb5b70b23.png)

### Software information
UPlay version of Far Cry 5 Arcade Editor.

### System information
- GPU: Nvidia GTX 1070
- Driver: Nvidia driver version 390.59 installed via RPMFusion
- Wine version: 3.9-staging
- DXVK version: 0.53

### Apitrace file(s)
- [ArcadeEditor64.trace](https://drive.google.com/open?id=1MCgVf74KRL-Kq5NTlVal57XjYiD7MGv0)

### Log files
- d3d11.log:  [ArcadeEditor64_d3d11.log](https://github.com/doitsujin/dxvk/files/2064487/ArcadeEditor64_d3d11.log)

- dxgi.log: [ArcadeEditor64_dxgi.log](https://github.com/doitsujin/dxvk/files/2064489/ArcadeEditor64_dxgi.log)

**Comment by acedogblast** [comment]
You need to use at least driver version 396.24.02. You can get them here: https://developer.nvidia.com/vulkan-driver

**Comment by NullTheSecond** [comment]
Installed the driver version 396.24.02. The Arcade Editor still does the same above.

As a side-note; Far Cry 5 (base game) works on both Nvidia driver version 390.59 and 396.24.02.

**Comment by doitsujin** [comment]
The log is pretty clear about what's wrong:
> err:   DxvkSurface::createSurface: Failed to create win32 surface

This is not something I can fix, sadly.
