### ISSUE TITLE
[regression] AQUARIUM renders its FMV shortly into the game as a black screen

### ISSUE THREAD

**Issue by AJuujarvi** [doitsujin/dxvk#4122]
The first FMV partway into the game renders as a black screen. Previous behavior was that it played with visuals, albeit it may have had stutter. Using some prebuilt Proton builds, I narrowed it down to being after commit 1783b9591af787bc41dcdf8994158f67bb00fae5, and happening at or before commit bbe851f6a25b57f320362c97b12afc52bfa99da1

You can get to the FMV by starting a new game and holding down the left mouse button. This will fast forward through text. You will have to click on the screen once in the middle of fast forwarding to select a dialogue option. The one you select does not matter, and you can just left click anywhere on the screen to select the default.

### Software information
AQUARIUM (2515070), default settings.

### System information
- GPU: Nvidia 4070
- Driver: 535.183.01
- Failing Proton: experimental-bleeding-edge-9.0-106101-20240705-p4f856c-w8d6dce-dbbe851-v1a2f20
- Working Proton: experimental-bleeding-edge-9.0-106030-20240704-p4f856c-w8d6dce-d1783b9-v1a2f20

### Log files
[steam-2515070.log](https://github.com/user-attachments/files/16131833/steam-2515070.log)

**Comment by Blisto91** [comment]
fwiw on Windows (only place I've tested so far) it black screens at the video both with master, 2.3.1 and 1.5. Plays fine when i throw `d3d9.deferSurfaceCreation = True` at it though.

**Comment by simifor** [comment]
I bisected and found the first bad commit to be 17577294, with the previous commit (5ae3cfe4) the video still loads in both my computer with a rx 6600 and mesa 24.1.3, and a steam deck oled on steamos beta.

**Comment by K0bin** [comment]
SRC: `276367 @11 IDirect3DDevice9::CreateOffscreenPlainSurface(this = 0x9430720, Width = 1920, Height = 1088, Format = D3DFMT_NV12, Pool = D3DPOOL_DEFAULT, ppSurface = [0x94abb88], pSharedHandle = NULL) = D3D_OK`

DST: `276339 @11 IDirect3DDevice9::CreateOffscreenPlainSurface(this = 0x9430720, Width = 1280, Height = 720, Format = D3DFMT_X8R8G8B8, Pool = D3DPOOL_DEFAULT, ppSurface = [0x94ab8e8], pSharedHandle = NULL) = D3D_OK`

`276434 @11 IDirect3DDevice9::StretchRect(this = 0x9430720, pSourceSurface = 0x94abb88, pSourceRect = [{left = 0, top = 0, right = 1920, bottom = 1080}], pDestSurface = 0x94ab8e8, pDestRect = [{left = 0, top = 0, right = 1280, bottom = 720}], Filter = D3DTEXF_POINT) = D3DERR_INVALIDCALL`
