### ISSUE TITLE
GTA 4 Doesnt work

### ISSUE THREAD

**Issue by TechySkills** [doitsujin/dxvk#4126]
### Software information
GTA 4

### System information
- GPU: Nvidia GT720M
- Driver: 391.35 
- DXVK version: 1.5.1 

### Apitrace file(s)
(Not Traceable because it doesnt even start well it does start but in Details Tab on Task Manager it shows its memory consumption going up to like 17343k then it suddenly drops to 1393k and will stay like that forever)

### Log files
```
info:  Game: GTAIV.exe
info:  DXVK: v1.5.1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  Failed to create Vulkan 1.1 instance, falling back to 1.0
info:  Game: GTAIV.exe
info:  DXVK: v1.5.1
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  Failed to create Vulkan 1.1 instance, falling back to 1.0
```

I have used Vulkan 1.5.1 because in 1.5.2 the Vulkan 1.1 is necessary and this is the max my drivers can go, So uh, I wanted to run this GTA 4 with DXVK, any way it is possible please?

**Comment by WinterSnowfall** [comment]
NVIDIA Fermi GPUs are at this point unsupported. You need a Vulkan 1.3 capable card.

**Comment by TechySkills** [comment]
> NVIDIA Fermi GPUs are at this point unsupported. You need a Vulkan 1.3 capable card.

What about older versions of DXVK do they also not support?

Also just tried 1.5 same result:
```
info:  Game: GTAIV.exe
info:  DXVK: v1.5
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  Failed to create Vulkan 1.1 instance, falling back to 1.0
info:  Game: GTAIV.exe
info:  DXVK: v1.5
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  Failed to create Vulkan 1.1 instance, falling back to 1.0

```

**Comment by WinterSnowfall** [comment]
> What about older versions of DXVK do they also not support?

Your guess is as good as mine. You're using no longer supported drivers, with a no longer supported card, with no longer supported versions of dxvk.

**Comment by TechySkills** [comment]
> > What about older versions of DXVK do they also not support?
> 
> Your guess is as good as mine. You're using no longer supported drivers, with a no longer supported card, with no longer supported versions of dxvk.

Hmm... So its my GPU fault and older versions of DXVK also wouldn't work, Am I correct?

**Comment by WinterSnowfall** [comment]
> So its my GPU fault and older versions of DXVK also wouldn't work, Am I correct?

They _might_ work in some situations, but it's hardly guaranteed at this point. If you run into issues I'm afraid there's nothing we can do at this point, other than advise you to use a supported card with the latest version of dxvk.

**Comment by TechySkills** [comment]
> > So its my GPU fault and older versions of DXVK also wouldn't work, Am I correct?
> 
> They _might_ work in some situations, but it's hardly guaranteed. If you run into issues I'm afraid there's nothing we can do at this point, other than advise you to use a supported card with the latest version of dxvk.

Okay...     :/

**Comment by K0bin** [comment]
I'm sorry but your GPU doesn't fulfil the minimum requirements of DXVK.
