### ISSUE TITLE
Banished: blocky shadows

### ISSUE THREAD

**Issue by sebastian-frysztak** [doitsujin/dxvk#413]
### Description
Some of shadows in Banished appear as blocks that move around in time. It looks like [this](https://www.dropbox.com/s/p7a7h3ehi5xxzew/banished.m4v?dl=0). Issue is gone when shadows are disabled, or when running the game without DXVK. It works well with wined3d, but I couldn't record full apitrace with it.

### Software information
Banished (32 bit build)

### System information
- GPU: AMD Ryzen 2400g (Raven Ridge)
- Driver: Mesa 18.0.4 (also tried with mesa-git)
- Wine version: 3.9
- DXVK version: 0.53

### Apitrace file(s)
- [dxvk apitrace](https://www.dropbox.com/s/us9qzepoan8a9we/Application-x32.trace.xz?dl=0)

### Log files
- d3d11.log: [Application-x32_d3d11.log](https://github.com/doitsujin/dxvk/files/2064814/Application-x32_d3d11.log)

- dxgi.log: [Application-x32_dxgi.log](https://github.com/doitsujin/dxvk/files/2064815/Application-x32_dxgi.log)

**Comment by doitsujin** [comment]
Your apitrace is extremely short so I don't know if it even shows the issue. Is there anything wrong with how this looks:
![banished](https://user-images.githubusercontent.com/25567304/40873295-f310a684-665d-11e8-910a-3919b86fb973.png)

Also, which LLVM version did you use?

**Comment by sebastian-frysztak** [comment]
Sorry it was so short, apitrace is extremely slow. I uploaded longer trace under the same link, it's still a couple of second long, counts 444 frames, and took 45 minutes to generate.

I tested with both Mesa-stable (LLVM 6.0) and Mesa-git (LLVM 7.0). There was no difference. I also compiled dxvk-master and issue still persists.

I think your screenshot looks fine, what I see are blocks like this:
![](https://user-images.githubusercontent.com/217806/40879196-b28f92d4-669c-11e8-9e27-3117d3d45bb3.png) They are visible in the video I linked.

**Comment by doitsujin** [comment]
I cannot reproduce the issue even with the longer trace.  This looks like a Vega/Raven-specific issue.

I haven't tested AMDVLK yet but it also renders correctly with the AMDGPU PRO Vulkan driver. Can you check if it works with those?

**Comment by hakzsam** [comment]
Yeah, looks like only GFX9 is affected. Please try to launch the game with RADV_DEBUG=nohiz

**Comment by sebastian-frysztak** [comment]
> Yeah, looks like only GFX9 is affected. Please try to launch the game with RADV_DEBUG=nohiz

That worked!

> I haven't tested AMDVLK yet but it also renders correctly with the AMDGPU PRO Vulkan driver. Can you check if it works with those?

AMDGPU PRO I haven't tried, because the version in AUR is outdated, but I have tried AMDVLK. It avoids the entire shadow issue by not rendering most objects that actually cast shadows! Pretty clever.

[Here's](https://www.dropbox.com/s/vsppi9kt83z2wio/banished_amdvlk.m4v?dl=0) a video. And [here's](https://www.dropbox.com/s/5g9yo2tqcqpwm61/banished_radv.m4v?dl=0) RADV without `RADV_DEBUG=nohiz` flag for comparison. AMDVLK also doesn't render weather effects, so I've disabled them for RADV as well.

What do I do now? Should I file a bug report to RADV issue tracker?

**Comment by hakzsam** [comment]
No need to fill a new ticket, I'm one of the RADV devs and this problem is well know. We will fix it at some point, I will let you know.

**Comment by sebastian-frysztak** [comment]
Great, thanks.

**Comment by hakzsam** [comment]
https://patchwork.freedesktop.org/patch/228364/ This fixes the rendering issue for me on Vega, can you confirm?

**Comment by sebastian-frysztak** [comment]
I can, the issue is gone. Thank you very much, I didn't expect this to be fixed so quickly.

On a unrelated note, do you happen to know what's the status of seemingly random system freezes caused by GPU on Raven Ridge? I just had one while writing this comment. I know the issue had been reported, but it seems like there's no progress.

**Comment by hakzsam** [comment]
Thanks for confirming. Unfortunately I don't have a Raven.
