### ISSUE TITLE
[d3d8] Question: Option to force windowed (non-fullscreen) mode?

### ISSUE THREAD

**Issue by thekovic** [doitsujin/dxvk#4133]
A motivation for using DirectX translation layers I often have is to allow me to force a game into bordered windowed mode (non-fullscreen) when the game doesn't offer this option by itself in its own options menu. This is a relatively common situation in pre-d3d9 games especially.

Now that DXVK has support for d3d8 titles too, it becomes a tool I might want to use for this purpose (alongside all its other benefits). However, it seems DXVK doesn't offer this feature currently? I looked for it as a configuration option in the [configuration file documentation](https://github.com/doitsujin/dxvk/blob/master/dxvk.conf) but couldn't find it. If it isn't present at the moment, is this something that would be feasible to implement and would you consider it?

Thank you for any response and for all the hard work you do on DXVK.

**Comment by doitsujin** [comment]
Setting `d3d9.enableDialogMode = True` may help, despite the name it should also apply to D3D8. That said, the best we can do on Windows is pass a flag to the driver to *please* not go into exclusive fullscreen, it may or may not get ignored.

**Comment by mirh** [comment]
Dxwrapper is what you are looking after.
