### ISSUE TITLE
[d3d9] some vulkan extensions are not present in x86

### ISSUE THREAD

**Issue by KoT3isGood** [doitsujin/dxvk#4136]
- GPU: RX 6700 XT
- Driver: Adrenalin 24.4.1
- DXVK version: 2.4

![image](https://github.com/user-attachments/assets/6dfcd73e-97f1-4658-81ee-06cbb605163c)

Left - vkEnumerateDeviceExtensionProperties, right - extensions supported

**Comment by Blisto91** [comment]
They likely just don't enable the Ray Tracing extensions in the 32bit driver.

https://github.com/GPUOpen-Drivers/xgl/blob/5dd432ade87244461b8cf357b5cb641e7ee7ff15/icd/api/strings/extensions.txt#L145
https://github.com/GPUOpen-Drivers/xgl/blob/5dd432ade87244461b8cf357b5cb641e7ee7ff15/icd/api/strings/extensions.txt#L189

**Comment by K0bin** [comment]
How is this a DXVK issue when your Vulkan driver doesn't expose certain extensions for 32bit applications?
