### ISSUE TITLE
GTA V Online - perfromance problem on high settings

### ISSUE THREAD

**Issue by MartinPL** [doitsujin/dxvk#414]
### Software information
Grand Theft Auto V Online
When i play on high settings with some time FPS gets degrade to unplayable level (4-5 FPS), i do not get that type problem on normal settings (normal = lowest in GTA). Din't find any trigger can happend randomly.

I recorded two videos with this issue: (sorry for crappy quality)
https://youtu.be/RVjgysP5AgA?t=39s (logs are from this)
in this scenerio i get low fps only afer car exit
https://youtu.be/R0F3gHl3hbQ?t=36m47s
in this fps get low after leaving the lobby (30m)

### System information
- GPU: Nvidia GTX 1070
- Driver: 396.24.02
- Wine version: Staging 3.9
- DXVK version: 0.53

### Log files
- d3d11.log:
```
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
warn:  D3D11Device: No matching border color found for (1,0,0,0)
warn:  D3D11RasterizerState: Depth clamp not properly supported
warn:  D3D11RasterizerState: Depth clamp not properly supported
warn:  D3D11RasterizerState: Depth clamp not properly supported
warn:  D3D11RasterizerState: Depth clamp not properly supported
warn:  D3D11RasterizerState: Depth clamp not properly supported
warn:  D3D11RasterizerState: Depth clamp not properly supported
err:   D3D11DeviceContext::SetPredication: Stub
```
- dxgi.log: 
```
info:  Enabled instance extensions:
info:    VK_KHR_win32_surface
info:    VK_KHR_surface
info:  GeForce GTX 1070:
info:    Driver: 396.24.2
info:    Vulkan: 1.1.73
info:    Memory Heap[0]: 
info:      Size: 8192 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 11979 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
info:  Enabled instance extensions:
info:    VK_KHR_win32_surface
info:    VK_KHR_surface
info:  GeForce GTX 1070:
info:    Driver: 396.24.2
info:    Vulkan: 1.1.73
info:    Memory Heap[0]: 
info:      Size: 8192 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 11979 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
warn:  Vulkan extension VK_EXT_vertex_attribute_divisor not supported
warn:  Vulkan extension VK_KHR_maintenance2 not supported
info:  Enabled device extensions:
info:    VK_KHR_swapchain
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_maintenance1
info:    VK_KHR_sampler_mirror_clamp_to_edge
warn:  Vulkan extension VK_EXT_vertex_attribute_divisor not supported
warn:  Vulkan extension VK_KHR_maintenance2 not supported
info:  Enabled device extensions:
info:    VK_KHR_swapchain
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_maintenance1
info:    VK_KHR_sampler_mirror_clamp_to_edge
warn:  DXGI: MakeWindowAssociation: Ignoring flags
info:  DxgiVkPresenter: Recreating swap chain: 
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_FIFO_KHR
  Buffer size:  2560x1440
info:  DxgiVkPresenter: Recreating swap chain: 
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  2560x1440
warn:  DXGI: MakeWindowAssociation: Ignoring flags
info:  DxgiVkPresenter: Recreating swap chain: 
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  2554x1414
info:  DxgiVkPresenter: Recreating swap chain: 
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  2560x1440
warn:  DXGI: MakeWindowAssociation: Ignoring flags
info:  DxgiVkPresenter: Recreating swap chain: 
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  2554x1414
```

**Comment by doitsujin** [comment]
Can't test GTA right now due to GPU hangs.

**Comment by Kerrung** [comment]
> Can't test GTA right now due to GPU hangs.
@doitsujin, [it looks like it has already been fixed](https://github.com/doitsujin/dxvk/issues/252#issuecomment-394014873)

**Comment by doitsujin** [comment]
I don't *want* to mess around with 100 different mesa+llvm combos right now, this can wait until the mesa patch lands in their git.

**Comment by MartinPL** [comment]
Didn't test long run with previous version so don't know it it's regression.
Video with stats (recorded with nvidia encoder)
https://youtu.be/9ypJV3na0YM?t=11m35s
timeline:
11:35 - fps start droping when i was killed
14:35 - uber low fps
19:44  - surprisingly fps back to normal
25:17 - i set almost all settings to very high (on windows in 1440p it gives ~60fps, game resolution on video is 1080p)

**Comment by doitsujin** [comment]
So it's not a memory issue, CPU isn't really utilized, GPU isn't utilized at all, PCIe bandwidth is a non-issue... no idea what's wrong there.

**Comment by xpander69** [comment]
had the same issue, but i thought it was just my system problem. It didn't happen with some really old dxvk builds or older wine versions, will be really hard to try to find at which point it regressed. Might be wine related also. I know that 3.7 staging didn't have this issue, but i also had much older dxvk then, will try to check.

**Comment by doitsujin** [comment]
Please test whether it works with latest `master`, which contains a workaround for games not setting up the depth bias correctly, leading to thousands and thousands of pipelines being compiled for no real reason.

**Comment by xpander69** [comment]
wine-staging 3.9
dxvk e8ac81f

no performance drop with 1 hour playing, single player campaign.

**Comment by MartinPL** [comment]
40m without drops, time to do some heists 😎 
There is still some problem with general performance, changing resolution 1080p<->1440p don't have any inpact on FPS, witcher 3 perfrom better then GTA V which shouldn't (?) be thing. Create now issue for this?

**Comment by xpander69** [comment]
@MartinPL your cpu? 4 core? GTA V loves cores and wine needs some also. With 4 core you wont have good experience, even with 4 core 8 thread there are issues, 6 core and up should be much better.

**Comment by MartinPL** [comment]
Intel i3770 4 core, 8 thread 🤔

**Comment by HadetTheUndying** [comment]
I'd be willing to give the latest builds a shot over the weekend. My performance wasn't very good when i tried GTA V before DXVK was a thing but my CPU is also 7 years old. I'll go ahead and install it and witcher 3 and see what i can post for tests.

**Comment by RomanHargrave** [comment]
@MartinPL have you experienced any periodical crashing with GTA, and if so has it lead to a process leak caused by winedbg crashing? 

I'm troubleshooting two problems - and am likely going to submit an issue about one here, and just wanted to know if anyone else is experiencing them.

**Comment by MartinPL** [comment]
nope, but have in mind that i play only GTA Online

**Comment by MartinPL** [comment]
Looks like eSync patches releases some CPU bound. FPS / GPU utilisation now looks good. Closing, thanks for your hard work 😀 🐧 ✌
https://github.com/zfigura/wine/blob/esync/

**Comment by RomanHargrave** [comment]
@MartinPL is there a description of this patch?

**Comment by MartinPL** [comment]
yep, https://github.com/zfigura/wine/blob/esync/README.esync
