### ISSUE TITLE
AC Origins option to use HDR grayed out with DXVK 2.4 on windows 11

### ISSUE THREAD

**Issue by vjsindhu-github** [doitsujin/dxvk#4140]
Have tried both these in the dxvk.conf file:

-DXVK_HDR=1
-dxgi.enableHDR = True

But in game HDR option is still grayed out in windows 11.

**Comment by Blisto91** [comment]
A lot of games need the vendor libraries Nvapi or amd ags working in order allow enabling HDR. Those won't work on Windows with dxvk.

**Comment by vjsindhu-github** [comment]
> A lot of games need the vendor libraries Nvapi or amd ags working in order allow enabling HDR. Those won't work on Windows with dxvk.

So if I was running the game though Linux would the HDR option be available?

**Comment by doitsujin** [comment]
Should be, yes. Either way, this game is known to require vendor libraries for HDR.

**Comment by hyperspeed6** [comment]
This fix works for me, it enables in game HDR option, tested on Windows 11.
Add this to dxvk.conf
`dxgi.hideNvidiaGpu = False`

**Comment by EChDatAnyl** [comment]
> This fix works for me, it enables in game HDR option, tested on Windows 11. Add this to dxvk.conf `dxgi.hideNvidiaGpu = False`

It still grayed out the HDR option, but it does force the use of in-game HDR mode when the game supports it. I never knew that one is still possible to do. Thank you!

**Comment by Oxilon** [comment]
@hyperspeed6 and this works to amd gpus?

**Comment by hyperspeed6** [comment]
> > This fix works for me, it enables in game HDR option, tested on Windows 11. Add this to dxvk.conf `dxgi.hideNvidiaGpu = False`
> 
> It still grayed out the HDR option, but it does force the use of in-game HDR mode when the game supports it. I never knew that one is still possible to do. Thank you!

Make sure the game is in fullscreen.
"Layer Vulkan/OpenGL on DXGI swapchain " enabled in nvidia profile inspector
This thing:
https://www.pcgamingwiki.com/wiki/Nvidia_Profile_Inspector#Layer_Vulkan.2FOpenGL_on_DXGI_swapchain

> [@hyperspeed6](https://github.com/hyperspeed6) and this works to amd gpus?

Tested with a Nvidia card

**Comment by Andrew-Miner** [comment]
> > > This fix works for me, it enables in game HDR option, tested on Windows 11. Add this to dxvk.conf `dxgi.hideNvidiaGpu = False`
> > 
> > 
> > It still grayed out the HDR option, but it does force the use of in-game HDR mode when the game supports it. I never knew that one is still possible to do. Thank you!
> 
> Make sure the game is in fullscreen. "Layer Vulkan/OpenGL on DXGI swapchain " enabled in nvidia profile inspector This thing: https://www.pcgamingwiki.com/wiki/Nvidia_Profile_Inspector#Layer_Vulkan.2FOpenGL_on_DXGI_swapchain
> 
> > [@hyperspeed6](https://github.com/hyperspeed6) and this works to amd gpus?
> 
> Tested with a Nvidia card

This fix worked for me! Thanks a ton @hyperspeed6. I almost wasn't going to play the game if I couldn't get HDR working.

**Comment by Gaboou** [comment]
> This fix works for me, it enables in game HDR option, tested on Windows 11.
> 
> 1. The game must be in fullscreen.
> 2. Make sure the "Layer Vulkan/OpenGL on DXGI swapchain " is enabled in nvidia profile inspector
>    This thing:
>    https://www.pcgamingwiki.com/wiki/Nvidia_Profile_Inspector#Layer_Vulkan.2FOpenGL_on_DXGI_swapchain
> 3. Then add this to dxvk.conf
>    `dxgi.hideNvidiaGpu = False`

One of the more recent versions of DXVK made Exclusive Fullscreen inactive by default so in my case I also had to add "dxvk.allowFse = True" to the dxvk.conf file - otherwise HDR would activate but the colors would be all wrong.

This also allows to use RTX HDR with DXVK, on a separate note.
