### ISSUE TITLE
[d3d9] Koi Kakeru Shinai Kanojo (and probably other Unison Shift visual novels) does not launch under DXVK

### ISSUE THREAD

**Issue by kichirouhoshino** [doitsujin/dxvk#4142]
### Software information
- Game: Koi Kakeru Shinai Kanojo (恋×シンアイ彼女)
- Settings: Default
- Japanese locale (LANG=ja_JP.UTF-8)
Same issue probably applies to other Unison Shift visual novels

### System information
- GPU: AMD Integrated GPU (Ryzen 5 5500U)
- Driver: apiVersion = 1.3.278, driverVersion = 24.1.3, RADV
- Wine version: wine-9.8-staging
- DXVK version: dxvk-2.4

### Apitrace file(s)
https://drive.google.com/file/d/1f8XldcShyvQsgzyEesBBqpZZuUM8eQKf/view?usp=sharing

### Log files
https://drive.google.com/file/d/1RsJecxh5n669pjKY18zc8vTXEz_DM-8y/view?usp=sharing

The game does not launch when using DXVK. Logs show that DXVK did initialize but no window shows up. Works fine under WineD3D.

**Comment by layercak3** [comment]
This is a duplicate of https://github.com/doitsujin/dxvk/issues/2104.

**Comment by kichirouhoshino** [comment]
Seems to be fixed on the latest wine version, it was apparently a wine issue.
