### ISSUE TITLE
DXVK new update made special k doenst work for fallout new vegas

### ISSUE THREAD

**Issue by MessyMark152** [doitsujin/dxvk#4145]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Game is fallout new vegas, settings is follow based on WallsoGB New Vegas performance guide with the use of special K following the 
instruction on WallsoGB guide
First problem: if press yes when enable native dxvk support, game still going but special K menu wont show up and cant be turn on
Second problem: If press no when enable native dxvk support, game is going and special K menu does appear but fps limiter or any other options doenst work.

### System information
- GPU: NVIDIA GeForce RTX 3060 Laptop GPU
- Driver: NVIDIA GFORCE GAME DRIVER ver: 556.12
- Wine version: Dont have it
- DXVK version:  2.4 - HDR

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

**Comment by MessyMark152** [comment]
sorry this is my first time posting any kind of bug about this, it works fine last version

**Comment by Blisto91** [comment]
The dxvk HDR-mod fork is not supported here at this repository so you have to test if official dxvk works or not.

**Comment by MessyMark152** [comment]
oh ok thank you i will try it out

**Comment by MessyMark152** [comment]
ok so the problem is the hdr version of dxvk then, i run the normal version and its works fine, thanks for helping

**Comment by Blisto91** [comment]
You can report the issue at https://github.com/EndlesslyFlowering/dxvk instead if you want to :slightly_smiling_face:
