### ISSUE TITLE
Feature request: Global config

### ISSUE THREAD

**Issue by Csimbi** [doitsujin/dxvk#4149]
Hello,
would it be possible change the config file lookup logic?

I'd prefer this flow:
1. Load defaults.
2. Look for a local config file (dxvk.conf at the same place as the DLL). If dxvk.conf exists, use found settings to override default settings and stop looking for additional settings.
3. Look for a global config file (on Windows, this would be %APPDATA%\dxvk.conf, pick one for Linux.) If dxvk.conf exists, use found settings to override default and global settings and continue looking for environment variable-based settings.
4. Look for environment variables. If exists, use it to override any settings already applied in steps 1, 3 and 4.

Something along these lines.
What do you think?

Thank you!

**Comment by doitsujin** [comment]
This can already be done by setting `DXVK_CONFIG_FILE`.
