### ISSUE TITLE
Crash in nfs therun

### ISSUE THREAD

**Issue by rakantoh** [doitsujin/dxvk#4153]
I tried to use dxvk in NFS The run, but show me this error message:
![image](https://github.com/user-attachments/assets/aecc3247-53f5-400f-8845-855f80285581)
this occurs in latest dxvk releases.

- GPU: Nvidia RTX 4070ti
- Driver: 556.12
- DXVK version: 2.0 - 2.4

**Comment by Blisto91** [comment]
Hi there.
Please attach the d3d11 + dxgi logs that appear in the games folder, usually next to the exe. Also make a apitrace if possible.

Make sure you don't have [Dozen](https://github.com/doitsujin/dxvk/wiki/Windows#dozen) installed. It will appear as a program called `OpenCL, OpenGL & Vulkan Compatibility Pack` in Add/Remove Programs

**Comment by rakantoh** [comment]
> Hi there. Please attach the d3d11 + dxgi logs that appear in the games folder, usually next to the exe. Also make a apitrace if possible.
> 
> Make sure you don't have [Dozen](https://github.com/doitsujin/dxvk/wiki/Windows#dozen) installed. It will appear as a program called `OpenCL, OpenGL & Vulkan Compatibility Pack` in Add/Remove Programs. It breaks dxvk

Solved/fixed adding "dxgi.deferSurfaceCreation=True" to dxvk.conf (discovered the issue viewing the log files), however i still testing if any other issue appears.

**Comment by K0bin** [comment]
Reopen if there's anything else wrong.
