### ISSUE TITLE
Issue releted to DXVK_CONFIG

### ISSUE THREAD

**Issue by niresh1234** [doitsujin/dxvk#4156]
**first argument does not load in dxvk config set by `DXVK_CONFIG`**

example (using Windows .cmd or .bat file........ or Windows Environment Variables)
```set DXVK_CONFIG="dxvk.hud=full; d3d9.enableDialogMode=True"``` 
in these case 1st arg `dxvk.hud=full` not working

but if i insert ```;``` before first argument also then it's working....
same example with `;` inserted
```set DXVK_CONFIG=";dxvk.hud=full; d3d9.enableDialogMode=True"```

**Comment by doitsujin** [comment]
Works here, and I don't really see why this would be any different on Windows?

**Comment by niresh1234** [comment]
You mean working on Linux?

**Comment by niresh1234** [comment]
See this

log 1
```
info:  DXVK: v2.4-5-g2a2d51e0
info:  Found config env: "dxvk.hud=full; d3d9.enableDialogMode=True"
info:  Effective configuration:
info:    d3d9.enableDialogMode = True
info:  Vulkan: Found vkGetInstanceProcAddr in vulkan-1.dll @ 0x6c5816e0
```
log 2 - **;** added
```
info:  DXVK: v2.4-5-g2a2d51e0
info:  Found config env: ";dxvk.hud=full; d3d9.enableDialogMode=True"
info:  Effective configuration:
info:    d3d9.enableDialogMode = True
info:    dxvk.hud = full
info:  Vulkan: Found vkGetInstanceProcAddr in vulkan-1.dll @ 0x6c5816e0
```

https://github.com/user-attachments/assets/2cd548a3-2fb6-41e0-9bab-5fb585881ed5

**Comment by niresh1234** [comment]
See this

log 1
```
info:  DXVK: v2.4-5-g2a2d51e0
info:  Found config env: "dxvk.hud=full; d3d9.enableDialogMode=True"
info:  Effective configuration:
info:    d3d9.enableDialogMode = True
info:  Vulkan: Found vkGetInstanceProcAddr in vulkan-1.dll @ 0x6c5816e0
```
log 2 - **;** added before 1st argument
```
info:  DXVK: v2.4-5-g2a2d51e0
info:  Found config env: ";dxvk.hud=full; d3d9.enableDialogMode=True"
info:  Effective configuration:
info:    d3d9.enableDialogMode = True
info:    dxvk.hud = full
info:  Vulkan: Found vkGetInstanceProcAddr in vulkan-1.dll @ 0x6c5816e0
```

https://github.com/user-attachments/assets/2cd548a3-2fb6-41e0-9bab-5fb585881ed5

**Comment by niresh1234** [comment]
@doitsujin See this

log 1
```
info:  DXVK: v2.4-5-g2a2d51e0
info:  Found config env: "dxvk.hud=full; d3d9.enableDialogMode=True"
info:  Effective configuration:
info:    d3d9.enableDialogMode = True
info:  Vulkan: Found vkGetInstanceProcAddr in vulkan-1.dll @ 0x6c5816e0
```
log 2 - **;** added before 1st argument
```
info:  DXVK: v2.4-5-g2a2d51e0
info:  Found config env: ";dxvk.hud=full; d3d9.enableDialogMode=True"
info:  Effective configuration:
info:    d3d9.enableDialogMode = True
info:    dxvk.hud = full
info:  Vulkan: Found vkGetInstanceProcAddr in vulkan-1.dll @ 0x6c5816e0
```

https://github.com/user-attachments/assets/2cd548a3-2fb6-41e0-9bab-5fb585881ed5

**Comment by Blisto91** [comment]
I can reproduce that there indeed seems to be a quirk with on Windows that isn't present on Linux.
Not sure exactly why though in the environment variable gui if you leave out the quotation marks (" ") then it works without needing a extra ;

**Comment by doitsujin** [comment]
The log above explains what's happening, the quotation marks are part of the string and confuse our parser. This doesn't really look like a bug to me, just some Batch syntax quirk, surely there must be a more correct way of setting env vars there.

**Comment by niresh1234** [comment]
yes..... without double quot(" ") is working.... and replacing doubleQuot with semicolon in beginning and ending also working

like `set DXVK_CONFIG=`
`;dxvk.hud=full; d3d9.enableDialogMode=True;`
or
`";dxvk.hud=full; d3d9.enableDialogMode=True;"`

**but it's just an experiment, not actual solution**

**Comment by niresh1234** [comment]
I THINK
```
IF
    Without DoubleQuote"_" working fine in windows (without any issue)
THEN
    It's should better add some NOTE in DXVK description/readme (about this)
////
```

**Comment by K0bin** [comment]
This is only an issue on Windows and Windows isn't the target platform for DXVK anyway.

**Comment by Blisto91** [comment]
It works as expected in powershell fwiw

**Comment by doitsujin** [comment]
That makes two ways of setting this up that are known to work on Windows. If Batch cannot express strings in the format that we expect them in then honestly I'd just recommend not using it at all if possible, or to work around its quirks on the script side of things.

**Comment by Redundanz** [comment]
@niresh1234 
this has nothing to do with dxvk at all. not even with the config syntax. this is internal windows workings.
you need to use the setx command. tested it: working!
make yourself familiar with it via `setx /?`
