### ISSUE TITLE
Serious Sam 2 Videos are broken

### ISSUE THREAD

**Issue by K0bin** [doitsujin/dxvk#4158]
![image](https://github.com/user-attachments/assets/0da5f25d-43ef-437d-93bf-bf971ee26b37)

Affects Serious Sam 2.
Reported by OnMars and bisected down to af0009c5debe33cffd5e412d0ff3d8adcd064c55.

**Comment by doitsujin** [comment]
Do we have a trace?

**Comment by simifor** [comment]
here is one https://mega.nz/file/hrtDBRhB#F9TF1WxEYCjUZG4q6sCcBtl90952Tt_lNZGBMq9cmYw
