### ISSUE TITLE
[d3d9 x32] Enter the Matrix (2003) crashes on startup

### ISSUE THREAD

**Issue by hyperspeed6** [doitsujin/dxvk#4164]
The game crashes as soon as I open it. I get this error "DEVICE NOT CREATED 2"
![6e8cecfa08d39f5030736f2973e2a173](https://github.com/user-attachments/assets/24860b0c-6ef1-43d2-98b5-c15b10452ee3)

### Software information
Enter the Matrix (2003)

### System information
- GPU: NVIDIA GeForce RTX 4090
- Driver: NVIDIA 560.70.0
- DXVK version: 2.4
- Windows 11

### Apitrace file(s)
https://drive.proton.me/urls/C7NAVT38J8#HDkkfwG8qkL9

### Log files
[Matrix_d3d9.log](https://github.com/user-attachments/files/16339280/Matrix_d3d9.log)

**Comment by Blisto91** [comment]
> err:   D3D9SwapChainEx: Failed to recreate swap chain: VK_ERROR_NATIVE_WINDOW_IN_USE_KHR

Line of interest in log

**Comment by K0bin** [comment]
Try it with the environment variable `DXVK_CONFIG=d3d9.deferSurfaceCreation=True`.

**Comment by mrdeathjr28** [comment]
Im my case run ok with dxvk 2.4

![etma](https://github.com/user-attachments/assets/fd716575-8dc8-496b-9a48-984b0af539ae)

![etmb](https://github.com/user-attachments/assets/b4d01b68-fbea-4b6e-945c-3b9ba4a3e0c7)

![etmc](https://github.com/user-attachments/assets/fdebcc56-9a92-4d2e-acbf-71a3a2d057cd)

**Comment by hyperspeed6** [comment]
> Try it with the environment variable `DXVK_CONFIG=d3d9.deferSurfaceCreation=True`.

Yes, this fixed it. I can launch the game and play it normally.
