### ISSUE TITLE
FIFA 19 won't RUN

### ISSUE THREAD

**Issue by ahhabjia** [doitsujin/dxvk#4165]
I tested over 3 distros : Manjaro, Pop Os and now endeavour os none of them work.
When I use DXVK 2.3 , It shows a DirectX Error Message that the graphic card is not initialized, But when I use the version 1.3, It shows also a DirectX Error 'An invalid parameter was passed to the returning function'.

I also tested it with wine-ge on lutris but the same problem persist.
### System information
- CPU: i5 4590
- GPU : Intel HD GRAPHICS 4600 
- Driver:
- Wine version: 9.8 Staging

These are some logs with DXVK 1.3 :

[FIFA19_dxgi.log](https://github.com/user-attachments/files/16351583/FIFA19_dxgi.log)
[FIFA19_d3d11.log](https://github.com/user-attachments/files/16351584/FIFA19_d3d11.log)

**Comment by K0bin** [comment]
As far as I remember, Intel GPUs before Broadwell don't properly support Vulkan (due to hardware limitations). ANV should also print a warning in the terminal about how Vulkan on those GPUs is incomplete and/or broken. That's almost certainly the issue.

Fifa 19 works on a proper GPU with a working driver.

**Comment by ahhabjia** [comment]
But It works perfectly on windows

**Comment by mbriar** [comment]
Hardware requirements are higher for running the game using a D3D11 to vulkan layer. Maybe it could work using wined3d and opengl on linux, but probably not nearly as well as it would on windows. You can also stop trying different distros, it doesn't change anything about your hardware and vulkan driver limitations.

**Comment by ahhabjia** [comment]
OK thanks for the fast reply

**Comment by Blisto91** [comment]
It is built in to Wine and will be used when dxvk isn't installed into a Wine prefix.

**Comment by ahhabjia** [comment]
And also when I set dx12 on directX the game start, but it shows a blank error after a while

**Comment by Blisto91** [comment]
Wine uses vd3d (not vkd3d-proton) for dx12 which uses Vulkan so you might be hitting issues like above. Only dx11 and below support OpenGL afaik.

**Comment by ahhabjia** [comment]
The problem is on dx11 it doesn't work completelly

**Comment by Blisto91** [comment]
Sorry there isn't much i can do. 
You can try using dxvk 1.10.3 which is the last version before the Vulkan requirement was bumped to 1.3, but it might not work anyway.

**Comment by K0bin** [comment]
Your GPU is definitely not capable of running D3D12.
