### ISSUE TITLE
Sequence Editor from Legendary Explorer of ME3Tweaks Mod Manager triggers GDI assert

### ISSUE THREAD

**Issue by gnusuari0** [doitsujin/dxvk#4171]
Sequence Editor 6.4.18 from Legendary Explorer of ME3Tweaks Mod Manager 9.0 (Tools->Legendary Explorer) triggers assert from Wine code base "err:msvcrt:_wassert (L"graphics->hdc_refs == 0",L"dlls/gdiplus/graphics.c",2621)". Executing with WINEDEBUG=warn+heap shows the following warning "warn:  Using GDI for swapchain presentation. This will impact performance." which belongs to https://github.com/doitsujin/dxvk/blob/master/src/d3d9/d3d9_swapchain.cpp#L218

The assert is triggered when trying to add a BioSeqVar_StoryManagerX variable where X is one of {Bool,Float,Int,StateId}. I have not tried all other object types. But from the Variables tab it only crashes when double clicking in any of those four.

The PCC file opened with the Sequence Editor can be downloaded here: https://drive.proton.me/urls/GSMNK9XPF8#MHMpgEs2uYHe

You have to configure Wine to emulate a virtual desktop. Otherwise tooltips and menus appear as black rectangles.

### Software information
Legendary Explorer 6.4.18 from ME3Tweaks Mod Manager 9.0.

### System information
- GPU: AMD Radeon VII (RADV VEGA20)
- Driver: radv 24.1.3
- Wine version: wine-9.13
- DXVK version: v2.3

### Apitrace file(s)
https://drive.proton.me/urls/7JP5G7ZJQ0#GJMdoH2IO9cx

### Log files
[me3tweaksmodmanager.log](https://github.com/user-attachments/files/16401891/me3tweaksmodmanager.log)

**Comment by mbriar** [comment]
> graphics->hdc_refs == 0",L"dlls/gdiplus/graphics.c",2621

That's not inside of DXVK code, why do you think it's a DXVK bug? Does it work with wined3d?

**Comment by gnusuari0** [comment]
Disabled DXVK and the assert is still being triggered. So yes, it's a Wine bug.
