### ISSUE TITLE
[Black Mesa] Transparency effects have very different rendering compared to native D3D9

### ISSUE THREAD

**Issue by Deus-nsf** [doitsujin/dxvk#4177]
It's been here for many versions but I didn't think of reporting this as an issue because I didn't want to be a bother,
but since Black Mesa may reintroduce DXVK as an option (because it comes with many benefits)
I feel like it's important to talk about it:

 DXVK vs native D3D9:

https://cdn.discordapp.com/attachments/1217231005203828836/1267962104275665048/362890_20240730234055_1.png?ex=66aab13b&is=66a95fbb&hm=a953f0a72a44558d3bedc4c9c14aa653f6fb930cd90a1b65d72a3a31e17f3489&

https://cdn.discordapp.com/attachments/1217231005203828836/1267962105257005179/362890_20240730234744_1.png?ex=66aab13b&is=66a95fbb&hm=eafb8230a0887899174613388979fae6e60df4f1fb9aebc22b42c4eaf7270733&

seems to do it with lens flares too, possibly other transparent textures like coronas etc...

**Comment by Joshua-Ashton** [comment]
Pretty sure this is a dupe of https://github.com/doitsujin/dxvk/issues/4006

**Comment by Deus-nsf** [comment]
It absolutely is, thanks.
So this is a Source thing, good to know, will help a lot more games than Black Mesa then :)

**Comment by Blisto91** [comment]
Is has been reported to Nvidia

**Comment by Deus-nsf** [comment]
Apparently Ada Lovelace GPUs are safe from it, but Pascal, Turing, and Ampere are affected (at least).

**Comment by Blisto91** [comment]
I have a Ada GPU and can reproduce it. In a apitrace at least

**Comment by Deus-nsf** [comment]
This is the guy that tested it for me, it looks correct here, hopefully that's not an other issue on top of it!
(This is on Windows):

https://i.imgur.com/LMSVDtZ.jpeg

**Comment by Deus-nsf** [comment]
It looks like the fog issue it isn't a duplicate after all, but a result of using the option
d3d9.forceSwapchainMSAA
when not using the option, things are normal (at least the fog opacity is)
since it's a custom config, I'm not sure it's worth investigating, I'll close this issue then.
