### ISSUE TITLE
[d3d8] Ballance black screen

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#4180]
Ballance just show a black screen when running with dxvk but not wined3d. The game ships with dgvoodoo2 on Steam and Gog but deleting that doesn't change anything. ~~@WinterSnowfall Says it is likely an issue with it using MFC.~~ See comments below 
Note that i had to manually install mfc42 with winetricks.

Game have a demo available https://www.pcgamingwiki.com/wiki/Ballance#Availability 

### Software information
https://store.steampowered.com/app/2000770/Ballance/

### System information
- GPU: RTX 4080
- Driver: 555.58.2
- Wine version: Proton Bleeding Edge

### Log files
[steam-2000770.log](https://github.com/user-attachments/files/16444424/steam-2000770.log)

### Apitrace file(s)
TBD

**Comment by dungeon007** [comment]
This looks some sort of collision between WINE's GLfied DDRAW and VK. Seems **DX7SoundManager.dll** just have it as an optional dep, but actually dont use it on this D3D8 path. So as a workaround, you can simple disable ddraw or to make it avoid touching GL... WINEDLLOVERRIDES="ddraw=d" or WINE_D3D_CONFIG="renderer=gdi" or whatever these vars are named for proton
![bance](https://github.com/user-attachments/assets/0d344758-f15a-4ef8-bbee-fa83d1285edd)
I even further tried disabling mfc42.dll and while couple libs (like InterfaceControls.dll and CK2UI.dll) complaining it is missing, it still runs regardless.. MFC seems also optional as game UI seems to functioning fine without that too  :D 
 GoG version just ships with DX8Rasterizer, while original engine supports DX5-8... so likely earlier renderers were needing that, but DX8... not really.

**Comment by WinterSnowfall** [comment]
What is the game using ddraw for? Is it just some intro videos perhaps? In that case does `d3d9.deferSurfaceCreation = True` do anything here?

**Comment by dungeon007** [comment]
Seems is not used for anything on D3D8 path :D, sound and video plays fine even with ddraw disabled.  Game itself dont use it on this D3D8 path, just that DX7SoundManager.dll have ddraw as an optional dep.
 Game engine was originally multi renderers SW/DX5/DX7/DX8... now on GoG only ships with D3D8 variant, so one can pretty much disable it.

**Comment by WinterSnowfall** [comment]
Got the GOG version of the game today and I'm able to run it just fine on Wine Staging 9.14 (and X11), without any ddraw overrides or anything else - just by removing the dgvoodoo2 files. There aren't any graphical issues with it as far as I can tell, so I believe we can consider this a "closure candidate".

**Comment by dungeon007** [comment]
Maybe issue depend sort of on a driver and/or WINE version or maybe let say staging is not affected, but classic WINE is or Proton... likelyy have some troubles with some combinations.  
 For Mesa i figured out that issue starting from this https://gitlab.freedesktop.org/mesa/mesa/-/commit/a4b28252286003a275988f3db9c91b8a3529ff54 
 So probably you can close it, as it inot VK related... it more looks like there are some sort of a GL issue there, maybe even in relation to particular wine ver or forks.
