### ISSUE TITLE
How do I use dxvk-native on Linux?

### ISSUE THREAD

**Issue by IriaSomobu** [doitsujin/dxvk#4182]
- Linux Mint 21.2 (kernel 5.15.0);
- gcc 11.4.0
- dxvk-native-2.4-steamrt-sniper.tar.gz from Releases page (manually unpacked in `/usr`)
- no `wine*` packages installed

I've compiled this [example.zip](https://github.com/user-attachments/files/16447183/example.zip) using the following command:
```
gcc \
-I/usr/include/dxvk/ \
-L/usr/lib/ \
-ldxvk_dxgi \
-ldxvk_d3d8 \
-ldxvk_d3d9 \
-ldxvk_d3d10core \
-ldxvk_d3d11 \
main.cpp -o main
```

And got linking error:
```
/usr/bin/ld: /tmp/cc8Kc4kk.o: in function `main':
main.cpp:(.text+0x73): undefined reference to `D3D11CreateDevice'
/usr/bin/ld: main.cpp:(.text+0x600): undefined reference to `D3DCompileFromFile'
/usr/bin/ld: main.cpp:(.text+0x70c): undefined reference to `D3DCompileFromFile'
collect2: error: ld returned 1 exit status
```

I guess I'm missing something obvious, like grabbing some other binaries (`.so`s? ) from somewhere else, but I cannot understand what exactly I'm doing wrong. Can somebody land me a hand?

**Comment by IriaSomobu** [comment]
Built from source ([e2b823b](https://github.com/doitsujin/dxvk/commit/e2b823b760775a2dd48727b76997ee888ba664cf)) -- same error :/

**Comment by Joshua-Ashton** [comment]
Hello. Does your /usr/lib actually contain `libdxvk_dxgi`, etc? Make sure if you build and install from src you install to /usr/lib instead of /usr/local/lib unless you want to change your -L.

I tried your example, and it works fine, aside from that DXVK does not implement D3DCompileFromFile. For that, you will need upstream vkd3d's vkd3d-utils and to load the file yourself.

Thanks.

**Comment by IriaSomobu** [comment]
Yup, the problem was on my side -- my friend w/ Archlinux says he has `undefined reference to 'D3DCompileFromFile'` only.

@Joshua-Ashton thank you! :blue_heart:

**Comment by IriaSomobu** [comment]
For anyone come here looking for a solution: it seems that it works w/ gcc14 but not w/ gcc11. Try compiling `clang` instead -- it worked for me.
