### ISSUE TITLE
Documentation: 32 bit and 64 bit mixed?

### ISSUE THREAD

**Issue by lrfinotti** [doitsujin/dxvk#4189]
Under "How to Use" in the README/documentation we see

```
export WINEPREFIX=/path/to/wineprefix
cp x64/*.dll $WINEPREFIX/drive_c/windows/system32
cp x32/*.dll $WINEPREFIX/drive_c/windows/syswow64
winecfg
```

Is that correct?  It seems that 32 and 64 bits are mixed.  Should it be

```
export WINEPREFIX=/path/to/wineprefix
cp x32/*.dll $WINEPREFIX/drive_c/windows/system32
cp x64/*.dll $WINEPREFIX/drive_c/windows/syswow64
winecfg
```

**Comment by K0bin** [comment]
"syswow64" is short for "system(32) windows on windows64". So while it seems confusing at first, the README gets it right.
