### ISSUE TITLE
Include the license file for OpenVR headers

### ISSUE THREAD

**Issue by oliwarner** [doitsujin/dxvk#419]
Noticed you pulled in a Valve header file for OpenVR. I'm not affiliated in any way (other than being a customer) but just want to make sure you stay compliant on their licensing because DXVK is just too damned important to be taken out by a silly compliance issue.

https://github.com/ValveSoftware/openvr/blob/master/LICENSE

https://github.com/doitsujin/dxvk/blob/2c9c7e1a363b2502c2a51d72a344ba54501e29df/include/openvr/openvr.hpp#L4

**Comment by doitsujin** [comment]
Right, thanks for the heads-up - fixed with 1fdcbdfa407952b8c9c1021e226f4d38c25d2aff.

**Comment by oliwarner** [comment]
Awesome. Thanks.
