### ISSUE TITLE
[d3d9] Might and Magic Heroes VI: vsync switch not working

### ISSUE THREAD

**Issue by ranplayer** [doitsujin/dxvk#4190]
The vsync switch option is not working (menu or in-game). This game uses **D3D9Ex** (don't know if that makes a difference for DXVK's implementation). I'm attaching a trace with the vsync on/off click. I've tried on X11 and Wayland.

### Software information
- Game: Might & Magic: Heroes VI
- Settings: maxed out at 1080p

### System information
- GPU: RX 6700 XT
- Driver: Mesa 24.1.5
- Wine version: Proton 9.0-2
- DXVK version: Proton's build and [latest master](https://github.com/doitsujin/dxvk/commit/7c9e1ed7cd469e2ad2e958ead3b56ce29aa30179)

### Apitrace file(s)
- [Apitrace](https://mega.nz/file/QhcDxJDK#NriXezulqw1OD1NAs-Ur8IDEpUlxqLzz5EFTt9P2MEs)

### Log files
- [steam-48220-heroes-vi.tar.gz](https://github.com/user-attachments/files/16512068/steam-48220-heroes-vi.tar.gz)

If more information is needed, let me know.

**Comment by Blisto91** [comment]
I do see that the option doesn't seem to do anything, but it also seems the same with wined3d. Will check Windows here later.

**Comment by Blisto91** [comment]
It appears that this is a game bug as the option doesn't do anything with the native game on Windows either.

**Comment by vlad54rus** [comment]
Was your game set to windowed? Vsync in D3D9 only works in fullscreen.

**Comment by Blisto91** [comment]
Tried both

**Comment by vlad54rus** [comment]
Strange. I downloaded the demo version from Steam and I can see Vsync toggle working correctly.

**Comment by Blisto91** [comment]
Can't get the demo working on Linux at the moment. 
But i can see that it is d3d9 instead of d3d9Ex and looking at SteamDB it seems the full version received a big update here back in March that the demo didn't, so the latter is probably not latest version.

**Comment by Blisto91** [comment]
Yes vsync works fine if i use the version pre March (still d3d9Ex).

**Comment by K0bin** [comment]
So it's a game bug according to @Blisto91.
