### ISSUE TITLE
Do all depth-stencil images need `VK_IMAGE_USAGE_SAMPLED_BIT` set by default?

### ISSUE THREAD

**Issue by werman** [doitsujin/dxvk#4191]
All depth-stencil attachments in DXVK have `VK_IMAGE_USAGE_SAMPLED_BIT` set (I'm sure about d3d9, but haven't looked at d3d11 too close), which is fine for Turnip for all formats but `VK_FORMAT_D24_UNORM_S8_UINT`. For this format when `customBorderColorWithoutFormat` is enabled we have to use different internal format and disable compression (UBWC) for it, which is obviously bad.

In `D3D9_COMMON_TEXTURE_DESC` I see `IsAttachmentOnly`. Maybe in such case DS image may skip SAMPLED flag?

Anyway, I'm not versed in D3D api, so the question is whether it's possible to skip  `VK_IMAGE_USAGE_SAMPLED_BIT` for DS attachments?

**Comment by K0bin** [comment]
On the D3D11 side of things, the sampling usage already mostly depends on whether the game passes the equivalent [D3D11 bind flag](https://learn.microsoft.com/en-us/windows/win32/api/d3d11/ne-d3d11-d3d11_bind_flag). There are a few cases where we add USAGE_SAMPLING without that but in those cases it's usually necessary for meta passes like blits/copies.

I need to re-check the D3D9 side, I think we can probably indeed get rid of the sampling usage in a lot of scenarios.
