### ISSUE TITLE
About the implementation of D3D10.dll

### ISSUE THREAD

**Issue by semmyenator** [doitsujin/dxvk#4194]
About the implementation of D3D10.dll

DXVK previously provided incomplete implementations of d3d10.dll and d3d10_1.dll, but they are no longer installed by default since version 1.6 because wine's implementation provides more functionality required for D3D10 games to run, including the D3D10 effects framework. Since our implementation is incomplete and has not been used by Proton or Lutris for a long time, DXVK will no longer provide these DLLs starting with this version. The D3D10 API itself is still supported through d3d10core.dll.

These announcements have been out for a while, and I have to say that the compatibility on the win32 platform seems to be better than the new supported version. I would like to ask if the team has stopped development in this area? In addition to the current supported version, is there any other version on the win32 platform? What is the alternative? Maybe I am one of the few users who operates dxvk d3d10 on the win32 platform.

**Comment by adolfintel** [comment]
You shouldn't use DXVK on windows, but if you must, I maintain some WineD3D builds for windows, you might be able to pull d3d10 DLLs from [here](https://github.com/adolfintel/wined3d4win) to use with DXVK. I never tested it but it might work.

Don't forget to extract wined3d.dll too and make sure you're using the correct 32/64 bit build for your game.

**Comment by Blisto91** [comment]
I'm not sure I understand the question. Are you saying dxvks d3d10.dll works better than the one provided by Wine?

**Comment by Joshua-Ashton** [comment]
DXVK's d3d10_core is compatible with the Windows DLLs. (Or at least was, haven't tested it in a while)

**Comment by semmyenator** [comment]
You shouldn't use DXVK on windows, but if you must, I maintain some WineD3D builds for windows, you might be able to pull d3d10 DLLs from here to use with DXVK. I never tested it but it might work.

Don't forget to extract wined3d.dll too and make sure you're using the correct 32/64 bit build for your game.

Thank you for your implementation. I will give it a try and consider using DXVK on Windows. This is because some games use more CPU than GPU under dx10/11. The reason is unknown.


I'm not sure I understand the question. Are you saying dxvks d3d10.dll works better than the one provided by Wine?

Or do you mean you used it on Windows as adolfintel says?

I think there should be differences between the native APIs based on Windows and Wine. Some games on Windows... cannot load the new alternative ver. On the contrary, the old version operates well.


I thank's all to help here.

**Comment by Blisto91** [comment]
I don't believe there should be any reason to use anything but the Windows versions of those DLLs while you are on Windows. All other implementations are trying to do what what the Windows one does so it is the best you are going to get.

Do you have a game where the Windows version is causing issues?

**Comment by semmyenator** [comment]
I don't believe there should be any reason to use anything but the Windows versions of those DLLs while you are on Windows. All other implementations are trying to do what what the Windows one does so it is the best you are going to get in regards to compatability.

Do you have a game where the Windows version is causing issues?

Yes, and no. When using Dxvk on Windows, the main reason is that the manufacturer's optimization may not necessarily be the best solution. There may also be compatibility differences in the driver. In my example, call to arms, when using dx, the cpu usage is 90 ℅The GPU usage is 60%, while in Dxvk, the cpu usage is 70℅ and the GPU usage is 80%. It may also be a psychological effect, it seems that the picture quality of Dxvk will be better than that of Dx.

**Comment by mbriar** [comment]
> When using Dxvk on Windows, the main reason is that the manufacturer's optimization may not necessarily be the best solution. There may also be compatibility differences in the driver. In my example, call to arms, when using dx, the cpu usage is 90 ℅The GPU usage is 60%, while in Dxvk, the cpu usage is 70℅ and the GPU usage is 80%

But you can still use DXVK's d3d10core.dll on windows and it should have the same effect, d3d10.dll and d3d10_1.dll are more or less "helper" libraries that should have no effect on performance whether you use windows', wine's or the old DXVK implementation.

>  It may also be a psychological effect, it seems that the picture quality of Dxvk will be better than that of Dx.

Placebo
