### ISSUE TITLE
Rainbow Six 3 -  broken Planing Phase.

### ISSUE THREAD

**Issue by YoinkerBoinker** [doitsujin/dxvk#4196]
When trying the Plan a Mission you can't set Waypoints (Screenshot shows the Planning Phase of the game). When trying to set them you will instead cycle through the levels of the map. Which isn't how it supposed to work and makes Planning a Mission pretty much impossible. This also seems to happen when using vanilla d3d8 on "modern" GPUs. The only "fix" for this  appears to be using dgvoodoo instead. Which is the reason why i started to hope dxvk (d8vk) might be able to fix it as well. 
When searching for a solution for the issue i found some old Posts (10y and older) in some Forums claiming that this was "fixed" by forcing AA Off via Driver. Though it appears that that fix no longer works. However i want to mention it in case it is helpful tracking this down.

### Software information
Tom Clancy's Rainbow Six 3 and Athena Sword, Default Settings

### System information
- GPU: 7700XT
- Driver: Mesa 24.1
- Wine version: Proton Expermental
- DXVK version:  2.4

![grafik](https://github.com/user-attachments/assets/6d0bd708-2b01-43ac-a4ca-8837c1eeb8a5)

**Comment by YoinkerBoinker** [comment]
I tried setting up windows exclusively for tracing this yet when using the trace files i'd get Visual C Errors when launching the game. I already installed an all in one Package of all Visual C Runtimes though the issue remains. Any Idea?

**Comment by WinterSnowfall** [comment]
Tracing works just fine on Linux usually, no need to go native for this. There's a guide you can follow here: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

That being said some games do crash when attempting to capture an apitrace, it is what it is.

**Comment by Blisto91** [comment]
@YoinkerBoinker Are you running the game with `PROTON_DXVK_D3D8=1 %commnad%` so that dxvk is used? It isn't enabled by default yet in proton.
Here i am only reproducing the issue with wined3d whereas it works fine with dxvk.

**Comment by YoinkerBoinker** [comment]
@Blisto91 Yup i tried it with the command still happens. Will only change the floor when trying to set Waypoint

**Comment by Blisto91** [comment]
Are you able to post a Proton log

**Comment by YoinkerBoinker** [comment]
Lol that was it. I'm an idiot. I just copied it noticed the same. Not it works. So this is a false report. I thought it would work by default since Proton Experimental contains DXVK 2.4. Ty so much. Finally this works :)

**Comment by YoinkerBoinker** [comment]
One more thing though. Do you have an Idea how to force fullscreen? That seems impossible to do so far.
