### ISSUE TITLE
Add Direct3D 7 support

### ISSUE THREAD

**Issue by Sagatt** [doitsujin/dxvk#4199]
Is that possible?

**Comment by Blisto91** [comment]
Yes. But the devs have also stated they aren't interested in having anything like that merged in to this repository. So if  someone decides to make a go at d3d7 it will be a separate project.

**Comment by K0bin** [comment]
Duplicate of #3234 and Blisto answered it.

**Comment by WinterSnowfall** [comment]
> so if someone decides to make a go at d3d7 it will be a separate project.

Stop making me sneeze!
