### ISSUE TITLE
[Regression] [d3d9] [Crash] Medieval 2. The mouse pointer disappears from the screen and the game crashes when loading without any error.

### ISSUE THREAD

**Issue by boludoz** [doitsujin/dxvk#4200]
### Software information
- Game: Medieval II: Total War
-  Latest stable working at  DKVK [Version 2.3.1](https://github.com/doitsujin/dxvk/releases/tag/v2.3.1)

### System information
- GPU: Intel(R) UHD Graphics
- Driver: Intel Corporation 101.5333.0
- Windows version: Windows 11 Pro
- DXVK version: v2.4

### Log files

[medieval2_d3d9.log](https://github.com/user-attachments/files/16568233/medieval2_d3d9.log)

**Comment by Blisto91** [comment]
Hi there.
Try to give latest master a shot https://github.com/doitsujin/dxvk/actions/runs/10308487321

**Comment by boludoz** [comment]
> Hi there. Try to give latest master a shot https://github.com/doitsujin/dxvk/actions/runs/10308487321

Tested on RTX 3080, Works.

**Comment by boludoz** [comment]
> Hi there. Try to give latest master a shot https://github.com/doitsujin/dxvk/actions/runs/10308487321

The mouse pointer is still not visible.

**Comment by boludoz** [comment]
![image](https://github.com/user-attachments/assets/438fef49-f247-4ff0-bf61-e81783c71a09)
![image](https://github.com/user-attachments/assets/31ee3902-fb51-4cf2-8d45-70eba7cd3e7f)

**Comment by Blisto91** [comment]
Does it work with this build <https://github.com/doitsujin/dxvk/actions/runs/9111053383>

**Comment by boludoz** [comment]
> Does it work with this build https://github.com/doitsujin/dxvk/actions/runs/9111053383

Not work sir.

**Comment by boludoz** [comment]
https://github.com/doitsujin/dxvk/actions/runs/10308487321 The good thing is that with this build the game at least works, it will show the mouse if there is an overlay on screen and the performance will be better when there is no overlay on screen, however and unfortunately the mouse pointer becomes invisible when there is no overlay on screen.

**Comment by boludoz** [comment]
One additional note is that CPU usage is extremely high.

**Comment by Blisto91** [comment]
Let's see if we are able to find the commit the cursor broke with. I assume you aren't set up to bisect dxvk yourself so i am just going to try supplying some builds.
Does it work with this?
[ab715a8.zip](https://github.com/user-attachments/files/16604588/ab715a8.zip)

I don't have access to a Intel GPU with a Windows install myself and haven't reproduced locally on Nvidia.

**Comment by boludoz** [comment]
> Let's see if we are able to find the commit the cursor broke with. I assume you aren't set up to bisect dxvk yourself so i am just going to try supplying some builds.
> Does it work with this?
> [ab715a8.zip](https://github.com/user-attachments/files/16604588/ab715a8.zip)
> 
> I don't have access to a Intel GPU with a Windows install myself and haven't reproduced locally on Nvidia.

No, in nVidia this does not happen, only in Intel.

**Comment by Blisto91** [comment]
Did you try the build i attached?

**Comment by boludoz** [comment]
> Did you try the build i attached?

That isnt working popperly.

**Comment by boludoz** [comment]
I offer you my computer for you to use with anydesk.

**Comment by Blisto91** [comment]
@boludoz I got my hands on a Intel GPU now to test with. I can reproduce the crash, which seems to be fixed now, but not the cursor issue.
Can you download this build and see how it looks? https://github.com/doitsujin/dxvk/actions/runs/12435734651

**Comment by boludoz** [comment]
> @boludoz I got my hands on a Intel GPU now to test with. I can reproduce the crash, which seems to be fixed now, but not the cursor issue. Can you download this build and see how it looks? https://github.com/doitsujin/dxvk/actions/runs/12435734651

Of course sir.

**Comment by boludoz** [comment]
> > @boludoz I got my hands on a Intel GPU now to test with. I can reproduce the crash, which seems to be fixed now, but not the cursor issue. Can you download this build and see how it looks? https://github.com/doitsujin/dxvk/actions/runs/12435734651
> 
> Of course sir.

It works perfectly.
