### ISSUE TITLE
Add a way to support DXVK with donations

### ISSUE THREAD

**Issue by elovin** [doitsujin/dxvk#421]
Since I don't know C and currently lack the time to learn it properly I would like to support this project with a small donation.

**Comment by MartinPL** [comment]
There were several similar topics, the author does not accept money. VK9 have patreon so you can donate him.

**Comment by oliwarner** [comment]
@MartinPL What's VK9 got to do with the price of fish?

If you're happy with the stack, wouldn't it be more logical to give it to Wine?

**Comment by MartinPL** [comment]
@oliwarner literally the same project but for directx 9 XD

**Comment by MeissnerEffect** [comment]
@elovin One way to support the project is to write _good_ bug reports for any bugs you find. i.e get apitrace working ;)

**Comment by doitsujin** [comment]
As was mentioned, I currently do not accept donations. Thanks anyway for willing to support the project.
