### ISSUE TITLE
Farcry 5 + nvidia 555/560 driver

### ISSUE THREAD

**Issue by adolfotregosa** [doitsujin/dxvk#4211]
It's not a bug report but more asking if there's some workaround.

### System information
- GPU: 3090
- Driver: 560.31.02
- Wine version: 9.14
- DXVK version: 2.4

The game refuses to start with nvidia driver above 550. 

Is there some known workaround? 

Thank you.

**Comment by Blisto91** [comment]
No known workarounds no

**Comment by qinlili23333** [comment]
Windows 560.94 & 565.90, same
The game seems cause driver reset when using DXVK.

An interesting thing is that dxgi.log is empty but d3d11.log is fine.
[FarCry5_d3d11.log](https://github.com/user-attachments/files/17228766/FarCry5_d3d11.log)
[FarCry5_dxgi.log](https://github.com/user-attachments/files/17228767/FarCry5_dxgi.log)

Seems something is blocking DXVK dxgi.dll

**Comment by qinlili23333** [comment]
Apitrace provided
Without DXVK, until menu https://github.com/qinlili23333/PageConnect/releases/download/TEST/FarCry5_apitrace.7z
With DXVK, until driver crash https://github.com/qinlili23333/PageConnect/releases/download/TEST/FarCry5_apitrace_dxvk.7z

**Comment by qinlili23333** [comment]
![image](https://github.com/user-attachments/assets/3322c1ea-ab86-44f5-b061-914c732b521d)
Solved. It's not DXVK or NVIDIA's issue.
Just disable the f**king Ubisoft overlay, and everything works.
See https://www.protondb.com/app/552520#tiDo4cxIIV

**Comment by adolfotregosa** [comment]
Can anyone confirm if it's the same fix under linux ? Unfortunately I cannot in the following days.
