### ISSUE TITLE
The Forest error when starting the game 

### ISSUE THREAD

**Issue by Oliwierox8** [doitsujin/dxvk#4213]
When starting the game, this error occurs. I tried launching in a window and in a lower resolution, but nothing worked. Any ideas on how to solve this?
![image](https://github.com/user-attachments/assets/9c9565a5-c65d-4641-a49b-fa86095296dd)

**Comment by Blisto91** [comment]
Hi there.
Please fill out the issue template with information such as GPU, driver, OS and or Wine version, logs. If on Windows the dxvk logs usually appear next to the exe.

**Comment by Oliwierox8** [comment]
Is this the file in question? 
[TheForest_d3d11.log](https://github.com/user-attachments/files/16682085/TheForest_d3d11.log)

**Comment by Blisto91** [comment]
There should be two. Are you using both the d3d11 and dxgi dlls with the game?

**Comment by Oliwierox8** [comment]
No, I only uploaded d3d11 to the game folder.

**Comment by Blisto91** [comment]
You need both

**Comment by Oliwierox8** [comment]
Thanks, it works. In games where I need to upload older versions than d3d11 also need dxgi?

**Comment by Blisto91** [comment]
You can find what dlls any specific API needs when using dxvk here https://github.com/doitsujin/dxvk#dll-dependencies
