### ISSUE TITLE
(Windows) Deadlock (unannounced Valve game) error on startup

### ISSUE THREAD

**Issue by ividyon** [doitsujin/dxvk#4215]
The new unannounced game by Valve does not allow launching when DXVK DLLs are used in the directory.

Deadlock is a D3D11 game, but also features a Vulkan mode.

If trying to use DXVK with the D3D11 mode, by copying DXVK's `dxgi.dll` and `d3d11.dll` into the game directory, the following message appears, and the game refuses to launch:

![image](https://github.com/user-attachments/assets/5581819f-a932-4b89-b7a5-a92fd6014b77)

This issue is not present when running in Vulkan mode, but presumably DXVK has no effect then.

I understand that this likely is not a DXVK bug per se, but as legacy DXVK is often used by Windows 7 users to run newer games, it would be a nice thing to look into.

On Windows 7, Deadlock in D3D11 mode causes crazy rainbow texture issues, while Vulkan mode has extremely poor performance and crashes very quickly after loading into the game. This is what makes DXVK interesting in the case of this game, despite its official Vulkan implementation.

### Software information
Deadlock, unannounced game by Valve Software

D3D11 mode and Vulkan mode

### System information
Tested on:

- Windows 7 64-bit with GeForce 3060 Ti on latest Win7 driver (474.11), with DXVK legacy version 1.10.3
- Windows 11 64-bit with GeForce 3080 Ti on latest driver (560.94), with DXVK 2.4

**Comment by Blisto91** [comment]
This is the games anti cheat kicking in (which is its job). Disabling it by launching with `-insecure` makes dxvk able to work but you wont be able to join a online match ofc.

**Comment by ividyon** [comment]
Good to know. Thank you. It is quite confusing, because a player on the Deadlock forums insists that they got DXVK to work just fine, but based on your testimony, that can't be true.

**Comment by doitsujin** [comment]
Maybe they were talking about Proton or something.

Anyway, closing based on above info.

**Comment by ividyon** [comment]
@doitsujin @Blisto91 I'd like to add onto this that apparently the solution is to set the game EXE to "run as administrator". This seems to launch the game with the DLLs correctly, working on my Win11 PC with the newest DXVK. I'll have the Win7 friend test it as well, but so far it's looking good, though I lack a means to confirm that DXVK really truly is running (the d3d11 and dxgi logs are empty).
