### ISSUE TITLE
SENRAN KAGURA Peach Ball: Backwards characters

### ISSUE THREAD

**Issue by waspennator** [doitsujin/dxvk#4216]
For some reason during cutscenes, character models are backwards, this issue goes away as soon as i set proton to use wined3d.

![download](https://github.com/user-attachments/assets/c6add78f-1bc8-4398-b97f-7c6edaa0c0e8)

How it should look.

![Screenshot_20240822_191242_YouTube](https://github.com/user-attachments/assets/e3f49c4c-e3a0-4971-9a6a-ad3e84714456)

### Software information
SENRAN KAGURA Peach Ball 

### System information
- GPU: AMD Van Gogh 
- Driver: Mesa 23.1.3 
- Wine version: Experimental 
- DXVK version: Unsure 

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

[steam-1074080.log.txt](https://github.com/user-attachments/files/16720801/steam-1074080.log.txt)

**Comment by K0bin** [comment]
Please make an apitrace.

**Comment by waspennator** [comment]
Disregard my last post, I was just a little dumb and didn't know how to do a DX11 api trace properly, here you go.

https://www.mediafire.com/file/6eden700jthycn0/SKPeachBall.zip/file

**Comment by doitsujin** [comment]
Fixed as of 1c30bc92bb49b67631abcccda884bab141f9ccb6.

**Comment by waspennator** [comment]
Can confirm that fixes it on my windows laptop, thank you. Presuming it will also fix on deck whenever proton pulls in DXVK again.
