### ISSUE TITLE
[d3d9] Borderlands GOTY (2009) buggy ambient occlusion

### ISSUE THREAD

**Issue by Spueh** [doitsujin/dxvk#4219]
### Software information
Borderlands GOTY (32-bit original)

### System information
- GPU: EVGA RTX 3060ti
- Driver: 560.94 (Latest)
- OS: Windows 10 22H2
- DXVK version: 2.4

### Apitrace file(s)
- Couldn't get to work currently, will post video for now:

https://github.com/user-attachments/assets/6fdbda08-18d5-4740-a1ef-c0d92ba3ee66

**Comment by K0bin** [comment]
Have you checked whether this happens with the regular Nvidia D3D9 driver? I wouldn't be surprised at all if this is just a side-effect of the SSAO algorithm they went with.

**Comment by K0bin** [comment]
Why did you close the issue?

**Comment by Spueh** [comment]
> Why did you close the issue?

For some reason I read that having this with game causes ambient occlusion to be buggy, I tested it without it (probably not enough) and somehow came to the conclusion that it bugged it, so it was my bad, there isn't any real issue here.
