### ISSUE TITLE
Kingdoms of Amalur Re-Reckoning Render issue on trees / plants (Missing texture and flickering shader)

### ISSUE THREAD

**Issue by NoTitleGamesOfficial** [doitsujin/dxvk#4229]
I made a short video where you can see the issue very clearly: 

https://www.youtube.com/watch?v=-21MSM27Qus

The log of the game shows always something like this:

```
00c4:fixme:d3dcompiler:d3dcompiler_shader_reflection_GetDesc iface 4CC36A70, desc 0012DE20 partial stub!
00c4:fixme:d3dcompiler:skip_u32_unknown Skipping 4 unknown u32s:
00c4:fixme:d3dcompiler:skip_u32_unknown 	0x7b83bea0
00c4:fixme:d3dcompiler:skip_u32_unknown 	0x88ba2a6f
00c4:fixme:d3dcompiler:skip_u32_unknown 	0xfe642eef
00c4:fixme:d3dcompiler:skip_u32_unknown 	0x320ec103
00c4:fixme:d3dcompiler:skip_u32_unknown Skipping 1 unknown u32s:
00c4:fixme:d3dcompiler:skip_u32_unknown 	0x00000001
00c4:fixme:d3dcompiler:skip_u32_unknown Skipping 1 unknown u32s:
00c4:fixme:d3dcompiler:skip_u32_unknown 	0x00000008
00c4:fixme:d3dcompiler:skip_u32_unknown Skipping 1 unknown u32s:
00c4:fixme:d3dcompiler:skip_u32_unknown 	0x00000008
00c4:fixme:d3dcompiler:skip_u32_unknown Skipping 1 unknown u32s:
00c4:fixme:d3dcompiler:skip_u32_unknown 	0x00000000
00c4:fixme:d3dcompiler:skip_u32_unknown Skipping 1 unknown u32s:
00c4:fixme:d3dcompiler:skip_u32_unknown 	0x00000000
00c4:fixme:d3dcompiler:skip_u32_unknown Skipping 2 unknown u32s:
00c4:fixme:d3dcompiler:skip_u32_unknown 	0x00000000
00c4:fixme:d3dcompiler:skip_u32_unknown 	0x00000000
00c4:fixme:d3dcompiler:skip_u32_unknown Skipping 1 unknown u32s:
00c4:fixme:d3dcompiler:skip_u32_unknown 	0x00000000
```

This get's repeated over and over again. 

### Software information
Kingdoms of Amalur Re-Reckoning, bought on GOG.
It runs through Heroic Games Launcher, using latest Crossover-Wine version. 

### System information
System Info:
CPU: 8x Apple M2
Memory: 8.59 GB (used: 3.78 GB)
GPUs:

OS:  14.4.0 (darwin)

The current system is not a Steam Deck
We are not running inside a Flatpak container

Software Versions:
  Heroic: 2.15.1 Emeth
  Legendary: 0.20.35 Lowlife (Heroic)
  gogdl: 1.1.1
  comet: comet 0.1.2

  Nile: 1.1.1 Will A. Zeppeli

Game Settings: {
	"autoInstallDxvk": true,
	"autoInstallDxvkNvapi": false,
	"autoInstallVkd3d": false,
	"preferSystemLibs": false,
	"enableEsync": true,
	"enableMsync": true,
	"enableFsync": false,
	"nvidiaPrime": false,
	"enviromentOptions": [],
	"wrapperOptions": [],
	"showFps": false,
	"useGameMode": false,
	"battlEyeRuntime": false,
	"eacRuntime": false,
	"language": "",
	"beforeLaunchScriptPath": "",
	"afterLaunchScriptPath": "",
	"wineVersion": {
		"wineserver": "/Users/maci/Library/Application Support/heroic/tools/wine/Wine-Crossover-latest/Contents/Resources/wine/bin/wineserver",
		"lib": "/Users/maci/Library/Application Support/heroic/tools/wine/Wine-Crossover-latest/Contents/Resources/wine/lib",
		"lib32": "/Users/maci/Library/Application Support/heroic/tools/wine/Wine-Crossover-latest/Contents/Resources/wine/lib",
		"bin": "/Users/maci/Library/Application Support/heroic/tools/wine/Wine-Crossover-latest/Contents/Resources/wine/bin/wine64",
		"name": "Wine Crossover - 23.7.1-1",
		"type": "wine"
	},
	"wineCrossoverBottle": "",
	"winePrefix": "/Users/maci/Games/Heroic/Prefixes/default/Kingdoms of Amalur Re-Reckoning"
}

### Apitrace file(s)
Sorry I'm a newbie and I don't get what Apitrace is or what I should add here? 
I did not change anything in the winecfg if that's what you're up to. 

### Log files
[1077045575-lastPlay.log](https://github.com/user-attachments/files/16823168/1077045575-lastPlay.log)

**Comment by K0bin** [comment]
D3DCompiler isn't part of DXVK. So if you're getting warnings/errors by that, it's very much possible that what you're looking at is a Wine bug where it generates invalid shaders or skips compiling some shaders entirely.

Try installing Microsofts d3dcompiler with Winetricks/Protontricks and see if that helps.

**Comment by NoTitleGamesOfficial** [comment]
> Try installing Microsofts d3dcompiler with Winetricks/Protontricks and see if that helps.

Unfortunately it did not (I installed d3dcompiler_47 - is that correct?)

thanks though that you help me even it's not a bug of your software. 

I wrote Crossover, maybe they can help me. 

You wrote that I'm running this using MoltenVK, is there an alternative that I can use on my Mac that might work better?

**Comment by mbriar** [comment]
> You wrote that I'm running this using MoltenVK, is there an alternative that I can use on my Mac that might work better?

Vulkan isn't supported on macOS and there is not better translation layer than MoltenVK.

**Comment by K0bin** [comment]
> Unfortunately it did not (I installed d3dcompiler_47 - is that correct?)

Try _43 as well.

> I wrote Crossover, maybe they can help me.

Are you even using Crossover?

> You wrote that I'm running this using MoltenVK, is there an alternative that I can use on my Mac that might work better?

Installing Linux on your Mac at some point in the future.

**Comment by NoTitleGamesOfficial** [comment]
> Vulkan isn't supported on macOS and there is no better translation layer than MoltenVK.

I See. So all Windows games are translated to Vulkan and then Vulkan is translated to Metal? 

> Try _43 as well.

I did but it did not change the issue :/ 

> Are you even using Crossover? Your logs sound more like you're using Heroic. So you can't expect Codeweavers to spend time and money providing support for you if you're essentially using their software without paying.

No, but I bought Crossover, too. Though the games runs worse using Crossover, it looks like this (even if this recording was made using PlayOnMac, though it looks the same on Crossover, so I did not make a new recording): https://youtu.be/aak9dsQeVi0

**Comment by mbriar** [comment]
> I See. So all Windows games are translated to Vulkan and then Vulkan is translated to Metal?

Pretty much. There is also the possibility to use wine's D3D to OpenGL translation (which is what you get by just not using DXVK), but that suffers from it's own performance and comparability problems and is mostly an option for older D3D9 games. Also not helped by the fact that OpenGL on macOS is stuck on version 4.1 and is probably barely maintained.
