### ISSUE TITLE
Post Scriptum (UE4): Performance and Rendering issues.

### ISSUE THREAD

**Issue by jarrard** [doitsujin/dxvk#423]
This game appears to work and load up quite well with no launch issues however in-game there is a problem where textures and lod's appear much lower then their windows counterparts. I also noticed the performance under DXVK was around 35fps while on windows with same settings (medium) it got 76fps.

I did use -force-d3d11 to make sure it wasn't dx12 or anything (windows) so the comparison is fair.

There is also a minor launch issue where the game will startup only 1 out of 3 times you attempt to launch it, this problem also exists in Deep Rock Galactic and could well be a general Unreal Engine 4 issue since they both use that engine.

### Software information
Post Scriptum, medium settings / 4k resolution  (trace done in 900p)
http://postscriptumgame.com

### System information
- GPU: 1080ti
- Driver: 396.24.02
- Wine version:  Wine3.9Staging
- DXVK version: dxvk-master 420b721

### Apitrace file(s)
I launched the game within windows10 and used apitrace.exe from there.

Used console from settings screen to AdminChangeMap and selected the last x-01 map and allowed it to load, it takes a few minutes for the grass and textures to pop-in due to fps being in the single digits, after which I closed the process.

- https://mega.nz/#!6n5yXISA!GOySKve5BF_zK-twZwwA_r2GS26Xq1P4fAao9BCzT_k

### Log files
- d3d11.log: [PostScriptum_d3d11.log](https://github.com/doitsujin/dxvk/files/2080286/PostScriptum_d3d11.log)
- dxgi.log:  [PostScriptum_dxgi.log](https://github.com/doitsujin/dxvk/files/2080287/PostScriptum_dxgi.log)

Wine/D3D Error codes that may be of relevance:
err:nvapi:NvAPI_D3D11_SetDepthBoundsTest Failed to get wined3d device handle!  (loads of these)

I will add logs and any other information as time goes on.

**Comment by jarrard** [comment]
As seen in this image, the roadway textures are low-res and the panzer4 is also load-res. I suspect the trees are also getting the low-res treatment. There may also be lower LOD models being used, can't be sure.  Under DXVK I would expect around 60fps as it gets 76fps in windows10.

![screenshot_20180607_202528](https://user-images.githubusercontent.com/17428910/41098312-1258f722-6a9a-11e8-8f68-406861b47a8e.png)

**Comment by doitsujin** [comment]
> err:nvapi:NvAPI_D3D11_SetDepthBoundsTest Failed to get wined3d device handle! (loads of these)

Please set nvapi and nvapi64 to `disabled` in winecfg.

**Comment by jarrard** [comment]
Update log files with nvapi and nvapi64 disabled.

[PostScriptum_d3d11.log](https://github.com/doitsujin/dxvk/files/2080432/PostScriptum_d3d11.log)
[PostScriptum_dxgi.log](https://github.com/doitsujin/dxvk/files/2080433/PostScriptum_dxgi.log)

I will work on getting a apitrace now.

**Comment by jarrard** [comment]
Apitrace complete, also a image from stock wine without dxvk.  The apitrace must be uploaded to meganz I'll link it once that's done. 

![wineonly_screenshot_20180607_222804](https://user-images.githubusercontent.com/17428910/41102412-fe1dadc8-6aa5-11e8-9dc9-23735da85404.png)

**Comment by jarrard** [comment]
Hopefully that APITRACE is good enough (link in op)

**Comment by doitsujin** [comment]
Your apitrace is an OpenGL apitrace, I need a **D3D11** apitrace.

Anyway, I think those issues are rather unique to this game, none of this happens in other UE4 games I've tested so far.

There's a texture streaming issue in Unreal Engine **3** games which might also cause the texture bug in this game, but it's basically impossible to debug that problem without knowing how the texture streaming works in the game/engine.

Poor performance is not an issue per se and it might not be possible to improve it.

**Comment by jarrard** [comment]
You saying Post Scriptum switched to opengl mode on me? or wine d3d11 via opengl?

If the later then the ONLY way to get a apitrace would be via windows boot itself.

**Comment by doitsujin** [comment]
You have to use the Windows version of apitrace (which also works on Linux). The Linux version of apitrace obviously captures wine's OpenGL output. It doesn't know that D3D11 even exists.

**Comment by jarrard** [comment]
Ok got it, doing the apitrace.exe from wine console now.

**Comment by jarrard** [comment]
Attached link to the new apitrace, hopefully this one is more useful.

I also produced apitrace for Fallout4 and KCD but I can't remember now if I did it in windows10 or not. Hopefully their not useless.. KCD still hard locks on nvidia cards at the bar scene :(
