### ISSUE TITLE
[d3d11 x64] Shadow of War crashes on startup

### ISSUE THREAD

**Issue by hyperspeed6** [doitsujin/dxvk#4240]
The game does not open at all with dxvk installed. 
When I use apitrace and open the game, I receive this error at launch:
![image](https://github.com/user-attachments/assets/5fc564cf-982f-40ee-bf66-19fca0e9e806)

By the way, injecting SpecialK in the game using its DLL (dxgi.dll) works without crashing.

### Software information
Middle-earth: Shadow of War - GoG edition

### System information
- GPU: NVIDIA GeForce RTX 4090
- Driver: NVIDIA 560.94.0
- DXVK version: 2.4
- Windows 11 Pro

### Apitrace file(s)
[Link](https://drive.proton.me/urls/CJWJ9V2AMM#ipwRi7mYVKdz)

### Log files
The log file is empty (ShadowOfWar_dxgi.log) and is the only log file created.

**Comment by K0bin** [comment]
https://github.com/doitsujin/dxvk/wiki/Windows#dll-loading-issues

**Comment by Blisto91** [comment]
See also https://github.com/doitsujin/dxvk/wiki/Windows#dozen

**Comment by hyperspeed6** [comment]
All overlays are off, including Nvidia's GeForce Experience and rivatuner statistics. Steam is closed.
Game is borderless.
"[OpenCL, OpenGL & Vulkan Compatibility Pack](https://apps.microsoft.com/detail/9NQPSL29BFFF)" is not installed in my system

**Comment by K0bin** [comment]
The game is probably loading d3d11.dll from C:\Windows\System32 and dxgi.dll from the game directory.

**Comment by Blisto91** [comment]
Did some poking and that seems to be the case yes.
