### ISSUE TITLE
[d3d11] DXGI_SWAP_EFFECT_SEQUENTIAL support 

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#4249]
Just so it is tracked.

https://github.com/ValveSoftware/Proton/issues/7017 needs the functionality for save game thumbnails.

Was tried implemented with https://github.com/doitsujin/dxvk/commit/79f6239df36a697ec79a1782d1df3b10607afcd1 but has to be reverted in https://github.com/doitsujin/dxvk/commit/a3fa9c26dce09a4e21935789e4f13bb537b19021 when issues was found.

**Comment by doitsujin** [comment]
Will be implemented with #4314.

**Comment by Blisto91** [comment]
Fixed by https://github.com/doitsujin/dxvk/commit/a278d6bf1da36f4cfefd3ec5b721cd5ebd3aadc6
