### ISSUE TITLE
Problem in S.T.A.L.K.E.R. (we need help) 

### ISSUE THREAD

**Issue by VladRabotnik24** [doitsujin/dxvk#4251]
Sorry for Russian language, I hope you can translate this by Google Translate. 

На некоторых новых, особенно, новых видеокартах (как, например, Intel Iris XE Graphics) наблюдаются баги с отображением листвы и травы. Вся растительность угловатая и чёрная и смазывается при движении игрока. Играть так, конечно, невозможно. 

Благодаря вашей замечательной утилите я смог запустить игру без багов, но, к сожалению, только на статическом освещении. По-моему, это Direct-X 8, хотя, может, я и ошибаюсь. 

Без динамического освещения (DX-10 вроде) играть не хочется, а замена движка на OGSR бессмысленна, если нужно запустить мод на движке SoC. 

Вопрос: может ли ваша утилита помочь в этой ситуации, и как помогает запускать игру вообще? Не увидел связи между Vulcan и статическим освещением. 

Спасибо за ответ.

**Comment by Blisto91** [comment]
> On some new, especially newer graphics cards (like Intel Iris XE Graphics) there are bugs with the display of leaves and grass. All vegetation is angular and black and blurs when the player moves. It is certainly impossible to play like this.
> 
> Thanks to your wonderful utility I was able to run the game without bugs, but unfortunately only on static lighting. I think it's Direct-X 8, although I may be wrong.
> 
> Without dynamic lighting (DX-10 I think) I don't want to play, and replacing the engine with OGSR is pointless if I need to run a mod on the SoC engine.
> 
> Question: can your utility help in this situation, and how does it help to run the game at all? I didn't see a connection between Vulcan and static lighting.
> 
> Thanks for the reply.

(DeepL translation)

Which operating system are you using?
If it is Windows then you can just try to shove all the x32 DLLs next to the exe and see if it helps or not.

Какую операционную систему вы используете?
Если это Windows, то вы можете просто попробовать засунуть все x32 DLL рядом с exe и посмотреть, поможет это или нет.

**Comment by tannisroot** [comment]
> Благодаря вашей замечательной утилите я смог запустить игру без багов, но, к сожалению, только на статическом освещении. 
Это опция? Каким образом она включается? Почему нельзя запустить с динамическим освещением?
> а замена движка на OGSR бессмысленна, если нужно запустить мод на движке SoC.
а это что вообще, какую это имеет связь? В чём собственно проблема при использовании DXVK?
Опиши проблему подробнее пожалуйста, и опиши как ты собственно DXVK установил.

**Comment by vlad54rus** [comment]
> На некоторых новых, особенно, новых видеокартах (как, например, Intel Iris XE Graphics) наблюдаются баги с отображением листвы и травы. Вся растительность угловатая и чёрная и смазывается при движении игрока. Играть так, конечно, невозможно.

Этот проблему Intel исправили ещё в апреле, обнови видеодрайвер до последней версии.

**Comment by K0bin** [comment]
I'm closing this because it's both missing the information which the issue template asks for and it's entirely in Russian. I don't think the burden to translate should be on us developers if you want us to look inside an issue you have.

**Comment by VladRabotnik24** [comment]
> Этот проблему Intel исправили ещё в апреле, обнови видеодрайвер до последней версии.

Спасибо. На апрельских и летних не работало, но теперь обновил на осенние, свежие - и заработало
