### ISSUE TITLE
Better message when libvulkan.so.1 fails to load

### ISSUE THREAD

**Issue by mbenkmann** [doitsujin/dxvk#426]
It would be good if there could be some better diagnostic printed when libvulkan.so.1 fails to load. I had libvulkan installed but still got that message. Only after using LD_PRELOAD did I find out the reason. Apparently I needed 32bit libvulkan.so.1 installed despite my WINEPREFIX being 64bit.

**Comment by SveSop** [comment]
@mbenkmann The WINEPREFIX 32 or 64 only makes you able to run 32 or 64 bit windows binaries. 32 bit prefix, does not run 64 bit windows binaries. 
When those binaries is run, they depend on the same bit-binary libraries in Linux to run - so running a 32-bit windows binary loads the suitable 32-bit Linux library, and that is why you have to have 32-bit libvulkan.so.1 :) 

I also found out that the hard way :)

**Comment by mbenkmann** [comment]
I'm sure a lot of people waste time trying to diagnose this, which is why a better diagnostic would be so useful.

**Comment by HellishINC** [comment]
Can confirm. Almost gave up when I couldn't get Graveyard Keeper working. Figured it was due to my 280x being "experimental" and not the project. Turns out I forgot to install lib32-vulkan-radeon.

**Comment by doitsujin** [comment]
DXVK doesn't load libvulkan.so directly, wine loads it. DXVK doesn't even know that it exists since it's using wine's own Vulkan library.
