### ISSUE TITLE
Company of Heroes 1

### ISSUE THREAD

**Issue by darkdakrioadenitis** [doitsujin/dxvk#4262]
When using the DXVK dx10 library, the ultra shader quality setting is not available in the game. dx10 version of DXVK does not work. Only dx9 works.
### System information
- GPU: GTX 1070
- Driver: 560.94
- Wine version: Windows 10
- DXVK version: 2.4

[d3d9.log](https://github.com/user-attachments/files/17003210/d3d9.log)

**Comment by Blisto91** [comment]
What DLLs are you using

**Comment by darkdakrioadenitis** [comment]
> What DLLs are you using

d3d10core.dll x32

**Comment by Blisto91** [comment]
For d3d10 you also have to use d3d11 and dxgi along with it.
