### ISSUE TITLE
Change DLL override to Native

### ISSUE THREAD

**Issue by jotkah** [doitsujin/dxvk#4265]
Hi Folks,

do i have to perform a DLL override for:

- d3d8
- d3d9
- d3d10core
- d3d11
- dxgi

As far as i remember i had to to this some years ago. I wonder why this is not mentioned in the Readme.md?

Greetings,
J.

**Comment by doitsujin** [comment]
Yes, it is necessary. I don't know why this was removed from the README, probably an oversight but we definitely used to mention it at *some* point.

**Comment by jotkah** [comment]
Thank you for your fast reply!
