### ISSUE TITLE
Bioshock Remastered needs IDXGIFactory2

### ISSUE THREAD

**Issue by aeikum** [doitsujin/dxvk#427]
Bioshock Remastered from Steam, appid 409710, crashes after the following warning:

```
warn:  DxgiFactory::QueryInterface: Unknown interface query
warn:  50c83a1c-e072-4c48-87b0-3630fa36a6d0
81894.112:01c5:01c6:trace:seh:raise_exception code=c0000005 flags=0 addr=0x10de5e7f ip=10de5e7f tid=01c6
```

This IID is IDXGIFactory2.

### System information
- GPU: Both Nvidia 1070 and Radeon RX Vega
- Driver: Nvidia 396.24 and 4.5 Mesa 18.2.0-devel - padoka PPA Direct Render: Yes
- Wine version: 3.7
- DXVK version: tagged v0.54

**Comment by doitsujin** [comment]
`IDXGIFactory2` is already implemented. You're not actually uisng DXVK 0.54 if you're getting the error (Lutris? old files somewhere?)
