### ISSUE TITLE
Can not build on KDE Neon (Ubuntu 16.04)

### ISSUE THREAD

**Issue by AnonimAssasin** [doitsujin/dxvk#428]
I tried to build dxvk, but had no success, here is the output:

[24/37] Compiling C++ object 'src/dxbc/dxbc@sta/src_dxbc_dxbc@sta_dxbc-unity.cpp.obj'.
FAILED: src/dxbc/dxbc@sta/src_dxbc_dxbc@sta_dxbc-unity.cpp.obj 
/usr/bin/x86_64-w64-mingw32-g++  -Isrc/dxbc/dxbc@sta -Isrc/dxbc -I../../../../git/dxvk/src/dxbc -I../../../../git/dxvk/./include -fdiagnostics-color=always -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++1z -O3 -MMD -MQ 'src/dxbc/dxbc@sta/src_dxbc_dxbc@sta_dxbc-unity.cpp.obj' -MF 'src/dxbc/dxbc@sta/src_dxbc_dxbc@sta_dxbc-unity.cpp.obj.d' -o 'src/dxbc/dxbc@sta/src_dxbc_dxbc@sta_dxbc-unity.cpp.obj' -c 'src/dxbc/dxbc@sta/dxbc-unity.cpp'
In file included from /home/alexey/work/dxvk/dxvk-master/build.64/../../../../git/dxvk/src/dxbc/../dxvk/dxvk_include.h:4:0,
                 from /home/alexey/work/dxvk/dxvk-master/build.64/../../../../git/dxvk/src/dxbc/../dxvk/dxvk_shader.h:5,
                 from /home/alexey/work/dxvk/dxvk-master/build.64/../../../../git/dxvk/src/dxbc/dxbc_include.h:3,
                 from /home/alexey/work/dxvk/dxvk-master/build.64/../../../../git/dxvk/src/dxbc/dxbc_common.h:3,
                 from /home/alexey/work/dxvk/dxvk-master/build.64/../../../../git/dxvk/src/dxbc/dxbc_chunk_isgn.h:5,
                 from /home/alexey/work/dxvk/dxvk-master/build.64/../../../../git/dxvk/src/dxbc/dxbc_analysis.h:3,
                 from /home/alexey/work/dxvk/dxvk-master/build.64/../../../../git/dxvk/src/dxbc/dxbc_analysis.cpp:1,
                 from src/dxbc/dxbc@sta/dxbc-unity.cpp:1:
/home/alexey/work/dxvk/dxvk-master/build.64/../../../../git/dxvk/src/dxbc/../dxvk/../util/log/log_debug.h:19:15: error: expected ‘{’ before ‘::’ token
 namespace dxvk::debug {
               ^
/home/alexey/work/dxvk/dxvk-master/build.64/../../../../git/dxvk/src/dxbc/../dxvk/../util/log/log_debug.h:19:17: error: ‘debug’ in namespace ‘::’ does not name a type
 namespace dxvk::debug {
                 ^
In file included from /usr/lib/gcc/x86_64-w64-mingw32/5.3-posix/include/c++/locale:41:0,
                 from /home/alexey/work/dxvk/dxvk-master/build.64/../../../../git/dxvk/src/dxbc/../dxvk/../util/util_string.h:3,
                 from /home/alexey/work/dxvk/dxvk-master/build.64/../../../../git/dxvk/src/dxbc/../dxvk/../util/util_env.h:3,
                 from /home/alexey/work/dxvk/dxvk-master/build.64/../../../../git/dxvk/src/dxbc/../dxvk/dxvk_include.h:6,
                 from /home/alexey/work/dxvk/dxvk-master/build.64/../../../../git/dxvk/src/dxbc/../dxvk/dxvk_shader.h:5,
                 from /home/alexey/work/dxvk/dxvk-master/build.64/../../../../git/dxvk/src/dxbc/dxbc_include.h:3,
                 from /home/alexey/work/dxvk/dxvk-master/build.64/../../../../git/dxvk/src/dxbc/dxbc_common.h:3,
                 from /home/alexey/work/dxvk/dxvk-master/build.64/../../../../git/dxvk/src/dxbc/dxbc_chunk_isgn.h:5,
                 from /home/alexey/work/dxvk/dxvk-master/build.64/../../../../git/dxvk/src/dxbc/dxbc_analysis.h:3,
                 from /home/alexey/work/dxvk/dxvk-master/build.64/../../../../git/dxvk/src/dxbc/dxbc_analysis.cpp:1,
                 from src/dxbc/dxbc@sta/dxbc-unity.cpp:1:
/usr/lib/gcc/x86_64-w64-mingw32/5.3-posix/include/c++/bits/locale_facets_nonio.h:59:39: error: ‘locale’ has not been declared
     struct __timepunct_cache : public locale::facet
                                       ^
/usr/lib/gcc/x86_64-w64-mingw32/5.3-posix/include/c++/bits/locale_facets_nonio.h:59:47: error: expected ‘{’ before ‘facet’
     struct __timepunct_cache : public locale::facet
                                               ^
/usr/lib/gcc/x86_64-w64-mingw32/5.3-posix/include/c++/bits/locale_facets_nonio.h:62:7: error: expected primary-expression before ‘static’
       static const _CharT*  _S_timezones[14];
       ^
..............

Many thanks!
Alexey

**Comment by doitsujin** [comment]
That software is hopelessly outdated. You need mingw 5.4 and GCC 7.3 in order to compile this.
