### ISSUE TITLE
Prince of Persia 2008

### ISSUE THREAD

**Issue by SadBoyOff** [doitsujin/dxvk#4281]
- GPU: RX470 
- Driver: 24.3.1
- DXVK version: 2.4.0
[Prince of Persia_d3d9.log](https://github.com/user-attachments/files/17085719/Prince.of.Persia_d3d9.log)

render in this game is broken

**Comment by Blisto91** [comment]
Hi there.
Broken in what way?
If a visual issue then try to include a screenshot or video that shows it and possibly a apitrace.

**Comment by mrdeathjr28** [comment]
In my case stay work and render seems ok with dxvk 2.4

![pop2008a](https://github.com/user-attachments/assets/fa7e2e32-48d4-4d3e-813f-4ffbf5bf7491)

![pop2008b](https://github.com/user-attachments/assets/024e0b48-3e6d-4061-8afd-d6f372655695)

**Comment by SadBoyOff** [comment]
https://youtu.be/V421D5wtHZA

**Comment by K0bin** [comment]
Probably a driver bug then.

**Comment by Blisto91** [comment]
Try giving it a shot with current master ø. You can download it here https://github.com/doitsujin/dxvk/actions/runs/10983650159

**Comment by K0bin** [comment]
Game works fine with DXVK on the Nvidia Vulkan driver and on RADV.

**Comment by SadBoyOff** [comment]
> Try giving it a shot with current master. You can download it here https://github.com/doitsujin/dxvk/actions/runs/10983650159

No, it didn't help

I should mention that I only have this problem in PoP2008

**Comment by SadBoyOff** [comment]
![image](https://github.com/user-attachments/assets/a622d7e4-f3d8-433c-85ce-cb2510d68d8f)

**Comment by K0bin** [comment]
Almost certainly a driver bug then. Not much for us to do about it.
