### ISSUE TITLE
GTA Vice City Massive FPS Drop in Latest Artifacts

### ISSUE THREAD

**Issue by niresh1234** [doitsujin/dxvk#4282]
**GTA Vice City Massive FPS Drop in Latest Artifacts**
in My modded game (d3d9 - using d3d8to9 wrapper)

**issue introduced from these commit** 👉 https://github.com/doitsujin/dxvk/commit/daccde7643a2b3ce0e67c2d460d29145c788d6bb

before these commit = game stable at 60FPS
after these commit = only 30-45FPS and sometime crash if ESE key press
.
.
.
here the part that remove from commit...
**I re-add this part in latest master and the issue suddenly gone.........** (see here what I change 👉https://github.com/niresh1234/dxvk/commit/95797e4bee875eb4abe19841a3cfa627da4d29ed)

```
    // Ignore sampled bit in case the image was created with
    // an image flag that only allows attachment usage
    if (m_desc.IsAttachmentOnly)
      Usage &= ~VK_IMAGE_USAGE_SAMPLED_BIT;
```

### Important: Im not a programmer and dont know about code that how it is working..

**Comment by K0bin** [comment]
That PR should fix it. Would be great if you could test it.

**Comment by niresh1234** [comment]
Yes! fixed 👏

**Comment by K0bin** [comment]
Great, thanks for reporting it.
