### ISSUE TITLE
DirectX9 Games Rendering Issue

### ISSUE THREAD

**Issue by akiy-33** [doitsujin/dxvk#4284]
Issue:
DirectX9 games such as Counter-Strike: Source and Counter-Strike: Global Offensive are not rendering properly. The screen remains black during gameplay.

Affected Versions:
This issue occurs in all versions of DXVK after 1.9.1. For example, version 1.9.1 works without any issues, while versions from 1.9.2 to 2.4 (latest) result in a black screen.

Software Information:

Game: Counter-Strike: Source
DXVK HUD setting: DXVK_HUD=full

System Information:
GPU: Apple M3 Pro
Driver Version: 0.2.2013

Wine Version: 9.0
DXVK Version: 1.9.2 to 2.4 (latest)

**Comment by Blisto91** [comment]
Hi there. 
MacOS is not supported (i assume that is what you are using). How are you even running dxvk at 2.0 and above? MoltenVK doesn't support Vulkan 1.3 afaik.

**Comment by K0bin** [comment]
DXVK requires Vulkan 1.3 and MoltenVK only supports 1.2. Even besides that, the way DXVK handles texture binding was (is?) broken on MoltenVK.

So you're almost certainly looking at MoltenVK bugs.

**Comment by akiy-33** [comment]
Sticking with the version 1.9.1 solved my problem. And since MoltenVK doesn't support Vulkan 1.3, I will keep on using the older version of DXVK for directx9 games.
