### ISSUE TITLE
DXVK Not Producing Logs

### ISSUE THREAD

**Issue by JamesYen220** [doitsujin/dxvk#4289]
I'm currently able to successfully show DXVK_HUD for steam games but for some old reason, the log files aren't being produced. I'm trying to log the FPS of the games. Here are my launch options on steam: DXVK_HUD=full DXVK_LOG_PATH=~/dxvk_logs PROTON_LOG=1 %command%

### Log files
[steam-247020.log](https://github.com/user-attachments/files/17111246/steam-247020.log)

**Comment by Blisto91** [comment]
Have you created the `dxvk_logs` directory beforehand?

**Comment by JamesYen220** [comment]
Are there any ways to log the information shown by DXVK_HUD then?

**Comment by WinterSnowfall** [comment]
[Maybe there is...](https://learn.microsoft.com/en-us/windows/win32/gdiplus/-gdiplus-sending-gdi-output-to-a-printer-use) (that was a joke). No, we don't have loggers for any of it at the moment. Arguably we could dump the info to logs as well when the HUD gets refreshed, I guess, but what would be the use care for that anyway?

**Comment by Blisto91** [comment]
Mango his have the functionality of i recall yea. But haven't tried using the logging myself with it.
