### ISSUE TITLE
Sleeping Dogs hang on startup with DXVK, runs fine on plain wine (crashes on actual game start though)

### ISSUE THREAD

**Issue by slapin** [doitsujin/dxvk#429]
If I install game (Definitive Edition) and run it via wine the menu works.
If I install any version of DXVK (0.50, 0.52, 0.53, 0.54) it just hangs untill killed.
GTAV works perfectly fine. Far Cry hangs too at 200% CPU, but I think it is something different.

### Software information
Sleeping Dogs DE, defaults.

### System information
- GPU: GeForce GTX 660
- Driver: 390.48.0
- Wine version: 3.9 staging
- DXVK version: 0.54

### Apitrace file(s)
- Put a link here
Nah, don't understand how to do it, too much for me.

### Log files
- d3d11.log:
empty.
- dxgi.log: 
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_win32_surface
info:    VK_KHR_surface
info:  GeForce GTX 660:
info:    Driver: 390.48.0
info:    Vulkan: 1.0.65
info:    Memory Heap[0]:
info:      Size: 2048 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]:
info:      Size: 12020 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
warn:  DXGI: CheckInterfaceSupport: No D3D10 support
err:   DXGI: CheckInterfaceSupport: Unsupported interface
err:   9b7e4c0f-342c-4106-a19f-4f2704f689f0

console output:

000b:fixme:winediag:start_process Wine Staging 3.9 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
0009:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0009:fixme:kerberos:kerberos_SpInstanceInit 65536,0x7f963cf2e7a0,(nil): stub
0009:fixme:heap:RtlSetHeapInformation 0x13a0000 0 0x2ae840 4 stub
0009:fixme:thread:SetThreadIdealProcessor (0x110): stub
0038:fixme:system:SystemParametersInfoW Unimplemented action: 59 (SPI_SETSTICKYKEYS)
0038:fixme:system:SystemParametersInfoW Unimplemented action: 53 (SPI_SETTOGGLEKEYS)
0038:fixme:system:SystemParametersInfoW Unimplemented action: 51 (SPI_SETFILTERKEYS)
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_win32_surface
info:    VK_KHR_surface
0038:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkCreateDebugReportCallbackEXT".
0038:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkDestroyDebugReportCallbackEXT".
0038:fixme:vulkan:wine_vkGetInstanceProcAddr Unsupported device or instance function: "vkDebugReportMessageEXT".
info:  GeForce GTX 660:
info:    Driver: 390.48.0
info:    Vulkan: 1.0.65
info:    Memory Heap[0]: 
info:      Size: 2048 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 12020 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
warn:  DXGI: CheckInterfaceSupport: No D3D10 support
err:   DXGI: CheckInterfaceSupport: Unsupported interface
err:   9b7e4c0f-342c-4106-a19f-4f2704f689f0
^C0039:fixme:console:CONSOLE_DefaultHandler Terminating process 8 on event 0
0039:fixme:msvcrt:__clean_type_info_names_internal (0x2f05e8) stub
0039:fixme:msvcrt:__clean_type_info_names_internal (0x42d1a8) stub

**Comment by doitsujin** [comment]
You need to run this game with `DXVK_FAKE_DX10_SUPPORT=1` set.

**Comment by mradermaxlol** [comment]
@doitsujin I think you should explicitly mention/link the project's Wiki, as the thing with fake D3D10 for SD and other game-specific info/quirks were there IIRC :)

**Comment by slapin** [comment]
Well now I get whole screen white with mouse cursor with occasional attempt to play sound.

dxgi:
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_win32_surface
info:    VK_KHR_surface
info:  GeForce GTX 660:
info:    Driver: 390.48.0
info:    Vulkan: 1.0.65
info:    Memory Heap[0]:
info:      Size: 2048 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]:
info:      Size: 12020 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
warn:  DXGI: CheckInterfaceSupport: No D3D10 support
warn:  Vulkan extension VK_EXT_vertex_attribute_divisor not supported
warn:  Vulkan extension VK_EXT_shader_viewport_index_layer not supported
warn:  Vulkan extension VK_KHR_maintenance2 not supported
info:  Enabled device extensions:
info:    VK_KHR_swapchain
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_maintenance1
info:    VK_KHR_sampler_mirror_clamp_to_edge

d3d11:
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0

and nothing more. Probably interface drawing is not supported for some reason...

**Comment by slapin** [comment]
Sorry, looks like wine crash is following, so I'm out of luck on this game. Sorry for trouble.

**Comment by slapin** [comment]
Thanks a lot for all help

**Comment by slapin** [comment]
Well, looks like wine + wined3d = no crash at startup. wine + dxvk = crash at startup. So closing this would not be right, but I probably consider this show stopper for me.

**Comment by doitsujin** [comment]
One major issue I've discovered with Sleeping Dogs is that it runs out of address space even if the LAA flag is set. I don't know why that happens, but it's not something I can fix, sorry.

Your driver version is not supported either, which might cause additional issues, but Sleeping Dogs won't be supported by DXVK.

**Comment by slapin** [comment]
Ah, thanks a lot!
