### ISSUE TITLE
[d3d9] The First Templar has lighting issues, not present with wined3d

### ISSUE THREAD

**Issue by Leopard1907** [doitsujin/dxvk#4291]
### Software information
 The First Templar, GOG copy, all settings set to maximum possible

### System information
- GPU: 7900 XTX
- Driver: Mesa 24.2.3
- Wine version: Proton Experimental
- DXVK version: Whatever Experimental has as of now

### Apitrace file(s)

wined3d trace:

https://drive.google.com/file/d/1Et4a9dbP9nOk7I3Nfkv8muZcozK26lhh/view?usp=sharing

dxvk trace:

https://drive.google.com/file/d/1PSOT1wePe9PWaDDG6_iLywewEsvOpWmp/view?usp=sharing

### Log files

Proton log: 
[steam-heroic-The First Templar.log](https://github.com/user-attachments/files/17119608/steam-heroic-The.First.Templar.log)

Shows a bunch of:

```
err:   DxvkContext: copyImageFb: Unsupported operation:
err:     srcFormat = VK_FORMAT_D32_SFLOAT_S8_UINT (aspect 6)
err:     dstFormat = VK_FORMAT_D32_SFLOAT (aspect 2)
```

### Screenshots that shows the issue

![Ekran Görüntüsü_20240924_213851](https://github.com/user-attachments/assets/0f64fb5a-1655-4162-856f-e21e1d640f23)
![Ekran Görüntüsü_20240924_214014](https://github.com/user-attachments/assets/f5c021a4-7337-49e8-814b-f7d8766871b0)
![Ekran Görüntüsü_20240924_214027](https://github.com/user-attachments/assets/423e0a92-cc73-41ac-9bce-97b5002dee57)

**Comment by K0bin** [comment]
> 90 @0 IDirect3DDevice9::CreateDepthStencilSurface(this = 0xd4240f0, Width = 2560, Height = 1440, Format = D3DFMT_D24S8, MultiSample = D3DMULTISAMPLE_NONE, MultisampleQuality = 0, Discard = TRUE, ppSurface = [0xd4c6430], pSharedHandle = NULL) = D3D_OK
89 @0 IDirect3DDevice9::CreateTexture(this = 0xd4240f0, Width = 2560, Height = 1440, Levels = 1, Usage = D3DUSAGE_DEPTHSTENCIL, Format = D3DFMT_DF24, Pool = D3DPOOL_DEFAULT, ppTexture = [0xd4c92e8], pSharedHandle = NULL) = D3D_OK

> 10533570 @0 IDirect3DDevice9::SetDepthStencilSurface(this = 0xd4240f0, pNewZStencil = 0xd4c6430) = D3D_OK
10561899 @0 IDirect3DDevice9::SetTexture(this = 0xd4240f0, Stage = 0, pTexture = 0xd4c92e8) = D3D_OK // RESZ

**Comment by Leopard1907** [comment]
Referenced PR fixes the issue. Thanks for the quick fix.
![Ekran Görüntüsü_20240925_014059](https://github.com/user-attachments/assets/05c5fefd-1d0e-415e-894d-b077dbcc29fb)
