### ISSUE TITLE
after the latest intel update, the game doesnt open and says "This version of directx is not supported by the titles, please check the system requirements." 

### ISSUE THREAD

**Issue by HI-man339** [doitsujin/dxvk#4294]
Please describe your issue as accurately as possible.
here is how it was, before dxvk: the game gave 2 fps, after DXVK: worked like normal game and i could enjoy it
Then came the latest intel update, which was on 9th of september 2024, ever since that the game is sending me the msg, "This version of directx is not supported by the titles, please check the system requirements." 
Please help, i will provide whatever necessary info i can

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Name of the game, settings used etc.: Batman arkham knight, all low settings

### System information
- GPU: Intel iris xe
- Driver: dunno
- Wine version: whats wine
- DXVK version: 2.4

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace (i tried this apitrace, it just gave the message box as, "the application was unable to start correctly, (0xc0000005). Click ok to close the application"

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

**Comment by K0bin** [comment]
There should also be a log file called something like `ArkhamKnight_d3d11.log` right next to the .exe file of the game. Can you please upload that?

**Comment by HI-man339** [comment]
@K0bin i am reinstalling the game, and then i will install, dvxk and run it again, i will send it asap

**Comment by HI-man339** [comment]
@K0bin i couldnt find the log file, here i have attached the files present, and also the message
![after dxvk](https://github.com/user-attachments/assets/3f1c71a0-5fac-49e8-8d2e-e454193598e8)
![before dxvk  2](https://github.com/user-attachments/assets/ae426f8d-c3ef-4e27-9933-f24970e0e8b5)
![before dxvk](https://github.com/user-attachments/assets/0b031e87-a9f5-4c4e-ae89-5cb91b6713f8)

i would be gratefull for your help, i really want to play this game

**Comment by K0bin** [comment]
I dont see any DXVK d3d11.dll or dxgi.dll files in your screenshot either.

**Comment by HI-man339** [comment]
@Its there, but yeah, any solution?

**Comment by Blisto91** [comment]
Show a screenshot with the dxvk files you put in the game folder

**Comment by HI-man339** [comment]
@Blisto91 @K0bin 
![image](https://github.com/user-attachments/assets/1c4635bb-dcc4-4841-93a7-497e26a39cca)

**Comment by Blisto91** [comment]
Make sure you dont have ["OpenCL, OpenGL & Vulkan Compatibility Pack"](https://github.com/doitsujin/dxvk/wiki/Windows#dozen) installed on your system

**Comment by HI-man339** [comment]
@Blisto91 its not there, i am telling yall, something was in the latest intel update that changed it because before it, everything worked perfect, do u have a discord we can talk on or smth like that, cuz this is getting tedious

**Comment by Blisto91** [comment]
If it broke with a driver update then I think you should try to report it to Intel.

**Comment by HI-man339** [comment]
@K0bin @Blisto91 there has to be some way right? to fix this?

**Comment by K0bin** [comment]
We still don't know what the issue is.

**Comment by HI-man339** [comment]
@K0bin well, i was hoping if yall could tell me what changes to make in dxvkl's directx 11 file so that it becomes compatible with directx 12 or simply change things in directx 11 file to make it directx12

**Comment by mbriar** [comment]
This game doesn't use directx12 and the problem you're having has nothing to do with directx12. I don't know why DXVK suddenly started to fail without producing any logs for you, but it most likely is some sort of driver or setup issue.

**Comment by HI-man339** [comment]
@mbriar wait, the game doesnt use directx12 , but my pc has directx12, so would that cause problem?

**Comment by HI-man339** [comment]
@K0bin @Blisto91 @mbriar ITS DONE!, ITS FIXED, I CAN PLAY IT, HAHAHAHAHA, ITS DONE,
heres what i did, i went into device manager, to display driver, updated to another driver (09/13/24) remember this date, because that update did it, i can finally play it, THANK YOU FOR YALLS HELP, IF ANYONE EVER COMEES ACROSS THIS PROBLEM AGAIN, JUST SHOW THEM THIS MSG
