### ISSUE TITLE
Incorrect shading on some 3D objects in UFO: Extraterrestrials

### ISSUE THREAD

**Issue by Snack555** [doitsujin/dxvk#4298]
Some 3D objects in the game UFO: Extraterrestrials appear very dark. The easiest way to test this is to take the tank unit on your missions as it's always rendered like this. It used to work correctly on DXVK 2.3.1 but DXVK 2.4 and 2.4.1 have this problem. I have attached a comparison screenshot below of different DXVK versions and WINED3D.

![comparison](https://github.com/user-attachments/assets/b8feef3a-7c2d-42d4-8072-10e97255261e)

### Software information
Game: UFO: Extraterrestrials (DVD edition, patch 2 applied, but still happens without the patch)
No graphical settings changed and they do not seem to have an effect on this if changed

### System information
- GPU: AMD R9 Nano
- Driver: Mesa 24.1.7
- Wine version: 9.17
- DXVK version: 2.4.1

### Apitrace file(s)
https://mega.nz/file/2d12kLDa#sQb5k1HofKW9Ft4yRuQ1NBM_vkoA_O8__VGsgYpvORM

### Log files
[UFO_ET WINE.log](https://github.com/user-attachments/files/17164397/UFO_ET.WINE.log)

**Comment by Blisto91** [comment]
Thank you for the well made issue.

I have been unable to bisect the specific commit it regresses with in the 2.4 release as a lot of the commits in between it and 2.3.1 just show the game as black in the trace.

**Comment by Blisto91** [comment]
Fixed by https://github.com/doitsujin/dxvk/commit/b99012d3323cddd357dac9c2167552bd4543322e
