### ISSUE TITLE
DXVK in Optimus Laptop

### ISSUE THREAD

**Issue by desekilibrio** [doitsujin/dxvk#430]
### Software information
World of Warcraft: Legion 7.3.5

### System information
- GPU: Optimus Laptop (Intel HD Graphics 520 + Nvidia GTX 960m)
- Driver: Intel (24.20.100.6025) / Nvidia (397.64)
- Wine version:  Not Wine - Windows 10 Pro Native
- DXVK version: 0.54

### Log files
- d3d11.log: nothing
- dxgi.log: warn: OpenVR: Failed to locate module

Hi, I have had problems trying to run World of Warcraft with DXVK. Every time I copy the dll's inside the  game folder, does not start and the 2 logs appear directly, one empty, and the other with the phrase "warn: OpenVR: Failed to locate module" eternally.

I have the Vulkan drivers installed, I also have the operating system updated, and I know that DXVK is made to be used under Linux + wine.

But, why doesn't let me initialize games on Windows 10 with all the above said? is it because it's a laptop with optimus technology (intel + nvidia)?

**Comment by GabrielMajeri** [comment]
If it is an issue with Optimus, try setting the `VK_ICD_FILENAMES` environment variable to force NVIDIA's ICD to load:

```bat
set VK_ICD_FILENAMES=C:/windows/system32/nv-vk64.json
./game.exe
```

**Comment by ssorgatem** [comment]
You can also try using VK_ICD_FILENAMES to point exclusively to the NVIDIA Vulkan ICD, so it doesn't pick up the Intel one instead.

**Comment by ssorgatem** [comment]
can you run other Vulkan apps?

**Comment by doitsujin** [comment]
Intel's Vulkan driver interacts with DXGI for some reason so it won't (ever) work with DXVK. What @ssorgatem suggested should hopefully help.

**Comment by Leopard1907** [comment]
I'm not a Windows user but DXVK worked for me on an Optimus laptop via Nvidia Prime. So maybe you should configure your Windows config like Nvidia Prime. Tried with Witcher 3. Failed with Skyrim SE though.

https://devtalk.nvidia.com/default/topic/957814/linux/prime-and-prime-synchronization/

Title is a bit misleading , that should contain Windows :D

**Comment by desekilibrio** [comment]
Hi, thanks for the quick help.
Currently try what @ssorgatem mentioned:

set VK_ICD_FILENAMES = C: /windows/system32/nv-vk64.json

When using this, the game tries to open, but I get the typical wow error that says "World of warcraft has not been able to start the 3d acceleration"

Also, the dxgi log now tells me "err: ExtensionSet :: addInstanceExtensions: Failed to query instance extensions"

What step am I missing?

**Comment by MarechalLima** [comment]
DXVK_FAKE_DX10_SUPPORT=1

**Comment by doitsujin** [comment]
@desekilibrio I suspect that the file path you entered is incorrect (i think you must use double backslashes on Windows). Not sure though.

In any case, since it's impossible for me to work around the Intel driver issues on Windows, I'm closing this.
