### ISSUE TITLE
Dark Souls 3 error 

### ISSUE THREAD

**Issue by MrWeedx3** [doitsujin/dxvk#431]
Hello i tried to install Dark Souls 3 over the Lutris installer script with enabled dxvk but the game crash at start :/

[crash.log](https://github.com/doitsujin/dxvk/files/2088082/crash.log)

- GPU:Nvidia GTX 1080
- Driver:396.24
- Wine version: 3.9-staging
- DXVK version: 0.54

**Comment by doitsujin** [comment]
Please post a stack trace. Dark Souls 3 works wine on DXVK so it must be an issue elsewhere.
