### ISSUE TITLE
Romansing Saga2 Revenge of the seven(Trial) Game data cannot save.

### ISSUE THREAD

**Issue by sakura-alice** [doitsujin/dxvk#4311]
### Software information
Romansing Saga2 Revenge of the Seven(Trial)
https://store.steampowered.com/app/2455640/_2/

Game data cannot save.

**Comment by Blisto91** [comment]
Hi there. Please fill out the issue template.
What do you mean by game data cannot save?

**Comment by Blisto91** [comment]
I just played through the demo but didn't encounter any issues.

**Comment by sakura-alice** [comment]
Ok. sorry I maybe used DXVK wrong.
It means I can't save at save points or save option settings.

![1](https://github.com/user-attachments/assets/ad80a2f1-c10a-42b2-b50d-6cf9d37617e6)
First, I can't play Romancing Saga2 Revenge of the Seven because this error massage occurred.
I couldn't start it in the normal way on Windows.

![2](https://github.com/user-attachments/assets/2feae5f2-3ed2-414b-943c-740dde4ae31e)
I heard on WEB that if I port the DLL like this, the Steam game will work on Windows.
Romancing Saga2 Revenge of the Seven works, but it makes no save data.

**Comment by qinlili23333** [comment]
If the game runs, then the save issue shouldn't be related to DXVK. DXVK does nothing about game's IO.
Please ask game developer for support. And I suggest to use [https://learn.microsoft.com/en-us/sysinternals/downloads/procmon](Process Monitor) to check game's IO actions.

**Comment by sakura-alice** [comment]
![3](https://github.com/user-attachments/assets/1b7f4a42-e647-490a-a797-a3d207adde0a)

Good! I see PATH NOT FOUND error.

**Comment by sakura-alice** [comment]
I found two errors, ”NAME NOT FOUND” and "PATH NOT FOUND".
So I have no way to solve.

**Comment by qinlili23333** [comment]
> ![3](https://private-user-images.githubusercontent.com/183497548/372717770-1b7f4a42-e647-490a-a797-a3d207adde0a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NTAxNzEsIm5iZiI6MTcyNzg0OTg3MSwicGF0aCI6Ii8xODM0OTc1NDgvMzcyNzE3NzcwLTFiN2Y0YTQyLWU2NDctNDkwYS1hNzk3LWEzZDIwN2FkZGUwYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQwNjE3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDg0NjMwOThmZmM5ZGIwYzFkYjI5MDE3NzU1NzJhZmU5N2RhMGYwYjMwYTAwZTA3ZDRiMzE2ZTE5ZGI2YTQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1ChnwFp7plbLyEgfguNdId4rfYty-dUc7cXf4euBdTk)
> 
> Good! I see PATH NOT FOUND error.

The game seems cannot create folder. Is your username "user"? Can you find the path manually?

**Comment by qinlili23333** [comment]
![image](https://github.com/user-attachments/assets/55307ae1-1c7a-4ae8-a54b-8a1d0131595a)
This is a normal condition for reference. CreateFile should return NAME NOT FOUND (which means the file doesn't exist and can be created). PATH NOT FOUND is returned when the target folder doesn't exist.

**Comment by K0bin** [comment]
DXVK has nothing to do with saving and the "Low Level Fatal Error"-Popup you saw is probably caused by your Vulkan driver missing features that DXVK requires. As Blisto said, please fill out the issue template and provide info like your GPU, your driver version, DXVK logs, etc.

**Comment by sakura-alice** [comment]
I think "Vulkan driver" word is a hint.
Now I have a dark connection out problem of NVIDIA driver.
NVIDIA new 561.09 driver kills my monitor. So I can't use it.
I use 536.23 driver now.
I use GeForce GTX 1650. I paid 200 dollars.
I wrote this word, audience said  "Your GPU is cheap and garbage. Pay 2000 dollars and buy new Gaming BTO PC" in our country.

**Comment by qinlili23333** [comment]
> I think "Vulkan driver" word is a hint. Now I have a dark connection out problem of NVIDIA driver. NVIDIA new 561.09 driver kills my monitor. So I can't use it. I use 536.23 driver now. I use GeForce GTX 1650. I paid 200 dollars. I wrote this word, audience said "Your GPU is cheap and garbage. Pay 2000 dollars and buy new Gaming BTO PC" in our country.

536.23 is too old. Try 560.81 if 561.09 cannot use.

**Comment by sakura-alice** [comment]
I found 555.85 is useable. I installed.
But same error massage occurred when I started the game in the normal way.

**Comment by K0bin** [comment]
Please upload DXVK logs. Otherwise we cannot do anything for you.

**Comment by sakura-alice** [comment]
[Romancing SaGa 2 RotS Demo-Win64_d3d11.log](https://github.com/user-attachments/files/17229941/Romancing.SaGa.2.RotS.Demo-Win64_d3d11.log)
[Romancing SaGa 2 RotS Demo-Win64_dxgi.log](https://github.com/user-attachments/files/17229943/Romancing.SaGa.2.RotS.Demo-Win64_dxgi.log)

 d3d11.log and dxgi.log

**Comment by sakura-alice** [comment]
I solved problems. This app blocked by windows defender. Thanks for everyone.
