### ISSUE TITLE
Garry's mod NPC motion problem...?

### ISSUE THREAD

**Issue by SakuraRK** [doitsujin/dxvk#4312]
When I use the latest dxvk on Garry's mod, I find the NPC motion look like low framerate.
I never seen that problem on native DirectX 9+ mode.
[I upload a video to bilibili about this problem](https://www.bilibili.com/video/BV15w4NewE3s/)

### Software information
Garry's mod x86-64 branch, DirectX 9 Mode
CPU: Intel(R) Core i5-10400 2.9GHz@4.00GHz(Locked the clock boosted all Core)
48GBytes(16+32 2 ways) 3200MT/s DDR4
### System information
- Rendering GPU: Tesla P40 without ECC, WDDM+TCC Mixed Mode
- Output iGPU: Intel UHD Graphics 630
- Driver: P40--31.0.15.3713(GRID Driver) UHD630--31.0.101.2128
- Wine version: Native Windows
- DXVK version: 2.4.1(Latest)

### Apitrace file(s)
It actually NOT property work(haven't catch ANY apitrace) on my PC.
So I ingore it. Sry *_*
### Log files
[gmod_d3d9.log](https://github.com/user-attachments/files/17211371/gmod_d3d9.log)

**Comment by K0bin** [comment]
I don't have any experience with GMod, so we **really** need that apitrace. Can you please try looking into it again?

**Comment by HunterCZ122** [comment]
Can you try increasing cl_interp_npcs or cl_interp?

**Comment by SakuraRK** [comment]
> Can you try increasing cl_interp_npcs or cl_interp (console commands)?
I usually set the cl_interp to 0.

**Comment by SakuraRK** [comment]
> Can you try increasing cl_interp_npcs or cl_interp (console commands)?

On steam arg

**Comment by HunterCZ122** [comment]
> I usually set the cl_interp to 0.

I think that's the problem. cl_interp 0 will make all NPCs laggy asf since it disables animation interpolation. Set it back to cl_interp 0.1.

**Comment by SakuraRK** [comment]
https://mega.nz/file/zz5gXY7R#Zfy8WQYPa9UqgDeswoYqO-PQRpS6Sct1u0JJ-rPBvFw
apitrace here (Mega) and maybe you(r) can find other problem.

**Comment by SakuraRK** [comment]
> https://mega.nz/file/zz5gXY7R#Zfy8WQYPa9UqgDeswoYqO-PQRpS6Sct1u0JJ-rPBvFw apitrace 这里 （Mega），也许您 （r） 可以找到其他问题。

@HunterCZ122 @K0bin
