### ISSUE TITLE
meson.build:42:2: ERROR: Problem encountered: Missing Vulkan-Headers

### ISSUE THREAD

**Issue by LUser-12** [doitsujin/dxvk#4321]
Hello so i am trying to setup wine manually to play a game and so when i use thios command

./package-release.sh master /your/target/directory --no-package

i get this Error : 
Check usable header "vulkan/vulkan.h" : NO 

meson.build:42:2: ERROR: Problem encountered: Missing Vulkan-Headers

and i am on Pop-OS 22.04
cpu: intel core i7 8550U
igpu : uhd graphics 620

**Comment by Blisto91** [comment]
`git submodule update --init --recursive` should solve it.

Remember to clone with submodules https://github.com/doitsujin/dxvk#build-instructions

**Comment by LUser-12** [comment]
fixed it thank you

**Comment by LUser-12** [comment]
> `git submodule update --init --recursive` should solve it.
> 
> Remember to clone with submodules https://github.com/doitsujin/dxvk#build-instructions

hey so now i got a new error which is : 
meson.build:176:0: ERROR: Program 'glslang glslangValidator' not found or not executable

**Comment by Blisto91** [comment]
That is a system package dependency you need to install https://github.com/doitsujin/dxvk#requirements
I don't know what it is called on Pop-OS

**Comment by LUser-12** [comment]
ok ty

**Comment by Blisto91** [comment]
Maybe `glslang-tools`

**Comment by LUser-12** [comment]
> Maybe `glslang-tools`

now when i use this command ./package-release.sh master /your/target/directory --no-package
i get a jumble of incoherent text and this error: ninja: build stopped: subcommand failed.

**Comment by Blisto91** [comment]
Attach the text in a file or GitHub gist.

And just in case, note that you should replace `/your/target/directory` with a path to a directory you want the files to build in to.

**Comment by LUser-12** [comment]
[log.txt](https://github.com/user-attachments/files/17259205/log.txt)
and yesy i know i need to rplace the path

**Comment by Blisto91** [comment]
For those errors see this section https://github.com/doitsujin/dxvk#build-troubleshooting

**Comment by LUser-12** [comment]
> For those errors see this section https://github.com/doitsujin/dxvk#build-troubleshooting

so when i choose the posix alternate it tells me Permission Denied :
update-alternatives: error: error creating symbolic link '/etc/alternatives/x86_64-w64-mingw32-gcc.dpkg-tmp': Permission denied

**Comment by Blisto91** [comment]
You likely need to run it with `sudo` to get elevated privileges

**Comment by LUser-12** [comment]
> You likely need to run it with `sudo` to get elevated privileges

did it and all worked but now i got another error
[log.txt](https://github.com/user-attachments/files/17259951/log.txt)

**Comment by Blisto91** [comment]
I don't know specifically how to solve that issue as i have never encountered it on Arch, but you can try some of the things suggested in https://github.com/doitsujin/dxvk/issues/3328

**Comment by LUser-12** [comment]
ah thank you for all of your time

**Comment by LUser-12** [comment]
> I don't know specifically how to solve that issue as i have never encountered it on Arch, but you can try some of the things suggested in #3328

hey so i fixed it i looked at mingw-w64 and it was on v.8.0.0 so i manualy installed these deb pkg
https://packages.ubuntu.com/noble/mingw-w64-common
https://packages.ubuntu.com/noble/mingw-w64-i686-dev
https://packages.ubuntu.com/noble/mingw-w64
https://packages.ubuntu.com/noble/mingw-w64-x86-64-dev
