### ISSUE TITLE
native: Add SDL3 WSI backend

### ISSUE THREAD

**Issue by flibitijibibo** [doitsujin/dxvk#4323]
SDL 3.1.3 was released today, and the ABI has been frozen! Making an SDL3 backend should now be safe - we can copypaste most of SDL2 and just fix the small bits that dxvk depends on (I think only monitor enumeration changed significantly, everything else is pretty much the same).

**Comment by doitsujin** [comment]
Sounds good, currently drowned in work but this is the kind of thing we should be able to do before the next release.
