### ISSUE TITLE
I want to use wine and dxvk to play a game

### ISSUE THREAD

**Issue by LUser-12** [doitsujin/dxvk#4324]
hello the issue is whenever i install the dxvk directory there is no file called setup-dxvk.sh so how can i do what i want to do now?

### Software information
POPOS!

### System information
- iGPU:uhd graphic 620
- Wine version: wine-9.18
- DXVK version: dxvk v2.4.1

**Comment by mbriar** [comment]
https://github.com/doitsujin/dxvk#how-to-use

**Comment by K0bin** [comment]
Follow the guide in the README that mbriar posted.

**Comment by LUser-12** [comment]
ah ok thank you
