### ISSUE TITLE
Middle Earth Shadow of War - Incorrect Resolution 

### ISSUE THREAD

**Issue by elogicuk** [doitsujin/dxvk#4330]
Unable to select the correct resolution in game.
Because of this it tries to enable Dynamic Resolution even when its disabled, and it makes my game downscale the graphics and it looks awful like a ps2 game. My screen is 21:9 3440x1440 and the game tries to tell me its 1290 x 540 (check screenshot)

### Software information
Middle Earth Shadow of War 1.2.0 Latest version 

### System information
- GPU: NVIDIA GeForce RTX 4070
- Driver:  560.35.03
- Wine version:  Tried new and old versions, same results 
- DXVK version:  2.4.1

Even after manually editing the config file located here ~/Games/middle-earth-shadow-of-war/drive_c/users/home/Local Settings/Application Data/WB Games/Shadow of War/render.cfg

"ScreenHeight16by9" "1440.000000"
"ScreenWidth16by9" "3440.000000"

![Screenshot from 2024-10-07 15-28-57](https://github.com/user-attachments/assets/c7260f6c-d898-4b83-b71a-9cfac107c78b)

**Comment by Blisto91** [comment]
Hi there.
Does this  work with wined3d or older dxvk?

**Comment by K0bin** [comment]
DXVK gets the resolutions directly from the responsible Windows API, so directly from Wine.

Besides that, for this kind of issue, it would be interesting to know your desktop environment and whether you use Wayland or X11.

**Comment by elogicuk** [comment]
> DXVK gets the resolutions directly from the responsible Windows API, so directly from Wine.
> 
> Besides that, for this kind of issue, it would be interesting to know your desktop environment and whether you use Wayland or X11.

DE: GNOME 46.4
WM: Mutter (X11)

**Comment by elogicuk** [comment]
> Hi there. Does this work with wined3d or older dxvk?

tried dxvk as early as 2.1, no change

**Comment by Blisto91** [comment]
Could you try wined3d out of interest.

**Comment by elogicuk** [comment]
> Could you try wined3d out of interest.

im not sure how todo that, im using lutris right now (if you can show me how, i will try and report back)

**Comment by elogicuk** [comment]
> Could you try wined3d out of interest.

a quick google search lead me to this

"Disable DXVK under Runner Options for that game/wine prefix? I’d think it would then default to WineD3D"

I tried this, and it made no difference sadly :(

**Comment by elogicuk** [comment]
I also tried running a virtual desktop of 3440x1400 in lutris, made no difference :-1:

**Comment by Blisto91** [comment]
If it properly switches to wind3d and it is also broken there then this is likely not a dxvk issue yeah.

**Comment by K0bin** [comment]
Sorry, in that case I can't help you.
