### ISSUE TITLE
Enhanced API support

### ISSUE THREAD

**Issue by qemuduewr** [doitsujin/dxvk#4331]
Is it possible to support d3d12 so that you don't have to install vkd3d or support older versions than d3d8?

**Comment by Blisto91** [comment]
It is possible yes. Will it happen? No
There is no reason for dxvk to implement d3d12 when vkd3d-proton exists, which the devs also contribute to.

In regards to Apsis lower than d3d8 see https://github.com/doitsujin/dxvk/issues/4199#issuecomment-2278648019

**Comment by K0bin** [comment]
Older versions than D3D8 are part of DirectDraw. That's why there are no plans to support anything older than D3D8.

As for D3D12: the API is more low level than older D3D APIs which is why it does not make sense to implement it as part of DXVK.  That said, @doitsujin is one of the primary developers of VKD3D-Proton. (https://github.com/HansKristian-Work/vkd3d-proton/graphs/contributors)

**Comment by qemuduewr** [comment]
Or DXVK is integrated with VKD3D, just as D8VK is integrated with DXVK

**Comment by qemuduewr** [comment]
> low

Or DXVK is integrated with VKD3D, just as D8VK is integrated with DXVK

**Comment by qemuduewr** [comment]
Or DXVK is integrated with VKD3D, just as D8VK is integrated with DXVK

**Comment by Blisto91** [comment]
vkd3d-proton and dxvk have different licenses and programming languages. Besides that the APIs are different enough, d3d12 is much lower level as @K0bin wrote, that it makes sense for them to be separate projects.

**Comment by qemuduewr** [comment]
If it can be integrated, there is no need to install multiple different versions to reduce conflicts

**Comment by K0bin** [comment]
There aren't any conflicts anyway and installing DLLs from two different projects is really not such a big deal...

**Comment by qemuduewr** [comment]
As for the support of D3D7 and below versions, it is to consider the minority needs of mobile phones, and dxvk is used in the mobile phone wine container. ...

**Comment by K0bin** [comment]
Phones are not a target platform of DXVK.

**Comment by qemuduewr** [comment]
This project ishttps://github.com/olegos2/mobox

**Comment by qemuduewr** [comment]
I know that this DXVK is to meet the needs of playing computer games without a computer, not to mention cloud gaming ...
