### ISSUE TITLE
Fallout 4: xact overrides crash DXVK

### ISSUE THREAD

**Issue by sputniktr02** [doitsujin/dxvk#434]
I cannot use DXVK with xact overrides, game crashes on launch. Both xact and DXVK works separately but not together.
Any ideas?
### Software information
Fallout 4 Game of The Year (Cracked copy to test it if it's worth buying)
I am using PlayonLinux with wine builds from Lutris

### System information
- GPU: Nvidia GTX 860m
- Driver:396.24.02
- Wine version: 3.7, 3.8, 3.9 (Also Staging)
- DXVK version: 0.51 to 0.54
- OS: Kubuntu 18.04

### Log files
- d3d11.log: 

> info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
warn:  D3D11Device: No matching border color found for (-3.40282e+038,0,0,0)

- dxgi.log: 

> warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_win32_surface
info:    VK_KHR_surface
info:  GeForce GTX 860M:
info:    Driver: 396.24.2
info:    Vulkan: 1.1.73
info:    Memory Heap[0]: 
info:      Size: 2048 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 11969 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
warn:  Vulkan extension VK_EXT_vertex_attribute_divisor not supported
warn:  Vulkan extension VK_EXT_shader_viewport_index_layer not supported
warn:  Vulkan extension VK_KHR_maintenance2 not supported
info:  Enabled device extensions:
info:    VK_KHR_swapchain
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_maintenance1
info:    VK_KHR_sampler_mirror_clamp_to_edge
warn:  DXGI: MakeWindowAssociation: Ignoring flags
info:  DxgiVkPresenter: Recreating swap chain: 
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_FIFO_KHR
  Buffer size:  1360x768

**Comment by doitsujin** [comment]
Can you post a stack trace to see where the crash happens?

There's almost certainly nothing I can do about it though because DXVK doesn't interact with any of the sound APIs.

**Comment by sputniktr02** [comment]
This is the wine backtrace:
[backtrace.txt](https://github.com/doitsujin/dxvk/files/2089650/backtrace.txt)

**Comment by doitsujin** [comment]
Try setting `xaudio2_7` to `native`. Anyway, not my bug.

**Comment by sputniktr02** [comment]
It was set to native, that what fixes audio in Fallout 4 but it does not work with DXVK for some reason. Anyway thanks for the quick reply though.

**Comment by aeikum** [comment]
@sputniktr02 Native xaudio2 is broken in Wine, unfortunately. See winehq bug 38668, especially comment 72.

**Comment by sputniktr02** [comment]
@aeikum Thanks for the info. It also seems like a pretty weird bug. I hope it gets fixed.

**Comment by hiigaran** [comment]
I've noticed that DXVK v0.6x and v0.7 all crash on startup of FO4 with xaudio2_7 set to native in wine-staging 3.13. However, v0.54 does load. Everything seems to go well, but once the game world loads, all sound/music/voices will cease to work anywhere from a few seconds to a few minutes in. None of the audio will abruptly cut out though. For example, if music is playing past the point where no new audio plays, it will continue playing until it finishes.
Running FO4 with xaudio2_7 at native without DXVK results in no audio issues. This seems odd, given that DXVK is a graphical project.
Also, Skyrim works with xaudio2_7 and v0.54. Not sure what to do with that information, but I'm sure it's significant enough to note.

**Comment by doitsujin** [comment]
Unless the crash happens in D3D11 code I can't really do much about it.
