### ISSUE TITLE
[d3d8] Still Life light flickering (regression)

### ISSUE THREAD

**Issue by WinterSnowfall** [doitsujin/dxvk#4340]
There's some light flickering noticeable on the in-game character models that wasn't there before.

It's present with dxvk 2.4 as well, and since this is a d3d8 game it won't be possible to bisect it beyond that. All I can say is that everything looks fine with d8vk 1.0 (which was based off of dxvk 2.3.1 IIRC).

I've captured a trace which reproduces the issue anyway, so hopefully that is enough to pinpoint it.

### Software information
Still Life

### System information
- GPU: Intel Xe-LP
- Driver: Intel open-source Mesa driver 24.0.9
- Wine version: 9.17 Staging
- DXVK version: Latest, but have tested as far back as 2.4.

### Apitrace file(s)
[StillLife.trace.tar.xz](https://drive.proton.me/urls/1XHH9QKPR8#dhQH7nAczL4P)

### Log files
[StillLife.log](https://github.com/user-attachments/files/17318070/StillLife.log)

**Comment by WinterSnowfall** [comment]
P.S.: I've tried reverting 9e422a2 and da81466 for good measure, but neither have caused the issue.

**Comment by K0bin** [comment]
Was it fine with D8VK before the merge?

**Comment by K0bin** [comment]
Bisected by Blisto to https://github.com/doitsujin/dxvk/commit/df9bdfc6ea248200558f1f64961f558097e04b1a
