### ISSUE TITLE
Game-compatibility.md is removed

### ISSUE THREAD

**Issue by xunto** [doitsujin/dxvk#436]
Why did ```Game-compatibility.md``` get removed from wiki? I know that someone used this table, so what is intent of doing so? Is there any alternative source of such information?

**Comment by doitsujin** [comment]
I removed the compatibility list because it turned out that more than half the games listed there *do not actually work* with DXVK, either due to major bugs or missing features. I'm not okay with falsely advertizing support for games which are not playable without major issues.

**Comment by xunto** [comment]
@doitsujin so DXVK isn't stable enough for now to recreate this table? I mean that is that because some games can stop working between DXVK versions or you just don't have time to recreate table in the right way?

**Comment by soredake** [comment]
https://ethercalc.org/1d9vtis8r2eb

**Comment by shmerl** [comment]
@xunto: Feel free to update and submit fixes to [this list](https://www.gamingonlinux.com/wiki/DXVK_Compatibility_List). It references testing context rather than simply a game.

**Comment by doitsujin** [comment]
@xunto My main issues with  compatibility list are:
- it needs to be maintained and updated (like the Far Cry 5 rendering issues listed in the GoL wiki - I fixed those over a month ago)
- the games on there need to be thoroughly tested. Claiming that games like Sleeping Dogs are "compatible" when in fact it *doesn't even start* is straight-up false advertizing.

The list we had in the wiki was actually not my own doing but the courtesy of someone else, but it listed a lot of games that are completely unplayable or had major stability issues. Also, a Markdown table is fairly limited in what it can express,. so it wasn't exactly a suitable format.
