### ISSUE TITLE
Battle Eye keeps blocking dxvk on GTA V 

### ISSUE THREAD

**Issue by thescalator** [doitsujin/dxvk#4365]
Battle Eye blocks one of the dxvk files while trying to open GTA V. Is there any way to bypass it?

**Comment by Blisto91** [comment]
Launch with `-nobattleye`

**Comment by thescalator** [comment]
I can turn it off using the launcher, but it doesn't allow me to play GTA Online. GTA Online's performance is a mess without Vulkan

**Comment by doitsujin** [comment]
Anticheat working as intended, not much we can do here.
