### ISSUE TITLE
DXVK woks on some games on Radeon RX480 but not on RX VEGA 64

### ISSUE THREAD

**Issue by giovannilaura** [doitsujin/dxvk#437]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

Game THe long Journej home after selectint training in the start menu game crashes on vega but not on RX480
This happen also for Quantum Break and Just Cause 3

### Software information
The long Journey home mesa git llvm git dxvk git wine 3.10

### System information
- GPU:Vega 64
- Driver:mesa GIT
- Wine version: 3.10
- DXVK version: GIT

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log: 
[tljh-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/2099936/tljh-Win64-Shipping_d3d11.log)
[tljh-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/2099937/tljh-Win64-Shipping_dxgi.log)

WINE LOG
[tljh_rx480.txt](https://github.com/doitsujin/dxvk/files/2099941/tljh_rx480.txt)
[tljh_vega.txt](https://github.com/doitsujin/dxvk/files/2099942/tljh_vega.txt)

**Comment by doitsujin** [comment]
Hm, looks like DXVK is generating broken shaders in some cases. Plaase run one of the games with the following environment variables set:
```
DXVK_LOG_LEVEL=debug
DXVK_SHADER_DUMP_PATH=$HOME/shaders
```
Note that you have to create `$HOME/shaders` manually first. Please post the resulting `d3d11.log`.

**Comment by giovannilaura** [comment]
I guess You are right
here the log

[tljh-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/2100249/tljh-Win64-Shipping_d3d11.log)

**Comment by doitsujin** [comment]
Did that run crash? Doesn't look like it.

In that case, please run
```
cd $HOME/shaders
find . -name "*.spv" | parallel 'spirv-val {} || echo {}'
```
and let me know if it outputs anything.

**Comment by giovannilaura** [comment]
it doese output nothing
here the log of the run
[tljh-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/2101543/tljh-Win64-Shipping_d3d11.log)
cheers

**Comment by giovannilaura** [comment]
it crashes

**Comment by giovannilaura** [comment]
i do not know if it can help but on the rx 480 it does still not output something but it runs with following log
[tljh-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/2101702/tljh-Win64-Shipping_d3d11.log)

**Comment by doitsujin** [comment]
Well, if there's no output, the shaders are all valid. Not sure what's going on there but this doesn't really look like a dxvk bug.

**Comment by giovannilaura** [comment]
it was indeed a mesa radv bug the devs sent me a patch link with this patch the bug is fixed

**Comment by doitsujin** [comment]
okay, closing the issue then.
