### ISSUE TITLE
World of tanks/ Wargaming gamelauncher runtime error 

### ISSUE THREAD

**Issue by Wayturns** [doitsujin/dxvk#4370]
On starting wargaming launcher I get c++ runtime error if I use DXVK but when I launch the game it self it works just fine how ever if I disable DXVK in lutris I don't get issues in launcher but game starts runing at 45 fps instead of 156 fps

### Software information
World of tanks/ Wargaming gamelauncher
Through lutris

### System information
- GPU: RTX 2060
- Driver: 560.35.03  
-NVML version: 12.560.35.03
- Wine version: Wine-ge 8.26_x84_64
- DXVK version: 2.4.1

![image](https://github.com/user-attachments/assets/cc73fc21-8170-4b25-8405-087a149b21cc)

**Comment by doitsujin** [comment]
Try an older wine build or an older Nvidia driver, the combination of 560 drivers + recent wine is known to have issues.

**Comment by Wayturns** [comment]
> Try an older wine build or an older Nvidia driver, the combination of 560 drivers + recent wine is known to have issues.

Thanks that actually worked I switched to most recent wine-lutris 7.2-2 version and it worked great
