### ISSUE TITLE
(Hosting request) Create a Radicle backup and mirror to protect your development

### ISSUE THREAD

**Issue by hardBSDk** [doitsujin/dxvk#4372]
[Radicle](https://radicle.xyz/) is a platform for peer-to-peer Git repositories, your repository works like a torrent where anyone can be a seeder of your code.

This will increase the download speed, add a backup and protect the project from GitHub problems.

**Comment by WinterSnowfall** [comment]
... I think all dxvk developers have local clones of the repository (git is distributed in its very nature anyway), so even if let's say disaster would strike and GitHub would suddenly vanish off the face of the world, it wouldn't be that big of a problem. Anyway, just my 2 cents.

**Comment by K0bin** [comment]
There's even an ancient version of DXVK in GitHubs arctic vault, so even if civilization ended, we could still render D3D11 games on Linux. :)
