### ISSUE TITLE
[d3d11] Baldur's Gate 3 Modding Toolkit Blank Sub-Windows

### ISSUE THREAD

**Issue by Cr-nch** [doitsujin/dxvk#4374]
Although 3D rendering works correctly for some sub-windows in the toolkit, the main game window remains blank, using the previous frames' buffer information to fill it in, resulting in a blank sub-window. The game also does not take mouse input when attempting to interact with it.

On my hardware, a black window appears in the top left of the screen which has the same size as the main game viewport. This box strangely seems to capture input and focus of the main game window, or be completely ignored depending on which application I place underneath it.

### Software information
Baldur's Gate 3 Modding Toolkit, running by instructions found here as the program does not launch otherwise: https://discord.com/channels/98922182746329088/1282031634954326066/1282031634954326066

### System information
- GPU: Radeon 7700S
- Driver: amdgpu
- Wine version: Using Proton 9.0-3, and hence wine-9.0.
- DXVK version: Proton 9.0-3, d0ea5a4a87c9b4ee8a7d700c5f55baf26054bd6a dxvk (v2.4-40-gd0ea5a4a)
- Proton Version: 9.0-3
Note: Multiple versions of Proton, including various proton-tkg and proton-GE builds, and Proton Experimental have the same issue.

### Apitrace
I couldn't get an Apitrace as it entirely broke the application, not even making it to the loading screen, I can try to get them again if needed.

### Log files
[steam-2934770.log](https://github.com/user-attachments/files/17405247/steam-2934770.log)
Please ignore the crash at the end, it happens every time I quit the application.

### Screenshots
![Screenshot_20241017_125938](https://github.com/user-attachments/assets/23f57847-6f86-46ad-a7bc-327765870389)
The black box does seem to actually be there to render something, as this showed up once while I was doing some experimentation:
![image](https://github.com/user-attachments/assets/b089ce86-06fb-45ae-8235-1776309791c6)

**Comment by Cr-nch** [comment]
I decided to see if RenderDoc could help diagnose any issues, it basically has just confirmed that, yes, the game is rendering correctly at some point, and it also takes only keyboard input. ![image](https://github.com/user-attachments/assets/fdebfa2e-d5d4-4882-8f10-8e9413c7fc8c)

**Comment by xStiven** [comment]
For what is worth dude from BG3 tool thread said "I used the wine-tkg version that has the **child window rendering fix** (or whatever its called), then used winetricks and set the renderer as vulkan". I tried tkg but the app wont even launch for me.

**Comment by Cr-nch** [comment]
> For what is worth dude from BG3 tool thread said "I used the wine-tkg version that has the **child window rendering fix** (or whatever its called), then used winetricks and set the renderer as vulkan". I tried tkg but the app wont even launch for me.

I had issues with getting it to work, if you get to the loading screen and it crashes after "flushing dispatcher" it's an issue related to installed fonts because of some Microsoft runtime that looks for some specific default fonts.

I've found running `winetricks fontfix` in the prefix tends to fix that issue.

**Comment by Cr-nch** [comment]
> Does this work on current master? We implement sequential swap effects there which might be part of the problem.
> 
> Could also be that the thing needs partial presentation implemented, which we do not support currently.
> 
> Could _also_ be an entirely different problem.

To a very very weird extent. With the tooltips fix I tried building from the current commit and it still won't display anything in the main game window, the black box is still present in the top left corner of my screen. Other 3D rendering works:
![image](https://github.com/user-attachments/assets/cbbd0607-569c-4336-b923-bd16cc20342a)

Without the tooltips fix (the one where you disable hardware rendering for the UI, re-enabling this runs everything through dxvk) I managed to get the game to work _with mouse input_ after closing the other windows and dragging the editor around on my screen which cleared some of the garbage data. Huge progress but I'm also so confused. I'll try get a screen recording of what happened.
![image](https://github.com/user-attachments/assets/349179a4-ec70-4d9e-aeb3-6896801e9a50)
![image](https://github.com/user-attachments/assets/fe2968cd-0968-4b71-b58f-3e79e7e047dd)

**Comment by Cr-nch** [comment]
Apologies for the fairly grotesque capture, but I think it illustrates my point well enough. Moving the window (seems more erratically the better) somehow manages to clear some of the screen and makes it interactable.
![image](https://github.com/user-attachments/assets/5051148f-0031-4f9e-9bba-f35ee22cce05)
[Screencast_20241018_091056.webm](https://github.com/user-attachments/assets/3fe5cb8a-4eff-4fdc-8956-6bcde361eaac)

**Comment by xStiven** [comment]
> > Does this work on current master? We implement sequential swap effects there which might be part of the problem.
> > Could also be that the thing needs partial presentation implemented, which we do not support currently.
> > Could _also_ be an entirely different problem.
> 
> To a very very weird extent. With the tooltips fix I tried building from the current commit and it still won't display anything in the main game window, the black box is still present in the top left corner of my screen. Other 3D rendering works: ![image](https://private-user-images.githubusercontent.com/57434983/377635986-cbbd0607-569c-4336-b923-bd16cc20342a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMDMwODMsIm5iZiI6MTcyOTIwMjc4MywicGF0aCI6Ii81NzQzNDk4My8zNzc2MzU5ODYtY2JiZDA2MDctNTY5Yy00MzM2LWI5MjMtYmQxNmNjMjAzNDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDIyMDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZmJmMzQ4NDRiMGQ5MDI4MTE2ZDk5ODA1OGFmMGY4MDM1YmQ3ZThjMjc0OGIyN2RhOTI3ODMwM2RjMGUwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GIG7J-JsL00ve6K9Iuu5p4f1uxQDMo1FTX9Cv5eA5NE)
> 
> Without the tooltips fix (the one where you disable hardware rendering for the UI, re-enabling this runs everything through dxvk) I managed to get the game to work _with mouse input_ after closing the other windows and dragging the editor around on my screen which cleared some of the garbage data. Huge progress but I'm also so confused. I'll try get a screen recording of what happened. ![image](https://private-user-images.githubusercontent.com/57434983/377647139-349179a4-ec70-4d9e-aeb3-6896801e9a50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMDMwODMsIm5iZiI6MTcyOTIwMjc4MywicGF0aCI6Ii81NzQzNDk4My8zNzc2NDcxMzktMzQ5MTc5YTQtZWM3MC00ZDllLWFlYjMtNjg5NjgwMWU5YTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDIyMDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOWZlMDMzNzBjNzRlODQ5NTI0OGRiZDMyY2RlNmZkMDlmZmEyNGQ4ZTJhNzU3YmE5ZDU2ZDY3NjczNmJhYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.agV7MBKUKmW1r2vqwDdM5pulvzJZ5-f8SuqgzXUd62s) ![image](https://private-user-images.githubusercontent.com/57434983/377647300-fe2968cd-0968-4b71-b58f-3e79e7e047dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMDMwODMsIm5iZiI6MTcyOTIwMjc4MywicGF0aCI6Ii81NzQzNDk4My8zNzc2NDczMDAtZmUyOTY4Y2QtMDk2OC00YjcxLWI1OGYtM2U3OWU3ZTA0N2RkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDIyMDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmODM5ZWNjNzUwMmMwOGYxOGVkYmUwMjRmMGE0ODg4NTI1M2Y0ZTExZjIxNTlkNDZhN2UwNDk4MWIzMmUxODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eDK10b87nYF9PceBWdZEcL2mv7qfxWvXrcFNlKmAZE8)

Did you tried to follow suggestion from the dude on the discord? I see in your OP post that you tried all sorts of wine flavors but did you tried to set render to vulkan for the BG3 Toolkit prefix? Im asking because, im trying to figure it out, too. If you tried then we can cross-out, that possibility.

**Comment by Cr-nch** [comment]
> Did you tried to follow suggestion from the dude on the discord? I see in your OP post that you tried all sorts of wine flavors but did you tried to set render to vulkan for the BG3 Toolkit prefix? Im asking because, im trying to figure it out, too. If you tried then we can cross-out, that possibility.

I already do have it set to Vulkan, yes
![image](https://github.com/user-attachments/assets/cb33f39f-b14d-46a3-ae10-a7458478de6d)

**Comment by Blisto91** [comment]
I am not 100% certain that this is a dxvk issue, especially since it behaves the same with wined3d.
On Windows the game view can show fine with dxvk

<details>
  <summary>Screenshot</summary>
  
![image](https://github.com/user-attachments/assets/8ee92ed7-c590-4620-a6b3-1a189fec21f6)
</details>

Though an extra note about dxvk on Windows is that if you minimize and open the toolkit Window again then the game view will for some reason switch to D3DEx instead of D3D11 and showing black before crashing.
Though i wouldn't necessarily chain that together with the issue on Linux as with such a complex app there is bound to be some dxvk issues on Windows instead of Proton. Also on Linux i can never even get the hud to show in the game viewport.

**Comment by eszlari** [comment]
Maybe this Wine MR (merged in 9.18) fixes this: https://gitlab.winehq.org/wine/wine/-/merge_requests/6467

**Comment by Blisto91** [comment]
Vulkan child Window rendering is already implemented in Proton

**Comment by eszlari** [comment]
Maybe the upstream implementation is more robust?

**Comment by Cr-nch** [comment]
For what it's worth, keeping hardware acceleration on (which means the UI is rendered with dxvk) does cause other issues seemingly unrelated to the game not showing. But it's still hard to confirm what exactly is causing this

I have found some other weird rendering bugs related to the 3D windows, that could probably be related to the wine issue (at the end of the clip, moving the windows to the left of the screen causes them to move away). This video also better showcases the workaround.
https://github.com/user-attachments/assets/0f4748fa-ced5-4129-8a02-1bbcc11cdfc7

I'll see what I can do about building wine from source, though it's probably good to note that I have tried proton--tkg which does (afaik) use more up to date Wine versions.

**Comment by eszlari** [comment]
> I'll see what I can do about building wine from source, though it's probably good to note that I have tried proton--tkg which does (afaik) use more up to date Wine versions.

They merged this about a month ago: https://github.com/Frogging-Family/wine-tkg-git/pull/1257

You could also try the Wayland driver, Wine 9.19 has this MR: https://gitlab.winehq.org/wine/wine/-/merge_requests/6323

**Comment by Cr-nch** [comment]
> They merged this about a month ago: https://github.com/Frogging-Family/wine-tkg-git/pull/1257
Tried a proton-tkg version built 2 hours ago, still has the bug. Had no luck getting the wayland driver working on it either so I'm now going to try running the toolkit through pure Wine and dxvk.

**Comment by Cr-nch** [comment]
Should probably just mention, in relation to Blisto's comment that it also happens in wined3d

While that is true, running the toolkit in dxvk allows for the window shaking workaround (while having other rendering errors), while wined3d (with a more stable general UI) doesn't seem to have any way to fix it. I'll try experiment with wined3d to see if I can get it working there or not to get something more conclusive though.

I also think it's quite strange that the black box moves when the window is moved in specific ways. In fact, I was able to get the box completely off screen and the game window was rendering perfectly normally, and was functional. It seems that whatever portion of the top left of the screen (an invisible rectangle bounded by the game window's size) is covered by the box shows nothing.

Also update on trying to run it through wine separately, I'll admit I'm fairly new to this and have no idea what I'm doing beyond getting wine 9.19 installed and running. I'm a bit low on free time these next few days but I'll keep at it though. Worse comes to worst I can still use the workaround.

**Comment by xStiven** [comment]
So, any updated on this subject?

**Comment by Cr-nch** [comment]
Unfortunately, no major changes, either with WINE updates or otherwise. All that's really happened is that it's gotten less buggy, but it also means previous workarounds have stopped functioning.

Using both DXVK and WINE3D produce the same (or very similar) results so this is more likely an issue with WINE than DXVK.

**Comment by Cr-nch** [comment]
WAIT, I just tried this with the Wine 9.22 Wayland driver and...
![image](https://github.com/user-attachments/assets/f014f882-2c70-4997-8a5a-889ada8a001f)

I'm going to close this issue now as the issue has been solved without any weird workarounds. Seems it was definitely a WINE issue.
