### ISSUE TITLE
GTA IV Complete Edition does not start with DXVK installed

### ISSUE THREAD

**Issue by PrinceNadeem** [doitsujin/dxvk#4379]
GTA IV Complete Edition does not start with the x32 d3d9.dll in the root folder. 
I also am not getting any log files in my root folder after the game crashes.
I assume it's a Driver issue, any idea which version works fine with DXVK ?

### Software information
GTA IV Complete Edition

### System information
- GPU: AMD RX 6800 XT
- Driver: 24.9.1
- DXVK version: 2.4.1

**Comment by K0bin** [comment]
I regularly test GTA IV and it works fine.

I assume you're on Windows but I can't help you without logs.

**Comment by Blisto91** [comment]
Be sure to check out the common Windows issues in the dxvk wiki

**Comment by PrinceNadeem** [comment]
yeah, im on Windows. I've tried to open it via the .exe in the root file instead of the url file from steam and it seems to start now.

**Comment by Blisto91** [comment]
You could try disabling Steam overlay and see if that helps when launched from Steam. Ditto for rockstar overlay

**Comment by Blisto91** [comment]
@PrinceNadeem Did you figure out the issue?
