### ISSUE TITLE
[d3d9][regression?] Alpha Protocol weird reflections

### ISSUE THREAD

**Issue by Blisto91** [doitsujin/dxvk#4387]
Since commit https://github.com/doitsujin/dxvk/commit/25076d9220d37fbac589a83193a571d965d7f81a the two metal containers in the corner of the first room will have a weird reflection that moves with the camera, it looks like the outside of a building maybe. Prior to this they didn't have any reflections which match wined3d and native.

`d3d9.forceSamplerTypeSpecConstants = True` seemingly works around the issue. 
Also if i change window mode via either the game options or alt + enter the issue also disappears until i load the map again.

<details>
  <summary>Screenshots</summary>

native Nvidia
![image](https://github.com/user-attachments/assets/004fce84-c9f3-4659-9849-b1dfa80a28a7)

dxvk
![image](https://github.com/user-attachments/assets/ba89ae2e-220a-4053-9162-ac4a8e91809f)
</details>

### Software information
[Alpha Protocol](https://store.steampowered.com/agecheck/app/34010/)
Using the default settings.

### System information
- GPU: RTX 4080
- Driver: 560.35.03
- Wine version: Proton Bleeding Edge / Windows 11
- DXVK version: https://github.com/doitsujin/dxvk/commit/25076d9220d37fbac589a83193a571d965d7f81a and above

### Apitrace file(s)
TBD

Edit: added
https://drive.proton.me/urls/XB50DYT3JR#MiZEjE0tSOf1

**Comment by Blisto91** [comment]
See comment https://github.com/doitsujin/dxvk/pull/4384#issuecomment-2428776897

**Comment by K0bin** [comment]
![image](https://github.com/user-attachments/assets/d1f7e382-0251-4c77-9956-397a1f5188cc)
