### ISSUE TITLE
 The Suffering crashes with Black Screen 

### ISSUE THREAD

**Issue by JavaDaVinci** [doitsujin/dxvk#4397]
I’ve tried running the game with the latest ProtonGE 9-16, but it results in a black screen followed by a crash.Here is the log file : 
[steam-14189411690667311104.log](https://github.com/user-attachments/files/17507803/steam-14189411690667311104.log)

My specs:
Operating System: Nobara Linux 40
KDE Plasma Version: 6.2.0
KDE Frameworks Version: 6.7.0
Qt Version: 6.7.2
Kernel Version: 6.11.3-200.fsync.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600G with Radeon Graphics
Memory: 19,4 GiB of RAM
Graphics Processor: AMD Radeon RX 6600
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7C51
System Version: 1.0

**Comment by WinterSnowfall** [comment]
Note that the game has never worked properly for me in Wine, neither with dxvk nor WineD3D, without the [AIO patch referenced here](https://www.pcgamingwiki.com/wiki/The_Suffering#AiO_Unofficial_Patch). Same for Ties That Bind. Maybe give that a go and let us know if it works for you then.

**Comment by JavaDaVinci** [comment]
> I'm seeing gstreamer errors, has this ever worked or does this work with wined3d?

When I run the game using Proton Experimental through Heroic Launcher, it works without crashing. Still, with ProtonGE 9-16 on Heroic, the game crashes as well. Unfortunately, it's impossible to run the game from Steam using either ProtonGE or Proton Experimental.

**Comment by JavaDaVinci** [comment]
> 

![Screenshot_20241024_184217](https://github.com/user-attachments/assets/cfb154b7-5e3e-4fcd-b2cd-cc17a6f386dd)

**Comment by mrdeathjr28** [comment]
> Note that the game has never worked properly for me in Wine, neither with dxvk nor WineD3D, without the [AIO patch referenced here](https://www.pcgamingwiki.com/wiki/The_Suffering#AiO_Unofficial_Patch). Same for Ties That Bind. Maybe give that a go and let us know if it works for you then.

Well in my case.......

![tsf2a](https://github.com/user-attachments/assets/68395ec4-4019-4f5b-9be9-283a2f9f306c)

![tsf2b](https://github.com/user-attachments/assets/207ea4a6-55e1-45ca-9937-4041467d7484)

![tsf2c](https://github.com/user-attachments/assets/a36720a4-a38b-472e-ac68-7566d97a6333)

**Comment by JavaDaVinci** [comment]
The game, running through Proton Experimental via Heroic Launcher, works, but the audio is not correct. Unfortunately, I cannot send PROTON_LOG=1 because it doesn't function when launched from Heroic Launcher.

**Comment by JavaDaVinci** [comment]
> The game, running through Proton Experimental via Heroic Launcher, works, but the audio is not correct. Unfortunately, I cannot send PROTON_LOG=1 because it doesn't function when launched from Heroic Launcher.

Adding -setup to the game launch options allowed me to Uncheck "Use 3D Sound Buffers" and "Enable EAX. This fixed my audio problems.

**Comment by WinterSnowfall** [comment]
Lutris uses the wmp10 winetrick during game installation, so it's very likely this is an issue with codecs and Heroic perhaps simply sets up the correct overrides. In any case, this isn't an issue with dxvk, so not much we can do about it. Feel free to try @mrdeathjr28's approach above, though I would still recommend having the AIO patch as the game tends to be a buggy mess without it, especially on the audio side.
