### ISSUE TITLE
Split Second: game doesn't want to boot. 

### ISSUE THREAD

**Issue by RaptorZX4** [doitsujin/dxvk#4407]
![dxvk_splitsecond](https://github.com/user-attachments/assets/a3485c39-cff8-4f91-9e0d-707c8203aa92)

When i try to boot up the game in Windows XP (32bit), using d3d9.dll, it gives me this error message.

I use a Windows XP computer to run Windows XP games. Computer is a Dell Vostro 230, with a Core 2 Duo E8600, 4gb DDR3, Geforce GTX 745 4gb. The game run without the d3d9.dll in the game folder. But supposedly, according to PCGamingWiki, it run much better with DXVK, but even with the steps explained to make it work with DXVK (putting the 32bit d3d9.dll in the game's root), it doesn't boot at all.

### Software information
Split Second. Highest details, full screen mode

### System information
- GPU: Geforce GTX 745
- Driver: last Windows XP drivers released for the card
- Wine version: N/A
- DXVK version: 2.4.1

**Comment by Blisto91** [comment]
Windows XP does not support Vulkan and therefor cannot use dxvk.

**Comment by WinterSnowfall** [comment]
If you're on Windows XP, you're already in an ideal situation for the vast majority of d3d8/d3d9 games. Even if dxvk could be used in such scenarios (but, as @Blisto91 mentioned above, it certainly can not, since Vulkan came out 15 years **after** Windows XP), there would be little point to it.

**Comment by doitsujin** [comment]
2001 called and wants its operating system back.

Seriously though, not sure what the expectation is here but running any sort of modern software on an OS that has been EOL for over a decade now is a losing proposition.

**Comment by WinterSnowfall** [comment]
> DXVK is made for older games running on modern OSes such as Windows 10 and 11.

Actually it's made for use on Linux, but happens to help performance in a few scenarios on Windows 10/11 as well.

**Comment by RaptorZX4** [comment]
> > DXVK is made for older games running on modern OSes such as Windows 10 and 11.
> 
> Actually it's made for use on Linux, but happens to help performance in a few scenarios on Windows 10/11 as well.

alright, thanks for the clarification.

**Comment by RaptorZX4** [comment]
> 2001 called and wants its operating system back.
> 
> Seriously though, not sure what the expectation is here but running any sort of modern software on an OS that has been EOL for over a decade now is a losing proposition.

Ok, but there are still more modern solutions made for retro computers, like CuteMouse which is a mouse driver for DOS that takes only like 2 or 3kb of memory, instead of the drivers from back then which used 20-40kb of conventional memory which is A LOT especially when those DOS game require you to have 580kb+ of free conventional memory.

I just though DXVK was one of those modern solutions for older computers, when it's pretty much the other way around, to help running older games on newer computers with modern OSes.
