### ISSUE TITLE
[DEBUG] DXVK on Windows, AMD

### ISSUE THREAD

**Issue by t14462** [doitsujin/dxvk#441]
Seems like DXVK do nothing with Z-fights, it's really killing performance and sometimes make games unplayable.

Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Fallout 4, Skyrim SE, Mass Effect: Andromeda

### System information
- GPU: AMD RX560
- Driver: 18.6.1
- Wine version: Win10
- DXVK version: 0.54

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log:

**Comment by doitsujin** [comment]
Not sure what exactly your issue is, but as mentioned in the [Wiki](https://github.com/doitsujin/dxvk/wiki/Driver-support), I do not intend to support AMD's Windows driver (or AMDGPU-PRO, for that matter).
