### ISSUE TITLE
PayDay 2 stopped launching with DXVK installed

### ISSUE THREAD

**Issue by MilesFox92** [doitsujin/dxvk#4419]
DXVK was working perfectly fine and giving very big performance boost in PayDay 2 before (around the beginning of the 2024), but then after some time it just stopped launching whenever DXVK is installed. I've tried installed older versions of DXVK, changing game's screen mode, tried installing it on a different machine - nothing helped

### Software information
PayDay 2, Update 240.6

### System information
- GPU: MSI AMD RX6600 8GB
- Driver: 24.10.1 (also happened on various other versions)
- Windows version: Windows 10 Pro 22H2
- DXVK version: 2.4.1 (also happens with 2.3 and 2.2)

DXGI Log:
[payday2_win32_release_dxgi.log](https://github.com/user-attachments/files/17604777/payday2_win32_release_dxgi.log)

Apitrace logs just say "at" inside them and weight 2 bytes

**Comment by Blisto91** [comment]
Payday 2 uses d3d9 so we need the d3d9 log.

**Comment by Blisto91** [comment]
@MilesFox92 Friendly ping

**Comment by MilesFox92** [comment]
Oh, I've been leaving an answer a week ago, guess my internet was acting weird and it did not publish
I've found out that game runs fine with just the d3d9.dll file, without the dxgi.dll file (despite DXGI also working in the past). Is the d3d9 log needed still? If so - how to generate it?

**Comment by Blisto91** [comment]
Should be fine if it works just with d3d9.dll. 
Since it also stopped working with old dxvk dxgi.dll's it indicated that it isn't a dxvk issue. Can sometimes be a bit finicky with dlls next to the exe of a game on Windows depending on what the game, driver or maybe even DirectX runtime does.

**Comment by Blisto91** [comment]
@MilesFox92 I tried checking this out and the only way i was able by installing [Dozen](https://github.com/doitsujin/dxvk/wiki/Windows#dozen). So i'd make sure you don't have a program called `OpenCL, OpenGL & Vulkan Compatibility Pack` installed.
