### ISSUE TITLE
Anti-Aliasing / Anisotropic Filtering

### ISSUE THREAD

**Issue by kakra** [doitsujin/dxvk#442]
Now that I got DXVK running (with very smooth results, big thumbs up for the great work!), I see that games look like they do no anti-aliasing (or maybe not at the full potential), and also I see a lot of aliasing in textures when looking at them from certain angles which may either be a result of different bias for mipmap, or missing anisotropic filtering (or trilinear filtering).

Are these features already fully handled by DXVK?

**Comment by doitsujin** [comment]
Anything related to texture filtering and MSAA should be fully supported by DXVK, yes.

Can you name a game where you see issues, post a screenshot or something, and post your hardware, driver versions etc.?

**Comment by kakra** [comment]
It's most visible in Witcher 3 which looks different. I cannot really describe it: More crisp? It looks different than vanilla wine. Maybe DXVK supports features that vanilla does not and that's why.

Wolfenstein New Order seems to have texture aliasing like there's no anisotropic filtering. But I'd need to cross-confirm this with vanilla. I didn't start it in a while. I'm not even sure if it really uses DXVK because it may not be a DX11 game.

Skyrim SE, OTOH, just looks fine. But it has much lower resolution textures than current games.

**Comment by doitsujin** [comment]
Wolfenstein: The New Order is an OpenGL game, so it's clearly unrelated.

The Witcher 3 looks crisp because it uses an LOD Bias of -1 for pretty much all its textures. I don't think there's an issue with DXVK in that regard since it looks the same way on Windows for me.

**Comment by kakra** [comment]
Okay, I think we can close that. Thanks for the explanation.
