### ISSUE TITLE
Rayman 3: visual issue (D3D8)

### ISSUE THREAD

**Issue by legluondunet** [doitsujin/dxvk#4422]
Hello DXVK team,

if I use DXVK for Rayman 3 game, I have a visual issue:
https://youtu.be/l4Ickp4R9wQ
As you can see in this video, this visual issue appearing when I fight an elf or recovering yellow prism.

![image](https://github.com/user-attachments/assets/9d425141-5dd8-4160-a114-481d76b0838e)

This visual issue could be related to "hardware vertex processing".
Is there a way to ask DXVK to disable "hardware vertex processing"?

Thank you for your help.

My config:
Manjaro 24.1.1 Xahea
Kernel:  x86_64 Linux 6.6.54-2-MANJARO
Proc: AMD Ryzen 9 5900HX
GPU: AMD Radeon RX 6600M
Drivers: Mesa 24.2.4
Resolution: 1920x1080
32 Go RAM
DE: Xfce4

wine log:
[rayman3_wine_dxvk.log](https://github.com/user-attachments/files/17606262/rayman3_wine_dxvk.log)

**Comment by WinterSnowfall** [comment]
Sigh... guess I was a bit hasty trying to get rig of some queue syncs.

Does setting `d3d9.allowDirectBufferMapping = True` in a `dxvk.conf` file next to the game executable fix it for you?

**Comment by WinterSnowfall** [comment]
I was able to reproduce the issue. Above PR should fix things. Thanks for the report!

**Comment by legluondunet** [comment]
d3d9.allowDirectBufferMapping = True 
in dxvk.conf resolved the issue
Thank you very much..

**Comment by WinterSnowfall** [comment]
Great. I'll make that the default in a moment, together with a couple of other things.
