### ISSUE TITLE
Ni no Kuni II: Revenant Kingdom | Broken Shadows

### ISSUE THREAD

**Issue by sambow23** [doitsujin/dxvk#443]
Upon starting a new game, in the first cutscene you can see broken shadows.
Changing the shadow setting to low, normal, or high does not resolve the issue.

### Software information
Game: Ni no Kuni II: Revenant Kingdom
Settings: Highest

### System information
- GPU: GeForce GTX 1060 6GB
- Driver: 396.24.02
- Wine version: staging-3.10
- DXVK version: v0.60

### Apitrace file(s)
[Game Trace](https://send.firefox.com/download/f352f1d050/#RWaRRCpaVq1UaabwrJkNnw)

### Log files
[Nino2_d3d11.log](https://github.com/doitsujin/dxvk/files/2129017/Nino2_d3d11.log)
[Nino2_dxgi.log](https://github.com/doitsujin/dxvk/files/2129018/Nino2_dxgi.log)

![image](https://user-images.githubusercontent.com/14916663/41797374-68e30006-762f-11e8-907f-4d786b478d52.png)

**Comment by jeffbolznv** [comment]
Confirmed this is a compiler bug, we will get it fixed.

**Comment by doitsujin** [comment]
Fixed in 396.24.10.
