### ISSUE TITLE
Not working in mta 1.6

### ISSUE THREAD

**Issue by MaxRhine** [doitsujin/dxvk#4445]
### Software information 
MTA:SA 1.6 (https://multitheftauto.com/) 

### System information 
- GPU: NVIDIA GeForce GTX 980 
- Driver: NVIDIA 560.94.0 
- DXVK version: v2.4.1 

The mta downloader blocks the loading of dlls, explaining that this version is unstable. As a result, mta works on dx9

**Comment by Blisto91** [comment]
What is the issue here? Does the mod not work with dxvk? Or does the mod/launcher block dxvk? The latter we can't do anything about.

**Comment by qinlili23333** [comment]
> The mta downloader blocks the loading of dlls

I checked mta source code. https://github.com/search?q=repo%3Amultitheftauto%2Fmtasa-blue%20d3d9&type=code#

mta actively blocks d3d9.dll in same folder.
See wiki page for more dll replace methods which can bypass checking. https://github.com/doitsujin/dxvk/wiki/Windows#dll-loading-issues


Should close as not our bug.

**Comment by Blisto91** [comment]
Checking on Windows it does indeed not seem to want to load the local dxvk d3d9 dll. Replacing my system one (DON'T DO THIS YOURSELF AS YOU CAN BRICK YOUR INSTALL) to test how the menu behaves it also isn't blinking in and out so that does not seem to be a dxvk issue either.
