### ISSUE TITLE
RiME: game hangs / GPU hangs on loading screen

### ISSUE THREAD

**Issue by ziabice** [doitsujin/dxvk#445]
This game works with plain Wine (tried versions 3.9 and 3.10) but crashes on the loading screen when run using dxvk. 
The game loads right to the first menu, then crashes while loading the game, when you start or continue a game. Music plays in background.

I could test differents Mesa versions:
On Mesa 18.0.5, wine-staging-3.9, dxvk-59, the game isn't rendered correctly and has a GPU hang on loading screen, leading to a system crash.
On Mesa 18.1.1, wine-staging-3.9 or 3.10, dxvk-59 or dxvk-60, game is perfectly rendered, the first menu works perfectly, but game hangs on the same loading screen that should lead to in-game. I don't know if in this case there's a GPU hang, because my system became unresponsive and I had to manually reset it.

This game uses Unreal Engine 4.

### Software information
RiME, latest Gog.com version.
Game is set to high detail, no v-sync, FXAA antialiasing, resolution is 1080p.

Running this game on Manjaro Linux.

### System information
- GPU: AMD RX 580 4GB
- Driver: Mesa 18.1.1
- Wine version: wine-staging-nine 3.10
- DXVK version: dxvk-bin-60

### Apitrace file(s)
I don't have one, trying to create one

### Log files
- d3d11.log:
- dxgi.log:

**Comment by Kerrung** [comment]
@ziabice you should use at least the latest Mesa version, Mesa 18.1.1 is outdated.
https://github.com/doitsujin/dxvk/wiki/Driver-support

**Comment by doitsujin** [comment]
If it is indeed a GPU hang, it should be fixed with Mesa 18.1.2.

**Comment by ziabice** [comment]
I'm awaiting for the Manjaro team to release the latest update, i'll report ASAP.

**Comment by doitsujin** [comment]
Please post a comment on #252 if the issue persists in this case.
