### ISSUE TITLE
Anisotropic filtering not working with 2.5

### ISSUE THREAD

**Issue by dezo2** [doitsujin/dxvk#4452]
Anisotropic filtering does not work for me with version 2.5 in any dx8 / dx9 game (i.e. max payne, half-life2). Using win11 and latest nvidia drivers 566.14. It works no problem with version 2.4.1 and even accepts in game or NV control panel settings, but with 2.5 I can only force it using external dxvk.conf file with a line d3d9.samplerAnisotropy = 16. Is it a bug or a new feature?

**Comment by doitsujin** [comment]
Derp, should be fixed as of https://github.com/doitsujin/dxvk/commit/4c09b006a5ce84b4707a0b175a800c56a28643f0.

I'm surprised nobody noticed this before because the broken code had been shipping in Proton-Experimental for several weeks already...

**Comment by dezo2** [comment]
Thank you!
