### ISSUE TITLE
L4D2 Anisotropic Filtering not working on 2.5

### ISSUE THREAD

**Issue by ImNickedNPC** [doitsujin/dxvk#4456]
As of the most recent DXVK 2.5 Update, Anisotropic Filtering is broken for L4D2, downgrading to 2.4.1 fixes it and the option works as intended

I am on Windows 11 Version 24H2

### Software information
Left 4 Dead 2
All settings set to High/Very High, 2X MSAA, No V-sync, 1080p Fullscreen

### System information
- GPU: AMD Radeon RX 6800
- Driver: 24.10.1
- Wine version: N/A
- DXVK version: 2.5

**Comment by doitsujin** [comment]
We already fixed this, duplicate of #4452.
