### ISSUE TITLE
The Witcher 2 graphical artifacts

### ISSUE THREAD

**Issue by somebody1121** [doitsujin/dxvk#4461]
There are several graphical artifacts present on dxvk but not on wined3d nor the native version. The graphical artifacts are more pronounce with the UberSampling option enabled
DXVK:
![The WICHER 2 BAD 1](https://github.com/user-attachments/assets/e821b2a2-fa76-4853-bca9-4f8ef9a8c847)
NATIVE:
![The WICHER 2 NORMAL 1](https://github.com/user-attachments/assets/ec20b719-cae6-4dd2-a162-172bd300bbe6)
WINED3D
![The WICHER 2 NORMAL 3](https://github.com/user-attachments/assets/5f28a337-7c65-4021-a33d-929bba83ee5d)
DXVK:
![The WICHER 2 BAD 2](https://github.com/user-attachments/assets/b98e7509-e002-48e3-ad0d-5b54b76e9b5c)
NATIVE:
![The WICHER 2 NORMAL 2](https://github.com/user-attachments/assets/cc54aa4f-af47-41d3-9612-22e49338e2a7)

Videos of the problem:

DXVK:
https://mega.nz/file/3c9gQIpI#90B0uiKq_PsUMLEpYCIqz-kP2oDIPleHVEU049byuAo

WINED3D:
https://mega.nz/file/zFFTyD6a#Ykjq-j430cENzGd0k5jPI24L1nol4PnA3VFcgvtl1tQ

### Software information
The witcher 2, an all settings but more pronounce with UberSampling

### System information
- GPU: 6750XT
- Driver: Mesa 24.2.7-arch1.1 
- Wine version: ProtonGE-20
- DXVK version: ProtonGE-20, also tried 2.5, 2.4.1 and latest master

### Apitrace file(s)
wined3d apitrace: https://mega.nz/file/vE0xVDxD#gEv7VChEcMvq9vDzUZHVV7PaQG98ZReeBpRtq_74izk
dxvk apitrace: https://mega.nz/file/vZlVhYjT#fh1nAq6q0WJNk2tFrO4eQN_azBuDevWcpxrXKuPExi4

### Log files
[steam-20920.log](https://github.com/user-attachments/files/17781993/steam-20920.log)

**Comment by Blisto91** [comment]
Hi there and thank you for the well made issue.
Are you sure it doesn't happen with wined3d? I can see the blue light flicker appearing very shortly a few times at Geralts right hand in the wined3d trace (not the dxvk one), but it seems baked in as it happens both when replayed with wined3d and dxvk. Or did you accidentally switch the traces around?

**Comment by somebody1121** [comment]
> Hi there and thank you for the well made issue.
> Are you sure it doesn't happen with wined3d? I can see the blue light flicker appearing very shortly a few times at Geralts right hand in the wined3d trace (not the dxvk one), but it seems baked in as it happens both when replayed with wined3d and dxvk. Or did you accidentally switch the traces around?
> 
> Tested with my RTX 4080

Thank you for testing, and yes i saw some flickerig on the hand on wined3d and native but not on the level as seen in dxvk, the screenshots show the diference. Also there is some line of light surrounding geralt that is more visible on certain camera positions that it's not present with the gl renderers. 

Tomorrow maybe i will create a video to show the diferences and redo the traces.

**Comment by Blisto91** [comment]
Ah the line. I wasn't sure what i was looking at in the first screenshot.

At least for the flickering i haven't been able to reproduce anything on my RTX 4080 that is worse than wined3d or on Windows. It seems to be a game bug that happens at higher resolutions. My monitor is 1080p which i can't reproduce anything with but if i fake a 1440p resolution i can reproduce both with wined3d and native Windows.
I'll check it out on AMD later. Also the outline

**Comment by somebody1121** [comment]
I just made an update to add videos of the problem

**Comment by Blisto91** [comment]
@somebody1121 Could you give this build a spin and see if things improve? https://github.com/doitsujin/dxvk/actions/runs/11873257279

**Comment by somebody1121** [comment]
Yes, now renders equal to wined3d

**Comment by Blisto91** [comment]
Which is the same level as native Windows?

**Comment by somebody1121** [comment]
> Which is the same level as native Windows?

I don't have a windows install to test. By native a meant the linux version that uses also gl...
