### ISSUE TITLE
Anisotropic filtering is broken in gta iv when using latest version

### ISSUE THREAD

**Issue by gabrielp001** [doitsujin/dxvk#4462]
It doesn't happen with the previous version, so I had to revert back to version 2.4.1 of dxvk .

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

Software information
GTA IV complete edition, Textures and reflections on high, water and shadow quality on medium, 16x anisotropic filtering, resolution 2560x1440. I have fussion fix installed.

System information
- CPU: Core i7 3770
- Ram: 16GB 1600Mhz
- GPU: GTX 1060 6GB
- Driver: 566.14
- Windows version: Windows 11 24H2
- DXVK version: 2.5

**Comment by Blisto91** [comment]
It has already been fixed on master. A bug fix release will likely get released in the near future.
