### ISSUE TITLE
[Warcraft III] Getting 7 (terribly low) FPS since the new W3 2.0 update 

### ISSUE THREAD

**Issue by sim590** [doitsujin/dxvk#4463]
The title.

Also, I want to point out that I did play that game recently (couple of weeks ago) and it was fine. Not sure if it's dxvk related. I'm just starting here...

### Software information

Warcraft 3. Settings were at lowest preset.

### System information
- GPU: AMD Radeon RX 5700XT
- Driver: mesa 24.2.7
- Wine version: wine-ge-8-26-x86_64
- DXVK version: v2.4.1 (I also tried v2.5)

### Apitrace file(s)

https://mega.nz/file/6uInDZ6J#_r420DwzC2T8AX-6-QhRn-9t8N42zLj8NaGuQwlvpzs

When I tried to disable DXVK for making the API trace, it crashed, so I left it.

### Log files

[wine.log](https://github.com/user-attachments/files/17783680/w3-7fps.log)

**Comment by sim590** [comment]
I have noticed the two following threads on Blizzard's forum:

https://eu.forums.blizzard.com/en/warcraft3/t/fps-drops-back/1035/2
https://us.forums.blizzard.com/en/warcraft3/t/the-frame-rate-still-has-a-significant-drop/33206

Both are speaking of FPS drop since 2.0, it seems. The timing seems consistant. Although, they are talking about getting from 240 FPS to 100 or 60 FPS while I'm getting at 7-12 FPS. Not sure if the difference is only due to hardware ?

So, it could be possible that the issue is from on blizzard's side, but I feel like what i'm experiencing is way more terrible than what these reports are talking about.

**Comment by WinterSnowfall** [comment]
> Also, I want to point out that I did play that game recently (couple of weeks ago) and it was fine. Not sure if it's dxvk related. I'm just starting here...

Terrible or not, it definitely sounds like a game induced issue then, which is out of our scope to address. Since this is about a game that is under active development, I'd recommend waiting until the problem is addressed and the game performs as expected on native/Windows. Should you still get iffy performance with dxvk in the game at that point, do let us know.

**Comment by sim590** [comment]
Performance on Windows is acceptable though while it's not on Linux whether there's a bug or not. Shouldn't linux be able to offer a performance close to what is reported by others on Windows?

The lowest reported in the forums was 60FPS and I'm here with 7FPS with a more than capable graphic card. I just think that even if there is a bug in the game, it still seems to me there is performance to gain on the linux side. I'm wondering if that linux gap sits in DXVK or not.

You can look at this streamer having 100FPS ingame:

https://www.youtube.com/@FollowGrubby/videos

Why wouldn't Linux/DXVK give something closer ? Again, my graphic card is more than capable.

I do have a Windows partition. I might just try to make room on it and try to install it on Windows to compare and I'll report back in order to eliminate the hardware difference hypothesis.

**Comment by mbriar** [comment]
What is VRAM usage looking like? Post a screenshot with DXVK_HUD=full

**Comment by sim590** [comment]
Something is wrong:

![image](https://github.com/user-attachments/assets/f2c0658e-0e37-4d7b-8311-dbfaa7aa920a)

GPU is 1% and CPU is 8% usage....

VRAM:

![image](https://github.com/user-attachments/assets/a12d8dc7-09f8-4b80-9e04-9c222b6ed732)

**Comment by Blisto91** [comment]
How does it behave when ran without fsync and esync?

**Comment by sim590** [comment]
> How does it behave when ran without fsync and esync?

This is behaving the same.

**Comment by Blisto91** [comment]
@sim590 Do you also have a iGPU in your system?

**Comment by sim590** [comment]
> @sim590 Do you also have a iGPU in your system?

Nope.

**Comment by Blisto91** [comment]
Does running with `DXVK_CONFIG="d3d11.cachedDynamicResources = a"` help?
If not then try running it with dxvk 2.3.1 along with `DXVK_CONFIG="dxgi.useMonitorFallback = True"`

**Comment by sim590** [comment]
@Blisto91 NICE.

Using
```
DXVK_CONFIG="d3d11.cachedDynamicResources = a"
```

made all the difference!

![image](https://github.com/user-attachments/assets/3f3e5c37-187c-407b-8255-d9d8405e4355

**Comment by sim590** [comment]
Can you explain what's going on? Is it a common option that I should have expected to be on, but is not for some reason? Is it bad config, or a particular case? Do you expect this to be enabled in my other games where I get OK performance?

**Comment by mbriar** [comment]
The comment in the example dxvk.conf explains it already quite well https://github.com/doitsujin/dxvk/blob/master/dxvk.conf#L279

**Comment by Blisto91** [comment]
I am not reproducing any uplift myself so we are probably not going to make it a builtin config i imagine. 
Besides some a rare few games where it can give a uplift to everyone it can also sometimes help specifically on systems that have issues with rebar performance. I imagine the latter is going on here.

**Comment by sim590** [comment]
I have enabled resizable bar as per the explanations here:

https://wiki.archlinux.org/title/Improving_performance#Enabling_PCI_resizable_BAR

So, you suspect that this is what is causing my issues?

**Comment by mbriar** [comment]
Try to disable ReBAR and also don't set the cachedDynamicResources and see how it performs then.

**Comment by Blisto91** [comment]
Bad rebar performance is my best guess yes.

**Comment by sim590** [comment]
So I tried disabling both the option and resizable bar and it did fix the major issue. Although, I got around 100FPS this way instead of the 144FPS with resizable bar AND the option you suggested. Or could it be a bad reading in the latter case? I'm wondering because the FPS was steady at 144FPS never changing. Even if I did remove the FPS cap to 144, it didn't move up or down. So, is the performance actually the same, but just badly read when resizable bar and `d3d11.cachedDynamicResources = a` is configured?

**Comment by doitsujin** [comment]
> Also, does d3d11.cachedDynamicResources = a actually makes it like resizable bar is disabled? My question is if it's gonna prevent resizable bar optimizations to be enabled?

Setting that option prevents DXVK from using BAR memory, but the Vulkan driver may still use it internally for some things.

**Comment by sim590** [comment]
Alright. Since the mystery is resolved, I'll close this. I understand that the best might be to stick with resizable bar and pay attention to that parameter if issues happen. Thanks for support!
