### ISSUE TITLE
`VK_EXT_vertex_attribute_divisor` on i965

### ISSUE THREAD

**Issue by MrChebik** [doitsujin/dxvk#447]
Hi, how I can use DXVK 0.60 through Intel (**i965**) with Mesa 18.1.2?
I don't have `VK_EXT_vertex_attribute_divisor` extension.

```
warn:  Vulkan extension VK_EXT_shader_viewport_index_layer not supported
err:   Required Vulkan extension VK_EXT_vertex_attribute_divisor not supported
```

**Comment by Eignar17** [comment]
@MrChebik intel not work correct in DXVK  in drivers on intel vulkan not complete

**Comment by doitsujin** [comment]
I'll be honest, I didn't really consider Intel when marking that extension as required, but DXVK needs it and some games won't work correctly without it. The best thing would be to file a feature request for Intel to implement that extension.

**Comment by MrChebik** [comment]
Thanks for the quick response. I just tried to run **SkyrimSE**, thinking that the [Green dots](https://imgur.com/a/6ivmPoe) could be fixed during rendering. Judging by the articles from Intel, they have already implemented this extension. It remains to work for Mesa. I'll try to write them.

**Comment by MrChebik** [comment]
I turned to the **mesa-dev**:

> Yes, we already have support for VK_EXT_shader_viewport_index_layer.  For 
VK_EXT_vertex_attribute_divisor, it should be trivial and I'm happy to do 
so but there are currently no tests for it and, up until this email, we 
haven't had any call for that.  We'll try to bump it up the priority list.
>
>
> --Jason

**Comment by doitsujin** [comment]
Great, in that case I'll close this issue.
