### ISSUE TITLE
Ghost Recon Advanced Warfighter 2 is not opening when using DXVK version 2.5.1 or 2.3.1 (x86) DX9 

### ISSUE THREAD

**Issue by ROG820** [doitsujin/dxvk#4475]
When copy and pasting d3d9.dll + with dxgi.dll the game fails to launch.
the game uses Nvidia physx 2.7.1 SDK and it can runs even on CPU with modified settings on XML file.
(C:\Users\(usename)\App data\Local\GRAW2\settings\profiles\graw2_(username)\settings.XML)
and also I have installed lagecy nvidia physx system software 9.13 + 9.23 new version.
the game runs fine with normal DX9 with physx thrue CPU (Or Not) with AMD GPU.

Error in application:

Crash in application version: 30899.3048

Failed setting up render device.

Renderer: threaded
Physics : threaded

### Software information
tom clancy's ghost recon advanced warfighter 2, defualt settings (safe mode).
Game version: 1.05 or 30899.3048 (Last update)

### System information
- GPU: AMD Radeon RX Vega 56
- Driver: AMD Driver 21.5.2  /  Vulkan version : 1.2.170 / Driver version 2.0.179
- Wine version: Windows 7 Ultimate X64 (up to 2023 updates.)
- DXVK version: 2.5.1 & 2.3.1 tested.

### Log files
I wasn't be able to fine any log files on the game folder.

**Comment by doitsujin** [comment]
If you want to use a three and a half year old driver on a 15-year old OS, you should probably also use an old DXVK version such as 1.10.3.

**Comment by Redundanz** [comment]
@ROG820 
why don't you try radeon 22.6.1 ?

**Comment by ROG820** [comment]
> If you want to use a three and a half year old driver on a 15-year old OS, you should probably also use an old DXVK version such as 1.10.3. DXVK 2.0 onwards requires Vulkan 1.3 support.

that's right.
I used version 1.10.3 and its worked!
thanks.

**Comment by ROG820** [comment]
> @ROG820 why don't you try radeon 22.6.1 ?

I used that driver with RX 480 under windows 7 and I had 15-20 lower FPS on Witcher 3 v1.32 Compare to 21.5.2.
that's why I never going to use that driver since its has nothing but some security and bug fix only for RX 6000.
