### ISSUE TITLE
Project Reality: Battlefield 2 doesn't launch.

### ISSUE THREAD

**Issue by tanvmaht10** [doitsujin/dxvk#4476]
Project Reality: Battlefield 2 crashes upon launch while showing a black screen and prompts a error popup which is barely seen due to the black screen goes windowed at the top left corner.

Software information:
Project Reality: Battlefield 2 is a free-to-download single and multiplayer game modification for the Battlefield 2. Initially based on the assets of battlefield 2, now independent of the the base game and maintained by a dedicated community. Link: https://www.realitymod.com/downloads 

System information:
- GPU: Apple M1
- Driver: Integrated
- Wine version: wine devel 9.21 
- DXVK version: 2.5.1

Apitrace file:
Untraceable.

Log files:
[PRBF2log.txt](https://github.com/user-attachments/files/17808295/PRBF2log.txt)

**Comment by Blisto91** [comment]
Hi there. Dxvk requires Vulkan 1.3 support which MoltenVK doesn't have. Latest dxvk that can work is 1.10.3

**Comment by K0bin** [comment]
The D3D9 frontend of 1.10.3 doesn't work either because MoltenVK cannot handle how we bind different texture types to the same descriptor set slot at the same time.
