### ISSUE TITLE
Red Orchestra 2 crashes

### ISSUE THREAD

**Issue by Derdekeas** [doitsujin/dxvk#4477]
Crashes when entering almost any map. On version DXVK 2.4 it did not crash, but there were unplayable freezes.

Software information
Rising Storm/Red Orchestra 2 Multiplayer, Ultra settings

System information
- RX 7900 GRE
- 24.10.1
- Windows 11 24H2
- 2.5.1

Apitrace file(s)
- 
[rogame_d3d9.log](https://github.com/user-attachments/files/17810794/rogame_d3d9.log)

**Comment by Blisto91** [comment]
Hi there. What do you mean by unplayable freezes in 2.4? Did it freeze fully until you quit or do you mean it stutters?

Also if able please make a apitrace

**Comment by Derdekeas** [comment]
Hi. It stutter. In the next versions everything went smoothly, but the game started to crashing.

>Also if able please make a apitrace
How? Sorry, I'm not a confident PC user.

**Comment by Derdekeas** [comment]
Hi. It stutter. In the next versions everything went smoothly, but the game started to crashing.

>Also if able please make a apitrace

How? Sorry, I'm not a confident PC user.

**Comment by Blisto91** [comment]
The guide here should hopefully be relatively straight forward. https://github.com/doitsujin/dxvk/wiki/Using-Apitrace#on-windows

Note that the apitrace file will replace dxvk so you should not reproduce the issue. Just get past the point ingame where it usually crashes and then quit. Then we will replay the output trace file with dxvk locally.

**Comment by Derdekeas** [comment]
https://drive.google.com/file/d/1emmDZLm61rBVYE6CKqllQFqcEIsKPONt/view?usp=sharing

**Comment by Derdekeas** [comment]
Maybe I did something wrong? Several files were created, I sent the heaviest one. I crashed when I did this, one map was working fine, I went to another and after 5 seconds I got a crash.

It's sad, I won't be able to play this game anymore. It crashes on modern AMD GPUs, and now it's the same through dxvk.

**Comment by Derdekeas** [comment]
Well, reinstalling the game seems to have helped. Sorry to disturb.

**Comment by Derdekeas** [comment]
Well, reinstalling the game seems to have helped. Sorry to disturb.
