### ISSUE TITLE
Cant start old Chromium 230060

### ISSUE THREAD

**Issue by TheSainEyereg** [doitsujin/dxvk#4481]
When I run Chromium through Wine the browser window is black and the terminal displays errors:
```
err:   Failed to create shared resource: VK_KHR_EXTERNAL_MEMORY_WIN32 not supported
```

### Software information
Old version of chromium downloaded from:
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/230060/

### System information
- GPU: NVIDIA GeForce RTX 3060 Lite Hash Rate
- Driver: Proprietary
- Wine version: wine-9.20
- DXVK version: 2.5.1

### Apitrace file(s)
TODO

### Log files
[chrome.log](https://github.com/user-attachments/files/17853645/chrome.log)

**Comment by doitsujin** [comment]
Upstream wine does not support shared resources, you'll need a build with Proton patches for that.

That being said, running Chromium is **not** a priority.
