### ISSUE TITLE
Game-breaking artifacts with some old DX9 games when running Wayland session

### ISSUE THREAD

**Issue by giantplaceholder** [doitsujin/dxvk#4483]
Description:

When some old games are launched with Wine or Proton (the issues doesn't seem to be version-specific) using DXVK, the image is corrupted with cubic black artifacts, akin to those one might expect to see when their GPU's memory is failing.

This was my immediate go-to thought, but after trying different configurations I've narrowed it down to DX9 applications and Wayland session. When launching the same games using X11 session (or with different API options), this issue is not present.

The other factor at play might be the resolution. I've first noticed that when FNV defaulted to low screen resolution after a crash (sub 720p). When I forced my display's native resolution via FNV's config file, the issue was no longer reproducible. The same went for the L.A. Noire which by default launches in 720p if the launcher is bypassed - artifacts were gone once the res was set to native.

This is how those artifacts appear to the user:

![image](https://github.com/user-attachments/assets/56558bab-dac3-420d-bad3-5df69c86a9d9)

(my apologies for the straight-up photo of the screen, but these artifacts are not visible on the screenshots or screen capture)

### Software information
* Fallout New Vegas with NVSE and 4G+ patch (Steam version)
* Fully vanilla L.A. Noire (Steam version)

### System information
- Arch Linux (fully updated, no outrageous tweaks, custom kernels or anything like that)
- GPU: Radeon RX 7900 XTX
- Driver: Mesa 24.2.7
- Wine version: various (Proton 9.0-5, GE-Proton9-20, Wine-GE-Proton8-26, custom Wine builds using TKG scripts)
- DXVK version: various (2.4, 2.5, 2.5.1)

### Apitrace file(s)
https://mega.nz/file/hs9wXBAC#qI1eZ5HZtBStbQUR81kq5fD55v8GaL9yji31t3YZoIc (.7z archive, ~440 megabytes, FalloutNV, GE-Proton9-5 and whatever's version of DXVK is inside of it)

When I was force-enabling WineD3D via Proton's feature flag, I was unable to reproduce the issue. So the .7z archive at the link above contains a number of traces: with WineD3D enabled and DXVK disabled and vice versa, plus separate trace files which were created due to the fact that the game uses a separate launcher which then spawns the main executable.

I was unable to force L.A. Noire to play nice with the apitrace toolkit, so I'm unable to provide any traces for it right now. I'll look into it though once I'll have some time.

### Log files
[steam-22490-d3d-disabled-dxvk-enabled.log](https://github.com/user-attachments/files/17879599/steam-22490-d3d-disabled-dxvk-enabled.log)
[steam-22490-d3d-enabled-dxvk-disabled.log](https://github.com/user-attachments/files/17879600/steam-22490-d3d-enabled-dxvk-disabled.log)

**Comment by mbriar** [comment]
This looks a driver bug and is fixed by https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/32115 on Mesa git. You can also work around it with `RADV_DEBUG=nodcc`.

**Comment by mbriar** [comment]
Multiple bug reports on the mesa gitlab: 

https://gitlab.freedesktop.org/mesa/mesa/-/issues/9890
https://gitlab.freedesktop.org/mesa/mesa/-/issues/8705
https://gitlab.freedesktop.org/mesa/mesa/-/issues/11789
https://gitlab.freedesktop.org/mesa/mesa/-/issues/11600
https://gitlab.freedesktop.org/mesa/mesa/-/issues/11547

**Comment by mbriar** [comment]
You can close this, it's not a dxvk bug.

**Comment by TedMosly** [comment]
> This looks a driver bug and is fixed by https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/32115 on Mesa git. You can also work around it with `RADV_DEBUG=nodcc`.

Just wanted to drop a huge thank you for pointing out the RADV_DEBUG=nodcc workaround!

I can confirm this completely fixed the white checkerboard/flickering artifacts on Steam Deck for both Dragon Age: Origins and The Witcher 1. It seems these older DX9 engines really struggle with DCC on current drivers.

You saved my playthroughs, thanks again!

**Comment by mbriar** [comment]
@TedMosly Whatever was broken last time with DCC should long be fixed, so if it's back for some reason for you i'd recommend you open a bug report on the Mesa gitlab using the 'vulkan radeon' template.

**Comment by TedMosly** [comment]
> [@TedMosly](https://github.com/TedMosly) Whatever was broken last time with DCC should long be fixed, so if it's back for some reason for you i'd recommend you open a bug report on the Mesa gitlab using the 'vulkan radeon' template.

Thanks for the feedback. I checked my environment: the system (SteamOS) is running Mesa 24.3.4 (git-8d0948917e), while the Flatpak runtime used by Heroic is on Mesa 25.2.6. Despite these versions, the checkerboard artifacts persist in The Witcher 1 and Dragon Age: Origins. It seems the fix hasn't reached the SteamOS stable/main branch yet, or this is a regression. The RADV_DEBUG=nodcc workaround is still mandatory to play these titles without flickering squares on Steam Deck.
