### ISSUE TITLE
Half life 2 crashing without steam running

### ISSUE THREAD

**Issue by fenderjaguarnet** [doitsujin/dxvk#4488]
I've noticed that when you run the game on windows, without the steam client running, it frequently crashes with memory error and also crashes when alt tabbing. it also can crash on in-level loading screens.

with the steam client running, it's fine. you don't actually need the client running, since HL2 has no DRM

this does not happen with the native D3D9 renderer. this also did not happen before, even with DXVK. but I don't know if its an update of DXVK that causes it, or if it's the latest 20 year anniversary HL2 patch that is the problem

**Comment by fenderjaguarnet** [comment]
![8943798](https://github.com/user-attachments/assets/cdc9d12a-7d88-482c-af72-0819b419c04e)

**Comment by fenderjaguarnet** [comment]
hmmm, no I wasn't using that. I see now I look at the new folders

I've tried it now. doesn't seem to crash on alt tab anymore, but initially it crashed upon launch

**Comment by fenderjaguarnet** [comment]
thanks. but it stutters a lot in the original renderer. with vulkan it is totally smooth :)

**Comment by fenderjaguarnet** [comment]
ok I will. thanks

yes I did see a "dxvk_d3d9.dll" file in the bin directory, but I always thought it was an older version of dxvk

**Comment by fenderjaguarnet** [comment]
yes, I also see it with dxvk.conf command "dxvk.hud = full". it is really old v1.8.1-3-gd3e43ed3

**Comment by fenderjaguarnet** [comment]
I think you were right about the whole needing to add -hl2_complete to the shortcut. cause when you launch the normal hl2.exe without shortcut it does actually run the kind of "old version", and I think it is somehow conflicting with the "complete". it's not that the steam client is running that solves the problem, it's that the steam client always launch the complete, in much the same was as creating the custom shortcu,t that you suggested, does.

thanks

**Comment by SakuraRK** [comment]
> Weird, I would expect it to be version 2.0 at least (as it is on Linux). Well, I think you can stick to the DXVK binaries you downloaded then (so remove `-vulkan` to avoid using the game's built-in binaries).
> 
> Is the game running normally with DXVK version 2.5.1?

Valve has hardly updated DXVK since its initial inclusion. I have encountered stranger issues on L4D2 cuz of it... Lazy Valve.(By google translate)
