### ISSUE TITLE
Build from source - `undefined reference to`

### ISSUE THREAD

**Issue by MrChebik** [doitsujin/dxvk#449]
I'm trying to build a version without required in `VK_EXT_vertex_attribute_divisor`. All necessary libraries seem to be installed.
I got many errors with `undefined reference to`.

https://pastebin.com/ZY1hUenT

--
It seems it need to enable LTO

--
I maked a build manually:
```
meson --cross-file build-win64.txt --prefix /your/dxvk/directory build.w64
cd build.w64
meson configure -Dbuildtype=release
ninja
```
Everything went successfully.

**Comment by doitsujin** [comment]
Doesn't happen on my end.

**Comment by MrChebik** [comment]
@doitsujin Many big thanks for 0.60 update with b62ccfe.

- Removed micro sagging after the first seconds of the gameplay.
- In a complex scene, the FPS ceased to sag.

**Comment by doitsujin** [comment]
Unity builds are disabled now, so Meson shouldn't try to use LTO or anything like that.
