### ISSUE TITLE
Horizontal lines glitch in fast movement

### ISSUE THREAD

**Issue by RaduNastase** [doitsujin/dxvk#4490]
Hello,

In multiple Winlator versions there is this glitch with dxvk, where these tearing-like lines appear. In some games it is more obvious than in others.
Tried all Turnip and  dxvk conbos, no fix sadly.
Am i overlooking some obvious setting that instantly fixes it?

![received_1290670928624862](https://github.com/user-attachments/assets/29e8f374-67ed-453b-9bb0-479a73eebcca)
![received_2069260970169410](https://github.com/user-attachments/assets/0c2816de-20eb-44f7-b9e8-1f0c2eace745)
![received_1287836472533884](https://github.com/user-attachments/assets/b8aace1b-4d0c-4ff5-ac07-1123a868f8bf)

**Comment by qinlili23333** [comment]
Seems to be some issue with x11 and turnip, and most probably vsync regarding.
Vsync is always on for Android, but not always on inside Winlator. So x11 need to handle vsync presentation. These glitches are likely to come from vsync presentation.

Can you try to limit framerate to half of screen refreshrate and enable vsync in game? If this can fix, that's probably not dxvk issue.

**Comment by RaduNastase** [comment]
A person found a fix for it:

They say that in a Winlator version that has DRI3 extension on by default (with no option to disable it), adding these values fixes it:

MESA_VK_WSI_PRESENT_MODE = immediate
MESA_VK_WSI_DEBUG = sw

However, my Winlator version has the option to disable DRI3, but even then the glitches persist. But if i insert these Environment Variables suggested, it looks perfect, no more horizontal tearing-like glitch.

Thank you for your efforts friend 🤗

**Comment by RaduNastase** [comment]
Yes, sorry for wasting your time guys!

Have a great day.
