### ISSUE TITLE
dlls are the wrong architecture

### ISSUE THREAD

**Issue by Fisk24** [doitsujin/dxvk#45]
When trying to run any d3d11 software wine complains that the dlls cannot be forwarded because they are the "wrong architecture". This was done with a completely fresh 64 bit wine prefix, using dlls that were compiled from a brand new clone of the repository using the instructions in the read me for a 64bit build

### Software information
Dark Souls II and the example executables provided in the bin folder for dxvk

### System information
- GPU: NVIDIA Corporation GM204M [GeForce GTX 965M] (rev a1)
- Driver: nvidia-387.34-21
- Wine version: wine-2.21 (Staging)
- DXVK version: commit 78c46f4

### Log files
[DarkSoulsII_d3d11.log](https://github.com/doitsujin/dxvk/files/1683997/DarkSoulsII_d3d11.log)
[DarkSoulsII_dxgi.log](https://github.com/doitsujin/dxvk/files/1683998/DarkSoulsII_dxgi.log)

### WINE OUTPUT
`fixme:winediag:start_process Wine Staging 2.21 is a testing version containing experimental patches.
fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
fixme:winediag:start_process Wine Staging 2.21 is a testing version containing experimental patches.
fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
fixme:module:load_dll Loader redirect from L"dxgi.dll" to L"dxgi_vk.dll"
fixme:module:load_dll Loader redirect from L"d3d11.dll" to L"d3d11_vk.dll"
err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
fixme:ver:GetCurrentPackageId (0x33e470 (nil)): stub
fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
fixme:winhttp:WinHttpDetectAutoProxyConfigUrl discovery via DHCP not supported
fixme:ntdll:EtwEventRegister ({47a9201e-73b0-42ce-9821-7e134361bc6f}, 0x3f006bd0, 0x3f043cf0, 0x3f043ce8) stub.
fixme:ntdll:EtwEventRegister ({58a9201e-73b0-42ce-9821-7e134361bc70}, 0x3f006bd0, 0x3f043d28, 0x3f043d20) stub.
fixme:ntdll:EtwEventRegister ({3fa9201e-73b0-43fe-9821-7e145359bc6f}, 0x3f006bd0, 0x3f043dd0, 0x3f043dc8) stub.
fixme:ntdll:EtwEventRegister ({1432afee-73b0-42ce-9821-7e134361b433}, 0x3f006bd0, 0x3f043d60, 0x3f043d58) stub.
fixme:ntdll:EtwEventRegister ({4372afee-73b0-42ce-9821-7e134361b519}, 0x3f006bd0, 0x3f043d98, 0x3f043d90) stub.
fixme:process:SetProcessShutdownParameters (00000100, 00000000): partial stub.
fixme:xinput:XInputGetCapabilities (index 3, flags 0x1, capabilities 0x33e75c) Stub!
fixme:win:RegisterDeviceNotificationW (hwnd=0x2006e, filter=0x41ce8e8,flags=0x00000000) returns a fake device notification handle!
fixme:xinput:XInputSetState (index 0, vibration 0x33e78c) Stub!
fixme:xinput:XInputSetState (index 1, vibration 0x33e78c) Stub!
fixme:xinput:XInputSetState (index 2, vibration 0x33e78c) Stub!
fixme:xinput:XInputSetState (index 3, vibration 0x33e78c) Stub!
fixme:imm:ImmGetOpenStatus (0x9e3fb8): semi-stub
fixme:file:GetLongPathNameW UNC pathname L"\\\\?\\C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe"
fixme:file:GetLongPathNameW UNC pathname L"\\\\?\\C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe"
fixme:file:GetLongPathNameW UNC pathname L"\\\\?\\C:\\Program Files (x86)\\Steam\\logs\\cef_log.txt"
fixme:file:GetLongPathNameW UNC pathname L"\\\\?\\C:\\Program Files (x86)\\Steam\\logs\\cef_log.txt"
fixme:ver:GetCurrentPackageId (0x33d90c (nil)): stub
fixme:dwmapi:DwmSetWindowAttribute (0x100a0, 2, 0x33df20, 4) stub
fixme:dwmapi:DwmExtendFrameIntoClientArea (0x100a0, 0x33df0c) stub
fixme:module:load_dll Loader redirect from L"d3d11.dll" to L"d3d11_vk.dll"
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\libcef.dll") not found
fixme:module:load_dll Loader redirect from L"dxgi.dll" to L"dxgi_vk.dll"
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\libcef.dll") not found
err:module:import_dll Library libcef.dll (which is needed by L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe" failed, status c0000135
fixme:advapi:StopTraceA (0, "Steam Event Tracing", 0x33e264) stub
fixme:advapi:StartTraceA (0x33e2f0, "Steam Event Tracing", 0x33e264) stub
fixme:advapi:OpenTraceA 0x33e0c4: stub
fixme:advapi:EnableTrace (1, 0x10, 4, {22fb2cd6-0e7b-422b-a0c7-2fad1fd0e716}, cafe4242): stub
fixme:advapi:CloseTrace cafe4242: stub
fixme:advapi:ProcessTrace 0x11968a08 1 (nil) (nil): stub
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
fixme:ver:GetCurrentPackageId (0x33cc20 (nil)): stub
fixme:win:RegisterDeviceNotificationA (hwnd=0x100ac, filter=0x12dce4ac,flags=0x00000004) returns a fake device notification handle!
fixme:module:load_dll Loader redirect from L"dxgi.dll" to L"dxgi_vk.dll"
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
err:module:import_dll Library dxgi.dll (which is needed by L"C:\\windows\\system32\\wbemprox.dll") not found
err:ole:COMPOBJ_DllList_Add couldn't load in-process dll L"C:\\windows\\system32\\wbemprox.dll"
err:ole:CoGetClassObject no class object {4590f811-1d3a-11d0-891f-00aa004b2e24} could be created for context 0x1
fixme:module:load_dll Loader redirect from L"dxgi.dll" to L"dxgi_vk.dll"
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
err:module:import_dll Library dxgi.dll (which is needed by L"C:\\windows\\system32\\wbemprox.dll") not found
err:ole:COMPOBJ_DllList_Add couldn't load in-process dll L"C:\\windows\\system32\\wbemprox.dll"
err:ole:CoGetClassObject no class object {4590f811-1d3a-11d0-891f-00aa004b2e24} could be created for context 0x1
fixme:iphlpapi:NotifyAddrChange (Handle 0x1ff050c, overlapped 0x1ff0510): stub
fixme:dwmapi:DwmExtendFrameIntoClientArea (0x100ae, 0x33e394) stub
err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
fixme:win:RegisterTouchWindow (0x100c4 00000003): stub
fixme:wgl:X11DRV_wglChoosePixelFormatARB unused pfAttribFList
err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
fixme:win:RegisterTouchWindow (0x300c8 00000003): stub
fixme:wgl:X11DRV_wglChoosePixelFormatARB unused pfAttribFList
err:ntdll:RtlLeaveCriticalSection section 0x3603b0 is not acquired
fixme:dwrite:dwritefactory_CreateMonitorRenderingParams (0x1): monitor setting ignored
fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
fixme:dwmapi:DwmExtendFrameIntoClientArea (0x300c2, 0x33e0e8) stub
fixme:dwmapi:DwmExtendFrameIntoClientArea (0x400cc, 0x33d818) stub
fixme:imm:ImmReleaseContext (0x100ae, 0x1044a8f8): stub
fixme:win:RegisterDeviceNotificationA (hwnd=0x400cc, filter=0x33dadc,flags=0x00000004) returns a fake device notification handle!
fixme:dwmapi:DwmGetWindowAttribute ((nil) 9 0x33da34 16) stub
err:ole:CoGetClassObject class {294935ce-f637-4e7c-a41b-ab255460b862} not registered
err:ole:CoGetClassObject class {294935ce-f637-4e7c-a41b-ab255460b862} not registered
err:ole:create_server class {294935ce-f637-4e7c-a41b-ab255460b862} not registered
fixme:ole:CoGetClassObject CLSCTX_REMOTE_SERVER not supported
err:ole:CoGetClassObject no class object {294935ce-f637-4e7c-a41b-ab255460b862} could be created for context 0x17
fixme:dwmapi:DwmExtendFrameIntoClientArea (0x3011c, 0x33e1fc) stub
fixme:hnetcfg:fw_apps_get__NewEnum 0x10a61c70, 0x14afe490
fixme:hnetcfg:fw_app_put_ProcessImageFileName 0x10a61c70, L"C:\\Program Files (x86)\\Steam\\Steam.exe"
fixme:hnetcfg:fw_app_put_Name 0x10a61c70, L"Steam"
fixme:hnetcfg:fw_app_put_Enabled 0x10a61c70, -1
fixme:hnetcfg:fw_apps_Add 0x104d32c0, 0x10a61c70
fixme:hnetcfg:netfw_rules_get__NewEnum 0x104d32c0, 0x14afe488
fixme:hnetcfg:fw_apps_get__NewEnum 0x104d32c0, 0x14afe490
fixme:hnetcfg:fw_app_put_ProcessImageFileName 0x104d3298, L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe"
fixme:hnetcfg:fw_app_put_Name 0x104d3298, L"Steam Web Helper"
fixme:hnetcfg:fw_app_put_Enabled 0x104d3298, -1
fixme:hnetcfg:fw_apps_Add 0x104d3238, 0x104d3298
fixme:hnetcfg:netfw_rules_get__NewEnum 0x10a6ce88, 0x14afe488
fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000019-0000-0000-c000-000000000046} (unknown)
fixme:shell:CustomDestinationList_BeginList 0x10286318 (0x14cfe518 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x14cfe524): stub
fixme:dwmapi:DwmExtendFrameIntoClientArea (0x300b4, 0x33e39c) stub
fixme:dwmapi:DwmExtendFrameIntoClientArea (0x10182, 0x33e374) stub
fixme:module:load_dll Loader redirect from L"dxgi.dll" to L"dxgi_vk.dll"
fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000019-0000-0000-c000-000000000046} (unknown)
fixme:shell:CustomDestinationList_BeginList 0x10b4ecd8 (0x14dfe518 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x14dfe524): stub
fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000019-0000-0000-c000-000000000046} (unknown)
fixme:shell:CustomDestinationList_BeginList 0x1047ba68 (0x1542e518 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x1542e524): stub
fixme:module:load_dll Loader redirect from L"d3d11.dll" to L"d3d11_vk.dll"
err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
fixme:ntdll:EtwEventRegister ({47a9201e-73b0-42ce-9821-7e134361bc6f}, 0x3602030, 0x36a9d40, 0x36a9d38) stub.
fixme:ntdll:EtwEventRegister ({58a9201e-73b0-42ce-9821-7e134361bc70}, 0x3602030, 0x36a9d78, 0x36a9d70) stub.
fixme:ntdll:EtwEventRegister ({3fa9201e-73b0-43fe-9821-7e145359bc6f}, 0x3602030, 0x36a9d08, 0x36a9d00) stub.
fixme:ntdll:EtwEventRegister ({1432afee-73b0-42ce-9821-7e134361b433}, 0x3602030, 0x36a9db0, 0x36a9da8) stub.
fixme:ntdll:EtwEventRegister ({4372afee-73b0-42ce-9821-7e134361b519}, 0x3602030, 0x36a9de8, 0x36a9de0) stub.
fixme:imm:ImmGetOpenStatus (0xd17f0): semi-stub
fixme:ver:GetCurrentPackageId (0x23ec90 (nil)): stub
fixme:module:find_dll_file skipping L"C:\\Program Files (x86)\\Steam\\dbghelp.dll" because of wrong architecture
fixme:ntdll:EtwEventRegister ({47a9201e-73b0-42ce-9821-7e134361bc6f}, 0x3f0070a0, 0x3f0524c0, 0x3f0524b8) stub.
fixme:ntdll:EtwEventRegister ({58a9201e-73b0-42ce-9821-7e134361bc70}, 0x3f0070a0, 0x3f0524f8, 0x3f0524f0) stub.
fixme:ntdll:EtwEventRegister ({3fa9201e-73b0-43fe-9821-7e145359bc6f}, 0x3f0070a0, 0x3f052488, 0x3f052480) stub.
fixme:ntdll:EtwEventRegister ({1432afee-73b0-42ce-9821-7e134361b433}, 0x3f0070a0, 0x3f052530, 0x3f052528) stub.
fixme:ntdll:EtwEventRegister ({4372afee-73b0-42ce-9821-7e134361b519}, 0x3f0070a0, 0x3f052568, 0x3f052560) stub.
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
fixme:vulkan:vkGetInstanceProcAddr "vkCreateDebugReportCallbackEXT" not supported
fixme:vulkan:vkGetInstanceProcAddr "vkDestroyDebugReportCallbackEXT" not supported
fixme:vulkan:vkGetInstanceProcAddr "vkDebugReportMessageEXT" not supported
fixme:ver:GetCurrentPackageId (0x6d6e510 (nil)): stub
fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000019-0000-0000-c000-000000000046} (unknown)
fixme:shell:CustomDestinationList_BeginList 0x10473390 (0x158ce518 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x158ce524): stub
fixme:vulkan:vkGetInstanceProcAddr "vkCreateDebugReportCallbackEXT" not supported
fixme:vulkan:vkGetInstanceProcAddr "vkDestroyDebugReportCallbackEXT" not supported
fixme:vulkan:vkGetInstanceProcAddr "vkDebugReportMessageEXT" not supported
fixme:vulkan:vkGetInstanceProcAddr "vkCreateDebugReportCallbackEXT" not supported
fixme:vulkan:vkGetInstanceProcAddr "vkDestroyDebugReportCallbackEXT" not supported
fixme:vulkan:vkGetInstanceProcAddr "vkDebugReportMessageEXT" not supported
wine: Unhandled page fault on read access to 0x00000000 at address 0x7f7b50522e0f (thread 0068), starting debugger...
err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000019-0000-0000-c000-000000000046} (unknown)
fixme:shell:CustomDestinationList_BeginList 0x10473390 (0x1542e518 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x1542e524): stub
fixme:file:GetLongPathNameW UNC pathname L"\\\\?\\C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe"
fixme:file:GetLongPathNameW UNC pathname L"\\\\?\\C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe"
fixme:file:GetLongPathNameW UNC pathname L"\\\\?\\C:\\Program Files (x86)\\Steam\\logs\\cef_log.txt"
fixme:file:GetLongPathNameW UNC pathname L"\\\\?\\C:\\Program Files (x86)\\Steam\\logs\\cef_log.txt"
fixme:module:load_dll Loader redirect from L"d3d11.dll" to L"d3d11_vk.dll"
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\d3d11_vk.dll" because of wrong architecture
err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\libcef.dll") not found
fixme:module:load_dll Loader redirect from L"dxgi.dll" to L"dxgi_vk.dll"
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
fixme:module:find_dll_file skipping L"Z:\\home\\fisk\\Staging\\dxvk\\bin\\dxgi_vk.dll" because of wrong architecture
err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\libcef.dll") not found
err:module:import_dll Library libcef.dll (which is needed by L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\Program Files (x86)\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe" failed, status c0000135
fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000003-0000-0000-c000-000000000046} (unknown)
fixme:shell:CustomDestinationList_QueryInterface not implemented for {00000019-0000-0000-c000-000000000046} (unknown)
fixme:shell:CustomDestinationList_BeginList 0x10a57f08 (0x158ce518 {92ca9dcd-5622-4bba-a805-5e9f541bd8c9} 0x158ce524): stub`

**Comment by GabrielMajeri** [comment]
1. Related to the "broken RandR error", check the [Wine FAQ](https://wiki.winehq.org/FAQ#Broken_NVIDIA_RandR_detected.2C_falling_back_to_RandR_1.0) or search the internet, since this is not related to this project.

2. You need to build and install the DLLs for the right architecture of the games you want to play. The original DS II is 32-bit, the Scholars of the First Sins edition is 64-bit.

3. Wine requiring `ntlm_auth` means you might need to install Samba for your distribution.

**Comment by doitsujin** [comment]
You can (and should) install both 32-bit and 64-bit libraries to the same prefix. You'll still get the messages, but they are a non-issue and just wine being overly verbose.

Can't promise that you can run the game though since you're on Nvidia, and their driver causes massive amounts of trouble for reasons that i have yet to find out.

**Comment by Kreyren** [comment]
@doitsujin Can you provide more info to `install both 32-bit and 64-bit libraries to the same prefix.` ? Wine refuses to merge 32+64 winearch by default with `wine: WINEARCH set to win32 but '/home/kreyren/.wine-64' is a 64-bit installation.`

Having simmilar issue on https://paste.pound-python.org/show/5DIqLET6E6XrQaCuj8Vs/ 
 OR https://github.com/RXT067/Research/tree/master/WINE-Dishonored2#performance-issues atm.

**Comment by doitsujin** [comment]
Just don't set `WINEARCH`?

**Comment by Kreyren** [comment]
> Just don't set `WINEARCH`?

Ah.. Didn't know that i can do that :thinking: Thanks! very helpful.
