### ISSUE TITLE
The Witcher 3: Trembling of trees

### ISSUE THREAD

**Issue by Kerrung** [doitsujin/dxvk#450]
@doitsujin  Hi! Some trees trembling instead of smoothly swaying from the wind. This does not happen with WineD3D or Windows.

### Software information
The Witcher 3, minimal graphics settings used.

### System information
- OS: Arch Linux
- GPU: AMD Radeon HD 7770
- Driver: Mesa-git, LLVM 7, AMDGPU from Linux 4.17.2
- Wine version: Wine-git + Staging-git
- DXVK version: 060cd1d

### [>>>Apitrace and some other files<<<](https://mega.nz/#!HBMzgILa!b7Z2pizToZkt7cWQ7G6OqrduYUGvxFVHBalM2KCAbpM)
It happened the game hangs during the end of load screen only when I tried to record apitraces? but works fine if I didn't record apitraces.

### Log files
- [witcher3_d3d11.log](https://github.com/doitsujin/dxvk/files/2131203/witcher3_d3d11.log)

- [witcher3_dxgi.log](https://github.com/doitsujin/dxvk/files/2131204/witcher3_dxgi.log)

Please, tell me if you need any more logs etc..

**Comment by jarrard** [comment]
This can happen in games like Fallout4 where the physics engine goes crazy on the trees. 

I don't really know if its directly related to DXVK, could easily be a game/wine bug. I have seen it happen under windows even, thought less often. Try and find some sort of modification to tweak tree sway (sometimes a INI tweak can do this).

**Comment by doitsujin** [comment]
@jarrard this isn't the first time someone reports broken trees in Witcher 3, but they seem to work fine for Nvidia users and most AMD users as well so I suspect it's just a driver issue with these older GPUs.

**Comment by Kerrung** [comment]
>This isn't the first time someone reports broken trees in Witcher 3, but they seem to work fine for Nvidia users and most AMD users as well so I suspect it's just a driver issue with these older GPUs.

@doitsujin thank you. Seems like I should to open a Mesa bug report.

**Comment by Kerrung** [comment]
@doitsujin [I opened a Mesa bug report](https://bugs.freedesktop.org/show_bug.cgi?id=107022).
