### ISSUE TITLE
Watch_Dogs 2 crashing randomly

### ISSUE THREAD

**Issue by AccountOneOff** [doitsujin/dxvk#451]
The game crashes/freezes when starting a new game but I was able to obtain a save after the prologue and I'm able to play for some time. However, the game crashes for seemingly no reason, or no reason that I can see, and I've only been able to play about 10-15 minutes at a time before crashing.

### Software information
High, Medium, and Low it doesn't matter which preset I use.

### System information
- GPU: GTX 960
- Driver: 396.24.02
- Wine version: Wine Staging 3.10
- DXVK version: 060cd1d

### Apitrace file(s)
- Would a trace help if it comes from DXVK on Wine? If so I can provide one no problem.

### Log files
- d3d11, dxgi, and validation layers: [WatchDogs2logs.zip](https://github.com/doitsujin/dxvk/files/2131215/WatchDogs2logs.zip)

**Comment by AccountOneOff** [comment]
I found a reliable way to reproduce the crashing. Start "Drake's Downhill" motocross race and hit the jump over the buildings. It's crashed 5/5 times so far doing that. Here's the save just in case: [wd2save.zip](https://github.com/doitsujin/dxvk/files/2135297/wd2save.zip)

**Comment by debianxfce** [comment]
Disable Uplay overlay and vsync in the game settings.

**Comment by AccountOneOff** [comment]
I don't know if it was a driver bug or DXVK but this seems fixed. Drake's Downhill race doesn't trigger a freeze anymore.
