### ISSUE TITLE
[d3d11] TopSpin 2K25 - Rendering issues

### ISSUE THREAD

**Issue by jr1991-g** [doitsujin/dxvk#4514]
Players, judges, ballboys are missing legs, arms and faces at 100% resolution. 
![20241208222221_1](https://github.com/user-attachments/assets/b3cccb92-2b5f-4239-be31-1d7c34b5e0fa)
200% res alleviates this somehow, but not completely. 
![20241208222237_1](https://github.com/user-attachments/assets/7e7a26b1-a6ea-4de2-8556-57d350eddd8c)

Before match the players are transparent.
![20241208221928_1](https://github.com/user-attachments/assets/5420840a-8f9e-411c-8a5a-7de0265d147f)

Also some game transitions and loadscreens look like this.
![20241208230606_1](https://github.com/user-attachments/assets/4d504fe9-8e53-42c1-b329-947ee07915c7)

Apitrace and proton log are with 2.4.1 and proton-9.0-3. Same results with dxvk 2.5.1 and proton exp/ge20. Game does not start at all with PROTON_USE_WINED3D11=1 %command%. These issues have been present since the game's release but no one reported it for some reason.

### Software information
[TopSpin 2K25](https://store.steampowered.com/app/1785650/TopSpin_2K25/) - 1920x1080, borderless, low/high settings.

### System information
- GPU: AMD RX 6650 XT 
- Driver: Mesa 24.2.8
- Wine version: proton-9.0-3e/experimental/GE-Proton9-20
- DXVK version: 2.4.1/2.5.1

### Apitrace file(s)
[Apitrace](https://mega.nz/file/N3IwQAKS#EW4F50ddxnUuWOWDxV-dLDSk0ztEbP27OUA76x7H4xo)

### Log files
[steam-1785650.zip](https://github.com/user-attachments/files/18055331/steam-1785650.zip)

**Comment by qinlili23333** [comment]
Good apitrace example.
I can replay with native d3d11 and get correct render. The loading screen is normal.
![image](https://github.com/user-attachments/assets/379fd8ce-03e9-44fa-ba64-5346d45ed84e)
If replay with [dxvk latest master,](https://github.com/doitsujin/dxvk/actions/runs/12189315012) loading screen is black and replay crash after loading screen.
![image](https://github.com/user-attachments/assets/74c08440-782b-4ab9-93d4-bd92cbfdb602)

I'm using NVIDIA 566.36, so I suppose it's dxvk issue.

**Comment by doitsujin** [comment]
I don't get the crash, but the rendering issue seems to be due to us not properly supporting `DXGI_FORMAT_A8_UNORM` for UAVs. Unfortunately, implementing this "properly" on top of `VK_FORMAT_A8_UNORM` has regressed Crysis 2 in the past for unknown reasons and it isn't supported by any debugging tools at the moment, so this is tricky.

**Comment by doitsujin** [comment]
Yeah, https://github.com/doitsujin/dxvk/tree/dxgi-a8-unorm works around the issue. Still need to figure out why this breaks other games, though.
