### ISSUE TITLE
Suddenly it stopped working

### ISSUE THREAD

**Issue by mvklmbrs** [doitsujin/dxvk#4516]
I haven't played for a while and then everything stopped running. They don't even start. Only in the task manager there is a process that does not load the CPU. I've tried different games, x32 and x64, different versions of DXVK (also dxvk-gplasync), reinstalled drivers using DDU, different driver versions, deleted RSS and MSI Afterburner. It remains only to reinstall Windows, but I really don't want to. It's very strange because recently everything worked perfectly. With apitrace game runs but using DX11 api (test game is thronefall) and has 1 fps.

System information
- GPU: Intel Arc A730M
- Driver: ANY but first faced on 32.0.101.6319
- Wine version: -
- DXVK version: from 1.10.3 to 2.5.1
- Windows 11 24H2 (26100.2454)

Apitrace file
https://mega.nz/file/PwZWCACa#8N-2yaDXgOc5nt62C_Ahy1JGVJwtcaRSPZ0YN_aR6Fg

Log file with 2.5.1 version is empty, but with 1.10.3:
https://pastebin.com/Azivs8ZM

**Comment by WinterSnowfall** [comment]
Please check to see if you have Dozen installed and if so remove it (more details [here](https://github.com/doitsujin/dxvk/wiki/Windows#dozen)).

**Comment by mvklmbrs** [comment]
> Please check to see if you have Dozen installed and if so remove it (more details [here](https://github.com/doitsujin/dxvk/wiki/Windows#dozen)).

you're goddam right, and I'm blind, I don't remember when and why I installed it

**Comment by WinterSnowfall** [comment]
> you're goddam right, and I'm blind, I don't remember when and why I installed it. thanks a lot

I don't think it was you, Windows just auto-installs it sometimes for whatever reason. It's not the first time we've seen it happen for sure, that's why we have a Wiki entry for it.
