### ISSUE TITLE
dxgi dll chaining?

### ISSUE THREAD

**Issue by delentef** [doitsujin/dxvk#4523]
Sorry in advance for the irrelevance of my post I guess, this is not an issue but more of an enquiry. I am on Fedora 40 btw.

I'd like to play Dark Souls II Scholar of the First Sin with the Lighting Engine Mod (https://www.nexusmods.com/darksouls2/mods/1146). However this mod hijacks dxgi.dll and dxvk does the same thing.

I thought of putting dxvk's dxgi.dll in the windows/sytem32 but I guess it'll try to load then dxgi.dll from Windows and either get stuck in a recursive loop, or abort right away.

Is there a way to achieve this, or should I stick to wine's implementation of D3dx11? (I intend to install steam in a wine prefix to do that).

Thanks for any hint! And very many thanks for DXVK !

**Comment by mbriar** [comment]
On linux/wine, installed dxvk's dlls to windows/sytem32 is the recommended way that's also described in the install instructions. I don't understand where you see a problem? This mod will probably "just work" without doing anything special by just installing the game from linux steam with proton and dumping the mod dll next to the exe.

**Comment by Blisto91** [comment]
"Installing" the dxvk DLLs in to the Wine prefix system folders (DON'T DO IT ON WINDOWS) is the recommended way yes. It should work the same way as on Windows then.

**Comment by mbriar** [comment]
> I intend to install steam in a wine prefix to do that

there is no need to do that for anything that you planned to do here, fwiw.

**Comment by K0bin** [comment]
The most elegant way would simply if the mod allowed you to configure the name of the DXGI dll it's gonna load internally with an environment variable. Idk if it's possible to convince the mod author to do that (or if the mod is even still maintained).

**Comment by delentef** [comment]
Thanks for you answers! It makes everything more simple :^)
