### ISSUE TITLE
How to force 1 cpu core with config file?

### ISSUE THREAD

**Issue by BParks21** [doitsujin/dxvk#4526]
I don't understand how I would force dxvk to use 1 cpu core? I'm using dxvk with the PC port of Legacy of Kain Defiance and the game can sometimes freeze on high core count cpus. I just want to know how to configure dxvk so the game runs on one cpu core without having to go into task manager every time I launch the game and manually setting affinity? Thanks didn't know where else to ask this.

### Software information
Legacy of Kain Defiance

### System information
- GPU: 1080 Ti
- Driver:
- DXVK version:  2.5.1

**Comment by K0bin** [comment]
We do not support changing the threading behavior of DXVK with a config file. Even if we did, the threading in DXVK works fine so if it is indeed multithreading, which breaks the game, it is in game code and any DXVK option wouldn't impact that.

**Comment by WinterSnowfall** [comment]
I've been somewhat playing it on and off now, and can't say I've ever had it crash. Then again I'm "only" on a 16-thread CPU, and it might every well explode above that. But, as K0bin mentioned, it's very very unlikely dxvk is the problem here.

**Comment by doitsujin** [comment]
`WINE_CPU_TOPOLOGY`, see above. This is outside the scope of DXVK though.

**Comment by BParks21** [comment]
Thanks for the info guys! Yeah I never said it was a problem with DXVK I just wanted to know if doing such a thing was possible.
