### ISSUE TITLE
If DXVK_CONFIG_FILE is set. DXVK_CONFIG is ignored

### ISSUE THREAD

**Issue by Trevonn** [doitsujin/dxvk#4529]
### Software Information

It would seem if you have `DXVK_CONFIG_FILE` set then `DXVK_CONFIG` is acknowledged but ignored.

### System Information
- GPU            : AMD Radeon 780M (RADV GFX1103_R1)
- Driver         : 24.3.1
- Wine Version   : proton-experimental-9.0-20241206
- DXVK Version   : (v2.5.1-23-g027fe596)
- Kernel         : 6.12.4-arch1-1
- CPU            : AMD Ryzen 7 7840U w/ Radeon 780M Graphics
- RAM            : 27 GB
- VRAM           : 4096 MB

### Log files
[DS_d3d9.log](https://github.com/user-attachments/files/18140744/DS_d3d9.log)

**Comment by doitsujin** [comment]
Works fine on my end, not sure what's going on here.
