### ISSUE TITLE
WoW Vanilla (1.12) dx9 regression dxvk-2.5.2

### ISSUE THREAD

**Issue by shikulja** [doitsujin/dxvk#4532]
### Software information
Windows 11
WoW vanilla 1.12
(UI addon) https://github.com/shagu/pfUI

### System information
- GPU: rx580 (8)
- Driver: 24.9.1
- Wine version:  not have
- DXVK version:  2.5.2

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files

[WoW_tweaked_d3d9.log](https://github.com/user-attachments/files/18212424/WoW_tweaked_d3d9.log)

- with dxvk 2.52
<img width="1154" alt="image" src="https://github.com/user-attachments/assets/dc5393ff-c5e3-4525-89db-71ddc92863a6" />
<img width="460" alt="image" src="https://github.com/user-attachments/assets/b1b2ed59-ee87-48c1-8d6b-e9ec419b1d5c" />

![image](https://github.com/user-attachments/assets/787c7da5-449b-47e7-a50b-5c9526d09cd2)
<img width="824" alt="image" src="https://github.com/user-attachments/assets/0ec094db-8113-4430-80cf-4decc6e9145b" />

- without dxvk
![image](https://github.com/user-attachments/assets/3c545b54-afeb-4477-89a2-6dc0572e4538)

**Comment by allfoxwy** [comment]
fb8f79e4a717991cf254352ed2f63f392787488a was fine.
