### ISSUE TITLE
Knights of the Temple have serious rendering issues and dxvk fps limit seems dont work

### ISSUE THREAD

**Issue by mrdeathjr28** [doitsujin/dxvk#4536]
Knights of the Temple* have serious rendering issues and dxvk fps limit seems dont work

*in good news this game stay avalaible on steam:

https://store.steampowered.com/app/1194610/Knights_of_the_Temple_Infernal_Crusade

![kot1a](https://github.com/user-attachments/assets/8b8d9f73-733d-429c-a810-0dec03d3352a)

![kotbca](https://github.com/user-attachments/assets/fcb209b2-f3ac-42bc-9287-00d34a70217c)

![kotcb](https://github.com/user-attachments/assets/4cd39c9f-4127-42e3-904d-d91886c721cb)

![kotcd](https://github.com/user-attachments/assets/447a3e31-0b1d-47b3-b045-c0383878363a)

### Software information

Knights of the Temple

### System information

- GPU: AMD Radeon Renoir iGPU @2300mhz
- Driver: Mesa 25.0-git
- Wine version: 10.0-rc3
- DXVK version: 2.5.2

### Apitrace file(s)

https://drive.google.com/file/d/1-mGK5cosF8MMcEZDQ0bhxRiDi0il4lQ1/view?usp=sharing

### Log files

[Templar_d3d9.log](https://github.com/user-attachments/files/18218912/Templar_d3d9.log)

**Comment by K0bin** [comment]
Try master.

2.5.2 unfortunately has a bug that breaks old games.

**Comment by mrdeathjr28** [comment]
> Try master.
> 
> 2.5.2 unfortunately has a bug that breaks old games.
> 
> And the log contains no mention of the FPS limiter*, so I assume you just didn't enable it correctly.

nope in other games works correctly and fps limit works incorrectly in this game

maybe can add a tiny video later

**Comment by K0bin** [comment]
How do you configure the limiter? Using your DXVK config file?

**Comment by mrdeathjr28** [comment]
> How do you configure the limiter? Using your DXVK config file?

Yeah i use for all games and works ok

DXVK_HUD=devinfo,fps,version,api **_DXVK_FRAME_RATE=60_** DXVK_LOG_LEVEL=none DXVK_CONFIG_FILE=/home/linuxdesktopx64/dxvk.conf WINEDEBUG=-all wine Appetizer.exe

using lastest master main menu improve

![dxvkfxa](https://github.com/user-attachments/assets/06741efc-78cd-4a09-971e-1dc54bf73010)

character show textures however scenary dont show textures correctly, but fps problem remains is very funny


https://github.com/user-attachments/assets/1f3e0f5a-965e-460c-8446-90626b9ba0ca

**Comment by K0bin** [comment]
> DXVK_FRAME_RATE=60

Your videos are locked to 60fps. So where's the problem with that?

About the texture bugs: please make an apitrace.

**Comment by mrdeathjr28** [comment]
> > DXVK_FRAME_RATE=60
> 
> Your videos are locked to 60fps. So where's the problem with that?
> 
> About the texture bugs: please make an apitrace.

in begin post i put a apitrace

**Comment by WinterSnowfall** [comment]
> https://drive.google.com/file/d/1-mGK5cosF8MMcEZDQ0bhxRiDi0il4lQ1/view?usp=sharing

Thank you for the trace. It looks the same as in your above screenshot on replay with WineD3D, but I'm guessing WineD3D renders everything fine for you?

**Comment by Blisto91** [comment]
I quickly checked out the game on Windows with dxvk while i was there. Didn't see any visual issues. Tested with a Arc b580.

In regards to the speed then i don't know why i goes that fast. It doesn't have anything directly to do with a fps apparently nor the number of CPU cores. It goes just as fast for me on Windows without dxvk

**Comment by mrdeathjr28** [comment]
In my case textures are fixed (some strage error in spanish translation, my native language)

Apparently lower values fix textures

![kott2b](https://github.com/user-attachments/assets/365bdeb7-2756-4e98-bb6b-e83d4efcabd1)

![kott2](https://github.com/user-attachments/assets/c402ae94-cb7c-4060-a0de-307983508746)

However fps issue still remains

**Comment by WinterSnowfall** [comment]
> However fps issue still remains

As you can see from the frame counter on the HUD, the game is in fact rendering at 60 fps, however its physics calculations seem to occur at a much faster rate. That is a game bug and not something we can address, since physics in this case are not tied to fps.

**Comment by mrdeathjr28** [comment]
> > However fps issue still remains
> 
> As you can see from the frame counter on the HUD, the game is in fact rendering at 60 fps, however its physics calculations seem to occur at a much faster rate. That is a game bug and not something we can address, since physics in this case are not tied to fps.

Curiously i test opengl renderer (present in this game too) and fps issue still remains

![kotogl](https://github.com/user-attachments/assets/6c70bcdf-b86d-4607-899f-ca421462e067)

And back to renderer curiously in last test using intel uhd 630 works ok (textures missing in some parts but fps work correctly)

https://www.youtube.com/watch?v=thHVxRA4Eyw
