### ISSUE TITLE
You need a DX11 capable GPU!

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [doitsujin/dxvk#454]
System information
    GPU: HD 8750M
    Driver: Mesa 18.1.1 (Padoka stable)
    Wine version: 3.10 staging
    DXVK version: 0.54

When I try to run 32bit game like Crysis 3, it doesn't run on 64bit environment or 32bit environment, and it gives me an error message : "You need a DX11 capable GPU to play Crysis3".

[Crysis3_dxgi.log](https://github.com/doitsujin/dxvk/files/2134089/Crysis3_dxgi.log)

The Witcher 3 Wild Hunt, and Rise of The Tomb Raider run well on 64bit environment, but Middle Earth Shadow of Mordor GOTY gives me the same error message : "Installed video device doesn't support DirectX 11 features".

[ShadowOfMordor_d3d11.log](https://github.com/doitsujin/dxvk/files/2134071/ShadowOfMordor_d3d11.log)
[ShadowOfMordor_dxgi.log](https://github.com/doitsujin/dxvk/files/2134072/ShadowOfMordor_dxgi.log)

I run all the game with DRI_PRIME=1 to ensure that my discrete GPU is running the game.

Any help will be appreciated.

**Comment by baka0815** [comment]
Did you install both the x32 and x64 DXVK libraries into your WINE prefix? Have you vulkan libs for both 64 and 32 bit installed?

**Comment by ahmed-elsayed2017** [comment]
I have a separate 32bit Wine prefix with x32 DXVK libraries installed, and my main Wine prefix have x64 DXVK libraries installed.

When I open Synaptic Package, and search for Vulkan, I see libvulkan1, libvulkan1:i386, mesa-vulkan-drivers, and vulkan-utils are already installed.

**Comment by MrChebik** [comment]
You need to install 'libvulkan1'.
And replace dll from: 
- x32 to windows/syswow64
- x64 to windows/system32

**Comment by doitsujin** [comment]
You probably don't have 32-bit vulkan drivers installed (only the *loader*).

**Comment by artivision** [comment]
#195

Write to ~/.bashrc and then update bashrc with: source ~/.bashrc.

Replace radeon with nvidia if you have Nvidia.

Prime doesn't work here.

**Comment by ahmed-elsayed2017** [comment]
@artivision It doesn't work on my case.

The problem is : when I open any 32bit game with Wine without using DXVK, it runs, but when I use DXVK it gives me this error.

@doitsujin how to install 32-bit vulkan drivers. I can't find it in Synaptic Package Manager.

**Comment by artivision** [comment]
Also make sure that you are on amdgpu and not radeon.

**Comment by sarether** [comment]
Update Mesa or downgrade DXVK.
