### ISSUE TITLE
[Morrowind] Flickering and glitched textures

### ISSUE THREAD

**Issue by serpenscaput** [doitsujin/dxvk#4540]
### Software information
Playing Morrowind with latest MGE XE, shaders and per pixel lighting enabled, I'm experiencing texture flickering all over the place. Some textures don't even display: I'm seeing white objects. Problems are visible in Balmora already. Previous version had no issues.

### System information
- GPU: Radeon RX 6500M
- Driver: 24.12.1
- Wine version:  N/A
- DXVK version: 2.5.2

**Comment by Blisto91** [comment]
Hi there. This should already be fixed. Try this build https://github.com/doitsujin/dxvk/actions/runs/12435734651
