### ISSUE TITLE
Windows 10. Assassin's creed II. Camera shakes

### ISSUE THREAD

**Issue by DoucheCase** [doitsujin/dxvk#4541]
In-game camera shakes when using DXVK.
P.S. I understand that the project does not officially support Windows, so I apologize for the irrelevant bug report.

I tried next versions of DXVK: 1.5, 2, 2.5.1.
Installed NVIDIA Driver: 553.45 (for last Vulkan version. Before tried with 566.36)

### Software information
Game: **Assassin's creed II**
Settings:
- VSync: ON
- Resolution: 1920x1080@60HZ
- MultiSample: x8
- Environment Quality: 3
- Texture Quality: 2
- Shadow Quality: 2
- Reflection Quality: 2
- Character Quality: 2
- PostFX: 1

### System information
- GPU: laptop NVIDIA GeForce GTX 1050 2GB
- Driver: 553.45
- Wine version: none
- DXVK version: 2.5.1

### Apitrace file(s)
- none (If there is interest, I will create an apitrace)

### Log files
[AssassinsCreedIIGame_d3d9.log](https://github.com/user-attachments/files/18221878/AssassinsCreedIIGame_d3d9.log)

[Video](https://youtu.be/nwuvRKjAfFc)

**Comment by Blisto91** [comment]
Hi there and thank you for the report.
This specific issue is already being tracked at https://github.com/doitsujin/dxvk/issues/2249
