### ISSUE TITLE
DXVK v2.5.2 EDID

### ISSUE THREAD

**Issue by mebabo1** [doitsujin/dxvk#4544]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information
Will the game perform poorly if EDID data is unavailable?

### System information
- GPU: amd
- Driver:
- Wine version: wine9.22
- DXVK version: DXVK v2.5.2

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
[ HID ]
  Connected Count : 1
  [0] [Keyboard]

err:   readMonitorEdidFromKey: Failed to get EDID reg key size
err:   DXGI: Failed to parse display metadata + colorimetry info, using blank.
info:  Setting display mode: 1280x720@120
info:  Setting display mode: 1280x720@120
=========================================================
	Application Start
=========================================================
0230:err:service:device_notify_proc failed to open RPC handle, error 1722
[LOG #002](12:18:32) Load Common Resource...
[LOG #003](12:18:32) cAudioPool::setupDatabase: Total:1405
[LOG #004](12:18:32) cAudioPool::setupDatabase: Total:50
[LOG #005](12:18:32) cAudioPool::setupDatabase: Total:2817
[LOG #006](12:18:32) cAudioPool::setupDatabase: Total:2817
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Color space:  VK_COLOR_SPACE_SRGB_NONLINEAR_KHR
info:    Present mode: VK_PRESENT_MODE_MAILBOX_KHR (dynamic: no)
info:    Buffer size:  1280x720
info:    Image count:  6
[LOG #007](12:18:34) Database setup ... 0.0364 sec
[LOG #008](12:18:34) Common Resource setup ... 2.18 sec
info:  Setting timer interval to 1000 us
info:  Restoring display mode: 1280x720@120
info:  Setting display mode: 1280x720@120

**Comment by K0bin** [comment]
No.

**Comment by mebabo1** [comment]
Thank you for your response
