### ISSUE TITLE
Port Royale 2 Graphical Glitches

### ISSUE THREAD

**Issue by Emalcat** [doitsujin/dxvk#4545]
Please describe your issue as accurately as possible.

If you use Windows, please check the following page: https://github.com/doitsujin/dxvk/wiki/Windows

### Software information

the retail version of Port Royale 2 has some weird glitches when I play it with DXVK: there is some flickering ingame and the water is green/black when it's supposed to be blue, tested with both AMD and an integrated intel GPU from a laptop
Tested the GOGn version and has the same problem

### System information

- GPU: Intel Xe
- Driver: 32.0.101.6325
- DXVK version: 2.5.2

[PR2_d3d9.log](https://github.com/user-attachments/files/18231024/PR2_d3d9.log)

**Comment by WinterSnowfall** [comment]
It should already be fixed, try with [this](https://github.com/doitsujin/dxvk/actions/runs/12435734651/artifacts/2349576952) build. I gave the game a go yesterday and it looked fine.

**Comment by Emalcat** [comment]
> It should already be fixed, try with [this](https://github.com/doitsujin/dxvk/actions/runs/12435734651/artifacts/2349576952) build. I gave the game a go yesterday and it looked fine.

Yup, works for me on my laptop
I have no access to my AMD machine RN, I'll let you know

**Comment by WinterSnowfall** [comment]
No worries, I'm sure it will be fine on any system. It's a problem we're well aware of, that unfortunately slipped into the latest release binaries.
