### ISSUE TITLE
DXVK v2.5.2 The problem with the TES 4 Oblivion game

### ISSUE THREAD

**Issue by Metronic** [doitsujin/dxvk#4547]
Operating system
Windows 10 21H2 ( LTSC 2021 ) x64

Software information
The Elder Scrolls IV: Oblivion

System information
- GPU AMD RX 480 G1 Gaming 8G
- Driver: Adrenalin Edition 24.9.1
- DXVK version: 2.5.2 

Problem with the game display ( possibly with shaders ) 
There are other problems in games as well DXVK 2.5.2 in GTA 4 ( The Invisible main character )
On DXVK 2.5.1 and on previous versions, everything was fine in many games.
When upgrading to a new version of DXVK, I usually delete the file "dxvk-cache" and other temporary files too
In the main menu of the game everything is fine with the image

![Oblivion_2024_12_24_08_24_53_787](https://github.com/user-attachments/assets/4319e75f-72ee-4ad2-b286-e9eb8c8dfedd)

![Oblivion 2024-12-24 08-44-40](https://github.com/user-attachments/assets/d1319fb2-b336-495a-9099-9e58840b58f1)

![Oblivion 2024-12-24 08-44-42](https://github.com/user-attachments/assets/dda15806-7461-4dda-a491-43cea932d5af)

![Oblivion 2024-12-24 08-44-41](https://github.com/user-attachments/assets/009d6bf3-4589-4bf6-ab0a-5de0780f23c4)

**Comment by K0bin** [comment]
Test master. This is most likely already fixed.

**Comment by Metronic** [comment]
So we'll have to wait for the new version of DXVK where it's already fixed ?
For now, it would be logical to use version 2.5.1. There are fewer problems with it in games.
Thought the file dxkv.conf was affecting this last one version dxvk. It turned out that not quite it so
