### ISSUE TITLE
Black textures in Midnight Club II

### ISSUE THREAD

**Issue by PlayNeth** [doitsujin/dxvk#4549]
Ground textures are completely black, but it also seems to affect buildings and cars too from time to time. Only seems to happen with DXVK as WineD3D looks correct

### Software information
Midnight Club II, no settings changed -- jumped straight into freeroam

### System information
- GPU: Intel UHD 600
- Driver: Mesa/i915
- Wine version: 10.0 rc3
- DXVK version: 2.5.2

### Log files
[game.log](https://github.com/user-attachments/files/18241600/game.log)

**Comment by Blisto91** [comment]
Do you know if this work correctly with 2.5.1?

**Comment by PlayNeth** [comment]
It does! Probably a regression with the newest release

**Comment by Blisto91** [comment]
Does it work with this build? 👀 https://github.com/doitsujin/dxvk/actions/runs/12435734651

**Comment by PlayNeth** [comment]
Yep!
