### ISSUE TITLE
Games  which use DXVK get massive FPS drop after 30 - 60 minutes active gameplay

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [doitsujin/dxvk#4555]
In current moment i detected such problem in two games under Proton . 
Last Epoch and The Elder Scrolls Online. 
Both games start to work fine if to start them using PROTON_USE_WINED3D=1 ie if to exclude usage Vulkan translation. 

Problem manifest following way: 
You start game and get good a lot of FPS and after a while about 30 - 60 minutes you start to detect stutters  and if to start FPS overlay it is quite visible FPS instability until game become completely unplayable.   
In current moment i also excluded thermal throttling factor on CPU and GPU.
In current moment i research possibility to make normal logging to catch exact moment.
 

### Software information
Last Epoch and The Elder Scrolls Online
settings not important and quite a lot of people in internet have this issue without real solve.
### System information
- GPU:   NVIDIA GeForce RTX 4070 Ti Super
- Driver:  Driver Version: 550.135        CUDA Version: 12.4
- Wine version: Latest Proton from steam with Hotfix. I also tested on Proton 9 and 8 and Experimental
- DXVK version:  Latest inside proton included 

### Apitrace file(s)
- Put a link here

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files

it is bit not easy to generate log file because log file generation speed is with PORTON_LOG=1 is about 1Tbyte  for 10 minutes. I not have space on filesystem before issue appear.

**Comment by K0bin** [comment]
Sounds like #4436

**Comment by jpVm5jYYRE1VIKL** [comment]
Nope not sure. I seen such issue during all investigations but for me all another games work fine. For example in thread was mentioned Cyberpunk 2077 and Hogwarts Legacy but on my systems it works smooth without any problem . But to exclude i will try do suggested workaround with LD_PRELOAD and if it is works then will close case in favor $4436 .

**Comment by jpVm5jYYRE1VIKL** [comment]
closed in favor to #4436
