### ISSUE TITLE
Environment variable for anisotropy on windows?

### ISSUE THREAD

**Issue by HitoM43** [doitsujin/dxvk#4556]
Is there an environment variable for windows that forces anisotropy globally on all games with dxvk applied?
Thanks!

**Comment by Blisto91** [comment]
Name `DXVK_CONFIG` and value `d3d11.samplerAnisotropy = 16; d3d9.samplerAnisotropy = 16`

**Comment by HitoM43** [comment]
Works! Tried without " ".
Thank you!
