### ISSUE TITLE
The Sims 2: objects use wrong textures in 2.5.2

### ISSUE THREAD

**Issue by Cosmatevs** [doitsujin/dxvk#4558]
As of version 2.5.2, some 3D objects in The Sims 2 use textures that don't belong to them:
![Sims2 2 5 2](https://github.com/user-attachments/assets/413d4741-b433-4fdb-b749-ce96d032c596)
The same scene with the same game setup in 2.5.1:
![Sims2 2 5 1](https://github.com/user-attachments/assets/e276c5dc-f905-4c56-ac93-cbe6d8dc09ab)
Logs from both versions are almost the same:
[2.5.2 Sims2EP9RPC_d3d9.log](https://github.com/user-attachments/files/18265502/2.5.2.Sims2EP9RPC_d3d9.log)
[2.5.1 Sims2EP9RPC_d3d9.log](https://github.com/user-attachments/files/18265503/2.5.1.Sims2EP9RPC_d3d9.log)

You can also find similar reports on Reddit:
https://www.reddit.com/r/sims2help/comments/1hn59yx/new_hpintel_laptop_graphic_glitches/
https://www.reddit.com/r/sims2help/comments/1hk9drk/how_to_fix_this_sht/
https://www.reddit.com/r/sims2/comments/1hlnh7e/something_cursed_for_your_amusement_dxvk/

### Software information
The Sims 2
high settings
[RPC launcher](https://lazyduchess.tumblr.com/post/631915230388158464/sims2rpc-mod-launcher-for-mansion-garden)

### System information
- GPU: NVIDIA GeForce GTX 1660 Ti / Intel(R) UHD Graphics 630
- Driver: 31.0.15.5222 / 31.0.101.1999
- OS: Windows 11
- DXVK version: 2.5.2 (x32, d3d9)

**Comment by Blisto91** [comment]
Hi there. This should already be fixed on master. Try this build https://github.com/doitsujin/dxvk/actions/runs/12435734651

**Comment by Cosmatevs** [comment]
@Blisto91 Yeah, this build fixes the issue. Thanks.
