### ISSUE TITLE
Fallout New Vegas: problem with light sources

### ISSUE THREAD

**Issue by tomov15** [doitsujin/dxvk#4559]
the light source breaks the texture of the ground outside the radius of light, flickering occurs at a certain camera angle, pieces of the earth, road, and other details become bright or vice versa without applying light where it is needed

![FalloutNV_2024_12_28_13_27_58_866](https://github.com/user-attachments/assets/bfb0b850-da7c-4fd0-b8b5-e3d894c5b43a)
![FalloutNV_2024_12_28_04_10_22_414](https://github.com/user-attachments/assets/00867709-50b7-41b1-9442-50e4a5342634)

https://youtu.be/wAeDYimK1zw

### Software information
New Vegas TTW, Ultra, AFx16, AAx4. running via MO2, mods are currently disabled

### System information
- Windows 10 x64
- GPU: RTX 4060 Ti
- Driver: 566.03
- DXVK version: 2.5.2

[FalloutNV_d3d9.log](https://github.com/user-attachments/files/18265538/FalloutNV_d3d9.log)

**Comment by Blisto91** [comment]
Hi there. Can you check if it still happens on current master? https://github.com/doitsujin/dxvk/actions/runs/12435734651

**Comment by tomov15** [comment]
I checked this and can confirm that the problem no longer exists. the same as before when I was moving from 2.5.2 to 2.5.1, thanks
