### ISSUE TITLE
World of Warcraft rendering distortion when MSAA is enabled

### ISSUE THREAD

**Issue by Kerrung** [doitsujin/dxvk#456]
Hi, @doitsujin !
One of the Mesa developers [said that this is not a Mesa bug in his opinion](https://bugs.freedesktop.org/show_bug.cgi?id=106595).

All looks fine when no any AA enabled:
![wow-dxvk-no_any_aa_ all_looks_fine](https://user-images.githubusercontent.com/36989404/41871122-676517dc-78d7-11e8-9444-02978b7c8062.png)

But World of Warcraft has a rendering distortion when MSAA(x2-x8) is enabled:
![wow-dxvk-msaax8](https://user-images.githubusercontent.com/36989404/41871219-b9212c1e-78d7-11e8-8427-3725d20bf6f1.png)

### Software information
World of Warcraft, any graphics settings used, but MSAA is enabled.

### System information
- OS: Arch Linux
- GPU: AMD Radeon HD7770
- Driver: AMDGPU Linux 4.17.2, today's freshest Mesa-git
- Wine version: today's freshest Wine-git + Staging-git
- DXVK version: 4f28d57

### Apitrace file(s)
- Sadly, but I absolutely haven't any more idea how I can record a apitrace, because it return only a lot of error messages, but it unfortunately don't creates a trace file. I tried recording a apitrace with WineD3D and then even with DXVK, but the trace file was not created anyway. This works for other games, but unfortunately does not work with WoW. I also tried it on Windows, but no result too...

### Log files
- [wow-wine-dxvk-console-output.txt](https://github.com/doitsujin/dxvk/files/2134519/wow-log.txt)
- [Wow-64_d3d11.log](https://github.com/doitsujin/dxvk/files/2134522/Wow-64_d3d11.log)
- [Wow-64_dxgi.log](https://github.com/doitsujin/dxvk/files/2134523/Wow-64_dxgi.log)

Please, tell me if you need any more info or logs etc...

**Comment by doitsujin** [comment]
> One of the Mesa developers said that this is not a Mesa bug in his opinion.

The DXVK bug which causes the Vulkan validation errors was fixed in 0.60.

**Comment by Kerrung** [comment]
>Please run the game with validation layers enabled and post the output.

@doitsujin ok, but I will do it tomorrow or maybe the other day because now I have gone to bed.
thank you.

**Comment by Worfhard** [comment]
MSAA should render correctly if you disable "Multisample Alpha-Test" at least on a RX 480 mesa-git llvm-svn-7. Otherwise I get the same kind of distortion.

**Comment by doitsujin** [comment]
@Worfhard do you happen to know what exactly that option does, or rather, how exactly it works?

**Comment by hakzsam** [comment]
@Worfhard if you have a RX480, can you record a trace of the problem using renderdoc please?

**Comment by Kerrung** [comment]
@hakzsam World of Warcraft has a free trial unlimited in time. So you can try to test this game yourself.
[Free download here](https://www.battle.net/download/getInstallerForGame?os=win&locale=ruRU&version=LIVE&gameProgram=BATTLENET_APP).

To reproduce this issue you need enable "Multi-sample Alpha-Test" simultaneously with MSAA.

**Comment by Kerrung** [comment]
@doitsujin 
>The DXVK bug which causes the Vulkan validation errors was introduced after you filed the Mesa bug
report and has been fixed in 0.60. This issue must be unrelated, but I can't help you without a trace file.
Please run the game with validation layers enabled and post the output.

Mesa (git) 18.2.0_devel.103211.99c6cae227
DXVK a196451
Wine-git [86864486be](https://source.winehq.org/git/wine.git/commit/86864486be64a277f6edf8e66709cd0f17a4eed9) + Staging-git [729a9eb](https://github.com/wine-staging/wine-staging/commit/729a9ebaddc178715c4a3dbb85f8c53af82ecc5d)

This [console output](https://github.com/doitsujin/dxvk/files/2153167/wow_VK_INSTANCE_LAYERS.txt) for some reason turned out to be very short, but I installed the [vulkan-validation-layers](https://www.archlinux.org/packages/extra/x86_64/vulkan-validation-layers/) Arch Linux package and ran the following command:

$ env VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_standard_validation WINEDEBUG=-all WINEPREFIX=~/.wine wine64 start /unix '/home/user/.wine/drive_c/Program Files (x86)/World of Warcraft/Wow-64.exe'

WARNING: radv is not a conformant vulkan implementation, testing use only.
ATTENTION: default value of option mesa_glthread overridden by environment.
WARNING: radv is not a conformant vulkan implementation, testing use only.
WARNING: radv is not a conformant vulkan implementation, testing use only.
WARNING: radv is not a conformant vulkan implementation, testing use only.
WARNING: radv is not a conformant vulkan implementation, testing use only.
mesa: for the -simplifycfg-sink-common option: may only occur zero or one times!

It's short, but that's all there is. Tell me please if I did something wrong.
Regards.

**Comment by fuchsi** [comment]
Multi-sample Alpha-Test with any MSAA option enabled shows similar distortions.

GPU: Radeon R9 380
Kernel: 4.16.9-gentoo
Mesa Version: 18.1.4
DXVK Version: 0.62
Wine: wine-staging-3.12

Output with Validation Layers: [wow.log](https://github.com/doitsujin/dxvk/files/2195977/wow.log)

I think the important part is: 

```
(null)(ERROR / SPEC): msgNum: 15 - Shader requires extension VK_KHR_shader_draw_parameters but is not enabled on the device
    Objects: 1
       [0] 0x0, type: 0, name: (null)
Validation(ERROR): msg_code: 15: Object: VK_NULL_HANDLE (Type = 0) | Shader requires extension VK_KHR_shader_draw_parameters but is not enabled on the device
```

I hope this helps.

**Comment by doitsujin** [comment]
> I think the important part is:

That's a bug in the validation layers which has already been fixed in newer versions.

**Comment by Olie440** [comment]
It's a bit late but I've done a trace and turned on validation both with the option enabled and the option disabled. I've included all the generated files and the output from stdout. I ran the same scene for both (human new char scene) so the only difference should be the option being on and off.
[wow-trace.zip](https://github.com/doitsujin/dxvk/files/2516542/wow-trace.zip)
Let me know if

**Comment by K0bin** [comment]
That's not an apitrace.

**Comment by Olie440** [comment]
@doitsujin Thanks for getting back so fast. It took me a while to MinGW64 setup but i've given https://github.com/doitsujin/dxvk/commit/a53e05339174ae626d1207f636c69e548fcdd6ee a test and its now throwing different validation errors. Here's the log: 
[wow-validation-a53e053.txt](https://github.com/doitsujin/dxvk/files/2517074/wow-validation-a53e053.txt)

**Comment by doitsujin** [comment]
But does it fix the rendering errors?

The new errors happen because the validation layers don't support transform feedback yet.

**Comment by Olie440** [comment]
Rendering errors are still present in that build.

**Comment by Olie440** [comment]
I tried to do a api trace using the x64 dll's but it caused the game to crash. It still output data though, i'm not sure how useful this will be but ill include it anyway: [Wow-a53e053.trace.zip](https://github.com/doitsujin/dxvk/files/2518226/Wow-a53e053.zip)

**Comment by doitsujin** [comment]
Completely useless, sadly.

**Comment by Olie440** [comment]
Thought as much :/ is there anything else I could run to help debugging?

**Comment by Dehir** [comment]
Guess this bug has something to do (is the same bug) with the bug im facing with rx480 too. It relates to all effects that are present and gets worse in example raids/dungeons where is lots of areal spells/effects happening. Tryed to debug this out but havent been able to make proper debug setup to make anything out. This is more Vulkan problem atm than DXVK?

**Comment by mati865** [comment]
WoW with everything maxed out doesn't have glitches on Nvidia so I'd blame Mesa.
Somebody could also try with AMDVLK and see if it gets better.

**Comment by doitsujin** [comment]
I finally got battle.net and WoW to work, will investigate this issue.

**Comment by doitsujin** [comment]
Should be fixed with the above commit.

**Comment by doitsujin** [comment]
Nevermind, that fix is wrong and doesn't fix the problem, it's just that WoW randomly lost my settings.

**Comment by Olie440** [comment]
Thank you for taking the time to looking into it :smiley:

**Comment by doitsujin** [comment]
Fixed in mesa by [this](https://gitlab.freedesktop.org/mesa/mesa/commit/ee8488ea3b99ad0632e5eac6defcef0264d8782c) commit.
