### ISSUE TITLE
DXVK 2.5.2 breaks off-screen framebuffer rendering

### ISSUE THREAD

**Issue by Arcitec** [doitsujin/dxvk#4561]
It seems like the issue is the off-screen framebuffers. They are getting mixed-up. Instead of drawing a minimap, it draws a copy of the game world camera. And on the login screen, it draws a button/texture on top of the main window texture, etc. It's really messed up since 2.5.2.

Reverting to **DXVK 2.5.1** fixes it.

I think that it also worked in DXVK 2.5.1 d956b18 which was an in-between git master version between 2.5.1 and 2.5.2. I have that version in Bottles Flatpak, but I CANNOT check again to verify if that git version worked, because my Bottles Flatpak is broken and cannot detect my GPU when launching this particular game, so I had to switch to the native Bottles package instead, and am now using DXVK 2.5.1 to avoid the issue.

(Edit: I was able to copy `dxvk-2.5.1-1-d956b18` from Bottles Flatpak to native, and installed it. It works. So **DXVK broke sometime between d956b18 and the 2.5.2 tag**. The bug is somewhere here: https://github.com/doitsujin/dxvk/compare/d956b188edce40d34cb6b246bc73678f4143a0ce..v2.5.2)

I will include images in the next comment.

### Software information
Game: World of Warcraft 3.3.5 (It's free from https://www.warmane.com/download)
Settings: DXVK is all on default settings, running inside Bottles.

### System information
- GPU: RTX 3090
- Driver: 565.77 on Fedora 41
- Wine version: wine-ge-proton8-26
- DXVK version: 2.5.2

**Comment by Arcitec** [comment]
# DXVK 2.5.1 (Working)

![Screenshot From 2024-12-28 20-27-30](https://github.com/user-attachments/assets/5184027f-0412-45de-aab2-1ed1a9b2c9dd)

![Screenshot From 2024-12-28 20-26-51](https://github.com/user-attachments/assets/caffb18b-f011-450c-adde-5df9b62e4027)

**Comment by Arcitec** [comment]
# DXVK 2.5.2 (Framebuffers all getting mixed up and drawing into each other, mixing random game textures and world cameras etc). Most noticeable in the top right (minimap).

![Screenshot From 2024-12-28 20-28-10](https://github.com/user-attachments/assets/47d5002b-0eae-4d69-a52c-bf4f17b03ca9)

![Screenshot From 2024-12-28 20-28-27](https://github.com/user-attachments/assets/f95f7018-3776-45e5-b78b-f40e47675a2c)

![Screenshot From 2024-12-28 20-28-31](https://github.com/user-attachments/assets/eab5efca-d159-4b1e-b493-997a234a1883)

![Screenshot From 2024-12-28 20-28-38](https://github.com/user-attachments/assets/5f2d4f14-35bd-45b2-a095-57c8f1f5777d)

**Comment by Blisto91** [comment]
Hi there.
This should already be fixed on current master. Could you give it a go to verfiy? The text at the bottom of this link have a download of it https://github.com/doitsujin/dxvk/actions/runs/12435734651

**Comment by Arcitec** [comment]
@Blisto91 @K0bin Ah, so there's been one commit since 2.5.2, this one:

https://github.com/doitsujin/dxvk/commit/1eb0c687a6748d8268dd84f466a1378de4fb3c10

And now there's no leftover locations where it replaces the whole mask. It's all bit-or/and now:

https://github.com/doitsujin/dxvk/blob/1eb0c687a6748d8268dd84f466a1378de4fb3c10/src/d3d9/d3d9_device.cpp

Great news. It fixes the entire issue! Everything's working beautifully again. Thank you so much. Your expertise is incredibly impressive. This Direct3D translator is such a stunningly great piece of work. Thank you for everything you do to make gaming on Linux great. :heart:

**Comment by K0bin** [comment]
Thanks for confirming. I basically debugged the issue with WoW, so I would've been surprised if it wasn't fixed but you never know.

Also thanks for the kind words. :smiley:

**Comment by Arcitec** [comment]
@K0bin Perfect. I have played for about 2 hours now and everything is working. 👍 😄
