### ISSUE TITLE
Hearts of iron 3 - flag and text not showing

### ISSUE THREAD

**Issue by maggiolinonero** [doitsujin/dxvk#4563]
Dear all, I would like to congratulate you on your incredible work.
Manually installing 32 dxvk 2.5.2, the game is very stable, even using the black ice mod. However, there are two problems: the flags are not rendered (all black) and the text of the diplomatic and menu section is blurry, as shown in the screenshot. I did several tests, both with steam - proton and with wine base, and using previous versions of dxvk. How could it be solved? Thank you

![Istantanea_2024-12-28_21-00-39](https://github.com/user-attachments/assets/b6f2ac01-a77b-4b27-9621-774498b5ed3e)
![Istantanea_2024-12-28_21-01-19](https://github.com/user-attachments/assets/5739dfb6-d083-47cb-b38b-9416f08fd950)

### Software information
paradox interactive Hearts of Iron 3. 4.02 - complete collection. tested base game and modded with Black ice. Steam and GOG versions.

### System information
- GPU: intel cometlake-u GT2 8086:9b41 rev02
- Driver: Mesa intel UHD Grpahic CML GT2. Kernel driver in use: i915
- Wine version: 9. Proton 9, experimental
- DXVK version: 2.5.2

### Log files
please find attached game log. 
[game.log.txt](https://github.com/user-attachments/files/18269359/game.log.txt)

**Comment by K0bin** [comment]
Check master, we already fixed a pretty bad bug that impacted older D3D9 and D3D8 games.

**Comment by maggiolinonero** [comment]
> Check master, we already fixed a pretty bad bug that impacted older D3D9 and D3D8 games.

thank you very much for quick response! I'll try to compile the latest development version.

**Comment by WinterSnowfall** [comment]
> I'll try to compile the latest development version.

To be fair you don't *have* to compile it yourself, you can just grab the binaries generated by the GitHub Actions CI: https://github.com/doitsujin/dxvk/actions/runs/12435734651 (note that you need to be logged into GitHub to see the download link at the bottom of that page).

**Comment by maggiolinonero** [comment]
It seems work

**Comment by K0bin** [comment]
Thanks for confirming.
