### ISSUE TITLE
Evil Within 1 fails with dxvk

### ISSUE THREAD

**Issue by NoMore201** [doitsujin/dxvk#458]
The Evil Within 1 fails to launch using dxvk with the error `D3D11CreateDeviceAndSwapChain FAILED with error (203)`. If I try to launch it in a clean prefix without dxvk, it starts but with very bad performance.

### Software information
The evil within 1 demo from steam

### System information
- GPU: Nvidia 840m (optimus laptop, using nvidia-xrun)
- Driver: 396.24
- Wine version: staging 3.11
- DXVK version: 0.60

### Apitrace file(s)
[EvilWithin.trace.gz](https://github.com/doitsujin/dxvk/files/2141079/EvilWithin.trace.gz)

### Log files
[EvilWithin_d3d11.log](https://github.com/doitsujin/dxvk/files/2141082/EvilWithin_d3d11.log)
[EvilWithin_dxgi.log](https://github.com/doitsujin/dxvk/files/2141083/EvilWithin_dxgi.log)

**Comment by doitsujin** [comment]
Your driver does not support `VK_EXT_vertex_attribute_divisor`, please update to 396.24.02 (or use DXVK 0.54). See #435.

**Comment by alex9099** [comment]
@doitsujin where can one get that version of the driver? I have 396.24 and i don't have that feature
