### ISSUE TITLE
[0.60] E_FAIL due to lack of layerssdk libraries?

### ISSUE THREAD

**Issue by grappas** [doitsujin/dxvk#459]
![bez tytulu](https://user-images.githubusercontent.com/1036957/41984828-ed4e321a-7a31-11e8-8377-3733ba5661a9.png)

**Comment by grappas** [comment]
https://docs.microsoft.com/pl-pl/windows/desktop/direct3d11/d3d11-graphics-reference-returnvalues

**Comment by doitsujin** [comment]
Can you please give me **any** information on what you are doing?

**Comment by doitsujin** [comment]
Closing due to the lack of data.
