### ISSUE TITLE
Alias for latest dxvk release?

### ISSUE THREAD

**Issue by shmerl** [doitsujin/dxvk#462]
Some projects like winetricks [can benefit](https://github.com/Winetricks/winetricks/issues/999#issuecomment-401112429) from linking to a fixed URL that always points to the latest release of dxvk, to avoid constantly bumping the version in their code. Is there any way to do it?

[This](https://help.github.com/articles/linking-to-releases/) suggests that it can be https://github.com/doitsujin/dxvk/releases/latest but it doesn't seem to do anything.

**Comment by shmerl** [comment]
https://api.github.com/repos/doitsujin/dxvk/releases/latest also produces:
```
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/repos/releases/#get-the-latest-release"
}
```

**Comment by doitsujin** [comment]
I'm not aware of any way to do this on github.

There might be some workarounds like adding a text file to the repo containing a URL pointing to the latest release or something, but that's kind of cumbersome.

**Comment by ZeroFault** [comment]
You could create a tagged release called latest. Then edit the tag to update the binaries each release if you want.

**Comment by shmerl** [comment]
You can also use Github "pages" and simply create some fixed link that always points to the latest release.

**Comment by austin987** [comment]
Editing tags is bad practice, afaik..

**Comment by shmerl** [comment]
@austin987 : May be winetrick can simply calculate the latest tag? It can use `git` for that.

**Comment by austin987** [comment]
@shmerl, that would require checking it the git repo, currently we just download the binaries.

Brainstorming: Do you have a release script? The script could provide a stable URL when publishing a release.

**Comment by ssorgatem** [comment]
There could be a file named RELEASE or VERSION, containing the latest version number/release, and the url can be deduced with just that (I do this for the dxvk-bin PKGBUILD).

**Comment by doitsujin** [comment]
Looks like the links pointing to the raw repository files are stable (such as https://raw.githubusercontent.com/doitsujin/dxvk/master/README.md) so i guess that's actually an option.

**Comment by austin987** [comment]
@doitsujin works for me, thanks. For reference, it's at https://github.com/Winetricks/winetricks/commit/c423a85b3cfda1e6181fc8164b089842964a0794

**Comment by doitsujin** [comment]
Great, thanks for reporting back.
