### ISSUE TITLE
Wreckfest

### ISSUE THREAD

**Issue by MrChebik** [doitsujin/dxvk#467]
1. In game, I see DXVK_HUD the frame counter shows 26-35 frames near other machines, and in fact - about 15-20.
2. During the race, every 10-15 seconds - falls FPS to 7-11, until you pass the first lap. Later, there is no drop down until the finish. At the end of the circle (3), one more drop down was noticed.

### Software information
Wreckfest, all settings to low.

### System information
- GPU: Intel HD 5500
- Driver: Mesa 18.1.2
- Wine version: 3.10-staging
- DXVK version: 0.61

### Apitrace file(s)
- I could not write apitrace. I waited 10 minutes, the game not opened.
[Google Drive](https://drive.google.com/file/d/1hYT3rCHeNgUJ7kLth9G5vVR4ac5VPksy/view?usp=sharing)

### Log files
- [d3d11.log](https://pastebin.com/2mQ44R1q) 
- [dxgi.log](https://pastebin.com/WWdvNP8k)

**Comment by doitsujin** [comment]
And what exactly is your issue? If you expect to run this game at a playable framerate on that kind of hardware, you're out of luck, DXVK won't magically convert your Intel GPU to a 1080 Ti.

**Comment by MrChebik** [comment]
I know, I'm not trying to run it on ultra settings. The game itself goes to 360p very well, near 35 FPS. But the falling FPS from time to time is not very good.

For example, the guy launched game on the [HD 4400](https://www.youtube.com/watch?v=Ls259v4DncE), yeah FPS is not big, but he does not have any subsidence like me.

Maybe DXVK does not correctly load resources during the race? Or falling FPS - does not depend on DXVK?

**Comment by doitsujin** [comment]
Sorry, but your hardware is **way** below the system requirements. It's nice if something runs fine regardless but you cannot take that for granted.

**Comment by MrChebik** [comment]
Hmm...
To the last, I will leave vivid examples of the problem:
- **Metro 2033 Redux** [[1](https://youtu.be/8S6REuGWXQQ?t=1m35s)] (You can pay attention to what the FPS was before the fall and after)
- **Darksiders Warmastered Edition** [[1](https://youtu.be/daO-9mY440U?t=44s)] [[2](https://youtu.be/daO-9mY440U?t=5m18s)] [[3](https://youtu.be/daO-9mY440U?t=6m32s)]
- **Wreckfest** [[1](https://youtu.be/sQvW74-6pts?t=0m40s)] [[2](https://youtu.be/sQvW74-6pts?t=0m46s)] [[3](https://youtu.be/sQvW74-6pts?t=1m06s)] [[4](https://youtu.be/sQvW74-6pts?t=2m52s)] [[5](https://youtu.be/sQvW74-6pts?t=2m55s)]

I think this will happen in the future, in games where open worlds / lands with many objects. Although the **NFS MW 12** so clearly not observed.

--
Also, at the time of mounting of **Wreckfest**, I learned that the time of this congealing is approximately equal (for 1-2 frames the difference is sometimes)

--
I notice that with **D3D11** - there are no similar problems (**Wreckfest**)

**Comment by doitsujin** [comment]
The HUD counts the number of times that `DXGISwapChain::Present` is called. The game might be passing some weird flags there which DXVK might not handle correctly, but other than that there is no bug.

The hangs look like shader compilation stutter, which **cannot** be fixed.

**Comment by MrChebik** [comment]
Thank you!

**Comment by doitsujin** [comment]
By the way, are you compiling Mesa yourself by any chance? If so, make sure to disable **all** debugging-related options and pass `-DNDEBUG` to the compiler, otherwise shader compile times will take significantly longer than necessary. Binary packages in most distributions should be doing that already though.

**Comment by MrChebik** [comment]
Previously, I had to collect packages from the sources of Mesa. Later I'll try it, thanks!

**Comment by libcg** [comment]
Just a side note, `MESA_NO_ERROR=1` has no effect on Vulkan apps. It's only used with OpenGL that has many more runtime checks.

**Comment by MrChebik** [comment]
@libcg Really, thank you!
