### ISSUE TITLE
Fallout 4

### ISSUE THREAD

**Issue by mandruis** [doitsujin/dxvk#47]
### Software information
Fallout 4 Lowest settings and all turn off

### System information
- GPU:R9 390
- Driver:Mesa git

- Wine version: Wine 2.21 staging
- DXVK version: master git

### Apitrace file(s)
Comming soon

### Log files
- d3d11.log:
[Fallout4_d3d11.log](https://github.com/doitsujin/dxvk/files/1687506/Fallout4_d3d11.log)

- dxgi.log: 
[Fallout4_dxgi.log](https://github.com/doitsujin/dxvk/files/1687507/Fallout4_dxgi.log)

**Comment by doitsujin** [comment]
Closing this due to the lack of actual information. Fallout 4 is being worked on, and the game partially started working with 43b7e84bb502c6ff33ee041014d568694d8a5bcb.
