### ISSUE TITLE
Hellblade - Yellow fog

### ISSUE THREAD

**Issue by MrChebik** [doitsujin/dxvk#470]
I somehow ran this game earlier, and everything was more than good, I took **DXVK** from **winetricks**.

But now, with **0.61** - yellow fog.
Tried also **0.53**, **0.54**, **b62ccfe** - black screen.
May be affected by the update of the **Mesa** from 18.1.1 to 18.1.2.

### Software information
All settings to low.

### System information
- GPU: Intel HD 5500
- Driver: Mesa 18.1.2
- Wine version: 3.10-staging
- DXVK version: 0.61

### Files
- [apitrace](https://drive.google.com/file/d/1TcVqQuQ0WDJxzTNu1Rpn7JkYBIDGklTJ/view?usp=sharing)
- [d3d11.log](https://pastebin.com/7BjVfHi8)
- [dxgi.log](https://pastebin.com/6AqF65sD)

Examples: [[1](https://imgur.com/a/df9iOfg)] [[2](https://imgur.com/a/ja5TKOy)] [[3](https://imgur.com/a/bNqlozQ)]

**Comment by oscarbg** [comment]
@MrChebik unrelated but you have modified 0.6.1 to not require VK_EXT_vertex_attribute_divisor, right?

**Comment by MrChebik** [comment]
@oscarbg yes
