### ISSUE TITLE
Multithread

### ISSUE THREAD

**Issue by artivision** [doitsujin/dxvk#471]
I hope that "deferred context/multi-threaded command lists" are first priority for DXVK. The commit bc1384b can be a wrong turn, DXVK can end up like AMD's driver. Thanks for the good work.

**Comment by doitsujin** [comment]
May I ask what your point is?

**Comment by artivision** [comment]
I wanted to ask, will you implement D3D11 the Nvidia multi-threaded way or the AMD single threaded way?

**Comment by doitsujin** [comment]
D3D11 deferred contexts and command lists are already fully implemented. Command buffer recording is serialized to a single thread, the D3D11 design prevents efficient multithreading.
