### ISSUE TITLE
Outlast 2 - Light flicker

### ISSUE THREAD

**Issue by MrChebik** [doitsujin/dxvk#473]
At the Outlast 2 I have a flicker of light.

### System information
- GPU: Intel HD 5500
- Driver: Mesa 18.1.2
- Wine version: 3.10-staging
- DXVK version: 0.61

### Log files
- [d3d11.log](https://drive.google.com/file/d/1emgjUKrQvxrrlo-Yo3cFWyoC_aaSRrry/view?usp=sharing)
- [dxgi.log](https://pastebin.com/BDTq3mZW)

**Comment by doitsujin** [comment]
If you're not going to post apitraces, could you please group your reports into **one** issue? I have nothing to work with and consider reports like this one to be spam.

**Comment by MrChebik** [comment]
Sorry, my mistake. Fixed in **18.1.3**.
