### ISSUE TITLE
Stutters when MSAA or/and (Motion) Blur enabled

### ISSUE THREAD

**Issue by nickfaces** [doitsujin/dxvk#474]
Stutters in games with any other graphics settings when MSAA or/and (Motion) Blur enabled enabled

Do I need to give some log and apitrace in this case?

### Software information
GTA V, Dark Souls 3, Witcher 3, etc

### System information
- GPU: RX 580 8 Gb
- Driver: Mesa 18.2-git + LLVM 7-svn
- Wine version: staging 3.11 git
- DXVK version: 0.61

**Comment by doitsujin** [comment]
Witcher 3 runs fine with all post processing enabled on my RX 480. There is no issue with those effects specifically. MSAA just costs a lot of performance.

**Comment by nickfaces** [comment]
Thanks for replies.

"MSAA just costs a lot of performance": yes, but on windows system its works fine. So its just "dxvk overhead" ?

**Comment by jarrard** [comment]
Typically if the framerate goes below 45-50fps you will experience some micro-stutters/skipping, basically poor framerate smoothing. I suggest turning on the DXVK hud and keep track of your framerate, Linux doesn't seem to have as good framerate smoothing as it should and could be partly related to your desktop composer etc..

**Comment by nickfaces** [comment]
FPS is good, but stutters every 5 seconds if msaa enabled.
In x11 cfg enabled tearfree options, DRI3 using too

**Comment by doitsujin** [comment]
MSAA does not cause stutters. Make sure that your GPU keeps running at full clock speed.
