### ISSUE TITLE
Wine esync

### ISSUE THREAD

**Issue by artivision** [doitsujin/dxvk#475]
Its a good idea to consider Wine esync to DXVK performance goals. Keep up the good work.

**Comment by doitsujin** [comment]
I'm aware that esync exists, what is your point?

**Comment by artivision** [comment]
Nothing special, i noticed that a major performance hit isn't coming from DXVK it self. It is a good idea to always test DXVK with ESYNC on Linux in order to have a real measure VS Windows. Otherwise you will end up continuously searching for optimizations to match the native performance.

**Comment by Tk-Glitch** [comment]
I'm not sure you understand how it works. You don't have to worry about Doitsujin.
