### ISSUE TITLE
Hot Lava freeze on startup

### ISSUE THREAD

**Issue by Lahvuun** [doitsujin/dxvk#477]
All I can see is the initial splash art that says "loading". Nothing happens after this: no crash, no messages in terminal, just a frozen window. The game works with wined3d. 

### Software information
hotlava.exe, [steam link](https://store.steampowered.com/app/382560/Hot_Lava/).
Settings were set to "potato".

### System information
- GPU: Radeon RX 560
- Driver: 18.2.0-devel (git-99c6cae227)
- Wine version: 3.11 staging+pba
- DXVK version: 0.61

### Apitrace file(s)
[apitrace](https://drive.google.com/file/d/15aFObP-RqsuSBMdxIyVnVp9vnrtCSnUP/view?usp=sharing)

### Log files
- d3d11.log: [hotlava_d3d11.log](https://github.com/doitsujin/dxvk/files/2166309/hotlava_d3d11.log)
- dxgi.log:  [hotlava_dxgi.log](https://github.com/doitsujin/dxvk/files/2166308/hotlava_dxgi.log)

**Comment by doitsujin** [comment]
I'm not sure I understand what the apitrace is supposed to do, as it only contains two frames.

**Comment by Lahvuun** [comment]
My bad. The game actually closes itself and starts the Steam client, so apitrace only got so far. [This one](https://drive.google.com/file/d/1_PJc5FJCfKh7EggD9uSUJfH6N8RFiHiq/view?usp=sharing) should be better.

**Comment by doitsujin** [comment]
> I think other Unity games play well with DXVK?

Unity Engine requires stream output for pretty much everything, but i can't see any of that in your logs so that shouldn't be the issue here.

**Comment by doitsujin** [comment]
Can you check htop while trying to start the game and check whether there is a significant amount of CPU load?

I can't think of anything wrong with the updated trace, it replays fine on my end, but I did notice that the game compiles over 9000 shaders and a total of over 10000 Vulkan pipelines during the first few frames, which takes **several minutes** on my Ryzen 2700X.

**Comment by Lahvuun** [comment]
Yes, the game uses 100% of a core. Looks like it uses only one at this stage.

I am not sure if I am doing this right, but my own [retrace](https://github.com/doitsujin/dxvk/files/2167909/hotlava.retrace.log) of apitrace crashes when using DXVK. Could this be a driver issue?

**Comment by doitsujin** [comment]
> Yes, the game uses 100% of a core. Looks like it uses only one at this stage.
That would be expected. You can set `DXVK_LOG_LEVEL=debug` to monitor pipeline compilation, unfortunately it's very slow (*especially* if you built mesa in debug mode, or without setting `c_args` and `cpp_args` to `-DNDEBUG` in case you're building with Meson).

The crash is not a driver issue. I guess you recorded the trace on Wine, which implements some interfaces not present in DXVK, and that requires some hacks to make work.

I got [this](https://drive.google.com/file/d/19mfLTFJeI-xZrPNwOhsYGK8SOLo0QmZm/view?usp=sharing) trace from another user though, you should be able to replay it out of the box.

By the way, since you're running mesa-git and llvm-svn, I recommend updating both *now* if you haven't already - there was a bit of an LLVM issue with my build from yesterday causing pipeline compilation failures, but it looks like it's fixed.

**Comment by Lahvuun** [comment]
OK. I'm gonna rebuild these and report back.

Provided retrace is not crashing indeed, but I am not seeing any frames either. The retrace process is taking up a whole core as well.

>there was a bit of an LLVM issue with my build from yesterday causing pipeline compilation failures

I'm not sure if that's the case here, since other games run just fine on my setup.

Meanwhile, I tried using [placeholder shaders](https://github.com/jomihaka/dxvk-poe-hack), as well as bumping the amount of pipecompiler threads to 8. The game is now using ~350% of CPU. After about a minute I managed to get into the game, with a couple elements drawn.

**Comment by doitsujin** [comment]
> Provided retrace is not crashing indeed, but I am not seeing any frames either.

As mentioned it can take several minutes even on a fast CPU. The PoE hack is known to break a lot of games.

**Comment by Lahvuun** [comment]
No, I'm using the binary 0.61 release for all my tests. But after you posted that it's basically just a huge amount of shader compiling, I remembered this hack and thought it would make sense to try it.

**Comment by doitsujin** [comment]
That's basically what the game does, yes. If the shader combinations and pipeline state were known in advance, it would be possible to compile pipelines in parallel (i.e. use all available cores), but the game enforces the pipeline compilation on the Dx11 side.

**Comment by frostworx** [comment]
I can confirm that the game works fine here after waiting some minutes.
the intro video isn't visible, but can be skipped. arch linux with dxvk git master, nvidia blob 396.24.02 with a gtx 980ti.
