### ISSUE TITLE
Error when starting World of Warcraft

### ISSUE THREAD

**Issue by FireBurn** [doitsujin/dxvk#478]
### Software information
World of Warcraft

### System information
- GPU: Radeon M395X
- Driver: radv (latest from git)
- Wine version:  3.11 Staging
- DXVK version: 0.61

I ran with VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json as I thought I might have been having issues with using a PRIME system

### Log files
[Wow-64_dxgi.log](https://github.com/doitsujin/dxvk/files/2168580/Wow-64_dxgi.log)

**Comment by Tk-Glitch** [comment]
You'll have to export DXVK_FAKE_DX10_SUPPORT=1 for WoW to work. From reading your lo it should be enough.

**Comment by steemandlinux** [comment]
Maybe add to quirks?

**Comment by doitsujin** [comment]
Added an entry to https://github.com/doitsujin/dxvk/wiki/Common-issues, this should suffice for now.
