### ISSUE TITLE
Alien Isolation closes almost immediately..

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#48]
note other games are working with the same dxvk dxgi dll's so not a problem..

seems wants:
warn:  DxbcCompiler: Unhandled instruction: DxbcOpcode::ImmAtomicCmpExch
err:   DxbcCompiler: Unhandled PS SV input: DxbcSystemValue::PrimitiveId

### System information
- GPU: Vega 64
- Driver: adrenalin 18.1.1
- Wine version: no Run under Windows 10 latest update
- DXVK version: up to https://github.com/doitsujin/dxvk/commit/14d5054893bb14b3448702de1114dfc46ad5e53a

### Log files
- d3d11.log:
[AI_d3d11.log](https://github.com/doitsujin/dxvk/files/1688980/AI_d3d11.log)

- dxgi.log: 
[AI_dxgi.log](https://github.com/doitsujin/dxvk/files/1688981/AI_dxgi.log)

**Comment by doitsujin** [comment]
Please test again with e38cc4a0e0f109bc981be255f5c093c4b4689e90, both missing shader features are now implemented.

**Comment by popsUlfr** [comment]
It goes to the menu but after loading a save or mission it immediately crashes

### System information
- GPU: Nvidia Geforce GTX 980Ti
- Driver: 390.48 on Linux, 391.35 on Windows
- Wine version: 3.6 Staging
- DXVK version: [5fa8174](https://github.com/doitsujin/dxvk/commit/5fa8174816bd0d7a038f5ac59686ff7d21d25ecf)

### Apitrace file(s)
Can not get any trace using `apitrace.exe`, injecting `dxgitrace.dll` crashes the game immediately and produces this small trace
- [AI.trace](https://u.teknik.io/7jkkG.trace)

### Log files
* Wine :
  - d3d11.log: 
[AI_d3d11.log](https://github.com/doitsujin/dxvk/files/1911042/AI_d3d11.log)

  - dxgi.log: 
[AI_dxgi.log](https://github.com/doitsujin/dxvk/files/1911044/AI_dxgi.log)

* Windows 10 :
  - d3d11.log: 
[AI_d3d11.log](https://github.com/doitsujin/dxvk/files/1911045/AI_d3d11.log)

  - dxgi.log: 
[AI_dxgi.log](https://github.com/doitsujin/dxvk/files/1911046/AI_dxgi.log)

**Comment by doitsujin** [comment]
Can you post a wine backtrace? If you can't obtain an apitrace I *at least* need to know where it crashes.

**Comment by popsUlfr** [comment]
I managed to get an Apitrace \o/ 

With dxvk enabled it crashes immediately `d3dretrace.exe` when trying to replay on both Windows and Wine. It also crashes immediately in wined3d mode.
* Wine with wined3d the game does not crash and successfully loads the level and is playable
* Wine with DXVK the game works until the level loads and the game just exits without any backtrace.

**Backtraces** : 

- [backtrace-wined3d.txt](https://github.com/doitsujin/dxvk/files/1912341/backtrace-wined3d.txt)
- [backtrace-dxvk.txt](https://github.com/doitsujin/dxvk/files/1912342/backtrace-dxvk.txt)

After `d3dretrace.exe` crashes `qapitrace.exe` shows these warnings and errors : 

```
4 @0 IDXGIFactory5::EnumAdapters1(this = 0xa0b9938, Adapter = 1, ppAdapter = [0x47faa40]) = S_OK
failed with 0x887a0002 (DXGI_ERROR_NOT_FOUND): The object was not found. If calling IDXGIFactory::EnumAdaptes, there is no adapter with the specified ordinal. apitrace: warning: caught exception 0xc0000005 
6 @0 IDXGIAdapter3::Release(this = 0x47faa40) = 0
caught an unhandled exception
```
## Apitrace

* Windows 10 : [AI.trace.xz](https://mega.nz/#!E6RSBQ5a!_rkQJ4jLqVhsZX8a5EgtOw4lkNwo7MkGP27tU3JQOpQ)

**Comment by Tk-Glitch** [comment]
The game should now work fine on 0.61. Can you retest please ?

**Comment by oscarbg** [comment]
Yep it works now..
at least wih DXVK 0.6.1+398.24.02+ NV 970  but crashes on latest RADV padoka ppa on Vega!
closing..
