### ISSUE TITLE
[Build error] The compilation error message

### ISSUE THREAD

**Issue by Kerrung** [doitsujin/dxvk#480]
Hi, @doitsujin !
I have a compilation error message. Is it a bug or a feature?

...
[55/150] Compiling C++ object 'src/dxvk/src@dxvk@@dxvk@sta/dxvk_image.cpp.obj'.
../../dxvk-git/src/dxvk/dxvk_image.cpp: In constructor ‘dxvk::DxvkImage::DxvkImage(const dxvk::Rc<dxvk::vk::DeviceFn>&, const dxvk::DxvkImageCreateInfo&, dxvk::DxvkMemoryAllocator&, VkMemoryPropertyFlags)’:
../../dxvk-git/src/dxvk/dxvk_image.cpp:20:36: warning: variable ‘formatList’ set but not used [-Wunused-but-set-variable]
     VkImageFormatListCreateInfoKHR formatList;
                                    ^~~~~~~~~~
...

![screenshot from 2018-07-06 20-39-58](https://user-images.githubusercontent.com/36989404/42387762-ccf33ccc-815c-11e8-8cd3-38a874ea162b.png)

### System information
- OS: Arch Linux with temporary downgraded gcc 7.3 and gcc-libs 7.3, because a [Wine bug](https://bugs.winehq.org/show_bug.cgi?id=45199). 
- DXVK version: 4d1a70b

**Comment by doitsujin** [comment]
This is not even an error, it's a **warning**. Yes, I'm aware, no, I won't fix it or accept any "fixes" for it because the goal is to re-enable the image format list extension as soon as possible.

**Comment by Kerrung** [comment]
@doitsujin I understood, thank you!
