### ISSUE TITLE
Crash Bandicoot N Sane Trylogy Crash GPU

### ISSUE THREAD

**Issue by OdnetninI** [doitsujin/dxvk#481]
Running Crash Bandicoot N Sane Trilogy crashed nvidia driver after activision logo.

Dmesg Out: ![photo_2018-07-06_22-07-09](https://user-images.githubusercontent.com/1885102/42398141-f1ee9204-8168-11e8-991d-cbfc2070b891.jpg)

### Software information
Crash Bandicoot N Sane Trilogy - Steam

### System information
- GPU: Nvidia GTX 650
- Driver: 396.24.02
- Wine version: 3.11 Staging
- DXVK version: 0.61

### Apitrace file(s)
- 

### Log files
- d3d11.log:  [CrashBandicootNSaneTrilogy_dxgi.log](https://github.com/doitsujin/dxvk/files/2171795/CrashBandicootNSaneTrilogy_dxgi.log)
- dxgi.log: [CrashBandicootNSaneTrilogy_d3d11.log](https://github.com/doitsujin/dxvk/files/2171796/CrashBandicootNSaneTrilogy_d3d11.log)

**Comment by doitsujin** [comment]
Already fixed in `master`, see [this comment](https://github.com/doitsujin/dxvk/issues/267#issuecomment-401585798).
