### ISSUE TITLE
Black Screen when running (Tom Clancy's Ghost Recon Future Soldier)

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [doitsujin/dxvk#482]
System information
GPU: HD 8750M
Driver: Mesa 18.1.3 (Padoka stable)
Wine version: 3.11 staging (32 bit)
DXVK version: 0.61

Tom Clancy's Ghost Recon Future Soldier runs and I can hear its sound but I can see any thing on the screen, only a black screen.

I don't know if the game is supported with Wine or not.

[Future Soldier_d3d11.log](https://github.com/doitsujin/dxvk/files/2171921/Future.Soldier_d3d11.log)
[Future Soldier_dxgi.log](https://github.com/doitsujin/dxvk/files/2171922/Future.Soldier_dxgi.log)

**Comment by doitsujin** [comment]
Please add an apitrace.

The game seems to be using an image format which is either invalid or currently not supported:
```err:   D3D11: Cannot create texture:
  Format:  VK_FORMAT_UNDEFINED
  Extent:  2048x1024x1
  Samples: 1
  Layers:  1
  Levels:  9
  Usage:   7```

**Comment by ahmed-elsayed2017** [comment]
[Future Soldier.trace.zip](https://github.com/doitsujin/dxvk/files/2172117/Future.Soldier.trace.zip)

**Comment by ahmed-elsayed2017** [comment]
I do not know if you need that file also or not.

[Future Soldier-version[May_31_2012-17_50_07]-created[Jul_07_2018-00_25_36].dmp.zip](https://github.com/doitsujin/dxvk/files/2172133/Future.Soldier-version.May_31_2012-17_50_07.-created.Jul_07_2018-00_25_36.dmp.zip)

**Comment by doitsujin** [comment]
The trace is useless since it's basically empty. Did you use the standalone executable or the DLLs linked at the bottom of the [Wiki](https://github.com/doitsujin/dxvk/wiki/Common-issues) (which might work better)?

**Comment by ahmed-elsayed2017** [comment]
Yes, I used these DLLs in the bottom of the Wiki, but the game ended with a fatal error and produced the dmp file I uploaded in the last post.
