### ISSUE TITLE
The Division - discard resource not implemented?

### ISSUE THREAD

**Issue by Altosk** [doitsujin/dxvk#485]
### Software information
The division gets about 1 fps doesnt matter of the settings

### System information
- GPU: amd rx580
- Driver: mesa-git
- Wine version: 3.10 esync
- DXVK version: 0.61

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
[TheDivision_d3d11.log](https://github.com/doitsujin/dxvk/files/2172986/TheDivision_d3d11.log)

- dxgi.log: 
[TheDivision_dxgi.log](https://github.com/doitsujin/dxvk/files/2172988/TheDivision_dxgi.log)

**Comment by doitsujin** [comment]
It is indeed not implemented, but since the effect is completely transparent to the application, it doesn't need to be implemented for correctness. I cannot do anything about poor performance without an apitrace.

**Comment by Altosk** [comment]
setting dxvk_log_level to none fixes the performance issue.

**Comment by doitsujin** [comment]
c8c6f24b63e66938e4a9af6514681f4e17517e4a fixes the log spam.

**Comment by doitsujin** [comment]
Having thought about this for a bit, it does not make sense for DXVK to implement these functions. In theory, they request the driver to allocate new memory for a backing resource, which *can* in some cases improve things, but I don't see how DXVK could benefit from this. In situations where doing so is truly beneficial, it already does so anyway.
