### ISSUE TITLE
Killing Floor 2 strange input acceleration issue

### ISSUE THREAD

**Issue by Lukypie** [doitsujin/dxvk#486]
Honestly it is not a game specific issue, I got this strange input latency in other games as well, like GTA 5, but not in overwatch, or at least I've not experienced it yet.

Every game or desktop setting does not matter, I use a KDE desktop with libinput drivers, Manjaro Linux (always the cutting edge packages) and a nvidia 1060 3gb card. Ryzen 5 processor and a Zowie FK2 mouse, 144Hz Benq monitor.

Seriously I don't know if that has something to do with my 1000hz mouse polling rate w the 144hz monitor, there is a strange input latency sometimes even with high framerates, it seems to skip pixel and accelerating the visual more than it should, even when  disabling completely the desktop mouse acceleration (if that has something to do with it, idk)
I don't even know if that is related to wine or dxvk honestly, what is your experience about? Can it be that in some way wine/dxvk takes the desktop mouse settings? Shouldn't it ignore the linux desktop mouse settings and using raw input then? Maybe I'm wrong.
I repeat, I use libinput because in my distro there is no way to switch back to evdev. Has something to do about it? should wine convert the basic vulkan/opengl/sdl input to directx and nothing else?

**Comment by doitsujin** [comment]
DXVK doesn't have *any* impact at all on input handling.

**Comment by Lukypie** [comment]
https://bugs.winehq.org/show_bug.cgi?id=43277

Ryzen CPU issue.
