### ISSUE TITLE
F1 2015 - Fakes stream output support

### ISSUE THREAD

**Issue by ziemia** [doitsujin/dxvk#487]
After activate  "FakeStreamOutSupport" in d3d11_options.cpp game work. I spent 5 hours in the game without any problems.

{ "F1_2015.exe",   D3D11OptionSet(D3D11Option::FakeStreamOutSupport)         },

I cannot play in Linux port because my cpu doesn't support sse4. 

The only problem I had was to change the resolution in the game. I changed the resolution in the configuration file. In 1920 × 1080 resolution, with medium settings I reach average 29FPS.

### System information
- GPU: NVIDIA 960GTX
- Driver: 396.24.02
- Wine version: 3.11-staging
- DXVK version: 0.61

**Comment by jarrard** [comment]
How does it fake stream output? sets data to null or something? or is it actually doing something useful so that features such as tessellation of Geralt's hair can work in witcher3 for example? or in TombRaiderD3D11

**Comment by varris1** [comment]
No, fake stream output will just return S_OK instead of E_NOTIMPL if the option is set.
The reason why it exists is because in Overwatch, it works around the missing sounds issue.

**Comment by doitsujin** [comment]
Thanks for the heads-up, added it to the list (along with Mafia 3 which seems to require this as well).
