### ISSUE TITLE
WRC 5 - `shaderXxx` is not enabled on the device

### ISSUE THREAD

**Issue by MrChebik** [doitsujin/dxvk#491]
### Surface problems:
- Does not display texts.
- Artifacts on headlights.
- Artifacts of the stroke of the item in the menu.

### Problems with output:
At the debug file you can see, that the game does not activate shaders, such as:
- `shaderStorageImageWriteWithoutFormat`
- `shaderClipDistance`
- `shaderCullDistance`
- `sampleRateShading`

I looked through **Mesa** news / **ANV** source code, and they support the required shaders.

### Software information
**WRC 5 FIA World Rally Championship**

### System information
- GPU: Intel HD 5500
- Driver: Mesa 18.1.3
- Wine version: 3.10-staging-esync
- DXVK version: 43cbe42

### Apitrace file(s)
- With the **apitrace** the game does not load, immediately crashes.

### Log files
- [d3d11.log](https://pastebin.com/QR8Jr3k1)
- [dxgi.log](https://pastebin.com/0qY7piYS)
- [debug](https://pastebin.com/m06vaMn2) (Validation Layers / Debug)

**Comment by doitsujin** [comment]
All of these features **are** enabled on the device, the messages are invalid.

**Comment by MrChebik** [comment]
I went into the game settings and noticed the dependence on the resolution for the game engine and the Fullscreen mode.

The render of the game is very strange.
Trees / car / bushes - have a polygonal and multi-colored visualization.

## Played at 640x360 resolution
### 1920x1080 for the engine (default)
```
Engine.Device.PC.Height = 1080;
Engine.Device.PC.Width = 1920;
```
> 30 FPS

There are no special problems in the menu, except descriptive ones. In the race - everything is bad, but noticed that the closer the object to the camera - the better it is drawn, and on it appear textures / remote polygons.

### 640x360 for the engine
```
Engine.Device.PC.Height = 360;
Engine.Device.PC.Width = 640;
```
> 45 FPS

In the menu, the model of the car is black, just like with increasing speed and and increasing the distance to the camera in the resolution 1920x1080.
Also, in the menu removed icons, sprites.
In the race itself, it's still worse, the polygons has become bigger. 

### 3840x2160 for the engine
```
Engine.Device.PC.Height = 2160;
Engine.Device.PC.Width = 3840;
```
> 15 FPS

The polygons has become less. The trees became more distinct.

--
It is interesting that the FPS changes, but the number of pixels that I see is not, because I play as I said above at 640x360 resolution.

--
Tried to play not in Fullscreen mode - everything is the same.

--
I hope someone will try the game on **AMD** / **Nvidia**
