### ISSUE TITLE
Farcry 5 Steering Bugs 

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [doitsujin/dxvk#492]
So in Farcry 5 a small issue regarding car steering has come up i can't turn left or right even when remapping the controls 

### Software information
Farcry 5 Mazed out

### System information
- GPU: R9 290X
- Driver:mesa 18.1.3
- Wine version: 3.10 e-sync
- DXVK version: 0.61

**Comment by doitsujin** [comment]
Input issue -> not a DXVK bug.

**Comment by Guy1524** [comment]
This is not the place to ask that question, as it has nothing to do with DXVK.

**Comment by ReaperOfSouls1909** [comment]
Getting real tired of lazy Linux assholes whatever dude you want to be a fuck face that’s not willing to help people so be it

**Comment by doitsujin** [comment]
Not going to bother with personal insults.
