### ISSUE TITLE
DX11 games do not work with DXVK >0.6

### ISSUE THREAD

**Issue by thetargos** [doitsujin/dxvk#496]
I am a bit confused about this, the last three releases of DXVK simply do not run for me. I only have two games that make use of D3D11: Diablo III and Skyrim Special Edition. D3 will show a crash window at some point trying to start up, and Skyrim will simply create an empty window that will sit there for ever (I even left it for an hour thinking that maybe all shaders were being compiled). I have to kill the process. I have no issues with DXVK 0.54 in neither games.

### Software information
Fedora Workstation 28, up to date, kernel 4.17.5

### System information
- GPU: GTX 1080
- Driver: 396.24
- Wine version: 3.11-staging, 3.12-staging
- DXVK version: 0.6, 0.61, 0.62
In the process of getting the apitrace and logs

**Comment by ZeroFault** [comment]
Unfortunately, DXVK requires at least vulkan beta driver 396.24.02 or the new 396.24.10 beta driver. If you can't get those then you will have to stay on v0.54 until a new stable driver comes out.

**Comment by thetargos** [comment]
Makes sense. I rather install from package manager, but I will install 396.24.10 from nvidia.

**Comment by doitsujin** [comment]
See #435 and the driver support page in the Wiki....
