### ISSUE TITLE
Far Cry 5 floating terrain decoration RX 570

### ISSUE THREAD

**Issue by marekjedrzejewski** [doitsujin/dxvk#497]
I get floating terain decoration, on the same level, not snapping to the ground below it. I used hight graphics settings, cause that was on by default, but using low preset didn't change it.

Here's what it looks like:
![one](https://user-images.githubusercontent.com/6793160/42734579-b0e0b5dc-8846-11e8-9706-1173986d5827.png)
![two](https://user-images.githubusercontent.com/6793160/42734580-b2c771a6-8846-11e8-9240-79f568585261.png)

It happens on dxvk 0.61 and 0.52. Didn't check other versions besides 0.62 which crashes immediately.

### System information
- GPU: Radeon RX 570
- Driver: mesa-git
- Wine version: 3.12 Staging
- DXVK version: 0.61

### Apitrace file(s)
https://www.sendspace.com/file/m5phs3

### Log files
- d3d11.log: https://www.sendspace.com/file/b1nt1i
- dxgi.log: https://www.sendspace.com/file/6dk5eh

**Comment by doitsujin** [comment]
Tagging this as an AMD issue since I haven't heard any complaints from Nvidia users.

I think the more interesting of the two issues is that 0.62 crashes immediately anyway. Can't debug it right now though.

**Comment by marekjedrzejewski** [comment]
I tried generating apitrace (I copied the dlls with x86 and x64 directories before, and ran apitrace externally, as written in new issue template, that's why I got the small file) and couldn't get it past loading. Neither benchmark nor 'continue' worked, and everything was extremely slow. I'm now trying to do it on 720p low setting. If I don't get past the loading screen, where no such issue is present, should I still send apitrace?

**Comment by doitsujin** [comment]
Someone else managed to send me an apitrace showing the benchmark, and while the trace is somewhat broken, I cannot reproduce the issue. It *might* be a driver issue, but in that case I should see it on my RX 480 as well.

It is also possible that the game just runs a different code path on AMD hardware which for some reason does not work with DXVK, or that there is some sort of setup issue. Please make sure that `nvapi` and `nvapi64` are **disabled** in winecfg, and try to make the game think you're using an Nvidia card: `export DXVK_CUSTOM_VENDOR_ID=10de`.

**Comment by doitsujin** [comment]
Update: Please disregard the above, looks like this is indeed a regression in mesa-git.

You can try running the game with Mesa 18.1.3, it doesn't seem to happen with that version.

**Comment by marekjedrzejewski** [comment]
It works with 18.1.4, thank you :)
But when I actually jumped into game I noticed it has inconsistent mouse sensitivity, sometimes even jagged. That's probably not a DXVK related issue though

**Comment by doitsujin** [comment]
I filed a Mesa bug report: https://bugs.freedesktop.org/show_bug.cgi?id=107276

For the time being, you can apply [this](https://bugs.freedesktop.org/attachment.cgi?id=140692) workaround to RADV, it should fix the problem.
