### ISSUE TITLE
glslangValidator wrong syntax

### ISSUE THREAD

**Issue by KayTaneJupiter** [doitsujin/dxvk#499]
It appears that you're using the wrong glslangValidator syntax. DXVK does not compile.

Error:

FAILED: src/dxvk/dxvk@sta/dxvk_clear_image2d_u.h 
'/usr/bin/glslangValidator' '-V' '--vn' '@BASENAME@' '../../dxvk-legacy/src/dxvk/shaders/dxvk_clear_image2d_u.comp' '-o' 'src/dxvk/dxvk@sta/dxvk_clear_image2d_u.h'

Usage: glslangValidator [option]... [file]...

Where: each 'file' ends in .<stage>, where <stage> is one of
    .conf   to provide an optional config file that replaces the default configuration

    (see -c option below for generating a template)
    .vert   for a vertex shader
    .tesc   for a tessellation control shader
    .tese   for a tessellation evaluation shader
    .geom   for a geometry shader
    .frag   for a fragment shader
    .comp   for a compute shader

Compilation warnings and errors will be printed to stdout.

To get other information, use one of the following options:
Each option must be specified separately.
  -V          create SPIR-V binary, under Vulkan semantics; turns on -l;
              default file name is <stage>.spv (-o overrides this)
              (unless -o is specified, which overrides the default file name)
  -G          create SPIR-V binary, under OpenGL semantics; turns on -l;
              default file name is <stage>.spv (-o overrides this)
  -H          print human readable form of SPIR-V; turns on -V
  -E          print pre-processed GLSL; cannot be used with -l;
              errors will appear on stderr.
  -c          configuration dump;
              creates the default configuration file (redirect to a .conf file)
  -d          default to desktop (#version 110) when there is no shader #version
              (default is ES version 100)
  -D          input is HLSL
  -e          specify entry-point name
  -h          print this usage message
  -i          intermediate tree (glslang AST) is printed out
  -l          link all input files together to form a single module
  -m          memory leak mode
  -o  <file>  save binary into <file>, requires a binary option (e.g., -V)
  -q          dump reflection query database
  -r          relaxed semantic error-checking mode
  -s          silent mode
  -t          multi-threaded mode
  -v          print version strings
  -w          suppress warnings (except as required by #extension : warn)

**Comment by doitsujin** [comment]
Your meson version is outdated.
