### ISSUE TITLE
Providing logs of some D3D11 games (Metro LL,Tomb Raider 2013 and Bioshock Infinite)

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#5]
Hi,
just wanted to see how far some of first AAA D3D11 games (from 2013 or so) would run with your wrapper..
in the process gathered the logs and I know you doesn't asked for but anyway I'm providing here to keep reference for the future..
Please ask if you need more games logs..
I'm removing printing same entry in log multiple times, and also note I will not repeat previously log entries from a previous game in next game to keep error list smaller..

state seems not bad (I mean it doesn't need more than new 12 DxBC opcodes and below 10 new API functions to implement to most of these errors disappear)..
the logs are until game closes/hangs so maybe they need more to run..

DXVK compiled from master 12 January 2018..

Bioshock Infinite:
DXGI log:
DxgiFactory::MakeWindowAssociation: Ignoring flags
DxgiAdapter: DXGI_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
DxgiSwapChain::SetFullscreenState: Not implemented

D3D log:
D3D11Device: Unsupported query type: 3
D3D11Device: Unsupported query type: 0
DxbcCompiler: Unsupported operand type declaration: DxbcOperandType::OutputDepth
DxbcCompiler: Unhandled operand type: DxbcOperandType::OutputDepth
DxbcCompiler: Unhandled opcode class: DxbcOpcode::Swapc
DxbcCompiler: Unhandled opcode class: DxbcOpcode::DclIndexRange
DxbcCompiler: Unhandled opcode class: DxbcOpcode::Gather4
DxbcCompiler: Unhandled opcode class: DxbcOpcode::Gather4C
DxbcCompiler: Unhandled PS SV input: DxbcSystemValue::IsFrontFace
D3D11Device: No such vertex shader semantic: COLOR0
D3D11Device: No such vertex shader semantic: TEXCOORD0
D3D11Device: No such vertex shader semantic: TEXCOORD1
D3D11Device: No such vertex shader semantic: TEXCOORD2
D3D11Device: No such vertex shader semantic: TEXCOORD3
D3D11RasterizerState: Depth clamp not supported
D3D11: Invalid blend factor: 0
D3D11: Invalid blend op: 0

Tomb 2013
DXGI
DxgiDevice::SetMaximumFrameLatency: Stub
D3D
DxbcCompiler: Unhandled opcode class: DxbcOpcode::LdMs
D3D11Query: Stub
D3D11Device::CreateHullShader: Not implemented
D3D11Device::CreateDomainShader: Not implemented
DxbcCompiler: Unhandled PS SV input: DxbcSystemValue::IsFrontFace
D3D11RasterizerState: Depth clamp not supported
D3D11DeviceContext::IAGetIndexBuffer: Not implemented
D3D11DeviceContext::IAGetVertexBuffers: Not implemented

Meto LL
DXGI
DxgiOutput::FindClosestMatchingMode: Not implemented
D3D
D3D11Device::CreatePredicate: Not implemented
DxbcCompiler: Unhandled opcode class: DxbcOpcode::SampleB
DxbcCompiler: Unhandled VS SV output: DxbcSystemValue::ClipDistance
DxbcCompiler: Unhandled opcode class: DxbcOpcode::DclStream
DxbcCompiler: Unhandled opcode class: DxbcOpcode::EmitStream
DxbcCompiler: Unhandled opcode class: DxbcOpcode::CutStream
DxbcCompiler: Unsupported operand type declaration: DxbcOperandType::OutputDepthGe
DxbcCompiler: Unhandled operand type: DxbcOperandType::OutputDepthGe

**Comment by doitsujin** [comment]
Thanks, that'll give me something to work with.

Tomb Raider is one of the next games I want to focus on anyway, at least without tessellation support for now, but I have the other two as well so I will be able to test them. Especially Bioshock may be worth working on.

**Comment by oscarbg** [comment]
nice to hear you have all games to test and interested to work on it..

**Comment by doitsujin** [comment]
Closing in order to clean up, most of the features have been implemented (except predication). Tomb Raider 2013 and Bioshock Infinite are now partially supported.
