### ISSUE TITLE
Rise of Tomb Raider loads up to menu with graphical issues crashes on benchmark launch..

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#50]
seems needs:
warn:  D3D11DeviceContext::QueryInterface: Unknown interface query
warn:  DxbcCompiler: Unhandled opcode class: DxbcOpcode::CountBits
err:   D3D11DeviceContext::ClearUnorderedAccessViewUint: Not implemented
warn:  DxbcCompiler: Unhandled instruction: DxbcOpcode::AtomicCmpStore

### System information
- GPU: Vega 56
- Driver: adrenalin 18.1.1
- Wine version: no run on Windows 10
- DXVK version: up to https://github.com/doitsujin/dxvk/commit/14d5054893bb14b3448702de1114dfc46ad5e53a

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
[ROTTR_d3d11.log](https://github.com/doitsujin/dxvk/files/1689015/ROTTR_d3d11.log)
- dxgi.log: 
[ROTTR_dxgi.log](https://github.com/doitsujin/dxvk/files/1689017/ROTTR_dxgi.log)

**Comment by doitsujin** [comment]
The game sort of runs on RADV with lowest settings (although with graphical corruption due to missing API/Shader features), so I assume the crashes are a driver bug or a bug in my shader compiler.

**Comment by oscarbg** [comment]
will try on RADV VEGA soon just to confirm..

**Comment by oscarbg** [comment]
using up to https://github.com/doitsujin/dxvk/commit/26ef59dd6f3740f53dd4fdbae76144d0e0c96604 and disabling tesselation even at high settings benchmark starts and runs for a few seconds then seems triggers a TDR driver recovery on Windows..
updated logs:
seems crash could be due to:
err:   DxvkGraphicsPipeline: Input layout mismatches vertex shader input
just before:
warn:  D3D11Device::GetDeviceRemovedReason: Stub
[ROTTR_d3d11.log](https://github.com/doitsujin/dxvk/files/1696607/ROTTR_d3d11.log)
[ROTTR_dxgi.log](https://github.com/doitsujin/dxvk/files/1696608/ROTTR_dxgi.log)

**Comment by doitsujin** [comment]
> seems crash could be due to:

It's not because DXVK just doesn't draw anything when that happens. There are a few DXBC instructions missing though, and I'm currently working on fixing an issue with read-ony depth buffers that affects ROTTR.

**Comment by doitsujin** [comment]
The latest set of commits should have fixed both the crashes and a bunch of visual issues. It still doesn't render correctly in all situations but those issues are not game specific, so I'm going to close this.
![bildschirmfoto-593](https://user-images.githubusercontent.com/25567304/38499330-7836b924-3c07-11e8-853d-fc4dffe814dd.png)

**Comment by oscarbg** [comment]
thanks.. 
yes it works now on RADV at least..
