### ISSUE TITLE
Sound issues with DXVK

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [doitsujin/dxvk#502]
### System information
- GPU: AMD HD 8750M
- Driver: 18.2 (Oibaf PPA)
- Wine version: 3.12 staging
- DXVK version: 0.62
I use KDE Neon (Ubuntu 16.04)

When I open some games like Battlefield 1, the sound is distorted like Batman voice running at 3X speed.

I tried alot of tweaks from this link >>> https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting

but I didn't find any fix for the sound problem.

I had sound issues also with games like Metro 2033 Redux and Metro Last Light Redux. I could hear the voices but with noises at the background, then I am now using the native version and it doesn't have any sound issues.

**Comment by Zeioth** [comment]
DXVK is a graphic DLL, I can't see how it can be related to an audio issue...

**Comment by ahmed-elsayed2017** [comment]
I reported a bug in Winehq and that is the answer I've got >>> https://forum.winehq.org/viewtopic.php?f=8&t=30910#p117104

**Comment by shahril96** [comment]
Have you tried to increase the Pulseaudio latency rate?

`PULSE_LATENCY_MSEC=60 <wine command>`

This trick worked for me before, and it being used in Lutris installer script for this game. [https://lutris.net/games/install/7607/view](View Install Script)

**Comment by doitsujin** [comment]
Even if this is for some reason caused by DXVK, which I doubt (sounds more like a configuration issue), it's not something that can be fixed.

**Comment by birdie-github** [comment]
@ahmed-elsayed2017 

File a bug report here: https://bugs.winehq.org/enter_bug.cgi?product=Wine

**Comment by doitsujin** [comment]
In general, when running into audio issues, you might want to set `xaudio2_7` to **native** in winecfg, or run `winetricks xact` on your wine prefix. But yeah, as @birdie-github said it's probably not a DXVK bug.

**Comment by ahmed-elsayed2017** [comment]
Starting the game with "PULSE_LATENCY_MSEC=60" fixed the sound issue. Thank you all and special thanks to @shahril96

**Comment by xndbogdan** [comment]
Did the xaudio2_7 **native** setting and it fixed audio popping for me in darksiders 3.
Thanks!

**Comment by ahmed-elsayed2017** [comment]
Using FAudio wrapper will be a better option.
