### ISSUE TITLE
Corrupted graphics in Hard Reset Redux

### ISSUE THREAD

**Issue by ptrb78** [doitsujin/dxvk#503]
Messed up screen especially when it rains in the game. It seems that graphics is not rendered correctly. For example where there should be smoke there is fire. In addition it flickers. It seems that there is something wrong with shaders.

### System information
- GPU: GTX 1070
- Driver: 396.24.10
- Wine version: 3.12 staging
- DXVK version: v0.62-16-g19f74a8

### Apitrace file(s)
- Too big for me to upload - slow internet connection(especially upload speed)

### Log files
- d3d11.log: 
[hr.x64_d3d11.log](https://github.com/doitsujin/dxvk/files/2210230/hr.x64_d3d11.log)

- dxgi.log: 
[hr.x64_dxgi.log](https://github.com/doitsujin/dxvk/files/2210231/hr.x64_dxgi.log)

**Comment by doitsujin** [comment]
> Too big for me to upload

Can't help then.

**Comment by birdie-github** [comment]
@ptrb78 

Find another Internet connection then. Also, try compressing your log using ``xz -9e`` or 7z ultra with the biggest dictionary possible for your system and word size set to 273.

**Comment by ptrb78** [comment]
@doitsujin @birdie-github
I have uploaded .trace file: [https://1drv.ms/u/s!AsGasIBm9m3Ahd5-aJcLHXyHUcF0og](url).
i tried it to be as small as possible. I ran the game to the main menu and loaded savegame with rain in the game.  After that i closed it.

**Comment by ptrb78** [comment]
@doitsujin 
The funny thing is when i take a screenshot everything is ok.
btw using wine renderer everything looks ok.

**Comment by ptrb78** [comment]
@doitsujin 
I have recorded a clip with my webcam
[https://1drv.ms/u/s!AsGasIBm9m3Ahd5_FBo2eb9ybQOQMA](url)

**Comment by doitsujin** [comment]
Does this happen if you run the game in windowed mode?

Also, can you test if this issue exists with DXVK **v0.54**?

**Comment by ptrb78** [comment]
@doitsujin 
It also happens in windowed mode.
It is all ok with DXVK v0.54.

**Comment by doitsujin** [comment]
Okay, can you figure out which version introduced the issue and then bisect it to the exact commit?

**Comment by ptrb78** [comment]
This issue was intoduced in DXVK 0.61.
I dont know how to bisect the exact commit :(

**Comment by doitsujin** [comment]
[Here](https://git-scm.com/docs/git-bisect)'s a tutorial on how to use `git bisect`.

**Comment by ptrb78** [comment]
Git bisect outcome:
832b3a9dba8329f06df9fdcdd2d9f0935e704b4c is the first bad commit
commit 832b3a9dba8329f06df9fdcdd2d9f0935e704b4c
Author: Philip Rebohle <philip.rebohle@tu-dortmund.de>
Date:   Thu Jun 28 01:00:07 2018 +0200

    [hud] Render HUD directly to swap chain image
    
    Saves a fullscreen render target, render pass, and a queue submission.

:040000 040000 00d5d3cdf5b72a746f8edadd7be5971ff36ae9b0 95c4660e67ec33cece36b5a31d4340e1b1c3a246 M	src

**Comment by doitsujin** [comment]
That's interesting to say the least.
- Does it work properly if you disable the HUD?
- Does it work properly if you revert that commit?

**Comment by ptrb78** [comment]
when i disable the hud problem still exists.
I dont know how to revert that commit.

**Comment by doitsujin** [comment]
`git revert 832b3a9dba8329f06df9fdcdd2d9f0935e704b4c` will do the trick.

**Comment by doitsujin** [comment]
So just to be absolutely sure, 

with commit  `832b3a9dba8329f06df9fdcdd2d9f0935e704b4c` it's broken, and
with commit `42a676bbdb21681525c2361a955e426368fead09` it works fine?

You can select a specific commit with `git checkout 832b3a9d` and `git checkout 42a676bb` respectively.

**Comment by ptrb78** [comment]
When i reverted the commit everything works fine.

**Comment by ptrb78** [comment]
After git checkout 42a676bb: game works fine.

**Comment by ptrb78** [comment]
After git checkout 832b3a9d it is broken.

**Comment by doitsujin** [comment]
Okay, thanks. Looks like something is fundamentally broken, some people reported that #283 only happens when the HUD is *enabled*, which indicates that this issue might be related. Possibly some timing/synchronization issue somewhere.

Unfortunately I have absolutely no way to debug this since I'm unable to reproduce either issue.

**Comment by doitsujin** [comment]
**Update:** I can see an issue when downclocking my GPU so that replaying your apitrace becomes fully GPU-bound. This is a devastating bug because it can potentially affect every game, but at the same time it's incredibly hard to figure out.

**Comment by doitsujin** [comment]
Please test if this still happens with latest `master`. adcc7a457367821edde436ff9a7dd45a579f4257 fixes the bug for me.

**Comment by ptrb78** [comment]
With latest git problem fixed for me.

**Comment by doitsujin** [comment]
Great, thanks for the quick reply, and for helping with the bisect and all.
