### ISSUE TITLE
Shadow Warrior 2 - Random Crashes Since 0.63

### ISSUE THREAD

**Issue by Jrugia** [doitsujin/dxvk#507]
Running the game with 0.63 causes it to crash randomly. Reverting to 0.62 the game becomes stable again. When it crashes, Wine prints the below 2 lines in terminal (full terminal output in attached file):

0038:err:seh:call_stack_handlers invalid frame 7ffffeaaa070 (0x9c92000-0x9d90000)
0038:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.

### Software information
Shadow Warrior 2 - Max Details except: Chromatic Aberration + Motion Blur + VSync = All Off

### System information
- GPU: GTX 1060 6GB
- Driver: 396.24.10
- Wine version: 3.12 Staging
- DXVK version: 0.63

### Log files
- d3d11.log: [ShadowWarrior2_d3d11.log](https://github.com/doitsujin/dxvk/files/2216415/ShadowWarrior2_d3d11.log)

- dxgi.log: [ShadowWarrior2_dxgi.log](https://github.com/doitsujin/dxvk/files/2216416/ShadowWarrior2_dxgi.log)

### Wine Terminal Log:

- Wine Log: [wine.log](https://github.com/doitsujin/dxvk/files/2216425/wine.log)

**Comment by doitsujin** [comment]
Please bisect to the exact commit which introduced this issue. The wine log is completely useless sadly.

**Comment by doitsujin** [comment]
There seems to be a critical regression in 0.63. The best thing to do is to continue using 0.62 for the time being.

If you can build DXVK from source, please bisect which commit introduced the regression.

**Comment by Jrugia** [comment]
I'm not familiar with git and bisecting. I updated to driver 396.45 and tried 0.63 again, no crashes for over an hour. I'll be testing a bit more tomorrow and will post my findings.

**Comment by doitsujin** [comment]
I could reproduce a crash after ~10 minutes of playing the game, so the issue *is* real.

Were you using wine-esync by any chance when experiencing that crash?

**Comment by doitsujin** [comment]
Please test if e4c5880ac629267fbe0de1bbac79410f1afa5f3d fixes the issue, and if possible, **do not** change anything else on your setup that might hide the bug.

**Comment by gravndal** [comment]
Maybe related, https://github.com/doitsujin/dxvk/commit/f38ee85a396bbc2a0ad2dba8f14f5a34d61457ee and https://github.com/doitsujin/dxvk/commit/64ffcbc9efef9750f7302b295bbdd2551e6ee42b introduced a regression for Path of Exile where it will crash immediately on launch with:
```
terminate called after throwing an instance of 'std::bad_function_call'
  what():  bad_function_call
003f:fixme:seh:dwarf_get_ptr unsupported encoding 9b
003f:fixme:seh:dwarf_get_ptr unsupported encoding 90
003f:fixme:seh:dwarf_get_ptr unsupported encoding b5
003f:fixme:seh:dwarf_get_ptr unsupported encoding 9b
003f:fixme:seh:dwarf_get_ptr unsupported encoding 90
003f:fixme:seh:dwarf_get_ptr unsupported encoding b5
wine: Assertion failed at address 0x7f398bd9986b (thread 003f), starting debugger...
```
Reverting the two commits or applying https://github.com/doitsujin/dxvk/commit/e4c5880ac629267fbe0de1bbac79410f1afa5f3d fixes it.

Tested with Wine Staging 3.13 and a dxvk winelib build.

**Comment by doitsujin** [comment]
Yes, this was related, thanks for reporting.

**Comment by doitsujin** [comment]
Got a confirmation that another related issue is fixed. Feel free to reopen if the original issue persists, but I cannot reproduce it anymore either.
