### ISSUE TITLE
Suggestion: Custom HUD via a file

### ISSUE THREAD

**Issue by enesaltinkaya** [doitsujin/dxvk#509]
Contents of a certain file could be displayed on the HUD.

We could then write the values we want to see into that file at an interval using bash or smiliar. 
Utilizations, temps etc...

**Comment by doitsujin** [comment]
As I've said multiple times already, the HUD exists **for debugging purposes** only and not for system monitoring. Those kind of features shouldn't be part of DXVK but rather a separate project.
