### ISSUE TITLE
Battlefield 4 opens 2 windows saying error creating hull and domain shader..

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#51]
also interesting because tries to requests D3D11.1 context of course fails:
info:  D3D11CreateDevice: Probing D3D_FEATURE_LEVEL_11_1
err:   D3D11CreateDevice: Requested feature level not supported

### System information
- GPU: Vega 56
- Driver: Adrenalin 18.1.1
- Wine version: run native Windows 10
- DXVK version: up to https://github.com/doitsujin/dxvk/commit/14d5054893bb14b3448702de1114dfc46ad5e53a

### Log files
- d3d11.log:
[bf4_d3d11.log](https://github.com/doitsujin/dxvk/files/1689085/bf4_d3d11.log)
- dxgi.log: 
[bf4_dxgi.log](https://github.com/doitsujin/dxvk/files/1689086/bf4_dxgi.log)

**Comment by doitsujin** [comment]
`11_1` not being supported is not an issue because the game simply falls back to `11_0`. The game does seem to require Tessellation though.

**Comment by oscarbg** [comment]
Yes..
just saying in future if implementing 11_1 support it's a game to test.. at the time it was said that using 11_1 game was able to extract a few percent more performace from videocards..
in fact 11_1 exposed some new interesting features (https://msdn.microsoft.com/en-us/library/windows/desktop/hh404562(v=vs.85).aspx):
Create larger constant buffers than a shader can access
Use logical operations in a render target
Force the sample count to create a rasterizer state
Extended support for shared Texture2D resources
Change subresources with new copy options
Discard resources and resource views
Support a larger number of UAVs
Bind a subrange of a constant buffer to a shader
Retrieve the subrange of a constant buffer that is bound to a shader
Clear all or part of a resource view
Map SRVs of dynamic buffers with NO_OVERWRITE
Use UAVs at every pipeline stage
just saying it would be nice to have support eventually..
of course feel no pressure and there are other important things to implement..

**Comment by doitsujin** [comment]
Closing this to clean up, see #93.
