### ISSUE TITLE
Debian - compile errors

### ISSUE THREAD

**Issue by themainliner** [doitsujin/dxvk#515]
I'm sure I've made a simple yet fundamental error. This is my output from running
`./package-release.sh master /your/target/directory --no-package`

https://pastebin.com/8GUwsChT

**Comment by doitsujin** [comment]
Please read the [Troubleshooting](https://github.com/doitsujin/dxvk#troubleshooting) section in the readme.

Also, GCC 6.3 is a bit on the old end and I don't know if it compiles anymore.

**Comment by themainliner** [comment]
That'll teach me to think I might be able to get away installing Debian's packages version. Thank you. I'll try that (both suggestions).

**Comment by themainliner** [comment]
I may have to throw the towel in...I have been trying to build mingw-w64 all day...the fundamental problem is the instruction which call for a "mingw-w32-1.0-bin_x86_64-linux_[yyyymmdd].tar.bz2" file I cannot locate. I even download something that clearly only needed unarching (mostly into /usr) and this seem to take me back a step (or two). If I cannot delploy mingw-64 that employs an more up-to-date gcc I not sure how to proceed.

**Comment by themainliner** [comment]
I tried the Debian Backports version that features GCC 7.3...same result.

**Comment by doitsujin** [comment]
Yes, you **need** to perform the `update-alternatives` step mentioned in the readme. It is not optional.

**Comment by themainliner** [comment]
Done sir, multiple times.

**Comment by doitsujin** [comment]
It's obvious that your MinGW doesn't support pthreads for whatever reason, but how to get that to work is not something I can help you with. Might be worth asking elsewhere.
