### ISSUE TITLE
Try to get DXVK merged into main Wine

### ISSUE THREAD

**Issue by aaronfranke** [doitsujin/dxvk#518]
To put it simply, it would be a vast improvement to the Wine and DXVK experience if DXVK was merged into Wine. Currently Wine and DXVK must be installed separately, and not all users know how to do this. 

Improving the accessibility of DXVK for users should be a high priority goal for the DXVK team.

To accomplish this, we would have to convince the Wine team to accept C++ code. As far as I know, Wine currently only accepts code written in C.

**Comment by doitsujin** [comment]
This is not for me to decide.
