### ISSUE TITLE
DXVK breaks -no-cef-sandbox Win7 libcef support

### ISSUE THREAD

**Issue by Eracktor** [doitsujin/dxvk#521]
Windows XP support for Steam ends 2019. There is a hack that allows Linux wine users to use the CEF features that Steam requires. It's the old crossover steam.patch. (https://github.com/Tk-Glitch/PKGBUILDS/blob/master/wine-staging-esync-pba/steam.patch). This patch is necessary to use the new friends list, store and chat features provided by the recent steam update. However, running DXVK (setting it to native in winecfg) with this patch causes the patch to fail, and all of these features cease to work.

Winetricks reports several errors that could be related:
014f:err:module:import_dll Library dxgi.dll (which is needed by L"C:\\Program Files\\Steam\\bin\\cef\\cef.win7\\libcef.dll") not found
014f:err:module:import_dll Library d3d11.dll (which is needed by L"C:\\Program Files\\Steam\\bin\\cef\\cef.win7\\libcef.dll") not found
014f:err:module:import_dll Library libcef.dll (which is needed by L"C:\\Program Files\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe") not found
014f:err:module:attach_dlls Importing dlls for L"C:\\Program Files\\Steam\\bin\\cef\\cef.win7\\steamwebhelper.exe" failed, status c0000135

In WinXP mode, DXVK and the patch do not conflict.

### Software information
Steam

### System information
- GPU: RX 480
- Driver: mesa-git
- Wine version:  3.13 Staging Esync PBA https://github.com/Tk-Glitch/PKGBUILDS/tree/master/wine-staging-esync-pba
- DXVK version: 0.63

**Comment by doitsujin** [comment]
The error messages indicate that you might not have 32-bit DXVK DLLs set up. You need **both** the 64-bit and 32-bit ones.

Anyway, CEF is probably something that will never work with DXVK because it apparently requires resource sharing. I'd recommend sticking to builtin wined3d DLls for `Steam.exe` if you absolutely need the shop etc. to work.

**Comment by Eracktor** [comment]
Does Steam have dxgl and d3dll dlls? I've never messed with though, and I don't see them in the Steam folder. I just  place the DXVK binaries in the game folder. For example, for Fallout 4, I just put the dlls next to the game.exe, set them both to native in the winecfg, and run the game it.

Chromium Embedded Framework features required for Steam's store and friends list no longer work if those binaries are on the prefix in Windows 7 mode.

For the longest, people would use WinXP mode to get around the CEF sandbox issues steam has, but that won't be a solution when XP support gets nixed a couple of months from now.

This big report explains it in a bit more detail: https://www.winehq.org/pipermail/wine-bugs/2015-October/425430.html

**Comment by Tk-Glitch** [comment]
Steam calls the system dxgi and d3d11 dlls. If you set them to native only (and not native then built-in) that's normal for steam to not find them as you have no system wide native dxgi/d3d11 dlls available. Install DXVK system-wide (for both 32 and 64 bit on a 64 bit prefix) and your issue should be resolved.

**Comment by Eracktor** [comment]
Installing DXVK system-wide would be simply putting the DLLS in SystemWOW (DXVK 32bit) and System32 (DXVK 64 bit) Correct? Because, if I do that, CEF works, but DXVK no longer works.

**Comment by doitsujin** [comment]
> but DXVK no longer works

In that case I would recommend to start with a fresh wine prefix and **use the setup script** for DXVK as mentioned in the readme. It's quite obvious that this is another case of a messed-up setup rather than an actual bug, and I'd appreciate if people could just use it as intended instead of trying to figure out their own ways.

**Comment by Eracktor** [comment]
If it was a messed up set up, why does DXVK work and Steam's store work if the prefix on WinXP mode and Win7 -no-cef-sandbox?

**Comment by doitsujin** [comment]
Windows XP does not support DirectX 11, so it's just using something else.

And yes, your setup **is** clearly messed up, otherwise DXVK would be working just fine with the global setup. I refuse to help troubleshoot any issues caused by "creative" ways of manually installing it.

**Comment by Eracktor** [comment]
Can you at least get the steam store and friends list to work with Win7's CEF features via --no-cef-sandbox and DXVK then? Because that's the problem. I don't see why that would be so hard to troubleshoot.

**Comment by doitsujin** [comment]
Can you just fix your goddamn setup and see if it works before complaining that it doesn't?

**Comment by Eracktor** [comment]
Why are you being so hostile? Ironically, you're complaining about creativity with something like DXVK - a literal hack. Thanks for the only useful information about this though, if it even is true

**Comment by doitsujin** [comment]
I'm not hostile, I just have better things to do than waste my time on issues that aren't even my fault.
