### ISSUE TITLE
Dragon Ball Xenoverse 2 crashes

### ISSUE THREAD

**Issue by John-Gee** [doitsujin/dxvk#523]
With DXVK the game will always crashes in certain circumstances, but I'm not sure what that means.

The game will always crash when starting a new game from scratch when the prologue should play, but if it's not a fresh gameplay, it's fine, I'm able to enter the city and interact with things, in that case the game will crash once I start an event of some sort: start a training lesson, enter the colosseum, etc.

### Software information
Dragon Ball Xenoverse 2, config: https://imgur.com/delete/vMIvpBv5cOAtCc2

### System information
- GPU: AMD 280X
- Driver: radv-git e68fe445f5, llvm-svn 7 337930
- Wine version: Staging 3.13
- DXVK version: 0.63, not the first one

### Apitrace file(s)
- https://mega.nz/#!51ghXBhL!mG7Byfwn1hkMLbVjP6C07wAgvqTkZKAHW5hXCZ8j90s

### Log files
- d3d11.log: https://pastebin.com/bgP1PHNR
- dxgi.log: https://pastebin.com/BK02kiaf
- wine output: https://pastebin.com/GfSPfuhc

I have to admit that the game is not 100% stable with simply Wine, but the crashes are fairly random and not reproducible unlike those when using DXVK.

Thanks!

**Comment by doitsujin** [comment]
Please post a stack trace of when the game crashes. Something is fishy with your apitrace, replaying it requires more than 48GiB of RAM and I don't have that.

**Comment by John-Gee** [comment]
neither do I, I have 16Gb.

What do you mean by a stack trace? I get nothing more from Wine that the log I posted.

**Comment by doitsujin** [comment]
The window that wine opens when an application crashes contains a stack trace.

**Comment by John-Gee** [comment]
Right but I don't get that in this crash, it just goes back to the terminal.

As for replaying the trace, I've just done it without issue. In case it matters I used the mingw build from https://people.freedesktop.org/~jrfonseca/apitrace/ , I was getting pagefault errors with the msvc one.

**Comment by doitsujin** [comment]
Without what issue exactly? If you can successfully replay the apitrace with DXVK without getting a crash, it's useless.

**Comment by John-Gee** [comment]
Oh you meant replaying it with DXVK, I meant with standard Wine.
With DXVK, replaying works fine till it ends earlier than without DXVK.
Looking at dmesg, d3dretrace indeed got killed from an OOM issue at the time the game would crash, so maybe that's the issue.

Is there any reason why DXVK or radv would require so much memory in that scene?
I had a similar issue with Rise Of The Tomb Raider when RADV_TRACE_FILE was set, it's not set currently but in case I forgot something let's restart.

**Comment by John-Gee** [comment]
Probably a naive question, but from the trace and with your knowledge, couldn't you see what calls create this memory issue and then with guesswork find whether the issue lies in DXVK or RADV?

I'm getting fresh llvm and mesa in case it's something that creeped in last week and maybe got fixed since.

**Comment by John-Gee** [comment]
Well as expected newer Mesa/LLVM + reboot didn't change anything.

**Comment by doitsujin** [comment]
I just randomly figured out by enabling `debug` logging that RADV fails to compile a compute shader. If necessary I'll file a Mesa bug.

**Comment by doitsujin** [comment]
Should be fixed as of 21667690960c7edcd7deb105ee995e598f326504, at least I can replay your trace now.

**Comment by John-Gee** [comment]
I've tested other places where it crashed and it worked fine now.

Thank you very much for the quick fix!

**Comment by doitsujin** [comment]
Alright, thanks for the feedback.

**Comment by John-Gee** [comment]
Of course!

Is there a need to create a bug for RADV after all? If so, did you do it or should I?

Thanks!
