### ISSUE TITLE
Mouse panning sometimes hits an 'edge'

### ISSUE THREAD

**Issue by salsadoom** [doitsujin/dxvk#525]
### Software information

So I'm having an issue that seems to be effecting all the games I play in wine+dxvk. Its mostly noticable with FPS games like Warframe or Killing Floor 2 -- my mouse seems to sometimes hit an "edge" and just won't move a certain direction. It can be any direction left/right or up/down. It doesn't happen all the time, but during a game session it'll happen enough that its troublesome. When the issue shows up jiggling the mouse fixes it but it comes back.

I haven't figured out why this is the case, but it almost always seems to happen when I'm aiming precisely at something. I thought it might be linked to ADS (aim-down-sights) but I confirmed earlier this was not the case. But I never notice it when I'm just running around.

Anyone else ever get something like this? These are launched via lutris but it doesn't seem related to it.

I've tried...

    Enabling grab mouse from fullscreen in winecfg
    Disabled second monitor
    Disabled KDE's desktop effects
    Wine's Virtual desktop
    Tried it out in OpenBox to see if it was a DE thing
    Set mouse override to "forced" (definitely no)
    Unlikely, but I also tried a totally different mouse.

All my games are using esync 3.13+DXVK 0.63 on Arch, although I had this with KF2 using older versions as well IIRC. 

At least one other user on reddit reported having the same issues. He suggested it was linked to DXVK, I tested with KF2 and without using DXVK the issue does not appear. 

### System information
- GPU: MSI RX Vega 56
- Driver: Mesa 18.1.4
- Wine version: Effects multiple.. but I'm mostly using wine-esync 3.13.
- DXVK version: 0.63 (and maybe earlier?)

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log:

**Comment by triffid** [comment]
Not sure if the same issue, but this happens occasionally for me in witcher 3 - apparently wine forgets that the mouse input is in relative mode and allows screen borders to stop it moving.

When this happens in witcher, going into the menu (where mouse is returned to absolute mode) and waving it back and forth a bit then exiting the menu sorts it out for long enough that it doesn't annoy me much.

This issue has been a long-standing one with wine, having numerous regressions and new solutions to those regressions over the years.. I remember tackling it a decade ago with GTA3!

**Comment by K0bin** [comment]
Does this also happen with WineD3D? DXVK doesn't touch anything mouse related at all.

**Comment by salsadoom** [comment]
I did waaay more testing and its happening even without DXVK. It doesn't seem as noticable in KF2 but its pretty apparent in Warframe. So its not DXVK, false alarm, my initial testing was wrong.
