### ISSUE TITLE
Russian Fishing 4 - missing textures

### ISSUE THREAD

**Issue by gypsymanz** [doitsujin/dxvk#528]
Using DXVK everything seem to work well, except the rod blanks and fish are not rendering.

The game is using Unity3d engine and dx11, it was dx9 and everything work well .

Can't run apitrace as game won't run without DXVK atm.(new bug login screen won't render, was working recently)

Russian Fishing 4 - A free to play fishing simulator.
https://rf4game.com/download/

RX560AMD RADV POLARIS11 (LLVM 6.0.1):
Driver: 18.1.4
DXVK: v0.63-24-g212bd56
wine-3.13 (Staging)

[rf4_x64_d3d11.log](https://github.com/doitsujin/dxvk/files/2255786/rf4_x64_d3d11.log)
[rf4_x64_dxgi.log](https://github.com/doitsujin/dxvk/files/2255787/rf4_x64_dxgi.log)
![screenshot_20180802_094713](https://user-images.githubusercontent.com/15258575/43621786-326a4402-972d-11e8-9c1b-6ac5af379e2b.jpeg)

**Comment by doitsujin** [comment]
Like all Unity Engine games, this requires Stream Output for most animated objects to render. There's a tracking bug for that, see #135, so I'll close this one to avoid having duplicates.
