### ISSUE TITLE
[Regression] Assetto Corsa hangs when launching game

### ISSUE THREAD

**Issue by gotzl** [doitsujin/dxvk#529]
Since version 9cae049, it is not possible to start a game in Assetto Corsa (AC) any more. The AC launcher works, but when starting an actual game, it gets stuck in the loading screen (i.e. the process hangs, does not crash...).
Console output:

```
.....
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
corrupted double-linked list (not small)
```

Using the master (96176e3), the error looks slightly different:

```
.....
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
warn:  DxgiSwapChain::QueryInterface: Unknown interface query
warn:  94d99bdb-f1f8-4ab0-b236-7da0170edab1
double free or corruption (out)
```

I cannot say if its AC specific since I don't play other games that need DX11/DXVK.
In prior versions (such as 3572775), AC works perfectly, so the issue seems to be introduced in commit 9cae049.
I use the 32bit version of the game, in case it's important...

### System information
- GPU: GTX 1060
- Driver: nvidia-drivers 396.45
- Wine version: wine 3.13
- DXVK version: all versions starting from 9cae049 on

### Apitrace file(s)
The process hangs immediately, it seems to me that it doesn't even render the first frame. I guess the issue should be somewhere in the very beginning of the apitrace...
https://drive.google.com/open?id=19laMlF2OyOwhaK_DvdzedxMFRseuEv_U

### Log files (broken version 96176e3)
- d3d11.log: [acs_x86_d3d11.log](https://github.com/doitsujin/dxvk/files/2257752/acs_x86_d3d11.log)
- dxgi.log: [acs_x86_dxgi.log](https://github.com/doitsujin/dxvk/files/2257754/acs_x86_dxgi.log)

### Log files (first broken version 9cae049)
- d3d11.log: [acs_x86_d3d11.log](https://github.com/doitsujin/dxvk/files/2257755/acs_x86_d3d11.log)
- dxgi.log: [acs_x86_dxgi.log](https://github.com/doitsujin/dxvk/files/2257757/acs_x86_dxgi.log)

### Log files (working version 3572775)
- d3d11.log: [acs_x86_d3d11.log](https://github.com/doitsujin/dxvk/files/2257759/acs_x86_d3d11.log)
- dxgi.log: [acs_x86_dxgi.log](https://github.com/doitsujin/dxvk/files/2257760/acs_x86_dxgi.log)

**Comment by doitsujin** [comment]
I cannot debug this without an apitrace.

**Comment by gotzl** [comment]
Thank for the quick response!
I've to admit, I'm not completely sure what I'm doing. But it seems both the dlls from the dropbox and those in the apitrace distribution produce the following (this is with `wine apitrace.exe trace -a dxgi -v acs_x86.exe`)

```
info: did not find Z:\home\gotzl\Downloads\apitrace-msvc\x86\bin\..\wrappers\RelWithDebInfo\dxgitrace.dll
info: found Z:\home\gotzl\Downloads\apitrace-msvc\x86\bin\..\lib\wrappers\dxgitrace.dll
inject -D Z:\home\gotzl\Downloads\apitrace-msvc\x86\bin\..\lib\wrappers\dxgitrace.dll -- acs_x86.exe
apitrace: loaded into Z:\run\media\gotzl\F4DA-C96F\Steam\steamapps\common\assettocorsa\acs_x86.exe
apitrace: loaded into Z:\run\media\gotzl\F4DA-C96F\Steam\steamapps\common\assettocorsa\acs_x86.exe
Setting breakpad minidump AppID = 244210
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197961181623 [API loaded no]
apitrace: tracing to Z:\run\media\gotzl\F4DA-C96F\Steam\steamapps\common\assettocorsa\acs_x86.trace
error: unavailable function CreateDXGIFactory
```
I think that I'm not completely off in what I'm doing, maybe you have a quick idea for that last error ?
Anyways, I'll try to figure it out in order to provide the apitrace ...

**Comment by Tk-Glitch** [comment]
Here's latest master on the 64 bit version of the game :
![screenshot_20180803_193859](https://user-images.githubusercontent.com/741977/43657069-f85c6bd2-9754-11e8-9e7a-bb804d42d5c7.png)

So it may only affect the 32 bit version.

**Comment by gotzl** [comment]
I've managed to create the apitrace, I've added it to the initial issue report.
Thanks @Tk-Glitch for the info, I'll try to test it tomorrow or Sunday.

**Comment by gotzl** [comment]
I can confirm, the 64bit version of the game is working for me. It really seems to affect only the 32bit version of the game. @Tk-Glitch , are you able to reproduce my issue with 32bit?

**Comment by Tk-Glitch** [comment]
I'll have to fight with my install to get there, but I'll try to reproduce the issue.

**Comment by jp7677** [comment]
AC (x64) seems to run fine here. I haven't played hours, just quite some sessions with several minutes, but never encountered such an error. I do use AC Content Manager and not the original launcher which I never got to run.

**Comment by doitsujin** [comment]
The original bug should be fixed by now since there was a bit of an issue with adapter<>instance interaction related to the first "broken" commit.

#wontfix is for any 32 bit-specific issues, please use the 64-bit version of the game.
