### ISSUE TITLE
NVIDIA 396.51 GNU/Linux graphics driver released

### ISSUE THREAD

**Issue by Kerrung** [doitsujin/dxvk#531]
https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-396.51-Released
Hi! I'm just informing you about the release of the new version of Nvidia blob driver there is now support for the Vulkan extension of VK_EXT_vertex_attribute_divisor. Maybe it's worthwhile to raise minimum requirements for the Nvidia driver in the DXVK Wiki or am I wrong?
Thank you!
Regards.

**Comment by doitsujin** [comment]
Done, and I'll probably make it a hard requirement again soon™.
