### ISSUE TITLE
Assassins Creed Origins

### ISSUE THREAD

**Issue by setsunati** [doitsujin/dxvk#535]
Trying to get Assassins Creed Origins working with DXVK on Windows 10 since DXVK has much better CPU management and Vulkan is much better than Directx. Tried copying 64-bit dxvk dll's to game folder. The game runs on DXVK dll's but lot of graphics issues and fps problems, menu graphics doesn't load properly either. Is DXVK not yet ready for Assassins Creed Origins?

**Comment by setsunati** [comment]
Maybe if you tried running cracked version on Wine, you can get apitrace or anything useful out of the game to debug and fix issues?

**Comment by Guy1524** [comment]
You probably shouldn't discuss piracy on a public bug tracker.

**Comment by setsunati** [comment]
> You probably shouldn't discuss piracy on a public bug tracker.

Not trying to but due to DRM issues preventing debug and fix issues, unfortunately using crack might be a solution to debug and fix issues.

**Comment by setsunati** [comment]
>You probably shouldn't discuss piracy on a public bug tracker.

**Comment by setsunati** [comment]
Clicked wrong button...

**Comment by doitsujin** [comment]
I have to agree with @Guy1524 here. Feel free to open an issue if you manage to get an apitrace, which is the only way for me to actually work with the game. Right now there's not much I can do.
