### ISSUE TITLE
Tom Clancy's Ghost Recon WildLands - Hangs on loading in game 

### ISSUE THREAD

**Issue by Sebastiangperez** [doitsujin/dxvk#537]
The game starts fine, shows ads etc , press any key screen and menu , i can select the first mission , start loading and hangs. 

### Software information
Tom Clancy's Ghost Recon WildLands , Full Settings 

### System information
- GPU: Nvidia GTX 980 
- Driver:  396.45
- Wine version: wine-3.13 (Staging)
- DXVK version: 0.64

### Log files
- d3d11.log:
[GRW_d3d11.log](https://github.com/doitsujin/dxvk/files/2268398/GRW_d3d11.log)
- dxgi.log: 
[GRW_dxgi.log](https://github.com/doitsujin/dxvk/files/2268399/GRW_dxgi.log)

**Comment by ZeroFault** [comment]
```
err:   DxvkPhysicalBufferView: Failed to create buffer view:
  Offset: 0
  Range:  235929600
  Format: VK_FORMAT_R32_UINT
```
Please try driver 396.51 or the newer vulkan beta driver 396.51.02. For some reason 396.45 doesn't look like it includes a fix.

Also, if you can get an apitrace, that would be helpful.

**Comment by Sebastiangperez** [comment]
Hi @ZeroFault , i just upgrade my Nvidia Drivers to 395.51.02 , in my first boot, half of my screen turn WHITE, and i thought that the driver burn one of two monitors, later i booted again and works fine, 
The game still hanging in the same place, but now i have a new log file with a different message, i will try to upload the apitrace log asap.  
Those are  the files : 
[GRW_d3d11.log](https://github.com/doitsujin/dxvk/files/2272366/GRW_d3d11.log)
[GRW_dxgi.log](https://github.com/doitsujin/dxvk/files/2272367/GRW_dxgi.log)

**Comment by Sebastiangperez** [comment]
Apitrace doesnt work , is looking for a dll called dxgitracer.dll , any solution ?

**Comment by ZeroFault** [comment]
You need to copy the d3dll.dll, dxgi.dll, and dxgitrace.dll from this[ link](https://www.dropbox.com/sh/o769ius47wpu3pw/AAAQ7CQuBLpRbHX4HXogllxFa/x64?dl=0&subfolder_nav_tracking=1) in to the directory with the game executable. Then, run the game to start recording the trace

**Comment by Sebastiangperez** [comment]
Yep , already did that and didn't work.

**Comment by ZeroFault** [comment]
Unfortunately, I'm not sure how to fix it then.

**Comment by Sebastiangperez** [comment]
I will try after work.

**Comment by Sebastiangperez** [comment]
I got the file 
[GRW.5.trace.zip](https://github.com/doitsujin/dxvk/files/2308309/GRW.5.trace.zip)

**Comment by ZeroFault** [comment]
Unfortunately, that trace didn't record correctly as the trace file should hundreds of megabytes large.

**Comment by Sebastiangperez** [comment]
I just read thar you guys works on Valve! , awesome job man! keep doing it! 
I got it !! i hope this will help you.
[GRW.6.trace.zip](https://github.com/doitsujin/dxvk/files/2308426/GRW.6.trace.zip)

**Comment by Sebastiangperez** [comment]
Sorry , the game crashes after start when i'm using apitrace without dxvk , but works when i'm using it until loads the solo mode. 
I will try later, thanks for your support.

**Comment by Sebastiangperez** [comment]
I just try it ... nothing . keeps freezing in the same place .
Maybe when i have some time , i will reinstall the game and tested from scrach.
Thanks man anyway !

**Comment by Blisto91** [comment]
@Sebastiangperez If you are still around after all this time. Can you verify that this is no longer an issue?
With dxvk 0.64 i can see the game crashes there with my R9 380. Haven't tested on a Nvidia.
Seems to be the Godrays setting set to enhanced.

With latest version it works fine.

**Comment by Sebastiangperez** [comment]
> @Sebastiangperez If you are still around after all this time. Can you verify that this is no longer an issue? With dxvk 0.64 i can see the game crashes there with my R9 380. Haven't tested on a Nvidia. Seems to be the Godrays setting set to enhanced.
> 
> With latest version it works fine.

Uff , long time no see !! 
I do not have interest now on playing that game or test it, but thanks anyway !

**Comment by SR-dude** [comment]
The game is fine. I've tested it with nvidia closed drivers.
