### ISSUE TITLE
DXVK breaks Steam embedded browser and friend list

### ISSUE THREAD

**Issue by TheRealestMVP** [doitsujin/dxvk#539]
Since several weeks the Steam embedded browser (store, profile, community, etc) and, lately, the friend list no longer work for me. I've always run Steam with the "-no-cef-sandbox" option, and it worked fine until a few weeks ago. I assumed some Steam update broke it.

But today I noticed that both the browser and the friend list work perfectly fine when I remove DXVK from my Wine installation.

- fresh Steam installation in a new WINEPREFIX without DXVK -> browser/friends work fine
- `/path/to/dxvk/x64/setup_dxvk.sh` -> games run fine, browser/friends no longer work
- `/path/to/dxvk/x64/setup_dxvk.sh reset` -> games run poorly, browser/friends work again

Tested with Wine Staging 3.13, DXVK 0.64, NVIDIA 396.51.

Is there any way to enable DXVK just for specific games/executables only?

**Comment by doitsujin** [comment]
You have to set up the 32-bit DXVK DLLs as well, the Steam browser should work just fine with that.

But yes, you can set up DLL overrides for specific applications in winecfg, just set `d3d11` and `dxgi` to **builtin** for games/apps that don't work with DXVK. I'd still recomment setting up the 32-bit DLLs though.

**Comment by TheRealestMVP** [comment]
Oh crap, it works with the 32bit libs. Thanks!

Strange that it worked until a few weeks ago without ever installing the 32bit libs in the first place, haha.

Thank you for this great piece of software :)
