### ISSUE TITLE
New Final Fantasy XV benchmark

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#54]
benchmark released today..
of course not works closes on loading benchmark launching 1080p lite graphics from menu..

maybe very interesting as it uses a lot of Gamework tech:
GFSDK_TurfEffects.win64.dll
GFSDK_ShadowLib_DX11.win64.dll
GFSDK_VXGI_x64.dll
NvFlowLibRelease_win64.dll
NvHairWorksDx11.win64.dll
AnselSDK64.dll
altough in principle they work on AMD GPUs so not be using any NVAPI extended D3D11 APIs..
wait.. I see amd_ags_x64.dll may be they use some AMD D3D11 extended features also..

### System information
- GPU: Vega 56
- Driver: adrenalin 18.1.1
- Wine version: no, native Windows
- DXVK version: up to latest commit as date posted..

### Log files
- d3d11.log:
[ffxv_d3d11.log](https://github.com/doitsujin/dxvk/files/1689318/ffxv_d3d11.log)

- dxgi.log: 
[ffxv_dxgi.log](https://github.com/doitsujin/dxvk/files/1689320/ffxv_dxgi.log)

**Comment by doitsujin** [comment]
Please test again with e38cc4a0e0f109bc981be255f5c093c4b4689e90, which implements the last missing shader features.

**Comment by doitsujin** [comment]
Should work with latest mesa-git and llvm-svn.
