### ISSUE TITLE
Unimplemented function: D3DX11CreateShaderResourceViewFromFileW

### ISSUE THREAD

**Issue by torokati44** [doitsujin/dxvk#544]
When trying to run [Intrinsic Gravity by Still](https://www.pouet.net/prod.php?which=64756), I get this error:

    wine: Call from 0x7b44f16a to unimplemented function d3dx11_43.dll.D3DX11CreateShaderResourceViewFromFileW, aborting

See [full output](https://gist.github.com/torokati44/0d66ce2dce67ba20c3ee7d51881ef914).

### System information
- GPU: Radeon RX580
- Driver: Mesa (RADV) 18.0.5
- Wine version: wine-3.13 (Staging)
- DXVK version: v0.64
- DXUP version: git@072014ac

### Apitrace file(s)
- I don't think it's applicable in this case, but I can provide it if asked for.

### Log files
- [d3d11.log](https://gist.github.com/torokati44/79c266fdb0e0f6d34cb9c7af7f0ada80)
- [dxgi.log](https://gist.github.com/torokati44/a804b72e1031fc49704299b62de74836)

**Comment by doitsujin** [comment]
Run `winetricks d3dx11_43`. D3D**X**11 is an additional library built on top of D3D11, but not part of it.

**Comment by torokati44** [comment]
Thank you for the quick response! This indeed did it, now I get a different error that is most likely (even more) unrelated to DXVK. (It's `002e:fixme:d3dcompiler:compile_shader Compilation target "fx_5_0" not yet supported` by the way.)

Really sorry for bothering you with this invalid report.

**Comment by doitsujin** [comment]
`winetricks d3dcompiler_43` should hopefully solve this, if not, you'll have to check which version of the dll it uses.

**Comment by torokati44** [comment]
Thanks again! You were right. Now it starts up, and plays the music as expected.
The loading bar is visible, but after that, it's only a black screen. :confused:
The problem is that it cannot find mono.exe, which is not that easy to install because this demo is an x64 application. When I could manage to make it find the .exe, it did not work properly, and couldn't build assemblies, but whatever, I've lost interest for now... :)
