### ISSUE TITLE
The Elder Scrolls Online, no rendering device with dxvk 0.65

### ISSUE THREAD

**Issue by debianxfce** [doitsujin/dxvk#547]
The game works fine with dxvk 0.64. With 0.65 the game fails to start, showing a dialog with a no rendering device message,

### System information
- GPU: RX560
- Driver: Oibaf ppa Mesa
- Wine version: 3.13 staging
- DXVK version: 0.65

The game is free for 3 days.

**Comment by doitsujin** [comment]
With this amount of information I can only point you to #369.

**Comment by debianxfce** [comment]
i installed 0.65 again and did  run winecfg and now it works.
