### ISSUE TITLE
Final Fantasy XV fails to start (QueryInterface: Unknown interface query)

### ISSUE THREAD

**Issue by Nmzik** [doitsujin/dxvk#548]
First of all, i would like to thank @doitsujin for such a great job! I got Witcher 3 working nice and smooth (I hope someday we'll get StreamOutput stuff on Vulkan:)
I'm Sorry if i miss something, but i can't get Final Fantasy XV to work on dxvk (I saw on bunch of videos on Youtube from people who got it working) :(

Game fails to start with these warns:
I **DO** understand that these messages are not actually "errors", but i don't get any further logs.
```
warn:  D3D11DeviceContainer::QueryInterface: Unknown interface query
warn:  a05c8c37-d2c6-4732-b3a0-9ce0b0dc9ae6
warn:  DXGI: MakeWindowAssociation: Ignoring flags
warn:  DxgiOutput::QueryInterface: Unknown interface query
warn:  068346e8-aaec-4b84-add7-137f513f77a1
warn:  D3D11DeviceContainer::QueryInterface: Unknown interface query
warn:  6007896c-3244-4afd-bf18-a6d3beda5023
```

### Software information
Final Fantasy XV

### System information
- GPU: Radeon Rx 580
- Driver: 18.2.99
- Wine version: 3.13 staging
- DXVK version: 0.65 (same crash on 0.64)

### Log files
- d3d11.log:
[ffxv_s_d3d11.log](https://github.com/doitsujin/dxvk/files/2281227/ffxv_s_d3d11.log)

- dxgi.log: 
[ffxv_s_dxgi.log](https://github.com/doitsujin/dxvk/files/2281228/ffxv_s_dxgi.log)

**Comment by doitsujin** [comment]
The Steam version of this game does not work on wine due to DRM issues.

**Comment by Nmzik** [comment]
Thanks! Got it to work. I'll close this issue.

**Comment by mixalis1987** [comment]
@Nmzik Hi sorry so how you get it to work? I got same problem.

**Comment by doitsujin** [comment]
As mentioned before, legal versions of this game do not work on wine.
