### ISSUE TITLE
Hearthstone requires ResolveSubresource with typeless images

### ISSUE THREAD

**Issue by Raffarti** [doitsujin/dxvk#55]
Pretty much the title. I wasn't able to get hold of a trace yet. With current version it displays a black screen.

**Comment by doitsujin** [comment]
Nah, how annoying. Will be implemented one day though.

Does the game provide a way to disable MSAA entirely? If so, does it work?

**Comment by Raffarti** [comment]
It's enabled even with lowest settings.

**Comment by doitsujin** [comment]
Can you record an apitrace of the game? So far, this is the only game I'm aware of which needs this feature.

**Comment by Raffarti** [comment]
My attempts with wine failed so far, I'll try with windows but it will take some time since it will kidnap my system for a while...

**Comment by Raffarti** [comment]
### [Trace](https://drive.google.com/open?id=1XW8v2cY9Dstwp58SOEy0D6_aztp8a66X)

**Comment by Raffarti** [comment]
Working in b419b3dfbda5643aa80fa67af1387be2c30eef80
