### ISSUE TITLE
[d3d10] Stalker CP crashes

### ISSUE THREAD

**Issue by axredneck** [doitsujin/dxvk#552]
### Software information
S.T.A.L.K.E.R. Call of Pripyat with d3d10 renderer (a.k.a renderer_r3) enabled

### System information
- GPU: Nvidia GTX 1050
- Driver: 396.51
- Wine version: 3.13
- DXVK version: git, commit 4867c8b6e55c699af0934401681a8b726c50be3b
Set up using setup_dxvk32 because prefix is 32-bit and the game is 32-bit too.
Arch Linux 64-bit

### Apitrace file(s)
Game crashes when apitracing it.

### Log files
[game's own log](https://github.com/doitsujin/dxvk/files/2283741/xray_redneck.log)
[xrEngine_d3d11.log](https://github.com/doitsujin/dxvk/files/2283758/xrEngine_d3d11.log)
[xrEngine_dxgi.log](https://github.com/doitsujin/dxvk/files/2283759/xrEngine_dxgi.log)
and xrEngine_d3d10.log is empty.

The same bug when using DXUP.
The game works well with d3d11 renderer a.k.a renderer_r4.

**Comment by axredneck** [comment]
Excuse me, apitrace crashed before, not game.
But finally i apitraced it: 
[xrEngine.trace.zip](https://github.com/doitsujin/dxvk/files/2283949/xrEngine.trace.zip)

**Comment by doitsujin** [comment]
Replaying the (very small) trace doesn't crash on my end. Was the trace recorded with DXVK? If so, it needs to be done on a platform where it works, i.e. wined3d if it works, or Windows.

**Comment by axredneck** [comment]
No, i recorded it with wined3d. Sadly i have no Windows.

**Comment by doitsujin** [comment]
Please let me know if dad015bd6782d9f332137349235f0873e57aa462 fixes the issue.

**Comment by pchome** [comment]
I can confirm dx10 mode fixed with latest master.

**Comment by pchome** [comment]
@axredneck 
Here is full overrides list for both 10/11 renderer options:
`stalker-cop-dll.reg`
```regedit
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Wine\AppDefaults\xrEngine.exe\DllOverrides]
"d3d10"="native"
"d3d10_1"="native"
"d3d10core"="native"
"d3d11"="native"
"d3dcompiler_42"="native"
"d3dcompiler_43"="native"
"d3dcompiler_47"="native"
"d3dx10_42"="native"
"d3dx10_43"="native"
"d3dx11_42"="native"
"d3dx11_43"="native"
"dxgi"="native"
```
Maybe not all of them are really needed.

**Comment by axredneck** [comment]
@pchome I installed all of them with winetricks (except compilers 42 and 47, i added them manually and copied them to Stalkers "bin" directory), but the same issue.

**Comment by sputniktr02** [comment]
@axredneck I have tested the game in a 64 bit prefix and it works for me (both dx10 and dx11). Maybe you should try it in a 64 bit prefix. Install both 32 bit and 64 bit DXVK binaries.

**Comment by pchome** [comment]
@axredneck 
* 64 bit prefix (default)
* `winxp` version set for `xrEngine.exe` (to be sure)
* `dxvk.conf` with `dxgi.fakeDx10Support = True` in game's root directory (where DXVK log files created)
* missing **32 bit** DLLs in game's `bin/` directory
* `r3_use_dx10_1 on` and `renderer renderer_r3` manually set in `user.ltx` config file
* winelib build

Don't know if there is other differences can be. Check log files produced by game/WINE .

**Comment by axredneck** [comment]
p.s.
Stalker CP GOG version without mods with dxvk-git form AUR **works for me in D3D11 mode** but crashes in D3D10 one. xrEngine_d3d10.log file is empty.
I try D3D10 because one of mods i want to play (Klondyke 2.0) doesn't support D3D11. Also i want to play Stalker CS with some mods later and it doesn't have D3D11 at all.

**Comment by axredneck** [comment]
Oh, i just rebuilt dxvk-git and now it works!
