### ISSUE TITLE
What Remains of Edith Finch does not start

### ISSUE THREAD

**Issue by AlexanderWKoenig** [doitsujin/dxvk#553]
Hello,

if i try to start this game i get this error Message:
![wroed-error1](https://user-images.githubusercontent.com/40361614/44044028-a1b7508a-9f24-11e8-9def-3a04d28c50d0.png)

if i try to start it with -d3d11 parameter the following error is shown:
![wroed-error2](https://user-images.githubusercontent.com/40361614/44044029-a1d9b27e-9f24-11e8-905a-1f41d87e5526.png)

It worked in some previous dxvk/linux/nvidia Versions but not anymore. But sadly I can not tell when it got broken.

Oh and it works in wine without dxvk, so it has to be a bug on dxvk side.

Greetings, I love your work

### Software information
What Remains of Edith Finch

### System information
- GPU: Nvidia GTX 1060
- Driver: 396.51
- Wine version: 3.13 Staging
- DXVK version: 0.65

### Log files
no content in Logfiles

**Comment by AlexanderWKoenig** [comment]
Alright here is a trace with wine and without dxvk, but apitrace crashes the game after a second:

[FinchGame-Win64-Shipping.trace.zip](https://github.com/doitsujin/dxvk/files/2284123/FinchGame-Win64-Shipping.trace.zip)

**Comment by doitsujin** [comment]
If they are actually completely empty, this means that the game doesn't even reach the point where it initializes DXGI, meaning that it doesn't run any DXVK code. Please make sure that you have everything set up correctly and post the wine console output.

Replaying the apitrace does not cause a crash on my end.

**Comment by AlexanderWKoenig** [comment]
My wineprefix for dxvk64 works well with Darksouls 2 and Darksiders Remastered.
Here is the console output, when I try to launch with dxvk:

`[alex@antergos Win64]$ WINEPREFIX="/home/alex/.wine_dxvk64/" wine FinchGame-Win64-Shipping.exe 
000b:fixme:winediag:start_process Wine Staging 3.13 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
002e:err:winediag:wined3d_dll_init Setting multithreaded command stream to 0.
002e:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
002e:fixme:gameux:GameExplorerImpl_VerifyAccess (0x666640, L"Z:\\home\\alex\\.wine\\drive_c\\GOG Games\\What Remains of Edith Finch\\FinchGame\\Binaries\\Win64\\FinchGame-Win64-Shipping.exe", 0x60f104)
002e:fixme:vcruntime:__telemetry_main_invoke_trigger (0x7a60000)
002e:fixme:heap:RtlSetHeapInformation 0x7bf0000 0 0x60f0e0 4 stub
002e:fixme:vcruntime:__telemetry_main_invoke_trigger (0x7d00000)
002e:fixme:vcruntime:__telemetry_main_invoke_trigger (0x7fb0000)
002e:fixme:vcruntime:__telemetry_main_invoke_trigger (0x7fe0000)
002e:fixme:vcruntime:__telemetry_main_invoke_trigger (0x8120000)
002e:fixme:vcruntime:__telemetry_main_invoke_trigger (0x8300000)
002e:fixme:vcruntime:__telemetry_main_invoke_trigger (0x8610000)
002e:fixme:win:DisableProcessWindowsGhosting : stub
002e:fixme:msctf:ThreadMgrSource_AdviseSink (0x681b20) Unhandled Sink: {b246cb75-a93e-4652-bf8c-b3fe0cfd7e57}
002e:fixme:system:SystemParametersInfoW Unimplemented action: 59 (SPI_SETSTICKYKEYS)
002e:fixme:system:SystemParametersInfoW Unimplemented action: 53 (SPI_SETTOGGLEKEYS)
002e:fixme:system:SystemParametersInfoW Unimplemented action: 51 (SPI_SETFILTERKEYS)
^C0038:fixme:console:CONSOLE_DefaultHandler Terminating process 2d on event 0
0038:fixme:vcruntime:__telemetry_main_return_trigger (0x8610000)
0038:fixme:vcruntime:__telemetry_main_return_trigger (0x8300000)
0038:fixme:vcruntime:__telemetry_main_return_trigger (0x8120000)
0038:fixme:vcruntime:__telemetry_main_return_trigger (0x7fe0000)
0038:fixme:vcruntime:__telemetry_main_return_trigger (0x7fb0000)
0038:fixme:vcruntime:__telemetry_main_return_trigger (0x7d00000)
0038:fixme:vcruntime:__telemetry_main_return_trigger (0x7a60000)
`

And here the working game with wine:
`[alex@antergos Win64]$ wine FinchGame-Win64-Shipping.exe 
000b:fixme:winediag:start_process Wine Staging 3.13 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
002e:err:winediag:wined3d_dll_init Setting multithreaded command stream to 0.
002e:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
002e:fixme:gameux:GameExplorerImpl_VerifyAccess (0x892a60, L"C:\\GOG Games\\What Remains of Edith Finch\\FinchGame\\Binaries\\Win64\\FinchGame-Win64-Shipping.exe", 0x5ff104)
002e:fixme:heap:RtlSetHeapInformation 0x7bc0000 0 0x5ff0e0 4 stub
002e:fixme:win:DisableProcessWindowsGhosting : stub
002e:fixme:msctf:ThreadMgrSource_AdviseSink (0x8c4780) Unhandled Sink: {71c6e74e-0f28-11d8-a82a-00065b84435c}
002e:fixme:system:SystemParametersInfoW Unimplemented action: 59 (SPI_SETSTICKYKEYS)
002e:fixme:system:SystemParametersInfoW Unimplemented action: 53 (SPI_SETTOGGLEKEYS)
002e:fixme:system:SystemParametersInfoW Unimplemented action: 51 (SPI_SETFILTERKEYS)
002e:fixme:dxgi:DXGID3D10CreateDevice Ignoring flags 0x1.
002e:fixme:d3d11:d3d11_device_CheckFeatureSupport Returning fake threading support data.
002e:fixme:dxgi:dxgi_factory_MakeWindowAssociation iface 0x8c6be0, window 0x40070, flags 0x1 stub!
003b:fixme:d3d_shader:shader_sm4_read_instruction_modifier Unhandled modifier 0x800000c2.
003b:fixme:d3d_shader:shader_sm4_read_instruction_modifier Unhandled modifier 0x00155543.
003b:fixme:d3d11:d3d_blend_state_create Per-rendertarget blend not implemented.
003b:fixme:d3d_shader:shader_sm4_read_instruction_modifier Unhandled modifier 0x800000c2.
003b:fixme:d3d_shader:shader_sm4_read_instruction_modifier Unhandled modifier 0x00155543.
003b:fixme:d3d_shader:print_glsl_info_log Info log received from GLSL shader #3:
003b:fixme:d3d_shader:print_glsl_info_log     Vertex info
003b:fixme:d3d_shader:print_glsl_info_log     -----------
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[5].zw" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[6]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[7]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[8]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[9]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[10]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[11]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[12]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[13]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[14]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[15]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[16]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[17]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[18]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[19]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[20]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[21]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[22]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[23]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[24]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[25]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[26]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[27]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[28]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[29]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[30]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(22) : warning C7050: "vs_out[31]" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     0(25) : warning C7050: "R2.w" might be used before being initialized
003b:fixme:d3d_shader:print_glsl_info_log     
003b:fixme:d3d_shader:print_glsl_info_log     Fragment info
003b:fixme:d3d_shader:print_glsl_info_log     -------------
003b:fixme:d3d_shader:print_glsl_info_log     0(30) : warning C7050: "R1.w" might be used before being initialized
003b:fixme:d3d_shader:shader_sm4_read_instruction_modifier Unhandled modifier 0x800000c2.
003b:fixme:d3d_shader:shader_sm4_read_instruction_modifier Unhandled modifier 0x00155543.
003b:fixme:d3d_shader:shader_sm4_read_instruction_modifier Unhandled modifier 0x800000c2.
003b:fixme:d3d_shader:shader_sm4_read_instruction_modifier Unhandled modifier 0x00155543.
`

**Comment by axredneck** [comment]
it seems like there is something wrong with your .wine_dxvk64 prefix

**Comment by doitsujin** [comment]
Please try to run the game in a clean prefix with only DXVK and maybe stuff like xaudio2_7 overrides enabled. As I've said repeatedly, it **does not even initialize** DXVK so I find it hard to believe that this is a bug.

**Comment by AlexanderWKoenig** [comment]
Sry guys for the trouble, a clean wineprefix did the trick. Dunno how i did break my old one.
Anyway big thanks, sry for wasting your time.

Keep the good work up
