### ISSUE TITLE
Unimplemented function d3dx11_43.dll.D3DX11PreprocessShaderFromMemory

### ISSUE THREAD

**Issue by ahuillet** [doitsujin/dxvk#554]
I tried to run the demo from http://www.pouet.net/prod.php?which=77399 (download link on the page) with Wine-staging as of 2018-08-10 and dxvk 0.65.
The demo crashes soon after startup because of a call do D3DX11PreprocessShaderFromMemory that is apparently not implemented.  Is this something that needs to be added to DXVK?

### Software information
http://www.pouet.net/prod.php?which=77399

### System information
- GPU: NVIDIA 
- Driver: 396.51
- DXVK version: 0.65

**Comment by ahuillet** [comment]
[backtrace.txt](https://github.com/doitsujin/dxvk/files/2284100/backtrace.txt)

**Comment by doitsujin** [comment]
D3D**X**11 is not part of D3D11 but a separate library which is available through winetricks, see #544.

**Comment by ahuillet** [comment]
Thanks for correcting the newbie mistake. The application goes further now, although not much. I have no evidence that it is a dxvk bug.

**Comment by lubosz** [comment]
I was able to run Number One/Another One with dxvk 1.4.3 on wine-4.17 (Staging) after installing `d3dx11_43` and `d3dcompiler_43` with `winetricks`.
