### ISSUE TITLE
Steam Friends UI fails to load

### ISSUE THREAD

**Issue by notfood** [doitsujin/dxvk#556]
Steam has introduced new feature that reworks the Friends UI, it isn't loading and all the online features and game integration fail to work. A work around is to revert to the old one with the `-nofriendsui` option.

This issue happens whenever dxvi.dll and d3d11.dll are set to native. If you set it to builtin then native, it will load but dxvk won't work in that scenario.

#### Software information
Steam

#### System information
- GPU: GeForce GTX 970
- Driver: nvidia-vulkan-dkms 396.51.02-1
- Wine version: wine-staging 3.13.1-1
- DXVK version: dxvk-win64-bin 0.64-6

**Comment by doitsujin** [comment]
Works for me, please make sure to set up the 32-bit DLLs as well.

**Comment by notfood** [comment]
Both are installed. It could be that only 64-bit is affected.

**Comment by doitsujin** [comment]
Can you post wine console log or something? Right now this bug report contains pretty much no info and I don't have the slightest idea what your specific issue might be.

**Comment by notfood** [comment]
![image](https://user-images.githubusercontent.com/5370107/44065531-e446a03e-9f30-11e8-9efc-60a1833fbdc6.png)


[wine_log.txt](https://github.com/doitsujin/dxvk/files/2285124/wine_log.txt)

These lines seem relevant
```
0059:err:module:import_dll Library dxgi.dll (which is needed by L"D:\\Steam.wine64\\bin\\cef\\cef.win7\\libcef.dll") not found
0059:err:module:import_dll Library d3d11.dll (which is needed by L"D:\\Steam.wine64\\bin\\cef\\cef.win7\\libcef.dll") not found
0059:err:module:import_dll Library libcef.dll (which is needed by L"D:\\Steam.wine64\\bin\\cef\\cef.win7\\steamwebhelper.exe") not found
```

**Comment by libcg** [comment]
Did you install DXVK through the setup_dxvk32 or setup_dxvk64 scripts? If you only set them to native in winecfg, Wine won't be able to find the DLLs.

**Comment by notfood** [comment]
I ran setup_dxvk32 as well and same situation. Steam friends is unable to go online.

**Comment by notfood** [comment]
This appears to be a bug in wine without dxvk as well. It replicates with the d3dx11_43 too.

I'll go report it over there.

**Comment by doitsujin** [comment]
If it can't find the DLLs, something about your wine prefix is messed up. Please double-check if the `dxgi.dll` and `d3d11.dll` exist in `$WINEPREFIX/drive_c/windows/system32` **and** `$WINEPREFIX/drive_c/windows/syswow64`, and that they point to the correct files.
