### ISSUE TITLE
Quantum Break renders incorrectly - black rectangles

### ISSUE THREAD

**Issue by kmaterka** [doitsujin/dxvk#559]
Quantum Break renders incorrectly in some situations. Some shadows/lighting are incorrect, sometimes in the shape of black rectangles:
![1_dxvk](https://user-images.githubusercontent.com/15380931/44115053-2b382788-a00d-11e8-838c-be3f9626bd03.png)
![1_win](https://user-images.githubusercontent.com/15380931/44115054-2b564d58-a00d-11e8-9716-da720a4525a2.jpg)
![2_dxvk](https://user-images.githubusercontent.com/15380931/44115055-2b74a424-a00d-11e8-8233-f5b7c60bc3ce.png)
![2_win](https://user-images.githubusercontent.com/15380931/44115056-2b94360e-a00d-11e8-87fc-5afc81524632.jpg)

### Software information
Quantum Break: https://pcgamingwiki.com/wiki/Quantum_Break
Problem occurs on all settings: from low to ultra.

### System information
- GPU: GeForce GTX 970
- Driver: 396.51.0
- Wine version: wine-3.13 (Staging)
- DXVK version: 0.65

### Apitrace file(s)
Without DXVK game crashes when save finisehs loading (menu works). I tried:
WINEDLLOVERRIDES="d3d11,dxgi=b" wine /home/konrad/Pobrane/apitrace-msvc/x64/bin/apitrace.exe trace --api dxgi -v QuantumBreak.exe
But no trace was generated and game crashed.
With [these DLLs](https://www.dropbox.com/sh/o769ius47wpu3pw/AABYFKQFFNsCsosXhl7_HReDa?dl=0) game crashed on start, but trace file was generated (useless I guess).

### Log files
[QuantumBreak_d3d11.log](https://github.com/doitsujin/dxvk/files/2288298/QuantumBreak_d3d11.log)
[QuantumBreak_dxgi.log](https://github.com/doitsujin/dxvk/files/2288299/QuantumBreak_dxgi.log)

**Comment by doitsujin** [comment]
Can't do anything without an apitrace. Also I'm pretty sure that the game did render correctly at some point, if you can't trace it, please check if it works with older drivers and/or dxvk.

**Comment by kmaterka** [comment]
First missions are OK or graphic error are less visible. It was the first time where it is so clearly visible, but I found problems in other areas too.

I tested it on Windows on the latest drivers (398.82). With DXVK there is exactly the same issue (performance is also similar). It still can be a driver bug, Nvidia uses the same common code on all platforms.

Anyway, I was able to create apitrace on Windows:
https://www.dropbox.com/sh/ziy9sku1qn8c8kn/AACFTdVDah0SSzgYaPld2WbDa?dl=0
There are two traces:
* QuantumBreak1.trace (1,7 GB) - game crashed after few seconds, but trace should be fine.
* QuantumBreak2.trace (1,9 GB) - scene rendered for few seconds, then I quit the game

I also uploaded save from that moment, if you wish to test using it you need to put it in:
~/.wine/drive_c/users/$USER/Local Settings/Application Data/QuantumBreak

**Comment by doitsujin** [comment]
Thanks for uploading trace files. Unfortunately I cannot debug the problem because replaying the traces causes a GPU hang.

**Comment by doitsujin** [comment]
I finally managed to grab a renderdoc capture of a frame. There are small lighting artifacts, but it's not nearly as bad on my RX 480 as it is on your screenshot. The problem might be related though.

Unfortunately it also appears that the buffer that seems to contain faulty data is only updated once while loading the game/level, which makes this exceptionally hard to debug.

**Comment by kmaterka** [comment]
Is there anything I can help (except patch :))? I can send you the Steam key if it helps (no obligations).

**Comment by kmaterka** [comment]
This can be closed, issue was fixed with version 0.72. I've checked 0.71 (still rendering issues), 0.72 and all newer are fine. Thanks!
