### ISSUE TITLE
The Bard's Tale trilogy [part I] fails to run aftter being minimized

### ISSUE THREAD

**Issue by shmerl** [doitsujin/dxvk#561]
Using [GOG version](https://www.gog.com/game/the_bards_tale_trilogy).

If the game loses focus (minimized or even Alt+Tab'ed out from) and then focus is restored, it turns black and nothing happens.

Mesa / hardware:
```
GPU: Radeon RX Vega (VEGA10, DRM 3.25.0, 4.17.0-2-amd64, LLVM 7.0.0) (0x687f)
Mesa: 18.3.0-devel (git-bffa025ada)
DXVK: v0.65-45-ge5eb155
```
Wine: latest Wine master and 3.13.0 - same result.

Errors in TheBardsTaleTrilogy_d3d11.log:

```
warn:  D3D11DeviceContainer::QueryInterface: Unknown interface query
warn:  9d06dffa-d1e5-4d07-83a8-1bb123f2f841
warn:  D3D11DeviceContext::QueryInterface: Unknown interface query
warn:  420d5b32-b90c-4da4-bef0-359f6a24a83a
warn:  D3D11DeviceContainer::QueryInterface: Unknown interface query
warn:  6007896c-3244-4afd-bf18-a6d3beda5023
err:   D3D11Device: CheckFeatureSupport: Unknown feature: 14
...
err:   D3D11: Unsupported format: 89
err:   D3D11Device: CheckFeatureSupport: Unknown feature: 14
...
err:   D3D11: Unsupported format: 107
err:   D3D11Device: CheckFeatureSupport: Unknown feature: 14
err:   D3D11: Unsupported format: 4294967295
...
err:   D3D11Device: CheckFeatureSupport: Unknown feature: 10
```

**Comment by shmerl** [comment]
Well, scrape that. It launched now weirdly. Not sure why it didn't last time.

**Comment by Guy1524** [comment]
The game is querying for the D3D11_FEATURE_D3D11_OPTIONS1 and D3D11_FEATURE_D3D11_OPTIONS2  features, which refer to D3D11.2 and D3D11.3 features respectively.

DXVK doesn't even support these versions of D3D, and therefore returns E_NOTIMPL.  If you want you can try returning the appropriate structures and specifying false for all the features.

The formats it is requesting are not documented.

**Comment by shmerl** [comment]
See my update above. I managed to run it, but if I ever minimize the game, it gets trashed.

**Comment by shmerl** [comment]
Hm, setting virtual desktop to screen resolution in Wine settings works around this.

**Comment by doitsujin** [comment]
Does it work properly with wined3d?

Witcher 3 basically dies when minimizing and restoring it as well, not sure what's going on there but *that* issue has been common to wined3d and dxvk ever since I fixed a bug related to window style flags.

As usual, there's nothing I can do without an apitrace (and with this kind of problem, there's probably not much I can do *with* one, but at the very least I could see what the game is trying to do).

**Comment by shmerl** [comment]
Behavior is similar with wined3d. If I minimize the window, music stops playing, and after restoring the focus I only see a hand cursor and black screen (and music is not restored). The difference is that with wined3d in game graphics don't work to begin with beyond the starting screen with text. With dxvk they work.

I also just realized that the game is actually using Unity 2017.4.2f2, I thought it was some custom engine before. So I suppose this issue should be common to other recent Unity games.

**Comment by shmerl** [comment]
I tried to test what you said about The Witcher 3 and I see that it works fine when I set "borderless window" in graphics settings. But when I set it to fullscreen, minimize + restore also trashes the game.

**Comment by shmerl** [comment]
I can try producing some api trace a bit later.

**Comment by Blisto91** [comment]
To me this seems like a wine issue.
If i launch this game through wine either with or without dxvk and alt tab then i get the black screen when i alt tab back in.
If i do the same with proton this does not happen both with and without `PROTON_USE_WINED3D=1`

**Comment by Blisto91** [comment]
Yes this does seem like a wine issue. It works when i set wine to use a virtual desktop

**Comment by ZereoX** [comment]
@Blisto91 I tested on Windows and can confirm your suspicion about this being a Wine issue. Title flawlessly toggled focus off and back on without issue using DXVK.

**Comment by Blisto91** [comment]
Thanks for checking 👍 
Ive been coming back to this with every wine release to see if anything has changed 😁
