### ISSUE TITLE
Hud on Windows 10

### ISSUE THREAD

**Issue by dennisblokland** [doitsujin/dxvk#565]
Is it possible to show the hud when using dxvk on windows 10. i've add DXVK_HUD to the system variables but that doesnt work. any idea?

**Comment by K0bin** [comment]
You might need to reboot.

**Comment by doitsujin** [comment]
It does work if you set the environment variable correctly, but as @K0bin said you might have to reboot.

Also, Windows is not the target platform of DXVK, it can be useful for debugging purposes, but I'm not going to support setup issues on Windows.

**Comment by 4ymen** [comment]
You don't need to reboot. You can add it like this: https://superuser.com/a/989665
Or use `setx DXVK_HUD 1` before launching the game from the command line.

**Comment by dennisblokland** [comment]
i've tried all suggestions. is the creation of the log files a real indication that the game is using dxvk? but i suspect there is something wrong with my w10 install because simple commands like "ping" cant be found in non admin powershell. but thanks for the help anyway.
