### ISSUE TITLE
Installing dxvk 0.70 over 0.65, library override problem

### ISSUE THREAD

**Issue by debianxfce** [doitsujin/dxvk#570]
When installing dxvk 0.70 over 0.65, you need to manually change libraries to native in winecfg.  Libraries are listed twice, first ones are marked with * and are set to native. Second ones are set to builtin and wine is using those overrides by default.

### System information
- GPU: RX560
- Driver: Oibaf ppa Mesa git
- Wine version:  3.12 staging
- DXVK version:  0.70

**Comment by doitsujin** [comment]
Quoting from the release notes:
**When using an older version of DXVK, it may be necessary to uninstall it first using** `setup_dxvk.sh --reset`

**Comment by TheRealestMVP** [comment]
@doitsujin:
It's `setup_dxvk.sh reset`, not `setup_dxvk.sh --reset`.
It's wrong on the release notes, too.

**Comment by doitsujin** [comment]
Fixed.

**Comment by debianxfce** [comment]
"When using an older version of DXVK, it may be necessary to uninstall it first using setup_dxvk.sh reset"

I did that, it does not remove old overrides.
