### ISSUE TITLE
Ori and the Blind Forest shows warnings

### ISSUE THREAD

**Issue by kakra** [doitsujin/dxvk#576]
### Software information
Ori and the Blind Forest (Steam, Definitive Edition)
XBox One S Controller
Full Screen, Full HD, Vsync, all details

### System information
- GPU: NVIDIA GTX 1050 Ti 4 GB
- Driver: Proprietary 396.51.0
- Wine version: 3.14
- DXVK version: 0.70

### Log files
- d3d11.log: [oriDE_d3d11.log](https://github.com/doitsujin/dxvk/files/2299446/oriDE_d3d11.log)
- dxgi.log: [oriDE_dxgi.log](https://github.com/doitsujin/dxvk/files/2299447/oriDE_dxgi.log)

While the game seems to work perfectly (I completed it 80% now, no crashes, no graphical glitches), I see some errors and warnings in the log. Is anything here critical or important to be supported by dxvk?

**Comment by doitsujin** [comment]
Nothing to worry about here - just some DX11.2 warnings, but the game doesn't require it, and a *lot* of warnings about a format that doesn't actually exist. Unity Engine loves to do that for some reason.
