### ISSUE TITLE
Assasins Creed 1 black screen issue - DX10 title

### ISSUE THREAD

**Issue by Leopard1907** [doitsujin/dxvk#577]
After you pass the intro cutscene , you can't see the profile creation menu. It is just black. FPS counter etc are all there but nothing rendered to screen. You can hear the main menu sound effects also.

### Software information
Game: Assasins Creed 1 Director's Cut - GOG version
d3d_compiler 43 via winetricks

### System information
- GPU: GTX 1050 4 GB ( Nvidia Prime - Nvidia card is always active )
- Driver: 396.51
- Wine version: Wine 3.11 Staging ( updated to 3.13 but no difference )
- DXVK version: 0.70

### Apitrace file(s)
- Put a link here

### Log files

Game has three executables named : 
1-) AssassinsCreed_Game.exe
2-) AssassinsCreed_Dx9.exe
3-) AssassinsCreed_Dx10.exe

Logs:

-d3d11.log from DX10 exec:

[AssassinsCreed_Dx10_d3d11.log](https://github.com/doitsujin/dxvk/files/2299630/AssassinsCreed_Dx10_d3d11.log)

-d3d10.log from DX10 exec:
Empty file so it cannot be uploaded

- dxgi.log from DX10 exec:
[AssassinsCreed_Dx10_dxgi.log](https://github.com/doitsujin/dxvk/files/2299629/AssassinsCreed_Dx10_dxgi.log)

-d3d11.log from Game.exe:

[AssassinsCreed_Game_d3d11.log](https://github.com/doitsujin/dxvk/files/2299634/AssassinsCreed_Game_d3d11.log)

-d3d10.log from Game.exe:

[AssassinsCreed_Game_d3d10.log](https://github.com/doitsujin/dxvk/files/2299635/AssassinsCreed_Game_d3d10.log)

-dxgi.log from Game.exe:

[AssassinsCreed_Game_dxgi.log](https://github.com/doitsujin/dxvk/files/2299637/AssassinsCreed_Game_dxgi.log)

**Comment by Rotscha** [comment]
Hmm, the exact same game works for me with
- fresh 64bit wine prefix
- copying 32bit dxvk dlls to windows/syswow64
- setting dxvk dlls to native in winecfg
- winetricks d3dcompiler_43

Comparing my logs to yours, the main difference (apart of my gpu being a gtx680) is the driver version. I'm on 396.51.02, yours appear to be 396.51

**Comment by Leopard1907** [comment]
- I also have 64 bit fresh wineprefix
-I just used new DXVK script method 
-They automically set to native in winecfg 
-Installed winetricks d3dcompiler_43 , then actived it on Winecfg and set to native , builtin. Deactivating has the same result

Just updated Wine to 3.13 but nothing changed.

I'm using graphics ppa and latest version on there is 396.51.

**Comment by Rotscha** [comment]
That's odd. The game shouldn't even start with deactivated d3dcompiler_43.

**Comment by Leopard1907** [comment]
It starts and works without d3dcomplier_43. 

But i assume it works in DX9 mode this way.

**Comment by Rotscha** [comment]
Did you have to manually add d3dcompiler_43 to dll overrides? If yes, installing it might have gone wrong, as winetricks should add the overrides itself.

**Comment by Leopard1907** [comment]
Thanks , that worked. However , before closing that issue i have noticed 2 more issues.

First:

Exit menu renders like that:

![ekran goruntusu - 2018-08-18 20-32-06](https://user-images.githubusercontent.com/24878978/44301817-13bc6a80-a326-11e8-8960-0bcd7d3f8933.png)

So you can't see yes or no prompts.

Second: 

MSAA seems deactived on options menu.

**Comment by Rotscha** [comment]
Yes, it's the same for me. But everything else seems to work fine.

**Comment by Leopard1907** [comment]
So you also have the exit issue and MSAA issue.

Maybe that is an Nvidia driver related issue.

Thanks for your help , i will close that issue.
