### ISSUE TITLE
AMDVLK driver discussion

### ISSUE THREAD

**Issue by gusthe** [doitsujin/dxvk#578]
With this amdvlk update https://github.com/GPUOpen-Drivers/llpc/commit/70ec075a21e28de6cfe5585bf67ad51f57c82eda DXVK no longer immediately crashes when using the driver. Here are some results of some tests I ran.
Edit1: Tested more games. Changed Naruto Shippuden: Ultimate Ninja Storm 4 to broken.

**Games that I didn't notice any issues**:
Batman Arkham Knight
Batman Arkham City
Thief
The Vagrant
Dying Light

**Games that had issues:**
**Naruto Shippuden: Ultimate Ninja Storm 4** - ~~Freezes during the start of some story missions.~~ Fixed with AMDVLK 2.0.60

**Final Fantasy XII The Zodiac Age** - ~~MSAA issue~~ Fixed with AMDVLK 2.0.60
with MSAA
![with msaa](https://user-images.githubusercontent.com/11148529/44303020-ebbc0f80-a303-11e8-967c-f5d5f3c099bd.png)
no MSAA
![no msaa](https://user-images.githubusercontent.com/11148529/44303027-127a4600-a304-11e8-9c84-f0348cd7e799.png)

**The Witcher 3** - ~~Issues with water, and turning on the Hair effects causes my computer to freeze up needing a hard reboot.~~ Fixed with AMDVLK 2.0.60
![witcher](https://user-images.githubusercontent.com/11148529/44303031-3b9ad680-a304-11e8-8c64-5d00fdf590ec.png)

**Killer Instinct** - ~~Freezes when entering a match or the benchmark mode, needing a hard boot to resolve.~~ Fixed with AMDVLK 2.0.60

**Just Cause 3** - ~~Freezes during startup, needed a hard boot to resolve.~~ Fixed with AMDVLK 2.0.60

**Skyrim Special Edtion** - Graphical glitches
![skyrim](https://user-images.githubusercontent.com/11148529/44303820-eddc9900-a318-11e8-96fd-067fecd706ea.png)

**Comment by Mushoz** [comment]
Very cool results! Do you happen to have any comparisons performance-wise between AMDVLK and Mesa/RADV?

**Comment by gusthe** [comment]
I ran a quick test for performance with the Arkham knight bench.
AMDVLK
Min:39
Max:80
Average:59

RADV
Min:35
Max:80
Average:58

This was the second run test results for both to rule out shader caching. With AMDVLK it's caching shaders every time I run the game. So RADV really wins this easily. Does AMDVLK not have on disk shader caching?

The other games I tried seemed close to the same in performance minus the shader caching in a few.

**Comment by shmerl** [comment]
The Witcher 3 has distortions:

![tw3_amdvlk_sky_mess](https://user-images.githubusercontent.com/310927/44305639-8c352280-a34a-11e8-9b8e-4e9549bb746f.png)

**Comment by shmerl** [comment]
Performance is very similar to radv:

amdvlk:

![tw3_amdvlk_1](https://user-images.githubusercontent.com/310927/44305697-f26e7500-a34b-11e8-9321-118b96ea5e53.jpg)

radv:

![tw3_radv](https://user-images.githubusercontent.com/310927/44305698-fa2e1980-a34b-11e8-8920-5a4fed5bdcfc.jpg)

**Comment by libcg** [comment]
Pinging relevant AMD people in the discussion. @JacobHeAMD @jinjianrong @amdrexu

**Comment by jinjianrong** [comment]
Thanks very much for trying AMDVLK with the games. We will continue to fix the remaining issues.
Regarding "Does AMDVLK not have on disk shader caching?", you could enable caching to disk by adding a  runtime setting "ShaderCacheMode,2" (refer to https://github.com/GPUOpen-Drivers/AMDVLK#runtime-settings)

**Comment by zenyd** [comment]
Hello @jinjianrong I can notice severe shader compile based stuttering compared to radv on my machine. It's pretty bad on Tomb Raider 2013 for example. radv itself also stutters but is often smoother. I hope there is something which can be done about this.

**Comment by VadikLeshy** [comment]
On AMD Raven and Arch Linux amdvlk works better, than radv 18.3dev + llvm8.0svn. For example NieR Automata hangs on start with radv, but works fine with amdvlk. Many 32 bit games (Beast Battle Simulator, Bio Inc Redemption and other) crashes with radv, but woks with amdvlk. BattleTech hangs in menu with radv, but works with amdvlk. Raft runs fine for both amdvlk and radv. Grey Goo crashes on start with amdvlk.. and crashes when gameplay starts with radv.

**Comment by doitsujin** [comment]
@VadikLeshy have you filed a Mesa bug report about that? On Raven it seems to be in a rather rough shape at the moment.

**Comment by VadikLeshy** [comment]
I don't even know where this bug is. Games works with amdvlk, so this problem is not a kernel bug, but both mesa and llvm are suspected.

**Comment by yurikoles** [comment]
@VadikLeshy, please post a link to the ticket here, it will help other people to provide more info to Mesa3D.

**Comment by VadikLeshy** [comment]
Bug about 32 bit crashes:
https://bugs.freedesktop.org/show_bug.cgi?id=107914

**Comment by thirdeyefunction** [comment]
Is anyone doing nightly builds for this? I can't manage to compile AMDVLK on my system, and would like to check the progress on this.

**Comment by thirdeyefunction** [comment]
To answer my own question, the builds here worked for me (although I needed to update glibc): https://copr.fedorainfracloud.org/coprs/tkov/amdvlk/builds/

**Comment by shmerl** [comment]
Just tested The Witcher 3 with latest amdlkv release which supposedly should enable VK_EXT_transform_feedback. It hard hangs the game in the start menu (I have to do Alt+SysRq / REISUB).

**Comment by skeevy420** [comment]
As of the 2019.Q2.3 AMDVLK release I'm getting within 1.5fps of RADV on the Miami Benchmark of Hitman 2.  37.1 with RADV, 35.75 with AMDVLK.  In-game, both look and feel the same.  Using everything built from yesterday's git master branches with tk-glitch's proton-tkg and wine-tkg.

Both RADV and AMDVLK have the same odd graphical bug if you look at a light source through multiple translucent surfaces. A good test and way to trigger that bug is in the free level Hawke's Bay -- on the 2nd floor next to the bedroom, turn and look towards the light in the pool room through the balcony and the pool room glass wall.  That may deserve it's own bug report since it's reproducible with any Vulkan implementation on my RX 580.

The current/latest Ubuntu AMDVLK-Pro is unusable with Hitman 2...it renders stuff, but it's very choppy.  Since the other two work just fine, it's likely not a DXVK issue as well since The Witness (DX11) plays perfect in-game with both RADV and AMDVLK using DXVK and has the same choppy thing Hitman 2 does with AMDVLK-Pro.

On a side-note, dxvk-ags built with the 5.0 version successfully initializes according to Hitman 2's console output with both RADV and AMDVLK.  Thanks for pushing that 5.0 version.  Console output shows a setdisplaymode error, but since that's related to HDR and I don't have an HDR setup I think that means it's working just fine.

**Comment by doitsujin** [comment]
> Both RADV and AMDVLK have the same odd graphical bug if you look at a light source through multiple translucent surfaces.

Is that really a driver/dxvk bug or is that just some issue with the game?

**Comment by skeevy420** [comment]
> > Both RADV and AMDVLK have the same odd graphical bug if you look at a light source through multiple translucent surfaces.
> 
> Is that really a driver/dxvk bug or is that just some issue with the game?

I'm not sure. I don't have a Windows installation to test it. I do have access to the PS4 version so I can see if it occurs there tonight.

**Comment by clee** [comment]
AMDVLK makes Elite: Dangerous waaaay too bright. RADV renders the game pretty well, but has some odd stutters occasionally.

AMDVLK screenshots attached.
![elite-dangerous-amdvlk-01](https://user-images.githubusercontent.com/2089/60753916-be696600-9f96-11e9-9d66-c2ad0a526e40.png)
![elite-dangerous-amdvlk-02](https://user-images.githubusercontent.com/2089/60753917-c0332980-9f96-11e9-9c2d-36b6a544a0ce.png)

**Comment by doitsujin** [comment]
@clee any chance you can upload a Renderdoc capture of the game with amdvlk?

**Comment by clee** [comment]
> @clee any chance you can upload a Renderdoc capture of the game with amdvlk?

No idea how to do that. Got a tutorial link handy?

**Comment by shmerl** [comment]
Latest amdvlk with Sapphire Pulse RX 5700 XT produces [such result for TW3](https://github.com/GPUOpen-Drivers/AMDVLK/issues/123):

![tw3_amdvlk](https://user-images.githubusercontent.com/310927/67642897-f8b09780-f8e6-11e9-87f9-33a93cff6784.jpg)

**Comment by noahfredriks** [comment]
> AMDVLK makes Elite: Dangerous waaaay too bright. RADV renders the game pretty well, but has some odd stutters occasionally.
> 
> AMDVLK screenshots attached.
> ![elite-dangerous-amdvlk-01](https://user-images.githubusercontent.com/2089/60753916-be696600-9f96-11e9-9d66-c2ad0a526e40.png)
> ![elite-dangerous-amdvlk-02](https://user-images.githubusercontent.com/2089/60753917-c0332980-9f96-11e9-9c2d-36b6a544a0ce.png)

This was root caused to an AMDVLK bug, which has now been fixed. Thanks for reporting the issue @clee !

**Comment by kodkuce** [comment]
2400G 
amdvlk-32bit-2019.Q4.3_1 
Linux 5.3.15_1
mesa-19.2.7_3

![2019-12-13_19:24:08](https://user-images.githubusercontent.com/24373114/70822893-f1821200-1dde-11ea-8b8a-ea537ca81dd3.png)
Titan quest, DXVK says UNKNOW GPU even if i supply it name form vulkaninfo

**Comment by stumts** [comment]
FIFA 20 grass render issues on AMDVLK 2.0.121:

![Captura de tela de 2019-12-18 11-04-35](https://user-images.githubusercontent.com/30453661/71095937-3bc31480-218c-11ea-9917-a19b46d1fe5e.png)

It renders perfect on RADV 19.2.99:

![Captura de tela de 2019-12-18 11-08-21](https://user-images.githubusercontent.com/30453661/71096017-5bf2d380-218c-11ea-85f1-1a43d2d493c4.png)

**System information:**
- GPU: RX 580
- Driver: AMDVLK 2.0.121 
- Wine TkG 5.0-rc1
- DXVK 1.5

**Apitrace file:** [https://drive.google.com/open?id=1Ry2PFvlNgmN3jhQRYNDT7OiWFWz5j1LN](url)

**Log files:**
- [FIFA20_dxgi.log](https://github.com/doitsujin/dxvk/files/3979096/FIFA20_dxgi.log)
- [FIFA20_d3d11.log](https://github.com/doitsujin/dxvk/files/3979098/FIFA20_d3d11.log)

**Comment by Berobad** [comment]
> Titan quest, DXVK says UNKNOW GPU even if i supply it name form vulkaninfo
The GPU Name is provided by libdrm, if it's missing amdvlk will always output UNKOWN GPU.

And for the 15DD device id of the 2400G (itself rev C6) only a few embedded revisions are in libdrm  
https://gitlab.freedesktop.org/mesa/drm/blob/master/data/amdgpu.ids
