### ISSUE TITLE
Battlerite

### ISSUE THREAD

**Issue by Raffarti** [doitsujin/dxvk#58]
### Software information
Battlerite, lowest settings

### System information
- GPU: RX480
- Driver: RADV
- Wine version: 2.20 staging
- DXVK version: current

### Issues:
- Crashes in loading screen
- d3dretrace crashes even worse (but works with wine staging)
- A few commits ago it was able to get to the menu, but it was crashing upon viewing 3d characters in it or during game loading. Note that d3dretrace was already crashing at startup. Also note that 3d characters' models are invisible in wine staging/3.0

**Comment by doitsujin** [comment]
From the logs I can already tell that this requires stream output, which isn't supported by Vulkan and will thus require a *lot* of dirty work. Won't be supported any time soon.

**Comment by doitsujin** [comment]
Closing since Stream Output is being discussed in #135
