### ISSUE TITLE
Batman Arkham Knight, game crash in detective mode

### ISSUE THREAD

**Issue by jp7677** [doitsujin/dxvk#580]
Batman Arkham Knight runs perfectly well with DXVK, no graphically issues and performance is really well. Thanks a lot for the hard work.
Unfortunately the game crashes on my machine when entering detective mode i.c.w. certain objects. This was also mentioned here https://github.com/doitsujin/dxvk/issues/335. The game usually crashes with a message box from the game itself.
![screenshot from 2018-08-20 22-02-40](https://user-images.githubusercontent.com/17219293/44363620-f5d93c00-a4c4-11e8-83ef-85465a7543ad.png)
I have also seen unhandled page faults in wine with the same scene. Running in fullscreen mode shows identical behavior, though I guess the message box is just behind the window. That makes it appear  like a system freeze.

### Software information
Batman Arkham Knight
Everything enabled or high, Max FPS: 60, Texture Filtering: 2x Anisotrpic.
Nvidia Gameworks features disabled

### System information
- GPU: Nvidia GTX 1080
- Driver: 396.51
- Wine version: 3.13 (Staging) from official Fedora repositories
- DXVK version: v0.70

### Apitrace file(s)
Obtained on Windows 10 with the procedure described here https://github.com/doitsujin/dxvk/wiki/Common-issues#apitrace:
- See https://github.com/doitsujin/dxvk/issues/580#issuecomment-417849484

### Log files
- d3d11.log: [BatmanAK_d3d11.log](https://github.com/doitsujin/dxvk/files/2303784/BatmanAK_d3d11.log)
- dxgi.log: [BatmanAK_dxgi.log](https://github.com/doitsujin/dxvk/files/2303785/BatmanAK_dxgi.log)
- Console output with Vulkan validation layers enabled: [vulkan-validation-output.log](https://github.com/doitsujin/dxvk/files/2307833/vulkan-validation-output.log)

### Save Game
- https://www.dropbox.com/s/cu80w2052vftvi2/SaveData.zip?dl=0
Though not sure if this works.

Don't know if this is relevant, but apitrace logging looks like
```
apitrace: loaded into C:\Program Files (x86)\Steam\steamapps\common\Batman Arkham Knight\Binaries\Win64\BatmanAK.exe
apitrace: warning: D3D11CreateDevice: unexpected IDXGIAdapter pointer 0000000007F67180
apitrace: tracing to C:\Program Files (x86)\Steam\steamapps\common\Batman Arkham Knight\Binaries\Win64\BatmanAK.trace
ERROR: Could Not Get Primary Adapter Handle
apitrace: warning: IDXGIDevice2::QueryInterface: unsupported IID uuid(3e1ff30b-c951-48c3-b010-0fb49f3dca71)
apitrace: warning: pVtbl = 00007FE73E10B880 (C:\windows\system32\dxgi.dll!+0x2b880)
apitrace: warning: WrapID3D11Device2::CreateRenderTargetView: unexpected ID3D11Resource pointer 00007FE6ABA41650
apitrace: flushing trace
apitrace: warning: WrapID3D11Device2::CreateUnorderedAccessView: unexpected ID3D11Resource pointer 00007FE6ABA41650
apitrace: warning: WrapID3D11DeviceContext1::CopySubresourceRegion: unexpected ID3D11Resource pointer 00007F26D94715B0
```
The last message get repeated over and over again. It took me quite some time to obtain the trace since the game with apitrace attached crashes 9 of 10 times with above message box and `apitrace: warning: caught exception 0xc0000005` before I could enter the actual game scene. Is this normal?

**Comment by Eignar17** [comment]
@jp7677 update driver nvidia to 396.51.02
https://developer.nvidia.com/vulkan-driver

**Comment by Leopard1907** [comment]
You should try with 396.51.

https://github.com/doitsujin/dxvk/wiki/Driver-support

**Comment by jp7677** [comment]
@Leopard1907 Version 396.51 was fortunately just released today for Fedora from negativo17 repositories. I gave it a retry, though it made no difference. The game still crashes at the same scene, sometimes with a message box from the game itself, sometimes with an unhandled page fault in wine. I updated the logs accordingly.

@Eignar17 Is your suggestion just a general recommendation or are you certain that this specific issue is no longer present in Nvidia's Vulkan development branch?

**Comment by Eignar17** [comment]
@jp7677 bug DXVK

**Comment by jp7677** [comment]
I have added the console output with Vulkan validation layers enabled, eventually this is of any use.

**Comment by doitsujin** [comment]
The image barrier error is interesting, I hope I'll be able to reproduce that.

**Comment by jp7677** [comment]
I should add that I recorded the apitrace and the validation output in
different sessions in window mode with a resolution of 1024x768. Please let
me know if I can assist any further, e.g. recording in fullscreen.

**Comment by Leopard1907** [comment]
@jp7677 Well , at least we ruled out that is not related to being on a previous driver :D

**Comment by Eignar17** [comment]
@jp7677 view and test game in wined3d and create api trace

**Comment by doitsujin** [comment]
I tried to replay the apitrace, but it has some issues baked which may be a result of it being recorded on wine. Replay fails even with wined3d for the same reasons.

**Comment by K0bin** [comment]
I could create an apitrace on Windows but I need a save because I haven't managed to reproduce the crash on my own.

**Comment by K0bin** [comment]
When I said, I wanted a save, I meant one that makes it easy to reproduce the crash, preferably standing in front of an object that makes it crash.

I've already flown around the city in detective mode for 15 minutes with my own save and it just doesn't crash for me, so a save that's just outside of a mission in the open world, won't help much.

@doitsujin 
I could still record a trace but would that help at all, if the game runs completely perfect for me?

**Comment by jp7677** [comment]
@K0bin Where you able to load my save game? You should stand in the correct room already if it loads correctly. Just press x and turn slightly forward and to the left...

**Comment by doitsujin** [comment]
@K0bin hm, it's probably not going to be useful, but right now I'll happily take any trace that i can replay, and maybe check what it's doing.

**Comment by K0bin** [comment]
@jp7677 I think your safe was actually sort of a backup because the game appears to store its saves inside the game directory /BmGame/SaveGames.

**Comment by K0bin** [comment]
I can't get it to load. I have no idea why but I've replaced both the saves in documents as well as the ones in BmGame and turned Steam into offline mode but it still only shows my save.

**Comment by jp7677** [comment]
Here is the Cache and Config folder from BmGame, eventually this helps
https://www.dropbox.com/s/wt12o1ed6729dff/Cache_Config.zip?dl=0

**Comment by pchome** [comment]
This game never crashed in detective mode for me.

Instead I have had similar problem when tried to optimize game parameters by hand. By edit `Poll` an so on in games config file directly. 

Finally I ended by using minimal settings offering by the game itself and lower resolution.
See https://steamcommunity.com/sharedfiles/filedetails/?id=484128370

**Comment by jp7677** [comment]
I have remove my download files here cause they weren't any good. I'll give apitrace another try today evening (Western Europe), hopefully I can come up with something better. I guess the trace is only good if I'm able to replay it locally, thus not just seeing the api calls but able to press play and see something happen?

**Comment by jp7677** [comment]
Hi @doitsujin 
The best I can provide is https://www.dropbox.com/s/0nnugwm3szq7u2l/BatmanAK.trace?dl=0

This is a trace with dxvk until right into the crash. The replay starts fine on my machine and enters the game, though either apitrace replay crashes (with wine dx11) or the replay halts and makes my complete desktop nearly unresponsive. It's not much, but eventually you can read at least something from it.
I tried lots off times to record a trace with wined3d, but most of the time the game crashes before I'm able to enter the game. The few times I somehow got a in-game trace I'm ending up with crash right in the beginning when trying to replay :(.
I hope that somebody is able to record a trace on Windows. Unfortunately I have a Linux installation only.

**Comment by jp7677** [comment]
Hi @doitsujin ,
I'm sort of back in business. I have found a spare disk and installed Win10, Steam etc there. I'm able to record traces of that scene. Though whenever I try to replay, d3dretrace stalls right after 10 frames or stops with a dxgi_error_device_removed error. When trying to replay in Linux with dxvk d3dretrace stalls too, with wine3d it crashes. Would a trace like this of any use to you?

**Comment by doitsujin** [comment]
It's quite clear that your driver crashed. Please upload the trace anyway.

**Comment by jp7677** [comment]
I managed to get a somewhat usable apitrace when using the "-nologo" launch argument (at least I think so ;)). Replaying in Windows 10 leaves the screen black, but does not crash the driver any longer. Replaying in Linux with DXVK seems to work actually, I see in-game rendering. The replay seems to stall at the same point where the real game would crash. Fingers crossed that you can get something out of it!

Apitrace:
https://www.dropbox.com/s/km3drlv4lrkah2m/BatmanAK.trace?dl=0
`wine apitrace replay` with DXVK console output:
[apitrace-replay.stdout.log](https://github.com/doitsujin/dxvk/files/2342288/apitrace-replay.stdout.log)

I had turn all graphics related options to off or low for recording to keep the size manageable, Before that I confirmed on Linux/DXVK that the crash still occurs with all options off or low.

**Comment by jp7677** [comment]
Oh man, I feel stupid. Faking a non-Nvidia GPU by using 
```
dxgi.customDeviceId = E366
dxgi.customVendorId = 1002
```
fixes makes this crash to away. Well, at least I learned quite a lot about apitrace ;)

**Comment by doitsujin** [comment]
No need to feel stupid, this *is* unexpected behaviour. I'll see what I can do.

**Comment by tuxtergames** [comment]
Anybody here can play through steam play with proton, here I just can play with lutris dxvk.

**Comment by jp7677** [comment]
@tuxtergames See https://github.com/ValveSoftware/Proton/issues/558
