### ISSUE TITLE
Render issue with The Witcher 3 Wild Hunt

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [doitsujin/dxvk#582]
### Software information
Name of the game: The Witcher 3 Wild Hunt
Settings used: All settings are on medium.

### System information
- GPU: AMD HD 8750M
- Driver: 18.1.5
- Vulkan: 1.1.70
- Wine version: esync-3.13
- DXVK version: 0.70

### Apitrace file(s)
- The game crashes everytime I use it.

### Log files

[witcher3_d3d11.log](https://github.com/doitsujin/dxvk/files/2303138/witcher3_d3d11.log)
[witcher3_dxgi.log](https://github.com/doitsujin/dxvk/files/2303139/witcher3_dxgi.log)

### A picture to explain my issue:

You can see the health bar above Siren but Siren itself doesn't appear on the screen.

I had the same problem with another monster appears in the sea but I thought it might be an invisible creature or something, so I didn't care at this moment!

![screenshot_20180820_180332](https://user-images.githubusercontent.com/29783425/44354168-5a869d80-a4a9-11e8-92a1-b41387521089.png)

**Comment by K0bin** [comment]
Sirens are one of the enemies in Witcher 3 that rely on Stream Output which DXVK currently can't implement. 

See #138
and #135

**Comment by ahmed-elsayed2017** [comment]
@K0bin Thanks for the clarification.

**Comment by Kerrung** [comment]
>Sirens are one of the enemies in Witcher 3 that rely on Stream Output which DXVK currently can't implement.

@K0bin by the way, why DXVK currently can not implement Stream Output.
What is the reason for this? What prevents it from doing?
Thank you! Regards.

**Comment by K0bin** [comment]
>What is the reason for this? What prevents it from doing?

Vulkan simply doesn't have that functionality at the moment.

@ahmed-elsayed2017 Please close the issue as we're already aware of it and it's kept track of in the two issues I linkes above.
