### ISSUE TITLE
LiF MMO launcher shader issues. black window

### ISSUE THREAD

**Issue by jayquonmarton** [doitsujin/dxvk#584]
The launcher for LiF MMO (supposed to be a directx 11 game, but not sure about the launcher.exe) simply shows a black screen. The dxvk HUD does show up on it though, if enabled.

I tried all DXVK_CONFIG_FILE settings, but none helped.

The console output has various shader 5 errors, such as the following. Does DXVK support shader 5?

```
Warning: D3D shader compilation failed with skip optimization flags. (vs_5_0)
C:\fakepath:15:18: error: syntax error, unexpected NEW_IDENTIFIER
```

Full console output: https://bpaste.net/show/c94eac7d30ce
Wine console output: https://bpaste.net/show/1aedc78f2a2d

Screenshot of the launcher (with dxvk HUD active):

![lol2](https://user-images.githubusercontent.com/42581387/44416069-cf4bed00-a526-11e8-80a6-14ff3d848292.png)

### Software information
the launcher for the game Life is Feudal - MMO

You can download the small installer for the launcher via the download button at top of https://play.lifeisfeudal.com/ (I think that requires making an account first?)
Direct link to the launcher installer (doesn't require registration): https://cdn.xsolla.net/life-is-feudal/launcher/life-is-feudal-mmo-installer.exe

### System information
- GPU: nvidia gtx 1070
- Driver: 396.45.0
- Wine version: 3.13-staging
- DXVK version: 0.70

### Apitrace file(s)
- https://transfer.sh/OuU6c/launcher.trace

### Log files
- d3d11.log: https://bpaste.net/show/f170744c1150
- dxgi.log: https://bpaste.net/show/e39b5c2575e1

**Comment by doitsujin** [comment]
The log message you posted indicates that **HLSL** shader compilation failed. That's not my bug though since DXVK doesn't compile raw HLSL, but takes the compiled byte code.

I'll look at the trace next week.

**Comment by jayquonmarton** [comment]
thanks for explaining the issue. I'll close it.
