### ISSUE TITLE
Wildstar black rendering

### ISSUE THREAD

**Issue by mentos1386** [doitsujin/dxvk#586]
Graphics are rendered wrong. But the preformance is great :smile:
![dxvk-wine](https://user-images.githubusercontent.com/1910649/44432022-a23c2080-a5a0-11e8-8867-dddcb1732a8c.png)

After seeing this, i also noticed that it's broken similarly but not quite the same with pure wine.
![pure-wine](https://user-images.githubusercontent.com/1910649/44432115-f7783200-a5a0-11e8-8b1d-b4b13f4aad77.png)

### Software information
Tried running game Wildstar. It works without any special settings, only thing that has to be done is to set wine to `Windows XP`.

### System information
- GPU: GeForce GTX 860M
- Driver: 396.51
- Wine version: 3.13 (also tried 3.14 staging)
- DXVK version: 0.70

### Apitrace file(s)
- Put a link here
[WildStar32.trace.txt](https://github.com/doitsujin/dxvk/files/2308229/WildStar32.trace.txt)

### Log files
- d3d11.log:
[WildStar32_d3d11.log](https://github.com/doitsujin/dxvk/files/2308226/WildStar32_d3d11.log)
- dxgi.log:
[WildStar32_dxgi.log](https://github.com/doitsujin/dxvk/files/2308227/WildStar32_dxgi.log)

**Comment by K0bin** [comment]
How did you record that trace? DXVK, WineD3D or Windows?

Because replaying it works fine for me:
![image](https://user-images.githubusercontent.com/1131720/44532017-6a44f280-a6f2-11e8-831c-59761318aea0.png)

**Comment by mentos1386** [comment]
@K0bin i followed the instructions in issue template. Created using wine without dxvk.

You have a bit newer drivers (398.91 vs 396.51) and newer vulkan (1.1.82 vs 1.1.70), could that be the reason it works for you? There aren't 398.91 drivers for Manjaro yet so i can't test with you drivers.

**Comment by K0bin** [comment]
I'm on Windows and NVIDIA uses different version numbers there for sone reason. 398.91 should equate to 396.54.

Can you try it again using 396.54? You can install that using the .run file on NVIDIAs website

**Comment by Mixaill** [comment]
It could be Maxwell gen1 specific problem

Got incorrect rendering with Windows 10, 860M and 398.82
![2018-08-25 14](https://user-images.githubusercontent.com/704382/44620966-8db09e80-a8a6-11e8-868b-1a4d7db557f2.png)

**Comment by doitsujin** [comment]
@K0bin can you please attach your log as well? I think this is an issue with DXVK picking the wrong surface format for presentation again, similar to the one that was already causing issues on AMD. Maxwell 1 only supports two formats.

**Comment by K0bin** [comment]
Sure, unfortunately it doesn't contain anything particularly useful.

[d3d11](https://pastebin.com/gFaWHH3q)
[dxgi](https://pastebin.com/n9iN8zE8)

**Comment by doitsujin** [comment]
Hm, so it picks the same swap image format on your end. Not sure what's going on then, but the visual error *does* very much look like missing linear<>srgb conversion somewhere.

**Comment by MartinPL** [comment]
This game is now dead, can be close.

**Comment by mentos1386** [comment]
@MartinPL there is progress being done on creating a server emulator for it [1]. So it isn't totally dead.

[1] https://github.com/NexusForever/NexusForever
