### ISSUE TITLE
Flickering issues in Batman: Arkham City

### ISSUE THREAD

**Issue by jekstrand** [doitsujin/dxvk#589]
Occasionally characters and other objects will flicker a bit.  This is noticeable in the intro menu where Batman will flicker in and out.  It's also noticeable with one of the characters in the freeze-ray scene of the benchmark.

### Software information
Batman: Arkham City
High settings with tessellation enabled.

### System information
- GPU: Intel Sky Lake
- Driver: mesa master
- Wine version: wine-3.13 (Staging)
- DXVK version: master

### Apitrace file(s)
I'd love to but I've never been able to get the game to trace correctly (and boy have I tried!)

**Comment by Eignar17** [comment]
@jekstrand  video card?

**Comment by jekstrand** [comment]
@Eignar17 Intel Sky Lake is my video card. :smile: Any Intel gen9 I've tried has these issues.  Maybe other gens; haven't tried.

**Comment by saboya** [comment]
Haswell doesn't support the necessary Vulkan version / features.

**Comment by K0bin** [comment]
[Here's the trace](https://mega.nz/#!0fICUT6A!f_PPRfqTzwFH-GzGEUbo0xzMW9tZGIfFCpYQP_98790) I recorded for #347. I'm not 100% sure I had tessellation enabled but I think so.

**Comment by doitsujin** [comment]
I tried replaying the trace file, but it hangs my GPU.

**Comment by K0bin** [comment]
No flickering at all for me on Nvidia.

**Comment by jekstrand** [comment]
I've observed the hang and I suspect it's a missing pipeline barrier somewhere.

@doitsujin If you're having hanging issues with Batman, you may need one or more of the patches in my batman branch: https://gitlab.freedesktop.org/jekstrand/mesa/commits/wip/anv-dxvk-batman

**Comment by doitsujin** [comment]
One of my problems is that I don't have any Intel hardware to test with, and RADV hangs during the replay.

**Comment by werman** [comment]
@jekstrand The flickering is fixed :tada: in Mesa master somewhere between 4daa3917a38 (2020-04-22)  and 896a7c28eb4 (2020-03-31)   
I investigated it a year ago and also found nothing at that time.

**Comment by werman** [comment]
```
Bisect ended on:
 191ced539a18e4738e7e6bce7612779dced1625a is the first bad commit
commit 191ced539a18e4738e7e6bce7612779dced1625a
Author: Juan A. Suarez Romero <jasuarez@igalia.com>
Date:   Tue Mar 31 10:59:20 2020 +0000

    anv/pipeline: allow more than 16 FS inputs
    
    A fragment shader can have more than 16 inputs, so SBE emission should
    deal with all of them.
    
    This fixes dEQP-VK.pipeline.max_varyings.*
    
    Cc: mesa-stable@lists.freedesktop.org
    Signed-off-by: Juan A. Suarez Romero <jasuarez@igalia.com>
    Reviewed-by: Jason Ekstrand <jason@jlekstrand.net>
    Reviewed-by: Ivan Briano <ivan.briano@intel.com>
    Tested-by: Marge Bot <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/2010>
    Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/2010>
```

read "bad" as "good" commit. Already in stable. So I have nothing to add.
