### ISSUE TITLE
Feature request: shader-cache pre-compiling.

### ISSUE THREAD

**Issue by andy-d1969** [doitsujin/dxvk#590]
Now that DXVK is integrated into Steam, Valve could provide complete shader-caches for the supported games. So pre-compiling would bring smooth gameplay from the first time you run a game.

**Comment by MartinPL** [comment]
https://github.com/ValveSoftware/Proton feels like better place for this request

**Comment by shmerl** [comment]
I don't think dxvk can benefit from it, since it needs to translate DXBC anyway and something in that process is dynamic and non cacheable. Actual SPIR-V shaders should be cached by the driver already.

**Comment by doitsujin** [comment]
DXVK could benefit **massively** from it, but as far as I'm aware, this would be supported by some Steam<>Driver interaction, DXVK would have to do pretty much nothing in order to support it.

**Comment by shmerl** [comment]
What exactly will be cached in such case?

**Comment by doitsujin** [comment]
I'm not entirely sure but I think they distribute shader caches for your GPU+Driver version. Of course, *someone* would still have to suffer through the stuttering anyway to generate those.

**Comment by shmerl** [comment]
You mean they cache final machine code for each architecture? Isn't it what radv cache is doing? They probably distribute cache for d3d pipeline so it could skip generating machine code from dxbc. How will dxvk benefit from it? I guess I'm missing something here.

**Comment by andy-d1969** [comment]
I thought about this way:

1. DXVK becomes an option to dump each vulkan pipeline before it gets compiled by the driver.
2. Someone at Valve is performing a speed-run through the whole game (maybe via cheats) while dumping the pipelines.
3. The so generated cache will be distributed and compiled by the driver before the game is started.

This would fill the drivers cache and the game would run smooth on the first run with every card/driver combo.

**Comment by sandman7920** [comment]
Isn't that already implemented in Steam

![image](https://user-images.githubusercontent.com/3589417/44515154-77e68200-a6ca-11e8-8903-c1400682f6c1.png)

**Comment by MartinPL** [comment]
This is for regular Steam games, not wine / dxvk

**Comment by sandman7920** [comment]
Is there a difference between `DXVK Vulkan shader` and `native Vulkan shader`

**Comment by SveSop** [comment]
@sandman7920 The steam games that you would run using DXVK would be running DirectX 10/11 and not OpenGL or Vulkan :)

**Comment by Leopard1907** [comment]
@SveSop

Though that shouldn't be a problem , if that was the case shader caching locally with DXVK wouldn't work at all in the first place. 

They are still stored in a way that Vulkan drivers can cache and use it , only locally.

Correct me if i'm wrong because i'm not a techy graphics guy :D

**Comment by K0bin** [comment]
There is practically no difference between native Vulkan games and games running on top of DXVK for the underlying OS and driver. I don't know how Valve's implementation works but there should be no technical reason preventing this from being used for DXVK. Valve would just have to implement it.

**Comment by Leopard1907** [comment]
@SveSop

Point is , every game for Linux is basically using OGL and VLK , even if they run through Proton. Since with Steam Play , every game on Steam now has also OGL and VK renderers , in a way...

Because DX is not supported on Linux natively , there is no way to caching DX related shaders natively. Also there is no way for a gpu running on Linux drivers to understand DX shaders. It has be happen through Wine , DXVK or some other solution. So shaders must be cached as a Vulkan shader then DXVK or other implementations shouldn't matter.

I think Valve's Shader Cache is suitable for this. 

Correct me if i'm wrong :)

**Comment by SveSop** [comment]
@Leopard1907 @K0bin 
I must be thick as a log today :(

Is the point that you want Steam to run all DirectX shaders through DXVK for us "Wine gamers" so that we could have cached shaders usable when we game with wine + DXVK? And.. possibly have a option for "Download cached vulkan shaders for DXVK" in the windows steam client?

**Comment by SveSop** [comment]
To kinda answer my own question: "Steam Play" is not a "magical conversion kit thingy", but those games that have both Linux/Windows/Mac clients, you buy once and have access to all versions.

This means that if you buy a windows only version game, that have no Linux or Mac client, it has no OpenGL/Vulkan shaders if it is a DirectX game... And thus we need to use wine+dxvk.
If the game already have a native Linux client.. Well.. :) 

I might be missing the point completely here ofc, so i guess ill start commenting on this :)

**Comment by Leopard1907** [comment]
@SveSop

Not Windows Steam Client , Linux Steam client runs with Proton now.

https://steamcommunity.com/games/221410/announcements/detail/1696055855739350561

Proton includes Wine , DXVK , Esync etc.

**Comment by SveSop** [comment]
@Leopard1907 
Yeah, i'm sorry. This was completely new to me. I just wish the thread starter had posted some links, and i had spent some time reading/googling that.. cos NOW i get it :)

Sorry guys.. 

Well.. that was certainly interesting news indeed :)

**Comment by Zeioth** [comment]
> This is for regular Steam games, not wine / dxvk

That's wrong. It works with proton games, in fact that feature is meant for proton games.

You can find the shader cache directory in any most games using DXVK.
![pro](https://user-images.githubusercontent.com/3357792/44762796-91635000-ab48-11e8-9346-d6f0029c8f76.png)

**Comment by shmerl** [comment]
Can anyone clarify the confusion please? What exactly is missing for dxvk while drivers already have their own cache (stored on disk after first compilation)? Just that warm up step, or something else?

**Comment by Leopard1907** [comment]
@Shmerl

Confusion was , some people were not aware of new SteamPlay and because of that they thought how DXVK shaders can be in Steam's internal cache sharing system.

So after all , probably Steam is doing that also like it does with other OGL and Vulkan games on store.Which could greatly help for stutterings.

For Linux users , every game on Steam is pratically either on OGL or VLK now.

**Comment by Leopard1907** [comment]
And for the record , my brother plays nearly non stop Fallout NV on Steam now and shader cache grows.

Also a Steam Shader Cache folder is in the FNV folder.

**Comment by Plagman** [comment]
Shader Pre-Caching is supported for any Vulkan application and DXVK is no different, everything should work as expected there.

**Comment by Leopard1907** [comment]
@Plagman

Thanks for clarifying this.

Same also applies to games work on Wine's OGL renderer.

**Comment by doitsujin** [comment]
Closing because this is pretty much already working.
