### ISSUE TITLE
Furi characters invisible

### ISSUE THREAD

**Issue by JibbityJobbity** [doitsujin/dxvk#593]
Title explains my issue. The character I play as, the boss and one or two of the attacks are invisible. Everything else renders fine though. This is an example of the issue, it's using 396.51 drivers in the screenshot but it still results in the same issue with 396.54.
![20180824131237_1](https://user-images.githubusercontent.com/37820565/44559634-7b980880-a79f-11e8-8966-4ebb63b5bb73.jpg)

This is an example of the characters rendering and running with wined3d11.
![20180824130201_1](https://user-images.githubusercontent.com/37820565/44559487-856d3c00-a79e-11e8-8136-6e96c6271743.jpg)

### Software information
Furi on Beautiful graphics option @ 1080p 60Hz

### System information
- GPU: Nvidia GeForce GTX 980 Ti
- Driver: Proprietary 396.54
- Wine version: 3.14-staging
- DXVK version: 0.70 then Commit 48697346c06011938ba04576cca45a5ae58d3227 (22 August)

### Apitrace file(s)
[Apitrace](https://pastebin.com/5KTgBzQT)

### Log files
- [d3d11.log](https://pastebin.com/0gAG96mk)
- [dxgi.log](https://pastebin.com/Ty163pHU)

**Comment by K0bin** [comment]
> D3D11Device::CreateBuffer: D3D11_BIND_STREAM_OUTPUT not supported

See #135

**Comment by JibbityJobbity** [comment]
Closing because duplicate of above.
