### ISSUE TITLE
Fallout 4 rendering issues

### ISSUE THREAD

**Issue by Nmzik** [doitsujin/dxvk#594]
### Software information
Fallout 4, Ultra Settings

### System information
- GPU: RX 580
- Driver: 18.5.1
- Wine version: No.
- DXVK version: 0.70

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
```
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
warn:  D3D11Device: No matching border color found for (-3.40282e+038,0,0,0)
```
- dxgi.log: 
```
info:  Game: Fallout4.exe
info:  DXVK: v0.70
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Radeon RX 580 Series:
info:    Driver: 2.0.20
info:    Vulkan: 1.1.70
info:    Memory Heap[0]: 
info:      Size: 7936 MiB
info:      Flags: 0x3
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 7890 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 256 MiB
info:      Flags: 0x3
info:      Memory Type[2]: Property Flags = 0x7
warn:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
warn:  DXGI: MakeWindowAssociation: Ignoring flags
info:  DxgiVkPresenter: Recreating swap chain: 
  Format:       VK_FORMAT_R8G8B8A8_UNORM
  Present mode: VK_PRESENT_MODE_FIFO_KHR
  Buffer size:  1440x900
```
The game was running on Windows 10 with dxvk dlls.
There is not much information in dxvk log, but the game itself has some problems. First of all, it has some kind of "exploding vertices". The same happens with dxvk 0.53 too (No regressions) 
GIF: 
![test](https://user-images.githubusercontent.com/691945/44578701-f9a6e000-a79c-11e8-8216-9b6450db699b.gif)
It also has another bug 
![test1](https://user-images.githubusercontent.com/691945/44579094-f6602400-a79d-11e8-9226-5e40bf314251.gif)
And third bug is when you enter **ANY open world location** the game just crashes. It happens every time.

**Comment by doitsujin** [comment]
The AMD Windows driver is **not supported** due to known issues, and because it's not the target platform.

Feel free to reopen if this happens on RADV as well (but if that's the case, please post an apitrace), and if this works correctly on RADV but not AMDVLK on Linux, please drop a comment in #578.
