### ISSUE TITLE
Neverwinter Online crashes randomly

### ISSUE THREAD

**Issue by aedalzotto** [doitsujin/dxvk#595]
The game runs fine with excellent performance. Smoother and with less FPS drops than Windows. Using wine with OpenGL runs fine but with DXVK random crashes occur. The crashes can happen from 15 seconds in game to several minutes, there is no pattern besides occuring more commonly when changing maps. I have tested the game both on my desktop and on my laptop, both have NVIDIA gpus and both have the same issue.

### Software information
Neverwinter Online. Downloaded from Arc via Windows installation and from steam via Lutris.
Tried with minimal configuration, no vsync.
Tried with game recommended defaults.
Tried both 32-bit and 64-bit clients.

### System information
Setup 1:
- CPU: i5-4210U
- GPU: Nvidia 830M
- RAM: 10GB
- Driver: 396.54 (tried 396.51 too)
- Wine version: 3.14
- DXVK version: 0.72, 0.72, 0.70, 0.63, 0.62

Setup 2:
- CPU: i5-4670K
- GPU: Nvidia 660Ti
- RAM: 16GB
- Driver: 396.54 (tried 396.51 and 390.77)
- Wine version: 3.14 and wine-tgk-git (https://github.com/Tk-Glitch/PKGBUILDS/tree/master/wine-tkg-git)
- DXVK version: 0.72, 0.71, 0.70, 0.63, 0.62, 0.52

### Apitrace file(s)
What I did: Entered the game, stayed a time in a map than changed to another. When the map loaded the game crashed (with DXVK). This is the situation the game crashes more commonly.
The tracing was made with entering the game and changing the map 2 times.
 - [Neverwinter.zip](https://github.com/doitsujin/dxvk/files/2320321/Neverwinter.zip)

### Log files
- d3d11.log (Launcher): [Neverwinter_d3d11.log](https://github.com/doitsujin/dxvk/files/2319985/Neverwinter_d3d11.log)
- dxgi.log (Launcher): [Neverwinter_dxgi.log](https://github.com/doitsujin/dxvk/files/2319987/Neverwinter_dxgi.log)
- d3d11.log (Game): 
[GameClient_d3d11.log](https://github.com/doitsujin/dxvk/files/2387171/GameClient_d3d11.log)
- dxgi.log (Game): 
[GameClient_dxgi.log](https://github.com/doitsujin/dxvk/files/2387172/GameClient_dxgi.log)
- WINEDEBUG=+vulkan [NW.txt](https://drive.google.com/file/d/1uJ3K5qhtcwu8DDEOiGvIYGutl1qboRwy/view?usp=sharing)

**Comment by K0bin** [comment]
Is the game a 32 bit executable?

**Comment by aedalzotto** [comment]
Totally forgot:
The setup 1 was tested with 32-bit executable
The setup 2 was tested with both 32-bit and 64-bit with wine64.
The result was always the same.

**Comment by doitsujin** [comment]
If the game crashes *randomly*, it's impossible to debug this.

**Comment by aedalzotto** [comment]
Is there any other log I can get to at least have a clue about what is crashing?

**Comment by aedalzotto** [comment]
The game log shows useless info:

GSM_Quit(). Reason: emEditorMain or utilitiesLibShouldQuit()

**Comment by K0bin** [comment]
Is that all?

**Comment by aedalzotto** [comment]
I will provide later an apitrace of the logging in, character change and map change, wich are the parts of the game that crashes the most.

**Comment by aedalzotto** [comment]
Added apitrace of a common situation of crash.

**Comment by Zeioth** [comment]
I play this game using DXVK 0.70 and I don't have this issue. If you install it from Lutris it should run just fine.

**Comment by aedalzotto** [comment]
Do you play on Nvidia, AMD or Intel? From steam or standalone client?

**Comment by Zeioth** [comment]
I installed it using the [Lutris installer](https://lutris.net/games/neverwinter/), so yes, it runs on Steam. 

GPU: Nvidia 1050 TI with drivers 396.54-5
CPU: Ryzen 1700
OS: Antergos

**Comment by aedalzotto** [comment]
Maybe I am facing specific wine version + dxvk problem. Can you inform your wine version? The lutris install script says DXVK 0.63 Wine-staging 3.12. Can you confirm?

**Comment by Zeioth** [comment]
Yes, but I've tried DXVK 0.70 and Wine 3.14 and it works fine too, DX11 with ultra settings, 70 FPS.

**Comment by Zeioth** [comment]
If your operative system is arch, try to run this three command, in case you are lacking some important wine dependency:

    sudo pacman -S giflib lib32-giflib libpng lib32-libpng libldap lib32-libldap gnutls lib32-gnutls mpg123 lib32-mpg123 openal lib32-openal v4l-utils lib32-v4l-utils libpulse lib32-libpulse alsa-plugins lib32-alsa-plugins alsa-lib lib32-alsa-lib libjpeg-turbo lib32-libjpeg-turbo libxcomposite lib32-libxcomposite libxinerama lib32-libxinerama ncurses lib32-ncurses opencl-icd-loader lib32-opencl-icd-loader libxslt lib32-libxslt libva lib32-libva gtk3 lib32-gtk3 gst-plugins-base-libs lib32-gst-plugins-base-libs vulkan-icd-loader lib32-vulkan-icd-loader cups samba dosbox

**Comment by aedalzotto** [comment]
Tried with Lutris: crashed anyway. The only differences I see I'm using:
OS: Arch Linux
CPU: i5-4670k

**Comment by aedalzotto** [comment]
The only package I didn't had was lib32-gst-plugins-base-libs. Installed and the crash remains. I'm using Cinnamon DE (if that matters). But what I still want to say: the game only crashes with DXVK, when using the default wined3d the game does not crash.

**Comment by Zeioth** [comment]
I doubt the problem is your wine version, but you can try to download [this](https://github.com/Tk-Glitch/PKGBUILDS) repo, go to the directory "wine-tkg-git" and run "makepkg -sri" to install it on your system. It's basically wine-staging 3.14+esync+pba+a lot of optional patches.

**Comment by hathlife** [comment]
Zeioth <notifications@github.com> 于 2018年8月25日周六 13:13写道：

**Comment by aedalzotto** [comment]
What I did now:
Installed from the repo mentioned above the spirv-tools (that provides lib32-spirv-tools not present in AUR).
Compiled wine from the provided repo. It included some packaged I didn't had: libspiro-1:0.5.20150702-2  libunicodenames-1.2.2-1  libxkbui-1.0.2-6  fontforge-20170731-2  schedtool-1.3.0-4, and the compiled VKD3D.
Configured lutris to use the system wine and it crashed again.

It seems to me that both GPUs I have tested are incompatible with some dxvk function besides having the latest drivers.

**Comment by Zeioth** [comment]
This issue can be closed.

**Comment by byaka** [comment]
@Zeioth just interesting, issue solved? i'm also have 660ti so want to know if it have some specific incompatibility with dxvk

**Comment by aedalzotto** [comment]
I am also interested. If you look at Steam Play Compatibility list made by community, Neverwinter runs fine but only GPUs listed are from 10xx series. https://docs.google.com/spreadsheets/d/1DcZZQ4HL_Ol969UbXJmFG8TzOHNnHoj8Q1f8DIFe8-8/edit?pli=1#gid=1003113831

**Comment by aedalzotto** [comment]
I am doing some tests. I have noticed that when running with DXVK the game uses almost 2GiB of VRAM constantly in ANY map. Since both my setups have 2GiB of VRAM, the usage is always at ~96%.
When running the game with wined3d, the highest VRAM usage was 1444MiB (70%), and in smaller maps the usage falls to 1024MiB.
I think the crash is occurring because I'm running out of VRAM/overflowing VRAM. Maybe the other users have GPUs with 4GiB+ of VRAM. @Zeioth can confirm?

**Comment by aedalzotto** [comment]
I am closing this issue. The problem is with video memory running out.
A possible workaround was setting the VideoMemorySize key inside wine regedit to 1512MB. This has limited the video memory for wine and the maximum total achieved being used by the game plus the rest of the system was 1855MB.
This seems a problem with Wine or Linux system using the Wine allocated memory. Limiting the Wine VRAM to 1512MB made the game run perfectly with always all memory being used, but when the rest of the system needs more than the 536MB left the game crashes.

**Comment by aedalzotto** [comment]
Seems like the VideoMemorySize didn't change anything.
With the last updates the game still crashes on my 660Ti setup, but not with the 830M.

I have tried changing virtual desktop, desktop integration in wine, as well as others desktop environment, such as Cinnamon, Gnome, Deepin and XFCE.

**Comment by doitsujin** [comment]
In that case I'd just recommend sticking to wined3d for this game.

**Comment by byaka** [comment]
@pchome think you can create link to 64bit exe, usually it works.

**Comment by pchome** [comment]
@byaka 
I already tried to to this, but
* client have separate x86/x64 folders for exe and dlls
* launcher checking checksums and reloading everything was changed
* launcher passing long command line options string to client, contains specific options
* game works fine with x86 client, so no real reason to change this

**Comment by aedalzotto** [comment]
Well, I'm adding a WINEDEBUG=+vulkan of a crash.
If anyone that understands better than I could take a look I would be very grateful.

**Comment by aedalzotto** [comment]
Hello. Seems that the d3d11 and dxgi logs I've uploaded to the issue are from the LAUNCHER ONLY, and not from the game itself.
In the game dxgi and d3d11 logs there is clearly an error "err:   DxvkMemoryAllocator: Memory allocation failed"
I am uploading here again:
[GameClient_dxgi.log](https://github.com/doitsujin/dxvk/files/2387169/GameClient_dxgi.log)
[GameClient_d3d11.log](https://github.com/doitsujin/dxvk/files/2387170/GameClient_d3d11.log)

**Comment by byaka** [comment]
@aedalzotto its x32/x64 exe and x86/x64 prefix?

**Comment by aedalzotto** [comment]
It is a x64 prefix.
I'm running the game with 'wine64'.
The launcher is 32-bit, but the game executable is x64 (using process monitor show 'GameClient.exe' inside game's x64 folder).

'''
file GameClient.exe
GameClient.exe: PE32+ executable (GUI) x86-64, for MS Windows
'''

**Comment by byaka** [comment]
hmm, interesting. looks like we need @doitsujin here

**Comment by doitsujin** [comment]
> In the game dxgi and d3d11 logs there is clearly an error "err: DxvkMemoryAllocator: Memory allocation failed"

Happens when you run out of (virtual) memory. There's nothing I can do about such an error.

**Comment by pchome** [comment]
@aedalzotto 
Don't expect 2GB VRAM should be enough for fullscreen 2560x1080 in every game, try to lower resolution e.g. 1920x1080 virtual desktop.
Since game contains PhysX*.dll files it's expected to use nvapi, so disable `nvapi` and `nvapi64` in `winecfg` for client. And, to be completely sure, set 
```
dxgi.customDeviceId = E366
dxgi.customVendorId = 1002
``` 
in dxvk.conf (in client's directory).

Also you can setup all dll overrides (dxvk,nvapi,...) for client executable only (in winecfg), but not for launcher. 

That's what I'm done.

**Comment by pchome** [comment]
If you have [conky](https://github.com/brndnmtthws/conky) built with nvidia support, use [gpu.conf.txt](https://github.com/doitsujin/dxvk/files/2388822/gpu.conf.txt) example, to see what going on with your gpu during game run.
`conky -c gpu.conf.txt`

**Comment by aedalzotto** [comment]
@pchome 
I already had the nvapi and nvapi64 disabled in winecfg.
Changing the device and vendor Id caused the memory allocated by the game stay constant and below 2GB (before that the values were 2.5GB ~ 4GB). I don't use conky, i'm using DXVK_HUD=memory,fps.
But it didn't stop the crashes. I'll upgrade my main memory from 8GB to 16GB and do further testing, as it seems that the upgrade from 8GB to 10GB of RAM made my laptop stop crashing, but taking in cosideration that it's resolution is 1366x768.
Thanks.

**Comment by aedalzotto** [comment]
Hello again.
I could test with 16GB of RAM now...
The d3d11.log doesn't show anymore the allocator error, but the game still crashes and the dxgi.log shows "err:   DxvkSwapchain: Failed to recreate swap chain"
I'm uploading the log if anyone can take a look: 
[GameClient_dxgi.log](https://github.com/doitsujin/dxvk/files/2394646/GameClient_dxgi.log)

**Comment by aedalzotto** [comment]
@byaka Yes, I'm currently using the latest release (v0.72)
