### ISSUE TITLE
Starpoint Gemini 2 - "Ultra" preset results in garbage rendering, then black screen

### ISSUE THREAD

**Issue by varris1** [doitsujin/dxvk#597]
I already posted the issue on the VKx discord server, but it's still better to post it here as well for completion's sake, especially after the whole Proton business & your vacation.

https://cdn.discordapp.com/attachments/413881848763252740/478544488030142486/stpg.png

### Software information
Starpoint Gemini 2 with ultra preset. Everything below seems to work fine

### System information
- GPU: NVIDIA GeForce GTX 970
- Driver: 396.54
- Wine version: 3.14 staging (TkG's PKGBUILD)
- DXVK version: 73cbf5b

### Apitrace file(s)
 https://mega.nz/#!u64UQSAQ!GO4iEcgH3aIvK3NtSlZiOCqqlCvySKjphtxy72ITIx4 

### Log files
[StarpointGemini2_d3d11.log](https://github.com/doitsujin/dxvk/files/2320528/StarpointGemini2_d3d11.log)
[StarpointGemini2_dxgi.log](https://github.com/doitsujin/dxvk/files/2320529/StarpointGemini2_dxgi.log)

**Comment by doitsujin** [comment]
Same issue as #1216 .
