### ISSUE TITLE
Ashes of the Singularity missing required extensions

### ISSUE THREAD

**Issue by 7oxicshadow** [doitsujin/dxvk#603]
When trying to launch Ashes of the Signularity (Escalation) in DX11 mode it fails with the following:

info:  Game: AshesEscalation_DX11.exe
info:  DXVK: v0.70
warn:  OpenVR: Failed to locate module
info:  Required Vulkan extension VK_KHR_get_physical_device_properties2 not supported
info:  Required Vulkan extension VK_KHR_surface not supported
info:  Required Vulkan extension VK_KHR_win32_surface not supported
err:   DxvkInstance: Failed to create instance

Not really a bug report, more just to make you are of what extensions some games require.

**Comment by varris1** [comment]
This looks more of a setup issue on your end. DXVK **requires** those extensions for every game as you can see here: `  struct DxvkInstanceExtensions {
    DxvkExt khrGetPhysicalDeviceProperties2 = { VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME, DxvkExtMode::Required };
    DxvkExt khrSurface                      = { VK_KHR_SURFACE_EXTENSION_NAME,                          DxvkExtMode::Required };
    DxvkExt khrWin32Surface                 = { VK_KHR_WIN32_SURFACE_EXTENSION_NAME,                    DxvkExtMode::Required };
  };   
`

**Comment by 7oxicshadow** [comment]
Not sure what that would be. I use DXVK with Quake Champions on the same prefix with no issues (apart from the known ones)? I also use the same prefix for Crysis and it also works fine. I know that DXVK is working because the diagnostics is in the top right hand corner of the screen.

**Comment by doitsujin** [comment]
This **is** a setup issue of some sort, and the extensions used/required by DXVK are the same for any game. Please make sure to have both 32-bit and 64-bit Vulkan loaders and drivers set up correctly.

**Comment by 7oxicshadow** [comment]
I am adding an additional comment to this in-case someone searches for it in the future. This issue appears to be caused because Ashes ships with vulkan-1.dll in the same directory as the executable.

Renaming this allows the game to progress as expected. Sadly it doesn't work as it hangs during the loading screen but this appears to be a wine issue and not a DXVK issue.

**Comment by doitsujin** [comment]
Oh, the game supports Vulkan?

Have you tried setting `vulkan-1.dll` to `Builtin` in winecfg? Should hopefully resolve that issue.
