### ISSUE TITLE
Alan Wake doesn't launch

### ISSUE THREAD

**Issue by LeJimster** [doitsujin/dxvk#605]
I get this error message if I try to launch the game:
![alanwake-dxvk-error](https://user-images.githubusercontent.com/35663469/44631149-29521580-a960-11e8-86a5-ff54dfd387fb.jpg)

### Software information
Alan Wake

### System information
- GPU: AMD RX Vega 56
- Driver: mesa 18.3.0-devel
- Wine version: wine-staging-nine 3.13.1-1
- DXVK version: 0.70

### Apitrace file(s)
https://drive.google.com/open?id=1ET6N1c4Cn6L9lXjbOY9mUhfJauTY6Q4G

### Log files
- d3d11.log: file contains nothing
- dxgi.log: file contains nothing

**Comment by doitsujin** [comment]
If the file contains nothing, the game does not use DXVK.

**Comment by LeJimster** [comment]
Seems like I was reading rumour articles.  Finally found one that confirmed it was dx9 (there had been rumours of dx10/dx11 for the PC port at the time)

Closing this then.

**Comment by K0bin** [comment]
Steams system requirements list DirectX 10 as a requirement and PCGamingwiki also lists Direct3D 10.
