### ISSUE TITLE
Overwatch hitching (FPS dips)

### ISSUE THREAD

**Issue by zaggynl** [doitsujin/dxvk#609]
**Issue**
Can start/play Overwatch but there is regular hitching, FPS dips.

**Setup:**
Ubuntu 18.04.1 + unstable padoka PPA + kernel 4.18.5-041805-generic through uuke kernel tool.
Installed Overwatch using the script here: https://lutris.net/games/overwatch/

Changed configuration for Overwatch in Lutris to use latest DXVK, enabled DXVK and used latest wine-esync version.
Changed the CPU governor to performance to improve performance, did the following in my installation of Ubuntu:
sudo apt-get install cpufrequtils
echo 'GOVERNOR="performance"' | sudo tee /etc/default/cpufrequtils
sudo systemctl disable ondemand 

Let me know if I should provide any logs files and how to generate these if required.

**Comment by doitsujin** [comment]
That's shader compilation stutter. Known issue, can't be fixed.

**Comment by zaggynl** [comment]
Thanks for the prompt response!
So that means the hitching might disappear after all of the shaders have been compiled?

**Comment by doitsujin** [comment]
It should. Unfortunatly, Overwatch has a **lot** of different shaders (over 25k) so you'll likely have issues with every new map you play.

**Comment by AetherUnbound** [comment]
At what point does the shader cache get cleared? As in, will there be a point where it'll have to re-cache everything?

**Comment by Taherm789** [comment]
^ I am interested to know the same

**Comment by doitsujin** [comment]
After driver updates, and when your shader cache size hits the driver-specific size limit.

**Comment by AetherUnbound** [comment]
Gotcha. FWIW I just switched from non DXVK to DVXK 0.63 and that seems to have triggered a cache-flush (which makes sense). Thanks @doitsujin!

**Comment by 132ikl** [comment]
Just wanted to let you all know that this shouldn't be a problem on NVIDIA by setting the [newly added](https://devtalk.nvidia.com/default/topic/1032059/linux/opengl-shader-disk-cache-max-size-garbage-collection-/post/5281950/#5281950) __GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1

**Comment by sirus20x6** [comment]
i have hitching well after when shader caches should be built. i usually only have troubles the first part of a map after an update, but now the hitches never stop even at the end of the game
