### ISSUE TITLE
Remove memory limit for Life is Feudal MMO

### ISSUE THREAD

**Issue by jayquonmarton** [doitsujin/dxvk#614]
They patched the game today to fix the 64-bit issue described in https://github.com/doitsujin/dxvk/issues/591 for which dxvk added the workaround in commit https://github.com/doitsujin/dxvk/commit/73cbf5b3524ffbba63c950608619a35ef872d8ad. This commit can now be reverted.

**Comment by doitsujin** [comment]
Thanks for letting me know.

Since it was mentioned that the studio releases multiple games with the same exe name, are any of them 64-bit as well, do they use D3D11, and if so, have they been updated? If that's not the case it might be a good idea to keep it around for now.

**Comment by jayquonmarton** [comment]
Turns out their other game is named `yo_cm_client.exe`, not `cm_client.exe` as I mistakenly remembered.
