### ISSUE TITLE
Support HDR games now that we have NV Vulkan drv with HDR support..

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#615]
Hi,
today NV released a dev driver which seems to expose VK HDR support (sadly Windows only):
August 31st, 2018 - Windows 399.17, Linux 396.54.02
    New Extensions:
        VK_EXT_swapchain_colorspace (Windows only)
        VK_EXT_hdr_metadata (Windows only)
Altough DXVK is meant for Linux, as DXVK can be used also on Windows, no pressure but perhaps it's good good to start implemeting it?
sadly first HDR games were using NVAPI extensions (in that case HDR NVAPI extensions should be added to Wine-Staging which has "some" NVAPI support)..
anyway by now we have some AAA games using DXGI HDR if not mistaken like Mass Effect Andromeda or Battlefield 1, right?

**Comment by doitsujin** [comment]
What's the point if this isn't supported on Windows? Also, I can't test this *at all*.

**Comment by oscarbg** [comment]
I think Windows support only limitation maybe temporal.. this extensions are also on Shield TV (Android)..
HDR and WCG APIs
no expert on HDR but:
https://docs.microsoft.com/en-us/windows/desktop/direct3ddxgi/dxgi-1-6-improvements
https://docs.microsoft.com/en-us/windows/desktop/direct3ddxgi/high-dynamic-range-and-wide-color-gamut
```
In order to enable HDR and WCG in your app, refer to the following APIs.

    IDXGISwapChain4::SetHDRMetaData : sets High Dynamic Range (HDR) and Wide Color Gamut (WCG) header metadata.
    DXGI_HDR_METADATA_HDR10 : structure containing the metadata settings.
    DXGI_HDR_METADATA_TYPE : enum identifying the type of header metadata.
    DXGI_COLOR_SPACE_TYPE : defines the colorspace (sRGB, YCbCr), color range, gamma settings, and other details of the color format.
```
some minimal samples:
first D3D12 API but almost all HDR code is in DXGI calls which will OK also for D3D11
https://github.com/Microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12HDR
here you have also D3D11 HDR sample:
https://github.com/Microsoft/Xbox-ATG-Samples/tree/master/PCSamples/Graphics/SimpleHDR_PC
in addition to D3D12:
https://github.com/Microsoft/Xbox-ATG-Samples/tree/master/PCSamples/Graphics/SimpleHDR_PC12

**Comment by doitsujin** [comment]
Yeah, this requires extremely new DXGI revisions. I won't support them (and with the current state of mingw headers I *cannot* support them).

**Comment by oscarbg** [comment]
no problem.. only wanted to know if was possible to "easily" add or not..
thanks..

**Comment by oscarbg** [comment]
just pointing out that latest AMDVLK supports VK_EXT_hdr_metadata on Linux!
so first HDR Vulkan driver..
@doitsujin can share, if that fact, updates your interest to implement HDR on DXVK?
curiously today also tested latest Unity 2019.3.0a8 adds Windows D3D11 and D3D12 HDR support.. so maybe we may see Unity indie titles supporting HDR not too far away..

**Comment by valentyn-l** [comment]
Sorry to be writing on a supposedly Closed issue, however I am really wishing for HDR support in DXVK due to its great benefits to performance on Windows in select game (eg. Assassin's Creed Origins). This game supports HDR and it would be lovely if the developers of DXVK could implement an optional config flag for HDR for those that really want it. :)

**Comment by Blisto91** [comment]
Hi there.
This isn't a priority for the devs as HDR is pretty much not supported on Linux at the moment (as far as i know) and so i don't think any of the devs even have the hardware for it.
Also see https://github.com/doitsujin/dxvk/issues/2832
