### ISSUE TITLE
Shadows: Awakening black screen on startup

### ISSUE THREAD

**Issue by mozo78** [doitsujin/dxvk#616]
The game starts and it actually doesn't freeze. The DXVK HUD shows FPS are changing but the screen is black and it ain't goes any further. I waited for 10 minutes to no avail. A tried to install DX and to disable nvapi/64 also.

### Software information
Shadows: Awakening GOG

### System information
- GPU: GTX 1080Ti
- Driver: 396.54
- Wine version:  3.14
- DXVK version: 0.70 / master

### Apitrace file(s)

[shadows.zip](https://github.com/doitsujin/dxvk/files/2342302/shadows.zip)

### Log files
- d3d11.log:
https://pastebin.com/WT2ScPQm
- dxgi.log: 
https://pastebin.com/uzqqeWiD

**Comment by doitsujin** [comment]
The black screen is to be expected because the game doesn't even try to render anything. Does it work with wined3d?

**Comment by doitsujin** [comment]
Hm. Do you have access to a Windows machine to record an apitrace on that OS? There's no indication of what might be wrong, but it's not a rendering issue because, as mentioned, the game doesn't actually render anything.

**Comment by mozo78** [comment]
I'm very sorry but I don't use Windows.

**Comment by Tk-Glitch** [comment]
Here is a windows trace of the game : https://drive.google.com/file/d/19Qnn6xt9cwujWTualVgyYOcN-IHDdMbN/view?usp=sharing

**Comment by Illynir** [comment]
Probably the videos of logos and intro?

**Comment by mozo78** [comment]
This is the first thing I thought of but I couldn't find anything for no intro fix with on the net.

**Comment by m-svo** [comment]
This game needs MS Media Foundation to play intro videos. @lieff managed to play it, described here: https://github.com/ValveSoftware/Proton/issues/1102#issuecomment-419678627

**Comment by doitsujin** [comment]
Not my bug then, closing.
