### ISSUE TITLE
d3d11 Don't supported D3D11_BIND_STREAM_OUTPUT

### ISSUE THREAD

**Issue by Lee02** [doitsujin/dxvk#621]
thx fix D3D11_BIND_STREAM_OUTPUT.
error log:
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
warn:  D3D11Device: No matching border color found for (0.501961,0.501961,1,1)
warn:  D3D11Device: No matching border color found for (0.501961,0.501961,1,1)
err:   D3D11Device::CreateBuffer: D3D11_BIND_STREAM_OUTPUT not supported
err:   D3D11Device::CreateBuffer: D3D11_BIND_STREAM_OUTPUT not supported
err:   D3D11Device::CreateBuffer: D3D11_BIND_STREAM_OUTPUT not supported
err:   D3D11Device::CreateBuffer: D3D11_BIND_STREAM_OUTPUT not supported
err:   D3D11Device::CreateBuffer: D3D11_BIND_STREAM_OUTPUT not supported
err:   D3D11Device::CreateBuffer: D3D11_BIND_STREAM_OUTPUT not supported
warn:  D3D11Device: No matching border color found for (0.501961,0.501961,1,1)
warn:  D3D11Device: No matching border color found for (0.501961,0.501961,1,1)

but i need supported ask me

**Comment by doitsujin** [comment]
#135
