### ISSUE TITLE
GTAV requires AMD spoof when not using staging.

### ISSUE THREAD

**Issue by Guy1524** [doitsujin/dxvk#624]
Seeing that you added the AMD card spoof for dragon quest, I thought I'd mention that GTAV also requires it on vanilla wine.  Without it, GTAV will crash before opening up.

**Comment by tingvarsson** [comment]
Guy, the exact exe name is needed for it to be added to the list (not sure if @doitsujin has it already or not). So to speed up the process please provide it. Also double check if there might be alternative exe's (in some cases there are, e.g. beta version/single player vs multiplayer/runtime,  and then it is good to cover all right away)

**Comment by Guy1524** [comment]
Sure, it should be GTA5.exe

**Comment by doitsujin** [comment]
Fixed as of #626.
