### ISSUE TITLE
Is possible to override driver version info?

### ISSUE THREAD

**Issue by EduFrazao** [doitsujin/dxvk#636]
Hi. This is not a issue, only a doubt.
I've tried to run BattleField V, and this games asks for a nvidia driver version that only exists on Windows. Its possible to override the Driver version reported to the game? I'm using Nvidia proprietary driver, version 396.54.
Thanks!

**Comment by doitsujin** [comment]
DXVK does not report the driver version to the application, it must be queried in some other way (nvapi?) - not something I can fix, sadly.

**Comment by EduFrazao** [comment]
@doitsujin thank you very mutch for your fast answer!
I understand.
Thank you for your great job!

**Comment by lieff** [comment]
May be fake AMD card helps? It may cut nvapi path with Nvidia driver detect.

**Comment by lieff** [comment]
Here https://github.com/ValveSoftware/Proton/issues/37#issuecomment-415833819 instruction.

**Comment by EduFrazao** [comment]
@lieff Thanks, it works. After some crashs with the Origin Client, the game runs!

**Comment by lieff** [comment]
@EduFrazao mind make issue about spoof AMD card for BattleField V, so for other users it will work out-of-box.

**Comment by doitsujin** [comment]
There has been some discussion going on about reporting Nvidia cards as AMD cards by default, and I'm starting to think that it's better than adding exceptions for all these games.
