### ISSUE TITLE
Possibly impractical feature request: DXVK with Vulkan multi GPU support

### ISSUE THREAD

**Issue by minecraft2048** [doitsujin/dxvk#639]
Disclaimer: I don't know how DX11 works, how Vulkan works, and how DXVK translate DX11 into vulkan commands

With this, we can support something like crossfire/SLI on games that doesn't support crossfire/SLI at all, giving new life for those old multi GPU cards like HD 7990 and R9 265x2, assuming that Vulkan multi GPU works on Linux driver, DX11 can be translated into multi GPU vulkan without all the problems associated with original crossfire/SLI...

**Comment by doitsujin** [comment]
D3D11 does not have any sort of Multi-GPU support.

**Comment by minecraft2048** [comment]
ahh sorry for not searching for this beforehand
