### ISSUE TITLE
[AMD RADV] Final Fantasy XV low framerate for tessellation enable

### ISSUE THREAD

**Issue by hitman249** [doitsujin/dxvk#645]
### Software information
Final Fantasy XV
Resolution: 1280x720
Low settings

### System information
https://linux-hardware.org/?probe=0c49463415
- GPU: AMD RX480 4Gb
- Driver: AMD RADV
- Wine version: 3.16 esync
- DXVK version: 0.72

### Log files
- d3d11.log: 
[ffxv_s_d3d11.log](https://github.com/doitsujin/dxvk/files/2389071/ffxv_s_d3d11.log)

- dxgi.log: 
[ffxv_s_dxgi.log](https://github.com/doitsujin/dxvk/files/2389073/ffxv_s_dxgi.log)

### Bugs
Enable tessellation - 3.7 FPS
Disable tessellation - 50 FPS 

To 3.7 FPS
> Load on the cpu - 10%
> Load on the gpu - 99%

Previously, when tessellation enable, fps was not changed.

### Others 
My game directory default is read only mode, except d3d11.log and dxgi.log files.
Does DXVK write anything to the game catalog?

**Comment by doitsujin** [comment]
I'm aware, but no idea what causes it.

**Comment by BNieuwenhuizen** [comment]
Seems somewhat on the extreme side, but if I look at some windows complaints seems like a drop of >= 4x is to be expected on AMD GCN3 hardware. On the radv side I guess we could put an option in to limit the max tessellation factors just like the windows drivers have.

**Comment by hitman249** [comment]
```
# Overrides the maximum allowed tessellation factor. This can be used to
# improve performance in titles which overuse tessellation.
# 
# Supported values: Any number between 8 and 64

# d3d11.maxTessFactor = 0
```
Set `d3d11.maxTessFactor = 8` not changes (5 fps)

```
wine 3.17 staging esync

{
    "CPU": "AMD FX-8320E Eight-Core Processor",
    "GPU": "AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.23.0, 4.15.0-34-generic, LLVM 7.0.0) (0x67df)",
    "RAM": 16039,
    "Distr": "Ubuntu 18.04",
    "Linux": "Linux 4.15.0-34-generic x86_64",
    "GLIBC": "2.27",
    "Mesa": "18.3.0-devel"
}
```

**Comment by hitman249** [comment]
Found the reason, it was due to the fact that the folder with the game was available only for reading.
Secondly, it turned out that the `dxvk.conf` file must be inside the **prefix**.
Third, the `cache folder` must also be in the **prefix**.

After fixing all the problems, the game began to work quickly.
