### ISSUE TITLE
Winelib build broken

### ISSUE THREAD

**Issue by ssorgatem** [doitsujin/dxvk#651]
The commit a078bb947e862d4c85c729c135eb9b39dd9dd94c breaks the winelib build:

`[3/3] Linking target src/d3d11/d3d11.dll.so.
FAILED: src/d3d11/d3d11.dll.so 
wineg++  -o src/d3d11/d3d11.dll.so 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_annotation.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_blend.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_buffer.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_class_linkage.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_cmdlist.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_context.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_context_def.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_context_imm.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_counter_buffer.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_depth_stencil.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_device.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_enums.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_initializer.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_input_layout.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_interop.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_main.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_options.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_present.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_query.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_rasterizer.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_resource.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_sampler.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_shader.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_state.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_texture.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_util.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_view_dsv.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_view_rtv.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_view_srv.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/d3d11_view_uav.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/.._d3d10_d3d10_blend.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/.._d3d10_d3d10_buffer.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/.._d3d10_d3d10_depth_stencil.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/.._d3d10_d3d10_device.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/.._d3d10_d3d10_input_layout.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/.._d3d10_d3d10_query.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/.._d3d10_d3d10_rasterizer.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/.._d3d10_d3d10_sampler.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/.._d3d10_d3d10_texture.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/.._d3d10_d3d10_util.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/.._d3d10_d3d10_view_dsv.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/.._d3d10_d3d10_view_rtv.cpp.o' 'src/d3d11/src@d3d11@@d3d11.dll@sha/.._d3d10_d3d10_view_srv.cpp.o' ../src/d3d11/d3d11.spec -Wl,--no-undefined -Wl,--as-needed -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,d3d11.dll.so src/util/libutil.a src/dxbc/libdxbc.a src/dxvk/libdxvk.a src/spirv/libspirv.a -ldxgi -lwinevulkan -Wl,--end-group -pthread -m64 -mwindows 
/usr/bin/ld: src/dxvk/libdxvk.a(dxvk_shader_key.cpp.o): in function `dxvk::DxvkShaderKey::DxvkShaderKey()':
dxvk_shader_key.cpp:(.text+0x24): undefined reference to `dxvk::Sha1Hash::compute(unsigned char const*, unsigned long)'
/usr/bin/ld: src/dxvk/libdxvk.a(dxvk_shader_key.cpp.o): in function `dxvk::DxvkShaderKey::DxvkShaderKey(VkShaderStageFlagBits, void const*, unsigned long)':
dxvk_shader_key.cpp:(.text+0x75): undefined reference to `dxvk::Sha1Hash::compute(unsigned char const*, unsigned long)'
/usr/bin/ld: src/dxvk/libdxvk.a(dxvk_shader_key.cpp.o): in function `dxvk::DxvkShaderKey::toString[abi:cxx11]() const':
dxvk_shader_key.cpp:(.text+0x284): undefined reference to `dxvk::Sha1Hash::toString[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
winegcc: g++ failed
ninja: build stopped: subcommand failed.`

**Comment by doitsujin** [comment]
For god's sake... how do I fix this? The function that it's complaining about does exist and gets linked into the library, so there's nothing wrong...
