### ISSUE TITLE
Cars in DIRT 3 not properly rendered

### ISSUE THREAD

**Issue by random2324** [doitsujin/dxvk#652]
![deepinbildschirmfoto_20180916191209](https://user-images.githubusercontent.com/19872920/45802798-1eb54280-bcb8-11e8-9edc-08be8a082193.png)
![20180916183751_1](https://user-images.githubusercontent.com/19872920/45802800-21b03300-bcb8-11e8-9b0b-a1a77d887e06.jpg)
![20180916183818_1](https://user-images.githubusercontent.com/19872920/45802828-3391d600-bcb8-11e8-8fe8-1660ad8af566.jpg)
![deepinbildschirmfoto_20180916193239](https://user-images.githubusercontent.com/19872920/45804909-bcf7d700-bcbd-11e8-8353-323017bc71c9.png)

These screenshots show the difference of Windows 10 and DXVK.
The cars are rendered a lot darker.
The car windows are almost black.

After I experimented with the MSAA settings, I saw that DXVK can actually render the cars correctly.
The game starts with MSAA 4x. If I set MSAA to OFF, everything looks correct. If I set MSAA to 4x again it stays correct.

### Software information
Dirt 3 Complete Edition
Ultra Settings

### System information
- GPU: Radeon HD 7970
- Driver: Mesa git, LLVM 8.0.0 svn
- Wine version: 3.16
- DXVK version: problem also exists with current master

### Apitrace file(s)
Putting the dlls in the game folder like described in the wiki makes the game crash on start.
However I honestly dont understand whats meant with "dont use apitrace with DXVK".
If DXVK is disabled, how can you see the issue then? Isnt it rendering with Wine's stock D3D11 implementation?
Also is a trace from Windows needed?
Im sorry for not having a trace ready yet. 

### Log files
[dirt3_game_dxgi.log](https://github.com/doitsujin/dxvk/files/2400273/dirt3_game_dxgi.log)
[dirt3_game_d3d11.log](https://github.com/doitsujin/dxvk/files/2400274/dirt3_game_d3d11.log)

**Comment by doitsujin** [comment]
This is a known bug with RADV. Affects GTA V as well.

**Comment by random2324** [comment]
Good to know, thanks!
Some fine man made already a superb bug report: https://bugs.freedesktop.org/show_bug.cgi?id=107786
Still Leaving open in case someone else stumbles about this.

**Comment by doitsujin** [comment]
Please test if this [RADV patch](https://patchwork.freedesktop.org/patch/251674/) fixes the issue.

I cannot test the game, it doesn't work on my Wine setup.

**Comment by random2324** [comment]
This patch is fixing the issue. Thanks everyone involved.
