### ISSUE TITLE
small rendering issue in DQ11

### ISSUE THREAD

**Issue by Glog78** [doitsujin/dxvk#653]
The characters are all kinda screwed up.
https://i.imgur.com/JZzTW7Y.jpg

### Software information
Name of the game, settings used etc.

### System information
- GPU: GTX 970
- Driver: 410.57
- Wine version:  PROTON 3.7-6
- DXVK version:  current from git

### Apitrace file(s)
https://www.dropbox.com/s/urv674x47cl5mt9/dq11_trace.7z?dl=0 (within dxvk)

**Comment by doitsujin** [comment]
What's wrong with it? How is it supposed to look?

**Comment by Glog78** [comment]
suggest to close after our talk on discord.
