### ISSUE TITLE
DXVK as a graphics SDK for native Linux apps?

### ISSUE THREAD

**Issue by prashantraina** [doitsujin/dxvk#656]
Can DXVK be used as an alternative to OpenGL to make **native** Linux (not Wine) or cross-platform apps? It could be a great alternative for people who find the DirectX API cleaner than OpenGL and simpler than Vulkan.

**Comment by doitsujin** [comment]
The DirectX APIs are not cross-platform, and parts of it (specifically, DXGI) would have to be redesigned to allow native Linux support. So no, this is not possible, it could be used for wine-based ports though.
