### ISSUE TITLE
A tool to precompile shader caches outside of game context would be nice

### ISSUE THREAD

**Issue by ryao** [doitsujin/dxvk#660]
It would be nice if there were a tiny executable that could precompile the shader cache outside the context of a game by taking the path to a shader cache as an argument. That way people could use a simple find command to locate all DXVK cache files on a system and execute the tool on each.

Someone on reddit mentioned that he uses mesa-git and that DXVK’s cache will be a huge improvement for him. It occurs to me after reading the release notes that a simple tool that hooked into DXVK could make the shader cache even more of an improvement for him. He could run that tool as part of a find command right after doing a Mesa update and then have a completely updated driver cache, which should reduce the CPU usage hit at game start.

**Comment by doitsujin** [comment]
Not possible because DXVK's state cache stores no shaders.

**Comment by John-Gee** [comment]
Probably a naive question, but would it not be worth it to store the shaders on top of the state, to allow this?
