### ISSUE TITLE
Create HUD indicator for CPU and GPU LOAD

### ISSUE THREAD

**Issue by benjamimgois** [doitsujin/dxvk#661]
I think it would be awesome if DXVK could display the CPU and GPU LOAD on the HUD, it could help trouble shooting performance issues for users and developpers. Currently theres a FORK of DXVK created by "flighlessmango" that already implement it, take a look:

https://github.com/flightlessmango/dxvk

Video of it in action:
https://www.youtube.com/watch?v=qubt4vrrh_E&lc=z22oy3zqvyeogbhwo04t1aokgwk0y3jarb5wzyuangerbk0h00410.1537297077644542&feature=em-comments

**Comment by doitsujin** [comment]
The HUD exists mostly for debugging and performance monitoring, it is **not** intended to be a system monitor, which would by the way only work on one platform. See https://github.com/doitsujin/dxvk/issues/488#issuecomment-403622075
