### ISSUE TITLE
Heroes of the Storm: Some minimap elements are missing

### ISSUE THREAD

**Issue by aufkrawall** [doitsujin/dxvk#663]
The minimap doesn't show the teams' cores and also the lava wave of Ragnaros is missing.
To reproduce, just start a custom game or the try mode with Ragnaros, set hero level to 10 and choose lava wave as ultimate talent.
Apart from that, the visuals seem to be absolutely fine.

### Software information
I tested in WQHD with maximum quality settings.
Latest HotS versions to date.

### System information
- GPU: GTX 1070 Ti
- Driver: 410.57
- Wine version: current wine-tkg-staging-git with esync
- DXVK version: 0.72_41_gb9ff234

### Log files
- dxgi.log: 
https://pastebin.com/G3bhq9bP

**Comment by doitsujin** [comment]
Same issue as #372 maybe?

Can't do much without an apitrace, sorry.

**Comment by aufkrawall** [comment]
You are absolutely right, thanks for pointing me to this. The game seems to run perfectly now.

Btw. once again very impressive that HotS hardly runs slower in CPU limit than on Windows with Nvidia DX11 driver.
