### ISSUE TITLE
Trackmania 2 GPU hang on loading screen

### ISSUE THREAD

**Issue by BlazeKl** [doitsujin/dxvk#664]
The game started to hang on some maps since commit https://github.com/doitsujin/dxvk/commit/6579b2ad994f0ef43459f4dd2150ca1e8c886e13

recorded an apitrace with an older version of dxvk since both wined3d and newer dxvk have problems with the loading screen crashing or hanging, I can trace another one with latest dxvk if you need it

### Software information
Trackmania 2 standalone non steam version
max settings

### System information
- GPU: AMD R9 270
- Driver: Mesa-git-ed797f6597
- Wine version: 3.16 staging esync pba
- DXVK version: 0.80

### Apitrace file(s)
- https://drive.google.com/open?id=1lPFRxiAN1-M3o4173TYF0Nu2Zg4hr9zy

### Log files
- d3d11.log: [ManiaPlanet_d3d11.log](https://github.com/doitsujin/dxvk/files/2411474/ManiaPlanet_d3d11.log)
- dxgi.log: [ManiaPlanet_dxgi.log](https://github.com/doitsujin/dxvk/files/2411475/ManiaPlanet_dxgi.log)

**Comment by BlazeKl** [comment]
https://github.com/doitsujin/dxvk/commit/6579b2ad994f0ef43459f4dd2150ca1e8c886e13 introduced the bug

**Comment by ZeroFault** [comment]
I wonder if this is related to the freeze I get in Valley benchmark on WIndows w/ DXVK. It was also introduced by the [6579b2a](https://github.com/doitsujin/dxvk/commit/6579b2ad994f0ef43459f4dd2150ca1e8c886e13) commit

**Comment by doitsujin** [comment]
Sorry for the very late reply. Is this still an issue with current DXVK and driver versions? I can't reproduce the hang with your apitrace on my RX 480.

**Comment by BlazeKl** [comment]
tested the game again with recently (5 minutes ago) compiled mesa and dxvk and it seems the hang is fixed

**Comment by BlazeKl** [comment]
tested the game again with recently (5 minutes ago) compiled mesa and dxvk and it seems the hang is fixed

**Comment by BlazeKl** [comment]
the problem is that the game seems to hang when the game is running too fast because if I trace the game or do a hang report with latest dxvk the game doesn't hang at all

**Comment by BlazeKl** [comment]
can't replicate the issue anymore with my new RX 470, maybe this issue is releated to GCN 1.0 or it just got fixed some time ago. Anyways I'll close this unless someone get this problem again
