### ISSUE TITLE
Star Control: Origins - no particles except the top-left corner

### ISSUE THREAD

**Issue by varris1** [doitsujin/dxvk#666]
This makes planetary landing pretty difficult because you can't see if the weather in front of you will destroy your lander or not. 

Tested with gverm's GetQueuedCompletionStatusEx stub.
https://www.winehq.org/pipermail/wine-devel/2018-September/132582.html

![Screenshot](https://user-images.githubusercontent.com/38386180/45977583-5884a100-c04a-11e8-9d91-bf32a6c2b81d.png)

### Software information
Game: Star Control: Origins

### System information
- GPU: NVIDIA GTX 970
- Driver: 396.54.06
- Wine version: wine-3.16-149-gb1a3b9e5ce (Staging)
- DXVK version: a950872

### Apitrace file(s)
https://mega.nz/#!DixWxAaS!3IfquELb30LOWE7FFmFugcFm3I8lqYUfV5ZW-twDrV4 (recorded on a different PC with Windows 7. Crashes on my own computer)

### Log files
- d3d11.log: 
[StarControl_DX11_d3d11.log](https://github.com/doitsujin/dxvk/files/2412769/StarControl_DX11_d3d11.log)

- dxgi.log: 
[StarControl_DX11_dxgi.log](https://github.com/doitsujin/dxvk/files/2412770/StarControl_DX11_dxgi.log)

**Comment by doitsujin** [comment]
I found a workaround to make the trace replay - it appears that it destroys an image view that is still used later - but i can't see any particles at all. Where are they supposed to appear in the trace?

**Comment by doitsujin** [comment]
Update: DXVK doesn't handle color->depth and depth->color image copies correctly in case the images involved are multisampled. This might be related.

**Comment by doitsujin** [comment]
The [dxvk-meta-copy](https://github.com/doitsujin/dxvk/tree/dxvk-meta-copy) branch contains a WIP fix for this issue.

**Comment by doitsujin** [comment]
Should be fixed as of c5f7f9f3b08d7d0fed1ee0fce3bd766e8002cfee.
