### ISSUE TITLE
GCC generates slow SHA1 assembly code

### ISSUE THREAD

**Issue by ryao** [doitsujin/dxvk#667]
Running `x86_64-w64-mingw32-objdump -D ./src/d3d11/d3d11.dll` after building d3d11.dll shows that the generated assembly code for the SHA1 routines is fairly terrible. There only 2 SSE/SSE2 instructions in SHA1Init and that is it.

It would be a good idea for someone to find a SSE2 routine that could be used here at the very least. It would also be useful to add support for Intel's SHA extensions when they are available:

https://en.wikipedia.org/wiki/Intel_SHA_extensions

Optimized routines for AVX and AVX2 would also be nice. It might be worthwhile to explore whether the graphite optimizations can improve things here as part of #646. @pchome is already building with graphite, so he should be able to just disassemble his binaries and look through them, provided that he has debuginfo (as I am not sure if he will be able to spot the routines without it).

**Comment by pchome** [comment]
Isn't `sha1` are part of `openssl` (or so) ? Maybe worth to use system one, or maybe it not affect performance in dxvk at all.
Isn't generic release must not contain advanced instructions?
Isn't `-march=native` will produce more optimized code for your local builds?

**Comment by ryao** [comment]
@pchome It is possible to have multiple routines, do CPU detection at initialization and pick the routine best suited to the processor.

> Isn't `sha1` are part of `openssl` (or so) ?
Yes.
> Maybe worth to use system one, or maybe it not affect performance in dxvk at all.
This is being built as a Windows DLL. You cannot use the system OpenSSL because that does not exist on Windows.

As for affecting DXVK performance, I really ought to profile (and I will when I have a working winelib. build), but given that SHA1 is expensive, I think that it will be a non-negligible amount of time. SHA1 is being used by the state cache.
> Isn't generic release must not contain advanced instructions?
Well, SSE and SSE2 are part of x86_64, so they are always safe to use there. In all other cases, it is possible to have multiple routines, do CPU detection at initialization and pick the routine best suited to the processor.
> Isn't `-march=native` will produce more optimized code for your local builds?
I am not building with -march=native in this case, but I doubt it would make a difference here because the compiler is refusing to use SSE/SSE2 intelligently on x86_64 where it is permitted to use it with or without -march=native.

I found some resources that might be useful:

https://stackoverflow.com/questions/21107350/how-can-i-access-sha-intrinsic
https://github.com/noloader/SHA-Intrinsics

**Comment by pchome** [comment]
> The last one shows a “fast” implementation

We can simply use `-O1` for `C` (`-fomit-frame-pointer` enabled at -O1), this optimization will cost nothing.
And yes, those numbers need to be retested using recent GCC version.

**Comment by ryao** [comment]
An AVX2 implementation:

https://software.intel.com/en-us/articles/improving-the-performance-of-the-secure-hash-algorithm-1

**Comment by doitsujin** [comment]
Seriously, who cares? The SHA-1 code is not performance-critical.
