### ISSUE TITLE
State cache file default location

### ISSUE THREAD

**Issue by rcpoison** [doitsujin/dxvk#677]
I'm developing a pool/repository for the state caches and have a small request.

Would you consider changing the default location for .dxvk-cache file to either:
- the same directory as the .exe (preferred by me)
- a static subdirectoy in C:

instead of $CWD.

Otherwise I have no way of reliably determining the target directory for a .dxvk-cache based on the exe's name+path.

In case that is not something you want to implement, would there be noticable side-effects in DXVK if I merged the DxvkStateCacheEntry's from different games (with the same executable name)?

**Comment by K0bin** [comment]
> Would you consider changing the default location for .dxvk-cache file to either: the same directory as the .exe (preferred by me)

That is what it's doing by default already.

You can even change the path by using the `DXVK_STATE_CACHE_PATH` environment variable. 

More information in the [readme](https://github.com/doitsujin/dxvk#state-cache) and the 0.80 release notes.

**Comment by doitsujin** [comment]
Why not just use the `DXVK_STATE_CACHE_PATH` environment variable to specify a directory?

There is no reliable way for DXVK to determine the path to the app's executable, and writing somewhere to the user's 'home' directory (on the Windows side) is not an option because it's a) fragile and b) the Windows APIs involved are completely retarded.

**Comment by rcpoison** [comment]
> Why not just use the DXVK_STATE_CACHE_PATH environment variable to specify a directory?
That would require user intervention for each game/wine prefix and appearently there are games that.change their CWD.
My implementations scans for executables in passed directories and queries the server for available cache entries for them, it would be nice for that to just work in a default setup instead of the user having to either manually specify file locations for each game or set DXVK_STATE_CACHE_PATH for each wine prefix.

> There is no reliable way for DXVK to determine the path to the app's executable
https://stackoverflow.com/questions/2647429/c-windows-path-to-the-folder-where-the-executable-is-located wouldn't work?
Sorry, I'm having trouble building mingw to try myself :(

**Comment by ryao** [comment]
You could likely add it to the user’s ~/.profile. It would require a log out / log in after installation though to ensure that it is reflected.

**Comment by rcpoison** [comment]
@ryao: sure, but that would affect all wine prefixes, and I wouldn't be able to tell games apart having the same executable name.

**Comment by rcpoison** [comment]
Also, setting it as global variable would probably(from a quick glance at the code) result in DXVK sharing the same state cache across games with the same executable name.

**Comment by doitsujin** [comment]
> would probably(from a quick glance at the code) result in DXVK sharing the same state cache across games with the same executable name.

That's not *too* common, and DXVK doesn't really care if you mix entries from multiple different games.

**Comment by rcpoison** [comment]
@doitsujin ok, thanks :)

I assume the .state-cache would have to grow to a respectable size for DXVK to run into problems?
Would there be additional heap being used apart from the structs size?
In that case I'll go ahead and simply merge all DxvkStateCacheEntry's with the same name.

**Comment by doitsujin** [comment]
Overwatch players get cache files in excess of 45 MB, so yeah, they can get fairly big without causing too much trouble in practice.

**Comment by rcpoison** [comment]
Got it, thanks.

https://github.com/rcpoison/dxvk-cache-pool/commit/df619164cca0d2fe439e156b8c78d8f382cf49e9

PS: That overwatch cache file sounds interesting for testing purposes if someone wants to send it to me.

**Comment by ryao** [comment]
Sharing DXVK cache files is insecure, so I would advise against using cache files from people that you do not know.

**Comment by ryao** [comment]
I am just making certain that you know that before you take a cache file from someone else. I think that you should have people PGP sign their caches so that trusted individuals who contribute cache files can at least have the origin of their contributions verified.

For example, I have a fairly well trusted PGP key. If I were to send you my cache file for overwatch and sign it with my key, I would be asserting that it is not malicious at the risk of my reputation if that should turn out to not be the case. As a consequence, it should be trustworthy to the extent that people trust that I am not going to throw my reputation away to compromise them.

**Comment by rcpoison** [comment]
@ryao I don't think you got my point.

> A web of trust is great unless you can not validate the subject

There's currently no way to validate the cache entry.
Your signature means nothing if you sign a message you yourself can not validate.
Hence you shouldn't sign said message in order not to tarnish your reputation.

**Comment by rcpoison** [comment]
@ryao the cache files have little entropy and thus compress well. Providing me a download would be nice. Thanks.

**Comment by ryao** [comment]
> @ryao I don't think you got my point:
> 
> > A web of trust is great unless you can not validate the subject
> 
> There's currently no way to validate the cache entry.
> Your signature means nothing if you sign something you yourself can not validate.
> Hence you shouldn't sign said message in order to not tarnish your reputation.

I can state that I generated it myself.

> @ryao the cache files have little entropy and thus compress well. Providing me a download would be nice. Thanks.

A download URL has the problem that once I put it up and link to it, I will feel obligated to host it forever, and I don’t want to volunteer infrastructure space for a cache file.  Send an email to my @gentoo.org address asking for it and I will reply with the cache file as an attachment.

**Comment by ryao** [comment]
@rcpoison It occurred to me that it is possible to attach files to github comments. Here is my 
[Overwatch dxvk-cache file](https://github.com/doitsujin/dxvk/files/2430303/Overwatch.dxvk-cache.gz). It has sha256 fa34bff4ee406fbd7da30dc27ff53249353b60ed7cb7586c5b0f5cb4760825e3.

**Comment by ryao** [comment]
By the way, if we had a way of validating cache entries, we would not need to trust people because we could check what they uploaded.

**Comment by doitsujin** [comment]
And how do you want to reasonably validate them? Reimplementing all Vulkan validation rules for pipeline creation just isn't viable, it's guaranteed to introduce bugs and break games.

**Comment by rcpoison** [comment]
@doitsujin I don't seem to be able specify a state cache dir outside of the wine prefix:
```
export DXVK_STATE_CACHE_PATH=/home/poison/.cache/dxvk
```
```
warn:  DXVK: No state cache file found
warn:  DXVK: Failed to open state cache file
```
is this working as inteded? Does steam/proton have a patch to write the caches to SteamApps/shadercache/*/DXVK_state_cache ?
Or is there some symlinking going on that I cant see?

Sorry for bothering you again :/

**Comment by pchome** [comment]
`mkdir -p "$DXVK_STATE_CACHE_PATH"` ?

**Comment by rcpoison** [comment]
@pchome Of course the directory exists. And is writable by my user.

**Comment by ryao** [comment]
Use drive z: to access out of the wine prefix.
