### ISSUE TITLE
[Feature Request] Fast/Enhanced Sync Equivalent (Triple Buffering)

### ISSUE THREAD

**Issue by CalcProgrammer1** [doitsujin/dxvk#678]
I'm not sure if DXVK is the place to put this, but on Windows I've gotten used to using Fast Sync in games that require fast reaction time.  I mainly use it for Overwatch and CS:GO.  As far as I know there isn't an equivalent feature in the Linux/X11 drivers and the feature is actually only useful for Direct3D games.  If it truly is only useful for D3D, it would make sense to implement at the D3D to Vulkan layer I'd expect.

Basically Fast Sync lets your game render at frame rates much higher than your monitor's refresh rate without introducing tearing.  It does this by syncing the most recently rendered frame.  On nVidia it seems the driver naturally locks frame rate to a multiple of monitor refresh as available, it hovers either around 120fps or 180fps on my setup with a 60Hz panel.  AMD calls the feature Enhanced Sync and pretty much works the same way, though I'm not sure they do the multiple of monitor refresh lock thing nVidia seems to do.

I compared Overwatch in Windows vs. Linux tonight at a gaming event and I performed a lot better on the Windows setup with the same settings except fast sync instead of vsync.  The mouse latency felt huge on Linux and I had trouble aiming while with fast sync on Windows, aim felt smooth and natural.  I was getting 60fps constantly in Linux.  If I disable vsync on Linux, it starts tearing horribly and stuttering to the point of being unplayable.

**Comment by doitsujin** [comment]
Sounds like what the `MAILBOX` present mode should do. I'll add a config option to enforce it, but can't promise that it works as expected on current drivers.

**Comment by doitsujin** [comment]
Done. At least on RADV this will **not** work in fullscreen mode, which seems to be a limitation of the window system - can't do anything about that. Also, on Nvidia, you might see tearing.
