### ISSUE TITLE
Saints Row 4: CopySubresourceRegion: Incompatible texel size

### ISSUE THREAD

**Issue by farmboy0** [doitsujin/dxvk#680]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

As native Saints Row 4 doesnt work for me anymore, I turned to the windows version. It runs great with DXVK but the log gets spammed with these error messages.
err:   D3D11: CopySubresourceRegion: Incompatible texel size
  Dst texel size: 4
  Src texel size: 8
After a ~1Hr play session that log was at ~40MB.

### Software information
Saints Row IV Windows

### System information
- GPU: R9 380X
- Driver: Mesa 18.2, LLVM 7
- Wine version: 3.17
- DXVK version: 0.80

### Apitrace file(s)
Apitracing with or without DXVK was not successful.

### Log files
[SaintsRowIV_d3d11.log](https://github.com/doitsujin/dxvk/files/2431449/SaintsRowIV_d3d11.log)
[SaintsRowIV_dxgi.log](https://github.com/doitsujin/dxvk/files/2431451/SaintsRowIV_dxgi.log)

**Comment by doitsujin** [comment]
It's a known game bug with Saints Row 4. If there are no rendering issues, I'd recommend disabling the log with `DXVK_LOG_LEVEL=none`.

**Comment by farmboy0** [comment]
Thanks for the info. I'm closing this issue.
