### ISSUE TITLE
Assassin's Creed Odyssey: wrong aspect ratio and incorrect rendering

### ISSUE THREAD

**Issue by Oschowa** [doitsujin/dxvk#688]
Assassin's Creed Odyssey seems to incorrectly assume that the display has an 4:3 aspect ratio and will display black bar at the top and bottom of the screen, no matter how much i fiddle with the settings.
Also there are rendering issues when running the benchmark mode on lowest settings like distorted npc's.
The apitrace i recorded goes only up until the main menu, where the game crashes, and thus will likely only be useful to debug the aspect ratio issue. I will also attach screenshots of the rendering issues, however useless they may be. Sadly i had to record the apitrace under dxvk as the game would not load with wined3d and i have no access to windows at the moment.
Another thing to note is that the performance is pretty poor, on lowest settings it struggles to even hold 30 fps; esync on/off doesn't seem to make a difference.

### Software information
Assassin's Creed Odyssey all settings low.

### System information
- GPU: RX580
- Driver: 18.2.1 (LLVM 7)
- Wine version: 3.17 / 3.15-esync
- DXVK version: v0.81-1-g87f1cd2

### Apitrace file(s)
[apitrace.xz](https://drive.google.com/open?id=1vFyghPpwZ_M5K16-xv1Vp97jauL4Ma9l)
[screenshots of incorrect rendering](https://drive.google.com/open?id=1z4Uuim_8OWj9rpgal8aYjozqrhizOl3O)

### Log files
[d3d11.log](https://gist.github.com/Oschowa/ef954cbeb5444d4490d41d7eece74924/raw/c3cefe534a9b6c21a8e5b1d30fdcc00d55bdb9b2/ACOdyssey_d3d11.log)
[dxgi.log](https://gist.githubusercontent.com/Oschowa/ef954cbeb5444d4490d41d7eece74924/raw/c3cefe534a9b6c21a8e5b1d30fdcc00d55bdb9b2/ACOdyssey_dxgi.log)

**Comment by Oschowa** [comment]
Can't test on windows; I just got the game with my GPU and thought i might as well test it out.
FWIW i also tried spoofing an nvidia card, as the game seems to use amd_ags, but it has no effect.

> Actually it doesn't even replay for some reason

Don't know what's wrong there, i just redownloaded the trace and it replays fine on my end.

**Comment by doitsujin** [comment]
Update:
- The aspect ratio issue is a wine bug, not a DXVK bug. This doesn't happen on Windows.
- The rendering issues are exclusive to Mesa 18.2, it renders fine with Mesa 18.3-git and LLVM 8.0.
![bildschirmfoto-339](https://user-images.githubusercontent.com/25567304/46580476-a673ae80-ca25-11e8-831e-4ab6708df5d1.png)

**Comment by doitsujin** [comment]
Thanks for the feedback. I guess for the aspect ratio issue it might be worth filing a wine bug.

For me, the game first started with 640x480 resolution, and while it allows me to change the resolution correctly, it has the same black bars as it does on your end. On Windows with DXVK, it detects 1920x1080 correctly and has no black bars.

**Comment by ah-** [comment]
How did you get it to start? My installation seems to crash after the intro videos have played, any hints?

**Comment by doitsujin** [comment]
What's your wine version?

It's working for me pretty much out of the box with wine-staging 3.16 (+esync) and a fresh prefix that has only Uplay and DXVK in it.

**Comment by ah-** [comment]
Pretty much the same, tried a bunch of different versions, including 3.16 staging. Installed via lutris winesteam.

Would you mind sharing your ACOdyssey.ini from drive_c/users/you/My\ Documents/?

**Comment by ah-** [comment]
Pretty much the same, tried a bunch of different versions, including 3.16 staging. Installed via lutris winesteam.

Would you mind sharing your ACOdyssey.ini from drive_c/users/you/My\ Documents/?

**Comment by doitsujin** [comment]
Here you go (thank Github for being annoying and blocking certain *file extensions*):
[ACOdyssey.ini.txt](https://github.com/doitsujin/dxvk/files/2454271/ACOdyssey.ini.txt)

FWIW I'm running the Uplay version of the game, not the Steam one. Maybe there are issues with that.

**Comment by ah-** [comment]
Great, thanks! With a few tweaks to my resolution settings it runs now :)

```
FullscreenWidth=1920                                                                            
FullscreenHeight=1080                                                                           
WindowedWidth=1920                                                                              
WindowedHeight=955                                                                              
WindowMaximised=0                                                                               
RefreshRate=60                                                                                  
WindowMode=2
```

It seems like something around resolution detection is broken, i had a wonky refresh rate in there, and way to small widths/heights. Still have some rendering issues, but I that seems to be expected since I'm running mesa 18.2 and llvm 7.

**Comment by doitsujin** [comment]
Yes, resolution detection is broken, the only way to fix it currently is to run the game (but not uplay) in an appropriately-sized virtual desktop. But as mentioned in this thread, this is not a DXVK bug.

**Comment by Rakan-Senpai** [comment]
> Great, thanks! With a few tweaks to my resolution settings it runs now :)
> 
> ```
> FullscreenWidth=1920                                                                            
> FullscreenHeight=1080                                                                           
> WindowedWidth=1920                                                                              
> WindowedHeight=955                                                                              
> WindowMaximised=0                                                                               
> RefreshRate=60                                                                                  
> WindowMode=2
> ```
> 
> It seems like something around resolution detection is broken, i had a wonky refresh rate in there, and way to small widths/heights. Still have some rendering issues, but I that seems to be expected since I'm running mesa 18.2 and llvm 7. I've got the steam version, so at least DRM doesn't seem to be an issue.

hey, didn't that cause your FPS to decrease?
