### ISSUE TITLE
Dauntless almost instant crash

### ISSUE THREAD

**Issue by nairaner** [doitsujin/dxvk#69]
### Software information
Dauntless - which is base on Unreal Engine 4.
Crashes gracefully before showing anything. 

### System information
- GPU: Nvidia
- Driver: proprietary 
- Wine version: wine-staging 2.21
- DXVK version: latest - 8f134bafcfe9136f924df2ae1d2946e46b1b7795

### Apitrace file(s)
- https://mega.nz/#!NVQSiabB!5M9mzDHLGMHjLlgj44CRDTmD_1lwdt40kubWgI-zb7o

### Log files
- d3d11.log:
[Dauntless-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/1713938/Dauntless-Win64-Shipping_d3d11.log)
- dxgi.log: 
[Dauntless-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/1713937/Dauntless-Win64-Shipping_dxgi.log)
- Wine log:
[wine.log](https://github.com/doitsujin/dxvk/files/1713943/wine.log)

**Comment by qwertychouskie** [comment]
Make sure you have `libtxc-dxtn-s2tc` installed, Wine can't find it.

**Comment by nairaner** [comment]
With DXVK 7ae4904ae9f6cdaf618fced661bbc732fac3dd83 with Vesim patches main menu now loads, but crashes during loading into gameplay with:
```
0090:err:seh:RtlUnwindEx invalid frame 33170008 (0x327e2000-0x33170000)
0090:err:seh:call_stack_handlers invalid frame 33170008 (0x327e2000-0x33170000)
0090:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
```
When using wined3d it works, but I'm unable to get apitrace as that also crashes.

On windows both apitrace and DXVK works, but that might be the issue with access violation being often ignored on windows 
New apitrace soon(1.1GB zipped, 2.7GB unpacked)

**Comment by doitsujin** [comment]
Please re-test with recent builds since some missing functionality has been implemented.

**Comment by nairaner** [comment]
It works, but there were shaders, which crash crash on Nvidia and even after optimizing I get ` DxvkComputePipeline: Failed to compile pipeline`. I already sent them on discord, but just in case they get lost 
[dauntless_shaders.zip](https://github.com/doitsujin/dxvk/files/1826690/dauntless_shaders.zip)

Unless you pushed some fix for these yesterday, this should be current status
