### ISSUE TITLE
Enter the Gungeon black screen

### ISSUE THREAD

**Issue by iLiwe** [doitsujin/dxvk#690]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Name of the game, settings used etc.
Enter the Gungeon (GOG version)
Used a 960x540 virtual desktop (also tried with no virtual desktop)

### System information
- GPU: Intel HD Graphics (Baytrail)
- Driver: mesa 18.3 devel
- Wine version: staging-git version with gallium nine, pba and esync patches
- DXVK version: 0.81

### Apitrace file(s)
- I wasn't able to trace, it gave me "binaries mismatch use 32-bit version" error. I did used 32-bit then but no luck, it still gave the same error.

### Log files
- d3d11.log: https://paste.ee/p/rBTlB
- dxgi.log: https://paste.ee/p/rBTlB (They are on the same url)

The game opens and everything works, except that the screen is literally black. Sound is working, i can even navigate menus and play the game. I opened dxvk hud, it shows something around 60 fps, but there is just pure black.

The game worked on wined3d11 with no errors and such, and the performance was good. The thing is, i can't run ANY vulkan game properly. The texts are white boxes, no rendering is happening etc. I guess that my Baytrail does not support vulkan? It does support up to OpenGL 4.2 and DirectX 11.2 though.

**Comment by doitsujin** [comment]
The game runs out of memory. This is not a bug that can be fixed, you could try patching the game exe to be large address aware.

**Comment by iLiwe** [comment]
Well... For testing Vulkan in my system because i literally don't have any games that use Vulkan. And i downloaded the GOG version from the internet, which there was only a Windows version. I basically pirated the game. I know, i should buy the game.

So patching the .exe file, how can i even do that? I don't know anything about that.

**Comment by doitsujin** [comment]
I cannot provide support for pirated games. Feel free to file a new report once you have a legitimate version of the game,
