### ISSUE TITLE
GPU Memory detection - Unigine Benchmarks

### ISSUE THREAD

**Issue by SveSop** [doitsujin/dxvk#691]
Not sure if this is only happening in Unigine Heaven/Valley, or if other "games" have similar issues. Different apps like "GPU Caps Viewer" and such with some built-in vulkan/openGL tests seemingly shows correct memory.. But Unigine benchmarks in DX11 mode does not.

### Software information
Unigine Heaven

### System information
- GPU: nVidia GTX 970 (4GB)
- Driver: 410.57
- Wine version: 3.17-staging(Git: cc4b28a99df649d2885c14fd28c2ad2f0c2abdad)
- DXVK version: 08b241b3ea7e6204588c4412e977d0262f1f3557

Unigine Heaven w/DXVK
![heaven_dxvk](https://user-images.githubusercontent.com/33990277/46686667-3027a580-cbf9-11e8-9688-39d687b5305e.jpg)
Unigine Heaven w/WineD3D
![heaven_wined3d](https://user-images.githubusercontent.com/33990277/46686671-33229600-cbf9-11e8-98a4-7f19579f2586.jpg)

**Comment by doitsujin** [comment]
This is not a bug. DXVK caps the amount of video memory reported for 32-bit applications to 3GB deliberately in order to work around issues with misbehaving applications.

Also, please do not use wined3d as a reference point. Use Windows as a reference point.

**Comment by SveSop** [comment]
> Also, 32-bit D3D11 applications cannot support more than 4GB of VRAM anyway due to API design limitations. In practice, there shouldn't be any downsides to this limitation because most 32-bit games need 2GB of VRAM at most, and DXVK uses the actual VRAM size to do its internal memory management.

Ah, yeah a 32-bit app would not be able to use 4GB Vram + whatever app memory from the actual app itself anyway... Just looked wrong :)

> Also, please do not use wined3d as a reference point. Use Windows as a reference point.

Meaning? I should grab me a copy of Winblow$ to test things? Aint effin'g gonna happen :)
