### ISSUE TITLE
Add option to change default mipmapLodBias

### ISSUE THREAD

**Issue by pchome** [doitsujin/dxvk#694]
Some old titles looks more natural when this option set to e.g. `-1`.

Tested on `SaintsRow3`: by default textures are blurry, even with all graphic options set to its maximum values. Setting `info.mipmapLodBias` to `-1` noticeable improve textures. No performance drops noticed for SR3 (looks like it even improved a bit, but not sure).

![sr3default-p](https://user-images.githubusercontent.com/10661854/46905472-f5758400-cefc-11e8-8af2-55018a39b59d.png) ![sr3new-p](https://user-images.githubusercontent.com/10661854/46905473-f5758400-cefc-11e8-9bd3-1641804053f4.png)

If performance can improved when using higher positive values for `info.mipmapLodBias`, this can help some new titles to be played on weaker hardware, e.g. Batman: AK.

Inspired by `libstrangle` PICMIP env var (tested on GTA IV: EFLC):
> You can adjust the mipmap lod bias in both opengl and vulkan with the environment variable PICMIP.
> A higher value means blurrier textures. A negative value could make textures crisper.

Changes used:
https://gist.github.com/pchome/74707d21f750d25cdf6fe050cc2c8a8f

P.S. not a PR because I'm actually don't know what I'm doing ;)

**Comment by pchome** [comment]
Tested this with The Witcher 3.

Default `TextureMipBias` value may depend on game's graphics preset, and forcing it to `-1` (along with disabling `Sharpening`, `Blur` and `Anti-aliasing` post-processing options) can improve  overall image quality.

`TextureMipBias` can be found/tuned in `bin/config/base/rendering.ini`
or `292030/pfx/drive_c/users/steamuser/My Documents/The Witcher 3/user.settings`
Default: 0
```ini
[Rendering]
TextureMipBias=0
```

**Comment by pchome** [comment]
#### Stalker: CoP (DX10)
_Max Textures/Objects (default)_
![stalker-cop-dx10](https://user-images.githubusercontent.com/10661854/49332573-f733fd80-f5b7-11e8-8a57-5c11a82905f1.png)

_Max Textures/Objects (LOD Bias hack)_
![stalker-cop-dx10-miplodbias -1](https://user-images.githubusercontent.com/10661854/49332574-f7cc9400-f5b7-11e8-8b96-bcd54cda83b7.png)

Updated hack: https://gist.github.com/pchome/cc45ccf9c749c0434645f812036ddc42

**Comment by pchome** [comment]
> Not sure what is the max, but i would say 2 is pretty horribly blurry and crappy.

You can check [libstrangle README](https://gitlab.com/torkel104/libstrangle#experimental-stuff) page, where `PICMIP=1337` turns `vkQuake` into the "modern" (texture-less ?) game.

The result can vary, depend on game, settings, hardware(?) and your own opinion/vision.

I read something like: for 4k you can set `-2 or -1`, for `1080` -- `-0.7 or -0.4`, ...

With this hack you can't set less then `-1`, because I don't know what the reasonable minimum should be. And I don't use values other than `-1`.

As for my own observation: this mostly affects signs, posters, foliage etc. Especially foliage are noticeable changes environment: it became thinner, light can path through, better shadows, ... -- which creates more alive scene (not a solid green piece of ... tree, and not a dark/light zone around).

This is for minimal AA/AF, probably maximized AA/AF can produce similar effect, but I have no such powerful hardware to check/play ;)

**Comment by doitsujin** [comment]
> I read something like: for 4k you can set -2

Texture filtering automatically selects the closest mip levels, no matter what your screen resolution is. A mip LOD bias of -2 would mean that in order to fill a 1024x1024 quad, you'd need a 4096x4096 texture, and the result would be of low quality because it can introduce high-frequency noise that mip mapping is designed to eliminate. Not a particularly good idea.

Like everything else, overriding the LOD bias can also quite easily break stuff, it's additional code to maintain, and not terribly useful in general. Not sure if DXVK really needs this.

**Comment by pchome** [comment]
@doitsujin 
> Like everything else, overriding the LOD bias can also quite easily break stuff

Sure. But, in both directions, sometimes. In particular, it fixes the light's glitches in GTA: EFLC (wined3d) for me.

![gta-eflc mip-lod-bias-small](https://user-images.githubusercontent.com/10661854/49344128-3166d300-f67c-11e8-82b8-65a5a686764a.png)

Anyway, that's why I left this patch as is (not as PR). And if you don't like it as DXVK builtin option -- feel free to close this issue.

**Comment by pchome** [comment]
Closing. There is https://gitlab.com/torkel104/libstrangle (or https://github.com/pchome/VkGHL) for this hack.

**Comment by Margen67** [comment]
#3435
