### ISSUE TITLE
Crysis flickering foliage

### ISSUE THREAD

**Issue by Rabcor** [doitsujin/dxvk#696]
While playing Crysis foliage has flickering shaders(?) or something like that, here's [an image example](https://steamuserimages-a.akamaihd.net/ugc/958596576359460133/82D1A51E0ED8556D94FB0DD097DC93A20346B8D8/) of an extreme scenario.

### Software information
Crysis, any settings. The object detail setting is the only setting that has a noticable impact on the amount of flickering foliage, setting it to very high is ideal for maximizing reproduction of the effect, if set to high there will be noticably less of foliage flickering (even if the amount of foliage itself is not reduced)

### System information
- GPU: Nvidia GTX 980-Ti
- Driver: 410.57
- Wine version: Proton 3.16-1 Beta
- DXVK version: 0.81-47

### Apitrace file(s)
- Failed to run apitrace on crysis.exe

**Comment by K0bin** [comment]
The latest Vulkan beta drivers have a fix for that which hasn't made it into the stable branch yet.

**Comment by Rabcor** [comment]
@K0bin I see, since I'm using proprietary drivers I don't think I can test that, but if this is true then I'm sure glad to hear it'll get fixed soon.

**Comment by Tk-Glitch** [comment]
@Rabcor We are talking about proprietary here. Just a different branch. 410.57 doesn't have the fix. 396.54.06 and 396.54.09 (released today) both have it.

**Comment by Rabcor** [comment]
Ah, so it's an nvidia specific issue then?

**Comment by Tk-Glitch** [comment]
Indeed. And since 410 series is behind on the vulkan side, it's only been fixed in the vulkan beta drivers as of yet.

**Comment by Rabcor** [comment]
It seems that I'm going to have to just wait on the driver update; getting the beta drivers installed on manjaro is a lot harder than it should be. The 396.54.09 fail to build from AUR, it looks like it's gonna be a pain in the ass to troubleshoot. I hope it won't be too long before the 410 series catches up...

**Comment by Tk-Glitch** [comment]
@Rabcor You can give my PKGBUILD a try : https://github.com/Tk-Glitch/PKGBUILDS/tree/master/nvidia-dev-all
I just confirmed it to work on Manjaro.

**Comment by Rabcor** [comment]
I have confirmed, the nvidia beta driver solved the issue.
