### ISSUE TITLE
Worlds Adrift loading UI issue. D3D11Device: CheckFeatureSupport: Unknown feature: 10 

### ISSUE THREAD

**Issue by kalkishnu** [doitsujin/dxvk#697]
The game client launches as expected but dose not load any UI item or graphic elements other than the background. The process is running and you can listen to the game background music.
Notice: err:   D3D11Device: CheckFeatureSupport: Unknown feature: 10 

### Software information
[Worlds Adrift](https://steamdb.info/app/322780/)

### System information
- GPU: GTX960
- Driver: nvidia 396.54.9
- Wine version: wine-3.18 ( Staging Esync PBA Dxvk )
- DXVK version: 0.90

### Apitrace file(s)
- Put a link here

### Log files
-[UnityClient@Windows_d3d11.log](https://github.com/doitsujin/dxvk/files/2476004/UnityClient.Windows_d3d11.log)
-[UnityClient@Windows_dxgi.log](https://github.com/doitsujin/dxvk/files/2476005/UnityClient.Windows_dxgi.log)

**Comment by Guy1524** [comment]
That error indicates that the game wants support for D3D 11.2, right now the maximum version of D3D11 DXVK supports is 11.1

**Comment by kalkishnu** [comment]
I guess then we can close this issue. Thx for the clarification sir.
