### ISSUE TITLE
GPU Hang The Witcher 3 (with dxvk 0.90)

### ISSUE THREAD

**Issue by sr-tream** [doitsujin/dxvk#700]
After updating to 0.90, GPU Hang appeared during fights

### Software information
The Witcher 3

### System information
- GPU: AMD RX560
- Driver: RADV (mesa 18.3 (with stream output patches), LLVM 8)
- Wine version: [3.18-tkg](wine-tkg-git)
- DXVK version: 0.90

### Log files
- d3d11.log: https://pastebin.com/AWjzKJCb
- dxgi.log: https://pastebin.com/4z0yDRNe

**Comment by doitsujin** [comment]
In case of GPU hangs, please try to generate a hang report as explained in #252.

**Comment by shmerl** [comment]
Thanks for the reminder, looks like [spirv-tools is still stuck in Debian's new queue](https://ftp-master.debian.org/new/spirv-tools_2018.2-1.html). I'll ping Debian developers about it.

**Comment by sr-tream** [comment]
@shmerl, I use archlinux, not debian

**Comment by shmerl** [comment]
Do you mean the henchmen fight in the save? I fought them all using a silver sword, no hangs. Sapphire Pulse Vega 56.

**Comment by sr-tream** [comment]
@shmerl, need test on GPU with 2GB VRAM. When this problem was before (up to 0.63 it seems), it appears only for users with 2GB VRAM

**Comment by shmerl** [comment]
Ah, OK. I have 8 GB so can't test such scenario.

**Comment by sr-tream** [comment]
@doitsujin I can't forward to enemy and fight them with 0.1 fps in debug mode. Sorry

**Comment by edmondo** [comment]
@sr-tream I also fought all the henchman and no hangs.
My configuration:
RX470 4 GB RAM

**Comment by sr-tream** [comment]
@edmondo, does an RX470 with 2GB VRAM exist?

**Comment by edmondo** [comment]
@sr-tream I don't think so. There were only 4 and 8 GB versions

**Comment by shmerl** [comment]
2GB VRAM sounds very tight for it to begin with.

**Comment by edmondo** [comment]
you could try to reduces the graphics settings and see if it's better

**Comment by doitsujin** [comment]
On cards with 2GB VRAM, some resources may need to be allocated in system memory, which will degrade performance. However, this generally works fine and shouldn't cause hangs (tested this by letting dxvk allocate **everything** in host memory).

**Comment by Jrugia** [comment]
Not AMD here but I have a system with Nvidia GT1030 and ut has 2GB VRam. Will give it a shot later today.

**Comment by doitsujin** [comment]
Can't reproduce when simulating 2GB of VRAM. Even when effectively disabling all VRAM, I don't get any hang, although performance is obviously degraded.

**Comment by Jrugia** [comment]
I play tested the OP's savegame using the GT1030 with a medium/high setting combination at 1280x720 / 30fps lock and haven't encountered any crashes or freezes.

Got to the end of the quest and played for an entire hour, even fast traveled in a bunch of places to force the game to load up on resources. GPU used about 1.3GB VRAM so it was far off from the limit.

Full System Specs:

Intel G4560
8GB 2400MHZ Ram
Debian 9 (with 9.5 updates)
Wine 3.18 built from source using the Lutris git. - ESync enabled / PBA disabled.

**Comment by hakzsam** [comment]
Are you still able to reproduce the hang with latest mesa git? I recently pushed VK_EXT_transform_feedback.

**Comment by doitsujin** [comment]
Closing due to the lack of feedback. Feel free to re-open if the problem persists.
