### ISSUE TITLE
Launching Assassin's Creed Origins on wine

### ISSUE THREAD

**Issue by FloBEAUG** [doitsujin/dxvk#704]
Hello,

Does somebody already launched Assassin's Creed Origins under wine and how ?
In my case, the game does not start at all. Not a single trace... (sorry)

All others AC Games are working pretty well except this one...

Sincerely

Here is my setup : 
### Software information
Assassin's Creed Origins

### System information
- GPU: GTX 970
- Driver: 410.57
- Wine version: 3.18 staging
- DXVK version: 0.90

### Log files
- d3d11.log: Empty
- dxgi.log: Empty

**Comment by doitsujin** [comment]
Not possible due to DRM issues. This game runs fine with DXVK on Windows.
