### ISSUE TITLE
Feature Request: option to show current D3D feature level in DXVK_HUD

### ISSUE THREAD

**Issue by tycho** [doitsujin/dxvk#705]
It would be really nice to have an option for the HUD which shows the current active D3D feature level.

**Comment by Guy1524** [comment]
Why would you want this?

**Comment by doitsujin** [comment]
Why? It's going to say `11_0` in 99.5% of your games and `11_1` in the rest.

And no, displaying it in the HUD is actually not trivial because the HUD technically doesn't even know what D3D11 is.

**Comment by tingvarsson** [comment]
@tycho why skim when you can `grep` :) :)

**Comment by SveSop** [comment]
From what i gather the new "release" nVidia driver (410.66) shows API version between GL or Vulkan... but it does not have the latest stream_output extensions sadly.

Joking aside, its a fair request, and possibly interesting to have. Does it create too much work to be bothered doing? Well.. That is also fair enough to not have it.

"Its too much work, as i would rather spend the time fixing bugs" is a thumbs up for me... just dont make up excuses about "feature creep", or "how easy it is to grep logs" :)

**Comment by doitsujin** [comment]
This has been implemented in 11d2082fd2cc59f4e28ff1b7470a32cc677f25ab.
