### ISSUE TITLE
generating dxvk_hud_font.cpp

### ISSUE THREAD

**Issue by aviau** [doitsujin/dxvk#708]
Hello!

I am currently working on packaging DXVK for Debian and I am not sure that we can include dxvk_hud_font.cpp in Debian since it was generated with software that we don't have and we must build everything from source.

Could we possibly build without hud support?

If not, could this functionality be added?

Cheers,

**Comment by doitsujin** [comment]
You're free to patch it out, but I'm not going to do it. If Debian has a stupid policy in place that prevents you from using a perfectly legal file, then that's your problem, not mine.

**Comment by Thaodan** [comment]
The issue is that debian was reproducible builds and wants source 100% the same if don't change the commit its based on.
There are other distros that do this too.

**Comment by doitsujin** [comment]
@Thaodan in what way does the HUD interfere with reproducible builds?

**Comment by Thaodan** [comment]
I just took a gues because that file is generated at build time and may change.

**Comment by doitsujin** [comment]
No, it's not.

**Comment by Thaodan** [comment]
Than sorry discard my comment. Than it doesn't make sense.

**Comment by aviau** [comment]
> If Debian has a stupid policy in place 

Sorry if this sounds annoying to you. I am doing my best here and I am willing to help.

> what the problem is here

Again, please bear with me. I'll explain my best.

We don't consider dxvk_hud_font.cpp isn't "source code" because it cannot be modified by hand. I have not decided this rule.

Possible solutions could include:
 - excluding it from the source
 - generating dxvk_hud_font.cpp as part of the build process
 - patching dxvk_hud_font.cpp in a way that wouldn't break the program but stiill build.

Could you help me understand how dxvk_hud_font.cpp is obtained from https://evanw.github.io/font-texture-generator/ and https://github.com/adobe-fonts/source-code-pro ?

Sorry if I came off as pointing that somehow DXVK wasn't legal. It has nothing to do with the legality of the project, it has to do with the Debian Free Software guidelines, that ask us to build everything from source and our definition of source code.

**Comment by saboya** [comment]
The last modification on that file was 7 months ago. What makes you think that it's going to change? It's not generated every commit, so your builds will be 100% reproducible.

**Comment by aviau** [comment]
I have never mentionned reproducible builds, I don't know what you mean by that.

**Comment by exolyte** [comment]
The g_hudFontImage array is just the C++ representation of an image generated by https://evanw.github.io/font-texture-generator/, this is not code so I don't think it should fall under software guidelines?

**Comment by aviau** [comment]
> this is not code so I don't think it should fall under software guidelines?

I'd be happy to explain how Debian policies work in another thread, if you want, but maybe we should keep this discussion technical for now. I have been a Debian Developper for years and I have dealt with similar issues dozens of time, my interpretation of our policies is correct.

>  C++ representation of an image

Is this image available in the repository? If not, could it be added?

**Comment by aviau** [comment]
I have got things working.

FWIW, for those interested, that would be the guide:

```
1. Launch debian/missing-source/font-texture-generator/index.html in
   a browser.

2. Select the data format: "C".

3. Save the provided image, and convert it to C:
    $ convert image.png image.h

4. Insert the generated image code in dxvk_hud_font.cpp as
   const uint8_t g_hudFontImage[].

5. Append the text generated by font-texture-generator to
   dxvk_hud_font.cpp, excluding the last constant.

6. Adapt the last constant to the following signature and append it
   to dxvk_hud_font.cpp.tmpl:
    - const HudFont g_hudFont = { int, int, int, int, int, int, g_hudFontGlyphs, g_hudFontImage };
```

**Comment by Thaodan** [comment]
@aviau i said this because you don't fully explained this isn't code for debian. I think about stuff that changes during builtime. Maybe you can commit this to avoid that hassle.

**Comment by lieff** [comment]
@Thaodan But this file can't be changed during builtime.
