### ISSUE TITLE
Civilization 5

### ISSUE THREAD

**Issue by GabrielMajeri** [doitsujin/dxvk#71]
### Software information
Civilization V, on highest graphics settings. The game runs, but after the intro videos the main menu shows a black screen, then the game crashes.

The game requires deferred contexts, which are currently not supported. There are also some errors in the shader compiler.

### System information
- GPU: NVIDIA GTX 960
- Driver: NVIDIA 390.77
- Wine version: N/A (Windows 10 x64)
- DXVK version:  8f134ba

### Log files
- d3d11.log: [CivilizationV_DX11_d3d11.log](https://github.com/doitsujin/dxvk/files/1714379/CivilizationV_DX11_d3d11.log)
- dxgi.log: [CivilizationV_DX11_dxgi.log](https://github.com/doitsujin/dxvk/files/1714380/CivilizationV_DX11_dxgi.log)
- [apitrace](https://drive.google.com/file/d/18wkX6iCpBfJhM_n-ZueSX7n3A7_vGTZN/view?usp=sharing)

**Comment by doitsujin** [comment]
Game requires tessellation and deferred contexts, see #93.

**Comment by doitsujin** [comment]
Please update your driver, 396.24.**02** is required for tessellation to work.

**Comment by ryanmusante** [comment]
Oh, that is nvidia beta release. I have to wait for manjaro to incorporate it.

**Comment by l29ah** [comment]
I observe garbled textures in Civilization V on dxvk-1.0 on an Intel GPU. Do i need any magical incantations for it to work?

**Comment by doitsujin** [comment]
Please bisect if this is a regression, and please try to record an apitrace.

There seem to be a lot of issues with 1.0 on Intel drivers, but not on AMD/Nvidia for some reason.
