### ISSUE TITLE
Problems with DXVK with Unreal Engine 4

### ISSUE THREAD

**Issue by massatt212** [doitsujin/dxvk#710]
[TekkenGame-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/2487897/TekkenGame-Win64-Shipping_d3d11.log)
[TekkenGame-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/2487898/TekkenGame-Win64-Shipping_dxgi.log)
[StreetFighterV_d3d11.log](https://github.com/doitsujin/dxvk/files/2487900/StreetFighterV_d3d11.log)
[StreetFighterV_dxgi.log](https://github.com/doitsujin/dxvk/files/2487901/StreetFighterV_dxgi.log)
[MVCI_d3d11.log](https://github.com/doitsujin/dxvk/files/2487902/MVCI_d3d11.log)
[MVCI_dxgi.log](https://github.com/doitsujin/dxvk/files/2487903/MVCI_dxgi.log)

I normally get 60fps of smooth play on these 3 titles Im on Windows 10 I know u dont like using it but i can only get these games running on them

Marvel Vs Capcom Infinite
https://youtu.be/KKgEWpCCKGA

Tekken 7
https://youtu.be/ZxNn8JKj4KM

Street FIghter V
https://youtu.be/hLRlTYTFWtg

**Comment by lieff** [comment]
Did you try spoof AMD card? UE4 uses nvapi for SLI support, and this library tries to load nvapi dll (which is missing in wine) on every API use and fail every time. This is not UE4 fault, but static part of nvapi.lib .

**Comment by massatt212** [comment]
Ow sorry this is Windows 10
So i know its DXVK prob need some optimization for this title

**Comment by lieff** [comment]
You can still try to spoof AMD card. Because I think SLI NVAPI path can be broken when DX11 not actually executed but translated DX11->Vulkan.

**Comment by massatt212** [comment]
so what you think Wine or DXVK can do to fix this problem
Cause this should be a high priority since its a new Engine

**Comment by lieff** [comment]
Wine makes stubs to nvapi https://github.com/wine-compholio/wine-staging/wiki/NVAPI
DXVK can do nothing about it except spoof AMD card by default.
Here how to do it: https://github.com/ValveSoftware/Proton/issues/37#issuecomment-415833819

**Comment by massatt212** [comment]
so how do i spoof a graphic card on windows 10 to redo my test ?

**Comment by lieff** [comment]
Same way as here https://github.com/ValveSoftware/Proton/issues/37#issuecomment-415833819
Create dxvk config with 2 lines:
```
dxgi.customDeviceId = E366
dxgi.customVendorId = 1002
```
and set DXVK_CONFIG_FILE environment variable pointing to this config.

**Comment by massatt212** [comment]
DXVK_CONFIG_FILE=C:\Steam\steamapps\common\TEKKEN 7\TekkenGame\Binaries\Win64\tekken.conf %command%

Not working or did i make a mistake ?

**Comment by doitsujin** [comment]
I don't think you can set environment variables like that on Windows.

**Comment by lieff** [comment]
Wrong. That line
```
DXVK_CONFIG_FILE="C:\Steam\steamapps\common\TEKKEN 7\TekkenGame\Binaries\Win64\tekken.conf" %command%
```
is for Proton. And do not forgot use quotes for path with spaces.
Just set variable.
Through GUI for whole system/user (you must logoff/login after that) or use .bat/.cmd file.
.bat file should look like this:
```
set DXVK_CONFIG_FILE="C:\Steam\steamapps\common\TEKKEN 7\TekkenGame\Binaries\Win64\tekken.conf"
"C:\Steam\steamapps\common\TEKKEN 7\TekkenGame\Binaries\Win64\tekken.exe"
```

**Comment by massatt212** [comment]
DXVK works on Windows 10 also im comparing benchmarks between dx11 native and dxvk i got it to work only gave me 10fps boost

**Comment by doitsujin** [comment]
> So i believe DXVK still needs some performance tweaking when it comes to EPIC Unreal Engine 4

Well, if you have any suggestions on how exactly to improve performance in UE4 games...

I'm well aware that it performs poorly compared to other engines, but that's down to how the engine design, there's no obvious bottleneck *that could be fixed*.

**Comment by massatt212** [comment]
idk
But unreal Engine 3 works Flawless even the Modded Ver. of 3 used on MKX and Injustice 2
how much of a difference is the modded unreal engine and 4
Maybe the new features of unreal engine 4 not getting alone with dxvk
Cause when Marvel vs capcom infinite just released i could of entred dx9 dx10 and dx12 and it work just bad performance im not a programmer or anything but i dont think i should be able to force unreal engine games to dx9 10 or 12 maybe look at that area

**Comment by doitsujin** [comment]
I've spent hours upon hours trying to figure out why UE4 runs so badly and how to improve it, but so far, the only "solution" i found is to disable occlusion queries because the game constantly waits for those to become ready. But that's obviously not a *good* solution because it'll lead to objects being rendered unnecessarily.

**Comment by massatt212** [comment]
Alright well I known u will figure it out

**Comment by doitsujin** [comment]
There's no sync issue, UE4 just doesn't delay the reading enough.

in DXVK, query results become available later than they do on native D3D11. The reason for that is that I have to wait for `vkCmdResetQueryPool` to finish before waiting on queries, but since that happens in the same command buffer that uses the queries, I have to wait for the entire command buffer to finish.

I put a quick hack together in order to allow forwarding query data to the application before synchronizing with the command buffer fence, and it did improve Hellblade significantly, but that approach can lead to incorrect query results.

**Comment by massatt212** [comment]
cant you call or message some one from epic games for a little help maybe they can tell you how to solve the issue if u havent tried that yet

**Comment by lieff** [comment]
Hmm, I think stuff in one Vulkan queue can have it's own fence, so we do not need to wait entire queue to finish.

**Comment by doitsujin** [comment]
Anyway, since there's no actual *problem* here and Windows is unsupported anyway, I'm going to close this.
