### ISSUE TITLE
Desktop resolution > game resolution degrades performance

### ISSUE THREAD

**Issue by dhewg** [doitsujin/dxvk#713]
On a 4k display, but using a 1080 desktop resolution, Witcher 3 set to 1080p performs just fine. It's the same as on a 1080p display with a desktop of the same resolution:
![desktop1080p-game1080p](https://user-images.githubusercontent.com/605548/47212417-63f09100-d398-11e8-8a21-64222567b085.png)

But when using a 4k desktop resolution the game stutters although it is using a 1080p resolution as before.
![desktop2160p-game1080p](https://user-images.githubusercontent.com/605548/47212415-6357fa80-d398-11e8-84e1-d843a7f579e0.png)

So if the desktop resolution is greater than the game resolution, the performance suffers. While the fps is not affected, the stuttering is pretty bad. As seen in the screenshots, the frame times and the allocated memory change for the worse.

### Software information
Witcher 3

### System information
- GPU: tonga
- Driver: radv
- Wine version: master
- DXVK version: master

**Comment by doitsujin** [comment]
Can't reproduce. What window manager / compositor are you using?

**Comment by dhewg** [comment]
xfce4 with compositing disabled

**Comment by doitsujin** [comment]
Weird then. Which fullscreen mode did you use? Fullscreen or borderless?

In any case, DXVK doesn't even know what a desktop is, this is not a bug on my end.

**Comment by dhewg** [comment]
Fullscreen, because borderless only uses a quarter of the screen estate in this case.

**Comment by dhewg** [comment]
Btw, this is mesa master with the VK_EXT_transform_feedback patchset and [0] on top (fix for baa38c144f6, reverting baa38c144f6 works too).

[0] https://lists.freedesktop.org/archives/mesa-dev/2018-October/207311.html

**Comment by doitsujin** [comment]
I'm running a mesa-git build with transform feedback as well and everything is working fine here. Borderless Window mode should definitely cover the entire screen as well.

**Comment by dhewg** [comment]
Hm, it doesn't for me, just tried again. The issue is probably related?
Since you mentioned it, enabling the xfce4 compositor doesn't fix the issue.

**Comment by dhewg** [comment]
asked around in #dri-devel
> +MrCooper> dhewg: ah, it leaves the root window size at 4K but switches to a smaller video mode? In that case, page flipping cannot be used for the game window
> dhewg> ok, but the game is switching to its configured 1080p resolution, why is the root window resolution relevant?
> dhewg> and if i run `xrandr --output DisplayPort-0 --mode 1920x1080` before launching the game the performance is fine, shouldn't that be the same as the game switching to its res?
> +MrCooper> the latter resizes the root window as well
> +MrCooper> page flipping can only be used if the game window fully covers the root window

**Comment by dhewg** [comment]
And I wondered why Rise of the Tomb Raider doesn't switch the resolution. Instead it scales the game window to the root window. I guess because of this flipping issue.

**Comment by doitsujin** [comment]
Hum, okay. It's still weird that you see these frame time issues whereas it works fine on my end, while we're running very similar hardware configurations, but if that's caused by WSI quirks, that would explain it.

FWIW, Proton has a similar feature that just scales up the rendered image to a full-screen window without changing the resolution, so if you have the Steam version of the game, it might be worth trying that. Unfortunately it is not possible to do this on the DXVK level because it isn't responsible for managing the application window, and messing around with it breaks applications.

**Comment by dhewg** [comment]
Oh, thanks for the proton hint!
> git remote add valve https://github.com/ValveSoftware/wine.git
> git fetch valve
> git checkout valve/proton_3.16 dlls/winex11.drv/
> make install

And the issue is gone, wine now does not switch the resolution anymore, it scales like discribed above.

Just skimmed through the diff, oboi @aeikum
> +BOOL fs_hack_window_is_hacked(HWND hwnd, struct x11drv_win_data *data)

**Comment by aeikum** [comment]
@dhewg Sorry, I don't understand what you're asking here.

**Comment by dhewg** [comment]
Oh, don't mind me, that's just me admiring your choice of function names :P

**Comment by dhewg** [comment]
Proton contains way too many patches and hacks I don't care about.
So I extracted just the relevant patches for what valve calls "fullscreen hack": [fs_hack.patch.gz](https://github.com/doitsujin/dxvk/files/2497953/fs_hack.patch.gz)

That solves this issue.

@aeikum are there any plans to get that upstream in one form or another? I would think quite some 4k display owners would care about this, yet I couldn't even find a bug on winehq (but maybe that's just my bugzilla-foo, or lack thereof)

**Comment by tingvarsson** [comment]
just for reference;  Im one of the few with a 4k monitor and haven't noticed similar issues. HOWEVER, I have a nvidia/gtx 1080 and it is only a handful of games I have gone down in resolution. So could be either of those reasons it hasn't happened to me.

**Comment by dhewg** [comment]
I'm not sure what the fallback to non-page flip entails, but if its copying buffers around that's going to be bandwidth limited.

doitsujin didn't notice the issue too with a 720p game and a 1080p root window. Maybe because he doesn't hit such a limit at those resolutions. Maybe you don't even at 4k. I don't know, but I know I am.

But even if you don't hit it, it sure sounds like an ineffective code path, and looking at the complexity of Valve's patches it sure looks like it's worth avoiding.

**Comment by aeikum** [comment]
> @aeikum are there any plans to get that upstream in one form or another? I would think quite some 4k display owners would care about this, yet I couldn't even find a bug on winehq (but maybe that's just my bugzilla-foo, or lack thereof)

I don't think upstream Wine would be interested in it, however wine-staging might want to have it.

**Comment by John-Gee** [comment]
> > @aeikum are there any plans to get that upstream in one form or another? I would think quite some 4k display owners would care about this, yet I couldn't even find a bug on winehq (but maybe that's just my bugzilla-foo, or lack thereof)
> 
> I don't think upstream Wine would be interested in it, however wine-staging might want to have it.

Please try to get it to either one, it's such a nice feature, especially on TVs like mine that pretty much only handle one resolution nicely...

**Comment by grigi** [comment]
I have a similar issue with Witcher 3 on Intel ANV using a UHD620 (kabylake mobile).
The game is much more prone to stutter when the following is true:
* Scaling from 1280x720 to 1920x1080
* Texture resolution is set to Medium.

When only either is set, I don't get the stuttering.

Which leads me to think it may be a GPU memory pressure issue?

**Comment by phush0** [comment]
I have same problem from 4k to 1920x1080, Ubuntu 18.04.2 with Gnome, Padoka PPA, DXGI log says that image will scale up to 4k. Vega M
