### ISSUE TITLE
Heroes of the Storm: DXVK 0.54 crashes on load after 8/16/2018 Patch

### ISSUE THREAD

**Issue by tacklebox8** [doitsujin/dxvk#714]
This may apply to later versions as well, but have to use 0.54 due to Nvidia Fermi chip (can't use 396 drivers).  0.54 ran perfectly with 64-bit 3.17 wine-staging before HoTS 8/16/2016 patch, now game crashes on load.  Game does run with vanilla 3.17 or 3.18 wine-staging, so it isn't a wine issue.  Getting "DxvkInstance::createInstance: Failed to create Vulkan instance" error, but like I said, the game was running fine before 8/16/2018 patch and I didn't change anything with my system since it was working.  I've tried all of the relevant dxvk.conf fixes with no luck.  Wine log below, any ideas on how to fix would be appreciated.

000b:fixme:winediag:start_process Wine Staging 3.18 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
0025:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
000b:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
002a:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
002a:fixme:shell:SetCurrentProcessExplicitAppUserModelID L"BlizzardEntertainment.HeroesOfTheStorm.HeroesOfTheStorm": stub
002c:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
002c:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
002c:fixme:ntdll:EtwEventRegister ({5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0x530107c, 0x5331030, 0x5331050) stub.
002c:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x532cdf0, 43) stub
002c:fixme:ntdll:EtwEventRegister ({5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0x4d2107c, 0x51d4030, 0x51d4050) stub.
002c:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x510b578, 43) stub
002e:fixme:ver:GetCurrentPackageId (0x57afda0 (nil)): stub
002c:fixme:ntdll:server_ioctl_file Unsupported ioctl 900c0 (device=9 access=0 func=30 method=0)
002c:fixme:process:SetProcessDEPPolicy (1): stub
002c:fixme:hnetcfg:fw_profile_get_FirewallEnabled 0xae650, 0x654e898
002c:fixme:ole:CoInitializeSecurity ((nil),-1,(nil),(nil),0,3,(nil),0,(nil)) - stub!
002c:fixme:wbemprox:client_security_SetBlanket 0x7f33f5dc9240, 0xf1a50, 10, 0, (null), 3, 3, (nil), 0x00000000
002c:fixme:wbemprox:client_security_Release 0x7f33f5dc9240
002c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0035:fixme:mpr:WNetGetUniversalNameW (L"C:\\Program Files (x86)\\Heroes of the Storm\\HeroesData\\data", 0x00000001, 0xd4de20, 0xd4dde0): stub
0036:fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
0036:fixme:winhttp:WinHttpDetectAutoProxyConfigUrl discovery via DHCP not supported
002c:fixme:progress:ProgressWindowProc state 0003 not yet handled
002c:fixme:wevtapi:EvtSubscribe ((nil) (nil) L"System" L"*[System[(EventID=4101)]]" (nil) (nil) 0x140c74440 1) stub
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_win32_surface
info:    VK_KHR_surface
002c:err:vulkan:wine_vk_instance_load_physical_devices Failed to enumerate physical devices, res=-3
002c:err:vulkan:wine_vkCreateInstance Failed to load physical devices, res=-3
err:   DxvkInstance::createInstance: Failed to create Vulkan instance
002c:fixme:shell:SHGetPropertyStoreForWindow (0x2005e 0x142481540 0x654f078) stub!
002c:fixme:shell:SHGetPropertyStoreForWindow (0x2005e 0x142481540 0x654f080) stub!
002a:fixme:ver:GetCurrentPackageId (0x23fd30 (nil)): stub
002c:fixme:msctf:ThreadMgr_ActivateEx Unimplemented flags 0x4
002c:fixme:msctf:ThreadMgrSource_AdviseSink (0x2285470) Unhandled Sink: {ea1ea136-19df-11d7-a6d2-00065b84435c}
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_win32_surface
info:    VK_KHR_surface
002c:err:vulkan:wine_vk_instance_load_physical_devices Failed to enumerate physical devices, res=-3
002c:err:vulkan:wine_vkCreateInstance Failed to load physical devices, res=-3
err:   DxvkInstance::createInstance: Failed to create Vulkan instance
0049:err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
0049:fixme:heap:GetPhysicallyInstalledSystemMemory stub: 0x33f09c
0049:fixme:heap:GetPhysicallyInstalledSystemMemory stub: 0x33f09c
0049:fixme:ntdll:NtQuerySystemInformationEx Relationship filtering not implemented: 0x3
0049:fixme:ntdll:NtQuerySystemInformationEx Relationship filtering not implemented: 0x3

### System information
- GPU: Nvidia Quadro 3000m (Fermi)
- Driver: 390.87
- Wine version: 3.18 staging (64-bit)
- DXVK version:  0.54

### Log files
- d3d11.log: none
- dxgi.log:
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_win32_surface
info:    VK_KHR_surface
err:   DxvkInstance::createInstance: Failed to create Vulkan instance
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_win32_surface
info:    VK_KHR_surface
err:   DxvkInstance::createInstance: Failed to create Vulkan instance

**Comment by ryao** [comment]
Nvidia does not support Vulkan on your GPU. You likely did not have DXVK properly installed when you thought it was working.

**Comment by doitsujin** [comment]
- Your GPU doesn't support Vulkan.
- Even if it did, your driver would be too old.
