### ISSUE TITLE
Kingdoms of Amalur: Reckoning

### ISSUE THREAD

**Issue by liberodark** [doitsujin/dxvk#717]
The Game Run and work great but no have possibility to change resolution.
more here: https://github.com/ValveSoftware/Proton/issues/783

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Kingdoms of Amalur: Reckoning, All in max.

### System information
- GPU: GTX 1060 6 GB
- Driver: Nvidia 410
- Wine version: Proton 3.16-3 Beta
- DXVK version: 0.90

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log:

**Comment by dlshinobi** [comment]
Dude it's DirectX 9 game. So no dxvk!
