### ISSUE TITLE
Quake Champtions Error 103

### ISSUE THREAD

**Issue by ronlaws86** [doitsujin/dxvk#721]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Name of the game, settings used etc.

### System information
- GPU: nVidia GTX 1070
- Driver: 396.54.09
- Wine version: Proton 3.16-3 Beta
- DXVK version: ^

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log: 
----------------------------------------------

QC Still fails to connect with Error Code 103

**Comment by ssv-170379** [comment]
https://www.reddit.com/r/QuakeChampions/comments/9dveag/cant_play_in_linux_since_the_last_update/
saved the day for me. (btw, there's a typo in solution for Ubuntu, doubled '/x86_64-linux-gnu')

**Comment by tingvarsson** [comment]
Why report this on dxvk?! Did you even read the issue template?

**Comment by doitsujin** [comment]
Becausse a ***GRAPHICS*** library is totally responsible for your ***NETWORK*** issue.... !$&%

**Comment by ronlaws86** [comment]
My bad, i had the Proton thread open on another tab!

**Comment by doitsujin** [comment]
There's already a report for this game on the Proton bug tracker: https://github.com/ValveSoftware/Proton/issues/225

**Comment by ronlaws86** [comment]
> There's already a report for this game on the Proton bug tracker: [ValveSoftware/Proton#225](https://github.com/ValveSoftware/Proton/issues/225)

It's an issue that affects multiple games (After sipping coffee and reading, again sorry for writing in the wrong place!) Proton is packaging a depreciated version of TLS with wine, which updated distros no longer have. A symlink to the new version using the path of version 26 fixes it, but this ignores the core issue that they really need to fix moving forward.
