### ISSUE TITLE
Subnautica, doesn't render player and lifepod, seamoth, cyclops and exosuit

### ISSUE THREAD

**Issue by Maccraft123** [doitsujin/dxvk#723]
![przechwycenie obrazu ekranu_2018-10-21_17-48-30](https://user-images.githubusercontent.com/25985122/47269388-31dc5c00-d55d-11e8-9829-081f8bb82b4e.png)

### Software information
Subnautica 1.0
Arch Linux

### System information
- GPU: AMD RX460
- Driver: Open Source
- Wine version: 3.18
- DXVK version: 0.90

### Apitrace file(s)
- crashed

### Log files
- d3d11.log: https://pastebin.com/g4YQ3ZPv
- dxgi.log: https://pastebin.com/2zDJvzE6
- wine output: https://pastebin.com/3eCyc8h8

**Comment by Maccraft123** [comment]
So, I have to compile mesa and wine?

**Comment by Kerrung** [comment]
@Maccraft123 
https://aur.archlinux.org/packages/mesa-transform-feedback-git

**Comment by Maccraft123** [comment]
Installing that mesa, and wine-tkg-git would fix it?

**Comment by Kerrung** [comment]
>Installing that mesa, and wine-tkg-git would fix it?

yes, installing [that mesa,](https://aur.archlinux.org/packages/mesa-transform-feedback-git) and wine-tkg-git would fix it

**Comment by Maccraft123** [comment]
Ok, compiling wine, then mesa

**Comment by Maccraft123** [comment]
And when these patches will be mainlined?

**Comment by doitsujin** [comment]
They will be mainlined once they are ready to get mainlined.
Anyway, closing since this issue is technically already fixed in DXVK.
