### ISSUE TITLE
Livelock missing textures

### ISSUE THREAD

**Issue by Lightjohn** [doitsujin/dxvk#727]
When launching the game all characters textures are missing.
Game can load and play fine but no heroes or enemies.
 
### Software information
Livelock
Ultra 
2560x1440

### System information
- GPU: AMD RX480
- Driver: 18.0.5
- Wine version: Proton 3-16.3-beta
- DXVK version: 0.90

### Apitrace file(s)
- Will try do that

### Log files
[Livelock_d3d11.log](https://github.com/doitsujin/dxvk/files/2502489/Livelock_d3d11.log)
[Livelock_dxgi.log](https://github.com/doitsujin/dxvk/files/2502490/Livelock_dxgi.log)

**Comment by K0bin** [comment]
> err:   D3D11: CreateGeometryShaderWithStreamOutput:
  Transform feedback not supoorted by device

Your driver does not support the transform feedback extension yet. You need to either wait for an update or compile it yourself. See #695 for more information.

**Comment by Lightjohn** [comment]
Ok thank you.

**Comment by doitsujin** [comment]
As mentioned, the game requires Stream Output and therefore requires a custom Mesa build for now.

In general, your graphics driver is extremely outdated, you should be using Mesa 18.2 and LLVM 7 in order to avoid unnecessary bugs.
