### ISSUE TITLE
Thronebreaker: The Witcher Tales - Black Screen

### ISSUE THREAD

**Issue by mozo78** [doitsujin/dxvk#728]
The game starts and loads without problems. After the intro movie it sticks with black screen.

### Software information
Thronebreaker: The Witcher Tales

### System information
- GPU: GTX 1080Ti
- Driver: 396.54.09
- Wine version: 3.18
- DXVK version: 0.90

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
https://pastebin.com/E98Bgk1z
- dxgi.log: 
https://pastebin.com/5nncK5Q4

**Comment by doitsujin** [comment]
Game runs fine on Windows with DXVK (except for missing transform feedback support) but doesn't show the intro video on my wine setup. This is not a DXVK bug.

**Comment by doitsujin** [comment]
Just confirms what I'm seeing here, the game doesn't even try to render anything when running on wine. But as mentioned, this is not my bug.

What did you do to make it play back the first intro movie by the way? I'm getting a black screen right after the initial loading screen.

**Comment by mozo78** [comment]
I installed the needed Windows Media Foundation files as it's stated in the Shadows: Awakening thread and installed DirectX 9. Nothing more.

**Comment by Kron4ek** [comment]
> I'm getting a black screen right after the initial loading screen.

Yes, i have the same problem. But there is a way to get in to main menu, just rename videos directory in game directory. 

Anyway, mouse and keyboard doesn't work in main menu and there is now way to start the new game.

**Comment by doitsujin** [comment]
Meh. Current Unity engine seems to do everything in its power to make life hard for us...

**Comment by doitsujin** [comment]
Anyway, closing since this is not my bug. Please file a wine bug report.

**Comment by doitsujin** [comment]
Small update: The input issue is actually **caused** by the video workaround.

**Comment by Dav1dde** [comment]
@doitsujin did you figure out how to get the video to play?

**Comment by doitsujin** [comment]
Someone on the GoL forums got it to work by using the native Media Foundation DLLs from Windows 7. It does not work with the Windows 10 DLLs.

**Comment by Dav1dde** [comment]
This seems to work, checking the unity logs I get a new error:

```
Context: CreateObjectFromByteStream
Error details: The byte stream type of the given URL is unsupported.
```

For reference on what is needed to do: https://github.com/ValveSoftware/Proton/issues/1102 - The error is also listed there with what to do. Unfortunately my windows 7 is missing some media packages I think and the Windows 10 does not work (`wmf.reg` export).

So this seems to be the way to go.

**Comment by mozo78** [comment]
Hmm I can't get the videos to play with Media Foundation DLLs...

**Comment by mozo78** [comment]
@Dav1dde, can you share to us your prefix without the game of course?

**Comment by Dav1dde** [comment]
@mozo78 not sure how I'd share it, the whole prefix (without game) is 700mb, Github allows 10mb max. Is there anything specific you need?

**Comment by mozo78** [comment]
The whole prefix actually :D You can archive it (xz or 7z will reduce the size dramatically) and upload it to one of hundreds hosting sites like mega, pcloud, etc. :) Thank you in advance :)

**Comment by mozo78** [comment]
@Dav1dde I managed to run the game so don't worry for the prefix. Thank you :)

**Comment by Dav1dde** [comment]
@mozo78 was about to upload it, can you maybe provide me the steps and necessary files?

**Comment by mozo78** [comment]
Actually it ran once and on the second start now I'm stuck with the black screen issue. I thouhgt that you managed to run the game?

**Comment by Dav1dde** [comment]
Nope, the error turned into:

```
Context: CreateObjectFromByteStream
Error details: The byte stream type of the given URL is unsupported.
```

After getting the necessary DLLs, see the linked Proton issue how to fix it, it should be the exact same issue.

**Comment by mozo78** [comment]
I haven't this issue but the black screen when the movie starts at the beginning. I found the responsible file. It's tb_intro_logo_en_us but this doesn't help much...

**Comment by mozo78** [comment]
I prepared wine prefix for those who want:
https://my.pcloud.com/publink/show?code=XZCHQM7ZPX2IgLPPXPVG3rIHPj2rzhGJglU7
Just extract the archive and put the preinstalled game in /prefix/drive_c/game/Thronebreaker/. 

Do NOT delete the AppData folder. In the the start script there is a command which puts it on the right place in order the game to run properly.

Start the game from the "start" script. Use "desktop" for shortcut on the desktop. If you want to use the FPS feature of DXVK, use the files "fps" and "desktop-fps".

The prefix is tested with the GOG version of the game. Using NVIDIA 396.54.09 is mandatory due to Stream Output requirements of the game. For AMD use mesa-git.

**Comment by Dav1dde** [comment]
@mozo78 that's awesome, can you give the steps you used in order to make it work / create the prefix? I want to know what else I needed to do or what I did wrong. Thanks!

**Comment by mozo78** [comment]
Just use my prefix and don't bother. I'll must write a novel to explain. If you are curious, examine the start script. Everything is there :)

**Comment by ahmed-elsayed2017** [comment]
I found a project at Github that might provide a lot of help for Wine developers

https://github.com/secondstory/ofxWMFVideoPlayer

As they described it, it is: "Video player for openFrameworks using Windows Media Foundation API and hardware acceleration capabilities"

All the technical description of this project can be found in this link:

https://github.com/secondstory/ofxWMFVideoPlayer/blob/master/TechnicalDescription.md

**Comment by mozo78** [comment]
Write to them. DXVK has nothing to do with WMF :)

**Comment by ahmed-elsayed2017** [comment]
> I prepared wine prefix for those who want:
> https://my.pcloud.com/publink/show?code=XZCHQM7ZPX2IgLPPXPVG3rIHPj2rzhGJglU7
> Just extract the archive and put the preinstalled game in /prefix/drive_c/game/Thronebreaker/.
> 
> Do NOT delete the AppData folder and the other files in that directory. Just put the game among them.
> 
> Start the game from the "start" script. Use "desktop" for shortcut on the desktop. If you want to use the FPS feature of DXVK, use the files "fps" and "desktop-fps".
> 
> The prefix is tested with the GOG version of the game and it work perfect. Using NVIDIA 396.54.09 is mandatory due to Stream Output requirements of the game. For AMD use mesa-git.

It works so good with the game, but how can I adjust it for other games? And does this wine has Esync?

**Comment by mozo78** [comment]
Yes but you always can replace it with newer version.
To adjust it for other games you just have to change the paths in the start script to the installer or the game, and to place the dxvk dlls in the new games folder.

**Comment by ahmed-elsayed2017** [comment]
> Yes but you always can replace it with newer version. It must be x64.
> To adjust it for other games you just have to change the paths in the start script to the installer or the game, and to place the dxvk dlls in the new games folder.

Oh! I found also a script that copy the save game to the the game directory. Thanks for your help.

**Comment by ahmed-elsayed2017** [comment]
> Yes but you always can replace it with newer version. It must be x64.
> To adjust it for other games you just have to change the paths in the start script to the installer or the game, and to place the dxvk dlls in the new games folder.

Replacing DX11.dll, and DXGI.dll with a newer version, and replacing Wine with a newer version makes the game go back to the black screen, so I will keep the prefix as it is.

**Comment by ahmed-elsayed2017** [comment]
The script is not working any more for Thronebreaker.

```
Using  override for following DLLs: winegstreamer
Executing winetricks_early_wine regedit C:\windows\Temp\_disabled\override-dll.reg
./start: line 163: : command not found
./start: line 163: : command not found
regsvr32: Failed to load DLL 'msmpeg2adec.dll'
./start: line 184: : command not found
regsvr32: Failed to load DLL 'msmpeg2vdec.dll'
./start: line 184: : command not found
./start: line 190: : command not found
```

**Comment by mozo78** [comment]
These errors are irrelevant and they was always there.

**Comment by ahmed-elsayed2017** [comment]
> These errors are irrelevant and they was always there.

The videos don't work.

**Comment by mozo78** [comment]
Did you try it with RE2 instructions?

**Comment by mozo78** [comment]
Try with [url=https://downloader.disk.yandex.ru/disk/af9a26a1974efa93cd9105659c528f22ed7b46b1cfde48184b1de46bab3b3fef/5c5ac79a/0g9gBqaPpF-viKrINKcA05tFHfcHR1vWgbpqNMCSJiuotOuD2dO9gxVKcWhx3ptWmdysYmyi5lnOzzS1tIjDiA%3D%3D?uid=0&filename=wine-4.1-amd64-nomultilib.tar.xz&disposition=attachment&hash=sKYM8/jwt8P5CrOxCGucy5h1TyMlaE8uTltXVsLMr9g%3D%3A/wine_builds/amd64-nomultilib/wine-4.1-amd64-nomultilib.tar.xz&limit=0&content_type=application%2Fx-xz&fsize=23328544&hid=ae905b18572651d4fb781289ea6caf32&media_type=unknown&tknv=v2]this[/url] Wine version.

**Comment by ahmed-elsayed2017** [comment]
> Try with this Wine version:
> https://tinyurl.com/y8udmcue

It is working again. Thanks.

**Comment by mozo78** [comment]
You are welcome :)

**Comment by ahmed-elsayed2017** [comment]
It did the same thing again. I will just delete all the videos.

**Comment by mozo78** [comment]
Oh, just reload until it starts. This game behaves like that and is known problem :)

**Comment by ahmed-elsayed2017** [comment]
**3 reasons for me to not playing this game:**

1- Using alt + tab makes the game freeze.
2- Xbox 360 has issues with some Unity games (this game is one of them).
3- Videos are not working.

I will try Gwent. Is it playable on Linux?

**Comment by mozo78** [comment]
I don't know. For the Alt+Tab problem use a virtual desktop. Issue the following command in the root folder where is the start script:
./winetools -cfg

**Comment by ahmed-elsayed2017** [comment]
> I don't know. For the Alt+Tab problem use a virtual desktop. Issue the following command in the root folder where is the start script:
> ./winetools -cfg

Deleting Thronebreaker.dxvk-cache from the game directory helps with the black screen at the beginning.

Virtual desktop works well with  alt + tab problem.

I used the workaround inside the prefix to be permanent in my main prefix. Importing registry keys fails but I did it manually using regedit.

I will try using Joytokey to get over joystick problems with Unity games.

**Comment by ahmed-elsayed2017** [comment]
> I don't know. For the Alt+Tab problem use a virtual desktop. Issue the following command in the root folder where is the start script:
> ./winetools -cfg
Virtual desktop doesn't help, the games still freezes when use alt+tab.

Deleting Thronebreaker.dxvk-cache from the game directory helps with the black screen at the beginning.

I used the workaround inside your prefix to be permanent in my main prefix. Importing registry keys fails but I did it manually using regedit.

**Comment by mozo78** [comment]
Can't the cash be stopped with `dxvk.useStateCache = True`?

**Comment by ahmed-elsayed2017** [comment]
> Can't the cash be stopped with `dxvk.useStateCache = False`?

When it is first introduced `dxvk.useStateCache = True` was the way to turn it on, but I don't know if it can be used to turn it off. I don't need to turn it off completely, one cache delete did the trick for me.

My main problem is Xbox 360 behave strangely with some unity games, so I can't play this games with a controller.

**Comment by DocKDE** [comment]
@mozo78 @ahmed-elsayed2017 
I just bought the game and realized it won't run out of the box. Now I'm looking for ways to make it run. You apparently made it work and shared your prefixes but the links don't exist anymore. Would it be possible to share them again? I'd really like to run this game without the workaround of deleting the campaign video folder.

**Comment by mozo78** [comment]
I'll have to install mfplat. Google for z0z0z0. You can do it for seconds :)

**Comment by DocKDE** [comment]
If you're talking about the mf-install script, I tried doing that right after the installation but it didn't help with the blackscreen. By the way I used the Lutris script for the GOG version. I think it install mfplat by itself.

**Comment by mozo78** [comment]
Here you are:
https://my.pcloud.com/publink/show?code=XZwa7FkZ2ewOwzxd7smzKFi5K64vDp9SUNT7

**Comment by DocKDE** [comment]
Thanks! Sorry if the questions seems stupid but what exactly should I do with this? I thought I'd need to move my game folder into the prefix' folder "drive_c/game" and then use the "start" script but that didn't work right. Anything else I need to do here?

**Comment by mozo78** [comment]
Extract the prefix again and put the preinstalled GOG game in /drive_c/game/Thronebraker. DO NOT delete AppData, dxvk-on, d3d11.dll, and dxgi.dll. Then start from the start script, wait for Wine to configure itself and that's it.

**Comment by DocKDE** [comment]
Do you mean the one the lutris installer script produces or just download the files from GOG and install them with wine?

**Comment by mozo78** [comment]
Lutris has nothing to do here. Just get the installed game files from Windows or install it via Wine. GOG installers are working fine with Wine for a long time ago. After the installation get the game files and put them in /drive_c/game/Thronebraker.

**Comment by DocKDE** [comment]
Thank you for your help. Sadly the start script threw an error and I still get the black screen problem when trying to play the game :-/

**Comment by mozo78** [comment]
Wthat error?
Here's a video of mine with the same script:
https://www.youtube.com/watch?v=5t02EfSRseE

Yes, some time the game hangs on loading screen but it's pretty playable.

**Comment by DocKDE** [comment]
Okay, I fixed it myself. The "ulimit -n" command in the beginning exceeded a hard limit and I suppose this broke the script. I set it to another value and it worked. Thanks again! I was beginning to think I'd be doomed to play the thing without video support :)

**Comment by mozo78** [comment]
You'll have to rise ulimit in order to use ESync. It's easy:
https://github.com/zfigura/wine/blob/esync/README.esync

**Comment by pardulas** [comment]
> ### Instructions for some games requires MF:
> 
> _(This workaround works with Resident Evil 7, and Resident Evil 2 Remake, but I am **not sure** if it will work with this game or any game else that requires MF)_
> 
> 1- download this compressed file [python-installcab-master.zip](https://github.com/doitsujin/dxvk/files/2823068/python-installcab-master.zip)
> 
> 2- Extract it and open the terminal and write the following commands:
> 
> 3- `cd ~/Downloads/python-installcab-master/ ` 4- `winetrick mf` and wait for it to finish.
> 
> 5- `export WINEPREFIX`=**/The/Location/Of/The/Game/Prefix** (you need to change the bold text to the actual location of wine prefix of the game)
> 
> 6- `./install-mf-64.sh` to start the script.
> 
> 7- Finally, you need to copy **mfplat.dll** version `12.0.7601.23471` (Windows7 64bit) to the game folder.
> 
> You can search for the file with: **mfplat.dll version 12.0.7601.23471 windows 7 64 bit** or copy the file from your Windows 7 SP1 operating system (_I can't upload the file because it is illegal_).
> 
> If you use **Arch**, or **Manjaro**, _skip step number 6_ and write these scripts instead:
> 
> `python2 installcab.py ~/.cache/winetricks/win7sp1/windows6.1-KB976932-X64.exe mediafoundation` `python2 installcab.py ~/.cache/winetricks/win7sp1/windows6.1-KB976932-X64.exe _mf` `python2 installcab.py ~/.cache/winetricks/win7sp1/windows6.1-KB976932-X64.exe mfreadwrite` `python2 installcab.py ~/.cache/winetricks/win7sp1/windows6.1-KB976932-X64.exe wmadmod` `python2 installcab.py ~/.cache/winetricks/win7sp1/windows6.1-KB976932-X64.exe wmvdecod`
> 
> If the game kept crashing after following these instructions, you probably did something wrong!

Running the Arch scripts give this output:
```
mediafoundation
Traceback (most recent call last):
  File "/mnt/WinData/Games/RE2R/linux-fix/python-installcab-master/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/mnt/WinData/Games/RE2R/linux-fix/python-installcab-master/installcab.py", line 233, in process_files
    outdata, arch = load_manifest(file_path)
  File "/mnt/WinData/Games/RE2R/linux-fix/python-installcab-master/installcab.py", line 199, in load_manifest
    reg_data, arch = process_manifest(file_path)
  File "/mnt/WinData/Games/RE2R/linux-fix/python-installcab-master/installcab.py", line 175, in process_manifest
    for registry_key in registry_keys[0].getchildren():
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```
I tried using python, python3 and pyhton 3.9 as program but they give all the same error.
Any way to fix the issue? (I'm not a programmer and I don't know python)

**Comment by tehmasterer** [comment]
For anyone who has this issue in 2025 and beyond, you can simply use GE-Proton, which has Media Foundation baked in. No need for a custom prefix or sketchy scripts. 

I ran the GOG version of the game, through Heroic Games Launcher, using GE-Proton9-27 and GE-Proton10-4 on two different computers and completed the game without issue.

**Comment by DocKDE** [comment]
Cool, thanks for the heads-up!
