### ISSUE TITLE
World of Tanks - Less than half native performance

### ISSUE THREAD

**Issue by acedogblast** [doitsujin/dxvk#730]
When playing World of Tanks the frame rate when using DXVK is less than half (about 40%) that of using native dx11. This is observed in both the game and the EnCore Demo/Benchmark. I have tested with different graphic settings and all have the same ~40% performance of native. Reading other issue posts claim good performance so I tested with 0.53 but the performance was worse than 0.90 and had rendering issues. 

Other games made by Wargaming like World of Warships could also have the same low performance. 
Is it possible for DXVK to have additional optimizations for these programs?

I have provided apitraces for both minimum and ultra settings. The ultra one has very low frame rate and has many rendering issues. The minimum has better frame rate and less rendering issues so try this one first.

You can also download the EnCore Demo here: [wotencore.net](http://dl-wot-gc.wargaming.net/encore/files/WoTEnCore_internet_install.exe)

Thanks for your work on this project!

### Software information
World of Tanks, World of Tanks EnCore Demo/Benchmark
Note: Both programs are only 32bit.
### System information
- GPU: GTX 1080
- Driver: 399.41.0
- Wine version: Tested using Windows 10
- DXVK version: 0.90 and 0.53

### Apitrace file(s)
- [EnCore Benchmark Minimum](https://drive.google.com/file/d/1E2YOHLEZ5hUVpeQrpr6h_S_61tRigI9x/view?usp=sharing)
- [EnCore Benchmark Ultra](https://drive.google.com/file/d/1FUD4XhBLFW38Q4S3G6Uu_6_8ye3Zgh_R/view?usp=sharing)
### Log files
- d3d11.log: 
[WorldOfTanksEnCore_d3d11.log](https://github.com/doitsujin/dxvk/files/2512508/WorldOfTanksEnCore_d3d11.log)

- dxgi.log: 
[WorldOfTanksEnCore_dxgi.log](https://github.com/doitsujin/dxvk/files/2512509/WorldOfTanksEnCore_dxgi.log)

**Comment by ah-** [comment]
Is it a UE4 title? If yes, try spoofing an AMD card, see https://github.com/doitsujin/dxvk/wiki/Configuration

Put a dxvk.conf into the same folder where your WorldOfTanksEnCore_d3d11.log is being written to with this content:
```
dxgi.customDeviceId = e366
dxgi.customVendorId = 1002
```

**Comment by acedogblast** [comment]
No. This games uses the Big World game engine.

**Comment by doitsujin** [comment]
Can you test this on Linux? I frankly don't care about Windows-specific issues.

**Comment by acedogblast** [comment]
I used the 32bit dlls and I will try do some testing on Linux as well later today.

**Comment by doitsujin** [comment]
Oh right, I'm stupid and copied the 64-bit DLLs over. Need more coffee.

**Comment by doitsujin** [comment]
**Update**: Just ran the benchmark on my Windows 10 install using the latest AMD drivers and I'm getting 12219 points using DXVK (vs 15122 with native D3D11). Not a stellar result, but within the usual range.

**Comment by acedogblast** [comment]
Did a test on my Linux computer (GTX 1060 3GB, 396.54.06, Wine 3.18 staging, Kubtunu 18.10) and i'm getting around 20 fps on maximum settings when viewing a replay. Looking online this GPU on windows should be getting around 50 fps. Maybe this is an Nvidia issue? Can someone else with an nvidia GPU please confirm this?

**Comment by viggy96** [comment]
I've noticed that the game dropped in performance on Linux a while ago. I used to get 70 - 80 fps (even 90 on some maps) on all ultra settings, on my R9 Fury, but now, I can only get about 60 with settings medium-high. I'm not sure what happened. I tried using older wine versions, older DXVK versions, but to no effect. There might have been something that changed in the RADV kernel driver that decreased performance, but that's just a theory.

**Comment by vladsol** [comment]
Same (?) problem
GeForce GTX 1060 6GB
Driver: 415.25.0
Vulkan: 1.1.84
Memory size detected correctly.

wine-4.0-rc5 (Staging) (but tried 3.xx wine versions too)
DXVK 0.94

Unfortunately, can't get FPS > 50 and GPU Memory usage < 1.5GB

**Comment by Kreyren** [comment]
@acedogblast Can you share info in https://bugs.winehq.org/show_bug.cgi?id=46378 (WarGaming launcher crashes) if you are not affected by it? 

Would help me a lot..

**Comment by acedogblast** [comment]
I didn't have that issue because when doing the test I just copied the game files and ran the game directly with the replay instead of using the launcher. Though now you said it. I do have issues getting WoT to run.

**Comment by Kreyren** [comment]
@acedogblast I wasn't able to figure out what is causing the issues i will focus on it once i solve the pull reguest to phoenicis, any relevant info is welcomed, just sent it on winebug instead of DXVK issue tracker.

**Comment by viggy96** [comment]
Hey, everyone, I just tried something today which bumped my performance waaay up. In the World of Tanks graphics settings, you can set which display the game runs on. By default with Wine, its set to 'Wine Display'. Even though I only have a single monitor, I also had a second option of 'DISPLAY1'. I set it to that, and boom, my performance went from 50 - 60 FPS to 80 - 90 FPS, on my R9 Fury. Huge difference. Weird that the game sees two displays though...

**Comment by PotassiumDideuteriumPhosphate** [comment]
There might indeed be something to this - At least in the current version of the game it seems that my graphics card is not being utilized to the max, something seems to be bottlenecked. Interestingly, this did not use to be the case but as the wine, dxvk and game versions keep changing over time it's hard to nail down exactly what caused this to happen.

**Tested setup**
Vega 56
Mesa 18.3.5 and 19.0.1
Wine 4.0.x 
Kernel 5.0.3
LLVM 7.0.1

**Observed behaviour**
When running the HD client, I get consistently low framerates, often dipping down to the low 50-ies. This is regardless of graphical settings: Lowering the settings to their minimal state will have little effect on FPS. 

The same occurs regardless if running in 2560x1080 and in 3440x1440, though at lower resolution the framerate consistency improves a lot and I experience fewer drops. The average framerate does seem to depend little on resolution or graphical setting at all and I've been unable to push it much beyond 70, except in some instances (intro film etc) where it will peak, unsurprisingly to ~700.

**Next steps**
I'll try to play with different DXVK versions to see if there is a regression, as I already tried different Mesa versions.

**Comment by doitsujin** [comment]
@PotassiumDideuteriumPhosphate does your wine build have esync enabled? If not, you'll be CPU-limited in pretty much **every** game that uses some sort of multithreading, this is not a DXVK issue.

**Comment by PotassiumDideuteriumPhosphate** [comment]
Interestingly, I've tried running it with both esync on and off, and while esync does seem to improve the situation, it's a very minor improvement. Quite puzzling. Also my processor seems to be under very little strain, though that might be an issue with poor threading in the game engine, so that might not say much.

**Comment by lieff** [comment]
It can be processor governor issue, have you tried set it manually to performance, or utility like https://github.com/FeralInteractive/gamemode ?

**Comment by PotassiumDideuteriumPhosphate** [comment]
I have indeed set the performance governor to performance manually as well as trying it in its default state. Alas, there is no appreciable difference in performance in the normal use case. On the plus side, I get an extra 100 fps when watching the intro movie! ;)

**Comment by PotassiumDideuteriumPhosphate** [comment]
I tried with older versions of DXVK, and the results were the same: ~25% GPU utilization and framerates that look slimilar (in the 50-70 span) regardless of of I run "High" or "Low" graphical settings. Clearly not a recent regression then.

Probably the issue resides with either amdgpu, llvm or the game itself. Sorry to have bothered you @doitsujin :frowning_face:

**Comment by doitsujin** [comment]
That's weird, I'm on AMD too and haven't noticed any weird performance issues.

**Comment by PotassiumDideuteriumPhosphate** [comment]
Indeed. It's like the GPU just won't clock up correctly, but it's not an issue I've noticed in other games. Just weird.
