### ISSUE TITLE
Civilization VI crash on start

### ISSUE THREAD

**Issue by hartmark** [doitsujin/dxvk#731]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

Crash on start when trying launching Civ6 with help of proton and DXVK

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace

) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Sid Meier's Civilization VI

### System information
- GPU: AMD Radeon RX Vega 64
- Driver: AMDGPU
- Wine version: 3.16
- DXVK version:  v0.90-8-g6558b27

### Log files
https://my.pcloud.com/publink/show?code=kZMkl97ZMpjsG0b2kymPSBtRcDWHBXzD0887

**Comment by doitsujin** [comment]
Can't debug without an apitrace.

**Comment by hartmark** [comment]
Is not the .trace file the apitrace?

That's the file I got in the application folder. Perhaps I'm holding it wrong.

**Comment by doitsujin** [comment]
Ah, missed it because of your weird way of formatting your post. But it's useless since you recorded it with DXVK enabled, it only contains one frame and replaying it doesn't trigger a crash. Please record it on wined3d (if that works) or in Windows.

Also, please post the full wine console output.

**Comment by hartmark** [comment]
Alright, I'll try get better logs when i get home from work.

**Comment by hartmark** [comment]
I think I was able to get logs now without DXVK enabled
https://my.pcloud.com/publink/show?code=kZHxE97ZFgHsCEJM4zQR1CMeN4RzdRoWmH8V

I used the trick with the modified dlls in the game folder.

**Comment by hartmark** [comment]
@doitsujin

**Comment by doitsujin** [comment]
Don't see anything useful in those logs. I need an apitrace that is not recorded with DXVK because that doesn't include whatever triggers the crash, assuming that this is even my bug.

**Comment by hartmark** [comment]
How do I disable dxvk? I tried both "setup_dxvk32 reset" and "setup_dxvk64 reset" but the logs still print out the dxvk version number

**Comment by TheGreatMcPain** [comment]
Try and use winecfg to set dxgi, and d3d11 to built-in.

**Comment by hartmark** [comment]
I were finally able to make it running without DXVK, it seems proton adds this override in the launcher WINEDLLOVERRIDES="xaudio2_7=n,b;dxgi=n;d3d11=n" and removing that I were able to get it to crash.

Are these new logs usable?
https://my.pcloud.com/publink/show?code=kZIfnM7ZacaJblo02D5S6IkgneJcqVIctibk

**Comment by ah-** [comment]
Doesn't Civ VI have a native port?

**Comment by hartmark** [comment]
> Doesn't Civ VI have a native port?

Yeah, but it doesn't support cross-platform play and I have also problems with it getting stuck in the loading screen.

**Comment by Pneumaticat** [comment]
I can reproduce the issue on DXVK v0.93.


-  GPU: AMD RX 580
-  Driver: AMDGPU
-  Wine version: 3.18
-  DXVK version: v0.93


Log (wine) and apitrace without dxvk installed:

[CivilizationVI.exe.zip](https://github.com/doitsujin/dxvk/files/2631385/CivilizationVI.exe.zip)

**Comment by doitsujin** [comment]
@Pneumaticat that apitrace isn't terribly useful because it doesn't really do anything. It also doesn't crash when replaying it with DXVK.

**Comment by MegWATTT** [comment]
I just tested DXVK on Windows for Civ VI and it was fine. No issues so far.
Civ VI never worked on Wine for me, with both Wined3d or DXVK.

**Comment by uniformbuffer** [comment]
Hi,
i'm sorry to bump this thread from a year ago, but i'm interested in the topic and i have some questions. 
Have anyone noticed that the linux version of the game is a wine wrapped window version? (you can find a folder called "wine64steam" where there are window executable)
So the main question is: can the linux shipped wine configuration and prefix applied to a generic wine (or proton) machine? So maybe can be possible to use a configured proton to run the window version of the game, with dxvk, esync and so on.
What do you think? Is it possible?

**Comment by doitsujin** [comment]
seems to work nowadays.
