### ISSUE TITLE
The Vanishing of Ethan Carter Redux

### ISSUE THREAD

**Issue by LeJimster** [doitsujin/dxvk#732]
Game crashes when it reaches about 90% on initial loading bar.  Seems like this title works fine on [nvidia proprietary drivers](https://github.com/ValveSoftware/Proton/issues/1103).  This is an Unreal Engine 4 game.

![vanishingofethancarterredux_dxvk_crash](https://user-images.githubusercontent.com/35663469/47467259-70884580-d7ed-11e8-83ed-260bf3fc93b4.jpg)

### Software information
The Vanishing of Ethan Carter Redux

### System information
- GPU: RX Vega 56
- Driver: Mesa 18.3.0-devel (git-ff281e6204) (with Transform Feedback patches)
- Wine version: Proton 3.16-3
- DXVK version: 0.90-12-ac0f8d6

### Apitrace file(s)
[EthanCarter-Win64-Shipping.trace](https://drive.google.com/file/d/1b4Iv8xHfzI_qdvLgpRxkd2qW2RSkORMs/view?usp=sharing)

### Log files
- d3d11.log:[EthanCarter-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/2512668/EthanCarter-Win64-Shipping_d3d11.log)
- dxgi.log:[EthanCarter-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/2512669/EthanCarter-Win64-Shipping_dxgi.log)

**Comment by doitsujin** [comment]
Does replaying the trace crash for you? It works fine on my end using latest mesa-git and LLVM 8.

**Comment by exolyte** [comment]
I didn't do any extensive testing of the game itself, but the crash at startup went away for me when using a dxvk.conf file in `steamapps/common/The Vanishing of Ethan Carter Redux/EthanCarter/Binaries/Win64` with the option `dxgi.customVendorId = 10DE`

**Comment by LeJimster** [comment]
@doitsujin I created the original trace in Windows10 and I was struggling to get a functioning trace in wine.  I've managed to get something now, although I don't know if it's useful.  Same thing happens on all DXVK versions I've tested including 0.90 release and I'm using latest LLVM.

[wine trace ](https://drive.google.com/open?id=10mbQ1eztqsb56WLf3NCSExe168PrIGjX)

@exolyte yes that option works and the game launches now..

**Comment by doitsujin** [comment]
UE4 being annoying again. Since there is no indication that it crashes inside or because of my D3D code, I added a workaround to spoof an Nvidia card for this game.

Not an ideal solution, but the only one that comes to mind.

**Comment by Skiski** [comment]
I've got an nvidia card (GTX960) and I've got this problem with Proton 3.16-4 and not with 3.7-8.
In the latest proton changelog, it says:

> For Direct3D games (both DXVK and wined3d), Nvidia cards are now reported as if they are actually AMD cards. This prevents games from trying to load the Windows-only nvapi library and crashing or giving very bad performance.

I think it breaks your patch and makes this game unplayable once again.

**Comment by LeJimster** [comment]
@Skiski I don't think 3.16-4 has the latest dxvk, but I was wondering if this was going to be an issue.

**Comment by Skiski** [comment]
I followed the link in the proton thread about the game but didn't see it wasn't on proton github. Maybe it's not exactly a dxvk issue. But at least, I found a way to solve it. I'm not sure if it's something you can solve for everyone. 

Maybe it would be interesting to have some fallback dxvk files that we can easily select (in the command line for launching the game) depending on the needs of the game.

**Comment by exolyte** [comment]
Dxvk game-specific settings can override that proton behavior, so once 422cf71 hits proton, it should just work for everyone.

**Comment by Skiski** [comment]
I tried adding only dxgi.customVendorId = 10DE but it did not worked. I needed also the DeviceId for it to work. I don't know if it's because I've got an nvidia card. And I don't know if the piece of code you've shown is only used in case of an AMD card.
