### ISSUE TITLE
DxvkShaderKey is incorrect when stream-out is used

### ISSUE THREAD

**Issue by AnzhongHuang** [doitsujin/dxvk#733]
There is a scenario when create two GS shaders with the same dxasm code, but with different DxbcXfbInfo.  The two GS should be considered as different shader, because they will generate two different spirv or hardware shaders.
But now in D3D11ShaderModuleSet::GetShaderModule() method, when creating the second shader, it just return the cache of the first one.  I think the DxbcXfbInfo should be a part of the ShaderKey.

**Comment by AnzhongHuang** [comment]
Yes, it's happened on an internal d3d11 test case, it's used to test corner cases I guess. The two shaders use the different SoEntries. I've work-round it on local.
`      size_t cacheSize = BytecodeLength;
      if ((pDxbcModuleInfo != nullptr) && (pDxbcModuleInfo->xfb != nullptr))
      {
          cacheSize += sizeof(DxbcXfbInfo);
      }
      std::vector<char> cachedata(cacheSize);

      memcpy(&cachedata[0], pShaderBytecode, BytecodeLength);
      if ((pDxbcModuleInfo != nullptr) && (pDxbcModuleInfo->xfb != nullptr))
      {
          memcpy(&cachedata[BytecodeLength], pDxbcModuleInfo->xfb, sizeof(DxbcXfbInfo));
      }

    // Compute the shader's unique key so that we can perform a lookup
    DxvkShaderKey key(GetShaderStage(ProgramType), cachedata.data(), cachedata.size());`

**Comment by doitsujin** [comment]
Should be fixed now.

**Comment by AnzhongHuang** [comment]
It works, thanks.
