### ISSUE TITLE
call of juarez (DX10) (3020)

### ISSUE THREAD

**Issue by matou68** [doitsujin/dxvk#734]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
call of juarez (DX10) (3020) start game in DX10 mode , start DX10 benchmark

### System information
- GPU:nvidia GTX 750 ti
- Driver:396.54.09
- Wine version: Proton 3.16-3 beta
- DXVK version: 0.90

### Apitrace file(s)
 https://my.pcloud.com/publink/show?code=kZdT697Z1rJt3nwu2678fzNq4AxQn48kdo6k

### Log files
- d3d11.log:
- dxgi.log:

**Comment by K0bin** [comment]
So... whats the problem?

**Comment by doitsujin** [comment]
Looking at the log file hidden behind the link, the game needs native d3dcompiler DLLs. Please run `winetricks d3dcompiler_43`.

**Comment by Leopard1907** [comment]
Calm down babe. You need `d3dcompiler_43`
