### ISSUE TITLE
Shadow artifacts in World of Warcraft

### ISSUE THREAD

**Issue by lavadrop** [doitsujin/dxvk#737]
I tried searching for it but due to me not being a native English speaker I think I hit a roadblock trying to convey the issue to a search engine.

I've seen this issue ever since my first Linux install this year on my new gaming build. I originally had an Nvidia GTX 1060 with proprietary drivers. Then exchanged to an AMD RX 580 and the issue remained. However, after hopping to Kubuntu from vanilla Ubuntu I decided to do a fresh install due to weird crashes. I installed a fresh Kubuntu 18.04 and the issue was gone! Then I again clean installed 18.10 and the issue is back.

The issue:

The High shadows setting (High resolution environmental shadows, high resolution dynamic shadows near the player) causes very large pixels or squares to be drawn around the edges of every shadow and also to flicker as you move. The lower Shadow quality settings don't have the same issue and it only happens to shadows far from the player. It used to be that I had this glitch happen on every shadow at every distance before reinstalling Kubuntu. I'm enclosing a screenshot of the glitch.

I'm running WoW though Lutris, with the Experimental All-in-One version script that uses DXVK 0.81 and esync wine-staging pba 3.16

### Software information
I'm running WoW though Lutris, with the Experimental All-in-One version script that uses DXVK 0.81 and esync wine-staging pba 3.16. In-game settings are (Recommended) level 7

### System information
- GPU: RX 580 8Gb
- Driver: Kernel 4.18.0-10 / Mesa 18.2.2 / Vulkan 1.1.82
- Wine version: staging pba 3.16
- DXVK version: 0.81
![imageedit_1_3059224367](https://user-images.githubusercontent.com/6760790/47550285-684f0980-d8c4-11e8-8a49-335fddce1604.jpg)

**Comment by Guy1524** [comment]
Is this DXVK specific, does this occur w/ wined3d?

**Comment by doitsujin** [comment]
Does this go away when you set the environment variable `RADV_DEBUG=nohiz`?

I've seen this before in Crysis and other games, it's a driver bug. Might also be worth testing whether this has already been fixed in mesa-git.

**Comment by gonX** [comment]
I'm also having this issue and can confirm setting `RADV_DEBUG=nohiz` fixes this.

**Comment by doitsujin** [comment]
In that case, please test if mesa-git fixed the problem, and if not, file a Mesa bug. The best way to help would be to create a Renderdoc capture that shows the bug.

Unfortunately I haven't succeeded in setting up WoW myself, and it appears that recording apitraces for this game is impossible as well so I can't really debug this.

**Comment by lavadrop** [comment]
Yeah, that works, thanks. I'll look into opening a bug report at the freedesktop bug tracker.

**Comment by edmondo** [comment]
@lavadrop 
> BTW, what does hiz stand for?

Hierarchical Z

**Comment by doitsujin** [comment]
Significantly lower performance or much higher GPU load are expected side effects when setting the `nohiz` option.

**Comment by lavadrop** [comment]
But frame rate is the same, however input lag is unbearable. It takes 5 or 6 full scrolls across my mouse pad to move the cursor from one end of the screen to the other.

**Comment by lavadrop** [comment]
Mesa-git fixed the issue. Thanks!

**Comment by hakzsam** [comment]
Do you know what commit fixed the problem?

**Comment by lavadrop** [comment]
No, I don't track the changes
