### ISSUE TITLE
Graphics distortion in Evil within 1 if reflections enabled

### ISSUE THREAD

**Issue by nickfaces** [doitsujin/dxvk#739]
### Software information
Evil within 1
Reflections ON

### System information
- GPU: RX 580 8Gb
- Driver: mesa-git + llvm-svn
- Wine version: wine-staging 3.19-git
- DXVK version: 0.90

### Apitrace file(s)
unfortunately when I try to do this, the game crashes
### Log files
[EvilWithin_d3d11.log](https://github.com/doitsujin/dxvk/files/2522705/EvilWithin_d3d11.log)
[EvilWithin_dxgi.log](https://github.com/doitsujin/dxvk/files/2522707/EvilWithin_dxgi.log)

RADV bug maybe?

![2018-10-28 15-44-40](https://user-images.githubusercontent.com/3217851/47615052-b97d1a00-dacb-11e8-8df4-9c18c9ea26ca.png)
![2018-10-28 15-43-37](https://user-images.githubusercontent.com/3217851/47615053-b97d1a00-dacb-11e8-93ae-189acd753f67.png)

**Comment by nickfaces** [comment]
OK. 
I trying to make the capture using renderdocmd but I dont know where is saving capture.

**Comment by doitsujin** [comment]
`/tmp/Renderdoc` by default. Same thing when you set `ENABLE_VULKAN_RENDERDOC_CAPTURE=1` instead of using `renderdoccmd`.

**Comment by nickfaces** [comment]
Ok i will try later.
By the way, with the old llvm (about six months ago) the image was rendered in the same way, it was just not possible to find out which setting influenced this, because a couple of seconds after the start the game hung together with the whole system

**Comment by nickfaces** [comment]
I created a bug report in mesa tracker https://bugs.freedesktop.org/show_bug.cgi?id=108594

**Comment by nickfaces** [comment]
something like this problem in NFS Payback with latest mesa-git/llvm-svn
![2018-11-04 19-54-55](https://user-images.githubusercontent.com/3217851/47965760-b1dde800-e06c-11e8-817b-f0d092683bc0.png)

**Comment by doitsujin** [comment]
Since Payback is based on Frostbite, that's probably the same LLVM bug [as here](https://bugs.freedesktop.org/show_bug.cgi?id=108611). Just use LLVM 7 for now.

**Comment by nickfaces** [comment]
Yes,I found this bug too. And several similar ones.  I think you can close this issue as not related to dxvk itself.

**Comment by ahmed-elsayed2017** [comment]
I have the same problem with LLVM 7.
