### ISSUE TITLE
Transform Feedback Not Supported By Device - Log Spam...

### ISSUE THREAD

**Issue by 7oxicshadow** [doitsujin/dxvk#742]
Fedora 28
DXVK 0.90
GeForce GTX 1070:
Driver: 410.73.0
Vulkan: 1.1.82

I have been playing Quake Champions and can confirm that everything is fixed. I can now play on all maps with all characters without crashes :)

I did notice that the d3d11.log file was being spammed by "Transform Feedback Not Supported By Device" errors even though everything is working perfectly? After an hours play the log is over 6MB.

Sure its not really excessive but I suspect there is a bug around the conditions for logging this error to file.

Added bonus: The error contains a typo:

err:   D3D11: CreateGeometryShaderWithStreamOutput:
  Transform feedback not **supoorted** by device

**Comment by Eignar17** [comment]
@7oxicshadow driver  Driver: 410.73.0 not work in  StreamOutput 

work in 396.54.09 driver.

**Comment by Eignar17** [comment]
NVIDIA UPDATE DRIVERS TO StreamOutput!!!!

:(

**Comment by Eignar17** [comment]
talk your problem in to https://github.com/doitsujin/dxvk/issues/695

**Comment by doitsujin** [comment]
The Vulkan beta driver (396.54.09) supports transform feedback.
