### ISSUE TITLE
Q- Does RenderDoc run with DXVK on?

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [doitsujin/dxvk#743]
Does RenderDoc run with DXVK on or should I turn it off?

**Comment by doitsujin** [comment]
Renderdoc generally works with DXVK.

**Comment by ahmed-elsayed2017** [comment]
I couldn't run any DX11 games with DXVK on. It works without DXVK!

**Comment by ahmed-elsayed2017** [comment]
Actually, the problem I had to use RenderDoc for gone with DXVK being off, but the textures were more darker than usual!

Can I open the previous thread with this problem?

https://github.com/doitsujin/dxvk/issues/719

**Comment by ahmed-elsayed2017** [comment]
Oh sorry, I can use the Linux version and capture using Vulkan. My mistake!
