### ISSUE TITLE
HearthStone crashes when DXVK is enabled

### ISSUE THREAD

**Issue by terzag** [doitsujin/dxvk#750]
- GPU: AMD RadeonHD 7770
- Driver: Mesa 18.2.2 / amdgpu
- Wine version: 3.19 Staging
- DXVK version: 0.91

I'm not sure how to do an apitrace as the game is not run directly but started from Battle.net (Blizzard's client). Also not sure where to find the d3d11.log and dxgi.log.

After having installed DXVK in my prefix dedicated to Blizzard games, HearthStone crashes at launch. It works fine if set the five DXVK dlls to builtin instead of native in winecfg. The crash also happens when forcing HS to run in DirectX 9 mode through Battle.net's options.

I've put the output I get from Wine on [Pastebin](https://pastebin.com/8q8eq4Va) if it's of any help, at about the time where HearthStone starts.

**Comment by arzardk** [comment]
How to do an apitrace is described in [DXVK's wiki](https://github.com/doitsujin/dxvk/wiki/Common-issues#apitrace).

**Comment by doitsujin** [comment]
`00d0:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-9`
Make sure you have a Vulkan driver installed (32-bit, if necessary).

**Comment by terzag** [comment]
> Make sure you have a Vulkan driver installed (32-bit, if necessary).

I'm on Ubuntu 18.10. I have libvulkan1 and libvulkan1:i386 installed. The thing is that Vulkan seems to work well with other Wine games (e.g. Gwent) and the issue I have is very specific to HearthStone.

> The DXVK logs are named GameExe_d3d11.log, where GameExe is the exact name of the game's executable without the file extension.

Oh, ok. The d3d11 log is empty. The dxgi log is as follows:

```
info:  Game: Hearthstone.exe
info:  DXVK: v0.91
warn:  OpenVR: Failed to locate module
info:  Required Vulkan extension VK_KHR_get_physical_device_properties2 not supported
info:  Required Vulkan extension VK_KHR_surface not supported
info:  Required Vulkan extension VK_KHR_win32_surface not supported
err:   DxvkInstance: Failed to create instance
```

I know that my GPU isn't officially supported by Vulkan (I force the usage of amdgpu instead of radeonsi) so I guess the log points to missing features at driver level needed by HearthStone? But if that's the case, I'm surprised that it would crash also when forcing D3D9. Is the dxgi dll included with DXVK also used for DX9 games while still requiring some Vulkan features?

**Comment by nickfaces** [comment]
https://github.com/terzag maybe not installed something like vulkan icd loader?

**Comment by terzag** [comment]
> @terzag maybe not installed something like vulkan icd loader?

I'm not sure what this is?

**Comment by nickfaces** [comment]
@terzag I dont know how its named in ubuntu, but in arch its need for vulkan titles.

However in dxvk wiki I see just this

sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386

**Comment by terzag** [comment]
> @terzag I dont know how its named in ubuntu, but in arch its need for vulkan titles.
> 
> However in dxvk wiki I see just this
> 
> sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386

Ok, problem fixed: I was missing the 32 bit package for the driver (only had the one for the Vulkan lib). I guess the other games I tried, like Gwent, were 64 bit so I didn't notice.

Not a bug, then, sorry.
