### ISSUE TITLE
Trouble compiling 0.91.

### ISSUE THREAD

**Issue by GurnBlanston** [doitsujin/dxvk#752]
When trying to compile 0.91, I get this:

The Meson build system
Version: 0.44.0
Source dir: /home/arichter/dxvk/dxvk-0.91
Build dir: /home/arichter/dxvk/duff/dxvk-master/build.64
Build type: cross build
Project name: dxvk
Native C compiler: ccache cc (gcc 5.5.0)
Cross C compiler: x86_64-w64-mingw32-gcc (gcc 6.1.0)
Native C++ compiler: ccache c++ (gcc 5.5.0)
Cross C++ compiler: x86_64-w64-mingw32-g++ (gcc 6.1.0)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Build machine cpu family: x86_64
Build machine cpu: x86_64
**Checking if "winelib check" compiles: NO**
Library vulkan-1 found: YES
Library d3d11 found: YES
Library dxgi found: YES
Library d3dcompiler_43 found: YES
Library d3dcompiler_47 found: YES
Program glslangValidator found: YES (/bin/glslangValidator)
Dependency threads found: YES

How do get the "winelib check" working?  

0.90 builds fine.

**Comment by JibbityJobbity** [comment]
I got the same output on that line but it still built and ran fine. Are you sure it didn't build and there aren't any other issues? Only thing I can say is to update gcc and mingw.

**Comment by GurnBlanston** [comment]
I'm afraid not, the build stopped rather promptly:
Meson encountered an error in file src/dxvk/meson.build, line 103, column 0:
Argument is of an unacceptable type 'Dependency'.
Must be either an external dependency (returned by find_library() or dependency()) or an internal dependency (returned by declare_dependency()).

I hate to be a bother because I'm such a fan of this project.  
After digging a bit, the testprog.cpp needs this:
#define __WINE__ 
which is something very new to me.

**Comment by doitsujin** [comment]
See 5a1b37b77078d902168e8b8ac2c0c3c23398edfe. Either use that, or use a newer Meson version.
