### ISSUE TITLE
Freeze some games after pressed any key on keyboard

### ISSUE THREAD

**Issue by sr-tream** [doitsujin/dxvk#755]
Some games is freezed after press any key on keyboard. When I pressed keys on mouse, game not freezed.
If I kill freezed game, I lose mouse point - cursor not showed, and programs do not respond to mouse movement and mouse clicks. 

### Software information
Witcher 3 and Fallout 4
Other tested games work is fine and even have a better performance than before

### System information
- GPU: RX560
- Driver: mesa 19, llvm 7
- Wine version: wine-tkg 3.19 (staging, nine, dxvk, faudio, esync)
- DXVK version: v0.91-4-g3d2e5a7

### Log files
https://dl.prime-hack.net/witcher3.zip
https://dl.prime-hack.net/Fallout_4.zip

**Comment by doitsujin** [comment]
And this does not happen with wined3d?

**Comment by sr-tream** [comment]
@doitsujin, I don't known, dxvk is builtin in wine. Now I compile wine-tkg without builtin dxvk, for test it, please wait

**Comment by sr-tream** [comment]
Yes, it a wine trubleshooting
