### ISSUE TITLE
World of Warcraft, renderpass issue?

### ISSUE THREAD

**Issue by ErikEklund** [doitsujin/dxvk#756]
I'm not entirely sure this is a DXVK issue, but I think it is. Without DXVK enabled, the problem does not show. When changing Vulkan driver from RADV to AMDGPU, the issue is exactly the same. So I'm leaning towards that this is a dxvk related.

In certain situations in World of Warcraft, when specific windows are opened or specific spell effects showing, there is a huge slowdown. The simplest example to trigger this is to open the Appearances tab (shift+p, select Appearances tab in the window). The framerate goes down to approx 50-60% of the "normal" value while the window is opened, and is restored when closed.

Example:
Window not opened (regular scene with average amount of players / objects visible): https://i.imgur.com/jK0eQsq.png
Window opened (same scene, only static window visible): https://i.imgur.com/5HQWvFl.png

As you can see in the screenshot above, the "renderpasses" count almost exactly doubles when the window opens. Usually with many players / complex objects in view the drawcalls increase, while the renderpasses stay roughly the same. The increased drawcalls in the screenshot was mostly due to more players in view at the time of the second screenshot, normally when opening the window the drawcalls increase by ~200.

### Software information
World of Warcraft, 7/10 quality setting

### System information
- GPU: Radeon R9 290X
- Driver: 18.2.4
- Wine version: 3.18 staging 
- DXVK version: 0.91

### Apitrace file(s)
Took a while to log in and start game, but when started I opened / closed the problematic window a few times before exiting:
- https://drive.google.com/file/d/1I6i4CoFjOSXAak685YyLT2J8NOPXRGvr/view?usp=sharing (note, 6 GB file!) 

### Log files
Can't see anything interesting here, but here they are anyways:
- d3d11.log: https://pastebin.com/5DfZNgFJ
- dxgi.log: https://pastebin.com/pzfSmpjT

**Comment by doitsujin** [comment]
100 render passes is still in the normal. As far as I can tell, there's no bug here.

**Comment by ErikEklund** [comment]
You might be right, I just wanted to ask the question to see if this was something that can be improved, as it is an annoyance.

What is odd though is that even if you face a wall (ie few things to render = high fps), it drops from say 200 fps to < 100 when opening that static window. No slowdown is noticed without DXVK or on the windows version.

Anyway, if there is no bug here to be fixed, feel free to close this issue. Thanks for the feedback :)

**Comment by SveSop** [comment]
Was not really able to reproduce a huge problem with nVidia.

Standing in Boralus, i have 70'ish fps, and opening the Appearance tab i dropped 5-7 fps, and renderpasses changed from 50 -> 90 at most (so almost double). 

I do however remember SOME issues with this when doing mouseover + shift to compare gear, but kinda think this got fixed with a addon update (but MIGHT have been a dxvk or driver update a while back).

**Comment by ErikEklund** [comment]
It might be my old GPU (290X), that is also only supporting vulkan 1.1.70 that might be the issue. I have at least tried updating Mesa, Vulkan amd DXVK to the latest version without success.

**Comment by ErikEklund** [comment]
Closing this as there does not seem to be any reproducible issue here
