### ISSUE TITLE
Deus Ex Human is broken at DXVK 0.81 and later. 0.80 runs fine.

### ISSUE THREAD

**Issue by GurnBlanston** [doitsujin/dxvk#757]
### Software information
Deus Ex Human Revolution from Steam. 
Using the configuration below dxhr.exe works fine with 0.80 but crashes on 0.81 and later.  Attached logs are from 0.81.  I can rebuild and attach 0.91 logs if necessary. 
Other games such as prey 2017 run Jim-dandy fine on all versions of DXVK. 

### System information
- GPU: AMD RADV Raven (LLVM 7.0.0)
- Driver: 18.4.2
- Wine version: 3.19 staging.  
- DXVK version: 0.81

### Apitrace file(s)
I downloaded apitrace but built a linux binary, I'll try harder to find or build apitrace.exe if this disqualifies this issue. 

### Log files
- d3d11.log: -- attached. 
- dxgi.log: -- attached.
[backtrace.txt](https://github.com/doitsujin/dxvk/files/2568602/backtrace.txt)
[dxhr_d3d11.log](https://github.com/doitsujin/dxvk/files/2568604/dxhr_d3d11.log)
[dxhr_dxgi.log](https://github.com/doitsujin/dxvk/files/2568605/dxhr_dxgi.log)

**Comment by doitsujin** [comment]
You can use [these](https://www.dropbox.com/sh/o769ius47wpu3pw/AABYFKQFFNsCsosXhl7_HReDa?dl=0) DLLs to generate an apitrace (just drop the files for the correct architecture next to the game exe).

The trace has to be generated either with a working DXVK version (0.80 in this case), Windows, or wined3d if the game works correctly with it. Don't use DXVK 0.81 because that's going to produce a completely useless trace file.

**Comment by Glog78** [comment]
@GurnBlanston might wanna give Proton a try or is there a reason why you use a wine-staging with steam installed inside ?

**Comment by doitsujin** [comment]
I got an apitrace from someone else and it replays fine. I'd suggest giving Proton a try as well though.

**Comment by dlshinobi** [comment]
I'm playing with wine-3.18-esync-staging-pba + dxvk [0.80 to 0.91] + nvidia 396.54.x, everything to max and it works fine.

**Comment by Leopard1907** [comment]
It works for me on Proton.

Didn't try with plain Wine.

**Comment by GurnBlanston** [comment]
Curious, it might be my GCC is too old gcc (Mageia 5.5.0-1.mga6) 5.5.0, I'll give it a shot in Proton.  Thanks to everyone for the interest.

**Comment by GurnBlanston** [comment]
It works just fine on Proton, I should have tried this before, I apologize for wasting everyone's time.  Please close this ticket and thank you all for the good advice and attention.
