### ISSUE TITLE
D3D11 minimal tess shader app used when Wine 2.9 added tess shader support..

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#76]
Hi,
I know I know.. you said tess shaders were coming not soon(tm).. :-)
anyway I searched that Wine added support for tess shaders in version 2.9 and mentioned as bug fixed:
https://bugs.winehq.org/show_bug.cgi?id=41184
(DX11 Tesselation tutorial doesn't work correctly)
I mention because this is a very minimal D3D11 test app using tess shaders complete with executable and source code too:
http://www.rastertek.com/dx11tut38.html
http://www.rastertek.com/dx11exe38.zip
http://www.rastertek.com/dx11src38.zip
Hope it can help with your eventual efforts adding tess shader support..

**Comment by doitsujin** [comment]
Works as of 88c4e363e5f079bb54de44c92b6867073812707f.
