### ISSUE TITLE
Resident Evil 7 Biohazard - Black screen when launching the game

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [doitsujin/dxvk#761]
### Software information
Resident Evil 7 Biohazard, 1366×768 - default settings.

The game doesn't load and it looks like this:

![screenshot_20181111_170040](https://user-images.githubusercontent.com/29783425/48314516-6929b000-e5d3-11e8-9104-85976859a3bf.png)

### System information
- GPU: AMD HD 8750M
- Driver: 18.3 latest version
- Wine version: 3.18 staging
- DXVK version: 0.91

### Log files
- d3d11.log: [re7_d3d11.log](https://github.com/doitsujin/dxvk/files/2569483/re7_d3d11.log)
- dxgi.log: [re7_dxgi.log](https://github.com/doitsujin/dxvk/files/2569484/re7_dxgi.log)

**Comment by doitsujin** [comment]
The game requires native media foundation DLLs as far as I know. This is not a DXVK bug.

**Comment by ahmed-elsayed2017** [comment]
I installed it using Winetricks but nothing changed.

**Comment by lieff** [comment]
You can't install it using Winetricks. It installs only mf.dll, not full set
```
mf.dll
mferror.dll
mfplat.dll
mfreadwrite.dll
msmpeg2adec.dll
msmpeg2vdec.dll
sqmapi.dll
```
which is needed. In other words, this game currently not supported by wine.

**Comment by ahmed-elsayed2017** [comment]
I found similar issue at Winehq  https://bugs.winehq.org/show_bug.cgi?id=43814

**Comment by ahmed-elsayed2017** [comment]
Could you please send to me these dlls, and the registry file?

ahmed.com.eg@hotmail.com

**Comment by ahmed-elsayed2017** [comment]
There is a script to fix this problem >>> https://github.com/tonix64/python-installcab

but one thing is missing

`"Now you need to get mfplat.dll version 12.0.7601.23471 from elsewhere and place it in your application directory"`

**Comment by ahmed-elsayed2017** [comment]
@lieff 

Now the game crashs instead of loading forever.

**Comment by lieff** [comment]
¯\_(ツ)_/¯
It can be because of denuvo protection.

**Comment by ahmed-elsayed2017** [comment]
I don't know. It is a short game any way. I will play it on Windows.

**Comment by ahmed-elsayed2017** [comment]
I opened an issue about this problem at Winetricks: https://github.com/Winetricks/winetricks/issues/1132

I think they will fix it faster than WineHQ.

**Comment by ahmed-elsayed2017** [comment]
Resident Evil 7 Biohazard starts after modifying some lines to the old fix **toni** did before.

PS: This fix could work with all game that require **Windows Media Foundation**.

![screenshot_20190130_014143](https://user-images.githubusercontent.com/29783425/52089507-5bbf0900-25b7-11e9-8628-e576779e794f.png)


The modified script (without any dlls from Windows) :
[python-installcab-master.zip](https://github.com/doitsujin/dxvk/files/2819252/python-installcab-master.zip)

**You need to write:**
winetricks mf
export WINEPREFIX=**_/The/Location/Of/The/Game/Prefix_**
./install-mf-64.sh
You need to copy mfplat.dll version 12.0.7601.23471 (Windows7 64bit) to the game folder

**Comment by mozo78** [comment]
Did you try the Gold Edition?

**Comment by ahmed-elsayed2017** [comment]
> Did you try the Gold Edition?

No, I didn't. What is the difference between them?
