### ISSUE TITLE
Final Fantasy XV dxvk 0.92 artifact

### ISSUE THREAD

**Issue by hitman249** [doitsujin/dxvk#762]
![index](https://user-images.githubusercontent.com/1325326/48349541-132e3880-e6b7-11e8-8630-6711d4daefc7.png)

A black square appeared in the upper left corner.

### System information
- GPU: RX 480 4 Gb
- Driver: RADV (mesa 18.3 dev) 
- Wine version: wine-3.19 (Staging) (win64) esync
- DXVK version: 0.92

**Comment by hitman249** [comment]
> Sorry for offtop but that a hud?  

yes 

![puiuljkhq023m057g6zdqw](https://user-images.githubusercontent.com/1325326/48350645-740b4000-e6ba-11e8-8751-75919f5e6546.png)
![34ftuwjgstse5gejcwvxlq](https://user-images.githubusercontent.com/1325326/48350644-7372a980-e6ba-11e8-808a-9a9aa748cbd3.png)

**Comment by hitman249** [comment]
I fell back to version 0.91, and the problem disappeared

![screenshot_20181112_215608](https://user-images.githubusercontent.com/1325326/48355207-13820000-e6c6-11e8-9057-0a5c2122c7b7.png)

The problem is on version 0.92

**Comment by doitsujin** [comment]
Turns out I still have the game installed.

Is there a specific setting that triggers this issue, or a specific spot where it occurs? Because so far, everything is working fine for me:
![bildschirmfoto-428](https://user-images.githubusercontent.com/25567304/48356263-2aa8f980-e696-11e8-93f7-1c2180fa5da9.png)

**Comment by hitman249** [comment]
After I switched back to 0.92 and turned on the dxvk hud the game began to work normally
I don’t know how to explain it, maybe it’s somehow connected **ffxv_s.dxvk-cache**  
magic)

Only the *.dll dxvk files were changed.

**Now the game works great**

**Comment by hitman249** [comment]
The problem was in the program **guake** + **zsh**

**Comment by mixalis1987** [comment]
Did the gamepad work for you?
