### ISSUE TITLE
Games freezing after 5-10 minutes with DXVK enabled

### ISSUE THREAD

**Issue by firewolf24** [doitsujin/dxvk#765]
### Software information
Game(s): Warframe, Destiny 2, Overwatch
Default settings

### System information
- GPU: Intel HD 4400
- Driver: Mesa 18.2.4
- Wine version: esync-staging-pba-3.18-x86_x64
- DXVK version: 0.90

### Log files
- d3d11.log: https://gist.github.com/firewolf24/229e76be1e0ddda154700e795fd6696b
- dxgi.log: https://gist.github.com/firewolf24/8e6c68944eb39f71aae73ad94b55f167

**Comment by doitsujin** [comment]
On Intel, you need at least a Broadwell-class GPU for full Vulkan support, Haswell is not supported.
