### ISSUE TITLE
DXVK freezes at startup game WorldOfTanks become in revision r1755

### ISSUE THREAD

**Issue by Kendak** [doitsujin/dxvk#768]
Hello doitsujin.
thanks for your excellent work on dxvk. But in revision: r1755 (which I downloaded from here:
https://haagch.frickel.club/files/dxvk/r1755.1724d51/32/bin/ )
is this error
debug: D3D11Device: No such vertex shader semantic: NORMAL0
debug: D3D11Device: No such vertex shader semantic: TANGENT0
debug: D3D11Device: No such vertex shader semantic: BINORMAL0

And game after this errors freezes during startup - I dont see login page/screen. Game is stucked.

If I use revision 1752 game will normal start.
Something is wrong in revision 1755 and later (1757 and 1760 doesn't work too)

### Software information
World Of Tanks 32bit version

### System information
- GPU: Nvidia GeForce 1050 Ti
- Driver: 415.13.0
- Wine version: 3.19 staging
- DXVK version: r1755

### Log files
- d3d11.log: [WorldOfTanks_d3d11.log](https://github.com/doitsujin/dxvk/files/2588575/WorldOfTanks_d3d11.log)
- dxgi.log: [WorldOfTanks_dxgi.log](https://github.com/doitsujin/dxvk/files/2588576/WorldOfTanks_dxgi.log)
- stdout log: [debug.1755.log](https://github.com/doitsujin/dxvk/files/2588561/debug.1755.log)

**Comment by doitsujin** [comment]
So 0.92 is fine?

**Comment by doitsujin** [comment]
Oh, also, please try an older driver. 415.13 is known to cause major issues.

**Comment by doitsujin** [comment]
Can't test because the Wargaming Game Center is broken on Wine.

**Comment by acedogblast** [comment]
I can help from windows. Do you need API trace of the game staring up or is it just the launcher that is having issues?

**Comment by doitsujin** [comment]
Got WGC to work and the game installed. How do I enable D3D11? It uses D3D9 for me.

**Comment by Kendak** [comment]
> Oh, also, please try an older driver. 415.13 is known to cause major issues.

Yes, I try 390.x, but it still same error -> newest release dxvk will not work on same error.

**Comment by K0bin** [comment]
Try 396 instead. The 390 drivers are ancient and broken.

**Comment by arzardk** [comment]
I tested DXVK x64 from [source](https://haagch.frickel.club/files/dxvk/r1755.1724d51/32/bin/) that @Kendak provided and encountered same bug: no login screen, just black window. I have same hardware (GTX 1050 Ti), Nvidia driver 396.54.09, all settings on Ultra. With DXVK 0.92, game works normally. 
Also, @Kendak your driver (415.13) does not support transform feedback which is needed if you wish to play with DX11 in this game.

**Comment by doitsujin** [comment]
This doesn't make any sense, it should be impossible for that specific commit to cause such an issue.

Anyway, if 0.92 works, just keep using that I guess. I cannot reproduce the bug and won't be able to fix it.

**Comment by doitsujin** [comment]
@arzardk actually, can you test e4d3357e55811cb8a5257ea8bd7b68c25a5eb022? Not sure if that fixes anything, but DXVK could definitely be doing the wrong thing there.

**Comment by arzardk** [comment]
Ok, i'll try it.

**Comment by doitsujin** [comment]
Current `master` requires MinGW 6.0.

Anyway, here's a build of latest master:
[dxvk-master.tar.gz](https://github.com/doitsujin/dxvk/files/2589622/dxvk-master.tar.gz)

**Comment by arzardk** [comment]
Game works normally.
Here is [DXGI log file](https://gist.github.com/arzardk/ffd75be270ead3c2432852514985f3e5 )

**Comment by magist3r** [comment]
Can confirm that [e4d3357](https://github.com/doitsujin/dxvk/commit/e4d3357e55811cb8a5257ea8bd7b68c25a5eb022) fixed the issue for me.

**Comment by doitsujin** [comment]
Alright, thanks for confirming.
