### ISSUE TITLE
Performance of state heavy applications

### ISSUE THREAD

**Issue by SpookySkeletons** [doitsujin/dxvk#772]
State heavy games seem to take a really hard toll on performance and dip well below the 80-90% performance rates I see everywhere else.

As far as I understand it would a similar caching mechanism to shader cache be able to be extended to any other element of the pipeline? Is it preferable to make some kind of a time/memory tradeoff in order to allocate GPU memory to reuse state to boost general performance?

**Comment by doitsujin** [comment]
What do you mean by "state-heavy games"?

**Comment by SpookySkeletons** [comment]
Games heavily reliant on streaming elements that must be performed in a sequence.
Is it possible to cache any inputs of streaming elements so that they can be reused, the same way that shader state cache is done, and match them up to run calls in parallel?

**Comment by doitsujin** [comment]
I still don't understand *what exactly you mean*. What's a "streaming element"?

**Comment by SpookySkeletons** [comment]
The game itself I'm having trouble with is Space Engineers now that it functions under wine at about 2/3 of the dx11 performance under most circumstances.
I don't know much about how graphical APIs work, was throwing some conjecture to see if I was onto anything, the game makes heavy use of stream output so I thought that might contribute, but I am going to try to get a trace of the game to pick through. What is your preferred trace method?
Would a Vulkan capture with renderdoc be any use for figuring out the slowdown?

**Comment by doitsujin** [comment]
> Would a Vulkan capture with renderdoc be any use for figuring out the slowdown?

If you have an AMD Polaris card (RX 480/580 and similar models), then I could take a look at it, yes. Unfortunately, Vulkan renderdoc captures are not portable.

Otherwise, apitrace should hopefully work (see Wiki/Common Issues).

**Comment by doitsujin** [comment]
Closing due to the lack of feedback, and this doesn't seem to be a bug to begin with.
