### ISSUE TITLE
0.80 binary release sha256sum change

### ISSUE THREAD

**Issue by bobwya** [doitsujin/dxvk#773]
@doitsujin 

@austin987 and I, are wondering how and/ or why the sha256sum for the tar.gz binary build of **dxvk** version **0.80** has changed since the release date??

For reference:
```
sha256sum ~/.cache/winetricks/dxvk80/dxvk-0.80.tar.gz 
f9e736cdbf1e83e45ca748652a94a3a189fc5accde1eac549b2ba5af8f7acacb  /home/robert_gentoo/.cache/winetricks/dxvk80/dxvk-0.80.tar.gz

sha256sum ~/Downloads/dxvk-0.80.tar.gz 
7058a834bb006cad5462933110449b434df561e67d83f68d3965ecc74e2e1cbc  /home/robert_gentoo/Downloads/dxvk-0.80.tar.gz
```
The former file was downloaded on **23 September 2018**.
The latter file was downloaded today, **17 November 2018**.

I wasn't aware of re-release of version **0.80**.
The hash change has been confirmed by multiple other Wine users on IRC.

Is Github suffering bitrot now that Microsoft have taken over? ;-)
Has the binary been rebuilt for some reason?

Any thoughts?

Thanks, Bob

**Comment by doitsujin** [comment]
The current file is definitely valid and matches that of the file that I still have lying around. It was rebuilt with a clean GCC 8.2 toolchain, IIRC because someone was complaining about seeing two different gcc versions in the binaries.

**Comment by austin987** [comment]
It would be helpful for us if that was documented somewhere. Even better if you use a different filename, e.g. -r1, but your call, of course.

**Comment by bobwya** [comment]
@doitsujin 

Thanks for the info!
