### ISSUE TITLE
GTAV Play Error

### ISSUE THREAD

**Issue by JamesChenChina** [doitsujin/dxvk#774]
launch GTAV,
ERR_GFX_D3D_NOD3D1X_4
No DirectX 10 or 11 adapter or runtime found. Please install latest Direct X runtime or install a compatible DirectX 10 or 11 video card.

### System information
- GPU: NVIDIA Quadro M5000
- Driver:396.54.09
- Wine version: wine-3.20
- DXVK version: 0.92

### Log files
- d3d11.log:
empty
- dxgi.log: 
info:  Game: GTA5.exe
info:  DXVK: v0.92
info:  Found built-in config: GTA5.exe
info:  Effective configuration:
info:    dxgi.customVendorId = 1002
info:    dxgi.customDeviceId = e366
warn:  OpenVR: Failed to locate module
info:  Required Vulkan extension VK_KHR_get_physical_device_properties2 not supported
info:  Required Vulkan extension VK_KHR_surface not supported
info:  Required Vulkan extension VK_KHR_win32_surface not supported
err:   DxvkInstance: Failed to create instance

### System information
- GPU: NVIDIA Quadro M5000
- Driver:396.54.09
- Wine version: wine-3.20
- DXVK version: 0.92

### Log files
- d3d11.log:
- dxgi.log: 

details:
### _______________________________________________________________
nvidia-smi
Tue Nov 20 18:42:36 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.54.09              Driver Version: 396.54.09                 |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro M5000        Off  | 00000000:03:00.0  On |                  Off |
| 45%   57C    P0    47W / 150W |    196MiB /  8123MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1582      G   /usr/lib/xorg/Xorg                            12MiB |
|    0      1844      G   /usr/lib/xorg/Xorg                           182MiB |
+-----------------------------------------------------------------------------+

which wine
/usr/local/bin/wine

wine --version
wine-3.20

~/Downloads/dxvk-0.92$ ../winetricks --force setup_dxvk.verb
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20180815-next - sha256sum: 354d480ed89b398275e099345855918ab5bed806d4313faee8b3139794a2793b with wine-3.20 and WINEARCH=win64
------------------------------------------------------
Github down? version '' doesn't appear to be a valid version
------------------------------------------------------
------------------------------------------------------
You are running winetricks-20180815-next, latest upstream is winetricks-!
------------------------------------------------------
------------------------------------------------------
You should update using your distribution's package manager, --self-update, or manually.
------------------------------------------------------
Executing w_do_call setup_dxvk
Executing load_setup_dxvk 
Executing cp /home/c00417849a/Downloads/dxvk-0.92/x32/dxgi.dll /home/c00417849a/.wine/dosdevices/c:/windows/syswow64/dxgi.dll
Executing cp /home/c00417849a/Downloads/dxvk-0.92/x32/d3d11.dll /home/c00417849a/.wine/dosdevices/c:/windows/syswow64/d3d11.dll
Executing cp /home/c00417849a/Downloads/dxvk-0.92/x32/d3d10.dll /home/c00417849a/.wine/dosdevices/c:/windows/syswow64/d3d10.dll
Executing cp /home/c00417849a/Downloads/dxvk-0.92/x32/d3d10_1.dll /home/c00417849a/.wine/dosdevices/c:/windows/syswow64/d3d10_1.dll
Executing cp /home/c00417849a/Downloads/dxvk-0.92/x32/d3d10core.dll /home/c00417849a/.wine/dosdevices/c:/windows/syswow64/d3d10core.dll
Executing cp /home/c00417849a/Downloads/dxvk-0.92/x64/dxgi.dll /home/c00417849a/.wine/dosdevices/c:/windows/system32/dxgi.dll
Executing cp /home/c00417849a/Downloads/dxvk-0.92/x64/d3d11.dll /home/c00417849a/.wine/dosdevices/c:/windows/system32/d3d11.dll
Executing cp /home/c00417849a/Downloads/dxvk-0.92/x64/d3d10.dll /home/c00417849a/.wine/dosdevices/c:/windows/system32/d3d10.dll
Executing cp /home/c00417849a/Downloads/dxvk-0.92/x64/d3d10_1.dll /home/c00417849a/.wine/dosdevices/c:/windows/system32/d3d10_1.dll
Executing cp /home/c00417849a/Downloads/dxvk-0.92/x64/d3d10core.dll /home/c00417849a/.wine/dosdevices/c:/windows/system32/d3d10core.dll
Using native override for following DLLs: dxgi d3d11 d3d10 d3d10_1 d3d10core
Executing wine regedit C:\windows\Temp\_setup_dxvk\override-dll.reg
Executing wine64 regedit C:\windows\Temp\_setup_dxvk\override-dll.reg
You opted in, so reporting 'setup_dxvk ' to the winetricks maintainer so he knows which winetricks verbs get used and which don't.  Use --optout to disable future reports.

**Comment by doitsujin** [comment]
You probably don't have the Vulkan ICD loader installed or something like that. Can't tell exactly what this is without the log files, but it's something you need to fix on your setup.

Also, please fix the formatting of your post.

**Comment by JamesChenChina** [comment]
@doitsujin 
dpkg -l|grep vulkan

ii  libvulkan-dev:amd64                                         1.1.73+dfsg-1                                amd64        Vulkan loader library -- development files
ii  libvulkan1:amd64                                            1.1.73+dfsg-1                                amd64        Vulkan loader library
ii  libvulkan1:i386                                             1.1.73+dfsg-1                                i386         Vulkan loader library
ii  vulkan-utils                                                1.1.73+dfsg-1                                amd64        Miscellaneous Vulkan utilities

**Comment by doitsujin** [comment]
Then please post the `GTAV_dxgi.log` and `GTAV_d3d11.log` or whatever they are called. The files should be next to the game exe.

**Comment by JamesChenChina** [comment]
@doitsujin Thanks for your help. I have posted GTAV_dxgi.log and GTAV_d3d11.log  at very start. please review

**Comment by doitsujin** [comment]
It fails to initialize Vulkan. Please make sure that you can run native Vulkan applications such as `vulkaninfo`, this is not a DXVK bug.

**Comment by doitsujin** [comment]
Looks like your graphics driver is not installed correctly for some reason. Can't help you with that though, don't have an Nvidia test rig right now and also don't know which distro you're running.

**Comment by Leopard1907** [comment]
@JamesChenChina

https://github.com/lutris/lutris/wiki/How-to:-DXVK

Follow that guide
