### ISSUE TITLE
GTAV: game freezes after keyboard input && low FPS

### ISSUE THREAD

**Issue by JamesChenChina** [doitsujin/dxvk#776]
using Lutris to play GTAV. 
FPS is only about 30. 
Game freezes about 2 seconds after any keyboard input. And FPS down to nearly 0.
Searching for help and solution! 
I tried wine3.19 and wine3.20. Both versions didn't help.
Thanks a lot!

### Software information
GTAV

### System information
- GPU: NVIDIA Quadro M5000
- Driver:396.54.0
- Wine version: 3.19/3.20
- DXVK version: 0.92
 -System: Ubuntu16.04

### Log files
- d3d11.log:
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_10_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_10_0
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0

- dxgi.log: 
info:  Game: GTA5.exe
info:  DXVK: v0.92
info:  Found built-in config: GTA5.exe
info:  Effective configuration:
info:    dxgi.customVendorId = 1002
info:    dxgi.customDeviceId = e366
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Quadro M5000:
info:    Driver: 396.54.0
info:    Vulkan: 1.1.70
info:    Memory Heap[0]: 
info:      Size: 8192 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 48264 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
info:  Game: GTA5.exe
info:  DXVK: v0.92
info:  Found built-in config: GTA5.exe
info:  Effective configuration:
info:    dxgi.customVendorId = 1002
info:    dxgi.customDeviceId = e366
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Quadro M5000:
info:    Driver: 396.54.0
info:    Vulkan: 1.1.70
info:    Memory Heap[0]: 
info:      Size: 8192 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 48264 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 8 valid state cache entries
info:  DXVK: Using 12 compiler threads
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 8 valid state cache entries
info:  DXVK: Using 12 compiler threads
info:  DXGI: Setting display mode: 800x600@60
warn:  DXGI: MakeWindowAssociation: Ignoring flags
info:  Game: GTA5.exe
info:  DXVK: v0.92
info:  Found built-in config: GTA5.exe
info:  Effective configuration:
info:    dxgi.customVendorId = 1002
info:    dxgi.customDeviceId = e366
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  Quadro M5000:
info:    Driver: 396.54.0
info:    Vulkan: 1.1.70
info:    Memory Heap[0]: 
info:      Size: 8192 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 48264 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 205 valid state cache entries
info:  DXVK: Using 12 compiler threads
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 206 valid state cache entries
info:  DXVK: Using 12 compiler threads
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 206 valid state cache entries
info:  DXVK: Using 12 compiler threads
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 224 valid state cache entries
info:  DXVK: Using 12 compiler threads
warn:  DXGI: MakeWindowAssociation: Ignoring flags
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 224 valid state cache entries
info:  DXVK: Using 12 compiler threads
info:  DXGI: Setting display mode: 1024x768@60
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 224 valid state cache entries
info:  DXVK: Using 12 compiler threads
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 225 valid state cache entries
info:  DXVK: Using 12 compiler threads
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 225 valid state cache entries
info:  DXVK: Using 12 compiler threads
info:  DXGI: Setting display mode: 800x600@60
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 225 valid state cache entries
info:  DXVK: Using 12 compiler threads
warn:  DXGI: MakeWindowAssociation: Ignoring flags
info:  DXGI: Setting display mode: 1920x1080@60
warn:  DXGI: LeaveFullscreenMode: Failed to restore display mode

**Comment by Kron4ek** [comment]
Do you use staging or vanilla Wine?

**Comment by JamesChenChina** [comment]
@Kron4ek 
Thanks for your reply.
I got source code here https://github.com/wine-mirror/wine
Is that ok?

**Comment by Kron4ek** [comment]
@JamesChenChina You are using vanilla Wine. It's ok, but not for GTAV. The last time i tried to play in GTAV with vanilla Wine (3.6) it freezed on keyboard input for a few seconds.

So use Wine Staging 3.19 (not 3.20).

**Comment by d4rkf4b** [comment]
Use Nvidia 396.54.**09** (ppa graphics-drivers/dev)
And install wine staging with Lutris (manage runners)

**Comment by Kron4ek** [comment]
@JamesChenChina i have just an integrated GPU, so my fps is lower than yours. What CPU do you have?

**Comment by d4rkf4b** [comment]
With i7-4790k and GTX970, 60 FPS . Only MSAA is off.

**Comment by JamesChenChina** [comment]
@Kron4ek Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz

**Comment by d4rkf4b** [comment]
@JamesChenChina 
no more. Using wine-tkg-3.20 in Lutris with latest dxvk, that's all.

**Comment by JamesChenChina** [comment]
@Kron4ek By the way, I got wine-staging3.19(amd64) from your link 

in a new machine(Ubuntu16.04 64bit) just
sudo cp -r bin /usr/local/
sudo cp -r lib /usr/local/
sudo cp -r lib64 /usr/local/
sudo cp -r share /usr/local/

then 
wine --version
ERROR: ld.so: object 'libachk.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
wine-3.19 (Staging)

Do you know error reason?
Thanks a lot

**Comment by Kron4ek** [comment]
Do you have Wine from repositories installed? If not, you have to install it because of dependencies.

And it better to use Wine from my link without copying it to /usr/local, just unpack and use full path to binary. Or just copy whole directory to /opt.

**Comment by LunaSquee** [comment]
I'm having the same issue over here. GTAV hangs for 5 seconds after any keyboard input.

**Comment by libcg** [comment]
I believe this doesn't happen with older versions of DXVK. Will try to bisect tonight.

**Comment by LunaSquee** [comment]
I figured out the problem with the keyboard input freezing. It has to do
with a patch of dinput in wine-staging that was removed recently. I
reverted to wine-staging 3.18 and I no longer have this issue.
