### ISSUE TITLE
[Assasin creed Syndicate] fps drops if anti-aliasing is enabled

### ISSUE THREAD

**Issue by nickfaces** [doitsujin/dxvk#778]
If anti-aliasing is enabled fps drops from 60-70 to 20-30. MSAA or FXAA - no difference.
Yes, MSAA its so hard for hardware, but FXAA... And I see its only in this game. 

### System information
- GPU: RX 580 8Gb
- Driver: mesa-git + llvm-svn
- Wine version: 3.20 tgk
- DXVK version: 0.92

[ACS_d3d11.log](https://github.com/doitsujin/dxvk/files/2605398/ACS_d3d11.log)

[ACS_dxgi.log](https://github.com/doitsujin/dxvk/files/2605399/ACS_dxgi.log)

**Comment by doitsujin** [comment]
Works fine for me (RX 480).

**Comment by nickfaces** [comment]
Sorry for the silence. I changed my rx 580 to 590, but it doesn’t work properly. I will test as soon as amd fixes the problem.
