### ISSUE TITLE
Unity BlackSmith 2015 tech demo keeps unresponsive upon loading.. 

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#78]
### Software information
See
https://blogs.unity3d.com/es/2015/06/24/releasing-the-blacksmith/
supposedly state of the art Unity engine circa 2015..
link:http://democontent.unity3d.com/BlacksmithStandalone_2015-06-24_0-00-06.05%202.7z

### System information
- GPU: AMD Vega
- Driver: latest
- Wine version:  none native Win
- DXVK version: latest as of today

### Log files
- d3d11.log:
[volund_d3d11amd.log](https://github.com/doitsujin/dxvk/files/1726299/volund_d3d11amd.log)
- dxgi.log: 
[volund_dxgiamd.log](https://github.com/doitsujin/dxvk/files/1726300/volund_dxgiamd.log)

seems unique error is:
err:   D3D11Device: CheckFeatureSupport: Unknown feature: 10

**Comment by doitsujin** [comment]
Works for me on RADV. Keep in mind that compiling shaders etc. can take several minutes, as long as there's some CPU load, the demo is actually doing something.

PS: Ignore the comment on the Adam demo, mixed the two up.

**Comment by oscarbg** [comment]
this is true.. also works also on AMDVLK.. and on Windows AMD driver I remember to have tested today also..
