### ISSUE TITLE
Dying Light terrain corruption

### ISSUE THREAD

**Issue by ThePiggyBanks** [doitsujin/dxvk#781]
I have several times encountered small patches of terrain which is randomly placed too high or too low. The problem should be clear by the following screenshots of a more extreme case:
![2018-11-24_17-27-41-781906721](https://user-images.githubusercontent.com/45315930/48971071-8750d080-f015-11e8-8033-3639c8772c88.png)
![2018-11-24_17-26-50-612263810](https://user-images.githubusercontent.com/45315930/48971072-8750d080-f015-11e8-97d6-b9c12d4f9344.png)

### Software information
Dying Light (latest GOG Version). The problem is present on both lowest and highest settings.

### System information
- GPU: AMD RX 580 8 GB
- Driver: 19.0.0-devel (git-896c59d 2018-11-22 xenial-oibaf-ppa)
- Wine version: wine-3.20 (Staging)
- DXVK version: 0.93 (but also happens with version 0.91).

### Apitrace file(s)
- https://wetransfer.com/downloads/358d8ec23d92f7ac168a555bf049791a20181124171052/3540d3b8cf4e7e788de70d98bf6fa07f20181124171052/ab4eab

### Log files
- d3d11.log: [DyingLightGame_d3d11.log](https://github.com/doitsujin/dxvk/files/2612445/DyingLightGame_d3d11.log)
- dxgi.log: [DyingLightGame_dxgi.log](https://github.com/doitsujin/dxvk/files/2612446/DyingLightGame_dxgi.log)

**Comment by doitsujin** [comment]
Are you sure that this isn't just a game bug? Same thing happens when replaying your trace with wined3d.

**Comment by ThePiggyBanks** [comment]
I do not currently have a Windows computer to test this on. However, I have found some videos on Youtube where people didn't have the same problem - as an example (I apologise for the blurriness; these were the best screenshots I could get):
![Youtube](https://user-images.githubusercontent.com/45315930/48978415-70f55400-f0ab-11e8-898d-eaf0770e86a9.png)
[Source](https://www.youtube.com/watch?v=KH2y1flk9P0&t=1022)

And for comparison (DXVK screenshot first):
![dxvk](https://user-images.githubusercontent.com/45315930/48978417-81a5ca00-f0ab-11e8-8b35-f64f975c551b.png)
![youtube1](https://user-images.githubusercontent.com/45315930/48978418-85d1e780-f0ab-11e8-95a9-aed511cd12b4.png)
[Source](https://www.youtube.com/watch?v=KH2y1flk9P0&t=1184)

Furthermore I am fairly certain that this is a bug in DXVK, since I sometimes experience the same in other games run through DXVK (e.g. The Witcher 3 where the water sometimes has a wrong height offset) but I haven't seen this in a native game.

**Comment by doitsujin** [comment]
Same thing happens on Windows when replaying your trace.
![dyinglight](https://user-images.githubusercontent.com/25567304/48979537-b4a48980-f0bc-11e8-9196-71202b9c612b.png)

**Comment by ThePiggyBanks** [comment]
I have now gotten access to a Windows computer and it appears, that the bug does indeed happen there as well, so I guess it is not a DXVK bug after all. Sorry for the inconvenience.

**Comment by doitsujin** [comment]
Alright, thanks for testing. I guess this can be closed then.
