### ISSUE TITLE
Witcher 3 black screen after winehq-staging update

### ISSUE THREAD

**Issue by PrzemekSkw** [doitsujin/dxvk#786]
Hi, sory for issue with wine-staging but I don't know where to go. 
Second time when I update winehq-staging I have problem with W3. Few weeks ago I update wine-staging and Witcher 3 stop working (desktop freeze after launch game). I have to restore my system with Timeshift, then block wine-staging update, then update nvidia drivers and other updates. After few days I unblock wine-staging and update it and everything was fine. 
Yesterday those updates appear:
`ocl-icd-libopencl1 ocl-icd-libopencl1:i386
  accountsservice curl desktop-file-utils dmsetup gdm3 gedit gedit-common gir1.2-accountsservice-1.0 gir1.2-gdm-1.0 gir1.2-goa-1.0 gnome-control-center gnome-control-center-data gnome-control-center-faces gnome-initial-setup
  gnome-online-accounts initramfs-tools initramfs-tools-bin initramfs-tools-core libaccountsservice0 libc-bin libc-dev-bin libc6 libc6:i386 libc6-dbg libc6-dev libc6-i386 libcurl3-gnutls libcurl4 libdevmapper1.02.1 libgdm1 libgoa-1.0-0b
  libgoa-1.0-common libgoa-backend-1.0-1 libnvidia-cfg1-410 libnvidia-common-410 libnvidia-compute-410 libnvidia-compute-410:i386 libnvidia-decode-410 libnvidia-decode-410:i386 libnvidia-encode-410 libnvidia-encode-410:i386
  libnvidia-fbc1-410 libnvidia-fbc1-410:i386 libnvidia-gl-410 libnvidia-gl-410:i386 libnvidia-ifr1-410 libnvidia-ifr1-410:i386 libxnvctrl0 locales multiarch-support nvidia-compute-utils-410 nvidia-dkms-410 nvidia-driver-410
  nvidia-kernel-common-410 nvidia-kernel-source-410 nvidia-settings nvidia-utils-410 pop-gtk-theme pop-icon-theme python3-distupgrade ubuntu-release-upgrader-core ubuntu-release-upgrader-gtk wine-staging wine-staging-amd64
  wine-staging-i386:i386 winehq-staging xserver-xorg-video-nvidia-410` 

I upgrade and Witcher 3 stop working (black screen after I launch game, no lutris combination with wine and dxvk helps) so I also restore my system with Timeshift and Witcher works. I must block wine-staging upgrade and install rest of packages and then upgrade wine-staging. Anyone also have that issue?

### Software information
Witcher 3 GOTY (from gog) installed with Lutris.
### System information
- Ubuntu 18.10
- CPU: i5-7300HQ CPU 2.50GHz × 4
- GPU: NVIDIA GTX 1050
- Driver: 410.73
- Wine version: esync-staging-pba-nopulse-3.18-x86_64 (from lutris)
- DXVK version: 0.92

**Comment by MartinPL** [comment]
Wine staging is official part of Wine. Here http://bugs.winehq.org/ is place to report wine/staging problems.

**Comment by SveSop** [comment]
@PrzemekSkw "Great" depending on if you would like Geralt's hair to wave in the wind with nVidia's "Hairworks"... cos that i think does NOT work with 410.73 due to missing support of `VK_EXT_transform_feedback` extension for DXVK.
