### ISSUE TITLE
dxvk install problem

### ISSUE THREAD

**Issue by JamesChenChina** [doitsujin/dxvk#787]
**Problems with using WINE and installing DXVK.**
**Thanks a lot!**

**DXVK install info:**
Executing w_do_call setup_dxvk
Executing load_setup_dxvk 
Executing cp /home/ppegavsim/drive_d/tools/dxvk/dxvk-0.92/x32/dxgi.dll /home/ppegavsim/.wine/dosdevices/c:/windows/syswow64/dxgi.dll
Executing cp /home/ppegavsim/drive_d/tools/dxvk/dxvk-0.92/x32/d3d11.dll /home/ppegavsim/.wine/dosdevices/c:/windows/syswow64/d3d11.dll
Executing cp /home/ppegavsim/drive_d/tools/dxvk/dxvk-0.92/x32/d3d10.dll /home/ppegavsim/.wine/dosdevices/c:/windows/syswow64/d3d10.dll
Executing cp /home/ppegavsim/drive_d/tools/dxvk/dxvk-0.92/x32/d3d10_1.dll /home/ppegavsim/.wine/dosdevices/c:/windows/syswow64/d3d10_1.dll
Executing cp /home/ppegavsim/drive_d/tools/dxvk/dxvk-0.92/x32/d3d10core.dll /home/ppegavsim/.wine/dosdevices/c:/windows/syswow64/d3d10core.dll
Executing cp /home/ppegavsim/drive_d/tools/dxvk/dxvk-0.92/x64/dxgi.dll /home/ppegavsim/.wine/dosdevices/c:/windows/system32/dxgi.dll
Executing cp /home/ppegavsim/drive_d/tools/dxvk/dxvk-0.92/x64/d3d11.dll /home/ppegavsim/.wine/dosdevices/c:/windows/system32/d3d11.dll
Executing cp /home/ppegavsim/drive_d/tools/dxvk/dxvk-0.92/x64/d3d10.dll /home/ppegavsim/.wine/dosdevices/c:/windows/system32/d3d10.dll
Executing cp /home/ppegavsim/drive_d/tools/dxvk/dxvk-0.92/x64/d3d10_1.dll /home/ppegavsim/.wine/dosdevices/c:/windows/system32/d3d10_1.dll
Executing cp /home/ppegavsim/drive_d/tools/dxvk/dxvk-0.92/x64/d3d10core.dll /home/ppegavsim/.wine/dosdevices/c:/windows/system32/d3d10core.dll
Using native override for following DLLs: dxgi d3d11 d3d10 d3d10_1 d3d10core
Executing wine regedit C:\windows\Temp\_setup_dxvk\override-dll.reg
ERROR: ld.so: object 'libachk.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libachk.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
003d:err:module:load_builtin_dll failed to load .so lib for builtin L"winex11.drv": libXext.so.6: cannot open shared object file: No such file or directory
003d:err:user:load_desktop_driver failed to load L"C:\\windows\\system32\\winex11.drv"
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Executing wine64 regedit C:\windows\Temp\_setup_dxvk\override-dll.reg
You opted in, so reporting 'setup_dxvk ' to the winetricks maintainer so he knows which winetricks verbs get used and which don't.  Use --optout to disable future reports.

**I think I have install 2.6.1 FreeType as info below:**
apt list|grep freetype
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
freetype2-demos/xenial-updates,xenial-security 2.6.1-0.1ubuntu2.3 amd64
libfont-freetype-perl/xenial,now 0.07-1build1 amd64 [installed]
libfreetype6/xenial-updates,xenial-security,now 2.6.1-0.1ubuntu2.3 amd64 [installed]
libfreetype6-dev/xenial-updates,xenial-security,now 2.6.1-0.1ubuntu2.3 amd64 [installed]
libisfreetype-java/xenial,xenial 5.3.20100629-3build1 all
libisfreetype-java-doc/xenial,xenial 5.3.20100629-3build1 all

**There is also a strange error about WINE.**
wine --version
ERROR: ld.so: object 'libachk.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
wine-3.19 (Staging)

### System information

- Wine version: wine-3.19 (Staging)
- DXVK version: 0.92
- GPU:
- Driver:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.54.09              Driver Version: 396.54.09                 |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P5000        Off  | 00000000:21:00.0  On |                  Off |
| 26%   35C    P8     7W / 180W |    361MiB / 16275MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1119      G   /usr/lib/xorg/Xorg                           196MiB |
|    0      2210      G   compiz                                       144MiB |
|    0     39984      G   ...uest-channel-token=17535810757399260506    17MiB |
+-----------------------------------------------------------------------------+

**Comment by SveSop** [comment]
@JamesChenChina 
I suspect you do not have :i386 libraries installed?
Do a `dpkg -l | grep -i libfreetype` and check the output.
It should read both libfreetype6:amd64 and libfreetype6:i386.

A good guide on getting wine correctly installed for Ubuntu is here:
[https://wiki.winehq.org/Ubuntu](https://wiki.winehq.org/Ubuntu)

Usually a hint is in the "Wrong ELF class" error message..

Is your wineprefix a 64-bit one?

**Comment by Guy1524** [comment]
Usually when installing wine from official repositories, it will fetch the 32-bit libraries for you, so it's odd that you don't have them.  Make sure you have run `dpkg --add-architecture i386` so that 32 bit libraries are supported.

**Comment by JamesChenChina** [comment]
@SveSop I just got a already compiled Wine builds(WINE 3.19 staging amd64) from https://drive.google.com/drive/folders/1HkgqEEdAkCSYUCRFN64GGFTLF7H_Q5Xr

My OS is Ubuntu16.04

and then 
sudo cp -r bin /usr/local/
sudo cp -r lib /usr/local/
sudo cp -r lib64 /usr/local/
sudo cp -r share /usr/local/

then
wine --version
ERROR: ld.so: object 'libachk.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
wine-3.19 (Staging)

I have also dpkg --add-architecture i386.
but no use.

**Comment by Guy1524** [comment]
@JamesChenChina You should install wine first from your package manager, then remove it so that you have all the dependencies.

**Comment by JamesChenChina** [comment]
@Guy1524  OK Thanks a lot!
