### ISSUE TITLE
(GTA V) System hang during the benchmark scene with AMDVLK

### ISSUE THREAD

**Issue by Alexander88207** [doitsujin/dxvk#790]
If I start the benchmark in gta v, the entire system hangs when the part comes with the jet 
and I need to restart my PC.

### System information
- GPU: RX 570
- Driver: AMDVLK 2.0.63
- Wine version: Proton 3.16-4
- DXVK version: DXVK 0.90

### Apitrace file(s) & log files with DXVK 
but i think they are useless...
- http://ul.to/f/4nnt33

**Comment by doitsujin** [comment]
Does it work with RADV?

**Comment by Alexander88207** [comment]
> Yes, your trace file is empty. Does it work with RADV?

Yes

**Comment by doitsujin** [comment]
In that case it's probably more fruitful to report a bug to them. I can't do much about GPU hangs unless they are caused by invalid use of the Vulkan API, but without a test case/apitrace I can't verify that either.

**Comment by Alexander88207** [comment]
All right, thank you.
