### ISSUE TITLE
Battlefield 1 fails to start on RADV since performance patch for nvidia

### ISSUE THREAD

**Issue by elovin** [doitsujin/dxvk#795]
Battlefield 1 fails to start with the message:
![image](https://user-images.githubusercontent.com/32832123/49343770-759fa680-f66f-11e8-883f-4533f8b8b9fe.png)

This is caused by commit 500d67e00280f1be7c12ccdbe2cda6eaedce4ce2

### Software information
Battlefield 1

### System information
- GPU: R9 Nano
- Driver: mesa-18.2.5
- Wine version: 3.21
- DXVK version: 
tested 0.93, 2d55852777ade5647c4b6cc379fba612ae17131b and 500d67e00280f1be7c12ccdbe2cda6eaedce4ce2

**Comment by pchome** [comment]
@elovin 
This likely reported by `nvapi` from wine-staging:
* [NvAPI_GetDisplayDriverVersion](https://github.com/wine-staging/wine-patched/blob/master/dlls/nvapi/nvapi.c#L298)
* [NvAPI_SYS_GetDriverAndBranchVersion](https://github.com/wine-staging/wine-patched/blob/master/dlls/nvapi/nvapi.c#L524)

Pretty easy to patch, if you build wine-staging manually. Or report to  https://bugs.winehq.org/ .
