### ISSUE TITLE
Compiler can't find math.h and stdlib.h

### ISSUE THREAD

**Issue by Sukid** [doitsujin/dxvk#799]
Trying to compile for Winelib, and whether I use the AUR or download and compile manually (even the stable source), I get these two errors multiple times:
/usr/include/c++/8.2.1/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>

/usr/include/c++/8.2.1/cmath:45:15: fatal error: math.h: No such file or directory
 #include_next <math.h>

And the build fails.

I'm starting to think this is something particular to my system since I'm not seeing a lot of people mention this issue with regards to DXVK.

**Comment by Tk-Glitch** [comment]
You need to revert 0e279d26b8386fc878f17bd6768e46e1cf9c5128 commit in wine mainline to get a wine build able to build DXVK.

**Comment by Sukid** [comment]
Thanks guys! I'll have a look at those. I also found out that you can also edit cstdlib and cmath, and change the #include_next for stdlib.h and math.h to just #include. It compiles just fine after that. Not sure about the long term ramifications of doing that though, so perhaps either of your solutions would be better...

**Comment by Sukid** [comment]
True! Well that answer's that. That would be more of a wine problem than anything. Alrighty then!
