### ISSUE TITLE
Unity Adam 2016 tech demo fails to load

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#80]
this is also another graphical intensive Unity tech demo (using 5.4.0) presumed to be state of the art at end of 2016 of graphics in Unity..

### Software information
see
https://blogs.unity3d.com/es/2016/11/01/adam-demo-executable-and-assets-released/
http://unity3d.com/adam-standalone

### System information
- GPU: vega
- Driver: latest
- Wine version:  no
- DXVK version: latest

### Log files
[Adam_d3d11amd.log](https://github.com/doitsujin/dxvk/files/1726379/Adam_d3d11amd.log)
[Adam_dxgiamd.log](https://github.com/doitsujin/dxvk/files/1726380/Adam_dxgiamd.log)

interesting I see lots of uncommon error in dxgi:
err:   DxgiAdapter: No format mapping for -1

also on d3d11 lots of:
err:   D3D11: Unsupported format: 4294967295
and:
err:   D3D11Device: CheckFeatureSupport: Unknown feature: 10
err:   D3D11Device: CheckFeatureSupport: Unknown feature: 15
err:   DxbcCompiler: Invalid sampled type: DxbcResourceReturnType::Unorm

and of course needs tesselation..

**Comment by doitsujin** [comment]
Works for me on RADV. Keep in mind that compiling shaders etc. can take several minutes, as long as there's some CPU load, the demo is actually doing something.

**Comment by doitsujin** [comment]
I fixed a bunch of bugs and crashes, the demo gets a bit further now but it requires stream output (see #135). Closing the issue for that reason.
