### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by JamesChenChina** [doitsujin/dxvk#800]
1. Does wine+dxvk support ubuntu server (e.g. Ubuntu server 16.04)?
2. Does wine+dxvk support NVIDIA Tesla GPU or Quadro NVS series GPU? e.g. Nvidia Tesla v100, Quadro NVS315

Thanks a lot

**Comment by doitsujin** [comment]
1: No.
2: Don't know, depends on whether those cards have Vulkan support.

**Comment by Tele42** [comment]
Tesla generation nVidia cards are DX10 / GL 3.3 capable hardware and will never support Vulkan.

**Comment by dlove67** [comment]
@Tele42 You're confused, Nvidia makes Tesla cards that are for supercomputing. The V100 is a Volta generation card: https://www.nvidia.com/en-us/data-center/tesla-v100/

**Comment by Guy1524** [comment]
There is nothing stopping DXVK from working on Ubuntu server 16.04

**Comment by barni2000** [comment]
1. Afaik Ubuntu Server has same repositories.
2. https://developer.nvidia.com/vulkan-driver

**Comment by JamesChenChina** [comment]
@doitsujin Could you please tell us why wine+dxvk doesn't support ubuntu server in more detail?
In other words, what should I install in ubuntu server so that I can make wine+dxvk work on it

**Comment by JamesChenChina** [comment]
@Tele42  Could you please show me official announce that Tesla generation nVidia cards will never support Vulkan? Thank you so much

**Comment by dlove67** [comment]
@Jameschenchina @Tele42 was confused and thinking Tesla *generation*: https://en.m.wikipedia.org/wiki/Tesla_(microarchitecture) instead of Tesla the *HPC product*: https://en.m.wikipedia.org/wiki/Nvidia_Tesla
