### ISSUE TITLE
Battlefield V doesn't start

### ISSUE THREAD

**Issue by acteru** [doitsujin/dxvk#807]
### Software information
I installed Battlefield V with the lutris script: https://lutris.net/games/battlefield-v/ , origin and download worked fine. The Game loads ink. cloud-sync but crashes after this step right away no errors found in the logs so far.

### System information
- OS: 4.19.4-arch1-1-ARCH
- GPU: GTX 1080
- Driver: 415.22
- Wine version: tkg-protonified-3.21-x86_64
- DXVK version: 0.93

### Log files
- d3d11.log: no file
- dxgi.log: 
```
info:  Game: bfv.exe
info:  DXVK: v0.93
warn:  OpenVR: Failed to locate module
01ff:fixme:ntdll:NtQueryInformationJobObject stub: 0x62c 1 0x19c8fdc4 48 (nil)
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  GeForce GTX 1080:
info:    Driver: 415.22.0
info:    Vulkan: 1.1.84
info:    Memory Heap[0]: 
info:      Size: 8192 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 11981 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
000d:fixme:file:FindFirstFileExW flags not implemented 0x00000002
DEBUG    2018-12-09 23:01:30,365 [thread]:Processes monitored: Origin.exe (14605:S), Origin.exe (14605:S), OriginClientSer (14680:S), QtWebEngineProc (14847:S), QtWebEngineProc (14875:S), bfv.exe (24268:R)
0009:fixme:netprofm:list_manager_GetConnectivity 0x1160fc00, 0x32c060
016d:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
DEBUG    2018-12-09 23:01:36,365 [thread]:Processes monitored: Origin.exe (14605:S), Origin.exe (14605:S), OriginClientSer (14680:S), QtWebEngineProc (14847:S), QtWebEngineProc (14875:S)
016d:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0009:fixme:netprofm:list_manager_GetConnectivity 0x131092e8, 0x32c060
0009:fixme:netprofm:list_manager_GetConnectivity 0x1307ff70, 0x32c060
```

**Comment by doitsujin** [comment]
What makes you think this is a DXVK bug? The game doesn't even initialize D3D11 if it crashes that early.

**Comment by acteru** [comment]
I guess the tunnel vision while searching to find the error. You got a good point there with D3D11, it seems that there is no DirectX present in: drive_c/Program Files (x86)/Origin Games/Battlefield V/__Installer as it should be, sorry for the disturbance.

**Comment by beyimanman** [comment]
How do u solve this?

**Comment by beyimanman** [comment]
> I guess the tunnel vision while searching to find the error. You got a good point there with D3D11, it seems that there is no DirectX present in: drive_c/Program Files (x86)/Origin Games/Battlefield V/__Installer as it should be, sorry for the disturbance.

how do u solve this error? i managed to can play bfv in linux after yesterday...i formated my linux partition and install xubuntu and do exact the same thing that in fedora (install lutris, vulkan, libmesa, install bfv script and install the game in origin) and doesnt work at all :/

**Comment by beyimanman** [comment]
i have this output in lutris -d

info:    Driver: 18.99.99
info:    Vulkan: 1.1.70
info:    Memory Heap[0]: 
info:      Size: 3840 MiB
info:      Flags: 0x1
info:      Memory Type[0]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 256 MiB
info:      Flags: 0x1
info:      Memory Type[2]: Property Flags = 0x7
info:    Memory Heap[2]: 
info:      Size: 4096 MiB
info:      Flags: 0x0
info:      Memory Type[1]: Property Flags = 0x6
info:      Memory Type[3]: Property Flags = 0xe
warn:  DXGI: VK_FORMAT_D24_UNORM_S8_UINT -> VK_FORMAT_D32_SFLOAT_S8_UINT
info:  Game: bfv.exe
info:  DXVK: v0.93
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  AMD RADV POLARIS10 (LLVM 7.0.1):
DEBUG    2018-12-10 16:49:02,838 [thread]:Processes monitored: Origin.exe (4937:S), QtWebEngineProc (5311:R), Origin.exe (4937:S), bfv.exe (9267:S), OriginClientSer (5035:S), QtWebEngineProc (5275:S)
DEBUG    2018-12-10 16:49:04,845 [thread]:Processes monitored: Origin.exe (4937:S), QtWebEngineProc (5311:S), Origin.exe (4937:S), bfv.exe (9267:R), OriginClientSer (5035:S), QtWebEngineProc (5275:S)
DEBUG    2018-12-10 16:49:06,834 [thread]:Processes monitored: Origin.exe (4937:S), QtWebEngineProc (5311:S), Origin.exe (4937:S), OriginClientSer (5035:S), QtWebEngineProc (5275:S)

**Comment by acteru** [comment]
hm yes looks like you got the same problem, i tried the install script on almost the same hardware on ubuntu 18.04 and got the same issue. When installing another game within origin directx shows up in the agreement to install the game, but that's not the case with battlefield v, maybe this is just an error with origin that the packages are not present. Would be interesting to know if this is the also case on windows too. There was a comment under "BF1" https://lutris.net/games/battlefield-1/ that describes the same behavior. 

> The version of this installer which I used about 2 weeks ago worked just fine, the updated one no longer works properly on my system. The game tries to start but never shows anything on screen and the process (bf1.exe) crashes after a few seconds. Trying a different WINE and DXVK versions didn't make any difference. I am running a AMD Radeon Vega 64 with MESA 18.2.6-1 on Arch Linux. 

to come back to your question: unfortunately, I could not find a solution to the problem yet, but i keep searching

**Comment by beyimanman** [comment]
> hm yes looks like you got the same problem, i tried the install script on almost the same hardware on ubuntu 18.04 and got the same issue. When installing another game within origin directx shows up in the agreement to install the game, but that's not the case with battlefield v, maybe this is just an error with origin that the packages are not present. Would be interesting to know if this is the also case on windows too. There was a comment under "BF1" https://lutris.net/games/battlefield-1/ that describes the same behavior.
> 
> > The version of this installer which I used about 2 weeks ago worked just fine, the updated one no longer works properly on my system. The game tries to start but never shows anything on screen and the process (bf1.exe) crashes after a few seconds. Trying a different WINE and DXVK versions didn't make any difference. I am running a AMD Radeon Vega 64 with MESA 18.2.6-1 on Arch Linux.
> 
> to come back to your question: unfortunately, I could not find a solution to the problem yet, but i keep searching

[ ](url

OK, very thank you for the help, please let me know if u have any advanced..i think that is posible to get the previus script on lutris but i dont know how, do you? i will looking for that

**Comment by beyimanman** [comment]
> hm yes looks like you got the same problem, i tried the install script on almost the same hardware on ubuntu 18.04 and got the same issue. When installing another game within origin directx shows up in the agreement to install the game, but that's not the case with battlefield v, maybe this is just an error with origin that the packages are not present. Would be interesting to know if this is the also case on windows too. There was a comment under "BF1" https://lutris.net/games/battlefield-1/ that describes the same behavior.
> 
> > The version of this installer which I used about 2 weeks ago worked just fine, the updated one no longer works properly on my system. The game tries to start but never shows anything on screen and the process (bf1.exe) crashes after a few seconds. Trying a different WINE and DXVK versions didn't make any difference. I am running a AMD Radeon Vega 64 with MESA 18.2.6-1 on Arch Linux.
> 
> to come back to your question: unfortunately, I could not find a solution to the problem yet, but i keep searching

[ ](url

OK, very thank you for the help, please let me know if u have any advanced..i think that is posible to get the previus script on lutris but i dont know how, do you? i will looking for that

**Comment by beyimanman** [comment]
im created a topic in lotrus forum
https://forums.lutris.net/t/battlefield-1-and-v-doesnt-start-with-new-installation-script/4482
