### ISSUE TITLE
Tekken 7 (Nvidia to AMD)

### ISSUE THREAD

**Issue by massatt212** [doitsujin/dxvk#808]
Is it possible to Spoof all Nvidia Cards to AMD through DXVK
Cause im dying to Play Tekken 7 without getting 30fps and 40fps
some reason Spoofing Card does not work for me
(DXVK_CONFIG_FILE=/home/arnold/.local/share/Steam/steamapps/common/TEKKEN 7/TekkenGame/Binaries/Win64/dxvk.conf %command%)
When i enter this and try to launch the Conf with the 2 lines inside the game wont load

So is it possible to Spoof all Nvidia card from your Side
and if possible please give us a side version.

**Comment by doitsujin** [comment]
This is already being done in DXVK 0.93.

**Comment by massatt212** [comment]
dang guess my GTX 960 cant pull of a 60fps on Tekken 7 on Ubuntu
Nooooooooo
thx for the quick reply

**Comment by BlazeKl** [comment]
try tweaking the nvidia control panel and your system, there is an old video of a guy playing at 60fps with a GT 1030, it may be possible to get better performance with that gpu

**Comment by doitsujin** [comment]
I'm under the impression that Pascal GPUs run much better than the older ones in general, I have a GTX 670 and it doesn't do nearly as well as it should compare to my RX 480.

**Comment by massatt212** [comment]
my RX 480 570 and 580 works soooooo sweet but my 960 makes me wanna cry

**Comment by massatt212** [comment]
i Notice in some DX9 Games or Unreal Engine 3 Games
When i turn off Rendering Threads i get so much FPS boost Maybe wine cant do it properly

**Comment by massatt212** [comment]
i got 3-4 more FPS in TEKKEN 7
Keep it up Slow and steady and Slow and Steady

**Comment by massatt212** [comment]
Sweet Sweet Another 3-5 FPS increase
Im getting 37-40 fps in Tekken 7 Arctic Stage
Come on Come ON a lil more upgraders Proton 3.16-6

**Comment by massatt212** [comment]
performance drop by 20 fps on 0.95 game running at 20fps for me again

**Comment by lieff** [comment]
Check free GPU mem (using nvidia-smi for example). Probably drops caused by using host memory.

**Comment by massatt212** [comment]
![screenshot from 2019-01-17 10-31-55](https://user-images.githubusercontent.com/43518479/51325400-35d82700-1a43-11e9-8017-25123cf49dec.png)
