### ISSUE TITLE
Some Unity games show a black screen, sometimes with HUD, logspam message about typeless subresource

### ISSUE THREAD

**Issue by roothorick** [doitsujin/dxvk#81]
Applications fail to present any 3D scene. May render some HUD elements. DXVK HUD renders, framerate counter updating, typically around 60fps. d3d11.log scrolls and scrolls with `err:   D3D11: ResolveSubresource with typeless images currently not supported`. Music can be heard, if the game plays music in its first scene.

### Software information
Affected applications include:

* Anyland
* #Archery (yes, the game name officially includes a pound sign)
* Armello
* Audioshield
* Blue Effect VR
* Conductor
* Dear Esther: Landmark Edition
* Drunkn Bar Fight
* Golf With Your Friends
* Gorn
* Hearthstone (#55)
* Keep Talking and Nobody Explodes

### System information
- GPU: Radeon RX 480
- Driver: Mesa 17.3.2
- Wine version: 2.21 (staging)
- DXVK version: git 8ebffc1

### Apitrace file(s)
These applications do not work on wined3d either; therefore I want to apitrace on native Windows, but don't have access to my Windows machine at the moment. Will update later.

### Log files
These are from Armello.
- d3d11.log: https://pastebin.com/aBYrDSYN
- dxgi.log: https://pastebin.com/RRrfG2XP

**Comment by roothorick** [comment]
Blue Effect VR appears to also be effected. It displays the DIVR logo in the bottom right and briefly shows a blue transition effect at startup, but otherwise black.

**Comment by roothorick** [comment]
I think I'll just edit the OP as I find more affected games...

**Comment by Raffarti** [comment]
#55 is also a Unity game.

**Comment by roothorick** [comment]
As of https://github.com/doitsujin/dxvk/commit/b419b3dfbda5643aa80fa67af1387be2c30eef80 all games identified as having been affected are now either working or have other problems that are clearly unrelated. So, we're good!
