### ISSUE TITLE
Wrong fallback.

### ISSUE THREAD

**Issue by artivision** [doitsujin/dxvk#810]
I noticed that DXVK is also active somehow on D3D9 games to, without taking part on them. But if DXVK fails somehow, it doesn't pass the torch to Gallium-Nine.

**Comment by Joshua-Ashton** [comment]
No.

**Comment by doitsujin** [comment]
DXVK doesn't affect D3D9 games. They don't even load the DLLs.

**Comment by doitsujin** [comment]
Okay, so the problem is not that "DXVK uses the wrong fallback", but that it doesn't catch one of its own exceptions when instance creation fails for whatever reason.

Please don't make random assumptions like that without posting any log files etc.

**Comment by Alexander88207** [comment]
> D3D9
> 
> mars@192:~/Games/Life_is_Strange/Binaries/Win32> DRI_PRIME=1 thread_submit=true wine LifeIsStrange.exe
> 000b:fixme:winediag:start_process Wine Staging 3.21 is a testing version containing experimental patches.
> 000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
> 0009:fixme:ver:GetCurrentPackageId (0x1d1e024 (nil)): stub
> 0009:fixme:gameux:GameExplorerImpl_VerifyAccess (0x1673a0, L"Z:\home\mars\Games\Life_is_Strange\Binaries\Win32\LifeIsStrange.exe", 0x1d1f5d0)
> 0009:fixme:module:load_dll Loader redirect from L"d3d9.dll" to L"d3d9-nine.dll"
> ATTENTION: default value of option thread_submit overridden by environment.
> 0009:fixme:d3d9nine:d3dadapter9_new
> Native Direct3D 9 is active.
> For more information visit https://wiki.ixit.cz/d3d9
> mesa: for the -simplifycfg-sink-common option: may only occur zero or one times!
> 0009:fixme:dxgi:DXGID3D10CreateDevice Ignoring flags 0x1.
> 0009:fixme:nvapi:unimplemented_stub function 0xbe7692ec is unimplemented!
> 0009:fixme:nvapi:unimplemented_stub function 0x6c2d048c is unimplemented!
> ATTENTION: default value of option thread_submit overridden by environment.
> 0009:fixme:d3d9nine:d3dadapter9_new
> Native Direct3D 9 is active.
> For more information visit https://wiki.ixit.cz/d3d9
> 0009:fixme:msvcrt:type_info_name_internal_method type_info_node parameter ignored
> 0009:fixme:system:SystemParametersInfoW Unimplemented action: 59 (SPI_SETSTICKYKEYS)
> 0009:fixme:system:SystemParametersInfoW Unimplemented action: 53 (SPI_SETTOGGLEKEYS)
> 0009:fixme:system:SystemParametersInfoW Unimplemented action: 51 (SPI_SETFILTERKEYS)
> 0009:fixme:wbemprox:client_security_SetBlanket 0xef25a938, 0x18d2c0, 10, 0, (null), 3, 3, (nil), 0x00000000
> 0009:fixme:wbemprox:client_security_Release 0xef25a938
> 0009:fixme:wbemprox:enum_class_object_Next timeout not supported
> 0009:fixme:d3d9nine:DRI3PresentGroup_GetMultiheadCount (0x168eb0), stub!
> 0009:fixme:d3d9nine:DRI3PresentGroup_GetMultiheadCount (0x168eb0), stub!
> 0009:fixme:d3d9nine:D3DPERF_SetOptions (0x1) : stub
> 0009:fixme:imm:ImmReleaseContext (0x7004a, 0x1adb60): stub

btw why are you playing LiS over wine if the game have a great linux port?

**Comment by artivision** [comment]
There wasn't a Linux Port when I did get the game.

**Comment by Leopard1907** [comment]
But now it has ( actually they ported it in 2016) and you can grab that game only on Steam. 

But you still use it on Wine? Doesn't make sense with only one exception...
