### ISSUE TITLE
Civilization V hangs when set to 1920x1080

### ISSUE THREAD

**Issue by Hello71** [doitsujin/dxvk#812]
steps to reproduce:
1. run CivilizationV_DX11.exe
2. set resolution to 1920x1080

expected results:
the resolution changes, and can click "OK" to continue.

actual results:
the resolution changes, and the screen repaints, but then immediately freezes. the timer is displayed but does not tick down, clicking anything has no visible effect, and the original resolution is not restored after 30 seconds.

also, starting Civ V again just hangs at the loading screen.

I have tried with and without virtual desktop; without virtual desktop, it always goes immediately to 1920x1080 and hangs at the loading screen.

### Software information
Civilization V
sway 1.0-beta.2+

### System information
- GPU: Intel Corporation HD Graphics 515 (rev 07)
- Driver: ANV (Mesa 18.3.1)
- Wine version: 4.0-rc1 staging
- DXVK version: 0.94
- Actual resolution: 1920x1080

### Apitrace file(s)
- Doesn't seem helpful, can provide on request

### Log files
- d3d11.log, dxgi.log: https://gist.github.com/Hello71/918077be5a7ccac642228f0d87a98434

**Comment by doitsujin** [comment]
I don't have the game, I need an apitrace.

**Comment by Hello71** [comment]
Sorry, it loads fine, just extremely slowly (is terrible on Windows too, but worse on Linux). Also, apparently DX9 hangs when changing resolution too; it hangs before changing, but I assume probably it is either not DXVK's fault or not worth fixing.
