### ISSUE TITLE
Path of Exile hangs system with some resolutions

### ISSUE THREAD

**Issue by morguldir** [doitsujin/dxvk#813]
If you use a resolution that has a ratio to 1080p, that is multiplicable by 1/3, and is a decimal number, the system hangs indefinietely.

These are the resolutions i tested

- Works: 640x480, 1366x766, 1920x1080, 3840x2160
- Doesn't work: 1280x720, 2560x1440, 3200x1800, 5120x2880

Also happening for people with amd gpu's here on the [PoE forums](https://www.pathofexile.com/forum/view-thread/8980/page/216#p15948939), but with slightly different results

### Software information
- Path of Exile

### System information
- GPU: Nvidia GTX 1080
- Driver: 415.22
- Wine version: tkg-3.21 (Needed for game launch in dx11)
- DXVK version: 0.94 (master at time of writing)

### Apitrace file(s)
- Path of Exile needs to be run in a 64-bit wineprefix to support dx11, which seems to break apitrace

### Log files
- d3d11.log: [PathOfExile_x64Steam_dxgi.log](https://github.com/doitsujin/dxvk/files/2683279/PathOfExile_x64Steam_dxgi.log)
- dxgi.log: [PathOfExile_x64Steam_d3d11.log](https://github.com/doitsujin/dxvk/files/2683280/PathOfExile_x64Steam_d3d11.log)

**Comment by doitsujin** [comment]
I'm aware of this, but I have no idea how to debug it.

Apitrace has a 64-bit version, it doesn't break, you just need to use the correct version.

**Comment by Jrugia** [comment]
I've tried this on my system, I don't have a 1440p but setting Wine's virtual desktop to a 2560x1440 lets me set the res in games. My system didn't hang but it became very slow, so much that the seconds on the clock where being updated every 4 seconds. I managed to close the game through X-Server Restart by Ctrl+Alt+Backspace (which also took a long time to restart) or using SSH.

I managed to capture an apitrace using Wine's D3D11. I've changed the game's resolution back and forth from 2560x1440 to 1080p and back to 2560x1440 while doing it. Hopefully it helps.

**Apitrace file(s)**

https://drive.google.com/file/d/1FAbc3prMVxtcpdCrQ_oT6spZ96c0z-Mc

**Comment by BartWillems** [comment]
On KDE with Xorg, my system also froze, but when I'm running gnome with gdm (both on wayland), I get kicked out of my gnome session. Maybe using a setup like this could help debugging the problem?

I'll see if I can get some stacktraces some time.

**Comment by evilch3n** [comment]
this is the most annoying bug at the moment, i wish i could go for a 21:9/1440p style resolution but it won't work

the system starts using 1 core to 100% thats why it hangs for most people, when i try to change my reso. poe just stays black and my tabbing out to kill the process takes 4-5 seconds but it does not crash entirly.

@doitsujin do you have some ideas what could need this special 1/3 multiplicable thing? maybe we can find a solution

**Comment by efirps** [comment]
Also having this same problem with 0.96 release and wine 4.0 rc5 staging. Everything slows and eventually completely locks up the PC with 1440p. 1080p runs, but obviously looks terrible. Has anyone found a workaround?

**Comment by quirxmode** [comment]
It would really be awesome if this issue was fixed. I can only play on the weirdest, most inconvenient resolutions...

**Comment by doitsujin** [comment]
@quirxmode I'm sure it would be, but your comment contributes exactly **nothing** to the solution **at all**.

**Comment by brandonegbert** [comment]
Should 87dc472 fix the issue allowing the game to run or just prevent the system from hanging?

**Comment by doitsujin** [comment]
It's a correct fix for the issue, the game does run with it.

**Comment by aufkrawall** [comment]
I could just play for half an hour without issues with it in 1440p & radv. I suppose this could convert some more players to play on Linux. :)
