### ISSUE TITLE
Lighting issues in multiple games

### ISSUE THREAD

**Issue by YuriNenakhov** [doitsujin/dxvk#814]
Several games have lighting artifacts when run with DXVK. Lighting and shadow effects appear or disappear on-screen depending on which angle you observe them at.

The Evil Within 2:
https://youtu.be/Jq9bIhjpvMI

Prey (2017):
https://youtu.be/HxKy8Rx5bX0

Tested with:
 * DXVK 0.94
 * Nvidia 415.23
 * Wine 3.21 (lutris-tkg)

**Comment by doitsujin** [comment]
Is that a regression (i.e. does it work with 0.93?) Can you please not ignore the issue template and record apitraces?

I can' t do anything with bug reports like this.

**Comment by YuriNenakhov** [comment]
Apitrace for The Evil Within 2:
https://drive.google.com/file/d/1PVYbciUv1YUhDPg5DXjZSRzq-27_U_ui/view?usp=sharing

Glitch in Prey seems to be not a DXVK's fault, it's present in wined3d as well. Sorry about that.

**Comment by doitsujin** [comment]
Is there any video showing how TEW2 is supposed to look like on Windows? I've taken a closer look at the apitrace but I can't find anything that DXVK would be doing wrong.

**Comment by Lyle-Tafoya** [comment]
I experienced a similar issue when playing with certain shadow settings in GTA V after updating from nvidia 396.54.09 vulkan beta drivers to 415.x.x. If you have an easy way to test out the 396 vulkan beta drivers, I would give that a shot and see if it solves your issue. If it does, maybe share this info over here: https://devtalk.nvidia.com/default/topic/1044857/linux/regression-with-vulkan-beta-driver-415-18-causes-shadow-rendering-issues-in-gta-v/

It very well may be an entirely different issue though.

**Comment by doitsujin** [comment]
Closing due to lack of feedback.

@Lyle-Tafoya GTA V problems are likely unrelated.
