### ISSUE TITLE
The Epic Games launcher flickers when mouse moving, just black screen if I doing nothing.

### ISSUE THREAD

**Issue by Kerrung** [doitsujin/dxvk#817]
Flickering when mouse moving, just black screen if I doing nothing: 
[epic-games-launcher-flickering-when-mouse-moving_2018-12-18 01:33:06.125336.mkv](https://github.com/doitsujin/dxvk/files/2687888/epic-games-launcher-flickering-when-mouse-moving_2018-12-18.01.33.06.125336.zip)

Seems like don't happens with Nvidia GPUs: https://www.youtube.com/watch?v=dDYeewMTPTg

### Software information
Epic Games launcher, default settings used etc.

### System information
- OS: Arch Linux
- GPU: AMD Radeon HD 7850
- Driver: [mesa-git-19.0.0_devel.106290.9add63a3a5](https://gitlab.freedesktop.org/mesa/mesa/commit/9add63a3a5600d96d96640320706dd2491b9bd64)
- Wine version: [wine-tkg-git](https://github.com/Tk-Glitch/PKGBUILDS)
- DXVK version: 92f3648

### Apitrace file(s)
Unfortunately, I could not write apitrace because the *.trace file does not appear after closing the Epic Games application. I guess it happens because I'm doing something wrong. I run this command:
https://pastebin.com/BAhHVBRK

### Log files
[EpicGamesLauncher_d3d11.log](https://github.com/doitsujin/dxvk/files/2687858/EpicGamesLauncher_d3d11.log)
[EpicGamesLauncher_dxgi.log](https://github.com/doitsujin/dxvk/files/2687859/EpicGamesLauncher_dxgi.log)

**Comment by doitsujin** [comment]
How do I get the launcher to work? It doesn't even start on my end.

**Comment by Kerrung** [comment]
@doitsujin see comments here: https://www.youtube.com/watch?v=dDYeewMTPTg
Same happens with wined3d too.

**Comment by doitsujin** [comment]
Doesn't look like my bug. The software just doesn't render anything most of the time, and it also doesn't use the DXGI present flags to partially update image regions.

**Comment by Kerrung** [comment]
And so tell me please, whose bug is it, that is, where should I write a bug report?

**Comment by Jrugia** [comment]
Since it happens with wined3d, then it's definitely not a DXVK bug.

Can you try with your desktop Compositor disabled?

**Comment by Kerrung** [comment]
GNOME can't disable compositor...

**Comment by Jrugia** [comment]
> GNOME can't disable compositor...

Maybe this might help?:
https://askubuntu.com/questions/969073/how-can-i-disable-the-compositor-gnome-shell-mutter-on-fullscreen-windows

Not very good with GNOME myself sorry.

**Comment by doitsujin** [comment]
@Kerrung I don't know whose bug that is.

**Comment by Kerrung** [comment]
>Maybe this might help?:
> https://askubuntu.com/questions/969073/how-can-i-disable-the-compositor-gnome-shell-mutter-on-fullscreen-windows

"on fullscreen windows", but Epic Games application is not a fullscreen window.

**Comment by Kerrung** [comment]
> @Kerrung I don't know whose bug that is.

@doitsujin ok, thank you.

**Comment by xDShot** [comment]
Launch it with `-opengl` parameter so it doesn't flicker
