### ISSUE TITLE
X4 Foundations dont show menutext . Cant start the game. 

### ISSUE THREAD

**Issue by davvvve1** [doitsujin/dxvk#818]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Name of the game, settings used etc.

### System information
- GPU:
- Driver:
- Wine version: 
- DXVK version: 

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log:

**Comment by davvvve1** [comment]
Software information
Name of the game, settings used etc.

System information
GPU:Amd RX580
Driver:Opensource latest mesa
Wine version:wine-staging 4.0-rc1
DXVK version:094
Apitrace file(s)
Put a link here
Log files
d3d11.log:
dxgi.log:

And for me to start the game , ill need to press alt+enter after the spalsh screen when loading screen appears . I think the game use vulkan so maby it isnt DXVK fault .

**Comment by doitsujin** [comment]
This is a native Vulkan game, do DXVK has nothing to do with it. If you're using Proton, there's already a bug report [here](https://github.com/ValveSoftware/Proton/issues/2045).
