### ISSUE TITLE
Vulkan version reported by the HUD?

### ISSUE THREAD

**Issue by shmerl** [doitsujin/dxvk#819]
Why is HUD always reporting Vulkan version as 1.1.70 (at least in case of radv) despite actual version being higher? What is the source of the actual value?

**Comment by doitsujin** [comment]
The HUD shows the value returned in the `VkPhysicalDeviceProperties` struct. This was changed in radv yesterday to show 1.1.90 instead of 1.1.70.

**Comment by shmerl** [comment]
Ah, I thought it was changed [here](https://gitlab.freedesktop.org/mesa/mesa/blob/master/src/amd/vulkan/radv_extensions.py#L34) a bit earlier, so I was surprised it didn't come up.

**Comment by shmerl** [comment]
Oh, I see [it wasn't being propagated](https://gitlab.freedesktop.org/mesa/mesa/commit/445867c80d5363a60bc17e4beff6016c8c9b5221) indeed.
