### ISSUE TITLE
Path of Exile - crash on start

### ISSUE THREAD

**Issue by jmis** [doitsujin/dxvk#82]
### Software information
Path of Exile - 64bit w/csmt

### System information
- GPU: GeForce GTX 970
- Driver: 390.25
- Wine version:  wine-2.21 (Staging)
- DXVK version:  8ebffc1018173903b4bfaf41561fb9bd2b006f74
- Distro:	Ubuntu 16.04.3 LTS

### Apitrace file(s)
- Not sure how to do this

### Log files
- d3d11.log: https://pastebin.com/m7wBCDYm
- dxgi.log: https://pastebin.com/TybbDR7r
- wine: https://pastebin.com/RwcMG7DF

### Notes

I had to compile from source to add a CoInitialize(NULL) call.  Here's a thread from winehq about the fix:

https://bugs.winehq.org/show_bug.cgi?id=42695

**Comment by doitsujin** [comment]
See #93.
