### ISSUE TITLE
dxvk dlls cant loading from wineprefix/drive_c/windows/system32 and syswow64

### ISSUE THREAD

**Issue by andysendo** [doitsujin/dxvk#825]
### Software information
x86_64 bit wine-staging 3.21  lutris wine 3.15  precompiled binary  

### System information
- OS: debian9 stable kernel 4.18
- GPU: intel+nvdia
- Driver:mesa 18.2 + intel opensource + nvidia driver
- Wine version: 3.xx
- DXVK version: 0.94 

i decompress wine binary to /tmp/wine, witch contains bin,lib,lib64,share. i always use wine that way including myself compile version. then copy x32 and x64 dlls to wineprefix/.../system32 and syswow64, set env WINEARCH=win32 or win64; WINEDLLOVERRIDES="dxgi,d3d11,d3d10,d3d10_1,d3d10core=n" to test wine dxvk game, but can not found and load the dxvk dll. only i copy the dlls to game exe directory runs ok.

i copy native d3dx9_xxx.dll to wineprefix/../system32 and set env WINEDLLOVERRIDES for testing some dx9 game, its ok.

so in my case dxvk dll cant load from wineprefix?

**Comment by doitsujin** [comment]
It works fine that way if you just follow the instructions in the readme.
