### ISSUE TITLE
Wrong monitor refresh rate.

### ISSUE THREAD

**Issue by artivision** [doitsujin/dxvk#827]
Good day. DXVK sets by itself my monitor's refresh rate to the maximum (120hz). Why please???

**Comment by doitsujin** [comment]
And why is that an issue?

**Comment by artivision** [comment]
You may not now this but fast monitors need precise synchronization to work correctly. For example if you run any 60/120fps stable (like FFXV) or any Variable-fps game on a 144hz monitor with or without Vsync, you will feel like you only get 15fps. Yes is that of a mess without Freesync or something similar. I'm very lucky because my monitor's menu allows me to lock it at 120hz so Vsync works perfect if the game have 60/120fps stable. One with only 144hz will be out of luck until Kernel_4.21. Also wile starting FFXV, DXVK asks for the highest 144hz except if i configure the monitor for 120hz.

**Comment by doitsujin** [comment]
I don't understand why you think this is a DXVK bug. Games either allow you to select the refresh rate manually or ask for the highest available refresh rate, which is 144 Hz in your case.

**Comment by elovin** [comment]
@artivision You mean that the FPS are locked at 120fps event without VSYNC ?

**Comment by doitsujin** [comment]
@elovin are you on Wayland? Locked frame rate when games use double-buffering is a known limitation of XWayland, see #806.

**Comment by elovin** [comment]
@doitsujin Hm no im sill using X11, I might have time to look into it within the next few days, if anything useful comes up I will open an issue

**Comment by doitsujin** [comment]
Weird, I don't have that problem on KDE.

**Comment by shmerl** [comment]
@elovin: Do you have such problem with everything or just with one game? It could be a game specific issue.

**Comment by artivision** [comment]
Ok problem solved. People with Amd Gpus, Mesa and fast monitors, should disable Tear_Free. This just destroys Games. If your compositor does that then disable it or change compositor. I now use Xfce with default compositor and simple Vsync and i'm fine. Compton Glx back-end and similar is what you shouldn't use.
