### ISSUE TITLE
Please remove winetricks completely!

### ISSUE THREAD

**Issue by greencopper** [doitsujin/dxvk#828]
Winetricks is notoriously messed up regarding "ProgramFiles returned empty string" issues that has persisted since 2015 https://github.com/Winetricks/winetricks/issues/163

Under "How to use" (DXVK) it currently lists "winetricks --force" etc. as the solution for DXVK.

This is also related to: https://github.com/doitsujin/dxvk/issues/573

I have just moved all my wine folders from a Manjaro box to an Arch box and now I manually have to delete every single wine installation (there is a lot) because winetricks is still suffering from the old "ProgramFiles returned empty string" issue. I then manually have to update every single wine installation.

Please remove the winetricks dependency as it breaks everything!

**Comment by massatt212** [comment]
i wish they make 32 and 64bit in 1 prefix
that will solve almost every problem

**Comment by greencopper** [comment]
I have made a temporary hack that runs through all my wine directories and deletes wine without deleting the installed applications, when updating DXVK the annoying winetricks "empty string" issue is avoided:

```
rm -rf $WINEDIR/dosdevices
rm $WINEDIR/.update-timestamp
rm $WINEDIR/system.reg
rm $WINEDIR/user.reg
rm $WINEDIR/userdef.reg
rm $WINEDIR/winetricks.log
rm -rf $WINEDIR/drive_c/windows
```

Where "WINEDIR" is the relevant Wine directory.

**Comment by doitsujin** [comment]
@greencopper I won't change the way to install DXVK **again** unless someone comes up with a solution that is better in every single use case. If you have trouble with winetricks, maybe report a bug there.

@massatt212 what do you mean? The default is to have a 64-bit prefix in which you can install 32-bit applications.

**Comment by greencopper** [comment]
It shouldn't have been changed in the first place! Making it dependent upon winetricks doesn't make sense as winetricks isn't a part of Wine and really has nothing to do with it per say.

**Comment by Bfgeshka** [comment]
winetricks is not a dependency really. If it is hard to update via winetricks, then just update dxvk manually, there's nothing hard to it - it only requires a simple file replacement, there's no need to delete all your prefixes because of it.

**Comment by greencopper** [comment]
Then what's the point with winetricks in the first place?!

**Comment by doitsujin** [comment]
@greencopper then please go ahead and find a better way to install DXVK without the winetricks verb which doesn't introduce any new problems.

The winetricks verb was added after some discussion on #569.

**Comment by greencopper** [comment]
But you are completely ignoring the problems with Winetricks! https://github.com/doitsujin/dxvk/issues/828

As long as this long standing issue from 2015 isn't resolved, using Winetricks for DXVK isn't a solution.
