### ISSUE TITLE
Space Engineers hangs on main menu

### ISSUE THREAD

**Issue by Zemogiter** [doitsujin/dxvk#829]
The game crashes in random places inside main menu. FPS counter locks at 120 or 119,9. After a while I get the Ubuntu's "Application is unresponsive" popup.

### Software information
Space Engineers, medium graphics preset, installed dotnet461, vcrun2015 and xact to get this game to launch. Using 64-bit wineprefix since 32bit is no longer supported. Using the latest version of PlayOnLinux 4 for debug log.
### System information
- GPU: GTX 1070
- Driver: 415.25
- Wine version: 4.0-rc3
- DXVK version: master but also tested on 0.94, same result

### Apitrace file(s)
Launched POL terminal, cd to the directory of steam .exe file but upon executing the command `apitrace trace --api=gl Steam.exe steam://rungameid/244850` I get this error:
```
apitrace: loaded into /usr/bin/apitrace
apitrace: unloaded from /usr/bin/apitrace
error: failed to execute: Steam.exe steam://rungameid/244850
```

### Log files
- d3d11.log:
[SpaceEngineers_d3d11.log](https://github.com/doitsujin/dxvk/files/2707050/SpaceEngineers_d3d11.log)
- dxgi.log: 
[SpaceEngineers_dxgi.log](https://github.com/doitsujin/dxvk/files/2707054/SpaceEngineers_dxgi.log)
PlayOnLinux log:
[playonlinux.log](https://github.com/doitsujin/dxvk/files/2707061/playonlinux.log)

**Comment by Oschowa** [comment]
You basically tried to record an opengl apitrace of windows steam, which probably uses directx, and would be useless anyways.
Try to do it as described in the [wiki](https://github.com/doitsujin/dxvk/wiki/Common-issues#apitrace).

**Comment by doitsujin** [comment]
Does it work with wined3d (i.e. without dxvk)?

**Comment by Zemogiter** [comment]
@doitsujin it does not work without dxvk. It works on Windows with dxvk. But after I disabled steam overlay the game no longer crashes on main menu but instead when actually playing. 
@Oschowa I've tried to use it with `--api=dxgi` but it gave me "unsupported API" error. I've downloaded those .dll files into Steam directory and it made no difference.

**Comment by K0bin** [comment]
You have to put the apitrace dlls into the directory of the game, right next to the .exe file. That's also where it's gonna put the .trace files after you're done.

**Comment by Zemogiter** [comment]
OK I've got the trace file.
https://www.mediafire.com/file/287rejpbwlb4j26/SpaceEngineers.trace/file
[SpaceEngineers_d3d11.log](https://github.com/doitsujin/dxvk/files/2707610/SpaceEngineers_d3d11.log)
[SpaceEngineers_dxgi.log](https://github.com/doitsujin/dxvk/files/2707611/SpaceEngineers_dxgi.log)

**Comment by exolyte** [comment]
Looks like someone got it to work on wine with some work and some in-game issues.
https://www.reddit.com/r/linux_gaming/comments/acrpnp/space_engineers_works_in_steam_proton_with_major/

**Comment by doitsujin** [comment]
According to [reddit](https://www.reddit.com/r/linux_gaming/comments/avhyxj/space_engineers_finally_playable_on_linux/), this game works now.
