### ISSUE TITLE
The Witcher 3 Texture Flickering

### ISSUE THREAD

**Issue by linuxwrper** [doitsujin/dxvk#831]
Certain terrain flickers. Ground/earth on side of grass planes and mountains/rocks. Plants and other greenery seem to be unaffected. 

![f2](https://user-images.githubusercontent.com/46094798/50402997-5e9a3300-079b-11e9-898d-7590368eef01.png)

Also uploaded video clips and more pictures showing the issue to Firefox send (limited to 24hours, will renew link when necessary):
https://send.firefox.com/download/603dd3311b/#ghj0LzAff2ffInpu6hmBpQ
The clips show the issue best

### Software information
Witcher 3 Wild Hunt
Vsync: On
Resolution: 1920 x 1080
FPS limit: 60
Everything else set to Ultra with exception of:
Detail Level: High
Shadow Quality: medium

Ran the game through Proton 3.16-6 Beta. Had the issue with non beta.
GPU: RX 580 Nitro+ 4GB
`INTEL-MESA: warning: Haswell Vulkan support is incomplete
        deviceName     = Intel(R) Haswell Desktop
        deviceName     = AMD RADV POLARIS10 (LLVM 8.0.0)
`

`server glx vendor string: SGI
server glx version string: 1.4
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
OpenGL vendor string: X.Org
OpenGL renderer string: Radeon RX 580 Series (POLARIS10, DRM 3.27.0, 4.19.11-041911-generic, LLVM 8.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.0.0-devel - padoka PPA
OpenGL core profile shading language version string: 4.50
OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.0.0-devel - padoka PPA
OpenGL shading language version string: 4.50
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.0.0-devel - padoka PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
`

Attempts at finding the cause of the issue:
- Installed kernel 4.19, was at 4.15 prior to installation. No effect
- Toggled graphic settings on and off (vsync, window mode, etc) to see if flicker stopped. Only changing Texture quality had a impact but the issue of things not rendering was still prevalent.

**Comment by Oschowa** [comment]
This looks very much like [this](https://bugs.freedesktop.org/show_bug.cgi?id=108935) llvm regression which has recently been fixed. Try again with llvm7 or wait until your ppa updates llvm to the revision which contains the fix.

**Comment by K0bin** [comment]
You opened the same issue twice. #830

**Comment by doitsujin** [comment]
This is a known LLVM bug, if you use LLVM 8.0 then please update your LLVM.

**Comment by linuxwrper** [comment]
> This is a known LLVM regression as @Oschowa said, please update to the latest revision.

Ty. I will wait for update.
