### ISSUE TITLE
DXVK 0.94 triggers anti-cheat on League Of Legends. 

### ISSUE THREAD

**Issue by Kreyren** [doitsujin/dxvk#835]
DXVK 0.94 (other versions not tested) triggers anti-cheat in League Of Legends after champion select.

Game is working on platinum with `corefonts adobeair vcrun2008 vcrun2017 winxp glsl=disabled`, but it has performance issues that can be improved using gallium9.

Afaik game also supports DirectX10/11 and would benefit greately from DXVK.

Game requires Wine-staging or patches from https://appdb.winehq.org/objectManager.php?sClass=version&iId=36323 to pass anti-cheat.

### Software information
https://paste.pound-python.org/show/mPFnWD2uKnRXu3wovN84/

### System information
- GPU: AMD7870
- Driver: AMDGPU
- Wine version: WINE-4.0-rc3
- DXVK version: 0.93

### Steps to reproduce:
Invoke `WINEPREFIX="<path>" winetricks corefonts adobeair vcrun2008 vcrun2017 win7 glsl=disabled dxvk` 

Download the game from https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20EUNE.exe

Run the installer using `WINEPREFIX="<path>" wine installer.exe`

Wait for launcher to update, then change region (if needed) and log-in.

Start a practice tool, select champion, lock and wait for error message.

*will provide more info on demand, not sure what info is helpful*

**Comment by doitsujin** [comment]
As far as I'm aware, this game **doesn't** support D3D11, so installing DXVK is useless.

Anyway, circumventing anti-cheat is not something I can do, especially in a game that doesn't even *use* DXVK.

**Comment by Leopard1907** [comment]
https://www.reddit.com/r/leagueoflegends/comments/7m6am1/why_does_league_use_dx9_when_its_over_a_decade_old/

**Comment by Kreyren** [comment]
@doitsujin i was told by a rioter that League Of Legends supports DirectX 10/11/12 https://i.imgur.com/a8r3eBH.png

About anti-cheat Riot's Anti-cheat engineer 0xNemi  (https://twitter.com/0xnemi?lang=en) publicly stated that Riot Games will cooperate with WINE developers unofficialy https://www.reddit.com/r/leagueoflinux/comments/904ofh/new_patch_new_problems_for_wine_users/e2v5irl afaik they ware the one who provided the patches to wine-staging i believe that they would help with DXVK implementation. 

Meaning that none would circumvent anti-cheat, but rather provided (un)official implementation.

Is that sufficient to allow work on the DXVK for League Of Legends?

**Comment by Laaas** [comment]
From my experience, you can play LoL without triggering the anti-cheat. I did not take any particular steps, I merely used the Lutris version without PBA.

**Comment by Laaas** [comment]
@Kreyren he's saying that LoL uses D3D9 AFAIU.

**Comment by Kreyren** [comment]
@Laaas I can confirm that League Of Legends is working on platinum with mensioned workarounds on my system excluding performace hit from using OpenGL/Gallium9.

**Comment by kassindornelles** [comment]
**League of Legends works perfectly** on Wine with DGVoodoo2 + DXVK, i don't know what you did with your prefix but something is wrong.

**Comment by doitsujin** [comment]
@Kreyren the game does not use D3D11, otherwise you would be using it already. It is D3D9 only. The reply you got probably just means that the game is **compatible** with systems that also support D3D10/11.

Also, DXVK should have absolutely nothing to do with any sort of anti-cheat technology, **unless**
1. DXVK misbehaves on the D3D11 level and the game detects that somehow
2. the game checks whether the DLLs are signed.

But point 1 would require the game to use D3D11 in the first place, and if point 2 was true, the game wouldn't work on wine at all, so... :woman_shrugging:

**Comment by kassindornelles** [comment]
@Kreyren like doitsujin said, this game is D3D9, but you can make it run with DXVK using DGVoodoo2 (D3D9 -> D3D11).
About the anticheat issue, you need to use a recent Wine Stable (or Staging, dev) version and set the Windows version to Windows XP.

**Comment by massatt212** [comment]
I think lol got a dx11 upgrade not sure I'm thinking about smite but I'll download and take a look and report back

**Comment by Kreyren** [comment]
i've just noticed that i've forgott to sent the message.. Resending:

=== 

League Of Legends support confirmed that it's DX9 only, my fault then.. it seems that rioters are confused about DXVK since DirectX 10+ is able to run DirectX9.. tbh it confuses me too shoudn't DXVK be able to run DirectX the same way as DirectX 10+ ?

Doing reseach on DGVoodoo2 so far with no success, game is working on gallium9 tho.

**Comment by Kreyren** [comment]
@doitsujin Thanks for info
