### ISSUE TITLE
Does Wine+DXVK support FiveM?

### ISSUE THREAD

**Issue by JamesChenChina** [doitsujin/dxvk#836]
Does Wine+DXVK support FiveM on Ubuntu16.04 now?
FiveM is a modification for Grand Theft Auto V enabling you to play multiplayer on customized dedicated servers.
https://fivem.net/
https://forum.fivem.net/t/windows-7-support-dropped/14957
https://forum.fivem.net/t/linux-game-client/67676/14
https://forum.fivem.net/t/request-fivem-linux-client/182056/6

**Comment by doitsujin** [comment]
If this is about shared resources, then no, and there currently doesn't seem to be a way to implement those.

**Comment by infin1tyy** [comment]
Is there any news on this? I’d really love to move to Linux but without  ragemp or FiveM on Linux I can’t do that.

**Comment by doitsujin** [comment]
No, it's impossible to support this at the moment, that has not changed and that might never change.

**Comment by infin1tyy** [comment]
Ah, thanks. Looks like I'll have to run rage in some sort of virtualized windows environment.

**Comment by Kreyren** [comment]
@doitsujin any known workarounds/hotfixes for this? 

Current issue with FiveM is 
![image](https://user-images.githubusercontent.com/11302521/56853425-9ec31b00-691f-11e9-90bf-59093150f05f.png)

assuming logs on https://drive.google.com/drive/folders/10KLDkIy7VpDZNfHHGInpncXffatObSc_

Maybe this could be implemented without shared resources?

**Comment by doitsujin** [comment]
No, can you people stop asking questions that have been answered dozens of times?

#899

**Comment by Joshua-Ashton** [comment]
What do they need resource sharing for anyway?

**Comment by infin1tyy** [comment]
Running anticheats such as Battleye or playing RageMP/FiveM.

**Comment by h1z1** [comment]
GTA RP is fairly popular on Twitch right now which is probably why more people are asking.  I'm rather surprised Fivem doesn't run under Wine or Proton tbh. 

Maybe worth adding links to a master request or something rather then just Not Implemented?  Just an idea.

**Comment by uselessknickknacks** [comment]
So is this shit ever gonna be fixed? :C

**Comment by infin1tyy** [comment]
I very much hope so. That was the only thing that actually stopped me from moving to Linux full time, and I have since removed my dual boot.

**Comment by Joshua-Ashton** [comment]
Resource sharing probably wont be fixed any time soon.

**Comment by infin1tyy** [comment]
Okay. Cheers. Keep us updated though!! 😊

**Comment by doitsujin** [comment]
To be clear, it's not certain whether this will **ever** be fixed, and repeatedly asking for it won't magically change that.

**Comment by bjwest** [comment]
> To be clear, it's not certain whether this will **ever** be fixed, and repeatedly asking for it won't magically change that.

Repeatedly asking shows an interest in running FiveM client on Linux.  I'd love to try out GTA 5 RP, but I don't do Windows at all.

**Comment by alextwothousand** [comment]
> > To be clear, it's not certain whether this will **ever** be fixed, and repeatedly asking for it won't magically change that.
> 
> 
> 
> Repeatedly asking shows an interest in running FiveM client on Linux.  I'd love to try out GTA 5 RP, but I don't do Windows at all.

Yeah, I agree.

**Comment by emmanuelvlad** [comment]
It would be great for SteamDeck owners to be able to play some FiveM

**Comment by bjwest** [comment]
Streamers with high-end systems have issues with FiveM, I highly doubt a SteamDeck would handle it well, if it could run it at all.

**Comment by JonLit** [comment]
> Streamers with high-end systems have issues with FiveM, I highly doubt a SteamDeck would handle it well, if it could run it at all.

I was able to run it on my PC with (at that time) an i7 4790k and a 1060 6g, I had a very playable 40+ FPS on mostly cranked up settings, so I don't think that'll be a problem...

I since upgraded to a rx 6700xt, and also would still like to play FiveM, vanilla GTA runs perfectly fine on my system, but I'm stuck at this `wine: Unhandled page fault on read access`

**Comment by obsidianical** [comment]
> > Streamers with high-end systems have issues with FiveM, I highly doubt a SteamDeck would handle it well, if it could run it at all.
> 
> I was able to run it on my PC with (at that time) an i7 4790k and a 1060 6g, I had a very playable 40+ FPS on mostly cranked up settings, so I don't think that'll be a problem...
> 
> I since upgraded to a rx 6700xt, and also would still like to play FiveM, vanilla GTA runs perfectly fine on my system, but I'm stuck at this `wine: Unhandled page fault on read access`

I am currently having the exact same issue, has there been any progress in this so far?

**Comment by Blisto91** [comment]
If you mean shared resources then yes there have been some progress on that front. https://github.com/doitsujin/dxvk/pull/2516 https://github.com/doitsujin/dxvk/pull/2608
But i don't know if it has any relevancy to FiveM. I see there is some talk about the original PR [on the forums.](https://forum.cfx.re/t/request-fivem-linux-client/182056/31)

**Comment by alextwothousand** [comment]
If you're looking for a third-party multiplayer mod, look no further. altV is now supported on Linux.

**Comment by obsidianical** [comment]
> The wine crash i don't know about but if you mean shared resources then yes there have been some progress on that front. #2516 #2608 But i don't know if it has any relevancy to FiveM. I see there is some talk about the first PR [on the forums.](https://forum.cfx.re/t/request-fivem-linux-client/182056/31)

Well, that's a start, maybe they'll actually do it!

> If you're looking for a third-party multiplayer mod, look no further. altV is now supported on Linux.

That sadly isn't really an option to me due to a variety of reasons :/

**Comment by pongo1231** [comment]
FiveM should already run on Linux (it's been the case for quite a while now actually), see [here](https://appdb.winehq.org/objectManager.php?sClass=version&iId=39283). You'll be limited to playing servers without svadhesive though (which is the anti cheat).
