### ISSUE TITLE
Dragon Age Inquisition on AMDVLK missing head on Player Character

### ISSUE THREAD

**Issue by llde** [doitsujin/dxvk#837]
Basically in the Head selection at the start the PC has no face, just hair and eyes.
Then it continue in the cutscene, where the face is soemtime rendered, sometime not rendered.
The issue is present only with AMDVLK, not RADV. (But RADV sometimes seems to stutter.)
I link a screenshot:
![](https://pict.covolunablu.org/252en0Yw/S58aSeUw)

### Software information
Dragon Age Inquisitions, all ULTRA, FULL AO, LOW setting for Post processing AA, NO MSAA.

### System information
- GPU: RX580 8GB
- Driver: AMDVLK  Driver: 2.0.66 Vulkan: 1.1.94  (from DXVK info)
- Wine version:  4.0rc4 staging 
- DXVK version: 0.94

### Apitrace file(s)
Working on it. Unluckly while the main offender for Deadlock on resizing is found, starting the game is still a bit of hit or miss with mangling with flags, or thinghs that alter timings as apitrace.

### Log files
- d3d11.log: https://gist.github.com/llde/0c1dbc47ca1f6831c18e006540273d1b
- dxgi.log: https://gist.github.com/llde/4d1f6bd04e2a29819e4172a80ec3ef3c

**Comment by shmerl** [comment]
Note that amdvlk still doens't support transform feedback. May be it's related.

**Comment by doitsujin** [comment]
Works fine in recent AMDVLK versions.
