### ISSUE TITLE
Dragon Ball Fighter Z

### ISSUE THREAD

**Issue by massatt212** [doitsujin/dxvk#839]
### System information
- GPU: GTX 960
- Driver: 417.35.0
- Wine version: Sorry not Wine Windows 10, does the same thing on Ubuntu 
- DXVK version: 0.94

### Apitrace file(s)
- Put a link here

[RED-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/2717174/RED-Win64-Shipping_d3d11.log)
[RED-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/2717175/RED-Win64-Shipping_dxgi.log)

**Comment by massatt212** [comment]
its doing the exact same thing on linux
you should check it out, its one of the best titles atm buy it and fix it up

**Comment by K0bin** [comment]
How about you actually tell him what's wrong with the game?

**Comment by doitsujin** [comment]
@massatt212 you didn't even say **what** it's doing, how am I supposed to fix anything?
