### ISSUE TITLE
Game crashes if launched from Linux Steam with Steam overlay enabled

### ISSUE THREAD

**Issue by ssorgatem** [doitsujin/dxvk#84]
Currently tested with Elder Scrolls Online.
The game works fine if launched outside Steam, or from Steam with the overlay disabled, but with the overlay enabled it crashed before showing anything.

### System information
- GPU: Vega 56
- Driver: latest mesa-git
- Wine version: staging 2.21
- DXVK version: latest git

I have no idea about how to debug this.

I tried launching the triangle sample app... but with latest mesa it crashes on my computer (it didn't before).

**Comment by doitsujin** [comment]
Steam overlay likely uses some sort of hooking that doesn't work with dxvk. FWIW it doesn't work with wined3d either.

**Comment by ssorgatem** [comment]
?
It does work with wined3d. At least with wine-staging. I haven't tested it in mainline wine.

That's how I've been playing ESO for the last 4 months, through native Steam  + wine with he Steam overlay.

Keep in mind that I'm talking about **native** Steam overlay, not from Steam inside wine.

If it can work with wined3d, why not with DXVK?

I understand if it's a very low priority issue... but why wontfix?

**Comment by doitsujin** [comment]
If it's the native one, please make sure that it works with Vulkan games as well.

Your initial post didn't make it clear that you were using the native steam overlay, so I assumed you meant the wine one, which last time I checked *did not* work on wined3d.

The native Vulkan overlay is implemented as a layer. If it doesn't work, it's not a DXVK bug, there's nothing I can do about it.

**Comment by ssorgatem** [comment]
It does work with (native) The Talos Principle. I don't have any other Vulkan games to test...

**Comment by Cloudef** [comment]
overlay should work with wine steam + wined3d too.
