### ISSUE TITLE
Thumper freezes

### ISSUE THREAD

**Issue by mimattr** [doitsujin/dxvk#840]
### Software information
Thumper ([Steam](https://store.steampowered.com/app/356400/)) freezes during launch process due to failed shader compilation:
`DxbcCompiler: Unsupported custom data block: DxbcCustomDataClass::Opaque`

[Original Reference](https://github.com/ValveSoftware/Proton/issues/850#issuecomment-450575153)

### System information
- GPU: **GTX 970**
- Driver: **NVIDIA 415.25**
- Wine version: **Proton 3.16-6 Beta**
- DXVK version: **0.94**

### Log files
- d3d11.log: [THUMPER_d3d11.log](https://gist.github.com/mimattr/a5ef49c54f3a374466d6b5ed8e9536b9)
- dxgi.log: [THUMPER_dxgi.log](https://gist.github.com/mimattr/c02c9ecb6fa6c4c044bbf44927a57d9e)

**Comment by doitsujin** [comment]
No, it doesn't. Please record an apitrace (preferably on Windows) so that I can actually debug the game.

**Comment by doitsujin** [comment]
The game is rated Platinum on [protondb](https://www.protondb.com/app/356400) by the way, please test whether an older DXVK version works.

**Comment by mimattr** [comment]
Apologies for the delayed response, the application no longer freezes during launch and appears to work as expected including `SteamVR` mode (tested with **Proton 4.11-11**/**DXVK 1.5**)

@doitsujin The `DxbcCompiler` message still exists though not causing the original issue, sorry for the confusion.
