### ISSUE TITLE
Black OPS 4 does not start

### ISSUE THREAD

**Issue by debianxfce** [doitsujin/dxvk#841]
Black OPS 4 does not start when you click the Play button on the launcher. It is launching but it does nothing visible. The launcher shows that the game has exited after 10 seconds. Then you must kill the game process. The launcher works only with win 7 and I tested game process files with win8.1 and win10. Using the virtual desktop did not help. I have a clean wine prefix. I created a log file by:
xfce@ryzenpc:/media/ssd/BattleNet/Call of Duty Black Ops 4$ wine 'Black Ops 4 Launcher.exe' &> winelog.log

Any ideas what to try?

### Software information
Call  Of Duty: Black Ops 4 standard edition, it is free when buy an Asus gaming product. The download size  is 85GB.

### System information
- GPU: Asus RX570 4GB
- Driver: Latest Oibaf ppa Mesa and the AMD wip kernel
- Wine version: wine-4.0-rc2 (Staging)
- DXVK version: 0.94

[winelog.log](https://github.com/doitsujin/dxvk/files/2718064/winelog.log)

### Log files
- d3d11.log: created but empty
- dxgi.log: created but empty

**Comment by debianxfce** [comment]
To clean messages from the log, use: winetricks  vcrun2015 and disable audio notifications in the launcher.

What debug channels are useful for tracing what happens?
https://wiki.winehq.org/Debug_Channels

**Comment by debianxfce** [comment]
The game runs some agent and it creates the dxgi.log file.
[Agent_dxgi.log](https://github.com/doitsujin/dxvk/files/2718805/Agent_dxgi.log)

**Comment by doitsujin** [comment]
Doesn't contain any useful info. Not sure what's happening but i doubt it's dxvk related.

**Comment by Kreyren** [comment]
Related: https://www.reddit.com/r/wine_gaming/comments/9r3t0v/call_of_duty_black_ops_4_wont_start/

Seems as wine issue also recommends invoking `WINEPREFIX="<PATH_TO_WINEPREFIX>" winetricks dxvk` as non-root to make sure that dxvk is installed -> ` `WINEPREFIX="<PATH_TO_WINEPREFIX>" winetricks dxvk<DXVK_version>` to eliminate issue with latest -> filing wine bug. 

Also winelog with `WINEDEBUG="+message,+dll" wine <path_to_game>` might reveal something helpful.. it seems to be missing a dependency which cause it to be stuck in a regression.

**Comment by debianxfce** [comment]
The game loads 32-bit dlls only, so the next tester could try with a 32-bit wine prefix. The game requirements says that OS must be 64-bit.

**Comment by doitsujin** [comment]
This game is most definitely not 32-bit. Aren't you mixing that up with the Blizzard launcher?

**Comment by debianxfce** [comment]
I have 64-bit wine prefix. I mixed windows versions only. as I wrote: "The launcher works only with win 7 and I tested game process files with win8.1 and win10. "

**Comment by doitsujin** [comment]
I don't have the game, can you post the log?

If it tries to load 32-bit DLLs then something is wrong, the game has to be a 64-bit exe.

**Comment by arno01** [comment]
Hi all,

I'd like to chip-in since I am having the same game.

- 1. The binary is **64-bit**

```
$ file BlackOps4.exe
BlackOps4.exe: PE32+ executable (GUI) x86-64, for MS Windows
```

- 2. When starting the game directly with **Proton 3.16** it crashes after few seconds

  > [DXVK is the one that is coming with Valve](https://github.com/ValveSoftware/dxvk/commits/proton_3.16), it is versioned as ``v0.90-206-g3b3ccc8``, but it is based off the DXVK ``v0.94``.

  - [``wine BlackOps4.exe`` logs](https://0.nixaid.com/?5e8d0b86b91d0e3f#ia2LAI1F5RNFzymyvrjLHzph3gRVkat/lReC6DgXVug=)

  - [``WINEDEBUG=+loaddll wine BlackOps4.exe`` logs](https://0.nixaid.com/?e8943175909dae30#RMmBAEQ9myEise0MKOednpmU2xzKLY+tEwk8raeLw9I=)

  - [Dll Overrides](https://0.nixaid.com/?acb0fe69036aaff2#zNLSzGbhLGVv9pA08iE0LrTCLqFS38CijdT96JK+7Iw=)

  - [DLL and EXE files of the game](https://0.nixaid.com/?87f668ce3f6cb170#QhyIrDhlJYqyHhAvngMX0o68Z2Ygta3xlMHF0bceZ4U=)

  - [objdump -x BlackOps.exe](https://0.nixaid.com/?fe7b4869edc382e7#mvGl+7fJXeA6pnbrkZO1y1dil2EI5fD7vot2hwjJGWw=) to see what functions it may be calling

When starting the game via the ``Battle.net.exe`` first, the behavior is pretty much same.. except that I see more error messages such as below. I am wondering if these errors could shed more light on the problem?

```
[0106/154043.056:ERROR:angle_platform_impl.cc(54)] rx::Renderer11::populateRenderer11DeviceCaps(906): Error querying driver version from DXGI Adapter.
```

```
00d6:fixme:d3d11:d3d11_device_CheckFormatSupport iface 0x7b28fc0, format 87, format_support 0x33e6cc partial-stub!
00d6:fixme:d3d11:d3d11_immediate_context_Flush iface 0x7b28fe0 stub!
#00d6:fixme:d3d12:D3D12CreateDevice Ignoring adapter (nil).
fixme:vkd3d_create_device: Unsupported feature level 0xc100.
00d6:fixme:d3d12:D3D12CreateDevice Ignoring adapter (nil).
fixme:vkd3d_create_device: Unsupported feature level 0xc000.
00d6:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
00d6:fixme:kernelbase:AppPolicyGetProcessTerminationMethod 0xfffffffa, 0x33fe3c
00d4:fixme:ntdll:FILE_CreateFile alloc_size not supported
wine: Unhandled exception 0xc0000409 in thread d4 at address 0x65e6f0 (thread 00d4), starting debugger...
0009:fixme:d3d11:wined3d_usage_from_d3d11 Unhandled bind flags 0x80.
```

```
0009:fixme:d3d11:wined3d_usage_from_d3d11 Unhandled bind flags 0x80.
0009:fixme:d3d11:d3d11_immediate_context_OMSetBlendState Ignoring blend factor {5.49019635e-01, 5.25490224e-01, 5.01960814e-01, 1.00000000e+00}.
0009:fixme:d3d11:d3d11_immediate_context_OMSetBlendState Ignoring blend factor {5.49019635e-01, 5.25490224e-01, 5.01960814e-01, 1.00000000e+00}.
0009:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 0x32c424.
0009:fixme:d3d11:d3d11_immediate_context_OMSetBlendState Ignoring blend factor {5.49019635e-01, 5.25490224e-01, 5.01960814e-01, 1.00000000e+00}.
0009:fixme:dxgi:d3d11_swapchain_Present1 Ignored present parameters 0x32c424.

00ea:fixme:ntdll:FILE_CreateFile alloc_size not supported
wine: Unhandled exception 0xc0000409 in thread ea at address 0x65e6f0 (thread 00ea), starting debugger...
```

**Comment by doitsujin** [comment]
@arno01 

> I am wondering if these errors could shed more light on the problem?

No, those are from the battle.net client (specifically, CEF), and completely irrelevant. Wouldn't even be surprised if the same thing happened on Windows as well...

Anyway, while generating your log files you were using wined3d and not dxvk, but even so there is no hint at all as to why the game might be crashing. I suspect that it's not related to rendering though.

**Comment by MinIsMin** [comment]
@doitsujin You should also remove the comment history because the links to the game files are still visible there.

**Comment by doitsujin** [comment]
I can't do that.

**Comment by arno01** [comment]
@doitsujin makes sense. Please edit your message, since I have not been sharing the copyrighted game files itself, but rather their metadata (information about the files, import tables). Which makes a big difference: reverse engineering vs. re-distribution of the copyrighted content. Thanks.

**Comment by Trollwut** [comment]
May I ask what the current state is and if it's fixable?

**Comment by doitsujin** [comment]
Probably doesn't work and the main reason for that is probably not DXVK.
