### ISSUE TITLE
Abstract: DXVK_HUD="all"

### ISSUE THREAD

**Issue by Kreyren** [doitsujin/dxvk#842]
i'm usually using `DXVK_HUD='devinfo,fps,frametimes,drawcalls,pipelines,memory,version' ` for debugging and so i think that shorting this command into `DXVK_HUD="all"` might prove helpful.

**Comment by Kreyren** [comment]
There is `DXVK_HUD="1"` which i wasn't aware of. Closing

**Comment by doitsujin** [comment]
d0ee7f54bf0165d1a98af07ee4465553de3b0a43 introduces `DXVK_HUD=full`, which enables all HUD elements.

**Comment by Kreyren** [comment]
@doitsujin Thanks! ^^
