### ISSUE TITLE
Invisible Objects (Osiris: New Dawn)

### ISSUE THREAD

**Issue by VortexAcherontic** [doitsujin/dxvk#847]
I have a little issue with DXVK on a Unity based game called Osiris: New Dawn it's an early access title.
I tried to figure out if I can fix this problem by myself but ended up having no idea.
Right now I did not discovered any more missing object or characters but there might be more.

### Software information
- Game: Osiris: New Dawn
- Engine: Unity
- Settings: Lowest and Highest
- Additional: I run the game trough Lutris and the Wine Steam runner.

### System information
- GPU: GTX 1080
- Driver: 410.78
- Wine version: 3.21 x86_64
- DXVK version: 0.94
- Vulkan: 1.1.82

### Apitrace file(s)
![missing_character_desert](https://user-images.githubusercontent.com/11244092/50769529-82be3f80-1284-11e9-9d9c-24ed0d46f3d0.png)
![missing_character_main_menu](https://user-images.githubusercontent.com/11244092/50769531-82be3f80-1284-11e9-9b86-056816c3cddb.png)

### Log files
- d3d11.log: [OsirisNewDawn_d3d11.log](https://github.com/doitsujin/dxvk/files/2732815/OsirisNewDawn_d3d11.log)
- dxgi.log: [OsirisNewDawn_dxgi.log](https://github.com/doitsujin/dxvk/files/2732816/OsirisNewDawn_dxgi.log)

**Comment by Tk-Glitch** [comment]
Your logs are telling everything : `err:   D3D11Device::CreateBuffer: D3D11_BIND_STREAM_OUTPUT not supported`
Your current GPU driver doesn't support transformation feedback extension. You'll have to use either 396.54.09 vulkan dev driver or 415 series.

**Comment by VortexAcherontic** [comment]
Thanks for the fast answer. I was not sure if that err in the log was caused by DXVK not supporting something or if it is caused by my driver.
We'll I think I need to update the my driver or wait for the NVidia LTS driver to support this ._. (Have no good experience with the vulkan dev drivers)

**Comment by Tk-Glitch** [comment]
No problem. The last 415.22.05 ones released yesterday have been working fine with my 980ti so far.

**Comment by VortexAcherontic** [comment]
Do you have any information on the 410.93 driver (the latest LTS driver by Nvidia) dose it support this too? :)

**Comment by Tk-Glitch** [comment]
410 branch seems to be missing support for it as a whole, sadly.

**Comment by VortexAcherontic** [comment]
Then I try 415.25 and check back later (if I do not completely break anything during this process :D)

**Comment by Tk-Glitch** [comment]
Right now you got pretty limited choices. Here is the complete list :
On short-lived branch : 415.22, 415.23, 415.25.
On the vulkan dev branch : 396.54.09, 415.18.02, 415.18.04, 415.22.01, 415.22.05.

**Comment by VortexAcherontic** [comment]
That did the trick, thank you very much :+1: 

![character_main_menu](https://user-images.githubusercontent.com/11244092/50772557-86ef5a80-128e-11e9-8534-9fd8e102d533.png)
