### ISSUE TITLE
(Shader/dxbc) Reasons to use opNMax,min,clamp instead of opFxxx one?

### ISSUE THREAD

**Issue by Klanly** [doitsujin/dxvk#848]
Hi, I am trying to use your dxbc funcs to convert some pre-compiled dx11 shaders to spirv,
then convert it back to pseudo-hlsl with spirv-cross --hlsl --shader-model 40.

The problem is spirv-cross does not process opcodes like unsupported_glsl450_nmax,nmin,nclamp.
I do not know well about shader standards actually.
So is it safe to change those nmax,nmin,nclamp in your dxbc funcs to FMax,FMin,FClamp?

**Comment by doitsujin** [comment]
The difference between `NMin` and `FMin` is how NaN operands are handled, and `NMin` is needed to emulate Direct3D behaviour. If you know that your shaders don't generate NaNs, then it is safe to make the change.

**Comment by Klanly** [comment]
Ok thanks.
BTW I also found that I have to make this change

 const uint32_t stageOffset = 0; //128 + 160 * uint32_t(shaderStage);

in **computeResourceSlotId** to let fxc compile the generated code (otherwise it says "maximum cbuffer exceeded").

Is that made for some optimization (not for exact code translating)?
Are there other places also contains this kind of trick(?)s ?

**Comment by doitsujin** [comment]
It's not an optimization, it's done to map the D3D11 binding model to something that DXVK can more easily work with internally.
