### ISSUE TITLE
Need For Speed 2015

### ISSUE THREAD

**Issue by ziemia** [doitsujin/dxvk#849]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Name of the game, settings used etc.

### System information
- GPU:
- Driver:
- Wine version: 
- DXVK version: 

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log:

**Comment by doitsujin** [comment]
This bug report has no info.

**Comment by ziemia** [comment]
The game starts with a black screen.
Sets:

> dxgi.customDeviceId = 10de
> dxgi.customVendorId = 1c06

Allows to start the game.

**Software information**
Need For Speed 2015 - Origin version 
https://www.ea.com/games/need-for-speed/need-for-speed-2015

**System information**
GPU: GTX 960
Driver: 415.25
Wine version: 3.21-staging
DXVK version: 0.94

[NFS16_d3d11.log](https://github.com/doitsujin/dxvk/files/2741934/NFS16_d3d11.log)
[NFS16_dxgi.log](https://github.com/doitsujin/dxvk/files/2741937/NFS16_dxgi.log)

PS. FAudio solves all sound problems that I had in this game.
