### ISSUE TITLE
Don't have error!But Game don't move. Screen freeze

### ISSUE THREAD

**Issue by Lee02** [doitsujin/dxvk#851]
### System information
- GPU:GTX970
- Driver: Linux 415.22.1
- Wine version: 4.0-RC4
- DXVK version: 0.94
- Vulkan: 1.1.95

Run Game.but Game Screen freeze.Game have voiced.no error!
system:ubuntu 18.10
d3d11.log and dxgi.log don't error

https://github.com/Lee02/dxvk-sea/blob/master/GameLog/gujianol_d3d11.log
https://github.com/Lee02/dxvk-sea/blob/master/GameLog/gujianol_dxgi.log

Please take a look at it for me!  Thanks very much!

**Comment by doitsujin** [comment]
Please record an apitrace on a Windows machine so that I can actually debug it.

**Comment by Lee02** [comment]
I use NVIDIA  Nsight Graphics OK?

**Comment by Lee02** [comment]
> Please record an apitrace on a Windows machine so that I can actually debug it.

I know what's wrong! usb Joystick wrong!close usb Joystick! game good run.

thx for you
