### ISSUE TITLE
FFXV no Vsync.

### ISSUE THREAD

**Issue by artivision** [doitsujin/dxvk#854]
FFXV + Polaris + Mesa_Git + 120-144Hz monitor, Vsync doesn't work.

**Comment by doitsujin** [comment]
What do you mean "doesn't work"? Is there tearing?

That's not a DXVK bug.

**Comment by artivision** [comment]
Wile Vsync=1 in config tearing is everywhere. Is your monitor 120-144Hz?

**Comment by doitsujin** [comment]
No, 60 Hz. I don't see how this matters though, if there's tearing with vsync then that's an issue with your system configuration or graphics driver.

**Comment by artivision** [comment]
Xfce default compositor's Vsync works fine, Steam CSGO OGL fine, Unigine Heaven 4 OGL fine, videos fine.

**Comment by doitsujin** [comment]
Can you please upload the DXVK log files? They show which present mode is in use. If it's `FIFO` or `MAILBOX` then DXVK enables Vsync correctly and the problem is somewhere else.

**Comment by doitsujin** [comment]
`VK_PRESENT_MODE_FIFO_KHR` enables Vsync, so yeah, not my bug.

Make sure that you're not using any non-default X11 options that might break it, check if using a minimal WM fixes the problem (something like Fluxbox, without any overly complicated presentation pipeline), and if nothing works, file a mesa bug.
