### ISSUE TITLE
Dragon ball FighterZ

### ISSUE THREAD

**Issue by massatt212** [doitsujin/dxvk#856]
This is my first APITRACE tell me i did good lol
Game Starts with a black Screen then crashes

### Software information
Dragon Ball Fighter Z
Lutris
Proton And 4.0 Staging Wine

### System information
- GPU: GTX 1050 TI
- Driver: 415.25.0
- Wine version: Steam Proton via Lutris
- DXVK version: 0.95

### Apitrace file(s)
- https://drive.google.com/open?id=1fNr48AE7bgPlXW--j0y-8r-7_mQmiVjd

### Log files
[RED-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/2752720/RED-Win64-Shipping_d3d11.log)
[RED-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/2752721/RED-Win64-Shipping_dxgi.log)

**Comment by massatt212** [comment]
is my Logs and Apitrace any good or i have to do it over ?

**Comment by massatt212** [comment]
Does the same on wined3d black screen and crash

**Comment by massatt212** [comment]
Recommend a apitrace to me

**Comment by massatt212** [comment]
so this game has Denuvo and EAC (WaW)
i think Denuvo  prevented it from starting, it also prevents injustice 2 from working also, but the original copy is not working, got the cracked one working on Windows (yes i own the game)
Some reason all Unreal Engine Games Show Yellow on DXVK on windows i know you say you dont support it but can you look into it with Tekken, Soulcalibur, Street fighter V, DBFZ if you own any

heres a lil video
https://youtu.be/4EU5vWP23j4

**Comment by doitsujin** [comment]
So, is this problem solved then?

I'm aware of the yellow hue issue in UE4 on Windows, it's likely a bug in AMD's proprietary Vulkan driver. Works fine on RADV and even AMDVLK.

**Comment by massatt212** [comment]
EAC detects DXVK and kills process

**Comment by massatt212** [comment]
https://drive.google.com/open?id=1y2UMCT2iXEOy5v-8AtJ1S2SIvqi62adL
so paladins EAC dll makes almost ever DXVK Game Works without a problem
I replace the 2 .dll in my Dragon ball Fighters EAC folder and it started working try it yourself
![screenshot from 2019-01-20 21-50-36](https://user-images.githubusercontent.com/43518479/51448533-95f9f200-1cfd-11e9-9a86-753514f028c2.png)
![screenshot from 2019-01-20 21-52-04](https://user-images.githubusercontent.com/43518479/51448539-a611d180-1cfd-11e9-9216-18e38804c32f.png)

**Comment by ibster1st123** [comment]
> Need help installing dbfz
