### ISSUE TITLE
Assassin's Creed Odyssey fails on 0.95, works on 0.94

### ISSUE THREAD

**Issue by jcdutton** [doitsujin/dxvk#858]
Description:

~/dxvk/dxvk-0.94$ winetricks --force setup_dxvk.verb    <- This works
~/dxvk/dxvk-0.95$ winetricks --force setup_dxvk.verb    <-  Odyssey Game fails to start.

### Software information
Assassin's Creed Odyssey

### System information
- GPU:  AMD Vega 56
- Driver: amdgpu   (not pro)
- Wine version:  wine-4.0-rc5
- DXVK version: 0.95

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log:

**Comment by doitsujin** [comment]
No log files -> how am I supposed to know what's wrong? The game runs fine with 0.95 so there's no DXVK bug.

You probably just messed up your DXVK install. Try a fresh prefix in that case or use Lutris (which has its own way of setting up DXVK).

**Comment by jcdutton** [comment]
Just adding logs now

**Comment by jcdutton** [comment]
The only files different in the two setups is the dxvk files

~/dxvk/dxvk-0.95$ winetricks --force setup_dxvk.verb 
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20180217 - sha256sum: 1b156c616174f41df79d72a90c52eb2b110c63a6e8ecb865d303a8f9f0908924 with wine-4.0-rc6 (Staging) and WINEARCH=win64
Executing w_do_call setup_dxvk
Executing load_setup_dxvk 
Executing cp /home/jcd/dxvk/dxvk-0.95/x32/dxgi.dll /home/jcd/.wine/dosdevices/c:/windows/syswow64/dxgi.dll
Executing cp /home/jcd/dxvk/dxvk-0.95/x32/d3d11.dll /home/jcd/.wine/dosdevices/c:/windows/syswow64/d3d11.dll
Executing cp /home/jcd/dxvk/dxvk-0.95/x32/d3d10.dll /home/jcd/.wine/dosdevices/c:/windows/syswow64/d3d10.dll
Executing cp /home/jcd/dxvk/dxvk-0.95/x32/d3d10_1.dll /home/jcd/.wine/dosdevices/c:/windows/syswow64/d3d10_1.dll
Executing cp /home/jcd/dxvk/dxvk-0.95/x32/d3d10core.dll /home/jcd/.wine/dosdevices/c:/windows/syswow64/d3d10core.dll
Executing cp /home/jcd/dxvk/dxvk-0.95/x64/dxgi.dll /home/jcd/.wine/dosdevices/c:/windows/system32/dxgi.dll
Executing cp /home/jcd/dxvk/dxvk-0.95/x64/d3d11.dll /home/jcd/.wine/dosdevices/c:/windows/system32/d3d11.dll
Executing cp /home/jcd/dxvk/dxvk-0.95/x64/d3d10.dll /home/jcd/.wine/dosdevices/c:/windows/system32/d3d10.dll
Executing cp /home/jcd/dxvk/dxvk-0.95/x64/d3d10_1.dll /home/jcd/.wine/dosdevices/c:/windows/system32/d3d10_1.dll
Executing cp /home/jcd/dxvk/dxvk-0.95/x64/d3d10core.dll /home/jcd/.wine/dosdevices/c:/windows/system32/d3d10core.dll
Using native override for following DLLs: dxgi d3d11 d3d10 d3d10_1 d3d10core
Executing wine regedit C:\windows\Temp\_setup_dxvk\override-dll.reg
Executing wine64 regedit C:\windows\Temp\_setup_dxvk\override-dll.reg

**Comment by jcdutton** [comment]
~/dxvk/dxvk-0.94$ winetricks --force setup_dxvk.verb 
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20180217 - sha256sum: 1b156c616174f41df79d72a90c52eb2b110c63a6e8ecb865d303a8f9f0908924 with wine-4.0-rc6 (Staging) and WINEARCH=win64
Executing w_do_call setup_dxvk
Executing load_setup_dxvk 
Executing cp /home/jcd/dxvk/dxvk-0.94/x32/dxgi.dll /home/jcd/.wine/dosdevices/c:/windows/syswow64/dxgi.dll
Executing cp /home/jcd/dxvk/dxvk-0.94/x32/d3d11.dll /home/jcd/.wine/dosdevices/c:/windows/syswow64/d3d11.dll
Executing cp /home/jcd/dxvk/dxvk-0.94/x32/d3d10.dll /home/jcd/.wine/dosdevices/c:/windows/syswow64/d3d10.dll
Executing cp /home/jcd/dxvk/dxvk-0.94/x32/d3d10_1.dll /home/jcd/.wine/dosdevices/c:/windows/syswow64/d3d10_1.dll
Executing cp /home/jcd/dxvk/dxvk-0.94/x32/d3d10core.dll /home/jcd/.wine/dosdevices/c:/windows/syswow64/d3d10core.dll
Executing cp /home/jcd/dxvk/dxvk-0.94/x64/dxgi.dll /home/jcd/.wine/dosdevices/c:/windows/system32/dxgi.dll
Executing cp /home/jcd/dxvk/dxvk-0.94/x64/d3d11.dll /home/jcd/.wine/dosdevices/c:/windows/system32/d3d11.dll
Executing cp /home/jcd/dxvk/dxvk-0.94/x64/d3d10.dll /home/jcd/.wine/dosdevices/c:/windows/system32/d3d10.dll
Executing cp /home/jcd/dxvk/dxvk-0.94/x64/d3d10_1.dll /home/jcd/.wine/dosdevices/c:/windows/system32/d3d10_1.dll
Executing cp /home/jcd/dxvk/dxvk-0.94/x64/d3d10core.dll /home/jcd/.wine/dosdevices/c:/windows/system32/d3d10core.dll
Using native override for following DLLs: dxgi d3d11 d3d10 d3d10_1 d3d10core
Executing wine regedit C:\windows\Temp\_setup_dxvk\override-dll.reg
Executing wine64 regedit C:\windows\Temp\_setup_dxvk\override-dll.reg

**Comment by doitsujin** [comment]
So what exactly is the problem? The game does start according to your logs. Does it crash?

**Comment by jcdutton** [comment]
The problem is is fails to reach the first welcome screen of the game.
You the the splash image while loading, but not the following welcome screen.

**Comment by tingvarsson** [comment]
@jcdutton You should disable the overlay at it is what seems to crash according to your own deduction, see [common issues](https://github.com/doitsujin/dxvk/wiki/Common-issues)

**Comment by doitsujin** [comment]
Ah yes, the Uplay overlay must be disabled.

**Comment by jcdutton** [comment]
I disabled the Uplay overlay.
The game benchmark (select benchmark from the game menus) now runs and completes, but it pauses often, about once every 2 seconds, so is not great.  The FPS is actually higher with 0.95 over 0.94, which is great, and why I was wishing to upgrade from 0.94 to 0.95.
The pause seems to be correlated (pauses each time the error message appears) with wine log messages like this:
01b6:fixme:nvapi:unimplemented_stub function 0xe3640a56 is unimplemented!
01b6:fixme:nvapi:unimplemented_stub function 0x60ded2ed is unimplemented!
01b6:fixme:nvapi:unimplemented_stub function 0xe3640a56 is unimplemented!
01b6:fixme:nvapi:unimplemented_stub function 0x60ded2ed is unimplemented!

**Comment by doitsujin** [comment]
Doesn't happen on my system.

**Comment by jcdutton** [comment]
> Ah yes, the Uplay overlay must be disabled.

It seems that updates don't work right in the game if overlay is disabled. I switched to 0.94, enabled overlay, finished the updates, then switched back to 0.95 and it seems to be OK pause wise.
Who should I be reporting the "overlay" problems to, so they might get fixed?

**Comment by doitsujin** [comment]
Does that mean the overlay works for you with 0.94? I don't recall it ever being usable.

**Comment by jcdutton** [comment]
I don't think I have ever pressed the overlay hot key while on 0.94.
I just did not have to disable "overlay" in uplay for 0.94 as I now have to do in 0.95.
I.e. having "overlay" enabled did not crash anything in 0.94.
