### ISSUE TITLE
dxgi.syncMode ignored ?

### ISSUE THREAD

**Issue by pchome** [doitsujin/dxvk#861]
https://github.com/doitsujin/dxvk/blob/master/src/d3d11/d3d11_options.cpp#L17 -- never used ?
https://github.com/doitsujin/dxvk/blob/master/src/d3d11/d3d11_swapchain.cpp#L707
https://github.com/doitsujin/dxvk/blob/master/src/vulkan/vulkan_presenter.cpp#L283

Looks like "Present mode" will always be `VK_PRESENT_MODE_FIFO_KHR` by default,
and ` VK_PRESENT_MODE_IMMEDIATE_KHR` for `dxgi.syncInterval=0`.

`dxgi.syncMode = 1` ignored.

<hr/>

Also, shouldn't DXVK force default number of `dxgi.numBackBuffers` to be `4` for `VK_PRESENT_MODE_MAILBOX_KHR` (and maybe for `VK_PRESENT_MODE_IMMEDIATE_KHR`), as described in #806 ?

There is indeed difference for me in `DXVK_HUD=fps,frametimes d3d11-triangle.exe` test.
* default : 2200+ fps
* `dxgi.numBackBuffers = 4` : 2300+ fps

Same when I trying to force `VK_PRESENT_MODE_MAILBOX_KHR`.

**Comment by doitsujin** [comment]
The correct fix is to remove the option entirely. There's no reason for it to exist and when it was there, it didn't work as expected on anything.

> Also, shouldn't DXVK force default number of dxgi.numBackBuffers to be 4 for VK_PRESENT_MODE_MAILBOX_KHR (and maybe for VK_PRESENT_MODE_IMMEDIATE_KHR), as described in #806 ?

No, DXVK has no business guessing what the window system it's running on **might** require. This is not a bug.

**Comment by pchome** [comment]
Understood, thanks.
