### ISSUE TITLE
World of Tanks / Warship Nvidia problem

### ISSUE THREAD

**Issue by Gilles25580** [doitsujin/dxvk#864]
Hello,
I can t use DXVK with this game. I think it s a problem betwin my computer (driver NVidia ?) and DXVK
I can t launch the game with DXVK enable but i can without DXVK. I test World of tank / Warship and WarThunder.
I don t understand how to solv my problem. 

Can you help me please ?
Thanks
Gilles

### Software information
Lutris
Games: World of tanks - World of Warship
War Thunder

### System information
MSI GT70-0ND with a upgrade MSI970M
Ubuntu 18.10 64bit - 
- GPU:core i7
- Driver:NVIDIA 415
- Wine version: a lot staging-3.18-x86-64 // tkg-protonified-3.20-x86-64 - idem -3.21 //
System wine staging 4.0rc6(staging)
- DXVK version: 0.94/.95

### Apitrace file(s)
 run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. 

### Log files
[worldoftanks_d3d11.log](https://github.com/doitsujin/dxvk/files/2762581/worldoftanks_d3d11.log)
[worldoftanks_dxgi.log](https://github.com/doitsujin/dxvk/files/2762582/worldoftanks_dxgi.log)

**Comment by doitsujin** [comment]
What *exactly* do you mean by "doesn't launch"? What happens?

**Comment by Gilles25580** [comment]
Hello, sorry for my bad english. When I activate DXVK in lutris, the Wine process launches with the game but nothing appears on the screen. Without DXVK, the wine process is active and the game is visible.
Thank you

**Comment by Gilles25580** [comment]
Some informations
neofetch
            .-/+oossssoo+/-.               gilles@gilles-GT70 
        `:+ssssssssssssssssss+:`           ------------------ 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 18.10 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: GT70 REV:1.0 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 4.18.0-13-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 21 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2211 (dpkg), 9 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.4.19 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 3.30.1 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: GNOME Shell 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i7-3630QM (8) @ 3.400GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA GeForce GTX 970M 
      -+sssssssssssssssssyyyssss+-         GPU: Intel 3rd Gen Core processor Gr 
        `:+ssssssssssssssssss+:`           Memory: 3131MiB / 15933MiB 

*****************************************
glxinfo | grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 970M/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 415.25
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 415.25
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 415.25
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
***************************************************
vulkaninfo
==========
VULKANINFO
==========

Vulkan Instance Version: 1.1.82

ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete


INTEL-MESA: warning: ../src/intel/vulkan/anv_device.c:1224: FINISHME: Implement pop-free point clipping


Instance Extensions:
====================
Instance Extensions	count = 17
	VK_EXT_acquire_xlib_display         : extension revision  1
	VK_EXT_debug_report                 : extension revision  8
	VK_EXT_debug_utils                  : extension revision  1
	VK_EXT_direct_mode_display          : extension revision  1
	VK_EXT_display_surface_counter      : extension revision  1
	VK_KHR_device_group_creation        : extension revision  1
	VK_KHR_display                      : extension revision 23
	VK_KHR_external_fence_capabilities  : extension revision  1
	VK_KHR_external_memory_capabilities : extension revision  1
	VK_KHR_external_semaphore_capabilities: extension revision  1
	VK_KHR_get_display_properties2      : extension revision  1
	VK_KHR_get_physical_device_properties2: extension revision  1
	VK_KHR_get_surface_capabilities2    : extension revision  1
	VK_KHR_surface                      : extension revision 25
	VK_KHR_wayland_surface              : extension revision  6
	VK_KHR_xcb_surface                  : extension revision  6
	VK_KHR_xlib_surface                 : extension revision  6
Layers: count = 8
=======
VK_LAYER_GOOGLE_threading (Google Validation Layer) Vulkan version 1.1.82, layer version 1
	Layer Extensions	count = 1
		VK_EXT_debug_report                 : extension revision  6
	Devices 	count = 2
		GPU id       : 0 (GeForce GTX 970M)
		Layer-Device Extensions	count = 0
		GPU id       : 1 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 0

VK_LAYER_GOOGLE_unique_objects (Google Validation Layer) Vulkan version 1.1.82, layer version 1
	Layer Extensions	count = 0
	Devices 	count = 2
		GPU id       : 0 (GeForce GTX 970M)
		Layer-Device Extensions	count = 0
		GPU id       : 1 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 0

VK_LAYER_LUNARG_core_validation (LunarG Validation Layer) Vulkan version 1.1.82, layer version 1
	Layer Extensions	count = 1
		VK_EXT_debug_report                 : extension revision  6
	Devices 	count = 2
		GPU id       : 0 (GeForce GTX 970M)
		Layer-Device Extensions	count = 2
			VK_EXT_debug_marker                 : extension revision  4
			VK_EXT_validation_cache             : extension revision  1
		GPU id       : 1 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 2
			VK_EXT_debug_marker                 : extension revision  4
			VK_EXT_validation_cache             : extension revision  1

VK_LAYER_LUNARG_object_tracker (LunarG Validation Layer) Vulkan version 1.1.82, layer version 1
	Layer Extensions	count = 1
		VK_EXT_debug_report                 : extension revision  6
	Devices 	count = 2
		GPU id       : 0 (GeForce GTX 970M)
		Layer-Device Extensions	count = 1
			VK_EXT_debug_marker                 : extension revision  4
		GPU id       : 1 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 1
			VK_EXT_debug_marker                 : extension revision  4

VK_LAYER_LUNARG_parameter_validation (LunarG Validation Layer) Vulkan version 1.1.82, layer version 1
	Layer Extensions	count = 1
		VK_EXT_debug_report                 : extension revision  6
	Devices 	count = 2
		GPU id       : 0 (GeForce GTX 970M)
		Layer-Device Extensions	count = 1
			VK_EXT_debug_marker                 : extension revision  4
		GPU id       : 1 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 1
			VK_EXT_debug_marker                 : extension revision  4

VK_LAYER_LUNARG_standard_validation (LunarG Standard Validation) Vulkan version 1.1.82, layer version 1
	Layer Extensions	count = 1
		VK_EXT_debug_report                 : extension revision  6
	Devices 	count = 2
		GPU id       : 0 (GeForce GTX 970M)
		Layer-Device Extensions	count = 2
			VK_EXT_debug_marker                 : extension revision  4
			VK_EXT_validation_cache             : extension revision  1
		GPU id       : 1 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 2
			VK_EXT_debug_marker                 : extension revision  4
			VK_EXT_validation_cache             : extension revision  1

VK_LAYER_VALVE_steam_overlay_32 (Steam Overlay Layer) Vulkan version 1.1.73, layer version 1
	Layer Extensions	count = 0
	Devices 	count = 2
		GPU id       : 0 (GeForce GTX 970M)
		Layer-Device Extensions	count = 0
		GPU id       : 1 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 0

VK_LAYER_VALVE_steam_overlay_64 (Steam Overlay Layer) Vulkan version 1.1.73, layer version 1
	Layer Extensions	count = 0
	Devices 	count = 2
		GPU id       : 0 (GeForce GTX 970M)
		Layer-Device Extensions	count = 0
		GPU id       : 1 (Intel(R) Ivybridge Mobile)
		Layer-Device Extensions	count = 0

Presentable Surfaces:
=====================
GPU id       : 0 (GeForce GTX 970M)
Surface type : VK_KHR_xcb_surface
**vulkaninfo: /build/vulkan-tools-ZnxIl9/vulkan-tools-1.1.82.0+dfsg1/vulkaninfo/vulkaninfo.c:1253: AppDumpSurfaceFormats: Assertion `!err' failed.
Abandon (core dumped)**

But sudo vulkaninfo is ok and very long

**Comment by doitsujin** [comment]
Can't reproduce the problem on my setup. This sounds like a configuration issue but I do not know how to set up multi-GPU systems such as yours to work properly with Vulkan.

I just tested World of Warships and it shows the loading screen, but then crashes. The exact same thing happens with wined3d so my issue is not a DXVK bug, but also unrelated to yours.

**Comment by Gilles25580** [comment]
Ok,
Thank you i continue to search

**Comment by Leopard1907** [comment]
If you're using Bumblebee , it doesn't support Vulkan. You should use Nvidia Prime.
