### ISSUE TITLE
Alt tab doesn't work with DXVK

### ISSUE THREAD

**Issue by KonomiKitten** [doitsujin/dxvk#866]
### Software information
I tested this on World of Warcraft I suspect it may be an issue on other games I lack any other DX11 games to test, but when I use DXVK and try to alt tab the game window does not lose focus and I cannot switch to my desktop. This issue doesn't happen if I just use Wine without DXVK.

### System information
- GPU: GeForce GTX 960
- Driver: NVIDIA 390.87
- Wine version: 3.21
- DXVK version: 0.95

**Comment by doitsujin** [comment]
> Driver: NVIDIA 390.87

Please update to 415.27, your driver version is horribly outdated.

**Comment by massatt212** [comment]
use borderless windows (windows Fullscreen) if driver update dont work

**Comment by Leopard1907** [comment]
That was a known problem in earlier Vulkan drivers.

Please update your driver , use 415 series.

**Comment by KonomiKitten** [comment]
@doitsujin I'd like to update my driver but there aren't anymore modern versions of the Nvidia driver available on Debian Stetch. If @Leopard1907 is sure it's just the driver version I'll close the bug.

**Comment by doitsujin** [comment]
Then stop using Debian, or find a PPA which offers reasonably up-to-date graphics drivers. The 390 series is known to be broken with DXVK and **will** cause all sorts of issues.

**Comment by KonomiKitten** [comment]
@doitsujin okay thanks for the reply I'll close this since I'm not willing to mess around trying to get packages for Debian.

**Comment by Leopard1907** [comment]
I'm sure. Just use a sane distro that can offer recent drivers out of the box or via a PPA.

If you want , you can manually update your driver too though that is not recommended. 

https://www.nvidia.com/Download/driverResults.aspx/141847/en-us

**Comment by Kreyren** [comment]
Gentoooo...

**Comment by KonomiKitten** [comment]
@Kreyren I'm.. I'm not ready for the Gentoo
