### ISSUE TITLE
heroes of the storm doesnt start

### ISSUE THREAD

**Issue by mmiat** [doitsujin/dxvk#868]
### Software information
Heroes of the Storm, new and clean prefix, it runs at 30fps
if i install dxvk it doesnt start with popup "the application encountered an unexpected error"

### System information
- OS: KDE Neon
- GPU: GeForce GTX 1060 3GB
- Driver: nvidia-driver-415                               415.27-0ubuntu0~gpu18.04.1
- Wine version: wine-staging                                    4.0~rc6~bionic
- DXVK version: 0.95

### Apitrace file(s)
i tried but i've error
wine: cannot find L"C:\\windows\\system32\\apitrace.exe"
I've tried to download it and extract both in system32 and in syswow64 but no success

### Log files
- d3d11.log: hots doesnt start, i've old ones with fresh prefix without dxvk
[HeroesOfTheStorm_x64_d3d11.log](https://github.com/doitsujin/dxvk/files/2775447/HeroesOfTheStorm_x64_d3d11.log)

- dxgi.log: hots doesnt start, i've old ones with fresh prefix without dxvk
[HeroesOfTheStorm_x64_dxgi.log](https://github.com/doitsujin/dxvk/files/2775448/HeroesOfTheStorm_x64_dxgi.log)

- dxvk install log: 
[dxvk_install.log](https://github.com/doitsujin/dxvk/files/2775449/dxvk_install.log)

**Comment by Anti-Ultimate** [comment]
You're using an outdated driver. Could you upgrade to the latest version? (415.27. 410.93 is also fine)

**Comment by mmiat** [comment]
sorry doesnt understand, i've 415.27
415.27-0ubuntu0~gpu18.04.1 downloaded from http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu

**Comment by doitsujin** [comment]
So did you solve your issue then?

**Comment by mmiat** [comment]
yes it's solved
