### ISSUE TITLE
ABOUT BATTLEYE AND OTHERS ANTI CHEATS

### ISSUE THREAD

**Issue by julianovs** [doitsujin/dxvk#880]
I do not know if you and the valve developers have already done this but could not contact the anti-cheat developers like battleye, vac, etc and ask them to collaborate with steam proton by making anti cheat work?
You and the valve guys did a wonderful thing for us who want to play on linux, what is missing now is just a few people also make their contribution to more and more things going forward and getting better

maybe a good conversation between you all can come out good things !!

**Comment by doitsujin** [comment]
Yeah, that. Also, it's not like this is a revolutionary idea or anything, it's just not as simple as that.
