### ISSUE TITLE
Injustice 2

### ISSUE THREAD

**Issue by massatt212** [doitsujin/dxvk#881]
### Software information
Injustice 2
Moded Unreal Engine 3 Game Like MKX

### System information
- GPU: GTX 1050 TI
- Driver: 415.27
- Wine version: 4.0 R6
- DXVK version: 0.95 and 0.94

### Apitrace file(s)
- Put a link here None yet

### Log files
[Injustice2_d3d11.log](https://github.com/doitsujin/dxvk/files/2784301/Injustice2_d3d11.log)
[Injustice2_dxgi.log](https://github.com/doitsujin/dxvk/files/2784302/Injustice2_dxgi.log)

Screen Shot Where it sticks
![screenshot from 2019-01-22 15-32-46](https://user-images.githubusercontent.com/43518479/51560597-52b59580-1e5b-11e9-8d17-675820b4bc5b.png)

**Comment by d10sfan** [comment]
From a comment on a similar proton thread, it sounds like this game does not work due to missing media foundation implementation in wine itself

**Comment by massatt212** [comment]
Possible it can be wine, but GTA V has the same media codes
