### ISSUE TITLE
Kingdom Come Deliverance, smoke flickering

### ISSUE THREAD

**Issue by qarmin** [doitsujin/dxvk#882]
### Software information
Kingdom Come Deliverance GOG - 1920x1080 Full Screen and Borderless, Quality Low and Ultra

### System information
- GPU: GTX 970
- Driver: 415.27
- Wine version: 4.0 rc6 staging
- DXVK version: 0.95  b1540a1 (I created logs with version cfc3f68)

### Apitrace file(s)
I will try to do this later if will be needed

### Log files
- d3d11.log: [KingdomCome_d3d11.log](https://github.com/doitsujin/dxvk/files/2784436/KingdomCome_d3d11.log)
- dxgi.log:  [KingdomCome_dxgi.log](https://github.com/doitsujin/dxvk/files/2784433/KingdomCome_dxgi.log)

### Save File
[save060.zip](https://github.com/doitsujin/dxvk/files/2784445/save060.zip) (/home/rafal/.wine/drive_c/users/rafal/Saved Games/kingdomcome)

### Video with flickering
https://streamable.com/cwni7

Sometimes when I move fast on a horse with a torch, I can see that sometimes the fire is outside of it. It is possible that this is a problem with the game or with my vsync settings but unfortunately I do not have a computer with a windows to check it. - https://streamable.com/dzg5f

**Comment by doitsujin** [comment]
Both these issues look like potential game bugs, are you sure that the smoke thing doesn't happen on Windows?

**Comment by qarmin** [comment]
I don't know, I haven't any windows machine to check this.

**Comment by doitsujin** [comment]
This doesn't look like a driver/dxvk bug tbh, just a limitation of the game's particle lighting system.

I do have the game, but can't test it on Windows at the moment.

**Comment by jarrard** [comment]
Do you have improved prefix mod installed? that has a enhanced volumetric fog setting that causes flickering when looking into fire based light stuff. 

But I do agree the game may just be bugged because the prefix mod use to work just fine until warhorse broke something and seemingly haven't bothered to fix whatever that was...

**Comment by qarmin** [comment]
I tried to reproduce bug, but with DXVK 1.5.5 I'm unable to run game because it crash and shows this error
```
wine: Call from 0x7b02cde6 to unimplemented function amd_ags_x64.dll.agsGetCrossfireGPUCount, aborting
```
I can run game with vanilla Wine

**Comment by doitsujin** [comment]
@qarmin that problem has nothing to do with DXVK. Please make sure that you don't have a DLL override for `amd_ags_x64` in your wine configuration.
