### ISSUE TITLE
Resident Evil 2 remake stucks at the loading screen

### ISSUE THREAD

**Issue by SergeyLatyshev** [doitsujin/dxvk#886]
In RESIDENT EVIL 2 / BIOHAZARD RE:2 I can play the intro level (at the gas station) which ends with a cutscene where Leon and Claire are driving the police car. After that there is a loading screen, but the game doesn't load the next level. If I quit the game with Alt+F4, I see this error:
![re2r_2019-01-25_20-55-29](https://user-images.githubusercontent.com/28780380/51782782-6e75b000-2169-11e9-8498-f03cc34458f2.png)

### Software information

RESIDENT EVIL 2 / BIOHAZARD RE:2
https://store.steampowered.com/app/883710/
I tried max and min graphics settings, both characters.

### System information
- GPU: Nvidia GTX 1060 6GB
- Driver: 415.27
- Wine version: Proton 3.16-6 beta and wine-4.0-rc7 (Staging)
- DXVK version: 0.95. I tried to compile a newer version, but get errors like these:
`error: ‘mutex’ in namespace ‘std’ does not name a type`
`error: ‘mutex’ is not a member of ‘std’`

**Comment by SergeyLatyshev** [comment]
I followed the instructions, and now the game crashes when I try to load it. I had to delete steamapps/compatdata/883710/pfx folder.

**Comment by james-munson** [comment]
@SergeyLatyshev make sure to use newest dvxk

**Comment by SergeyLatyshev** [comment]
I use v0.95.

**Comment by SergeyLatyshev** [comment]
AFAIR, there was a similar '...dx11.cpp' error in the demo with DXVK 0.94 which has gone in 0.95, so I thought it's a DXVK bug. Sorry if I'm wrong.

Anyway, I tried what was suggested in the comments of that video, but it either didn't help, or started to crash the game when I load a savefile.

My log file:
[steam-883710.zip](https://github.com/doitsujin/dxvk/files/2798969/steam-883710.zip)

**Comment by doitsujin** [comment]
Apologies, referenced the wrong commit there.

**Comment by DistantThunder** [comment]
Just to say I got this running on my end with those same drivers and that same GPU and manually upgraded DXVK 0.95.

**Comment by DistantThunder** [comment]
I have to say, however, I'm experiencing an after image "blinking" phenomenon... Every once in a while, a former image will blink on the screen.

This happens only with the cursor in the menu and then with the whole screen in-game...

**Comment by doitsujin** [comment]
Do you play with keyboard and mouse? If so, that's an input issue where the camera perspective changes rapidly for some reason, not a rendering issue.

**Comment by DistantThunder** [comment]
Indeed I play with Keyboard and mouse.

Mmh, must be it, would you know a fix?

**Comment by doitsujin** [comment]
Apart from using a controller, no.

**Comment by DistantThunder** [comment]
Ok. I'm stuck in mf shenanigans anyway. Thanks.

**Comment by DistantThunder** [comment]
As a side note, the bug disappears when running the game Windowed...

**Comment by laichiaheng** [comment]
@SergeyLatyshev Thanks! It works!
Although the performance is awful on Proton.

**Comment by DistantThunder** [comment]
@laichiaheng Haven't you forgotten to switch off Wine debugging after you were done?

**Comment by laichiaheng** [comment]
@DistantThunder Isn't it disabled by default?

**Comment by mixalis1987** [comment]
I followed the instructions and I keep getting errors.

`./install-mf-64.sh 
mediafoundation
/home/michael/Downloads/python-installcab-master/installcab.py:175: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for registry_key in registry_keys[0].getchildren():
- amd64_microsoft-windows-mediafoundation_31bf3856ad364e35_6.1.7601.17514_none_fa8534ab236134c4.manifest (win64)
- wow64_microsoft-windows-mediafoundation_31bf3856ad364e35_6.1.7601.17514_none_04d9defd57c1f6bf.manifest (wow64)
Traceback (most recent call last):
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 243, in process_files
    install_dll(file_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 214, in install_dll
    dest_dir = get_dll_destdir(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 65, in get_dll_destdir
    arch = check_dll_arch(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 85, in check_dll_arch
    if 'x86-64' in out:
TypeError: a bytes-like object is required, not 'str'
mf
- amd64_microsoft-windows-mf_31bf3856ad364e35_6.1.7601.17514_none_ab34ec409a77d93c.manifest (win64)
- wow64_microsoft-windows-mf_31bf3856ad364e35_6.1.7601.17514_none_b5899692ced89b37.manifest (wow64)
mfreadwrite
/home/michael/Downloads/python-installcab-master/installcab.py:175: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for registry_key in registry_keys[0].getchildren():
- amd64_microsoft-windows-mfreadwrite_31bf3856ad364e35_6.1.7601.17514_none_177bed732ea3f85f.manifest (win64)
- wow64_microsoft-windows-mfreadwrite_31bf3856ad364e35_6.1.7601.17514_none_21d097c56304ba5a.manifest (wow64)
Traceback (most recent call last):
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 243, in process_files
    install_dll(file_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 214, in install_dll
    dest_dir = get_dll_destdir(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 65, in get_dll_destdir
    arch = check_dll_arch(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 85, in check_dll_arch
    if 'x86-64' in out:
TypeError: a bytes-like object is required, not 'str'
wmadmod
/home/michael/Downloads/python-installcab-master/installcab.py:175: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for registry_key in registry_keys[0].getchildren():
- amd64_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_e474f0ac34979bc4.manifest (win64)
- x86_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_885655287c3a2a8e.manifest (win32)
Traceback (most recent call last):
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 243, in process_files
    install_dll(file_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 214, in install_dll
    dest_dir = get_dll_destdir(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 65, in get_dll_destdir
    arch = check_dll_arch(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 85, in check_dll_arch
    if 'x86-64' in out:
TypeError: a bytes-like object is required, not 'str'
wmvdecod
/home/michael/Downloads/python-installcab-master/installcab.py:175: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for registry_key in registry_keys[0].getchildren():
- amd64_microsoft-windows-wmvdecod_31bf3856ad364e35_6.1.7601.17514_none_20b089c0f6efacae.manifest (win64)
- x86_microsoft-windows-wmvdecod_31bf3856ad364e35_6.1.7601.17514_none_c491ee3d3e923b78.manifest (win32)
Traceback (most recent call last):
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 243, in process_files
    install_dll(file_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 214, in install_dll
    dest_dir = get_dll_destdir(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 65, in get_dll_destdir
    arch = check_dll_arch(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 85, in check_dll_arch
    if 'x86-64' in out:
TypeError: a bytes-like object is required, not 'str'
wmadmod
/home/michael/Downloads/python-installcab-master/installcab.py:175: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for registry_key in registry_keys[0].getchildren():
- amd64_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_e474f0ac34979bc4.manifest (win64)
- x86_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_885655287c3a2a8e.manifest (win32)
Traceback (most recent call last):
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 243, in process_files
    install_dll(file_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 214, in install_dll
    dest_dir = get_dll_destdir(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 65, in get_dll_destdir
    arch = check_dll_arch(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 85, in check_dll_arch
    if 'x86-64' in out:
TypeError: a bytes-like object is required, not 'str'

Done!
Now you need to get mfplat.dll version 12.0.7601.23471 from elsewhere and place it in your application directory`

Anyone know what its talking about? Did I place the `python-installcab-master` folder in the wrong place or something? I also have `~/.cache/winetricks/win7sp1/windows6.1-KB976932-X64.exe`

Game keeps getting stuck loading after the gas station still.

**Comment by ahmed-elsayed2017** [comment]
**The edited script:** 
[python-installcab-master.zip](https://github.com/doitsujin/dxvk/files/2810674/python-installcab-master.zip)

**Comment by mixalis1987** [comment]
Yea got it fixed in the end. https://www.youtube.com/watch?v=JCPgIyZTHA0

**Comment by prometeh** [comment]
just wanted to say installcab.py is in python2 so if you are on a distro like Arch Linux, instead of the third step on  https://github.com/doitsujin/dxvk/issues/886#issuecomment-458487008 use this (assuming you are in the installcab.py directory):

`python2 installcab.py ~/.cache/winetricks/win7sp1/windows6.1-KB976932-X64.exe mediafoundation`
`python2 installcab.py ~/.cache/winetricks/win7sp1/windows6.1-KB976932-X64.exe _mf`
`python2 installcab.py ~/.cache/winetricks/win7sp1/windows6.1-KB976932-X64.exe mfreadwrite`
`python2 installcab.py ~/.cache/winetricks/win7sp1/windows6.1-KB976932-X64.exe wmadmod`
`python2 installcab.py ~/.cache/winetricks/win7sp1/windows6.1-KB976932-X64.exe wmvdecod`

the mfplat.dll file in https://github.com/ValveSoftware/Proton/files/2705555/WMF_workaround.zip is working for me.

**Comment by Sur3** [comment]
The link to that workaround.zip seems broken.. :-/

**Comment by ahmed-elsayed2017** [comment]
> The link to that workaround.zip seems broken.. :-/

Use that one >>> https://github.com/doitsujin/dxvk/files/2810674/python-installcab-master.zip

**Comment by SergeyLatyshev** [comment]
That archive probably was removed. Distributing Windows files isn't legal, so you'll have to find mfplat.dll elsewhere. It's in C:\Windows\system32 on every computer with Windows 7 (I'm not sure if Win10 version works.)

**Comment by ahmed-elsayed2017** [comment]
I searched for `mfplat.dll version 12.0.7601.23471` using https://duckduckgo.com/ and it was the second in the search result (make sure that it is for windows 7 (64bit) or it won't work)

**Comment by mixalis1987** [comment]
@SergeyLatyshev Not tested myself if win10 mfplat works but it was reported not to. Only Win7

**Comment by mixalis1987** [comment]
@Sur3 did you install mf first from winetricks?

**Comment by ahmed-elsayed2017** [comment]
Start over with a clean prefix.

**Comment by laichiaheng** [comment]
How to do it with Lutris or Wine, there is no `/your_path_to_steam_library/steamapps/compatdata/883710/pfx/` in their steam path.

**Comment by SergeyLatyshev** [comment]
In Wine it's just `~/.wine` and you don't even need to export it, in Lutris it's whatever your wineprefix is. But I'd recommend to not use the default Wine prefix just in case something goes wrong and your wineprefix gets broken.

**Comment by mixalis1987** [comment]
@laichiaheng Made a video for you for making and finding the WINEPREFIX of Lutris to work with.
https://www.youtube.com/watch?v=HYCCsGatnrg
Sorry for quality didn't know when I was recording it was low.

**Comment by Sur3** [comment]
Using a new prefix seems not to have helped.. May I ask what Windows-Version do you have set in winecfg?

**Comment by mixalis1987** [comment]
@Sur3 Windows 7

**Comment by Sur3** [comment]
thx, I have it set to windows 10 in my old prefix, but windows 7 in my new one, I'll try some other things with the new prefix then.. ^^

**Comment by mixalis1987** [comment]
Just finished Clairs chapter..no problems at all FPS was great all the way on max settings.

**Comment by Sur3** [comment]
You also use wine to run the game, so you also use the windows version of steam like I do to run it?

**Comment by mixalis1987** [comment]
@Sur3 No I use native steam to run the game. I use Proton to run the game version 3.16-6 Beta Proton

**Comment by Sur3** [comment]
Ahh ok, yeah with the linux version of steam I also can only use proton and not my wine-staging because wine only works with the windows version of steam and otehrwise says it cant connect to the steam api, but I get the same mfreadwrite error at least with proton/linux-steam or wine-staging/windows-steam. ^^

**Comment by Sur3** [comment]
Ups sry i was in the wrong prefix dir, this is the right one:
e8706a051bffc9da9e9b935aaa432aac  ./windows/system32/mfreadwrite.dll
bfebb6f76a0988a38260870c61a6d1b7  ./windows/syswow64/mfreadwrite.dll

**Comment by mixalis1987** [comment]
md5sum for mfplat: 2188de5fa5c741fb2b81eb9f37d26ba7  mfplat.dll
md5sum for mfreadwrite system32: e8706a051bffc9da9e9b935aaa432aac  mfreadwrite.dll
md5sum for mfreadwrite syswow64: bfebb6f76a0988a38260870c61a6d1b7  mfreadwrite.dll

Looks the same.

**Comment by Sur3** [comment]
Ok thanks, weird then the error must be somewhere else, probably some zombie ghosts.. ^^"

**Comment by Sur3** [comment]
Ok I finally got it working, the problem was I _commented_ out the lines in the install script, should have read the instructions more carefully.. :upside_down_face:

**Comment by mixalis1987** [comment]
@Sur3 Glad it's working for you now. I'm on my second play through lol

**Comment by ahmed-elsayed2017** [comment]
@SergeyLatyshev Close this issue man. It is not DXVK issue, and it is fixed.

**Comment by Phil25** [comment]
If anyone is viewing this issue still in hopes to run RE2 through Proton, I've made a comprehensive guide detailing every fix and every step: https://steamcommunity.com/sharedfiles/filedetails/?id=1654060648

**Comment by Phil25** [comment]
It seems that as of the recent Proton 3.16-7 update, RE2 runs without any additional configuration. Even without mfplat.dll

**Comment by ahmed-elsayed2017** [comment]
> It seems that as of the recent Proton 3.16-7 update, RE2 runs without any additional configuration. Even without mfplat.dll

mfplat.dll helps running the video files. It doesn't stop the game from running at the beginning.

**Comment by Phil25** [comment]
> > It seems that as of the recent Proton 3.16-7 update, RE2 runs without any additional configuration. Even without mfplat.dll
> 
> mfplat.dll helps running the video files. It doesn't stop the game from running at the beginning.

Yes, you're right. I've played after a few cutscenes from a save file later in game thinking it was fine. It seems the opening cinematic after the gas station is the only thing needing mf.

**Comment by SergeyLatyshev** [comment]
> Yes, you're right. I've played after a few cutscenes from a save file later in game thinking it was fine. It seems the opening cinematic after the gas station is the only thing needing mf.

All cinematics need mf actually, including video on surveillance cameras.

**Comment by mixalis1987** [comment]
yes all videos cutscenes and camera, computers etc need mfplat

**Comment by ahmed-elsayed2017** [comment]
With MF workaround, the game crashes everytime when I use _the laptop_ inside the _police station_.

**mf.dll** checksum is `20ecac7791dcba69121631cb627e5a96`
**mfreadwrite.dll** checksum is `e8706a051bffc9da9e9b935aaa432aac`
**mfplat.dll** checksum is `2188de5fa5c741fb2b81eb9f37d26ba7`

The crash happens because of **mfreadwrite.dll** from what appears in the crash report. Any ideas beside not doing the workaround right, because I am sure that I did everything right, and it works fine with **Resident Evil 7 Biohazard**.

**Comment by bkdwt** [comment]
> Guys, guys, it works! The instruction:
> 
>     1. Download scripts from https://github.com/tonix64/python-installcab
> 
>     2. Edit installcab.py the way described here: [tonix64/python-installcab#1](https://github.com/tonix64/python-installcab/issues/1)
>        (uncomment lines 129-137 which look like `value = value.replace("%SystemRoot%", "C:\\windows")`)
> 
>     3. Launch the terminal in the folder with these scripts and run this:
>        `$ export WINEPREFIX=/your_path_to_steam_library/steamapps/compatdata/883710/pfx/`
>        `$ ./install-mf-64.sh`
> 
>     4. Copy mfplat.dll to /your_path_to_steam_library/steamapps/common/RESIDENT EVIL 2  BIOHAZARD RE2/
>        That's it!
> 
> 
> My terminal output:
> 
> > $ ./install-mf-64.sh
> > mediafoundation
> > 
> > * wow64_microsoft-windows-mediafoundation_31bf3856ad364e35_6.1.7601.17514_none_04d9defd57c1f6bf.manifest (wow64)
> > * amd64_microsoft-windows-mediafoundation_31bf3856ad364e35_6.1.7601.17514_none_fa8534ab236134c4.manifest (win64)
> > * mf.dll -> /2TB/Games/Linux/Steam/steamapps/compatdata/883710/pfx/drive_c/windows/syswow64
> > * mf.dll -> /2TB/Games/Linux/Steam/steamapps/compatdata/883710/pfx/drive_c/windows/system32
> > * mfps.dll -> /2TB/Games/Linux/Steam/steamapps/compatdata/883710/pfx/drive_c/windows/system32
> >   002f:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
> >   002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
> >   002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
> >   002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
> >   002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
> >   002f:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
> >   002f:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
> >   0033:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
> >   0033:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
> >   0033:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
> >   0023:fixme:dwmapi:DwmIsCompositionEnabled 0x6dbd1518
> >   0035:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x69ebd3de, context 0x856590, init_notify 0, handle 0x114fa10): stub
> >   004f:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
> >   004f:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
> >   004f:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
> >   004d:fixme:dwmapi:DwmIsCompositionEnabled 0x6d5d3018
> >   0051:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x6a0cb608, context 0x8d8870, init_notify 0, handle 0x111fc88): stub
> >   wine: configuration in '/2TB/Games/Linux/Steam/steamapps/compatdata/883710/pfx' has been updated.
> >   mf
> > * wow64_microsoft-windows-mf_31bf3856ad364e35_6.1.7601.17514_none_b5899692ced89b37.manifest (wow64)
> > * amd64_microsoft-windows-mf_31bf3856ad364e35_6.1.7601.17514_none_ab34ec409a77d93c.manifest (win64)
> >   mfreadwrite
> > * wow64_microsoft-windows-mfreadwrite_31bf3856ad364e35_6.1.7601.17514_none_21d097c56304ba5a.manifest (wow64)
> > * amd64_microsoft-windows-mfreadwrite_31bf3856ad364e35_6.1.7601.17514_none_177bed732ea3f85f.manifest (win64)
> > * mfreadwrite.dll -> /2TB/Games/Linux/Steam/steamapps/compatdata/883710/pfx/drive_c/windows/system32
> > * mfreadwrite.dll -> /2TB/Games/Linux/Steam/steamapps/compatdata/883710/pfx/drive_c/windows/syswow64
> >   wmadmod
> > * amd64_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_e474f0ac34979bc4.manifest (win64)
> > * x86_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_885655287c3a2a8e.manifest (win32)
> > * wmadmod.dll -> /2TB/Games/Linux/Steam/steamapps/compatdata/883710/pfx/drive_c/windows/syswow64
> > * wmadmod.dll -> /2TB/Games/Linux/Steam/steamapps/compatdata/883710/pfx/drive_c/windows/system32
> >   wmvdecod
> > * x86_microsoft-windows-wmvdecod_31bf3856ad364e35_6.1.7601.17514_none_c491ee3d3e923b78.manifest (win32)
> > * amd64_microsoft-windows-wmvdecod_31bf3856ad364e35_6.1.7601.17514_none_20b089c0f6efacae.manifest (win64)
> > * wmvdecod.dll -> /2TB/Games/Linux/Steam/steamapps/compatdata/883710/pfx/drive_c/windows/syswow64
> > * wmvdecod.dll -> /2TB/Games/Linux/Steam/steamapps/compatdata/883710/pfx/drive_c/windows/system32
> >   wmadmod
> > * amd64_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_e474f0ac34979bc4.manifest (win64)
> > * x86_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_885655287c3a2a8e.manifest (win32)
> > * wmadmod.dll -> /2TB/Games/Linux/Steam/steamapps/compatdata/883710/pfx/drive_c/windows/syswow64
> > * wmadmod.dll -> /2TB/Games/Linux/Steam/steamapps/compatdata/883710/pfx/drive_c/windows/system32
> > 
> > Done!
> > Now you need to get mfplat.dll version 12.0.7601.23471 from elsewhere and place it in your application directory
> > (it was different before editing the script and had errors)
> 
> A screenshot from the video that wasn't played before:
> ![20190129175846_1](https://user-images.githubusercontent.com/28780380/51901197-0e456f00-23f2-11e9-9fb8-9ec642e600da.jpg)
> 
> A game screenshot after:
> ![20190129180230_1](https://user-images.githubusercontent.com/28780380/51901271-3339e200-23f2-11e9-8554-658d29d56536.jpg)
> 
> Don't forget to replace the old DXVK files in `/your_path_to_steam_library/steamapps/common/Proton 3.16 Beta/dist/lib64/wine/dxvk/` with the newest version 0.96.
> Also, run `winetricks mf` before executing the Python script to make sure you have file `~/.cache/winetricks/win7sp1/windows6.1-KB976932-X64.exe` to extract dlls from.

It's possible to do this with a no-legitimate copy of the game without steam?

**Comment by SergeyLatyshev** [comment]
> It's possible to do this with a no-legitimate copy of the game without steam?

I suppose it is, just don't use WINEPREFIX or set it to `~/.wine`.

**Comment by mixalis1987** [comment]
No you must set the correct wine prefix if your going to use wine.

**Comment by doitsujin** [comment]
Please don't talk about piracy on my bug tracker.
