### ISSUE TITLE
WineD3D Vulkan Plans & Why DXVK Isn't Being Used

### ISSUE THREAD

**Issue by amayra** [doitsujin/dxvk#887]
after i read Wine mailing list and phoronix article about dxvk i'm curious to know why you refused cooperation with them and don't even answer any email they send you 

Wine mailing list :
https://www.winehq.org/pipermail/wine-devel/2019-January/138023.html

phoronix article : 

https://www.phoronix.com/scan.php?page=news_item&px=WineD3D-Vulkan-Details

**Comment by Kerrung** [comment]
Indeed, @doitsujin , we all are interested to find out that this is why you ignored all the proposals of Wine developers about cooperation? Please give us your comments on this topic. Why is this happening like this?

**Comment by doitsujin** [comment]
As I said on Reddit: I'm not going to engage in Internet Drama.
