### ISSUE TITLE
Warframe crashes during launch with DXVK after 24.2.X

### ISSUE THREAD

**Issue by danielimperial** [doitsujin/dxvk#888]
Hello. At the moment of the writing, Warframe is on version 24.2.10. However, the issue with launching has begun since the 24.2 update (The Profit-Taker). I installed the game via Lutris using the [GloriusEggroll script](https://gitlab.com/GloriousEggroll/warframe-linux). Didn't touch nor tweaked anything: as it shipped, it launched perfectly just before this update.

Now, it's somehow not working anymore. After the update script, the game just crashes at launch. No load screen, just the standard crash report.

EDIT: The game opens up just fine without DXVK.

### Software information
Warframe using Lutris and Wine64. All graphical configurations set to low. Borderless fullscreen. No additional arguments.

### System information
- GPU: Nvidia GT 750M
- Driver: 415.27
- Wine version: wine-4.0-rc6 (Staging)
- DXVK version: 0.90

### Apitrace file(s)
I wasn't able to create a trace. If someone could help me out on that, I'm new on this stuff, and there is no Warframe.exe. 

```
wine64 apitrace trace -a dxgi Warframe-Launcher.bat 
000b:fixme:winediag:start_process Wine Staging 4.0-rc6 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
wine: cannot find L"C:\\windows\\system32\\apitrace.exe"

```

### Log files
- d3d11.log: [Warframe.x64_d3d11.log](https://github.com/doitsujin/dxvk/files/2799338/Warframe.x64_d3d11.log)
- dxgi.log: [Warframe.x64_dxgi.log](https://github.com/doitsujin/dxvk/files/2799340/Warframe.x64_dxgi.log)

**Comment by doitsujin** [comment]
From your logs:
```
err:   DxvkSurface::getSurfaceFormats: Failed to query surface formats
err:   DXGI: DxgiSwapChain: Failed to create presenter or back buffer
```
This would explain the crash, but I frankly have no idea what could cause this to happen. Can you please attach the full wine log / console output?

**Comment by danielimperial** [comment]
Lutris output:

```
INFO     2019-01-27 00:02:41,434 [runner]:Runtime disabled by system configuration
INFO     2019-01-27 00:02:41,565 [dxvk]:Replacing /home/imperial/Games/warframe/drive_c/windows/system32/dxgi with DXVK version
INFO     2019-01-27 00:02:41,589 [dxvk]:Replacing /home/imperial/Games/warframe/drive_c/windows/system32/d3d11 with DXVK version
INFO     2019-01-27 00:02:41,604 [dxvk]:Replacing /home/imperial/Games/warframe/drive_c/windows/system32/d3d10core with DXVK version
INFO     2019-01-27 00:02:41,604 [dxvk]:Replacing /home/imperial/Games/warframe/drive_c/windows/system32/d3d10_1 with DXVK version
INFO     2019-01-27 00:02:41,605 [dxvk]:Replacing /home/imperial/Games/warframe/drive_c/windows/system32/d3d10 with DXVK version
INFO     2019-01-27 00:02:41,605 [dxvk]:Replacing /home/imperial/Games/warframe/drive_c/windows/syswow64/dxgi with DXVK version
INFO     2019-01-27 00:02:41,606 [dxvk]:Replacing /home/imperial/Games/warframe/drive_c/windows/syswow64/d3d11 with DXVK version
INFO     2019-01-27 00:02:41,606 [dxvk]:Replacing /home/imperial/Games/warframe/drive_c/windows/syswow64/d3d10core with DXVK version
INFO     2019-01-27 00:02:41,607 [dxvk]:Replacing /home/imperial/Games/warframe/drive_c/windows/syswow64/d3d10_1 with DXVK version
INFO     2019-01-27 00:02:41,607 [dxvk]:Replacing /home/imperial/Games/warframe/drive_c/windows/syswow64/d3d10 with DXVK version
INFO     2019-01-27 00:02:42,142 [runner]:Runtime disabled by system configuration
```

Couldn't execute the updater.exe nor the Warframe-launcher.bat files with wine to catch the logs with Wine. I installed it via Lutris, so maybe that's the issue. I will try installing it via the script given within the game files and return.

**Comment by NeroBurner** [comment]
could you try with the standalone version from `master`?

**Comment by newnah** [comment]
This issue can most likely be attributed to xaudio2_7. Wine 3.19 came with a patch for xaudio2_7 "Don't return XAudio28 interface for XAudio2[0..7] objects in QueryInterface().". In my experience this solved issues in other games but left Warframe unable to launch. You can build wine staging via tkg and create your own patch with this removed, however I recommend just sicking with wine staging 3.18 for the time being. I noticed that you said you use gloriousegroll's script but you are using wine 4, his script strictly specifies to use 3.18. You probably just updated accidentally. Hope this solves the issue.

**Comment by NeroBurner** [comment]
@doitsujin @danielimperial I recommend closing this issue as it has nothing to do with DXVK rather with an outdated Lutris script
