### ISSUE TITLE
Endless Legend and Endless Space pink screen

### ISSUE THREAD

**Issue by clapbr** [doitsujin/dxvk#890]
Both games start but when main menu loads the full screen turns into a plain pink color. Wined3d plays fine.
### Software information
Endless Legend and Endless Space (both with -force-d3d11)

### System information
- GPU: Saphire RX 580 8gb Nitro
- Driver: RADV (also tested AMDVLK and got same behavior)
- Wine version: 4.0 staging
- DXVK version: 0.96+ master

### Apitrace file(s)
- I didn't understand if the apitrace should be recorded with dxvk or stock wined3d, please clarify.

### Log files
- d3d11.log: [EndlessLegend_d3d11.log](https://github.com/doitsujin/dxvk/files/2799700/EndlessLegend_d3d11.log)

- dxgi.log: [EndlessLegend_dxgi.log](https://github.com/doitsujin/dxvk/files/2799701/EndlessLegend_dxgi.log)

**Comment by doitsujin** [comment]
> I didn't understand if the apitrace should be recorded with dxvk or stock wined3d, please clarify.

wined3d if it works fine.

**Comment by doitsujin** [comment]
This is what it looks like on my Windows 10 install:

![endlesslegend](https://user-images.githubusercontent.com/25567304/51798184-214c1980-220f-11e9-9b9b-2590a5f66c49.png)

So yeah, there's nothing to fix here. wined3d also only renders anything meaningful **without** the  `-force-d3d11` flag.
