### ISSUE TITLE
Mirror's Edge Catalyst crash with DXVK 0.93 and above.

### ISSUE THREAD

**Issue by mixalis1987** [doitsujin/dxvk#893]
Note: Would provice apitrace but don't know how to on Lutris. Just thought you should know that any version of DXVK above 0.92 breaks Mirror's Edge Catalyst, game wont load all you see is a white screen and FPS counter stops so you know it freezes. Versions of DXVK I tested from 0.92 and lower makes the game work fine.

I thought I should mention this because newer DXVK versions say they have improvements with CPU load etc.

### Software information
Mirror's Edge Catalyst

### System information
- GPU: Nvidia
- Driver: 415.27
- Wine version: tkg-4.0 default (other versions also do the same) 
- DXVK version: 0.93 and above

### Apitrace file(s)
Dont know how to make one with Lutris

### Log files
- d3d11.log: Don't know how
- dxgi.log: Don't know how

**Comment by Guy1524** [comment]
This looks like yet another game which doesn't respond well to the AMD spoof( 5d49644 ).  You should try and see if adding `dxgi.nvapiHack = True` to your config file fixes it.

**Comment by mixalis1987** [comment]
@doitsujin Oh your right! the logs are in the exe directory dumb old me! Ok I will try that and see.

**Comment by mixalis1987** [comment]
@doitsujin Every time I add that line the game just removes it. Tried changing the permissions of the file to read only but it wont let me change them either not even as root user. 
Adding the logs below if they help. the DXGI log mentions this `DXGI: NvAPI workaround enabled, reporting AMD GPU`
[MirrorsEdgeCatalyst_d3d11.log](https://github.com/doitsujin/dxvk/files/2813205/MirrorsEdgeCatalyst_d3d11.log)
[MirrorsEdgeCatalyst_dxgi.log](https://github.com/doitsujin/dxvk/files/2813206/MirrorsEdgeCatalyst_dxgi.log)

**Comment by doitsujin** [comment]
You're not supposed to add that line to the log files, but to a file `dxvk.conf` next to the game's executable, see [Wiki](https://github.com/doitsujin/dxvk/wiki/Configuration).

**Comment by mixalis1987** [comment]
@doitsujin I didn't have that config so I created it and copied and pasted what was written in the wiki and uncommented that line needed. Then placed the dxvk.conf file in the games folder. That right? But that didn't fix it either.

**Comment by doitsujin** [comment]
Can you attach new logs?

**Comment by mixalis1987** [comment]
[MirrorsEdgeCatalyst_d3d11.log](https://github.com/doitsujin/dxvk/files/2813441/MirrorsEdgeCatalyst_d3d11.log)
[MirrorsEdgeCatalyst_dxgi.log](https://github.com/doitsujin/dxvk/files/2813442/MirrorsEdgeCatalyst_dxgi.log)

**Comment by Guy1524** [comment]
@mixalis1987 You need to set the value to false, not true, like I mentioned in my earlier post.

**Comment by mixalis1987** [comment]
@Guy1524 Your right that fixed it, game runs fine now. Also noticed some increase in speed.

**Comment by Guy1524** [comment]
@mixalis1987 My bad.

**Comment by mixalis1987** [comment]
@Guy1524 Lol it happens. No probs.
