### ISSUE TITLE
Tekken 7 - Severe bottleneck in certain stages

### ISSUE THREAD

**Issue by Waistless** [doitsujin/dxvk#894]
It seems like certain stages in this game bottleneck at 100% GPU usage, even at low settings.

The most troubled stages are **Brimstone and Fire**, where at most camera angles sidestepping around the framerate drops to ~50 (with a few angles climbing back to 60), and in **Arctic Snowfall**, where the framerate stays at around 35fps, despite being easily capable of 60 at equivalent settings in D3D11.

I have also encountered performance issues in the mishima building and forgotten realm. This performance level is consistent in different linux distros (Kubuntu and Arch) and Windows, ruling out a proton/platform specific issue.

Screenshots with DXVK hud=full attached. 

1st screenshot: Twilight Conflict stage working well at 60fps.
![20190130165208_1](https://user-images.githubusercontent.com/43065289/51964003-eff27880-24b0-11e9-8b9e-08823e043c89.jpg)
2nd screenshot: Brimstone and Fire
![20190130165316_1](https://user-images.githubusercontent.com/43065289/51964015-f41e9600-24b0-11e9-8f65-21fa32f59ae0.jpg)
3rd screenshot: Arctic Snowfall
![20190130165408_1](https://user-images.githubusercontent.com/43065289/51964022-f8e34a00-24b0-11e9-9095-963908986ce5.jpg)

Going from a mix of high/medium settings to all low settings: performance in Arctic snowfall barely increases up to 41fps. None of the dxvk.conf options listed in the wiki had a noticeable impact.

Note: Graphics pipelines appears to incrementally increase across different maps, loading the Arctic snowfall map first will result in less than 1000 pipelines and will not have any effect on performance.

[TekkenGame-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/2811424/TekkenGame-Win64-Shipping_d3d11.log)
[TekkenGame-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/2811425/TekkenGame-Win64-Shipping_dxgi.log)

### System information
- CPU: Ryzen 5 1600X @ 4GHz
- RAM: 16GB
- GPU: Nvidia GTX 960 4GB
- Driver: 417.35 (Windows) | 415.27 (Linux)
- DXVK version: 0.96

The current workaround is to use potato versions of these maps https://www.tapatalk.com/groups/sfxt_mods/tekken-7-stage-modding-t1476.html   Although ideally if these issues can be fixed at the very least for arctic snowfall it would likely improve performance across the board.

edit: should mention when stress testing, always pick 2 bears, seems to put a strain on the engine. I did not pick bears in this instance to show the performance problems as being purely stage related.
edit2: reuploaded log files with debug flag enabled

**Comment by Tk-Glitch** [comment]
@Waistless I have provided a trace to Doitsujin with both Arctic Snowfall and Brimstone and Fire, just in case.

**Comment by Waistless** [comment]
Thanks @Tk-Glitch , had generated one of arctic snowfall but had to compress and upload. Would by any chance a vktrace whilst using dxvk be useful? If I get figure out/if its possible to get working.

**Comment by doitsujin** [comment]
vktrace is sadly not in a usable state, no.

**Comment by Waistless** [comment]
Unusable as in you can't use what it outputs? Well if so then that's a shame, I'll leave this here anyway just in case or if one day it becomes usable:  https://drive.google.com/open?id=14dhr9yBBGbI4wfM6vBn4rT_zC8LMJrXo

(Generated under DXVK + Windows, VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_vktrace)

**Comment by massatt212** [comment]
Glad to know it's not me alone

**Comment by doitsujin** [comment]
Does the game have an option to disable Tessellation? The trace @Tk-Glitch shared shows that the game uses it in a rather inefficient way, which might very well be the cause of your performance issues.

**Comment by BlazeKl** [comment]
the game doesn't have an option for tessellation, the graphics menu is not very specific on what it is actually enabling, is @Tk-Glitch 's trace using high settings? maybe the low preset deactivates tessellation

**Comment by doitsujin** [comment]
@Waistless ping? Can you try setting the maximum tessellation factor to 8 as described on the [wiki](https://github.com/doitsujin/dxvk/wiki/Configuration)?

**Comment by Waistless** [comment]
@doitsujin Apologies for the slow response.

No noticeable difference with that option enabled, even in other circumstances for example two bears in a non modded stage on high textures. (excluding the laggy stages).

I did some more testing, depending on the settings used and on the laggy stages, can end up with this sort of CPU usage behavior: 
![cpuusagevulkan](https://user-images.githubusercontent.com/43065289/52803936-c51e3c00-30ce-11e9-8497-dfb682d1c0d5.png)
(note SMT threads disabled through affinity to make the graph clear, has no impact on performance).

Those dips on CPU#6 are a result of a slight change in camera angle depending on how you walk around the stage. Those levels are consistent, its either at 40% usage or fully bottlenecked, with no middle ground. During the lower cpu usage the FPS will sit at 60, at maxxed out it will sit at somewhere below 60, depending on settings. (Also noticed the same behavior on linux). GPU usage itself remains fairly constant.  This occurs regardless of VRAM usage sitting at around 2GB used out of 4GB, and other stages appear to use more or similar amounts without the same problem occurring.

I am able to almost fine tune this behavior with all low settings on arctic snowfall using the rendering scale. At 50 (so 50% of 1080p), there is no CPU bottleneck at any camera angle. At 55% this behavior shows up, and at 60% there are only small camera angles where the bottleneck goes away. At 65% the CPU remains bottlenecked and beyond this is where the huge dip in performance comes from. 

This also occurs if you leave rendering scale at 50%, all low settings with either Effects on Ultra, or Post Processing at Ultra. Ultra Textures or Ultra Shadows have little impact. These values are different for 
brimstone and fire, but the end result is the same.

Appreciate the effort btw, so happy that this project exists!

**Comment by doitsujin** [comment]
This is extremely weird, the Rendering Scale option should have absolutely no effect on CPU performance at all.

Can you monitor PCIe bus utilization in the Nvidia settings (on Linux)?

**Comment by Waistless** [comment]
I monitored this is in Linux(nv settings) and Windows (msi afterburner), same behavior

PCI Generation Gen3
Max PCIE Link Width x16
Max PCIE Link Speed 8.0 GT/S

In the menu the utilization will stay at 1%
When loading it behaves as expected, some spiking to load resources. On linux I saw a couple of 20% spikes, on windows msi afterburner it only shows going as high as maybe 5%.
In game: on Arctic Snowfall stage I cannot get bus utilization above 0%, no matter the settings if I put render scale to 50% for 60 fps, or 100% render scale on all low or all high settings for its slow capped out behavior.
![bususage](https://user-images.githubusercontent.com/43065289/52839452-e4a27c80-3141-11e9-947f-7e2a43d3bc79.PNG)
In other stages when I put settings to High and 100% render scale, it can still do 60fps and bus utilization stays at around 1%.
![bususage2](https://user-images.githubusercontent.com/43065289/52839463-e9ffc700-3141-11e9-84b0-081c2cfc0096.PNG)

So yea, it is a bit weird that it can maintain a higher bus usage in the menu than in the laggy stage. Unfortunately I see no options to use decimal values for the usage graph.

**Comment by Waistless** [comment]
@doitsujin BREAKTHROUGH! I suspected as much, there were certain objects on the stage causing problems.

Remember those potato stages I linked? Turns out its really easy to remove things from stages, and the potato mod of Arctic Snowfall doesn't actually remove a whole lot of things. So I only took all out of the files in the "Developer" subfolder (hexedit rename to neveloper) while leaving everything else in, paked up a new mod, and now the stage works like a breeze, 60fps at high settings. 

![20190215225430_1](https://user-images.githubusercontent.com/43065289/52858118-f9e4ce80-3174-11e9-846d-79ef87053c34.jpg)

I'll place all stage mods with these removed dev files here https://drive.google.com/open?id=1L5ugDHCIl_8vrAOq9cRtSOC73i8ig9rU

Regarding the issue itself, its possible these "developer" objects aren't meant to ever be loaded, hence why I can't see any visual change from removing them. For whatever reason in native DX11 these files might be ignored/not loaded, but they give DXVK a massive headache. 

I've zipped up these offending files if you want to look at them. If you're short on time I can re-add each dev file to the map until the problem occurs again, and let you know what specific file that is. 

https://drive.google.com/open?id=1YFdfmHdhwMPjxKufDjPpSbqvgodTdvQB

**Comment by Waistless** [comment]
I narrowed the major cause of the FPS drop and CPU usage in the Arctic Snowfall stage to a small uasset called "SnowA_FIXED" which itself links to a larger uasset "SnowMaster_LO". Hex editing out their texture asset links in a mod doesn't fix the lag, so I assume its related to one of the core assets themselves. 
Just hex editing the link to "SnowA_FIXED" and the stage goes from 35-40fps low settings to 60fps playable on medium settings. Taking out the rest of the dev files and the stage goes to 60fps high settings playable as stated earlier.

Unfortunately, Tekken 7 uses a modified version of Unreal Engine 4.13.2, so I was unable to view the assets in the respective tool (and hence why modders aren't directly using UE for their mods). This makes linking the files rather pointless.

Another more extreme example of the CPU usage spikes I found though, was on infinite azure. When the opponent hits the ground and enough water splash effects occur, game drops slightly below 60 and I get CPU usage that looks like this: 
![cpuwoessendofthrow](https://user-images.githubusercontent.com/43065289/52916412-e11e1980-332a-11e9-823d-40f563ccfcf4.png)

That happens on medium settings, on low settings the effects aren't enough to tip dxvk over the edge and cause high cpu usage. It's almost like it ends up running out of some specific resource and when that happens, has to fallback to the CPU pushing everything through.

**Comment by doitsujin** [comment]
No such thing as a "CPU fallback" for anything in 3d rendering.

Anyway, thanks for looking into this, not being an UE4 developer I'm just not really sure what to make of it, and why it would cause this obscene CPU utilization. This almost sounds like it's hitting some GPU<>CPU synchronization, which *does* cause 100% utilization on one thread for a while, but I haven't found any hints to that actually happening in the apitrace that TKG provided.

Has anyone tested this with an AMD GPU? Their Dx11 driver overhead is comparable to that of DXVK+RADV.

**Comment by juicefreak** [comment]
@Waistless 

Not all "developer assets" are invisible. I tried the mod where I overwrite all instances of "/Developers/" with junk near the beginning of /TekkenGame/Content/Maps/stg03_geom.umap first, and that seemed to remove all the carts from the trains moving in the background and left just the train engine there.

Disabling SnowA_FIXED only seems to not cause any visual differences at a quick glance, but I wonder if there's still something missing there now that just isn't easy to notice.

I've seen other games where assets have been organized into directories by the names of artists working on the game. That might be what's happened here too, instead of these being development leftovers.

Still, nice to know that I don't really have to use the mod which removes the background from Arctic Snowfall almost completely to play this game on a GTX770 without rebooting to Windows! I'll have to see if there's a single asset that can be disabled to fix Brimstone too, unless you happen to find it first... (though the already made "potato mod" for that stage isn't that bad, it just simplifies the background a bit instead of removing it completely)

**Comment by juicefreak** [comment]
I just updated the DXVK DLLs manually from 0.95 to 1.0 in my Proton x64 library directory. This improved the framerate on these stages on my GTX770 a lot!

In a 1600x900 window with High preset settings but AA disabled (the settings I usually play with), framerate in unmodified Arctic stage rose to about 50-55fps from the 30s, so it is almost playable without the mod now. Brimstone is now a solid 60fps without the mod, at least without bears on screen.

In fact, Brimstone now runs at 60fps in 1920x1080 resolution with the same settings, Arctic dips to about 44fps then, though. Seems Brimstone can even tolerate raising the settings a little bit further than that, like enabling AA...
