### ISSUE TITLE
Resident Evil 2 Remake - Visual Glitches in dark environments.

### ISSUE THREAD

**Issue by Sur3** [doitsujin/dxvk#895]
I've some visual glitches in Resident Evil 2 Remake in dark environments:
https://i.postimg.cc/m2vgCW7d/20190130-134400-354360684.png

### System information
- GPU: Radeon RX 570 Series (POLARIS10, DRM 3.19.0, 4.14.90-gentoo, LLVM 6.0.1) (0x67df)
- Wine version: wine-staging-4.0-139-g699eb8cdba8f
- DXVK version: 0.96

**Comment by doitsujin** [comment]
LLVM 6.0.1 is broken and not supported, please update your GPU driver.

**Comment by Sur3** [comment]
OK I'll try if updating to 7.0.1 fixes it..

**Comment by Sur3** [comment]
Ok updating llvm fixed it, there are still some minor lighting glitches but they seem to exist in windows as well, so they are probably intended by the game, or so.. ^^
