### ISSUE TITLE
Add driver name to hud for better readability

### ISSUE THREAD

**Issue by shmerl** [doitsujin/dxvk#897]
Vulkan allows getting driver name through [VkPhysicalDeviceDriverPropertiesKHR](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkPhysicalDeviceDriverPropertiesKHR.html).driverName.

For example, for radv it reports `radv` and for amdvlk `AMD open-source driver`.

**Comment by shmerl** [comment]
Also, opened [this](https://github.com/GPUOpen-Drivers/AMDVLK/issues/81), may be amdvlk developers can make it more distinct.

**Comment by doitsujin** [comment]
And why? Where would you even put this?

I'd argue that most people who have both the proprietary AMD driver and amdvlk installed know which one they are using. RADV can be recognized by its device name, and Nvidia and Intel only have one driver each.

Granted, I could potentially add some driverinfo HUD field, but I'd prefer to spend time on useful things rather than pointless feature requests that don't even work on all drivers.

**Comment by shmerl** [comment]
__Can be recognized__ doesn't mean it's very obvious right away. It just improves readability. I suppose like now it says:

```
Driver: <version>
```
It can say:
```
Driver: <name>
Driver ver: <version>
```
Or something of that sort.

**Comment by doitsujin** [comment]
And which part of "AMD **RADV** POLARIS10" does not make it clear that the driver being used is RADV?

**Comment by shmerl** [comment]
That's not a driver name though, but "GPU id". It's not really a given it should even have `RADV` in it, it's just coincidental. amdvlk puts more to the point string there like `Radeon RX Vega`.

**Comment by Joshua-Ashton** [comment]
lol it having radv is coincidental

ok dude
sure
mhmm
yes
uh huh

**Comment by shmerl** [comment]
It is coincidental in the device name. Why should it be there?

**Comment by Joshua-Ashton** [comment]
do you know what the word coincidence means?

**Comment by shmerl** [comment]
It means it just occurred there, not for some specific intent. The point is, it's not the field for getting the driver name from.

**Comment by Joshua-Ashton** [comment]
so you do not know what the word coincidence means. got it. 👍

**Comment by shmerl** [comment]
@Joshua-Ashton Can you please drop off-topic if you have nothing to add?

**Comment by doitsujin** [comment]
> That's not a driver name though, but "GPU id". It's not really a given it should even have RADV in it, it's just coincidental. amdvlk puts more to the point string there like Radeon RX Vega.

Yes, I **know** that. Doesn't change the fact that it is completely useless for vendors with more reasonable driver situations, and also doesn't change the fact that the device name on RADV happens to have RADV in it.

**Comment by shmerl** [comment]
Well, it's just that - happens to have it. So it's kind of distinguishable now, but not really a straight way to do it. Anyway, it's not really any critical feature, just enhancement to use more proper fields for identification. I didn't test how Intel or Nvidia populate `driverName`, so can't say if their values make sense.

**Comment by Joshua-Ashton** [comment]
I implemented this for you here:
https://github.com/Joshua-Ashton/dxvk/tree/driver-hud

All the drivers have stupid names that aren't what people call them. Not only that but it takes up a fair amount of space displaying fairly redundant information.

![image](https://user-images.githubusercontent.com/21316711/52023579-8a74ab00-24f5-11e9-98bc-f66c73f5ee1c.png)

**Comment by Joshua-Ashton** [comment]
Bigger image of it:

![image](https://user-images.githubusercontent.com/21316711/52023669-e2abad00-24f5-11e9-8907-2baca47d8ba6.png)

**Comment by shmerl** [comment]
Interesting. So that's how closed AMD driver doing it? I guess it's in line with their 'AMD open source driver' naming for amdvlk. I opened a proposal for them to put amdvlk in the open driver name. Not sure how they call their closed one.

**Comment by Joshua-Ashton** [comment]
I replied to your issue on their page about that.

It would be ill-advised for them to change their name as other games/apps may be relying on that string now to make driver-specific optimizations/workarounds.

**Comment by shmerl** [comment]
If they have such concerns, they'll keep it, or figure out a way to combine them (like add, rather than completely change the field value).

**Comment by Joshua-Ashton** [comment]
Any change could disrupt things. I doubt it will happen.

**Comment by shmerl** [comment]
Let's see what they say. amdvlk is barely used yet, so not a big problem probably.
