### ISSUE TITLE
ID3D11Device::OpenSharedResource implementation

### ISSUE THREAD

**Issue by decrn** [doitsujin/dxvk#899]
Any timeline on shared resources? :)

**Comment by doitsujin** [comment]
It is not possible to implement this in any useful way without support for external memory, and Wine does not support that (it would be a *huge* task as well).

What do you need it for anyway?

**Comment by decrn** [comment]
Ah, damn shame. Injection clients like FiveM for GTA V uses it, among others.

**Comment by droidmahn** [comment]
Not sure if an appropriate place to ask this question but seems more appropriate than opening a new thread. What's more likely we get shared resources or the windows battleye anti cheat playing nice in linux?

**Comment by decrn** [comment]
Considering BattleEye and similar AC also use ReadProcessMemory and WriteProcessMemory, neither will be supported. I believe it will be up to the AC developers themselves to add Linux Support, paving the way for game developers to support Linux out of the box.

After all, an anticheat that operates through a D3D wrapper can never be assumed to work as intended, anyway...

**Comment by romulasry** [comment]
https://www.phoronix.com/scan.php?page=news_item&px=Wine-Vulkan-Shared-Resources

**Comment by Kreyren** [comment]
FWIW for FiveM I have tracking for it in winetricks, but so far I wasn't able to make sufficient workaround.

https://github.com/Winetricks/winetricks/issues/1356

**Comment by Kreyren** [comment]
ping @KarenGhavam-lunarG

Assuming this being a vulkan related could you provide some info that would help with the interpretation in DXVK or possible workarounds to be implemented in winetricks?

**Comment by doitsujin** [comment]
@Kreyren please refrain from pinging people who aren't directly involved in this project for no good reason. **Last warning.**

**Comment by Kreyren** [comment]
> @Kreyren please refrain from pinging people who aren't directly involved in this project for no good reason. Last warning.

These are vulkan developers so I believe that they are directly related to DXVK where I'm hoping that they would be able to provide info (or reference someone who might be able to) which would help us implement shared resources in either wine as wine patch/hack or workaround in winetricks or help you with the implementation in DXVK assuming that you said

> It is not possible to implement this in any useful way without support for external memory, and Wine does not support that (it would be a huge task as well).

where I'm unable to find any relavant winebug to shared resources (https://bugs.winehq.org/buglist.cgi?quicksearch=shared%20resources) or external memory (https://bugs.winehq.org/buglist.cgi?quicksearch=external%20memory) 
and assuming that codeweawers announced working on this (https://www.phoronix.com/scan.php?page=news_item&px=Wine-Vulkán-Shared-Resources)  including the patchwork (https://www.winehq.org/pipermail/wine-devel/2019-October/153443.html)

Maybe your informations about this implementation are not up to date based on provided info? Or is there a reason where you don't want to implement this in DXVK even if it would be possible?

> Last warning

:(

**Comment by Kreyren** [comment]
@Joshua-Ashton thanks that's helpful, but some tracking for what needs to be done would be useful since if I wanted to contribute myself I have to go in basically blind without asking alike..

**Comment by Kreyren** [comment]
> Attaching texture metadata to the handle

could you be more specific on this?  Which handle? 

> How the hell do things synchronize??? 
>... 

flush meaning? Reference on the docs?

.. assuming that me extracting these informations from Direct3D devs is helpful

**Comment by doitsujin** [comment]
> These are vulkan developers so I believe that they are directly related to DXVK

No, they are not. Or is Linus Torvalds is directly related to DXVK as well now because it targets Linux?

Maybe just leave the development and project management to me and contributors.
