### ISSUE TITLE
Trying to build dxvk 0.96 from git (this one)

### ISSUE THREAD

**Issue by jcdutton** [doitsujin/dxvk#902]
When trying to build/compile dxvk 0.96 from git (this one)
I get compile errors:
../src/dxgi/dxgi_include.h:28:10: fatal error: dxgi1_4.h: No such file or directory

 Please can someone add to the troubleshooting section, what package I need to install to fix this problem?

I am using Ubuntu 18.04.1

**Comment by lieff** [comment]
You need mingw 6+, see https://github.com/doitsujin/dxvk/issues/766

**Comment by jcdutton** [comment]
Thank you. I did:
sudo add-apt-repository ppa:mati865/mingw-w64
upgraded mingw from that ppa.
It now compiles ok.

**Comment by montvid** [comment]
Got the same problem solved by adding this ppa.
