### ISSUE TITLE
GTA V doesn't start with nvidia-drm.modeset=1

### ISSUE THREAD

**Issue by kakserpom** [doitsujin/dxvk#903]
If I set nvidia-drm.modeset=0 then the game runs flawlessy, but at the same time I don't have vsync outside of the game. So I need to switch it on and off which is annoying.

If I set nvidia.drm.modeset=1 then I see "DirectX not found" error when I try to start GTA V. 

### Software information
GTA V (Steam), Ubuntu 18.10 (Gnome)

### System information
- GPU: GTX1070M
- Driver: 415.27
- Wine version: 4.0
- DXVK version: 0.94 (Proton 3.16-6)

**Comment by doitsujin** [comment]
Make sure that Vulkan works on your end. This is not a DXVK bug, but enabling `nvidia.drm.modeset=1` somehow broke your Vulkan setup.

**Comment by jp7677** [comment]
@kakserpom I'm using 'nvidia.drm.modeset=1' and it works just fine. Please make sure that you are not running Wayland but X when using this switch ;)

**Comment by kakserpom** [comment]
@jp7677 how to make sure of that?

**Comment by jp7677** [comment]
@kakserpom Please use something like https://unix.stackexchange.com/questions/202891/how-to-know-whether-wayland-or-x11-is-being-used to ensure what session you are running. If you are indeed using Wayland you can  just select "Gnome on Xorg" (or similar, don't remember exactly  what it is called) as session type when logging in.

**Comment by jp7677** [comment]
Mmh, alright. False bet from my side then. The game though works with nvidia drm enabled, just did a test a minute ago. Something else is wrong on your system. Does the nvidia control panel works on your system with nvidia drm enabled?

**Comment by kakserpom** [comment]
@jp7677 Yes, it works just fine. I tried different driver version, I tried KDE. No luck. I could give you access to the laptop via TeamViewer :)

**Comment by jp7677** [comment]
Do you have any other Vulkan application you could test? Both x64 and x86? 'vulkaninfo' might be a good start..

**Comment by kakserpom** [comment]
@jp7677 https://gist.github.com/kakserpom/adfe465fba42469f14e9ac5c52fe9ae0

**Comment by kakserpom** [comment]
https://bugs.launchpad.net/nvidia-drivers-ubuntu/+bug/1800465

**Comment by jp7677** [comment]
I'm running Fedora and a desktop machine, I'm the wrong one to answer. Only solution I could think of is indeed disabling nvidia drm.

**Comment by kakserpom** [comment]
@Leopard1907 what driver are you on?

**Comment by Leopard1907** [comment]
415.27
