### ISSUE TITLE
Black The Fall performance issues

### ISSUE THREAD

**Issue by mozo78** [doitsujin/dxvk#905]
Hello,
The game runs without any graphical problems but it have very low performance. It runs with 10-12 FPS.

### Software information
Black The Fall
I tried to stop nvapi hack to no avail.

### System information
- GPU: NVIDIA GTX 1080Ti
- Driver: 415.27
- Wine version: 4.1 Staging
- DXVK version: 0.96

### Apitrace file(s)
The game crashes when it reaches the main menu when I try to get an apitrace. However a ~60MB file was created:
https://my.pcloud.com/publink/show?code=XZ2kXl7ZIElI2uHAzCzmkuRDyb5LKXvSJFh7

### Log files
- d3d11.log:
https://pastebin.com/VrcYziBp
- dxgi.log: 
https://pastebin.com/UxxxkKhn

**Comment by doitsujin** [comment]
Do you have access to a Windows system to record an apitrace? The trace you got out of the game is completely useless since it ends before the game actually starts.

**Comment by mozo78** [comment]
Unfortunately no :( I don't use Windows 15 years already.

**Comment by doitsujin** [comment]
Are you using Proton? Does esync work? What's your CPU? Can you check if you are CPU bound or GPU bound?

**Comment by mozo78** [comment]
1. I tried it with latest Proton but the FPS are even lower - 3-5 or so.
2. Yes I tried with esync.
3. My CPU is Intel 3770
4. I don't know how bur I'll try to check it out. What export DXVK options do you like?
5. No it's the same. I just forgot to mention.

**Comment by doitsujin** [comment]
> 4\. What export DXVK options do you like?

DXVK cannot tell you whether you are CPU bound, you have to open the Nvidia settings, one of the tabs shows GPU utilization (along with memory utilization etc.)

> 5\. No it's the same. I just forgot to mention.

Then this is very likely not an issue with DXVK *or* wined3d, but something else.

**Comment by mozo78** [comment]
I started the game in virtual desktop and check the system load - it seems the GPU and CPU are barely used:
![22](https://user-images.githubusercontent.com/38666396/52425529-dc748c80-2b04-11e9-8743-5a06a7c8c797.png)

I just wonder why file a Proton bug but not Wine?

**Comment by doitsujin** [comment]
Hm, interesting. Can you post the full wine log?

> I just wonder why file a Proton bug but not Wine?

You're more likely to get help there than on the wine bug tracker, since Proton focusses on game compatibility.

**Comment by mozo78** [comment]
I just read the log and it seems missing vcrun2015. I installed it and now the game runs with ~110 FPS. Thank tou very much and I'm sorry for the inconvenience caused. 
Best regards!
