### ISSUE TITLE
Make DXVK_STATE_CACHE_PATH directory if it does not exist

### ISSUE THREAD

**Issue by X0rg** [doitsujin/dxvk#907]
When I set `DXVK_STATE_CACHE_PATH` environment variable, the `DXVK_STATE_CACHE_PATH` directory is not created, so DXVK state cache is disabled.
After creating `DXVK_STATE_CACHE_PATH` directory manually, DXVK state cache works as expected.

DXVK should check if `DXVK_STATE_CACHE_PATH` directory exists and make it if it does not exist.

### System information
- DXVK version: 0.96

**Comment by doitsujin** [comment]
Is there a valid use case for setting the env var to a directory which doesn't exist?

I don't really like messing around with file system functions for no good reason.

**Comment by X0rg** [comment]
> Is there a valid use case for setting the env var to a directory which doesn't exist?

Yes, I want to put DXVK state cache in `~/.cache` directory (like `mesa_shader_cache` does). I'm using that: 
```
export DXVK_STATE_CACHE_PATH="$HOME/.cache/dxvk"
```
Generally, others software put things in cache directory without that I need to create a subdirectory manually.


> I don't really like messing around with file system functions for no good reason, especially since the C++ standard library does not provide any such functions [...]. In other words, the current behaviour is intended.

I understand.
However, C++**17** provides such functions, like [`std::filesystem::exists`](https://en.cppreference.com/w/cpp/filesystem/exists) and [`std::filesystem::create_directory`](https://en.cppreference.com/w/cpp/filesystem/create_directory).
What do you thing about using C++17?

**Comment by doitsujin** [comment]
> What do you thing about using C++17?

I'm already using C++17 language features, but using the standard library features is currently not an option since DXVK has to support a bunch of old compilers, unfortunately.

**Comment by Joshua-Ashton** [comment]
If you were to use Win32 funcs:

``CreateDirectory[A/W]`` is usually good enough, but it functions like ``mkdir`` and not ``mkdir -p``

You'd also have to try and make every directory (or check before making) along the way to that dir in order for it to work properly.

``Shlwapi`` has some nice helper functions for this (and its what I see a few games use), but its another dependency and a bit of a hacky solution. Using std string find and going through may be a better solution.

**Comment by doitsujin** [comment]
The thing that bothers me about `CreateDirectoryW` is that we need to convert char sets again, which wouldn't be necessary if `<filesystem>` worked (honestly I can't wait for it to become usable), and that can potentially go wrong if not done correctly.

But yeah, that will have to do. `mkdir -p` behaviour shouldn't be necessary and might be too invasive anyway.

**Comment by X0rg** [comment]
Thank you, it works as expected since v1.0. :ok_hand:
