### ISSUE TITLE
Wiki: add Elder Scrolls Online to the list of playable games

### ISSUE THREAD

**Issue by ssorgatem** [doitsujin/dxvk#91]
After extensive tsting, I can say that ESO works better on current DXVK than on Wined3d (staging or otherwise), with the only noticeable downside being textures taking slightly longer to load sometimes.

This is important because ESO is currently broken in wined3d (texture glitches).

So I propose adding it to the supported game list int he wiki, something like this:

The table below lists games and applications that were tested with DXVK. Note that the project is still in an early stage of development, and games not listed below should not be expected to work.

| Game                       | Status   | Since version | Notes                                        |
|----------------------------|----------|---------------|----------------------------------------------|
| Cities: Skylines           | Testing  |               | Occationally crashes when zoomed in          |
| Elder Scrolls Online       | Playable | git           | Requires mesa-git for Vega GPUs              |
| Homefront                  | Testing  |               |                                              |
| Megadimension Neptunia VII | Testing  |               | Depth of Field not working, RADV issues      |
| Nier: Automata             | Playable | v0.20         |                                              |
| Offworld Trading Company   | Testing  |               |                                              |
| Ori and the Blind Forest   | Testing  |               |                                              |
| Rise of the Tomb Raider    | Testing  |               | Renders incorrectly, poor performance        |
| Thief (2014)               | Testing  |               | Some options not working, poor performance   |
| Tomb Raider (2013)         | Testing  |               | Requires Mesa-git, not all options supported |
| Unigine Heaven Benchmark   | Working  | v0.21         | Tessellation not supported                   |
| Unigine Valley Benchmark   | Working  | v0.21         |                                              |

**Comment by doitsujin** [comment]
Done, and thanks for testing+reporting this.
