### ISSUE TITLE
[Question] Variable rate shading support 

### ISSUE THREAD

**Issue by rcaridade145** [doitsujin/dxvk#913]
Hello this is by no means a request but just a question.
Is it possible to integrate technologies like variable rate shading (supported on Nvidia Turing) or Coarse Pixel Shading that will come with Gen 11 from Intel?
https://software.intel.com/en-us/articles/coarse-pixel-shading 
Would this bring issues with dx11 games or is more work than it is worth it?

**Comment by doitsujin** [comment]
This is something that games themselves have to support, since they have to generate a buffer which tells the GPU which sections of the image to process with a higher or lower shading rate. While interesting, it is not viable to do this on an API level.
