### ISSUE TITLE
Sleeping Dogs Definitive Edition crashing

### ISSUE THREAD

**Issue by AccountOneOff** [doitsujin/dxvk#917]
Crashes after about an hour of gameplay.

### Software information
Sleeping Dogs Definitive Edition

### System information
- GPU: GTX 960
- Driver: 415.27
- Wine version: Wine Staging 4.1
- DXVK version: 0.96

### Apitrace file(s)
- Don't know if you still have my trace from a while back. Unfortunately I removed it from gdrive. I can make a new one if need be.

### Log files
- [sdhdship_d3d11.log](https://github.com/doitsujin/dxvk/files/2862742/sdhdship_d3d11.log)
- [sdhdship_dxgi.log](https://github.com/doitsujin/dxvk/files/2862743/sdhdship_dxgi.log)
- [sdhdship_backtrace.txt](https://github.com/doitsujin/dxvk/files/2862755/sleepingdogsde-crash.txt)

**Comment by doitsujin** [comment]
Does it work without DXVK?

**Comment by minilandl** [comment]
The game works fine with wined3d I was able to play through at least 3 missions without any crashes which was not possible while using dxvk 0.96 or previous versions of dxvk. What is the best way to capture an apitrace?

**Comment by doitsujin** [comment]
See [this](https://github.com/doitsujin/dxvk/wiki/Common-issues#apitrace) section on the wiki.

**Comment by minilandl** [comment]
I have captured an apitrace however the file is around 20gb. I was able to get the game running by using the lutris provided wine 4.1 with esync enabled. By disabling dxvk and adding the old environment variable DXVK_FAKE_DX10_SUPPORT=1. The game ran fine with the wined3d vulkan dx10 renderer. Without this environment variable enabled the game fails to launch. The game runs fine and I was able to play for about an hour. While the game crashed after 40 mins under dxvk 0.96 as well as  previous versions of dxvk.

**Comment by mozo78** [comment]
Use 7z on ultra settings, the file will be reduced dramatically. Then upload it to pcloud for example. There is 10GB free space for everybody :)

**Comment by minilandl** [comment]
Thanks I managed to compress the trace file. Here is the download link https://my.pcloud.com/publink/show?code=XZa6zd7ZcegB3YkRaTkhlzLW8GkVJJlfK4jy

**Comment by Tk-Glitch** [comment]
@minilandl 
DXVK_FAKE_DX10_SUPPORT=1 env var only ever affected DXVK (zero effect on wine or wined3d), but that function has been removed in august of last year afaik https://github.com/doitsujin/dxvk/commit/7fa6dddc9ee30a58cc073e44fe9d11ea49d3a3ed. If you're using Lutris, you may have an empty env var set in your runner that interferes with the game launch (it wouldn't be the first time).
Also, wined3d doesn't make use of Vulkan.

**Comment by minilandl** [comment]
Maybe for some reason enabling DXVK_FAKE_DX10_SUPPORT=1 in lutris  allows the game to run fine in wined3d. Maybe its just the fact that its using wined3d instead of dxvk. I have recorded a video showcasing how I fixed this issue. So I'll post the link after I have uploaded it to YouTube.

**Comment by Tk-Glitch** [comment]
I have installed the game in my steam runner in lutris (I didn't use lutris installer for the game). The game ran just fine with no override and no env var with wined3d (even without virtual desktop). Then I have installed DXVK, and got a white screen unless I used a virtual desktop. I have then played for an hour and a half with no crash, all settings maxed. I sadly couldn't reproduce your issue.
Other notable differences : I was using wine-staging 4.2, DXVK master and 415.22.05 drivers.

**Comment by minilandl** [comment]
Maybe it's something to do with the lutris probided dxvk or the wine 4.1 protonified build lutris provides which is causing issues. If I try playing with dxvk. The game crashes which also happens with proton https://www.protondb.com/app/307690 . It could do with my GPU which is a 750ti which us only 2gb. I read somewhere that dxvk runs better with GPUs with more vram.

**Comment by doitsujin** [comment]
Is this a 32-bit game? If so, please try enabling the large address aware flag.

I've replayed the apitrace, and apitrace does crash while replaying, but only once it actually reaches the end of the file. Not sure if that's a dxvk issue at this point or just an apitrace one. I'm currently replaying it with wined3d to see if it happens there as well (damn that thing is *long*).

**Comment by Tk-Glitch** [comment]
@doitsujin The definitive edition is 64-bit only, so that shouldn't be an issue. The game crashed on exit for me, that may possibly explain the apitrace crash.

@minilandl The wine build I was using is very similar to the 4.1 protonified available in lutris. For DXVK, lutris downloads directly from github releases so that shouldn't be an issue. I was using a GTX 980ti with 6GB VRAM but didn't check VRAM usage. Even though maxwell v1 apparently has driver issues, OP is using a GTX 960 so that doesn't seem related.

**Comment by pchome** [comment]
https://github.com/doitsujin/dxvk/issues/407#issuecomment-394089907
This time it randomly crashing with the exception (similar backtrace every single time):
```
wine: Unhandled page fault on read access to 0x00000068 at address 0x7fb4ff594805 (thread 0033), starting debugger...
Unhandled exception: page fault on read access to 0x00000068 in 64-bit code (0x00007fb4ff594805).
Register dump:
 rip:00007fb4ff594805 rsp:00000000022ef920 rbp:0000000000000000 eflags:00010202 (  R- --  I   - - - )
 rax:0000000000000001 rbx:00007fb4ec0d6660 rcx:0000000000000000 rdx:0000000000000000
 rsi:0000000000000000 rdi:00007fb5006bb540  r8:00007fb500075a60  r9:0000000002f1e801 r10:0000000000000000
 r11:0000000000000001 r12:00007fb4ec0d6660 r13:0000000000000000 r14:00007fb50111c550 r15:00007fb5006bb540
Stack dump:
0x00000000022ef920:  000000007d255110 00000000006bc100
0x00000000022ef930:  0000000100000000 00007fb5006bc090
0x00000000022ef940:  0000000000000000 00007fb4ff5872cb
0x00000000022ef950:  000000011e3ab200 00000000022ef9d0
0x00000000022ef960:  ffffffff00000000 00000100ff505b50
0x00000000022ef970:  00007fb400000001 c91b533e14303b00
0x00000000022ef980:  0000020000000200 00007fb4ec0c3250
0x00000000022ef990:  0000000000010000 00007fb4ec0d6660
0x00000000022ef9a0:  0000000000000000 00007fb4ec0d6660
0x00000000022ef9b0:  00007fb5006c3970 00007fb50111c550
0x00000000022ef9c0:  00007fb50111c578 00007fb50b8f1bce
0x00000000022ef9d0:  00007fb5006c3930 00007fb5006c3930
Backtrace:
=>0 0x00007fb4ff594805 in libnvidia-glcore.so.415.22.05 (+0x11cf805) (0x0000000000000000)
0x00007fb4ff594805: cmpl        0x0000000000000068(%r13),%eax
```
**Driver**: 415.22.05, 418.31.03
**Proton**: 3.16-7, 3.16-7(custom build + winelib dxvk git)
**Graphic settings**: default (medium)
**GPU**: 750 Ti 2Gb
**Max GPU Memory usage**: 1200 - 1400
**CPU/GPU load**: < 80%
**FPS**: 50 - 70 (~2x higher than was in Steam(wine) version)

**Comment by minilandl** [comment]
@Tk-Glitch I tested on wine 4.2 and the game works fine without crashes

**Comment by minilandl** [comment]
@Tk-Glitch as I suspected this game works fine through wined3d dxvk still seems to crash for me.

**Comment by minilandl** [comment]
here is a video I recorded to prove it works :)https://youtu.be/Lg2iPEOXAnQ

**Comment by barni2000** [comment]
I have played the game with multiple times, about years ago the game is crashing very often, but now days the game is only crashing when I open the steam overlay.

PS.: I think this ticket is outdated.

**Comment by Blisto91** [comment]
@AccountOneOff Sorry for the necro. Is it correct that this has been solved?

**Comment by ZereoX** [comment]
@Blisto91 Just wanted to add for visibility that I just completed the game on Proton 7.0-4 (w/ DXVK master-ish). Played 27 hours, 80% completion or so and only encountered a single crash. Probably a good closure candidate.

The only remaining issues appear to either be with Wine or Steam as neither can be reproduced on Windows w/ DXVK:

1. Title freezes when opening the Steam Overlay.
2. Title fails to launch in Fullscreen mode (Proton-GE has a workaround or you can just use gamescope `gamescope -w 3440 -h 1440 -W 3440 -H 1440 -f -e %command%`).

**Comment by K0bin** [comment]
@ZereoX Thank you. The issue is ancient and you've clearly tested this quite a lot. So I think it's save to say this is fixed.
