### ISSUE TITLE
what an input layouts are?

### ISSUE THREAD

**Issue by marcel-klomsbeck** [doitsujin/dxvk#918]
good morning doitsujin,

i am write to ask whate are an input layout? is it like vertex declaration in other api??h

also what are an hull and doman shader, they used for what type of shade?

thank you for your time!

**Comment by doitsujin** [comment]
Input layouts are the vertex format declaration, yes.
Hull/Domain shaders are the direct equivalents of Tessellation Control and Tessellation Evaluation shaders in GL/Vulkan.

**Comment by marcel-klomsbeck** [comment]
thanking you sir

should help with deployment of our simulation
