### ISSUE TITLE
Just Cause 3: almost instant crash 

### ISSUE THREAD

**Issue by pchome** [doitsujin/dxvk#92]
### Software information
Just Cause 3
**DX11 mode**: Runs with wine-staging-2.21, but ate all my RAM and GRAM and have some texture glitches.
**DXVK mode**: crash 
- DXVK build: _native Linux x86_64_

### System information
- GPU: _GeForce GTX 750 Ti_
- Driver: _387.34_
- Wine version: _wine-staging 2.21_
- DXVK version: _current master_ https://github.com/doitsujin/dxvk/commit/45a03b11bef70d1e7d99f9ea5ead99d18b6ceb20

### Apitrace file(s)
- _N/A_

### Log files
- d3d11.log: [dxvk_d3d11_-compiling.log](https://github.com/doitsujin/dxvk/files/1738199/dxvk_d3d11_-compiling.log)
- dxgi.log: [dxvk_dxgi.log](https://github.com/doitsujin/dxvk/files/1738200/dxvk_dxgi.log)

**Comment by doitsujin** [comment]
See #93.

**Comment by pchome** [comment]
Not only that.
Looks like the game loads `all shaders at onse`. Despite almost instant crash it produced 1455 shaders. And when I tried to optimize them  - `spirv-opt` itself has locked on one for five min.:
```sh
spirv-opt --legalize-hlsl CS_1358ba5d71fac34d06b16b37585f29d244c0e680.spv -o ../dxvk_shader_read/CS_1358ba5d71fac34d06b16b37585f29d244c0e680.spv
```
Than I run validator on all and It reported errors:
```sh
$ ./z_spirv-val-shaders.sh
CHECK_DUMP...
error: 10533: MemoryBarrier: Vulkan specification requires Memory Semantics to have one of the following bits set: Acquire, Release, AcquireRelease or SequentiallyConsistent
Error: PS_2c14013989db3668eecb2fd8abab3afeece2b26b.spv
CHECK_FIXED...
error: 7098: MemoryBarrier: Vulkan specification requires Memory Semantics to have one of the following bits set: Acquire, Release, AcquireRelease or SequentiallyConsistent
Error: PS_2c14013989db3668eecb2fd8abab3afeece2b26b.spv
DONE
```
Maybe you'll find something interesting inside:
[CS_1358ba5d71fac34d06b16b37585f29d244c0e680.dxbc.gz](https://github.com/doitsujin/dxvk/files/1738300/CS_1358ba5d71fac34d06b16b37585f29d244c0e680.dxbc.gz)
[CS_1358ba5d71fac34d06b16b37585f29d244c0e680.spv.gz](https://github.com/doitsujin/dxvk/files/1738301/CS_1358ba5d71fac34d06b16b37585f29d244c0e680.spv.gz)
[PS_2c14013989db3668eecb2fd8abab3afeece2b26b.dxbc.gz](https://github.com/doitsujin/dxvk/files/1738302/PS_2c14013989db3668eecb2fd8abab3afeece2b26b.dxbc.gz)
[PS_2c14013989db3668eecb2fd8abab3afeece2b26b.spv.gz](https://github.com/doitsujin/dxvk/files/1738304/PS_2c14013989db3668eecb2fd8abab3afeece2b26b.spv.gz)

**Comment by doitsujin** [comment]
The shader validation issue is known and has been reported several times already (I think in the Nvidia thread).

As for spirv-opt taking forever - it's still a dirty hack that is not officially supported. I'll check the compute shader though.
