### ISSUE TITLE
Anthem Game Slow FPS in menu and City

### ISSUE THREAD

**Issue by mixalis1987** [doitsujin/dxvk#922]
Game works well but with one problem not sure what the cause could be and thought I would ask here too. In the game the Menu has very low FPS and the City, you can still move about if you have the patience and talk to people. 
The missions, freeplay, Video Cutscenes pretty much all else is normal speed, this is what bothers me why the menu and city but once your in the world map works great.
If I add `dxgi.customVendorId = 10de` to dxvk.conf the game wont start because it will tell me my drivers are out of date and I need to update, removing dxvk.conf lets me play again.

Maybe you people with move skill can come up with some ideas. Only other thing I can think of is to update to beta GPU drivers. but if it was the drivers wouldn't the problem also affect the world map? So I'm not sure if that really is the problem either.

You can have a look here https://www.youtube.com/watch?v=P4bL7yV7tEQ skip to 6 minutes to see the full speed of the game.

### Software information
Anthem, Settings ( Hight, Medium, Low )

### System information
- GPU: Nvidia GTX 1080ti
- Driver: 415.27
- Wine version: 4.0
- DXVK version: 0.96

### Log files
- d3d11.log: [Anthem_d3d11.log](https://github.com/doitsujin/dxvk/files/2873405/Anthem_d3d11.log)
- dxgi.log: [Anthem_dxgi.log](https://github.com/doitsujin/dxvk/files/2873406/Anthem_dxgi.log)

**Comment by doitsujin** [comment]
I assume your wine build does not have esync? In that case, low performance is to be expected in **all** modern games.

**Comment by mixalis1987** [comment]
ESYNC is enabled, I tried to enable DXVK_HUD but for some reason it wouldn't show, maybe because Origins starts first and then the game?

**Comment by doitsujin** [comment]
> ESYNC is enabled

Regular wine builds don't support esync. Are you using a custom build then?

> DXVK_HUD but for some reason it wouldn't show

This means that the environment variable doesn't get propagated properly.

> And why just the Menu and City?

Don't know, someone would have to do some profiling. Are you CPU or GPU bound?

**Comment by mixalis1987** [comment]
> Don't know, someone would have to do some profiling. Are you CPU or GPU bound?
Had a look with htop when this happens and CPU is in normal range, no core is being used 100% just like any other game I play in WINE with DXVK. I'm pretty sure the GPU is normal too. What would be the best way to check that one?

> Regular wine builds don't support esync. Are you using a custom build then?
No it's not custom, I will keep trying to start the game with staging see what happens.

**Comment by doitsujin** [comment]
staging also doesn't support esync, unless you explicitly add the patch set.

> I'm pretty sure the GPU is normal too. What would be the best way to check that one?

nvidia-settings has a tab that shows GPU utilization. It should show 100% when you are GPU-bound.

**Comment by mixalis1987** [comment]
Does wine + tkg 4.0 have ESYNC? that's what I was using. Can't test out the GPU now because EA blocked me for a time because they think I was changing OS too often. Too many different wine attempts.

**Comment by doitsujin** [comment]
wine-tkg should have esync, yes.

**Comment by mixalis1987** [comment]
Thought so, so I was using ESYNC.

**Comment by ZeroFault** [comment]
Can you try just adding `d3d11.zeroInitWorkgroupMemory = True` in a dxvk.conf file? It seems to work for me to fix the performance on the main menu.

**Comment by mixalis1987** [comment]
@ZeroFault So you had lag at first? Like the video?

**Comment by mixalis1987** [comment]
I confirm adding `d3d11.zeroInitWorkgroupMemory = True` to dxvk.conf will fix the lag issues in the menu and the city. Game works great for me even all at max settings. I also updated to wine 4.2 staging, but I don't think that had anything to do with it. 

Now if only Origins worked better with wine, the game might start easier. Most of the the time it starts on this wine version but you may encounter a few times when the game may not start or might start to a black screen and freeze your OS. If the game doesn't start usually kill all wine processes and try again. 
Just thought I would mention that last bit even though WINE has nothing to do with dxvk stuff.

**Comment by SveSop** [comment]
@mixalis1987 It makes it somewhat confusing that you say "i also updated to wine 4.2 staging", if you are not specifying it is the lutris TKG build (With ESYNC support).
Regular "wine-staging-4.2" from winehq does NOT support ESYNC.

You could always just build your own from lutris git: [https://github.com/lutris/wine/tree/tkg](https://github.com/lutris/wine/tree/tkg)

Not everyone uses the Lutris launcher thingy, and get a warning if ESYNC is not supported, and afaik its not overly simple to actually CHECK if esync is enabled other than possibly do a wine debug log with +esync or something).

**Comment by mixalis1987** [comment]
Can't do a debug now as I'm on windows over the weekend. The wine version I got was from the arch AUR not its official repo. So maybe that's different? Other versions from the official repo I used in the past, Lutris told me that specific version I was using didn't support it when I tried to enable it. That's why I think i'm using it right now.
