### ISSUE TITLE
Far Cry New Dawn

### ISSUE THREAD

**Issue by SR-dude** [doitsujin/dxvk#923]
Has anyone tried it?

**Comment by SR-dude** [comment]
I have learned that the game has both Denuvo & VMProtect.

**Comment by Joshua-Ashton** [comment]
I haven't tried it, no.

You or I not trying this game is not a DXVK issue either though.

**Comment by doitsujin** [comment]
This really doesn't belong here, please use an appropriate forum / subreddit / whatever for this type of question.
