### ISSUE TITLE
Skyrim Special Edition Hangs

### ISSUE THREAD

**Issue by asdfjkluiop** [doitsujin/dxvk#927]
Running skyrim special edition through steam play hangs on the main menu. I'm not sure if the logs I've attached are helpful, if not let me know. I was expecting this to be an LLVM 7.0.1 issue so I manually built RADV against LLVM 8 but the issue still persists.

### Software information
Skyrim Special Edition, Ultra with TAA

### System information
- GPU: AMD Radeon R9 Fury
- Driver: RADV 19.0.0~rc4(LLVM 8.0)
- Wine version: Proton Beta 3.16-7

### Log files
- d3d11.log: [SkyrimSE_d3d11.log](https://github.com/doitsujin/dxvk/files/2882210/SkyrimSE_d3d11.log)

- dxgi.log: [SkyrimSE_dxgi.log](https://github.com/doitsujin/dxvk/files/2882211/SkyrimSE_dxgi.log)

**Comment by doitsujin** [comment]
Can't reproduce, works fine with latest mesa-git and llvm-git. Please file a mesa bug.

**Comment by asdfjkluiop** [comment]
Yeah, I guess I will have to because I Just tried it with LLVM-9svn and it still hangs

**Comment by Oschowa** [comment]
Are you sure this hang is gpu driver related? Looking at the proton bug [report](https://github.com/ValveSoftware/Proton/issues/4), there are people (even nvidia users) reporting freezes on the main menu, which are apparently solved by disableing esync or with a self-compiled faudio build against ffmpeg.

**Comment by asdfjkluiop** [comment]
@Oschowa people I've talked to say it's working for them so I assumed it was a driver issue because I've been having issues with native vulkan games although recent updates have fixed them but not skyrim. I also knew certain versions of LLVM had this issue so I assumed it was. Disabling esync is something I try frequently as it's fixed other games for me but not this one. I have not tried the faudio fix, maybe I should try that next because I REALLY want this game working.

**Comment by doitsujin** [comment]
Wait, are you talking about a GPU hang which causes your entire system to freeze, or just the game hanging?

**Comment by asdfjkluiop** [comment]
@doitsujin you know, I feel really dumb now but until you said that it didn't occur to me that "GPU hang" meant a full system hang. For some reason I read that as "game hang."

**Comment by asdfjkluiop** [comment]
Alright, so it's an XWayland issue, or an XWayland issue with RADV because I had a friend test it and it hangs for him in XWayland but not under X.Org. I got the idea from looking at this issue https://github.com/ValveSoftware/Proton/issues/4 someone else mentioned it as an issue and it turns out it's correct.

**Comment by t14462** [comment]
It is XWayland bug causing of VSync

This was fixed in X.Org release 1.20.4, so just update your XWayland
