### ISSUE TITLE
Deferred Context support

### ISSUE THREAD

**Issue by doitsujin** [doitsujin/dxvk#93]
Deferred contexts are currently **not** fully supported, which usually results in an application crash.

Please **do not** open a new bug report if you see the following message in your log files:
```
err:   D3D11DeferredContext::Map: Not implemented
```

**Comment by roothorick** [comment]
Shouldn't this be split into two issues? It'd be nice to have more specific issues to link to in compatibility lists and whatnot.

**Comment by oscarbg** [comment]
Ok not opening an issue, but just for future reference to test when deferred contexts are in Sonic Forces requires it:
[Sonic Forces_d3d11.log](https://github.com/doitsujin/dxvk/files/1755441/Sonic.Forces_d3d11.log)
[Sonic Forces_dxgi.log](https://github.com/doitsujin/dxvk/files/1755442/Sonic.Forces_dxgi.log)

**Comment by doitsujin** [comment]
Updated top comment as tessellation is now (partially) supported.

**Comment by doitsujin** [comment]
Updated top comment now that deferred contexts are partially supported as of 7069df6b1ee1abc21f425d81c0dff7fb411712f1.

Resource mapping on deferred contexts is still missing, but some CryEngine games may be able to run.

**Comment by doitsujin** [comment]
Closing since the most relevant functions are implemented as of f1c3b59e87746f56f1956bfa54b9403d0e5317b1.
