### ISSUE TITLE
Nvidia 418.43 crash on startup of some games with "Unhandled exception: page fault on read access to 0x00000000 in 64-bit code"

### ISSUE THREAD

**Issue by Xaenalt** [doitsujin/dxvk#930]
After upgrading to Nvidia 418.43, Monster Hunter: World now crashes on startup with:

```
Unhandled exception: page fault on read access to 0x00000000 in 64-bit code (0x00007fd76f188e24).
Register dump:
 rip:00007fd76f188e24 rsp:0000000015eac9c8 rbp:0000000015eaca18 eflags:00010206 (  R- --  I   - -P- )
 rax:0000000000000000 rbx:00007fd7401121e0 rcx:00007fd740000020 rdx:00007fd74071a110
 rsi:00007fd740384e10 rdi:00007fd7404fb1e8  r8:0000000000000031  r9:0000000000000001 r10:00007fd7400008d0
 r11:0000000000000001 r12:00007fd7404fad80 r13:0000000015eac9e0 r14:00007fd7401121e0 r15:00007fd74041f100
Stack dump:
0x0000000015eac9c8:  00007fd76f114221 000000000000007f
0x0000000015eac9d8:  00000000000000b0 0000000000000036
0x0000000015eac9e8:  00007fd74071a100 00007fd74071a110
0x0000000015eac9f8:  00007fd74071a110 0000000015eaca18
0x0000000015eaca08:  0000000015eaca18 0000000015eaca28
0x0000000015eaca18:  00007fd76f1120eb ffffffffffffff90
0x0000000015eaca28:  0000000000000801 0000083100000020
0x0000000015eaca38:  0000000015eace98 00007fd7404b0b00
0x0000000015eaca48:  0000000000000000 0000000000000000
0x0000000015eaca58:  00007fd76f209fcb 00007fd7404b13b0
0x0000000015eaca68:  00007fd7407456b0 0000000000020050
0x0000000015eaca78:  0000000000002004 ffffffffffffff90
Backtrace:
=>0 0x00007fd76f188e24 in libnvidia-glvkspirv.so.418.43 (+0x563e24) (0x0000000015eaca18)
  1 0x00007fd76f114221 in libnvidia-glvkspirv.so.418.43 (+0x4ef220) (0x0000000015eaca18)
0x00007fd76f188e24: movq        (%rax),%rax
```

Not all games seem to be affected, Heroes of the Storm loads just fine

### Software information
Monster Hunter: World, default settings I had pre-crash

### System information
```
System:    Host: graviton.localdomain Kernel: 4.20.8-100.fc28.x86_64 x86_64 bits: 64 Desktop: KDE Plasma 5.13.5 
           Distro: Fedora release 28 (Twenty Eight) 
Machine:   Type: Desktop System: Gigabyte product: Z370 AORUS Gaming 7 v: N/A serial: <root required> 
           Mobo: Gigabyte model: Z370 AORUS Gaming 7 v: x.x serial: <root required> UEFI: American Megatrends v: F3 
           date: 09/22/2017 
CPU:       6-Core: Intel Core i7-8700K type: MT MCP speed: 800 MHz min/max: 800/5000 MHz 
Graphics:  Device-1: NVIDIA GP102 [GeForce GTX 1080 Ti] driver: nvidia v: 418.43 
           Display: x11 server: Fedora Project X.org 1.19.6 driver: nvidia 
           resolution: 3840x2160~60Hz, 3840x2160~60Hz, 3840x2160~60Hz, 3840x2160~60Hz 
           OpenGL: renderer: GeForce GTX 1080 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 418.43 
Network:   Device-1: Intel Ethernet I219-V driver: e1000e 
           Device-2: Qualcomm Atheros Killer E2500 Gigabit Ethernet driver: alx 
           Device-3: Intel Wireless 8260 driver: iwlwifi 
Drives:    Local Storage: total: 2.31 TiB used: 579.93 GiB (24.5%) 
Info:      Processes: 514 Uptime: 48m Memory: 31.35 GiB used: 11.93 GiB (38.1%) Shell: zsh inxi: 3.0.29 
```

[MHW-Crash-Proton3.16-4.log.gz](https://github.com/doitsujin/dxvk/files/2897173/MHW-Crash-Proton3.16-4.log.gz)
[MHW_CRASH_VK_LAYER_LUNARG_core_validation.log.gz](https://github.com/doitsujin/dxvk/files/2897174/MHW_CRASH_VK_LAYER_LUNARG_core_validation.log.gz)
[MHW_CRASH_VK_LAYER_LUNARG_api_dump.log.gz](https://github.com/doitsujin/dxvk/files/2897175/MHW_CRASH_VK_LAYER_LUNARG_api_dump.log.gz)
[MHW-Crash-Proton3.16-7beta.log.gz](https://github.com/doitsujin/dxvk/files/2897176/MHW-Crash-Proton3.16-7beta.log.gz)

**Comment by Xaenalt** [comment]
Thanks for taking a look at it! :D

**Comment by doitsujin** [comment]
Looks like there's an invalid shader somewhere. Please run the game with `DXVK_SHADER_DUMP_PATH=/some/path` set (note that you **must** create `/some/path` before), and upload that directory somewhere.

**Comment by Xaenalt** [comment]
One moment :D

**Comment by Xaenalt** [comment]
Bigger than the 10M limit, let me know if you can access this: https://drive.google.com/file/d/1SoiuE8Mp5OulTZDwQAOxBdoi6LlSE1fj/view?usp=sharing

**Comment by doitsujin** [comment]
Yeah that works, thanks. Will take a look.

**Comment by Xaenalt** [comment]
Awesome! Thanks so much! :D

**Comment by Xaenalt** [comment]
Was able to get back into the game by setting `DXVK_STATE_CACHE=0`, weird

**Comment by Xaenalt** [comment]
Unsetting it has the crash reoccur though

**Comment by doitsujin** [comment]
Should be fixed as of 0d049f105c5880794de8aa90100ed057878c0e88, please test. Tell me if you need a build.

**Comment by Xaenalt** [comment]
If you could send me a build, that would be amazing, I have trouble compiling it on F28 due to too old mingw. I suppose I could compile the new mingw

**Comment by doitsujin** [comment]
Alright: [dxvk-mhw-fix.tar.gz](https://github.com/doitsujin/dxvk/files/2897217/dxvk-mhw-fix.tar.gz)

**Comment by Xaenalt** [comment]
That does indeed seem to have fixed it :D thanks!
