### ISSUE TITLE
dxvk-git doesn't present D3D11 device

### ISSUE THREAD

**Issue by t14462** [doitsujin/dxvk#931]
### Software information
Every single game can't initialize D3D11 device

### System information
- GPU: AMD RX560
- Driver: AMDGPU, RADV, Mesa-git 19.1, LLVM-svn 9.0.0
- Wine version: 4.2 Staging
- DXVK version: DXVK-git (AUR)

Logs doesn't say anything, something broken in commits around presenter, or in setup_dxvk64.sh

**Comment by doitsujin** [comment]
Sounds like a setup issue on your end. Please keep in mind that the AUR package is unofficial, I cannot provide support for that.

**Comment by t14462** [comment]
Hmm... OKay, looks like AUR winelib buiding bug. So if everything OK - i'll close it.
