### ISSUE TITLE
Metro Exodus doesn't start with Wine's DXGI

### ISSUE THREAD

**Issue by t14462** [doitsujin/dxvk#933]
### Software information
Metro Exodus on launch shows only a frozen black window with wine's builtin DXGI.
Just for statistics report. I dunno is this normal behavior or not.

### System information
- GPU: RX 560
- Driver: AMDGPU RADV, Mesa-git 19.1, LLVM-svn 9.0.0
- Wine version: 4.2 Staging / 4.2 Esync-TkG
- DXVK version: 1.0

### Log files
- d3d11.log:
- dxgi.log: 
[MetroExodus_d3d11.log](https://github.com/doitsujin/dxvk/files/2906731/MetroExodus_d3d11.log)
[MetroExodus_dxgi.log](https://github.com/doitsujin/dxvk/files/2906732/MetroExodus_dxgi.log)

**Comment by doitsujin** [comment]
When using wine's dxgi, please attach the **full** wine console output, and omit the DXGI log since that obviously no longer applies.

**Comment by Nikolay0054** [comment]
https://hastebin.com/ucoxagifet.rb here is wine console output

**Comment by doitsujin** [comment]
```
003b:fixme:dxgi:dxgi_output_FindClosestMatchingMode1 iface 0x34e5880, mode 0x54de30, closest_match 0x54de50, device (nil) stub!
```
Looks like this is the problem, wine doesn't implement that function yet.

**Comment by DocMAX** [comment]
but we need a solution

**Comment by t14462** [comment]
> but we need a solution

Just use DXGI from DXVK for now/

**Comment by DocMAX** [comment]
Ok thanks, that was easy. Somehow the default installation of /usr/bin/setup_dxvk installs with the --without-dxgi option on arch linux.

**Comment by t14462** [comment]
Bug fixed in wine-git by this patches below: https://bugs.winehq.org/show_bug.cgi?id=46783
