### ISSUE TITLE
setup_dxvk.sh file is not being installed after 1.0 update

### ISSUE THREAD

**Issue by Shished** [doitsujin/dxvk#934]
When building DXVK from source and installing it, setup_dxvk.sh file is not copied to the install prefix.
I set the install prefix to ~/dxvk/install and used build-win64.txt cross-file. Here is the list of files that being installed (provided by install-log.txt file):

```
~/dxvk/install/bin/dxgi.dll
~/dxvk/install/lib64/dxgi.dll.a
~/dxvk/install/bin/d3d11.dll
~/dxvk/install/lib64/d3d11.dll.a
~/dxvk/install/bin/d3d10core.dll
~/dxvk/install/lib64/d3d10core.dll.a
~/dxvk/install/bin/d3d10.dll
~/dxvk/install/lib64/d3d10.dll.a
~/dxvk/install/bin/d3d10_1.dll
~/dxvk/install/lib64/d3d10_1.dll.a
~/dxvk/install/lib64
~/dxvk/install/bin
~/dxvk/install
```

Winelib build is also affected.
Is this a bug or a feature? How to install libs to wineprefixes now?

**Comment by doitsujin** [comment]
This is intended, because the old setup script had the horrible property that it would only install the files for **one** architecture (so you'd have to run the script *twice*), whereas the new one handles both 32-bit and 64-bit DLLs. The downside is that it only works if the directory structure is like this:
```
|- setup-dxvk.sh
|- x32
| |- d3d11.dll etc,
|- x64
| |- d3d11.dll etc.
```
You can use `package-release.sh dev ~ --dev-build` as a quick way to generate a working development setup.

**Comment by Sebastiangperez** [comment]
I downloaded the release version , and the setup_dxvk.sh file do not work here no errors appear on screen , i just copied both directories and pasted into the last version and used the winetricks verb install. 
Strange ...

**Comment by doitsujin** [comment]
@Sebastiangperez what do you mean by "does not work"?

**Comment by Sebastiangperez** [comment]
> @Sebastiangperez what do you mean by "does not work"?
I just runned the file , tested a game with DXVK_HUD=version and appear the previous version, but when i used the verb file , that works.

**Comment by doitsujin** [comment]
Can you try to figure out why exactly it doesn't work for you? I can't reproduce the issue.

**Comment by Sebastiangperez** [comment]
> Can you try to debug the script to find out why exactly it doesn't work for you? I can't reproduce the issue.
I will try later i have to go to work right now.

**Comment by SveSop** [comment]
@Sebastiangperez Not tested this in depth, but if it is a "old" wineprefix that used symlinks, the uninstall script will not remove symlinks, and there might be troubles copying new dll's from the script if symlinks already exist.

You could test to remove the d3d1*.dll + dxgi.dll and/or symlinks manually (from both system32 and syswow64 folders) before installing via the new script, and also run `WINEPREFIX=your/prefix wineboot -u` to fix wine default fake dll's before installing DXVK via the new script (Atleast THAT seemed to work after i tested it yesterday.. but as i said, i have not tested much more tho).

@doitsujin Not overly fan of the "rename dll to .old if exist" function in the new script, as this may not work too well on "previously used prefixes" that have symlinks, but seems fine on clean and new prefixes (or if you uninstall old dxvk by hand like i described above).

**Comment by Sebastiangperez** [comment]
> @Sebastiangperez Not tested this in depth, but if it is a "old" wineprefix that used symlinks, the uninstall script will not remove symlinks, and there might be troubles copying new dll's from the script if symlinks already exist.
> 
> You could test to remove the d3d1*.dll + dxgi.dll and/or symlinks manually (from both system32 and syswow64 folders) before installing via the new script, and also run `WINEPREFIX=your/prefix wineboot -u` to fix wine default fake dll's before installing DXVK via the new script (Atleast THAT seemed to work after i tested it yesterday.. but as i said, i have not tested much more tho).

Yes , you have right , i not tested this in deep , i had the same old prefix with the old dlls already copied on it. 
I copied directly the files into the folders but some game shows that there not Directx11 installed, so i just move the files into another directory and run the verb file , and works just fine, it's obvious that's something wrong with my setup.

**Comment by doitsujin** [comment]
@SveSop 

> Not overly fan of the "rename dll to .old if exist" function in the new script, as this may not work too well on "previously used prefixes" that have symlinks

What do you mean? symlinks can be moved just fine, although the backup doesn't have the intended effect in this case. The idea is to restore the prefix to its original state when uninstalling DXVK from it, which neither the old script nor the winetricks verb could accomplish.

**Comment by SveSop** [comment]
@doitsujin 
The script did not remove symlinks if no .old file existed when using the "uninstall" function. Sure, as i said above, starting with a "new" or "clean" prefix, this is no problem. So its no "bug".

And tbh, "restore the prefix to its original state if you uninstall DXVK" is best done by using `wineboot -u` after deleting the dll's (cos they get automagically recreated), and not by restoring backups of the old fake dll's. 
If the script would overwrite the .old file with the current .dll when installing a new version, using uninstall to roll back dxvk to the "last working version" would be the only reasonable usage, but it does not seem to do that if the .old file already exist when installing.

I must admit i have not done too much testing, so i might be totally wrong here, and this result was some weirdness that happened with my prefix when i tested. I apologize if I am mistaken :)

**Comment by doitsujin** [comment]
Yeah, uninstalling from an old prefix doesn't work. As for `wineboot -u`, yes I know that this works, not sure if it's a great solution though.
