### ISSUE TITLE
How do I enable d3d11.relaxedBarriers?

### ISSUE THREAD

**Issue by laichiaheng** [doitsujin/dxvk#935]
### Software information
Resident Evil 2 Remake

### System information
- GPU: AMD RX580
- Driver: amdgpu
- Wine version: 4.1
- DXVK version: 1.0

Do I only need to add `d3d11.relaxedBarriers=1` in the game properties in steam?

**Comment by K0bin** [comment]
It's enabled by default for RE2, you don't need to do anything.

**Comment by laichiaheng** [comment]
@K0bin Thanks
