### ISSUE TITLE
very low fps(<5) playing cutscenes movies for Tomb Raider 9

### ISSUE THREAD

**Issue by andysendo** [doitsujin/dxvk#936]
### Software information
Tomb Raider 9

### System information
- GPU: nvidia k1100m
- Driver: debian 9 stable nvidia-glvnd 390.87-4~bpo9+1
- Wine version: wine4.0
- DXVK version: 0.96 / 0.94

the game test playing very well, fps>30, cpu load < 150%, but playing the cutscenes movies  fps always < 5. Tomb Raider 10 also have the same issue.

not all the dx11 game i've tested have the same issue, for now only found in Tomb Raider 9/10.

is it dxvk bug or not?

regards.

**Comment by xpander69** [comment]
first of all, amazingly old drivers for vulkan. Are those cutscenes movies? like not rendered ingame? then it probably is wine issue in general. whats the fps without dxvk? what video format is the playback?
where are the logs?

**Comment by doitsujin** [comment]
> nvidia-glvnd 390.87

https://github.com/doitsujin/dxvk/wiki/Driver-support#nvidia-267

**Comment by debianxfce** [comment]
There is native version of Tomb Raider 2013 in Steam. Do you have a crack or what?

**Comment by andysendo** [comment]
with wine builtin dx11 dlls cutscenes movies keeps 10~12 fps, slow but visual lag not too much, with dxvk visual lag very much.

so deal with the Immediate calculus cutscenes, maybe dxvk can make some improve? 

debian 9 stable + backports not commit nvidal 415.22 or later driver yet so cant update for now.

**Comment by doitsujin** [comment]
Closing because I cannot support outdated drivers.

Also, the behaviour you're observing is most likely just the normal stutter when compiling shaders, this is particularly bad in these two games and **cannot** be fixed.

**Comment by debianxfce** [comment]
> debian 9 stable + backports not commit nvidal 415.22 or later driver yet so cant update for now.

Remove Debian nvidia packages and use the run file from the nvidia site. Download the driver before removing Debian packages and install the kernel headers package and the build-essential package. Use the run file in the Linux rescue mode.
