### ISSUE TITLE
Anthem not run erro Directx!

### ISSUE THREAD

**Issue by Marcio2AA** [doitsujin/dxvk#942]
I am trying to run the game Anthem of Bioware by Lutris and happens this error of the Image, how to solve?

### Software information
Lutris
### System information
- GPU: Nvidia GTX 1070 Ti
- Driver: 418.43-3
- Wine version: 4.2-1
- DXVK version: 1.0

### Apitrace file(s)
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/Bb7FxdFg/DXVK-erro.png' border='0' alt='DXVK-erro'/></a>
### Log files
- d3d11.log: [Anthem_d3d11.log](https://github.com/doitsujin/dxvk/files/2915112/Anthem_d3d11.log)

- dxgi.log: [Anthem_dxgi.log](https://github.com/doitsujin/dxvk/files/2915115/Anthem_dxgi.log)

**Comment by doitsujin** [comment]
You have this set in your confg file:
`dxgi.customVendorId = 10de`

This is **known** to break Anthem.

**Comment by mixalis1987** [comment]
@Marcio2AA Set windows to 7 in wine config I think that was the fix I can't remember exactly. Or I didn't have DXVK enabled at the time in Lutris. Double check.

**Comment by Marcio2AA** [comment]
Ok, I'm afraid to put win 7 because I did it previously and with Anthem I took 2 suspensions of 12 hours without being able to access the game! Thank you for your support doitsujin and mixalis1987.

**Comment by mixalis1987** [comment]
@Marcio2AA I got suspended once on anthem for changing too many times when I was doing some testing but windows 7 does work I have it set now with dxvk 1.0. Strange that windows 10 didn't work for me in wine as EA says it want's it.
If you already changed it recently though before the 12 hours I would wait a bit before making any changes or login in, so you don't get suspended.

**Comment by Marcio2AA** [comment]
@mixalis1987 The error no longer appears when running the game, but the anthem window does not appear now, only the 2 processes remain on the Anthem system monitor in N / A. Yes I am with DXVK and the Esync checks

**Comment by mixalis1987** [comment]
@Marcio2AA Try just using 4.2 staging. I had same problem the only ones that started the game was version `tkg 4.0` and `4.2 staging` of wine for me. Now i'm using `4.2 staging` and its working.
**Caution:** Too many wine version changes in a day can also get you suspended.
****** My Lutris Config, if it helps ******
![config 1](https://user-images.githubusercontent.com/5172236/53586759-be88cd80-3b80-11e9-86e6-ecaaf289579e.png)
![config 2](https://user-images.githubusercontent.com/5172236/53586798-d3656100-3b80-11e9-93c0-d1bb18675908.png)
![config 3](https://user-images.githubusercontent.com/5172236/53586809-d8c2ab80-3b80-11e9-801f-ebb2297f99a4.png)
**********************
Also if your using wine staging try disabling CSMT in the staging tab in wine config. Mine is disabled.

**Comment by mixalis1987** [comment]
@Marcio2AA Oh and make sure Origins in-game overlay is disabled. That often causes problems with that enabled.

**Comment by Marcio2AA** [comment]
@mixalis1987 I made all the configs, but I fell into a new suspension, I'll wait, release and say whether or not Anthem.

**Comment by Marcio2AA** [comment]
@mixalis1987 Thanks. I managed to play the game.

**Comment by mixalis1987** [comment]
@Marcio2AA Your welcome.
