### ISSUE TITLE
Disney's Infinity 1.0 : Gold Edition does not work with DXVK

### ISSUE THREAD

**Issue by LeCharlatan** [doitsujin/dxvk#946]
Disney's Infinity 1.0 : Gold Edition doesn't use DXVK
Using Wine 4.0-staging through PlayOnLinux

The game generates an empty dxgi.log but no d3dx11.log

### Software information
There is no options to change graphics settings, then used standard/default game's settings

### System information
- GPU: Nvidia GTX 1070
- Driver: Proprietary v418.43
- Wine version: 4.0-staging
- DXVK version: 0.96 and 1.0

### Log files
d3d11.log is not rendered
dxgi.log: rendered but empty, useless

**Comment by Joshua-Ashton** [comment]
An apitrace would be useful.

**Comment by doitsujin** [comment]
Not a DXVK bug if the game doesn't even create a d3d11.log (i.e. does **not even load** d3d11.dll).

**Comment by LeCharlatan** [comment]
Got it, just wonder why it doesn't World with that game
