### ISSUE TITLE
Need help with the installation

### ISSUE THREAD

**Issue by halukcang** [doitsujin/dxvk#948]
Hello this is a basic question but while I am running the:
export WINEPREFIX=/path/to/.wine-prefix
./setup_dxvk.sh install  
Command
I keep getting a "not a valid wine prefix error"
I don't know what to do and I appreciate your help

**Comment by Joshua-Ashton** [comment]
You should set the /path/to/.wine-prefix to the path to your wine prefix.

**Comment by halukcang** [comment]
I have already done that I went to wine-stable folder and chosen the prefix but still got the same error, reinstalled the eine same thing happens.
/opt/usr/wine-stable/bin/wine

**Comment by doitsujin** [comment]
Don't run `export WINEPREFIX=/path/to/.wine-prefix` if you don't have multiple wine prefixes, or if you don't know what that command even does.

**Comment by SveSop** [comment]
@halukcang 
To create a new empty prefix:
`WINEPREFIX=/home/halukcang/mywineprefix wineboot`
When you do stuff with that, you reference this with `WINEPREFIX=/home/halukcang/mywineprefix`

eg.
`WINEPREFIX=/home/halukcang/mywineprefix ./setup_dxvk.sh install`
will install dxvk in the prefix "mywineprefix". This can ofc be whatever you want.

If you find fiddling with prefixes and making scripts and whatnot to start your favorite games bothersome, there is always stuff like lutris that makes fiddling with various prefixes a wee bit easier :)
[https://lutris.net/](https://lutris.net/)

**Comment by halukcang** [comment]
Thanks for the help. I know ıt was kind of a noob question but I just switched a week ago so all of this is new to me.

**Comment by PreritBhandari** [comment]
first write the export WINEPREFIX=/path/to/.wine-prefix  in the terminal window and run it.
then open the winetricks in terminal by simply typing winetricks .If you dont have wineprefix at that location, it will create it for you.And then you can run the setup .sh file.Hope This helps. :dancing_men:
