### ISSUE TITLE
DXVK Rust?

### ISSUE THREAD

**Issue by StinkyAnimeGirl** [doitsujin/dxvk#949]
Hello!

I heard there were some people aiming to port VK9 to Rust so I was wondering if there were any plans to port DXVK etc to Rust. I think it could be much faster!

Thanks!

**Comment by doitsujin** [comment]
No.

**Comment by Kreyren** [comment]
@StinkyAnimeGirl We are in FOSS community, Fork it and rewrite it yourself then o.o 

... yea DXVK in rust would be really cool
