### ISSUE TITLE
Elder scrolls online.  nVidia 1050, wine staging 2.21(64bit) DXVK build as of 20/02/2018 - Working great!

### ISSUE THREAD

**Issue by asharin75** [doitsujin/dxvk#95]
Not an issue as such, would like to say a big thank you to the author(s) of DXVK for finally allowing me to play ESO again.   With DXVK built as of 20/02/2018 with Wine staging 2.21 (64bit) I can run ESO at playable frame rates, with no texture corruption on ground or player models.
Previous versions of DXVK had either messed up player/npc models or totally invisible models.  Newer versions of Wine cause the old green ground texture bugs that ESO on nvidia/wine has suffered for ages.
The combo listed above makes it work...so...thanks for all the work :)

**Comment by doitsujin** [comment]
Glad to hear it's useful, and ESO has been added to the list of playable games a couple of days ago. If anything regresses, please open a new issue.
