### ISSUE TITLE
Basemark GPU crashes with unsupported IDXGIFactory5

### ISSUE THREAD

**Issue by SergeySlice** [doitsujin/dxvk#951]
DXVK is from source 05.03.2019 v1.0-11-ga40d8d4
Log
~~~~
info:  Intel HD Graphics 4000:

info:    Driver: 0.2.1841

info:    Vulkan: 1.0.101

info:    Memory Heap[0]: 

info:      Size: 1536 MiB

info:      Flags: 0x1

info:      Memory Type[0]: Property Flags = 0x1

info:      Memory Type[1]: Property Flags = 0xb

info:      Memory Type[2]: Property Flags = 0xf

warn:  DxgiFactory::QueryInterface: Unknown interface query

warn:  7632e1f5-ee65-4dca-87fd-84cd75f8838d

Unknown error 0x887A00040000000001CCED18wine: Unhandled page fault on read access to 0x00000000 at address 0x1c9261b (thread 0037), starting debugger...
~~~~~

I made simple implementation and got the app started
[patch-factory5.txt](https://github.com/doitsujin/dxvk/files/2932599/patch-factory5.txt)

**Comment by doitsujin** [comment]
Have you tried setting the Windows version in wine to Windows 7? IDXGIFactory5 is only supported on recent versions of Windows 10, so it would be surprising if an app that advertizes Windows 7 support actually requires it.

I don't intend to support that particular interface on its own without supporting the rest of DXGI 1.5, as it would probably break more apps than it fixes in the long run.

**Comment by SergeySlice** [comment]
May be[ the application ](https://www.basemark.com/products/basemark-gpu/)didn't check Windows version. 
~~~
System requirements
Android: Version 7.x and newer with Vulkan 1.0/OpenGL ES 3.1 drivers
Windows Desktop: Vulkan 1.0/OpenGL 4.5 drivers. 64-bit Windows version
~~~

But it checks Vulcan version
~~~
0037:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-9
warn:  Failed to create Vulkan 1.1 instance, falling back to 1.0

[mvk-info] MoltenVK version 1.0.33. Vulkan version 1.0.101.
~~~

**Comment by SergeySlice** [comment]
I set Windows 7.

**Comment by doitsujin** [comment]
Actually it turns out that this benchmark only supports D3D**12**, not 11. This is out of scope for DXVK, and if you plan on running it, use VKD3D in combination with Wine's DXGI.
