### ISSUE TITLE
Manjaro w/Steam+Wine+Proton: "\src\panorama\renderer\d3d10d2dsurface.cpp (9532) : Assertion Failed: No D2D device created, possible no GPU supoprting D3D10_FEATURE_LEVEL_9_1 or higher was found? Can't create surface."

### ISSUE THREAD

**Issue by esotericDisciple** [doitsujin/dxvk#953]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Name of the game, settings used etc.

"steam-wine steam" 
...Attempting to open a window for steam controller settings to see if I can find a way to circumvent a proton-related bug (https://github.com/ValveSoftware/Proton/issues/1549)  that prevents controllers from being detected or are poorly detected...

...But attempting to enter big-picture mode triggers this bug as well...

There are other display issues with running steam and its games, such as the screen not updating/refreshing when I switch to the store/browser window, breaking the plasma shell/desktop (unless I switch to 'virtual desktop' mode in wine) other issues that I can't remember and/or I'm too tired to address at the moment...

### System information
- GPU:NVIDIA Quadro K4000
- Driver:1:415.27-8
- Wine version:4.2-1
- DXVK version:1.0-1 

### Apitrace file(s)
- Put a link here
https://bugs.winehq.org/show_bug.cgi?id=46775
### Log files
- d3d11.log: https://bugs.winehq.org/show_bug.cgi?id=46775
- dxgi.log: https://bugs.winehq.org/show_bug.cgi?id=46775

**Comment by Joshua-Ashton** [comment]
Big picture and the controller dialog uses D3D10 with Feature Level 9_1 iirc.

I am not sure how well supported this is in DXVK, as I think there is some extra ctable stuff in the shader and there may be some differences in formatting.

Although the issue may also rely in Direct2D being used -- I'm not sure how its interop/usage of D3D is so it could be that wined3d's d2d is not interacting nicely with DXVK given it is now supplying the d3d1x layer.

**Comment by doitsujin** [comment]
The Direct2D thing was fixed in DXVK a while ago, unfortunately now the bloody thing needs `D3D10CreateEffectFromMemory`, which DXVK does not and will not support, see
https://github.com/doitsujin/dxvk/issues/1070#issuecomment-502198496
