### ISSUE TITLE
Diablo 

### ISSUE THREAD

**Issue by lsdage** [doitsujin/dxvk#959]
Hello,

I am having an issue with Diablo 3 64-bit under DXVK.
When the game starts, the screen goes gray and does not continue. The file d3d11.log gets full of the messages:
```
err:   D3D11: Cannot create texture:
  Format:  44
  Extent:  32x32x1
  Samples: 1
  Layers:  1
  Levels:  1
  Usage:   48
  Flags:   0
```

The longer I stay on the gray screen, the more times this message is repeated.
I do not get to hear the game sound / music on the gray screen.
I get the same result if I run the game via Battle.net client or directly.
If I run Diablo 3 in windowed mode (-launch -windowed), it is the same.

The 32-bit Diablo 3 runs fine with just the Wine native libraries.
The 64-bit Diablo 3 runs with native libraries but the performance is appalling.

### Software information
Diablo 3
Tried on Debian 10 Testing and Lubuntu 18.10
Tried various setting, resolutions etc. in the game, various settings in Wine, various versions of MESA drivers and DXVK, it always ends with the same gray screen and the same error.

### System information
- GPU: HD Graphics 4400 on Intel Haswell CPU
- Driver: Mesa, 18.3.2.; 18.3.4; 19.1 (via PPA/Oibaf)
- Wine version: 4.2 Staging; 4.3 Staging
- DXVK version: 0.96; 1.0; latest Github master

### Apitrace file(s)
[apitrace_D3_x64.zip](https://github.com/doitsujin/dxvk/files/2949383/apitrace_D3_x64.zip)

### Log files
[Diablo III64_d3d11.log](https://github.com/doitsujin/dxvk/files/2949381/Diablo.III64_d3d11.log)
[Diablo III64_dxgi.log](https://github.com/doitsujin/dxvk/files/2949382/Diablo.III64_dxgi.log)

Any help is appreciated! Thank you!

**Comment by doitsujin** [comment]
Haswell does not have good-enough Vulkan support to run DXVK.
