### ISSUE TITLE
Battlefield 1 Micro sounds stutters.

### ISSUE THREAD

**Issue by Smeltie** [doitsujin/dxvk#962]
When playing battlefield 1 the audio has micro stutters when alot is going on or when more than a few sounds are playing.
this seems to overload the system resulting in a small hickup in the sound plus a small framedrop.
it does this very regularly, sometimes once a minute sometimes every 2 to 3 seconds.
I haven't seen anyone express this issue before so i thought i'd add it.
i have tried multiple settings and options but nothing seemed to make a difference.

### Software information
Name of the game, settings used etc.
Game: Battlefield 1
Settings: i tried ultra and medium presets, same results.
Ingame audio settings: headphones and wartapes, both same result

### System information
- GPU: amd ryzen 7 1700x
- Driver: Nvidia 418.43
- Wine version: tkg-protonified-3.21-x86_64
- DXVK version: (latest as of writing this issue)

**Comment by doitsujin** [comment]
DXVK has nothing to do with audio.
