### ISSUE TITLE
Device filter substring matching not working

### ISSUE THREAD

**Issue by win8linux** [doitsujin/dxvk#963]
### Software information
Name of the game, settings used etc.

### System information
- GPU: Radeon Vega 8/Radeon RX 560X
- Driver:  Mesa AMDGPU 18.1.0
- Wine version: 4.3
- DXVK version: 1.0

It seems that substring matching for the device filter setting does not work. Testing with both Metal Gear Solid V: The Phantom Pain and Sleeping Dogs: Definitive Edition, using `DXVK_FILTER_DEVICE_NAME="POLARIS11"` causes DXVK to fail finding the dGPU:
```
warn:  DXVK: No adapters found. Please check your device filter settings and Vulkan setup.
```
Using the dGPU's full device name with `DXVK_FILTER_DEVICE_NAME="AMD RADV POLARIS11 (LLVM 7.0.0)"`, DXVK successfully finds it and uses it.

While this is not yet working, perhaps the README should be updated to reflect this? I've already made the necessary changes here:
https://github.com/win8linux/dxvk/commit/afe9dbceade57622d27cfb00aa5991bae000a3b3

Should I make a PR request for this?

EDIT: Oops, made a mistake with one of the env variables.

**Comment by doitsujin** [comment]
> Should I make a PR request for this?

No, because this "solution" is exceptionally stupid. You **can** however submit a PR to fix the bug.

That said, I cannot reproduce this, the device filter works fine for me. Please make sure that you actually use DXVK 1.0 and not an older version.

**Comment by doitsujin** [comment]
Here's the code:
```
      if (std::string(deviceProps.deviceName).find(m_matchDeviceName) == std::string::npos)
        return false;
```
That's not even subject to system locale or character encoding issues.

**Comment by win8linux** [comment]
Oops, I made a mistake there. Changed it to reflect the actual env variable.

**Comment by win8linux** [comment]
Also, I'm certain that DXVK 1.0 is used since that's the version selected in the Lutris runner config:
![image](https://user-images.githubusercontent.com/11584387/54212033-48d81680-451d-11e9-9897-4ab59a8ea757.png)

**Comment by doitsujin** [comment]
Anyway, can you please attach log files?

On my system this clearly works, and since this is a standard library function there's basically no way it wouldn't work for you.

**Comment by win8linux** [comment]
[dxgi.log](https://github.com/doitsujin/dxvk/files/2957638/dxgi.log)

The `d3d11.log` file was empty.

**Comment by doitsujin** [comment]
Can you also post the log *without* that env var set?

**Comment by Joshua-Ashton** [comment]
I too cannot replicate this.
Substring matching works fine here and I cannot see a reason in the code for the issues you are having.
