### ISSUE TITLE
World of Warcraft Freezes/Hangs Patch 8.1.5

### ISSUE THREAD

**Issue by Booleanperspective** [doitsujin/dxvk#964]
[Many users](https://us.forums.blizzard.com/en/wow/t/linux-client/119819/) appear to be having issues with the [new major changes](https://us.forums.blizzard.com/en/wow/t/new-graphics-apis-in-8-1-5/121542) in the World of Warcraft engine.

I also have this issue. I am able to get into the game and login to a character for around 5 seconds before the game hangs and freezes my entire system.

### Software information
World of Warcraft, installed with Lutris using dxvk 1.0

### System information
- GPU: GTX 1080 Ti
- Driver: Nvidia 418.43-5
- Wine version: 4.2
- DXVK version: 0.96 (Also tested on 1.0)

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
```
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_1
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_1
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_driver_properties
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 5968 valid state cache entries
info:  DXVK: Using 16 compiler threads
info:  D3D11CoreCreateDevice: Probing D3D_FEATURE_LEVEL_11_1
info:  D3D11CoreCreateDevice: Using feature level D3D_FEATURE_LEVEL_11_1
info:  Enabled device extensions:
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_dedicated_allocation
info:    VK_KHR_descriptor_update_template
info:    VK_KHR_driver_properties
info:    VK_KHR_get_memory_requirements2
info:    VK_KHR_image_format_list
info:    VK_KHR_maintenance1
info:    VK_KHR_maintenance2
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
info:  DXVK: Read 5968 valid state cache entries
info:  DXVK: Using 16 compiler threads
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  1876x1000
  Image count:  3
info:  Presenter: Actual swap chain properties:
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
  Buffer size:  931x1000
  Image count:  3
```
- dxgi.log: 
```
info:  Game: Wow.exe
info:  DXVK: v0.96
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  GeForce GTX 1080 Ti:
info:    Driver: 418.43.0
info:    Vulkan: 1.1.95
info:    Memory Heap[0]: 
info:      Size: 11264 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 11965 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
warn:  DxgiFactory::QueryInterface: Unknown interface query
warn:  7632e1f5-ee65-4dca-87fd-84cd75f8838d
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  Game: Wow.exe
info:  DXVK: v0.96
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_physical_device_properties2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  GeForce GTX 1080 Ti:
info:    Driver: 418.43.0
info:    Vulkan: 1.1.95
info:    Memory Heap[0]: 
info:      Size: 11264 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:      Memory Type[8]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 11965 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[9]: Property Flags = 0x6
info:      Memory Type[10]: Property Flags = 0xe
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
warn:  DXGI: MakeWindowAssociation: Ignoring flags
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
```

**Comment by EntropicEffect** [comment]
Have you tried recording an apitrace?

**Comment by mozo78** [comment]
Try to stop the nvapi hack.

**Comment by prosenboim** [comment]
tried running with hack disabled. same problem

**Comment by prosenboim** [comment]
Also, getting errors
0078:err:d3d:wined3d_debug_callback 0x272f8360: "GL_INVALID_OPERATION error generated. Target buffer must be bound and not overlapped with mapping range.".

**Comment by doitsujin** [comment]
Does this still work with wined3d?

**Comment by prosenboim** [comment]
it looks working with wined3d. I've seen reports that it works with vkd3d too, but didn't try it personally.

**Comment by doitsujin** [comment]
Just tested, both `D3D11` and `D3D11 (Legacy)` work completely fine on my end with latest RADV.

What **exactly** happens anyway? Is it a GPU hang?

**Comment by prosenboim** [comment]
Currently, for me, game hangs. I'm able to kill it, and desktop continues to work normally.
Also, see 'NVRM: Xid (PCI:0000:01:00): 41, CCMDs 00000023 0000b0b5' in dmesg output.

**Comment by doitsujin** [comment]
Well, fun times. Can't debug those.

**Comment by garpu** [comment]
dxvk 1.0, wine-staging 4-2, Nvidia 418.42.02, and if I set the version to windows 10, I can get into the game. But then a minute or so later, I crash and the desktop locks hard.  I'm getting this, though: NVRM: Xid (PCI:0000:07:00): 39, CCMDs 00000013 0000c1b5

Same error, regardless of Legacy or regular DX11 in the WoW settings. Logs attached. 

[Wow_d3d11.log](https://github.com/doitsujin/dxvk/files/2961625/Wow_d3d11.log)
[Wow_dxgi.log](https://github.com/doitsujin/dxvk/files/2961627/Wow_dxgi.log)

**Comment by doitsujin** [comment]
Logs sadly aren't helpful to debug this, in fact I cannot debug this at all since I don't know what the Xid errors mean. I suggest everyone playing WOW give vkd3d a try, there's just nothing I can do here.

**Comment by thedae** [comment]
> dxvk 1.0, wine-staging 4-2, Nvidia 418.42.02, and if I set the version to windows 10, I can get into the game. But then a minute or so later, I crash and the desktop locks hard. I'm getting this, though: NVRM: Xid (PCI:0000:07:00): 39, CCMDs 00000013 0000c1b5
> 
> Same error, regardless of Legacy or regular DX11 in the WoW settings. Logs attached.
> 
> [Wow_d3d11.log](https://github.com/doitsujin/dxvk/files/2961625/Wow_d3d11.log)
> [Wow_dxgi.log](https://github.com/doitsujin/dxvk/files/2961627/Wow_dxgi.log)
> 
> ETA: it's like when I'm loading a new area that things lock. For instance, I logged into the Great Seal, and it locked. Next time I was in, I was able to make it to the flight path before locking. And so on.

In my case it crashes way earlier, but it's the same behaviour and error code as yours. I'm using dxvk 1.0, lutris + tkg-4.2 runner and nvidia 390 drivers on a Nvidia MX150

Just FYI, if I disable dxvk from lutris runner config and switch to "Directx11 Legacy" within the game, it works, but with a very poor performance (from ~50 to ~15fps).

I understand it's hard to debug and fix, thanks for the effort @doitsujin

**Comment by darek1945** [comment]
> In my case it crashes way earlier, but it's the same behaviour and error code as yours. I'm using dxvk 1.0, lutris + tkg-4.2 runner and nvidia 390 drivers on a Nvidia MX150
> 
> Just FYI, if I disable dxvk from lutris runner config and switch to "Directx11 Legacy" within the game, it works, but with a very poor performance (from ~50 to ~15fps).
> 
> I understand it's hard to debug and fix, thanks for the effort @doitsujin

same here

**Comment by godlike64** [comment]
> Logs sadly aren't helpful to debug this, in fact I cannot debug this at all since I don't know what the Xid errors mean. I suggest everyone playing WOW give vkd3d a try, there's just nothing I can do here.
> 
> fwiw I _can_ reproduce this on my GTX 670, but not on AMD.

I don't know if this might be useful or not, but using a newer DXVK (1.0) I was able to spot this on the lutris logs:

~~~
err: DxvkDevice: Command buffer submission failed: VK_ERROR_DEVICE_LOST
err: DxvkDevice: Command buffer submission failed: VK_ERROR_DEVICE_LOST
err: DxvkDevice: Command buffer submission failed: VK_ERROR_DEVICE_LOST
err: DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
err: DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
err: DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
err: DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
err: DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
err: DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
err: DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
err: DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
err: DxvkSubmissionQueue: Failed to sync fence: VK_ERROR_DEVICE_LOST
~~~

This is in addition to the NVRM Xid 41 errors as noted earlier. Both of these logs (VK_ERROR_DEVICE_LOST and the NVRM Xid 41 one) happen right as the game 'freezes'. I say 'freezes' because I can still hear music, but if I don't X11 kill the window right away it starts to lock up my entire desktop.

Currently using nvidia-drivers-418.43 (this issue does seem to be related only to NVIDIA cards). Probably related to https://www.wowhead.com/news=289041.2/nvidia-driver-optimizations-for-patch-8-1-tides-of-vengeance. Beats me why a graphics pseudo-update would hit at this point in the patch lifecycle but oh well.

Currently trying to get 4.1 staging + vkd3d to work. So far I was greeted by a black screen when forcing DX12 (although that in itself is promising enough, for something that used to not work completely).

Sorry if this adds more noise than information. Let me know if I can provide any further debugging steps.

**Comment by btodd83** [comment]
From Nvidia's documentation it looks like both those Xid Errors are unused.

[https://docs.nvidia.com/deploy/xid-errors/index.html](url)

**Comment by Thaodan** [comment]
Has anyone noticed this error?:
`warn:  DxgiFactory::QueryInterface: Unknown interface query
warn:  7632e1f5-ee65-4dca-87fd-84cd75f8838d
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
warn:  DxgiAdapter::QueryInterface: Unknown interface query
warn:  7abb6563-02bc-47c4-8ef9-acc4795edbcf
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
ACCESS_VIOLATION : error 132: ERROR #132 (0x85100084) Fatal exception!
 The instruction at "0x000000018000396a" referenced memory at "0x0000000000000000".
The memory could not be "read".
`

**Comment by Thaodan** [comment]
I noticed one query is from here:
https://github.com/CMCHTPC/DelphiDX12/blob/master/Units/DX12.DXGI1_5.pas#L53

**Comment by Thaodan** [comment]
https://github.com/Microsoft/DirectX-Graphics-Samples/commit/f2cd4470851b0f87a92f4e9b4147dde8b8a987d2

**Comment by Thaodan** [comment]
7abb6563-02bc-47c4-8ef9-acc4795edbcf seems to be an undocumented interface:
https://github.com/bo3b/3Dmigoto/issues/32
https://github.com/bo3b/3Dmigoto/blob/e88d97fd57c6ddec7424be274f4cff2886693aca/DirectXGI/DXGIWrapper.cpp#L713

**Comment by Nuadh** [comment]
> Has anyone noticed this error?:
> 
> ```
> warn:  DxgiFactory::QueryInterface: Unknown interface query
> 
> warn:  7632e1f5-ee65-4dca-87fd-84cd75f8838d
> 
> info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
> 
> warn:  DxgiAdapter::QueryInterface: Unknown interface query
> 
> warn:  7abb6563-02bc-47c4-8ef9-acc4795edbcf
> 
> info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
> 
> info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
> 
> ACCESS_VIOLATION : error 132: ERROR #132 (0x85100084) Fatal exception!
> 
>  The instruction at "0x000000018000396a" referenced memory at "0x0000000000000000".
> 
> The memory could not be "read".
> ```
> ```

I also get that error if I'm using wine-tkg-4.2. Everything is working nice with wine-staging-4.3.

**Comment by garpu** [comment]
https://www.reddit.com/r/linux_gaming/comments/b0gvmf/wow_815_freezes/eigcf0r/ 

Allegedly a windows 10 user is having the same issue, also Nvidia. Could very well be a driver issue.

**Comment by Thaodan** [comment]
I noticed that using the dxvk.dxgi backend was the issue. Wine's dxgi backend works better with multithreaded d3d11.

**Comment by Thaodan** [comment]
Please see #967

**Comment by Thaodan** [comment]
[nvrm.log](https://github.com/doitsujin/dxvk/files/2963931/nvrm.log)
[Wow_d3d11.log](https://github.com/doitsujin/dxvk/files/2963933/Wow_d3d11.log)

**Comment by doitsujin** [comment]
Can anyone test this hack:
[wow-test.patch.txt](https://github.com/doitsujin/dxvk/files/2964032/wow-test.patch.txt)

There's a game bug in *some* regions which actually triggers validation errors, the above patch seems to fix GPU hangs on my GTX 670.

**Comment by thedae** [comment]
> Can anyone test this hack:
> [wow-test.patch.txt](https://github.com/doitsujin/dxvk/files/2964032/wow-test.patch.txt)
> 
> There's a game bug in _some_ regions which actually triggers validation errors, the above patch seems to fix GPU hangs on my GTX 670.

I've been trying to compile with the patch applied, but I'm having issues with the dependencies, sorry. Let's see if someone else can help you out.

**Comment by doitsujin** [comment]
@thedae here's a build:
[dxvk-master.tar.gz](https://github.com/doitsujin/dxvk/files/2964170/dxvk-master.tar.gz)

**Comment by thedae** [comment]
It's working flawlessly so far! I'm going to move around regions to check that it's really fixed

**Comment by doitsujin** [comment]
Okay, thanks for testing. Also thanks to @ZeroFault for finding this.

**Comment by prosenboim** [comment]
Thanks! Works great so far, and with new directx11 even faster than before!

**Comment by a-lutz** [comment]
Thank you soooo much, it works perfectly now :)

**Comment by andrewschott** [comment]
Fixed issue for me as well, thanks!

**Comment by MadMagnetic** [comment]
Can someone help me to understand - how to use this? I'm running Linux mint 19.1 mate x64, nvidia gtx850m, 390.77 driver

**Comment by prosenboim** [comment]
@MadMagnetic 
download [dxvk-master.tar.gz](https://github.com/doitsujin/dxvk/files/2964170/dxvk-master.tar.gz),
extract it, and in created directory, run command `WINEPREFIX=/path/to/your/wineprefix ./setup_dxvk.sh install`
If you originally installed dxvk via Lutris, or by some other means, you probably need to find out how to install it from there.

**Comment by LP0101** [comment]
@MadMagnetic @prosenboim 

If installed via Lutris, set the DXVK version to manual, set your WINEPREFIX to wherever Lutris installed WoW, and run the command as usual. Worked for me.

**Comment by xilcoy** [comment]
FYI, Blizzard took @doitsujin's advice and fixed their game:
https://us.forums.blizzard.com/en/wow/t/linux-client/119819/87:

Post from [Rommax - WoW Developer](https://us.forums.blizzard.com/en/wow/u/rommax-1333/summary) referencing this github issue directly:
> With the most recent 8.1.5 build (29732) the DX11 bug causing issues should be fixed and the workaround changeset for dxvk shouldn’t be necessary anymore, though it should be harmless to keep.

**Comment by terndrup** [comment]
Unfortunately this issue is back and the old DXVK fix no longer works :( as of today, the game crashes with an 132 Error as soon I try to log in (login screen finishes and when its about to transition into the game the crash occurs). Any chance we  can reopen this?

**Comment by doitsujin** [comment]
Was there a game update or did you just screw up your wine/battle.net configuration?

**Comment by terndrup** [comment]
There was a minor game update which apparently addresses some legacy DX11 problems so presumably that has messed something up. I'm using the same wine/bnet configuration that has been working flawlessly for months. I'm not sure how to run it just with wined3d, can you point me to some instructions for that?

If the wined3d works I can create a new issue with all my specs and info etc.

**Comment by doitsujin** [comment]
> I'm not sure how to run it just with wined3d, can you point me to some instructions for that?

Just disable DXVK. I have no idea how you launch the game; if you're using Lutris then there's an option somewhere in the Lutris GUI.

Since you mentioned D3D11 legacy fixes, please test both the D3D11 legacy and the new D3D11 mode (the "new" mode should be preferred anyway when using DXVK).

**Comment by terndrup** [comment]
Yes, I'm using Lutris. Disabling DXVK means when I launch the game it throws an "Battle.net could not find a missing DLL" error - let me try to see if I can get it to run so I can test the D3D11 mode. Thanks!

**Comment by terndrup** [comment]
OK I managed to start it up without DXVK and it works (does not crash) but it runs at around 1-2 FPS. I'll create a new issue.

**Comment by godlike64** [comment]
> Unfortunately this issue is back and the old DXVK fix no longer works :( as of today, the game crashes with an 132 Error as soon I try to log in (login screen finishes and when its about to transition into the game the crash occurs). Any chance we can reopen this?

Leaving this here in case somebody has this same issue: game is working fine for me, but I do get the Error 132 (IIRC it's an access violation error, memory could not be "read" or something like that) from time to time, typically after a certain update (major or minor) has hit. This error I usually relate to not having the correct windows version on the WINEPREFIX.

So, in order to fix this, what I usually do is run winecfg on the WINEPREFIX, set it to Windows 7, then back to Windows 10. That usually fixes it.

This issue was originally about a game hang (and subsequent desktop hang) that occurred primarily on NVIDIA cards using DXVK, unrelated to the Error 132 bit.
