### ISSUE TITLE
Error when installing DXVK (object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded)

### ISSUE THREAD

**Issue by YamiYukiSenpai** [doitsujin/dxvk#965]
When I ran the install script, this error popped up:
`ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
`
Uninstalling `gtk3-nocsd` made the error multiply.  Reinstalling it brought the number of same error printed out back to one.

**Comment by doitsujin** [comment]
Install the 32-bit version of the package as well to make it go away.

Anyway, not a DXVK bug, it's probably wine which needs this.
