### ISSUE TITLE
World of Warcraft patch 8.1.5 mouse jumping on DXVK

### ISSUE THREAD

**Issue by will-lp** [doitsujin/dxvk#966]
Hey there! I've been running WoW on Playonlinux because I never managed to set `DRI_PRIME=1` on Lutris. Well, after patch 8.1.5 my playonlinux with wine-3.19-staging-pba dropped my FPS from ~30 to ~15, even in older areas. I gave Lutris another shot and, though I still can't set DRI_PRIME, DXVK worked! And, OMG, it's so smooth! But sadly the mouse is now "jumping" when turning the camera and it's pretty unplayable (this doesn't happen in wine-3.19-staging-pba). Keyboard turning is very smooth, though. The cursor hides when I'm dragging, but sometimes (rarely) it doesn't, and I can see it doing the little jumps in the middle of the screen.

Here's my setup:

### Software information
World of warcraft: 8.1.5 build 29701 mar 12 2019
Graphic settings: minimum (1). Tried both `DirectX 11` and `DirectX 11 Legacy`.
Lutris: 0.5.0.1
OS: Ubuntu 18.04.2 LTS
kernel: 4.15.0-46-generic

### System information
- GPU: 
```
    03:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330 / M430 / R7 M520] (rev ff) (prog-if ff)
    !!! Unknown header type 7f
      Kernel driver in use: amdgpu
      Kernel modules: radeon, amdgpu
```

- Driver: `amdgpu 18.20`
- Wine version: `tkg-4.2-x86_64` (Lutris runner)
- DXVK: 1.0 (installed through Lutris)

I also get a lot of these, means I shouldn't even be trying to run DXVK?

	WARNING: radv is not a conformant vulkan implementation, testing use only.
	INTEL-MESA: warning: Haswell Vulkan support is incomplete

### Apitrace file(s)
- I'm checking how to generate these files.

### Log files
- d3d11.log / dxgi.log: I couldn't reproduce the bug with `DXVK_LOG_LEVEL=debug` as it makes the game hangs when I select my toon.

[Wow_d3d11.log](https://github.com/doitsujin/dxvk/files/2961956/Wow_d3d11.log)
[Wow_dxgi.log](https://github.com/doitsujin/dxvk/files/2961957/Wow_dxgi.log)

### Stuff I tried:

- winecfg "Automatically capture mouse on fullscreen windows" = bug persists
- Enabling Lutris' ESync with wine `tkg-4.2-x86_64` = bug persists
- Lutris' Mouse Warp Override FORCE = bug persists
- Switching wine versions `4.3-x86_64`, `staging-pba-3.19`, `staging-pba-3.18`, `tkg-4.2-x86_64` = bug persists
- DXVK version 0.90 and 0.96 (through Lutris) = bug persists, also, FPS drop
- On PoL I used to have `__GL_THREADED_OPTIMIZATIONS="1"` and `mesa_glthread="true"`. I also added then on Lutris, not sure if they are still needed, but it doesn't change the bug.

**Comment by doitsujin** [comment]
Why do you think this is a DXVK bug? DXVK doesn't do **anything** with your mouse.

**Comment by doitsujin** [comment]
Also, I couldn't reproduce this problem while testing #964.

**Comment by will-lp** [comment]
Because it doesn't happen with wine-3.19-pba-staging

**Comment by will-lp** [comment]
Found it! It was fixed by enabling Vertical Sync!

**Comment by Veske** [comment]
I get this same behaviour when running on Wayland. On Xorg it's not doing that.
