### ISSUE TITLE
Star Wars Battlefront 2015 Radeon driver error message

### ISSUE THREAD

**Issue by doomicle** [doitsujin/dxvk#968]
I got Star Wars Battlefront 2015 to run in wine yesterday. But it really needs DXVK in order to be able to solve various graphical glitches.
The problem I'm having with DXVK enabled, is that SWBF brings up an error message that the AMD driver isn't detectable, and that the game requires a Radeon driver of a certain version to be able to function. There must be some kind of driver version checker that takes place before it launches the game.
I tried putting some registry entries in with the wine registry editor, to see if I could spoof a Radeon driver version. I wasn't able to get that to work however, or not in a way that the SWBF driver checker recognises.

### Software information
Star Wars Battlefront (2015 version), Wine tkg-4.0 DXVK 1.0

### System information
- GPU: nVidia Geforce GTX 1060
- Driver: nvidia-driver-415
- Wine version: tkg-4.0
- DXVK version: 1.0

**Comment by Tk-Glitch** [comment]
I would try disabling the nvapi hack as well as disabling nvapi.dll/nvapi64.dll in your wine prefix. Frostbite usually doesn't like the hack.

**Comment by doomicle** [comment]
Ah thanks :) Interesting. Yea that seems to be what this guy over at Lutris did for me to get the game to work with DXVA:

https://forums.lutris.net/t/help-with-star-wars-battlefront-2015/5222/2

**Comment by doitsujin** [comment]
Can you post the log files, or the exact name of the executable? I'll add a workaround, Frostbite games are know to not work well with the nvapi hack.

**Comment by doomicle** [comment]
Hi, there are two exe's that people would use:
starwarsbattlefront.exe
starwarsbattlefronttrial.exe

The latter is for the trial version of the game and isn't used by the full version to my knowledge, though  it's been downloaded into my game directory by Origin for some reason.

I'm sort of a newb with this sort of stuff, so I don't know how to get my logs.

**Comment by Joshua-Ashton** [comment]
> I'm sort of a newb with this sort of stuff, so I don't know how to get my logs.

The logs should be in the folder of the game binaries.
Look for ``starwarsbattlefront_d3d11.log`` and ``starwarsbattlefront_dxgi.log``

If they aren't in the game binary folder then they maybe wherever Origin decided to have its working dir; you can probably do a search for these files starting from your Origin folder in this case.

**Comment by doomicle** [comment]
Are these any good?

[o264_log_0.txt](https://github.com/doitsujin/dxvk/files/2966874/o264_log_0.txt)
[o264_log_1.txt](https://github.com/doitsujin/dxvk/files/2966875/o264_log_1.txt)

**Comment by Joshua-Ashton** [comment]
These are logs from a video encoder.

**Comment by Joshua-Ashton** [comment]
Look for ``starwarsbattlefront_d3d11.log`` and ``starwarsbattlefront_dxgi.log``

If you are playing the trial then it would be ``starwarsbattlefronttrial_d3d11.log`` and ``starwarsbattlefronttrial_dxgi.log``

**Comment by doomicle** [comment]
Haha. Maybe they were from the program I was using for screen recordings.

Hmm, here we go:
[starwarsbattlefront_d3d11.log](https://github.com/doitsujin/dxvk/files/2966903/starwarsbattlefront_d3d11.log)
[starwarsbattlefront_dxgi.log](https://github.com/doitsujin/dxvk/files/2966904/starwarsbattlefront_dxgi.log)

Thanks for your help and patience Josh :)
