### ISSUE TITLE
Ashes of Singularity FPS drops

### ISSUE THREAD

**Issue by tsalwierz** [doitsujin/dxvk#969]
Ashes of singularity, "Crazy" settings @ 4k resolution, 2xAA. Game runs with esync disabled.

- GPU: 2080 ti
- Driver: 418.43
- Wine version: Proton - 3.16-8
- DXVK version: 1.0

I know the game can be played with native Vulkan, but while running DXVK the overall average FPS is good. However, it frequently dips in the 40's to low 25's during the GPU benchmark. When running Vulkan, it's usually in the 60's with one or two dips to the 49-50's.

I don't know if this can be reproduced on a lower resolution. As you can see in the screenshot, during the FPS drops GPU utilization is also down by around 40%. It's normally at 100%.

It's possible this isn't a DXVK issue at all and a problem with how DX11 is implemented in the game, but throwing this out there anyway.
![ashes-fps](https://user-images.githubusercontent.com/7935624/54360063-3cd57d00-4621-11e9-9a76-0ad4b2ac86a6.jpeg)

**Comment by doitsujin** [comment]
This is to be expected when comparing D3D11 to the native Vulkan implementation in a game that is notoriously slow with D3D11.

**Comment by tsalwierz** [comment]
Right, I should have worded it better. DX11 performance is good on Windows, but DXVK performance has frequent dips into the low 28 FPS.

According to the benchmark, Normal & Medium batches are within 10FPS of each other compared to Windows vs DXVK,, but when it comes to heavy batches there is a ~20 FPS difference which is significant at 4k resolution.

Even with Linux set to the lowest settings, it can’t match the FPS on Windows (crazy settings) on Long Shot 3 in the benchmark. All other locations in the benchmark show higher FPS then Windows.

(left, Linux/low settings. Right, Windows/crazy settings)
![ashes-dxvk-windows10](https://user-images.githubusercontent.com/7935624/54470095-9cd23d80-475f-11e9-82c1-fe0e8ac1056d.jpeg)

**Comment by tsalwierz** [comment]
> This is to be expected when comparing D3D11 to the native Vulkan implementation in a game that is notoriously slow with D3D11.

Right, I should have worded it better. DX11 performance is good on Windows, but DXVK performance has frequent dips into the low 28 FPS.

According to the benchmark, Normal & Medium batches are within 10FPS of each other compared to Windows vs DXVK,, but when it comes to heavy batches there is a ~20 FPS difference which is significant at 4k resolution.

Even with Linux set to the lowest settings, it can’t match the FPS on Windows (crazy settings) on Long Shot 3 in the benchmark. All other locations in the benchmark show higher FPS then Windows.

(left, Linux/low settings. Right, Windows/crazy settings)
![ashes-dxvk-windows10](https://user-images.githubusercontent.com/7935624/54470095-9cd23d80-475f-11e9-82c1-fe0e8ac1056d.jpeg)

**Comment by K0bin** [comment]
Just to get that out of the way, are you sure you ran both at the same resolution?

**Comment by tsalwierz** [comment]
Yes, same resolution. The screenshot is smaller on the right because it's
an image being displayed on my secondary monitor.

**Comment by doitsujin** [comment]
Lower performance than Windows is also expected, **especially** when compared to Nvidia's Windows drivers which are vastly more CPU efficient.
