### ISSUE TITLE
Shadow Tactics just quits after the loading a level

### ISSUE THREAD

**Issue by yoshimo** [doitsujin/dxvk#97]
### Software information
Shadow Tactics GoG Version 1.2.1f 32bit Highest Graphic Settings

### System information
- GPU: AMD Radeon RX 480
- Driver: Radeon 18.2.2
- Wine version: none, used Windows 10
- DXVK version: 0.21

### Log files
- d3d11.log: 
[d3d11.log](https://github.com/doitsujin/dxvk/files/1745778/d3d11.log)
- dxgi.log: 
[dxgi.log](https://github.com/doitsujin/dxvk/files/1745776/dxgi.log)

**Comment by doitsujin** [comment]
Finally works with latest `master`, although the game still has major visual issues due to the lack of Stream Output (#135).
![bildschirmfoto-698](https://user-images.githubusercontent.com/25567304/40591040-2d97ee6e-620a-11e8-99be-ce14c0d72611.png)
