### ISSUE TITLE
GRID 2 is stuck on a black screen

### ISSUE THREAD

**Issue by tannisroot** [doitsujin/dxvk#972]
When I launch GRID 2 from Steam (got it for free from Humble) using DXVK (tried Proton and Lutris' Windows Steam with latest DXVK), the game is stuck on a black screen. Doesn't launch with WineD3D either.
In a d3d11 log, an interesting error pops up:
```
err:   D3D11: Cannot create texture:
  Format:  88
  Extent:  205679679x2098426539x1
  Samples: 1
  Layers:  1
  Levels:  1
  Usage:   8
  Flags:   0
```
### System information
- GPU: Nvidia GTX 1070
- Driver: 418.43
- Wine version: tkg-4.3
- DXVK version: 1.0.1

### Apitrace file(s)
Note: this apitrace was recorded on computer with Windows 7 and a pretty old card with a very outdated driver (as newer ones result in BSODs). And while it loaded the main menu and prompted to start a new game just fine, it got stuck on a loading screen, so the actual gameplay wasn't traced.
https://yadi.sk/d/NjJOr6eCYUHCIQ

### Log files
- d3d11.log: [grid2_avx_d3d11.log](https://github.com/doitsujin/dxvk/files/2974933/grid2_avx_d3d11.log)
- dxgi.log: [grid2_avx_dxgi.log](https://github.com/doitsujin/dxvk/files/2974934/grid2_avx_dxgi.log)

**Comment by mrdeathjr28** [comment]
> When I launch GRID 2 from Steam (got it for free from Humble) using DXVK (tried Proton and Lutris' Windows Steam with latest DXVK), the game is stuck on a black screen. Doesn't launch with WineD3D either.
> In a d3d11 log, an interesting error pops up:
> 
> ```
> err:   D3D11: Cannot create texture:
>   Format:  88
>   Extent:  205679679x2098426539x1
>   Samples: 1
>   Layers:  1
>   Levels:  1
>   Usage:   8
>   Flags:   0
> ```
> ### System information
> * GPU: Nvidia GTX 1070
> * Driver: 418.43
> * Wine version: tkg-4.3
> * DXVK version: 1.0.1
> 
> ### Apitrace file(s)
> Note: this apitrace was recorded on computer with Windows 7 and a pretty old card with a very outdated driver (as newer ones result in BSODs). And while it loaded the main menu and prompted to start a new game just fine, it got stuck on a loading screen, so the actual gameplay wasn't traced.
> https://yadi.sk/d/NjJOr6eCYUHCIQ
> 
> ### Log files
> * d3d11.log: [grid2_avx_d3d11.log](https://github.com/doitsujin/dxvk/files/2974933/grid2_avx_d3d11.log)
> * dxgi.log: [grid2_avx_dxgi.log](https://github.com/doitsujin/dxvk/files/2974934/grid2_avx_dxgi.log)

This can be fixed with nodvd but steam only shows same error in my case

**Comment by Joshua-Ashton** [comment]
As I mentioned on Discord:

D3D11 has a max 2D texture width/height of 16384 and and 3D of 2048 w/h/d.

I have verified the behavior of this in native d3d11:
If any of the dimensions exceeds the values listed above, E_INVALIDARG is returned.

**Comment by Joshua-Ashton** [comment]
#974

**Comment by Joshua-Ashton** [comment]
Probably won't fix the issue but would mimic native behaviour better maybe? 🤷‍♂️

**Comment by ziemia** [comment]
I tried to run versions of this game from Steam (wine and proton) for a few hours, unfortunately without success.
There are several videos on Youtube that have worked (DXVK), but not from the Steam version.

https://www.youtube.com/watch?v=WKbxXebVPjw
https://www.youtube.com/watch?v=eJiAdNEp7ms

**Comment by Zeioth** [comment]
It doesn't start on my end, not in Lutris, nor in Steam+proton. I get:

    [0318/233958.239:ERROR:angle_platform_impl.cc(54)] populateRenderer11DeviceCaps(906): Error querying driver version from DXGI Adapter.

Lutris log [here](https://pastebin.com/raw/CH571Mci).
DXVK logs are empty.

Wine 4.4 + Nvidia drivers 418.49.4 but i've tested several versions.

**Comment by doitsujin** [comment]
@Zeioth that message comes from Steam, not the game.

**Comment by ziemia** [comment]
If you want to run this game (stem ver.), read this:
https://github.com/ValveSoftware/Proton/issues/1647
https://github.com/ValveSoftware/Proton/issues/753
https://www.youtube.com/watch?v=zwfCZJd56AY&feature=youtu.be

@doitsujin this is not a problem with dxvk

**Comment by Joshua-Ashton** [comment]
I think Pierre-Loup has mentioned CEG being an issue before -- not sure what the status is on that though.

**Comment by NerosTie** [comment]
Tested and it's a DRM issue:

https://www.reddit.com/r/linux_gaming/comments/cl1o6p/how_piracy_saves_pc_gaming_using_the_example_of/  

https://www.protondb.com/app/44350

Unfortunately, I'm stuck on the "check for DLC" screen, but it's not an issue with DXVK.

Can be closed.
