### ISSUE TITLE
Heroes of the Storm - switch to fullscreen is very slow, unlike borderless

### ISSUE THREAD

**Issue by aufkrawall** [doitsujin/dxvk#973]
When starting Heroes of the Storm, the screen stays black for something like 15 seconds when fullscreen mode is used. This also makes Alt + Tab insanely slow in both directions. This is inside a Plasma Xorg session without compositor. On Wayland with Xwayland, it is even worse, as the game seems to freeze completely with a black screen for an unlimited duration.

The issue doesn't appear when selecting borderless windowed mode inside the game.
The issue doesn't appear either with wined3d nor other Vulkan/D3D11 -> DXVK programs inside wine (as far as I can tell).

### Software information
It's happening for months now with various HotS, DXVK and Wine versions. It wasn't that way before, seems I unfortunately missed the optimal time frame to bisect.
I once suspected the Proton upscaling patch for wine-tkg which I always enable, but false alarm.

### System information
- GPU: RX 580
- Driver: Mesa 19 / 19.1-dev
- Wine version: wine-staging-tkg 4.4
- DXVK version: 1.0.1 (well, the latest code commit before declaring it)

### Log files
[HeroesOfTheStorm_x64_d3d11.log](https://github.com/doitsujin/dxvk/files/2975248/HeroesOfTheStorm_x64_d3d11.log)
[HeroesOfTheStorm_x64_dxgi.log](https://github.com/doitsujin/dxvk/files/2975249/HeroesOfTheStorm_x64_dxgi.log)
(`dxgi.numBackBuffers = 3` is not faulty either)

**Comment by doitsujin** [comment]
Does it *work*? If so, this is not a bug and expected behaviour.

**Comment by aufkrawall** [comment]
Yes, it happens also with Wine DXGI (and also amdvlk instead of radv).
Makes me wonder where to report this issue. Afaik it doesn't exist with proprietary Nvidia driver.

The xwayland thing is probably really totally unrelated, as minimizing the window with OGL makes it freeze to death as well.

As a side note: It works fine though in borderless mode (both wined3d and dxvk) and performance is as good as on Xorg with KWin Wayland. Alt + Tab doesn't work correctly either, but it just refuses to minimize except of freezing. Switching virtual desktops via hotkeys is a working alternative.

**Comment by aufkrawall** [comment]
Ok, wine-tkg is the culprit. I installed wine-staging from Arch repository and it doesn't show this behavior. Sorry for the inconvenience, should have checked that before.
Now to find the faulty wine patch...

**Comment by doitsujin** [comment]
heh, weird.

**Comment by aufkrawall** [comment]
Huh, it's esync (+ DXVK + Hots FSE). With `WINEESYNC=0`, Alt + Tab works as expected, while `=1` reproducibly makes it slow again (unless borderless is used).

**Comment by aufkrawall** [comment]
It has gotten fixed in wine or wine-staging, alt + tab is now always instant with esync + DXVK. It's just a few percent faster in Hitman 2 (which btw. showed the same slow alt + tab issue) though vs. esync off in a fixed CPU limited scene. But it is reliably faster than esync off, so I guess it still works as expected.

Btw: There is one more strange issue: After alt + tabbing, the GPU performance in HotS often gets reduced by a few percent (e.g. 158fps vs 150fps). I can workaround this by creating window rules in KWin to never hide the window's content, as this seems to be reproducible, and not the window focus switch.
