### ISSUE TITLE
(Origin) Need for Speed 2015 [Deluxe Edition]

### ISSUE THREAD

**Issue by Yupy** [doitsujin/dxvk#975]
I'm using Lutris with Origin installed, I installed Need for Speed 2015 but the game seems to not start at all I have also followed this issue but still seems to not work:

https://github.com/doitsujin/dxvk/issues/832

### Software information
Need for Speed 2015 Deluxe Edition

### System information
- GPU: GTX 760
- Driver: 418.43
- Wine version: Staging 4.1
- DXVK version: 1.0.1

### Log files
- d3d11.log: https://pastebin.com/Vn095fix
- dxgi.log: https://pastebin.com/Vpsm3fR6

**Comment by doitsujin** [comment]
What do you mean by "does not start at all"? What happens?

Also, does this work on wined3d?

**Comment by Yupy** [comment]
It doesen't start at all and no error is showing up, I did not tried wined3d.

**Comment by doitsujin** [comment]
Well, can you please try wined3d then? If the game doesn't launch with either implementation then there's a good chance that this isn't even a DXVK bug.

Of course an apitrace would be useful too, right now I have **nothing** to work with.

**Comment by ziemia** [comment]
I played this game (I finished it) using WINE-Staging 3.21 and DXVK.
Recently, when I tried to run it on Wine 4.1, it did not start, but I did not have time to debug.
Use the old Wine to verify.

**Comment by Yupy** [comment]
Thank you both for the replies, Looks like the game works with: tkg-protonified-3.21

The only issue it has now is the ingame music, menu music and cutscenes music and voices volume are very low and it echous.

**Comment by mozo78** [comment]
Use xact and DX9 :)

**Comment by ziemia** [comment]
With music, only with Faudio worked ok.
You can use a prepared Faudio builds. - https://github.com/Kron4ek/FAudio-Builds/

For voices in the game settings, set the stereo mixing - otherwise the voice is played on the center speaker.

**Comment by Yupy** [comment]
Got it working with Faudio, Thank you all!
