### ISSUE TITLE
Anthem: Graphical issues

### ISSUE THREAD

**Issue by cookiEoverdose** [doitsujin/dxvk#976]
In Anthem a lot of not directly lit environment pieces appear almost black. Changing graphical settings or disabling dxgi.nvapiHack has no effect. I wonder if it's DXVK related and worth investigating in your opinion or something else (driver, game bug etc.).

### Software information
Anthem 1.0.3

### System information
- GPU: RTX 2080
- Driver: 418.42.02
- Wine version: 3.21/4.3/4.4
- DXVK version: 1.0.1 

### Apitrace / Log files
- Will try to provide if worth investigating

![Anthem 2019-03-21 12-38-52](https://user-images.githubusercontent.com/19622019/54752050-04174400-4bdd-11e9-89aa-fe03a7f596a7.png)
![Anthem 2019-03-21 12-39-59](https://user-images.githubusercontent.com/19622019/54752061-10030600-4bdd-11e9-9b4a-0f2893912153.png)

**Comment by doitsujin** [comment]
How is this supposed to look on Windows, and have you tried the latest *stable* driver?

**Comment by cookiEoverdose** [comment]
I installed a stable driver and made some day/night comparison screenshots under roughly the same conditions.

Fedora 29 (Kernel 4.20)
- Driver: 418.43
- Wine: 4.4 (tkg-protonified-faudio)
- DXVK: 1.0.1
- Anthem Graphics Quality preset: Medium
- setup via Lutris
- d3d11.zeroInitWorkgroupMemory = True
- dxgi.nvapiHack = False
- d3d11.log: [Anthem_d3d11.log](https://github.com/doitsujin/dxvk/files/2993273/Anthem_d3d11.log)
- dxgi.log: [Anthem_dxgi.log](https://github.com/doitsujin/dxvk/files/2993275/Anthem_dxgi.log)

![Anthem_Fedora29_day](https://user-images.githubusercontent.com/19622019/54772583-f0cd9e00-4c07-11e9-9c40-186b7fcb1f9a.png)
![Anthem_Fedora29_night](https://user-images.githubusercontent.com/19622019/54772612-00e57d80-4c08-11e9-827c-ddc5ff3647b5.png)

Windows 7 Pro
- Driver: 419.35
- Anthem Graphics Quality preset: Medium

![Anthem_Win7_day](https://user-images.githubusercontent.com/19622019/54772724-473adc80-4c08-11e9-8cbd-49a42b7702b3.png)
![Anthem_Win7_night](https://user-images.githubusercontent.com/19622019/54772745-5457cb80-4c08-11e9-9b1c-927cfe4386c0.png)

**Comment by doitsujin** [comment]
Any chance you can record an apitrace? This doesn't look right, but it's impossible for me to debug this since I don't have the game (and to be perfectly honest, this is a game that I'll refuse to get).

**Comment by cookiEoverdose** [comment]
Sorry, I was not successful regarding the apitrace. With nvapi64 disabled I can get it start without complaining about an outdated NVIDIA driver but the title screen does not look right (almost completely in greyscale). After login and during the first loading screen it always crashes with a DirectX error.

![Bildschirmfoto von 2019-03-21 21-11-32](https://user-images.githubusercontent.com/19622019/54783493-cab4f780-4c21-11e9-82d4-d9463f9aa30a.png)

**Comment by K0bin** [comment]
Does the GTX 470 even support Vulkan?

**Comment by cookiEoverdose** [comment]
Upon looking into the wine output I also noticed apitrace loading & unloading right from the beginning. I used the latest msvc binary from [https://people.freedesktop.org/~jrfonseca/apitrace/](https://people.freedesktop.org/~jrfonseca/apitrace/). So maybe I misread the documentation.

Used call:
>WINEPREFIX=<PATH_TO_PREFIX> <PATH_TO_WINE> <PATH_TO_APITRACE_EXE> trace --api dxgi <PATH_TO_ANTHEM_EXE> &> wine.log

WINE log:
> 000b:fixme:winediag:start_process Wine Staging 4.4 is a testing version containing experimental patches.
> 000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
> wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
> 000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
> 0024:fixme:file:FindFirstFileExW flags not implemented 0x00000002
> 0024:fixme:netprofm:connection_point_Advise 0x187e18, 0x99bf4c, 0x99bfb4 - semi-stub
> 0024:fixme:netprofm:list_manager_GetConnectivity 0x187df8, 0x11dfd78
> 002f:fixme:winhttp:get_system_proxy_autoconfig_url no support on this platform
> 002f:fixme:winhttp:WinHttpDetectAutoProxyConfigUrl discovery via DHCP not supported
> 0030:fixme:toolhelp:CreateToolhelp32Snapshot Unimplemented: heap list snapshot
> 0030:fixme:toolhelp:Heap32ListFirst : stub
> **apitrace: loaded into C:\Program Files (x86)\Origin Games\Anthem\Anthem.exe**
> 003d:fixme:ver:GetCurrentPackageId (0x24f470 (nil)): stub
> **apitrace: unloaded from C:\Program Files (x86)\Origin Games\Anthem\Anthem.exe
> warning: Z:\home\user\Software\apitrace\apitrace-msvc\x64\bin\..\lib\wrappers\dxgitrace.dll was never used: application probably does not use this API**
> ....

**Comment by doitsujin** [comment]
Ah right, games re-launching themselves a dozen times before actually starting up. Fun times.

Please try this: https://github.com/doitsujin/dxvk/wiki/Common-issues#apitrace

**Comment by cookiEoverdose** [comment]
No luck getting it to run and do an apitrace (without DXVK) but the dlls in the game folder. Without the dlls and just wine-staging it starts but crashes on the first loading screen with the DX error above.

**Comment by enthalpie** [comment]
I have minor graphical issues on RADV as well, birds shimmer in neon colors, if it's raining I see rain and projectiles flieing like I was shit at and some explosions and water or mud Form a bubble when jumping in that pops up and does not look right. Same goes for a kind of eye of mordor effect, which should limit my POV but makes the screen flicker instead in red and green.
Very hard to describe. 
I upgraded my cpu now and run at a bit more fps. 
I will try to do an apitrace in the next days.

**Comment by enthalpie** [comment]
OK, I wasn't able to do a trace as well, it crashed the GPU driver on the first loading screen. After trieing to revert back, game kept crashing, so I deleted it and reinstalled. That really worked wonders, there is a new patch out today and I know have solid 60 fps in the menu and fort Tarsis and the game runs at 45 - 55 fps, so a huge performance increase on the r7 2700x and vega 64.
In the settings menu the patch has ambient occlusion auto disabled, I don't know if that did the trick but it improved massively. From 20 minutes of playing, as far as I can tell, my gfx glitches are gone, so prolly it was game related.

**Comment by cookiEoverdose** [comment]
> OK, I wasn't able to do a trace as well, it crashed the GPU driver on the first loading screen. After trieing to revert back, game kept crashing, so I deleted it and reinstalled. That really worked wonders, there is a new patch out today and I know have solid 60 fps in the menu and fort Tarsis and the game runs at 45 - 55 fps, so a huge performance increase on the r7 2700x and vega 64.
> In the settings menu the patch has ambient occlusion auto disabled, I don't know if that did the trick but it improved massively. From 20 minutes of playing, as far as I can tell, my gfx glitches are gone, so prolly it was game related.

Thank you for testing. For me the rendering issues persist even after updating the game (1.0.4) and the NVIDIA driver (418.56). I did not do a full reinstall but I verified the game files with Origin. On aiptrace attempts the game still crashes on the first loading screen with the mentioned DirectX error.

Login screen without DXVK looks like this:
![2019-03-27 22-26-57](https://user-images.githubusercontent.com/19622019/55113998-17e10f80-50e1-11e9-9541-3b0c045b0ce1.png)

**Comment by cookiEoverdose** [comment]
Not an DXVK issue: I retested it with the same wine & DXVK version previously used.
Either the driver update (430.14), intermediate game patches (1.2.0) or the upgrade to Fedora 30 fixed the rendering issues for me.
