### ISSUE TITLE
DXVK reporting Geforce 999 GTX on Radeon VII

### ISSUE THREAD

**Issue by Alexmitter** [doitsujin/dxvk#979]
Running Superposition with DXVK in wine reports that I am using a Nvidia GPU, Benchmark tries to use NVAPI.
If i remember correctly, DXVK normaly always pretend to be a AMD Card, so i found this unusual.

### Software information
Superposition Windows Version

### System information
- GPU: Radeon VII
- Driver: Mesa 19.1.0-devel - padoka PPA
- Wine version: 4.4 Staging
- DXVK version: 1.0.1

https://pastebin.com/RKYABGSe

**Comment by doitsujin** [comment]
Disable NVAPI.
