### ISSUE TITLE
setup_dxvk.sh: add an option not relying on staging dll-overrides

### ISSUE THREAD

**Issue by ssorgatem** [doitsujin/dxvk#98]
Since https://github.com/doitsujin/dxvk/tree/1a0a924c7d6d9f3eed5796ab6a63f2cb2353d325 (from https://github.com/doitsujin/dxvk/pull/57) the setup script no longer works outside wine-staging, that is, it doesn't work with wine-vulkan or its future (hopelly) merged changed into mainline wine.

I know there are several approaches for this and has drawbacks... but even if the scripts need to be called each time wine is updated, that's better than now (and it's not going to be updated often in most cases, anyway).

Thoughts?

(Does tagging usernames work here? @Raffarti )

**Comment by Raffarti** [comment]
You got a little confused here, it only support *overrides* not *redirections*. The whole purpose of it was to support wine-vulkan (overrides are the builtin/native switches which are of course supported in all wine versions).
Tagging works fine.
