### ISSUE TITLE
Missing dll version properties

### ISSUE THREAD

**Issue by zzhiyi** [doitsujin/dxvk#980]
Currently the generated dlls doesn't contain any version properties. You can check it on Windows via right checks and choose properties and then details. On Linux, you can also check it via exiftools and see that version properties are missing.  

Some games check for the version of d3d dlls at start. Please see https://github.com/ValveSoftware/Proton/issues/2393 for details.

Related link: https://www.transmissionzero.co.uk/computing/building-dlls-with-mingw/  #Adding Version Information and Comments to your DLL shows how to add version information to dlls.

**Comment by doitsujin** [comment]
What exactly do these games check for and what information would the DXVK DLLs need to provide?

**Comment by Joshua-Ashton** [comment]
The meta data inside the dll provided by the .rc

Here is the .rc of a d3d11 dll https://hastebin.com/vefovefowu.bash

**Comment by SveSop** [comment]
You can have a look at the various .rc files in the wine source.
Wine's "version.rc" attached.
[version.rc.gz](https://github.com/doitsujin/dxvk/files/3005553/version.rc.gz)

**Comment by SveSop** [comment]
Looking at the [https://www.transmissionzero.co.uk/computing/building-dlls-with-mingw/](https://www.transmissionzero.co.uk/computing/building-dlls-with-mingw/) i guess the d3d11 version.rc file could be something like i attach here. I can use windres on it, and link it to the d3d11.dll.

Probably not a good idea to use "CompanyName: Microsoft" on it tho, cos of possibly legal issues, depending on WHAT the game actually checks this should be no problem? Ie. if its version only, i see no issues keeping a "windows dll version" as long as the other stuff is changed?

Anyway, i have been stabbing around in total darkness trying to figure out how meson can build this file with windres `x86_64-w64-mingw32-windres`, but i dont have a clue how to achieve this as im a total meson n00b.
Supposedly its to use some `windows.compile_resources()`, but "windows" is a unknown thing, and i dont know how to fiddle with that.

Attaching a suggestion to version.rc file from the info posted earlier.
[version.rc.gz](https://github.com/doitsujin/dxvk/files/3026000/version.rc.gz)

**Comment by zzhiyi** [comment]
In wine, there is `VALUE "CompanyName", "Microsoft Corporation" /* GameGuard depends on this */`. So some anti-cheat toolkit check for Microsoft as well. I don't know if it's safe for dxvk although regarding the legal issues.

**Comment by zzhiyi** [comment]
> What exactly do these games check for and what information would the DXVK DLLs need to provide? I'm not familiar with Windows DLL versioning.

For now. Just the usual version information  present in dlls is fine. We don't have to use "Microsoft" etc. The game just need some version so it doesn't fail. We probably want to keep the version the same as Windows though.

**Comment by dhewg** [comment]
For doing that with meson and winelib you could have a look at:
https://github.com/iXit/wine-nine-standalone/blob/master/meson.build#L51
https://github.com/iXit/wine-nine-standalone/blob/master/d3d9-nine/meson.build#L3
https://github.com/iXit/wine-nine-standalone/blob/master/d3d9-nine/version.rc

**Comment by SveSop** [comment]
@dhewg 
Quick glance on a couple of those links and i got a couple of ideas to try :)

Thx.

**Comment by SveSop** [comment]
@dhewg Thanks for the tips! Was able to make that work, but since DXVK currently do not create the "fakedlls" when building winelib, so i disabled this "function" for the dll.so's.

@doitsujin Created a PR: https://github.com/doitsujin/dxvk/pull/993
Take a look at see if its of any use.

Example: (The "real" is to the left)
![dll_version](https://user-images.githubusercontent.com/33990277/55412091-11cab300-5567-11e9-8917-11c6e6be0481.jpg)

**Comment by doitsujin** [comment]
Can anyone test if #993 fixes Shattered Horizon? If so, does it still work when **removing** both the "Copyright", "Company Name" and "Product Name" lines?

I'm concerned about the legal implications of slapping the Microsoft name onto the project, even if it is required for certain applications to work.

**Comment by zzhiyi** [comment]
> Can anyone test if #993 fixes Shattered Horizon? If so, does it still work when **removing** the "Copyright", "Company Name" and "Product Name" lines?
> 
> I'm concerned about the legal implications of slapping the Microsoft name onto the project, even if it is required for certain applications to work.

I will test it.

**Comment by SveSop** [comment]
Copyright should possibly be: "zlib/libpng license"? (The project license)?

**Comment by zzhiyi** [comment]
#993 Fixed the Shattered Horizon. Removing "Copyright", "Company Name" and "Product Name" lines also works. But I would rather keep them and use "DXVK Project" for example.

**Comment by doitsujin** [comment]
Alright, thanks. Will do something like that then.

**Comment by SveSop** [comment]
Made a push to my fork that builds "fake_dlls" if you build `--winelib` with the aforementioned versioning.

If that can be of any use, although i don't really see it, you kinda need to overwrite wine dll.so's and fakedll's with these, so that you would use it without dll overrides or anything, kinda like if it was "native wine".

As i said, dunno if it is worth the trouble for dll versioning? Anyway, for lulz and gigglez i guess:
[https://github.com/SveSop/dxvk/commit/7632ffb1dac52347f14c2a4d1ced4776d6e28b7d](https://github.com/SveSop/dxvk/commit/7632ffb1dac52347f14c2a4d1ced4776d6e28b7d)

**Comment by sl1pkn07** [comment]
@SveSop not is need remove the dll.so and fakedlls in the installation. i only change the dlls in the prefix pointed to the dxvk fakedlls, without any dll override. this works (at least, the triangle test)

~~~
yaourt -Ql sl1-dxvk-git
--snip--
sl1-dxvk-git /usr/lib/
sl1-dxvk-git /usr/lib/dxvk/
sl1-dxvk-git /usr/lib/dxvk/d3d10.dll.so
sl1-dxvk-git /usr/lib/dxvk/d3d10_1.dll.so
sl1-dxvk-git /usr/lib/dxvk/d3d10core.dll.so
sl1-dxvk-git /usr/lib/dxvk/d3d11.dll.so
sl1-dxvk-git /usr/lib/dxvk/dxgi.dll.so
sl1-dxvk-git /usr/lib/dxvk/fakedlls/
sl1-dxvk-git /usr/lib/dxvk/fakedlls/d3d10.dll
sl1-dxvk-git /usr/lib/dxvk/fakedlls/d3d10_1.dll
sl1-dxvk-git /usr/lib/dxvk/fakedlls/d3d10core.dll
sl1-dxvk-git /usr/lib/dxvk/fakedlls/d3d11.dll
sl1-dxvk-git /usr/lib/dxvk/fakedlls/dxgi.dll
sl1-dxvk-git /usr/lib32/
sl1-dxvk-git /usr/lib32/dxvk/
sl1-dxvk-git /usr/lib32/dxvk/d3d10.dll.so
sl1-dxvk-git /usr/lib32/dxvk/d3d10_1.dll.so
sl1-dxvk-git /usr/lib32/dxvk/d3d10core.dll.so
sl1-dxvk-git /usr/lib32/dxvk/d3d11.dll.so
sl1-dxvk-git /usr/lib32/dxvk/dxgi.dll.so
sl1-dxvk-git /usr/lib32/dxvk/fakedlls/
sl1-dxvk-git /usr/lib32/dxvk/fakedlls/d3d10.dll
sl1-dxvk-git /usr/lib32/dxvk/fakedlls/d3d10_1.dll
sl1-dxvk-git /usr/lib32/dxvk/fakedlls/d3d10core.dll
sl1-dxvk-git /usr/lib32/dxvk/fakedlls/d3d11.dll
sl1-dxvk-git /usr/lib32/dxvk/fakedlls/dxgi.dll
--snip--
~~~

~~~
└───╼  ls .wine/drive_c/windows/system32/d*dll
-rw-r--r-- 1 sl1pkn07 users    4016 abr  1 20:54 .wine/drive_c/windows/system32/d2d1.dll
lrwxrwxrwx 1 sl1pkn07 users      34 abr  4 20:10 .wine/drive_c/windows/system32/d3d10_1.dll -> /usr/lib/dxvk/fakedlls/d3d10_1.dll
lrwxrwxrwx 1 sl1pkn07 users      36 abr  4 20:10 .wine/drive_c/windows/system32/d3d10core.dll -> /usr/lib/dxvk/fakedlls/d3d10core.dll
lrwxrwxrwx 1 sl1pkn07 users      32 abr  4 20:10 .wine/drive_c/windows/system32/d3d10.dll -> /usr/lib/dxvk/fakedlls/d3d10.dll
lrwxrwxrwx 1 sl1pkn07 users      32 abr  4 20:10 .wine/drive_c/windows/system32/d3d11.dll -> /usr/lib/dxvk/fakedlls/d3d11.dll
--snip--
lrwxrwxrwx 1 sl1pkn07 users      31 abr  4 20:10 .wine/drive_c/windows/system32/dxgi.dll -> /usr/lib/dxvk/fakedlls/dxgi.dll
--snip--
~~~

**Comment by SveSop** [comment]
[https://github.com/doitsujin/dxvk/pull/993#issuecomment-480177025](https://github.com/doitsujin/dxvk/pull/993#issuecomment-480177025)

**Comment by 29039** [comment]
Hi, is it possible as part of the build process to add the actual DXVK Version & Arch into the version properties? Knowing that you have the wrong or outdated DLL can sometimes be a bit tricky.

I understand that compatibility issues are at play, perhaps use the LegalTrademarks property, i.e. "DXVK, version: x32 v2.5.2" 

Would make troubleshooting much simpler.

Thanks!
