### ISSUE TITLE
The Witcher 3. Disappeared doppler face texture

### ISSUE THREAD

**Issue by kergalym** [doitsujin/dxvk#983]
Hi!

When playing a quest "Pyres of Novigrad" I noticed that texture of doppler's face is missed.
Sorry if that submitting is duplicate, I'm new here.
I would be glad to get his face back :)

Comparison:
Win10: Correct
![witcher3_win10](https://user-images.githubusercontent.com/9489149/55164144-5b955100-5195-11e9-8323-76a6467574f8.jpeg)
DXVK: Incorrect
![witcher3_dxvk](https://user-images.githubusercontent.com/9489149/55164145-5b955100-5195-11e9-96d5-32dc2a3fcc3f.jpeg)

information
- GPU: NVIDIA 1050Ti
- Driver: 410.73
- Wine version: 4.0
- DXVK version: 1.01 

### Log files
[witcher3_dxgi.log](https://github.com/doitsujin/dxvk/files/3018281/witcher3_dxgi.log)
[witcher3_d3d11.log](https://github.com/doitsujin/dxvk/files/3018282/witcher3_d3d11.log)

**Comment by doitsujin** [comment]
Your graphics driver doesn't support `VK_EXT_transform_feedback`, which is required for this game to render correctly. Please update to a 415-series or 418-series driver.
