### ISSUE TITLE
Lords of the Fallen missing objects after Mesa + DXVK upgrade

### ISSUE THREAD

**Issue by ziabice** [doitsujin/dxvk#985]
Sorry to bother, but I can't understand if this is a Mesa problem or DXVK.

I'm using Manjaro Linux, and this game was running well with Mesa 18.3.5, LLVM 7.0.1, DXVK 1.0 and Wine-staging-nine 4.1.

I did a system upgrade that brought Mesa 19.0.1, LLVM 7.0.1, DXVK 1.0.1, but wine-staging-nine was not upgraded.

Since this upgrade I can't see object, enemies or buildings in game. The problem is visually exactly the same as described in #285 .

### Software information
Lords Of The Fallen (GOG Version)

### System information
- GPU: AMD RX 580 4 GB
- Driver: Mesa 19.0.1/LLVM 7.0.1
- Wine version: wine-staging-nine 4.1
- DXVK version: 1.0.1

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log: 
[LordsOfTheFallen_d3d11.log](https://github.com/doitsujin/dxvk/files/3024685/LordsOfTheFallen_d3d11.log)

- dxgi.log:

**Comment by Oschowa** [comment]
This is a mesa regression and fixed in git master. AFAIK it only affects the 19.0.1 stable release, 19.0 should be fine.

**Comment by doitsujin** [comment]
Already [fixed](https://cgit.freedesktop.org/mesa/mesa/commit/?id=62a9d757e6074215c145c9637014d9acb16d865d) in mesa. There is no DXVK workaround, so you're going to have to compile for yourself for now or revert to Mesa 19.0.0.

**Comment by ziabice** [comment]
Thank you all a lot, I'll notify my distro maintainers of the problem! ;)

**Comment by Faalagorn** [comment]
Thanks for the info! Seems the same was affecting Esacpe from Tarkov windows reflection on Factory, right now I'm running with RADV_DEBUG=nohiz until mesa-git get updated in unofficial arch repo.
