### ISSUE TITLE
poor performance on sherlock holmes devil's daugther

### ISSUE THREAD

**Issue by Macribit** [doitsujin/dxvk#986]
### Software information
Sherlock Holmes Devil's daughter

### System information
- GPU: amd gigabyte rx460 4gb
- Driver: mesa 19.0.1
- Wine version: Proton 4.2
- DXVK version: 1.0.1
- CPU: Ryzen 1600
- Ram: 12gb ddr4 2400mhz

### Apitrace file(s)
https://drive.google.com/file/d/1LjQPajXke2s8_GT5Nf92RQWwY0xajyje/view?usp=sharing

### Log files
- d3d11.log: https://drive.google.com/file/d/1-1VGGWcT_1_5Mcx7cwY0YT7aifkAZljz/view?usp=sharing
- dxgi.log: https://drive.google.com/file/d/1kKwWEi5HGEbE7EyqUsyi8VzN6NmYRETJ/view?usp=sharing

**Comment by doitsujin** [comment]
And what exactly is "poor performance"?

**Comment by Macribit** [comment]
steam version doesn't work cause of denuvo you need gog version.

**Comment by Macribit** [comment]
> And what exactly is "poor performance"?

freezes, lags

**Comment by doitsujin** [comment]
This is completely normal as long as new shaders are being compiled, and not a bug.

**Comment by Macribit** [comment]
*up

> This is completely normal as long as new shaders are being compiled, and not a bug.

too bad is barely playable but to be fair it happens with other games like shadow of the tomb raider with my system, maybe I need a more powerful gpu. closing.

**Comment by doitsujin** [comment]
Some games are worse than others, Shadow of the Tomb Raider is also known for being problematic due to the sheer number of different shaders it has. There's no reasonable way to fix this unfortunately.

**Comment by Macribit** [comment]
> Some games are worse than others, Shadow of the Tomb Raider is also known for being problematic due to the sheer number of different shaders it has. There's no reasonable way to fix this unfortunately.

I could try using AMDVLK driver instead, would that help?

**Comment by doitsujin** [comment]
Not really. The proprietary driver is a bit faster, but also has issues with a lot of games (including SotTR).
