### ISSUE TITLE
Moto Racer 4 launches up to menu and screen stays black..

### ISSUE THREAD

**Issue by oscarbg** [doitsujin/dxvk#99]
Seems uses Unreal Engine 4.16.2 and from logs unique error is:
err:   D3D11: ClearUnorderedAccessViewUint: Not supported for buffers
searching issues list I see this is needed also for Rise of Tomb Raider altough Moto Racer may only need this to work correctly..(?)

### System information
- GPU: Vega
- Driver: 18.1.1
- Wine version: none
- DXVK version: up to https://github.com/doitsujin/dxvk/commit/8813ff979a49d2ae0ae3e6d1a88ad0ac12d48993

### Log files
[Racer-Win64-Shipping_d3d11.log](https://github.com/doitsujin/dxvk/files/1753638/Racer-Win64-Shipping_d3d11.log)
[Racer-Win64-Shipping_dxgi.log](https://github.com/doitsujin/dxvk/files/1753639/Racer-Win64-Shipping_dxgi.log)

**Comment by doitsujin** [comment]
Please retest since `ClearUnorderedAccessViewUint` is now partially supported for buffer resources.

Keep in mind that Vega GPUs are currently not supported due to the dire driver situation. An apitrace would be useful.

**Comment by doitsujin** [comment]
Closing due to lack of feedback. Please re-open if this is still an issue.
