### ISSUE TITLE
MTGA fails to start with an error message

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [doitsujin/dxvk#992]
Magic the Gathering Arena fails to start with this error message:

![Error_001](https://user-images.githubusercontent.com/29783425/55351322-4a628200-54be-11e9-8fec-bba5d3473bb4.png)

and the same error message happened with me before with other two unity games on Linux Mint 19.1, Ubuntu 18.04, and Ubuntu 18.10. These games are Cuphead, and Ori and the Blind Forest DE. I found a few errors/warnings in dxgi.log. That is why I posted this issue here.

### Software information
Magic the Gathering Arena

### System information
- GPU: AMD HD 8750M.
- Driver: Mesa 19.0.1 (Padoka PPA)
- Wine version: Wine-staging 4.5
- DXVK version: 1.0.2

### Log files
- d3d11.log:  The file is empty.
- dxgi.log: 
[MTGA_dxgi.log](https://github.com/doitsujin/dxvk/files/3030892/MTGA_dxgi.log)

**Comment by doitsujin** [comment]
```
info:  Required Vulkan extension VK_KHR_get_physical_device_properties2 not supported
info:  Required Vulkan extension VK_KHR_surface not supported
info:  Required Vulkan extension VK_KHR_win32_surface not supported
```

As usual, your Vulkan setup is broken. Please make sure you can run both 32-bit and 64-bit Vulkan apps before reporting issues.

**Comment by ahmed-elsayed2017** [comment]
Ops! I installed libvulkan1:i386, and forget to install mesa-vulkan-drivers:i386. They can't be found in Synaptic package manager, I had to install them manually from the terminal. The game doesn't run anyway (wine bug). Thanks, and sorry about.
