### ISSUE TITLE
release-1.0 new way to track dxvk source releases?

### ISSUE THREAD

**Issue by bobwya** [doitsujin/dxvk#995]
I see that the **master** branch is no longer tracking dxvk releases.
Is the **release-1.0** branch the accepted way to track newer releases?

I am asking with reference to the **winetricks dxvk** verb.
This currently uses the **RELEASE** file, to obtain the current release.

Thanks

**Comment by doitsujin** [comment]
Hm, yeah, I can see why this is an issue. `release-1.0` has diverged from `master` and only receives cherry-picked bug fixes. `master` will at some point (soon-ish) turn into 1.1.

Would it be useful if I maintained a `latest-release` branch that always points to the latest tagged release, and thus always contains an up-to-date `RELEASE` file? I'd just force-push to it whenever tagging a new one.

**Comment by bobwya** [comment]
KISS! So yeah, a `latest-release` branch would be cool.
Thanks! :-)

**Comment by austin987** [comment]
A latest-release branch would work, but I'm not clear on why that couldn't be done in master instead?

I have two concerns with that approach.
1) you might forget to update the service branch
2) if there's 1.0, 1.0.1 and 1.1, then you tag 1.0.2, what's the latest? IMO it's 1.1, but it's unclear from your comment which it would be.

Anyway, as long at there's a file we can query in plain text, we can make it work 😀

**Comment by phush0** [comment]
Release can be done by tagging point release. Then with git it is simple.

**Comment by doitsujin** [comment]
@austin987 because having a commit "Release 1.0.2" in the master branch which has nothing to do with Release 1.0.2 is a bit weird, to say the least.

@phush0 What do you mean? Releases are already tagged.

**Comment by doitsujin** [comment]
@bobwya Branch is up: https://github.com/doitsujin/dxvk/tree/latest-release

**Comment by phush0** [comment]
Never mind, my misunderstanding of the problem.

**Comment by bobwya** [comment]
Thanks, that's great!

**Comment by austin987** [comment]
@doitsujin, I agree. Do you plan to tag 1.0.2 in latest-release, after 1.1.0? That's what I'm trying to understand/avoid.

**Comment by austin987** [comment]
Saw edit, that works, thanks!

**Comment by doitsujin** [comment]
Before anyone complains: I'm not going to update that branch to 1.1, that release turned out to be a failure pretty much immediately.

**Comment by dhewg** [comment]
You can just use the github api to get the latest release:
https://api.github.com/repos/doitsujin/dxvk/releases/latest

It's what I'm doing for the `galliumnine` verb already. For exactly that reason, there's no need to rely on any commited file, branch or whatever.
