### ISSUE TITLE
Space Engineers(244850) Stutter

### ISSUE THREAD

**Issue by Linux74656** [doitsujin/dxvk#998]
We have been trying to get Space Engineers to run stably with mixed results. The main issue we have now is that, no matter what you do in the game their are constant but very brief lag spikes, that persist throughout gameplay, even while floating motionless on an empty map. We have been trying to pin the cause down without any luck. 
I am not entirely sure if the lag is caused by the gpu/cpu or a combination of both.
Perhaps you can look at the attached trace files and see what the is causing the stutter, and confirm if it has something to do with DXVK or WINED3D, or if this issue is unrelated.

The relevant thread for our other discussion on this is here: https://github.com/ValveSoftware/Proton/issues/1792

### Software information
Game: Space Engineers

### System information
- GPU: Nvidia Asus Strix GTX 960 2GB
- Driver: Nvidia proprietary 418.56
- Wine version: Proton 4.2-2 (Also tried in wine staging )
- DXVK version: 1.0.2

### Apitrace file(s)

https://drive.google.com/open?id=1XtQ9-xEv_2fX8myNpk7gNLhxuPvIieAu
Some information that might be relevant. The game starts and empty world(with some asteroids) at about 40 seconds after the main menu. And at about 1:15 i place a few blocks with creative mode which causes more of the heavy stuttering for a short time.

### Log files
Not Applicable / No Crash

**Comment by doitsujin** [comment]
Looking at your apitrace, this is just the regular stutter caused by shader compilation, as it goes away on the second run. It's normal in all games, just more noticeable in some than others, and cannot be fixed.

**Comment by Linux74656** [comment]
I think I may not have been a bit confusing in my initial explanation of the problem, sorry about that. 
The issue players are having is not with the lag caused when placing blocks. It is the constant 'microlags' that take place even in a completely empty world.(See image)
![20190405110539_1](https://user-images.githubusercontent.com/49169170/55637884-090af480-5794-11e9-86c5-d1befc01423a.jpg)

When there is a red spike on the graph, the entire game pauses for a fraction of a second. It happens in the game no matter what. In the image above, the map is completely empty, no asteroids, no grids.(Only the Character, sun, and Skybox should exists.)

**Comment by doitsujin** [comment]
Looks like this on my end:
![Bildschirmfoto-659](https://user-images.githubusercontent.com/25567304/55640616-4ee3af00-57cc-11e9-86ba-b71749a60f86.png)

Given that the game does barely any rendering, I think it's safe to assume that this isn't a DXVK issue.

**Comment by Linux74656** [comment]
So you are not experiencing this stutter at all? It most definitely is not DXVK then.

Thank you very much for helping us narrow this down a little further.

**Comment by doitsujin** [comment]
I don't have the game, all I did is replay your apitrace.

**Comment by Linux74656** [comment]
OK well thank you again. You have been very helpful.

I will close this as not the issue.
