### ISSUE TITLE
Warframe Crash on Startup after Warframe version 24.6.0

### ISSUE THREAD

**Issue by jnelen22** [doitsujin/dxvk#999]
After the recent Plains of Ediolon update the game now immediately crashes on startup after the initial loading screen. Prior to the update the game on crashes sparingly on random occasions.

### Software information
Warframe

Default Ultra Settings

### System information
- GPU: RX Vega 64
- Driver: Mesa 19.1.0-devel (git-b2d651b862)
- Wine version: wine-staging 4.4
- DXVK version: 1.0.1

### Apitrace file(s)
https://mega.nz/#!tIFkCYhZ!mOejq1mhbR0cGLF20r_bgHbcvSpaXJyYwyKo8R_K2Ug

### Log files
- d3d11.log:
[Warframe.x64_d3d11.log](https://github.com/doitsujin/dxvk/files/3046742/Warframe.x64_d3d11.log)

- dxgi.log: 
[Warframe.x64_dxgi.log](https://github.com/doitsujin/dxvk/files/3046744/Warframe.x64_dxgi.log)

Here are the last lines the game output before crashing if that helps.
[crashmessage.txt](https://github.com/doitsujin/dxvk/files/3046754/crashmessage.txt)

**Comment by doitsujin** [comment]
The apitrace doesn't seem to be all that useful, it crashes when replaying it even on Windows. Was this recorded on Linux? If so, and if possible, please use Windows to do that.

Obligatory questions:
- Does this game still work with wined3d / are you 100% sure it's DXVK's fault and not Wine's?
- Can you post info from the crash dialogue that Wine should show?

**Comment by jnelen22** [comment]
Yes the game works with wined3d besides some performance and graphical glitches it works just fine.

Unfortunately, wine doesn't give me a crash dialog when it crashes, instead the Warframe crash handler pops up instead, and frustratingly it doesn't leave a crashlog or at least not one I can find.

Yes the Apitrace was made on Linux. I'm sorry but I don't have the ability to test this on windows. I unfortunately don't own a copy of any windows version and do not have another PC capable of running the game.

I'm sorry I can't be more helpful. Let me know what else I can do I will try to assist with the best of my ability.

**Comment by doitsujin** [comment]
I'd test the game on my end if I could get it to work, but I wasn't able to.

I received some reports that the game still works fine for them, though.

**Comment by jnelen22** [comment]
Since closing the game after the API trace (which took several hours) the game updated to 24.6.1 and now seems to run perfectly fine. I don't know why this is. This is rather confusing. It appears the something done in the hotfix fixed whatever the problem was.

I am so sorry for wasting your time but it seems the issue has suddenly resolved it's self. Closing this issue.
